### PR TITLE
asroute 0.1.0 (new formula)

### PR DESCRIPTION
**Pull request by stevenpack**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by stevenpack** [comment]
HI team, just saw the CI pipeline fail on "repo too new < 30 days". I hadn't realized that, I thought it was only minimum 50 stars (I have 95). Will close and reopen after 30 days.

**Comment by stevenpack** [comment]
Reopening now repo > 30 days

**Comment by stevenpack** [comment]
Reopening as test failure looked transient - just doing a git pull

**Comment by alebcay** [comment]
Our CI infrastructure is currently having a tough time 🧯 - expect failure for now, and we'll re-fire the tests when everything comes back up. 🚀

**Pull request closed without merging**
