### PR TITLE
imagemagick: add heic support

### PR DESCRIPTION
**Pull request by EkilDeew**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @EkilDeew

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by hjmallon** [comment]
Does this sort of change require a new `revision` in the formula to force an update and a new bottle? Or will that happen automatically?

**Comment by fxcoudert** [comment]
Once this is merged, users will get it by reinstalling or at the next update.

**Comment by fxcoudert** [comment]
Thanks @EkilDeew

**Pull request closed without merging**
