### PR TITLE
monkeysphere: revision bump (perl shebang fix)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes CI failure seen in #77228 and various other PRs.

See https://github.com/Homebrew/brew/pull/11286.

### CODE REVIEW

**Comment by carlocab** [comment]
Mojave and Catalina are audit failures for using `http` rather than `https`.

On Big Sur:
```
An exception occurred within a child process:
  Minitest::Assertion: Expected /We\ need\ at\ least/ to match "dyld: missing lazy symbol called\n".
```

On ARM:
```
Error: monkeysphere: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /We\ need\ at\ least/ to match "Can't load '/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle' for module Crypt::OpenSSL::RSA: dlopen(/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle, 0x0001): symbol '_ERR_load_crypto_strings' not found, expected in flat namespace by '/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle' at /System/Library/Perl/5.30/XSLoader.pm line 96.\n\u0000 at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/Crypt/OpenSSL/RSA.pm line 14.\nCompilation failed in require at /opt/homebrew/Cellar/monkeysphere/0.44_4/bin/openpgp2pem line 54.\nBEGIN failed--compilation aborted at /opt/homebrew/Cellar/monkeysphere/0.44_4/bin/openpgp2pem line 54.\n".
```

Ideas, @Bo98?

**Comment by carlocab** [comment]
License ref: https://metadata.ftp-master.debian.org/changelogs//main/m/monkeysphere/monkeysphere_0.44-1_copyright

**Comment by Bo98** [comment]
What's the output of `otool -L /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle` and `file /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle`?

**Comment by carlocab** [comment]
```
❯ otool -L /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle
/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
❯ file /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle
/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64e:Mach-O 64-bit bundle arm64e]
/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle (for architecture x86_64):        Mach-O 64-bit bundle x86_64
/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle (for architecture arm64e):        Mach-O 64-bit bundle arm64e
```

**Comment by Bo98** [comment]
uhh why is it not linking to libssl and libcrypto?

**Comment by Bo98** [comment]
Is the 5.28 bundle the same?

**Comment by carlocab** [comment]
```
❯ otool -L /System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle
/System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
❯ file /System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle
/System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64e:Mach-O 64-bit bundle arm64e]
/System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle (for architecture x86_64):        Mach-O 64-bit bundle x86_64
/System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle (for architecture arm64e):        Mach-O 64-bit bundle arm64e
```

**Comment by carlocab** [comment]
5.18 is though:
```
❯ otool -L /System/Library/Perl/Extras/**/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle
/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle:
        /usr/lib/libssl.46.dylib (compatibility version 47.0.0, current version 47.1.0)
        /usr/lib/libcrypto.44.dylib (compatibility version 45.0.0, current version 45.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
/System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/RSA/RSA.bundle:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

**Comment by carlocab** [comment]
macOS `perl` seems broken 🙃

**Comment by Bo98** [comment]
I guess I'm writing a bug report tomorrow.

Resourcing `Crypt::OpenSSL::RSA` is a potential workaround.

**Comment by Bo98** [comment]
Did this regress in 11.3 or something? We managed to build a bottle before and we definitely weren't using 5.18 to do that.

**Pull request closed without merging**
