### PR TITLE
libpng 1.6.35

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
http://www.libpng.org/pub/png/libpng.html

Not released yet.

**Comment by lembacon** [comment]
It has now been released.

**Comment by ilovezfs** [comment]
I guess my ping worked! https://sourceforge.net/p/libpng/bugs/283/#9c98

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
