### PR TITLE
coq: update test

### PR DESCRIPTION
**Pull request by tchajed**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The `omega` tactic is deprecated, producing a warning when compiling the old test. It might stop working at some point so better to just switch to `lia` in the test.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Why does`math-comp` need to be rebuilt when you've only changed `coq`'s test?

**Comment by chenrui333** [comment]
yeah, agree you dont have to bump `math-comp` since only coq test was touched.

**Comment by tchajed** [comment]
This CI failure appears to be due to math-comp expecting a different Coq: https://github.com/Homebrew/homebrew-core/runs/1675519267.

I'm also surprised, but I've never checked exactly how Coq determines interface compatibility.

**Comment by chenrui333** [comment]
I see, it looks like when `math-comp` formula got regression tested, it directly reference the `coq` test suite

```
==> /usr/local/opt/coq/bin/coqc -R /usr/local/Cellar/math-comp/1.12.0_2/lib/coq/user-contrib/mathcomp mathcomp testing.v
File "./testing.v", line 1, characters 0-43:
Error:
Compiled library mathcomp.ssreflect.ssreflect (in file /usr/local/Cellar/math-comp/1.12.0_2/lib/coq/user-contrib/mathcomp/ssreflect/ssreflect.vo) makes inconsistent assumptions over library Coq.Init.Ltac
```

**Comment by carlocab** [comment]
But this should have changed nothing about how `coq` was compiled... unless `coq` compiles non-deterministically, and `math-comp` depends on those non-deterministic changes? Because that would be annoying.

**Comment by chenrui333** [comment]
let me run it in my local first.

**Comment by chenrui333** [comment]
My hunch is because of the `coq` test change and the formula got rebuilt, as result, the object hash got regenerated for the ocaml objects (don't know how to run `ocamlobjinfo` to assert that), and then `math-comp` is using different ocaml interface than the one that coq is using? So revision bump is needed for math-comp to make them consistent.

I can also reproduce the `math-comp` test failure by bumping the revision for `coq`. And has received the same result as for the test change for `math-comp`.

So from my perspective, it seems like we need to better understand ocaml objects (sorry, I am not ocaml programmer), and the revision for `math-comp` is certainly needed in this PR.

Let me know if that makes sense.

**Review by carlocab — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@tchajed, since you are ocaml developer, can you run the `ocamlobjinfo` before and after the `math-comp` revision bump for `/usr/local/Cellar/math-comp/1.12.0_2/lib/coq/user-contrib/mathcomp/ssreflect/ssreflect.vo`?

**Comment by tchajed** [comment]
> Let me know if that makes sense.

I think what you said makes sense, @chenrui333, except that it's mostly Coq object files involved and not OCaml. The version of OCaml itself also matters since Coq plugins directly interface with the OCaml API, and OCaml isn't binary compatible between minor versions.

It's very generous to call me an OCaml developer, other than some light hacking on the Coq compiler, but I am a Coq developer. In any case that `vo` file is a Coq output file. It probably has some hash recording what interface it expects from the modules it depends on, but I don't know the binary format to be able to find that information (and Coq doesn't ship with any tools for this purpose, like `objdump` or `ocamlobjinfo`).

**Comment by chenrui333** [comment]
Yeah, I think `ocamlobjinfo` is a ocaml object inspector tool. I was not sure if we can use that to inspect `vo` files, looks like we cannot. But thanks for the explanations, that is helpful for our [OCaml PR](https://github.com/Homebrew/homebrew-core/pull/67721) as well.

**Pull request closed without merging**
