### PR TITLE
menhir 20220210

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2021-12-07T05:14:52.6310320Z [34m==>[0m [1mbrew audit menhir --online --git --skip-style[0m
2021-12-07T05:15:00.0439430Z [31m==>[0m [1m[31mFAILED[0m[0m
2021-12-07T05:15:00.0457710Z ##[group]Full audit menhir --online --git --skip-style output
2021-12-07T05:15:00.0458480Z menhir:
2021-12-07T05:15:00.0458900Z   * Libraries were compiled with a flat namespace.
2021-12-07T05:15:00.0459510Z     This can cause linker errors due to name collisions, and
2021-12-07T05:15:00.0460390Z     is often due to a bug in detecting the macOS version.
2021-12-07T05:15:00.0461020Z       /opt/homebrew/Cellar/menhir/20211128/lib/menhirLib/menhirLib.cmxs
2021-12-07T05:15:00.0461660Z       /opt/homebrew/Cellar/menhir/20211128/lib/menhirSdk/menhirSdk.cmxs
```

**Comment by pthariensflame** [comment]
Oh gosh.  :/

**Comment by pthariensflame** [comment]
Can someone add the `help wanted` label here?  I don't have that power.

**Comment by iMichka** [comment]
The `-flat_namespace` is probably set somewhere during the build. Don't know where though. It might come through one of the dependencies.

**Comment by iMichka** [comment]
Can you look at the full logs, `-flat_namespace` must be coming from somewhere. I don't see it in the `menhir` source code, it might come through `ocaml` or `dune` ?

**Comment by cho-m** [comment]
Interesting that it doesn't impact Monterey. I was having trouble reproducing locally due to this. 

As a guess, maybe rebuilding `ocaml` might help since our Monterey & Linux `ocaml` bottles are newer than the previous macOS bottles.

Can also re-explore `ocaml` v4.13.1 PR #87856

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
