### PR TITLE
 logtalk: update 3.09.0 bottle.

### PR DESCRIPTION
**Pull request by pmoura**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Duplicates https://github.com/Homebrew/homebrew-core/pull/7313 but I'll close mine in favor of this PR.

**Comment by pmoura** [comment]
@ilovezfs Oops! Somehow I missed it. So sorry.

**Comment by ilovezfs** [comment]
It's no problem at. Here's how I check for duplicates:
https://github.com/Homebrew/homebrew-core/pull/4763#issuecomment-246596997

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `logtalk 3.09.0`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
