### PR TITLE
libsvm 3.22

### PR DESCRIPTION
**Pull request by woodruffw**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
We should mirror this or find a mirror so it doesn't happen again

**Comment by woodruffw** [comment]
Yeah, I'll look for one.

**Comment by woodruffw** [comment]
Well, his GitHub mirror has [releases] but they don't match the ones published on this site...

```bash
$ sha256sum v322.tar.gz 
a3469436f795bb3f8b1e65ea761e14e5599ec7ee941c001d771c07b7da318ac6  v322.tar.gz
```

**Comment by woodruffw** [comment]
Went ahead and mirrored it to bintray.

**Pull request closed without merging**
