### PR TITLE
cadence 0.6.0 (new formula)

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/onflow/cadence

### CODE REVIEW

**Comment by chenrui333** [comment]
@SeekingMeaning have you used this tool before? seems pretty interesting.

**Comment by SeekingMeaning** [comment]
Other than when I created this formula, I have not

I like programming languages

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> Other than when I created this formula, I have not
> 
> I like programming languages

😂

**Comment by turbolent** [comment]
Nice, thank you for submitting and getting it merged! 🎉

Note that this only Cadence's interpreter and REPL. In case you are looking for the Flow CLI, which also includes this and the Flow emulator, consider installing that instead: https://docs.onflow.org/docs/cli.

We're planning to open-source the Flow CLI very soon, and hope to have Homebrew Formula for it as well 🙂

**Pull request closed without merging**
