### PR TITLE
libxc 5.1.4, cp2k 8.2

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Giving these another try as newer GCC is available:
- `libxc` #72930 #69347 #53077
- `cp2k` #72230 #68951 #58949 #50978

### CODE REVIEW

**Comment by cho-m** [comment]
<details>
<summary>ARM Failure - undefined symbol <tt>__ZNSt8ios_base4InitC1Ev</tt></summary>

```make
gfortran -D__FFTW3 -I/opt/homebrew/opt/fftw/include -I /opt/homebrew/opt/libxc/include -I /opt/homebrew/Cellar/cp2k/8.2/libexec/include -fopenmp -funroll-loops -ftree-vectorize -ffree-form -O2 -g -D__FFTW3 -D__NO_STATM_ACCESS -D__ACCELERATE -D__LIBXC -D__LIBINT -D__COMPILE_ARCH="\"Darwin-gfortran\"" -D__COMPILE_DATE="\"Fri Jun  4 15:06:27 PDT 2021\"" -D__COMPILE_HOST="\"HMBRW-A-001-M1-004.local\"" -D__COMPILE_REVISION="\"git:310b7ab\"" -D__DATA_DIR="\"/private/tmp/cp2k-20210604-34043-mzdky7/cp2k-8.2/data\""  -L/private/tmp/cp2k-20210604-34043-mzdky7/cp2k-8.2/lib/Darwin-gfortran/ssmp -o /private/tmp/cp2k-20210604-34043-mzdky7/cp2k-8.2/exe/Darwin-gfortran/cp2k.ssmp cp2k.o  -lcp2kstart -lcp2kmc -lcp2kswarm -lcp2kmotion -lcp2kthermostat -lcp2kemd -lcp2ktmc -lcp2kmain -lcp2kgrid -lcp2kgridcpu -lcp2kgridref -lcp2kgridcommon -ldbcsrarnoldi -ldbcsrx -lcp2kshg_int -lcp2keri_mme -lcp2kminimax -lcp2khfxbase -lcp2ksubsys -lcp2kxc -lcp2kao -lcp2kpw_env -lcp2kinput -lcp2kpw -lcp2koffload -lcp2kfft -lcp2kfpga -lcp2kfm -lcp2kcommon -lcp2kmpiwrap -lcp2kbase -L/private/tmp/cp2k-20210604-34043-mzdky7/cp2k-8.2/lib/Darwin-gfortran/ssmp/exts/dbcsr -ldbcsr -L/opt/homebrew/opt/fftw/lib -lfftw3 -lfftw3_threads -framework Accelerate -L/opt/homebrew/opt/libxc/lib -lxcf03 -lxc -L/opt/homebrew/Cellar/cp2k/8.2/libexec/lib -lint2
Undefined symbols for architecture arm64:
  "__ZNSt8ios_base4InitC1Ev", referenced from:
      __GLOBAL__sub_I_libint2_static_init.cc in libint2.a(libint2_static_init.o)
      __GLOBAL__sub_I__1emultipole_D_D.cc in libint2.a(_1emultipole_D_D.o)
      __GLOBAL__sub_I__1emultipole_D_F.cc in libint2.a(_1emultipole_D_F.o)
      __GLOBAL__sub_I__1emultipole_D_G.cc in libint2.a(_1emultipole_D_G.o)
      __GLOBAL__sub_I__1emultipole_D_H.cc in libint2.a(_1emultipole_D_H.o)
      __GLOBAL__sub_I__1emultipole_D_P.cc in libint2.a(_1emultipole_D_P.o)
      __GLOBAL__sub_I__1emultipole_D_S.cc in libint2.a(_1emultipole_D_S.o)
      ...
  "__ZNSt8ios_base4InitD1Ev", referenced from:
      __GLOBAL__sub_I_libint2_static_init.cc in libint2.a(libint2_static_init.o)
      __GLOBAL__sub_I__1emultipole_D_D.cc in libint2.a(_1emultipole_D_D.o)
      __GLOBAL__sub_I__1emultipole_D_F.cc in libint2.a(_1emultipole_D_F.o)
      __GLOBAL__sub_I__1emultipole_D_G.cc in libint2.a(_1emultipole_D_G.o)
      __GLOBAL__sub_I__1emultipole_D_H.cc in libint2.a(_1emultipole_D_H.o)
      __GLOBAL__sub_I__1emultipole_D_P.cc in libint2.a(_1emultipole_D_P.o)
      __GLOBAL__sub_I__1emultipole_D_S.cc in libint2.a(_1emultipole_D_S.o)
      ...
Undefined symbols for architecture arm64:
  "__ZNSt8ios_base4InitC1Ev", referenced from:
      __GLOBAL__sub_I_libint2_static_init.cc in libint2.a(libint2_static_init.o)
      __GLOBAL__sub_I__1emultipole_D_D.cc in libint2.a(_1emultipole_D_D.o)
      __GLOBAL__sub_I__1emultipole_D_F.cc in libint2.a(_1emultipole_D_F.o)
      __GLOBAL__sub_I__1emultipole_D_G.cc in libint2.a(_1emultipole_D_G.o)
      __GLOBAL__sub_I__1emultipole_D_H.cc in libint2.a(_1emultipole_D_H.o)
      __GLOBAL__sub_I__1emultipole_D_P.cc in libint2.a(_1emultipole_D_P.o)
      __GLOBAL__sub_I__1emultipole_D_S.cc in libint2.a(_1emultipole_D_S.o)
      ...
  "__ZNSt8ios_base4InitD1Ev", referenced from:
      __GLOBAL__sub_I_libint2_static_init.cc in libint2.a(libint2_static_init.o)
      __GLOBAL__sub_I__1emultipole_D_D.cc in libint2.a(_1emultipole_D_D.o)
      __GLOBAL__sub_I__1emultipole_D_F.cc in libint2.a(_1emultipole_D_F.o)
      __GLOBAL__sub_I__1emultipole_D_G.cc in libint2.a(_1emultipole_D_G.o)
      __GLOBAL__sub_I__1emultipole_D_H.cc in libint2.a(_1emultipole_D_H.o)
      __GLOBAL__sub_I__1emultipole_D_P.cc in libint2.a(_1emultipole_D_P.o)
      __GLOBAL__sub_I__1emultipole_D_S.cc in libint2.a(_1emultipole_D_S.o)
      ...
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
```
</details>

<details>
<summary>Mojave Failure - <tt>env: python3: No such file or directory</tt></summary>

```make
==> make ARCH=Darwin-gfortran VERSION=ssmp
env: python3: No such file or directory
env: python3: No such file or directory
env: python3: No such file or directory
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /private/tmp/cp2k-20210604-6391-vw12jm/cp2k-8.2/exts/dbcsr -f .cp2k/Makefile \
	   INCLUDEMAKE=/private/tmp/cp2k-20210604-6391-vw12jm/cp2k-8.2/arch/Darwin-gfortran.ssmp \
	   LIBDIR=/private/tmp/cp2k-20210604-6391-vw12jm/cp2k-8.2/lib/Darwin-gfortran/ssmp/exts/dbcsr \
	   OBJDIR=/private/tmp/cp2k-20210604-6391-vw12jm/cp2k-8.2/obj/Darwin-gfortran/ssmp/exts/dbcsr \
	   ACC="" \
	   ACCFLAGS=""
Removing stale archives for ssmp ... 
env: python3: No such file or directory
make[2]: *** [makedep] Error 127
make[2]: *** Waiting for unfinished jobs....
Removing stale archives ... 
env: python3: No such file or directory
```
</details>

**Comment by fxcoudert** [comment]
- `Error: Unclassifiable statement ` is https://github.com/cp2k/cp2k/issues/1316
- `undefined symbol __ZNSt8ios_base4InitC1Ev`: that's weird, is libint supposed to be compiled with C++?
- `env: python3: No such file or directory`: we can require `python` as build dependency

**Comment by cho-m** [comment]
Since upstream issue mention `-j` causes issues, I guess we can try to deparallelize make.
For next run, I'll try this with python dependency for Intel CI nodes.

For ARM, haven't taken much of a look. Upstream script to build is https://github.com/cp2k/cp2k/blob/v8.2.0/tools/toolchain/scripts/stage3/install_libint.sh#L82-L87
```
      ./configure --prefix=${pkg_install_dir} \
        --with-cxx="$CXX $LIBINT_CXXFLAGS" \
        --with-cxx-optflags="$LIBINT_CXXFLAGS" \
        --enable-fortran \
        --libdir="${pkg_install_dir}/lib" \
        > configure.log 2>&1
```

**Comment by cho-m** [comment]
Looks like Mojave is now failing where ARM Big Sur did.
I could try some C++ flags.

From https://github.com/cp2k/cp2k/blob/master/INSTALL.md#2g-libint-optional-enables-methods-including-hf-exchange, 
>  Add `-L$(LIBINT_DIR)/lib -lint2 -lstdc++` to `LIBS` and `-I$(LIBINT_DIR)/include` to `FCFLAGS`.
> `lstdc++` is needed if you use the GNU C++ compiler.

Alternatively, from the other issue https://github.com/cp2k/cp2k/issues/1316
> `CFLAGS   = -std=c11 -fopenmp -O2`

---

```make
Undefined symbols for architecture x86_64:
  "__ZNSt8ios_base4InitC1Ev", referenced from:
      __GLOBAL__sub_I_libint2_static_init.cc in libint2.a(libint2_static_init.o)
      __GLOBAL__sub_I__1emultipole_D_D.cc in libint2.a(_1emultipole_D_D.o)
      __GLOBAL__sub_I__1emultipole_D_F.cc in libint2.a(_1emultipole_D_F.o)
      __GLOBAL__sub_I__1emultipole_D_G.cc in libint2.a(_1emultipole_D_G.o)
      __GLOBAL__sub_I__1emultipole_D_H.cc in libint2.a(_1emultipole_D_H.o)
      __GLOBAL__sub_I__1emultipole_D_P.cc in libint2.a(_1emultipole_D_P.o)
      __GLOBAL__sub_I__1emultipole_D_S.cc in libint2.a(_1emultipole_D_S.o)
      ...
```

**Comment by cho-m** [comment]
Successful build for ARM now.
Sadly forgot to modify the test since `sopt` and `popt` aren't built.

@fxcoudert should `-lstdc++` be added to upstream?
In order to get build to succeed, I'll keep in current Formula, but may add a comment to consider removing if added to upstream files.

**Review by carlocab — APPROVED** [review]
👏

**Pull request closed without merging**
