### PR TITLE
cockroach 2.0.6

### PR DESCRIPTION
**Pull request by benesch**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> Verifying d68c4686051349bfb0a4e2e39e739c654328225002a87b24c50323fa90b9a8f1--cockroach-v2.0.6.src.tgz checksum
tar xf /Users/brew/Library/Caches/Homebrew/downloads/d68c4686051349bfb0a4e2e39e739c654328225002a87b24c50323fa90b9a8f1--cockroach-v2.0.6.src.tgz -C /private/tmp/d20181001-55578-nb1krh
cp -pR /private/tmp/d20181001-55578-nb1krh/cockroach-v2.0.6/. /private/tmp/cockroach-20181001-55578-6sqnlx/cockroach-v2.0.6
Error: An exception occured within a child process:
  Errno::ENOENT: No such file or directory @ rb_file_s_stat - /private/tmp/d20181001-55578-nb1krh/cockroach-v2.0.6/src/github.com/cockroachdb/cockroach/vendor/github.com/apache/thrift/tutorial/erl/client.sh
```

Yet more unpack dark magic… @reitermarkus

**Comment by reitermarkus** [comment]
What's the backtrace?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by benesch** [comment]
@fxcoudert I'm afraid that the fix for https://github.com/cockroachdb/cockroach/issues/30765 isn't in any released version of CockroachDB yet. If you'd like I can update the formula with the one necessary patch. (It'll be about a week or two before we release a version with the fix, if that factors into your calculus.)

**Comment by fxcoudert** [comment]
@benesch if you can have a single patch, included in a `patch do` block (e.g. the relevant commit from master), I think we can live with that.

**Comment by fxcoudert** [comment]
@benesch gentle ping on this one :)

**Comment by SMillerDev** [comment]
@benesch gentle ping on this one :)

**Comment by fxcoudert** [comment]
Close in favour of #33508

**Pull request closed without merging**
