### PR TITLE
argo 2.11.1

### PR DESCRIPTION
**Pull request by crunchtime-ali**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by simster7** [comment]
You beat me to this by 1 minute!

**Comment by crunchtime-ali** [comment]
> You beat me to this by 1 minute!

My GitHub action did :P

Can someone kick the build-server please?

**Comment by Rylan12** [comment]
I restarted CI. Just FYI we're having CI issues so failures are not a surprise. Once everything's up and running again we'll go through and restart CI where it's needed.

**Comment by crunchtime-ali** [comment]
> I restarted CI. Just FYI we're having CI issues so failures are not a surprise. Once everything's up and running again we'll go through and restart CI where it's needed.

Thank you. Can I help with the CI issues? Are there related issues?

**Comment by SMillerDev** [comment]
Unless you work at github I doubt there's much you can do. Performance to the repo has been terrible lately, we're waiting for github to fix it. (Issue is pinned)

**Review by miccal — APPROVED** [review]

**Pull request closed without merging**
