### PR TITLE
youtube-dl 2019.04.24

### PR DESCRIPTION
**Pull request by Zegnat**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Just a straight forward version bump.

### CODE REVIEW

**Comment by Zegnat** [comment]
Not sure why Jenkins is showing an issue with `mps-youtube`. Especially because the error shown (“"token" parameter not in video info for unknown reason”) is specifically an issue solved by this newer version of youtube-dl. See first point [in the release description](https://github.com/ytdl-org/youtube-dl/releases/tag/2019.04.24).

**Comment by Yarn** [comment]
https://github.com/Homebrew/homebrew-core/blob/0fbf3dee8442e22a35161df6d402b09ec0c8f5f6/Formula/mps-youtube.rb

looking at the formula it looks like it's downloading an older version of youtube-dl?

**Comment by Zegnat** [comment]
@Yarn right you are, not sure how I missed that!

To clarify again then: the Jenkins failure is because of the `mps-youtube` formula failing, and not because of the update I made to `youtube-dl`.

It looks like `mps-youtube` is a little special in that it [requires youtube-dl as a Python module](https://github.com/mps-youtube/mps-youtube/pull/802#issuecomment-457874098). Should probably require a separate PR and not get mixed up with this one.

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
Thanks @Zegnat!

**Pull request closed without merging**
