### PR TITLE
sonic 1.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error: failed to run custom build command for `librocksdb-sys v6.20.3`
  
  Caused by:
    process didn't exit successfully: `/tmp/sonic-20230812-9917-10wj5jb/sonic-1.4.1/target/release/build/librocksdb-sys-551f32dd734153b5/build-script-build` (exit status: 101)
    --- stderr
    thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_854_1)" is not a valid Ident', /github/home/.cache/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.66/src/fallback.rs:774:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  error: failed to compile `sonic-server v1.4.1 (/tmp/sonic-20230812-9917-10wj5jb/sonic-1.4.1)`, intermediate artifacts can be found at `/tmp/sonic-20230812-9917-10wj5jb/sonic-1.4.1/target`

```

**Comment by danielnachun** [comment]
This error is occurring because an incompatibility between older versions of the `bindgen` crate and Clang 16.  I believe the build should work if you use `llvm@15` to build instead of `llvm`.  If that fixes it, we can put a comment that we can try to `llvm` when the `bindgen` crate has been updated to a new enough version to work with LLVM >= 16.

**Comment by danielnachun** [comment]
Building with `llvm@15` resolves the build failure but now on Intel macOS we're hitting a seemingly unrelated test failure.  I don't know why it only fails on Intel macOS and not on ARM macOS or Linux.

**Comment by chenrui333** [comment]
raised an upstream issue on this, https://github.com/valeriansaliou/sonic/issues/314

**Comment by cho-m** [comment]
Just a random attempt but maybe try increasing sleep time given that Intel macOS is slower than ARM macOS.

**Comment by ZhongRuoyu** [comment]
> Just a random attempt but maybe try increasing sleep time given that Intel macOS is slower than ARM macOS.

Yes, that worked. Thanks, @cho-m.

**Review by branchv — APPROVED** [review]

**Pull request merged**
