### PR TITLE
antlr@2: deprecate

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is the patch upstreamed?

**Comment by cho-m** [comment]
I don't think `antlr@2` is maintained anymore (2.7.7 is from 2006. No repo). `antlr` v3 and v4 are maintained.

I assume we haven't deprecated it due to `nco`, which is actively maintained. Looks like `nco` also keeps a patched tarball of `antlr@2` with similar fix (at least for `cstring`) as mentioned in http://nco.sourceforge.net/#bld and https://github.com/nco/nco/issues/58. Based on comments, it doesn't seem likely that `antlr` version will be updated in near future.

**Comment by SMillerDev** [comment]
It's a shame that NCO is a popular formula, but if they refuse to use supported versions of antlr I think we should deprecate it.

CC @Homebrew/core for opinions

**Comment by MikeMcQuaid** [comment]
> It's a shame that NCO is a popular formula, but if they refuse to use supported versions of antlr I think we should deprecate it.

Alternatively, we should just use their patched version in the formula. I have little preference either way but, if pushed, would very lightly prefer deprecation.

**Comment by danielnachun** [comment]
There is an upstream issue about this: https://sourceforge.net/p/nco/discussion/9831/thread/1a424aac/.  I think they had a good reason at the time not to migrate to ANTLR4 - it had incomplete C++ support compared to ANTLR 2.  Would it be worth asking them if more recent versions of ANTLR4 would now work?

**Comment by cho-m** [comment]
Based on comments in that issue and on March 2022 in https://github.com/nco/nco/issues/58, the upstream will review/accept PRs to update parser, but aren't planning to work on it themselves. The problem is moving from ANTLR2 to ANTLR4 may require a rewrite of entire grammar given changes in AST generation and other parts.

**Comment by danielnachun** [comment]
I am going to see if I can use the patched copy of ANTLR 2 that `nco` uses as a resource instead of this formulae.  If that works, we can update `nco` to depend on that instead, and then deprecate this formulae.

**Comment by danielnachun** [comment]
The URLs to the patched copies are dead, but it looks like `nco` is hosting a copy of `antlr2` on GitHub which they use: https://github.com/nco/antlr2.  I can make a pull request there to fix the missing `<include>`.  That seems like a viable option to fix ANTLR2 until they can migrate to ANTLR4, and we can still deprecated `antlr@2` as nothing is else using it.

**Comment by danielnachun** [comment]
Now that https://github.com/Homebrew/homebrew-core/pull/103967 is merged and `nco` is bottled on Linux, nothing uses `antlr@2` so it is time to deprecate this.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
