### PR TITLE
cake 0.38.1

### PR DESCRIPTION
**Pull request by gep13**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@gep13 can you do the rebase to the latest master?

**Comment by gep13** [comment]
@chenrui333 yes, I can do that.

**Comment by chenrui333** [comment]
Also, can you add a comment in the code referencing our previous conversation about the prerelease tag issue (would be helpful for future merges).

**Comment by gep13** [comment]
@chenrui333 said...
Also, can you add a comment in the code referencing our previous conversation about the prerelease tag issue (would be helpful for future merges).

Sorry, just seeing this now... will get this added just now.

**Comment by chenrui333** [comment]
> > @chenrui333 said...
> > Also, can you add a comment in the code referencing our previous conversation about the prerelease tag issue (would be helpful for future merges).
> 
> Sorry, just seeing this now... will get this added just now.

no worries.

**Comment by gep13** [comment]
@chenrui333 should be ready to go now.

**Comment by chenrui333** [comment]
you also need to remove this file, `Formula/cake.rb.orig` :)

**Comment by gep13** [comment]
>@chenrui333 said...
you also need to remove this file, Formula/cake.rb.orig :)

Apologies, just seeing this now!  Thanks for taking care of that.  I normally have the *.orig files in my gitignore file, so didn't think to check for it here.  Apologies again!

**Comment by gep13** [comment]
@chenrui333 would you like me to rebase out the commit that you made, or can this be merged in as-is?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> @chenrui333 would you like me to rebase out the commit that you made, or can this be merged in as-is?

definitely, sorry about the delay

**Comment by gep13** [comment]
No need to apologise, thanks for merging!

**Pull request merged**
