### PR TITLE
ssh-copy-id: provided by macOS.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Provided since Sierra.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks @MikeMcQuaid! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by MikeMcQuaid** [comment]
Thanks so much for your comment! Without maintainers like you making comments we couldn't use this project. You rock, @SMillerDev!

**Comment by Bo98** [comment]
Perhaps for another PR, but could the `depends_on` in `appscale-tools` be a potential `uses_from_macos`?

https://github.com/Homebrew/homebrew-core/blob/5ab9766e70776ef1702f8d40c8ef5159252c31be/Formula/appscale-tools.rb#L18

**Comment by MikeMcQuaid** [comment]
@bo98 good idea, see https://github.com/Homebrew/homebrew-core/pull/52660

**Pull request merged**
