### PR TITLE
awscli 2.0.22

### PR DESCRIPTION
**Pull request by shigemk2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tkawachi** [comment]
Version 2.0.23 has just been released.

**Comment by SMillerDev** [comment]
@tkawachi please make a pull request for it so I can close this

**Comment by jaeggir** [comment]
could we merge this in the meantime? AWS added support for CodeArtifact in 2.0.21 (current version is 2.0.19).

**Comment by jaeggir** [comment]
PR for 2.0.23: https://github.com/Homebrew/homebrew-core/pull/56442

**Comment by tkawachi** [comment]
Thanks @jaeggir for the PR!

**Pull request closed without merging**
