### PR TITLE
curl 7.51.0

### PR DESCRIPTION
**Pull request by chriso**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://curl.haxx.se/changes.html#7_51_0

### CODE REVIEW

**Comment by fuzzyroddis** [comment]
LGTM

**Comment by DomT4** [comment]
Yeah, It's fine. I'm sure a maintainer will drop by to merge it soon.

**Comment by DomT4** [comment]
@dunn Any chance you could merge this one in? ❤️. Picked you out from the top of the PR list, heh, so if you immediately dropped offline again I apologise for the ping 😉.

**Comment by dunn** [comment]
Oops, I did run off again.

Merged in 01a5baea83d01e4ba9cee37a0c0f9c8a4b7c7490 now, thanks @chriso!

**Pull request closed without merging**
