### PR TITLE
ykpers 1.18.0

### PR DESCRIPTION
**Pull request by snood1205**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source ykpers`?
- [X] Does your build pass `brew audit --strict ykpers` (after doing `brew install ykpers`)?

-----

Version bump

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thank you @snood1205 for your contribution to Homebrew! We couldn't do it with pull requests like this.

**Comment by snood1205** [comment]
What would be a better way to do this?

**Comment by ilovezfs** [comment]
@snood1205 what do you mean?

**Comment by snood1205** [comment]
I guess I'm just not understanding what "We couldn't do it with pull requests like this." means.

**Comment by ilovezfs** [comment]
@snood1205 your changes were merged: https://github.com/Homebrew/homebrew-core/commit/a629cc21a23b69d2fa81a8ef2c80f8c3cb66b0cc

@fxcoudert just meant that Homebrew relies on contributions such as yours! Thank you!

**Comment by snood1205** [comment]
Ah! I'm so sorry I was confused because the PR was closed. Oops, sorry about that! Thank you all!

**Comment by ilovezfs** [comment]
@snood1205 no problem. This confuses people all the time. The reason the PR is closed not merged is that we use `brew pull` when accepting changes that cause the formulae to need new bottles, rather than using the GitHub interface.

**Comment by fxcoudert** [comment]
@snood1205 sorry, I meant “we couldn't do Homebrew *without* pull requests like yours!’

**Comment by snood1205** [comment]
@fxcoudert No worries! Sorry about that!

**Pull request closed without merging**
