### PR TITLE
platformio 3.5.2

### PR DESCRIPTION
**Pull request by ivankravets**
* [PlatformIO Home](http://docs.platformio.org/page/home/index.html) - interact with PlatformIO ecosystem using modern and cross-platform GUI:

  - Multiple themes (Dark & Light)
  - Ability to specify a name for new project

* Control [PIO Unified Debugger](http://docs.platformio.org/en/latest/plus/debugging.html) and its firmware loading mode using [debug_load_mode](http://docs.platformio.org/en/latest/projectconf/section_env_debug.html#debug-load-mode) option
* Added aliases (off, light, strict) for [LDF Compatibility Mode](http://docs.platformio.org/page/librarymanager/ldf.html)
* Search for a library using PIO Library Registry ID ``id:X`` (e.g. ``pio lib search id:13``)
* Show device system information (MCU, Frequency, RAM, Flash, Debugging tools) in a build log
* Show all available upload protocols before firmware uploading in a build log
* Handle "os.mbed.com" URL as a Mercurial (hg) repository
* Improved support for old mbed libraries without manifest
* Fixed project generator for Qt Creator IDE ([issue #1303](https://github.com/platformio/platformio-core/issues/1303), [issue #1323](https://github.com/platformio/platformio-core/issues/1323))
* Mark project source and library directories for CLion IDE ([issue #1359](https://github.com/platformio/platformio-core/issues/1359), [issue #1345](https://github.com/platformio/platformio-core/issues/1345), [issue #897](https://github.com/platformio/platformio-core/issues/897))
* Fixed issue with duplicated "include" records when generating data for IDE ([issue #1301](https://github.com/platformio/platformio-core/issues/1301))

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Please update resources to certifi 2018.1.18 and click 6.7

**Comment by ivankravets** [comment]
Why?

**Comment by ivankravets** [comment]
"certifi" was updated, the "click" could not be updated because we depend on the old version which has an API that was removed in 6.7

**Comment by commitay** [comment]
Thanks @ivankravets!

**Pull request closed without merging**
