### PR TITLE
dsd: delete formula

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The [homepage for `dsd` (Digital Speech Encoder)](https://wiki.radioreference.com/index.php/Digital_Speech_Decoder_%28software_package%29) states the following:

> While DSD was intended to be patent-free, mbelib describes functions that may be covered by one or more U.S. patents owned by DVSI Inc. The source code itself should not be infringing as it merely describes possible methods of implementation. **Compiling or using mbelib may infringe on patents rights and/or require licensing. It is unknown if DVSI will sell licenses for software that uses mbelib. If you do not have a license and are in a jurisdiction protected by the DVSI patents you should not compile or use this source code.**

_(Emphasis from original excerpt)_

The `dsd` formula currently downloads `mselib` as a resource during compilation. As such, I think we're in the wrong here with how we also compile and install `mbelib` as part of the process.

IANAL of course, but something just seemed off here so I figured I'd bring it up.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Given it's not clear what code is involved, what countries/jurisdictions are involved… removing seems precipitated

**Comment by alebcay** [comment]
I considered that as well, so I'm of course open to other solutions. I figured I would at least open a PR to warrant further investigation and, if worst comes to worst, the PR is already written and ready to go.

**Comment by jonchang** [comment]
Based on my reading, it seems that compiling without `mbelib` would be fine?

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Do we want a new review to change dsd to compile without mbelib?

**Comment by fxcoudert** [comment]
Possibly… I'm 👎 on merely deleting it.

**Comment by zbeekman** [comment]
Let's just build without mbelib.

**Review by zbeekman — CHANGES_REQUESTED** [review]
Let's just build without mbelib.

**Comment by SMillerDev** [comment]
@alebcay could you make a new PR for that?

**Comment by alebcay** [comment]
It looks like `mbelib` is a required dependency. Either that, or I have yet to find some way to build this without it.

**Comment by fxcoudert** [comment]
Building without the problematic component turns out not to be possible: https://github.com/Homebrew/homebrew-core/pull/39070

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
