### PR TITLE
Remove old, unsupported version of Sync Gateway

### PR DESCRIPTION
**Pull request by tleyden**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tleyden** [comment]
I work at Couchbase and this came up in a meeting today.  We want to pull this formula out of homebrew until we can get homebrew into our release building / QA process.  

Currently, this is an older version which we want to avoid distributing and supporting. 

> Have you built your formula locally with brew install --build-from-source <formula>, where <formula> is the name of the formula you're submitting?

No, since I'm just removing formula

> Does your build pass brew audit --strict <formula> (after doing brew install <formula>)?

Ditto

**Comment by ilovezfs** [comment]
Do you mind if we move it to the boneyard (:skull:) instead of deleting it?
https://github.com/Homebrew/homebrew-boneyard

**Comment by tleyden** [comment]
Sure!  Didn't know about the boneyard

**Comment by ilovezfs** [comment]
Any reason not to create a new tag and update it? I seem to recall [when I updated this](https://github.com/Homebrew/homebrew-core/pull/7497) recently that it built from HEAD fine.

**Comment by tleyden** [comment]
Yeah sync gateway 1.3.1 is the current version, so if we can get it working without much fuss, then it's probably worth it.

**Comment by ilovezfs** [comment]
The version in Homebrew is 1.3.1 currently.

**Comment by ilovezfs** [comment]
@tleyden 
```
iMac-TMP:~ joe$ brew install sync_gateway
==> Downloading https://homebrew.bintray.com/bottles/sync_gateway-1.3.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/sync_gateway-1.3.1.el_capitan.bottle.tar.gz
==> Pouring sync_gateway-1.3.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/sync_gateway/1.3.1: 6 files, 42.8M
iMac-TMP:~ joe$ git ls-remote https://github.com/couchbase/sync_gateway.git|grep 'refs/tags/1.3.1'
660b1c92fadce1a9c7e692dfe7c5b741772d1dd2	refs/tags/1.3.1
iMac-TMP:~ joe$ brew test -vd sync_gateway 2>&1 |grep 660b1c9
2016-12-09T11:31:44.800-08:00 ==== Couchbase Sync Gateway/HEAD(nobranch)(660b1c9) ====
iMac-TMP:~ joe$ brew test sync_gateway
Testing sync_gateway
==> Using the sandbox
2016-12-09T11:31:59.671-08:00 ==== Couchbase Sync Gateway/HEAD(nobranch)(660b1c9) ====
2016-12-09T11:31:59.671-08:00 Configured process to allow 5000 open file descriptors
2016-12-09T11:31:59.671-08:00 Opening db /sync_gateway as bucket "sync_gateway", pool "default", server <walrus:>
2016-12-09T11:31:59.671-08:00 Opening Walrus database sync_gateway on <walrus:>
2016-12-09T11:31:59.672-08:00 Using default sync function 'channel(doc.channels)' for database "sync_gateway"
2016-12-09T11:31:59.672-08:00     Reset guest user to config
2016-12-09T11:31:59.672-08:00 Starting profile server on 
2016-12-09T11:31:59.672-08:00 Starting admin server on 127.0.0.1:4985
2016-12-09T11:31:59.674-08:00 Starting server on localhost:4984 ...
iMac-TMP:~ joe$ ssh 10.0.1.197
Password:
Last login: Fri Dec  9 07:55:35 2016 from 10.0.1.83
Josephs-Mac:~ joe$ brew install sync_gateway
==> Downloading https://homebrew.bintray.com/bottles/sync_gateway-1.3.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sync_gateway-1.3.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/sync_gateway/1.3.1: 6 files, 42.8M
Josephs-Mac:~ joe$ brew test -vd sync_gateway 2>&1 |grep 660b1c9
2016-12-09T11:32:41.591-08:00 ==== Couchbase Sync Gateway/HEAD(nobranch)(660b1c9) ====
Josephs-Mac:~ joe$ brew test sync_gateway
Testing sync_gateway
==> Using the sandbox
2016-12-09T11:32:48.815-08:00 ==== Couchbase Sync Gateway/HEAD(nobranch)(660b1c9) ====
2016-12-09T11:32:48.815-08:00 Configured process to allow 5000 open file descriptors
2016-12-09T11:32:48.815-08:00 Opening db /sync_gateway as bucket "sync_gateway", pool "default", server <walrus:>
2016-12-09T11:32:48.816-08:00 Opening Walrus database sync_gateway on <walrus:>
2016-12-09T11:32:48.816-08:00 Using default sync function 'channel(doc.channels)' for database "sync_gateway"
2016-12-09T11:32:48.816-08:00     Reset guest user to config
2016-12-09T11:32:48.816-08:00 Starting profile server on 
2016-12-09T11:32:48.816-08:00 Starting admin server on 127.0.0.1:4985
2016-12-09T11:32:48.818-08:00 Starting server on localhost:4984 ...
Josephs-Mac:~ joe$
```

What am I missing?

**Comment by tleyden** [comment]
Ok, sorry, this was a stale ticket in our repo then.  Thanks for looking into it!

**Comment by ilovezfs** [comment]
@tleyden no problem. Please let us know if you encounter any issues with the brew version!

**Pull request closed without merging**
