### PR TITLE
gawk 5.2.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
#109630 was closed due to a test failure on Ubuntu ([output](https://github.com/Homebrew/homebrew-core/actions/runs/2989304013/jobs/4800263192#step:11:103)). Let me try to get this fixed.

**Comment by ZhongRuoyu** [comment]
So, I am able to reproduce this locally in a Docker image:

```
# docker run --rm -it --pull always homebrew/ubuntu22.04:latest /bin/bash
brew developer on
cd `brew --repository homebrew/core`
curl -fsSL "https://github.com/Homebrew/homebrew-core/commit/e80f37b924da0b1b626bb09e072a72e5b1644605.patch" | git apply -
brew install --build-from-source gawk
brew install translate-shell
brew test translate-shell
```

The last `brew test` command produces the same failure.

<details>
<summary> <code>brew test</code> Output</summary>

```
==> Testing translate-shell
==> /home/linuxbrew/.linuxbrew/Cellar/translate-shell/0.9.7/bin/trans -no-init -b -s es -t en hola
gawk: /dev/fd/63:2787: fatal: internal error: file interpret.h, line 253: unexpected parameter type Node_val
Error: translate-shell: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 2
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.16.3/lib/minitest/assertions.rb:183:in `assert'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.16.3/lib/minitest/assertions.rb:218:in `assert_equal'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_assertions.rb:26:in `shell_output'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/translate-shell.rb:38:in `block in <class:TranslateShell>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2270:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:605:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2269:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:967:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2268:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2545:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2262:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:50:in `<main>'
```
</details>

However, manually running the test outside Homebrew's build environment does produce the expected result:

```
linuxbrew@f04236f2dffa:~$ /home/linuxbrew/.linuxbrew/Cellar/translate-shell/0.9.7/bin/trans -no-init -b -s es -t en hola
hello
```

It turned out that there's nothing wrong with `translate-shell`. It's just that `gawk`, used by `translate-shell`, does not like the initial `LC_ALL` value in the build environment.

```
linuxbrew@f04236f2dffa:~$ brew sh
Your shell has been configured to use Homebrew's build environment;
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit`.
brew ~$ echo $LC_ALL
C.utf8
brew ~$ /home/linuxbrew/.linuxbrew/Cellar/translate-shell/0.9.7/bin/trans -no-init -b -s es -t en hola
gawk: /dev/fd/63:2787: fatal: internal error: file interpret.h, line 253: unexpected parameter type Node_val
brew ~$ export LC_ALL="en_US.UTF-8"
brew ~$ /home/linuxbrew/.linuxbrew/Cellar/translate-shell/0.9.7/bin/trans -no-init -b -s es -t en hola
hello
```

So we can have this fixed by overriding `LC_ALL` in `translate-shell`'s tests.

**Review by danielnachun — DISMISSED** [review]
Nice job with the Linux fix!  The Big Sur failure should be ignored because it's just a transient failure.

**Comment by ZhongRuoyu** [comment]
CI took an unusually long time on macOS arm64 (and was timed out). Looks like it was stuck while building `gawk`, but that shouldn't have happened. I doubt if it was also just a transient issue. 🤔

**Comment by ZhongRuoyu** [comment]
I think I have fixed the build on macOS arm64. Can someone please help to remove the `long build` label? It shouldn't be needed.

The issue was with the [PMA test](https://git.savannah.gnu.org/cgit/gawk.git/tree/test/Makefile.in?h=gawk-5.2.0&id=7eacf279a6ff4bff560ff49a8a2a9c531658096c#n2217). The new feature is not working on macOS arm64, and the test ate up 100% of a CPU core indefinitely. The commit that disabled PMA can't be directly applied, so I'm embedding the necessary stuffs in the formula.

**Review by chenrui333 — COMMENTED** [review]
LGTM

**Review by danielnachun — APPROVED** [review]

**Pull request closed without merging**
