### PR TITLE
exiv2 0.28.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at cmake/Findinih.cmake:28 (message):
    inih library not found
```

**Comment by chenrui333** [comment]
raised an issue about regression building gexiv2 0.14.1: https://gitlab.gnome.org/GNOME/gexiv2/-/issues/74

**Comment by chenrui333** [comment]
- for geeqie, https://github.com/BestImageViewer/geeqie/issues/1090
- for siril, https://gitlab.com/free-astro/siril/-/issues/1117

**Comment by chenrui333** [comment]
if https://gitlab.gnome.org/GNOME/gexiv2/-/merge_requests/78 got merged, we can re-try this PR with siril patch

**Comment by chenrui333** [comment]
> if https://gitlab.gnome.org/GNOME/gexiv2/-/merge_requests/78 got merged, we can re-try this PR with gexiv2 and siril patches

this patch does not apply to us.

**Comment by MikeMcQuaid** [comment]
Have removed `help wanted` and/or `in progress` from this PR as there's been no progress in a few months. Maintainers: please don't add these labels as the stalebot is performing a useful service in continuing to bump these PRs and closing them if there's no activity after those bumps. Thanks ❤️

**Comment by chenrui333** [comment]
gonna close it for now, and will open a new one for the new efforts.

**Comment by chenrui333** [comment]
#154055

**Pull request closed without merging**
