### PR TITLE
libav 12

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
Need to remove the patch.

**Comment by ilovezfs** [comment]
@zmwangx done. I'll probably want to check the options build before merging, though.

**Comment by JCount** [comment]
@ilovezfs This has a runtime failure on El Capitan due to lazy symbol binding against `_clock_gettime` in [libavutil/time.c#L57-L66](https://github.com/libav/libav/blob/v12/libavutil/time.c#L57-L66).

**Comment by ilovezfs** [comment]
@JCount :scream:

**Comment by JCount** [comment]
Working on it!

**Comment by JCount** [comment]
For reference: https://github.com/libav/libav/blob/v12/libavutil/time.c#L57-L66 & https://github.com/libav/libav/blob/v12/configure#L4476-L4477

**Comment by ilovezfs** [comment]
@JCount main thing is reporting it upstream.

**Comment by woodruffw** [comment]
Opened upstream report: https://bugzilla.libav.org/show_bug.cgi?id=1033

**Comment by ilovezfs** [comment]
:bowing_man:

**Comment by woodruffw** [comment]
Upstream got back to me with a patch, opened #10655 to test it.

**Comment by JCount** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/10655.

**Pull request closed without merging**
