### PR TITLE
enchant 2.1.2

### PR DESCRIPTION
**Pull request by jessetan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jessetan** [comment]
The Jenkins test is failing because gspell installed from bottle is linked to `/usr/local/opt/enchant/lib/libenchant.1.dylib`, I can replicate this error locally by running `brew test gspell --verbose`.
If I rebuild gspell from source using `brew install --build-from-source gspell`, the above test succeeds.
How do we go about making sure gspell is linked appropriately? Can it perhaps link to `/usr/local/opt/enchant/lib/libenchant.dylib` which is a symlink to `libenchant.2.dylib`

**Comment by ilovezfs** [comment]
You need to bump the revision gspell.

**Comment by jessetan** [comment]
Thanks @ilovezfs, I've bumped the gspell revision and fixed the merge conflict, but Jenkins still seems to see a merge conflict :(

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @jessetan! Shipped.

**Pull request closed without merging**
