### PR TITLE
mkvtoolnix 47.0.0

### PR DESCRIPTION
**Pull request by 404NetworkError**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by 404NetworkError** [comment]
I don't exactly know what needs to happen to fix the `fmt` linkage problem.  It could be related to the change in #54759 or it just needs a revision bump.  I'm not sure.  Any help would be appreciated.

**Comment by issyl0** [comment]
That type of failure is usually indicative of needing a revision bump. You can do this with `brew bump-revision fmt --message "for mkvtoolnix 47.0.0"`

**Comment by 404NetworkError** [comment]
That did it. Thanks @issyl0.

**Review by issyl0 — APPROVED** [review]
Thanks once again for your contribution!

**Pull request closed without merging**
