### PR TITLE
hub: install man pages for head and devel

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

also provide an option to opt-out of installing the man pages

CC @mislav

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> also provide an option to opt-out of installing the man pages

Why would you want this; just that it takes a while?

**Comment by ilovezfs** [comment]
Yeah, the gems take a while to build so someone is likely to complain.

**Comment by ilovezfs** [comment]
Specifically, on my machine, it's 3 seconds without the man pages, and 1 minute 7 seconds with them.

**Comment by ilovezfs** [comment]
You can use `https://raw.githubusercontent.com/Homebrew/formula-patches/4b15321/qt5/QTBUG-57656.patch` before this is merged. Please open the corresponding PR before we merge a patch here.

**Comment by mislav** [comment]
This looks solid!

I wish the man page install process was a bit faster. A full `bundle install` might be wasteful since that installs 20 gems, whereas only `ronn` is needed and that equates to a total of 4 gems. Should I make changes to master to speed up the install mode for man pages-only?

@MikeMcQuaid The next stable version of hub will dynamically generate man pages. Even if this process takes a full minute, will Homebrew auto-create a bottle for the build product, speeding up future installs since a bottle will contain pre-built binary plus already built man pages? I guess what I'm asking is: is build speed irrelevant in the world where we enjoy the awesomeness that is Homebrew bottles?

**Comment by ilovezfs** [comment]
Considering qt5 takes 2 hours and 45 minutes to build, and we bottle that, I'd say you're entitled to your 1 minute. Maybe even 2 minutes.

**Review by MikeMcQuaid — APPROVED** [review]

**Pull request merged**
