### PR TITLE
etl, synfig: add github mirror

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

```console
% curl -Ls https://github.com/synfig/synfig/releases/download/v1.2.2/source-ETL-1.2.2.tar.gz | shasum -a 256                                                                                
0dc19c5a6c9e964054ca3af6dacd6ab0c198d78071cfab2aebac178afe454d8b  -
% curl -Ls https://github.com/synfig/synfig/releases/download/v1.2.2/source-synfig-1.2.2.tar.gz | shasum -a 256                                                                                 
5f5f7b33483041165f9a63fe4d95eb815971c7444569e574206f6964e83cc2ef  -
```

### CODE REVIEW

**Review by dawidd6 — APPROVED** [review]

**Comment by chenrui333** [comment]
Just curious, why do we need to have mirror?

**Comment by SeekingMeaning** [comment]
SourceForge has been a little unreliable (although not always)

**Comment by chenrui333** [comment]
I see, make sense.

**Comment by chenrui333** [comment]
> SourceForge has been a little unreliable (although not always)

relates to #181398

**Pull request closed without merging**
