### PR TITLE
uhd: Fixed Python library failing to install

### PR DESCRIPTION
**Pull request by fksms**
The problem of setting the wrong Python site-packages path has already been fixed below.
https://github.com/EttusResearch/uhd/commit/c385d20eeea717b3859ac6a2bcc247b69fc66003

Please merge as revision:2, as the next Stable version is not yet available in uhd.

### CODE REVIEW

**Review by SMillerDev — CHANGES_REQUESTED** [review]
You can apply the patch, but we will not ship a random commit as a stable version.

**Comment by SMillerDev** [comment]
Did the current pre-build release also have this problem?

**Comment by SMillerDev** [comment]
Please remove the merge commit from the pull request.

**Comment by daianjibetu** [comment]
The branch I used for the pull request over here is getting complicated, so can we have it handled in the https://github.com/Homebrew/homebrew-core/pull/140761 pull request?

**Comment by daianjibetu** [comment]
I did it.

**Review by SMillerDev — APPROVED** [review]
Thanks @daianjibetu  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request merged**
