### PR TITLE
git-review 1.27.0

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by deepanshu-zendrive** [comment]
git-review releases: https://github.com/openstack-infra/git-review/releases
URL taken from: https://pypi.org/project/git-review/#files

**Review by fxcoudert — CHANGES_REQUESTED** [review]
Some resources need to be updated: `certifi` at least, possibly others.

**Comment by deepanshu-zendrive** [comment]
Updated all resources to their latest versions

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @deepanshu-zendrive

**Pull request closed without merging**
