### PR TITLE
tomee-webprofile 7.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
```
22:04:03 ==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/40411
22:05:04 ==> FAILED
22:05:04 fatal: ref HEAD is not a symbolic ref
22:05:04 ==> Fetching patch 
22:05:04 Patch: https://github.com/Homebrew/homebrew-core/pull/40411.patch
22:05:04 curl: (22) The requested URL returned error: 504 Gateway Time-out
22:05:04 Error: Failure while executing; `/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.4-6-g7c3bb36\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --fail --progress-bar --silent --location --remote-time --continue-at 0 --output /Users/brew/Library/Caches/Homebrew/40411.patch https://github.com/Homebrew/homebrew-core/pull/40411.patch` exited with 22. Here's the output:
22:05:04 curl: (22) The requested URL returned error: 504 Gateway Time-out
22:05:04 Homebrew/brew 2.1.4-6-g7c3bb36ca (Merge pull request #6181 from Homebrew/dependabot/bundler/Library/Homebrew/ruby-progressbar-1.10.1)
22:05:04 
22:05:04 Testing tap homebrew/core with:
22:05:04   origin/master   3536392d0f (jena 3.11.0 (#40407))
22:05:04   HEAD            3536392d0f (jena 3.11.0 (#40407))
22:05:04   diff_start_sha1 3536392d0f
22:05:04   diff_end_sha1   3536392d0f
```

**Comment by chenrui333** [comment]
image

**Comment by SMillerDev** [comment]
@brewtestbot test this please

**Comment by SMillerDev** [comment]
Why did the URL change?

**Comment by chenrui333** [comment]
yeah, you are right, I will switched the url back, sorry for the confusion. :)

**Comment by SMillerDev** [comment]
Thanks @chenrui333! Without contributions like yours it'd be impossible to keep homebrew going! 👍 🎉

**Pull request merged**
