### PR TITLE
apr: install to prefix and delete .exp file

### PR DESCRIPTION
**Pull request by lexicol**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`.exp` is used on Windows only, so it is safe to delete.

### CODE REVIEW

**Comment by carlocab** [comment]
On Mojave:
```
Error: 20 failed steps!
brew linkage --test activemq-cpp
brew linkage --test apr-util
brew linkage --test ctail
brew linkage --test ganglia
brew linkage --test httpd
brew test --retry --verbose httpd
brew linkage --test log4cxx
brew linkage --test mesos
brew linkage --test openmama
brew linkage --test php
brew test --retry --verbose php
brew linkage --test php@7.3
brew test --retry --verbose php@7.3
brew linkage --test php@7.4
brew test --retry --verbose php@7.4
brew linkage --test shibboleth-sp
brew linkage --test subversion
brew test --retry --verbose subversion
brew linkage --test subversion@1.8
brew linkage --test tomcat-native
```
I think we'll need to rebuild at least all these formulae, presumably for their `apr` dependency. We should probably wait to see if there are more from the other CI nodes, though.

**Comment by carlocab** [comment]
ARM:
```
Error: 13 failed steps!
brew linkage --test activemq-cpp
brew linkage --test apr-util
brew linkage --test httpd
brew test --retry --verbose httpd
brew linkage --test log4cxx
brew linkage --test openmama
brew linkage --test php
brew test --retry --verbose php
brew linkage --test php@7.4
brew test --retry --verbose php@7.4
brew linkage --test shibboleth-sp
brew linkage --test subversion
brew linkage --test tomcat-native
```

**Comment by carlocab** [comment]
Big Sur:

```
Error: 19 failed steps!
brew linkage --test activemq-cpp
brew linkage --test apr-util
brew linkage --test ctail
brew linkage --test ganglia
brew linkage --test httpd
brew test --retry --verbose httpd
brew linkage --test log4cxx
brew linkage --test mesos
brew linkage --test openmama
brew linkage --test php
brew test --retry --verbose php
brew linkage --test php@7.3
brew test --retry --verbose php@7.3
brew linkage --test php@7.4
brew test --retry --verbose php@7.4
brew linkage --test shibboleth-sp
brew linkage --test subversion
brew linkage --test subversion@1.8
brew linkage --test tomcat-native
```

Catalina:

```
Error: 20 failed steps!
brew linkage --test activemq-cpp
brew linkage --test apr-util
brew linkage --test ctail
brew linkage --test ganglia
brew linkage --test httpd
brew test --retry --verbose httpd
brew linkage --test log4cxx
brew linkage --test mesos
brew linkage --test openmama
brew linkage --test php
brew test --retry --verbose php
brew linkage --test php@7.3
brew test --retry --verbose php@7.3
brew linkage --test php@7.4
brew test --retry --verbose php@7.4
brew linkage --test shibboleth-sp
brew linkage --test subversion
brew test --retry --verbose subversion
brew linkage --test subversion@1.8
brew linkage --test tomcat-native
```

**Comment by carlocab** [comment]
What exactly is this meant to fix, @lexicol? It looks like this change is going to destroy a lot of older bottles.

**Comment by lexicol** [comment]
I wanted to simplify the apr formula but I’m surprised that it had such an effect on other formulae. I don’t think it’s worth it at this point anymore.

**Comment by carlocab** [comment]
If you're still pursuing this PR you need to add again all the revision bumps I made previously.

**Comment by lexicol** [comment]
Are the revision bumps still needed? The symlinks I have added should fix any linkage issues, which if I understand correctly was the reason why formulae were breaking.

**Comment by carlocab** [comment]
Missed the symlinks. They might help. Let's see.

**Comment by carlocab** [comment]
Looks like the symlinks worked. I think we need to skip the revision bumps and merge this without bottles, though, and just let it take effect at the next version bump of `apr` or `apr-util`.

**Comment by lexicol** [comment]
Okay. Shall I push one more time?

**Comment by carlocab** [comment]
No need; I can fix that upon merging.

**Comment by carlocab** [comment]
Merged in b038b7aaa1ab95f8bed107dfd8237e49f4d99fe4. Thanks, @lexicol.

**Comment by DomT4** [comment]
> I think we need to skip the revision bumps and merge this without bottles, though, and just let it take effect at the next version bump of apr or apr-util.

I don't know if this is worth revisiting. Working out where this warning was coming from has been doing my head in lately 🤣 
```
Broken dependencies:
  /opt/homebrew/opt/apr-util/lib/libaprutil-1.0.dylib (apr-util)
Warning: php has broken dynamic library links:

Rebuild this from source with:
  brew reinstall --build-from-source php
If that's successful, file an issue here:
  https://github.com/Homebrew/homebrew-core/issues
```
Makes it seem like it's PHP's fault, when in reality it's because `apr-util` has been sat on my filesystem without me pouring a new bottle or building it from source for lord knows how long now 😅.

**Comment by carlocab** [comment]
Yes, this has come up a few times since then. I'm not opposed to a `revision` bump here if you feel strongly about it.

**Pull request closed without merging**
