### PR TITLE
gdcm_2.8.6

### PR DESCRIPTION
**Pull request by michaelloewenstein**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
> sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.

https://sourceforge.net/projects/gdcm/

**Comment by commitay** [comment]
@michaelloewenstein Can you post a link to the issue please?

**Comment by michaelloewensteinviz** [comment]
https://sourceforge.net/p/gdcm/feature-requests/36/

**Comment by commitay** [comment]
Thanks!

**Comment by ilovezfs** [comment]
@malaterre any idea what happened here?

**Comment by michaelloewensteinviz** [comment]
@commitay any thoughts of how to move this forward?

**Comment by michaelloewensteinviz** [comment]
@commitay?

**Comment by ilovezfs** [comment]
Thanks for the PR @michaelloewenstein and for filing the upstream issue. This is now fixed as we've just shipped 2.8.7 in Homebrew.

**Pull request closed without merging**
