### PR TITLE
Update subversion formula to use serf 1.3.10 (updated URL)

### PR DESCRIPTION
**Pull request by PlugNPush**
Solves #133035 

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by PlugNPush** [comment]
Recreating the PR taking into account the Serf builder migration to Python 3 and complying to the commit style.

**Comment by KeyCompTheater** [comment]
@PlugNPush Hi there,
Is it possible that this change nuked the SSL support for svn with a (very!) outdated svn server that only supports TLSv1-ish?

I can't figure out what else could be the problem. The svn version is the same built for a Mac where it is working (Ventura / ARM) and one that it is not working on (also Ventura / ARM). The OpenSSL version is newer were the problem occurs (3.1.1 vs 3.0.8 were it works) and the surf version in svn --version is still behind at 1.3.9 on the working Mac.
`svn: E170013: Unable to connect to a repository at URL 'https://<URL>'
svn: E120171: Error running context: An error occurred during SSL communication`
This is the error message I'm getting with all flags for trust-ssl-cert on etc. My curl test command was able to connect (with the flag --insure although) to the server, so I dare to say the newer OpenSSL version might not be the problem here.

Is there a way I can revert my SVN to a version before this commit?
Thank you very much in advance!

**Comment by PlugNPush** [comment]
Hey, I think that PR did not go through. I had another one for it. That being said, I have no idea if your issue is related to Serf or not; one of the issues is that the old version of Serf is no longer available for download so I'm not sure how you could get the previous version. You could try finding the old version somewhere and building locally from the formulae file from this current PR. If you succeed, you can try to host the old Serf files somewhere safe and copy this PR as your own to overwrite my changes. Good luck 🍀

**Comment by Bo98** [comment]
> Is it possible that this change nuked the SSL support for svn with a (very!) outdated svn server that only supports TLSv1-ish?

TLS 1.0 and TLS 1.1 are disabled in modern OpenSSL (not just Homebrew but also in Linux distributions too). You may have to lower the security level to 0 in `openssl.cnf`, though be aware that this will enable it for everything.

**Pull request closed without merging**
