### PR TITLE
go 1.17.5

### PR DESCRIPTION
**Pull request by stefanb**
Closes https://github.com/Homebrew/homebrew-core/pull/90350

### CODE REVIEW

**Comment by gonzaloserrano** [comment]
Any idea on what's the CI issue here?

> Error: The file '/home/actions/actions-runner/_work/homebrew-core/homebrew-core' already exists.

**Comment by stefanb** [comment]
in previous #90350 the tag `CI-linux-self-hosted` was removed, perhaps for same reason?

**Comment by stefanb** [comment]
This time it got 
> The self-hosted runner: linux-self-hosted-1 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

I'd suggest:
- adding tag `CI-no-fail-fast` to leave CI running on other platforms regardless of first failure and/or
- removing the `CI-linux-self-hosted` tag to skip this platform

**Comment by SMillerDev** [comment]
I'm going to close this since it's much nicer to keep the history and research of the old PR (and not have to reconfigure the labels)

**Comment by gonzaloserrano** [comment]
@SMillerDev so https://github.com/Homebrew/homebrew-core/pull/90350 needs to be updated to 1.17.5?

**Pull request closed without merging**
