### PR TITLE
subversion: enable i18n support

### LINKED ISSUE #33110: Enable i18n support for subversion
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Support i18n for `subversion`
- What happened (include command output)
Homebrew disable i18n support for `subversion`by using the option `--disable-nls` when build it.
- What you expected to happen
Do NOT use the option `--disable-nls` when build subversion.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install subversion`

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Fix #33110

### CODE REVIEW

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by moonfruit** [comment]
I compare the compile option between my branch and d391bf4, and I see no different.
Add I have no environment for High Sierra to dig into it.
Sorry for not helping.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by fxcoudert** [comment]
Subversion build is currently broken, we need to fix it first. We are tracking this in 
https://github.com/Homebrew/homebrew-core/pull/33530

**Pull request closed without merging**
