### PR TITLE
tor 0.3.3.7

### PR DESCRIPTION
**Pull request by yurikoles**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Want to keep the mirror here ideally given `torproject.org` can be _quite the target_ for governments/etc less than keen on unfettered access to information.

**Comment by yurikoles** [comment]
@DomT4 sorry, I had provided the new mirror address but script had removed it.

**Comment by yurikoles** [comment]
@DomT4 oh I see that mirror is not synced yet.

**Comment by DomT4** [comment]
Ah. Should be soon, I expect.

**Comment by ilovezfs** [comment]
Thanks for reminding me @yurikoles. I've been meaning to upstream this for a while. https://github.com/Homebrew/brew/pull/4336

**Comment by ilovezfs** [comment]
Shipped! Thanks again @yurikoles

**Pull request closed without merging**
