### PR TITLE
protobuf 3.12.2

### PR DESCRIPTION
**Pull request by anderscarling**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by anderscarling** [comment]
#54950 also bumps a few other formulas, I'm not sure it that's needed for a minor update such as this. @alebcay could you advise?

**Comment by anderscarling** [comment]
(Other bumps are probably not needed, as #55143 was merged without further changes.)

**Comment by anderscarling** [comment]
If someone could advise on how to properly debug what actually causes the issue in the 10.15-check I could have a look at it.

Seems weird that there should be an issue on only one macOS-version if there is a compatibility issue with a library, does it not?

**Review by chenrui333 — COMMENTED** [review]
lgtm

**Comment by chenrui333** [comment]
@anderscarling looks like it was a flaky build?

**Comment by alebcay** [comment]
I think it was a flaky build. I don't recall exactly what the logs mentioned previously, but it was something regarding `postgresql` I think (something about resource limits - maybe something about the `postinstall` step or related to `shmget`).

Seeing as the Catalina nodes have been falling behind and have probably been really stressed, I'm not too surprised that something broke.

Shouldn't need any revision bumps for a patch release like this, I think. Linkages all seem to be okay.

**Review by alebcay — APPROVED** [review]

**Comment by samford** [comment]
Just a heads up for the future, the `six` resource in this formula should have been bumped to version 1.15.0 in this PR.

**Comment by anderscarling** [comment]
@samford - is that just to keep the dependency up to date, or will building against 1.14 cause issues? If the later, we should probably fix asap.

**Comment by samford** [comment]
> is that just to keep the dependency up to date, or will building against 1.14 cause issues?

It may work fine on 1.14.0 but part of updating a formula is to update any relevant resources. Basically, the goal is to install the same versions as `pip install protobuf` would.

To be clear, we don't want to blindly bump the resource to the newest version on PyPi, as we have to take the dependency requirements for `protobuf` into account. There are a couple ways that you can determine the appropriate resource version for this formula.

The easy way is to install `protobuf` using `pip` and to note the version of `six` installed (afterward you can uninstall everything, to tidy up). This formula only has one resource, so you could also check the relevant dependency requirement in the [`setup.py` file in the `protobuf` repo](https://github.com/protocolbuffers/protobuf/blob/e492e5a4ef16f59010283befbde6112f1995fa0f/python/setup.py#L244) and check [the latest version of the resource on PyPi](https://pypi.org/project/six/#history).

Regardless of how you go about this, you want to pay attention to `resource` blocks when updating Python formulae. It's not uncommon for people to run `brew bump-formula-pr` and miss the resource update but maintainers usually catch this in review and request an update.

I would just leave this as it is and we can update it the next time there's a `protobuf` version bump (unless someone encounters an issue in the interim time). I just mentioned this to make you aware of the issue for the future.

**Comment by anderscarling** [comment]
Thanks for the great explanation @samford, much appreciated!

**Pull request closed without merging**
