### PR TITLE
git-annex: fix build by constraining feed to < 1

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @fxcoudert

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @joeyh RE: http://git-annex.branchable.com/bugs/Build_failure_with_feed___62____61___1.0.0.0/

**Comment by joeyh** [comment]
ee2f096e3ba3aea24445ff2093b426b68e000cc2 fixed that already.
A release with it may be along later this week.

-- 
see shy jo

**Comment by ilovezfs** [comment]
@joeyh nice!

**Comment by ilovezfs** [comment]
@joeyh So I tried testing HEAD, since you said you're near a new release, but I still ran into the `resource exhausted (Too many open files)` when running `git annex test` if I build with GHC 8.2.1. See http://git-annex.branchable.com/bugs/git_annex_test_fails/

(Also, the `aws` flag fails to build due to https://github.com/aristidb/aws/issues/238 but I worked around that by setting `--allow-newer=aws:time`.)

Full build log is here: https://gist.github.com/ilovezfs/40f2f20f6460212e5f2d98ed9c67b2f7

**Pull request closed without merging**
