### PR TITLE
emojify 2.1.0

### PR DESCRIPTION
**Pull request by posoo**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Unfortunately, emojify 2.x does not support macOS's bash.

**Comment by posoo** [comment]
> Unfortunately, emojify 2.x does not support macOS's bash.

This is true. However, people can opt to upgrade the bash to support emojify 2.x by single command `brew install bash`

Maybe I can create another formula called emojify2 with dependencies specified to offer a choice for those who intend to get the latest version.

**Comment by SMillerDev** [comment]
Does it work with macOS' zsh? In that case I'd suggest `uses_from_macos "zsh"`. @Homebrew/core what do you think?

**Comment by posoo** [comment]
> Does it work with macOS' zsh? In that case I'd suggest `uses_from_macos "zsh"`. @Homebrew/core what do you think?

I tried on my machine and made it worked with zsh by a few modifications. I pushed them in my fork [emojify-zsh](https://github.com/posoo/emojify-zsh) if someone interests in it. I am going to create a formula for this.

There was also similar work done in [zemojify](https://github.com/filipekiss/zemojify).

**Pull request closed without merging**
