### PR TITLE
Use HTTPS in URLs and tests (1/2)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vszakats** [comment]
`httping` test was updated to use HTTPS, this works in El Cap and Sierra, but fails in Yosemite:
```
==> FAILED
Testing httping
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170320-88245-168w2z6.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/httping.rb --verbose
==> /usr/local/Cellar/httping/2.5/bin/httping -c 2 -g https://brew.sh/
Auto enabling SSL due to https-URL
PING brew.sh:443 (/):
short read during receiving reply-headers from host
short read during receiving reply-headers from host
--- https://brew.sh/ ping statistics ---
2 connects, 0 ok, 100.00% failed, time 2126ms
Error: httping: failed
Failed executing: /usr/local/Cellar/httping/2.5/bin/httping -c 2 -g https://brew.sh/
```

This could be intermittent or sign of a tool issue, can't decide, but the update appears to be valid by itself.

**Comment by vszakats** [comment]
The Yosemite `httping` test failure seems to be consistent.

**Comment by vszakats** [comment]
`httping` moved to #11335.

**Comment by fxcoudert** [comment]
Thanks for migrations

**Pull request merged**
