### PR TITLE
pg_partman 4.7.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /opt/homebrew/opt/postgresql@15/bin/pg_ctl start -D /private/tmp/pg_partman-test-20221217-42317-mwjc46/test -l /private/tmp/pg_partman-test-20221217-42317-mwjc46/log
  Error: test failed
  waiting for server to start.... stopped waiting
  pg_ctl: could not start server
```

**Comment by chenrui333** [comment]
From logfile running with pg 15
```
2022-12-17 11:48:47.453 EST [2754] LOG:  database system is shut down
2022-12-17 11:54:57.146 EST [24460] FATAL:  could not access file "pg_partman_bgw": No such file or directory
2022-12-17 11:54:57.146 EST [24460] LOG:  database system is shut down
```

**Comment by chenrui333** [comment]
@Porkepix Can you report an upstream issue on the regression test thing?

**Review by chenrui333 — APPROVED** [review]

**Comment by Porkepix** [comment]
@chenrui333 I guess I can't really do more here: https://github.com/pgpartman/pg_partman/issues/498#issuecomment-1357998699

**Pull request closed without merging**
