### PR TITLE
expat 2.6.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by stefanb** [comment]
Fyi, 2.6.4 not yet listed on https://libexpat.github.io/
image

but is latest on https://github.com/libexpat/libexpat/releases

**Comment by ZhongRuoyu** [comment]
Ah, I only checked the GitHub release. Probably just an oversight given it's also listed on the repo main page? https://github.com/libexpat/libexpat

**Comment by stefanb** [comment]
Yeah, likely they just forgot to update the web page.

**Comment by hartwork** [comment]
@stefanb @ZhongRuoyu not forgotten, it _always_ comes later in the release process (https://github.com/libexpat/libexpat/issues/919).

**Comment by ZhongRuoyu** [comment]
Thanks for confirming @hartwork!

**Pull request merged**
