### PR TITLE
pkl: 0.25.1 (new formula)

### PR DESCRIPTION
**Pull request by bioball**
Pkl is a configuration as code language.
This adds a formula to install the CLI for interacting with Pkl.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — CHANGES_REQUESTED** [review]
https://docs.brew.sh/Acceptable-Formulae

**Comment by bioball** [comment]
@SMillerDev are you saying we should re-submit this to https://github.com/Homebrew/homebrew-cask?

**Comment by chenrui333** [comment]
@bioball we need to build from source for core

**Comment by SMillerDev** [comment]
If your tool is not open source it should be a cask.

**Comment by bioball** [comment]
It is open source: https://github.com/apple/pkl

We'll re-do this as a cask though. Closing out.

**Comment by skyline69** [comment]
When will this be available?

**Comment by amatzen** [comment]
I wouldn't consider the pkl CLI-tool a cask. Please reopen this issue instead @bioball.

**Comment by onedr0p** [comment]
This should not be a cask, please re-open.

**Comment by bioball** [comment]
Re-submitted!

**Pull request closed without merging**
