### PR TITLE
nodenv: remove `bottle :unneeded`.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
It should have an identical checksum on all platforms.

### CODE REVIEW

**Comment by carlocab** [comment]
All different:
```
❯ sha256sum *.tar.gz
c86512e5a1505eb10c79a4aeb618db66cc08a48ac855e9c0f9fb9fba7868d5e7  nodenv--1.4.0.arm64_big_sur.bottle.tar.gz
b6cce4dccc468b49f71f989a3f6f0d505f198e2fa4604a0cd8a24f969901a6d6  nodenv--1.4.0.big_sur.bottle.tar.gz
b5af0ac98407b7d246a41154c4ca9db9cad273b5fa65a487fcb080f3d15704f6  nodenv--1.4.0.catalina.bottle.tar.gz
69231fd7b4e38aee64caecb7582969f0abcbeacaaf4ebce6de700b2e20848e11  nodenv--1.4.0.mojave.bottle.tar.gz
```
Will try to come back to this to see where the diff is coming from.

**Comment by carlocab** [comment]
Diff comes from
```diff
--rwxr-xr-x   0        0        0     8600 2020-07-20 14:28:53.000000 nodenv/1.4.0/libexec/nodenv-realpath.dylib
+-rwxr-xr-x   0        0        0    49592 2020-07-20 14:28:53.000000 nodenv/1.4.0/libexec/nodenv-realpath.dylib
```
which looks to be compiled in

https://github.com/Homebrew/homebrew-core/blob/d6ae1abc4c5e0fb5ab6cbe01c9cc0e6447d18c1c/Formula/nodenv.rb#L23-L25

**Comment by MikeMcQuaid** [comment]
`nodenv-realpath.dylib` doesn't sound very `bottle :unneeded` to me 😂

**Comment by carlocab** [comment]
Yup. 😅 Building it used to be optional, so it was genuinely `bottle :unneeded` before. It was just forgotten when the option was removed in https://github.com/Homebrew/homebrew-core/commit/167c719049b8d7316c2ace331e77e0ebabd50c73.

**Review by carlocab — APPROVED** [review]
I think this one can be merged as-is, since I don't think we can change this to an `all` tag.

**Comment by MikeMcQuaid** [comment]
@carlocab agree, thanks for checking it out!

**Pull request closed without merging**
