### PR TITLE
workflows: use container for uploads

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/issues/124619

### CODE REVIEW

**Comment by dawidd6** [comment]
Wooops, don't know what happened here. I just tried the workflow from this branch and it merged this PR?
Workflow run was successful though: https://github.com/Homebrew/homebrew-core/actions/runs/4313581516/jobs/7525552982.

**Comment by dawidd6** [comment]
Should we revert it or just observe how it goes?

**Comment by carlocab** [comment]
That's weird. I didn't even think @BrewTestBot could merge changes to workflow files.

**Comment by dawidd6** [comment]
Looks like it is performing just fine:
https://github.com/Homebrew/homebrew-core/actions/runs/4313811425
https://github.com/Homebrew/homebrew-core/actions/runs/4313811451
https://github.com/Homebrew/homebrew-core/actions/runs/4313811527
and we are down to less than 2 minutes per workflow run.

**Pull request merged**
