### PR TITLE
texlive 62297

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by SMillerDev** [comment]
Should probably wait for icu4c to even test

**Comment by carlocab** [comment]
I updated the resources by hand... not doing that again. Some way to automate this would be very helpful. @branchvincent

**Comment by carlocab** [comment]
When `icu4c` is merged I think we should run this anyway (we'll have to prematurely remove a `CI-long-timeout` label from either `llvm` or `go`), since the `icu4c` bump will break `texlive` for everyone (not just Linux users).

**Comment by carlocab** [comment]
The `inreplace` needs updating. CC @danielnachun

**Comment by carlocab** [comment]
Opened #96154 so we can rebuilt `texlive`, since I'm not quite sure how to fix the `inreplace`.

**Comment by danielnachun** [comment]
I have to download the sources to check, but I believe the reason it doesn't work now is because they upstreamed my changes to so the `inreplace` should be unneeded.  My only source of concern is that it seemed like the last file did not fail, which may mean it wasn't changed.  I'll have the answer for this soon as I don't actually have run the build, just check the files.

**Comment by danielnachun** [comment]
I've tested this locally and we no longer need to use `inreplace` on any file except `TLUtils.pm`.  This has been fixed upstream like the others, but it is distributed with the `install-tl` resource, which hasn't been updated yet, rather than the main source tarball.  Here is the diff: 
```
diff --git a/Formula/texlive.rb b/Formula/texlive.rb
index ef744e9d388..0c685b01c4a 100644
--- a/Formula/texlive.rb
+++ b/Formula/texlive.rb
@@ -374,25 +374,8 @@ class Texlive < Formula
     inreplace share/"texmf-dist/web2c/texmfcnf.lua",
       "selfautoparent:texmf", "selfautodir:share/texmf"

-    # Fix path resolution in some scripts.  The fix for tlmgr.pl, TLUTils.pm, and
-    # tlshell is being upstreamed here: https://www.tug.org/pipermail/tex-live/2021-September/047394.html.
-    # The fix for cjk-gs-integrate.pl is being upstreamed here: https://github.com/texjporg/cjk-gs-support/pull/50.
-    # The author of crossrefware and pedigree-perl has been contacted by email.
-    pathfix_files = %W[
-      #{buildpath}/texk/texlive/linked_scripts/cjk-gs-integrate/cjk-gs-integrate.pl
-      #{buildpath}/texk/texlive/linked_scripts/crossrefware/bbl2bib.pl
-      #{buildpath}/texk/texlive/linked_scripts/crossrefware/bibdoiadd.pl
-      #{buildpath}/texk/texlive/linked_scripts/crossrefware/bibmradd.pl
-      #{buildpath}/texk/texlive/linked_scripts/crossrefware/biburl2doi.pl
-      #{buildpath}/texk/texlive/linked_scripts/crossrefware/bibzbladd.pl
-      #{buildpath}/texk/texlive/linked_scripts/crossrefware/ltx2crossrefxml.pl
-      #{buildpath}/texk/texlive/linked_scripts/texlive/tlmgr.pl
-      #{buildpath}/texk/texlive/linked_scripts/pedigree-perl/pedigree.pl
-      #{buildpath}/texk/texlive/linked_scripts/tlshell/tlshell.tcl
-      #{share}/tlpkg/TeXLive/TLUtils.pm
-    ]
-
-    inreplace pathfix_files, "SELFAUTOPARENT", "TEXMFROOT"
+    # Fix path resolution in TLUtils.pm. Remove with next release of install-tl resource.
+    inreplace share/"tlpkg/TeXLive/TLUtils.pm", "SELFAUTOPARENT", "TEXMFROOT"
```

**Comment by carlocab** [comment]
Thanks, @danielnachun. #96154 is two hours in and only waiting for the Intel macOS nodes, so I suggest we merge that first to get the broken linkage fixed ASAP.

**Comment by SMillerDev** [comment]
```
   gcc-11 -DHAVE_CONFIG_H -I. -I./w2c  -I./mfluadir/potrace    -g -O2 -c -o mfluadir/potrace/libmfluapotrace_a-curve.o `test -f 'mfluadir/potrace/curve.c' || echo './'`mfluadir/potrace/curve.c
  In file included from mfluadir/potrace/curve.c:8:
  ./w2c/config.h:23:10: fatal error: kpathsea/config.h: No such file or directory
     23 | #include <kpathsea/config.h>
        |          ^~~~~~~~~~~~~~~~~~~
  compilation terminated.
  Makefile:16288: recipe for target 'mfluadir/potrace/libmfluapotrace_a-curve.o' failed
```

**Pull request closed without merging**
