### PR TITLE
overmind 2.0.0

### PR DESCRIPTION
**Pull request by DarthSim**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/overmind/2.0.0/bin/overmind start
Error: overmind: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </inappropriate\ ioctl\ for\ device/> expected to be =~
<"\e]0;overmind-test-20190212-59263-1x4u9ah | overmind\a\e[1;38;5;7msystem\e[0m | \e[1mListening at /private/tmp/overmind-test-20190212-59263-1x4u9ah/.overmind.sock\e[0m\n\e[1;38;5;7msystem\e[0m | \e[1mTmux socket name: overmind-overmind-test-20190212-59263-1x4u9ah-8Rog7YEUJs2BTqzsW3kEqY\e[0m\n\e[1;38;5;7msystem\e[0m | \e[1mTmux session ID: overmind-test-20190212-59263-1x4u9ah\e[0m\n\e[1;38;5;2mtest  \e[0m | \e[1mStarted with pid 59281...\e[0m\n\e[1;38;5;2mtest  \e[0m | test message\n\e[1;38;5;2mtest  \e[0m | \e[1mExited\e[0m\n">.
```

**Comment by DarthSim** [comment]
Looks like fixed

**Comment by gee-forr** [comment]
Eagerly awaiting this merge. Thank you @DarthSim for overmind, it's wonderful.

**Comment by fxcoudert** [comment]
Thanks @DarthSim

**Pull request closed without merging**
