### PR TITLE
bottom: update default branch for `head` build

### PR DESCRIPTION
**Pull request by ClementTsang**
The head branch name changed from `master` to `main` a while ago, and this isn't reflected in the formula, which is apparently breaking things for some users.

Original report: https://github.com/ClementTsang/bottom/issues/1454

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@ClementTsang thanks for the pr, can you amend your commit msg as `bottom: update default branch for 'head' build`

**Comment by ClementTsang** [comment]
Hm, not sure if that was meant to automatically close?

**Comment by ClementTsang** [comment]
Reopened a PR here: https://github.com/Homebrew/homebrew-core/pull/170627

Sorry about the noise 😅

**Comment by chenrui333** [comment]
you should do a rebase, that would do the job.

**Comment by ClementTsang** [comment]
Yeah, I ended up just rebasing, but I couldn't reopen the PR so I just opened a new one 🤷

**Pull request closed without merging**
