### PR TITLE
pythran 0.12.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Ok, I have no idea why this is trying to run `gcc-5` on Linux. CC @cho-m @Homebrew/linux for ideas.

**Comment by cho-m** [comment]
The only place I can think of is `python@3.10`. The test passed when dependent tested in #109777.

However, I don't know why `pythran` didn't use specified compiler when attempting to modify `pythran-linux.cfg`.

**Comment by carlocab** [comment]
Ok, let's skip the test for now and re-enable it when `python@3.10` is rebuilt with the newer GCC.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Updating the `test` so that we attempt the second test case when `python@3.10` is rebuilt. #111953

**Pull request closed without merging**
