### PR TITLE
cpmtools 2.24

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
2.24 is not the latest (looking at http://www.moria.de/~michael/cpmtools/), but [repology thinks so](https://repology.org/project/cpmtools/versions) because that's what 3/54 repos have it.

**Comment by osalbahr** [comment]
Actually, the tar is in http://www.moria.de/~michael/cpmtools/files does that mean it might be the latest?

**Comment by chenrui333** [comment]
good catch, sounds like stale website info issue, need to file an upstream issue to have maintainer fix it.

**Comment by chenrui333** [comment]
```
  ==> /opt/homebrew/Cellar/cpmtools/2.24/bin/mkfs.cpm -f ibm-3740 /private/tmp/cpmtools-test-20230804-18893-i6rr2f/disk.cpm
  Error: cpmtools: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /opt/homebrew/Cellar/cpmtools/2.24/bin/mkfs.cpm -f ibm-3740 /private/tmp/cpmtools-test-20230804-18893-i6rr2f/disk.cpm
```

**Comment by chenrui333** [comment]
just dropped the upstream maintainer an email about the stale information on the site.

**Pull request closed without merging**
