### PR TITLE
yaegi 0.9.5

### PR DESCRIPTION
**Pull request by crunchtime-ali**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Thanks, @crunchtime-ali!

**Comment by crunchtime-ali** [comment]
@Rylan12 What is a sparkle ? 
/sparkle

**Comment by crunchtime-ali** [comment]
@Rylan12 What is a sparkle ? 
/sparkle

**Comment by SMillerDev** [comment]
It's a beta thing to "reward" people for contributions. Basically internet points.

**Comment by crunchtime-ali** [comment]
> It's a beta thing to "reward" people for contributions. Basically internet points.

Wow, people love internet points so what can I exchange them for or where can I see how many I collected?

**Comment by SMillerDev** [comment]
Would be cool if you can exchange them for GitHub socks/stickers/tees

**Pull request closed without merging**
