### PR TITLE
libhdhomerun 20231020

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
> The formula version (20231020) is newer than the version from `brew livecheck` (

**Comment by p-linnane** [comment]
I think it's a CDN propagation delay or something. It's returning 20231020 for me each time I check.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
just did a quick DNS propagation check
image

**Comment by chenrui333** [comment]
could be just their DNS issue

image

**Pull request merged**
