### PR TITLE
boost 1.68.0

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

~`boost-build` has not been updated to `1.68.0` yet. https://github.com/boostorg/build/releases~

Edited: `boost-build` has been updated to `1.68.0`.

### CODE REVIEW

**Comment by lembacon** [comment]
Since @DomT4 pointed out that

> […], it’s worth splitting anything that breaks into individual PRs and handling those after the main `boost` update has been pushed through successfully. Trying to get a `boost` update done in one PR generally results in it taking weeks.

It will indeed take us forever to update `boost`, so I'm temporarily dropping all commits regarding revision bumps, and will fix test failures due to broken linkages in a separated PR.

**Comment by lembacon** [comment]
@eyal0 I'm take a look later. Anyway, a pull request is always welcome though. :-)

**Comment by DomT4** [comment]
> It will indeed take us forever to update boost, so I'm temporarily dropping all commits regarding revision bumps

It's worth running it through once, leaving anything in that works or can be fixed in a trivial way, but pulling out anything that is broken in that initial run into a unique PR. It's possible not everything needs a bump; [last time around](https://github.com/Homebrew/homebrew-core/pull/26605) @commitay only updated ~30 formulae. That number is [pretty consistent](https://github.com/Homebrew/homebrew-core/pull/17122) so I think it's worth starting with that list and see what happens.

> boost 1.66 is the latest working boost that I have found. For my OSX users, this is a problem because there are not versions between boost 1.60 and 1.67 available on brew.

It's likely one would need to 💀 if we added a new one. We already have more old `boost` versions sitting around than we should.

**Comment by lembacon** [comment]
Pushed revision bumps for 29 formulae. 🤨

**Comment by lembacon** [comment]
Some updates here after an, unsurprisingly, failed CI run:

- Pushed a few more revision bumps.
- Removed obsolete `-mt` suffix for `ncmpcpp`.
- Applied upstream patch for `sfcgal`, see Oslandia/SFCGAL#169.
- Applied upstream patch for `osquery`, see facebook/osquery#4692.
- `mkvtoolnix` and `osrm-backend` are both still failing due to `Undefined symbols […]: […]boost::system::detail::system_category_instance`.
- `pcl` and `ledger` are failing due to `fatal error: 'boost/uuid/sha1.hpp' file not found`.

**Comment by eyal0** [comment]
@lembacon No, I think that I figured out what is happening and the problem was mine.

First, bg:simplify on a polygon now changes the start/end point of a ring. That is a new behavior that surprised me but it's correct.

Second, passing a vector of pairs of doubles to bg::simplify used to simplify it like a linestring. That is no longer true. The behavior is strange now. But if my input is a valid input with the right geometry concept, it works fine.

So my problem went away when I fixed my input type. No need for boost 1.66 for me anymore.

Thanks for your hard work!

**Comment by lembacon** [comment]
@eyal0 So we can drop the vendored boost 1.66.0 when a new release of `pcb2gcode` is available. 😉

**Comment by lembacon** [comment]
> Try relplacing `-std=c++11` with `-std=c++14` per boostorg/system#24

If we decide to bump the C++ standard used to build Boost from C++11 to C++14, then we may really need to rebuild everything depending on Boost. At least, this is something worthing considering. As of LLVM 6.0.0, which was released on 8 Mar 2018, the default C++ standard is C++14, IIRC. cc @Homebrew/maintainers

**Comment by fxcoudert** [comment]
Let's try not to move C++ standard to much… it might break other stuff :(

**Comment by jbeich** [comment]
> ... we may really need to rebuild everything depending on Boost

On FreeBSD we do this on every update per ABI: https://abi-laboratory.pro/tracker/timeline/boost/
Our oldest supported release is 10.4 which ships Clang/libc++ 3.4, so when switching Boost to C++14 only Clang had to be upgraded to Clang 6.0 from package. All ~300 Boost consumers built fine despite using Clang 3.4 from base system and the only fallout was https://github.com/boostorg/asio/pull/135

**Comment by lembacon** [comment]
The CI is started again here, feel free to kill it.

**Comment by lembacon** [comment]
Wish I could add a versioned `boost@1.67` for those failed formulae. 🤒

**Comment by DomT4** [comment]
Hopefully it'll be okay to get through 🤞. It's been a quiet day for CI thus far.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by JoeLoser** [comment]
Is there a decision on how to move forward with this PR? I'd love to see this get into master so I do not keep maintaining a Boost 1.68 built from source rather than Homebrew.

**Comment by claui** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
@JoeLoser I didn't find myself some time to handle this as well as #31193, I'm happy to close these PRs in favor of yours, if you do want to take them over. :-)

**Comment by lembacon** [comment]
Superseded by #32610.

**Pull request closed without merging**
