### PR TITLE
stunnel 5.44

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x]  Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
maybe we should save this up for the next openssl upgrade :trollface:

**Comment by DomT4** [comment]
You're tempting the universe's sense of humour far too much there, I fear 😉.

**Comment by ilovezfs** [comment]
Zeus may smite me with a :zap: CVE.

**Comment by ilovezfs** [comment]
:candy:

**Comment by DomT4** [comment]
Ta :heart:. Gonna be nervously watching my OpenSSL filter all week now.

**Comment by DomT4** [comment]
screen shot 2017-12-04 at 16 19 57

🙃

**Comment by ilovezfs** [comment]
how wonderful

**Pull request closed without merging**
