### PR TITLE
octave 5.1.0

### PR DESCRIPTION
**Pull request by gorisanson**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Build fails on all macOS versions with:

```
ld: framework not found QtOpenGL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgui/graphics/__init_qt__.la] Error 1
```

**Comment by scpeters** [comment]
I just tried building this locally, and I think the clang invocation is just missing a `-F /usr/local/opt/qt/Frameworks`. I'm not sure if we can easily inject that or if it needs to be a patch / upstream change.

**Comment by scpeters** [comment]
This patch seems like it might help, but it doesn't apply cleanly

* https://hg.savannah.gnu.org/hgweb/octave/rev/26889

**Comment by apjanke** [comment]
Here's a working Octave 5.1.0 formula for comparison: https://github.com/octave-app/homebrew-octave-app/blob/master/Formula/octave-octave-app%405.1.0.rb.

I'm doing it [with this](https://github.com/octave-app/homebrew-octave-app/blob/9d0c10834a09f057e6b76f038bc5a25406cefc64/Formula/octave-octave-app%405.1.0.rb#L147-L152) in the formula itself:

```
      # Qt 5.12 merged qcollectiongenerator into qhelpgenerator, and Octave's
      # source hasn't been updated to auto-detect this yet.
      ENV['QCOLLECTIONGENERATOR']='qhelpgenerator'
      # These "shouldn't" be necessary, but the build breaks if I don't include them.
      ENV['QT_CPPFLAGS']="-I#{Formula["qt"].opt_include}"
      ENV.append 'CPPFLAGS', "-I#{Formula["qt"].opt_include}"
      ENV['QT_LDFLAGS']="-F#{Formula["qt"].opt_lib}"
      ENV.append 'LDFLAGS', "-F#{Formula["qt"].opt_lib}"
```

**Comment by scpeters** [comment]
Thanks for the tip @apjanke; I'm going to move that to a new pull request since this one says `unknown repository`

**Pull request closed without merging**
