### PR TITLE
deno 1.7.0

### PR DESCRIPTION
**Pull request by chimurai**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Is it possible for this not to be merged until after https://github.com/Homebrew/homebrew-core/pull/66285?

The CI run for that PR take nearly two full days to complete, and this PR will create a merge conflict. If I have to rebase the Rust PR against master again, then that will cause another two-day delay.

**Comment by chimurai** [comment]
Removed the patch in PR, which is included in deno `1.6.1`

Got no problems to wait. Up to mods to respect your request @carlocab 👍

**Comment by carlocab** [comment]
It would help if you marked this PR as a draft in the meantime, but I hope a maintainer sees my previous comment before approving.

**Comment by chimurai** [comment]
Thanks for adding `do not merge` label @bayandin

I removed the `draft`. @carlocab, can you give a ping when this can be merged?

**Comment by carlocab** [comment]
Will do. Thanks!

**Comment by JounQin** [comment]
Can `depends_on :macos` be removed in favor of https://github.com/denoland/deno/pull/7779

**Comment by gromgit** [comment]
> Can `depends_on :macos` be removed in favor of [denoland/deno#7779](https://github.com/denoland/deno/pull/7779)

From that issue:
> Note: Building with python3 works provided you don't build V8. :sunglasses:

This formula _does_ build V8, if I'm reading it correctly. I suggest wrapping up this PR first, then you can open a separate one to do the migration.

**Comment by bayandin** [comment]
> This formula _does_ build V8, if I'm reading it correctly. I suggest wrapping up this PR first, then you can open a separate one to do the migration.

The formula itself doesn't, but `deno` uses [`rusty_v8`](https://github.com/denoland/rusty_v8) which could build it.

**Comment by carlocab** [comment]
Rust PR merged. Thanks for waiting, @chimurai.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
Thanks all, merging! :)

**Comment by carlocab** [comment]
Seems to succeed on 10.14 but not on 10.15 and 11.0. Do we know if `deno` is compatible with Xcode 12.2?

**Comment by Rylan12** [comment]
Sorry, I think this will have a conflict now that #67043 is merged. I'll resolve and update here.

**Comment by chenrui333** [comment]
```
  error: error opening 'obj/third_party/zlib/zlib/crc32.o.d': No such file or directory
```

**Comment by carlocab** [comment]
Deno now has a 1.6.3 release. Maybe try that one?

**Comment by carlocab** [comment]
Yea I really don't get this formula. In between the current CI run and the previous one, nothing changed for 10.14. Still, 10.14 succeeded previously and yet failed now.

**Comment by asip** [comment]
Is this issue not useful ?
https://github.com/denoland/deno/issues/8992

**Comment by chimurai** [comment]
See if Deno 1.7.0 release will build 🤞

**Comment by carlocab** [comment]
@asip it is not, unfortunately. We already use the `--locked` flag with `cargo install`.

**Comment by carlocab** [comment]
Let's try it without my changes to the build.

**Comment by carlocab** [comment]
[This](https://github.com/Homebrew/homebrew-core/pull/66920/checks?check_run_id=1741214532#step:7:9868) is weird:
```
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
```

**Comment by bayandin** [comment]
Shall we try to build if for Apple Silicon as well next time?

**Comment by carlocab** [comment]
Yes. I'd love ideas on how to fix the Catalina build tho.

**Comment by chrmoritz** [comment]
> 
> 
> Ok, better than last time, where the [Mojave runner failed too](https://github.com/Homebrew/homebrew-core/runs/1735172182). The failure is totally uninformative as usual though.

The error is in the gn / rusty_v8 part and at about 60% through the log:

```
[207/1259] LIBTOOL-STATIC obj/v8/libv8_libplatform.a
  FAILED: obj/v8/libv8_libplatform.a 
  rm -f obj/v8/libv8_libplatform.a && TOOL_VERSION=1611011547 python ../../../../../../../Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/toolchain/mac/filter_libtool.py /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static  -o obj/v8/libv8_libplatform.a -filelist obj/v8/libv8_libplatform.a.rsp
  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file list file: obj/v8/libv8_libplatform.a.rsp (No such file or directory)
```

**Comment by carlocab** [comment]
I think those come from my having removed the Xcode build dependency. I couldn't find any documentation about it being needed, whether in Deno's or rusty_v8's docs, so I thought it would be safe to remove.

**Comment by chrmoritz** [comment]
> 
> 
> I think those come from my having removed the Xcode build dependency. I couldn't find any documentation about it being needed, whether in Deno's or rusty_v8's docs, so I thought it would be safe to remove.

I'm pretty sure the V8 build has some hard coded requirement on XCode in it's build system and doesn't support CLT only systems.

**Comment by carlocab** [comment]
>I'm pretty sure the V8 build has some hard coded requirement on XCode in it's build system and doesn't support CLT only systems.

I believe that; it's just not mentioned in their docs. (They even [explicitly](https://deno.land/manual@v1.7.0/contributing/building_from_source#building-deno) only require CLT, and mention that you don't need it if you have Xcode.)

>On the other hand I'm not sure if removing that requirement is relevant for the error on systems where XCode is at least still installed and accessible.

Superenv changes environment variables depending on the declared dependencies though. For example, without the Xcode build dependency, `HOMEBREW_SDKROOT` is

```
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

With it, it looks something like
```
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

**Comment by chrmoritz** [comment]
> I believe that; it's just not mentioned in their docs. (They even [explicitly](https://deno.land/manual@v1.7.0/contributing/building_from_source#building-deno) only require CLT, and mention that you don't need it if you have Xcode.)

But this doc are for people who use their prebuilt (rusty_)V8 binary and not accurate if you build all dependencies, including (rusty_)V8 from source.

> Superenv changes environment variables depending on the declared dependencies though.

Okay, that might be the cause then. It's still strange that the build failures aren't deterministic and seem to fail randomly on different paths. But maybe the CLT `HOMEBREW_SDKROOT` is causing some issues with V8 build system which hard codes XCode somewhere else. 🤷

**Comment by carlocab** [comment]
Ok, looks like 10.15 failed in https://github.com/Homebrew/homebrew-core/pull/66920/commits/77e4ad870875fb3666c56650622bafc01e7401e2 long before it decided to stop: https://github.com/Homebrew/homebrew-core/runs/1741214532#step:7:6447

I wonder if there's some sort of `FAIL_FAST` option...

**Comment by carlocab** [comment]
>But this doc are for people who use their prebuilt (rusty_)V8 binary and not accurate if you build all dependencies, including (rusty_)V8 from source.

Yup, I had a look at the rusty_V8 docs too. No mention of Xcode. Though, I suppose this isn't as carefully documented if they just fully intend for you to download a binary.

**Comment by carlocab** [comment]
> It's still strange that the build failures aren't deterministic and seem to fail randomly in different steps.

Yes. See https://github.com/Homebrew/homebrew-core/pull/66920#issuecomment-753236604

**Comment by chrmoritz** [comment]
> 
> 
> > But this doc are for people who use their prebuilt (rusty_)V8 binary and not accurate if you build all dependencies, including (rusty_)V8 from source.
> 
> Yup, I had a look at the rusty_V8 docs too. No mention of Xcode. Though, I suppose this isn't as carefully documented if they just fully intend for you to download a binary.

Yeah, the complicated why Chromiums tries to find the macOS SKD is here: 
* https://github.com/denoland/chromium_build/blob/5fb411ddc335f0d76a12033d7b0a707f9ed89048/config/mac/mac_sdk.gni
* https://github.com/denoland/chromium_build/blob/5fb411ddc335f0d76a12033d7b0a707f9ed89048/mac/find_sdk.py

**Comment by carlocab** [comment]
Talk about non-deterministic. Compare:

https://github.com/Homebrew/homebrew-core/commit/54c027e24f0ba91816ff906af17efe05d1b5d663 with CI logs at https://github.com/Homebrew/homebrew-core/runs/1745216015

vs

https://github.com/Homebrew/homebrew-core/commit/77e4ad870875fb3666c56650622bafc01e7401e2 with CI logs at https://github.com/Homebrew/homebrew-core/runs/1741214515

Is it just me, or are these two identical formulae with exactly opposing outcomes?

**Comment by carlocab** [comment]
Ok, I patterned this latest commit after https://github.com/carlocab/homebrew-personal/pull/30/commits/0ab0b25c77e2ad47fbb3f17bac9f00341b76c1d1 which build successfully on GitHub runners (see https://github.com/carlocab/homebrew-personal/runs/1744816923).

Unfortunately, it also creates a runtime dependency on `llvm`, which isn't great.

**Comment by carlocab** [comment]
Ok, let's try to be at least a little systematic about this.

|Formula State|11-arm|11|10.15|10.14|CI Logs|
|---|:---:|:---:|:---:|:---:|---|
|54c027e24f0ba91816ff906af17efe05d1b5d663| ❌ | ❌ | ✅ | ❌ |https://github.com/Homebrew/homebrew-core/runs/1745215996|
|77e4ad870875fb3666c56650622bafc01e7401e2| ✅ | ✅ | ❌ | ✅ | https://github.com/Homebrew/homebrew-core/runs/1741214532|
|10834714c2dc1339e4aec483113a64530dfde1dc| ✅ | ✅ | ✅ | ❌ | https://github.com/Homebrew/homebrew-core/runs/1746847316|

**Comment by carlocab** [comment]
Ok, the current version of the formula builds on:

|OS Version|Commit|CI Log|
|---|---|---|
|Mojave|cce5be149e0966ea37b85a073e270b23d028a6f5|https://github.com/Homebrew/homebrew-core/actions/runs/504751675|
|Catalina|https://github.com/carlocab/homebrew-personal/pull/32/commits/51f5900ed7a24e4d8ac3d6c4d00816aced32a428|https://github.com/carlocab/homebrew-personal/pull/32/checks?check_run_id=1752854844|
|Big Sur|https://github.com/carlocab/homebrew-personal/pull/32/commits/51f5900ed7a24e4d8ac3d6c4d00816aced32a428|https://github.com/carlocab/homebrew-personal/pull/32/checks?check_run_id=1752854830|
|Big Sur-ARM|cce5be149e0966ea37b85a073e270b23d028a6f5|https://github.com/Homebrew/homebrew-core/runs/1751756652?check_suite_focus=true|

Just not all at the same time. I guess if we just keep re-running CI, we'll get lucky and find a run where all of them succeed? Otherwise, I may try and merge a run where ARM and Mojave build, and just try to bottle for Catalina and Big Sur separately. (Not sure if `brew pr-pull` will let me do that tho?)

**Review by carlocab — APPROVED** [review]
I'm going to try to merge this and bottle for Big Sur separately.

**Comment by carlocab** [comment]
Big Sur bottle job: https://github.com/Homebrew/homebrew-core/runs/1753554159?check_suite_focus=true 🤞

**Comment by carlocab** [comment]
[Second bottle atttempt](https://github.com/Homebrew/homebrew-core/runs/1753788057?check_suite_focus=true) succeeded: 5c23efe1564d77603259fa6deecfeba9a2fd70e0

Thanks for the help all!

**Comment by carlocab** [comment]
Non-deterministic builds reported at https://github.com/denoland/deno/issues/9244.

**Pull request closed without merging**
