### PR TITLE
cbmc 5.12.6

### PR DESCRIPTION
**Pull request by hannes-steffenhagen-diffblue**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is tagged as a pre-release on github

**Comment by dtrodrigues** [comment]
It looks like the audit pre-release check only looks for GitHub release URLs and not tags:
https://github.com/Homebrew/brew/blob/fb5b541dcdcaebe5f48a0042ce367623086797f6/Library/Homebrew/dev-cmd/audit.rb#L784-L801

**Comment by dtrodrigues** [comment]
I suppose tags themselves don't have a pre-release status, but the corresponding GitHub release may. I'm not sure if it's worth trying to go from tag to release to pre-release status or only do the pre-release checks when a GitHub release is given.

**Comment by chenrui333** [comment]
> This is tagged as a pre-release on github

we had this discussion before around the tags auditing. So for many formuale that they insist to use prerelease tag for all pre-v1.0.0 releases. I guess it does not quite apply in here.

But the rationale is if we have merge/release one pre-release before, then we can keep releasing prereleases. I will ask upstream to see if they can have a latest release some time soonish.

**Comment by hannes-steffenhagen-diffblue** [comment]
Hi, maintainer here. We’ve been tagging releases as pre-releases for now as we are migrating to a new release process rather than the ad-hoc one we had before. We’re not quite done with setting up everything that we wanted for that (e.g. regular automatic releases of Debian packages and such), and this is all the meaning we’ve attached to that. If this is problematic over here we can change it.

The plan was basically to have biweekly releases like this going forward, but if this is too frequent or unstable for homebrew-core we can also just provide our own tap, I just thought that since CBMC already has a Formula here it would be better to update that instead.

**Comment by chenrui333** [comment]
yeah, we have no issue with the release cadence, but more questions regarding the tags usage. we can consolidate the conversations in the cbmc side. I will go with a merge for this PR. :)

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
