### PR TITLE
buku 2.8

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
Gotta love updating the resources... At least I just wrote a poet wrapper, so now the process has been simplified to

```sh
mktmpenv
multipoet urllib3 cryptography beautifulsoup4 requests
brew edit buku
deactivate
```

**Comment by zmwangx** [comment]
Not sure why this is failing on CI. Works fine locally.

**Comment by ilovezfs** [comment]
@zmwangx This will fix it:
```
diff --git a/Formula/buku.rb b/Formula/buku.rb
index 499e63a..b291b0c 100644
--- a/Formula/buku.rb
+++ b/Formula/buku.rb
@@ -67,7 +67,22 @@ class Buku < Formula
 
   def install
     venv = virtualenv_create(libexec, "python3")
-    venv.pip_install resources
+    resource("cryptography").stage do
+      if MacOS.version < :sierra
+        # Fixes .../cryptography/hazmat/bindings/_openssl.so: Symbol not found: _getentropy
+        # Reported 20 Dec 2016 https://github.com/pyca/cryptography/issues/3332
+        inreplace "src/_cffi_src/openssl/src/osrandom_engine.h",
+          "#elif defined(BSD) && defined(SYS_getentropy)",
+          "#elif defined(BSD) && defined(SYS_getentropy) && 0"
+      end
+      venv.pip_install Pathname.pwd
+    end
+
+    res = resources.map(&:name).to_set - ["cryptography"]
+
+    res.each do |r|
+      venv.pip_install resource(r)
+    end
 
     # Replace shebang with virtualenv python
     inreplace "buku.py", "#!/usr/bin/env python3", "#!#{libexec}/bin/python"
@@ -80,6 +95,7 @@ class Buku < Formula
   end
 
   test do
+    ENV["LC_ALL"] = "en_US.UTF-8"
     ENV["XDG_DATA_HOME"] = "#{testpath}/.local/share"
 
     # Firefox exported bookmarks file
```

**Comment by zmwangx** [comment]
@ilovezfs Thanks for looking into this.

What a lovely bug.

```
> grep -rI 'resource "cryptography"' | wc -l
14
```

**Comment by ilovezfs** [comment]
>What a lovely bug.

Yeah, it's pretty bad. `pillow` is in the same boat, prevalent as a resource and afflicted by a non-trivial bug we patch via copy-paste.

**Comment by ilovezfs** [comment]
:1st_place_medal:

**Comment by zmwangx** [comment]
@ilovezfs You're the 🥇 of PR emojis.

**Comment by ilovezfs** [comment]
@zmwangx well I know how much you :heart: them

**Comment by zmwangx** [comment]
🙅‍♂️

**Pull request closed without merging**
