### PR TITLE
screenpipe 0.2.5

### PR DESCRIPTION
**Pull request by louis030195**
Automated update to version 0.2.5

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@louis030195 your base branch is outdated.

**Comment by p-linnane** [comment]
I've rebased this. @louis030195 please run `brew update` before your next PR. Thanks!

**Comment by chenrui333** [comment]
```
    --- stderr
    2024-11-27 17:35:46.688 xcodebuild[28421:72332] [MT] DVTDownloadable: Error creating downloadable cache directory file:///Users/brew/Library/Caches/com.apple.dt.Xcode/Downloads/
    2024-11-27 17:35:48.831 xcodebuild[28421:72410] NetworkStorageDB:_openDBReadConnections: failed to open read connection to DB @ /Users/brew/Library/Caches/com.apple.dt.xcodebuild/Cache.db.  Error=14. Cause=unable to open database file
    2024-11-27 17:35:48.832 xcodebuild[28421:72410] The read-connection to the DB=/Users/brew/Library/Caches/com.apple.dt.xcodebuild/Cache.db is NOT valid.  Unable to determine schema version.
    2024-11-27 17:35:48.832 xcodebuild[28421:72410] NetworkStorageDB:_openDBWriteConnections: failed to open write connection to DB @ /Users/brew/Library/Caches/com.apple.dt.xcodebuild/Cache.db.  Error=14. Cause=unable to open database file
    2024-11-27 17:35:48.832 xcodebuild[28421:72410] DEBUG: there is no SQL cache DB located at /Users/brew/Library/Caches/com.apple.dt.xcodebuild/Cache.db.
    2024-11-27 17:35:48.832 xcodebuild[28421:72410] DEBUG: there is no SQL cache DB located at /Users/brew/Library/Caches/com.apple.dt.xcodebuild/Cache.db-shm.
    2024-11-27 17:35:48.832 xcodebuild[28421:72410] DEBUG: there is no SQL cache DB located at /Users/brew/Library/Caches/com.apple.dt.xcodebuild/Cache.db-wal.
    2024-11-27 17:35:49.036 xcodebuild[28421:72348] writeDBwithCachedResponse-ERROR: (_dbWriteConnection=0x152edff90) insert SQL stmnt. is nil for storage: /Users/brew/Library/Caches/com.apple.dt.xcodebuild
    ** BUILD FAILED **
```

**Comment by chenrui333** [comment]
#199395

**Comment by chenrui333** [comment]
#199398

**Comment by chenrui333** [comment]
@louis030195 please fix the current build before making more releases.

**Pull request closed without merging**
