### PR TITLE
gstreamer: generate script for base and ges tools

### PR DESCRIPTION
**Pull request by dabrain34**
Generate script for the tools where the GST_PLUGIN_SYSTEM_PATH is defined properly

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by sdroege** [comment]
Don't create more hacks for working around packaging mistakes in the GStreamer recipes. See https://github.com/orgs/Homebrew/discussions/3740 for the proper solution.

**Comment by dabrain34** [comment]
I gave a try to a fresh Linux toolbox to check what was occuring and it seems to work fine without GST_PLUGIN_SYSTEM_PATH. 

So I guess the patch would be more to remove the line than adding in gst-plugins-base
`bin.env_script_all_files libexec/"bin", GST_PLUGIN_SYSTEM_PATH: HOMEBREW_PREFIX/"lib/gstreamer-1.0"` in gstreamer recipe.

**Comment by timvahlbrock** [comment]
Origin of this MR: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1702

**Comment by chenrui333** [comment]
Can someone volunteer to merge the gstreamer formulae?

**Comment by carlocab** [comment]
Note: This should no longer be an issue with the latest build of GStreamer. Feel free to file an issue if it's still causing you problems.

**Pull request closed without merging**
