### PR TITLE
cryptol: GHC 8 compatibility

### PR DESCRIPTION
**Pull request by ilovezfs**
Uses an upstream commit already in Cryptol's master plus a PR opened by
Tom Kerckhove to patch the closely coupled dependency SBV:

https://github.com/GaloisInc/cryptol/pull/317
https://github.com/LeventErkok/sbv/pull/219

### CODE REVIEW

**Comment by ilovezfs** [comment]
:8ball: :fire: 

```
 cd("sbv-5.11") { system "patch", "-p1", "-i", buildpath/"219.diff" }
```

In the absence of the ability to add `patch do` blocks to `resource do` blocks, does anyone have a better idea? I'm perfectly happy with it as-is, but don't want to be :gun:

**Comment by DomT4** [comment]
Do either of those need applying to `HEAD` in the formula?

The mechanism is kind of grim but I think it's the best we can hope for until we get resource patching sorted, so 👍.

**Comment by ilovezfs** [comment]
Nice catch. The first one is from HEAD, so should be in a stable block. The one for the dependency is needed for both stable and HEAD.

**Comment by MikeMcQuaid** [comment]
👍 

> In the absence of the ability to add patch do blocks to resource do blocks, does anyone have a better idea? I'm perfectly happy with it as-is, but don't want to be 🔫

That's the best thing for now but 👍 to making `resource do` support a `patch do`

**Pull request closed without merging**
