### PR TITLE
gnu-getopt: upstream Linux fix

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I believe this is the right way to make this keg-only on both platforms, but let me know if something else should be done.

**Review by carlocab — COMMENTED** [review]
This changes behaviour of the formula though. `:provided_by_macos` formulae cannot be `brew link`ed, even with `--force`.

**Comment by danielnachun** [comment]
Is there a way for us to preserve that behavior on macOS and also make it keg-only on Linux?  `keg_only` is currently not allowed inside an `on_linux do` block (which I suppose we could change).

**Comment by danielnachun** [comment]
Can I get a review on this?  This should preserve the behavior on macOS and also make this keg-only on Linux.

**Review by iMichka — APPROVED** [review]

**Pull request merged**
