### PR TITLE
byteman: fix test

### PR DESCRIPTION
**Pull request by jonchang**
Supports https://github.com/Homebrew/homebrew-core/pull/69460

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> /opt/homebrew/Cellar/byteman/4.0.12/bin/bmjava -l brew.btm -cp src/main/java BytemanHello
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
Error: byteman: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <"Entering main\n" + "Hello, Brew!\n" + "Exiting main\n"> expected but was
<"Hello, Brew!\n">.
```
Kinda weird that the output is different on ARM...

**Comment by jonchang** [comment]
Wow. Yeah, that is baffling.

**Comment by carlocab** [comment]
On the one hand, I get the impression that it's not broken. On the other, well. It's weird.

**Comment by jonchang** [comment]
Oh, that actually makes a lot of sense. It's possible that the `traceln` output is getting sent to stderr or something.

**Comment by jonchang** [comment]
I've cherry picked the other three patches and left byteman in this PR while I investigate.

**Comment by jonchang** [comment]
Yeah, it's an openjdk 16 thing. I downloaded adoptopenjdk beta 16 for intel macOS and could repro the test failure.

**Review by carlocab — APPROVED** [review]

**Comment by jonchang** [comment]
Thanks for pointing me in the right direction!

**Comment by carlocab** [comment]
No thanks needed; you did all the hard work.

**Pull request merged**
