### PR TITLE
mariadb 10.5.11

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Related attempts: #79696, #76887

**Comment by Moisan** [comment]
I was hoping that the new release would fix some of these.

**Comment by carlocab** [comment]
The build failure appears to be a different issue. Also, it looks like it's building its own PCRE2. Not cool.

**Comment by Moisan** [comment]
> Also, it looks like it's building its own PCRE2. Not cool.

The formula currently includes this option: `-DWITH_PCRE=bundled`. 

Let's try to depend on `pcre2`.

**Comment by carlocab** [comment]
Here's the problem:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gm4: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/bison//tmp/mariadb-20210627-91867-1nl0oq6/mariadb-10.5.11/sql/myskel.m4: No such file or directory
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: subsidiary program `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gm4' failed (exit status 1)
```

The build appears to be confused about where `myskel.m4` is. Presumably it is supposed to be in
```
/tmp/mariadb-20210627-91867-1nl0oq6/mariadb-10.5.11/sql
```
but for some reason the build is looking for it in
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/bison//tmp/mariadb-20210627-91867-1nl0oq6/mariadb-10.5.11/sql/myskel.m4
```

**Comment by carlocab** [comment]
Using newer `bison` seems to have fixed the earlier build failure, but also exposed the `#include <version>` bug.

**Pull request closed without merging**
