### PR TITLE
gr-osmosdr 0.2.0

### PR DESCRIPTION
**Pull request by shwang53**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
This is blocked on #49733.

**Comment by chenrui333** [comment]
<details>
<summary>Build failure</summary>
```
00:19:14 writing list of installed files to 'installed.txt'
00:19:14 ==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gr-osmosdr/0.2.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
00:19:14 -- The CXX compiler identification is AppleClang 11.0.0.11000033
00:19:14 -- The C compiler identification is AppleClang 11.0.0.11000033
00:19:14 -- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
00:19:14 -- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -- works
00:19:14 -- Detecting CXX compiler ABI info
00:19:14 -- Detecting CXX compiler ABI info - done
00:19:14 -- Detecting CXX compile features
00:19:14 -- Detecting CXX compile features - done
00:19:14 -- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang
00:19:14 -- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -- works
00:19:14 -- Detecting C compiler ABI info
00:19:14 -- Detecting C compiler ABI info - done
00:19:14 -- Detecting C compile features
00:19:14 -- Detecting C compile features - done
00:19:14 CMake Error at CMakeLists.txt:45 (find_package):
00:19:14   Could not find a configuration file for package "Gnuradio" that is
00:19:14   compatible with requested version "3.8".
00:19:14 
00:19:14   The following configuration files were considered but not accepted:
00:19:14 
00:19:14     /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.7.13.4
00:19:14     /usr/local/opt/gnuradio/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.7.13.4
00:19:14 
00:19:14 
00:19:14 
00:19:14 -- Configuring incomplete, errors occurred!
00:19:14 See also "/tmp/gr-osmosdr-20200303-49330-gru54d/gr-osmosdr-0.2.0/CMakeFiles/CMakeOutput.log".
```
</details>

**Comment by issyl0** [comment]
Blocked on a draft PR that seems stalled. Closing.

**Pull request closed without merging**
