### PR TITLE
Apache flink 1.4.0

### PR DESCRIPTION
**Pull request by juanmirocks**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
I'd be surprised to know how that pull request could pass `brew install` or `brew audit` with wrong SHA-256 sums 🤨

**Comment by fxcoudert** [comment]
Doesn't seem to work on Java 9. Please report it upstream, so they can fix it (and we can ship new versions).

**Comment by juanmirocks** [comment]
The library doesn't work with scala 2.12 either, and the current version (1.3.2) doesn't work either with java 9 / scala 2.12. 

I see no reason why we cannot update the formula now. But yes, the version range should be defined.

_The next version of apache-flink (1.5.0) will [support Java 9](https://issues.apache.org/jira/browse/FLINK-8033) & [scala 2.12](https://issues.apache.org/jira/browse/FLINK-7811?jql=project%20%3D%20FLINK%20AND%20text%20~%202.12), but still, I think we can update now._

**Comment by ilovezfs** [comment]
@juanmirocks Our CI boxes have both Java 9 and Java 8 installed. If this must use Java 8, it needs to find a way to do so successfully in such a setup. Typically we use a wrapper script but that may prove a tad trickier here.

```
brew cask install java
brew cask install caskroom/versions/java8
```

if you want to work on this.

See

ammonite-repl
apache-geode
app-engine-java
aspectj
bazel
commandbox
druid
elasticsearch
gosu
grakn
htmlcleaner
infer
jmxtrans
kafka
libbluray
libtensorflow
logstash
logstash@5.6
metabase
payara
planck
ringojs
scm-manager
yeti

for examples.

**Comment by juanmirocks** [comment]
@ilovezfs great, I will try.

Question: is it possible to define a range version like: `depends_on :java => ["1.7, "1.8"]` ?

**Comment by ilovezfs** [comment]
No we're just passing that string to the `java_home` command. So if you need < 9.0 then you must specifically require 1.8 as only a + operator is supported unless there's some undocumented java_home feature I don't know about.

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ /usr/libexec/java_home -v 1.6
Unable to find any JVMs matching version "1.6".
/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
iMac-TMP:~ joe$ /usr/libexec/java_home -v 1.6+
/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
iMac-TMP:~ joe$ /usr/libexec/java_home -v 1.7
/Library/Java/JavaVirtualMachines/zulu-7.jdk/Contents/Home
iMac-TMP:~ joe$ /usr/libexec/java_home -v 1.7+
/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
iMac-TMP:~ joe$ /usr/libexec/java_home -v 1.8
/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
iMac-TMP:~ joe$ /usr/libexec/java_home -v 1.8+
/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
iMac-TMP:~ joe$ /usr/libexec/java_home -v 9.0
/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
iMac-TMP:~ joe$ /usr/libexec/java_home -v 9.0+
/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
```

**Pull request closed without merging**
