### PR TITLE
Added gitfame formula

### PR DESCRIPTION
**Pull request by ArtSabintsev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I added my formula, `gitfame`, which installs locally, but the audit crashes.

```
brew audit --strict gitfame
Error: A JSON text must at least contain two octets!
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:77:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:45:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:71:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

### CODE REVIEW

**Comment by AliSoftware** [comment]
Could you ensure that you have the latest version of Homebrew?

**Comment by ArtSabintsev** [comment]
```
brew --version
Homebrew 1.1.11-3-gec7530b
Homebrew/homebrew-core (git revision 05e3; last commit 2017-03-07)
```

**Comment by ArtSabintsev** [comment]
OK, the CI returned this:

```
Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.1
Successfully installed ast-2.3.0
Successfully installed parser-2.4.0.0
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.1.3
Successfully installed rubocop-0.47.1
7 gems installed
Error: 4 problems in 1 formula
gitfame:
  * Description shouldn't start with an indefinite article (A)
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
  * xcodebuild should be passed an explicit "SYMROOT"
```

**Comment by AliSoftware** [comment]
First and last are easy to fix. Indeed you should pass a `SYMROOT` and make the generated binary be copied into `bin/'gitfame'`

Alternatively, given that your tool is a single `main.swift` file without dependency, it can easily be converted into a Swift _script_ (just add the shebang at the top of your file, `chmod +x` the file, and rename it `gitfame`). This would make it already standalone — users can just download the `gitfame` script file, install it into `/usr/local/bin` or in any directory in their `$PATH` and it can be executed by anyone having the swift interpreted installed — so not sure it's worth compiling it and having a homebrew formula for it might then be overkill?

**Comment by ArtSabintsev** [comment]
Fixed the first and last one. All that's left is the _notability_ and _newness_ constraints:

 * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
 * GitHub repository too new (<30 days old)

**Comment by fxcoudert** [comment]
Sorry, the repo is pretty far from our quite lenient notability criteria. We also generally prefer that packages be submitted by someone other than their primary maintainer — it gives us an indication that a community will be keeping the package alive. You should consider hosting this formula in a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by ArtSabintsev** [comment]
Out of curiosity, does the script need to meet one or all of the stars/forks/watchers minimum?

In other words, does 50 stars, but 0 watchers/forks still qualify?

**Comment by fxcoudert** [comment]
The script is quite lenient, actually. Our goal is to have formulas for that have widespread use, and we have to draw the line somewhere.

The good news is: [external Homebrew taps](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) can be created and maintained by anyone, and are just a single extra command for the user.

**Comment by ArtSabintsev** [comment]
got it - thanks @fxcoudert

**Pull request closed without merging**
