### PR TITLE
sourcery 0.10.1

### PR DESCRIPTION
**Pull request by Antondomashnev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Antondomashnev what is the status of the commented out tests? https://github.com/krzysztofzablocki/Sourcery/pull/133 was merged but they're still disabled.

**Comment by Antondomashnev** [comment]
@ilovezfs you're right, but the uncommenting test code didn't help. Check my last comment in https://github.com/Homebrew/homebrew-core/pull/9191 - maybe you have some ideas.

**Comment by Antondomashnev** [comment]
@ilovezfs could you please merge the PR? 😄

**Comment by Mazyod** [comment]
@ilovezfs since 0.10.0 breaks sourcery for homebrew users, it is painful for us users waiting for this upgrade :) Thanks for all your efforts, just wanted to share our experience

**Comment by klundberg** [comment]
Agreed, please merge this PR in if there's nothing else at issue! I'd love to be able to use the latest version via homebrew

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@Antondomashnev I'm removing the broken test block so that this stops coming up.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @Antondomashnev! Shipped.

**Pull request closed without merging**
