### PR TITLE
erlang 24.3.4

### PR DESCRIPTION
**Pull request by alaadahmed**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
build patch failed for the PR

**Comment by alaadahmed** [comment]
So what does this mean? What should I do?

**Comment by leoliu** [comment]
The patch that was introduced for https://github.com/Homebrew/homebrew-core/pull/99206 is not needed any more.

**Comment by alaadahmed** [comment]
OK now this makes sense

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
