### PR TITLE
tig: add `ncurses` dependency

### PR DESCRIPTION
**Pull request by IanEdington**
`tig` is not using the brew version of ncurses

As per this issue in tig, it seems that vim and other cli's use the brew version of ncurses and `tig` uses the system version.

https://github.com/jonas/tig/issues/1210
I've confirmed this resolves the above issue

Also I saw this PR from 5 years ago. The reasoning doesn't seem like it makes sense now that ncurses is a fairly ubiquitous dependency. https://github.com/Homebrew/homebrew-core/pull/18934

TBH I don't now the impacts of this but it seems like a reasonable solution so feel free to close if it's not.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Can you bump the `revision` so that users who have this installed get the updated version of the formula with `brew upgrade`?

Please amend your existing commit when you do so (instead of adding new ones to your PR).

**Comment by IanEdington** [comment]
ok done! Thanks for the guidance.

**Review by carlocab — DISMISSED** [review]
Thanks for your contribution!

For future reference, our commit messages (for changes that are not version bumps) are formatted like so:
```
tig: add `ncurses` dependency
```
or similar, as in your PR title.

I've fixed that up for you.

**Comment by carlocab** [comment]
By the way, you may find this guide to using `tmux-256color` on macOS useful: https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/

**Comment by IanEdington** [comment]
That worked beautifully, thank you

**Review by SMillerDev — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
