### PR TITLE
protobuf 3.10.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
23:46:35 ==> /usr/bin/clang++ test.cpp -std=c++11 -I/usr/local/Cellar/apache-arrow/0.14.1_2/include -L/usr/local/Cellar/apache-arrow/0.14.1_2/lib -larrow -o test
23:46:35 ==> ./test
23:46:35 dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.20.dylib
23:46:35   Referenced from: /usr/local/opt/apache-arrow/lib/libarrow.14.dylib
23:46:35   Reason: image not found
23:46:35 Error: apache-arrow: failed
23:46:35 Failed executing:

**Comment by chenrui333** [comment]
Broken dependencies for the other formula.

**Comment by scpeters** [comment]
we typically need to bump revisions on several dependents of protobuf; compare the file bumped in #40438 with the list of CI failures

**Comment by chenrui333** [comment]
Thanks for weighing in on this, I will do the similar thing now.

**Comment by scpeters** [comment]
thanks!

**Pull request closed without merging**
