### PR TITLE
Remove universal support, except for wine dependencies

### PR DESCRIPTION
**Pull request by fxcoudert**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is based on #9641, where I have fixed the comments by @ilovezfs. It removes the universal option from 147 formulas, but does not touch the 17 formulas that are `wine` dependencies (as they need to be vendored into the wine formula before universal is removed from them).

### CODE REVIEW

**Comment by DomT4** [comment]
I don't know how much it matters really but if you expand the scope of this to cover `--include-optional` on the `wine` deps more from this list appear.

**Comment by fxcoudert** [comment]
PS: I've also fixed the `openssl@1.1` changes which were incorrect (the few lines after `next unless build.universal?` needed to be removed, otherwise the logic is wrong).

**Comment by fxcoudert** [comment]
The wine optional dependencies that have universal build are: `bdw-gc giflib libgsm python readline xz`. I can remove them from the PR if maintainers wish it so.

**Comment by JCount** [comment]
This probably needs to be split into multiple PRs.

**Comment by fxcoudert** [comment]
Too big for testing, closing.

**Pull request closed without merging**
