### PR TITLE
erlang: Add doc chunks + escript test

### LINKED ISSUE #55217: Erlang/OTP 23 missing doc chunks
Not really relevant, see rest of issue below (although I did run `brew doctor` and verified it does not affect my Erlang installation).

- [x] ~ran `brew update` and can still reproduce the problem?~
- [x] ~ran `brew doctor`, fixed all issues and can still reproduce the problem?~
- [ ] ~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~
- [ ] ~if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~

## What you were trying to do (and why)

Erlang/OTP 23 introduced doc chunks, a standardized way of storing documentation in BEAM files. Unfortunately the brew formulae does not build these.

## What happened (include command output)

```console
$ erl # Open an Erlang shell
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.0  (abort with ^G)
1> h(lists). % Try to access the documentation for `lists`

   lists

  There is no documentation for lists
ok
2>
```

## What you expected to happen

```console
$ erl # Open an Erlang shell
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V11.0  (abort with ^G)
1> h(lists). % Try to access the documentation for `lists`

   lists

  This module contains functions for list processing.

  Unless otherwise stated, all functions assume that position numbering
  starts at 1. That is, the first element of a list is at position 1.
more (y/n)? (y) n
ok
2>
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```console
$ brew install erlang # works
$ erl # open an Erlang shell
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.0  (abort with ^G)
1> h(lists). % Try to access the documentation for `lists`
```

You can use [kerl][], or [asdf-erlang][] that uses [kerl][] under the hood, to build your own Erlang distribution. That one will include the chunks.

Using `kerl`:
```console
$ export KERL_BUILD_DOCS=yes
$ export KERL_DOC_TARGETS=chunks # Should be the default, but better safe then sorry
$ kerl build 23.0.1 23.0.1
$ kerl install 23.0.1 /your/favourite/path/to/23.0.1
```

Using `asdf`
```console
$ export KERL_BUILD_DOCS=yes
$ export KERL_DOC_TARGETS=chunks # Should be the default, but better safe then sorry
$ asdf install erlang 23.0
$ asdf shell erlang 23.0
```

I'm not too familiar with the building process, but these two issue in [kerl][] should hopefully be enough to port over the change to `brew`.

https://github.com/kerl/kerl/issues/334
https://github.com/kerl/kerl/pull/336

[kerl]: https://github.com/kerl/kerl
[asdf-erlang]: https://github.com/asdf-vm/asdf-erlang

### PR DESCRIPTION
**Pull request by gromgit**
Documentation chunks are a new feature in 23.0, enabling inline
man pages for the interactive Erlang shell. Building these chunks
also builds man pages, so the "man" resource is no longer needed,
but it requires "fop" at build time.

An escript test has also been added, to verify that Erlang scripts
can be run correctly.

Closes #55217.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
failed with rabbitmq test build on 10.15, which is expected.

Proceed with a merge

**Comment by chenrui333** [comment]
@gromgit should we add this similar change into the other versioned formulae as well?

**Comment by gromgit** [comment]
> @gromgit should we add this similar change into the other versioned formulae as well?

Well, the docchunk one only applies to this version, but yeah, I'll add the escript test to the other versions.

**Comment by chenrui333** [comment]
Thanks!

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/issues/61770

**Pull request closed without merging**
