### PR TITLE
protobuf 26.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by scpeters** [comment]
I saw the following comment in https://github.com/Homebrew/homebrew-core/pull/166096

> Using Python bindings with C++ backend is deprecated and we are removing them from formula in https://github.com/Homebrew/homebrew-core/pull/166008. Officially need to use PyPI source to build with UPB backend (or Bazel in git source but usually better to avoid Bazel).

Is this a change for `protobuf` only, or is this a policy change for all homebrew formulae (deprecation of python bindings with c++ backend)? If it's a broader change and there's a tracking issue, apologies that I've missed it, and I would appreciate if you could share a link to it.

If this is only for `protobuf`, then carry on!

**Comment by chenrui333** [comment]
@scpeters only for protobuf at the moment

**Comment by cho-m** [comment]
> Is this a change for `protobuf` only, or is this a policy change for all homebrew formulae (deprecation of python bindings with c++ backend)?

> only for protobuf at the moment

Specifically, we are following upstream instructions. If upstream supports Python bindings with C++ backend, we will keep them.

Protobuf doesn't want users to build this anymore - https://github.com/protocolbuffers/protobuf/commit/5722aeffcad72e9a335a3ec7985858dfa31477be

**Comment by scpeters** [comment]
> > Is this a change for `protobuf` only, or is this a policy change for all homebrew formulae (deprecation of python bindings with c++ backend)?
> 
> > only for protobuf at the moment
> 
> Specifically, we are following upstream instructions. If upstream supports Python bindings with C++ backend, we will keep them.
> 
> Protobuf doesn't want users/downstreams to build this anymore - [protocolbuffers/protobuf@5722aef](https://github.com/protocolbuffers/protobuf/commit/5722aeffcad72e9a335a3ec7985858dfa31477be)

thanks for the info!

**Comment by scpeters** [comment]
glancing at the `grpc` failure, it looks like it is caused by an API change in protobuf and needs https://github.com/grpc/grpc/pull/35898

**Comment by cho-m** [comment]
Need to figure out how to deal with `or-tools`. It is only compatible with Protobuf 25. I did try building bundled copy but that links conflicting libs into `HOMEBREW_PREFIX`. Given that it is only a single formula, I may just resource Protobuf 25 into `libexec` but will need to figure out how to fix up CMake files to pick correct copy.

Other failures are:
* `bear` - https://github.com/rizsotto/Bear/commit/4d9d4525cd3d1ad11761c79ca71645946f48e07c
* `mavsdk` - need to regenerate files with newer protoc
* `nanopb` - will need a virtualenv for `protobuf` python libs
* `sysdig` - revision bump

**Comment by fxcoudert** [comment]
The `no long build conflict` label is preventing https://github.com/Homebrew/homebrew-core/pull/166807#issuecomment-2026917770 from being merged. It this PR mergeable in current state, or can we remove it for now?

**Comment by cho-m** [comment]
> The `no long build conflict` label is preventing [#166807 (comment)](https://github.com/Homebrew/homebrew-core/pull/166807#issuecomment-2026917770) from being merged. It this PR mergeable in current state, or can we remove it for now?

Can remove tag for now.

There are currently 3 failures in this PR:
* `or-tools` (Linux) - test failure. could be RPATH. I may split out commit to separate PR as number of changes that need a proper review
* `fastnetmon` (12/13-x86_64) - test failure. may be sporadic given that it didn't happen in previous run.
* Dependents (12/13-x86_64) - both can't find `bear` bottle. I'm guessing bottle cache issue. May need to re-run without cache.

**Comment by cho-m** [comment]
> 26.1 got released (probably no incompatibility difference with 26.0, I guess?)

I'm aware, but previously didn't handle as wanted to speed up run via bottle cache. Previous comment:

> > EDIT: There is also a new minor version but I'm not sure if that will invalidate our bottle cache. So may just want to stick to current protobuf version

Since bottle cache may not have worked for `bear`, I'll probably update version for next run and invalidate the cache.

**Comment by cho-m** [comment]
Going to try `or-tools` upstream commit locally and then try another run with `protobuf 26.1` when long runner is free - https://github.com/google/or-tools/commit/e0a4dcf5a082e7f90b73708fc7ff4a5e4760ed85

**Comment by cho-m** [comment]
Accidentally broken the `or-tools` test for Linux as I forgot to handle RPATH. I do want to add a CMake test as it looks like a common use case rather than manually adding all the flags. I'll fix it in a follow up PR assuming no other issues.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
