### PR TITLE
deno 1.8.0

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Now picking up linkage with llvm. Weird. Would it help to remove llvm's `lib` directory from `HOMEBREW_LIBRARY_PATHS`?

**Comment by dtrodrigues** [comment]
Does it still depend on Python2? The linked issue in the formula implies it might not anymore.

**Comment by Bo98** [comment]
I think `rusty_v8` requires Python 2 still. I'll update the link to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=942720

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Failed on Mojave. My guess is that it's [this problem](https://github.com/denoland/deno/issues/9244), rather than anything actually being broken.

**Comment by carlocab** [comment]
Three different failures on the three Intel nodes.

**Comment by Bo98** [comment]
There's something quite wrong here - it looks like textbook parallelisation issues. Does the `v8` have issues or is it specific to `rusty_v8`?

**Comment by carlocab** [comment]
I think it's just `rusty_v8`. The last few `v8` version bumps (#71938, #71241, #6933, #68668, #66816) went off without incident.

`deno`, on the other hand... #66920

**Comment by Bo98** [comment]
This definitely looks wrong:

```
     Running `/private/tmp/deno-20210303-81966-1phq3cx/deno/target/release/build/rusty_v8-dd3a6944940e9e8a/build-script-build`
     Running `/private/tmp/deno-20210303-81966-1phq3cx/deno/target/release/build/rusty_v8-dd3a6944940e9e8a/build-script-build`
[rusty_v8 0.20.0] clang_base_path /usr/local/opt/llvm
[rusty_v8 0.20.0] clang_base_path /usr/local/opt/llvm
[rusty_v8 0.20.0] cargo:warning=Not using sccache or ccache
[rusty_v8 0.20.0] cargo:warning=Not using sccache or ccache
[rusty_v8 0.20.0] The current directory is /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.20.0
[rusty_v8 0.20.0] gn gen --root=/Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.20.0 /private/tmp/deno-20210303-81966-1phq3cx/deno/target/release/gn_out
[rusty_v8 0.20.0] The current directory is /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.20.0
[rusty_v8 0.20.0] gn gen --root=/Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/
```

Looks like `cargo` is triggering two parallel builds at the same time.

**Comment by Bo98** [comment]
I could easily disable parallel builds in `cargo`, and that will solve the failure. It would however be nice to avoid actually building things twice. I'm not entirely sure what `cargo` is doing here.

**Comment by Bo98** [comment]
(In theory this shouldn't make the `rusty_v8` part of the build any slower since the `ninja` invokation should still be fully parallel but we'll soon see.)

**Comment by Bo98** [comment]
Actually builds faster.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
