### PR TITLE
kops 1.9.0

### PR DESCRIPTION
**Pull request by mikesplain**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mikesplain** [comment]
I'll remove the beta in another PR

**Comment by mikesplain** [comment]
Or you can @ilovezfs 😄

**Comment by ilovezfs** [comment]
@mikesplain fyi if you make an edit like deleting the devel block manually first, it'll be preserved by bump-formula-pr when opening the pr.

**Comment by mikesplain** [comment]
Fair enough I wasn't sure how you prefer the PRs so I was going to separate it. Thanks!

**Comment by ilovezfs** [comment]
>wasn't sure how you prefer the PRs so I was going to separate it

audit will fail if devel version compares as < stable version so they "need" to be in the same PR to please the linter gods

**Comment by ilovezfs** [comment]
Thanks for the upgrade @mikesplain! 🚀

**Pull request closed without merging**
