### PR TITLE
httpie 0.9.4 (II.)

### PR DESCRIPTION
**Pull request by jkbrzt**
A replacement for #2555 with changes suggested by @ilovezfs.

### CODE REVIEW

**Comment by ilovezfs** [comment]
why are we switching to python3? is there no python2 support anymore?

**Comment by jkbrzt** [comment]
@ilovezfs please see https://github.com/jkbrzt/httpie/commit/2b0e6428424af581fd1663252d5c2212e31b2ce6

**Comment by ilovezfs** [comment]
@jkbrzt Ah, you are the upstream for this software?

**Comment by jkbrzt** [comment]
Yes, it's me 😃

**Comment by ilovezfs** [comment]
@jkbrzt then we're switching to python3 because you said so!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/44d0e8623185e3aa2d7dd09d02fa2bc921c2f5aa. Thank you for your contribution to Homebrew @jkbrzt; we appreciate it! :smiley_cat:

**Pull request closed without merging**
