### PR TITLE
marksman 2023-04-02

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
This version [requires dotnet 7](https://github.com/artempyanykh/marksman/releases/tag/2023-04-02). I took the liberty of making the change.

**Comment by chenrui333** [comment]
`Timeout::Error: execution expired`

**Comment by moonfruit** [comment]
@chenrui333 @Moisan Please review

**Comment by moonfruit** [comment]
I believe that both `null rooUri` and `Workspace folder is bogus` makes this.

See https://github.com/artempyanykh/marksman/blob/6be821098da55bd9bae4311934126e92f739d55f/Marksman/Server.fs#L42

**Comment by artempyanykh** [comment]
@moonfruit thanks. Yes, I remember this logic. The server should still initialise just without any folders. Not sure why it would hang. I'll need to look into it.

**Comment by artempyanykh** [comment]
Re: the above -- it's a bug. I'll push a fix shortly.

**Comment by artempyanykh** [comment]
It's probably best to go straight to [2023-04-06](https://github.com/artempyanykh/marksman/releases/tag/2023-04-06) which fixes the single file mode / hanging on init when no workspace folders are configured.

**Comment by moonfruit** [comment]
OK, I will close this for #127769.

**Pull request closed without merging**
