### PR TITLE
oil 0.8.1

### PR DESCRIPTION
**Pull request by WorkInProgress-Development**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Rylan12** [comment]
Looks like upstream removed the line that was being changed by the `inreplace`. Removing the `increplace` line will probably do the trick

**Comment by miccal** [comment]
Thank you @WorkInProgress-Development.

**Review by miccal — DISMISSED** [review]

**Comment by miccal** [comment]
Sorry @Rylan12, I did not spot the extra commit before I approved :(

**Comment by Rylan12** [comment]
No worries! FYI you should now be able to use `brew pr-publish --automerge` to squash the commits automatically during the merge. Still not as easy as just approving, though...

**Pull request closed without merging**
