### PR TITLE
ffmpeg: add ability to disable SecureTransport

### PR DESCRIPTION
**Pull request by saghul**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

It uses private APIs which Apple doesn't allow on AppStore releases.

### CODE REVIEW

**Comment by zmwangx** [comment]
Might be worth checking whether `/usr/lib/libssl.0.9.8.dylib` is linked when `--disable-securetransport` is specified. If it is, we might want to add `--disable-openssl` unless `--with-openssl` is specified.

**Comment by saghul** [comment]
@zmwangx TBH I don't know what ffmpeg needs those for. Also, AFAIK `--with-openssl` is not the default, so why would it link with the system OpenSSL? Also, its header have not been exported for the past 2 macOS releases...

**Comment by zmwangx** [comment]
> TBH I don't know what ffmpeg needs those for.

FFmpeg supports a bunch of live streaming protocols — RTMP and RTSP for instance — that may require TLS, among other things.

> Also, AFAIK --with-openssl is not the default, so why would it link with the system OpenSSL?

FFmpeg's configure autodetects many optionally dependencies. However, I just checked and `--enable-openssl` defaults to `no`, so no need to worry about it.

**Comment by saghul** [comment]
@zmwangx Ok.  So, is there anything else I would need to do here?

**Comment by zmwangx** [comment]
I'm 👍 on this.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. Thanks for the help here too @zmwangx. You rock!

**Pull request merged**
