### PR TITLE
vim 8.0.0575

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chdiza** [comment]
Hold off on this.  Vim 8.0.570 introduced a bug that prevents building on macOS.  This already has a patch submitted to the mailing list.  I'm sure an official fix will be made shortly.

**Comment by ilovezfs** [comment]
ok

**Comment by chdiza** [comment]
Long story short: They mucked around with the `configure` and `make` system and apparently didn't bother to test it on a Mac before pushing it.

**Comment by neutric** [comment]
For reference: https://github.com/vim/vim/issues/1647

**Comment by neutric** [comment]
@chdiza Thanks for letting us know!

**Comment by chdiza** [comment]
It's been fixed as of 8.0.576, as far as I can tell from local testing.

**Comment by neutric** [comment]
Looks like it, CI is 🍏  for 8.0.577.

**Pull request closed without merging**
