### PR TITLE
kamel 1.11.1

### PR DESCRIPTION
**Pull request by oscerd**
Signed-off-by: Andrea Cosentino <ancosen@gmail.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
This doesn't seem to be a stable release yet

**Comment by oscerd** [comment]
> This doesn't seem to be a stable release yet

It's a non-LTS release. But it's the latest version available.

**Comment by SMillerDev** [comment]
https://github.com/apache/camel-k/releases/tag/1.11.1-nightly suggests it's not the latest release but a nightly instead.

**Comment by oscerd** [comment]
And I also I forgot to update the release page too.

**Comment by oscerd** [comment]
Let me do that

**Comment by oscerd** [comment]
https://github.com/apache/camel-k/releases/tag/v1.11.1

**Review by SMillerDev — APPROVED** [review]
LGTM now that it's marked as stable upstream

**Pull request closed without merging**
