### PR TITLE
libvirt 6.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
```
configure: error: "rst2html5/rst2html is required to build libvirt"
```

**Comment by Amar1729** [comment]
i think this version needs `docutils` as a dep to build the documentation

**Comment by chenrui333** [comment]
Fixed and passed test locally.

**Comment by chenrui333** [comment]
Thanks @Amar1729 for the direction.

**Pull request closed without merging**
