### PR TITLE
lmdb: add simple lmdb.pc pkg-config file

### PR DESCRIPTION
**Pull request by oerdnj**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR adds a simple pkg-config file for lmdb library, so it can be used with modern build systems without too much hacking.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Has this been reported to upstream and a patch offered? If they decide not to ship a `.pc` file, it probably means software depending on `lldb` won't expect one and its use is very limited.

**Comment by oerdnj** [comment]
@fxcoudert , Fedora[1], Debian[2] (and all Debian based distros), and f.e. ArchLinux[3] carry custom lmdb.pc, so in fact, there's a plenty of software that depends on it.

Not sure, if anybody has reported that to Howard, but from my interactions with him, he's happy about lmdb as is.

1. http://git.net/ml/scm-fedora-commits/2017-03/msg11834.html
2. https://anonscm.debian.org/git/pkg-db/lmdb.git/tree/debian/lmdb.pc.in (I am author here).
3. https://www.archlinux.org/packages/extra/x86_64/lmdb/files/

**Comment by oerdnj** [comment]
Here I tried https://twitter.com/hyc_symas/status/858014706430349312

**Comment by fxcoudert** [comment]
Thanks @oerdnj for the pull request!

**Comment by ilovezfs** [comment]
I've reverted this in https://github.com/Homebrew/homebrew-core/pull/13626 as upstream has explicitly rejected the proposal.

**Comment by oerdnj** [comment]
That makes no sense to me. All major distributions have added lmdb.pc, and Homebrew users have to suffer just because upstream has personal (not technical) problem with pkg-config.

**Comment by ilovezfs** [comment]
@oerdnj you'll need to make your case to upstream.

**Comment by oerdnj** [comment]
@ilovezfs I would agree with such decision in case of significant changes in the upstream project, but here I respectfully disagree. Homebrew carry many patches to many other projects, and it's goal is to make the libraries and programs accessible to users. I don't think that pleasing the stubborn personality of upstream authors should not be the goals of any "distribution" project.

The patch is small and has a clear purpose, it won't break anything, and it doesn't need any updates for the lifetime of lmdb library. There's literally *nothing* to change in the future, as the library is stable and the compile/links flags won't change.

We (as a community of packagers) are not afraid to disable SSLv3 in SSL libraries, but lmdb has to stay verbatim?  Please provide a technical arguments against adding `lmdb.pc`. The "you need to convince upstream author" is not a technical argument.

**Comment by ilovezfs** [comment]
We don't want to carry patches around in perpetuity. If it's such a minimal change, you shouldn't have any trouble convincing upstream to include a pkg-config file in the future.

**Comment by MikeMcQuaid** [comment]
> There's literally nothing to change in the future, as the library is stable and the compile/links flags won't change.

Only upstream can make that guarantee.

> Please provide a technical arguments against adding lmdb.pc. The "you need to convince upstream author" is not a technical argument.

@ilovezfs does not have to provide technical arguments (or indeed any); he is following our usual policy.

**Comment by oerdnj** [comment]
> Only upstream can make that guarantee.

Yes, and upstream has stated, that he will not make any API and ABI backwards incompatible changes[*]. Please at least look into `lmdb.pc` -> that's the most simplest pkg-config file ever.

* - This was from my previous conversation with upstream about the library versioning (the library doesn't have SOVERSION). I will find a reference if needed.

**Comment by MikeMcQuaid** [comment]
> Please at least look into lmdb.pc

I did, thanks for assuming otherwise.

**Pull request merged**
