### PR TITLE
m4ri 20140914 (new formula)

### PR DESCRIPTION
**Pull request by imhotepisinvisible**

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks for your submission. I am not sure we can accept this package as-is: from the Bitbucket repository statistics, it seems to have very low activity: 1 fork, 4 watchers, 1 pull request, no release since 2014… It does not seem to meet the broad audience of Homebrew, and would probably be better if hosted in a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

Sorry, and thanks again!

**Comment by MikeMcQuaid** [comment]
Passing on this for now as @fxcoudert says, sorry!

**Comment by imhotepisinvisible** [comment]
OK, thanks for your consideration.  To note, it is a component of Sage Math ( http://doc.sagemath.org/html/en/reference/matrices/sage/matrix/matrix_mod2_dense.html ) which of course has a large audience, so it seemed to me like it could be a candidate for inclusion.  It is in the Ubuntu/Debian repos ( http://packages.ubuntu.com/source/xenial/libm4ri ), but I don't know what your policy is on matching that content.

**Comment by ilovezfs** [comment]
This is probably a better candidate for homebrew/science.

**Comment by imhotepisinvisible** [comment]
OK, thanks I will submit it to there.  BTW, their website doesn't work: https://brew.sh/homebrew-science/

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-science/

**Comment by imhotepisinvisible** [comment]
Yes I found that, but they link to the brew.sh website in their description, which doesn't work

**Comment by ilovezfs** [comment]
@imhotepisinvisible yup, I see what you mean. I let the science channel know on Slack :)

**Pull request closed without merging**
