### PR TITLE
i2p 0.9.47

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
pretty complicated license setup.
https://github.com/i2p/i2p.i2p/blob/master/LICENSE.txt#L29-L372

**Comment by chenrui333** [comment]
cc @gromgit @Rylan12

**Comment by Rylan12** [comment]
I think we need to go through those files and get all those licenses...

Should just be a matter of going through the [`licenses`](https://github.com/i2p/i2p.i2p/tree/master/licenses) directory and listing the license there. Most are easy, some might take some more work.

At first glance, it looks like there are a few that don't have `SPDX` entries (e.g. [`LICENSE-Noise.txt`](https://github.com/i2p/i2p.i2p/blob/master/licenses/LICENSE-Noise.txt)). We may need to comb through a little to figure out which licenses are actually distributed and which ones we don't need to include.

I'm too tired to do this now, but I'll try to take a look tomorrow.

**Review by SMillerDev — DISMISSED** [review]

**Comment by gromgit** [comment]
As far as I can tell, i2p itself is public domain. Below is the breakdown of the files in `licenses/`:

File | License(s)
---- | -----
ABOUT-Jetty.html | EPL-1.0, Apache-2.0
COPYING-BOB.txt | WTFPL
LICENSE-Addressbook.txt | MIT
LICENSE-Apache2.0.txt | Apache-2.0
LICENSE-BlockFile.txt | BSD-3-Clause
LICENSE-Boost.txt | BSL-1.0
LICENSE-BSD.txt | BSD-3-Clause
LICENSE-CC0-1.0-Universal.txt | CC0-1.0
LICENSE-Cryptix.txt | BSD-2-Clause
LICENSE-ECLIPSE-1.0.html | EPL-1.0
LICENSE-ElGamalDSA.txt | BSD-3-Clause
LICENSE-FatCowIcons.txt | CC-BY-3.0
LICENSE-Feather.txt | MIT 
LICENSE-fontawesome.txt | CC-BY-4.0
LICENSE-forked-subprocess.swift.txt | MIT
LICENSE-FugueIcons.txt | CC-BY-3.0
LICENSE-GPLv2.txt | GPL-2.0-only
LICENSE-GPLv3.txt | GPL-3.0-only
LICENSE-HashCash.txt | :custom
LICENSE-I2PTunnel.txt | GPL-2.0-or-later
LICENSE-InstallCert.txt | BSD-3-Clause
LICENSE-jBCrypt.txt | ISC
LICENSE-LGPLv2.1.txt | LGPL-2.1-only
LICENSE-LGPLv3.txt | LGPL-3.0-only
LICENSE-Ministreaming.txt | BSD-3-Clause, BSD-2-Clause, MIT, :public_domain
LICENSE-NDT.txt | :custom
LICENSE-Noise.txt | MIT
LICENSE-sbt-wrapper.txt | BSD-3-Clause
LICENSE-Scala.md | BSD-3-Clause
LICENSE-SHA256.txt | MIT
LICENSE-SilkIcons.txt | CC-BY-2.5
LICENSE-SNTP.txt | BSD-3-Clause
LICENSE-Undraw.txt | :custom
LICENSE-UPnP.txt | BSD-3-Clause
LICENSE-Wrapper.txt | :custom

Looking solely at `LICENSE.txt` and the above files, the following apply to one component or another (ignoring public-domain and custom licenses):

Apache-2.0
BSD-2-Clause
BSD-3-Clause
BSL-1.0
CC0-1.0
CC-BY-2.5
CC-BY-3.0
CC-BY-4.0
EPL-1.0
GPL-2.0-only
GPL-2.0-or-later
GPL-3.0-only
ISC
LGPL-2.1-only
LGPL-3.0-only
MIT
WTFPL

And now it's :zzz: for me.

**Comment by chenrui333** [comment]
Gonna merge this PR and open a separate license PR to discuss this 💤 stuff.

**Comment by chenrui333** [comment]
we need a :license: emoji! :)

**Pull request merged**
