### PR TITLE
semgrep v1.17.1

### PR DESCRIPTION
**Pull request by brendongo**
Bump semgrep to version v1.17.1

### CODE REVIEW

**Comment by p-linnane** [comment]
@brendongo Please do not open PR's from organization forks. Our new merge flow pushes commits to the branch as part of our merge process, and that doesn't work for org forks. We have had to open new PR's for the last 2 bumps of this formula.

See: https://github.com/Homebrew/homebrew-core/pull/127238 for https://github.com/Homebrew/homebrew-core/pull/127162 and https://github.com/Homebrew/homebrew-core/pull/127640 for https://github.com/Homebrew/homebrew-core/pull/127564.

**Comment by spencerdrak** [comment]
Hi there @p-linnane - thanks for the input, we'll rectify this. One quick question - would you like us to re-open this PR from a non-organizational account?

**Comment by p-linnane** [comment]
Yes please. The fork just has to be a non-org fork that our maintainers and bot can push to.

**Comment by spencerdrak** [comment]
Thanks!

**Pull request closed without merging**
