### PR TITLE
openvino: 2023.1.0

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Hi @SMillerDev
I observe CI issue not connected with my changes:
```
CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CMakeTestCCompiler.cmake:[67](https://github.com/Homebrew/homebrew-core/actions/runs/5534264630/jobs/10099099585?pr=134935#step:3:68) (message):
    The C compiler
  
      "/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang"
  
    is not able to compile a simple test program.
  
    It fails with the following output:
  
      Change Dir: /tmp/openvino-20230[71](https://github.com/Homebrew/homebrew-core/actions/runs/5534264630/jobs/10099099585?pr=134935#step:3:72)2-[72](https://github.com/Homebrew/homebrew-core/actions/runs/5534264630/jobs/10099099585?pr=134935#step:3:73)22-b53jdu/openvino-df2ed95dab227d[78](https://github.com/Homebrew/homebrew-core/actions/runs/5534264630/jobs/10099099585?pr=134935#step:3:79)95cef4720f007c371cfb6a33/build/CMakeFiles/CMakeScratch/TryCompile-vcta5V
      
      Run Build Command(s):/usr/local/Cellar/cmake/3.26.4/bin/cmake -E env VERBOSE=1 /usr/local/Homebrew/Library/Homebrew/shims/mac/super/gmake -f Makefile cmTC_4a412/fast && 
      Failed to execute gmake -f Makefile cmTC_4a412/fast
      
      Xcode and/or the CLT appear to be misconfigured. Try one or both of the following:
        xcodebuild -license
        sudo xcode-select --switch /path/to/Xcode.app
      
      
      
  
    
  
    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:25 (project)
  
  
  -- Configuring incomplete, errors occurred!
```
Is it something you observe on other PRs?

**Comment by ilya-lavrenov** [comment]
Hi @carlocab 
Could you please help to answer the question above?
I.e. what to do if library changes its SOVERSION, while tested formula compiled with the previous one?

**Comment by chenrui333** [comment]
@ilya-lavrenov you need to do the rebase rather than the `merge master` branch

**Comment by ilya-lavrenov** [comment]
@chenrui333 
Thank you for your comments. 
Could you please set labels for long run? 
The PR is ready for review.

**Comment by ilya-lavrenov** [comment]
@chenrui333 @SMillerDev 
Thank you for your comments. 
Could you please set labels for long run? 
The PR is ready for review.

**Comment by ilya-lavrenov** [comment]
Thanks @alebcay 
I suppose we need all three labels like here:
Screenshot 2023-09-16 at 11 55 50 PM

**Comment by alebcay** [comment]
FYI - only a limited number of PRs may possess `CI-long-timeout` at any given time (think of it as a ticket to run with longer timeout) - we allocate a split of CI runners, some for "short" jobs and some for "long" jobs. `long build` only indicates that the PR _needs_ `CI-long-timeout` to run successfully. So we only add `CI-long-timeout` to a PR when it's about to be used.

**Comment by ilya-lavrenov** [comment]
Hi @chenrui333 @SMillerDev @cho-m 
Could you please review and merge?

**Comment by ilya-lavrenov** [comment]
Hi @chenrui333 @SMillerDev @cho-m @alebcay
Could you please review and merge?

**Pull request closed without merging**
