### PR TITLE
docker-credential-helper-ecr 0.2.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by samuelkarp** [comment]
Hey, apologies for breaking the build here; I didn't realize that Homebrew was pulling the tar.gz that GitHub generates for the repository.  In the short term, I think a straightforward way to fix this is to add `echo b9fd5a8 > GITCOMMIT_SHA` before invoking `make`.  Longer-term, I can see about publishing tar.gz files generated with `make release-tarball` that will include this file properly.

**Comment by igas** [comment]
Hi @samuelkarp ,

Thanks for looking into this. Sometimes brew using git as a source with tags/revisions. I'm not what is preferred way and when to use one over another.

@fxcoudert could you please assist here? Looks like it's similar to https://github.com/Homebrew/homebrew-core/pull/33879

Thanks

**Comment by igas** [comment]
`brew cleanup --prune=7` failed but I don't think it's related

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Review by samuelkarp — APPROVED** [review]
LGTM!

**Comment by Moisan** [comment]
Thank you @igas and @samuelkarp !

**Pull request closed without merging**
