### PR TITLE
gdb: add head

### PR DESCRIPTION
**Pull request by fxcoudert**
Rebasing #35006 on current master

### CODE REVIEW

**Comment by roolebo** [comment]
@timotheecour the URI of gdb git repo is not a fork rather it’s the upstream repo. Therefore the build issue should be reported at https://sourceware.org/bugzilla/ if nobody has done this yet

**Comment by fxcoudert** [comment]
@timotheecour That's the nature of a "head" build, it's not checked by us for quality, it builds from the sources in their latest state, and they can be broken at times. This bug was already reported, actually: https://sourceware.org/bugzilla/show_bug.cgi?id=24060

Your PR proposed a build from an unofficial repo (https://github.com/bminor/binutils-gdb) and a fixed, arbitrary revision, shipped as a “stable” version. We have rather added the official “head” version.

**Comment by fxcoudert** [comment]
@timotheecour regarding:

> all I care is that I can install a usable version of gdb

Your problem really is with the GDB project. You should report bugs to them, and if no GDB maintainer is interested in fixing the build for macOS, propose patches — or find someone to create patches for you.

**Comment by timotheecour** [comment]
granted, I should've used git://sourceware.org/git/binutils-gdb.git instead of the Unofficial mirror https://github.com/bminor/binutils-gdb ; that being said, wouldn't it make more sense to use a fixed revision (as I had done) ? that would've avoid the current situation where:
* stable is ununsable and has always been (on latest OSX (Mojave) at least)
* --HEAD is unusable (and is a moving target; if they fix it tomorrow it may break again the day after)

the `fixed, arbitrary revision` indeed doesn't correspond to a git tag, but is not that arbitrary, it's a revision that actually worked on latest OSX; which seems like an intuitive definition of what `stable` is

I can think of 2 options:
* use the official sources `git://sourceware.org/git/binutils-gdb.git` but making `stable` point to a fixed revision instead of a fixed git tag that doesn't work
* or, re-open this proposal https://github.com/Homebrew/brew/issues/1738 I had made which allows: `brew install foo --commit=eeeb0f2e8d0a77`, from which we could install a working gdb pointing to that fixed revision

> Your problem really is with the GDB project

I know; I've reported it upstream and many did too for the past 1+ year, I'm just trying to find a practical approach to actually solving this.

As last resort option, I can use my own tap of gdb, but that won't benefit anyone trying to use gdb

**Comment by fxcoudert** [comment]
@timotheecour What will benefit everyone trying to use gdb is to actually fix the bug(s) in the gdb codebase.

We ship stable versions as released by upstream. We're not developers of that software — and we don't want to be: Homebrew core has 4680 formulas and a dozen maintainers.

**Pull request merged**
