### PR TITLE
gdb: Add support for --HEAD version

### PR DESCRIPTION
**Pull request by roolebo**
master branch of binutils-gdb contains a number of fixes essential for
local debugging on macOS. An ability to install the latest gdb should
ease the pain of #34750 and alike until 8.3 is out.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by timotheecour** [comment]
thanks @roolebo !!

**Comment by timotheecour** [comment]
btw: `sudo /Users/timothee/homebrew/Cellar/gdb/HEAD-60f9fdc_1/bin/gdb` works fine, but one question:

is the following clash with `binutils` expected?


```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/cb7a4c1b8e52220ed8d5d382268e5a36fad99815/Formula/gdb.rb --HEAD
######################################################################## 100.0%
==> Cloning git://sourceware.org/git/binutils-gdb.git
Cloning into '/Users/timothee/Library/Caches/Homebrew/gdb--git'...
Checking out files: 100% (32599/32599), done.
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> ./configure --prefix=/Users/timothee/homebrew/Cellar/gdb/HEAD-60f9fdc_1 --with-python=/usr
==> make
==> make install
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /Users/timothee/homebrew
Could not symlink bin/addr2line
Target /Users/timothee/homebrew/bin/addr2line
is a symlink belonging to binutils. You can unlink it:
  brew unlink binutils

To force the link and overwrite all conflicting files:
  brew link --overwrite gdb

To list all files that would be deleted:
  brew link --overwrite --dry-run gdb

Possible conflicting files are:
/Users/timothee/homebrew/bin/addr2line -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/addr2line
/Users/timothee/homebrew/bin/ar -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/ar
/Users/timothee/homebrew/bin/c++filt -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/c++filt
/Users/timothee/homebrew/bin/elfedit -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/elfedit
/Users/timothee/homebrew/bin/nm -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/nm
/Users/timothee/homebrew/bin/objcopy -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/objcopy
/Users/timothee/homebrew/bin/objdump -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/objdump
/Users/timothee/homebrew/bin/ranlib -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/ranlib
/Users/timothee/homebrew/bin/readelf -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/readelf
/Users/timothee/homebrew/bin/size -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/size
/Users/timothee/homebrew/bin/strings -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/strings
/Users/timothee/homebrew/bin/strip -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/bin/strip
/Users/timothee/homebrew/share/info/binutils.info -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/info/binutils.info
/Users/timothee/homebrew/share/man/man1/addr2line.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/addr2line.1
/Users/timothee/homebrew/share/man/man1/ar.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/ar.1
/Users/timothee/homebrew/share/man/man1/c++filt.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/c++filt.1
/Users/timothee/homebrew/share/man/man1/dlltool.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/dlltool.1
/Users/timothee/homebrew/share/man/man1/elfedit.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/elfedit.1
/Users/timothee/homebrew/share/man/man1/nm.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/nm.1
/Users/timothee/homebrew/share/man/man1/objcopy.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/objcopy.1
/Users/timothee/homebrew/share/man/man1/objdump.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/objdump.1
/Users/timothee/homebrew/share/man/man1/ranlib.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/ranlib.1
/Users/timothee/homebrew/share/man/man1/readelf.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/readelf.1
/Users/timothee/homebrew/share/man/man1/size.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/size.1
/Users/timothee/homebrew/share/man/man1/strings.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/strings.1
/Users/timothee/homebrew/share/man/man1/strip.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/strip.1
/Users/timothee/homebrew/share/man/man1/windmc.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/windmc.1
/Users/timothee/homebrew/share/man/man1/windres.1 -> /Users/timothee/homebrew/Cellar/binutils/2.31.1_2/share/man/man1/windres.1
==> Caveats
gdb requires special privileges to access Mach ports.
You will need to codesign the binary. For instructions, see:

  https://sourceware.org/gdb/wiki/BuildingOnDarwin

On 10.12 (Sierra) or later with SIP, you need to run this:

  echo "set startup-with-shell off" >> ~/.gdbinit
==> Summary
🍺  /Users/timothee/homebrew/Cellar/gdb/HEAD-60f9fdc_1: 90 files, 19MB, built in 7 minutes 41 seconds
```

**Comment by roolebo** [comment]
binutils became keg-only(#33419) a while ago, so it's okay to drop all dangling links to it with:
```
brew unlink binutils
```
Regardless of that you've caught a regression of #10407.

**Comment by roolebo** [comment]
An updated fix for #10407 should probably use ```--disable-DIR``` flag to ```./configure``` script to disable particular part of binutils-gdb as [outlined by gdb maintainer](https://stackoverflow.com/questions/34037219/why-were-gnu-binutils-and-gdb-merged-as-one-package). I'll add a commit for that shortly.

**Comment by roolebo** [comment]
@timotheecour Updatad formulae shouldn't have the issue:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/311be07ab50b75b55cf4462ea9b8d7acf955f968/Formula/gdb.rb --HEAD
```

**Comment by timotheecour** [comment]
well it now doesnt error but says:
```
Target /Users/timothee/homebrew/bin/addr2line
is a symlink belonging to binutils. You can unlink it:
  brew unlink binutils
```

is it safe to `brew link --overwrite --dry-run gdb` ? (which overwrites a long list similar to https://github.com/Homebrew/homebrew-core/pull/35006#issuecomment-446436977) ?

**Comment by roolebo** [comment]
I don't know why it happens because I don't see the conflicting files anymore:
```
brew list gdb
/usr/local/Cellar/gdb/HEAD-60f9fdc_2/bin/gdb
/usr/local/Cellar/gdb/HEAD-60f9fdc_2/bin/gdb-add-index
/usr/local/Cellar/gdb/HEAD-60f9fdc_2/include/gdb/jit-reader.h
/usr/local/Cellar/gdb/HEAD-60f9fdc_2/share/gdb/ (40 files)
/usr/local/Cellar/gdb/HEAD-60f9fdc_2/share/info/ (3 files)
/usr/local/Cellar/gdb/HEAD-60f9fdc_2/share/man/ (4 files)
```

With regards to you question it's safe to ```brew unlink binutils``` because it's supposed to be keg-only for now.

**Comment by timotheecour** [comment]
> I don't know why it happens because I don't see the conflicting files anymore:

correct, it only happened after I called `brew link gdb` 
(as recommended by:
You can use `brew link gdb` to link this version
)

anyway, all is good since binutils was changed to keg-only . Thanks again

**Review by fxcoudert — CHANGES_REQUESTED** [review]

**Comment by fxcoudert** [comment]
@roolebo I have opened a clean PR on top of master at https://github.com/Homebrew/homebrew-core/pull/35754, so we can merge it. Thanks for your contribution!

**Comment by fxcoudert** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/fa7e2f143d2656e49700dcb4a63dd33fd52ceba3

**Comment by roolebo** [comment]
@fxcoudert thanks for rebasing! I’m sorry I wasn’t able to do that due to the holidays.

**Pull request closed without merging**
