### PR TITLE
firebase-cli 9.16.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
firebase-cli:
  * Binaries built for a non-native architecture were installed into firebase-cli's prefix.
    The offending files are:
      /opt/homebrew/Cellar/firebase-cli/9.16.2/libexec/lib/node_modules/firebase-tools/node_modules/term-size/vendor/macos/term-size	(x86_64)
    Unexpected universal binaries were found.
    The offending files are:
      /opt/homebrew/Cellar/firebase-cli/9.16.2/libexec/lib/node_modules/firebase-tools/node_modules/fsevents/fsevents.node
```

**Review by andressalas93 — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]
Squashed your commits since this is `automerge skip`.

**Review by carlocab — APPROVED** [review]
You forgot to pass `--no-autosquash`.

**Comment by chenrui333** [comment]
> You forgot to pass `--no-autosquash`.

I see, noted 👍

**Pull request closed without merging**
