### PR TITLE
tailscale 1.18.1

### PR DESCRIPTION
**Pull request by frankli0324**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for the PR. I see that there's a 1.18.1 tag, but the latest release on GitHub still shows as 1.18.0. Is that just an oversight upstream?

**Comment by frankli0324** [comment]
no, 1.18.1 was released 3 days ago. I noticed the release when I upgraded tailscale in ubuntu yesterday, and the latest version they pushed to their repository shows "1.18.1".

**Comment by carlocab** [comment]
Yes, there is a `1.18.1` tag, but `1.18.0` is still registered as the latest release. See: https://github.com/tailscale/tailscale/releases/latest

It currently points to `1.18.0`.

**Comment by frankli0324** [comment]
I believe the tailscale maintainers forgot to issue a release then.

**Comment by carlocab** [comment]
Yes, that's what I meant about this being an oversight. Do you mind asking upstream to be sure? That way we don't have to guess.

**Comment by bradfitz** [comment]
The Tailscale 1.18.1 was unique in that it only contained Linux-specific fixes, so we didn't go through our usual release dance. We didn't want to e.g. build for all platforms and make Windows/macOS users go through the upgrade process.

There's no real reason for Homebrew to update to 1.18.1, but you can. It was a "real" release, kinda.

**Comment by carlocab** [comment]
We do want the Linux-specific fixes though. Thanks for clarifying!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
