### PR TITLE
simutrans: drop GCC dependency

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Can we not create so many of these PRs at a time? This is creating long queues in CI.

**Comment by danielnachun** [comment]
Sorry, I didn't see that message.  I didn't have many more to push but I'll wait until it's less busy.

**Comment by danielnachun** [comment]
This is the failure here and I'm not yet sure what it means:
```
In file included from dataobj/../simversion.h:12,
                    from dataobj/environment.cc:10:
  dataobj/../revision.h:1:1: error: stray ‘\’ in program
      1 | \#define REVISION
        | ^
  dataobj/../revision.h:1:2: error: stray ‘#’ in program
      1 | \#define REVISION
        |  ^
  dataobj/../revision.h:1:3: error: ‘define’ does not name a type
      1 | \#define REVISION
        |   ^~~~~~
  In file included from dataobj/../sys/simsys.h:14,
                   from dataobj/environment.cc:13:
  /home/linuxbrew/.linuxbrew/include/zlib.h:1422:9: error: ‘z_size_t’ does not name a type; did you mean ‘ssize_t’?
   1422 | ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
        |         ^~~~~~~~
        |         ssize_t
  /home/linuxbrew/.linuxbrew/include/zlib.h:1454:9: error: ‘z_size_t’ does not name a type; did you mean ‘ssize_t’?
   1454 | ZEXTERN z_size_t ZEXPORT gzfwrite OF((voidpc buf, z_size_t size,
        |         ^~~~~~~~
        |         ssize_t
  In file included from /home/linuxbrew/.linuxbrew/include/zlib.h:34,
                   from dataobj/../sys/simsys.h:14,
                   from dataobj/environment.cc:13:
  /home/linuxbrew/.linuxbrew/include/zlib.h:1709:33: error: ‘z_size_t’ has not been declared
   1709 | ZEXTERN uLong ZEXPORT adler32_z OF((uLong adler, const Bytef *buf,
        |                                 ^~
  /home/linuxbrew/.linuxbrew/include/zlib.h:1745:31: error: ‘z_size_t’ has not been declared
   1745 | ZEXTERN uLong ZEXPORT crc32_z OF((uLong crc, const Bytef *buf,
        |                               ^~

**Comment by danielnachun** [comment]
I don't have a definitive answer yet, but it appears the issue we're seeing here is to due to a bug in the autotools build which is old and crusty.  Upstream now supports building with `cmake` and with this it successfully compiles, though I am having trouble getting it to install to the right location.  Nonetheless I think this is the right path to take here, it will just require more troubleshooting.

**Comment by jonchang** [comment]
Does it still need `autoconf` and `automake` if we're switching to cmake-based builds?

**Review by jonchang — APPROVED** [review]

**Pull request closed without merging**
