### PR TITLE
passpie 1.4.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Seems fine but might be worth checking if the Python deps should be updated at all.

**Comment by ilovezfs** [comment]
I checked all of them one by one ;)

**Comment by DomT4** [comment]
You're aware of `homebrew-pypi-poet` right? 😄

**Comment by ilovezfs** [comment]
@DomT4 What do you think I used when I said "one by one"? ;)

**Comment by DomT4** [comment]
It sounded like you'd manually given 'em some love 😄.

**Comment by ilovezfs** [comment]
Nope, just confirmed that the only thing `poet` had to contribute to the discussion was uglier URLs.

**Comment by DomT4** [comment]
We'll have to adopt them eventually, sadly. Tim likes them I believe, I'm less of a fan due to the silly length.

**Comment by ilovezfs** [comment]
Unfortunately the prettier URLs don't always exist, which might be the reason, if I had to guess.

**Comment by marcwebbie** [comment]
Thanks for that @ilovezfs and @DomT4 , I was just about to update the formula here. 😃

**Pull request closed without merging**
