### PR TITLE
julia 1.8.4

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Linux:
```
ERROR: Unable to load dependent library /tmp/julia-20221224-16399-1iftaq2/julia-1.8.4/usr/bin/../lib/libstdc++.so.6
  Message:/tmp/julia-20221224-16399-1iftaq2/julia-1.8.4/usr/bin/../lib/libstdc++.so.6: cannot open shared object file: No such file or directory
  make[2]: *** [sysimage.mk:61: /tmp/julia-20221224-16399-1iftaq2/julia-1.8.4/usr/lib/julia/corecompiler.ji] Error 1
  make[2]: Leaving directory '/tmp/julia-20221224-16399-1iftaq2/julia-1.8.4'
  make[1]: *** [Makefile:82: julia-sysimg-ji] Error 2
  make[1]: Leaving directory '/tmp/julia-20221224-16399-1iftaq2/julia-1.8.4'
```

Documentation now states:
```
On Linux, now autodetects the system libstdc++ version, and automatically loads the system library if it is newer. The old behavior of loading the bundled libstdc++ regardless of the system version obtained by setting the environment variable JULIA_PROBE_LIBSTDCXX=0.
```

**Comment by chenrui333** [comment]
on linux build

```
  ERROR: Unable to load dependent library /tmp/julia-20221228-16392-i8u8xw/julia-1.8.4/usr/bin/../lib/libstdc++.so.6
  Message:/tmp/julia-20221228-16392-i8u8xw/julia-1.8.4/usr/bin/../lib/libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by fxcoudert** [comment]
I have reported the macOS Intel issue upstream: https://github.com/JuliaLang/julia/issues/48056

We can work around it with this patch (untested, but simple): https://github.com/Homebrew/formula-patches/commit/c0a411ea7f5848d7b46fd360d0bb8783f75d2fb3

**Comment by cho-m** [comment]
Added `do not merge` to handle #118915 first.

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/120170

**Pull request closed without merging**
