### PR TITLE
bettercap 2.26

### PR DESCRIPTION
**Pull request by djerfy**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by djerfy** [comment]
Build failed:
```
==> dep ensure -vendor-only
could not find project Gopkg.toml, use dep init to initiate a manifest
```

This file (and vendor directory) has been removed from the repository: https://github.com/bettercap/bettercap/commit/b8ff8a00e873ca308502a43356a2a6d20c0d6cc9 😢

**Comment by dawidd6** [comment]
Simple `make build PREFIX=#{prefix}` should be enough now.

**Comment by djerfy** [comment]
> 
> 
> Simple
> 
> system "make", "build"
> system "make", "install", "PREFIX=#{prefix}"
> 
> should be enough now.
> 
> Also, `python` might be needed.

Thank you! I remove `dep ensure` and add `python` dependency.
I don't add `make install` because I use `bin.install bettercap`, my tests are good.

**Comment by fxcoudert** [comment]
What does this need python for? At build time, run time? Can macOS Python 2 be used, especially if it's build-only?

**Comment by djerfy** [comment]
> What does this need python for? At build time, run time? Can macOS Python 2 be used, especially if it's build-only?

Exactly, no python required (https://www.bettercap.org/installation/), so I remove it, sorry.

**Comment by dawidd6** [comment]
Is suggested `python` cause I saw it in upstream's Makefile: https://github.com/bettercap/bettercap/blob/5a6a7143f206da2b4654c02f11b6654d32001721/Makefile#L18

**Pull request closed without merging**
