### PR TITLE
ninja: make bottle relocatable

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Passing the full path of Homebrew Python3 hardcodes this in the binary,
but there's no need to do that.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
```
➜ jq '.[].bottle.cellar' < *.bottle.json
"any_skip_relocation"
"any_skip_relocation"
"any_skip_relocation"
"any_skip_relocation"
```
and
```
Warning: String '/usr/local/opt' still exists in these files:
/usr/local/Cellar/ninja/1.10.2/bin/ninja
 --> match '/usr/local/opt/python@3.9/bin/python3' at offset 0x2e76e
```

**Comment by carlocab** [comment]
> ```
> 
> Warning: String '/usr/local/opt' still exists in these files:
> 
> /usr/local/Cellar/ninja/1.10.2/bin/ninja
> 
>  --> match '/usr/local/opt/python@3.9/bin/python3' at offset 0x2e76e
> 
> ```

Which node is this one from? I only see `any_skip_relocation`.

**Comment by nandahkrishna** [comment]
Ah I downloaded the bottles locally and checked with `brew bottle` – specifically, on the Intel Big Sur one.

**Comment by carlocab** [comment]
As in compared to the existing bottles? Or are these the new bottles? I'm still confused about what this means, exactly:

> ```
> Warning: String '/usr/local/opt' still exists in these files:
> /usr/local/Cellar/ninja/1.10.2/bin/ninja
>  --> match '/usr/local/opt/python@3.9/bin/python3' at offset 0x2e76e
> ```

Does that mean the bottles actually aren't relocatable? Because the output of `brew bottle` says they are...

**Review by nandahkrishna — APPROVED** [review]
They are relocatable, and the output is for the new bottles.

I included that just to show why we had `any_skip_relocation` as opposed to `any` (correct me if I'm wrong here, still learning 😅). Evidently, I forgot to approve the PR after commenting.

**Comment by carlocab** [comment]
Ah, I see! I was confused by your comment; I thought you were saying it's not actually relocatable 😅

**Comment by carlocab** [comment]
Just for future reference: 

This might mean that `ninja` now needs to be able to find a `python3` in `PATH` in order to function. This could be a problem for formulae that have a `depends_on "ninja" => :build` but no `depends_on "python@3.9"`, because `brew` won't put `python3` in `PATH` in that case.

The solution to that would be to wrap `ninja` in an env script that adds Python3 to `ninja`'s `PATH` -- this will allow `ninja` to easily find `python3` without actually hardcoding the location in the binary.

**Pull request closed without merging**
