### PR TITLE
pwntools 3.12.1

### PR DESCRIPTION
**Pull request by zbeekman**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zbeekman** [comment]
See https://github.com/Homebrew/homebrew-core/pull/33419 for some additional context.

**Comment by Moisan** [comment]
Fails due to `pwntools.com` being down at the moment.

**Comment by zbeekman** [comment]
@Moisan Yes, that's correct. pwntools.com has been down for quite some time, it would appear. Upstream doesn't seem to have gotten around to fixing this, see https://github.com/Gallopsled/pwntools/issues/1215 for some additional details.

**Comment by Moisan** [comment]
Then I suggest that we change the homepage to `https://github.com/Gallopsled/pwntools`.

**Pull request closed without merging**
