### PR TITLE
Update chisel to latest version

### PR DESCRIPTION
**Pull request by revolter**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
That's not the latest version. A version needs to be a tagged release.

**Comment by revolter** [comment]
So there really is no way to use the latest code. Because they didn't release a new version in a long time, and we can't work around this fact. There really should be a way for us to install from any commit in cases like this.

**Comment by SMillerDev** [comment]
That would just mean any install is a gamble if it works. The best solution is asking for a release upstream. The second best solution is to make `--HEAD` builds work. https://github.com/Homebrew/homebrew-core/blob/master/Formula/ceres-solver.rb#L35 has a hint on how you can do that.

**Comment by revolter** [comment]
Is there any way to directly test the change from this branch?

**Comment by revolter** [comment]
Yeah, it doesn't work. And they don't seem to want to release a new version, for some reason, even if they do merge PRs.

**Pull request closed without merging**
