### PR TITLE
vtk@8.2: Fix patch sha256, the code has slightly changed

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
We need an audit to use `.diff` extensions instead of `.patch` extensions for gitlab-hosted repositories. The former do the equivalent of `git diff --full-index` but the latter do not. Ideally gitlab would also add this feature themselves (if anyone can figure out the gitlab issue tracker that would be awesome)

**Comment by jonchang** [comment]
Oh, apparently we already have an audit for this but it goes the wrong way. Pull request incoming...

**Comment by jonchang** [comment]
Wow, and it looks like I was the one to merge this style fix in the first place. https://github.com/Homebrew/brew/commit/ea10192f8b420a5b3cb2e7b7f24d4714e8a8d548

**Comment by jonchang** [comment]
The suspect, witness, and prosecutor for this offense were all the same person.

**Comment by carlocab** [comment]
Already in https://github.com/Homebrew/homebrew-core/pull/70826

**Comment by carlocab** [comment]
Merging this will cause problems for the qt PR, so let's try to merge that one first.

**Comment by iMichka** [comment]
As this has been merged in #70826, I'll close this then. Thanks!

**Pull request closed without merging**
