### PR TITLE
k3d 5.4.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iwilltry42** [comment]
Release v5.4.9 fixed: https://github.com/k3d-io/k3d/releases/tag/v5.4.9

**Comment by ZhongRuoyu** [comment]
Thanks @iwilltry42!

**Review by ZhongRuoyu — DISMISSED** [review]

**Comment by ZhongRuoyu** [comment]
@iwilltry42 was `v5.4.9` retagged?

**Comment by iwilltry42** [comment]
Yep, previous Tag was broken

**Comment by ZhongRuoyu** [comment]
Thanks for confirming that. I will update this PR accordingly.

By the way, I would recommend against retagging once the tag is published. As mentioned in [Git's documentation](https://git-scm.com/docs/git-tag#_on_re_tagging), re-tagging is an "insane thing" that's strongly discouraged.

**Comment by iwilltry42** [comment]
I totally agree with you there. Unfortunately CI was failing, while the code was OK.
I was too impatient there 🙄

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
