### PR TITLE
llvm 3.9.0

### PR DESCRIPTION
**Pull request by Godin**
- [x] `creduce`
- [x] `ponyc`
- [x] `castxml`
- [x] `ldc devel`
- [ ] `ldc`
- [x] `crystal-lang`

### CODE REVIEW

**Comment by DomT4** [comment]
Will also need to bump the revisions on `castxml`, `creduce`, `emacs-clang-complete-async`, `ponyc` and `rtags`. Some of those may well need new releases or compatibility patches backported.

**Comment by Godin** [comment]
@DomT4 increased revision in all formulas which have `depends_on "llvm"`, i.e. `crystal-lang` and `ldc` in addition to your list. And indeed - according to Jenkins almost all of those projects should be updated/patched to compile with clang 3.9 :disappointed:

Shall we do the same for formulas with `depends_on "llvm" => :optional`, i.e. `doxygen`, `cctols` and `rust` ?

**Comment by DomT4** [comment]
> And indeed - according to Jenkins almost all of those projects should be updated/patched to compile with clang 3.9

I feared as much, to be honest. LLVM updates are usually pretty hard to get through.

Let's see what the response is from upstreams as to whether this is something we can get done quickly through patch backports or new releases, but otherwise we might have to consider adding the 3.9.0 release as a new formula & migrating things over as possible.

> Shall we do the same for formulas with depends_on "llvm" => :optional

We don't bother; option usage is generally fairly low & forcing everyone to do a rebuild to cover the small minority that use those options isn't worthwhile.

**Comment by Godin** [comment]
Strange, `ponyc` fails, while its current version 0.3.0 supposed to have support for LLVM 3.9 already - https://github.com/ponylang/ponyc/commit/f0fa3fc0c7c128c05b2493e5231eed94289d8f01

**Comment by Godin** [comment]
According to release notes `ldc-1.1.0-beta2` (`devel` in homebrew) supposed to work too, but also fails.

**Comment by Godin** [comment]
Seems that `crystal-lang` put update to LLVM 3.9 on hold - https://github.com/crystal-lang/crystal/issues/3237

**Comment by Godin** [comment]
Patch from `castxml` upstream - https://github.com/CastXML/CastXML/commit/e1ee6852c79eddafa2ce1f134c097decd27aaa69 , but unfortunately due to change in `README.rst` it can't be applied cleanly on current version `0.1+git20160412` in homebrew.

**Comment by Godin** [comment]
:yum: `creduce` successfully patched

**Comment by Marqin** [comment]
* ponyc has updated to 0.3.2 and seems to have few more commits about fixing llvm39 since 0.3.0

**Comment by Godin** [comment]
@Marqin thank you for notification. `master` branch has been merged into this to get update of `ponyc`, let's see what @BrewTestBot will tell us

**Comment by Godin** [comment]
Looks like @BrewTestBot can't eat PRs containing merges from master with resolution of conflicts, so instead rebased this branch.

**Comment by Godin** [comment]
😋  `ponyc` passed

Thanks again for notification @Marqin :thumbsup:

**Comment by Marqin** [comment]
btw. could it be possible to add this as [standalone `llvm39` package](https://github.com/Homebrew/homebrew-versions/issues/1388) (like `llvm38`, `llvm37`, etc.)

**Comment by Godin** [comment]
@Marqin I don't think the same question in multiple places gives any speedup.
Some work has been already started - https://github.com/Homebrew/homebrew-versions/pull/1384

And as stated in https://github.com/Homebrew/homebrew-versions/blob/19e6a94df3130a8038789aa5c1dcd5eccffc5850/.github/ISSUE_TEMPLATE.md
> Please note by far the quickest way to get a new formula into Homebrew is to file a Pull Request.

So to really speedup the process - IMO either provide a PR yourself for the opened issue, either help finalize an existing PR  😉

**Comment by Godin** [comment]
:yum: `castxml` passed after update and patch

**Comment by Godin** [comment]
`ldc devel` actually includes so called `ldc-lts`, which is `ldc-0.17.1`, and this one is failing, not `ldc-1.1.0-beta2`. I have no idea why `ldc-lts` was preserved here together with `stable ldc-1.0.0`. but this definitely doesn't look like an upstream issue. And so I'm wondering if it can be simply removed? This way we'll be able either do a patch just for `1.0.0` (hopefully by picking it from `1.1.0-beta2`), either wait `1.1.0` GA. Otherwise `0.17.1` should also be patched and guessing based on gap between version numbers it might be not that straightforward, i.e. probably without cherry-picking from upstream.

@DomT4 maybe you have an advice?

**Comment by iMichka** [comment]
@Godin I updated castxml separately, because the old URL's were broken and there were no Sierra bottles. You can rebase your PR. Of course the patch for llvm 3.9 needs to stay the time being.

P.S. thanks for pushing llvm 3.9 forward 👍

**Comment by JohanEngelen** [comment]
@Godin LDC 0.17.1 has already been patched for LLVM3.9, LDC's 'ltsmaster' branch, but has not been released yet unfortunately.
Hope we can release 0.17.2 soon, so that there is a good LDC bootstrap procedure with LLVM3.9. ("bootstrap" = building LDC without a pre-installed D compiler. 0.17.* can be built with just a C++ compiler, and then 0.17.* can build the latest version).

**Comment by Godin** [comment]
@iMichka thanks for notification - rebased

**Comment by JohanEngelen** [comment]
LDC 0.17.2 (can be built with LLVM3.9) has been released: https://github.com/ldc-developers/ldc/releases/tag/v0.17.2

**Comment by John-Colvin** [comment]
The ldc formula should now work with llvm 3.9.0

**Comment by Godin** [comment]
@JohanEngelen @John-Colvin thx for notification, rebased and `ldc-devel` passed. So just need to wait when it will go out of beta.

**Comment by ilovezfs** [comment]
@Godin looks like ponyc needs a little conflict resolution

**Comment by ilovezfs** [comment]
@Godin there's a crystal-lang PR adding 3.9 support now https://github.com/crystal-lang/crystal/pull/3439 if you'd like to test it out!

**Comment by Godin** [comment]
@ilovezfs yup, `ponyc` got several updates in past days and gets conflict resolution with each rebase here. And thanks for notification about `crystal-lang`, I'll try to check it.

**Comment by Godin** [comment]
😋  `crystal-lang` passed build after patch

However I did not checked whether it actually works or not.
I guess anyway would be better to wait when work in https://github.com/crystal-lang/crystal/pull/3439 will be finished and it will be closed.

**Comment by JohanEngelen** [comment]
(Note that LDC has a chicken-egg problem with this:  we use homebrew in our CI tests to install LLVM.  Because LLVM3.9 is not available yet, we also can't test whether LDC works with LLVM3.9 on Mac...)

**Comment by ilovezfs** [comment]
I don't see any reason to wait on crystal-lang/crystal#3439.

**Comment by ilovezfs** [comment]
@Godin Thanks for your excellent work on this PR and your contribution to Homebrew! :fireworks:

**Comment by ilovezfs** [comment]
@JohanEngelen chicken and egg problem solved :)

**Comment by JohanEngelen** [comment]
@ilovezfs It would help me a lot if `brew install llvm39` would work (instead of `brew install llvm` which I read installs LLVM3.9 at the moment).

**Comment by ilovezfs** [comment]
@JohanEngelen You can add a symlink in `Aliases`

```
ln -s ../Formula/llvm.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/llvm39
```

**Comment by JohanEngelen** [comment]
The reason I want to type `llvm39` is that `llvm` or your proposed solution will require babysitting. If brew updates to llvm4.0, I don't want the tester to automatically update to it too.

**Comment by ilovezfs** [comment]
I'd recommend using your own tap in that case.

**Comment by jgavris** [comment]
@JohanEngelen @ilovezfs Hopefully someone will make an llvm39 formula https://github.com/Homebrew/homebrew-versions/blob/master/llvm38.rb

**Comment by ilovezfs** [comment]
llvm.rb in core is the llvm39 formula.

**Comment by JohanEngelen** [comment]
I'd much appreciate the copy-paste from homebrew-core/llvm.rb to homebrew-versions/llvm39.rb !

**Comment by ilovezfs** [comment]
@JohanEngelen You can do that in your own tap ... it's not difficult to set up: https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by JohanEngelen** [comment]
[sigh]  https://github.com/Homebrew/homebrew-versions/pull/1446

**Comment by JohanEngelen** [comment]
This is very frustrating. Installing an arbitrary version of llvm (`brew install llvm`) is bound to give build problems for people. Not having a versioned `llvm` install available effectively means that brew cannot be used for it. Unfortunately, it appears TravisCI does not come with macports preinstalled, otherwise I would have switched already.

**Comment by MikeMcQuaid** [comment]
> [sigh] Homebrew/homebrew-versions#1446

I'm not sure what reaction you expected with "I have no clue about homebrew contribution guidelines and do not wish to know."

> Installing an arbitrary version of llvm (brew install llvm) is bound to give build problems for people.

Which is why we allow you to install older versions in homebrew/versions, any version pinned to a version from your own tap and are working on improving our versions support (https://github.com/Homebrew/brew/issues/620).

> Not having a versioned llvm install available effectively means that brew cannot be used for it.

The large numbers of people doing `brew install llvm` disagree with you.

> Unfortunately, it appears TravisCI does not come with macports preinstalled, otherwise I would have switched already.

I'm not sure what this is meant to communicate to us. You can make your TravisCI job install MacPorts, checkout a specific version of Homebrew and disable auto-update, install from your own tap, etc. If you'd behaved a little differently I'd be willing to help you do that but you didn't so I'm not, sorry.

**Pull request closed without merging**
