### PR TITLE
imagemagick 6.9.5-8

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by dunn** [comment]
Merged as 24f57d2090385b5b907c3e2aeecf9d0a50fbc9ce, thanks!

**Comment by DomT4** [comment]
@dunn Gentle nudge to remember to `brew mirror imagemagick` after merging to avoid the upstream purging their servers & breaking `fetch` each new version issue.

**Comment by dunn** [comment]
Oops, thanks for the reminder.  And I didn't realize we had a subcommand now!

**Comment by DomT4** [comment]
Aye, Mike got tired of waiting for me & did it himself a while back 🙈.

**Pull request closed without merging**
