### PR TITLE
iproute2mac 1.2.0

### PR DESCRIPTION
**Pull request by brona**
iproute2mac 1.2.0

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
Duplicate of #12760

**Comment by ilovezfs** [comment]
I will defer to @brona since he's upstream.

**Comment by brona** [comment]
It is not passing tests.. will release 1.2.1 shortly. Closing for now

**Comment by ilovezfs** [comment]
OK, no problem.

**Pull request closed without merging**
