### PR TITLE
pgplot: restore C bindings

### PR DESCRIPTION
**Pull request by ludwigschwardt**
Even though PGPLOT is a Fortran library, it also supports C bindings via a wrapper library (`libcpgplot`). This wasn't built because of a typo in the formula. Restore the wrapper library and also add a test for the C version.

See http://www.astro.caltech.edu/~tjp/pgplot/cbinding.html for more details. The test currently uses `gfortran` to link the final executable as suggested there, although `clang` also seems to work. The test plots also work with X11 even without explicitly linking against it in the executable, so go for the simplest setup that works.

Bump the revision to get working bottles again (is this necessary?)

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Nice catch @ludwigschwardt!

Should we be executing the test programs? It seems odd that they're built but not executed.

**Comment by ilovezfs** [comment]
>Is there a way to teleport into the test environment à la brew install -i or brew install -d?

Yes. Add a line `raise "here"` to the test block, and then run the test with -d

That'll give you an opportunity to drop down into the shell.

**Comment by ludwigschwardt** [comment]
Thanks for that, very useful! I now execute both the Fortran and C tests and check that their results are equal.

**Comment by ilovezfs** [comment]
Excellent work here, @ludwigschwardt! Shipped.

**Comment by ludwigschwardt** [comment]
I'm pleased too - it's my first PR to someone else's repo in 4 years (after 366 PRs to my own)!

**Comment by ilovezfs** [comment]
Wow, that's quite a while. Don't be a stranger! We look forward to your next contribution.

**Pull request closed without merging**
