### PR TITLE
arduino-cli 0.19.0

### PR DESCRIPTION
**Pull request by ArduinoBot**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /usr/local/Cellar/arduino-cli/0.19.0/bin/arduino-cli completion bash` exited with 2. Here's the output:
```

**Comment by umbynos** [comment]
I think the problem resides in https://github.com/Homebrew/homebrew-core/pull/84497/files#diff-1f27f53ebc531ef63e26b37fdf625548a950e332499585c592a8dfd731f937bfR34

applying this patch should solve the problem:

```diff
-    output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/arduino-cli", "completion", "bash")
+    output = Utils.safe_popen_read(bin/"arduino-cli", "completion", "bash")
     (bash_completion/"arduino-cli").write output
 
-    output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/arduino-cli", "completion", "zsh")
+    output = Utils.safe_popen_read(bin/"arduino-cli", "completion", "zsh")
     (zsh_completion/"_arduino-cli").write output
 
-    output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/arduino-cli", "completion", "fish")
+    output = Utils.safe_popen_read(bin/"/arduino-cli", "completion", "fish")
     (fish_completion/"arduino-cli.fish").write output
 ```
 Or should I open a new PR?

**Comment by carlocab** [comment]
Thanks, @umbynos. I've applied the change you suggested.

**Comment by umbynos** [comment]
@carlocab That's really strange... The last release we did, everything was working just fine… 
From what I see, the only things that changed in the recipe are [this](https://github.com/Homebrew/homebrew-core/commit/28665a768f4545eda47d6e42658223bd6a41508f#diff-1f27f53ebc531ef63e26b37fdf625548a950e332499585c592a8dfd731f937bf) and [this](https://github.com/Homebrew/homebrew-core/commit/fcde17117ff4f76159d01eb6b6e0305df1df2820#diff-1f27f53ebc531ef63e26b37fdf625548a950e332499585c592a8dfd731f937bf). This problem could be related to them?
I really don' t know how to solve this problem… There's a way to run the step run by the CI locally? running `arduino-cli completion bash` works just fine on my machine. There's some documentation that I'm missing?
I' ve tried to download the artifact `bottles.zip` in the github checks page and the completion are correctly placed in `/arduino-cli/0.19.0/etc/bash_completion.d/arduino-cli` and `/arduino-cli/0.19.0/share/fish/vendor_completions.d/arduino-cli.fish`,`/arduino-cli/0.19.0/share/zsh/site-functions/_arduino-cli`

**Comment by carlocab** [comment]
Ah, I think I see the problem. You have an `x/sys` dependency. You might be using a version that isn't working with Go 1.17.

Can that be updated to a newer version? I think that should fix the problems here.

**Comment by per1234** [comment]
It has already been updated by https://github.com/arduino/arduino-cli/pull/1427 but that happened after the Arduino CLI 0.19.0 release.

**Comment by umbynos** [comment]
Ok, so we'll need another release. We'll do it on Monday. I think we can close this one. I'm planning to pin also the go version used to build in the recipe, ATM we use 1.16 in our release pipeline

**Comment by umbynos** [comment]
On second thought, it would be nice to have arduino-cli version 0.19.0 in the homebrew repo. Users might want to go back to that specific version, and having it missing would be unfortunate. Pinning the go version used for the build to 1.16 ([like this](https://github.com/Homebrew/linuxbrew-core/blob/6f9becaf1c6018cb006b0b2eeec00837fa1c0e9f/Formula/modd.rb#L21) ) should be sufficient for now.
``` diff
-  depends_on "go" => :build
+  depends_on "go@1.16" => :build
```
In the next release we will fix the problem with go 1.17.
What do you think @carlocab? It's doable?

**Comment by carlocab** [comment]
Apologies for the delay -- there are a lot of PRs to keep up with here.

Can we apply a patch from https://github.com/arduino/arduino-cli/pull/1427? That would be ideal, I think. If not then we can build with `go@1.16`.

**Comment by umbynos** [comment]
No problem for the delay!  I think for now the best solution is to pin the go version used to build, since our binaries are built using go 1.16.
FYI We are planning a small minor release which will include the dependency bump.

**Comment by umbynos** [comment]
@carlocab any news?

**Review by carlocab — APPROVED** [review]
Sure, let's use Go 1.16.

**Pull request closed without merging**
