### PR TITLE
redis 3.2.6

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by neutric** [comment]
@ilovezfs Thanks for kicking the test off again! For next time: should mere contributors stay away from using "test this please"?

**Comment by ilovezfs** [comment]
@neutric yeah, you have to force push instead.

**Comment by neutric** [comment]
Ok! Thanks for letting me know. :)

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
