### PR TITLE
xgboost 1.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
[ 90%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o
cd /tmp/xgboost-20210420-54288-x2xcx8/build/src && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DDMLC_CORE_USE_CMAKE -DDMLC_LOG_CUSTOMIZE=1 -DDMLC_USE_CXX11=1 -DXGBOOST_BUILTIN_PREFETCH_PRESENT=1 -DXGBOOST_MM_PREFETCH_PRESENT=1 -D_MWAITXINTRIN_H_INCLUDED -D__USE_XOPEN2K8 -I/tmp/xgboost-20210420-54288-x2xcx8/include -I/tmp/xgboost-20210420-54288-x2xcx8/dmlc-core/include -I/tmp/xgboost-20210420-54288-x2xcx8/rabit/include -I/tmp/xgboost-20210420-54288-x2xcx8/build/dmlc-core/include -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC -funroll-loops -Xclang -fopenmp -std=gnu++14 -MD -MT src/CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o -MF CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o.d -o CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o -c /tmp/xgboost-20210420-54288-x2xcx8/src/tree/updater_refresh.cc
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
```

**Comment by trivialfis** [comment]
Is there any way we can look into the crash log of clang?

**Comment by carlocab** [comment]
I don't think those logs are recoverable from the runner, unfortunately.

**Comment by carlocab** [comment]
Yup, I can see that. Let me try and figure out a way to fish them out from the runner.

**Comment by carlocab** [comment]
Let's try to re-run this.

**Pull request closed without merging**
