### PR TITLE
update Molten-VK (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by iMonZ**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Are you not able to test these changes locally?

**Comment by iMonZ** [comment]
> Are you not able to test these changes locally?

No!
My Xcode is currently unable to build anything from the command line!
After it detects IOS devices in my area it stopped.

**Comment by iMonZ** [comment]
> > Are you not able to test these changes locally?
> 
> No!
> My Xcode is currently unable to build anything from the command line!
> After it detects IOS devices in my area it stopped.

Sorry for that but I just want to fix this formula

**Comment by carlocab** [comment]
You can test this on a GitHub runner:

See https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

Just create your own tap and add this version of the formula to it in a PR to your own GitHub repo.

**Comment by iMonZ** [comment]
> You can test this on a GitHub runner:
> 
> See https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/
> 
> Just create your own tap and add this version of the formula to it in a PR to your own GitHub repo.

Thanks

**Pull request closed without merging**
