### PR TITLE
tbb 2021.2.0

### PR DESCRIPTION
**Pull request by carlocab**
Continuation of #72682.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> FAILED
mlt:
  * mlt contains conflicting version recursive dependencies:
      tbb, tbb@2020
    View these with `brew deps --tree mlt`.
opencv@3:
  * opencv@3 contains conflicting version recursive dependencies:
      tbb, tbb@2020
    View these with `brew deps --tree opencv@3`.
synfig:
  * synfig contains conflicting version recursive dependencies:
      tbb, tbb@2020
    View these with `brew deps --tree synfig`.
Error: 3 problems in 3 formulae detected
Error: mlt contains conflicting version recursive dependencies:
  tbb, tbb@2020
View these with `brew deps --tree mlt`.

Error: opencv@3 contains conflicting version recursive dependencies:
  tbb, tbb@2020
View these with `brew deps --tree opencv@3`.

Error: synfig contains conflicting version recursive dependencies:
  tbb, tbb@2020
View these with `brew deps --tree synfig`.
```

**Comment by carlocab** [comment]
Hmmm. This will be difficult.

**Comment by carlocab** [comment]
Fixing `opencv@3` so it can depend on `tbb` instead of `tbb@2020` should fix all of this, though.

**Comment by carlocab** [comment]
Will try to backport https://github.com/opencv/opencv/pull/19384.

**Comment by bayandin** [comment]
Thanks for doing this, @carlocab!

**Comment by carlocab** [comment]
Don't thank me yet, we don't know if my backported patch works 😄

**Comment by carlocab** [comment]
Oops. Missed a line in the patch.

**Comment by carlocab** [comment]
Mojave failed with what looks like the same error as in https://github.com/Homebrew/homebrew-core/pull/77278.

I found a really weird fix referenced in various places: https://stackoverflow.com/questions/53603246/strange-error-running-osascript-e-command-on-macos-mojave

**Comment by carlocab** [comment]
Tried logging into the Mojave nodes to try the [fix suggested above](https://stackoverflow.com/questions/53603246/strange-error-running-osascript-e-command-on-macos-mojave), but I can't log into Orka for some reason.

Tempted to make `opencascade` depend on Catalina, at least in the interim while I figure out a fix for the `opencascade` Mojave bottle. (Not sure `opencascade` should be holding back a `tbb` upgrade too...)

**Comment by carlocab** [comment]
Tested the `opencascade` bottle locally. Seems to be working fine. Pretty sure it's a CI problem, and not a problem with the bottle. Merging this and uploading the built `opencascade` Mojave bottle too.

**Pull request closed without merging**
