### PR TITLE
Use cert bundle generated by Brew's OpenSSL in PHP formula.

### LINKED ISSUE #37702: PHP, OpenSSL, Composer and not found cert bundle
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install brew versions of PHP and Composer and run Composer

- What happened (include command output)
Running composer with brew PHP version results in
```
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```

- What you expected to happen
If I install PHP and Composer from brew, I'd expect it to work without modifying configuration files.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install php composer
composer update # I used it on a `typo3/cms-base-distribution` project
```

[It seems that the OpenSSL formula builds a CA bundle out of the keychain](https://github.com/Homebrew/homebrew-core/blob/63063c790f814ff24a6d66631b7174f59e2dbeaa/Formula/openssl.rb#L71), but PHP does not find it. I fixed this by editing `/usr/local/etc/php/7.3/php.ini` and setting the following settings:
```
openssl.cafile=/usr/local/etc/openssl/cert.pem
openssl.capath=/usr/local/etc/openssl/certs
```

I think the lines should be there by default. Googling for the issue results in a lot of questions concerning this error message and a lot of weird "fixes", which do not help. It is necessary to understand the problem thoroughly (Keychain vs. file based certs), what the problem is (PHP does not find certs) and understand what the OpenSSL formula is doing (exporting keychain to files). I doubt it should be necessary to understand all that to have a working composer installation out of Homebrew.

### PR DESCRIPTION
**Pull request by UlrichThomasGabor**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This fixes #37702.

Changed it in the older formulae as well, although I did not run the tests for these. Should be fine though, nothing has substantially changed.

### CODE REVIEW

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by UlrichThomasGabor** [comment]
@zbeekman The failed checks are all style checks. These have failed last time already, but to be honest, I do not understand the proposed modification, as I just copy&pasted another regular expression out of this file. It makes no sense to me to mix multiple regular expression styles in one file.

**Comment by zbeekman** [comment]
> @zbeekman The failed checks are all style checks.

This doesn't mean they can be ignored

> It makes no sense to me to mix multiple regular expression styles in one file.

We prefer the slash-syntax for regexes. In some instances, the re itself has characters that require you to use the `%r{}` syntax.

> to be honest, I do not understand the proposed modification

`brew style`, which you can run locally (it runs as part of `brew audit --strict` too) tells you exactly which line numbers need fixing. Please run this command and follow its advice. If the inconsistency bothers you, and you're able to change the other instances of `%r{...}` to `/.../` without causing a syntax error or triggering a complaint from `brew audit --strict` then you're welcome to change them for consistency. (But my quick look at it seems to indicate that they are required.)

**Comment by UlrichThomasGabor** [comment]
Appended new, passing, rebased commits. Although they fail with some http errors in the CI, I do not know why (@zbeekman).

It may also be useful to extend the CI or [documentation](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) by automatically applying / mentioning `--fix`, which is the function I have used now. This would have likely saved a lot of time on this issue.

And, to be honest, I think the contribution handling in general could benefit from some rethinking/rework from the side of the homebrew team. My personal experience with the issue and pull request did not exactly motivate me to contribute more—mainly because of the stale bot.

**Comment by zbeekman** [comment]
> It may also be useful to extend the CI or [documentation](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) by automatically applying / mentioning `--fix`, which is the function I have used now.

This is a good idea.


> My personal experience with the issue and pull request did not exactly motivate me to contribute more—mainly because of the stale bot.

I'm sorry to hear that. We have to strike a balance between being efficient and being thorough. Unfortunately, it is hard enough when everything is working correctly to stay on top of PRs, and when CI hits issues we get a backlog. This is further compounded by users submitting PRs without testing them locally. This holds up the CI queue and creates failing PRs we need to respond to. Without Stalebot, we would have many thousands of opened and abandoned PRs from users. We do not have the man-power to badger everyone who submits a less than stellar PR. We have to triage to be as efficient as possible to keep up with contributions and package upgrades.

You opened the PR during a particularly rough time (due to recurring CI infra failures) and between prioritizing getting everything fixed and dealing with the onslaught of new PRs yours slipped through the cracks.

**Comment by zbeekman** [comment]
It's possible that rebasing this branch on master will fix the https errors. For now, I'll just retry it and see what happens.

@BrewTestBot test this please

**Comment by UlrichThomasGabor** [comment]
> It's possible that rebasing this branch on master will fix the https errors. For now, I'll just retry it and see what happens.

Ah, I forgot `fetch` before the last rebase. I have just done it again, before CI runs for another hour just resulting in an error again.

**Comment by UlrichThomasGabor** [comment]
@zbeekman Passes now.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
