### PR TITLE
stone-soup: fix `python3` references.

### PR DESCRIPTION
**Pull request by miles170**
See #108008.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by miles170** [comment]
@carlocab What should I do to fix `Formulae in homebrew/core should not have a Linux-only dependency on GCC.`

**Comment by carlocab** [comment]
Remove the
```ruby
on_linux do
  depends_on "gcc"
end
```
block. We'll need to publish new bottles for this.

**Comment by miles170** [comment]
> Remove the
> 
> ```ruby
> on_linux do
>   depends_on "gcc"
> end
> ```
> 
> block. We'll need to publish new bottles for this.

did it means that gcc is implicit dependency?

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
It was necessary because `stone-soup` did not compile with our system gcc on CI (gcc 5 on ubuntu 16.04). So we forced the usage of brewed gcc 11.

We switched to ubuntu 22.04 for our CI with brew 3.6.0, so we now use system gcc everywhere, so no need to install brewed gcc anymore.

**Pull request closed without merging**
