### PR TITLE
argyll-cms 2.1.2

### PR DESCRIPTION
**Pull request by jd-a**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jd-a** [comment]
I had tried using brew bump-formula-pr, but could not get brew to handle git correctly

**Comment by fxcoudert** [comment]
```
numlib/numsup.c:844:25: error: too many arguments to function call, expected 0, have 2
        if ((pi = objc_msgSend((id)pic, pis)) == nil) {
                  ~~~~~~~~~~~~ ^~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
OBJC_EXPORT void
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
#   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
#       define OBJC_EXTERN extern
                           ^
```

with Xcode 11

**Comment by mistydemeo** [comment]
Here's documentation on the change to the prototype: https://www.mikeash.com/pyblog/objc_msgsends-new-prototype.html

It sounds like the old version "just worked" in ways that were technically incorrect. The new version is designed to fail without casting it to a specific appropriate type. The old prototypes are available if `OBJC_OLD_DISPATCH_PROTOTYPES` is defined.

> This can be remedied by casting objc_msgSend to have the right signature. Recall that objc_msgSend's actual prototype is that of whatever method will end up being invoked, so the correct way to use it is to cast it to the corresponding function pointer type. This call works correctly:

>    `((void (*)(id, SEL, float))objc_msgSend)(obj, @selector(log:), M_PI);`

**Comment by mistydemeo** [comment]
Merged via a followup PR incorporating your commit. Thanks!

**Comment by chenrui333** [comment]
Superseded by #49669

**Pull request closed without merging**
