### PR TITLE
Various formulae: resolve deprecated SPDX licenses

### PR DESCRIPTION
**Pull request by kthchew**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
  - Note: `lzo` has a problem here about build-time checks, unrelated to licenses

-----
I believe that these formulae should all be `GPL-3.0-or-later`:

- [`adns`](https://www.chiark.greenend.org.uk/ucgi/~ianmdlvl/git?p=adns.git;a=blob;f=client/addrtext.c;h=6f893b1d60896414b6590c42bab4ba8889e2ced5;hb=HEAD)
- [`libunistring`](https://git.savannah.gnu.org/gitweb/?p=libunistring.git;a=blob;f=lib/Makefile.am;h=6136cedbfb3e42af71804e40434103c0f7f34542;hb=HEAD)
- [`shellcheck`](https://github.com/koalaman/shellcheck/blob/master/src/ShellCheck/Formatter/Quiet.hs)
- [`gdbm`](https://ftp.gnu.org/gnu/gdbm/gdbm-1.18.1.tar.gz); see, for example, `Makefile.in` after extracting that file
- [`graphite2`](https://github.com/silnrsi/graphite/blob/master/src/CmapCache.cpp)
- [`libidn2`](https://gitlab.com/libidn/libidn2/-/blob/master/src/idn2.c) (note: this was formerly marked as "GPL-2.0")

because of this clause (or similar) I found in the above files:

> you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.

----------------

I believe these formulae should be `GPL-2.0-or-later`:

- [`rtmpdump`](https://git.ffmpeg.org/gitweb/rtmpdump.git/blob/HEAD:/rtmpdump.c); you may need to download the [raw file](https://git.ffmpeg.org/gitweb/rtmpdump.git/blob_plain/HEAD:/rtmpdump.c) or clone the repo with `git clone git://git.ffmpeg.org/rtmpdump` to view the file
- [`frei0r`](https://github.com/dyne/frei0r/blob/master/src/filter/3dflippo/3dflippo.c)
- [`lzo`](https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz); see `src/compr1b.h`
- [`xvid`](http://websvn.xvid.org/cvs/viewvc.cgi/trunk/xvidcore/src/decoder.c?view=markup)

because of the clause (or similar) I found in the above files:

> you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version. 

----------------

I believe these should be `LGPL-2.1-or-later`:

- [`fribidi`](https://github.com/fribidi/fribidi/blob/master/bin/fribidi-benchmark.c)
- [`npth`](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=npth.git;a=blob;f=configure.ac;h=8a9373c2da735a4dcaec3bb002cedafa05a6ef25;hb=HEAD)

because of the clause I found in the above files:

> you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.

----------------

`LGPL-2.0-or-later`:

- [`lame`](https://sourceforge.net/p/lame/svn/HEAD/tree/trunk/hip/lib/common.c)

has this clause:

> you can redistribute it and/or modify it under the terms of the GNU Library General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

----------------

`MIT`:

- [`pixman`](https://cgit.freedesktop.org/pixman/tree/COPYING), formerly "LGPL-2.1"

---------------

`libksba`'s license was changed to `any_of: ["LGPL-3.0-or-later", "GPL-2.0-or-later"]` because in `src/ksba.h` from [here](https://www.gnupg.org/ftp/gcrypt/libksba/libksba-1.5.0.tar.bz2), I found this clause:

```
> KSBA is free software; you can redistribute it and/or modify
> it under the terms of either
>
>   - the GNU Lesser General Public License as published by the Free
>     Software Foundation; either version 3 of the License, or (at
>     your option) any later version.
>
> or
>
>   - the GNU General Public License as published by the Free
>     Software Foundation; either version 2 of the License, or (at
>     your option) any later version.
>
> or both in parallel, as here.
```

---------------

`xz` seems to be most complicated. Its license is at https://git.tukaani.org/?p=xz.git;a=blob;f=COPYING;h=20e60d5b2427334e1fec6701e7c5ad0da0bc8a5d;hb=HEAD. Based on that information, I used the following license:

```
license all_of: [
  :public_domain,
  "LGPL-2.1-or-later",
  "GPL-2.0-or-later",
  "GPL-3.0-or-later",
]
```

Not 100% sure on that, so please tell me if that's wrong!

### CODE REVIEW

**Comment by jonchang** [comment]
Thanks for your first contribution to Homebrew, @kthchew! These mostly look good, but I checked these files and have some suggestions:

adns - adns.h is licensed under LGPLv2 or later

fribidi - getopt.c is GPL2+, but it's unclear if this is used in the build. It may be safest to just include that license as well.

graphite2 - this is trilicensed:

> Alternatively, the contents of this file may be used under the terms of the
> Mozilla Public License (http://mozilla.org/MPL) or the GNU General Public
> License, as published by the Free Software Foundation, either version 2
> of the License or (at your option) any later version.


libidn2 - this is dual licensed:

> The source code for the C library (libidn2.a or libidn.so) are
> licensed under the terms of either the GNU General Public License
> version 2.0 or later (see the file COPYINGv2) or the GNU Lesser
> General Public License version 3.0 or later (see the file
> COPYING.LESSERv3), or both in parallel as here.

libunistring - this is dual licensed:

> The libunistring library and its header files are dual-licensed under
> "the GNU LGPLv3+ or the GNU GPLv2". This means, you can use it under either
>   - the terms of the GNU Lesser General Public License (LGPL) version 3 or
>     (at your option) any later version, or
>   - the terms of the GNU General Public License (GPL) version 2, or
>   - the same dual license "the GNU LGPLv3+ or the GNU GPLv2".

rtmpdump - librtmp is licensed LGPLv2.1+, while the overall software is GPLv2+

**Comment by kthchew** [comment]
Thanks for checking; I’ll make changes when I find the time, hopefully later today. For clarification, when a project has files with a different license from the project itself, such as with `adns`, I should use `all_of` to list them all, correct?

**Comment by jonchang** [comment]
> For clarification, when a project has files with a different license from the project itself, such as with `adns`, I should use `all_of` to list them all, correct?

Yeah, except in the case where they are explicitly dual or tri-licensed like in the case of e.g. graphite2, in which case you should use `any_of` as the upstream lets you choose which license applies.

**Comment by kthchew** [comment]
I've made the suggested changes. As a side note, I found that graphite2 seems to specifically use MPL-1.1+ as shown [here](https://github.com/silnrsi/graphite/blob/92f59dcc52f73ce747f1cdc831579ed2546884aa/setup.py), but when I used "MPL-1.1+" in the `graphite2.rb` file, `brew audit --strict graphite2` showed a warning stating that "MPL-1.1+" was deprecated.

```
graphite2:
  * Formula graphite2 contains deprecated SPDX licenses: ["MPL-1.1+"].
    You may need to add `-only` or `-or-later` for GNU licenses (e.g. `GPL`, `LGPL`, `AGPL`, `GFDL`).
    For a list of valid licenses check: https://spdx.org/licenses/
```

Removing the + and just having "MPL-1.1" removed the warning, so I ended up removing it.

According to https://spdx.org/licenses/, there is no valid identifier like "MPL-1.1-or-later" (and when I tried, it was invalid, anyway). "MPL-1.1+" is not listed as deprecated on that site, as well. Is this a bug in how `brew audit` checks for deprecated licenses, or have I missed something?

**Comment by jonchang** [comment]
> According to https://spdx.org/licenses/, there is no valid identifier like "MPL-1.1-or-later" (and when I tried, it was invalid, anyway). "MPL-1.1+" is not listed as deprecated on that site, as well. Is this a bug in how brew audit checks for deprecated licenses, or have I missed something?

Yeah, this is probably a brew bug. I'll look into it later.

**Comment by kthchew** [comment]
> Yeah, this is probably a brew bug. I'll look into it later.

I think I was able to solve the issue. All non-deprecated licenses ending with a "+" are incorrectly being marked as deprecated. I'll make a PR.

**Comment by jonchang** [comment]
Thanks for the pull requests, and congratulations on your first contributions to Homebrew, @kthchew!

**Review by teetee-make — COMMENTED** [review]
I'm in

**Review by teetee-make — COMMENTED** [review]
****

**Pull request merged**
