### PR TITLE
trace2html 2015-07-07

### PR DESCRIPTION
**Pull request by bfontaine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```

trace-viewer has moved!
===========================================================================
We're now part of the
[catapult repo](https://github.com/catapult-project/catapult).

trace-viewer is located at [github.com/catapult-project/catapult/tree/master/tracing](https://github.com/catapult-project/catapult/tree/master/tracing)
```
https://github.com/google/trace-viewer/blob/master/README.md

**Comment by bfontaine** [comment]
@ilovezfs Unfortunately the new repo has no tag so we can’t use the new URL.

**Comment by ilovezfs** [comment]
Then we need to get them to tag.

**Comment by bfontaine** [comment]
Seems like there’ve been an issue for this sitting upstream for almost a year: https://github.com/catapult-project/catapult/issues/2323

Closing for now.

**Pull request closed without merging**
