### PR TITLE
hdf5: build with fortran by default

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
@fxcoudert @ilovezfs As discussed in #16223

**Comment by fxcoudert** [comment]
Does this need `cxxstdlib_check :skip` to avoid `Warning: hdf5 dependency gcc was built with a different C++ standard`?

**Comment by fxcoudert** [comment]
Fortran test:

```
(testpath/"test.f90").write <<-EOS.undent
  use hdf5
  integer(hid_t) :: f, dspace, dset
  integer(hsize_t), dimension(2) :: dims = [2, 2]
  integer :: error = 0, major, minor, rel

  call h5open_f (error)
  if (error /= 0) call abort
  call h5fcreate_f ("test.h5", H5F_ACC_TRUNC_F, f, error)
  if (error /= 0) call abort
  call h5screate_simple_f (2, dims, dspace, error)
  if (error /= 0) call abort
  call h5dcreate_f (f, "data", H5T_NATIVE_INTEGER, dspace, dset, error)
  if (error /= 0) call abort
  call h5dclose_f (dset, error)
  if (error /= 0) call abort
  call h5sclose_f (dspace, error)
  if (error /= 0) call abort
  call h5fclose_f (f, error)
  if (error /= 0) call abort
  call h5close_f (error)
  if (error /= 0) call abort
  CALL h5get_libversion_f (major, minor, rel, error)
  if (error /= 0) call abort
  write (*,"(I0,'.',I0,'.',I0)") major, minor, rel
  end
  EOS
system "#{bin}/h5fc", "test.f90"
assert_equal version.to_s, shell_output("./a.out").chomp
```

(Does `shell_output` actually test that the return code is zero?)

**Comment by fxcoudert** [comment]
And we want a revision-bump, don't we?

**Comment by iMichka** [comment]
Thanks for the test! Makes sense to have it :)

**Review by fxcoudert — APPROVED** [review]

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @iMichka!

**Pull request closed without merging**
