### PR TITLE
xrootd 5.0.3

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```==> brew linkage --test root
==> FAILED
Broken dependencies:
  /usr/local/opt/xrootd/lib/libXrdCl.2.dylib (xrootd)
  /usr/local/opt/xrootd/lib/libXrdClient.2.dylib (xrootd)
  /usr/local/opt/xrootd/lib/libXrdUtils.2.dylib (xrootd)

...
Error: 1 failed steps!
brew linkage --test root
```

Not sure why these dependencies are considered broken:
```
❯ brew deps root
...
xrootd
xz
zstd
```

`root` declares `xrootd` as a dependency.

**Comment by fxcoudert** [comment]
Probably `root` needs to be relinked against the newer version of xrootd, if it's a major update. Revision bump to root should do it.

**Comment by carlocab** [comment]
Right, of course. I think I got confused by the names and interpreted the dependency information I just posted as the reverse, which is why a revision bump didn’t occur to me. Will give that a try.

**Comment by carlocab** [comment]
root isn't failing here... which is good for this PR I guess, but suggests a problem elsewhere in the other CI runs. Though hopefully the xrootd bump fixed those too.

**Review by iMichka — APPROVED** [review]

**Comment by fxcoudert** [comment]
@carlocab a root update was committed recently, that fixed the root issue

**Comment by carlocab** [comment]
Sorry, closed this by mistake. Not sure when or how I did that, though. I think I may have been too keen to delete the branch once the PR was approved.

**Comment by iMichka** [comment]
It will go through CI again and be merged eventually, do not worry.

**Pull request closed without merging**
