### PR TITLE
terraform 0.7.13

### PR DESCRIPTION
**Pull request by cblecker**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by Ninir** [comment]
@cblecker Since the update, `Terraform version` is exposing something like `0.8.0-dev`. Any hint?

**Comment by cblecker** [comment]
@Ninir Looks like there was a problem with the release process upstream: https://github.com/hashicorp/terraform/issues/10357

**Comment by Ninir** [comment]
@cblecker thanks for the hint! 😄

**Pull request merged**
