### PR TITLE
nzbget 18.0

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
Yosemite-only build failure:

```
daemon/postprocess/RarReader.cpp:642:7: error: use of undeclared identifier 'PKCS5_PBKDF2_HMAC'
        if (!PKCS5_PBKDF2_HMAC(m_password, m_password.Length(), salt, 16,
             ^
1 error generated.
make[1]: *** [RarReader.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

Could be that the package is linking with OS X's outdated SSL instead of the OpenSSL dep?

**Comment by neutric** [comment]
In a previous iteration, I tried adding
```ruby
"--with-openssl-includes=#{Formula["openssl"].opt_include}",
"--with-openssl-libraries=#{Formula["openssl"].opt_lib}"
```
which did not fix the problem, neither does using openssl 1.1, which in hindsight I didn't even have to try... 

Help would be appreciated.

**Comment by ilovezfs** [comment]
@neutric 
```
diff --git a/Formula/nzbget.rb b/Formula/nzbget.rb
index b8f0453..d99ce26 100644
--- a/Formula/nzbget.rb
+++ b/Formula/nzbget.rb
@@ -36,7 +36,8 @@ class Nzbget < Formula
 
     # Fix "ncurses library not found"
     # Reported 14 Aug 2016: https://github.com/nzbget/nzbget/issues/264
-    ENV["ncurses_CFLAGS"] = "-I/usr/include"
+    (buildpath/"brew_include").install_symlink MacOS.sdk_path/"usr/include/ncurses.h"
+    ENV["ncurses_CFLAGS"] = "-I#{buildpath}/brew_include"
     ENV["ncurses_LIBS"] = "-L/usr/lib -lncurses"
 
     # Tell configure to use OpenSSL
```

**Comment by neutric** [comment]
@ilovezfs 🍻  :)

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@neutric you're welcome!

**Comment by ilovezfs** [comment]
Shipped! Thanks @neutric :newspaper:

**Comment by ilovezfs** [comment]
@neutric you inspired this: https://github.com/Homebrew/homebrew-core/pull/9965.

**Pull request closed without merging**
