### PR TITLE
docker-compose 1.27.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — COMMENTED** [review]
Where do all these resources suddenly come from?

**Comment by chenrui333** [comment]
> Where do all these resources suddenly come from?

come with `brew bump-formula-pr`, unfortunately.

**Comment by SMillerDev** [comment]
If it's available on pypy maybe we can move to that source? And it should probably have a better test.

**Comment by chenrui333** [comment]
Sounds good to me, I will use pypi index instead.

**Comment by SMillerDev** [comment]
In that case it should be the resources right?

**Comment by chenrui333** [comment]
nope, I think it is ready to be merged.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
