### PR TITLE
libarchive 3.2.1

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for doing this. You must have read my mind.

**Comment by ilovezfs** [comment]
@alex Actually, it looks like the mirror needs to be removed because the checksum of the GitHub archive does not match.

**Comment by alex** [comment]
@ilovezfs done.

**Comment by ilovezfs** [comment]
Thanks!

**Comment by ilovezfs** [comment]
@alex thanks for your contribution to Homebrew! :balloon:

**Pull request closed without merging**
