### PR TITLE
pcre: deprecate along upstream instructions

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Related: https://github.com/Homebrew/homebrew-core/issues/91367

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I don't think we can/should deprecate this. Too much depends on it:
```console
$ brew uses pcre
aide                 fastq-tools          httpd                oq                   sord
aircrack-ng          fourstore            httpflow             passenger            stone-soup
apachetop            freeswitch           hyperscan            pcre++               suricata
bigloo               ganglia              libmp3splt           pdfgrep              swi-prolog
ccze                 gdal                 lighttpd             pev                  swig
cfengine             gforth               lnav                 pike                 swig@3
cgrep                glib                 logstalgia           postgis              the_silver_searcher
classads             gmt@5                luvit                privoxy              tintin
coccinelle           goffice              monetdb              r3                   tiny-fugue
collada-dom          gource               mydumper             rakudo-star          trafficserver
comby                grep                 ncmpc                rdup                 uwsgi
cppcheck             grok                 neko                 remctl               vimpc
cppcms               groonga              nginx                root                 watchman
crush-tools          gsmartcontrol        ngs                  scry                 yaf
crystal              haproxy              nu                   semgrep              zabbix
ettercap             harbour              octave               shadowsocks-libev    zsh
exim                 hardlink             ohcount              simgrid
fastfec              haxe                 omega                snort
```

Perhaps some of those can be migrated to pcre2 but we definitely should not deprecate all these formulae.

**Comment by SMillerDev** [comment]
I don't want to either, but with the official source removed and upstream explicitly mentioning it's unsupported I'm not sure if we have options other than marking this deprecated.

**Comment by MikeMcQuaid** [comment]
@SMillerDev I think adding this to `caveats` would be a reasonable middle ground. My issue with deprecated is it's going to shout at people using those formulae and change our CI behaviour in an undesirable way.

**Comment by Bo98** [comment]
I will go through the list and see what the status of everything is.

The URL should however still be updated here. Maybe split that into a separate pull request so we can merge that sooner.

**Comment by MikeMcQuaid** [comment]
Thanks @Bo98, agreed.

**Comment by MikeMcQuaid** [comment]
We could also consider having a DSL tweak that says something like "deprecated but only complain when it's not installed as a dependency and still test dependencies in CI".

**Comment by Bo98** [comment]
* aide - will come in 0.18
* bigloo - #91379
* exim - will come in the next version
* gdal - will come in 3.4.1
* gforth - needs investigation to see where pcre is used
* gmt@5 - #91380
* goffice - needs investigation to see where pcre is used
* gource - will come in 0.52
* grep - will come in the next version
* haproxy - #91381
* hardlink - in 0.3.2 in the Debian git repo (formula is deprecated so this isn't a priority)
* haxe - being tracked upstream, targetting for 4.3
* httpd - supported in 2.5 (unstable) so will be a part of 2.6 stable.
* lighttpd - #91382
* ncmpc - #91386
* oq - needs investigation to see where pcre is used
* pev - #91388
* postgis - will come in 3.2.0
* rakudo-star - needs investigation to see where pcre is used
* scry - needs investigation to see where pcre is used
* simgrid - #91389
* suricata - will come in 6.1 or 7.0 (whatever is next)

This is going to be a fairly big migration job in general. Debian are targetting pcre2 migration by 2023 (Debian Bookworm release).

**Comment by SMillerDev** [comment]
Thanks @Bo98 ill try and rework this PR tomorrow

**Comment by carlocab** [comment]
I'm also against deprecating this. In general, I am against deprecating any formula that has (perhaps multiple) dependents. I've been planning to open a PR to update the documentation regarding deprecating/disabling formulae to reflect this -- will do this soon for discussion.

**Comment by carlocab** [comment]
Homebrew/brew#12727

**Pull request closed without merging**
