### PR TITLE
gitless 0.8.8

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by zbeekman** [comment]
The patch is either no longer needed or should be updated.

**Comment by chenrui333** [comment]
ack, update it now.

**Comment by chenrui333** [comment]
Surprisingly, it built locally but failed in the test part

**Comment by chenrui333** [comment]
Now after removing the patch, I received this error:
```
20:36:11 ==> Applying 4eb3a971d1d7d63fa359b60812a5a5df8b8a72db.patch
20:36:11 patch -g 0 -f -p1 -i /private/tmp/gitless--patch-20190525-10957-t7gmfa/4eb3a971d1d7d63fa359b60812a5a5df8b8a72db.patch
20:36:11 patching file gitless/core.py
20:36:11 Hunk #1 succeeded at 65 with fuzz 1 (offset 7 lines).
20:36:11 Hunk #2 FAILED at 81.
20:36:11 Hunk #3 FAILED at 122.
20:36:11 2 out of 3 hunks FAILED -- saving rejects to file gitless/core.py.rej
20:36:11 Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/gitless--patch-20190525-10957-t7gmfa/4eb3a971d1d7d63fa359b60812a5a5df8b8a72db.patch` exited with 1.
20:36:11 
```

**Comment by chenrui333** [comment]
Bumped to 0.8.8 to see if the issue still persists.

**Comment by SMillerDev** [comment]
Thanks @

**Pull request closed without merging**
