### PR TITLE
kibana 5.4.3

### PR DESCRIPTION
**Pull request by jasontedor**
This pull request bumps the version on the Kibana formula from version 5.4.2 to version 5.4.3.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@jasontedor the build appears to be feeling uncooperative today.

**Comment by ilovezfs** [comment]
@jasontedor it looks like this got retagged? :see_no_evil: 

```
==> Checking out tag v5.4.3
git checkout -f v5.4.3 --
HEAD is now at 0c83527... ensure no scroll-bar pops up inside timelion viz (#12298) (#12429)
Error: v5.4.3 tag should be 79c3ab1b64609651a88d889c0092490a5d96274f
but is actually 0c83527f76c8338a1ab83a30b42e2a46cadf74da
```

**Comment by ilovezfs** [comment]
@jasontedor the difference between those revisions is non trivial:
```
Josephs-MacBook-Pro:kibana joe$ git diff 79c3ab1b64609651a88d889c0092490a5d96274f..0c83527f76c8338a1ab83a30b42e2a46cadf74da|wc -l
   70683
```

Any idea what happened here?

**Comment by jasontedor** [comment]
I'll look into this.

**Comment by ilovezfs** [comment]
@jasontedor thanks!

**Comment by jasontedor** [comment]
It appears that it was initially mistagged but I have verified that the current v5.4.3 tag is now correct. I have pushed an update to reflect this.

**Comment by ilovezfs** [comment]
@jasontedor perfect. Thanks for looking into this! :crossed_fingers: it builds :)

**Comment by ilovezfs** [comment]
@jasontedor :green_apple: and shipped! Thanks for the upgrade. When you have a moment, do you mind reviewing https://github.com/Homebrew/homebrew-core/pull/15019 ?

**Comment by jasontedor** [comment]
Awesome. Thanks again @ilovezfs. I'll look at #15019 right now.

**Pull request closed without merging**
