### PR TITLE
axel 2.16.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like it needs pkg-config.

**Comment by mistydemeo** [comment]
Hm, looks like there's some trouble with type definitions.

**Comment by alebcay** [comment]
Looks like [it's not our first time to the rodeo](https://github.com/Homebrew/homebrew-core/pull/30931) with axel 2.16.x. [Upstream issue remains unfixed at this time](https://github.com/axel-download-accelerator/axel/issues/136).

**Comment by mistydemeo** [comment]
Opened a PR: https://github.com/axel-download-accelerator/axel/pull/196

**Comment by alebcay** [comment]
`axel` has been updated to 2.16.1 in #37319. 🎉

**Pull request closed without merging**
