### PR TITLE
libgpg-error 1.33

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
```
==> /usr/local/Cellar/anjuta/3.28.0_3/bin/anjuta --version
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2018-12-10 17:25:07.140 anjuta[45529:33914405] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff43eb659b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6b1e9942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff43ed004d -[__NSArray0 objectAtIndex:] + 93
	3   libgdk-3.0.dylib                    0x00000001098e44d5 gdk_quartz_screen_init + 49
	4   libgobject-2.0.0.dylib              0x0000000109c72ab8 g_type_create_instance + 612
	5   libgobject-2.0.0.dylib              0x0000000109c62caf g_object_new_internal + 50
	6   libgobject-2.0.0.dylib              0x0000000109c62768 g_object_new_with_properties + 376
	7   libgobject-2.0.0.dylib              0x0000000109c625d2 g_object_new + 154
	8   libgdk-3.0.dylib                    0x00000001098df3b7 _gdk_quartz_display_open + 130
	9   libgdk-3.0.dylib                    0x00000001098bdff1 gdk_display_manager_open_display + 407
	10  libgtk-3.0.dylib                    0x00000001093d08d4 post_parse_hook + 274
	11  libglib-2.0.0.dylib                 0x0000000109cd69cf g_option_context_parse + 2149
	12  anjuta                              0x00000001090b8a2c anjuta_application_local_command_line + 842
	13  libgio-2.0.0.dylib                  0x0000000109b3fa23 g_application_run + 339
	14  anjuta                              0x00000001090bc6e8 main + 74
	15  libdyld.dylib                       0x00007fff6be00015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Error: anjuta: failed
```

Not sure if it's High Sierra CI machine or revision bumps needed for:
- anjuta
- fuse-emulator
- gitg
- gopass

**Comment by tschoonj** [comment]
it's the High Sierra machine... see also #34937

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
