### PR TITLE
blastem 0.6.2

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
18:56:10 ==> brew audit blastem --online
18:56:52 ==> FAILED
18:56:52 ==> Installing 'bundler' gem
18:56:52 Successfully installed bundler-2.0.1
18:56:52 1 gem installed
18:56:52 Error: 1 problem in 1 formula detected
18:56:52 blastem:
18:56:52   * Stable: version 0.6.2 is redundant with version scanned from URL
18:56:52 
18:56:52 ==> brew style blastem
```

**Comment by zbeekman** [comment]
The test for this formula stinks. Any chance you could take a stab at making a better one?

**Comment by chenrui333** [comment]
Sure, I will take a chance now.

**Comment by chenrui333** [comment]
hmm, actually, I want to take a deep look tomorrow, looks like the formula test part is too simple right now. :)

**Comment by chenrui333** [comment]
resume

**Comment by chenrui333** [comment]
having some issue installing the formula locally:
```
-L/usr/local/lib -L/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -ljpeg -lopenjp2 -lz -ltiff -o build/lib.macosx-10.13-x86_64-2.7/PIL/_imaging.so
clang: error: no such file or directory: 'build/temp.macosx-10.13-x86_64-2.7/decode.o'
clang: error: no such file or directory: 'build/temp.macosx-10.13-x86_64-2.7/encode.o'
clang: error: no such file or directory: 'build/temp.macosx-10.13-x86_64-2.7/map.o'
clang: error: no such file or directory: 'build/temp.macosx-10.13-x86_64-2.7/display.o'
clang: error: no such file or directory: 'build/temp.macosx-10.13-x86_64-2.7/libImaging/Jpeg2KDecode.o'
clang: error: no such file or directory: 'build/temp.macosx-10.13-x86_64-2.7/libImaging/Jpeg2KEncode.o'
error: command 'clang' failed with exit status 1

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/blastem.rb
```

**Comment by SMillerDev** [comment]
Got it working yet?

**Comment by chenrui333** [comment]
oh, almost forgot this PR, checking it really quick.

**Comment by chenrui333** [comment]
I somehow still have local build issue, I will push the fix and run on CI.

**Comment by chenrui333** [comment]
@SMillerDev i have simplified the test step. I think it should be sufficient?

**Comment by chenrui333** [comment]
timeout.
```
1.1.5/lib:/Library/Ruby/Gems/2.3.0/gems/power_assert-0.2.6/lib:/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib:/Library/Ruby/Site/2.3.0:/Library/Ruby/Site/2.3.0/x86_64-darwin18:/Library/Ruby/Site/2.3.0/universal-darwin18:/Library/Ruby/Site:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/blastem.rb --verbose
10:24:36 ==> /usr/local/Cellar/blastem/0.6.2/bin/blastem -v
10:24:36 Killing child processes...
10:24:36 Error: blastem: failed
10:24:36 An exception occurred within a child process:
10:24:36   Timeout::Error: execution expired
10:24:36 /usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:12:in ``'
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
> having some issue installing the formula locally:

`brew unlink openjpeg` will fix that.

To fix the test you need to add `-g` with `-v` and find a way to convince blastem that it's being run in a terminal, otherwise it spawns a gui window with the version info. (Even with `-g`.)

**Comment by chenrui333** [comment]
Refreshed the PR now.

**Pull request closed without merging**
