### PR TITLE
pandoc 2.11

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
`pandoc-citeproc` says:

```
  MethodDeprecatedError: Calling Language::Haskell::Cabal.install_cabal_package is disabled! Use cabal v2-update directly followed by v2-install with std_cabal_v2_args instead.
```

**Comment by reagle** [comment]
Is this issue stalled? How to move forward?

**Comment by fxcoudert** [comment]
> How to move forward?

Investigate the `pandoc-citeproc` failure and fix it.

**Comment by reagle** [comment]
FYI: [2.11.04 was just released](https://github.com/jgm/pandoc/releases/tag/2.11.0.4) and upstream notes that 
"pandoc 2.11.0.3 was released on Hackage but deprecated,because of some errors." Perhaps that is the source of the problem here as well and addressed by 2.11.04 .

**Comment by jgm** [comment]
Note: pandoc 2.11.x no longer requires pandoc-citeproc (and pandoc-citeproc won't build with pandoc 2.11).  With pandoc 2.11 citation processing is integrated (`--citeproc` option), and the external pandoc-citeproc filter is no longer needed. It should not be provided by the brew package. Hope that helps.

**Comment by iandol** [comment]
Pandoc is currently at V2.11.1. So it seems that pandoc-citeproc should be deprecated / removed from brew core, and @owickstrom's pandoc-include-code is still outstanding a pull request to support Pandoc V2.11: https://github.com/owickstrom/pandoc-include-code/pull/34 — this will be held up until that gets merged...

pandoc-crossref has been updated for Pandoc V2.11, as has pandocomatic (currently at 0.2.7.4 to support Pandoc V2.11.1).

**Comment by chenrui333** [comment]
```
Error: 2 failed steps!
brew install --verbose --build-bottle pandoc-citeproc
brew test --verbose pandoc-include-code
```

**Comment by chenrui333** [comment]
Gonna fix `pandoc-include-code` in a separate PR.

**Comment by chenrui333** [comment]
`Error: pandoc-include-code--1.5.0.0_2.catalina.bottle.tar.gz for upload doesn't exist!`

**Comment by chenrui333** [comment]
```
Error: 1 failed steps!
brew install --verbose --build-bottle pandoc-citeproc
```

merging.

**Comment by chenrui333** [comment]
Thanks everyone involved with this PR!

**Pull request closed without merging**
