### PR TITLE
gmp 6.3.0

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> Created by `brew bump`
> 
> Created with `brew bump-formula-pr`.

@osalbahr are you actually using the command, this is a duplicate of #138036

**Comment by osalbahr** [comment]
> > Created by `brew bump`
> > Created with `brew bump-formula-pr`.
> 
> @osalbahr are you actually using the command, this is a duplicate of #138036

No, the command I was using was `brew bump --open-pr` (without args). I did not write the PR manually.

**Comment by chenrui333** [comment]
> > > Created by `brew bump`
> > > Created with `brew bump-formula-pr`.
> > 
> > 
> > @osalbahr are you actually using the command, this is a duplicate of #138036
> 
> No, the command I was using was `brew bump --open-pr` (without args). I did not write the PR manually.

please use the `brew bump --open-pr`, it should notify you about the open PR.

**Comment by osalbahr** [comment]
> > > > Created by `brew bump`
> > > > Created with `brew bump-formula-pr`.
> > > 
> > > 
> > > @osalbahr are you actually using the command, this is a duplicate of #138036
> > 
> > 
> > No, the command I was using was `brew bump --open-pr` (without args). I did not write the PR manually.
> 
> please use the `brew bump --open-pr`, it should notify you about the open PR.

Yes, I was running `brew bump --open-pr`. I agree that it should notify me. But I don't know why it went ahead and opened the PR anyways. I suspect it might have to do with me reaching the GitHub API limit (despite setting `HOMEBREW_GITHUB_API_TOKEN`) or that I was running the command without arguments.


Relevant logs:
```console
...
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 8 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 8 seconds
==> gmp
Current formula version:  6.2.1
Latest livecheck version: 6.3.0
Latest Repology version:  6.3.0
Open pull requests:       none
Closed pull requests:     none
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 5 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 5 seconds
Warning: This formula has patches that may be resolved upstream.
==> Downloading https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
######################################################################### 100.0%
Warning: Cannot verify integrity of '1acf0006a97f7e7f7422af38a067abfb2c6af0981fed5ac5368fa0607a14d5fa--gmp-6.3.0.tar.xz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"
==> replace /^  revision \d+\n(\n(  head "))?/m with "\\2"
==> replace / +mirror "https:\/\/ftp\.gnu\.org\/gnu\/gmp\/gmp\-6\.2\.1\.tar\.xz"
==> replace /https:\/\/gmplib\.org\/download\/gmp\/gmp\-6\.2\.1\.tar\.xz/ with "
==> replace "fd4829912cddd12f84181c3451cc752be224643e87fac497b69edddadc49b4f2" w
==> replace /^( +)(url "https:\/\/gmplib\.org\/download\/gmp\/gmp\-6\.3\.0\.tar\
M	Formula/arkade.rb
M	Formula/gmp.rb
Switched to a new branch 'bump-gmp-6.3.0'
[bump-gmp-6.3.0 44bb33337c4] gmp 6.3.0
 1 file changed, 3 insertions(+), 4 deletions(-)
remote: 
remote: Create a pull request for 'bump-gmp-6.3.0' on GitHub by visiting:        
remote:      https://github.com/osalbahr/homebrew-core/pull/new/bump-gmp-6.3.0        
remote: 
To https://github.com/osalbahr/homebrew-core.git
 * [new branch]              bump-gmp-6.3.0 -> bump-gmp-6.3.0
branch 'bump-gmp-6.3.0' set up to track 'https://******@github.com/osalbahr/homebrew-core.git/bump-gmp-6.3.0'.
https://github.com/Homebrew/homebrew-core/pull/138592
...
```

**Pull request closed without merging**
