### PR TITLE
gammaray 2.5.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
One of the build tests failed, apparently.

**Comment by ilovezfs** [comment]
@DomT4 yeah, I don't think it's not a real bug, just lldb not attaching, probably due to the sandbox. The test should be skipped instead of failing.

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
:shipit:

**Pull request closed without merging**
