### PR TITLE
protobuf 3.12.3

### PR DESCRIPTION
**Pull request by anderscarling**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by anderscarling** [comment]
Version of resource "six" bumped to version 1.15.0 as per discussion in #55423. 
Hash and download url fetched from https://pypi.org/project/six/#files

**Comment by anderscarling** [comment]
I think this will be fixed by a rebuild of libphonenumber - as the phonenumber.pb.h file seems to be generated at build time. I guess we should bump revision on that formula?

```
==> FAILED
161
Testing libphonenumber
162
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200603-78079-1vofq8c.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libphonenumber.rb --verbose
163
==> /usr/bin/clang++ -std=c++11 test.cpp -L/usr/local/Cellar/libphonenumber/8.12.4_2/lib -lphonenumber -o test
In file included from test.cpp:1:
In file included from /usr/local/include/phonenumbers/phonenumberutil.h:31:
/usr/local/include/phonenumbers/phonenumber.pb.h:47:51: error: no type named 'AuxillaryParseTableField' in namespace 'google::protobuf::internal'; did you mean 'AuxiliaryParseTableField'?
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
                                                  AuxiliaryParseTableField
```

**Comment by Moisan** [comment]
Could you squash together your first and second commit with the first commit message (`protobuf 3.12.3`)? We prefer to keep one commit per formula. After that it should be ready to merge.

**Comment by anderscarling** [comment]
@Moisan Done!

**Comment by anderscarling** [comment]
Error seems to be a coding problem in homebrew audit cmd:

```
Error: undefined local variable or method `release' for #<Homebrew::FormulaAuditor:0x00007ffdce1d9c90>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:701:in `audit_specs'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:932:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:925:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:925:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:122:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:115:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:115:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by anderscarling** [comment]
When fixing the issue manually (by replacing `release` with `@release` on line 701 and 702 in audit.rb), the style check is successful on my machine.

**Comment by Moisan** [comment]
I think the issue was solved since then, I'll relaunch the CI.

**Comment by Moisan** [comment]
The issue is still present so I opened PR https://github.com/Homebrew/brew/pull/7689
Thanks for the pointer how to solve this 👍 .

**Review by Moisan — APPROVED** [review]
Thank you @anderscarling ! Without people like you, we couldn't run this project.

**Pull request closed without merging**
