### PR TITLE
libgeotiff 1.5.1

### PR DESCRIPTION
**Pull request by alebcay**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @alebcay, can you incorporate the work already done in #38399?

**Comment by alebcay** [comment]
Think I got everything that I missed - just a bump for `pdal`. The patches in question in the previous PR should no longer be necessary (the commit in question should be built into 1.5.1).

**Comment by fxcoudert** [comment]
`liblas` not happy:

```
==> make test
Running tests...
/usr/local/Cellar/cmake/3.14.3/bin/ctest --force-new-ctest-process 
Test project /tmp/liblas-20190426-71425-1x4n0z2/libLAS-1.8.1/macbuild
    Start 1: liblas_test
1/1 Test #1: liblas_test ......................***Failed    0.25 sec
```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Audit failure on certificate of the website, it is probably temporary. Merging, thanks @alebcay

**Pull request closed without merging**
