### PR TITLE
pkg-config: correct default system include path

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by fredowski** [comment]
Hi, I was just in the process of preparing a pull request for pkg-config but maybe you can include the change in your fix here as it is also related to the pc_path. I have installed homebrew in a non-standard location. During install the bottled version of pkg-config is installed which is compiled with the default pc_path setting. I removed the "cellar :any_skip_relocation" line such that pkg-config is recompiled on a non-default homebrew location. You can see the change here:

https://github.com/fredowski/homebrew-core/commit/60f67ba72fcef0b388d67756973a7c16121b908f

Then pkg-config finds the correct packages also in my non-standard homebrew install location.

**Comment by Bo98** [comment]
I think the cellar value is indeed wrong (and has been so for years - this isn't anything new), but any change I make here will just get overwritten when @BrewTestBot builds the bottles.

Here's the code that determines which cellar value to use: https://github.com/Homebrew/brew/blob/1824435f678d1209cf787dbdfb1fcc261a199803/Library/Homebrew/dev-cmd/bottle.rb#L327-L342. If you can figure out why it detects the wrong one, that's probably the best way forward.

**Comment by fredowski** [comment]
Hi, I had a look at bottle.rb to figure out what might be wrong with the autodetection. My impression is that mainly file locations are checked. But in pkg-config we add the path via a hardcoded configure option. I found no way how this can be detected in bottle.rb file. Therefore I added the pour_bottle check in 

fredowski@60f67ba

I think that is the way how this is done in fontconfig

**Comment by fredowski** [comment]
I had a wrong link: https://github.com/fredowski/homebrew-core/commit/8d0e0e1420c805bf20e4d46dcf37fadad22400b6

**Comment by Bo98** [comment]
Ok so it's because the pc path appears as a single string `/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15` which will fail this check: https://github.com/Homebrew/brew/blob/1824435f678d1209cf787dbdfb1fcc261a199803/Library/Homebrew/dev-cmd/bottle.rb#L151

Your workaround is something that is applied to other formulae so I will apply it here for now until we look into the detection further. Thanks for raising the issue!

**Pull request closed without merging**
