### PR TITLE
direnv added caveats

### PR DESCRIPTION
**Pull request by NeckBeardPrince**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Just adding some post install instructions.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Sorry, but these caveats are not Homebrew-specific. We only add caveats when they're specific to Homebrew.

**Comment by carlocab** [comment]
Thanks for the PR anyway.

**Comment by NeckBeardPrince** [comment]
> Sorry, but these caveats are not Homebrew-specific. We only add caveats when they're specific to Homebrew.

Sorry, can you clarify the difference between my caveats and the ones used in [this](https://github.com/Homebrew/homebrew-core/blob/master/Formula/thefuck.rb#L56-L64) formula?

**Comment by carlocab** [comment]
There isn't, but we never should've added those caveats in the first place.

**Pull request closed without merging**
