### PR TITLE
Update ldid to 2.1.2

### PR DESCRIPTION
**Pull request by Diatrus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This updates ldid to it's latest version and also builds it manually with CC/CXX in order to bypass the issues with Saurik's make system.

### CODE REVIEW

**Comment by Moisan** [comment]
`brew audit` points that 'revision 1' should be removed.

**Comment by Diatrus** [comment]
@Moisan oddly enough, `brew audit —strict` didn’t tell me that. Fixed, regardless. :)

**Comment by Moisan** [comment]
Great, could you squash your commits in one using the commit message `ldid 2.1.2`? We should be good to merge after that.

**Comment by Diatrus** [comment]
Done deal @Moisan.

**Review by Moisan — APPROVED** [review]
Thank you @Diatrus for your first contribution! Without people like you, we couldn't run this project.

**Pull request closed without merging**
