### PR TITLE
haskell-stack: make the bottles Sierra compatible

### PR DESCRIPTION
**Pull request by ilovezfs**
Remove the rpaths, which aren't actually needed here, so that the
El Capitan bottles can be deployed on Sierra too.

Add MaximumMacOSRequirement when bottling to prevent CI failure.

Raise an exception at the beginning of the `install` method to prevent
known-to-fail source builds on Sierra.

CC @zmwangx @borsboom

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 hmmm looks like max os requirement fails CI unconditionally ...

**Comment by DomT4** [comment]
The CI passes `--build-bottle` though right? So `if build.bottle?` would be true here? Am I missing something? 🙈

**Comment by ilovezfs** [comment]
@DomT4 right, so as a result, shouldn't bot skip it without failing it?

**Comment by DomT4** [comment]
IIRC MMOSR is always a failure to CI, whether or not it should be is another question. I think certain other requirements may be as well, but don't quote me on that, I think about 5% of my brain is working this evening.

**Comment by ilovezfs** [comment]
hmm I seem to recall it always be :green_apple:

**Comment by ilovezfs** [comment]
@DomT4 I wonder if it's min os req I'm thinking of

**Comment by DomT4** [comment]
Yeah, I think so. CI seems to handle that fine, off the top of my head.

**Pull request closed without merging**
