### PR TITLE
molecule: update resource block instructions

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Now that we have some more advanced functionality in `update-python-resources`, I've added some instructions for updating `molecule`'s resources using the new options.

Also bumped some resources (using the method described in the instructions!).

### CODE REVIEW

**Comment by Rylan12** [comment]
```
ERROR: Command errored out with exit status 1: /usr/local/Cellar/molecule/3.2.0/libexec/bin/python /usr/local/Cellar/molecule/3.2.0/libexec/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-iz_bewic/overlay --no-warn-script-location -v --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel 'cffi>=1.1; python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
```

Not sure what to make of this. I thought this was fixed in #65953. Also why only for 11.0? I'll continue to investigate.

**Comment by chenrui333** [comment]
having the same issue in certbot pr, #66055

**Comment by Rylan12** [comment]
Good to know, thanks. I haven't looked into this at all, yet (aside from verifying that it also fails for me locally). I've got a busier day tomorrow so may not be able to look into it until later. Let me know if you find anything.

FYI: `molecule` built without any issues 3 days ago in https://github.com/Homebrew/homebrew-core/pull/65846 so something must have changed since then. I haven't updated the `molecule` formula, so I think it's either and issue with the changing resources or something else in homebrew/core (possibly `python@3.9`)

**Comment by dtrodrigues** [comment]
The PR pulled in by https://github.com/Homebrew/homebrew-core/pull/65953  has been updated to address the couple other places the issue is manifesting: https://github.com/python/cpython/pull/23556 . We'll probably need to do another Python revision bump once the upstream PR is finalized.

@fxcoudert

**Comment by Rylan12** [comment]
@fxcoudert FYI this is still failing albeit with a slightly different error message:

```
    File "/private/tmp/pip-build-env-4hijcw35/overlay/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
      assert len(base_version) == 2
```

It looks (without investigating at all) to be related to another issue with the new macOS version scheme. Will try to investigate more later but I'm not familiar with the code here at all, so figured you may have an idea.

**Comment by Rylan12** [comment]
Okay, now that the `python@3.9` issue is resolved this should be good to go

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
