### PR TITLE
istioctl 1.0.5 (new formula)

### PR DESCRIPTION
**Pull request by murarisumit**
Issue link : https://github.com/istio/istio/issues/10484

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
I think you can set tag to the version variable. That should make it easier to update.

**Comment by murarisumit** [comment]
That tag env variable is required for building the project. https://github.com/istio/istio/wiki/Dev-Guide#setting-up-environment-variables

For version I thought "url" section has that details, do i need to explicit set variable for version ?

**Comment by SMillerDev** [comment]
I meant you could do `env[TAG] = "#{version}"`

**Comment by SMillerDev** [comment]
Looks good to me, if Jenkins is fine with it I'll be too.

**Comment by murarisumit** [comment]
@SMillerDev I think jenkins is stuck somewhere, not able to check status of build. 
Can you please help in it !

**Comment by SMillerDev** [comment]
Yeah, some build is currently taking 4 hours. You'll have to wait in queue I'm afraid.

**Comment by murarisumit** [comment]
Oh, that's fine. I thought something has gone wrong in background.

**Comment by SMillerDev** [comment]
It hadn't 👍(you can check on Jenkins.brew.sh)

**Comment by SMillerDev** [comment]
That'd pull in the entire repo even though you only need what's in the archive though. Not sure what the police is, I thought archives were preferred. @homebrew/core?

**Comment by sjackman** [comment]
I use the archive tarball if the Git repo does not use git submodules, and git clone if it does use git submodules.

**Comment by javian** [comment]
Thanks @murarisumit !

**Comment by SMillerDev** [comment]
Afaik it's not using git here, it's more of a build identifier.

**Comment by murarisumit** [comment]
Okay, so I'll try with git then, this https://github.com/Homebrew/homebrew-core/blob/b825200fd1944c4c66c3173dabb52b33149c49aa/Formula/moz-git-tools.rb can probably help me. 

I need to change url and setttings as @igas suggestion

**Comment by murarisumit** [comment]
I created PR here : https://github.com/Homebrew/homebrew-core/pull/35331#issuecomment-449378535, but it got closed.

**Comment by sjackman** [comment]
> I created PR here : #35331 (comment), but it got closed.

Add an explanation of what your changes do and why you'd like us to include them.

**Comment by SMillerDev** [comment]
>  javian closed this in dd5b244 19 hours ago 

You saw that this pull request was already merged?

**Comment by igas** [comment]
I thought we could do `resource` block for `https://raw.githubusercontent.com/istio/istio/release-1.0/samples/sleep/sleep.yaml` and run `istioctl kube-inject -f sleep.yaml`. Unfortunately, you need to have k8s running or config. There are also `istioctl context-create` but it also needs API URL. I ran out of ideas for now.

More info https://istio.io/docs/setup/kubernetes/sidecar-injection/#manual-sidecar-injection

**Pull request closed without merging**
