### PR TITLE
awscli 2.1.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by miketheman — DISMISSED** [review]

**Comment by chenrui333** [comment]
looks like 11.0 build got stuck, re-kick off the build.

**Comment by chenrui333** [comment]
build failure:

```
   AssertionError
   Building wheel for cffi (setup.py): finished with status 'error'
   ERROR: Failed building wheel for cffi
   Running setup.py clean for cffi
   Running command /usr/local/Cellar/awscli/2.1.6/libexec/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-y85igtn7/cffi/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-y85igtn7/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
   /bin/sh: brew: command not found
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: /usr/local/opt/pkg-config/bin/pkg-config: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: exec: /usr/local/opt/pkg-config/bin/pkg-config: cannot execute: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: /usr/local/opt/pkg-config/bin/pkg-config: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: exec: /usr/local/opt/pkg-config/bin/pkg-config: cannot execute: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: /usr/local/opt/pkg-config/bin/pkg-config: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: exec: /usr/local/opt/pkg-config/bin/pkg-config: cannot execute: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: /usr/local/opt/pkg-config/bin/pkg-config: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: exec: /usr/local/opt/pkg-config/bin/pkg-config: cannot execute: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: /usr/local/opt/pkg-config/bin/pkg-config: No such file or directory
   /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: exec: /usr/local/opt/pkg-config/bin/pkg-config: cannot execute: No such file or directory
   running clean
   removing 'build/temp.macosx-11-x86_64-3.9' (and everything under it)
   removing 'build/lib.macosx-11-x86_64-3.9' (and everything under it)
   removing 'build/bdist.macosx-11-x86_64' (and everything under it)
   'build/scripts-3.9' does not exist -- can't clean it
   removing 'build'
 Successfully built PyInstaller botocore awscli
 Failed to build ruamel.yaml cryptography cffi
 ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
 Exception information:
 Traceback (most recent call last):
   File "/usr/local/Cellar/awscli/2.1.6/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
     status = self.run(options, args)
   File "/usr/local/Cellar/awscli/2.1.6/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
     return func(self, options, args)
   File "/usr/local/Cellar/awscli/2.1.6/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 364, in run
     raise InstallationError(
 pip._internal.exceptions.InstallationError: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
 WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
 You should consider upgrading via the '/usr/local/Cellar/awscli/2.1.6/libexec/bin/python -m pip install --upgrade pip' command.
 Removed build tracker: '/private/tmp/pip-req-tracker-2dmxp2nn'
```

**Comment by miketheman** [comment]
[2.1.7 was released a few hours ago](https://github.com/aws/aws-cli/releases/tag/2.1.7) - I can't seem to find the changelog yet - but maybe worth trying to bump to that version instead?

**Comment by chenrui333** [comment]
yeah, doing that now.

**Pull request closed without merging**
