### PR TITLE
fabio 1.5.10

### PR DESCRIPTION
**Pull request by magiconair**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by magiconair** [comment]
```
==> go install github.com/fabiolb/fabio
$GOPATH/go.mod exists but should not
```

I'll have a look.

**Comment by magiconair** [comment]
There is a bogus module reference in the dependencies which I'll fix in the next release.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@magiconair next release ready yet?

**Comment by magiconair** [comment]
Sorry, got sidetracked. I'll try to fix this today.

**Comment by fxcoudert** [comment]
Removing `go.mod` and `go.sum` feels like a hack really…

**Comment by magiconair** [comment]
@fxcoudert you're right and there is a better way of solving this by disabling go modules inside the GOPATH. Thx

**Comment by magiconair** [comment]
Anything else you need from me?

**Comment by SMillerDev** [comment]
@BrewTestBot Test this please!

**Comment by SMillerDev** [comment]
Thanks @magiconair !

**Pull request closed without merging**
