### PR TITLE
rustup: renamed from rustup-init

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

With #177582, `rustup-init` now provides the full rustup installation (so using the `rustup-init` installer is no longer necessary)

Rename the formula to just `rustup` to reflect these changes (which also hopefully gives users some indication of these changes)

### CODE REVIEW

**Comment by chenrui333** [comment]
maybe split the PR into two one depends_on rustup for test, one depends_on rustup

**Comment by branchvincent** [comment]
What are you thinking? But the audit will fail if this isn't renamed all in one PR:

```console
$ brew audit rustfmt
rustfmt
  * Can't find dependency 'rustup-int'.
Error: 1 problem in 1 formula detected.
```

**Comment by chenrui333** [comment]
aha, that sounds about right. Yeah, the transition for such thing is not easy.

**Comment by chenrui333** [comment]
also, this might need a long build label

**Comment by branchvincent** [comment]
Gonna follow https://github.com/Homebrew/homebrew-core/pull/165649 instead so this can be a syntax-only PR:  add `rustup` as a new formula first, migrate existing dependents to call `rustup` directly instead of `rustup-init`, and then update `formula_renames.json` here

**Review by chenrui333 — APPROVED** [review]

**Comment by AurevoirXavier** [comment]
Shit. This break all my CIs.

```
==> Migrating formula rustup-init to rustup
==> Unlinking rustup-init
==> Moving rustup-init versions to /opt/homebrew/Cellar/rustup
==> Relinking rustup
==> Downloading https://ghcr.io/v2/homebrew/core/create-dmg/manifests/1.2.2
==> Fetching create-dmg
==> Downloading https://ghcr.io/v2/homebrew/core/create-dmg/blobs/sha256:ed92cefd6df282057e6c1a162eb453d4c8d3b34a4a8637bf292813817badef81
==> Pouring create-dmg--1.2.2.all.bottle.tar.gz
🍺  /opt/homebrew/Cellar/create-dmg/1.2.2: 13 files, [70](https://github.com/hack-ink/AiR/actions/runs/10078744161/job/27864368210#step:4:71).6KB
/Users/runner/work/_temp/11525461-2136-42d7-8eca-b1dd4a94ee41.sh: line 4: cargo: command not found
Error: Process completed with exit code 127.
```

**Comment by AurevoirXavier** [comment]
> can you share more about what exactly is breaking for you (i.e. a reproducible example)?

I think there were already some links to this PR. Such as https://github.com/edgedb/edgedb/pull/7590, https://github.com/hack-ink/AiR/commit/3583c95cc6bd8700fe35219701cb83df9a7011f7. Please take a look.

**Pull request merged**
