### PR TITLE
percona-server: specifying plugin directory instead of accepting default

### PR DESCRIPTION
**Pull request by cringdahl**
this fixes issue #16373, and is applied to all three percona-server versions

also removed last two -DCMAKE flags in @5.6, as they are duplicated in the main cmake flags.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
Did you end up filling an upstream report as @ilovezfs suggested?

**Review by ilovezfs — CHANGES_REQUESTED** [review]
The underlying issue needs to be reported upstream. `mysql_config` should not fail simply because the path to it contains a symlink.

**Comment by cringdahl** [comment]
Unfortunately, this isn't an upstream issue. The symlink issue is only a surface issue, triggered because the INSTALL_PLUGINDIR value inside `cmake/install_layout.cmake` defaults to a relative`lib/mysql/plugin', which works with MySQL standalone, albeit one path up. Every other included OS option inside of `cmake/install_layout.cmake` manually sets this INSTALL_PLUGINDIR to `lib/plugin`. Theoretically, a case could be made for asking Percona why they don't detect the Homebrew install as OSX, though I suspect it's because of the custom install method Homebrew uses.

If we allow this default `lib/mysql/plugin` directory to be created, the `mysql_config.pl.in` configurator will be populate the bash script with this plugin directory, which is what causes the issue. 

Apologies if the initial symlink trigger confused anyone. However, due to the specialized environment Homebrew uses, I think passing this up to Percona or MySQL would result in the issue getting kicked back down to Homebrew.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@cringdahl please split this into one commit per formula.

**Comment by ilovezfs** [comment]
@cringdahl ping

**Comment by cringdahl** [comment]
@ilovezfs Sorry, been busy. Commits committed. Thanks.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks again for your first contribution to Homebrew, @cringdahl! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by cringdahl** [comment]
Hi there, and thanks for the approval. I'm not seeing the commits in the new update, and the PR shows closed with unmerged commits. Did I miss something on my end, or did this not get fully merged?

**Pull request closed without merging**
