### PR TITLE
akamai 1.5.0

### PR DESCRIPTION
**Pull request by robertolopezlopez**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by robertolopezlopez** [comment]
Hi,

Before merging, I want to find out how to add a darwin arm64 bottle. We have added this binary to the github release https://github.com/akamai/cli/releases/tag/v1.5.0 , but still it does not show up here. Could you please give me any hint? Thanks

Roberto

**Comment by SMillerDev** [comment]
It needs to succesfully build and test on ARM, which it currently does not:
```
==> /opt/homebrew/Cellar/akamai/1.5.0/bin/akamai install --force purge

[KAttempting to fetch command from https://github.com/akamai/cli-purge.git... [          ] 
[KAttempting to fetch command from https://github.com/akamai/cli-purge.git... ... [OK]

[KInstalling... ... [WARN]

[KDownloading binary... ... [FAIL]
Unable to install selected package
Error: akamai: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /Purge/ to match "unable to locate runtime: go. Please verify if the executable is included in your PATH\nUnable to download binary: invalid response status while fetching command binary: 404
```

**Comment by bayandin** [comment]
It fails because a plugin (`purge`) we're trying to install during the test doesn't support Apple Silicon (btw, there's a PR from a Homebrew member to fix it: https://github.com/akamai/cli-purge/pull/22).
For now, I'm switching the test to use another plugin (`diagnostics`), hope this one works on ARM.

**Comment by robertolopezlopez** [comment]
@SMillerDev @SMillerDev : great, we did not know of such test 😆 

Fantastic work, I did not expect that any of you would know about the akamai cli submodules 👍 We are adding now darwin arm64 support and diagnostics is one of the few submodules which are working on such architecture already.

Please, wait for the merge if still the arm64 bottle is still not present. Thanks!

**Comment by robertolopezlopez** [comment]
> It fails because a plugin (`purge`) we're trying to install during the test doesn't support Apple Silicon (btw, there's a PR from a Homebrew member to fix it: [akamai/cli-purge#22](https://github.com/akamai/cli-purge/pull/22)). For now, I'm switching the test to use another plugin (`diagnostics`), hope this one works on ARM.

Unfortunately, this project depends on another team and they have their own schedule to add arm64 builds.

**Review by SMillerDev — DISMISSED** [review]

**Comment by robertolopezlopez** [comment]
@SMillerDev , @bayandin : can we change the test from `akamai install diagnostics` to `akamai help`? This would be a good enough test, and will not depend on other github repositories.

**Comment by bayandin** [comment]
> @SMillerDev , @bayandin : can we change the test from `akamai install diagnostics` to `akamai help`? This would be a good enough test, and will not depend on other github repositories.

We don't like testing only help or version commands in tests because usually they never fail, and do not reflect real user experience

**Comment by robertolopezlopez** [comment]
> > @SMillerDev , @bayandin : can we change the test from `akamai install diagnostics` to `akamai help`? This would be a good enough test, and will not depend on other github repositories.
> 
> We don't like testing only help or version commands because usually they never fail and do not reflect real user experience

Fair enough.

I can foresee another problem: `cli-diagnostics` (same as `cli-purge`) depends on `go` being installed on the system. Is that something possible to add as requirement for the test container?

**Comment by robertolopezlopez** [comment]
Another option, as it was done in the original test, is adding the `--force` flag to the `akamai install` command

**Comment by bayandin** [comment]
> I can foresee another problem: cli-diagnostics (same as cli-purge) depends on go being installed on the system. Is that something possible to add as requirement for the test container?

Yep, I've added it and builds on ARM have passed.

**Review by bayandin — APPROVED** [review]

**Comment by robertolopezlopez** [comment]
All looks good, but the `no-arm-bottle` is still there. Could you please check that? Thanks :-)

**Comment by bayandin** [comment]
> All looks good, but the `no-arm-bottle` is still there. Could you please check that? Thanks :-)

That's ok, it reflects the current situation (for 1.4.2).

**Comment by robertolopezlopez** [comment]
Thank you @bayandin and @SMillerDev ! Great work!

Looking forward for that merge.

Regards,

Roberto

**Pull request closed without merging**
