### PR TITLE
bartycrouch 4.10.0

### PR DESCRIPTION
**Pull request by FlineDevPublic**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]
Thanks!

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
there are no bottles for the build 🤔

**Comment by Bo98** [comment]
Yes,  Xcode 13.3 isn't on the CI node yet.

**Comment by chenrui333** [comment]
I see, thanks! 😆

**Comment by Jeehut** [comment]
Is it possible to merge this without Xcode 13.3 on the servers? Or do you already have plans to set it up soon?

I don't want to put pressure on anybody, but users are waiting for this release so they can use BartyCrouch with Xcode 13.3. Until the CI has Xcode 13.3 on them, can a non-bottled release be made? I guess the upgrade would take more time to build for users, but at least they could use the latest version, or am I misunderstanding something?

Thank you for your help and sorry for my impatience. 🙏

**Comment by SMillerDev** [comment]
We don't support source builds so non-bottled is out of the question. The Xcode 13.3 update will be distributed to CI soon, unfortunately we're all volunteers here so there's no set timeline.

**Comment by SMillerDev** [comment]
Yeah, merge commits break our CI so you'll have to do it locally either way.

**Comment by Bo98** [comment]
Rebased it for you.

**Comment by Bo98** [comment]
Intel CI build fails because it's building a universal binary. If we can make it not do that it will work.

arm64 build fails to execute:

```
==> /opt/homebrew/Cellar/bartycrouch/4.10.0/bin/bartycrouch update
  dyld[37621]: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
    Referenced from: /opt/homebrew/Cellar/bartycrouch/4.10.0/bin/bartycrouch
    Reason: tried: '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/opt/homebrew/Cellar/bartycrouch/4.10.0/bin/../lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/opt/homebrew/Cellar/bartycrouch/4.10.0/bin/../lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file)
```

I suspect something has changed in SwiftSyntax 5.6 in how this is managed.

**Comment by Jeehut** [comment]
@cho-m Do you think it helps when I revert [the commit](https://github.com/Flinesoft/BartyCrouch/commit/9f5ddaa8b15f0b30c725407ec91b43c6dfcbb895) that creates a universal binary?

**Comment by Bo98** [comment]
> @cho-m Do you think it helps when I revert [the commit](https://github.com/Flinesoft/BartyCrouch/commit/9f5ddaa8b15f0b30c725407ec91b43c6dfcbb895) that creates a universal binary?

Could make it optional by making it in an overridable `ARCHFLAGS` variable.

**Comment by Jeehut** [comment]
> Could make it optional by making it in an overridable ARCHFLAGS variable.

I'm a total Makefile beginner, so I have no idea how I would make an array `ARCHFLAGS` variable and then pass them in something like a for-loop as parameters. So I just separated out a `bartycrouch_universal` make command for the change I had done between version 4.9.0 and 4.10.0 (for a CocoaPods binary issue) and reverted the `bartycrouch` command to what it looked like before. As I think this change requires a new version update, I just posted https://github.com/Homebrew/homebrew-core/pull/97838. This PR can be closed, I think.

**Pull request closed without merging**
