### PR TITLE
libepoxy 1.5.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@ilovezfs the audit warning can be safely ignored. Even though libepoxy is distributed by GNOME nowadays, it does not follow the GNOME versioning scheme. This release has been explicitly marked as [stable](https://github.com/anholt/libepoxy/releases/tag/1.5.0)

**Comment by tschoonj** [comment]
Please hold off merging this one in... problem with the pkg-config script...

**Comment by ilovezfs** [comment]
@tschoonj if you have a chance it would be great to add it to the unstable whitelist in Homebrew/brew.

**Comment by tschoonj** [comment]
What file is that exactly in brew?

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L542-L594

**Pull request closed without merging**
