### PR TITLE
ios-deploy 1.12.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Not the latest release? Looks like it's just an upstream oversight though. Probably worth filing an issue.

**Review by chenrui333 — DISMISSED** [review]

**Comment by gabebear** [comment]
We would normally release with the command `brew bump-formula-pr --url="https://github.com/ios-control/ios-deploy/archive/1.12.2.tar.gz" ios-deploy`. It's possible we should kill this PR and create a new one with that command.

This isn't my PR(I found it when trying to create one). I had started creating this release and then had to pause it because of not being able to also push the npm release. Once I cleared the npm issue I found this PR had already been created.

**Comment by carlocab** [comment]
@gabebear feel free to create another PR. Thanks!

**Comment by chenrui333** [comment]
#128901

**Pull request closed without merging**
