### PR TITLE
gradle: set JAVA_HOME in wrapper

### PR DESCRIPTION
**Pull request by forevergenin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Added wrapper generation code for gradle

### CODE REVIEW

**Comment by DomT4** [comment]
@jasontedor @MikeMcQuaid Is this okay or did we decide to not env script Gradle at all after the discussion a few days back?

**Comment by jasontedor** [comment]
At least this respects the user `JAVA_HOME` if it's already set, but this is still unnecessary since the [`gradle` script already tries to detect Java](https://github.com/gradle/gradle/blob/65b309141421f4aaeae35d7eab830bee9ea4b790/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt#L70-L89):

```
08:21:19 ⏚ [jason:~] $ unset JAVA_HOME
08:21:21 ⏚ [jason:~] $ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+120)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+120, mixed mode)
08:21:23 ⏚ [jason:~] $ gradle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-ea (Oracle Corporation 9-ea+120)
OS:           Mac OS X 10.11.5 x86_64

08:21:26 ⏚ [jason:~] $ 
```

**Comment by MikeMcQuaid** [comment]
No-one has really explained what `GRADLE_HOME` is and when it does/does not need to be set. That'll be a requirement before we can consider merging this.

**Comment by jasontedor** [comment]
@MikeMcQuaid In my [comment](https://github.com/Homebrew/homebrew-core/pull/1543#discussion_r65474941) on #1543 and my [comment](https://github.com/Homebrew/homebrew-core/issues/889#issuecomment-223178532) on #889, I gave explanations that `GRADLE_HOME` does nothing. I've also explained [here](https://github.com/Homebrew/homebrew-core/pull/1708#issuecomment-223752781) and there that setting `JAVA_HOME` in a wrapper script is completely unnecessary.

**Comment by MikeMcQuaid** [comment]
@jasontedor Sorry, to be clear, your previous comments were great and I should have said: we'll need to hear why/when `GRADLE_HOME` or `JAVA_HOME` are required to be set by end-users before we can merge anything like this.

**Comment by forevergenin** [comment]
This is again related to `jenv` and #1706 . If have a specific version of `java` configured with `jenv` (say `1.6`), `gradle` also tries using the same version instead of the latest `java` version available. If I want `gradle` to use the latest `java` version installed I need to set `JAVA_HOME` manually in the environment.

This change sets `JAVA_HOME` if `JAVA_HOME` is not set to the latest version of `java` available in the system by default. If required we can manually override the `java` version via setting  a new `JAVA_HOME`

**Comment by MikeMcQuaid** [comment]
@forevergenin Ok that explains `JAVA_HOME` but why does `GRADLE_HOME` need set? @jasontedor does the `JAVA_HOME` thing sound reasonable to you?

**Comment by jasontedor** [comment]
> If have a specific version of java configured with `jenv` (say `1.6`), `gradle` also tries using the same version instead of the latest `java` version available.

@forevergenin That is the point of `jenv`; you're intentionally working around what it is designed to do. With the *current* `gradle` formula, and then switching to your formula (in a fresh El Capitan VM because I do not run `jenv` and prefer to not run `jenv`):

```
os-x-el-capitan:~ jason$ mkdir jdk8
os-x-el-capitan:~ jason$ cd jdk8
os-x-el-capitan:jdk8 jason$ jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/
oracle64-1.8.0.92 added
1.8.0.92 added
1.8 added
os-x-el-capitan:jdk8 jason$ jenv add /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/
oracle64-9-ea added
9-ea added
There is already a 9-ea JDK managed by jenv
Do you want to override (type y to confirm)? y
9-ea added
os-x-el-capitan:jdk8 jason$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+121)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+121, mixed mode)
os-x-el-capitan:jdk8 jason$ jenv local oracle64-1.8.0.92
os-x-el-capitan:jdk8 jason$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
os-x-el-capitan:jdk8 jason$ ls -al /usr/local/bin/gradle 
lrwxr-xr-x  1 jason  admin  32 Jun  4 15:29 /usr/local/bin/gradle -> ../Cellar/gradle/2.13/bin/gradle
os-x-el-capitan:jdk8 jason$ gradle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.11.5 x86_64

os-x-el-capitan:jdk8 jason$ cd /usr/local/Library/Taps/homebrew/homebrew-core/
os-x-el-capitan:homebrew-core jason$ git checkout formula/gradle
Switched to branch 'formula/gradle'
Your branch is up-to-date with 'forevergenin/formula/gradle'.
os-x-el-capitan:homebrew-core jason$ brew remove gradle
Uninstalling /usr/local/Cellar/gradle/2.13... (168 files, 49.7M)
os-x-el-capitan:homebrew-core jason$ brew install gradle
==> Downloading https://downloads.gradle.org/distributions/gradle-2.13-bin.zip
Already downloaded: /Users/jason/Library/Caches/Homebrew/gradle-2.13.zip
🍺 /usr/local/Cellar/gradle/2.13: 180 files, 50.9M, built in 2 seconds
os-x-el-capitan:homebrew-core jason$ cd ~/jdk8/
os-x-el-capitan:jdk8 jason$ gradle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-ea (Oracle Corporation 9-ea+121)
OS:           Mac OS X 10.11.5 x86_64

os-x-el-capitan:jdk8 jason$ 
```

This is basically the same problem as the previous change to this formula to set `JAVA_HOME` in a wrapper script: the previous wrapper script would violate `JAVA_HOME` if it is set, this wrapper script will violate a `jenv` environment.

> If I want `gradle` to use the latest `java` version installed I need to set `JAVA_HOME` manually in the environment.

Yes, and this works just fine as long as you do not have the `jenv` plugin for `gradle` activated. Continuing from above and switching back to the current `gradle` formula:

```bash
os-x-el-capitan:jdk8 jason$ cd /usr/local/Library/Taps/homebrew/homebrew-core/
os-x-el-capitan:homebrew-core jason$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
os-x-el-capitan:homebrew-core jason$ brew remove gradle
Uninstalling /usr/local/Cellar/gradle/2.13... (180 files, 50.9M)
os-x-el-capitan:homebrew-core jason$ brew install gradle
==> Downloading https://downloads.gradle.org/distributions/gradle-2.13-bin.zip
Already downloaded: /Users/jason/Library/Caches/Homebrew/gradle-2.13.zip
ð  /usr/local/Cellar/gradle/2.13: 168 files, 49.7M, built in 2 seconds
os-x-el-capitan:homebrew-core jason$ cd ~/jdk8/
os-x-el-capitan:jdk8 jason$ export JAVA_HOME=`/usr/libexec/java_home -v 9`
os-x-el-capitan:jdk8 jason$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
os-x-el-capitan:jdk8 jason$ ls -al ~/.jenv/plugins/
total 0
drwxr-xr-x   2 jason  staff   68 Jun  4 18:38 .
drwxr-xr-x  10 jason  staff  340 Jun  4 18:34 ..
os-x-el-capitan:jdk8 jason$ gradle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-ea (Oracle Corporation 9-ea+121)
OS:           Mac OS X 10.11.5 x86_64

os-x-el-capitan:jdk8 jason$ jenv enable-plugin gradle
gradle plugin activated
os-x-el-capitan:jdk8 jason$ gradle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.11.5 x86_64

os-x-el-capitan:jdk8 jason$ 
```

> If required we can manually override the `java` version via setting a new `JAVA_HOME`.

Since *you're* intentionally working around the point of `jenv`, that's what I think *you* should do. Or set `JAVA_HOME` on each invocation or set an alias. Continuing as above, after disabling the `jenv` plugin for `gradle`:

```bash
os-x-el-capitan:jdk8 jason$ JAVA_HOME=`/usr/libexec/java_home -v 9` gradle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-ea (Oracle Corporation 9-ea+121)
OS:           Mac OS X 10.11.5 x86_64

os-x-el-capitan:jdk8 jason$ alias ladle='JAVA_HOME=`/usr/libexec/java_home -v 9` gradle'
os-x-el-capitan:jdk8 jason$ ladle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-ea (Oracle Corporation 9-ea+121)
OS:           Mac OS X 10.11.5 x86_64

os-x-el-capitan:jdk8 jason$ 
```

**Comment by jasontedor** [comment]
> @jasontedor does the `JAVA_HOME` thing sound reasonable to you?

@MikeMcQuaid It does not, because it violates the point of `jenv`.

**Comment by forevergenin** [comment]
@MikeMcQuaid I didn't add a `GRADLE_HOME`.

**Comment by forevergenin** [comment]
@jasontedor for my use case an alias would do. Thanks !

**Pull request closed without merging**
