### PR TITLE
kube-aws 0.16.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
`GOPATH` deprecation could be performed here as well :)

**Comment by SMillerDev** [comment]
Can we have a GOPATH audit?

**Comment by chenrui333** [comment]
> Can we have a GOPATH audit?

We still have lots of formulae have to be built with GOPATH per my last check.

**Comment by dawidd6** [comment]
Yep, not every project moved to Go Modules and I suspect it won't happen anytime soon for some of them.

**Review by dawidd6 — DISMISSED** [review]

**Comment by chenrui333** [comment]
rebase for the license change.

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
