### PR TITLE
openrct2 0.3.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

redo PR #59754

### CODE REVIEW

**Comment by chenrui333** [comment]
license header ref (`distribution/openrct2.d.ts`):

```
/*****************************************************************************
 * Copyright (c) 2014-2020 OpenRCT2 developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is licensed under the GNU General Public License version 3.
 *****************************************************************************/
```

**Comment by SMillerDev** [comment]
Any way to improve the test?

**Comment by jonchang** [comment]
Might be tough, since it's a game.

**Comment by chenrui333** [comment]
yeah, it would be tough, like many GUI applications.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
