### PR TITLE
ollama 0.1.25

### PR DESCRIPTION
**Pull request by dcchambers**
Created with `brew bump-formula-pr`. I was having some issues with my git remote causing a timeout and causing the script to fail, so I manually git pushed and opened this PR. The file change itself was doing using `bump-formula-pr`

### CODE REVIEW

**Comment by chenrui333** [comment]
@dcchambers just curious, what was the error?

**Comment by dcchambers** [comment]
> @dcchambers just curious, what was the error?

Ahh sorry, already closed that terminal and didn't copy the exact error, but it was taking quite a long time and finally gave me a `fatal: The remote end hung up unexpectedly` error of some kind.

**Comment by chenrui333** [comment]
you might want to try the `brew update` before using `brew bump ---open-pr ollama` command next time.

**Comment by chenrui333** [comment]
Any way, thanks for your first contribution to homebrew-core! 🎉

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
