### PR TITLE
opendht 2.3.3 (new formula)

### PR DESCRIPTION
**Pull request by ghenry**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ghenry** [comment]
Thanks. Raised it upstream, but their CI is passing so have asked them to
compare.

**Comment by cho-m** [comment]
Looks like GCC-5 needs to manually enable C++11 standard support to get `atomic`:
```
In file included from /home/linuxbrew/.linuxbrew/Cellar/gcc@5/5.5.0_7/include/c++/5.5.0/atomic:38:0,
                 from /tmp/opendht-20220227-30685-1x4bozf/opendht-2.3.3/CMakeFiles/CMakeTmp/src.cxx:2:
/home/linuxbrew/.linuxbrew/Cellar/gcc@5/5.5.0_7/include/c++/5.5.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
```

One thing to try is force this on Linux via:
```
ENV.cxx11 if OS.linux?
```

This should at least get past the current error. It may still fail since I am guessing the upstream is using a newer compiler than GCC-5, so behavior is different.

If, after all attempts at fixing, there is a hard blocker in GCC-5, then will need to disable it like `fails_with gcc: "5"` and add a `depends_on "gcc"` for Linux https://docs.brew.sh/Formula-Cookbook#compiler-selection

**Comment by cho-m** [comment]
The Linux build is done on Ubuntu 16.04 with GCC-5 and Glibc 2.23, which I believe provides high compatibility with a number of Linux distros.

The next step for Homebrew's Linux packaging is to move to Ubuntu 18.04 with GCC-7; however, this will require various changes from CI Linux docker container to Homebrew infrastructure modifications to support the migration and allow seamless functionality.

Using a Homebrew `gcc` formula as a dependency comes with demerit of extra overhead in space/installation-time and the issue that the bottle (pre-built package) is not relocatable so a Linux user who doesn't use default `/home/linuxbrew/.linuxbrew` prefix will need to compile GCC from source.

---

What this means for now is that Homebrew Linux builds will continue to use GCC-5 as preference, while incompatible formulae will use GCC-11.

**Comment by ghenry** [comment]
Thanks for the detail @cho-m I'll ask upstream again.

**Comment by aberaud** [comment]
Hi, I updated checkAtomics and it should now use the c++11 flag. So let's try with OpenDHT 2.3.4.

**Comment by ghenry** [comment]
Thanks. I'll do a fresh PR when 2.3.4 is out.

**Pull request closed without merging**
