### PR TITLE
cvs: revision for ARM

### PR DESCRIPTION
**Pull request by fxcoudert**
Trying to bottle on ARM

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
checking build system type... configure: error: /bin/sh build-aux/config.sub -apple-darwin20.2.0 failed
```

**Comment by fxcoudert** [comment]
```
Can't exec "autopoint": No such file or directory at /opt/homebrew/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345
```

**Comment by nickzman** [comment]
Did this work for you? I tried these changes, and `configure` didn't work for me, because the configure script doesn't recognize `aarch64`. If I change that to "arm", it appears to work.

**Comment by carlocab** [comment]
Bottled in 95a13d13548e3936ed336c33f8b52580062f0c7c.

**Pull request closed without merging**
