### PR TITLE
i2pd 2.48.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — APPROVED** [review]

**Comment by chenrui333** [comment]
relates to #128510

**Review by p-linnane — APPROVED** [review]

**Comment by carlocab** [comment]
Needs rebase. Uploaded bottle also probably needs deletion as a consequence.

**Comment by p-linnane** [comment]
I've rebased this, dropping the bottle commit, and requested an org owner remove the existing bottles.

**Review by carlocab — APPROVED** [review]
Bottle deleted.

**Pull request merged**
