### PR TITLE
yarn 1.5.0

### PR DESCRIPTION
**Pull request by jure**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jure** [comment]
This is a new release of yarn, released ~30 minutes ago, and is not a pre-release: https://github.com/yarnpkg/yarn/releases

**Comment by ilovezfs** [comment]
https://yarnpkg.com/en/ still show 1.3.2. Thanks, though

**Comment by jure** [comment]
🤷‍♂️  I'll keep an eye on that bit updating. There's probably a site rebuild CD/CI that still needs to complete somewhere.

**Comment by ilovezfs** [comment]
@jure fyi upstream sends automated PRs for this: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3Adanbuild+is%3Aclosed

**Comment by jure** [comment]
Thanks! Should've waited a bit I guess, but I was too impatient (npm package hasn't been published and homebrew formula hasn't been updated, so installing the new version isn't that straightforward).

**Pull request closed without merging**
