### PR TITLE
conjure-up: update resources based on current 'requirements.txt'

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
update `conjure-up`'s resources based on the  current release's 'requirements.txt' file

### CODE REVIEW

**Comment by DomT4** [comment]
Aren't some of the existing resources which you've removed dependencies though? If I install this in a `virtualenv` I get this list:

```
aiofiles (0.3.1)
awscli (1.11.123)
botocore (1.5.86)
bundle-placement (0.0.1)
colorama (0.3.7)
contextlib2 (0.5.5)
docutils (0.14)
env (1.0.0)
Jinja2 (2.9.6)
jmespath (0.9.3)
juju (0.6.0)
juju-wait (2.6.2)
jujubundlelib (0.5.4)
MarkupSafe (1.0)
oauthlib (2.0.2)
pip (9.0.1)
prettytable (0.7.2)
progressbar2 (3.20.0)
psutil (5.2.2)
pyasn1 (0.3.2)
python-dateutil (2.6.1)
python-utils (2.2.0)
pyvmomi (6.5.0.2017.5.post1)
PyYAML (3.12)
raven (6.1.0)
redis (2.10.5)
requests (2.14.2)
requests-oauthlib (0.8.0)
rsa (3.4.2)
s3transfer (0.1.10)
setuptools (36.2.7)
sh (1.12.13)
six (1.10.0)
termcolor (1.1.0)
theblues (0.3.8)
ubuntui (0.1.7)
urwid (1.3.1)
websockets (3.4)
wheel (0.29.0)
ws4py (0.3.4)
```

**Comment by JCount** [comment]
@DomT4 I thought it was odd, so I double-checked installing everything in the same `python3` `virtualenv`. I tried testing it as best I could, but not being a user of the software that's not worth much. Are you perhaps using a different list of requirements? The list I am referring to is [conjure-up/conjure-up/blob/2.2.2/requirements.txt](https://github.com/conjure-up/conjure-up/blob/2.2.2/requirements.txt). I am probably just overlooking something really obvious.

**Comment by JCount** [comment]
I think I found the missing piece. https://github.com/conjure-up/spells/tree/2.2.0

**Comment by DomT4** [comment]
I did use the `master` branch which might have thrown the results off a bit but, based on the existing formula I'm not sure how much. My process was:

```
~> curl -LvO https://raw.githubusercontent.com/conjure-up/conjure-up/master/requirements.txt
~> mkdir venv && cd venv
~> virtualenv .
~> bin/pip3 install -r /tmp/requirements.txt
```

**Comment by JCount** [comment]
```
aiofiles==0.3.1
bundle-placement==0.0.1
contextlib2==0.5.5
env==1.0.0
Jinja2==2.9.6
juju==0.5.3
juju-wait==2.5.1
jujubundlelib==0.5.4
MarkupSafe==1.0
oauthlib==2.0.2
prettytable==0.7.2
progressbar2==3.20.0
psutil==5.2.2
python-dateutil==2.6.1
python-utils==2.2.0
PyYAML==3.12
raven==6.1.0
redis==2.10.5
requests==2.14.2
requests-oauthlib==0.8.0
sh==1.12.13
six==1.10.0
termcolor==1.1.0
theblues==0.3.8
ubuntui==0.1.6
urwid==1.3.1
websockets==3.4
ws4py==0.3.4
```
is the list I get running
```
virtualenv3 --clear pypi3/
cd pypi3/ && source bin/activate
curl -vLO https://raw.githubusercontent.com/conjure-up/conjure-up/2.2.2/requirements.txt
pip install -vr requirements.txt
pip freeze
```

**Comment by DomT4** [comment]
Ah, yup, I get your list with the branch-specific `requirements.txt` 👍. I guess however this does move the question onto whether to remove the `head` spec or whether to move the current head-only requirements into a `head do` block.

**Comment by JCount** [comment]
Given the current degree of divergence and the reality that the requirements for `HEAD` are, and will continue to be, in a constant state of flux, it is impractical to try and maintain a `HEAD` spec with how inflexible resource blocks are.

**Comment by DomT4** [comment]
No disagreement from me.

**Pull request closed without merging**
