### PR TITLE
Update revision of apr

### PR DESCRIPTION
**Pull request by frdmn**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Bump revision to apply location change (`/usr/local/Library/` -> `/usr/local/Homebrew/Library/`)

### CODE REVIEW

**Comment by ilovezfs** [comment]
:+1:

**Comment by DomT4** [comment]
Can you go into more detail here? I'm a little confused. What changed in the 15 days since this was last revision bumped?

**Comment by ilovezfs** [comment]
@DomT4 the location of the shims moved ... so we now have a problem because it's getting hard-coded in and the path could be the old one or the new one :(

```
/usr/local/opt/apr/libexec/build-1/libtool: line 959: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
```

original user log: http://paste.frd.mn/lipot

**Comment by ilovezfs** [comment]
CC @MikeMcQuaid so the repository move from /usr/local into /usr/local/Homebrew apparently has broken any of the bottles that have hard coded paths to the shims for new installations, and then the bottles are broken for the old installations following a revision bump.

**Comment by MikeMcQuaid** [comment]
@ilovezfs I think we should avoid assuming bottles have a particular `HOMEBREW_REPOSITORY`. Temporarily we can fix this an `inreplace` in a `post_install` and add a check for the `HOMEBREW_REPOSITORY` location after we migrate the bots.

**Comment by ilovezfs** [comment]
I guess any hard references into the HOMEBREW_REPOSITORY should be an audit failure...

**Comment by MikeMcQuaid** [comment]
@ilovezfs Or at least avoid a `cellar :any`. When the HOMENBREW_REPOSITORY is `/usr/local` this is hard. When it's `/usr/local/Homebrew` this is easy 😁.

**Comment by ilovezfs** [comment]
Maybe just a symlink /usr/local/Homebrew -> /usr/local on non-migrated installations would be a temporary workaround? Then bumping the revision should make it work on old and new, I think.

**Comment by DomT4** [comment]
I think there's a better workaround for `apr` here, at least. Give me a little bit to poke at it. Are we aware of anything else this is impacting yet?

**Comment by ilovezfs** [comment]
likely anything that broke the last time the shims moved!

**Comment by DomT4** [comment]
Same fix we applied to `libtool` last time works on `apr` just fine as well. PR @ https://github.com/Homebrew/homebrew-core/pull/4779.

**Comment by ilovezfs** [comment]
don't know if anything actually relies on this but just grepp'ing a random install I created a few hours ago that has 49 formulae
```
./hdf5/1.8.17/share/hdf5/libhdf5.settings:                     C Compiler: /usr/local/Library/Homebrew/shims/super/clang ( Apple LLVM version 7.3.0 )
./hdf5/1.8.17/share/hdf5/libhdf5.settings:                   C++ Compiler: /usr/local/Library/Homebrew/shims/super/clang++ ( Apple LLVM version 7.3.0 )
```

**Comment by ilovezfs** [comment]
perl
```
./perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/Config_heavy.pl:full_sed='/usr/local/Library/Homebrew/shims/super/sed'
./perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE/config.h:#define LOC_SED 	"/usr/local/Library/Homebrew/shims/super/sed"	/**/
```

**Comment by ilovezfs** [comment]
python3
```
./python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_sysconfigdata.py:                "'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.8'",
./python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m/Makefile:CONFIG_ARGS=	 '--prefix=/usr/local/Cellar/python3/3.5.2_1' '--enable-ipv6' '--datarootdir=/usr/local/Cellar/python3/3.5.2_1/share' '--datadir=/usr/local/Cellar/python3/3.5.2_1/share' '--enable-framework=/usr/local/Cellar/python3/3.5.2_1/Frameworks' '--without-ensurepip' '--without-gcc' 'MACOSX_DEPLOYMENT_TARGET=10.8' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.8'
```

**Comment by ilovezfs** [comment]
pkg-config
```
Josephs-MacBook-Pro:Cellar joe$ strings ./pkg-config/0.29.1/bin/pkg-config|grep Library|grep local
/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.8
```

**Comment by DomT4** [comment]
The `pkg-config` one is intentional. The others, less so.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-core/commit/ca6d089d10de35da5d18ce5894187b805ae5eb5e. Some idiot (_me_) forgot to include the `Closes` bit in the actual commit message 🙈.

**Comment by DomT4** [comment]
@ilovezfs If you want to open a tracking issue about trying to eliminate some of those, feel free. Certainly hardcoded references to our `sed` shim at the very least isn't desirable.

**Comment by ilovezfs** [comment]
open-mpi
```
iMac-TMP:bin joe$ strings orte-info|grep Library
/usr/local/Library/Homebrew/shims/super/clang
iMac-TMP:bin joe$ strings ompi_info|grep Library
/usr/local/Library/Homebrew/shims/super/clang
/usr/local/Library/Homebrew/shims/super/clang++
```

netcdf
```
./netcdf/4.3.3.1_4/lib/libnetcdf.settings:C Compiler:		/usr/local/Library/Homebrew/shims/super/clang
```

:see_no_evil:

**Pull request closed without merging**
