### PR TITLE
gnu-chess 6.2.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
clang++  -g -O2    -o gnuchess main.o components.o  frontend/libfrontend.a adapter/libadapter.a engine/libengine.a -lreadline -lncurses 
make[4]: Nothing to be done for `install-data-am'.
 .././install-sh -c -d '/usr/local/Cellar/gnu-chess/6.2.6/bin'
 .././install-sh -c -d '/usr/local/Cellar/gnu-chess/6.2.6/bin'
/bin/sh: .././install-sh: Permission denied
make[4]: *** [install-binPROGRAMS] Error 1
/bin/sh: .././install-sh: Permission denied
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [install-binSCRIPTS] Error 1
make[3]: *** [install-am] Error 2
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

**Comment by Bo98** [comment]
Looks like they shipped `install-sh` with incorrect permissions.

6.2.5: `-rwxr-xr-x`
6.2.6: `-rw-r--r--`

**Comment by chenrui333** [comment]
Fixed the permission denied issue and verified in my local.

**Comment by Bo98** [comment]
Ah nice Ruby way to do it is `chmod "+x", "install-sh"` rather than `system`. though it doesn't matter much.

**Pull request closed without merging**
