### PR TITLE
mitmproxy: Pillow wants zlib

### LINKED ISSUE #77: mitmproxy failed to build on 10.11.3 with with-cssutils option
brew install mitmproxy --with-cssutils

fails with ValueError: --enable-zlib requested but zlib not found, aborting.

Gist logs: https://gist.github.com/e57b8e2d294ada09e744b105ae4d9cf5

Installing without the cssutils option works.

### PR DESCRIPTION
**Pull request by ilovezfs**
Closes #77.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Test is failing and this looks like it should warrant an upstream patch?

**Comment by ilovezfs** [comment]
@mikemcquaid Yeah this isn't going to work. @tdsmith said this is actually a distutils bug but we're kind of stuck when dealing with system python. This is how it was fixed in homebrew/python https://github.com/Homebrew/homebrew-python/pull/295/commits/bd1df7e96d53dbdf4fd92e6ebb953e17919a9abc

I guess we may be able to do something like that here.

**Comment by ilovezfs** [comment]
@mikemcquaid @tdsmith PR refreshed.

**Comment by tdsmith** [comment]
the relevant python patch, just for reference: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L64-L70

**Comment by tdsmith** [comment]
i think you can :shipit:, in any case

**Pull request closed without merging**
