### PR TITLE
ansible@2.9 2.9.25

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
- May consider dropping unmaintained `pycrypto` and `python-keyczar`. I did this for main `ansible` formula back in #80365.
- `textfsm` can probably be switched to PyPI source like main `ansible` formula. This and previous are the non-PyPI resources, so modifying them enables standard bump logic to work.
- `six` can be switched to formula

**Comment by chenrui333** [comment]
I thought I did for `six` 🤦 

I will followup the others.

**Comment by chenrui333** [comment]
They default to `pycrypto`, but I think we can replace with the `cryptography`, did not see any issue.

https://github.com/ansible/ansible/blob/7db0dbee5109e56f2d652bfd0aa76c2e546ad0c4/setup.py#L205-L236

**Comment by cho-m** [comment]
Can probably ignore error and re-run CI.

The Python build uses `setuptools-scm`, which I think had an upstream issue. The version used in CI was yanked: https://pypi.org/project/setuptools-scm/#history and a new 6.3.1 release was done.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
