### PR TITLE
jpeg 9b

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @DomT4

### CODE REVIEW

**Comment by ilovezfs** [comment]
- [ ]   **devil (needs 41fcabbe and 4a2d7822)
- [ ]   **flactag (needs https://gist.github.com/ilovezfs/d296a8a612d9411169033fcaadc718ac)
- [ ]   **libgeotiff (seems to need --with-jpeg now) 
- [ ]   **libbpg--segfaults but that's not new
- [ ]   **mame (https://github.com/mamedev/mame/blob/master/src/emu/rendutil.cpp#L580)  **mapnik@2 (needs https://github.com/mapnik/mapnik/commit/860631acc5605a1ab6bdec59850dd233cbfe1a4f)
- [ ]   **onscripter
- [ ]   **open-scene-graph
- [ ]   **ufraw--needs patch TRUE -> (boolean)TRUE
- [ ]   volatility--cannot be in the same PR as openjpeg, needs pillow fix
- [ ]   --libspectre--not linked
- [ ]   --librsvg--not linked
- [ ]   --openjpeg--not linked
- [ ]   --gource--not linked
- [ ]   --jhead--not linked
- [ ]   --jpegrescan--not linked
- [ ]   --libgxps--not linked (has bug: build.without? libjpeg -> jpeg)
- [ ]   --logstalgia--not linked
- [ ]   --mal4s--not linked
- [ ]   --gtkglext--not linked

**Comment by DomT4** [comment]
Would perhaps suggest we merge something fixing `wxmac` prior to this being merged or everyone running High Sierra is about to have a truly painful day, but otherwise getting this done finally is a huge 👍.

I'm happy to keep working on getting upstream to do something about the stable/devel branches of `wxmac` but perhaps it's worth accepting that PR as-is & I'll keep updating the status for as long as I keep getting replies from upstream.

**Comment by ilovezfs** [comment]
:-1: to any wxmac patching.

**Comment by DomT4** [comment]
It's literally just the one `CPPFLAG` at this point. No patching of the source itself.

**Comment by ilovezfs** [comment]
Then they can cut a release no problem.

**Comment by DomT4** [comment]
I'm more or less 100% sure we ain't going to get them to cut a release prior to High Sierra's release, or even immediately after it based on their existing comment. I can ask again but 😅. It doesn't feel like the one flag is hideous for Homebrew to carry around.

It just feels a bit garbage for us to intentionally break `wxmac` for what is probably at this point at least hundreds of users when the fix is that simple for us. We have certainly carried worse for pre-release versions of macOS.

**Comment by ilovezfs** [comment]
Not really interested in arguing about it.

**Comment by DomT4** [comment]
Not arguing. Just saying if we're prepared to patch every `printf` invocation in the world it seems silly _this_ is the hill you choose to die on, but 🤷‍♂️.

**Comment by ilovezfs** [comment]
Let's keep this PR focused on jpeg. Thanks.

**Comment by DomT4** [comment]
You were the one who tagged me into it 😄. It's your PR, do as you wish.

**Comment by mistydemeo** [comment]
Flactag, mame, onscripter and ufraw look good to me.

**Comment by ilovezfs** [comment]
@mistydemeo thanks for looking those over! :bowing_man:

**Comment by MikeLund** [comment]
@ilovezfs Not sure if this pull is the cause, but seems like it maybe broke Homebrew's PHP?

```
~$ php -v
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Abort trap: 6
```

**Comment by ilovezfs** [comment]
@MikeLund yup. Everything linked to jpeg needs to be revision bumped, which includes PHP.

**Comment by ilovezfs** [comment]
@MikeLund as a workaround, you can use `brew reinstall --build-from-source` for the relevant formulae.

**Comment by byCedric** [comment]
@ilovezfs Thanks for the workaround, do we need to create an issue on the homebrew php repo for this? What exactly needs to be done for this to play nice again?

**Comment by ilovezfs** [comment]
@byCedric yes PHP tap needs an issue like this one: https://github.com/Homebrew/homebrew-science/issues/6075

In most cases it will just be a matter of either adding `revision 1` or bumping `revision 1` to `revision 2`, etc. and then rebuilding the bottle.

In some cases, a patch may be needed for JPEG 9 compatibility, which is usually a matter of changing a `true` to a `TRUE` or casting something to `boolean` depending on the situation.

The bumps of all formulae for a given version of PHP should occur in a single PR.

**Pull request closed without merging**
