### PR TITLE
nyx: migrate to python@3.8

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Superseded by #54214

**Comment by Bo98** [comment]
Oops, I didn't intend to overlap work here.

**Comment by iMichka** [comment]
It's ok. I have seen that you made way better cleanups than mine :)

**Comment by Bo98** [comment]
I went around trying to see which of the remaining ones could use a virtualenv as it's way cleaner and easier to migrate. I think I've exhausted that option now.

**Pull request closed without merging**
