### PR TITLE
various: revision bump for python update

### PR DESCRIPTION
**Pull request by rakkesh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by rakkesh** [comment]
Fixes https://github.com/Homebrew/homebrew-core/issues/2506 (vim) and other packages.

**Comment by DomT4** [comment]
Do _all_ of these actually link the direct framework path? As far as I'm led to believe from prior conversations with Tim direct framework linking is "incorrect" behaviour on OS X. CC @tdsmith.

**Comment by rakkesh** [comment]
I did not check this previously; apologies for the oversight. None of the formulae installations except for `vim` link to `Python Framework` path. Now that `vim` has a new version, this PR can be closed.

**Comment by DomT4** [comment]
No worries, appreciate the enthusiasm to fix things!

**Comment by tdsmith** [comment]
wrt linking the Framework: It's correct for things which embed a Python interpreter; it's incorrect for extension modules.

**Pull request closed without merging**
