### PR TITLE
path-extractor: disable due to no license

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See also: #47627

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
It isn't syntax only though

**Comment by Bo98** [comment]
We don't need to build new bottles so we don't need to run tests on all the OS versions (in fact, homebrew-test-bot will block it).

**Comment by SMillerDev** [comment]
If something depends on it, that would break now. In addition to that, it's also semantically incorrect (you're not making a style change). The label name is specific for this reason.

**Comment by Bo98** [comment]
> If something depends on it, that would break now

homebrew-test-bot does not test dependents of disabled formula - it skips it entirely. Sounds like a reasonable addition to do though.

**Pull request merged**
