### PR TITLE
shadowsocks-libev: fix udns is not required now

### PR DESCRIPTION
**Pull request by icpz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lcdtyph** [comment]
@ilovezfs 
Sorry but how can I fix this...
```
08:00:48 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by lcdtyph** [comment]
@ilovezfs 
Thanks !

**Comment by ilovezfs** [comment]
Shipped! Thanks, @lcdtyph.

**Pull request closed without merging**
