### PR TITLE
percona-server 5.7.17-11

### PR DESCRIPTION
**Pull request by zmoazeni**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by zmoazeni** [comment]
I didn't realize `brew bump-formula-pr` would immediately submit the PR. Oops.

This isn't ready yet. 5.7.17 changed some security settings when calling mysqld_safe from an absolute path. This installs just fine, but it doesn't start up properly.

**Comment by zmoazeni** [comment]
I'm sorry. I was wrong. This is fine.

I did something dumb locally and didn't realize that was what really was at fault.

This formula is good to go now.

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
