### PR TITLE
gatsby-cli 2.10.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
21:19:06 ==> brew test gatsby-cli --verbose
21:19:11 ==> FAILED
21:19:11 Testing gatsby-cli
21:19:11 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200311-55022-gidtck.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gatsby-cli.rb --verbose
21:19:11 ==> /usr/local/Cellar/gatsby-cli/2.10.5/bin/gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
21:19:11 error UNHANDLED EXCEPTION initStarter is not a function
```

**Comment by Bo98** [comment]
There's a 2.10.7 now. Have you tried that?

**Comment by chenrui333** [comment]
> There's a 2.10.7 now. Have you tried that?

trying it now.

**Comment by chenrui333** [comment]
Yeah, the issue got fixed in the latest version.

**Pull request closed without merging**
