### PR TITLE
kpt 0.4.0 (new formula)

### PR DESCRIPTION
**Pull request by tfhartmann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Hello, I'm proposing this formula addition to brew for `kpt` (kept)  Kept is a new project that was recently released.  It is described from the docs page as: 
>  `kpt is a toolkit to help you manage, examine, manipulate, customize, validate, and apply Kubernetes resource configuration files, both manually and programmatically.` .

 Although this is a recently published project, and as such I do get this errer when running `brew audit` it is my expectation that this project will shortly meet the notability standards. 

```Shell
❯ brew audit --new-formula --strict kpt
kpt:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

kpt is installable through the Google Cloud SDK, however I thought it would be valuable to also have available via home brew.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by tfhartmann** [comment]
Ok thanks! Shall I close this PR and reopen it at a later date if and when the `kpt` repo reached the required notability threshold?

**Comment by SMillerDev** [comment]
Yeah, apparently I forgot to close it. Sorry about the confusion.

**Comment by tfhartmann** [comment]
no problem! Thanks!

**Pull request closed without merging**
