### PR TITLE
gifify 4.0

### PR DESCRIPTION
**Pull request by jclem**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by UniqMartin** [comment]
It seems like `gifify`'s command line interface has changed in a way that makes the test fail. Can you look into this? You can run the test locally after you have installed the formula by executing `brew test gifify`, if that helps with testing and making sure it works. Thanks!

**Comment by jclem** [comment]
@UniqMartin Should work now, I've force-pushed (assuming this is best for Homebrew PRs?) with a passing test.

**Comment by UniqMartin** [comment]
Thanks! Let's see what the build bot says. (Will take a few moments as it's currently quite busy.)

> I've force-pushed (assuming this is best for Homebrew PRs?)

Yes, that's exactly right. We prefer to have one commit per formula.

**Comment by UniqMartin** [comment]
Merged in 3b8ad7f523926abc4c929ed114be6d7c8fc2a0e0. Thank you for this contribution to Homebrew, @jclem! :tada:

**Comment by jclem** [comment]
Happy to be here 🍦

**Pull request closed without merging**
