### PR TITLE
llvm@4: fix C++ compilation for Mojave and Catalina

### PR DESCRIPTION
**Pull request by smorimoto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Port from #45693. Thank you @jamiesnape.

Related issue and PR: #45061 and #45304.

### CODE REVIEW

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by fxcoudert** [comment]
```
/tmp/llvm@4-20191030-5941-10nafpo/llvm-4.0.1.src/tools/lld/ELF/LTO.cpp:161:32: error: 'template' keyword not permitted here
template void BitcodeCompiler::template add<ELF32LE>(BitcodeFile &);
                               ^~~~~~~~~
/tmp/llvm@4-20191030-5941-10nafpo/llvm-4.0.1.src/tools/lld/ELF/LTO.cpp:162:32: error: 'template' keyword not permitted here
template void BitcodeCompiler::template add<ELF32BE>(BitcodeFile &);
                               ^~~~~~~~~
/tmp/llvm@4-20191030-5941-10nafpo/llvm-4.0.1.src/tools/lld/ELF/LTO.cpp:163:32: error: 'template' keyword not permitted here
template void BitcodeCompiler::template add<ELF64LE>(BitcodeFile &);
                               ^~~~~~~~~
/tmp/llvm@4-20191030-5941-10nafpo/llvm-4.0.1.src/tools/lld/ELF/LTO.cpp:164:32: error: 'template' keyword not permitted here
template void BitcodeCompiler::template add<ELF64BE>(BitcodeFile &);
                               ^~~~~~~~~
```

**Comment by imbsky** [comment]
This should work.

```cpp
template void BitcodeCompiler::add<ELF32BE>(BitcodeFile &);
```

**Comment by imbsky** [comment]
Oh, it's the LLVM source code... Possibly it can't build on Mojave or later. I guess.

**Comment by fxcoudert** [comment]
Given it's an old version, we'll keep it as is. Thanks @imbsky nonetheless for this PR, and all the others!

**Comment by imbsky** [comment]
@fxcoudert I think that's fine. Nooo! Review, merge, and manage are really hard work than most people think! Thank you!

**Pull request closed without merging**
