### PR TITLE
bump Gambit Scheme to 4.9.3

### PR DESCRIPTION
**Pull request by ober**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like the test is failing.

**Comment by ober** [comment]
So the problem here is Gerbil-Scheme needs to be rebuilt to pass. As it is dependent on the version of Gambit. Anyway to force Gerbil-scheme to rebuild as part of this Update?

**Comment by SMillerDev** [comment]
You can make a seperate commit where you bump the revision of gerbil-scheme by adding `revision 1` at the line underneath the version.

**Comment by ober** [comment]
@mistydemeo it is all passing now. Could you please take a look now? Thanks.

**Comment by fxcoudert** [comment]
@ober please make the revision bump a separate commit (one commit per formula)

**Comment by ober** [comment]
Done.

**Comment by fxcoudert** [comment]
Thanks @ober

**Pull request closed without merging**
