### PR TITLE
distcc 3.3.4

### PR DESCRIPTION
**Pull request by mitchblank**
Upstream released moments ago... been waiting for this for awhile.

It does seem like a change made minutes before release broke the build ( https://github.com/distcc/distcc/issues/408 ) but it's easy to fix.  Maybe we'll see a 3.3.5 momentarily that incorporates the fix :shrug:

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by chenrui333** [comment]
did we mention the fix was not incorporated in the 3.3.4 release? :(

**Comment by mitchblank** [comment]
> did we mention the fix was not incorporated in the 3.3.4 release? :(

The title of the bug I filed on distcc starts with "3.3.4 doesn't compile" so I don't think my bug report was ambigious on that.

If you look at the commit history https://github.com/distcc/distcc/commits/master it seems that @shawnl figured it out on his own, since he made another commit to that code immediately after tagging 3.3.4.

The compile issue was introduced minutes before the 3.3.4 release was cut :-(

**Comment by shawnl** [comment]
That release is broken and I will release a fixed version tomorrrow. I will
take down the broken version now.

**Comment by mitchblank** [comment]
> That release is broken and I will release a fixed version tomorrrow. I will take down the broken version now.

If I could ask one favor -- please call the new one 3.3.5.  It always causes a lot of drama and confusion for distributors when the same tarball name gets reused with a new sha256 hash.

**Comment by shawnl** [comment]
Done. I was going to call it 3.3.4.1, but 3.3.5 is fine.

**Comment by mitchblank** [comment]
> Done. I was going to call it 3.3.4.1, but 3.3.5 is fine.

Either of those are fine, I just want to make sure it isn't called "3.3.4" :-) 

Occasionally developers decide to sneak fixes in and do re-releases with the same version number, and it always turns into a pain.

**Pull request closed without merging**
