### PR TITLE
pre-commit 1.14.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails during test:
```
==> /usr/local/Homebrew/Library/Homebrew/shims/scm/git commit -m test
env: python3.7: No such file or directory
```

**Comment by asottile** [comment]
I'll look into this, sorry about the breakage

**Comment by asottile** [comment]
I believe it's related to https://github.com/pre-commit/pre-commit/pull/893

**Comment by igas** [comment]
Closing will try when new version released.

**Comment by asottile** [comment]
Sounds good, this should be 1.14.2 when I get it ready

**Comment by asottile** [comment]
1.14.2 should have a fix for this!  sorry again

**Comment by igas** [comment]
@asottile no worries, thank you for looking into it. https://github.com/Homebrew/homebrew-core/pull/35888

**Pull request closed without merging**
