### PR TITLE
nuxeo: update sha256 for upstream retag

### PR DESCRIPTION
**Pull request by akervern**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

SHA256 has been updated.

### CODE REVIEW

**Comment by DomT4** [comment]
CI disagrees with the updated checksum:
```
==> Verifying nuxeo-8.3.zip checksum
Error: SHA256 mismatch
Expected: 69a51ea0f5663723a58448be80b5caf4258f9d1f8df124e4de90676224afac3c
Actual: cf5111cc72da8c88b19f4002de77a6e5ef86190be9bb1234a52e9d4045bae6f9
```

Any idea why it changed?

**Comment by akervern** [comment]
The zip file was updated just after the PR to fix a blocker; that's why the SHA changed.

**Comment by DomT4** [comment]
Is the issue that forced the repackage something that'll impact users with existing installations?

**Comment by akervern** [comment]
Nope; it just a false-negative java version detection that made the server unable to start.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/734b8ebdbf17acbbf81686a82b6afc7d58da88fc. Thank you for your contribution to Homebrew @akervern; we appreciate it! :smiley_cat:

**Pull request merged**
