### PR TITLE
redis 5.0.7

### PR DESCRIPTION
**Pull request by brainix**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by brainix** [comment]
I ran `brew audit --strict Formula/redis.rb` and got the following output:

```
redis:
  * Formula has other versions so create an alias named redis@5.0.
Error: 1 problem in 1 formula detected
```

But I get the same error on the `master` branch, and it looks like the alias exists here?  https://github.com/Homebrew/homebrew-core/blob/4128f9a15b5c012a9407e69d40cfd032ba1bfdd4/Aliases/redis%405.0

I'm not sure how to proceed.  Any tips?

**Comment by Bo98** [comment]
I don't get that issue on my end. I imagine it'll be fine in the CI too.

**Review by chenrui333 — APPROVED** [review]
looks good to me. conjure-up issue on catalina which is a known issue.

**Comment by chenrui333** [comment]
Thanks @brainix!!

**Pull request closed without merging**
