### PR TITLE
sslsplit: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by chenrui333**
See #134251.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  gcc-11 -L/home/linuxbrew/.linuxbrew/opt/libnet/lib -L/home/linuxbrew/.linuxbrew/Cellar/openssl@3/3.1.1/lib -L/home/linuxbrew/.linuxbrew/Cellar/libevent/2.1.12_1/lib -L/home/linuxbrew/.linuxbrew/Cellar/libpcap/1.10.4/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/libpcap/1.10.4/lib -pthread -o sslsplit base64.o build.o cache.o cachedsess.o cachefkcrt.o cachemgr.o cachessess.o cachetgcrt.o cert.o dynbuf.o log.o logbuf.o logger.o logpkt.o main.o nat.o opts.o privsep.o proc.o proxy.o pxyconn.o pxythrmgr.o ssl.o sys.o thrqueue.o url.o util.o -lnet -lssl -lcrypto -levent_openssl -levent_pthreads -levent -lpcap
  /usr/bin/ld: pxyconn.o: in function `pxy_bev_eventcb':
  pxyconn.c:(.text+0x3418): undefined reference to `ERR_GET_FUNC'
  /usr/bin/ld: pxyconn.c:(.text+0x3483): undefined reference to `ERR_GET_FUNC'
  /usr/bin/ld: pxyconn.c:(.text+0x356c): undefined reference to `ERR_GET_FUNC'
  /usr/bin/ld: pxyconn.c:(.text+0x39a2): undefined reference to `ERR_GET_FUNC'
  /usr/bin/ld: pxyconn.c:(.text+0x3aa0): undefined reference to `ERR_GET_FUNC'
  /usr/bin/ld: pxyconn.o:pxyconn.c:(.text+0x412c): more undefined references to `ERR_GET_FUNC' follow
  collect2: error: ld returned 1 exit status
```

**Comment by Bo98** [comment]
https://github.com/droe/sslsplit/commit/e17de8454a65d2b9ba432856971405dfcf1e7522

**Comment by chenrui333** [comment]
```
  ==> (/home/linuxbrew/.linuxbrew/Cellar/sslsplit/0.5.5_2/bin/sslsplit -D http 0.0.0.0 36763 www.roe.ch 80 & PID=$! && sleep 3 ; kill $PID) 2>&1
  Error: sslsplit: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /Starting\ main\ event\ loop/ to match "".
```

**Comment by cho-m** [comment]
No issues on re-run. Probably a timing issue.

Patch should only be for `stable` to avoid breaking HEAD build, but low priority and can be ignored if we want to merge as-is.

**Review by carlocab — APPROVED** [review]

**Review by nandahkrishna — APPROVED** [review]

**Pull request merged**
