### PR TITLE
cmus-control 1.0.2 (new formula)

### PR DESCRIPTION
**Pull request by TheFox**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
https://github.com/TheFox/cmus-control is the GitHub project as linked from the blog post.

Sorry, this project does not meet our notability criteria:

```
GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

Please consider [hosting it in your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by TheFox** [comment]
That was the reason why I uploaded it to my homepage instead of using the GitHub page URL. So how do you measure the notability of a project when it's not hosted on GitHub?

**Comment by zmwangx** [comment]
> That was the reason why I uploaded it to my homepage instead of using the GitHub page URL.

Unfortunately, we do have human curators, so trying to hide it doesn't help. Using a blog post as the homepage was what got me suspicious in the first place.

Also, the practice of self-submitting marginally notable (if at all) projects is in itself discouraged.

**Comment by bfontaine** [comment]
This is written in [our guidelines](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#niche-or-self-submitted-stuff):

> We frown on authors submitting their own work unless it is very popular.

You can have an idea of a project’s popularity by e.g. checking its mailing-list (if it has one); searching on Google or Twitter; looking if there’s a Debian package; etc.

**Comment by TheFox** [comment]
Ok, I see. I created a tap for this purpose: https://github.com/TheFox/homebrew-brewery

Thank you for your help.

**Pull request closed without merging**
