### PR TITLE
protobuf 27.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by scpeters** [comment]
probably need to bump revisions for `sysdig` and `securefs` as well

**Comment by bevanjkay** [comment]
Just failures for `fastnetmon` on two of the runners. We can followup after?

**Comment by chenrui333** [comment]
sounds good to me :)

**Review by bevanjkay — APPROVED** [review]

**Review by bevanjkay — APPROVED** [review]

**Review by bevanjkay — APPROVED** [review]

**Comment by carlocab** [comment]
Seems like bottles have already been uploaded. They might need to be deleted, which will be a huge pain.

**Comment by bevanjkay** [comment]
@carlocab Is the only way forward here to manually delete all of the bottles? 😅

**Comment by carlocab** [comment]
Unfortunately, yes, probably. Not sure why there was a [force-push](https://github.com/Homebrew/homebrew-core/pull/174260#event-13161950713) after a [`pr-publish`](https://github.com/Homebrew/homebrew-core/pull/174260#issuecomment-2168095922), but, the moral of the story is: don't do that.

**Comment by carlocab** [comment]
This is done except for
- etcd-cpp-apiv3
- fastnetmon
- ncnn
- opentelemetry-cpp
- pytorch

**Pull request merged**
