### PR TITLE
nginx: install src to pkgshare instead of share

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Otherwise we will end up with `$HOMEBREW_PREFIX/share/src/src.tar.xz` which is weird.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Yes, good call, sorry I missed this!

**Comment by MikeMcQuaid** [comment]
Could also consider https://github.com/Homebrew/homebrew-core/pull/36754#issuecomment-463982937 while you're here?

**Comment by lembacon** [comment]
> Could also consider [#36754 (comment)](https://github.com/Homebrew/homebrew-core/pull/36754#issuecomment-463982937) while you're here?

Sure. Updated in https://github.com/Homebrew/homebrew-core/pull/37003/commits/a13d006520c967ace142a8570296f7dc76581589.

**Comment by MikeMcQuaid** [comment]
Perfect, thanks @lembacon!

**Pull request closed without merging**
