### PR TITLE
folly: restore from boneyard

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Ref: https://github.com/Homebrew/homebrew-core/pull/3321

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Failing on 10.10/10.9.

**Comment by DomT4** [comment]
Typical it didn't break on the one platform I can most easily test for. This had a problem with some older Clangs before, so perhaps still the case. I'll poke around upstream.

**Comment by DomT4** [comment]
Filed an Issue upstream: https://github.com/facebook/folly/issues/451

**Comment by JoeLoser** [comment]
Is there any update on this?

**Comment by DomT4** [comment]
It's kind of stuck on upstream. There's [this issue](https://github.com/facebook/folly/issues/451) which breaks Mavericks/Yosemite, and then the latest release contained a new bug that breaks El Capitan's build 🙈.

**Comment by MikeMcQuaid** [comment]
@DomT4 I think trying to get this back from the boneyard may be...



folly

**Comment by DomT4** [comment]
😅 If I ever need cheesy jokes, I'll know where to come 😜. This has only ever really consistently built on El Cap, so my temptation is to restrict it to that for now until upstream fix the Issue I opened there.

**Comment by MikeMcQuaid** [comment]
@DomT4 👍

**Pull request closed without merging**
