### PR TITLE
Bottle unneeded (p)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Extracted from https://github.com/Homebrew/homebrew-core/pull/79448
Part of https://github.com/Homebrew/homebrew-core/issues/75943

### CODE REVIEW

**Comment by carlocab** [comment]
ARM
```
Error: 8 failed steps!
brew install --only-dependencies --verbose --build-bottle payara
brew install --verbose --build-bottle payara
brew test --verbose phplint
brew test --verbose pig
brew audit polynote --online --git --skip-style
brew fetch --retry predictionio --build-bottle --force
brew install --only-dependencies --verbose --build-bottle predictionio
brew install --verbose --build-bottle predictionio
```

`payara` and `predictionio` need `depends_on arch: :x86_64`. Will need a closer look at the rest. Some of the above failed on the Intel nodes too.

**Comment by nandahkrishna** [comment]
All of `polynote`'s releases are marked as pre-releases, so we should probably ignore that audit failure and maybe add it to the allowlist.

**Comment by cho-m** [comment]
`polynote` 0.4.2 was released yesterday as actual release: https://github.com/polynote/polynote/releases/tag/0.4.2
May want to update and bottle separately.

`plantuml` is updated and bottled in #80093, so should remove from here.

**Comment by cho-m** [comment]
May still fail on `predictionio`.
Previously, everything but Mojave hit SHA checksum issue.
Left it in for now since Mojave had passed, so maybe temporary issue.

**Review by nandahkrishna — APPROVED** [review]

**Comment by carlocab** [comment]
No `all` bottle:

`pow` - 9726a6bc38636ed207a55124ef4d3b9c599c4385
`phpstan` - a6642cc22e155ba10bf50aa22a5fc51d86838654
`plod` - e4e05afb82bd9936b5164a3022e7c403410b17c1
`phpbrew` - 1e4a792f04843be2b6a236beda5cba9d097e05b1
`pickle` - d58e2b3df99145aa6490d6bd733e43da5f064e02
`phpmyadmin` - 57776b6703382595d4df17174d320c18ca8d2cd2
`phplint` - 8ca93b866dce04123dc89f655d02431bce2d710d
`plenv` - bdb4846d8f94ffa447093ac1b7bd22993649b1f5

**Pull request closed without merging**
