### PR TITLE
qt: use sqlite from homebrew

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Add missing Qt for automation components.
`sqlite` plugin still use homebrew's `sqlite`, any suggestions?

### CODE REVIEW

**Comment by carlocab** [comment]
>`sqlite` plugin still use homebrew's `sqlite`, any suggestions?

This is okay. You can add `depends_on "sqlite"`, because this already `depends_on "python@3.9"`, which `depends_on "sqlite"`. So you will need to have brewed `sqlite` installed to install `qt` anyway.

**Comment by carlocab** [comment]
What are these plugins for? Are these plugins that used to be bundled as part of qt5?

**Comment by paperchalice** [comment]
> What are these plugins for? Are these plugins that used to be bundled as part of qt5?

These libraries are the part of `qt for automation`, not `qt`. In fact users can still build these libraries out of tree, so I'm not sure should I put them here.

**Comment by carlocab** [comment]
> users can still build these libraries out of tree

This sounds like a good reason not to include them then, especially if we don't have any users asking for them.

**Review by carlocab — APPROVED** [review]
Thanks, @paperchalice.

**Pull request merged**
