### PR TITLE
mpfr 4.1.1

### PR DESCRIPTION
**Pull request by fxcoudert**
@samford I would appreciate help adjusting the livecheck please

### CODE REVIEW

**Comment by samford** [comment]
> I would appreciate help adjusting the livecheck please

When I created this `livecheck` block, I set it up so that it will work predictably whether patches are available or not. When patches aren't available, it will simply return the main version without any patch suffix (e.g., `4.1.1`). If patch information is available on the `/mpfr-current/` page in the expected format, then livecheck will return a version with the trailing patch suffix (e.g., `4.1.1-p01`). At the moment, there aren't any patches so livecheck returns `4.1.1` as newest, as you would expect.

So long as upstream continues to post patch links in the same way that they did on the [4.1.0 release page](https://www.mpfr.org/mpfr-4.1.0/), this `livecheck` block will handle either situation without needing modifications. Does that meet your needs or is there something new that I've missed?

**Comment by fxcoudert** [comment]
Now, I couldn't follow the logic to confirm. You rock!

**Comment by lrineau** [comment]
mpfr version 4.1.2 is planned for mi-december 2022. Meanwhile, you can apply the upstream patch https://www.mpfr.org/mpfr-4.1.1/allpatches to get mpfr version 4.1.1-p1.

**Comment by fxcoudert** [comment]
@lrineau yes I've seen that. We might end up waiting for the new release, it's more work tracking individual patch files posted on website vs. just looking out for new releases.

**Pull request closed without merging**
