### PR TITLE
apache-flink 1.10.0

### PR DESCRIPTION
**Pull request by abonte**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> brew test apache-flink --verbose
==> FAILED
Testing apache-flink
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200213-72372-130ltqf.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apache-flink.rb --verbose
==> /usr/local/Cellar/apache-flink/1.10.0/libexec/bin/start-cluster.sh
Starting cluster.
Starting standalonesession daemon on host Mojave.
[ERROR] Unexpected result: Error: Could not find or load main class org.apache.flink.runtime.util.BashJavaUtils
[ERROR] The last line of the BashJavaUtils outputs is expected to be the execution result, following the prefix 'BASH_JAVA_UTILS_EXEC_RESULT:'
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/private/tmp/apache-flink-test-20200213-72373-16kxxb9 -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Error: Could not find or load main class org.apache.flink.runtime.util.BashJavaUtils
[ERROR] Could not get JVM parameters properly.
Error: apache-flink: failed
Failed executing:
```

**Comment by carp84** [comment]
> ```
> [ERROR] Unexpected result: Error: Could not find or load main class org.apache.flink.runtime.util.BashJavaUtils
> [ERROR] The last line of the BashJavaUtils outputs is expected to be the execution result, following the prefix 'BASH_JAVA_UTILS_EXEC_RESULT:'
> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/private/tmp/apache-flink-test-20200213-72373-16kxxb9 -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
> Error: Could not find or load main class org.apache.flink.runtime.util.BashJavaUtils
> [ERROR] Could not get JVM parameters properly.
> Error: apache-flink: failed
> Failed executing:
> ```

Should be some Flink issue to fix, have opened [FLINK-16052](https://issues.apache.org/jira/browse/FLINK-16052) to track.

Since Flink 1.10.0 is already released with the uploaded artifacts immutable, I'm afraid we have to wait for the next release (1.10.1 or 1.11.0) to update the flink formula.

**Comment by carp84** [comment]
Finally we've located the problem: in [FLINK-15519](https://issues.apache.org/jira/browse/FLINK-15519) we have introduced a jar file and put it under the `bin` directory, which will be moved into `libexec/libexec` directory after the `env_script_all_files` execution and causing the above issue. Will open a new PR to fix the problem.

**Comment by chenrui333** [comment]
Close as the upgrade was done per #50240

Thanks @abonte, @carp84.

**Pull request closed without merging**
