### PR TITLE
ansible: add pynetbox,pytz

### PR DESCRIPTION
**Pull request by k0ste**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Fixes https://github.com/orgs/Homebrew/discussions/5702
NetBox collection is: https://github.com/netbox-community/ansible_modules

### CODE REVIEW

**Comment by timureh** [comment]
This PR fixed my bug: pynetbox ModuleNotFound
pynetbox_not_found

**Comment by k0ste** [comment]
@chenrui333 Hi
Seems your additions break the build. Especially for `readline` 🥲

**Comment by chenrui333** [comment]
> Seems your additions break the build. Especially for `readline` 🥲

that is from the dependency resolution

**Comment by k0ste** [comment]
> that is from the dependency resolution

What exactly package (`pynetbox`, `pytz`) does it require `gnureadline`? I don't see it at dependencies, for example in arch: [1](https://gitlab.archlinux.org/archlinux/packaging/packages/python-pytz/-/blob/main/PKGBUILD?ref_type=heads#L14), [2](https://gitlab.archlinux.org/archlinux/packaging/packages/python-pynetbox/-/blob/main/PKGBUILD?ref_type=heads#L12)

----

Without resource `gnureadline`, the builds & test completes fine
```bash
🍺  /opt/homebrew/Cellar/ansible/10.6.0_1: 33,403 files, 376.1MB, built in 4 minutes 29 seconds
√ homebrew-core % brew test ansible
==> Testing ansible
==> /opt/homebrew/Cellar/ansible/10.6.0_1/bin/ansible-playbook /private/tmp/ansible-test-20241112-38927-rdrym5/playbook.yml -i /private/tmp/a
==> /opt/homebrew/Cellar/ansible/10.6.0_1/libexec/bin/python -c import requests as r; r.get('https://mozilla-modern.badssl.com')
==> /opt/homebrew/Cellar/ansible/10.6.0_1/bin/ansible-vault encrypt --vault-password-file /private/tmp/ansible-test-20241112-38927-rdrym5/vau
==> /opt/homebrew/Cellar/ansible/10.6.0_1/bin/ansible-vault decrypt --vault-password-file /private/tmp/ansible-test-20241112-38927-rdrym5/vau
==> /opt/homebrew/Cellar/ansible/10.6.0_1/bin/ansible-test sanity --list-tests 2>&1
√ homebrew-core %
```

**Comment by chenrui333** [comment]
I am using `brew update-python-resources` cc @branchvincent

**Comment by branchvincent** [comment]
> What exactly package (`pynetbox`, `pytz`) does it require `gnureadline`?

Looks like it's required by `python-neutronclient` which was added for https://www.openstack.org/ support

**Comment by k0ste** [comment]
> > What exactly package (`pynetbox`, `pytz`) does it require `gnureadline`?
> 
> Looks like it's required by `python-neutronclient` which was added for https://www.openstack.org/ support

Can we skip the OS-client update as it is not related to this PR?

**Comment by chenrui333** [comment]
> > > What exactly package (`pynetbox`, `pytz`) does it require `gnureadline`?
> > 
> > 
> > Looks like it's required by `python-neutronclient` which was added for https://www.openstack.org/ support
> 
> Can we skip the OS-client update as it is not related to this PR?

yeah, I know this is unrelated to this PR, but for the next PR it would come again. (this needs to be addressed in the upstream)

**Comment by k0ste** [comment]
> yeah, I know this is unrelated to this PR, but for the next PR it would come again. (this needs to be addressed in the upstream)

The `readline` is common & standard library. It's builtin under MacOS too, in brew the [readline formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/r/readline.rb#L82) is keg. So I don't think that python gnureadline (statically linked) is actually needed, because (copy from description):

> The standard Python readline extension statically linked against the GNU readline library, providing readline support to Python on platforms without it.

I think the `gnureadline` is only needed in very uncommon environments, like IoT devices \(\?\)

----

I'm double checked [ansible-collection for openstack](https://opendev.org/openstack/ansible-collections-openstack/src/branch/master/requirements.txt), [openstacksdk](https://github.com/openstack/openstacksdk/blob/master/requirements.txt), and [python-neutronclient](https://github.com/openstack/python-neutronclient/blob/master/requirements.txt) requirements.txt files. Can't find the root cause for `brew update-python-resources` adding this resource

----

Thanks to the author of `gnureadline` @ludwigschwardt, we can check the environment to answer on question "Do I need this package?"
```shell
√ ~ % python3 -c "import readline; print(readline.__doc__)"
Importing this module enables command line editing using libedit readline.
√ ~ %
```

My MacOS 15 says - no. I removed the `gnureadline` from Formula, and add to exclude list. Now CI are green 🟢

**Comment by chenrui333** [comment]
> I removed the `gnureadline` from Formula, and add to exclude list. Now CI are green 🟢

yeah, that is one way to go. (it might take more time to find out the root cause, but might not worth the efforts)

@k0ste thanks a lot for your work on this.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
