### PR TITLE
s3ql 3.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Processing /private/tmp/s3ql--pyfuse3-20200413-80076-18grpcj/pyfuse3-1.3.1
  Created temporary directory: /private/tmp/pip-req-build-3rv8jdea
  Added file:///private/tmp/s3ql--pyfuse3-20200413-80076-18grpcj/pyfuse3-1.3.1 to build tracker '/private/tmp/pip-req-tracker-aacvhl50'
    Running setup.py (path:/private/tmp/pip-req-build-3rv8jdea/setup.py) egg_info for package from file:///private/tmp/s3ql--pyfuse3-20200413-80076-18grpcj/pyfuse3-1.3.1
    Running command python setup.py egg_info
    Package fuse3 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `fuse3.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'fuse3' found
Cleaning up...
  Removing source in /private/tmp/pip-req-build-3rv8jdea
Removed file:///private/tmp/s3ql--pyfuse3-20200413-80076-18grpcj/pyfuse3-1.3.1 from build tracker '/private/tmp/pip-req-tracker-aacvhl50'
Removed build tracker: '/private/tmp/pip-req-tracker-aacvhl50'
ERROR: Command errored out with exit status 2: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 544, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 118, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/usr/local/Cellar/s3ql/3.4.0/libexec/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 2: python setup.py egg_info Check the logs for full command output.

```

**Comment by chenrui333** [comment]
Having the same issue in my local also.

**Comment by issyl0** [comment]
From the README:

> S3QL is developed and tested under Linux. Users have also reported running S3QL successfully on OS-X, FreeBSD and NetBSD. We try to maintain compatibility with these systems, but (due to lack of pre-release testers) we cannot guarantee that every release will run on all non-Linux systems. Please report any bugs you find, and we will try to fix them.

Doesn't bode very well... I get the same error (on Catalina).

**Comment by issyl0** [comment]
This relies on `pyfuse3` as a resource. At the [required `pyfuse3` version for `s3ql`](https://github.com/s3ql/s3ql/blob/master/rst/installation.rst#dependencies) the docs [don't mention macOS](http://www.rath.org/pyfuse3-docs/install.html) at all. I think this might be a non-starter.

**Comment by Bo98** [comment]
osxfuse is still on 2.9.x API. fuse3 API is not available on macOS.

This is similar to how we cannot use newer versions of sshfs.

s3ql 3.4.0 simply cannot be used on macOS unfortunately.

**Comment by issyl0** [comment]
In light of Bo's comments, I'm going to close this. The current formula as-is has had 23 installs over the past 90 days, so I don't think it's a candidate for deletion _yet_.

**Pull request closed without merging**
