### PR TITLE
update gpg-agent to 2.2.5

### PR DESCRIPTION
**Pull request by faraazkhan**
- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chdiza** [comment]
I'm not sure users of `gnupg@2.0` should be using the `gpg-agent` bundled with `gnupg` 2.2.5.  They should be using the one associated with `gnupg@2.0`.

Users of the latest `gnupg` don't need a separate `gpg-agent` formula.

**Comment by DomT4** [comment]
Agree with @chdiza here. I think there used to be a note in the formula about which branch this was supposed to track but maybe I'm misremembering.

**Comment by faraazkhan** [comment]
So the reason I did had to do this on my local was `git-crypt`, it complained about version `2.0.31` being outdated and that there might be vulnerabilities, but maybe there is a better fix?

**Comment by DomT4** [comment]
Are you using the `gnupg@2.0` formula locally or is `gpg-agent` simply a remnant from before Homebrew moved over to the 2.1 branch?

**Comment by faraazkhan** [comment]
I am not using the `gnupg@2.0`, so most likely a remnant then

**Comment by DomT4** [comment]
I'd probably just `brew rm gpg-agent`, run `gpgconf --kill gpg-agent` and then see if `git-crypt` still complains.

**Comment by faraazkhan** [comment]
Nope, doesn't complain. Also I see what you meant about it picking up the bundled `gpg-agent`. Thanks for the tip. Would you like me to close this PR now?

**Comment by DomT4** [comment]
> Thanks for the tip. 

No worries!

> Would you like me to close this PR now?

Aye, may as well. At some point this formula and `gnupg@2.0` will go bye-bye but we're not quite there yet, so I think the status quo will have to live on for now.

**Pull request closed without merging**
