### PR TITLE
Switch download url from bintray to binaries.sonarsource.com

### PR DESCRIPTION
**Pull request by xavierbourguignon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As you can see on https://www.sonarqube.org/downloads/, we (I'm working at SonarSource, the company behind SonarQube) decided to switch from bintray to our own download site.

### CODE REVIEW

**Comment by fxcoudert** [comment]
From https://www.sonarlint.org I am not seeing any notice that it is discontinued. We still have many users:

```
install events in the last 30 days
================================================================================
1 | sonarlint                                                     | 47 | 100.00%
================================================================================
```

**Comment by xavierbourguignon** [comment]
This formula install sonarlint cli that has been stopped in 2017, the repo is read only now: https://github.com/SonarSource/sonarlint-cli

And we talk about it on our google groups: https://groups.google.com/d/msg/sonarqube/WlALjVzp-OE/q_tx5oOgBAAJ

**Comment by fxcoudert** [comment]
Please update the pull request so that it has 1 commit per formula, with commit message:
`sonar-scanner: update URL`, `sonarlint: delete`, etc.

**Comment by xavierbourguignon** [comment]
done !

**Comment by fxcoudert** [comment]
Thanks @xavierbourguignon

**Pull request merged**
