### PR TITLE
awscli 1.11.139

### PR DESCRIPTION
**Pull request by shigemk2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
I think as a rule of thumb we should only bump this formula if the difference between versions is >= 10 so I'm going to pass on this PR but thanks nonetheless.

**Comment by shigemk2** [comment]
Well, awscli is very often updated. 

You mean we should bump awscli when awscli is upgraded from `1.11.140` to `1.11.150`, right?

**Comment by ilovezfs** [comment]
@shigemk2 yeah, or if brew is at 140 and current version is 152, then upgrade to 152 not 150. So just make sure the difference is at least 10.

**Comment by ilovezfs** [comment]
@shigemk2 but yes, bumping when the last digit is zero would be simplest.

**Comment by shigemk2** [comment]
@ilovezfs 
For this reason, I think other formula just like presto should be also bumped from `0.180` to `0.190`, right?
https://github.com/Homebrew/homebrew-core/pull/16474

And then, is there any documentation for this rule of thumb?

**Comment by ilovezfs** [comment]
@shigemk2 I don't think presto is updated very often, is it?

>And then, is there any documentation for this rule of thumb?

No but we could put a note in the formula, I suppose. The same rule should apply to aws-sdk-cpp. For vim the interval needs to be more like 30 or 40.

**Comment by shigemk2** [comment]
@ilovezfs 
> I don't think presto is updated very often, is it?

No. But I am not sure when we should bump presto?

I am not sure the standard when we should bump formulae in homebrew-core's documents, so please add the documentation for bumping or I will write the documentation.

**Pull request closed without merging**
