### PR TITLE
argocd: fix revision v1.8.7 (#72633)

### LINKED ISSUE #72633: argocd 1.8.7 wrong revision
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
$ brew config
HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 145f4964db7896156b1bcbcf5181b7e5f6a638a8
Core tap last commit: 7 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 24-core 64-bit zen
Clang: N/A
Git: 2.25.1 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-45-generic x86_64 GNU/Linux
OS: Linux Mint 20 (ulyana)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A

$ brew doctor
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

brew install argocd on linux. for mac it seems it downloads the binary because it's available but on linux clone from https://github.com/argoproj/argo-cd.git and the release for tag v1.8.7 seems incorrect

### What happened (include all command output)?

```
> brew install argocd
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://linuxbrew.bintray.com/bottles/go-1.16_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/sdelrio/.cache/Homebrew/downloads/303d221902a438336a16ccf086eac2b5920490516545955e7552cc8667f96190--go-1.16_1.x86_64_linux.bottle.tar.gz
==> Cloning https://github.com/argoproj/argo-cd.git
Updating /home/sdelrio/.cache/Homebrew/argocd--git
==> Checking out tag v1.8.7
HEAD is now at eb3d1fb Bump version to 1.8.7
HEAD is now at eb3d1fb Bump version to 1.8.7
Error: v1.8.7 tag should be a97230859344f8906502763743717d7ad7339c55
but is actually eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
```

### What did you expect to happen?

argocd 1.8.7 to get installed

### Step-by-step reproduction instructions (by running `brew` commands)

brew install argocd

### PR DESCRIPTION
**Pull request by sdelrio**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @sdelrio. Can you file an issue upstream to check that the retagging of 1.8.7 was intentional? (For an example, see https://github.com/ksync/ksync/issues/495.)

Also, for future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings. Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

**Comment by sdelrio** [comment]
I did fill the issue but seems the I wrote bad the fix text

https://github.com/Homebrew/homebrew-core/issues/72633

**Comment by carlocab** [comment]
No, I don't mean to file an issue here in homebrew/core. I mean to file an issue upstream: https://github.com/argoproj/argo-cd.git

**Comment by sdelrio** [comment]
> Thanks for your PR, @sdelrio. Can you file an issue upstream to check that the retagging of 1.8.7 was intentional? (For an example, see [ksync/ksync#495](https://github.com/ksync/ksync/issues/495).)
> 
> Also, for future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings. Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

Ok, missunderstand when reading it first time. will file the ussue there in argo-cd

https://github.com/Homebrew/homebrew-core/issues/72633

**Comment by sdelrio** [comment]
Already commented on the argocd issue. I found  that brew on the mac version there was a binary already build with that missing commit id a97230859344f8906502763743717d7ad7339c55

```
❯ argocd version
argocd: v1.8.7+a972308.dirty
  BuildDate: 2021-03-03T06:56:34Z
  GitCommit: a97230859344f8906502763743717d7ad7339c55
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
```
What I found (probably can't see with the copy/paste) is that the tag had an space after the 1.8.7. When brew (mac) upgrade to that version (" Upgrading argocd 1.8.4 -> 1.8.7 ") and the one giving error brew (linux) didn't had the space when saying "Upgrading argocd 1.8.4 -> 1.8.7"

```
❯ brew upgrade argocd
==> Upgrading 1 outdated package:
argocd 1.8.4 -> 1.8.7
==> Upgrading argocd 1.8.4 -> 1.8.7 
==> Downloading https://homebrew.bintray.com/bottles/argocd-1.8.7.catalina.bottle.tar.gz
```

**Comment by carlocab** [comment]
Very strange. I'm thinking the one we have bottled in Homebrew is probably the wrong tag, so we'll want to add `revision 1` right after the `license` line. This way, users will get the updated version of the formula when they do `brew upgrade`.

Can you add that change to this PR, then squash your commits together? Thanks!

**Comment by sdelrio** [comment]
Want me to `git rebase -i HEAD~1` or there is an option "Merge squash" on the PR (the merge says I'm not authorized so I can't see that)

**Comment by carlocab** [comment]
You can `git rebase -i HEAD~2` to squash your second commit into the first one.

**Comment by sdelrio** [comment]
argocd confirmed there was released twice. https://github.com/argoproj/argo-cd/issues/5703#issuecomment-792301905
Did I make the git rebase correctly or need more changes?

**Comment by carlocab** [comment]
>Did I make the git rebase correctly or need more changes?

Not exactly. You should have only one commit here, and no merge commits. Let me know if you need help fixing this.

**Review by carlocab — APPROVED** [review]
I've helped you out here by rebasing for you. Next time you want to avoid doing `git merge` so that you don't create merge commits. (You can do `git rebase` instead.)

Thanks for your first contribution to homebrew/core!

**Comment by sdelrio** [comment]
Thanks for helping with the squash!

**Pull request closed without merging**
