### PR TITLE
python: make unversioned symlinks optional (but discouraged)

### LINKED ISSUE #24788: Option for old behavior of python formula
I know that Python migration is intentional, and was announced in January (via post in blog which I doubt is read by many users)

However, one may want to have "python3" link and/or have system python not shadowed.

From what I saw in other closed issues, user is expected to workaround this, but  I can't come up with any workaround which doesn't require replacing links brew creates manually, and which won't break on upgrade.

In fact, I can't come up with any way to workaround this properly: if there's any non-kegonly formula depending on python, it can safely expect "python" to be python 3, and in fact it has to do that, because it can't use python3 anymore.

I also realize that "python is now same as other languages", but python2 and python3 is a thing that makes it different.

So, provided that workaround isn't easy, and may even be impossible in some cases, I think that it should be provided out of box.

And removing "python3" symlink is a bad choice too -- even on systems where "python" is python 3, python3 symlink still exists
because it's widely used.

And maybe it can be done in a way that anything depending on python may specify it absolutely needs "python" to be "python3", but I'm not that good in brew to think of this.

### PR DESCRIPTION
**Pull request by cmsj**
Closes #24788

### CODE REVIEW

**Comment by cmsj** [comment]
I realise this is somewhat unlikely to be accepted, but I felt compelled to do the work anyway :)

**Comment by cmsj** [comment]
(and FTR, I'd be happy to add any number of big flashing warnings about how this is almost certainly not what the user wants, because it is what I want and I know what Im doing 😁)

**Comment by pwnall** [comment]
FWIW I will have to remove Homebrew's Python 3 from my computer because a lot of Google-internal tools I have no control over assume that "python" resolves to python2.

**Comment by ilovezfs** [comment]
@pwnall why not

```
iMac-TMP:~ joe$ brew() {
brew "$@"
rm -f /usr/local/bin/python
}
```

**Comment by ilovezfs** [comment]
@cmsj @pwnall PR making python and python@2 PEP 394 compliant:
https://github.com/Homebrew/homebrew-core/pull/25060

**Comment by pwnall** [comment]
@ilovezfs Thank you very much for putting together the PR above. Sorry for expressing my gratitude so late -- been swamped this past week.

**Comment by ilovezfs** [comment]
@pwnall you're welcome!

**Pull request closed without merging**
