### PR TITLE
vim 8.0.1241

### PR DESCRIPTION
**Pull request by ericbn**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ericbn** [comment]
This update includes the [highlighting of all matches while incremental searching](https://www.reddit.com/r/vim/comments/79hi4q/vim_801238_adds_highlighting_of_all_matches_while/) patch.

**Comment by woodruffw** [comment]
Thanks @ericbn!

**Comment by ilovezfs** [comment]
I've reverted this. We're only updating `vim` every 50 releases.

**Comment by ilovezfs** [comment]
8.0.1250 has now shipped: https://github.com/Homebrew/homebrew-core/pull/20194

**Pull request closed without merging**
