### PR TITLE
lc0 0.29.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ../../src/neural/metal/mps/NetworkGraph.mm:709:51: error: no visible @interface for 'MPSGraph' declares the selector 'splitTensor:splitSizes:axis:name:'
      NSArray<MPSGraphTensor *> * offsets = [_graph splitTensor:keys
                                             ~~~~~~ ^~~~~~~~~~~~~~~~
  ../../src/neural/metal/mps/NetworkGraph.mm:723:21: error: no visible @interface for 'MPSGraph' declares the selector 'stackTensors:axis:name:'
      promo = [_graph stackTensors:stack axis:3 name:[NSString stringWithFormat:@"%@/offset_broadcast", label]];
               ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 errors generated.
```

**Review by bayandin — DISMISSED** [review]

**Review by SMillerDev — APPROVED** [review]

**Comment by borg323** [comment]
I don't know the appropriate place for this, but I assume the interested parties will notice it here: Net 42850 is quite old and considerably weaker than modern ones, more so since lc0 defaults have changed. I would suggest using 753723 that works with all lc0 backends, but if you want a different one with the metal backend, then use 791556 (but note it won't work with opencl).

**Comment by bayandin** [comment]
Thanks for popping up @borg323!
I was thinking about using the Small network (from https://lczero.org/play/networks/bestnets/#strongest-networks) as a reasonable default which will be easy to update with new releases (by getting a link from the webpage); it also will reduce the size of the package, since we bundle it. What do you think?

Another question or maybe an idea, currently `lc0` installed from homebrew doesn't play nice with additional networks (if a user puts it to the directory with the binary, we delete it for the next update); it would be nice if we could configure the directory where to look for a network, then we'll be able to preserve it.

**Comment by borg323** [comment]
> I was thinking about using the Small network.

The networks I suggest above are the same size with the one suggested in the bestnets page, but are tested a bit more and thus the defaults we use for our releases. Also note the one suggested in bestnets will not work with the opencl backend - I updated the page to reflect that.

> it would be nice if we could configure the directory where to look for a network, then we'll be able to preserve it.

Currently, lc0 looks for networks in `$HOME/Library/lc0` under macos, while under linux either `$XDG_DATA_HOME/lc0` if `XDG_DATA_HOME` is defined or `$HOME/.local/share/lc0` otherwise.

**Comment by bayandin** [comment]
Created https://github.com/Homebrew/homebrew-core/pull/118495

**Pull request closed without merging**
