### PR TITLE
swiftformat 0.32.1

### PR DESCRIPTION
**Pull request by nicklockwood**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nicklockwood** [comment]
I'm confused by this test failure. The test fails when I run it locally too, but I haven't changed the test code, and the app runs fine if I perform the same commands manually.

**Comment by ilovezfs** [comment]
did you figure it out? It looks like the checksum changed here.

**Comment by nicklockwood** [comment]
@ilovezfs yeah, I think it was returning nonzero exit code on success. I've pushed a fix.

**Comment by ilovezfs** [comment]
Cool. That was fast :)

**Comment by nicklockwood** [comment]
@ilovezfs Cool, that worked. Maybe you should add `brew test` to the PR checklist?

**Comment by nicklockwood** [comment]
@ilovezfs is this good to go?

**Comment by ilovezfs** [comment]
yup. a bit of a log jam because we just upgraded the base image but it'll clear soon

**Comment by ilovezfs** [comment]
Thanks @nicklockwood!

**Pull request closed without merging**
