### PR TITLE
evince 3.26.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
libtool: link: ar crD .libs/libgimpcellrenderertoggle.a .libs/libgimpcellrenderertoggle_la-gimpcellrenderertoggle.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar: illegal option -- D
```
Same as https://github.com/pioneerspacesim/pioneer/commit/4e49e7eb1c62d6b74e1a5fb3c38b1085a5236426 so I think we only need `r`

**Comment by tschoonj** [comment]
strange as I didn't get that error locally

**Comment by tschoonj** [comment]
This one ready for a merge?

**Comment by ilovezfs** [comment]
The arflags things needs to be reported but otherwise yes

**Comment by tschoonj** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=787709

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:balloon:

**Pull request closed without merging**
