### PR TITLE
vim 8.2.0150

### PR DESCRIPTION
**Pull request by shigemk2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tyru** [comment]
8.2.0150 was broken. Many plugins may not work (https://github.com/vim/vim/issues/5541).
Now current vim HEAD (8.2.0172) is fixed, but brew doesn't accept hotfix PR?

```
$ brew bump-formula-pr vim --url='https://github.com/vim/vim/archive/v8.2.0172.tar.gz'

...

vim:
  * should only be updated every 50 releases on multiples of 50
Error: 1 problem in 1 formula detected
Error: `brew audit` failed!
```

**Comment by tyru** [comment]
Current homebrew HEAD is broken.
Please include hotfix patch like #30357.

**Comment by chuling** [comment]
Maybe homebrew-core should create a new formula named `vim@stable` or `vim@release` which only provide the most recent release build without patch (like [vim 8.2.0000](https://github.com/vim/vim/releases/tag/v8.2.0000)).

**Comment by itchyny** [comment]
> Maybe homebrew-core should create a new formula named vim@stable or vim@release which only provide the most recent release build without patch (like vim 8.2.0000).

The problem is that there're no stable release in Vim. Actually, 7.4.000 was unstable due to the new NFA engine, 8.0.0000 and 8.1.0000 were buggy that netrw (bundled and famous plugin) do not work. 8.2.0000 was stable, but there're no guarantee that 8.3.0000 (or maybe 9.0.0000?) is a stable release. It is important to adopt flexibility to quickly upgrade the version when serious problems are fixed, even if there are no more than 50 patches.

**Comment by chuling** [comment]
> > Maybe homebrew-core should create a new formula named vim@stable or vim@release which only provide the most recent release build without patch (like vim 8.2.0000).
> 
> The problem is that there're no stable release in Vim. Actually, 7.4.000 was unstable due to the new NFA engine, 8.0.0000 and 8.1.0000 were buggy that netrw (bundled and famous plugin) do not work. 8.2.0000 was stable, but there're no guarantee that 8.3.0000 (or maybe 9.0.0000?) is a stable release. It is important to adopt flexibility to quickly upgrade the version when serious problems are fixed, even if there are no more than 50 patches.

Upgrading vim every 50 patches feels like playing a roulette :joy:. Homebrew-core should either provide the latest known-to-work version (maybe not up-to-date) like some linux distros or allow maintainers to upgrade more frequent :thinking:.

**Comment by tyru** [comment]
> Current homebrew HEAD is broken.

Fixed by #49721

**Pull request closed without merging**
