### PR TITLE
sslyze 5.0.6

### PR DESCRIPTION
**Pull request by singingwolfboy**
Upgrade `sslyze` to 5.0.6. Also makes it depend on `python-typing-extensions` (from #112583).

### CODE REVIEW

**Comment by singingwolfboy** [comment]
https://github.com/nabla-c0d3/nassl/issues/96

**Comment by chenrui333** [comment]
looks like the upstream patch has been merged, can we try the patch in this PR?

**Comment by chenrui333** [comment]
ping @singingwolfboy

**Comment by singingwolfboy** [comment]
> looks like the upstream patch has been merged, can we try the patch in this PR?

Fixed.

**Comment by carlocab** [comment]
`zlib 1.2.13`?

**Comment by singingwolfboy** [comment]
> `zlib 1.2.13`?

Yes, it seems that it's not possible to download older versions from zlib.net.

**Comment by chenrui333** [comment]
Can you squash the commits into one?

**Comment by singingwolfboy** [comment]
> Can you squash the commits into one?

Done.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @singingwolfboy!

**Pull request closed without merging**
