### PR TITLE
gtk-doc 1.27

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by tschoonj** [comment]
You can safely ignore the audit error. gtk-doc does not have development releases.

**Comment by ilovezfs** [comment]
@tschoonj it would be good to add a white list exception for it in Homebrew/brew if you find a moment.

**Comment by ilovezfs** [comment]
:sparkle:

**Pull request closed without merging**
