### PR TITLE
aws-sdk-cpp 1.9.10

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
-- Performing Test CURL_HAS_TLS_PROXY - Success
CMake Error at aws-cpp-sdk-core/CMakeLists.txt:496 (aws_use_package):
  Unknown CMake command "aws_use_package".
```

**Comment by cho-m** [comment]
Version 1.9 appears to have introduced git submodules
- Commit: https://github.com/aws/aws-sdk-cpp/commit/bb964685686c211d078fba7b8c840b73e16430de
- Docs: https://github.com/aws/aws-sdk-cpp#version-19-is-now-available

It seems to have broken build via `tar.gz`/`zip` source code: aws/aws-sdk-cpp#1638

**Comment by carlocab** [comment]
Can we check that the submodules aren't pulling in any dependencies that already exist in Homebrew/core? I'm usually suspicious of Git checkouts because they often end up vendoring things we don't want them to.

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by unilynx** [comment]
Reporting this in case anyone else is seeing issues. I don't know if this is the best place for this or if I should file an issue somewhere, but this update is triggering build failures for me

```
Undefined symbols for architecture x86_64:
  "Aws::Crt::g_allocator", referenced from:
...
  "_aws_mem_release", referenced from:
```

even after cleaning builds. A colleague on a M1 is also reporting it.

**Comment by carlocab** [comment]
Can you reproduce it with a source build straight from the Git repo (i.e. without using `brew` at all)? If you can, report it upstream. If you can't, open an issue here.

**Comment by unilynx** [comment]
It turned out we now needed to add aws-crt-cpp and aws-c-common as extra libraries the linker. For some reason they weren't automatically picked up or added through pkg-config.

**Pull request closed without merging**
