### PR TITLE
nss 3.79

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    "_PR_GetPrefLoopbackAddrInfo", referenced from:
        _getBoundListenSocket in selfserv.o
  ld: symbol(s) not found for architecture arm64
```

**Comment by cho-m** [comment]
May need a newer `nspr` (#102292)

**Comment by owine** [comment]
> May need a newer `nspr` (#102292)

This is the case per their release notes. Hopefully that is merged soon and I will rebase.

**Comment by owine** [comment]
Only test failure appears to be unrelated.

**Pull request closed without merging**
