### PR TITLE
mist 1.9.1

### PR DESCRIPTION
**Pull request by NorseGaud**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by NorseGaud** [comment]
Opened https://github.com/ninxsoft/mist-cli/issues/108 regarding failing tests

**Comment by NorseGaud** [comment]
I don't have permissions to add the label :(

**Comment by chenrui333** [comment]
did not get response yet, right?

**Comment by NorseGaud** [comment]
> did not get response yet, right?

The dev said he's out of town for a few weeks and he'll likely need to do 1.9.2 anyway... we can just keep closed for now

**Comment by chenrui333** [comment]
> > did not get response yet, right?
> 
> The dev said he's out of town for a few weeks and he'll likely need to do 1.9.2 anyway... we can just keep closed for now

Sounds good!

**Comment by chenrui333** [comment]
I should have spotted out the artifact issue way earlier. @NorseGaud, for the future, you can just use `brew bump --open-pr mist` to file the PR.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
