### PR TITLE
sui 1.25.0

### PR DESCRIPTION
**Pull request by johnjmartin**
Created by https://github.com/mislav/bump-homebrew-formula-action

From release: https://github.com/MystenLabs/sui/actions/runs/9087033911

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error: could not compile `sui` (bin "sui") due to 1 previous error
  error: failed to compile `sui v1.25.0 (/private/tmp/sui-20240514-8180-1vdlvm/sui-testnet-v1.25.0/crates/sui)`, intermediate artifacts can be found at `/private/tmp/sui-20240514-8180-1vdlvm/sui-testnet-v1.25.0/target`.
```

**Comment by carlocab** [comment]
```
  error[E0080]: evaluation of constant value failed
    --> crates/sui/src/main.rs:12:1
     |
  12 | bin_version::bin_version!();
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'unable to query git revision', crates/sui/src/main.rs:12:1
     |
     = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `bin_version::bin_version` (in Nightly builds, run with -Z macro-backtrace for more info)
  
  note: erroneous constant encountered
    --> crates/sui/src/main.rs:12:1
     |
  12 | bin_version::bin_version!();
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this note originates in the macro `bin_version::bin_version` (in Nightly builds, run with -Z macro-backtrace for more info)
  
  note: erroneous constant encountered
    --> crates/sui/src/main.rs:12:1
     |
  12 | bin_version::bin_version!();
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this note originates in the macro `$crate::to_str` which comes from the expansion of the macro `bin_version::bin_version` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by johnjmartin** [comment]
Thank you both! i found the problematic change and am fixing forward

**Comment by johnjmartin** [comment]
Fixed, will be applied with our next release on monday/tuesday

**Pull request closed without merging**
