### PR TITLE
Update hash value for gnutls patch

### LINKED ISSUE #43156: gnutls patch sha256 seemingly incorrect
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
$ brew gist-logs gnutls
Error: No logs.

$ brew gist-logs gnupg
Error: Not Found
```

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 925ec737fba1db97d0170c56de982900711cacd3
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3d417df47f02fba0c118678916aeef0656a0360e
Core tap last commit: 6 minutes ago
HOMEBREW_PREFIX: /Users/jakew/dev/other/homebrew
HOMEBREW_CELLAR: /Users/jakew/dev/other/homebrew/Cellar
HOMEBREW_REPOSITORY: /Users/jakew/dev/other/homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /Users/jakew/dev/other/homebrew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14, 13, 12.0.1, 11.0.3, 10, 9.0.1, 1.8.0_212, 1.7.0_80, 1.6.0_65-b14-468
macOS: 10.14.5-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.2.1
CLT headers: 10.3.0.0.1.1562985497

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this unsupported configuration.


Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /Users/jakew/dev/other/homebrew/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/Users/jakew/dev/other/homebrew/sbin:$PATH"' >> ~/.bash_profile
```

To help us debug your issue please explain:

- What you were trying to do (and why)

Regular `brew upgrade` with `gnupg` already installed at version 2.2.16_1

- What happened (include command output)

```
$ brew upgrade
==> Upgrading 5 outdated packages:
gnupg 2.2.16_1 -> 2.2.17, repo 1.13.3 -> 1.13.4, git 2.22.0_1 -> 2.22.1, buildifier 0.26.0 -> 0.28.0, gnutls 3.6.8 -> 3.6.9
==> Upgrading gnupg
==> Installing dependencies for gnupg: gnutls
==> Installing gnupg dependency: gnutls
==> Downloading https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.9.tar.xz
######################################################################## 100.0%
==> Downloading https://gitlab.com/gnutls/gnutls/commit/ef80617d1e17e0878a909baad62a75ba265c0e00.patch
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 3b1634fa348c0f0064e43f3fb673e30a5e46f2b51cd6cd0d4a0cbf326e71c90e
  Actual: 34480b13120e2167060795060b6738c26622c341498cf6303b17b143642b14cd
 Archive: /Users/jakew/Library/Caches/Homebrew/downloads/0c113ab0098bc4c3f2e8f410741b6104f2928fe63eb38cf98f8dcc3362f02ac4--ef80617d1e17e0878a909baad62a75ba265c0e00.patch
To retry an incomplete download, remove the file above.
```

Deleted the patch file and re-ran, same result. Deleted the patch file and the gnutls 3.6.9 tar.xz file and re-ran, same result.

- What you expected to happen

`gnutls` 3.6.9 installs successfully allowing `gnupg` to install.

- Step-by-step reproduction instructions (by running `brew install` commands)

Given an installation of `gnupg` 2.2.16_1 and `gnutls` 3.6.8 (and any other required dependencies), attempt `brew upgrade`.

---

The formula for `gnutls` currently contains:

https://github.com/Homebrew/homebrew-core/blob/2f555dbfbcd65888c8deb00bb22b16926de7e698/Formula/gnutls.rb#L31-L34

When downloading that patch manually and piping through `sha256sum` I see the same result as the failed install which is different from the formula value:

```
$ curl https://gitlab.com/gnutls/gnutls/commit/ef80617d1e17e0878a909baad62a75ba265c0e00.patch | sha256sum
34480b13120e2167060795060b6738c26622c341498cf6303b17b143642b14cd
```

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #43156

### CODE REVIEW

**Comment by alebcay** [comment]
I'm the one that originally included that patch in the `gnutls` formula in #42779. I guess I'm wondering - I know for GitHub, there is the `?full_index=1` parameter that's supposed to prevent this kind of thing from happening; does GitLab have something similar?

**Comment by JakeWharton** [comment]
Interesting. That parameter seems to be documented nowhere (at least not that's indexed by Google). It's not clear to me why that affects the hash of the contents of the patch though?

**Comment by alebcay** [comment]
At least with GitHub, I believe the checksum changes because the commit range (`index <start_commit>..<end_commit>`) changes without the URL parameter.

**Comment by jonchang** [comment]
https://gitlab.com/gnutls/gnutls/commit/ef80617d1e17e0878a909baad62a75ba265c0e00.diff appears to use the full index, as opposed to the `.patch` version

**Comment by SMillerDev** [comment]
@jonchang should @JakeWharton use the diff instead? Or are we just going to accept the changed hash?

**Comment by jonchang** [comment]
Yeah @JakeWharton please use the `.diff` version instead since it has the full index. From my reading of https://gitlab.com/gitlab-org/gitlab-ce/issues/5786 it seems like the full index information for a git style patch is available only via their API.

**Comment by JakeWharton** [comment]
I will update on Monday, or feel free to make a separate PR that supercedes
this one to land it sooner!

**Comment by cbracken** [comment]
I've sent #43333 which uses the `.diff` URL.

**Comment by EddieOne** [comment]
How do I fix then?

**Comment by juno** [comment]
@EddieOne 

My workaround:

- `brew edit guntls` and modify sha256 from expected value to actual value
- `brew install gnutls` again

**Comment by EddieOne** [comment]
I updated macOS to sierra and homebrew started working. Took a long time though.

**Pull request closed without merging**
