### PR TITLE
platformio 3.3.0

### PR DESCRIPTION
**Pull request by ivankravets**
# PlatformIO 3.3.0
* PlatformIO Library Registry statistics with new [pio lib stats](http://docs.platformio.org/page/userguide/lib/cmd_stats.html) command

  - Recently updated and added libraries
  - Recent and popular keywords
  - Featured libraries (today, week, month)

* List built-in libraries based on development platforms with a new [pio lib builtin](http://docs.platformio.org/page/userguide/lib/cmd_builtin.html) command
* Show detailed info about a library using [pio lib show](http://docs.platformio.org/page/userguide/lib/cmd_show.html) command ([issue #430](https://github.com/platformio/platformio-core/issues/430))
* List supported frameworks, SDKs with a new [pio platform frameworks](http://docs.platformio.org/en/latest/userguide/platforms/cmd_frameworks.htmll) command
* Visual Studio Code extension for PlatformIO ([issue #619](https://github.com/platformio/platformio-core/issues/619))
* Added new options ``--no-reset``, ``--monitor-rts`` and ``--monitor-dtr`` to [pio test](http://docs.platformio.org/en/latest/userguide/cmd_test.html) command (allows to avoid automatic board's auto-reset when gathering test results)
* Added support for templated methods in ``*.ino to *.cpp`` converter ([pull #858](https://github.com/platformio/platformio-core/pull/858))
* Package version as "Repository URL" in manifest of development version (``"version": "https://github.com/user/repo.git"``)
* Produce less noisy output when ``-s/--silent`` options are used for [platformio init](http://docs.platformio.org/page/userguide/cmd_init.html) and [platformio run](http://docs.platformio.org/page/userguide/cmd_run.html) commands ([issue #850](https://github.com/platformio/platformio-core/issues/850))
* Use C++11 by default for CLion IDE based projects ([pull #873](https://github.com/platformio/platformio-core/pull/873))
* Escape project path when Glob matching is used
* Do not overwrite project configuration variables when system environment variables are set
* Handle dependencies when installing non-registry package/library (VCS, archive, local folder) ([issue #913](https://github.com/platformio/platformio-core/issues/913))
* Fixed package installing with VCS branch for Python 2.7.3 ([issue #885](https://github.com/platformio/platformio-core/issues/885))

-------

* Development platform [Atmel AVR](https://github.com/platformio/platform-atmelavr)

  + New boards: EnviroDIY Mayfly, The Things Uno, SparkFun Qduino Mini, SparkFun ATmega128RFA1 Dev Board, SparkFun Serial 7-Segment Display, Generic ATTiny2313 and ATTiny4313
  + Set fuse bits with new target named ``fuses`` ([issue #865](https://github.com/platformio/platformio-core/issues/865))
  + Updated Arduino Core to 1.6.17
  + Fixed ISO C99 warning for EnviroDIY Mayfly board
  + Fixed firmware uploading to Arduino Leonardo

* Development platform [Atmel SAM](https://github.com/platformio/platform-atmelsam)

  + Added support for Adafruit Circuit Playground Express, Arduino MKRZero, Atmel ATSAMW25-XPRO boards
  + Added support for ARM mbed events library
  + Updated ARM mbed OS to 5.3.6/rev137
  + Updated Arduino SAM & SAMD Core to 1.6.11

* Development platform [Espressif 32](https://github.com/platformio/platform-espressif32)

  + Added support for Simba & Pumbaa Frameworks
  + Added new boards: Node32s, Hornbill ESP32 Dev, Hornbill ESP32 Minim
  + Updated Arduino Core
  + Updated ESP-IDF framework to the latest v2.0 Release Candidate 1
  + New ESP IDF examples: BLE, Coap Server, Peripherals UART, Storage SDCard

* Development platform [Freescale Kinetis](https://github.com/platformio/platform-freescalekinetis)

  + Added support for ARM mbed events library
  + Updated ARM mbed OS to 5.3.6/rev137

* Development platform [Lattice iCE40](https://github.com/platformio/platform-lattice_ice40)

  + Improved path management for Windows
  + Custom uploader using ``$UPLOAD`` build variable ([issue #6](https://github.com/platformio/platform-lattice_ice40/issues/6))
  + Updated toolchain-icestorm to 1.10.0 (added -C option to "time" target)
  + Updated toolchain-iverilog to 1.1.0  (loaed all vlib/\*.v files in "iverilog" builder)

* Development platform [Linux ARM](https://github.com/platformio/platform-linux_arm)

  + Added support for Samsung ARTIK boards (520, 530, 710, 1020) and ARTIK SDK ([issue #353](https://github.com/platformio/platformio-core/issues/353))

* Development platform [Nordic nRF51](https://github.com/platformio/platform-nordicnrf51)

  + Added support for ARM mbed events library
  + Updated ARM mbed OS to 5.3.6/rev137

* Development platform [NXP LPC](https://github.com/platformio/platform-nxplpc)

  + Added support for LPCXpresso4337 and y5 LPC11U35 mbug boards
  + Added support for ARM mbed events library
  + Updated ARM mbed OS to 5.3.6/rev137

* Development platform [Silicon Labs EFM32](https://github.com/platformio/platform-siliconlabsefm32)

  + Added support for ARM mbed events library
  + Updated ARM mbed OS to 5.3.6/rev137

* Development platform [ST STM32](https://github.com/platformio/platform-ststm32)

  + Added support for new boards: Espotel LoRa Module, NAMote72, MTS Dragonfly, ST Nucleo F303ZE, u-blox EVK-ODIN-W2, MultiTech xDot
  + Added support for ARM mbed events library
  + Updated ARM mbed OS to 5.3.6/rev137

* Development platform [Teensy](https://github.com/platformio/platform-teensy)

  + Added support for ARM mbed events library
  + Updated ARM mbed OS to 5.3.6/rev137
  + Updated Arduino Core to v1.35

* Development platform [TI TIVA](https://github.com/platformio/platform-titiva)

  + Updated Energia Core to 1.0.2

### CODE REVIEW

**Comment by fxcoudert** [comment]
Tests failed with:

```
  File "/usr/local/Cellar/platformio/3.3.0/bin/platformio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/platformio/3.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/Cellar/platformio/3.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/platformio/3.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/platformio/3.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/platformio/3.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/platformio/3.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'arrow<1' distribution was not found and is required by platformio
```

**Comment by ivankravets** [comment]
@fxcoudert How to re-start task for Jenkins?

Thanks!

**Comment by fxcoudert** [comment]
```
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/platformio.rb ==
C: 22:  1: Trailing whitespace detected.
```

**Comment by ivankravets** [comment]
Thanks, please sorry for these fixes :(

**Comment by fxcoudert** [comment]
Thanks @ivankravets for contributing this pull request!

**Pull request closed without merging**
