### PR TITLE
glog: use cmake to generate makefile; build shared libs

### PR DESCRIPTION
**Pull request by ahundt**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Continuing from #14379

### CODE REVIEW

**Comment by JCount** [comment]
@ahundt I somewhat brutally cleaned things up here, for which I apologize, but hopefully this can get merged soon.

**Comment by ahundt** [comment]
@JCount Actually, that's super cool! Is there a utility or tutorial that shows how to do modifications like that to the commit history while contributors remain on the commits?

**Comment by JCount** [comment]
Potentially? I just did it all by hand.

**Comment by ilovezfs** [comment]
@ahundt it's GitHub's way of showing that the Git committer and the Git author aren't the same anymore. So if @JCount modifies your commits and force pushes to your branch, then it shows up with the double icon thingy.

**Comment by ahundt** [comment]
Ah cool, that led me to find this neat utility. https://github.com/A-Helberg/pair-up

Anyway, everything look ok with the PR now?

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @ahundt! Shipped. Note that you will keep showing up as a "first time contributor" unless you harmonize the account from which you open PRs and the account from which you're committing. Right now the former is @ahundt and the latter is @athundt

**Pull request closed without merging**
