### PR TITLE
fauna-shell: avoid stalling CI runs

### PR DESCRIPTION
**Pull request by carlocab**
Linux CI seems to get stuck testing this formula (e.g. #89459, #89857). Let's
avoid the part of the test that gets stuck for now.

### CODE REVIEW

**Comment by carlocab** [comment]
@Homebrew/linux, better suggestions welcome.

**Comment by Bo98** [comment]
Does it happen locally? What is the process tree like? Is something detached?

**Comment by carlocab** [comment]
Ah, yes I can. It repeatedly produces
```
Endpoint Key: sh: 1: read: Illegal option -s
```
Looks like there's non-portable shell code somewhere there.

**Comment by Bo98** [comment]
Upstream issue: https://github.com/jdxcode/password-prompt/issues/12

Changing `TERM` might be a workaround to avoid the buggy code, though it should probably be fixed properly.

**Comment by iMichka** [comment]
If it uses `password-prompt`, that dependency looks "dead", as the maintainer does not use his library anymore, and there were no new commits since 1 year.
We might open an upstream issue at https://github.com/fauna/fauna-shell too.

**Comment by carlocab** [comment]
I wonder if we can depend on `bash` on Linux and replace the `sh` references with `bash` while we're working out a proper fix. Either that or just skip the tests as done here, since we'll probably need a quicker fix for CI.

I'm also confused as to how a bottle got built previously. Were the tests added after then?

**Comment by iMichka** [comment]
I'm fine to skip the test if:
- we open an upstream issue
- add the link as comment, so that it's easy to see if it's fixed later on

**Comment by carlocab** [comment]
> * we open an upstream issue

Which upstream, though? `password-prompt` looks like a recursive dependency of `fauna-shell`.

**Comment by carlocab** [comment]
Merging this later today since this is needed to unblock other PRs (e.g. #91712; it also requires manual intervention for others). We can add comments, etc separately.

**Review by iMichka — APPROVED** [review]

**Pull request merged**
