### PR TITLE
kobalt 0.931

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
Congrats on PR #10000 🎉

**Comment by JCount** [comment]
🎊 🎆

**Comment by ilovezfs** [comment]
immortalized in the commit subject with the squash-rebase button! :100: * :100:

**Comment by MikeMcQuaid** [comment]
```
                                                                                  ,---,  
                                                                               ,`--.' |  
     ,---,     ,----..                ,----..        ,----..        ,----..    |   :  :  
  ,`--.' |    /   /   \              /   /   \      /   /   \      /   /   \   '   '  ;  
 /    /  :   /   .     :            /   .     :    /   .     :    /   .     :  |   |  |  
:    |.' '  .   /   ;.  \          .   /   ;.  \  .   /   ;.  \  .   /   ;.  \ '   :  ;  
`----':  | .   ;   /  ` ;         .   ;   /  ` ; .   ;   /  ` ; .   ;   /  ` ; |   |  '  
   '   ' ; ;   |  ; \ ; |         ;   |  ; \ ; | ;   |  ; \ ; | ;   |  ; \ ; | '   :  |  
   |   | | |   :  | ; | '         |   :  | ; | ' |   :  | ; | ' |   :  | ; | ' ;   |  ;  
   '   : ; .   |  ' ' ' :         .   |  ' ' ' : .   |  ' ' ' : .   |  ' ' ' : `---'. |  
   |   | ' '   ;  \; /  |         '   ;  \; /  | '   ;  \; /  | '   ;  \; /  |  `--..`;  
   '   : |  \   \  ',  /    ___    \   \  ',  /   \   \  ',  /   \   \  ',  /  .--,_     
   ;   |.'   ;   :    /    /  .\    ;   :    /     ;   :    /     ;   :    /   |    |`.  
   '---'      \   \ .'     \_ ; |    \   \ .'       \   \ .'       \   \ .'    `-- -`, ; 
               `---`       /  ,"      `---`          `---`          `---`        '---`"  
                          '--'                                                                                                 
```

**Pull request merged**
