### PR TITLE
mysql 5.7.18

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
Marked as a failure but no actual build logs, so I presume CI went 💀 instead of the PR.

**Comment by ilovezfs** [comment]
Yes, I deleted the entire queue when it decided to have 200 jobs lined up all of sudden.

**Comment by DomT4** [comment]
Oh, _fun_.

**Comment by ilovezfs** [comment]
Off to the races https://bot.brew.sh/job/Homebrew/job/homebrew-core/job/PR-12467/2/

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:crown:

**Pull request closed without merging**
