### PR TITLE
apr-util: fix opportunistic linking to postgres

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by fxcoudert** [comment]
Looks like `apib` needs a revision bump

**Comment by SMillerDev** [comment]
apib still seems to be failing.

**Comment by fxcoudert** [comment]
```
checking /usr/include/apr-1/apr_general.h usability... no
checking /usr/include/apr-1/apr_general.h presence... no
checking for /usr/include/apr-1/apr_general.h... no
checking /usr/include/apr-1.0/apr_general.h usability... no
checking /usr/include/apr-1.0/apr_general.h presence... no
checking for /usr/include/apr-1.0/apr_general.h... no
```

and

```
In file included from apib_lines.c:17:
./apib_common.h:23:10: fatal error: 'apr_file_io.h' file not found
#include <apr_file_io.h>
         ^~~~~~~~~~~~~~~
```

Yet these files are part of the macOS SDK:

```
$ ls /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/apr-1 
apr.h                apr_errno.h          apr_ldap_init.h      apr_poll.h           apr_signal.h         apr_uri.h
apr_allocator.h      apr_escape.h         apr_ldap_option.h    apr_pools.h          apr_skiplist.h       apr_user.h
apr_anylock.h        apr_file_info.h      apr_ldap_rebind.h    apr_portable.h       apr_strings.h        apr_uuid.h
apr_atomic.h         apr_file_io.h        apr_ldap_url.h       apr_proc_mutex.h     apr_strmatch.h       apr_version.h
apr_base64.h         apr_fnmatch.h        apr_lib.h            apr_queue.h          apr_support.h        apr_want.h
apr_buckets.h        apr_general.h        apr_md4.h            apr_random.h         apr_tables.h         apr_xlate.h
apr_crypto.h         apr_getopt.h         apr_md5.h            apr_reslist.h        apr_thread_cond.h    apr_xml.h
apr_date.h           apr_global_mutex.h   apr_memcache.h       apr_ring.h           apr_thread_mutex.h   apu.h
apr_dbd.h            apr_hash.h           apr_mmap.h           apr_rmm.h            apr_thread_pool.h    apu_errno.h
apr_dbm.h            apr_hooks.h          apr_network_io.h     apr_sdbm.h           apr_thread_proc.h    apu_version.h
apr_dso.h            apr_inherit.h        apr_optional.h       apr_sha1.h           apr_thread_rwlock.h  apu_want.h
apr_env.h            apr_ldap.h           apr_optional_hooks.h apr_shm.h            apr_time.h
```

**Comment by fxcoudert** [comment]
- Force `apib` to find and link against our own `apr` and `apr-util`, in all cases
- Fix the detection of `libcrypto` to be compatible with OpenSSL 1.1

**Pull request closed without merging**
