### PR TITLE
rgbds 0.5.2

### PR DESCRIPTION
**Pull request by ISSOtm**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Also adds the new Bash completions!

(This is my 3<sup>rd</sup> PR to bump t his version, hopefully I did it right first try this time? ^^')

### CODE REVIEW

**Comment by ISSOtm** [comment]
Woops, forgot to pass `-L` to `curl`, and I ended up using the redirection page's SHA256 >_<'

**Review by carlocab — APPROVED** [review]
Thanks @ISSOtm!

Try `brew bump-formula-pr --version=0.5.2 rgbds` next time to make it automatic (provided you've set up an authentication method for GitHub with `git`). You can always amend the commit it creates with further changes.

**Comment by ISSOtm** [comment]
> Try `brew bump-formula-pr --version=0.5.2 rgbds` next time to make it automatic (provided you've set up an authentication method for GitHub with `git`). You can always amend the commit it creates with further changes.

Yeah, sorry, I don't use `brew`, I'm just acting for some of my users who do ^^'

**Comment by carlocab** [comment]
Ah, I see. In that case, you might be interested in https://github.com/dawidd6/action-homebrew-bump-formula to get CI to do this for you automatically.

**Comment by ISSOtm** [comment]
I considered this earlier, but it might be better to do it manually, since manual changes may be necessary? (E.g. dependency changes?) Idk, OTOH it'd help avoid blunders like the above.

**Pull request closed without merging**
