### PR TITLE
sonarqube 6.1

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by ilovezfs** [comment]
Jenkins error is
```
==> brew install --verbose sonarqube
==> brew audit sonarqube
==> FAILED
Error: 1 problem in 1 formula
sonarqube:
  * The installation was broken.
    Broken dylib links found:
      /usr/lib/libgcc_s_ppc64.1.dylib
```

**Comment by MikeMcQuaid** [comment]
@ilovezfs We've been ignoring that so far because it's a universal linkage issue but I'm open to approaches to fixing it.

**Comment by ilovezfs** [comment]
If it's a bug a user will never see, then ...

**Comment by Godin** [comment]
@ilovezfs This doesn't affect users in any way. The full story was discussed in https://github.com/Homebrew/homebrew-core/pull/3613 Unfortunately I had no time to work on this in upstreams.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
