### PR TITLE
Removing awscli.

### PR DESCRIPTION
**Pull request by lazzurs**
Removing awscli as the new version has moved this from being a python
package to a macOS pkg distributed by AWS with bundled python and app
the dependencies it needs.

A new cask has been created in homebrew/homebrew-cask#76967 and this
should only be merged once that PR has been accepted.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> A new cask has been created in [Homebrew/homebrew-cask#76967](https://github.com/Homebrew/homebrew-cask/pull/76967) and this
> should only be merged once that PR has been accepted.

On the contrary, the cask will only be accepted if it’s determined there’s no way to keep this as a formula. The outcome of this PR will determine the outcome of https://github.com/Homebrew/homebrew-cask/pull/76967.

Unrelated tip: use `x` in checklists (no spaces inside the brackets) and [Github will make them clickable](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments).

**Comment by SMillerDev** [comment]
Is the new cli no longer open source?

**Comment by lazzurs** [comment]
The new CLI is open source and it is on the v2 branch of the current repo. 

As said above AWS have changed the way they are distributing the module away from being a python package to now being an operating system package (for macOS a .pkg file) that contains python and all the other dependencies. 

This change reflects their change in distribution.

**Comment by fxcoudert** [comment]
If the new CLI is open source and can be installed from source, we should do that, rather than ship a binary. Whether upstream ships a binary themselves is irrelevant.

**Comment by MikeMcQuaid** [comment]
> This change reflects their change in distribution.

That they change how this is distributed does not necessarily mean we will or need to do so. We would prefer to not break our users' workflows and a CLI being open source application means we should try to keep it as a formula if at all possible.

**Comment by MikeMcQuaid** [comment]
Oops, sorry @fxcoudert!

**Comment by SMillerDev** [comment]
If it's still a cli and still open source homebrew rules dictate that it should just be a formula.

**Comment by lazzurs** [comment]
Fixed by  #50083

**Pull request closed without merging**
