### PR TITLE
terraform 0.9.0

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Testsuite failure:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x168814f]

goroutine 1 [running]:
go.(*struct { github.com/hashicorp/terraform/vendor/github.com/hashicorp/consul/testutil.TestingT }).Fatal(0xc4201febb0, 0xc4201fec20, 0x1, 0x1)
	<autogenerated>:2 +0x3f
github.com/hashicorp/terraform/vendor/github.com/hashicorp/consul/testutil.NewTestServerConfig(0x1bdfb00, 0xc4201febb0, 0x1840900, 0x0)
	/private/tmp/terraform-20170315-8122-1seqqgz/terraform-0.9.0/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/consul/testutil/server.go:170 +0x11b
github.com/hashicorp/terraform/builtin/providers/consul.TestMain(0xc4201bff20)
	/private/tmp/terraform-20170315-8122-1seqqgz/terraform-0.9.0/src/github.com/hashicorp/terraform/builtin/providers/consul/resource_provider_test.go:52 +0x71
main.main()
	github.com/hashicorp/terraform/builtin/providers/consul/_test/_testmain.go:74 +0xf7
FAIL	github.com/hashicorp/terraform/builtin/providers/consul	0.022s
```

**Comment by cblecker** [comment]
Following up with upstream.

**Comment by cblecker** [comment]
@fxcoudert New commit pushed including the upstream patch to let the tests pass. I've linked to the upstream issue.

**Comment by dunn** [comment]
Great work, thanks! Merged as 96a7e51052faf1e062f64377a79f34416a5d27ab.

**Pull request closed without merging**
