### PR TITLE
aspectj: fix description.

### PR DESCRIPTION
**Pull request by kpearson**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by neutric** [comment]
@kpearson Thanks for the description tweak! Would you like to update this to the [current release](https://eclipse.org/aspectj/doc/released/README-1810.html)?

**Comment by kpearson** [comment]
@neutric Yes I would like to update the version.

**Comment by neutric** [comment]
@kpearson Try `https://www.eclipse.org/downloads/download.php?file=/tools/aspectj/aspectj-1.8.10.jar&r=1`.

**Comment by kpearson** [comment]
@neutric Can you tell me what your mean try `https://www.eclipse.org/downloads/download.php?file=/tools/aspectj/aspectj-1.8.10.jar&r=1`?

When I swapped out the url with the one you suggested the download failed on my machine. However, it works without the additional query param `r=1`.

Sorry for the extra work. I want to get this right.

> My system
MacOS: 10.12.3
Ruby: 2.2.3p173

**Comment by neutric** [comment]
@BrewTestBot test this please

**Comment by neutric** [comment]
You are right, for some reason I thought that the URL pattern has changed when it didn't. Sorry for that! I undid the damage I've caused. Now we just have to wait for CI to be working again.

**Comment by neutric** [comment]
@BrewTestBot test this please

**Comment by neutric** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
The URL doesn't download for me, as the audit says:

`  * Stable: The URL https://www.eclipse.org/downloads/download.php?file=/tools/aspectj/aspectj-1.8.10.jar is not reachable`

It leads to a mirror chooser, and thus fails from the command line.

**Comment by fxcoudert** [comment]
Thanks @kpearson for the pull request!

**Comment by neutric** [comment]
Thanks for figuring that tricky one out @fxcoudert!

**Comment by fxcoudert** [comment]
It was @ilovezfs who did it :) I'm just playing Dr. Watson here

**Pull request merged**
