### PR TITLE
nwchem 7.2.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by edoapra** [comment]
to fix the current github actions failures, you might want to change
https://github.com/p-linnane/homebrew-core/blob/0894727b5fe10ce3e742866c65c339c69fb93599/Formula/nwchem.rb#L61
`      system "make", "nwchem_config", "NWCHEM_MODULES=all python"`
to
`      system "make", "nwchem_config", "NWCHEM_MODULES=all python", "USE_MPI=Y"`

**Comment by edoapra** [comment]
I would suggest the following to increase hardware compatibility, too
`      ENV["USE_HWOPT"] = "n"`

**Comment by p-linnane** [comment]
@edoapra I see you are the author of this software, I didn't realize you were also a Homebrew contributor. I'm going to close this PR and let you open your own so that you can make modifications as you see fit without waiting on me.

**Comment by edoapra** [comment]
Sure. I thought we were pretty close at getting the formula working.

**Comment by p-linnane** [comment]
Agreed, but in this case I'd prefer to let someone who knows the software take over 😄

**Comment by p-linnane** [comment]
```
brew test --verbose nwchem
==> Testing nwchem
==> ./runtests.mpi.unix procs 0 dft_he2+ pyqa3 prop_mep_gcube pspw tddft_h2o tce_n2
mkdir: /opt/homebrew/Cellar/nwchem/7.2.0/share/nwchem/QA/testoutputs: Operation not permitted
failed: cannot make directory /opt/homebrew/Cellar/nwchem/7.2.0/share/nwchem/QA/testoutputs
Error: nwchem: failed
```

**Comment by p-linnane** [comment]
@edoapra I took another pass at this since I had time. I've got the syntax of the formula working, and it builds and runs the tests, but there are some actual tests failures. There are the tests that fail: `dft_he2+`, `prop_mep_gcube`, `tddft_h2o`. Can you provide some guidance here?

**Comment by edoapra** [comment]
This could be the change needed to fix the test failures.
Change
`ENV["SCALAPACK_SIZE"] = "8"`
to
`ENV["SCALAPACK_SIZE"] = "4"`

**Comment by edoapra** [comment]
I would suggest a few more changes (including the SCALAPACK_SIZE) in order to increase the functionality of the NWChem buidl
```
--- org.rb      2023-03-11 00:17:56
+++ Formula/nwchem.rb   2023-03-11 00:15:02
@@ -56,15 +56,17 @@
       ENV["LAPACK_LIB"] = "-L#{Formula["openblas"].opt_lib} -lopenblas"
       ENV["BLAS_SIZE"] = "4"
       ENV["SCALAPACK"] = "-L#{Formula["scalapack"].opt_prefix}/lib -lscalapack"
-      ENV["SCALAPACK_SIZE"] = "8"
+      ENV["SCALAPACK_SIZE"] = "4"
       ENV["USE_64TO32"] = "y"
-      ENV["USE_HWOPT"] = "n"
+      ENV["LIBXC_LIB"] = "#{Formula["libxc"].opt_prefix}/lib"
+      ENV["LIBXC_INCLUDE"] = "#{Formula["libxc"].opt_prefix}/include"
       os = OS.mac? ? "MACX64" : "LINUX64"
-      system "make", "nwchem_config", "NWCHEM_MODULES=all python", "USE_MPI=Y"
+      system "make", "nwchem_config", "NWCHEM_MODULES=all python gwmol", "USE_MPI=Y"
       system "make", "NWCHEM_TARGET=#{os}", "USE_MPI=Y"
 
       bin.install "../bin/#{os}/nwchem"
       pkgshare.install "basis/libraries"
+      pkgshare.install "basis/libraries.bse"
       pkgshare.install "nwpw/libraryps"
       pkgshare.install Dir["data/*"]
     end
```

**Review by edoapra — COMMENTED** [review]
Looks good to me

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
