### PR TITLE
akamai 1.4.2

### PR DESCRIPTION
**Pull request by robertolopezlopez**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by robertolopezlopez** [comment]
@branchvincent , do you have any idea why [the tests](https://github.com/Homebrew/homebrew-core/runs/6384361764?check_suite_focus=true) have been stuck for over 8h already?

> Requested labels: 12-arm64-2305739779-1
> Job defined at: Homebrew/homebrew-core/.github/workflows/tests.yml@refs/pull/101280/merge
> Waiting for a runner to pick up this job...

**Comment by robertolopezlopez** [comment]
> @branchvincent , do you have any idea why [the tests](https://github.com/Homebrew/homebrew-core/runs/6384361764?check_suite_focus=true) have been stuck for over 8h already?
> 
> > Requested labels: 12-arm64-2305739779-1
> > Job defined at: Homebrew/homebrew-core/.github/workflows/tests.yml@refs/pull/101280/merge
> > Waiting for a runner to pick up this job...

just asking because I have seen on other PRs that you have been stopping these tests (rancher-cli, webpack, jenkins) and we would like to know what's going on today :-) Thanks 👍

**Comment by branchvincent** [comment]
Thanks for the ping @robertolopezlopez, we just have some hiccups today with experimental CI changes. It currently requires manual intervention, so I'll get this merged for you

**Review by branchv — APPROVED** [review]

**Comment by branchvincent** [comment]
you too 😄

**Pull request closed without merging**
