### PR TITLE
clojure 1.9.0.273

### PR DESCRIPTION
**Pull request by puredanger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by puredanger** [comment]
I hate to ask this, but we are in the process of releasing Clojure 1.9, and it would be great if this was merged expeditiously if possible. Thanks!

**Comment by ilovezfs** [comment]
bit of a back log because we just upgraded the base image but I'll try to get this :green_apple: ASAP

**Comment by puredanger** [comment]
Understood, thanks for your efforts!

**Comment by ilovezfs** [comment]
Should we add `ENV["TERM"] = "xterm"` to the test block to prevent
```
clojure: warning: Your terminal 'dumb' is not fully functional, expect some problems.
```

**Comment by puredanger** [comment]
Can I add that on the next version? Happy to do so...

**Comment by puredanger** [comment]
bump

**Comment by ilovezfs** [comment]
Thanks @puredanger! Shipped.

**Comment by puredanger** [comment]
Thanks!

**Pull request merged**
