### PR TITLE
automerge: run on failed `merge_group` events

### LINKED ISSUE #172999: Make "Merge when ready" button always "work"
### What were you trying to do (and why)?

It would be nice if the Homebrew/homebrew-core "Merge when ready" button always "just worked" i.e. it would intelligently know to push bottle commits to the PR if necessary and then attempt another merge later.

### What happened (include all command output)?

People click the "merge when ready" button and it does the wrong thing e.g. not merge, not include bottles, etc.

### What did you expect to happen?

The "merge when ready" button always merges when ready.

### Step-by-step reproduction instructions (by running `brew` commands)

- Press "merge when ready"
- Sometimes: it does not do what you want/expect

### PR DESCRIPTION
**Pull request by carlocab**
Closes #172999 ~~(maybe)~~

### CODE REVIEW

**Comment by carlocab** [comment]
This depends a lot on `Homebrew/actions/find-related-workflow-run-id`, and whether it can find the associated PR based on the `merge_group` run.

**Review by ZhongRuoyu — APPROVED** [review]
So the logic is: click "merge when ready", merge group CI fails, then automerge is run where the real merge happens?

The "merge group CI fails" part could be a bit counterintuitive, but I guess this does work provided merge group CI fails in appropriate cases.

**Comment by MikeMcQuaid** [comment]
> The "merge group CI fails" part could be a bit counterintuitive

I think this is probably unavoidable given that:
- you cannot commit to a PR inside a merge group itself and have those commits merged as part of the same merge group
- the hook for the "merge when ready" button is the merge group event

I'd be happy with this as a solution 👍🏻

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me! Worth a try, thanks for this @carlocab!

**Comment by Bo98** [comment]
Is there a risk of an infinite loop here?

**Comment by carlocab** [comment]
> Is there a risk of an infinite loop here?

Possibly, yes. It seemed like a possibility to me as I was writing this down, but I haven't yet worked out definitively either way.

**Comment by MikeMcQuaid** [comment]
@carlocab could consider applying a label at some stage as a marker to avoid this?

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
I had to rework this.

> This depends a lot on `Homebrew/actions/find-related-workflow-run-id`, and whether it can find the associated PR based on the `merge_group` run.

Unfortunately, `find-related-workflow-run-id` cannot find the associated PR based on the `merge_group` run.

This meant I had to write a new GraphQL query that does find the associated PR. I've also written another query that checks the PR timeline for removed-from-merge-queue events so that we can exit with an error when we see too many of those (in order to avoid infinite loops).

**Comment by carlocab** [comment]
> @carlocab could consider applying a label at some stage as a marker to avoid this?

I took the more direct approach of checking the PR timeline for too many removed-from-merge-queue events.

**Review by MikeMcQuaid — APPROVED** [review]
Great work @carlocab!

**Pull request merged**
