### PR TITLE
xpipe 2.1

### PR DESCRIPTION
**Pull request by jschauma**
This is a trivial version upgrade.  I'm guessing the bottle sums are updated automatically?

### CODE REVIEW

**Comment by carlocab** [comment]
For future reference:

Please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings.

For new formulae:

> At Homebrew, we like to put the name of the formula up front like so: `foobar 7.3 (new formula)`.

For existing formulae:

> The preferred commit message format for simple version updates is `foobar 7.3` and for fixes is `foobar: fix flibble matrix.`.

Refer to the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit) for more details. Also, when making further changes to your pull request, use the following guidelines to make sure that @BrewTestBot can merge your commits:

> - One formula per commit; one commit per formula.
> - Keep merge commits out of the pull request.

**Comment by chenrui333** [comment]
```
  ==> make PREFIX=/home/linuxbrew/.linuxbrew/Cellar/xpipe/2.0 install
  gcc-11 -g -Wall -Werror -Wextra -c src/xpipe.c -o src/xpipe.o
  Please install 'libbsd' and 'libbsd-devel'.
  make: *** [Makefile:28: configure] Error 1
  make: *** Waiting for unfinished jobs....
  src/xpipe.c:43:12: fatal error: bsd/string.h: No such file or directory
     43 | #  include <bsd/string.h>
        |            ^~~~~~~~~~~~~~
  compilation terminated.
  make: *** [Makefile:24: src/xpipe.o] Error 1
```

**Comment by jschauma** [comment]
> Please use the preferred commit-message style for homebrew/core.

Will try to remember that!

**Comment by jschauma** [comment]
Re the failing ubuntu check: I suspect that on some linux systems you need to install 'libbsd-devel' (or equivalent) in addition to 'libbsd'.  Unfortunately that may be inconsistent across distributions.

**Comment by carlocab** [comment]
The `libbsd` formula should be both `libbsd` and `libbsd-devel`.

**Comment by jschauma** [comment]
> The `libbsd` formula should be both `libbsd` and `libbsd-devel`.

Ah, I see. Cool, thanks!

**Comment by jschauma** [comment]
I don't understand why the ubuntu build fails.

https://github.com/Homebrew/homebrew-core/actions/runs/3071661795/jobs/4962581119 shows it running

```
 ==> make PREFIX=/home/linuxbrew/.linuxbrew/Cellar/xpipe/2.1 install
  gcc-11 -Wall -Werror -Wextra -I/home/linuxbrew/.linuxbrew/Cellar/xpipe/2.1/include -c src/xpipe.c -o src/xpipe.o
  Please install 'libbsd' and 'libbsd-devel'.
  make: *** [Makefile:29: configure] Error 1
  make: *** Waiting for unfinished jobs....
```

but that order makes no sense.  'make' should fail _before_ invoking gcc if it can't find the include, and I've confirmed to be the case on Ubuntu when extracting the tarball and running 'make'.  Here, it looks like 'make' is not following the order of dependencies and executes the compilation step prior to the configure step.  Being unable to reproduce this, I don't know what's going on here.

**Comment by danielnachun** [comment]
I pushed a Linux fix.  This was a very weird one - it assumes that the `libbsd` headers are in the same folder as the prefix for the `xpipe`, but on Homebrew this happens not to be true.  The solution here is to just `inreplace` the include path to `libbsd` with the one from the `libbsd` formula.

**Comment by jschauma** [comment]
Oh, cool, thanks - I would never have figured that out.  (Still curious about the execution order of 'make' in the example, but that's a separate issue that won't apply if it can indeed find the header. :-)

**Review by carlocab — APPROVED** [review]

**Comment by danielnachun** [comment]
> Oh, cool, thanks - I would never have figured that out. (Still curious about the execution order of 'make' in the example, but that's a separate issue that won't apply if it can indeed find the header. :-)

It's possible that this is because our `make` by default runs parallel jobs.  You could test this on a multi-core system by running `make -j NUM_CORES` with at least 4 cores (I think that's how many our Linux runner has) to see if it's still out of order.

**Pull request closed without merging**
