### PR TITLE
zenith: use `IO#winsize` instead of `stty`

### PR DESCRIPTION
**Pull request by vladimyr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you see if you can write a rubocop stylecheck for this? I think it's a good idea, but I would like to see it enforced by brew.

**Comment by fxcoudert** [comment]
@SMillerDev  Does something that occurs 7 times out of 5000 formulas warrant a specific audit/stylecheck?

**Comment by SMillerDev** [comment]
Seeing how often people seem to copy parts of a formula from 2015 into a new submission I think it's better to let brew already warn them.

**Comment by vladimyr** [comment]
> Seeing how often people seem to copy parts of a formula from 2015 into a new submission I think it's better to let brew already warn them.

Knowing how many times I did that I could not agree more 🙇

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
