### PR TITLE
bumpversion: deprecate

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Can look into adding the new successor `bump-my-version` as separate formula. Hopefully it survives better than prior versions.

### CODE REVIEW

**Comment by stefanb** [comment]
https://github.com/c4urself/bump2version?tab=readme-ov-file#bump2version
mentions https://github.com/callowayproject/bump-my-version as a successor

**Comment by cho-m** [comment]
> https://github.com/c4urself/bump2version?tab=readme-ov-file#bump2version mentions https://github.com/callowayproject/bump-my-version as a maintained successor

Yes. I did add a comment on that. Will look into a separate formula in different PR as it is now under a new name.

**Comment by stefanb** [comment]
Should this formula mention the successor formula?

**Review by carlocab — APPROVED** [review]
Happy for deprecation message improvement in a separate PR.

**Comment by carlocab** [comment]
I opened https://github.com/Homebrew/brew/issues/18294 to track this more generally.

**Pull request merged**
