### PR TITLE
fontforge and mftrace: migrate to python@3.8

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
> 2020-05-09T11:31:23.5211040Z [34m==>[0m [1mbrew audit --skip-style fontforge --online[0m
2020-05-09T11:31:47.3203370Z [31m==>[0m [1m[31mFAILED[0m[0m
2020-05-09T11:31:47.3204870Z [31mError:[0m 1 problem in 1 formula detected
2020-05-09T11:31:47.3205240Z fontforge:
2020-05-09T11:31:47.3205480Z   * Files were found with references to the Homebrew shims directory.
2020-05-09T11:31:47.3205730Z     The offending files are:
2020-05-09T11:31:47.3205910Z       bin/ttf2eps
2020-05-09T11:31:47.3206760Z       bin/acorn2sfd

**Comment by iMichka** [comment]
```
2020-05-14T08:58:40.0600150Z [34m==>[0m [1m/usr/local/Cellar/fontforge/20190801_2/bin/fontforge -version[0m
2020-05-14T08:58:40.0600400Z dyld: Symbol not found: _PyBool_Type
2020-05-14T08:58:40.0600820Z   Referenced from: /usr/local/Cellar/fontforge/20190801_2/lib/libfontforge.3.dylib
2020-05-14T08:58:40.0601190Z   Expected in: flat namespace
2020-05-14T08:58:40.0601470Z  in /usr/local/Cellar/fontforge/20190801_2/lib/libfontforge.3.dylib
```

**Comment by iMichka** [comment]
```
2020-05-14T08:58:40.0598220Z /usr/bin/sandbox-exec -f /private/tmp/homebrew20200514-5098-jmc64d.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fontforge.rb --verbose
2020-05-14T08:58:40.0600150Z [34m==>[0m [1m/usr/local/Cellar/fontforge/20190801_2/bin/fontforge -version[0m
2020-05-14T08:58:40.0600400Z dyld: Symbol not found: _PyBool_Type
2020-05-14T08:58:40.0600820Z   Referenced from: /usr/local/Cellar/fontforge/20190801_2/lib/libfontforge.3.dylib
2020-05-14T08:58:40.0601190Z   Expected in: flat namespace
2020-05-14T08:58:40.0601470Z  in /usr/local/Cellar/fontforge/20190801_2/lib/libfontforge.3.dylib
2020-05-14T08:58:40.0602690Z [31mError:[0m fontforge: failed
2020-05-14T08:58:40.0602910Z An exception occurred within a child process:
2020-05-14T08:58:40.0604260Z   BuildError: Failed executing: /usr/local/Cellar/fontforge/20190801_2/bin/fontforge -version
```

**Comment by iMichka** [comment]
Almost there ...:
```
2020-05-19T16:49:51.8209660Z [34m==>[0m [1mbrew audit --skip-style fontforge --online[0m
2020-05-19T16:50:18.6836480Z [31m==>[0m [1m[31mFAILED[0m[0m
2020-05-19T16:50:18.6837570Z [31mError:[0m 1 problem in 1 formula detected
2020-05-19T16:50:18.6837910Z fontforge:
2020-05-19T16:50:18.6838100Z   * python modules have explicit framework links
2020-05-19T16:50:18.6838360Z     These python extension modules were linked directly to a Python
2020-05-19T16:50:18.6842550Z     framework binary. They should be linked with -undefined dynamic_lookup
2020-05-19T16:50:18.6843750Z     instead of -lpython or -framework Python.
2020-05-19T16:50:18.6844750Z       /usr/local/opt/fontforge/lib/python3.8/site-packages/fontforge.so
2020-05-19T16:50:18.6845780Z             /usr/local/opt/fontforge/lib/python3.8/site-packages/psMat.so
```

**Comment by Bo98** [comment]
That's already "patched" upstream. There was just some debate whether it was 100% fixed.

**Comment by iMichka** [comment]
I see, found the commits:
https://github.com/fontforge/fontforge/commit/c47a582ffbc3f8254f7d5f0fc5d64b7160505b09
https://github.com/fontforge/fontforge/commit/596eadba4fc8fdc4fae107fdcec3c9d6927cf50f

But also a full PR that got also merged:
https://github.com/fontforge/fontforge/pull/4258

**Pull request closed without merging**
