### PR TITLE
clang-tidy 10.0.1 (new formula)

### PR DESCRIPTION
**Pull request by SubtleMuffin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR provides formula for `clang-tidy`, a static analysis tool.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
`clang-tidy` is already provided by the `llvm` formula.

**Comment by SubtleMuffin** [comment]
> `clang-tidy` and `clang-format` are already provided by the `llvm` formula:
> 
> ```
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-10
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-apply-replacements
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-change-namespace
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-check
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-cl
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-cpp
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-doc
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-extdef-mapping
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-format
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-import-test
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-include-fixer
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-move
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-offload-bundler
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-offload-wrapper
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-query
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-refactor
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-rename
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-reorder-fields
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-scan-deps
> /usr/local/Cellar/llvm/10.0.1_1/bin/clang-tidy
> ``

I would say this formula is valuable in the following sense,
1. The LLVM formula install a lot of binaries into the system
2. What if a user would like to only lint the code and use GCC as compiler, instead of adding so many other tools?
3. What if there are compatibility issues when compiling with Brew’s LLVM instead of macOS stock compiler?
4. Since clang-format is provided as standalone binary, why can’t the clang-tidy do the same?

**Comment by alebcay** [comment]
This is not to say that this formula cannot exist; however, you must declare the conflict with `llvm` via the `conflicts_with` directive.

**Comment by gromgit** [comment]
> `clang-tidy` and `clang-format` are already provided by the `llvm` formula:

True, but `llvm` itself is keg-only, so there are no conflicts in the normal case.

**Comment by SMillerDev** [comment]
> The LLVM formula install a lot of binaries into the system

But it's keg-only so it won't interfere

> What if a user would like to only lint the code and use GCC as compiler, instead of adding so many other tools?

They can ignore the other tools. AFAIK the whole install is about the size of a large website.

> What if there are compatibility issues when compiling with Brew’s LLVM instead of macOS stock compiler?

You don't need to use brew llvm just because it's on the system.

> Since clang-format is provided as standalone binary, why can’t the clang-tidy do the same?

I'd rather get rid of clang-format. Having a lot of copies of 1 code base is bad for maintenance.

**Comment by SubtleMuffin** [comment]
Well, thanks for the discouragements. I will go ahead close this PR and distribute scripts (which do not require `brew`) to my target audiences.

> > The LLVM formula install a lot of binaries into the system
> 
> But it's keg-only so it won't interfere

So, letting the user compile LLVM infrastructure (`brew install llvm`) on their own machine (which takes more than half hour on MBP A1990, 8-core i9) and having [multi-gig disk space usage](https://stackoverflow.com/questions/57888827/how-to-make-brew-show-the-size-of-the-formula-before-installing-it), just to lint C++ code, is a **good** idea. The *sole* purpose of this formula is to use binary hosting provided by brew, install a ~30MB binary and be down with it.

> 
> > What if a user would like to only lint the code and use GCC as compiler, instead of adding so many other tools?
> 
> They can ignore the other tools. AFAIK the whole install is about the size of a large website.

So to use `clang-tidy`, the users will need to install LLVM, reconfigure their makefile and continue their works.

> 
> > What if there are compatibility issues when compiling with Brew’s LLVM instead of macOS stock compiler?
> 
> You don't need to use brew llvm just because it's on the system.

Ditto. The users will need to shadow system paths and/or reconfigure their makefile (or other build systems) to use stock compiler + clang-tidy for linting, if they have to install LLVM from brew.

> 
> > Since clang-format is provided as standalone binary, why can’t the clang-tidy do the same?
> 
> I'd rather get rid of clang-format. Having a lot of copies of 1 code base is bad for maintenance.

This is a great idea! I bet [these 64818](https://formulae.brew.sh/formula/clang-format) downloads should change their workflows to compile LLVM on their own.

**Comment by porceCodes** [comment]
> > Since clang-format is provided as standalone binary, why can’t the clang-tidy do the same?
> I'd rather get rid of clang-format. Having a lot of copies of 1 code base is bad for maintenance.

This raises an existential question about a missing package manager.
It is noteworthy how Ubuntu/Linux does about it:

```
sudo apt install clang-tidy
sudo apt install clang-format
```

**Comment by KindDragon** [comment]
@SMillerDev, hi. Can we maybe move out `clang-tools-extra` to separate dependency?

**Pull request closed without merging**
