### PR TITLE
mpw 2.6-cli-1 (update)

### PR DESCRIPTION
**Pull request by lhunath**
Also adds support for --HEAD and mpw's new toggleable feature support
for JSON configuration, XML test cases and colorized output using curses

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lhunath** [comment]
I'd like some advice on the `test do` block.  Specifically, the tarball provides an `mpw-cli-tests` script which uses the installed `mpw` binary to test several scenarios, but I don't have access to this script from the `test do` block, and was wondering what the best way is to gain access.

**Comment by lhunath** [comment]
mpw-cli-tests is:
https://github.com/Lyndir/MasterPassword/blob/master/platform-independent/cli-c/mpw-cli-tests

It essentially runs `mpw` with certain parameters and tests whether the output is as expected.

**Comment by lhunath** [comment]
I've fixed an issue and updated the `test do` to match what I expect it should do.

**Comment by lhunath** [comment]
For reference/completion, the original mpw was submitted in https://github.com/Homebrew/legacy-homebrew/pull/36046 and reviewed by @mistydemeo

**Comment by fxcoudert** [comment]
Thanks @lhunath for the pull request and comments!

**Pull request closed without merging**
