### PR TITLE
retro68 2019.8.2

### PR DESCRIPTION
**Pull request by easybe**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
Looking at the upstream project's README, I don't think we (Homebrew) would be able to distribute this:

> The Universal Interfaces used to be a free download from Apple. However, they have taken the site off-line and the license agreement does not allow redistribution, which is why it's not included in this repository. The concept of fair use might cover keeping it available for reasons of historical interest, or it might not. I am not a lawyer.

https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by easybe** [comment]
Yes, that is why they are not included in the binary. Everything that is part of the package is GPL (https://github.com/autc04/Retro68/blob/master/COPYING). Apple's code is installed in `post_install`. Ist that a no-go?

**Comment by SMillerDev** [comment]
I don't think "does not allow redistribution" cares if it's in the install or post_install block. I don't think it's allowed either way. The only option is a caveat but then we're just shipping broken software.

**Comment by easybe** [comment]
The toolchain (binaries) are not broken. Only Apple's API is missing which can be installed by calling a script after installation. I can remove that part from the Formula if necessary. I do not see how distributing a script that downloads and installs the API (which we are free to use/compile against) is illegal.

**Comment by SMillerDev** [comment]
Cause it's redistributing the file. Which the quote above says isn't allowed

**Comment by easybe** [comment]
OK. As I said I can remove that part.

**Comment by fxcoudert** [comment]
Given the complexity of the build and the license issues, I think the better solution (at least for the short term) is for you to package it in your own tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Pull request closed without merging**
