### PR TITLE
node@22 22.10.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
node@22 22.10.0 (new formula)

---

follow up #194645

### CODE REVIEW

**Comment by ianzone** [comment]
Wishing a node@lts formula 🙏

**Comment by unilynx** [comment]
> Wishing a node@lts formula 🙏

That one would have jumped from node@20 to node@22. I think ideally node@22/node@23 and soon node@24 formulas would always be present instead of just 'node', as node major version updates break a lot more than eg. a postgres major update.

(even minor node version updates cause regressions often enough)

**Comment by Stanzilla** [comment]
I would like to propose that the next time a major gets bumped, the new formula for the old version gets pushed at the same time. Otherwise you end up with people stuck on something incompatible

**Review by daeho-ro — APPROVED** [review]

**Comment by chenrui333** [comment]
> I would like to propose that the next time a major gets bumped, the new formula for the old version gets pushed at the same time. Otherwise you end up with people stuck on something incompatible

yeah, we had inconsistent practices on that, we should do it.

**Comment by chenrui333** [comment]
> Wishing a node@lts formula 🙏

there are three active node lts versions, one is current, the other two are in maintenance mode.

**Pull request merged**
