### PR TITLE
Use a multilib build of x265 so you can have both 8 and 10 bit

### PR DESCRIPTION
**Pull request by TellowKrinkle**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Previously, if you wanted a 10-bit version of x265 to use with ffmpeg, you had to recompile with `--with-16-bit`, which would *only* be a 10 bit version and wouldn't support 8-bit encodes.

This change adds support for 12-bit builds and switches to a multilib build, which allows 8, 10, and 12 bit versions of x265 to be combined into one library, removing the need to recompile every time you want to switch libraries.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for the PR. We're going to pass on this since it significantly increases the complexity of the formula, but we could consider a multilib build if it were an upstream option that we could just pass to cmake.

**Comment by ilovezfs** [comment]
@JCount says this is a good idea so reopening.

**Comment by tellowkrinkle** [comment]
One option to keep the formula complexity low is to see if we can get the multilib shell script in x265 to support custom cmake parameters, because then we could just use that instead of reimplementing it.

The only problem is that I have no idea how to get bash to pass lists of arguments, but if someone else does, that would probably work.

**Comment by JCount** [comment]
The problem with taking that approach is that the result would probably be even more fragile.

**Comment by JCount** [comment]
@tellowkrinkle This has been replaced with #19124. 

Thank you very much for this PR, though, because it definitely has helped improve Homebrew! Feel free to open more! 😄

**Pull request closed without merging**
