### PR TITLE
up 0.3.1 (new formula)

### PR DESCRIPTION
**Pull request by vickio**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vickio** [comment]
Updated to utilize `HOMEBREW_CACHE/"go_cache"`, improved test, and improved description.

**Comment by vickio** [comment]
Struggling to find a useful test that works with Jenkins.

**Review by fxcoudert — DISMISSED** [review]

**Comment by fxcoudert** [comment]
Formula looks good, but test is failing:

```
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <"error: open /dev/tty: device not configured\n"> expected to include
<"error: up requires some data piped on standard input">.
```

**Comment by vickio** [comment]
The previous test was working locally, but `up` opens `/dev/tty` pretty early, which doesn't work in with the CI environment. Looks like the updated test is passing now. It doesn't do much, but I think it's slightly better than checking the output of `--help`. `up` doesn't have a non-interactive mode.

**Comment by fxcoudert** [comment]
Agreed, I think the test is as much as we can do. Thanks @vickio for the pull request!

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
