### PR TITLE
duck 6.2.0

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@dkocher building this locally the test block is failing with
```
bash-3.2$ /usr/local/Cellar/duck/6.2.0.25806/bin/duck --download https://ftp.gnu.org/gnu/wget/wget-1.19.1.tar.gz /tmp/duck-test-20170725-23043-n1yhk3/test
Missing protocol in URI https://ftp.gnu.org/gnu/wget/wget-1.19.1.tar.gz
Try 'duck --help' for more options.
```

any idea what is wrong? maybe the test needs a tweak?

**Comment by ilovezfs** [comment]
@dkocher test has failed on CI https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5309/version=sierra/console

```
==> brew test duck --verbose
==> FAILED
Testing duck
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170725-85650-xipchv.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/duck.rb --verbose
==> /usr/local/Cellar/duck/6.2.0.25806/bin/duck --download https://ftp.gnu.org/gnu/wget/wget-1.19.1.tar.gz /tmp/duck-test-20170725-85651-1bzu76i/test

wget-1.19.1.tar.gz…wget-1.19.1.tar.gz
Login ftp.gnu.org. Login ftp.gnu.org – Azure with username and password. No login credentials could be found in the Keychain.
Storage Account Name (brew): 
Disconnecting ftp.gnu.org – Azure…


Unknown…
Error: duck: failed
```
So it looks like it thinks the https URL is ftp.

**Comment by dkocher** [comment]
Yes, this is a regression that the download will only work with `davs://…`.

**Comment by ilovezfs** [comment]
@dkocher OK. Any idea why locally I see `Missing protocol in URI` whereas on CI it has the attempt-to-use-ftp problem?

**Comment by dkocher** [comment]
@ilovezfs I am looking into it wether we want to continue supporting using the `https` scheme or fix the test.

**Comment by dkocher** [comment]
The issue is that the lookup in the protocol factory by a scheme is no longer ordered and now returns the Microsoft Azure implementation for `https://` scheme instead of the previously WebDAV implementation that would work to download the file.

I will change the test to work with a `ftp://` scheme that explicitly matches a protocol implementation as a short term fix. In the long run, we will want to explicitly map `http(s)://` to the WebDAV protocol implementation.

**Comment by fxcoudert** [comment]
Thanks @dkocher for the pull request!

**Pull request closed without merging**
