### PR TITLE
ffmpeg 3.2

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

See https://github.com/FFmpeg/FFmpeg/blob/n3.2/Changelog.
- `openh264` 1.6 support added (FFmpeg/FFmpeg@293676c); drop vendored `openh264` 1.5.
- <s>Restore the `--with-ffplay` option and deprecate `--with-sdl`/`--with-sdl2` (recently added).  Whatever backend `ffplay` uses is just an implementation detail, users should not need to know it (and most don't), and using the dependency name in the option name not only causes user confusion (especially after years of `--with-ffplay` which is the only name that makes sense), it's also a headache when upstream switches backend, as is happening with this release.</s>
- Deprecate `--with-sdl` in favor of `--with-sdl2`, and point `--with-ffplay` to `--with-sdl2` too. FFplay now uses `sdl2` as its backend.
- Drop the AAC encoding caveats specific to the FFmpeg 3.0 release. It's been out for the better part of a year and shouldn't be news anymore. Users concerned with this caveat should have migrated already.
- Sort options and optional dependencies. They're a mess and I didn't even know where to insert options and dependencies.

More revision bumps are probably necessary. Let's see what the bot has to say.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> Restore the --with-ffplay option and deprecate --with-sdl/--with-sdl2 (recently added). Whatever backend ffplay uses is just an implementation detail, users should not need to know it (and most don't), and using the dependency name in the option name not only causes user confusion (especially after years of --with-ffplay which is the only name that makes sense), it's also a headache when upstream switches backend, as is happening with this release.

This creates issues with our dependency system so until we have a `variant do` or similar in Homebrew/brew we should avoid regressing back on these.

> Drop the AAC encoding caveats specific to the FFmpeg 3.0 release. It's been out for the better part of a year and shouldn't be news anymore. Users concerned with this caveat should have migrated already.

👍

**Comment by zmwangx** [comment]
> This creates issues with our dependency system so until we have a variant do or similar in Homebrew/brew we should avoid regressing back on these.

The mistake here was deprecating `--with-ffplay` in the first place, which doesn't make sense (as an FFmpeg user I can tell you this for sure) and led to a funny stable/head split that `brew info` completely failed to account for. I myself lost `--with-ffplay` somewhere along the upgrade path which shouldn't have happened.

If you look at all the existing `deprecated_option`s, they are mostly adding a `with-` prefix or changing `enable-` to `with-` / `disable-` to `without-`. None of them changes an option from something that users can understand (`--with-ffplay`) to something that they can't (`--with-sdl2`).

Restoring `--with-ffplay` simply isn't a regression, and shouldn't cause problems for users if `deprecated_option` works as expected. If it doesn't, well, they were probably already screwed the last time (as I did), so recompiling `--with-ffplay` is the way to restore sanity.

**Comment by zmwangx** [comment]
> None of them changes an option from something that users can understand (--with-ffplay) to something that they can't (--with-sdl2).

Oh, not only that. `--with-ffplay` was deprecated in favor of `--with-sdl`, which is outdated three weeks later.

**Comment by MikeMcQuaid** [comment]
> Restoring --with-ffplay simply isn't a regression

`depends_on "sdl2" if build.with?("ffplay")` is buggy and `depends_on "sdl2" => :optional` is not so it will cause a regression.

> I myself lost --with-ffplay somewhere along the upgrade path which shouldn't have happened.

I agree this should not happen. If you can figure out how to reproduce an issue or PR would be welcome.

**Comment by zmwangx** [comment]
> depends_on "sdl2" if build.with?("ffplay") is buggy

Then fix the bug?

**Comment by zmwangx** [comment]
```
depends_on "sdl2" if build.with?("ffplay")
```

That structure is used all over the place and deprecating options doesn't work in most cases.

**Comment by MikeMcQuaid** [comment]
> That structure is used all over the place

Yes but we want to avoid it when it's possible (as it isn't always possible).

Please put it back to how it was.

**Comment by retokromer** [comment]
@zmwangx At some point it was necessary to use both `--with-sdl` and `--with-sdl2` in order to cover all situations, which is absurde.
👍 👍 👍  in favour for restoring `--with-ffplay`, which is intuitive for the user.

**Comment by zmwangx** [comment]
Deprecated `--with-ffplay` and made `--with-sdl2` the primary option. (Sorry, I tried.)

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by zmwangx** [comment]
Can someone get this merged? Thanks.

**Comment by dunn** [comment]
Done, thanks!

**Pull request closed without merging**
