### PR TITLE
abi-compliance-checker 2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
After some poking, the test spat out an error that is very enlightening: `ERROR: incorrect format of library (should be *.dylib): '/usr/local/opt/ctags/lib/readtags.o'` If `-static` is passed it gives `ERROR: incorrect format of library (should be *.a): '/usr/local/opt/ctags/lib/readtags.o'`. Apparently, if we want to keep the same basic test, we need to find a way to feed it either a *.dylib or *.a lib and associated header.

**Comment by ilovezfs** [comment]
```
diff --git a/Formula/abi-compliance-checker.rb b/Formula/abi-compliance-checker.rb
index a49eb67..e98fa91 100644
--- a/Formula/abi-compliance-checker.rb
+++ b/Formula/abi-compliance-checker.rb
@@ -23,7 +23,7 @@ class AbiComplianceChecker < Formula
     (testpath/"test.xml").write <<-EOS.undent
       <version>1.0</version>
       <headers>#{Formula["ctags"].include}</headers>
-      <libs>#{Formula["ctags"].lib}</libs>
+      <libs>/usr/lib/system</libs>
     EOS
     gcc_suffix = Formula["gcc"].version.to_s.slice(/\d/)
     system bin/"abi-compliance-checker", "-cross-gcc", "gcc-" + gcc_suffix,
```
Seems to be happy no matter what I feed it as long as there are some libraries. I suspect our test is totally bogus.

**Comment by ilovezfs** [comment]
Test block seems useless, so I'm not comfortable merging this. Someone else will need to do this upgrade.

**Pull request closed without merging**
