### PR TITLE
node 21.0.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by derrabus** [comment]
I think it would make sense to add a `node@20` formula at the same time because Node 20.x is going to be the next LTS release.

**Comment by ZhongRuoyu** [comment]
> I think it would make sense to add a `node@20` formula at the same time because Node 20.x is going to be the next LTS release.

Yes. It takes a long time to build `node`, so instead of doing it here we can follow up with another PR.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
looks like these four formulae do not work with node21, checking in my local

```
brew test --retry --verbose cdktf
brew test --retry --verbose localtunnel
brew test --retry --verbose node-sass
brew test --retry --verbose quicktype
```

**Comment by chenrui333** [comment]
We can merge it now and quickly followup on the node@20 formula as well as patches for the four formula.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
