### PR TITLE
swift: migrate to boneyard

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Why?

**Comment by zmwangx** [comment]
Swift is provided by Apple through Xcode or CLT. Not many people install this formula, nothing depends on it, no one cared to bring it to 3.0, and the last time I tried to bring it up-to-date with [this patch](https://gist.github.com/zmwangx/0075ced732314f1902bdc12ef6e720e4) it [errored out](https://gist.github.com/zmwangx/85c741a6b1b167ea6d7e70d0639e3c3c) in a non-obvious way. Lacking demand and enthusiasm, let just make it history.

**Comment by zmwangx** [comment]
@MikeMcQuaid I was just about to CC you since you originally added it.

**Comment by MikeMcQuaid** [comment]
We're running a pretty old release that's probably worth trying to upgrade.

**Comment by zmwangx** [comment]
See comment above. If you can get it to work then sure.

**Comment by zmwangx** [comment]
My patch is a starting point: https://gist.github.com/zmwangx/0075ced732314f1902bdc12ef6e720e4.

**Comment by MikeMcQuaid** [comment]
Given we've got some people installing/using this: 👎 on removing.

**Comment by zmwangx** [comment]
Then bring it to 3.0.

**Comment by zmwangx** [comment]
@MikeMcQuaid I take that to mean you'll fix it? Because I've done my fair share of work to update it, and don't plan to waste more human and CPU time on something with little return (the official channel is better). I also don't want to see swiftin #5488 forever.

**Comment by MikeMcQuaid** [comment]
> I take that to mean you'll fix it?

Not necessarily but I'll take a look.

> Because I've done my fair share of work to update it, and don't plan to waste more human and CPU time on something with little return (the official channel is better).

That's up to you (as my work is up to me). We shouldn't boneyard things people are using. I won't object when no-one is using them.

> I also don't want to see swift in #5488 forever.

A maximum macOS requirement is the best short-term fix for these cases, I think.

**Comment by zmwangx** [comment]
> We shouldn't boneyard things people are using.

Running `brew install swift` is not equivalent to using `/usr/bin/local/swift` (well, it's not even linked by default) regularly, especially when `/usr/bin/swift` is up-to-date and infinitely better supported (in this respect the formula swift is not comparable to any other dupe we have). A long time ago, when swift was initially open sourced, I tried `brew install swift` just out of curiosity. I surely didn't use it afterwards; in fact, I haven't even got past page fifty of *The Swift Programming Language*, despite having kept it in iBooks since Swift 1.0 beta. Given the enthusiasm in Swift in general and our relatively pathetic install stats, I wouldn't be surprised if the great majority of those install numbers come from novelty trials like mine.

Even if there are people using it, there's always `/usr/bin/swift` (or swift under whatever sdk path), so it's not like we're leaving people in the dark by boneyarding this formula. In fact, I would urge them to use Apple's swift.

**Comment by MikeMcQuaid** [comment]
This isn't a conversation specific to Swift. We shouldn't boneyard things that aren't unsupported by upstream, are still installed by users and run on at least 1-2 of our supported OS versions.

**Comment by zmwangx** [comment]
> This isn't a conversation specific to Swift.

Well it is, or at least I'm not arguing about anything else. Swift is special in that it is provided by Apple, and is already installed by either Xcode or CLT, which we require at least one. If we can keep it up to date then sure, but it has been having trouble for a long time and no one bothered to fix it.

What we support is ultimately decided by what is feasible for the team to support (including what outside help we can solicit), not what non-contributing users wish for. Also, in this case I doubt anyone cares about the removal of the swift formula.

**Comment by MikeMcQuaid** [comment]
> Also, in this case I doubt anyone cares about the removal of the swift formula.

I care about the removal of things that aren't unsupported by upstream, are still installed by users and run on at least 1-2 of our supported OS versions.

**Comment by zmwangx** [comment]
What people are running (suppose they're actually running it) is an outdated version.

**Pull request closed without merging**
