### PR TITLE
cp2k 2023.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
@dduugg  got some ideas?

**Comment by dduugg** [comment]
Afk until Sunday, but try `to_a` on the enumerator at the call site, or widening the T::Array to T::Enumerable in the `sig` at the definition site. 🙏

**Comment by chenrui333** [comment]
does not build in my local, https://gist.github.com/chenrui333/aec57a686cba209c9035e3906aa33c41

```
gfortran -D__FFTW3 -I/opt/homebrew/opt/fftw/include -I /opt/homebrew/opt/libxc/include -I /opt/homebrew/Cellar/cp2k/2023.2/libexec/include -fopenmp -funroll-loops -ftree-vectorize -ffree-form -O2 -g -D__FFTW3 -D__NO_STATM_ACCESS -D__ACCELERATE -D__LIBXC -D__LIBINT -D__COMPILE_ARCH="\"Darwin-gfortran\"" -D__COMPILE_DATE="\"Thu Aug 10 00:30:40 UTC 2023\"" -D__COMPILE_HOST="\"rui-mbp-m1x-9.local\"" -D__COMPILE_REVISION="\"git:65cca6c\"" -D__DATA_DIR="\"/private/tmp/cp2k-20230809-2748-1ju1eq7/cp2k-2023.2/data\""  -L/private/tmp/cp2k-20230809-2748-1ju1eq7/cp2k-2023.2/lib/Darwin-gfortran/ssmp -o /private/tmp/cp2k-20230809-2748-1ju1eq7/cp2k-2023.2/exe/Darwin-gfortran/cp2k.ssmp cp2k.o  -lcp2kstart -lcp2kmc -lcp2kswarm -lcp2kmotion -lcp2kthermostat -lcp2kemd -lcp2ktmc -lcp2kmain -lcp2kdbt -lcp2ktas -lcp2kdbm -lcp2kgrid -lcp2kgriddgemm -lcp2kgridcpu -lcp2kgridref -lcp2kgridcommon -ldbcsrarnoldi -ldbcsrx -lcp2kshg_int -lcp2keri_mme -lcp2kminimax -lcp2khfxbase -lcp2ksubsys -lcp2kxc -lcp2kao -lcp2kpw_env -lcp2kinput -lcp2kpw -lcp2kgpu -lcp2kfft -lcp2kfpga -lcp2kfm -lcp2kcommon -lcp2koffload -lcp2kmpiwrap -lcp2kbase -L/private/tmp/cp2k-20230809-2748-1ju1eq7/cp2k-2023.2/lib/Darwin-gfortran/ssmp/exts/dbcsr -ldbcsr -L/opt/homebrew/opt/fftw/lib -lfftw3 -lfftw3_threads -lstdc++ -framework Accelerate -L/opt/homebrew/opt/libxc/lib -lxcf03 -lxc -L/opt/homebrew/Cellar/cp2k/2023.2/libexec/lib -lint2
Undefined symbols for architecture arm64:
  "_libint2_build_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eris in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eri_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eris in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eri_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_eri1 in libcp2kmain.a(libint_wrapper.o)
Undefined symbols for architecture arm64:
  "_libint2_build_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eris in libcp2kmain.a(libint_wrapper.o)
ld: symbol(s) not found for architecture arm64
  "_libint2_build_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eri_derivs in libcp2kmain.a(libint_wrapper.o)
collect2: error: ld returned 1 exit status
make[3]: *** [/private/tmp/cp2k-20230809-2748-1ju1eq7/cp2k-2023.2/exe/Darwin-gfortran/libcp2k_unittest.ssmp] Error 1
make[3]: *** Waiting for unfinished jobs....
  "_libint2_build_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eris in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eri_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_eri1 in libcp2kmain.a(libint_wrapper.o)
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[3]: *** [/private/tmp/cp2k-20230809-2748-1ju1eq7/cp2k-2023.2/exe/Darwin-gfortran/cp2k.ssmp] Error 1
make[2]: *** [all] Error 2
make[1]: *** [ssmp] Error 2
make: *** [all] Error 2

```

**Comment by chenrui333** [comment]
https://github.com/cp2k/cp2k/issues/2950

**Comment by fxcoudert** [comment]
The exact same PR builds for me locally. Trying another run at https://github.com/Homebrew/homebrew-core/pull/141288

**Pull request closed without merging**
