### PR TITLE
cypher-shell 1.1.11

### PR DESCRIPTION
**Pull request by chenrui333**
- bump the version to 1.1.11
- Fix the version

### CODE REVIEW

**Comment by chenrui333** [comment]
12:43:14 ==> Installing 'bundler' gem
12:43:14 Successfully installed bundler-2.0.2
12:43:14 1 gem installed
12:43:14 Error: 1 problem in 1 formula detected
12:43:14 cypher-shell:
12:43:14   * stable version should not decrease (from 1.10.0 to 1.1.11)

**Comment by EricFromCanada** [comment]
`version_scheme` needs to follow `sha256`. I believe you can remove the `version` line as well.

**Comment by chenrui333** [comment]
@EricFromCanada cool, just updated per comment :)

**Comment by chenrui333** [comment]
21:58:31 ==> Installing 'bundler' gem
21:58:31 Successfully installed bundler-2.0.2
21:58:31 1 gem installed
21:58:31 Error: 1 problem in 1 formula detected
21:58:31 cypher-shell:
21:58:31   * Stable: version (shell) is set to a string without a digit

**Pull request closed without merging**
