### PR TITLE
pwntools 3.0.1

### PR DESCRIPTION
**Pull request by ilovezfs**
use new virtualenv feature

### CODE REVIEW

**Comment by DomT4** [comment]
Resources need a bump/rejiggle here, apparently:
```
pkg_resources.DistributionNotFound: pysocks
Error: pwntools: failed
<0> expected but was
<1>.
```

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed. Also, any idea when `binutils` was there? Would you add it back?

**Comment by DomT4** [comment]
Pretty sure it needs `binutils` for `objdump`, so probably required. Rest of the PR looks 💯.

**Comment by ilovezfs** [comment]
worth adding a conflicts_with moreutils since they're both installing an errno binary?

**Comment by DomT4** [comment]
Is that a new thing? There's no conflict currently. If it's a new thing, I guess no other choice.

**Pull request closed without merging**
