### PR TITLE
Delete tart formula

### PR DESCRIPTION
**Pull request by fkorotkov**
We have our own tap https://github.com/cirruslabs/homebrew-cli where one can install Tart via:

```console
brew install cirruslabs/cli/tart
```

We prefer to have our tap as the way to install Tart since Tart's binary needs to go though Apple's notarization process. The notarization process is hooked into our CI and Apple Developer account.

### CODE REVIEW

**Review by SMillerDev — CHANGES_REQUESTED** [review]
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#official-vendor-taps documents why we won't do this while the license allows distribution.

**Comment by fkorotkov** [comment]
So you either forcing us to find a way to maintain this tap or our users to struggle because this tap is not picking up new version and is not properly signed?

**Comment by SMillerDev** [comment]
> So you either forcing us to find a way to maintain this tap or our users to struggle because this tap is not picking up new version and is not properly signed?

Well, you only need to update the one formula not the entire tap, and there are automations to automatically update the formula so your users struggle less. 

But yes, the fact that it's open source gives package managers a license to package your software. If you don't like them doing that you can always pick a different license.

**Comment by fkorotkov** [comment]
It doesn't seem there is a way to report an issue with a formula in this repository:

Screenshot 2022-12-20 at 8 55 54 AM

The first template is not suitable so I'll summarize the issue here.

There are two main issues with building Tart from sources (or any other software that integrates with macOS internals):

1. Tart is using Keychain to store credentials. Without proper signature upon every `brew update` a user will need to re-authorize the new binary to have access to Keychain.
2. For some functionality Tart needs [`com.apple.vm.networking` entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_networking) which you need special authorization from Apple to use. There is no way to override it locally even with `sudo`.

The only way to overcome these issues in this formula is not to install from sources but download signed binaries from our release page. Is it an option? Or you only do building from sources?

**Comment by SMillerDev** [comment]
> The first template is not suitable so I'll summarize the issue here.

Are these not reproducible? Because then it might just be your device settings.

> Tart is using Keychain to store credentials. Without proper signature upon every brew update a user will need to re-authorize the new binary to have access to Keychain.

AFAIK the `gh` CLI uses the keychain too and that doesn't have to re-authorize on my device. Are you sure this is caused by the signature?

> For some functionality Tart needs [com.apple.vm.networking entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_networking) which you need special authorization from Apple to use. There is no way to override it locally even with sudo.

So while it's open source you can't actually build it working for yourself?

**Comment by fkorotkov** [comment]
>AFAIK the gh CLI uses the keychain

Doesn't seem like the `gh` is using keychain yet https://github.com/cli/cli/issues/449. Seems it stores things in `~/.config/gh` https://github.com/cli/cli/issues/1773.

On macOS you either trust a binary or a developer that signed a binary. If you trusted a developer than updates to the binary won't ask for you password.

> So while it's open source you can't actually build it working for yourself?

You can. But if you'd like to use Bridged networking (which is not the default one) you'll need to `sudo` if you build from sources. With the entitlements macOS will allow modifying networking without `sudo`.

What about an option to use binaries from our release in this formula?

**Comment by SMillerDev** [comment]
> What about an option to use binaries from our release in this formula?

https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by fkorotkov** [comment]
@SMillerDev should we leave formula as is? You yourself had concerns about the signing in the original PR https://github.com/Homebrew/homebrew-core/pull/114571#discussion_r1012623099.

I wonder if @carlocab can weight in if the formula should've been accepted in the first place given that this formula requires an exception:

1. ["Stuff that requires heavy manual pre/post-install intervention"](https://docs.brew.sh/Acceptable-Formulae#stuff-that-requires-heavy-manual-prepost-install-intervention). Proper signing is hard and requires credentials to our Apple Developer Account.
2. Seems like a [Niche and doesn't fall under "We frown on authors submitting their own work unless it is very popular"](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff).
3. Tart only works on macOS under Apple Silicon and [doesn't support all three platforms](https://docs.brew.sh/Acceptable-Formulae#supported-platforms).

**Comment by carlocab** [comment]
Not really convinced an exception is required, but if one is: I'm fine with extending one here.

If there is a difference in functionality from the signed binaries due to the `com.apple.vm.networking` entitlement requirement then we can document it in the `caveats`.

**Comment by fkorotkov** [comment]
I just see this formula doing more harm to user experience than providing convenience (see https://github.com/cirruslabs/tart/issues/360#issuecomment-1359166324 for example where person used this). People don't search for a virtualization solution via `brew search`. It's a pretty niche area and people google it.

As I pointed above there is no way to build the same binary without our credentials. It's not our will but this is how things are on Apple platform when you are doing advanced integrations with keychain and networking.

I just want to make sure our users won't experience issues and confusions.

**Comment by SMillerDev** [comment]
> People don't search for a virtualization solution via brew search. It's a pretty niche area and people google it.

But people do see software and then run `brew install <name>`. Which won't work if it's in a non-default tap.

**Comment by fkorotkov** [comment]
How about a compromise and moving tart to casks and using pre-built binaries from [our releases](https://github.com/cirruslabs/tart/releases)?

**Pull request closed without merging**
