### PR TITLE
trino 432

### PR DESCRIPTION
**Pull request by iMichka**
Simplify test: this test is broken since some time. Running trino on macOS start 2 cfprefsd processes that eat up 100% CPU https://github.com/trinodb/trino/issues/18983#issuecomment-1793539236

We already have 2 upstream issues open:
https://github.com/trinodb/trino/issues/17023
https://github.com/trinodb/trino/issues/18983

See also this issue on our side
https://github.com/Homebrew/homebrew-core/issues/131903

Removing the original test is probably the best course of action here.

Some users seem to use trino (there were around 130 downloads in the last 30 days), but I do not know how ...

I am also a little bit unhappy that we do not compile the .jar file ourselves from source ...

Also, looking at the number of upstream issues (more than 2000), I am worried about the long term maintenance of the project ...

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
So the conclusion is it's broken and unusable on macOS?

Just to check (though I don't want to use up anyone's time): did you try my suggestion of OpenJDK 17? The test broke around the time OpenJDK 20 was released.

**Comment by iMichka** [comment]
https://github.com/trinodb/trino/issues/18983#issuecomment-1794206475
https://bugs.openjdk.org/browse/CODETOOLS-7903447

**Comment by iMichka** [comment]
Given the above bugs: I would like to get rid of the tests, until upstream sorts this out. There nothing more we can do here.

The download counts are not super high and I feel we spend already way too much time on this. If we feel maintaining trio is too much of an issue, then we can still deprecate/remove it later.

**Comment by SMillerDev** [comment]
Sounds good to me, can you add a comment to the test block for that though?

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
