### PR TITLE
macosvpn 0.2.0

### PR DESCRIPTION
**Pull request by halo**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Build failed on Mavericks & Yosemite. The recent Xcode 7 updates, which only shipped on El Cap, contained Swift changes so it's possible if upstream wrote the project on El Cap with the newest Xcode it could mask breaking changes for older Swifts.

**Comment by halo** [comment]
Sorry, I overlooked the `depends_on` option. Let's see if the build goes through now.

(The Deployment Target is still on 10.9 and Xcode 7 does not complain about that, so it should compile. But I forgot that I upgraded Xcode recently.)

**Comment by DomT4** [comment]
Passed this time, but you have effectively killed support for <El Cap because Yosemite is stuck on Xcode 7.2.1 indefinitely. If you're happy with that we're happy to 🚢 though.

**Comment by halo** [comment]
Haha, I realized that, too. I'm okay with that. People who want the old stuff can get it manually.

Thank you for your time! You guys are heroes.

**Comment by DomT4** [comment]
Cool. If you're happy upstream we're happy with this as-is then. No worries at all, glad people find Homebrew useful!

Merged in https://github.com/Homebrew/homebrew-core/commit/c87e5702a69df481ca6b4d670f0ec5e5389a1c12. Thank you for your contribution to Homebrew @halo; we appreciate it! :smiley_cat:

**Pull request closed without merging**
