### PR TITLE
apache-archiva 2.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@woodruffw another interesting corner case false positive for the linkage audit.

**Comment by woodruffw** [comment]
Is that actually a false positive? I would think that `/usr/lib/libgcc_s_ppc64.1.dylib` doesn't exist on modern OS X.

**Comment by ilovezfs** [comment]
@woodruffw yeah because it's a universal binary in the old school sense, and `otool` doesn't even register the linkage. See below.
```
iMac-TMP:homebrew-core joe$ brew install apache-archiva
==> Using the sandbox
==> Downloading https://www.apache.org/dyn/closer.cgi?path=archiva/2.2.1/binaries/apache-archiva-2.2.
Already downloaded: /Users/joe/Library/Caches/Homebrew/apache-archiva-2.2.1.tar.gz
Warning: The installation was broken.
Broken dylib links found:
  /usr/lib/libgcc_s_ppc64.1.dylib
==> Caveats
To have launchd start apache-archiva now and restart at login:
  brew services start apache-archiva
Or, if you don't want/need a background service you can just run:
  ARCHIVA_BASE=/usr/local/var/archiva /usr/local/opt/apache-archiva/bin/archiva console
==> Summary
🍺  /usr/local/Cellar/apache-archiva/2.2.1: 471 files, 75.9MB, built in 4 seconds
iMac-TMP:homebrew-core joe$ brew linkage --reverse apache-archiva
/usr/lib/libSystem.B.dylib
  libexec/bin/wrapper-macosx-universal-32
  libexec/bin/wrapper-macosx-universal-64
  libexec/lib/libwrapper-macosx-universal-32.jnilib
  libexec/lib/libwrapper-macosx-universal-64.jnilib

/usr/lib/libgcc_s.1.dylib
  libexec/bin/wrapper-macosx-universal-64
  libexec/lib/libwrapper-macosx-universal-64.jnilib

/usr/lib/libgcc_s_ppc64.1.dylib
  libexec/bin/wrapper-macosx-universal-64
  libexec/lib/libwrapper-macosx-universal-64.jnilib
iMac-TMP:homebrew-core joe$ otool -L /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 
/usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64:
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
iMac-TMP:homebrew-core joe$ otool -L /usr/local/Cellar/apache-archiva/2.2.1/libexec/lib/libwrapper-macosx-universal-64.jnilib
/usr/local/Cellar/apache-archiva/2.2.1/libexec/lib/libwrapper-macosx-universal-64.jnilib:
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
iMac-TMP:homebrew-core joe$ file /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 
/usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64: Mach-O universal binary with 2 architectures
/usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 (for architecture ppc64):	Mach-O 64-bit executable ppc64
/usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 (for architecture x86_64):	Mach-O 64-bit executable x86_64
iMac-TMP:homebrew-core joe$ file /usr/local/Cellar/apache-archiva/2.2.1/libexec/lib/libwrapper-macosx-universal-64.jnilib
/usr/local/Cellar/apache-archiva/2.2.1/libexec/lib/libwrapper-macosx-universal-64.jnilib: Mach-O universal binary with 2 architectures
/usr/local/Cellar/apache-archiva/2.2.1/libexec/lib/libwrapper-macosx-universal-64.jnilib (for architecture ppc64):	Mach-O 64-bit bundle ppc64
/usr/local/Cellar/apache-archiva/2.2.1/libexec/lib/libwrapper-macosx-universal-64.jnilib (for architecture x86_64):	Mach-O 64-bit bundle x86_64
iMac-TMP:homebrew-core joe$
```

**Comment by woodruffw** [comment]
I could be misunderstanding, but I don't think this is a bug on our end. In older versions on OS X, `/usr/lib/libgcc_s_ppc64.1.dylib` was a symlink to `/usr/lib/libgcc_s.1.dylib`. However, modern versions of `libgcc_s.1.dylib` don't provide a `ppc64` slice:

```
file /usr/lib/libgcc_s.1.dylib 
/usr/lib/libgcc_s.1.dylib: Mach-O universal binary with 2 architectures: [x86_64: Mach-O 64-bit dynamically linked shared library x86_64] [i386: Mach-O dynamically linked shared library i386]
/usr/lib/libgcc_s.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/usr/lib/libgcc_s.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
```

Thus, any `ppc64` binary that links to them (or tries to with the old symlink) should explode at load-time anyways.

**Comment by ilovezfs** [comment]
It's only the x86_64 part of the file that's relevant for us though ...

**Comment by ilovezfs** [comment]
```
iMac-TMP:homebrew-core joe$ /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 
FATAL  | wrapper  | Unable to resolve the full path of the configuration file, wrapper-macosx-universal-64.conf: No such file or directory
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org

Usage:
  /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 <command> <configuration file> [configuration properties] [...]
  /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 <configuration file> [configuration properties] [...]
     (<command> implicitly '-c')
  /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64 <command>
     (<configuration file> implicitly 'wrapper-macosx-universal-64.conf')
  /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64
     (<command> implicitly '-c' and <configuration file> 'wrapper-macosx-universal-64.conf')

where <command> can be one of:
  -c  --console  run as a Console application
  -v  --version print the wrapper's version information.
  -?  --help    print this help message

<configuration file> is the wrapper.conf to use.  Name must be absolute or relative
  to the location of /usr/local/Cellar/apache-archiva/2.2.1/libexec/bin/wrapper-macosx-universal-64

[configuration properties] are configuration name-value pairs which override values
  in wrapper.conf.  For example:
  wrapper.debug=true

```

No evidence of being broken.

**Comment by woodruffw** [comment]
Relevant to us, but the linkage checker cares about all architectures.

Are you saying that we should ignore broken linkages on older arches (i.e., `ppc` and `ppc64`)? That probably wouldn't be unreasonable (since almost nobody's running them anyways), but I think we should nudge upstreams first before resorting to that.

**Comment by ilovezfs** [comment]
>Are you saying that we should ignore broken linkages on older arches

That, or white-list the specific formula.

>I think we should nudge upstreams first before resorting to that.

Nudge them to do what, though? Wouldn't any "fix" break the PPC part of the file?

**Comment by woodruffw** [comment]
> That, or white-list the specific formula.

I'd be okay with this, although there's another option we can consider: completely stripping packages of their `ppc`/`ppc64` slices. I don't think we (being Homebrew) support such ancient versions of OS X  anyways, and they really only serve to take up space and cause audit failures.

> Nudge them to do what, though? Wouldn't any "fix" break the PPC part of the file?

I can thing of two avenues of recourse for upstreams:

* Remove their `ppc`/`ppc64` targets entirely, since the last OS X to actually support them is (nearly?) a decade old and completely unsupported at this point. They almost certainly aren't testing their PowerPC builds anyways, so having them in the builds almost certainly adds nothing.
* Dig up ancient versions of libraries like `/usr/lib/libgcc_s.1.dylib` and vendor them in their projects. I think that's relatively common, at least with Apache projects.

**Comment by ilovezfs** [comment]
>I'd be okay with this, although there's another option we can consider: completely stripping packages of their ppc/ppc64 slices.

That sounds a tad invasive for `bottle :unneeded` but I have no reason to believe it would actually cause problems.

Or we could acknowledge :elephant: in the room, and build the software from source.

**Comment by woodruffw** [comment]
> That sounds a tad invasive for bottle :unneeded but I have no reason to believe it would actually cause problems.

Yeah, that's true. We could do it as part of the relocation phase (so that nothing is excluded), but it's a fair bit more hands-on that we currently are.

> Or we could acknowledge :elephant: in the room, and build the software from source.

Yeah, that would work. They have building instructions here: https://archiva.apache.org/developers/building.html, although I think that shooting them a friendly email first could save us a bit of work. I can do that later today.

**Pull request merged**
