### PR TITLE
kibana 5.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by 7elix** [comment]
How does this PR get into the core?
(https://bot.brew.sh/job/Homebrew%20Core/10208/console)

**Comment by GRoguelon** [comment]
Hi,

In looking at the [package.json](https://github.com/elastic/kibana/blob/v5.0.0/package.json#L220) of Kibana 5.0, we can see it depends of Node 6.9.0, Shouldn't we update the Node part of this formula?

**Comment by fiedl** [comment]
This does not work for me on *macOS Sierra*.

```
➜  brew install kibana
==> Downloading https://homebrew.bintray.com/bottles/kibana-5.0.0.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "kibana"
Download failed: https://homebrew.bintray.com/bottles/kibana-5.0.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Cloning https://github.com/elastic/kibana.git
Updating /Users/fiedl/Library/Caches/Homebrew/kibana--git
==> Checking out tag v5.0.0
==> Downloading https://nodejs.org/dist/v4.4.4/node-v4.4.4.tar.gz
Already downloaded: /Users/fiedl/Library/Caches/Homebrew/kibana--node-4.4.4.tar.gz
==> ./configure --prefix=/usr/local/Cellar/kibana/5.0.0/libexec/node
==> make install
==> npm install --verbose
==> npm run build
Last 15 lines from /Users/fiedl/Library/Logs/Homebrew/kibana/04.npm:
npm ERR!
npm ERR! Failed at the kibana@5.0.0 build script 'grunt build'.
npm ERR! This is most likely a problem with the kibana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kibana
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls kibana
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/kibana-20161031-42591-9bd1lw/npm-debug.log

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
kibana 5.0.0 https://github.com/Homebrew/homebrew-core/pull/6317

➜  cat /private/tmp/kibana-20161031-42591-9bd1lw/npm-debug.log
cat: /private/tmp/kibana-20161031-42591-9bd1lw/npm-debug.log: No such file or directory
```

Kibana 5.0.0-alpha3 (using `brew install kibana --devel`) and Kibana 4.5.1 do install fine though.

**Comment by ilovezfs** [comment]
I'll leave this to someone else.

**Pull request closed without merging**
