### PR TITLE
[WIP] wtfutil 0.10.1 (New Formula)

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/Homebrew/homebrew-cask/pull/59525

### CODE REVIEW

**Comment by fxcoudert** [comment]
`go_resource`s are deprecated

**Comment by chenrui333** [comment]
@fxcoudert what should be the right way to address the dependencies of `go modules`? I might need some help and advice on it.

**Comment by fxcoudert** [comment]
We have lots of go formulas, so look at the one that matches closest what you need :)

**Comment by chenrui333** [comment]
I see, I did try, will checkout again. 😆

**Comment by chenrui333** [comment]
Right now, helmfile-0.60.1 suffers the similar dependencies issue.

**Comment by chenrui333** [comment]
Close this in favor of new version, v0.10.2

**Pull request closed without merging**
