### PR TITLE
sdl, sdl2: use pkgshare instead of share for tests

### PR DESCRIPTION
**Pull request by ticky**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @ticky! Would you mind splitting this into one commit per-formula?

**Comment by ticky** [comment]
_breaks out the ✂️_

**Comment by ticky** [comment]
@MikeMcQuaid: done! ✨

**Comment by dunn** [comment]
Thanks! Merged as 969d6e3a4c41f5f19a2a9ff94697a4ebe14ec94e and 3d0f658f62079a6bcbd71c13978483a43b2389f3.

**Pull request closed without merging**
