### PR TITLE
biome 1.4.0

### PR DESCRIPTION
**Pull request by nhedger**
Update `biome` to 1.4.0

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by nhedger** [comment]
The audit fails because of a perceived difference in licenses between the formula and GitHub.

We have multiple licenses on GitHub: `MIT` and `Apache-2.0`

How is this usually handled in Homebrew ?

**Comment by chenrui333** [comment]
> The audit fails because of a perceived difference in licenses between the formula and GitHub.
> 
> We have multiple licenses on GitHub: `MIT` and `Apache-2.0`
> 
> How is this usually handled in Homebrew ?
> 
> I was thinking of updating the formula with the following:
> 
> ```
> license any_of: ["MIT", "Apache-2.0"]
> ```

yeah, that is the way to go. as you can see multiple rust formulae are following the same pattern

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
Thanks @nhedger !

**Comment by nhedger** [comment]
Appreciate the help, thanks!

**Comment by p-linnane** [comment]
Looks like this PR was affected by the GitHub Actions incident from earlier. You'll need to force push again to get the jobs started.

**Pull request merged**
