### PR TITLE
hugo 0.81.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ress997** [comment]
> We finally provide native Hugo binary for Apple M1 devices. Download the file named hugo_0.81.0_macOS-ARM64.tar.gz.

The settings for Apple M1 have not been added.

**Comment by chenrui333** [comment]
```
tpl/internal/go_templates/texttemplate/helper.go:11:2: package io/fs is not in GOROOT (/usr/local/Cellar/go/1.15.8/libexec/src/io/fs)
```

**Comment by chenrui333** [comment]
depends_on #71289 (go1.16)

**Comment by bryanforbes** [comment]
Why was this closed?

**Comment by carlinmack** [comment]
[Historically these are closed](https://github.com/Homebrew/homebrew-core/pulls?q=is:pr+hugo) but I'm not sure how hugo is updated otherwise

**Comment by carlinmack** [comment]
#71289 has been merged

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
