### PR TITLE
imagemagick 7.0.9-9

### PR DESCRIPTION
**Pull request by ath0mas**
Should brew mirror imagemagick when merging

### CODE REVIEW

**Comment by ath0mas** [comment]
Any analysis on the failed checks? _please_

**Comment by Watson1978** [comment]
Seems that `https://www.imagemagick.org/download` causes certificate error when download a tarball.
You can fix the error with `https://imagemagick.org/download` instead.

**Comment by Watson1978** [comment]
Seems ImageMagick 7.0.9-9 fails to build where it use `aligned_alloc` on old platform.
I think it will fix with https://github.com/ImageMagick/ImageMagick/commit/25b296e564af6e000b8aaf8809f940c6eb1d3515 which will be shiped with next version.

**Comment by fxcoudert** [comment]
ImageMagick releases pretty often, so we'll wait for the next version. Thanks @ath0mas

**Pull request closed without merging**
