### PR TITLE
symlinks 1.4.3 (new formula)

### PR DESCRIPTION
**Pull request by danielbayley**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

``` sh
* GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

---

Signed-off-by: Daniel Bayley daniel.bayley@me.com

### CODE REVIEW

**Comment by zmwangx** [comment]
This software is not notable (sorry, but 26 stars on GitHub really is nothing) and not actively developed, so I'm afraid you might want to explore the self-hosted tap option: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Migrating-A-Formula-To-A-Tap.md, which is really easy by the way.

I'll leave this open for a day or two to see if other maintainers want to endorse it, but I doubt it.

**Comment by zmwangx** [comment]
Sorry, wrong doc link: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md.

**Comment by chdiza** [comment]
Someone tried to get this formula in awhile back, in homebrew-legacy.  I don't have time right now to go search for it.  But IIRC the number of stars is, in this particular case, misleading.

**Comment by zmwangx** [comment]
https://github.com/Homebrew/legacy-homebrew/pull/47832

If Mike and Martin wanted to pass that time and pretty much no one else cared, and the situation isn't much different from January, I don't see why we should consider it this time.

**Comment by chdiza** [comment]
I don't care one way or the other, I just wanted to point out that there was some prior discussion.

**Comment by zmwangx** [comment]
Please don't randomly push to this branch, it just pointlessly taxes our CI. Since you no longer seem committed to submitting this formula (seeing that you actually pushed something else), I'm going to close this PR. Sorry!

**Comment by danielbayley** [comment]
> you actually pushed something else

@zmwangx That’s odd… and certainly wasn’t my intention! Looking at this; I was working on a local _branch_, but had pushed to _master_ rather than mirror the branch on the remote fork… new git client, sorry!

> you no longer seem committed to submitting this formula

I would be happy to, and had made an `--amend` (which was unintentionally overridden…) to make sure the man page was also linked: `man8.install "symlinks.8”`. I can resubmit, but it looks like there would be no point now?

**Comment by zmwangx** [comment]
> new git client, sorry!

No problem.

> I can resubmit, but it looks like there would be no point now?

You can certainly try, but I doubt it's worth the effort, to be honest.

**Pull request closed without merging**
