### PR TITLE
anime-downloader 5.0.1

### PR DESCRIPTION
**Pull request by bonkboykz**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bonkboykz** [comment]
@dtrodrigues is there anything wrong with the pr?

**Comment by dtrodrigues** [comment]
This can be merged after https://github.com/Homebrew/homebrew-core/pull/62560 completes

**Comment by fxcoudert** [comment]
@dtrodrigues thanks for putting it on hold!

**Review by fxcoudert — CHANGES_REQUESTED** [review]
- Please rebase on top of master (because of the python upgrade revision bump)
- Check whether the resources can be updated

**Comment by bonkboykz** [comment]
>     * Please rebase on top of master (because of the python upgrade revision bump)
> 
>     * Check whether the resources can be updated

Done

**Comment by bonkboykz** [comment]
One of the tests is failing
Screen Shot 2020-10-23 at 16 33 50
with
Screen Shot 2020-10-23 at 16 33 21

Should I remove revision @fxcoudert ?

**Comment by dtrodrigues** [comment]
Yes please

**Comment by dtrodrigues** [comment]
For reference, if you had run `brew bump-formula-pr anime-downloader --version=5.0.1`, it would have done the version bump, removed the revision, and also seen and updated urllib3 from 1.25.10 to 1.25.11. I've pushed that updated resource to your branch.

**Comment by bonkboykz** [comment]
> For reference, if you had run `brew bump-formula-pr anime-downloader --version=5.0.1`, it would have done the version bump, removed the revision, and also seen and updated urllib3 from 1.25.10 to 1.25.11. I've pushed that updated resource to your branch.

I did, but it failed due to some network issues, which I later fixed, and, as far as I know, there's no way to continue bumping the version once it failed

**Review by fxcoudert — APPROVED** [review]

**Comment by dtrodrigues** [comment]
It should be possible to re-try if it failed along the way due to network issues. I'm wondering if after the failed network issue, the primary url had been updated in which case `bump-formula-pr` might not work. Resetting to the original one should allow you to re-run the command.

**Comment by bonkboykz** [comment]
> It should be possible to re-try if it failed along the way due to network issues. I'm wondering if after the failed network issue, the primary url had been updated in which case `bump-formula-pr` might not work. Resetting to the original one should allow you to re-run the command.

I was looking at this comment: https://github.com/Homebrew/brew/issues/3150#issuecomment-331539591

**Comment by dtrodrigues** [comment]
The decision of whether or not to restore state was a deliberate one - there are cases where a different error occurred and one might want to continue from that position vs starting over from scratch. You may need to manually revert/manually delete the branch that was auto-created though. As the issue submitter pointed out, deleting the branch should allow you to re-run the command.

Thanks for your patience with this in the middle of our Python 3.9 migration and for your first contribution to Homebrew @bonkboykz!

**Comment by bonkboykz** [comment]
> The decision of whether or not to restore state was a deliberate one - there are cases where a different error occurred and one might want to continue from that position vs starting over from scratch. You may need to manually revert/manually delete the branch that was auto-created though. As the issue submitter pointed out, deleting the branch should allow you to re-run the command.
> 
> Thanks for your patience with this in the middle of our Python 3.9 migration and for your first contribution to Homebrew @bonkboykz!

Got it, I kinda rushed to the first solution I could come up with 😅 I'll try that next time

Thanks for the support, guys!

**Pull request closed without merging**
