### PR TITLE
libwebsockets 2.2.0

### PR DESCRIPTION
**Pull request by mdemierre**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by mdemierre** [comment]
This change seems to break mosquitto and ttyd. I don't know why, maybe someone can provide guidance.

**Comment by ilovezfs** [comment]
They need revision bumps.
```
        Missing libraries:
  /usr/local/opt/libwebsockets/lib/libwebsockets.9.dylib
```
But
```
$ ls /usr/local/Cellar/libwebsockets/2.2.0/lib/
cmake			libwebsockets.a		pkgconfig
libwebsockets.10.dylib	libwebsockets.dylib
```

**Comment by mdemierre** [comment]
@ilovezfs I bumped both revisions and the tests now pass.

**Comment by fxcoudert** [comment]
Thanks @mdemierre for your contribution!

**Comment by DomT4** [comment]
Both of the revisions here should have been to `1` rather than `2` just for future reference; the default revision is `0` but unwritten.

**Comment by fxcoudert** [comment]
Indeed, I had missed that. Does it matter, in practice, as long as it increases?

**Comment by DomT4** [comment]
No practical issue as long as it increases and is placed outside of a block, aye. Just less than fondly remember spending time on Bintray in the past trying to find `revision 1` bottles for debugging only to realise they never existed 😆.

**Comment by mdemierre** [comment]
@DomT4 @fxcoudert woops sorry about the '2', I'll know for next time 😉

**Pull request closed without merging**
