### PR TITLE
vault: add support for UI

### PR DESCRIPTION
**Pull request by nic**
Add support for UI (web admin). Ref: https://learn.hashicorp.com/vault/getting-started/ui

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@nic Any update on this for the fix?

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
```

Number of parallel builds: 5

-->    darwin/amd64: github.com/hashicorp/vault

1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/hashicorp/vault/http
http/handler.go:136:147: undefined: assetFS
http/handler.go:137:129: undefined: assetFS

make: *** [dev-ui] Error 1
```

**Comment by adarobin** [comment]
Based on the [upstream readme](https://github.com/hashicorp/vault/blob/master/README.md) It looks like it should be `system "make", "static-dist", "dev-ui"`

**Comment by adarobin** [comment]
I'm close to having it build, but it looks like there is a build-time dependency missing in Homebrew - github.com/elazarl/go-bindata-assetfs/

**Comment by adarobin** [comment]
So https://github.com/elazarl/go-bindata-assetfs/ depends on https://github.com/go-bindata/go-bindata/.  https://github.com/kevinburke/go-bindata is what is used for `go-bindata` in Homebrew.

How are build time Go dependencies typically handled in Homebrew?

**Comment by chenrui333** [comment]
FYI, there is new vault UI effort in here, https://github.com/Homebrew/homebrew-core/pull/55484

**Pull request closed without merging**
