### PR TITLE
osmium-tool 1.12.1

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Depends on https://github.com/Homebrew/homebrew-core/pull/57049

**Comment by chenrui333** [comment]
@dtrodrigues if that is the case, can you have two commits into one PR?

**Comment by dtrodrigues** [comment]
Would it make more sense to keep them separate and rebase this once the other one is merged, similar to pidgin/libgnt https://github.com/Homebrew/homebrew-core/pull/56096 ?

**Comment by chenrui333** [comment]
@dtrodrigues technically, we should group the relevant PRs together and it would save some CI efforts.

But in the past, sometimes the dependency chain is not quite clear and we did not enforce it.

**Comment by chenrui333** [comment]
The only exception is the new formula, we generally don't create new formulae in the dependency upgrade PR (if my memory serves correctly)

**Comment by chenrui333** [comment]
Alright, I think @Rylan12 did approve and merge the other PR, I think now we can rebase and go for the merge for this PR.

**Comment by Rylan12** [comment]
Oops, my apologies. I missed this...

**Comment by chenrui333** [comment]
> Oops, my apologies. I missed this...

No worries at all, just think of a best way for the related dependencies management. :)

@dtrodrigues hope you dont mind either. :)

**Comment by Rylan12** [comment]
> No worries at all, just think of a best way for the related dependencies management. 😄

@chenrui333 can you clarify what you mean by this? The other PR was just a version bump, so I'm curious what the benefit of having them together in the same PR is.

**Comment by chenrui333** [comment]
> > No worries at all, just think of a best way for the related dependencies management. 😄
> 
> @chenrui333 can you clarify what you mean by this? The other PR was just a version bump, so I'm curious what the benefit of having them together in the same PR is.

The benefit would save the CI time?

This might be my own personal opinion though.

> @dtrodrigues technically, we should group the relevant PRs together and it would save some CI efforts.
> But in the past, sometimes the dependency chain is not quite clear and we did not enforce it.

**Comment by dtrodrigues** [comment]
I’ll rebase and force push once I’m back at a computer.

Personally I think the benefit of having consistently-named PRs (`formula version`) outweighs the CI savings given the (probable) relative infrequency.

I do think in general there’s substantial room for CI usage improvements but I don’t think we’d really get that much savings from these cases.

**Comment by dtrodrigues** [comment]
@chenrui333 @Rylan12  I rebased and CI is passing now.

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
