### PR TITLE
ats2-postiats: fix checksum mismatch

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to #88329

### CODE REVIEW

**Comment by chenrui333** [comment]
let me also reach out to the upstream to check if we do need to rebottle this (even though I think we should)

**Comment by chenrui333** [comment]
added `do not merge` tag to wait for original author's comments

**Comment by chenrui333** [comment]
Did not get any response on this PR. I would say that let's go with the revision bump.

**Comment by SMillerDev** [comment]
Had upstream responded? Otherwise it's a definite no.

**Comment by githwxi** [comment]
Thanks Chen Rui for fixing this checksum mismatch issue for ATS2-Postiats-0.4.2.

After releasing the original ATS2-Postiats-0.4.2, I noticed a minor issue. I fixed the issue but
unfortuately forgot to update the checksum. It is really good to learn that Rui took the initiative
to finally update the checksum so as to match it with the fixed release of ATS2-Postiats-0.4.2.

Best!

--Hongwei

**Comment by SMillerDev** [comment]
Good to hear you retagged the release, because the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do. So we generally assume it's a compromised repo.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
