### PR TITLE
qt 5.9.2

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Let's see how this goes. _Sighs deeply_.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Huh, not a single thing broke. How unexpected, even for a minor release 😄.

**Comment by s172262** [comment]
Building `QT` with `--with-webkit` makes error.
```
$ brew info qt
qt: stable 5.9.2 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.9.1 (9,128 files, 304.0MB)
  Built from source on 2017-09-28 at 06:47:39 with: --with-qtwebkit
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
==> Dependencies
Build: pkg-config ✔
==> Requirements
Build: xcode ✔
Required: macOS >= 10.8 ✔
Optional: mysql ✘, postgresql ✘
==> Options
--with-docs
	Build documentation
--with-examples
	Build examples
--with-mysql
	Build with mysql support
--with-postgresql
	Build with postgresql support
--with-qtwebkit
	Build with QtWebkit module
--HEAD
	Install HEAD version
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.
```
```
$ brew upgrade -s --cleanup qt --with-qtwebkit
==> Upgrading 1 outdated package, with result:
qt 5.9.2
==> Upgrading qt --with-qtwebkit
==> Downloading https://download.qt.io/official_releases/qt/5.9/5.9.2/single/qt-
==> Downloading from http://ftp.jaist.ac.jp/pub/qtproject/archive/qt/5.9/5.9.2/s
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e8fe6
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/a627e
######################################################################## 100.0%
==> Patching
==> Applying restore-pc-files.patch
patching file qtbase/mkspecs/features/qt_module.prf
Hunk #1 succeeded at 264 (offset 19 lines).
==> Applying QTBUG-56814.patch
patching file qttools/src/macdeployqt/shared/shared.cpp
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 821 with fuzz 2 (offset 18 lines).
==> Downloading https://download.qt.io/official_releases/qt/5.9/5.9.1/submodules
==> Downloading from http://ftp.jaist.ac.jp/pub/qtproject/archive/qt/5.9/5.9.1/s
######################################################################## 100.0%
Error: inreplace failed
.gitmodules:
  expected replacement of /.*status = obsolete\n((\s*)project = WebKit\.pro)/ with "\\1\n\\2initrepo = true"
```
In `.gitmodules`.
```
[submodule "qtbase"]
	path = qtbase
	url = ../qtbase.git
	branch = 5.9.2
	status = essential
	repoType = inherited
[submodule "qtsvg"]
	depends = qtbase
	path = qtsvg
	url = ../qtsvg.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtdeclarative"]
	depends = qtbase
	recommends = qtsvg qtxmlpatterns
	path = qtdeclarative
	url = ../qtdeclarative.git
	branch = 5.9.2
	status = essential
	repoType = inherited
[submodule "qtactiveqt"]
	depends = qtbase
	path = qtactiveqt
	url = ../qtactiveqt.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtscript"]
	depends = qtbase
	recommends = qttools
	path = qtscript
	url = ../qtscript.git
	branch = 5.9.2
	status = deprecated
	repoType = inherited
[submodule "qtmultimedia"]
	depends = qtbase
	recommends = qtdeclarative
	path = qtmultimedia
	url = ../qtmultimedia.git
	branch = 5.9.2
	status = essential
	repoType = inherited
[submodule "qttools"]
	depends = qtbase
	recommends = qtdeclarative qtactiveqt
	path = qttools
	url = ../qttools.git
	branch = 5.9.2
	status = essential
	repoType = inherited
[submodule "qtxmlpatterns"]
	depends = qtbase
	path = qtxmlpatterns
	url = ../qtxmlpatterns.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qttranslations"]
	depends = qttools
	path = qttranslations
	url = ../qttranslations.git
	branch = 5.9.2
	status = essential
	priority = 30
	repoType = inherited
[submodule "qtdoc"]
	depends = qtdeclarative
	path = qtdoc
	url = ../qtdoc.git
	branch = 5.9.2
	status = essential
	priority = 40
	repoType = inherited
[submodule "qtrepotools"]
	path = qtrepotools
	url = ../qtrepotools.git
	branch = master
	status = essential
	project = -
	repoType = inherited
[submodule "qtqa"]
	depends = qtbase
	path = qtqa
	url = ../qtqa.git
	branch = master
	status = essential
	priority = 50
	repoType = inherited
[submodule "qtlocation"]
	depends = qtbase
	recommends = qtdeclarative qtquickcontrols qtquickcontrols2 qtserialport
	path = qtlocation
	url = ../qtlocation.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtsensors"]
	depends = qtbase
	recommends = qtdeclarative
	path = qtsensors
	url = ../qtsensors.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtsystems"]
	depends = qtbase
	recommends = qtdeclarative
	path = qtsystems
	url = ../qtsystems.git
	branch = dev
	status = ignore
	repoType = inherited
[submodule "qtfeedback"]
	depends = qtdeclarative
	recommends = qtmultimedia
	path = qtfeedback
	url = ../qtfeedback.git
	branch = master
	status = ignore
	repoType = inherited
[submodule "qtdocgallery"]
	depends = qtdeclarative
	path = qtdocgallery
	url = ../qtdocgallery.git
	branch = master
	status = ignore
	repoType = inherited
[submodule "qtpim"]
	depends = qtdeclarative
	path = qtpim
	url = ../qtpim.git
	branch = dev
	status = ignore
	repoType = inherited
[submodule "qtconnectivity"]
	depends = qtbase
	recommends = qtdeclarative qtandroidextras
	path = qtconnectivity
	url = ../qtconnectivity.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtwayland"]
	depends = qtbase
	recommends = qtdeclarative
	path = qtwayland
	url = ../qtwayland.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qt3d"]
	depends = qtbase
	recommends = qtdeclarative qtimageformats qtgamepad
	path = qt3d
	url = ../qt3d.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtimageformats"]
	depends = qtbase
	path = qtimageformats
	url = ../qtimageformats.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtquick1"]
	depends = qtscript
	recommends = qtsvg qtxmlpatterns
	path = qtquick1
	url = ../qtquick1.git
	branch = dev
	status = ignore
	repoType = inherited
[submodule "qtgraphicaleffects"]
	depends = qtdeclarative
	path = qtgraphicaleffects
	url = ../qtgraphicaleffects.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtquickcontrols"]
	depends = qtdeclarative
	recommends = qtgraphicaleffects
	path = qtquickcontrols
	url = ../qtquickcontrols.git
	branch = 5.9.2
	status = essential
	repoType = inherited
[submodule "qtserialbus"]
	depends = qtserialport
	path = qtserialbus
	url = ../qtserialbus.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtserialport"]
	depends = qtbase
	path = qtserialport
	url = ../qtserialport.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtx11extras"]
	depends = qtbase
	path = qtx11extras
	url = ../qtx11extras.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtmacextras"]
	depends = qtbase
	path = qtmacextras
	url = ../qtmacextras.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtwinextras"]
	depends = qtbase
	recommends = qtdeclarative qtmultimedia
	path = qtwinextras
	url = ../qtwinextras.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtandroidextras"]
	depends = qtbase
	path = qtandroidextras
	url = ../qtandroidextras.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtenginio"]
	depends = qtdeclarative
	path = qtenginio
	url = ../qtenginio.git
	branch = dev
	status = ignore
	repoType = inherited
[submodule "qtwebsockets"]
	depends = qtbase
	recommends = qtdeclarative
	path = qtwebsockets
	url = ../qtwebsockets.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtwebchannel"]
	depends = qtbase
	recommends = qtdeclarative qtwebsockets
	path = qtwebchannel
	url = ../qtwebchannel.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtwebengine"]
	depends = qtquickcontrols qtwebchannel
	recommends = qtlocation qttools
	path = qtwebengine
	url = ../qtwebengine.git
	branch = 5.9.2
	status = addon
	priority = 10
	repoType = inherited
[submodule "qtcanvas3d"]
	depends = qtdeclarative
	path = qtcanvas3d
	url = ../qtcanvas3d.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtwebview"]
	depends = qtdeclarative
	recommends = qtwebengine
	path = qtwebview
	url = ../qtwebview.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtquickcontrols2"]
	depends = qtgraphicaleffects
	path = qtquickcontrols2
	url = ../qtquickcontrols2.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtpurchasing"]
	depends = qtbase qtandroidextras
	recommends = qtdeclarative
	path = qtpurchasing
	url = ../qtpurchasing.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtcharts"]
	depends = qtbase
	recommends = qtdeclarative qtmultimedia
	path = qtcharts
	url = ../qtcharts.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtdatavis3d"]
	depends = qtbase
	recommends = qtdeclarative qtmultimedia
	path = qtdatavis3d
	url = ../qtdatavis3d.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtvirtualkeyboard"]
	depends = qtbase qtdeclarative qtsvg
	recommends = qtmultimedia qtquickcontrols
	path = qtvirtualkeyboard
	url = ../qtvirtualkeyboard.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtgamepad"]
	depends = qtbase
	recommends = qtdeclarative
	path = qtgamepad
	url = ../qtgamepad.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtscxml"]
	depends = qtbase qtdeclarative
	path = qtscxml
	url = ../qtscxml.git
	branch = 5.9.2
	status = addon
	repoType = inherited
[submodule "qtspeech"]
	depends = qtbase
	recommends = qtdeclarative qtmultimedia
	path = qtspeech
	url = ../qtspeech.git
	branch = 5.9.2
	status = preview
	repoType = inherited
[submodule "qtnetworkauth"]
	depends = qtbase
	recommends = qtwebview
	path = qtnetworkauth
	url = ../qtnetworkauth.git
	branch = 5.9.2
	status = preview
	repoType = inherited
[submodule "qtremoteobjects"]
	depends = qtbase
	recommends = qtdeclarative
	path = qtremoteobjects
	url = ../qtremoteobjects.git
	branch = 5.9.2
	status = preview
	repoType = inherited
[submodule "tqtc-qmlcompiler"]
	depends = qtbase qtdeclarative
	path = tqtc-qmlcompiler
	url = ../tqtc-qmlcompiler
	branch = 5.9
	status = addon
	project = qmlcompiler.pro
```

**Comment by DomT4** [comment]
Will look into it. I've seen people report 5.9.1 WebKit works fine with 5.9.2 Qt5 so I suspect it's simply an `inreplace` issue rather than a deeper incompatibility. I've got a pretty full schedule today so people are welcome to jump over me in terms of working out what broke.

**Pull request closed without merging**
