### PR TITLE
rizin: put head back to dev instead of stable

### PR DESCRIPTION
**Pull request by ret2libc**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Fixing https://github.com/Homebrew/homebrew-core/pull/106163#pullrequestreview-1044237281

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by carlocab** [comment]
By the way, @ret2libc, about these options in `meson_options.txt`:

```
option('rizin_wwwroot', type: 'string', value: '', description: 'Install path for www files')
option('rizin_sdb', type: 'string', value: '', description: '')
option('rizin_zigns', type: 'string', value: '', description: 'Install path for zignatures files')
option('rizin_sigdb', type: 'string', value: '', description: 'Install path for sigdb files')
option('rizin_themes', type: 'string', value: '', description: 'Install path for themes (colors, etc.)')
option('rizin_fortunes', type: 'string', value: '', description: 'Install path for fortunes displayed when starting')
option('rizin_flags', type: 'string', value: '', description: 'Install path for flags tags')
option('rizin_hud', type: 'string', value: '', description: 'Install path for hud file (V!/)')
option('rizin_plugins', type: 'string', value: '', description: 'Path where plugins are expected to be found')
option('rizin_bindings', type: 'string', value: '', description: 'Path where rizin bindings are expected to be found')
```

Do these have to be locations whose contents are persistent, or can they be destroyed when the version of `rizin` changes?

Because currently they are pointed at directories that will be deleted with a `brew upgrade rizin`, so I just want to double check that that's ok.

**Comment by ret2libc** [comment]
They can be destroyed on each upgrade, things are re-installed on each meson install.

**Comment by carlocab** [comment]
Ok, sounds good. Thanks!

**Pull request merged**
