### PR TITLE
apache-spark: set JAVA_HOME in wrapper

### PR DESCRIPTION
**Pull request by forevergenin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Added java as dependency for apache-spark

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you explain why these are needed (the test works without them)? Thanks!

**Comment by forevergenin** [comment]
I have installed `jenv` on my machine and the `spark-shell` doesn't work if I don't set JAVA_HOME manully in my environment. The test also fails with `jenv` case. I am getting the below mentioned error message.
`/usr/local/Cellar/apache-spark/1.6.1/libexec/bin/spark-class: line 87: /Users/premsubr/.jenv/versions/system/bin/java: No such file or directory`

This change fixes the issue.

**Comment by MikeMcQuaid** [comment]
@forevergenin Ok that explains `JAVA_HOME` but why does `SPARK_HOME` need set?

**Comment by jasontedor** [comment]
I'm not able to replicate the problem here:

```bash
os-x-el-capitan:~ jason$ mkdir jdk8
os-x-el-capitan:~ jason$ cd jdk8
os-x-el-capitan:jdk8 jason$ jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/
oracle64-1.8.0.92 added
1.8.0.92 added
1.8 added
os-x-el-capitan:~ jason$ jenv add /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/
oracle64-9-ea added
9-ea added
There is already a 9-ea JDK managed by jenv
Do you want to override (type y to confirm)? y
9-ea added

os-x-el-capitan:jdk8 jason$ jenv local oracle64-1.8.0.92
os-x-el-capitan:jdk8 jason$ echo $JAVA_HOME

os-x-el-capitan:jdk8 jason$ brew list
apache-spark    gradle          jenv
os-x-el-capitan:jdk8 jason$ ls -al /usr/local/bin/spark-shell 
lrwxr-xr-x  1 jason  admin  44 Jun  4 19:19 /usr/local/bin/spark-shell -> ../Cellar/apache-spark/1.6.1/bin/spark-shell
os-x-el-capitan:jdk8 jason$ spark-shell
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's repl log4j profile: org/apache/spark/log4j-defaults-repl.properties
To adjust logging level use sc.setLogLevel("INFO")
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.6.1
      /_/

Using Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_92)
Type in expressions to have them evaluated.
Type :help for more information.
Spark context available as sc.
16/06/04 19:22:23 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/06/04 19:22:23 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/06/04 19:22:30 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/06/04 19:22:30 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
16/06/04 19:22:33 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/06/04 19:22:33 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/06/04 19:22:38 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/06/04 19:22:39 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
SQL context available as sqlContext.

scala> Stopping spark context.
os-x-el-capitan:jdk8 jason$
```

**Comment by forevergenin** [comment]
@jasontedor did you try running `spark-shell` without configuring `jenv` ?
That use case is still failing for me.

**Comment by forevergenin** [comment]
@MikeMcQuaid `SPARK_HOME` is not required.

**Comment by jasontedor** [comment]
> did you try running `spark-shell` without configuring `jenny` (without running `jenv local oracle64-1.8.0.92`)?

Yes, and I think that what you're running into is because you haven't configured a global JVM through `jenv`.

**Comment by forevergenin** [comment]
@jasontedor Thanks ! That fixed the issue for me.

**Comment by MikeMcQuaid** [comment]
Thanks both!

**Pull request closed without merging**
