### PR TITLE
oj 1.21.5 (new formula)

### PR DESCRIPTION
**Pull request by ohler55**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This adds the oj application. I think it meets all the guidelines. I may have missed something though.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chbrown** [comment]
_Incredible_ timing

---

* [x] Is your formula's namesake aware of the project and/or verifiably deceased?

**Comment by ohler55** [comment]
Not sure what you mean. If you are referring to the Ruby Oj then that would be me also. OjG has an app called oj mostly for recognition of being the same author and also an optimize JSON processor but for Go hence the G tacked on the end.

**Comment by chbrown** [comment]
(It was a joke) https://www.google.com/search?q=oj -> 
image

**Comment by ohler55** [comment]
Ah, different Oj completely. <shiver>

**Pull request merged**
