### PR TITLE
use secure urls

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by UniqMartin** [comment]
Though not modified by you, the `shismtracker` tarball seems to have moved to <https://bitbucket.org/Storlek/schismtracker/get/20120105.tar.bz2>. Can you verify this and the other URLs in that formula and update them as needed? Thanks!

**Comment by vszakats** [comment]
Thanks for the hint, urls updated. I've updated the revision as well, please shout if this was not necessary.

**Comment by UniqMartin** [comment]
Thanks, but neither the `revision 1` nor the structural changes to the `head do` block and the `autoconf` dependency were necessary, just a change of the URLs. However, the changed URL seems to have also changed the archive contents and consequently broken the build. I'll have a look. Let's drop the changes to `shismtracker` from this PR for now, so that we can get the rest merged …

**Comment by vszakats** [comment]
Okay, `schismtracker` deleted completely for now.

**Comment by vszakats** [comment]
Possibly off topic, recently I'm getting this error when trying to `brew audit`:
```
$ brew audit --online --strict ./schismtracker.rb 
error: could not lock config file /usr/local/.git/config: Permission denied
```
(my user is a non-admin, but this very use-case used to work, up until the recent past.)

**Comment by UniqMartin** [comment]
> Possibly off topic, recently I'm getting this error when trying to `brew audit`:

Are you sometimes invoking `brew` via `sudo brew`? More recently we've started using `git config` to keep track of certain repository-related information (hence writing to `.git/config`) and if one of those writes happens in a `sudo brew` session, that would cause this issue.

It should be fixable by changing the ownership of that file back to your normal user, but if you can reproduce that, i.e. find out which invocation causes the ownership/permissions to change, please let us know by reporting that to https://github.com/Homebrew/brew/issues.

**Comment by UniqMartin** [comment]
> Okay, `schismtracker` deleted completely for now.

Thanks! Are you up for making the URL changes and any necessary changes to the build process in the formula as a new PR? Would be much appreciated, but if not, I'll have a look.

I'll wait for the build of this PR in its current state to finish, but will merge it then.

**Comment by vszakats** [comment]
I never `sudo brew`, instead I login as admin user on update/upgrade/cleanup and run `brew` as-is. Can't spot anything irregular with `config` ownership, compared to other brew files.

**Comment by vszakats** [comment]
...but, it seems `brew audit` now requires write access to the brew files, which is unexpected because one would imagine such operation would not need to modify state.

**Comment by vszakats** [comment]
It seem to mean `brew audit` became unusable, unless one is operating under an admin account, or the local homebrew repo is moved under an admin account. None of these is practical. What's even more strange is that `./<formula.rb>` is supposed to operate solely on the local sandbox, not the live one.

(I'll resubmit `schismtracker.rb` separately.)

**Comment by UniqMartin** [comment]
> I never `sudo brew`, instead I login as admin user on update/upgrade/cleanup and run `brew` as-is. Can't spot anything irregular with `config` ownership, compared to other brew files.

This could be an explanation of the issue. I'll try to reproduce it. I suspect most people use the same local user for all `brew` operations and thus won't experience the issue.

> ...but, it seems brew audit now requires write access to the brew files, which is unexpected because one would imagine such operation would not need to modify state.

Unless I'm mistaken it doesn't need write access, but it started interacting with the Git repository not too long ago. (It's checking the history of formulae to make sure a newer formula is not accidentally replaced by an older version and makes sure the `revision` is monotonic and reset when the version is bumped.)

**Comment by vszakats** [comment]
Thank you, it'd be nice to have it working again in this scenario. Now it's a bit of a blind flight.

**Comment by UniqMartin** [comment]
Merged in 836f178030a31f4519daa3e4bd172cd117244e67. Thank you for another contribution to Homebrew, @vszakats! :tada:

> (I'll resubmit `schismtracker.rb` separately.)

Thanks! ❤️

**Pull request closed without merging**
