### PR TITLE
libatomic_ops 7.4.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
A test would be nice, otherwise 👍.

**Comment by ilovezfs** [comment]
`make` runs three tests.

**Comment by DomT4** [comment]
You know what I mean.

**Comment by ilovezfs** [comment]
Indeed, I do.

**Comment by ilovezfs** [comment]
will worry about a test later.

**Pull request closed without merging**
