### PR TITLE
app-engine-go-{32,64}: migrate to cask google-cloud-sdk

### PR DESCRIPTION
**Pull request by woodruffw**
These are full of prebuilt binaries, and as such not compatible with our source-only policy.

cc @ilovezfs

### CODE REVIEW

**Comment by ilovezfs** [comment]
@commitay @vitorgalvao any thoughts on whether we should

1) just delete this
2) treat this as a migration to the preexisting cask google-cloud-sdk
3) treat this as a migration to a new cask google-app-engine (or whatever name)
4) something else

See https://cloud.google.com/appengine/docs/standard/go/download

>The original App Engine SDK is superseded by the Cloud SDK and its gcloud commands. If your systems or scripts rely on the appcfg or goapp commands, you can download and install the original App Engine SDK by following the instructions below. If you do not install the Cloud SDK, you will not have the gcloud commands on your system.

**Comment by ilovezfs** [comment]
fwiw
```
cask 'app-engine-go-64' do
  version '1.9.62'
  sha256 'abc350f5d630aa06e84b5f8f58e7b79c421b591e4419010da6f159911f2e0306'

  # storage.googleapis.com/appengine-sdks/featured was verified as official when first introduced to the cask
  url "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_darwin_amd64-#{version}.zip"
  name 'app-engine-go-64'
  homepage 'https://cloud.google.com/appengine/docs/go/'

  binary "#{staged_path}/go_appengine/appcfg.py"
  binary "#{staged_path}/go_appengine/bulkloader.py"
  binary "#{staged_path}/go_appengine/bulkload_client.py"
  binary "#{staged_path}/go_appengine/dev_appserver.py"
  binary "#{staged_path}/go_appengine/download_appstats.py"
  binary "#{staged_path}/go_appengine/goapp"

  postflight do
    FileUtils.ln_sf("#{staged_path}/go_appengine", "#{HOMEBREW_PREFIX}/share/app-engine-go-64")
  end

  uninstall_postflight do
    FileUtils.rm("#{HOMEBREW_PREFIX}/share/app-engine-go-64")
  end
end
```

**Comment by commitay** [comment]
1 or 2

`app-engine-go` isn't part of the default install for the `google-cloud-sdk` Cask so there might be some user confusion if it's treated as a migration.

Probably wouldn't add it as a Cask as it's superseded.

**Comment by ilovezfs** [comment]
@commitay regarding the user confusion, a caveat mentioning `gcloud components install app-engine-go` in the `google-cloud-sdk` cask might help with that?

**Comment by ilovezfs** [comment]
@commitay @vitorgalvao I have migrated them to the google-cloud-sdk cask.

**Pull request merged**
