### PR TITLE
xctesthtmlreport 2.3.1

### PR DESCRIPTION
**Pull request by tylervick**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
still failed on 11
```
  [5/6] Compiling XCTestHTMLReportCore String+Path.swift
  remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[6/7] Compiling XCTestHTMLReport Version.swift
  /private/tmp/xctesthtmlreport-20230115-4257-hs4y9g/XCTestHTMLReport-2.3.1/Sources/XCTestHTMLReport/XCTestHtmlReport.swift:82:1: error: 'XCTestHtmlReport' is annotated with @main and must provide a main static function of type () -> Void or () throws -> Void.
  @main
  ^
  /private/tmp/xctesthtmlreport-20230115-4257-hs4y9g/XCTestHTMLReport-2.3.1/Sources/XCTestHTMLReport/XCTestHtmlReport.swift:62:19: warning: 'resultBundlePath' is deprecated: Result bundle paths may be passed as arguments.
          results + resultBundlePath
                    ^
```

**Comment by chenrui333** [comment]
@tylervick what is the xcode requirement for this PR?

**Comment by chenrui333** [comment]
#120759

**Comment by tylervick** [comment]
> @tylervick what is the xcode requirement for this PR?

Xcode 13.0 is the minimum requirement, this is also the version that shipped with Swift 5.5. I'm thinking the problem has to do with the `uses_from_macos "swift"` setting. 
For instance, Big Sur was released prior to Xcode 13.0 (with Swift 5.5). I haven't tested this yet, but it's possible that selecting the OS built-in Swift differs from the one Xcode provides.. The failure in this PR supports my hunch since the compiler failed to recognize newer `async` syntax.

Let me know if you have other thoughts/areas I can investigate further into. Fortunately it looks like GitHub's hosted runners still provide Big Sur builders. I'll add a job to our XCTestHTMLReport project to verify this in CI going forward.

**Pull request closed without merging**
