### PR TITLE
lumo 1.6.0

### PR DESCRIPTION
**Pull request by anmonteiro**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by anmonteiro** [comment]
The Yosemite failure looks bogus. I think it may go away if the build is retried.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Failed on Yosemite again.

**Comment by anmonteiro** [comment]
The error seems non-deterministic to me. Can we retry again and I'll investigate more if it fails?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by anmonteiro** [comment]
@ilovezfs glad it's passing now. I wonder what caused those failures. I'll try to identify what caused it not to be reliable in the first place.

**Comment by ilovezfs** [comment]
Let's send it through again!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by anmonteiro** [comment]
it had passed the tests though, are you just making sure it passes a second time? :)

**Comment by ilovezfs** [comment]
>are you just making sure it passes a second time?

Yup. May even do a third and a fourth …

**Comment by anmonteiro** [comment]
sounds good!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@anmonteiro triggered the failure again: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4021/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_lumo/

So we have a bit of a problem.

**Comment by ilovezfs** [comment]
@anmonteiro let's try it with the same steps as your `.travis.yml`

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by anmonteiro** [comment]
@ilovezfs the failure doesn't look related to lumo to me, it just looks like we're inheriting an upstream bug (perhaps from the ClojureScript compiler)

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@anmonteiro do you mean an issue with boot-clj?

**Comment by anmonteiro** [comment]
Boot is just a build system. I mean with the ClojureScript compiler which is something that Boot knows how to build but a separate project altogether

**Comment by ilovezfs** [comment]
looks like it failed on Yosemite again: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4049/version=yosemite/console

**Comment by ilovezfs** [comment]
@anmonteiro can we depend on `closure-compiler` then?

**Comment by ilovezfs** [comment]
Or I guess `clojurescript`?

**Comment by anmonteiro** [comment]
We already depend on ClojureScript (through Boot).

Boot is to Clojure what Maven is to Java. ClojureScript is just a JAR

**Comment by ilovezfs** [comment]
Seems weird that it's only happening on Yosemite.

**Comment by anmonteiro** [comment]
Yeah, ClojureScript has had problems vefore calculating the dependency graph. I wonder if there's still a non-deterministic bug that could still be causing it (under very weird circumstances).

The good news is once Lumo builds it doesn't need to build those files again, since it builds a single binary.

**Comment by ilovezfs** [comment]
Hurray! Yosemite is exonerated. Sierra has failed too: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4050/version=sierra/console

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@anmonteiro do you mind filing a bug with ClojureScript upstream about this?

**Comment by anmonteiro** [comment]
Yeah I've brought it up now

**Comment by ilovezfs** [comment]
@anmonteiro thank you! Do you have a link to the report?

**Comment by anmonteiro** [comment]
sure thing: https://dev.clojure.org/jira/browse/CLJS-2153

**Comment by ilovezfs** [comment]
@anmonteiro perfect, thanks.

**Comment by ilovezfs** [comment]
Thanks @anmonteiro! Shipped! :bulb:

**Comment by anmonteiro** [comment]
@ilovezfs so the build passed in the end?

**Comment by ilovezfs** [comment]
@anmonteiro yes. There were a ton of successful builds along the way :)

**Comment by anmonteiro** [comment]
awesome, thanks. I'll make sure to follow up on the CLJS issue, currently looks like a "parallel build" issue so I'll disable concurrency for the next foreseeable releases.

Thanks once again for your patience!

**Comment by ilovezfs** [comment]
@anmonteiro no problem at all. Thanks for reporting upstream!

**Pull request closed without merging**
