### PR TITLE
ballerina 1.2.14

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ apply2files - bin/ballerina

**Comment by cho-m** [comment]
May be related to https://github.com/ballerina-platform/ballerina-lang/issues/28800 (and PR attempt #72412)

Upstream may have renamed executable as in-between step before moving to v2 release.
```console
❯ ls ballerina-1.2.14/bin
bal  bal.bat
```

**Comment by nandahkrishna** [comment]
Do we want to add a `bal` alias? Just asking based on comments from the linked upstream issue.

**Comment by chenrui333** [comment]
I think we can add an alias, I will comment back in that issue as well.

**Review by nandahkrishna — APPROVED** [review]
Pushed again because there was a problem with the alias, this looks good to me but I'm not merging right away (in case anyone else has other feedback).

**Pull request closed without merging**
