### PR TITLE
dasel 2.0.0

### PR DESCRIPTION
**Pull request by TomWright**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    Minitest::Assertion: --- expected
  +++ actual
  @@ -1,2 +1 @@
  -"Tom
  -Jim"
  +""
```

**Comment by TomWright** [comment]
Hi @chenrui333, that failed test is a flaky test due to JSON array decode ordering not being guaranteed.

I have a fix planned for this but in any case it's not a broken implementation, just a flaky test.

**Comment by chenrui333** [comment]
> Hi @chenrui333, that failed test is a flaky test due to JSON array decode ordering not being guaranteed.
> 
> I have a fix planned for this but in any case it's not a broken implementation, just a flaky test.

yeah, feel free to update test. :) I was mostly trying to get the build passed.

**Comment by chenrui333** [comment]
I failed to run the original test in my local though.

**Comment by chenrui333** [comment]
```
$ echo "[{\"name\": \"Tom\"}, {\"name\": \"Jim\"}]" > json
$ dasel --plain -p json -m '.[*].name'
Error: unknown flag: --plain
```

```
$ echo "[{\"name\": \"Tom\"}, {\"name\": \"Jim\"}]" > json
$ dasel -f json -r json '.[*].name'
$
```

**Review by fxcoudert — APPROVED** [review]

**Comment by TomWright** [comment]
@chenrui333 Sorry that's my bad - these release is a v2 with breaking changes to the syntax. I forgot that test line was there as these PR's are auto-created by a GH action on release.

It looks like you updated the test to get it working? If you'd like me to change anything let me know 👍

**Comment by chenrui333** [comment]
yeah, just want to get a confirmation with you 😄 Should be good to go.

**Pull request closed without merging**
