### PR TITLE
switch to HTTPS for Git access on sf.net #2

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by vszakats** [comment]
A dependency named `evince` fails:
```
==> Pouring evince-3.22.1.sierra.bottle.tar.gz
==> /usr/local/opt/glib/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas
==> /usr/local/opt/gtk+3/bin/gtk3-update-icon-cache -f -t /usr/local/share/icons/hicolor
==> /usr/local/opt/shared-mime-info/bin/update-mime-database /usr/local/share/mime
Last 150 lines from /Users/brew/Jenkins/pr-core/version/sierra/logs/evince/post_install.03.update-mime-database:
2017-03-09 22:53:38 +0000

/usr/local/opt/shared-mime-info/bin/update-mime-database
/usr/local/share/mime

I/O error : Operation not permitted
I/O error : Operation not permitted
Failed to write XML file; For permission problems, try rerunning as root
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall evince`
```

The `downloads.sourceforge.net` URLs seem to be working again, that was the other failure.

**Comment by vszakats** [comment]
I'd appreciate a CI bump here to see what errors remain now that sf.net recovered.

**Comment by vszakats** [comment]
Thank you. Only the above `evince` failure remains.

**Comment by vszakats** [comment]
`djvulibre` moved to #10905. (in the hope the `evince` failure will move with it)

**Comment by vszakats** [comment]
Clean finally.

**Comment by ilovezfs** [comment]
Perfect. Thanks @vszakats

**Pull request merged**
