### PR TITLE
liblwgeom: deprecate

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
same artifact as postgis

**Comment by chenrui333** [comment]
```
==> make install DESTDIR=/private/tmp/liblwgeom-20201123-21175-q2yt6m/postgis-3.0.3/stage
make: Nothing to be done for `install'.
Warning: tried to install empty array to /usr/local/Cellar/liblwgeom/3.0.3/lib
Warning: tried to install empty array to /usr/local/Cellar/liblwgeom/3.0.3/include
Error: Empty installation
```

**Comment by chenrui333** [comment]
relates to https://github.com/postgis/postgis/pull/348

**Comment by fxcoudert** [comment]
It has 1,107 monthly installs, so clearly it's useful to people, no?

**Comment by SMillerDev** [comment]
Should probably deprecate it to make people aware of it before we disable it.

**Comment by chenrui333** [comment]
Sure, I will change to deprecate then. 👍

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
