### PR TITLE
freeling 4.1.1

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Patch still required for 4.1.1

https://github.com/TALP-UPC/FreeLing/commit/5e323a5

https://github.com/TALP-UPC/FreeLing/blob/4.1.1/src/libfreeling/CMakeLists.txt#L43

**Comment by SeekingMeaning** [comment]
```
==> brew audit --skip-style freeling --online --git
==> FAILED
Error: 1 problem in 1 formula detected
freeling:
  * The URL http://nlp.lsi.upc.edu/freeling/ is not reachable
```

http://nlp.lsi.upc.edu/freeling/ is still up from what I can tell

**Comment by SeekingMeaning** [comment]
Error uploading bottle(s)?

```
Uploading 'bottles/freeling--4.1.1.mojave.bottle.tar.gz' (99%)
Total file: 7 ---- Processed file: 6 (85%)
Unable to copy file to server StatusCode=BadRequest: Bad Request. Source file path: /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/freeling--4.1.1.mojave.bottle.tar.gz. Target server path: bottles/freeling--4.1.1.mojave.bottle.tar.gz
Cannot continue uploading files, so draining upload queue of 0 items.
Fail to upload '/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/freeling--4.1.1.mojave.bottle.tar.gz' due to 'Critical failure uploading '/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/freeling--4.1.1.mojave.bottle.tar.gz''.
GitHub.Runner.Plugins.Artifact.UploadFailedException: Critical failure uploading '/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/freeling--4.1.1.mojave.bottle.tar.gz'
   at GitHub.Runner.Plugins.Artifact.FileContainerServer.UploadAsync(RunnerActionPluginExecutionContext context, Int32 uploaderId, CancellationToken token)
File error 'Critical failure uploading '/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/freeling--4.1.1.mojave.bottle.tar.gz'' when uploading file '/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/freeling--4.1.1.mojave.bottle.tar.gz'.
Associated artifact bottles (4313160) with run #26308
##[error]Critical failure uploading '/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/freeling--4.1.1.mojave.bottle.tar.gz'
##[error]Exit code 1 returned from process: file name '/Users/brew/actions-runner/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Review by SMillerDev — APPROVED** [review]
Thanks @SeekingMeaning ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
