### PR TITLE
chezmoi 2.33.1

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by twpayne** [comment]
Please do not merge this.

This PR was created before chezmoi 2.33.1 was released.

Source: I am the author of chezmoi.

**Comment by ZhongRuoyu** [comment]
Thanks @twpayne. Then we'll wait for the release to be finalised.

**Comment by twpayne** [comment]
OK, `v2.33.1` is now released with commit ID `bc4478d84f59ea38084cf7e58b9226278d0e046d`.

https://github.com/twpayne/chezmoi/releases/tag/v2.33.1

**Comment by ZhongRuoyu** [comment]
Thanks! I've updated the formula accordingly.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
