### PR TITLE
sbcl 2.1.11

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
The CI tests for Intel are all fine -- the 12 failure is trivial.

However, the two CI tests for Arm are an issue, and as I do not have an Arm-based Mac I am not sure how to proceed here?

**Comment by SMillerDev** [comment]
The error should be reported upstream at least

**Comment by miccal** [comment]
> The error should be reported upstream at least

Sorry @SMillerDev, but I am not sure what _exactly_ to report to upstream?

**Comment by SMillerDev** [comment]
The build failures on ARM likely need some help from upstream to resolve.

**Comment by miccal** [comment]
A release candidate for 2.1.11 has been released: https://sourceforge.net/projects/sbcl/files/sbcl-rc/

Release notes:
```
changes relative to sbcl-2.1.10:
  * optimization: The compiler assignment-converts functions much more
    aggressively, meaning that local or non-entry block-compiled functions
    which always return to the same place are automatically converted into the
    equivalent loop or goto control structures, increasing opportunities for
    optimization as well. For example, this is often beneficial for state
    machines written in terms of LABELS or iteration constructs written in
    terms of tail-recursive structures. Many more situations in which this
    "auto-inlining" (or "contification") applies are now recognized, such as
    in the following:

    > (DEFUN FOO (V) (FLET ((F (X) ...)) (BAR (IF (READ) (F V) (F (+ V V))))))

    Here the body of F is directly substituted into the control point where
    the IF expression returns. Note that unlike inlining, this optimization
    never increases code size.
  * enhancement: improved reporting of code deletion notes.
  * minor change: *COMPILE-PRINT* now defaults to NIL. T gives the old
    behavior of echoing top level forms. Users who want to see a report of the
    phases of compilation can use *COMPILE-PROGRESS* and the corresponding
    COMPILE-FILE :PROGRESS argument.
```

**Comment by metayan** [comment]
sbcl-2.1.11 has been released.

**Comment by miccal** [comment]
Still failing on Arm :(

**Comment by miccal** [comment]
Note to self: https://github.com/macports/macports-ports/blob/master/lang/sbcl/Portfile

**Pull request closed without merging**
