### PR TITLE
lxc 5.11

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
Really? This is just the normal monthly version bump...

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> Really? This is just the normal monthly version bump...

you can also use `brew bump --open-pr lxc`, it would autofill some info :)

**Comment by stgraber** [comment]
I'd need to actually be using homebrew in the first place. I'm not, I'm just the upstream developer for that project and send a PR every time we make a release, I don't actually use this stuff myself.

**Comment by chenrui333** [comment]
then filling some basically info like `bump the version` when creating the PR would be fine as well. Thanks for keeping it up to date.

**Pull request closed without merging**
