### PR TITLE
bam 0.5.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- use full path in the test
- minor style changes in the test
- patch a bug with bam's new CC, CXX, etc. detection

### CODE REVIEW

**Comment by ilovezfs** [comment]
An alternative to the patch is to work around it in the test with
```
    ENV["CC"] = ENV.cc.split("/")[-1]
    ENV["CXX"] = ENV.cxx.split("/")[-1]
```

**Comment by ilovezfs** [comment]
@UniqMartin Any opinion on the patch vs. the workaround?

**Comment by UniqMartin** [comment]
I'm definitely leaning towards the patch, though ideally we'd hear back from upstream how they feel about this and whether they wish to fix the issue as suggested. (I'd be surprised if they object, but who knows.)

**Comment by ilovezfs** [comment]
PR refreshed with a patch in formula-patches. Upstream has yet to comment on the issue.

**Comment by ilovezfs** [comment]
upstream fixed it! :fireworks: https://github.com/matricks/bam/commit/27b28f0956a78844e73aa94fee7d0187c9b68bbd

**Comment by ilovezfs** [comment]
PR refreshed using upstream's patch instead.

**Pull request closed without merging**
