### PR TITLE
Biogeme 2.6a

### PR DESCRIPTION
**Pull request by michelbierlaire**
- [X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by neutric** [comment]
Please provide a PR without conflicts by basing it on the current master branch.

**Comment by michelbierlaire** [comment]
I am not sure to understand what to do. 

I have a new version of the software. Therefore, I have updated the formula to point to the new distribution (and recalculated the sha256), and I have followed step by step the instructions on the webpage, where <some-descriptive-name> is the name of the new version. “biogeme-2.6a”:

brew update # required in more ways than you think (initializes the brew git repository if you don't already have it)
cd $(brew --repo homebrew/core)
# Create a new git branch for your formula so your pull request is easy to
# modify if any changes come up during review.
git checkout -b <some-descriptive-name>
git add Formula/foo.rb
git commit

When I look at the conflicts on github, they are exactly the implemented changes. 

Actually, I could not find an example or explicit instructions to submit a new version. Therefore, I assume that I have missed something in the procedure. 

Help would be appreciated.

Thanks,

Michel



> On 23 avr. 2017, at 22:09, neutric <notifications@github.com> wrote:
> 
> Please provide a PR without conflicts by basing it on the current master branch.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Homebrew/homebrew-core","title":"Homebrew/homebrew-core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Homebrew/homebrew-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@neutric in #12804: Please provide a PR without conflicts by basing it on the current master branch."}],"action":{"name":"View Pull Request","url":"https://github.com/Homebrew/homebrew-core/pull/12804#issuecomment-296485083"}}}

Michel Bierlaire
Transport and Mobility Laboratory
School of Architecture, Civil and Environmental Engineering
EPFL - Ecole Polytechnique Fédérale de Lausanne
http://transp-or.epfl.ch
http://people.epfl.ch/michel.bierlaire

**Comment by ilovezfs** [comment]
@michelbierlaire I believe I have fixed it for you. Please check if it looks correct to you.

**Comment by neutric** [comment]
@michelbierlaire To update a formula, follow the instructions for submitting a new formula that you quoted above and leave out the `git add Formula/foo.rb` step as the file in question is already tracked by git. Or check out [`brew bump-formula-pr`](https://github.com/Homebrew/brew/blob/ceb1629ad7aeec4c9e9c264efb29b59a96f8556c/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L1-L35).

**Comment by michelbierlaire** [comment]
Thank you. So, if I understand correctly, this upgrade has been implemented. And I have to use the "bump-formula-pr" for he next one. I really appreciate your help.

**Comment by neutric** [comment]
The upgrade is now implemented, yes. And you don't have to use `brew bump-formula-pr`, but it makes the update process easier and faster especially in cases where the only change to a formula is to update the version.

**Comment by michelbierlaire** [comment]
Thank you! I’ll know it for next time.

> On 24 avr. 2017, at 19:45, neutric <notifications@github.com> wrote:
> 
> The upgrade is now implemented, yes. And you don't have to use brew bump-formula-pr, but it makes the update process easier and faster especially in cases where the only change to a formula is to update the version.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Homebrew/homebrew-core","title":"Homebrew/homebrew-core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Homebrew/homebrew-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@neutric in #12804: The upgrade is now implemented, yes. And you don't have to use `brew bump-formula-pr`, but it makes the update process easier and faster especially in cases where the only change to a formula is to update the version."}],"action":{"name":"View Pull Request","url":"https://github.com/Homebrew/homebrew-core/pull/12804#issuecomment-296766033"}}}

Michel Bierlaire
Transport and Mobility Laboratory
School of Architecture, Civil and Environmental Engineering
EPFL - Ecole Polytechnique Fédérale de Lausanne
http://transp-or.epfl.ch
http://people.epfl.ch/michel.bierlaire

**Pull request closed without merging**
