### PR TITLE
mongodb-atlas-cli: add mongodb-atlas alias

### PR DESCRIPTION
**Pull request by andreaangiolillo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This PR adds the alias `mongodb-atlas` the `mongodb-atlas-cli `formula

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Do we really need five aliases for this formula? That seems a bit much.

**Comment by andreaangiolillo** [comment]
Hi @carlocab, 
my understanding was that homebrew doesn’t have a limit on the number of aliases per formula [#3065](https://github.com/Homebrew/discussions/discussions/3065#discussioncomment-2330084). The main reason for having these 5 aliases is that we believe `mongodb-atlas-cli` may not be easy to remember and customers may type some combinations of this name. Let me know how many aliases we can have if you have a strong opinion about this.

Thank you very much!

**Comment by SMillerDev** [comment]
Well, the aliases are not a replacement for `brew search`. It's really just meant as an alias:

> an assumed or additional name that a person (such as a criminal) sometimes uses

Unless `mongodb-atlas-cli` is also commonly known under all these other names, they should not be an alias, no matter how forgetful you think your customers are.

**Comment by andreaangiolillo** [comment]
We would like to add only the alias `mongodb-atlas` if possible as we're going to refer to the atlascli in this way in different places depending on the context. Let me know if you are okay with this change and I will update the PR.

Thank you

**Comment by SMillerDev** [comment]
Just an alias without the `-cli` suffix makes sense to me

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request merged**
