### PR TITLE
salt: migrate to python@3.9

### PR DESCRIPTION
**Pull request by fxcoudert**
Splitting from https://github.com/Homebrew/homebrew-core/pull/62560
Updating `cffi`

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is weird, maybe we're not building the right version of cffi?

```
    In file included from c/_cffi_backend.c:7552:
    In file included from c/cffi1_module.c:20:
    c/call_python.c:26:30: error: incomplete definition of type 'struct _is'
        builtins = tstate->interp->builtins;
                   ~~~~~~~~~~~~~~^
```

**Comment by fxcoudert** [comment]
Even if we provide a newer cffi in the resources, it downloads and uses cffi 1.12.2
It actually downloads a lot of other packages, it seems…

**Comment by bayandin** [comment]
> It actually downloads a lot of other packages, it seems…

It is. Salt installs of its dependencies + we use resources for installing additional ones (the switch was done in https://github.com/Homebrew/homebrew-core/pull/52835)

If we want to install a custom version of `cffi`, we need to use inreplace it in https://github.com/saltstack/salt/blob/v3001.1/pkg/osx/req.txt#L4 (and it looks like we'll need to rework it for the next version of salt because of https://github.com/saltstack/salt/pull/56904)

**Comment by fxcoudert** [comment]
Upstream report: https://github.com/saltstack/salt/issues/58809

**Comment by fxcoudert** [comment]
Closing, will reopen once upstream has fixed this.

**Comment by MikeMcQuaid** [comment]
Given the failure is only on 10.14 and 10.13: have you checked those files actually exist in the macOS workers on those versions?

**Comment by MikeMcQuaid** [comment]
Yes, looking at the code: I'm almost certain these frameworks don't exist on these macOS versions.

I've opened https://github.com/Homebrew/brew/pull/9031 which should fix this failure when it's merged and CI is rerun. It may be that `brew test` fails after that point, though, in which case the error message should be adjusted in `brew linkage --test` and the PR perhaps reverted.

**Comment by MikeMcQuaid** [comment]
Rerunning CI now https://github.com/Homebrew/brew/pull/9031 is merged.

**Comment by MikeMcQuaid** [comment]
Looks good now. Seems those broken system framework referenced didn't matter 🤷🏻.

@fxcoudert should be ✅ to merge.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
