### PR TITLE
elixir 1.4.5

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
@JCount Why the "do not merge" label?

**Comment by austinsmorris** [comment]
Does this require erlang 20 first?  is that why "do not merge"?

**Comment by praveenperera** [comment]
This is not dependant on Erlang 20, it will work >= Erlang 18.0.

**Comment by JCount** [comment]
If this gets merged before `erlang`, this would have to have a revision added for the new `erlang` version, and rebuilt. `erlang` should be mergeable soon, and waiting will save people who use the bottles from having to upgrade `elixir` twice.

**Comment by PhillippOhlandt** [comment]
@JCount Ah, makes sense. Maybe it would be better to change the label to `do not merge yet` and add a little explanation on future issues with that label so people won't get confused and think it won't get merged at all.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by gmile** [comment]
@ilovezfs is there anything else blocking this?

**Comment by ilovezfs** [comment]
@gmile no ... that's why I've removed `do not merge`.

**Pull request closed without merging**
