### PR TITLE
dlite: disable

### PR DESCRIPTION
**Pull request by andig**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

dlite has seen the last commit in 2017, is without maintainer and hinders upgrade to go 1.15.6 in https://github.com/Homebrew/homebrew-core/pull/66355, hence I propose to remove.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for the PR, andig. The [preferred commit style](https://docs.brew.sh/Formula-Cookbook#commit) at Homebrew is:

>At Homebrew, we like to put the name of the formula up front like so: foobar 7.3 (new formula).

You need to change your commit message to something like `dlite: remove`.

**Comment by bayandin** [comment]
Let's disable it instead of deleting: `disable! date: "2020-12-17", because: :unmaintained`

**Comment by andig** [comment]
Would you lend a hand? Not sure where to put that.

**Comment by bayandin** [comment]
Sure, it should be between `bottle` block and `depends_on`: 
```diff
diff --git a/Formula/dlite.rb b/Formula/dlite.rb
index 7710c58b8c..d3e95cbcfc 100644
--- a/Formula/dlite.rb
+++ b/Formula/dlite.rb
@@ -16,6 +16,8 @@ class Dlite < Formula
     sha256 "d1244ccccc75ab8747a86c01aceeb25fee219617d9d4a2c3a3c6cd0bad45c0ee" => :yosemite
   end
 
+  disable! date: "2020-12-17", because: :unmaintained
+
   depends_on "go" => :build
 
   def install
```

A basic rule of thumb here — just add it somewhere and then run `brew audit --fix dlite` — it will fix style for you.

**Comment by carlocab** [comment]
Another hint: if you're not sure how to do something, look at other formulae. `grep`ping the core repo should make it easy.

**Comment by andig** [comment]
No luck with 

    ❯ brew audit --fix dlite
    warning: parser/current is loading parser/ruby26, which recognizes
    warning: 2.6.6-compliant syntax, but you are running 2.6.3.
    warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

hope the position works.

**Comment by iMichka** [comment]
> `bottle` (line 11) should be put before `disable!` (line 9)

**Pull request merged**
