### PR TITLE
icu4c 61.1

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
- `chakra` https://gist.github.com/commitay/6cf65b25bcaf82ade3974abb3a1ed46a

- `hfstospell` https://gist.github.com/commitay/ff27e5b97e9d912ff894a09ac9cf5b17

- `mapnik` https://gist.github.com/commitay/c0f2c7a96caf8ddb789b36c2f036d1da

- `node@8` https://gist.github.com/commitay/fb8b32937a8810cc482815e9f5995f3a

- `php` https://gist.github.com/commitay/60d1dbdc019af4bc523579cffcb2efee

- `widelands` https://gist.github.com/commitay/9bc9d72fcf057b5e48953b5013fb6891

- `zorba` https://gist.github.com/commitay/3de92343a3e8ea254f30d48c9a3e5909

**Comment by SMillerDev** [comment]
All of the failing projects are probably affected by http://site.icu-project.org/download/61#TOC-Migration-Issues

**Comment by SMillerDev** [comment]
PHP issue reported upstream here: https://bugs.php.net/bug.php?id=76153

**Comment by commitay** [comment]
Thanks @SMillerDev!

**Comment by ilovezfs** [comment]
We can add `ENV.append "CPPFLAGS", "-DU_USING_ICU_NAMESPACE=1"` to each of the formulae that broke as long as the breakage also gets reported to each upstream.

**Comment by ilovezfs** [comment]
For chakra `--extra-defines=U_USING_ICU_NAMESPACE=1`

**Comment by ilovezfs** [comment]
For mapnik
```
diff --git a/Formula/mapnik.rb b/Formula/mapnik.rb
index aba19d3..7705656 100644
--- a/Formula/mapnik.rb
+++ b/Formula/mapnik.rb
@@ -50,6 +50,7 @@ class Mapnik < Formula
             "CXX=\"#{ENV.cxx}\"",
             "PREFIX=#{prefix}",
             "CUSTOM_CXXFLAGS=\"-DBOOST_EXCEPTION_DISABLE\"",
+            "CUSTOM_DEFINES=-DU_USING_ICU_NAMESPACE=1",
             "ICU_INCLUDES=#{icu}/include",
             "ICU_LIBS=#{icu}/lib",
             "JPEG_INCLUDES=#{jpeg}/include",
```

**Comment by ilovezfs** [comment]
For widelands `ENV.append "CXXFLAGS", "-DU_USING_ICU_NAMESPACE=1"`

**Comment by chrmoritz** [comment]
For `node` the issue was fixed in https://github.com/nodejs/node/commit/b8f47b27571f8d763f811f017be3fb37d466c4fc. But the issue with `node@8` is somehow expected, because every node version officially only support the icu version it's ships with, which is icu 60 for `node@8`. So we either have to change the formula to build against the bundled icu again, build it with `-DU_USING_ICU_NAMESPACE=1` or apply said patch.

**Comment by ilovezfs** [comment]
For zorba, also `ENV.append "CXXFLAGS", "-DU_USING_ICU_NAMESPACE=1"`

**Comment by ilovezfs** [comment]
@chrmoritz why would upstream refuse to apply backwards compatible fixes to the 8.x branch? I don't think we should assume that.

**Comment by ilovezfs** [comment]
@srl295 any chance of getting https://github.com/nodejs/node/commit/b8f47b27571f8d763f811f017be3fb37d466c4fc back ported to Node 8.x LTS?

**Comment by srl295** [comment]
@chrmoritz 

> every node version officially only support the icu version it's ships with, which is icu 60 for node@8

That's not officially true (officially not true?)… I opened https://github.com/nodejs/node/pull/19624 2 days ago in master explicitly to support ICU 58.2. Actually I had opened  https://github.com/nodejs/Intl/issues/35 to explicitly document which versions are supported, but have not done it yet. I'll try to at least document something.

**Comment by ilovezfs** [comment]
>Please ask upstreams to actually use the namespace (that's what it's for!) instead of just adding the flag. Adding the flag is a bandage for the time being, but not the best practice.

@srl295 Definitely. We will ask them to use the namespace. We will not ask them to add the flag to their build scripts.

**Review by ilovezfs — APPROVED** [review]

**Pull request closed without merging**
