### PR TITLE
mesa: add license

### PR DESCRIPTION
**Pull request by chenrui333**
add license for mesa project.

license doc ref, https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/docs/license.rst

relates to #59220

### CODE REVIEW

**Comment by Rylan12** [comment]
I think we should hold off on the license based on the discussion in https://github.com/Homebrew/homebrew-core/issues/58225#issuecomment-669245181

**Comment by chenrui333** [comment]
> I think we should hold off on the license based on the discussion in [#58225 (comment)](https://github.com/Homebrew/homebrew-core/issues/58225#issuecomment-669245181)

Yeah, I read about it (I understand lots of the formulae additions are not perfect).

But dealing with the license situation one by one can potentially mitigate the issue, either way, our goal is to reach to a place that we can have licenses for every formulae.

With that being said, I think this license addition is clear and good from my perspective.

**Comment by Rylan12** [comment]
> But dealing with the license situation one by one can potentially mitigate the issue, either way, our goal is to reach to a place that we can have licenses for every formulae.

I agree, but I think we just aren't ready to start that yet.

If you disagree, can you bring it up in #58225 so we can get the opinions of other maintainers who have been involved?

**Comment by SMillerDev** [comment]
I don't think anyone suggested stopping all work on licenses. If we're sure about a license and it can be represented by the current implementation I don't see a reason to hold of.

**Comment by Rylan12** [comment]
Okay, this sounds like it was a misunderstaning on my part of what was said. My apologies!

CI seems broken though...

**Comment by dtrodrigues** [comment]
I think it needs a rebase in order to trigger the `CI-syntax-only` logic that was just added.

**Comment by chenrui333** [comment]
cancelled my PR build. I think the `tap_syntax` is fixed now?

**Comment by chenrui333** [comment]
interesting that `tests` are all hanging:
image

**Comment by dtrodrigues** [comment]
Those tests aren't hanging - they're yellow due to the branch protection checks. See https://github.com/Homebrew/homebrew-core/pull/59208#issuecomment-669586673

**Review by SMillerDev — DISMISSED** [review]

**Review by dtrodrigues — APPROVED** [review]

**Pull request merged**
