### PR TITLE
Add docker-diff

### PR DESCRIPTION
**Pull request by JoeNyland**

### CODE REVIEW

**Review by moul — APPROVED** [review]
LGTM

**Comment by JoeNyland** [comment]
Rebased off master

**Comment by fxcoudert** [comment]
Thanks for your submission. Unfortunately, we can't accept this as-is:

```
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

We also generally prefer that packages be submitted by someone other than their primary maintainer — it gives us an indication that a community will be keeping the package alive. In the mean time, you can always host this formula in a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

Sorry, and thanks again!

**Comment by JoeNyland** [comment]
> We also generally prefer that packages be submitted by someone other than their primary maintainer — it gives us an indication that a community will be keeping the package alive.

@fxcoudert I'm not a maintainer of the package. I'm a user of the package that's willing to maintain the package in Homebrew.

> GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)

I can't argue with this though 😞

**Pull request closed without merging**
