### PR TITLE
clamav 0.102.4

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by robertleeblairjr** [comment]
Closed a previous PR #58304 when I was attempting to squash two commits together. But, somehow referenced multiple past commits, as well, from my local. So, hopefully I wasn't the first to have done this and closed it to open this one.

**Review by SMillerDev — APPROVED** [review]
Thanks @robertleeblairjr ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by robertleeblairjr** [comment]
@SMillerDev I've found how to clone your fork locally in order to maintain and sync the forked repo. I suppose I could look up someone that's provided a script or alias to clean up branches that are created locally when submitting these PRs. Which would require to somehow push that the branch required deleting after the fact. What do you use to cut down on needing to remember or not remember the cleanup of these created branches?

**Comment by SMillerDev** [comment]
I don't really bother. Generally when I can't find anything through the clutter I clean all my branches. And then wait a couple of months for it to become a mess again 😅

**Comment by robertleeblairjr** [comment]
> I don't really bother. Generally when I can't find anything through the clutter I clean all my branches. And then wait a couple of months for it to become a mess again 😅

Sounds like everything else at home. People say it's messy when they're over. I just call it sufficiently organized chaos. Don't move anything from that pile or I'll never find it again.

**Pull request closed without merging**
