### PR TITLE
couchdb 3.3.0

### PR DESCRIPTION
**Pull request by janl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by janl** [comment]
There was a “`revision 1` should be removed” style error in the build. It’d be nice if `brew audit` caught that.

**Comment by janl** [comment]
just checking in as I’m not familiar with the test setup here: when testing on a particular platform, is the formula built for that platform as well? If not (say the formula is built on `x86_64` and tested on `arm64` that’s not gonna work with Erlang 24 or later because of the the new Erlang JIT that Rosetta can’t deal with properly).

**Comment by SMillerDev** [comment]
No, the whole stack is compiled for that architecture.

**Comment by chenrui333** [comment]
```
  Broken dependencies:
    /opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib (openssl@1.1)
```

looks like it needs `openssl@1.1`

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
