### PR TITLE
crystal 0.26.0

### PR DESCRIPTION
**Pull request by matiasgarciaisaia**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

We've officially released 0.26.0 some hours ago, so here we are once again :)

Thanks, as always!

### CODE REVIEW

**Comment by DomT4** [comment]
Does this remain incompatible with `llvm` 6.0.1, out of interest?

**Comment by matiasgarciaisaia** [comment]
The builds are failing, waiting on amberframework/amber#922 (and a subsequent upgrade in its formula?)

I'm not sure if this is the place, but we should discuss how will Crystal and its ecosystem fit within Homebrew before hitting 1.0.

Is Homebrew OK with waiting until amber gets updated to have crystal 0.26.0? In that case, we may have a Crystal-maintained tap that gets releases as soon as they're out, and then let Homebrew work its times.

Making Crystal releases depend on the rest of the ecosystem doesn't feel that good.

Once we hit 1.0 everything should be fine - dependent formulae won't break upon minor releases, so there won't be major issues then. But in the meantime, I'm not sure about the best way to go.

**Comment by bcardiff** [comment]
@DomT4 AFAIK llvm 6 should be supported in this version. There has been some PR for its support, yet we don't have CI for it yet.

Maybe the `llvm@5` can be relaxed.

**Comment by felixbuenemann** [comment]
I've been running Crystal 0.25.1 with the patches from https://github.com/crystal-lang/crystal/pull/6380 for some time with no problems, so I think changing the dependency from `llvm@5` to `llvm` should be fine.

**Comment by DomT4** [comment]
> (and a subsequent upgrade in its formula?)
> Is Homebrew OK with waiting until amber gets updated to have crystal 0.26.0?

If there's no imminent release planned upstream there we could apply a short-term patch, if necessary, and bump the revision. A formal release with compatibility would be ideal, but if compatibility is there but simply not in a release yet and we can patch in that compatibility with `patch do` blobs, I can be okay with that short-term.

> so I think changing the dependency from llvm@5 to llvm should be fine.

Sounds good!

**Comment by Willamin** [comment]
> Making Crystal releases depend on the rest of the ecosystem doesn't feel that good.

Totally agreed. Not everyone uses Amber. In my opinion, if someone's project requires an old version of a language, they should be using a version manager to ensure compatibility.

**Comment by Willamin** [comment]
Is there any chance we could get a home-brew option for something like `--latest` to grab the latest released Crystal version regardless of the compatibility of other packages like Amber? There's already a `--HEAD` option, so it seems like there's a bit of a precedent set.

**Comment by felixbuenemann** [comment]
Well it would be possible to add a devel block and bump it as soon as a new release is tagged, you could then specify `--devel` to install it.

Another option would be to move things like amber into their own tap(s) until crystal hits 1.0.

**Comment by matiasgarciaisaia** [comment]
Just changed `llvm@5` to `llvm`.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/3eb9fe91d152276c1d20bc8c6d30e8538c265f33. Thank you for the contribution @matiasgarciaisaia, and thanks to everyone who helped out with review/discussion/etc.

**Pull request closed without merging**
