### PR TITLE
harfbuzz 4.3.0

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by owine** [comment]
`pianod` and `root` linkage on Linux fixed in #100627

**Comment by owine** [comment]
Blocked by linkage changes in #100627

**Comment by owine** [comment]
Remains blocked

**Comment by cho-m** [comment]
Actually may be fine to merge this.

For Linux, linkage errors are only warnings. `gst-libav` and `pdfsandwich` are reoccurring CI failures but we don't have a fix yet. `root` was broken in `gcc` PR and isn't directly impacted by `harfbuzz`.

For macOS, I think `dynare` failed on Catalina in other PRs, but may want to make sure.

**Review by cho-m — APPROVED** [review]

**Comment by chenrui333** [comment]
10.15

```
brew test --retry --verbose dynare
```

linux

```
brew test --retry --verbose gst-libav
brew test --retry --verbose pdfsandwich
brew test --retry --verbose root
```

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
