### PR TITLE
v8 9.9.115.8

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
The two commits need to be squashed for bot to merge into master branch.

**Comment by Porkepix** [comment]
> The two commits need to be squashed for bot to merge into master branch.

This can't be done from GitHub UI on merge time? Because squashing locally and then pushing will trigger a new pipeline (that'll fail 1H later by timeout), right?
Plus I believe I already had other PRs with more than one commit that didn't had issues in that regard, why is this a problem on that one?

**Comment by chenrui333** [comment]
[This commit](https://github.com/Homebrew/homebrew-core/commit/ca5c8064d9f5718fb8e21b9e96e6c3969f55a3b4) was the challenge that I referred to, let's make sure the commits got squashed whenever you see `automerge-skip` label next time.

**Comment by Porkepix** [comment]
> [This commit](https://github.com/Homebrew/homebrew-core/commit/ca5c8064d9f5718fb8e21b9e96e6c3969f55a3b4) was the challenge that I referred to, let's make sure the commits got squashed whenever you see `automerge-skip` label next time.

@chenrui333 What do you mean here by challenge? How the `automerge-skip` makes things different here, I don't get the special treatment, is there some places where such differences are documented for me to take a look?

Also, it would have triggered a new pipeline that would have failed due to the missing long CI label, right?

**Pull request closed without merging**
