### PR TITLE
rust 1.31.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
Ooof, looks like building cargo is broken on macOS Sierra, due to missing symbols related to ALPN. /cc @alexcrichton is this issue known upstream?

**Comment by alexcrichton** [comment]
For compatibility with older versions of OSX the `curl-sys` crate needs a feature activated ([like this which rustc itself uses](https://github.com/rust-lang/rust/blob/118e052d84157a675649fe640e3d56f264475a3a/src/tools/rustc-workspace-hack/Cargo.toml#L62)). I think you can build with `--features curl-sys/force-system-lib-on-osx` though if you're building Cargo with Cargo!

**Comment by alex** [comment]
@alexcrichton thanks! let's see if this works!

**Comment by alex** [comment]
Bingo, it worked!

**Comment by fxcoudert** [comment]
Thanks @alex and @alexcrichton !

**Pull request closed without merging**
