### PR TITLE
dav1d 0.8.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`minidlna` and `mpd` currently fail to build on 11.0

**Comment by chenrui333** [comment]
```
Error: mpd--0.22.3_1.big_sur.bottle.tar.gz for upload doesn't exist!
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:58:in `upload'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:237:in `block (2 levels) in upload_bottles'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:219:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:219:in `block in upload_bottles'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:213:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:213:in `upload_bottles'
==> Uploading homebrew/bottles/mpd/0.22.3_1/mpd-0.22.3_1.big_sur.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-upload.rb:131:in `pr_upload'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew pr-upload --debug --bintray-org=homebrew` exited with 1.
```

**Comment by chenrui333** [comment]
I have some trouble merging this PR :(

```
==> Checking remote file homebrew/bottles/mpd-0.22.3_1.big_sur.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.11-266-g9539485\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --fail --silent --head https://dl.bintray.com/homebrew/bottles/mpd-0.22.3_1.big_sur.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.11-266-g9539485\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --fail --retry 3 --fail --silent --output /dev/null https://api.bintray.com/packages/homebrew/bottles/mpd
==> Uploading homebrew/bottles/mpd/0.22.3_1/mpd-0.22.3_1.big_sur.bottle.tar.gz
Error: mpd--0.22.3_1.big_sur.bottle.tar.gz for upload doesn't exist!
```

**Comment by fxcoudert** [comment]
How about `--warn-on-upload-failure`?

**Comment by fxcoudert** [comment]
minidlna and mpd are now failing on 10.15, we need to understand why those tests fail

**Comment by chenrui333** [comment]
[minidlna 1.3.0 failed on 10.15](https://github.com/Homebrew/homebrew-core/pull/65760) after rebase build as well

**Comment by carlocab** [comment]
There's a 0.8.1 release now.

**Comment by carlocab** [comment]
Still failing:
```
Error: 2 failed steps!
brew test --verbose minidlna
brew test --verbose mpd
```

**Comment by carlocab** [comment]
10.15:
```
==> FAILED
==> Testing minidlna
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210104-96766-fev6ow.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/minidlna.rb --verbose
==> curl localhost:61971
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 61971: Connection refused
```

**Comment by chenrui333** [comment]
both are related to localhost testing, I feel like we had some change and localhost testing does not work quite well since then.

**Comment by carlocab** [comment]
Yup, I've seen a bunch of other `localhost` test failures before too. Though I thought it was just on Big Sur.

**Comment by fxcoudert** [comment]
OK let's merge and work to fix those someplace else. This has been open long enough.

**Comment by fxcoudert** [comment]
Rebased on top of master, due to conflicts in `openimageio` and `ffmpeg`

**Comment by chenrui333** [comment]
fix the merge conflict, I will do the merge tonight.

**Comment by fxcoudert** [comment]
Did it conflict again? I had rebased, I thought it was good to go :(

**Comment by chenrui333** [comment]
> Did it conflict again? I had rebased, I thought it was good to go :(

yeah, was conflict with opencv and openimageio. :(

**Comment by fxcoudert** [comment]
Merging, despite `mpd` and `minidlna` failures on 10.15 and 11, these will need to be fixed separately.

**Comment by chenrui333** [comment]
Superseded by #102566

**Pull request closed without merging**
