### PR TITLE
libjson-rpc-cpp 0.7.0

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@MikeMcQuaid audit insists on the revision 1, but I guess that's correct since the devel spec is being promoted without change? Should I make it like 7.0.0.1 instead or something?

**Comment by MikeMcQuaid** [comment]
Either leave `revision 1` or ignore the `audit` in this case.

**Comment by ilovezfs** [comment]
OK, I'll kill it and ignore the audit.

**Comment by DomT4** [comment]
Can you file an Issue/PR to highlight/fix the audit issue so we don't forget this is a problem as well? 🙈. Otherwise, 👍 to ignoring this for now.

**Comment by ilovezfs** [comment]
Is it actually a bug, though? It's getting named `formula_revision` not `spec_revision`.

**Comment by DomT4** [comment]
It wasn't an issue in the past, and it's not desired behaviour, so I'd consider it a bug personally.

**Pull request closed without merging**
