### PR TITLE
allureofthestars v0.10.2.0

### PR DESCRIPTION
**Pull request by Mikolaj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Maintainer of the upstream package here. The commandline and test result changed slightly, as reflected here. I lied about testing above (I don't have a mac, except a PowerPC one), but I will assist if anything breaks.

### CODE REVIEW

**Comment by Mikolaj** [comment]
The CI error is " * 'revision 2' should be removed" --- is that really what I should do?

**Comment by Mikolaj** [comment]
Let's try without 'revision 2'...

**Comment by carlocab** [comment]
Thanks for your PR, @Mikolaj. You can leave those boxes unchecked if you didn't do them; we won't hold it against you 🙂

**Comment by Mikolaj** [comment]
I was more worried about a nosy bot with not yet ascended enough AI. Thank you. :)

**Review by carlocab — APPROVED** [review]
Thanks again, @Mikolaj.

**Pull request closed without merging**
