### PR TITLE
julia 1.9.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Apparently I cannot reopen https://github.com/Homebrew/homebrew-core/pull/119456 so this is a new PR.
Testing 1.9.0-beta4

### CODE REVIEW

**Comment by fxcoudert** [comment]
Upstream issue: https://github.com/JuliaLang/julia/issues/48732

**Comment by fxcoudert** [comment]
Does someone skilled in Linux know why we have:

```
Missing libraries:
    unexpected (libjulia-internal.so.1)
    unexpected (libjulia.so.1)
```

**Comment by fxcoudert** [comment]
This is an audit failure for Linux, but I don’t know where it comes from, and the tests pass so it might be a false positive?

**Comment by fxcoudert** [comment]
If these shared objects are loaded by the compiler and it sets, itself, an rpath, then there is no functional issue. I think this audit is too strict in cases like this.

**Review by carlocab — APPROVED** [review]
I'm ok with merging this, but note that doing so will delete the Linux bottle.

**Comment by fxcoudert** [comment]
> will delete the Linux bottle

Is that the case? The bottle was built and uploaded.

**Comment by carlocab** [comment]
> Is that the case? The bottle was built and uploaded.

Yes. It was uploaded to the `bottles-ubuntu-22.04` artifact, which is what happens when a bottle is built but it fails `brew test` or `brew linkage`. It will not be uploaded to GitHub Packages by `brew pr-pull`, which uses only the `bottles` artifact. You can download the `bottles` artifact to check that the Linux bottle is indeed not there.

**Pull request merged**
