### PR TITLE
polynote 0.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Seems like they replaced their `jar` file with a Python script.

**Comment by chenrui333** [comment]
looks like all releases are marked as `pre release`

**Comment by Moisan** [comment]
I tried to update this PR using `rewrite_shebang` on the python script. However one of the python requirement is `pandas` which I cannot get to build inside properly with cython inside homebrew. This was also an issue in https://github.com/Homebrew/homebrew-core/pull/54717.

**Comment by chenrui333** [comment]
Close the PR for now.

**Pull request closed without merging**
