### PR TITLE
{gdal,glew}: revision bumps

### LINKED ISSUE #68038: glew-targets.cmake points to wrong OpenGL location on MacOS Big Sur
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

**NOTE**: This is exactly the same issue as https://github.com/Homebrew/homebrew-core/issues/47813 , but this time with _/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk_ (which doesn't exist, MacOSX11.1.sdk does however). I can not however reopen this issue so I'm creating this one.

Compile a CMake/C++ project using glew with macOS Big Sur (SDK 11.1)

## What happened (include command output)

The CMake target file of **glew** (_/usr/local/lib/cmake/glew/glew-targets.cmake_) installed using a brew bottle, ie `brew install glew`, have a hard coded absolute path dependency to OpenGL.Framwork in _/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk_, but the last update of MacOS replaced  `MacOSX11.0.sdk` by `MacOSX11.1.sdk`.

<details>
  <summary>Command output</summary>
  <pre>

  ninja: error: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework', needed by 'test_glew', missing and no known rule to make it

  </pre>
</details>

## What you expected to happen

Compilation success using _/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk_ which is a symbolic link to the latest installed version of the SDK.

## Step-by-step reproduction instructions (by running `brew install` commands)

I've tested it on my macbookpro Big Sur, and also with a clean Big Sur virtual machine. The following steps will reproduce the bug:

1. Make sure the MacOS is Big Sur and the command line tools are installed and up-to-date (i.e. _/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk_ should point towards _/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk_ or higher.
2. Install **glew** using `brew install glew`
3. Create the following CMake/C++ project:
**CMakeLists.txt**
```cmake
 project(test_glew)                                                                                                    |   #include <string>
                                                                                                                       |   #include <GL/glew.h>
 find_package(OpenGL REQUIRED)                                                                                         |
 find_package(GLEW REQUIRED)                                                                                           |
                                                                                                                       |   const char* GetGlExtensionsList()
 add_executable(${PROJECT_NAME} main.cpp)                                                                              |   {
                                                                                                                       |       return reinterpret_cast<const char*>(glGetString(GL_EXTENSIONS));
 target_link_libraries(${PROJECT_NAME} PUBLIC OpenGL::GL GLEW::GLEW)
```
**main.cpp**
```c++
#include <GL/glew.h>

int main() {
    return 0;
}
```
4. Run `cmake . && make`

## `brew config` and `brew doctor` output

```sh
$ brew config
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 641370ad6392b4a8421c66ad5448554e254387cd
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
```

```sh
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

### PR DESCRIPTION
**Pull request by carlocab**
Fixes #68038, #68049.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
CI failure looks related to #68049.

**Comment by carlocab** [comment]
On Mojave:
```
==> /usr/local/opt/python@3.9/bin/python3 -c import osgeo.gdal
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/osgeo/__init__.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1108, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/osgeo/_gdal.cpython-39-darwin.so, 2): Symbol not found: _curl_mime_addpart
  Referenced from: /usr/local/Cellar/gdal/3.2.0_2/lib/libgdal.28.dylib
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/gdal/3.2.0_2/lib/libgdal.28.dylib
```
This is looking a lot like a mismatched SDK problem too. @fxcoudert, do you know how to fix this?

**Comment by carlocab** [comment]
Big Sur error is related to the disappearance of the `MacOSX11.0.sdk` on the latest Big Sur. In progress at https://github.com/Homebrew/homebrew-core/pull/67615.

**Comment by carlocab** [comment]
I'm also wondering if this can be removed:

https://github.com/Homebrew/homebrew-core/blob/530732c63aaf7f06db9b6f08a0de0570541dd05b/Formula/gdal.rb#L142-L147

**Comment by SMillerDev** [comment]
>  # Remove once support for macOS 10.12 Sierra is dropped 

Comment says yes

**Comment by carlocab** [comment]
The comment is also ambiguous about whether it's talking about Homebrew support for Sierra (yes), or `gdal` support for Sierra (dunno). Though I guess Homebrew support is a safe assumption.

**Comment by SMillerDev** [comment]
Definitely homebrew support, we don't really care what upstream supports (and we're also not going to patch it for versions that homebrew doesn't support)

**Comment by carlocab** [comment]
Ok, so I've managed to fix the Mojave CI failure, though I don't know if it's the right fix. poke @fxcoudert (again, sorry)

**Comment by fxcoudert** [comment]
I think, if there is a SDK issue with curl on Mojave, depending on our own curl is probably best.

**Pull request closed without merging**
