### PR TITLE
libhttpseverywhere 0.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> meson --prefix=/usr/local/Cellar/libhttpseverywhere/0.4.0 ..
The Meson build system
Version: 0.39.1
Source dir: /private/tmp/libhttpseverywhere-20170321-70713-134nag7/libhttpseverywhere-0.4.0
Build dir: /private/tmp/libhttpseverywhere-20170321-70713-134nag7/libhttpseverywhere-0.4.0/build
Build type: native build
Project name: httpseverywhere
Native vala compiler: valac (valac 0.36.0)
Native c compiler: clang (clang 8.0.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/opt/pkg-config/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.50.3
Native dependency gobject-2.0 found: YES 2.50.3
Native dependency json-glib-1.0 found: YES 1.2.8
Native dependency libxml-2.0 found: YES 2.9.4
Native dependency libsoup-2.4 found: YES 2.56.0
Native dependency gio-2.0 found: YES 2.50.3
Native dependency gee-0.8 found: YES 0.20.0
Native dependency libarchive found: YES 3.3.1

Meson encountered an error in file meson.build, line 65, column 0:
Tried to form an absolute path to a source dir. You should not do that but use
relative paths instead.

To get include path to any directory relative to the current dir do

incdir = include_directories(dirname)

After this incdir will contain both the current source dir as well as the
corresponding build dir. It can then be used in any subdirectory and
Meson will take care of all the busywork to make paths work.

Dirname can even be '.' to mark the current directory. Though you should
remember that the current source and build directories are always
put in the include directories by default so you only need to do
include_directories('.') if you intend to use the result in a
different subdirectory.
```
install method needs to be updated

**Comment by tschoonj** [comment]
Yep saw that one too, looks like a bug in the meson script

**Comment by ilovezfs** [comment]
@tschoonj "fixed"

**Comment by tschoonj** [comment]
Nice work 👍

**Pull request closed without merging**
