### PR TITLE
mysql@5.7: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by carlocab**
See #134251.

### CODE REVIEW

**Comment by Bo98** [comment]
5.7 EOL is October.

**Comment by chenrui333** [comment]
```
  -- 
  Cannot find appropriate system libraries for WITH_SSL=yes.
  Make sure you have specified a supported SSL version. 
  Valid options are : 
  system (use the OS openssl library), 
  yes (synonym for system), 
  </path/to/custom/openssl/installation>
  
  CMake Error at cmake/ssl.cmake:63 (MESSAGE):
    Please install the appropriate openssl developer package.
  
  Call Stack (most recent call first):
    cmake/ssl.cmake:306 (FATAL_SSL_NOT_FOUND_ERROR)
    CMakeLists.txt:603 (MYSQL_CHECK_SSL)
```

**Comment by Bo98** [comment]
The patch is likely not trivial, judging by the 8.0 patch: https://github.com/mysql/mysql-server/commit/a0132f53d93eefe4338a27ce4e3f5ffcc7126596 (+ several follow up fix commits)

**Comment by chenrui333** [comment]
I think we can just close the PR as `wont do`

**Pull request closed without merging**
