### PR TITLE
libswiften 4.0.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Downloading https://swift.im/downloads/releases/swift-4.0.2/swift-4.0.2.tar.gz
curl: (60) SSL certificate problem: certificate has expired
```

**Comment by chenrui333** [comment]
<details>
<summary>license ref</summary>

```
Swift - An XMPP Client
Copyright (C) 2009-2018 Isode Limited.

The license under which these products are made available is provided in the COPYING.gpl file.

These products also use third-party code and contributions, the licenses for which are provided in the COPYING.thirdparty file.
```


</details>

**Comment by chenrui333** [comment]
Formula is still using lua@5.1 (`3rdParty/Lua/src/lua.h`)
```
#define LUA_VERSION	"Lua 5.1"
#define LUA_RELEASE	"Lua 5.1.4"
#define LUA_VERSION_NUM	501
```

**Comment by chenrui333** [comment]
invalid syntax issue in my local build
```
scons: Reading SConscript files ...
  File "/private/tmp/libswiften-20211213-66374-14li1ik/swift-4.0.2/BuildTools/SCons/Version.py", line 166

    windowsVersionMapping = list(map(lambda (x,y): (x, convertToWindowsVersion(x)), versionStringsWithOldVersions))

                                            ^

SyntaxError: invalid syntax
```

**Comment by chenrui333** [comment]
only failed on 10.15

>   scons: Reading SConscript files ...
>     File "/private/tmp/libswiften-20211214-50593-1rex64i/swift-4.0.2/BuildTools/SCons/Version.py", line 166
>
>       windowsVersionMapping = list(map(lambda (x,y): (x, convertToWindowsVersion(x)), versionStringsWithOldVersions))
>  
>                                               ^
>  
>   SyntaxError: invalid syntax

**Comment by iMichka** [comment]
Superseded by #93296

**Pull request closed without merging**
