### PR TITLE
[RFC] curl: use openssl@1.1

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

To replace OpenSSL 1.0 with 1.1, I must replace all openssl dependencies in the whole dependency tree.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please test this locally before spinning it on our CI. Mixed-dependency chains are very hard to avoid, and why we haven't made much progress into an `openssl@1.1` transition so far…

**Comment by equal-l2** [comment]
I have replaced all `openssl` with `openssl@1.1` in the dependencies of `curl-openssl`, in the dependencies of the dependencies of `curl-openssl`, and so on.
Also I have replaced one in the dependents of `curl-openssl`, in the dependencies of the dependents, and so on.
Is it not enough?

**Comment by equal-l2** [comment]
I don't know how to test this locally.

**Comment by equal-l2** [comment]
Hmm, I forgot to inspect the dependant of the dependant of curl-openssl, but it will require extraordinary work.
I'll give up and wait for great version shift of OpenSSL in Homebrew.

**Pull request closed without merging**
