### PR TITLE
terrascan 1.3.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
on 11-arm
```
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/hashicorp/go-getter@v1.5.1/get_git.go:20:2: missing go.sum entry for module providing package github.com/hashicorp/go-version; try 'go mod tidy' to add it
pkg/cli/run.go:30:2: missing go.sum entry for module providing package github.com/mattn/go-isatty; try 'go mod tidy' to add it
pkg/iac-providers/kustomize/v3/load-dir.go:11:2: missing go.sum entry for module providing package sigs.k8s.io/kustomize/api/filesys; try 'go mod tidy' to add it
pkg/iac-providers/kustomize/v3/load-dir.go:12:2: missing go.sum entry for module providing package sigs.k8s.io/kustomize/api/krusty; try 'go mod tidy' to add it
```

**Comment by williepaul** [comment]
@chenrui333 Thanks for the help with this. I'm able to repro the arm64 build issue and raised a PR for it: https://github.com/accurics/terrascan/pull/507. Will update when merged.

**Comment by williepaul** [comment]
https://github.com/accurics/terrascan/pull/507 has been merged, can we kick off the pipeline again?

**Comment by SMillerDev** [comment]
It'll still need to be released for the fix to be available though.

**Comment by williepaul** [comment]
Ah right, we actually released 1.3.1 earlier but I forgot the original PR needs to be updated. Should we close this one and start new, or just update it?

**Comment by chenrui333** [comment]
I can update the release artifact. One sec.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
