### PR TITLE
Fixed issue with missing --with-dynamics option in vault

### PR DESCRIPTION
**Pull request by Mazorius**
Signed-off-by: Ron Gebauer <ron.gebauer@valtech.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
We are not going to add that option back, for reasons explained here: https://github.com/Homebrew/homebrew-core/issues/33507#issuecomment-434462752

**Comment by Mazorius** [comment]
Hi @fxcoudert ,

I do not found a solution which I can use otherwise.
If I set the environment variable CGO_ENABLED=1 the vault installation does not work as well.

Do you know a solution for that problem?

Best regards

**Comment by icebourg** [comment]
We were dependent on the --with-dynamic option, this is a major 👎 for home brew.

**Comment by Mazorius** [comment]
Hi @icebourg ,

Since I was not allowed to add this, I built a script as a workaround. This adapts the .md file and installs vault with `dev-dynamic`.

```
#!/usr/bin/env bash

set -x

SCRIPT_PATH=$(dirname $0)/

cp "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vault.rb" ${SCRIPT_PATH}
sed -i -e 's/"dev"/"dev-dynamic"/' ${SCRIPT_PATH}vault.rb

brew uninstall --force vault
brew install --build-from-source ${SCRIPT_PATH}vault.rb

rm ${SCRIPT_PATH}vault.rb
```

**Pull request closed without merging**
