### PR TITLE
torchvision 0.14.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
Gonna check/update resources

**Comment by iMichka** [comment]
I was doing that, I just bumped them.

**Review by iMichka — APPROVED** [review]

**Comment by chenrui333** [comment]
> I was doing that, I just bumped them.

Not quite sure whether some resources are needed or not, based on the reading of `setup.py`

**Comment by chenrui333** [comment]
probably yes, let's see, thanks @iMichka !

**Comment by iMichka** [comment]
Right, they don't seem to have a clear dependency list. Maybe some of these are not necessary anymore. Let's just bump them for the time being I guess.

**Pull request closed without merging**
