### PR TITLE
envoy 1.17.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Can't bottle for ARM yet. Blocked by `bazelisk`

**Comment by carlocab** [comment]
`bazelisk` seems to build on ARM, actually. It's just that the test seems to be designed to download a bazelisk ARM binary from GitHub, but this doesn't exist.

**Comment by carlocab** [comment]
I wonder if we can bottle `bazelisk` for ARM by fixing the test?

**Comment by chenrui333** [comment]
> I wonder if we can bottle `bazelisk` for ARM by fixing the test?

that is the thing, bazelisk is just a wrapper to download bazel binary. If bazel does not support ARM yet, then, we cannot make it available for arm.

let me do a quick check.

**Comment by carlocab** [comment]
I see, that explains why it's trying to download binaries. If they don't have any ARM binaries then there's probably nothing we can do.

**Comment by chenrui333** [comment]
`https://github.com/bazelbuild/bazel/issues/11628` is the tracker issue.

It looks like it is not that hard to build darwin_arm64, but not sure why they did not do that yet.

**Comment by chenrui333** [comment]
This arm issue would technically open the door for all arm binaries.

Depending on which bazelversion got specified, it would download specific arm edition of that bazel binary, which would require arm binary be available for that version. That sucks!! :D

**Comment by chenrui333** [comment]
```
ninja -v
ninja -v install
copy_dir_contents_to_dir $BUILD_TMPDIR/$INSTALL_PREFIX $INSTALLDIR
replace_in_files $INSTALLDIR $BUILD_TMPDIR \${EXT_BUILD_DEPS}
replace_in_files $INSTALLDIR $EXT_BUILD_DEPS \${EXT_BUILD_DEPS}
mkdir -p $EXT_BUILD_ROOT/bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/copy_curl/curl
copy_dir_contents_to_dir $INSTALLDIR $EXT_BUILD_ROOT/bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/copy_curl/curl
touch $EXT_BUILD_ROOT/bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/empty_curl.txt
cd $EXT_BUILD_ROOT
_____ END BUILD SCRIPT _____
rules_foreign_cc: Build script location: bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/curl/logs/CMake_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/curl/logs/CMake.log

Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 979.353s, Critical Path: 257.58s
INFO: 3677 processes: 1249 internal, 2427 processwrapper-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by chenrui333** [comment]
test file got renamed per [this PR](https://github.com/envoyproxy/envoy/pull/13612)

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
