### PR TITLE
stubby 0.2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Homepage moved to `https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby`

Source [unconditionally uses](https://github.com/getdnsapi/stubby/blob/3d0766f832368ff249020fc5101cca1a41a98620/macos/stubby-ui-helper.c) `os_log`, which is [a 10.12+ API](https://developer.apple.com/documentation/os/os_log). Thus needs `depends_on :macos => :sierra`

**Comment by ilovezfs** [comment]
@saradickinson was it intentional to drop support on < 10.12? That sounds like a bug.

**Comment by saradickinson** [comment]
@ilovezfs Nope - an oversight. Darn it... The 0.2.1 release should fix this.
@fxcoudert Correct - the homepage has moved.

**Comment by ilovezfs** [comment]
Thanks @saradickinson! Voilà https://github.com/Homebrew/homebrew-core/pull/21887.

**Pull request closed without merging**
