### PR TITLE
pulumi 3.40.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
+ cp 'goreleaser-lang/*/darwin-arm64/pulumi-language-*' /Users/brew/Library/Caches/Homebrew/go_mod_cache/bin/
cp: goreleaser-lang/*/darwin-arm64/pulumi-language-*: No such file or directory
make: *** [brew] Error 1
```

**Comment by AaronFriel** [comment]
@chenrui333 Apologies for my ignorance here and the failure to publish. It looks like a release process change failed to account for `make brew`.

We are moving toward signing our binaries ourselves, would it be appropriate to replace the action in the `make brew` script with one that acquires the archives from our GitHub release or S3?

**Comment by SMillerDev** [comment]
it really should not be downloading prebuilt binaries at all.

**Comment by AaronFriel** [comment]
@SMillerDev Can you help me understand why? I think we expect to codesign and notarize our binaries, we would want the certificates and entitlements to reflect what we're distributing.

**Comment by SMillerDev** [comment]
You're not distributing. Homebrew is.

This details our policy: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by chenrui333** [comment]
#111138

**Comment by AaronFriel** [comment]
@chenrui333 thank you!

**Pull request closed without merging**
