### PR TITLE
openexr 3.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
We should probably have a separate formula for https://github.com/AcademySoftwareFoundation/Imath, as `openexr` will vendor this if it's not found.

**Comment by hjmallon** [comment]
Looks like:
* openvdb brew formula needs proting `ilmbase` -> `imath`
* ctl needs cmake patching to remove ilmbase search
* jpeg-xl needs to either include `ImfInt64.h` manually or port away from using OpenEXT::Int64 to int64_t etc.

**Comment by carlocab** [comment]
> * ctl needs cmake patching to remove ilmbase search
> * jpeg-xl needs to either include `ImfInt64.h` manually or port away from using OpenEXT::Int64 to int64_t etc.

We should check if these two are already being tracked upstream. If they are, maybe there is already a patch we can use. If not, then it should be reported.

**Comment by hjmallon** [comment]
* openvdb upstream issue: https://github.com/AcademySoftwareFoundation/openvdb/issues/1034
* ctl appears dead? - brew formula already includes patches for the last set of openexr changes
* jpeg-xl upstream issue https://gitlab.com/wg1/jpeg-xl/-/issues/162

**Comment by carlocab** [comment]
ARM:

```
Error: 3 failed steps!
brew install --verbose --build-bottle ctl
brew install --verbose --build-bottle jpeg-xl
brew install --verbose --build-bottle openvdb
```

All Intel Nodes:

```
Error: 9 failed steps!
brew test --retry --verbose caffe
brew test --retry --verbose openalpr
brew linkage --test opencv
brew test --retry --verbose opencv
brew linkage --test opencv@3
brew test --retry --verbose opencv@3
brew install --verbose --build-bottle ctl
brew install --verbose --build-bottle jpeg-xl
brew install --verbose --build-bottle openvdb
```

**Comment by carlocab** [comment]
`caffe` and `openalpr` are from missing libraries; they depend on `ilmbase` though one of the `opencv` formulae (which depends on `openexr`). I suspect these won't work with `imath`.

**Comment by cho-m** [comment]
**jpeg-xl** has a new fix https://gitlab.com/wg1/jpeg-xl/-/commit/9a8f5195e4d1c45112fd65f184ebe115f4163ba2#0442ba75b1c9e65970a8c225708b9e10fee0631b

**ctl** will probably require at least rewriting the cmake find module logic for IlmBase https://github.com/ampas/CTL/blob/master/cmake/modules/FindIlmBase.cmake

**openvdb** will require something similar, splitting off things like IlmThread/Iex (now in OpenEXR package) and moving the rest to be identified as Imath: https://github.com/AcademySoftwareFoundation/openvdb/blob/master/cmake/FindIlmBase.cmake

https://github.com/AcademySoftwareFoundation/Imath/blob/master/docs/PortingGuide2-3.md#openexr-and-imath-are-different-packages

**Comment by carlocab** [comment]
Looks like this will require some work. I guess we can add an `openexr@2` formula in the meantime for the dependent formulae that don't work with the latest `openexr` yet.

**Comment by cho-m** [comment]
With **`ilmbase`** made `keg_only`, is the `conflicts_with` in **`imath`** unnecessary?

https://github.com/Homebrew/homebrew-core/blob/d82dff1ab1f4fef29b0f9995dbc048f60aadd80c/Formula/imath.rb#L17-L18

**Comment by carlocab** [comment]
> With **`ilmbase`** made `keg_only`, is the `conflicts_with` in **`imath`** unnecessary?

Yes, I was thinking that. However, I didn't realise till well after I made changes to this PR, and I'd rather not have to re-run it: a) it takes ages, and b) `caffe`'s test is flaky, so we risk having to re-run the tests a few more times with further changes to this PR.

**Comment by carlocab** [comment]
Yes. Ideally, we would have rev-bumped `ilmbase` here so that users who have it installed get it unlinked from their prefix before upgrading `openexr`.

**Comment by carlocab** [comment]
`imath`: #76889
`ilmbase`: #76890

**Review by carlocab — APPROVED** [review]
Merging this now to avoid merge conflicts from catching up with this PR.

**Comment by hjmallon** [comment]
I got some errors while `brew upgrading`

```
==> Pouring imath--3.0.1.big_sur.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/libImath.dylib
Target /usr/local/lib/libImath.dylib
is a symlink belonging to ilmbase. You can unlink it:
  brew unlink ilmbase

To force the link and overwrite all conflicting files:
  brew link --overwrite imath

To list all files that would be deleted:
  brew link --overwrite --dry-run imath

Possible conflicting files are:
/usr/local/lib/libImath.dylib -> /usr/local/Cellar/ilmbase/2.5.5/lib/libImath.dylib
==> Summary
🍺  /usr/local/Cellar/imath/3.0.1: 49 files, 884.9KB
==> Installing opencv dependency: openexr
==> Pouring openexr--3.0.1.big_sur.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/OpenEXR/Iex.h
Target /usr/local/include/OpenEXR/Iex.h
is a symlink belonging to ilmbase. You can unlink it:
  brew unlink ilmbase

To force the link and overwrite all conflicting files:
  brew link --overwrite openexr

To list all files that would be deleted:
  brew link --overwrite --dry-run openexr

Possible conflicting files are:
/usr/local/include/OpenEXR/Iex.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/Iex.h
/usr/local/include/OpenEXR/IexBaseExc.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexBaseExc.h
/usr/local/include/OpenEXR/IexErrnoExc.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexErrnoExc.h
/usr/local/include/OpenEXR/IexExport.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexExport.h
/usr/local/include/OpenEXR/IexForward.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexForward.h
/usr/local/include/OpenEXR/IexMacros.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexMacros.h
/usr/local/include/OpenEXR/IexMathExc.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexMathExc.h
/usr/local/include/OpenEXR/IexMathFloatExc.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexMathFloatExc.h
/usr/local/include/OpenEXR/IexMathIeeeExc.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexMathIeeeExc.h
/usr/local/include/OpenEXR/IexNamespace.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexNamespace.h
/usr/local/include/OpenEXR/IexThrowErrnoExc.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IexThrowErrnoExc.h
/usr/local/include/OpenEXR/IlmThread.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IlmThread.h
/usr/local/include/OpenEXR/IlmThreadExport.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IlmThreadExport.h
/usr/local/include/OpenEXR/IlmThreadForward.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IlmThreadForward.h
/usr/local/include/OpenEXR/IlmThreadMutex.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IlmThreadMutex.h
/usr/local/include/OpenEXR/IlmThreadNamespace.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IlmThreadNamespace.h
/usr/local/include/OpenEXR/IlmThreadPool.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IlmThreadPool.h
/usr/local/include/OpenEXR/IlmThreadSemaphore.h -> /usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR/IlmThreadSemaphore.h
/usr/local/lib/libIex.dylib -> /usr/local/Cellar/ilmbase/2.5.5/lib/libIex.dylib
/usr/local/lib/libIlmThread.dylib -> /usr/local/Cellar/ilmbase/2.5.5/lib/libIlmThread.dylib
==> Summary
🍺  /usr/local/Cellar/openexr/3.0.1: 176 files, 5.3MB
```

**Comment by carlocab** [comment]
> I think brew hasn't noticed that `openexr` 3.0.1 and `imath` 3.0.1 require `ilmbase` to be 2.5.5_1 (if it is installed)

Yea, I thought `ilmbase` would be "upgraded" before `openexr` was, but I was mistaken. Guess my revision bump was pointless. I'd be open to adding `caveats` to the `ilmbase` formula that explains what to do when encountering this error.

**Comment by hjmallon** [comment]
> Would you like to open a PR for that?

Something like this https://github.com/Homebrew/homebrew-core/pull/76965?

**Comment by carlocab** [comment]
Yup, pretty much what I had in mind. Thanks very much, @hjmallon!

**Comment by lgritz** [comment]
Hi, I noticed that if I build Imath or OpenEXR 3.0.1 from source, it produces and installs cmake config files  (ImathConfig*.cmake, OpenEXRConfig*.cmake) installed in $prefix/lib/cmake/{Imath,OpenEXR}. But no such config files end up in /usr/local/lib with homebrew.

**Comment by carlocab** [comment]
Not really sure why that's happening... what commands do you use to build from source? All `brew` is doing here is calling `cmake` then `make`.

**Comment by hjmallon** [comment]
@lgritz : The CMake configs are symlinking fine for me. Is there something different about your setup to mine? Do you use an Apple Silicon machine and have brew under `/opt/` maybe? Do the cmake configs appear in `ls /usr/local/Cellar/imath/3.0.1/lib`?

```
% brew unlink imath 
Unlinking /usr/local/Cellar/imath/3.0.1... 7 symlinks removed.

% brew link imath -n
Would link:
/usr/local/include/Imath
/usr/local/lib/cmake/Imath    <-------
/usr/local/lib/libImath-3_0.27.0.0.dylib
/usr/local/lib/libImath-3_0.27.dylib
/usr/local/lib/libImath-3_0.dylib
/usr/local/lib/libImath.dylib
/usr/local/lib/pkgconfig/Imath.pc
```

**Comment by lgritz** [comment]
Aha, I see now. Because I still had the old IlmBase, it never did the "brew link" step for imath (because of conflicting files).
After "brew unlink ilmbase ; brew link imath", the cmake files are where I expect.

So it's important to brew unlink ilmbase before installing imath, I think.

**Comment by carlocab** [comment]
Hm, yes. Perhaps it was in fact better to keep `conflicts_with` rather than make `ilmbase` keg-only. Whoops. Hopefully the `caveats` mitigate that a bit:

```
==> Caveats
`ilmbase` has been replaced by `imath`. You may want to `brew uninstall ilmbase`
or `brew unlink ilmbase` to prevent conflicts.
```

**Pull request closed without merging**
