### PR TITLE
fluent-bit 1.2.2

### PR DESCRIPTION
**Pull request by zfouts**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Have you tried 1.3.2, [which seems to be the latest](https://fluentbit.io/download/)?

**Comment by zfouts** [comment]
@Bo98 
> Have you tried 1.3.2, [which seems to be the latest](https://fluentbit.io/download/)?

I did, actually. Both unfortunately fail at the same point, so I'm talking to @edsiper (fluent-bit maintainer) about the issue.

**Comment by zfouts** [comment]
I will create a second PR for 1.3.2.

**Comment by zfouts** [comment]
Fails on Catalina builds -- closing in hopes v1.3.2 fixes.

**Pull request closed without merging**
