### PR TITLE
tintin 2.01.3

### PR DESCRIPTION
**Pull request by number5**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
```
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tintin.rb ==
C: 29:  1: Trailing whitespace detected.

1 file inspected, 1 offense detected
```

and
```
Error Message

failed: brew test tintin --verbose

Stacktrace

        Testing tintin
/usr/bin/sandbox-exec -f /tmp/homebrew20171110-67987-zbwhry.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tintin.rb --verbose
==> /usr/local/Cellar/tintin/2.01.3/bin/tt++ -G brewtest.bin
tcgetattr: Inappropriate ioctl for device
�=
Error: tintin: failed
Failed executing: /usr/local/Cellar/tintin/2.01.3/bin/tt++ -G brewtest.bin
```

**Comment by number5** [comment]
The white space one I get it (and it's easy fix)

But I can't reproduce the test error locally
```
λ brew test tintin --verbose                                      [11-10 20:49]
Testing tintin
/usr/bin/sandbox-exec -f /tmp/homebrew20171110-2692-1rdb4au.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tintin.rb --verbose
==> /usr/local/Cellar/tintin/2.01.3/bin/tt++ -G brewtest.bin

{bye}

Goodbye from TinTin++
```

brew config 
```
HOMEBREW_VERSION: 1.3.6-207-g934480c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 934480ca44b292cb6a50b2fc4a6aa78e065c1e47
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 66b919a489a2fed751f9630c034d1eec2c9ce047
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.8.0_144
macOS: 10.12.6-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11
```

**Comment by ilovezfs** [comment]
@zmwangx didn't we see something like this happen before?

**Comment by zmwangx** [comment]
This one is easily reproduced locally.

```console
$ touch /tmp/stdin
$ brew test tintin </dev/null
Testing tintin
/usr/bin/sandbox-exec -f /tmp/homebrew20171111-21895-1igeu09.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tintin.rb
==> /usr/local/Cellar/tintin/2.01.3/bin/tt++ -G brewtest.bin
tcgetattr: Inappropriate ioctl for device
```

Setting `TERM` does not help, and I did not try to come up with more tricks.

There's always `PTY` as a last resort.

**Comment by number5** [comment]
It made no sense to run test with tintin++ without a PTY,  it's designed to be run inside a active pty session.

I'm happy to remove the test (and fix the extra space) if you like,  it doesn't have a test for previous version anyway.

**Comment by zmwangx** [comment]
Use

```rb
  test do
    require "pty"
    (testpath/"input").write("#end {bye}\n")
    PTY.spawn(bin/"tt++", "-G", "input") do |r, _w, _pid|
      assert_match "Goodbye", r.read
    end
  end
```

**Comment by number5** [comment]
@ilovezfs updated as per @zmwangx suggestion, looks good now

**Comment by ilovezfs** [comment]
Thanks @number5 and @zmwangx! Shipped.

**Pull request closed without merging**
