### PR TITLE
Update to LibGit2-0.28.1

### PR DESCRIPTION
**Pull request by mrmikeface**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
It seems that an update to the `pygit2` resource in the `gitfs` formula also needs to be updated; the current `pygit2` in the `gitfs` formula still seems to be searching for the previous version of `libgit2`.

**Comment by MikeKnowles** [comment]
pygit2 doesn't seem to have a v0.28 so I'll leave this for now. It does prevent upgrade to the latest RubyGem rugged-0.28.1

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by fxcoudert** [comment]
`gitfs` needs to have a revision bump.

**Comment by fxcoudert** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/38263

**Pull request closed without merging**
