### PR TITLE
suite-sparse 7.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Pending `ceres-solver` 2.2.0 release (currently at RC1): https://github.com/ceres-solver/ceres-solver/tags

**Comment by chenrui333** [comment]
ceres-solver 2.2.0 is now avail

**Comment by SMillerDev** [comment]
Ceres-solver bump in https://github.com/Homebrew/homebrew-core/pull/151003

**Comment by fxcoudert** [comment]
There is now a conflict due to https://github.com/Homebrew/homebrew-core/pull/152092

**Comment by chenrui333** [comment]
cherry-pick 59c6ed81be64f6dae4bae773ac237deff459a0bb into this pr

**Comment by chenrui333** [comment]
I guess colmap and opencv situations would be a bit complicated for this PR

**Pull request closed without merging**
