### PR TITLE
fibjs 0.34.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Trying to force an ARM build by setting `BUILD_ARCH` successfully builds but fails to run. Formula may not be compatible with M1.
```
==> Testing fibjs
==> /opt/homebrew/Cellar/fibjs/0.34.0/bin/fibjs /private/tmp/fibjs-test-20210905-86366-w350b3/test.js
<jemalloc>: Unsupported system page size
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

Error: fibjs: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: nil
```

Linux build originally failed on finding `libx11` headers. After using opt_include path, it failed on `xorgproto` headers. Now trying the linked prefix include path to try to get all `<X11/*.h>`.

May require some more attempts if Linux build is missing other dependencies or needs help finding path to libraries.

**Comment by cho-m** [comment]
In order to avoid audit failure, we may want to switch `homepage` to GitHub. Both Linux-default `curl` and brewed `curl` hit this issue:
```console
# curl https://fibjs.org/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

# /home/linuxbrew/.linuxbrew/opt/curl/bin/curl https://fibjs.org/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by chenrui333** [comment]
we also have `audit_exceptions/cert_error_allowlist.json` that we can leverage as well.

**Comment by chenrui333** [comment]
Thanks @cho-m! 💯

**Pull request closed without merging**
