### PR TITLE
clang-format 2018-08-24

### PR DESCRIPTION
**Pull request by tommyang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tommyang** [comment]
Failed on Mojave CI due to TLS cert trust issue. Not sure why, can't repro locally on Mojave 18A391 public release. 

```
04:19:09 Error: Failed to download resource "clang-format"
04:19:09 Failure while executing; `svn checkout https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2018-08-24/ /Users/brew/Library/Caches/Homebrew/clang-format--svn` exited with 1. Here's the output:
04:19:09 svn: E170013: Unable to connect to a repository at URL 'https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2018-08-24'
04:19:09 svn: E230001: Server SSL certificate verification failed: issuer is not trusted
```

**Comment by tommyang** [comment]
Homebrew/brew#4870

**Comment by fxcoudert** [comment]
I can reproduce locally:

```
$ svn ls https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2018-08-24/
Error validating server certificate for 'https://llvm.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
```

(maybe the reason you can't is because you have a non-system `svn` in your `PATH`?)

Let's remove all the `if MacOS.version >= :sierra` checks and switch to HTTP throughout the formula.

**Comment by fxcoudert** [comment]
Thanks @tommyang

**Pull request closed without merging**
