### PR TITLE
node 14.2.0

### PR DESCRIPTION
**Pull request by ryenus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Could you please squash these changes into one commit `node 14.2.0`

**Comment by Bo98** [comment]
Tecnically node 14.2.0 ships with npm 6.14.4 and we do say:

> We track major/minor from upstream Node releases.

**Comment by bayandin** [comment]
> Technically node 14.2.0 ships with npm 6.14.4 and we do say:
> 
> > We track major/minor from upstream Node releases.

I thought this comment is about separate bumping `npm` resource.

**Comment by ryenus** [comment]
Hmm, it's a bit confusing, @bayandin and @Bo98 could you please clarify what's actually needed? Thank you

**Comment by SMillerDev** [comment]
Please revert the change to the npm resource.

**Comment by ryenus** [comment]
Done, thank you all.

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
