### PR TITLE
flake8 3.8.4

### PR DESCRIPTION
**Pull request by tommyang**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by equal-l2** [comment]
`license` line should be added.
FYI this product is licensed under MIT, according to [LICENSE in the repo](https://gitlab.com/pycqa/flake8/-/blob/master/LICENSE).

**Comment by tommyang** [comment]
no `resource` block update needed per homebrew-pypi-poet

**Comment by tommyang** [comment]
@equal-l2 I noticed the label that BrewTestBot added but thanks for the reminder! :-)

**Review by SMillerDev — APPROVED** [review]
Thanks @tommyang  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
