### PR TITLE
knot 2.8.3

### PR DESCRIPTION
**Pull request by Payne-X6**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you squash your commits to `knot 2.8.3`?

**Comment by Payne-X6** [comment]
> Can you squash your commits to `knot 2.8.3`?

I hope I done it as you expected

**Comment by SMillerDev** [comment]
Yeah, looks good. Thanks @Payne-X6 ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
