### PR TITLE
kore 2.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
restrict to >= yosemite due to "error: 'MAP_ANONYMOUS' undeclared"

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
Might be a good idea to report the failure upstream on Mavericks & see whether they've intentionally killed that platform. We've seen a few `MAP_ANONYMOUS` usages creep in lately.

That said, I can't see anything in the analytics that justifies bending over sideways to support Mavericks here.

👍.

**Comment by ilovezfs** [comment]
Reported upstream https://github.com/jorisvink/kore/issues/140

**Comment by ilovezfs** [comment]
@DomT4 Yup, upstream confirmed no intent to support <= Mavericks: https://github.com/jorisvink/kore/issues/140#issuecomment-237552370

**Comment by DomT4** [comment]
Cool, Thanks for chasing that 🙇.

**Pull request closed without merging**
