### PR TITLE
mist 1.8

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==>/opt/homebrew/Cellar/mist/1.8/bin/mist list --quiet --export /private/tmp/mist-test-20220614-82429-1gyfe4k/out.json --output-type json
  Error: Unknown option '--quiet'
  Usage: mist list <subcommand>
    See 'mist list --help' for more information.
  
  Error: mist: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected: 0
    Actual: 64
```

**Comment by NorseGaud** [comment]
@ninxsoft

**Comment by ninxsoft** [comment]
@Porkepix the `mist` subcommands have changed in version 1.8:

`mist list [--kind <kind>]` has been split into `mist list firmware` and `mist list installer`

Line 32 in the formula needs to be updated from:

https://github.com/Homebrew/homebrew-core/blob/d6a11b2c76fbe1641a596a49ca50c4aa8a167b53/Formula/mist.rb#L32

to:

```ruby
     shell_output("#{bin}/mist list firmware --quiet --export #{out} --output-type json").strip
```

or:

```ruby
     shell_output("#{bin}/mist list installer --quiet --export #{out} --output-type json").strip
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks all!

**Pull request closed without merging**
