### PR TITLE
icu4c 68.1

### PR DESCRIPTION
**Pull request by miccal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by fxcoudert** [comment]
```
Error: 194 failed steps!
brew test --retry --verbose alexjs
brew test --retry --verbose angular-cli
brew test --retry --verbose apidoc
brew test --retry --verbose apollo-cli
brew test --retry --verbose appium
brew test --retry --verbose appstream-glib
brew test --retry --verbose ask-cli
brew test --retry --verbose atomist-cli
brew test --retry --verbose autocode
brew test --retry --verbose autorest
brew test --retry --verbose avro-cpp
brew test --retry --verbose aws-cdk
brew test --retry --verbose azure-storage-cpp
brew test --retry --verbose babel
brew test --retry --verbose balena-cli
brew test --retry --verbose bcoin
brew test --retry --verbose bit
brew test --retry --verbose bitwarden-cli
brew linkage --test boost
brew test --retry --verbose bower
brew test --retry --verbose cash-cli
brew test --retry --verbose cdk8s
brew test --retry --verbose cdktf
brew linkage --test chakra
brew test --retry --verbose chakra
brew test --retry --verbose chalk-cli
brew test --retry --verbose charge
brew test --retry --verbose code-server
brew test --retry --verbose coffeescript
brew test --retry --verbose contentful-cli
brew linkage --test couchdb
brew test --retry --verbose couchdb
brew test --retry --verbose cpprestsdk
brew test --retry --verbose cubejs-cli
brew test --retry --verbose cucumber-cpp
brew test --retry --verbose dartsim
brew linkage --test dwdiff
brew test --retry --verbose dwdiff
brew test --retry --verbose easyrpg-player
brew test --retry --verbose eleventy
brew test --retry --verbose emscripten
brew test --retry --verbose eslint
brew test --retry --verbose fauna-shell
brew test --retry --verbose field3d
brew test --retry --verbose firebase-cli
brew test --retry --verbose folly
brew linkage --test freeling
brew test --retry --verbose freeling
brew test --retry --verbose gatsby-cli
brew test --retry --verbose gedit
brew test --retry --verbose generate-json-schema
brew test --retry --verbose geocode-glib
brew test --retry --verbose gitg
brew test --retry --verbose gitmoji
brew test --retry --verbose gitter-cli
brew linkage --test gjs
brew test --retry --verbose gjs
brew test --retry --verbose gnome-latex
brew test --retry --verbose gnome-recipes
brew test --retry --verbose gnuradio
brew test --retry --verbose gr-osmosdr
brew test --retry --verbose graph-tool
brew test --retry --verbose graphql-cli
brew test --retry --verbose grunt-cli
brew test --retry --verbose gssdp
brew test --retry --verbose gtranslator
brew test --retry --verbose gulp-cli
brew test --retry --verbose gupnp
brew test --retry --verbose gupnp-tools
brew linkage --test harfbuzz
brew linkage --test hfstospell
brew test --retry --verbose hfstospell
brew test --retry --verbose homebank
brew test --retry --verbose hsd
brew test --retry --verbose http-server
brew test --retry --verbose insect
brew test --retry --verbose ios-sim
brew test --retry --verbose jhipster
brew test --retry --verbose jsdoc3
brew test --retry --verbose jsonlint
brew test --retry --verbose lanraragi
brew test --retry --verbose ledger
brew test --retry --verbose lerna
brew test --retry --verbose lgogdownloader
brew test --retry --verbose libbitcoin
brew test --retry --verbose libbitcoin-blockchain
brew test --retry --verbose libbitcoin-client
brew test --retry --verbose libbitcoin-database
brew test --retry --verbose libbitcoin-explorer
brew test --retry --verbose libbitcoin-network
brew test --retry --verbose libbitcoin-node
brew test --retry --verbose libbitcoin-protocol
brew test --retry --verbose libbitcoin-server
brew linkage --test libcdr
brew test --retry --verbose libcdr
brew test --retry --verbose libchamplain
brew test --retry --verbose libgdata
brew test --retry --verbose libgweather
brew test --retry --verbose libhttpseverywhere
brew linkage --test libical
brew test --retry --verbose libical
brew linkage --test liblcf
brew test --retry --verbose liblcf
brew linkage --test libmspub
brew test --retry --verbose libmspub
brew test --retry --verbose libosinfo
brew linkage --test libphonenumber
brew test --retry --verbose libphonenumber
brew linkage --test libpsl
brew test --retry --verbose libpsl
brew test --retry --verbose libpulsar
brew test --retry --verbose librest
brew test --retry --verbose libsoup
brew test --retry --verbose libswiften
brew linkage --test libvisio
brew test --retry --verbose libvisio
brew linkage --test mapnik
brew test --retry --verbose marked
brew test --retry --verbose metaproxy
brew test --retry --verbose monero
brew linkage --test mpd
brew test --retry --verbose mpd
brew test --retry --verbose nativefier
brew linkage --test ncmpcpp
brew test --retry --verbose ncmpcpp
brew test --retry --verbose netlify-cli
brew test --retry --verbose newman
brew linkage --test node
brew test --retry --verbose node
brew test --retry --verbose node-sass
brew linkage --test node@10
brew test --retry --verbose node@10
brew linkage --test node@12
brew test --retry --verbose node@12
brew linkage --test node@14
brew test --retry --verbose node@14
brew linkage --test openrct2
brew test --retry --verbose openrct2
brew test --retry --verbose osm-gps-map
brew test --retry --verbose osrm-backend
brew linkage --test pazpar2
brew test --retry --verbose pazpar2
brew test --retry --verbose pcl
brew install php
brew install php@7.2
brew install php@7.3
brew test --retry --verbose pnpm
brew linkage --test postgresql
brew linkage --test postgresql@10
brew linkage --test postgresql@11
brew linkage --test postgresql@12
brew test --retry --verbose prettier
brew test --retry --verbose protoc-gen-grpc-web
brew test --retry --verbose pulp
brew test --retry --verbose quicktype
brew test --retry --verbose react-native-cli
brew test --retry --verbose serverless
brew linkage --test sile
brew test --retry --verbose sile
brew test --retry --verbose sloc
brew test --retry --verbose source-highlight
brew test --retry --verbose supertux
brew test --retry --verbose svgo
brew linkage --test tarantool
brew test --retry --verbose tarantool
brew test --retry --verbose tdkjs
brew linkage --test tectonic
brew test --retry --verbose tectonic
brew linkage --test tepl
brew test --retry --verbose tepl
brew test --retry --verbose terrahub
brew test --retry --verbose triton
brew test --retry --verbose typescript
brew test --retry --verbose ungit
brew linkage --test urweb
brew test --retry --verbose urweb
brew linkage --test vte3
brew test --retry --verbose vte3
brew linkage --test vtk
brew test --retry --verbose webpack
brew test --retry --verbose webtorrent-cli
brew test --retry --verbose whistle
brew linkage --test widelands
brew test --retry --verbose widelands
brew test --retry --verbose wownero
brew test --retry --verbose write-good
brew linkage --test yaz
brew test --retry --verbose yaz
brew linkage --test zebra
brew test --retry --verbose zebra
brew linkage --test znc
brew test --retry --verbose znc
brew linkage --test zorba
brew test --retry --verbose zorba
```

Enjoy!

**Comment by miccal** [comment]
> Enjoy!

I am not sure "enjoy" is the word I would use ... holy crap!

**Comment by miccal** [comment]
`brew linkage` errors:
```
boost
chakra
couchdb
dwdiff
freeling
gjs
harfbuzz
hfstospell
libcdr
libical
liblcf
libmspub
libphonenumber
libpsl
libvisio
mapnik
mpd
ncmpcpp
node
node@10
node@12
node@14
openrct2
pazpar2
postgresql
postgresql@10
postgresql@11
postgresql@12
sile
tarantool
tectonic
tepl
urweb
vte3
vtk
widelands
yaz
zebra
znc
zorba
```
I guess the first thing to try would be to revision-bump all of these -- is there an "easy" way to do this with `bump−revision`?

**Comment by SMillerDev** [comment]
`bump−revision` _is_ the easy way 😅

**Comment by miccal** [comment]
> `bump−revision` _is_ the easy way 😅

Ah, so it is -- I did not realise that `bump−revision` committed and set a message automatically :)

**Comment by miccal** [comment]
A little better than before:
```
Error: 16 failed steps!
brew install php
brew install php@7.2
brew install php@7.3
brew install --verbose --build-bottle postgresql
brew install --verbose --build-bottle dwdiff
brew install --verbose --build-bottle libcdr
brew install --verbose --build-bottle libical
brew install --build-from-source postgresql
brew install --only-dependencies --verbose --build-bottle mapnik
brew install --verbose --build-bottle mapnik
brew install --verbose --build-bottle postgresql@10
brew install --verbose --build-bottle postgresql@11
brew install --verbose --build-bottle postgresql@12
brew install --verbose --build-bottle tarantool
brew install --verbose --build-bottle urweb
brew install --verbose --build-bottle zorba
```

**Comment by Totktonada** [comment]
We restored the old URL for tarantool (someone added the direct link to our backend, I was not aware of this; it is better to use `download.tarantool.org` URLs). Now the build passes for tarantool on 10.14 and 10.15. I [investigated](https://github.com/Homebrew/homebrew-core/pull/59203#issuecomment-720041862) the problem on 10.13 and I hope @avtikhon will fix it soon within PR #59203.

**Comment by derrabus** [comment]
Bumping icu4c would currently break the php formulae. I've filed a bug report: https://bugs.php.net/bug.php?id=80310

**Comment by derrabus** [comment]
PHP has shipped a fix for 7.3 (#65700) and 7.4 (#65689). PHP 7.2 won't be fixed upstream and will be EOL by the end of the month.

**Comment by miccal** [comment]
I first submitted this PR before I did a clean install of Big Sur, so I think it would be best that I close this one and create a new one.

**Pull request closed without merging**
