### PR TITLE
ansible 2.4.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by mkozjak** [comment]
What happened with https://jenkins.brew.sh? :)

**Comment by TangRufus** [comment]
What happened with https://jenkins.brew.sh? :) x2

**Comment by ilovezfs** [comment]
It said "ilovezfs hasn't updated the resource blocks yet so please ignore me as an irrelevance."

**Comment by ilovezfs** [comment]
@rdewaele @mkozjak @TangRufus the resource blocks are now updated.

**Comment by TangRufus** [comment]
Thanks!!!!!!!!!!!!!!

**Pull request closed without merging**
