### PR TITLE
glib 2.52.2 and gobject-introspection 1.52.1

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
FYI @ilovezfs

**Comment by tschoonj** [comment]
@ilovezfs @MikeMcQuaid Any idea whats going on here? Looks like the tests are not recursively installing dependencies before running them. Pretty sure this used to work properly

**Comment by MikeMcQuaid** [comment]
@tschoonj Tests used to be able to rely on dependencies/formulae being linked and this is no longer the case. Sound like it could be that?

**Comment by tschoonj** [comment]
Yes sounds about right. What's the solution here?

**Comment by MikeMcQuaid** [comment]
@tschoonj Unfortunately: rewrite the relevant tests to not have that assumption. Is that a possibility?

**Comment by tschoonj** [comment]
I do not understand why something like this should ever fail as the `corebird` Formula clearly has `gtk+3` marked as a dependency. This appears to be happening for a lot tests with executables linked to `gtk+3`.

````
      Testing corebird
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170503-80265-1o5lhby.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/corebird.rb --verbose
==> /usr/local/Cellar/corebird/1.4.2/bin/corebird --help
dyld: Library not loaded: /usr/local/lib/libgtk-3.0.dylib
  Referenced from: /usr/local/opt/gtk-mac-integration/lib/libgtkmacintegration-gtk3.2.dylib
  Reason: image not found
Error: corebird: failed
Failed executing: /usr/local/Cellar/corebird/1.4.2/bin/corebird --help
/usr/local/Homebrew/Library/Homebrew/formula.rb:1856:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1794:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1794:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/corebird.rb:40:in `block in <class:Corebird>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1692:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:887:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1691:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1685:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
````

**Comment by MikeMcQuaid** [comment]
Looks like this caught a linkage issue; stuff shouldn't be linking to `/usr/local/lib` paths for GTK.

**Comment by tschoonj** [comment]
Interestingly I cannot reproduce this locally:

````
otool -L /usr/local/opt/gtk-mac-integration/lib/libgtkmacintegration-gtk3.2.dylib
/usr/local/opt/gtk-mac-integration/lib/libgtkmacintegration-gtk3.2.dylib:
	/usr/local/opt/gtk-mac-integration/lib/libgtkmacintegration-gtk3.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/usr/local/opt/gtk+3/lib/libgtk-3.0.dylib (compatibility version 2201.0.0, current version 2201.7.0)
	/usr/local/opt/gtk+3/lib/libgdk-3.0.dylib (compatibility version 2201.0.0, current version 2201.7.0)
	/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.3.0)
	/usr/local/opt/pango/lib/libpango-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.3.0)
	/usr/local/opt/atk/lib/libatk-1.0.0.dylib (compatibility version 22210.0.0, current version 22210.1.0)
	/usr/local/opt/cairo/lib/libcairo-gobject.2.dylib (compatibility version 11403.0.0, current version 11403.8.0)
	/usr/local/opt/cairo/lib/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.8.0)
	/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib (compatibility version 3603.0.0, current version 3603.0.0)
	/usr/local/opt/glib/lib/libgio-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.2.0)
	/usr/local/opt/glib/lib/libgobject-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.2.0)
	/usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.2.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1348.28.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1070.13.0)
````

But I do build everything from source, so this may be an issue with the `gtk-mac-integration` bottle.

**Comment by MikeMcQuaid** [comment]
@tschoonj If it hasn't been rebuild recently, it sounds likely. We've introduced multiple changes in the last few months that should help address this. A separate PR to rebuild it might be worth it?

**Comment by ilovezfs** [comment]
This was also the reason for https://github.com/Homebrew/homebrew-core/pull/13157

**Comment by tschoonj** [comment]
Ok will do

**Comment by tschoonj** [comment]
Clearly hasn't seen a rebuild in a long time as there are bottles available for the last macOS releases 😄

**Comment by tschoonj** [comment]
Ok I added a couple of pull requests that should take care of the majority of these failures.

**Comment by tschoonj** [comment]
@MikeMcQuaid I have managed to reduce to failing tests down to 55 but I am giving up. Has not exactly been a lot of fun.

Would it be ok to merge this PR in anyway?

**Review by fxcoudert — DISMISSED** [review]

**Comment by ilovezfs** [comment]
I'd prefer test-bot be reverted to actually link the dependencies of things being tested than having us start merging PRs in the red.

**Review by ilovezfs — DISMISSED** [review]
Let's wait for test-bot to be fixed and this to be green.

**Comment by fxcoudert** [comment]
@ilovezfs we're preventing users to get an update that is functional, because our CI tool is imperfect. It's definitely not a good idea, and we can give lots of examples of PRs that are merged red, once the errors have been audited and rightfully dismissed.

**Comment by MikeMcQuaid** [comment]
@tschoonj apologies for the late reply. I'm going to investigate further and get this PR green. I'll shout if I need help on your end.

**Comment by ilovezfs** [comment]
>we can give lots of examples of PRs that are merged red, once the errors have been audited and rightfully dismissed.

If that is happening, it should stop.

**Comment by ilovezfs** [comment]
As part of getting this green, I think all of these should be reverted as the changes should not be necessary when test-bot is functioning properly:

https://github.com/Homebrew/homebrew-core/pull/13315
https://github.com/Homebrew/homebrew-core/pull/13316
https://github.com/Homebrew/homebrew-core/pull/13317
https://github.com/Homebrew/homebrew-core/pull/13336
https://github.com/Homebrew/homebrew-core/pull/13338
https://github.com/Homebrew/homebrew-core/pull/13341
https://github.com/Homebrew/homebrew-core/pull/13342
https://github.com/Homebrew/homebrew-core/pull/13343
https://github.com/Homebrew/homebrew-core/pull/13344
https://github.com/Homebrew/homebrew-core/pull/13346
https://github.com/Homebrew/homebrew-core/pull/13348
https://github.com/Homebrew/homebrew-core/pull/13349
https://github.com/Homebrew/homebrew-core/pull/13350
https://github.com/Homebrew/homebrew-core/pull/13351

**Comment by tschoonj** [comment]
@ilovezfs not all of those should be reverted. In some cases there were some genuine problems with the formulas.

**Comment by ilovezfs** [comment]
@tschoonj I've updated the list. Are there any of those listed currently you disagree about?

**Comment by tschoonj** [comment]
#13316 keep this one, as we never use pkg-config in test blocks anyway
#13336 I prefer this one too as that executable will probably be removed in a future release.
#13346 keep it, except perhaps the changes in the test block

**Comment by ilovezfs** [comment]
@tschoonj I've updated the list accordingly.

**Comment by tschoonj** [comment]
@ilovezfs 🙇

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
I've merged https://github.com/Homebrew/homebrew-test-bot/pull/83 which should help with the remaining failing tests.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
`corebird` and `file-roller` tests fail over missing settings schemas:

```
==> /usr/local/Cellar/corebird/1.4.2/bin/corebird --help
(corebird:74932): GLib-GIO-ERROR **: Settings schema 'org.baedert.corebird' is not installed

==> /usr/local/Cellar/file-roller/3.24.1/bin/file-roller --help
(process:8935): GLib-GIO-ERROR **: Settings schema 'org.gnome.FileRoller.Listing' is not installed
```

`pygobject3` test fails over `python3` not being there:

```
==> python test.py
==> python3 test.py
Failed to execute: python3
```

(I don't know why it's trying `python3` in the Python versions loop.)

**Comment by ilovezfs** [comment]
No longer relevant as we're backing out the linking changes to test-bot.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@fxcoudert https://github.com/Homebrew/homebrew-test-bot/pull/84 is unmerged so re-running this is not going to help right now.

**Comment by fxcoudert** [comment]
It helped in triggering you to post the link to the brew PR that this is dependent on, making me understand what is happening here… although I still don't understand why we block on something that is a testbot issue :(

**Comment by MikeMcQuaid** [comment]
> although I still don't understand why we block on something that is a testbot issue :(

Otherwise we don't know that these changes aren't broken in another way because the tests aren't being run correctly.

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
One link error, otherwise 💚 https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1345/version=sierra/testReport/junit/brew-test-bot/sierra/link_ganglia/

**Comment by ilovezfs** [comment]
I think this will fix the `ganglia` link error:
```
diff --git a/cmd/brew-test-bot.rb b/cmd/brew-test-bot.rb
index a9e2948..39de1b4 100755
--- a/cmd/brew-test-bot.rb
+++ b/cmd/brew-test-bot.rb
@@ -523,6 +523,16 @@ module Homebrew
       test "brew", "config"
     end
 
+    def unlink_conflicts(formula)
+      conflicts = formula.conflicts.map { |c| Formulary.factory(c.name) }.select(&:installed?)
+      formula.recursive_dependencies.each do |dependency|
+        conflicts += dependency.to_formula.conflicts.map { |c| Formulary.factory(c.name) }.select(&:installed?)
+      end
+      conflicts.each do |conflict|
+        test "brew", "unlink", conflict.name
+      end
+    end
+
     def formula(formula_name)
       @category = "#{__method__}.#{formula_name}"
 
@@ -718,16 +728,12 @@ module Homebrew
         shared_test_args << "--keep-tmp" if ARGV.keep_tmp?
         test "brew", "test", formula_name, *shared_test_args if formula.test_defined?
         bottled_dependents.each do |dependent|
-          unless dependent.installed?
+          if dependent.installed?
+            unlink_conflicts dependent
+          else
             test "brew", "fetch", "--retry", dependent.name
             next if steps.last.failed?
-            conflicts = dependent.conflicts.map { |c| Formulary.factory(c.name) }.select(&:installed?)
-            dependent.recursive_dependencies.each do |dependency|
-              conflicts += dependency.to_formula.conflicts.map { |c| Formulary.factory(c.name) }.select(&:installed?)
-            end
-            conflicts.each do |conflict|
-              test "brew", "unlink", conflict.name
-            end
+            unlink_conflicts dependent
             unless ARGV.include?("--fast")
               run_as_not_developer { test "brew", "install", dependent.name }
               next if steps.last.failed?
```

**Comment by ilovezfs** [comment]
I've opened https://github.com/Homebrew/homebrew-test-bot/pull/85 to try to fix the `ganglia` link error.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Going to merge without reverting the tests yet since we have :green_apple:

**Comment by ilovezfs** [comment]
:rocket:

**Pull request closed without merging**
