### PR TITLE
prr 0.5.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
I was surprised of the `openssl` in the formula seeing no mention of it into their repo so I tried to compile from source and execute on my computer without it, without any issue. Note though that my system - outside `brew` - does provide `openssl` and that just by installing `prr` dependencies to build and nothing else, `openssl` was installed, so I'm not sure what this test is worth and maybe I'm completely mistaken.

**Comment by SMillerDev** [comment]
It's clearly needed:
```
Missing libraries:
  unexpected (libcrypto.so.1.1)
  unexpected (libssl.so.1.1)
```

**Comment by Porkepix** [comment]
Pushed a try with `openssl@3`. Why is this dependency only required for Linux, though? Might this be due to the version of Ubuntu being too old regarding a provided `openssl`?

**Comment by SMillerDev** [comment]
It's likely because macOS provides it's own SSL library that Rust uses while on Linux it uses the Linux standard (OpenSSL)

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
