### PR TITLE
Missing `uses_from_macos`

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Noticed this working on https://github.com/Homebrew/homebrew-core/pull/75299

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Comment by Bo98** [comment]
Looks like pod2man is already supplied by `perl`, so this extra dependency actually conflicts.

**Comment by MikeMcQuaid** [comment]
@bo98 can you elaborate on what you mean by "conflicts" here?

**Comment by Bo98** [comment]
```
/usr/local/bin/pod2man -> ../Cellar/perl/5.32.1_1/bin/pod2man
```

**Comment by MikeMcQuaid** [comment]
> Perl ships with a `pod2man` so this installs a second one, which might cause a `brew link` failure.

`pod2man` is `keg_only` so won't be linked (on macOS at least), right?

**Comment by Bo98** [comment]
On macOS yes. I'm concerned about Linux because that's the platform `uses_from_macos` affects.

**Comment by MikeMcQuaid** [comment]
@Bo98 I don't have a Linux box handy and can't remember if `provided_by_macos` links as expected. What do you propose instead? Options I can see:
- add `conflicts_with` on Linux only
- add `conflicts_with` everywhere (it's a no-op on macOS)
- never use `uses_from_macos "pod2man"` because `uses_from_macos "perl"` actually provides it anyway
- make `uses_from_macos "pod2man"` actually use `perl` instead of `pod2man`.

**Comment by Bo98** [comment]
For smooth use of `all:` when the cores are merged, we probably want consistency betwen macOS and Linux. That means using the same version (i.e. both `pod2man` 4.14).

`conflicts_with` makes sense but is problematic because we would actually need both most of the time on Linux.

Honestly, we could probably just make `pod2man` universally `keg_only`. It would be unusual compared to the norm, and some tweaks would be needed to make sure it uses the correct executable (either by absolute paths or potentially adjusting the superenv to prioritise keg-only deps in the PATH), but might end up making the most sense.

**Comment by MikeMcQuaid** [comment]
> For smooth use of `all:` when the cores are merged, we probably want consistency betwen macOS and Linux.

Agreed.



> Honestly, we could probably just make `pod2man` universally `keg_only`.

Agreed.

> It would be unusual compared to the norm

It's also unusual to have formulae that are shipped as part of another formulae so: I think this is justified and the best solution here. I can't see (m)any people on Linux complaining about this. 

> either by absolute paths

This seems fine to me :+1:. Nicer than bringing back the shim 😅

**Comment by Bo98** [comment]
#75751

**Pull request merged**
