### PR TITLE
rio 0.0.9

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>- Created "rio" terminfo.
- Breaking changes for configuration file regarding `Advanced`. The configuration `Advanced` has moved to root level and `disable-render-when-unfocused` renamed to `disable-unfocused-render`.

**before**

```toml
theme = "dracula"

[advanced]
disable-render-when-unfocused = true
```

**now**

```toml
theme = "dracula"
disable-unfocused-render = true
```

- Support to **spawn and fork processes**, spawn has became default. Spawn increases Rio compability in a broad range, like old MacOS versions (older or equal to Big Sur). However, If you want to use Rio terminal to fork processes instead of spawning processes, enable `use-fork` in the configuration file:

```toml
use-fork = true
```

- Introduced `RIO_LOG_LEVEL` variable usage. (`e.g: RIO_LOG_LEVEL=debug rio -e "echo 1"`)
- Increased max tabs from 6 to 9.
- Fix Incorrect cursor position when using multi-byte characters (Ref: [#127](https://github.com/raphamorim/rio/issues/127))
- Fix bug ["black screen with nearly zero interactivity"](https://github.com/raphamorim/rio/issues/112) and new tab hanging.
- Fix cursor disappearing after resize.
- Introduction of `shell` and `working_dir` in configuration file.
- Multi window support [#97](https://github.com/raphamorim/rio/issues/97).
- Corrections on select and scroll experience (it was using wrongly font-bound for line calculation).
- Add selection color to the theme config (closed [#125](https://github.com/raphamorim/rio/issues/125)).
- Implemented Inverse (fix [#92](https://github.com/raphamorim/rio/issues/92)).
- Proper choose formats that matches with `TextureFormat::is_srgb` (it fixed the Vulkan driver, related [#122](https://github.com/raphamorim/rio/issues/122)).
- Corcovado: Filter windows crate dependency to only Windows targets (related: [#119](https://github.com/raphamorim/rio/issues/119)).
- Teletypewriter: Fixes for musl as target_env (related: [#119](https://github.com/raphamorim/rio/issues/119)).
- FreeBSD support, implementation by [yurivict](https://github.com/yurivict) ([Commit](https://github.com/freebsd/freebsd-ports/commit/8582b8c59459a7dc5112a94a39de45f6cc124c3e), Ref: [#115](https://github.com/raphamorim/rio/issues/115))</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
>   Failed to spawn command 'echo 1; exit': No such file or directory (os error 2)

**Comment by alebcay** [comment]
The issue here is that `echo 1; exit` is passed as one argument so `rio` is looking for a binary called `echo 1; exit`. We could split this into multiple arguments to make the existing test work.

I've replaced the test with one that will hopefully offer a bit more confirmation that the execution is actually happening.

**Comment by raphamorim** [comment]
Hey there, sorry about it. The new version doesn't accept string as commands and `exit` isn't necessary anymore; So you could just run `rio --command echo 1`

**Comment by raphamorim** [comment]
And the suggestion that @alebcay made also works prob even better than before since now can check if a file a created after the command execution

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> And the suggestion that @alebcay made works prob even better than it was before since now can check if a file a created after the command execution

Yeah, we can ship the better test, my issue was mostly confirming about the formula behavior change

**Pull request merged**
