### PR TITLE
hyperspec: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by Amar1729**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See #75943.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your help here, @Amar1729! Let's hold off on further PRs that remove `bottle :unneeded` for now while there are still a few dozen open ones waiting to be merged.

**Comment by Amar1729** [comment]
No problem @carlocab . Happy to help.

**Comment by Amar1729** [comment]
Current failure on 10.14 might've been a temporary network issue - 
```
==> brew audit hyperspec --online --git --skip-style
==> FAILED
hyperspec:
  * The homepage URL https://www.lispworks.com/documentation/common-lisp.html is not reachable
Error: 1 problem in 1 formula detected
```

**Comment by Moisan** [comment]
Let's requeue de CI and see if the networks issue is gone.

**Comment by bayandin** [comment]
> Let's requeue the CI and see if the networks issue is gone.

It's not a network issue, but an old curl on Mojave. I've added it to `allowlist`.

**Comment by bayandin** [comment]
```
 sha256sum bottles/hyperspec--7.0.*.tar.gz
f97fdd5f56b2c8d2ea223a0ce5950c225c198e3e1157d7bd8c7d691c65773404  bottles/hyperspec--7.0.arm64_big_sur.bottle.tar.gz
f97fdd5f56b2c8d2ea223a0ce5950c225c198e3e1157d7bd8c7d691c65773404  bottles/hyperspec--7.0.big_sur.bottle.tar.gz
f97fdd5f56b2c8d2ea223a0ce5950c225c198e3e1157d7bd8c7d691c65773404  bottles/hyperspec--7.0.catalina.bottle.tar.gz
f97fdd5f56b2c8d2ea223a0ce5950c225c198e3e1157d7bd8c7d691c65773404  bottles/hyperspec--7.0.mojave.bottle.tar.gz
```

**Review by bayandin — DISMISSED** [review]
Thanks @Amar1729 🎉

**Pull request closed without merging**
