### PR TITLE
sbcl 1.3.20

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Alhadis** [comment]
Hey @ilovezfs, sorry for the random ping... bur do you remember last December when you told me there was a formulae that hadn't been updated in ages, because the updater was written in Lisp, and nobody had the balls or brackets to touch it?))) If so, could you remind me what it was so I could look at it? :) Thanks!

~~~lisp
`))))))))))))))
        )))))))) ; Sexpy af`
~~~

**Comment by ilovezfs** [comment]
@Alhadis yep. I took care of it in https://github.com/Homebrew/homebrew-core/pull/15429/files

**Comment by Alhadis** [comment]
Manually, or did you learn Lisp on-the-fly?

Well, if you ever need some brackets-wrestled... just `cdr` down my way and give me a shout-out. =)

**Comment by ilovezfs** [comment]
I know a little Lisp. The difficulty was figuring out how to use https://github.com/benesch/quicklisp-homebrew-roundup.

>Well, if you ever need some brackets-wrestled... just cdr down my way and give me a shout-out. =)

Will do!

**Pull request closed without merging**
