### PR TITLE
cockroach 19.1.5

### PR DESCRIPTION
**Pull request by ajwerner**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

---
This change is [Reviewable](https://reviewable.io/reviews/homebrew/homebrew-core/44732)

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/49058/version=mojave/console

15:15:54 [ 51%] Linking CXX static library libprotoc.a
15:15:54 Scanning dependencies of target protoc
15:15:54 [ 52%] Building CXX object CMakeFiles/protoc.dir/tmp/cockroach-20191002-11265-tgvcmm/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/c-deps/protobuf/src/google/protobuf/compiler/main.cc.o
15:15:54 [ 53%] Linking CXX executable protoc
15:15:54 make[1]: Leaving directory '/private/tmp/cockroach-20191002-11265-tgvcmm/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach'
15:15:54 make: *** [Makefile:6: buildoss] Error 2
15:15:54

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by ajwerner** [comment]
@chenrui333 I got ahold of a mac and fixed the build problems. Should be RFAL. Thanks!

**Comment by chenrui333** [comment]
Very nice!! Thanks!!

**Comment by ajwerner** [comment]
@BrewTestBot test this please

**Comment by ajwerner** [comment]
@BrewTestBot test this please

**Comment by ajwerner** [comment]
@chenrui333 now the build actually passed; it needed another round to deal with the recent XCode upgrade. Sorry it took so many iterations.

**Comment by chenrui333** [comment]
@ajwerner, I think it is all good now. 

Really appreciate your persistent efforts on this PR!!

**Pull request closed without merging**
