### PR TITLE
bzt 1.10.2 (formula update)

### PR DESCRIPTION
**Pull request by greyfenrir**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by greyfenrir** [comment]
I tried to downgrade them to previous "checked" versions as lxml build was unsuccessful (according to your jenkins logs). It didn't help, and I will be grateful for any ideas how to fix blocked lxml problem..

**Comment by ilovezfs** [comment]
Yeah I think I know what's wrong with Sierra. But in terms of the other two nodes, do you have any idea why it's timing out?

**Comment by greyfenrir** [comment]
1. Even if you fix it (lxml) by yourself, will be great if you give me short explanation of problem or link to info.
2. I'll look into timeout asap.

**Comment by ilovezfs** [comment]
@greyfenrir the lxml thing happens if we have not set SDKROOT to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk` and yet the xcode-select active developer directory is `/Applications/Xcode.app/Contents/Developer`. `/usr/lib/system/libsystem_darwin.dylib` doesn't exist on 10.12 but `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/system/libsystem_darwin.tbd` does.

**Comment by greyfenrir** [comment]
Cool, thanks a lot. Now I have to fix that broken pipe problem.

**Pull request closed without merging**
