### PR TITLE
monero 0.17.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Not the latest GitHub release yet, but should be soon.

**Comment by carlocab** [comment]
Should be announced here when ready to merge: https://www.getmonero.org/blog/tags/releases.html

**Comment by chenrui333** [comment]
close it for now.

**Comment by selsta** [comment]
Yes, it sometimes takes 1-2 days between tag and released binaries + release notes.

**Comment by selsta** [comment]
ping @chenrui333, v0.17.2.0 is stable now

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
