### PR TITLE
commandbox 5.3.0

### PR DESCRIPTION
**Pull request by bdw429s**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bdw429s** [comment]
Can someone kick off the tests again please?  It failed saying some S3 URLs were not reachable, but I just tested them again and I can hit them in a browser just fine, so perhaps it was an intermittent networking issue on your build server?

**Comment by chenrui333** [comment]
you got it.

**Comment by bdw429s** [comment]
Thanks so much @chenrui333 , it looks like everything passed this time!

**Review by chenrui333 — DISMISSED** [review]

**Comment by bdw429s** [comment]
@chenrui333 is there a reason you removed the bottle portion of the formula?  It seems to have caused issues.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
let's wait for a second try, not sure what is going on.

**Review by nandahkrishna — APPROVED** [review]

**Comment by nandahkrishna** [comment]
> is there a reason you removed the bottle portion of the formula?

We're trying to get every formula bottled, and hence removing `bottle :unneeded` from formulae. The upload issue was a bug in Homebrew/brew that's been fixed. Thanks @bdw429s.

**Comment by bdw429s** [comment]
Thanks guys!

**Pull request closed without merging**
