### PR TITLE
clozure-cl: delete

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is installing binaries not building from source.

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by ylluminarious** [comment]
@ilovezfs I actually use this formula and a number of other people do as well. Would you accept a PR which re-adds this formula if it builds from source?

**Comment by paulvaneecke** [comment]
We also use this formula in an install script for our software. Would love to have it back.

**Comment by ilovezfs** [comment]
>Would you accept a PR which re-adds this formula if it builds from source?

Possibly. The documentation on source builds is relatively poor and it needs to be bootstrapped. I'd have to see the formula.

**Comment by ilovezfs** [comment]
In the meantime,
```
Josephs-MacBook-Pro:~ joe$ brew install clozure-cl
Error: No available formula with the name "clozure-cl" 
==> Searching for a previously deleted formula (in the last month)...
clozure-cl was deleted from homebrew/core in commit f726081:
  clozure-cl: delete (https://github.com/Homebrew/homebrew-core/issues/23970)

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show f726081^:Formula/clozure-cl.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by ylluminarious** [comment]
@ilovezfs Ok, I'll try to whip something up when I have time. Of course, anyone who is more familiar with Clozure CL is welcome to do it as well.

**Comment by vinay** [comment]
Would love to have this formula back. I use it a lot.

**Pull request merged**
