### PR TITLE
grafana 8.4.2

### PR DESCRIPTION
**Pull request by srclosson**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by cho-m** [comment]
Only Monterey ARM runner is running out of memory.

We do set `--max-old-space-size=4096` (MB), but it is exceeding that. We could try increasing limit depending on available RAM. It may also be worth checking upstream if increased build memory requirements are expected.

**Comment by SMillerDev** [comment]
@srclosson I see you work at Grafana, is there a minimal amount of RAM required to build Grafana?

**Comment by cho-m** [comment]
At this point, we can just try another run with more memory. Some examples I saw in upstream repo:
- [Dockerfile](https://github.com/grafana/grafana/blob/main/Dockerfile#L3) uses 8G `ENV NODE_OPTIONS=--max_old_space_size=8000`
- [.drone.yml](https://github.com/grafana/grafana/blob/main/.drone.yml#L145) uses either 4G `NODE_OPTIONS: --max_old_space_size=4096` or 8G `NODE_OPTIONS: --max_old_space_size=8192` at some steps

Also wasn't sure if the `NODE_ENV=production` is assumed in our installation, or if we building a Development version. ArchLinux is setting it for their package https://github.com/archlinux/svntogit-community/blob/packages/grafana/trunk/PKGBUILD#L80

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
