### PR TITLE
fastqc: update test

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

seeing test failure in:
- https://github.com/Homebrew/homebrew-core/pull/160907
- https://github.com/Homebrew/homebrew-core/pull/160573

### CODE REVIEW

**Comment by cho-m** [comment]
We should not modify the test as it is a valid failure. The JDK is crashing in Sonoma ARM.

More discussion in #159563.

**Comment by chenrui333** [comment]
oh, did not see that PR, close this one now. Thanks @cho-m!

**Comment by cho-m** [comment]
Going to reopen to do a quick re-run and make sure `openjdk` rebuilt with new SDK has fixed issue. Other PR has more modifications so easier to do here.

**Comment by cho-m** [comment]
It's fixed now.

**Pull request closed without merging**
