### PR TITLE
gcc 7-20170226 (new formula)

### PR DESCRIPTION
**Pull request by roederw**
- [✓] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds an updated gcc-7 formula

### CODE REVIEW

**Comment by fxcoudert** [comment]
GCC 7 has not been released, and there is not even a release candidate yet. GCC's development version can be installed with `brew install --HEAD gcc`. It is not clear to me why we would need a versioned GCC 7 formula at this stage.

**Comment by roederw** [comment]
When homebrew-versions used to exist we always had the latest development version of GCC, in its own formula mind you. Shouldn't we allow development versions of gcc? Also, head only hits 6.3.0. GCC-7 offers plenty of new features ready for testing. I don't see the downside to adding the formula.

**Comment by fxcoudert** [comment]
`gcc.rb` has:
```
  head "svn://gcc.gnu.org/svn/gcc/trunk"
```
which is GCC's current development branch, i.e. GCC 7. So a versioned formula would duplicate existing functionality.

**Comment by roederw** [comment]
I am reinstalling now. If it is pulling the latest GCC 7 development branch I also don't see the point in this new formula and will close it. Thanks!

**Comment by roederw** [comment]
After rebuilding it doesn't seem like TRUNK is pointing to GCC 7. It's pointing to development versions of GCC 6.3.0_A. In that case, I do believe opening a GCC 7 formula would be beneficial to anyone who would like to use it over the current HEAD.

**Comment by fxcoudert** [comment]
@roederw after rebuilding, what is the output of `gfortran -v`?

**Comment by roederw** [comment]
Sorry, my mistake. Just double checked. It's 100% GCC 7.

**Comment by fxcoudert** [comment]
Happy hacking @roederw!

**Pull request closed without merging**
