### PR TITLE
luajit: fix for Xcode 11

### PR DESCRIPTION
**Pull request by fxcoudert**
Works locally

### CODE REVIEW

**Comment by clason** [comment]
This change breaks neovim: Reinstalling the new(!) bottle and then `brew install neovim` leads to a non-functional install (see https://github.com/neovim/neovim/issues/11411); reverting to the old bottle fixes things.

**Comment by clason** [comment]
Actually, the bottle is just straight-up broken for me: 
```
> luajit
luajit: cannot create state: not enough memory
```
If I were to open an issue, what sort of information would be useful here?

**Comment by clason** [comment]
Ah, I see the issue is known. Sorry for the noise!

**Comment by fxcoudert** [comment]
I've reported the issue to https://github.com/LuaJIT/LuaJIT/issues/521 so to fix the issue one thing needs to happen:
- a new version is released
- a fix for LuaJIT-2.0.5 is proposed

At some point, if LuaJIT is broken / not releasing new versions, we'll have to remove it from Homebrew.

**Comment by clason** [comment]
But (and this is an honest question) don't you already have a fix (use the `lj_alloc.c`/patch from 2.1.0)?

The issue is that the new 2.0.5 bottle is broken on Catalina, which also means neovim is completely unusable there (neither the bottle nor building from source (`-s` or `--HEAD`) works). This can be fixed by changing the build recipe to use the bundled luajit (which is 2.1.0-beta3 by default).

**Comment by fxcoudert** [comment]
> I just saw the patch does not apply cleanly, but dumping the file works -- wouldn't that be a feasible patch?

Can you make a patch that applies against 2.0.5? I'm not sure just using that file works, there could be other changes in the rest of the source that affect this file.

If you can provide a patch, I'm willing to test it in Homebrew, and ship it if it works.

**Comment by fxcoudert** [comment]
Meanwhile, I've removed the Catalina bottle for now: b1635e668bf665e86da0efab3a652c78c0291255

What I do not understand is how that PR did pass testing on our CI in the first place! (And it really did, I have double-checked)

**Comment by clason** [comment]
I'll try tonight (not very familiar with homebrew hacking, especially patches)!

> Meanwhile, I've removed the Catalina bottle for now: b1635e6

Thanks!

> What I do not understand is how that PR did pass testing on our CI in the first place! (And it really did, I have double-checked)

Yeah, that's weird. It builds correctly, but the CI should have run it -- I guess? Does it test on (the latest) Catalina? I admit I don't understand the CI setup on this repo.

**Comment by clason** [comment]
> Meanwhile, I've removed the Catalina bottle for now: b1635e6

Sorry to say, the Mojave bottle has the same problem, so that didn't help :(

> If you can provide a patch, I'm willing to test it in Homebrew, and ship it if it works.

On the other hand, the attached formula works fine!
[luajit.rb.gz](https://github.com/Homebrew/homebrew-core/files/3860379/luajit.rb.gz)

**Comment by clason** [comment]
@fxcoudert Let me know if I should make a pull request for this; you seem to have more than enough to do...

**Comment by fxcoudert** [comment]
@clason yeah I'm swamped, all help is appreciated! cc me in the PR

**Comment by clason** [comment]
@fxcoudert done! (keeping the engines running looks like a massive undertaking -- I appreciate all the efforts!)

It's my first PR for homebrew; let me know if I need to change something!

**Pull request closed without merging**
