### PR TITLE
libcouchbase 2.9.5

### PR DESCRIPTION
**Pull request by avsej**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @avsej for the pull request!

I'm using this opportunity to remove the options, which have very low analytics (2 installs per month, i.e. 0.5% users).

**Comment by avsej** [comment]
So those users will be doomed? How having handy options makes formula worse, @fxcoudert?

**Comment by fxcoudert** [comment]
See #31510 for the rationale behind this move.
Another possibility is to build support for libuv and libev unconditionally, providing a feature-full package. Does that seem better?

**Comment by fxcoudert** [comment]
`  * C: 17: col 3: dependency "libev" (line 17) should be put before dependency "libevent" (line 16)`

**Comment by avsej** [comment]
@fxcoudert fixed

**Comment by javian** [comment]
Thanks @avsej !

**Pull request closed without merging**
