### PR TITLE
prototool 1.8.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by smaye81** [comment]
Just a note that this was done by someone not affiliated with the prototool project.  

We were not ready to have this bumped in Homebrew - this is incorrect as our 1.8.0 release is not finalized, and should be reverted.

**Comment by SMillerDev** [comment]
The idea is that anyone can submit updates to homebrew.

As for reverting the 1.8.0 release, since this is an official tag from upstream, is there any way we can monitor if something is "finalized" rather than just tagged? Cause for almost all projects making an immutable marker such as a  git tag means that that version is final.

**Comment by smaye81** [comment]
The release wasn't actually published yet, that was just a marker.  The delay was a result of some issues generating our release artifacts.  As a result, this should be a one-off problem.  We will try to be a bit more cautious before posting that tag.  In the meantime, if this could be reverted until we get the 1.8 release posted, that would be helpful.

**Comment by smaye81** [comment]
FYI -- the [v1.8.0 release](https://github.com/uber/prototool/releases/tag/v1.8.0) has officially been published.  If someone can revert this commit, I can publish a new update to Homebrew based on the official 1.8.0 release.

**Comment by SMillerDev** [comment]
You can publish an update either way

**Comment by smaye81** [comment]
Tried to run `brew bump-formula-pr` and see:

```
Error: You probably need to bump this formula manually since the new version
and old version are both 1.8.0.
```

**Pull request closed without merging**
