### PR TITLE
sshguard 2.1.0

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
The test is still broken, this is just some other fixes.

**Comment by JCount** [comment]
shoo @stale[bot] this mainly needs a new test

**Comment by JCount** [comment]
@ilovezfs All this needs is a test I believe, but creating one is proving a tad tricky.

**Comment by JCount** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
