### PR TITLE
readline 8.0.0

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by igas** [comment]
I'm not sure about good one, but I wrote https://github.com/igas/homebrew-revision-bump-commit

```
brew tap igas/revision-bump-commit
cd $(brew --repository homebrew/core)
brew revision-bump-commit readline awk
```

I used it once, use on your own risk, it's basically gsub + commit.

**Comment by fxcoudert** [comment]
Hi @leonklingele and thanks for opening this PR. I hope you don't mind, I took the liberty of pushing some revision bumps to your branch to get testing under way.

Based on previous round of testing (linkage errors), the following direct dependencies were revision-bumped: `abook afflib argus-clients augeas bacula-fd cadaver calc cgdb clisp crystal-icr devtodo dwarf ekg2 fontforge gawk ginac gjs gnu-chess gnu-smalltalk gnu-units gnuplot gnuplot@4 gphoto2 gqlplus grv guile guile@2.0 hss hstr hunspell kpcli ldapvi lftp libgda libqalculate libreadline-java lldpd mailutils mdbtools mdk monero monetdb ncmpcpp newlisp ngspice nickle octave opendbx pari pce pdsh postgres-xc postgresql postgresql@10 postgresql@9.4 postgresql@9.5 postgresql@9.6 profanity pspg pwsafe python python@2 r renameutils rlwrap ruby ruby@1.8 ruby@2.0 ruby@2.3 ruby@2.4 ruby@2.5 sdcv socat spatialite-tools spidermonkey sqlite takt tarantool telegram-cli tig vte vtk with-readline xdot yafc yosys z3`

**Comment by leonklingele** [comment]
Awesome! Thanks @fxcoudert! :)
How did you find those? Did you use @igas' script to automate things?

Based on the `depends_on` directive, those additional formula require a bump as well:

- asdf
- bareos-client
- citus
- freeciv
- gnu-apl
- lnav
- nnn
- pyenv
- ruby@2.4
- swi-prolog
- tdlib

**Comment by fxcoudert** [comment]
I took the list of linkage test failures from the first CI run. Yes, I have a little shell script to automate the revision bumps :)

Let's wait for the end of this CI cycle to see what is the global state of it, and decide how many more formulas need a revision bump.

**Comment by fxcoudert** [comment]
Need to be revision bumped: `libpqxx`. Other test failures are harder to interpret: some are due to conflicting formula requirements.

**Comment by leonklingele** [comment]
Does that mean we need to defer the bumps of those conflicting formulae to a later point of time when this PR has been merged? And `libpqxx` should probably depend on `readline` then, right?

**Comment by fxcoudert** [comment]
We probably need to identify the unrelated test failures, and fix them, to clean up the board a bit.

**Comment by fxcoudert** [comment]
In addition to `libpqxx`, `doitlive` and `sip` also need revision bumps (because `python`).

**Comment by fxcoudert** [comment]
Mojave test results:

- `test couchdb` existing test failure
- `test theharvester` existing test failure
- `unlink bareos-client`: `brew unlink --force bareos-client` gave `Error: invalid option: --force`. Why?!
- `bareos-client` not being uninstalled in turn prevented `bacula-fd` to install (they conflict)
- `unlink todoman`: `brew unlink --force todoman ` gave `Error: invalid option: --force`.
- This in turn prevented `devtodo` from installing.
- `audit ldapvi --online` has Debian mirror audit issues
- `yafc` also has Debian mirror audit issues
- `install pce` fails with `error: unable to find utility "nasm"`
- `audit postgres-xc --online` fails because their page has moved

High Sierra did not finish running because the node ran out of disk space :(

**Comment by fxcoudert** [comment]
Manually cleaned up all the nodes, `test-bot` fixed, misc audits and `pce` fixed in 
https://github.com/Homebrew/homebrew-core/pull/35936.

Let's try this again, @BrewTestBot test this please !

**Comment by fxcoudert** [comment]
- `gawk` failure on Sierra not reproducible, bottles fixed: 4e15f7174773f861617895f4152a858612107b70
- Most of the test issues appear to be random network failures, except `couchdb`

**Pull request closed without merging**
