### PR TITLE
Functions 0.2.5 (new formula)

### PR DESCRIPTION
**Pull request by seiflotfy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
`test` failure:

```
==> /usr/local/Cellar/functions/0.2.25/bin/fn-server -help
time="2017-03-01T14:44:00Z" level=fatal msg="couldn't connect to docker daemon" error="Get http://unix.sock/_ping: dial unix /var/run/docker.sock: connect: no such file or directory" 
Error: functions: failed
Failed executing: /usr/local/Cellar/functions/0.2.25/bin/fn-server -help
```

**Comment by MikeMcQuaid** [comment]
@woodruffw Agreed 👍

**Comment by dunn** [comment]
Ping?

**Comment by seiflotfy** [comment]
Sorry was out of order. Taking care of this again :D

**Comment by bfontaine** [comment]
Closing due to inactivity. Feel free to open a new PR that adresses the feedback above. Thanks!

**Pull request closed without merging**
