### PR TITLE
snapcraft 4.8.1

### PR DESCRIPTION
**Pull request by sergiusens**
With required dependency updates.

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
Test fails on Apple Silicon:
```
==> /opt/homebrew/Cellar/snapcraft/4.8.1/bin/snapcraft --version
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/bin/snapcraft", line 5, in <module>
    from snapcraft.cli.__main__ import run
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/__init__.py", line 354, in <module>
    from snapcraft._store import (  # noqa
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/_store.py", line 34, in <module>
    from snapcraft import storeapi, yaml_utils
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/__init__.py", line 22, in <module>
    from . import http_clients  # noqa: F401 isort: skip
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/__init__.py", line 20, in <module>
    from ._candid_client import CandidClient  # noqa: F401
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/_candid_client.py", line 14, in <module>
    from . import agent, _config, _http_client
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/_http_client.py", line 34, in <module>
    class Client:
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/_http_client.py", line 37, in Client
    def __init__(self, *, user_agent: str = agent.get_user_agent()) -> None:
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/agent.py", line 50, in get_user_agent
    arch = project.Project().deb_arch
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/project/_project.py", line 50, in __init__
    super().__init__(target_deb_arch, debug, work_dir=work_dir)
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/project/_project_options.py", line 237, in __init__
    self._set_machine(target_deb_arch)
  File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/project/_project_options.py", line 361, in _set_machine
    self.__machine_info = _ARCH_TRANSLATIONS[self.__target_machine]
KeyError: 'arm64'
```

**Comment by sergiusens** [comment]
> Test fails on Apple Silicon:
> 
> ```
> ==> /opt/homebrew/Cellar/snapcraft/4.8.1/bin/snapcraft --version
> Traceback (most recent call last):
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/bin/snapcraft", line 5, in <module>
>     from snapcraft.cli.__main__ import run
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/__init__.py", line 354, in <module>
>     from snapcraft._store import (  # noqa
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/_store.py", line 34, in <module>
>     from snapcraft import storeapi, yaml_utils
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/__init__.py", line 22, in <module>
>     from . import http_clients  # noqa: F401 isort: skip
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/__init__.py", line 20, in <module>
>     from ._candid_client import CandidClient  # noqa: F401
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/_candid_client.py", line 14, in <module>
>     from . import agent, _config, _http_client
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/_http_client.py", line 34, in <module>
>     class Client:
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/_http_client.py", line 37, in Client
>     def __init__(self, *, user_agent: str = agent.get_user_agent()) -> None:
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/storeapi/http_clients/agent.py", line 50, in get_user_agent
>     arch = project.Project().deb_arch
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/project/_project.py", line 50, in __init__
>     super().__init__(target_deb_arch, debug, work_dir=work_dir)
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/project/_project_options.py", line 237, in __init__
>     self._set_machine(target_deb_arch)
>   File "/opt/homebrew/Cellar/snapcraft/4.8.1/libexec/lib/python3.9/site-packages/snapcraft/project/_project_options.py", line 361, in _set_machine
>     self.__machine_info = _ARCH_TRANSLATIONS[self.__target_machine]
> KeyError: 'arm64'
> ```

This is a known upstream issues tagged for fixing in a future release. Older versions also fail the same way. Is that a blocker for this version?

**Comment by bayandin** [comment]
> This is a known upstream issues tagged for fixing in a future release. Older versions also fail the same way. Is that a blocker for this version?

The current version that we have (4.4.1) works on Apple Silicon (at least it passed the test), I guess it's a blocker. 
We can apply a patch from upstream for 4.8.1 when the problem will be fixed

**Comment by cho-m** [comment]
For existing 4.4.1 ARM bottle, I just tried it out and see that, although it doesn't error on `snapcraft --version` (Homebrew test), it does hit the same `KeyError` with `snapcraft login` (https://bugs.launchpad.net/snapcraft/+bug/1925374).

**Comment by cho-m** [comment]
New commit today: https://github.com/snapcore/snapcraft/pull/3535
We can try patching it in

**Review by nandahkrishna — APPROVED** [review]
Thanks, @sergiusens and @cho-m.

**Pull request closed without merging**
