### PR TITLE
mvtools: fixed build issues on apple silicon

### PR DESCRIPTION
**Pull request by Stefan-Olt**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
As there doesn't seem to be any development going on at the original repo I forked it and fixed the build issues on Apple Silicon

### CODE REVIEW

**Comment by SMillerDev** [comment]
Did you try upstreaming those changes? Because changing the source of a package is a big change and we generally require upstream's "blessing" to accept that.

**Comment by Stefan-Olt** [comment]
Is there some way to figure out what the problem with the test "12-arm64" is? I tested on 12-arm64 and it build, here it is just showing `error` without any further information, that's not helpful to fix it, as I can build this fine on 12-arm64 (that was my idea, to fix this build issue).

**Comment by Stefan-Olt** [comment]
There isn't any active development anymore, this is a fork from a fork (that fixes ARM on Linux)

**Comment by Bo98** [comment]
> There isn't any active development anymore,

Worth noting upstream were responding to bug reports as recently as a few months ago.

> I forked it and fixed the build issues on Apple Silicon

Given the purpose of this is just that, instead of a hard fork and calling that the new official home, it's probably better to just have the individual patches applied via `patch do` blocks. The bar for that is much lower and I'd say we would probably accept that.

Ideally a PR would be submitted upstream with those patches to satisfy the policy that we always forward patches upstream, but given the changes seem small and simple enough, they don't necessarily need to wait to be merged upstream if you think upstream development is completely dead.

**Pull request closed without merging**
