### PR TITLE
mavsdk 0.35.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
CMake Error at CMakeLists.txt:25 (message):
  The argument BUILD_BACKEND has been replaced by BUILD_MAVSDK_SERVER.  To
  build mavsdk_server, use -DBUILD_MAVSDK_SERVER=ON.
```
You need to `s/BACKEND/MAVSDK_SERVER`

**Comment by carlocab** [comment]
Why is it trying to build its own openssl?
```
make: *** [all] Error 2
CMake Error at third_party/cmake/build_target.cmake:49 (message):
  /tmp/mavsdk-20210104-74106-wfl0n0/build/default/third_party/openssl failed
  to build!
Call Stack (most recent call first):
  third_party/CMakeLists.txt:20 (build_target)
```

**Comment by carlocab** [comment]
Killed the tests as they seem to be failing anyway. Plus, this formula seems to be vendoring its own dependencies, and I don't think we want that.

**Comment by chenrui333** [comment]
we can PR to update cmake to check if there is openssl installed.

**Comment by chenrui333** [comment]
it does not need to use the vendored ssl.

**Comment by carlocab** [comment]
Yea, I imagine it doesn't. Can we check that it doesn't vendor anything else?

**Pull request closed without merging**
