### PR TITLE
opensc 0.16.0

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Yosemite execution of `brew test` hung here for two hours whereas the others took three minutes, so aborted for now.

**Comment by nijikon** [comment]
@DomT4 what are we doing with this?

**Comment by DomT4** [comment]
Who knows. We saw something similar repeatedly in the past so I just ended up ripping the test out, but obviously it was returned at some point.

**Comment by nijikon** [comment]
@DomT4 can we merge this or what?

**Comment by DomT4** [comment]
I'd remove the test again until we can work out why it takes hours _exclusively_ on CI & merge it then, personally.

**Comment by ab** [comment]
Bash completion appears to be broken in this version. Are there plans to upgrade to the HEAD version with the fix?

https://github.com/OpenSC/OpenSC/issues/782

**Comment by DomT4** [comment]
@ab We'd be happy to take a backport of the fix by applying the patch from https://github.com/OpenSC/OpenSC/commit/da4446a822b949b90356ff05569824e5059f07c9, if someone wants to file a PR.

**Pull request closed without merging**
