### PR TITLE
flow v0.44.0

### PR DESCRIPTION
**Pull request by gabelevi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @gabelevi for your contribution to Homebrew!

**Comment by ilovezfs** [comment]
@gabelevi just for future reference, the standard bump subject is `flow 0.44.0` not `flow v0.44.0`. If you use `brew bump-formula-pr` it will handle such pedantry for you.

**Comment by gabelevi** [comment]
Sorry about that! I [usually get this right](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aclosed+author%3Agabelevi). I didn't know about `brew bump-formula-pr`! I'll try it next time!

**Comment by ilovezfs** [comment]
No problem at all. I hope you find the command useful.

**Pull request closed without merging**
