### PR TITLE
libassuan 2.4.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 you're slipping!

**Comment by DomT4** [comment]
I’m on a train, I’m claiming that as a legitimate excuse 😜.

**Comment by ilovezfs** [comment]
```

Libassuan | 2.4.4 | 2017-11-16 | 550k | download | download
-- | -- | -- | -- | -- | --


```

**Comment by DomT4** [comment]
Oh 😱. Did they not announce it on the GnuPG list, hmm 🙈.

**Comment by DomT4** [comment]
I can't find an announcement email so I'm resuming claiming extenuating circumstances, heh.

**Pull request closed without merging**
