### PR TITLE
tass64 1.53.1515 (new formula)

### PR DESCRIPTION
**Pull request by rhalkyard**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
`64tass` is a popular assembler for the 65xx series of microprocessors found in many early home computers.

Project's real name is `64tass`, which is not a valid formula name. Add an alias to work around this.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Looks neat, just a couple of comments:

Could you remove the head spec completely? Doesnt make sense to have it commented out.

Is the alias you added a commonly used name for the program?

**Comment by rhalkyard** [comment]
> Is the alias you added a commonly used name for the program?

From what I understand, the `64tass` alias is the developer's preferred name for the application - it is what is used in the [reference manual](http://tass64.sourceforge.net/) and the name of the executable itself. `tass64` appears to only be used in situations where leading digits aren't allowed, such as in the project's SourceForge URL.

I wasn't able to create a `64tass` formula - presumably since Ruby class names can't start with a digit, so I followed the pattern of `0mq` -> `zeromq` and other such aliases.

**Comment by SMillerDev** [comment]
Cool, thanks for the explanation. Looks good to me.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @rhalkyard for the pull request

**Pull request closed without merging**
