### PR TITLE
teleport: port linux changes

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Part of https://github.com/Homebrew/linuxbrew-core/issues/23986

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> curl --insecure https://localhost:3080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 3080 after 0 ms: Connection refused
```

**Comment by SMillerDev** [comment]
I'm so confused how it works in the linuxbrew repo.

**Comment by iMichka** [comment]
The test does not pass on Linux: https://github.com/Homebrew/linuxbrew-core/runs/3204799716?check_suite_focus=true (I just ran a build there to have a look). It was maybe a failed attempt to fix it, which worked at one point way back.

So you can disregard the linuxbrew-core fix, and maybe find a better one.

**Comment by SMillerDev** [comment]
It works locally for me now, I'm on Arch by the way :smile:

**Comment by SMillerDev** [comment]
> 2021-08-02T20:20:18Z ERRO [PROC:1]    Critical service proxy.init has exited with error the teleport binary was built without web assets, try building with `make release`, aborting. service/signals.go:144

This is the issue, it doesn't happen when I build on my own machine though. @iMichka maybe we can test on the self-hosted runner to check if it's a debian or a docker issue?

**Comment by SMillerDev** [comment]
Since the self-hosted runners self-host the docker container, that didn't help.

**Comment by SMillerDev** [comment]
Checking again based on teleport 7.0

**Pull request closed without merging**
