### PR TITLE
xmake: update v2.0.1

### PR DESCRIPTION
**Pull request by waruqi**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing:
```
==> /usr/local/Cellar/xmake/2.0.1/bin/xmake
error: null
Error: xmake: failed
```

**Comment by DomT4** [comment]
Not completely sure why you removed the bottles? The CI knows to ignore them when the version changes, and was unrelated to the test failure.

**Comment by ilovezfs** [comment]
The problem here is that the test uses an empty file, which is no longer tolerated. This fixes it:
```
  test do
    cp_r (pkgshare/"templates/c/shared_library/project").children, testpath
    assert_match "build ok!", pipe_output(bin/"xmake")
  end
```

**Comment by waruqi** [comment]
I fixed it. :)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/2f7656e38f09041fcb2c64e9497220a7af41a396. Thank you for your contribution to Homebrew @waruqi; we appreciate it! :smiley_cat:

**Pull request closed without merging**
