### PR TITLE
spidermonkey 102.3.0, gjs 1.74.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
`gjs` and `couchdb` are probably going to fail since they have specific versions.

**Comment by Bo98** [comment]
> For `gjs`, HEAD build should use this formula (it depends on [`mozjs-102`](https://gitlab.gnome.org/GNOME/gjs/-/blob/master/meson.build#L131)) but stable release is still using [`mozjs-91`](https://gitlab.gnome.org/GNOME/gjs/-/blob/1.72.2/meson.build#L129)

Sounds like that might be out with the imminent GNOME 43 release.

**Comment by Bo98** [comment]
And indeed gjs 1.74.0 is here.

**Comment by Bo98** [comment]
This release looks like it breaks `--with-system-*` flags on macOS: https://bugzilla.mozilla.org/show_bug.cgi?id=1776255

gjs applied this patch: https://github.com/ptomato/mozjs/commit/f2d9f096fb3e99074dc30ee1bf7be72592230f8f. Though upstream seem to want to enforce bundling libraries on macOS

**Comment by chenrui333** [comment]
Gonna resume the work in this fresh PR, #120675

**Pull request closed without merging**
