### PR TITLE
testdisk 7.2

### PR DESCRIPTION
**Pull request by JuPlutonic**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JuPlutonic** [comment]
<details open="">
  <summary>Todo: add new bug on testdisk compilation</summary>
  <pre> Installation error in QT5 related, but my OS is LUBUNTU 19.04 - DE worked on system's Qt, also complicated Qt suites were compiled from source in this setup without errors... So, I think TESTDISK need to be bottled... 
 
Previous testdisk (7.1WIP) installation didn't work 
```sh
==> make install
Last 15 lines from /home/salessionato/.cache/Homebrew/Logs/testdisk/02.make:
gcc-5 -DHAVE_CONFIG_H -I. -I..     -g -O2 -Wdeclaration-after-statement -Wall -Wextra -MD -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wwrite-strings -W -Wcast-align -Waggregate-return -Wbad-function-cast -Wcast-qual -Wundef -Wredundant-decls -Wsign-compare -Wnested-externs -Winline -Wdisabled-optimization -Wfloat-equal -Wmissing-format-attribute -Wmultichar -Wc++-compat -Wformat=2 -Wunreachable-code -Wvla -fstack-protector-strong  -c -o file_zpr.o file_zpr.c
gcc-5 -DHAVE_CONFIG_H -I. -I..     -g -O2 -Wdeclaration-after-statement -Wall -Wextra -MD -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wwrite-strings -W -Wcast-align -Waggregate-return -Wbad-function-cast -Wcast-qual -Wundef -Wredundant-decls -Wsign-compare -Wnested-externs -Winline -Wdisabled-optimization -Wfloat-equal -Wmissing-format-attribute -Wmultichar -Wc++-compat -Wformat=2 -Wunreachable-code -Wvla -fstack-protector-strong  -c -o partgptro.o partgptro.c
gcc-5 -DHAVE_CONFIG_H -I. -I..     -g -O2 -Wdeclaration-after-statement -Wall -Wextra -MD -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wwrite-strings -W -Wcast-align -Waggregate-return -Wbad-function-cast -Wcast-qual -Wundef -Wredundant-decls -Wsign-compare -Wnested-externs -Winline -Wdisabled-optimization -Wfloat-equal -Wmissing-format-attribute -Wmultichar -Wc++-compat -Wformat=2 -Wunreachable-code -Wvla -fstack-protector-strong  -c -o suspend_no.o suspend_no.c
gcc-5 -DHAVE_CONFIG_H -I. -I..     -g -O2 -Wdeclaration-after-statement -Wall -Wextra -MD -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wwrite-strings -W -Wcast-align -Waggregate-return -Wbad-function-cast -Wcast-qual -Wundef -Wredundant-decls -Wsign-compare -Wnested-externs -Winline -Wdisabled-optimization -Wfloat-equal -Wmissing-format-attribute -Wmultichar -Wc++-compat -Wformat=2 -Wunreachable-code -Wvla -fstack-protector-strong  -c -o fidentify.o fidentify.c
g++-5 -DHAVE_CONFIG_H -I. -I..    -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -g -O2 -Wall -MD -Wpointer-arith -Wmissing-declarations -Wshadow -Wwrite-strings -W -Wcast-align -Wcast-qual -Wundef -Wredundant-decls -Wsign-compare -Wdisabled-optimization -Wmissing-format-attribute -Wmultichar -Wformat=2 -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -Wvla --std=c++14 -fstack-protector-strong  -c -o qphotorec-qmainrec.o `test -f 'qmainrec.cpp' || echo './'`qmainrec.cpp
qmainrec.cpp:27:24: fatal error: QApplication: No such file or directory
compilation terminated.
g++-5 -DHAVE_CONFIG_H -I. -I..    -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -g -O2 -Wall -MD -Wpointer-arith -Wmissing-declarations -Wshadow -Wwrite-strings -W -Wcast-align -Wcast-qual -Wundef -Wredundant-decls -Wsign-compare -Wdisabled-optimization -Wmissing-format-attribute -Wmultichar -Wformat=2 -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -Wvla --std=c++14 -fstack-protector-strong  -c -o qphotorec-qphotorec.o `test -f 'qphotorec.cpp' || echo './'`qphotorec.cpp
make[1]: *** [Makefile:2155: qphotorec-qmainrec.o] Error 1
make[1]: *** Waiting for unfinished jobs....
qphotorec.cpp:59:24: fatal error: QApplication: No such file or directory
compilation terminated.
make[1]: *** [Makefile:2169: qphotorec-qphotorec.o] Error 1
make[1]: Leaving directory '/tmp/testdisk-20191208-12315-1iyavo/testdisk-7.1/src'
make: *** [Makefile:437: install-recursive] Error 1

```
  </pre>
</details>

**Comment by JuPlutonic** [comment]
Could I add this:
```ruby
bottle do
    cellar :any
end
```

**Comment by JuPlutonic** [comment]
Why I see PR it in Homebrew/homebrew-core PR-s but not on the Homebrew/linuxbrew-core?

**Comment by SMillerDev** [comment]
Linuxbrew merges changes from homebrew regularly. If possible all updates should be done to homebrew and then merged into linuxbrew, regardless of the platform used to make the pull request.

**Comment by SMillerDev** [comment]
Now as for the PR, homebrew and by extension linuxbrew only ship stable versions (https://docs.brew.sh/Acceptable-Formulae#stable-versions) and the `WIP` in the URL suggests this is not a stable version.

**Comment by JuPlutonic** [comment]
Ok, for me WIP in testdisk is generic thing so I forget about "prefer stable over unversioned/unstable for aceptance"

**Pull request closed without merging**
