### PR TITLE
coq: fix emacs caveat

### PR DESCRIPTION
**Pull request by hrldcpr**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

The emacs major mode bundled with Coq is called `gallina.el`, not `coq.el` file, so the current caveat doesn't work.

From the [Coq Reference Manual](https://coq.inria.fr/refman/Reference-Manual017.html) section 15.6.1:

> Coq comes with a Major mode for GNU Emacs, `gallina.el`.
> Add the following lines to your .emacs file:
> 
> ```
> (setq auto-mode-alist (cons '("\\.v$" . coq-mode) auto-mode-alist))
> (autoload 'coq-mode "gallina" "Major mode for editing Coq vernacular." t)
> ```

### CODE REVIEW

**Comment by dunn** [comment]
I wonder if the entire caveats section should be removed; it's not Homebrew-specific information, so there's no point replicating upstream docs (and getting them wrong).

**Comment by hrldcpr** [comment]
Good question. I personally found it useful, since the files only end up in that location because of the specific `--emacslib` option passed to the build by this formula.

**Comment by dunn** [comment]
The caveats message doesn't tell you where it's been installed, does it?

**Comment by hrldcpr** [comment]
Yeah you're right, that message (which for the record is `Emacs Lisp files have been installed to: /usr/local/share/emacs/site-lisp/coq`) must come from homebrew.

I don't have much an opinion either way—no caveats, or corrected caveats, both are probably better than the current incorrect situation.

**Comment by dunn** [comment]
Ah, yeah; we print that message when elisp is installed in `share/formula_name`.

Let's go ahead and remove the caveats, thanks!

**Comment by hrldcpr** [comment]
Sounds good, removed.

**Comment by ilovezfs** [comment]
That build failure smells like a parallelization problem.

**Comment by hrldcpr** [comment]
Yeah weird… I've just pushed again in hopes that will trigger the CI again, we shall see.

**Comment by hrldcpr** [comment]
Weird, the CI failed again… It definitely works on my machine, plus it's hard to see how removing the caveats could cause a build failure. I'll leave it to you experts.

**Comment by ilovezfs** [comment]
Well, it was 10.11 not 10.10 so that pretty much confirms it's a parallelization issue :)

Please add a commit making it
```
ENV.deparallelize { system "make", "install" }
```

**Comment by hrldcpr** [comment]
Thanks for looking into it, committed.

**Comment by dunn** [comment]
Thanks! Merged as 13c57c3651489007e9e72cd7b0f0c156d0e0d605 and a12ab38e246ef5c6c26d0c8198d9349ad08656f0.

**Pull request closed without merging**
