### PR TITLE
fish 3.6.2

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zanchey** [comment]
Don't publish this, please, the test suite is broken.

**Comment by osalbahr** [comment]
Superseded by:
- #156344

**Comment by osalbahr** [comment]
@zanchey out of curiosity, how were you able to find this PR so quickly?

**Comment by zanchey** [comment]
I came to make it myself!

**Pull request closed without merging**
