### PR TITLE
mapnik: revision for gdal

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes:

```
2020-11-29T15:40:57.4198860Z �[34m==>�[0m �[1mbrew linkage --test mapnik�[0m
2020-11-29T15:40:59.6497430Z �[31m==>�[0m �[1m�[31mFAILED�[0m�[0m
2020-11-29T15:40:59.6498070Z Missing libraries:
2020-11-29T15:40:59.6498620Z   unexpected (/usr/lib/libpq.5.dylib)
2020-11-29T15:40:59.6499170Z Broken dependencies:
2020-11-29T15:40:59.6499900Z   /usr/local/opt/gdal/lib/libgdal.27.dylib (gdal)
```

### CODE REVIEW

**Comment by fxcoudert** [comment]
I don't understand where the `/usr/lib/libpq.5.dylib` is coming from

**Comment by iMichka** [comment]
`gdal` depends on `libpq`. But I am unsure what happened here.

I saw this while rebuilding `popper` on CI.

**Comment by fxcoudert** [comment]
There are some upstream fixes for it, but I don't know which commit is the right one (if any): https://github.com/mapnik/mapnik/issues/4196

**Comment by Rylan12** [comment]
FYI using [`@redneb`'s patch](https://github.com/redneb/gentoo-mapnik-overlay/blob/master/sci-geosciences/mapnik/files/mapnik-3.0.23-boost-1.74.patch) that they linked in https://github.com/mapnik/mapnik/issues/4196 worked locally.

**Comment by iMichka** [comment]
I asked if they can tag a new release. If not, I'll add the patch tomorrow.

**Comment by iMichka** [comment]
I went for the patch as the new release should come before end of the year, but we did not get a clear date.

**Pull request closed without merging**
