### PR TITLE
sourcekitten 0.26.0

### PR DESCRIPTION
**Pull request by jpsim**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jpsim** [comment]
Can CI be kicked off on this again? It doesn't seem to have run on the last commit.

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by jpsim** [comment]
Can this be merged?

**Comment by chenrui333** [comment]
I will take care of it now. Thanks @jpsim !!

**Comment by jpsim** [comment]
Thanks!

**Pull request closed without merging**
