### PR TITLE
semgrep 0.112.1

### PR DESCRIPTION
**Pull request by brendongo**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  semgrep:
    * Libraries were compiled with a flat namespace.
      This can cause linker errors due to name collisions, and
      is often due to a bug in detecting the macOS version.
        /opt/homebrew/Cellar/semgrep/0.112.1/libexec/lib/python3.10/site-packages/semgrep/bin/semgrep_bridge_core.so
```

**Comment by iMichka** [comment]
@brendongo can you open an issue at https://github.com/returntocorp/semgrep and ask what is going on with the .so file built on macOS (it should be a .dylib file): `lib/python3.10/site-packages/semgrep/bin/semgrep_bridge_core.so`

**Comment by cho-m** [comment]
May be `dune` behavior? From quick glance, it looks like `semgrep` is using `dune` DSL which just says to compile a shared library.

https://github.com/returntocorp/semgrep/blob/v0.112.1/semgrep-core/src/cli-bridge/dune#L23
```
  (modes (native shared_object))
```

**Comment by spencerdrak** [comment]
Hi all - sorry we're a bit late to the party, but we're also looking at this on the semgrep side. We'll be in touch if we have any questions. Thanks!

**Comment by smcpeak** [comment]
Regarding the origin of the flat namespace, `ocamlopt` unconditionally passes `-flat_namespace` when making a shared library.  This behavior is hardcoded in the OCaml `configure.ac` script:

https://github.com/ocaml/ocaml/blob/4.14/configure.ac#L945

```
    [*-apple-darwin*],
      [mksharedlib="$CC -shared \
                   -flat_namespace -undefined suppress -Wl,-no_compact_unwind \
                   \$(LDFLAGS)"
      supports_shared_libraries=true],
```

I traced this back to the commit on 2002-11-15 that added dynamic library support for macOS to OCaml, but there isn't any explanation of the rationale:

  https://github.com/ocaml/ocaml/commit/c4411b3972b2e3b2ed8520b60fd80010e25e6bdf

In any case, I can override that by appending `-twolevel_namespace`.  However, `ld` will then complain that `-undefined suppress` is incompatible with two-level names, so that needs to be overridden as well.  On the `ocamlopt` command line, the full incantation then looks like:

```
-ccopt -Wl,-twolevel_namespace -ccopt -Wl,-undefined -ccopt -Wl,error
```

With that change, `otool -hV` shows the `TWOLEVEL` flag, which should pacify `brew audit`.  The resulting library appears to still work for its intended purpose.  I'm working on getting this fixed in `semgrep`.

**Comment by spencerdrak** [comment]
We're going to close this PR in favor of superceding. Our fixes should be included in the new PR we open. Thanks all for the assistance!

**Comment by chenrui333** [comment]
#110828

**Pull request closed without merging**
