### PR TITLE
dvc 0.63.4 (new formula)

### PR DESCRIPTION
**Pull request by efiop**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
Thanks @efiop for your contribution to Homebrew! :tada: 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Review by chenrui333 — APPROVED** [review]

**Comment by fxcoudert** [comment]
```
depends_on "openssl"
```

No, please don't 😢 
We are actively getting rid of OpenSSL 1.0: https://github.com/Homebrew/homebrew-core/issues/46454 and it should definitely not be introduced in new formulas

**Comment by efiop** [comment]
@fxcoudert Oh, sorry for that! Will send a PR ASAP.

**Comment by efiop** [comment]
@fxcoudert Created https://github.com/Homebrew/homebrew-core/pull/46829 . Please take a look. Thanks for the heads up and sorry for the inconvenience!

**Pull request closed without merging**
