### PR TITLE
appium 1.19.1

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chrmoritz** [comment]
The issue here is, that `appium` uses an hacky / unsupported way to create a bin symlink to a binary of one of it dependencies: https://github.com/appium/appium/blob/master/package.json#L31 .
This has worked before in npm 6-, but it looks like npm 7+ made changes to the installation order and not tries to create these bin symlinks before installing the dependencies. This of course works fine if the `bin` refers to only local file, but in this case it breaks, because the dependency it's pointing to isn't installed yet.

A workaround would removing that `authorize-ios` `bin` field from the `package.json`and creating this symlink later by ourself until upstream fully supports `npm@7`.

```diff
diff --git a/Formula/appium.rb b/Formula/appium.rb
index f4d19e5b3b..08a604c462 100644
--- a/Formula/appium.rb
+++ b/Formula/appium.rb
@@ -22,7 +22,12 @@ class Appium < Formula
   depends_on "node"
 
   def install
+    # workaround packaging bug exposed in npm 7+ (bin smylinks are now created
+    # before installing dependencies) => manually create symlink for authorize-ios
+    inreplace "package.json", "\"appium\": \"./build/lib/main.js\",", "\"appium\": \"./build/lib/main.js\""
+    inreplace "package.json", "\"authorize-ios\": \"./node_modules/.bin/authorize-ios\"", ""
     system "npm", "install", *Language::Node.std_npm_install_args(libexec)
+    ln_s libexec/"lib/node_modules/appium/node_modules/.bin/authorize-ios", libexec/"bin/authorize-ios"
     bin.install_symlink Dir["#{libexec}/bin/*"]
   end
 

```

**Comment by SMillerDev** [comment]
https://github.com/appium/appium/issues/14901 would suggest that the latest NPM version would work. But I'll apply your patch instead.

**Comment by chrmoritz** [comment]
The suggested fix with `npm i -g npm@latest` is actually a downgrade to the latest `npm@6` version, because that's what said command does. The `latest` tag of npm still points to the LTS `npm@6`release line, while the current version of node already uses the current stable `npm@7` release line (yeah, it's a bit confusing).

**Review by chenrui333 — APPROVED** [review]
👍

**Pull request closed without merging**
