### PR TITLE
ffmpeg: add enable-libpulse option

### PR DESCRIPTION
**Pull request by dericed**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dericed** [comment]
:'(

**Review by retokromer — APPROVED** [review]

**Comment by iMichka** [comment]
Hi. @fxcoudert has been removing options in ffmpeg lately. Not sure we want to bring in another one.

**Comment by fxcoudert** [comment]
Yes, we need to figure out a good strategy for users that want all the bells and whistles of ffmpeg. But individual options are not the way to go…

Thanks @dericed for suggesting it anyway, we are going to decline.

**Comment by macserv** [comment]
> Yes, we need to figure out a good strategy for users that want all the bells and whistles of ffmpeg.

@fxcoudert Is there (or can there be) a tracking issue opened for this?  I didn't see one with a cursory search.

It seems like a somewhat important topic, and could set an overall tone for HomeBrew as a whole.  Consider that if an option isn't supported by HomeBrew, then the user is left without recourse unless they're capable of pulling all the sources, configuring, patching, and building it themselves.  They essentially go from "zero effort," to "zero assistance."

In general, I certainly do appreciate the effort to simplify things, and I thought that your recent patch to the ffmpeg formula was a very well-reasoned and carefully-crafted step in that direction.  Thanks for your consideration.

**Comment by dericed** [comment]
I appreciate @macserv's comments. I have contributed a few times to homebrew, not in order to have all the bells and whistles of ffmpeg, to make features from ffmpeg that I consider useful accessible through homebrew. I didn't mean for the patch to be considered frivolous and hope that homebrew is open-minded to consider supporting configuration options which the community finds useful.

**Pull request closed without merging**
