### PR TITLE
mysql-connector-c++ 8.0.32

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

continuing #112854

### CODE REVIEW

**Comment by chenrui333** [comment]
I dont know why linux build failed, I will check on the action runner later.

**Comment by chenrui333** [comment]
I can reproduce this issue

```
==> Testing mysql-connector-c++
==> /home/linuxbrew/.linuxbrew/bin/g++-12 test.cpp -std=c++11 -I/home/linuxbrew/.linuxbrew/Cellar/mysql-connector-c++/8.0.31/include -L/home/linuxbrew/.linuxbrew/Cellar/mysql-connector-c++/8.0.31/lib -lmysqlcppconn8 -o test
Last 15 lines from /home/codespace/.cache/Homebrew/Logs/mysql-connector-c++/test.01.g++-12:
2023-01-15 18:28:35 +0000

/home/linuxbrew/.linuxbrew/bin/g++-12
test.cpp
-std=c++11
-I/home/linuxbrew/.linuxbrew/Cellar/mysql-connector-c++/8.0.31/include
-L/home/linuxbrew/.linuxbrew/Cellar/mysql-connector-c++/8.0.31/lib
-lmysqlcppconn8
-o
test

/usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/12/liblto_plugin.so: error loading plugin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/12/liblto_plugin.so)
collect2: error: ld returned 1 exit status
Error: mysql-connector-c++: failed
An exception occurred within a child process:
  BuildError: Failed executing: /home/linuxbrew/.linuxbrew/bin/g++-12 test.cpp -std=c++11 -I/home/linuxbrew/.linuxbrew/Cellar/mysql-connector-c++/8.0.31/include -L/home/linuxbrew/.linuxbrew/Cellar/mysql-connector-c++/8.0.31/lib -lmysqlcppconn8 -o test
```

**Comment by chenrui333** [comment]
needs #120679

**Comment by cho-m** [comment]
Looking up `exit code 137`, it appears to be an OOM failure. Either a memory leak or the build is using too much memory.

In case of latter, could try deparallelizing to reduce memory usage.

**Comment by chenrui333** [comment]
> Looking up `exit code 137`, it appears to be an OOM failure. Either a memory leak or the build is using too much memory.
> 
> In case of latter, could try deparallelizing to reduce memory usage.

I was kind of thinking the same thing too.

**Comment by cho-m** [comment]
Still seems to be killing the container, which makes it difficult to debug as we get no logs. Could try on self-hosted or may need to debug locally to find out what is going wrong.

**Comment by danielnachun** [comment]
Unfortunately I can't reproduce this locally - the test works with no issues.  It might be worth trying this on the self-hosted runner to see if it has more resources and doesn't get killed.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
