### PR TITLE
astrometry-net 0.79

### PR DESCRIPTION
**Pull request by GabriellaXue**
hi from hack illinois!

### CODE REVIEW

**Comment by brettkoonce** [comment]
see #50891

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Just updated the resource as well and tested locally.

**Comment by Bo98** [comment]
BrewTestBot misplaced to have misplaced the patch for `brew pull`.

@BrewTestBot test this please

**Pull request closed without merging**
