### PR TITLE
x264 r2999

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Previous attempt for r2991: #49295

### CODE REVIEW

**Comment by bayandin** [comment]
Catalina results:
```
brew audit --skip-style opencv --online
brew install --verbose --build-bottle ffmpeg2theora
brew audit --skip-style ffmpeg2theora --online
brew install --verbose --build-bottle komposition
brew audit --skip-style opencv@2 --online
brew audit --skip-style opencv@3 --online
```

`ffmpeg2theora` is going to be deleted in https://github.com/Homebrew/homebrew-core/pull/51883 ("No longer builds from source, even with Debian patches that upgrade
its scons build system for Python 3.8.")

**Comment by EricFromCanada** [comment]
Added a shims fix for the opencv formulae, so the only issue left is komposition not building in any contexts with what appears to be an unrelated issue (@athas?):
```
src/Komposition/Logging.hs:33:38: error:
    Not in scope: type constructor or class ‘StringConv’
   |
33 |      (Member Log sig, Carrier sig m, StringConv s Text)
   |                                      ^^^^^^^^^^
```

**Comment by athas** [comment]
That looks like the usual Haskell fragility, unrelated to this PR.  There is an [upstream patch](https://github.com/owickstrom/komposition/pull/101) to pin Komposition's dependencies.

**Comment by EricFromCanada** [comment]
The only failures now are `ffmpeg2theora` and a temporary inability to download `youtube-dl`, so this is probably good to merge as-is.

**Comment by EricFromCanada** [comment]
The only issue now is an inaccessible `ffmpeg2theora` git repo due to some [downtime at xiph.org](https://twitter.com/xiphmont/status/1258160143180726274).

**Comment by issyl0** [comment]
Needs a rebase.

**Comment by EricFromCanada** [comment]
✅ Rebased

**Comment by SMillerDev** [comment]
```
 ==> brew audit --skip-style ffmpeg2theora --online
==> FAILED
Error: 1 problem in 1 formula detected
ffmpeg2theora:
  * HEAD: The URL https://git.xiph.org/ffmpeg2theora.git is not a valid git URL
```

**Comment by EricFromCanada** [comment]
Yes, that's only due to some [downtime at xiph.org](https://twitter.com/xiphmont/status/1258160143180726274). All the Xiph-related formulae are affected.

**Comment by SMillerDev** [comment]
Sure, just reporting the error. If this is the same on all nodes I think we can merge.

**Comment by Bo98** [comment]
Were the various test failures happening before on High Sierra?

```
brew test --verbose ffmpeg
brew test --verbose ffmpeg@2.8
brew test --verbose ffmpegthumbnailer
brew test --verbose libav
brew test --verbose qcli
brew test --verbose vcs
```

**Comment by EricFromCanada** [comment]
@Bo98 Ah… yep. But no longer.

**Comment by Bo98** [comment]
There was a bug in brew that prevented patching from working. Can you rebase?

**Review by bayandin — APPROVED** [review]

**Comment by bayandin** [comment]
Thanks @EricFromCanada 🎉

**Pull request closed without merging**
