### PR TITLE
Update cockroachdb.rb to 1.0.5

### PR DESCRIPTION
**Pull request by jordanlewis**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
We need to wait for 1.0.5 to be designated as the latest stable release here:
https://github.com/cockroachdb/cockroach/releases/latest

**Comment by jordanlewis** [comment]
cc @benesch could you do or delegate this? I'm OOO til Tuesday. Thanks!

**Comment by benesch** [comment]
You bet! Done.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @jordanlewis! For future reference,

>Warning: Nonstandard bump subject: Update cockroachdb.rb to 1.0.5
>Warning: Subject should be: cockroach 1.0.5

**Pull request closed without merging**
