### PR TITLE
ghc 9.0.1

### PR DESCRIPTION
**Pull request by lukel97**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @bubba. You need to update the `binary` resource block.

**Comment by carlocab** [comment]
FYI, you used the wrong URL: https://downloads.haskell.org/~ghc/9.0.1/ghc-9.0.1-x86_64-apple-darwin.tar.xz

The URL you should've used was https://downloads.haskell.org/~ghc/9.0.1/ghc-9.0.1-src.tar.xz

I've fixed that for you.

**Comment by fishtreesugar** [comment]
According to the[ GHC 9.0 migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#integer-gmp-11-integer-simple-ghc-bignum-10):
> ghc-bignum package replaces both integer-gmp and integer-simple.

do we still need to depend on gmp?

**Comment by carlocab** [comment]
I guess not, but we also have the issue of ghc 9.0 not being compatible with Homebrew `cabal-install`: https://www.haskell.org/ghc/download_ghc_9_0_1.html

I think we may need to have a separate `ghc@8.10` formula first, and everything that needs `cabal-install` (which must be all the formulae that use `ghc`...) should depend on that.

**Comment by carlocab** [comment]
@fishtreesugar, is `ghc-bignum` packaged as part of the source tarball? Can we just get rid of the `gmp` resource here?

**Comment by fishtreesugar** [comment]
> is ghc-bignum packaged as part of the source tarball?

Yes.

>  Can we just get rid of the gmp resource here, or would the formula need additional changes?

Maybe we can add a build option to let users decide which bignum backend to use.

reference: https://github.com/ghc/ghc/blob/ghc-9.0/libraries/ghc-bignum/GMP.rst

**Comment by carlocab** [comment]
>Maybe we can add a build option to let users decide which bignum backend to use.

We don't do build options in homebrew/core. We'll have to pick one for the formula.

**Comment by fishtreesugar** [comment]
> We don't do build options in homebrew/core. We'll have to pick one for the formula.

Ok, we can respect ghc's default option (native backend) which did not depend on gmp.

**Comment by carlocab** [comment]
Merged in #70817.

**Pull request closed without merging**
