### PR TITLE
sops 3.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by wi1dcard** [comment]
Hi @chenrui333. Could you please change `depends_on` to `go@1.12` and make the build passed first? Looks like that updating Go 1.13 for sops requires a lot of work on it. They forked `go-yaml` into a new repo named `mozilla-services/yaml` which implemented `Comment` features for sops. Simply changing to `gopkg.org/yaml.v2` won't work.

**Comment by chenrui333** [comment]
yeah, that is good point, I will do that.

**Comment by chenrui333** [comment]
Should be good now. 

Yeah, sops go v1.13 upgrade is not quite straightforward.

**Comment by wi1dcard** [comment]
Thanks for your quick response!

**Comment by chenrui333** [comment]
😄

**Pull request closed without merging**
