### PR TITLE
root 6.22.06

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Testing root
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201127-61854-132o6x3.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/root.rb --verbose
==> /usr/local/Cellar/root/6.22.06/bin/root -b -l -q -e gSystem->LoadAllLibraries(); 0

(int) 0
==> root -l -b -n -q test.C
==> /bin/bash test_compile.bash
==> /usr/local/opt/python@3.9/bin/python3 -c import ROOT; ROOT.gSystem.LoadAllLibraries()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ROOT'
```

**Comment by chenrui333** [comment]
test out fine on my 10.14 machine locally

```
==> Testing root
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201127-49306-1p1v224.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/root.rb --debug --verbose
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/root.rb
==> /usr/local/Cellar/root/6.22.06/bin/root -b -l -q -e gSystem->LoadAllLibraries(); 0

(int) 0
==> root -l -b -n -q test.C
==> /bin/bash test_compile.bash
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb
==> /usr/local/opt/python@3.9/bin/python3 -c import ROOT; ROOT.gSystem.LoadAllLibraries()
NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
```

**Comment by henryiii** [comment]
Is this a problem on ROOT's side or homebrew's side? Sounds a little (maybe also from #65840) that this might be on homebrew's side?

**Comment by SMillerDev** [comment]
```
==> /usr/local/opt/python@3.9/bin/python3 -c import ROOT; ROOT.gSystem.LoadAllLibraries()
```
This fails because it can't find ROOT. I'm not sure if that changed between the last versions, but I'd guess it's a code change that the install didn't adapt to yet.

**Comment by henryiii** [comment]
@chenrui333 Could you give me access to your branch in your fork? I'll have some time to debug this tomorrow.

**Comment by henryiii** [comment]
Should I open up a new PR for debugging? Actually, if I PR to my own repo, maybe the actions will run and I can debug that way, and then I can suggest whatever I find.

**Comment by henryiii** [comment]
I can reproduce this locally on 10.15! Don't need CI now, at least for the 10.15 problem. :)

**Comment by henryiii** [comment]
Found the problem with finding root, at least fixing 10.15 and 11.0. Before, everything was in `/usr/local/Cellar/root/6.22.04/lib/root`; now everything is in `/usr/local/Cellar/root/6.22.06/lib`, there is a folder called ROOT in that with `__init__.py` in it, which is why the directory exists, but doesn't really do anything when added using the .pth file. I'm checking with the ROOT team to see if this was intentional - it's a big reordering for a patch release, especially after they assured me that nothing significant was supposed to change with the install. :)

**Comment by henryiii** [comment]
It should not be dumping everything in `/lib`, it should be in `/lib/root` due to the way home-brew links. I've verified by building 6.22.04 (with the GitHub tarball, since the release was pulled) that it now does this too, so it's a change in Home-brew, not ROOT. I've also rebuilt the CMake formula with 3.18 and retried, with the same result, so it's not due to a CMake update. Has possibly a variable been removed or added that might affect a gnu style install?

**Comment by henryiii** [comment]
Found the bug with the help from members of the ROOT team, @oshadura and @amadio ! The problem is [this line in homebrew](https://github.com/Homebrew/brew/blob/2c77a540b522c2eee74af0745851167412adb83b/Library/Homebrew/formula.rb#L1412), which was added [here](https://github.com/Homebrew/brew/commit/7d8f6d9d227764f1e93bc2736e529a8fbe8f4aaf). The libdir is now specified (but not all the other GNU paths?), so this breaks ROOT.

There are two options.

1. We can specify this back to what we want it to be, `/lib/root`. This will recover the old behavior, where ROOT lives in a nested folder, `/lib/root/stuff`.
2. Or, we can remove `gnuinstall=ON` (OFF is the default), and then ROOT will install itself into un-nested `/lib` and such. The problem is it is _huge_, and has a lot of commonly named files, like libMath.so and RConfig.h (colliding with at least R), so this doesn't live as nicely with other packages when it is OFF. But it is more "standard".

Thoughts?

**Comment by henryiii** [comment]
@chenrui333 I still can't edit your branch, so my recommendation is:

Add:
```
-DCMAKE_INSTALL_LIBDIR=lib/root
```

to the cmake line. Put a comment like this above the place these get set:

```ruby
# Homebrew now sets CMAKE_INSTALL_LIBDIR to /lib, which is incorrect
# for ROOT with gnuinstall, so we set it back here.
```

I bet they set it to avoid it being set to lib64. Technically, ROOT maybe should install to `CMAKE_INSTALL_LIBDIR/root` in gnuinstall mode, as these variables are supposed to be set to the lib, not lib + something, I think. Anyway, this should unblock this PR.

**Comment by chenrui333** [comment]
I will give this a shot.

**Comment by chenrui333** [comment]
@henryiii also, you should be all set with permissions to my branch. :)

**Comment by henryiii** [comment]
Thanks, though hopefully this will Just Work™, and I won't need to debug further. :)

**Review by SMillerDev — APPROVED** [review]
Thanks @chenrui333 and @henryiii  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
