### PR TITLE
mahout 0.12.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Why the move away from `dyn` here?

**Comment by ilovezfs** [comment]
@DomT4 the dyn url didn't seem to work at all when I tried it. Does it work for you?

**Comment by DomT4** [comment]
Seems to, yeah. Maybe some of the mirrors hadn't been updated yet or something.

**Comment by ilovezfs** [comment]
```
```

**Comment by ilovezfs** [comment]
Josephs-MacBook-Pro:~ joe$ wget 'https://www.apache.org/dyn/closer.cgi?path=mahout/0.12.2/apache-mahout-distribution-0.12.2.tar.gz'
--2016-06-24 11:24:43--  https://www.apache.org/dyn/closer.cgi?path=mahout/0.12.2/apache-mahout-distribution-0.12.2.tar.gz
Resolving www.apache.org... 140.211.11.105, 88.198.26.2, 2a01:4f8:130:2192::2
Connecting to www.apache.org|140.211.11.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘closer.cgi?path=mahout%2F0.12.2%2Fapache-mahout-distribution-0.12.2.tar.gz’

closer.cgi?path=mah     [ <=>                ]  22.64K  --.-KB/s    in 0.05s   

2016-06-24 11:24:43 (416 KB/s) - ‘closer.cgi?path=mahout%2F0.12.2%2Fapache-mahout-distribution-0.12.2.tar.gz’ saved [23187]

Josephs-MacBook-Pro:~ joe$ sha256 closer.cgi\?path\=mahout%2F0.12.2%2Fapache-mahout-distribution-0.12.2.tar.gz 
SHA256(closer.cgi?path=mahout%2F0.12.2%2Fapache-mahout-distribution-0.12.2.tar.gz)= b82762065db3ec36a02da3bebb8fb19570d1bb3fdeeeeec172b46ab2807501d6
```
Am I doing something wrong?

**Comment by DomT4** [comment]
It doesn't work directly over `wget`. Apache mirrors are actually really weird things which require [a blob of special handling](https://github.com/Homebrew/brew/blob/5e272257d288d751d936624767d4613dde7ff452/Library/Homebrew/download_strategy.rb#L369-L405).

**Comment by DomT4** [comment]
Does work though, inside our special handling:

```
~> brew fetch mahout -s -v
==> Downloading https://www.apache.org/dyn/closer.cgi?path=mahout/0.12.2/apache-mahout-distribution-0.12.2.tar.gz
==> Best Mirror http://apache.mirror1.spango.com/mahout/0.12.2/apache-mahout-distribution-0.12.2.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 http://apache.mirror1.spango.com/mahout/0.12.2/apache-mahout-distribution-0.12.2.tar.gz -C 0 -o /usr/local/var/homebrew/cache/mahout-0.12.2.tar.gz.incomplete --connect-timeout 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  223M  100  223M    0     0  13.3M      0  0:00:16  0:00:16 --:--:-- 16.5M
Downloaded to: /usr/local/var/homebrew/cache/mahout-0.12.2.tar.gz
SHA256: 8e9d9fb04c6f1cfc11932a8cf268dea87460ffdd50aa0355db7cd470d0420946
==> Verifying mahout-0.12.2.tar.gz checksum
```

**Comment by ilovezfs** [comment]
ew

**Comment by DomT4** [comment]
They win points for being one of the most complicated mirroring systems I've ever seen, that's for sure.

**Comment by ilovezfs** [comment]
@DomT4 Should I put "https://archive.apache.org/dist/mahout/0.12.2/apache-mahout-distribution-0.12.2.tar.gz" in as a mirror or just use the dyn url?

**Comment by DomT4** [comment]
It _should_ fall back automatically if the `dyn` mirror ever borks for some reason. Theoretically, at least. Let's stick to `dyn` solely for now.

**Pull request closed without merging**
