### PR TITLE
mercurial: --with-custom-python can be a no-op

### PR DESCRIPTION
**Pull request by tdsmith**
... without changing its behavior.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍 but I'm wondering why we want to allow people to use a system Python for an application?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@MikeMcQuaid does this require bottle update? (and thus a revision bump)

**Comment by ilovezfs** [comment]
No. :python resolves to "python" when bottling

**Pull request merged**
