### PR TITLE
manim 0.17.2 (new formula)

### PR DESCRIPTION
**Pull request by unitof**
Work in progress

Inspired by wanting to add `git-sim` today, which requires manim as a dependency

NOTE: this is the Community Edition, which is a fork of Grant Sanderson (3blue1brown)'s [original](https://github.com/3b1b/manim). It is the best-maintained and [recommended](https://github.com/ManimCommunity/manim#readme) fork for new manim animations.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by unitof** [comment]
Is it possible to let the builds run for all platforms, rather than cancelling when 12-arm64 fails? It is building fine for me locally on 13-arm64 so would like to see if it does on Brew's runners.

The py package that's failing to build into a wheel is `ManimPango`, maintained by the same upstream as this project. They actually [pinned their own builder to macOS 11](https://github.com/ManimCommunity/ManimPango/commit/a960fd4d191bb3df5f6ccbd715757ada673ab83f), citing build issues.

**Comment by chenrui333** [comment]
should build for all platforms now.

**Comment by chenrui333** [comment]
> The py package that's failing to build into a wheel is `ManimPango`, maintained by the same upstream as this project. They actually [pinned their own builder to macOS 11](https://github.com/ManimCommunity/ManimPango/commit/a960fd4d191bb3df5f6ccbd715757ada673ab83f), citing build issues.

that is not a good idea. (can you raise an issue asking the upstream about it?)

**Comment by unitof** [comment]
Hm, even 13-arm64 (same as my development machine) fails with [same error](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1857):

```
running build_ext
[1848](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1849)
    building 'manimpango.cmanimpango' extension
[1849](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1850)
    creating build/temp.macosx-13-arm64-cpython-311
[1850](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1851)
    creating build/temp.macosx-13-arm64-cpython-311/private
[1851](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1852)
    creating build/temp.macosx-13-arm64-cpython-311/private/tmp
[1852](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1853)
    creating build/temp.macosx-13-arm64-cpython-311/private/tmp/manim--ManimPango-20230317-29272-19jp9vy
[1853](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1854)
    creating build/temp.macosx-13-arm64-cpython-311/private/tmp/manim--ManimPango-20230317-29272-19jp9vy/ManimPango-0.4.3
[1854](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1855)
    creating build/temp.macosx-13-arm64-cpython-311/private/tmp/manim--ManimPango-20230317-29272-19jp9vy/ManimPango-0.4.3/manimpango
[1855](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1856)
    clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/Cellar/manim/0.17.2/libexec/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /private/tmp/manim--ManimPango-20230317-29272-19jp9vy/ManimPango-0.4.3/manimpango/cmanimpango.c -o build/temp.macosx-13-arm64-cpython-311/private/tmp/manim--ManimPango-20230317-29272-19jp9vy/ManimPango-0.4.3/manimpango/cmanimpango.o
[1856](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1857)
    /private/tmp/manim--ManimPango-20230317-29272-19jp9vy/ManimPango-0.4.3/manimpango/cmanimpango.c:767:10: fatal error: 'cairo.h' file not found
[1857](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1858)
    #include "cairo.h"
[1858](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1859)
             ^~~~~~~~~
[1859](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1860)
    1 error generated.
[1860](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1861)
    error: command '/opt/homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
[1861](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1862)
    error: subprocess-exited-with-error
[1862](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1863)
    
[1863](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1864)
    × Building wheel for ManimPango (pyproject.toml) did not run successfully.
[1864](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1865)
    │ exit code: 1
[1865](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1866)
    ╰─> See above for output.
[1866](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1867)
    
[1867](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1868)
    note: This error originates from a subprocess, and is likely not a problem with pip.
[1868](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1869)
    full command: /opt/homebrew/Cellar/manim/0.17.2/libexec/bin/python3.11 /opt/homebrew/Cellar/manim/0.17.2/libexec/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /private/tmp/tmppn0pnew6
[1869](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1870)
    cwd: /private/tmp/manim--ManimPango-20230317-29272-19jp9vy/ManimPango-0.4.3
[1870](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1871)
    Building wheel for ManimPango (pyproject.toml): finished with status 'error'
[1871](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1872)
    ERROR: Failed building wheel for ManimPango
[1872](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1873)
  Failed to build ManimPango
[1873](https://github.com/Homebrew/homebrew-core/actions/runs/4390697399/jobs/7819608097?pr=121408#step:7:1874)
  ERROR: Could not build wheels for ManimPango, which is required to install pyproject.toml-based projects
```

Yes I'll dig back in, and ask up stream if needed. Reverting back to draft until I have a fix.

**Comment by chenrui333** [comment]
Sounds good, thanks @unitof!

**Pull request closed without merging**
