### PR TITLE
sourcery 0.12.0

### PR DESCRIPTION
**Pull request by ilyapuchka**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
Needs Xcode 9.3

**Comment by commitay** [comment]
@BrewTestBot test this please

**Comment by commitay** [comment]
```
==> swift build --disable-sandbox -c release -Xswiftc -static-stdlib
Compile CYaml src/writer.c
Compile CYaml src/scanner.c
Compile CYaml src/reader.c
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
       ^
/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
1 error generated.
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
       ^
/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
       ^
/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
warning: dependency 'Stencil' is not used by any target
warning: dependency 'AEXML' is not used by any target
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /private/tmp/sourcery-20180413-13363-b60m1u/Sourcery-0.12.0/.build/release.yaml main output:
```

**Comment by ilyapuchka** [comment]
no idea, builds without errors on my machine running 10.13.4

**Comment by ilovezfs** [comment]
This needs to be fixed in https://github.com/Homebrew/brew because we don't want to manipulate brew internals in formulae.

**Comment by ilyapuchka** [comment]
@commitay any feedback on that?

**Comment by ilyapuchka** [comment]
This is currently blocking new release
@ilovezfs any update on the fix?

**Comment by mistydemeo** [comment]
This error seems to be fixed as of Xcode 9.4, so we should be good once we have the build bots updated.

**Comment by yonaskolb** [comment]
This is still present in Xcode 9.4, as mentioned here https://github.com/Homebrew/brew/pull/4147

**Comment by ilovezfs** [comment]
Thanks @ilyapuchka! I went with the minimal hack
```
ENV["CC"] = Utils.popen_read("xcrun -find clang").chomp
```

until we get a response from Apple on rdar://40724445

**Pull request closed without merging**
