### PR TITLE
lazydocker 0.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for yet another PR but literally 1/4 PRs in homebrew-core is yours. Could you please first close or resolve any existing ones before creating new ones? The current flow is very taxing on maintainers (or at least on me) and you're at this point slowing down the repo more than you're helping it.

**Comment by chenrui333** [comment]
@SMillerDev, I can be more proactive in closing the PRs that I cannot resolve and let the repo maintainers to deal with the upgrade issue.

yeah, I do think keeping the homebrew up to date is really taxing. But that does not prevent me from pushing this further forward. 

Happy to chat privately on this. Really appreciate your understanding.

**Comment by SMillerDev** [comment]
>  I can be more proactive in closing the PRs that I cannot resolve

That'd be a good first step

> yeah, I do think keeping the homebrew up to date is really taxing. But that does not prevent me from pushing this further forward.

There is a point where you're actually doing the opposite by just throwing more work at a thinly stretched group. It's only keeping things up-to-date if people have time to actually merge your flood of PRs.
In addition to this there used to be an argument for removing outdated software that people clearly didn't care for. And that doesn't work if all software is updated regardless of usage by people.

**Comment by chenrui333** [comment]
> That'd be a good first step

I am doing the active cleanup right now.

> And that doesn't work if all software is updated regardless of usage by people.

That sounds very true, actually, I think many formula might be only used by handful people.

**Pull request closed without merging**
