### PR TITLE
itk 5.0.1

### PR DESCRIPTION
**Pull request by dawidd6**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/linuxbrew-core/issues/16902

Previous effort: https://github.com/Homebrew/homebrew-core/pull/42236

### CODE REVIEW

**Comment by dawidd6** [comment]
```
/usr/local/Cellar/itk/5.0.1/include/ITK-5.0/itkMacro.h:166:6: error: "Apple LLVM < 5.0 (clang < 3.3) is not supported under ITKv5"
    #error "Apple LLVM < 5.0 (clang < 3.3) is not supported under ITKv5"
```

**Comment by jonchang** [comment]
That error message doesn't make sense.

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkMacro.h#L165-L168

Is clang being called with `-std=c++11`?

**Comment by jonchang** [comment]
Really odd, This should be setting `-std=c++11` properly...

https://github.com/InsightSoftwareConsortium/ITK/blob/3a17dfd2874d66b85a28e88ddfcc655dcb8f65f5/CMakeLists.txt#L45-L47

**Comment by dawidd6** [comment]
Yep, dunno really what is wrong, just trying to fix it by trial and error. I would appreciate any help on this.

**Comment by jonchang** [comment]
If this doesn't work, try adding `-std=c++11` to these calls to `ENV.cxx` (clang) in the test block:

```
system ENV.cxx, "-isystem", "#{include}/ITK-#{v}", "-o", "test.cxx.o", "-c", "test.cxx"

system ENV.cxx, "test.cxx.o", "-o", "test",
```

**Pull request closed without merging**
