### PR TITLE
pngcrush 1.8.11

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Does this not have `make install`?

**Comment by neutric** [comment]
It doesn't.

**Comment by neutric** [comment]
Tweaked the update a bit. Changed source to *.tar.xz since it is more compact. The option `-cc` was removed in v1.8.0.

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
