### PR TITLE
mercurial 6.4.2

### PR DESCRIPTION
**Pull request by chuanchan1116**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  chg.c:535:40: error: use of undeclared identifier 'environ'; did you mean 'union'?
                  hgc_setenv(hgc, (const char *const *)environ);
                                                       ^~~~~~~
                                                       union
  chg.c:535:40: error: address of overloaded function 'environ' does not match required type 'const char *'
                  hgc_setenv(hgc, (const char *const *)environ);
                                                       ^~~~~~~
  2 errors generated.
```

same as 6.4.1

**Comment by cho-m** [comment]
Upstream issue: https://bz.mercurial-scm.org/show_bug.cgi?id=6812

Info on `environ`: 
- https://www.gnu.org/software/gnulib/manual/html_node/environ.html
- https://pubs.opengroup.org/onlinepubs/9699919799/functions/environ.html

**Comment by carlocab** [comment]
Ok, the patch in the linked issue works, except dependent testing fails with
```
  ==> Fetching mercurial
  ==> Pouring mercurial--6.4.2.arm64_monterey.bottle.tar.gz
  ==> Skipping 'post_install' on request
  You can run it manually using:
    brew postinstall mercurial
  Error: No such file or directory - /opt/homebrew/opt/mercurial/bin/hg
```
Not sure what that's about. @Homebrew/brew?

**Comment by MikeMcQuaid** [comment]
> Not sure what that's about. @Homebrew/brew?

Sounds like skipping post install is making not creating the opt link properly?

**Comment by cho-m** [comment]
Superseded by #135756 / #135950.

Issue was `caveats` were failure due to `python@3.11` not being installed when we try to run `hg` (error message is a bit odd as it is failing on use shebang). Added a workaround in `mercurial` formula.

**Pull request closed without merging**
