### PR TITLE
wasmer 0.12.0 (new formula)

### PR DESCRIPTION
**Pull request by Hywan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR creates a new formula for [Wasmer, a WebAssembly runtime](https://github.com/wasmerio/wasmer).

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you remove the test comment and check for some output in the test?

**Comment by Hywan** [comment]
Yeah I can!

**Comment by Hywan** [comment]
Done.

**Comment by SMillerDev** [comment]
Can you squash the commits?

**Comment by Hywan** [comment]
Done!

**Comment by chenrui333** [comment]
Thanks @Hywan for your contribution to Homebrew! :tada: 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
