### PR TITLE
Solidity 0.8.17

### PR DESCRIPTION
**Pull request by matheusaaguiar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Not sure why Linux only is failing to build.

**Comment by danielnachun** [comment]
`boost` needs to be rebuilt in Ubuntu 22.04 so that it is build with `-fPIE`/`-fPIC`.  This will happen when https://github.com/Homebrew/homebrew-core/pull/109752.

**Comment by matheusaaguiar** [comment]
Please, let me know if there is anything I can do to help get this merged. Thanks!

**Review by carlocab — APPROVED** [review]
Linux installs for this formula make up 0.8% of all installs in the past year. (See analytics data [here](https://formulae.brew.sh/formula/solidity#default).)

It looks like #109752 has stalled. Instead of delaying this update for such a small proportion of users, I suggest merging this now and building the Linux bottle later when we have a working version of Boost.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
