### PR TITLE
gpg-agent Add launchd plist file

### PR DESCRIPTION
**Pull request by gjasny**

### CODE REVIEW

**Comment by gjasny** [comment]
Need to teach launchd that the agent double-forks in daemon mode.

**Comment by MikeMcQuaid** [comment]
You can push changes to this PR instead of opening a new one.

**Comment by gjasny** [comment]
Oh boy. After reading through [Macports #43584](https://trac.macports.org/ticket/43584) I came to the conclusion that it might be easier to use some shell magic like the [zsh gpg-plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gpg-agent).

**Comment by MikeMcQuaid** [comment]
@gjasny Whatever you think is best. Feel free to close if you're no longer interested in making a PR here. Thanks either way!

**Comment by chdiza** [comment]
I don't see the reason for this.  The agent starts on demand and stays active.

**Comment by fxcoudert** [comment]
There seems to be general consensus that this PR is not needed. Closing accordingly.

**Pull request closed without merging**
