### PR TITLE
llvm 4.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by aw1621107** [comment]
Can't wait to see how many formulae this will break!

Also, is lld officially the default linker for clang now? If so, how badly might that mess with homebrew?

**Comment by AraHaan** [comment]
love how this somehow fails.

**Comment by ilovezfs** [comment]
@AraHaan that's expected with creduce. I haven't even done the revision bumps yet, which when it really starts to break.

**Comment by fxcoudert** [comment]
- `creduce` will release a new version that works with llvm 4.0.0: https://github.com/csmith-project/creduce/issues/129
- `ldc` fixed in master: https://github.com/ldc-developers/ldc/issues/2000
- `nvc` fixed in master: https://github.com/nickg/nvc/issues/313
- `ponyc` not fixed: https://github.com/ponylang/ponyc/issues/1592

**Comment by ilovezfs** [comment]
@fxcoudert yeah. already dealt with locally ;)

**Review by ilovezfs — COMMENTED** [review]
```
==> FAILED
Error: 1 problem in 1 formula
llvm@3.9:
  * `head block` (line 78) should be put before `keg_only` (line 76)
```

**Review by MikeMcQuaid — APPROVED** [review]

**Review by AraHaan — APPROVED** [review]

**Review by ilovezfs — COMMENTED** [review]
I've removed the llvm@3.9 formula since ponyc can use the preexisting llvm@3.8 formula.

**Comment by ilovezfs** [comment]
Shipped without the nvc bump, which I'll do in a separate PR.

**Comment by ilovezfs** [comment]
nvc https://github.com/Homebrew/homebrew-core/pull/11088

**Comment by AraHaan** [comment]
but what about having homebrew install 4.0.0?

**Pull request closed without merging**
