### PR TITLE
node 15.9.0

### PR DESCRIPTION
**Pull request by beyera**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

npm updated in this release: 

image

### CODE REVIEW

**Review by approached — APPROVED** [review]
👍

**Review by derrabus — APPROVED** [review]

**Comment by matinzd** [comment]
👍

**Comment by mvanaltvorst** [comment]
I'd love for this to get merged, is there a way to manually install the latest node until this happens? Fixes a bug I've been having to work around all day

**Review by bayandin — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Thanks very much, @beyera.

**Comment by justaashir** [comment]
Working fine now. Thanks. Installed from nvm like this:
 - nvm install node --reinstall-packages-from=node

Using M1 Macbook Pro

**Pull request closed without merging**
