### PR TITLE
Point `openssl@3` to `openssl@3.0`.

### PR DESCRIPTION
**Pull request by oraluben**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Per https://github.com/openssl/openssl/pull/20948#issuecomment-1549359739, OpenSSL does not plan to fix the debugging error on darwin-aarch64, this might affect users that building and debugging from source against brew-installed `openssl@3` on that platform. Cases can be found at https://github.com/openssl/openssl/issues/20188.

OpenSSL 3.0 is LTS and won't be affected (troublesome commits won't be cherry-picked); 3.1 won't be fixed. Further plan is unclear to all of us now.
So I think setting default version to 3.0 is a proper way to prevent most of user from the failure.

### CODE REVIEW

**Comment by oraluben** [comment]
cc @ZhongRuoyu maybe?

**Comment by ZhongRuoyu** [comment]
This is a major change that may potentially impact a great number of users ([stats](https://formulae.brew.sh/formula/openssl@3)). I am not certain if the switch is worth it, as (to my knowledge) we have not received any bug reports regarding the debugging error that you mentioned.

> this might affect users that building and debugging from source against brew-installed `openssl@3` on that platform

I'd consider it a better option to only switch the affected dependents to `openssl@3.0` (if any). And `openssl@3` users affected by this bug can choose to build their programs against `openssl@3.0`.

> 3.1 won't be fixed. Further plan is unclear to all of us now. So I think setting default version to 3.0 is a proper way to prevent most of user from the failure.

`openssl@3` is not pinned at 3.1, so it will be upgraded to 3.2.0 when it's available.

**Comment by Porkepix** [comment]
Isn't the whole 3.x a LTS? I thought it was the point of their change in versioning. AIn any case, not fixing affected versions while they're not EOL seems strange…

**Comment by ZhongRuoyu** [comment]
> Isn't the whole 3.x a LTS?

It doesn't seem like it: https://www.openssl.org/policies/releasestrat.html

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
We can't downgrade `openssl@3` for multiple reasons:
- people won't be updated to that version with `brew upgrade`, only `brew reinstall`
- people/formulae may already be relying on `openssl@3.1` features that we will break
- this debugging issue isn't breaking things in a widespread enough fashion to override the above (e.g. I am on an M1 machine and have no issues with OpenSSL 3.1 usage)

If there ends up being a patch we can back port to fix this issue: we should consider that.

**Comment by oraluben** [comment]
> We can't downgrade `openssl@3` for multiple reasons:
> 
> * people won't be updated to that version with `brew upgrade`, only `brew reinstall`
> * people/formulae may already be relying on `openssl@3.1` features that we will break
> * this debugging issue isn't breaking things in a widespread enough fashion to override the above (e.g. I am on an M1 machine and have no issues with OpenSSL 3.1 usage)

Thanks for the explanation!

> If there ends up being a patch we can back port to fix this issue: we should consider that.

Yes, that might be a better idea. Upstream patch: https://github.com/openssl/openssl/commit/52a38144b019cfda6b0e5eaa0aca88ae11661a26

**Pull request closed without merging**
