### PR TITLE
openjdk 20.0.2

### PR DESCRIPTION
**Pull request by ik11235**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Okay, let's try again

**Comment by ik11235** [comment]
Is there anything I can do?

From the error message, it seems that CI is failing due to an error unrelated to openjdk.
I do not have the authority to manipulate CI, so I would like to ask a contributor to help me.

**Comment by SMillerDev** [comment]
Someone should fix and resolve the issues. No need to modify CI.

**Comment by trinitronx** [comment]
> Is there anything I can do?
> 
> From the error message, it seems that CI is failing due to an error unrelated to openjdk. I do not have the authority to manipulate CI, so I would like to ask a contributor to help me.

Please could someone add label: `help wanted`
Thanks!

**Comment by Moisan** [comment]
`kafka` is currently failing with the same error as https://github.com/Homebrew/homebrew-core/pull/133887.

**Comment by ZhongRuoyu** [comment]
Now that #133887 is merged, let's give this another spin.

**Comment by ZhongRuoyu** [comment]
Ah, @branchvincent beat me to it 😄

**Comment by branchvincent** [comment]
Great timing! 😏

**Comment by ZhongRuoyu** [comment]
## Source build failures

- [ ] `carrot2` (`digital envelope routines::unsupported`; [logs](https://github.com/Homebrew/homebrew-core/actions/runs/6062268848/job/16448724221?pr=137124#step:3:1206))
- [ ] `libreadline-java` (`TypeError: Parameter 'new_value': Expected type T.any(Pathname, String), got type Version with value #<Version:0x0000000126aefc5...0.2", @detected_from_url=true>`; [logs](https://github.com/Homebrew/homebrew-core/actions/runs/6062268848/job/16448724221?pr=137124#step:3:2925))
- [ ] `mercury` (`make[2]: *** [libmer_browser.install_ints] Error 1`; download 12-arm64 logs to check) (could be race condition)
- [ ] `nesc` (`-Wimplicit-function-declaration`; [logs](https://github.com/Homebrew/homebrew-core/actions/runs/6062268848/job/16448724221?pr=137124#step:3:3342))
- [ ] `opensearch` (`error: StandaloneRestIntegTestTask is not abstract and does not override abstract method getDryRun() in Test`; [logs](https://github.com/Homebrew/homebrew-core/actions/runs/6062268848/job/16448724221?pr=137124#step:3:3585))

## `brew fetch` failures

- [ ] `apache-opennlp` (source unavailable)
- [ ] `davmail` (source unavailable)
- [ ] `jolie` (checksum change)
- [x] `spring-loaded` (401 unauthorized): #141326

## `brew test` failures

- [ ] `selenium-server` (pre-existing; see #128950)
- [ ] `trino` (pre-existing; see #131903)

**Review by ZhongRuoyu — APPROVED** [review]
Given none of the failures seem related: I think it's fine to merge this.

**Pull request merged**
