### PR TITLE
Bump pip to 9.0.3

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
no revision bumps are needed

**Comment by alex** [comment]
@ilovezfs would you like me to remove the revision bumps?

**Comment by ilovezfs** [comment]
Yes please. The bottle names hard code the (version, revision, rebuild) tuplet so it can't be fixed post CI.

**Comment by alex** [comment]
Done!

**Comment by ilovezfs** [comment]
@DomT4 it seems pypy3 needs to moved from the nice list to the naughty list
```
fetching archive http://ftp.gnu.org/gnu/gdbm/gdbm-1.13.tar.gz
unpacking archive /tmp/pypy-archives/gdbm-1.13.tar.gz
configuring /private/tmp/pypy3-20180317-90175-17apt75/pypy3-v5.10.1-src/pypy/tool/dest/gdbm-1.13
building /private/tmp/pypy3-20180317-90175-17apt75/pypy3-v5.10.1-src/pypy/tool/dest/gdbm-1.13
* _ssl_build.py
fetching archive http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.2.tar.gz
unpacking archive /tmp/pypy-archives/libressl-2.6.2.tar.gz
applying patch /private/tmp/pypy3-20180317-90175-17apt75/pypy3-v5.10.1-src/pypy/tool/../../lib_pypy/_cffi_ssl/osx-roots.diff
configuring /private/tmp/pypy3-20180317-90175-17apt75/pypy3-v5.10.1-src/pypy/tool/dest/libressl-2.6.2
building /private/tmp/pypy3-20180317-90175-17apt75/pypy3-v5.10.1-src/pypy/tool/dest/libressl-2.6.2
* _audioop_build.py
* _curses_build.py
* _lzma_build.py
fetching archive https://tukaani.org/xz/xz-5.2.3.tar.gz
Traceback (most recent call last):
```

http ... um

**Comment by ilovezfs** [comment]
@lembacon I believe the pypy bottle jobs are failing due to the pycache commit.

**Comment by ilovezfs** [comment]
Hopefully fixed via https://github.com/Homebrew/brew/pull/3946.

@BrewTestBot test this please

**Comment by DomT4** [comment]
> it seems pypy3 needs to moved from the nice list to the naughty list

😒 😭. Maybe we can discourage that behaviour somehow. Or at least `inreplace` the usage of `http`. Something less hideous. Anything less hideous.

**Comment by alex** [comment]
This ought to be switched to pip 9.0.3. I won't have time to do dive into why there are failing tests here for a while.

Would submitting a more minimal PR that just covers the python formula be ok? That should cover the majority of users.

**Comment by ilovezfs** [comment]
@alex sure. Just chuck out pypy3

**Comment by alex** [comment]
Ah, if that's really the only one having trouble I'll just remove that commit. Thanks

**Comment by alex** [comment]
Test failure here doens't look related to this PR?

**Comment by ilovezfs** [comment]
fixed in https://github.com/Homebrew/homebrew-test-bot/commit/beba5b2cf0f20f1cc249debce78725575a9c39f9

**Comment by alex** [comment]
:+1:

**Comment by ilovezfs** [comment]
Thanks @alex! Shipped.

**Pull request closed without merging**
