### PR TITLE
mingw-w64 6.0.0

### PR DESCRIPTION
**Pull request by theli-ua**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by theli-ua** [comment]
Not sure why jenkins build fails, succeeded here :-/

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
@theli-ua Can I see the `brew config` you built this with locally?

@fxcoudert Any idea/thoughts about the test issues on High Sierra/Mojave (as this "kinda" GCC)? My guess is there's something with i686 support there but when I removed the i686 testing it still failed for me locally. Feels like a header or two may need tweaked for Xcode 10 compat.

**Comment by theli-ua** [comment]
```
~ brew config
HOMEBREW_VERSION: 1.9.2-5-g44f4f36
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 44f4f36c0db693000410fe664b250a90325f4e32
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: de1ecc1d981de9d5165ea9e96242c32023d14d7c
Core tap last commit: 9 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/romanton/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.13.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
@theli-ua That matches what we see in CI where this doesn't work on 10.13/14.

**Pull request closed without merging**
