### PR TITLE
exiftool 12.00

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by samford** [comment]
```
==> brew install --verbose --build-bottle exiftool
==> FAILED

...

Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
exiftool:
  expected replacement of "$exeDir/lib" with #<Pathname:/usr/local/Cellar/exiftool/12.00/libexec/lib>
```

`$exeDir/lib` doesn't exist in the `exiftool` file anymore, so the `inreplace` either isn't necessary anymore or needs to be updated in some way.

**Comment by samford** [comment]
Looks like the `inreplace` needs to be updated to the following:

```
    inreplace "exiftool", "$1/lib", libexec/"lib"
```

**Comment by SeekingMeaning** [comment]
Looks like CI needs to be re-triggered for this

**Review by SMillerDev — DISMISSED** [review]

**Review by jonchang — DISMISSED** [review]
Let's try that again

**Comment by samford** [comment]
Let's see if setting off a new build helps.

**Review by samford — APPROVED** [review]

**Pull request closed without merging**
