### PR TITLE
arduino-cli: fix ldflags

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fix for changes made here: #56884

### CODE REVIEW

**Comment by SConaway** [comment]
@dawidd6 May I ask what this changes?

I'm seeing no change in the `go build` command (`go build -ldflags -s -w -X github.com/arduino/arduino-cli/version.versionString=0.11.0 -X github.com/arduino/arduino-cli/version.commit=0296f4df116385f868b67c5ffa7393936c3345c9` vs ` go build -ldflags -s -w -X github.com/arduino/arduino-cli/version.versionString=0.11.0 -X github.com/arduino/arduino-cli/version.commit=0296f4df116385f868b67c5ffa7393936c3345c9`). But it makes versioning work.

**Comment by dawidd6** [comment]
Sure. This changes one thing. Whole ldflags argument is now passed as one single parameter to the shell. Like for example:

Before:
```
go build -ldflags -s -w
```

After:
```
go build -ldflags "-s -w"
```

**Comment by SConaway** [comment]
So it tells `ruby`, essentially to separate each item with a ` ` in between. This causes it to be wrapped in quotes then?

I'm just curious, since i know no `ruby` at all.

**Comment by dawidd6** [comment]
Yep, basically that.

**Comment by SConaway** [comment]
Cool, thanks.

**Pull request closed without merging**
