### PR TITLE
packer: install zsh completion

### PR DESCRIPTION
**Pull request by itiut**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by apjanke** [comment]
This should include a revision bump since it changes the set of files that are installed. Just add `revision 1` after the `url` line.

**Comment by itiut** [comment]
Added `revision 1`.

**Comment by mikemcquaid** [comment]
@apjanke I don't think that's the case if it's not e.g. fixing a user-facing bug and it requires a rebuilding from source for some users. That said, I'll just pull this case as-is.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
