### PR TITLE
boost, boost-python 1.61.0

### PR DESCRIPTION
**Pull request by afh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Timed out but looks like a bunch of stuff will need `revision` bumps.

**Comment by afh** [comment]
What's the best strategy to move forward?

**Comment by mikemcquaid** [comment]
One of us will bump the timeout for this when CI is quiet and then we can get to work on adding `revision`s.

**Comment by afh** [comment]
Great! Please do let me know if I can help out with updating `revision`s on affected formulae.

**Comment by UniqMartin** [comment]
@afh [A complete test bot run has just finished](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2084/) with the expected failures. You can now start addressing them by bumping the `revision`s of affected formulae. Add those revision bumps as individual commits with a commit message `<formula>: revision for boost` (or `boost-python`). Checking out what was done for the last Boost version bump also might come in handy: Homebrew/legacy-homebrew#47125.

**Comment by tdsmith** [comment]
We can't count on test-bot failures; everything that declares a runtime boost dependency should be bumped (across taps, as well).

**Comment by afh** [comment]
Alright I'll do that. Do you prefer the revision of the formula to bumped or of the bottle?

**Comment by UniqMartin** [comment]
> Do you prefer the revision of the formula to bumped or of the bottle?

It's the `revision` of the formula that needs to be bumped. The bottle revisions are completely and automatically managed by our CI and aren't supposed to be touched by humans (this also applies to the rest of the `bottle do` block).

Sorry for the confusion! We plan on improving this in Homebrew/brew#38.

**Comment by afh** [comment]
Thanks for the heads-up. I've updated the formulae accordingly and have included the boost 1.61.0 update for boost-bcp.

**Comment by UniqMartin** [comment]
Thanks! I just aborted the build, bumped the CI timeout, and re-queued the build. Let's see how that goes …

**Comment by UniqMartin** [comment]
@afh Build finished without exceeding the time limit and was almost successful. Can you look into the remaining build failures?

**Comment by afh** [comment]
* I've updated the `uhd` formula to 003.009.004 and would like @BrewTestBot to test this version on mavericks.

* `folly` fails since as of boost 1.61.0 the `fcontext_t` is no longer part of the public API, it seems there are upstream changes necessary and a patch/commit is currently missing (see [folly #413](https://github.com/facebook/folly/issues/413)).

**Comment by UniqMartin** [comment]
I aborted the build for now, as it's not going to complete in time. (Will maybe reschedule it later.)

> I've updated the `uhd` formula to 003.009.004.

Is this version of `uhd` still compatible with Boost 1.60.0? If so, I think the best solution would be to pull out this version bump into a separate PR that can be merged fairly quickly, which would simplify this PR.

> `folly` fails since as of boost 1.61.0 the `fcontext_t` is no longer part of the public API, it seems there are upstream changes necessary and a patch/commit is currently missing (see facebook/folly#413).

I guess it's fair to give upstream a bit more time to react to that. Would you mind looking into whether this can be fixed easily or am I asking too much here? Upstream is certainly more likely to deal with the issue if someone goes to the trouble of providing a PR with a fix. (And this will allow us to move on with this PR even if the fix doesn't get accepted immediately by upstream.)

**Comment by afh** [comment]
Hi @UniqMartin 

The new version of `uhd` is compatible with Bosot 1.60.0 and I've created a PR (#1397) for it.

Unfortunately I do not have the resources in the near future to address the folly issue myself.

**Comment by bhamiltoncx** [comment]
OK, the folly issue is fixed. Sorry for the delay there.

**Comment by UniqMartin** [comment]
@bhamiltoncx Thanks! Any suggestions how to proceed with the `folly` formula? Unfortunately, the commit doesn't cleanly apply on top of folly 0.57.0, partially because the sub-library in question has been relocated from `experimental/fibers/` to just `fibers/`.

**Comment by bhamiltoncx** [comment]
You'd either have to backport the patch to 0.57.0 or upgrade brew to the
latest.
2016年6月10日(金) 19:19 Martin Afanasjew <notifications@github.com>:

**Comment by UniqMartin** [comment]
> You'd either have to backport the patch to 0.57.0 or upgrade brew to the latest.

@bhamiltoncx I gave backporting to 0.57.0 a try by cherry-picking commits https://github.com/facebook/folly/commit/6d52608a55d3c0b1f7c9b6ed2fc4d43bc2ddcc0d and https://github.com/facebook/folly/commit/52155e1d78650fd0360104f70df987dceed06cb2 (and resolving conflicts), but failed. However, this made me aware of a problem:

I checked the upstream repository and noticed that releases have been tagged on a weekly basis, but this suddenly stopped in August 2015. That's when 0.57.0 was “released”. Can you comment on your release policy? We might have to remove the `folly` formula from our core tap (formula repository) if things have changed and the expectation is to always build from `master`. (One requirement for our core tap is that there's a tagged, stable release.)

**Comment by bhamiltoncx** [comment]
Sorry, I don't know the release policy.
2016年6月11日(土) 7:48 Martin Afanasjew <notifications@github.com>:

**Comment by knutaldrin** [comment]
What's currently holding back this PR?

**Comment by afh** [comment]
@knutaldrin From my point of view yes.

**Comment by UniqMartin** [comment]
Sorry for the lack of activity here! This PR kinda went off my radar after I pinged `fully` upstream for a stable release tag and this didn't yield anything (except for some discussion). I went ahead and created a boneyard PR (#3321) for `folly` to unblock this PR.

@afh Thanks for still being around! Could you rebase your branch on an up-to-date `master` (to resolve the merge conflicts) and modify it a little bit in the mean time? You should drop the changes to `Formula/folly.rb`. If you could be so kind, would you also split the revision bump commit into individual commits (one per formula)? That's how tend to handle these. Afterwards, your `git log --oneline --reverse master..` should look something like this:

```console
$ git log --oneline --reverse master..
b3c00a8b boost 1.61.0
5a0d4931 boost-bcp 1.61.0
ac59aa98 boost-python 1.61.0
e2e90398 cucumber-cpp: revision for boost
0d10b369 freeling: revision for boost
192b5457 ledger: revision for boost
1be34276 metaproxy: revision for boost
68548afd mkvtoolnix: revision for boost
49c16a05 ncmpcpp: revision for boost
35c86900 source-highlight: revision for boost
9eb8ceb3 uhd: revision for boost
```

You can force push your updated branch as soon as #3321 has been merged.

**Comment by UniqMartin** [comment]
… and `folly` is gone. :tada: Finally, we can resume work here and get this PR merged.

**Comment by afh** [comment]
@UniqMartin Thanks for the work. I'll rebase my branch and do the necessary cleanup in the coming days.

**Comment by DomT4** [comment]
How are things going here?

**Comment by UniqMartin** [comment]
@afh I've basically already done the rebasing locally when I tried to get folly to work. If you're happy with me carrying over that work to a new PR while preserving your commit credit, just let me know. I think we're eager to ship this update sooner than later … and maybe that's a viable option if you don't have time to work on this right now (which would be totally understandable).

**Comment by afh** [comment]
@UniqMartin Oh yes please! That would be very helpful and I'm happy with you carrying over that work to get this update rather sooner than later; my schedule is tight at the moment.

**Comment by UniqMartin** [comment]
Sorry for the long wait everyone. With some luck, we'll be able to ship this very soon.

Closing in favor of #3488.

**Pull request closed without merging**
