### PR TITLE
aws-vault 6.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
```
Minitest::Assertion:
  Expected /aws\-vault:\ error:\ login:\ argument\ 'profile'\ not\ provided,\ nor\ any\ AWS\ env\ vars\ found\.\ Try\ \-\-help/
  to match "aws-vault: error: Specified keyring backend not available, try --help\n".`

**Comment by chenrui333** [comment]
idk why linux test run is different from macos ones

**Comment by chenrui333** [comment]
gonna try out [this](https://github.com/99designs/aws-vault/issues/670#issuecomment-983594427)

**Comment by chenrui333** [comment]
#108198

**Pull request closed without merging**
