### PR TITLE
git-annex 8.20210330

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
```
Database/Handle.hs:257:20: error:
    Variable not in scope: askLogFunc :: m LogFunc
    |
257 |         logFunc <- askLogFunc
    |                    ^^^^^^^^^^
cabal: Failed to build git-annex-8.20210330. See the build log above for
details.
```

**Comment by nirgo** [comment]
[Bug](https://git-annex.branchable.com/bugs/git-annex_8.20210330_fails_to_build_in_brew/) opened upstream.

**Comment by nirgo** [comment]
> [Bug](https://git-annex.branchable.com/bugs/git-annex_8.20210330_fails_to_build_in_brew/) opened upstream.

[Upstream fix](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=8868a3a4c7bfaa356d8c0eb7c6abb8b980f63d99) which won't hit until the next release.

**Comment by chenrui333** [comment]
revisit this later.

**Pull request closed without merging**
