### PR TITLE
slimerjs 0.10.0pre (devel)

### PR DESCRIPTION
**Pull request by spinlock99**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by spinlock99** [comment]
Hi,

Just realized I am getting this error from the `brew audit`:

    ==> audit problems
    slimerjs:
     * Devel: version 0.10.0pre is redundant with version scanned from URL

I'm not really sure what it is complaining about. Does it want me to just remove the version?

**Comment by apjanke** [comment]
Yes. Saying the version is only needed for weird file names that brew can't parse correctly itself. Looks like the extra "-" in the old version was confusing it, but this version changed the format to something that fits brew's conventions and can be parsed. So you can just remove the `version` line instead of updating it.

**Comment by apjanke** [comment]
P.S. Run `audit` first and check that last check box before submitting the PR, so you don't have to go through the CI build queue before getting an error message. :wink: The audit checks are updated over time and maybe other things change between releases of the software you're installing (like here), so it should be run even on trivial version bumps.

**Comment by spinlock99** [comment]
Thanks for the feedback @apjanke. The PR should be all set now.

**Comment by dunn** [comment]
Thanks! Merged as f6c05a414b0e9211dbed65f84f7e5fedd7c02a23.

**Pull request closed without merging**
