### PR TITLE
lnav: fix argument to --with-libcurl and simplify

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by DomT4** [comment]
:+1:

**Comment by apjanke** [comment]
Should this get a revision bump if the old way was not pulling in the curl lib properly?

**Comment by tdsmith** [comment]
libssh2 is already linked to libssl and libcrypto; unless lnav uses openssl symbols directly it shouldn't have to link openssl again? Am I confused or is there broken encapsulation somewhere?

**Comment by DomT4** [comment]
> Should this get a revision bump if the old way was not pulling in the curl lib properly?

We don't bother on optional things, since to date we've had no idea how heavily they're used and whether it's worthwhile making even users who haven't built with the option rebuild.

> Am I confused or is there broken encapsulation somewhere?

It does work fine without the `ENV.append` tweak locally, finally having a moment to test it. So having only the `arg` passed in-formula works fine, now that it actually points to the right place? @ilovezfs reproduced the failure in Slack earlier I believe, maybe I'm forgetting something from that chat.

**Comment by ilovezfs** [comment]
@apjanke @DomT4 @tdsmith PR refreshed.

**Comment by DomT4** [comment]
:+1: Feel free to ship when :green_apple:.

**Pull request closed without merging**
