### PR TITLE
libidn2 2.0.4 (new formula)

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
libidn2 2.0.4 (new formula)

### CODE REVIEW

**Comment by DomT4** [comment]
Oh good, this again. https://github.com/Homebrew/homebrew-core/pull/12959, https://github.com/Homebrew/homebrew-core/pull/12885.

**Comment by JCount** [comment]
Yup, but this time it will _not_ be a versioned formula.

**Comment by JCount** [comment]
`curl` temporarily has `libidn2` set to recommended to test it on the CI.

**Comment by ilovezfs** [comment]
@ :no_good_man:

**Pull request closed without merging**
