### PR TITLE
nushell 0.11.0

### PR DESCRIPTION
**Pull request by waldyrious**
Created with `brew bump-formula-pr --url=https://github.com/nushell/nushell/archive/0.11.0.tar.gz nushell`.

- [Relase notes](https://github.com/nushell/nushell/releases/tag/0.11.0)
- [Announcement blog post](https://www.nushell.sh/blog/2020/03/10/nushell_0_11_0.html)

### CODE REVIEW

**Comment by SMillerDev** [comment]
Test is failing.

**Comment by waldyrious** [comment]
@SMillerDev yes, I was trying to figure out what was the cause. @jonathandturner, can you share any insight? The current test for this formula is:

```
echo '{"foo":1, "bar":2}' | from-json | get bar | echo $it
```

And the output was expected to be

```
Welcome to Nushell <VERSION> (type 'help' for more info)
~ 
❯ 2
~ 
❯ 
```

but instead it now is

```
Welcome to Nushell <VERSION> (type 'help' for more info)
~ 
❯ 2~ 
❯ 
``` 

Was this change intentional?

**Comment by waldyrious** [comment]
(By the way, if you have a suggestion to improve the test pipeline to better reflect nushell's recent evolution, let me know!)

**Comment by jonathandturner** [comment]
Yes, with 0.11.0 this is currently expected. This may change back in the future, as we're in the middle of making some internal protocol changes. Apologies for the confusion.

**Comment by waldyrious** [comment]
No problem, thanks for confirming this was intended (although I must say it looks weird). I'll update the test script accordingly.

**Comment by SMillerDev** [comment]
Thanks @waldyrious! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
