### PR TITLE
python@3.10 3.10.4

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by cho-m** [comment]
For some reason, CI didn't run on this PR and #97011. Need to re-run in both before merge.

**Comment by chenrui333** [comment]
Oh I know, might be because of the github outage today. Let me do the rebase.

**Comment by chenrui333** [comment]
incident reference, https://www.githubstatus.com/incidents/fpk08rxnqjz2

**Comment by cclauss** [comment]
Python 3.10.4 --> https://docs.python.org/release/3.10.4/whatsnew/changelog.html#python-3-10-4-final

**Comment by cho-m** [comment]
On macOS, `chapel` only failed on Big Sur ARM so may not be too important.

On Linux, the `streamlink` failure seems pre-existing. 

On Linux, the `vim` failure looks like some Python versioned Cellar paths are saved somewhere since they point to 3.10.2. Will need a fix, maybe in separate PR:
```
==> brew test --retry --verbose vim
==> FAILED
Full test vim output
  ==> Testing vim
  ==> /home/linuxbrew/.linuxbrew/Cellar/vim/8.2.4650/bin/vim -T dumb -s commands.vim test.txt
  Vim: Warning: Output is not to a terminal
  Vim: Warning: Input is not from a terminal
  "test.txt" [New]~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               ~                                                                               0,0-1All                        
  :python3 import vim; vim.current.buffer[0] = 'hello python3'
  Could not find platform independent libraries <prefix>
  Could not find platform dependent libraries <exec_prefix>
  Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
  Python path configuration:
    PYTHONHOME = (not set)
    PYTHONPATH = (not set)
    program name = 'python3'
    isolated = 0
    environment = 1
    user site = 1
    import site = 1
    sys._base_executable = '/home/linuxbrew/.linuxbrew/bin/python3'
    sys.base_prefix = '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.2'
    sys.base_exec_prefix = '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.2'
    sys.platlibdir = 'lib'
    sys.executable = '/home/linuxbrew/.linuxbrew/bin/python3'
    sys.prefix = '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.2'
    sys.exec_prefix = '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.2'
    sys.path = [
      '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.2/lib/python310.zip',
      '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.2/lib/python3.10',
      '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.2/lib/lib-dynload',
    ]
  Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
  Python runtime state: core initialized
  ModuleNotFoundError: No module named 'encodings'
  
  Current thread 0x00007f8ad8f43740 (most recent call first):
    <no Python frame>
```

**Comment by ylieder** [comment]
Any updates on when Python 3.10.4 is available in Homebrew?

**Comment by SMillerDev** [comment]
When its done

**Comment by cho-m** [comment]
Linux failures can be ignored (`buku` and `streamlink`).

Only `chapel` on 11-arm64 is consistently failing, but other runners don't see an issue with this formula. Will give my approval, but will let someone else check on this and trigger merge.

**Review by cho-m — APPROVED** [review]

**Comment by cho-m** [comment]
Going to merge this to avoid re-running CI due to #100473

**Pull request closed without merging**
