### PR TITLE
openssl@1.1 1.1.1r

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
9 linux failures, please advise. In particular, ruby is looking for `gcc-5`:

```
make: gcc-5: No such file or directory
  make: *** [Makefile:246: generator.o] Error 127
```

**Review by carlocab — APPROVED** [review]
Not worth delaying a fix for a (low-severity) security advisory.

**Comment by thomasdziedzic-calmwave** [comment]
OpenSSL 1.1.1r has been pulled, might be worth force downgrading users that already updated and pulling this version as well. https://mta.openssl.org/pipermail/openssl-announce/2022-October/000237.html

**Comment by fxcoudert** [comment]
> We have received a report of a significant regression in the latest 
3.0.6 and 1.1.1r versions. The regression is not thought to have
security consequences. While the regression is further investigated we 
have taken the decision to withdraw the 3.0.6 and 1.1.1r versions and
instead recommend that users remain on the previous 3.0.5 and 1.1.1q 
versions for now.

Given that _“The regression is not thought to have security consequences”_ I'd say we don't roll back.

**Comment by carlocab** [comment]
I'm ok to revert the commits (and suffer some CI failures in the meantime complaining about versions decreasing...) to avoid more users upgrading to the new version, but forcing a downgrade does not seem necessary.

**Comment by p-linnane** [comment]
I think it's wise to revert especially since the investigation into the regression is ongoing. Better safe than sorry.

**Comment by dtrodrigues** [comment]
Description of the regressions: https://github.com/openssl/general-policies/pull/32

**Pull request closed without merging**
