### PR TITLE
imlib2: avoid opportunistic linkage of libid3tag

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Addresses #16531.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The current bottle isn't broken as far as I know, so the revision bump shouldn't be needed.

**Comment by apjanke** [comment]
Oh, right, you already re-built bottles for these, right? Removing the revision bumps.

**Comment by ilovezfs** [comment]
Yeah, the original issue was born out of the jpeg 9 upgrade causing havoc due to test-bot's monolithic approach. I rebuilt all the broken bottles right away.

**Comment by apjanke** [comment]
Revision bumps removed.

**Comment by ilovezfs** [comment]
Thanks @apjanke!

**Pull request merged**
