### PR TITLE
traefik: switch to containous/go-bindata

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
cc @ilovezfs

### CODE REVIEW

**Comment by ilovezfs** [comment]
I sure hope the community can standardize on one version of this :(

**Comment by ilovezfs** [comment]
Thanks @commitay!

**Comment by commitay** [comment]
> I sure hope the community can standardize on one version of this :(

It would be nice! 

I've been looking at other (non-Homebrew) stuff that uses `bindata`, they are mostly switching to using their own forks. A couple are moving over to https://github.com/gobuffalo/packr or `go-statik`.
___
`gitlab-runner` has https://gitlab.com/gitlab-org/gitlab-runner/issues/3077 open.

`goad` hasn't had any activity in their repo since october.

**Comment by DomT4** [comment]
FWIW https://github.com/jteeuwen/go-bindata/ is back, although it's not the same user despite the username being the same. See: https://github.com/jteeuwen/go-bindata/issues/5.

**Comment by ilovezfs** [comment]
We know ;) https://github.com/Homebrew/homebrew-core/pull/23803#issuecomment-363934701

**Pull request merged**
