### PR TITLE
hg-flow 0.9.8.3

### PR DESCRIPTION
**Pull request by zebastiane**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by zebastiane** [comment]
The build fails with this error

> Error: 1 problem in 1 formula
> hg-flow:
>  * C: 11: col 3: :hg is deprecated. Usage should be "mercurial".

The suggestion would result in replacing [line 11](https://github.com/zebastiane/homebrew-core/blob/c72b13c8f4dc211cc43a6393ba03255066fb1830/Formula/hg-flow.rb#L11) `depends_on :hg` with `depends_on "mercurial"`.

I don't know if this is the correct approach, `hg-flow` needs mercurial sure, but it can already be installed and if I understand the documentation correctly, `depends_on :hg` covers this case.

**Comment by ilovezfs** [comment]
The audit is correct.

**Comment by ilovezfs** [comment]
Thanks for the update @zebastiane!

**Pull request merged**
