### PR TITLE
cif_api 0.4.2 (new formula)

### PR DESCRIPTION
**Pull request by DylanLukes**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DylanLukes** [comment]
To address the CI audit/issues: 

* _Dependency 'icu4c' may be unnecessary as it is provided by macOS; try to build this formula without it._
  * This dependency _is_ necessary, as the system icu4c does not provide headers nor pkgconfig.
* _GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)_
  * This is the official reference implementation for the CIF format. COMCIFS is the "IUCr Committee for the Maintenance of the CIF Standard". The IUCr is the International Union of Crystallography.

**Comment by ilovezfs** [comment]
Thanks for the PR @DylanLukes! I'd recommend hosting this in [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) for now.

**Comment by DylanLukes** [comment]
@ilovezfs sounds good. I was going to submit this to the science tap, but it seems Homebrew/homebrew-science is deprecated, and it's not clear to me what the successor is. 

Do you have any suggestions as to where an appropriate place for it would ultimately be?

**Comment by ilovezfs** [comment]
@DylanLukes a tap within the https://github.com/COMCIFS organization would be good if you can get someone's ear over there.

**Comment by DylanLukes** [comment]
I can look into that. I'm not sure it will be especially feasible, given that they only really have that one library published. Currently, I'm the only person who has forked `cif_api`...  

For the time being I think the best bet is to manage my own tap, so that I can add necessary formulae to it as I build out the additional libraries I will soon be publishing without having to roundtrip through a third party. 

I was more confused by `brewsci/homebrew-science` just being an archive, with the only replacement under `brewsci` being `brewsci/homebre-bio`. This isn't really a bioinformatics specific library.

**Pull request closed without merging**
