### PR TITLE
openrct2 0.3.1

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Looks like the CI jobs for 10.14 and 10.15 partially failed due to an infrastructure issue:
> fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining

What's the procedure here? Should someone restart these jobs?

**Comment by jonchang** [comment]
> -- Checking for module 'jansson>=2.5'
> --   No package 'jansson' found
> CMake Error at /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindPkgConfig.cmake:545 (message):
>   A required package was not found

Looks like jansson is still required for this formula.

**Comment by AaronVanGeffen** [comment]
> Looks like jansson is still required for this formula.

@jonchang Ah, I see — for the 0.3.0 release, the `jansson` package is still required. For current development builds (i.e. `--HEAD`) and the upcoming 0.3.1 release, it has been replaced by `nlohmann-json`. Can we specify this in the formula?

**Comment by SMillerDev** [comment]
> @jonchang Ah, I see — for the 0.3.0 release, the `jansson` package is still required. For current development builds (i.e. `--HEAD`) and the upcoming 0.3.1 release, it has been replaced by `nlohmann-json`. Can we specify this in the formula?

Since we don't really support HEAD installs I'd keep the current dependency.

**Comment by jonchang** [comment]
You can wrap it in a `head do` block.

**Comment by AaronVanGeffen** [comment]
Perhaps it would be more sensible for this to be addressed after the next OpenRCT2 release, then. We expect the 0.3.1 release to happen soon-ish, anyway.

**Comment by AaronVanGeffen** [comment]
OpenRCT2 0.3.1 was released last night. I have updated the PR to reflect this.

**Comment by AaronVanGeffen** [comment]
Looks like the CI jobs for 10.14 and 10.15 partially failed due to an infrastructure issue:
> fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining

What's the procedure here? Should someone restart these jobs?

**Comment by jonchang** [comment]
Yea we've been having issues with CI. Will look into deeper fixes but have restarted the jobs for now

**Comment by jonchang** [comment]
This was merged in https://github.com/homebrew/homebrew-core/commit/94b7ab9c245f5b3b13f5a7c8e687ac174fa2398a, GitHub forgot to close it

**Comment by jonchang** [comment]
Thanks @AaronVanGeffen!

**Pull request closed without merging**
