### PR TITLE
azure-cli: migrate to python@3.9

### PR DESCRIPTION
**Pull request by bsiegel**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by carlocab — CHANGES_REQUESTED** [review]
Thanks for the PR, @bsiegel. However, I believe `azure-cli` isn't compatible with Python3.9 yet. (e.g. https://github.com/Azure/azure-cli/issues/15580)

`azure-cli`'s automated release workflow will just switch this back to Python3.8 at the next version bump. See:

https://github.com/Azure/azure-cli/blob/dev/scripts/release/homebrew/docker/formula_template.txt
https://github.com/Azure/azure-cli/pull/15482
https://github.com/Homebrew/homebrew-core/pull/62253
https://github.com/Homebrew/homebrew-core/pull/62785

**Comment by bsiegel** [comment]
Ah, okay. The tracking issues for Python 3.9 support (https://github.com/Azure/azure-cli/issues/16611) was closed and the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md) for 2.24.0 mention Python 3.9 support so it seemed like this was all that was needed. However as you point out the automation seems like it will just overwrite this, so it sounds like the right thing to do will be to open a PR to update the automation in the azure-cli repo.

**Comment by bsiegel** [comment]
I've opened https://github.com/Azure/azure-cli/pull/18224 to update the formula template

**Comment by carlocab** [comment]
Great, this should be good then once https://github.com/Azure/azure-cli/pull/18224 is merged. Thanks for working on that.

**Comment by carlocab** [comment]
This needs rebasing after #78459. (With `git rebase` and not `git merge`, please. Apologies if that's obvious--I've seen others use `git merge` to rebase before.)

**Comment by bsiegel** [comment]
Still pending merge of the blocking PR in the azure-cli repo. Looks like it -may- be scheduled for completion this month.

**Comment by jiasli** [comment]
We have merged https://github.com/Azure/azure-cli/pull/18224. Please go ahead and merge this PR. Thanks!!

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Thanks, @bsiegel, @jiasli!

**Comment by carlocab** [comment]
Oops, this doesn't work. Let me try something else.

**Comment by carlocab** [comment]
Cherry-picked the changes here onto #83088.

**Pull request closed without merging**
