### PR TITLE
saxon 9.9.0.1

### PR DESCRIPTION
**Pull request by joewiz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by joewiz** [comment]
For the list of changes, see http://www.saxonica.com/documentation/index.html#!changes/all/9.8-9.9.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @joewiz

**Comment by joewiz** [comment]
@fxcoudert Thank you!

**Pull request merged**
