### PR TITLE
lychee 0.7.0 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
  error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
```
Not compatible with ARM yet, it seems.

**Comment by alebcay** [comment]
Upstream seems to think that the issue is probably similar to getting `exa` to build (https://github.com/lycheeverse/lychee/issues/59#issuecomment-771640142). The issue is specifically with the `ring` crate.

**Comment by carlocab** [comment]
It's possible:
```
error: failed to run custom build command for `ring v0.16.15`
```
except that `ring` is [at `0.16.20`](https://crates.io/crates/ring). The solution may be as simple as updating their `Cargo.lock` file and cutting a new release with it.

**Review by carlocab — DISMISSED** [review]
I'm actually not opposed to this formula even if it doesn't build on ARM. I imagine it will eventually anyway.

Rebased, though, to make sure it builds against the current version of Rust.

**Comment by alebcay** [comment]
Just FYI, they're waiting on some of their own dependencies for Big Sur support: https://github.com/lycheeverse/lychee/issues/59#issuecomment-798677637.

**Comment by carlocab** [comment]
If you prefer to wait that's fine with me too. I just thought you were waiting for someone else to approve this before you merged.

**Comment by alebcay** [comment]
I can rebase it anyways; I've kind of just left this open here for tracking purposes up until now.

**Comment by alebcay** [comment]
Looks like all checks are passing now 🎉

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
