### PR TITLE
ffmpeg 7.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Full audit --formula ffmpeg@6 --online --new output
  ffmpeg@6
    * Non-executables were installed to "/opt/homebrew/opt/ffmpeg@6/bin".
      The offending files are:
        /opt/homebrew/opt/ffmpeg@6/bin/python
```

**Comment by chenrui333** [comment]
move ffmpeg@6 to a followup PR.

**Comment by lembacon** [comment]
For `mpv-0.37.0` being able to be successfully built against FFmpeg 7, upstream patches from mpv-player/mpv#13659 are needed.

**Comment by ZhongRuoyu** [comment]
Previous run, for reference: https://github.com/Homebrew/homebrew-core/actions/runs/8591317346?pr=168136

**Comment by ZhongRuoyu** [comment]
This should be good to go.

`audacious` fails to build on Linux on `master` too, and seems to be a result of 942660c2d068c37115e83ad4fa8f7534a4378a7c.

`gstreamer`'s failure on 12-x86_64 seems to be transient; will attempt to rebuild after merging.

**Comment by ZhongRuoyu** [comment]
Would appreciate an approval on #168460 too. That should be merged right after this one.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by kasper93** [comment]
FYI, mpv users are complaining that you ship broken builds after ffmpeg 7 update. https://github.com/mpv-player/mpv/pull/13659 fixes build indeed, but the https://github.com/mpv-player/mpv/pull/13665 is also needed to fix audio conversions.

**Comment by ZhongRuoyu** [comment]
> FYI, mpv users are complaining that builds are broken after ffmpeg 7 update. [mpv-player/mpv#13659](https://github.com/mpv-player/mpv/pull/13659) fixes build indeed, but the [mpv-player/mpv#13665](https://github.com/mpv-player/mpv/pull/13665) is also needed to fix audio conversion issues.

Thanks. Should be fixed by #168933.

**Pull request merged**
