### PR TITLE
libharu 2.4.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Error: An exception occurred within a child process:
    Errno::ENOENT: No such file or directory - build-static/src/libharu.a

**Comment by chenrui333** [comment]
relates to https://github.com/libharu/libharu/commit/bc2fdfa1369bb9f10ee486ae7147fbc9cd9f4e69

**Comment by carlocab** [comment]
There's also a bug in their install configuration. See https://github.com/Homebrew/homebrew-core/issues/109676.

**Comment by chenrui333** [comment]
Go for the merge?

**Comment by chenrui333** [comment]
#111116

**Pull request closed without merging**
