### PR TITLE
dstask 0.23.2 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by naggie** [comment]
Thanks @alebcay (and @carlocab ) -- much appreciated. Note that to get a correct output for `dstask version` as such:

```
$ dstask version
Version: v0.23.2
Git commit: f098bdd77b8887e93ac05ff6b378c98dd8a8d159
Build date: Tue 17 Nov 23:41:53 GMT 2020
```

... you'll need some LDFLAGS as defined here: https://github.com/naggie/dstask/blob/e13a47b68e5b434144d80c75555b05e4a4e30325/do-release.sh#L17

**Comment by carlocab** [comment]
Just to clarify: does this mean the formula as currently built leads to `dstask version` outputting incorrect information?

**Comment by naggie** [comment]
Technically just no information:

```
$ /usr/local/Cellar/dstask/0.23.2/bin/dstask version
Version: Unknown
Git commit: Unknown
Build date: Unknown
```

**Comment by carlocab** [comment]
I see. Would you like to open a PR to fix that?

The formula should be able to parse the version from the tarball URL, so you can just interpolate with `#{version}` for the version. I imagine some Ruby method will give you the current time; hopefully, that can be called from within the install block.

The commit has will be a bit trickier to fix. I imagine switching from the tarball to a git checkout will allow you to recover the commit information using `Utils.git_head`. See https://github.com/Homebrew/homebrew-core/issues/68805.

There are many formulae that set `ldflags` for `go build`; I'm sure you can easily `grep` for them.

**Comment by naggie** [comment]
I can do but I don't think I'll have time for a while. @alebcay I'd appreciate it if you could look into that.

> The commit has will be a bit trickier to fix. I imagine switching from the tarball to a git checkout will allow you to recover the commit information using Utils.git_head. See #68805.

Git checkout sounds like a good solution, I assume (and think) hardcoding the git ref isn't best practice.


> There are many formulae that set ldflags for go build; I'm sure you can easily grep for them.

Great -- that's encouraging.

**Pull request closed without merging**
