### PR TITLE
awscli 1.16.280

### PR DESCRIPTION
**Pull request by cmckni3**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by cmckni3** [comment]
hmmm I'm seeing this during `brew audit`

```
Error: RuboCop found unsupported Ruby version 2.2 in `TargetRubyVersion` parameter (in 2.2-compatible analysis was dropped after version 0.69.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7
````

**Comment by chenrui333** [comment]
previous effort, https://github.com/Homebrew/homebrew-core/pull/46001

**Comment by cmckni3** [comment]
any ideas?

**Comment by SMillerDev** [comment]
It failed on testing `conjure-up`. Does that work locally?

**Comment by cmckni3** [comment]
Yes it passed locally for me. It’s failing on Catalina though and I’m on Mojave

**Comment by chenrui333** [comment]
I can check on this later. I am on Catalina machine.

**Comment by chenrui333** [comment]
test on my catalina machine, works pretty good

$ aws --version
aws-cli/1.16.280 Python/3.7.5 Darwin/19.0.0 botocore/1.13.16

```
$ aws sts get-caller-identity
{
    "UserId": "AROAWH7HDRXRQIK4PQ66R:ruichen",
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @cmckni3!!

**Comment by cmckni3** [comment]
Awesome! No problem

**Pull request closed without merging**
