### PR TITLE
librsvg 2.57.0

### PR DESCRIPTION
**Pull request by chenrui333**
gnome_devel_allowlist: allow librsvg 2.57.0

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

image

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  configure: error: Package requirements (	cairo >= 1.17.0               	cairo-png >= 1.17.0           	cairo-gobject >= 1.17.0       	freetype2 >= 20.0.14       	gdk-pixbuf-2.0 >= 2.20 	gio-2.0 >= 2.24.0               	glib-2.0 >= 2.50.0             	harfbuzz >= 2.0.0         	libxml-2.0 >= 2.9.0         	pangocairo >= 1.46.0          	pangoft2 >= 1.46.0	       ) were not met:
  
  Requested 'cairo >= 1.17.0' but version of cairo is 1.16.0
  Requested 'cairo-png >= 1.17.0' but version of cairo-png is 1.16.0
  Requested 'cairo-gobject >= 1.17.0' but version of cairo-gobject is 1.16.0
```

**Comment by chenrui333** [comment]
raised an upstream issue about cario release scheme, https://gitlab.freedesktop.org/cairo/cairo/-/issues/804

**Comment by chenrui333** [comment]
gonna wait for cario 1.18.0 before retry this PR

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Seems unrelated, let's try this again
```
Full linkage --test easy-tag output
  Broken dependencies:
    /opt/homebrew/opt/libid3tag/lib/libid3tag.0.16.2.dylib (libid3tag)
```

**Comment by iMichka** [comment]
easy-tag has been fixed by #152204

**Review by iMichka — APPROVED** [review]

**Pull request merged**
