### PR TITLE
hopenpgp-tools 0.20.1

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Tried to remove the `(buildpath/"cabal.config")` hack, apparently it's still needed 😢

**Comment by ilovezfs** [comment]
That would only be true if we move it to 8.4. 8.2 is fine https://matrix.hackage.haskell.org/package/hopenpgp-tools

**Comment by commitay** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
```
Downloading graphviz-2999.5.0.0...
Configuring graphviz-2999.5.0.0...
Building graphviz-2999.5.0.0...
Failed to install graphviz-2999.5.0.0
```
It looks as if it may still need the `graphviz >= 2999.17.0.0` constraint.

**Comment by ilovezfs** [comment]
that doesn't make sense. why is it passing on hackage matrix. maybe because they use cabal new-build

**Comment by JCount** [comment]
That is my guess.

**Comment by ilovezfs** [comment]
will test

**Comment by ilovezfs** [comment]
Yeah it builds fine with new-build.

**Pull request closed without merging**
