### PR TITLE
swift 5.1.2

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is going to take far too long to build on my machine. Apologies to the build bots for making them suffer.

Let's see how many attempts this takes...

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on Mojave and Catalina

23:48:12 --- bootstrap: note: building runtime v4_2 target: PackageDescription4: 
23:48:12 Compiling Swift Module 'PackageDescription' (10 sources)
23:48:12 Linking PackageDescription
23:48:12 --- bootstrap: note: building runtime v4 target: PackageDescription4: 
23:48:12 Compiling Swift Module 'PackageDescription' (10 sources)
23:48:12 Linking PackageDescription
23:48:12 --- bootstrap: note: building stage1
23:48:12 Compiling libc.c
23:48:12 unable to spawn process (No such file or directory)
23:48:12 --- bootstrap: error: build failed with exit status 1
23:48:12 Building the standard library for: swift-stdlib-macosx-x86_64
23:48:12 /private/tmp/swift-20191107-96979-14ozqlb/swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
23:48:12

**Comment by Bo98** [comment]
> unable to spawn process (No such file or directory)

:/

Wish it said a little more than that.

**Comment by Bo98** [comment]
Let's try a verbose build.

**Comment by SMillerDev** [comment]
Does it build successfully locally?

**Comment by fxcoudert** [comment]
It's probably worth opening a ticket upstream to get some help. swift is very difficult to build :(

**Comment by Bo98** [comment]
@SMillerDev Unfortunately, I've been unable to set aside a couple hours for it to build locally but I may have to try at the weekend.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
I think I've found the problem: https://github.com/apple/swift-package-manager/blob/swift-5.1.2-RELEASE/Utilities/bootstrap#L740

If CC isn't absolute it takes it relative to the working directory, which is kind of dumb.

What's the best way of setting CC ourselves to be absolute? I suppose I could also unset it, though I don't suppose letting their build script pick the clang for themselves is preferred.

**Comment by Bo98** [comment]
And my first attempt there didn't work, because `os.path.realpath` also follows symlinks which `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/cc` is and thus invokes `/usr/local/Homebrew/Library/Homebrew/shims/super/cc` instead which doesn't work directly (verified in `brew sh`).

**Comment by Bo98** [comment]
For reference, I have opened https://bugs.swift.org/browse/SR-11757 as there is a bug here anyhow.

The options open to us beside that is either:
* Patch the build script (either now or after a patch is proposed in SR-11757)
* Clear the CC env and let it rely on `xcrun --find clang` (which means bypassing the superenv shim - which I suspect is undesirable but someone more familiar with it can let me know)

**Pull request closed without merging**
