### PR TITLE
caf 0.18.0

### PR DESCRIPTION
**Pull request by Neverlord**
Update CAF to version 0.18.0

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> /usr/local/Cellar/zeek/3.2.3/bin/zeek --version
dyld: Library not loaded: /usr/local/opt/caf/lib/libcaf_core.0.17.6.dylib
  Referenced from: /usr/local/Cellar/zeek/3.2.3/bin/zeek
  Reason: image not found
```

**Comment by Neverlord** [comment]
Zeek 3.x won't build with CAF 0.18. Zeek 4.0 (currently available as release candidate: https://github.com/zeek/zeek/releases/tag/v4.0.0-rc2) is going to depend on 0.18.

**Comment by carlocab** [comment]
Bumping caf to 0.18.0 breaks zeek, though, so we can't ship this as is. Is there a timeline for zeek 4.0?

**Comment by Neverlord** [comment]
> Bumping caf to 0.18.0 breaks zeek, though, so we can't ship this as is. Is there a timeline for zeek 4.0?

RC2 for Zeek 4.0 just released. So it's probably going to take a couple weeks before the final release. I don't know the HomeBrew internals enough to know whether there's a way to point Zeek to a specific CAF release in the meantime. Otherwise it's wait and see, I guess? 🙂

**Pull request closed without merging**
