### PR TITLE
nift 2.3.5

### PR DESCRIPTION
**Pull request by n-ham**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by n-ham** [comment]
Seems std::floor works on Linux/Windows but needs to be just floor on osx, have fixed this in the next/new PR. My apologies..

**Comment by Bo98** [comment]
> Seems std::floor works on Linux/Windows but needs to be just floor on osx

I think it's picky and needs the `<cmath>` header or something. Technically `math.h` is C and `cmath` is C++.

**Comment by n-ham** [comment]
It seems to compile when I remove the std:: in front of floor, I'll add cmath as well anyway, cheers! Should hopefully be fixed for the moment..

**Comment by Bo98** [comment]
> It seems to compile when I remove the std:: in front of floor

Yeah, because you can use C in C++. The differences between the two are minimal anyway.

**Comment by Bo98** [comment]
Merged now - thanks!

**Pull request closed without merging**
