### PR TITLE
awscli 2.6.3

### PR DESCRIPTION
**Pull request by DannyGoldberg**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

Pulls in fix for issue https://github.com/aws/aws-cli/issues/6920, https://github.com/aws/aws-cli/pull/6476

_Full changelog: https://github.com/aws/aws-cli/compare/2.6.2...2.6.3_

### CODE REVIEW

**Comment by mprimeaux** [comment]
@DannyGoldberg First, thanks much for this change as it is important to me and our teams. My apologies if you are a reviewing with write access to this repository but if you aren't would you kindly add a reviewer who does have write access?  

Again, thanks for your help and support.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @DannyGoldberg!

@mprimeaux yeah, we do review/merge pretty fast. No worries.

**Comment by mprimeaux** [comment]
Thank you. I wasn’t sure but happy to help when I can. Again, thank you 🙏

**Comment by ebachle** [comment]
Thanks from me too y'all.  When you get brew updated faster than the underlying bug is fixed, it's really impressive!

**Pull request closed without merging**
