### PR TITLE
emscripten 2.0.23

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>build failure</summary>

```
==> script/build-wasm
Last 150 lines from /Users/brew/actions-runner-x86_64/_work/homebrew-core/homebrew-core/bottles/logs/tree-sitter/04.build-wasm:
2021-05-28 21:47:40 -0700

script/build-wasm

shared:INFO: (Emscripten: Running sanity checks)
cache:INFO: generating system headers: sysroot_install.stamp... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot_install.stamp" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libgl.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libgl.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libal.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libal.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libhtml5.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libhtml5.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc++-noexcept.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc++abi-noexcept.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libdlmalloc.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc_rt_wasm.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libsockets.a... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libsockets.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/private/tmp/tree-sitter-20210528-83161-twib7e/tree-sitter-0.19.5/.brew_home/.emscripten_cache/generated_struct_info.json" for subsequent builds)
cache:INFO:  - ok
emcc: error: undefined exported symbol: "__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_" [-Wundefined] [-Werror]
```

</details>

**Comment by carlocab** [comment]
Reported upstream at https://github.com/tree-sitter/tree-sitter/issues/1131.

**Comment by chenrui333** [comment]
Close it for now.

**Comment by chenrui333** [comment]
Superseded by #79571

**Pull request closed without merging**
