### PR TITLE
llvm@4: delete

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The last formula that needed it, ispc, now no longer uses it (#46789).

This had issues on Catalina as well and isn't worth tracking down.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @Bo98

**Comment by eregon** [comment]
Hello, TruffleRuby was using this formula, is there a specific reason for removing it?

The latest version of TruffleRuby ships its own LLVM and no longer needs this, but previous TruffleRuby versions on macOS do need `llvm@4`.

https://github.com/oracle/truffleruby/issues/1820 is an issue about this.

**Comment by eregon** [comment]
From https://github.com/Homebrew/homebrew-core/issues/46728, it seems the error is:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:89:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
         ^~~~~~~~~~
1 error generated.
```

That could likely be solved by running tests with `xcrun --sdk macosx $ORIGINAL_COMMAND`.

**Comment by Bo98** [comment]
The reason was it was old, was completely broken and unusable on Catalina, and was no longer used by any other formulae in Homebrew. We can't keep everything around forever, particularly unsupported software that wasn't even working properly.

> That could likely be solved by running tests with `xcrun --sdk macosx $ORIGINAL_COMMAND`.

Looks like it is already picking up the SDK. `stdarg.h` doesn't exist in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include`, that's for sure.

Either way, it would work out-of-the-box like every other `llvm` formulae we ship does.

If you can get it functional on Catalina (i.e. `brew test` passes without having to change it to an extent that would be calling on end-users to adjust their workflow for `llvm@4` on Catalina specifically), then you have two options: resubmit it (might be rejected) or create your own tap. Your script should then work as long as `brew tap <your tap>` has been done at least once.

**Comment by dapixcasey** [comment]
This change really makes me angry. We use llvm in production and now we need to find ways for our users to get llvm in a clean way without using brew

**Comment by Bo98** [comment]
> we need to find ways for our users to get llvm

Presumably LLVM 6 and later, which has been available for a while now and are available in brew, don't work for you?

> without using brew

You can still use brew

```
brew tap-new <user>/<tap name>
brew extract --version=4.0.1 llvm@4 <user>/<tap name>
```

Then you can maintain the formula in your own repository on GitHub which people can use with `brew tap <user>/<tap name>`.

**Comment by jonchang** [comment]
If it doesn’t build on our supported platforms and otherwise isn’t needed by other formulae, we are likely to drop it. Please consult https://docs.brew.sh/Versions for our policy regarding versioned formulae. In particular:

> Homebrew’s versions are not intended to be used for any old versions you personally require for your project. You should create your own tap for formulae you or your organisation wish to control the versioning of or those that do not meet the above standards.

Please move further discussion to Discourse if you need help with the `brew extract` command or setting up your own tap.

**Pull request merged**
