### PR TITLE
solr: fix paths

### LINKED ISSUE #50537: solr 8.4.1 broken since commit of #50494
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew upgrade

## What happened (include command output)

Solr doesn't start anymore since updated from 8.4.1 to 8.4.1_1, due to the commit of #50494

<details>
  <summary>Command output</summary>
  <pre>

  $ solr start

Solr server directory /usr/local/Cellar/solr/8.4.1_1/libexec/server not found!

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install solr
solr start

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/Homebrew/homebrew-core/issues/50537.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@mkalkbrenner, could you test this?

**Comment by mkalkbrenner** [comment]
I can confirm that Solr is now starting. But all existing cores and collections are broken.
The reason is that symlink `/usr/local/opt/solr` is wrong. It has to point to the libexec folder now.
Or you need to modify a Java property:
`-Dsolr.install.dir=/usr/local/opt/solr/libexec`

**Comment by mkalkbrenner** [comment]
That's because the replacement for `../../../..` doesn't apply to any user generated solrconfig.xml.

**Comment by reitermarkus** [comment]
@mkalkbrenner, please have another look.

**Review by zbeekman — CHANGES_REQUESTED** [review]
@reitermarkus could you please add tests that would catch this problem in the future? The “tests” for solr currently stink. 

Or, @mkalkbrenner could you suggest some tests to catch this that I could easily add? (Caveat: I know almost nothing about java/solr)

Also, is there still a good reason to keep the versioned formula?

**Comment by mkalkbrenner** [comment]
> Also, is there still a good reason to keep the versioned formula?

@zbeekman What do you mean by that statement? Drop the formula entirely?

As maintainer of https://github.com/solariumphp/solarium and https://www.drupal.org/project/search_api_solr I know a lot of people who use the formula for their  development environment.

**Comment by zbeekman** [comment]
Yes I meant drop it. But if there are a lot of people depending on it and using it then I’m happy keeping it.

**Comment by SMillerDev** [comment]
I think the suggestion to drop it was refering to solr@7.7. Do a lot of people still use that? And is it still supported by upstream?

**Comment by mkalkbrenner** [comment]
In my latest talks about local development with Solr I recommended to use homebrew on macOS instead of docker. While Solr works great on docker in gerneral, there're too many problems with docker on macOS.

So I'm not a fried of dropping the support entirely!

I now had a deeper look at the issue. The problem is that the original solr scripts expect to find the various components relative to the scripts themselves. But with 8.4.1_1 you moved these scripts locataed under `bin` to `libexec/bin` while you put corresponding wrapper scripts in the original `bin` folder.

The latest PR of @reitermarkus now  tries to patch all the original scripts and example config files to replace the relative path `..` by the full real path of `libexec`. But this will break all existing cores and collections because their solrconfig.xml is not patched.

So I see two solutions if you want to force the usage of openjdk:
1. Keep the wrapper script approach but copy the scripts to `libexec`directly instead of the bin folder. In this case the relative patch `..` will work again.
2. Don't use the wrapper script but patch the solr scripts (and not the configs!) to set JAVA_HOME to openjdk.

For both solutions it won't be required to patch the xml config files anymore!

**Comment by mkalkbrenner** [comment]
A third solution would be ...

3. Don't move the `bin/*` files to `libexec/bin/` but the wrapper scripts and change the symlinks in `/usr/local/bin` to point to `libexec/bin/*`

**Comment by zbeekman** [comment]
@reitermarkus any chance you could look at this again?

**Comment by mkalkbrenner** [comment]
I now implemented my proposed solution 1 and created #50684

**Comment by mkalkbrenner** [comment]
this one should be closed because of the commit of  #50759

**Pull request closed without merging**
