### PR TITLE
aliyun-cli 3.0.27

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
```
22:41:41 go: downloading github.com/jteeuwen/go-bindata v3.0.7+incompatible
22:41:41 go: extracting github.com/jteeuwen/go-bindata v3.0.7+incompatible
22:41:41 go-bindata -o resource/metas.go -pkg resource -prefix ../aliyun-openapi-meta ../aliyun-openapi-meta/...
22:41:41 bindata: Failed to stat input path '../aliyun-openapi-meta': lstat ../aliyun-openapi-meta: no such file or directory
22:41:41 make: *** [metas] Error 1
```

**Comment by igas** [comment]
closing. Hopefully #44606 will fix the issue

**Pull request closed without merging**
