### PR TITLE
Extra boost dependents

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I'm splitting these off from #109752 because there's no way we'll ever get a PR that rebuilds that many formulae merged.

### CODE REVIEW

**Comment by danielnachun** [comment]
We should fix the Linux failures in follow up PRs.  Here is a list:
- postgis - we forgot to drop the GCC dependency
- dspdfviewer - it probably needs to have `--std=c++14` set explicitly on Linux
- freeling - probably missing an `include <cmath>`
- mupen64plus - needs this upstream commit: https://github.com/mupen64plus/mupen64plus-core/commit/fedf950be7370ff8e8649b1c35519b2474df8cc3.patch
- osrm-backend - can't find `pthread` for some reason - one of its dependencies probably needs to be rebottled.
- upscaledb - will be fixed in https://github.com/Homebrew/homebrew-core/pull/111966

**Review by cho-m — DISMISSED** [review]

**Comment by carlocab** [comment]
We should drop the failed Linux builds before merging. Someone needs to do `brew pr-pull` and push the bottle commits here. I can do this later when I get off mobile.

**Comment by danielnachun** [comment]
> We should drop the failed Linux builds before merging. Someone needs to do `brew pr-pull` and push the bottle commits here. I can do this later when I get off mobile.

I'm not entirely sure how this works.  Does this mean we drop the revision bumps for the failed builds without rerunning CI again?  Or do we need another CI run?

**Comment by danielnachun** [comment]
I have no idea what is wrong with `fuego` but it seems unrelated to migration, so I think we should drop the Linux bottle until we know why the test is failing.  The other build failures will all be fixed by various PRs.

**Comment by carlocab** [comment]
Downloading the bottles. May take a bit.

**Comment by carlocab** [comment]
> I'm not entirely sure how this works. Does this mean we drop the revision bumps for the failed builds without rerunning CI again? Or do we need another CI run?

We can drop them without running CI again. Doing that now.

**Comment by carlocab** [comment]
Bottles are still uploading, but will merge this when they're ready.

**Pull request closed without merging**
