### PR TITLE
node 10.0.0

### PR DESCRIPTION
**Pull request by chrmoritz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR updates node to the new major node 10 release: https://nodejs.org/en/blog/release/v10.0.0/

Unfortunately npm 6.0.0 didn't make it in time for the node 10.0 release (it will ship most likely with node 10.1) and because of that we have to apply the same workaround as node upstream to suppress the incorrect incompatibility warnings from npm 5.6.0.
I had to also change the native addon test from the soon to be obsolete (native BigInt support will ship with v8 5.7) `bignum` module to `bufferutil`, because it doesn't support node 10 yet.

### CODE REVIEW

**Comment by chrmoritz** [comment]
Looks like `joplin` doesn't support node 10 yet.

```
==> brew test --verbose joplin
==> FAILED
Testing joplin
/usr/bin/sandbox-exec -f /tmp/homebrew20180424-33831-1d7ln38.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/joplin.rb --verbose
==> /usr/local/Cellar/joplin/1.0.106/bin/joplin config editor subl
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '/usr/local/Cellar/joplin/1.0.106/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/1.0.106/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: joplin: failed
Failed executing: /usr/local/Cellar/joplin/1.0.106/bin/joplin config editor subl
```

**Comment by chrmoritz** [comment]
Added the missing revision bump for `joplin`, so that it's native addon part can be rebuild against node 10.

**Comment by chrmoritz** [comment]
@ilovezfs: I've manually updated the `sqlite3` dependency in `joplin` to version 4.0.0, which does support node 10. Looking at [the changes between v3.1.13 and 4.0.0](https://github.com/mapbox/node-sqlite3/compare/72bddaf...d02f5c3) there doesn't seem to be any noticable change expect the required nan update and dropping node 0.10 and 0.12 support (per node-pre-gyp upgrade), which is the reason for it being a semver major release.

If you feel uncomfortable with it, we could alternative let `joplin` depend on `node@8` instead.

**Review by ruchernchong — APPROVED** [review]

**Comment by ilovezfs** [comment]
@chrmoritz has the issue been reported to joplin?

**Comment by ilovezfs** [comment]
🚀

**Comment by micdah** [comment]
I'm having difficulty upgrading to node 10.0.0 from 9.11.1, this is the output from `brew`

```
Please wait for it to finish or terminate it to continue.
==> Upgrading 2 outdated packages, with result:
node 9.11.1 -> 10.0.0, wireshark 2.4.6 -> 2.6.0
==> Upgrading node --with-openssl
==> Downloading https://nodejs.org/dist/v10.0.0/node-v10.0.0.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/node/10.0.0 --without-npm --with-intl=system-icu --shared-openssl
==> make install
Last 15 lines from /Users/micdah/Library/Logs/Homebrew/node/02.make:
../src/node_crypto.cc:457:43: error: cannot initialize a parameter of type 'const SSL_METHOD *' (aka 'const ssl_method_st *') with an lvalue of type 'int'
  SSL_CTX_set_max_proto_version(sc->ctx_, max_version);
                                          ^~~~~~~~~~~
/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ssl.h:2346:61: note: passing argument to parameter 'meth' here
int SSL_CTX_set_ssl_version(SSL_CTX *ctx, const SSL_METHOD *meth);
                                                            ^
../src/node_crypto.cc:461:22: error: no member named 'ticket_key_name_' in 'node::crypto::SecureContext'
  if (RAND_bytes(sc->ticket_key_name_, sizeof(sc->ticket_key_name_)) <= 0 ||
                 ~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [/private/tmp/node-20180427-33762-750iu4/node-v10.0.0/out/Release/obj.target/node_lib/src/node_crypto.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm 76570940aae8a38f80b343391f51957d58e5952a.intermediate
make: *** [node] Error 2
```

**Comment by chrmoritz** [comment]
@micdah Thx for reporting this. Openssl in node 10 was upgraded to 1.1.0h and the `--with-openssl` option should build now against homebrews `openssl@1.1` instead. Will Open a PR with a fix soon.

**Comment by chrmoritz** [comment]
@ilovezfs Do you have looked into the statistics on how often `node --with-openssl` is used? I'm currently testing a build of node against homebrews `openssl@1.1` locally, but would be fine with removing the option altogether too.

**Comment by ilovezfs** [comment]
last 90 days https://gist.github.com/ilovezfs/a92142a6b2ba084c3a95cde174b32b70

**Comment by ilovezfs** [comment]
Alternatively, we could remove `depends_on "python@2"` from `emscripten`. That goes against the spirit of https://github.com/Homebrew/homebrew-core/issues/26287 but it looks like the formula is actually still using system Python anyway, which should be fixed at some point if we do keep the `python@2` dependency.

**Comment by chrmoritz** [comment]
I can confirm that https://github.com/chrmoritz/homebrew-core/commit/700e517aa7e1b007af09c13bf88ad04c41ce356f seems to work for building node against homebrews `openssl@1.1`. 
And regarding `emscripten` it looks like
 https://github.com/Homebrew/homebrew-core/blob/efb001d45f6ebc427ae7faf4918bd1f3d452729f/Formula/emscripten.rb#L49-L54
needs to be updated to use homebrew python2 instead.

**Comment by ilovezfs** [comment]
indeed

**Pull request closed without merging**
