### PR TITLE
ufraw: deprecate

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
No longer supported upstream and blocking https://github.com/Homebrew/homebrew-core/pull/114917

### CODE REVIEW

**Comment by SMillerDev** [comment]
Huh, fun fact it's already broken before that PR.

CC @cho-m for suggestions

**Comment by cho-m** [comment]
Linux build may have broke when we updated Linux GCC.

There is a patch that some Linux distros are/were using. Fedora's has commit in their forked repo: https://github.com/sergiomb2/ufraw/commit/c56f8be3caf1cf3d9a5c80597bdbaf1325faacc0. Gentoo had applied a similar patch before they removed `ufraw` (https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=dd9edb33d1b4949330bb07661f39d76df84519f3).

**Comment by cho-m** [comment]
Sadly `ufraw` has various bugs and some CVEs.

Gentoo gave up on the package due to this:
- https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4789b3a217c455255ac641ce403f940ec1f92432
- https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=699a7159a7d6c00cc571191e2a8ccd884e8fb670

**Comment by SMillerDev** [comment]
Yeah, I'm not going to waste time fixing a package I'm planning to deprecate.

**Comment by SMillerDev** [comment]
Okay, build now ignores Linux so I'd say it's ready to merge.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
