### PR TITLE
util-linux: keep getopt. system one is rather crippled

### PR DESCRIPTION
**Pull request by glensc**
Refs: #26353

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Going to pass on this since otherwise we'll need to make the formula keg_only. Thanks nonetheless, @glensc

**Comment by glensc** [comment]
here's example of crippledness:

```
$ /usr/bin/getopt -o hv --long help,verbose -n test -- 'argument with space.zip'
 -- hv --long help,verbose -n test -- argument with space.zip
$ /usr/local/bin/getopt -o hv --long help,verbose -n test -- 'argument with space.zip'
 -- 'argument with space.zip'
```

**Comment by glensc** [comment]
@ilovezfs don't know what keg_only means or why it's bad.

perhaps rename the single binary to `ggetopt` like some other recipes do?

**Comment by glensc** [comment]
i have software that works in linux, there's no good alternative to doing option parsing in shell script.

sounds a bit silly to force "porting" to use program from 1970, while the linux (gnu?) version is more advanced.

**Comment by ilovezfs** [comment]
@glensc I assume `brew install gnu-getopt` does what you want already.

**Pull request closed without merging**
