### PR TITLE
gmt: revision for ARM

### PR DESCRIPTION
**Pull request by seisman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by seisman** [comment]
I'd like to build the ARM bottle for gmt, but it doesn't work as I expected:

```
==> Using Homebrew/homebrew-test-bot 328a7db (Merge pull request #558 from Homebrew/dependabot/bundler/docile-1.3.5)
==> Using Homebrew/brew 2.7.4-21-gedfa34064 (Merge pull request #10137 from sjackman/sj/governance)
==> Testing Homebrew/homebrew-core f6df20d767 (Merge 54af16110e9da77b486a9611cf60a95fc6b142f3 into 9172c8ee3d84981e5ee274c67bf3ecb9857544cf):

==> Running Formulae#detect_formulae!
==> git -C /opt/homebrew/Library/Taps/homebrew/homebrew-core fetch origin +refs/heads/master
    url             https://github.com/Homebrew/homebrew-core/pull/69023/checks
    origin/master   9172c8ee3d (sile: update 0.10.13_2 bottle.)
    HEAD            f6df20d767 (Merge 54af16110e9da77b486a9611cf60a95fc6b142f3 into 9172c8ee3d84981e5ee274c67bf3ecb9857544cf)
    diff_start_sha1 9172c8ee3d84981e5ee274c67bf3ecb9857544cf
    diff_end_sha1   f6df20d767f8b838efafc1e65317c210242ad1cc
==> Testing Formula changes:
    added    (empty)
    modified gmt
    deleted  (empty)

==> Running Formulae#formula!(gmt)
==> SKIPPED gmt
All steps passed!
Warning: gmt has not yet been bottled on ARM!
```

What's the correct way to enable ARM support?

**Comment by carlocab** [comment]
Does this build for you from source on ARM?

**Comment by carlocab** [comment]
I've submitted a bottle request: https://github.com/Homebrew/homebrew-core/actions/runs/486408086

**Comment by carlocab** [comment]
No, it doesn't build yet.
```
/tmp/gmt-20210114-45703-wos0wo/gmt-6.1.1/src/gmt_common_sighandler.c:178:14: error: no member named '__eip' in 'struct __darwin_arm_thread_state64'
        array [0] = UC_IP (uc); /* caller's address */
                    ^~~~~~~~~~
/tmp/gmt-20210114-45703-wos0wo/gmt-6.1.1/src/gmt_common_sighandler.c:62:56: note: expanded from macro 'UC_IP'
#   define UC_IP(uc) ((void *) (uc)->uc_mcontext->__ss.__eip)
                               ~~~~~~~~~~~~~~~~~~~~~~~ ^
```
Please only request for ARM bottles if you know they build from source. Thank you!

**Pull request closed without merging**
