### PR TITLE
bun 1.1.6 (new formula)

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — COMMENTED** [review]
I wonder if we can do the zig build for it.

**Comment by p-linnane** [comment]
> I wonder if we can do the zig build for it.

I know nothing about zig unfortunately.

**Comment by chenrui333** [comment]
you can get some inspirations from:
- https://github.com/Homebrew/homebrew-core/pull/105263
- https://github.com/Homebrew/homebrew-core/pull/142016

I made some similar efforts with swc as well:
- https://github.com/Homebrew/homebrew-core/pull/84075

**Comment by p-linnane** [comment]
I took a look at those previous PR's. This looks very messy, and isn't something I want to burn time on.

**Pull request closed without merging**
