### PR TITLE
gnu-apl 1.6

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 the 12,259 line patch can be removed now, but once again of course it needs to be patched. :scream_cat: 

```
inreplace "src/LApack.cc", "malloc.h", "malloc/malloc.h"
```

:8ball:

**Comment by DomT4** [comment]
Not sure if I should laugh or cry really 😕. At least we get to drop the 12k+ patch, I guess.

**Comment by ilovezfs** [comment]
@DomT4 one of these days we'll just create a `gnu` tap and pawn it off on some unsuspecting third party.

**Comment by apjanke** [comment]
LOL.

Lookin' good. Merged.

**Comment by ilovezfs** [comment]
@apjanke LOL is right. In case we were wondering whether they tested at all on macOS, I think we now have our answer.

**Pull request closed without merging**
