### PR TITLE
minimal-racket 8.7

### PR DESCRIPTION
**Pull request by xxyzz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
Thanks @xxyzz!

**Comment by chenrui333** [comment]
Looks like it builds/tests out fine with openssl@3; let's also update it to use openssl@3 then

**Comment by chenrui333** [comment]
> I build it with your change in my machine but the loaded openssl version is 0.9.8. Update to openssl 3 probably needs this patch:
> 
> ```diff
> diff --git a/racket/collects/openssl/libcrypto.rkt b/racket/collects/openssl/libcrypto.rkt
> index a10c609118..e775ab9b82 100644
> --- a/racket/collects/openssl/libcrypto.rkt
> +++ b/racket/collects/openssl/libcrypto.rkt
> @@ -73,9 +73,6 @@
>    #:runtime?-id runtime?
>    (case (if runtime? (system-type) (cross-system-type))
>      [(windows) '(so "libeay32")]
> -    [(macosx)
> -     ;; Version "1.1" is bundled with Racket
> -     '(so "libcrypto" ("1.1" #f))]
>      [else '(so "libcrypto")]))
> 
>  (define libcrypto
> diff --git a/racket/collects/openssl/libssl.rkt b/racket/collects/openssl/libssl.rkt
> index b570ec007b..1e8cf7574c 100644
> --- a/racket/collects/openssl/libssl.rkt
> +++ b/racket/collects/openssl/libssl.rkt
> @@ -17,9 +17,6 @@
>    #:runtime?-id runtime?
>    (case (if runtime? (system-type) (cross-system-type))
>      [(windows) '(so "ssleay32")]
> -    [(macosx)
> -     ;; Version "1.1" is bundled with Racket
> -     '(so "libssl" ("1.1" #f))]
>      [else '(so "libssl")]))
> 
>  (define libssl
> ```
> 
> Nope, this doesn't work...

can you submit it to the upstream for discussion, I am gonna revert the openssl@3 change now.

**Review by branchv — APPROVED** [review]

**Comment by xxyzz** [comment]
> can you submit it to the upstream for discussion, I am gonna revert the openssl@3 change now.

That patch doesn't make racket to use openssl 3 on my machine and I still don't understand where that libssl.0.9.8.dylib come from.

**Comment by chenrui333** [comment]
> > can you submit it to the upstream for discussion, I am gonna revert the openssl@3 change now.
> 
> That patch doesn't make racket to use openssl 3 on my machine and I still don't understand where that libssl.0.9.8.dylib come from.

Do you mind creating an issue in the upstream to kill of openssl@3 chat (and link to this PR)? Thanks!

**Comment by xxyzz** [comment]
I figure it out and create a new pull request: https://github.com/Homebrew/homebrew-core/pull/115930

The official racket build still ships openssl 1 for macOS, I don't think they would accept the patch.

**Pull request closed without merging**
