### PR TITLE
tgui 0.7.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by DomT4** [comment]
Although `devel` may be older than stable now? ❓

**Comment by ilovezfs** [comment]
@DomT4 Yes, you're right. Audit didn't catch it because there's a bug in the devel spec:
```
iMac-TMP:Formula joe$ brew info tgui
tgui: stable 0.6.9 (bottled), devel 2
```

**Comment by DomT4** [comment]
Sigh, that issue again. We'll fix that one day, hopefully.

**Comment by ilovezfs** [comment]
Yeah, I've noticed we seem to have trouble parsing devel versions from their URLs in general.

**Comment by DomT4** [comment]
Anything with an initial version and a numerical version modifier separated with a `-`, pretty much.

**Comment by ilovezfs** [comment]
That sounds quite fixable.

**Comment by DomT4** [comment]
It probably is. The joy is making sure that we don't involuntarily break a bunch of other versions by tweaking our core understanding of this kind of string, and nobody's really been up for that kind of testing to date.

**Comment by ilovezfs** [comment]
@DomT4 one way to check that is to dump `brew info` for literally everything and then just diff the before and after. It's good when all that the diff shows is ones that are currently broken that we didn't notice yet and shows nothing else.

**Comment by DomT4** [comment]
Well, if you wanted to work on it, I'm sure we could organise a cake in appreciation or something 😉.

**Comment by ilovezfs** [comment]
I may take a look. The `version "123"` overrides are always a heinous sight.

**Pull request closed without merging**
