### PR TITLE
Updated ripgrep to 0.10.0

### PR DESCRIPTION
**Pull request by skunkworker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This adds `PCRE2` support as an optional flag.

### CODE REVIEW

**Comment by lembacon** [comment]
We do not want to add new options to existing formulae, however `ripgrep` may always be built with `pcre2` since `pcre2` itself is not something huge and does not have any other dependencies.

Building with `pcre2` may provide `ripgrep` with some significant performance improvements in this particular case I think, then that is reasonable.

**Comment by lembacon** [comment]
Also, per `ripgrep`'s `README.md`:

> Enabling the PCRE2 feature works with a stable Rust compiler and will attempt to automatically find and link with your system's PCRE2 library via `pkg-config`. If one doesn't exist, then ripgrep will build PCRE2 from source using your system's C compiler and then statically link it into the final executable. Static linking can be forced even when there is an available PCRE2 system library by either building ripgrep with the MUSL target or by setting `PCRE2_SYS_STATIC=1`.

We need to add `depends_on "pkg-config" => :build`.

**Comment by mmoehring** [comment]
> We do not want to add new options to existing formulae, 

Anyone interested in a reason for this should take a look at https://github.com/Homebrew/homebrew-core/issues/31510.

**Comment by skunkworker** [comment]
Thanks for the feedback, I've closed this PR and created a new one with `pkg-config` and `pcre2` as dependent for build.

https://github.com/Homebrew/homebrew-core/pull/31899

**Pull request closed without merging**
