### PR TITLE
codespell 1.17.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Issue submitted upstream https://github.com/codespell-project/codespell/issues/1516

**Comment by dtrodrigues** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/55114

**Comment by chenrui333** [comment]
Generally, if the PR never got merged, you can also reuse this PR for updating.

**Comment by dtrodrigues** [comment]
Ahh, good to know. I closed it since I could just use `brew bump-formula-pr` on the newly-created `1.17.1` and the new PR name would match the commit/version.

**Pull request closed without merging**
