### PR TITLE
vermin: 0.6.0 (new formula)

### PR DESCRIPTION
**Pull request by JarryShaw**
`vermin` is a utility tool to detect the minimum Python versions needed to run code. (seems it's now notable enough)

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hi @JarryShaw this is a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by netromdk** [comment]
It is notable enough according to your own bot, with 75+ stars. So why are you closing it?

**Comment by JarryShaw** [comment]
As far as I know, Homebrew core repository defines”notable” as `<30 forks, <30 watchers and <75 stars` (cf. [#35633](https://github.com/Homebrew/homebrew-core/pull/35633#issuecomment-450820908) and the following [code](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L587)), where the requirements are made with `OR`. So… why not notable enough now?

btw: do please address somewhere on Homebrew documentations about the “notable” definition. It’s really irritating :(

**Comment by fxcoudert** [comment]
The bot gives us an "automatic" way to sort the most obvious cases. In the end, notability remains a subjective measure, I don't see how it could be otherwise. We look at other measures, like activity of the projet (number of issues / pull requests), number of contributors, etc.

Due to Homebrew's modular nature, it is very easy to host a tap and deliver your software. This has the added bonus of enabling analytics, so we then know in the future how widely used the formula is, and can base a decision to migrate to core.

**Comment by JarryShaw** [comment]
Okay, understood. Thanks for explanation :).

**Pull request closed without merging**
