### PR TITLE
cbmc 6.2.0

### PR DESCRIPTION
**Pull request by db-ci-cprover**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tautschnig** [comment]
Could the failing job please be re-run? The error message doesn't really make sense as that file is there, assuming the checkout was actually complete. (We have seen the same spurious failure in a PR against CBMC earlier today, and re-running the job fixed the problem.)

**Comment by carlocab** [comment]
Restarted.

**Comment by carlocab** [comment]
```
  CMake Error at jbmc/unit/CMakeLists.txt:13 (add_executable):
    Cannot find source file:
  
      /tmp/unit/unit_tests.cpp
  
    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
    .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
    .f95 .f03 .hip .ispc
  
  
  CMake Error at jbmc/unit/CMakeLists.txt:13 (add_executable):
    No SOURCES given to target: java-unit
```
Same error after re-run.

**Comment by tautschnig** [comment]
Investigating in https://github.com/diffblue/cbmc/pull/8435. Will likely need to re-release.

**Comment by chenrui333** [comment]
#190643

**Pull request closed without merging**
