### PR TITLE
xray 1.3.1 (new formula)

### PR DESCRIPTION
**Pull request by kidonng**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
On ARM:
```
Failed to start: main: failed to load config files: [/private/tmp/xray-test-20210227-95563-m1hur/config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /opt/homebrew/Cellar/xray/1.3.0/bin/geoip.dat: no such file or directory
```

**Comment by kidonng** [comment]
This should be fixed in XTLS/Xray-core#312. Should I add a patch after this get accepted or just wait for a new release?

**Comment by carlocab** [comment]
New formulae must build without patches, so we would need to wait for a new release.

**Comment by kidonng** [comment]
Is it good to go?

**Review by SMillerDev — DISMISSED** [review]
Thanks @kidonng  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
