### PR TITLE
codequery 0.19.0

### PR DESCRIPTION
**Pull request by ruben2020**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ruben2020** [comment]
Jenkins seems to be stuck on an old merge conflict, from a long time ago, which is already resolved.

**Comment by ilovezfs** [comment]
```
mv Formula/codequery.rb ~
git fetch origin
git reset --hard origin/master
mv ~/codequery.rb Formula
git commit -am "codequery 0.19.0"
git push -f
```

**Comment by ilovezfs** [comment]
@ruben2020 is that how you want it now?

**Comment by ruben2020** [comment]
@ilovezfs It seems to have merge problems from 0.17.0 - a long time ago, not my recent attempt.

```
Failed to merge in the changes.
Patch failed at 0001 CodeQuery 0.17.0
The copy of the patch that failed is found in:
   /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Error: codequery: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/codequery.rb:2: syntax error, unexpected <<
<<<<<<< 82ba1534f6c4ddc5dd5a62ede44ee879f6de53e4
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/codequery.rb:8: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/codequery.rb:14: syntax error, unexpected >>, expecting keyword_end
>>>>>>> CodeQuery 0.17.0
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/codequery.rb:14: no .<digit> floating literal anymore; put 0 before dot
>>>>>>> CodeQuery 0.17.0
```

**Comment by ilovezfs** [comment]
@ruben2020 right but I've fixed it for you. Looks we have :green_apple: now.

**Comment by ruben2020** [comment]
@ilovezfs Thanks. It seems to work now. Did you do something?

**Comment by ilovezfs** [comment]
Yes, I've force pushed to your master branch.

```
git fetch --all
git reset --hard @{u}
git rev-parse @
```
It should show af8221f67bf25bbb00bc358906a1b620abda9c9e

**Comment by ilovezfs** [comment]
Shipped! Thanks for the PR and the upgrade @ruben2020

**Comment by ruben2020** [comment]
@ilovezfs Thank you!

**Comment by ilovezfs** [comment]
You're welcome

**Pull request closed without merging**
