### PR TITLE
bats-support 0.2.0 (new formula)

### PR DESCRIPTION
**Pull request by kaos**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

bats-support is a supporting library providing common functions to test helper libraries written for Bats.
https://github.com/sstephenson/bats
https://github.com/ztombol/bats-support

### CODE REVIEW

**Comment by kaos** [comment]
The `bats-support` repo is not notable enough yet.. not much I can do about that myself.

**Comment by kaos** [comment]
@ztombol 

I have branches for `bats-assert` and `bats-file` too, once this is merged (probably pending a more "notable" project status..)

**Comment by DomT4** [comment]
Sorry this isn't near to being notable enough for submission here yet :cry:. If you wish to you could set up [your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) to support this yourself until it does meet those eligibility requirements. We'd be more than happy to re-review this at that point.

Thank you nonetheless for the submission to Homebrew :heart:.

**Comment by kaos** [comment]
Thanks for the info @DomT4 
I'll make a stab at hosting my own tap. That'll be an interesting adventure ;)

**Comment by kaos** [comment]
It turned out nicely: https://github.com/kaos/homebrew-shell

@ztombol there's now a brew tap where you can install bats-support and friends for Mac users ;)

**Comment by ztombol** [comment]
@kaos Nice! More package manager support! Can you add installation instructions to `bats-docs` too? Thanks a lot! :smile:

**Pull request closed without merging**
