### PR TITLE
terraform 0.12.0

### PR DESCRIPTION
**Pull request by andyshinn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by ndobbs** [comment]
Anxiously awaiting this to be released.

**Comment by barendb** [comment]
Waiting too....

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by zbeekman** [comment]
what the heck, where'd the testbot commit go?

@BrewTestBot test this please

**Comment by chenrui333** [comment]
Does terraform 0.12 backward compatible? If not, we might need to create separate formula, most of my team is still using 0.11 though.

**Comment by ndobbs** [comment]
> Is terraform 0.12 backward compatible? If not, we might need to create separate formula, most of my team is still using 0.11 though.
> 
> You can `brew pin` it, and/or open up a new PR for another version if it's truly needed.

I'm just going to install the binary, most of us have been following the releases pretty closely for over a year now. All of my code is ported over to `0.12.0`. The upgrade is pretty seamless, the `0.12upgrade` command does all of the hand holding for you. There are a few providers out there that are not compatible but I'm of the opinion that the formula should follow the stable release cycle of the upstream product. 

This release is so major I understand why people would be hesitant to upgrade but at the same time the new features are so substantial its really not worth waiting any longer.

**Comment by zbeekman** [comment]
FYI, the only thing holding up merging this is some funny business with our workflow.

@BrewTestBot test this please

**Comment by chenrui333** [comment]
Yeah, I kind of agree as well! It is indeed big impact though. Cannot wait about the community feedback on this now.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
