### PR TITLE
xz: revert to 5.4.6

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
A backdoor has been discovered in the tarballs for v5.6.0 and v5.6.1 of `xz`. This PR reverts our package to the last clean version. More details: https://www.openwall.com/lists/oss-security/2024/03/29/4

Credit to @alex for raising this issue internally.

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
https://www.openwall.com/lists/oss-security/2024/03/29/4

> == Affected Systems ==
> 
> The attached de-obfuscated script is invoked first after configure, where it
> decides whether to modify the build process to inject the code.
> 
> These conditions include targeting only x86-64 linux:
>     if ! (echo "$build" | grep -Eq "^x86_64" > /dev/null 2>&1) && (echo "$build" | grep -Eq "linux-gnu$" > /dev/null 2>&1);then
> 
> Building with gcc and the gnu linker
>     if test "x$GCC" != 'xyes' > /dev/null 2>&1;then
>     exit 0
>     fi
>     if test "x$CC" != 'xgcc' > /dev/null 2>&1;then
>     exit 0
>     fi
>     LDv=$LD" -v"
>     if ! $LDv 2>&1 | grep -qs 'GNU ld' > /dev/null 2>&1;then
>     exit 0
> 
> Running as part of a debian or RPM package build:
>     if test -f "$srcdir/debian/rules" || test "x$RPM_ARCH" = "xx86_64";then
> 
> Particularly the latter is likely aimed at making it harder to reproduce the
> issue for investigators.
> 
> 
> Due to the working of the injected code (see below), it is likely the backdoor
> can only work on glibc based systems.
> 
> 
> Luckily xz 5.6.0 and 5.6.1 have not yet widely been integrated by linux
> distributions, and where they have, mostly in pre-release versions.


Looks like that Homebrew users (both macOS and Linux, both Intel and ARM) are unlikely affected?

**Comment by p-linnane** [comment]
> Looks like that Homebrew users (both macOS and Linux, both Intel and ARM) are unlikely affected?

Correct. Though we do not appear to be affected, this revert was done out of an abundance of caution.

**Comment by AkihiroSuda** [comment]
The malicious (or just hijacked) account seems to have been making commits since xz v5.3.3alpha https://github.com/tukaani-project/xz/commits/master/?author=JiaT75&after=af071ef7702debef4f1d324616a0137a5001c14c+419

Not sure if v5.4.6 is trustable

**Comment by p-linnane** [comment]
This situation is still unfolding, and we are continuing to monitor. If evidence emerges that older releases have malicious code, we will figure out which type of action to take.

**Comment by LittleSound** [comment]
How do I update my homebrew and downgrade my dependencies that managed by homebrew to roll back to the version with xz@5.4.6?

**Comment by hakusaro** [comment]
@LittleSound `brew upgrade` should automatically roll you back to 5.4.6.

**Comment by praseodym** [comment]
I was curious to know how upgrading to an older version works internally. Here's how I understand it: this PR adds `version_scheme 1`. [version_scheme](https://docs.brew.sh/Formula-Cookbook#version-scheme-changes) is used to signify a new version scheme, which is useful when a project decides to e.g. create a release v1.0.0 after v20240330. Because 20240330 > 1.0.0 the new version would never be installed as an upgrade, so we need to tell Homebrew that this new v1.0.0 versioning scheme (`version_scheme 1`) should not be compared to existing versions (v20240330) in the older versioning scheme (implicitly `version_scheme 0`).

In this case, `version_scheme` is used to tell that this v5.4.6 is using a new versioning scheme and should not be compared v5.6.1 under the old versioning scheme. Homebrew will then upgrade any existing version to v5.4.6.

**Comment by slabstone** [comment]
Why is this reverted to 5.4.6 and not to 5.4.1?

5.4.1 was the last release made by original maintainer/author Lasse Collin.
5.4.6 was released by Jia Tan, and I think it's only logical to assume that _any_ releases made by Jia Tan are compromised.

**Comment by slabstone** [comment]
`homepage` is also not okay because `xz.tukaani.org` is owned by Jia Tan and while it is taken down by GitHub for now, it might as well be compromised as everything else.
This can also be fixed by reverting to 5.4.1 however.

**Comment by p-linnane** [comment]
@slabstone See https://github.com/orgs/Homebrew/discussions/5243#discussioncomment-8965956 for discussion on why the homepage hasn't been updated yet.

There isn't any evidence of needing to roll back to 5.4.1 currently. Most major distributors are using 5.4.6. We are continuing to monitor the situation and will make other necessary changes as they arise.

**Pull request merged**
