### PR TITLE
waffle: switch to meson, since cmake is deprecated upstream

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Can we also try to remove -D_DARWIN_C_SOURCE ?

See https://gitlab.freedesktop.org/mesa/waffle/-/issues/115#note_2037131

**Comment by iMichka** [comment]
And thanks for trying to update this: had no time to answer upstream and work on it.

**Comment by yurikoles** [comment]
> Can we also try to remove -D_DARWIN_C_SOURCE ?
> 
> See https://gitlab.freedesktop.org/mesa/waffle/-/issues/115#note_2037131

No, switching to `meson` doesn't automagically fix this issue. I sent another [MR](https://gitlab.freedesktop.org/mesa/waffle/-/merge_requests/129) with a fix.

**Review by iMichka — APPROVED** [review]
Thanks, makes sense. Let's ship this first change then

**Pull request merged**
