### PR TITLE
zimg: fix download sha256

### PR DESCRIPTION
**Pull request by janosorcsik**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Can you check with upstream if this was an intentional retag & if it was what changed? Thanks!

**Comment by ilovezfs** [comment]
There's a 2.1 branch so this isn't terribly surprising https://github.com/sekrit-twc/zimg/commits/v2.1

**Comment by ilovezfs** [comment]
https://github.com/sekrit-twc/zimg/issues/49

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `zimg: fix sha256`. This format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md). Thanks!

**Pull request merged**
