### PR TITLE
awscli 2.0.12

### PR DESCRIPTION
**Pull request by shigemk2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failure
```
==> brew test --verbose awscli
==> FAILED
Testing awscli
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200508-18969-o743aa.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awscli.rb --verbose
==> /usr/local/Cellar/awscli/2.0.12/bin/aws help
Error: awscli: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - /usr/local/Cellar/awscli/2.0.12/bin/aws
```

**Comment by issyl0** [comment]
I was curious to try this out locally...

```
issyl0 at ophiuchus in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on awscli-2.0.12
➜ aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
ImportError: No module named awscli.clidriver
```

**Comment by shigemk2** [comment]
I am not sure why, but the 2.0.12's shebang in `aws` file is `#!python`.

**Comment by SMillerDev** [comment]
Could you report it upstream?

**Comment by jwatzman** [comment]
> I am not sure why, but the 2.0.12's shebang in aws file is #!python.

FWIW I am seeing the same thing on a fresh install of 2.0.10 from Homebrew, so this may not be a new issue in this PR. I wonder if some other python tooling update elsewhere broke it?

**Comment by shigemk2** [comment]
I am not sure wny, but the testing is SUCCESS when updating upstream.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @shigemk2  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
