### PR TITLE
ppsspp 1.15.2

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ppsspp:
    * Unexpected universal binaries were found.
      The offending files are:
        /opt/homebrew/Cellar/ppsspp/1.15/PPSSPPSDL.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2
```

**Comment by alebcay** [comment]
Looks like upstream is starting to use the framework bundle for SDL2 now on macOS. Not sure how we might replace this with a brewed dep, since we don't build a framework bundle for `sdl2` currently.

**Comment by carlocab** [comment]
We could probably still symlink `SDL2.framework/Versions/A/SDL2` to `libSDL2.dylib` TBH. But we should probably see if we can skip building the SDL2 framework entirely.

**Comment by alebcay** [comment]
There is a flag to use system SDL, but it was disabled specifically on macOS in commit https://github.com/hrydgard/ppsspp/commit/5d028cb00449fe994dc3e5eb2579087d05c22d13 which is part of 1.15.

**Comment by p-linnane** [comment]
This is also available as a cask, so if we can't find a good way to handle this that can be a remaining option.

**Comment by alebcay** [comment]
> This is also available as a cask, so if we can't find a good way to handle this that can be a remaining option.

See also previous discussion at https://github.com/Homebrew/homebrew-core/pull/88704. I do think that if we prefer to emphasize the cask, maybe it's still possible to keep the formula as Linux-only to continue Linux support, where they can't use casks.

Not sure if that will be a poor user experience due to someone trying `brew install ppsspp` on macOS and getting some message about it only being available for Linux.

**Comment by p-linnane** [comment]
@hrydgard Sorry for the ping, but would you mind weighing in here please?

**Comment by hrydgard** [comment]
Sorry all, I changed around some stuff to make my life easier and reduce the paths I had to test while upgrading our bundled SDL and improving .app packaging. Didn't realize it'd break things for homebrew.

I'll happily take a patch that partially reverts my change to keep things working (as long as it doesn't break the bundled path), or I'll try to do it myself but I don't know how to test locally that the configuration you're using will work for homebrew.

**Comment by p-linnane** [comment]
Awesome work @alebcay, thank you!

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
