### PR TITLE
noir 0.11.0

### PR DESCRIPTION
**Pull request by hahwul**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## What's Changed
- 👋🏼 Add new detectors and analyzers
   - Ruby Hanami
   - Elixir Phoenix
   - Crystal Lucky
- 🍪 Add cookie parameter type
- 🖥️ Improve logger
   - It expresses the parameters that exist in the endpoint more beautifully.
   - Debug logs have been added to many more.
- 🏁 Enhance detector performance
   - The existing Fiber-based parallel processing has been changed to Fiber+Channel structure. 
   - As a result, it has increased stability while maintaining the same speed.
   - Add `--concurrency` flag
- 🔭 Improve testcodes
- 🐞 Fixed bugs

**Full Changelog**: https://github.com/noir-cr/noir/compare/v0.10.0...v0.11.0</pre>
</details>

### CODE REVIEW

**Comment by hahwul** [comment]
- Release note: https://github.com/noir-cr/noir/releases/tag/v0.11.0
- Tap Formula: https://github.com/noir-cr/homebrew-noir/blob/main/Formula/noir.rb

**Comment by p-linnane** [comment]
Please squash your commits into one with the message `noir 0.11.0`. Thanks.

**Comment by hahwul** [comment]
@p-linnane I've finished the task. Appreciate it :D

**Review by p-linnane — APPROVED** [review]
Thanks for your first contribution @hahwul!

**Pull request merged**
