### PR TITLE
datree: test

### PR DESCRIPTION
**Pull request by chenrui333**
test PR to reproduce datreeio/datree#160

relates to #84566

### CODE REVIEW

**Comment by branchvincent** [comment]
so they pass, and this is what I observe locally:

```console
$ git -C $(brew --repo) checkout 6d2a2960fcdf5550fda796c67e283c98376ef607
$ git -C $(brew --repo homebrew/core) checkout d7ba094baa2de34a34e2fcbbb08ca7371955bfb1
$ brew install datree
$ brew test datree
==> Testing datree
==> /usr/local/Cellar/datree/0.9.0/bin/datree test /private/tmp/datree-test-20210902-40849-sas8y0/invalidK8sSchema.yaml 2>&1
==> /usr/local/Cellar/datree/0.9.0/bin/datree version
$ datree version
fatal error: unexpected signal during runtime execution
...
```

It has something to do with the environment in the test runner that does not reproduce this. I can even put a `system "false"` in the test block, run `brew test --debug datree`, drop into a shell and observe:

```console
$ datree version
0.9.0
```

**Comment by chenrui333** [comment]
Agree, looks like the CI did not catch anything with [this commit](https://github.com/Homebrew/homebrew-core/commit/995680d7d187022c7be79a5b81d6038de2950de1), I have seen the same issue with `datree` and `datree version`

**Comment by branchvincent** [comment]
got it, it's `TERM=dumb` that does not repro this:

```console
$ env -i PATH="$PATH" TERM="dumb" datree version
0.9.0
$ env -i PATH="$PATH" datree version
fatal error: unexpected signal during runtime execution
```

**Comment by chenrui333** [comment]
Nice find. That is why CI failed catching it!

**Comment by branchvincent** [comment]
given that, i can't think of how we could have realistically caught this. can you?

**Comment by chenrui333** [comment]
yeah, I dont have any further idea, I am gonna close this PR for now. (feel free to reopen if you feel fit)

**Pull request closed without merging**
