### PR TITLE
balena-cli 11.32.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
It can't find bottles, I'm rerunning the test jobs

**Comment by chenrui333** [comment]
Just did the rebase. :)

**Comment by SMillerDev** [comment]
okay, I guess I'm not because that's not an option.

**Comment by Bo98** [comment]
> Error: The newest workflow run for #54050 is still in progress!

No it's not.

**Comment by Bo98** [comment]
There was a "cancel workflow" button still, so I've clicked that.

**Comment by Bo98** [comment]
Go away @BrewTestBot

**Pull request closed without merging**
