### PR TITLE
dvc 1.7.0

### PR DESCRIPTION
**Pull request by efiop**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by efiop** [comment]
Looks like the same error as in https://github.com/Homebrew/homebrew-core/pull/60454

**Comment by dtrodrigues** [comment]
@homebrew/core - there's a few python formulae including this one which indirectly require the poetry python tool to build one of their dependencies or one of their dependency's dependencies, but poetry does not build with `pip install poetry --no-binary :all:`. This has prevented upgrades in some cases and there are other formulae which have tried to get into `homebrew-core` and failed due to this.

The root issue is https://github.com/python-poetry/poetry/issues/1975, but issues directly affecting existing formulae are 
https://github.com/Homebrew/homebrew-core/pull/60173
https://github.com/Homebrew/homebrew-core/pull/59966
https://github.com/Homebrew/homebrew-core/pull/59954
and formulae trying get into Homebrew:
https://github.com/Ciphey/Ciphey/issues/197#issuecomment-671027503
https://github.com/commitizen-tools/commitizen/issues/256

The workaround being used here for `dvc` is installing poetry not from source. `jrnl` removes `pyproject.toml` prior to building as a workaround. This may be better suited to discuss outside of this issue as well as general support for PEP 517/518, but as of now, there are several packages that are stuck.

**Comment by SMillerDev** [comment]
I'd say that if we can get away with removing a file that option should be used as a workaround over downloading binaries. 

Is there an anticipated timeline for the poetry version that'll stop breaking?

**Comment by efiop** [comment]
Hm, did I get it right that removing pyproject.toml from dvc itself would solve this issue? That's a bit unobvious. Let me give it a try...

**Comment by efiop** [comment]
Nope, I guess I misunderstood the advice. So it meant that we need to remove pyproject.toml from each dependency that uses poetry. In that case, unless I'm missing something, it seems like a lot of effort. Would rather keep already existing --only-binary workarounds, and then just get rid of them once the poetry fix is out. Let me know if it is acceptable or not, I'll happily comply with the requirements in any case, just care about merging this ASAP, as our users are waiting for the release :slightly_smiling_face:

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @efiop  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
