### PR TITLE
planck 2.28.0

### PR DESCRIPTION
**Pull request by mfikes**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>### Changed
- Update to ClojureScript 1.11.132 ([#1102](https://github.com/planck-repl/planck/issues/1102))
</pre>
</details>

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@mfikes you base branch is outdated, you need to run `brew update` before filing the PR next time.

**Comment by chenrui333** [comment]
you also have to use rebase rather than merge unfortunately, should be good now.

**Comment by mfikes** [comment]
Thanks for your help @chenrui333 ! It has been a couple of years, and I've now updated my instructions at https://github.com/planck-repl/planck/wiki/Release-Checklist#homebrew

**Comment by chenrui333** [comment]
no worries

**Comment by SMillerDev** [comment]
Since it's a GitHub repo it might be easiest to use a GitHub action to automatically publish the release. I know former maintainer dawiddd made one

**Comment by mfikes** [comment]
I believe I've fixed the slow build problem. (An optional upstream build cache file had not yet been cached.) So, the `long build` tag can likely be removed and the build tried again.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
