### PR TITLE
ballerina 0.95.8 (new formula)

### PR DESCRIPTION
**Pull request by rasika**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rasika** [comment]
As i understood tests has failed due to JDK9. Current version of the ballerina doesn't support jdk-9.0.1.jdk due to endorsed libraries support dropped in JDK9+. How do I restrict JDK9+?

**Comment by ilovezfs** [comment]
Do you mean restrict to 8?

**Comment by rasika** [comment]
Yes please.

**Comment by ilovezfs** [comment]
`depends_on :java => "1.8"`

However, this isn't permitted for new formulae, so I'm afraid we'll need to pass on this PR for the time being. You may want to host it in [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap), though.

Thanks for the PR nonetheless @rasika!

**Comment by rasika** [comment]
In fact; if we remove the dependency in the future, any chance of passing the PR?

**Comment by ilovezfs** [comment]
I don't think there'll be a problem if it can use Java 9.

**Pull request closed without merging**
