### PR TITLE
various formulae: avoid pipes in `shell_output`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This produces better logs and more exit code checks.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please audit for this too (doesn't have to be before merging this)

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
> Please audit for this too (doesn't have to be before merging this)

There are a handful I don't think I can get rid of, though. For example, I don't know how to replace piping `yes` into some other command.

**Comment by carlocab** [comment]
Network error on Linux:
```
  curl: (7) Failed to connect to invisible-mirror.net port 443: Connection timed out
```
The tarball failed to download, so everything else failed. Would probably go away on a re-run, but doesn't seem worth the few hours of CI time. Thoughts, @SMillerDev?

**Comment by SMillerDev** [comment]
F it, we'll do it live!

Yeah, they're all test changes so I think we can safely merge it if you're confident about it.

**Comment by carlocab** [comment]
Will merge then will run `mawk` again in a separate PR to check.

**Comment by carlocab** [comment]
All green: #89688

**Pull request closed without merging**
