### PR TITLE
vowpal-wabbit 8.9.2

### PR DESCRIPTION
**Pull request by lalo**
Based on https://github.com/Homebrew/homebrew-core/pull/70445

- 8.9.1 had a bug surfaced by the homebrew tests, so thanks for that. We've fixed it and bump the version to 8.9.2
- Added license

### CODE REVIEW

**Comment by lalo** [comment]
Based on https://github.com/Homebrew/homebrew-core/pull/70445

**Review by carlocab — APPROVED** [review]
Thanks, @lalo.

**Comment by lalo** [comment]
@carlocab looks like some other process failed, not sure why the CI passed and this one failed. What's the main difference between those runs? I do not have a lot of context here.

**Comment by carlocab** [comment]
[Fails](https://github.com/Homebrew/homebrew-core/runs/2025409460?check_suite_focus=true#step:6:231) to build on ARM with error
```
error: unknown FP unit 'sse'
```

**Comment by lalo** [comment]
VW doesn't support ARM currently, is there a way to disable it?

We're working on adding ARM support soon.

**Comment by carlocab** [comment]
It's already disabled; I just started an ARM build to see if it would work. We can wait till you support it. The bottles for Intel macOS are already uploaded.

**Pull request closed without merging**
