### PR TITLE
jumanpp 1.02

### PR DESCRIPTION
**Pull request by ymyzk**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Bottle upload fails: `Error: jumanpp-1.02.yosemite.bottle.tar.gz is already published.`

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Same error this time: `jumanpp-1.02.yosemite.bottle.tar.gz is already published`

**Comment by ilovezfs** [comment]
:green_apple: now

**Comment by fxcoudert** [comment]
Thanks to whoever acted behind the scenes :)
I'm merging this one now

**Comment by fxcoudert** [comment]
Thanks @ymyzk for your contribution to Homebrew!

**Pull request closed without merging**
