### PR TITLE
mikutter 4.1.2

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> FAILED
==> Testing mikutter
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201003-81146-cnm1.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mikutter.rb --verbose
==> /usr/local/Cellar/mikutter/4.1.2/bin/mikutter plugin_depends /private/tmp/mikutter-test-20201003-81147-szea70/.mikutter/plugin/test_plugin/test_plugin.rb
/usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer/extend.rb:56:in `block in extended': uninitialized constant Delayer::Extend::Set (NameError)
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer/extend.rb:47:in `class_eval'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer/extend.rb:47:in `extended'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer/extend.rb:18:in `extend'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer/extend.rb:18:in `block in included'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer/extend.rb:17:in `class_eval'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer/extend.rb:17:in `included'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer.rb:24:in `include'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer.rb:24:in `block in generate_class'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer.rb:23:in `initialize'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer.rb:23:in `new'
	from /usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor/ruby/2.7.0/gems/delayer-1.1.2/lib/delayer.rb:23:in `generate_class'
	from /usr/local/Cellar/mikutter/4.1.2/libexec/core/boot/delayer.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/local/Cellar/mikutter/4.1.2/libexec/core/boot/shell/plugin_depends.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/local/Cellar/mikutter/4.1.2/libexec/core/boot/option.rb:72:in `block in parse'
	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/optparse.rb:1093:in `initialize'
	from /usr/local/Cellar/mikutter/4.1.2/libexec/core/boot/option.rb:24:in `new'
	from /usr/local/Cellar/mikutter/4.1.2/libexec/core/boot/option.rb:24:in `parse'
	from /usr/local/Cellar/mikutter/4.1.2/libexec/mikutter.rb:17:in `<main>'
Error: mikutter: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/mikutter/4.1.2/bin/mikutter plugin_depends /private/tmp/mikutter-test-20201003-81147-szea70/.mikutter/plugin/test_plugin/test_plugin.rb

```

**Comment by alebcay** [comment]
I've seen this error with the past few updates for `mikutter`, it seems to be caused by the updates for `delayer` and `delayer-deferred`. Rolling back those bumps (and whatever version bumps depend on those) should fix that.

**Comment by chenrui333** [comment]
Oh, I see, thanks for the direction. Sounds like we can put some gemfile update to the upstream as well :)

**Comment by alebcay** [comment]
Yes, in the past I've also tried updating the `gtk` gem (and all dependencies/reverse dependencies of it) and somehow everything also broke. Not really sure why, but it would probably be nice for upstream to update that at some point.

**Comment by chenrui333** [comment]
The dependencies are all derived from the gemfile though.

**Comment by chenrui333** [comment]
trying to file some PR, but it looks that is only a mirror (`https://github.com/mikutter/mikutter`)

**Comment by chenrui333** [comment]
delayer version is specified in the gemfile, I cannot believe it.
```
==> bundle install --local --path=/usr/local/Cellar/mikutter/4.1.2/lib/mikutter/vendor
Some gems seem to be missing from your vendor/cache directory.
Could not find gem 'delayer (>= 1.1.2, < 2.0)' in any of the gem sources listed
in your Gemfile or in gems cached in vendor/cache.
```

**Comment by chenrui333** [comment]
waiting for upstream's comments before reopening this again.

**Pull request closed without merging**
