### PR TITLE
mpd, minidlna: rebuild bottles

### PR DESCRIPTION
**Pull request by carlocab**
The `mpd` and `minidlna` Catalina and Big Sur bottles have gone missing, causing CI failures in various PRs (e.g. #68937).

### CODE REVIEW

**Comment by carlocab** [comment]
Tests are failing because of `localhost` issues.

**Comment by carlocab** [comment]
Ping @gromgit, I feel like you might have a better idea of what's going wrong with these tests

**Comment by gromgit** [comment]
Both formulae test fine on my Big Sur, after increasing `sleep` to 20 seconds.

**Comment by carlocab** [comment]
I always forget to check the `sleep` commands. Hopefully, I'll remember next time...

**Comment by gromgit** [comment]
> I always forget to check the `sleep` commands. Hopefully, I'll remember next time...

Actually, since both daemons seem to be started in a way that prints matchable output, it's probably better to replace `fork`/`sleep` with `IO.popen`, then [`expect`](https://ruby-doc.org/stdlib-2.7.2/libdoc/expect/rdoc/IO.html) specific progress strings from the daemon output before proceeding with client connection. For `mpd`, the final line on daemon startup seems to be:
```
output: Successfully detected a osx audio device
```
while `minidnla` seems to spit out:
```
debug: Initial file scan completed
```

**Comment by carlocab** [comment]
That's a good point... Do you want to open another PR for that? Probably better to merge this one now, since there are missing bottles.

**Comment by gromgit** [comment]
Yeah, I'll take care of that later.

**Pull request closed without merging**
