### PR TITLE
kapacitor: fix build for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/runs/3158668157?check_suite_focus=true
```
go: downloading sigs.k8s.io/yaml v1.2.0
# pkg-config --cflags  -- flux
Started pkg-config	{"arg0": "/tmp/kapacitor-20210726-8467-1qvlnnn/bootstrap/pkg-config", "args": ["--cflags", "--", "flux"]}
Could not find pkg-config executable	{"path": "/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/go/bin:/home/linuxbrew/.linuxbrew/opt/rust/bin:/usr/bin:/bin:/usr/sbin:/sbin", "error": "exec: \"pkg-config\": executable file not found in $PATH"}
pkg-config: exit status 1

```

### CODE REVIEW

**Comment by cho-m** [comment]
Not sure why this didn't get tested during Rust 1.54 bump, but seems to not build due to the old flux dependency in go.mod.

**Comment by danielnachun** [comment]
Has upstream been notified that they need to update `flux`?  I'm not sure if we were doing that for other formulae that had this issue.

**Comment by cho-m** [comment]
We can open an issue/PR to request an update, though the upstream org (InfluxData) is the maintainer of both projects, so I would hope they are already aware of it.

Not sure if we have examples in Go, but we do modify Rust projects Cargo.lock dependencies when necessary. Though, I am not sure if we have a standard way to go about this.

The only options here to fix build would be to modify go.mod to either a much newer version (v0.124 thru v0.126), or just patch the specific problem like shown.

**Comment by SMillerDev** [comment]
We should really create an issue upstream too if we're going to patch this.

**Comment by cho-m** [comment]
I'll open an issue upstream as I didn't see anything specific to `flux`

However, I did find that upstream is looking into locking Rust version, e.g. https://github.com/influxdata/kapacitor/issues/2600, which may mean they aren't going to support newer `flux` (Rust 1.54) for now.

Not sure if we would prefer the workaround of swapping `rust` with `rustup-init` + previous stable Rust (1.53.x).

**Comment by cho-m** [comment]
Upstream issue https://github.com/influxdata/kapacitor/issues/2612
I'll add in a comment.

Now, the question is whether to use:
- current patch on `flux`
- switch `rust` to `rustup-init` and do something like
    ```rb
        system Formula["rustup-init"].bin/"rustup-init", "-qy", "--no-modify-path",
               "--default-toolchain", "stable-1.53.0", "--profile", "minimal"
        ENV.prepend_path PATH, HOMEBREW_CACHE/"cargo_cache/bin"
    ```

**Review by SMillerDev — DISMISSED** [review]
I don't like it, but I think it's the best of two evils.

**Comment by cho-m** [comment]
Actually didn't hit an issue after rebase, so should be fine to merge

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
