### PR TITLE
pueue 0.2.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
*sh-completion are generated by a separate command now: https://github.com/Nukesor/pueue/blob/v0.2.1/README.md#shell-completion-files

**Comment by chenrui333** [comment]
kind of the similar story as #52022. :)

**Comment by chenrui333** [comment]
This PR ref, #52058 is better :)

**Comment by Bo98** [comment]
It's probably just a case of invoking `system "./build_completions.sh"` before you install the completions

**Pull request closed without merging**
