### PR TITLE
chapel: don't install chpldoc command

### PR DESCRIPTION
**Pull request by awallace-cray**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
      This is open https://github.com/Homebrew/homebrew-core/pull/26225,
      but I have asked for it to be closed https://github.com/Homebrew/homebrew-core/pull/26225#issuecomment-379369000
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
From https://github.com/chapel-lang/chapel/issues/8979

> 2018-04-06 proposed change to Homebrew chapel formula
> 
> Homebrew/homebrew-core#26263 - pending Homebrew maintainers
> 
> Creates "revision 1" of chapel-1.17.0 in Homebrew. The only difference is to omit
> make chpldoc' andmake test-venv`.
> That way, there's no chpldoc command in /usr/local/bin, so it cannot break.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
@awallace-cray can you elaborate on why this change is needed and what it does?

**Comment by ilovezfs** [comment]
@awallace-cray also please note https://github.com/Homebrew/homebrew-core/issues/26287

**Comment by awallace-cray** [comment]
@ilovezfs - Glad to explain! This change is not urgent for us. 

The short version : since we discovered Python virtual env's "chpldoc" and "test-venv" were missing from the chapel 1.17.0 bottles created on 04/05, we decided that the related Chapel features were just not important enough to our likely end-user, to justify adding `depends_on "python@2"` to everyone's Homebrew chapel installs. As it is, however, anyone who installs chapel 1.17.0 and tries to run chpldoc (the exe script still gets installed in /usr/local/bin) will get an error message they probably won't understand. So, this very small change just removes `make chpldoc` and `make test-venv` from our Homebrew build, to create chapel 1.17.0 rev 1.  (Slightly) better for chpldoc to be missing entirely, than be broken by the missing Python venv. 

Long version, much of which you have already seen elsewhere.

While preparing our regular twice-a-year Chapel release, we updated chapel's Homebrew formula to version 1.17.0 in the usual way, with https://github.com/Homebrew/homebrew-core/pull/26218. Everything succeeded as far as we knew, and the chapel formula was successfully updated, bottles and all, on 04/05. 

When I attempted to verify that the newly updated formula actually worked right, I found out that the installed "chpldoc" exe was broken- it throws an error message when you try to run it, and the message is not meaningful without knowing the internals. 

Investigating, I found that two Python virtual env's were missing from the new sierra bottle. Those venv's should have been created by the `make chpldoc` and `make test-venv` commands in chapel's Homebrew formula- the commands this PR wants to remove for chapel 1.17.0 rev 1. 

The reason those venv's were missing from the chapel 1.17.0 sierra bottle was the PyPI brownout, silently breaking "easy_install" on your bottle-building machine. We were already familiar with this problem on older, non-Mac systems - https://github.com/pypa/packaging-problems/issues/130.  As of release day, however, I still thought the Mac OS was not affected. 

When I wrote https://github.com/Homebrew/homebrew-core/pull/26218#issuecomment-379071654, I was hoping this would be quick and easy to correct, and when @DomT4 volunteered https://github.com/Homebrew/homebrew-core/pull/26263, I was enthusiastic. I was already thinking of using Homebrew's Python 2 in some way to fix chpldoc, and DomT4 just saved me the trouble of figuring out the formula changes. 

However, on reflection, I (and the chapel team) decided that the Chapel features supported by the missing Python venv's - "chpldoc" and an internal test harness - were just not important enough to our likely end-users, to justify adding `depends_on "python@2"` to their Homebrew installs. 

Not that there's anything wrong with Homebrew's python@2, nor would I argue with your idea to use it as a general solution to the PyPI situation. For Chapel's needs, however, it seemed a heavier change than we want to impose on our end-users, at least for now.  That opinion could change any time. 

Not only that, @ben-albrecht is investigating a change to replace easy_install from Python 2 with a newer "pip" version, in Chapel.  No decision yet. 

Hope that helps.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for the PR @awallace-cray! Shipped.

**Comment by awallace-cray** [comment]
Never mind. My mistake. brew install works as-is.

**Pull request closed without merging**
