### PR TITLE
envoy@1.18 1.18.4

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
weird... same thing here, though on a different os matrix cell cc @Ryan

```
INFO: Analyzed target //source/exe:envoy-static (810 packages loaded, 42835 targets configured).
84
INFO: Found 1 target...
85
[0 / 77] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
86
ERROR: <builtin>: Failed to determine workspace status: Process exited with status 1
87
fatal: not a git repository (or any of the parent directories): .git
88
Target //source/exe:envoy-static failed to build
```

**Comment by cho-m** [comment]
We haven't gotten around to fixing `envoy@1.18` build for Linux, so failure is first CI runner that starts building (either 10.15 or 11).

I had only recently bottled `envoy` on Linux (#82077).

**Review by carlocab — DISMISSED** [review]
Let's fix the comment separately.

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]
Oops; GitHub registered me as the owner because I uploaded this manually when the formula was first added.

I've inherited access settings from Homebrew/core, so this should work for @BrewTestBot now.

**Pull request closed without merging**
