### PR TITLE
HTTPie 2.2.0

### PR DESCRIPTION
**Pull request by jkbrzt**
https://github.com/jakubroztocil/httpie/releases/tag/2.2.0

---
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@jakubroztocil can you squash the commits, change looks good.

**Comment by jakubroztocil** [comment]
Thanks. Could you use the `Squash and merge` button? I’m afk.

**Comment by SMillerDev** [comment]
Unfortunately using that breaks our automation

**Comment by jakubroztocil** [comment]
Good to know! I’ll squash then.

**Comment by jakubroztocil** [comment]
@SMillerDev @chenrui333 I’ve created a new PR #56552.

It would be good to document the 1-commit/PR requirement. Off-GitHub squashing is quite a challenge with a repo of this magnitude. 😅

**Pull request closed without merging**
