### PR TITLE
psalm 5.9.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
The build seems got stuck?

**Comment by carlocab** [comment]
Yea, maintainers are not allowed to edit the PR. @derrabus, can you enable that for future PRs? Our new merge flow requires it.

**Comment by derrabus** [comment]
The settings look okay to me. 😓 

Bildschirmfoto 2023-03-30 um 20 22 10

**Comment by carlocab** [comment]
Hmm, ok, not that then. I'll look into it.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Not really sure what went wrong there, but hopefully it doesn't happen again. Seems to work fine in other PRs.

**Comment by derrabus** [comment]
Ah, PRs are actually flagged as "merged" now. Nice. ✌🏻

**Comment by carlocab** [comment]
Yes, we push bottle commits directly to PR branches instead of rebasing them onto `master`.

**Pull request merged**
