### PR TITLE
global: fix head build deps

### PR DESCRIPTION
**Pull request by lucafavatella**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Please refer to the commit message for details.

### CODE REVIEW

**Comment by DomT4** [comment]
Can you elaborate on which OS X version you tested this against to discover the initial version?

The `flex` & `bison` on newer OS X versions is, compared to a fair amount of system utilities, fairly modern, and most things can tend to use those to build with.

**Comment by lucafavatella** [comment]
I tested on Travis CI for a clean environment and reproducibility, specifically image `xcode7.1` that is OS X 10.10 with CLT 7.1.1 ([ref](https://docs.travis-ci.com/user/osx-ci-environment#OS-X-Version)).

----

Instead locally in my laptop (that is not where I tested) I have Yosemite with a slightly more up-to-date [version of the CLT](http://apple.stackexchange.com/questions/180957/determine-xcode-command-line-tools-version/181994#181994):
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F1909
```
```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables

package-id: com.apple.pkg.CLTools_Executables
version: 7.2.0.0.1.1447826929
volume: /
location: /
install-time: 1461506844
groups: com.apple.FindSystemFiles.pkg-group com.apple.DevToolsBoth.pkg-group com.apple.DevToolsNonRelocatableShared.pkg-group
```

---

It looks to me that the Travis image I used is quite close to my laptop - considering the laptop is kept quite up-to-date. Hence the PR looks meaningful to me.

Please advise on how to proceed.

**Comment by DomT4** [comment]
Can reproduce on the latest stable OS X version, so I guess this is alright as-is.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/afd7811ad1904e689afac918c6e5f08a2247dd0b. Thank you for your contribution to Homebrew @lucafavatella; we appreciate it! :smiley_cat:

**Pull request merged**
