### PR TITLE
kyma-cli 1.21.1

### PR DESCRIPTION
**Pull request by suleymanakbas91**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why does it depend on macOS catalina?

**Comment by suleymanakbas91** [comment]
@SMillerDev  We have a dependency on Terraform v1.12 that has the bug https://github.com/hashicorp/terraform/issues/24287 which is causing a problem with Mojave. This is solved in Terraform v1.13, but we cannot upgrade to that because that version has a dependency on an old version of Kubernetes Go client.

**Comment by suleymanakbas91** [comment]
It does not require the terraform binary. I'm referring to the terraform Go client. It's a code dependency.

**Review by SMillerDev — APPROVED** [review]
Thanks @suleymanakbas91  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
