### PR TITLE
emacs 25.0.94 (devel)

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Announcement: https://lists.gnu.org/archive/html/info-gnu-emacs/2016-05/msg00000.html.

### CODE REVIEW

**Comment by dunn** [comment]
Just an audit failure:
```
        Error: 3 problems in 1 formula
emacs:
  * Dependency 'd-bus' was renamed; use new name 'dbus'.
  * Dependency 'd-bus' was renamed; use new name 'dbus'.
  * Dependency 'd-bus' was renamed; use new name 'dbus'.

**Comment by zmwangx** [comment]
Hmm, shouldn't have cut that corner even though it's just a URL change...

**Comment by DomT4** [comment]
You might need a `deprecated_option` to cover the rename, unless it automagically knows what you mean if you upgrade with a `--with-d-bus` flag. I don't think it knows, but my brain isn't working tonight.

**Comment by dunn** [comment]
Good point, it doesn't remember the name of the old flag.

**Comment by zmwangx** [comment]
Added.

**Comment by mikemcquaid** [comment]
Thanks again @zmwangx!

**Pull request merged**
