### PR TITLE
pyqt, pyqt@5: unify resource names with PyPI packages

### PR DESCRIPTION
**Pull request by woodruffw**
This makes it easier to do vulnerability scanning on these dependencies, and is consistent with how all other PyPI resources in Python formulae are named.

I haven't run the build or tests locally yet, since they're pretty heavy.

Signed-off-by: William Woodruff <william@yossarian.net>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Can you rebase your branch so that each commit modifies only one formula at a time? @BrewTestBot doesn't like commits that modify multiple formulae. (That's why there's an "automerge-skip" label.)

**Comment by woodruffw** [comment]
> Can you rebase your branch so that each commit modifies only one formula at a time? @BrewTestBot doesn't like commits that modify multiple formulae. (That's why there's an "automerge-skip" label.)

Done! Sorry for the churn.

**Comment by danielnachun** [comment]
The Linux GCC dependency needs to be removed as it is unneeded and will fail the audit.

**Comment by woodruffw** [comment]
> The Linux GCC dependency in `qt@5` needs to be removed as it is unneeded and will fail the audit.

This one, right?

```
  on_linux do
    depends_on "gcc"
  end
```

Does that mean the `fails_with gcc: "5"` can be removed as well, or do we want to keep that around for when the toolchain still is GCC 5?

**Comment by danielnachun** [comment]
> > The Linux GCC dependency in `qt@5` needs to be removed as it is unneeded and will fail the audit.
> 
> This one, right?
> 
> ```ruby
>   on_linux do
>     depends_on "gcc"
>   end
> ```
> 
> Does that mean the `fails_with gcc: "5"` can be removed as well, or do we want to keep that around for when the toolchain still is GCC 5?

We're keeping the `fails_with` statements around for now.

**Comment by woodruffw** [comment]
Okay, squashed that into the `pyqt@5` change.

**Comment by carlocab** [comment]
CI queue is quiet, so I'm borrowing the long build label.

**Comment by woodruffw** [comment]
Thanks for shepherding!

**Review by carlocab — APPROVED** [review]
Failure is pre-existing.

**Pull request closed without merging**
