### PR TITLE
unar: Install Update

### PR DESCRIPTION
**Pull request by ghost**
- [✓] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why is this change necessary?

**Comment by sentoukat** [comment]
Well, it was suggested as a fix by the "brew audit --strict" command.

**Comment by ilovezfs** [comment]
I think it's a false positive.

**Comment by ilovezfs** [comment]
Thanks for the PR nonetheless @sentoukat!

**Pull request closed without merging**
