### PR TITLE
openimageio 2.3.11.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
>  ==> /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3
>  Traceback (most recent call last):
>    File "<stdin>", line 2, in <module>
>  ModuleNotFoundError: No module named 'OpenImageIO'

**Comment by iMichka** [comment]
`openimageio` depends on `python@3.10` through `mesa`->`llvm`->`python@3.10`
Let's see if we can migrate it to `openimageio`. Nothing seems to use `openimageio`.

**Comment by carlocab** [comment]
> `openimageio` depends on `python@3.10` through `mesa`->`llvm`->`python@3.10`
> Let's see if we can migrate it to `openimageio`. Nothing seems to use `openimageio`.

You may as well kill the Python bindings, since this needs Python 3.9 for `boost-python3`. How does this formula depend on `mesa`?

**Review by carlocab — APPROVED** [review]

**Comment by iMichka** [comment]
Nice catch.

**Pull request closed without merging**
