### PR TITLE
flashrom 1.3.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  hwaccess_x86_msr.c:307:10: fatal error: 'DirectHW/DirectHW.h' file not found
  #include <DirectHW/DirectHW.h>
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  make: *** [hwaccess_x86_msr.o] Error 1
  make: *** Waiting for unfinished jobs....
  hwaccess_x86_io.c:123:10: fatal error: 'DirectHW/DirectHW.h' file not found
  #include <DirectHW/DirectHW.h>
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  make: *** [hwaccess_x86_io.o] Error 1
  hwaccess_physmap.c:136:10: fatal error: 'DirectHW/DirectHW.h' file not found
  #include <DirectHW/DirectHW.h>
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  make: *** [hwaccess_physmap.o] Error 1
```

**Comment by chenrui333** [comment]
this is a false alarm

```
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/flashrom.rb:29:5: C: https://github.com/PureDarwin/DirectHW/archive/refs/tags/DirectHW-1.tar.gz looks like a binary package, not a source archive; homebrew/core is source-only.
      url "https://github.com/PureDarwin/DirectHW/archive/refs/tags/DirectHW-1.tar.gz"
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by p-linnane** [comment]
@chenrui333 Thanks for all the work on this one 🙏

**Comment by chenrui333** [comment]
squash the commits before the merge run.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
