### PR TITLE
tart: skip 1.x release

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /usr/bin/codesign -f -s - --entitlement Resources/tart.entitlements .build/release/tart
  Resources/tart.entitlements: cannot read entitlement data
```

**Comment by carlocab** [comment]
`Resources/tart.entitlements` was renamed. https://github.com/cirruslabs/tart/pull/429

**Review by carlocab — CHANGES_REQUESTED** [review]
This has been relicensed and is no longer open source: https://github.com/cirruslabs/tart/commit/4339a03102b9354301da823bed9c376c3cf7827e

I suggest migrating this to Homebrew/cask.

**Comment by vitorgalvao** [comment]
> I suggest migrating this to Homebrew/cask.

Can’t yet go in there because [it’s not notarised](https://github.com/cirruslabs/tart/pull/415#issuecomment-1450545065) but [might be soon](https://github.com/cirruslabs/tart/pull/415#issuecomment-1450637860).

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
