### PR TITLE
boost 1.83

### PR DESCRIPTION
**Pull request by ik11235**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
There are failures on ~90 formulas, but they're only on Linux, and I don't understand why…

**Review by iMichka — DISMISSED** [review]
For `boost 1.82` we rev bumped way more formulae: #128510
So I guess almost of the broken ones need a rev bump on Linux.

I'm working on the `ghc` PR right now but I can come back to this one after that. Or someone else can rev bump everything to make it work.

**Comment by SMillerDev** [comment]
graph-tool
```
  ./src/graph/gml.hh:370:31: error: use of undeclared identifier 'tend'
          parse_grammar(tbegin, tend, g, dp,
                                ^
```

mapnik
```
  include/mapnik/json/generic_json.hpp:97:50: error: use of undeclared identifier 'utf8_iter'
          boost::utf8_output_iterator<insert_iter> utf8_iter(out_iter);
                                                   ^
```

**Comment by fxcoudert** [comment]
```
==> Running Formulae#run!
Error: No available formula with the name "boost@1.79". Did you mean boost@1.76?
Error: Process completed with exit code 1.
```

**Comment by iMichka** [comment]
Let me fix this

**Comment by fxcoudert** [comment]
@iMichka the build errors seemed fatal enough that I killed the workflow on Intel nodes, we're currently struggling with CI resources, I hope that was the right call.

```
brew fetch --retry avro-cpp --build-bottle --force
brew install --verbose --build-bottle avro-cpp
brew install --verbose --build-bottle graph-tool
brew install --verbose --build-bottle upscaledb
brew install --verbose --build-bottle votca
```

**Comment by iMichka** [comment]
No issue this was the right thing to do. No need to clutter CI with long builds if we already have some first failures to fix.

**Comment by iMichka** [comment]
Fix for `avro`: #146296

**Comment by iMichka** [comment]
I've added the self hosted linux runner to the flags, as I see the Linux build failed after 360 minutes.

What is the issue with `upscaledb`? @fxcoudert did you try to rebase this, as I think this is building since #134605 now.

Still need to have a look at the other errors

**Comment by fxcoudert** [comment]
The PR was rebased on top of master

- graph-tool needs cmake, fixed in latest push
- i2pd was rev-bumped twice, my mistake, fixed in latest push
- upscaledb: no idea
- votca: patch does not apply cleanly

**Comment by SMillerDev** [comment]
UpscaleDB seems to be unmaintained at this point so might as well deprecate it and pin it to an older boost version.

**Comment by nega0** [comment]
Can we get boostorg/process@5f795d9e62c81893a44c58162abd3b8c0c6beb8c included? Otherwise `boost::process` chokes itself on MacOSX14.0.sdk (CLT).

```console
$ cat foo.cc
#include <boost/process.hpp>

$ clang++ -std=c++17 -Wall -g -O0 -I/opt/homebrew/opt/boost/include -c foo.cc |& rg error:
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:36:20: error: expected unqualified-id
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:36:20: error: unexpected type name 'DIR': expected expression
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:36:20: error: use of undeclared identifier '_dirp'
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:120:24: error: expected unqualified-id
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:120:24: error: unexpected type name 'DIR': expected expression
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:120:24: error: use of undeclared identifier '_dirp'
```

Or should I just file a PR against 1.82? Or wait and file against 1.83?

**Comment by iMichka** [comment]
I have taken over the PR at #151447, to benefit from our build cache (it works only for maintainers and allows to reuse previously built bottles to speed up things).

@nega0 I think your change can be handled in a separate pull request and is unrelated to this one. You can open a separate fix for it right away.

**Pull request closed without merging**
