### PR TITLE
standardese 0.5.2

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - external/cppast/lib_cppast_tiny_process.dylib
```
Looks like they moved the stuff I used to install manually.

**Comment by alebcay** [comment]
From what I can tell, this library is no longer built (maybe rolled into `libcppast` proper). It also looks like the `cppast` build process has moved from using Git submodules to using CMake to fetch content at build-time instead 🤦.

**Comment by carlocab** [comment]
Doesn't surprise me.

In the last version bump, they changed their build so that `standardese` now relies on shared libraries that their build system don't install, so 🤷

**Comment by carlocab** [comment]
In any case, I was planning on moving those libraries from `libexec` into `lib` so we can pass `rpath` to `CMAKE_INSTALL_RPATH`. (I put them in `libexec` last time since I wasn't really sure where to put stuff their build system doesn't install, but `lib` does seem like the right move here.)

**Review by nandahkrishna — APPROVED** [review]

**Pull request closed without merging**
