### PR TITLE
root 6.26.06

### PR DESCRIPTION
**Pull request by henryiii**
- root 6.26.06
- minuit2 6.26.06

Both need to be bumped at the same time.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
I think it might now be possible to migrate `python@3.9 --> python@3.10`. Recent formula changes have helped remove extra Pythons from dependency tree (`brew deps --tree root`).

**Comment by henryiii** [comment]
Has the default changed to Python 3.10 yet? Was kind of waiting for that, since ROOT is accessible via `import ROOT`, so `python3 -c "import root"` will go from working to failing after this change if it's not the default. Very happy to have it move up, though.

I'm asking about the free type error (`undefined reference to 'BrotliDecoderDecompress'`) on Linux to see if anyone has seen that before.

**Comment by carlocab** [comment]
Will introduce a merge conflict in #106755, so we may want to hold off on merging this for a bit.

**Comment by carlocab** [comment]
> I'm asking about the free type error (`undefined reference to 'BrotliDecoderDecompress'`) on Linux to see if anyone has seen that before.

Maybe it has the wrong link flags, or they are in the wrong order? I know our somewhat ancient Linux toolchain is a bit pickier about the order in which the flags appear.

**Review by carlocab — COMMENTED** [review]
GCC has been merged. This needs a rebase.

**Comment by carlocab** [comment]
CC @Homebrew/linux for ideas on the Linux failure.

**Comment by cho-m** [comment]
Any reason why we can't use Homebrew's `freetype`? I'm guess `brotli` got picked up from build environment while building bundled `freetype` resulting in the symbols that need the corresponding `brotli` library.

**Review by iMichka — APPROVED** [review]
Thanks!

**Pull request closed without merging**
