### PR TITLE
cli53 0.8.16

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
12:16:30 cp -pR /private/tmp/d20191029-57343-yzk5te/cli53-0.8.16/. /private/tmp/cli53-20191029-57343-1wfm5wu/cli53-0.8.16
12:16:30 chmod -Rf +w /private/tmp/d20191029-57343-yzk5te
12:16:30 ==> make build
12:16:30 go build -i -v ./cmd/cli53
12:16:30 $GOPATH/go.mod exists but should not
12:16:30 make: *** [build] Error 1
12:16:30

**Comment by chenrui333** [comment]
They moved to `go modules` now.

**Comment by igas** [comment]
@chenrui333 please take this one, I'm not sure why it fails, as gomod is default now, I tried with normal `go build` - same problem. Thanks.

**Comment by chenrui333** [comment]
Sure, let me take a look.

**Comment by chenrui333** [comment]
Should be addressed in https://github.com/Homebrew/homebrew-core/pull/45962

**Pull request closed without merging**
