### PR TITLE
frida-12.7.22 (new formula)

### PR DESCRIPTION
**Pull request by mofneko**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by mofneko** [comment]
GitHub: https://github.com/frida/frida

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by mofneko** [comment]
@SMillerDev
The brew test bot references another repository.  The repository I submitted is a repository divided into the core engine and cui interface. The main is the one linked in the previous comment.

**Comment by SMillerDev** [comment]
If you make an interface to Amazon Web Services you can't really claim the AWS users as your own either. The measurement is done on the software you're shipping. Not on another repository that might be related to it.

**Comment by mofneko** [comment]
It is the repository described in frida's official installation procedure.
https://www.frida.re/docs/installation/

**Comment by SMillerDev** [comment]
That makes it even more confusing because nowhere there it mentions the source you're downloading. Why can't this formula build frida itself?

**Comment by mofneko** [comment]
Building it as a dependency.

**Comment by mofneko** [comment]
@SMillerDev
As another plan, submit this formula as a single frida, and submit again the formula of the next link as a dependency.  Do you accept it?

https://github.com/Homebrew/homebrew-core/pull/46906

**Comment by SMillerDev** [comment]
After looking into it for a bit, there isn't any need I can find to build frida-tools. It's already pulled in by the main repo as a git submodule. I'd be fine with a frida formula based on the main repo, provided it fullfils the rest of the criteria for a formula: https://docs.brew.sh/Acceptable-Formulae

**Comment by claui** [comment]
In case @mofneko or anyone else would like to give it another shot:
as far as I can tell, [both the notability issue and the confusing repository layout](https://github.com/frida/frida) have been solved by now.

**Pull request closed without merging**
