### PR TITLE
ghc 8.8.1

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is failing to build with:

```
checking for version of alex... 
configure: error: Alex version 3.1.7 or later is required to compile GHC.
```

**Comment by fishtreesugar** [comment]
According to the ghc's [document](https://gitlab.haskell.org/ghc/ghc/wikis/building/preparation/tools)
> Like Happy, you don't need Alex if you're building GHC from a
source tarball, but you do need it if you're modifying GHC and/or
building from a git repository.

It seems that the misoperation was introduced in https://gitlab.haskell.org/ghc/ghc/commit/699e507237ccda65fe9f37651d2358129390e2de

cc @bgamari

**Comment by robrix** [comment]
Out of curiosity, why do we build from source instead of using the binary distribution?

**Comment by SMillerDev** [comment]
>Out of curiosity, why do we build from source instead of using the binary distribution?

@robrix because homebrew policy prohibits binary distribution. Everything has to be open source and build from source. (Otherwise using homebrew on Linux would become very difficult to maintain for example)

**Comment by robrix** [comment]
@SMillerDev thanks very much for the explanation! 🙇

**Comment by fishtreesugar** [comment]
#43930 already merged

**Pull request closed without merging**
