### PR TITLE
efl: depend on luajit-openresty

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Another try for #69021.

### CODE REVIEW

**Comment by equal-l2** [comment]
This works on my Mac (macOS 12.0.1, x86) at least.

**Comment by equal-l2** [comment]
Can someone re-run the CI with `CI-no-fail-fast` so that I can see how the change works on all envs?

**Comment by equal-l2** [comment]
The build fails on ARM and Linux.

The relevant lines for ARM:
```
2021-11-08T23:20:46.4277950Z [1709/2316] /usr/bin/env EFL_RUN_IN_TREE=1 /private/tmp/efl-20211108-36049-u87dbz/efl-1.25.1/build/src/bin/edje/edje_cc -id /private/tmp/efl-20211108-36049-u87dbz/efl-1.25.1/data/elementary/themes/img -sd /private/tmp/efl-20211108-36049-u87dbz/efl-1.25.1/data/elementary/themes/snd ../src/bin/exactness/player_entry.edc src/bin/exactness/player_entry.edj
2021-11-08T23:20:46.4279470Z FAILED: src/bin/exactness/player_entry.edj 
2021-11-08T23:20:46.4281010Z /usr/bin/env EFL_RUN_IN_TREE=1 /private/tmp/efl-20211108-36049-u87dbz/efl-1.25.1/build/src/bin/edje/edje_cc -id /private/tmp/efl-20211108-36049-u87dbz/efl-1.25.1/data/elementary/themes/img -sd /private/tmp/efl-20211108-36049-u87dbz/efl-1.25.1/data/elementary/themes/snd ../src/bin/exactness/player_entry.edc src/bin/exactness/player_entry.edj
```

The relevant lines for Linux:
```
  ../src/lib/ecore_cocoa/meson.build:34:0: ERROR: No host machine compiler for "src/lib/ecore_cocoa/ecore_cocoa.m"
```

**Comment by danielnachun** [comment]
To fix this on Linux, I had to first make the argument `-Dcocoa=true` only run on macOS.  You can do this by just deleting from the array and then putting it below as `args << "-Dcocoa=true" if OS.mac`.  The second issue is that this needs to be built with GCC 11 by adding these lines after `uses_from_macos "zlib`:
```
on_linux do
   depends_on "gcc"
end
```
However when I try this it still uses GCC 5.  I was able to force it to use GCC 11 by setting `CC` and `CXX` to the right values, but that bypasses our compiler shim which we don't like doing.  We'll have to see if this actually bypassing the shim or if there's some other reason it doesn't choose the right compiler.

**Comment by equal-l2** [comment]
@danielnachun
Thank you for the advice. I applied the cocoa part.
One thing I want to ask you, how did you know the build requires GCC 11?

**Comment by equal-l2** [comment]
Failure on Linux:
```
  FAILED: src/generic/evas/evas_image_loader.pdf 
  g++-5  -o src/generic/evas/evas_image_loader.pdf src/generic/evas/evas_image_loader.pdf.p/pdf_main.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 '-Wl,-rpath,$ORIGIN/../../lib/eina:/home/linuxbrew/.linuxbrew/Cellar/poppler/21.12.0/lib' -Wl,-rpath-link,/tmp/efl-20211225-53084-afyptu/efl-1.25.1/build/src/lib/eina -Wl,-rpath-link,/home/linuxbrew/.linuxbrew/Cellar/poppler/21.12.0/lib -Wl,--start-group src/generic/evas/libevas_loader_common.a src/lib/eina/libeina.so.1.25.1 -pthread -lm -ldl /home/linuxbrew/.linuxbrew/Cellar/poppler/21.12.0/lib/libpoppler-cpp.so -lrt -Wl,--end-group
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 2 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 3 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 4 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 5 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 6 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 7 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 8 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 9 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 10 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 11 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 12 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 13 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 14 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 15 (>= sh_info of 2)
  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/poppler/21.12.0/lib/libpoppler-cpp.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
  collect2: error: ld returned 1 exit status
```

**Pull request closed without merging**
