### PR TITLE
sdl2_mixer: support mp3 by default

### PR DESCRIPTION
**Pull request by Starbuck5**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Hello!

I use SDL_Mixer in one of my projects, and I noticed that homebrew builds it without mp3 support.

I dug through some commit history, and apparently it used to be optional, but was straight up removed when options were removed.

In the past, I believe there were potential copyright issues with using libmpg for mp3 reading, but in the last few years those have been resolved. (The copyrights expired). Perhaps that's why it was optional in the past. But that shouldn't count against it today.

According to the SDL_Mixer configure, the `--enable-music-mp3-mpg123` defaults to `yes`. (https://github.com/libsdl-org/SDL_mixer/blob/master/configure#L1607-L1608) If it's their default, then perhaps it should be homebrew's default as well.

In this PR, I added the `--enable-music-mp3-mpg123`, added a dependency on `mpg123`, which is also on brew thankfully, and removed the obsolete disable smpeg option. (The smpeg option must've been removed in 2.0.4, which dropped the smpeg mp3 backend in favor of libmpg123). I also added 1 to the revision number to re bottle the changes, as was mentioned in the contributing guide.

This is my first PR on homebrew, so be sure to tell me if I did anything wrong 🙂 

Have a nice day!

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
Thanks, @Starbuck5!

For future reference: we prefer PRs to feature a single commit per formula modified (and a single formula modified per commit), with commit messages that start with the formula name (as in the title you chose for your PR).

I've fixed that up for you. Thanks for your contribution!

**Comment by carlocab** [comment]
CI is stuck for some reason... Let's try closing and reopening this.

**Comment by Starbuck5** [comment]
Wow, thanks for such a quick response!

Should I worry about this "Bottle publish failed" ?

I see that the sdl2_mixer page on brew.sh looks updated, so it probably published the bottles from another commit.

**Comment by carlocab** [comment]
Don't worry about it. That's just from @BrewTestBot triggering a second publish job after I already did so. Thanks again for your contribution!

**Pull request closed without merging**
