### PR TITLE
radare2 3.9.0

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Odd that this builds fine on my VM but [fails in CI](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/48718/version=mojave/console):
```
...
15:38:42 ld: Assertion failed: (0 && "unknown objc arch"), function doPass, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-512.4/src/ld/passes/objc.cpp, line 1747.
15:38:42 ld: warning: platform not specified
15:38:42 ld: warning: -arch not specified
15:38:42 ld: warning: ignoring file zip/librz.a, building for -unknown but attempting to link with file built for macOS-x86_64
15:38:42 0  0x10d730168  __assert_rtn + 127
15:38:42 1  0x10d73a105  ld::passes::objc::fixClassAliases(ld::Atom const*) (.cold.1) + 0
15:38:42 2  0x10d70b9b4  void ld::passes::objc::doPass<x86_64, true>(Options const&, ld::Internal&) + 0
15:38:42 3  0x10d6130aa  main + 868
15:38:42 A linker snapshot was created at:
15:38:42 	/tmp/librz.a.a.o-2019-08-24-163839.ld-snapshot
15:38:42 ld: Assertion failed: (0 && "unknown objc arch"), function doPass, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-512.4/src/ld/passes/objc.cpp, line 1747.
15:38:42 make[1]: *** [libr_shlr.a] Error 1
15:38:42 make: *** [install] Error 2
```

**Comment by EricFromCanada** [comment]
@BrewTestBot Test this please

**Comment by nl5887** [comment]
Getting the same issue on MacOS version 10.14.6. To make this work with release 3.9.0, you'll need to patch the makefiles. I created a PR to update head, but don't expect it to land on 3.9.0 shortly. 

https://github.com/radareorg/radare2/pull/15202

In the meantime embedding the patch will work:

```
class Radare2 < Formula
  desc "Reverse engineering framework"
  homepage "https://radare.org"
  url "http://radare.mikelloc.com/get/3.9.0/radare2-3.9.0.tar.gz"
  sha256 "0b912c69fe4e00e6f0c67c5cc547ad3afcf316fc426d0b9c1fe6c3c768e9b6f5"
  head "https://github.com/radare/radare2.git"

  patch :DATA

  def install
    system "./configure", "--prefix=#{prefix}"
    system "make"
    system "make", "install"
  end

  test do
    assert_match "radare2 #{version}", shell_output("#{bin}/r2 -version")
  end
end

__END__
diff --git a/mk/clang.mk b/mk/clang.mk
index 60c56b305..ee13e264b 100644
--- a/mk/clang.mk
+++ b/mk/clang.mk
@@ -16,7 +16,7 @@ CFLAGS_DEBUG=-g

 ifeq ($(OSTYPE),darwin)
 ARCH=$(shell uname -m)
-PARTIALLD=ld -r -all_load
+PARTIALLD=ld -r -all_load -platform_version macos 10.14 10.14
 #CFLAGS+=-arch ${ARCH}
 #LDFLAGS+=-arch ${ARCH}
 LDFLAGS_LIB=-dynamiclib
diff --git a/mk/gcc.mk b/mk/gcc.mk
index 27759944e..ea5f65fec 100644
--- a/mk/gcc.mk
+++ b/mk/gcc.mk
@@ -20,7 +20,7 @@ ifeq ($(OSTYPE),darwin)
 ARCH=$(shell uname -m)
 #CFLAGS+=-arch ${ARCH}
 #LDFLAGS+=-arch ${ARCH}
-PARTIALLD=${LD} -r -all_load
+PARTIALLD=${LD} -r -all_load -arch ${ARCH} -platform_version macos 10.14 10.14
 CFLAGS+=-fno-common
 LDFLAGS_LIB=-dynamiclib
 LDFLAGS_SONAME=-Wl,-install_name,${LIBDIR}/
diff --git a/mk/tcc.mk b/mk/tcc.mk
index 8f573da16..c48c64447 100644
--- a/mk/tcc.mk
+++ b/mk/tcc.mk
@@ -14,7 +14,7 @@ CFLAGS_OPT3=-O3
 LD?=ld

 ifeq ($(OSTYPE),darwin)
-PARTIALLD=${LD} -r -all_load
+PARTIALLD=${LD} -r -all_load -platform_version macos 10.14 10.14
 LDFLAGS_LIB=-dynamiclib
 LDFLAGS_SONAME=-Wl,-install_name,
 else
```

**Comment by nl5887** [comment]
Updated version that will test for xcode version: 

```class Radare2 < Formula
  desc "Reverse engineering framework"
  homepage "https://radare.org"
  url "http://radare.mikelloc.com/get/3.9.0/radare2-3.9.0.tar.gz"
  sha256 "0b912c69fe4e00e6f0c67c5cc547ad3afcf316fc426d0b9c1fe6c3c768e9b6f5"
  head "https://github.com/radare/radare2.git"

  patch :DATA

  def install
    system "./configure", "--prefix=#{prefix}"
    system "make"
    system "make", "install"
  end

  test do
    assert_match "radare2 #{version}", shell_output("#{bin}/r2 -version")
  end
end

__END__
diff --git a/mk/clang.mk b/mk/clang.mk
index 60c56b305..4e079a7f1 100644
--- a/mk/clang.mk
+++ b/mk/clang.mk
@@ -16,7 +16,12 @@ CFLAGS_DEBUG=-g
 
 ifeq ($(OSTYPE),darwin)
 ARCH=$(shell uname -m)
-PARTIALLD=ld -r -all_load
+XCODE_VERSION=$(shell xcodebuild -version|grep Xcode|grep -o "[\.0-9]\+")
+XCODE_VERSION_MAJOR = $(word 1, $(subst ., ,$(XCODE_VERSION)))
+PARTIALLD=${LD} -r -all_load
+ifeq ($(XCODE_VERSION_MAJOR),11)
+PARTIALLD+=-arch ${ARCH} -platform_version macos 10.14 10.14
+endif
 #CFLAGS+=-arch ${ARCH}
 #LDFLAGS+=-arch ${ARCH}
 LDFLAGS_LIB=-dynamiclib
diff --git a/mk/gcc.mk b/mk/gcc.mk
index 27759944e..e75fcd8ae 100644
--- a/mk/gcc.mk
+++ b/mk/gcc.mk
@@ -18,9 +18,14 @@ LD?=ld
 
 ifeq ($(OSTYPE),darwin)
 ARCH=$(shell uname -m)
+XCODE_VERSION=$(shell xcodebuild -version|grep Xcode|grep -o "[\.0-9]\+")
+XCODE_VERSION_MAJOR = $(word 1, $(subst ., ,$(XCODE_VERSION)))
 #CFLAGS+=-arch ${ARCH}
 #LDFLAGS+=-arch ${ARCH}
-PARTIALLD=${LD} -r -all_load
+PARTIALLD=${LD} -r -all_load 
+ifeq ($(XCODE_VERSION_MAJOR),11)
+PARTIALLD+=-arch ${ARCH} -platform_version macos 10.14 10.14
+endif
 CFLAGS+=-fno-common
 LDFLAGS_LIB=-dynamiclib
 LDFLAGS_SONAME=-Wl,-install_name,${LIBDIR}/
diff --git a/mk/tcc.mk b/mk/tcc.mk
index 8f573da16..88c3c3b1c 100644
--- a/mk/tcc.mk
+++ b/mk/tcc.mk
@@ -14,7 +14,13 @@ CFLAGS_OPT3=-O3
 LD?=ld
 
 ifeq ($(OSTYPE),darwin)
+ARCH=$(shell uname -m)
+XCODE_VERSION=$(shell xcodebuild -version|grep Xcode|grep -o "[\.0-9]\+")
+XCODE_VERSION_MAJOR = $(word 1, $(subst ., ,$(XCODE_VERSION)))
 PARTIALLD=${LD} -r -all_load
+ifeq ($(XCODE_VERSION_MAJOR),11)
+PARTIALLD+=-arch ${ARCH} -platform_version macos 10.14 10.14
+endif
 LDFLAGS_LIB=-dynamiclib
 LDFLAGS_SONAME=-Wl,-install_name,
 else
```

**Comment by EricFromCanada** [comment]
Will resubmit once a new release containing radareorg/radare2#15202 is out.

**Pull request closed without merging**
