### PR TITLE
workflows/tests: set up Bundler Gems cache

### PR DESCRIPTION
**Pull request by carlocab**
This sets up the Gems cache for use on PR branches. Companion to
Homebrew/actions#375.

### CODE REVIEW

**Comment by Bo98** [comment]
LGTM but this seems like it could go into a separate workflow instead. There's already a lot going on in tests.yml.

**Comment by carlocab** [comment]
Yea, that's fair. I've opened https://github.com/Homebrew/actions/pull/376 so we can just have a single `populate-gems-cache` action that we can use in both Homebrew/core and Homebrew/cask.

**Comment by carlocab** [comment]
`actionlint` failure fixed in #132722.

**Review by MikeMcQuaid — COMMENTED** [review]
Leaving a comment to make GitHub/Slack shut up but have left real review on the other PR

**Pull request closed without merging**
