### PR TITLE
gpsbabel: fix patch url

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by gromgit** [comment]
@dtrodrigues How did you get the commit ID of the entire patchset?

I ask because I downloaded and manually applied both the original patch URL and your new one to separate copies of the gpsbabel source, and there's a difference:
```
diff -r gpsbabel1/jeeps/gpsusbstub.cc gpsbabel2/jeeps/gpsusbstub.cc
36c36
<   Fatal() << no_usb;
---
>   fatal(no_usb);
```

**Comment by dtrodrigues** [comment]
I grabbed it from the merge commit here at the bottom of https://github.com/gpsbabel/gpsbabel/pull/611 - https://github.com/gpsbabel/gpsbabel/commit/d0b73a0b8fca2f9c0ee6253954920f9bd142cba6, but you're right, they don't seem to be the same.

**Comment by gromgit** [comment]
Yeah, the new patch doesn't capture changes to `gpsusbstub.cc` that are in two separate patches in the PR patchset.

Might be a good idea to initiate a "standard operating procedure": When replacing a PR patch URL that spans multiple commits, dump the URL's contents into `formula-patches` and point to that instead.

**Comment by dtrodrigues** [comment]
You're right, I just saw that too. Was in a rush since the style check to verify this just got merged into `brew`. I'll undo this change and undo the brew change as well so that the style checks don't fail for everybody.

**Pull request merged**
