### PR TITLE
cgal 4.13

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
High Sierra graph-tool issue filed upstream: https://git.skewed.de/count0/graph-tool/issues/509

**Comment by lrineau** [comment]
Hi FX, I'm Laurent Rineau (ENS math 1999). I am surprised to see that your are maintaining the CGAL package in brew (probably you maintain a lot of homebrew-core as a hobby).

I am the release manager of the CGAL project, and also employee of GeometryFactory, a small company that maintains actively that open source project. The CGAL project  has decided this summer to help package maintainers of CGAL packages. My college Maxime Gimeno (@maxGimeno) is responsible for that. Do not hesitate to join us for help, if you need any.

**Comment by fxcoudert** [comment]
`graph-tool` fails to build again, this time on High Sierra and Mojave, with:

```
    In file included from src/ft2font_wrapper.cpp:5:
    In file included from src/numpy_cpp.h:19:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:246:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
    using ::signbit;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
    using ::fpclassify;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:315:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
    using ::isfinite;
          ~~^
    /usr/include/math.h:757:12: note: 'finite' declared here
    extern int finite(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
               ^
    In file included from src/ft2font_wrapper.cpp:5:
    In file included from src/numpy_cpp.h:19:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:246:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:316:9: error: no member named 'isinf' in the global namespace
    using ::isinf;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:317:9: error: no member named 'isnan' in the global namespace
    using ::isnan;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error: no member named 'isnormal' in the global namespace
    using ::isnormal;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:9: error: no member named 'isgreater' in the global namespace
    using ::isgreater;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:9: error: no member named 'isgreaterequal' in the global namespace
    using ::isgreaterequal;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
    using ::isless;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
    using ::islessequal;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
    using ::islessgreater;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    13 errors generated.
    error: command 'clang' failed with exit status 1
    Running setup.py install for matplotlib: finished with status 'error'
Cleaning up...
  Removing source in /private/tmp/pip-req-build-9j0l2r49
Removed build tracker '/private/tmp/pip-req-tracker-khino1qj'
Command "/usr/local/Cellar/graph-tool/2.27_2/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-9j0l2r49/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-a0dy0bp9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/graph-tool/2.27_2/libexec/bin/../include/site/python3.7/matplotlib" failed with error code 1 in /private/tmp/pip-req-build-9j0l2r49/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/graph-tool/2.27_2/libexec/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/graph-tool/2.27_2/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 347, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/graph-tool/2.27_2/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/graph-tool/2.27_2/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 972, in install
    spinner=spinner,
  File "/usr/local/Cellar/graph-tool/2.27_2/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 701, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/graph-tool/2.27_2/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-9j0l2r49/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-a0dy0bp9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/graph-tool/2.27_2/libexec/bin/../include/site/python3.7/matplotlib" failed with error code 1 in /private/tmp/pip-req-build-9j0l2r49/
```

**Comment by fxcoudert** [comment]
Salut @lrineau, thanks for the notice, we welcome any help. CGAL usually compiles fine, but major version updates tend to break some of the other packages that depend on it. This time, it appears to be graph-tool…

**Comment by lrineau** [comment]
@fxcoudert It looks like that code requires `<math.h>` but it is not included.

**Comment by fxcoudert** [comment]
Turns out that graph-tool issue is preexisting. Will merged now…

**Comment by fxcoudert** [comment]
Closed in https://github.com/Homebrew/homebrew-core/commit/ca382ac67a661b42cb57988234d696c903f05330

**Pull request closed without merging**
