### PR TITLE
rubberband 2.0.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Failed to build on Linux only.

**Comment by miccal** [comment]
Ping @Homebrew/linux for any advise here.

**Comment by dawidd6** [comment]
Maybe newer gcc could help?

**Comment by miccal** [comment]
> Maybe newer gcc could help?

Thanks @dawidd6, but you will need to be more specific about what I have to add here :)

I assume you mean to add a `depends_on` to the `on_linux do` block ... ?

**Comment by miccal** [comment]
Thank you @dawidd6, much appreciated :)

**Comment by dawidd6** [comment]
Brewed gcc wasn't even picked up, interesting.

**Comment by SMillerDev** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/glslviewer/1.7.0/bin/glslViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/lib/librubberband.so.2)
```

**Comment by danielnachun** [comment]
If `rubberband` needs a newer GCC, all of its C++ dependents must also be built with the newer GCC as well.  Hopefully that’s not a crazy number of formulae!

**Review by iMichka — APPROVED** [review]

**Comment by miccal** [comment]
Thank you all for your help with this.

**Pull request closed without merging**
