### PR TITLE
docker 17.03.0

### PR DESCRIPTION
**Pull request by mkjaer**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mkjaer** [comment]
It looks like the last -ce part is not supporting somewhere in your build process or maybe I'm misunderstanding the below from Jenkins:

>Created binary: bundles/17.03.0-ce/dynbinary-client/docker-17.03.0-ce
>Error: No such file or directory - bundles/17.03.0/dynbinary-client/docker-17.03.0

**Comment by fxcoudert** [comment]
It looks like it's the `make.sh` script that does not support the `-ce` suffix:

```
==> hack/make.sh dynbinary-client
# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#

---> Making bundle: dynbinary-client (in bundles/17.03.0-ce/dynbinary-client)
Building: bundles/17.03.0-ce/dynbinary-client/docker-17.03.0-ce
Created binary: bundles/17.03.0-ce/dynbinary-client/docker-17.03.0-ce

Error: No such file or directory - bundles/17.03.0/dynbinary-client/docker-17.03.0
```

**Comment by JCount** [comment]
This should fix the final installation step since the only issue was in the version name embedded in the path. 

However, this brings forward a larger question: Do we want to acknowledge, (in naming, version, etc.) the splitting of docker into "Docker Community Edition" and "Docker Enterprise Edition"? There are also now two different release channels, the more standard quarterly release which has a maintenance life cycle of 4 months, and the monthly release termed "Edge" which is only supported until the next release. The versioning scheme has also changed with a move to a YY.MM format like Ubuntu. In regards to the two different CE release variants, Docker's [blog post](https://blog.docker.com/2017/03/docker-enterprise-edition/) said:
```
Docker CE comes in two variants:

Edge is for users wanting a drop of the latest and greatest features every month
Stable is released quarterly and is for users that want an easier-to-maintain release pace
```

cc @ilovezfs and @MikeMcQuaid since I feel might as well start considering sooner rather than later what to do about supporting/not supporting both variants, do we want to change the versioning scheme, etc? This need not hold this PR up unnecessarily, but I thought it best that there be awareness/understanding before this gets merged. It will make the future road less bumpy. 🐳

**Comment by MikeMcQuaid** [comment]
@jcount Thanks for the question. The closest similar thing seems to be `jenkins` and `jenkins-lts`. This seems like a similar thing so might be worth having a `docker-stable` and `docker` be the edge formula (or vice-versa). Another option is to use `devel` for this difference. @ilovezfs thoughts?

**Comment by ilovezfs** [comment]
Let's do two formulae, `docker` and `docker-edge`.

**Comment by JCount** [comment]
Ok, I am going to merge this now. Docker seems to have an "Edge" channel dmg you can download from them, but from all the research I did the docker engine is apparently the same. The very first CE release, `17.03.0-ce`, seems to merge beta into stable. I expect that we will see tagged "Edge" releases being cut in the future. Until then, there does not seem to be any reason to create a `docker-edge` formula.

**Comment by JCount** [comment]
Thank you for your contribution @mkjaer! 😁 
closed in 478c8317fc4b00561df96ce16281b34faac74a7a

**Pull request closed without merging**
