### PR TITLE
uberftp: fix homepage

### PR DESCRIPTION
**Pull request by vitorgalvao**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Current homepage couldn’t be clearer:
image

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I don't know why but I 😆 at that screenshot.

**Comment by vitorgalvao** [comment]
So the problem here is that the github repo is not notable enough. However, the tool was already included.

What’s the usual procedure, here? Ignore the failed audit (since the formula itself is functional) or remove the formula?

**Comment by ilovezfs** [comment]
that check only applies to new formulae. the build is failing on sierra https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8013/version=sierra/console

the jenkins babble on the other two nodes happens sometimes but is nonsense

**Comment by ilovezfs** [comment]
@BrewTestBot test this please.

**Comment by MikeMcQuaid** [comment]
Aborted this because `globus-toolkit` already failed.

**Comment by MikeMcQuaid** [comment]
And can ship this homepage-only change as-is.

**Pull request merged**
