### PR TITLE
rust 1.62.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by Moisan** [comment]
The `rgbds` failure is due to `clap` which seems to match this [upstream issue](https://github.com/clap-rs/clap/issues/3883).

**Comment by cho-m** [comment]
`rgbds` and `watchman` are same issues as last PR #98823. Specifically:
- `rgbds` -- resource `rgbobj` didn't have Cargo.lock in current release and was using deprecated clap behavior, so it broke when Cargo fetched newer clap release. Reported upstream at https://github.com/gbdev/rgbobj/issues/4 and they fixed it, so we could backport patch if wanted.
- `watchman` -- dependency `folly` doesn't like building with different `-march`/etc. flags, which happens as we originally built bottles with `-march=nehalem`, but we test dependents using `--build-from-source` which doesn't apply the `-march`.

---

New issues:
- [ ] `bzt` -- Looks more like an issue in Python `setuptools` rather than `rust`, maybe from the multiple versions of `setuptools`. Reproduced locally with current `rust`/etc so unrelated to PR. Working on version bump in #104902 which removes extra `setuptools` and don't see issue there.
- [ ] `rbspy` -- Looks like some code is using deprecated behavior that was elevate from warning to error in newer `rust`. Probably needs to be reported upstream
    ```
    error: `#[derive]` can't be used on a `#[repr(packed)]` struct that does not derive Copy (error E0133)
          --> ruby-structs/src/ruby_3_1_2.rs:8741:10
           |
      8741 | #[derive(Debug)]
           |          ^^^^^
           |
           = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    ```

**Comment by branchvincent** [comment]
`rbspy` was already fixed upstream, opened #105217

**Review by carlocab — APPROVED** [review]
LGTM.

**Pull request closed without merging**
