### PR TITLE
jansson 2.12

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
The jshon test fails which I've corrected in the linked pr

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
Thanks @javian! 😅

**Comment by javian** [comment]
Now fails on
```
14:12:44 ==> brew linkage --test radare2
14:12:45 ==> FAILED
14:12:45 Broken dependencies:
14:12:45   /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/Python (python@2)
```

**Pull request closed without merging**
