### PR TITLE
cppinsights 16.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not the latest release: https://github.com/andreasfertig/cppinsights/releases

This tag is also pretty different from the previous ones.

**Comment by chenrui333** [comment]
https://github.com/andreasfertig/cppinsights/issues/592

**Comment by chenrui333** [comment]
> Not the latest release: https://github.com/andreasfertig/cppinsights/releases
> 
> This tag is also pretty different from the previous ones.

good call, raised an issue to ask about it.

**Review by carlocab — APPROVED** [review]
Confirmed as intentional by upstream.

**Pull request merged**
