### PR TITLE
unbound 1.7.0

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
for x in testdata/*.rpl; do echo -n "$x "; if ./testbound -p $x >/dev/null 2>&1; then echo OK; else echo failed; exit 1; fi done
-n testdata/acl.rpl 
OK
-n testdata/auth_xfr.rpl 
OK
-n testdata/auth_xfr_host.rpl 
OK
-n testdata/auth_xfr_ixfr.rpl 
failed
make: *** [test] Error 1
```

**Comment by JCount** [comment]
Yes, `make test` is failing that test, but it is difficult to ascertain what, and how much, significance that  failure has.

cc @ilovezfs for thoughts/opinion.

**Comment by Habbie** [comment]
The breakage was introduced in https://github.com/NLnetLabs/unbound/commit/172b84f7ce6507e96fe51bd94448222a5a47274b

**Comment by Habbie** [comment]
```
[3600] unbound[91909:0] error: mismatch in file /tmp/testbound_91909_temp_example.com.tmp, line 9
[3600] unbound[91909:0] error: file has : mail.example.com.	3600	IN	AAAA	::0.0.0.5
[3600] unbound[91909:0] error: should be: mail.example.com.	3600	IN	AAAA	::5
```

this is a long standing bug in the macOS libc.

**Comment by Habbie** [comment]
Working formula: https://gist.github.com/Habbie/9403f6bd280caf2ec414f9a42b61ff3b

It adds the `patch :DATA` line, and the patch at the end. The `patch :DATA` probably needs some comments before homebrew will accept this.

**Comment by Habbie** [comment]
Upstream workaround submitted at https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=4043 in the hope the next release will then not need `patch :DATA` any more.

**Comment by Habbie** [comment]
Upstream has merged the patch.

**Comment by JCount** [comment]
@Habbie Thanks for the info! 👍 😄

**Comment by ilovezfs** [comment]
@BrewTestBot test this please or else

**Comment by JCount** [comment]
😡

**Pull request closed without merging**
