### PR TITLE
diff-so-fancy 0.11.0

### PR DESCRIPTION
**Pull request by stevemao**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
@stevemao It seems the formula is still having to inreplace lib -> libexec in order to avoid audit failure. Do you mind changing this upstream so we can excise the complication from the formula?

**Comment by stevemao** [comment]
https://github.com/so-fancy/diff-so-fancy/pull/191

**Comment by dunn** [comment]
Thanks, looks like that was merged! Could you backport it for this stable version?

**Comment by stevemao** [comment]
How does it look now :)

**Comment by DomT4** [comment]
```
==> /usr/local/Cellar/diff-so-fancy/0.11.1/bin/diff-so-fancy
/usr/local/Cellar/diff-so-fancy/0.11.1/bin/diff-so-fancy: line 26: /usr/local/Cellar/diff-so-fancy/0.11.1/libexec/diff-so-fancy.pl: No such file or directory
Error: diff-so-fancy: failed
```

**Comment by stevemao** [comment]
Hm.. Not sure why @scottchiefbaker mind taking a look? Cheer.

**Comment by ilovezfs** [comment]
@DomT4 upstream seems to recommend npm now. Maybe this should be converted to use the new npm dsl?

**Comment by scottchiefbaker** [comment]
@stevemao I'm not sure what I'm looking at here. I use vanilla d-s-f, I'm not hip on youz kidz and all your fancy tools. Looks like it's just not finding d-s-f.pl in libexec, but I'm not sure what this is to even begin to troubleshoot.

**Comment by stevemao** [comment]
@scottchiefbaker Thanks. I feel the same when I see the TBH. @DomT4 @ilovezfs Would be great if you guys can help? Thanks for the time :)

**Comment by DomT4** [comment]
Oh, heh. Checking locally revealed something of an obvious problem:
```
~> ls -1 /usr/local/opt/diff-so-fancy
INSTALL_RECEIPT.json
bin
diff-so-fancy
readme.md
third_party
```
We're not instaling `libexec`, so that'll be the issue 😅.

I opened https://github.com/Homebrew/homebrew-core/pull/3855 to migrate to the `npm` installation, since that seems the best way to avoid having to manually work out where things should be placed, etc in future. If you're all 👍 on that idea, let me know & I'll merge that in.

**Comment by stevemao** [comment]
You have my :+1:  😄

**Comment by DomT4** [comment]
@stevemao Cheers! 😉. Merged your commits here in https://github.com/Homebrew/homebrew-core/commit/c8651a898d9485d27691d734930e042f7683b345 & https://github.com/Homebrew/homebrew-core/commit/623b25528d3759dd65aa2226d6e3406b04b95cde.

Thank you for your contributions to Homebrew, and the patience in waiting for one of us to swing back around to this PR 🙇.

**Pull request closed without merging**
