### PR TITLE
sstp-client 1.0.17

### PR DESCRIPTION
**Pull request by enaess**
Signed-off-by: eivind.naess <eivind.naess@netmotionsoftware.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
hmm, interesting, it looks like the openssl@3 does not quite work?

**Comment by enaess** [comment]
The dependency graph even when compiling with ***@***.*** still looked like this and that broke the CI build:

brew deps --tree sstp-client
sstp-client
├── libevent
│   └── ***@***.***
│       └── ca-certificates
└── ***@***.***
    └── ca-certificates

I have no idea how to fix that. Though, the CA certificates can be overridden in the sstp-client package with "--with-system-ca-path=/path/to/ca-certs". 

Regards,
- Eivind






På fredag 8. april 2022, 19:06:51 PDT skrev Rui Chen ***@***.***> følgende: 







hmm, interesting, it looks like the ***@***.*** does not quite work?

**Comment by enaess** [comment]
@chenrui333 
The dependency graph even when compiling with openssl@3 still looked like this and that broke the CI build:

```
brew deps --tree sstp-client
sstp-client
├── libevent
│   └── ***@***.***
│       └── ca-certificates
└── ***@***.***
    └── ca-certificates
```

I have no idea how to fix that. Though, the CA certificates can be overridden in the sstp-client package with "--with-system-ca-path=/path/to/ca-certs".

Regards,
- Eivind

**Comment by Bo98** [comment]
Yeah, OpenSSL 3 update needs to be done en masse to several formulae, which we'll do at some point.

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
