### PR TITLE
htop: set MaximumMacOSRequirement to Sierra

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Running htop can lead to system freezes on macOS 10.13 High Sierra

https://github.com/hishamhm/htop/issues/682
https://github.com/Homebrew/homebrew-bundle/issues/315

### CODE REVIEW

**Comment by jpwenzel** [comment]
When upgrading brew after this formula change...

```
==> Upgrading 3 outdated packages, with result:
htop 2.0.2_1, zsh 5.4.2_2, imagemagick 7.0.7-19
htop: This formula either does not compile or function as expected on macOS
versions newer than Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```
... it lead to the `zsh` and `imagemagick` packages not being updated due to the `htop` formula constraint; this broke my login shell.

Is there a less intrusive way of preventing the `htop` upgrade right now? How can we make sure the other packages in a `brew upgrade` transaction are installed anyway?

**Comment by ilovezfs** [comment]
`brew uninstall htop`

**Comment by jpwenzel** [comment]
Yes, I ended up "fixing" the issue like that. :)

**Comment by ilovezfs** [comment]
>this broke my login shell.

I assume this was because of gdbm?

**Comment by nodesocket** [comment]
Just ran `brew uninstall htop` to fix my issue (see https://github.com/Homebrew/homebrew-core/issues/22523). I am running High Sierra. Does this mean I cannot use htop with High Sierra? Is there a workaround?

**Comment by andradei** [comment]
Same questions as @nodesocket above.

**Comment by ylluminarious** [comment]
@jpwenzel 

> Is there a less intrusive way of preventing the htop upgrade right now?

You can `brew pin htop`. I've actually left `sudo htop` running for weeks on High Sierra with no problems whatsoever. It's been that way since High Sierra beta for me.

**Pull request closed without merging**
