### PR TITLE
gopass 1.12.3

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like `make install` doesn't work again. CC @dominikschulz

**Comment by dominikschulz** [comment]
Ahw, sorry. BSD `install` doesn't support `-D`. I wonder why my other PR didn't fail?

We'll switch to a separate `install -d` for the directories as we should have in the first place.

**Comment by carlocab** [comment]
>I wonder why my other PR didn't fail?

I don't understand that too, as I tried pretty much what you did when I first tried to fix the formula 😅

**Comment by carlocab** [comment]
Also, I should mention, given
```
-n      GPG1    : /opt/homebrew/opt/gnupg/bin/gpg gpg (GnuPG) 2.2.27
 [OK]
-n      GPG2    :  
 [OK]
```
that the GPG you're picking up is actually GPG2. Not sure if that matters for your build scripts, but just FYI.

**Review by dominikschulz — APPROVED** [review]
LGTM. Thank you!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
