### PR TITLE
Protobuf 21.2

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
Note: Starting with
[v21.0-rc1](https://github.com/protocolbuffers/protobuf/releases/tag/v21.0-rc1),
protobuf is using a new versioning scheme.

Signed-off-by: Wolfgang Sanyer <wolfgangsanyer@google.com>

-   [x] Have you followed the
    [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
-   [x] Have you ensured that your commits follow the
    [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
-   [x] Have you checked that there aren't other open
    [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the
    same formula update/change?
-   [x] Have you built your formula locally with `brew install
    --build-from-source <formula>`, where `<formula>` is the name of the formula
    you're submitting?
-   [x] Is your test running fine `brew test <formula>`, where `<formula>` is
    the name of the formula you're submitting?
-   [x] Does your build pass `brew audit --strict <formula>` (after doing `brew
    install --build-from-source <formula>`)? If this is a new formula, does it
    pass `brew audit --new <formula>`?

--------------------------------------------------------------------------------

I do not have a mac to test this on, so I cannot e.g. execute `brew
bump-formal-pr`

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @ezzieyguywuf.

Could you also do
```
mv Aliases/protobuf@3.19 Aliases/protobuf@21.2
```
please?

> I do not have a mac to test this on, so I cannot e.g. execute brew `bump-formal-pr`

You can run those commands on a Linux machine too if you have one to test one.

**Comment by ezzieyguywuf** [comment]
> Could you also do

Done

> You can run those commands on a Linux machine too if you have one to test on.

Ok, I figured out how to do this. It was a bit challenging since I could not immediately figure out how to install from my `bump_protobuf` branch, but I worked around this by just copying my changes to my `ezzieyguywuf/homebrew-core` master branch in order to execute the install.

I'll update the remaining checkboxes on the first post on this PR once the install has completed.

**Comment by carlocab** [comment]
Formulae that need to be rebuilt due to linkage failures:
```
apache-arrow
bear
bloaty
caffe
etcd-cpp-apiv3
fastnetmon
grpc
libphonenumber
libpulsar
libtorch
mavsdk
monero
mosh
mysql
ncnn
netdata
ola
opencv
or-tools
osm-pbf
percona-server
percona-xtrabackup
protobuf-c
protoc-gen-grpc-web
rethinkdb
sysdig
torchvision
```

**Comment by carlocab** [comment]
> I'll update the remaining checkboxes on the first post on this PR once the install has completed.

There's no need; we're a bit more relaxed about following the checklist for version-only changes.

**Comment by ezzieyguywuf** [comment]
oh cool! it was merged :-D

**Comment by SMillerDev** [comment]
It was not merged, you closed the PR.

**Comment by carlocab** [comment]
You deleted your branch, so the PR was closed.

**Pull request closed without merging**
