### PR TITLE
metabase 0.26.2

### PR DESCRIPTION
**Pull request by salsakran**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
`test` failure:

```
==> /usr/local/Cellar/metabase/0.26.2/bin/metabase migrate up
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
```

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Same failure as noted here: https://github.com/Homebrew/homebrew-core/issues/19696

This lacks Java 9 compatibility.

**Comment by camsaul** [comment]
@salsakran for Java 9 we need to add the same option I added in this PR: https://github.com/metabase/metabase/pull/6250

We need to pass `--add-modules=java.xml.bind` as a Java option

**Comment by camsaul** [comment]
@salsakran this PR should fix tests with Java 9: https://github.com/metabase/metabase/pull/6299

So if you want to cherry-pick into the 0.26.2 branch then we should be g2g here

**Comment by camsaul** [comment]
@salsakran actually on second thought we need to update `metabase.rb` to pass in the same Java options as I added in the PR mentioned above, as well as cherry-picking the commit from the PR so tests pass

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
What's the status here?

**Comment by ilovezfs** [comment]
@salsakran thanks for this PR. We'll continue to tackle this in #21135.

**Pull request closed without merging**
