### PR TITLE
duckdb 0.10.0

### PR DESCRIPTION
**Pull request by Mytherin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at CMakeLists.txt:686 (add_dependencies):
    Cannot add target-level dependencies to non-existent target
    "duckdb_local_extension_repo".
  
    The add_dependencies works for top-level logical targets created by the
    add_executable, add_library, or add_custom_target commands.  If you want to
    add file-level dependencies see the DEPENDS option of the add_custom_target
    and add_custom_command commands.
  Call Stack (most recent call first):
    CMakeLists.txt:788 (build_loadable_extension_directory)
    extension/autocomplete/CMakeLists.txt:11 (build_loadable_extension)
```

**Comment by Mytherin** [comment]
Thanks - I've pushed a fix now, we have a new dependency on Python in the build

**Comment by Mytherin** [comment]
It could be any python 3

**Comment by chenrui333** [comment]
> It could be any python 3

okay, then you can try `uses_from_macos "python" => :build` instead.

**Comment by Mytherin** [comment]
Thanks for the feedback - I've updated the script to use that instead

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@Mytherin thanks for your contribution!

**Pull request merged**
