### PR TITLE
gitui 0.10.1

### PR DESCRIPTION
**Pull request by extrawurst**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Still blocked by https://github.com/Homebrew/homebrew-core/pull/60290 for now

**Comment by extrawurst** [comment]
@dtrodrigues it should work now, right?

**Comment by dtrodrigues** [comment]
Can you rebase on top of master which now includes Rust 1.46.0 and force-push please?

**Comment by dtrodrigues** [comment]
I was rebasing https://github.com/Homebrew/homebrew-core/pull/60465 anyway for the rust upgrade so I did this one as well.

**Comment by extrawurst** [comment]
what is this now?
```
==> FAILED
clang-format@8:
  * Versioned formulae in homebrew/core should use `keg_only :versioned_formula`
Error: 1 problem in 1 formula detected
```

**Comment by dtrodrigues** [comment]
It got stuck in between a formula being merged and  https://github.com/Homebrew/brew/pull/8371 being merged, but now that it is, I've restarted the CI.

However, I did try and test this version of gitui locally and it failed, so the test may need to be adjusted.

**Comment by SMillerDev** [comment]
@MikeMcQuaid you merged this one right?

**Comment by MikeMcQuaid** [comment]
@SMillerDev Yes, it's fixed now.

**Comment by dtrodrigues** [comment]
Looks like `SHA:` got changed to `Sha:` in this commit https://github.com/extrawurst/gitui/commit/a95ffd7bcc55bacf8925a8d637f2d906b30932c3

**Comment by extrawurst** [comment]
wow sorry for that, I did not even realize it when accepting the PR 🙈
changed the test script accordingly

**Review by dtrodrigues — APPROVED** [review]
I squashed your commit which updated the test (which sounds like the change was unintentional, part of the reason we have tests). I've approved this PR now so it'll get merged as soon as CI passes again. Thanks work your patience while we worked through things, @extrawurst!

**Review by dtrodrigues — APPROVED** [review]

**Comment by extrawurst** [comment]
@dtrodrigues I have to thank, keep up the great work!

**Pull request closed without merging**
