### PR TITLE
coq 8.8.2

### PR DESCRIPTION
**Pull request by thomasheartman**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
```
==> /usr/local/opt/coq/bin/coqc -R /usr/local/Cellar/math-comp/1.7.0_2/lib/coq/user-contrib/mathcomp mathcomp testing.v
File "./testing.v", line 1, characters 0-43:
Error:
Compiled library mathcomp.ssreflect.ssreflect (in file /usr/local/Cellar/math-comp/1.7.0_2/lib/coq/user-contrib/mathcomp/ssreflect/ssreflect.vo) makes inconsistent assumptions over library Coq.Init.Notations
```
`math-comp` depends on `coq` and its test is failing with this new version of `coq`. `math-comp` states that they are compatible with `coq` 8.8 so they don't expect breaking changes. This should be reported upstream to math-comp.

**Comment by apjanke** [comment]
Looks like `math-comp` just needs a rebuild against the updated `coq`. This is common, and one of the things Homebrew's tests are designed to catch.

This can be accomplished with a "revision bump" to math-comp. In this same PR, but in a separate commit, change `revision 2` to `revision 3` in `math-comp.rb`. (Use "math-comp: revision bump for coq 8.8.2" as the commit comment.) This will cause Homebrew to rebuild math-comp against the updated coq as part of this PR, and it will be happy. (I tested this locally.)

**Comment by Moisan** [comment]
Thank you @t-hart for your contribution and sorry for the false alert. Thanks @apjanke for the pointer!

**Comment by fxcoudert** [comment]
Thanks @t-hart for the pull request

**Comment by t-hart** [comment]
Thanks for finishing up the pull request there; apologies for my tardiness :)

**Comment by apjanke** [comment]
🎉

**Pull request closed without merging**
