### PR TITLE
faas-cli 0.10.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
16:24:57 ==> /usr/local/Cellar/faas-cli/0.10.0/bin/faas-cli deploy -yaml test.yml 2>&1
16:24:57 ==> /usr/local/Cellar/faas-cli/0.10.0/bin/faas-cli template pull 2>&1
16:24:57 Error: faas-cli: failed
16:24:57 An exception occurred within a child process:
16:24:57   Test::Unit::AssertionFailedError: <0> expected but was
16:24:57 <1>.

**Comment by alexellis** [comment]
Hi, thanks for the notification.

Do we know who wrote those unit tests? Are they OpenFaaS code, or ruby?

**Comment by chenrui333** [comment]
@alexellis, 👋, what do you mean by unit tests (this formula?)?

**Comment by chenrui333** [comment]
Still failed locally (Catalina OS)
$ brew test faas-cli
Testing faas-cli
==> /usr/local/Cellar/faas-cli/0.10.3/bin/faas-cli deploy -yaml test.yml 2>&1
==> /usr/local/Cellar/faas-cli/0.10.3/bin/faas-cli template pull 2>&1
==> /usr/local/Cellar/faas-cli/0.10.3/bin/faas-cli new --list
==> /usr/local/Cellar/faas-cli/0.10.3/bin/faas-cli deploy -yaml test.yml
Error: faas-cli: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.

**Comment by chenrui333** [comment]
try to upgrade to the latest release to see how it goes.

**Comment by alexellis** [comment]
Thank you

**Comment by chenrui333** [comment]
np. :)

**Pull request closed without merging**
