### PR TITLE
protobuf 3.15.3

### PR DESCRIPTION
**Pull request by Loyalsoldier**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Moisan** [comment]
Currently fails on 
```
Error: 2 failed steps!
brew install --verbose --build-bottle apache-arrow
brew test --retry --verbose knot-resolver
```

**Comment by Bo98** [comment]
`apache-arrow` patch: https://github.com/apache/arrow/commit/06c795c948b594c16d3a48289519ce036a285aad.patch?full_index=1

**Comment by Bo98** [comment]
`knot-resolver` is a `brew` bug which I'll fix in a moment.

**Comment by carlocab** [comment]
On ARM and Mojave:

```
Error: 2 failed steps!
brew linkage --test libphonenumber
brew test --retry --verbose libphonenumber
```

`libphonenumber` probably needs a revision bump. However, we should probably wait until the Catalina and Big Sur nodes are done, to make sure there's nothing else.

Before giving `libphonenumber` a revision bump, be sure to rebase against `origin/master`, as `libphonenumber` also just got a revision bump here: #71274

**Comment by Loyalsoldier** [comment]
> On ARM and Mojave:
> 
> ```
> Error: 2 failed steps!
> brew linkage --test libphonenumber
> brew test --retry --verbose libphonenumber
> ```
> 
> `libphonenumber` probably needs a revision bump. However, we should probably wait until the Catalina and Big Sur nodes are done, to make sure there's nothing else.
> 
> Before giving `libphonenumber` a revision bump, be sure to rebase against `origin/master`, as `libphonenumber` also just got a revision bump here: #71274

Rebased. Bumped.

**Comment by carlocab** [comment]
Rebased against master to incorporate workaround for the Bintray outage.

**Comment by Bo98** [comment]
Whoever merges this: you might have to strip out any `root_url` created by bottle commits, due to the differing `HOMEBREW_BOTTLE_DOMAIN` between when the bottle JSON were generated (in this CI) and publish time.

**Review by carlocab — APPROVED** [review]
On it.

Thanks, @Loyalsoldier, @Bo98.

**Pull request closed without merging**
