### PR TITLE
mac 4.92 (new formula)

### PR DESCRIPTION
**Pull request by AlexaraWu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
This needs a license check https://monkeysaudio.com/license.html

**Comment by javian** [comment]
Just in case you try and download the source package manually its a "tar(zip)bomb" so it extracts to the current directory.

**Comment by SMillerDev** [comment]
Yeah, that's not a valid open source license. That unfortunately means that we can't accept the pull request per https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by SMillerDev** [comment]
Yeah, that's not a valid open source license. That unfortunately means that we can't accept the pull request per https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Pull request closed without merging**
