### PR TITLE
sourcekitten 0.23.0

### PR DESCRIPTION
**Pull request by jpsim**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jpsim** [comment]
Passed on High Sierra but failed on Mojave and Sierra. Interesting CI error:

> 21:57:49 stderr: fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': SSL certificate problem: Couldn't understand the server certificate format

**Comment by zbeekman** [comment]
I re-ran the tests. [It looks like swift tools](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/40553/version=sierra/testReport/junit/brew-test-bot/sierra/install___build_bottle_sourcekitten/) is too old on sierra?

```
rm -rf "/private/tmp/sourcekitten-20190409-52323-1klkn7v/SourceKitten.dst"
swift package clean
error: package at '/private/tmp/sourcekitten-20190409-52323-1klkn7v' requires a minimum Swift tools version of 4.2.0 (currently 4.0.0)
make: *** [build_with_disable_sandbox] Error 1
```

**Comment by jpsim** [comment]
The formula has the required Xcode version needed to build set to 10.0, which ships with Swift 4.2. So why is this being run on CI with Swift 4.0?

**Comment by norio-nomura** [comment]
Xcode 10.0 requires a Mac running macOS 10.13.6 or later.
It seems like a bug in CI that CI is trying to create a bottle for macOS 10.12 Sierra even though it declares Xcode 10.0 necessary for build.

**Review by zbeekman — DISMISSED** [review]
Please follow @norio-nomura's advice and add a dependency on `:macos => :high_sierra` and drop the `:xcode => "6.0"` dependency. If Xcode is a runtime dependency, then please also drop the `:build` qualification from the Xcode 10.0 dependency.

e.g.,
```
depends_on :xcode => "10.0"
depends_on :macos => :high_sierra
```

**Comment by norio-nomura** [comment]
> - what are the runtime Xcode/macOS version dependencies for the binary package?

I think that runtime dependency is still Xcode 6.0, but it is not realistic to prepare the environment now, there would be no need to describe that runtime dependency is `:xcode => "6.0"` separately from build time dependency.

> - what are the build Xcode/macOS version dependencies for the from-source build?

The source code itself does not depend on a specific macOS version and can be built with Swift 4.2 (Xcode 10.0) or later.

**Comment by MikeMcQuaid** [comment]
@norio-nomura Yes. Found a bug: https://github.com/Homebrew/brew/pull/6002

**Comment by jpsim** [comment]
The reason why we have different runtime and buildtime Xcode dependencies:

```ruby
depends_on :xcode => ["10.0", :build]
depends_on :xcode => "6.0"
```

Is that Xcode 10.0+ is required to _build_ SourceKitten, but it needs an Xcode version (or Xcode CLT) installed from Xcode 6.0 or later, since we depend on finding `sourcekitd.framework` at runtime (it's not re-packaged as part of this tool). `sourcekitd.framework` was introduced in Xcode 6.0. So a user could download a prebuilt bottle built with Xcode 10.2 onto their system where they only have Xcode 6.0 installed and the tool would work.

**Comment by MikeMcQuaid** [comment]
Thanks so much again for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @jpsim!

**Comment by jpsim** [comment]
No thank you, digging into this took some work on many people's part, so thanks for taking the time to do things right 👍

**Pull request closed without merging**
