### PR TITLE
Use HTTPS in homepages, comments and caveats (1/3)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vszakats** [comment]
This will be probably to large for Jenkins. None of these updates changes anything that should influence the build of these packages though. (Only homepages, comments and caveat texts were touched.)

**Comment by vszakats** [comment]
Removed `grafana` in favour of this comment: https://github.com/Homebrew/homebrew-core/pull/9918/files#r107021359

**Comment by vszakats** [comment]
Should I split this to multiple PRs, or can this be fast-tracked to merge with the existing CI-timeout? (This PR is only brew-audit-passed homepage/comment/caveat-text changes, so no actual builds are affected.)

**Comment by vszakats** [comment]
Split off compilers to #11439.

**Comment by vszakats** [comment]
Split off more to #11441.

**Comment by vszakats** [comment]
Anything else missing to get this merged? These are brew-audited and fairly innocent homepage/comment/caveat-text updates, so any CI failure is unrelated.

**Comment by MikeMcQuaid** [comment]
Thanks again @vszakats!

**Comment by vszakats** [comment]
Thanks a lot @MikeMcQuaid!

**Pull request merged**
