### PR TITLE
ffmpeg: patch for openjpeg 2.3 compatibility

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/Homebrew/homebrew-core/issues/19094.

CC @zmwangx

### CODE REVIEW

**Comment by zmwangx** [comment]
👍 Mailing list reference: https://ffmpeg.org/pipermail/ffmpeg-devel/2017-October/217389.html.

**Comment by kieranjol** [comment]
Wow, thanks so much for the quick fix!

**Comment by ilovezfs** [comment]
@zmwangx thanks for the mailing list reference :heart:

**Comment by ilovezfs** [comment]
@kieranjol you're welcome!

**Comment by kieranjol** [comment]
❤️

**Pull request merged**
