### PR TITLE
angular-cli 1.1.0, 1.2.0-beta.0 (devel)

### PR DESCRIPTION
**Pull request by cglong**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
`brew audit` fails with
```
Error: 1 problem in 1 formula
angular-cli:
  * devel version 1.1.0-rc.2 is older than stable version 1.1.0
```
In general if there are upgrades for both stable and devel, they should be done in one commit in one PR with a commit title like
```
tomcat 8.5.15, 9.0.0.21 (devel)
```
which will prevent the audit failure.

**Comment by ilovezfs** [comment]
:green_apple: Shipped! Thanks @cglong

**Comment by cglong** [comment]
Thanks @ilovezfs! 😄

**Pull request closed without merging**
