### PR TITLE
erlang@21 21.3.8.20

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by carlocab** [comment]
Previous attempt: #69412

It seems this just doesn't build on Big Sur, so I've added a
```ruby
depends_on maximum_macos: [:catalina, :build]
```
to reflect that.

**Comment by SMillerDev** [comment]
That just skips the build. Is there no component that we can define that it doesn't work with on Big Sur? This would mean that it's silently marked as succeeding until someone notices and tries to remove it.

**Comment by carlocab** [comment]
>That just skips the build.

Yes, that was my intention.

>Is there no component that we can define that it doesn't work with on Big Sur?

Not sure what you mean by this. I tried out the existing Catalina bottle on Big Sur, and it seems to work. The issue is that the patch to fix the build for Big Sur hasn't been backported to this version, so it just won't build on Big Sur.

We can also drop the dependency so that CI will complain every time this formula is updated. However, I don't think Big Sur failures should block version bumps, since this formula doesn't have a Big Sur bottle anyway. That's what we've done for other formulae that didn't have Big Sur bottles yet.

**Comment by gromgit** [comment]
@carlocab , please try applying this backported Big Sur patch: https://github.com/erlang/otp/commit/99fc87254e07fbd7bf4f9a02966a455846d5d017.patch?full_index=1

**Comment by SMillerDev** [comment]
> We can also drop the dependency so that CI will complain every time this formula is updated. However, I don't think Big Sur failures should block version bumps, since this formula doesn't have a Big Sur bottle anyway.

It doesn't have to be blocking just because it fails. We can make an informed decision to merge anyway when CI complains.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
