### PR TITLE
mpir: fix build on Xcode 12

### PR DESCRIPTION
**Pull request by mitchblank**
I opened a PR on upstream package https://github.com/wbhart/mpir/pull/292 which I am importing here.  Does require regenerating `./configure` script, of course.

### CODE REVIEW

**Comment by mitchblank** [comment]
```
==> brew audit mpir --online --git --skip-style
==> FAILED
mpir:
  * The URL http://mpir.org/ should use HTTPS rather than HTTP
  * Stable: The URL http://mpir.org/mpir-3.0.0.tar.bz2 should use HTTPS rather than HTTP
Error: 2 problems in 1 formula detected
```

**Comment by SMillerDev** [comment]
can it just use a github url?

**Comment by mitchblank** [comment]
> can it just use a github url?

Doesn't homebrew usually prefer the upstream's "download" link where available?

One issue with the github download links (when non-"official") is that they usually have a different sha256 since they're tar'ed up by github instead of the package's release process:
```
$ curl 'https://codeload.github.com/wbhart/mpir/tar.gz/mpir-3.0.0' | sha256sum
86a5039badc3e6738219a262873a1db5513405e15ece9527b718fcd0fac09bb2  -
```

**Comment by SMillerDev** [comment]
> Doesn't homebrew usually prefer the upstream's "download" link where available?

That's true, but personally I prefer HTTPS and a functioning homepage a bit more. So if the main one will have HTTP I'd prefer GH.

**Comment by mitchblank** [comment]
> So if the main one will have HTTP I'd prefer GH.

But that just isn't the case.

Let me review the history of this PR:
* This formula as it exists in `master` today uses `http://`
* I made an unrelated fix to this formula.  It passed `brew test` and `brew audit --strict` so I submitted it
* CI rejected because it uses even stricter `brew audit` flags and those noticed that the "http" URLs are actually accessible over https as well.
* Even though those lines were there before I touched the formula, I dutifully changed the `http:` to `https:` on those lines, and then CI was hapy 
* You (and apparently @chenrui333) are now objecting of this change *from* `http` *to* `https`

At this point I am completely confused about what you want.  Are you saying that we should *not* use HTTPS *except* for GH URLs?  That doesn't seem to be a rule in common usage -- there are lots of non-GH https URLs throughout the formulae corpus.

Honestly the objections people make to PRs on this project are just baffling to me.

**Comment by SMillerDev** [comment]
> At this point I am completely confused about what you want. Are you saying that we should not use HTTPS except for GH URLs? That doesn't seem to be a rule in common usage -- there are lots of non-GH https URLs throughout the formulae corpus.

I must have misread the file the first time since I was sure it was changing from https to http. If this is not the case I have no objections.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
