### PR TITLE
prettier 2.8.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by derrabus** [comment]
Is there something I can do about the failure on Catalina?

**Comment by carlocab** [comment]
Rebase when this is finished: https://github.com/Homebrew/homebrew-core/actions/runs/3532425551

**Comment by carlocab** [comment]
You can rebase now.

**Review by SMillerDev — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you!

**Pull request closed without merging**
