### PR TITLE
alertmanager 0.15.1 (new formula)

### PR DESCRIPTION
**Pull request by azalio**
New formula for Prometheus alertmanager package.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by azalio** [comment]
Hello! What is wrong? I can't see tests status.

**Comment by azalio** [comment]
@fxcoudert thanks!

**Comment by fxcoudert** [comment]
The makefile is running `go get`, which is not acceptable for Homebrew. All source and dependencies need to be downloaded as resources.

**Comment by azalio** [comment]
`depends_on "go-bindata" => :build` added.

**Comment by fxcoudert** [comment]
Yes, the makefile needs to be modified, or the build process modified, so that resources are downloaded through Homebrew. Given the current state, I am closing this PR for now, but please feel free to ping us here or open a new pull request once the formula builds without `go get`.

**Pull request closed without merging**
