### PR TITLE
hlint 2.1.21

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
19:06:19 cabal: The program 'alex' version >=3.1 is required but it could not be found.
19:06:19 
19:06:19 cabal: Leaving directory '/private/tmp/cabal-tmp-57994/ghc-lib-parser-0.20190516'
19:06:19 Downloading  hashable-1.2.7.0
19:06:19 Downloaded   hashable-1.2.7.0
19:06:19 Starting     hashable-1.2.7.0
19:06:19 Building     hashable-1.2.7.0
19:06:19 Completed    dlist-0.8.0.6
19:06:19 Completed    cmdargs-0.10.20
19:06:19 Completed    hashable-1.2.7.0
19:06:19 cabal: Error: some packages failed to install:
19:06:19 ghc-lib-parser-0.20190516-7wxfXz0CaaO93uVMFZLo8q failed during the configure
19:06:19 step. The exception was:
19:06:19 ExitFailure 1
19:06:19 
19:06:19 
19:06:19 ==> Formula
19:06:19 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hlint.rb
19:06:19 ==> Configuration
```

**Comment by ndmitchell** [comment]
As you can see in https://hackage.haskell.org/package/ghc-lib-parser-0.20190516/ghc-lib-parser.cabal there is a line:

```
    build-tools: alex >= 3.1, happy >= 1.19.4
```

This means that to build ghc-lib-parser the tools `alex` and `happy` must be installed. Note that the package `haskell-src-exts` (which HLint also depends on) has a dependency on:

```
  Build-Tools:          happy >= 1.19
```

So I suggest you look at whatever homebrew is doing to install that package (e.g. does it pick up the `happy` from metadata, or is there a hardcoded list somewhere?) and copy that for `ghc-lib-parser`.

**Comment by chenrui333** [comment]
@ndmitchell taking an action now.

**Comment by chenrui333** [comment]
Should be good now!

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
