### PR TITLE
curl 7.81.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
The Linux build was green for the previous version. Looks like 2 tests broke due to this change.

**Comment by carlocab** [comment]
`asuka` seems unrelated. Also seen at #92531. I'm going to guess the same is true about `zurl`

**Comment by iMichka** [comment]
I have a fix for `Asuka`: #92656

**Comment by iMichka** [comment]
`zurl` works with the previous curl version, but not with this one. So this does introduce a regression somewhere.

**Review by carlocab — APPROVED** [review]
It seems likely to me that the `zurl` is not actually broken, and that its test just needs updating.

Even if that's wrong, it seems unreasonable to delay a `curl` version bump to avoid breaking a formula that has had three downloads in the past year.

CC @homebrew/core in case someone has objections. (Or if someone wants to fix `zurl`...)

**Comment by iMichka** [comment]
I have opened an issue upstream: https://github.com/fanout/zurl/issues/20

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
