### PR TITLE
sqlite 3.30.1, dbhash 3.30.1, sqldiff 3.30.1, sqlite-analyzer 3.30.1

### PR DESCRIPTION
**Pull request by tommyang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by SMillerDev** [comment]
@tommyang can you update to 3.30.1? https://github.com/Homebrew/homebrew-core/pull/45220 will become duplicate then.

**Comment by tommyang** [comment]
@SMillerDev done

**Comment by EricFromCanada** [comment]
Only issues are tests timing out on 10.13 and [conjure-up](https://github.com/Homebrew/homebrew-core/pull/44831) & docker-compose tests on 10.15. I'd say this is good to go.

**Pull request closed without merging**
