### PR TITLE
 gnu-cobol: rename to gnucobol 

### PR DESCRIPTION
**Pull request by GitMensch**
following the package rename from 2017
as well as the renaming in other known package managers

follow-up to #53927 as requested in #57247 (and others)

I _think_ that `brew` is now possibly the only one that has `install gnu-cobol` instead of `install gnucobol` (and ideally the rename entry will automatically do the right thing if the installation that used the old name is updated/requested to be installed).

### CODE REVIEW

**Comment by GitMensch** [comment]
`brew audit` complains about `depends_on "berkeley-db"`, wanting `uses_from_macos "berkeley-db"` - but doing so results in either the wrong db.h found or is just too old.

How to handle that?

**Comment by GitMensch** [comment]
Thanks for the not, I'll adjust that. Question: What bison version will be taken from macOS and can I force a bison3+ version this way or should I also use `depends_on` when that is needed?

**Comment by ZhongRuoyu** [comment]
> What bison version will be taken from macOS and can I force a bison3+ version this way or should I also use `depends_on` when that is needed?

Whatever is provided by macOS will be used. On my latest Sonoma it shows 2.3, so none of the macOS versions seem to qualify for `uses_from_macos`. `depends_on` seems suitable here.

```console
$ /usr/bin/bison --version
bison (GNU Bison) 2.3
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

When a dependency is provided by recent macOS releases but not older ones, we can use `uses_from_macos` with `since:`. See [`trurl.rb`](https://github.com/Homebrew/homebrew-core/blob/f5d71e0c2c3f2cc081743788c20097c7bebe1d89/Formula/t/trurl.rb#L21), for example:

https://github.com/Homebrew/homebrew-core/blob/f5d71e0c2c3f2cc081743788c20097c7bebe1d89/Formula/t/trurl.rb#L21

**Comment by GitMensch** [comment]
Thank you for the further help - adjusted and pushed - waiting for human review.

**Review by chenrui333 — APPROVED** [review]
LGTM

**Review by ZhongRuoyu — APPROVED** [review]
Thank you @GitMensch!

**Pull request merged**
