### PR TITLE
pre-commit 0.8.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like there's missing resource(s).

**Comment by ilovezfs** [comment]
It's worse than that. Upstream has only published bdist_wheels for the last three versions not sdists, and the same for one of the dependencies, aspy.

**Comment by DomT4** [comment]
Any chance we can fetch that dependency from the project's GitHub/BitBucket/etc tarball & build it ourselves that way?

**Comment by ilovezfs** [comment]
@DomT4 The issue is just that it breaks poet, so it's annoying to fix. Nonetheless, PR should be fixed now.

**Comment by ilovezfs** [comment]
@DomT4 :green_apple:

**Comment by DomT4** [comment]
:shipit:

**Pull request closed without merging**
