### PR TITLE
ship: 0.54.1

### PR DESCRIPTION
**Pull request by jnozsc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

<s>found from https://github.com/Homebrew/homebrew-core/pull/59242
fixed from upstream by https://github.com/replicatedhq/ship/pull/1126</s>

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Review by chenrui333 — COMMENTED** [review]
you need `revision 1` after `license` field.

**Comment by jnozsc** [comment]
added

**Comment by laverya** [comment]
so I just released ship v0.54.1
which might be a better solution

**Comment by jnozsc** [comment]
@laverya absolutely! I update this PR to `v0.45.1`. Thanks for this quick release

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @laverya, @jnozsc!! ❤️

**Pull request closed without merging**
