### PR TITLE
gnutls 3.5.8

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
any reason to be concerned the rev-deps won't build going from 3.4.x to 3.5.x?

**Comment by DomT4** [comment]
According to upstream should be complete ABI/API compatibility between the old stable and new stable branches, so if we trust them, no.

**Comment by DomT4** [comment]
Sierra crashed though because I force pushed to fix an earlier problem that didn't happen locally due to already having a library installed, so you might want to kill the build and re-queue it, sigh.

**Comment by ilovezfs** [comment]
killed it if you want to force push

**Comment by DomT4** [comment]
Ta. Gave it the ol' rebase on master & force push trick.

**Comment by ilovezfs** [comment]
Thanks. The secret rebuild button. Should put a GUI on it.

**Comment by DomT4** [comment]
Seems to have passed without one or more of the CIs throwing a tantrum this time at least 😄

**Comment by ilovezfs** [comment]
Shipped! Thanks Dom

**Pull request closed without merging**
