### PR TITLE
ringojs 2.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
still with java8
https://github.com/ringo/ringojs/blob/f1a99c6f0e5e4b512ffd91246ac65bd712b47e52/debian/rules#L13

**Review by dtrodrigues — APPROVED** [review]

**Comment by jonchang** [comment]
The java11 work seems to be tracked in: https://github.com/ringo/ringojs/pull/406

It may be possible to migrate this soon if that patchset gets merged.

**Comment by botic** [comment]
> still with java8
> https://github.com/ringo/ringojs/blob/f1a99c6f0e5e4b512ffd91246ac65bd712b47e52/debian/rules#L13

It runs with Java 11, but we don't recommend it at the moment. Ringo 3.0.0 will be the next release with full Java 11 support.

**Comment by chenrui333** [comment]
> > still with java8
> > https://github.com/ringo/ringojs/blob/f1a99c6f0e5e4b512ffd91246ac65bd712b47e52/debian/rules#L13
> 
> It runs with Java 11, but we don't recommend it at the moment. Ringo 3.0.0 will be the next release with full Java 11 support.

@botic, thanks for confirming it. 😄

**Pull request merged**
