### PR TITLE
reflex 1.1.2

### PR DESCRIPTION
**Pull request by genivia-inc**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please rebase on top of master.

**Comment by genivia-inc** [comment]
I cherry-picked 1d9fb15. I tried `git -rebase -i HEAD~3` to squash 3 commits into one and `git rebase -i master` but that didn't get me anywhere because of errors.

**Comment by fxcoudert** [comment]
You currently have five commits, and the pull request does not apply cleanly in our CI. Don't use merge commits.

**Comment by genivia-inc** [comment]
I know, but it seemed that I can't do anything about that. Git failed with error messages when rebasing. Now I tried `git rebase -I HEAD~5` but that pulled in a lot of stuff (700+) and now I'm stuck with 527 files I have to merge with conflicts to resolve. Nice. I think I should abandon this commit and start over.

**Comment by fxcoudert** [comment]
Or you can delete your branch, re-create it from master, apply a single commit, and force-push.

**Comment by genivia-inc** [comment]
"Or you can delete your branch, re-create it from master, apply a single commit, and force-push."

Ok, I did that by following https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md using rebase and force-push. I had to add some spaces to the formula to make a diff that can be pushed.

**Comment by genivia-inc** [comment]
It doesn't help much that I also cannot get `brew bump-formula-pr` to work, which is recommended but I can't specify url without a tag and when I add a tag it says I can't use tag with the url:

~~~
brew bump-formula-pr --url='https://github.com/Genivia/RE-flex/archive/v1.1.2.tar.gz' --sha256='89022d215be79e5b9d846711de44f7ac5176bab959f7c6ff456f00714c5783c3' --message='bump-formula-pr re-flex' re-flex
Error: re-flex: no --tag=/--revision= arguments specified!
~~~
~~~
brew bump-formula-pr --url='https://github.com/Genivia/RE-flex/archive/v1.1.2.tar.gz' --sha256='89022d215be79e5b9d846711de44f7ac5176bab959f7c6ff456f00714c5783c3' --message='bump-formula-pr re-flex' --tag=6142aaf re-flex
Error: Options --url and --tag are mutually exclusive.
~~~

**Comment by genivia-inc** [comment]
I'm afraid that trying to squash the commits to one will get us in the same trouble getting stuck trying to rebase and squash 6 commits into one. This is the worst experience I had in 30 years (compared to subversion, CVS etc.) Because the current re-flex.rb formula is not usable due to a missing part, perhaps we can remove it and replace it with a new formula renamed to reflex.rb. IMO reflex.rb is preferable, shorter, and matches the name of the tool and it does not clash with existing formulas. What do you guys think?

**Comment by fxcoudert** [comment]
`brew bump-formula-pr re-flex --url=https://github.com/Genivia/RE-flex/archive/v1.1.2.tar.gz` works.
I've opened #38090

**Pull request closed without merging**
