### PR TITLE
freetype 2.10.2

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Continuation of https://github.com/Homebrew/homebrew-core/pull/54504, which may be fixed after the merging of https://github.com/Homebrew/homebrew-core/pull/56379.

**Comment by miccal** [comment]
`brew test --verbose genometools` fails as in https://github.com/Homebrew/homebrew-core/pull/55922.

**Comment by miccal** [comment]
`genometools` has been bumped in https://github.com/Homebrew/homebrew-core/pull/55922 which has fixed its failing tests.

**Comment by miccal** [comment]
The test for `genometools` now passes, but still getting the same error for `lesstif`.

**Comment by miccal** [comment]
There are two ways that I can think of to fix the `brew link lesstif` error -- pass either the `--disable-man`or the `"--mandir=#{man}` option to `system "./configure"`, but I am not sure which way would be preferred?

**Comment by miccal** [comment]
@SMillerDev @chenrui333 all tests are passing now -- could you please check that what I have done here is acceptable.

Thank you.

**Review by chenrui333 — COMMENTED** [review]
lgtm ❤️

**Review by SMillerDev — APPROVED** [review]
Thanks @miccal   ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
