### PR TITLE
dshb: remove

### PR DESCRIPTION
**Pull request by fxcoudert**
dshb never compiled on macOS 10.12 or 10.13. It was reported upstream (https://github.com/beltex/dshb/issues/36) but no activity on the bug. It has small number of downloads (21 in the last month). We suggested in September 2016 that we would boneyard it if no activity was forthcoming, I think now is time to do so.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Let's use an or_later bottle instead, since upstream development is still active and user count isn't 0.

**Comment by fxcoudert** [comment]
There is a patch for the issue that is 1 year old (https://github.com/beltex/dshb/pull/37) with no action. 1 series of 6 documentation-related commits in 1 year. I guess we don't define _“active”_ in the same way.

**Comment by ilovezfs** [comment]
CC @beltex we really need dshb to compile on 10.12 and 10.13.

**Comment by ilovezfs** [comment]
@fxcoudert I've opened another issue here: https://github.com/beltex/dshb/issues/40.

**Comment by ilovezfs** [comment]
Also, it looks like https://github.com/ealeksandrov/dshb works (see https://github.com/beltex/dshb/pull/37#issuecomment-311789388).

**Pull request closed without merging**
