### PR TITLE
bup: use system Python, update vendored dependencies

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> /usr/local/Cellar/bup/0.30_1/bin/bup init
/usr/local/Cellar/bup/0.30_1/bin/bup: /usr/local/Cellar/bup/0.30_1/libexec/bup.py: python3: bad interpreter: No such file or directory
/usr/local/Cellar/bup/0.30_1/bin/bup: line 2: /usr/local/Cellar/bup/0.30_1/libexec/bup.py: Undefined error: 0
Error: bup: failed
```

**Comment by dawidd6** [comment]
Changing to:
```
    ENV["PYTHON"] = Formula["python3"].opt_bin/"python3"
```

produces this durint `bup init`:
```
error: bup may crash with python versions other than 2, or eat your data
```

**Comment by Bo98** [comment]
There is some Python 3 work in place already for 0.31. I don't know if it'll be ready before the end of the year though.

**Comment by iMichka** [comment]
Let's go with system python then.

**Pull request closed without merging**
