### PR TITLE
formulae*: remove livecheck due to fuse deprecation

### PR DESCRIPTION
**Pull request by chenrui333**
formulae*: remove livecheck due to fuse

---

This would fix the livecheck report.

### CODE REVIEW

**Comment by carlocab** [comment]
Would
```
livecheck do
  skip "depends on deprecated formula"
end
```
be better?

**Comment by chenrui333** [comment]
> Would
> 
> ```
> livecheck do
>   skip "depends on deprecated formula"
> end
> ```
> 
> be better?

it got covered by the `deprecated!` directive, so no need to have livecheck anymore.

**Review by samford — APPROVED** [review]
I had been planning to address this after some time had passed and it was clear that these formulae were going to stay deprecated. Now seems like a good time, so thanks for taking care of this.

Just for good measure, I checked the `depends_on :osxfuse` formulae and none have been version bumped after they were deprecated, so I'm good with skipping them all due to the deprecation 👍

**Comment by carlocab** [comment]
@samford You're only meant to auto-squash single-formula PRs, I think 😅

**Comment by samford** [comment]
The [Maintainer Guidelines documentation](https://docs.brew.sh/Maintainer-Guidelines) says, "Use the GitHub squash & merge workflow where bottles aren’t required" and "...squash/merge via GitHub should be used for formulae where those formulae don’t need bottles or the change does not require new bottles to be pulled".

If this has changed in the interim time, the docs may need to be revisited.

**Comment by carlocab** [comment]
I wouldn't say that it's changed; I think we just have different interpretations of those guidelines. In either case, it would be good to clarify them.

**Comment by samford** [comment]
Ah, I think I understand your view now. The quoted squash/merge guidelines may have been written with the assumption that the PR only affects one formula. I agree it would be good to clarify the workflow for when a PR modifies multiple formulae but the changes don't affect bottles. I've seen different maintainers merge or squash/merge in this type of situation and the documentation should be clear about which is correct.

**Pull request merged**
