### PR TITLE
dependency-check 6.3.1

### PR DESCRIPTION
**Pull request by jeremylong**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by jeremylong** [comment]
Looks like a temporary resource availability issue:

```bash
Error:  Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta
```

I am now able to download https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta

Any chance someone could re-run the actions?

**Review by chenrui333 — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Rerunning it didn't help, and locally doing `curl https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta` twice will cause it to slow down to a crawl. Can you alert upstream of this?

**Comment by chenrui333** [comment]
^^ cc @jeremylong

**Comment by jeremylong** [comment]
I believe we are seeing some rate limiting by the NVD. In normal use, this is not an issue as dependency-check will build a database from the data feeds provided by the NVD and won't try to re-pull the data on every execution. Instead it will incrementally pull data as needed. However, for some build systems if you run ODC repeatedly and do not keep the data directory it will require re-pulling of the data. Thus, I believe the repeated testing of ODC in the homebrew build pipeline is what is causing the failure.  Two options:

1. Is there a way to cache a directory in the pipeline? I'm guessing no - as this would not be a normal concern for software distributed by homebrew.
2. I could distribute a handful of file files from the NVD with the test case for homebrew and configure the test to use the local files instead of the remote files.

**Comment by chenrui333** [comment]
ok it is all good now, merging this PR.

**Comment by chenrui333** [comment]
> I believe we are seeing some rate limiting by the NVD. In normal use, this is not an issue as dependency-check will build a database from the data feeds provided by the NVD and won't try to re-pull the data on every execution. Instead it will incrementally pull data as needed. However, for some build systems if you run ODC repeatedly and do not keep the data directory it will require re-pulling of the data. Thus, I believe the repeated testing of ODC in the homebrew build pipeline is what is causing the failure. Two options:
> 
> 1. Is there a way to cache a directory in the pipeline? I'm guessing no - as this would not be a normal concern for software distributed by homebrew.
> 2. I could distribute a handful of file files from the NVD with the test case for homebrew and configure the test to use the local files instead of the remote files.

Thanks for sharing these info (we will see if we need next time)

**Pull request closed without merging**
