### PR TITLE
cmark 0.26.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 More backticks purged.

**Comment by DomT4** [comment]
Crush them, crush them with fire 😉. LGTM, Thanks ILZ.

**Comment by zmwangx** [comment]
`make test` was removed in https://github.com/Homebrew/legacy-homebrew/pull/44246 because at that time the tests failed due to a Python upgrade — you know, test suites could sometimes be lagging. It could happen again. Again reason to go through the hassle?

**Comment by ilovezfs** [comment]
@zmwangx usually if `make test` is available and doesn't take a stupidly long time to run, I like to add it, but I don't mind removing it here if you'd prefer.

**Comment by zmwangx** [comment]
Actually I just tried the tests on Python 3.6.0a3, and they're fine, so no objection to bringing it back.

**Comment by ilovezfs** [comment]
@zmwangx are you OK with the changes to `test do`?

**Comment by zmwangx** [comment]
Yep, much better!

**Comment by ilovezfs** [comment]
:ship: 'd

**Pull request closed without merging**
