### PR TITLE
php@8.1 8.1.26

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by derrabus** [comment]
Same build failure as with #155271.

**Comment by chenrui333** [comment]
can you raise that into the upstream?

**Comment by derrabus** [comment]
The issue has been fixed upstream already. I've included a patch that we can remove on the next bump.

See https://github.com/Homebrew/homebrew-core/pull/155271#issuecomment-1825087743 for context. Thanks @cho-m for your helpful comment!

**Comment by derrabus** [comment]
The build is green. 🎉

**Review by iMichka — APPROVED** [review]
Thanks!

**Pull request merged**
