### PR TITLE
gitlab-ci-multi-runner 9.0.1

### PR DESCRIPTION
**Pull request by To1ne**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by To1ne** [comment]
cc @ilovezfs

**Comment by ilovezfs** [comment]
@tmaczukin Is 9.0.0 really the new current stable version?

**Comment by tmaczukin** [comment]
@ilovezfs Yes, it is. However, as always, there are some problems found in first days of usage. We will be releasing 9.0.1 soon (I hope that it will be done at upcoming Monday or Tuesday) so you can wait a few days and add support for 9.0.x version without bugs that are already known :)

**Comment by ilovezfs** [comment]
@tmaczukin sounds like a plan. Thanks!

**Review by ilovezfs — DISMISSED** [review]
Wait on 9.0.1 please

**Comment by tmaczukin** [comment]
@To1ne 9.0.1 is out

**Comment by ilovezfs** [comment]
@tmaczukin thanks for the heads up!

@To1ne do you mind refreshing this with 9.0.1?

**Comment by To1ne** [comment]
@ilovezfs @tmaczukin I've pushed the changes for 9.0.1.

**Review by ilovezfs — APPROVED** [review]
That was fast!

**Comment by ilovezfs** [comment]
@To1ne Thanks for the PR!

**Pull request closed without merging**
