### PR TITLE
kapacitor 1.0.0

### PR DESCRIPTION
**Pull request by gunnaraasen**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Bump to `1.0.0` stable. Removes dependency definitions since they're now vendored in the repo.

### CODE REVIEW

**Comment by apjanke** [comment]
Audit failure.

```
        Error: 1 problem in 1 formula
kapacitor:
  * require "language/go" is unnecessary unless using `go_resource`s
```

**Comment by gunnaraasen** [comment]
Thanks @apjanke. I've pushed up a fix.

Oddly, `brew audit --strict --online kapacitor` was passing on my local machine. Is there another flag to detect those errors in the future?

**Comment by zmwangx** [comment]
`brew audit --new-formula` should be the strictest one.

**Comment by gunnaraasen** [comment]
Ok, tests pass now. Thanks for the tip @zmwangx.

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
