### PR TITLE
GCC 8

### PR DESCRIPTION
**Pull request by fxcoudert**
Testing the second release candidate…

brew PR needs to be merged first: https://github.com/Homebrew/brew/pull/4125

### CODE REVIEW

**Comment by fxcoudert** [comment]
- opencoarrays fails to build: https://github.com/sourceryinstitute/OpenCoarrays/issues/527
- spades fails to build

**Comment by zbeekman** [comment]
@fxcoudert with 8.1 released are the errors discussed at https://github.com/sourceryinstitute/OpenCoarrays/issues/527 the same with 8.1 & OpenCoarrays? Has anything changed with last minute patching? If not, OC can try to figure out a work around or we could patch gcc for GFortran.

**Comment by fxcoudert** [comment]
@zbeekman I don't think GCC 8.1.0 was patched to fix the coarray issue, compared to the RC2. I will not delay shipping GCC 8.1.0 in Homebrew for opencoarrays (gcc has 55,217 installs per month, opencoarrays has 52).

We are generally reluctant to accept patches, unless they are already merged upstream and significantly impact the functionality of the software.

**Comment by zbeekman** [comment]
Sure, that's fine, I'm not asking you to delay releasing, mostly just
asking how to help.

**Comment by fxcoudert** [comment]
Having Fortran maintainers make sure that opencoarrays still builds when they commit coarray patches to the front-end seems like the best advice at this point :)

**Comment by zbeekman** [comment]
I completely agree. Especially when it's right before the F$*&ing release.
Sigh.

**Comment by fxcoudert** [comment]
Merging.

`siril` will be revision-bumped independently, as something happened to its bottle during the big CI job (bottle checksum mismatch)

**Pull request closed without merging**
