### PR TITLE
Migrate more formulas to openssl 1.1 (F/G)

### PR DESCRIPTION
**Pull request by fxcoudert**
Formula beginning with F and G, that depend on openssl and are not part of more complex dependency chains. Let's see how many build with openssl 1.1

### CODE REVIEW

**Comment by fxcoudert** [comment]
- `frag_find` has had only one release in 2013 and no development since. It has 2 installs per month. Removing.

**Comment by fxcoudert** [comment]
Trying to update freeswitch in https://github.com/Homebrew/homebrew-core/pull/43591

**Comment by fxcoudert** [comment]
`ftimes` does not support OpenSSL, is not actively maintained, has 1 install in the last month. Removing.

**Comment by raagha-b** [comment]
Hello @fxcoudert , I have brew install freetds@0.91 which is not available any more.
Which is the nearest alternative available for me to upgrade ?

**Comment by fxcoudert** [comment]
@raagha-b you should either update to the main `freetds` version, or maintain the old version in your own tap

**Pull request closed without merging**
