### PR TITLE
x264 r3018

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Failed to build gi-glib-2.0.23. The failure occurred during the configure
step.
Build log (
/private/tmp/komposition-20201023-47763-x7e0zm/komposition-0.2.0/.brew_home/.cabal/logs/ghc-8.8.4/g-glb-2.0.23-8849f8ab.log
):
[1 of 1] Compiling Main             ( /private/tmp/cabal-install.-47893/dist-newstyle/tmp/src-47893/gi-glib-2.0.23/dist/setup/setup.hs, /private/tmp/cabal-install.-47893/dist-newstyle/tmp/src-47893/gi-glib-2.0.23/dist/setup/Main.o )
Linking /private/tmp/cabal-install.-47893/dist-newstyle/tmp/src-47893/gi-glib-2.0.23/dist/setup/setup ...
Unknown GIR element "docsection" when processing namespace "GLib", aborting.
CallStack (from HasCallStack):
  error, called at lib/Data/GI/CodeGen/API.hs:199:16 in hskll-g-0.23.1-634cbf53:Data.GI.CodeGen.API
cabal: Failed to build gi-glib-2.0.23 (which is required by exe:komposition
from komposition-0.2.0 and exe:komposition-split from komposition-0.2.0). See
the build log above for details.
```

**Comment by chenrui333** [comment]
komposition build issue reported in [here](https://github.com/owickstrom/komposition/issues/104)

**Comment by jonchang** [comment]
https://github.com/Homebrew/homebrew-core/pull/63449

**Comment by fxcoudert** [comment]
Restarting CI now that komposition is deprecated

**Comment by jonchang** [comment]
Rebased and force pushed. Re-bumped revisions:

```
dropping c3d64c80f2fda4e7c69e3e4fedad1aab0315247b mpv: revision for x264 -- patch contents already upstream
dropping af643985711d303f7f7831eb194b6a2d284bba1e opencv: revision for x264 -- patch contents already upstream
dropping dd7ff3c089f116da559b9aed1674c910f35030de opencv@3: revision for x264 -- patch contents already upstream
dropping 781d4503dd7cab34924b56715df4fc5f6c89d000 openimageio: revision for x264 -- patch contents already upstream
dropping 1e4c99a018b32ae10d9c3bd0c731c33acadbce42 vapoursynth-sub: revision for x264 -- patch contents already upstream
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
