### PR TITLE
arangodb: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by p-linnane**
See #134251.

### CODE REVIEW

**Comment by Bo98** [comment]
> cc1: error: bad value ('merom') for '-march=' switch

Our `-march` filtering is probably messing it up - the CMake script is supposed to check if `-march=merom` is available and falls back to `core2` if not. We're also building an old version here so I'm guessing this issue has impacted updating the formulae.

3.11.x totally redos the architecture stuff so if we update to that it will require some care.

**Comment by p-linnane** [comment]
Yeah, I was unable to get us bumped to 3.11.1 a few days ago: https://github.com/Homebrew/homebrew-core/pull/134010

**Comment by cho-m** [comment]
Could try `core` instead though we will lose some optimization (SSSE3).

Part of reason we haven't been able to update ArangoDB is that they only support specific Clang/GCC versions, which is why we aren't able to use default compilers.

Looks like new LLVM/Clang behavior is causing build failure.

**Comment by carlocab** [comment]
Superseded by #135487.

**Pull request closed without merging**
