### PR TITLE
influxdb 1.8.0

### PR DESCRIPTION
**Pull request by russorat**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Test times out, I think we might need something stronger than SIGINT

**Comment by russorat** [comment]
@SMillerDev testing to see if increasing the sleep on line 100 will fix this.

**Comment by SMillerDev** [comment]
It won't, the test is being performed successfully. The server isn't killed correctly. Please use SIGTERM instead of SIGINT like I suggested.

**Comment by russorat** [comment]
@SMillerDev thanks! 🤞

**Comment by russorat** [comment]
Looks like the testing of chronograf failed, but chronograf was recently updated from 1.8.0 to 1.8.2 (https://github.com/Homebrew/homebrew-core/pull/53124) which might fix this. Any way to kick off those tests again?

**Comment by SMillerDev** [comment]
You can squash your commits (this needs to happen anyway)

**Pull request closed without merging**
