### PR TITLE
sgr: migrate to python@3.11

### PR DESCRIPTION
**Pull request by ryenus**
Update formula **sgr** to use python@3.11 instead of python@3.10, see the related pr https://github.com/Homebrew/homebrew-core/pull/114154

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    pglast/parser.c:282:12: fatal error: longintrepr.h: No such file or directory
      282 |   #include "longintrepr.h"
          |            ^~~~~~~~~~~~~~~
```

**Comment by ryenus** [comment]
```log
==> Testing sgr
  ==> /opt/homebrew/Cellar/sgr/0.3.12_1/bin/sgr cloud login --username homebrewtest -*** 2>&1
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/sgr/0.3.12_1/bin/sgr", line 5, in <module>
      from splitgraph.commandline import cli
    ...
    File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/target_postgres/__init__.py", line 15, in <module>
      from jsonschema import Draft7Validator, FormatChecker
  ModuleNotFoundError: No module named 'jsonschema'
```

**Comment by ryenus** [comment]
> ModuleNotFoundError: No module named 'attr'

It appears to need more dependencies, @singingwolfboy any suggestion? Asking for the sake of https://github.com/Homebrew/homebrew-core/pull/111649

<details>
<summary><b>Full error trace</b></summary>

```log
==> Testing sgr
==> /opt/homebrew/Cellar/sgr/0.3.12_1/bin/sgr cloud login --username homebrewtest -*** 2>&1
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/bin/sgr", line 5, in <module>
    from splitgraph.commandline import cli
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/splitgraph/commandline/__init__.py", line 46, in <module>
    from splitgraph.commandline.mount import mount_c
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/splitgraph/commandline/mount.py", line 11, in <module>
    from splitgraph.hooks.data_source import get_data_source, get_data_sources
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/splitgraph/hooks/data_source/__init__.py", line 12, in <module>
    from .fdw import (  # noqa
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/splitgraph/hooks/data_source/fdw.py", line 40, in <module>
    from splitgraph.ingestion.airbyte.data_source import delete_schema_at_end
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/splitgraph/ingestion/airbyte/data_source.py", line 45, in <module>
    from .utils import (
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/splitgraph/ingestion/airbyte/utils.py", line 4, in <module>
    from target_postgres.db_sync import column_type
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/target_postgres/__init__.py", line 15, in <module>
    from jsonschema import Draft7Validator, FormatChecker
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/opt/homebrew/Cellar/sgr/0.3.12_1/libexec/lib/python3.11/site-packages/jsonschema/exceptions.py", line 12, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
Error: sgr: failed

```
</details>

**Comment by singingwolfboy** [comment]
> > ModuleNotFoundError: No module named 'attr'
> 
> It appears to need more dependencies, @singingwolfboy any suggestion? Asking for the sake of #111649

I believe #119519 should solve this

**Pull request closed without merging**
