### PR TITLE
staq 3.2.2

### PR DESCRIPTION
**Pull request by vsoftco**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  SHA256: 3054a25dab7b49885b212482220e86c89aa7f7e9d902ccb9059e827b4e62d745
  Warning: Formula reports different sha256: e22dac337f98a73b6f59a4f667b01bc5381a0e950b64bf027e0512b350c1b634
```

**Comment by chenrui333** [comment]
checksum mismatch reported on linux

**Comment by vsoftco** [comment]
If this fails, I'll close the PR and re-open. I believe we pushed one commit after, then did brew update-pr. Thanks!!

**Comment by chenrui333** [comment]
> Thanks, since this fails, I'll close the PR and re-open. I believe we pushed one commit after, while we did brew update-pr. Thanks for your help!

I think you also need to remove the cached artifact as well, otherwise the sha would be the same when creating a new one (meaning the sha would still be different), can you stop creating new PRs?

**Pull request closed without merging**
