### PR TITLE
node-build 2.6.8

### PR DESCRIPTION
**Pull request by jasonkarns**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for the upgrade @jasonkarns!

**Comment by openreply-dleinhaeuser** [comment]
`brew upgrade` repeatedly gives the following error:

```
> brew upgrade
==> Upgrading 7 outdated packages, with result:
node-build 2.6.8, nodenv 1.1.1, npth 1.5, plantuml 1.2017.14, pngquant 2.10.1, pyenv 1.1.3, rbenv 1.1.1
==> Upgrading node-build 
==> Using the sandbox
==> Downloading https://github.com/nodenv/node-build/archive/v2.6.8.tar.gz
==> Downloading from https://codeload.github.com/nodenv/node-build/tar.gz/v2.6.8
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c98f7de6a749520fb7155c1b315f01804eb6554f8edb0d45bd7514f9e9a1dc44
Actual: 6c636ae7bcead1186ee392cd9974e764cb0ba82165396366d502987f0d3c466f
Archive: /Users/dleinhaeuser/Library/Caches/Homebrew/node-build-2.6.8.tar.gz
To retry an incomplete download, remove the file above.
```

Deleting `/Users/dleinhaeuser/Library/Caches/Homebrew/node-build-2.6.8.tar.gz` an trying again does not change anything.

Are others seeing this as well?

**Comment by ilovezfs** [comment]
@openreply-dleinhaeuser yeah

@jasonkarns did this get retagged?

**Comment by jasonkarns** [comment]
Yeah. There's something funky in the npm script that's tagging/pushing to github. I thought it got fixed before this PR was submitted.

**Comment by jasonkarns** [comment]
@ilovezfs I'll submit a fix

**Comment by ilovezfs** [comment]
Thanks Jason

**Comment by jasonkarns** [comment]
@ilovezfs https://github.com/Homebrew/homebrew-core/pull/16020

**Comment by ilovezfs** [comment]
@openreply-dleinhaeuser this should now be fixed

**Pull request merged**
