### PR TITLE
bbftp-client: fix homepage url, add license

### PR DESCRIPTION
**Pull request by FnControlOption**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

#88329

### CODE REVIEW

**Comment by carlocab** [comment]
@samford any ideas about the livecheck failure?

**Comment by samford** [comment]
> any ideas about the livecheck failure?

It works fine for me locally, so it's probably the same timeout issue we've been seeing on macOS CI (as in #88309 and many of the unfixed livecheck failures in #88329). I ran this again and, by chance, it passed on some macOS targets. I'm not familiar with our CI environment, so I have no idea what's causing the issue and I can't replicate it locally (macOS 12, ARM64).

In the short term, I'm working on creating PRs in homebrew/test-bot and homebrew/core to add a `--skip-livecheck` option to test-bot and a `CI-skip-livecheck` label here that's used in the `tests` workflow. I should have these up in a bit and this will at least allow us to work around this issue (where livecheck works locally but fails on CI) unless/until someone identifies the source of the issue on macOS CI.

Longer term, as you mentioned elsewhere, I would be interested to see if using brewed curl resolves this issue [on CI] like it does some others. We don't have a way of enabling this in livecheck at the moment and there's some groundwork to lay before it's possible. I have most of this work done already but I still need to create a PR for it and there will likely be some discussion around the shape of it, so this may take a bit to land. I'll try to get a PR up when I get a chance.

**Comment by carlocab** [comment]
Another idea, instead of skipping livecheck entirely, is to avoid making it a hard failure and just have @BrewTestBot spit out a warning or something. This would also be useful for other things we do in `test-bot`, I think.

I'm not sure what form the warning would take -- it probably shouldn't be in the CI log, because we typically don't look at it unless it's red. Maybe we can get @BrewTestBot to post a comment in the PR about it?

**Comment by FnControlOption** [comment]
Might the cause be some sort of rate limit or DDoS protection? But that would be unlikely if using Homebrew curl results in less errors.

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request merged**
