### PR TITLE
asciidoctor 2.0.12

### PR DESCRIPTION
**Pull request by ChrisBaker97**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Rylan12** [comment]
Can we try to update the resources that have newer versions?

**Comment by ChrisBaker97** [comment]
Looks like those [had to be reverted](https://github.com/Homebrew/homebrew-core/commit/60ed0cab9a7f28c8000aaa56eb94f40a3d89401a) just a week ago to pass tests on 2.0.11. Let me know if you still want me to try them again.

**Comment by Rylan12** [comment]
Ah, good find! No need then. Thanks for the PR!

**Review by Rylan12 — APPROVED** [review]

**Comment by ChrisBaker97** [comment]
Thanks @Rylan12. Just for my own knowledge, is there some (semi-)automated way to update these resources, or is it all manual copying of URLs and SHAs?

**Comment by Rylan12** [comment]
Currently, we have this only for Python formulae that are also available on PyPI because that seems to be where the majority of our resource blocks are. If you'd be interested in adding some tooling to help automate this for resources in other formulae, though, feel free! I think that would be very helpful.

**Comment by ChrisBaker97** [comment]
I was wondering because I'm not even sure how to start doing it manually, so this Ruby noob is probably not the best person for the job, but I'll keep that in mind as I figure stuff out.

**Comment by Rylan12** [comment]
Maybe a command that takes in a formula name, resource name, and new version/url and automatically modifies the files as needed (including figuring out what the correct sha is)? If you wanted, you could use the [`update-python-resources`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/update-python-resources.rb) command as a starting point but it's got a lot of python-specific stuff.

If you're unsure but potentially interested, maybe open a feature-request issue in [Homebrew/brew](https://github.com/Homebrew/brew) and you can get some feedback/tips form other maintainers

**Pull request closed without merging**
