### PR TITLE
pachi 12.84

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`. Incorporates several suggestions from #123060. 

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Bizzare failure on Linux:
```
==> Verifying checksum for 'f77ef811b4ebf31764486aa39169ce6d324ee9a5fa329bda0a5049dd5e085059--pachi-pachi-12.84.tar.gz'
/usr/bin/env tar --extract --no-same-owner --file /home/linuxbrew/.cache/Homebrew/downloads/f77ef811b4ebf31764486aa39169ce6d324ee9a5fa329bda0a5049dd5e085059--pachi-pachi-12.84.tar.gz --directory /tmp/d20231128-2878-d47kag
/usr/bin/env cp -pR /tmp/d20231128-2878-d47kag/pachi-pachi-12.84/. /tmp/pachi-20231128-2878-hs1hr9/pachi-pachi-12.84
/usr/bin/env tar --extract --no-same-owner --file /home/linuxbrew/.cache/Homebrew/downloads/9de2ffb988a7676aeecffc3ea12067c84de52aa7ff4cbded86340addb1f7fd23--pachi-12.84-linux-static.tgz --directory /tmp/d20231128-2878-bfxy8m
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by alebcay** [comment]
I can replicate the error on macOS if I attempt to read/unpack https://github.com/pasky/pachi/releases/download/pachi-12.84/pachi-12.84-linux-static.tgz using `gnu-tar`. macOS' built-in `tar` handles it just fine.

`file` reveals a possible root cause. A "regular" tarball (a bottle):

```
/Users/caleb/Library/Caches/Homebrew/downloads/fa50e9ca8de54101194d1ee3a5803affb4d608e1d99d7759e72c3e08c24bc4c1--llvm--17.0.5.monterey.bottle.tar.gz: gzip compressed data, was "llvm-bottle.tar", last modified: Tue Nov 14 08:22:39 2023, from Unix, original size modulo 2^32 1880627200
```

The `pachi` tgz:

```
pachi-12.84-linux-static.tgz: Zip archive data, at least v1.0 to extract, compression method=store
```

Indeed, `unzip -l pachi-12.84-linux-static.tgz` reads it just fine... so looks like it's actually a zip archive. My guess is macOS/`bsdtar` is just able to cope with that, while Linux/`gnu-tar` can't.

**Comment by EricFromCanada** [comment]
@alebcay Thanks for the tip; I've found a workaround.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Looks good. If you find some time, can you open an issue upstream about the tar/zip issue?

**Comment by lemonsqueeze** [comment]
Hi i'm Pachi maintainer,

Pachi shouldn't be in homebrew anymore, it was flagged for removal months ago :
There's no way to provide a decent Pachi build under homebrew guidelines.
See [PR123301](https://github.com/Homebrew/homebrew-core/pull/123301).

This build is a stunted nodcnn build, basically the equivalent of Pachi 11.00,
the state of the project as it was in 2015, almost 9 years ago.

**Pull request merged**
