### PR TITLE
ox 0.2.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Testing ox
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201108-58447-1js9f8q.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ox.rb --verbose
Error: ox: failed
An exception occurred within a child process:
  Errno::EIO: Input/output error @ io_write - /dev/ttys000
```

**Comment by vladimyr** [comment]
@chenrui333 Author is aware of this https://github.com/curlpipe/ox/issues/62
0.2.7 is in development, hopefully, it will bring fixes. 🤞

**Comment by chenrui333** [comment]
Thanks @vladimyr!!

**Comment by chenrui333** [comment]
Closing the PR for now.

**Comment by chenrui333** [comment]
#135686

**Pull request closed without merging**
