### PR TITLE
abyss 2.3.7

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Upstream has moved `btllib` to an external dependency. I don't see anything else that would use it, and it doesn't meet notability requirements so I'm adding it as a resource here.

**Comment by p-linnane** [comment]
Opened an upstream issue for the `btllib` build failure: https://github.com/bcgsc/btllib/issues/92

**Comment by p-linnane** [comment]
`btllib` failure was fixed by @parham-k. I've opened a new issue for the resulting `abyss` build failure: https://github.com/bcgsc/abyss/issues/466

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
💯

**Pull request merged**
