### PR TITLE
bazel 0.5.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@damienmg do you have any idea what's causing this?

```
.WARNING: /tmp/bazel_lufvwwzX/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_lufvwwzX/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
```

**Comment by damienmg** [comment]
/cc @kchodorow: we should remove that warning for this case.

The warning is safe to ignore.

**Comment by ilovezfs** [comment]
@damienmg thanks for taking a look!

**Comment by kchodorow** [comment]
I'm kind of surprised, I actually thought we already had.

**Pull request closed without merging**
