### PR TITLE
opencv: build both shared and static libs

### PR DESCRIPTION
**Pull request by jeroen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This uses the same strategy as e.g. the [poppler formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/poppler.rb#L71-L78) to build and install static libs with cmake.

Thank you for considering!

### CODE REVIEW

**Comment by ilovezfs** [comment]
Let's not bump the revision given the high user count.

**Comment by jeroen** [comment]
OK let me revert the bump.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by jeroen** [comment]
Thanks! 🚀

**Comment by ilovezfs** [comment]
Thanks again @jeroen! You're awesome

**Comment by jeroen** [comment]
Thanks! One question: `opencv.rb` currently has:

```
  depends_on "python"
  depends_on "python@2"
```

Could we make this dependency build-only? I would like to use the C++ library, but I am not interested in the python bindings.

**Comment by ilovezfs** [comment]
That sounds problematic to me because it's specifically using Homebrew's numpy so I'm imagining  a bunch of people seeing
```
python2.7 -c 'import cv2; print(cv2.__version__)'
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
```

```
python3 -c 'import cv2; print(cv2.__version__)'
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
```

and not knowing what to do about it, which a caveat is unlikely to address well since they tend to go unread.

If anything an `opencv-python` formula would probably be the way to go and remove all of the python bits from this one. I'm not sure it's worth it giving how little complaining we've had about the python deps here. You are the first I think.

**Comment by ilovezfs** [comment]
If you can figure out how to vendor `numpy` resource blocks into the formula in such a way that it doesn't need the `depends_on "numpy"` for those imports to work, then it could make sense to move the python deps to `=> [:build, :test]` only.

**Pull request closed without merging**
