### PR TITLE
glib 2.82.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
  [147/174] /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tools/g-ir-scanner --quiet --output=tests/offsets/Offsets-1.0.gir --no-libtool --reparse-validate --add-include-path /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/gir --add-include-path /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/gir --warn-all --warn-error --namespace=Offsets --nsversion=1.0 --include=GObject-2.0 --library=offsets-1.0 -L /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tests/offsets -I /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/tests/offsets -I /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/tests ../tests/offsets/offsets.c ../tests/offsets/offsets.h
  FAILED: tests/offsets/Offsets-1.0.gir 
  /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tools/g-ir-scanner --quiet --output=tests/offsets/Offsets-1.0.gir --no-libtool --reparse-validate --add-include-path /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/gir --add-include-path /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/gir --warn-all --warn-error --namespace=Offsets --nsversion=1.0 --include=GObject-2.0 --library=offsets-1.0 -L /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tests/offsets -I /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/tests/offsets -I /private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/tests ../tests/offsets/offsets.c ../tests/offsets/offsets.h
  ld: missing LC_LOAD_DYLIB (must link with at least libSystem.dylib) in '/private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tests/offsets/liboffsets-1.0.1.dylib'
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  linking of temporary binary failed: Command '['clang', '-o', '/private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tmp-introspect4u_m8i21/Offsets-1.0', '/private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tmp-introspect4u_m8i21/Offsets-1.0.o', '-L.', '-Wl,-rpath,.', '-L/private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tests/offsets', '-Wl,-rpath,/private/tmp/glib--gobject-introspection-20240827-9315-83pyv0/gobject-introspection-1.80.1/build/tests/offsets', '-loffsets-1.0', '-L/private/tmp/glib-20240827-9315-e9rpgg/glib-2.82.0/staging/lib', '-lgio-2.0', '-lgobject-2.0', '-lgmodule-2.0', '-lglib-2.0', '-lintl']' returned non-zero exit status 1.
```

**Comment by chenrui333** [comment]
```
  ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

- https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/515

**Comment by fxcoudert** [comment]
- The gobject-introspection resource needs the same patch as in https://github.com/Homebrew/homebrew-core/pull/183298 to fix https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/490
- Handle glibmm update at the same time

**Review by bevanjkay — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Dependent testing failure fixed at #183791.

**Review by cho-m — APPROVED** [review]

**Pull request merged**
