### PR TITLE
scipy 1.5.4

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Rylan12** [comment]
It doesn't look like the patch has made it into the release branch yet, but CI passed. Not sure, is that fine?

**Comment by chenrui333** [comment]
@Rylan12 this might be [the commit](https://github.com/scipy/scipy/commit/b8e47064f831a959ec2fbb01236de8276b546d87) that you are looking for, it is on the v1.5.4 source tree.

cc @sethtroisi

**Review by chenrui333 — APPROVED** [review]

**Comment by Rylan12** [comment]
That's the right commit, but it's on the `master` branch which differs from the `v1.5.4` tag. That commit hasn't been applied to the release branch yet. Either way, if it works without that change, not need to keep it.

**Comment by dtrodrigues** [comment]
It looks like the 1.5.4 release is intended to support Xcode 12 and Python 3.9:
https://github.com/scipy/scipy/releases/tag/v1.5.4
https://github.com/scipy/scipy/issues/12935#issuecomment-720172955

**Comment by chenrui333** [comment]
> It looks like the 1.5.4 release is intended to support Xcode 12 and Python 3.9:
> https://github.com/scipy/scipy/releases/tag/v1.5.4
> [scipy/scipy#12935 (comment)](https://github.com/scipy/scipy/issues/12935#issuecomment-720172955)

that is a better reference :)

**Pull request closed without merging**
