### PR TITLE
[TBC] add postgres-x2, successor of postgres-xc

### PR DESCRIPTION
**Pull request by ryenus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Let's be honest, this is yet to be completed, but by someone who has sufficient knowledge to build PGX2 on macOS, so here I just make a start point for those of you :P

### CODE REVIEW

**Comment by ryenus** [comment]
According to the latest [README][1], it's time to update [Postgres-XC Formula][2]:

> Postgres-XC is renamed to [Postges-X2][3] from 2015 after it was moved to [Github][4].

[1]: https://github.com/postgres-x2/postgres-x2/blob/master/README.md
[2]: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgres-xc.rb
[3]: https://postgres-x2.github.io/
[4]: https://github.com/postgres-x2/postgres-x2

**Comment by MikeMcQuaid** [comment]
Thanks for the PR @ryenus! Could you follow this guide to rename it from the old formula name: https://github.com/Homebrew/brew/blob/master/docs/Rename-A-Formula.md. Using the existing formula as a base (and seeing what small changes need made) would make things easier. Thanks!

**Comment by MikeMcQuaid** [comment]
Do you have anywhere on a postgres-xc site that points to this as the successor? Also, could you rebase this and fix merge conflicts? Thanks!

**Comment by bfontaine** [comment]
Ping?

**Pull request closed without merging**
