### PR TITLE
haproxy 1.9.0

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mnuic** [comment]
Hi, 
Can someone check this? Thanks

**Comment by javian** [comment]
@Moisan something must have happend in the last commit since
```
10:35:42 ==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/35421
10:35:45 ==> FAILED
10:35:45 fatal: ref HEAD is not a symbolic ref
10:35:45 ==> Fetching patch 
10:35:45 Patch: https://github.com/Homebrew/homebrew-core/pull/35421.patch
10:35:45 ==> Applying patch
10:35:45 Applying: haproxy 1.9.0
10:35:45 Using index info to reconstruct a base tree...
10:35:45 M	Formula/haproxy.rb
10:35:45 Falling back to patching base and 3-way merge...
10:35:45 Auto-merging Formula/haproxy.rb
10:35:45 CONFLICT (content): Merge conflict in Formula/haproxy.rb
10:35:45 error: Failed to merge in the changes.
10:35:45 Patch failed at 0001 haproxy 1.9.0
```

**Comment by fxcoudert** [comment]
This needs to be rebased on top of master

**Comment by Moisan** [comment]
Superseded by #36908.

**Pull request closed without merging**
