### PR TITLE
xrootd 5.5.5

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
(The GitHub releases seem to happen before the main website is updated.)

**Comment by pthariensflame** [comment]
What's going on with the Linux deps failure?  I didn't touch `root` or `libtiif`.

**Comment by p-linnane** [comment]
`root` depends on `xrootd`, so that's why it was tested.

That being said, `root` has issues and always fails testing right now.

**Review by p-linnane — APPROVED** [review]
This is marked as latest on Github, so no need to wait for the homepage.

**Pull request merged**
