### PR TITLE
ghc 8.10.3

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
Rebased against master to incorporate fix for `allureofthestars` (https://github.com/Homebrew/homebrew-core/pull/67259).

**Comment by fishtreesugar** [comment]
Adga build failed because the bound of transformers is too tight, and fixed in [upstream](https://github.com/agda/agda/commit/76278c23d447b49f59fac581ca4ac605792aabbc)

**Comment by carlocab** [comment]
Thanks. Would you know if any of the other builds are failing because of version specifications that are unnecessarily strict"?

**Comment by fishtreesugar** [comment]
> Thanks. Would you know if any of the other builds are failing because of version specifications that are unnecessarily strict?

I roughly browse the error message,  it seem that is  the only one  error cause by too strict version bound.

**Comment by fishtreesugar** [comment]
```
Last 150 lines from /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs/elm/02.cabal:
2020-12-21 02:52:37 +0000

cabal
v2-install
--jobs=6
--max-backjumps=100000
--install-method=copy
--installdir=/usr/local/Cellar/elm/0.19.1/bin

cabal: Invalid package ID: .
```
elm failed with weird error message, I guess it cause by cabal-install. I will investigate it later.

**Comment by fishtreesugar** [comment]
@carlocab carlocab I patched the elm formula #67404, you can give it a try.

**Comment by SeekingMeaning** [comment]
11.0:

```
brew linkage --test allureofthestars
brew install --build-from-source elm
brew install --build-from-source jupyterlab
brew fetch --retry youtube-dlc
brew fetch --retry youtube-dlc
brew install --verbose --build-bottle git-annex
brew install --verbose --build-bottle hledger
```

10.15:

```
brew linkage --test allureofthestars
brew install --build-from-source bond
brew install --build-from-source elm
brew fetch --retry youtube-dlc
brew fetch --retry youtube-dlc
```

10.14:

```
brew linkage --test allureofthestars
brew install --build-from-source bond
brew install --build-from-source elm
brew fetch --retry youtube-dlc
brew fetch --retry youtube-dlc
```

**Comment by fishtreesugar** [comment]
`git-annex` and `hledger ` still failed with:
> can't load framework: Cocoa (not found)
Because they are use wrong ghc version: `git-annex` build dependency still require `ghc@8.6` and `hledger` use stack with `lts-16.25` snapshot which ghc version is 8.8.4

**Comment by carlocab** [comment]
Good catch. I should've checked that. What is the correct `resolver` to use for `hledger` so that it uses ghc 8.10.3?

**Comment by fishtreesugar** [comment]
> Good catch. I should've checked that. What is the correct `resolver` to use for `hledger` so that it uses ghc 8.10.3?

Stack doesn't support ghc 8.10.3, currently commercialhaskell/stack#5463.

**Comment by carlocab** [comment]
That's annoying. I suppose it doesn't help to let `stack` just vendor its own `ghc` for the build? I suspect that that runs into similar Big Sur incompatibility issues. Not to mention that Homebrew `stack` is outdated.

**Comment by fishtreesugar** [comment]
> I suppose it doesn't help to let stack just vendor its own ghc for the build?

Yes, what we can do is waiting for a new stackage snapshot with ghc 8.10.3 support :(

**Comment by carlocab** [comment]
How difficult would it be to switch `hledger` to a vanilla `cabal v2-install`?

Tagging @simonmichael, who might have ideas on how to get `hledger` to build with ghc 8.10.3.

**Comment by simonmichael** [comment]
@carlcab thanks for working on this. I can switch hledger back to cabal but I would prefer not to; I switched to stack to fix [CI failures with cabal](https://github.com/Homebrew/homebrew-core/commit/2b682e161038bf4eba9bdcf6b1c2b97b6cd57c71). 

Once ghc-8.10.3 is available in homebrew, I can make the hledger formula use it, without waiting for a new stackage snapshot. But is there a chicken and egg problem here ? ghc can't be updated unless hledger builds, and it's not easy to temporarily disable the hledger formula ? I'll go ahead make this update so that possibly both can be merged at the same time.

**Comment by carlocab** [comment]
Yes, please open a PR to fix `hledger` for ghc 8.10.3. That will make it easy for me to add your commit fixing `hledger` to this one.

**Comment by simonmichael** [comment]
44c7fdd5 pushed, it might work when combined with this PR.

**Comment by fishtreesugar** [comment]
#66599 failed with:
> No compiler found, expected minor version match with ghc-8.8.4 (x86_64) (based on resolver setting in /private/tmp/hledger-20201223-28512-1j3xtet/stack.yaml).
To install the correct GHC into /private/tmp/hledger-20201223-28512-1j3xtet/hledger-1.20/.brew_home/.stack/programs/x86_64-osx/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.

As I explained [above](#issuecomment-749963309), stack's compiler version is restricted by the resolver/stackage snapshot whatever uses stack installed compiler or system compiler.

**Comment by carlocab** [comment]
Yep, didn't work:
```
==> stack install --system-ghc --no-install-ghc --local-bin-path=/usr/local/Cellar/hledger/1.20/bin
No compiler found, expected minor version match with ghc-8.8.4 (x86_64) (based on resolver setting in /private/tmp/hledger-20201224-83889-1p2xo2j/stack.yaml).
To install the correct GHC into /private/tmp/hledger-20201224-83889-1p2xo2j/hledger-1.20/.brew_home/.stack/programs/x86_64-osx/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```
@simonmichael

**Comment by simonmichael** [comment]
@carlocab 6a961f4 might work better (insists on system GHC harder). If not, I'll switch to cabal temporarily.

**Comment by simonmichael** [comment]
Or even better: 08d32551.

**Comment by fishtreesugar** [comment]
`--skip-ghc-check` is great 👍🏻

**Comment by simonmichael** [comment]
@fishtreesugar lots of options! To be clear I don't think all that stuff I added is necessary, I'm just being paranoid to maximise chance of success.

**Comment by simonmichael** [comment]
@carlocab please try 5d7c609418, which uses the old cabal build method.

**Comment by carlocab** [comment]
The old cabal build method has been disabled, so you can no longer use it, unfortunately.

**Comment by simonmichael** [comment]
Oh dear. Meaning, I should use cabal v2-install like in git-annex.rb ? I assumed brew's cabal-install (3.2) is new enough so that "install" is equivalent to "v2-install", but perhaps there's more to it and testing would take a while.  I'll pursue this when I can. Is hledger is the only blocker here ? If there's a way to disable it temporarily without actually removing hledger.rb, I'd be fine with that.

**Comment by carlocab** [comment]
>I should use cabal v2-install like in git-annex.rb

Yes.

>there's more to it

There is, but not much more. The issue is that the old `hledger` formula used a special method called `install_cabal_package`, which no longer exists. You may wish to look at `agda` to see how I tried to get around it. (I may have done it wrong, tbh; I don't really know how to use `cabal`. However, it works.)

**Comment by carlocab** [comment]
Ok, dropped `hledger` from this PR.

With any luck, the only CI error from the next run should be just `hledger` on Big Sur (and possibly a whole lot of failures on the ARM runner if that's active now).

If this is the case then I intend to merge this PR, since `hledger` doesn't have and Big Sur bottles anyway. https://github.com/Homebrew/homebrew-core/issues/65000

**Comment by fxcoudert** [comment]
Sorry, I've killed CI because we couldn't have used to bottles on Big Sur anyway, due to https://github.com/Homebrew/homebrew-core/issues/67713

You'll need to rebase on top of master and push to start it again

**Comment by carlocab** [comment]
Yes, I was expecting that. I actually wanted to ping you here to check, but I figured you were busy fighting fires elsewhere and it could wait. Rebasing against master.

**Comment by fxcoudert** [comment]
> I figured you were busy fighting fires elsewhere

The kids, mostly 😸

**Comment by carlocab** [comment]
@fishtreesugar looks like `haskell-stack` now supports ghc 8.10.3: https://github.com/commercialhaskell/stackage-content/commit/812b7e6b0019438deee55d852baab22f1fccd4eb

**Comment by fishtreesugar** [comment]
@carlocab Still not show on https://www.stackage.org

**Comment by carlocab** [comment]
That's annoying. I wonder if this setting help: https://docs.haskellstack.org/en/stable/yaml_configuration/#allow-newer

**Comment by fishtreesugar** [comment]
If it failed at compiler version checking, try below config may help.
```yaml
system-ghc: true
resolver: nightly-2020-12-14
compiler: ghc-8.10.3
compiler-check: newer-minor
```

**Comment by simonmichael** [comment]
Right, there isn't a new stackage snapshot tested with GHC 8.10.3 yet, but stack now has the ability to build with GHC 8.10.3 at least. Let's see if efb0f42 at #66599 succeeds.

**Pull request closed without merging**
