### PR TITLE
libvmaf 3.0.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>- Removal of deprecated API `compute_vmaf()`, header file `compute_vmaf.h`.
- First release to include `vmaf_cuda_*` APIs, header file `vmaf_cuda.h`.
- Speedups and bug fixes.</pre>
</details>

### CODE REVIEW

**Comment by bevanjkay** [comment]
`ffmeg@4 build failure`

```
clang: warning: argument unused during compilation: '-L/opt/homebrew/Cellar/libvmaf/3.0.0/lib' [-Wunused-command-line-argument]
/private/tmp/ffconf.zAECDQkx/test.c:3:47: error: use of undeclared identifier 'compute_vmaf'
long check_compute_vmaf(void) { return (long) compute_vmaf; }
                                              ^
1 error generated.
ERROR: libvmaf >= 1.5.2 not found using pkg-config
```

The `compute_vmaf` API was deprecated in `libvmaf 3.0.0`

**Comment by SMillerDev** [comment]
Let's drop libvmaf from `ffmpeg@4` if we can, since there are multiple newer versions for people to use.

**Comment by bevanjkay** [comment]
If there's a fix upstream we can re-enable for `ffmpeg@4`, but that was my next thought to keep things moving.

**Comment by SMillerDev** [comment]
All problems seem to be known issues, I think we're ready to go.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
