### PR TITLE
cartridge-cli 2.7.1

### PR DESCRIPTION
**Pull request by dokshina**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]
Thanks, @dokshina.

**Comment by carlocab** [comment]
Quick question: where do we use the Git checkout here? Would the install work if we used a tarball instead?

**Comment by dokshina** [comment]
Git checkout is used to compute current version (tag and commit) that is shown by `version` command. 
Version [is passed](https://github.com/tarantool/cartridge-cli/blob/master/magefile.go#L70) via ldflags.
In fact, we can support passing it to `mage build` directly.

**Comment by bayandin** [comment]
`gopsutil` has been updated (in https://github.com/tarantool/cartridge-cli/pull/506), let's have another go on Apple Silicon

**Review by bayandin — APPROVED** [review]

**Comment by bayandin** [comment]
Thanks @dokshina!

**Comment by carlocab** [comment]
@dokshina it might be nice (it's faster, etc) if this could use the tarball instead, but not if that requires manual updating of a commit hash.

**Pull request closed without merging**
