### PR TITLE
purescript 0.13.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
cabal package install issue.
```
10:45:58 
10:45:58 dist/dist-sandbox-cb300401/build/Language/PureScript/CST/Parser.hs:1179:53: error:
10:45:58     Wildcard ‘_’ not allowed
10:45:58       in the definition of data constructor ‘HappyWrap187’
10:45:58      |
10:45:58 1179 | newtype HappyWrap187 = HappyWrap187 ([(SourceToken, _)])
10:45:58      |                                                     ^
10:45:58 cabal: Leaving directory '.'
10:45:58 cabal: Error: some packages failed to install:
10:45:58 purescript-0.13.0-91BbjW6Uwd8DlIR2FB4vOO failed during the building phase. The
10:45:58 exception was:
10:45:58 ExitFailure 1
10:45:58 
10:45:58 
10:45:58 ==> Formula
10:45:58 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/purescript.rb
```

**Comment by chenrui333** [comment]
Refresh the PR to use haskell-stack 2.1.1

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/41367

**Comment by chenrui333** [comment]
Now it does use stack 2.1.1, 

```
20:40:51 [ 29 of 162] Compiling Language.PureScript.CST.Parser ( dist/dist-sandbox-9b08a292/build/Language/PureScript/CST/Parser.hs, dist/dist-sandbox-9b08a292/build/Language/PureScript/CST/Parser.o )
20:40:51 
20:40:51 dist/dist-sandbox-9b08a292/build/Language/PureScript/CST/Parser.hs:60:64: error:
20:40:51     Not in scope: type variable ‘a’
20:40:51    |
20:40:51 60 | newtype HappyWrap27 = HappyWrap27 (QualifiedName (N.ProperName a))

...

20:40:51 [ 29 of 162] Compiling Language.PureScript.CST.Parser ( dist/dist-sandbox-9b08a292/build/Language/PureScript/CST/Parser.hs, dist/dist-sandbox-9b08a292/build/Language/PureScript/CST/Parser.o )
20:40:51 
20:40:51 dist/dist-sandbox-9b08a292/build/Language/PureScript/CST/Parser.hs:60:64: error:
20:40:51     Not in scope: type variable ‘a’
20:40:51    |
20:40:51 60 | newtype HappyWrap27 = HappyWrap27 (QualifiedName (N.ProperName a))
20:40:51    |                                                                ^
20:40:51 
```

**Comment by EricFromCanada** [comment]
For v0.13.5, setting `depends_on "ghc@8.6" => :build` fixes `rejecting: base-4.13.0.0/installed-4.1... (conflict: purescript => base>=4.11 && <4.13)`, but later fails with `cabal: The program 'happy' version ==1.19.9 is required but the version found at /private/tmp/purescript-20191128-7272-i95pem/purescript-0.13.5/.cabal-sandbox/bin/happy is version 1.19.12`.

**Comment by Bo98** [comment]
@EricFromCanada Likely the `install_cabal_package :using => ["alex", "happy"]` installing the latest version of Happy. It needs to be 1.19.9 for now - maybe try change `"happy"` to `"happy-1.19.9"` or whatever the Cabal syntax is for version pinning.

**Pull request closed without merging**
