### PR TITLE
chakra: fix build with modern compilers

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

\+ try fix Linux

### CODE REVIEW

**Comment by SMillerDev** [comment]
I think this needs a revision bump

**Review by iMichka — CHANGES_REQUESTED** [review]
Yes, a revision bump would be nice, as there are quite a bunch of changes here.

**Comment by Bo98** [comment]
I tried to make sure to limit the changes to only affect the build rather than anything at runtime. But I plan to revision bump this in the icu4c PR anyway so I'll probably just fold the changes here into that PR instead of double revision bumping.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
A rev bump requires publishing bottles, which I think we can avoid completely here.

**Review by iMichka — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
