### PR TITLE
workflows: set `HOMEBREW_GIT_PATH`

### PR DESCRIPTION
**Pull request by carlocab**
Fixes failures in #84822.

### CODE REVIEW

**Comment by Bo98** [comment]
I was thinking homebrew-test-bot.

**Comment by carlocab** [comment]
Ok, sure. That makes more sense.

**Review by MikeMcQuaid — APPROVED** [review]
Fine with me but also agree I'd probably set in `test-bot`

**Comment by dawidd6** [comment]
Yes. Do it in test-bot please. Maybe even do the same for curl too while we are here.

**Comment by carlocab** [comment]
Homebrew/homebrew-test-bot#660

**Pull request closed without merging**
