### PR TITLE
angular-cli 11.2.0

### PR DESCRIPTION
**Pull request by crunchtime-ali**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by crunchtime-ali** [comment]
> Please install a compatible version to proceed (`npm install --global npm@6`).

Shall I just do that?

**Comment by chenrui333** [comment]
> > Please install a compatible version to proceed (`npm install --global npm@6`).
> 
> Shall I just do that?

yes

**Comment by chenrui333** [comment]
`npm install` fails with NPM 7
https://github.com/angular/angular-cli/issues/19957

**Comment by crunchtime-ali** [comment]
@chenrui333 I tried a few solutions without success:

**1. Use the `--legacy-peer-deps` as described in angular/angular-cli#19957**

The installation works with this, but the tests fail due to angular-cli complaining that it requires NPM 6.

> brew test angular-cli
> ==> Testing angular-cli
> ==> /usr/local/Cellar/angular-cli/11.1.4/bin/ng new angular-homebrew-test --skip-install
> Last 15 lines from /Users/azigelsk/Library/Logs/Homebrew/angular-cli/test.01.ng:
> 2021-02-09 13:44:10 +0100

> /usr/local/Cellar/angular-cli/11.1.4/bin/ng
> new
> angular-homebrew-test
> --skip-install

> npm version 7.5.0 detected.
> The Angular CLI currently requires npm version 6.

> Please install a compatible version to proceed (`npm install --global npm@6`).

> Error: angular-cli: failed

**2. Install npm@6**

`system "npm", "install", "--global", *Language::Node.std_npm_install_args(libexec), "npm@6"`

This leads to `angular-cli` not being able to be linked:

> Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/npm
Target /usr/local/bin/npm
already exists. You may want to remove it:
  rm '/usr/local/bin/npm'

> To force the link and overwrite all conflicting files:
  brew link --overwrite angular-cli

> To list all files that would be deleted:
  brew link --overwrite --dry-run angular-cli

> Possible conflicting files are:
> /usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
> /usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
