### PR TITLE
spades 3.13.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
The Mojave CI issue is due to GCC needing a rebottle on Mojave with the latest Xcode. Doing this is https://github.com/Homebrew/homebrew-core/pull/45585

**Comment by Bo98** [comment]
> ```ruby
> fails_with :clang # no OpenMP support
> ```

Is this still true? I managed to use OpenMP no problem a couple weeks ago after a `brew install libomp`.

**Comment by fxcoudert** [comment]
OpenMP support through `libomp` by adding custom `clang` flags (that Apple's clang officially does not support) is a hack that we reserve to select few formulas, where we think it's beneficial yet don't want the weight of a full GCC install. In other cases, let's use GCC.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
>  custom clang flags (that Apple's clang officially does not support) is a hack that we reserve to select few formulas

Fair enough.

In this case, CMake is used and CMake supports doing that for you so may well work out of the box, so I just wanted to ask the question.

**Comment by fxcoudert** [comment]
@Bo98 one of the factors in making such decision is that we want to avoid absolutely the case where we would have mixed dependencies in any formula, with some things liked to `libomp` and some to `libgomp`.

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by fxcoudert** [comment]
On Mojave:

```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wchar.h:90,
                 from /usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/cwchar:44,
                 from /usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/bits/postypes.h:40,
                 from /usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/bits/char_traits.h:40,
                 from /usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/string:40,
                 from /tmp/spades-20191226-51467-fkrr13/SPAdes-3.13.1/src/../ext/include/getopt_pp/getopt_pp.h:24,
                 from /tmp/spades-20191226-51467-fkrr13/SPAdes-3.13.1/ext/src/getopt_pp/getopt_pp.cpp:22:
/usr/local/Cellar/gcc/9.2.0_2/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include-fixed/stdio.h:222:7: error: conflicting declaration of 'char* ctermid(char*)' with 'C' linkage
  222 | char *ctermid(char *);
      |       ^~~~~~~
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:525,
                 from /tmp/spades-20191226-51467-fkrr13/SPAdes-3.13.1/ext/src/getopt_pp/getopt_pp.cpp:21:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_ctermid.h:26:10: note: previous declaration with 'C++' linkage
   26 | char    *ctermid(char *);
      |          ^~~~~~~
```

Will merge without the Mojave bottle to avoid this issue (and will rebuild GCC with latest headers).

**Pull request closed without merging**
