### PR TITLE
Node 8.2.0 (and npm 5.3)

### PR DESCRIPTION
**Pull request by chrmoritz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR updates Node to v8.2.0: https://nodejs.org/en/blog/release/v8.2.0/
and all active node formulae to npm@5.3.0: https://github.com/npm/npm/releases

### CODE REVIEW

**Comment by chrmoritz** [comment]
```
FetchError: request to https://registry.npmjs.org/har-schema/-/har-schema-1.0.5.tgz failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
```
Looks like some connectivity issue on the sierra bot unreleated to this PR.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by chrmoritz** [comment]
The exact same network error happend again, but again only on the sierra bot (it passes locally for me on sierra).

**Comment by ilovezfs** [comment]
Going to take `sierra_stadium_2` offline.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @chrmoritz!

**Pull request closed without merging**
