### PR TITLE
trunk-ng 0.17.10 (new formula)

### PR DESCRIPTION
**Pull request by ctron**
This adds a new formula for trunk-ng, a fork of trunk.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ctron** [comment]
I am stuck with this and need some help. According to the docs, I ran the audit command, and it returned nothing:

```
➜  t git:(add-trunk-ng) brew audit trunk-ng --online --new-formula
➜  t git:(add-trunk-ng) 
```

Now it looks that the result in the CI is different:

```
Full audit trunk-ng --online --new-formula output
  trunk-ng
    * GitHub fork (not canonical repository)
  Error: 1 problem in 1 formula detected.
```

However, this also is correct. This is a fork or the original project. However, that's just what it is.

**Comment by chenrui333** [comment]
can you show the `brew config`?

**Comment by chenrui333** [comment]
> This adds a new formula for trunk-ng, a fork of trunk.

also did you get endorsement from the original fork (that one seems still in active dev)? and in terms of the github stats, it is also low as well.

**Comment by ctron** [comment]
> > This adds a new formula for trunk-ng, a fork of trunk.
> 
> also did you get endorsement from the original fork (that one seems still in active dev)? and in terms of the github stats, it is also low as well.

The problem with the original project is, that none of the contributors is responsive anymore. Still, the original author stated that he's ok with that (https://github.com/thedodd/trunk/issues/588#issuecomment-1677972227):

> @ctron I can appreciate where you are coming from. Folks often times have a great deal of urgency when it comes to fixes that they need for their projects and such. YOU SHOULD do whatever it is that you need to do in order to get to a stable point. Host a build yourself. Whatever. Its fine. This is open source.


> can you show the `brew config`?

As I am currently at a conference, I can't provide this before Thursday.

**Comment by SMillerDev** [comment]
> The problem with the original project is, that none of the contributors is responsive anymore. Still, the original author stated that he's ok with that (https://github.com/thedodd/trunk/issues/588#issuecomment-1677972227):

That reads as a "sure you can fork, I don't care" rather than a "yes, you are the new upstream now I am giving up". So that would leave us with the exact situation the audit is meant to catch: "who is the real developer".

If you are never going to upstream changes anymore, you can unfork your repo. If you are, it shouldn't be in Homebrew/core.

**Comment by ctron** [comment]
> If you are never going to upstream changes anymore, you can unfork your repo. If you are, it shouldn't be in Homebrew/core.

I believe that "unforking" the repository is just wrong. It is a fork of that original project and keeping that information is kind of an attribution to the original author.

I don't plan to bring changes to the original project at this point, just because I can't. On the other side, I am not sure what the future will bring. So I wouldn't rule that out either.

**Comment by ctron** [comment]
Activity

**Comment by fxcoudert** [comment]
I agree with @SMillerDev here, and this is a fork with not enough notable activity, and not the “current upstream”, so not really suitable for homebrew-core. Thank you for your pull request, we are going to decline at this point. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Pull request closed without merging**
