### PR TITLE
bullet 2.89

### PR DESCRIPTION
**Pull request by sayomaki**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Bump version to `2.89`, removed patch due to build failure with patch.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`efl` has had trouble building for a long time:

```
lib/ecore_cocoa/ecore_cocoa_app.m:48:5: error: use of undeclared identifier '_mainMenu'
   [_mainMenu update];
    ^
lib/ecore_cocoa/ecore_cocoa_app.m:79:4: error: use of undeclared identifier '_running'
   _running = 1;
   ^
```

**Comment by willi123yao** [comment]
Ok, the build succeeds on high sierra but fails on both mojave and catalina. Would try updating `efl` to the latest version (`1.23.3`) and see if that builds locally.

**Comment by willi123yao** [comment]
Alright, build failed for efl on local and I am unable to test the package for linking. Time to wait for an upstream fix to solve this issue before we can link successfully to update this formula.

**Comment by chenrui333** [comment]
@willi123yao is there any upstream issue that you can link to this PR?

**Comment by scpeters** [comment]
can you rebase and bump dartsim revision to 4?

**Comment by iMichka** [comment]
Ping @willi123yao

**Comment by willi123yao** [comment]
> can you rebase and bump dartsim revision to 4?

It is already at revision 4 after I did a rebase, do I still need to bump the revision?

**Comment by iMichka** [comment]
You need to remove the revision, as you are bumping the version here. This means revision == 0, which means no revision at all.

**Comment by willi123yao** [comment]
Correct me if I am wrong, but I believe there isn't an update for `dartsim` formula yet?
The latest version is still `v6.9.2` as of right now.

**Comment by iMichka** [comment]
Ok, got it. The dartsim revision is 4 now. In this case set it as 5.

**Pull request closed without merging**
