### PR TITLE
mmctl 6.0.0

### PR DESCRIPTION
**Pull request by dawidd6**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — APPROVED** [review]

**Comment by elyscape** [comment]
@dawidd6 This version of mmctl is still in prerelease status. The current stable version is 5.36.0.

**Comment by nandahkrishna** [comment]
Thanks for letting me know. I remember checking the repository before approving this PR and it was marked as the latest version, do you happen to know if it was changed to a pre-release later?

Dawid's action uses `livecheck` to determine the latest version (see https://github.com/dawidd6/ba-bump), and this formula uses the `GithubLatest` strategy, meaning this PR would not have been created unless `6.0.0` was marked as "latest" on GitHub.

That said, I'll try to create a PR soon to revert this, since it's now marked as a pre-release.

**Comment by elyscape** [comment]
> I remember checking the repository before approving this PR and it was marked as the latest version, do you happen to know if it was changed to a pre-release later?

I guess it must have.

**Comment by nandahkrishna** [comment]
Thanks, we've downgraded `mmctl` to the stable version. You'll have to uninstall it, ensure your `homebrew/core` is up-to-date with `brew update` and then install it again. Thanks for the report.

**Pull request closed without merging**
