### PR TITLE
libvpx 1.14.1

### PR DESCRIPTION
**Pull request by ik11235**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ik11235** [comment]
The build is failing in CI and I can't figure out why.
Can someone please help me?

I run brew install locally and get the same result.

```bash
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source libvpx

[omitted in the middle]

==> make install
Last 15 lines from /Users/yuichi/Library/Logs/Homebrew/libvpx/02.make:
../vpx_dsp/arm/vpx_convolve8_neon_i8mm.c:136:10: error: assigning to 'uint8x8_t' (vector of 8 'uint8_t' values) from incompatible type 'int'
      d1 = convolve8_8_usdot(s1, filters, perm_tbl);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vpx_dsp/arm/vpx_convolve8_neon_i8mm.c:137:10: error: assigning to 'uint8x8_t' (vector of 8 'uint8_t' values) from incompatible type 'int'
      d2 = convolve8_8_usdot(s2, filters, perm_tbl);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vpx_dsp/arm/vpx_convolve8_neon_i8mm.c:174:12: error: call to undeclared function 'convolve8_4_usdot'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      t0 = convolve8_4_usdot(s0, filters, perm_tbl);
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
make[1]: *** [vpx_dsp/arm/vpx_convolve_neon_i8mm.c.o] Error 1
make[1]: *** Waiting for unfinished jobs....
20 errors generated.
make[1]: *** [vpx_dsp/arm/vpx_convolve8_neon_i8mm.c.o] Error 1
make: *** [.DEFAULT] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```

But if I build and install from source, it succeeds without error.

```bash
cd /tmp
git clone https://github.com/webmproject/libvpx
git checkout v1.14.1
cd ..
mkdir build
cd build/
../libvpx/configure
make
make install
```
=> Successfully installed without error.

**Comment by carlocab** [comment]
> But if I build and install from source, it succeeds without error.

What's the output of your `brew config`?

**Comment by ik11235** [comment]
> What's the output of your brew config? Which compiler did you use when installing from source outside of brew?

The output of config looks like this.
```
HOMEBREW_VERSION: 4.3.2-60-gc6368be
ORIGIN: https://github.com/Homebrew/brew
HEAD: c6368bea8a1e038e77d49ed13bba33c5bc2f8ce6
Last commit: 30 hours ago
Core tap HEAD: c5a891742a6a813e91c636ce2b6f0913ede51150
Core tap last commit: 2 hours ago
Core tap branch: bump-libvpx-1.14.1
Core tap JSON: 02 Jun 05:23 UTC
Core cask tap HEAD: b9e8f78351f2da3c2cdaae578bcd9b9244246ab5
Core cask tap last commit: 3 hours ago
Core cask tap JSON: 02 Jun 05:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

> Which compiler did you use when installing from source outside of brew?

I just ran Make, so I did not specify any special compiler. However my guess is that gcc is probably used by default.

The gcc in my environment is as follows
```
$ gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 /```

**Comment by carlocab** [comment]
Can you dump the output of `configure` into a text file and upload it here?

**Comment by ik11235** [comment]
The results of running `configure` using the [aforementioned Process](https://github.com/Homebrew/homebrew-core/pull/173470#issuecomment-2143715162) are as follows.
```bash
$ ../libvpx/configure
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'arm64-darwin23-gcc'
  enabling arm64
  enabling pic
  enabling runtime_cpu_detect
  enabling neon
  enabling neon_dotprod
  enabling neon_i8mm
  enabling sve
  disabling sve: arm_neon_sve_bridge.h not supported by compiler
  enabling unit_tests
  enabling webm_io
  enabling libyuv
Creating makefiles for arm64-darwin23-gcc libs
Creating makefiles for arm64-darwin23-gcc examples
Creating makefiles for arm64-darwin23-gcc tools
Creating makefiles for arm64-darwin23-gcc docs
```

**Comment by carlocab** [comment]
Does it still work if you pass
```
--enable-shared
--enable-vp9-highbitdepth
```
to `configure`?

**Comment by ik11235** [comment]
>Does it still work if you pass
>
>to configure?

In my environment, make succeeded even with that option.

```bash
 ../libvpx/configure --enable-shared --enable-vp9-highbitdepth
  enabling shared
  enabling vp9_highbitdepth
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'arm64-darwin23-gcc'
  enabling arm64
  enabling pic
  enabling runtime_cpu_detect
  enabling neon
  enabling neon_dotprod
  enabling neon_i8mm
  enabling sve
  disabling sve: arm_neon_sve_bridge.h not supported by compiler
  enabling unit_tests
  enabling webm_io
  enabling libyuv
Creating makefiles for arm64-darwin23-gcc libs
Creating makefiles for arm64-darwin23-gcc examples
Creating makefiles for arm64-darwin23-gcc tools
Creating makefiles for arm64-darwin23-gcc docs
```

```bash
$ make
```

-> [make.log](https://github.com/user-attachments/files/15551642/make.log)

**Pull request closed without merging**
