### PR TITLE
libpng 1.6.30

### PR DESCRIPTION
**Pull request by zmwangx**
Switching to URLs currently listed on the home page
<https://web.archive.org/web/20170707222014/http://www.libpng.org/pub/png/libpng.html>.

### CODE REVIEW

**Comment by zmwangx** [comment]
`png2ico` bottles somehow 404. Need to be re-bottled.

**Comment by ilovezfs** [comment]
@zmwangx it was caused by https://github.com/Homebrew/brew/commit/1e1ae204c2fa01a913af0b2feb09b53232e310a7. The version went from being `2002-12` (which probably should have been overridden as `version "2002-12-08"` but no one noticed)  to being `2002-12-08`. The bottles still exist under the old version number.

>Need to be re-bottled.

Indeed.

**Comment by ilovezfs** [comment]
:paintbrush:

**Comment by ilovezfs** [comment]
I ran `brew info` on everything before and after that change and turned up that `myman` has the same issue.

**Comment by ilovezfs** [comment]
Fixed in
https://github.com/Homebrew/homebrew-core/commit/393e45c919c72ebe835f98eb07967e94107dfcbd
and
https://github.com/Homebrew/homebrew-core/commit/5bbb433069ac28342fd356adc87fc400eeee113a

**Comment by zmwangx** [comment]
My man!

**Comment by ilovezfs** [comment]
:myanmar: ?

**Pull request closed without merging**
