### PR TITLE
libmarisa: migrate to boneyard

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Similarly: if it's not causing us problems is it worth boneyarding?

**Comment by MikeMcQuaid** [comment]
I'm also coming around to @chdiza's point about maybe having `brew boneyard-formula-pr` taking a mandatory "reason" argument that's inserted into the various commit messages. Thoughts?

**Comment by ilovezfs** [comment]
No I don't think that's necessary.

**Comment by ilovezfs** [comment]
>Similarly: if it's not causing us problems is it worth boneyarding?

jumping jacks rule again.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Would you actively object to it? Seems preferably to have this conversation every time (sometimes in hindsight). 

> jumping jacks rule again.

It's got no installs since records began so 👍 to boneyard this one.

**Comment by ilovezfs** [comment]
>Would you actively object to it? Seems preferably to have this conversation every time (sometimes in hindsight). 

Yes.

**Comment by MikeMcQuaid** [comment]
> Yes.

Can you elaborate a bit on that?

**Comment by ilovezfs** [comment]
>Can you elaborate a bit on that? 

Most of the time the reason is self-evident if you look at the PR on GitHub not email due to cross links between issues and PRs. Mandating that information be duplicated when it's already there is just wasting time.

**Comment by ilovezfs** [comment]
>a mandatory "reason" argument that's inserted into the various commit messages

@MikeMcQuaid I think it would be fine as long as it's not mandatory (i.e., has an opt-in or opt-out).

**Comment by MikeMcQuaid** [comment]
@ilovezfs 🆒

**Pull request merged**
