### PR TITLE
ninja 1.11.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on 11 and linux

**Comment by alebcay** [comment]
**Failures on Linux**
- Test failure for `gst-libav`:
  ```
  (gst-plugin-scanner:184993): GStreamer-WARNING **: 19:30:02.104: Failed to load plugin '/home/linuxbrew/.linuxbrew/lib/gstreamer-1.0/libgstlibav.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/lib/librubberband.so.2)
    No such element or plugin 'libav'
  ```
- Test failure for `root`:
  ```
  /home/linuxbrew/.linuxbrew/Cellar/root/6.26.02_1/etc/root/cling/std.modulemap:314:20: error: header 'string_view' not found
      textual header "string_view"
                     ^
  input_line_1:1:10: note: submodule of top-level module 'std' implicitly imported here
  #include <new>
           ^
  Warning in cling::IncrementalParser::CheckABICompatibility():
    Failed to extract C++ standard library version.
  Replaced symbol atexit cannot be found in JIT!
  Replaced symbol at_quick_exit cannot be found in JIT!
  
  IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
  You are probably missing the definition of cling::runtime::gCling
  Maybe you need to load the corresponding shared library?
  ```
- Linkage audit failure for `root` (linkage to old `libcrypt`)
- Linkage audit failure for `systemd` (linkage to old `libcrypt`)

**Review by carlocab — APPROVED** [review]

**Comment by cho-m** [comment]
`gst-libav` has been hitting issues for a while during dependent testing, but not sure exact reason.

`root` may have been broken when rev-bumping `gcc` (maybe #101834) as there appears to be a `gcc` Cellar path embedded somewhere based on #99773. Can rev-bump `root` outside this PR along with a migration to `xlibcrypt`.

**Comment by chenrui333** [comment]
As the formulae test failures pre-exist (`gst-libav` failure is also in python@3.9 PR as well), merging the PR now.

**Pull request closed without merging**
