### PR TITLE
link-grammar 5.3.13

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
Urgh:
```
link-grammar:
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/Cellar/link-grammar/5.3.13/lib/python2.7/site-packages/linkgrammar/_clinkgrammar.5.so
      /usr/local/Cellar/link-grammar/5.3.13/lib/python2.7/site-packages/linkgrammar/_clinkgrammar.so

**Comment by nijikon** [comment]
What we can do here? /cc @tdsmith

**Comment by tdsmith** [comment]
Fix the makefile!

Possible we could handle these problems automatically by stripping the linkages using an approach like https://github.com/alexzielenski/optool; maybe you could convince @woodruffw to implement it ;)

**Comment by woodruffw** [comment]
Ruby-macho can do this!

The current check is just this (in `check_python_framework_links`):

```ruby
python_modules = Pathname.glob lib/"python*/site-packages/**/*.so"
framework_links = python_modules.select do |obj|
  dlls = obj.dynamically_linked_libraries
  dlls.any? { |dll| /Python\.framework/.match dll }
end
```

Replacing it with this should work:

```ruby
python_modules = Pathname.glob lib/"python*/site-packages/**/*.so"
python_modules.each do |obj|
  macho = MachO::MachOFile.new(obj.to_s)
  macho.dylib_load_commands.each do |dylib|
    if  /Python\.framework/.match dylib.name.to_s 
      macho.delete_command(dylib)
    end
  end
end
```

(Not sure if that should remain in checks, since it modifies the binary.)

That's a bit longer than it needs to be, I can add abstract all that away in a `MachO::Tools` method if preferred.

**Comment by tdsmith** [comment]
Hey, neat! This could save a lot of trouble if it works (at the cost of letting upstreams get away with bad habits...).

Agree this wouldn't be a check; the cleaner should do if we want it to happen magically. (Implementation note: we should only do this to things with realpaths in site-packages. Some packages like lldb build a single all-singing, all-dancing dylib that is both an importable Python module and, separately, a library that includes functionality that embeds a Python interpreter; the latter functionality will break without this linkage. If a dylib in lib/ is just symlinked into site-packages, we should probably assume something like that is going on.)

**Comment by woodruffw** [comment]
> at the cost of letting upstreams get away with bad habits...

Yeah, this is the dilemma. Perhaps we should perform the linkage removals *and* spit out a warning that we had to?

> If a dylib in lib/ is just symlinked into site-packages, we should probably assume something like that is going on.)

So something like `next if File.symlink?(obj)`? Just want to make sure I'm understanding correctly :smile:

**Comment by tdsmith** [comment]
I think so and yes!

**Comment by woodruffw** [comment]
Got it, I'll open a brew PR in a bit!

**Comment by woodruffw** [comment]
Opened Homebrew/brew#1769 for this.

**Comment by tdsmith** [comment]
@woodruffw and I looked further and it's not that easy; we'd have to do additional rewriting of the bundles to indicate that the symbols should be found at runtime instead of from a linked library.

So we're back to "fix the makefile!"

**Comment by nijikon** [comment]
@tdsmith is it really so crucial to check this linking? What consequences does it bring if we ship it like this?

**Comment by ilovezfs** [comment]
```
    ENV["PYTHON_LIBS"] = "-undefined dynamic_lookup"
    inreplace "bindings/python/Makefile.am",
      "$(PYTHON2_LDFLAGS) -module -no-undefined",
      "$(PYTHON2_LDFLAGS) -module"
```

**Pull request closed without merging**
