### PR TITLE
pgroonga 2.2.1

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
`pgroonga` test failed with:
```
running bootstrap script ... 2019-07-26 03:50:30.705 BST [97995] FATAL:  could not create shared memory segment: No space left on device
```

I cannot replicate this on my local machine, and given the nature of the failure, I think it's an issue with the CI environment itself.

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by alebcay** [comment]
CI tests passing now.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
