### PR TITLE
geoipupdate 4.0.5

### PR DESCRIPTION
**Pull request by oschwald**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
you might need to create a PR for 4.0.6

**Comment by oschwald** [comment]
There are no code changes in 4.0.6 so I am not sure if it is worthwhile. It was a re-release to fix an Ubuntu PPA packaging issue.

**Comment by chenrui333** [comment]
ok, that sounds good then.

**Comment by fxcoudert** [comment]
Thank you @oschwald

**Pull request closed without merging**
