### PR TITLE
pandoc 2.12

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by storopoli** [comment]
Does this cover ARM? because we have a pandoc binary for ARM 🎉 !! See jgm/pandoc#6960

**Comment by storopoli** [comment]
@carlocab I am not suggesting a build from source. They released a **binary** for ARM, can we include it in the formula so that the user using M1 could download pandoc using `brew install pandoc`?

**Comment by storopoli** [comment]
OOOOOOOO @carlocab so sorry! I made a mess here. They release a binary for 2.12 to **ARM Linux**!!

**Comment by carlocab** [comment]
Well, I would be shocked if they had built a binary for Apple Silicon, because

>pandoc does not build natively on ARM, because it needs ghc, and ghc does not work on ARM yet.

Though obviously by "ARM" I meant Apple Silicon. Even assuming they somehow had a native Apple Silicon binary that we're not able to build from source for some strange reason (presumably, whatever they did to build a binary, we could do too):

https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Pull request closed without merging**
