### PR TITLE
slimerjs: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by Amar1729**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See #75943.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
Seeing this with `diffoscope` for Mojave and Catalina:
```
Format-specific differences are supported for ZIP archives but no file-specific differences were detected; falling back to a binary diff. file(1) reports: Zip archive data, at least v1.0 to extract, compression method=store
│ │┄ Archive contents identical but files differ, possibly due to different compression levels. Falling back to binary comparison.
```

Checksums:
```
07f7049c293cc9d75b70a52b7184ff5f0a783114cd27eb1fce564abeea27005e  slimerjs--1.0.0.arm64_big_sur.bottle.tar.gz
2258065f303babc625187f31afedfcb3f68215ab690a74b1a506bab09feb6b92  slimerjs--1.0.0.big_sur.bottle.tar.gz
48cb1a45cf9f0bdf310fe561ee9e856480abcd416ed562e347deee9dfce9a225  slimerjs--1.0.0.catalina.bottle.tar.gz
50316a653108b9b06978547677083bcbca302ee2438f1c7c719bb0eb8c390f3d  slimerjs--1.0.0.mojave.bottle.tar.gz
```

**Comment by nandahkrishna** [comment]
```
50bdd592449f2e9fe95d57bc7d09653cb3a166ab7a6beeba42883979bb8916f7  slimerjs--1.0.0.arm64_big_sur.bottle.tar.gz
6a0979652c15b31cbe855755f4f198e1e39ee441fc7f0b626c6beb5f63e1c6ca  slimerjs--1.0.0.big_sur.bottle.tar.gz
71a0f575ea2bcca856814bfd781d9de72dd78ec08a803b0ef1cc408a3b4f2979  slimerjs--1.0.0.catalina.bottle.tar.gz
327503d2e8b1424bb83cf1d00c712f238771bf130c46318e1caafcbe59b703df  slimerjs--1.0.0.mojave.bottle.tar.gz
```
There are multiple instances of this in `diffoscope slimerjs--1.0.0.arm64_big_sur.bottle.tar.gz slimerjs--1.0.0.big_sur.bottle.tar.gz`:
```diff
-  file last modified on (DOS date/time):          2018 Mar 23 01:30:16
+  file last modified on (DOS date/time):          2018 Mar 23 08:30:16
```
This is apart from other differences between binary file(s).

Still seeing this:

> Seeing this with `diffoscope` for Mojave and Catalina:
> 
> ```
> Format-specific differences are supported for ZIP archives but no file-specific differences were detected; falling back to a binary diff. file(1) reports: Zip archive data, at least v1.0 to extract, compression method=store
> │ │┄ Archive contents identical but files differ, possibly due to different compression levels. Falling back to binary comparison.
> ```

**Comment by Bo98** [comment]
The `zip` command within should be adjusted for reproducibility.

I recommend looking into some or all of these:

* `-o`/`--latest-time` flag
* Setting the `TZ` env to `UTC`
* `-X`/`--no-extra` flag

**Comment by nandahkrishna** [comment]
```
8885664d7813c68ee458bf887d4e52ccf8164a05bd89d8f2a7e82a3a5c6396b7  slimerjs--1.0.0.arm64_big_sur.bottle.tar.gz
8885664d7813c68ee458bf887d4e52ccf8164a05bd89d8f2a7e82a3a5c6396b7  slimerjs--1.0.0.big_sur.bottle.tar.gz
8885664d7813c68ee458bf887d4e52ccf8164a05bd89d8f2a7e82a3a5c6396b7  slimerjs--1.0.0.catalina.bottle.tar.gz
8885664d7813c68ee458bf887d4e52ccf8164a05bd89d8f2a7e82a3a5c6396b7  slimerjs--1.0.0.mojave.bottle.tar.gz
```
🎉

Thanks Bo! 🙇🏻‍♂️

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
