### PR TITLE
blast 2.15.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
`  Errno::ENOENT: No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/blast/2.15.0/bin/blastn`

**Comment by chenrui333** [comment]
linux build works for me

```
==> Testing blast
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/b/blast.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/g/gcc@11.rb
==> /home/linuxbrew/.linuxbrew/Cellar/blast/2.15.0/bin/update_blastdb.pl --showall
==> /home/linuxbrew/.linuxbrew/Cellar/blast/2.15.0/bin/blastn -query test.fasta -subject test.fasta
==> /home/linuxbrew/.linuxbrew/Cellar/blast/2.15.0/bin/makeblastdb -in test.fasta -out testdb -dbtype nucl
==> /home/linuxbrew/.linuxbrew/Cellar/blast/2.15.0/bin/blastdbcmd -info -db testdb

runner@fv-az1426-144:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ ls /home/linuxbrew/.linuxbrew/Cellar/blast/2.15.0/bin/blastn
/home/linuxbrew/.linuxbrew/Cellar/blast/2.15.0/bin/blastn
```

**Review by SMillerDev — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
I want to understand first why `blastn` is not build on Linux. I am waiting on the artifacts to investigate.

**Comment by chenrui333** [comment]
> I want to understand first why `blastn` is not build on Linux. I am waiting on the artifacts to investigate.

yeah, i could not reproduce it in the actual linux runner

**Comment by chenrui333** [comment]
@iMichka The test works, but just not work in linux CI, I think we can just merge it and followup on the linux CI test separately.

**Comment by chenrui333** [comment]
need a rerun for the build timeout on 13

**Comment by iMichka** [comment]
I looked at the Linux bottle; the `bin` folder is basically empty (compared to macOS or previous version 2.14)

```
➜  bin ll
total 42728
-r-xr-xr-x@ 1 michkapopoff  staff   6.1K Oct 19 19:21 cleanup-blastdb-volumes.py
-r-xr-xr-x@ 1 michkapopoff  staff   8.9M Oct 19 19:21 datatool
-r-xr-xr-x@ 1 michkapopoff  staff   4.6K Oct 19 19:21 get_species_taxids.sh
-r-xr-xr-x@ 1 michkapopoff  staff    50K Oct 19 19:21 legacy_blast.pl
-r-xr-xr-x@ 1 michkapopoff  staff   4.9M Oct 19 19:21 lmdbxx_sample
-r-xr-xr-x@ 1 michkapopoff  staff   6.5M Oct 19 19:21 project_tree_builder
-r-xr-xr-x@ 1 michkapopoff  staff    54K Oct 19 19:21 run_with_lock
-r-xr-xr-x@ 1 michkapopoff  staff   349K Oct 19 19:21 test_pcre
-r-xr-xr-x@ 1 michkapopoff  staff    36K Oct 19 19:21 update_blastdb.pl
-r-xr-xr-x@ 1 michkapopoff  staff   5.8K Oct 19 19:21 windowmasker_2.2.22_adapter.py
```

We need to understand why it's not building binaries on Linux

**Review by iMichka — APPROVED** [review]
Found the solution in the logs:

```
make[4]: *** No rule to make target '/tmp/blast-20231104-3304-1f19irr/ncbi-blast-2.15.0+-src/c++/ReleaseMT/status/SQLITE3.enabled', needed by 'requirements'.  Stop.
make[4]: Leaving directory '/tmp/blast-20231104-3304-1f19irr/ncbi-blast-2.15.0+-src/c++/ReleaseMT/build/db/sqlite'
NOTE:  skipping project "sqlitewrapp" due to unmet requirements
```

**Comment by chenrui333** [comment]
> Found the solution in the logs:
> 
> ```
> make[4]: *** No rule to make target '/tmp/blast-20231104-3304-1f19irr/ncbi-blast-2.15.0+-src/c++/ReleaseMT/status/SQLITE3.enabled', needed by 'requirements'.  Stop.
> make[4]: Leaving directory '/tmp/blast-20231104-3304-1f19irr/ncbi-blast-2.15.0+-src/c++/ReleaseMT/build/db/sqlite'
> NOTE:  skipping project "sqlitewrapp" due to unmet requirements
> ```

👍 💯

**Comment by chenrui333** [comment]
> Found the solution in the logs:
> 
> ```
> make[4]: *** No rule to make target '/tmp/blast-20231104-3304-1f19irr/ncbi-blast-2.15.0+-src/c++/ReleaseMT/status/SQLITE3.enabled', needed by 'requirements'.  Stop.
> make[4]: Leaving directory '/tmp/blast-20231104-3304-1f19irr/ncbi-blast-2.15.0+-src/c++/ReleaseMT/build/db/sqlite'
> NOTE:  skipping project "sqlitewrapp" due to unmet requirements
> ```

👍 💯

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
