### PR TITLE
mysql 8.0.11, mysql@5.7 5.7.22 (new formula)

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by cristhiank** [comment]
Looking forward to this formula to be available. Thanks! (Y)

**Comment by ilovezfs** [comment]
Shipped! 🍪

**Comment by mfraase** [comment]
MySQL 8.0.11 uses `caching_sha2_password` as the default authentication method (leave it to Oracle to do something like this in a point release, but there you have it).

So far, it breaks everything I've tried: phpMyAdmin, Nextcloud, and WordPress.

**Comment by ilovezfs** [comment]
@mfraase I'm not sure what you mean by "point release" here. This was a major version upgrade.

**Comment by mfraase** [comment]
@ilovezfs My understanding is that MySQL 8.0.x *prior* to 8.0.11 did not use `caching_sha2_password` as the default authentication method. If I'm mistaken, my apologies; if not, my comment stands.

In any case, the outcome is the same: Homebrew pushed out MySQL 8.0.11 as an upgrade yesterday. It breaks everything I've tried.

**Comment by ilovezfs** [comment]
Ah, I see. Did you figure out how to change the setting such that it works?

**Comment by mfraase** [comment]
@ilovezfs Sadly, no. I spent all day trying a variety of things and just rolled back to MySQL 5.7.22.

Disclosure: I'm a writer, editor, and UX practitioner; not a coder (nor much of a system administrator; my development/staging server is down and I could have sworn I had MySQL pinned in Homebrew, but didn't).

**Comment by cristhiank** [comment]
Hi @mfraase, you can disable the caching_sha2_password by setting the `––default-authentication-plugin= mysql_native_password` option in the my.cnf or in the startup options.

https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/

**Comment by mfraase** [comment]
Thanks @christhiank. Setting the default-authentication-plugin in my.cnf was the first thing I tried. It didn't work. I find this graf from the article you cite perplexing in the extreme:

> User accounts already created in existing instances are not altered as a part of an upgrade. So, all existing user accounts continue to use the same authentication plugin that they used in e.g. MySQL 5.7. However, if you create a new user without changing –-default-authentication-plugin explicitly, caching_sha2_password is used as authentication mechanism for such users.

So, I take it existing user accounts continue to use MySQL 5.7.x authentication; newly created user accounts default to caching_sha2_password authentication. Fine if it worked. But in my experience it doesn't (existing user accounts are apparently "upgraded" to caching_sha2_password authentication (based on error log entries).

The article cited is specific to MySQL 8.0.4, so maybe the behavior changed in 8.0.11, although I don't see any mention of it in the 8.0.11 release notes:

[https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-11.html](url)

**Comment by mfraase** [comment]
**Three step solution**:

1. Add to `[mysqld]` section of `my.cnf` file:

`default-authentication-plugin=mysql_native_password`

2. At shell prompt:

`mysql -u root -p`

`ALTER USER 'root'@'localhost'
  IDENTIFIED WITH mysql_native_password
  BY '[password]';`
  
`exit`

3. Reboot server

[Short version solution](https://www.farces.com/wrestling-with-the-mysql-8-0-11-bear/)

[Long version solution](https://www.farces.com/wikis/naked-server/mysql/)

**Comment by mfraase** [comment]
The solution provided above is partial, at best. In my experience MySQL 8.0.11 is not nearly ready for production (or even development) use.

**Pull request closed without merging**
