### PR TITLE
hugo 0.72.0 (new formula) 

### PR DESCRIPTION
**Pull request by CHOWY0152**
add hugo@0.72.0 formula

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
And the same as in https://github.com/Homebrew/homebrew-core/pull/57334, please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions)

**Comment by chow1026** [comment]
> Versioned software should build on all Homebrew’s supported versions of macOS.

I have only tested on macOS catalina. Please advise on how many version of macOS this should be tested on, and how I could test install on other versions of macOS.

> Versioned formulae should differ in major/minor (not patch) versions from the current stable release. This is because patch versions indicate bug or security updates and we want to ensure you apply security updates.

Yes, this is fulfilled.

> Unstable versions (alpha, beta, development versions) are not acceptable for versioned (or unversioned) formulae.

Yes, this is a stable released version. 

> Upstream should have a release branch for the versioned formulae version and still make security updates for that version, when necessary. For example, PHP 5.5 was not a supported version but PHP 7.2 was in January 2018.

Yes, this is fulfilled. Please find the corresponding release branch [here](https://github.com/gohugoio/hugo/tree/release-0.72.0)

> Versioned formulae share a codebase with the main formula. If the project is split into a different repository we recommend creating a new formula (formula2 rather than formula@2 or formula@1).

Yes, this versioned formulae does share the same codebase with the main formula. 

> Formulae that depend on versioned formulae must not depend on the same formulae at two different versions twice in their recursive dependencies. For example, if you depend on openssl@1.0 and foo, and foo depends on openssl then you must instead use openssl.

This is fulfilled. No dependencies issue.

> Versioned formulae should only be linkable at the same time as their non-versioned counterpart if the upstream project provides support for it, e.g. using suffixed binaries. If this is not possible, use keg_only :versioned_formula to allow users to have multiple versions installed at once.

`keg_only :versioned_formula` already added to the formulae. 

- A keg_only :versioned_formula should not post_install anything in the HOMEBREW_PREFIX that conflicts with or duplicates the non-versioned counterpart (or other versioned formulae). For example, a node@6 formula should not install its npm into HOMEBREW_PREFIX like the node formula does.

This versioned formulae does not post_install anything. 

> Versioned formulae submitted should be expected to be used by a large number of people. If this ceases to be the case: they will be removed. We will aim not to remove those in the top 3,000 install_on_request formulae.

Hugo is a popular static site generator. It's among the top ranked formales [here](https://formulae.brew.sh/analytics/install-on-request/365d/). 

> Versioned formulae should not have resources that require security updates. For example, a node@6 formula should not have an npm resource but instead rely on the npm provided by the upstream tarball.

This versioned formulae does not have any resources that require security updates.

> Versioned formulae should be as similar as possible and sensible compared to the non-versioned formulae. Creating or updating a versioned formula should be a chance to ask questions of the non-versioned formula, e.g. can some unused or useless options be removed or made default?

This versioned formulae is very similar as to the non-versioned formular, except for the url and hash. 

> No more than five versions of a formula (including the non-versioned one) will be supported at any given time, regardless of usage. When removing formulae that violate this we will aim to do so based on usage and support status rather than age.

This is not an issue. Currently there are only 1 main in homebrew-core and 2 versioned in PR.

**Comment by gromgit** [comment]
> and still make security updates for that version, when necessary. For example, PHP 5.5 was not a supported version but PHP 7.2 was in January 2018.

You didn't address this part. At the very least, there should be a written commitment from the author to backport security fixes to the versions that you're requesting to version. Ideally, a clear public statement about support for older versions, like [PHP](https://www.php.net/supported-versions.php) and [PostgreSQL](https://www.postgresql.org/support/versioning/), gives Homebrew maintainers a clear timeline to remove unsupported versions.

**Comment by chow1026** [comment]
Thank you for the direct examples. Since I am not a maintainer of Hugo, I will speak with them about the idea of having version formulaes on homebrew and corresponding requirements. 

Thanks for taking the time to review and explain.

**Pull request closed without merging**
