### PR TITLE
docker 1.12.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by alex** [comment]
I am confused, the buidl failures look like like garden variety "this does not compile" errors.

**Comment by DomT4** [comment]
Looks like a fairly major release, perhaps there's build changes we need to tweak for here.

**Comment by ushuz** [comment]
docker 1.12 split client and daemon into two binaries, thus affected packaging process. 

See here: https://github.com/docker/docker/blob/master/project/PACKAGERS.md#dynamic-daemon--client-only-binary

P.S. `DOCKER_CLIENTONLY` envvar was removed by https://github.com/docker/docker/commit/9e7651db4d464649bc32cf346fdee8c6900ebe0f

**Comment by alex** [comment]
I don't think I'll have time to sort this out, so I'll leave it to someone else.

**Pull request closed without merging**
