### PR TITLE
percona-server 5.7.19-17

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
[ 36%] Building CXX object storage/rocksdb/CMakeFiles/rocksdb.dir/ha_rocksdb.cc.o
cd /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DHAVE_CONFIG_H -DHAVE_LIBEVENT1 -DLZ4 -DMYSQL_DYNAMIC_PLUGIN -DROCKSDB_LIB_IO_POSIX -DROCKSDB_PLATFORM_POSIX -DZLIB -DZSTD -Drocksdb_EXPORTS -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/include -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/extra/rapidjson/include -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/libbinlogevents/include -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/libbinlogevents/export -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/rocksdb -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/rocksdb/include -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/rocksdb/include/rocksdb -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/rocksdb/third-party/gtest-1.7.0/fused-src -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/third_party/lz4/lib -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/third_party/zstd/lib -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/third_party/zstd/lib/common -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/sql -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/sql/auth -I/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/regex -I/usr/local/opt/openssl/include  -std=c++11 -Wno-deprecated-declarations  -Wall -Wextra -Wformat-security -Wvla -Woverloaded-virtual -Wno-unused-parameter -Wno-null-conversion -Wno-unused-private-field -DNDEBUG -DDBUG_OFF -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -o CMakeFiles/rocksdb.dir/ha_rocksdb.cc.o -c /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:24:
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./ha_rocksdb.h:33:
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./ib_ut0counter.h:88:10: error: cannot initialize return object of type 'size_t' (aka 'unsigned long') with an rvalue of type 'pthread_t _Nonnull' (aka '_opaque_pthread_t *')
                return get_curr_thread_id();
                       ^~~~~~~~~~~~~~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./ib_ut0counter.h:41:30: note: expanded from macro 'get_curr_thread_id'
#define get_curr_thread_id() pthread_self()
                             ^~~~~~~~~~~~~~
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:24:
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./ha_rocksdb.h:390:
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:36:20: error: use of undeclared identifier 'htobe64'
  uint64 net_val = htobe64(val);
                   ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:46:20: error: use of undeclared identifier 'htobe32'
  uint32 net_val = htobe32(val);
                   ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:56:20: error: use of undeclared identifier 'htobe16'
  uint16 net_val = htobe16(val);
                   ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:69:20: error: use of undeclared identifier 'htobe64'
  uint64 net_val = htobe64(n);
                   ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:78:20: error: use of undeclared identifier 'htobe32'
  uint32 net_val = htobe32(n);
                   ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:87:20: error: use of undeclared identifier 'htobe16'
  uint16 net_val = htobe16(n);
                   ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:117:10: error: use of undeclared identifier 'be64toh'
  return be64toh(net_val);
         ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:128:10: error: use of undeclared identifier 'be32toh'
  return be32toh(net_val);
         ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_buff.h:139:10: error: use of undeclared identifier 'be16toh'
  return be16toh(net_val);
         ^
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:62:
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_datadic.h:685:41: error: implicit instantiation of undefined template 'std::__1::array<void (myrocks::Rdb_key_def::*)(const myrocks::Rdb_collation_codec *, const Field *, myrocks::Rdb_pack_field_context *) const, 2>'
  std::array<rdb_make_unpack_info_t, 2> m_make_unpack_info_func;
                                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:62:
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_datadic.h:686:43: error: implicit instantiation of undefined template 'std::__1::array<int (myrocks::Rdb_key_def::*)(myrocks::Rdb_field_packing *, Field *, unsigned char *, myrocks::Rdb_string_reader *, myrocks::Rdb_string_reader *) const, 2>'
  std::array<rdb_index_field_unpack_t, 2> m_unpack_func;
                                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:62:
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_datadic.h:688:26: error: implicit instantiation of undefined template 'std::__1::array<unsigned char, 256>'
  std::array<uchar, 256> m_enc_idx;
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:62:
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_datadic.h:689:26: error: implicit instantiation of undefined template 'std::__1::array<unsigned char, 256>'
  std::array<uchar, 256> m_enc_size;
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:62:
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/./rdb_datadic.h:691:26: error: implicit instantiation of undefined template 'std::__1::array<unsigned char, 256>'
  std::array<uchar, 256> m_dec_size;
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:679:8: error: cannot initialize a member subobject of type 'unsigned long *' with an rvalue of type 'uint64_t *' (aka 'unsigned long long *')
static MYSQL_SYSVAR_ENUM(
       ^~~~~~~~~~~~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/include/mysql/plugin.h:390:34: note: expanded from macro 'MYSQL_SYSVAR_ENUM'
  #name, comment, check, update, &varname, def, typelib }
                                 ^~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:749:8: error: cannot initialize a member subobject of type 'unsigned long *' with an rvalue of type 'uint64_t *' (aka 'unsigned long long *')
static MYSQL_SYSVAR_ULONG(max_total_wal_size,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/include/mysql/plugin.h:375:34: note: expanded from macro 'MYSQL_SYSVAR_ULONG'
  #name, comment, check, update, &varname, def, min, max, blk }
                                 ^~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:780:8: error: cannot initialize a member subobject of type 'unsigned long *' with an rvalue of type 'uint64_t *' (aka 'unsigned long long *')
static MYSQL_SYSVAR_ULONG(
       ^~~~~~~~~~~~~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/include/mysql/plugin.h:375:34: note: expanded from macro 'MYSQL_SYSVAR_ULONG'
  #name, comment, check, update, &varname, def, min, max, blk }
                                 ^~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/storage/rocksdb/ha_rocksdb.cc:841:8: error: cannot initialize a member subobject of type 'unsigned long *' with an rvalue of type 'uint64_t *' (aka 'unsigned long long *')
static MYSQL_SYSVAR_ULONG(max_manifest_file_size,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/percona-server-20170831-44078-1degtiw/percona-server-5.7.19-17/include/mysql/plugin.h:375:34: note: expanded from macro 'MYSQL_SYSVAR_ULONG'
  #name, comment, check, update, &varname, def, min, max, blk }
                                 ^~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [storage/rocksdb/CMakeFiles/rocksdb.dir/ha_rocksdb.cc.o] Error 1
make[1]: *** [storage/rocksdb/CMakeFiles/rocksdb.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ilovezfs** [comment]
@DomT4 I would not object if you fixed this for me. :innocent:

**Comment by DomT4** [comment]
See, now I just feel like I've done something to upset you :wink:.

What is even with the Yosemite failure lol:
```
-- Performing Test HAVE_STDCXX11 - Success
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
/tmp/percona-server-20170831-85442-18xzoew/percona-server-5.7.19-17/storage/rocksdb/get_rocksdb_files.sh: line 7: $MKFILE: ambiguous redirect
/Applications/Xcode.app/Contents/Developer/usr/bin/make: option `--makefile' requires an argument
Usage: make [options] [target] ...
```

And Sierra failed another way:
```
In file included from /tmp/percona-server-20170831-96906-67bw7l/percona-server-5.7.19-17/storage/rocksdb/rocksdb/port/port.h:18:
/tmp/percona-server-20170831-96906-67bw7l/percona-server-5.7.19-17/storage/rocksdb/rocksdb/port/port_posix.h:50:12: fatal error: 'endian.h' file not found
  #include <endian.h>
```

And El Cap failed yet another way:
```
/tmp/percona-server-20170831-35956-1x5cw7z/percona-server-5.7.19-17/storage/rocksdb/tools/mysql_ldb.cc:11:36: error: default initialization of an object of const type 'const myrocks::Rdb_pk_comparator' without a user-provided default constructor
  const myrocks::Rdb_pk_comparator pk_comparator;
                                   ^
                                                {}
```

What... what did they do with this release :eyes:

**Comment by ilovezfs** [comment]
>See, now I just feel like I've done something to upset you :wink:.

You? Never.

>What is even with the Yosemite failure

That is a common one: https://github.com/Homebrew/homebrew-core/pull/15003#issuecomment-311400703

>What... what did they do with this release

They tempted me to `rm percona*` from homebrew/core.

**Pull request closed without merging**
