### PR TITLE
platformio 4.3.4

### PR DESCRIPTION
**Pull request by ivankravets**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

* Added [PlatformIO CLI Shell Completion](https://docs.platformio.org/page/core/userguide/system/completion/index.html) for Fish, Zsh, Bash, and PowerShell ([issue #3435](https://github.com/platformio/platformio-core/issues/3435))
* Automatically build ``contrib-pysite`` package on a target machine when pre-built package is not compatible ([issue #3482](https://github.com/platformio/platformio-core/issues/3482))
* Fixed an issue on Windows when installing a library dependency from Git repository ([issue #2844](https://github.com/platformio/platformio-core/issues/2844), [issue #3328](https://github.com/platformio/platformio-core/issues/3328))

### CODE REVIEW

**Review by issyl0 — CHANGES_REQUESTED** [review]
Thanks for this PR, @ivankravets. The version bump sounds packed full of features! 👍

One thing that would be good here is to make sure that the `brew test platformio` command is testing a feature of the command-line tool and asserting some output, rather than just that it prints `--help`. Something like the following would be good to add, please:

```ruby
  test do
    output = shell_output("#{bin}/platformio account show 2>&1", 1).chomp
    assert_match "Error: You are not authorized! Please log in to PIO Account.", output
  end
```

**Comment by ivankravets** [comment]
@issyl0  thanks for the idea! I updated PR and added real tests :)

**Comment by issyl0** [comment]
Those tests look good, thanks! Could you please squash your commits into one named `platformio 4.3.4`, then this will be mergeable once it passes CI.

**Comment by ivankravets** [comment]
Sorry, done in https://github.com/Homebrew/homebrew-core/pull/55158

**Pull request closed without merging**
