### PR TITLE
riemann 0.2.11

### PR DESCRIPTION
**Pull request by mnuessler**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by mnuessler** [comment]
I think the build fails only because it tries to download riemann several times in a row and there is some kind of download limit for a time period.

**Comment by mikemcquaid** [comment]
@mnuessler A bunch of Homebrew people are going to end up doing that so we'll need to work out some solution to this.

**Comment by mikemcquaid** [comment]
Perhaps finding a `mirror` we can add?

**Comment by mnuessler** [comment]
Unfortunately I am not able to find a mirror. The download limit is not a problem for homebrew users, just for the build because it does several downloads within a very short time.

**Comment by mikemcquaid** [comment]
There's only one download per (virtual) machine so it'll be the fact they share the same external IP address. This will be a problem for Homebrew users who share an external IP address.

**Comment by mikemcquaid** [comment]
We can always consider mirroring ourselves if that's a better option.

**Comment by apjanke** [comment]
A version of the releases are also hosted on their [GitHub releases](https://github.com/riemann/riemann/releases). E.g. https://github.com/riemann/riemann/archive/0.2.11.tar.gz.

**Comment by apjanke** [comment]
I [asked upstream](https://github.com/riemann/riemann/issues/716) if they would include the distribution tarballs with the GitHub releases, too. That seems like an ideal mirroring situation.

**Comment by apjanke** [comment]
There's [already a mirror out there](https://github.com/riemann/riemann/issues/716#issuecomment-241855800):  https://wintermute.skunkwerks.at/riemann/releases/

Added it in #4207.

**Comment by MikeMcQuaid** [comment]
Replaced with https://github.com/Homebrew/homebrew-core/pull/4207 (@apjanke, probably worth using "Closes" in future subsuming PRs to autoclone).

**Comment by apjanke** [comment]
Thanks.

I had the "Closes" in the PR, but since the PR gets closed by `brew pull` instead of a normal merge, it didn't trigger. Forgot to follow it manually. And I've avoided putting "Closes" in the commit comments for a PR, because IIRC, those get spuriously triggered when the test-bot runs them. Is there a good way to get auto-closing behavior to work with `brew pull`?

**Pull request closed without merging**
