### PR TITLE
openssl@1.1 1.1.1a

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
I don't think the CI issues are because of this patch?

**Comment by fshot** [comment]
@alex - Yes, this looks like a global issue with the Homebrew Jenkins server.  I've [posted to the Homebrew Community forum](https://discourse.brew.sh/t/new-jenkins-brew-sh-issue-every-pr-failing-on-brew-cleanup-prune-7/3488) in hopes of getting some help from the CI maintainers.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @alex !

**Pull request closed without merging**
