### PR TITLE
expat 2.4.3

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
long running build on linux, gonna rerun one more time.

**Comment by alebcay** [comment]
Sorry for the noise on this issue. For myself/other maintainers' reference, looks like this is waiting on #90318 which stalled the Linux test runner on the first run attempt (after running for 5+ hours).

**Comment by chenrui333** [comment]
make sense, thanks @alebcay!

**Comment by chenrui333** [comment]
timeout issue on linux build.

**Comment by chenrui333** [comment]
reverted my change as there are lots formulae depend on expat for linux build

**Comment by carlocab** [comment]
Had to kill `heartbeat` again.

**Comment by iMichka** [comment]
Yes the `heartbeat` stays stuck forever. I've seen that in other PR's and mentionned it to @Bo98 who wanted to look at the root cause (at least in Homebrew/brew to prevent stuck pull requests).

**Comment by carlocab** [comment]
We shouldn't even need to be testing `heartbeat` here. The dependency is `heartbeat` -(build)-> `python@3.10` ---> `expat`. I should pick up my changes to testing dependents again.

**Comment by chenrui333** [comment]
at this point, should we disable `heartbeat` until we can rebuild it again?

```
==> Analytics
install: 9 (30 days), 74 (90 days), 412 (365 days)
install-on-request: 9 (30 days), 74 (90 days), 412 (365 days)
build-error: 0 (30 days)
```

**Comment by carlocab** [comment]
Well, we can build heartbeat. That works fine. What doesn't work is testing heartbeat as a dependent, but seems to only be an issue on Linux.

**Review by carlocab — APPROVED** [review]
Linux failures look either pre-existing or unrelated to me. I think most of them are `:all` bottles that were never tested properly on Linux.

**Review by iMichka — CHANGES_REQUESTED** [review]
Agreed that we can merge, linux issues are pre-existing.

But the first commit is named "expat 2.4.2", so even with autosquash we will get the wrong commit message. Can someone rebase this, and squash the commits into a single one?

**Comment by carlocab** [comment]
Actually, `--autosquash` is smart enough not to be fooled by the first commit having the wrong version.

**Review by iMichka — APPROVED** [review]
Ha ha did not know that. Too much cleverness in that algorithm.

This can be shipped then.

**Comment by owine** [comment]
I actually noticed my livecheck reporting 2.4.4 available. I’m not sure if the preference would be to capture that here or merge and open a new PR for 2.4.4.

**Comment by carlocab** [comment]
Let's merge this first... CI here takes ages to run.

**Pull request closed without merging**
