### PR TITLE
mariadb 10.4.14

### PR DESCRIPTION
**Pull request by gfitzp**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Rylan12** [comment]
Thanks, @gfitzp!

Can you update the `license` line to say `license "GPL-2.0-only"`?

**Comment by gfitzp** [comment]
@Rylan12 Sure thing, updated!

**Comment by Rylan12** [comment]
One more thing: can you squash the commits so we just have the `mariadb 10.4.14` commit?

**Comment by gfitzp** [comment]
@Rylan12 Sure thing, I think it should be all set in one commit now.

**Comment by Rylan12** [comment]
Yeah, this isn't quite what we're looking for (looks like a `git merge` instead of `git rebase`. Take a look [here](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#following-up); it might help explain what to do for the future. Essentially, `git rebase --interactive` allows you to change the order/number of commits. You can `fixup` commits into their parents which will, essentially, combine multiple commits into just one. There are plenty of videos/tutorials online if you'd like to learn more.

I'll take care of it in this case, though, so no worries!

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
So, as you may have noticed, something weird happened with the publish. I've forced pushed to reset everything, but we'll need CI to run again. Once it runs this should be good.

Sorry for the confusing messages!

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Okay, everything should be good now...

Thanks for your patience, @gfitzp!

**Comment by gfitzp** [comment]
No worries, thanks so much for your assistance @Rylan12 !

**Pull request closed without merging**
