### PR TITLE
biosig: use tinyxml2

### PR DESCRIPTION
**Pull request by scpeters**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Split out from #119829.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Awesome, thanks @scpeters!

**Comment by scpeters** [comment]
rarian build works on macOS but fails on Linux

**Comment by p-linnane** [comment]
Rerunning with no-fail-fast so we can see everything and debug from there.

**Comment by scpeters** [comment]
> rarian build works on macOS but fails on Linux

ok, I was wrong about `rarian`. I was testing on my local machine that still had `tinyxml` installed and linked in the background. Unlinking `tinyxml` shows the same failure. I'll redact `rarian` from this PR, since I think `biosig` does still work

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
