### PR TITLE
dbcrossbar 0.5.0-beta.4 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to dbcrossbar/dbcrossbar#160

### CODE REVIEW

**Comment by chenrui333** [comment]
>  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/crc32c-0.4.0/src/hw.rs:5:5
  |
5 | use std::arch::x86_64 as simd;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `x86_64` in `arch`

It does not support apple arm64 yet.

**Comment by chenrui333** [comment]
on 11

```
  = note: ld: library not found for -lpq
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by chenrui333** [comment]
Close it for now, and revisit it later.

**Comment by SMillerDev** [comment]
No betas

**Pull request closed without merging**
