### PR TITLE
aravis 0.7.3

### PR DESCRIPTION
**Pull request by shwang53**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
<details>
<summary>Build failure</summary>
```
08:54:02 ==> brew install --verbose --build-bottle aravis
08:54:26 ==> FAILED
08:54:26 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200303-80542-1tmayxj.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/aravis.rb --build-bottle --verbose
08:54:26 ==> Downloading https://download.gnome.org/sources/aravis/0.7/aravis-0.7.3.tar.xz
08:54:26 Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/83a87302665f4bad58cec3ff3ae86e390d015b10ee933078566049c42f0b2fea--aravis-0.7.3.tar.xz
08:54:26 ==> Verifying 83a87302665f4bad58cec3ff3ae86e390d015b10ee933078566049c42f0b2fea--aravis-0.7.3.tar.xz checksum
08:54:26 tar xof /Users/brew/Library/Caches/Homebrew/downloads/83a87302665f4bad58cec3ff3ae86e390d015b10ee933078566049c42f0b2fea--aravis-0.7.3.tar.xz -C /private/tmp/d20200303-80543-1dd9wmk
08:54:26 cp -pR /private/tmp/d20200303-80543-1dd9wmk/aravis-0.7.3/. /private/tmp/aravis-20200303-80543-1yri3yt/aravis-0.7.3
08:54:26 chmod -Rf +w /private/tmp/d20200303-80543-1dd9wmk
08:54:26 Error: An exception occurred within a child process:
08:54:26   Errno::ENOENT: No such file or directory @ rb_sysopen - viewer/Makefile.am
08:54:26 
08:54:26 ==> brew uninstall --force adwaita-icon-theme atk autoconf automake bison boost cairo cmake docbook docbook-xsl doxygen faac faad2 flac fontconfig freetype fribidi gd gdbm gdk-pixbuf gettext glib glib-networking gmp gnutls gobject-introspection graphite2 graphviz gsettings-desktop-schemas gst-plugins-bad gst-plugins-base gst-plugins-good gstreamer gtk+3 gtk-doc gts harfbuzz hicolor-icon-theme icu4c intltool itstool jasper jpeg lame libcroco libepoxy libevent libffi libidn2 libmms libnice libnotify libogg libpng libpsl librsvg libshout libsoup libssh2 libtasn1 libtiff libtool libunistring libusb libvorbis libvpx libxml2 lzo meson netpbm nettle ninja openssl@1.1 opus orc p11-kit pango pcre pixman pkg-config python python@3.8 readline rtmpdump rust source-highlight speex sphinx-doc sqlite srtp taglib theora unbound vala webp xz yasm
08:54:56 
08:54:56 ==> /usr/bin/git -C homebrew/homebrew-core checkout master -f
```
</details>

**Comment by Bo98** [comment]
```
../src/arvgvstream.c:50:10: fatal error: 'linux/if_packet.h' file not found
#include <linux/if_packet.h>
         ^~~~~~~~~~~~~~~~~~~
```

oh dear

**Comment by issyl0** [comment]
Finally, a PR in homebrew-core that I can try and build on Linux and have it be a better experience! :trollface:

**Comment by issyl0** [comment]
I followed the "not directly supported" building on macOS instructions (https://github.com/AravisProject/aravis#building-on-mac-os-x), so hey, we tried... :stuck_out_tongue:

**Comment by Bo98** [comment]
`-Dpacket-socket=false` might work

**Comment by Bo98** [comment]
Actually just realised 0.7.x is unstable so this is can't be merged, sorry.

**Comment by chenrui333** [comment]
@Bo98 That is fine, thanks the work though!

**Pull request closed without merging**
