### PR TITLE
groff: fix build

### PR DESCRIPTION
**Pull request by carlocab**
See https://github.com/Homebrew/homebrew-core/issues/65000#issuecomment-728899218

Builds on https://github.com/Homebrew/homebrew-core/pull/64842

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Newly added dependencies are for creating PDF and HTML files, and for file encoding recognition.

### CODE REVIEW

**Comment by jonchang** [comment]
Thanks for working on this, I figured it would be something fiddly that touches a ton of files. Do you mind submitting a pull request to Homebrew/formula-patches and referencing that, instead of the embedded patch? Thanks!

**Comment by carlocab** [comment]
Sure, no problem. I was actually thinking that's what needed to be done here; I just didn't know how that worked exactly. I will go have a look and figure it out.

**Comment by jonchang** [comment]
Just make a pull request with this patch in the `groff` directory.

**Comment by carlocab** [comment]
PR at Homebrew/formula-patches opened.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
lgtm though.

**Review by jonchang — DISMISSED** [review]

**Review by jonchang — APPROVED** [review]

**Pull request closed without merging**
