### PR TITLE
snapcraft 3.7.2

### PR DESCRIPTION
**Pull request by tobias-bischoff**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
The test fails with
```
ModuleNotFoundError: No module named 'pbr'
```
This is probably due to the resources not being up to date with the new release. You can take a look at [homebrew-pypi-poet](https://github.com/tdsmith/homebrew-pypi-poet) to help you update all the resources.

**Comment by tobias-grasse** [comment]
@Moisan Thanks for the pointer to `homebrew-pypi-poet`! Maybe I'm missing something obvious, but running `poet snapcraft` (in a virtual env with snapcraft 3.7.2 installed from the release tarball) doesn't pick up the local installation of snapcraft:

```
PackageVersionNotFoundWarning: Could not find an exact version match for snapcraft version 3.7.2; using newest instead
  format(name, version), PackageVersionNotFoundWarning)
```
Thus, the generated resource list is only valid for snapcraft 3.3, the latest version released on PyPI.org – but the whole point of this PR is to use the GH releases directly, so there's no snapcraft 3.7.2 on PyPI.org in the first place 😄 

I skimmed poet's docs + issues to see if poet supports local packages at all, but couldn't find a hint. The two follow-up commits add/update resources, will continue until Jenkins (hopefully) is satisfied.

**Comment by tobias-grasse** [comment]
Ping @Moisan: The CI runs the tests fine again, is this ready to merge? Don’t want to nag, but snapcraft macOS users have been asking 😊 thanks in advance!

**Comment by Moisan** [comment]
Thank you @tobias-grasse ! 

For the poet part, I think it only covers packages available on PyPI.

**Pull request closed without merging**
