### PR TITLE
mercurial 5.2

### PR DESCRIPTION
**Pull request by ghost**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
See https://github.com/Homebrew/homebrew-core/pull/44095
It's probably time to move to Python 3

**Comment by socifo** [comment]
I think should follow:

>  move back to Python 2
    update to 5.2 when it is released
    update to Python 3 somewhere before 2019-12-31

wait longer for python3, 5.2 very recent

**Comment by fxcoudert** [comment]
Upstream recommendations at https://www.mercurial-scm.org/pipermail/mercurial-packaging/2019-October/000282.html state:

> We are asking packagers to switch the Python that is distributed with
> Mercurial or that Mercurial uses by default to the most modern version of
> Python 3 you can with the 5.2 release.

So let's do that!

**Comment by socifo** [comment]
updated, now uses python3.

**Comment by fxcoudert** [comment]
Thanks. Will rebottle `cayley` next.

**Pull request closed without merging**
