### PR TITLE
Delete molten-vk.rb

### PR DESCRIPTION
**Pull request by iMonZ**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This formula is outdated and broken that's why a temporary [cask](https://github.com/Homebrew/homebrew-cask/pull/98204) is created.

After the cask is merged this formula can be removed until someone fixed the issues

### CODE REVIEW

**Comment by carlocab** [comment]
How is it broken? Even if it were, it probably shouldn't be removed. It stands a better chance of someone coming along to fix it if it were deprecated/disabled instead.

Ref. https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae

**Comment by iMonZ** [comment]
> How is it broken? Even if it were, it probably shouldn't be removed. It stands a better chance of someone coming along to fix it if it were deprecated/disabled instead.
> 
> Ref. https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae

This formula can still be found in PR.

In that time there is a cask for the Vulkan-sdk

If the problems are fixed this formula can be added again into the main repo

**Review by carlocab — CHANGES_REQUESTED** [review]
>This formula can still be found in the PR section.

It's much less discoverable that way. It also integrates less well with Homebrew tooling such as `brew extract`. Please disable the formula instead.

Please also answer this question:

>How is it broken?

**Comment by iMonZ** [comment]
> > This formula can still be found in the PR section.
> 
> It's much less discoverable that way. Please disable the formula instead.
> 
> Please also answer this question:
> 
> > How is it broken?

1. the formula is outdated
2. currently its not possible to compile. A few people (including me) tried to fix that but without luck

Thank you I will disable this formula instead

**Comment by carlocab** [comment]
Thanks. When you edit your commit, please use homebrew/core's preferred commit message format. For example,

    molten-vk: disable

**Comment by iMonZ** [comment]
> Thanks. When you edit your commit, please use homebrew/core's preferred commit message format. For example,
> 
> ```
> molten-vk: disable
> ```

Where should I add this line?

**Comment by carlocab** [comment]
I tried installing and testing this formula, and it seems to work fine, so I actually still don't understand how this is broken. That probably means it shouldn't be disabled either, as it still has about 100 monthly installs.

At most, it should be deprecated, but I'm not sure about that either.

**Comment by carlocab** [comment]
>Where should I add this line?

That should be the subject of your commit message. Please see the documentation: https://docs.brew.sh/Formula-Cookbook#commit

**Comment by iMonZ** [comment]
> I tried installing and testing this formula, and it seems to work fine, so I actually still don't understand how this is broken. That probably means it shouldn't be disabled either, as it still has about 100 monthly installs.
> 
> At most, it should be deprecated, but I'm not sure about that either.

The bottles are working (but the version is outdated)
But its not possible to build from source (maybe its because of macOS BigSur)

**Comment by carlocab** [comment]
This is version 1.0.41, which appears to have been tagged early last year: https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.41

That's nowhere near outdated enough to warrant deprecating or disabling it.

You can add the `deprecate!`/`disable!` lines just after the bottle block. However, I should emphasise that I don't think this should be deprecated or disabled at all.

**Comment by iMonZ** [comment]
> This is version 1.0.41, which appears to have been tagged early last year: https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.41
> 
> That's nowhere near outdated enough to warrant deprecating or disabling it.
> 
> You can add the `deprecate!`/`disable!` lines just after the bottle block. However, I should emphasise that I don't think this should be deprecated or disabled at all.

This version is not compatible with the latest apple products (and a lot of features are not working with BigSur)
Thats why I want to disable this formula until its fixed! (to not confuse the developers)

I created a PR for a cask which work perfectly fine.

**Pull request closed without merging**
