### PR TITLE
nghttp2 1.13.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
#linkfail

```
==> FAILED
Error: 1 problem in 1 formula
nghttp2:
  * Formulae are required to declare all linked dependencies.
    Please add all linked dependencies to the formula with:
      depends_on "libxml2" => :linked
```

**Comment by DomT4** [comment]
Is it picking it up from the environment or is that solid gunk?

**Comment by ilovezfs** [comment]
@DomT4 

```
iMac-TMP:Formula joe$ brew deps -1 nghttp2|while read f; do brew deps "$f"|grep -q libxml2 && echo "$f" ; done
spdylay
```
So it comes from the environment since it will always be installed during bottling due to spdylay's unconditional dependency on libxml2 together with `spdylay => :recommended` and the default `"--with-libxml2=check"`. So this "fixes" it:
```
diff --git a/Formula/nghttp2.rb b/Formula/nghttp2.rb
index 2d144f3..3ea6931 100644
--- a/Formula/nghttp2.rb
+++ b/Formula/nghttp2.rb
@@ -59,6 +59,7 @@ class Nghttp2 < Formula
     args << "--enable-examples" if build.with? "examples"
     args << "--with-spdylay" if build.with? "spdylay"
     args << "--disable-python-bindings"
+    args << "--with-libxml2=no" unless MacOS.version <= :lion
 
     system "autoreconf", "-ivf" if build.head?
     system "./configure", *args
```

**Comment by DomT4** [comment]
Is that not strictly true though? We presumably still want `libxml2`, except the system is good enough to satisfy the requirement on newer OS X/macOS so it doesn't need _our_ `libxml2`?

Maybe it's worth poking at why `spdylay` needs _our_ `libxml2` all the time.

**Comment by ilovezfs** [comment]
>Maybe it's worth poking at why spdylay needs our libxml2 all the time.

Or maybe it's worth reverting `:linked` check since it's ridiculous?

**Comment by DomT4** [comment]
I'm somewhat dismayed it was added in for _everything_ rather than being restricted to `--strict` until we iron out the multiple awkward kinks. I think it's a good check, I'm unconvinced it's ready for primetime, even with Xu's recent (good) adjustments.

**Comment by ilovezfs** [comment]
I entirely fail to see the point since undeclared dependencies should be considered a feature not a bug. Perhaps there's a way to auto-assign all the #linkfail to someone else.

**Comment by DomT4** [comment]
I'd perhaps consider removing the addition of the:
```ruby
args << "--with-libxml2=no" unless MacOS.version <= :lion
```
Line for now, ignoring the audit error, merging as-is & opening a new Issue at `homebrew/brew` on how awkward this is getting.

**Comment by ilovezfs** [comment]
Situation is actually worse than that. `--without-spdylay` is broken.

**Comment by ilovezfs** [comment]
```
libtool: link: ar cru .libs/libnghttp2_asio.a  libnghttp2_asio_la-util.o libnghttp2_asio_la-http2.o libnghttp2_asio_la-ssl.o libnghttp2_asio_la-timegm.o libnghttp2_asio_la-asio_common.o libnghttp2_asio_la-asio_io_service_pool.o libnghttp2_asio_la-asio_server_http2.o libnghttp2_asio_la-asio_server_http2_impl.o libnghttp2_asio_la-asio_server.o libnghttp2_asio_la-asio_server_http2_handler.o libnghttp2_asio_la-asio_server_request.o libnghttp2_asio_la-asio_server_request_impl.o libnghttp2_asio_la-asio_server_response.o libnghttp2_asio_la-asio_server_response_impl.o libnghttp2_asio_la-asio_server_stream.o libnghttp2_asio_la-asio_server_serve_mux.o libnghttp2_asio_la-asio_server_request_handler.o libnghttp2_asio_la-asio_server_tls_context.o libnghttp2_asio_la-asio_client_session.o libnghttp2_asio_la-asio_client_session_impl.o libnghttp2_asio_la-asio_client_session_tcp_impl.o libnghttp2_asio_la-asio_client_session_tls_impl.o libnghttp2_asio_la-asio_client_response.o libnghttp2_asio_la-asio_client_response_impl.o libnghttp2_asio_la-asio_client_request.o libnghttp2_asio_la-asio_client_request_impl.o libnghttp2_asio_la-asio_client_stream.o libnghttp2_asio_la-asio_client_tls_context.o  .libs/libnghttp2_asio.lax/libhttp-parser.a/http_parser.o 
libtool: link: ranlib .libs/libnghttp2_asio.a
libtool: link: rm -fr .libs/libnghttp2_asio.lax
libtool: link: ( cd ".libs" && rm -f "libnghttp2_asio.la" && ln -s "../libnghttp2_asio.la" "libnghttp2_asio.la" )
/bin/sh ../libtool  --tag=CXX   --mode=link clang++   -g -O2   -o nghttp util.o http2.o timegm.o app_helper.o nghttp2_gzip.o  nghttp.o HtmlParser.o  ssl.o ../lib/libnghttp2.la ../third-party/libhttp-parser.la -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm -lev -L/usr/local/Cellar/openssl/1.0.2h_1/lib -lssl -lcrypto -L/usr/local/Cellar/jansson/2.7/lib -ljansson -lz -ldl  -pthread 
libtool: link: clang++ -g -O2 -o .libs/nghttp util.o http2.o timegm.o app_helper.o nghttp2_gzip.o nghttp.o HtmlParser.o ssl.o -pthread  ../lib/.libs/libnghttp2.dylib ../third-party/.libs/libhttp-parser.a -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib -lxml2 -lpthread -licucore -lm -lev -L/usr/local/Cellar/openssl/1.0.2h_1/lib -lssl -lcrypto -L/usr/local/Cellar/jansson/2.7/lib -ljansson -lz -ldl -pthread
Undefined symbols for architecture x86_64:
  "_SSL_CIPHER_get_id", referenced from:
      nghttp2::ssl::check_http2_cipher_black_list(ssl_st*) in ssl.o
  "_SSL_CTX_set_alpn_protos", referenced from:
      nghttp2::(anonymous namespace)::communicate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nghttp2_data_provider*, long long>, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nghttp2_data_provider*, long long> > >, nghttp2_session_callbacks const*) in nghttp.o
  "_SSL_CTX_set_next_proto_select_cb", referenced from:
      nghttp2::(anonymous namespace)::communicate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nghttp2_data_provider*, long long>, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nghttp2_data_provider*, long long> > >, nghttp2_session_callbacks const*) in nghttp.o
  "_SSL_get0_alpn_selected", referenced from:
      nghttp2::HttpClient::connection_made() in nghttp.o
  "_SSL_get0_next_proto_negotiated", referenced from:
      nghttp2::HttpClient::connection_made() in nghttp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [nghttp] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by DomT4** [comment]
Literally nobody (that we know of) is using the `--without` option there. Might as well turn it on by default.

**Comment by ilovezfs** [comment]
OK let's look at why spdylay thinks it needs our libxml2.

**Comment by ilovezfs** [comment]
For the same reason the head build in nghttp2 thinks it does, too. Because Autotools sucks:
```
==> autoreconf -i
configure.ac:184: warning: macro 'AM_PATH_XML2' not found in library
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:184: warning: macro 'AM_PATH_XML2' not found in library
configure.ac:184: error: possibly undefined macro: AM_PATH_XML2
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by DomT4** [comment]
Ah, that does make sense. The system doesn't bother shipping an `libxml.m4` file for it because Apple likes being hilariously unhelpful.

**Comment by ilovezfs** [comment]
Seems like something that could go in superenv like those custom pkgconfig files that broke everything when they got moved.

**Comment by ilovezfs** [comment]
iMac-TMP:~ joe$ wc -l /usr/local/Cellar/libxml2/2.9.4/share/aclocal/libxml.m4
     188 /usr/local/Cellar/libxml2/2.9.4/share/aclocal/libxml.m4

**Comment by ilovezfs** [comment]
@DomT4 Yep that would work.
```
diff --git a/Formula/spdylay.rb b/Formula/spdylay.rb
index 60f481b..255b216 100644
--- a/Formula/spdylay.rb
+++ b/Formula/spdylay.rb
@@ -17,10 +17,10 @@ class Spdylay < Formula
   depends_on "libtool" => :build
   depends_on "pkg-config" => :build
   depends_on "libevent" => :recommended
-  depends_on "libxml2"
   depends_on "openssl
 
   def install
+    cp HOMEBREW_LIBRARY/"Homebrew/os/mac/m4/libxml.m4", "m4"
     system "autoreconf -i"
     system "automake"
     system "autoconf"

```
gives us
```
iMac-TMP:~ joe$ brew linkage  spdylay
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libicucore.A.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/libevent/lib/libevent-2.0.5.dylib (libevent)
  /usr/local/opt/libevent/lib/libevent_openssl-2.0.5.dylib (libevent)
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/Cellar/spdylay/1.3.2/lib/libspdylay.7.dylib (spdylay)
```

**Comment by ilovezfs** [comment]
Library/Homebrew/vendor/m4/libxml.m4 ?
Library/Homebrew/os/m4/libxml.m4 ?
Library/Homebrew/os/mac/m4/libxml.m4 ?

or we can continue to require libxml2 everywhere the 188 line file is needed :)

**Comment by ilovezfs** [comment]
>whether a current libxml2 m4 file is backwards compatible with the prior system libxml2s or if that's going to cause problems if such a system was introduced

I'm not sure, but we could always supply multiple versions of the file if necessary.

**Comment by DomT4** [comment]
I guess we do for each OS X/macOS version we support with `pkg-config` support so it wouldn't be unprecedented. Just somewhat leery about blowing open this rabbit hole given our vendored `pkg-config` files have proven, at times, to be something of a pain heh.

**Comment by ilovezfs** [comment]
Yeah, the vendored pkg-config files seem like a massive hack, and this would be too, but ... :apple:.

**Comment by ilovezfs** [comment]
The question is whether it's sane to require libxml2 just for an m4 file... and my knee-jerk reaction is, no, that's not sane.

**Comment by DomT4** [comment]
Yeah. I agree with your assessment it's not a rational use of a hard `libxml2` dependency. 

_Theoretically_ we perhaps couldn't vendor m4 files from GPLv3 formulae due to the mess that is that license, but `libmxl2` is MIT so that'd be fine.

**Comment by ilovezfs** [comment]
>Theoretically we perhaps couldn't vendor m4 files from GPLv3 formulae due to the mess that is that license

I tend to think GPLv3 license concerns are massively overstated, and until someone from FSF emits something resembling human communication in our direction, I'm inclined to ignore the entire affair.

**Comment by DomT4** [comment]
GPLv2 is fine. It's just dealing with GPLv3 that's a nightmare, particularly due to the 555,000 ways people have tried to interpret it over the years.

**Comment by ilovezfs** [comment]
@DomT4 https://www.gnu.org/licenses/rms-why-gplv3.en.html

I cannot tell if that's deliberately written to sound deranged and paranoid or if they just can't help themselves.

**Comment by ilovezfs** [comment]
ok this has officially started to make my head hurt

**Comment by ilovezfs** [comment]
@DomT4 :green_apple:. I'm fairly confident the net achievement here is nout unless wasting time counts.

**Comment by DomT4** [comment]
I dislike this less than I thought I would. Nice work 👍.

**Comment by ilovezfs** [comment]
@DomT4 Yeah, it's nice not to require libxml2 if the system version suffices. I'm not thrilled with
```
    if MacOS.version > :lion
      Formula["libxml2"].stable.stage { (buildpath/"m4").install "libxml.m4" }
    end
```
but I don't think a larger conversation about `libxml.m4` needs to block this PR.

**Comment by DomT4** [comment]
Agreed. I do think it's worth having a discussion over at `brew` about vendoring necessary `.m4` files. It does smell funny to require whole dependencies to satisfy that one requirement at times.

**Pull request closed without merging**
