### PR TITLE
autorest 2.0.4283

### PR DESCRIPTION
**Pull request by ptolstoi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ptolstoi** [comment]
Are there any reasons for not merging I missed?

**Comment by fxcoudert** [comment]
There are no explanations for the changes made:

- github says 2.0.4222 is the latest release
- why is the URL changing from one host to another?
- does it now depend on both node and mono? that's unusual

**Comment by fxcoudert** [comment]
Also: it seems like autorest can auto-update: this needs to be disabled.

**Comment by SMillerDev** [comment]
It seems like this tool changed from .NET to JS based? The formula should probably be completely revisited.

**Pull request closed without merging**
