### PR TITLE
qscintilla2 2.9.1

### PR DESCRIPTION
**Pull request by apjanke**
Closes homebrew/homebrew#44726

### CODE REVIEW

**Comment by apjanke** [comment]
Well, this is new. The test failure on 10.10 and 1.11 is `brew doctor`.

```
Error Message

failed: brew doctor

Stacktrace

        Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    czmq

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install metis suite-sparse libsodium nspr readline spidermonkey tbb

Run `brew missing` for more details.

```

screen shot 2016-04-02 at 3 37 23 pm

Looking through the other homebrew/homebrew-core PRs, looks like others are failing with this issue, too.

**Comment by UniqMartin** [comment]
Just requeued this for you. Should be fixed …

**Comment by apjanke** [comment]
Fixed now; thanks. I'm going to try `brew pull`-ing this.

**Comment by apjanke** [comment]
Looks like it worked.

Thank you for your contribution to Homebrew, me!

**Comment by UniqMartin** [comment]
> Thank you for your contribution to Homebrew, me!

:joy:

**Pull request closed without merging**
