### PR TITLE
baobab 45.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
depends_on #142989

**Comment by chenrui333** [comment]
closing for now.

**Comment by chenrui333** [comment]
just reopened #142989

**Comment by chenrui333** [comment]
gonna rebase after #153408

**Comment by chenrui333** [comment]
should be good now

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
