### PR TITLE
crystal-lang 0.18.6

### PR DESCRIPTION
**Pull request by asterite**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by asterite** [comment]
Again failed... :-(

Am I doing something wrong, or is there something wrong in the PR itself?

**Comment by UniqMartin** [comment]
> Am I doing something wrong, or is there something wrong in the PR itself?

Neither. This seems to be an issue with GitHub infrastructure. (See Homebrew/brew#413 for details.)

**Comment by ilovezfs** [comment]
@asterite :green_apple: now :)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/01cb79e041a74cfd4a679329ce206eb6655d2b57. Thank you for your contribution to Homebrew @asterite; we appreciate it! :smiley_cat:

**Comment by asterite** [comment]
@ilovezfs @DomT4 Thank you! Your speed of fixing things and merging pull requests is amazing! 🎉

**Pull request closed without merging**
