### PR TITLE
yarn 0.25.4

### PR DESCRIPTION
**Pull request by morrislaptop**

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
https://yarnpkg.com/en/ still shows 0.24.6 as latest release despite GitHub so we'll need to wait for upstream confirmation.

**Comment by ilovezfs** [comment]
CC @Daniel15 it seems that https://github.com/yarnpkg/yarn/releases/latest and https://yarnpkg.com/en/ disagree about the latest version.

**Comment by Daniel15** [comment]
Sorry, not quite sure what happened there but the 0.25.x series is still an RC. I think the plan is to release 0.27.1 tomorrow as stable.

**Comment by ilovezfs** [comment]
@Daniel15 thanks for the quick response!

**Comment by ilovezfs** [comment]
@morrislaptop closing based on upstream guidance but thanks for the PR nonetheless!

**Pull request closed without merging**
