### PR TITLE
commandbox 5.2.1

### PR DESCRIPTION
**Pull request by bdw429s**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bdw429s** [comment]
It looks like some tests failed, but I don't quite understand why.  This is the same brew file that passed fine last month in our previous release.  I see an error message in the logs about not finding java, but openjdk is set up as a dependency in our formula, so I'm not sure what the issue is there.  
```
  depends_on "openjdk"
```
Perhaps someone can help shed some light on what the issue is.

**Comment by SMillerDev** [comment]
Just depending on openjdk might not be enough. You might need to set `JAVA_HOME`

**Comment by bdw429s** [comment]
@SMillerDev Thanks for the reply, but has this changed recently?  This is the same formula file we've used for a long time and we last pushed a version just last month. Does the openjdk dependency not set the standard java_home env var?  I really don't know anything about how Brew installs that. (I'm not even a Mac user)

**Comment by SMillerDev** [comment]
> @SMillerDev Thanks for the reply, but has this changed recently? This is the same formula file we've used for a long time and we last pushed a version just last month. Does the openjdk dependency not set the standard java_home env var? I really don't know anything about how Brew installs that. (I'm not even a Mac user)

For a long time our CI had Java installed using the default installer so the formulae could depend on it if needed. Now that we have Java in Homebrew core, and removed the standard Java from our CI we're finding out that a lot of the things we tested with an OpenJDK dependency secretly just used the standard Java.

**Comment by carlocab** [comment]
You just need to add something like

    ENV["JAVA_HOME"] = Formula["openjdk"].opt_libexec/"openjdk.jdk/Contents/Home"

at the start of the `test` block, I think.

**Comment by chenrui333** [comment]
license header ref:

```

/**
 * Copyright (C) 2012 Ortus Solutions, Corp
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */
```

**Comment by bdw429s** [comment]
@chenrui333 Thanks for helping out, I appreciate it!  Is there anything else I need to do in order to get this merged now?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
yeah, merging now! Thanks!

**Comment by bdw429s** [comment]
Thanks again for the assist, guys.  I'll update our brew formula template so my CI builds have the correct env vars being set in our new formula files for next time.

**Comment by chenrui333** [comment]
Sounds good!

**Pull request merged**
