### PR TITLE
kops 1.14.0

### PR DESCRIPTION
**Pull request by mikesplain**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mikesplain** [comment]
@BrewTestBot test this please!

**Comment by mikesplain** [comment]
@chenrui333 This should force 1.12, which would be our preferred fix.  Let me know if you want me to squash or anything.

Thanks!

**Comment by chenrui333** [comment]
@mikesplain yeah, please squash the commits. Thanks! :)

**Comment by mikesplain** [comment]
Done! Thank you!

**Comment by chenrui333** [comment]
👍 I will merge it after the PR build is done!

**Comment by mikesplain** [comment]
Thanks so much!

**Comment by chenrui333** [comment]
Thanks a lot for your contribution!

**Pull request closed without merging**
