### PR TITLE
dosbox-x 0.82.21

### PR DESCRIPTION
**Pull request by equal-l2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please, now that the Mojave node is fixed

**Comment by fxcoudert** [comment]
On macOS Mojave with Xcode 11, we get a build failure:

```
clang: error: the clang compiler does not support -pg option on versions of OS X 10.9 and later
```

**Comment by fxcoudert** [comment]
On macOS Sierra, we get:

```
drive_local.cpp:1186:13: error: use of undeclared identifier 'futimens'
        if (futimens(fileno(fhandle), ftsp)) {
            ^
```

**Comment by equal-l2** [comment]
> On macOS Mojave with Xcode 11, we get a build failure:
> 
> ```
> clang: error: the clang compiler does not support -pg option on versions of OS X 10.9 and later
> ```

I couldn't reproduce this.

**Comment by fxcoudert** [comment]
> On macOS Mojave with Xcode 11, we get a build failure

Sorry, ignore that one, I opened the wrong test results. Only the Sierra failure has to be dealt with.

**Comment by equal-l2** [comment]
> Only the Sierra failure has to be dealt with.

There's nothing to do with Sierra, since `futimens` has introduced in High Sierra.
I made this formula available only for High Sierra or higher.

**Pull request closed without merging**
