### PR TITLE
claws-mail 4.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
```
configure: error: Package requirements (gtk+-3.0 >= 3.20 cairo) were not met:

No package 'gtk+-3.0' found
```

**Comment by chenrui333** [comment]
This is my current setup

```diff
   depends_on "glib"
   depends_on "gnutls"
-  depends_on "gtk+"
+  depends_on "gtk+3"
   depends_on "libetpan"
   depends_on "nettle"
+  depends_on "pygobject3"
+  depends_on "python@3.9"
```

And then failed with

```
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/claws-mail/02.make:
typedef struct _AtkSocket         AtkSocket;
                                  ^
6 errors generated.
make[3]: *** [compose.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by chenrui333** [comment]
https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=4505

**Comment by mones** [comment]
Not sure why you label this as an upstream issue since the failing code is not even on upstream code base.
As already answered on upstream bug you need to fix your dependencies.

**Pull request closed without merging**
