### PR TITLE
libtorch: enabling openmp

### PR DESCRIPTION
**Pull request by sabify**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by sabify** [comment]
The tests will be passed after merging #101705.

**Comment by carlocab** [comment]
> The tests will be passed after merging #101705.

Still not passing.

**Comment by sabify** [comment]
Shouldn't the new `torchvision` bottle be available first to run the tests against it?

**Comment by sabify** [comment]
It seems the `libomp` feature of `torchvision` solely depends on this `libtorch` with `libomp` feature before building.

Here is the steps you can take to make the tests passed:

1. `brew install --build-from-source libtorch` (with this commit/pr)
2. `brew install --build-from-source torchvision` (the homebrew repo currently has the latest revision with the link to `libomp`, so no action needed)
3. `brew test torchvision` (tests will be passed)

The steps need to be taken to make this feature happen:

1. Force merge this commit.
2. A new `torchvision` revision with the new `libtorch` should be built.

**Comment by SMillerDev** [comment]
We won't merge this commit until CI turns green on it, you'll have to come up with another solution unfortunately.

**Comment by SMillerDev** [comment]
We won't merge this commit until CI turns green on it, you'll have to come up with another solution unfortunately.

**Comment by carlocab** [comment]
Rev bumping `torchvision` should suffice.

**Comment by sabify** [comment]
@SMillerDev You may not be familiar with [circular dependency](https://en.wikipedia.org/wiki/Circular_dependency)! I don't know another solution and I'm afraid there would be one. There might be a solution in homebrew's CI that I may not be aware of to batch these tasks. If not, these steps need to be done manually or make another CI pipeline that solves these dependency issues.

**Comment by carlocab** [comment]
There is no circular dependency here. I've fixed your issue for you, hopefully. We just need to wait for CI to finish.

**Comment by sabify** [comment]
@carlocab Would `torchvision` be built against this PR by increasing the rev?

**Comment by carlocab** [comment]
Yes.

**Comment by sabify** [comment]
Nice! I didn't know about this revision feature in my first contribution here...

**Comment by sabify** [comment]
Could you please make the CI run longer? some tasks was cancelled.

**Comment by sabify** [comment]
Could you please make the CI run longer? some tasks were cancelled.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
