### PR TITLE
docker-machine-driver-xhyve: remove

### PR DESCRIPTION
**Pull request by andig**
xhyve blocks upgrade to go1.15.6. xhyve is no longer used by Docker. It was introduced with 10.9 or 10.10 to take advantage of macOS' new Hyperkit.framework. Docker replaced it with hyperkit (which is based on xhyve and maintained).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Helps with unblocking go 1.15.6 in https://github.com/Homebrew/homebrew-core/pull/66355

### CODE REVIEW

**Comment by carlocab** [comment]
Disabling is probably better than removing it, as in the other PR: https://github.com/Homebrew/homebrew-core/pull/67054#issuecomment-747549172

Analytics has nearly 20,000 downloads for this formula in the past year. Would be good to be sure that this is the right course of action before doing it.

**Comment by bayandin** [comment]
It looks like people still use it: `install: 635 (30 days), 2,027 (90 days), 17,884 (365 days)`
This formula doesn't build on Big Sur from the beginning and it's not related to go update (https://github.com/Homebrew/homebrew-core/issues/65000)

**Comment by arbourd** [comment]
@bayandin Can you help us understand what the bare minimum is required for #66355? Should we only focus on fixing formulae that are broken in `10.15`, `10.14`?

For context, this is the current package usage that's being blocked: `install: 80,696 (30 days), 280,915 (90 days), 1,303,827 (365 days)`

**Comment by bayandin** [comment]
https://github.com/Homebrew/homebrew-core/pull/66355 should not introduce any new failures. If it discovers any new (unreported) failures (which are not related to go update), they should be fixed if possible, if not — reported (like we did for python https://github.com/Homebrew/homebrew-core/issues/66450)

**Comment by arbourd** [comment]
Thank you, that is a different answer from the Homebrew members in #66355.

For this issue, the repository is [arguably unmaintained](https://github.com/machine-drivers/docker-machine-driver-hyperkit#docker-machine-driver-hyperkit) according to: `The Hyperkit driver will eventually replace the existing xhyve driver and uses moby/hyperkit as a Go library.`

Should we keep it because of it's use (although it will unlikely be updated for 11.0)? I don't see much value in removing it if it does not block Go 1.15.6.

**Comment by fxcoudert** [comment]
Let's keep it for now, see my comment at https://github.com/Homebrew/homebrew-core/pull/66355 for details

**Pull request closed without merging**
