### PR TITLE
workflows/triage: update labels

### PR DESCRIPTION
**Pull request by carlocab**
Let's update the labels to be more appropriate after #171457.

### CODE REVIEW

**Comment by carlocab** [comment]
These changes were made entirely from memory, but I hope it's mostly right. We can fix the ones I got wrong later (or if someone notices something off, now).

**Review by MikeMcQuaid — APPROVED** [review]
Looks good to me (from what I can read of diff....)!

**Comment by carlocab** [comment]
@MikeMcQuaid needs another ✅ since https://github.com/Homebrew/homebrew-core/pull/173053 targets this branch

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by carlocab** [comment]
..or, rather, needs a ✅ from someone who is not-Mike.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
