### PR TITLE
glibc@2.13 (new formula)

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is extracted from #92329, to be able to bottle this formula first; and be able to tests stuff with a bottled glibc 2.13 version. I plan to use my tests in https://github.com/Homebrew/brew/pull/13231 to test the binutils build with glibc 2.13 once this PR is merged.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2022-05-11T22:06:41.6846199Z ##[group]Full linkage --cached glibc@2.13 output
2022-05-11T22:06:41.6846881Z System libraries:
2022-05-11T22:06:41.6847223Z   /lib/x86_64-linux-gnu/libc.so.6
2022-05-11T22:06:41.6848058Z   /lib/x86_64-linux-gnu/libdl.so.2
2022-05-11T22:06:41.6848404Z   /lib/x86_64-linux-gnu/libnsl.so.1
2022-05-11T22:06:41.6848748Z   /lib/x86_64-linux-gnu/libnss_files.so.2
2022-05-11T22:06:41.6849112Z   /lib/x86_64-linux-gnu/libpthread.so.0
2022-05-11T22:06:41.6849469Z   /lib/x86_64-linux-gnu/libresolv.so.2
2022-05-11T22:06:41.6849792Z   /lib/x86_64-linux-gnu/librt.so.1
2022-05-11T22:06:41.6850125Z   /lib64/ld-linux-x86-64.so.2
2022-05-11T22:06:41.6850717Z Homebrew libraries:
2022-05-11T22:06:41.6851035Z   /home/linuxbrew/.linuxbrew/Cellar/glibc@2.13/2.13/lib/gconv/libCNS.so (glibc@2.13)
2022-05-11T22:06:41.6851454Z   /home/linuxbrew/.linuxbrew/Cellar/glibc@2.13/2.13/lib/gconv/libGB.so (glibc@2.13)
2022-05-11T22:06:41.6851872Z   /home/linuxbrew/.linuxbrew/Cellar/glibc@2.13/2.13/lib/gconv/libISOIR165.so (glibc@2.13)
2022-05-11T22:06:41.6852277Z   /home/linuxbrew/.linuxbrew/Cellar/glibc@2.13/2.13/lib/gconv/libJIS.so (glibc@2.13)
2022-05-11T22:06:41.6852699Z   /home/linuxbrew/.linuxbrew/Cellar/glibc@2.13/2.13/lib/gconv/libJISX0213.so (glibc@2.13)
2022-05-11T22:06:41.6853114Z   /home/linuxbrew/.linuxbrew/Cellar/glibc@2.13/2.13/lib/gconv/libKSC.so (glibc@2.13)
2022-05-11T22:06:41.6853619Z [31mError:[0m source sequence is illegal/malformed utf-8
2022-05-11T22:06:41.6854090Z [1mDo not report this issue until you've run `brew update` and tried again.[0m
2022-05-11T22:06:41.6854730Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:224:in `generate'
2022-05-11T22:06:41.6855417Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:224:in `generate'
2022-05-11T22:06:41.6856089Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:394:in `dump'
2022-05-11T22:06:41.6856554Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cache_store.rb:76:in `write_if_dirty!'
2022-05-11T22:06:41.6856983Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cache_store.rb:34:in `use'
2022-05-11T22:06:41.6857521Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/linkage.rb:40:in `linkage'
2022-05-11T22:06:41.6857927Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

```
2022-05-11T22:06:29.5454484Z [34m==>[0m [1mBottling glibc@2.13--2.13.x86_64_linux.bottle.tar.gz...[0m
2022-05-11T22:06:29.5454896Z [31mError:[0m invalid byte sequence in UTF-8
2022-05-11T22:06:29.5457794Z [1mDo not report this issue until you've run `brew update` and tried again.[0m
2022-05-11T22:06:29.5458814Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:231:in `match'
2022-05-11T22:06:29.5459601Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:231:in `extname'
2022-05-11T22:06:29.5460108Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:276:in `block (2 levels) in text_files'
2022-05-11T22:06:29.5460864Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/pathname.rb:565:in `block in find'
2022-05-11T22:06:29.5461568Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
2022-05-11T22:06:29.5462221Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/find.rb:48:in `catch'
2022-05-11T22:06:29.5462885Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/find.rb:48:in `block in find'
2022-05-11T22:06:29.5463539Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/find.rb:43:in `each'
2022-05-11T22:06:29.5464170Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/find.rb:43:in `find'
2022-05-11T22:06:29.5465228Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/pathname.rb:565:in `find'
2022-05-11T22:06:29.5465741Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:271:in `each'
2022-05-11T22:06:29.5467594Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:271:in `reject'
2022-05-11T22:06:29.5468036Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:271:in `block in text_files'
2022-05-11T22:06:29.5468440Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:595:in `with_env'
2022-05-11T22:06:29.5468849Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:302:in `with_custom_locale'
2022-05-11T22:06:29.5469276Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:270:in `text_files'
2022-05-11T22:06:29.5469823Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:145:in `replace_text_in_files'
2022-05-11T22:06:29.5470318Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:133:in `replace_placeholders_with_locations'
2022-05-11T22:06:29.5471016Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:501:in `block (2 levels) in bottle_formula'
2022-05-11T22:06:29.5471485Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:406:in `ignore_interrupts'
2022-05-11T22:06:29.5472070Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:499:in `ensure in block in bottle_formula'
2022-05-11T22:06:29.5472677Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:499:in `block in bottle_formula'
2022-05-11T22:06:29.5473124Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg.rb:334:in `block in lock'
2022-05-11T22:06:29.5473776Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/lock_file.rb:35:in `with_lock'
2022-05-11T22:06:29.5474165Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg.rb:330:in `lock'
2022-05-11T22:06:29.5474734Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:390:in `bottle_formula'
2022-05-11T22:06:29.5475409Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:105:in `block in bottle'
2022-05-11T22:06:29.5475924Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `each'
2022-05-11T22:06:29.5476454Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `bottle'
2022-05-11T22:06:29.5476979Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

cc @danielnachun

**Comment by iMichka** [comment]
Weird. I re-ran the job and the bottling error disappeared. I could also not reproduce it locally ...

**Review by danielnachun — DISMISSED** [review]
Let's get this bottled so we can work on building `binutils` and `portable-ruby` against this and get rid of the Wheezy image.

**Comment by SMillerDev** [comment]
Okay, first it was autosquash now it's a pending workflow. Someone else can merge this

**Review by SMillerDev — DISMISSED** [review]

**Pull request closed without merging**
