### PR TITLE
Compcert 3.0.1

### PR DESCRIPTION
**Pull request by beurdouche**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
The current version of `coq` in homebrew/core is 8.6, so the OPAM stuff can be removed in favor of `depends_on "coq" => :build`

**Comment by beurdouche** [comment]
I was thinking that this would prevent problems in case of breaking changes from a Coq update as Compcert is really tied with a specific version of Coq. That said, I don't expect real breaking changes. @ilovezfs WDYT ?

**Comment by ilovezfs** [comment]
Yup, good thought. Unfortunately, that will always be the case, so it's a dance we'll keep doing each time they're out of sync. But when the stars are aligned we might as well speed up the build for everyone by using the botted dependency.

**Comment by beurdouche** [comment]
Ok, I'll let the build finish because I am curious and update the formula using brew dependencies soon ;)

**Comment by ilovezfs** [comment]
Just shout if you need any help.

**Comment by ilovezfs** [comment]
Failed because it needs a newer Menhir. So: https://github.com/Homebrew/homebrew-core/pull/11430.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/11430 shipped.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Why do we not compile as 64-bit by default (when possible)?

**Comment by ilovezfs** [comment]
@fxcoudert see https://github.com/Homebrew/homebrew-core/pull/9875

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by ilovezfs** [comment]
@beurdouche it looks like we got our wires crossed here. I'll handle changing it to `depends_on "coq" => :build`, so no worries.

**Pull request closed without merging**
