### PR TITLE
gdb: Added option for automatic code signing

### PR DESCRIPTION
**Pull request by ronmrdechai**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Added automatic code signing for GDB. I'm not really sure this should be here, as it makes the installation process interactive (`codesign` requires a password in order to run). It is rather convenient though, and I've seen this pattern in the `radare2` formula as well.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 any thoughts here?

**Comment by DomT4** [comment]
No major objection, although I'm curious about:
> as it makes the installation process interactive (codesign requires a password in order to run).

How is this different to `llvm`, which IIRC never required a password apart from as part of the initial setup in the Keychain application, obviously? Or at least, didn't used to require a password to build even when building `--with-lldb`?

**Comment by ronmrdechai** [comment]
That's odd, I just compared my formula with `llvm`, the check is identical but mine requires a password and `llvm` does not. Maybe it has to do with my certificate being in the `System` Keychain? The dialog states that's what it trying to be accessed.

**Comment by DomT4** [comment]
Ah, yes, part of the LLVM instructions suggest moving it over to the `login` keychain, I believe?

**Comment by ronmrdechai** [comment]
Tried changing the requirement to look more like `llvm`'s but I messed up in the process. How do I get out of this mess?

Moving the identity to `login` keychain seems to fix everything by the way.

**Comment by DomT4** [comment]
> Moving the identity to login keychain seems to fix everything by the way.

Yeah. We should probably ask `gdb` to adopt that advice unless they have a reason not to. Interactivity for any reason in Homebrew beyond initial setup is generally unexpected & breaking that expectation seems potentially unwise.

> How do I get out of this mess? Should I just delete the fork and recreate the pull request?

You just messed up the rebase. There are a whole bunch of ways to fix it, I believe, although I've not borked a rebase quite so severely in some time & have kinda forgotten how 😅. You could try something like `git fetch --force && git rebase master`.

**Comment by ronmrdechai** [comment]
> You just messed up the rebase. There are a whole bunch of ways to fix it, I believe, although I've not borked a rebase quite so severely in some time & have kinda forgotten how 😅. You could try something like `git fetch --force && git rebase master`.
Doesn't work at all, it just says master is up to date. I think I'll just open a new PR.

**Pull request closed without merging**
