### PR TITLE
bde 3.59.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> python ./bin/waf configure --prefix=/usr/local/Cellar/bde/3.59.0.1
python: can't open file './bin/waf': [Errno 2] No such file or directory
```

**Review by Rylan12 — COMMENTED** [review]
Should the `bde-tools` resource be updated as well?

```ruby
  resource "bde-tools" do
    url "https://github.com/bloomberg/bde-tools/archive/v1.1.tar.gz"
    sha256 "c5d77d5e811e79f824816ee06dbf92a2a7e3eb0b6d9f27088bcac8c06d930fd5"
  end
```

It's on version [3.59.0.0](https://github.com/bloomberg/bde-tools/releases/tag/3.59.0.0) but it doesn't look like the resource has been updated since 1.1. Is that intentional or an oversight?

**Comment by chenrui333** [comment]
> Should the `bde-tools` resource be updated as well?
> 
> ```ruby
>   resource "bde-tools" do
>     url "https://github.com/bloomberg/bde-tools/archive/v1.1.tar.gz"
>     sha256 "c5d77d5e811e79f824816ee06dbf92a2a7e3eb0b6d9f27088bcac8c06d930fd5"
>   end
> ```
> 
> It's on version [3.59.0.0](https://github.com/bloomberg/bde-tools/releases/tag/3.59.0.0) but it doesn't look like the resource has been updated since 1.1. Is that intentional or an oversight?

I did the bump in this commit 0c8b5b0, but the build has some issue, for now, I will just let it go (will file an upstream report on this).

The details are listed in https://github.com/bloomberg/bde-tools/tree/master/bin

I did check the past upgrades though, the bde-tools seems always out of sync with the bde versions.

**Comment by Rylan12** [comment]
I think that's fine 👍

**Review by Rylan12 — APPROVED** [review]

**Pull request closed without merging**
