### PR TITLE
jhiccup 2.0.8

### PR DESCRIPTION
**Pull request by queengooborg**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Supersedes #22616 -- upgrade jHiccup to version 2.0.8 (and include a test).

-----

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Strange, this built fine on my local machine...  Looking into it now!

**Comment by ilovezfs** [comment]
maybe just
```
    assert_match "CSV", shell_output("#{bin}/jHiccup -h", 255)
```

**Comment by vinyldarkscratch** [comment]
Ah, much better looking!

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks again @vinyldarkscratch!

**Comment by vinyldarkscratch** [comment]
Always a pleasure!  😄

**Pull request merged**
