### PR TITLE
LANraragi 0.6.6 (new formula)

### PR DESCRIPTION
**Pull request by Bl4Cc4t**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?

I have no test available. I don’t really think you can test this kind of application, but ofc I’m open for good ideas :)

- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

It showed me this message at the first run, but I guess that’s irrelevant.
```text
HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
```
-----

### CODE REVIEW

**Comment by Difegue** [comment]
(Disclaimer: I'm the lead developer on [LANraragi](https://github.com/Difegue/LANraragi).)  

For `brew test`, I think you could hook it up easily to the app's existing test suite, which is ran through `npm test`.  
You need the redis server to be running for this, but if the tests are done post-install this should be doable.

**Comment by Bl4Cc4t** [comment]
> Dependency 'libarchive' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.

We definitely need a brewed `libarchive`, since `include/archive.h` is needed.

As for the test, I have trouble starting `redis-server` simultaneously with the `npm test` command.

Here’s what I got so far:
```ruby
test do
    system "cp", prefix/"redis.conf", testpath/"redis.conf"
    (testpath/"log").mkpath
    touch testpath/"log/redis.conf"
    inreplace "redis.conf", "<LRR_DATA_DIRECTORY>", testpath
    system "redis-server", "redis.conf", "&", "npm", "test"
  end
```

**Comment by Difegue** [comment]
You might be able to get away without using the config file -- The database isn't really used, some parts of the tests just connect to it.  
(Which is a bit dumb -- I should get around to mocking it in a later release.)

**Comment by Bl4Cc4t** [comment]
The config file is read just fine, that’s not a problem.
I just cannot run two commands simultaneously

**Comment by Difegue** [comment]
Oh, then you should be able to make it three: 
```
redis-server --daemonize yes
npm test
redis-cli stop
```

**Comment by Bl4Cc4t** [comment]
Okay, now I get this error:
```text
Can't open file "./log/plugins.log": Operation not permitted at /usr/local/Cellar/lanraragi/0.6.6/libexec/lib/perl5/Mojo/Log.pm line 17.
```
It seems like Mojo wants to output a log but Homebrew is restricting it from doing so.
I have no idea how to fix that.

**Comment by Difegue** [comment]
You need to create the `log` directory beforehand, as it doesn't do so automatically.  
(This is something I fixed with the recent log refactoring so it won't be necessary in a future release.)

**Comment by Bl4Cc4t** [comment]
But the directory exists…

**Comment by Difegue** [comment]
Well, I guess you can just chmod it, then? Not sure if this is desired/good practice here though.

**Comment by Bl4Cc4t** [comment]
We have to somehow disable the log output to this file (at least for this test). 
```ruby
ENV["MOJO_LOG_LEVEL"] = "fatal"
```
gets ignored. 

Maybe you can add another env var for this behavior?
Since this is a logging related issue, I guess we have to wait for 0.6.7 :)

**Comment by Difegue** [comment]
`MOJO_LOG_LEVEL` might be getting overridden by `prove -v`, which is called by `npm test`. You could try replacing the npm call with `prove -l tests/*.t`, which should do the same thing.

Past that, current nightlies can use `LRR_LOG_DIRECTORY` to redirect log output, you could try something with that.

**Comment by Bl4Cc4t** [comment]
Closing this in favor of the upcoming v0.6.7 which will hopefully work :)
Sorry for the hassle.

**Pull request closed without merging**
