### PR TITLE
get-flash-videos 1.25.92

### PR DESCRIPTION
**Pull request by rakkesh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by rakkesh** [comment]
As discussed in https://github.com/Homebrew/homebrew-core/pull/2651.

**Comment by DomT4** [comment]
Looks like they may have changed the syntax a bit?
```
==> /usr/local/Cellar/get-flash-videos/1.25.92/bin/get_flash_videos http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Using method 'bbc' plugin version 0.01 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
rtmpdump: ERROR: You must specify a hostname (--host) or url (-r "rtmp://host[:port]/playpath") containing a hostname
Download failed, no valid file downloaded
Couldn't download any videos.
Error: get-flash-videos: failed
```

**Comment by rakkesh** [comment]
```
$ get_flash_videos http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Using method 'bbc' plugin version 0.01 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   duration              283.58
INFO:   moovPosition          53109262.00
INFO:   width                 688.00
INFO:   height                384.00
INFO:   videocodecid          avc1
INFO:   audiocodecid          mp4a
INFO:   avcprofile            77.00
INFO:   avclevel              31.00
INFO:   aacaot                2.00
INFO:   videoframerate        25.00
INFO:   audiosamplerate       48000.00
INFO:   audiochannels         1.00
INFO: trackinfo:
INFO:   length                7089000.00
INFO:   timescale             25000.00
INFO:   language              eng
INFO: sampledescription:
INFO:   sampletype            avc1
INFO:   length                13612032.00
INFO:   timescale             48000.00
INFO:   language              eng
INFO: sampledescription:
INFO:   sampletype            mp4a
WARNING: Larger timestamp than 24-bit: 0xffffffbev: 99% (51849.68 / 52267.82 KiB)

Done. Saved 53477629 bytes to BBC_-__Do_whatever_it_takes_to_get_him_to_talk.flv
```

**Comment by rakkesh** [comment]
```
$ brew test get-flash-videos
Testing get-flash-videos
==> Using the sandbox
==> /usr/local/Cellar/get-flash-videos/1.25.92/bin/get_flash_videos http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
```

**Comment by ilovezfs** [comment]
same rtmpdump?

**Comment by rakkesh** [comment]
Yes, `rtmpdump` was last updated in January.
```
$ brew info rtmpdump
rtmpdump: stable 2.4+20151223 (bottled), HEAD
Tool for downloading RTMP streaming media
https://rtmpdump.mplayerhq.hu
Conflicts with: flvstreamer
/usr/local/Cellar/rtmpdump/2.4+20151223 (19 files, 425.8K) *
  Poured from bottle on 2016-01-30 at 21:04:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/rtmpdump.rb
==> Dependencies
Required: openssl ✔
```

**Comment by ilovezfs** [comment]
might be worth trying a site other than bbc

**Comment by ilovezfs** [comment]
@rakkesh looks like the problem went away

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
The test should probably use `assert File.exist?` not just `File.exist?`

**Comment by MikeMcQuaid** [comment]
@ilovezfs The boolean return value of the argument is fine but it'd be good to add an assertion message as otherwise a boolean error will be kinda unclear 👍

**Comment by rakkesh** [comment]
@ilovezfs updated the test with `assert`.

**Comment by ilovezfs** [comment]
@rakkesh What Mike means is doing something like
```
file = "BBC_-__Do_whatever_it_takes_to_get_him_to_talk.flv"
assert File.exist?(file), "Failed to download #{file}!"
```

**Comment by rakkesh** [comment]
I have used the code from here, https://github.com/Homebrew/homebrew-core/blob/e40dc2e709ff5409c672e31c8f89ad31a3e9712e/Formula/abcm2ps.rb#L44; but yes, I'll update to something similar to this - 

```rb
assert File.exists?(file), true
```

**Comment by ilovezfs** [comment]
There are plenty of formulae you can point to that need improvements. We try to address them as we go along because it's often not feasible to do them all at once. The models for how this one should be are


https://github.com/Homebrew/homebrew-core/blob/master/Formula/daemonize.rb#L31
https://github.com/Homebrew/homebrew-core/blob/master/Formula/daemonize.rb#L33
https://github.com/Homebrew/homebrew-core/blob/master/Formula/govendor.rb#L36
https://github.com/Homebrew/homebrew-core/blob/master/Formula/kobalt.rb#L42
https://github.com/Homebrew/homebrew-core/blob/master/Formula/lcm.rb#L62
https://github.com/Homebrew/homebrew-core/blob/master/Formula/lcm.rb#L63
https://github.com/Homebrew/homebrew-core/blob/master/Formula/lcm.rb#L65
https://github.com/Homebrew/homebrew-core/blob/master/Formula/lcm.rb#L68
https://github.com/Homebrew/homebrew-core/blob/master/Formula/libressl.rb#L75
https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb#L161
https://github.com/Homebrew/homebrew-core/blob/master/Formula/tippecanoe.rb#L24
https://github.com/Homebrew/homebrew-core/blob/master/Formula/yadm.rb#L16

**Comment by rakkesh** [comment]
@ilovezfs my bad 🙃; i wasn't thinking clearly when I had made that commit, and then the comment. 😅
Updated the commit now.

**Comment by ilovezfs** [comment]
@rakkesh Thanks!!

**Comment by ilovezfs** [comment]
:+1:

CC @DomT4

**Comment by DomT4** [comment]
Seems reasonable 👍

**Comment by ilovezfs** [comment]
@rakkesh Thanks for taking this on! Great work :100:

**Pull request closed without merging**
