### PR TITLE
cdparanoia: use brewed curl for URLs

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
For #88329

### CODE REVIEW

**Comment by EricFromCanada** [comment]
on Linux:
```
==> brew linkage --test cdparanoia
==> FAILED
Missing libraries:
  unexpected (libcdda_interface.so.0)
  unexpected (libcdda_paranoia.so.0)

==> brew install --only-dependencies --include-test cdparanoia
==> brew test --verbose cdparanoia
==> FAILED
==> Testing cdparanoia
==> /home/linuxbrew/.linuxbrew/Cellar/cdparanoia/10.2/bin/cdparanoia --version
/home/linuxbrew/.linuxbrew/Cellar/cdparanoia/10.2/bin/cdparanoia: error while loading shared libraries: libcdda_interface.so.0: cannot open shared object file: No such file or directory
Error: cdparanoia: failed
```

**Comment by carlocab** [comment]
```ruby
ENV.append "LDFLAGS", "-Wl,-rpath,#{libexec}" if OS.linux?
```
Or you can install the libraries into `lib` rather than `libexec` on Linux.

**Review by carlocab — DISMISSED** [review]
There is no Linux bottle, so the failure is not blocking.

**Comment by EricFromCanada** [comment]
The added line fixes linkage in the `cdparanoia` binary, but not for one of its libs:
```
$ brew linkage cdparanoia
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/librt.so.1
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/Cellar/cdparanoia/10.2/libexec/libcdda_interface.so.0 (cdparanoia)
  /home/linuxbrew/.linuxbrew/Cellar/cdparanoia/10.2/libexec/libcdda_paranoia.so.0 (cdparanoia)
Missing libraries:
  libcdda_interface.so.0
$ ldd /home/linuxbrew/.linuxbrew/Cellar/cdparanoia/10.2/libexec/libcdda_paranoia.so.0
	linux-vdso.so.1 (0x00007ffe742c6000)
	libcdda_interface.so.0 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2adef20000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2adf125000)
```

**Review by carlocab — APPROVED** [review]

**Pull request merged**
