### PR TITLE
smlnj 110.80

### PR DESCRIPTION
**Pull request by rprimus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Upstream updated.  110.79 skipped as would not build on Mavericks

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Failing on Yosemite now 😭 : https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6686/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_smlnj/

Requeued in case a one-off.

**Comment by rprimus** [comment]
Tue Aug 23 15:12:57 BST 2016

I'm at a loss here.  Build now failing on ```yosemite``` due to missing heap image ```run.x86-darwin```,  however this cooers to have been successfully built:

```
cc -m32 -std=c99 -o run.x86-darwin -g -O2 -D_DARWIN_C_SOURCE -mmacosx-version-min=10.6  main.o c-libraries.o unix-raise-syserr.o ml-options.o boot.o load-ml.o run-ml.o globals.o ml-state.o error.o timers.o unix-timers.o qualify-name.o swap-bytes.o unix-fault.o signal-util.o unix-signal.o unix-prof.o prim.o   ../c-libs/posix-os/libposix-os.a ../c-libs/smlnj-runtime/libsmlnj-runt.a ../c-libs/smlnj-signals/libsmlnj-sig.a ../c-libs/smlnj-prof/libsmlnj-prof.a ../c-libs/smlnj-sockets/libsmlnj-sock.a ../c-libs/smlnj-time/libsmlnj-time.a ../c-libs/smlnj-date/libsmlnj-date.a ../c-libs/smlnj-math/libsmlnj-math.a ../c-libs/posix-process/libposix-process.a ../c-libs/posix-procenv/libposix-procenv.a ../c-libs/posix-filesys/libposix-filesys.a ../c-libs/posix-io/libposix-io.a ../c-libs/posix-sysdb/libposix-sysdb.a ../c-libs/posix-signal/libposix-signal.a ../c-libs/posix-tty/libposix-tty.a ../c-libs/posix-error/libposix-error.a ../gc/libgc.a ../memory/libmem.a ../c-libs/dl/libunix-dynload.a -ldl -lm
```

[Log](https://gist.github.com/rprimus/af332c652bb99d2ef2d1f65a5934bebd) of my build from this morning.

### Question:
Is all OK with the ```yosemite``` Jenkins build agent?

Comparing:

1. [el_capitan](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=el_capitan/)

2 . [mavericks](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=mavericks/)
3. [yosemite](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=yosemite/)

there seems to be a pattern of builds passing on ```mavericks``` and ```el_capitan``` but failing on ```yosemite```.

**Comment by rprimus** [comment]
On Tue, Aug 23, 2016 at 07:09:26AM -0700, Mike McQuaid wrote:
> Failing on Yosemite now 😭 : https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6686/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_smlnj/
> 
> Requeued in case a one-off.
> 

Tue 23 Aug 2016 15:40:01 BST

Just saw this - was busy drafting my 'comment'.

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: 0x28E92848DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by rprimus** [comment]
Tue 23 Aug 2016 17:14:48 BST

@mikemcquaid Since job 6684 (apart from jobs
6692, 6693) **every** build that has been
successful on {el_capitan, mavericks} has failed
on yosemite.

Can the yosemite build agent be restarted?

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: 0x28E92848DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by rprimus** [comment]
Tue Aug 23 21:36:54 BST 2016

@MikeMcQuaid  A ```vimdiff``` of my log file and the fail yosemite console log showed two failed ```sed``` operations (in the console log):

```
% ag -iw sed consoleText-yosemite.txt
11305:sed: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/unistd.h: No such file or directory
11367:sed: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/unistd.h: No such file or directory
```

Searching for ```Xcode```:

```
 % ag Xcode consoleText-yosemite.txt
11305:sed: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/unistd.h: No such file or directory
11367:sed: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/unistd.h: No such file or directory
11717:Git: 2.5.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
11723:Xcode: 7.2.1
11729:SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
```

### Question:

Shouldn't the ```SDKROOT``` on ```yosemite``` be ```MacOSX10.10.sdk```?

[link](https://forums.developer.apple.com/thread/17334)

**Comment by DomT4** [comment]
There is no `MacOSX10.10.sdk` with Xcode 7. Apple introduced universal SDKs, which are pretty frequently the bane of our lives.

You may want to try `ENV.delete("SDKROOT")` at the top of `def install`.

**Comment by rprimus** [comment]
Wed Aug 24 07:47:17 BST 2016

@DomT4 With your advice,  builds on ```el_capitan```.

Here is the code that sets up the ```sed```:

```
  # newer versions of the Mac OS X developer tools keep the include files inside the Xcode
  # application bundle, so we add that as a possible path.
  *x86-darwin*)
    case `uname -r` in
      13.*) SDK=MacOSX10.9.sdk ;;
      14.*) SDK=MacOSX10.10.sdk ;;
      15.*) SDK=MacOSX10.11.sdk ;;
      16.*) SDK=MacOSX10.12.sdk ;;
      *) SDK=none ;;
    esac
    if test x$SDK != xnone ; then
      # note: at some point, we might use "xcrun --show-sdk-path", but that only works
      # with Xcode 5.x+
      XCODE_DEV_PATH=`xcode-select --print-path`
      INCLFILE=$XCODE_DEV_PATH/Platforms/MacOSX.platform/Developer/SDKs/$SDK/usr/include/unistd.h
    fi
    ;;
```

### Question:

Does the ```yosemite``` build agent include  ```MacOSX10.10.sdk```?

**Comment by MikeMcQuaid** [comment]
> Does the yosemite build agent include MacOSX10.10.sdk?

Not any more, no. This is a bad assumption, unfortunately.

**Comment by rprimus** [comment]
Wed Aug 24 09:59:25 BST 2016

@MikeMcQuaid @DomT4 

Have:

1. sent an [email](https://groups.google.com/d/msg/homebrew-discuss/DULMlLQhJR8/EuIEj7AYBwAJ) to ```smlj-dev-list``` 
2. made a request on IRC re: ```/usr/include/unistd.h```

**Comment by rprimus** [comment]
Wed Aug 24 11:13:44 BST 2016

```Xcode 7``` provides support for ```OS X 10.10.4``` (```Yosemite```) and above.

> > Does the yosemite build agent include MacOSX10.10.sdk?

> Not any more, no. This is a bad assumption, unfortunately.

For completeness,  shouldn't ```SDK 10.10``` be included on a ```Yosemite``` instance to cater for 
versions <= ```OS X 10.10.3```?

I refer to [link](https://forums.developer.apple.com/thread/17334) again (where someone experienced similar problems).

**Comment by MikeMcQuaid** [comment]
> For completeness, shouldn't SDK 10.10 be included on a Yosemite instance to cater for 
> versions <= OS X 10.10.3?

Yes I agree but that's something you'll need to convince Apple rather than us (they control SDK inclusion) 😉

**Comment by rprimus** [comment]
Wed Aug 24 16:23:11 BST 2016

@MikeMcQuaid 

With help from @qu1j0t3 on IRC, (I believe) I'm all clear now on Xcode and SDKs (back to 10.4).

Earlier,  Prof. John Reppy responded to the email and has made a change to ```gen-posix-names.sh``` to check for ```/usr/include/unistd.h``` first.

This should alleviate the problem.  I've asked him to let me know when he's pushed the changes
and will submit the PR then.

**Comment by rprimus** [comment]
Fri Aug 26 17:46:06 BST 2016

@MikeMcQuaid @DomT4 

No idea what's caused this:

```
FATAL: Could not checkout 00d1d4fe0079f068d614187c53c7e84793d9b49a
```

**Comment by DomT4** [comment]
Jenkins bug, that apparently will never be fixed. Re-queued the build.

**Comment by rprimus** [comment]
Fri Aug 26 17:56:59 BST 2016

/me dances a jig!

Thanks for all the help @MikeMcQuaid @DomT4 and @qu1j0t3 .

Next up - lfe.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/b210b741ccaa40f39733385ab03dc039c7ab0c54. Thank you for your contribution to Homebrew @rprimus; we appreciate it! :smiley_cat:

**Pull request closed without merging**
