### PR TITLE
git-delta 0.0.16

### PR DESCRIPTION
**Pull request by dandavison**
Created with

```
brew bump-formula-pr --url https://github.com/dandavison/delta/archive/0.0.16.tar.gz git-delta
```

### CODE REVIEW

**Comment by chenrui333** [comment]
==> brew test git-delta --verbose
==> FAILED
Testing git-delta
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200207-28004-78ysrd.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-delta.rb --verbose
Error: git-delta: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </delta\ 0\.0\.16/> was expected to be =~
<"delta 0.0.15">.

**Comment by dandavison** [comment]
```ruby
assert_match "delta #{version}", `#{bin}/delta --version`.chomp
```
```
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </delta\ 0\.0\.16/> was expected to be =~
<"delta 0.0.15">.
```

Can someone tell me why `#{version}` is resolving to the old version 0.0.15? I'm not sure where the string "0.0.15" is coming from. cc @dawidd6 if you wouldn't mind explaining to me.

(I can reproduce the failure locally with `brew test`).

**Comment by dandavison** [comment]
Oh I see, the `.tgz` has the wrong version. Will fix.

**Comment by dandavison** [comment]
I believe this is fixed now. The Jenkins build passes and the following passes locally:

```bash
    cd $(brew --repo homebrew/homebrew-core) && \
    brew uninstall --force git-delta && \
    brew install --build-from-source git-delta && \
    brew test git-delta && \
    brew uninstall --force git-delta && \
    brew install git-delta && \
    brew audit --strict git-delta
```

**Comment by chenrui333** [comment]
Thanks @dandavison!!

**Comment by dandavison** [comment]
@chenrui333 Thank you for keeping the internet working.

**Pull request closed without merging**
