### PR TITLE
augustus 3.3.1

### PR DESCRIPTION
**Pull request by suujia**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
https://github.com/Homebrew/homebrew-core/pull/27886#issuecomment-399272907

### CODE REVIEW

**Comment by ilovezfs** [comment]
@suujia @sjackman should this be reported upstream? Presumably not running `make` from the correct directory isn't a Homebrew specific issue.

**Comment by sjackman** [comment]
It's not a matter of being built in the wrong directory. This auxiliary feature `bam2wig` requires an ancient legacy version of samtools 0.1.x. `auxprogs/bam2wig/` is not built by default in Augustus 3.3, but in Augustus 3.3.1 it is built by default. We could consider vendoring samtools 0.1.x into `augustus`. I'd recommend not building `auxprogs/bam2wig/`. I do not believe it's core functionality of Augustus. We can reconsider this later if someone were to claim they needed this functionality.

**Comment by sjackman** [comment]
This PR disables building `auxprogs/bam2wig/`.

**Comment by ilovezfs** [comment]
Ah OK.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @suujia! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
