### PR TITLE
fix sha256 in xplanetfx

### PR DESCRIPTION
**Pull request by blogabe**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by neutric** [comment]
@blogabe Before we can proceed, we'll need to know why the file has changed. Is upstream aware of this issue? If not, would you be so kind and let them know about the checksum change and then report back to us? See [this](https://github.com/Homebrew/homebrew-core/pull/9778) for an example of what we are looking for.

**Comment by blogabe** [comment]
I don't think it was working for some time.  Running `brew audit --strict` on the formula before fixing it didn't identify any errors.  It wasn't until I tried installing it that the alert came up.  My point is, I don't know if it's an upstream issue or if the formula had the wrong sha since the last update maybe 4 months ago.

**Comment by neutric** [comment]
`sha256` was [changed](https://github.com/Homebrew/homebrew-core/commit/e4137bb511da38085b63b6af1ccd356c6c1bece8) during the version bump to 2.6.12 and bottles were built successfully, so what we have now was the correct checksum at some point. Upstream uses a comment form as "bug reporting facility". Would you mind asking real quick whether they are aware of the checksum change and why it changed?

**Comment by blogabe** [comment]
From upstream: "I set up a new key for verification cause newer Ubuntu and derivates were complaining about the old one."

**Comment by neutric** [comment]
[Link to upstream's response](http://mein-neues-blog.de/xplanetFX/#comment-1746) for good record keeping. 🗃 

I guess a version bump by upstream would have communicated this change better, as @ilovezfs [said recently](https://github.com/Homebrew/homebrew-core/pull/10842#issuecomment-285658549), but what are you gonna do. Thanks for getting clarification, @blogabe!

**Pull request merged**
