### PR TITLE
i386-elf-binutils, i386-elf-gcc: add 64-bit support

### PR DESCRIPTION
**Pull request by MRNIU**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by fxcoudert — CHANGES_REQUESTED** [review]
- Can you please extend the `i386-elf-gcc` test to include a 64-bit case?
- One commit per formula, with commit message: `i386-elf-binutils: add 64-bit support` (same for gcc)

**Comment by MRNIU** [comment]
Hi, I have a problem, when I test i386-elf-gcc with the following configure:
```
system "../configure", "--target=i386-elf",
                             "--enable-targets=all",
                             "--prefix=#{prefix}",
                             "--without-isl",
                             "--enable-multilib",
                             "--disable-werror",
                             "--without-headers",
                             "--with-as=#{Formula["i386-elf-binutils"].bin}/i386-elf-as",
                             "--with-ld=#{Formula["i386-elf-binutils"].bin}/i386-elf-ld",
                             "--enable-languages=c,c++"
```
the error is:
```
> i386-elf-gcc tmp.c -c -m64
> cc1: 对不起，尚未实现：未编译入对 64 位模式的支持
```
which means not support 64bits.
I am not sure if I have some mistake, but to tell the truth, I succeeded under target x86_64.
Do you have any suggestions?

**Comment by fxcoudert** [comment]
Yes the target should be `x86_64-elf`, I think.

**Comment by MRNIU** [comment]
@fxcoudert 
So there's a new question, if we use target `x86_64-elf`, and we are going to get something like `x86_64-elf-ld`, `x86_64-elf-as`, instead of `i386-elf-xxx`
Is that allowed?

**Comment by fxcoudert** [comment]
Yes that's fine. We can rename the formulas into `x86_64-elf-*`, and add aliases to their previous names.

**Comment by MRNIU** [comment]
@fxcoudert 
So should I create a new pr named `x86_64-elf-binutils` and `x86_64-elf-gcc`?

**Comment by fxcoudert** [comment]
No, rename and add alias in this PR.

**Comment by MRNIU** [comment]
@fxcoudert 
I think I might have finished, thank you.

**Comment by fxcoudert** [comment]
Not sure why, but there is a conflict :(

**Comment by MRNIU** [comment]
I am sorry for that...if I can do anything, just tell me

**Comment by fxcoudert** [comment]
@MRNIU you need to rebase so the conflict is resolved

**Comment by MRNIU** [comment]
@fxcoudert
It's finally done.

**Comment by MRNIU** [comment]
The lesson: don't count your chickens before they hatch

**Comment by fxcoudert** [comment]
This is looking good!

**Comment by fxcoudert** [comment]
```
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/i386-elf-gcc
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/i386-elf-binutils
```

Don't know why this is happening :(

**Comment by MRNIU** [comment]
@fxcoudert
I have [raised this issue in the forum](https://discourse.brew.sh/t/error-non-file-alias-encountered-with-add-an-alias/6528), do you have any thought?

**Comment by MRNIU** [comment]
@fxcoudert

**Comment by fxcoudert** [comment]
Thank you @MRNIU ! Merging

**Pull request closed without merging**
