### PR TITLE
silicon 0.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
error[E0308]: mismatched types
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:75:12
   |
75 |         if ok {
   |            ^^ expected `bool`, found `i8`

error[E0308]: mismatched types
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:82:59
   |
82 |             NSData::writeToFile_atomically_(object, path, false);
   |                                                           ^^^^^ expected `i8`, found `bool`

error: aborting due to 2 previous errors
```

**Comment by carlocab** [comment]
Let's try this with Rust 1.50. Also, let's see if this will build on ARM: https://github.com/Aloxaf/silicon/issues/156

**Review by carlocab — DISMISSED** [review]
🤞

**Comment by Moisan** [comment]
Upstream issue is still unresolved: https://github.com/Aloxaf/silicon/issues/158

**Comment by chenrui333** [comment]
```
error[E0308]: mismatched types
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:75:12
   |
75 |         if ok {
   |            ^^ expected `bool`, found `i8`

error[E0308]: mismatched types
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:82:59
   |
82 |             NSData::writeToFile_atomically_(object, path, false);
   |                                                           ^^^^^ expected `i8`, found `bool`

error: aborting due to 2 previous errors

```

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
