### PR TITLE
go 1.20.6

### PR DESCRIPTION
**Pull request by stefanb**
Security bugfix release, see https://groups.google.com/g/golang-announce/c/2q13H6LEEx0

Related PRs:
* previous 1.20 version bump #132982 
* 1.19.x bump: #136350

----

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by stefanb** [comment]
@carlocab actually it might make sense to rebuild dependants. Because Go programs are statically linked all the bugs in Go programs will remain baked into the binaries unless they are rebuilt with the latest Go.

**Comment by p-linnane** [comment]
> @carlocab actually it might make sense to rebuild dependants. Because Go programs are statically linked all the bugs in Go programs will remain baked into the binaries unless they are rebuilt with the latest Go.

We generally only do this for major version bumps. As the individual formulae are updated after this is merged they will be built with 1.20.6.

**Comment by stefanb** [comment]
> > @carlocab actually it might make sense to rebuild dependants. Because Go programs are statically linked all the bugs in Go programs will remain baked into the binaries unless they are rebuilt with the latest Go.
> 
> We generally only do this for major version bumps. As the individual formulae are updated after this is merged they will be built with 1.20.6.

Yeah, i am aware of this, but it might not be the best practice.

**Comment by p-linnane** [comment]
There are almost 850 formulae that directly depend on `go.` It's quite taxing on our limited CI resources and maintainer time to rebuild every dependent for every `go` version bump. It just isn't feasible, which is why we limit it to major versions only.

**Comment by p-linnane** [comment]
Please format your commit messages with the formula name first, followed by a colon and then the changes you're making. Otherwise our autosquash workflow will have to deploy a replacement PR to fix the formatting. Someting like `garble: revision bump (go 1.20.6)` would be perfect. Thanks.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
