### PR TITLE
amdatu-bootstrap: Update link

### PR DESCRIPTION
**Pull request by queengooborg**
The user managing this repository on BitBucket changed their username.  This should fix it right up!

_OLD DESCRIPTION: These are updates to fix some of the broken links as listed in #22653.  I have not gotten the chance to test these out with a `brew install` and `brew audit` -- I'm in the middle of an update of my formulas -- but will make changes as needed and as specified by the Brew Test Bot!_

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks @vinyldarkscratch! Note that checksum changes must be reported to and confirmed by upstream before we update them to rule out malicious circumstances. So those should be in individual PRs so they don't block the rest.

**Comment by vinyldarkscratch** [comment]
That makes complete sense!  I shall cherrypick those commits now.  🙂

**Comment by ilovezfs** [comment]
for cadaver we can use a mirror. there are a few if you google the tarball name

**Comment by ilovezfs** [comment]
The ones for formula version upgrades should also be in separate PRs since they'll need new bottles pulled whereas the ones where we're just updating the URL won't.

**Comment by vinyldarkscratch** [comment]
Alrighty, allow me to cherrypick the rest of the changes (probably should have done that already, #LazyDev) -- standby, and thank you!

**Comment by ilovezfs** [comment]
hehe no worries. We really appreciate the help with these.

**Review by ilovezfs — APPROVED** [review]

**Comment by vinyldarkscratch** [comment]
The Brew Test Bot is reporting (on a few of my PRs):
```
01:09:38 Homebrew Core Pull Requests » sierra completed with result FAILURE
01:09:38 Homebrew Core Pull Requests » el_capitan completed with result FAILURE
01:12:55 Homebrew Core Pull Requests » high_sierra completed with result FAILURE
```

I feel a little embarrassed for asking, but is there a way to request the test bot to re-test something?

**Comment by ilovezfs** [comment]
That looks like a Java 9 failure.

**Comment by ilovezfs** [comment]
```
diff --git a/Formula/amdatu-bootstrap.rb b/Formula/amdatu-bootstrap.rb
index 9c0e479..a2538e3 100644
--- a/Formula/amdatu-bootstrap.rb
+++ b/Formula/amdatu-bootstrap.rb
@@ -6,9 +6,11 @@ class AmdatuBootstrap < Formula
 
   bottle :unneeded
 
+  depends_on :java => "1.8"
+
   def install
     libexec.install %w[amdatu-bootstrap bootstrap.jar conf]
-    bin.install_symlink "#{libexec}/amdatu-bootstrap" => "amdatu-bootstrap"
+    (bin/"amdatu-bootstrap").write_env_script libexec/"amdatu-bootstrap", Language::Java.java_home_env("1.8")
   end
 
   test do
```

**Comment by vinyldarkscratch** [comment]
Oh I'm stupid, I was looking at the wrong part -- I was looking at the Console Output (like on Travis CI), not the Test Results.  Durr!  🤦‍♀️

**Comment by ilovezfs** [comment]
Thanks @vinyldarkscratch! 👢

**Pull request merged**
