### PR TITLE
python and python@2: remove

### PR DESCRIPTION
**Pull request by fxcoudert**
In order to prepare for the upcoming release of Python 4, and avoid the migration pains that have plagued us in the move from Python 2 to Python3, it has been decided to preemptively remove the Python 2  and Python 3 formulas from Homebrew core.

All dependent formulas are logically removed. Optionals will have to be taken care of, hence this is currently a work in progress.

We estimate that this new change is compatible with [PEP 394](https://www.python.org/dev/peps/pep-0394/).

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]
Only logical, great to see homebrew taking a head start

**Review by ilovezfs — APPROVED** [review]

**Review by reitermarkus — APPROVED** [review]
About time to remove all of this legacy software. 👍

**Review by pradyunsg — APPROVED** [review]
Sounds like a good idea. :)

**Comment by resistor4u** [comment]
april fools, right?

**Comment by ilovezfs** [comment]
>Unix-like software distributions (including systems like Mac OS X and Cygwin) should install the python2 command into the default path whenever a version of the Python 2 interpreter is installed, and the same for python3 and the Python 3 interpreter.

Since macOS does not ship its own `python2` command, removing Homebrew's Python would lead to further unacceptable violations of PEP 394, unfortunately.

**Comment by fxcoudert** [comment]
@ilovezfs this is a sad, but fair decision. I will open a radar on Apple's bug reporter system in order for them to remove Python 2 from macOS, before petition for reopening this pull request.

**Pull request closed without merging**
