### PR TITLE
boost 1.67.0

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
`boost-build` doesn't have a `1.67.0` tag yet. https://github.com/boostorg/build/releases

### CODE REVIEW

**Comment by jbeich** [comment]
- `uhd` (used by `gnuradio`) maybe broken due to type confusion: https://github.com/EttusResearch/uhd/pull/170

**Comment by ilovezfs** [comment]
I think we can just ignore boost-build for now. I've filed an issue. https://github.com/boostorg/build/issues/298

**Comment by commitay** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
boost-build “latest release” on their [website](https://www.boost.org/build/) clearly points to 2014.10

**Comment by henryiii** [comment]
It looks like 1.67 is now tagged. :)

**Comment by ilovezfs** [comment]
@fxcoudert feel free to report that upstream.

**Comment by ilovezfs** [comment]
osquery failure is preexisting https://github.com/facebook/osquery/issues/4283

**Comment by ilovezfs** [comment]
Shipped!

**Comment by ilovezfs** [comment]
Remaining revision bumps here:

- [ ] [gr-osmosdr](https://github.com/Homebrew/homebrew-core/pull/26727)
- [ ] [lgogdownloader](https://github.com/Homebrew/homebrew-core/pull/26728)
- [ ] [osquery](https://github.com/Homebrew/homebrew-core/pull/26729)

And upscaledb homepage issue reported here: https://github.com/cruppstahl/upscaledb/issues/112

**Pull request closed without merging**
