### PR TITLE
docker-gen 0.7.4

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

build from source

CC @DomT4 :roll_eyes:

### CODE REVIEW

**Comment by DomT4** [comment]
Yikes. How did we all miss this absolute delight.

**Comment by ilovezfs** [comment]
Well, https://github.com/Homebrew/legacy-homebrew/pull/49321 isn't too surprising to me.

But https://github.com/Homebrew/homebrew-core/commit/e681a01378c763f91266f980654cc9499d125ad2 is.

**Comment by DomT4** [comment]
Yeah I glanced through the commit history. I’m hoping/presuming that it was the case that I went looking for anything that just said bin.install with no compile step & flipped them to being unbottled without too much examination 🙈.

**Comment by ilovezfs** [comment]
@DomT4 it looks like we also have an app-engine-go-64 and app-engine-go-32 problem:
```
iMac-TMP:~ joe$ find /usr/local/Cellar/app-engine-go-64/1.9.61 -exec file "{}" \;|grep Mach-O 
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/go-app-stager: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/bin/cover: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/bin/go-app-builder: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/bin/goapp: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/bin/godoc: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/bin/gofmt: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/pkg/tool/darwin_amd64/asm: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/pkg/tool/darwin_amd64/cgo: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/pkg/tool/darwin_amd64/compile: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/pkg/tool/darwin_amd64/cover: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/pkg/tool/darwin_amd64/link: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/debug/dwarf/testdata/typedef.macho: Mach-O 64-bit object x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/debug/macho/testdata/fat-gcc-386-amd64-darwin-exec: Mach-O universal binary with 2 architectures
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/debug/macho/testdata/fat-gcc-386-amd64-darwin-exec (for architecture i386):	Mach-O executable i386
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/debug/macho/testdata/fat-gcc-386-amd64-darwin-exec (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/debug/macho/testdata/gcc-386-darwin-exec: Mach-O executable i386
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/debug/macho/testdata/gcc-amd64-darwin-exec: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/debug/macho/testdata/gcc-amd64-darwin-exec-debug: Mach-O 64-bit dSYM companion file x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.6/src/runtime/race/race_darwin_amd64.syso: Mach-O 64-bit object x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/bin/cover: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/bin/go-app-builder: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/bin/goapp: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/bin/godoc: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/bin/gofmt: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/pkg/tool/darwin_amd64/asm: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/pkg/tool/darwin_amd64/cgo: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/pkg/tool/darwin_amd64/compile: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/pkg/tool/darwin_amd64/cover: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/pkg/tool/darwin_amd64/link: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/debug/dwarf/testdata/typedef.macho: Mach-O 64-bit object x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/debug/macho/testdata/fat-gcc-386-amd64-darwin-exec: Mach-O universal binary with 2 architectures
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/debug/macho/testdata/fat-gcc-386-amd64-darwin-exec (for architecture i386):	Mach-O executable i386
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/debug/macho/testdata/fat-gcc-386-amd64-darwin-exec (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/debug/macho/testdata/gcc-386-darwin-exec: Mach-O executable i386
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/debug/macho/testdata/gcc-amd64-darwin-exec: Mach-O 64-bit executable x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/debug/macho/testdata/gcc-amd64-darwin-exec-debug: Mach-O 64-bit dSYM companion file x86_64
/usr/local/Cellar/app-engine-go-64/1.9.61/share/app-engine-go-64/goroot-1.8/src/runtime/race/race_darwin_amd64.syso: Mach-O 64-bit object x86_64
iMac-TMP:~ joe$
```

**Comment by DomT4** [comment]
> problem

If it's just the one problem that's about as good as the `app-engine-go-*` formulae seem to get 🙈.

**Pull request closed without merging**
