### PR TITLE
Upgrade to john-1.9.0-jumbo-1

### PR DESCRIPTION
**Pull request by catap**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
On Sierra and High Sierra, build failure:

```
==> make -s CC=clang
ar: creating archive aes.a
ar: creating archive secp256k1.a
ar: creating archive ed25519-donna.a
Undefined symbols for architecture x86_64:
  "_fmt_stribog_256", referenced from:
      _john_register_all in john.o
  "_fmt_stribog_512", referenced from:
      _john_register_all in john.o
ld: symbol(s) not found for architecture x86_64
```

and on all:

```
configure: WARNING: unrecognized options: --disable-native-macro
```

**Comment by catap** [comment]
@fxcoudert any chances to get from Sierra or High Sierra build folder? Because it is related to new algorithm and without access to this system I have no idea how can I fix it :(

**Comment by catap** [comment]
@fxcoudert I've pushed some ideas that should fix this issue but jenkins ignores my build.

What should I do?

**Comment by equal-l2** [comment]
Relevant PR (closed without merging): https://github.com/Homebrew/homebrew-core/pull/39873

**Comment by fxcoudert** [comment]
Hello @catap, some quick feedback:
- regarding `-mno-sse4.1`, the compiler will not force if its CPU does not support it. The fact that this is needed probably means there is a bug in `configure`, which should detect that there is no SSE4
- since we distribute binaries built on a machine that may have better hardware than some of our users, the correct check is `unless MacOS.version.requires_sse42?`
- is OpenMP strictly necessary? Including GCC as a dependency is very heavy…

**Comment by catap** [comment]
@fxcoudert I'm debugging it :)

Honestly I thought the same about `-mno-sse4.1` but as I show at https://github.com/magnumripper/JohnTheRipper/issues/4077 we have very wired case here:

`clang` exports define that SSE4.1 exists
```
==> clang -dM -E test.c
...
#define __SSE2_MATH__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE_MATH__ 1
#define __SSE__ 1
#define __SSP__ 1
#define __SSSE3__ 1
...
```

but at same time it has error: `needs target feature sse4.1` at configure script:
```
configure:11468: clang -o conftest -m64 -g -O2 -I/usr/local/include -I/usr/local/opt/openssl/include   -O0  -I/usr/local/include -I/usr/local/opt/openssl/include -m64  -L/usr/local/lib -L/usr/local/opt/openssl/lib conftest.c  >&5
conftest.c:30:52: error: '__builtin_ia32_roundpd' needs target feature sse4.1
        int main(){__m128d t;*((long long*)&t)=1;t=_mm_round_pd(t,1);if((*(long long*)&t)==88)printf(".");exit(0);}
                                                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/smmintrin.h:323:12: note: expanded from macro '_mm_round_pd'
  (__m128d)__builtin_ia32_roundpd((__v2df)(__m128d)(X), (M)); })
           ^
1 error generated.
configure:11468: $? = 1
configure: failed program was:
``` 

and this behaviour brokes build.

I've tried to enabled `gcc` for build, but it has some wired issue and I don't like an idea to move forward.

**Comment by catap** [comment]
@fxcoudert I've used the last possibly workaround and I don't like but I haven't got any another ideas.

I've suggest to wait a couple of days to get response from upstream.

**Comment by catap** [comment]
@fxcoudert I've created https://github.com/magnumripper/JohnTheRipper/pull/4100

That is fixed a root cause why we can't use:
```
ENV.append "CFLAGS", "-mno-sse4.1" unless MacOS.version.requires_sse4?
```

So, for me we can move forward with this patch.

**Comment by fxcoudert** [comment]
@catap thanks for everything. I'm merging now, seeing how difficult it was to make it all work.

Could you, however, work on a separate PR to switch the formula to `openssl@1.1`? OpenSSL 1.0 will reach end-of-life on 2019-12-31, and will be removed from Homebrew at that point.

**Comment by catap** [comment]
@fxcoudert let's wait before merge it until some feedback from upstream

**Pull request closed without merging**
