### PR TITLE
xcodegen 2.19.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> /usr/local/Cellar/xcodegen/2.19.0/bin/XcodeGen --spec /private/tmp/xcodegen-test-20210223-82884-wnda1w/xcodegen.yml
dyld: Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit
  Referenced from: /usr/local/Cellar/xcodegen/2.19.0/bin/XcodeGen
  Reason: image not found
```
Does this library exist on Mojave?

**Comment by alebcay** [comment]
[Looks like it's only available on macOS 10.15 and later](https://developer.apple.com/documentation/cryptokit/).

**Comment by carlocab** [comment]
The only evidence of pre-requisites on the project GitHub page is Xcode 11 though. But I guess it's entirely possible they've never bothered to test this on Mojave.

**Comment by Bo98** [comment]
I think it's pulled in from one of its dependencies: https://github.com/tuist/XcodeProj/blob/ad2d6cbdfade93e3dd95813786c6b78910ab8339/Sources/XcodeProj/Extensions/String%2Bmd5.swift

Given the conditional checks there, I consider it a bug that it's strong linking CryptoKit - it should be weak linking instead.

**Comment by alebcay** [comment]
Opened upstream issue https://github.com/yonaskolb/XcodeGen/issues/1033 for this.

**Comment by yonaskolb** [comment]
Have opened https://github.com/Homebrew/homebrew-core/pull/74854

**Pull request closed without merging**
