### PR TITLE
kotlin-native 1.3.0 (new formula)

### PR DESCRIPTION
**Pull request by Nimrodda**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is a re-opening of #33989 as the former cannot be commented on anymore. IMO it is not feasible that this formula will build from source and pre-built binaries should be used instead.

According to Kotlin Native's [README.md](https://github.com/JetBrains/kotlin-native/blob/d74384db189a70318bd187d7c43d57040bf50467/README.md):
>The build can take about an hour on a Macbook Pro

Not to mention that the prerequisites are to have the following installed:

>install JDK for your platform, instead of JRE. The build requires tools.jar, which is not included in JRE;
>on macOS install Xcode 10.1

BTW: I noticed that the already existing [Kotlin formula](https://github.com/Homebrew/homebrew-core/blob/a506f8508e40d47040698349ba95d7df06f34d75/Formula/kotlin.rb) also downloads a pre-built binary. (Just saying)

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hi, thanks for the pull request! Homebrew formulas need to build from source to be acceptable in the core repository: https://docs.brew.sh/Acceptable-Formulae

This is shipping target-specific binary data and bytecode:

```
OpenGL/targets/macos_x64/native/cstubs.bc:                  LLVM bitcode, wrapper x86_64
```

**Comment by Nimrodda** [comment]
There are no other pre-built binaries shipped officially by Jetbrains for MacOS or any other platform. Kotlin native only supports 64bit systems. See https://github.com/JetBrains/kotlin-native/issues/939

**Comment by fxcoudert** [comment]
The formula will need to build from source. I am closing for now, feel free to reopen once a suitable PR is ready.

**Comment by Nimrodda** [comment]
@fxcoudert As I said, building from source will take about an hour on the host computer. This does not make any sense. This formula must be included as a binary!!!

**Comment by SMillerDev** [comment]
Including it as a binary in core is not allowed as per the homebrew rules. Also, boost takes a couple of hours to compile but we ship that too because all users should be using the homebrew provided bottles. You can see more about those and the rules for acceptable formula on docs.brew.sh

**Comment by fxcoudert** [comment]
> Kotlin native compiler takes an hour to build. It does not make any sense to have the formula build from source. Please reopen the PR and merge it.

As @SMillerDev said, we have many compilers in core, and they are all built from source or bootstrapped.

> It's not like it's the first ever formula that is not build from source. There're plenty of formulas that download a pre-built binary :)

It would be suitable for a Cask, or a user-maintained tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap but not in Homebrew core

**Pull request closed without merging**
