### PR TITLE
*binutils 2.42

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
 output.cc:32:10: fatal error: 'uchar.h' file not found
 #include <uchar.h>
          ^~~~~~~~~
```

**Comment by FtZPetruska** [comment]
Looks like the issue has already been reported upstream: https://sourceware.org/bugzilla/show_bug.cgi?id=31320

From personal testing, the following path was enough to get it to build on my personal machine (Sonoma, arm64):
```patch
diff --git a/gold/output.cc b/gold/output.cc
index ead67f20363..98b2f25c18b 100644
--- a/gold/output.cc
+++ b/gold/output.cc
@@ -29,7 +29,9 @@
 #include <unistd.h>
 #include <sys/stat.h>
 #include <algorithm>
+#ifndef __APPLE__
 #include <uchar.h>
+#endif
 
 #ifdef HAVE_SYS_MMAN_H
 #include <sys/mman.h>
diff --git a/gold/stringpool.cc b/gold/stringpool.cc
index d8f38cfabc1..e04909edad1 100644
--- a/gold/stringpool.cc
+++ b/gold/stringpool.cc
@@ -25,7 +25,9 @@
 #include <cstring>
 #include <algorithm>
 #include <vector>
+#ifndef __APPLE__
 #include <uchar.h>
+#endif
 
 #include "output.h"
 #include "parameters.h"
```

Using this suggestion from the thread did not work for me:
```
#ifdef __APPLE__
#include <stdint.h>
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#else
#include <uchar.h>
#endif
```
```
output.cc:34:24: error: cannot combine with previous 'type-name' declaration specifier
typedef uint_least16_t char16_t;
                       ^
output.cc:35:24: error: cannot combine with previous 'type-name' declaration specifier
typedef uint_least32_t char32_t;
                       ^
```

**Comment by fxcoudert** [comment]
Rerunning to see which SDKs have the header and which don't.

**Comment by fxcoudert** [comment]
Testing the patch at https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=941d02eaae0557c80c9e4130478e584a8b284494 mentioned in https://sourceware.org/bugzilla/show_bug.cgi?id=30867

**Comment by fxcoudert** [comment]
Upstream effectively decided to raise their requirements and excluded Monterey and earlier. Not sure why it only manifests for some targets.

**Review by iMichka — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
Would this break some reverse deps on Monterey? I see a few formula that would still need it on macOS

**Comment by iMichka** [comment]
Whoops I approved to fast, I wanted to discuss the Monterey situation first, sorry. I canceled the upload job.

**Comment by fxcoudert** [comment]
> Would this break some reverse deps on Monterey? I see a few formula that would still need it on macOS

Neither `arm-linux-gnueabihf-binutils` nor `x86_64-linux-gnu-binutils` are dependencies of anything in homebrew-core.

**Comment by Bo98** [comment]
Unlike C, `char16_t` and `char32_t` are builtin types in C++. They are not defined in `uchar.h` so the include seems unnecessary entirely unless they're catering for C99-compatible compilers that are not C++11 compliant (though https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=941d02eaae0557c80c9e4130478e584a8b284494 seems to suggest otherwise).

**Comment by Bo98** [comment]
For example, see:

* https://godbolt.org/z/Pc79Ksheb (oldest GCC on Godbolt which accepts `-std=c++0x`)
* https://godbolt.org/z/vb1cMb9x7 (Clang 3)
* https://godbolt.org/z/5fEb3dGbb (MSVC)
* https://godbolt.org/z/fTqr86W8T (icc)

**Review by iMichka — APPROVED** [review]

**Pull request merged**
