### PR TITLE
nebula 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by tommyang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by SMillerDev** [comment]
Thanks @tommyang! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by rvangcode** [comment]
@bayandin Following the rest of this thread, your closing this seems somewhat out of the blue to me. It seems to me it was ready to merge - did you press a wrong button 😄 ?

**Comment by SMillerDev** [comment]
It's closed by a merge from the commandline, as all homebrew formulae are.

**Comment by bayandin** [comment]
Hey @rvangcode, don't worry! The PR was merged in https://github.com/Homebrew/homebrew-core/commit/b70d621638348970ca71dec1b4b535e5b9ee35ba. Because the formula requires bottles we have a non-GitHub flow for merging it.

**Comment by SMillerDev** [comment]
That's why it has a commit hash in the close message by the way.

**Comment by rvangcode** [comment]
Ah, my apologies for the noise. Thanks for adding this to Homebrew :)

**Pull request closed without merging**
