### PR TITLE
rex 1.13.2

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
name = Rex
author = Jan Gehring <jfried@rexify.org>
license = Apache_2_0
copyright_holder = Jan Gehring
```

**Comment by fxcoudert** [comment]
Trying on ARM…

**Comment by carlocab** [comment]
Ah, the missing ARM bottle is applied only to formulae that have a Big Sur bottle but no ARM bottle. This one doesn't have a Big Sur bottle...

**Comment by fxcoudert** [comment]
@carlocab no I don't think we need a missing big sur bottle label, after all if there is an open PR it will either build or not build (ARM is different because we skip the build if there is no existing bottle)

**Comment by carlocab** [comment]
Right, that's actually exactly what I was thinking when I created the label and added it to the ones that are automatically applied. Guess I forgot 😅

**Comment by mitchblank** [comment]
I actually was working on this same formula recently... there are a couple other fixes needed:
1. the ordering of the resource build needs to be made deterministic (my branch does this)
2. like other perl curses users it requires some build tweaks to work around Big Sur perl issues.  Unfortunately the fix we used on other formula doesn't quite work as-is because the makemaker-generated makefile is *slightly* different due to something or another and I was still diagnosing that

**Comment by chenrui333** [comment]
@mitchblank feel free to drop a new PR, I can close mine. :)

**Comment by chenrui333** [comment]
closing mine.

**Pull request closed without merging**
