### PR TITLE
babel 7.22.17

### PR DESCRIPTION
**Pull request by dnhn**
Created by `brew bump`

-----

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> Created by `brew bump`
> 
> Created with `brew bump-formula-pr`.

there is babel-cli resource needs to be checked

**Comment by chenrui333** [comment]
it is up to date

image

**Review by chenrui333 — APPROVED** [review]

**Comment by dnhn** [comment]
@chenrui333 I’ve got it from here https://github.com/babel/babel/releases/tag/v7.22.17

**Comment by chenrui333** [comment]
@dnhn if you see the previous PRs, it always has a resource check task, https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr++babel

**Pull request merged**
