### PR TITLE
ponyc 0.21.0

### PR DESCRIPTION
**Pull request by SeanTAllen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
According to the release notes, this now supports LLVM 5.0.0, so should be `depends_on "llvm"`

**Comment by SeanTAllen** [comment]
@fxcoudert I'm a Pony core team member. We do not officially support LLVM 5. It is experimental. It can be built however, there are large performance degradations due to a work around we had to do for an LLVM bug. Additionally we make no guarantee that it Pony wont crash with LLVM 5. We are putting it out there as an option for folks to try while we continue to work on getting it fully supported. LLVM 3.9 is still the last version that we are confident in people using.

**Comment by ilovezfs** [comment]
@SeanTAllen can we have a pledge that ponyc will use LLVM 5 before 2019 :smiling_imp:

**Comment by ilovezfs** [comment]
:bowing_man: :horse: :ocean:

**Comment by SeanTAllen** [comment]
@ilovezfs We are actively working on it. we managed after a lot of hard work to track down why LLVM 4 and 5 were segfaulting and put in a work around so that tests do not segfault. However, there's a large performance impact from that. At this point, we also don't know there aren't other stability problems as 4 and 5 have only been used so far when tests are run in CI. Its possible that we might never support LLVM 5. The solution might be that we have to upstream a fix with LLVM if that is the case, we wouldnt support LLVM 4 or 5 but would support later versions.

**Comment by ilovezfs** [comment]
makes sense

**Comment by SeanTAllen** [comment]
Thanks as always @ilovezfs.

**Pull request closed without merging**
