### PR TITLE
opensearch-dashboards 2.9.0

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
A PR to upstream with Apple Silicon support: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4983

### CODE REVIEW

**Comment by bayandin** [comment]
The test with `opensearch` fails on macOS 11-x86_64: 
```
 java.lang.UnsupportedOperationException: sandbox_init(): Operation not permitted
```
https://github.com/Homebrew/homebrew-core/actions/runs/6132394847/job/16645157468?pr=141856

But it looks like it's rather related to `opensearch` formula than to `opensearch-dashboards`
Funny enough, we had these errors for `elasticsearch`:
- https://github.com/Homebrew/homebrew-core/pull/62019
- https://github.com/Homebrew/homebrew-core/pull/64573

**Comment by p-linnane** [comment]
@bayandin We just dropped support for Big Sur, so this should be good if you want to rebase it.

**Comment by p-linnane** [comment]
You'll want to squash the commits into one (`opensearch-dashboards 2.9.0`) so the autosquash workflow doesn't create replacement PR.

**Comment by bayandin** [comment]
Thanks @p-linnane, all done!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
