### PR TITLE
libidn 1.41

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
This might not be a stable release yet: https://lists.gnu.org/archive/html/help-libidn/2022-06/msg00001.html

**Comment by chenrui333** [comment]
> This might not be a stable release yet: https://lists.gnu.org/archive/html/help-libidn/2022-06/threads.html

Agree, this is in a unstable release yet.

**Comment by carlocab** [comment]
On the other hand, some distros have picked this version up already: https://repology.org/project/libidn/versions

**Comment by fxcoudert** [comment]
I think it is stable: nothing on the libidn website indicates anything else, and GNU projects would not typically show an unstable version among the released ones.

I think the confusion comes from the fact that the release was included into [Debian testing](https://wiki.debian.org/DebianTesting) and [Debian unstable](https://wiki.debian.org/DebianUnstable).

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
