### PR TITLE
bartycrouch 3.9.3

### PR DESCRIPTION
**Pull request by Jeehut**

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please, and no error 405 this time!

**Comment by fxcoudert** [comment]
`curl: (22) The requested URL returned error: 404 Not Found` so that's not a 405, indeed…

still @BrewTestBot test this again please

**Comment by Dschee** [comment]
Looks good this time, wonder why it didn't work ... ❓

**Comment by fxcoudert** [comment]
@Dschee bintray is [unstable](http://status.bintray.com) right now and our bottle build thus fails

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @Dschee for the pull request!

**Pull request closed without merging**
