### PR TITLE
llnode 1.1.0

### PR DESCRIPTION
**Pull request by indutny**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by indutny** [comment]
My bad, didn't follow guidelines. Will fix things up in a bit, sorry!

**Comment by indutny** [comment]
Force pushed, should be better now.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/39c5673dc00affe78678e1b52c747c5199f397d1. Thank you for your contribution to Homebrew @indutny; we appreciate it! :smiley_cat:

**Comment by indutny** [comment]
Thank *you*, @DomT4 !

**Pull request closed without merging**
