### PR TITLE
mame & rom-tools 0.227

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
OK I'm trying on ARM, feel free to remove the label and skip for now, if it fails there.

**Comment by chenrui333** [comment]
looks like same linkage test failure as earlier.
```
==> /opt/homebrew/Cellar/mame/0.227/bin/mame -help
dyld: Library not loaded: /opt/homebrew/opt/pugixml/lib/libpugixml.1.dylib
  Referenced from: /opt/homebrew/Cellar/mame/0.227/bin/mame
  Reason: image not found
```

**Comment by mbcoguno** [comment]
Move pugixml to runtime dependency seems working (on my machine).

**Comment by chenrui333** [comment]
works great, thanks @mbcoguno!!

**Pull request closed without merging**
