### PR TITLE
krakend 0.4.0 (new formula)

### PR DESCRIPTION
**Pull request by alombarte**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

http://www.krakend.io

Thank you!
-----

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
@BrewTestBot test this please

**Comment by vinyldarkscratch** [comment]
@alombarte Yikes!  The Brew test bot is saying the repository isn't notable enough (less than 20 watchers).

**Comment by ilovezfs** [comment]
Thanks for the PR @alombarte! I'd recommend hosting this in [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) for now.

**Comment by alombarte** [comment]
Thank you! We are using our own tap for now. Will reopen when we are famous enough! ;)

**Comment by vinyldarkscratch** [comment]
@alombarte You guys excell past the required Star count, and pass the Fork count as well — just four more watchers and you’ll be good to go!  😄

**Comment by alombarte** [comment]
@vinyldarkscratch We have 20 watchers now! Shall we reopen?

**Comment by vinyldarkscratch** [comment]
Yay, congrats!  Yes please, @alombarte, and from there we’ll be able to proceed in getting this package added.  😉

**Comment by alombarte** [comment]
Only write members of the repo can reopen a closed issue. I can duplicate though if you prefer... Please let me know

**Comment by vinyldarkscratch** [comment]
Hmm...  I'd say, duplicate and mention this one, perhaps?

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/23425

**Pull request closed without merging**
