### PR TITLE
postgresql 11.0

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
- The Mojave `inreplace` fails, it's probably not needed anymore
- We can remove `without-perl` and `without-tcl`: they don't add dependencies, and nobody uses them
- I'd say `python@2` can go, too, it is much less used than `python`
- Hopefully `Temporarily disable building/installing the documentation` is fixed upstream now
- `fails_with :clang` for `build 211` is so old it's irrelevant 😆

**Comment by deepj** [comment]
Hello,
is possible to change the release rules in this context? Or improve a way to deal with incompatible  packages? PostgreSQL 11 is released for a while and it's still not in `homebrew`. I guess the most of PostgreSQL users using it through `homebrew` don't use the most of the above mentioned packages (let's say except `postgis`).

What I want to say, it's to find some better way how to notice users if they want to use xxx package incompatible with this new one and offer some options how to deal with it.

**Comment by Dieken** [comment]
@deepj  I ran "brew edit postgresq" and pasted the whole new formula, it's dirty but works @_@

**Comment by MikeMcQuaid** [comment]
> is possible to change the release rules in this context?

No, sorry.

> PostgreSQL 11 is released for a while and it's still not in `homebrew`

Please consider submitting a pull request where you address the current issues with this one if you want to speed things up.

> I guess the most of PostgreSQL users using it through `homebrew` don't use the most of the above mentioned packages

That doesn't matter; as a package manager we can't just push a version that knowingly breaks other, widely used packages.

**Comment by SMillerDev** [comment]
@lembacon can you rebase this?

**Comment by lembacon** [comment]
Since `postgresql` 11.1 has been released, I'm closing this one and will open a new one for that.

**Pull request closed without merging**
