### PR TITLE
i2pd 2.39.0

### PR DESCRIPTION
**Pull request by r4sas**
* Update i2pd to 2.39.0
* Remove `USE_AVX` and `USE_AESNI` in `make` command due to:
  * AVX flag is deprecated
  * AESNI checked at runtime, so disabling is not required since 2.35.0.

### CODE REVIEW

**Comment by r4sas** [comment]
Additional quick question: how make formulae bottled on ARM?

**Comment by cho-m** [comment]
> Additional quick question: how make formulae bottled on ARM?

I enabled a run on ARM CI and it failed. You can check the failure logs to see what was reason.

**Comment by r4sas** [comment]
Thank you.
I see where issue. How can I add `USE_AVX=no` for ARM only?
I'll add required checks in main repo, but they will be available here only on next tag.

**Comment by cho-m** [comment]
The common pattern is to create a list variable for arguments and append to it for ARM-only, e.g.
```rb
args = %W[
  DEBUG=no
  HOMEBREW=1
  USE_UPNP=yes
  PREFIX=#{prefix}
]
args << "USE_AVX=no" if Hardware::CPU.arm?
```

You can probably grep for other formulae that use the ARM condition syntax, like `mariadb`.

**Comment by r4sas** [comment]
Thank you. Done same way as you proposed, now let's see...

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
