### PR TITLE
ponyc 0.53.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /tmp/ponyc-20221202-7951-sw46t/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/thread_manager.h:50:31: error: expected ‘)’ before ‘(’ token
     50 |   GUARDED_BY(GetBenchmarkMutex()) Result results;
        |      
```

**Comment by chenrui333** [comment]
on linux

```
  In file included from /tmp/ponyc-20221221-7951-1mfxhew/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/perf_counters.h:26,
                   from /tmp/ponyc-20221221-7951-1mfxhew/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/benchmark_runner.h:23,
                   from /tmp/ponyc-20221221-7951-1mfxhew/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/benchmark.cc:18:
  /tmp/ponyc-20221221-7951-1mfxhew/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/thread_manager.h:50:31: error: expected ‘)’ before ‘(’ token
     50 |   GUARDED_BY(GetBenchmarkMutex()) Result results;
        |                          
```

**Comment by chenrui333** [comment]
build failure on linux build
```
  [  1%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark.cc.o
  In file included from /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/perf_counters.h:26,
                   from /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/benchmark_runner.h:23,
                   from /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/benchmark.cc:18:
  /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/thread_manager.h:50:31: error: expected ‘)’ before ‘(’ token
     50 |   GUARDED_BY(GetBenchmarkMutex()) Result results;
        |                               ^
  /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/mutex.h:12:56: note: in definition of macro ‘THREAD_ANNOTATION_ATTRIBUTE_’
     12 | #define THREAD_ANNOTATION_ATTRIBUTE_(x) __attribute__((x))
        |                                                        ^
  /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/thread_manager.h:50:3: note: in expansion of macro ‘GUARDED_BY’
     50 |   GUARDED_BY(GetBenchmarkMutex()) Result results;
        |   ^~~~~~~~~~
  /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/mutex.h:21:62: note: to match this ‘(’
     21 | #define GUARDED_BY(x) THREAD_ANNOTATION_ATTRIBUTE_(guarded_by(x))
        |                                                              ^
  /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/mutex.h:12:56: note: in definition of macro ‘THREAD_ANNOTATION_ATTRIBUTE_’
     12 | #define THREAD_ANNOTATION_ATTRIBUTE_(x) __attribute__((x))
        |                                                        ^
  /tmp/ponyc-20230101-7944-130rt5j/build/build_libs/gbenchmark-prefix/src/gbenchmark/src/thread_manager.h:50:3: note: in expansion of macro ‘GUARDED_BY’
     50 |   GUARDED_BY(GetBenchmarkMutex()) Result results;
        |   ^~~~~~~~~~
```

**Comment by chenrui333** [comment]
still the same issue.

**Comment by cho-m** [comment]
This builds the same `google-benchmark` version as our formula, which didn't have any issue.

**Comment by cho-m** [comment]
Added a workaround to build with LLVM.

However, as I already mentioned, we are able to build `google-benchmark` formula with GCC. So it is a bit odd that we cannot build it here. Maybe `ponyc` is using some build flags that are causing issue. Probably worth looking into further, but don't think we need to block new version for it.

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
