### PR TITLE
ruby 2.7.0

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes #48329.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Revision-bumped a few things that need it. `wpscan`'s postinstall fails on master as well, so I'm not concerned with that being a blocker.

**Comment by mistydemeo** [comment]
Confirmed mikutter is also broken in master; not broken by this branch.

**Comment by SMillerDev** [comment]
Wpscan is failing on missing gems but it's also way behind. Updating to the latest version could very well fix it.

**Comment by jonchang** [comment]
I've got a partial patch for updating `wpscan`. It installs but doesn't run; `minitest` and friends are definitely in `libexec` so I'm not sure what I'm doing wrong with bundler (and also not really sure I know what bundler is doing in the first place).
```
==> /usr/local/Cellar/wpscan/3.7.8/bin/wpscan --update
Last 15 lines from /Users/jonchang/Library/Logs/Homebrew/wpscan/post_install.01.wpscan:
/usr/local/Cellar/wpscan/3.7.8/libexec/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find minitest-5.14.0 in any of the sources (Bundler::GemNotFound)
```

```diff
diff --git a/Formula/wpscan.rb b/Formula/wpscan.rb
index f2ca67500e..2b72cfd4e0 100644
--- a/Formula/wpscan.rb
+++ b/Formula/wpscan.rb
@@ -1,9 +1,8 @@
 class Wpscan < Formula
   desc "Black box WordPress vulnerability scanner"
   homepage "https://wpscan.org"
-  url "https://github.com/wpscanteam/wpscan/archive/2.9.4.tar.gz"
-  sha256 "ad066b48565e82208d5e0451891366f6a9b9a3648d149d14c83d00f4712094d3"
-  revision 1
+  url "https://github.com/wpscanteam/wpscan/archive/v3.7.8.tar.gz"
+  sha256 "4837ca3f8d5d42ca6aa8ccfa61fb3cb8262f050903e6b6d28f747709fea637a5"
   head "https://github.com/wpscanteam/wpscan.git"
 
   bottle do
@@ -17,41 +16,29 @@ class Wpscan < Formula
   depends_on "ruby"
 
   def install
-    inreplace "lib/common/common_helper.rb" do |s|
-      s.gsub! "File.join(USER_DIR, '.wpscan/cache')", "'#{var}/cache/wpscan'"
-      s.gsub! "File.join(USER_DIR, '.wpscan/data')", "'#{var}/wpscan/data'"
-      s.gsub! "File.join(USER_DIR, '.wpscan/log.txt')", "'#{var}/log/wpscan/log.txt'"
-    end
-
-    system "unzip", "-o", "data.zip"
-    libexec.install "data", "lib", "spec", "Gemfile", "Gemfile.lock", "wpscan.rb"
-
+    inreplace "lib/wpscan.rb", /DB_DIR.*=.*$/, "DB_DIR = Pathname.new('#{var}/wpscan/db')"
+    libexec.install Dir["*"]
     ENV["GEM_HOME"] = libexec
     ENV["BUNDLE_PATH"] = libexec
     ENV["BUNDLE_GEMFILE"] = libexec/"Gemfile"
     system "gem", "install", "bundler"
     bundle = Dir["#{libexec}/**/bundle"].last
-    system bundle, "install", "--without", "test"
+    system bundle, "install", "--jobs=#{ENV.make_jobs}"
+    wpscan = Dir["#{libexec}/ruby/**/bin/wpscan"].last
 
     (bin/"wpscan").write <<~EOS
       #!/bin/bash
       GEM_HOME="#{libexec}" BUNDLE_GEMFILE="#{libexec}/Gemfile" \\
         exec "#{bundle}" exec "#{Formula["ruby"].opt_bin}/ruby" \\
-        "#{libexec}/wpscan.rb" "$@"
+        "#{wpscan}" "$@"
     EOS
   end
 
   def post_install
-    (var/"log/wpscan").mkpath
     # Update database
     system bin/"wpscan", "--update"
   end
 
-  def caveats; <<~EOS
-    Logs are saved to #{var}/cache/wpscan/log.txt by default.
-  EOS
-  end
-
   test do
     assert_match "URL: https://wordpress.org/",
                  pipe_output("#{bin}/wpscan --url https://wordpress.org/")
```

**Comment by mistydemeo** [comment]
Looks like the `GEM_HOME` in the bin wrapper is wrong. This works:

```patch
diff --git a/Formula/wpscan.rb b/Formula/wpscan.rb
index f2ca67500e..7b3323314e 100644
--- a/Formula/wpscan.rb
+++ b/Formula/wpscan.rb
@@ -1,9 +1,8 @@
 class Wpscan < Formula
   desc "Black box WordPress vulnerability scanner"
   homepage "https://wpscan.org"
-  url "https://github.com/wpscanteam/wpscan/archive/2.9.4.tar.gz"
-  sha256 "ad066b48565e82208d5e0451891366f6a9b9a3648d149d14c83d00f4712094d3"
-  revision 1
+  url "https://github.com/wpscanteam/wpscan/archive/v3.7.8.tar.gz"
+  sha256 "4837ca3f8d5d42ca6aa8ccfa61fb3cb8262f050903e6b6d28f747709fea637a5"
   head "https://github.com/wpscanteam/wpscan.git"
 
   bottle do
@@ -17,41 +16,33 @@ class Wpscan < Formula
   depends_on "ruby"
 
   def install
-    inreplace "lib/common/common_helper.rb" do |s|
-      s.gsub! "File.join(USER_DIR, '.wpscan/cache')", "'#{var}/cache/wpscan'"
-      s.gsub! "File.join(USER_DIR, '.wpscan/data')", "'#{var}/wpscan/data'"
-      s.gsub! "File.join(USER_DIR, '.wpscan/log.txt')", "'#{var}/log/wpscan/log.txt'"
-    end
-
-    system "unzip", "-o", "data.zip"
-    libexec.install "data", "lib", "spec", "Gemfile", "Gemfile.lock", "wpscan.rb"
-
+    inreplace "lib/wpscan.rb", /DB_DIR.*=.*$/, "DB_DIR = Pathname.new('#{var}/wpscan/db')"
+    libexec.install Dir["*"]
     ENV["GEM_HOME"] = libexec
     ENV["BUNDLE_PATH"] = libexec
     ENV["BUNDLE_GEMFILE"] = libexec/"Gemfile"
     system "gem", "install", "bundler"
     bundle = Dir["#{libexec}/**/bundle"].last
-    system bundle, "install", "--without", "test"
+    system bundle, "install", "--jobs=#{ENV.make_jobs}"
+    wpscan = Dir["#{libexec}/ruby/**/bin/wpscan"].last
+
+    ruby_series = Formula["ruby"].version.to_s.split(".")[0..1].join(".")
+    (libexec/"ruby/#{ruby_series}.0/gems").install 
+
 
     (bin/"wpscan").write <<~EOS
       #!/bin/bash
-      GEM_HOME="#{libexec}" BUNDLE_GEMFILE="#{libexec}/Gemfile" \\
+      GEM_HOME="#{libexec}/ruby/#{ruby_series}.0" BUNDLE_GEMFILE="#{libexec}/Gemfile" \\
         exec "#{bundle}" exec "#{Formula["ruby"].opt_bin}/ruby" \\
-        "#{libexec}/wpscan.rb" "$@"
+        "#{wpscan}" "$@"
     EOS
   end
 
   def post_install
-    (var/"log/wpscan").mkpath
     # Update database
     system bin/"wpscan", "--update"
   end
 
-  def caveats; <<~EOS
-    Logs are saved to #{var}/cache/wpscan/log.txt by default.
-  EOS
-  end
-
   test do
     assert_match "URL: https://wordpress.org/",
                  pipe_output("#{bin}/wpscan --url https://wordpress.org/")
```

**Comment by jonchang** [comment]
`wpscan` can actually use system Ruby. Here's the diff for that.

`brew test wpscan` will always fail since it checks if `/usr/local/var/wpscan/db` is writeable (which it isn't due to the sandbox). I've opened https://github.com/wpscanteam/wpscan/pull/1455 upstream to address this. Running the same command outside of the testing sandbox works fine.

```diff
diff --git a/Formula/wpscan.rb b/Formula/wpscan.rb
index f2ca67500e..49bf3dd986 100644
--- a/Formula/wpscan.rb
+++ b/Formula/wpscan.rb
@@ -1,9 +1,8 @@
 class Wpscan < Formula
   desc "Black box WordPress vulnerability scanner"
   homepage "https://wpscan.org"
-  url "https://github.com/wpscanteam/wpscan/archive/2.9.4.tar.gz"
-  sha256 "ad066b48565e82208d5e0451891366f6a9b9a3648d149d14c83d00f4712094d3"
-  revision 1
+  url "https://github.com/wpscanteam/wpscan/archive/v3.7.8.tar.gz"
+  sha256 "4837ca3f8d5d42ca6aa8ccfa61fb3cb8262f050903e6b6d28f747709fea637a5"
   head "https://github.com/wpscanteam/wpscan.git"
 
   bottle do
@@ -14,46 +13,33 @@ class Wpscan < Formula
     sha256 "7289430447efb7be22a729ef3d2147702c770984e4b96b61607a06aea8e40ef3" => :sierra
   end
 
-  depends_on "ruby"
+  uses_from_macos "ruby"
 
   def install
-    inreplace "lib/common/common_helper.rb" do |s|
-      s.gsub! "File.join(USER_DIR, '.wpscan/cache')", "'#{var}/cache/wpscan'"
-      s.gsub! "File.join(USER_DIR, '.wpscan/data')", "'#{var}/wpscan/data'"
-      s.gsub! "File.join(USER_DIR, '.wpscan/log.txt')", "'#{var}/log/wpscan/log.txt'"
-    end
-
-    system "unzip", "-o", "data.zip"
-    libexec.install "data", "lib", "spec", "Gemfile", "Gemfile.lock", "wpscan.rb"
-
+    inreplace "lib/wpscan.rb", /DB_DIR.*=.*$/, "DB_DIR = Pathname.new('#{var}/wpscan/db')"
+    libexec.install Dir["*"]
     ENV["GEM_HOME"] = libexec
     ENV["BUNDLE_PATH"] = libexec
     ENV["BUNDLE_GEMFILE"] = libexec/"Gemfile"
     system "gem", "install", "bundler"
     bundle = Dir["#{libexec}/**/bundle"].last
-    system bundle, "install", "--without", "test"
+    system bundle, "install", "--jobs=#{ENV.make_jobs}"
+    gem_home = Dir["#{libexec}/ruby/*.0"].last
 
     (bin/"wpscan").write <<~EOS
       #!/bin/bash
-      GEM_HOME="#{libexec}" BUNDLE_GEMFILE="#{libexec}/Gemfile" \\
-        exec "#{bundle}" exec "#{Formula["ruby"].opt_bin}/ruby" \\
-        "#{libexec}/wpscan.rb" "$@"
+      GEM_HOME="#{gem_home}" BUNDLE_GEMFILE="#{libexec}/Gemfile" \\
+        exec "#{bundle}" exec "/usr/bin/ruby" \\
+        "#{gem_home}/bin/wpscan" "$@"
     EOS
   end
 
   def post_install
-    (var/"log/wpscan").mkpath
-    # Update database
     system bin/"wpscan", "--update"
   end
 
-  def caveats; <<~EOS
-    Logs are saved to #{var}/cache/wpscan/log.txt by default.
-  EOS
-  end
-
   test do
     assert_match "URL: https://wordpress.org/",
-                 pipe_output("#{bin}/wpscan --url https://wordpress.org/")
+                 pipe_output("#{bin}/wpscan --no-update --url https://wordpress.org/")
   end
 end
```

**Comment by mistydemeo** [comment]
Not on 10.14 and earlier, unfortunately. It requires Ruby 2.4 or later. I'll adopt the `--no-update` fix and leave the rest using the Homebrew Ruby.

**Comment by SMillerDev** [comment]
CI is green 🎉

**Pull request closed without merging**
