### PR TITLE
monetdb 11.33.11

### PR DESCRIPTION
**Pull request by monetdb-team**

### CODE REVIEW

**Comment by sjoerdmullender** [comment]
This is a new release of the MonetDB package (Apr2019-SP1 aka 11.33.11). Until now I've never had a complaint that the checkin message consisting of package name and version number (which follows your published guide lines) wasn't good enough.  What changed?

**Comment by SMillerDev** [comment]
>  What changed?

We started checking pull request body.
Please make the bot send something like "Autogenerated PR as part of the release" so there's some more context in the PR.

**Comment by SMillerDev** [comment]
The commit was fine and should only have `<formula> <version>` but the pull request should have a body.

**Comment by fxcoudert** [comment]
> the pull request should have a body

Ideally, please include a handle for whom we should contact if the autogenerated PR fails to build. Thanks!

**Comment by sjoerdmullender** [comment]
> Ideally, please include a handle for whom we should contact if the autogenerated PR fails to build. 
You mean, add an email address in the pull-request message body?

**Comment by fxcoudert** [comment]
Maybe a github handle, if possible?

**Pull request closed without merging**
