### PR TITLE
pdm 0.10.1

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
do we need to change the install step? lgtm though.

**Comment by dtrodrigues** [comment]
Yeah I just noticed that, I'll try updating it.

**Comment by dtrodrigues** [comment]
One of the resources does not build from source but the wheel does install: https://github.com/frostming/python-cfonts/issues/36

**Comment by dtrodrigues** [comment]
I submitted a PR and included the patch in the formula which does allow the formula to install, but I'm not sure if it's the correct approach. I've pinged the project maintainer to see if they have a suggested path forward, but I believe this should be good to go for the time being.

**Comment by dtrodrigues** [comment]
Closing in favor of #64137

**Pull request closed without merging**
