### PR TITLE
openvpn: depends on openssl@1.1

### PR DESCRIPTION
**Pull request by JLHwung**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Is there a reason for this change?

**Comment by JLHwung** [comment]
@ilovezfs Just update dependency to latest version as openvpn 2.4.3 brings openssl 1.1 support.

`brew uses openvpn` implies there is no formulae depends on openvpn, so I think it is safe to have it depends on openssl 1.1.

**Comment by ilovezfs** [comment]
If there's no specific reason you need this to use openssl@1.1, passing on this for now. But thanks for the PR nonetheless.

**Comment by JLHwung** [comment]
Alright. Is there any documented openssl 1.1 update contribution policy? It would good to inform potential contributor whether this kind of PR is welcomed.

**Comment by ilovezfs** [comment]
Not in the docs but see

https://github.com/Homebrew/homebrew-core/issues/4543#issuecomment-260371674
https://github.com/Homebrew/homebrew-core/issues/4543#issuecomment-287628115
https://github.com/Homebrew/homebrew-core/pull/14158#issuecomment-305839321

**Comment by JLHwung** [comment]
Got that, thank you so much. :)

**Comment by ilovezfs** [comment]
@JLHwung you're welcome!

**Comment by jmaurice** [comment]
Please re-open and merge this PR. OpenSSL 1.1 adds many crypto features that OpenVPN 2.4.3 now officially 
screen shot 2017-07-05 at 16 04 51
supports.

**Pull request closed without merging**
