### PR TITLE
node: remove leftover icu caveat

### LINKED ISSUE #10251: Node inexistant option in caveats
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Hello ! 

The problem is likely with the build script :

The Caveats section of `node` says I could use `--with-full-icu` option, but the formulae does NOT provide the option
```
 ~  brew reinstall node --with-full-icu
==> Reinstalling node
Warning: node: this formula has no --with-full-icu option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/node-7.6.0.sierra.bottle.tar.gz
Already downloaded: /Users/arthur/Library/Caches/Homebrew/node-7.6.0.sierra.bottle.tar.gz
==> Pouring node-7.6.0.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
Please note by default only English locale support is provided. If you need
full locale support you should either rebuild with full icu:
  `brew reinstall node --with-full-icu`
or add full icu data at runtime following:
  https://github.com/nodejs/node/wiki/Intl#using-and-customizing-the-small-icu-build

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/7.6.0: 3,148 files, 40M
```
No logs form `brew gist-logs node`
 
```
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 81e8a66398e0a947963c9eda671872c193ab994d
Core tap last commit: 51 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/arthur/.rvm/rubies/ruby-2.3.1/bin/ruby
Java: 1.8.0_60
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Fixes #10251

CC @ilovezfs 😉

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Is this how we do caveats when there's only a single if?

**Comment by MikeMcQuaid** [comment]
> Is this how we do caveats when there's only a single if?

I think so?

**Comment by ilovezfs** [comment]
Ah, looks like we have a mixture of this, and of
```
  def caveats
    if build.with? "cocoa" then <<-EOS.undent
      Please try the Cask for a better-supported Cocoa version:
        brew cask install emacs
      EOS
    end
  end
```

**Comment by ilovezfs** [comment]
and of
```
  def caveats
    if build.without? "default-names"
      <<-EOS.undent
        All commands have been installed with the prefix 'g'.
        If you do not want the prefix, install using the "with-default-names" option.

        If you need to use these commands with their normal names, you
        can add a "gnubin" directory to your PATH from your bashrc like:

            PATH="#{opt_libexec}/gnubin:$PATH"

        Additionally, you can access their man pages with normal names if you add
        the "gnuman" directory to your MANPATH from your bashrc as well:

            MANPATH="#{opt_libexec}/gnuman:$MANPATH"
      EOS
    end
```

**Comment by ilovezfs** [comment]
and a
```
  def caveats
    s = <<-EOS.undent
      For full Perl support you may need to adjust your PERL5LIB variable:
        export PERL5LIB="#{HOMEBREW_PREFIX}/lib/perl5/site_perl":$PERL5LIB
    EOS
    s if build.with? "perl"
  end
```
lol

**Comment by ilovezfs** [comment]
and even a
```
  if (build.with? "book") || (build.with? "patterns")
    def caveats; <<-EOS.undent
      This formula also downloads additional data, such as opening books and
      pattern files. They are stored in #{share}.

      At present, pachi cannot be pointed to external files, so make sure to
      set the working directory to #{share} if you
      want pachi to take advantage of these additional files.
    EOS
    end
  end

```

**Comment by DomT4** [comment]
The format for this form of caveat changed a lot and I never cared about it enough to harmonise that, so apologies 🙈.

**Review by ilovezfs — APPROVED** [review]

**Pull request merged**
