### PR TITLE
vault 0.6.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- add an option to run `make test`, and always do so when bottling
- all resources except `gox` have been vendored upstream

### CODE REVIEW

**Comment by sl4m** [comment]
It looks like there's a newer tag / revision that fixes the version reported via `vault version`. The tag / revision you're using now reports the version as `Vault v0.6.0-rc1`.

New tag: `v0.6.0-rebuild`
New revision: `d2d0aa07d079836c9a5bd258479b019ca00eb6b8`

**Comment by ilovezfs** [comment]
@sl4m last I checked, there was no difference between the tags with those names, but maybe that has since changed.

**Comment by sl4m** [comment]
I have tried both versions and the newer tag outputs the correct version.

**Comment by ilovezfs** [comment]
@sl4m yes as you can see I've already updated the PR ;)

**Comment by sl4m** [comment]
Sorry, was replying directly via email and haven't looked. :+1:

**Comment by ilovezfs** [comment]
@DomT4 :shipit:?

**Comment by DomT4** [comment]
Aye, seems reasonable to me.

**Pull request closed without merging**
