### PR TITLE
cmake 3.18.0

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by hjmallon** [comment]
There is now an upstream patch being worked on here https://gitlab.kitware.com/cmake/cmake/-/commit/83bc79e2326247c4a73608c6c9723a8bd398cf96?merge_request_iid=5035

This could be patched into 3.18 and dropped with 3.18.1?

**Comment by Bo98** [comment]
Yes, we can do that. I'll wait until it's merged - which shouldn't be long from past experience.

**Comment by claui** [comment]
As expected, the formula works perfectly on Apple Silicon, just like the previous version with the patches. 🥇

**Comment by hjmallon** [comment]
There is now a patch merged here https://gitlab.kitware.com/cmake/cmake/-/commit/83bc79e2326247c4a73608c6c9723a8bd398cf96

**Comment by SMillerDev** [comment]
https://gitlab.kitware.com/cmake/cmake/-/commit/24571e8eca27d6c51ca408f4b834fa930760e1d0.diff is the diff for the commit to the 2.18 branch

**Review by SeekingMeaning — APPROVED** [review]

**Pull request closed without merging**
