### PR TITLE
Update ponyc to 0.3.3

### PR DESCRIPTION
**Pull request by SeanTAllen**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
I rebased on master because some recent funny style changes is causing trouble when I try to pull the bottle. Rest assured, your contribution is still yours, and no action is required on your part.

**Comment by SeanTAllen** [comment]
@zmwangx thanks. i don't really care about attribution. i'm on the pony core team and just want to get the new version out to as many users as easily as possible.

**Comment by zmwangx** [comment]
Sure, I'll merge as soon as CI rebuild finishes.

**Comment by zmwangx** [comment]
Merged as c1e189f. Thank you for another contribution to Homebrew! For future reference, our preferred format of commit subject is `foo 1.2.3`.

**Comment by SeanTAllen** [comment]
@zmwangx thanks for the info, i'll update our "how to release" documentation.

**Pull request closed without merging**
