### PR TITLE
mariadb: fix for ARM

### PR DESCRIPTION
**Pull request by fxcoudert**
Use the upstream patch at https://github.com/MariaDB/server/pull/1743

### CODE REVIEW

**Comment by carlocab** [comment]
Doesn't apply, unfortunately:
```
==> Applying b1241585.patch
patch -g 0 -f -p1 -i /private/tmp/mariadb--patch-20210130-62359-sl7yxh/b1241585.patch
patching file include/my_global.h
Hunk #1 FAILED at 152.
1 out of 1 hunk FAILED -- saving rejects to file include/my_global.h.rej
patching file mysys/crc32/crc32_arm64.c
Hunk #1 succeeded at 4 with fuzz 2.
Hunk #2 FAILED at 73.
1 out of 2 hunks FAILED -- saving rejects to file mysys/crc32/crc32_arm64.c.rej
```

**Comment by tholu** [comment]
Based on this Pull Request, I took the upstream patch and fixed all problems by applying the changes to 10.5.8 without any further changes.

You can find a working formula in my tap: https://github.com/tholu/homebrew-tap/blob/master/mariadb.rb

Feel free to try out via:
```
brew tap tholu/tap
brew install tholu/tap/mariadb
```

You can find the modified patch in this gist: https://gist.github.com/tholu/a9f8a228609234f38e0cc1e0b5e2265d

Please note, that RocksDB also needs to be disabled for now for a successful build: https://github.com/tholu/homebrew-tap/blob/master/mariadb.rb#L69

**Comment by carlocab** [comment]
Thanks, @tholu. Can you submit the patch to https://github.com/Homebrew/formula-patches/, and we can incorporate it into this formula?

**Comment by carlocab** [comment]
Thanks again, @tholu. Do you have a tracking issue for rocksdb support on Apple Silicon? It'd be useful to include it in the formula so it can be activated when supported.

**Comment by tholu** [comment]
@carlocab Unfortunately, I don't. I have only found this comment upstream: https://github.com/MariaDB/server/pull/1743#issuecomment-772953059

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
