### PR TITLE
yarn 0.20.0

### PR DESCRIPTION
**Pull request by artdevjs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by mourner** [comment]
Can we rerun the test here? The failure seems random.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by mourner** [comment]
Passed! Good to merge then?

**Comment by ilovezfs** [comment]
new node version incoming. so let's wait on that

**Comment by mourner** [comment]
@ilovezfs I don't see why this would be a blocker. Yarn works with both the current one and the new one — it's a minor version with a small changelog (mostly bumping OpenSSL dep).

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by cebor** [comment]
Why upgraded to 20.0? 

19.1 is the latest official release!

https://github.com/yarnpkg/yarn/releases

**Comment by mourner** [comment]
It was initially marked as stable by mistake, but it should be promoted to stable this week anyway. See https://github.com/yarnpkg/yarn/issues/2616

**Pull request closed without merging**
