### PR TITLE
gradle 8.0, gradle@7 7.6 (new formula)

### PR DESCRIPTION
**Pull request by FrauBoes**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Thanks for your first contribution to Homebrew @FrauBoes!

**Comment by SMillerDev** [comment]
@FrauBoes what is the support policy for Gradle 7 from upstream ?

**Comment by FrauBoes** [comment]
@SMillerDev Gradle 7.6 will continue to be supported, until further notice.

**Comment by SMillerDev** [comment]
Where will people be able to find that further notice and will it be actively supported or security fixes only?

**Comment by ljacomet** [comment]
Hi @SMillerDev,

We have an [outdated EOL policy](https://docs.gradle.org/current/userguide/feature_lifecycle.html#eol_support).

It should be corrected (and will be for the next release) to say that the previous major version continues to see critical and security fixes.
You can confirm that by looking at the `6.9.x` releases that were made after Gradle `7.0` was released.

**Comment by SMillerDev** [comment]
Can you add a deprecation to the gradle@7 formula then, saying it's deprecated by upstream.

**Pull request closed without merging**
