### PR TITLE
libx11 1.8.6

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jmcphers** [comment]
The CI failures have the same error message a number of us have observed on Apple Silicon machines in https://github.com/Homebrew/homebrew-core/pull/132483:

```
  /opt/homebrew/Cellar/xtrans/1.5.0/include/X11/Xtrans/Xtranslcl.c:81:11: fatal error: 'stropts.h' file not found
  # include <stropts.h>
            ^~~~~~~~~~~
```

**Comment by JollyRoger8X** [comment]
> The CI failures have the same error message a number of us have observed on Apple Silicon machines in #132483:
> 
> ```
>   /opt/homebrew/Cellar/xtrans/1.5.0/include/X11/Xtrans/Xtranslcl.c:81:11: fatal error: 'stropts.h' file not found
>   # include <stropts.h>
>             ^~~~~~~~~~~
> ```

Just a note: This also affects _Intel-based_ Macs (not just Apple Silicon).

**Comment by daladim** [comment]
Maybe I have not dug enough, but doesn't this other thread suggest the `xtrans` package is broken? Should it be fixed, before (or in parallel to) adding a new version of libx11?

**Comment by furritos** [comment]
It should be noted that the steps [outlined here](https://github.com/Homebrew/homebrew-core/pull/132483#issuecomment-1589551256) are still valid to get libx11 installed.  Bring that note here because that thread was closed in favor for this one.

**Comment by SMillerDev** [comment]
Has someone tried to report this to the X11 developers yet?

**Comment by Lucy-Janssens** [comment]
Hi everyone, I'm gettign this error when trying to install libx11 on my mac M1 Pro using rosetta2, I'm on MacOS14 but I was gettign the same error before updating. 

here's the complete error mesage i get from brew : 

```
input:
arch -x86_64 /usr/local/homebrew/bin/brew install libx11

output:
==> Installing libx11
==> ./configure --prefix=/usr/local/homebrew/Cellar/libx11/1.8.4 --sysconfdir=/usr/local/homebrew/etc --localstatedir=/usr/local/homebrew/var --enable-unix-transport --
==> make
Last 15 lines from /Users/lucfer/Library/Logs/Homebrew/libx11/02.make:
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c lcCharSet.c -o lcCharSet.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c XDefaultIMIF.c -o XDefaultIMIF.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c IMWrap.c -o IMWrap.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c imKStoUCS.c -o imKStoUCS.o >/dev/null 2>&1
1 error generated.
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c ICWrap.c -o ICWrap.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c XlcSL.c -o XlcSL.o >/dev/null 2>&1
make[3]: *** [xim_trans.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c XlcDL.c -o XlcDL.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c lcCT.c -o lcCT.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -I../../include/X11 -I../../include -I../../include/X11 -I../../include -I../../include/X11 -I../../src/xcms -I../../src/xkb -I../../src/xlibi18n -I../../src -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/local/homebrew/Cellar/libxau/1.0.11/include -I/usr/local/homebrew/Cellar/libxdmcp/1.1.4/include -I/usr/local/homebrew/Cellar/libxcb/1.15_1/include -I/usr/local/homebrew/Cellar/xtrans/1.5.0/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -I/usr/local/homebrew/Cellar/xorgproto/2023.2/include -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -g -O2 -c XDefaultOMIF.c -o XDefaultOMIF.o >/dev/null 2>&1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!

These open issues may also help:
libx11 1.8.6 https://github.com/Homebrew/homebrew-core/pull/133898

Error: You are using macOS 14.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

**Comment by Tatikoma** [comment]
> --enable-local-transport

it installs without this option, is it required?

**Comment by shingoxy** [comment]
https://github.com/Homebrew/homebrew-core/pull/132483#issuecomment-1605895473

This answer helped me and I also followed this merge to modify the libx11 to 1.8.6 in the libx11.rb file. So far my lib11 1.8.6 has been installed sucessfully. I am trying to install the gaming porting toolkit again.

**Comment by branchvincent** [comment]
> > --enable-local-transport
> 
> it installs without this option, is it required?

thanks for investigating @paperchalice and @Tatikoma, looks like we should indeed remove `--enable-local-transport` as it's only supported on Solaris (more explanation at https://github.com/Homebrew/homebrew-core/pull/134949#issuecomment-1606406411)

Re-running this now

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
