### PR TITLE
imagemagick 6.9.4-4

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Make sure the Bintray mirror is updated. The `brew mirror` command will do it automatically for you if desired 😃.

**Comment by DomT4** [comment]
:shipit:

**Comment by MikeMcQuaid** [comment]
I reverted this because neither the mirror nor primary URL were downloading. In this case the issue was that the filename `brew mirror` uploaded and the one used in the formula were different.

**Comment by DomT4** [comment]
Apparently we downcase fetched tarballs?

```
~> brewmirror imagemagick
==> Downloading https://dl.bintray.com/homebrew/mirror/ImageMagick-6.9.4-5.tar.xz
Already downloaded: /usr/local/var/homebrew/cache/imagemagick-6.9.4-5.tar.xz
==> Uploading to https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.4-5.tar.xz
{"message":"success"}
```

```
~> brew fetch imagemagick -s -v -f
==> Downloading https://dl.bintray.com/homebrew/mirror/ImageMagick-6.9.4-5.tar.xz
/usr/bin/curl -fRLA Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://dl.bintray.com/homebrew/mirror/ImageMagick-6.9.4-5.tar.xz -C 0 -o /usr/local/var/homebrew/cache/imagemagick-6.9.4-5.tar.xz.incomplete --connect-timeout 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
```

Trying with it lowercased:
```
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.4-5.tar.xz
/usr/bin/curl -fRLA Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.4-5.tar.xz -C 0 -o /usr/local/var/homebrew/cache/imagemagick-6.9.4-5.tar.xz.incomplete --connect-timeout 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8578k  100 8578k    0     0  2839k      0  0:00:03  0:00:03 --:--:-- 2840k
Downloaded to: /usr/local/var/homebrew/cache/imagemagick-6.9.4-5.tar.xz
SHA256: 39a65b8e2371db36cb63709dea0b15f08a6870f8ce6103432f068112d9513c5a
```

**Comment by MikeMcQuaid** [comment]
@DomT4 Tarballs are fetched based on the formula naming rather than upstream. It's cool, it just means we'll need to rename on the mirroring.

**Comment by DomT4** [comment]
@MikeMcQuaid Ah, of course 👍, makes sense. Yeah, I just switched to the actually mirrored URL in the fresh PR.

**Pull request closed without merging**
