### PR TITLE
openblas64 0.3.21 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

OpenBLAS uses 32-bit integers by default to follow the reference BLAS.
This results in inefficient memory usage on 64-bit machines.

We can configure `openblas` to use 64-bit integers instead, but this is
likely to break many dependents that expect the same ABI as the
reference BLAS. To avoid this breakage, we can ship a 64-bit OpenBLAS as
`openblas64`. This is similar to what other distros (e.g. Debian,
Fedora) do for OpenBLAS.

The 64-bit version of OpenBLAS is what is used upstream by projects such
as Julia and NumPy.

We configure this with `SYMBOLSUFFIX` set to `64_` to allow loading both
versions of OpenBLAS in the same process. This is also the configuration
used in the projects mentioned above.

### CODE REVIEW

**Comment by fxcoudert** [comment]
> The 64-bit version of OpenBLAS is what is used upstream by projects such as Julia and NumPy.

Both can use either 32-bit or 64-bit, and the doc for numpy actually has it as default: https://numpy.org/devdocs/user/building.html#bit-blas-and-lapack

I'm not opposed, but seeing the duplication, maybe what we want is to ship both the 32 and 64-bit versions in the same formula? We could manage the headers by moving them to subdirectories (most libraries that depend on BLAS do not actually use the C headers).

**Comment by carlocab** [comment]
> Both can use either 32-bit or 64-bit, and the doc for numpy actually has it as default: https://numpy.org/devdocs/user/building.html#bit-blas-and-lapack

Yes, but if you install the NumPy wheels, you get `libopenblas64_.0.dylib`:
```
❯ python3 -m venv . && source bin/activate && pip install numpy &> /dev/null && ls -la lib/python3.10/site-packages/numpy/.dylibs
.rw-r--r-- 129k carlocab 16 Oct 17:11 libgcc_s.2.dylib
.rwxr-xr-x 3.3M carlocab 16 Oct 17:11 libgfortran.5.dylib
.rwxr-xr-x  23M carlocab 16 Oct 17:11 libopenblas64_.0.dylib
```
See also https://github.com/numpy/numpy/issues/13956.

> I'm not opposed, but seeing the duplication, maybe what we want is to ship both the 32 and 64-bit versions in the same formula? We could manage the headers by moving them to subdirectories (most libraries that depend on BLAS do not actually use the C headers).

My first local attempt at this was to ship them both in the same formula and install them into the same formula prefix. I ended up going with a separate formula since I wasn't sure how to handle the headers and the CMake/pkg-config files, which conflict with each other, and this doubles the install size from 56MB to 112MB.

We could probably move/rename conflicting files as needed, but that can get messy and also confusing for users. That, together with the install size made me put this in a separate formula (which probably could be made not-keg-only on macOS, actually).

I can give putting them into the same formula another try so that we can compare approaches, if desired.

**Comment by fxcoudert** [comment]
The doubling of the size is also something that will have an impact on users. I assume you plan on moving numpy to openblas64, but I am not sure all dependents of openblas can use openblas64: therefore, we will have mixed dependencies, which technically works but is not a great user experience.

How do other distros deal with the headers and pkg files? Is there a canonical way of renaming?

**Comment by carlocab** [comment]
> we will have mixed dependencies, which technically works but is not a great user experience.

This is true, but still better than getting multiple versions of OpenBLAS whether you have something using it or not.

> How do other distros deal with the headers and pkg files? Is there a canonical way of renaming?

I don't think they do any renaming. They just have a separate `openblas64` package configured with `INTERFACE64=1`, and, occasionally, `SYMBOLSUFFIX=64_`.

**Pull request closed without merging**
