### PR TITLE
clojure 1.8.0.119 (new formula)

### PR DESCRIPTION
**Pull request by puredanger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

*No - see below for details.*

-----

This is a new formula for Clojure (the language) to install the Clojure repl tool (`clj`). This tool has been created by the Clojure core team (of which I am a member) and released as a stable version for 1.8.0 and a devel version for the upcoming Clojure 1.9.0 release.

There is one audit failure as Clojure is currently in the brew blacklist. I have created a separate PR to remove clojure from the blacklist at https://github.com/Homebrew/brew/pull/3083. Presumably that PR needs to be applied before this formula can be accepted.

### CODE REVIEW

**Comment by JCount** [comment]
As laid out in the [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae.html) documentation:
```
Formulae in the core repository must have a stable version tagged by the upstream project. Tarballs are preferred to Git checkouts, and tarballs should include the version in the filename whenever possible.
```
The Homebrew-core repository is designed to provide stable/production level software. The `devel` and `head` specs are only used in conjunction with the required `stable` spec.
> provide feedback on this new tool prior to its official release.

We deliberately try to avoid having this repository act solely as a testing platform for any piece of software.

I am sorry, but because of these reasons, we cannot accept a Clojure formula that is still in alpha. If you would like to try and gather user feedback at this stage, I suggest you consider hosting your own tap for the time being. https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

**Comment by puredanger** [comment]
Ok, I have done a release for the last stable version Clojure 1.8.0 (but also have the devel version included for upcoming alpha).

**Comment by puredanger** [comment]
The blacklist PR has been accepted and there are now no audit failures.

**Comment by puredanger** [comment]
will just close and re-open a fresh pr

**Pull request closed without merging**
