### PR TITLE
mtm 1.2.1 (new formula)

### LINKED ISSUE #51: Homebrew formula
Hi @deadpixi :wave: 

I've tried to package `mtm` for Homebrew distribution but a substantial amount of changes between the latest release and `HEAD` turned out to be a dealbreaker (https://github.com/Homebrew/homebrew-core/pull/66093#issuecomment-739564041)
I'm wondering is there a new release on the horizon anytime soon so we could move this thing forward?

### PR DESCRIPTION
**Pull request by colindean**
mtm 1.2.1 (new formula) builds on https://github.com/Homebrew/homebrew-core/pull/66093

Closes https://github.com/deadpixi/mtm/issues/51

As comments illustrate, mtm 1.2.1 requires Homebrew's ncurses but future versions may be able to use it from macOS since HEAD compiles fine with `uses_from_macos "ncurses"`.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by colindean** [comment]
How can I reflect the need for brew's ncurses in the recipe so this audit passes?

```
mtm
    * Dependency 'ncurses' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
```

**Comment by chenrui333** [comment]
> How can I reflect the need for brew's ncurses in the recipe so this audit passes?
> 
> ```
> mtm
>     * Dependency 'ncurses' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
> ```

Sometimes that is false negative depending on the formula usage. (we could use macos native `ncurses` but sometimes formulae require newer `ncurses`)

**Comment by chenrui333** [comment]
@colindean can you squash the commits?

**Comment by colindean** [comment]
> @colindean can you squash the commits?

I can… I'd wanted to keep the original commit in place to recognize the work I built on.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
