### PR TITLE
pilosa 0.5.0

### PR DESCRIPTION
**Pull request by codysoyland**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by codysoyland** [comment]
This is failing to build, so I will close and re-open when I get it working.

**Comment by codysoyland** [comment]
I modified the formula to use `dep` instead of `glide` and successfully built it with `brew install --build-from-source pilosa`.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by codysoyland** [comment]
Ideally, we could merge #15311 prior to this version bump. I can combine the two PRs into one if that helps. Thanks!

**Comment by ilovezfs** [comment]
@codysoyland yes combining them would help. Also, I have added a `dep` formula so you can use that.

**Comment by codysoyland** [comment]
@ilovezfs Thanks, I've updated this PR to include the changes in #15311. Please advise on the _statik_ build-time dependency -- Would it be preferred for me to create a homebrew package for _statik_, and if so, what should it be named, as there is an existing package called _statik_?

**Comment by codysoyland** [comment]
Closing this PR in favor of #16688.

**Pull request closed without merging**
