### PR TITLE
bedops: fix sha256 checksum

### PR DESCRIPTION
**Pull request by amadejpapez**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Updated sha256 checksum. Related to #88329

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why did the checksum change?

**Comment by amadejpapez** [comment]
> Why did the checksum change?

v2.4.40 was released on July 22 and it was updated in Homebrew that day. Looking at the version tag on bedops repo another [commit](https://github.com/bedops/bedops/commit/abf5c517d921cf1ec188119293b021491e891e66) was added on July 27.

**Comment by SMillerDev** [comment]
Can you ask why they did that? 
The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do so we want to make sure that this was done intentional by upstream and the repo has not been compromised.

**Comment by amadejpapez** [comment]
@SMillerDev The maintainer confirmed that this was intentional in the above linked issue. :)

> Yes, I added a file a few days later. Thanks for updating the homebrew package.

**Review by branchv — APPROVED** [review]
@amadejpapez thank you!

**Pull request merged**
