### PR TITLE
Update git-archive-all to 1.15

### PR DESCRIPTION
**Pull request by Kentzo**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by Kentzo** [comment]
How do I update bottle?

**Comment by MikeMcQuaid** [comment]
@Kentzo We'll do that when pulling. The test is failing so needs adjusted: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7074/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_git_archive_all/

**Comment by ilovezfs** [comment]
@Kentzo the test can be fixed with this diff
```
diff --git a/Formula/git-archive-all.rb b/Formula/git-archive-all.rb
index 6b0ce32..c15dcf9 100644
--- a/Formula/git-archive-all.rb
+++ b/Formula/git-archive-all.rb
@@ -27,7 +27,7 @@ class GitArchiveAll < Formula
     system "git", "add", "homebrew"
     system "git", "commit", "--message", "brewing"
 
-    assert_equal "#{testpath}/homebrew => archive/homebrew",
+    assert_equal "#{testpath.realpath}/homebrew => archive/homebrew",
                  shell_output("#{bin}/git-archive-all --dry-run ./archive", 0).chomp
   end
 end
```

**Comment by Kentzo** [comment]
@ilovezfs Was fixed by checks still fail.

**Comment by Kentzo** [comment]
Anyone?

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Sorry for the delay!  Merged as 488f52303a2069d9a01384505ffda7f4a9f39971.

**Pull request closed without merging**
