### PR TITLE
gmt 6.2.0

### PR DESCRIPTION
**Pull request by seisman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Update to GMT 6.2.0 and its resource DCW to 2.0.0.

### CODE REVIEW

**Comment by seisman** [comment]
GMT 6.2.0 can be successfully compiled on ARM. Could anyone please enable ARM bottom for this formula?

**Comment by cho-m** [comment]
Is `pcre2` supported?

If so, it would be better to update the lines:
- `depends_on "pcre"`
- `-DPCRE_ROOT=#{Formula["pcre"].opt_prefix}`

**Comment by seisman** [comment]
> Is `pcre2` supported?
> 
> If so, it would be better to update the lines:
> 
> * `depends_on "pcre"`
> * `-DPCRE_ROOT=#{Formula["pcre"].opt_prefix}`

Yes, GMT supports `pcre2`. I made the change in commit 7a1cf4f7605df72d1180631e803ffd219744c316.

**Review by cho-m — APPROVED** [review]
Thanks, @seisman

**Pull request closed without merging**
