### PR TITLE
haskell-stack: rebuild with GHC 9.2.7

### PR DESCRIPTION
**Pull request by elopez**
GHC 9.2.5 (the previous release used to build `haskell-stack`) is affected by a GMP issue (https://gitlab.haskell.org/ghc/ghc/-/issues/22497) which causes Stack to frequently crash with SIGBUS. A fix has been provided starting on GHC 9.2.6.

-----

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
This looks like something already fixed in Homebrew `gmp`:

https://github.com/Homebrew/homebrew-core/blob/2e2b60628dd7f483b708f5b2ec25be7b50609e03/Formula/gmp.rb#L45-L49

I wonder if we should be using our GMP with GHC instead. CC @cho-m for thoughts here.

**Comment by cho-m** [comment]
> I wonder if we should be using our GMP with GHC instead. CC @cho-m for thoughts here.

As I recall, the issue with dynamically linking GMP (and libffi) was the excessive linkage for anything built with GHC. It would cause all dependents with build-only GHC dependency to require a GMP dependency even if unused.

This was still the case the last time I tried switching to dynamic linkage. Not sure about Linux as Ubuntu might default to linker flags like `--as-needed`.

**Comment by elopez** [comment]
Hi all! Can we merge this package rebuild in the meantime?

**Comment by p-linnane** [comment]
Rebased and will merge after CI finishes.

cc @woodruffw

**Comment by ZhongRuoyu** [comment]
```
  src/Stack/Config.hs:92:1: error:
      Could not find module ‘System.PosixCompat.User’
      Perhaps you meant
        System.PosixCompat.Files (from unix-compat-0.7)
        System.PosixCompat.Temp (from unix-compat-0.7)
        System.PosixCompat.Time (from unix-compat-0.7)
      Use -v (or `:set -v` in ghci) to see a list of the files searched for.
     |
  92 | import           System.PosixCompat.User ( getEffectiveUserID )
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Error: cabal: Failed to build stack-2.9.3. See the build log above for
  details.
```

The `System.PosixCompat.User` module was removed in `unix-compat-0.7` ([changelog](https://hackage.haskell.org/package/unix-compat-0.7/changelog)). Also seen previously in #127002.

**Review by carlocab — APPROVED** [review]

**Comment by elopez** [comment]
Thank you everyone! 😄

**Pull request merged**
