### PR TITLE
olsrd 0.9.6.1

### PR DESCRIPTION
**Pull request by nijikon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Build fails on 10.11, and test fails on 10.10 and 10.12.

**Comment by ilovezfs** [comment]
@nijikon what's the status here?

**Comment by fxcoudert** [comment]
Upstream's [webpage](http://www.olsr.org/mediawiki/index.php/Releases) still has 0.9.0.3 as the latest release. Should we close this?

**Comment by ilovezfs** [comment]
It would be good to file an issue here https://github.com/OLSR/olsrd/issues to ask whether that is correct or not.

**Comment by JCount** [comment]
This is probably provides a definitive enough answer: https://github.com/OLSR/olsrdReleases

According to that repo, the current release is actually `v0.9.6.2`.

**Comment by fxcoudert** [comment]
@JCount repo with 0 stars, 0 forks? hum…

**Comment by JCount** [comment]
@fxcoudert It is the release repo, and this is the first release they have used it for. It is not the development repository... Why would there be forks of it?

**Pull request closed without merging**
