### PR TITLE
shadowsocks-libev 2.5.3

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
@ilovezfs Let the `clock_gettime` fun begin: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8066/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_shadowsocks_libev/

**Comment by haodong** [comment]
@zmwangx I tested OK on my El Capitan.
This failure log indicates that there's something wrong on the port of testing platform.

**Comment by zmwangx** [comment]
Certainly not.

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/shadowsocks-libev/2.5.3/bin/ss-server
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/shadowsocks-libev/2.5.3/bin/ss-server
  Expected in: /usr/lib/libSystem.B.dylib

 2016-09-21 17:48:09 INFO: initializing ciphers... table
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/shadowsocks-libev/2.5.3/bin/ss-local
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/shadowsocks-libev/2.5.3/bin/ss-local
  Expected in: /usr/lib/libSystem.B.dylib

```

Rest assured, this is a signature Xcode 8 problem and we know it. You probably haven't upgraded to Xcode 8.

**Comment by haodong** [comment]
OK.
Actually, I did not have Xcode installed, just command-line. So, what should we do next?

**Comment by zmwangx** [comment]
Just patiently wait for our Xcode 8 expert (whom I pinged above), thanks.

**Comment by ilovezfs** [comment]
Choices
```
if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
  ENV["ac_have_clock_syscall"] = "no"
end
```
or
```
if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
    inreplace "configure", "unset ac_cv_func_clock_gettime",
                           "unset ac_cv_func_clock_gettime_no_thanks"
end
```

**Comment by haodong** [comment]
@zmwangx What should we do now?

**Comment by zmwangx** [comment]
I believe this should be fixed now.

@BrewTestBot Test this please.

**Comment by zmwangx** [comment]
Merged as 6a6558c. Thank you for your contribution to Homebrew! And thanks for bearing with us.

**Pull request closed without merging**
