### PR TITLE
hdf5@1.8 (import from homebrew/science)

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Basically it is a copy of the current `hdf5` formula, with just the name change + url/sha256 change + & change in one of the in replace statements + `keg_only :versioned_formula`.

I think it makes sense to host it in core, as `hdf5` is here too. There seem to be still some downloads from our users. And I will probably have 1 or 2 formulae in science that will need it.

**Comment by iMichka** [comment]
Companion PR in science: https://github.com/Homebrew/homebrew-science/pull/6120

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
thanks!

**Pull request closed without merging**
