### PR TITLE
onetime 2.0.15 (devel)

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Test failing on El Cap: https://bot.brew.sh/job/Homebrew%20Core/12084/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test___devel_onetime/

**Comment by DomT4** [comment]
Oh joy, Python-based errors 🙈. Not sure why that's failing, to be honest, especially when Yosemite passes.

**Comment by ilovezfs** [comment]
It's not reproducible on demand as far as I can tell. But this is what can happen when a test generates its input with /dev/random :)

**Comment by DomT4** [comment]
Could always use Ruby's PRNG to generate a slightly more predictable/sane random output, or we could write a garbage file to use as the random source, which for testing purposes I guess doesn't really have to be cryptographically secure.

**Comment by ilovezfs** [comment]
I ran it a few times and it occurred. Here's an input file that triggers it

[pad_data.txt.zip](https://github.com/Homebrew/homebrew-core/files/614293/pad_data.txt.zip)

**Comment by ilovezfs** [comment]
```
$ openssl dgst -sha256 pad_data.txt
SHA256(pad_data.txt)= 6c4f1ed861faae5badf91855371cd4dad4a1fb2d9e3c963ef7b577deaec89b54
```

**Comment by DomT4** [comment]
Even with that can't get it to reproduce on Sierra here. Maybe El Cap's Python has a bug or something. I don't know. Any preference over PRNG or explicitly written garbage?

**Comment by ilovezfs** [comment]
Reproduces on Sierra too
```
Josephs-Mac:rand joe$  onetime -e --pad=pad_data.txt --no-trace --config=. input.txt
Traceback (most recent call last):
  File "/usr/local/bin/onetime", line 1923, in <module>
    main()
  File "/usr/local/bin/onetime", line 1841, in main
    result = encoder.finish()
  File "/usr/local/bin/onetime", line 1493, in finish
    remainder += self.pad_sess.finish()
  File "/usr/local/bin/onetime", line 1424, in finish
    remainder += self._make_fuzz(self._tail_fuzz_length)
  File "/usr/local/bin/onetime", line 1105, in _make_fuzz
    ret_data = ret_data + chr(ord(rnd_data[i]) ^ ord(pad_data[i]))
IndexError: string index out of range
Josephs-Mac:rand joe$
```

**Comment by DomT4** [comment]
```
~> /usr/bin/env python --version
Python 2.7.10
~> touch input.txt
~> onetime -e --pad=pad_data.txt --no-trace --config=. input.txt
~> $?
0
```
😢

**Comment by ilovezfs** [comment]
do you have the real input.txt there?

**Comment by DomT4** [comment]
Ah, that broke it for me 👍.

**Comment by DomT4** [comment]
I was using `touch` instead of `echo` because I'm lazy.

**Comment by ilovezfs** [comment]
Interestingly it's a regression from the stable version, at least for that input file. So it should be bisectable.

**Comment by DomT4** [comment]
Seems to be a regression from even 2.0.13, which I can't reproduce this problem with.

**Comment by ilovezfs** [comment]
nice. that narrows it down!

**Comment by DomT4** [comment]
https://github.com/kfogel/OneTime/commit/76c46de2efdd651846758e419f2ef35743b5968a

**Comment by ilovezfs** [comment]
lol. does it apply cleanly?

**Comment by DomT4** [comment]
That's not the fix, that's the breakage apparently. Breakage is still there in master.

**Comment by ilovezfs** [comment]
Yikes. Feel like reporting it? :innocent:

**Comment by DomT4** [comment]
Aye. Was gonna see if I could narrow it down to a specific line given a lot of the changes there are code comments, but maybe easier to just report the commit & explain the breakage without poking at it too much given my less-than-fond relationship with Python.

**Comment by ilovezfs** [comment]
Yeah, I'd let upstream fix this nonsense.

**Comment by DomT4** [comment]
https://github.com/kfogel/OneTime/issues/26

**Comment by ilovezfs** [comment]
@DomT4 thanks! may want to correct `/dev/null` to `/dev/random` :)

**Comment by DomT4** [comment]
Crap. Long week 😓. Thanks for spotting that.

**Comment by ilovezfs** [comment]
You're welcome :)

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
@fxcoudert 👍

**Comment by DomT4** [comment]
Upstream has vanished, happens every so often, but they usually return with a wad of sudden activity at some point. I'd be tempted to just leave this formula where it is for now; I can't explain why it would suddenly be passing CI unless the initial failure is random.

**Comment by ilovezfs** [comment]
It is random remember?

**Comment by DomT4** [comment]
I thought it was pretty consistent on CI? I don't know. I can't remember last week, so, this PR is a stretch 🙈

**Comment by ilovezfs** [comment]
It's reproducible with given broken input, but since we generate the input in the test with /dev/rand, you get success or failure depending on whether you stumble into a broken input or not.

**Comment by DomT4** [comment]
Cheers 👍. I forgot this PR existed to be honest, so, remembering what happened here without re-reading the thread wasn't going to be a strong point 😓.

**Comment by ilovezfs** [comment]
Heh no problem. You're not responsible for the process snafu above.

**Pull request closed without merging**
