### PR TITLE
gox 0.4.0 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @DomT4

### CODE REVIEW

**Comment by ilovezfs** [comment]
I've asked whether iochan can be vendored at some point here https://github.com/mitchellh/gox/issues/101

**Review by DomT4 — APPROVED** [review]
Agree getting `iochan` vendored would be a big 👍 but this is a significant & positive change over the status quo.

**Comment by commitay** [comment]
@ilovezfs I've got PRs ready to submit after this is merged for the formulas that can depend on `gox`.

Hopefully I'm not duplicating work you've already done. 😆

**Comment by ilovezfs** [comment]
Shipped! Thanks for your contribution to Homebrew @ilovezfs!

@commitay nope, I haven't done that work yet. That would be great if you already have!

@DomT4 do you mind :+1: on https://github.com/mitchellh/gox/issues/101 :)

**Comment by DomT4** [comment]
Consider it done 😉

**Comment by DomT4** [comment]
> Shipped! Thanks for your contribution to Homebrew @ilovezfs!

😆 😆

**Comment by commitay** [comment]
> Shipped! Thanks for your contribution to Homebrew @ilovezfs!

🤣  

> nope, I haven't done that work yet. That would be great if you already have!

Cool, I'll check that they build locally with the bottle first and then submit them.

**Pull request closed without merging**
