### PR TITLE
go@1.7

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Knock on to #10320 to add go@1.7

### CODE REVIEW

**Review by ilovezfs — DISMISSED** [review]
I'd like to wait for https://github.com/Homebrew/homebrew-core/pull/10320 to be merged first.

**Review by JCount — APPROVED** [review]
Good work! @cblecker

**Comment by JCount** [comment]
Good work on this PR, and thank you for your patience @cblecker! 💯

**Comment by cblecker** [comment]
Glad to help!

**Pull request closed without merging**
