### PR TITLE
kops 1.8.0

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Created with `brew bump-formula-pr`.

As https://github.com/Homebrew/homebrew-core/pull/21302 bumps only devel, I also created this one to bump stable.

### CODE REVIEW

**Comment by afirth** [comment]
Hi @johanneswuerbach thanks for that, I thought about bumping that too but figured it might be good to give 1.8.0 a shakedown (I'm sure it will at kubecon), but I'm not a maintainer or anything. Anyway, this build will pass once #21302 is merged I think

**Review by KashifSaadat — APPROVED** [review]
LGTM

**Comment by StevenACoffman** [comment]
Test failures indicate:
> `devel version 1.8.0-beta.2 is older than stable version 1.8.0`

**Review by ilovezfs — CHANGES_REQUESTED** [review]
This needs to be rebased on master, and the devel block needs to be deleted entirely.

**Comment by johanneswuerbach** [comment]
Thanks @ilovezfs for the review, devel removed and rebased against master.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @johanneswuerbach! Shipped. :tada:

**Pull request closed without merging**
