### PR TITLE
okteto 1.7.4

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> brew test okteto --verbose
==> FAILED
Testing okteto
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200229-95122-6lr6s.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/okteto.rb --verbose
==> echo | okteto init --overwrite --file test.yml
Recommended image for development with ruby: okteto/ruby:2
Which docker image do you want to use for your development environment? [okteto/ruby:2]: 
 ✓  Okteto manifest (test.yml) created
Error: okteto: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <"name: okteto-test-20200229-95123-1y50n13\n" +
"image: okteto/ruby:2\n" +
"command:\n" +
"- bash\n" +
"workdir: /usr/src/app\n"> expected but was
<"name: okteto-test-20200229-95123-1y50n13\n" +
"image: okteto/ruby:2\n" +
"command:\n" +
"- bash\n" +
"workdir: /usr/src/app\n" +
"sshServerPort: 0\n">.

diff:
  name: okteto-test-20200229-95123-1y50n13
  image: okteto/ruby:2
  command:
  - bash
  workdir: /usr/src/app
+ sshServerPort: 0
```

**Comment by chenrui333** [comment]
new release with v1.8.0

**Comment by Bo98** [comment]
An extra line `sshServerPort: 0` just needs adding under the `workdir` in the test.

**Comment by chenrui333** [comment]
Should be fixed in this PR, https://github.com/Homebrew/homebrew-core/pull/51220 (tested locally).

**Pull request closed without merging**
