### PR TITLE
google-java-format: add google-java-format-diff

### PR DESCRIPTION
**Pull request by nakulj**
This script formats changed lines in a given patch.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
This looks to be a completely different tool that's just semantically related, I don't think this is the right approach.

**Comment by nakulj** [comment]
It's in the same repository as google-java-format and is documented there too.

From https://github.com/google/google-java-format#from-the-command-line:
Screen Shot 2021-08-02 at 12 50 52 PM

**Comment by SMillerDev** [comment]
After reading the link you send, I think we'll have to decline for the more important reason that it requires an unsupported python version.

**Comment by nakulj** [comment]
🤦  I've submitted https://github.com/google/google-java-format/pull/640 to update the python version.

**Pull request closed without merging**
