### PR TITLE
grib-api 1.19.0

### PR DESCRIPTION
**Pull request by jfsimoneau**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

grib-api 1.19.0

### CODE REVIEW

**Comment by woodruffw** [comment]
Holding off on merging this until the mirror reappears. Might be worth prodding upstream/the mirror owners in a few days if it doesn't happen on its own.

**Comment by ilovezfs** [comment]
@woodruffw the mirror is macports so we probably should open a PR to upgrade their port file if we want the mirror updated: https://github.com/macports/macports-ports/blob/master/science/grib_api/Portfile

If we're concerned about mirrors and don't want to do the MacPorts PR, we could switch over to the Debian mirrors' tarballs. They're .xz instead of .tar.gz so the checksum won't match (we'd just use them instead of the upstream link). Alternatively, we could just stick with the upstream tarball and hope it doesn't 404. The last option would be to use --mirror when pulling this and host our own tarball.

**Comment by woodruffw** [comment]
@ilovezfs I'll open a MacPorts PR, let's just go with Debian mirrors if they don't get around to it within a day or so.

**Comment by woodruffw** [comment]
macports/macports-ports#71 has the changes.

**Comment by ilovezfs** [comment]
:+1:

**Comment by woodruffw** [comment]
There hasn't been much movement from the MacPorts team on this (I was told that my bump was merged, but hasn't appeared in the tree...), so let's go ahead and switch to Debian here @jfsimoneau

**Comment by jfsimoneau** [comment]
I added the mirror link to Debian's package. When Takeshi Enomoto, the maintainer of grib-api on MacPorts, approves your pull request, I'll change it back to MacPorts so the checksum matches.

**Comment by ilovezfs** [comment]
Actually @woodruffw meant as a full replacement since the checksums must match or the tarball will be rejected by brew. I've updated and squashed the PR accordingly, as well as fixed the audit error.

**Comment by ilovezfs** [comment]
@jfsimoneau thanks for your contribution to Homebrew!

**Pull request closed without merging**
