### PR TITLE
rust 1.48

### LINKED ISSUE #63202: rust-1.47 contains mismatched tools
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
tbmbp:Homebrew admin$ brew gist-logs rust
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
tbmbp:Homebrew admin$ brew config
HOMEBREW_VERSION: 2.5.6-100-ga6ee5b7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a6ee5b79b06c39f5d43ae41a85004e773c04e019
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1163d23427690cfe4b498e197a2f72359bae2660
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_231, 1.8.0_31
macOS: 10.15.7-x86_64
CLT: N/A
Xcode: 12.0.1
XQuartz: 2.7.11 => /opt/X11
```
```
tbmbp:Homebrew admin$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

Trying to build Firefox nightly, which now requires Rust 1.47

## What happened (include command output)

configure fails complaining that cargo isn't new enough, and requires version 1.47

<details>
  <summary>Command output</summary>
  <pre>

tbmbp:Homebrew admin$ brew install rust
==> Downloading https://homebrew.bintray.com/bottles/rust-1.47.0.catalina.bottle.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/30d7cc7ba65e5799e9515db1996d1a0a2cb7ec546ee365f3252e6292705ba4c9--rust-1.47.0.catalina.bottle.tar.gz
==> Pouring rust-1.47.0.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/rust/1.47.0: 12,057 files, 576.9MB
tbmbp:Homebrew admin$ ls -ld `which rustc`
lrwxr-xr-x  1 admin  wheel  31 Oct 21 02:30 /usr/local/bin/rustc -> ../Cellar/rust/1.47.0/bin/rustc
tbmbp:Homebrew admin$ rustc --version
rustc 1.47.0
tbmbp:Homebrew admin$ ls -ld `which cargo`
lrwxr-xr-x  1 admin  wheel  31 Oct 21 02:30 /usr/local/bin/cargo -> ../Cellar/rust/1.47.0/bin/cargo
tbmbp:Homebrew admin$ cargo --version
cargo 1.46.0
tbmbp:~ admin$ ls -ld `which rustdoc`
lrwxr-xr-x  1 admin  wheel  33 Oct 21 02:30 /usr/local/bin/rustdoc -> ../Cellar/rust/1.47.0/bin/rustdoc
tbmbp:~ admin$ rustdoc --version
rustdoc 1.47.0

  </pre>
</details>

## What you expected to happen

The utilities installed with rust are supposed to be version-locked to rust itself.  If I use rustup-init to install rust instead of using the homebrew package, I get matched versions, which implies something wasn't built right in the package (I can't guarantee that, but that's what it looks like)

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install rust
/usr/local/bin/cargo --version
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Picks up from https://github.com/Homebrew/homebrew-core/pull/65286.

Fixes https://github.com/Homebrew/homebrew-core/issues/63202 (hopefully).

## 10.14

| Done? | Formula           | CI failure   | Comment                                       |
| ---   | ---               | ---          | ---                                           |
| ✅       | cargo-instruments | `install -s` | SHA256 mismatch (https://github.com/cmyr/cargo-instruments/issues/27, https://github.com/Homebrew/homebrew-core/pull/66872)                              |
| ✅       | deno              | `install -s` | #66482                                        |
| ✅       | findomain         | `install -s` | SHA256 mismatch (https://github.com/Findomain/Findomain/issues/121)                               |
| ✅       | ktmpl             | `test`       | https://github.com/jimmycuadra/ktmpl/issues/5, fixed in https://github.com/Homebrew/homebrew-core/pull/66914 |
|       | root              | `install -s` | connection failure                            |
| ✅       | silicon           | `install -s` | SHA256 mismatch, waiting for upstream response                               |
| ✅       | simgrid           | `install -s` | bad build script                              |

## 10.15

| Done? | Formula   | CI failure   | Comment                                      |
| ---   | ---       | ---          | ---                                          |
| ✅       | findomain | `install -s` | SHA256 mismatch (https://github.com/Findomain/Findomain/issues/121)                             |
|       | ktmpl     | `test`       | htps://github.com/jimmycuadra/ktmpl/issues/5, fixed in https://github.com/Homebrew/homebrew-core/pull/66914 |
|       | root      | `install -s` | connection failure                           |
| ✅       | silicon   | `install -s` | SHA256 mismatch, waiting for upstream response                              |
| ✅       | simgrid   | `install -s` | bad build script                             |

## 11.0

All `install --build-from-source` except for asuka (`test`), ktmpl (`test`), root (both - !)

| Done? | Formula           | CI failure           | Comment                                       |
| ---   | ---               | ---                  | ---                                           |
|       | asuka             | `test`               | `pty` allocation?, https://github.com/Homebrew/homebrew-core/issues/66450, https://github.com/Homebrew/homebrew-core/issues/65000                             |
| ✅       | cargo-instruments | `install -s`         | SHA256 mismatch (https://github.com/cmyr/cargo-instruments/issues/27, https://github.com/Homebrew/homebrew-core/pull/66872)                              |
| ✅       | deno              | `install -s`         | #66482                                        |
|       | echoprint-codegen | `install -s`         | #65000                                        |
| ✅       | findomain         | `install -s`         | SHA256 mismatch (https://github.com/Findomain/Findomain/issues/121)                              |
| ✅       | ktmpl             | `test`               | https://github.com/jimmycuadra/ktmpl/issues/5, fixed in https://github.com/Homebrew/homebrew-core/pull/66914 |
|       | root              | `install -s`, `test` | connection failure?                           |
| ✅       | silicon           | `install -s`         | SHA256 mismatch, waiting for upstream response                               |
| ✅       | simgrid           | `install -s`         | bad build script                              |
|       | visp              | `install -s`         | #65000                                        |

All three SHA256 mismatches have been reported upstream. Links visible down the thread.

### CODE REVIEW

**Comment by carlocab** [comment]
Before (#65286), on 11.0:
```
Error: 11 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose asuka
brew install --build-from-source deno
brew install --build-from-source echoprint-codegen
brew install --build-from-source findomain
brew test --retry --verbose ktmpl
brew test --retry --verbose kubie
brew install --build-from-source root
brew test --retry --verbose root
brew install --build-from-source simgrid
brew install --build-from-source visp
```
After:
```
Error: 10 failed steps!
brew install --build-from-source echoprint-codegen
brew install --build-from-source findomain
brew install --build-from-source ocrmypdf
brew install --build-from-source silicon
brew install --build-from-source simgrid
brew install --build-from-source visp
brew test --verbose ktmpl
brew fetch --retry root --build-bottle --force
brew install --verbose --build-bottle root
brew audit root --online --git --skip-style
```
Not really sure it made things better...

**Comment by carlocab** [comment]
10.14
```
Error: 7 failed steps!
brew install --build-from-source cargo-instruments
brew install --build-from-source deno
brew install --build-from-source findomain
brew test --retry --verbose ktmpl
brew install --build-from-source root
brew install --build-from-source silicon
brew install --build-from-source simgrid
```

**Comment by carlocab** [comment]
Bizarrely, there is no sha256 mismatch error for `cargo-instruments` on 10.15:
```
Error: 5 failed steps!
brew install --build-from-source findomain
brew test --retry --verbose ktmpl
brew install --build-from-source root
brew install --build-from-source silicon
brew install --build-from-source simgrid
```

**Comment by carlocab** [comment]
I've diagnosed the `simgrid` build failure, and have found a local workaround. Upstream report here: https://framagit.org/simgrid/simgrid/-/issues/59

**Comment by carlocab** [comment]
11.0:
```
Error: 12 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose asuka
brew install --build-from-source cargo-instruments
brew install --build-from-source deno
brew install --build-from-source echoprint-codegen
brew install --build-from-source findomain
brew test --retry --verbose ktmpl
brew install --build-from-source root
brew test --retry --verbose root
brew install --build-from-source silicon
brew install --build-from-source simgrid
brew install --build-from-source visp
```

**Comment by carlocab** [comment]
This is the `root` failure:
```
==> brew install --build-from-source root
==> FAILED
==> Downloading https://root.cern.ch/download/root_v6.22.04.source.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "root"
Download failed: https://root.cern.ch/download/root_v6.22.04.source.tar.gz
```
Not sure why CI keeps failing to download these tarballs. I can fetch them locally just fine.

**Comment by carlocab** [comment]
I tested `asuka` locally. It seems to be trying to open a tty, which doesn't work on Big Sur? (Cf. https://github.com/Homebrew/homebrew-core/pull/66311)

<details><summary>Verbose Test Output</summary>
<p>

```sh
Error: asuka: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </# Project Gemini/> was expected to be =~
<"stty rows 80 cols 43\r\n" +
"env LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 TERM=xterm /usr/local/Cellar/asuka/0.8.1/bin/asuka\r\n" +
"clear:echotc: no such capability: cl\r\n" +
"This is the Z Shell configuration function for new users,\r\n" +
"zsh-newuser-install.\r\n" +
"You are seeing this message because you have no zsh startup files\r\n" +
"(the files .zshenv, .zprofile, .zshrc, .zlogin in the directory\r\n" +
"~).  This function can help you with a few settings that should\r\n" +
"make your use of the shell easier.\r\n" +
"\r\n" +
"You can:\r\n" +
"\r\n" +
"(q)  Quit and do nothing.  The function will be run again next time.\r\n" +
"\r\n" +
"(0)  Exit, creating the file ~/.zshrc containing just a comment.\r\n" +
"     That will prevent this function being run again.\r\n" +
"\r\n" +
"(1)  Continue to the main menu.\r\n" +
"\r\n" +
"--- Type one of the keys in parentheses --- \r\n" +
"Aborting.\r\n" +
"The function will be run again next time.  To prevent this, execute:\r\n" +
"  touch ~/.zshrc\r\n" +
"%                                                                              \r \r\rcarlocab@hermes ~ % \e[?2004htty rows 80 cols 43\e[?2004l\r\r\n" +
"tty: extra operand 'rows'\r\n" +
"Try 'tty --help' for more information.\r\n" +
"%                                                                              \r \r\rcarlocab@hermes ~ % \e[?2004henv LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 TERM=xterm /us\r<UTF-8 LANG=en_US.UTF-8 TERM=xterm /usr                                       \r<UTF-8 LANG=en_US.UTF-8 TERM=xterm /usr/local/Cellar/asuka/0.8.1/bin/asuka\e[?2004l\r\r\n" +
"\e[?1049h\e[1;24r\e(B\e[m\e[4l\e[?7h\e[?1h\e=\e[?1000h\e[39;49m\e[?25l\e[?1002h\e[39;49m\e[34m\e[44m\e[H\e[2J\e[30m\e[47m┌──────────────────────────────┤ \e[31m\e[47mAsuka Browser\e[30m\e[47m ├───────────────────────────────┐\e[2;1H│ ┌──────────────────────────────────────────────────────────────────────────┐ │\e[3;1H│ │\e[37m\e[40mWelcome to Asuka Gemini browser!         \e[30m\e[47m\e[33X\e[78G│ │\e[4;1H│ │\e[74X\e[78G│ │\e[5;1H│ │  Press g to visit an URL\e[49X\e[78G│ │\e[6;1H│ │  Press b to go to the previous URL\e[39X\e[78G│ │\e[7;1H│ │  Press B to show bookmarks\e[47X\e[78G│ │\e[8;1H│ │  Press a to add current URL to bookmarks\e[33X\e[78G│ │\e[9;1H│ │  Press q to exit\e[57X\e[78G│ │\e[10;1H│ │\e[74X\e[78G│ │\e[11;1H│ │\e[74X\e[78G│ │\e[12;1H│ │\e[74X\e[78G│ │\e[13;1H│ │\e[74X\e[78G│ │\e[14;1H│ │\e[74X\e[78G│ │\e[15;1H│ │\e[74X\e[78G│ │\e[16;1H│ │\e[74X\e[78G│ │\e[17;1H│ │\e[74X\e[78G│ │\e[18;1H│ │\e[74X\e[78G│ │\e[19;1H│ │\e[74X\e[78G│ │\e[20;1H│ │\e[74X\e[78G│ │\e[21;1H│ └──────────────────────────────────────────────────────────────────────────┘ │\e[22;1H│\e[78X\e[80G│\e[23;1H│            <Back (b)> <Go To URL (g)> <Bookmarks (B)> <Quit (q)>             │\e[24;1H└──────────────────────────────────────────────────────────────────────────────\e[?7l┘\e[?7h\e[1;47H\e[39;49m\e(B\e[m\e[34m\e[44m\e[H\e[2J\e[30m\e[47m┌──────────────────────────────┤ \e[31m\e[47mAsuka Browser\e[30m\e[47m ├───────────────────────────────┐\e[2;1H│ ┌──────────────────────────────────────────────────────────────────────────┐ │\e[3;1H│ │\e[37m\e[44mWelcome to Asuka Gemini browser!         \e[30m\e[47m\e[33X\e[78G│ │\e[4;1H│ │\e[74X\e[78G│ │\e[5;1H│ │  Press g to visit an URL\e[49X\e[78G│ │\e[6;1H│ │  Press b to go to the previous URL\e[39X\e">.
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:55:in `block in assert_block'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1631:in `_wrap_assertion'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:53:in `assert_block'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:543:in `block in assert_match'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1636:in `_wrap_assertion'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:533:in `assert_match'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/asuka.rb:46:in `block in <class:Asuka>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1871:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:504:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1870:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1869:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2116:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1863:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:42:in `<main>'
```

</p>
</details>

**Comment by carlocab** [comment]
@fxcoudert A single CI run for this PR takes about two days to complete. Given this, I was wondering what your thoughts were on my rebasing this against master to resolve conflicts and just to fix the remaining issues in separate PRs.

I've investigated all of the CI failures (and fixed about half of them). The remaining are:
| Formula | CI failure | Status |
| --- | --- | --- |
|silicon|SHA256 mismatch|Waiting for upstream response (https://github.com/Aloxaf/silicon/issues/141)|
|root|Connection failure, unable to fetch source|Cannot reproduce locally|
|ktmpl|test failure|https://github.com/jimmycuadra/ktmpl/issues/5|
|asuka|test failure (11.0)|https://github.com/Homebrew/homebrew-core/issues/65000, https://github.com/Homebrew/homebrew-core/issues/66450|
|echoprint-codegen|build failure (11.0)|https://github.com/Homebrew/homebrew-core/issues/65000|
|visp|build failure (11.0)|https://github.com/Homebrew/homebrew-core/issues/65000|
|pike|missing dependency|https://github.com/Homebrew/homebrew-core/pull/66285/commits/6b892c2622cbfc35756268f769aff5b50004427e, fix confirmed locally. cf. https://github.com/Homebrew/homebrew-core/pull/66555|

**Comment by fxcoudert** [comment]
@carlocab makes total sense. I've cancelled the current run, since it's useless to spend one more day on CI provided we can't merge it anyway. Feel free to rebase and ping me when you think it's ready.

**Comment by carlocab** [comment]
Sure. Happy to do that. One thing I'm still unsure about is the remaining SHA256 mismatch. Should I include the commit that fixes that with my next push? Or should I leave it out and fix it when upstream responds?

**Comment by fxcoudert** [comment]
Re `silicon` please leave it out, we can't merge until it's confirmed, and I don't want it to block this PR

**Comment by carlocab** [comment]
Done. Should be ready now.

**Comment by fxcoudert** [comment]
@carlocab we'll wait for the tests, so we can check nothing new is broken, and also importantly so we get the bottles built by CI

**Comment by carlocab** [comment]
Sure. Will ping you when tests are done.

I've broken off `silicon` into a separate PR: https://github.com/Homebrew/homebrew-core/pull/66903

**Comment by carlocab** [comment]
Ping @fxcoudert 

`deno` seems to have gotten broken again, but it's getting a version bump here: https://github.com/Homebrew/homebrew-core/pull/66920

My fix for `pike` didn't quite take, but that's because the CI node couldn't fetch the source. (Expired SSL cert.) I hope it's not a problem that it didn't get bottled here...

There also appear to have been some spurious failures, like
```
==> brew audit findomain --online --git --skip-style
==> FAILED
Error: GitHub Bad credentials:HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
```

If all if this is fine I think this one's ready.

**Comment by fxcoudert** [comment]
@carlocab thanks, merging

**Pull request closed without merging**
