### PR TITLE
youtube-dl 2016.06.27

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍, although Alex will likely fight you over the deps blank line separator in `head`.

**Comment by ilovezfs** [comment]
@DomT4 That's another one of those issues we should set a policy on like the rule governing the presence of a blank line between the top section and the head url.

**Comment by DomT4** [comment]
I do actually prefer it with the empty line between the initial block & dependencies, but I lost that vote amongst the maintainers before now & I wasn't going to die on a hill over that particularly issue. It still slightly bothers me stylistically, but ho hum.

**Comment by ilovezfs** [comment]
I guess I can see the argument for no blank line if there is exactly one `depends_on`, but otherwise it makes no sense in terms of consistency with how the general `depends_on`s are separated from what's above them with a blank line.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
