### PR TITLE
neo4j 3.0.0

### PR DESCRIPTION
**Pull request by dgem**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

Change the JDK dependency to 1.8. Users also need to set a NEO4J_HOME env var

### CODE REVIEW

**Comment by dgem** [comment]
Very happy to take feedback as this is the first time I've tried modifying a formula

**Comment by DomT4** [comment]
The test is failing for some reason:
```
==> /usr/local/Cellar/neo4j/3.0.0/bin/neo4j status
/usr/local/Cellar/neo4j/3.0.0/bin/neo4j: line 219: cd: logs: No such file or directory
Error: neo4j: failed
<3> expected but was
<1>.
```

Looks okay to me otherwise, though. Is Java 1.7 no longer supported by the upstream project?

**Comment by dgem** [comment]
Hi @DomT4 
You need to do an export NEO4J_HOME=#{libexec} as per the brew info
I couldn't see a way to get around this change :(
Re Java version... they now require JDK 1.8 (http://neo4j.com/docs/operations-manual/current/#deployment-requirements)
I was wondering if brew should support both NEO4J V2 and V3 or does it typically only support the latest release ?

**Comment by DomT4** [comment]
> You need to do an export NEO4J_HOME=#{libexec} as per the brew info

Oh, fairly simply, thankfully. Add `ENV["NEO4J_HOME"] = libexec` inside the `test do` block.

We could perhaps do this for the executables themselves so users don't have to; something like:

```ruby
def install
  ENV["NEO4J_HOME"] = libexec
  
  # Remove windows files
  rm_f Dir["bin/*.bat"]

  # Install jars in libexec to avoid conflicts
  libexec.install Dir["*"]

  # Symlink binaries
  bin.install Dir["#{libexec}/bin/neo4j{,-shell,-import,-shared.sh, -admin}"]
  bin.env_script_all_files(libexec/"bin", :NEO4J_HOME => ENV["NEO4J_HOME"])

  # Adjust UDC props
  # Suppress the empty, focus-stealing java gui.
  (libexec/"conf/neo4j-wrapper.conf").append_lines <<-EOS.undent
    wrapper.java.additional=-Djava.awt.headless=true
    wrapper.java.additional.4=-Dneo4j.ext.udc.source=homebrew
  EOS
end
```

Might work. We do something similar for another formula [here](https://github.com/Homebrew/homebrew-core/blob/f6f748d5939eddfe6679efe2564b90ee5ac98d9b/Formula/nifi.rb).

**Comment by dgem** [comment]
Thanks @DomT4 that suggestion worked great

**Comment by DomT4** [comment]
Looks good to me. Nice work here.

Merged in https://github.com/Homebrew/homebrew-core/commit/0b661e3a0a24bba4689831d845e77830e7f2ba1d. Thank you for your contribution to Homebrew @dgem; we appreciate it! :smiley_cat:

**Comment by md5** [comment]
Looks like `neo4j-admin` is not being installed correctly. I've submitted a fix in https://github.com/Homebrew/homebrew-core/pull/814

**Pull request closed without merging**
