### PR TITLE
python*: add missing system tk cflags.

### LINKED ISSUE #34511: python@2: unable to import zlib when compiled on Mojave
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

https://gist.github.com/sashkab/f020a5bfe09b0e88fa9ef46cacdf472d

I've used slightly modified version of the python@2.rb formulae, only modification for this test was update revision from `1` to `2` and forced to build on macOS Mojave with the latest updates and latest CLT to compile Python 2.7 from source. Upon successful compilation, I was not able to import the zlib package:

```
$ /usr/local/Cellar/python@2/2.7.15_2/bin/python -c "import zlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named zlib
```

I've seen few resolved issues or accepted pull requests mentioning this, but didn't have a chance to dig deeper.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
As mentioned in https://github.com/Homebrew/homebrew-core/commit/a7e9375d1d521f05f70a3b71c78c3d2683c08471#r31441172.

Fixes #34511

CC @chdiza

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
- Given that not finding zlib has happened before, and leads to rather unusable Python, could we add a test that does `system "#{bin}/python#{xy}", "-c", "import zlib"`?

- Given that we do not offer to build with brewed tcl/tk, I think the Tk caveats (which only applies to Snow Leopard) should be removed

**Comment by MikeMcQuaid** [comment]
@fxcoudert Good call, done.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Tkinter does not build:

```
11:50:30 ==> /usr/local/Cellar/python@2/2.7.15_1/bin/python -c import Tkinter; root = Tkinter.Tk()
11:50:30 Traceback (most recent call last):
11:50:30   File "<string>", line 1, in <module>
11:50:30   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
11:50:30     import _tkinter # If this fails your Python may not be configured for Tk
11:50:30 ImportError: No module named _tkinter
11:50:30 Error: python@2: failed
```

nor does zlib

**Comment by fxcoudert** [comment]
zlib failure was reported here: 34511

**Comment by MikeMcQuaid** [comment]
> The lines have gone missing again:

@fxcoudert They were intentionally removed because the previous build still didn't pass the `zlib` test. I'll add them back, though, as this is now breaking even more stuff than before :sob:.

**Comment by fxcoudert** [comment]
I'm wondering if we should revert e7ce9fef918bcebef2373b410fe4105ae9a7b410
I think @mistydemeo understands this better than I do

**Comment by sashkab** [comment]
On macOS 10.14, zlib.h is in the `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/zlib.h`, so do we need to add something like this?

```ruby
      cflags << "-I#{MacOS.sdk_path}/usr/include"
```

**Comment by MikeMcQuaid** [comment]
I think the `/usr/include` bit is pointless because `if MacOS.sdk_path_if_needed` then `/usr/include` isn't the place we want to include `zlib` from anyway.

**Comment by sashkab** [comment]
Things I tried and didn't help:

```
      cflags << "-I#{MacOS.sdk_path}/usr/include"
      ldflags << "-L#{MacOS.sdk_path}/usr/lib"
```

Should we consider using brewed zlib?

**Comment by sashkab** [comment]
Can this be related to https://bugs.python.org/issue25136?

**Comment by MikeMcQuaid** [comment]
> Should we consider using brewed zlib?

This should be a last resort.

> Can this be related to https://bugs.python.org/issue25136?

That hasn't had any activity in several years so I doubt it.

**Comment by MikeMcQuaid** [comment]
Have pushed a version that's working for me locally for both `python` and `python@2` on Mojave.

**Comment by sashkab** [comment]
It didn't build zlib on my system. `configure` found `checking for inflateCopy in -lz... yes`, but while building, `setup.py` was not able to find `zlib.h` in include dirs, therefore added it into `missing`.

**Comment by fxcoudert** [comment]
@MikeMcQuaid This PR would restore bottles with working `zlib`, so I'd say we merge it.

@sashkab can you please open an issue (or pull request) for your issue? We will need to debug this, and improve the flags we pass.

**Comment by fxcoudert** [comment]
Done!

**Comment by MikeMcQuaid** [comment]
Thanks @fxcoudert! 👏🏻❤️

**Comment by sashkab** [comment]
> @sashkab can you please open an issue (or pull request) for your issue? We will need to debug this, and improve the flags we pass.

See #34549

**Pull request closed without merging**
