### PR TITLE
prometheus 2.0.0

### PR DESCRIPTION
**Pull request by lukasmalkmus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lukasmalkmus** [comment]
This is my first PR to a brew formula ever and I just noticed this one depends on `go`. Is there a reason for this? Binary distributions are are available on the release page as well.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by jibaku** [comment]
Does it make sense to extend the formula to make Prometheus available as a service ?

Please tell me if there are reasons not to do it, in the other case I can try to make a PR to provide this feature (as a first contribution)

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
```
==> brew install ./prometheus-2.0.0.el_capitan.bottle.tar.gz
==> brew test prometheus --verbose
==> FAILED
Testing prometheus
/usr/bin/sandbox-exec -f /tmp/homebrew20171109-63014-1dgil2h.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/prometheus.rb --verbose
==> /usr/local/Cellar/prometheus/2.0.0/bin/promtool check-rules /tmp/prometheus-test-20171109-63015-klt46t/rules.example
promtool: error: expected command but got "check-rules", try --help
Error: prometheus: failed
```

**Comment by lukasmalkmus** [comment]
@BrewTestBot test this please

**Comment by lukasmalkmus** [comment]
Previous test failed because the `check-rules` command has been renamed to `check rules` in promtool 2.0.

**Comment by lukasmalkmus** [comment]
And I also forgot to change the rule format, which is now yaml.

**Comment by lukasmalkmus** [comment]
@BrewTestBot test this please

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @lukasmalkmus! You're awesome :)

**Pull request closed without merging**
