### PR TITLE
duck 7.5.1

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?

It builds but prints the notorious `Failed changing dylib ID` warning. I suppose we will have to add the `OTHER_LDFLAGS=-headerpad_max_install_names` flag for building this framework.

- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Don't know what to do about this error.
```
  * Formula duck contains deprecated SPDX licenses: ["GPL-3.0"].
```

### CODE REVIEW

**Comment by gromgit** [comment]
According to https://svn.cyberduck.io/trunk/LICENSE.txt and https://spdx.org/licenses/, the correct license ID seems to be `GPL-3.0-only`.

**Comment by dkocher** [comment]
> According to https://svn.cyberduck.io/trunk/LICENSE.txt and https://spdx.org/licenses/, the correct license ID seems to be `GPL-3.0-only`.

I cannot find any reference to `GPL-3.0` in our formula.

**Comment by gromgit** [comment]
There's a line right after the SHA256 checksum you changed:
```
  license "GPL-3.0"
```

**Comment by dkocher** [comment]
> There's a line right after the SHA256 checksum you changed:
> 
> ```
>   license "GPL-3.0"
> ```

Sure I missed that.

**Comment by dkocher** [comment]
Can you confirm the `Failed to fix install linkage` error is due to the missing `-headerpad_max_install_names` of the linked framework?

**Comment by gromgit** [comment]
Sorry, no idea. You'll have to try it for yourself.

**Comment by dkocher** [comment]
> Can you confirm the `Failed to fix install linkage` error is due to the missing `-headerpad_max_install_names` of the linked framework?

Confirmed this is caused by failing to run `install_name_tool -id` which gives the error `…because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)`

**Pull request closed without merging**
