### PR TITLE
makensis: pass compiler as SCons arguments

### PR DESCRIPTION
**Pull request by idleberg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR removes the patching of `SCons/config.py` and passes the compiler to SCons as arguments instead

### CODE REVIEW

**Comment by idleberg** [comment]
@ilovezfs Is this the error below something known on your end? It not only occurs with this PR, but also when I try to install the master.

```
==> Downloading https://downloads.sourceforge.net/project/libpng/zlib/1.2.8/zlib128-dll.zip
Already downloaded: /Users/jan/Library/Caches/Homebrew/downloads/bd348774a814a3084315316c1e2178768167e9f964926a18ef7c8284a5a21607--zlib128-dll.zip
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:54:in `reinstall_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:25:in `block in reinstall'
	from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:19:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:19:in `reinstall'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: An exception occured within a build process:
  Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /private/tmp/d20180908-43202-1803zfz
```

**Comment by reitermarkus** [comment]
I think I had a similar error once. It was somewhere deep inside a stdlib function, but cannot remember what was the cause. I think the backtrace for `Errno::ENOTEMPTY` would be more helpful than the one for `Errno::EPIPE`.

**Comment by idleberg** [comment]
>  I think the backtrace for `Errno::ENOTEMPTY` would be more helpful than the one for `Errno::EPIP`.

The piece of the log I posted is taken from Jenkins: 

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/30154/version=high_sierra/console

**Comment by DomT4** [comment]
I pulled this locally to get the fuller version.

```
==> Verifying bd348774a814a3084315316c1e2178768167e9f964926a18ef7c8284a5a21607--zlib128-dll.zip checksum
unzip /usr/local/var/homebrewcache/downloads/bd348774a814a3084315316c1e2178768167e9f964926a18ef7c8284a5a21607--zlib128-dll.zip -d /private/tmp/d20180908-30807-2gfi2i
cp -pR /private/tmp/d20180908-30807-2gfi2i/test/. /private/tmp/makensis--zlib-win32-20180908-30807-1l3yn7q/test
cp -pR /private/tmp/d20180908-30807-2gfi2i/include/. /private/tmp/makensis--zlib-win32-20180908-30807-1l3yn7q/include
cp -pR /private/tmp/d20180908-30807-2gfi2i/zlib1.dll /private/tmp/makensis--zlib-win32-20180908-30807-1l3yn7q/zlib1.dll
cp -pR /private/tmp/d20180908-30807-2gfi2i/lib/. /private/tmp/makensis--zlib-win32-20180908-30807-1l3yn7q/lib
cp -pR /private/tmp/d20180908-30807-2gfi2i/DLL_FAQ.txt /private/tmp/makensis--zlib-win32-20180908-30807-1l3yn7q/DLL_FAQ.txt
cp -pR /private/tmp/d20180908-30807-2gfi2i/README.txt /private/tmp/makensis--zlib-win32-20180908-30807-1l3yn7q/README.txt
cp -pR /private/tmp/d20180908-30807-2gfi2i/USAGE.txt /private/tmp/makensis--zlib-win32-20180908-30807-1l3yn7q/USAGE.txt
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1452:in `unlink'
Errno::EACCES: Permission denied @ unlink_internal - /private/tmp/d20180908-30807-2gfi2i/test/example_d.exe
```

**Comment by idleberg** [comment]
@DomT4 Can you install the makensis formula from master?

**Comment by DomT4** [comment]
@idleberg Same error, which is expected here, IMO.

**Comment by idleberg** [comment]
> @idleberg Same error, which is expected here, IMO.

So the question is why it worked for #23471

**Comment by DomT4** [comment]
It'll be a change we've made to the way things are unpacked, I suspect. We've _(well, Markus)_ has done a lot of great work cleaning up & restructuring things around that, but as ever with major changes you walk into some edge cases sometimes. Suspect this is one of those.

**Comment by idleberg** [comment]
Alright then, I'll sit still and hopefully it will work in the near future. I got a couple of further changes on my mind.

**Comment by fxcoudert** [comment]
I've opened a `brew` bug report about this issue: https://github.com/Homebrew/brew/issues/4910

**Comment by idleberg** [comment]
Just for the record: as of today, the error has changed:

```sh
unzip /Users/jan/Library/Caches/Homebrew/downloads/bd348774a814a3084315316c1e2178768167e9f964926a18ef7c8284a5a21607--zlib128-dll.zip -d /private/tmp/d20180929-18238-1p4o2mx
cp -pR /private/tmp/d20180929-18238-1p4o2mx/test/. /private/tmp/makensis--zlib-win32-20180929-18238-rwk3t4/test
cp -pR /private/tmp/d20180929-18238-1p4o2mx/include/. /private/tmp/makensis--zlib-win32-20180929-18238-rwk3t4/include
cp -pR /private/tmp/d20180929-18238-1p4o2mx/zlib1.dll /private/tmp/makensis--zlib-win32-20180929-18238-rwk3t4/zlib1.dll
cp -pR /private/tmp/d20180929-18238-1p4o2mx/lib/. /private/tmp/makensis--zlib-win32-20180929-18238-rwk3t4/lib
cp -pR /private/tmp/d20180929-18238-1p4o2mx/DLL_FAQ.txt /private/tmp/makensis--zlib-win32-20180929-18238-rwk3t4/DLL_FAQ.txt
cp -pR /private/tmp/d20180929-18238-1p4o2mx/README.txt /private/tmp/makensis--zlib-win32-20180929-18238-rwk3t4/README.txt
cp -pR /private/tmp/d20180929-18238-1p4o2mx/USAGE.txt /private/tmp/makensis--zlib-win32-20180929-18238-rwk3t4/USAGE.txt
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1452:in `unlink'
Errno::EACCES: Permission denied @ unlink_internal - /private/tmp/d20180929-18238-1p4o2mx/test/example_d.exe
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1452:in `unlink'
Errno::EACCES: Permission denied @ unlink_internal - /private/tmp/d20180929-18238-1p4o2mx/test/minigzip_d.exe
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `rmdir'
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /private/tmp/d20180929-18238-1p4o2mx/test
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1452:in `unlink'
Errno::EACCES: Permission denied @ unlink_internal - /private/tmp/d20180929-18238-1p4o2mx/include/zlib.h
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1452:in `unlink'
Errno::EACCES: Permission denied @ unlink_internal - /private/tmp/d20180929-18238-1p4o2mx/include/zconf.h
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `rmdir'
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /private/tmp/d20180929-18238-1p4o2mx/include
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1452:in `unlink'
Errno::EACCES: Permission denied @ unlink_internal - /private/tmp/d20180929-18238-1p4o2mx/lib/zdll.lib
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1452:in `unlink'
Errno::EACCES: Permission denied @ unlink_internal - /private/tmp/d20180929-18238-1p4o2mx/lib/zlib.def
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `rmdir'
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /private/tmp/d20180929-18238-1p4o2mx/lib
...
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `rmdir'
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /private/tmp/d20180929-18238-1p4o2mx
```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please
@idleberg the unpack issue should be fixed now

**Comment by idleberg** [comment]
The error from the [Mojave log](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/31155/version=mojave_testing/console) appears to be temporary problem, both URLs work fine for me:

```
11:22:48 ==> brew audit makensis --online
11:23:53 ==> FAILED
11:23:53 Error: 2 problems in 1 formula detected
11:23:53 makensis:
11:23:53   * Stable resource "nsis": The URL https://downloads.sourceforge.net/project/nsis/NSIS%203/3.03/nsis-3.03.zip is not reachable
11:23:53   * Stable resource "zlib-win32": The URL https://downloads.sourceforge.net/project/libpng/zlib/1.2.8/zlib128-dll.zip is not reachable
```

Not sure what to make of the [High Sierra log](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/31155/version=high_sierra/console) though.

**Comment by fxcoudert** [comment]
- CI issues, no problem.
- Can we take this opportunity to remove the options? Nobody is using them, and Homebrew is trimming down options across the board #31510

```
install events in the last 90 days
================================================================================
1 | makensis                                                     | 315 | 100.00%
================================================================================
```

**Comment by idleberg** [comment]
> Can we take this opportunity to remove the options? Nobody is using them, and Homebrew is trimming down options across the board #31510

I was actually planning to add more options, but if nobody is using them, it probably makes more sense to remove them. I didn't know about taps until I read through the issue. I might maintain one that keeps the options.

**Comment by fxcoudert** [comment]
Thanks @idleberg for the pull request!

**Pull request merged**
