### PR TITLE
Rollback apt-dater to v0.9.0

### PR DESCRIPTION
**Pull request by MikeLund**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Does not pass audit only because of "stable version should not decrease (from 1.0.3 to 0.9.0)".

Please see https://github.com/Homebrew/homebrew-core/pull/8924#issuecomment-273152828 for reason to rollback. Thanks.

### CODE REVIEW

**Comment by mbi** [comment]
Agreed, FWIW: 1.0.3 seems toxic at first sight.

**Comment by MikeMcQuaid** [comment]
0.9.0 is also marked as unstable so an earlier version seems like the best bet.

> Does not pass audit only because of "stable version should not decrease (from 1.0.3 to 0.9.0)".

That means it needs a `version_scheme` bump added.

If there's no stable version in over 5 years I think that somewhat implies this software isn't maintained and I'm unsure if we should be packaging it at all.

**Comment by nijikon** [comment]
Done.

**Comment by MikeMcQuaid** [comment]
Reverted in 2bdb07adaf as this needs a `version_scheme`, to be before 0.9.0 and discussion on whether it should be maintained by us at all.

**Comment by MikeLund** [comment]
I use apt-dater v0.9.0 every week with no issues. It serves its purpose and doesn't really need any changes. Apt doesn't really change much either, so I don't see this version breaking in the near-future. Thus I don't support removing it.

How would one use `version_scheme` by the way? Didn't see much description in the docs.

**Comment by MikeMcQuaid** [comment]
Add `version_scheme 1` to the formula.

**Comment by MikeLund** [comment]
@MikeMcQuaid thanks, please see new commit, passes audit now.

**Comment by MikeMcQuaid** [comment]
> 0.9.0 is also marked as unstable so an earlier version seems like the best bet.

To repeat myself more explicitly: given 0.9.0 is also listed as unstable I think it's either worth going on 0.8.6 or leaving the version as-is.

**Comment by MikeLund** [comment]
1. Changes from 0.9.0 from 0.8.6 didn't make any regressions, only added an optional feature (clustering) and fixed some bugs. The addition of clustering is why it gets tagged "unstable". Users can just not use that feature if doesn't work well for them, and us who like it can continue to use it.

2. Under this situation you propose (using 0.8.6), you will break the configs for people who use clustering from v9, and reintroducing bugs fixed in v9. There is no real benefit other than /saying/ the version is more stable.

3. 0.9.0 has been out and "unstable" since 2012. There is no major issue with it.


Stability-flags from an inactive hobby-project shouldn't be taken so strictly, especially when it "works" and has been around for so long. If I am missing the point, please explain it a bit better, because I simply do not understand how it helps any brewer to use a less-stable version of a software simply because it claims to be stable. Thanks much.

**Comment by MikeMcQuaid** [comment]
> Under this situation you propose (using 0.8.6), you will break the configs for people who use clustering from v9, and reintroducing bugs fixed in v9. There is no real benefit other than /saying/ the version is more stable.

> Stability-flags from an inactive hobby-project shouldn't be taken so strictly, especially when it "works" and has been around for so long.

I think both the above arguments could be made for this PR as a whole.

>  I simply do not understand how it helps any brewer to use a less-stable version of a software simply because it claims to be stable.

We either go by what upstreams claim to be stable or the latest released version. It feels strange to me to deliberately be on neither. When do we upgrade? What if there's a security vulnerability?

**Comment by MikeLund** [comment]
Yeah I mean normally I'd agree with that stability logic; no one wants to run unstable stuff without opting in to it. In a case where the project is dormant, I might be inclined for graveyard. But this version is fine. It's a simple userland utility. There is not much risk of security issues, it's mostly just a frontend to automate updating Debian packages.

But I'll stop trying to go around in circles. Merging 0.9.0 LGTM, but if that's unacceptable then using 0.8.6 would still be better than the 1.x mess. So let me know the final decision and I can test it out, thank you.

**Comment by MikeMcQuaid** [comment]
Went for 0.9.0. Thanks for the PR @MikeLund!

**Pull request closed without merging**
