### PR TITLE
awscli 1.16.290

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
We definitely need to get this conjure-up formula sorted at some point. It's a little bit annoying.

I don't have a Catalina machine to test it on at the moment so if I do anything it might have to be trial and error.

**Comment by chenrui333** [comment]
I am actually on a catalina machine, but i could not figure it out though.

**Comment by chenrui333** [comment]
I did add bunch of comments in the past PR, https://github.com/Homebrew/homebrew-core/pull/46001

**Comment by Bo98** [comment]
Actually does Juju even function on Catalina? Try run `juju version`.

**Comment by bayandin** [comment]
`juju` is broken on Catalina: 
```
panic: cannot determine host series: unknown series ""

goroutine 1 [running]:
github.com/juju/juju/vendor/github.com/juju/os/series.mustHostSeries(0x2540be400, 0x74fea40)
	/private/tmp/juju-20191123-70924-q8x0wz/juju-core_2.6.10/src/github.com/juju/juju/vendor/github.com/juju/os/series/series.go:50 +0x65
github.com/juju/juju/api.init()
	/private/tmp/juju-20191123-70924-q8x0wz/juju-core_2.6.10/src/github.com/juju/juju/api/certpool.go:19 +0x17f
```

Fixed in https://github.com/juju/juju/pull/10775 (will be released in version 2.7)

**Comment by bayandin** [comment]
And it seems I've managed to patch bundled dependency for juju to fix this problem: https://github.com/Homebrew/homebrew-core/pull/47078

**Comment by chenrui333** [comment]
Sounds great, let's see how it goes.

**Comment by chenrui333** [comment]
@Bo98, btw, this formula also depends_on "python", do we want to wait for the merge after python 3.8.0?

**Comment by Bo98** [comment]
Thanks - I missed this one!

Given some formulae was missing a revision bump when the current build started, it's looking like we'll probably be restarting the 3.8 build anyway so I think it's ok to merge. Just trying to keep track of it all just now.

Keep tagging pull requests as Python and that'll be useful!

**Pull request closed without merging**
