### PR TITLE
icu4c 70.1

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

Not yet officially announced yet, but it will be by the time we're ready with this.

### CODE REVIEW

**Comment by Bo98** [comment]
Linux linkage failures are awkward as they are checked recursively, which I'll try fix tomorrow before pushing.

**Comment by Bo98** [comment]
Plan for this is to do it after `openldap` is done, to avoid conflicts.

**Comment by SMillerDev** [comment]
OpenLDAP is finally merged, shall I rebase this?

**Comment by carlocab** [comment]
You still have a conflict for `tracker`

**Comment by Bo98** [comment]
Oh libsoup just got merged when I was rebasing it seems.

**Comment by carlocab** [comment]
Are any of these GCC dependents? If they are we may want to rebase this so we can attempt a bottle build when applicable.

**Comment by Bo98** [comment]
`ncmpcpp`.

`mapnik` too though that's not even on Intel Monterey yet.

**Comment by carlocab** [comment]
Only ones that show up for me (on `master`) as `ready to bottle` are `chakra`, `gjs`, `mysql`, `ncmpcpp`, `tarantool`, and `percon-server`.

Probably only `ncmpcpp` then, so not worth the rebase.

**Comment by Bo98** [comment]
I've got PRs open for most failures (last couple will be up in a bit).

I do not think it will be possible to revision bump `texlive` in this PR so I will likely drop it. Going forward we will need to consider splitting that formula to be manageable.

**Comment by SMillerDev** [comment]
@danielnachun I think we'll have to reduce the size of the installed packages for texlive. Is this something you could pick up?

**Comment by danielnachun** [comment]
> @danielnachun I think we'll have to reduce the size of the installed packages for texlive. Is this something you could pick up?

Definitely.  The reason the bottle is so big right now is because of the `texlive-texmf` resource.  I would propose that we rename the current formula to `texlive-bin` and remove the `texlive-texmf` resource.  Then we would make a `texlive-texmf` formula which just installs the `texlive-texmf` resource and symlinks it into the cellar path for `texlive-bin`.  This `texlive-texmf` formula would only depend on `texlive-bin` so it wouldn't get pulled into any dependent tests.

**Comment by danielnachun** [comment]
I think we were running out of space on macOS actually, though we should confirm that.

**Comment by cho-m** [comment]
> I think we were running out of space on macOS actually, though we should confirm that.

Ah. I do see Intel macOS is out of space now. Only checked Linux and ARM macOS.

**Comment by carlocab** [comment]
Since we're blocked on `texlive` here, I suggest dropping it from the PR for now and rebuilding it separately. `texlive` also does `uses_from_macos "icu4c"`, which should limit the impact of the breakage somewhat.

Otherwise, we should consider rebuilding `texlive` while restricting this line only to macOS:
https://github.com/Homebrew/homebrew-core/blob/ce2c42929bb5eecccc18fe2fc0723a137b47ceca/Formula/texlive.rb#L416

**Comment by danielnachun** [comment]
Let's drop `texlive` from the PR and revision bump it afterward.

**Comment by Bo98** [comment]
I'll rebase this without texlive but with qtwebengine 5.15.8 (to avoid a double revision bump) shortly.

**Comment by carlocab** [comment]
> Let's drop `texlive` from the PR and revision bump it afterward.

Great. We should also update `Net::SSLeay` to bottle it on Monterey too. And any other outdated resources too, to maximise what we get out of the rev bump.

**Comment by danielnachun** [comment]
> > Let's drop `texlive` from the PR and revision bump it afterward.
> 
> Great. We should also update `Net::SSLeay` to bottle it on Monterey too. And any other outdated resources too, to maximise what we get out of the rev bump.

Yes, that sounds good.

**Comment by carlocab** [comment]
Since we're rev-bumping `boost` here, we should apply this patch https://www.boost.org/patches/1_78_0/0001-b2-fix-install.patch

See the [release notes](https://www.boost.org/users/history/version_1_78_0.html).

**Comment by Bo98** [comment]
> Since we're rev-bumping `boost` here, we should apply this patch https://www.boost.org/patches/1_78_0/0001-b2-fix-install.patch
> 
> See the [release notes](https://www.boost.org/users/history/version_1_78_0.html).

Unless it affects the build of Boost itself, shouldn't this be applied to the `boost-build` formula instead?

**Comment by Bo98** [comment]
Looks like it might have affected our Boost, but I do think it should be applied to boost-build too (in a separate PR).

**Comment by carlocab** [comment]
Yes, I believe it affected our build of `boost`.

**Comment by Bo98** [comment]
This rolls in #90021 and #94881 to avoid unnecessary revision bumps and make best use of CI time.

**Comment by SMillerDev** [comment]
Can we roll in https://github.com/Homebrew/homebrew-core/pull/95386 too?

**Comment by Bo98** [comment]
Can do. Not sure if it's worth rerunning CI for it, but I'll definitely include it if we need a second run.

**Comment by carlocab** [comment]
Might also make sense to include #94072 here too.

**Comment by Bo98** [comment]
The other formulae in that PR seem light enough so it probably makes sense to do that.

**Comment by Bo98** [comment]
Avoiding merge conflicts here is a pain.

**Comment by SMillerDev** [comment]
When we think we're close we can just disable automerge for a day or so.

**Comment by Bo98** [comment]
I'm hoping this is it.

(PHP failure on 12-arm is a known random failure, but it's fine as we can dispatch a bottle for that after merge and people can use the 11-arm bottle in the small few minute window in between.)

**Comment by cho-m** [comment]
**11-arm64**
- Related failures:
  - [ ] `brew linkage --test easyrpg-player` - needs revision bump
  - [ ] `brew linkage --test boost@1.76` - needs revision bump
  - [ ] `brew linkage --test zk` - needs revision bump
  - [ ] `brew test --retry --verbose gedit` - `tepl` needs revision bump
- Unrelated failures (should be fixed outside this PR):
  - [ ] `brew test --retry --verbose zurl` - `python@3.10` prefix scheme issue (attempting to mkdir outside sandbox)

**Comment by Bo98** [comment]
> * `python@3.10` prefix scheme issue (attempting to mkdir outside sandbox)

This is probably a bug I need to fix (separately of course) - has there been any other cases of this?

**Comment by cho-m** [comment]
> > * `python@3.10` prefix scheme issue (attempting to mkdir outside sandbox)
> 
> This is probably a bug I need to fix (separately of course) - has there been any other cases of this?

#94696
#95399
#95529

**Comment by Bo98** [comment]
That's possibly impossible to solve without some changes upstream. Fedora has a similar issue: https://bugzilla.redhat.com/show_bug.cgi?id=2026979.

I did work around the issue for `pip`, so if you `--prefix` with that then it should work. That doesn't however apply to setuptools directly.

**Comment by cho-m** [comment]
ARM looks good (`zurl` can be ignored and was fixed in separate PR, `clickhouse-odbc` is due to CI conflict handling, and `texlive` is being dealt with outside PR).

Linux hit a build failure for `postgresql@10`. If I recall, this means dependents weren't tested, so there may be some other breakages not caught by CI.

**Comment by Bo98** [comment]
Looks like a sporadic error. `ENV.deparallelize` might have prevented it.

> If I recall, this means dependents weren't tested, so there may be some other breakages not caught by CI.

This is annoying because I was hoping to merge the Boost regression fix asap.

**Comment by carlocab** [comment]
> This is annoying because I was hoping to merge the Boost regression fix asap.

I agree. If you rebase it won't happen next time around: https://github.com/Homebrew/homebrew-core/pull/95440

Though, I don't mind risking the breakage if dependents are tested on Intel macOS and we're happy with the results. (Recognising that there are many more Linux dependents...)

**Review by SMillerDev — DISMISSED** [review]
I think these fixes are worth the potential breakage.

**Comment by Bo98** [comment]
I could possibly adapt `publish-commit-bottles.yml` to be able to (optionally) run on self-hosted?

**Comment by carlocab** [comment]
> I could possibly adapt `publish-commit-bottles.yml` to be able to (optionally) run on self-hosted?

Yes, please. The last two (three?) `icu4c` PRs couldn't be merged by a GitHub runner due to lack of memory.

Otherwise, I guess you could merge it manually.

**Comment by Bo98** [comment]
Testing stuff so this might get spammed a bit.

**Comment by carlocab** [comment]
Installing `gnupg` if needed sounds like it should be handled by the commit signing action?

**Comment by Bo98** [comment]
Probably yeah. It's quite large but if scoped to self-hosted (i.e. we run non-self-hosted outside the container) it'll be fine.

**Comment by Bo98** [comment]
I'm off for a few hours but if this works:

* Regenerate the Linux runner afterwards (even if it fails) - it seems like the home directory is not currently nuked between CI runs, which is a somewhat concerning from a security POV (this probably requires making the runner run as root to fix - or ephemeral). This will be fixed in some way before the next time we need to use this (it's only icu4c that should need this, right?).
* Dispatch a Linux build for `postrgesql@10`.

**Comment by Bo98** [comment]
> it seems like the home directory is not currently nuked between CI runs

Until ephemeral, I'll cover this scenario with https://github.com/Homebrew/actions/pull/262.

> Still can't find `unzip` for some reason.

Hopefully fixed by https://github.com/Homebrew/brew/pull/12947

**Comment by carlocab** [comment]
```
error: gpg failed to sign the data
error: failed to write commit object
```

**Comment by Bo98** [comment]
That error basically means "gpg didn't exit successfully", which is always fun to debug as it means absolutely anything and it's not reproducible in a local Docker container.

**Comment by Bo98** [comment]
Oh of course, it'll be because brew env filters GNUPGHOME.

**Comment by SMillerDev** [comment]
> Error: Bottles are for tectonic 0.8.0_1 but formula is version 0.8.1_1!

**Comment by carlocab** [comment]
```
Error: Bottles are for tectonic 0.8.0_1 but formula is version 0.8.1_1!
```
😭

**Comment by carlocab** [comment]
I suggest a manual merge while dropping `tectonic`. Let's just rebuild it after.

**Comment by carlocab** [comment]
Attempting a manual merge. Downloading the bottles now. Will warn before I start an upload attempt.

**Comment by carlocab** [comment]
I decided to leave the download going overnight. It's finished now, but I'll be on the road so will try an upload when I have a stable connection.

**Comment by carlocab** [comment]
Attempting upload.

**Comment by carlocab** [comment]
Merge conflict for `sile`. Dropping.

**Comment by Bo98** [comment]
We need a better way to "lock" formula or whatever. A significant amount of the pain here is because of conflicts.

ICU 71 will probably be out next month, and I'm up for coordinating the revision bumps for that again, but I just can't monitor every single PR which comes in while the build is happening.

**Comment by Bo98** [comment]
Maybe CODEOWNERS is the solution here.

**Comment by carlocab** [comment]
> We need a better way to "lock" formula or whatever. A significant amount of the pain here is because of conflicts.
> 
> ICU 71 will probably be out next month, and I'm up for coordinating the revision bumps for that again, but I just can't monitor every single PR which comes in while the build is happening.

Agreed. I tried to monitor PRs too, but I can't watch this repo 24/7 and `tectonic` and `sile` were merged while I was away.

> Maybe CODEOWNERS is the solution here.

This sounds like a good idea, actually. Is there a way to make code owner review mandatory only for specific files?

**Comment by Bo98** [comment]
> Is there a way to make code owner review mandatory only for specific files?

In terms of GitHub branch protection? No, but we could make `pr-pull` fail without a code owner review for any formula file, overridable by an argument that can be passed to `pr-publish` too.

**Comment by Bo98** [comment]
Or actually it maybe doesn't even need to be that complicated-  it probably only needs to be on autopublish level

**Comment by carlocab** [comment]
> Or actually it maybe doesn't even need to be that complicated - it probably only needs to be on autopublish level

If we could automatically label those PRs with `do not merge` too that might be useful, in case some maintainer wonders why a PR they approved hasn't been auto-merged and decides to `pr-publish` it.

**Comment by Bo98** [comment]
Makes sense. I would maybe lean on a separate red label just to make it more obvious to the PR author what's going on rather than getting a random "do not merge" label immediately.

**Comment by carlocab** [comment]
> Makes sense. I would maybe lean on a separate red label just to make it more obvious to the PR author what's going on rather than getting a random "do not merge" label immediately.

Sure, I'm fine with that too.

**Pull request closed without merging**
