### PR TITLE
sdl2 2.24.1

### PR DESCRIPTION
**Pull request by FtZPetruska**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Error: The `brew link` step did not complete successfully
  Could not symlink bin/playsound
  Target /opt/homebrew/bin/playsound
  is a symlink belonging to sdl_sound. You can unlink it:
    brew unlink sdl_sound
```

**Comment by FtZPetruska** [comment]
This doesn't  seem to be an issue with `sdl2` itself but rather a conflict between `sdl_sound` and `sdl2_sound` where they both provide the `playsound` binary. Should the latter two be marked as `conflicts_with` each other ?

**Comment by carlocab** [comment]
We could also make `sdl_sound` keg-only (in a separate PR, please). Do any formulae still depend on it? (On mobile atm, so not easy to check.)

**Comment by FtZPetruska** [comment]
> We could also make `sdl_sound` keg-only (in a separate PR, please). Do any formulae still depend on it? (On mobile atm, so not easy to check.)

It seems only `dosbox` has a dependency on `sdl_sound`. Additionally, `qtads` uses `Formula["sdl_sound"].opt_include` without declaring a dependency on the formula.

> Alternatively, we can rename or delete the executables from `sdl_sound`, since everyone likely installs it for the libraries.

It seems that `playsound` is meant as an example/test program. It can be disabled for `sdl2_sound` by setting the CMake variable`SDLSOUND_BUILD_TEST` to off, but there doesn't seem to be any way to disable it for `sdl_sound`.

Moreover, out of curiosity I tried to use `playsound` from both packages and it seems the `sdl_sound` version fails with any MP3 file (whereas it works fine with `sdl2_sound`). So I would be in favour of removing it altogether.

**Review by carlocab — APPROVED** [review]
Linux failures are pre-existing.

**Pull request closed without merging**
