### PR TITLE
wartremover 1.2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@apjanke do you mind taking a look at this one?

**Comment by apjanke** [comment]
Scala's a bit out of my area of expertise; don't know how much help I'd be here.

This message seems like it's missing a dependency on the main Scala library. But the `libraryDependencies` in `build.sbt` look okay, and haven't changed from the previous 1.1.1 formula. I can't tell why the error is happening now, if it wasn't with the previous version. (And I tested both on my own El Cap machine, and can reproduce: 1.1.1 passes, and 1.2.0 throws this error.) Sorry.

**Comment by ilovezfs** [comment]
@apjanke OK, thanks. I may try bisecting it in that case.

**Comment by ilovezfs** [comment]
@apjanke regression is due to https://github.com/puffnfresh/wartremover/commit/f92d8daeb50a11a3174c30868d62d67f45479275. Not sure why yet, but that's the culprit.

**Comment by ilovezfs** [comment]
@apjanke reported it upstream: https://github.com/puffnfresh/wartremover/issues/289.

**Comment by ilovezfs** [comment]
@apjanke well that sure was simple: https://github.com/puffnfresh/wartremover/commit/e914d91a6a7ec9a027c2a494bc1c2500a7af0587 

Yikes.

**Comment by ChrisNeveu** [comment]
1.2.1 is now out with the fix for this issue.

**Comment by apjanke** [comment]
@ilovezfs good detective work. I have no idea why that change would have caused this. :shruggie:

**Pull request closed without merging**
