### PR TITLE
curl: http/3 support using quiche

### PR DESCRIPTION
**Pull request by junhochoi**
Add HTTP/3 download support using quiche (github.com/cloudflare/quiche).
When curl is built with quiche, it also need to build a bundled
boringssl and link with it, so this formula include quiche as
a resource.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by junhochoi** [comment]
`brew audit` shows the following:
```
Formula/curl.rb:67:7: C: use "cargo", "install", *std_cargo_args
        system "cargo", "build", ...
```

Since I just need a library (libquiche.a), no need to run `cargo install`. Any workaround to use?

**Comment by carlocab** [comment]
Thanks for the PR, @junhochoi.

`curl` is a widely used formula, and many users (e.g. running Mojave or older) need to build it from source. I don't think we can afford to make this dependent on Rust.

It's not clear that replacing the SSL implementation is a good idea either.

If you need `curl` with http/3 support, please consider using the version hosted at this tap: https://github.com/cloudflare/homebrew-cloudflare

**Comment by junhochoi** [comment]
> Thanks for the PR, @junhochoi.

Hi Thanks for a quick review.

> 
> `curl` is a widely used formula, and many users (e.g. running Mojave or older) need to build it from source. I don't think we can afford to make this dependent on Rust.

I thought that most people uses a binary so rust as a build time dependency might not be too big but I might be wrong.
Initially I'd thought this as a build time option (--with-quiche) but it looks not allowed in core.

> 
> It's not clear that replacing the SSL implementation is a good idea either.
> 
> If you need `curl` with http/3 support, please consider using the version hosted at this tap: https://github.com/cloudflare/homebrew-cloudflare

Yes I am the primary author of the above curl.rb :) Just thought that sending to upstream is a better option.

Best,

**Comment by carlocab** [comment]
> I thought that most people uses a binary so rust as a build time dependency might not be too big but I might be wrong.

This is true, but there are also a significant number of users who need to compile `curl` from source.

This is a requirement for using `brew` on macOS 10.12, for example. That's actually why we have an audit that requires an HTTP mirror for `curl` (along with its dependencies): users who will need to build `curl` from source likely have a system `curl` that doesn't support new TLS protocols, so will not be able to download sources via HTTPS.

> Yes I am the primary author of the above curl.rb :) Just thought that sending to upstream is a better option.

I see. Thanks for maintaining an alternate version of the `curl` formula. I do hope that we're able to get http/3 support in this formula soon, but I don't think it's quite ready yet.

**Comment by carlocab** [comment]
By the way, feel free to open a PR to add your tap to this list, so that users who are looking for an alternate version of `curl` have an easier time finding it:

https://github.com/Homebrew/brew/blob/master/docs/Interesting-Taps-and-Forks.md

**Comment by junhochoi** [comment]
> By the way, feel free to open a PR to add your tap to this list, so that users who are looking for an alternate version of `curl` have an easier time finding it:
> 
> https://github.com/Homebrew/brew/blob/master/docs/Interesting-Taps-and-Forks.md

Sounds good. I opened https://github.com/Homebrew/brew/pull/12821

**Comment by carlocab** [comment]
I opened a PR with some improvements to your formula: https://github.com/cloudflare/homebrew-cloudflare/pull/44

**Pull request closed without merging**
