### PR TITLE
libopenmpt has been updated to version 0.5.1

### PR DESCRIPTION
**Pull request by volkanorhan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Can you please change your commit message to `libopenmpt 0.5.1` and force-push? https://docs.brew.sh/Formula-Cookbook#commit

**Comment by volkanorhan** [comment]
> Can you please change your commit message to `libopenmpt 0.5.1` and force-push? https://docs.brew.sh/Formula-Cookbook#commit

How can I change my commit message? Do you mean to prepare a new commit?

**Comment by volkanorhan** [comment]
> Can you please change your commit message to `libopenmpt 0.5.1` and force-push? https://docs.brew.sh/Formula-Cookbook#commit

done

**Review by issyl0 — APPROVED** [review]
Thanks for your first contribution to Homebrew, @volkanorhan!

**Pull request closed without merging**
