### PR TITLE
qt: rebuild without `ffmpeg` linkage

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

`qt` picked up `ffmpeg` linkage in #122867. Let's rebuild it without
that linkage.

Follow up to #123738.

### CODE REVIEW

**Comment by cho-m** [comment]
Have we checked on state of macOS bundled dependencies?

At least for Qt5, MacPorts does use system libraries in QtWebEngine: https://ports.macports.org/port/qt5-qtwebengine/details/

**Comment by carlocab** [comment]
Nope. But I guess if we can link with `ffmpeg` then we can use more Homebrew-provided libraries instead of bundled ones.

**Comment by iltommi** [comment]
Sorry to hop in, I've seen that intel big_sur bottle is missing for qt since babf8d05b209f8bd5ba299bfe508084ef2abd5c4. 
Any chance it will appear soon? Should I build from source? Should I open an Issue?
Thanks!

**Comment by carlocab** [comment]
@paperchalice, is there any chance you'd know more about being able to use Homebrew-provided macOS deps here? It seems we can get Qt to link with `ffmpeg`, just not sure about the others.

**Comment by carlocab** [comment]
Merged in https://github.com/Homebrew/homebrew-core/pull/124104.

**Pull request closed without merging**
