### PR TITLE
grafana 6.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
09:21:51 ==> go run build.go build
09:21:51 Version: 6.5.0, Linux Version: 6.5.0, Package Iteration: 1574691635
09:21:51 rm -r ./bin/darwin-amd64/grafana-server
09:21:51 rm -r ./bin/darwin-amd64/grafana-server.md5
09:21:51 go version
09:21:51 go version go1.12.13 darwin/amd64
09:21:51 Targeting darwin/amd64
09:21:51 go build -ldflags -w -X main.version=6.5.0 -X main.commit=unknown-dev -X main.buildstamp=1574691636 -X main.buildBranch=master -mod=vendor -o ./bin/darwin-amd64/grafana-server ./pkg/cmd/grafana-server
09:21:51 # github.com/grafana/grafana-plugin-sdk-go/transform
09:21:51 vendor/github.com/grafana/grafana-plugin-sdk-go/transform/transform.go:128:29: q.Interval.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
09:21:51 exit status 2
09:21:51 exit status 1
09:21:51

**Comment by aknuds1** [comment]
You need Go version 1.13 to build Grafana 6.5.

**Comment by chenrui333** [comment]
I see, removing it now.

**Comment by chenrui333** [comment]
Trying with go v1.13

**Comment by chenrui333** [comment]
Looks like in this commit, their node dependency is also updated.
https://github.com/grafana/grafana/commit/0a080beffaf3b54b7e71b7d292bea3ad10380ac9

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by aknuds1** [comment]
Grafana 6.5 still uses Node version 10, not 12.

**Comment by chenrui333** [comment]
interesting, what about that node v10 upgrade then?

**Comment by chenrui333** [comment]
According this `engines` field, we should use node v12, no?
https://github.com/grafana/grafana/blob/master/package.json#L278

**Comment by aknuds1** [comment]
> According this `engines` field, we should use node v12, no?
> https://github.com/grafana/grafana/blob/master/package.json#L278

The 6.5 series is still on [Node 10](https://github.com/grafana/grafana/blob/v6.5.x/package.json#L278).

**Comment by chenrui333** [comment]
I see, sounds good. Thanks for pointing it out.

**Pull request closed without merging**
