### PR TITLE
json-fortran 5.0.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by UniqMartin** [comment]
cc @zbeekman

**Comment by zbeekman** [comment]
@UniqMartin: LGTM
@ilovezfs: wow, you are ⚡ fast!

@UniqMartin: if you merge this first the merge FORD 4.6.2 I think things should be squared away... some minor issues are lingering with JSON-Fortran's self publishing documentation, but not that effect a homebrew formula, or the functionality of the library itself.

**Comment by UniqMartin** [comment]
LGTM. Can you be so kind and also merge #1578 once you have merged this PR and once @zbeekman had a chance to address https://github.com/Homebrew/homebrew-core/pull/1578#discussion_r66713011? Thanks!

**Comment by zbeekman** [comment]
@UniqMartin said:

> Can you be so kind and also merge #1578 once you have merged this PR and once @zbeekman had a chance to address #1578 (comment)? Thanks!

Not sure who you're talking to regarding also merging 1578, but I pushed the required changes (made them last night... but forgot to push them...)

**Comment by UniqMartin** [comment]
> Not sure who you're talking to regarding also merging 1578, but I pushed the required changes (made them last night... but forgot to push them...)

I was talking to @ilovezfs as he's the creator of this PR and the only one among you two who has the ability to merge PRs. :wink: Thanks for all your work in the last couple of weeks and for chiming in so promptly on this PR, @zbeekman! I made you aware of this PR because I thought you might be interested and to maybe save you some work.

**Comment by zbeekman** [comment]
I appreciate it!

**Comment by zbeekman** [comment]
Ah yes I had forgotten @ilovezfs was a homebrew maintainer... thanks for doing this, glad to hear you're interested in JSON-Fortran...

**Pull request closed without merging**
