### PR TITLE
glew 2.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 :green_apple:

**Comment by DomT4** [comment]
👍. There's a small cluster of `glew`-using formulae in Science as well, don't know if you want to sort those out with revision bumps after. Up to you.

**Comment by ilovezfs** [comment]
@DomT4 Yeah, I saw those were there and was dreading them, since CI on science virtually never works unless twenty other formulae are corrected at the same time.

**Comment by DomT4** [comment]
Yeah, I try to avoid Science 😕, not least because they also support Linux for formulae & I have no desire to do that dance at all.

**Comment by ilovezfs** [comment]
@DomT4 what's with the permissions error? https://travis-ci.org/Homebrew/homebrew-core/builds/146997018

**Comment by tdsmith** [comment]
> don't know if you want to sort those out with revision bumps after. Up to you.

I'm glad ILZ is handling the -science fallout but if you'd prefer not to do it yourself please do tag some homebrew-scientists and give them/us a few days before pulling breaking PRs.

**Comment by DomT4** [comment]
I've been ignored for days tagging the entire team before. Become somewhat exasperated with trying. Will try to have even more patience with them in future.

**Pull request closed without merging**
