### PR TITLE
percona-server 8.0.26-17

### PR DESCRIPTION
**Pull request by SMillerDev**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
Note: this is also getting a rev bump at #88210, so we want to be careful about merge conflicts.

**Comment by carlocab** [comment]
```
  Undefined symbols for architecture arm64:
    "thd_get_psi(THD*)", referenced from:
        psi_memory_resource::do_allocate(unsigned long, unsigned long) in libkeyring_common.a(psi_memory_resource.cpp.o)
        psi_memory_resource::do_deallocate(void*, unsigned long, unsigned long) in libkeyring_common.a(psi_memory_resource.cpp.o)
    "mysql_components_handle_std_exception(char const*)", referenced from:
        keyring_kmip::backend::Keyring_kmip_backend::load_cache(keyring_common::operations::Keyring_operations<keyring_kmip::backend::Keyring_kmip_backend, keyring_common::data::Data_extension<keyring_kmip::IdExt> >&) in backend.cc.o
        keyring_kmip::backend::Keyring_kmip_backend::store(keyring_common::meta::Metadata const&, keyring_common::data::Data_extension<keyring_kmip::IdExt>&) in backend.cc.o
        keyring_kmip::backend::Keyring_kmip_backend::size() const in backend.cc.o
    "xtrabackup::components::component_config_data_sb", referenced from:
        keyring_kmip::config::find_and_read_config_file(std::__1::unique_ptr<keyring_kmip::config::Config_pod, std::__1::default_delete<keyring_kmip::config::Config_pod> >&) in config.cc.o
    "thread-local wrapper routine for current_thd", referenced from:
        psi_memory_resource::do_allocate(unsigned long, unsigned long) in libkeyring_common.a(psi_memory_resource.cpp.o)
        psi_memory_resource::do_deallocate(void*, unsigned long, unsigned long) in libkeyring_common.a(psi_memory_resource.cpp.o)
    "_psi_memory_service", referenced from:
        psi_memory_resource::do_allocate(unsigned long, unsigned long) in libkeyring_common.a(psi_memory_resource.cpp.o)
        psi_memory_resource::do_deallocate(void*, unsigned long, unsigned long) in libkeyring_common.a(psi_memory_resource.cpp.o)
  ld: symbol(s) not found for architecture arm64
```
https://github.com/Homebrew/homebrew-core/runs/5283767101?check_suite_focus=true#step:6:2259

**Comment by Bo98** [comment]
PXB isn't very well tested on macOS it seems.

**Comment by Bo98** [comment]
Linux error looks fun too.

**Comment by Bo98** [comment]
I'm 99% sure this source tarball has never been tested.

**Comment by Bo98** [comment]
Merged:

* 5b05e9837c4a19d24ee63b58e89741a2c2ee9a6d
* e373e9d15adbf6d12fbdbe58f00d9e2f680d35fa

**Pull request closed without merging**
