### PR TITLE
duplicity 0.7.14

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Apparently `pyrax` was responsible for a ton of the dependencies here. Losing so many makes me a touch nervous in terms of accidental side-effects but the test passes fine, so, either the test isn't comprehensive enough or the formula is fine, I guess.

### CODE REVIEW

**Comment by ilovezfs** [comment]
where did azure go?

**Comment by DomT4** [comment]
Hmm. Didn't end up in the generated `resources` file. Apparently `poet` had a sulk and seemingly dropped everything related to it:

```
/private/tmp/venv/lib/python2.7/site-packages/poet/poet.py:97: PackageVersionNotFoundWarning: Could not find an exact version match for azure-nspkg version 2.0.0; using newest instead
  format(name, version), PackageVersionNotFoundWarning)
```

**Comment by ilovezfs** [comment]
Yeah it's missing an sdist for azure-nspkg :(

**Comment by DomT4** [comment]
Managed to get a clean `poet` readout by doing `bin/pip install -v --no-binary :all: --ignore-installed` instead. Updated with the new `resources` list it kicked out.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:key:

**Comment by DomT4** [comment]
Ta :heart:

**Pull request closed without merging**
