### PR TITLE
rust 1.63.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
`rgbds` seems to be broken with this version of Rust:
```
  ==> Testing rgbds
  ==> /opt/homebrew/Cellar/rgbds/0.5.2/bin/rgbasm -o output.o source.asm
  ==> /opt/homebrew/Cellar/rgbds/0.5.2/bin/rgbobj -A -s data -p data output.o
  thread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups at `[hash: 754F87C87F12EDF4]`', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/clap-3.2.16/src/parser/matches/arg_matches.rs:1732:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
https://github.com/Homebrew/homebrew-core/runs/7798455156?check_suite_focus=true#step:10:4449 (Big Sur ARM)
https://github.com/Homebrew/homebrew-core/runs/7798455056?check_suite_focus=true#step:10:4445 (Monterey ARM)

@ISSOtm, would you happen to know anything about this?

**Comment by cho-m** [comment]
> `rgbds` seems to be broken with this version of Rust:

It was broken due to Clap update and was reported & fixed in HEAD a while back (https://github.com/gbdev/rgbobj/issues/4).

I patched in upstream commit after this CI run (#107917) so should stop failing on `CI-build-dependents-from-source` while there isn't a new release yet.

**Comment by cho-m** [comment]
Other ARM failures are not directly related to `rust`:
- [x] `brew linkage --cached --test --strict cargo-udeps` - #107918
- [ ] `brew fetch --build-from-source --retry drill` - checksum issue
- [ ] `brew install --build-from-source spidermonkey` - looks like Python3.9 is hitting same issue as Python3.10 after update & alias migration. Not sure how to fix. macOS Python 3.8 works but still issues for pre-Catalina and Linux.

**Comment by carlocab** [comment]
Would adding `libexec/"bin"` to `PATH` work for `spidermonkey`? Though, given that it's a build dependency, would be much nicer to do
```ruby
uses_from_macos "python", since: :catalina
```

**Comment by cho-m** [comment]
> Would adding `libexec/"bin"` to `PATH` work for `spidermonkey`?

I don't think so. It is correctly picking up Python 3.9, but we are now seeing prefix scheme issue here too.
```
    File "/private/tmp/spidermonkey-20220812-48536-ssbbta/firefox-91.12.0/python/mozbuild/mozbuild/virtualenv.py", line 269, in create
      self._disable_pip_outdated_warning()
    File "/private/tmp/spidermonkey-20220812-48536-ssbbta/firefox-91.12.0/python/mozbuild/mozbuild/virtualenv.py", line 615, in _disable_pip_outdated_warning
      with open(os.path.join(site_packages, pip_dist_info, "INSTALLER"), "w") as file:
  PermissionError: [Errno 1] Operation not permitted: '/opt/homebrew/lib/python3.9/site-packages/pip-22.2.1.dist-info/INSTALLER'
```

---

May actually be side-effect of newer `setuptools`. Maybe `ENV["SETUPTOOLS_USE_DISTUTILS"] = "stdlib"` could help.

**Review by carlocab — APPROVED** [review]

**Review by cho-m — APPROVED** [review]

**Comment by cho-m** [comment]
Only other failure from Intel macOS is `watchman`, which we have seen in previous `rust` PRs.

Issue there is problem when mixing SIMD and/or CRC compilation options across `folly` dependents, which seems to happen when we build `folly` bottle (`-march=nehalem`) while running `--build-from-source` on `watchman`.

**Pull request closed without merging**
