### PR TITLE
faas-cli 0.4.18

### PR DESCRIPTION
**Pull request by johnmccabe**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I assume this is do-not-merge since it's alpha?

**Comment by johnmccabe** [comment]
@alexellis can you confirm whether we should ship with `-alpha` or bump with a `0.4.18`

**Comment by ilovezfs** [comment]
Going to assume this is pre-release but thanks for the PR nonetheless @johnmccabe!

**Comment by alexellis** [comment]
Missed this. Pre-release that was tested and had pre-release flag taken off. No new changes so not sure there is any point in cutting s new release of the same code / commit

**Comment by ilovezfs** [comment]
@alexellis you should be able to push a new tag that points to the same revision.

**Comment by ilovezfs** [comment]
Thanks @johnmccabe and @alexellis!

**Comment by johnmccabe** [comment]
Thanks @ilovezfs blows my mind how responsive to PRs you are. Keep up the awesome work !

**Pull request closed without merging**
