### PR TITLE
ruby-to-python 0.0.1

### PR DESCRIPTION
**Pull request by snood1205**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by bfontaine** [comment]
`brew audit ruby-to-python --strict --online` fails:
```
Error: 2 problems in 1 formula
ruby-to-python:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
```

**Comment by UniqMartin** [comment]
I'm sorry, but aside from not being notable enough, it is also a self-submission, that is frowned upon as you can learn from our [Acceptable Formulae](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff) document. Furthermore, it doesn't look like this tool has a community (however small) yet, as there are no externally contributed issues or PRs.

We appreciate your submission, but it is too soon to accept it yet. However, you can always [create and maintain a tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) to make installation via Homebrew easy.

**Comment by snood1205** [comment]
Thank you! I didn't realize that self-submissions were frowned upon! I'll try to get a greater following and have documentation and hopefully in a little bit this will be an acceptable formula! Thanks for doing what you do!

**Comment by UniqMartin** [comment]
Good luck with your project! Thank you for understanding and for the kind words!

**Pull request closed without merging**
