### PR TITLE
dnsping 1.1.3 (new formula)

### PR DESCRIPTION
**Pull request by ldemailly**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----
[edit after full reinstall of xcode everything above passed]

### CODE REVIEW

**Comment by ldemailly** [comment]
So the build failed with
```
dnsping:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```
Any exception? I asked around for folks to star it (though didn't feel great to do so) but if you look at the main project:
Screen Shot 2020-10-22 at 12 14 44 AM
1.6k stars on Fortio itself

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by ldemailly** [comment]
@SMillerDev no problem and thanks for the pointer to private taps;
I tried but I got
```
==> FAILED
dnsping.rb:1:1: C: Missing frozen string literal comment.
class Dnsping < Formula
^

1 file inspected, 1 offense detected, 1 offense auto-correctable
Error: Missing frozen string literal comment.
```
just copying the tap into what `brew tap-new -v fortio/dnsping` created

you can see the action failure:
https://github.com/fortio/homebrew-dnsping/runs/1301248871?check_suite_focus=true

googling that issue seems to be related to ruby but no idea really (I would think the action brew tap created works/has right dependencies?)

**Comment by ldemailly** [comment]
ok this may help someone the help page says
`Tap formulae follow the same format as the core’s ones, and can be added under either the Formula subdirectory, the HomebrewFormula subdirectory or the repository’s root.`
but the formula only works "as is" in Formula/ directory (maybe because of the < Formula)

the build passed now, thanks Sean!

**Pull request closed without merging**
