### PR TITLE
dosbox-x 0.84.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
As discussions in https://github.com/Homebrew/homebrew-core/pull/104911 never ended, reusing the notes I gave then to review:


- mac build scripts got their `x` removed (`build-macosx` -> `build-mac-os`);

- While looking at this, I noticed there was also a `build-macos-sdl2`. As we already depended on it, I tried switching to that one;
- If we prefer building against sdl 1.x as it was the case and use `build-macos` instead, I guess we can depends on `sdl2` only for Linux then, as sdl 1.x is included in-tree (documentation doesn't seems to show a preference between the both of them or if that's the case I didn't see it);
- This dependency could even be removed as I understand it, it would just use the 1.x version present in-tree;

As an addition to back then, this PR was initally opened for version `0.84.3`, which is curiously still a prerelease after more than one month, which is why I changed the livecheck strategy.
I wanted to use `0.84.2` which is a stable release, but that one used a weird tagging, no idea about why: `dosbox-x-windows-v2022.08.0` is the tag name, visible at https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-v2022.08.0 and as `0.84.3` went back to the previous tagging scheme, so I feel like changing the url scheme for just this single release wasn't necessary, but can of course do it.

**Comment by carlocab** [comment]
This doesn't depend on `sdl` or `sdl2`, though:
```
❯ brew deps --tree --formula dosbox-x
dosbox-x
└── fluid-synth
    ├── glib
    │   ├── gettext
    │   └── pcre2
    ├── libsndfile
    │   ├── flac
    │   │   └── libogg
    │   ├── libogg
    │   ├── libvorbis
    │   │   └── libogg
    │   └── opus
    ├── portaudio
    └── readline
```

**Comment by Porkepix** [comment]
It seems to produce a strange livecheck error?

**Comment by Porkepix** [comment]
@carlocab I believe aside from the strange livecheck messages, the tests were fine?

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
