### PR TITLE
pandoc 2.10

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

closes #57131

### CODE REVIEW

**Review by claui — COMMENTED** [review]
Why no revision bump for `pandoc-include-code`?

**Comment by chenrui333** [comment]
@claui good catch, thanks!

**Comment by chenrui333** [comment]
test failures

```
brew test --verbose pandoc-crossref
brew test --verbose pandoc-include-code
```

**Comment by iandol** [comment]
So, am I right in inferring that because the optional filters for Pandoc have not yet been upgraded, then the new version of Pandoc itself cannot be updated from Brew, even for those users who don't use these plugins? This seems like a problem to solve with the filters, without penalising all Pandoc homebrew installs. What is the solution for this? Thank you!

**Comment by claui** [comment]
> This seems like a problem to solve with the filters

@iandol I agree. I see you’ve reached out to the affected upstream projects, which I think is the way to go for now. Thank you.

> without penalising all Pandoc homebrew installs.

Holding off on an update due to incompatible dependencies is not penalizing anyone. It’s exactly what package managers do. Homebrew is no exception.

> What is the solution for this?

You only just reached out to the plugin authors so I’d say let’s wait for the replies.

**Comment by claui** [comment]
Update:

- On `pandoc-include-code`, there’s a [PR in review](https://github.com/owickstrom/pandoc-include-code/pull/32).
- On `pandoc-crossref`, a release is [expected by the end of the week](https://github.com/lierdakil/pandoc-crossref/issues/272#issuecomment-656586365).

**Comment by claui** [comment]
Cool. Thanks @chenrui333 and @iandol!

**Comment by iandol** [comment]
And thank you @chenrui333 and @claui for your time and effort keeping homebrew the indispensable tool it is!

**Pull request closed without merging**
