### PR TITLE
lua-language-server 3.5.4

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
  An exception occurred within a child process:
    Minitest::Assertion: Expected /^Content-Length: \d+\s*$/ to match "/opt/homebrew/Cellar/lua-language-server/3.5.4/libexec/bin/lua-language-server: create_directories: Operation not permitted: \"/opt/homebrew/Cellar/lua-language-server/3.5.4/libexec/log/cache/99110\"\r\n".
```
Can we configure the location this writes logs to?

**Comment by clason** [comment]
yes, with `--logpath=<path>`

**Comment by clason** [comment]
could also set `--loglevel` higher?

**Comment by carlocab** [comment]
> yes, with `--logpath=<path>`

I was hoping we could change the compile-time default to somewhere in `var`. But, if not, I guess we can pass `--logpath`.

**Comment by clason** [comment]
That is assuming it's `lua-language-server` that's doing the logging, not one of the dependencies...

**Comment by carlocab** [comment]
> I thought we deliberately created the log path during install?

Not all of it:
```
/opt/homebrew/Cellar/lua-language-server/3.5.4/libexec/log/cache/99110
```
We could probably just pass `"--logpath=#{testpath}/log"`, like so:
```diff
diff --git a/Formula/lua-language-server.rb b/Formula/lua-language-server.rb
index 4db3df336a8..ac736ecf564 100644
--- a/Formula/lua-language-server.rb
+++ b/Formula/lua-language-server.rb
@@ -48,7 +48,7 @@ class LuaLanguageServer < Formula
     require "pty"
     output = /^Content-Length: \d+\s*$/
 
-    stdout, stdin, lua_ls = PTY.spawn bin/"lua-language-server"
+    stdout, stdin, lua_ls = PTY.spawn bin/"lua-language-server", "--logpath=#{testpath}/log"
     sleep 5
     stdin.write "\n"
     sleep 25

```

**Review by carlocab — APPROVED** [review]

**Comment by clason** [comment]
Nice, thank you as always for your help!

**Pull request closed without merging**
