### PR TITLE
wireshark 2.4.0

### PR DESCRIPTION
**Pull request by alagoutte**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Failed to build on all three macOS versions. Error is not clear, the end of the log is:

```
[ 64%] Building C object epan/dissectors/CMakeFiles/dissectors.dir/register.c.o
cd /tmp/wireshark-20170807-51915-rra5l9/wireshark-2.4.0/epan/dissectors && /usr/local/Homebrew/Library/Homebrew/shims/super/clang -DG_DISABLE_DEPRECATED -DG_DISABLE_SINGLE_INCLUDES -DWS_BUILD_DLL -I/tmp/wireshark-20170807-51915-rra5l9/wireshark-2.4.0 -I/tmp/wireshark-20170807-51915-rra5l9/wireshark-2.4.0/epan -I/tmp/wireshark-20170807-51915-rra5l9/wireshark-2.4.0/tools/lemon -isystem /usr/local/opt/gettext/include -isystem /usr/local/include -isystem /usr/local/include/glib-2.0 -isystem /usr/local/lib/glib-2.0/include -isystem /usr/local/Cellar/pcre/8.41/include -isystem /usr/local/Cellar/glib/2.52.3/include/glib-2.0 -isystem /usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include -isystem /usr/include/libxml2 -I/tmp/wireshark-20170807-51915-rra5l9/wireshark-2.4.0/epan/dissectors  -Qunused-arguments  -fvisibility=hidden -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -Wall -Wextra -Wendif-labels -Wpointer-arith -Wformat-security -fwrapv -fno-strict-overflow -Wvla -Waddress -Wattributes -Wdiv-by-zero -Wignored-qualifiers -Wpragmas -Wno-overlength-strings -Wno-long-long -Wheader-guard -Wframe-larger-than=16384 -Wc++-compat -Wshadow -Wno-pointer-sign -Wold-style-definition -Wstrict-prototypes -Wlogical-op -Wjump-misses-init -Wunused-const-variable -Wshorten-64-to-32 -Werror=implicit -std=gnu99 -o CMakeFiles/dissectors.dir/register.c.o   -c /tmp/wireshark-20170807-51915-rra5l9/wireshark-2.4.0/epan/dissectors/register.c
[ 64%] Built target dissectors
make: *** [all] Error 2
```

**Comment by DomT4** [comment]
Wondering if this is a packaging error, given building from the [2.4.0 git commit](https://code.wireshark.org/review/gitweb?p=wireshark.git;a=tag;h=7ec3c772c7cfb9802a5864af01af4eddc5787323) works just fine.

**Comment by alagoutte** [comment]
May be from https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=13903 ? (need to wait 2.4.1)

**Comment by DomT4** [comment]
Homebrew can apply patches or indeed build from git temporarily but it may well be easier to wait for 2.4.1 if y'all upstream are aware the packaging issue.

**Comment by ilovezfs** [comment]
Yes let's wait on 2.4.1. Thanks for the PR @alagoutte!

**Pull request closed without merging**
