### PR TITLE
perl-build 1.13

### PR DESCRIPTION
**Pull request by ilovezfs**
Also, add a test.

### CODE REVIEW

**Comment by DomT4** [comment]
Did upstream forget to update the version line with the new release?

**Comment by ilovezfs** [comment]
@DomT4 clearly, nor is it updated in HEAD. I checked and it was the scenario last time. i.e., current version report 11 not 12.

**Comment by DomT4** [comment]
Sigh. It's probably worth giving them a nudge about that to try and stop us inreplacing it every time, but 👍.

**Comment by ilovezfs** [comment]
Yeah, I couldn't decide whether to do that. It's so ridiculously wrong and for so long that I assume they know and I'd just be annoying. But I suppose that's their problem not mine :)

**Comment by DomT4** [comment]
If we're having to effectively patch it you've every right to be annoying 😉.

**Comment by ilovezfs** [comment]
I wonder if the "real" issue here is that we should be building it, not installing the prebuilt thingy

**Comment by DomT4** [comment]
If it has the correct version after manual building, possibly so.

**Comment by ilovezfs** [comment]
Not sure what this output means yet, but it does suggest it's cognizant of the correct version
```
iMac-TMP:Perl-Build joe$  perl Build.PL --install-base=`pwd`/IB
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Perl-Build' version '1.13'
cp META.json MYMETA.json
```

**Comment by ilovezfs** [comment]
Yeah, this is just confusing, since the 1.13 tag is from April 1 but the pre-built thing was last updated January 8. So I'm closing this PR for now.

**Pull request closed without merging**
