### PR TITLE
git 2.14.0

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @leonklingele for the pull request!

**Comment by RandomDSdevel** [comment]
@fxcoudert:  This is just something I thought I'd belatedly mention that might end up being a good thing to address either in an extra immediate revision bump to the formula affected by this PR (`git.rb`, as implicitly indicated in this PR's name) or when the next version of Git comes out, but the release notes for the version of Git that this PR propagates through into Homebrew contains the following:  

> * Git can now be built with PCRE v2 instead of v1 of the PCRE library. Replace USE_LIBPCRE=YesPlease with USE_LIBPCRE2=YesPlease in existing build scripts to build against the new version.  As the upstream PCRE maintainer has abandoned v1 maintenance for all but the most critical bug fixes, use of v2 is recommended.

`git.rb` should thus say that Git `depends_on "pcre2" => :optional`, not that it `depends_on "pcre" => :optional`.  (I should _probably_ file a PR for this, so you can also partially consider this a 'note to self' to a certain extent even if I forget about it amidst some of the other things my disorganized mind is preoccupied with at the moment&thinsp;—&thinsp;hopefully I don't, though!)

**Comment by fxcoudert** [comment]
@RandomDSdevel thanks for letting us know, I've opened a pull request for the migration: https://github.com/Homebrew/homebrew-core/pull/16439

**Comment by RandomDSdevel** [comment]
You're welcome, @fxcoudert.  I _was_ about to open a PR myself, but all's well that ends well, I suppose…

**Pull request closed without merging**
