### PR TITLE
sqlite dbhash sqldiff sqlite-analyzer 3.39.0

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by danielnachun** [comment]
This is failing only because of `python@3.7`.  Is it time to deprecate it?  It only has two dependents both of which are deprecated.

**Comment by cho-m** [comment]
> This is failing only because of `python@3.7`. Is it time to deprecate it? It only has two dependents both of which are deprecated.

From EOL standpoint, `python@3.7` is supported until June 2023.

However, I think the problem here is that `importlib-metadata` has a setup_requires dependency on `setuptools_scm`, but `setuptools_scm>=7` has a runtime dependency on `importlib-metadata`. It picks up the vendor copy within `setuptools` and fails.

Upstream has specifically mentioned they consider Homebrew's way of handling package installation unsupported (https://github.com/pypa/setuptools_scm/issues/722#issuecomment-1162834325).

We luckily got a fix for Python 3.8 and later as `importlib-metadata` is only needed on Python 3.7, but it is possible that we will hit more of these issues in future. For example, we see a build loop in `jupyterlab` #104097. 

---

If we want to keep `python@3.7`, then one option is to locally inreplace `importlib-metadata/setup.cfg` to restrict `setuptools_scm[toml]` requirement to `< 7`.

If we want to deprecate, we could use `:unsupported` reason as that is pretty much what upstream told us.

**Comment by carlocab** [comment]
I suggest doing `inreplace`. Possibly also consider deprecating it, but I think that's just going to end up teaching users not to take deprecation warnings seriously.

**Comment by owine** [comment]
This is blocked by `python@3.7`

**Comment by carlocab** [comment]
> This is blocked by `python@3.7`

Actually, it's not. `brew install python@3.7` fails with the same error even without this PR. (Which makes sense, because the failure looks to be happening inside pure Python code rather than in anything `sqlite`-related.)

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
