### PR TITLE
mas 1.2.0 (new formula)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Haven't tested this locally as I don't have Xcode installed but this looks like it should work.

### CODE REVIEW

**Comment by argon** [comment]
This is missing a couple of steps. `script/bootstrap` must be run to pull down dependencies and the Xcodeproj referenced has the incorrect name, should be `mas-cli.xcodeproj`

**Comment by mikemcquaid** [comment]
@argon Sorry, it wasn't my intention you'd have to review this. My main issue with `script/bootstrap` (which is why I was trying to avoid it) was the use of `bundler` which is painful to do inside Homebrew itself. Thoughts?

**Comment by argon** [comment]
I'm thinking about beginning to bundle the Swift dependencies which would obviate the need for bundler when doing a normal build. I will need to make some small changes but I can take a look this weekend.

**Comment by mikemcquaid** [comment]
Yeh, either vendoring or submodules would be 👍 from our perspective. I'll see if I can hack something together before then, though.

**Comment by mikemcquaid** [comment]
Or using e.g. Carthage would be easy too as we have a formula for that you could depend on at build time.

**Comment by argon** [comment]
Carthage not an option at this point as there are untold problems with frameworks etc. I wanted to keep mas as a single binary without ancillary frameworks to install which means frameworks aren't an option.

**Comment by argon** [comment]
Also, I think that Xcode 7.3 might be required now, I can't remember.

**Comment by mikemcquaid** [comment]
Sure; I have no idea about e.g. Swift development so just parroting blindly 😉

**Comment by mikemcquaid** [comment]
> Also, I think that Xcode 7.3 might be required now, I can't remember.

@argon Once we get this building in CI that'll tell us.

**Comment by mikemcquaid** [comment]
@argon Actually no need to do anything on your side, I figured out the right approach.

**Comment by argon** [comment]
Ok, I may still begin vendoring the dependencies - it's something I've been thinking about for a while, but I won't do it as a priority.

**Comment by mikemcquaid** [comment]
Nice, working. Any thoughts/objections @argon?

**Comment by argon** [comment]
Nope. Looks good to me.

**Pull request closed without merging**
