### PR TITLE
groonga 13.0.5

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
good catch!

**Comment by osalbahr** [comment]
> good catch!

Thx, but I owe it to the strange `brew bump` bug (heisenbug?) and Repology lol.

Old logs:
```console
...
==> grc
Current formula version:  1.13
Latest livecheck version: 1.13
Latest Repology version:  1.13.1
Open pull requests:       none
Closed pull requests:     grc 1.13 (https://github.com/Homebrew/homebrew-core/pull/83008)

Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 36 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 36 seconds
==> groonga
Current formula version:  13.0.4
Latest livecheck version: 13.0.5
Latest Repology version:  13.0.5
Open pull requests:       none
Closed pull requests:     none
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 33 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 33 seconds
Warning: This formula has resources that may need to be updated.
==> Downloading https://github.com/groonga/groonga/releases/download/v13.0.5/gro
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
Warning: Cannot verify integrity of '1f3987a5f67f3a6fac39f90b4dd4edcf9b10ec80257ebcdaeef8089c70e52e06--groonga-13.0.5.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "f49c4b2bd24f60a3237495dda241017c42076f4d2012bc523fcfa4f349f069a0"
==> replace /https:\/\/github\.com\/groonga\/groonga\/releases\/download\/v13\.0
==> replace "38687ab060001aeabe0c0e05de5b90289543eeb98504fdde53c682e937a3d077" w
M	Formula/arkade.rb
M	Formula/groonga.rb
Switched to a new branch 'bump-groonga-13.0.5'
[bump-groonga-13.0.5 0e9d75890af] groonga 13.0.5
 1 file changed, 2 insertions(+), 2 deletions(-)
remote: 
remote: Create a pull request for 'bump-groonga-13.0.5' on GitHub by visiting:        
remote:      https://github.com/osalbahr/homebrew-core/pull/new/bump-groonga-13.0.5        
remote: 
To https://github.com/osalbahr/homebrew-core.git
 * [new branch]              bump-groonga-13.0.5 -> bump-groonga-13.0.5
branch 'bump-groonga-13.0.5' set up to track 'https://******@github.com/osalbahr/homebrew-core.git/bump-groonga-13.0.5'.
https://github.com/Homebrew/homebrew-core/pull/138593

Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 17 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 17 seconds
==> gtk-gnutella
Current formula version:  1.2.2
Latest livecheck version: 1.2.2
Latest Repology version:  2023.07.17
Open pull requests:       none
Closed pull requests:     none

Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 17 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 17 seconds
...
```


New logs:
```console
$ brew bump groonga
==> groonga
Current formula version:  13.0.4
Latest livecheck version: 13.0.4
Latest Repology version:  13.0.5
Open pull requests:       groonga 13.0.5 (https://github.com/Homebrew/homebrew-core/pull/138593)
Closed pull requests:     none
```

**Comment by kou** [comment]
Sorry. We forgot to upgrade the Web site information.
I've updated.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @kou!

**Pull request merged**
