### PR TITLE
llvm@8: use elfutils, libelf is deprecated

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by danielnachun** [comment]
I'd also like to add a couple flags to this that should have been added on Linux when we enabled `libc++` here.  This should be a minor change but it would be good to do it at the same time we handle the rest of this.

**Comment by iMichka** [comment]
> I'd also like to add a couple flags to this that should have been added on Linux when we enabled libc++ here. This should be a minor change but it would be good to do it at the same time we handle the rest of this.

llvm 8 is deprecated, so I would not worry that much. I just want to get rid of the dependency to be able to cleanup `libelf`.

**Comment by danielnachun** [comment]
Okay, I did push the commit already but you can drop it if you want.

**Review by danielnachun — DISMISSED** [review]

**Comment by danielnachun** [comment]
I dropped the other commit as there is really no point in fixing this given that it is deprecated.  @carlocab mentioned here: https://github.com/Homebrew/homebrew-core/pull/104050 that we probably didn't migrate `llvm@7` and `llvm@8` to `elfutils` to avoid the trouble of having to rebuild the bottles.  Given how backed up our CI queue is with long builds already, maybe we should focus on getting `avrdude` and `dynamips` off of `libelf` and not worry about trying to disable `libelf`, given that it's already deprecated?

**Comment by iMichka** [comment]
I fixed the patch url, as it needed full index. I also went for Python 3.8 as Python 2 is gone on Mac.

I think this can be merged now. There are still around 400 downloads / month, so I think we can disable this formula when that number drops a little bit.

**Review by carlocab — APPROVED** [review]
> I fixed the patch url, as it needed full index.

No, it doesn't.

```
❯ url="https://raw.githubusercontent.com/Homebrew/formula-patches/bc3176e6794efb9f2581ce4f9ede3ad34efb492c/llvm%409/llvm%409.patch"
❯ diff <(curl -sL "${url}?full_index=1") <(curl -sL "$url") && echo same
same
```

**Comment by iMichka** [comment]
The previous build failed with a checksum mismatch on the patch. full index makes sure we always get the same file and the same checksum.

**Comment by carlocab** [comment]
No, it doesn't. That file is a GitHub-hosted raw file, and not a generated patch. GitHub probably shouldn't change the contents of files in your repo because you added `?full_index=1` to the URL.

**Pull request closed without merging**
