### PR TITLE
icon-naming-utils: Get tarball from Debian.

### PR DESCRIPTION
**Pull request by hfiguiere**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Fixes Homebrew/brew#209

### CODE REVIEW

**Comment by hfiguiere** [comment]
I'll be honest I'm not sure if it is a good idea to pull from Debian and use their resources.

**Comment by DomT4** [comment]
An imaginary $1 says if you run `brew doctor` it nudges you to `brew install curl` 😉.

**Comment by DomT4** [comment]
Oh, that's actually not the problem for once. I can reproduce.

The system `curl` on 10.8 is heavily useless when it comes to a lot of secure connections these days, so that's become something of my go-to response when reports come from 10.8 about secure connections failing. My apologies for jumping to that conclusion here!

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/2c96f339133529eb82baba6be0d0340715a16907. Apologies once again for the presumption 🙈, and thank you for reporting it to us.

**Comment by hfiguiere** [comment]
I forgot to mention I did test in the browser :-D, but then the file is 404.

**Comment by DomT4** [comment]
Yeah. Upstream have been working towards getting SSL/TLS across that whole domain for a little while now, which is great, but they seem to have turned it on by default (by forcing the redirect to `https`) without perhaps noticing the certificate is for `www.freedesktop.com` rather than a wildcard or specific subdomain, which has consequently broken things like `tango.freedesktop.com`.

**Pull request closed without merging**
