### PR TITLE
mdbook 0.2.3 (new formula)

### PR DESCRIPTION
**Pull request by CameronNemo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by CameronNemo** [comment]
Some feedback here would be appreciated, Jenkins is no help.

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by CameronNemo** [comment]
Takes about 20 minutes on average. Is my commit message too short?

**Comment by SMillerDev** [comment]
No, should be fine. I just think it was a hiccup in Jenkins.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by CameronNemo** [comment]
Bump. CI keeps failing. Not sure why.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Not sure why CI is failing:

```
14:11:58 Error: undefined method `values' for nil:NilClass
14:11:58 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:780:in `bottle_reinstall_formula'
14:11:58 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:941:in `formula'
14:11:58 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1292:in `block in run'
14:11:58 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1291:in `each'
14:11:58 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1291:in `run'
14:11:58 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1674:in `test_bot'
14:11:58 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1774:in `<top (required)>'
14:11:58 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
14:11:58 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
14:11:58 /usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
14:11:58 /usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
```

Maybe it's because your file name has capital M? Please make it lowercase.

**Comment by CameronNemo** [comment]
The M is lower case. The B is upper case, though. I could try changing that.

**Comment by fxcoudert** [comment]
So that worked, except we had a weird network fluke on Sierra:

```
==> Downloading https://github.com/rust-lang-nursery/mdBook/archive/v0.2.3.tar.gz
==> Downloading from https://codeload.github.com/rust-lang-nursery/mdBook/tar.gz/v0.2.3
curl: (22) The requested URL returned error: 500 Internal Server Error
Error: Failed to download resource "mdbook"
```

@BrewTestBot test this please, again

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @CameronNemo for your contribution to Homebrew!

**Pull request closed without merging**
