### PR TITLE
mpv with lua or lua51

### PR DESCRIPTION
**Pull request by kkdd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you explain the motivation for this change? Thanks!

**Comment by kkdd** [comment]
luabind users need lua51 installed with preventing lua (= lua 5.2) from being installed.

**Comment by MikeMcQuaid** [comment]
Why can't they both be installed?

**Comment by fxcoudert** [comment]
Given the lack of activity, closing this pull request for now. Please reopen with more information if the problem is still present.

**Pull request closed without merging**
