### PR TITLE
Require java 1.8 was (1.8+) as kafka 0.11.0.1 does not run with java 9

### PR DESCRIPTION
**Pull request by service-michaelnielson-taulia**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
I am a bit confused why we have this
```

  # Related to https://issues.apache.org/jira/browse/KAFKA-2034
  # Since Kafka does not currently set the source or target compability version inside build.gradle
  # if you do not have Java 1.8 installed you cannot used the bottled version of Kafka
  pour_bottle? do
    reason "The bottle requires Java 1.8."
    satisfy { quiet_system("/usr/libexec/java_home --version 1.8 --failfast") }
  end
```
if it simply doesn't work with > 1.8.

**Comment by michaelnielson-taulia** [comment]
When the current stable version of kafka supports java 9 these could all be updated to use `1.8+` including the install requirement that is already requiring that java 8 be installed. 

This PR resolves an issue when a user has both java 8 and java 9 installed. Because 1.8 is installed the formula will install but `/usr/libexec/java_home --version 1.8+` will select the latest java version in this case 1.9 which fails on startup.

The Kafka ticket for Java 9 support appears to have been completed recently: https://issues.apache.org/jira/browse/KAFKA-4501 
I assume this means the next Kafka release (1.0.0) should support Java 9

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@michaelnielson-taulia Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
