### PR TITLE
pulseaudio 12.99.1

### PR DESCRIPTION
**Pull request by maxim-belkin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
I may be wrong about this, but I'm pretty sure FreeDesktop uses the `x.99.x` format to indicate a rolling development release (i.e. 12.99.1 is not stable).

**Comment by maxim-belkin** [comment]
Let me double check...

**Comment by maxim-belkin** [comment]
> I'm pretty sure FreeDesktop uses the x.99.x format to indicate a rolling development release

I couldn't find any information about that, however it _looks like_ `.99.x` releases are &beta; releases that precede stable ones by about a month. I'll close the PR then.

**Comment by maxim-belkin** [comment]
I've just received a confirmation from one of the developers that this is a &beta; (release-candidate) release and there's probably going to be one more before 13.0 is released.

**Pull request closed without merging**
