### PR TITLE
ansible 2.3.0.0

### PR DESCRIPTION
**Pull request by jeremiahwinsley**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
The resource blocks ought to be updated as well.

**Comment by respawner** [comment]
I don't know if this can help, I'm pretty new to homebrew here is what I gathered from `pip install ansible homebrew-pypi-poet && poet ansible`

```
resource "ansible" do
  url "https://files.pythonhosted.org/packages/65/6e/3df94b6bf0e2d8b7d1e9e4e384e312c49c59fce45ccfce3d01dd98084395/ansible-2.3.0.0.tar.gz"
  sha256 "299f3907cd566a20e163942fa82b6afc86ef89c2726ba503b90c1a651e82a458"
end

resource "appdirs" do
  url "https://files.pythonhosted.org/packages/48/69/d87c60746b393309ca30761f8e2b49473d43450b150cb08f3c6df5c11be5/appdirs-1.4.3.tar.gz"
  sha256 "9e5896d1372858f8dd3344faf4e5014d21849c756c8d5701f78f8a103b372d92"
end

resource "asn1crypto" do
  url "https://files.pythonhosted.org/packages/67/14/5d66588868c4304f804ebaff9397255f6ec5559e46724c2496e0f26e68d6/asn1crypto-0.22.0.tar.gz"
  sha256 "cbbadd640d3165ab24b06ef25d1dca09a3441611ac15f6a6b452474fdf0aed1a"
end

resource "cffi" do
  url "https://files.pythonhosted.org/packages/5b/b9/790f8eafcdab455bcd3bd908161f802c9ce5adbf702a83aa7712fcc345b7/cffi-1.10.0.tar.gz"
  sha256 "b3b02911eb1f6ada203b0763ba924234629b51586f72a21faacc638269f4ced5"
end

resource "cryptography" do
  url "https://files.pythonhosted.org/packages/ec/5f/d5bc241d06665eed93cd8d3aa7198024ce7833af7a67f6dc92df94e00588/cryptography-1.8.1.tar.gz"
  sha256 "323524312bb467565ebca7e50c8ae5e9674e544951d28a2904a50012a8828190"
end

resource "enum34" do
  url "https://files.pythonhosted.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz"
  sha256 "8ad8c4783bf61ded74527bffb48ed9b54166685e4230386a9ed9b1279e2df5b1"
end

resource "idna" do
  url "https://files.pythonhosted.org/packages/d8/82/28a51052215014efc07feac7330ed758702fc0581347098a81699b5281cb/idna-2.5.tar.gz"
  sha256 "3cb5ce08046c4e3a560fc02f138d0ac63e00f8ce5901a56b32ec8b7994082aab"
end

resource "ipaddress" do
  url "https://files.pythonhosted.org/packages/4e/13/774faf38b445d0b3a844b65747175b2e0500164b7c28d78e34987a5bfe06/ipaddress-1.0.18.tar.gz"
  sha256 "5d8534c8e185f2d8a1fda1ef73f2c8f4b23264e8e30063feeb9511d492a413e1"
end

resource "Jinja2" do
  url "https://files.pythonhosted.org/packages/90/61/f820ff0076a2599dd39406dcb858ecb239438c02ce706c8e91131ab9c7f1/Jinja2-2.9.6.tar.gz"
  sha256 "ddaa01a212cd6d641401cb01b605f4a4d9f37bfc93043d7f760ec70fb99ff9ff"
end

resource "MarkupSafe" do
  url "https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz"
  sha256 "a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665"
end

resource "packaging" do
  url "https://files.pythonhosted.org/packages/c6/70/bb32913de251017e266c5114d0a645f262fb10ebc9bf6de894966d124e35/packaging-16.8.tar.gz"
  sha256 "5d50835fdf0a7edf0b55e311b7c887786504efea1177abd7e69329a8e5ea619e"
end

resource "paramiko" do
  url "https://files.pythonhosted.org/packages/64/79/5e8baeedb6baf1d5879efa8cd012f801efc232e56a068550ba00d7e82625/paramiko-2.1.2.tar.gz"
  sha256 "5fae49bed35e2e3d45c4f7b0db2d38b9ca626312d91119b3991d0ecf8125e310"
end

resource "pyasn1" do
  url "https://files.pythonhosted.org/packages/69/17/eec927b7604d2663fef82204578a0056e11e0fc08d485fdb3b6199d9b590/pyasn1-0.2.3.tar.gz"
  sha256 "738c4ebd88a718e700ee35c8d129acce2286542daa80a82823a7073644f706ad"
end

resource "pycparser" do
  url "https://files.pythonhosted.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz"
  sha256 "0aac31e917c24cb3357f5a4d5566f2cc91a19ca41862f6c3c22dc60a629673b6"
end

resource "pycrypto" do
  url "https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz"
  sha256 "f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c"
end

resource "pyparsing" do
  url "https://files.pythonhosted.org/packages/3c/ec/a94f8cf7274ea60b5413df054f82a8980523efd712ec55a59e7c3357cf7c/pyparsing-2.2.0.tar.gz"
  sha256 "0832bcf47acd283788593e7a0f542407bd9550a55a8a8435214a1960e04bcb04"
end

resource "PyYAML" do
  url "https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz"
  sha256 "592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab"
end

resource "six" do
  url "https://files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz"
  sha256 "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a"
end
```

**Comment by jeremiahwinsley** [comment]
It needs the dependencies from [lines 21-35](https://github.com/jeremiahwinsley/homebrew-core/blob/b34841f42fce79800e945aae6e4c17b3b5f651e0/Formula/ansible.rb#L21-L35) also.

However `pyrax` is no longer maintained and has quite a few dependency conflicts when I try to update anything. I'm not a Python dev so I'm not having much luck resolving them.

**Comment by jeremiahwinsley** [comment]
@ilovezfs - can we remove `pyrax` from the formula? This would remove Rackspace cloud support until users installed that dependency locally, but we could update everything without conflicts.

**Comment by ilovezfs** [comment]
CC @tdsmith @DomT4 for thoughts regarding pyrax/rackspace.

**Comment by tdsmith** [comment]
openstack wyd

https://git.openstack.org/cgit/openstack/oslo.policy/tree/requirements.txt

```
requests!=2.12.2,!=2.13.0,>=2.10.0 # Apache-2.0
```

**Comment by tdsmith** [comment]
Yeah, looking at this, I agree that pyrax's dependencies are incompatible and we should remove it.

**Comment by tdsmith** [comment]
It looks like I can get a consistent set this way:

```
pip install ansible docker-py shade pywinrm kerberos xmltodict boto boto3 botocore apache-libcloud python-keyczar passlib zabbix-api
# pip doesn't actually install a consistent working set on its own; #sad
pip install 'requests<2.13.0' 'pbr!=2.1.0,>=2.0.0'
pip install homebrew-pypi-poet
poet -f ansible -a docker-py -a shade -a pywinrm -a kerberos -a xmltodict -a boto -a boto3 -a botocore -a apache-libcloud -a python-keyczar -a passlib -a zabbix-api
```

and this is the resource list I get: https://gist.github.com/455de716f6df09954cc9e6f477328c79

**Comment by ilovezfs** [comment]
Thanks Tim!

@jeremiahwinsley let's go with that list! :) Thanks for identifying the pyrax trouble.

**Comment by jeremiahwinsley** [comment]
@ilovezfs Ready for review.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@jeremiahwinsley Shipped! Thanks for the PR :100:

**Comment by DomT4** [comment]
@ilovezfs Apologies, wasn't deliberately ignoring your ping. Have been a bit under the weather lately so unpredictable as to when I'll be around or not, sigh.

**Pull request closed without merging**
