### PR TITLE
digdag 0.9.40

### PR DESCRIPTION
**Pull request by inohiro**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
11:09:16 ==> brew test digdag --verbose
11:09:19 ==> FAILED
11:09:19 Testing digdag
11:09:19 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200115-33601-1026vea.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/digdag.rb --verbose
11:09:19 ==> /usr/local/Cellar/digdag/0.9.40/bin/digdag --version
11:09:19 Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
11:09:19 Unrecognized VM option 'AggressiveOpts'
11:09:19 Error: Could not create the Java Virtual Machine.
11:09:19 Error: A fatal exception has occurred. Program will exit.
11:09:19 Error: digdag: failed
11:09:19 An exception occurred within a child process:
11:09:19   Test::Unit::AssertionFailedError: <0> expected but was
11:09:19 <1>.

**Comment by inohiro** [comment]
I have no idea to solve this error because the dependency is already declared at https://github.com/Homebrew/homebrew-core/pull/49016/files#diff-386efc29180bfbfc052ace392df5850dR9

@chenrui333 May I have some suggestions?

**Comment by chenrui333** [comment]
Close in favor of #49061

**Comment by chenrui333** [comment]
@inohiro I think we have good idea to solve the issue (java version related), creating a new PR to do the work :)

**Pull request closed without merging**
