### PR TITLE
oq 1.3.0

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Automated bump.

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
@dawidd6 I used https://github.com/Homebrew/actions/tree/master/bump-formulae for this. Do you know if there's a way to change commit author?  Seems it got set to `runner` due to it coming from GHA.

**Comment by branchvincent** [comment]
> Do you know if there's a way to change commit author?

Just configure `git` with your desired username/email prior to running the action. See https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Review by branchv — APPROVED** [review]
thanks @Blacksmoke16!

**Comment by Blacksmoke16** [comment]
@branchvincent Oh, easy enough. Thanks!

**Pull request closed without merging**
