### PR TITLE
Azure CLI 2.20.0

### PR DESCRIPTION
**Pull request by azclibot**
The latest release of the Azure CLI

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]

**Comment by miketimofeev** [comment]
@iMichka could you please merge this? We're looking forward to this version since it fixes a lot of bugs.

**Comment by iMichka** [comment]
Github actions is currently broken so we need to wait. There is a live github incident right now. It's not stuck on our side.

This was opened 3 hours ago, I think we have been pretty reactive here :)

**Comment by miketimofeev** [comment]
@iMichka what GitHub issue breaks the publish? I'll try to escalate or ask when it will be resolved

**Comment by iMichka** [comment]
The search functionality of GitHub is broken. It fails on an API call to GitHub, you can see it in the logs of the publish failure:
> 2021-03-02T17:13:06.9536500Z /usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.0.4-8-gb024954\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/Homebrew/homebrew-core/actions/workflows/tests.yml/runs\?event=pull_request\&branch=azcli2.20.0

This has already been reported to GitHub but the more people complain about it the more chance we have to get it fixed.

**Comment by carlocab** [comment]
Merging this manually, but this

>I'll try to escalate or ask when it will be resolved

would still help a lot. Thanks!

**Pull request closed without merging**
