### PR TITLE
gvim v8.2.2650 (new formula)

### PR DESCRIPTION
**Pull request by ghost**
Adds a new vim formula with X11 GUI support to include much needed features in the build e.g. the clipboard utility

### CODE REVIEW

**Comment by brewfixvim** [comment]
Hey there maintainers...i'm on a machine with no git installed and am doing this entirely on the website. Could you please help me set up a `vim-gtk` alias file that symlinks to `gvim.rb`

**Comment by brewfixvim** [comment]
@sjackman regarding the naming of the formulae, I have decided go with the Arch Linux way of naming. This is much less confusing than Debian's and regarding that an alias will be set up, it should be much easier to spin up whichever build a user needs flawlessly.

**Comment by SMillerDev** [comment]
> Hey there maintainers...i'm on a machine with no git installed and am doing this entirely on the website. Could you please help me set up a vim-gtk alias file that symlinks to gvim.rb

You'll have to install git to use this with brew anyway. This formula can wait until you have your environment sorted. 

And please stop tagging maintainers, people will read the PR when they have time.

**Comment by brewfixvim** [comment]
Someone pick this up...

**Pull request closed without merging**
