### PR TITLE
gxml: depend on gtk-doc

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@fxcoudert while in new formula PRs there's the rule within alphabetization with a given dependency type, let's not reorder anything in existing formulae unless a line is changing for some other reason, because it needlessly obfuscates the diff.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Why is this suddenly needed?

**Comment by ilovezfs** [comment]
CC @tschoonj for review

**Comment by tschoonj** [comment]
Interesting, now I also need gtk-doc to build this Formula. I think it has to do with valadoc having been added to vala 0.36.0. Wouldn't it make more sense to give `vala` a run-time dependency on `gtk-doc`? Other Formulas might be affected by the same problem.

**Comment by ilovezfs** [comment]
@tschoonj yes but I'm not sure that actually works as expected :(
Can you try it locally?

**Comment by tschoonj** [comment]
Doesnt work unfortunately 😢 
Not sure why though: if I specify `gtk-doc` as a `:run` dependency of `vala`, shouldn't it get added to the PATH whenever `vala` is specified somewhere as `:build` dependency?

**Comment by ilovezfs** [comment]
@tschoonj yep but that would require fixing the "bug" in brew, which may be considered a feature.

**Comment by tschoonj** [comment]
Until someone does that, I think the only solution is to add `gtk-doc` as an option here.

Or alternatively, the documentation can be disabled by passing `--disable-docs` to configure. This also fixes the problem on my machine.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
https://jenkins.brew.sh/job/Homebrew%20High%20Sierra%20Testing/884/

**Pull request merged**
