### PR TITLE
awscli 2.2.44

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
not sure what this failure is about

```
  ERROR: No matching distribution found for botocore==2.0.0dev152
  Installing backend dependencies: finished with status 'error'
```

**Comment by cho-m** [comment]
Upstream introduced a new build-backend.

Based on comment in https://github.com/aws/aws-cli/blob/2.2.44/requirements-runtime.txt, we may need to try with `--no-build-isolation` to avoid PyPI lookup for `botocore`:
```
# ... However, pip tries to
# do this in isolation which will fail because the botocore implementation is
# not on PyPI. To work around this, you need to specify --no-build-isolation
# so pip uses the current virtualenv, but that also disables pip's logic to
# try install the build dependencies on your behalf and you have to install
# the dependencies yourself.
```

**Comment by bevanjkay** [comment]
@cho-m Strange, because I think the build changed for version `2.2.43` - but maybe it was only a part migration.
How do we pass the flag to the build?

**Comment by kyleknap** [comment]
Just chiming in as I saw it was referenced from my PR: https://github.com/aws/aws-cli/pull/6448. Yeah you are going to need to use `--no-build-isolation` for the time being. Once the final point in this [proposal](https://github.com/kyleknap/aws-cli/blob/source-proposal/proposals/source-install.md#required-code-base-changes-for-pep-517-support) is complete you should be able to remove the flag.

Another thing that I noticed was the you should now be able to remove usage of the [`gen-ac-index`](https://github.com/Homebrew/homebrew-core/pull/86527/files#diff-b7f4cf8106a4733682db1cc78b97f60827775265a22fb6eb41d1e6dc31d4147fR153) script since the auto-complete index should now be built as part of pip building/installing the wheel. We'll likely be keeping that script around as it is needed for editable installs, but there is a chance in the future that we remove it completely if we are ever able to build the auto-complete index as part of editable installs.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
