### PR TITLE
hidapi 0.10.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
https://github.com/libusb/hidapi/blob/master/LICENSE.txt

```
HIDAPI can be used under one of three licenses.

1. The GNU General Public License, version 3.0, in LICENSE-gpl3.txt
2. A BSD-Style License, in LICENSE-bsd.txt.
3. The more liberal original HIDAPI license. LICENSE-orig.txt

The license chosen is at the discretion of the user of HIDAPI. For example:
1. An author of GPL software would likely use HIDAPI under the terms of the
GPL.

2. An author of commercial closed-source software would likely use HIDAPI
under the terms of the BSD-style license or the original HIDAPI license.
```

So probably:

```
license any_of: ["GPL-2.0-only", "BSD-3-Clause", :cannot_represent]
```

**Comment by Rylan12** [comment]
> ```ruby
> license any_of: ["GPL-3.0-only", "BSD-3-Clause", :cannot_represent]
> ```

Is this how we want to use the `:cannot_represent` symbol?
Ah, interesting! That way I envisioned the `:cannot_represent` symbol was to represent the entire expression.

**Comment by SMillerDev** [comment]
I don't think we should do that

**Comment by fxcoudert** [comment]
@SMillerDev so `license :cannot_represent`?

**Comment by SMillerDev** [comment]
Either that or we choose not to represent the BSD alternative.

**Comment by fxcoudert** [comment]
It's not the BSD part that's the issue, it's the “more liberal original HIDAPI license”

**Comment by SMillerDev** [comment]
I agree with it feeling wrong, but to me it would be worse to not represent any of the 3 options. If only we had a lawyer that could help us here

**Comment by chenrui333** [comment]
Let's go with the version bump for this PR and move the license discussion into separate one?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
