### PR TITLE
Java 9 tweaks

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
yeti fails to build.

**Comment by DomT4** [comment]
In `build.xml` try changing the two lines that read:
```
encoding="UTF-8" source="1.4" target="1.4" debuglevel="source,lines"
```
into:
```
encoding="UTF-8" source="1.6" target="1.6" debuglevel="source,lines"
```

Apparently that's the hiccup, reading around. If it works easy enough to submit upstream I guess.

**Comment by ilovezfs** [comment]
@DomT4 I know ;)

**Comment by DomT4** [comment]
Ah, I thought you were exercising an air of mystery 😉.

**Comment by ilovezfs** [comment]
@DomT4 FYI we have both Java 8 and Java 9 installed on CI now.

**Comment by DomT4** [comment]
Nice 👍. Probably a solid choice given Java 9 support seems likely to take a while to trickle down.

**Pull request merged**
