### PR TITLE
feat: new Formula, ossutil 1.6.6

### PR DESCRIPTION
**Pull request by alswl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-   `brew audit --new-formula ossutil`
   -  except: "`go_resource`s are deprecated. Please ask upstream to implement Go vendoring`"

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
  * C: 4: col 9: Description should start with a capital letter
  * C: 4: col 9: Description shouldn't start with an indefinite article, i.e. "a"
  * C: 13: col 3: `go_resource`s are deprecated. Please ask upstream to implement Go vendoring
```

**Comment by alswl** [comment]
> ```
>   * C: 4: col 9: Description should start with a capital letter
>   * C: 4: col 9: Description shouldn't start with an indefinite article, i.e. "a"
>   * C: 13: col 3: `go_resource`s are deprecated. Please ask upstream to implement Go vendoring
> ```

Issues left are all about `go_resource` now, I will push upstream use vendoring. Can you merge this version to homebrew-core

**Comment by SMillerDev** [comment]
We won't merge formula (especially new ones) with known issues. After this has been resolved upstream we can merge it.

**Comment by fxcoudert** [comment]
I'm closing this for now, we'll be glad to consider a new PR with proper dep vendoring.

**Pull request closed without merging**
