### PR TITLE
driftctl 0.38.1

### PR DESCRIPTION
**Pull request by patch-the-dog**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by dawidd6** [comment]
Homepage's certificate expired or something.

**Comment by p-linnane** [comment]
There's a mismatch with the certificate. It's only valid for `*.wordpress.com`, so there's probably a misconfiguration on the homepage.

**Comment by eliecharra** [comment]
The website is currently down because of a payment issue. This is under investigation and should be resolved soon by our financial division but it's taking a long time ... Maybe we could change the homepage to https://docs.driftctl.com also 🤔

**Comment by SMillerDev** [comment]
That's not the homepage though, it's the docs page

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Sorry made a mistake on the run.

**Comment by chenrui333** [comment]
I did not realize the tag `CI-no-fail-fast` was added, but we did never made a rerun. 🤦  Creating a new PR to rebuild the bottles.

**Comment by eliecharra** [comment]
Ok guys the website should be up again, sorry for the interruption 🙏🏻

**Pull request closed without merging**
