### PR TITLE
i686-elf-gcc, x86_64-elf-gcc 11.1.0

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
`mingw-w64` did not build at all, so dropping it from this PR.

**Comment by Gcenx** [comment]
> `mingw-w64` did not build at all, so dropping it from this PR.

I’ve also confirmed this but it’s very strange, as I’ve managed to build Macports-ports `i686-w64-mingw32-gcc` & `x86_64-w64-mingw32-gcc` GCC-11.1.0 sources.

I’ve not had enough time to dig into the specifics of why this works, it could be one of the two patches or the multi build stages for gcc.

**Comment by carlocab** [comment]
> Edit;
> You might want to avoid this upgrade as gcc-11 seems to have caused ld issues when I tried to compile wine-6.7

Oops. Missed this. In any case, we ship whatever upstream ships. If it's broken, it needs to be fixed upstream.

**Comment by Gcenx** [comment]
> > Edit;
> > You might want to avoid this upgrade as gcc-11 seems to have caused ld issues when I tried to compile wine-6.7
> 
> Oops. Missed this. In any case, we ship whatever upstream ships. If it's broken, it needs to be fixed upstream.

My comment is more if someone had an issue and searches they will see the reason.

**Comment by Gcenx** [comment]
@carlocab do you happen to remember the issue you had when trying to compile mingw-w64 with gcc11?

**Comment by carlocab** [comment]
You can check the logs at https://github.com/Homebrew/homebrew-core/actions/runs/789657555.

**Pull request closed without merging**
