### PR TITLE
spaceinvaders-go 1.2.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like this uses go modules: https://github.com/asib/spaceinvaders/issues/5

**Comment by SMillerDev** [comment]
Latest commit isn't in a release yet right?

**Comment by carlocab** [comment]
It's in the tag in this PR: https://github.com/asib/spaceinvaders/releases/tag/v1.2.1

We could maybe wait for the tag to be registered as the latest release in the GitHub UI, but in the meantime, it would be good to know if the commit does in fact fix it.

**Comment by chenrui333** [comment]
let me refactor the PR.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
