### PR TITLE
openssl@1.1, gnutls: fix postinstall failure

### PR DESCRIPTION
**Pull request by brentward**
…ilure t 

addressing issue: https://github.com/Homebrew/homebrew-core/issues/79932

- [ x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by nandahkrishna** [comment]
Could you split your commit into two so that each commit modifies only one formula? And you'll also have to tweak the commit message according to the commit style guide (formula name at the start of the commit message).

**Comment by brentward** [comment]
Sure, can it be two commits within a single PR or should I open a separate PR for each formula?

**Comment by nandahkrishna** [comment]
> Sure, can it be two commits within a single PR or should I open a separate PR for each formula?

Two commits in a single PR is fine, just as you've done now.

**Comment by brentward** [comment]
Thanks,
I got both changes in separate commit named correctly.

**Comment by carlocab** [comment]
Before we merge this, I'd like an answer to my question in https://github.com/Homebrew/homebrew-core/issues/79932#issuecomment-867897897. I'm concerned that this is just a band-aid, and doesn't really fix the underlying problem (which is that, AFAICT, the `post_install` `PATH` seems to be broken sometimes).

**Comment by carlocab** [comment]
Oh whoops. `--skip-recursive-dependents` still tests immediate dependents. Which still takes too long. nvm.

**Review by carlocab — APPROVED** [review]
I think this change is fine to make. Also tested it locally to be sure (though I'm really not sure how this can break anything...)

**Pull request merged**
