### PR TITLE
cockatrice 2.6.0

### PR DESCRIPTION
**Pull request by tooomm**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Cockatrice/Cockatrice/releases/tag/2018-06-17-Release-2.6.0

Linking https://github.com/Homebrew/homebrew-core/pull/28190#issuecomment-397914297

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks again @tooomm! FYI from now on users will need to
```
brew cask install cockatrice
```
due to https://github.com/Homebrew/homebrew-core/pull/29152

See also https://github.com/Homebrew/homebrew-cask/pull/48575

**Comment by tooomm** [comment]
>FYI from now on users will need to
>
>       brew cask install cockatrice
>
>due to #29152

Will there be some kind of information or hint to a user doing
`brew install cockatrice`, `brew upgrade` or `brew upgrade cockatrice`?

<br>

Too bad this removes compatibility with https://github.com/Linuxbrew/brew. 😢

**Comment by ilovezfs** [comment]
>Will there be some kind of information or hint to a user doing
brew install cockatrice, brew upgrade or brew upgrade cockatrice?

Believe it or not, it's actually triggered on `brew update` and will automatically install the dmg.

>Too bad this removes compatibility with https://github.com/Linuxbrew/brew.

It's entirely up to https://github.com/Linuxbrew/homebrew-core whether to keep the formula. CC @iMichka

**Comment by ilovezfs** [comment]
Also note there is no Linux bottle right now https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/cockatrice.rb#L11-L15 so it wasn't working over there probably.

**Comment by iMichka** [comment]
Hi. Yes I think it was not building correctly on Linux.

We would accept a Linux-only formula, if it is building without error.

**Pull request closed without merging**
