### PR TITLE
grantlee: switch to Qt6

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
Please add label `help wanted`, I'm unsure how to pass test if `qt` is installed.

**Comment by yurikoles** [comment]
Commit with `grantlee-qt5` is optional and may be dropped.

**Comment by chenrui333** [comment]
looks like no space on the linux build
```
/tmp/qt-20221215-123200-1tynvv7/qt-everywhere-src-6.4.1/qtscxml/src/statemachine/qstatemachine.h:164:2: fatal error: cannot write PCH file: No space left on device
  164 | };
      |  ^
```

**Comment by SMillerDev** [comment]
I'd say we can drop the qt5 version since that qt isn't actively developed anymore.

**Comment by yurikoles** [comment]
Forgot to mention upstream PR: https://github.com/steveire/grantlee/pull/88

**Comment by yurikoles** [comment]
I dropped `grantlee-qt5`.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
