### PR TITLE
flow 0.24.2

### PR DESCRIPTION
**Pull request by gabelevi**

### CODE REVIEW

**Comment by DomT4** [comment]
`ocamlbuild` was removed from `ocaml` in the most recent release and shunted into its own project by upstream. You need to add an explicit `depends_on "ocamlbuild" => :build` line here if you need that functionality.

**Comment by DomT4** [comment]
Looks like there are additional issues. Fixing that problem results in getting past that error onto to run into:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:448:6: error: unknown type name 'uint32'; did you mean 'sint32'?
    (uint32 num,
     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmconfig.h:55:17: note: 'sint32' declared here
typedef int32_t sint32;
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Command exited with code 2.
make: *** [build-flow-native-deps] Error 10
```

**Comment by gabelevi** [comment]
Sorry, we hadn't realized homebrew had moved to OCaml 4.03.0 and didn't support building in it yet. Flow v0.25.0 will have support. Closing this out.

**Comment by DomT4** [comment]
Thanks @gabelevi.

Apologies for us missing that; we don't have the capacity to rebuild everything with a `depends_on "xyz" => :build` style dependency from source on upgrades so sometimes things like this slip through. We test formulae with hard runtime dependencies, but the size of our CI cluster limits expansion beyond that for now.

**Pull request closed without merging**
