### PR TITLE
nanopb-generator 0.4.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
It looks like protobuf python bindings does not work for py3.11, gonna do a rerun first before reverting to use py3.10. cc @cho-m

**Comment by cho-m** [comment]
```
ModuleNotFoundError: No module named 'google'
```

That's a sign that it isn't using the right Python. As long as it runs Homebrew's Python 3.10 or Python 3.11, a basic `import google` should work.

e.g.
```console
❯ /usr/bin/python3 -c 'import google'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'google'

❯ /opt/homebrew/bin/python3.11 -c 'import google'

❯ /opt/homebrew/bin/python3.10 -c 'import google'

```

**Comment by chenrui333** [comment]
> ```
> ModuleNotFoundError: No module named 'google'
> ```
> 
> That's a sign that it isn't using the right Python. As long as it runs Homebrew's Python 3.10 or Python 3.11, a basic `import google` should work.
> 
> e.g.
> 
> ```
> ❯ /usr/bin/python3 -c 'import google'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'google'
> 
> ❯ /opt/homebrew/bin/python3.11 -c 'import google'
> 
> ❯ /opt/homebrew/bin/python3.10 -c 'import google'
> ```

On the action runner, I could not test out the setup against python@3.11, but it works fine for python@3.10

**Comment by cho-m** [comment]
> On the action runner, I could not test out the setup against python@3.11, but it works fine for python@3.10

That is probably because it is symlinked, but will be broken again once we move alias.

Instead, should fix shebang:
```console
❯ head -1 bin/*
==> bin/nanopb_generator.py <==
#!@@HOMEBREW_PREFIX@@/opt/python@3.11/bin/python3.11

==> bin/protoc-gen-nanopb <==
#!/usr/bin/env python3
```

**Comment by chenrui333** [comment]
That is the right pointer, thanks @cho-m!

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
