### PR TITLE
perl 5.34.1

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
Does this need something besides restarting with longer timeout?

**Comment by pthariensflame** [comment]
Anyone have ideas for this?

**Comment by Bo98** [comment]
Biber is being tracked at #98483. I'll see if I can reproduce it locally.

**Comment by cho-m** [comment]
`biber` issue on macOS is due to the `test-dev.bcf` being updated probably to match development branch. The previous file is now `test.bcf`.

`biber` also has been failing on self-hosted Linux. Still haven't debugged, but current error is for `gnutls_handshake` so I may try to use Homebrew curl.

Anyway, can ignore in next attempt once CI long-timeout queue is freed up.

**Comment by cho-m** [comment]
Just remembered I never finished the PR to remove patch version & Cellar paths from `perl` (#84510) which is why some of these formulae need revision bumps on a patch release.

**Comment by chenrui333** [comment]
looks like only failed with `apt` and no one is using `apt`

```
==> Analytics
install: 1 (30 days), 1 (90 days), 6 (365 days)
install-on-request: 1 (30 days), 1 (90 days), 6 (365 days)
build-error: 1 (30 days)
```

**Pull request closed without merging**
