### PR TITLE
pgroonga 2.4.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Test fails with `Failed to execute: /opt/homebrew/opt/postgresql@15/bin/pg_ctl`

**Comment by Porkepix** [comment]
Changelog shows pgroonga to be compatible with PostGreSQL 15 since 2.4.1 and 2.4.2 though… https://pgroonga.github.io/news/#version-2-4-1

**Comment by carlocab** [comment]
> Changelog shows pgroonga to be compatible with PostGreSQL 15 since 2.4.1 and 2.4.2 though… https://pgroonga.github.io/news/#version-2-4-1

You forgot to change the
```ruby
depends_on "postgresql@14"
```

**Comment by kou** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/4364494128/jobs/7638179411#step:7:135

```text
    Errno::ENOENT: No such file or directory @ dir_initialize - /private/tmp/pgroonga-20230308-8099-1ux6e9j/pgroonga-2.4.5/stage/opt/homebrew/lib
```

https://github.com/Homebrew/homebrew-core/actions/runs/4364494128/jobs/7638179411#step:7:130

```text
  /bin/sh /opt/homebrew/opt/postgresql@15/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/private/tmp/pgroonga-20230308-8099-1ux6e9j/pgroonga-2.4.5/stage/opt/homebrew/opt/postgresql@15/lib/postgresql'
```

Should we update `File.join("stage", HOMEBREW_PREFIX)` to something like `File.join("stage", HOMEBREW_PREFIX, "opt", "postgresql@15")` too?

**Comment by kou** [comment]
Or:

```diff
diff --git a/Formula/pgroonga.rb b/Formula/pgroonga.rb
index b59c2027ce3..f470208708b 100644
--- a/Formula/pgroonga.rb
+++ b/Formula/pgroonga.rb
@@ -35,10 +35,9 @@ class Pgroonga < Formula
     mkdir "stage"
     system "make", "install", "DESTDIR=#{buildpath}/stage"
 
-    stage_path = File.join("stage", HOMEBREW_PREFIX)
-    lib.install (buildpath/stage_path/"lib").children
-    share.install (buildpath/stage_path/"share").children
-    include.install (buildpath/stage_path/"include").children
+    lib.install (buildpath/"stage"/postgresql.opt_lib).children
+    share.install (buildpath/"stage"/postgresql.opt_share).children
+    include.install (buildpath/"stage"/postgresql.opt_include).children
   end
 
   test do
```

**Comment by kou** [comment]
Ah, we need to remove the leading "/" from `postgresql.opt_*` to join with `buildpath/"stage"`:

```diff
diff --git a/Formula/pgroonga.rb b/Formula/pgroonga.rb
index 119e045b3b9..33a661ddfff 100644
--- a/Formula/pgroonga.rb
+++ b/Formula/pgroonga.rb
@@ -35,10 +35,12 @@ class Pgroonga < Formula
     mkdir "stage"
     system "make", "install", "DESTDIR=#{buildpath}/stage"
 
-    stage_path = File.join("stage", HOMEBREW_PREFIX)
-    lib.install (buildpath/stage_path/"lib").children
-    share.install (buildpath/stage_path/"share").children
-    include.install (buildpath/stage_path/"include").children
+    relative_pg_opt_lib = postgresql.opt_lib.relative_path_from("/")
+    relative_pg_opt_share = postgresql.opt_share.relative_path_from("/")
+    relative_pg_opt_include = postgresql.opt_include.relative_path_from("/")
+    lib.install (buildpath/"stage"/relative_pg_opt_lib).children
+    share.install (buildpath/"stage"/relative_pg_opt_share).children
+    include.install (buildpath/"stage"/relative_pg_opt_include).children
   end
 
   test do
```

**Comment by askdkc** [comment]
@Porkepix 

I think this PR should be closed.

Newer version of PGroonga is already merged.

https://github.com/Homebrew/homebrew-core/pull/126781

**Pull request closed without merging**
