### PR TITLE
crystal-lang 0.23.0

### PR DESCRIPTION
**Pull request by josacar**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Thanks in advance

### CODE REVIEW

**Comment by ilovezfs** [comment]
0.22.0 is still designated as the latest release: https://github.com/crystal-lang/crystal/releases

**Comment by ilovezfs** [comment]
CC @asterite is 0.23.0 the current stable version now?

**Comment by asterite** [comment]
@ilovezfs Thank you for letting me know about this.

@josacar Thank you for this, but I prefer if someone from the core team pushes homebrew releases. The team (I think @mgarciaisaia) was preparing this release but I think there were some problems. That's why I'm not sure it's a good idea to just send PRs here whenever there's a new tag.

I'm not in charge of releases anymore but I think this can be safely closed.

**Comment by ilovezfs** [comment]
@asterite you're welcome and thanks for the quick response!

**Comment by ilovezfs** [comment]
@josacar closing based on upstream guidance but thanks for the PR nonetheless!

**Comment by matiasgarciaisaia** [comment]
@ilovezfs 0.23.0 is the stable Crystal version _now_.

So @josacar's PR should be merged now.

Let me know if for any reason you prefer a new PR to be sent 👌

And thank you both for the support!

**Comment by MakeNowJust** [comment]
Crystal has man page of `crystal` command since 0.23.0, but this PR seems to forget to add it.

**Comment by ilovezfs** [comment]
@asterite @matiasgarciaisaia what version should be used for the bootstrap binary?

https://github.com/crystal-lang/crystal/releases/download/0.22.0/crystal-0.22.0-1-darwin-x86_64.tar.gz

https://github.com/crystal-lang/crystal/releases/download/0.23.0/crystal-0.23.0-1-darwin-x86_64.tar.gz

or something else?

**Comment by asterite** [comment]
The boot version should always be the previous version. In this case it should be 0.22.0

**Comment by matiasgarciaisaia** [comment]
@MakeNowJust we forgot to add the man page into the tar.gz, for a starter, so we'll probably add it to 0.23.1 or any future version.

@ilovezfs as @asterite said, the PR correctly states 0.22.0 as the boot version. This PR seems good to go 👍

**Comment by ilovezfs** [comment]
Shipped!

@josacar Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
