### PR TITLE
inxi 3.3.00-1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Error: inxi: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

**Comment by chenrui333** [comment]
> ```
> Error: inxi: failed
> An exception occurred within a child process:
>   Timeout::Error: execution expired
> ```

😓  it seems always behaving like that.

**Comment by carlocab** [comment]
I actually think I saw it succeed on Mojave in the first run. But I'm not 100% sure, so I don't feel confident about merging...

**Comment by carlocab** [comment]
I think I've re-run it thrice by now and it's timed out every time.

**Comment by carlocab** [comment]
All the tests have passed except for Mojave... So I think as soon as we see a Mojave ✅ this should be ready to 🚢.

**Review by carlocab — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @carlocab!!

**Pull request merged**
