### PR TITLE
netpbm: fix for Xcode 14.3

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This should allow us to rebuild this after #118902.

### CODE REVIEW

**Comment by Bo98** [comment]
Can you paste the error in this PR for future reference?

**Comment by carlocab** [comment]
```
nstring.c:625:21: error: call to undeclared library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                    snprintf(f, ARRAY_SIZE(f), "%%%u.%uf",
                    ^
nstring.c:625:21: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
nstring.c:793:30: error: call to undeclared library function 'strdup' with type 'char *(const char *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    const char * const dup = strdup(arg);
                             ^
nstring.c:793:30: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
nstring.c:811:10: error: call to undeclared function 'vasprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    rc = vasprintf((char **)&result, fmt, varargs);
         ^
nstring.c:811:10: note: did you mean 'vsprintf'?
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/stdio.h:209:6: note: 'vsprintf' declared here
int      vsprintf(char * __restrict, const char * __restrict, va_list) __printflike(2, 0);
         ^
```

**Comment by Bo98** [comment]
Thanks. Looks like the issue is something is setting `_ANSI_SOURCE` or `_POSIX(_C)_SOURCE` or `_XOPEN_SOURCE` that previously didn't.

**Review by SMillerDev — APPROVED** [review]
Not gonna block this on it, but I would like this reported upstream

**Comment by carlocab** [comment]
> Not gonna block this on it, but I would like this reported upstream

Reported upstream via email.

**Pull request merged**
