### PR TITLE
geckodriver 0.26.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
install step failed

```
23:28:45 ==> cargo install --root /usr/local/Cellar/geckodriver/0.26.0 --path .
23:28:45 error: `/private/tmp/geckodriver-20191012-64895-17lpif8/geckodriver-0.26.0` does not contain a Cargo.toml file. --path must point to a directory containing a Cargo.toml file.
```

**Comment by chenrui333** [comment]
https://github.com/mozilla/geckodriver/releases/tag/v0.26.0

> Note to macOS Catalina users: Due to the recent requirement
from Apple that all programs be notarized, geckodriver will
not work on Catalina. We are working on a fix for this
and you can follow the progress on this in bug 1588081.

> Note also that with this release the minimum recommended Firefox version
has changed to Firefox ≥60.

**Comment by chrmoritz** [comment]
Looks like the GitHub tag for this doesn't contain any source code at all. Might need to check out their hg repository for commit `e9783a644016aa9b317887076618425586730d73` to get the actual source code for this release (similar to HEAD build).

**Comment by chenrui333** [comment]
Yeah, that is interesting comment, let me switch to use git-tag thing.

**Comment by chrmoritz** [comment]
No, I meant they didn't published the source code for 0.26.0 on GitHub at all. Previously they at least pushed the source code with the corresponding tags only. Not it looks like it's only available in their hg repository.

**Comment by chenrui333** [comment]
ok, I will submit a issue in their repo to see how it goes.

**Comment by andreastt** [comment]
Hi, the maintainer of geckodriver here.

> No, I meant they didn't published the source code for 0.26.0 on GitHub at all. Previously they at least pushed the source code with the corresponding tags only. Not it looks like it's only available in their hg repository. Not sure if this was intended or not.

Some Rust crate dependencies now exist only in source form inside [mozilla-central](https://hg.mozilla.org/mozilla-unified/), and their releases are not always coordinated with geckodriver. If geckodriver works with a pinned, previous crate version this is more incidental than intended. It used to be a best-effort process to put together something that built outside of the canonical source code repository, but this is no longer possible.

Because we [publish release binaries](https://github.com/mozilla/geckodriver/releases) that require secret signing keys (and soon notarisation) from the [Firefox build/CI system](https://treeherder.mozilla.org/), we can no longer guarantee that a source code export with pinned crate dependencies will make a reproducible build.

I was not aware geckodriver was released on Homebrew and I’m sorry for the trouble this causes you. Please let me know if there’s anything I can do or questions I can answer that will make it possible for you to resolve this breakage.

**Comment by andreastt** [comment]
I forgot to mention that once you have a [mozilla-central](https://hg.mozilla.org/mozilla-unified/) checkout of the Mercurial SHA-1 mentioned in the [release notes](https://github.com/mozilla/geckodriver/releases), you should be able to follow the build instructions documented here: https://firefox-source-docs.mozilla.org/testing/geckodriver/Building.html

You may need to run `./mach configure` first. If that doesn’t work you may also need `./mach bootstrap` to get all the right build dependencies.

**Comment by chenrui333** [comment]
That sounds about right, I will close the PR for now.

**Pull request closed without merging**
