### PR TITLE
bazel 0.17.2

### PR DESCRIPTION
**Pull request by phedoreanu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by phedoreanu** [comment]
```
15:57:37 Caused by: java.io.IOException: Cannot run program "git" (in directory "/Users/brew/Jenkins/workspace/Homebrew Core Pull Requests/version/mojave_testing"): error=0, posix_spawn failed
```

**Comment by phedoreanu** [comment]
@BrewTestBot test this please

**Comment by phedoreanu** [comment]
@fxcoudert please merge it 😃

**Comment by fxcoudert** [comment]
Thanks @phedoreanu

**Comment by phedoreanu** [comment]
@fxcoudert Wrong button? 🤔

**Comment by mpassell** [comment]
@phedoreanu Was there a reason you did this, rather than using the tap provided by the Bazel project? See https://docs.bazel.build/versions/master/install-os-x.html#install-on-mac-os-x-homebrew and https://blog.bazel.build/2018/08/22/bazel-homebrew.html for the preferred way to install Bazel via homebrew.

**Comment by phedoreanu** [comment]
@mpassell Because there was already a PR opened and I wanted to have the `brew` formula at the latest version. We can deprecate it now...

**Comment by fxcoudert** [comment]
Given that at least one other formula in Homebrew core depend on `bazel` to build (namely `libtensorflow`), we have to figure out a way forward…

**Pull request closed without merging**
