### PR TITLE
julia: fix build on Linux

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

~~Julia needs both `libunwind` and `llvm` but they conflict on Linux.
Since we have no way to resolve that conflict, let's just use Julia's
vendored `libunwind` on Linux instead.~~ [*]

~~This can be changed if/when Julia switches to using LLVM's libunwind on
Linux, as it currently does on HEAD for macOS.~~

Julia fails to build with GCC 5.

While we're here, let's clean up the ARM-specific logic, since it
doesn't actually produce a successful ARM build.

[*] ~~See comment below for one way to resolve the conflict.~~ Resolved in #80915.

### CODE REVIEW

**Comment by carlocab** [comment]
An alternative fix here that would all Julia to keep using Homebrew `libunwind` instead of a vendored one would be to rename either LLVM's `libunwind.a` or `libunwind`'s `libunwind.a`.

**Comment by carlocab** [comment]
We should be able to keep using Homebrew `libunwind` on Linux if #80915 is merged.

**Comment by carlocab** [comment]
Nope, `libunwind` still installs a conflicting `libunwind.so`. I missed that despite checking the bottles...

**Comment by carlocab** [comment]
We should merge #80962 before this one, so that a new bottle can be uploaded there, and this one can be merged without bottles (and the Linux bottle for Julia built separately).

**Review by danielnachun — APPROVED** [review]

**Comment by carlocab** [comment]
Dispatching a bottle separately.

**Pull request merged**
