### PR TITLE
fstar: make ocaml a required dependency

### PR DESCRIPTION
**Pull request by ilovezfs**
instead of build-time or recommended.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @s-zanella

### CODE REVIEW

**Comment by ilovezfs** [comment]
@s-zanella I'm assuming this isn't actually needed at run time?

**Comment by ilovezfs** [comment]
Or given what's in the caveat, maybe we should just require it.

**Comment by s-zanella** [comment]
FStar is still usable as a theorem prover without OCaml, but I assume most users would like to extract FStar programs to OCaml and be able to compile and run them. I'm fine either way.

**Comment by ilovezfs** [comment]
The analytics don't show anyone using the --without-ocaml option, so we'll just require it.

**Comment by s-zanella** [comment]
I was about to push a last change to my previous PR, but is now closed: https://github.com/Homebrew/homebrew-core/compare/master...s-zanella:fstar-0.9.6.0
Should be combine these new changes with this PR?

**Comment by ilovezfs** [comment]
@s-zanella what change did you want to make?

**Comment by s-zanella** [comment]
It doesn't make sense to pin specific versions of OPAM packages now that the formula uses the system OCaml compiler.
The change is here: https://github.com/Homebrew/homebrew-core/compare/master...s-zanella:fstar-0.9.6.0

**Comment by ilovezfs** [comment]
@s-zanella OK I added that commit to the PR.

**Comment by s-zanella** [comment]
Thanks!

**Pull request closed without merging**
