### PR TITLE
mbedtls: enable psa config

### PR DESCRIPTION
**Pull request by zhang-wenchao**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Could you comment on what is gained and what are the risks/downsides of this?

Also, the doc for PSA drivers (https://github.com/Mbed-TLS/mbedtls/blob/development/README.md#psa-drivers) states: _“When using drivers, you will generally want to enable two compilation options”_. And this seems important for us: _“This is work in progress. Please note that the driver interfaces are not fully stable yet and may change without notice.”_

**Comment by zhang-wenchao** [comment]
Since I'm using psa crypto, the interface is stable.

**Comment by zhang-wenchao** [comment]
MBEDTLS_USE_PSA_CRYPTO can be left on to preserve compatibility.

**Comment by zhang-wenchao** [comment]
Use psa api : https://github.com/butterfly-communtiy/ohw-wallets

**Comment by zhang-wenchao** [comment]
https://github.com/Mbed-TLS/mbedtls/issues/8147

**Comment by daeho-ro** [comment]
@zhang-wenchao Can you rebase this branch? Tests got stuck and so that is the only option for now.

**Comment by fxcoudert** [comment]
At this stage, it seems no real rationale (except personal use) was given, and the pros and cons are not discussed. It seems (from the links given, without any comment) that this will be enabled by default in an upcoming version. So we will pass on this PR, and wait for it to be the default.

**Comment by zhang-wenchao** [comment]
Yes, close this pr for now, psa on will become the default in the next version.

**Comment by zhang-wenchao** [comment]
update: 4.0.0-beta version has become the default.

**Pull request closed without merging**
