### PR TITLE
openrct2 0.3.5

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
On _Monterey_:
```
In file included from /tmp/openrct2-20211107-15505-1o8t3aq/src/openrct2/CmdlineSprite.cpp:16:
In file included from /tmp/openrct2-20211107-15505-1o8t3aq/src/openrct2/core/Json.hpp:15:
In file included from /usr/local/include/nlohmann/json.hpp:51:
In file included from /usr/local/include/nlohmann/adl_serializer.hpp:6:
/usr/local/include/nlohmann/detail/conversions/from_json.hpp:453:57: error: 'path' is unavailable: introduced in macOS 10.15
void from_json(const BasicJsonType& j, std::filesystem::path& p)
                                                        ^
```

**Comment by carlocab** [comment]
Try setting `-DCMAKE_OSX_DEPLOYMENT_TARGET=#{MacOS.version}`, since the CMake cache has this set to 10.14 for some reason.

**Review by carlocab — DISMISSED** [review]
Linux failure is pre-existing.

**Comment by carlocab** [comment]
Probably also needs `fontconfig` and `mesa` on Linux, though their README says these can be disabled.

**Review by carlocab — DISMISSED** [review]
Let's fix the Linux bottle in a separate PR.

**Comment by EricFromCanada** [comment]
I'll attempt to get it to build.

**Comment by carlocab** [comment]
Oops, ok. Merge cancelled.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
