### PR TITLE
duck 6.8.2

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
Error: Failed changing dylib ID of /usr/local/Cellar/duck/6.8.2.28974/libexec/Contents/Frameworks/libcore.dylib
  from /usr/local/opt/duck/libexec/Contents/Frameworks/libcore.dylib
    to @@HOMEBREW_PREFIX@@/opt/duck/libexec/Contents/Frameworks/libcore.dylib
==> Bottling duck--6.8.2.28974.mojave.bottle.tar.gz...
Error: Updated load commands do not fit in the header of /usr/local/Cellar/duck/6.8.2.28974/libexec/Contents/Frameworks/libcore.dylib. /usr/local/Cellar/duck/6.8.2.28974/libexec/Contents/Frameworks/libcore.dylib needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
```

**Comment by dkocher** [comment]
Not sure why this was not an issue for previous builds. We will add `OTHER_LDFLAGS=-headerpad_max_install_names` then to our build options. Is it possible to add this to the environment for this version in the formula? Otherwise we will have to skip this version and wait for the next update with the build option included.

**Comment by fxcoudert** [comment]
Normally our build scripts (superenv) does that by itself, and it is transparent to formulas. One possibility is that the header, even packed to the maximum size, is still not large enough to accommodate the rewriting of dylib paths… this needs to be investigated.

**Comment by SMillerDev** [comment]
@fxcoudert ever found the issue?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by dkocher** [comment]
Anything expected from me to resolve this?

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
Error: Updated load commands do not fit in the header of /usr/local/Cellar/duck/6.8.2.28974/libexec/Contents/Frameworks/libcore.dylib. /usr/local/Cellar/duck/6.8.2.28974/libexec/Contents/Frameworks/libcore.dylib needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
```

It's possible the build process is stripping superenv's `-headerpad_max_install_names`

**Pull request closed without merging**
