### PR TITLE
gdal: try to handle Java... better

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
This blows up if you replace `"JAVA_HOME=$(shell echo $$JAVA_HOME)"` with `"JAVA_HOME=#{Language::Java.java_home_env("1.8")}"` so I'm a little unsure what to do here re the audit.

**Comment by ilovezfs** [comment]
I think you want `Language::Java.java_home_cmd("1.8")` not `Language::Java.java_home_env("1.8")`

**Comment by DomT4** [comment]
Yeah, tried that after spotting the mistake but it's still blowing. Currently trying the positively silly:
```ruby
          s.gsub! "#JAVA_HOME = /usr/lib/jvm/java-6-openjdk/",
                  "JAVA_HOME=$(shell echo #{Language::Java.java_home_cmd("1.8")})"
```

**Comment by ilovezfs** [comment]
maybe needs two $

**Comment by ilovezfs** [comment]
Don't think you need that echo

**Comment by ilovezfs** [comment]
```
inreplace "java.opt",  "= /usr/lib/jvm/java-6-openjdk/", "= $(shell #{Language::Java.java_home_cmd("1.8")})"
```

**Comment by DomT4** [comment]
Do we need to do anything about the `#` that prepends `#JAVA_HOME =`? I assumed since that gets changed that `#` meant _"Ignore me"_ in a similar way that it does in Ruby.

**Comment by ilovezfs** [comment]
and `"#JAVA_HOM", "JAVA_HOM"`should work lol

**Comment by DomT4** [comment]
```ruby
        inreplace "java.opt" do |s|
          s.gsub! "linux", "darwin"
          s.gsub! "#JAVA_HOME = /usr/lib/jvm/java-6-openjdk/",
                  "JAVA_HOME = $(shell #{Language::Java.java_home_cmd("1.8")})"
        end
```
works if you can tolerate that.

**Comment by ilovezfs** [comment]
won't that trigger the audit?

**Comment by DomT4** [comment]
Hahahahahaha it does. Kill me now.

**Comment by ilovezfs** [comment]
I guess we could use regex

**Comment by ilovezfs** [comment]
```
inreplace "java.opt", /#(.* = )/usr/lib/jvm/java-6-openjdk/",
                      "\\1$(shell #{Language::Java.java_home_cmd("1.8")})"
```

**Comment by DomT4** [comment]
This is becoming increasingly upsetting 😅.

**Comment by ilovezfs** [comment]
I guess there are two so
```
        inreplace "java.opt" do |s|
          s.gsub! "linux", "darwin"
          s.gsub! /#(.* = )/usr/lib/jvm/java-6-openjdk/",
                  "\\1$(shell #{Language::Java.java_home_cmd("1.8")})"
        end
```

**Comment by DomT4** [comment]
Yeah the next commit which isn't pushed yet is actually `gdal: use block inreplace`.

**Comment by DomT4** [comment]
```ruby
        inreplace "java.opt" do |s|
          s.gsub! "linux", "darwin"
          s.gsub! %r{#(.* = )/usr/lib/jvm/java-6-openjdk/},
                  "\\1$(shell #{Language::Java.java_home_cmd("1.8")})"
        end
```

```
gdal:
  * Use `depends_on :java` to set JAVA_HOME
Error: 1 problem in 1 formula
```

Please tell me it is not being triggered by the `java_home` part of `java_home_cmd`.

**Comment by ilovezfs** [comment]
yes the /i

**Comment by ilovezfs** [comment]
Please remind me why we use audits.

**Comment by DomT4** [comment]
Something about saving us time & misery wasn't it? Ha. Ha. Haha. Hahahaha. Ha.

**Comment by ilovezfs** [comment]
```
        inreplace "java.opt" do |s|
          s.gsub! "linux", "darwin"
          javahome_cmd = "/usr/libexec/java_"
          javahome_cmd += "home --version 1.8"
          s.gsub! %r{#(.* = )/usr/lib/jvm/java-6-openjdk},
                  "\\1$(shell #{javahome_cmd}"
        end
```

**Comment by DomT4** [comment]
We may have to accept the audit needs some work here.

**Comment by DomT4** [comment]
By which I mean, the audit is being ridiculous.

**Comment by ilovezfs** [comment]
```
diff --git a/Formula/gdal.rb b/Formula/gdal.rb
index f491e60..44f169f 100644
--- a/Formula/gdal.rb
+++ b/Formula/gdal.rb
@@ -79,12 +79,12 @@ class Gdal < Formula
     depends_on "json-c"
   end
 
+  depends_on :java => ["1.8", :optional]
   if build.with? "java"
     depends_on "ant" => :build
     depends_on "swig" => :build
     # Technically 1.7+ but definitely not Java 9.
     # "bootstrap class path not set in conjunction with -source 1.4"
-    depends_on :java => "1.8"
   end
 
   depends_on "python" => :optional if MacOS.version <= :snow_leopard
@@ -305,8 +305,11 @@ class Gdal < Formula
 
     if build.with? "java"
       cd "swig/java" do
-        inreplace "java.opt", "linux", "darwin"
-        inreplace "java.opt", "#JAVA_HOME = /usr/lib/jvm/java-6-openjdk/", "JAVA_HOME=$(shell echo $$JAVA_HOME)"
+        inreplace "java.opt" do |s|
+          s.gsub! "linux", "darwin"
+          s.gsub! "#JAVA_HOME = /usr/lib/jvm/java-6-openjdk/",
+                  "JAVA_HOME = $(shell #{Language::Java.java_home_cmd("1.8")})"
+        end
         system "make"
         system "make", "install"
 
```

**Comment by DomT4** [comment]
Yeah alright, I can tolerate that as a workaround.

**Comment by ilovezfs** [comment]
It's not actually a workaround since technically `depends_on :java => ["1.8", :optional]` is more correct anyway.

**Comment by DomT4** [comment]
Alright. Review to your heart's content.

**Comment by ilovezfs** [comment]
I guess If we had something like
```
option "arbitrary-option-name" do
  depends_on :java => "1.8"
end
```
we could probably make it so `foo.requirements` isn't blind to those.

**Comment by DomT4** [comment]
Yeah various similar things have been discussed before. Just one of those things nobody loves the idea of enough to actually do the work for, so the status quo persists.

**Comment by ilovezfs** [comment]
Also it's a pretty ugly DSL :(

**Comment by ilovezfs** [comment]
I'd leave `numpy` at the old version since that's what was current when this shipped.

**Comment by DomT4** [comment]
I was mostly banishing the audit warning about the URL. Do you want it back completely or do you want the URL updated to the current standard with the existing version?

**Comment by ilovezfs** [comment]
I'd leave it with the "bad url" so this is a java-only pr.

**Comment by DomT4** [comment]
Alright, at least that only involved punting a commit out of existence. Done.

**Comment by ilovezfs** [comment]
:globe_with_meridians:

**Comment by DomT4** [comment]
:tada:

**Pull request merged**
