### PR TITLE
pandoc-citeproc 0.16.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
23:18:03 Downloading the latest package list from hackage.haskell.org
23:18:03 ==> cabal v1-install --jobs=6 --max-backjumps=100000 --only-dependencies
23:18:03 clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
23:18:03 clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
23:18:03 clang: warning: argument unused during compilation: '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
23:18:03 Resolving dependencies...
23:18:03 cabal: Could not resolve dependencies:
23:18:03 [__0] trying: pandoc-citeproc-0.16.3 (user goal)
23:18:03 [__1] trying: pandoc-2.7.3 (dependency of pandoc-citeproc)
23:18:03 [__2] trying: haddock-library-1.7.0 (dependency of pandoc)
23:18:03 [__3] next goal: base (dependency of pandoc-citeproc)
23:18:03 [__3] rejecting: base-4.13.0.0/installed-4.1... (conflict: haddock-library =>
23:18:03 base>=4.5 && <4.13)
23:18:03 [__3] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
23:18:03 base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
23:18:03 base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
23:18:03 base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
23:18:03 base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
23:18:03 base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
23:18:03 non-upgradeable package requires installed instance)
23:18:03 [__3] fail (backjumping, conflict set: base, haddock-library, pandoc-citeproc)
23:18:03 After searching the rest of the dependency tree exhaustively, these were the
23:18:03 goals I've had most trouble fulfilling: pandoc, haddock-library,
23:18:03 pandoc-citeproc, base
23:18:03 Try running with --minimize-conflict-set to improve the error message.
23:18:03 Note: when using a sandbox, all packages are required to have consistent
23:18:03 dependencies. Try reinstalling/unregistering the offending packages or
23:18:03 recreating the sandbox.

**Comment by nateberkopec** [comment]
ghc is installing base 4.13, which is explicitly not allowed by haddock-library.

As an end-user, you can fix this by installing an older version of GHC. As for this formula, I guess we have to go fix haddock-library or mark a requirement that it needs ghc <= some_ver.

**Comment by chenrui333** [comment]
@nateberkopec, doing that now, thanks for the guidance!

**Comment by chenrui333** [comment]
Seems still failing with ghc@8.6
```
==> cabal v1-update
Downloading the latest package list from hackage.haskell.org
==> cabal v1-install --jobs=8 --max-backjumps=100000 --only-dependencies
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/opt/ghc@8.6/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-citeproc-0.16.3 (user goal)
[__1] trying: pandoc-2.7.3 (dependency of pandoc-citeproc)
[__2] next goal: haddock-library (dependency of pandoc)
[__2] rejecting: haddock-library-1.8.0 (conflict: pandoc =>
haddock-library>=1.7 && <1.8)
[__2] trying: haddock-library-1.7.0
[__3] trying: base-4.12.0.0/installed-4.1... (dependency of pandoc-citeproc)
[__4] next goal: HsYAML (dependency of pandoc-citeproc)
[__4] rejecting: HsYAML-0.2.0.0 (conflict: pandoc => HsYAML>=0.1.1.1 && <0.2)
[__4] rejecting: HsYAML-0.1.2.0, HsYAML-0.1.1.3, HsYAML-0.1.1.2,
HsYAML-0.1.1.1, HsYAML-0.1.1.0, HsYAML-0.1.0.0 (conflict: pandoc-citeproc =>
HsYAML>=0.2 && <0.3)
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
