### PR TITLE
texlab 2.2.1

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by clason** [comment]
(for #68301)

**Comment by carlocab** [comment]
Hm, no, still doesn't build on ARM. Can you try replacing this line

https://github.com/Homebrew/homebrew-core/blob/ab89e775f02684a3a245462dc84d30f1949d3a97/Formula/texlab.rb#L20

with
```ruby
system "cargo", "install", "--root", prefix, "--path", "."
```

If this replacement works then there's still something wrong with `texlab`'s `Cargo.lock` file.

**Comment by clason** [comment]
It may be due to the build steps for one of the dependencies. (I unfortunately don't have an M1 machine to test.) I'm reporting this upstream.

**Comment by carlocab** [comment]
>I unfortunately don't have an M1 machine to test.

Yes, that's why we're going to test it on the ARM runner. Hang on, let me just add a commit to this PR.

**Comment by carlocab** [comment]
Nope, dropping the `--locked` flag doesn't seem to help. Dropping that commit. Hopefully upstream have a better idea of what's going on.

**Comment by richiksc** [comment]
I've looked at the failure output for the 11-arm build. The build script is calling `clang` with the Rust target triple of `aarch64-apple-darwin`. I tried compiling a simple "Hello, World" C program locally using `clang --target=aarch64-apple-darwin hello.c`, and sure enough, I got the same error:

```
% clang --target=aarch64-apple-darwin hello.c
error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
```

The Clang target triple for Apple Silicon is `arm64-apple-darwin`, and you can verify this by running `clang --version`.

When compiled with `--target-arm64-apple-darwin`, sure enough, it works fine.

```
% clang --target=arm64-apple-darwin hello.c
% ./a.out
Hello, world!
```

I'll open an upstream PR to fix this.

**Comment by richiksc** [comment]
I've opened a new PR latex-lsp/texlab#346 that updates the bibutils-sys version to the one that uses the new `cc` crate. Once that's merged and a new point version is released, it should build successfully on Homebrew CI.

**Comment by clason** [comment]
closing in favor of #68708, which should fix the errors.

**Pull request closed without merging**
