### PR TITLE
druid: fix test for Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I'll upstream my patch if it works.

**Comment by iMichka** [comment]
Waiting for a quick upstream patch review: https://github.com/apache/druid/pull/12014

**Comment by iMichka** [comment]
Upstream merged the patch. As the folder structure of their release tarball is different, I am keeping the slightly different inline patch for now. I added a comment to remove this patch for the next release.

**Review by chenrui333 — APPROVED** [review]
LGTM. 🚀

**Pull request closed without merging**
