### PR TITLE
glooctl: migrate to solo-io/tap

### PR DESCRIPTION
**Pull request by scranton**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by scranton** [comment]
https://github.com/solo-io/homebrew-tap/pull/1

**Comment by zbeekman** [comment]
Why?

**Comment by scranton** [comment]
We need more control. Some PRs are taking a long time to get accepted - appreciated its OSS and volunteer maintainers. I'm in the process of integrating these formulas with our build system, and I'm worried the rate of change will make things worse as they are currently set up. With a tap, we have a lot more control over keeping the formulas current and in sync.

**Comment by zbeekman** [comment]
FYI, We don't accept 3rd party taps in tap migrations. If you browse the `tap_migrations.json` file you won't see any taps outside of the homebrew org. We cannot redirect users blindly to 3rd party taps because it is a security risk for us, and violates user's trust of our software quality assurance practices.

You're always welcome to run your own 3rd party tap in parallel to our homebrew/core tap. In addition, the formula does provide a head url to build from source for the impatient.

On your website, you can even point users to your own tap. However, I don't think it makes sense to remove this from Homebrew. We will do our best to review PRs in a timely fashion.

**Comment by scranton** [comment]
I would not classify moving a formula to a tap hosted by the originating github.com org as a blind 3rd party tap. If anything it should increase confidence in the formula knowing that the same org that publishes the deployed code is directly managing the Homebrew formula. The Homebrew team has no way to provide better quality assurance than the originating project. I included the tap_migration.json patch specifically because of your documentation https://docs.brew.sh/Migrating-A-Formula-To-A-Tap.

The formula does now add a head URL, which took over a week to accept that PR, and I added that specifically because of how long it was taking to get version bumps to the formula. And by the time that head PR got accepted, the formula was 4 versions behind.

I appreciate that Homebrew is managed by volunteer maintainers, and it serves a great service. I also like that Homebrew provides a mechanism, Tap, to handle exactly this situation, that is the publishing software entity wants to have more control over the release process, and we want to seamlessly plug into the Homebrew toolchain. Why else do you support tap, if not for this reason?

Its become quickly apparent after I submitted this formula that our Gloo project release cadence is much faster than what we can reasonably expect the dedicated Homebrew maintainers to keep up with. We'd still like to allow Gloo users who depend on Homebrew to still use that tool, so we'd like to take more ownership of maintaining this and related formulas for our Github.com org.

I am really puzzled why Homebrew is denying the original author of this formula the ability to provide a higher quality offering by managing this formula in the same place as the software and more tightly integrating it with our release process. And how confusing to homebrew users to be the software publisher and tell them "Don't use the homebrew core version of the formula because it's out of date; use our provided formula instead.'

Please explain to me why you are making this very odd decision?

**Comment by zbeekman** [comment]
@scranton Thank you for sharing your opinions.

This topic has been discussed before. For an example of arguments pro and con, please see the discussion at: https://github.com/Homebrew/homebrew-core/pull/33268

I will respond briefly to some of your points here, however, I don't think we have the energy or desire to rehash this topic beyond what I'll add below.

> If anything it should increase confidence in the formula knowing that the same org that publishes the deployed code is directly managing the Homebrew formula. 

We have no idea if you test natively on all 3 macOS systems we officially support, and have no guarantees or insights into your org and QA process. We have a process for vetting maintainers, and formulae. Users have decided to place their trust in us and our processes; redirecting users without warning to another source would mean that we are vouching for that source, and we have no way of doing so.

>The formula does now add a head URL, which took over a week to accept that PR, and I added that specifically because of how long it was taking to get version bumps to the formula. And by the time that head PR got accepted, the formula was 4 versions behind.

I'm sorry to hear that. As you noted we are volunteers, and our CI infra needs upgrading; it falls over from time to time. We are hoping Azure will come around to supporting the 3 latest macOS releases, but for now we have to maintain our own CI infra in addition to the package manager and formulae. Sometimes things get stuck. You're welcome to host a tap in addition to homebrew-core, or point your users to some alternate installation method if you find homebrew unsuitable for your needs.

> I included the tap_migration.json patch specifically because of your documentation [docs.brew.sh/Migrating-A-Formula-To-A-Tap](https://docs.brew.sh/Migrating-A-Formula-To-A-Tap).

Thank you for pointing this out. IMO, this should be updated to explicitly address the purpose. For Homebrew maintained taps, it's purpose is to migrate between homebrew maintained taps. 3rd party taps can utilize migration info as they see fit.

> I am really puzzled why Homebrew is denying the original author of this formula the ability to provide a higher quality offering by managing this formula in the same place as the software and more tightly integrating it with our release process. And how confusing to homebrew users to be the software publisher and tell them "Don't use the homebrew core version of the formula because it's out of date; use our provided formula instead.'

As I said, you're welcome to provide your own tap and/or recommend other installation mechanisms. If your software is open source, then it may be freely distributed by others, like homebrew.

Our preference is to do our best to update your formula in a timely fashion, and work with you. You could, for example, integrate `brew bump-formula-pr` into your CI/CD workflow to automatically submit PRs when a new release is minted.

Best wishes,
-Z

**Comment by zbeekman** [comment]
I will also note, that, beyond exploring more robust CI solutions, we are actively pursuing mechanisms to automatically merge simple/easy version bumps once CI is green, such as those made with `brew bump-formula-pr`.

**Comment by MikeMcQuaid** [comment]
> I am really puzzled why Homebrew is denying the original author of this formula the ability to provide a higher quality offering by managing this formula in the same place as the software and more tightly integrating it with our release process.

To flip it round: I'm confused as to why authors of software believe they have the right to tell a package manager to no longer package their software and require all current Homebrew users of that software change their installation method.

Homebrew's position here is standard for package managers. We respect the wishes of upstream authors where they do not conflict with the experience of our users.

**Comment by scranton** [comment]
This is OSS, and yes people can what the license says. My goal was only in providing a better experience for glooctl users. I submitted this PR following your documentation; not out of a sense of privilege. I admit I was/am confused by the rejection as I thought our goals were aligned in that both our communities are trying to ensure an easy way to install/upgrade software.  

I am a homebrew user both to install software AND in providing a formula, and its this later user experience that I'm struggling with. Perhaps I don't fully understand Homebrew mission; I've always seen it as a great way to install/upgrade software and dependencies, and allowing me to pin a version if needed. I personally did not view Homebrew as responsible for managing specific binary builds or reproducible build from source - if there was an issue with any formula, I always viewed that as an issue with the software package provider. Hence my desire to update to a mechanism we feel is better able to get the formula up to date. I thought that was in line with Homebrew's goals, but it's feeling like I'm mistaken.

Homebrew has a feature, Tap, that appears to provide a way to manage brew user experience in letting them know the formula has moved, and brew users can choose to continue using that migrated formula OR choose another path, including writing their own formula. That Homebrew feature looked like it would make it easier for us, a Homebrew user as formula maintainer. If you allowed for tap_migration info to be allowed in certain cases, like when the original formula author asks to migrate that same formula to the same org as the installed software with the goal of enhancing user experience long term, IMO feels like that addresses everyone's goal, but that is just my opinion.

In the other thread, you asked for specifics on why we feel the need to move from core to a tap. glooctl is a tool, like kubectl, that is built to interact with a Kubernetes cluster. This makes it very difficult to include any sort of realistic testing in the `test do` block as it feels unreasonable to me to pull down say `minikube` just to run some build tests in homebrew. So the tests that are there are somewhat basic. We recently had a change in the version string, and this broke the formula, and it took a few days for that patch to get accepted. I get and greatly appreciate the volunteer maintainers - just saying this change and delay impacted both of our users. We also recently had a CVE within dependent software and again a couple of days delay in getting an update pushed through homebrew core. I added the `head` tag in response to allow people an out to update given these delays, and that head PR took well over a week to get reviewed and accepted.

I love brew and greatly appreciate you all volunteer maintainers. You've currently got a manual PR review process, which is your choice, and that seems to add delays. I was trying to leverage a documented Homebrew feature to improve the experience for both of our user bases. This is all OSS, and like has been pointed out, you can do what you want. My ask is also to please consider the perspective of your formula maintainers who are also homebrew users, as those users I believe share your desire to allow people to have a great experience with homebrew to install/upgrade software.

We plan on using a Tap and documenting the software as such. If I can update our build processes to also update the core version if that continues to exist, I will try to do that. Thanks for the great work you do in the brew community, and your attention to my concerns around this PR.

**Comment by zbeekman** [comment]
Thanks for your detailed and considerate response. I think for now the path you've outlined is the best recourse: maintain your own tap and try to integrate `brew bump-formula-pr` into your release process in an automated fashion. As we improve our CI infra and work towards greater automation in merging revision bumps, hopefully this friction will be reduced. At any rate, between the head block and your own tap, users needing an immediate release or fix should be able to get one.

Thanks for sharing your opinions in a kind and respectful way. That certainly is not always the case when we have differences of opinions with package contributors or upstream.

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words @scranton. I would say that we've been having some CI hardware issues lately which may be part of the reason for the delay. If it will help in future you can feel free to CC me personally on any PR to speed up the merge process and then it is unlikely to take more than 24-48h (and, if I'm at a computer before that, may take ~5m).

**Comment by scranton** [comment]
Very much appreciate the offer.

May I also ask that you update the Homebrew migrate tap documentation to more accurately reflect when that should be used, and some of your community policies that have been discussed in this in other threads... Very frustrating as a contributor to feel I've done the extra work to research the right way to submit a change and work within the community, only to be told No it doesn't work that way despite what the doc or other things say... Making that change me help lower the temperature of any future PRs like this.

Thanks again for a great brew!

**Comment by zbeekman** [comment]
Another suggestion: version bumps that mitigate CVEs could have prominent titles to include something to that effect. Then we can tag them and prioritize them.

**Pull request closed without merging**
