### PR TITLE
p11-kit:  Versioning fixes.

### PR DESCRIPTION
**Pull request by RandomDSdevel**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] ~~Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?~~  (N/A:  This is a formula _revision_.)  

---

Moves v0.23.2 of p11-kit to `devel` status and (correctly) gives v0.22.1 of the software `stable` status.

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
@dunn, @ilovezfs, @DomT4, @toonetown, @dwmw2, @MikeMcQuaid, @nmav:  Here's that PR I promised to submit in my comments (relevant ones starting [hereabouts](https://github.com/Homebrew/homebrew-core/commit/46be01e503df1e30dba395bffd87d2619e117748#commitcomment-19246722)) on [the 'p11-kit: add 0.23.2 bottle.' commit](https://github.com/Homebrew/homebrew-core/commit/46be01e503df1e30dba395bffd87d2619e117748).

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by DomT4** [comment]
We may end up reverting this depending on how the resolution to https://github.com/Homebrew/homebrew-core/commit/46be01e503df1e30dba395bffd87d2619e117748 goes. Still awaiting something from upstream there 😕.

**Comment by nmav** [comment]
I am not nettle upstream but my suggestion would be to use the latest versions released. The new versions of gnutls already require no earlier than 0.23.1.

**Comment by dwmw2** [comment]
Note, we also want p11-kit to build with `p11-kit-proxy.so`. See (misplaced) discussion with @mouse07410 in https://github.com/Yubico/yubico-piv-tool/issues/94

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  You're very welcome!  (Sorry for the response, delay, though; I've been away from my setup for a couple of days.)

**Pull request closed without merging**
