### PR TITLE
terraform 1.4.4

### PR DESCRIPTION
**Pull request by doeber**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by benlangfeld** [comment]
This installs 1.4.3-dev:

```
❯ brew upgrade terraform
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: terraform 1.4.4 already installed
❯ terraform -v
Terraform v1.4.3-dev
```

**Comment by ijunaidf** [comment]
Same here

```bash
$ terraform version 
Terraform v1.4.3-dev
on darwin_arm64
```

**Comment by SMillerDev** [comment]
It seems that is correct: https://github.com/hashicorp/terraform/pull/32953

**Comment by benlangfeld** [comment]
> It seems that is correct: [hashicorp/terraform#32953](https://github.com/hashicorp/terraform/pull/32953)

No. Installing 1.4.4 should get you 1.4.4.

**Comment by benlangfeld** [comment]
> And it does. Because that's the version that was compiled. What that version reports when you run `terraform --version` is not up to brew

The 1.4.4 release on the Terraform website and the TF cask are both really 1.4.4. This can be fixed.

**Comment by p-linnane** [comment]
If you download the 1.4.4 tarball from GitHub and build it, the version it returns is v1.4.3-dev. This is an issue with upstreams tarball, and nothing to do with `brew`. Please report the issue to them.

**Pull request merged**
