### PR TITLE
sorbet 0.4.4405 (new formula)

### PR DESCRIPTION
**Pull request by victorjacobs**
Adds formula for the [Sorbet Ruby type checker](https://github.com/sorbet/sorbet/).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Formula that only build for 1 macOS version aren't a good fit for homebrew-core. It excludes the majority of the supported platforms.

**Comment by victorjacobs** [comment]
@SMillerDev Completely agree. The reason I added it was because [the build was failing on the older MacOS versions](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/44827/version=high_sierra/consoleFull) with:

```
main/lsp/request_dispatch.cc:58:57: error: call to unavailable function 'get': introduced in macOS 10.14
```

Since I am not the maintainer of the project, I am not sure how/if this can be solved. I'm also running into problems getting it to work in Mojave anyways. So if you think it won't get merged anyways, I won't look into it more.

**Comment by SMillerDev** [comment]
If you can make an issue upstream we can decide based on their answers about support for earlier macOS versions.

**Comment by mistydemeo** [comment]
I've been having some trouble building locally; curious if this lines up with any failures you've seen. I'm running 10.14 with the CLT. https://gist.github.com/8550fe81f112e1fefdc3f8c8f7ff8d61

**Comment by victorjacobs** [comment]
@mistydemeo Quickly scanning through your gist I see:

```
include/jemalloc/internal/jemalloc_internal_decls.h:4:10: fatal error: 'math.h' file not found
#include <math.h>
```

Which is an issue I ran into. It has to do with the fact that Apple no longer installs headers in `/usr/include` by default. Initially I tried getting jemalloc to use the headers at their new location but gave that up after some time because my knowledge of bazel/make is pretty limited.

Luckily the headers are still shipped with macOS, you can install them by following [this article](https://silvae86.github.io/sysadmin/mac/osx/mojave/beta/libxml2/2018/07/05/fixing-missing-headers-for-homebrew-in-mac-osx-mojave/). Which works for now, but it is only a matter of time before Apple also removes this installer since shipping headers in this location is deprecated.

**Comment by fxcoudert** [comment]
> Luckily the headers are still shipped with macOS, you can install them by following this article

We do not recommend this *at all*. The headers are shipped with developer tools, but they are installed in a different location, is all.

Closing this for now, we'll be happy to consider a new PR once you have worked around this build issue.

**Pull request closed without merging**
