### PR TITLE
katago 1.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
build issue on 10.13:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
:9using ::signbit;:
       ~~^
error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
 error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
```

**Comment by dwt** [comment]
I'd like to help debug this, but I don't have access to 10.13 anymore. If you have any ideas how I can help repro this I'd be glad to help.

My suspicion is that there are some special cmake path magic things that should hep - but I'm not a C++ guru.

**Comment by chenrui333** [comment]
If you see the `10.13` label, there are some similar failures happening.

**Comment by dwt** [comment]
Still activity here, just waiting for a resolution of the spurious 10.13 failures.

**Comment by dwt** [comment]
No time from me to look into this yet - but I'm definitely interested. Seems the other compile problems got solved, a similar solution should be applicable here too.

**Comment by chenrui333** [comment]
Going to see if it still happens with the latest release.

**Pull request closed without merging**
