### PR TITLE
icu4c 62.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
#29269 should fix the build failure of `hfstospell`.

**Comment by lembacon** [comment]
They've updated the tarball, the checksum is changed from `5945ca2cf649aa6d80ef8b585ed1ad0b7d3a6ee26041c995a324a9fe710f6950` to `3dd9868d666350dda66a6e305eecde9d479fb70b30d5b55d78a1deffb97d5aa3`.

**Comment by ilovezfs** [comment]
@srl295 any idea what happened with the checksum? https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/26254/

**Comment by srl295** [comment]
@yumaoka ^ do you know why the checksum changed?

**Comment by roubert** [comment]
`5945ca2cf649aa6d80ef8b585ed1ad0b7d3a6ee26041c995a324a9fe710f6950` was a tarball that was not signed nor listed in a checksum file. I deleted it this morning.

`3dd9868d666350dda66a6e305eecde9d479fb70b30d5b55d78a1deffb97d5aa3` is the tarball that is signed and listed in the checksum file. I added it this morning.

The source code in the two tarballs is however identical.

**Comment by ilovezfs** [comment]
Thanks for the PR, @lembacon! Shipped.

@srl295 @roubert thank you very much for the explanation :)

**Pull request closed without merging**
