### PR TITLE
libbluray 1.3.4

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by iamralch** [comment]
@miccal @p-linnane 

The following error occurs on my end:

**Comment by aerogus** [comment]
same bug as @iamralch 

```
% brew install mpv
Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
==> Downloading https://ghcr.io/v2/homebrew/core/libbluray/manifests/1.3.4
curl: (22) The requested URL returned error: 404

Error: mpv: Failed to download resource "libbluray_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/libbluray/manifests/1.3.4
```

**Comment by kapitainsky** [comment]
> Looks like this PR accidentally set `CI-no-bottles` which caused CI to ignore new bottle upload. Did a manual upload and will hopefully be fixed with #116960

==> Upgrading 1 outdated package:
libbluray 1.3.3 -> 1.3.4
==> Downloading https://ghcr.io/v2/homebrew/core/libbluray/manifests/1.3.4
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/3ca2a7bc181ca21ac727ad165abb77758d74c9c260dd155b33f741b1eee5801a--libbluray-1.3.4.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libbluray/manifests/1.3.4
######################################################################## 100.0%
Error: Couldn't find manifest matching bottle checksum.

**Comment by cho-m** [comment]
The PR #116960 needs to be merged before you can upgrade. The bottle block is still for 1.3.3.

**Comment by aerogus** [comment]
Bug is gone, thank you @cho-m !

**Comment by iamralch** [comment]
Thank you for the quick resolution!

**Pull request closed without merging**
