### PR TITLE
antiword: deprecate, update url

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Last release was in 2005, homepage is gone now.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Should be deprecated too

**Comment by p-linnane** [comment]
@SMillerDev Looks like `textract` depends on this. That appears to have had recent activity, so probably shouldn't deprecate. Would it be better to go back to the "skip livecheck" route here?

**Comment by iMichka** [comment]
Maybe open an issue at `textract` and ask what they plan to do with `antiword`, or if it can made optional/disabled first?

**Comment by p-linnane** [comment]
`textract` upstream issue ref: https://github.com/deanmalmgren/textract/issues/454

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
