### PR TITLE
hiredis 1.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/bin/clang -I/usr/local/Cellar/hiredis/1.0.0/include/hiredis -L/usr/local/Cellar/hiredis/1.0.0/lib -lhiredis /usr/local/Cellar/hiredis/1.0.0/share/hiredis/examples/example.c -o /private/tmp/hiredis-test-20200805-47091-13lreo0/test
/usr/local/Cellar/hiredis/1.0.0/share/hiredis/examples/example.c:5:10: fatal error: 'win32.h' file not found
#include <win32.h>
         ^~~~~~~~~
1 error generated.
Error: hiredis: failed
```

**Comment by chenrui333** [comment]
build failure for `libjson-rpc-cpp`

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
`libjson-rpc-cpp` already failed to build from the source with the same error log:

```
[ 88%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/redisserver.cpp.o
cd /tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/src/jsonrpccpp && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Djsonrpcserver_EXPORTS -I/usr/local/include/jsoncpp -I/tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/gen -I/tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/gen/jsonrpccpp/common -I/tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/.. -std=c++11 -fprofile-arcs -ftest-coverage -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC -o CMakeFiles/jsonrpcserver.dir/server/connectors/redisserver.cpp.o -c /tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/redisserver.cpp
/tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/httpserver.cpp:78:22: error: no matching function for call to 'MHD_start_daemon'
      this->daemon = MHD_start_daemon(
                     ^~~~~~~~~~~~~~~~
/usr/local/include/microhttpd.h:2425:1: note: candidate function not viable: no known conversion from 'int (void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)' (aka 'int (void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') to 'MHD_AccessHandlerCallback' (aka 'MHD_Result (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') for 5th argument
MHD_start_daemon (unsigned int flags,
^
/tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/httpserver.cpp:87:24: error: no matching function for call to 'MHD_start_daemon'
        this->daemon = MHD_start_daemon(
                       ^~~~~~~~~~~~~~~~
/usr/local/include/microhttpd.h:2425:1: note: candidate function not viable: no known conversion from 'int (void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)' (aka 'int (void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') to 'MHD_AccessHandlerCallback' (aka 'MHD_Result (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') for 5th argument
MHD_start_daemon (unsigned int flags,
^
/tmp/libjson-rpc-cpp-20200830-65413-1opzd8o/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/httpserver.cpp:97:22: error: no matching function for call to 'MHD_start_daemon'
      this->daemon = MHD_start_daemon(
                     ^~~~~~~~~~~~~~~~
/usr/local/include/microhttpd.h:2425:1: note: candidate function not viable: no known conversion from 'int (void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)' (aka 'int (void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') to 'MHD_AccessHandlerCallback' (aka 'MHD_Result (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') for 5th argument
MHD_start_daemon (unsigned int flags,
^
3 errors generated.
make[2]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/httpserver.cpp.o] Error 1
```

**Comment by chenrui333** [comment]
create a fresh PR so that it can have better visibility.

**Pull request closed without merging**
