### PR TITLE
go 1.17.1

### PR DESCRIPTION
**Pull request by jmhodges**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by cho-m** [comment]
Failures across CI nodes, ignoring not-yet-bottled ARM failures:
- [ ] `brew fetch --build-from-source --retry fluxctl` - SHA mismatch
- [ ] `brew install --build-from-source newrelic-infra-agent`
- [ ] `brew test --retry --verbose annie`
- [ ] `brew test --retry --verbose croc`
- [ ] `brew test --retry --verbose fn`
- [ ] `brew test --retry --verbose vitess`
- [x] `brew test --retry --verbose jabba` - #85004

**Comment by chenrui333** [comment]
>  brew test --retry --verbose fn (Mojave only)

works on my Mojave machine.

**Comment by chenrui333** [comment]
>  brew test --retry --verbose annie

this works fine for me as well.

**Comment by chenrui333** [comment]
>  brew install --build-from-source newrelic-infra-agent
This is known issue.

**Comment by andig** [comment]
What's missing? go 1.17.1 seems important as it fixes some problems with handling `go.mod` files.

**Comment by chenrui333** [comment]
you are right, I think we can do a rebase and then the merge, and then fix all the broken formulae afterwards.

**Comment by chenrui333** [comment]
somehow 11-arm runner job got cancelled. Have to restart the workflow again.

**Review by cho-m — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @cho-m!

**Pull request closed without merging**
