### PR TITLE
ponyc 0.22.0

### PR DESCRIPTION
**Pull request by SeanTAllen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SeanTAllen** [comment]
The build error appears to be environmental. What can be done to address...

`mkdir: /usr/local/include/pony/detail: Operation not permitted`

we don't have this issue when building locally.

**Comment by ilovezfs** [comment]
That's not the configured prefix. It should be writing to

/usr/local/Cellar/ponyc/0.22.0/include/pony/detail

**Comment by SeanTAllen** [comment]
That's odd @ilovezfs. We didn't change anything related to that and it worked previously.

**Comment by SeanTAllen** [comment]
@ilovezfs that uses `destdir` which is set by `destdir=#{prefix}"`.

from our Makefile:

```
@mkdir -p $(DESTDIR)$(ponydir)/include/pony/detail
```

has something changed where #{prefix} is no longer valid?

**Comment by SeanTAllen** [comment]
@ilovezfs is this failing now because pony-stable hasn't been updated yet and the current pony-stable release won't build with this ponyc release (which is something i was going to address after this release is out)?

**Comment by ilovezfs** [comment]
Yes, but also because the ponyc `test do` block fails.

We can either temporarily break pony-stable or add the pony-stable change to this PR as a second commit. Usually our requirement is the latter but if the pony-stable change will follow immediately in a second PR, it's not a big deal either way.

**Comment by ilovezfs** [comment]
ponyc test failure https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/24660/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/test_ponyc/

**Comment by SeanTAllen** [comment]
@ilovezfs i dont understand the ponyc failure.

`Failed to execute: /usr/local/Cellar/ponyc/0.22.0/bin/ponyc`

why would it fail to execute? that means... the binary wasn't there? i'm not sure what that error message means. can you provide any insight?

**Comment by ilovezfs** [comment]
I'd try `prefix=#{prefix}` instead of setting DESTDIR

**Comment by ilovezfs** [comment]
improvement: pony-stable passed this time
but still ponyc test failure https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/24667/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/test_ponyc/

**Comment by SeanTAllen** [comment]
That error is really weird because, it starts to succeed and then fails on the 2nd package it tries running over. This is the "normal" output (different paths from a local build)

```
 ---> bin/ponyc -rexpr packages/stdlib
Building builtin -> /usr/local/lib/pony/0.21.3-69e9a53c/packages/builtin
Building packages/stdlib -> /usr/local/lib/pony/0.21.3-69e9a53c/packages/stdlib
Building ponytest -> /usr/local/lib/pony/0.21.3-69e9a53c/packages/ponytest
```

You can see in the error output that it found bultin and started working after having found packages/stdlib, it then complained about not finding it.

**Comment by SeanTAllen** [comment]
@ilovezfs i have no idea how pony-stable would pass.  it would build with the new version of ponyc without an update.

**Comment by ilovezfs** [comment]
It's just the preexisting pony-stable bottle successfully running the pony-stable test block, not a rebuild of pony-stable.

**Comment by ilovezfs** [comment]
It looks like
```
    system "make", "config=release", "ponydir=#{prefix}", "prefix=", "install", "verbose=1"
```
also works

**Comment by SeanTAllen** [comment]
@ilovezfs that's better updating

**Comment by SeanTAllen** [comment]
@ilovezfs all good. thanks for you help! sorry about that. Someone changed the makefile out from underneath me and never mentioned it.

**Comment by ilovezfs** [comment]
No worries. Shipped! Thanks for the PR

**Comment by ilovezfs** [comment]
@SeanTAllen it looks like 0.22.1 is out now?

**Pull request closed without merging**
