### PR TITLE
glib 2.66.1

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]
Thanks @tschoonj  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by tschoonj** [comment]
Hmm, this looks like it's due to one of these commits also being present in #62023 

Do I need to rebase against master?

**Comment by SMillerDev** [comment]
Yeah, please do

**Comment by tschoonj** [comment]
Done!

Apologies, I thought this case was supported.

**Comment by tschoonj** [comment]
```
==> brew livecheck glib --full-name --debug
38
==> FAILED
39
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glib.rb
40
Error: glib: 503 Service Unavailable
41

42
Formula:          glib
43
Livecheckable?:   Yes
44

45
URL:              https://download.gnome.org/sources/glib/2.66/glib-2.66.1.tar.xz
46
Strategy:         Gnome
```

I guess this was a temporary glitch that shouldn't stop us from merging it in?

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
