### PR TITLE
openvpn 2.5.0

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by robertleeblairjr** [comment]
@chenrui333 I'm not sure what's failing for the audit from the previous 2.4.8. I'll look to see what's possibly changed by the maintainers. Feel free to make any suggestions or edits to this.

**Comment by chenrui333** [comment]
@robertleeblairjr  sorry for the late reply, i will take another look today on this PR.

**Comment by ChrisBaker97** [comment]
This seems to do the trick:

```diff
@@ -24,6 +24,9 @@ class Openvpn < Formula
   depends_on "pkcs11-helper"
 
   def install
+    ENV["PKG_CONFIG"] = "/usr/local/bin/pkg-config"
+    ENV["SED"] = "/usr/bin/sed"
+
     system "./configure", "--disable-debug",
                           "--disable-dependency-tracking",
                           "--disable-silent-rules",
```
That uses the system `sed` though. I've got `sed` in `shims` but I can't find any other `sed` inside Homebrew's path, so I'm not sure what else it should point to.

Also, this is the first time I've tried to address this type of error, so let me know if I'm totally barking up the wrong tree here.

**Comment by ChrisBaker97** [comment]
So I think maybe my suggestion above is incorrect, because it would cause `./configure` to run with versions other than what's in `shims`. 

This also seems to pass the post-install audit, by simply modifying the offending file after `./configure` runs:
```diff
@@ -30,6 +30,12 @@ class Openvpn < Formula
                           "--with-crypto-library=openssl",
                           "--enable-pkcs11",
                           "--prefix=#{prefix}"
+    inreplace "sample/sample-plugins/Makefile",
+              HOMEBREW_LIBRARY/"Homebrew/shims/mac/super/pkg-config",
+              Formula["pkg-config"].opt_bin/"pkg-config"
+    inreplace "sample/sample-plugins/Makefile",
+              HOMEBREW_LIBRARY/"Homebrew/shims/mac/super/sed",
+              "/usr/bin/sed"
     system "make", "install"
 
     inreplace "sample/sample-config-files/openvpn-startup.sh",
```

**Pull request closed without merging**
