### PR TITLE
gnome: various

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Willing to entertain bets on how much stuff breaks in this PR.

Had to re-do a lot of it from scratch because the original PR no longer applies cleanly & patching in dribs & drabs proved to be a nightmare, so I gave up and did it myself. _Welp x 500_.

Continuing on the work from https://github.com/Homebrew/legacy-homebrew/pull/50257 and https://github.com/Homebrew/homebrew-core/pull/267.

Closes #2198.
Closes #2293.
Closes #492.

### CODE REVIEW

**Comment by tdsmith** [comment]
> 	gsettings-desktop-schemas: use our Python on <10.10

Have we filed a bug against gobject-introspection for this?

**Comment by DomT4** [comment]
It's not really a new problem. It's the old problem spreading; that dependency is essentially inherited from `gobject-introspection`.

I've no idea if it was reported upstream at this point, but IIRC you okayed the hack for `gobject-introspection` before with some reasonable sounding explanation. I could have dreamt that though, it's entirely possible 🙈.

**Comment by tdsmith** [comment]
The contagion worries me but maybe it's not blocking for this

**Comment by DomT4** [comment]
Yeah, Mavericks is a fair jump from our usual enforcement on Snow Leopard and below only, to say the least. I guess either Apple give the Python on 10.9 an update, which seems unlikely, or GNOME stop using the problematic call in increasing doses.

@tschoonj If you're around, do you recall reporting the original issue upstream at all?

**Comment by DomT4** [comment]
I'm pretty sure almost all of the failures so far are gunk. I'm unable to replicate them locally, doing the same thing the CI would be doing _(New stuff installed from source, non-updated formula poured from bottles for testing)_.

We've seen this stuff before and I'm not sure anyone's ever nailed it down completely. It's like the CI install the changes from source for testing, removes the formula, and then doesn't bother reinstalling it to test other elements against.

So far locally:

* `homebank` - Test passes fine, no `linkage --test` complaints.
* `file-roller` - Test passes fine, no `linkage --test` complaints.
* `gupnp-tools` - Test passes fine, no `linkage --test` complaints.
* `libchamplain` - Test passes fine, no `linkage --test` complaints.
* `cogl` - Test passes fine, no `linkage --test` complaints.

CI log output is interesting:

```
==> brew uninstall --force pango
==> brew install ./gdk-pixbuf-2.34.0.el_capitan.bottle.tar.gz
==> brew test gdk-pixbuf --verbose
==> brew linkage --test file-roller
==> FAILED
Missing libraries:
  /usr/local/opt/pango/lib/libpango-1.0.0.dylib
  /usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib
==> brew test --verbose file-roller
==> FAILED
Testing file-roller
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160623-34988-mdwh53.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/file-roller.rb --verbose
==> /usr/local/Cellar/file-roller/3.20.2/bin/file-roller --version 2>&1
sh: line 1: 34998 Trace/BPT trap: 5       /usr/local/Cellar/file-roller/3.20.2/bin/file-roller --version 2>&1
Error: file-roller: failed
<0> expected but was
<133>.
==> brew linkage --test gimp
==> FAILED
Missing libraries:
  /usr/local/opt/pango/lib/libpango-1.0.0.dylib
  /usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib
  /usr/local/opt/pango/lib/libpangoft2-1.0.0.dylib
```

So it looks like `pango` isn't there at that point, since it was forcibly removed, and even though `file-roller` declares a `pango` dependency CI isn't bothering to put it back before running the test. Later on when `gtk+3` is installed it pulls in `pango` and `file-roller` passes fine:

```
==> brew uses gtk+3
==> brew fetch --retry atk autoconf automake gdk-pixbuf gettext git glib gobject-introspection gsettings-desktop-schemas libffi pango pcre
==> brew fetch --retry gtk+3 --build-bottle --force
==> brew uninstall --force gtk+3
==> brew install --only-dependencies --build-bottle --verbose gtk+3
==> brew install --build-bottle --verbose gtk+3
==> brew audit gtk+3
==> brew bottle --verbose --json gtk+3
==> brew bottle --merge --write --no-commit ./gtk+3-3.20.6.el_capitan.bottle.json
==> brew uninstall --force gtk+3
==> brew uninstall --force autoconf automake git
==> brew install ./gtk+3-3.20.6.el_capitan.bottle.tar.gz
==> brew test gtk+3 --verbose
==> brew fetch --retry awf
==> brew install awf
==> brew linkage --test awf
==> brew test --verbose awf
==> brew linkage --test file-roller
==> brew test --verbose file-roller
```

I hate CI.

**Comment by DomT4** [comment]
If we get this down to just `linkage --test` and `brew test` failures that _don't_ reproduce when their known dependency is installed later in the same CI run I'm going to plow ahead with this. Fixed a couple more things though, so another 2+ hour trip through CI to see.

**Comment by tdsmith** [comment]
looks like our last conversation about gobject-introspection was also pretty yolo https://github.com/Homebrew/legacy-homebrew/pull/44235#discussion_r40506985

otoh given the size of the mavericks userbase and the limited sympathy i have for them this seems fine

**Comment by DomT4** [comment]
Everything installed fine here, and I'm 100% sure the test failures are a CI bug rather than formula related given they don't reproduce outside the CI mechanism, so I'm going to bite the bullet and merge this in. I'll deal with related breakage as it comes, if necessary. Let's see how it goes rather than endlessly sitting on this despite repeated user requests.

Thanks for the Python-related feedback as ever @tdsmith ❤️.

**Comment by UniqMartin** [comment]
@DomT4 Thanks for dealing with this huge update and actually making it happen! :heart:

**Comment by DomT4** [comment]
Thanks @UniqMartin. Just hoping it goes smoothy. These huge updates are always varying degrees of awful.

**Pull request closed without merging**
