### PR TITLE
poppler 20.10.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/bin/clang -I/usr/local/Cellar/simple-tiles/0.6.1_8/include -L/usr/local/Cellar/simple-tiles/0.6.1_8/lib -lsimple-tiles -I/usr/local/opt/cairo/include/cairo -I/usr/local/opt/gdal/include -I/usr/local/opt/glib/include/glib-2.0 -I/usr/local/opt/glib/lib/glib-2.0/include -I/usr/local/opt/harfbuzz/include/harfbuzz -I/usr/local/opt/pango/include/pango-1.0 test.c -o test
==> /private/tmp/simple-tiles-test-20201002-30300-1010buo/test
dyld: Library not loaded: /usr/local/opt/poppler/lib/libpoppler.102.dylib
  Referenced from: /usr/local/opt/gdal/lib/libgdal.27.dylib
  Reason: image not found
Error: simple-tiles: failed
An exception occurred within a child process:
  BuildError: Failed executing: /private/tmp/simple-tiles-test-20201002-30300-1010buo/test
```

**Comment by miccal** [comment]
`gdal` is causing all the problems I think.

**Comment by miccal** [comment]
Just one failure for all now:
```
Error: 1 failed steps!
brew install --verbose --build-bottle gdal
```

**Comment by fxcoudert** [comment]
gdal being updated in https://github.com/Homebrew/homebrew-core/pull/61096

**Comment by miccal** [comment]
Perhaps there is an issue with this updated version of `poppler` and the current version of `gdal`:
```
Error: 1 failed steps!
brew install --verbose --build-bottle gdal
```

**Comment by fxcoudert** [comment]
Bug is fixed by https://github.com/OSGeo/gdal/commit/9ef8e16e27c5fc4c491debe50bf2b7f3e94ed334
But… it shouldn't even trigger without jasper (which I removed as a der in the latest update). Maybe opportunistic linkage?

**Comment by miccal** [comment]
> Bug is fixed by [OSGeo/gdal@9ef8e16](https://github.com/OSGeo/gdal/commit/9ef8e16e27c5fc4c491debe50bf2b7f3e94ed334)
> But… it shouldn't even trigger without jasper (which I removed as a der in the latest update). Maybe opportunistic linkage?

Thanks for your insight @fxcoudert, but would you mind explaining what you mean by "opportunistic linkage"?

Do you think I should add https://github.com/OSGeo/gdal/commit/9ef8e16e27c5fc4c491debe50bf2b7f3e94ed334 to `gdal` as a patch?

**Comment by miccal** [comment]
Try again after the merging of https://github.com/Homebrew/homebrew-core/pull/62190.

**Comment by miccal** [comment]
Thanks to the efforts of @fxcoudert with `gdal`, this is now ready to merge.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
