### PR TITLE
emscripten 3.1.51

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

Continuing https://github.com/Homebrew/homebrew-core/pull/157312 & https://github.com/Homebrew/homebrew-core/pull/158038. Also updated the instructions for updating resources, as I found it confusing that the first resource didn't explain how to update them.

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Comment by p-linnane** [comment]
Looks like this has linkage with `zlib`. I'll open a syntax-only PR as a follow up to add `uses_from_macos "zlib"` so we don't have to run several hours of CI again.

**Comment by p-linnane** [comment]
`tree-sitter` needs a rev bump. I'll open a followup PR to avoid wasted CI time here.

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/158869

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/158870

**Pull request merged**
