### PR TITLE
abyss 2.3.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
>   abyss:
    * Stable resource "testdata": The source URL https://www.bcgsc.ca/sites/default/files/bioinformatics/software/abyss/releases/1.3.4/test-data.tar.gz is not reachable

**Comment by chenrui333** [comment]
Good for the merge (just page audit errors)

**Review by branchv — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

**Comment by carlocab** [comment]
@iMichka please don't pass `--no-autosquash` when there are commits to be squashed.

**Comment by iMichka** [comment]
My bad I did not notice the 2 commits, I should have been more careful.

**Pull request closed without merging**
