### PR TITLE
pdm: add livecheck

### PR DESCRIPTION
**Pull request by LouisStAmour**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by samford — COMMENTED** [review]
We only add a `livecheck` block to a formula when the default check isn't sufficient or livecheck's strategies don't apply to any of the formula URLs.

Without a `livecheck` block, the `Pypi` strategy is applied to `pdm`'s `stable` URL, which checks https://pypi.org/project/pdm/#files using a `%r{href=.*?/packages.*?/pdm[._-]v?(\d+(?:\.\d+)*(?:[._-]post\d+)?)\.t}i` regex and correctly gives `1.4.1` as the latest version. This is working as expected to me.

The regex in this PR would match versions with a trailing letter and digit(s), which doesn't seem appropriate for this formula. This software doesn't appear to use a version scheme with a trailing letter that increments (e.g., `1.2a`, `1.2b`, 1.2c`, etc.) and this would only serve to match unstable versions like `1.0.0b2` (marked as "pre-release" on PyPI), which we don't want.

Could you explain why you believe this regex is needed over the default one from the `Pypi` strategy?

**Comment by LouisStAmour** [comment]
Sorry for the PR noise. :) 

This can be closed. The only reason I added it was because 1.4.1 had recently been released (9 hours prior) but had not been updated, and previous to this, it had been my understanding that an RSS feed or URL would be required from a few years back when I contributed appcast URLs. 

Livecheck is new to me and the documentation page didn’t indicate the defaults as clearly as it could have, because my eyes jumped right over the Behaviour section to how it was specified for Black and other Python tools. https://docs.brew.sh/Brew-Livecheck 

Thanks for letting me know!

**Comment by samford** [comment]
> The only reason I added it was because 1.4.1 had recently been released (9 hours prior) but had not been updated, and previous to this, it had been my understanding that an RSS feed or URL would be required from a few years back when I contributed appcast URLs.

@LouisStAmour Formulae are manually updated by maintainers and contributors in homebrew/core. On the other hand, homebrew/cask uses livecheck's data (replacing the `appcast` functionality) to automatically create version bump PRs, as it's easier to do when you're only dealing with binaries.

The long-term goal is to have some level of automated version bump PRs in homebrew/core based on livecheck's data (even if it's limited to specific formulae at first) but it's naturally more complicated since we're building from source. Without going into detail, there are some challenges to overcome before this is something that we have in homebrew/core.

---

> Livecheck is new to me and the documentation page didn’t indicate the defaults as clearly as it could have, because my eyes jumped right over the Behaviour section to how it was specified for Black and other Python tools. https://docs.brew.sh/Brew-Livecheck

`brew livecheck`'s default behavior varies from one formula to the next, so it's not something that can be covered in the documentation. The "Behavior" section provides the big picture and it's necessary to use `brew livecheck --debug` to understand what livecheck does for a particular formula/cask (as mentioned in the first step of the "Creating a check" section).

If you're interested in what strategies are available and how they work, you'll want to check the relevant part of [rubydoc.brew.sh](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.html) (as linked at the top of the doc).

---

If you ever find yourself looking for a new version of a formula and a PR hasn't been created for it yet, check out [`brew bump-formula-pr`](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula). It's a painless way to create a PR for a new version, so you can help others while helping yourself at the same time. That said, it's usually a good idea to search closed PRs beforehand, as sometimes formulae are blocked on a particular issue and can't be updated until something changes.

Hopefully this helps to clear things up a bit.

**Comment by LouisStAmour** [comment]
Thanks, I did end up using bump-formula-pr and it was quite painless! :)

**Pull request closed without merging**
