### PR TITLE
gauge 0.6.2

### PR DESCRIPTION
**Pull request by mahendrakariya**

### CODE REVIEW

**Comment by mahendrakariya** [comment]
Hey brew maintainers,

The build is failing on el capitan and yosemite because it is not able to find the standard golang libraries. Could you please help us here?

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
I'm not sure what's causing this but it seems to be reproducible.

**Comment by mahendrakariya** [comment]
@MikeMcQuaid What do you suggest we should do?

**Comment by MikeMcQuaid** [comment]
@ilovezfs is looking; it's a probably with `godep`.

**Comment by mahendrakariya** [comment]
Cool! Thanks! I will wait for a response.

**Comment by ilovezfs** [comment]
@mahendrakariya please try adding
```
ENV["GOROOT"] = Formula["go"].opt_libexec
```
underneath the `ENV["GOPATH"] = buildpath` on line 27.

**Comment by mahendrakariya** [comment]
@ilovezfs After the changes suggested by you, the build is passing! :)

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `gauge 0.6.2`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
