### PR TITLE
chapel 1.13.0

### PR DESCRIPTION
**Pull request by awallace-cray**
- [ yes ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ yes ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ yes ] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ yes ] Have you built your formula locally prior to submission with `brew install <formula>`?

This updates the homebrew formula "chapel" to the new Chapel release version 1.13.0.

### CODE REVIEW

**Comment by apjanke** [comment]
Build is failing.

```

==> make
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make
***** adt/ *****
making gen/darwin.clang.wide-struct.llvm-none subdirectory to store platform-specific files
clang++ -c -MMD -MP -O3 -I. -I../include/darwin -I../include    -o gen/darwin.clang.wide-struct.llvm-none/bitVec.o bitVec.cpp
clang++ -c -MMD -MP -O3 -I. -I../include/darwin -I../include    -o gen/darwin.clang.wide-struct.llvm-none/map.o map.cpp
clang++ -c -MMD -MP -O3 -I. -I../include/darwin -I../include    -o gen/darwin.clang.wide-struct.llvm-none/vec.o vec.cpp
vec.cpp:52:10: fatal error: 'misc.h' file not found
#include "misc.h"
         ^
bitVec.cpp:20:10: fatal error: 'bitVec.h' file not found
#include "bitVec.h"
         ^
1 error generated.
make[3]: *** [gen/darwin.clang.wide-struct.llvm-none/vec.o] Error 1
make[3]: *** Waiting for unfinished jobs....
1 error generated.
make[3]: *** [gen/darwin.clang.wide-struct.llvm-none/bitVec.o] Error 1
make[2]: *** [adt.makedir] Error 2
make[1]: *** [compiler] Error 2
make: *** [comprt] Error 2
==> Formula
Path: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/chapel.rb
==> Configuration
...
```

**Comment by awallace-cray** [comment]
> build failing
I noticed that- it fails exactly the same in all three platforms. I don't understand, because:
* misc.h and bitVec.h are right there in our tarball, you can see them in the tar -xv right there in the Jenkins console log
* I have successfully run this on my Mac (el-capitan), including copy-pasting the commands from Jenkins console log: 
```
  503  PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  504  HOMEBREW_DEVELOPER=1
  505  HOMEBREW_SANDBOX=1
  506  export PATH HOMEBREW_DEVELOPER HOMEBREW_SANDBOX
  507  cd /usr/local
  508  git reset --hard origin/master
  509  git clean -ndx
  510  git clean -n
  511  git clean -nd
  512  brew update
  513  echo $PATH
  514  pwd
  515  brew pull --clean https://github.com/Homebrew/homebrew-core/pull/137
  516  brew doctor
  517  brew --env
  518  brew config
  519  brew tests
  520  brew tests --no-compat
  521  brew readall --aliases --syntax
  522  brew uses chapel
  523  brew uninstall chapel
  524  brew fetch --retry chapel --build-bottle --force
  525  brew install --verbose --build-bottle chapel
  526  history 50
```
* I can provide outputs from any/all of the above, re-run any of it a different way, etc. Open for suggestions! 
* Another thing we could try, is to take our current chapel formula (chapel 1.12.0) and run that through this build process somehow. That chapel 1.12.0 formula is definitely known to work.

**Comment by ben-albrecht** [comment]
I was able to reproduce the error locally using `brew test-bot chapel`. However, I am still confused as to how `clang++ -c -MMD -MP -O3 -I. -I../include/darwin -I../include    -o gen/darwin.clang.wide-struct.llvm-none/vec.o vec.cpp` is not finding `../include/misc.h`, which it is shown to have been untarred in the output above. Any ideas @apjanke ?

**Comment by ben-albrecht** [comment]
FWIW, the current Chapel 1.12.0 formula fails for the same reason with `brew test-bot chapel`.

**Comment by awallace-cray** [comment]
I had the same shell window open from above (ie, where brew install chapel worked fine).  I un-installed chapel and ran brew test-bot chapel, and that failed for the same reason (ie, missing the two header files)

**Comment by apjanke** [comment]
Hmmmm. I bet it's over-aggressive flag filtering from brew's env sanitization logic. Though I don't know why it would only show up in test-bot.

If you look at the logs from `test-bot --local --keep-logs`, the `*.cc` files will tell you what filtering is going on. It might be killing those `-I../...` flags. (Because it's not expecting to be run from a subdirectory of the build dir.) If so that's probably a `brew` bug and not a problem with the formula.

I'm on mobile right now, but if this is the case, I'll repro and investigate when home in a couple hours. Or someone else can pick it up if they have time.

**Comment by ben-albrecht** [comment]
Hi @apjanke, I ran `test-bot --local --keep-logs` and received the following output for `*.cc` logs:

    > cat 01.make.cc

    clang++ called with: -c -MMD -MP -O3 -I. -I../include/darwin -I../include -o gen/darwin.clang.wide-struct.llvm-none/bitVec.o bitVec.cpp
    superenv removed:  -O3 -I. -I../include
    superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    superenv executed: clang++ -pipe -w -Os -march=core2 -c -MMD -MP -I../include/darwin -o gen/darwin.clang.wide-struct.llvm-none/bitVec.o bitVec.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    
    clang++ called with: -c -MMD -MP -O3 -I. -I../include/darwin -I../include -o gen/darwin.clang.wide-struct.llvm-none/map.o map.cpp
    superenv removed:  -O3 -I. -I../include
    superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    superenv executed: clang++ -pipe -w -Os -march=core2 -c -MMD -MP -I../include/darwin -o gen/darwin.clang.wide-struct.llvm-none/map.o map.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    
    clang++ called with: -c -MMD -MP -O3 -I. -I../include/darwin -I../include -o gen/darwin.clang.wide-struct.llvm-none/vec.o vec.cpp
    superenv removed:  -O3 -I. -I../include
    superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    superenv executed: clang++ -pipe -w -Os -march=core2 -c -MMD -MP -I../include/darwin -o gen/darwin.clang.wide-struct.llvm-none/vec.o vec.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers


I believe this confirms your suspicion.

**Comment by apjanke** [comment]
Sure does.

I'll follow up on this when I have time (prob tonight) or some other maintainer can pick it up.

**Comment by awallace-cray** [comment]
Is there anything we can do? -thanks.

**Comment by mikemcquaid** [comment]
@awallace-cray You could investigate our flag filtering and try to fix this bug (or just wait for a maintainer to do it). Thanks!

**Comment by apjanke** [comment]
https://github.com/Homebrew/brew/pull/63 should fix this. Those `-I..` relative paths were evaluated relative to the formula's keg prefix, not the build directory, so they were being filtered out as an undeclared dependency. Relative paths under the build directory are already accepted. That PR alters things to allow paths under the current formula itself. Tests okay locally for me.

**Comment by awallace-cray** [comment]
Great! Thanks! Should I wait for Homebrew/brew#63 to be merged, then rebase this (just to get it to kick off a new build, I guess)

**Comment by apjanke** [comment]
No need; I kicked off reruns of the affected PRs after merging 63. And it worked here.

Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
