### PR TITLE
gosu 1.15.3

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
Checking on the fix now.

**Comment by zbeekman** [comment]
Java/Maven issue: likely caused by moving to adoptopenjdk in Homebrew

**Comment by chenrui333** [comment]
@zbeekman do you have any commit or PR references for what you mentioned?

**Comment by zbeekman** [comment]
https://github.com/Homebrew/brew/pull/6040

I'm no java expert, but basically we switched to using OpenJDK as default java. My comment may be a red-herring though. I'd recommend trying a local build to debug.

**Comment by chenrui333** [comment]
Closing this in favor of https://github.com/Homebrew/homebrew-core/pull/40278

**Pull request closed without merging**
