### PR TITLE
pulumi 0.17.26

### PR DESCRIPTION
**Pull request by lukehoban**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lukehoban** [comment]
The build appears to have been stuck for 7 hours.  Does it need to be restarted?

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/45738/version=high_sierra/

**Comment by lukehoban** [comment]
Anything needed before this is merged?

**Comment by SMillerDev** [comment]
Just a bunch of patience

**Comment by Moisan** [comment]
Superseded by #42572 .

**Pull request closed without merging**
