### PR TITLE
mysql-client 5.7.26

### PR DESCRIPTION
**Pull request by selfagency**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
Undefined symbols for architecture x86_64:
  "_mysql_file_read", referenced from:
      _my_b_fill in libmysqlclient.a(mf_iocache2.c.o)
  "_mysql_file_seek", referenced from:
      _my_b_fill in libmysqlclient.a(mf_iocache2.c.o)
      _my_b_filelength in libmysqlclient.a(mf_iocache2.c.o)
```

**Comment by scpeters** [comment]
yeah, I think we saw those same mysterious linking errors in #40816

**Comment by fxcoudert** [comment]
Have they been reported upstream?

**Comment by selfagency** [comment]
I referred this issue to MySQL's maintainers and they're fairly insistent it's not on their end. One of them did a fresh build on a Mac from source ([see ticket](https://bugs.mysql.com/bug.php?id=95740)). So what's the difference here in the way Homebrew is building it that's causing it to fail?

**Comment by fxcoudert** [comment]
Given a bug reported in August 2017 is still not fixed: https://bugs.mysql.com/bug.php?id=87348 probably don't hold your breath on this one.

Homebrew's complete compilation line is: `cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql-client/5.7.26 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCOMPILATION_COMMENT=Homebrew -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DINSTALL_DOCDIR=share/doc/mysql-client -DINSTALL_INCLUDEDIR=include/mysql -DINSTALL_INFODIR=share/info -DINSTALL_MANDIR=share/man -DINSTALL_MYSQLSHAREDIR=share/mysql -DWITH_BOOST=boost -DWITH_EDITLINE=system -DWITH_SSL=yes -DWITH_UNIT_TESTS=OFF -DWITHOUT_SERVER=ON`

**Comment by selfagency** [comment]
I think they just put the file for 5.7.23 back up on the CDN...

**Comment by selfagency** [comment]
🙄
```
We do not support Homebrew builds, because we do not use it. We do not
know whether it is possible to build with Homebrew, because this is not
our official manner of building MySQL on macOS.

Not a bug.
```

**Comment by selfagency** [comment]
😤
```
Our build team will not consider Homebrew building for the foreseeable
future.
```
Time to move to Maria, I guess.

**Pull request closed without merging**
