### PR TITLE
rbenv 1.1.0

### PR DESCRIPTION
**Pull request by mislav**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thanks!

**Comment by bgentry** [comment]
Should I have expected this upgrade to make rbenv forget about all installed versions? Immediately after upgrade, I see this:

```
➜  ~  rbenv versions
* system (set by /usr/local/opt/rbenv/version)
```

I definitely had multiple ruby versions installed prior to the upgrade.

**Comment by MikeMcQuaid** [comment]
@bgentry All my `rbenv versions` are there after the upgrade but I'm using `/Users/mike/.rbenv`. @mislav, any thoughts?

**Comment by mislav** [comment]
@bgentry This upgrade shouldn't have caused any changes to where rbenv looks up installed versions, unless you also changed some other part of your configuration when upgrading. The most important configuration detail is RBENV_ROOT, which is where rbenv looks up the `versions/` directory. By default, RBENV_ROOT is `~/.rbenv`. Can you check how is this configured on your system, and also check where on disk where were all the Ruby versions installed?

**Comment by bgentry** [comment]
I didn't get any time to dig into this unfortunately. I can tell you that I'm using `oh-my-zsh` with the rbenv plugin, if that's relevant. I think that's why I'm installed to a path other than `~/.rbenv`.

After reinstalling my Ruby version and gems everything is working fine, though.

**Comment by MikeMcQuaid** [comment]
> I didn't get any time to dig into this unfortunately. I can tell you that I'm using oh-my-zsh with the rbenv plugin, if that's relevant. I think that's why I'm installed to a path other than ~/.rbenv.

@bgentry Please consider if you're willing to take the time to dig into the problem before asking others to do so on your behalf. It's disappointing for me to spend a bit of time on this and you not to reciprocate.

**Pull request closed without merging**
