### PR TITLE
zrepl 0.2.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
20:52:52 go: finding github.com/jinzhu/copier v0.0.0-20170922082739-db4671f3a9b8
20:52:52 go: finding google.golang.org/genproto v0.0.0-20181202183823-bd91e49a0898
20:52:52 Error: An exception occurred within a child process:
20:52:52   Errno::ENOENT: No such file or directory - artifacts/zrepl
20:52:52 
20:52:52 ==> brew audit zrepl --online

**Comment by JMoVS** [comment]
Hi chenrui333 - maintainer here - apparently there was a refactor of the makefile - we may need to accomodate for this in the brew formula

https://github.com/zrepl/zrepl/releases/tag/v0.2.1

**Comment by dawidd6** [comment]
Seems like simple `go build -o bin/name` is enough to build this project.

**Comment by chenrui333** [comment]
yeah, they introduced 'GOOS' and 'GOARCH'. I think the build should be good now.

This commit is more relevant though, https://github.com/zrepl/zrepl/commit/080f2c0616d536cc1887a1ab3120c760e86a2e07

Thanks @JMoVS @dawidd6!!

**Comment by chenrui333** [comment]
@JMoVS, I think that seems more like a smell that we should try to use goreleaser.

**Pull request closed without merging**
