### PR TITLE
signal-cli 0.11.8

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~
<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* Document accepting group invitations by @exquo in https://github.com/AsamK/signal-cli/pull/1218

**Full Changelog**: https://github.com/AsamK/signal-cli/compare/v0.11.7...v0.11.8</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    --- stderr
    gmake: warning: -j2 forced in submake: resetting jobserver mode.
    thread 'main' panicked at '"__atomic_wide_counter_struct_(unnamed_at_/usr/include/x86_64-linux-gnu/bits/atomic_wide_counter_h_28_3)" is not a valid Ident', /github/home/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.29/src/fallback.rs:702:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
```

**Comment by ZhongRuoyu** [comment]
Error was due to a change in LLVM 16. https://github.com/rust-lang/rust-bindgen/pull/2319 explains that.

**Comment by ZhongRuoyu** [comment]
I tried to use `cargo update --package bindgen --precise 0.64.0` but failed due to `boring-sys`'s requirement [here](https://github.com/cloudflare/boring/blob/da2c13e7618acf3f5b4f9da03233b79c2a183665/boring-sys/Cargo.toml#L30). It's not present in the `libsignal` source and thus not easily patchable.

**Comment by ZhongRuoyu** [comment]
`The self-hosted runner: bigsur-arm-3 lost communication with the server.` But there are no dependants to test so that's okay.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
