### PR TITLE
k6 0.28.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/*
 *
 * k6 - a next-generation load testing tool
 * Copyright (C) 2017 Load Impact
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
```

**Review by SMillerDev — COMMENTED** [review]
Does it still print the correct version after this? Cause that's a common problem with go.

**Comment by chenrui333** [comment]
it does.
```
    assert_match version.to_s, shell_output("#{bin}/k6 version")	
```

**Comment by chenrui333** [comment]
`Cause that's a common problem with go.` that is more like implementation issue case by case (in general, the code should have some `fallback_version` to use)

**Comment by imiric** [comment]
Hey guys, I'm one of the maintainers of k6, and we noticed this issue when we ran `brew bump-formula-pr k6` ourselves. Thanks for the initiative @chenrui333!

We noticed that the k6 formula builds the binary from source, but it doesn't include the build flags that we use in our [official releases](https://github.com/loadimpact/k6/releases), so the version information from `k6 version` won't be correct. In addition to this in v0.28.0 we switched to Go modules, so the `dep` tool isn't used anymore.

This could be fixed in the formula here, but we'd prefer it if Homebrew bundles [the same macOS binary from the official release](https://github.com/loadimpact/k6/releases/download/v0.28.0/k6-v0.28.0-mac.zip), verifies the checksum and bundles it in the Homebrew package. That way we don't have to maintain two separate builds.

We have limited familiarity with macOS and Homebrew, but is this possible/recommended?

**Comment by SMillerDev** [comment]
That is very explicitly not supported. We're an open source package manager and just shipping binaries therefore isn't something we're willing to do. See https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#official-vendor-taps for more info.

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
@imiric no worries, this would work exactly the same way as the macOS binary that built out by gorelaese.

**Pull request closed without merging**
