### PR TITLE
ocrmypdf 11.3.3

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
This failed because of a livecheck connectivity issue on 10.13 and 10.15.
@homebrew/core:
Should we be doing the livecheck check for every OS or just one? Should there be a "retry" mechanism to handle intermittent network issues?

**Comment by SMillerDev** [comment]
I triggered the "retry" mechanism :smile:

**Comment by chenrui333** [comment]
> Should there be a "retry" mechanism to handle intermittent network issues?

that sounds like we need special try catch flow to do that.

**Comment by chenrui333** [comment]
> Should we be doing the livecheck check for every OS or just one?

The livecheck part seems not quite ideal, we can probably move it up (before the CI tests)

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
