### PR TITLE
clipboard 0.8.3

### PR DESCRIPTION
**Pull request by nevack**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>
CBBannerRelease8 2

# About

The Clipboard Project is an advanced clipboard manager for the terminal. No other clipboard manager exists with features like an unlimited history, unlimited clipboards, and user friendliness all while being in the terminal!

# Summary
These are some nice optimizations and fixes to keep CB high quality. :)

# New
- Added async X11/Wayland clipboard compat! This allows you to copy multiple items without running CB each time. This feature works by creating a CB daemon that checks the X11/Wayland clipboard every two seconds and updates the internal clipboard if it detects a change.
- Optimized file reading
- Optimized color replacement to be 3x faster!
- Complain about a missing action if the chosen combination isn't available
- Added `NO_ALSA` compile option for CMake
- Optimized History action by performing tasks while waiting for threads to complete
- Optimized MIME and file extension inference
- Optimized History action AGAIN by caching color formatting
- Check that the clipboard name is compatible with the host filesystem
- Added zsh completions
- Added `ansi` theme that uses the ANSI 3-bit color system (#159)
- Added Antony Santos to bachata feature

# Fixed
- Fixed typo in manpage
- Fixed the Load action not working in piped situations
- Fixed silent confirmations not working for many messages
- Fixed memory issue on Clang ARM causing broken colors
- Fixed typo in help message
- Fixed displaying history on Windows
- Fixed segmentation fault if giving an empty argument that expects a string
- Fixed JSON escaping for Info and History actions
- Fixed JSON escaping not working for Unicode characters
- Fixed "last changed" in Info reporting changes for unrelated files when pasting
- Fixed not releasing a clipboard lock in the Status action

# Changed
- Changed "All of your clipboard with content" to "All your clipboards with content"
- Changed Info JSON's "lastChanged" key to "contentLastChanged"
- Only show progress messages if an action takes 500ms or longer
- Updated CMake C++ version to C++23
</pre>
</details>

### CODE REVIEW

**Comment by nevack** [comment]
Reported to upstream https://github.com/Slackadays/Clipboard/issues/166

**Comment by Slackadays** [comment]
@nevack could you check if the latest commit works? I added a potential fix for this problem

**Comment by Slackadays** [comment]
There is now a 0.8.3 release which has the fix

**Comment by nevack** [comment]
I don't know if it's acceptable to edit this automated PR, I think I'll try to bump again in a separate one.

**Comment by chenrui333** [comment]
> I don't know if it's acceptable to edit this automated PR, I think I'll try to bump again in a separate one.

it is acceptable, you just need to squash the commits and update the PR title

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
