### PR TITLE
code-server 4.1.0

### PR DESCRIPTION
**Pull request by jsjoeio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jsjoeio** [comment]
## Notes

Trying to understand what's actually wrong. 

Logs: https://github.com/Homebrew/homebrew-core/runs/5425429238?check_suite_focus=true

> Error: 2 failed steps!
> brew install --only-dependencies --verbose --build-bottle code-server
> brew install --verbose --build-bottle code-server

Having a hard time seeing what the actual error is 🤔

The only thing I see in `brew install --only-dependencies --verbose --build-bottle code-server` is this:
```ruby
  You can try again using:
    brew postinstall python@3.10
  Warning: The post-install step did not complete successfully
```

And then in `brew install --verbose --build-bottle code-server` I see this: 

```ruby
 Logs:
       /Users/brew/actions-runner-x86_64/_work/homebrew-core/homebrew-core/bottles/logs/code-server/00.options.out
       /Users/brew/actions-runner-x86_64/_work/homebrew-core/homebrew-core/bottles/logs/code-server/01.yarn
  READ THIS: https://docs.brew.sh/Troubleshooting
  
  Error: code-server 4.1.0 did not build
```

I'm not sure why it's saying it didn't build?

**Comment by jsjoeio** [comment]
so it's only failing on arm...I think we had to manually fix this last time: https://github.com/Homebrew/homebrew-core/pull/92582/files

Shouldn't these changes have made it into `homebrew` from that PR? 🤔 Maybe the `brew-bump-formula` used an older commit?

**Comment by jsjoeio** [comment]
Hmm maybe related to this? https://github.com/coder/code-server/issues/4896

**Comment by jsjoeio** [comment]
It seems like brew or something is swallowing the logs so I can't see the actual errors. I downloaded the logs but there's nothing in there either

**Comment by cho-m** [comment]
I am guessing a Homebrew CI issue, but will need someone else to take a look at ARM runners. There are some other PRs failing without logs and/or failing on `postinstall`.

**Comment by jsjoeio** [comment]
Now it's passing? 🤷‍♂️ That's magical lol yay!

**Review by chenrui333 — APPROVED** [review]

**Review by cho-m — APPROVED** [review]

**Comment by cho-m** [comment]
Some notes for Linux build to be explored outside this PR.

For Linux (not yet bottled, so ignored in CI), looks like there are a number of system libraries, which are mostly from `electron`.

Not sure if there is a way around this to allow us to package `code-server` for Linuxbrew. I guess an option would be to introduce an `electron@13` and hack the build to pick that up, similar to what [ArchLinux does for `code`](https://github.com/archlinux/svntogit-community/blob/packages/code/trunk/PKGBUILD).

---

```
Missing libraries:
  unexpected (libX11.so.6)
  unexpected (libXcomposite.so.1)
  unexpected (libXdamage.so.1)
  unexpected (libXext.so.6)
  unexpected (libXfixes.so.3)
  unexpected (libXrandr.so.2)
  unexpected (libasound.so.2)
  unexpected (libatk-1.0.so.0)
  unexpected (libatk-bridge-2.0.so.0)
  unexpected (libatspi.so.0)
  unexpected (libc.musl-x86_64.so.1)
  unexpected (libcairo.so.2)
  unexpected (libcups.so.2)
  unexpected (libdrm.so.2)
  unexpected (libgbm.so.1)
  unexpected (libgdk-3.so.0)
  unexpected (libgdk_pixbuf-2.0.so.0)
  unexpected (libgtk-3.so.0)
  unexpected (libnspr4.so)
  unexpected (libnss3.so)
  unexpected (libnssutil3.so)
  unexpected (libpango-1.0.so.0)
  unexpected (libsmime3.so)
  unexpected (libxcb.so.1)
  unexpected (libxkbcommon.so.0)
  unexpected (libxshmfence.so.1)
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libdbus-1.so.3
```

**Comment by jsjoeio** [comment]
> Not sure if there is a way around this to allow us to package code-server for Linuxbrew. I guess an option would be to introduce an electron@13 and hack the build to pick that up, similar to what [ArchLinux does for code](https://github.com/archlinux/svntogit-community/blob/packages/code/trunk/PKGBUILD).

I was talking to @code-asher about this. We used to exclude electron entirely since we don't use it. It somehow got added back in (we believe by accident from another maintainer).

We plan to revisit this in a future version of code-server (possibly removing electron/x11 dependencies in a build step) to avoid this.

**Pull request closed without merging**
