### PR TITLE
kumactl 1.0.7

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.8/envoy/api/v2/cds.pb.go:15:2: missing go.sum entry for module providing package google.golang.org/grpc (imported by github.com/kumahq/kuma/api/mesh/v1alpha1);
```

**Comment by tharun208** [comment]
@chenrui333, can we skip arm for now and proceed?

**Comment by SMillerDev** [comment]
It worked on ARM before. This is a regression that needs to be checked.

**Comment by tharun208** [comment]
@SMillerDev, so, we cant merge this until the regression passes?

**Comment by SMillerDev** [comment]
This update broke the software for ARM, we're not going to merge something we know to be broken.

**Comment by tharun208** [comment]
@SMillerDev, 1.0.6 (https://github.com/Homebrew/homebrew-core/pull/69565) also has arm issues, it got merged.

**Comment by carlocab** [comment]
@tharun208, that's because kumactl in #69565 lacked the fix in #69627. It wasn't bottled for ARM in #69565, so the ARM build failure wasn't blocking.

It's now been bottled since #69627, so the ARM build failure is blocking. Merging this will break things for users on ARM who have kumactl installed.

**Comment by chenrui333** [comment]
```
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.8/envoy/api/v2/cds.pb.go:15:2: missing go.sum entry for module providing package google.golang.org/grpc (imported by github.com/kumahq/kuma/api/mesh/v1alpha1); to add:
	go get github.com/kumahq/kuma/api/mesh/v1alpha1@v0.0.0-00010101000000-000000000000
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.8/envoy/api/v2/cds.pb.go:16:2: missing go.sum entry for module providing package google.golang.org/grpc/codes (imported by github.com/kumahq/kuma/api/mesh/v1alpha1); to add:
	go get github.com/kumahq/kuma/api/mesh/v1alpha1@v0.0.0-00010101000000-000000000000
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/istio.io/pkg@v0.0.0-20201012181155-29f8c67d2848/log/config.go:65:2: missing go.sum entry for module providing package google.golang.org/grpc/grpclog (imported by istio.io/pkg/log); to add:
	go get istio.io/pkg/log@v0.0.0-20201012181155-29f8c67d2848
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.8/envoy/api/v2/cds.pb.go:17:2: missing go.sum entry for module providing package google.golang.org/grpc/status (imported by github.com/kumahq/kuma/api/mesh/v1alpha1); to add:
	go get github.com/kumahq/kuma/api/mesh/v1alpha1@v0.0.0-00010101000000-000000000000
make: *** [build/kumactl] Error 1
```

**Comment by nickolaev** [comment]
I am trying to figure the source of the problem here.
Trying to build this on native Ubuntu arm64 (in a docker container) I managed to get it built without any changes:
```
root@613982c99ffd:/home/kuma# ./build/artifacts-linux-arm64/kumactl/kumactl version
Kuma: 1.0.7
root@613982c99ffd:/home/kuma# uname -a
Linux 613982c99ffd 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```
So obviously it is not a matter of HW arch per se. I Will try with homebrew on that same platform and see how it goes.

**Comment by tharun208** [comment]
we can close this as pr with fix (https://github.com/Homebrew/homebrew-core/pull/71176) got merged

**Pull request closed without merging**
