### PR TITLE
abcmidi 2017-10-11

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Error: SHA256 mismatch
Expected: cf35dc962e268a980a89f4bde5d67771d1e4127151e3eebd5141bcf6b9392ee4
Actual: c421bfe41f9fcb8d19b101e6c0e2057505416c7c4f30689184a8ca3fea2e1234

I just merged that one into Linuxbrew. @ilovezfs or @fxcoudert I have limited internet connection for the moment, could you have a look? Thanks :)

**Comment by ilovezfs** [comment]
here we go again

**Comment by ilovezfs** [comment]
```
iMac-TMP:abc joe$ diff old/abcmidi/parseabc.c new/abcmidi/parseabc.c
1367c1367
<   char word[30];
---
>   char word[64]; /* 2017-10-11 */
iMac-TMP:abc joe$ diff old/abcmidi/parseabc.h new/abcmidi/parseabc.h
17c17
< #define V_STRLEN 64
---
> #define V_STRLEN 256 /* [SS] 2017-10-11 increase from 64 */
iMac-TMP:abc joe$ diff old/abcmidi/toabc.c new/abcmidi/toabc.c 
24c24
< #define VERSION "1.95 October 11 2017 abc2abc"
---
> #define VERSION "1.97 October 11 2017 abc2abc"
1200c1200
<   char output[128];  /* [SS] 2017-10-09 */
---
>   char output[256];  /* [SS] 2017-10-09 2017-10-11 */
iMac-TMP:abc joe$ diff old/abcmidi/doc/CHANGES new/abcmidi/doc/CHANGES 
12490c12490
< parameters chopped short. Fix: in parseabc.h increased V_STRLEN to 128.
---
> parameters chopped short. Fix: in parseabc.h increased V_STRLEN to 256.
iMac-TMP:abc joe$ diff old/abcmidi/doc/readme.txt new/abcmidi/doc/readme.txt 
5c5
< abc2abc  version 1.95 October 11 2017
---
> abc2abc  version 1.97 October 11 2017
iMac-TMP:abc joe$ 
```
So they released 1.95 and 1.97 on the same day, which their tarball version scheme cannot handle. :(

**Comment by ilovezfs** [comment]
I've emailed fy733 AT ncf
DOT ca

**Comment by ilovezfs** [comment]
This now moot: https://github.com/Homebrew/homebrew-core/pull/19629

**Pull request closed without merging**
