### PR TITLE
openexr 3.0.3

### PR DESCRIPTION
**Pull request by crunchtime-ali**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by cho-m** [comment]
Looks like uninstalled binaries due to https://github.com/AcademySoftwareFoundation/openexr/pull/1008 where installation options were accidentally removed.

This is fixed in https://github.com/AcademySoftwareFoundation/openexr/pull/1022

**Comment by hjmallon** [comment]
Good spot, I have asked on the original issue https://github.com/AcademySoftwareFoundation/openexr/issues/1021

**Comment by cary-ilm** [comment]
This was an oversight in the OpenEXR v3.0.2, that fix got missed. I'll patch and put out a v3.0.3 release right away.

**Comment by cary-ilm** [comment]
This should be fixed now with the OpenEXR v3.0.3 release, https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.0.3.

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/77589

**Comment by crunchtime-ali** [comment]
Closing in favor of #77589

**Pull request closed without merging**
