### PR TITLE
Specified postgresql as a runtime dependency for pgcli.

### PR DESCRIPTION
**Pull request by j-bennet**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
I'm not sure what you're trying to fix, but `depends_on :postgresql` is a runtime dependency in itself, adding `=> :run` should not be needed.

**Comment by ilovezfs** [comment]
`=> :run` is used to suppress a specific audit error about tools that are usually build-time only being specified without `=> :build`. Beyond that, it has no impact on behavior.

**Comment by j-bennet** [comment]
@ilovezfs What I'm trying to achieve here is for homebrew not to update existing user's installation of postgresql. I tested the pgcli formula with and without `:run` with `--build-from-source`, and it looks to me like `:run` works for this case. Without it, homebrew update to the latest postgresql, which is not what I want.

**Comment by j-bennet** [comment]
@ilovezfs If `:run` is not the correct option to trigger the behavior, can you tell me what I should use?

**Comment by ilovezfs** [comment]
>What I'm trying to achieve here is for homebrew not to update the existing user's installation of postgresql.

This is not something we support.

> I tested the pgcli formula with and without :run with --build-from-source, and it looks to me like :run works for this case. Without it, homebrew updates to the latest postgresql, which is not what I want.

Yes, you're right about this. It's somewhat undocumented behavior that is not used in homebrew/core at all.

>If :run is not the correct option to trigger the behavior, can you tell me what I should use?

Typically, you'd use --build-from-source if you want to use something other than the `default_formula` to satisfy a requirement. In this case, it looks like the default formula was being used, with an outdated version, which we don't support even in the --build-from source case.

**Comment by j-bennet** [comment]
@ilovezfs I'm not sure what you mean by this:

> In this case, it looks like the default formula was being used, with an outdated version, which we don't support even in the --build-from source case.

There must be precedents for a formula where it's not necessary for the formula's dependencies to be at their latest version. pgcli is a client for postgresql. It depends on psycopg2, which is why we specify postgresql as a dependency, but we don't need postgresql to be any specific version. Many developers may have to stick to an older postgresql to mimic production. Is there a way for the formula to specify an acceptable version range?

**Comment by ilovezfs** [comment]
>There must be precedents for a formula where it's not necessary for the formula's dependencies to be at their latest version.

Only in some cases where a requirement is satisfied by something other than the default formula. So in this case that would mean a postgresql not provided by Homebrew.

>Is there a way for the formula to specify an acceptable version range?

Some requirements allow a minimum or exact version to be specified but `:postgresql` is not one of them.

**Comment by ilovezfs** [comment]
Note that we have

```
postgresql.rb      postgresql@9.4.rb  postgresql@9.5.rb 
```
and I believe all of them will satisfy the requirement.

**Comment by j-bennet** [comment]
@ilovezfs Woudl it be more correct is we specified postgresql as a `:build` dependency?

**Pull request closed without merging**
