### PR TITLE
nesc: depend on openjdk

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by bayandin** [comment]
Catalina build fails with `configure: error: cannot find emacs`

We need to add something like
```ruby
depends_on "emacs" if MacOS.version >= :catalina
```

**Comment by bayandin** [comment]
@chenrui333 I believe we need to update bottles for this PR

**Comment by chenrui333** [comment]
yeah, I am doing that now.

**Comment by chenrui333** [comment]
Did not realize this java have a bottle.

**Comment by chenrui333** [comment]
Somehow the bottle commit mismatch:

```
$ brew reinstall nesc
==> Reinstalling nesc
==> Downloading https://homebrew.bintray.com/bottles/nesc-1.4.0_1.mojave.bottle.tar.gz
Already downloaded: /Users/rchen/Library/Caches/Homebrew/downloads/69d04d74fbe4f29acf899d3f17d2ef150f5f8f71fa406dbe8f7abd0a0914aa41--nesc-1.4.0_1.mojave.bottle.tar.gz
Error: SHA256 mismatch
Expected: 421acf77b9f7eeb328811365a08b5b870c4386d2eb5ed8f1f0ccf919ac2e0bba
  Actual: aa88e3409a0528ef9437aedbbfaa4768b8aaeb462b7140c40ba6af9a74d6846e
 Archive: /Users/rchen/Library/Caches/Homebrew/downloads/69d04d74fbe4f29acf899d3f17d2ef150f5f8f71fa406dbe8f7abd0a0914aa41--nesc-1.4.0_1.mojave.bottle.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by chenrui333** [comment]
My bottle publish curl script.
```
$ curl --write-out --silent --fail \
→       --user "chenrui:xx" --request POST \
→       --header "Content-Type: application/json" \
→       https://api.bintray.com/content/homebrew/bottles/nesc/1.4.0_1/publish
{"files":3}--silent
```

**Pull request merged**
