### PR TITLE
wget: depend on libidn2

### PR DESCRIPTION
**Pull request by jdvorak001**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This should bring back the ability to use the `wget` option `--local-encoding=UTF-8`; wget was failing with _This version does not have support for IRIs_.

This basically fulfills the wish from the last sentence in https://github.com/Homebrew/homebrew-core/pull/9873#issuecomment-279179737, 
as `libidn2` is available now.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Unsure whether we want to add a seldom-used additional mandatory dependency to one of our most-used formulas. When `wget` had optional IRI support, it was used by [1% of users](https://github.com/Homebrew/homebrew-core/pull/9873#discussion_r100677390) only.

**Comment by ilovezfs** [comment]
>This should bring back the ability

have you tested it?

**Comment by jdvorak001** [comment]
Yes, I have tested it.

1. `brew test wget` finishes o.k.
2. `brew audit --strict wget` finds no problems.
3. It runs fine for me.

**Comment by jdvorak001** [comment]
@fxcoudert: The 1% are the users who ran into the problem and **had found** the solution in the past. My thinking is that if the wget(1) man page offers the `--local-encoding` option, homebrew should have a rather strong reason not to provide it by default. 

BTW, one needs this option to support non-English letters in the whole URI, not just in the server hostname: it's also characters in the path and the query string. When mirroring wikis, we often prefer to have these characters in the filenames directly rather than with the URI percent escapes. At least that's what I see as a common requirement here in Europe.

I can change the dependency to `:recommended`, if that's how it should be done.

**Comment by ilovezfs** [comment]
I think given wget is already saddled with openssl@1.1 that a little libidn2 won't hurt anyone.

**Review by JCount — APPROVED** [review]

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @jdvorak001! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
