### PR TITLE
k9s 0.25.3

### PR DESCRIPTION
**Pull request by nwhobart**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]

**Comment by nwhobart** [comment]
@carlocab this is the first time I've submitted a version bump PR. the error doesn't look like anything I can help fix is it?

**Review by carlocab — APPROVED** [review]
Probably just a transient network error. Let's try again in a bit.

Thanks, @nwhobart!

**Comment by nwhobart** [comment]
> Probably just a transient network error. Let's try again in a bit.
> 
> Thanks, @nwhobart!

Does the brew test bot / merge happen autonomously?

**Comment by nwhobart** [comment]
@carlocab is this supposed to happen like this? `brew update` shows the new version and `brew upgrade` upgraded appropriately however I'm curious why this didn't get merged into `Homebrew:master`.

**Pull request closed without merging**
