### PR TITLE
sapling 0.2.20231109-183451-14d92511

### PR DESCRIPTION
**Pull request by zzl0**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  sapling
    * 0.2.20231109-183451+14d92511 is a GitHub pre-release.
    * Non-executables were installed to "/opt/homebrew/opt/sapling/bin".
      The offending files are:
        /opt/homebrew/opt/sapling/bin/isl-dist.tar.xz
```

**Comment by chenrui333** [comment]
@zzl0 any chance that you can mark the recent releases as latest release? (mostly for the release semantics) Thanks!

**Comment by zzl0** [comment]
Hi @chenrui333, thanks for reviewing it. Yeah, I noticed those two audit check errors in the CI jobs. I have a fix for `Non-executables were installed to "/opt/homebrew/opt/sapling/bin"` error and was planning to test it and create a new release on Monday.

> @zzl0 any chance that you can mark the recent releases as latest release? (mostly for the release semantics) Thanks!

Yeah, I can mark it as latest release. Just wondering if `Non-executables were installed to "/opt/homebrew/opt/sapling/bin"` is a blocker for this PR:
* If no, I will mark the current release as latest release. And we will fix it in the next release.
* If yes, I will test my fix and release a new version on Monday.

**Comment by chenrui333** [comment]
> * Non-executables were installed to "/opt/homebrew/opt/sapling/bin".
>       The offending files are:
>         /opt/homebrew/opt/sapling/bin/isl-dist.tar.xz

we can just remove that tarball file (not sure why that got installed)

**Comment by zzl0** [comment]
> we can just remove that tarball file (not sure why that got installed)

Actually, that's needed by Sapling, it contains [ISL code](https://sapling-scm.com/docs/addons/isl), I have a fix to move it to `lib` directory, I will release a new version then.

**Comment by chenrui333** [comment]
If needed, you can also move to pkgshare folder

**Comment by zzl0** [comment]
@chenrui333 Sorry to bother you. I got the [following error](https://github.com/zzl0/sapling/actions/runs/6854566968) when running`HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-bottle sapling` today, which [succeeded](https://github.com/zzl0/sapling/actions/runs/6836677381) on Saturday on the same commit.

> Last 15 lines from /Users/runner/Library/Logs/Homebrew/sapling/03.0.2.20231111-162854+16d9bad6:

**I was wondering if you know how to get more lines from the Homebrew log file?**

```
==> source /Users/runner/Library/Caches/Homebrew/cargo_cache/env && make PREFIX=
Last 15 lines from /Users/runner/Library/Logs/Homebrew/sapling/03.0.2.20231111-162854+16d9bad6:
  cargo:warning=         ^~~~~~~~~~~

  cargo:warning=1 error generated.

  exit status: 1

  --- stderr


  error occurred: Command "clang++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-apple-darwin" "-mmacosx-version-min=10.7" "-I" "/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11" "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-function" "-fno-common" "-dynamic" "-DNDEBUG" "-g" "-fwrapv" "-O3" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk" "-o" "/private/tmp/sapling-20[23](https://github.com/zzl0/sapling/actions/runs/6854566968/job/18637777930#step:7:24)1113-2671-1khnzbs/eden/scm/build/cargo-target/x86_64-apple-darwin/release/build/pycext-4bf[24](https://github.com/zzl0/sapling/actions/runs/6854566968/job/18637777930#step:7:25)58160d01796/out/713ff949e19e1a67-traceprofimpl.o" "-c" "../../../../sapling/cext/../ext/extlib/traceprofimpl.cpp" with args "clang++" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
error: compilation of Rust target 'hgmain' failed
make: *** [local] Error 1
```

**Pull request closed without merging**
