### PR TITLE
gdal 3.3.0

### PR DESCRIPTION
**Pull request by jacopofar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @jacopofar.

On ARM:
```
Error: 6 failed steps!
brew linkage --test mapnik
brew linkage --test pdal
brew test --retry --verbose pdal
brew linkage --test postgis
brew linkage --test simple-tiles
brew test --retry --verbose simple-tiles
```
These formulae need revision bumps. You can do this simply with:
```
cd "$(brew --repo homebrew/core)"
git checkout bump-gdal-3.3.0
brew bump-revision --message="(gdal 3.3.3)" mapnik pdal postgis simple-tiles
git push
git checkout master
```

**Comment by nandahkrishna** [comment]
Mojave failures:
```
brew linkage --test gmt
brew test --retry --verbose gmt
brew linkage --test gmt@5
brew test --retry --verbose gmt@5
brew linkage --test mapserver
brew test --retry --verbose mapserver
brew linkage --test osmcoastline
brew test --retry --verbose osmcoastline
brew linkage --test points2grid
brew test --retry --verbose points2grid
```
`gmt`, `gmt@5`, `mapserver`, `osmcoastline` and `points2grid` would need revision bumps as well.

**Comment by carlocab** [comment]
@nandahkrishna you have a merge conflict; you need to rebase.

**Comment by carlocab** [comment]
`gmt@5` didn't build. Might be from a new CMake.

**Comment by nandahkrishna** [comment]
@carlocab It doesn't seem like `gmt@5` has had any new releases, and the `5.4` branch at https://github.com/GenericMappingTools/gmt/tree/5.4 hasn't had commits since 2019.

Do we patch this ourselves to work with CMake 3.20+ or deprecate/disable the formula?

**Comment by carlocab** [comment]
From analytics...

Index | Name (with options)                                                                                    |   Count |  Percent
-----:|--------------------------------------------------------------------------------------------------------|--------:|--------:
1     | gdal                                                                                                   | 220,967 |   98.02%
2     | gdal --HEAD                                                                                            |   4,460 |    1.98%
Total |                                                                                                        | 225,427 |  100.00%


Index | Name (with options)                                                                                      | Count |  Percent
-----:|----------------------------------------------------------------------------------------------------------|------:|--------:
1     | gmt@5                                                                                                    |   774 |  100.00%

Yep, no justifying holding `gdal` back for `gmt@5`.

If we can patch `gmt@5` let's patch it. Possibly deprecate it even if we can patch it. Is this version still maintained?

**Comment by carlocab** [comment]
I suggest we drop the `gmt@5` revision bump from here, merge this PR, and work on fixing `gmt@5` in a separate PR (whether it's  to patch it or deprecate/disable it).

We did the same with `gcc` and `gromacs`.

**Comment by nandahkrishna** [comment]
Only `gmt@5` failed CI, as expected. This should be good to merge, and we can handle `gmt@5` separately.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Feel free to merge whenever you're ready.

**Pull request closed without merging**
