### PR TITLE
x264 r2728, r2744 (devel)

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`stable` now includes new and improved x86 assembly code that before were limited to the `devel` build.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
🍏 ❗️ 😄 👍 👏

**Comment by ilovezfs** [comment]
Thanks @JCount :bowing_man:

**Comment by dunn** [comment]
I've been seeing problems with bottles recently, did `brew pull` exit cleanly?
```
==> Downloading https://homebrew.bintray.com/bottles/x264-r2728.sierra.bottle.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.4 (Macintosh; Intel macOS 10.12.2) curl/7.51.0 https://homebrew.bintray.com/bottles/x264-r2728.sierra.bottle.tar.gz -C 0 -o /Users/alex/Library/Caches/Homebrew/x264-r2728.sierra.bottle.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "x264"
Download failed: https://homebrew.bintray.com/bottles/x264-r2728.sierra.bottle.tar.gz

**Comment by ilovezfs** [comment]
https://bintray.com/homebrew/bottles/x264#files/

yes, and all 3 are there

**Comment by dunn** [comment]
Huh, now I'm getting a 200.  Maybe there was a delay somewhere.

**Comment by ilovezfs** [comment]
I keep getting really long delays on the "Waiting for Bintray …"

**Comment by dunn** [comment]
Me too.  But they eventually finish?

**Comment by ilovezfs** [comment]
yup. sometimes i'll cancel and try again until they do ... :see_no_evil:

**Comment by ilovezfs** [comment]
@dunn lol
```
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "sratoolkit"
Download failed: https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
iMac-TMP:~ joe$ brew install sratoolkit
==> Installing sratoolkit from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/sratoolkit-2.8.0-2.el_capitan.bottle.1.t
######################################################################## 100.0%
==> Pouring sratoolkit-2.8.0-2.el_capitan.bottle.1.tar.gz
Warning: homebrew/science/sratoolkit dependency hdf5 was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/sratoolkit/2.8.0-2: 128 files, 91.2M
```

**Comment by dunn** [comment]
Oh dear.

**Comment by JCount** [comment]
wow....

**Pull request closed without merging**
