### PR TITLE
mapnik 3.0.23

### PR DESCRIPTION
**Pull request by pOmelchenko**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by pOmelchenko** [comment]
Tested with deps from master and tested with update icu4c (from #52481) too. In all tries I have success compiling

**Comment by pOmelchenko** [comment]
@Bo98 if I add changes with reverting deleted rows about bottles, queue will update? Or I will have two tries into queue?

**Comment by Bo98** [comment]
On Jenkins it replaces your original build. On GitHub Actions it will have two entries but don't worry about that - I can easily cancel one.

**Comment by pOmelchenko** [comment]
Please check changes in that PR before jobs start :) Because I'm not sure in last times with changes in this repo 🙈

**Comment by Bo98** [comment]
Looks good. We prefer the commit message to be "mapnik 3.0.23" rather than "update mapnik version" but I can probably correct that while merging since it's just one commit.

**Comment by pOmelchenko** [comment]
Thx! In other PR I fix all commit messages with all recommendations

**Pull request closed without merging**
