### PR TITLE
bazel 0.27.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
This needs to be addressed
```
[1A[KError occurred while attempting to use the default Python toolchain (@bazel_tools//tools/python:autodetecting_toolchain).
13:36:50 According to '/usr/bin/python -V', version is 'Python 2.7.10', but we need version 3. PATH is:
13:36:50 
13:36:50 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin
13:36:50 
13:36:50 Please ensure an interpreter with version 3 is available on this platform as 'python3' or 'python', or else register an appropriate Python toolchain as per the documentation for py_runtime_pair (https://github.com/bazelbuild/bazel/blob/master/tools/python/toolchain.bzl).
13:36:50 
13:36:50 Note that prior to Bazel 0.27, there was no check to ensure that the interpreter's version matched the version declared by the target (#4815). If your build worked prior to Bazel 0.27, and you're sure your targets do not require Python 3, you can opt out of this version check by using the non-strict autodetecting toolchain instead of the standard autodetecting toolchain. This can be done by passing the flag `--extra_toolchains=@bazel_tools//tools/python:autodetecting_toolchain_nonstrict` on the command line or adding it to your bazelrc.
13:36:50 ----------------
13:36:50 Note: The failure of target //src:create_embedded_tools (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.
13:36:50 
13:36:50 If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
```

**Comment by chenrui333** [comment]
Added py3 dep for build

**Comment by chenrui333** [comment]
```
07:07:08 ==> Installing 'bundler' gem
07:07:08 Successfully installed bundler-2.0.2
07:07:08 1 gem installed
07:07:08 Error: 1 problem in 1 formula detected
07:07:08 bazel:
07:07:08   * C: 16: col 3: dependency "python" (line 16) should be put before dependency "macos" (line 15)
```

**Comment by chenrui333** [comment]
It should be fixed now.

**Comment by chenrui333** [comment]
```
00:53:46 ==> brew style bazel
00:53:50 ==> FAILED
00:53:50 == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bazel.rb ==
00:53:50 C: 14: 22: Unnecessary spacing detected.
00:53:50 
00:53:50 1 file inspected, 1 offense detected
```

**Comment by chenrui333** [comment]
Finally, it is good now!

**Comment by chenrui333** [comment]
@fxcoudert it can be merged now.

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Pull request closed without merging**
