### PR TITLE
cfr-decompiler: use `openjdk@11`

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Needed for #126319. See failure [here](https://github.com/Homebrew/homebrew-core/actions/runs/4488442125/jobs/7893146179?pr=126319#step:11:1329).

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
> Is this upstreamed?

Upstream still targets Java 1.6, but I have reservations about upstraming this, because in my opinion, similar to `inreplace`-ing `-std=c++11` to `-std=c++17` in C++-based formulae, it is our decision to target newer toolchains in our builds.

**Comment by SMillerDev** [comment]
But upstream should probably be aware their software doesn't work on OpenJDK 20. We're not doing this because we like patches, we're doing this because it doesn't work otherwise.

**Comment by ZhongRuoyu** [comment]
Makes sense. Let me file an upstream issue.

**Comment by ZhongRuoyu** [comment]
Ah okay, upstream says this in their [`contributing.md`](https://github.com/leibnitz27/cfr/blob/master/contributing.md):

> It's in Java 6. This is deliberate. This won't change. It even runs on [Apache's JVM6 clone, Harmony](https://harmony.apache.org/).

Also in the same doc:

> ## Not great things to contribute
> Java above 6.  See above.  *I know.*  But it's all syntactic sugar anyway.  **cough**.  Anyway, you get to work with $$FUNKY_NEW_LANGUAGE$$ in your day job.

Well... Either we bump the target version to 1.8, or we may use an older `openjdk`.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
