### PR TITLE
cedille: build with haskell-stack

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Does `cedille` also need `alex` and `happy`, or was that just to build `agda`? Because there should be `alex` and `happy` binaries in `agda`'s `libexec`.

**Comment by SeekingMeaning** [comment]
Hmm, that's a good question

**Comment by carlocab** [comment]
Wel, CI passed.. so I guess not?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
lgtm. 💯

**Comment by chenrui333** [comment]
> Does `cedille` also need `alex` and `happy`, or was that just to build `agda`? Because there should be `alex` and `happy` binaries in `agda`'s `libexec`.

I got inferred from the stack.yaml, so that is vendored in the build process (we will need to look at it later)

**Comment by carlocab** [comment]
>I got inferred from the stack.yaml, so that is vendored in the build process

So that means it tried to install its own `alex` and `happy`?

**Comment by chenrui333** [comment]
> > I got inferred from the stack.yaml, so that is vendored in the build process
> 
> So that means it installed its own `alex` and `happy`?

to my understanding, yes. you can also check discussions on this PR, https://github.com/Homebrew/brew/pull/6945

**Pull request closed without merging**
