### PR TITLE
mesos 1.0.1

### PR DESCRIPTION
**Pull request by haosdent**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by haosdent** [comment]
yosemite and sierra could pass. And ei_capitan failed by

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/mesos/1.0.1/lib/libmesos-1.0.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

My osx version is ei_capitan and brew install locally successfully, if this error is expected?

**Comment by ilovezfs** [comment]
```
diff --git a/Formula/mesos.rb b/Formula/mesos.rb
index 8af63cc..99ebe44 100644
--- a/Formula/mesos.rb
+++ b/Formula/mesos.rb
@@ -59,6 +59,10 @@ class Mesos < Formula
   def install
     ENV.java_cache
 
+    if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
+      ENV["ac_have_clock_syscall"] = "no"
+    end
+
     boto_path = libexec/"boto/lib/python2.7/site-packages"
     ENV.prepend_create_path "PYTHONPATH", boto_path
     resource("boto").stage do
```

**Comment by haosdent** [comment]
@ilovezfs Thank you! Let me update

**Comment by haosdent** [comment]
@ilovezfs @zmwangx May you help merge this?

**Comment by ilovezfs** [comment]
@haosdent it looks like some of the resources are outdated and should be bumped to their latest versions here too, with special attention to whether it works with protobuf 3.x

Also, I wonder if this can be converted to depend on the `protobuf` formula instead of the pypi version?

**Comment by haosdent** [comment]
Hi, @ilovezfs Thanks a lot for your view. Mesos don't support protobuf 3.x because it would break backwards compatibility. We have an open ticket for this. http://issues.apache.org/jira/browse/MESOS-5186

>Also, I wonder if this can be converted to depend on the protobuf formula instead of the pypi version?

Could not, because mesos use a bundle protobuf in its source code.

**Comment by ilovezfs** [comment]
@haosdent Ah, ok. Thanks for the explanation.

Please make sure the other resource blocks are updated to their latest versions.

**Comment by haosdent** [comment]
Thanks @ilovezfs' quick reply. Confirmed

**Comment by ilovezfs** [comment]
```
  resource "boto" do
    url "https://files.pythonhosted.org/packages/c4/bb/28324652bedb4ea9ca77253b84567d1347b54df6231b51822eaaa296e6e0/boto-2.42.0.tar.gz"
    sha256 "dcf140d4ce535bb8f5266d1750c16def4d50f6c46eff27fab38b55d0d74d5ac7"
  end

  resource "six" do
    url "https://files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz"
    sha256 "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a"
  end

  resource "python-dateutil" do
    url "https://files.pythonhosted.org/packages/3e/f5/aad82824b369332a676a90a8c0d1e608b17e740bbb6aeeebca726f17b902/python-dateutil-2.5.3.tar.gz"
    sha256 "1408fdb07c6a1fa9997567ce3fcee6a337b39a503d80699e0f213de4aa4b32ed"
  end

  resource "pytz" do
    url "https://files.pythonhosted.org/packages/f7/c7/08e54702c74baf9d8f92d0bc331ecabf6d66a56f6d36370f0a672fc6a535/pytz-2016.6.1.tar.bz2"
    sha256 "b5aff44126cf828537581e534cc94299b223b945a2bb3b5434d37bf8c7f3a10c"
  end

  resource "python-gflags" do
    url "https://files.pythonhosted.org/packages/6b/1c/47996c14dc91249376f218c0f943da3b85ff7e9af9c5de05cd2600c8afb4/python-gflags-3.0.7.tar.gz"
    sha256 "db889af55e39fa6a37125d6aa70dfdd788dbc180f9566d3053250e28877e68dc"
  end

  resource "google-apputils" do
    url "https://files.pythonhosted.org/packages/69/66/a511c428fef8591c5adfa432a257a333e0d14184b6c5d03f1450827f7fe7/google-apputils-0.4.2.tar.gz"
    sha256 "47959d0651c32102c10ad919b8a0ffe0ae85f44b8457ddcf2bdc0358fb03dc29"
  end
```

**Comment by haosdent** [comment]
Hi, @ilovezfs Many thanks for your great helps! Have updated.

**Comment by ilovezfs** [comment]
hmm ... did u push the update?

**Comment by haosdent** [comment]
Oh, sorry. Forget to add `--force`.

**Comment by haosdent** [comment]
Wait for the build result of bot.

**Comment by haosdent** [comment]
@ilovezfs Sorry to ping you again. Now should be fine?

**Comment by ilovezfs** [comment]
yup looks great!

**Comment by ilovezfs** [comment]
@haosdent thanks for your contribution to Homebrew! Nice job on this PR :100:

**Comment by haosdent** [comment]
@ilovezfs Thanks for your great help! Apology that I didn't check dependencies carefully before.

**Comment by ilovezfs** [comment]
@haosdent You're welcome! No need to apologize. It happens more often than not!

**Pull request closed without merging**
