### PR TITLE
ffmpeg: added openvino dependency

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by retokromer — COMMENTED** [review]
```
--enable-openvino
```

**Comment by ilya-lavrenov** [comment]
> ```
> --enable-openvino
> ```

https://github.com/FFmpeg/FFmpeg/blob/master/configure#L254

**Comment by retokromer** [comment]
My bad, sorry for the noise.

**Comment by ilya-lavrenov** [comment]
Failure is not related to OpenVINO
https://github.com/Homebrew/homebrew-core/actions/runs/7473452606/job/20338618911?pr=159295#step:3:491

**Comment by ilya-lavrenov** [comment]
> Failure is not related to OpenVINO https://github.com/Homebrew/homebrew-core/actions/runs/7473452606/job/20338618911?pr=159295#step:3:491

@cho-m 
Could you please advice how to resolve the issue?

**Comment by bevanjkay** [comment]
@ilya-lavrenov The failure is unrelated, and known so this is okay to be merged as is.

**Comment by p-linnane** [comment]
We shouldn't revision bump this and force a reinstall for everyone. We can rebuild the bottles so that new installs and reinstalls have it, and then everyone will get it on the next version bump.

**Comment by ilya-lavrenov** [comment]
> We shouldn't revision bump this and force a reinstall for everyone. We can rebuild the bottles so that new installs and reinstalls have it, and then everyone will get it on the next version bump.

it's already one

**Comment by bevanjkay** [comment]
@ilya-lavrenov Can you remove the revision update for this? We **shouldn't** revision bump here as the update won't be useful for a majority of users.

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov Can you remove the revision bump for this? We **shouldn't** revision bump here as the update won't be useful for a majority of users.

done

**Review by p-linnane — APPROVED** [review]
Thanks!

**Pull request merged**
