### PR TITLE
flyway 5.0.2 (updated formula) - Updated flyway verson from 4.2.0

### PR DESCRIPTION
**Pull request by spencerdcarlson**
Flyway 4.2.0 has a conflict with Java 9 - [flyway issue 1545](https://github.com/flyway/flyway/issues/1545) and no longer works on the latest version of MacOS. Flyway 5.0.2 works with Java 9 and the latest version of MacOS

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
This needs to be built from source. That tarball has pre-compiled Mach-O files.

**Comment by spencerdcarlson** [comment]
@ilovezfs I updated the traball to the non-OS specific version.

**Review by ilovezfs — APPROVED** [review]

**Comment by Moisan** [comment]
This is related to #19696 .

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @spencerdcarlson! :flight_departure:

**Comment by ilovezfs** [comment]
#19696 updated @Moisan

**Pull request merged**
