### PR TITLE
screenpipe 0.2.4

### PR DESCRIPTION
**Pull request by louis030195**
Automated update to version 0.2.4

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by p-linnane** [comment]
Linux needs an `xz` dep.

**Comment by louis030195** [comment]
> Linux needs an `xz` dep.

what do i need to do?

**Comment by louis030195** [comment]
@p-linnane did what claude said

`depends_on "xz" => :build`

**Comment by p-linnane** [comment]
It's a runtime dependency, so we needed to drop the `:build`. I've pushed that here and taken `pkgconf` out of the `on_linux` conditional since it's pulled in by `rust` anyway.

**Comment by louis030195** [comment]
anything else required to merge?

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
