### PR TITLE
mitmproxy@4

### PR DESCRIPTION
**Pull request by chimurai**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Need older version mitmproxy@4 due to a bug in latest `mitmproxy` (version 5) 

Makes latest revision of mitmproxy 4.0.4 available with `mitmproxy@4`

Direct copy of this latest revision:
https://github.com/Homebrew/homebrew-core/blob/8f17964/Formula/mitmproxy.rb

Removed:
```ruby
head
revision
```

Added:
```ruby
keg_only :versioned_formula
```

### CODE REVIEW

**Comment by Bo98** [comment]
> due to a bug in latest `mitmproxy` (version 5)

What is the bug you refer to?

**Comment by chimurai** [comment]
Hi @Bo98 
Referring to this issue: https://github.com/mitmproxy/mitmproxy/issues/3778

It's unreleased.

Would be nice to have `mitmproxy@4` available so we can choose to use between `v4` or `v5`

**Comment by Bo98** [comment]
We could potentially apply a patch to `mitmproxy` with that fix.

**Comment by chimurai** [comment]
That would be nice.

I'll have to dig into brew patching.

Got any good resources on that?

**Comment by Bo98** [comment]
Looking at existing formulae is probably the best way:

https://github.com/Homebrew/homebrew-core/blob/31ae0e5eb7d3d63cdc5047ee779a4c43286c8f65/Formula/mongrel2.rb#L6-L15

**Comment by chimurai** [comment]
Applying a patch seems to work!

Shall I create a new PR for `mitmproxy` with patch and close this one?

**Comment by Bo98** [comment]
Yeah, I think that's the way to go.

**Comment by chimurai** [comment]
Created a new PR at https://github.com/Homebrew/homebrew-core/pull/52417

**Pull request closed without merging**
