### PR TITLE
m4 1.4.19

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Continues #78294

**Review by Edord99 — APPROVED** [review]

**Comment by SMillerDev** [comment]
Current Solr 7.7.x support state is "might receive security fixes" so I don't think we'll be able to fix this.

**Comment by SMillerDev** [comment]
With m4 1.4.19 pympress and solr work just fine locally (although on macOS 12.0), pympress has been recently updated so that might have fixed something. And as for solr, I think I just want to disable it if it fails again.

**Comment by SMillerDev** [comment]
@Homebrew/maintainers opinions on just merging this?

**Review by carlocab — APPROVED** [review]
LGTM. I actually very much doubt the failures are due to the m4 version bump.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
