### PR TITLE
gx 0.14.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Note that we are actively working on deprecating go_resource blocks, which include gx: #21801.

**Comment by SMillerDev** [comment]
Could you change the go_resource blocks here @igas ?

**Comment by igas** [comment]
Hi @Moisan @SMillerDev I'm not very familiar with go, how do I check repo have dependency management? Should I just delete blocks or create upstream issue?

**Comment by SMillerDev** [comment]
@Moisan could you help with this?

**Comment by igas** [comment]
@Moisan In last days I learned a bit more from other formulas, yet I don't see `vgo` or `Gopkg.lock` there.

**Pull request closed without merging**
