### PR TITLE
rom-tools 0.218

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Seing a build failure:

```
../../../../../src/lib/util/server_ws_impl.hpp:79:87: error: no member named 'get_io_service' in 'asio::basic_stream_socket<asio::ip::tcp, asio::executor>'
                        explicit Connection(socket_type *socket): super(0), socket(socket), strand(socket->get_io_service()), closed(false) { }
                                                                                                   ~~~~~~  ^
```

**Comment by mistydemeo** [comment]
Looks like that was deprecated in older versions of `asio`, and may have been removed in 1.14.0:

> I/O objects (such as sockets and timers) now provide access to their associated `io_service` via a `context()` member function. The `get_io_service()` member function is deprecated.

**Comment by mistydemeo** [comment]
Upstream issue: https://github.com/mamedev/mame/issues/5721

We may be able to build with the `asio` dep removed and `USE_SYSTEM_LIB_ASIO=0`.

**Comment by mistydemeo** [comment]
```diff
diff --git a/Formula/rom-tools.rb b/Formula/rom-tools.rb
index a4af87708b..c29c0b1dc4 100644
--- a/Formula/rom-tools.rb
+++ b/Formula/rom-tools.rb
@@ -13,7 +13,6 @@ class RomTools < Formula
     sha256 "d00dfa62f18e09ab0c51bb1ffb64b4599ded97941f38b8b6b347a4322dd6c869" => :high_sierra
   end
 
-  depends_on "asio" => :build
   depends_on "pkg-config" => :build
   depends_on "flac"
   # Need C++ compiler and standard library support C++14.
@@ -29,7 +28,7 @@ class RomTools < Formula
                    "USE_LIBSDL=1",
                    "USE_SYSTEM_LIB_EXPAT=1",
                    "USE_SYSTEM_LIB_ZLIB=1",
-                   "USE_SYSTEM_LIB_ASIO=1",
+                   "USE_SYSTEM_LIB_ASIO=0",
                    "USE_SYSTEM_LIB_FLAC=1",
                    "USE_SYSTEM_LIB_UTF8PROC=1"
     bin.install %w[
```

**Comment by chenrui333** [comment]
Thanks @mistydemeo

**Pull request closed without merging**
