### PR TITLE
llvm: trim options

### PR DESCRIPTION
**Pull request by fxcoudert**
`llvm` has a great number of options, many of them being very rarely used. I am proposing that we cut anything that does 0.2% or less (that's 16 installs per month). We retain the most-used options.

```
install_on_request events in the last 30 days
================================================================================================================================
 1 | llvm                                                                                                      | 5,883 |  75.03%
 2 | llvm --with-toolchain                                                                                     | 1,343 |  17.13%
 3 | llvm --HEAD                                                                                               |   156 |   1.99%
 4 | llvm --HEAD --with-python@2                                                                               |    47 |   0.60%
 5 | llvm --with-lldb                                                                                          |    46 |   0.59%
 6 | llvm --with-toolchain --with-lldb                                                                         |    33 |   0.42%
 7 | llvm --with-lldb --with-python@2                                                                          |    31 |   0.40%
 8 | llvm --devel                                                                                              |    26 |   0.33%
 9 | llvm --HEAD --with-toolchain                                                                              |    25 |   0.32%
10 | llvm --with-python@2                                                                                      |    19 |   0.24%
11 | llvm --with-toolchain --with-shared-libs                                                                  |    16 |   0.20%
12 | llvm --HEAD --with-lldb                                                                                   |    14 |   0.18%
13 | llvm --with-toolchain --with-lldb --with-python@2 --with-shared-libs --with-polly-gpgpu --with-graphviz - |    13 |   0.17%
14 | llvm --with-toolchain --with-python@2                                                                     |     9 |   0.11%
15 | llvm --devel --with-toolchain                                                                             |     8 |   0.10%
16 | llvm --with-shared-libs                                                                                   |     8 |   0.10%
17 | llvm --with-toolchain --with-shared-libs --with-graphviz                                                  |     8 |   0.10%
18 | llvm --with-graphviz                                                                                      |     7 |   0.09%
19 | llvm --with-toolchain --with-lldb --with-graphviz                                                         |     7 |   0.09%
20 | llvm --with-toolchain --with-graphviz                                                                     |     6 |   0.08%
21 | llvm --with-toolchain --with-lldb --with-python@2 --with-graphviz                                         |     6 |   0.08%
22 | llvm --with-toolchain --with-shared-libs --with-polly-gpgpu --with-graphviz --with-ocaml                  |     6 |   0.08%
23 | llvm --HEAD --with-toolchain --with-python@2 --with-shared-libs --with-polly-gpgpu --with-graphviz --with |     5 |   0.06%
24 | llvm --with-toolchain --with-lldb --with-python@2                                                         |     5 |   0.06%
```

### CODE REVIEW

**Comment by fxcoudert** [comment]
Also of note: about half of the installs `--with-toolchain` fail:

```
BuildError events in the last 30 days
===============================================================================
 1 | llvm --with-toolchain                                      | 515 |  77.33%
 2 | llvm                                                       |  19 |   2.85%
 3 | llvm --with-toolchain --with-lldb                          |  10 |   1.50%
```

**Comment by fxcoudert** [comment]
- Mojave test failures are unrelated.
- @MikeMcQuaid opinion welcome, given this is a particularly important formula :)

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Works for me. Can you clean up the versioned ones to be consistent too? Thanks!

**Comment by CYBAI** [comment]
@fxcoudert @MikeMcQuaid When I'd like to re-install `llvm` today, I suddenly found the `--with-shared-libs` doesn't work. I'd need the flag for enabling `BUILD_SHARED_LIBS`, or I cannot build my packages successfully.

Besides, the 11th option is `llvm --with-toolchain --with-shared-libs`; maybe that flag is still useful for developers?

Could we get the `--with-shared-libs` back? Thanks.

**Comment by fxcoudert** [comment]
To give some insight behind the decision: Analytics for the `llvm` formula show that about 0.4% of users used `--with-shared-libs` (about 50 installs per month). Moreover, this option is almost always used alongside `--with-toolchain`, and those specific source builds have a failure rate over 60%.

We can't cater to every user out there. We could, possibly, build both static and shared libs into the bottles, but that would be huge, I guess. Fact is: the llvm project decided to build only static libs by default.

**Pull request merged**
