### PR TITLE
cling 0.9

### PR DESCRIPTION
**Pull request by razzius**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @razzius. Does the `llvm` resource not need updating?

**Comment by razzius** [comment]
@carlocab I think llvm and clang should be updated, and I've been iterating on that over at https://github.com/razzius/homebrew-tap-cling/pull/1. If that works I'll update this with those versions.

**Comment by razzius** [comment]
This built fine for MacOS; for Linux there was [an issue](https://github.com/razzius/homebrew-tap-cling/runs/2519786763):

```
==> brew linkage --test razzius/tap-cling/cling
==> FAILED
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz3.so.4
```

I don't see libz3 referenced anywhere in cling; I'm not sure what's going on with that...

**Comment by Bo98** [comment]
In the LLVM formula we avoid that with `-DLLVM_ENABLE_Z3_SOLVER=OFF`.

**Review by carlocab — APPROVED** [review]
Thanks, @razzius.

**Pull request closed without merging**
