### PR TITLE
heroku 6.11.14

### PR DESCRIPTION
**Pull request by jdx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Not sure when the formula switched from the Ruby to the Node-based tool, but is it possible to build it from source using Yarn instead of using the precompiled version?

**Comment by dickeyxxx** [comment]
it's likely not to work at all unless users are on the latest version of node and we do not intend to ever back-support old versions. So technically yes, but that's definitely not the way we'd like users to install the tool with homebrew.

**Comment by dunn** [comment]
> it's likely not to work at all unless users are on the latest version of node

Can you elaborate a bit?  Is there a runtime dependency on Node?

**Comment by dickeyxxx** [comment]
yeah it's all written in node

**Comment by dunn** [comment]
Homebrew provides the latest version of Node so I don't see why we couldn't modify the wrapper script to point at it.

If that's not something you want to explore, this might be a better fit for Homebrew Cask.

**Comment by dickeyxxx** [comment]
Using the homebrew version of node is fine, but if a user is developing an app on an earlier version of node than the CLI supports then it will not function. We've been doing this for over 2 years and it has been very successful.

**Comment by dunn** [comment]
Totally understandable; but in that case I'd recommend it be migrated to Cask: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask

cc @Homebrew/maintainers

**Comment by dickeyxxx** [comment]
We had a cask before, but we got rid of it to have just one install method. What about people that currently have the formula installed? Is there any way to help them migrate them to the cask?

**Comment by ilovezfs** [comment]
This has come up more than once before, most recently in https://github.com/Homebrew/homebrew-core/issues/9770. The status quo is not acceptable given our policies in Homebrew, but that's not something we need to figure out today.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @dickeyxxx

**Comment by dickeyxxx** [comment]
Certainly willing to work with you guys to fit your standards. A few months ago we switched from our recommended install using our pkg to homebrew and it's been a good choice I feel.

Thanks for the merge!

**Comment by dickeyxxx** [comment]
Apologies @dunn if I came across a little harsh. Statically linking the node version in our CLI is very important to me after dealing with issues from supporting various versions of ruby with our previous CLI and is a big selling point of our CLI. We are working on making our CLI into a framework for other CLIs that work similarly.

Finding a path with this that works well with homebrew is something we all want. Let's follow up on figuring out what this all should look like.

**Comment by MikeMcQuaid** [comment]
The best solution is using Homebrew's Node with the shebangs/wrapper scripts setup to ensure the right node is used every time. The "use the right node every time" logic is all stuff that's provided by Homebrew if the Heroku tool can be convinced to use the PATH or other environment variable. Let us know how best to move along this path, thanks @dickeyxxx!

**Comment by dickeyxxx** [comment]
Using PATH is a big problem for us. If a user is working on a node 0.8 Heroku app then they'll have node 0.8 in their PATH. They may be in the process of updating it to a newer version of node, but regardless the CLI should continue to function for them. We can't be expected to support every version of node before and after what we target.

Maybe for some products users want control so they can pick which node an app is using, but that certainly does not work for us.

**Comment by ilovezfs** [comment]
@dickeyxxx note that @MikeMcQuaid said "with the shebangs/wrapper scripts setup to ensure the right node is used every time."

**Comment by dickeyxxx** [comment]
So you're saying that it alters the PATH to point to the latest node? Is this documented somewhere? I feel that may be problematic for our 'heroku local' command but I can definitely take a look.

**Comment by ilovezfs** [comment]
Here's an example that uses a curl in `libexec` https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-ftp.rb#L25-L45. You'd want to point at the relevant node@6 (you use 6 right?) directories instead of `libexec`.

**Comment by dickeyxxx** [comment]
yeah that would break our `heroku local` command that users use to run their apps locally. It would also break some upcoming stuff we have planned with client-side buildpacks that would need to execute the projects locally as it would be using the CLIs version of node and not the project's

**Comment by ilovezfs** [comment]
It's now clear to me how using the node you're including in the package is somehow categorically different from using the one Homebrew provides.

**Comment by MikeMcQuaid** [comment]
This can be done without playing around with the `PATH` if need be. The proper Unix solution would be to set shebangs correctly and the alternate is just ensure the right Node is fully specified but not in the PATH.

**Comment by dickeyxxx** [comment]
yeah is there a way that I could point to the cellared latest node rather than using `/usr/local/bin/node`? I feel like the former would be liable to change (I know that's how 'n' works is by changing that file)

**Comment by MikeMcQuaid** [comment]
Yes, `/usr/local/opt/node/bin/node`.

**Comment by ilovezfs** [comment]
```
Formula["node"].opt_bin/"node"
```

**Comment by dickeyxxx** [comment]
Is there a way to enforce that the formula is compatible only with a node greater than a certain version? Right now we make heavy use of node 7.6 features. Can I enforce or check that node is installed greater than that version?

**Comment by ilovezfs** [comment]
>Is there a way to enforce that the formula is compatible only with a node greater than a certain version? 

You can specify `depends_on "node"` which will mean the latest version 8 node (currently 8.1.2).

That will always mean a fully up-to-date node formula. i.e., brew install heroku will trigger a node upgrade if the user's node is outdated (e.g. 8.1.0).

**Comment by dickeyxxx** [comment]
ah! that's great. Let me chat with the team and see what we think the right approach is here

**Comment by ilovezfs** [comment]
Excellent. Thanks @dickeyxxx

**Pull request merged**
