### PR TITLE
vault 1.1.1

### PR DESCRIPTION
**Pull request by kkirsche**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by kkirsche** [comment]
supersedes #38027

**Comment by fxcoudert** [comment]
`vault` had 4,829 installs in the last month, while `safe` had 35. If `safe` is still broken with this version, I suggest we remove it, because it's broken too often.

**Comment by javian** [comment]
This is what the github page of `safe` says
```
ATTENTION HOMEBREW USERS
If you run Homebrew on MacOS, be aware that the the Formula for safe in homebrew core is outdated, incorrect, and unmaintained. We maintain our own tap, which you are encouraged to use instead:

brew tap starkandwayne/cf
brew install starkandwayne/cf/safe
```

**Comment by fxcoudert** [comment]
@javian could live with that

**Comment by fxcoudert** [comment]
Thanks @kkirsche I've merged, we'll follow up with `safe` in a separate PR.

**Pull request closed without merging**
