### PR TITLE
openjdk: caveat and keg_only strictly for macOS

### PR DESCRIPTION
**Pull request by gromgit**
Addresses https://github.com/Homebrew/discussions/discussions/709

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting? *(Only `caveats` block was changed.)*
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting? *(Only `caveats` block was changed.)*
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by gromgit** [comment]
Note: This PR also changes the caveats output in an unexpected way on macOS.

Before:
```
==> Caveats
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

openjdk is keg-only, which means it was not symlinked into /usr/local,
because it shadows the macOS `java` wrapper.

If you need to have openjdk first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openjdk/bin:$PATH"' >> /Users/aho/.bash_profile

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/usr/local/opt/openjdk/include"
```

After:
```
==> Caveats
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

openjdk is keg-only, which means it was not symlinked into /usr/local,
because it shadows the macOS `java` wrapper.
```

Not sure what happened there.

**Comment by jonchang** [comment]
I've only seen that happen if you run `brew info` when the formula isn't installed as Homebrew wouldn't know that it had a keg-only `bin` or `include` dir.

**Comment by carlocab** [comment]
This seems to work for me, but not sure if it's the kind of change we want to add to the formula:

```diff
diff --git a/Formula/openjdk.rb b/Formula/openjdk.rb
index 88fcfcde45..5e63b3af0f 100644
--- a/Formula/openjdk.rb
+++ b/Formula/openjdk.rb
@@ -161,19 +161,25 @@ class Openjdk < Formula
   end
 
   def caveats
-    s = <<~EOS
-      For the system Java wrappers to find this JDK, symlink it with
-        sudo ln -sfn #{opt_libexec}/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
-    EOS
+    mac_caveats
+  end
 
-    if Hardware::CPU.arm?
-      s += <<~EOS
-        This is a beta version of openjdk for Apple Silicon
-        (openjdk 16 preview).
+  def mac_caveats
+    on_macos do
+      s = <<~EOS
+        For the system Java wrappers to find this JDK, symlink it with
+          sudo ln -sfn #{opt_libexec}/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
       EOS
-    end
 
-    s
+      if Hardware::CPU.arm?
+        s += <<~EOS
+          This is a beta version of openjdk for Apple Silicon
+          (openjdk 16 preview).
+        EOS
+      end
+
+      s
+    end
   end
 
   test do
```

**Comment by gromgit** [comment]
> I've only seen that happen if you run `brew info` when the formula isn't installed as Homebrew wouldn't know that it had a keg-only `bin` or `include` dir.

Oops, it was actually uninstalled by an earlier `brew autoremove`. Reinstalling it produces the full output on a `brew info`.

That said, which is the preferred syntax for this?
```
def caveats
  on_macos do
    ...
  end
end
```
or
```
on_macos do
  def caveats
    ...
  end
end
```

**Comment by jonchang** [comment]
I believe other formulae use the former, (`on_macos` inside `def caveats`). I don't think we have an audit for it or anything though.

**Comment by gromgit** [comment]
For completeness, the same change on Linuxbrew yields:
```
==> Caveats
openjdk is keg-only, which means it was not symlinked into /home/linuxbrew/.linuxbrew,
because it shadows the macOS `java` wrapper.

If you need to have openjdk first in your PATH, run:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/openjdk/bin:$PATH"' >> ~/.profile

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/openjdk/include"
```
Not sure how best to address the `keg_only` issue. Enclosing it in `on_macos` would be the obvious solution, but that would suddenly link `openjdk` on Linux installs.

**Comment by iMichka** [comment]
It's fine to link it for Linux. In 99% of the cases we link our stuff over the system provided stuff on linux.

We could use `keg_only :shadowed_by_macos`, which makes it link on linux but not on Mac.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
