### PR TITLE
ffmpeg: added openvino dependency

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
See: https://www.phoronix.com/news/FFmpeg-OpenVINO-GPU
Optimized `libavfilter` with openvino.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
`  ERROR: libopenvino not found`

**Comment by cho-m** [comment]
`ffmpeg` may need OpenVINO API 2.0 support in a release https://github.com/FFmpeg/FFmpeg/commit/e79bd1f1b158b84c4aa5083b5e2af2de8ede3b0e

Alternatively, it may need help finding `c_api/ie_c_api.h` with older OpenVINO API.

**Comment by ilya-lavrenov** [comment]
Oh, looks like we have to wait for next ffmpeg official release.

**Comment by chenrui333** [comment]
> Oh, looks like we have to wait for next ffmpeg official release.

can we maybe reopen this PR by that time? we are crowded with PRs.

**Pull request closed without merging**
