### PR TITLE
homebank 5.8.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
clang -DHAVE_CONFIG_H -I. -I..  -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/Cellar/pcre2/10.43/include -I/opt/homebrew/Cellar/xz/5.4.6/include -I/opt/homebrew/Cellar/glib/2.80.2/include/gio-unix-2.0 -I/opt/homebrew/Cellar/glib/2.80.2/include -I/opt/homebrew/Cellar/glib/2.80.2/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.80.2/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/libxcb/1.17.0/include -I/opt/homebrew/Cellar/libx11/1.8.9/include -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/opt/homebrew/Cellar/cairo/1.18.0/include -I/opt/homebrew/Cellar/cairo/1.18.0/include/cairo -I/opt/homebrew/Cellar/jpeg-turbo/3.0.3/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/libtiff/4.6.0/include -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/opt/homebrew/Cellar/fribidi/1.0.14/include/fribidi -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/harfbuzz/8.4.0/include/harfbuzz -I/opt/homebrew/Cellar/pango/1.52.2/include/pango-1.0 -I/opt/homebrew/Cellar/at-spi2-core/2.52.0/include/atk-1.0 -I/opt/homebrew/Cellar/libepoxy/1.5.10/include -I/opt/homebrew/Cellar/gtk+3/3.24.42/include/gtk-3.0 -I/opt/homebrew/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi -I/opt/homebrew/Cellar/pcre2/10.43/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/Cellar/glib/2.80.2/include -I/opt/homebrew/Cellar/glib/2.80.2/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.80.2/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/icu4c/74.2/include -I/opt/homebrew/Cellar/libnghttp2/1.61.0/include -I/opt/homebrew/Cellar/libpsl/0.21.5_1/include -I/opt/homebrew/Cellar/libsoup/3.4.4/include/libsoup-3.0 -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi -DSHARE_DIR=\""/opt/homebrew/Cellar/homebank/5.8.1/share/homebank"\" -DDATA_DIR=\""/opt/homebrew/Cellar/homebank/5.8.1/share"\"   -g -O2 -Wall -Wmissing-prototypes -Wno-deprecated-declarations -DOFX_ENABLE -c -o rep-time.o rep-time.c
rep-budget.c:259:2: error: expected expression
        gchar *name;
        ^
rep-budget.c:262:22: error: use of undeclared identifier 'name'
                        LST_BUDGET_NAME, &name,
                                          ^
rep-budget.c:265:34: error: use of undeclared identifier 'name'
                g_object_set(renderer, "text", name, NULL);
                                               ^
rep-budget.c:266:10: error: use of undeclared identifier 'name'
                g_free(name);
                       ^
4 errors generated.
```

**Comment by chenrui333** [comment]
https://bugs.launchpad.net/homebank/+bug/2067543

**Comment by Tchecker67** [comment]
Good morning,
I've been using Homebank on MacOS for a few days. The application is still in version 5.7.4 (February 2024).
What about updating to the latest version on homebrew? (5.8.1; 2024-05-26)
Thank you
@chenrui333 
@Porkepix

**Comment by chenrui333** [comment]
checking on this again.

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/176859

**Pull request closed without merging**
