### PR TITLE
sops 1.14

### PR DESCRIPTION
**Pull request by jvehent**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

This release of sops has a few minor improvements:
- Support insertion in encrypted documents via `--set`
- Support AWS KMS Encryption Contexts
- Read location of gpg binary from SOPS_GPG_EXEC env variables

### CODE REVIEW

**Comment by apjanke** [comment]
Test [failed](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7417/) on all platforms. Missing a simplejson dependency?

```
        Testing sops
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160908-39439-1rfqpsp.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/sops.rb --verbose
==> /usr/local/Cellar/sops/1.14/bin/sops -v
Traceback (most recent call last):
  File "/usr/local/Cellar/sops/1.14/libexec/bin/sops", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/sops/1.14/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/Cellar/sops/1.14/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/sops/1.14/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/sops/1.14/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/sops/1.14/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/sops/1.14/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'simplejson>=3.8' distribution was not found and is required by sops
Error: sops: failed
Failed executing: /usr/local/Cellar/sops/1.14/bin/sops -v
```

**Comment by zmwangx** [comment]
Sorry, this has been sitting for too long, I took the liberty to do it right.

**Comment by zmwangx** [comment]
Shipped in f3ee172. Thanks for bringing this up!

**Comment by jvehent** [comment]
Thanks a lot for fixing it! You guys are awesome! 👍

**Pull request closed without merging**
