### PR TITLE
terraform@0.14 0.14.10 (new formula)

### PR DESCRIPTION
**Pull request by blackstar257**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Will this version meet all requirements for versioned formula? Especially the one about guaranteed future support?

https://docs.brew.sh/Versions

**Comment by nexxai** [comment]
@SMillerDev I'm not clear on the question - this version (0.14) was the main version until TF 0.15 was released earlier this week.  I also don't know which specific rule on that link corresponds to guaranteeing future support so I don't know if anyone is willing to comment on that directly.

**Comment by SMillerDev** [comment]
> this version (0.14) was the main version until TF 0.15 was released earlier this week.

I know, that's why we need to know if that version will still be supported now that 0.15 is out.

**Comment by nexxai** [comment]
Aside from the fact that they still offer downloads of the v0.14 binary from their own site, what would be acceptable ways from the homebrew team's perspective to confirm this?

**Comment by SMillerDev** [comment]
A web page from terraform listing their supported versions that includes 0.14.

**Comment by nexxai** [comment]
@SMillerDev All I've been given from Hashicorp is their own list of Terraform releases which are all downloadable: https://releases.hashicorp.com/terraform/

**Comment by ph-l** [comment]
Terraform 0.14 was released on 2 Dec 2020 and so should be supported till 2022 based on their support policy linked below.

https://support.hashicorp.com/hc/en-us/articles/360021185113-Support-Period-and-End-of-Life-EOL-Policy

> Support Period
>
> HashiCorp will support Generally Available (GA) releases of active products for up to two (2) years. Eligible code-fixes and hot-fixes are provided via a new minor release (Z) on top of the latest “major release” branch, for up to two (2) releases from the most current major release. A major release is identified by a change in the first (X) or second (Y) digit in the following versioning nomenclature: Version X.Y.Z.
> 
> ** Terraform Enterprise follows a 2 year Advisory support policy.
> 
> As a best practice, HashiCorp expects customers to stay current within two (2) releases from the latest major release in order to receive optimal support. Release updates for Customers are provided regularly on HashiCorp product pages for each HashiCorp product.
> 
>  
> End-of-Life 
> 
> HashiCorp’s end-of-life policy provides that HashiCorp will provide customers at least twelve (12) months’ prior written notice before discontinuing any product (“End of Life Period”). If a customer’s subscription term ends before the End of Life Period has elapsed, the customer may renew the subscription to the discontinued software until the End of Life Period expires. If the End of Life Period expires prior to the end of a customer’s subscription term, HashiCorp will provide a pro-rated refund of the pre-paid fees for the terminated software, and for the applicable support services subscription, for the remainder of the subscription term. After the End of Life Period expires, HashiCorp will no longer be obligated to provide support services for the terminated software.

**Comment by nexxai** [comment]
@SMillerDev Does @ph-l 's document satisfy the requirements to have it added?

**Comment by SMillerDev** [comment]
I can't actually access it, I have to log in first so that makes me think it's only the enterprise policy.

**Comment by nexxai** [comment]
Ok then I'm confused at what the homebrew team expects for OSS in terms of "support"?  They have an active [Github repo](https://github.com/hashicorp/terraform) where issues can be raised regarding old versions (in the bug report issue template, they suggest - but do not require - running the latest version), they offer all old versions on their own company-hosted site, but because they don't have an entire support team to address tickets for free software, this is the basis for them possibly being denied versioned-formula status?

**Comment by SMillerDev** [comment]
> they offer all old versions on their own company-hosted site

As far as I know Microsoft still allows you to download windows XP images. Doesn't mean they'll be supporting it.

**Comment by blackstar257** [comment]
Im sorry im confused with all the interrogation with whether to support versioned terraform formulas. Homebrew already has terraform@0.11 terraform@0.12 terraform@0.13. What makes this one different? @SMillerDev

**Comment by SMillerDev** [comment]
Previous versions might have had exceptions like "Homebrew Formula depend on it" each review is done independently of prior work because our insights and rules change.

**Comment by blackstar257** [comment]
Okay well im not sure what exactly your looking for in regards to open source software support? As someone mentioned earlier anyone can post issues to the github repo if they run into an issue. The biggest issue i have is right now the main terraform formula has been updated to a new major version from 0.14 to 0.15 which contains breaking changes. 

https://github.com/hashicorp/terraform/blob/v0.15.0/CHANGELOG.md#0150-april-14-2021

Those of us that leverage homebrew to install terraform now don't have an option to install version 0.14.

If the given information doesn't meet your new requirement @SMillerDev please close this PR. I will take a different direction.

**Comment by SMillerDev** [comment]
> Okay well im not sure what exactly your looking for in regards to open source software support? 

Ideally something like this: https://www.php.net/supported-versions.php a public overview of supported versions.

> Those of us that leverage homebrew to install terraform now don't have an option to install version 0.14.

You can always keep it in a tap until this review is done (whatever the outcome is)

> If the given information doesn't meet your new requirement @SMillerDev please close this PR. I will take a different direction.

Maybe someone can ping some terraform devs to give the final information on what they support? I don't _want_ to close this. But I also don't want to provide support when upstream doesn't.

**Comment by blackstar257** [comment]
For those that come here looking for terraform 0.14 until its approved for easy use like the other versions i have created my own tap. Feel free to use or fork.

`brew tap blackstar257/tap`
`brew install terraform@0.14`
https://github.com/blackstar257/homebrew-tap

**Comment by blackstar257** [comment]
gonna close this due to this. Looks like you were very familiar with this post, not sure why it wasn't mentioned. 

https://discourse.brew.sh/t/maintenance-of-formulas-by-vendor/7649

**Comment by chenrui333** [comment]
With the newer update on the 0.14 release line, I am gonna push this legacy formula update again. Ideally we should support 0.14 release (upstream is also actively maintaining it) :)

**Pull request closed without merging**
