### PR TITLE
ldc 1.0.0-beta2 (devel)

### PR DESCRIPTION
**Pull request by John-Colvin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Build is failing: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2005/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install___devel_ldc/

**Comment by John-Colvin** [comment]
I think I've found the problem (the build system not handling the `D_COMPILER` relative path properly), just testing the workaround now

**Comment by John-Colvin** [comment]
fixed :)

**Comment by mikemcquaid** [comment]
Thanks again @John-Colvin!

**Pull request merged**
