### PR TITLE
generate-json-schema 2.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
The usage of `https://registry.npmjs.org/*` for `npm` stuff is intended, FWIW. Various things are packaged/optimised in the `npm` tarballs that aren't in the GitHub ones.

**Comment by ilovezfs** [comment]
@DomT4 yeah I know. The problem is that upstream seems not to be updating the registry with the latest: https://github.com/nijikokun/generate-schema/releases

It's now two ahead of the registry.

**Comment by DomT4** [comment]
That's.. unusual. Are they definitely stable releases & not development tags?

**Comment by ilovezfs** [comment]
They're not definitely anything, but it's been since 14 Mar 2015 so it's certainly time for a check-in.

**Comment by ilovezfs** [comment]
Filed upstream issue requesting clarification: https://github.com/nijikokun/generate-schema/issues/13

**Comment by DomT4** [comment]
Thanks ILZ!

**Pull request closed without merging**
