### PR TITLE
Cromwell 36.1

### PR DESCRIPTION
**Pull request by cjllanwarne**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by mistydemeo — COMMENTED** [review]
Is this a downgrade? We have version 37 now, which is numerically higher than 36.1.

**Comment by cjllanwarne** [comment]
Hey @mistydemeo - yes, it's a temporary revert while some regressions are worked out in version 37.

If going backwards messes with your numbering system, is there any way of revoking 37 as a working version until we can publish a 37.1?

**Comment by cjllanwarne** [comment]
(more details on the releases page: https://github.com/broadinstitute/cromwell/releases)

**Comment by mistydemeo** [comment]
We may need to use a `version_scheme` to force Homebrew to recognize 36.1 as a newer release. See [the docs](https://www.rubydoc.info/github/Homebrew/brew/master/Formula#version_scheme%3D-class_method) for information.

**Comment by cjllanwarne** [comment]
OK, I'll have a look into that - thanks!

**Comment by mistydemeo** [comment]
Ping - just wanted to check in on this again. Do you also have an ETA for the fixed 37.x release?

**Comment by cjllanwarne** [comment]
@mistydemeo I'm going to close this PR - a version 38 is being released either today (or latest) tomorrow which will make this hotfix redundant.

Thanks again.

**Pull request closed without merging**
