### PR TITLE
gollum 0.4.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like you may need to dig out the trusty `prefix.install_metafiles` here.

**Comment by ilovezfs** [comment]
That hideous beast, you mean.

**Comment by DomT4** [comment]
Yeah, that's the one! 😉

**Comment by ilovezfs** [comment]
@DomT4 perhaps we should use this pattern:
```
  def install
    ENV["GOPATH"] = buildpath
    ln_s "vendor", "src"
    (buildpath/"src/github.com/trivago").mkpath
    ln_s buildpath, "src/github.com/trivago/gollum"
    system "go", "build", "-o", bin/"gollum"
  end
```
Works fine.

**Comment by ilovezfs** [comment]
I suspect that may work in a lot of these... `symlink_madness_go_install_with_vendor` DSL, much? CC @tdsmith

**Comment by tdsmith** [comment]
I don't understand go packaging well enough to have opinions about it but it does feel like there are opportunities here!

**Comment by DomT4** [comment]
I'm semi-loathe to hack around with the `ln_s "vendor", "src"` syntax, but I agree we could probably wrap this in DSL `go_install_vendor` or something which automatically does all of this sort of thing:
```ruby
    ENV["GOPATH"] = buildpath
    glidepath = buildpath/"src/github.com/Masterminds/glide"
    glidepath.install buildpath.children

    cd glidepath do
      system "go", "build", "-o", "glide", "-ldflags", "-X main.version=#{version}"
      bin.install "glide"
      prefix.install_metafiles
    end
```

**Comment by ilovezfs** [comment]
I think they're ultimately equivalent because the src -> vendor symlink is pretty trivial given the definitions, but I'd be reluctant only because it will confuse contributors, not because i'm concerned about it being "hacking of the build system" or something.

But yes, I'm 1000% behind a DSL for these that hides this boierplate rubbish.

**Comment by DomT4** [comment]
I'll add it to my post-GPG pile, unless anyone wants to beat me to it, in which case by all means please very much do.

**Comment by ilovezfs** [comment]
I volunteer Tim.

**Pull request closed without merging**
