### PR TITLE
folderify 2.3.0

### PR DESCRIPTION
**Pull request by lgarron**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
> I'm not aware of a `seticon` build for Apple Silicon, and I'm not sure that's even possible.

Why is it not possible? Is `seticon` not open source?

> Is there a way to allow an exception while for `seticon` while Rosetta 2 still works?

We can do `depends_on arch: :x86_64` to depend on a Rosetta 2 installation of Homebrew (in `/usr/local`) on ARM. For installs in `/opt/homebrew`, we don't want to assume a user has Rosetta 2 installed.

**Comment by lgarron** [comment]
> Why is it not possible? Is `seticon` not open source?

It is, but it's "here be dragons": https://github.com/sveinbjornt/osxiconutils

> NB: No longer maintained by me. Fork and make it better.
> ...
> Copyright © 2003-2018 Sveinbjorn Thordarson.

I include the `seticon` binary because it's been working for over 10 years and I try to keep backwards compat for macOS (OS X, in fact) and Python as much as possible.

The main alternatives I know are based on `Rez`, but that requires a XCode command line tool installation and only works for folders.

> We can do `depends_on arch: :x86_64` to depend on a Rosetta 2 installation of Homebrew (in `/usr/local`) on ARM. For installs in `/opt/homebrew`, we don't want to assume a user has Rosetta 2 installed.

I think unless someone provides a fully backwards-compatible pull request to `folderify`, I would prefer this option. It's a little heavy, but it works (similar to the version of Python installed for `folderify`, when the system version should already work in theory).

Is there an example I can copy for this?

**Comment by lgarron** [comment]
> I think unless someone provides a fully backwards-compatible pull request to `folderify`, I would prefer this option. It's a little heavy, but it works (similar to the version of Python installed for `folderify`, when the system version should already work in theory).
> 
> Is there an example I can copy for this?

Still could use some advice on how to do this!

**Comment by carlocab** [comment]
Oops, sorry. I have way too many GitHub notifications, so I missed this. You can do 
```
grep -Rl 'depends_on arch:' "$(brew --repository homebrew/core)/Formula
```
for many examples.

I did look at the build script for `seticon`, though, and it doesn't seem too involved. We should try to build this from source, especially since we're [not supposed to be shipping pre-built binaries](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae) in formulae anyway.

Or, alternatively, just get rid of `seticon`, since it's quite unlikely anyone who has a Homebrew Python3 installed doesn't also have the CLT installed, because of:

https://github.com/Homebrew/homebrew-core/blob/359cb0857099cdfa8b9ce8f421c680c9829dfe81/Formula/python%403.10.rb#L23-L25

**Comment by carlocab** [comment]
> `folderify` has included binaries for over a decade, and no one's gotten hurt so far! 😜

Until now! Trying to run an x86-64 binary from the command line on ARM macOS sometimes leads to errors that can be quite confusing for the inexperienced. (I say sometimes because you’re also sometimes prompted to install Rosetta, but I haven’t worked out yet how that gets triggered. I think it might need to be built into the binary you’re executing rather than something the OS does.)

> But that doesn't sound _too_ crazy. Homebrew can ignore the binary and I'm okay with shelling out to an existing `seticon` when available. Who would maintain it, though? `folderify` is mainly a Python project, and I would not like to introduce a binary build step.

We can do it here in the formula. I’ll have a closer look at it and push the needed changes. Give me a bit, though, as I’m a little bit swamped at the moment.

**Review by carlocab — APPROVED** [review]
ARM build is green. This should be ready when the other CI nodes catch up. (We're at reduced CI capacity to bottle formulae for Monterey.)

**Pull request closed without merging**
