### PR TITLE
kafka 0.10.0.1

### PR DESCRIPTION
**Pull request by slothspot**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit <formula>` (after doing `brew install <formula>`)?

---

Updated kafka to 0.10.0.1, switched to binary Scala 2.11 based official build due to conflict with Gradle 3.0 (see #3962)

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Makes sense to me 👍

**Comment by apjanke** [comment]
Looks like the test bot runs are timing out at the test stage.

```
==> brew bottle --verbose --json kafka
==> brew bottle --merge --write --no-commit ./kafka-0.10.0.1.mavericks.bottle.json
==> brew uninstall --force kafka
==> brew install ./kafka-0.10.0.1.mavericks.bottle.1.tar.gz
==> brew test kafka --verbose
Build timed out (after 60 minutes). Marking the build as aborted.
Build was aborted
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Archiving artifacts
```

**Comment by slothspot** [comment]
@apjanke I'll investigate this

**Comment by slothspot** [comment]
@MikeMcQuaid , @apjanke how timeout for tests is defined on build server? On my MacBook Pro (early 2013) it takes around ~2 min 10 sec to pass tests according to time command output without any failures.

**Comment by MikeMcQuaid** [comment]
@slothspot The build gets killed after 60 minutes which means something was hanging here.

**Comment by slothspot** [comment]
@MikeMcQuaid from what I see here: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6533/ build failed for 3 platforms within 4 minutes with timeout, so I don't understand how to approach this problem

**Comment by MikeMcQuaid** [comment]
That's a different error which gives you the error message: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6533/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_kafka/

**Comment by apjanke** [comment]
The test passes on my local El Cap machine too. Possibly a test bot configuration issue or a sandbox problem.

Might be nice to see the log output for that `kafka-server-start` call, along with the sandbox log. I don't think we have other tests that are explicitly capturing logs during the test, but maybe this is a good use case for it.

```
     exec "#{bin}/kafka-server-start #{testpath}/kafka/server.properties >/dev/null
```

That `exec`'ed processes doesn't have its output captured by default, even if you don't `>/dev/null` it. Let's send that to a log. Instead of sending it to `>/dev/null`, redirect it to `>#{logs}/test.kafka-server-start.log 2>&1`.

```
         exec "#{bin}/kafka-server-start #{testpath}/kafka/server.properties >#{logs}/test.kafka-server-start.log 2>&1"
```

Similarly, send the `zookeeper-server-start` output to `#{logs}/test.zookeeper-server-start.log 2>&1`.

These log files won't be available as part of the build result web page, but one of the maintainers will be able to log in to the server and extract them to a gist for you to review.

**Comment by slothspot** [comment]
@apjanke Done

**Comment by apjanke** [comment]
Aaaand it passed this time. Going to chalk this up to a transient problem with the test-bot machines.

Merged. Thank you for your contribution to Homebrew!

**Comment by slothspot** [comment]
@apjanke , @MikeMcQuaid Thanks for your support!

**Pull request closed without merging**
