### PR TITLE
heroku-toolbelt 3.42.50

### PR DESCRIPTION
**Pull request by jdx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by DomT4** [comment]
@Homebrew/maintainers Any idea why this merged as a blank commit? Not sure what's going on here. https://github.com/Homebrew/homebrew-core/commit/7debfcb39ab0ed0ca86de0e39d4d20773bbc022b

**Comment by dickeyxxx** [comment]
looks like the code is good though https://github.com/Homebrew/homebrew-core/commit/751d202bbd5c34af63d00fe428bb1b9d8e7c7944

**Comment by DomT4** [comment]
Oh, looks like this was merged 12 days ago by @apjanke in https://github.com/Homebrew/homebrew-core/commit/751d202bbd5c34af63d00fe428bb1b9d8e7c7944, and if your branch is based off an older point than that it'd make sense the diff would show here but the merged commit would be empty.

Maybe you accidentally submitted the same PR twice or something? Hmm.

**Comment by apjanke** [comment]
Looks like a double-pull. I already merged it a couple days back using `brew pull`.

screen shot 2016-04-21 at 2 53 46 pm

Looks like the auto-close didn't work. Maybe the comment was lost during manual squashing? I don't recall this specific merge. Or it could have been a bug in an in-progress `brew pull` update that I'm working on and using locally.

**Comment by dickeyxxx** [comment]
couldn't be the same commit, I only pushed that version of the CLI out today, but yeah, it could be something with an older commit somehow

**Comment by dickeyxxx** [comment]
ahhhh

**Comment by dickeyxxx** [comment]
because I used the same branch, sorry for the double post!

**Comment by apjanke** [comment]
Ah, that explains it. Thanks, and no worries.

**Comment by DomT4** [comment]
Ah, that makes sense. That messed with my head temporarily 😄. These things happen, heh.

**Comment by DomT4** [comment]
@apjanke Can you `git rebase -i HEAD~10` successfully for example locally after this being merged? I am having some major problems. That command gets me the last 100 or so commits rather than 10 with this message:

```
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
interactive rebase in progress; onto 936c934
Last commands done (6 commands done):
   pick e802027 moreutils: update 0.58 bottle.
   pick cd8a36c moreutils 0.58
Next commands to do (128 remaining commands):
   pick a06fc70 moreutils: update 0.58 bottle.
   pick 4a5eb25 httperf: fix head url (https -> http)
You are currently rebasing branch 'master' on '936c934'.

nothing to commit, working directory clean
Could not apply cd8a36c87037b90d65bb4174459b6c5b8d149ec6... moreutils 0.58
```

I'm working from a clean git repo as well. Wiped mine locally in case that was the issue.

**Comment by DomT4** [comment]
Oh, maybe https://github.com/Homebrew/homebrew-core/commit/dbf81ea4ab3c5591d382b5380c303e60fb094b99 is the problem? When the rebase fails with that message and I run `git log` I see this:

```
commit e802027e344362ab2f810cb5460e63dd66e743c5
Author: BrewTestBot <brew-test-bot@googlegroups.com>
Date:   Mon Apr 18 17:03:04 2016 +0100

    moreutils: update 0.58 bottle.

commit cc95d3ee2854ce150ce1452506507c43e9251993
Author: Ross Penman <ross@pen.mn>
Date:   Mon Apr 18 16:44:06 2016 +0100

    moreutils 0.58

    Closes #422.

    Signed-off-by: Andrew Janke <andrew@apjanke.net>
```

Whereas GitHub shows that I merged that [PR](https://github.com/Homebrew/homebrew-core/pull/422) in [this commit](https://github.com/Homebrew/homebrew-core/commit/cd8a36c87037b90d65bb4174459b6c5b8d149ec6).

**Comment by DomT4** [comment]
I think we've managed to create a dual set of histories here with the merge commit, particularly in overwriting that `moreutils` push. CC @mikemcquaid for the morning for analysis and help.

I can kind of fix it locally by doing:
```
git rebase -i HEAD~<number>
<make literally any change>
git commit --allow-empty
<save commit>
git rebase --continue
git commit --allow-empty
<save commit>
git rebase --continue
...
Rebasing (40/135)
....
```
That gets me back to being able to do interactive rebases successfully, seemingly by overwriting my `moreutils` commits with Andrew's.

**Comment by UniqMartin** [comment]
You have both pulled this PR, thereby created two separate branches that were then merged again in dbf81ea4ab3c5591d382b5380c303e60fb094b99. e275a242cb2f063032f52b94221d58e8198ee083 is the parent of those two diverging branches …

Just have a look at the history with `git log --graph --decorate --date-order --oneline origin/master` or use some graphical tool. :wink:

**Comment by DomT4** [comment]
It wasn't necessarily that we've managed to create this situation that bothered me, I was more wondering what the sane way to get out of it is so I can rebase things again without wild failures 😄.

**Comment by UniqMartin** [comment]
Sorry, I'm not sure what the issue with the rebase is. It should work flawlessly across this temporary split of histories and for me it always has thus far. But I'm not sure how complicated your local setup is and what kinds of histories you are rebasing …

**Comment by DomT4** [comment]
I wiped both `/usr/local/.git` and `/usr/local/Library/Taps/homebrew/homebrew-core/.git` and tried with fresh git histories initially. That didn't resolve the problem. Then tried with a separate Homebrew installation elsewhere on the system, which didn't resolve the problem. Then tried both those steps with my global `.gitconfig` temporarily renamed, no dice. Then tried a completely fresh VM with no standard git configuration and ran `git rebase -i HEAD~10` there and the problem remains.

**Comment by UniqMartin** [comment]
Re `git rebase -i HEAD~10`: But why are you even interactively rebasing the last 10 commits if those are already in `origin/master` not your local yet unpushed commits? If you're going 10 commits back (following the left line of ancestry because you haven't specified otherwise) you are currently moving across both the merge and split point and thus also get the many commits from the side branch.

I'm assuming what you really want to do is amend a few commits from a `brew pull`? If so:

```shell
# Start off with a clean repository with checked out master:
brew pull <whatever>

# To amend the commits pulled in by that `brew pull`:
git rebase -i origin/master # or @{u}

# Check that everything is as it should be (commits not yet on remote):
git log -p @{u}..

# Push to official repository:
git push

# Cannot fast-forward (because someone else pushed in the mean time):
git rebase
git push
```

Does any of that help or make sense? I hope I haven't completely missed the point.

**Comment by DomT4** [comment]
> Re git rebase -i HEAD~10: But why are you even interactively rebasing the last 10 commits if those are already in origin/master not your local yet unpushed commits?

It's my default number. I have an alias that I use _(because I'm lazy)_ and I set it to a relatively high number so it works in situations even where a contributor has pushed a small hoard of changes without squashing. You'd be amazed how frequently 10 isn't high enough, despite that.

Using a much lower number does work, but my concern was more "Is this likely to cause future issues if we leave it as-is or people checkout a specific earlier commit".

**Comment by UniqMartin** [comment]
> It's my default number.

That's why I suggested to use `@{u}` (short for remote branch of this branch) or just `origin/master`. This is both shorter and will always be the correct number, no matter if it's 2 commits or 20. You're using the `HEAD~10` sledgehammer, so don't complain it's creating a bit of damage left and right. :wink:

> "Is this likely to cause future issues if we leave it as-is or people checkout a specific earlier commit"

I don't think it's going to create issues for other people, Git can handle this situation just fine. It's just that interactively rebasing across multiple branches isn't usually what you want to do (especially if you cannot change that history anyway because it already has been pushed). I think it's good practice to limit rebasing/amending to what hasn't been pushed yet and lives in a single branch.

**Comment by DomT4** [comment]
> so don't complain it's creating a bit of damage left and right.

It's worked well for me for over 6 months now. This is the first problem. I learned to trust that my sledgehammer wouldn't betray me, until now 😜.

> I don't think it's going to create issues for other people, Git can handle this situation just fine.

Cool. That's what I was worried about, primarily, that if I was seeing this sort of thing other contributors were going to run into it. The crossover in history is why I loathe merge commits with a passion and am generally thankful GitHub made it possible to ban the from-web ones at least.

**Comment by mikemcquaid** [comment]
@DomT4 👍 to using `git rebase -i origin/master`; maybe even alias it (like I do) to `git i`.

**Pull request merged**
