### PR TITLE
salt 3000

### PR DESCRIPTION
**Pull request by dafyddj**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is it actually officially released now?

**Comment by dafyddj** [comment]
Yes, [released](https://www.saltstack.com/blog/future-infrastructure-automation/) a few days ago.

**Comment by SMillerDev** [comment]
Cool, the repo changelog still marked neon as "unreleased"

**Comment by SMillerDev** [comment]
Thanks @dafyddj! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
