### PR TITLE
maven 3.9.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Error:  Cannot invoke "java.util.List.stream()" because the return value of "org.apache.maven.project.MavenProject.getCollectedProjects()" is null
  Error:  
  Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
  Error:  Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by jhaber** [comment]
Thanks for updating the formula 😄 Maven 3.9.0 includes the long-awaited parallel pom.xml downloads so I'm sure lots of people are eager to use it

**Review by iMichka — APPROVED** [review]

**Comment by iemejia** [comment]
It also includes support for https://maven.apache.org/extensions/maven-build-cache-extension/ so definitely great to have it available

**Comment by iMichka** [comment]
You mean maven 3.9.0? Yes, since 1 week now.

**Comment by imranparsa** [comment]
I'm using maven version 3.9.0 still getting the same problem? How to apply the fix?

**Comment by jhaber** [comment]
What problem?

**Comment by imranparsa** [comment]
Same error 

Error:  Cannot invoke "java.util.List.stream()" because the return value of "org.apache.maven.project.MavenProject.getCollectedProjects()" is null
  Error:  
  Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
  Error:  Re-run Maven using the -X switch to enable full debug logging.

**Comment by jhaber** [comment]
Are you using pax construct? If you rerun maven with `-e` flag and put the full stacktrace in a [gist](https://gist.github.com/) that might help to narrow things down

**Pull request closed without merging**
