### PR TITLE
Fix/secure URLs

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please stop merging PRs that don't pass CI. And generally please stop merging PRs before other maintainers can look at them.

**Comment by vszakats** [comment]
Can you remove me from the list of maintainers?

**Comment by vszakats** [comment]
Okay, I've left the Homebrew project, so this won't be a problem any longer.

**Comment by MikeMcQuaid** [comment]
Reverting in https://github.com/Homebrew/homebrew-core/pull/63676

**Pull request merged**
