### PR TITLE
ponyc 0.38.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Related: https://github.com/Homebrew/homebrew-core/issues/66450

**Comment by chenrui333** [comment]
looks interesting, specially considering their 0.38.2 release is to fix big sur linking issue.

**Comment by carlocab** [comment]
That is quite weird. Actually, I just tried testing the old version of `ponyc` locally. I can make the test succeed in the shell if I add the flag

    --linker="ld -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"

to the test. It fails when I add this to the formula and run `brew test` though.

Ref. https://github.com/ponylang/ponyc/issues/3684

**Comment by chenrui333** [comment]
yeah, I saw that issue, I thought the change was supposed to be released part of 0.38.2 :(

**Comment by carlocab** [comment]
>I thought the change was supposed to be released part of 0.38.2

Me too. Though maybe I'm thinking the test failure may have more to do with the `brew test` environment since I think the important change from 0.38.2 is that they now add those linker flags by default.

**Comment by chenrui333** [comment]
archive pony-stable, #68201

**Comment by chenrui333** [comment]
@carlocab I think we are good with the merge(only pony-stable test failure on 11.0, and it can be deprecated as the upstream no longer support it), what do you think?

**Review by carlocab — APPROVED** [review]
Technically deprecated formulae should still be working... but not sure there’s much point trying to fix `pony-stable` now, so LGTM

**Comment by chenrui333** [comment]
Thanks! merging the PR. :)

**Pull request closed without merging**
