### PR TITLE
triage: add labels for boost, icu4c, ffmpeg dependents

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

We often struggle with merging boost and icu4c updates due to merge
conflicts. The same occasionally happens with ffmpeg updates.

Let's make it easier to identify PRs that could potentially cause merge
conflicts with appropriate labels.

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Would it be possible to make these work as "do not merge" if any of those dependents are in an approved review?

**Comment by carlocab** [comment]
> Would it be possible to make these work as "do not merge" if any of those dependents are in an approved review?

All the time? Or only when a relevant PR is open? Why wait until an approved review?

**Comment by SMillerDev** [comment]
Only if there is for example: an icu4c PR that has been approved.

**Comment by carlocab** [comment]
I don't see why it's not possible, but implementing it might take a bit of work.

**Pull request merged**
