### PR TITLE
ffmpeg: enable librubberband and libtesseract

### PR DESCRIPTION
**Pull request by retokromer**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As suggested in https://github.com/Homebrew/homebrew-core/pull/36665#issuecomment-460528279 cc @mistydemeo

### CODE REVIEW

**Comment by javian** [comment]
Thanks @retokromer - about to merge this now.

**Comment by MikeMcQuaid** [comment]
I'm pretty sure this doesn't work as it doesn't add `rubberband` or `tesseract` as dependencies.

**Comment by javian** [comment]
That’s what I thought as well but discovered that the deps had been added in a previous commit .

**Comment by MikeMcQuaid** [comment]
@javian Gotcha, thanks.

**Comment by retokromer** [comment]
The current version works fine on our end. However, if an error is generated, then please let me know, possibly with the full details. Thanks!

**Pull request closed without merging**
