### PR TITLE
pgcli: fix out-of-date cli-helpers dependency

### PR DESCRIPTION
**Pull request by tsroten**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This pull request updates the CLI Helpers dependency version used in the pgcli formula, which fixes a bug - https://github.com/dbcli/pgcli/issues/791

### CODE REVIEW

**Comment by ilovezfs** [comment]
Probably should bump the revision, too.

**Comment by tsroten** [comment]
Hi @ilovezfs! Good idea - working on it.

**Comment by ilovezfs** [comment]
1.8.1 is out if you want to dump the revision and make this a version bump pr instead :)

**Comment by ilovezfs** [comment]
Thanks @tsroten!

**Comment by tsroten** [comment]
@ilovezfs Thanks for updating the pgcli version!

**Comment by ilovezfs** [comment]
@tsroten no problem :)

**Pull request closed without merging**
