### PR TITLE
Fluent bit 1.3.2

### PR DESCRIPTION
**Pull request by zfouts**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Had one open for 1.2.2 but was failing on Catalina: https://github.com/Homebrew/homebrew-core/pull/46780

### CODE REVIEW

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
Catalina only:

```
BUILDVM   lj_bcdef.h
CC        lj_dispatch.o
/bin/sh ./libtool --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/libbacktrace-5a99ff7f    -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o state.lo /tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/libbacktrace-5a99ff7f/state.c
[ 28%] Building C object lib/mbedtls-2.16.3/library/CMakeFiles/mbedx509.dir/x509_create.c.o
cd /tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/mbedtls-2.16.3/library && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DFLB_HAVE_PARSER -DFLB_HAVE_RECORD_ACCESSOR -DFLB_HAVE_STREAM_PROCESSOR -DFLB_HAVE_TLS -DJSMN_PARENT_LINKS -DJSMN_STRICT -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/include -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/flb_libco -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/rbtree -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/msgpack-3.2.0/include -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/chunkio/include -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/LuaJIT-2.1.0-beta3/src -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/monkey/include -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/mbedtls-2.16.3/include -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/sqlite-amalgamation-3240000 -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/mpack-amalgamation-1.0/src -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/miniz -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/onigmo  -Wall -D__FILENAME__='"/privatelib/mbedtls-2.16.3/library/x509_create.c"' -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -fPIC   -o CMakeFiles/mbedx509.dir/x509_create.c.o   -c /tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/mbedtls-2.16.3/library/x509_create.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/libbacktrace-5a99ff7f -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c /tmp/fluent-bit-20191122-16776-1npluhi/fluent-bit-1.3.2/lib/libbacktrace-5a99ff7f/state.c -o state.o
BUILDVM   lj_folddef.h
make[4]: *** [lj_folddef.h] Segmentation fault: 11
make[4]: *** Deleting file `lj_folddef.h'
make[3]: *** [default] Error 2
make[2]: *** [luajit-prefix/src/luajit-stamp/luajit-build] Error 2
make[1]: *** [CMakeFiles/luajit.dir/all] Error 2
```

There's a lot going on at once. Not sure how kindly this project copes with parallelism.

With that said, does it strictly require the bundled 2.1 beta LuaJIT? Or will Homebrew's 2.0.5 build be sufficient?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by zfouts** [comment]
> With that said, does it strictly require the bundled 2.1 beta LuaJIT? Or will Homebrew's 2.0.5 build be sufficient?

I believe it does, but I will check with @edsiper the developer/maintainer of fluentbit.

**Pull request closed without merging**
