### PR TITLE
dnscrypt-proxy 1.9.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by justinmayer** [comment]
@ilovezfs: Have you considered moving DNSCrypt settings from plist CLI flags to the configuration file introduced in v1.8?

As in stands now, all settings changes in the plist (for example, resolver) are overwritten on each `brew upgrade`, which seems rather suboptimal. Moving the current defaults to an example file at `/use/local/etc/dnscrypt-proxy-example.conf` and switching the plist to call `/use/local/etc/dnscrypt-proxy.conf` seems like a more resilient approach. Doing so would also be more consistent with the behavior of other Homebrew formulae.

What do you think?

**Comment by ilovezfs** [comment]
@justinmayer sounds reasonable. Do you mind opening a PR? I can close this one if you'd like.

**Comment by nijikon** [comment]
I'm merging this.

**Comment by justinmayer** [comment]
I attempted to switch DNSCrypt's formula to use a configuration file, but I'm a bit stumped as to how to accomplish that given `brew`'s auto-linking behavior. Created an issue in case anyone has any suggestions: https://github.com/Homebrew/homebrew-core/issues/8711

**Pull request closed without merging**
