### PR TITLE
vifm 0.10

### PR DESCRIPTION
**Pull request by dmlemos**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Follow up of #35841

Please let me know if there is anything else that needs changing.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Where is it documented that `vifm` now only builds on High Sierra and later?

**Comment by dmlemos** [comment]
@fxcoudert I am not able to test on Sierra, but this is based on previous closed PRs https://github.com/Homebrew/homebrew-core/pull/34161#issuecomment-439473505

**Comment by fxcoudert** [comment]
Please remove `depends_on :macos => :high_sierra` unless upstream confirms the software it not supported on Sierra.

**Comment by fxcoudert** [comment]
We support macOS versions supported by Apple: Sierra, High Sierra, and Mojave. Unless they are officially unsupported by the software upstream.

> what can be done to avoid another rejected merge for this formula

Someone needs to fix the build for Sierra.

**Comment by dmlemos** [comment]
@fxcoudert Please check the new changes

**Comment by dmlemos** [comment]
Any chance to get this merged soon?

**Comment by xaizek** [comment]
@fxcoudert, ping. This is ready to merge for weeks now. Please take a look.

**Pull request closed without merging**
