### PR TITLE
bazel 0.4.0

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Asking for help here - http://discourse.brew.sh/t/audit-is-broken-on-fully-scope-test-system-calls-no-clue-how-to-fix/365

**Comment by kevmoo** [comment]
@MikeMcQuaid - hitting your new audit RE "fully scoped test system calls" – zero clue how to fix.

Help?

**Comment by MikeMcQuaid** [comment]
@kevmoo The check wasn't strict enough; improved in https://github.com/Homebrew/brew/pull/1424  in https://github.com/Homebrew/brew/pull/1424/commits/f35a86ff70fbc89d03811c821689c7e6c0536899, thanks.

**Comment by kevmoo** [comment]
@MikeMcQuaid Uh...so what should I do w/ my request? Wait? Fix something? Still confused. 😕

**Comment by MikeMcQuaid** [comment]
Ignore the failure, we can merge regardless.

**Comment by kevmoo** [comment]
> Ignore the failure, we can merge regardless.

Cool, @MikeMcQuaid – uh, should I just hangout, then? Is there a magic button someone needs to push?

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
