### PR TITLE
ios-sim 3.2.0

### PR DESCRIPTION
**Pull request by jfirebaugh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Note that I'm purposefully _not_ upgrading to the 5.x series for ios-sim. In 5.x, ios-sim was converted to a node module and the functionality is different enough that it's virtually a new package entirely. People who wish to use 5.x are better off installing with npm.

**Comment by DomT4** [comment]
Perhaps we should note that as a `caveat` or something. People typically expect the latest from Homebrew.

**Comment by mikemcquaid** [comment]
> In 5.x, ios-sim was converted to a node module and the functionality is different enough that it's virtually a new package entirely. People who wish to use 5.x are better off installing with npm.

I'd probably rather we just installed the `npm` version in this formula rather than intentionally package an old, unmaintained version.

**Comment by jfirebaugh** [comment]
Okay. I need 3.x specifically and am not interested in packaging the most recent version, so I'll create a personal tap.

**Pull request closed without merging**
