### PR TITLE
Updated mockserver to 5.5.0 and added previous versions for mockserver 5.4 and 5.3

### PR DESCRIPTION
**Pull request by jamesdbloom**
Updated mockserver to 5.5.0 and added previous versions for mockserver 5.4 and 5.3

- [ Yes] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ Yes] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ Yes] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ Yes] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jamesdbloom** [comment]
the build appears to be still running after two days, can someone please take a look at this

**Comment by SMillerDev** [comment]
Are 5.3 and 5.4 actively maintained by upstream and needed by homebrew? Otherwise it's probably better to leave those out.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by zbeekman** [comment]
@jamesdbloom (CC: @SMillerDev) can someone please explain to me the rationale/benefit/need/use case for introducing these versioned formulae?

The jenkins jobs keep hanging which is clogging up our build/ci queue. 

@jamesdbloom It looks like this PR includes a version bump. Can you please do the following:

- Submit 1 PR with the version bump for mockserver
  - This obviously should upgraded
- Submit a 2nd PR with the introduction of the versioned formulae
  - We should further discuss the merits of adding these to Homebrew
- Build and audit the formula according to the PR template
- After the build & install from source and audit, please also run `brew test <formula>` and ensure that the tests don't hang.

We can't have tests that hang or that are extremely expensive. If the test is expensive, then it may be worth considering ways to implement a cheaper one.

You're welcome to roll this branch back to https://github.com/Homebrew/homebrew-core/commit/5d935347e1e04162dd6bbc0b431721da5c2736fe and then open a new PR for the @5.4 and @5.3 versions, or you can close this PR and open two new ones. Up to you.

Thanks for your efforts in contributing to Homebrew.

**Comment by jamesdbloom** [comment]
@zbeekman Several users of MockServer have explicitly request support in homebrew for older version of MockServer.  Is there a reason why a Formula shouldn't support multiple versions?

**Comment by zbeekman** [comment]
The only reason would be because of introducing additional maintenance and complexity. However, if it's a well used, popular package with demand for older versions, that can/should be weighed against complexity and maintenance burden. I've had a crazy two weeks, including a stolen laptop, so I probably won't have time to look into the addition of older versions until later tonight or tomorrow.

Please do submit both PRs (after testing locally including `brew test mockserver`) and we'll assess the pros/cons of adding the older versions.

**Comment by jamesdbloom** [comment]
For now I've resubmitted a PR to update the version twice however different tests have failed each time for reasons that are unrelated to my code change.  Can you please take a look at #34330

**Pull request closed without merging**
