### PR TITLE
chapel-1.17.0

### PR DESCRIPTION
**Pull request by awallace-cray**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by awallace-cray** [comment]
Same thing every six months. (https://github.com/Homebrew/homebrew-core/pull/19051 for example). Thanks again.

**Comment by awallace-cray** [comment]
Hello, anyone! The newly-built Chapel 1.17.0 bottles are not quite the same as what I got. 

When you built these binaries, you must have run the build during PyPI's "brownout" time slot (https://status.python.org/incidents/hdx7w97m5hr8). One part of the Chapel build, responsible for a rather minor optional feature ("chpldoc"), just silently did not work because of this PyPI "brownout". I only noticed this myself after I tested out our newly released Homebrew formula. 

As noted, the Chapel 1.17.0 formula and bottles are 98% functional as-is, and I do not want to just pull them down without having something better. 

If you could re-build those binaries (bottles) at just the right time (:16-:29 or :46-:59 minutes, any hour), then PyPI should accept the connection, and that would be great.  

Otherwise, I'm willing to try something else.  One thing I haven't tried yet, is to use Homebrew versions of OpenSSL and Python2.7 to build Chapel. I don't know if that will help, but I am going to try it. 

Thanks!

**Comment by DomT4** [comment]
On High Sierra at least, where the system `python` is linked to LibreSSL which can handle modern connections, that doesn't seem to be the issue.

```
==> make chpldoc
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /usr/local/Cellar/chapel/1.17.0/libexec/third-party/llvm none
make[2]: Nothing to be done for `none'.
cd chpl-venv && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc-venv
***** adt/ *****
***** AST/ *****
***** backend/ *****
***** codegen/ *****
***** ifa/ *****
mkdir -p /usr/local/Cellar/chapel/1.17.0/libexec/third-party/chpl-venv/install/darwin/py2.7
***** ipe/ *****
export PYTHONPATH=/usr/local/Cellar/chapel/1.17.0/libexec/third-party/chpl-venv/install/darwin/py2.7:$PYTHONPATH && \
	/usr/bin/easy_install --install-dir=/usr/local/Cellar/chapel/1.17.0/libexec/third-party/chpl-venv/install/darwin/py2.7  virtualenv==12.0.5
***** main/ *****
***** optimizations/ *****
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 11, in <module>
    load_entry_point('setuptools==18.5', 'console_scripts', 'easy_install')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 46, in <module>
    from setuptools.archive_util import unpack_archive
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/archive_util.py", line 15, in <module>
    from pkg_resources import ensure_directory, ContextualZipFile
ImportError: cannot import name ContextualZipFile
make[2]: *** [install/darwin/py2.7/virtualenv] Error 1
make[1]: *** [/usr/local/Cellar/chapel/1.17.0/libexec/third-party/chpl-venv/install/darwin/py2.7/chpl-virtualenv/bin/sphinx-build] Error 2
make: [third-party-chpldoc-venv] Error 2 (ignored)
***** parser/ *****
***** passes/ *****
***** resolution/ *****
***** util/ *****
***** ./ *****
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc
rm -f /usr/local/Cellar/chapel/1.17.0/libexec/bin/darwin/chpldoc
ln -s chpl /usr/local/Cellar/chapel/1.17.0/libexec/bin/darwin/chpldoc

==> make test-venv
cd chpl-venv && /Applications/Xcode.app/Contents/Developer/usr/bin/make test-venv
export PYTHONPATH=/usr/local/Cellar/chapel/1.17.0/libexec/third-party/chpl-venv/install/darwin/py2.7:$PYTHONPATH && \
	/usr/bin/easy_install --install-dir=/usr/local/Cellar/chapel/1.17.0/libexec/third-party/chpl-venv/install/darwin/py2.7  virtualenv==12.0.5
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 11, in <module>
    load_entry_point('setuptools==18.5', 'console_scripts', 'easy_install')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 46, in <module>
    from setuptools.archive_util import unpack_archive
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/archive_util.py", line 15, in <module>
    from pkg_resources import ensure_directory, ContextualZipFile
ImportError: cannot import name ContextualZipFile
make[2]: *** [install/darwin/py2.7/virtualenv] Error 1
make[1]: *** [/usr/local/Cellar/chapel/1.17.0/libexec/third-party/chpl-venv/install/darwin/py2.7/chpl-virtualenv/chpl-test-reqs] Error 2
make: [third-party-test-venv] Error 2 (ignored)
```

It does however build without throwing errors all over the place if you build against `python@2`.

**Comment by DomT4** [comment]
I can't decide if it's slightly heavy-handed on some level but I've opened https://github.com/Homebrew/homebrew-core/pull/26225 for people to think/talk through. It does resolve the silent build tantrums.

**Comment by awallace-cray** [comment]
https://github.com/Homebrew/homebrew-core/pull/26225#issuecomment-379098840
I'd say, please approve that. 
Thanks

**Pull request closed without merging**
