### PR TITLE
yarn 0.23.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ilovezfs — COMMENTED** [review]
The homepage says 0.23.2 is now the current stable version but the 0.23.2 release on GitHub is still designated "pre-release" so we should probably wait until that status gets updated as well.

**Comment by chrisfinazzo** [comment]
Ugh. #12399 is a duplicate - merge as you see fit.

**Comment by Daniel15** [comment]
lol, I wrote a script to send PRs to update Brew as part of our release process, but it was broken and when I fixed it it failed due to this PR already being opened 😛 

https://build.dan.cx/job/yarn-homebrew/2/console

0.23.2 is stable, I think the GitHub release hasn't been updated.

**Comment by Daniel15** [comment]
lol, I wrote a script to send PRs to update Brew as part of our release process, but it was broken and when I fixed it it failed due to this PR already being opened 😛 

https://build.dan.cx/job/yarn-homebrew/2/console

0.23.2 is stable, I think the GitHub release hasn't been updated. I updated the GitHub release now. In general, https://yarnpkg.com/latest-version is the source of truth for the latest stable Yarn version number.

**Comment by chrisfinazzo** [comment]
@Daniel15,

Yeah, I goofed on this one.

I was looking at @jcoulaud's Boilerplate-app and wanted to do a PR there for Jekyll's default theme, minima. Boilerplate's dev server requires Yarn, so I thought `brew install yarn` would do the trick. However, when I ran it, the install failed because I wasn't getting the latest version out of Homebrew, hence the PR.

So I guess `brew bump-formula-pr` is a thing - I did it manually in my branch. #whippersnappers

what-magic

**Comment by Daniel15** [comment]
>  so I thought brew install yarn would do the trick. However, when I ran it, the install failed because I wasn't getting the latest version out of Homebrew

@chrisfinazzo  - What failed exactly? Installing older Yarn versions should work fine.

**Comment by neutric** [comment]
Thanks guys!

**Pull request merged**
