### PR TITLE
sync_gateway 2.7.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
even 2.7.1 is not rebuildable with the same error

**Comment by iMichka** [comment]
> repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
... A new version of repo (2.5) is available.
... You should upgrade soon:
 cp /private/tmp/sync_gateway-20200524-45530-ahy51q/repo_cache/sync_gateway/.repo/repo/repo /private/tmp/sync_gateway-20200524-45530-ahy51q/depot_tools/repo

It would be great if we could migrate this to python 3.8

**Comment by chenrui333** [comment]
> > repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
> > ... A new version of repo (2.5) is available.
> > ... You should upgrade soon:
> > cp /private/tmp/sync_gateway-20200524-45530-ahy51q/repo_cache/sync_gateway/.repo/repo/repo /private/tmp/sync_gateway-20200524-45530-ahy51q/depot_tools/repo
> 
> It would be great if we could migrate this to python 3.8

totally, but I did not see the build instructions on the upstream repo for python3, I will submit an issue to ask there.

**Comment by chenrui333** [comment]
issue tracker in here, https://issues.couchbase.com/browse/CBG-880

**Pull request closed without merging**
