### PR TITLE
apache-spark 2.1.1: previous version

### PR DESCRIPTION
**Pull request by oliverxchen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Please explain why this version is needed.

**Comment by oliverxchen** [comment]
AWS EMR 5.7.0 uses Spark 2.1.1. (http://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-5.7.0/emr-release-components.html). 

I'm working on a production system using AWS EMR 5.7.0 and this version is needed so that developers' local environments can match the production system as closely as possible.

**Comment by ilovezfs** [comment]
Please consider hosting this [in your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) as I don't see any evidence on the homepage that upstream will continue to maintain the 2.1.x apart from the 2.2.x line. But thank you for the PR!

**Comment by oliverxchen** [comment]
Ok, I've hosted my own tap. Thanks for the tip and sorry for the trouble!

**Comment by ilovezfs** [comment]
@oliverxchen it's no trouble at all! :heart:

**Pull request closed without merging**
