### PR TITLE
immudb: build using go@1.16

### PR DESCRIPTION
**Pull request by jeroiraz**
Signed-off-by: Jeronimo Irazabal <jeronimo.irazabal@gmail.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — CHANGES_REQUESTED** [review]
Does this not work with the latest `go`?

**Comment by SMillerDev** [comment]
With go 1.19 the 1.16 release is deprecated. If it doesn't work with the latest Go that should be fixed.

**Comment by jeroiraz** [comment]
> With go 1.19 the 1.16 release is deprecated. If it doesn't work with the latest Go that should be fixed.

would it be possible to use 1.17 instead? As it's the newest version we are using to build binaries?

**Comment by SMillerDev** [comment]
Does it not work with a modern go version?

**Comment by jeroiraz** [comment]
> Does it not work with a modern go version?

It should work but we'd like to avoid the need of using latest compiler version for users who may be using older versions. If the formula uses latest Go, will that require users to upgrade their Go version as a prerequisite?

**Comment by SMillerDev** [comment]
Users will rarely need to have any Go version installed to use homebrew Formula that use Go because go produces complete binaries.

**Comment by carlocab** [comment]
We ship pre-built binaries for Linux and the last three versions of macOS, so `brew install immudb` does not need a Go installation for the vast majority of our users.

**Comment by jeroiraz** [comment]
thanks a lot for your time and explanation. I'm closing it then

**Pull request closed without merging**
