### PR TITLE
s-search 0.5.5

### PR DESCRIPTION
**Pull request by ilovezfs**
gvt vendoring

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 vendor!

**Comment by DomT4** [comment]
They would be using one of the few popular vendoring systems we don't have a formula for 😅. Nice work here 👍

**Comment by ilovezfs** [comment]
@DomT4 yeah I was considering asking for a tag for gvt to create a formula, but it didn't look like anything else in core is using it (yet).

**Comment by DomT4** [comment]
Aye. It's a useful tool, and possibly the last _big_ Go vendoring helper I know a lot of people recommend that we don't ship a formula for. Maybe worthwhile.

**Pull request closed without merging**
