### PR TITLE
q 3.1.7

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
I don't think we want to update this as mentioned in deprecation message. PyOxidizer-based build was added in 3.x making this not meet Homebrew's acceptable formulae

**Comment by pthariensflame** [comment]
I see!  Should we delete the formula instead, then?

**Comment by cho-m** [comment]
We usually go through a deprecate to disable to remove workflow. Some related docs for this is https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#disabling
> Formulae should not be disabled without a deprecation period of at least three months unless the circumstances are exceptional (e.g. the formula does not build on any supported macOS version or Linux). Popular formulae should have longer deprecation periods. The popularity of a formula should be based on our analytics data.

It was deprecated on `2021-11-30` so minimum of 3 months have passed, so the popularity will determine when we should disable. Would need another maintainer to judge this as I am not familiar with exact translation of installs to deprecation periods.

**Comment by Bo98** [comment]
There's nothing really set in stone. For versioned formulae (which I know this isn't but still), the boundary is top 3000 install-on-request and this is in the top 2000.

I would say the maximum deprecation period is about a year (unless there's a good reason for longer) so I guess it depends where you place it on that 3-12 month spectrum.

In terms of checking for new versions: `brew livecheck` is already disabled for this.

**Pull request closed without merging**
