### PR TITLE
teleport 2.0.1

### PR DESCRIPTION
**Pull request by bcg62**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — COMMENTED** [review]
Does the build fail without libu2f-host?

**Comment by bcg62** [comment]
@ilovezfs no, it's not a build requirement. It's needed at runtime if you are using u2f for authentication

**Comment by ilovezfs** [comment]
@bcg62 Does u2f authentication work if `libu2f-host` is installed subsequently or does it have to have been available during the build?

**Comment by bcg62** [comment]
@ilovezfs it does not have to be available at build time. Subsequently also gets it working.

**Comment by ilovezfs** [comment]
OK. I think it's safe to leave the dependency out in that case.

**Comment by bcg62** [comment]
updated

**Comment by ilovezfs** [comment]
@bcg62 thanks for keeping this up to date! :rocket:

**Pull request closed without merging**
