### PR TITLE
pyside 6.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
```
  /tmp/pyside-20230405-65909-hh6hei/pyside-setup-everywhere-src-6.5/build/sources/pyside6/PySide6/QtCore/PySide6/QtCore/qcalendar_wrapper.cpp:502:34: error: expected unqualified-id
          int cppArg1 = QCalendar::(unnamed enum at /opt/homebrew/lib/QtCore.framework/Headers/qcalendar.h:57:5)::Unspecified;
                                   ^
```

Probably due to https://github.com/llvm/llvm-project/commit/19e984ef8f49bc3ccced15621989fa9703b2cd5b, new in Clang 16. Also seen in #127600.

**Comment by p-linnane** [comment]
Upstream issue ref: https://bugreports.qt.io/browse/PYSIDE-2268

I tried changing this to `llvm@15`. It worked for `pyside@2`, but not this one.

**Comment by p-linnane** [comment]
Issue specific to this error: https://bugreports.qt.io/browse/PYSIDE-2286

**Comment by carlocab** [comment]
```
  qt.shiboken: (network) Found HOMEBREW_OPT with value: "/opt/homebrew/opt" Assuming homebrew build environment.
  qt.shiboken: (network) Filtering out homebrew include path:  "/opt/homebrew/opt/llvm@15/include"
  qt.shiboken: (network) Filtering out homebrew include path:  "/opt/homebrew/opt/openssl@1.1/include"
  qt.shiboken: (network) Filtering out homebrew include path:  "/opt/homebrew/opt/readline/include"
  qt.shiboken: (network) Filtering out homebrew include path:  "/opt/homebrew/opt/sqlite/include"
  qt.shiboken: (network) Filtering out homebrew include path:  "/opt/homebrew/opt/icu4c/include"
```
https://github.com/Homebrew/homebrew-core/actions/runs/4648214077/jobs/8225808252?pr=127674#step:7:847
Probably not related to the build failure, but still interesting.

**Pull request closed without merging**
