### PR TITLE
opendht 2.3.2 (new formula)

### PR DESCRIPTION
**Pull request by ghenry**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ghenry** [comment]
`brew test opendht` is working on Big Sur Intel and find msgpack-cxx no problem on there. This is just an arm issue? Only fails here but msgpack-cxx is installed:

https://github.com/Homebrew/homebrew-core/runs/5304426367?check_suite_focus=true#step:6:59

**Comment by cho-m** [comment]
CMake is currently looking for the `msgpack` C header (`version_master.h`) rather than the `msgpack-cxx` C++ header (`version_master.hpp`) https://github.com/savoirfairelinux/opendht/blob/2.3.2/cmake/FindMsgpack.cmake#L24-L26

If you have `msgpack` locally installed, then it may pass due to finding those headers.

---

If `opendht` only needs C++ headers, then the CMake logic should be changed upstream to find that header. A workaround would be to help CMake via `-DMSGPACK_INCLUDE_DIR=...`, etc. input.

If `opendht` needs C headers, then `msgpack` may be needed as dependency.

The current issue may be due to how upstream split up code. Homebrew has followed suit and packaged these in separate formulae.

**Comment by ghenry** [comment]
Thanks for digging into this and your feedback. I'll ask upstream and for a brand new PR? That's the preferred way?

**Comment by ghenry** [comment]
Upstream are fixing this @cho-m  Thanks again.

**Comment by aberaud** [comment]
should hopefully be fixed by OpenDHT 2.3.3

**Pull request closed without merging**
