### PR TITLE
spice-gtk: backport fix to build on Sonoma

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Is this tracked somewhere (either upstream or Apple depending on where the issue is)?

**Comment by cho-m** [comment]
> Is this tracked somewhere (either upstream or Apple depending on where the issue is)?

Not sure where issue is yet. Snippet of command run on `spice-gtk` side includes:
```
clang  -o src/libspice-client-glib-2.0.8.dylib ... -export-symbols /private/tmp/spice-gtk-20240119-26450-kkru8e/spice-gtk-0.42/src/spice-glib-sym-file
```

Symbol file being https://gitlab.freedesktop.org/spice/spice-gtk/-/blob/v0.42/src/spice-glib-sym-file

Looks like this is used when compiler doesn't support `-Wl,--version-script` - https://gitlab.freedesktop.org/spice/spice-gtk/-/blob/v0.42/src/meson.build#L186-192

**Comment by Bo98** [comment]
Surprised it ever worked then. `-exported_symbols_list` is the equivalent on macOS.

Looks like this is fixed upstream by https://gitlab.freedesktop.org/spice/spice-gtk/-/commit/1511f0ad5ea67b4657540c631e3a8c959bb8d578 so we could apply that.

**Review by Bo98 — APPROVED** [review]
Thanks!

**Pull request merged**
