### PR TITLE
mpv 0.28.1

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
This still has the HEAD ffmpeg dep

**Comment by zmwangx** [comment]
Oh, 3.4.1 isn't good enough? I didn't check.

**Comment by ilovezfs** [comment]
I don't think so. I can check again.

**Comment by zmwangx** [comment]
Ah, now I remember, we're waiting for 3.5.

**Comment by zmwangx** [comment]
Hmm, not sure why [someone with only 6 commits](https://github.com/mpv-player/mpv/commits?author=CounterPillow), mostly typo fixes, was lecturing in that issue. For a fleeting moment I thought mpv had a new lead maintainer.

**Comment by ilovezfs** [comment]
Yeah, I've banned him from the Homebrew organization at least.

**Comment by yetisyny** [comment]
FFmpeg 3.4.2 is out. So, does this finally let us use the latest version of mpv if we use stable releases?

Seems like the answer is NO, because the library versions at [http://ffmpeg.org/download.html#release_3.4](http://ffmpeg.org/download.html#release_3.4) are not as high as the ones listed at [https://github.com/mpv-player/mpv/releases/tag/v0.28.0](https://github.com/mpv-player/mpv/releases/tag/v0.28.0).

I guess we will have to wait for the next major version of FFmpeg, probably 3.5, to be released before we can use mpv 0.28 and later, for those of us who don’t like using unstable HEAD revisions of FFmpeg that sometimes don’t even compile correctly.

At least mpv put out version 0.27.1, I am using it now, glad to see that developers from mpv, FFmpeg, and Homebrew are on speaking terms at least, things got pretty nasty late last year, especially around the time of the ffmpeg-mpv fork. Things still are kinda nasty but not quite as bad, at least there is some level of cooperation between these projects now and it seems like mpv and FFmpeg developers have made peace. I hope the next major FFmpeg release comes out soon so we can put this nonsense behind us.

**Comment by ilovezfs** [comment]
It needs 3.5, right. Both the ffmpeg formula and the mpv formula have --HEAD so you can do that in the meantime.

**Pull request closed without merging**
