### PR TITLE
jfrog-cli-go 1.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
remove remaining go_resource in favor of upstream vendor directory

### CODE REVIEW

**Comment by DomT4** [comment]
There's a `vendor` folder upstream, might be able to ditch the last resource left standing here... Maybe.

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by ilovezfs** [comment]
@DomT4 ping.

**Comment by DomT4** [comment]
Was sure I'd responded to this one. Huh. :shipit:

**Comment by ilovezfs** [comment]
Yes, there was an eerie silence.

**Comment by DomT4** [comment]
👻

**Pull request closed without merging**
