### PR TITLE
switch to HTTPS for Git access on sf.net (and some misc domains) #4

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

For formulae that used an unorthodox/arcane repository URL format.

### CODE REVIEW

**Comment by vszakats** [comment]
Added a bunch of misc non-sf.net upgrades too.

**Comment by AraHaan** [comment]
Why did you not put it all in a single pull request with 1 commit instead?

**Comment by vszakats** [comment]
@AraHaan There is policy to never include multiple formulae into a single commit. This makes it easy revert without effecting other formulae and helping the formula histories separate.

**Comment by AraHaan** [comment]
However this PR does just that on the URLs unless this is fix some issues with them.

**Comment by vszakats** [comment]
@AraHaan Do you mean this PR has a commit which touches multiple formulae?
These commits are not fixing _fatal_ problems (except for `synfig`, where the original URI was broken); their goal is to enable a standard, proxy-able, encrypted and authenticated transport protocol for replicating the source code to the local machine. The `git:` protocol is cleartext, this is replaced with `https:`, which isn't. In most cases these transfers are not protected/verified by any other means, so TLS is quite useful here.

**Comment by MikeMcQuaid** [comment]
@AraHaan Please leave the review to more Homebrew maintainers and previous contributors, thanks.

**Comment by vszakats** [comment]
CI says these:
```
==> FAILED
Error: 1 problem in 1 formula
halibut:
  * HEAD: The URL https://git.tartarus.org/simon/halibut.git is not a valid git URL
[...]
==> FAILED
Error: 1 problem in 1 formula
agedu:
  * HEAD: The URL https://git.tartarus.org/simon/agedu.git is not a valid git URL
```

When testing these using `git clone <URL>`, both do work fine locally with both Apple and Homebrew Git. It's also strange that other similar repos like Putty checked out fine by the CI.

**Comment by ilovezfs** [comment]
you could try with `, :using => :git` instead of `.git` I guess

**Comment by vszakats** [comment]
Should I add this to all 4 of the `git.tartarus.org` URLs? (two of them work just fine with the exact same URL form.)

**Comment by vszakats** [comment]
Moved `git.tartarus.org` commits to #10896.

**Comment by vszakats** [comment]
A single, apparently intermittent false positive on El Cap:
```
==> FAILED
Error: 1 problem in 1 formula
ngspice:
  * HEAD: The URL https://git.code.sf.net/p/ngspice/ngspice.git is not a valid git URL
==> brew style ngspice
```

**Comment by ilovezfs** [comment]
Thanks @vszakats

**Pull request merged**
