### PR TITLE
conjure-up 2.6.9

### PR DESCRIPTION
**Pull request by kwmonroe**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Bump core conjure-up to match latest upstream release. Also refresh the related resources (using `homebrew-pypi-poet`) to latest tested revisions.

### CODE REVIEW

**Comment by chenrui333** [comment]
19:39:30 ==> /usr/local/Cellar/conjure-up/2.6.9/bin/conjure-up openstack-base metal --show-env
19:39:30 Error: conjure-up: failed
19:39:30 An exception occurred within a child process:
19:39:30   Test::Unit::AssertionFailedError: <0> expected but was
19:39:30 <nil>.

**Comment by kwmonroe** [comment]
Hmmm,`test` and `audit` are working for me:

```bash
$ brew test conjure-up && echo $?
Testing conjure-up
==> /usr/local/Cellar/conjure-up/2.6.9/bin/conjure-up openstack-base metal --show-env
0

$ brew audit --strict conjure-up && echo $?
0
```

Let's tweak this so the spell path test (the thing we actually care about) isn't hinged on shell output.

**Comment by chenrui333** [comment]
Yeah, it only failed on Catalina build, so we probably get away with it.

cc @fxcoudert @SMillerDev

**Comment by kwmonroe** [comment]
> Yeah, it only failed on Catalina build, so we probably get away with it.

Ah, of course!  I glossed over the darwin19 and ruby-2.6.0 refs when inspecting the failure earlier. I don't have a Catalina env available to dig into this.  Is it possible to exclude catalina in the formula?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @kwmonroe for your contribution!!

**Comment by chenrui333** [comment]
@kwmonroe, do you want to double check on this upgrade again? I think we still have this issue with our other upgrades.

**Pull request closed without merging**
