### PR TITLE
tfenv 2.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failure:

```
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200429-70412-8uf5pe.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tfenv.rb --verbose
==> /usr/local/Cellar/tfenv/2.0.0/bin/tfenv list-remote
/usr/local/Cellar/tfenv/2.0.0/bin/tfenv: line 39: /usr/local/Cellar/tfenv/2.0.0/lib/helpers.sh: No such file or directory
[FATAL] /usr/local/Cellar/tfenv/2.0.0/bin/tfenv: Failed to source helpers from /usr/local/Cellar/tfenv/2.0.0/lib/helpers.sh
Error: tfenv: failed
Failed executing:
```

**Comment by Bo98** [comment]
#53471

**Comment by rafilkmp3** [comment]
@stephengroat-dd

**Comment by Bo98** [comment]
The error when it is installed correctly:

```
/usr/local/Cellar/tfenv/2.0.0/bin/tfenv: line 107: @: unbound variable
```

**Comment by chenrui333** [comment]
I cannot reproduce it in my local catalina machine :

```
$ /usr/local/Cellar/tfenv/2.0.0/bin/tfenv
tfenv 2.0.0
Usage: tfenv <command> [<options>]

Commands:
   install       Install a specific version of Terraform
   use           Switch a version to use
   uninstall     Uninstall a specific version of Terraform
   list          List all installed versions
   list-remote   List all installable versions
```

**Comment by Bo98** [comment]
@chenrui What does your `bash --version` output?

**Comment by chenrui333** [comment]
was about to post that :)
```
$ bash -version
GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin19.3.0)
```

**Comment by Bo98** [comment]
@chenrui333 What does your `bash --version` output?

**Comment by Bo98** [comment]
Yeah, default macOS bash is 3.2.57.

**Comment by chenrui333** [comment]
make sense.

**Comment by chenrui333** [comment]
Looking at their travis build, they do have dependency of bash:
https://travis-ci.com/github/tfutils/tfenv/jobs/323243349

$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bash; fi

**Comment by Bo98** [comment]
Swapping out the user's default shell is quite a intrusive thing to do. We generally avoid it unless there is a good reason.

For example, it's why we don't ship the latest `yarn-completion`.

**Comment by chenrui333** [comment]
Raising an issue to see if they can simplify the installation process.

**Comment by rafilkmp3** [comment]
maybe we can use a brew bash as a dependency and use this to run tests. 

but sure this can cause issues in future, and not sure if works with vanila macos

**Comment by issyl0** [comment]
This formula is [very popular](https://formulae.brew.sh/formula/tfenv), so it would be good to find a fix.

**Comment by bayandin** [comment]
> This formula is [very popular](https://formulae.brew.sh/formula/tfenv), so it would be good to find a fix.

Trying to fix it in https://github.com/tfutils/tfenv/pull/181

If we have bash-guru here, please take a look

**Comment by chenrui333** [comment]
> > This formula is [very popular](https://formulae.brew.sh/formula/tfenv), so it would be good to find a fix.
> 
> Trying to fix it in [tfutils/tfenv#181](https://github.com/tfutils/tfenv/pull/181)
> 
> If we have bash-guru here, please take a look

Including your PR change in here

**Comment by bayandin** [comment]
> Including your PR change in here

Let's wait until I (or somebody else) fix problems with tests (I'm afraid it didn't test enough) https://github.com/tfutils/tfenv/pull/181#issuecomment-622383038

**Comment by bayandin** [comment]
https://github.com/tfutils/tfenv/pull/181 is merged now, so we can add it as a patch:

```ruby
patch do
  url "https://github.com/tfutils/tfenv/pull/181.patch?full_index=1"
  sha256 "b1365be51a8310a44b330f9b008dabcdfe2d16b0349f38988e7a24bcef6cae09"
end

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
