### PR TITLE
inlets 2.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
05:09:53 cp -pR /private/tmp/d20191017-78586-mskr1j/pkg/. /private/tmp/inlets-20191017-78586-dy76wl/pkg
05:09:53 chmod -Rf +w /private/tmp/d20191017-78586-mskr1j
05:09:53 ==> go build -ldflags -s -w -X main.GitCommit=f505174ba97c1d14d8a171e8789a364e0493288a -X main.Version=2.6.0 -a -installsuffix cgo -o /usr/local/Cellar/inlets/2.6.0/bin/inlets
05:09:53 main.go:4:2: cannot find package "github.com/inlets/inlets/cmd" in any of:
05:09:53 	/private/tmp/inlets-20191017-78586-dy76wl/src/github.com/alexellis/inlets/vendor/github.com/inlets/inlets/cmd (vendor tree)
05:09:53 	/usr/local/Cellar/go/1.13.1/libexec/src/github.com/inlets/inlets/cmd (from $GOROOT)
05:09:53 	/private/tmp/inlets-20191017-78586-dy76wl/src/github.com/inlets/inlets/cmd (from $GOPATH)
05:09:53

**Comment by dawidd6** [comment]
Upstream URL changed: `github.com/alexellis/inlets` -> `github.com/inlets/inlets`.

**Comment by chenrui333** [comment]
Cool, going to update now.

**Comment by chenrui333** [comment]
It would be test failure 

```
Starting inlets server with port 57329
Starting inlets client with remote localhost:57329, upstream localhost:57328
2019/10/22 21:51:02 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
2019/10/22 21:51:02 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
2019/10/22 21:51:02 Starting server - version 2.6.0
2019/10/22 21:51:02 Starting client - version 2.6.0
2019/10/22 21:51:02 Upstream:  => localhost:57328
2019/10/22 21:51:02 Control Plane Listening on :57329
2019/10/22 21:51:02 Data Plane Listening on :57329
INFO[0000] Connecting to proxy                           url="ws://localhost:57329/tunnel"
2019/10/22 21:51:02 http: superfluous response.WriteHeader call from github.com/inlets/inlets/vendor/github.com/rancher/remotedialer.DefaultErrorWriter (server.go:23)
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
Querying upstream endpoint via inlets remote: http://localhost:57329/inlets-test
Tearing down Mock Server on PID 94937
Tearing down Inlets Server on PID 94943
Tearing down Inlets Client on PID 94944
Error: inlets: failed
```

**Pull request closed without merging**
