### PR TITLE
baresip 0.6.5

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on Catalina, Mojave

==> brew test baresip --verbose
==> FAILED
Testing baresip
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200120-86822-ct3io7.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/baresip.rb --verbose
==> /usr/local/Cellar/baresip/0.6.5/bin/baresip -f /private/tmp/baresip-test-20200120-86823-dr87jq/.baresip -t
baresip v0.6.5 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
config: creating config template /Users/brew/.baresip/config
[31mconfig: writing /Users/brew/.baresip/config: No such file or directory
[;m[31mmain: configure failed: No such file or directory
[;mua: stop all (forced=1)
Error: baresip: failed

**Comment by Moisan** [comment]
I opened an issue upstream. The same behavior shows up in the current version (`0.5.10`).

**Comment by alfredh** [comment]
is `HAVE_GETOPT` defined in main.c ?

I think for selftesting it is better to run "make test".
Baresip has a full test suite that tests the whole stack.

also make sure that SYSROOT is correctly defined:

```
       SYSROOT         := $(shell xcrun --show-sdk-path)/usr
```

**Comment by Moisan** [comment]
Thanks @alfredh for the pointer to `HAVE_GETOPT`, that fixed the issue.

For the `make test` part, we prefer to have tests in Homebrew formulae that only require the formula to be installed, not necessarily to have access to the whole codebase.

**Comment by chenrui333** [comment]
🎉 🎉

**Pull request closed without merging**
