### PR TITLE
gnome-themes-extra: fix build

### PR DESCRIPTION
**Pull request by fxcoudert**
Fall-out from a44f49f9fbd38252db73ab2d696dc97649f7b041

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  checking for perl >= 5.8.1... 5.38.0
  checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool
```

**Comment by fxcoudert** [comment]
Linux-only, and for some reason it was working before…

**Comment by SMillerDev** [comment]
Rebuild the intltool bottles that it depends on expecting a Linux failure there, but that seems to work fine. https://github.com/Homebrew/homebrew-core/actions/runs/6478958009

**Comment by chenrui333** [comment]
I suspect that we do need to revision bump the formula (works for me after it)

- https://github.com/Homebrew/homebrew-core/pull/150703

**Review by chenrui333 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
