### PR TITLE
ooniprobe: deprecate and fix patch url

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Use stable commit url rather than unstable PR url for patches

### CODE REVIEW

**Comment by dtrodrigues** [comment]
This looks to be no longer maintained: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ooniprobe.rb#L20

**Comment by Rylan12** [comment]
I don't think I totally understand that comment. What is supposed to use https://github.com/ooni/probe-cl? It's out of pre-release now.

**Comment by Rylan12** [comment]
Changing `virtualenv_install_with_resources` to `virtualenv_install_with_resources :using => "python2"` seems to work but I'm not sure that's the right solution. If it's not maintained it should probably be disabled.

**Comment by dtrodrigues** [comment]
I think the `ooniprobe` tool being pointed to is unmaintained and was replaced by https://github.com/ooni/probe-cli, so either this formula needs to be deleted/deprecated or replaced by one that points to the new repo. It's had 30 or so installs in the last 90 days, so I'm leaning towards the former and somebody can create a new formula if the demand exists.

**Comment by gromgit** [comment]
Given that the old software (https://github.com/ooni/probe-legacy) was written in Python, and the new one's in Go, I think the right move would be to deprecate this and create a new `probe-cli` formula.

**Comment by Rylan12** [comment]
Okay. In that case, should the homepage still be updated to https://ooni.org or left at what is currently is?

```
==> brew audit ooniprobe --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
ooniprobe:
  * https://ooni.torproject.org/ permanently redirects to https://ooni.org
```

**Comment by gromgit** [comment]
Might as well fix the homepage URL, since that reflects current reality.

**Review by dtrodrigues — APPROVED** [review]

**Pull request merged**
