### PR TITLE
root: v6.22.00

### PR DESCRIPTION
**Pull request by henryiii**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://discourse.brew.sh/t/updating-root-formula-a-few-questions

This fixes a long standing issues with the Python part formula - ROOT finally avoids linking to the Python libraries directly in 6.22, so this is now runnable without first sourcing thisroot.sh (previously required for Python usage).

This also fixes a case where the shim directory was being compiled into the library.

And, of course, this updates to 6.22!

### CODE REVIEW

**Comment by henryiii** [comment]
PS: I also dropped the workaround for macOS < 10.13, assuming it is not supported by brew - and it is no longer supported by ROOT as well, according to the devs.

**Comment by chenrui333** [comment]
> PS: I also dropped the workaround for macOS < 10.13, assuming it is not supported by brew - and it is no longer supported by ROOT as well, according to the devs.

Good call, thanks!

**Review by chenrui333 — COMMENTED** [review]
lgtm

**Review by SMillerDev — APPROVED** [review]
Thanks @henryiii  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
