### PR TITLE
wtfutil 0.19.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
worth mentioning starting 0.15.0, the binary has been renamed to `wtfutil` to avoid conflict:
https://wtfutil.com/blog/2019-07-10-wtfutil-release/

Thanks @senorprogrammer for helping fixing the test step issue (https://github.com/wtfutil/wtf/issues/509). 

Previous efforts: #39962 #39896

### CODE REVIEW

**Comment by chenrui333** [comment]
I think we should merge this quickly. As this has been included as installation step in the main repo, so that it won't cause any confusion.

https://github.com/wtfutil/wtf#install-via-homebrew

**Comment by senorprogrammer** [comment]
The installation step in the main repo includes the step to first `tap` from [homebrew-wtfutil](https://github.com/wtfutil/homebrew-wtfutil) so it's not dependent on this. However having this merged in would allow me to remove the `tap` step, which would be awesome.

**Comment by chenrui333** [comment]
yeah, that is right!

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Pull request closed without merging**
