### PR TITLE
protobuf: add Python 3.7 compatibility

### PR DESCRIPTION
**Pull request by benmwebb**
If built using --with-python, compilation fails with
Python 3.7 because the Python folks changed their C
API such that PyUnicode_AsUTF8AndSize() now returns
a const char* rather than a char*. Add a patch to
work around.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x]  Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Thanks for the PR @benmwebb. This needs to be submitted upstream as a PR and then we can use a `patch do` block in the formula to apply the upstream PR as a patch.

**Comment by benmwebb** [comment]
OK, I think I can do that. I was just following the example of OpenCV, which patches directly in the formula: 377ac4c29. Figured that was the approved way to handle such issues.

**Comment by ilovezfs** [comment]
@benmwebb see https://github.com/Homebrew/homebrew-core/pull/29707 :)

**Comment by benmwebb** [comment]
Upstream PR: google/protobuf#4862. I can update *this* PR once the protobuf folks merge that (or otherwise fix Python 3.7), if that works best for you guys.

**Comment by ilovezfs** [comment]
Just use "https://github.com/google/protobuf/pull/4862.patch?full_index=1"

**Comment by ilovezfs** [comment]
i.e. no need to wait

**Comment by benmwebb** [comment]
OK, PR updated to use the upstream patch.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @benmwebb! Shipped.

**Pull request merged**
