### PR TITLE
vectorscan 5.4.9

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /usr/bin/clang test.c -I/opt/homebrew/Cellar/vectorscan/5.4.9/include -L/opt/homebrew/Cellar/vectorscan/5.4.9/lib -lhs -o test
  ==> ./test
  Error: vectorscan: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /hyperscan\ v5\.4\.9/ to match "hyperscan v5.4.8 ".
```

**Comment by mistydemeo** [comment]
Looks like the version constants weren't updated this release: https://github.com/VectorCamp/vectorscan/issues/138

We can patch/inreplace `CMakeLists` to set the minor version appropriately.

**Comment by chenrui333** [comment]
> Looks like the version constants weren't updated this release: [VectorCamp/vectorscan#138](https://github.com/VectorCamp/vectorscan/issues/138)
> 
> We can patch/inreplace `CMakeLists` to set the minor version appropriately.

yeah, their release was not done cleanly.

**Comment by mistydemeo** [comment]
According to that issue, 5.4.9 isn't actually released yet and that tag was a mistake.

**Comment by chenrui333** [comment]
#126906

**Pull request closed without merging**
