### PR TITLE
gitlab-runner 13.0.1

### PR DESCRIPTION
**Pull request by clementpadovani**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by clementpadovani** [comment]
can we get https://github.com/Homebrew/homebrew-core/pull/55649/checks?check_run_id=729904633 to re-run?

I'm not quite sure why this failed without any specific error

**Comment by clementpadovani** [comment]
I have absolutely no clue as to why the checks are failing…

Would someone know what's going on?

**Comment by SMillerDev** [comment]
Can you rebase on the latest master?

**Comment by clementpadovani** [comment]
@SMillerDev I think I messed up the rebase… I’m going to to close this MR and create a new one.

**Comment by clementpadovani** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/55931

**Pull request closed without merging**
