### PR TITLE
pyenv 1.2.20

### PR DESCRIPTION
**Pull request by samdoran**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]
Thanks @samdoran  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by SMillerDev** [comment]
There's no such release. Closing this

**Comment by samdoran** [comment]
Interesting. I thought there was a 1.2.20 release. https://github.com/pyenv/pyenv/releases/tag/v1.2.20
Maybe I just did this prematurely.

**Comment by samdoran** [comment]
This was done in #58379. ¯\_(ツ)_/¯

**Pull request closed without merging**
