### PR TITLE
latino 1.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
Unrelated to the failure: the repository has moved to an organisation (https://github.com/MelvinG24/latino redirects to https://github.com/lenguaje-latino/latino).

**Comment by nandahkrishna** [comment]
The build failure is because they now use submodules, but pulling from the tag still fails because of the absence of `.gitmodules` in `v1.4.0`.

**Comment by chenrui333** [comment]
Close the PR for now.

**Comment by jorge2985** [comment]
Please check https://github.com/lenguaje-latino/latino-core, I answered issue https://github.com/lenguaje-latino/latino/issues/190

**Pull request closed without merging**
