### PR TITLE
psalm 4.18.1

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> Uncaught Error: Class "Composer\InstalledVersions" not found in phar:///opt/homebrew/Cellar/psalm/4.18/bin/psalm/src/Psalm/Internal/CliUtils.php:116
> Stack trace:
> #0 phar:///opt/homebrew/Cellar/psalm/4.18/bin/psalm/src/Psalm/Internal/Cli/Psalm.php(188): Psalm\Internal\CliUtils::requireAutoloaders('/opt/homebrew/L...', false, 'vendor')
> #1 phar:///opt/homebrew/Cellar/psalm/4.18/bin/psalm/src/Psalm/Internal/IncludeCollector.php(31): Psalm\Internal\Cli\Psalm::Psalm\Internal\Cli\{closure}()
> #2 phar:///opt/homebrew/Cellar/psalm/4.18/bin/psalm/src/Psalm/Internal/Cli/Psalm.php(189): Psalm\Internal\IncludeCollector->runAndCollect(Object(Closure))
> #3 phar:///opt/homebrew/Cellar/psalm/4.18/bin/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
> #4 /opt/homebrew/Cellar/psalm/4.18/bin/psalm(14): require('phar:///opt/hom...')
> #5 {main}
> (Psalm (unknown version) crashed due to an uncaught Throwable)

**Comment by derrabus** [comment]
I'll have a look later. It's probably something that has to be solved on Psalm's side.

**Comment by derrabus** [comment]
See vimeo/psalm#7329

**Comment by derrabus** [comment]
The problem has been resolved upstream and a new release 4.18.1 has been issued. However, that release produces warnings on PHP 8.1  (vimeo/psalm#7314). Because of that, I have added a wrapper script (similar to what we have done for the `php-cs-fixer` formulae) to make sure Psalm is executed with PHP 8.0 until that problem has been resolved as well.

**Comment by derrabus** [comment]
CI is 🟢

**Comment by SMillerDev** [comment]
I don't think we should add a wrapper script for that. It runs just fine, you just get some deprecation messages that upstream is already aware of.

**Comment by derrabus** [comment]
Are you sure about that? I'm using that formula to install Psalm locally and those error messages are dumped into the console everytime I run Psalm, which is a bit annoying.

Alternatively, we could have the wrapper script change the error level before running Psalm. This way we would not pin the PHP version and the deprecation warnings would be silenced on PHP 8.1.

**Comment by derrabus** [comment]
Very well, I've reverted the wrapper script. 🙂

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @derrabus!

**Comment by Trurl101** [comment]
This error still persist and make Psalm unusable in some frontend/editors/applications like PHPstorm. because the error message popups constantly.

**Comment by derrabus** [comment]
@Trurl101 I think, you should report this to [the Psalm project](https://github.com/vimeo/psalm/) instead.

**Pull request closed without merging**
