### PR TITLE
lean 3.45.0

### PR DESCRIPTION
**Pull request by fanninpm**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fanninpm** [comment]
Waiting for https://github.com/leanprover-community/mathlib/pull/15325 to be merged.

**Comment by chenrui333** [comment]
Sounds about right, I also think they should automate this process :)

**Comment by fanninpm** [comment]
Third time's the charm, apparently.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
you dont have to close/reopen to trigger a CI build, the rebase would do the same thing.

**Comment by fanninpm** [comment]
> you dont have to close/reopen to trigger a CI build, the rebase would do the same thing.

At the time, it would have been several hours until I had access to my Mac.

**Pull request closed without merging**
