### PR TITLE
hwloc 2.9.3

### PR DESCRIPTION
**Pull request by osalbahr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
Note: 
```
==> hwloc
Current formula version:  2.9.2
Latest livecheck version: 2.9.2
Latest Repology version:  2.9.3
Open pull requests:       none
Closed pull requests:     hwloc: update 2.9.2 bottle. (https://github.com/Homebrew/homebrew-core/pull/142230), hwloc 2.9.2 (https://github.com/Homebrew/homebrew-core/pull/135203)
hwloc was not bumped to the Repology version because it's livecheckable.
```

> More details are available in the [Documentation](https://www-lb.open-mpi.org/projects/hwloc/doc/) (in both PDF and HTML). The documentation for each version contains [examples of outputs](https://www-lb.open-mpi.org/projects/hwloc/doc/v2.9.3/a00359.php#cli_examples) and an [API interface example](https://www-lb.open-mpi.org/projects/hwloc/doc/v2.9.3/a00359.php#interface) (these links are for v2.9.3).

https://www-lb.open-mpi.org/projects/hwloc/

**Comment by chenrui333** [comment]
Good catch, we need an upstream issue to have them fix the website version reporting problem then.

**Comment by chenrui333** [comment]
https://github.com/open-mpi/hwloc/issues/627

**Comment by osalbahr** [comment]
> Good catch, we need an upstream issue to have them fix the website version reporting problem then.

Thx! I owe this to `curl 'https://repology.org/api/v1/projects/?inrepo=homebrew&outdated=on&vulnerable=on' | grep -Eo 'homebrew[^}]+' | awk -F '"' '{print $5}' | shuf` :)

**Comment by osalbahr** [comment]
Is it usual for a job to be queued for >1h?

**Comment by chenrui333** [comment]
> Is it usual for a job to be queued for >1h?

we have lots of PRs in the queue, so for now, yes

**Comment by bgoglin** [comment]
> Good catch, we need an upstream issue to have them fix the website version reporting problem then.

What version reporting problem do you see on the website? 2.9.3 has been there for days. And https://www.open-mpi.org/software/hwloc/current/downloads/latest_snapshot.txt says 2.9.3 is the latest.

**Comment by osalbahr** [comment]
```console
% brew dr
Your system is ready to brew.
% brew bump hwloc
==> hwloc
Current formula version:  2.9.2
Latest livecheck version: 2.9.2
Latest Repology version:  2.9.3
Open pull requests:       hwloc 2.9.3 (https://github.com/Homebrew/homebrew-core/pull/151735)
Closed pull requests:     none
% brew livecheck hwloc
hwloc: 2.9.2 ==> 2.9.2
% brew livecheck -v hwloc
hwloc: 2.9.2 ==> 2.9.2
% brew livecheck -d hwloc
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/h/hwloc.rb

Formula:          hwloc
Livecheckable?:   Yes

URL:              https://www.mail-archive.com/hwloc-announce@lists.open-mpi.org/
Strategy:         PageMatch
Regex:            /[\s,>]v?(\d+(?:\.\d+)+)(?:\s*?,|\s*?released)/i

Matched Versions:
2.9.2, 2.9.1, 2.7.2, 2.9.0, 2.8.0, 2.7.1, 2.7.0, 2.6.0, 2.5.0, 2.4.1, 2.4.0, 2.3.0, 2.2.0, 2.1.0, 2.0.4, 1.11.13, 1.11.12, 2.0.3, 1.11.11, 2.0.2, 2.0.1, 1.11.10, 1.11.9, 1.11.8, 1.11.7, 1.11.6, 1.11.5, 1.11.4, 1.11.3, 1.11.2, 1.11.1, 1.10.1, 1.9.1, 1.9, 1.8.1, 1.8, 1.7.2, 1.7.1, 1.7, 1.5.2, 1.4.3, 1.3.3, 1.6.2, 1.6.1, 1.6, 1.5.1, 1.5, 1.4.2, 1.4.1, 1.3.2, 1.4, 1.3.1, 1.3, 1.2.2, 1.2.1, 1.2, 1.1.2, 1.1.1, 1.1, 1.0.3, 1.0.2, 1.0.1, 1.0, 0.9.3, 0.9.2

hwloc: 2.9.2 ==> 2.9.2
```

---

https://github.com/Homebrew/homebrew-core/blob/26a320bba4447303bf834c8141281d450b5b509c/Formula/h/hwloc.rb#L8-L11

I am not very well-versed on regex, but I hope the debug output above helps.

Quick guess: could the `rc` be what's preventing the detection?

```console
% curl -s https://www.mail-archive.com/hwloc-announce@lists.open-mpi.org/ | grep '2.9.2'
<span class="subject"><a name="00157" href="msg00157.html">[hwloc-announce] hwloc 2.9.2rc1 released</a></span>
<span class="subject"><a name="00158" href="msg00158.html">[hwloc-announce] hwloc 2.9.2 released</a></span>
% curl -s https://www.mail-archive.com/hwloc-announce@lists.open-mpi.org/ | grep '2.9.3'
<span class="subject"><a name="00159" href="msg00159.html">[hwloc-announce] hwloc 2.9.3rc1 released</a></span>
<span class="subject"><a name="00160" href="msg00160.html">Re: [hwloc-announce] hwloc 2.9.3rc1 released</a></span>
<span class="subject"><a name="00161" href="msg00161.html">Re: [hwloc-announce] hwloc 2.9.3rc1 released</a></span>
```

**Comment by osalbahr** [comment]
@bgoglin would you suggest switching to using https://www.open-mpi.org/software/hwloc/current/downloads/latest_snapshot.txt for detection? i.e.
```console
% brew livecheck -d hwloc
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/h/hwloc.rb

Formula:          hwloc
Livecheckable?:   Yes

URL:              https://www.open-mpi.org/software/hwloc/current/downloads/latest_snapshot.txt
Strategy:         PageMatch
Regex:            /(\d+\.\d+\.\d+)/

Matched Versions:
2.9.3

hwloc: 2.9.2 ==> 2.9.3
```

**Comment by bgoglin** [comment]
> @bgoglin would you suggest switching to using https://www.open-mpi.org/software/hwloc/current/downloads/latest_snapshot.txt for detection? i.e.

Oh now I understand, you were parsing the email subjects in the announce list to find releases, this will likely break quite often (the subject pattern already changed in the past, sometimes I forget to fix the release number after copy-paste, sometimes I releases two versions in a single email, sometimes I just reply to the RC announce without changing the subject).

Yes please switch to latest_snapshot.txt which was exactly designed for this (but I think I should make it more visible in the main project page).

**Comment by bgoglin** [comment]
> > @bgoglin would you suggest switching to using https://www.open-mpi.org/software/hwloc/current/downloads/latest_snapshot.txt for detection? i.e.
> 
> Oh now I understand, you were parsing the email subjects in the announce list to find releases, this will likely break quite often (the subject pattern already changed in the past, sometimes I forget to fix the release number after copy-paste, sometimes I releases two versions in a single email, sometimes I just reply to the RC announce without changing the subject).
> 
> Yes please switch to latest_snapshot.txt which was exactly designed for this (but I think I should make it more visible in the main project page).

By the way, that URL will report 2.9.4rc1 when available. If you have something automatically updating and you don't want release candidates, you should filter-out anything ending with rc[0-9]+

**Comment by SMillerDev** [comment]
> By the way, that URL will report 2.9.4rc1 when available. If you have something automatically updating and you don't want release candidates, you should filter-out anything ending with rc[0-9]+

But that means there won't be any results when there is an RC available. Is there no endpoint that always reports the latest stable version?

**Comment by bgoglin** [comment]
I am working on adding another URL that doesn't include RC, but it's quite hard to test because of the PHP/AWS logic in the back.

Fortunately, there's usually several months between releases, and one week only with a RC. So the chances of hitting the RC case are low.

**Comment by bgoglin** [comment]
There's now https://www.open-mpi.org/software/hwloc/current/downloads/latest_release.txt for the latest release, not including prerelease candidates, etc.

**Comment by SMillerDev** [comment]
Thanks a lot @bgoglin !

**Comment by SMillerDev** [comment]
Updated the livecheck so now it should be good to go.

**Review by SMillerDev — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
