### PR TITLE
cairomm@1.14: update livecheck

### PR DESCRIPTION
**Pull request by chenrui333**
---

Follow up of #65531

### CODE REVIEW

**Comment by Rylan12** [comment]
If you're making `cairomm@1.14` keg-only, it should also be removed from the [`versioned_keg_only_allowlist`](https://github.com/Homebrew/homebrew-core/blob/master/audit_exceptions/versioned_keg_only_allowlist.json)

**Comment by fxcoudert** [comment]
poke @tschoonj because I think there's a good reason this was not made keg-only

**Comment by tschoonj** [comment]
Yep, there's no reason to make this keg only. It doesn't conflict with cairomm.

**Comment by fxcoudert** [comment]
@tschoonj actually we have more trouble with the new cairomm. Some broken linkages have been introduced, for example in graph-tool: https://github.com/Homebrew/homebrew-core/pull/65855

You'll see a bunch of cairomm-related failures in https://github.com/Homebrew/homebrew-core/pull/65763/checks?check_run_id=1464473235

The reason why they weren't flagged in the cairomm PR is (I think) because we had a bug in brew: https://github.com/Homebrew/brew/issues/9321
which has since been corrected: https://github.com/Homebrew/brew/pull/9322

We would need to check the cairomm dependents (and recursive dependents)

**Comment by tschoonj** [comment]
Yeah looks like `prefixsuffix`, `gsmartcontrol` and `pcb2gcode` could do with a rebuild. Would you like me to take care of that?

**Comment by fxcoudert** [comment]
@tschoonj if you can that'd be perfect, I'm short on time right now

**Comment by tschoonj** [comment]
See #65878

**Pull request merged**
