### PR TITLE
hashlink 1.12

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Maybe due to https://github.com/HaxeFoundation/hashlink/commit/880b81d4e49817f69c67131e501ff4874c4fadf8

Looks like upstream bundles `pcre`. The Makefile was refactored with variable `PCRE_INCLUDE` but the actual variable used is `PCRE_FLAGS`

**Comment by tobil4sk** [comment]
I tried to create a PR for this update but `brew bump-formula-pr` redirected me here.

The make file issue is indeed as diagnosed above, so until the next version is released (which probably won't be for a while), the best solution would be to fix it manually. Also, a bunch of the other patches can now be removed because with 1.12, the rpath issues they were trying to address have been resolved. Just requires setting the prefix for both make commands.

```ruby
def install
  inreplace "Makefile", /PCRE_INCLUDE =/, "PCRE_FLAGS ="
  system "make", "PREFIX=#{libexec}"
  system "make", "install", "PREFIX=#{libexec}"
  bin.install_symlink Dir[libexec/"bin/*"]
end
```

**Comment by chenrui333** [comment]
@tobil4sk adopted your build update.

**Comment by tobil4sk** [comment]
Thanks! After a conversation in #99237, it would seem that adding the rpath to the libraries is still necessary, so this should address that issue:

```ruby
def install
  # For Linux, also set RPATH in LIBFLAGS, so that the linker will also add the RPATH to .hdll files.
  inreplace "Makefile", "LIBFLAGS =", "LIBFLAGS = -Wl,-rpath,${INSTALL_LIB_DIR}"
  inreplace "Makefile", /PCRE_INCLUDE =/, "PCRE_FLAGS ="
  system "make", "PREFIX=#{libexec}"
  system "make", "install", "PREFIX=#{libexec}"
  bin.install_symlink Dir[libexec/"bin/*"]
end
```

**Comment by tobil4sk** [comment]
Hm, looking at the other errors, perhaps setting the rpath for the main executables is still necessary for now on macos.

**Comment by tobil4sk** [comment]
So maybe something like this is needed until the makefile is fixed:

```ruby
def install
  # For Linux, also set RPATH in LIBFLAGS, so that the linker will also add the RPATH to .hdll files.
  inreplace "Makefile", "LIBFLAGS =", "LIBFLAGS = -Wl,-rpath,${INSTALL_LIB_DIR}" if os.linux?
  inreplace "Makefile", /PCRE_INCLUDE =/, "PCRE_FLAGS ="

  if os.mac?
    # make file doesn't set rpath on mac yet
    system "make", "PREFIX=#{libexec}", "EXTRA_LFLAGS=-Wl,-rpath,#{libexec}/lib"
  elsif os.linux?
    system "make", "PREFIX=#{libexec}"
  end

  system "make", "install", "PREFIX=#{libexec}"
  bin.install_symlink Dir[libexec/"bin/*"]
end
```

**Comment by chenrui333** [comment]
let's give it another run

**Comment by chenrui333** [comment]
Also @tobil4sk, feel free to submit a new PR.

**Comment by tobil4sk** [comment]
> let's give it another run
> Also @tobil4sk, feel free to submit a new PR.

Alright, thanks! I might do that just to check that the `-rpath` line is 100% necessary on macOS or whether we can just get rid of that if block.

**Comment by tobil4sk** [comment]
I've opened #113509.

**Comment by chenrui333** [comment]
Thanks @tobil4sk!

**Pull request closed without merging**
