### PR TITLE
vamp-plugin-sdk: upstream Linux test fix

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
It looks like this is also blocked by https://github.com/Homebrew/brew/issues/11705.

**Comment by cho-m** [comment]
This is a possibly more annoying curl issue. Unlike the XIPH/TLS1.3+ issue, this formula hits an SSL certificate verification issue.
```
==> Downloading https://code.soundsoftware.ac.uk/attachments/download/2691/vamp-plugin-sdk-2.10.0.tar.gz
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html
```

---

On macOS, system curl is fine but brewed curl actually hits the same issue.

---

On Linux docker, both system curl and brewed curl hit issue:
```console
# /usr/bin/curl https://code.soundsoftware.ac.uk/attachments/download/2691/vamp-plugin-sdk-2.10.0.tar.gz
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.


# .linuxbrew/opt/curl/bin/curl https://code.soundsoftware.ac.uk/attachments/download/2691/vamp-plugin-sdk-2.10.0.tar.gz
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by cho-m** [comment]
Added Debian source as mirror to get build/test to pass.

Not sure how curl failure can be resolved:
```
Error: 2 failed steps!
brew livecheck vamp-plugin-sdk --full-name --debug
brew audit vamp-plugin-sdk --online --git --skip-style
```

**Comment by SMillerDev** [comment]
I guess the certificate is too new/old or something? I don't really know what we could do about that.

**Comment by iMichka** [comment]
I’ve sent upstream an email about the certificate error. 

Can we host the source file ourselves?

**Comment by cho-m** [comment]
Looks like Void Linux hit same issue back in May: https://github.com/void-linux/void-packages/issues/31161

We could merge bottles as-is and accept audit/livecheck failures for now.

If we want to pass CI, then we would need to:
- swap url with the mirror (I used Debian. Ubuntu and NetBSD also have a copy)
- change livecheck to another site. The problem is finding one:
   - Homepage lists old version so not reliable: https://www.vamp-plugins.org/develop.html
   - Using a distro FTP/server is probably not accurate due to their own local revision updates.
   - Not entirely sure if official, but there is a GitHub https://github.com/c4dm/vamp-plugin-sdk which seems to have related org/contributor. However, the version numbering is not the same (2.10 vs 2.10.0) and it isn't linked in official site.

**Review by samford — DISMISSED** [review]
I've been maintaining a soft guideline of not using Debian in `livecheck` blocks but this idea came about because most of the related formulae I've seen are using a Debian `stable` archive because the first-party source has disappeared (i.e., there won't be new versions). I've left those alone for the time being and eventually I'll make a decision about whether to automatically skip formulae with a Debian `stable` URL (this can be overridden by a `livecheck` block, when appropriate). [We already do this for `stable` URLs from Internet Archive, Google Code Archive, etc.]

`vamp-plugin-sdk` was most recently updated on 2020-05-18, so it makes sense to check for new versions in this specific context. As long as we have an explanatory comment, I'm okay checking Debian here until the certificate issues on the first-party site are resolved. Just to be clear, this is a one-off exception and the soft guideline of not creating Debian `livecheck` blocks remains for now.

The `livecheck` block `url` and `regex` here are correct and we just need to move the explanatory comment before the `livecheck` block (I've added suggestions for this).

**Review by cho-m — APPROVED** [review]

**Pull request merged**
