### PR TITLE
adam: migrate from homebrew-science

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Companion PR: https://github.com/Homebrew/homebrew-science/pull/6339

**Comment by ilovezfs** [comment]
looks like it should be bottle :unneeded

**Comment by ilovezfs** [comment]
5 installs in the last 30 days, so going to pass on this one.

**Comment by iMichka** [comment]
What would be an acceptable number of downloads? Just that I do not loose my time migrating stuff from science to core (see https://github.com/Homebrew/homebrew-science/issues/6331)

**Comment by ilovezfs** [comment]
Let's say >=50 in the last 90 days.

**Comment by iMichka** [comment]
Ok I'll add the download stats as comments to the migration list, this will filter out a good part of it.

**Comment by heuermh** [comment]
How about pinging the formulae authors for feedback?

The last ADAM release was in April and we have another one coming up here in January.  On such long release cycles interest will wane, users have the latest release or are on HEAD.

We'd like to migrate to core, can this pull request be reopened, or should I create a new one?

**Comment by iMichka** [comment]
> How about pinging the formula authors for feedback?

In a perfect world, yes, but we are around 2-3 active maintainers, and I do not see how we could have contacted 500 persons in our free time :)

Before opening a new pull request I think the best is to discuss this with @ilovezfs , to see if the formula can be added; but as the downloads are rare I am not sure this will work out.

**Comment by heuermh** [comment]
That is what is frustrating about homebrew-science being shut down.  There aren't a hundred thousand people in the world interested in doing genomics on Apache Spark.  But there are some and it should be easy for them to find the tap with our formula in it.  Our formula has been well maintained and we are committed to maintaining it going forward.

**Comment by ilovezfs** [comment]
@heuermh see https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap

**Comment by heuermh** [comment]
@ilovezfs We would like to have our formula included in core.

**Comment by ilovezfs** [comment]
@heuermh is it packaged by Debian?

**Comment by heuermh** [comment]
> @heuermh is it packaged by Debian?

No.  I had committer access at Debian Med at one point, so we could probably make it happen.  We depend on Apache Spark, so that would also need to be in Debian.  Why do you ask?

**Comment by ilovezfs** [comment]
@heuermh see https://github.com/Homebrew/homebrew-science/issues/6331#issuecomment-331441501

**Pull request closed without merging**
