### PR TITLE
gperftools: prevent operator delete build failure

### PR DESCRIPTION
**Pull request by ilovezfs**
Reverts upstream commit
  build sized delete aliases even when sized-delete is disabled
  https://github.com/gperftools/gperftools/commit/782165fa7f2c49d6a67c2415626a1f215cc21ac2

Prevents

```
  Undefined symbols for architecture x86_64:
    "operator delete(void*, unsigned long)", referenced from:
        ProcMapsIterator::~ProcMapsIterator() in libsysinfo.a(sysinfo.o)
        ProcMapsIterator::~ProcMapsIterator() in libsysinfo.a(sysinfo.o)
        tcmalloc::FillProcSelfMaps(char*, int, bool*) in libsysinfo.a(sysinfo.o)
        tcmalloc::DumpProcSelfMaps(int) in libsysinfo.a(sysinfo.o)
```

Workaround for https://github.com/gperftools/gperftools/issues/794

### CODE REVIEW

**Comment by ilovezfs** [comment]
Mainly intend to trigger CI, since it seems to be determined to fail locally despite the existence of bottles.

**Comment by ilovezfs** [comment]
So it appears the regression is limited to El Capitan. This is the same error I was getting locally.

If anyone can test with El Capitan + Xcode 7.2 that might narrow it down some.

**Comment by ilovezfs** [comment]
Issue reported upstream: https://github.com/gperftools/gperftools/issues/794

**Comment by mikemcquaid** [comment]
Thanks!

**Comment by ilovezfs** [comment]
Filtering out -fsized-deallocation fixes this. With Xcode 7.2.1 this is detected by gperftools configure as unsupported, whereas with Xcode 7.3 it is detected as supported. I'm not sure what the real bug is, but that is the proximate cause of the build failure.

The same failure occurs if I build outside of brew.

@mistydemeo Any idea if there's some flags that can be set in superenv or in the formula to fix this properly, or do we just need to filter out -fsized-deallocation in superenv?

**Comment by ilovezfs** [comment]
@mikemcquaid :ship:?

**Comment by mikemcquaid** [comment]
👍

**Pull request closed without merging**
