### PR TITLE
klee 2.3

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
This is split off from #99064.

**Comment by danielnachun** [comment]
Add in a do not merge label here until https://github.com/Homebrew/homebrew-core/pull/97618 is done running, as it is revision bumping `klee`.

**Comment by iMichka** [comment]
> klee contains conflicting version recursive dependencies:
        python@3.10, python@3.9

Actually I can't migrate klee right away due to llvm and python tabulate ...

**Comment by iMichka** [comment]
@danielnachun I thought that you wanted to migrate klee first: https://github.com/Homebrew/homebrew-core/pull/99064#issuecomment-1162437599

**Comment by danielnachun** [comment]
I didn't start that CI run but now that it's already going we should just wait to update this.  We'll have to see if `klee` 2.3 supports LLVM 14, and have it use `llvm@13` if does not.

**Comment by cho-m** [comment]
May be easier to just get `llvm@13`. Not sure if `klee` has support for LLVM 14. There is an open PR https://github.com/klee/klee/pull/1477

**Review by danielnachun — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]
LGTM; thanks @iMichka!

**Review by carlocab — CHANGES_REQUESTED** [review]
This is `automerge-skip` because 7c8ed707841bc5c158e856aeb4798eb3bced4772 modifies two formulae. Can you split that into separate commits?

But beyond that this is fine.

**Review by cho-m — DISMISSED** [review]
Should be good to merge. Can try fixing Apple Silicon later by patching https://github.com/klee/klee/commit/885997a9841ab666ccf1f1b573b980aa8c84a339

**Review by carlocab — APPROVED** [review]
Ok, commits fixed.

**Comment by cho-m** [comment]
Looks like same Big Sur CI runner issue as #104823 where audit is taking over 1 hour.

**Pull request closed without merging**
