### PR TITLE
ocaml 4.09.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
looks like git checkout issue.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
23:34:30 ==> ./configure --prefix=/usr/local --enable-debug-runtime --mandir=/usr/local/Cellar/ocaml/4.09.0/share/man --disable-graph-lib
23:34:30 configure: Configuring OCaml version 4.09.0
23:34:30 checking build system type... x86_64-apple-darwin18.7.0
23:34:30 checking host system type... x86_64-apple-darwin18.7.0
23:34:30 checking target system type... x86_64-apple-darwin18.7.0
23:34:30 configure: error: The graphics library is no longer distributed with OCaml since version 4.09. It is now distributed as a separate "graphics" package: https://github.com/ocaml/graphics
23:34:30

**Comment by imbsky** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
