### PR TITLE
newsboat 2.29

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Minoru** [comment]
Hi, Newsboat maintainer here :wave: The build failure on macOS is because of an old GNU Make that Apple ships. Just install `gmake` from Homebrew, and it should work fine (as checked by Newsboat's CI).

**Comment by Porkepix** [comment]
Added `coreutils`, there's still an error, but I'm not seeing what's the issue.

**Comment by Porkepix** [comment]
Also, https://github.com/Homebrew/homebrew-core/actions/runs/3157438182

**Comment by Minoru** [comment]
coreutils is unrelated to this build failure, because it doesn't contain GNU Make. Instead, you have to install the  "make" package — that's what I did in Newsboat's CI and what fixed the issue for me. You also have to invoke `gmake` instead of `make`, but I don't know enough about Homebrew's recipes to provide concrete guidance on that.

**Comment by chenrui333** [comment]
#113404

**Pull request closed without merging**
