### PR TITLE
terraform 0.6.15

### PR DESCRIPTION
**Pull request by bsiegel**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

Update terraform to v0.6.15

### CODE REVIEW

**Comment by bsiegel** [comment]
I still have no idea how to properly update the `go_resource` stanzas here. I tried using `gdm brew` but there were way more deps than are currently listed in the formula, and they all had the exact same hash. If someone could lend a hand and show me what I'm doing wrong that'd be awesome. Thanks!

**Comment by DomT4** [comment]
Can you provide that `gdm brew` output?

**Comment by bsiegel** [comment]
@DomT4 I believe I had my GOPATH messed up before - here's what I get now:

```
======= Go Dependency Manager =======
= working dir: /Users/brandon/Downloads/gopath/src/github.com/hashicorp/terraform
= GOPATH:      /Users/brandon/Downloads/gopath
=====================================

  go_resource "github.com/hashicorp/terraform" do
    url "https://github.com/hashicorp/terraform.git",
    :revision => "0c5c54e7b6a59d77e89ce24057509503639d8d3d"
  end
```

**Comment by nicolai86** [comment]
@bsiegel following the changes in the `Godeps.json` for tag `v0.6.15` I think you should upgrade `github.com/aws/aws-sdk-go` to `6876e9922ff299adf36e43e04c94820077968b3b`, and `github.com/golang/protobuf` to `34a5f244f1c01cdfee8e60324258cfbb97a42aec`, too.

**Comment by DomT4** [comment]
Looking over the upstream repo I'm not sure if we should be using resources here at all anymore. Maybe switching to use `godep` would work best? I'm not sure.

**Comment by nicolai86** [comment]
@DomT4 godeps alone should be worth a shot, yup.

**Comment by bsiegel** [comment]
Closing in favor of #590

**Pull request closed without merging**
