### PR TITLE
sysdig 0.10.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
If you're feeling kind, `test do` is badly written & `share/demos` should probably be `pkgshare/demos` but otherwise 👍.

**Comment by ilovezfs** [comment]
domitus

**Comment by DomT4** [comment]
Even people not suffering with the unfortunate domitus can hopefully notice the test is kind of messily written compared to our usual standard 😇.

**Comment by ilovezfs** [comment]
Yes, it's awful, but you gave me an opening :)

**Comment by DomT4** [comment]
😄, I aim to please!

**Comment by ilovezfs** [comment]
@DomT4 Better?
```
  test do
    system bin/"sysdig", "-cl"

    expected = <<-EOS.undent.tr("\n", " ")
      1 20:08:16.115840886 1 sysdig (3532) < open
      fd=5(<f>/tmp/sysdig/sample.scap)
      name=sample.scap(/tmp/sysdig/sample.scap)
      flags=262(O_TRUNC|O_CREAT|O_WRONLY)
      mode=0
    EOS

    file = pkgshare/"demos/sample.scap"
    filter = "evt.type=open and evt.arg.name contains /tmp/sysdig/sample.scap"
    output = shell_output("#{bin}/sysdig -r #{file} \"#{filter}\"")
    assert_equal expected, output.chomp
  end
```

**Comment by DomT4** [comment]
As good as it's going to get I suspect 👍.

**Comment by ilovezfs** [comment]
@DomT4 it could be simplified if we just use assert_match and a substring so like
```
assert_match "/tmp/sysdig/sample.scap", output.chomp
```
Probably no need to match the exact, full output, since if it's broken, it will likely die in an obvious ball of flames.

**Comment by ilovezfs** [comment]
In fact even this will work:
```
    system bin/"sysdig", "-cl"
    output = shell_output("#{bin}/sysdig -r #{pkgshare}/demos/sample.scap")
    assert_match "/tmp/sysdig/sample", output
```
and I'm not sold that `system bin/"sysdig", "-cl"` if we're doing the other check. So how about:
```
    output = shell_output("#{bin}/sysdig -r #{pkgshare}/demos/sample.scap")
    assert_match "/tmp/sysdig/sample", output
```
and declare victory

**Comment by ilovezfs** [comment]
@DomT4 of course we actually have a bigger problem with this formula which is that cmake seems to be downloading some other nonsense in the middle of the build :(

**Comment by ilovezfs** [comment]
```
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='/tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses-6.0-20150725.tgz'
-- Downloading... done
cd /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src && /usr/local/Cellar/cmake/3.6.0/bin/cmake -P /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses-stamp/verify-ncurses.cmake
cd /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src && /usr/local/Cellar/cmake/3.6.0/bin/cmake -P /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses-stamp/extract-ncurses.cmake
-- extracting...
     src='/tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses-6.0-20150725.tgz'
     dst='/tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
cd /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src && /usr/local/Cellar/cmake/3.6.0/bin/cmake -E touch /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses-stamp/ncurses-download
[ 84%] No patch step for 'ncurses'
[ 86%] No update step for 'ncurses'
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E echo_append
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E echo_append
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E touch /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses-stamp/ncurses-patch
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E touch /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses-stamp/ncurses-update
[ 87%] Performing configure step for 'ncurses'
cd /tmp/sysdig-20160710-41096-1a59w0o/sysdig-0.10.1/build/ncurses-prefix/src/ncurses && ./configure --without-cxx --without-cxx-binding --without-ada --without-manpages --without-progs --without-tests --with-terminfo-dirs=/etc/terminfo:/lib/terminfo:/usr/share/terminfo
checking for egrep... grep -E
```

How did this thing pass review lol

**Comment by DomT4** [comment]
Welp. That's just great, real great. Can you see if we can hack that out somehow? Downloads during build processes are the 👿.

**Comment by ilovezfs** [comment]
@DomT4 it makes me want to disable networking in the sandbox.

**Comment by DomT4** [comment]
Sadly the list of exemptions would be ridiculous. Anything Node, Python, Cabal, Opam, Maven, Gradle, etc. Sure I'm forgetting some even on top of that list.

**Comment by ilovezfs** [comment]
Yup, but perhaps anything that doesn't declare one of those could be unplugged by default.

**Comment by ilovezfs** [comment]
@DomT4 PR  refreshed.

**Comment by MikeMcQuaid** [comment]
@ilovezfs I tried that once before and it was a bit of a nightmare even for stuff that didn't use networking. That said, I'd love you to give it a go as I do think making networking opt-in (or in `fetch do`) would be an improvement.

**Comment by ilovezfs** [comment]
@MikeMcQuaid Do you recall any of the pitfalls for stuff that didn't use networking?

Also, I suppose even if it doesn't work out via the sandbox specifically and it's also not feasible to regulate it in some other way, it might be worthwhile to find some way to at least log the network access emanating from a particular brew install.

**Comment by MikeMcQuaid** [comment]
@ilovezfs I can't really recall much except I think `fetch` occurs in the same sandbox which made things difficult and it's hard to just block outgoing networking and not e.g. loopback or even TCP unix sockets.

**Comment by ilovezfs** [comment]
Ah ok. That's surprising that fetch would be in the same sandbox.

**Comment by DomT4** [comment]
@ilovezfs This PR itself LGTM if you're happy :shipit:.

**Pull request closed without merging**
