### PR TITLE
mono-4.6.2.7, fsharp 4.0.1.20

### PR DESCRIPTION
**Pull request by mfilippov**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by apjanke** [comment]
This should probably include a revision bump to the `mono` formula, since it changes the resulting installation. (And that way it'll be picked up by a `brew upgrade`.)

**Comment by mfilippov** [comment]
Ok, it's PR can be delayed until mono bump version. I think it's should be soon.

**Comment by mfilippov** [comment]
I updated new stable mono and fsharp.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `mono 4.6.27`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
