### PR TITLE
yle-dl 20221015

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Strange that `brew bump` didn't used the full version number for the commit while it did for the PR's title. An explanation for this?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> Strange that `brew bump` didn't used the full version number for the commit while it did for the PR's title. An explanation for this?

you mean `brew bump --open-pr` did not set the message correctly?

**Comment by chenrui333** [comment]
I can actually see the commit message correctly in my local though

```
commit 7c75d9d7032fb8bbadfbdd8d2f2bd018d92142c5 (HEAD -> bump-yle-dl-20221015)
Author: Porkepix <porkepix@gmail.com>
Date:   Sat Oct 15 12:04:00 2022 +0200

    yle-dl 20221015
```

**Comment by Porkepix** [comment]
> I can actually see the commit message correctly in my local though
> 
> ```
> commit 3297fe067a10c8c5da606cfbc7d2b07806922940 (HEAD -> bump-yle-dl-20221015, Porkepix/bump-yle-dl-20221015)
> Author: xxx
> Date:   xxx
> 
>     yle-dl 20221015
> ```

Some strange GitHub behavior, then?

**Pull request closed without merging**
