### PR TITLE
logstash: move config files into etc

### PR DESCRIPTION
**Pull request by StudioMaX**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
What is the actual problem this is trying to fix?

**Comment by StudioMaX** [comment]
When updating between versions the config files will be lost, for example.
old: `/usr/local/Cellar/logstash/6.2.0/libexec/config`
new: `/usr/local/Cellar/logstash/6.4.1/libexec/config`
With this change the config files of logstash will be located here: `/usr/local/etc/logstash`

**Comment by StudioMaX** [comment]
Still relevant.

**Comment by fxcoudert** [comment]
Thanks @StudioMaX

**Pull request merged**
