### PR TITLE
pgcli 2.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by StephenBrown2** [comment]
This should probably hold off on being merged until https://github.com/dbcli/pgspecial/pull/83 gets merged into pgspecial and a new release is cut, then bump the resource: https://github.com/chenrui333/homebrew-core/blob/pgcli-2.2.0/Formula/pgcli.rb#L45-L48

**Comment by mlarraz** [comment]
Looks like that PR was released already. I was about to open a PR to upgrade when I found this one. Here's my commit anyway (https://github.com/Homebrew/homebrew-core/commit/54b50a5c760701994c084fc2f497c97ed0706137) as it contains the relevant URL and SHA256 for pgspecial

**Comment by surprisetalk** [comment]
It looks like https://github.com/dbcli/pgspecial/pull/83 is merged -- anything I can do to help here?

**Comment by chenrui333** [comment]
I will take a look today. Thanks for the info.

**Comment by chenrui333** [comment]
Should be good now, tested locally on my Catalina machine.

**Pull request closed without merging**
