### PR TITLE
python: update resources

### PR DESCRIPTION
**Pull request by wifijanitor**
- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Update to current versions of pip, wheel and setuptools.
This is in relation to [43867](https://github.com/Homebrew/homebrew-core/issues/43867)

### CODE REVIEW

**Comment by wifijanitor** [comment]
@fxcoudert thank you for catching the "revision" on line 6, I was looking for a version/ver and missed that.

For the naming, should it have just been "python update resources"? I was trying to follow point 6 of [Pull Request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request)

**Comment by fxcoudert** [comment]
`doitlive` and `sip` also require a revision bump (each one in its separate commit, please)

**Comment by wifijanitor** [comment]
doitlive appears to already be pulling the latest version of 4.3.0 from what I can see on pypi.

I was able to see that sip had a new version, I updated sip to pull 5.0.0

**Comment by fxcoudert** [comment]
I think you have push a lot of new unrelated commits to this PR, probably when trying to rebase on top of the master branch. I've tried a clean PR with the same content (and revision bumps) in #45222

**Pull request closed without merging**
