### PR TITLE
curl: switch to tar.xz, add canonical github mirror

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'd prefer not to add a second mirror or change the mirror as that will make it impossible to maintain with bump-formula-pr and we need the non-https mirror.

**Comment by ilovezfs** [comment]
Going to pass on this PR since this is a key formula for bootstrapping on earlier versions of macOS and I don't think we want to make xz a dependency for that, but thanks!

**Comment by vszakats** [comment]
Ok!

**Comment by vszakats** [comment]
(a short comment about this and the reason for using an HTTP mirror could be nice here - I saw the latter in the history, but the former is easy to miss.)

**Pull request closed without merging**
