### PR TITLE
parquet-tools 1.12.2

### PR DESCRIPTION
**Pull request by shanielh**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Thanks @shanielh for your first contribution!

**Comment by shanielh** [comment]
> Thanks @shanielh for your first contribution!

Sure! Happy to help, seems like this didn't help me and I'm going to have to wait for them to release 1.13.0 😭

**Comment by iMichka** [comment]
By the way this formula is deprecated.

The comment in the code links to https://issues.apache.org/jira/browse/PARQUET-1666. Is this still the case? From our side deprecation means the formula might get be deleted one day ...

**Comment by shanielh** [comment]
> By the way this formula is deprecated.
> 
> The comment in the code links to https://issues.apache.org/jira/browse/PARQUET-1666. Is this still the case? From our side deprecation means the formula might get be deleted one day ...

Yes, it will not be in 1.13, instead, people should migrate to `parquet-cli`

**Pull request closed without merging**
