### PR TITLE
argo 2.12.2

### PR DESCRIPTION
**Pull request by alexec**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
see previous attempt, #67080

**Comment by alexec** [comment]
I don't have the first clue on how to fix that issue.

**Comment by chenrui333** [comment]
```
/bin/sh: SHELLOPTS: readonly variable
/bin/sh: SHELLOPTS: readonly variable
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/private/tmp/argo-20201218-47419-5nbin4/ui/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/15.4.0/bin/node" "/private/tmp/argo-20201218-47419-5nbin4/ui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /private/tmp/argo-20201218-47419-5nbin4/ui/node_modules/node-sass
gyp ERR! node -v v15.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [ui/dist/app/index.html] Error 1
```

**Comment by chenrui333** [comment]
yeah, same issue as before.

**Comment by alexec** [comment]
```
Alex Collins:speech_balloon: Today at 10:54 AM
is anyone familiar with Brew and NodeJS and can help with this error? https://github.com/Homebrew/homebrew-core/pull/67080

simster7simster7
#67080 argo 2.12.1
Created with brew bump-formula-pr.
Labels
build failure, go, nodejs
Comments
2
<https://github.com/Homebrew/homebrew-core|Homebrew/homebrew-core>Homebrew/homebrew-core | Yesterday at 4:42 PM | Added by GitHub




6 replies

Josh Soref  4 hours ago
https://github.com/Automattic/node-canvas/issues/822

kurisubrookskurisubrooks
#822 "./util/has_lib.sh freetype" returned exit status 0 in Canvas 1.6.0
After updating to 1.6.0 on Ubuntu 16.04, i'm now recieving the following error:
$ npm i canvas

> canvas@1.6.0 install /home/kurisu/sherlock/node_modules/canvas
> node-gyp rebuild

Show more
Comments
15
<https://github.com/Automattic/node-canvas|Automattic/node-canvas>Automattic/node-canvas | Oct 20th, 2016 | Added by GitHub

Alex Collins:speech_balloon:  4 hours ago
any thoughts on a fix?

Daniel Herman  4 hours ago
We might want to consider migrating to dart-sass which provides a pure JS implementation of sass going forward - have always found things that use node-gyp to be painful to use for reason like this when compilation is actually needed

Daniel Herman  3 hours ago
The version of node-sass in use does not have pre-built bindings for Node 15 which I think is being used here, that's why it's failing (I'm not that familiar with brew)

Daniel Herman  3 hours ago
You can either lock Node to 14 if possible, or upgrade node-sass to 5.0.0 which does have node 15 bindings pre-built

Alex Collins:speech_balloon:  2 hours ago
@Daniel Herman would you be able to help fix this? I think it might be beyond me
```

**Comment by alexec** [comment]
How to upgrade node-saas?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @alexec!

**Pull request closed without merging**
