### PR TITLE
ocaml 4.06.0

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
cc @ilovezfs

**Comment by JCount** [comment]
`coccinelle` is blocked on updating `camlp4`

**Comment by ilovezfs** [comment]
This will fix OPAM: https://github.com/Homebrew/homebrew-core/pull/20251

**Comment by ilovezfs** [comment]
This fixes the coccinelle test: https://github.com/Homebrew/homebrew-core/commit/5063c2c8564ca83fc74a8f6f8946af0e9b461abb

**Comment by ilovezfs** [comment]
This will fix lablgtk: https://github.com/Homebrew/homebrew-core/pull/20252

**Comment by ilovezfs** [comment]
This will fix ocamlsdl: https://github.com/Homebrew/homebrew-core/pull/20253

**Comment by ilovezfs** [comment]
:green_apple: but it seems to break a lot of the things with a build-time-only dependency so we may need to do some more surgery before merging.

**Comment by ilovezfs** [comment]
This gets `coq` building again: https://github.com/Homebrew/homebrew-core/pull/20255

**Comment by ilovezfs** [comment]
`ENV["OCAMLPARAM"] = "safe-string=0,_"` seems to make most problems go away. So I think we can ship this.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:cookie:

**Comment by ilovezfs** [comment]
- [ ] bibtex2html
- [ ] camlp4
- [ ] camlp5
- [ ] coccinelle
- [ ] compcert
- [ ] coq
- [ ] corectl
- [ ] docker-machine-driver-xhyve
- [ ] flow
- [ ] fstar
- [ ] haxe
- [ ] hevea
- [ ] infer
- [ ] lablgtk
- [ ] ledit
- [ ] menhir
- [ ] mldonkey
- [ ] ocamlbuild
- [ ] ocamlsdl
- [ ] one-ml
- [ ] opam
- [ ] ott
- [ ] pdfsandwich
- [ ] ssreflect
- [ ] unison
- [ ] unison@2.40
- [ ] zero-install

**Comment by shawwn** [comment]
Eh... 

@ilovezfs FWIW, ocaml 4.06.0 wreaks havoc when attempting to build haxe from source.

To build haxe: `make opam_install && make && make install`

This works fine on older ocaml versions, but 4.06.0 fails to install various libraries during the `make opam_install` step.

This fixes most of the problems:

`OCAMLPARAM="safe-string=0,_" make opam_install`

However, `opam install ptmap` still fails. I had to run `opam pin add ptmap path/to/my/monkeypatched/ptmap`  and fix the build issue in my local ptmap dir.

At that point haxe compiles successfully.

You can reproduce the issue:

```
brew install opam
brew unlink ocaml
opam switch 4.06.0
git clone https://github.com/HaxeFoundation/haxe
cd haxe
make opam_install # kaboom!
make && make install
```

Hope this helps!

**Comment by ilovezfs** [comment]
@shawwn yeah unsafe-string was enough for the current release version (see https://github.com/Homebrew/homebrew-core/commit/7f64c3156618832a1381169626b43522e7b05623) but I haven't tried HEAD for haxe. Did you submit your monkey-patch for ptmap upstream?

**Comment by shawwn** [comment]
Nah, it's horrible. I don't know ocaml at all, so I did the bare minimum hack to get it to compile:

```ocaml
let rec update x f = function
    Empty ->
      begin match f None with
      | None -> Empty
      | Some data -> add x data empty
      end
    | Leaf (k,j) as t -> t
    | Branch (p,m,t0,t1) as t -> t
```

If you put that into ptmap.ml, it compiles and all the tests pass. But that update function is obviously bogus. It doesn't actually update anything.

The compile error was due to the fact that ptmap.ml has no `update` function, so the above snippet is just a way to sidestep the problem.

That only works because apparently nothing calls `update`. So even though the functionality is bogus, haxe still built successfully.

Good enough for me :P I'm out of time, so someone else will have to carry this from here.

**Comment by ilovezfs** [comment]
CC @andyli have you hit the above issue yet?

**Comment by shawwn** [comment]
ah, I see.. https://github.com/Homebrew/homebrew-core/commit/7f64c3156618832a1381169626b43522e7b05623  you changed haxe's brew formula to set `OCAMLPARAM="safe-string=0,_"`.

Makes sense. It might be good to add that `OCAMLPARAM="safe-string=0,_"` trick to haxe's makefile instead.

**Comment by ilovezfs** [comment]
@shawwn well really it needs to be fixed so that it works with safe-string on :)

**Comment by shawwn** [comment]
good luck! :) You'll have to submit patches to 3 or 4 opam repos. e.g. `rope` fails to install without that safe-string workaround.

**Comment by ilovezfs** [comment]
@shawwn yeah the whole ecosystem is going to take time to catch up.

**Comment by avsm** [comment]
It's unfortunate that this got merged so quickly.  We're working hard on getting opam-repository to be compliant with safe-string, but it does take a few weeks to work through all the libraries.  In the meanwhile, upgrading to 4.06.0 does break users as a result.

**Comment by ilovezfs** [comment]
@avsm we merge stable versions of each package as soon as they're green for our CI.

**Comment by ilovezfs** [comment]
@avsm my suggestion would be that you ship an opam version 1.2.3 that sets `OCAMLPARAM="safe-string=0,_"` in the environment until such time as the opam repository is actually caught up.

**Pull request closed without merging**
