### PR TITLE
vcpkg 2021.12.01

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
just audit failure
```
  vcpkg:
    * Unexpected universal binaries were found.
      The offending files are:
        /usr/local/Cellar/vcpkg/2021.12.01/libexec/bin/vcpkg
```

@carlocab, maybe we just need to allowlist the universal binary exception?

**Comment by carlocab** [comment]
I'd rather not. We should work out first why it's building universal binaries, since that's a sure sign it's evading the shims.

**Comment by SMillerDev** [comment]
It seems to download a precompiled binary: https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.sh#L128-L144

**Comment by carlocab** [comment]
You can build it from source with CMake from https://github.com/microsoft/vcpkg-tool

**Pull request closed without merging**
