### PR TITLE
go 1.14.6

### PR DESCRIPTION
**Pull request by roopakv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by roopakv** [comment]
@Bo98 what is the best way to re-trigger the builds?

**Comment by SMillerDev** [comment]
Done

**Comment by roopakv** [comment]
seems like the failures are
- auditbeat
- berglas
- charm
- dashing
- docker2aci
- packetbeat
- wellington
- ship

@SMillerDev and @Bo98 do we need to go fix these packages first? what are the steps we follow now?

**Comment by SMillerDev** [comment]
If these are broken by the update they need to be reported and fixed.

**Comment by roopakv** [comment]
@SMillerDev afaik, they have been or are broken. wellington is an example that has been broken since 10.13.

dashing has a https cert error (this is new, but is unrelated to go 1.14.6)

**Comment by Bo98** [comment]
Looks like the Catalina build didn't complete.

There's also a merge conflict anyway. Can you rebase on master?

**Comment by roopakv** [comment]
@Bo98 done. before we triggered a restart Catalina did finish and it was the same packages. 

Merged master after fixing conflicts, hopefully we should have all builds complete with ~the same errors

**Comment by SMillerDev** [comment]
Please don't introduce merge commits. We keep our log to one commit per formula. If you want the newest changes you'll have to rebase.

**Comment by Bo98** [comment]
Bottle commits like 8c9d7544bef93d770989a8ec57db04c93a4c126b wouldn't get applied if we used GitHub's merge button.

**Comment by roopakv** [comment]
Failing formulae: 

- auditbeat
- berglas
- charm
- dashing
- gobuster
- grv
- heartbeat
- packetbeat
- ship
- wellington

I'm going to see which of them are existing issues and see if we can send fixes to the repos. @Bo98, curious if you know where we are painting the list of broken golang reps, the issue seems to be closed?

**Comment by chenrui333** [comment]
@roopakv previous upgrade failure tracker, #56539

**Comment by AnyCPU** [comment]
What should be done to make go 1.14.6 available for upgrade?
What should be done to decrease time needed to prepare a new release?

**Comment by SMillerDev** [comment]
Fix the build issues to get this migrated faster, and make sure that projects dependent on `go` have proper CI that'll catch these issues.

**Comment by Bo98** [comment]
Hi, sorry for the delay in responding here - I've been less active this week.

> @Bo98, curious if you know where we are painting the list of broken golang reps, the issue seems to be closed?

I believe #56539 is being used now.

I'll make this a priority to review tomorrow evening. I think it would be worthwhile rebasing in the meantime until then so I'm not reviewing unrelated breakages which have already been fixed.

**Comment by roopakv** [comment]
@Bo98 seems like godep is archived: https://github.com/tools/godep

do we remove godep in a separate PR? brew says there is a problem since repo is archived.

**Comment by SMillerDev** [comment]
You can mark it deprecated with a date in this one.

**Comment by roopakv** [comment]
@SMillerDev is that as simple as adding 
```
deprecate! date: "2020-07-28"
```
to the formula?

when i try running `brew audit Formula/godep.rb` i never see the github error. i tried updating brew and running with debug, seems like that check is always skipped. what am i missing?

**Comment by SMillerDev** [comment]
Yeah, although it should be the date that it was archived. `brew audit --online` will show this (since it needs to connect to github)

**Comment by roopakv** [comment]
@SMillerDev yeah i tried with --online and still no dice. not sure what i am missing

**Comment by SMillerDev** [comment]
Did you already mark it as deprecated? Because it will be skipped if you do. Otherwise you have something making brew audits ignore `--online`

**Comment by Bo98** [comment]
Thanks. I've gone through all that failed and have matched them up with existing issues or PRs, bar a couple which I'll open a separate PR to fix shortly.

Typically we do one commit per formula:

* `go 1.14.6`
* `godep: revision bump for go`

I've done that for you while merging.

**Comment by Bo98** [comment]
Merged as 33b25d5fa9dff51c5bb03b0d1f61aebd31f32113 and cf7ad5522119f3df7a7eb16d85d10c0b329c4838.

**Comment by roopakv** [comment]
thanks @Bo98 I'll keep that in mind for the future. I just copied what we did for 1.14.5

**Pull request closed without merging**
