### PR TITLE
gdbm 1.19

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Another attempt at #67539.

**Comment by SMillerDev** [comment]
Rbtools on ARM is an upstream issue.

**Comment by carlocab** [comment]
Mojave:

```
Error: 5 failed steps!
brew test --retry --verbose hyperkit
brew test --retry --verbose opencascade
brew test --retry --verbose rbtools
brew test --retry --verbose swift
brew test --retry --verbose wasm-pack
```

Catalina:

```
Error: 5 failed steps!
brew install --only-dependencies creduce
brew install --only-dependencies gitg
brew test --retry --verbose hyperkit
brew test --retry --verbose rbtools
brew test --retry --verbose wasm-pack
```

These look either spurious (e.g. `gitg` is is network error, `creduce` is an out-of-space error) or pre-existing.

**Comment by carlocab** [comment]
Big Sur:

```
Error: 12 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose aws-google-auth
brew test --retry --verbose creduce
brew test --retry --verbose hyperkit
brew install llvm@8
brew install --only-dependencies oclgrind
brew install oclgrind
brew install pypy
brew install pypy3
brew test --retry --verbose rbtools
brew fetch --retry root
brew test --retry --verbose wasm-pack
```

**Comment by carlocab** [comment]
Let's try to track these failures systematically:

| Formula         | ARM                | Big Sur            | Catalina           | Mojave             | Comment        |
| ---             | ---                | ---                | ---                | ---                | ---            |
| asuka           | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: | pre-existing   |
| aws-google-auth | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: |                |
| creduce         | :white_check_mark: | :x:                | :x:                | :white_check_mark: |                |
| gitg            | :white_check_mark: | :white_check_mark: | :x:                | :white_check_mark: |                |
| hyperkit        | :white_check_mark: | :x:                | :x:                | :x:                | pre-existing   |
| llvm@8          | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: |                |
| oclgrind        | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: |                |
| opencascade     | :white_check_mark: | :white_check_mark: | :white_check_mark: | :x:                |                |
| pypy            | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: |                |
| pypy3           | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: |                |
| rbtools         | :x:                | :x:                | :x:                | :x:                | upstream issue |
| root            | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: |                |
| swift           | :white_check_mark: | :white_check_mark: | :white_check_mark: | :x:                |                |
| wasm-pack       | :white_check_mark: | :x:                | :x:                | :x:                | pre-existing   |

I think the upshot is that these are all either pre-existing or unrelated, but I want to double-check each one first. Will finish looking at this later.

**Comment by carlocab** [comment]
Will try to look at `aws-google-auth` separately. Merging.

**Pull request closed without merging**
