### PR TITLE
dmd 2.072.0-b2 (devel)

### PR DESCRIPTION
**Pull request by John-Colvin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Install is failing: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8711/version=sierra/testReport/junit/brew-test-bot/sierra/install___devel_dmd/

**Comment by John-Colvin** [comment]
yeah, it's an upstream bug. Hopefully will have a patch or new beta that fixes it soon.

**Comment by MikeMcQuaid** [comment]
Closing until we've got an upstream fix.

**Comment by John-Colvin** [comment]
I've pushed a fix, it's present when I look at my fork, but it doesn't seem to be showing in this PR? Either way, please re-open

**Comment by MikeMcQuaid** [comment]
@John-Colvin I can't unfortunately, not sure why. Can you create a new one? Sorry!

**Comment by John-Colvin** [comment]
Feels like a lot of the basics of github don't work as well as they used to :(   I'll open a new pull

**Pull request closed without merging**
