### PR TITLE
kafkacat: enable json support by default

### PR DESCRIPTION
**Pull request by xvrl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
@edenhill @theduderog

### CODE REVIEW

**Comment by theduderog** [comment]
This is great.  Thank you, @xvrl!

**Comment by edenhill** [comment]
Awesome!

**Comment by xvrl** [comment]
@ilovezfs any chance we can get this one merged?

**Comment by ilovezfs** [comment]
Do we actually anticipate anyone needing the `--without-yajl` option?

**Comment by xvrl** [comment]
@ilovezfs no strong reason to keep it, other than the fact that it is possible to build without it.

**Comment by ilovezfs** [comment]
Let's just require it then.

**Comment by xvrl** [comment]
@ilovezfs updated

**Comment by dunn** [comment]
It looks like this needs to be rebased, sorry!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @xvrl for your contribution, I've merged this through #13548

**Pull request closed without merging**
