### PR TITLE
clamav 0.102.4

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@robertleeblairjr thanks for the PR, can you squash the commits in one with msg as `clamav 0.102.4`

**Comment by robertleeblairjr** [comment]
> @robertleeblairjr thanks for the PR, can you squash the commits in one with msg as `clamav 0.102.4`

How would I do that in this PR on the Homebrew branch for this repository? Only thing I could think of is I have to do this in a repository that I have write permissions, my own, and then make another PR for the squashed commits. Perhaps, it's right in front of my face with an option on GitHub to squash these two commits into one and I don't see it. Sure would have been nice if this was given as an option when viewing the PR in a web browser.

**Comment by SMillerDev** [comment]
This PR is based on your own repository. Since you used `bump-formula-pr`, if you do `cd $(brew --repo homebrew/core)` you'll find the homebrew repo there with your username as a git upstream where you can push your changes.

I'm really wondering how you added the second commit if it wasn't there.

**Comment by robertleeblairjr** [comment]
> This PR is based on your own repository. Since you used `bump-formula-pr`, if you do `cd $(brew --repo homebrew/core)` you'll find the homebrew repo there with your username as a git upstream where you can push your changes.
> 
> I'm really wondering how you added the second commit if it wasn't there.

Thank you for the help. I'll give it a go from my local through terminal which isn't ideal since I opened the email for this PR in a web browser. I can't be the first person who's wanted this option to squash commits in the same PR through GitHub. I could have selected both commits with a drop down menu in the PR, squash them, and carry on.
As to how I made multiple commits, I just edited the file. I don't know whether this happened to be an anomaly or some feature.

**Comment by SMillerDev** [comment]
> @SMillerDev YIKES! Definitely not what I was trying to do. Thinking I should just close this one and start over now?

If you think that's the most convenient way, you can do that. Other options are:
1. Try and rebase on `origin/master` and only keep the relevant commits.
1. I try and reset your branch so it only has one commit.

**Comment by robertleeblairjr** [comment]
> > @SMillerDev YIKES! Definitely not what I was trying to do. Thinking I should just close this one and start over now?
> 
> If you think that's the most convenient way, you can do that. Other options are:
> 
> 1. Try and rebase on `origin/master` and only keep the relevant commits.
> 2. I try and reset your branch so it only has one commit.

LOL. When I checked what had occurred with this PR for pushing the squash after rebase, then I see a plethora of references to commits which have been merged into this branch. Really not wanting this snowball to keep growing to where I still have to close. I think I ended up pulling to that branch from master commits. Thinking until my git fu improves to know how this happened, then it's probably better to just close. Takes 5 minutes to open another and frees up people having to look at this mess.

**Comment by SMillerDev** [comment]
> Takes 5 minutes to open another and frees up people having to look at this mess.

Thanks, can you link it here when it's ready?

**Comment by robertleeblairjr** [comment]
> > Takes 5 minutes to open another and frees up people having to look at this mess.
> 
> Thanks, can you link it here when it's ready?

Will do. Just going through and cleaning up local branches and checking remote for being in sync before doing this. Would like to automatically cleanup old branches from submissions after they've been merged to keep from my forked repo and Homebrew's from having so many commits behind. I'm sure there are scripts, aliases, and other simplified methods for maintaining this. I just kind of dived into using git, GitHub, PRs, commits, bug reports etc. with a learn as I go along approach.

**Comment by SMillerDev** [comment]
Once a PR is merged you get a "delete branch" button. That'll remove the now unused branch.

**Comment by robertleeblairjr** [comment]
> Once a PR is merged you get a "delete branch" button. That'll remove the now unused branch.

Yep. I saw this after it closes which would explain why I had multiple old branches that had already been merged that I had long forgot about. Is there a way to have that branch deleted automatically when the PR is merged? I'll look under options for my repos. I don't have anything automatically setup locally to pull from multiple branches or repos other than whichever one that git is checked out on. Of course, I haven't used git except for brew.

**Pull request closed without merging**
