### PR TITLE
kubecolor 0.3.0

### PR DESCRIPTION
**Pull request by prune998**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by prune998** [comment]
> ⚠️ Bottle publish [failed](https://github.com/Homebrew/homebrew-core/actions/runs/8689983388).

Anything I can do about that ?

**Comment by prune998** [comment]
@chenrui333 can it be because my PR does not have the tag `[bump-formula-pr]` ?

**Comment by chenrui333** [comment]
Nope, I think we have linux build failure. cc @Homebrew/core

**Comment by chenrui333** [comment]
let me check build in my local really quick.

**Comment by chenrui333** [comment]
this is the root cause

```
bash-3.2$ KUBECTL_COMMAND=echo /opt/homebrew/Cellar/kubecolor/0.3.0/bin/kubecolor get pods --plain -o yaml
bash-3.2$
```

the command does not return anything now.

**Comment by prune998** [comment]
I patched the app and it's re-releasing now. I'll have to change the SHA to match.

**Comment by prune998** [comment]
everything should be good now

**Review by timsutton — APPROVED** [review]

**Comment by prune998** [comment]
I re-added the test and rebased

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @prune998!

**Comment by prune998** [comment]
Thanks you all for your help !

**Pull request merged**
