### PR TITLE
planck 2.0-alpha1-devel

### PR DESCRIPTION
**Pull request by ilovezfs**
Also, fix a case sensitivitity issue.

### CODE REVIEW

**Comment by mfikes** [comment]
I am the maintainer of Planck. I'd prefer that this alpha not be released this way. I can't guarantee that the tags will remain stable, and additionally I have a PR open for Planck 1.15. Can this PR be declined?

**Comment by ilovezfs** [comment]
@mfikes certainly, but you're aware this can only be installed if the user deliberately passes `--devel` right?

**Comment by mfikes** [comment]
@ilovezfs No. Thanks. I wasn't aware of the `--devel` flag. But, my preference would be to not have to maintain the alpha tags (I plan on deleting them), nor the consequences to `planck.rb`, nor dealing with Planck being released this way. (Of course, I don't control Hombebrew—just expressing my preference.)

**Comment by ilovezfs** [comment]
@mfikes I'm definitely closing this, then :) I just wanted to make sure you were aware the `:stable` and `:devel` specs are orthogonal. If you'd like to do a `:devel` release of the `2.*` series at some point before blessing it `:stable`, let us know!

**Comment by mfikes** [comment]
@ilovezfs Thanks! Perhaps I'll consider this when Planck 2.0 reaches beta quality. (Have been using `--HEAD` in general to install master without having to deal with tags.)

**Comment by ilovezfs** [comment]
>Have been using --HEAD in general to install master

Nice! Always cool to hear when upstreams find ways to use brew productively themselves, not solely for distribution.

**Comment by mfikes** [comment]
@ilovezfs Cool. In hindsight, FWIW, I don't even think this formula was building the 2.0 alpha. I haven't looked at it carefully, but it appears to be building the 1.x (Objective-C) release, not the new 2.0 C port.

**Comment by ilovezfs** [comment]
Ah so they coexist in the same source tree but `$ ./script/build-sandbox` triggers the 1.x build?

**Comment by mfikes** [comment]
Right. The 1.x train is still being maintained for a while. Ultimately we will sort out how to build 2.x via Homebrew (which currently uses make and clang, which may be fine), sort out what packages/libs it depends on (if any, or none if statically linked, etc).

**Comment by ilovezfs** [comment]
Yup, simple make is fine, as is CMake, Autools, etc.

**Pull request closed without merging**
