### PR TITLE
rttr 0.9.6 (new formula)

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Closed and reopened to get the tests running again, this time with ARM

**Comment by fxcoudert** [comment]
It's not happy:

```
2020-12-27T10:29:33.3913220Z /tmp/rttr-20201227-45587-fmwnp0/rttr-0.9.6/src/unit_tests/misc/array_range_test.cpp:47:5: error: invalid token in expression
2020-12-27T10:29:33.3914310Z     CHECK(range.begin() == range.end());
2020-12-27T10:29:33.3914830Z     ^
2020-12-27T10:29:33.3916060Z /tmp/rttr-20201227-45587-fmwnp0/rttr-0.9.6/3rd_party/catch-1.12.0/catch/catch.hpp:11599:23: note: expanded from macro 'CHECK'
2020-12-27T10:29:33.3942510Z #define CHECK( expr ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, expr )
2020-12-27T10:29:33.3944370Z                       ^
2020-12-27T10:29:33.3945920Z /tmp/rttr-20201227-45587-fmwnp0/rttr-0.9.6/3rd_party/catch-1.12.0/catch/catch.hpp:2235:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
2020-12-27T10:29:33.3947800Z         INTERNAL_CATCH_REACT( __catchResult ) \
2020-12-27T10:29:33.3948370Z         ^
2020-12-27T10:29:33.3949710Z /tmp/rttr-20201227-45587-fmwnp0/rttr-0.9.6/3rd_party/catch-1.12.0/catch/catch.hpp:2219:44: note: expanded from macro 'INTERNAL_CATCH_REACT'
2020-12-27T10:29:33.3951200Z     if( resultBuilder.shouldDebugBreak() ) CATCH_BREAK_INTO_DEBUGGER(); \
2020-12-27T10:29:33.3952110Z                                            ^
2020-12-27T10:29:33.3953490Z /tmp/rttr-20201227-45587-fmwnp0/rttr-0.9.6/3rd_party/catch-1.12.0/catch/catch.hpp:2155:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
2020-12-27T10:29:33.3956290Z     #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
2020-12-27T10:29:33.3957120Z                                                                           ^
2020-12-27T10:29:33.3958460Z /tmp/rttr-20201227-45587-fmwnp0/rttr-0.9.6/3rd_party/catch-1.12.0/catch/catch.hpp:2133:38: note: expanded from macro 'CATCH_TRAP'
2020-12-27T10:29:33.3959540Z         #define CATCH_TRAP() __asm__("int $3\n" : : /* NOLINT */ )
2020-12-27T10:29:33.3960260Z                                      ^
2020-12-27T10:29:33.3960900Z <inline asm>:1:6: note: instantiated into assembly here
2020-12-27T10:29:33.3961520Z         int $3
2020-12-27T10:29:33.3961890Z             ^
```

**Review by chenrui333 — APPROVED** [review]
lgtm

**Comment by chenrui333** [comment]
@yurikoles, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
