### PR TITLE
lsyncd: depend on lua (Draft: Do not merge)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Follow up to https://github.com/Homebrew/homebrew-core/pull/65993.

See also https://github.com/axkibe/lsyncd/issues/621.

I've fixed a bunch of configuration and compile errors, but I'm left
with the following linker error:

    [100%] Linking C executable lsyncd
    /usr/local/Cellar/cmake/3.19.1/bin/cmake -E cmake_link_script CMakeFiles/lsyncd.dir/link.txt --verbose=1
    /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/lsyncd.dir/lsyncd.c.o CMakeFiles/lsyncd.dir/runner.c.o CMakeFiles/lsyncd.dir/defaults.c.o CMakeFiles/lsyncd.dir/fsevents.c.o -o lsyncd  /usr/local/opt/lua/lib/liblua.5.4.dylib
    Undefined symbols for architecture x86_64:
      "_lua_objlen", referenced from:
          _l_exec in lsyncd.c.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [lsyncd] Error 1
    make[1]: *** [CMakeFiles/lsyncd.dir/all] Error 2
    make: *** [all] Error 2

Does anyone have any ideas?

### CODE REVIEW

**Comment by carlocab** [comment]
@mitchblank -- you seem to be a wizard at this: any ideas?

**Comment by mitchblank** [comment]
Well `lua_objlen` is a macro, so the base issue is that some include is missing.

Normally I'd expect that to be fetched via /usr/local/include/lua/luaconf.h which .../lua.h includes.  So probably your includepath is getting the headers for the wrong lua version

**Comment by carlocab** [comment]
The version should be right, but I'll take a look again.

To me, it's more likely that lua5.4 dropped `lua_objlen`. They've got a habit of doing things like that between lua versions.

**Comment by carlocab** [comment]
Nope, don't know how to fix this. Definitely have the right version of lua. Closing.

**Pull request closed without merging**
