### PR TITLE
castxml: do no patch when building with head

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
The patch should be inside a `head do` block.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
please relocate patch to a `stable do` block, which should also have the stablle url, mirror, and checksum, and be above the bottle block.

**Comment by iMichka** [comment]
Done

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@iMichka thanks for your contribution to Homebrew

**Comment by iMichka** [comment]
Thanks for the fast merge :)

**Pull request merged**
