### PR TITLE
appscale-tools: bump dependencies

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍

**Comment by DomT4** [comment]
@nijikon Make sure you pull the bottles on resource updates so the bottled and from-source installations produce the same result. Thanks 😃

**Comment by nijikon** [comment]
@DomT4 Will it work properly without bumping the revision?

**Comment by DomT4** [comment]
Which `revision`? 😄. Bottle revisions get bumped automatically when you pull new ones.

If you mean formula revisions, unless the dependencies are vital for functionality doesn't need a `revision` bump but future installations should produce the same outcome whether you install from source or pour the bottle. Otherwise we can see issues reported where different installations are using different dependencies and it's hard to debug.

**Comment by nijikon** [comment]
I meant formula revision. So basically for this pulling it with bottle would be enough. It would bump the bottle revision. Correct?

**Comment by DomT4** [comment]
Yup. Just pulling the bottle in these situations is enough, unless you're fixing existing breakage, in which case bump the formula revision.

**Comment by nijikon** [comment]
Very clear now, thanks!

**Pull request closed without merging**
