### PR TITLE
rsync 3.1.3

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
:arrows_counterclockwise:

**Comment by ilovezfs** [comment]
@DomT4 your wait is over!

**Comment by DomT4** [comment]
🎉 🍰

**Comment by ilovezfs** [comment]
Hmm ... the patches were actually still relevant for 3.1.3 and in the 3.1.3 patches tarball but they're causes build failure. I may need to revert this until we figure out why the build fails.

**Comment by ilovezfs** [comment]
```
bash-3.2$ make -j1
clang -I. -I. -I./zlib -I./popt -O2 -DHAVE_CONFIG_H -Wall -W  -c flist.c -o flist.o
clang -I. -I. -I./zlib -I./popt -O2 -DHAVE_CONFIG_H -Wall -W  -c rsync.c -o rsync.o
rsync.c:623:40: error: too few arguments to function call, expected 4, have 2
                if (cmp_time(sxp->crtime, file_crtime) != 0
                    ~~~~~~~~                         ^
./proto.h:402:1: note: 'cmp_time' declared here
int cmp_time(time_t f1_sec, unsigned long f1_nsec, time_t f2_sec, unsigned long f2_nsec);
^
1 error generated.
make: *** [rsync.o] Error 1
bash-3.2$ 
```

```
diff --git a/Formula/rsync.rb b/Formula/rsync.rb
index ef4a0d0..9eb0582 100644
--- a/Formula/rsync.rb
+++ b/Formula/rsync.rb
@@ -5,6 +5,7 @@ class Rsync < Formula
   mirror "https://mirrors.kernel.org/gentoo/distfiles/rsync-3.1.3.tar.gz"
   mirror "https://www.mirrorservice.org/sites/rsync.samba.org/rsync-3.1.3.tar.gz"
   sha256 "55cc554efec5fdaad70de921cd5a5eeb6c29a95524c715f3bbf849235b0800c0"
+  revision 1
 
   bottle do
     sha256 "1b023b82b13c5afaaf0ef980465b660c7a3972f842b2a73cbb2fe541d0a7d210" => :high_sierra
@@ -14,6 +15,16 @@ class Rsync < Formula
 
   depends_on "autoconf" => :build
 
+  patch do
+    url "https://download.samba.org/pub/rsync/src/rsync-patches-3.1.3.tar.gz"
+    mirror "https://www.mirrorservice.org/sites/rsync.samba.org/rsync-patches-3.1.3.tar.gz"
+    mirror "https://launchpad.net/rsync/main/3.1.2/+download/rsync-patches-3.1.3.tar.gz"
+    sha256 "0dc2848f20ca75c07a30c3237ccf8d61b61082ae7de94758a27dac350c99fb98"
+    apply "patches/fileflags.diff",
+          "patches/crtimes.diff",
+          "patches/hfs-compression.diff"
+  end
+
   def install
     system "./prepare-source"
     system "./configure", "--disable-debug",
```

**Comment by ilovezfs** [comment]
PR, which will fail, here: https://github.com/Homebrew/homebrew-core/pull/23415

**Comment by ilovezfs** [comment]
OK for a crtime fix I think we want
```
diff --git a/generator.c b/generator.c
index 69c4efb..a7745ca 100644
--- a/generator.c
+++ b/generator.c
@@ -526,7 +526,7 @@ void itemize(const char *fnamecmp, struct file_struct *file, int ndx, int statre
                if (crtimes_ndx) {
                        if (sxp->crtime == 0)
                                sxp->crtime = get_create_time(fnamecmp);
-                       if (cmp_time(sxp->crtime, f_crtime(file)) != 0)
+                       if (cmp_time(sxp->crtime, 0, f_crtime(file), 0) != 0)
                                iflags |= ITEM_REPORT_CRTIME;
                }
 #if !defined HAVE_LCHMOD && !defined HAVE_SETATTRLIST
diff --git a/rsync.c b/rsync.c
index d5559be..a214b72 100644
--- a/rsync.c
+++ b/rsync.c
@@ -620,7 +620,7 @@ int set_file_attrs(const char *fname, struct file_struct *file, stat_x *sxp,
                time_t file_crtime = f_crtime(file);
                if (sxp->crtime == 0)
                        sxp->crtime = get_create_time(fname);
-               if (cmp_time(sxp->crtime, file_crtime) != 0
+               if (cmp_time(sxp->crtime, 0, file_crtime, 0) != 0
                 && set_create_time(fname, file_crtime) == 0)
                        updated = 1;
        }
```

But then the next error is
```
xattrs.c:280:1: error: unknown type name '$$$ERROR$$$'
$$$ERROR$$$ the old patch needs reworking since rsync_xal_get() has totally changed!
^
xattrs.c:280:16: error: expected ';' after top level declarator
$$$ERROR$$$ the old patch needs reworking since rsync_xal_get() has totally changed!
               ^
               ;
xattrs.c:1384:2: error: #endif without #if
#endif /* SUPPORT_XATTRS */
 ^
3 errors generated.
make: *** [xattrs.o] Error 1
```

**Comment by ilovezfs** [comment]
I guess that means no hfs-compression patch for 3.1.3 unless we revert.

**Comment by DomT4** [comment]
Apologies, I am hideously unwell. I'll catch up on GitHub emails when I feel less completely awful 🙈.

**Comment by DomT4** [comment]
Not really back, just had to wake up for an antibiotic dose, lucky me. Have we nudged upstream that these are failing?

**Comment by ilovezfs** [comment]
Nope. Be my guest.

**Comment by DomT4** [comment]
Was hoping you'd take pity on me 😉. I'll look into it in the near future.

**Comment by ilovezfs** [comment]
The problematic one is the one they already know about unfortunately, not the cmp_time oversight :(

**Comment by n8felton** [comment]
Is there an upstream bug to track?

**Pull request closed without merging**
