### PR TITLE
mpv: revert removed Vapoursynth support

### PR DESCRIPTION
**Pull request by chainikdn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
As #55906 is telling us, this configuration is known to be non-working.

We can add this back only if we can add a test for it in the test block of this formula, that shows that it is properly working with `vapoursynth`.

**Comment by chainikdn** [comment]
> As #55906 is telling us, this configuration is known to be non-working.

#55906 is wrong, this configuration IS used to work for years and working right now.

**Comment by iMichka** [comment]
What commands do I need to run to check that it works?

**Comment by chainikdn** [comment]
For example, check mpv configure log - ~/Library/Logs/Homebrew/mpv/02.python3.
> Checking for Vapoursynth filter bridge:  yes

or run
'mpv --vf=help'
to list available filters, ensure you have 'vapoursynth' in the list

**Comment by iMichka** [comment]
Build looks good to me, and the filter is present.

Could you please add `assert_match "vapoursynth", shell_output(bin/"mpv --vf=help")` in the test block, so that we make sure we test for `vapoursynth`'s presence in the future?

**Comment by chainikdn** [comment]
Here you are

**Comment by chainikdn** [comment]
BTW, is this `depends_on :xcode => :build` really necessary? 
Again, it used to work w/o this before and I don't understand the reason for adding this dependency there - https://github.com/Homebrew/homebrew-core/pull/51335 
Could somebody elaborate please?

**Comment by iMichka** [comment]
The build failed on macOS 10.14 with:
```
2020-06-13T23:03:39.6344820Z <unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx10.10'
2020-06-13T23:03:39.6345320Z 
2020-06-13T23:03:39.6346140Z Waf: Leaving directory `/private/tmp/mpv-20200614-52534-ksqv78/mpv-0.32.0/build'
2020-06-13T23:03:39.6346280Z Build failed
2020-06-13T23:03:39.6347290Z  -> task in 'osdep/macOS_swift.o,osdep/macOS_swift.h,osdep/macOS_swift.swiftmodule' failed with exit status 1 (run with -v to display more information)
```

I wild guess is that this was the reason why Xcode was needed.

**Comment by chainikdn** [comment]
Just tried clean 10.14.4 image, everything builds just fine with CLT only.
Is it possible there's a problem in 10.14 configuration here?

**Comment by chainikdn** [comment]
Tried on 10.14**.6** (not 100% "clean" though as it was clean 10.14.4 + update to 10.14.6).
Still works.

**Comment by iMichka** [comment]
Yes, it's weird. But we are not seeing any issues on the hundreds/thousands of builds we run on these machines.

Can you add the Xcode dependency back? I would like to at least get the vapoursynth part shipped, so that we get rid of the issue first.

We can discuss the Xcode issue in a second step as it is unrelated to the fix added by this pull request.

**Comment by chainikdn** [comment]
done

**Comment by SMillerDev** [comment]
Can you squash all your commits into one so we can merge it?

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Thanks @chainikdn. At least we are back to normal now.

@jnozsc if you encounter issues with `vapoursynth` and `mpv`, let us know, as we added it back.

@chainikdn if you want to get rid of the xcode dependency: you are free to open a pull request and try to investigate this, but we do not really consider this an issue as it builds fine now.

**Pull request closed without merging**
