### PR TITLE
mariadb@10.0 10.0.28 (new formula)

### PR DESCRIPTION
**Pull request by kuahyeow**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by kuahyeow** [comment]
This formula has to have `conflicts_with` as it provides the same binaries as `mysql`

**Comment by kuahyeow** [comment]
Have opened https://github.com/Homebrew/homebrew-versions/pull/1526 as well

**Comment by makigumo** [comment]
Maybe it's a good idea to weed out the `build.devel?`, `build.stable?` stuff for a simpler formula.

Also it probably needs to `conflicts_with` the unversioned `mariadb` package.

**Comment by kuahyeow** [comment]
> Maybe it's a good idea to weed out the build.devel?, build.stable? stuff for a simpler formula.

Good idea, have done so.

> Also it probably needs to conflicts_with the unversioned mariadb package.

Hmm, I'm not sure. Seems like `brew audit` is explicitly telling me to use `keg_only :versioned_formula` to deal with rather than `conflicts_with`. Seems to be consistent if I look at the formula for mysql@5.5 for example (https://github.com/Homebrew/homebrew-core/blob/master/Formula/mysql%405.5.rb).

So currently there's seems to be audit check against any `conflicts_with` in a versioned formula. I'm guessing this new formula is a new exception ?

**Comment by makigumo** [comment]
Yes you are right, I believe this is the corresponding issue: https://github.com/Homebrew/brew/pull/1851

**Comment by MikeMcQuaid** [comment]
> This formula has to have conflicts_with as it provides the same binaries as mysql

Once a formula is `keg_only` the `conflicts_with` are no longer needed so can be removed. Thanks!

**Comment by kuahyeow** [comment]
Thanks for the guidance @MikeMcQuaid. I have removed the `conflicts_with`.

**Comment by fxcoudert** [comment]
Thanks @kuahyeow for your contribution!

**Pull request closed without merging**
