### PR TITLE
ansible 9.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
image

**Comment by cho-m** [comment]
Can you add a test to catch #154912 the next time we migrate Python. We broken `ansible-test` when migrating to Python 3.12, but it should be fixed with this release.

---

On side note, upstream originally posted this in forum as pre-release but edited post to remove that https://forum.ansible.com/t/release-announcement-ansible-community-package-9-0-0/2492 so may be official release

**Comment by chenrui333** [comment]
yeah, totally, I will add ansible-core constraint moving forward.

**Comment by chenrui333** [comment]
it would be probably 9.0.1

image

**Comment by chenrui333** [comment]
I would think we should just fix ansible 8.6.1 for now.

**Comment by chenrui333** [comment]
Looking at this PR, https://github.com/Homebrew/homebrew-core/pull/152694, it might be good to wait until ansible 9.0.1 to fix the py3.12 migration

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
looks like we are good to go

image

**Pull request merged**
