### PR TITLE
sslscan 2.0.10; re-add custom OpenSSL

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes #75914.

### CODE REVIEW

**Comment by SMillerDev** [comment]
I'd be more inclined to say that sslscan has to live without this feature. Vendoring formula should only be done if there is no other choice to make something work IMHO.

**Comment by DomT4** [comment]
This would at least have a low maintenance overhead given it doesn't really need to actively track OpenSSL releases as well; it can just be bumped whenever one is available and `sslscan` is due an upgrade anyway. I've no real opinion though, the second commit here was mostly offered up as an alternative to https://github.com/Homebrew/homebrew-core/pull/75914 where I'm very keen to avoid changing a sensible upstream default.

**Comment by dsXLII** [comment]
I was just about to submit a PR that did the "use a local copy of OpenSSL" hack but yours is much more elegant than mine, probably because you actually know what you're doing. :)

If this gets merged there won't be a reason for #75914 so I'll remove that one shortly.

**Comment by DomT4** [comment]
@SMillerDev This is probably the lesser of two evils 🙃, unless you completely hate the idea.

It's reasonable enough for a tool like `sslscan` to require its own version of OpenSSL. It'd be nice if upstream could do something, like they did with SSLv2 and SSLv3, to check for compression support without requiring a weakened version of OpenSSL to build/run against but I don't think that's something we can necessarily hold our breaths on. I defer to you, but this is about as non-ugly as this can get 😸.

**Comment by SMillerDev** [comment]
Seeing how we had exactly one request for this I'm going to suggest we hold off on vendoring openssl. If we get more I agree we should go this way.

**Comment by dsXLII** [comment]
Did the 2.0.10 part of this PR get merged separately/in another PR? Even if we don't want to merge the compression change, the routine version update still needs to go in.

**Pull request closed without merging**
