### PR TITLE
boost: fix env: userpaths deprecated

### PR DESCRIPTION
**Pull request by nikivdev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is my first pull request and I am not fully certain how to perform the 4th operation correctly. 

I found the error through running `brew audit --strict` and I thought it was trivial to fix it since it's just a one line change in each of the formulas.

I hope this solves the issue.

### CODE REVIEW

**Comment by cblecker** [comment]
It's failing audit because https://github.com/nikitavoloboev/homebrew-core/blob/e1e9045a95b7cc2c8839f9d6e77f51c70d98c38a/Formula/boost%401.55.rb#L3 needs to be https.

**Comment by nikitavoloboev** [comment]
I changed to https

**Comment by cblecker** [comment]
```
boost@1.57:
  * Stable: The URL https://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.bz2 is not reachable
```

**Comment by nikitavoloboev** [comment]
That's very strange thought since I have just tried going to said URL and I am presented with the loading screen. I am not really sure why it says it is not reachable.

**Comment by fxcoudert** [comment]
Sometimes the CI has network instabilities that show weird network errors. If those "online" failures do not happen locally, don't mind them.

**Comment by nikitavoloboev** [comment]
Is there anything I can d to make the checks complete? I am not really sure what to do next to make this pull request merged.

**Comment by fxcoudert** [comment]
@nikitavoloboev can you split it into 3 different pull requests?

**Comment by nikitavoloboev** [comment]
Yes of course, let me do that.

**Comment by fxcoudert** [comment]
Thanks for your contribution @nikitavoloboev!

**Pull request closed without merging**
