### PR TITLE
zeromq: Add `--with-cmake` option

### PR DESCRIPTION
**Pull request by dennisklein**
When building ZeroMQ with autotools only a pkconfig file
is installed. When building with CMake, in addition
a CMake package is installed (`share/cmake/ZeroMQ`), which
enables better integration with projects using CMake as well.

This commit also changes the source from the dist tarball to
the source tarball generated by github, because the dist tarball
does not contain all the files tracked in git (and thus fails to
build with CMake). According to zeromq/libzmq#3056 this issue
seems to be fixed, but it is not yet released.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
--> Both `--with-cmake` and without work for me (el capitan).
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
--> It does not, but the reported issue is intentional:
```
$ brew audit --strict zeromq
zeromq:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
Error: 1 problem in 1 formula
```

-----

### CODE REVIEW

**Comment by bluca** [comment]
> This commit also changes the source from the dist tarball to
the source tarball generated by github, because the dist tarball
does not contain all the files tracked in git (and thus fails to
build with CMake). According to zeromq/libzmq#3056 this issue
seems to be fixed, but it is not yet released.

Please don't do that. It will make the build uselessly slower for those who don't have to use cmake, by forcing a dependency on the autotools stack. The distributable tarballs are provided to avoid just that.
Just wait for the next release.

**Comment by dennisklein** [comment]
Would you support switching to the CMake build completely not just optionally? It is faster than autotools from dist tarballs.

> Just wait for the next release

When is it going to be? Could be a year from now..

**Comment by bluca** [comment]
> Would you support switching to the CMake build completely not just optionally? It is faster than autotools from dist tarballs.

Please, don't - CMake constantly breaks backward compatibility, so there is no way to know that a tarball released now will keep working 6 months, a year or two years from now. Which means I'll get more bug reports that I can't do anything about.
That's one of the main points of the distributable tarballs - it has no dependencies, and if the configure/make/make install combo works now then most likely will also keep working years from now.

> When is it going to be? Could be a year from now..

When a few more features land. In the meanwhile, brew allows to build from the git HEAD, so you can do that.

**Comment by ilovezfs** [comment]
>Please, don't - CMake constantly breaks backward compatibility, so there is no way to know that a tarball released now will keep working 6 months, a year or two years from now. Which means I'll get more bug reports that I can't do anything about.

For what it's worth, this is not our experience in Homebrew. There's rarely any breakage on CMake upgrades in any of the 439 formulae using it.

**Comment by dennisklein** [comment]
> When a few more features land.

@bluca Can I convince you to make a libzmq (hotfix) release with the fixed cmake build in the dist tarball sooner than later? It would be for science ;)

**Comment by dennisklein** [comment]
@ilovezfs If libzmq cannot provide a fixed dist tarball, would you accept a PR that applies a patch in the brew formula?

Because after hearing the concerns by bluca, I would rather not change the source url away from the dist tarball as it is done currently in this PR.

**Comment by bluca** [comment]
> For what it's worth, this is not our experience in Homebrew. There's rarely any breakage on CMake upgrades in any of the 439 formulae using it.

I understand, unfortunately my experience has not been as good.

> @bluca Can I convince you to make a libzmq (hotfix) release with the fixed cmake build in the dist tarball sooner than later? It would be for science ;)

Sorry, there's a few things to do - some new APIs have been promoted out of draft state and there's a few more that need documentation, so it will take a few weeks I think.

**Pull request closed without merging**
