### PR TITLE
gcc: fix build on Mojave

### PR DESCRIPTION
**Pull request by fxcoudert**
1. GCC does not compile with the current Mojave beta, because headers are expected in `/usr/include` when CLT is installed (which we require on Mojave). But the headers are not there, it seems they have moved to `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`. Fortunately, this path does not depends on the Xcode installation path, so we can use it for bottles!

2. 32-bit support was dropped from Xcode 10, so we need to tell GCC not to build the "multilib", i.e. the 32-bit runtime support. If it tries, it will fail: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87030

Patching these two issues leads to a successful build of GCC on macOS 10.14 Mojave.

### CODE REVIEW

**Comment by fxcoudert** [comment]
This seems safe to me, but I'd welcome another maintainer's opinion @mistydemeo @DomT4

**Comment by fxcoudert** [comment]
The resulting GCC successfully compiles OpenMPI and various Fortran formulas, with all tests working as expected.

**Comment by DomT4** [comment]
> If it tries, it will fail: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87030

Do you recall the failure, out of interest?

> but I'd welcome another maintainer's opinion @mistydemeo @DomT4

I don't have an objection here but I'd feel more comfortable with Misty providing an opinion than me on SDK/Mojave/Compiler related issues 😅.

**Comment by fxcoudert** [comment]
@DomT4 the 32-bit failure is at link time: it compiles fine into an object file, but at link time it complains about not finding standard C library symbols.

It can be reproduced with a trivial example:

```
einstein:tmp fx$ cat a.c
#include <stdlib.h>

int main (void) { abort(); }
einstein:tmp fx$ clang a.c -arch i386
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "_abort", referenced from:
      _main in a-9e910f.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by DomT4** [comment]
> It can be reproduced with a trivial example

Aye, I tried earlier with:
```c
#include <stdio.h>

int main()
  {
    printf("Homebrew\n");
    return 0;
  }
```
and `clang -m32 homebrew.c -o homebrew` and got the warning but otherwise compiled okay, which is what threw me off. Your example succeeds locally as well. I think you're right, I'm just unsure why it's not breaking for me.

**Comment by fxcoudert** [comment]
After many more tests passed locally, merged to allow us to start bottling GCC and formulas that depend on it.

**Comment by zbeekman** [comment]
FWIW, this patch looks good to me! Thanks @fxcoudert

**Pull request merged**
