### PR TITLE
archi-steam-farm 4.1.2.0

### PR DESCRIPTION
**Pull request by shwang53**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
```
tar xof /Users/brew/Library/Caches/Homebrew/downloads/126038fb691a9d1b8ab95ef774355aca00b4e8340cb48653cad4527bdf93acce--ArchiSteamFarm-4.1.2.0.tar.gz -C /private/tmp/d20200302-72630-dtsiq8
cp -pR /private/tmp/d20200302-72630-dtsiq8/ArchiSteamFarm-4.1.2.0/. /private/tmp/archi-steam-farm-20200302-72630-j49rju/ArchiSteamFarm-4.1.2.0
chmod -Rf +w /private/tmp/d20200302-72630-dtsiq8
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - ASF.exe
```

**Comment by samford** [comment]
You may want to look through #21804 to get a better idea as to why this formula hasn't been updated yet.

It's often a good idea to not only check for open PRs but also to take a look through closed PRs before running `brew bump-formula-pr` for a new version. The last time this formula was updated successfully was in 2017 and the closed PRs since then show that this formula has some issues that need to be addressed before it will work with a newer version.

**Comment by Bo98** [comment]
This cannot happen until .NET Core is in homebrew-core.

**Pull request closed without merging**
