### PR TITLE
pyqt: debug Linux build issue on CI

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
> 2023-08-14T20:20:10.7767853Z [34m==>[0m [1msip-install --verbose --target-dir /home/linuxbrew/.linuxbrew/Cellar/pyqt/6.5.2/lib/python3.11/site-packages[0m
2023-08-14T20:20:10.7768003Z Querying qmake about your Qt installation...
2023-08-14T20:20:10.7768223Z /home/linuxbrew/.linuxbrew/opt/qt/bin/qmake -query
2023-08-14T20:20:10.7768458Z These bindings will be built: QtWebEngineCore, QtWebEngineQuick, QtWebEngineWidgets.
2023-08-14T20:20:10.7768608Z Generating the QtWebEngineCore bindings...
2023-08-14T20:20:10.7768760Z Generating the QtWebEngineQuick bindings...
2023-08-14T20:20:10.7768904Z Generating the QtWebEngineWidgets bindings...
2023-08-14T20:20:10.7769081Z Generating the .pro file for the QtWebEngineCore module...
2023-08-14T20:20:10.7769262Z Generating the .pro file for the QtWebEngineQuick module...
2023-08-14T20:20:10.7769557Z Generating the .pro file for the QtWebEngineWidgets module...
2023-08-14T20:20:10.7769753Z Generating the top-level .pro file...
2023-08-14T20:20:10.7769867Z Generating the Makefiles...
2023-08-14T20:20:10.7770162Z /home/linuxbrew/.linuxbrew/opt/qt/bin/qmake -recursive PyQt6-WebEngine.pro
2023-08-14T20:20:10.7770550Z sip-install: '/home/linuxbrew/.linuxbrew/opt/qt/bin/qmake -recursive PyQt6-WebEngine.pro' failed returning 3
2023-08-14T20:20:10.7770702Z Info: creating stash file /tmp/tmp2atid2i4/.qmake.stash
2023-08-14T20:20:10.7770893Z Reading /tmp/tmp2atid2i4/QtWebEngineCore/QtWebEngineCore.pro
2023-08-14T20:20:10.7771053Z Project ERROR: Unknown module(s) in QT: webenginecore

**Comment by carlocab** [comment]
PyQt doesn't build on Linux because our Qt build on Linux doesn't have QtWebEngine, which requires a patched FFmpeg. See #133732.

**Comment by iMichka** [comment]
Ok got it, I had the feeling I was able to build it locally a few weeks ago, maybe I still had an older ffmpeg version.

Looks like it's an older issue, going back to 2021:
https://ffmpeg.org/pipermail/ffmpeg-devel/2021-September/285401.html

Some only noticed in 2023; which is weird;
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270209

Anyway, upstream says the patch is not the right way to fix it. But since then everyone has been happily applying the patch everywhere ...

I applied the patch in this PR, and will the CI run on qt/pyqt to make sure it fixes it. Then we can maybe temporarily accept the patch, and I'll open a ticket on Qt's side to get this sorted out.

**Comment by iMichka** [comment]
`ffmpeg` fails to build on Linux due to a binptils change: https://sourceware.org/bugzilla/show_bug.cgi?id=30578

**Comment by iMichka** [comment]
`ffmpeg` patch for `binutils` has been moved to #139956

**Comment by iMichka** [comment]
Making some progress as `qt` tries to build `chromium`, but fails to do so:

```
2023-08-19T10:07:06.4074496Z FAILED: obj/extensions/browser/browser_sources/browser_sources_jumbo_8.o 
2023-08-19T10:07:06.4086798Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-11 -MMD -MF obj/extensions/browser/browser_sources/browser_sources_jumbo_8.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DLIBYUV_DISABLE_NEON -DUSE_EGL -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DLEVELDB_PLATFORM_CHROMIUM=1 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DLOGGING_INSIDE_WEBRTC -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPGC_POINTER_COMPRESSION -I. -Igen -I../../../3rdparty/chromium -I../../../3rdparty/chromium/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../../3rdparty/chromium/third_party/libyuv/include -I../../../3rdparty/chromium/third_party/jsoncpp/source/include -I../../../3rdparty/chromium/third_party/khronos -I../../../3rdparty/chromium/gpu -I../../../3rdparty/chromium/third_party/vulkan-deps/vulkan-headers/src/include -Igen/third_party/dawn/include -I../../../3rdparty/chromium/third_party/dawn/include -I../../../3rdparty/chromium/third_party/wtl/include -I../../../3rdparty/chromium/third_party/abseil-cpp -I../../../3rdparty/chromium/third_party/boringssl/src/include -I../../../3rdparty/chromium/third_party/protobuf/src -Igen/protoc_out -I../../../3rdparty/chromium/net/third_party/quiche/overrides -I../../../3rdparty/chromium/net/third_party/quiche/src/quiche/common/platform/default -I../../../3rdparty/chromium/net/third_party/quiche/src -Igen/net/third_party/quiche/src -I../../../3rdparty/chromium/third_party/flatbuffers/src/include -I../../../3rdparty/chromium/third_party/leveldatabase -I../../../3rdparty/chromium/third_party/leveldatabase/src -I../../../3rdparty/chromium/third_party/leveldatabase/src/include -I../../../3rdparty/chromium/third_party/ced/src -I../../../3rdparty/chromium/third_party/webrtc_overrides -I../../../3rdparty/chromium/third_party/webrtc -Igen/third_party/webrtc -I../../../3rdparty/chromium/third_party/skia -I../../../3rdparty/chromium/third_party/wuffs/src/release/c -I../../../3rdparty/chromium/third_party/vulkan/include -I../../../3rdparty/chromium/third_party/libwebm/source -I../../../3rdparty/chromium/third_party/mesa_headers -I../../../3rdparty/chromium/third_party/libaom/source/libaom -I../../../3rdparty/chromium/v8/include -Igen/v8/include -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-unknown-pragmas -Wno-address -Wno-parentheses -Wno-sign-compare -Wno-stringop-overflow -Wno-stringop-overread -Wno-psabi -Wno-multichar -Wno-format-zero-length -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -msse3 -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -I/home/linuxbrew/.linuxbrew/Cellar/nspr/4.35/include/nspr -I/home/linuxbrew/.linuxbrew/Cellar/nss/3.92/include/nss -I/home/linuxbrew/.linuxbrew/Cellar/icu4c/73.2/include -I/home/linuxbrew/.linuxbrew/Cellar/icu4c/73.2/include -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -Wno-deprecated-copy -std=gnu++2a -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wno-deprecated-declarations -c gen/extensions/browser/browser_sources_jumbo_8.cc -o obj/extensions/browser/browser_sources/browser_sources_jumbo_8.o
2023-08-19T10:07:06.4087270Z In file included from gen/extensions/browser/browser_sources_jumbo_8.cc:6:
2023-08-19T10:07:06.4088421Z ./../../../3rdparty/chromium/extensions/browser/api/web_request/form_data_parser.cc: In member function ‘virtual bool extensions::FormDataParserUrlEncoded::SetSource(base::StringPiece)’:
2023-08-19T10:07:06.4089223Z ./../../../3rdparty/chromium/extensions/browser/api/web_request/form_data_parser.cc:429:11: error: ‘using StringPiece = class absl::string_view’ {aka ‘class absl::string_view’} has no member named ‘set’
2023-08-19T10:07:06.4089384Z   429 |   source_.set(source.data(), source.size());
2023-08-19T10:07:06.4089478Z       |           ^~~
2023-08-19T10:07:06.4090245Z ./../../../3rdparty/chromium/extensions/browser/api/web_request/form_data_parser.cc: In member function ‘virtual bool extensions::FormDataParserMultipart::SetSource(base::StringPiece)’:
2023-08-19T10:07:06.4091221Z ./../../../3rdparty/chromium/extensions/browser/api/web_request/form_data_parser.cc:573:11: error: ‘using StringPiece = class absl::string_view’ {aka ‘class absl::string_view’} has no member named ‘set’
2023-08-19T10:07:06.4091400Z   573 |   source_.set(source.data(), source.size());
2023-08-19T10:07:06.4091636Z       |           ^~~
2023-08-19T10:07:06.4091853Z [25423/28989] CXX obj/extensions/browser/browser_sources/browser_sources_jumbo_16.o
2023-08-19T10:07:06.4092051Z [25424/28989] CXX obj/extensions/browser/browser_sources/browser_sources_jumbo_19.o
2023-08-19T10:07:06.4092247Z [25425/28989] CXX obj/extensions/browser/browser_sources/browser_sources_jumbo_18.o
```

**Comment by iMichka** [comment]
This worked. I opened a PR to ship the fix in ffmpeg separately: #140131

**Comment by iMichka** [comment]
Final PYQT build https://github.com/Homebrew/homebrew-core/actions/runs/5947152260

**Comment by iMichka** [comment]
Bottle has been published #140248

**Pull request closed without merging**
