### PR TITLE
macvim: remove --with-custom-python option

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Follow-up to https://github.com/Homebrew/homebrew-core/pull/22413.

### CODE REVIEW

**Comment by filcab** [comment]
Why, though? Is there a place where I can find the reason to stop supporting this option?
It's very handy to be able to avoid installing python, especially since the system (macOS) comes with it already (fewer possibilities of problems mixing and matching libraries/executables).

Does MacVim require a version of python that's more recent than what's shipped?

**Comment by ilovezfs** [comment]
@filcab we've deprecated all requirements that were able to be satisfied by a default formula. These deprecations are to reduce the deviations between building from source and building/installing bottles.

**Comment by filcab** [comment]
It sucks that using the system python won’t be supported. That invalidates one of my main reasons to pick homebrew: that it used the system libraries/executables as much as possible.

I’ll just keep local patches, as I don’t know that much about homebrew and probably won’t be able to help maintain a different build path.

Thanks for the explanation (and helping support homebrew).

 Filipe

**Comment by ilovezfs** [comment]
@filcab the alternative would be to drop the `python` dependency in the `macvim` formula, and use system Python for everyone. That's not necessarily a bad idea, but it may be more disruptive since about 2/3 of the installs have been the bottle, which has been using Homebrew's Python for a while.

**Comment by MikeMcQuaid** [comment]
> that it used the system libraries/executables as much as possible.

We do still do this "as much as possible" but it's just we're considering "as much as possible" to be "as much as possible while maintaining a high quality" which means matching our majority, bottled, CI environment as much as possible for everyone. I appreciate this doesn't help your use case but I figured it'd help to explain a bit.

**Comment by filcab** [comment]
Yes, I understand that there are lots of other use cases, and mine might not even be too representative (and, as you both mentioned, would require more maintenance work to support. Consistency is good :-) ).

Thanks,

 Filipe

**Comment by PatTheMav** [comment]
FWIW this grinds my gears as well - wondered already why vim all of a sudden needs to install yet another python version on my system, _especially_ as I told it to use python3 instead (but it installs python 2.7 nonetheless).

**Pull request closed without merging**
