### PR TITLE
dpkg 1.20.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> As usual with `dpkg` updates, the `url` tarball source needs mirroring onto Homebrew bintray.

previous upgrade, https://github.com/Homebrew/homebrew-core/pull/41734

**Comment by chenrui333** [comment]
On Mojave
```
00:59:14 i18n.c:27:8: error: unknown type name 'locale_t'
00:59:14 static locale_t dpkg_C_locale;
00:59:14        ^
00:59:14 i18n.c:38:47: error: use of undeclared identifier 'locale_t'
00:59:14         dpkg_C_locale = newlocale(LC_ALL_MASK, "C", (locale_t)0);
00:59:14                                                      ^
00:59:14 i18n.c:38:28: error: use of undeclared identifier 'LC_ALL_MASK'
00:59:14         dpkg_C_locale = newlocale(LC_ALL_MASK, "C", (locale_t)0);
00:59:14                                   ^
00:59:14 i18n.c:61:19: error: use of undeclared identifier 'locale_t'
00:59:14         dpkg_C_locale = (locale_t)0;
00:59:14                          ^
00:59:14 4 errors generated.
00:59:14 make[4]: *** [i18n.lo] Error 1
00:59:14 make[4]: *** Waiting for unfinished jobs....
```

**Comment by alebcay** [comment]
This might fix it:
```
#ifdef __APPLE__
# include <string.h>
# include <xlocale.h>
#endif
```

**Comment by chenrui333** [comment]
That works!

**Pull request closed without merging**
