### PR TITLE
abcl: lowering the compile target JDK version to Java 8

### PR DESCRIPTION
**Pull request by mdbergmann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does it not work with the newer version?

**Comment by mdbergmann** [comment]
The thing is this:

The openjdk dependency installs the latest JDK, but it's not automatically enabled.
But most people using ABCL already have a JDK/Java runtime installed which is probably Java 11 or newer, maybe even Java 8.
So this change to the formula makes sure that ABCL is compiled with largest possible compatibility (not going beyond Java 8) for all people that use Java lower than the latest version.

**Comment by mdbergmann** [comment]
So, if it helps, the risk is low. The only change is lowering the version ABCL is compiled against so that it works against a larger set of possible Java installations.

**Comment by jonchang** [comment]
Squashed, rebased and force pushed. Note that this will have updated your `master` branch. (It's best to send pull requests from a branch of your own fork to avoid problems with maintainers pushing to your `master`)

**Review by jonchang — APPROVED** [review]
Thanks for making your first contribution to Homebrew, @mdbergmann!

**Pull request closed without merging**
