### PR TITLE
recode 3.7.8

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Considering that the GitHub repo hasn't been updated in nearly 7 years, perhaps we should migrate this formula to this fork: https://github.com/rrthomas/recode (latest release was 28 days ago)

The original repo has 57 stars, and the fork has 45

**Comment by SMillerDev** [comment]
Is there any other package managers that use the fork?

**Comment by SeekingMeaning** [comment]
MacPorts, Fedora, and Alpine Linux (anything that uses a stable 3.7.x version: https://repology.org/project/recode/versions)

**Comment by iMichka** [comment]
Can you migrate this to the fork then? Maybe run a quick build test on linux too. I would like to avoid to carry this patch around.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
