### PR TITLE
perl 5.36.0 grokj2k 9.7.8 rxvt-unicode 9.30

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
linux regression failures

```
Error: 32 failed steps!
brew test --retry --verbose clipsafe
brew linkage --test collectd
brew test --retry --verbose ddclient
brew test --retry --verbose extract_url
brew test --retry --verbose feedgnuplot
brew linkage --test freeradius-server
brew test --retry --verbose get_iplayer
brew test --retry --verbose git-svn
brew linkage --test gnumeric
brew linkage --test grokj2k
brew test --retry --verbose grokj2k
brew test --retry --verbose help2man
brew test --retry --verbose imapsync
brew test --retry --verbose innotop
brew linkage --test irssi
brew test --retry --verbose kpcli
brew install latexml
brew test --retry --verbose monkeysphere
brew test --retry --verbose mytop
brew test --retry --verbose perl-build
brew linkage --test pidgin
brew linkage --test postgresql
brew linkage --test postgresql@10
brew linkage --test postgresql@11
brew linkage --test postgresql@12
brew linkage --test postgresql@13
brew linkage --test rxvt-unicode
brew test --retry --verbose rxvt-unicode
brew test --retry --verbose sql-translator
brew test --retry --verbose sslmate
brew test --retry --verbose subversion
brew linkage --test uwsgi
```

**Comment by cho-m** [comment]
I am guessing many Linux failures are due to `libperl.so` linkage and will need revision bumps.

At minimum, we need revision bumps on major/minor `perl` updates like this PR (`5.34 -> 5.36`). This is based on how distros like Arch and Debian use major/minor version in library path.

In Homebrew, linked dependents will also need revision bumps on every patch/revision change since `libperl.so` is linked via Cellar path (see unmerged #84510 for details)

**Comment by bayandin** [comment]
> I am guessing many Linux failures are due to `libperl.so` linkage and will need revision bumps.
> 
> At minimum, we need revision bumps on major/minor `perl` updates like this PR (`5.34 -> 5.36`). This is based on how distros like Arch and Debian use major/minor version in library path.
> 
> In Homebrew, linked dependents will also need revision bumps on every patch/revision change since `libperl.so` is linked via Cellar path (see unmerged #84510 for details)

Makes sense! Will cherry-pick it

**Comment by shenlebantongying** [comment]
May I ask why this is stalled? halted?

**Comment by shenlebantongying** [comment]
This looks stalled. What's wrong? Is there something special already planned for perl5.36?

**Comment by carlocab** [comment]
I'll have a look at this when we merge #98809, since it is pretty close and also modifies some formulae modified here.

**Comment by danielnachun** [comment]
One thing to note - we'll want to update this to Perl 5.37 as that has since been released.

**Comment by danielnachun** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/112161.

**Comment by cho-m** [comment]
`grokj2k` and `mhonarc` were only changes I didn't cherry-pick to minimize impact.
- `grokj2k` has been superseded by #112269
- `mhonarc` is only change left. It may be worth making a separate PR for using macOS `perl`.

**Comment by danielnachun** [comment]
mhonarc: https://github.com/Homebrew/homebrew-core/pull/112316

**Pull request closed without merging**
