### PR TITLE
ios-deploy 1.12.0

### PR DESCRIPTION
**Pull request by taylorkline**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
Undefined symbols for architecture arm64:
  "_AMDeviceCopyDeveloperModeStatus", referenced from:
      _check_developer_mode in ios-deploy.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by taylorkline** [comment]
help wanted

**Comment by chenrui333** [comment]
let me try the revert to see if it works now.

**Comment by chenrui333** [comment]
Should be good for the merge now.

**Review by chenrui333 — APPROVED** [review]

**Comment by taylorkline** [comment]
Thanks @chenrui333 !

**Pull request closed without merging**
