### PR TITLE
faust 2.60.3

### PR DESCRIPTION
**Pull request by nwhetsell**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This updates [Faust](https://faust.grame.fr) to 2.60.3.

I also ran `brew test csound`, and everything seems to work fine on macOS Ventura (13.5.1).

### CODE REVIEW

**Comment by nwhetsell** [comment]
I’m not sure how to fix the Linux failure.

The build appears to fail at a call to `ar`, which is part of [binutils](https://www.gnu.org/software/binutils/) and also built-in to macOS:

https://github.com/Homebrew/homebrew-core/actions/runs/6073776413/job/16476459374?pr=141360#step:4:583

Faust’s build system calls `ar` here:

https://github.com/grame-cncm/faust/blob/2.60.3/build/Make.llvm.static#L46

(The value of `AR` is [`ar` by default](https://github.com/grame-cncm/faust/blob/2.60.3/build/Make.llvm.static#L7).)

I’m not sure whether the `ar` used by Faust is Homebrew’s or the [one included on the runner](https://github.com/actions/runner-images/blob/ubuntu22/20230821.1/images/linux/Ubuntu2204-Readme.md#installed-apt-packages), but I’m able to successfully build Faust on a VMware Fusion virtual machine running Ubuntu 22.04.3. This works whether I use `ar` from binutils 2.38, or I add `depends_on "binutils" => :build` to the formula and run

```rb
ENV["AR"] = Formula["binutils"].bin/"ar"
system "make", "world"
system "make", "install", "LIBNCURSES_PATH=#{Formula["ncurses"].lib}/libncurses.a", "PREFIX=#{prefix}"
```

I can get `ar` to output its usage info if I run

```sh
ar -csr
```

(omitting the required `archive-file` and `file` arguments), but I can’t see how that could happen in [Faust’s Makefile](https://github.com/grame-cncm/faust/blob/2.60.3/build/Make.llvm.static#L46).

**Comment by iMichka** [comment]
That's odd. Does llvm ship it's own `ar` that has a different behaviour?
By the way, would it be possible to build with system llvm on macOS? (remove the brewed llvm dependency)?

Also, can we disable the static build? We prefer shared libraries in Homebrew.

**Comment by nwhetsell** [comment]
@iMichka Thanks for taking a look at this!

> Does llvm ship it's own `ar` that has a different behaviour?

I don’t believe so.

> By the way, would it be possible to build with system llvm on macOS? (remove the brewed llvm dependency)?

It doesn’t look like it (the build fails with `Cannot find program llvm-config (llvm-config or derived expected)`).

> Also, can we disable the static build?

I just pushed a change to attempt this with CMake arguments based on:

* https://github.com/grame-cncm/faust/blob/2.60.3/build/backends/all.cmake
* https://github.com/grame-cncm/faust/blob/2.60.3/build/targets/all.cmake

**Comment by p-linnane** [comment]
Can you squash your commits into one with the message `faust 2.60.3` please? Thanks!

**Comment by nwhetsell** [comment]
@p-linnane Done!

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
