### PR TITLE
qt@5: apply patch for Xcode 14.3

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This should allow us to rebuild this on Ventura after #118902.

Also, let's switch the other KDE patch to use `.diff` to prevent the
checksum for changing on us again.

No idea if the patch even applies, or if I need to specify `directory`, as I'm unable to download the source for some reason.

### CODE REVIEW

**Comment by carlocab** [comment]
Complete logs of build failure: [qt5.tar.gz](https://github.com/Homebrew/homebrew-core/files/11322743/qt5.tar.gz)

**Comment by fxcoudert** [comment]
Error on macOS 11 was:

```
2023-04-26T10:02:06.8277360Z In file included from gen/chrome/browser/extensions/api/generated_api_registration.cc:11:
2023-04-26T10:02:06.8277650Z ../../3rdparty/chromium/chrome/browser/extensions/api/webrtc_logging_private/webrtc_logging_private_api.h:10:10: fatal error: 'chrome/common/extensions/api/webrtc_logging_private.h' file not found
2023-04-26T10:02:06.8277740Z #include "chrome/common/extensions/api/webrtc_logging_private.h"
2023-04-26T10:02:06.8277800Z          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-04-26T10:02:06.8277850Z 1 error generated.
```

which makes no sense. Rerunning on all versions, trying to see better what happens.

**Comment by fxcoudert** [comment]
On macOS 12 Intel, we now have a compiler crash 😭 

```
2023-04-29T09:45:13.3052000Z clang: error: unable to execute command: Abort trap: 6
2023-04-29T09:45:13.3052510Z clang: error: clang frontend command failed due to signal (use -v to see invocation)
2023-04-29T09:45:13.3052780Z Apple clang version 14.0.0 (clang-1400.0.29.202)
2023-04-29T09:45:13.3053150Z Target: x86_64-apple-darwin21.6.0
2023-04-29T09:45:13.3053250Z Thread model: posix
2023-04-29T09:45:13.3053860Z InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Review by fxcoudert — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks for the effort chasing this @fxcoudert! Without your contributions it'd be impossible to keep homebrew going. You can feel good knowing that you've made the world a lot better for homebrew users around the world! 👍 🎉

**Comment by carlocab** [comment]
Thanks @fxcoudert!

**Pull request merged**
