### PR TITLE
Revert skaffold 1.17.1 due to incorrect binaries

### PR DESCRIPTION
**Pull request by tejal29**
This reverts commit bc9bec3f5a4db6e1a53bc56475bfda0501a8417f.

- [ X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@tejal29 based on my reading of the other thread, the version tag `v1.17.1` is there, right?
https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.17.1

Is there anyway that you can roll forward rather than rollback? I am saying that is because the homebrew version revert is little bit tricky.

**Comment by tejal29** [comment]
@chenrui333 thanks for quick reply. 
Yes v1.17.1 is still there. We have uploaded the right binaries now. I was hoping to manually bump the release.

Re: Roll forward, we don't have a new release planned until next year 2021. I was hoping to avoid another dummy release to just fix the version.

**Comment by SMillerDev** [comment]
Homebrew shouldn't be downloading binaries though, so is it even affected?

**Comment by tejal29** [comment]
closed due to v1.17.2 release of skaffold.

**Comment by tejal29** [comment]
> Homebrew shouldn't be downloading binaries though, so is it even affected?

Thanks @SMillerDev we ended by doing a minor release for other issues.

Re: Homebrew shouldn't be downloading binaries though, so is it even affected?

If Users have already installed using `homebrew upgrade` and picked up incorrect binaries, how can they pick up the correctly binary for the same version?

**Pull request closed without merging**
