### PR TITLE
tm: add completions

### PR DESCRIPTION
**Pull request by max-ae**
split from #110148

### CODE REVIEW

**Comment by SMillerDev** [comment]
Needs a rebase

**Comment by chenrui333** [comment]
```
  Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /home/linuxbrew/.linuxbrew/Cellar/tm/1.21.0/bin/tm completion bash` exited with 1. Here's the output:
Truncated install --build-bottle tm output
```

**Comment by max-ae** [comment]
I have no idea why this is failing... It's not a permissions issue

**Comment by cho-m** [comment]
> Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /home/linuxbrew/.linuxbrew/Cellar/tm/1.21.0/bin/tm completion bash` exited with 1. Here's the output:
> Truncated install --build-bottle tm output

On a side note, we probably should find a way to make the output more useful. Most failures I've seen are sent to stderr, which `brew`'s popen will send to /dev/null unless `HOMEBREW_STDERR` is set or `err: ...` is passed in. This leads to the blank `Here's the output:` making it difficult to debug.

---

Anyways, running with `{ err: :err }` set, I at least see what went wrong:
```
2022/12/18 09:55:15 stat /private/tmp/tm-20221218-96181-11jpq9c/tm-1.21.0/.brew_home/.kube/config: no such file or directory, falling back to in-cluster configuration
2022/12/18 09:55:15 unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /usr/local/Cellar/tm/1.21.0/bin/tm completion bash` exited with 1. Here's the output:
```

The command is trying to load a cluster config even when running `tm completion`.

**Pull request closed without merging**
