### PR TITLE
Remove seldom-used versioned formulas

### PR DESCRIPTION
**Pull request by fxcoudert**
Following https://github.com/Homebrew/brew/pull/3697, here is a list of versioned formulas, sorted by number of installs over 30 days: https://gist.github.com/fxcoudert/70b0820c76aff061de446574b076703b

Here is a PR removing those that have 50 installs a month or lower, and are not currently used as dependency inside homebrew-core.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can we use 30 days and 90 days and only remove those not in both?

**Comment by ilovezfs** [comment]
@DomT4 any of these you think should be spared the axe?

**Comment by DomT4** [comment]
Not sure whether the `libxml@2.9`, `libpng@1.6`, etc aliases should continue existing for the current versions? It's possible people are relying on that in some way. `varnish@4` is still supported upstream and potentially could be spared.

Nothing else jumps out at me beside those things though.

**Comment by ilovezfs** [comment]
I could see that affecting a few people but we probably don't want to set a precedent of preserving @ aliases for things that once upon a time had a versioned formula but don't anymore.

1st column install events in last 30 days
2nd column install events in last 90 days
```
0 10 ledger@2.6
2 19 apache-spark@1.5
4 21 perl@5.14
5 16 zeromq@4.1
6 21 juju@1.25
6 36 jpeg@6
8 23 laszip@2
8 29 jetty@8
9 24 zeromq@4.0
11 11 librealsense@1
11 57 selenium-server-standalone@2.45
11 57 srtp@1.6
12 57 azure-cli@1
14 85 open-mpi@1.6
18 67 docker@1.11
19 35 kubernetes-cli@1.3
19 71 autoconf@2.64
20 68 go@1.5
21 52 swig@2
21 84 logstash@2.4
22 66 automake@1.12
23 48 bazel@0.2
23 84 gsl@1
27 67 redis@2.6
29 62 influxdb@0.8
29 86 grails@2.5
32 116 antlr@3
32 138 apache-spark@1.6
32 138 eigen@3.2
33 98 libxml2@2.7
34 145 glfw@2
35 142 varnish@4
36 95 percona-server@5.5
38 175 unison@2.40
38 176 solr@5.5
39 53 libpqxx@3
40 79 zeromq@3.2
42 129 clang-format@3.8
45 140 libpng@1.2
45 205 gnuplot@4
50 122 logstash@5.6
```

**Comment by ilovezfs** [comment]
If I divide the 90 days by 3, and sort by that
```
3.33333 0 ledger@2.6
3.66667 11 librealsense@1
5.33333 5 zeromq@4.1
6.33333 2 apache-spark@1.5
7 4 perl@5.14
7 6 juju@1.25
7.66667 8 laszip@2
8 9 zeromq@4.0
9.66667 8 jetty@8
11.6667 19 kubernetes-cli@1.3
12 6 jpeg@6
16 23 bazel@0.2
17.3333 21 swig@2
17.6667 39 libpqxx@3
19 11 selenium-server-standalone@2.45
19 11 srtp@1.6
19 12 azure-cli@1
20.6667 29 influxdb@0.8
22 22 automake@1.12
22.3333 18 docker@1.11
22.3333 27 redis@2.6
22.6667 20 go@1.5
23.6667 19 autoconf@2.64
26.3333 40 zeromq@3.2
28 21 logstash@2.4
28 23 gsl@1
28.3333 14 open-mpi@1.6
28.6667 29 grails@2.5
31.6667 36 percona-server@5.5
32.6667 33 libxml2@2.7
38.6667 32 antlr@3
40.6667 50 logstash@5.6
43 42 clang-format@3.8
46 32 apache-spark@1.6
46 32 eigen@3.2
46.6667 45 libpng@1.2
47.3333 35 varnish@4
48.3333 34 glfw@2
58.3333 38 unison@2.40
58.6667 38 solr@5.5
68.3333 45 gnuplot@4
```

**Comment by ilovezfs** [comment]
@fxcoudert so maybe we spare varnish@4, solr@5.5 and gnuplot@4

**Pull request merged**
