### PR TITLE
aws-sdk-cpp 0.10.14

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Bump aws-sdk-cpp stable version from 0.10.10 to 0.10.14

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 Not sure what voodoo is needed to get the CI working for this one again ;)

**Comment by DomT4** [comment]
Oh, just whack the `Rebuild` button here. Should do the trick. No voodoo required 😜.

**Comment by ilovezfs** [comment]
pretty sure I've done that more than once now but I could be imagining it for sure

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/c583d47727665fd751c6d7a06bfc879b76e422e6. Thanks again @Jerzerak!

**Comment by theopolis** [comment]
Heads up, this started breaking the downstream osquery dependency, see: https://github.com/facebook/osquery/issues/2107

**Comment by Jerzerak** [comment]
@theopolis I've got #1278 pending and an osquery 1.7.4 PR coming tonight hopefully

**Pull request closed without merging**
