### PR TITLE
upx 4.0.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by equal-l2** [comment]
The license seems to be `GPL-2.0-or-later`.

https://github.com/upx/upx/blob/fdec47a83daab27414fe2c4f617ced1c78365008/LICENSE#L51-L65

**Comment by chenrui333** [comment]
```
  ==> Applying 51f69a20e0287904398bbf4c72ba2f809a0b0850.patch
  patch -g 0 -f -p1 -i /tmp/upx--patch-20221118-3881-1uk3an6/51f69a20e0287904398bbf4c72ba2f809a0b0850.patch
  patching file src/p_mach.cpp
  Hunk #1 FAILED at 1194.
  1 out of 1 hunk FAILED -- saving rejects to file src/p_mach.cpp.rej
```

**Comment by iredmail** [comment]
Dear @Porkepix, any plan to fix it and resend the PR?

**Comment by chenrui333** [comment]
This is a blocker for the upgrade, https://github.com/upx/upx/issues/628

**Comment by chenrui333** [comment]
#116052

**Pull request closed without merging**
