### PR TITLE
various formulae: use `.diff` for GitLab patches

### PR DESCRIPTION
**Pull request by carlocab**
Companion to https://github.com/Homebrew/brew/pull/10760.

The tricky part here is that the tap_syntax test will prevent this PR from being tested until the PR linked above is merged.

### CODE REVIEW

**Comment by Rylan12** [comment]
> The tricky part here is that the tap_syntax test will prevent this PR from being tested until the PR linked above is merged.

I think it's probably fine to temporarily remove the audit so this can be merged. Any new violations will technically not be violations anymore once https://github.com/Homebrew/brew/pull/10760 is merged so I don't think it's would be an issue

**Review by Rylan12 — DISMISSED** [review]

**Comment by carlocab** [comment]
> I think it's probably fine to temporarily remove the audit so this can be merged.

Aha, yes, ok. I'll find some time to do this next week.

**Comment by carlocab** [comment]
Oops. Forgot about this.

**Comment by carlocab** [comment]
Ok. Merging this one. I need to split up my Linux PR because of the timeout though.

**Pull request merged**
