### PR TITLE
pcre2 10.30

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Let's remove the `make check` step (and let upstream do their own quality control). At the mean time, please file a report to upstream.

**Comment by vszakats** [comment]
I'm not promising an upstream report, though: It's a mailing list with manual approval for non-member reports. Tried and failed just recently.

**Comment by ilovezfs** [comment]
Thanks @vszakats!

**Comment by vszakats** [comment]
Thanks to the individual who kindly reported the check issue, here:
https://lists.exim.org/lurker/thread/20170816.202110.ddf9eded.en.html

(The issue is innocent and with a fix already posed.)

**Pull request closed without merging**
