### PR TITLE
qt: patches for Xcode 15

### PR DESCRIPTION
**Pull request by fxcoudert**
Will require https://github.com/Homebrew/homebrew-core/pull/149337 merged first, to bottle on Sonoma

### CODE REVIEW

**Comment by fxcoudert** [comment]
Cancelling build, with Xcode 15 we're seeing this:

```
2023-10-04T02:18:18.5790010Z /tmp/qt-20231003-8606-cq0gtt/qt-everywhere-src-6.5.1/qtmultimedia/src/plugins/multimedia/darwin/camera/avfcamerautility.mm:72:35: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
2023-10-04T02:18:18.5798540Z struct FormatHasNoFPSRange : std::unary_function<AVCaptureDeviceFormat *, bool>
2023-10-04T02:18:18.5798750Z                              ~~~~~^~~~~~~~~~~~~~
2023-10-04T02:18:18.5798900Z                                   __unary_function
2023-10-04T02:18:18.5799300Z /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
2023-10-04T02:18:18.5799620Z using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
2023-10-04T02:18:18.5799900Z ^
2023-10-04T02:18:18.5800010Z 1 error generated.
```

Patch is known (see `qt@5`).

**Comment by fxcoudert** [comment]
Patch for 6.5 is slightly different from qt@5 (file has moved)

**Review by iMichka — APPROVED** [review]

**Comment by ZeldaZach** [comment]
Was dropping qt for MacOS Big Sur intentional with this change?

50541d2ff86812fcf3b2e9d0cca901c58b47fab2

**Comment by fxcoudert** [comment]
Like Apple, we only actively support (and provide binaries for) the 3 most recent macOS versions. At this time, those are Sonoma, Ventura and Monterey. macOS Big Sur is unsupported as of Sonoma's release date.

We will not remove Big Sur binaries/bottles from formulas that have them, but we have switched our machines to build for Sonoma instead, so we cannot provide new binaries/bottles when a formula is updated.

**Pull request merged**
