### PR TITLE
azion 2.1.0

### PR DESCRIPTION
**Pull request by marcusgrando**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## Changelog
### New Features
* bd78c6dd2a3ec0b03743b77fc0cff20c3a6d4ebb feat: add logs to debug flag during deploy
* 51e6139736bb45f03cdbb79eb89d785d0b3ea53f feat: allow local deploy with flag
* 8c00809cb097d479676e2039f054d014ef36c74d feat: new flag --port in dev command
### Improvements
* 2d79a92dfeb40256c53f28619e4bc160bea6570b chore(deps): bump github.com/zcalusic/sysinfo from 1.0.2 to 1.1.2
* 25ae8331da56ee32764495f71971979fa14411da chore: add build on link command
* 5f7fe5ed367356c4079925282d1ca34f09febef3 chore: increase hard-coded timeout for http calls
* f3128760a75aea51254aefb3f62d6f7680e958a8 chore: read azion.json
* 4a7dd48948c800bb7a7b207f0826fae32b7055fb chore: update link message
* d6f85774b0bebfbc210b962b41fecd0c575a3460 chore: update messages during deploy
### Other Work
* 96a6c39b8739f40ba1050da45d7fd28d630dccca refactor: lint fields not used
* 24ed7a4580ed48c77d0cf99a82e72844729229b4 refactor: remove comment

</pre>
</details>

### CODE REVIEW

**Comment by PatrickMenoti** [comment]
Apparently a workflow failed. What would be the reason? 🤔

**Comment by stefanb** [comment]
the test [failed](https://github.com/Homebrew/homebrew-core/actions/runs/11468766311/job/31920109491?pr=195272#step:4:54) with:
`==> /home/linuxbrew/.linuxbrew/Cellar/azion/2.1.0/bin/azion build --yes 2>&1
  Error: Failed to build your resource. Azion configuration not found. Make sure you are in the root directory of your local repository and have already initialized or linked your resource with the commands 'azion init' or 'azion link'`

**Comment by PatrickMenoti** [comment]
> 

That message has been the same way for a very long time. Even when I first wrote the test 🤔

**Comment by PatrickMenoti** [comment]
Should I update the tests to check for the entire string? 
I thought that assert checked if the string appeared in the response.

**Comment by PatrickMenoti** [comment]
We've encountered the problem. Apparently the status code returned is different than expected for some reason. 
We'll be releasing a new Patch. 
You guys may close this PR please.

**Comment by stefanb** [comment]
Superseded by
* https://github.com/Homebrew/homebrew-core/pull/195358

**Pull request closed without merging**
