### PR TITLE
libatomic_ops: use `cmake` to build

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is what upstream uses in their CI.[^1]

[^1]: https://github.com/ivmai/libatomic_ops/blob/cc9bc49ae39fcfdf75efb971c74393a313d70491/.github/workflows/cmake-build.yml

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
May need to set `CMAKE_INSTALL_RPATH`:

```
Files with missing rpath:
  /opt/homebrew/Cellar/libatomic_ops/7.8.2/lib/libatomic_ops_gpl.1.2.1.dylib
```

**Comment by carlocab** [comment]
Yep, good catch.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by carlocab** [comment]
Needed to fix a conflict with `master`.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/10792318413

**Pull request merged**
