### PR TITLE
wxpython: add license + update homepage

### PR DESCRIPTION
**Pull request by urwrstkn8mare**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Updated the homepage to what seemed more suitable (their official homepage) and added the license in the formula as well (2 different commits). (Inspiration: https://github.com/Homebrew/homebrew-core/issues/58225)

See: https://wxpython.org/pages/license/

### CODE REVIEW

**Review by Rylan12 — DISMISSED** [review]
Thanks for the PR, @urwrstkn8mare!

This looks correct to me. The style issue seems to be a bug. I'm looking into it

**Comment by Rylan12** [comment]
Okay, I've created a fix in https://github.com/Homebrew/brew/pull/8862. Once that's merged this will be good to go!

**Comment by Rylan12** [comment]
The fix has been merged, but you'll need to rebase your branch onto the latest `master` to fix the new issue.

**Comment by urwrstkn8mare** [comment]
@Rylan12 do I need to fix the issue to merge? If so, is there any easy way to rebase my branch onto the latest `master`.

**Comment by Rylan12** [comment]
The issue was unrelated to this PR, so this should be good to go once CI runs (I went ahead and rebased for you).

You can use the `git rebase` and `git push --force` commands to do this in the future (there's a brief explanation [here](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#following-up))

**Comment by urwrstkn8mare** [comment]
Thanks a lot for that. I'll make sure to have a look so in the future I'm able to do it myself. :)

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Thanks again, @urwrstkn8mare!

If you're curious, maybe check out https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase for a more in-depth explanation of what a rebase is and how to do it

**Pull request merged**
