### PR TITLE
openmodelica 1.17.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like it's building its own Ipopt. It should be using the Homebrew version.

Any chance you could take a look at this, @alexchandel?

**Comment by alexchandel** [comment]
@carlocab the formula uses lpopt already, it's pretty deep in the build system IIRC.  I can look into removing it but 1.16.5 already does the same thing.  Can we just merge for now & keep status quo?

**Comment by carlocab** [comment]
Had I known 1.16.5 was doing that, I'd have told you the same thing about using Homebrew Ipopt. In any case, this didn't build, so there's nothing to merge.

**Comment by alexchandel** [comment]
@carlocab can you trigger a rebuild so I can see it with latest?

**Comment by carlocab** [comment]
The log is still available, so I'm not sure there's a need to re-run it on CI.

**Comment by cho-m** [comment]
There are at least 2 build issues relating to newer versions of tools:
1. `autoconf 2.71+` - Probably need to switch to `autoreconf` like doc change says https://github.com/OpenModelica/OpenModelica/pull/7324
2. `cmake 3.20+` - Errors with `--build` argument in `cmake`. See issue https://github.com/OpenModelica/OpenModelica/issues/7330. Probably need patch or upstream fix since Homebrew is building with `3.20.2`

---

Also, there was an old PR for using system libraries (Ipopt, ...): https://github.com/OpenModelica/OpenModelica/pull/983#issuecomment-647161981. Currently, doesn't seem to be supported.

**Comment by carlocab** [comment]
Thanks for having a look at this, @cho-m.

> Also, there was an old PR for using system libraries (Ipopt, ...): [OpenModelica/OpenModelica#983 (comment)](https://github.com/OpenModelica/OpenModelica/pull/983#issuecomment-647161981). Currently, doesn't seem to be supported.

This sounds like the typical upstream response to requests not to use vendored dependencies.

**Comment by cho-m** [comment]
@alexchandel It should be possible to fix some of the basic build issues now if you want to work on this by:
- replacing `system "autoconf"` with `system "autoreconf", "--install"`
- Add patch from this commit: https://github.com/OpenModelica/OpenModelica/commit/71aa2f871639041f3569fafe1b1cea25b84981ff

There may be other issues that occur afterward, but this should at least get you past the current build issues.

**Pull request closed without merging**
