### PR TITLE
odin 2024-05

### PR DESCRIPTION
**Pull request by laytan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @laytan!

**Comment by laytan** [comment]
Weird failure, will have to look at that later

**Comment by chenrui333** [comment]
`  gcc-11: error: unrecognized command-line option ‘-target’`

---

gcc command line option issue

**Comment by laytan** [comment]
> ` gcc-11: error: unrecognized command-line option ‘-target’`
> 
> gcc command line option issue

Yep, although Odin does not use gcc so it somehow used it instead of clang, will see if I can hit that locally

**Comment by laytan** [comment]
So it looks like brew forces the usage of gcc during installation? This is technically fine because Odin (the compiler) can be build with gcc, but programs build by the Odin compiler require clang for linking.

Odin runs a demo/example program by default after the build which we can disable by doing: `inreplace "build_odin.sh", /^\s*run_demo\s*$/, ""`, after that is done the installation succeeds, and afaik once installed it gets to use clang like normal and it all works.

Shall I add the `inreplace` or is there a better solution here?

**Comment by chenrui333** [comment]
> Odin runs a demo/example program by default after the build which we can disable by doing: `inreplace "build_odin.sh", /^\s*run_demo\s*$/, ""`, after that is done the installation succeeds, and afaik once installed it gets to use clang like normal and it all works.

I think it is fine. (can you also leave a note in the code as well)

**Comment by laytan** [comment]
> > Odin runs a demo/example program by default after the build which we can disable by doing: `inreplace "build_odin.sh", /^\s*run_demo\s*$/, ""`, after that is done the installation succeeds, and afaik once installed it gets to use clang like normal and it all works.
> 
> I think it is fine. (can you also leave a note in the code as well)

Alright, thanks for the help!

**Review by chenrui333 — APPROVED** [review]
Thanks!

**Pull request merged**
