### PR TITLE
switch to HTTPS for SVN access on sf.net #2

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by DomT4** [comment]
Cross referencing myself in case someone else asks the same thing: https://github.com/Homebrew/homebrew-core/pull/10841#issuecomment-285678304

**Comment by vszakats** [comment]
Moved `synfig` here from #10827, and added one update that I forgot to commit (`zboy`).

**Comment by vszakats** [comment]
`quex` moved to #10886 to fix its broken download with a version bump.

**Comment by vszakats** [comment]
`stella` moved to GitHub.

**Comment by vszakats** [comment]
No failure on Sierra, and the expected SVN certificate failure on the previous systems.

**Comment by ilovezfs** [comment]
Same comment as the other one. For the stable URLs, let's branch so it doesn't fail CI. You won't need to do so for vgmstream because it's now available on GitLab: https://gitlab.kode54.net/kode54/vgmstream

**Comment by ilovezfs** [comment]
Thanks @vszakats

**Pull request merged**
