### PR TITLE
micromamba 1.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
build/test out fine in my local.

**Comment by ZhongRuoyu** [comment]
Patch upstreamed. Not a language lawyer, but it seems to me that this was due to the lack of an implicit default constructor for `std::stringstream` in Big Sur's libc++. If I understand it correctly, this is related to the discussion on copy-list-initialization in https://stackoverflow.com/a/38419922.

**Comment by ZhongRuoyu** [comment]
Also, it seems that this is not marked as the latest release yet: https://github.com/mamba-org/mamba/releases

**Comment by Porkepix** [comment]
Might be able to use `openssl@3`; also, why does it refer to a python 3.9 here in tests? https://github.com/Homebrew/homebrew-core/pull/126371/files#diff-1b9e82faf624f370bbb589471eafe777d87c0c6051c92d963fc0eb548efa1271R92
Shouldn't it point to a 3.11, here? Or I completely misunderstand this?

**Comment by ZhongRuoyu** [comment]
> Might be able to use `openssl@3`

👍

> also, why does it refer to a python 3.9 here in tests

This has nothing to do with the newest Python version. (Also note that no Python is available in the test.) What this test does is to create a new [environment](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html) with Python 3.9 downloaded and installed.

**Review by dawidd6 — APPROVED** [review]

**Pull request merged**
