### PR TITLE
Update paths override for 0.1.40 release

### PR DESCRIPTION
**Pull request by glensc**
Fix https://github.com/Homebrew/homebrew-core/pull/45834 for skopeo 0.1.40.

The paths have changed again in 0.1.40 release.

cc @chenrui333

### CODE REVIEW

**Review by jonchang — CHANGES_REQUESTED** [review]
Please remove the change that touches the `rebuild` number in the bottle block. This will automatically be updated by our bottling infrastructure.

**Comment by SMillerDev** [comment]
Can you squash your commits to `skopeo: update paths override`?

**Comment by glensc** [comment]
squashed as 264bfbda3f1

why not use squash and merge option?
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits

**Comment by SMillerDev** [comment]
You asked this before but we can't provide bottles if we use squash and merge.

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Pull request closed without merging**
