### PR TITLE
dynare: delete

### PR DESCRIPTION
**Pull request by houtanb**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Dynare will no longer be maintained in Hombrew as we now depend on the version of Octave distributed via the Octave app.

Thank you so much for the work you do in maintaining this valuable ecosystem.

### CODE REVIEW

**Comment by Bo98** [comment]
> Dynare will no longer be maintained in Hombrew

Just to be clear: we don't have a notion of maintainers of individual formulae and as such don't require upstream to be providing the support, in case that was an issue here.

> now depend on the version of Octave distributed via the Octave app

Can you clarify? Does this mean that newer versions will refuse to compile against Octave located anywhere else (i.e. are you using features unique to Octave app)?

**Comment by houtanb** [comment]
Hi @Bo98 thanks for your response.

It actually works with Octave 5.2 so that shouldn't be a problem. I just thought that since we were no longer directing users to come here that perhaps you would want to get rid of it.

To make 4.6.0 compile, it must be compiled with support for C++17 and to make dynare run, `gcc-9` must be installed on the user's system. Those should be the only changes to make to the formula between this version and the previous version.

**Comment by SMillerDev** [comment]
Unless it is actively broken or no longer open source we don't really delete formula.

**Comment by houtanb** [comment]
Ok, well it is currently two versions behind the latest release, 4.6.1.

**Comment by issyl0** [comment]
There's a PR to attempt the update to 4.6.1 at #51706. Let's see if that works before we make a decision here?

**Comment by SMillerDev** [comment]
The decision is "homebrew only deletes things that are unworkably broken"

**Pull request closed without merging**
