### PR TITLE
mariadb-connector-odbc 3.1.3

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
16:37:29 cd /tmp/mariadb-connector-odbc-20190515-13118-1id694x/mariadb-connector-odbc-3.1.1-ga-src/osxinstall && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DHAVE_OPENSSL -DMAODBC_DEBUG -DSQLCOLATTRIB_SQLLEN_PTR -I/tmp/mariadb-connector-odbc-20190515-13118-1id694x/mariadb-connector-odbc-3.1.1-ga-src -I/tmp/mariadb-connector-odbc-20190515-13118-1id694x/mariadb-connector-odbc-3.1.1-ga-src/libmariadb/include -I/usr/local/Cellar/libiodbc/3.52.12/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/install_driver.dir/install_driver.c.o   -c /tmp/mariadb-connector-odbc-20190515-13118-1id694x/mariadb-connector-odbc-3.1.1-ga-src/osxinstall/install_driver.c
16:37:29 Scanning dependencies of target maodbc
16:37:29 /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/maodbc.dir/build.make CMakeFiles/maodbc.dir/build
16:37:29 /tmp/mariadb-connector-odbc-20190515-13118-1id694x/mariadb-connector-odbc-3.1.1-ga-src/osxinstall/install_driver.c:111:31: error: use of undeclared identifier 'FALSE'
16:37:29   SQLRemoveDriver(DriverName, FALSE, &UsageCount);
16:37:29                               ^
16:37:29 /tmp/mariadb-connector-odbc-20190515-13118-1id694x/mariadb-connector-odbc-3.1.1-ga-src/osxinstall/install_driver.c:116:122: error: use of undeclared identifier 'FALSE'
16:37:29   if (SQLInstallDriverEx(DriverDescr, DriverDir, OutLocation, sizeof(OutLocation), NULL, ODBC_INSTALL_COMPLETE, NULL) == FALSE)
16:37:29                                                                                                                          ^
16:37:29 2 errors generated.
16:37:29 make[2]: *** [osxinstall/CMakeFiles/install_driver.dir/install_driver.c.o] Error 1
16:37:29 make[1]: *** [osxinstall/CMakeFiles/install_driver.dir/all] Error 2
16:37:29 make[1]: *** Waiting for unfinished jobs....
```

Dont quite understand the errors.

**Comment by chenrui333** [comment]
@SMillerDev I need some help to fix the build issue on this PR.

**Comment by SMillerDev** [comment]
I have no idea either, check if this is the latest from upstream and report an issue for it if you don't know how to fix it.

**Comment by Bo98** [comment]
This is in among the pkg build. Maybe try only building the `maodbc` target? Try `make maodbc install/local/fast`. Completely untested so might not work at all.

**Comment by chenrui333** [comment]
Refresh the PR to the latest version

**Pull request closed without merging**
