### PR TITLE
grpc: Fix build

### PR DESCRIPTION
**Pull request by Mizux**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Mizux** [comment]
this is a fix for the PR #62803

**Comment by SMillerDev** [comment]
Please also include a test that would indicate this in the future.

**Comment by SMillerDev** [comment]
Since grpc depends on abseil here: https://github.com/Homebrew/homebrew-core/pull/62916/files#diff-2325170da0acac021ad144f5df99ce0062d90d8b489de582e8bef1e3c0ad1008R29 that means that any abseil update will run the `test` block in the formula. Clearly the current test isn't good enough or it would have blocked your abseil PR. Please update the test block to add something that fails in the current situation.

**Comment by Mizux** [comment]
[0]─[/usr/local/Cellar]
[^v^]─corentinl@corentinl-macbookair %otool -L grpc/1.32.0_1/lib/*.dylib | grep absl
[1]─[/usr/local/Cellar]

on my way to try to build a test, but at least no grpc dylib depends on abseil -> build dependency :thinking: ?

**Comment by Mizux** [comment]
abseil is build as static libs (.a) need to check if grpc headers i.e. public include depends on abseil ones or not

**Comment by Mizux** [comment]
no installed headers depends on abseil only the grpc-config.cmake and the .pc file
```sh
[0]─[/usr/local/Cellar]
[^v^]─corentinl@corentinl-macbookair %grep -rIn "absl_" grpc/1.32.0_1 
grpc/1.32.0_1/lib/pkgconfig/grpc.pc:11:Libs: -L${libdir} -lgrpc -laddress_sorting -lre2 -lupb -lcares -lz -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_exponential_biased -labsl_hash -labsl_bad_variant_access -labsl_city -labsl_status -labsl_cord -labsl_bad_optional_access -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_stacktrace -labsl_debugging_internal -labsl_malloc_internal -labsl_time -labsl_time_zone -labsl_civil_time -labsl_strings -labsl_strings_internal -labsl_throw_delegate -labsl_int128 -labsl_base -labsl_spinlock_wait -labsl_raw_logging_internal -labsl_log_severity -labsl_dynamic_annotations
grpc/1.32.0_1/lib/pkgconfig/gpr.pc:11:Libs: -L${libdir} -lgpr -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_stacktrace -labsl_debugging_internal -labsl_malloc_internal -labsl_time -labsl_time_zone -labsl_civil_time -labsl_strings -labsl_strings_internal -labsl_throw_delegate -labsl_int128 -labsl_base -labsl_spinlock_wait -labsl_raw_logging_internal -labsl_log_severity -labsl_dynamic_annotations
grpc/1.32.0_1/lib/pkgconfig/grpc++_unsecure.pc:11:Libs: -L${libdir} -lgrpc++_unsecure -labsl_status -labsl_cord -labsl_bad_optional_access -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_stacktrace -labsl_debugging_internal -labsl_malloc_internal -labsl_time -labsl_time_zone -labsl_civil_time -labsl_strings -labsl_strings_internal -labsl_throw_delegate -labsl_int128 -labsl_base -labsl_spinlock_wait -labsl_raw_logging_internal -labsl_log_severity -labsl_dynamic_annotations
grpc/1.32.0_1/lib/pkgconfig/grpc++.pc:11:Libs: -L${libdir} -lgrpc++ -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_exponential_biased -labsl_hash -labsl_bad_variant_access -labsl_city -labsl_status -labsl_cord -labsl_bad_optional_access -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_stacktrace -labsl_debugging_internal -labsl_malloc_internal -labsl_time -labsl_time_zone -labsl_civil_time -labsl_strings -labsl_strings_internal -labsl_throw_delegate -labsl_int128 -labsl_base -labsl_spinlock_wait -labsl_raw_logging_internal -labsl_log_severity -labsl_dynamic_annotations
grpc/1.32.0_1/lib/pkgconfig/grpc_unsecure.pc:11:Libs: -L${libdir} -lgrpc_unsecure -labsl_status -labsl_cord -labsl_bad_optional_access -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_stacktrace -labsl_debugging_internal -labsl_malloc_internal -labsl_time -labsl_time_zone -labsl_civil_time -labsl_strings -labsl_strings_internal -labsl_throw_delegate -labsl_int128 -labsl_base -labsl_spinlock_wait -labsl_raw_logging_internal -labsl_log_severity -labsl_dynamic_annotations
grpc/1.32.0_1/lib/cmake/grpc/gRPCConfig.cmake:17:if(NOT absl_FOUND)
[0]─[/usr/local/Cellar]
```

so I'm not sure grpc once installed depends on abseil.
Feel free to do whatever you want with this PR...

**Comment by Mizux** [comment]
@SMillerDev So after investigating grpc I think you need two separate PR, this one fix the grpc build, and an other one once grpc fix its cmake-config, pkg-config (i.e. release a new version) If i add a cmake/pc test in this PR it will just block it since its a bug in grpc extra file, while you could already at least fix the grpc build using this PR imho

ps: If you want, we can have a chat on discord (ortools discord https://discord.gg/ENkQrdf)  or IIRC (freenode user: mizux) where we can talk...

**Comment by jeroen** [comment]
This was already merged in https://github.com/Homebrew/homebrew-core/commit/8912ce907a328e0874d8eca9ff31b3926de53573. Can be closed.

**Pull request closed without merging**
