### PR TITLE
graphviz 2.44.1

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
groff -Tps -man cdt.3 >cdt.3.ps
  CCLD     libcdt.la
  CCLD     libcdt_C.la
false cdt.3.ps cdt.3.pdf
make[3]: *** [cdt.3.pdf] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

**Comment by chenrui333** [comment]
Should be good now.

**Comment by Bo98** [comment]
Bit weird it needs GhostScript in a patch release. I think there's a bug somewhere.

**Comment by Bo98** [comment]
Does replacing

```
AC_CHECK_PROG(PS2PDF,ps2pdf,ps2pdf,false)
AC_CHECK_PROG(PS2PDF,pstopdf,pstopdf,false)
```

with

```
AC_CHECK_PROGS(PS2PDF,ps2pdf pstopdf,false)
```

work?

(Will require invoking `./autogen.sh`)

**Comment by chenrui333** [comment]
Let me try that suggestion later.

**Comment by chenrui333** [comment]
Applied your change, but failed with the same error:

```
false cdt.3.ps cdt.3.pdf
make[3]: *** [cdt.3.pdf] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

**Comment by Smattr** [comment]
Sorry a bit late to the party on this one, but the cause of the `ps2pdf` failure was likely this: https://gitlab.com/graphviz/graphviz/-/commit/74f181aa9d9ee519cd2444267850038c90056329. We discovered `ps2pdf` detection wasn't working correctly and compilation was silently producing empty PDFs when you didn't have it installed.

Graphviz does not bump major or minor version for changes that only affect users building from source. We also unfortunately don't have the resources to actively watch package ecosystems like Homebrew that are consuming Graphviz releases. Obviously this situation is not ideal.

However, the patch you applied looks like a general fix. If you have time to post this as a Merge Request to the Graphviz repository, I think we'd happily accept this upstream.

**Comment by kaoh** [comment]
I still see this error when running `brew install graphviz` under Linux inside the Docker brew image. Any idea how to fix this? I installed ghostscript and groff, but the `AC_CHECK_PROGS` does not seem to detect it.

**Comment by kaoh** [comment]
It seems to be working now.

**Pull request closed without merging**
