### PR TITLE
[docker-cloud] Remove formula since this is no longer valid

### PR DESCRIPTION
**Pull request by nandhini915**
Signed-off-by: Nandhini <nandhini@docker.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[Cluster management](https://docs.docker.com/docker-cloud/getting-started/intro_cloud/) on Docker Cloud (cloud.docker.com) was a feature provided to Docker customers until [May 2018](https://docs.docker.com/docker-cloud/migration/). 

The PR removes the `docker-cloud` formula from homebrew since the formula can not be used going forward.

### CODE REVIEW

**Comment by javian** [comment]
This perhaps ? https://blog.containership.io/k8sfordockercloud

**Comment by nandhini915** [comment]
Apologies for not responding sooner. 

[Cluster management](https://docs.docker.com/docker-cloud/getting-started/intro_cloud/) on Docker Cloud (cloud.docker.com) was a feature provided to Docker customers until [May 2018](https://docs.docker.com/docker-cloud/migration/). 

The PR removes the `docker-cloud` formula from homebrew since the formula can not be used going forward.

**Note** : I've edited the original PR description as well.

**Comment by fxcoudert** [comment]
We still have a significant number of installs per month, though:

```
install_on_request events in the last 30 days
================================================================================
1 | docker-cloud                                                 | 110 | 100.00%
================================================================================
```

**Comment by fxcoudert** [comment]
Given we still have many users for this package (why? I don't know), and given the sources are still available and it builds fine, we are going to keep it for now. Thanks @nandhini915 nonetheless for making us aware of the situation, we'll keep an eye on it.

**Pull request closed without merging**
