### PR TITLE
eksctl: remove aws-iam-authenticator

### PR DESCRIPTION
**Pull request by koooge**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

aws-iam-authenticator should be removed since awscli now provides `aws eks get-token`.  The current behavior is that eksctl uses `aws-iam-authenticator` as a priority instead of `aws eks get-token`.

### CODE REVIEW

**Comment by cPu1** [comment]
Can this be prioritized? I'm from the eksctl team. We cut a release yesterday but this open PR is likely preventing the https://github.com/Homebrew/homebrew-core/actions/workflows/autobump.yml action from opening a PR for eksctl with the latest version.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
I dont see any harm of merging this PR, ✅

**Comment by chenrui333** [comment]
@cPu1 👋 thanks for checking on this.

**Comment by cPu1** [comment]
> @cPu1 👋 thanks for checking on this.

@chenrui333, thanks for the prompt resolution!

**Pull request merged**
