### PR TITLE
mariadb@10.3 10.3.18

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by alebcay** [comment]
```
Undefined symbols for architecture x86_64:
  "_BIO_free", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_BIO_new_mem_buf", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_ERR_clear_error", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_PEM_read_bio_RSA_PUBKEY", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_RSA_free", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_RSA_public_encrypt", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_RSA_size", referenced from:
      _auth_sha256_client in sha256_pw.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libmariadb/sha256_password.so] Error 1
make[1]: *** [libmariadb/CMakeFiles/sha256_password.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Bo98** [comment]
See #44958. We're waiting for a new release which should become available very shortly.

**Comment by Bo98** [comment]
See #46341. Hopefully there aren't further issues.

**Pull request closed without merging**
