### PR TITLE
pdf2djvu 0.9.18.1 (new formula)

### PR DESCRIPTION
**Pull request by fxcoudert**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The audit for new formula fails, the github repo is a bit short in terms of notoriety. But the software has a long history, is actively maintained (latest release last month), is included in many Linux distros (Debian, Ubuntu, Arch Linux, openSUSE), is in MacPorts, and would be useful to Wikisource contributors using macOS.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
I'm fine merging it with the failing notability audit. If it breaks ik just ping FX till they fix it.

**Comment by fxcoudert** [comment]
Linux build fails because `djvulibre` is not bottled. How should this be handled?

**Comment by SMillerDev** [comment]
Dispatched a bottle: https://github.com/Homebrew/homebrew-core/runs/4079389235?check_suite_focus=true

**Comment by SMillerDev** [comment]
That was the wrong button 😞

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/commit/68d3c3d1381159d559ea9b7bc2fd931c7ce70830 has been committed, you might need to rebase it now

**Comment by carlocab** [comment]
Rebased for `djvulibre`.

**Comment by fxcoudert** [comment]
Another linux issue:

```
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libsmime3.so: .dynsym local symbol at index 15 (>= sh_info of 2)
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/poppler/21.11.0/lib/libpoppler.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
collect2: error: ld returned 1 exit status
Makefile:56: recipe for target 'pdf2djvu' failed
```

**Review by carlocab — APPROVED** [review]
Should be fixed now.

**Comment by carlocab** [comment]
All builds successful; only failures are the repo audit. Merging.

**Comment by fxcoudert** [comment]
Thanks @carlocab

**Pull request closed without merging**
