### PR TITLE
OpenH264 1.6.0 retag fix

### PR DESCRIPTION
**Pull request by JCount**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Fix sha256 mismatch likely due to release retagging

### CODE REVIEW

**Comment by JCount** [comment]
Opened https://github.com/cisco/openh264/issues/2528 to make certain this was not the result of some deliberate changes.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
@DomT4 I was busy yesterday, so I missed the progress on this. Thanks for moving forward with it!

It looks like the bottles were all built successfully, so this can probably be merged.

However, the commit that was added causing the retag, https://github.com/cisco/openh264/pull/2522 changes SharedLibVersion, an area I am not really sure how homebrew normally handles. e.g. Should a revision be added to force an update to the new bottles for users with an install of the bottles built before the retag?

CC @ilovezfs (since you were the one that actually took the issue I opened and ran with it. 💯)

**Comment by DomT4** [comment]
We should probably bump the `revision` for the formula, aye. Thanks for reporting this upstream, appreciate you doing that proactively. I'd been keeping a loose eye on the upstream Issue but there wasn't much of a response for a little while.

**Comment by JCount** [comment]
Ok, do you want to bump the revision, or should I add and squash it to the PR?

**Comment by DomT4** [comment]
It'll need to go back through CI to get bottles generated for the appropriate formula revision, so will need to be the latter.

**Comment by JCount** [comment]
Figured as much, doing it now.

**Comment by JCount** [comment]
Ok, I think I did that right. 
(Honestly, it's my first time trying to do this so if I could improve something feel free to tell me, I will not be offended.)

**Comment by DomT4** [comment]
You were mostly on the money. Couple of nits for future reference would be ideally multiple commits for the same formula should be squashed together in _most_ circumstances, and the commit message should adhere to the format we use for non-version changes, in this case:
```
openh264: revision for upstream retag
```
Neither are a massive deal. Everything else was 💯.

Merged in https://github.com/Homebrew/homebrew-core/commit/74e0db0cc41fab14d567ff45a7e32d487a1b4c53. Thank you for another contribution to Homebrew @JCount; we appreciate it! :smiley_cat:

**Comment by JCount** [comment]
Thanks for the constructive feedback for the future!

**Pull request closed without merging**
