### PR TITLE
bash: store the patches in an array, not a hash

### PR DESCRIPTION
**Pull request by ilovezfs**
ruby 1.8.7 doesn't preserve the hash's order but the patches must be
applied in order.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1: but I wonder if it's a better idea to rely on a Array where the ordering is defined.

**Comment by ilovezfs** [comment]
We could but isn't that kind of ugly to do [["a", "314"], ["b", "159"], ...]?

**Comment by mikemcquaid** [comment]
Yeh it is a bit. I dunno, this is probably fine.

**Comment by ilovezfs** [comment]
@mikemcquaid How's this?

**Comment by mikemcquaid** [comment]
@ilovezfs :+1:

**Pull request closed without merging**
