### PR TITLE
QuestDB formula #2nd PR

### PR DESCRIPTION
**Pull request by bluestreak01**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

> ---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Test is failing: https://bot.brew.sh/job/Homebrew%20Core/9353/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_questdb/

When you've got a fix please push it to the same branch.

**Comment by MikeMcQuaid** [comment]
(and don't create a new PR, thanks!)

**Comment by bluestreak01** [comment]
Thank Mike.

This is classic case where test passed on my osx and didn't on yours. Is "curl" available on your build machines? It doesn't look like it ran.

**Comment by MikeMcQuaid** [comment]
Yeh. Just FYI `curl` is always available with macOS.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for new formulae is `questdb 1.0.0 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Comment by bluestreak01** [comment]
Awesome, thanks Mike. I'll try to stick to guidelines next time.

**Pull request merged**
