### PR TITLE
influxdb 1.7.8

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Test failed on Sierra.

**Comment by chenrui333** [comment]
Same test failure as before: https://github.com/Homebrew/homebrew-core/pull/43329#issuecomment-523525710

**Comment by chenrui333** [comment]
@igas  :) we probably can still work on this PR for the upgrade.

**Comment by igas** [comment]
@chenrui333 I close if I don't think I'll be able to come back and fix it to not hold the queue.

**Comment by chenrui333** [comment]
Relates to https://github.com/Homebrew/homebrew-core/pull/45888

**Pull request closed without merging**
