### PR TITLE
vim: uses from macos perl and ruby

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

uses from macos perl and ruby

### CODE REVIEW

**Comment by carlocab** [comment]
Well, it builds. On the other hand, all I've experienced is grief from macOS `perl`...

**Comment by moonfruit** [comment]
Errr, I just don't want to install `vim` with unnecessary `perl`. I think most `vim` users do not use `perl`.

**Comment by moonfruit** [comment]
Or I can make `vim` to load `perl` dynamically when necessary.
And this also suits `lua`, `python` and `ruby`.

**Comment by Bo98** [comment]
If it works I'm fine with this. Looks like there wasn't any particular reason to use brewed Perl.

I suppose the same could be argued with Ruby?

> ```rb
> # Homebrew will use the first suitable Perl & Ruby in your PATH if you
> # build from source. Please don't attempt to hardcode either.
> ```

I don't think this should happen anymore. That's an opportunistic linkage nightmare and goes against what reproducible builds are about.

**Comment by carlocab** [comment]
> > ```ruby
> > # Homebrew will use the first suitable Perl & Ruby in your PATH if you
> > # build from source. Please don't attempt to hardcode either.
> > ```
> 
> I don't think this should happen anymore. That's an opportunistic linkage nightmare and goes against what reproducible builds are about.

It doesn't. The comment is inaccurate.

**Comment by moonfruit** [comment]
I make ruby `uses_from_macos` also.
And I add some tests to verify perl and ruby.

**Pull request closed without merging**
