### PR TITLE
mingw-w64: update binutils resource

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Comment by mrpippy** [comment]
Thanks @Gcenx. Maybe this commit should be reverted? The only point of mingw is to build DLLs/EXEs, and I've seen this bug while building Wine with mingw-w64-9.0.0_3

**Comment by Gcenx** [comment]
@mrpippy that’s not usually how brew handles upstream bugs, if you don’t compile in parallel theses no issue with dlltool but that’s annoying.

I’ve added a versioned keg_only formula to my tap `gcenx/wine/mingw-w64@9`

**Comment by carlocab** [comment]
We'll accept a patch that fixes this if it's been upstreamed. Otherwise, I'll consider a PR that downgrades the `binutils` resource if it includes an update to the `test` block that succeeds without the bug in binutils 2.38 and fails with it.

**Comment by Gcenx** [comment]
> We'll accept a patch that fixes this if it's been upstreamed. Otherwise, I'll consider a PR that downgrades the `binutils` resource if it includes an update to the `test` block that succeeds without the bug in binutils 2.38 and fails with it.

There's still no responses in the mailing list so no patch as of yet unfortunately I'm keeping my eye out since I've had `*-w64-mingw32-binutils` Portfiles updated on macports held back due to this bug.

As the bug is rather sporadic when parallel compiling so it doesn't always happen, so writing a test for this would be complicated _if_ it's even possible (lightly beyond me).

**Pull request closed without merging**
