### PR TITLE
ice: patch for Xcode 10

### PR DESCRIPTION
**Pull request by externl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Upstream (where I work) has released a patch for Xcode 10. It's at a new tag `v3.7.1-xcode10`. A rebuild is necessary for anyone using Xcode 10 as the patch fixes compilation issues as well as code generation issues for users of Ice (their Xcode 10 projects may not compile in some circumstances).

Brew audit complains that the SHA was changed without changing the version, not sure if the way I've structured my PR is the best approach. However, this is the way we've done brew patches in the past.

### CODE REVIEW

**Comment by fxcoudert** [comment]
I see the Xcode 10-specific tag, but it's not actually marked as a release (“latest release” still points to 3.7.1). We'd rather ship only official releases, is it possible that a version 3.7.2 (or 3.7.1.1) could be shipped?

**Comment by externl** [comment]
Hi @fxcoudert. This is the official release for Xcode 10 support. It is intended only for Xcode 10 support for Ice 3.7.1. We do not plan on releasing a new version `v3.7.1` any time soon. In the past this is what we've done for homebrew since it required non-trivial changes.

Can we just call it version `3.7.1.1` here in brew?

**Comment by externl** [comment]
Looking back at el_captian we did a patch form the commit. Would that be better for you?

**Comment by externl** [comment]
Is the testing hung?

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @externl for the pull request!

**Pull request closed without merging**
