### PR TITLE
awscurl 0.29

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Opened an upstream issue: https://github.com/okigan/awscurl/issues/167

**Comment by okigan** [comment]
Retry with v0.29 release. Thanks!

**Comment by p-linnane** [comment]
@okigan Thanks for the response. We build from the PyPI release, which appears to still be v0.28. Can you push v0.29 there and I'll rerun this?

**Comment by okigan** [comment]
Updated on pypi

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @okigan!

**Pull request merged**
