### PR TITLE
geographiclib 2.1.2

### PR DESCRIPTION
**Pull request by cffk**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cffk** [comment]
I've no idea how to fix

  Run Homebrew/actions/label-pull-requests@master
  Error: Not Found

or even what it refers to.  Help!

**Comment by p-linnane** [comment]
It was a transitory GitHub issue that has since been resolved.

**Review by p-linnane — DISMISSED** [review]

**Review by p-linnane — APPROVED** [review]

**Comment by p-linnane** [comment]
I was able to pull a bottle for my system down. Can you try again?
```
brew fetch geographiclib
==> Downloading https://ghcr.io/v2/homebrew/core/geographiclib/manifests/2.1.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/geographiclib/blobs/sha256:10cf6efab39f38c196766b1834ae4f38fa0e5a95cebe8d55c8948619e39635cb
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:10cf6efab39f38c196766b1834ae4f38fa0e5a95cebe8d55c8948619e39635cb?se=2022-12-14T02%3A25%3A00Z&sig=oBTLoTE7yFDv%2BiBMpyTTJCG1qJSJHM
######################################################################## 100.0%
Downloaded to: /Users/patrick/Library/Caches/Homebrew/downloads/f93186c3b12fc563eb8d4d8995d920960553ef723d5059c86a221cc678356ace--geographiclib--2.1.2.arm64_ventura.bottle.tar.gz
SHA256: 10cf6efab39f38c196766b1834ae4f38fa0e5a95cebe8d55c8948619e39635cb
```

**Comment by cffk** [comment]
`brew fetch geographiclib` is OK:
```
$ brew fetch geographiclib
==> Downloading https://ghcr.io/v2/homebrew/core/geographiclib/manifests/2.1.2
Already downloaded: /Users/ckarney/Library/Caches/Homebrew/downloads/cd41bd98c2acd4b447f01dfffebd55adaac9f97ee51795815384671f8b9f2d34--geographiclib-2.1.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/geographiclib/manifests/2.1.2
######################################################################## 100.0%
Error: Couldn't find manifest matching bottle checksum.
Warning: Bottle fetch failed, fetching the source instead.
==> Downloading https://downloads.sourceforge.net/project/geographiclib/distrib-
==> Downloading from https://netactuate.dl.sourceforge.net/project/geographiclib
######################################################################## 100.0%
Downloaded to: /Users/ckarney/Library/Caches/Homebrew/downloads/3a0aed5860df34153f37b52f0b80b17b615325c096c61b9f43a17fa92885938c--GeographicLib-2.1.2.tar.gz
SHA256: b062b472dae3d371b3005f4ea2fc59af687b8ea76eb23df732ec11c500fba959
```
But a subsequent `git install geographiclib` fails:
```
$ brew install geographiclib
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).

==> Fetching geographiclib
==> Downloading https://ghcr.io/v2/homebrew/core/geographiclib/manifests/2.1.2
Already downloaded: /Users/ckarney/Library/Caches/Homebrew/downloads/cd41bd98c2acd4b447f01dfffebd55adaac9f97ee51795815384671f8b9f2d34--geographiclib-2.1.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/geographiclib/manifests/2.1.2
######################################################################## 100.0%
Error: Couldn't find manifest matching bottle checksum.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:447:in `github_packages_manifest_resource_tab'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:400:in `fetch_tab'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2605:in `fetch_bottle_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1182:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:313:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:284:in `map'
/usr/local/Homebrew/Library/Homebrew/install.rb:284:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in `<main>'
$ type GeodSolve
-bash: type: GeodSolve: not found 
```

BTW, I'm running MacOS Monterey.

**Pull request closed without merging**
