### PR TITLE
sbcl 1.3.9

### PR DESCRIPTION
**Pull request by rprimus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
I believe the resource blocks should all be updated as well, no?

**Comment by rprimus** [comment]
Wed Aug 31 09:42:58 BST 2016

1.  No errors when compiled without changing resource blocks (see [logfile](https://gist.github.com/58216731ad6781cd6db8d00f64f25326))
2.  Used [pull request](https://github.com/Homebrew/homebrew-core/pull/2530) as example.

Can you recommend how/when resources should be checked?

**Comment by ilovezfs** [comment]
It looks fine. There are no newer versions of the binaries in the table mentioned in the comment in the formula.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
