### PR TITLE
opus 1.3

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
For some reason, the `ffmpeg@2.8` bottles were unpublished, this is now fixed.
Other test failures are preexisting.

**Comment by commitay** [comment]
The `ffmpeg@2.8` bottle block needs to be updated with the correct checksums.
```
$ brew fetch ffmpeg@2.8
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg@2.8-2.8.15_1.high_si
######################################################################## 100.0%
Downloaded to: /Users/commitay/Library/Caches/Homebrew/downloads/78ddeb260e5cad6c50064ad10525dcb5bf1f96d6a4e301674617fed16171ad5e--ffmpeg@2.8-2.8.15_1.high_sierra.bottle.tar.gz
SHA256: 18a2e5804df50bb5a359be87a6e9144b1e449de9a95e580a7d4ac1a654ae8f30
Warning: Formula reports different SHA256: 77714c2ed74758ffca2e0852c7784022a06903be46a4094b5813cdcd3a3f7caf
```

**Comment by fxcoudert** [comment]
@commitay on it :) https://github.com/Homebrew/homebrew-core/commit/6f4c785a0e4dd34333390e19971e7561e89cb6aa

**Comment by commitay** [comment]
Thanks!

**Pull request closed without merging**
