### PR TITLE
akamai: add bash and zsh completion.

### PR DESCRIPTION
**Pull request by rajiv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

cc @dshafik

### CODE REVIEW

**Review by dshafik — COMMENTED** [review]
Would it be better to pipe the output of `akamai --bash` and `akamai --zsh` to these files instead, in case it is updated in future…

**Comment by commitay** [comment]
> Would it be better to pipe the output of `akamai --bash` and `akamai --zsh` to these files instead

Yes.

**Comment by rajiv** [comment]
in order to do so, the `akamai` binary needs to be updated to support a mode where `akamai --bash` can work on the first run, from inside the homebrew formula. at least as of version 1.0.1, if you try and call `akamai --bash` inside the formula, it hangs waiting for input to the "anonymous analytics" question.

**Comment by commitay** [comment]
> the `akamai` binary needs to be updated to support a mode where `akamai --bash` can work on the first run

If this isn't possible, adding the completion scripts to the upstream repo so we can install them would be preferred rather than including the full scripts in the formula.

**Pull request closed without merging**
