### PR TITLE
Fix sha256 for ballerina-1.2.2

### PR DESCRIPTION
**Pull request by nicolaevladescu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Have upstream stated why it has changed? This isn't first time this has happened.

**Comment by nicolaevladescu** [comment]
Upstream provides only sha1 and md5

**Comment by Bo98** [comment]
It's impossible (excluding the security weaknesses of SHA-1 and MD5) for the SHA-256 to change and the SHA-1 and MD5 to not.

**Comment by nicolaevladescu** [comment]
What i am trying to say is that this page https://ballerina.io/downloads/ only provides sha1 and md5 from the authors of the software. I have no clue where the current sha256 came from, could be as arbitrary as mine, mine comes from my computer after downloading the 1.2.2 zip from the above page.

**Comment by Bo98** [comment]
Sure, but the sha256 was correct before otherwise the CI would have failed. The archive has been modified.

**Comment by nicolaevladescu** [comment]
That is my guess also, and it’s a very bad practice on their part, but we can’t bump the version so i am out of ideas.

**Comment by SMillerDev** [comment]
Did you try contacting them and asking?

**Comment by Bo98** [comment]
We will eventually merge this, but we need to try and get upstream to stop modifying the archives - or provide an alternative more stable URL - or we can't really ship this in Homebrew in the future.

**Comment by nicolaevladescu** [comment]
No, i will do it tomorrow and come back. We can close this PR meanwhile if you would like. What are the options if this is in fact the correct and final hash for 1.2.2 and maybe they forgot something in the earlier archive?

**Comment by Bo98** [comment]
> What are the options if this is in fact the correct and final hash for 1.2.2 and maybe they forgot to add something in the earlier archive?

We'll merge this, it's fine.

I'm concerned if it's going to become a regular occurrence though.

**Comment by Bo98** [comment]
I have found and traced old and new source archives.

I compared the original released 1.2.2 archive from 2020-04-16 and the modified archive uploaded two days after release on 2020-04-18. There are no new files (a couple renames however), but there were modifications to 280 files, including changes to 218 library files (JARs etc.). This isn't insignificant - it's effectively a new version so we may have to revision bump here if we want to issue this new release. Can you add a `revision 1` line to this pull request?

I also checked back for previous incidents. For 1.2.0, there were modifications to 275 files, including 218 library files. In this case, there was also the addition of docs which was missing from the originally released archive.

For 1.1.0 (which didn't affect Homebrew since we only updated 2 weeks later), there was again modifications to 243 files, including 218 library files. There was also the addition of one example and some copyright & readme .txt files.

It seems upstream regularly issue new versions without bumping the version number. We will need to consider what to do in the future for this formula - perhaps blocking future updates from being included in Homebrew until a week has passed since the release.

**Comment by nicolaevladescu** [comment]
I have emailed them, i have also sent them the link to this PR, let's see what they have to say, if they will respond to my email only i'll come back with the findings.

**Comment by rasika** [comment]
Hi Folks, I am from the Ballerina team. Apology for the mistake and this hash diff in my [PR[1]](https://github.com/Homebrew/homebrew-core/pull/53249/files) has occurred due to a miscommunication occurred regarding the RC pack. Until last release, we were updating the Homebrew Formula manually. Moving forward, we have introduced a workflow for the automation of updating the Homebrew Formula in [git-workflows[2]](https://github.com/ballerina-platform/ballerina-dev-website/blob/master/.github/workflows/homebrew_publish.yml), to avoid these type of issues.

We'll make sure that these type of incident will never happen again. And kindly request to merge this PR to correct the hash. Thanks for the your continued support of making our package available through the Homebrew !

[1] https://github.com/Homebrew/homebrew-core/pull/53249/files
[2] https://github.com/ballerina-platform/ballerina-dev-website/blob/master/.github/workflows/homebrew_publish.yml

**Comment by Bo98** [comment]
Thanks for letting us know!

**Pull request merged**
