### PR TITLE
Secure URLs (2 of 3)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Known issues:
```
llvm@3.9:
  * Dependency graphviz should not use option dot
raine:
  * Stable resource "libpng": The URL https://downloads.sourceforge.net/project/libpng/libpng16/1.6.28/libpng-1.6.28.tar.xz is not
  * HEAD resource "libpng": The URL https://downloads.sourceforge.net/project/libpng/libpng16/1.6.28/libpng-1.6.28.tar.xz is not re
```

Corrected the `raine` `libpng` URL, still fails in audit, even though the URL is fine.

### CODE REVIEW

**Comment by vszakats** [comment]
Not sure what the canonical is, but HTTPS can also be enabled in `llvm.rb`, by moving back from `http://releases.llvm.org/` to `https://llvm.org/releases/`.

**Comment by ilovezfs** [comment]
All were detected by audit.

**Comment by ilovezfs** [comment]
>Not sure what the canonical is, but HTTPS can also be enabled in llvm.rb, by moving back from http://releases.llvm.org/ to https://llvm.org/releases/

yes, let's move back if they have https now

**Comment by vszakats** [comment]
`llvm.rb` committed.

**Comment by ilovezfs** [comment]
:key:

**Pull request merged**
