### PR TITLE
sing-box 1.1.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  ## :memo: Release Notes

* Improve the stability of the VMESS server
* Fix `auto_detect_interface` incorrectly identifying the default interface on Windows
* Fix bugs and update dependencies

</details>

### CODE REVIEW

**Comment by nekohasekai** [comment]
Hi there, as the author of this project, I kindly request that you use the commands provided by the Makefile to compile rather than adding deprecated parameters. Thank you for your understanding.

Here is an example: https://github.com/SagerNet/homebrew-sing-box/blob/main/Formula/sing-box.rb

**Comment by carlocab** [comment]
Hi @nekohasekai, thanks for dropping by. Could you tell me which parameters are deprecated? From my understanding of your [`Makefile`](https://github.com/SagerNet/sing-box/blob/b6dbb69fc4de3af787eb558715f033f7791d51e8/Makefile), the formula runs the same command that `make install` does.

**Review by carlocab — DISMISSED** [review]

**Comment by nekohasekai** [comment]
> Hi @nekohasekai, thanks for dropping by. Could you tell me which parameters are deprecated? From my understanding of your [`Makefile`](https://github.com/SagerNet/sing-box/blob/b6dbb69fc4de3af787eb558715f033f7791d51e8/Makefile), the formula runs the same command that `make install` does.

I guess it's a misunderstanding, but I don't think build parameters should be defined by the package manager, which might cause some confusion.

**Comment by SMillerDev** [comment]
Generally I agree with that, but in my experience most makefiles for Go don't work so well in a package manager context. We can give it another try here though.

**Comment by carlocab** [comment]
I disagree. I think we should set these parameters here. Setting these in the formula makes the build process more transparent to readers of the formula. It also helps us make sure that we are building this formula in line with our package management policies.

**Comment by nekohasekai** [comment]
I can understand that some package managers prohibit downloading files during build, but not executing arbitrary code. Would you do this with a more free-form build tool like gradle?

**Comment by carlocab** [comment]
> Would you do this with a more free-form build tool like gradle?

If I could still write the formula `install` method in less than 10 lines, yes.

**Comment by nekohasekai** [comment]
You basically can't compile an android project using gradle with commands other than gradle. Is there any reason to prohibit the golang program from compiling according to its own configuration?

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
