### PR TITLE
gitg 3.24.0 plus dependencies

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Any thoughts on how to fix this:

````
gitg:
  * Dependency pygobject3 should not use option  if build.with?("python3
````

**Comment by ilovezfs** [comment]
It should say
```
* Dependency pygobject3 should not use option with-python3
```

The solution is a separate pygobject3-python3 formula or vendoring pygobject3 with python3 in a resource block in gitg itself.

**Comment by tschoonj** [comment]
Hmmm... how about making `python3` `:recommended` in `python3`?

**Comment by ilovezfs** [comment]
@tschoonj That should work though it may involve some blow back from unhappy users.

**Comment by tschoonj** [comment]
What is brew actually complaining about? The `python3` and `pygobject3` dependencies are optional anyway, and do not stop a bottle from being generated.

Anyway, I am not a fan of vendoring in as it is essentially an assault on my disk space.

So if there's no objection and this audit warning really needs to go, I would prefer to make `python3` recommended in `pygobject3`

**Comment by ilovezfs** [comment]
>What is brew actually complaining about?

`depends_on "foo" => "with-bar"` is now deprecated.

>So if there's no objection and this audit warning really needs to go, I would prefer to make python3 recommended in pygobject3

The objection will not come from me.

**Comment by tschoonj** [comment]
> depends_on "foo" => "with-bar" is now deprecated.

Even when "foo" itself depends on another `:optional` dependency explicitly being used? Seems a bit harsh to me...

**Comment by ilovezfs** [comment]
>Even when "foo" itself depends on another :optional dependency explicitly being used? Seems a bit harsh to me...

Yes, even then.

**Comment by DomT4** [comment]
`python2` has a death date set anyway, so it's not like expecting people to increasingly need/want `python3` is unreasonable, IMO. More Homebrew formulae are going to start moving in that direction sooner or later.

**Comment by MikeMcQuaid** [comment]
I'd like to see `python` become `python@2` and `python3` become `python`, eventually.

**Comment by ilovezfs** [comment]
To be clear, the point is not about people wanting or not wanting python3, but about forcing a Homebrew python3 installation on people who are installing a formula that may not even depend on python3 optionally but does depend on pygobject3. E.g. `brew install mat`

**Comment by DomT4** [comment]
It's hardly ideal but unless you want to add a whitelist of things that are reasonable to the new audit I think your best bet here is to make it `:recommended` and see how many people shout at you for it 😕

**Comment by ilovezfs** [comment]
No whitelist.

I'm still not sure why a separate formula or a resource block is objectionable but :man_shrugging:

**Comment by DomT4** [comment]
> No whitelist.

I am in no way looking to get into this debate.

> I'm still not sure why a separate formula

I don't hate this idea FWIW, but I do think it'll be confusing, not least because `pygobject3` is hard to manipulate as a name without it getting clunky. `pygobject3-python3`, etc ❓

**Comment by ilovezfs** [comment]
>I don't hate this idea FWIW, but I do think it'll be confusing, not least because pygobject3 is hard to manipulate as a name without it getting clunky. pygobject3-python3, etc :question:

Yes we need a naming convention for this.

**Comment by ilovezfs** [comment]
Maybe `pygobject3^python3` or `pygobject3%python3`? Any takers?

**Review by fooosmar — APPROVED** [review]

**Comment by tschoonj** [comment]
So, has the jury reached a verdict?

**Comment by DomT4** [comment]
Maybe @tdsmith has ideas/thoughts here given the Python subject 🙈

**Comment by tschoonj** [comment]
@tdsmith Would you mind having a look at the discussion here? Thanks!

**Comment by tdsmith** [comment]
Sorry; looked at this and couldn't figure out what the question was. I don't care about naming. Why does gitg have an optional python3 dependency, though? Can we just drop the option?

**Comment by tschoonj** [comment]
From `gitg`'s [PACKAGING](https://github.com/GNOME/gitg/blob/master/PACKAGING) file:

````
gitg has a soft dependency on python due to its plugin system. Building gitg
without python is perfectly possible, and since there are currently no plugins
implemented in python, it will not affect core functionality. However, we would
like to be able to have third party developers write plugins in python and it
is therefore recommended to have python as a dependency for gitg.
````

Maybe not the worst thing in the world to drop it now then I guess... we can think about bringing it back if there's ever a request.

**Pull request closed without merging**
