### PR TITLE
azure-cli: migrate to python@3.10

### PR DESCRIPTION
**Pull request by branchv**
azure-cli: migrate to python@3.10

### CODE REVIEW

**Comment by branchvincent** [comment]
see https://github.com/Azure/azure-cli/issues/19857

**Comment by branchvincent** [comment]
superseded #88586

**Comment by jiasli** [comment]
We have finished the work for Python 3.10: https://github.com/Azure/azure-cli/pull/20195. Please feel free to change the formula.

**Comment by tuzi3040** [comment]
Seems we can reopen this PR now. @branchvincent 

Also, azure-cli cannot function properly on python 3.9.8 Azure/azure-cli#20269, which is cause by a [bugfix](https://bugs.python.org/issue45235) (python/cpython#28420) introduced in 3.9.8. This bugfix is now reverted (python/cpython#29525) in both 3.9 and 3.10 branch, but hadn't been released into official 3.10 release, so 3.10 is not affected by it.

**Comment by jiasli** [comment]
This PR looks good to me. Please merge it as as soon as possible as users are affected by the Python 3.8.9 regression (https://github.com/Azure/azure-cli/issues/20269).

**Comment by cclauss** [comment]
Was this closed in #88586

**Comment by tuzi3040** [comment]
> This has all tests passing. Was it closed in #88586 ?

No, it's not.

**Review by SMillerDev — APPROVED** [review]

**Comment by branchvincent** [comment]
thanks @jiasli and @tuzi3040 for the ping and letting us know about the issue!

**Pull request closed without merging**
