### PR TITLE
ldns 1.7.0

### PR DESCRIPTION
**Pull request by aabdnn**
This commit updates ldns to 1.7.0

### CODE REVIEW

**Comment by woodruffw** [comment]
```
Error: freeswitch contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree freeswitch`.
```

**Comment by woodruffw** [comment]
Does this actually fail without `openssl@1.1`? We might want to hold off on that dependency bump in order to get this through.

**Comment by ilovezfs** [comment]
There's a moratorium on new openssl@1.1 dependencies: https://github.com/Homebrew/homebrew-core/issues/4543#issuecomment-260371674

**Comment by aabdnn** [comment]
@woodruffw ldns 1.7.0 can build against openssl 1.0.x, but then we have to pass some options to "configure" to turn off some functions of ldns that require openssl 1.1. Upstream recommends building against openssl 1.1.

**Comment by MikeMcQuaid** [comment]
If this moves to OpenSSL 1.1 then Freeswitch and everything it depends on must be too.

**Comment by ilovezfs** [comment]
which means

curl, xml-security-c, xml-tooling-c, opensaml, apr-util, and once you hit apr-utils, you can just keep going

**Comment by MikeMcQuaid** [comment]
@ilovezfs Yeh so in this case: almost certainly not worth it.

**Comment by aabdnn** [comment]
Guys, I don't understand. How is freeswitch depending on openssl 1.1 when I've only added it as a dependency for ldns?

**Comment by ilovezfs** [comment]
Due to https://github.com/Homebrew/homebrew-core/blob/master/Formula/freeswitch.rb#L32

**Comment by aabdnn** [comment]
Okay, perhaps I am too thick or missing something obvious. ldns doesn't need freeswitch. Why is the ldns build being held up by a different package?

**Comment by ilovezfs** [comment]
It's the reverse. `freeswitch` currently depends on ldns: https://github.com/Homebrew/homebrew-core/blob/master/Formula/freeswitch.rb#L31

**Comment by MikeMcQuaid** [comment]
> Why is the ldns build being held up by a different package?

Because we need to make sure we don't break our other packages through upgrading. This is standard practise for package managers.

**Comment by aabdnn** [comment]
Aaaaah, now the penny has dropped. Thank you for patiently explaining it to me @ilovezfs.
I see two options. One is personal, where I build ldns 1.7.0 on a personal branch and use it privately without updating Homebrew. The other is to create an ldns@1.7 formula.
What do you guys think?

**Comment by ilovezfs** [comment]
```
checking for libldns >= 1.6.6... checking for ldns_str2rdf_a in -lldns... no
configure: error: You need to either install libldns-dev or disable mod_enum in modules.conf
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./configure --disable-dependency-tracking --enable-shared --enable-static --prefix=/usr/local/Cellar/freeswitch/1.6.13_1 --exec_prefix=/usr/local/Cellar/freeswitch/1.6.13_1
```
so it may be possible to drop the ldns dependency from freeswitch.

The other one that's in the same boat is dnscrypt-proxy, which would need to be switched over to openssl@1.1.

**Comment by MikeMcQuaid** [comment]
@aabdnn I'd consider just using OpenSSL 1.0 for now.

**Comment by aabdnn** [comment]
@MikeMcQuaid I can't use openssl 1.0, because then some functions have to be disabled in ldns 1.7, and I want to use those specific functions (relating to DANE verification).

**Comment by ilovezfs** [comment]
Actually dnscrypt-proxy only uses openssl via ldns, but isn't itself linked to it.

With mod-enum disabled, freeswitch does build successfully without needing ldns (diff below).

Here's a description of what the mod-enum feature is that would get sacrificed:

>ENUM (Electronic Number Mapping System) is a system that uses standard phone numbers as a key to lookup addressing and identification information that can potentially let Freeswitch servers communicate directly, thus bypassing the PSTN, reducing cost, and improving audio quality. It is based on the E.164 standard and uses standard DNS systems to translate telephone numbers into a special DNS record type called a NAPTR record (NamingAuthority PoinTer Resource Record) that might contain information for 1-(800)-555-1234 such as:

```
$ORIGIN 4.3.2.1.5.5.5.0.0.8.1.e164.arpa.
IN NAPTR 100 10 "U" "E2U+sip" "!^.*$!sip:customer-service@example.com!" .
IN NAPTR 102 10 "U" "E2U+email" "!^.*$!mailto:information@example.com!" .

```

(https://freeswitch.org/confluence/display/FREESWITCH/mod_enum)

```
diff --git a/Formula/freeswitch.rb b/Formula/freeswitch.rb
index dc7a5e6..b4ca3a7 100644
--- a/Formula/freeswitch.rb
+++ b/Formula/freeswitch.rb
@@ -28,7 +28,6 @@ class Freeswitch < Formula
 
   depends_on "curl"
   depends_on "jpeg"
-  depends_on "ldns"
   depends_on "openssl"
   depends_on "pcre"
   depends_on "sqlite"
@@ -147,6 +146,9 @@ class Freeswitch < Formula
   #------------------------ End sound file resources --------------------------
 
   def install
+    inreplace "build/modules.conf.in", "applications/mod_enum",
+                                       "#applications/mod_enum"
+
     system "./bootstrap.sh", "-j"
 
     # tiff will fail to find OpenGL unless told not to use X
bash-3.2$ 
```

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/9189 should allow you to use openssl@1.1 here.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Think we just need a `revision 1` added to `dnscrypt-proxy` and we're good to go.

**Comment by ilovezfs** [comment]
I rebased on master, and pushed a revision for dnscrypt-proxy

**Comment by ilovezfs** [comment]
@aabdnn shipped with the openssl@1.1 dependency! Thanks for your contribution to Homebrew.

**Pull request closed without merging**
