### PR TITLE
tarantool 2.7.0.0

### PR DESCRIPTION
**Pull request by mprince**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Was this version officially released?
On the website, I see that they refer to 2.6 as the latest version.

**Comment by mprince** [comment]
This is weird. When you got [building_from_source](https://www.tarantool.io/en/doc/latest/dev_guide/building_from_source/)link on the homepage you see the doc shows the latest version as 2.6. The reason why i upgraded is because the checking command shows the 2.7.0 version
```sh
$ brew livecheck tarantool
tarantool : 2.5.2.0 ==> 2.7.0
```

**Comment by Totktonada** [comment]
The latest released version is 2.6.1 (beta). The latest stable version is 2.5.2. Let's consider the [releases](https://github.com/tarantool/tarantool/releases) and [release policy](https://www.tarantool.io/en/doc/latest/dev_guide/release_management/) pages.

As one of tarantool developers, I kindly ask to don't push any transient versions to brew formulae. Creating of a PR to homebrew-core is part of our release processes.

**Comment by bayandin** [comment]
Thanks for the clarification @Totktonada

**Comment by Totktonada** [comment]
Filed https://github.com/tarantool/tarantool/issues/5542 to verify the build failure.

How `brew livecheck` works? Maybe we should make it point to the latest stable release somehow?

**Comment by bayandin** [comment]
> How `brew livecheck` works? Maybe we should make it point to the latest stable release somehow?

Documentation still in progress, you can find a draft in https://github.com/Homebrew/brew/pull/7937.

I guess we need to add a `livecheck` block something like this: 
```ruby
  livecheck do
    url :head
    regex(/^(\d+\.\d+\.[2-9]\d*)$/i)
  end
```

**Comment by Totktonada** [comment]
Thanks for the pointing it out. Would it better to handle it with a `stable` block somehow? AFAIU, `livecheck` take it into account by default.

**Comment by bayandin** [comment]
> Would it better to handle it with a `stable` block somehow?

What do you mean by this? 

`stable` block is used for separating behaviour for default `brew install` and `brew install --HEAD`.

If you meant using `url :stable` instead of `url :head` in `livecheck` block then it won't work since `url` in `livecheck` block is used for specifying URL which we want to check for a new version; and `:stable` for `tarantool` is a link to an archive, so we want to use "https://github.com/tarantool/tarantool.git" for getting git tags and finding an appropriate one

**Pull request closed without merging**
