### PR TITLE
pypy3 7.1.0

### PR DESCRIPTION
**Pull request by hyuraku**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@hyuraku please update resources to the latest compatible version

**Comment by hyuraku** [comment]
@fxcoudert 
Sure, I will update them.

**Comment by Moisan** [comment]
Multiple resources return 404. You need to update to the complete url of the resource, the hash in the pythonhosted url changes from file to file.

**Comment by Moisan** [comment]
Latest `setuptools` is `40.8.0`. `packaging` and `pip` also needs to be updated.

**Pull request closed without merging**
