### PR TITLE
rustup-init: install proxy binaries

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

Currently, this formula only contains a `rustup-init` binary (an installer) which a user must call once (and then will never need it again). It's not really useful in its current form because users can just do `curl https://sh.rustup.rs | sh` to achieve the same.

Instead, this actually installs all rustup-managed [proxies](https://rust-lang.github.io/rustup/concepts/proxies.html) (which are all just `rustup` symlinked under a different name). All users need to do is configure a default toolchain on the first run.

The only downside is conflicting with `rust`, which was noted in the original PR #9617 but I think we should reconsider since it gives users the choice (and most users won't notice now that we have bottles and rust is only a build dep). It is also the same approach other packagers seem to have taken: [arch](https://gitlab.archlinux.org/archlinux/packaging/packages/rustup/-/blob/main/PKGBUILD), [debian](https://packages.debian.org/trixie/rustup), [nix](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/rust/rustup/default.nix)

### CODE REVIEW

**Comment by branchvincent** [comment]
Ah but we need `rust` to build `rustup`. Let me rethink this

**Comment by branchvincent** [comment]
Ok moved proxy binaries to `libexec` to avoid conflicts

**Review by SMillerDev — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
> The only downside is conflicting with `rust`, which was noted in the original PR #9617 but I think we should reconsider since it gives users the choice (and most users won't notice now that we have bottles and rust is only a build dep). It is also the same approach other packagers seem to have taken: [arch](https://gitlab.archlinux.org/archlinux/packaging/packages/rustup/-/blob/main/PKGBUILD), [debian](https://packages.debian.org/trixie/rustup), [nix](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/rust/rustup/default.nix?rgh-link-date=2024-07-17T04%3A18%3A28Z)

We could probably make one of them keg-only to fix the conflict.

**Comment by branchvincent** [comment]
I do like that approach more since users could also `brew link --force`. Looking at analytics:

rust:
```
install: 38,827 (30 days), 113,069 (90 days), 440,514 (365 days)
install-on-request: 28,106 (30 days), 81,005 (90 days), 333,059 (365 days)
```

rustup-init:
```
install: 3,643 (30 days), 16,870 (90 days), 51,411 (365 days)
install-on-request: 3,393 (30 days), 15,613 (90 days), 47,587 (365 days)
```

So I say we make `rustup-init` keg-only, rename it to `rustup` (note we do have an existing alias) and stop installing the `rustup-init` binary (since it no longer serves a purpose). Only issue is breaking current installs, do we care? We could of course just note it in the caveats or instead deprecate `rustup-init` and make `rustup` a new formulae

**Comment by branchvincent** [comment]
great idea, done! This looks pretty good to me now, my only other nit is I want to rename this to `rustup` and have `rustup-init` be the alias instead, but I can save that for another PR

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
