### PR TITLE
sourcekitten: remove :build tag from Xcode dep

### PR DESCRIPTION
**Pull request by jpsim**
as recommended in https://github.com/Homebrew/legacy-homebrew/pull/50211#issuecomment-217037901 /cc @apjanke

### CODE REVIEW

**Comment by DomT4** [comment]
It looks potentially like something about the new Xcode release has broken the build here. I checked locally and reproduced the failure as well.

**Comment by jpsim** [comment]
Seems to build & test fine on 7.3.1 here: https://github.com/jpsim/SourceKitten/pull/205

**Comment by apjanke** [comment]
I can also reproduce an error, but with my `xcode_select` pointing at 7.3, not 7.3.1.

https://gist.github.com/ad3ccbbbb2ae7a90e5de74d900f117f9

Here's a version done with `--debug` enabled and single-threaded, so it's easier to read. https://gist.github.com/8751ba6d7f2066cd78b60aaae788150a

Last few lines, with the error message:

```
Clean.Remove clean /Users/janke/Library/Developer/Xcode/DerivedData/SourceKitten-eyryesqsuekpsqcgzimizgjqiwze/Build/Intermediates/SourceKitten.build/Test/sourcekitten.build
    builtin-rm -rf /Users/janke/Library/Developer/Xcode/DerivedData/SourceKitten-eyryesqsuekpsqcgzimizgjqiwze/Build/Intermediates/SourceKitten.build/Test/sourcekitten.build

** CLEAN SUCCEEDED **

script/bootstrap
*** Updating submodules...
*** Bootstrapping Carthage/Checkouts/Commandant...
fatal: /usr/local/Cellar/git/2.8.2/libexec/git-core/git-submodule cannot be used without a working tree.
Stopping at 'Carthage/Checkouts/Nimble'; script returned non-zero status.
Stopping at 'Carthage/Checkouts/Commandant'; script returned non-zero status.
make: *** [bootstrap] Error 1
```

This looks like it's assuming that it's running from a `git` clone somewhere, and is trying to download some additional files via `git`? That could explain why it's failing from `brew`, which I believe copies the files from the git repo out to a clean build directory.

**Comment by DomT4** [comment]
Yeah. It doesn't seem tied specifically to Homebrew's `git` being installed either:

```
Build settings from command line:
    DSTROOT = /private/tmp/sourcekitten-20160506-7790-1xupngh/SourceKitten.dst

fatal: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-submodule cannot be used without a working tree.
Stopping at 'Carthage/Checkouts/Nimble'; script returned non-zero status.
Stopping at 'Carthage/Checkouts/Commandant'; script returned non-zero status.
make: *** [bootstrap] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
I've merged this despite the failure as it isn't related to the change, but it would be nice to spend some time triaging that failure & trying to work out why it happens.

Merged in https://github.com/Homebrew/homebrew-core/commit/3f14b191ea2ade51e81d5eed33563b7d3571885d. Thanks again @jpsim!

**Pull request merged**
