### PR TITLE
php@7.1: 7.1.12 New Formula

### PR DESCRIPTION
**Pull request by kabel**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

PHP 7.1 versioned formula based on the work from #16067 which is now tracking the 7.2 upstream.

### CODE REVIEW

**Comment by ilovezfs** [comment]
At this point I'm :-1: on having any versioned php formulae for the time being so I'm going to close this. But thanks @kabel!

**Comment by kabel** [comment]
Not even a full run at the test bot. 😢

**Comment by ilovezfs** [comment]
Don't cry.

**Comment by kabel** [comment]
Thanks for satisfying my test curiosity. I now have better confirmation that my approaches build and install without issue. 🎉

**Comment by ilovezfs** [comment]
@kabel you're welcome :)

**Pull request closed without merging**
