### PR TITLE
xdk 0.4.2 (new formula)

### PR DESCRIPTION
**Pull request by cpurdy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Notes:
There was one error reported by audit: "* 21: col 12: Use `assert_match` instead of `assert ...include?`"
Unfortunately, on my environment, assert_match would not work; it always failed. (It may have been because additional text was present due to the way that the test changes the environment temporarily when auditing, but I am not a Ruby or Homebrew expert, so I am only hypothesizing.) Regardless, I modified the assertion so that it would work, even when running the brew test, but unfortunately the audit now flags it.

### CODE REVIEW

**Comment by cpurdy** [comment]
Please see notes in original pull request.

**Review by carlocab — COMMENTED** [review]
Please don't mark items in the PR template as completed when you know they're not. In particular, your notes indicate that `brew audit` fails, despite the matching template item being marked as completed.

Please use the preferred commit-message style for homebrew/core as explained in the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit) linked in the PR template. We put the name of the formula first in commit-message headings.

For new formulae:

> At Homebrew, we like to put the name of the formula up front like so: `foobar 7.3 (new formula)`.

For existing formulae:

> The preferred commit message format for simple version updates is `foobar 7.3` and for fixes is `foobar: fix flibble matrix.`.

Also, when making further changes to your pull request, use the following guidelines to make sure that @BrewTestBot can merge your commits:

> - One formula per commit; one commit per formula.
> - Keep merge commits out of the pull request.

**Comment by cpurdy** [comment]
This seems like a stupid question, but how were you able to edit the commit message? I was able to edit it in my local repository (via "git rebase -i HEAD~1") but those changes were lost when I pushed to my Homebrew fork on Github.

I'm also still a little worried about the assert_match, because it didn't match for me, but I appreciate that your experience with this topic is infinitely greater than mine.

Lastly, thank you for the pointers and the assistance. Are there steps that I need to take to complete this? Again, it's probably a stupid question, but this is actually the first time I've ever done a pull request, so this process is very new to me.

**Review by cpurdy — COMMENTED** [review]
These changes seem reasonable. The inclusion of "version" is necessary with our CI builds [in our Tap](https://github.com/xtclang/homebrew-xvm/blob/main/xdk-latest.rb), because we include the Github hash as version metadata. Our release versions (i.e. this Formula) use the standard 3 part version and don't include metadata, (so your change seems to indicate that the "version" in this Formula is redundant).

**Comment by SMillerDev** [comment]
The version is parsed from the URL so no need to add it.

**Comment by cpurdy** [comment]
I'm not sure what the next step is. Do I need to close this pull request and create a new one with the changes? Or is there a step that I need to take on this pull request?

**Comment by carlocab** [comment]
You can just amend your existing pull request. See https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#following-up.

**Pull request closed without merging**
