### PR TITLE
v8 8.8.278.14

### PR DESCRIPTION
**Pull request by jeroen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
You need to `mv Aliases/v8@8.7 Aliases/v8@8.8`.

**Comment by fxcoudert** [comment]
any chance the build-dependency on llvm for ARM can be dropped in this new version?

**Comment by jeroen** [comment]
Only one way to find out...

**Comment by jeroen** [comment]
Nope it looks this [that broke the build](https://github.com/Homebrew/homebrew-core/pull/69334/checks?check_run_id=1731592093):

```
warning: unknown warning option '-Wno-psabi' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-non-c-typedef-for-linkage'; did you mean '-Wno-return-type-c-linkage'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-max-tokens'; did you mean '-Wno-extra-tokens'? [-Wunknown-warning-option]
4 warnings generated.
ninja: build stopped: subcommand failed.
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
```

Reverting...

**Review by carlocab — APPROVED** [review]
Needing LLVM Clang on ARM probably deserves a proper bug report, actually. But that shouldn't block this PR. Thanks, @jeroen!

**Pull request closed without merging**
