### PR TITLE
libgit2 0.25.0

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
**libgit 0.25.0**

-----

- **gitless 0.8.5** is a new version and should probably be put in a separate PR before this is merged

- **libgit2-glib** currently only has support through the libgit2-0.24.x version series

- **gnome-builder** and **gitg** depend on **libgit2-glib** so they are held up at least until libgit2-glib gets support for libgit2 0.25.0

-----
cc @ilovezfs since this originated from his #8184

### CODE REVIEW

**Comment by tschoonj** [comment]
Doesn't look like libgit2 and its GNOME dependents will see an update soon. Could easily be March before this happens.

From the libgit2 website:

> libgit2 is a portable, pure C implementation of the Git core methods provided as a re-entrant linkable library with a solid API, allowing you to write native speed custom Git applications in any language which supports C bindings.

Not sure why they call it solid when they break backwards compatibility about once a year 😢

**Comment by JCount** [comment]
Thanks for the info @tschoonj, I thought that something like that might be the case.

In that case, it might be worth doing a PR for a simple version bump for **gitless 0.8.5** since it is still compatible with the current **libgit2 0.24.5** formula. Any thoughts anyone?

**Comment by ilovezfs** [comment]
Is there a GNOME issue about this yet?

**Comment by JCount** [comment]
I couldn't find one, but honestly the GNOME bugzilla was making my head spin.

**Comment by tschoonj** [comment]
I opened a bug: https://bugzilla.gnome.org/show_bug.cgi?id=776506

**Comment by JCount** [comment]
Haha, @tschoonj I was about to hit enter on essentially the same bug. 😀

**Comment by tschoonj** [comment]
You're welcome 😄 

Also, no objections here if you want to update `gitless` in a separate PR

**Comment by JCount** [comment]
Ok, will do, especially since there is not roadmap for libgit2-glib.

**Comment by ilovezfs** [comment]
@JCount OK, I've shipped https://github.com/Homebrew/homebrew-core/pull/8275 so you should be back in business here.

**Comment by JCount** [comment]
@ilovezfs @tschoonj Looks like we are in business here.

**Comment by ilovezfs** [comment]
sweet!

**Comment by ilovezfs** [comment]
Shipped! Thanks @JCount

**Pull request closed without merging**
