### PR TITLE
Rubocop 0.57.1 style fixes

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Realign trailing EOS.

I'd rather see the `def caveats; <<-EOS` weird pattern changed but I'm open to either approach, really.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
As mentioned on the other PR, let's leave the caveats and plist as-is. Rubocop upgrade should not involve tweaking core heredocs with an established style.

**Comment by reitermarkus** [comment]
> I'd rather see the `def caveats; <<-EOS` weird pattern changed

If this isn't also changed, this PR doesn't make it better. `EOS` aligned with `end` just looks weird.

**Comment by ilovezfs** [comment]
>If this isn't also changed

And it should not be.

**Comment by MikeMcQuaid** [comment]
> If this isn't also changed, this PR doesn't make it better. EOS aligned with end just looks weird.

I agree so updated this PR accordingly.

> Rubocop upgrade should not involve tweaking core heredocs with an established style.

It doesn't need to but, like every RuboCop upgrade that introduces new warnings, it's worth considering whether our current style is better than the standard Ruby style that RuboCop espouses. In this case I think this PR helps make our `caveats` and `plist` more readable and more idiomatic.

**Comment by ilovezfs** [comment]
I strongly disagree with the more sweeping change. If you want to just shift the EOS: ok.

**Comment by MikeMcQuaid** [comment]
> I strongly disagree with the more sweeping change.

Can you elaborate on why? It would be good to have a conversation about the `def foo; ...` pattern; it's a bit weird.

**Comment by ilovezfs** [comment]
Because the indentation level is better kept under control and because it's been idiomatic in formulae for a while.

**Comment by DomT4** [comment]
FWIW, I agree with Joe on this one. I'm inevitably some degree of a hypocrite on this & I appreciate that, but I feel like it's confusing to have spent so much time enforcing a particular style on contributors and then overnight enforce a whole new style for no reason greater than it looking subjectively nicer.

**Comment by reitermarkus** [comment]
> no reason greater than it looking subjectively nicer.

I'd argue it looks objectively nicer.

```ruby
def caveats; <<~EOS
    Lorem ipsum.
  EOS
end
```

and 

```ruby
def caveats; <<~EOS
  Lorem ipsum.
  EOS
end
```

make no sense indentation-wise. Both

```ruby
def caveats; <<~EOS; end
  Lorem ipsum.
EOS
```

and preferably

```ruby
def caveats
  <<~EOS
    Lorem ipsum.
  EOS
end
```

would make more sense than the current style.

**Comment by MindTooth** [comment]
As a none-relevant person who has no say, I like the new style.  More cleaner and reasonable.
Just my 2 :dollar:
_(Talking about the last example of **reitermarkus**.)_

**Comment by ilovezfs** [comment]
I find the current style in core pleasing to behold, weird in no way, perfectly logical, and to make all the sense in the world. I'd go so far as to say it's gorgeous even.

By contrast the newly proposed style is verbose, overly indented, grotesque, and hard to understand.

**Comment by MindTooth** [comment]
I would argue:

```html
<div class="header">
  <h1>
    <a href="github.com">GitHub</a>
  </h1>
</div>
```
vs.
```html
<div class="header"><h1>
  <a href="github.com">GitHub</a>
  </h1>
</div>
```
Not sure the example is valid, but were my reasoning for viewing the proposed change as an acceptable & a logical change/improvement.

_(I now see that I should have include this in my original post, my apologies.)_

**Comment by MikeMcQuaid** [comment]
> If you want to just shift the EOS: ok.

Have reverted this PR back to that.

**Comment by ilovezfs** [comment]
🚀

**Comment by MikeMcQuaid** [comment]
Thanks @ilovezfs!

**Pull request merged**
