### PR TITLE
Go 1.11.5

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by leonklingele** [comment]
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ dir_chdir - src
```

Is this because I'm still on 10.11.6?

```
$ brew config | head -n3
HOMEBREW_VERSION: 1.9.2-91-gb221a46
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b221a46af2db8c99606af176c2c4fd10e072ccfb
```

**Comment by leonklingele** [comment]
After some debugging I found the reason: the new release tarball includes two garbage folders: `gocache` and `tmp` which screw up the build process, but I don't know why and how to fix it.

**Comment by leonklingele** [comment]
I don't know Ruby, but this seems to do the trick: https://github.com/Homebrew/homebrew-core/pull/36344/commits/715ee1c7b9d2551bf3e35d247246156f2ddbf9c7

**Comment by wingyplus** [comment]
Should we waiting for https://github.com/golang/go/issues/29906?

**Comment by leonklingele** [comment]
@wingyplus no, they "will not be updating the tarballs for this release". See https://github.com/golang/go/issues/29906#issuecomment-457015983.

**Comment by fxcoudert** [comment]
@leonklingele the comment you linked to also says:

> Only go1.11.5.linux-amd64.tar.gz and go1.10.8.linux-amd64.tar.gz are affected.

**Comment by fxcoudert** [comment]
@leonklingele the comment you linked to also says:

> Only go1.11.5.linux-amd64.tar.gz and go1.10.8.linux-amd64.tar.gz are affected.

Which is clearly not the case.

**Comment by leonklingele** [comment]
@fxcoudert this is a security release and should be merged asap. If they decide to create a new release without the temp directories, we can simply remove the workaround.

**Comment by tsuna** [comment]
Please merge this ASAP, thanks :)

**Pull request closed without merging**
