### PR TITLE
abseil 20211102.0

### PR DESCRIPTION
**Pull request by ismail**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
See previous attempt: https://github.com/Homebrew/homebrew-core/pull/89215

**Comment by ismail** [comment]
> See previous attempt: #89215

Yup saw that, or-tools compiles fine right now, one just needs to bump reverse dependencies for a recompile. Re-opening the original PR might be a better idea. Let me comment there.

**Comment by ismail** [comment]
@Moisan I did rev-bump reverse dependencies, but the tests do not rebuild them. Any tips?

**Comment by Moisan** [comment]
I'm not sure why it's failing right now. I'll mark the PR ready for review and relaunch the CI 🤞 .

**Comment by carlocab** [comment]
Rebased your PR since all the rev-bumped formulae were also given rev bumps that were not present in your branch.

**Comment by carlocab** [comment]
```
  Undefined symbols for architecture arm64:
    "absl::lts_20211102::container_internal::kEmptyGroup", referenced from:
        absl::lts_20211102::container_internal::EmptyGroup() in simple_sat_program-5a8542.o
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Not sure why this is happening, since or-tools should now work with this version of abseil.

**Comment by ismail** [comment]
or-tools fixed, etcd-cpp-apiv3 needed a revision bump, fingers crossed.

**Comment by ismail** [comment]
@carlocab @Moisan Not sure why 3 tests got cancelled by {11/12}-arm64 passed, so I believe it's good to go.

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
