### PR TITLE
coq: update libdir paths a la ocaml-findlib

### PR DESCRIPTION
**Pull request by JasonGross**
See https://github.com/coq/coq/issues/15663#issuecomment-1655145717 and https://github.com/coq/coq/issues/15635#issuecomment-1868450824.  Coq lib files must be installed to the same location as ocaml-findlib lib files in order for plugins to be buildable.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting? (sorry, I don't actually have a Mac)
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting? (sorry, I don't actually have a Mac)
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`? (sorry, I don't actually have a Mac, hopefully the CI will test this?)

-----

### CODE REVIEW

**Comment by JasonGross** [comment]
The problem on Linux looks like a stale cache problem.  There's no way the change I made here could cause an "inconsistent assumptions" error message

**Comment by JasonGross** [comment]
The error was "Stable: The source URL https://github.com/coq/coq/archive/refs/tags/V8.18.0.tar.gz is not reachable", let's try running yet again

**Comment by JasonGross** [comment]
And now the issue is that the job seems to have been cancelled for no reason?  What is up with the CI?

**Review by Bo98 — APPROVED** [review]
Thank you!

**Pull request merged**
