### PR TITLE
trace2html 2016-05-04

### PR DESCRIPTION
**Pull request by ndfred**
Pulled from latest master, points to my repo until the pull request to get the symlink working is done:
https://github.com/catapult-project/catapult/pull/2316

### CODE REVIEW

**Comment by apjanke** [comment]
I think we'll want to hold off on this until upstream incorporates the fix. Changing to use a non-official fork is a significant step.

**Comment by mikemcquaid** [comment]
We can apply upstream `master` commits as patches if need be, though.

**Comment by ndfred** [comment]
Cool, I'll get the patch landed in master and update this

**Comment by ndfred** [comment]
Our PR on catapult is still stalled, we'll update it today to get this through soon:
https://codereview.chromium.org/1957663002/

I updated my commit to pull in the latest version of catapult. I'll update this again once it is ready for review.

**Comment by apjanke** [comment]
Any movement on this? I don't see any releases made on that Catapult repo. (Homebrew requires labelled versions with discrete releases, not just a commit identifier in a Git repo.)

**Comment by ndfred** [comment]
The patch to fix symlinks is still waiting for a merge upstream.

The catapult maintainers do continuous rather than discrete releases (you always pull from master), is there a recommendation in that case or should we just pick a specific release and upgrade to it?

**Comment by MikeMcQuaid** [comment]
Let's reopen this when there's a merge/tag, thanks.

**Pull request closed without merging**
