### PR TITLE
libspatialindex 1.9.0

### PR DESCRIPTION
**Pull request by fjperini**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
A number of build errors produced
```
06:35:57 /usr/local/include/spatialindex/SpatialIndex.h:102:31: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
06:35:57                 virtual ~IEvolvingShape() = default;
06:35:57                                             ^
06:35:57 /usr/local/include/spatialindex/SpatialIndex.h:110:13: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
06:35:57                 ~IEntry() override = default;
06:35:57                           ^
06:35:57 fatal error: too many errors emitted, stopping now [-ferror-limit=]
06:35:57 53 warnings and 20 errors generated.
06:35:57 Error: spatialindex: failed
```

**Comment by fjperini** [comment]
@javian Any idea of what may be happening?

**Comment by Moisan** [comment]
Adding `ENV.cxx11` to the test should help. With the flags `ENV.cxx11` adds, I could build the test locally once `libspatialindex` is installed but not in the `brew test` environment. `brew test` instead outputs
```
Failed to execute: /usr/bin/clang++ -std=c++11 -stdlib=libc++
``` 
🤔

**Comment by fjperini** [comment]
@fxcoudert Thanks, you found the solution.

**Comment by fxcoudert** [comment]
Thanks @fjperini

**Pull request closed without merging**
