### PR TITLE
protobuf 3.12.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
A libtorch pull request was recently merged. Can you rebase (making sure the revision bump doesn't get lost)?

**Comment by alebcay** [comment]
Rebased.

**Comment by alebcay** [comment]
```
==> brew install --verbose --build-bottle protoc-gen-grpc-web
==> FAILED
==> Downloading https://github.com/grpc/grpc-web/archive/1.0.7.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/bab6d8c1f11dfa130ece2562000437c0aa09bb83fe5d5fe3970787566f22b161--grpc-web-1.0.7.tar.gz
==> Verifying bab6d8c1f11dfa130ece2562000437c0aa09bb83fe5d5fe3970787566f22b161--grpc-web-1.0.7.tar.gz checksum
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200519-69890-1cmytjf.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/protoc-gen-grpc-web.rb --build-bottle --verbose
Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/node not present or broken
Please reinstall node. Sorry :(
```

**Comment by Bo98** [comment]
That should be fixed with https://github.com/Homebrew/brew/commit/8b98ed1f4747852d1ceafcf38fb192f8d5f9da58

**Comment by alebcay** [comment]
We just have to wait for that to land in a `brew` release, right?

**Comment by Bo98** [comment]
Nah, the original commit that broke it is also from today and the last release was yesterday so the latest release doesn't have the issue. The CI always runs on the latest `master` commit.

**Comment by alebcay** [comment]
I'll try re-running the tests after the `postgresql` PR finishes going through CI.

**Comment by alebcay** [comment]
Everything passed, but... another merge conflict, another rebase. Time to rerun CI.

**Comment by alebcay** [comment]
Everything passed, but... another merge conflict, another rebase. Time to rerun CI.

**Review by chenrui333 — APPROVED** [review]
💯 🚢

**Pull request closed without merging**
