### PR TITLE
node@6 6.9.3

### PR DESCRIPTION
**Pull request by febLey**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — DISMISSED** [review]
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md

npm is supposed to be 3.10.10

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by marcokrikke** [comment]
Node6 LTS is currently at v6.9.4. npm stays at v3.10.10

**Comment by ilovezfs** [comment]
@febLey thanks for your contribution to Homebrew

**Pull request closed without merging**
