### PR TITLE
openfortivpn 1.12.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
 ./install-sh -c -d '/usr/local/Cellar/openfortivpn/1.12.0/bin'
 ./install-sh -c -d '/usr/local/Cellar/openfortivpn/1.12.0/share/openfortivpn'
 ./install-sh -c -d '/usr/local/Cellar/openfortivpn/1.12.0/share/man/man1'
mkdir: /usr/local/Cellar/openfortivpn/1.12.0/share: File exists
  /usr/bin/install -c openfortivpn '/usr/local/Cellar/openfortivpn/1.12.0/bin'
 /usr/bin/install -c -m 644 etc/openfortivpn/config.template '/usr/local/Cellar/openfortivpn/1.12.0/share/openfortivpn'
 /usr/bin/install -c -m 644 doc/openfortivpn.1 '/usr/local/Cellar/openfortivpn/1.12.0/share/man/man1'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-data-hook
chmod 0600 /usr/local/Cellar/openfortivpn/1.12.0/share/openfortivpn/config.template ; \
	if ! test -e /usr/local/Cellar/openfortivpn/1.12.0/etc/openfortivpn/config ; then \
		mkdir -p /usr/local/Cellar/openfortivpn/1.12.0/etc/openfortivpn ; \
		cp -a /usr/local/Cellar/openfortivpn/1.12.0/share/openfortivpn/config.template \
			 /usr/local/Cellar/openfortivpn/1.12.0/etc/openfortivpn/config ; \
	sed -i 's/^/# /' /usr/local/Cellar/openfortivpn/1.12.0/etc/openfortivpn/config ; \
	fi 
sed: 1: "/usr/local/Cellar/openf ...": extra characters at the end of l command
make[2]: *** [install-data-hook] Error 1
make[1]: *** [install-data-am] Error 2
make: *** [install-am] Error 2
```

**Comment by Bo98** [comment]
Does this patch work? https://github.com/Bo98/openfortivpn/commit/d2d7f32e06725bdf88a95a51783c65108dde5464.patch?full_index=1

(If it does, hold back on merging until I submit it upstream)

**Comment by DimitriPapadopoulos** [comment]
@Bo98 Please do not hesitate to create a pull request against _openfortivpn_. Alternatively I can fix _openfortivpn_  directly:

On GNU/Linux we currently use **`sed -i`** which edits files in-place without backup. Unfortunately it looks like the backup _extension_  argument to the **`-i`** option is not optional on FreeBSD as it is on GNU systems. I would therefore suggest **`sed -i''`** to avoid backups on both Linux and FreeBSD. Does it work for you?

**Comment by Bo98** [comment]
@DimitriPapadopoulos `sed -i'' -e` does not work on macOS - it creates a backup with the suffix `-e` and omitting `-e` is not supported. `sed -i '' -e` does work, but does not work on GNU sed. I'm not aware of a portable way of avoiding backups.

**Comment by DimitriPapadopoulos** [comment]
I see. There's probably a logical reason why GNU _sed_ requires the _extension_ parameter to follow the `-i` option without a space, but without knowing that reason this GNU _sed_ feature looks like a nasty bug :-)

So be it then: **`sed -i'.sed'`**

**Comment by Bo98** [comment]
I'll test the patch on our CIs shortly (to make sure I didn't mess up!) and send a pull request your way.

**Comment by DimitriPapadopoulos** [comment]
Or perhaps **`sed -i'.bak'`** just for the sake of readability. I find the two very different occurrences of _sed_ disturbing.

**Comment by Bo98** [comment]
Fair enough, I'll make it that.

**Comment by Bo98** [comment]
`sed` haunts my dreams too.

**Pull request closed without merging**
