### PR TITLE
apache-arrow apache-arrow-glib 14.0.2

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by raulcd** [comment]
It seems to be failing to build jemalloc due to `Bad file descriptor` which seems weird to me:
```
   [  9%] Performing build step for 'jemalloc_ep'
  cd /tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build/jemalloc_ep-prefix/src/jemalloc_ep && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.1/bin/cmake -P /tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-build-RELEASE.cmake
  CMake Error at /tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-build-RELEASE.cmake:37 (message):
    Command failed: 2
  
     '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make'
  
    See also
  
      /tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-build-*.log
  
  
  -- stdout output is:
  make[3]: Entering directory '/tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build/jemalloc_ep-prefix/src/jemalloc_ep'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-11 -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -Wno-missing-attributes -pipe -g3 -fvisibility=hidden -Wimplicit-fallthrough -O3 -funroll-loops -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/jemalloc.sym.o src/jemalloc.c
  make[3]: Leaving directory '/tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build/jemalloc_ep-prefix/src/jemalloc_ep'
  
  -- stderr output is:
  make[3]: *** read jobs pipe: Bad file descriptor.  Stop.
  make[3]: *** Waiting for unfinished jobs....
  
  CMake Error at /tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-build-RELEASE.cmake:47 (message):
    Stopping after outputting logs.
  
  
  make[2]: *** [CMakeFiles/jemalloc_ep.dir/build.make:89: jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-build] Error 1
  make[2]: Leaving directory '/tmp/apache-arrow-20231218-14842-qnv9xn/apache-arrow-14.0.2/build'
  make[1]: *** [CMakeFiles/Makefile2:978: CMakeFiles/jemalloc_ep.dir/all] Error 2
```
Should we just retry @p-linnane ?

**Comment by raulcd** [comment]
cc @kou

**Comment by p-linnane** [comment]
@raulcd I will rerun CI to see if there is any change in behavior.

**Comment by p-linnane** [comment]
Looks like this is only affecting Linux.

**Comment by kou** [comment]
In general, the error may be happen when we use parallel build feature of `make`. It's sometimes unstable...

Can we try using Ninja instead of `make`? It may avoid the error.

```diff
diff --git a/Formula/a/apache-arrow.rb b/Formula/a/apache-arrow.rb
index 2abf0a7bd6d..100cf888ede 100644
--- a/Formula/a/apache-arrow.rb
+++ b/Formula/a/apache-arrow.rb
@@ -20,6 +20,7 @@ class ApacheArrow < Formula
 
   depends_on "boost" => :build
   depends_on "cmake" => :build
+  depends_on "ninja" => :build
   depends_on "aws-sdk-cpp"
   depends_on "brotli"
   depends_on "bzip2"
@@ -69,6 +70,7 @@ class ApacheArrow < Formula
       -DARROW_WITH_UTF8PROC=ON
       -DARROW_INSTALL_NAME_RPATH=OFF
       -DPARQUET_BUILD_EXECUTABLES=ON
+      -GNinja
     ]
 
     args << "-DARROW_MIMALLOC=ON" unless Hardware::CPU.arm?
```

**Comment by p-linnane** [comment]
Thank you @kou. I've pushed that change. Let's see how it goes.

**Comment by p-linnane** [comment]
Looks like that did the trick. Thank you @raulcd & @kou for helping get this PR across the line.

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
