### PR TITLE
Go 1.12.1 released

### PR DESCRIPTION
**Pull request by kirillDanshin**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by leonklingele** [comment]
@kirillDanshin don't forget to [bump the revision for godep](https://github.com/Homebrew/homebrew-core/pull/37338/commits/bcf12a5ee77f3af1196ad8301ddd19bf1d7de500).

**Comment by kirillDanshin** [comment]
@leonklingele thank you! that my first contribution here and I didn't notice that.

**Comment by SMillerDev** [comment]
Nice going on your first contribution, first of many I hope 😄

**Comment by lembacon** [comment]
Thanks @kirillDanshin!

**Pull request closed without merging**
