### PR TITLE
libgccjit: depend on gcc

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/orgs/Homebrew/discussions/5364

### CODE REVIEW

**Comment by Bo98** [comment]
Do we need the dependency on Linux?

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/171811

**Comment by fxcoudert** [comment]
To be honest, I don't understand how this happens to work with a non-GCC compiler (or a different version of the GCC compiler). libgccjit is a giant wrapping of the GCC compiler itself, and it emits GCC-generated code, so it will call functions from its runtime library.

Ah, found it:

```
Breakpoint 2: where = libcompiler_rt.dylib`__muldc3, address = 0x000000018d09a1b8
```

so it is using the clang runtime libraries from the system. Doesn't seem like a good thing, though. And not sure that all functions are provided.

**Comment by Bo98** [comment]
Linux question was more of a question whether we need the latest GCC or whether using the system GCC (Homebrew's minimum is 11) is OK.

**Pull request closed without merging**
