### PR TITLE
boot2docker: fixes

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
Nice 👍 One more resolved in #4841.

**Comment by zmwangx** [comment]
Um what did I just do... I'll add the bottle commit soon... (Guess I was too happy to try out the rebase and merge.)

**Comment by zmwangx** [comment]
Bottle commit in f5a7d2a.

**Comment by DomT4** [comment]
😆 I thought you were going to forget to pull a bottle again for a moment!

**Comment by zmwangx** [comment]
Thanks to the hint in the title "Popular formulae with bottling trouble on 10.12", I didn't.

**Comment by DomT4** [comment]
Not having a ton of luck with Qt5 so far. The tip of the upstream 5.6, 5.7 and dev branches are all broken lol.

**Comment by zmwangx** [comment]
Nice. /s

**Comment by DomT4** [comment]
Yeah. Looking like might have to try the tip of the 5.7 branch with some patches from the dev branch. Bunch o'fun.

**Comment by zmwangx** [comment]
At this point you should just volunteer to be their release manager...

**Comment by DomT4** [comment]
Considering trying to slip someone at Qt a bribe to cut a working 5.7.1 tag today. Given we've refused to give up the `pkg-config` files for `qt5` we might as well call it a fork at this point, heh.

**Pull request merged**
