### PR TITLE
ykclient: various fix and improvements

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

`ykclient`, or actually `yubico-c-client`, has moved to https://developers.yubico.com/yubico-c-client/.

I'm adding the head build along the way. Note I'm using `ENV.deparallelize`: the Makefile in current master seems to be suffering from a race condition where `help2man` is called on the `ykclient` executable before it is even generated. I don't bother to report a bug at this point; hope they'll sort this out if they ever release another version.

### CODE REVIEW

**Comment by zmwangx** [comment]
Adding the maintainer feedback flag to see if anyone particularly hates `ENV.deparallelize` hack and the laziness of not reporting upstream.

**Comment by apjanke** [comment]
Come on, report upstream. 😄 🙏   How else are they going to know to fix it? A lot of developers don't seem to build in parallel.

**Comment by zmwangx** [comment]
Okay... https://github.com/Yubico/yubico-c-client/issues/38

**Comment by zmwangx** [comment]
Should I remove the `ENV.deparallelize` hack then? The ball is now in their hands, it's their duty to make sure master compiles. However, if they don't fix it, it is our (and their) users that will feel the pain.

**Comment by dunn** [comment]
If they don't respond in a few days, I'd leave it with a link to the upstream ticket.

**Comment by zmwangx** [comment]
Sounds reasonable 👍

**Comment by zmwangx** [comment]
Actually I'm just gonna add the comment and :shipit: (if no one objects in a given period of time). Then I'll remove the comment and the hack when once upstream has a fix.

**Pull request closed without merging**
