### PR TITLE
lazydocker 0.6.4 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
I think there is no need for this piece of code since `lazydocker` makes use of go modules + vendoring:
```ruby
ENV["GO111MODULE"] = "on"
ENV["GOPATH"] = buildpath

dir = buildpath/"src/github.com/jesseduffield/lazydocker"
dir.install buildpath.children
```

Also because of vendoring, it would be appropriate to append `-mod=vendor` to `go build`.

**Comment by chenrui333** [comment]
@dawidd6 Thanks for the comment, I will update my PR.

**Comment by chenrui333** [comment]
That does make sense, the build is much faster now. Did not using `go modules` with `vendoring` before.

**Comment by drothmaler** [comment]
Build seems to fail :-/ Maybe you could take another look... Also why didn't you just use the binaries, provided on GitHub, instead of building it from the sources?

**Comment by dawidd6** [comment]
Test is failing because of upstream bug, which should be fixed in master now https://github.com/jesseduffield/lazydocker/issues/140

**Comment by chenrui333** [comment]
@drothmaler homebrew-core formula requires building from the source for better or worse.

@dawidd6 cool! will update once there is a new release.

**Comment by dawidd6** [comment]
@chenrui333 FYI new release is up: https://github.com/jesseduffield/lazydocker/releases/tag/v0.6.4

**Comment by chenrui333** [comment]
Cool, updating the PR now.

**Comment by chenrui333** [comment]
Fixed the commit message to `v0.6.4`

**Comment by igas** [comment]
Thank you @chenrui333 and @dawidd6!

**Pull request closed without merging**
