### PR TITLE
pypy3 7.3.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by bayandin** [comment]
It looks like it requires `pypy` to get fixed and build for Big Sur first, see https://github.com/Homebrew/homebrew-core/pull/65854

**Comment by mattip** [comment]
Maybe update pypy.rb at the same time?

**Comment by mattip** [comment]
Also see https://foss.heptapod.net/pypy/pypy/-/issues/3314 which needs someone fluent in macOS to help work through supporting Big Sur on x64 (M1 support is a whole other thing).

**Comment by bayandin** [comment]
> Also see https://foss.heptapod.net/pypy/pypy/-/issues/3314 which needs someone fluent in macOS to help work through supporting Big Sur on x64 (M1 support is a whole other thing).

Yep, this exact thing we have found during `pypy` update: https://github.com/Homebrew/homebrew-core/pull/65854#issuecomment-735311575


> Maybe update pypy.rb at the same time?

It's possible, the only problem I see here it's BigSur incompatibility.

Meanwhile, I'll have a look if it's possible to update `pypy`/`pypy3` for pre-BigSur versions

**Comment by carlocab** [comment]
Merged in #68019.

**Comment by cclauss** [comment]
`brew install pypy3` now fails with:
```
AttributeError: No symbol SCDynamicStoreCopyProxies found in library <None>
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall pypy3`
```

**Comment by bayandin** [comment]
> `brew install pypy3` now fails with:
> 
> ```
> AttributeError: No symbol SCDynamicStoreCopyProxies found in library <None>
> Warning: The post-install step did not complete successfully
> You can try again using `brew postinstall pypy3`
> ```

Which version of macOS do you use? (`brew config` and `brew doctor` outputs will be helpful as well)
I've checked it on Catalina and Mojave and it installs without any problem.

As mentioned above, `pypy3` doesn't support BirSur yet. See https://foss.heptapod.net/pypy/pypy/-/issues/3314

**Comment by cclauss** [comment]
BigSur it is.
```
% brew config
HOMEBREW_VERSION: 2.7.1-58-g4186cd9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4186cd94a3dc60fc55757348282931b47197b1c9
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d95c6ee2144764548262885cd97faca46b1099c9
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.251.08
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A

% brew doctor
Your system is ready to brew.
```

**Pull request closed without merging**
