### PR TITLE
platformio 6.1.6

### PR DESCRIPTION
**Pull request by ivankravets**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

* Added support for Python 3.11
* Added a new [name](https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/generic/description.html) configuration option to customize a project name ([pull #4498](https://github.com/platformio/platformio-core/pull/4498))
* Made assets (templates, ``99-platformio-udev.rules``) part of Python's module ([issue #4458](https://github.com/platformio/platformio-core/issues/4458))
* Updated [Clang-Tidy](https://docs.platformio.org/en/latest/plus/check-tools/clang-tidy.html) check tool to v15.0.5 with new diagnostics and bugfixes
* Removed dependency on the "zeroconf" package and install it only when a user lists mDNS devices (issue with zeroconf's LGPL license)
* Show the real error message instead of "Can not remove temporary directory" when ["platformio.ini"](https://docs.platformio.org/en/latest/projectconf.html) configuration file is broken ([issue #4480](https://github.com/platformio/platformio-core/issues/4480))
* Fixed an issue with an incorrect test summary when a testcase name includes a colon ([issue #4508](https://github.com/platformio/platformio-core/issues/4508))
* Fixed an issue when [extends](https://docs.platformio.org/en/latest/projectconf/sections/env/options/advanced/extends.html) did not override options in the right order ([issue #4462](https://github.com/platformio/platformio-core/issues/4462))
* Fixed an issue when [pio pkg list](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_list.html) and [pio pkg uninstall](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_uninstall.html) commands fail if there are circular dependencies in the [library.json](https://docs.platformio.org/en/latest/manifests/library-json/index.html) manifests ([issue #4475](https://github.com/platformio/platformio-core/issues/4475))

### CODE REVIEW

**Comment by chenrui333** [comment]
#121331

**Comment by chenrui333** [comment]
@ivankravets why did this get closed?

**Comment by ivankravets** [comment]
CI failed with "revision: 1". I don't know who added that line to the manifest file. I didn't add it.

**Comment by chenrui333** [comment]
➕ to what SMillerDev said. 

You can also use `brew bump --open-pr platformio`, which would handle the `revision` for your next PR version bump. Thanks!

**Comment by ivankravets** [comment]
Sorry, we don't release PlatormIO Core so often. Typically a few times per year. 

What I noticed, the moderation team here changes often rules as well. The previous moderators asked me to recreate new PR even with small changes (extra spaces).

I always have problems with updating the PlatformIO formula. Maybe, we will ask you to remove it from the homebrew registry. Need to ask how many people used it. Mostly, developers use PlatormIO in pair with VSCode (above 3,000,000 developers, https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide), where PlatformIO is directly integrated into the extension.

Sorry again for the issues.

**Comment by SMillerDev** [comment]
> The previous moderators asked me to recreate new PR even with small changes (extra spaces).

Can you link that pull request because I doubt that.

> Maybe, we will ask you to remove it from the homebrew registry.

I think the 1000 users in the last 30 days would be pretty disappointed so that'll be a no from me.

**Comment by ivankravets** [comment]
I'll check the previous PR/releases and share them here.

Regarding the "1000 users in the last 30 days". Oh, I didn't know that so many of users use platformio via brew. So, let's keep it here.

Do you have any simple steps on how to generate `platformio` formula next time? I use the next:

1. Create a clean Python virtual environment
2. `pip install homebrew-pypi-poet`
3. poet -f platformio
4. Edit the existing `platformio` formula and merge changes manually. This is the place where "typos" happen.

**Comment by SMillerDev** [comment]
`brew bump --open-pr platformio` should be all you need.

**Comment by ivankravets** [comment]
Thanks, will try next time. Thanks again for your help!

**Pull request closed without merging**
