### PR TITLE
sbt@0.13: Fix lookup of Java home

### PR DESCRIPTION
**Pull request by nchammas**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The current formula fails to install with:

```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Java.java_home_cmd is disabled! Use Language::Java.java_home or Language::Java.overridable_java_home_env instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sbt@0.13.rb:25
```

This PR fixes this problem by replacing the deprecated `java_home_cmd` with `overridable_java_home_env`.

### CODE REVIEW

**Comment by nchammas** [comment]
I see that over in #60794 they've fixed a similar problem using `overridable_java_home_env` instead of `java_home`, whereas in #60850 they're using `java_home` as well.

Is there a preferred approach?

**Comment by SMillerDev** [comment]
`overridable_java_home_env` is definitely prefered. Since that allows users to pick their own Java if needed

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @nchammas  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by nchammas** [comment]
Happy to help. The Homebrew project, and the maintenance efforts of people like yourself @SMillerDev, have saved my co-workers and I untold hours installing software on our Macs.

**Pull request closed without merging**
