### PR TITLE
zellij 0.35.1

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by ZhongRuoyu** [comment]
```
Error: Failure while executing; `/usr/bin/env /usr/bin/skopeo copy --all oci:zellij--0.35.1 docker://ghcr.io/homebrew/core/zellij:0.35.1 --dest-creds=brewtestbot:******` exited with 1. Here's the output:
Getting image list signatures
Copying 7 of 7 images in list
Copying image sha256:a64ec9ba40b73e3f693b7948937ff48ebb08793bfa96c152bd4561911e67288a (1/7)
Getting image source signatures
Copying blob sha256:10e82b724bbddfdc30e85f8e997829a866e7746afc2f2be5a66ccaa19eeb9889
Copying config sha256:0ae1504d4532cbf9b20fb03c78f45b011fbb1ae37b0d8481641283f07e54f0f9
Writing manifest to image destination
Storing signatures
Copying image sha256:fb59505b10e207e624950fed4d6e0e508a073b4ad8cdb372d22f4ab2cb95e39e (2/7)
Getting image source signatures
Copying blob sha256:0fd82fa48a5a90b18507e945e032aa7dc700c90e6878961d68e946585109f4dd
time="2023-03-07T11:01:49Z" level=fatal msg="writing blob: Patch \"[https://ghcr.io/v2/homebrew/core/zellij/blobs/upload/fcf90ec5-bd4e-49c2-a348-384aa8579c03\](https://ghcr.io/v2/homebrew/core/zellij/blobs/upload/fcf90ec5-bd4e-49c2-a348-384aa8579c03/)": write tcp 172.18.0.2:53336->140.82.113.33:443: write: connection reset by peer"
```

**Comment by dawidd6** [comment]
Fix what?

**Comment by ZhongRuoyu** [comment]
> @dawidd6 how can we fix it? the version 0.35.0 was wrong and they released 0.35.1

@danillos did you mean https://github.com/Homebrew/homebrew-core/pull/124982#issuecomment-1457885516? This PR has already updated `zellij` to version 0.35.1. Try `brew update && brew upgrade zellij`.

**Comment by danillos** [comment]
For me it shows:

```
brew update && brew upgrade zellij
Already up-to-date.
Warning: zellij 0.35.0 already installed
```

**Comment by dawidd6** [comment]
Try again now. API data needed some time to regenerate.

**Comment by danillos** [comment]
> Try again now. API data needed some time to regenerate.

I think homebrew had some kind of issue. It only worked after I run `brew search zellij`.

```
brew search zellij
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
```

**Comment by ZhongRuoyu** [comment]
> The `brew version` still show an older version:

Since [version 4.0.0](https://brew.sh/2023/02/16/homebrew-4.0.0/), `brew` has switched to using a JSON API for installation of formulae. As a result of this, the two taps `homebrew/core` and `homebrew/cask` have stopped updating since you last updated `brew`.

As mentioned in the release notes, you may `brew untap homebrew/core` and `brew untap homebrew/cask` unless you need these Git repos.

**Comment by ZhongRuoyu** [comment]
> It only worked after I run `brew search zellij`.

This was likely because your local copy of API results happened to have expired when you did that. In that case `brew update` and many other commands would also fetch the latest results from the API.

**Pull request closed without merging**
