### PR TITLE
heroku 6.11.3

### PR DESCRIPTION
**Pull request by jdx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
We tightened up the description audit:
```
        == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/heroku.rb ==
C:  2: 48: Description shouldn't include the formula name

1 file inspected, 1 offense detected
```
We can maybe whitelist this, but if you can think of a way to reword it that'd be great.

**Comment by dickeyxxx** [comment]
hmm. It's difficult. I could change the description to just "CLI client" but that seems extremely vague

**Comment by dunn** [comment]
Maybe `Command-line tools for the cloud PaaS`?

**Comment by dickeyxxx** [comment]
sounds good, updated

**Comment by dunn** [comment]
Thanks! Merged together as 7a8bfac209e734e2be3cc3e922f8d333a3a8e65c.

**Pull request closed without merging**
