### PR TITLE
conjure-up 2.5.9

### PR DESCRIPTION
**Pull request by adam-stokes**
Misc compat changes:

- Pulls in websockets from upstream
- Pulls in beta2 of PyYAML

Soon as a websockets 5.0.2 and PyYAML 4.2 stable are released I'll push a new
update to account for those. In the interest of time and unblocking homebrew
these decisions were made.

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by battlemidget** [comment]
@ilovezfs sorry for the delay, im around the rest of the night if you need me to do anything else.

Thanks!!

**Comment by ilovezfs** [comment]
I'm seeing 
```
==> /usr/local/Cellar/conjure-up/2.5.7/bin/conjure-up openstack-base metal --show-env
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.5.7/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.5.7', 'console_scripts', 'conjure-up')()
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/conjureup/app.py", line 27, in <module>
    from conjureup import charm, consts, controllers, errors, events, juju, utils
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/conjureup/controllers/__init__.py", line 41, in <module>
    from conjureup import events
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/conjureup/events.py", line 10, in <module>
    from conjureup import errors, utils
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/conjureup/utils.py", line 31, in <module>
    from conjureup.telemetry import track_event
  File "/usr/local/Cellar/conjure-up/2.5.7/libexec/lib/python3.7/site-packages/conjureup/telemetry.py", line 8
    from conjureup.async import submit
                       ^
SyntaxError: invalid syntax
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Test::Unit::AssertionFailedError: <0> expected but was
```

**Comment by ilovezfs** [comment]
@battlemidget maybe because it's missing the version bump to 2.5.8? With 2.5.8 I see this
```
==> Summary
🍺  /usr/local/Cellar/conjure-up/2.5.8: 3,997 files, 36.0MB, built in 1 minute 50 seconds
iMac-TMP:homebrew-core joe$ brew test -vd conjure-up
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/conjure-up.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libyaml.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/juju.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/juju-wait.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jq.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/redis.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awscli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pwgen.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
Testing conjure-up
/usr/bin/sandbox-exec -f /tmp/homebrew20180629-14575-1mmj1eo.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew:/usr/local/Homebrew/Library/Homebrew/cask/lib -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/conjure-up.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/conjure-up.rb
==> /usr/local/Cellar/conjure-up/2.5.8/bin/conjure-up openstack-base metal --show-env
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.5.8/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.5.8', 'console_scripts', 'conjure-up')()
  File "/usr/local/Cellar/conjure-up/2.5.8/libexec/lib/python3.7/site-packages/conjureup/app.py", line 370, in main
    spell['key']))
  File "/usr/local/Cellar/conjure-up/2.5.8/libexec/lib/python3.7/site-packages/conjureup/utils.py", line 490, in set_chosen_spell
    track_event("Spell Choice", spell_name, "")
  File "/usr/local/Cellar/conjure-up/2.5.8/libexec/lib/python3.7/site-packages/conjureup/telemetry.py", line 38, in track_event
    app.loop.run_in_executor(None, partial(_post_track, args))
AttributeError: 'NoneType' object has no attribute 'run_in_executor'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Test::Unit::AssertionFailedError: <0> expected but was
```

**Comment by battlemidget** [comment]
Trying to get this built again, but hitting:

```
  Removing source in /private/tmp/pip-req-build-ca7y1cj3
Command "/usr/local/Cellar/conjure-up/2.5.9/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-ca7y1cj3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-z700xuwp/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/conjure-up/2.5.9/libexec/bin/../include/site/python3.7/bcrypt" failed with error code 1 in /private/tmp/pip-req-build-ca7y1cj3/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.5.9/libexec/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/conjure-up/2.5.9/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/conjure-up/2.5.9/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/conjure-up/2.5.9/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/Cellar/conjure-up/2.5.9/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/conjure-up/2.5.9/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-ca7y1cj3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-z700xuwp/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/conjure-up/2.5.9/libexec/bin/../include/site/python3.7/bcrypt" failed with error code 1 in /private/tmp/pip-req-build-ca7y1cj3/

```

Seems to only happen with 3.7

**Comment by ilovezfs** [comment]
make sure `cffi` gets installed first. See

https://github.com/Homebrew/homebrew-core/blob/444afb242c2d69f7ed7943f9c9f66c69cf42ae57/Formula/fdroidserver.rb#L346
https://bitbucket.org/cffi/cffi/issues/367/problems-installing-other-packages-with

**Comment by battlemidget** [comment]
:crossed_fingers: this works now @ilovezfs

**Comment by ilovezfs** [comment]
Awesome work! Thanks again @battlemidget 💯

**Pull request closed without merging**
