### PR TITLE
sambamba 1.0.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## ChangeLog v1.0.1 (20230816)

+ Fixed the build for recent ldc2 compilers by using a recent msgpack
+ Ran benchmarks and optimized meson build

</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
`  Errno::ENOENT: No such file or directory @ rb_sysopen - BioD/bio/std/hts/thirdparty/msgpack.d`

**Comment by chenrui333** [comment]
```
  ldc2 -wi -I. -I./BioD:./BioD/contrib/msgpack-d/src -g -J. -O3 -release -enable-inlining -boundscheck=off -L=-flto=full -of=bin/sambamba-1.0.1 bin/sambamba-1.0.1.o  -L-lz -L-llz4
  ld: unknown option: -flto=full
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Error: /opt/homebrew/Library/Homebrew/shims/mac/super/gcc failed with status: 1
  make: *** [bin/sambamba-1.0.1] Error 1
```

**Comment by mjsteinbaugh** [comment]
@chenrui333 I just got this working on my Mac, looks like you have to use `export CC=gcc` outside of the `make` call.

Here's my build script, for reference:
https://github.com/acidgenomics/koopa/blob/main/lang/bash/include/install/common/shared/sambamba.sh

**Comment by chenrui333** [comment]
@mjsteinbaugh thanks for the pointer, I just disabled that `-flto=full` instead, which should help the CI build now.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
