### PR TITLE
openjdk@8 1.8.0+332

### PR DESCRIPTION
**Pull request by allen-servedio**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by allen-servedio** [comment]
This is the first time I have submitted one of these, so maybe this is normal, but this test is still running after 17 hours?

Screen Shot 2022-05-26 at 08 36 02

**Comment by Bo98** [comment]
No, that doesn't seem normal. Looks like something changed in this version that is causing the build to hang.

**Comment by allen-servedio** [comment]
Okay @Bo98 - so what do we do in this case? I looked around a little and do not see a way to see any logs about this job to see what is happening. Is this something you all can stop? 

This is the last time someone updated this: https://github.com/Homebrew/homebrew-core/pull/95575

I do see this change after that PR too: https://github.com/Homebrew/homebrew-core/commit/0e987ec8f2813ce4353968ec37dacaf77a387559

**Comment by allen-servedio** [comment]
I pulled the latest commits and rebased my PR. If this hangs again, I will just close this until I or someone else has a chance to see what is hanging.

**Comment by allen-servedio** [comment]
Looks like this is required for this PR to run:

```
Error: PR requires the CI-long-timeout label but it is not set!
Error: If the longer timeout is not required, remove the "long build" label.
Error: Otherwise, add the "CI-long-timeout" label.
Error: No more than 2 PRs at a time may use "CI-long-timeout".
```

**Comment by SMillerDev** [comment]
Label added, let's see how far we get

**Comment by cho-m** [comment]
Looks like build got stuck again since run is now over 8 hours, so going to cancel.

This will probably require trying to build locally to figure out where it is stalling or checking upstream build changes that got added to this release. Probably can just see if run gets stuck during `brew install --build-from-source --verbose ...`.

**Comment by allen-servedio** [comment]
Okay @cho-m . Let me know if you want this PR closed until that is figured out or just try to add any fixes found into the PR.

**Comment by SMillerDev** [comment]
It's fine if you add any fixes here

**Comment by allen-servedio** [comment]
Sorry about the continued delay, it is taking me sometime to get to this. I found where it is hanging - I am trying to determine WHY it is hanging:

```
configure: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/config.status
config.status: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/spec.gmk
config.status: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/hotspot-spec.gmk
config.status: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/bootcycle-spec.gmk
config.status: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/compare.sh
config.status: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/spec.sh
config.status: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/Makefile
config.status: creating /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release/config.h
found it

====================================================
A new configuration has been successfully created in
/private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/build/release
using configure arguments '--with-boot-jdk-jvmargs=-Duser.home=/Users/allenservedio/Library/Caches/Homebrew/java_cache --with-boot-jdk=/private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/boot-jdk --with-debug-level=release --with-conf-name=release --with-jvm-variants=server --with-milestone=fcs --with-native-debug-symbols=none --with-update-version=332 --with-vendor-bug-url=https://github.com/Homebrew/homebrew-core/issues --with-vendor-name=Homebrew --with-vendor-url=https://github.com/Homebrew/homebrew-core/issues --with-vendor-vm-bug-url=https://github.com/Homebrew/homebrew-core/issues --with-toolchain-type=clang'.

Configuration summary:
* Debug level:    release
* JDK variant:    normal
* JVM variants:   server
* OpenJDK target: OS: macosx, CPU architecture: x86, address length: 64

Tools summary:
* Boot JDK:       openjdk version "1.7.0_322" OpenJDK Runtime Environment (Zulu 7.50.0.11-CA-macosx) (build 1.7.0_322-b01) OpenJDK 64-Bit Server VM (Zulu 7.50.0.11-CA-macosx) (build 24.322-b01, mixed mode)  (at /private/tmp/openjdkA8-20220613-90932-14iiic3/jdk8u332-b09/boot-jdk)
* Toolchain:      clang (clang/LLVM)
* C Compiler:     Version 13.1.6 (at /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang)
* C++ Compiler:   Version 13.1.6 (at /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++)

Build performance summary:
* Cores to use:   7
* Memory limit:   32768 MB

==> make bootcycle-images CONF=release
Building 'release' (matching CONF=release)
/bin/sh: line 0: [: too many arguments
```

It just stops after that last log line (basically the build is hung at that point).

**Comment by allen-servedio** [comment]
This is what is running:
Screen Shot 2022-06-13 at 09 00 10

Which translates to:
```
> ps | grep '756\|519\|2130\|2137\|4864\|4878\|4879\|4880'
  519 ttys000    0:02.51 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W1 --disable=rubyopt /usr/local/Homebrew/Library/Homebrew/brew.rb install --build-from-source --verbose openjdk@8

  756 ttys000    0:46.07 -zsh

 2130 ttys000    0:00.06 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W1 --disable=rubyopt /usr/local/Homebrew/Library/Homebrew/brew.rb install --build-from-source --verbose openjdk@8

 2137 ttys005    0:14.20 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk@8.rb --verbose

 4864 ttys005    0:00.02 /Applications/Xcode.app/Contents/Developer/usr/bin/make bootcycle-images CONF=release

 4878 ttys005    0:00.00 /bin/sh -c cd /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09 ; if [ -d  -a "" != "" ] ; then  >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; elif [ -f  ] ; then /usr/bin/printf ":%s" "$( /bin/cat  )" >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; fi;

 4879 ttys005    0:00.00 /bin/sh -c cd /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09 ; if [ -d  -a "" != "" ] ; then  >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; elif [ -f  ] ; then /usr/bin/printf ":%s" "$( /bin/cat  )" >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; fi;

 4880 ttys005    0:00.00 /bin/cat
```

So in `build/release/make/Main.gmk` there is the `bootcycle-images` target:
```
bootcycle-images: images bootcycle-images-only
bootcycle-images-only: start-make
	@$(ECHO) Boot cycle build step 2: Building a new JDK image using previously built image
	@($(CD) $(SRC_ROOT) && $(BUILD_LOG_WRAPPER) $(MAKE) SPEC=$(dir $(SPEC))bootcycle-spec.gmk images)
```

Which calls `images` first:
```
# Note: This double-colon rule is intentional, to support
# custom make file integration.
images:: source-tips demos nashorn images-only
images-only: start-make
	@$(call TargetEnter)
	@($(CD) $(JDK_TOPDIR)/make && $(BUILD_LOG_WRAPPER) $(MAKE) $(MAKE_ARGS) -f BuildJdk.gmk images)
	@$(call TargetExit)
```

Which calls `source-tips` first:
```
# Stores the tips for each repository. This file is be used when constructing the jdk image and can be
# used to track the exact sources used to build that image.
source-tips: $(OUTPUT_ROOT)/source_tips
$(OUTPUT_ROOT)/source_tips: FRC
	@$(MKDIR) -p $(@D)
	@$(RM) $@
	@$(call GetSourceTips)
```

That `call GetSourceTips` (which is what appears to be running) is defined as:
```
# Emit the scm:id pair to $@
define GetSourceTips
	$(CD) $(SRC_ROOT) ; \
	if [ -d $(SCM_DIR) -a "$(SCM_VERSION)" != "" ] ; then \
	  $(ID_COMMAND) >> $@ ; \
	elif [ -f $(SCM_TIP_FILENAME) ] ; then \
          $(SCM_TIP_FILECMD) >> $@ ; \
	fi;
	$(PRINTF) "\n" >> $@
endef
```

That function looks like it gets translated to (I am putting line breaks to match the function and make it easier to read):
```
/bin/sh -c cd /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09 ; 

if [ -d  -a "" != "" ] ; then

  >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; 

elif [ -f  ] ; then 

  /usr/bin/printf ":%s" "$( /bin/cat  )" >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; 

fi;
```

And I can see that there is no `/private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips` file created and it looks like it is running the `elif` part of that since `cat` is running as part of the process tree.

Also, when I run that last command, I get the same failure that I am seeing in the build. Here is an example of me running JUST that source_tips command from the terminal:

```
> /bin/sh -c 'cd /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09 ; if [ -d  -a "" != "" ] ; then  >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; elif [ -f  ] ; then /usr/bin/printf ":%s" "$( /bin/cat  )" >> /private/tmp/openjdkA8-20220613-2137-13s42qq/jdk8u332-b09/build/release/source_tips ; fi;'
/bin/sh: line 0: [: too many arguments
```

**Comment by allen-servedio** [comment]
Okay, so considering that @Bo98 - I don't think there is any reason to leave this PR open :-). At least I learned a bit more about building the JDK. I will close it and wait for the next release.

**Pull request closed without merging**
