### PR TITLE
questdb 5.0.4

### PR DESCRIPTION
**Pull request by bluestreak01**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bluestreak01** [comment]
guys, could someone give these checks a kick? they are well and truly stuck

**Comment by Rylan12** [comment]
They are not stuck. When our CI runners are available the checks will run. You can monitor the [queue](https://github.com/Homebrew/homebrew-core/actions?query=is%3Aqueued) to see where this PR stands.

**Comment by bluestreak01** [comment]
erm, there are things on the queue that are 15 months old. Is that a good approximation for these checks to run?

**Comment by SMillerDev** [comment]
Those can be ignored, but anything in that list that's actually related to a formula is ahead of you in the queue

**Comment by Rylan12** [comment]
Filtering by [GitHub Actions CI](https://github.com/Homebrew/homebrew-core/actions?query=is%3Aqueued+workflow%3A%22GitHub+Actions+CI%22) will not show you those.

**Comment by bayandin** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/66245

**Pull request closed without merging**
