### PR TITLE
jpeg-xl 0.9.2

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>### Fixed
 - bugs in the gdk-pixbuf plugin
 - some build issues
 
 **Note:** This release is for evaluation purposes and may contain bugs, including security bugs, that may not be individually documented when fixed. See the [SECURITY.md](SECURITY.md) file for details. Always prefer to use the latest release.
 
Please provide feedback and report bugs [here](https://github.com/libjxl/libjxl/issues).</pre>
</details>

### CODE REVIEW

**Comment by miccal** [comment]
Resource checked via https://github.com/libjxl/libjxl/tree/v0.9.2/third_party and points to https://github.com/webmproject/sjpeg/tree/e5ab13008bb214deb66d5f3e17ca2f8dbff150bf, hence does not need updating.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by jonsneyers** [comment]
Not sure if it should be done together with this version bump, but it would be nice to set `-DJPEGXL_ENABLE_DEVTOOLS=ON` in the build script so all the peripheral tools get built too (in particular the butteraugli and ssimulacra2 metrics).
Perhaps it's also worthwhile to enable jpegli instead of disabling it.

**Comment by bevanjkay** [comment]
jpegli was disabled with the update to 0.9.0 as we could not successfully build with it enabled. That may have changed since.

**Comment by p-linnane** [comment]
We discussed the possibility of a dedicated long build queue at our annual general meeting last week. CC @Bo98 for thoughts on what that would take.

**Pull request closed without merging**
