### PR TITLE
fix sha256 hash for docker-completion v17.04.0-ce

### PR DESCRIPTION
**Pull request by Cinal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Cinal** [comment]
Actual sha256 hash is 76e84fbb7b5f1077f424ff40ddd14c98247f5aa3f49ad6412eede5a8cb11a29e

==> Downloading https://github.com/docker/docker/archive/v17.04.0-ce.tar.gz
Error: SHA256 mismatch
Expected: b6ee0aa93ecea44e956d3627907e10557b3ec37d13ddfb40e436656e5037c640
Actual: 76e84fbb7b5f1077f424ff40ddd14c98247f5aa3f49ad6412eede5a8cb11a29e

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Any idea why this checksum changed? Can you submit an issue upstream to check this was intentional and that they haven't been hacked? Thanks!

**Comment by Cinal** [comment]
Issue: #12833

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for this PR. Yeah it turns out this is caused by the upstream repository having just been renamed "moby."

**Comment by Cinal** [comment]
@ilovezfs thanks

**Pull request merged**
