### PR TITLE
bluepill 5.5.3

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Previous attempt: https://github.com/Homebrew/homebrew-core/pull/65673

**Comment by carlocab** [comment]
@bayandin Thanks. Errors look like they have to be dealt with upstream, no? I'll take a closer look at it and send a report if needed.

**Comment by chenrui333** [comment]
it had pretty much the same issues in the past builds for 10.15, not sure how to tackle it :(

**Comment by bayandin** [comment]
Looking at the error message 
> CoreSimulator is out of date. Current version (681.17.2) is older than build version (732.18.0).

Can't say exactly, but it could be related to some CI misconfiguration (for example older simulators). There's a similar question https://developer.apple.com/forums/thread/666924

**Comment by carlocab** [comment]
Yep, same error:
```
==> xcodebuild -workspace Bluepill.xcworkspace -scheme bluepill -configuration Release SYMROOT=../
2020-12-09 21:01:46.206 xcodebuild[12131:8417982]  DVTErrorPresenter: Unable to load simulator devices.
Domain: DVTCoreSimulatorAdditionsErrorDomain
Code: 3
Failure Reason: The version of the CoreSimulator framework installed on this Mac is out-of-date and not supported by this version of Xcode.
Recovery Suggestion: Please ensure that you have installed all available updates to your Mac's software, and that you are running the most recent version of Xcode supported by macOS.
--
CoreSimulator is out of date. Current version (681.17.2) is older than build version (732.18.0).
Domain: DVTCoreSimulatorAdditionsErrorDomain
Code: 3
--
2020-12-09 21:01:46.206 xcodebuild[12131:8417982]  iOSSimulator: [SimServiceContext sharedServiceContextForDeveloperDir:error:] returned nil (Error Domain=DVTCoreSimulatorAdditionsErrorDomain Code=3 "CoreSimulator is out of date. Current version (681.17.2) is older than build version (732.18.0)." UserInfo={NSLocalizedDescription=CoreSimulator is out of date. Current version (681.17.2) is older than build version (732.18.0).}). Simulator device support disabled.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace Bluepill.xcworkspace -scheme bluepill -configuration Release SYMROOT=../

Build settings from command line:
    SYMROOT = ../

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: The linked framework 'CoreSimulator.framework' is missing one or more architectures required by this target: arm64. (in target 'bp' from project 'bp')
error: The linked framework 'CoreSimulator.framework' is missing one or more architectures required by this target: arm64. (in target 'bplib' from project 'bp')

** BUILD FAILED **
```

**Comment by carlocab** [comment]
Seems like they just don't support Xcode 12.2. https://github.com/linkedin/bluepill/issues/459

I'll try to build it locally to see if that gets me somewhere, but I'm not sure there's much I can do for this formula. I'll leave this PR open in case someone comes across it and can help.

**Pull request closed without merging**
