### PR TITLE
upgrade bazel 0.23.1

### PR DESCRIPTION
**Pull request by hawkingrei**
- [x] Have you followed the guidelines for contributing?
- [x] Have you checked that there aren't other open pull requests for the same formula update/change?
- [x] Have you built your formula locally with brew install --build-from-source <formula>, where <formula> is the name of the formula you're submitting?
- [x] Is your test running fine brew test <formula>, where <formula> is the name of the formula you're submitting?
- [x] Does your build pass brew audit --strict <formula> (after doing brew install <formula>)?

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @hawkingrei

**Comment by jonchang** [comment]
Fixed bottles in commit ca6b39ae991c21cb1d535527338dfaeef021d132.

**Comment by fxcoudert** [comment]
Oops… sorry

**Comment by fxcoudert** [comment]
Oops… sorry

**Pull request merged**
