### PR TITLE
protobuf 3.0.2 (devel)

### PR DESCRIPTION
**Pull request by vhbit**
Updated location, removed `version` as `audit` insisted.

### CODE REVIEW

**Comment by zmwangx** [comment]
https://github.com/google/protobuf/releases/tag/v3.0.2 marks it as "latest release". Why is it a devel release?

(I did notice https://developers.google.com/protocol-buffers/docs/downloads still points to 3.0.0, but maybe they're just slow at updating their website. Asking to make sure.)

**Comment by ilovezfs** [comment]
Putting this in devel has already been suggested and rejected in favor of https://github.com/Homebrew/homebrew-core/pull/4145 but thanks nonetheless for this PR!

**Comment by ilovezfs** [comment]
@zmwangx you can make it up to me by helping jmhodges figure out what's wrong with upscaledb+protobuf3 :)

**Comment by zmwangx** [comment]
@ilovezfs No, I'm going to bed 😉

**Comment by ilovezfs** [comment]
hehe ok :)

**Comment by vhbit** [comment]
oops, that was fast :-) #4145 indeed looks much better, hope it'll get merged soon.

**Comment by ilovezfs** [comment]
@zmwangx I fixed it

```
bash-3.2$ ./test
success!
```

**Comment by zmwangx** [comment]
@ilovezfs Good for you. Now I'm going to try to finish up my hour-long "going to bed" process 😉

**Comment by ilovezfs** [comment]
@zmwangx https://github.com/Homebrew/homebrew-core/pull/4145#issuecomment-245498045

**Pull request closed without merging**
