### PR TITLE
Jmeter: 5.2.1 plugin manager

### PR DESCRIPTION
**Pull request by nxft**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
Can you also link some docs or release notes into this PR? That would be awesome.

Thanks @NonoXie!!

**Comment by NonoXie** [comment]
> Can you also link some docs or release notes into this PR? That would be awesome.
> 
> Thanks @NonoXie!!

Sorry for late response due to Chinese New Year @chenrui333, I thought the PR has been merged into master? or you mean update in this part?

image

**Comment by chenrui333** [comment]
@NonoXie even though the PR has been merged, it is never too late to provide some context and motivation for the PR itself though.

**Comment by chenrui333** [comment]
Did not know how to reply you thru email, I will just reply in here.

**Pull request closed without merging**
