### PR TITLE
singularity 3.8.1 (new formula)

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
90 installs a year, I think we can drop it. Unless we need it for something

**Comment by danielnachun** [comment]
cc @Homebrew/linux Any thoughts on keeping or deleting this formula?  I'm not aware of anything we need it for but it would be good to give a bit of time for feedback.

**Comment by danielnachun** [comment]
I was going back over formula requirements and I see we do make exceptions if a package has its own website.  Singularity most certainly does, and a very polished one at that: https://sylabs.io/singularity/.  I think this might qualify for an exception to the notability requirements.  Do we think this is reasonable?

**Comment by SMillerDev** [comment]
I'm unsure how spending money or effort on a website makes your project more popular without showing up in the hosting stats we check.

**Comment by jonchang** [comment]
Singularity is not exactly some fly-by-night software. https://github.com/hpcng/singularity is the older github url not associated with sylabs.

**Comment by danielnachun** [comment]
Thanks for clarifying this @jonchang.  This now passes audit and should be ready to merge.

**Review by jonchang — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]
Thanks @danielnachun!

**Pull request merged**
