### PR TITLE
Update prototool 256 hash

### PR DESCRIPTION
**Pull request by smaye81**
Updating prototool hash to correct sha256

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like you've created a prototool file outside the formula directory instead of patching the one that already exists.

Do you know why the sha256 changed?

**Comment by SMillerDev** [comment]
>Looks like you've created a prototool file outside the formula directory instead of patching the one that already exists. ...

@mistydemeo there's an issue about that, apparently upstream tagged it but wasn't ready to release yet.

**Comment by mistydemeo** [comment]
> @mistydemeo there's an issue about that, apparently upstream tagged it but wasn't ready to release yet.

Hm, if there's changes maybe we should revision it to make sure everyone gets one built from this version?

**Comment by smaye81** [comment]
Not sure why this keeps failing the checks.  Can we maybe revert this update and I can run `brew bump-formula-pr` to update the formula?

**Comment by SMillerDev** [comment]
Reverting it would fail a lot more checks. You need to add a `revision 1` to the formula so it'll actually update for everyone.

**Comment by mistydemeo** [comment]
Can you also remove the spare prototool file, too? Thanks!

**Comment by smaye81** [comment]
OK, I closed this one and opened https://github.com/Homebrew/homebrew-core/pull/41002.  Let me know if I'm doing it correctly.  I've never actually had to update these files by hand before.

**Pull request closed without merging**
