### PR TITLE
rust 1.9.0

### PR DESCRIPTION
**Pull request by mrageh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by CamJN** [comment]
Patch doesn't apply any more. Is it still needed?

**Comment by dunn** [comment]
Looks like it was backported, so it ought to be safe to remove.

**Comment by DomT4** [comment]
Does `cargo` not need updating this time around?

**Comment by mrageh** [comment]
@DomT4 I can't see a new release of [Cargo](https://github.com/rust-lang/cargo/releases) right now, maybe they'll release another version in the near future?

**Comment by DomT4** [comment]
If there's no new release and it builds fine I guess we should be safe enough. Thanks for checking.

**Comment by mrageh** [comment]
Well when I run `brew audit --strict --online rust` on my machine I see this error message 

```
çrust:
  * `bottle block` (line 35) should be put before `head block` (line 28)
Error: 1 problem in 1 formula
```

And putting the `bottle block` before the `head block` fixes the problem, should I update `Forumal/rust.rb` with the same fix?

**Comment by DomT4** [comment]
Don't worry about that. I'll probably do it in post, given Rust takes a little over an hour to build on our CI and each commit will be built individually, so pushing a new commit for a style tweak = another hour of CI 🙈.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/595b2e4c8d5fb654c676e61740be97fe1af2795c. Thank you for your contribution to Homebrew @mrageh; we appreciate it! :smiley_cat:

**Comment by mrageh** [comment]
Thanks @DomT4 glad to make my first contribution to homebrew

**Pull request closed without merging**
