### PR TITLE
cfr-decompiler 0.149

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by dwijnand** [comment]
Needs this small diff applied to the test fixture:

```diff

   test do
     fixture = <<~EOS
-      import java.io.PrintStream;
-
+      /*
+       * Decompiled with CFR 0.149.
+       */
       class T {
           T() {
           }
```

**Comment by pthariensflame** [comment]
This is now stale.

**Comment by SMillerDev** [comment]
It's redundant rather than stale. Closing nonetheless

**Pull request closed without merging**
