### PR TITLE
urbit 0.5.1

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by ilovezfs** [comment]
The error is `ar: softfloat/usr/local/Cellar/urbit/0.5.1/share: No such file or directory` and is likely caused by a mishandling of the LIB parameter somewhere in the Makefile. We run

```
 system "make", "BIN=#{bin}", "LIB=#{share}"
```
where that expands to
```
system "make", "BIN=/usr/local/Cellar/urbit/0.5.1/bin", "LIB=/usr/local/Cellar/urbit/0.5.1/share"
```

**Comment by ilovezfs** [comment]
Yes reverting that fixes it.

**Comment by ohAitch** [comment]
So there's a Makefile bug in a *vendored dependency*, which only manifested when we built it for a *different architecture*. @belisarius222 was the original commit's motivation just using 64bit instructions?

**Comment by belisarius222** [comment]
The original motivation was that make was failing on my Linux machine, and I think it was failing on a mac too. These were all 64-bit machines, so it seemed strange to be using the 32-bit build in the first place. I don't know how the internals of softfloat differ between the two builds, but switching it to the 64-bit build fixed the build on both Linux and mac when using make directly.

**Comment by belisarius222** [comment]
@ilovezfs thanks for helping out!

**Comment by ilovezfs** [comment]
Please reopen when this is fixed

**Comment by ilovezfs** [comment]
@belisarius222 @ohAitch what's the status on getting a new upstream version with that problem fixed?

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/28919

**Pull request closed without merging**
