### PR TITLE
lizard-analyzer 1.17.13

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
```
==> /home/linuxbrew/.linuxbrew/Cellar/lizard-analyzer/1.17.12/bin/lizard -l swift /tmp/lizard-analyzer-test-20241031-7292-51t8jw/test.swift

Cannot find the lizard_languages module.
```

**Comment by dtrodrigues** [comment]
The `pygments` requirement (for `erlang.py`) needs to be reported upstream.

**Comment by dtrodrigues** [comment]
https://github.com/terryyin/lizard/pull/399

**Comment by stefanb** [comment]
Homepage is having problems...
>The homepage URL http://www.lizard.ws/ is not reachable (HTTP status code 503)

**Comment by chenrui333** [comment]
upstream has made a new 1.17.13 rel, so that we can get rid of the pypi mapping change

**Comment by chenrui333** [comment]
> Homepage is having problems...
> 
> > The homepage URL http://www.lizard.ws/ is not reachable (HTTP status code 503)

seems working now

image

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
