### PR TITLE
openjdk@11 11.0.8

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Canceled the build to avoid tying up all resources with long builds. Please restart when there's no long builds running

**Comment by SMillerDev** [comment]
Just the hbase test failing, which was a known issue for 14.0 before.

**Comment by SeekingMeaning** [comment]
I can't seem to find the matching pull request for https://github.com/Homebrew/homebrew-core/commit/8c2f4697f0d36dd31ea5c4c1e59191a0acb2629d

`brew test` worked for 1.3.5, but then it appears to have broke when updated 2.2.3, at least that's what happening for me

**Comment by SMillerDev** [comment]
It's probably part of the openjdk 13 -> 14 PR.

**Comment by Bo98** [comment]
The fix should be the same as that of `opentsdb`.

However, I've gone for a generic fix here since it's come up a few times now: Homebrew/brew#8053

**Comment by SMillerDev** [comment]
Since we know the test is faulty, shall I just merge this?

**Comment by SeekingMeaning** [comment]
Yeah, sounds good to me

**Pull request closed without merging**
