### PR TITLE
phpstan 0.11.5 (new formula)

### PR DESCRIPTION
**Pull request by senki**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thank you @senki for your contribution to Homebrew!

**Comment by Zifius** [comment]
@fxcoudert @senki I know it's PR merged, but do we need to depend on PHP like this? `depends_on "php" => :test`

On my system I don't have PHP 7.3 installed and it get's installed on my system. As far as I see phpstan works on PHP 7.1+ https://github.com/phpstan/phpstan/blob/master/composer.json#L8

**Comment by SMillerDev** [comment]
> @fxcoudert @senki I know it's PR merged, but do we need to depend on PHP like this? `depends_on "php" => :test`
> 
> On my system I don't have PHP 7.3 installed and it get's installed. As far as I see phpstan works on PHP 7.1+ https://github.com/phpstan/phpstan/blob/master/composer.json#L8

That means it won't work on sierra unless it depends on PHP like this.

**Comment by Zifius** [comment]
Thanks @SMillerDev!

**Pull request merged**
