### PR TITLE
libtensorflow: copy vendored dependencies

### LINKED ISSUE #82429: formula libtensorflow headers missing third_party/eigen3
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
No logs.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

linking with libtensorflow

### What happened (include all command output)?

/usr/local/Cellar/libtensorflow/2.5.0/include/tensorflow/core/framework/tensor.h:22:10: fatal error: 'third_party/eigen3/unsupported/Eigen/CXX11/Tensor' file not found

### What did you expect to happen?

compile.
By including eigen include path did not solve the problem, cause the header should be in third_party subdirectory.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libtensorflow
g++ -std=c++17 `pkg-config --cflags --libs tensorflow` -c main.cc

main.cc
#include <tensorflow/core/framework/tensor.h>
int main(int argc, char **argv) {
}
```

### LINKED ISSUE #82430: libtensorflow broken on protobuf version
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
No logs.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

linking with libtensorflow

### What happened (include all command output)?

/usr/local/include/tensorflow/core/framework/types.pb.h:17:2: error: This file was generated by an older version of protoc which is

### What did you expect to happen?

compile.
The libtensorflow generated pb header should use the same brew formula protobuf compiler.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libtensorflow
g++ -std=c++17 `pkg-config --cflags --libs tensorflow` -c main.cc

main.cc
#include <tensorflow/core/framework/tensor.h>
int main(int argc, char **argv) {
}
```

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

`libtensorflow` uses Bazel to build, so it has various vendored/versioned dependencies, which are difficult to decouple.

WIP since probably need to add a testcase to check on issue and probably want to look at some other things.

### CODE REVIEW

**Comment by cho-m** [comment]
I will add a revision bump later on when adding testcase.

If we merge #81639, then can also rebase and try Linux, which will probably figuring out shim behavior.

**Comment by bayandin** [comment]
Just a note what an official distribution looks like (from https://www.tensorflow.org/install/lang_c#download):

```
$ find libtensorflow-cpu-darwin-x86_64-2.5.0 -type f
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/core/platform/ctstring.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/core/platform/ctstring_internal.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/c_api_experimental.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/c_api.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/tf_status.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/tf_attrtype.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/tf_datatype.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/tf_file_statistics.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/c_api_macros.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/tf_tensor.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/tensor_interface.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/tf_tstring.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/eager/c_api_experimental.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/eager/dlpack.h
libtensorflow-cpu-darwin-x86_64-2.5.0/include/tensorflow/c/eager/c_api.h
libtensorflow-cpu-darwin-x86_64-2.5.0/LICENSE
libtensorflow-cpu-darwin-x86_64-2.5.0/THIRD_PARTY_TF_C_LICENSES
libtensorflow-cpu-darwin-x86_64-2.5.0/lib/libtensorflow.2.5.0.dylib
libtensorflow-cpu-darwin-x86_64-2.5.0/lib/libtensorflow_framework.2.5.0.dylib
```

which doesn't have any third-party includes:
```
$ grep -rh '#include' libtensorflow-cpu-darwin-x86_64-2.5.0/include | sort -u
#include "tensorflow/c/c_api.h"
#include "tensorflow/c/c_api_macros.h"
#include "tensorflow/c/eager/c_api.h"
#include "tensorflow/c/tf_attrtype.h"
#include "tensorflow/c/tf_datatype.h"
#include "tensorflow/c/tf_status.h"
#include "tensorflow/c/tf_tensor.h"
#include "tensorflow/c/tf_tstring.h"
#include "tensorflow/core/framework/types.pb.h"
#include "tensorflow/core/platform/ctstring.h"
#include "tensorflow/core/platform/ctstring_internal.h"
#include "tensorflow/core/platform/status.h"
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
```

I'm not sure if we should make any extra headers available (like `include/tensorflow/core/framework/tensor.h`) in our distribution.

**Comment by cho-m** [comment]
I guess it depends on what we want to distribute.

If we only want to provide the C library similar to official upstream package, then a more light-weight distribution of just that can be done, but it will be different than our original formula.

Upstream build documentation for C API is just https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md
```
bazel test --config opt //tensorflow/tools/lib_package:libtensorflow_test
bazel build --config opt //tensorflow/tools/lib_package:libtensorflow
```

---

The current build is closer to both Arch and Gentoo's `tensorflow` package.
Everything we build right now:
```
      tensorflow:libtensorflow.so
      tensorflow:install_headers
      tensorflow/tools/benchmark:benchmark_model
      tensorflow/tools/graph_transforms:summarize_graph
      tensorflow/tools/graph_transforms:transform_graph
```

I don't know what users prefer here.

**Comment by cho-m** [comment]
Also, if this is the decision, then please comment on #82429 as we would not be supporting the specific headers in the example.

Also, #82430 is something I don't know how to deal with.
From official package, we have `#include "tensorflow/core/framework/types.pb.h"`
However, this is not part of the official release files, so users will need to find a way to add this themselves.

**Comment by SMillerDev** [comment]
> If we only want to provide the C library similar to official upstream package, then a more light-weight distribution of just that can be done, but it will be different than our original formula.

That seems like a good solution to me, in line with the naming. And then if there is demand people could add a `tensorflow` package that does the full thing.

**Comment by cho-m** [comment]
Closing for now. Will let someone else look into this or revisit in future.

**Pull request closed without merging**
