### PR TITLE
erlang 26.0.1 erlang@25 25.3.2.2 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
- elixir-ls runtime issue with erlang 26, https://github.com/elixir-lsp/elixir-ls/issues/886

**Comment by chenrui333** [comment]
let me wait for 26.0.2 instead

It would allow elixir-ls to run with OTP 26

**Comment by samford** [comment]
@chenrui333 [26.0.2](https://github.com/erlang/otp/releases/tag/OTP-26.0.2) is out now (as of yesterday).

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/135413

**Pull request closed without merging**
