### PR TITLE
glibc glibc@2.13: fix local time zone setting (again)

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

#138622 didn't work as intended, unfortunately. This should do it.

Tested on Ubuntu 20.04, before:

    $ sudo ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime
    $ `brew --prefix python3`/bin/python3 -c "import time; print(time.localtime().tm_zone)"
    UTC
    $ ls -al `brew --prefix`/etc/localtime
    ls: cannot access '/home/linuxbrew/.linuxbrew/etc/localtime': No such file or directory
    $ ls -al `brew --prefix glibc`/etc/localtime
    lrwxrwxrwx 1 linuxbrew linuxbrew 34 Aug  5 17:39 /home/linuxbrew/.linuxbrew/opt/glibc/etc/localtime -> ../../../../../../../etc/localtime

After:

    $ sudo ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime
    $ `brew --prefix python3`/bin/python3 -c "import time; print(time.localtime().tm_zone)"
    +08
    $ ls -al `brew --prefix`/etc/localtime
    lrwxrwxrwx 1 linuxbrew linuxbrew 25 Aug  5 17:29 /home/linuxbrew/.linuxbrew/etc/localtime -> ../../../../etc/localtime

Also, apply the same to `glibc@2.13`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
```
checking for gcc... gcc-11
checking version of gcc-11... 11.4.0, bad
checking for gnumake... gnumake
checking version of gnumake... 4.3, ok
checking for gnumsgfmt... no
checking for gmsgfmt... no
checking for msgfmt... no
checking for makeinfo... no
checking for sed... sed
checking version of sed... v. ?.??, bad
checking for autoconf... no
configure: error: 
*** These critical programs are missing or too old: gcc
*** Check the INSTALL file for required versions.
```

**Comment by ZhongRuoyu** [comment]
Error should be unrelated.

**Comment by iMichka** [comment]
> /usr/bin/ld: /tmp/glibcA2.13-20230805-9979-pciuvo/glibc-2.13/build/csu/crt1.o: relocation R_X86_64_32S against symbol `__libc_csu_fini' can not be used when making a PIE object; recompile with -fPIE

Not so sure .. it did not build a bottle. I don't remember, are we supposed to build glibc@2.13 with gcc-11?

**Comment by ZhongRuoyu** [comment]
> I don't remember, are we supposed to build glibc@2.13 with gcc-11?

I don't think so. (I don't think this is even used by users since we migrated CI to Ubuntu 22.04, actually.) It was last built in #105136, when we still ran CI on Ubuntu 16.04.

**Comment by Bo98** [comment]
`-no-pie` will probably fix it

**Comment by ZhongRuoyu** [comment]
```
  Unwanted system libraries:
    /lib/x86_64-linux-gnu/libnsl.so.1
```

Deprecated in Homebrew/brew#13741.

**Comment by iMichka** [comment]
Maybe try `depends_on "libnsl"`. That version is a newer 2.0.0 version, which might be usable instead.

**Comment by ZhongRuoyu** [comment]
That would pull in the following dependencies, though:

```console
$ brew deps --tree libnsl
libnsl
└── libtirpc
    └── krb5
        └── openssl@3
            └── ca-certificates
```

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
