### PR TITLE
OpenVINO 2024.6.0

### PR DESCRIPTION
**Pull request by artanokhov**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
> Please add tags required for long-build, as we have in previous PR
> #198227

for the future prs, it would be handled with https://github.com/Homebrew/homebrew-core/pull/201765 :)

**Comment by artanokhov** [comment]
> for the future prs, it would be handled with #201765 :)

Thanks!

**Comment by artanokhov** [comment]
```
2024-12-19T15:49:52.7937560Z ##[error]An exception occurred within a child process:
  RuntimeError: No universal binaries found to deuniversalize

2024-12-19T15:49:52.7946660Z ##[endgroup]
2024-12-19T15:49:52.7947160Z ##[group]Truncated install --formula --build-bottle opencv output
2024-12-19T15:49:55.4738880Z ##[error]-- Found OpenBLAS include: /usr/local/opt/openblas/include
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /usr/local/opt/openblas/lib/libopenblas.dylib
-- LAPACK(OpenBLAS): Support is enabled.
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/ant: line 9: /usr/local/opt/ant/bin/ant: No such file or directory
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/ant: line 9: exec: /usr/local/opt/ant/bin/ant: cannot execute: No such file or directory
-- Java version check failed: /usr/bin/java -version returned an error: "The operation couldn’t be completed. Unable to locate a Java Runtime.
```

seems like some infrastructure errors.

**Comment by SMillerDev** [comment]
It doesn't seem to depend on openjdk, so a missing Java makes sense to me

**Comment by cho-m** [comment]
Needs a rebase with increased `opencv` revision number.

**Review by p-linnane — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
