### PR TITLE
monero 0.16.0.3

### PR DESCRIPTION
**Pull request by selsta**
Created with `brew bump-formula-pr`.

~~Edit: Had to manually change the website to fix CI.~~ Still failing.

### CODE REVIEW

**Comment by selsta** [comment]
Anyone know why CI is failing with

> The URL https://www.getmonero.org/ is not reachable

?

Seems to work fine here:

```
selsta@mbpR ~> curl -I https://www.getmonero.org/
HTTP/2 200 
```

**Comment by gromgit** [comment]
Looks like https://github.com/Homebrew/homebrew-core/issues/58854 strikes again:
```
$ /usr/bin/curl -vso /dev/null https://www.getmonero.org/
*   Trying 163.171.208.198...
* TCP_NODELAY set
* Connected to www.getmonero.org (163.171.208.198) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [231 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [98 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [5419 bytes data]
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
} [2 bytes data]
* SSL certificate problem: certificate has expired
* Closing connection 0
```

**Comment by fluffypony** [comment]
@gromgit yeah that's definitely the case; someone needs to fix the CI server :)

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
audit failure, go with the merge.

**Comment by chenrui333** [comment]
Thanks @selsta!

**Pull request closed without merging**
