### PR TITLE
lxi-tools 2.6 (new formula)

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
WARNING: Found pkg-config '/opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config' but it failed when run
Found Pkg-config: NO
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency lua-5.4 found: NO (tried pkgconfig, framework and cmake)
Run-time dependency lua-5.3 found: NO (tried pkgconfig, framework and cmake)
Run-time dependency lua-5.2 found: NO (tried pkgconfig, framework and cmake)
Run-time dependency lua-5.1 found: NO (tried pkgconfig, framework and cmake)
Run-time dependency lua found: NO (tried pkgconfig, framework and cmake)

src/meson.build:53:2: ERROR: Problem encountered: Lua could not be found!
```

**Comment by robcarruthers** [comment]
I'm keen to help in any way possible:
```
Error: The `brew link` step did not complete successfully
  Could not symlink share/glib-2.0/schemas/gschemas.compiled
  Target /opt/homebrew/share/glib-2.0/schemas/gschemas.compiled
  already exists. You may want to remove it:
    rm '/opt/homebrew/share/glib-2.0/schemas/gschemas.compiled'
```
Could you please explain how I can adjust the formula to correct this error?

**Comment by SMillerDev** [comment]
Make sure the formula doesn't install something that another formula also installs

**Comment by robcarruthers** [comment]
I need some help, I can't replicate this error locally.

I've checked all dependency formulas for unnecessary duplication and removed were found.

Given the error occurs post install, is it possible to overwrite the linking in formula ie.
```
# The error suggests rm '/opt/homebrew/share/glib-2.0/schemas/gschemas.compiled'
# I have seen elsewhere similar to:
link_overwrite '/opt/homebrew/share/glib-2.0/schemas/gschemas.compiled'
```

Any pointers or direction would be greatly appreciated.

**Comment by lundmar** [comment]
@robcarruthers I think you can go ahead and just delete it like they do in pulseaudio.rb: https://github.com/Homebrew/homebrew-core/blob/d108cbeff6fef27a3af36705accd0ce944934267/Formula/pulseaudio.rb#L115

It is a system wide gschemas cache file which should not be installed by the homebrew formula when installing stuff in the system. In fact, the homebrew package manager should generate the cache file after the lxi-tools package has installed schema.xml file.

**Comment by lundmar** [comment]
It believe is better to use:
```
rm "#{share}/glib-2.0/schemas/gschemas.compiled"
```
I think then it simply deletes the file generated in the package and so it will not conflict with the system wide cache file when installing the package in the system.

**Comment by robcarruthers** [comment]
I need some help correcting the Commit style error, any advice would be appreciated.

I've rebased (and squashed) against origin/master as it suggests, but the error is still present.

**Comment by lundmar** [comment]
@robcarruthers I believe you need to get rid of your merge commit. Try do the following - it should do the trick:
```
git check master
git pull
git checkout lxi_tools
git rebase master
git push -f
```

**Comment by lundmar** [comment]
Oh, this looks odd. I think you may at some point have merged the wrong way. It may be easier to simply make a new PR and branch and cherry pick your commit to that new PR branch.

**Comment by robcarruthers** [comment]
New PR #138831

**Comment by chenrui333** [comment]
> Oh, this looks odd. I think you may at some point have merged the wrong way. It may be easier to simply make a new PR and branch and cherry pick your commit to that new PR branch.

it is just because the base branch did not get updated properly and caused some issue when doing git rebase

**Pull request closed without merging**
