### PR TITLE
cronolog: deprecate

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

no new release since 2003, skip the livecheck

### CODE REVIEW

**Comment by p-linnane** [comment]
Shouldn't we deprecate this?

**Comment by SMillerDev** [comment]
Yeah, it's using archive.org it should be deprecated. That's still on my list to write a rubocop for.

**Comment by chenrui333** [comment]
make sense, let's deprecate it.

**Review by samford — APPROVED** [review]
I just tried to build this locally and immediately ran into an error, so deprecating makes sense to me, too.

**Pull request merged**
