### PR TITLE
swift 5.6.3

### PR DESCRIPTION
**Pull request by Bo98**
Created by `brew update-swift`. 🚀

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Do you want to roll this into https://github.com/Homebrew/homebrew-core/pull/98809, or wait until after?

`icu4c` is looking as close to ready as it's going to get, barring any substantial changes in CI results on the next rerun.

**Comment by carlocab** [comment]
Or, if it's possible to split the bits that need `icu4c` into a separate formula, it may make landing `icu4c` easier...

**Comment by Bo98** [comment]
Happy to roll this into icu4c. I don't expect any build complications from this update.

**Comment by Bo98** [comment]
> Or, if it's possible to split the bits that need `icu4c` into a separate formula, it may make landing `icu4c` easier...

I'll have a think of this - it'll likely require a bit of experimentation so unlikely to make it in time for icu4c rerun but might be possible for next time.

**Comment by carlocab** [comment]
Incidentally, I'm surprised this does not need `gcc`'s runtime libraries. I guess `clang` still relies on the host's runtime libraries when linking even when it uses `gcc`'s runtime libraries itself.

**Comment by carlocab** [comment]
Already merged

**Pull request closed without merging**
