### PR TITLE
ansible-lint 4.0.1

### PR DESCRIPTION
**Pull request by shigemk2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Let's use the PyPI link instead: 
https://files.pythonhosted.org/packages/9b/c5/64d80bf71860af82d3b08daab6bee546c8dc9c447ac7300d9b0c7cb96eff/ansible-lint-4.0.1.tar.gz

**Comment by fxcoudert** [comment]
Also, resources may need to be updated.

**Comment by shigemk2** [comment]
I fixed links.

**Comment by javian** [comment]
Superseded by #36973

**Pull request closed without merging**
