### PR TITLE
mysql@5.5 5.5.55

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
https://bot.brew.sh/job/Homebrew/job/homebrew-core/job/PR-12469/3/

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:1st_place_medal:

**Comment by DomT4** [comment]
Totally not distracting myself from feeling under the weather with this stupid cold thing by trying to update anything I can get my hands on around Homebrew 😄.

**Comment by ilovezfs** [comment]
:pill:

**Pull request closed without merging**
