### PR TITLE
dbus 1.11.6 (devel)

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

dbus 1.11.6 (devel)

### CODE REVIEW

**Comment by JCount** [comment]
unhappiness related to https://github.com/Homebrew/brew/pull/1493

@ilovezfs it seems that increasing the devel version is making the audit check think:
```* stable version should not decrease```

However, I _**only**_ modified the `devel` block.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by JCount** [comment]
@MikeMcQuaid did you mean to merge this by any chance? ❓ 😇

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks for noticing that @JCount!

**Pull request merged**
