### PR TITLE
wget2 2.0.1 (new formula)

### PR DESCRIPTION
**Pull request by onlynone**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by onlynone** [comment]
It looks like it failed due to:

```
==> brew audit wget2 --online --new-formula
==> FAILED
Full audit wget2 --online --new-formula output
  wget2
    * Dependency 'texinfo' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
  Error: 1 problem in 1 formula detected.
```

But when I run that command locally, it passes. I added the require `texinfo` because it provides the `makeinfo` binary that the build needs to run, and my system doesn't seem to have that binary installed.

```
$ brew config
HOMEBREW_VERSION: 4.0.26-24-g36fc91b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 36fc91b7c1999d42e9e9d4af40b594a4416a93dc
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7fb2ad8c226b4345ba523e596d131e099f5f1777
Core tap last commit: 20 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.QH40Jg0BkZ/org.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

**Comment by chenrui333** [comment]
> ==> brew audit wget2 --online --new-formula
> ==> FAILED
> Full audit wget2 --online --new-formula output
>   wget2
>     * Dependency 'texinfo' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
>   Error: 1 problem in 1 formula detected.

that is actually fine, we have other formulae have similar issues like it.

**Comment by chenrui333** [comment]
squashed the commits into one and rebased to the latest master

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
lgtm

**Comment by fxcoudert** [comment]
The audit error should be gone after https://github.com/Homebrew/brew/pull/15681

**Pull request merged**
