### PR TITLE
cantera 2.4.0 (new formula)

### PR DESCRIPTION
**Pull request by bryanwweber**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is related to https://github.com/Homebrew/homebrew-core/pull/22720 with the update for Cantera 2.4.0 that was mentioned in that PR.

### CODE REVIEW

**Comment by bryanwweber** [comment]
I'm confused about the error messages from @BrewTestBot. Why shouldn't formulas have options? Why shouldn't formulas have optional dependencies? Why shouldn't formulas have `HEAD` or `devel` specs?

Also, in the build, we have a "minimal" Python interface that can only process input files, so doesn't need numpy. This minimal interface is typically recommended if users won't be using the Python interface, but instead one of the other interfaces we offer. How should I handle numpy as a dependency?

**Comment by fxcoudert** [comment]
Homebrew's goal is to maximise the number of users who can download prebuilt binaries, rather that compile from source. We thus do not allow options in new formulas, or optional dependencies. We only allow options, once a formula is in Homebrew core, if there is a strong user need for it (and high usage).

So you need to make a "best compromise" choice of build settings. We tend to prefer feature-full choices, which can satisfy most users, rather than offering a minimalistic (bare bones) choice.

**Comment by bryanwweber** [comment]
@fxcoudert Thanks for the explanation. Cantera offers 3 main interfaces to users:

- Python
- C++
- Matlab

The former two of these are fairly easy to have pre-built binaries, but the last one is not possible because we require a copy of Matlab to be installed on the build machine to be able to build the interface. Making an educated guess, I would say that the Matlab option is actually the most popular option for users who are using Homebrew, thus we need to have this option available.

Thus, we also have the "minimal" Python interface that I referred to before. Input files for Cantera are a subset of the Python syntax and must be processed by a Python interpreter. However, to do so does not require the full Python interface to be installed (although that is also an option), so for users who do not want to build the full interface, we allow them to just build the minimal. I suppose in this case it would be possible to drop the option for the minimal interface, to simplify the set of dependencies. Nonetheless, since we have the optional Python 2 dependency, we still have to check the numpy dependency in an `if` statement to make sure we get the right version.

Finally, on the `HEAD` option - this formula is technically a migration (see #22720), although I marked it as a `new formula` because of the version bump and because it isn't in homebrew-core yet. This option used to be available with the old formula, so I expect some of our users will be looking for it.

**Comment by bryanwweber** [comment]
Also, on the optional Python 2 dependency: I would expect that most of our users are on Python 3, and will be using the Python 3 interface (unless they're using a different interface entirely). Thus, with Python 3 as the default, most users of the Python interface should be using binaries. However, I don't think it makes sense to also have those users install Python 2 when they won't use it at all. Hence, we prefer the optional Python 2 dependency.

**Comment by fxcoudert** [comment]
```
install events in the last 30 days
================================================================================
1 | brewsci/science/cantera                                       | 10 |  55.56%
2 | brewsci/science/cantera --with-matlab=                        |  5 |  27.78%
3 | brewsci/science/cantera --HEAD --with-python3                 |  2 |  11.11%
4 | brewsci/science/cantera --HEAD --with-matlab=                 |  1 |   5.56%
================================================================================
Total                                                             | 18 |    100%
```

**Comment by fxcoudert** [comment]
For a formula with a small number of installs like this one, we cannot support (many) options in Homebrew core: they are not tested, break and add maintenance burden. There are two choices, nonexclusive, and both are actually _good_ choices for users:

- Continue to maintain the formula, with its options, in a tap: it can be `brewsci` or a cantera tap. Taps are easy to use, by design.
- Integrate the formula, without options (I'd say: without matlab, with python3), into Homebrew core. You can continue to have another formula in a tap, for people who want extra options.

**Comment by DomT4** [comment]
Agree 100% with @fxcoudert here.

**Comment by bryanwweber** [comment]
@fxcoudert @DomT4 Thank you for your time to give feedback on the formula. The requirements as you've described here don't really match what we're looking for to use Homebrew to distribute Cantera to our users, so I'm going to close this pull request. Thanks again!

P.S.: I would like to point out that the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook) discusses both optional dependencies and adding optional build steps. If these are really discouraged for new formulas, I would suggest adding large disclaimers to those sections, so that new formula writers don't end up wasting their time and yours.

**Pull request closed without merging**
