### PR TITLE
ponyc 0.11.0

### PR DESCRIPTION
**Pull request by SeanTAllen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by neutric** [comment]
@SeanTAllen Thank you for keeping this formula up to date!

**Comment by SeanTAllen** [comment]
@neutric I take it the process has changed as this was closed without committing? I'd like to update our release docs to indicate when we can know that the homebrew side of things is finished. How would we verify the "release is done"?

**Comment by ilovezfs** [comment]
>@neutric neutric closed this in b65d360 18 minutes ago

**Comment by SeanTAllen** [comment]
@ilovezfs so, how do we know this has been done? should i update our docs to say "when the issue is closed and you've been thanked for keeping the formula up to date"?

**Comment by ilovezfs** [comment]
Well, it's possible you may receive an emoji such as :bowing_man: or :tada: so that might not be accurate in all cases.

**Comment by neutric** [comment]
@ilovezfs Thanks for filling in for me!

@SeanTAllen I am not sure I understand the problem as the process was exactly how it has been the last couple of times. How about referring to the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ponyc.rb) itself in your docs? If it shows the new version, all is good to go.

**Comment by SeanTAllen** [comment]
@neutric We, the Pony core team, are the ones opening the PRs for Homebrew. We don't announce our releases until the Homebrew PR is merged. Our current instructions say to wait for the PR to be merged, however, it appears at some point your process changed and the PR itself it no longer merged. I want to update our instructions accordingly, however, I'm not sure what the best way to know that the PR has been accepted. PR closed itself doesn't seem indicative of PR accepted.

**Comment by neutric** [comment]
@SeanTAllen Thanks for the explanation! I haven't been a maintainer for long, so I can't shed light on why PRs that require new `bottles` to be built are not merged directly but done the way you can see above (that is, with a commit by a maintainer that mirrors your PR + tweaks if needed). A rejection would be missing that commit and would also give a reason for why we did not accept the PR. Does this help?

**Comment by SeanTAllen** [comment]
@neutric yes. so there should be some variation on a "thank you!" or "PR accepted" message even though the PR was closed, yes?

**Comment by neutric** [comment]
That is correct, except for those cases where this message gets forgotten. What is always there is the commit that is closing the PR:

>neutric closed this in [b65d360](https://github.com/Homebrew/homebrew-core/commit/b65d360e732178c4a831739c964b7632519500c7) 18 hours ago

I just had a look at what I think is the [doc](https://github.com/ponylang/ponyc/blob/0a6208c65694bfa0e3ebc33e9a64e3820006f113/RELEASE_PROCESS.md) you are referring to. If you fear there is a risk for your team members to misinterpret what happened in the PR because it has the "closed" icon instead of the "merged" icon despite of the timeline showing a commit right before the closing event that brings the `formula` up to date (which is missing from rejected PRs such as [this](https://github.com/Homebrew/homebrew-core/pull/10818)), how about saying something to the tune of "wait for the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ponyc.rb) to reflect the version bump"?

**Comment by ilovezfs** [comment]
You can also operationalize that by telling them to check the version of
```
$ curl -sL https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/ponyc.rb | grep url
  url "https://github.com/ponylang/ponyc/archive/0.11.0.tar.gz"
```

**Comment by SeanTAllen** [comment]
Thanks @ilovezfs. Updating our documentation. Y'all rock!

**Pull request closed without merging**
