### PR TITLE
opencoarrays 2.1.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@zbeekman I think this may require a little love.

**Comment by zbeekman** [comment]
@ilovezfs The problem is that GCC 8.1 NEEDS TO BE PATCHED. There are coarray triggered ICES no matter what we do in OpenCoarrays. A gfortran contributor committed a broken patch during the freeze period, and no matter what, it must be patched or we must wait for 8.1.1 or 8.2. There is nothing that can be done to fix this on the OpenCoarrays side. Fundamentally GFortran 8.1 is broken without patching for any (serial or parallel) coarray implementation.

**Comment by zbeekman** [comment]
OK, it looks like this is actually due to GCC allowing extensions that clang does not... I'll look into getting this patched and releasing a patch release.

**Comment by zbeekman** [comment]
@dcelisgarza can you please have a look at the build log at https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/25127/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_opencoarrays/ and look into fixing the build problems when compiling with clang? It looks like we're relying on GCC extensions.

CC: @rouson

**Comment by zbeekman** [comment]
Just to clarify, @ilovezfs, I doubt that we'll be able to get OpenCoarrays functioning due to the GCC 8.1 issue I mentioned above, but it should be able to compile and run tests using clang regardless of the GFortran 8.1 f*(& up. So we definitely need to address this either way, but don't hold your breath, unless we're willing to patch GCC 8.1 in Homebrew.

**Comment by ilovezfs** [comment]
Has a fix for gfortran been merged by gcc upstream?

**Comment by zbeekman** [comment]
> Has a fix for gfortran been merged by gcc upstream?

yes, [PR85507](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85507) has been patched upstream in GCC 8.1. The full patch can be found here: https://gcc.gnu.org/ml/fortran/2018-04/msg00120.html but a more minimal version is all that's needed. We apply it when building GCC 8.1 from source with our installer script. The reduced version of the patch is visible at https://github.com/sourceryinstitute/OpenCoarrays/blob/9e6f2cb0e6ad6c385ec2c941ce51aa29740bca2c/prerequisites/build-functions/patches/gcc/8.1.0/partially-revert-rev259385.diff

**Comment by dcelisgarza** [comment]
I had a look at the logs, they're all the so-called variable length arrays. The offending macro is defined in the Fortran standard. Variable length arrays are part of the C99 standard, see [here](https://www.geeksforgeeks.org/variable-length-arrays-in-c-and-c/).

Unless clang starts supporting this feature of C99, the solution is unrolling all the loops and providing literals for the rank. Alternatively it might be necessary to define a C descriptor type for each single rank.
@zbeekman @rouson @ilovezfs

**Comment by zbeekman** [comment]
Ok so perhaps we should see if clang has flags to support that c99 feature.
If not we can disable the iso_fortran_binding stuff if compiling with a c
compiler that doesn’t support it.

**Comment by rouson** [comment]
I suggest we mark this as "won't fix."  My recollection is that AppleClang is based on an ancient version of clang that Apple has no plans to ever update, which presumably is why the error message says the problematic feature "will never be supported."  I think the solution to this is to use a more up-to-date compiler such as a more recent version of clang.  As Daniel notes, the offending code is C99.   I don't think we want to modify our code to support a compiler that is not yet supporting a C standard from nearly 2 decades ago.

**Comment by rouson** [comment]
@zbeekman I just saw your latest comment.  If you want to disable the building of ISO_Fortran_binding based on introspection whenever a compiler doesn't support the required C99 feature, that's a reasonable option too.

**Comment by zbeekman** [comment]
Yes, like it or not old clang will always be relevant on macOS. I’ll
investigate whether there are flags etc to coax clang into building this
and if not add some introspection to disable building the parts that
require C99 stuff. It may only be the tests, in which case we can still
ship iso_fortran_binding.h.

Also, @rouson, this is not our repository so I don’t think we can mark
anything as won’t fix 😉

**Comment by ilovezfs** [comment]
Pretty sure you have some misinformation. Latest Xcode supports even C++14.

**Comment by mistydemeo** [comment]
Taking a look at the error in question:

```
/tmp/opencoarrays-20180531-14782-1hq3nec/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:1189:7: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
```

I think the problem is not variable length arrays, but VLAs inside structs. The use of VLAs as struct members is a GCC extension, not a standard feature of C99, and *that's* what Apple doesn't support. LLVM documents their reasoning here, in their section of [Intentionally unsupported GCC extensions](http://clang.llvm.org/docs/UsersManual.html#intentionally-unsupported-gcc-extensions).

> clang does not support the gcc extension that allows variable-length arrays in structures. This is for a few reasons: one, it is tricky to implement, two, the extension is completely undocumented, and three, the extension appears to be rarely used. Note that clang does support flexible array members (arrays with a zero or unspecified size at the end of a structure).

**Comment by dcelisgarza** [comment]
Well that makes sense actually. This means we'd have to create an explicitly ranked `struct` in `ISO_Fortran_binding.h` for each possible rank. And inside `ISO_Fortran_binding_tests.c`, have a case-switch or if statement for statically declaring the variable.

It shouldn't be hard work, but i bet it's tedious as hell. That would fix it though.

**Comment by fxcoudert** [comment]
@zbeekman @rouson I am closing this pull request. We would welcome a new PR, including the new opencoarrays version and the patch to GCC 8.1.

**Comment by zbeekman** [comment]
@fxcoudert @ilovezfs what is the preferred technique for patching GCC? I.e., where should the patch be hosted? Inline at the end of the formula? At https://github.com/Homebrew/formula-patches/tree/master/gcc? Pulled directly from https://raw.githubusercontent.com/sourceryinstitute/OpenCoarrays/9e6f2cb0e6ad6c385ec2c941ce51aa29740bca2c/prerequisites/build-functions/patches/gcc/8.1.0/partially-revert-rev259385.diff?

**Comment by ilovezfs** [comment]
url from gcc upstream or formula-patches

**Comment by fxcoudert** [comment]
@zbeekman use a `patch do` block with `url "https://raw.githubusercontent.com/Homebrew/formula-patches/71a5df4b/gcc/8.1.0-opencoarrays.patch"`. Add a comment above with a link to the GCC bugzilla issue it fixes.

**Pull request closed without merging**
