### PR TITLE
moc 2.6-alpha3 (devel)

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

**Please merge https://github.com/Homebrew/formula-patches/pull/95 first, then the commit hash c02ec96 needs to be updated to the one in formula-patches' master branch.**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
the build succeeded! Please merge ( @MikeMcQuaid )

**Comment by zmwangx** [comment]
As mentioned in https://github.com/Homebrew/homebrew-core/pull/7421#issuecomment-266127277, build and test would have succeeded even if `clock_gettime` is linked on 10.11 :)

However, since I'm intimately familiar with this patch and have done local testing, it should be fine.

**Comment by dunn** [comment]
👍

**Comment by zmwangx** [comment]
Um, there's https://github.com/Homebrew/formula-patches/pull/95...

**Comment by dunn** [comment]
Ah, crap. Sorry!

**Comment by dunn** [comment]
Fixed the URL in https://github.com/Homebrew/homebrew-core/commit/e349eef566524d1bbd5317dd3e37f9dd500c77a4.

**Pull request closed without merging**
