### PR TITLE
grafana 4.6.1

### PR DESCRIPTION
**Pull request by bergquist**

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
 [791] multi jquery angular angular-bindonce angular-mocks angular-native-dragdrop angular-route angular-sanitize babel-polyfill brace clipboard eventemitter3 file-saver lodash moment mousetrap ngreact react react-dom remarkable tether tether-drop tinycolor2 280 bytes {4} [built]
 [792] ./node_modules/angular-mocks/angular-mocks.js 120 kB {4} [built]
[1050] ./node_modules/css-loader/lib/css-base.js 2.26 kB [built]
[1052] ./node_modules/css-loader?{"importLoaders":2,"url":false,"sourceMap":false,"minimize":true}!./node_modules/postcss-loader/lib?{"sourceMap":false,"config":{"path":"/private/tmp/grafana-20171101-29681-wfiucj/grafana-4.6.1/src/github.com/grafana/grafana/scripts/webpack/postcss.config.js"}}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./public/vendor/css/spectrum.css 9.57 kB [built]
    + 1038 hidden modules

Done.
Error: No such file or directory - public_gen
```

**Comment by ilovezfs** [comment]
@bergquist any news here?

**Comment by mikepurvis** [comment]
I can reproduce the failure on my El Cap machine, though I haven't tried to build it from source outside of homebrew. I don't know enough about node or grunt to really know what the problem is that I'm looking at, but I've filed a bug upstream (see above).

**Comment by mikepurvis** [comment]
@bergquist Please see comment from upstream here: https://github.com/grafana/grafana/issues/9832#issuecomment-343216331

Looks like a small change to the formula is required.

**Comment by bergquist** [comment]
Fixed!

**Comment by ilovezfs** [comment]
Thanks @bergquist! Shipped.

**Pull request closed without merging**
