### PR TITLE
logtalk: add env script and test

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

Drops the caveat from #201666 in favor of env scripts

### CODE REVIEW

**Comment by pmoura** [comment]
Thanks for looking into this. The environment variables still need to be defined for other Logtalk usage contexts, however. For example, the Logtalk for VScode extension requires  entering their values in the settings. Thus, printing the values that should be used is still useful for the user. More significant, the value for the `LOGTALKUSER` environment variable is just a default (that's explained in the Logtalk documentation) and the user may choose a different location. But the script wrappers created by the changes in this pull request would override the user definition. Defining only the `LOGTALKHOME` environment variable in the wrapper scripts would also be problematic as the original scripts would printing a warning if `LOGTALKUSER` environment variable is not defined and would look for the default location. But that warning breaks running Logtalk Jupyter notebooks. In the end, having the user defining both environment variables is less troublesome.

P.S. The alternative methods to install Logtalk, notably the `.deb`,  `.rpm`, `.exe`, or `.pkg` installers, define the **default** value of the `LOGTALKUSER` environment variable by writing to the files in the `/etc` directory that define defaults for common shells. This allows the user to easily override the default.

**Comment by branchvincent** [comment]
Hey Paulo, thanks for your comment

> The environment variables still need to be defined for other Logtalk usage contexts, however. For example, the Logtalk for VScode extension requires entering their values in the settings. Thus, printing the values that should be used is still useful for the user.

Gotcha, the broader goal here is just to set sane defaults for our users and not require any manual configuration/intervention. As an FYI, most users ignore our caveats today so we do try to limit them to an absolute minimum. That said, we can keep the caveat if you want 

> But the script wrappers created by the changes in this pull request would override the user definition.

I think there's a slight misunderstanding, `LOGTALKUSER` is overridable here, i.e. `${LOGTALKUSER:-$HOME/logtalk}` just sets a default value. Since this approach is also used by other installation methods, does it work for you?

**Comment by pmoura** [comment]
Indeed I missed that the generated wrapper scripts only define default values for the environment variables. But can we keep the caveat? Thanks.

**Comment by branchvincent** [comment]
Sure no problem, added them back

**Review by chenrui333 — APPROVED** [review]
lgtm

**Pull request merged**
