### PR TITLE
llvm: include tests support in order to ship llvm-lit

### PR DESCRIPTION
**Pull request by abpostelnicu**
Without this we don't have llvm-lit [support](https://github.com/llvm/llvm-project/blob/main/llvm/CMakeLists.txt#L1020-L1031). 
We will also need this as a first step in order to introduce [LLVM Toolchain Integration Test Suite](https://github.com/opencollab/llvm-toolchain-integration-test-suite/). This test suite has already been introduced in major linux distributions, Debian/Ubuntu.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Homebrew generally doesn't run upstream tests unless there is cryptography involved (openssl etc). Why would we want to make an exception for llvm?

**Comment by abpostelnicu** [comment]
> Homebrew generally doesn't run upstream tests unless there is cryptography involved (openssl etc). Why would we want to make an exception for llvm?

Since this is shipped as an alternative to the default llvm infra on mac, delivered by apple, how would we know the sanity of the compiler. By sanity I understand the status of each object that is generated by llvm and if it's performed any miss-compilations. These kind of tests are very good to have this sorted out.
If this is not desired, then another approach must be implemented, like a multi stage builder of the llvm toolchain, but this is resource intensive and adds cost.

I don't understand the opposition regarding this.

**Comment by carlocab** [comment]
> If this is not desired, then another approach must be implemented, like a multi stage builder of the llvm toolchain, but this is resource intensive and adds cost. A [multi stage](https://searchfox.org/mozilla-central/source/build/build-clang/build-clang.py) build example can be exampled at Mozilla.

The `llvm` formula already does a multi-stage build.

> We will also need this as a first step in order to introduce [LLVM Toolchain Integration Test Suite](https://github.com/opencollab/llvm-toolchain-integration-test-suite/).

Would an end-user ever be interested in running this? If not, then there's not much reason to include this, since we probably won't be running this test suite in CI.

**Comment by carlocab** [comment]
> Homebrew generally doesn't run upstream tests unless there is cryptography involved (openssl etc). Why would we want to make an exception for llvm?

Though, TBF, `LLVM_INCLUDE_TESTS=ON` doesn't mean you run the tests -- it just means you build the tools necessary to run them. You still need to do `make check-*` to actually run the tests after doing this.

So we can actually do this without making any exceptions here. But what I don't see is why we would want to do this.

**Comment by abpostelnicu** [comment]
> Though, TBF, `LLVM_INCLUDE_TESTS=ON` doesn't mean you run the tests -- it just means you build the tools necessary to run them. You still need to do `make check-*` to actually run the tests after doing this.

Yes, this change only builds the llvm-lit library.

**Comment by carlocab** [comment]
What's the use-case for having `llvm-lit` installed when you have an installed toolchain? You don't have the source tree, so you wouldn't be able to run the tests from there.

Also, as you've pointed out, the alternative is to do a multi-stage build, which the formula already does.

**Comment by abpostelnicu** [comment]
> What's the use-case for having `llvm-lit` installed when you have an installed toolchain? You don't have the source tree, so you wouldn't be able to run the tests from there.

Please see [this](https://llvm.org/docs/CommandGuide/lit.html).

Doing a couple of passes it's not enough by far, see [this](https://reviews.llvm.org/D105207/). Doing as much testing as we can it's a very good thing. Please bring some arguments why we wouldn't ship a complete llvm toolchain?

**Comment by SMillerDev** [comment]
> Doing as much testing as we can it's a very good thing. Please bring some arguments why we wouldn't ship a complete llvm toolchain?

Because upstream should test their code on macOS, not Homebrew. We only want to test if we installed it in the right place without missing dependencies.

**Comment by abpostelnicu** [comment]
> > Doing as much testing as we can it's a very good thing. Please bring some arguments why we wouldn't ship a complete llvm toolchain?
> 
> Because upstream should test their code on macOS, not Homebrew. We only want to test if we installed it in the right place without missing dependencies.

I'm sorry, but I don't understand your reasoning here. Why the back-clash on having this in LLVM formula? All of the major linux distributions do this for their packages, see [Debian](https://wiki.debian.org/ContinuousIntegration/autopkgtest) for example.

**Comment by SMillerDev** [comment]
> All of the major linux distributions do this for their packages, see Debian for example.

We're not really a linux distribution, our rules for packaging are different. Let's put it this way: if our rules define that we will never be running `make check` for LLVM, how would enabling this be benefitial for at least 80% of our (LLVM) users?

**Comment by abpostelnicu** [comment]
> > All of the major linux distributions do this for their packages, see Debian for example.
> 
> We're not really a linux distribution, our rules for packaging are different. Let's put it this way: if our rules define that we will never be running `make check` for LLVM, how would enabling this be benefitial for at least 80% of our (LLVM) users?

Ok, let's say we will not run the sanity tests, but even though we are shipping an incomplete llvm package, please see the first paragraph of this comment https://github.com/Homebrew/homebrew-core/pull/82479#issuecomment-891865265

**Comment by alebcay** [comment]
> Please see this.

> please see the first paragraph of #82479 (comment)

I see - so `lit` appears to be "a portable tool for executing LLVM and Clang style test suites". So in other words - it's for running user-specified tests on _their own code_. It is _not_ used for testing LLVM/Clang itself.

Is this understanding correct?

**Comment by carlocab** [comment]
> > What's the use-case for having `llvm-lit` installed when you have an installed toolchain? You don't have the source tree, so you wouldn't be able to run the tests from there.
> 
> Please see [this](https://llvm.org/docs/CommandGuide/lit.html).

I've already seen this page and it doesn't really answer my question. Can you give an example of a non-LLVM project that uses `llvm-lit` to run their tests? What's a typical example where an end-user would want to make use of the `llvm-lit` tool?

> Doing a couple of passes it's not enough by far, see [this](https://reviews.llvm.org/D105207/).

We do the same number of passes as in the [example](https://searchfox.org/mozilla-central/source/build/build-clang/build-clang.py) you linked earlier.

> Doing as much testing as we can it's a very good thing.

We're already doing as much testing as we can.

> Please bring some arguments why we wouldn't ship a complete llvm toolchain?

Because we don't want to ship parts that aren't useful. Note that this was also [your argument](https://github.com/Homebrew/homebrew-core/pull/75204#issuecomment-821839555) when you suggested we shouldn't ship LLDB.

> I see - so `lit` appears to be "a portable tool for executing LLVM and Clang style test suites". So in other words - it's for running user-specified tests on _their own code_. It is _not_ used for testing LLVM/Clang itself.
> 
> Is this understanding correct?

Not quite -- it's both. I've only ever seen it used to test LLVM/Clang itself (or derivative projects), though.

**Comment by carlocab** [comment]
A few additional comments on this:

A user can already do `pip3 install lit` if what they need is to use the `lit` executable. Indeed, you can do this and then run the [test suite](https://github.com/opencollab/llvm-toolchain-integration-test-suite/) referenced above. To demonstrate this, I forked the repo and ran the test suite against Homebrew LLVM. Here's the latest [test run](https://github.com/carlocab/llvm-toolchain-integration-test-suite/actions/runs/1097539858). All but one test passes on the Linux, and there are a number of failures on macOS. Most of the macOS failures are expected: 

1. The commands that `lit` runs lack some compiler flags or pass inappropriate ones. Many of the commands that `lit` runs assume that LLVM is in the linker's default search path. I've also seen it try to use `-static-libstdc++`.
2. Many of the tests pass `-fuse=lld`. `lld` doesn't work out-of-the-box on macOS.
3. There's also a failure from testing the gold linker which just isn't a thing.

A number of the tests in the test suite are already done in the formula's `test` block. For example, the [suite's OpenMP test](https://github.com/opencollab/llvm-toolchain-integration-test-suite/blob/main/tests/basic_openmp.c) is functionally equivalent to the [formula's OpenMP test](https://github.com/Homebrew/homebrew-core/blob/aa2d1427e14f422f17f9445c36eb42b9e30880c3/Formula/llvm.rb#L328-L355). There are some tests that the suite does that the formula doesn't do (and vice-versa), but any useful tests from the suite can be easily added to the formula's `test` block.

The only additional benefits of using the test suite are that the tests can be run in parallel and that we wouldn't need to duplicate code that someone else has already written.

In all, I don't find the change in this PR to be hugely compelling, though I'm willing to reconsider this if/when the test suite is modified to work properly on macOS/with Homebrew LLVM. Until then, we can add any useful missing tests to the formula's `test` block.

**Comment by carlocab** [comment]
I opened #83017 to allow us to install `lit` without setting `LLVM_INCLUDE_TESTS` to `ON`.

**Comment by carlocab** [comment]
Getting lit to work while building it out of the LLVM source tree required a few ugly hacks, and even then there were some weird issues with it. It's likely because `llvm` is keg-only.

That said, you can `pip install lit`, and it's a command-line tool, so there's no reason it can't be a formula. See #84391.

**Pull request closed without merging**
