### PR TITLE
code-server 3.12.0

### PR DESCRIPTION
**Pull request by jsjoeio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jsjoeio** [comment]
```ruby
internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/linuxbrew/.linuxbrew/Cellar/code-server/3.12.0/libexec/node_modules/argon2/lib/binding/napi-v3/argon2.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/linuxbrew/.linuxbrew/Cellar/code-server/3.12.0/libexec/node_modules/argon2/argon2.js:9:56)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

Hmm `argon2` was in the previous release of code-server. I wonder if we need to use the prebuilt binaries for `node-argon2`?

https://github.com/ranisalt/node-argon2#before-installing

**Comment by chenrui333** [comment]
> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

added glibc dependency

**Comment by carlocab** [comment]
>  I wonder if we need to use the prebuilt binaries for node-argon2?

The opposite, actually, I think. This looks like it's currently using a pre-built binary, but the pre-built binary was built on a machine with a newer Glibc than our minimum. Fixing this probably requires building from source.

**Review by carlocab — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by jsjoeio** [comment]
> The opposite, actually, I think. This looks like it's currently using a pre-built binary, but the pre-built binary was built on a machine with a newer Glibc than our minimum -- hence the errors. Fixing this probably requires building from source.

Ahhh! Got it. Thanks for the quick support + help y'all! 🙌

**Pull request closed without merging**
