### PR TITLE
awscli 1.10.38

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- minor style updates taken from `poet -f` output.
- have test match against the version

### CODE REVIEW

**Comment by DomT4** [comment]
Seems fine 👍. Maybe @tdsmith knows more about the change from `https://pypi.python.org` to `https://files.pythonhosted.org`... Is that part of the previously discussed URL changes or are we hitting a mirroring system or such?

**Comment by tdsmith** [comment]
@dstufft says these are good and stable URLs so I'm happy; thanks for checking

**Comment by DomT4** [comment]
Thanks Tim! 🙇

**Comment by nijikon** [comment]
Always update botocore as well.

**Comment by nijikon** [comment]
#2034

**Comment by ilovezfs** [comment]
@nijikon As you can see I *did* update botocore (note that the URL changed). The change you just made is for a release of botocore that occurred after I opened this PR.

**Comment by nijikon** [comment]
Sure, I just wanted to make sure that all are aware that the best approach is to update both awscli and botocore as they are dependent on each other. No worries :)

**Comment by DomT4** [comment]
@nijikon Maybe this is worth noting in the formula if it needs an update _every_ time.

**Comment by nijikon** [comment]
@DomT4 "Make sure that you also bump botocore"?

**Pull request closed without merging**
