### PR TITLE
sfml 2.5.1

### PR DESCRIPTION
**Pull request by pedrovanzella**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
`brew style sfml` fails. 
Also `csfml` and `tgui` need to have their revision bumped, one commit each. Look at #34063 for example.

**Comment by pedrovanzella** [comment]
`tgui` is up-to-date. `csfml`'s latest version is `2.5`, and I verified it compiles fine against `sfml` `2.5.1`.

**Comment by SMillerDev** [comment]
It seems sfml doesn't compile properly on sierra. Could you look at what the issue could be there @pedrovanzella ?

**Pull request closed without merging**
