### PR TITLE
ttyd 1.7.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Dependency tree conflict to allow for a switch to `openssl@3`.

**Comment by chenrui333** [comment]
```
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libwebsockets.a(unix-sockets.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
  /usr/bin/ld: failed to set dynamic section sizes: bad value
  collect2: error: ld returned 1 exit status
  gmake[2]: *** [CMakeFiles/ttyd.dir/build.make:171: ttyd] Error 1
  gmake[2]: Leaving directory '/tmp/ttyd-20221019-12430-1rwa9xw/ttyd-1.7.2/build'
  gmake[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/ttyd.dir/all] Error 2
  gmake[1]: Leaving directory '/tmp/ttyd-20221019-12430-1rwa9xw/ttyd-1.7.2/build'
  gmake: *** [Makefile:139: all] Error 2
```

**Comment by chenrui333** [comment]
libwebsockets needs a rebuild for linux

**Comment by maaslalani** [comment]
> libwebsockets needs a rebuild for linux

@chenrui333, Is there any way I can help rebuild this so that this PR can be merged?

**Pull request closed without merging**
