### PR TITLE
tkey-ssh-agent: update artifact url and checksum

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

found in #162713

### CODE REVIEW

**Comment by stefanb** [comment]
This should also change dependancy from "go" to "go@1.21" once
* https://github.com/Homebrew/homebrew-core/pull/162713
 
is merged

**Comment by dehanj** [comment]
> This should also change dependancy from "go" to "go@1.21" once
> 
>     * [go@1.21 1.21.7 (new formula) #162713](https://github.com/Homebrew/homebrew-core/pull/162713)
> 
> 
> is merged

If I'm not mistaken, I think it should be built with `go@1.20`.  It relates to this [issue](https://github.com/tillitis/tkey-ssh-agent/issues/103), which is fixed upstreams but not yet released. 
So to close this PR that is the easiest fix. We do intend to make the release fixing the build issue with go above 1.20, but that will happen in about 2 weeks from now.

**Comment by dehanj** [comment]
@chenrui333, can you update the build dependency from "go" to "go@1.20"?  Would appreciate it.
Should fix the build issue so this PR can go through.

**Comment by bevanjkay** [comment]
@dehanj we are waiting for confirmation from upstream that the changed checksum is legitimate.

**Comment by dehanj** [comment]
@bevanjkay I think it is legitimate. See my comment [here](https://github.com/tillitis/tkey-ssh-agent/issues/108#issuecomment-1949446871).

**Comment by bevanjkay** [comment]
Unfortunately what we "think" is generally not enough in these instances. We need official confirmation from upstream

**Comment by chenrui333** [comment]
> @chenrui333, can you update the build dependency from "go" to "go@1.20"? Would appreciate it.

we [actually deprecate go@1.20 recently](https://github.com/Homebrew/homebrew-core/pull/162668), meaning we cannot use it as build dependencies anymore

**Comment by dehanj** [comment]
> we [actually deprecated go@1.20 recently](https://github.com/Homebrew/homebrew-core/pull/162668), meaning we cannot use it as build dependencies anymore

Ah, I see. Then this will have to wait until we release in about 2 weeks. It would obviously produce a new checksum for that release, but I will try to dig a bit more until then to see if we can get a better explanation for this change. The source in the tarball has not changed at least.

**Comment by chenrui333** [comment]
@dehanj is the upstream maintainer and confirm the latest checksum, my idea is maybe we can upload the tarball into the github asset rather than use github's source archive tarball for the sake of the tarball stability.

**Comment by dehanj** [comment]
If uploading our own release tarball is the recommendation from Homebrew, that is a solution. Is that the general recommendation from Homebrew? I guess it has to be seen Github does not offer checksum stability on the tarballs (even if they should seldomly change).

Unfortunately, we still have the issue that our latest released only supports Go 1.20 and below, and it has been deprecated. The fix is merged upstream, but we have some other changes the we absolutely need to include in our next release, it is our priority, but It is not finished yet. Sorry for the wait.

**Comment by ZhongRuoyu** [comment]
In this case I think the tarball checksum *could* be a result of the repository rename because the repository name is encoded in the tarball:

```console
$ curl -Ls https://github.com/tillitis/tillitis-key1-apps/archive/refs/tags/v0.0.6.tar.gz | tar zt | head
tkey-ssh-agent-0.0.6/
tkey-ssh-agent-0.0.6/.clang-format
tkey-ssh-agent-0.0.6/.editorconfig
tkey-ssh-agent-0.0.6/.github/
tkey-ssh-agent-0.0.6/.github/workflows/
tkey-ssh-agent-0.0.6/.github/workflows/ci.yaml
tkey-ssh-agent-0.0.6/.gitignore
tkey-ssh-agent-0.0.6/.golangci.yml
tkey-ssh-agent-0.0.6/LICENSE
tkey-ssh-agent-0.0.6/Makefile
```

> I guess it has to be seen Github does not offer checksum stability on the tarballs (even if they should seldomly change).

There was [an incident last year](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/) changing the checksum of all Git archives. The change was reverted shortly after, but the recommendation from GitHub is that release assets are preferred over Git archives if checksum stability is a requirement.

However, most of the checksum mismatches we see are a result of re-tagging. So, if you don't [go against Git's recommendation](https://git-scm.com/docs/git-tag#_on_re_tagging) and re-tag your releases (or frequently rename the repository which I don't think you will :) ), then it should be fine.

**Review by ZhongRuoyu — COMMENTED** [review]
I don't think this is ready to merge. It fails to build on macOS.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by dehanj** [comment]
> In this case I think the tarball checksum _could_ be a result of the repository rename because the repository name is encoded in the tarball:

Thanks, the renaming seems to be the root cause. 

> However, most of the checksum mismatches we see are a result of re-tagging. So, if you don't [go against Git's recommendation](https://git-scm.com/docs/git-tag#_on_re_tagging) and re-tag your releases (or frequently rename the repository which I don't think you will :) ), then it should be fine.

Makes sense! Then I think it should be fine.

**Pull request merged**
