### PR TITLE
sphinx-doc 2.3.0

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by dawidd6** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Testing interrupted because it was taking forever to test reverse build-only dependencies. Merging.

**Pull request closed without merging**
