### PR TITLE
kde frameworks 5.82.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Build failure on `extra-cmake-modules`.
```make
Extension error:
Could not import extension ecm (exception: cannot import name 'htmlescape' from 'sphinx.util.pycompat' (/usr/local/Cellar/sphinx-doc/4.0.1/libexec/lib/python3.9/site-packages/sphinx/util/pycompat.py))
make[2]: *** [docs/doc_format_html] Error 2
make[1]: *** [docs/CMakeFiles/documentation.dir/all] Error 2
```

From https://www.sphinx-doc.org/en/master/extdev/deprecated.html
- `sphinx.util.pycompat.htmlescape` was removed in v4.0. Homebrew `sphinx-doc` is v4.0.1.

**Comment by yurikoles** [comment]
Upstream [ticket](https://bugs.kde.org/show_bug.cgi?id=436818)

**Comment by cho-m** [comment]
@yurikoles Thanks for pointing that out.
Looks like PR is ready: https://invent.kde.org/frameworks/extra-cmake-modules/-/merge_requests/121/diffs

**Comment by nandahkrishna** [comment]
Superseded by #77471.

**Pull request closed without merging**
