### PR TITLE
fuseki 3.12.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
The [upstream download page](https://jena.apache.org/download/) doesn't mention `3.12.0` yet.

**Comment by nick-manasys** [comment]
Can you please have a look again. I just tried and 3.11 is not there any more only 3.12
https://www-us.apache.org/dist/jena/binaries/

I got as far as creating pull request and was referred here
New 3.12 sha for me is
sha256 "60ae78b13f60b4edc20b2699d7366003e0b7f6e8b5409d731794dcb7491e57c8"

**Comment by igas** [comment]
@BrewTestBot test this please

**Pull request merged**
