### PR TITLE
epinio 1.7.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not the latest release yet: https://github.com/epinio/epinio/releases

**Comment by chenrui333** [comment]
- relates to https://github.com/epinio/epinio/issues/2089

**Comment by chenrui333** [comment]
#124128

**Comment by chenrui333** [comment]
Looks like upstream has automated the release process, let's just use their PR.

**Pull request closed without merging**
