### PR TITLE
emscripten: use upstream recommended llvm revision

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
See https://github.com/Homebrew/homebrew-core/issues/63176, https://github.com/emscripten-ports/SDL2_mixer/issues/2, https://github.com/emscripten-core/emscripten/issues/12551. This should hopefully fix all of them.

### CODE REVIEW

**Comment by alebcay** [comment]
Anyone have any ideas on this High Sierra failure during the `llvm` build?
```
[ 60%] Copying CXX header support/ibm/support.h
In file included from /tmp/emscripten--llvm-20201021-71374-z6k23r/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_mac.cpp:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/mach/mach.h:65:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/mach/std_types.h:66:
/tmp/emscripten--llvm-20201021-71374-z6k23r/llvm/build/./bin/../include/c++/v1/stdint.h:106:10: fatal error: '__config' file not found
#include <__config>
         ^~~~~~~~~~
```

**Comment by alebcay** [comment]
Current failure on Big Sur:
```
[ 62%] Copying CXX header stdexcept
In file included from /tmp/emscripten--llvm-20201115-24307-rmveyg/compiler-rt/lib/lsan/lsan_malloc_mac.cpp:57:
In file included from /tmp/emscripten--llvm-20201115-24307-rmveyg/compiler-rt/lib/lsan/../sanitizer_common/sanitizer_malloc_mac.inc:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:69:
/tmp/emscripten--llvm-20201115-24307-rmveyg/llvm/build/./bin/../include/c++/v1/stdbool.h:22:10: fatal error: '__config' file not found
#include <__config>
         ^~~~~~~~~~
[ 62%] Copying CXX header stdint.h
[ 62%] Copying CXX header stdio.h
1 error generated.
make[5]: *** [compiler-rt/lib/lsan/CMakeFiles/clang_rt.lsan_osx_dynamic.dir/lsan_malloc_mac.cpp.o] Error 1
```

**Comment by carlocab** [comment]
Quick question, in case you would know (no worries if not, I'll just have a look myself):

Does emscripten really need such a fully-featured installation of llvm to work?

https://github.com/Homebrew/homebrew-core/blob/168f18b0694692ed85fc0413c0313a8632016f6d/Formula/emscripten.rb#L53-L69

https://github.com/Homebrew/homebrew-core/blob/168f18b0694692ed85fc0413c0313a8632016f6d/Formula/emscripten.rb#L100

The [build docs](https://emscripten.org/docs/building_from_source/index.html#building-llvm) only recommend building the following targets
```
-DLLVM_ENABLE_PROJECTS='lld;clang'
-DLLVM_TARGETS_TO_BUILD="host;WebAssembly"
```

Their [docs on packaging](https://github.com/emscripten-core/emscripten/blob/master/docs/packaging.md) require the following binaries:
* clang
* clang++ (note: this is a symlink to clang)
* wasm-ld
* llc
* llvm-nm
* llvm-ar
* llvm-as
* llvm-dis
* llvm-dwarfdump

I don't think you need `clang-tools-extra`, `lldb`, or `polly` for these?

As it is the emscripten package takes up 2GB of space, and I imagine a lot of that is unused. Building more targets than you need to also increases the probability of build failures. (Not sure if that's the culprit here, but could be worth a look.)

**Comment by alebcay** [comment]
I think you raise a fair point. Seeing as the error encountered is while compiling the `compiler-rt` runtime, I don't think this is necessarily going to fix things, but it should definitely reduce the package size. I copied over a lot of the LLVM cruft/boilerplate over from the main LLVM formula because I was just nervous about touching stuff and breaking something.

**Comment by carlocab** [comment]
No worries. I know how difficult it can be trying to get llvm to build (I must've done so nearly a dozen times in the past week trying to implement an improvement to the llvm formula).

Do you want more input on other things I think you can cut out? I understand if you'd rather not -- I'll just pursue cutting down the installation size in another PR when this one is merged. But I do think there's still some low-hanging fruit.

Also, are you sure any of those runtimes are even necessary? My impression was they're not, and it seems dropping `compiler-rt` would help the tests.

**Comment by alebcay** [comment]
Well, I'll be darned. Looks like everything's working now. This one has been sitting around for a while, so I'd kindly ask that we address further improvements in a new PR.

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
Sure, no problem. Leave it with me.

**Pull request closed without merging**
