### PR TITLE
vifm 0.10

### PR DESCRIPTION
**Pull request by mschloesser**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
`make check` fails on Sierra.

**Comment by mschloesser** [comment]
Should I remove Sierra (temporarily) or is someone able to fix the issue? I don't have a Sierra machine available.

**Comment by mschloesser** [comment]
@equal-l2 Thanks a lot for the hint!

**Comment by mschloesser** [comment]
Ok, I give up....

**Comment by dmlemos** [comment]
I was about to submit a PR for this formula. Was there a reason why wasn't this merged?

Would be good to have some support to push this as I'd like to use the new version from brew.

**Comment by equal-l2** [comment]
I don't remember the detail since there's no build log anymore, but I guess the new version hasn't built or failed on the test.

**Comment by dmlemos** [comment]
I understand the bumped version is not compatible with high sierra, so the `depends_on` was specified. Is it is not enough?

Any help would be much appreciated as I am using Mojave and builds just fine. I assume the author had the same problem due to lack of environment to test.

**Comment by igas** [comment]
@dmlemos I also made an attempt before https://github.com/Homebrew/homebrew-core/pull/34161 you can check the logs there.

**Pull request closed without merging**
