### PR TITLE
volta 0.9.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Still a pre-release:  https://github.com/Homebrew/homebrew-core/pull/60168#issuecomment-687648446 https://github.com/volta-cli/volta/releases/tag/v0.9.0

**Comment by chenrui333** [comment]
checking with upstream.

**Comment by charlespierce** [comment]
Apologies! I intended to not mark version 0.9.0 as a pre-release, but I forgot to update the CI script that creates the release. I edited the release to reflect that.

**Comment by chenrui333** [comment]
@charlespierce no need to apologize, thanks for confirming this is the latest release! 🚀

**Review by dtrodrigues — APPROVED** [review]

**Pull request closed without merging**
