### PR TITLE
anjuta: depends on gnutls

### PR DESCRIPTION
**Pull request by bw-yuhogg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Discovered [here](https://github.com/Homebrew/homebrew-core/pull/1292#issuecomment-220362878).

### CODE REVIEW

**Comment by DomT4** [comment]
Can you bump the formula `revision` here as well? Thanks.

**Comment by rwhogg** [comment]
> Can you bump the formula revision here as well? Thanks.

Specifically the *formula* revision, as opposed to the *bottle* revision?

**Comment by DomT4** [comment]
Yeah, bottle revisions aren't intended to be touched by humans. We're plotting a change of terminology [at some point](https://github.com/Homebrew/brew/issues/38).

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/6986c80248d2801ef6a4547649431222cab5e549. Thank you for your contribution to Homebrew @rwhogg; we appreciate it! :smiley_cat:

**Pull request closed without merging**
