### PR TITLE
zile: revert version bump back to stable

### LINKED ISSUE #67379: Zile formula is shipping a beta version but marking it as stable
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

https://formulae.brew.sh/formula/zile

Lists the current version as "stable", and "2.6.0.90". But 2.6.0.90 is a beta release. See:

https://mail.gnu.org/archive/html/bug-zile/2020-12/msg00000.html

It is clearly marked as a beta.

Please downgrade to 2.4.15.

I am the upstream maintainer of Zile. Thanks for packaging Zile!

### PR DESCRIPTION
**Pull request by carlocab**
Fixes https://github.com/Homebrew/homebrew-core/issues/67379.

This reverts commit dd80dd1fc8549b955191f1db8677d7483aacbcb3.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by Rylan12** [comment]
Maybe add a comment saying to check the `NEWS` file to make sure the release is stable? We have a few formulae with similar messages (although those tend to point to a website rather that a file in the tarball)

**Comment by carlocab** [comment]
Good idea; done. Is there a way to exempt this from `livecheck` and `bump-formula-pr`? Will removing the `livecheck` block be enough for the former?

**Comment by Rylan12** [comment]
I think the closest we have is this which is used by 23 formulae (e.g.  [`term`](https://github.com/Homebrew/homebrew-core/blob/69d43acedd0fa4d1808fa90c0de666e1ff8c0841/Formula/term.rb#L8-L10)):

```ruby
livecheck do
  skip "reason"
end
```

Probably a good idea to do that here to avoid `livecheck` being used to automate PRs.

**Comment by carlocab** [comment]
Done.

>`livecheck` being used to automate PRs

Guilt as charged.

**Comment by Rylan12** [comment]
> > `livecheck` being used to automate PRs
> 
> Guilty as charged.

Nothing wrong with that... it's part of what `livecheck` is for after all.

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Thanks as always, @carlocab

**Pull request closed without merging**
