### PR TITLE
bundletool new homepage

### PR DESCRIPTION
**Pull request by silverskyvicto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I fixed `bundletool` homepage url.
### why the change is needed?

Because the website already exists.

### CODE REVIEW

**Comment by SMillerDev** [comment]
That page seems more focused on the technology that bundle-tool is supposed to support though. Not on bundle-tool itself.

**Comment by silverskyvicto** [comment]
Is the link below correct?

- [bundletool](https://developer.android.com/studio/command-line/bundletool)

**Comment by SMillerDev** [comment]
That would be better, but isn't that information available on the github page as well?

**Comment by silverskyvicto** [comment]
Thank you for comment.

In the case of the Github repository, I thought it might contain information that is not Stable and is still under development (for example, features that will be available in the next release).
For this reason, I set the URL of the official documentation.

**Comment by SMillerDev** [comment]
It's still the best place to find information about the tool though, seeing how both the links you tried are in the README. Unless this is a common problem with this repo I'd rather keep it pointing to the location that has all information.

**Pull request closed without merging**
