### PR TITLE
cake 0.38.0

### PR DESCRIPTION
**Pull request by gep13**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> FAILED
Error: 1 problem in 1 formula detected
cake:
  * v0.38.0 is a GitHub prerelease
```

**Comment by gep13** [comment]
@chenrui333 Thanks for looking at this.  Is this something that we should be aware of for future releases?

**Comment by chenrui333** [comment]
that is why I created the prerelease tag, we can circle back on this later. Or creating another issue tracker in the upstream repo?

**Comment by gep13** [comment]
>@chenrui333 said...
Or creating another issue tracker in the upstream repo?

I am not sure I follow what you mean by this, can you elaborate?

**Comment by gep13** [comment]
All Cake releases have been pre-releases, and the last PR worked without any issues:

https://github.com/Homebrew/homebrew-core/pull/49688

Has something changed since then?

**Comment by chenrui333** [comment]
> All Cake releases have been pre-releases, and the last PR worked without any issues:
> 
> #49688
> 
> Has something changed since then?

The audit process (now it does track the stable/latest release) got changed a little bit, but if that is what is like, I think we can accept this.

Any documentation reference for the prerelease tag usage?

**Comment by gep13** [comment]
>@chenrui333 said...
Any documentation reference for the prerelease tag usage?

We have always used the prerelease flag on our releases.  Once we reach 1.0.0, we intend on removing it.

**Comment by chenrui333** [comment]
> > @chenrui333 said...
> > Any documentation reference for the prerelease tag usage?
> 
> We have always used the prerelease flag on our releases. Once we reach 1.0.0, we intend on removing it.

ok, sounds cool!

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
