### PR TITLE
glow 1.5.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test out fine on linux action runner

```
runner@fv-az622-155:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ brew test glow
==> Testing glow
==> /home/linuxbrew/.linuxbrew/Cellar/glow/1.5.0/bin/glow test.md
```

**Comment by chenrui333** [comment]
@Homebrew/linux I could not actually reproduce the error on the linux runner. Can someone also take a look?

**Comment by dawidd6** [comment]
Yep, works fine locally on my Ubuntu 22.04 machine.

**Comment by chenrui333** [comment]
super weird.

**Comment by iMichka** [comment]
I re-ran it again and no change. Maybe try on the self-hosted runner?

**Comment by chenrui333** [comment]
That might be the only option. I actually directly run the test inside a github hosted runner and the test passed.

**Comment by chenrui333** [comment]
rerun with a self-hosted runner now

**Comment by chenrui333** [comment]
still the same issue.

**Comment by chenrui333** [comment]
Also raise an upstream issue for help.

**Comment by chenrui333** [comment]
running into the similar issue with #121789

**Comment by chenrui333** [comment]
For now, I am just gonna update test and ship the change (glow works fine in the linux runner, but just not on CI)

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
