### PR TITLE
corectl: fix build due to OCaml shift

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Currently, `brew install --build-from-source hyperkit` fails. This fixes the build.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why do we have a build-only X11 dependency? That's weird…

**Comment by alebcay** [comment]
I think that may be leftover since I copied some stuff over from `hyperkit`. Will see if build succeeds without it and omit if possible.

The addition of the `:x11` is because there are certain features in the OCaml compiler that required it (which we don't use). Once upon a time, there was a way to disable those components so `:x11` was not required, but those switches don't seem to be working anymore.

**Comment by alebcay** [comment]
@fxcoudert, this is what happens when building without `depends_on :x11 => :build`:

```
[ERROR] The compilation of ocaml-base-compiler failed at "/usr/local/Homebrew/Library/Homebrew/shims/mac/super/make world".

#=== ERROR while compiling ocaml-base-compiler.4.05.0 =========================#
# context              2.0.4 | macos/x86_64 |  | https://opam.ocaml.org#e985de4f
# path                 /private/tmp/corectl-20190620-82719-1ne9n2a/corectl-0.7.18/src/github.com/TheNewNormal/corectl/opamroot/ocaml-base-compiler.4.05.0/.opam-switch/build/ocaml-base-compiler.4.05.0
# command              /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make world
# exit-code            2
# env-file             /private/tmp/corectl-20190620-82719-1ne9n2a/corectl-0.7.18/src/github.com/TheNewNormal/corectl/opamroot/log/ocaml-base-compiler-82821-a71bb4.env
# output-file          /private/tmp/corectl-20190620-82719-1ne9n2a/corectl-0.7.18/src/github.com/TheNewNormal/corectl/opamroot/log/ocaml-base-compiler-82821-a71bb4.out
### output ###
# [...]
# ../../boot/ocamlrun ../../ocamlc -nostdlib -I ../../stdlib -I ../../otherlibs/unix -a -o stdlib.cma ../../stdlib/camlinternalFormatBasics.cmo pervasives.cmo ../../stdlib/array.cmo ../../stdlib/list.cmo ../../stdlib/char.cmo ../../stdlib/bytes.cmo ../../stdlib/string.cmo ../../stdlib/sys.cmo ../../stdlib/sort.cmo marshal.cmo ../../stdlib/obj.cmo ../../stdlib/int32.cmo ../../stdlib/int64.cmo ..[...]
# ../../boot/ocamlrun ../../tools/ocamlmklib -ocamlc '../../boot/ocamlrun ../../ocamlc -nostdlib -I ../../stdlib -I ../../otherlibs/unix' -o unix -linkall unix.cmo ../unix/unixLabels.cmo
# cc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE -Wall -I../../byterun  -I/usr/X11R6/include -c open.c
# In file included from open.c:19:
# ./libgraph.h:17:10: fatal error: 'X11/Xlib.h' file not found
# #include <X11/Xlib.h>
#          ^~~~~~~~~~~~
# 1 error generated.
# make[3]: *** [open.o] Error 1
# make[2]: *** [otherlibraries] Error 2
# make[1]: *** [all] Error 2
# make: *** [world] Error 2
```

So I think it is needed now. Just for building `ocaml-base-compiler`, not even `corectl` itself. 🤦‍♂

**Comment by alebcay** [comment]
I'm a bit confused, why is this marked as a build failure?

**Comment by SMillerDev** [comment]
Ehhhhh, so am I. I must have overlooked something when tagging.

**Comment by alebcay** [comment]
While you're here, any thoughts on the changes? This change has been sitting around for a while now ⌚️.

**Comment by SMillerDev** [comment]
Not too happy with an x11 dependency but at least it's just for build.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Pull request closed without merging**
