### PR TITLE
nicotine-plus: update description and homepage

### PR DESCRIPTION
**Pull request by mathiascode**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Update the description and homepage to the current ones used upstream.

### CODE REVIEW

**Comment by chenrui333** [comment]
build failed for linux runner
```
    error: [Errno 2] No such file or directory: 'msgfmt'
```

**Review by chenrui333 — APPROVED** [review]

**Comment by mathiascode** [comment]
The gettext dependency is not specific to Linux, perhaps it has been installed implicitly until now? https://nicotine-plus.org/doc/DEPENDENCIES.html#building

**Comment by chenrui333** [comment]
> The gettext dependency is not specific to Linux, perhaps it has been installed implicitly until now? https://nicotine-plus.org/doc/DEPENDENCIES.html#building

it is for makeinfo, which osx provided before ventura.

**Comment by chenrui333** [comment]
it is not broken for macOS builds, that is why I did not add it.

**Pull request closed without merging**
