### PR TITLE
micro 1.1.2

### PR DESCRIPTION
**Pull request by zyedidia**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by zyedidia** [comment]
Hmm I'm not sure what the test problem is. The makefile seems to be build the version as `1.1.3` instead of `1.1.2` even though on my machine it is working fine. The makefile uses git to determine what the current version should be. Is there any reason that might fail on on Jenkins?

**Comment by nijikon** [comment]
@zyedidia revert the bottle changes, this is done automatically on our end.

**Comment by zyedidia** [comment]
Ok I did that, and the other problems should be fixed as well.

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
