### PR TITLE
clamav: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by carlocab**
See #134251.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Linkage verified. Test failures are unrelated network issues.

**Comment by carlocab** [comment]
Tests need to succeed or else we lose bottles for the runners with failing tests.

**Comment by carlocab** [comment]
FYI, you can re-run only failing runners now. Doing that might be helpful here.

**Comment by p-linnane** [comment]
I didn't realize that. That's awesome!

**Comment by p-linnane** [comment]
Making progress here. Only Big Sur is failing the test. Looks like the rate limit is up in 4 hours, so I will try them again then.

**Pull request merged**
