### PR TITLE
streamlink 4.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bastimeyer** [comment]
Streamlink 4.0.0 has a new build-dependency `versioningit`:
https://streamlink.github.io/changelog.html#streamlink-4-0-0-2022-05-01

Not sure if you need to define it here, as it's set in the pyproject.toml file (PEP 518) and gets pulled from pypi when running `pip install` (via `virtualenv_install_with_resources`).

**Review by SMillerDev — APPROVED** [review]

**Comment by bastimeyer** [comment]
As pointed out in my [previous comment](https://github.com/Homebrew/homebrew-core/pull/100506#issuecomment-1114115455), you are pulling build-dependencies from PyPI when building `streamlink`. You'll have to package `versioningit` and its dependencies, and add it here as a build dependency.

**Comment by chenrui333** [comment]
> As pointed out in my [previous comment](https://github.com/Homebrew/homebrew-core/pull/100506#issuecomment-1114115455), you are pulling build-dependencies from PyPI when building `streamlink`. You'll have to package `versioningit` and its dependencies, and add it here as a build dependency.

I think it was pulled as recursive dependency, not direct dependency. Any concern over that?

**Comment by chenrui333** [comment]
also feel free to shoot a new PR to improve the formula.

**Pull request closed without merging**
