### PR TITLE
pipx 0.15.1.2

### PR DESCRIPTION
**Pull request by AlJohri**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Seems to be a tar issue with catalina, let's relaunch the CI to make sure.
@BrewTestBot test this please.

**Comment by fxcoudert** [comment]
```
pipx-0.15.1.2/src/pipx/.main.py.swp: Failed to restore metadata
tar: Error exit delayed from previous errors.
Error: Failure while executing; `tar xof /Users/brew/Library/Caches/Homebrew/downloads/f069ba4947f8e657fee51ecee1c0c8faf13b21b03fc0976800cd0c24eb5ae5c9--pipx-0.15.1.2.tar.gz -C /private/tmp/d20200117-33554-4zgrei` exited with 1. Here's the output:
pipx-0.15.1.2/src/pipx/.main.py.swp: Failed to restore metadata
tar: Error exit delayed from previous errors.
```

**Comment by fxcoudert** [comment]
I can confirm that on Catalina, the `.tar.gz` file is not unpacking:

```
$ tar xf pipx-0.15.1.2.tar.gz 
pipx-0.15.1.2/src/pipx/.main.py.swp: Failed to restore metadata
tar: Error exit delayed from previous errors.
```

**Comment by bayandin** [comment]
The same as in the previous attempt  (https://github.com/Homebrew/homebrew-core/pull/48955), I believe it's an upstream issue.

**Comment by AlJohri** [comment]
I will check this out- thanks for verifying.

**Comment by AlJohri** [comment]
This is fixed in `0.15.1.3`, I will submit a new PR.

**Comment by AlJohri** [comment]
Resolved by https://github.com/Homebrew/homebrew-core/pull/49893

**Pull request closed without merging**
