### PR TITLE
coffeescript 2.0.0

### PR DESCRIPTION
**Pull request by cglong**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---
I added `coffeescript@1` because 2.0.0 introduces breaking syntax changes to the language; happy to remove it though if determined to not be useful :smile:

### CODE REVIEW

**Comment by ilovezfs** [comment]
217 coffeescript installs in the last 30 days, so probably no need for the @1.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Review by ilovezfs — APPROVED** [review]

**Comment by fxcoudert** [comment]
@brewtestbot test this please

**Comment by fxcoudert** [comment]
@brewtestbost test this please

**Comment by fxcoudert** [comment]
Thanks @cglong for the pull request!

**Pull request closed without merging**
