### PR TITLE
openssl: compile with fips module

### PR DESCRIPTION
**Pull request by dsexton**
Build openssl with the FIPS module.

### CODE REVIEW

**Comment by SMillerDev** [comment]
We're trying to get rid of options because most are rarely used and never tested. If you think this should be a default addition you can edit your pull request to no longer use an option. Or you could maintain a version with options in your own tap.

**Comment by dsexton** [comment]
@SMillerDev updated per your suggestion

**Comment by fxcoudert** [comment]
- `openssl` is a key component, so I'm not sure we want to ship it in such a nondefault configuration.
- `no-ssl3` was carefully weighed before it was introduced, so we don't want to go back on that.

**Comment by MikeMcQuaid** [comment]
Agreed with @fxcoudert. Passing on this, sorry.

**Comment by dsexton** [comment]
@fxcoudert @MikeMcQuaid: I removed `no-ssl3` because there is a unit test for FIPS which tests that given FIPS mode is enabled, then SSLv3 is denied. However, the combination of `no-ssl3` and `fips` cause a test failure, which I believe to be a bug. That is why initially this PR had `no-ssl3` the default and `fips` as an options flag (i.e. with `fips` excludes `no-ssl3` flag).

Are one of these options possible?
* Reconsider my original proposal of having `fips` be an options flag?
* If I contribute a fix to the bad unit test in openssl, can this PR be reconsidered?

FIPS 140-2 is important when dealing with regulated industries, and it would be advantageous to have this included in the core packages where it is community maintained and updated.

Happy Holidays!

**Comment by MikeMcQuaid** [comment]
> Reconsider my original proposal of having `fips` be an options flag?

No, see https://github.com/Homebrew/homebrew-core/issues/31510. 

> If I contribute a fix to the bad unit test in openssl, can this PR be reconsidered?

I think that would be a wise idea anyway but: perhaps not.

> FIPS 140-2 is important when dealing with regulated industries, and it would be advantageous to have this included in the core packages where it is community maintained and updated.

I'm not sure I understand why it isn't part of the default OpenSSL installation but requires another package to be downloaded as well.

**Comment by dsexton** [comment]
@MikeMcQuaid:

I opened a PR with OpenSSL to resolve the unit test, hopefully that can be resolved soon.

Instead of updating OpenSSL to meet the requirements a module was created and passed validation:

> OpenSSL itself is not validated. Instead a special carefully defined software component called the OpenSSL FIPS Object Module has been created. This Module was designed for compatibility with OpenSSL so that products using the OpenSSL API can be converted to use validated cryptography with minimal effort. ([Source](https://www.openssl.org/docs/fips.html))

**Comment by MikeMcQuaid** [comment]
@dsexton I think the best bet for now is to maintain a `openssl-fips` formula in your own tap. I'd want to see a lot of people asking for this before we'd modify the OpenSSL formula in this way, sorry. It's just too important to the wider ecosystem.

**Pull request closed without merging**
