### PR TITLE
zookeeper 3.4.14

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
@chenrui333 Only listens to maintainers 😉 

@BrewTestBot test this please

**Comment by zbeekman** [comment]
Also, @chenrui333 can you please use the issue template, or at least say what you're changing and why when it's not a simple version bump?

(And you may enjoy using `brew bump-formula-pr ...` to handle the version updates which will also make our lives easier because we'll see it was created in the standard way and you won't need to fill out any PR templates for simple version incrementing.)

**Comment by chenrui333** [comment]
@zbeekman I can actually use the command `@BrewTestBot test this please` (somehow ;) )

yeah, I was kind of thinking to use the `brew bump-formula-pr`, but that is way too much hassle. But I will try to make change accordingly. :)

**Pull request closed without merging**
