### PR TITLE
neovim 0.7.0

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by clason** [comment]
@carlocab

**Comment by LC0117** [comment]
Wow! Waiting for this update.

**Comment by clason** [comment]
@carlocab (or anyone): looks like bottle upload will fail since I restarted the CI (by closing and reopening) from a failed run (when ARM12 runner ran out of disk space), same as the `lua-language-server` bump.

**Comment by hermitmaster** [comment]
https://github.com/neovim/neovim/pull/16219 has been resolved. Should be able to use the `libvterm` formula as a dependency now instead.

**Comment by clason** [comment]
No, it has not.

**Comment by hermitmaster** [comment]
@clason my bad, I didn't mean to post that comment.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
