### PR TITLE
zig 0.11.0

### PR DESCRIPTION
**Pull request by LarssonOliver**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  cd /tmp/zig-20230804-8002-75ynty/zig-0.11.0 && /tmp/zig-20230804-8002-75ynty/zig-0.11.0/build/zig2 build --prefix /tmp/zig-20230804-8002-75ynty/zig-0.11.0/build/stage3 --zig-lib-dir /tmp/zig-20230804-8002-75ynty/zig-0.11.0/lib -Dconfig_h=/tmp/zig-20230804-8002-75ynty/zig-0.11.0/build/config.h -Denable-llvm -Doptimize=ReleaseFast -Dstrip -Dno-langref -Dno-autodocs -Dtarget=native -Dcpu=core2 -Dversion-string=0.11.0
  error: sub-compilation of compiler_rt failed
      /tmp/zig-20230804-8002-75ynty/zig-0.11.0/lib/compiler_rt/addf3.zig:37:37: note: overflow of integer type 'u128' with value '-1'
      /tmp/zig-20230804-8002-75ynty/zig-0.11.0/lib/compiler_rt/addtf3.zig:16:17: note: called from here
      /tmp/zig-20230804-8002-75ynty/zig-0.11.0/lib/compiler_rt/exp2.zig:86:27: note: type 'f64' cannot represent float value '-nan'
  make[2]: *** [CMakeFiles/stage3.dir/build.make:76: stage3/bin/zig] Error 2
  make[2]: Leaving directory '/tmp/zig-20230804-8002-75ynty/zig-0.11.0/build'
  make[1]: *** [CMakeFiles/Makefile2:199: CMakeFiles/stage3.dir/all] Error 2
  make[1]: Leaving directory '/tmp/zig-20230804-8002-75ynty/zig-0.11.0/build'
  make: *** [Makefile:139: all] Error 2
```

**Comment by LarssonOliver** [comment]
Build only fails on Linux. I'll look into it as I get time, but feel free to work on it if you want. Previous comment shows the compilation issue.

**Comment by LarssonOliver** [comment]
So far been unable to reproduce this. 

Been testing on a machine running Ubuntu 22.04 (x86_64), which runs the homebrew Ubuntu container image.

```bash
docker run --interactive --tty --rm --pull always homebrew/ubuntu22.04:latest /bin/bash
```

Then, inside the container:
```bash
brew install cmake llvm z3 zstd ncurses zlib
curl https://ziglang.org/download/0.11.0/zig-0.11.0.tar.xz -o zig-0.11.0.tar.xz
tar -xf zig-0.11.0.tar.xz
cd zig-0.11.0
sudo ln -s /home/linuxbrew/.linuxbrew/lib/libzstd.so /lib
sudo ln -s /home/linuxbrew/.linuxbrew/lib/libtinfo.so /lib
cmake -S . -B build -DZIG_STATIC_LLVM=ON -DZIG_TARGET_MCPU=core2 -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF
cmake --build build
```

Builds fine.

For some reason, `ld` does not find `-lzstd` and `-ltinfo` here. Hence the symlinks.

`HOMEBREW_NO_INSTALL_FROM_API=1` does not appear to be working on Linux. Even when specified, the `brew --repository homebrew/core` repo checks out origin/master before trying to install. This is not the case on macos. It makes `HOMEBREW_NO_INSTALL_FROM_API=1 brew install zig --build-from-source` unusable here. Bug, or have I misunderstood this flag?

PS. `z3` is a dependency of `llvm` should it still be explicitly specified here?

**Comment by knweiss** [comment]
@LarssonOliver A shot in the dark but maybe this additional `cmake` argument helps?
```
-DCMAKE_PREFIX_PATH="$(brew --prefix llvm);$(brew --prefix zstd);$(brew --prefix ncurses)
```

It is mentioned here: https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#for-macos--homebrew

**Comment by LarssonOliver** [comment]
Done some more digging. In `install --interactive` mode, setting PATH as
```bash 
export PATH=/usr/bin:/home/linuxbrew/.linuxbrew/opt/cmake/bin:/home/linuxbrew/.linuxbrew/opt/llvm/bin:/home/linuxbrew/.linuxbrew/opt/lz4/bin:/home/linuxbrew/.linuxbrew/opt/xz/bin:/home/linuxbrew/.linuxbrew/opt/zstd/bin:/home/linuxbrew/.linuxbrew/opt/ncurses/bin:/home/linuxbrew/.linuxbrew/opt/binutils/bin
```
makes everything build fine. This essentially bypasses https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/super/cc when compiling. Thus, using the `/usr/bin/cc` directly.

I've not yet been able to figure out what Homebrew's `cc` script together with its environment variables does to create this issue.

---
```bash
$ env
SHELL=/bin/bash
HOMEBREW_DEBUG_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0
OBJCXX=g++-11
HOMEBREW_MACOS_OLDEST_ALLOWED=10.11
HOMEBREW_GENERIC_DEFAULT_REPOSITORY=/usr/local/Homebrew
HOMEBREW_COMMAND_DEPTH=2
HOMEBREW_CURL_SPEED_TIME=5
PKG_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/lz4/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/xz/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/zlib/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/zstd/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/z3/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/ncurses/lib/pkgconfig
HOMEBREW_PROCESSOR=x86_64
HOMEBREW_RUBY_WARNINGS=-W1
HOMEBREW_DEPENDENCIES=cmake,llvm,lz4,xz,zlib,zstd,z3,ncurses
HOMEBREW_REQUIRED_RUBY_VERSION=2.6.10
HOMEBREW_DEV_CMD_RUN=1
HOMEBREW_BOTTLE_DEFAULT_DOMAIN=https://ghcr.io/v2/homebrew/core
HOMEBREW_CCCFG=
HOMEBREW_RUBY_DISABLE_OPTIONS=--disable=gems,rubyopt
HOMEBREW_DEFAULT_LOGS=/home/linuxbrew/.cache/Homebrew/Logs
HOMEBREW_LINUX_DEFAULT_PREFIX=/home/linuxbrew/.linuxbrew
HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
HOMEBREW_ENV=super
HOMEBREW_DEFAULT_CACHE=/home/linuxbrew/.cache/Homebrew
HOMEBREW_LIBRARY_PATHS=/home/linuxbrew/.linuxbrew/lib
HOMEBREW_SYSTEM=Linux
HOMEBREW_BREW_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/brew
PWD=/tmp/zig-20230812-24681-x2js6w/zig-0.11.0
HOMEBREW_VERSION=4.1.4-38-g7044f50-dirty
SOURCE_DATE_EPOCH=1691090498
HOMEBREW_OPT=/home/linuxbrew/.linuxbrew/opt
HOMEBREW_MACOS_OLDEST_SUPPORTED=11
CXX=g++-11
TZ=UTC0
HOMEBREW_DEFAULT_TEMP=/tmp
HOMEBREW_LOGS=/home/linuxbrew/.cache/Homebrew/Logs
HOMEBREW_GITHUB_PACKAGES_AUTH=Bearer QQ==
HOME=/home/linuxbrew
HOMEBREW_BREWED_CURL_PATH=/home/linuxbrew/.linuxbrew/opt/curl/bin/curl
HOMEBREW_CURL=curl
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
HOMEBREW_LINUX_DEFAULT_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_ERROR_PIPE=/tmp/homebrew20230812-23981-1na9l3/socket
HOMEBREW_LINUX_MINIMUM_GLIBC_VERSION=2.13
RUSTFLAGS=--codegen target-cpu=core2
HOMEBREW_NO_INSTALL_FROM_API=1
HOMEBREW_RPATH_PATHS=/home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib:/home/linuxbrew/.linuxbrew/opt/gcc/lib/gcc/current:/home/linuxbrew/.linuxbrew/opt/lz4/lib:/home/linuxbrew/.linuxbrew/opt/xz/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/opt/zstd/lib:/home/linuxbrew/.linuxbrew/opt/z3/lib:/home/linuxbrew/.linuxbrew/opt/ncurses/lib:/home/linuxbrew/.linuxbrew/lib
TMPDIR=/tmp
CMAKE_PREFIX_PATH=/home/linuxbrew/.linuxbrew
HOMEBREW_MACOS_ARM_DEFAULT_PREFIX=/opt/homebrew
HOMEBREW_CURL_SPEED_LIMIT=100
HOMEBREW_DEFAULT_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_ARCHFLAGS=
HOMEBREW_PHYSICAL_PROCESSOR=x86_64
HOMEBREW_ISYSTEM_PATHS=/home/linuxbrew/.linuxbrew/include
LESSCLOSE=/usr/bin/lesspipe %s %s
MAKEFLAGS=-j8
TERM=xterm
HOMEBREW_MACOS_ARM_DEFAULT_REPOSITORY=/opt/homebrew
ACLOCAL_PATH=/home/linuxbrew/.linuxbrew/share/aclocal
HOMEBREW_AUTO_UPDATE_CHECKED=1
LESSOPEN=| /usr/bin/lesspipe %s
HOMEBREW_RUBY_PATH=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby
USER=linuxbrew
HOMEBREW_USER_AGENT_CURL=Linuxbrew/4.1.4-38-g7044f50-dirty (Linux; x86_64 Ubuntu 22.04.2 LTS) curl/7.81.0
HOMEBREW_CXX=g++-11
HOMEBREW_API_DEFAULT_DOMAIN=https://formulae.brew.sh/api
HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CC=gcc-11
HOMEBREW_BREW_FILE=/home/linuxbrew/.linuxbrew/bin/brew
TEMP=/tmp
SHLVL=1
HOMEBREW_FORMULA_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0
HOMEBREW_MACOS_NEWEST_UNSUPPORTED=14
HOMEBREW_AUTO_UPDATE_COMMAND=1
HOMEBREW_CORE_GIT_REMOTE=https://github.com/Homebrew/homebrew-core
HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
TERMINFO_DIRS=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/share/terminfo
HOMEBREW_USER_AGENT=Linuxbrew/4.1.4-38-g7044f50-dirty (Linux; x86_64 Ubuntu 22.04.2 LTS)
HOMEBREW_OPTFLAGS=-march=native
HOMEBREW_NO_BOOTSNAP=1
HOMEBREW_BREW_GIT_REMOTE=https://github.com/Homebrew/brew
HOMEBREW_DEFAULT_PREFIX=/home/linuxbrew/.linuxbrew
HOMEBREW_PRODUCT=Linuxbrew
HOMEBREW_GIT=git
LC_ALL=C.utf8
HOMEBREW_GIT_CONFIG_FILE=/home/linuxbrew/.linuxbrew/Homebrew/.git/config
OBJC=gcc-11
TMP=/tmp
PATH=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/cmake/bin:/home/linuxbrew/.linuxbrew/opt/llvm/bin:/home/linuxbrew/.linuxbrew/opt/lz4/bin:/home/linuxbrew/.linuxbrew/opt/xz/bin:/home/linuxbrew/.linuxbrew/opt/zstd/bin:/home/linuxbrew/.linuxbrew/opt/z3/bin:/home/linuxbrew/.linuxbrew/opt/ncurses/bin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/usr/bin:/bin:/usr/sbin:/sbin
CC=gcc-11
HOMEBREW_OS_VERSION=Ubuntu 22.04.2 LTS
OPENSSL_NO_VENDOR=1
HOMEBREW_USER_CONFIG_HOME=/home/linuxbrew/.homebrew
HOMEBREW_LIBRARY=/home/linuxbrew/.linuxbrew/Homebrew/Library
HOMEBREW_OPTIMIZATION_LEVEL=O2
HOMEBREW_DYNAMIC_LINKER=/home/linuxbrew/.linuxbrew/lib/ld.so
HOMEBREW_MINIMUM_GIT_VERSION=2.7.0
HOMEBREW_CACHE=/home/linuxbrew/.cache/Homebrew
HOMEBREW_TEMP=/tmp
HOMEBREW_DEBUG_INSTALL=zig
HOMEBREW_CORE_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/homebrew-core
HOMEBREW_GENERIC_DEFAULT_PREFIX=/usr/local
_=/usr/bin/env
```

**Comment by cho-m** [comment]
Homebrew's superenv/shims help clean up build environment for reproducible runs and portable binaries as mentioned in https://docs.brew.sh/Formula-Cookbook#superenv-notes. It does things like redirecting all compiler calls (`clang`, `gcc`, `cc`) to the same compiler, removing extra environment variables, adding header/lib directories as needed, modifying optimization settings (e.g. `-O*`, `-march`, ...), etc.

If you check Homebrew's logs, there should be a `*.cc` file that details how the shims are modifying commands, e.g. from `zig` logs attached in this PR you can see output in `02.cmake.cc` like:
```
superenv removed:  -O3
superenv added:    -pipe -w -march=core2 -isystem/home/linuxbrew/.linuxbrew/include
```
```
superenv removed:  -O3
superenv added:    -pipe -w -O2 -march=core2 -isystem/home/linuxbrew/.linuxbrew/include -L/home/linuxbrew/.linuxbrew/lib -B/home/linuxbrew/.linuxbrew/opt/glibc/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/gcc/lib/gcc/current -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/z3/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/lz4/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/xz/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/zlib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/zstd/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/ncurses/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so
```

---

For debugging, you could try modifying some optimization settings to see if it alters behavior like:
- Change optimization setting (e.g. `ENV.O3` for original optimization, `ENV.O0`, ...)
- Change compiler (e.g. try using LLVM to build with `fails_with :gcc` to see if GCC-specific)
- If you build from source (`-s`) it should use `-march=native`. If you build bottle (`--build-bottle`) it should use `-march=core2`

**Comment by LarssonOliver** [comment]
Struggling to get anywhere with this, closing for now due to time constraints from my side. If nothing else happens I'll look back into it in a few weeks.

**Comment by mclark4386** [comment]
This seemed to be the main PR for this version... What's the best way to bubble this back up so someone else may see that it's still needed? I would love to help, but have no idea where to start with what's holding this up even having read everything above.

**Pull request closed without merging**
