### PR TITLE
Logstash 5.1.1

### PR DESCRIPTION
**Pull request by jasontedor**
This commit updates the Logstash formula from version 5.0.2 to version
5.1.1.

### CODE REVIEW

**Comment by jasontedor** [comment]
Blocked by elastic/logstash#6378.

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by woodruffw** [comment]
(Meant to run test on #7681, apologies)

**Comment by jasontedor** [comment]
This is unblocked now with ff191bb0695906689f4817271ef3f13f6b3df345.

**Comment by woodruffw** [comment]
Probably worth making a note about the workaround so that it can be removed from future versions of the formula, but otherwise :+1: by me.

**Comment by jasontedor** [comment]
@woodruffw I pushed f5ca1f395af38f60808d6be39172edff626db705.

**Comment by dunn** [comment]
Thanks! Merged as 7372f126bdaacec21658d73f7a9b0bbe24232efb.

**Comment by jasontedor** [comment]
Thanks @dunn!

**Pull request closed without merging**
