### PR TITLE
hugo 0.18

### PR DESCRIPTION
**Pull request by ilovezfs**
use govendor

### CODE REVIEW

**Comment by dunn** [comment]
Gonna wanna update the resources per https://github.com/spf13/hugo/blob/master/vendor/vendor.json

**Comment by dunn** [comment]
I can take care of it, actually.

**Comment by dunn** [comment]
Rude, why can't I push to your branch.

**Comment by dunn** [comment]
Anyway feel free to cherry-pick https://github.com/dunn/homebrew-core/commit/b5fe18b416aca74dc8955023de11c58ed89cb8b6

**Comment by ilovezfs** [comment]
@dunn actually switching it over to `govendor sync`.

**Comment by hafeez3000** [comment]
Make sense

**Pull request closed without merging**
