### PR TITLE
frotz: enable sound and SDL support

### PR DESCRIPTION
**Pull request by dfabulich**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR enables graphics and sound support in frotz.

### CODE REVIEW

**Comment by jonchang** [comment]
`pkg-config` is an unusual runtime dependency. Can you check / confirm that all of these are needed at run time?

**Comment by dfabulich** [comment]
Good catch! Fixed.

**Comment by dfabulich** [comment]
Is this bottle failure something I need to act on?

**Comment by jonchang** [comment]
I'm using this pull request to test something out so you might see some failures. It won't be anything that you need to intervene for though.

**Pull request closed without merging**
