### PR TITLE
gom 0.3.3

### PR DESCRIPTION
**Pull request by ilovezfs**
build system switched to meson

### CODE REVIEW

**Comment by apjanke** [comment]
Looks like they switched from a `configure`-based build system to using Meson with this release, and the formula will have to be redone.

I don't know Meson, and there's no build instructions in the README, so...

**Comment by ilovezfs** [comment]
@apjanke it should build now

**Comment by apjanke** [comment]
Yep, builds now, now just an audit complaint.

```
Error: 1 problem in 1 formula
gom:
  * Dependency pygobject3 should not use option with-python3
```

**Review by tschoonj — DISMISSED** [review]
Looks good, but I would prefer to see the meson/ninja command being executed in a mkdir block, like e.g. `libhttpseverywhere`

**Pull request closed without merging**
