### PR TITLE
openjdk: add Linux dependencies and make some parts macOS only

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
The failure on Big Sur Arm64 seems to be due to a flaky upstream URL (I noticed the same issue when running `brew audit` locally).  However, I'm a little stumped by what happened with Mojave.

**Comment by SMillerDev** [comment]
I can't access the boot JDK for ARM either, I guess we'll have to find another. Possibly adoptJDK or something

**Comment by danielnachun** [comment]
Is it normal for this workflow to take more than 24 hours in CI?  I'm worried this is stuck on some test that doesn't exit properly.

**Comment by SMillerDev** [comment]
Yeah, that sounds about right. You can check the openjdk 16 PR to be sure.

**Comment by danielnachun** [comment]
There were some build failures here but OpenJDK itself built fine on the Intel Macs, and the failure on ARM is because of an invalid upstream URL.  Are we okay with merging this as is?

**Comment by danielnachun** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/72535

**Pull request closed without merging**
