### PR TITLE
ghostscript 10.02.1

### PR DESCRIPTION
**Pull request by ik11235**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@ik11235 the dependency tests can be handled separately, no need to do the forced updates (it would build/test from the beginning)

**Comment by ik11235** [comment]
@chenrui333 
Noted on this. Thank you for pointing that out. I will be careful next time.

**Comment by chenrui333** [comment]
No worries

**Comment by chenrui333** [comment]
`brew test --retry --verbose lilypond`

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
