### PR TITLE
supervisor 4.2.1

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
I am not sure which license to use here when looking at [upstream LICENSES.txt file](https://github.com/Supervisor/supervisor/blob/master/LICENSES.txt).

**Comment by chenrui333** [comment]
> I am not sure which license to use here when looking at [upstream LICENSES.txt file](https://github.com/Supervisor/supervisor/blob/master/LICENSES.txt).

IMO, the license field should be `license all_of: ["BSD-4-Clause", "BSD-3-Clause", "MIT"]`

cc @Rylan12

**Comment by Rylan12** [comment]
The license issues in CI should be fixed by a rebase (this PR must have been opened right in-between merging the brew PR and pushing fixes for the newly broken formulae.

The license looks a little more complex so that might want to move to it's own PR.

> IMO, the license field should be `license all_of: ["BSD-4-Clause", "BSD-3-Clause", "MIT"]`

Not sure about `BSD-4-Clause`. The license provided doesn't seem to match `BSD-4-Clause` but I can't figure out exactly what it is. It's pretty similar to `ZPL-2.0` or `ZPL-2.1`, but not quite the same.

I agree with `BSD-3-Clause`.

I think the last one is `MIT-CMU`.

**Comment by SMillerDev** [comment]
Check if Debian allows the license, if Debian doesn't mark it for deletion.

**Comment by Rylan12** [comment]
`ZPL` is not listed at all on https://wiki.debian.org/DFSGLicenses

Assuming that's what you had in mind, I think we need to mark for deletion.

**Comment by gromgit** [comment]
FYI, I pinged upstream about this two weeks ago: https://github.com/Homebrew/homebrew-core/pull/59371#issuecomment-671164701. Bottom line: They're no help.

**Comment by Moisan** [comment]
Alright I'll update the PR to remove the formula unless someone objects.

**Review by SMillerDev — COMMENTED** [review]
LGTM

**Comment by jonchang** [comment]
Debian lists it as BSD: https://salsa.debian.org/python-team/applications/supervisor/-/blob/debian/master/debian/copyright

**Comment by dtrodrigues** [comment]
I think if it's removed from Debian due to the licensing issue, it would make sense to remove from Homebrew but until then, I'm slightly opposed to fully removing it.

**Comment by Moisan** [comment]
Looking at the [SPDX listing](https://spdx.org/licenses/), I don't know which of the BSD licenses I should add.

**Comment by SMillerDev** [comment]
@jonchang can you make a suggestion for the new value of license

**Comment by jonchang** [comment]
It's BSD-3-clause with an extra "say you modified the source code" clause. Don't think it's SPDX listed. We can probably ask SPDX to add it to the list?

**Comment by Moisan** [comment]
I added the BSD-3-clause license but I'll request the new license from SPDX.

**Comment by Moisan** [comment]
New license request: https://github.com/spdx/license-list-XML/issues/1094

**Comment by Rylan12** [comment]
Let's move forward with the version bump so we can get `supervisor` 4.2.1 out. We can handle the license in a separate issue/PR, especially because I don't know how quickly we can expect a response from SPDX

**Comment by Moisan** [comment]
I am stuck here, the test is passing locally on 10.15.

**Comment by Moisan** [comment]
Closing for now.

**Pull request closed without merging**
