### PR TITLE
liboping 1.10.0

### PR DESCRIPTION
**Pull request by SimenB**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Unsure if the test is valid? `bump-formula-pr` failed without it, and it seems to pass 🙂

### CODE REVIEW

**Comment by SimenB** [comment]
Test fails 😭 Ideas?

**Comment by dunn** [comment]
We run the tests in a sandbox, which I think is what's causing it to fail:
```
==> /usr/local/Cellar/liboping/1.10.0/bin/oping -c 1 https://www.github.com
ping_send failed: Operation not permitted
PING github.map.fastly.net (151.101.0.133) 56 bytes of data.
Error: liboping: failed
Failed executing: /usr/local/Cellar/liboping/1.10.0/bin/oping -c 1 https://www.github.com
```
@MikeMcQuaid did we disallow network calls in the sandbox profile?

**Comment by SimenB** [comment]
Liboping needs sudo for some reason :/ There's a caveat section

**Comment by dunn** [comment]
Ah, gotcha.  Well, that would explain why there hadn't been a test before.  

Can it just print the version or help text instead?  That would be better than nothing.

**Comment by SimenB** [comment]
I opened up octo/liboping#24, no response, though.

I can try a `version`, in a couple of days. PC-less until then :smile:

**Comment by SimenB** [comment]
There was no version option, but the help text could be printed at least 🙂

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid did we disallow network calls in the sandbox profile?

@dunn Nope; I started down that path a while ago but it proved way too hard.

**Comment by dunn** [comment]
Merged as 904570e6cbc1c61771899bd4932ff808a7c59a5f, thanks!

**Pull request closed without merging**
