### PR TITLE
Use free_port instead of TCPServer.new(0) in test

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR applies following changes:

```diff
-    server = TCPServer.new(0)
-    port = server.addr[1]
-    server.close
+    port = free_port
```

DO NOT MERGE until the next homebrew release with https://github.com/Homebrew/brew/pull/7225

### CODE REVIEW

**Comment by bayandin** [comment]
- `oauth2_proxy` will be fixed by https://github.com/Homebrew/homebrew-core/pull/52620
- `brew audit miniserve --online` failure is expected (https://github.com/Homebrew/brew/pull/7256#issuecomment-607765840)

- `brew test fn --verbose` — looks like an unstable test will have a look at it

And there're several extra failures on high sierra:
- [`brew install --verbose --build-bottle php`](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/60502/version=highsierra/testReport/junit/brew-test-bot/high_sierra/install___build_bottle_php/): 
```
checking for libxml-2.0 >= 2.7.6... no
configure: error: in `/private/tmp/php-20200405-4628-lepu8v/php-7.4.4':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.
```

- [`brew install --verbose --build-bottle imgproxy`](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/60502/version=highsierra/testReport/junit/brew-test-bot/high_sierra/install___build_bottle_imgproxy/):
```
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
# /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config --cflags  -- vips
--define-variable argument does not have a value for the variable
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: exit status 1
```

Are these fails related to the latest changes in `pkg-config` @Bo98?

**Comment by Bo98** [comment]
Yes, sorry. Please ignore those High Sierra failures. I fixed the issue last night.

**Comment by bayandin** [comment]
No problem, thanks!

**Comment by bayandin** [comment]
- `brew audit miniserve --online` failure is expected (Homebrew/brew#7256 (comment))

We're good to go right after the next release of homebrew. 
Since changes affect tests only it could be merged via GitHub UI (Rebase and merge).

**Pull request merged**
