### PR TITLE
libffi: use std_configure_args

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Related: https://github.com/Homebrew/homebrew-core/pull/66965, https://github.com/Homebrew/brew/pull/10047

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Comment by SeekingMeaning** [comment]
11.0:

```
brew test --retry --verbose creduce
brew test --retry --verbose glyr
brew test --retry --verbose llvm
brew install pypy
brew install pypy3
```

10.15, 10.14:

```
brew test --retry --verbose glyr
```

**Comment by iMichka** [comment]
Merged as this is almost only a syntax change. Tested locally and all is fine.

The other build failures are unrelated but concerning. Should we open a separate issue to keep track of these?

**Comment by SeekingMeaning** [comment]
Most of the Big Sur failures are acknowledged in https://github.com/Homebrew/homebrew-core/issues/65000; I'm not sure why `llvm` and `glyr` are failing

**Comment by iMichka** [comment]
`glyr` is known too: #66450

**Pull request merged**
