### PR TITLE
go: Update URLs to new go.dev domain

### PR DESCRIPTION
**Pull request by marcofranssen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This removes some HTTP redirects (301) redirect

### CODE REVIEW

**Comment by marcofranssen** [comment]
Seems to be an error in the workflow, let me know if there is anything I can do to fix it.

**Comment by carlocab** [comment]
It should be fine; GitHub just couldn't allocate the self-hosted runner because it's in use.

We'll want to wait until #88775 is merged to avoid introducing a merge conflict there and having to re-run CI. Thanks for your contribution!

**Comment by marcofranssen** [comment]
I can also include the version bump in this PR if that makes it easier. Locally I am already using the 1.17.3 version including this change.

**Comment by carlocab** [comment]
> I can also include the version bump in this PR if that makes it easier.

No, that will mean ~3 days of CI. Let's let the other one finish the existing run.

**Comment by marcofranssen** [comment]
@carlocab oh wow, didn't know there are 3 days of CI involved, that is massive. Looking at the other PR, it did the same change now in addition to the version bump. so will close my PR.

https://github.com/Homebrew/homebrew-core/pull/88775/files#diff-2b4628657de5dd65ff1afe2817f23c4deb13e2ba587b1fe8a7605479c5e0c660R3-R4

Hopefully the issues with the version bump are resolved soon.

**Pull request closed without merging**
