### PR TITLE
tarsnap 1.0.39

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
1.0.39 has landed, FWIW.

**Comment by dunn** [comment]
@brewtestbot test this please

**Comment by dunn** [comment]
Oh woops I didn't see the label 😬

**Comment by ilovezfs** [comment]
Reported https://github.com/Tarsnap/tarsnap/issues/286.

**Pull request closed without merging**
