### PR TITLE
yq 4.9.3

### PR DESCRIPTION
**Pull request by Moulick**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moulick** [comment]
Created as https://github.com/Homebrew/homebrew-core/pull/77778 is closed

made for https://github.com/mikefarah/yq/issues/830

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @Moulick  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by Moulick** [comment]
@SMillerDev  maybe stupid question, why is this not merged and instead closed ? 
I see it's merged somehow but not merged in GitHub ?

**Comment by SMillerDev** [comment]
Because the bot doesn't do a github merge action, it takes the commit (squashes it if needed) and rebase it into the branch.

**Pull request closed without merging**
