### PR TITLE
aws-elasticbeanstalk 3.16.0

### PR DESCRIPTION
**Pull request by issyl0**
Created with `brew bump-formula-pr`.

Resolves some conversation about revision bumps after #47369.

### CODE REVIEW

**Comment by issyl0** [comment]
:eyes: ❌

**Comment by SMillerDev** [comment]
The file on line 161 doesn't seem to exist anymore according to jenkins

**Comment by issyl0** [comment]
I checked all the releases since 3.14.6 for that file: It was removed in 3.14.9, with no notes in the changelog as to why. Maybe they forgot about it, or maybe it legitimately didn't work any more? If this were a project with a GitHub repo I'd raise an issue and ask, but alas it is not. I guess I'll remove the completions.

**Comment by SMillerDev** [comment]
I think you need to update the resources too. It's missing something.

**Comment by issyl0** [comment]
I updated many resources. The test passes locally now. 🤞 for CI.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
