### PR TITLE
osc 0.165.4

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
`osc` seems to support `python3` now. Could you make the switch?

**Comment by alebcay** [comment]
Well, I made the switch and now it looks like `virtualenv` is not getting found.

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by Moisan** [comment]
Going to force push to merge the recent changes.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Close due to inactivity.

**Pull request closed without merging**
