### PR TITLE
nginx: include HTTP/3 module

### PR DESCRIPTION
**Pull request by lcrilly**
Since the formula for nginx was updated to 1.25.0 with commit f13c480 it is now possible to build nginx with the ngx_http_v3_module [1]. The Formula already requires OpenSSL 1.1 which is sufficient to utilize nginx's OpenSSL compatibility layer the QUIC TLS API.

[1] http://nginx.org/en/docs/http/ngx_http_v3_module.html

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Review by carlocab — COMMENTED** [review]
> The module is experimental, caveat emptor applies.

Note that we don't usually enable experimental features, particularly when they're disabled by default.

**Comment by lcrilly** [comment]
@carlocab that's fair, and of course subject to Homebrew's policy on these things.

If it helps, the HTTP/3 module *is* built by default on the [nginx official packages](https://hg.nginx.org/pkg-oss/rev/d571b0a7b706) (provided the platform provides a suitable TLS library) and the Docker Official Image.

**Comment by carlocab** [comment]
> If it helps, the HTTP/3 module *is* built by default on the [nginx official packages](https://hg.nginx.org/pkg-oss/rev/d571b0a7b706) (provided the platform provides a suitable TLS library) and the Docker Official Image.

That does change things. I'm fine with this change if another maintainer agrees with me and is willing to approve it.

**Comment by chenrui333** [comment]
> > If it helps, the HTTP/3 module _is_ built by default on the [nginx official packages](https://hg.nginx.org/pkg-oss/rev/d571b0a7b706) (provided the platform provides a suitable TLS library) and the Docker Official Image.
> 
> That does change things. I'm fine with this change if another maintainer agrees with me and is willing to approve it.

yeah, i think we can ship `http_v3_module` support (just did cross check, archlinux already does the same)

**Review by chenrui333 — APPROVED** [review]

**Comment by oxpa** [comment]
Just for the record: even though it is called 'experimental' the feature is shipped in nginx.org packages.
http://hg.nginx.org/pkg-oss/file/tip/rpm/SPECS/Makefile#l91
Everything newer than 5 years is called 'experimental' in nginx >_<

**Comment by chenrui333** [comment]
Thanks @lcrilly!

**Comment by lcrilly** [comment]
> Thanks @lcrilly!

My pleasure. Thanks for all that you do!

**Pull request merged**
