### PR TITLE
plank 1.5

### PR DESCRIPTION
**Pull request by rahul-malik**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like it's failing to build with Sierra's version of Swift. Is this expected?

**Comment by rahul-malik** [comment]
The swift version bumped to 4.2 which might have broken this. If I upgrade the Xcode requirement does that eliminate Sierra builds?

**Comment by rahul-malik** [comment]
@mistydemeo - I updated the formula by removing the line for Sierra since I believe Swift 4.2 and at least the required Xcode won't support it. Let me know if there is anything else you'd like to see updated. Thanks!

**Comment by fxcoudert** [comment]
Thanks @rahul-malik for the pull request

**Comment by rahul-malik** [comment]
@fxcoudert - Any idea how the bottle sha256 entries are updated? I just tried to install but the bottle installation failed since it didn't match the sha256 entry in the formula

**Comment by fxcoudert** [comment]
The bottles are merged by the maintainers during commit: the PR was merged in d5b8c24526d76744223b4f8c973c0529bac54ccc and the bottle was updated in 3eb6ad42b5337b645b440e68dd6fdd3b224e7787

**Pull request closed without merging**
