### PR TITLE
berkeley-db 18.1.40

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Installing DB utilities: /usr/local/Cellar/berkeley-db/18.1.40/bin ...
libtool: install: cp -p .libs/db_archive /usr/local/Cellar/berkeley-db/18.1.40/bin/db_archive
libtool: install: cp -p .libs/db_checkpoint /usr/local/Cellar/berkeley-db/18.1.40/bin/db_checkpoint
libtool: install: cp -p .libs/db_convert /usr/local/Cellar/berkeley-db/18.1.40/bin/db_convert
libtool: install: cp -p .libs/db_deadlock /usr/local/Cellar/berkeley-db/18.1.40/bin/db_deadlock
libtool: install: cp -p .libs/db_dump /usr/local/Cellar/berkeley-db/18.1.40/bin/db_dump
libtool: install: cp -p .libs/db_hotbackup /usr/local/Cellar/berkeley-db/18.1.40/bin/db_hotbackup
libtool: install: cp -p .libs/db_load /usr/local/Cellar/berkeley-db/18.1.40/bin/db_load
libtool: install: cp -p .libs/db_log_verify /usr/local/Cellar/berkeley-db/18.1.40/bin/db_log_verify
libtool: install: cp -p .libs/db_printlog /usr/local/Cellar/berkeley-db/18.1.40/bin/db_printlog
libtool: install: cp -p .libs/db_recover /usr/local/Cellar/berkeley-db/18.1.40/bin/db_recover
libtool: install: cp -p .libs/db_replicate /usr/local/Cellar/berkeley-db/18.1.40/bin/db_replicate
libtool: install: cp -p .libs/db_stat /usr/local/Cellar/berkeley-db/18.1.40/bin/db_stat
libtool: install: cp -p .libs/db_tuner /usr/local/Cellar/berkeley-db/18.1.40/bin/db_tuner
libtool: install: cp -p .libs/db_upgrade /usr/local/Cellar/berkeley-db/18.1.40/bin/db_upgrade
libtool: install: cp -p .libs/db_verify /usr/local/Cellar/berkeley-db/18.1.40/bin/db_verify
Installing documentation: /usr/local/Cellar/berkeley-db/18.1.40/docs ...
cp: bdb-sql: No such file or directory
cp: gsg_db_server: No such file or directory
make: *** [install_docs] Error 1
```

**Comment by gromgit** [comment]
Just looked at the [changelog for this release](https://download.oracle.com/otndocs/products/berkeleydb/html/changelog_18_1_40.html):
> The Berkeley DB client-server architecture is no longer supported. If you require the Berkeley DB client-server architecture you must use Berkeley DB 18.1.32 or earlier.

That might break stuff for some users.

> The SQL API is no longer supported. If you require SQL support you must use Berkeley DB 18.1.32 or earlier.

And yet it tries to install the (now nonexistent) SQL docs. Sounds like this release should be reconsidered.

**Comment by SMillerDev** [comment]
If upstream wants to break things for users it's not on us to stop that.

**Comment by gromgit** [comment]
> If upstream wants to break things for users it's not on us to stop that.

True, but the release itself is broken. Even a manual `make install` on Linux triggers that same error. I'm surprised it got through QA.

**Pull request closed without merging**
