### PR TITLE
node-build 2.6.8

### PR DESCRIPTION
**Pull request by jasonkarns**
Fix sha after retag

### CODE REVIEW

**Comment by ilovezfs** [comment]
@jasonkarns this still seems to be the same checksum

**Comment by jasonkarns** [comment]
Hmm, that's the one that brew gave me as "actual" when attempting an install _without_ the checksum in the formula.

**Comment by ilovezfs** [comment]
@jasonkarns delete it from your cache :)

**Comment by jasonkarns** [comment]
that should do it

**Comment by ilovezfs** [comment]
@jasonkarns now we will get the audit error telling us to report this to you :)

**Comment by ilovezfs** [comment]
```
Error: 1 problem in 1 formula
node-build:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```
:tada:

**Comment by ilovezfs** [comment]
Thanks @jasonkarns!

**Comment by jasonkarns** [comment]
Kindly tell brew-bot that upstream thought he was being clever and screwed everything up instead :) He won't do it again. (Though he still needs to figure out why the scripts result in different tags between local-git and github. :/ )

**Pull request merged**
