### PR TITLE
qwt 6.1.6

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
It's not clear to me why we have `if ENV.compiler == :clang`, the compiler is always clang. @iMichka is that a linux thing?

**Comment by yurikoles** [comment]
I just tried to not break things :)

**Comment by iMichka** [comment]
@fxcoudert this predates the start of the linux migration (d8d32c0797b dates back to 03/2020). But the code is not wrong, I would keep the gcc/clang distinction. It's a shame that you need to manually to specify all these targets ...

**Review by carlocab — APPROVED** [review]
Thanks, @yurikoles.

**Pull request closed without merging**
