### PR TITLE
yaml-cpp 0.6.3

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failed
```
00:01:52 ==> expect -f test.exp
00:01:52 send: spawn id exp6 not open
00:01:52     while executing
00:01:52 "send "me@foo.bar
00:01:52 ""
00:01:52     (file "test.exp" line 7)
00:01:52 Error: skafos: failed
00:01:52 An exception occurred within a child process:
00:01:52   Test::Unit::AssertionFailedError: <0> expected but was
00:01:52 <1>.
```

**Comment by chenrui333** [comment]
Test seems working fine in my local:
```
omebrew/Library/Taps/homebrew/homebrew-core/Formula/yaml-cpp.rb --verbose
==> /usr/bin/clang++ test.cpp -std=c++11 -L/usr/local/Cellar/yaml-cpp/0.6.3/lib -lyaml-cpp -o test
==> ./test
```

**Comment by fxcoudert** [comment]
`skafos` needs a revision bump?

**Comment by chenrui333** [comment]
Good point, I will do that.

**Comment by chenrui333** [comment]
Updated the test for `skafos`

**Comment by chenrui333** [comment]
skafos Test step failed in Catalina build:

23:07:56 ==> expect -f test.exp
23:07:56 The system has no more ptys.  Ask your system administrator to create more.
23:07:56     while executing
23:07:56 "spawn /usr/local/Cellar/skafos/1.7.7_1/bin/skafos setup"
23:07:56     (file "test.exp" line 1)
23:07:56 Error: skafos: failed
23:07:56 An exception occurred within a child process:
23:07:56   Test::Unit::AssertionFailedError: <0> expected but was
23:07:56 <1>.

**Pull request closed without merging**
