### PR TITLE
fribidi 1.0.10

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Continuation of https://github.com/Homebrew/homebrew-core/pull/57505

**Comment by miccal** [comment]
```
Error: 2 failed steps!
brew fetch --retry evince
brew test --verbose opentsdb
```

See https://github.com/Homebrew/homebrew-core/pull/57584#issuecomment-654823296

**Comment by chenrui333** [comment]
oops, thought there is CI issue, just rebased to the latest master (I guess it does not hurt either though)

**Comment by miccal** [comment]
No problem @chenrui333 -- If you do not mind, could you please have a look at my PR [here](https://github.com/Homebrew/homebrew-core/pull/57562); for some reason the tests are not running?

Thanks.

**Comment by miccal** [comment]
@chenrui333 the only failure now is `opentsdb`, so I think this can be merged?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> @chenrui333 the only failure now is `opentsdb`, so I think this can be merged?

@miccal sorry for missing earlier, yeah, we can definitely ship this out.

**Pull request closed without merging**
