### PR TITLE
deis 2.11.0

### PR DESCRIPTION
**Pull request by jayjun**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This formula needs to be changed not to use `go get`

**Comment by jayjun** [comment]
I don't believe there's a workaround.

[The original source](https://github.com/deis/workflow-cli/blob/master/version/version.go) uses the Go linker to pass the current version number into the build.

Without it, the `deis version` command won't work.

**Comment by jayjun** [comment]
@ilovezfs Found official Darwin binaries. Removed Go dependency in 29049be.

**Comment by MikeMcQuaid** [comment]
@jayjun We need to build from source, sorry.

**Comment by jayjun** [comment]
@MikeMcQuaid The [official build](https://github.com/deis/workflow-cli/blob/master/Makefile#L42) uses `gox`, but I can't use `go get`.

Can I clarify that we need to find a way to use `go build` alone?

**Comment by MikeMcQuaid** [comment]
@jayjun We prefer upstream vendored resources or submodules but if not you can use `go_resource` (`grep` other formulae to see usage).

**Comment by jayjun** [comment]
Thanks for the `go_resource` hint @MikeMcQuaid.

305b7d7 removes `go get` and builds from source.

**Comment by dunn** [comment]
Looks great, thanks! Merged as f3648f06d9d188117599e537a504b8fd8445cafd.

**Pull request closed without merging**
