### PR TITLE
tmuxinator 3.0.1

### PR DESCRIPTION
**Pull request by dcalhoun**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by Rylan12 — COMMENTED** [review]
Can you try updating the `thor` resource to [version 1.1.0](https://rubygems.org/gems/thor/versions/1.1.0)?

**Comment by dcalhoun** [comment]
> Can you try updating the `thor` resource to [version 1.1.0](https://rubygems.org/gems/thor/versions/1.1.0)?

@Rylan12 Sure. Is that something `brew bump-forumla-pr` is able to handle or a manual change?

**Comment by Rylan12** [comment]
No, unfortunately, it's a manual thing. `brew bump-formula-pr` can only automatically update python dependencies at the moment.

It should be pretty simple, just change the version number in the URL and copy the checksum from the rubygems page.

**Comment by cho-m** [comment]
On a side note, it looks like all Intel bottles are same as of 3.0.0

The diff if someone wants to try look into difference with ARM bottle (based on 3.0.1)
```diff
❯ git diff tmuxinator-arm tmuxinator-intel
diff --git a/tmuxinator-arm/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir/extended.rb b/tmuxinator-intel/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir/extended.rb
index 86cbd22..4137e75 100644
--- a/tmuxinator-arm/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir/extended.rb
+++ b/tmuxinator-intel/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir/extended.rb
@@ -5,7 +5,7 @@ module XDG

     #
     DEFAULTS['XDG_RESOURCE_HOME'] = ['~/.local']
-    DEFAULTS['XDG_RESOURCE_DIRS'] = ['/usr/local','/usr']
+    DEFAULTS['XDG_RESOURCE_DIRS'] = ['@@HOMEBREW_PREFIX@@','/usr']

     # Working directory
     # TODO: Not sure about these defaults
diff --git a/tmuxinator-arm/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir.rb b/tmuxinator-intel/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir.rb
index 2b6800d..efd6303 100644
--- a/tmuxinator-arm/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir.rb
+++ b/tmuxinator-intel/3.0.1/libexec/gems/xdg-2.2.5/lib/xdg/base_dir.rb
@@ -12,7 +12,7 @@ module XDG
     # Standard defaults for locations.
     DEFAULTS = {
       'XDG_DATA_HOME'   => ['~/.local/share'],
-      'XDG_DATA_DIRS'   => ['/usr/local/share', datadir],
+      'XDG_DATA_DIRS'   => ['@@HOMEBREW_PREFIX@@/share', datadir],
       'XDG_CONFIG_HOME' => ['~/.config'],
       'XDG_CONFIG_DIRS' => [File.join(sysconfdir,'xdg'), sysconfdir],
       'XDG_CACHE_HOME'  => ['~/.cache'],
```

**Comment by carlocab** [comment]
Those directories come from the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), so I'm not sure those should be relocated.

Or, if we're relocating them on Intel, we may as well relocate them on ARM too.

**Comment by nandahkrishna** [comment]
Updated the `thor` resource. Meanwhile, I was going to open a PR to restrict relocation in text files based on Rylan's suggestion (in Slack and https://github.com/Homebrew/brew/issues/11558#issuecomment-864153583), but I think what we're seeing here is a stronger argument to have a `skip_relocation` DSL (for specific files/cases).

**Comment by cho-m** [comment]
The current behavior of relocation on resource packages probably needs to be looked into. If there is no smart way to autodetect, then a DSL may be necessary.
- Here, we have a Ruby gem where `/usr/local` is being replaced where it probably shouldn't be.
- In https://github.com/Homebrew/homebrew-core/pull/79683#issuecomment-864616631, we have Python packages like pip is seeing a similar behavior.

**Review by carlocab — APPROVED** [review]
I think the discussion about relocation can be pursued elsewhere, and shouldn't block this PR.

Thanks, @dcalhoun!

**Pull request closed without merging**
