### PR TITLE
atk 2.35.1

### PR DESCRIPTION
**Pull request by GabriellaXue**
see #50891

### CODE REVIEW

**Comment by chenrui333** [comment]
audit failure, saying it is dev release.

Looking at the tag list, https://gitlab.gnome.org/GNOME/atk/-/tags, did not find anything alarming.

**Comment by chenrui333** [comment]
I will cross-check brew audit on this later.

**Comment by Bo98** [comment]
The livecheck was wrong about this one: Homebrew/homebrew-livecheck#300.

GNOME is weird, I know.

**Comment by chenrui333** [comment]
hmm, interesting to know.

**Comment by chenrui333** [comment]
my question is "is this a development release"?

**Comment by Bo98** [comment]
There's a mention of their version system on [Wikipedia](https://en.wikipedia.org/wiki/GNOME#GNOME_1):

> GNOME version numbers follow the scheme v.xx.yy. (...) if xx is even (e.g. 3.20) the release is considered stable, whereas if xx is odd it represents a current development snapshot (e.g. 3.21) that will eventually evolve into the next stable release.

**Comment by chenrui333** [comment]
I see, that makes more sense.

**Comment by chenrui333** [comment]
honestly, I still think we might want to merge this work (2.34 -> 2.35), the release (2.35.1) was done in last September.

**Comment by Bo98** [comment]
If you want 2.35.1, then you'll need to request for it to be [whitelisted](https://github.com/Homebrew/brew/blob/bcb8f4da5f48bb4ad96c1c66af0a3b5996f711d1/Library/Homebrew/dev-cmd/audit.rb#L751-L756).

However, GNOME 3.36 is released in about a week and ATK 2.36.0 should be released at the same time, so there isn't too much longer to wait for a stable version.

**Comment by chenrui333** [comment]
Nice!

**Pull request closed without merging**
