### PR TITLE
Complete core formula bottling

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

With this PR we now have at least one bottle for every formula in homebrew-core. `vmalloc` had some installs since analytics began but cannot be downloaded any more and the homepage isn't up either. The rest had 0️⃣ installations. I added `ld64` bottles because I'm a completionist and had Leopard/Snow Leopard VMs handy.

I believe now this has been done we can enable the sandbox for users installing formulae in homebrew/core. Correct me if I'm wrong, here.

CC @mistydemeo @xu-cheng

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> I believe now this has been done we can enable the sandbox for users installing formulae in homebrew/core. Correct me if I'm wrong, here.

I am wrong, still a few more to do: https://github.com/Homebrew/homebrew-core/issues/342

**Comment by DomT4** [comment]
All of the boneyardings here seem reasonable to me, at least.

**Comment by UniqMartin** [comment]
I agree with all of the changes made here. Filed #2195 to complement this one and get one step closer to achieving the stated goal of this PR.

**Comment by UniqMartin** [comment]
👍 👏  (And sorry for temporarily creating a merge conflict for you.)

**Pull request closed without merging**
