### PR TITLE
fheroes2: Adding installation instructions and documentation

### PR DESCRIPTION
**Pull request by kfishster**
Adding additional documentation to the homebrew installation process similar to how it functions in the [MacPorts formula](https://github.com/macports/macports-ports/blob/master/games/fheroes2/Portfile)

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
All of this should be documented upstream, not in the formula

**Comment by dawidd6** [comment]
Also, those instructions will only be printed if a user installs the formula from source, which means majority of people won't see these anyway.

**Comment by kfishster** [comment]
@SMillerDev @dawidd6 thanks for the feedback. Could you advise on how to better approach this? I tried using `ohai` to print out installation instructions, but it seems that has a length limit. We want to mimic a behavior we've used in the [MacPorts installation procedure](https://github.com/macports/macports-ports/blob/master/games/fheroes2/Portfile), would you recommend just adding a link to documentation instead of printing out the whole instructions? Is there a different way to print out some helpful tips to the user?

**Comment by SMillerDev** [comment]
Unless it's specific to Homebrew it should not be printed by Homebrew installs.

**Comment by kfishster** [comment]
@SMillerDev, got it. Would it be acceptable to print just the bare minimum, something like, "read this Readme" or "visit this website for more information" using ohai in the installation portion? As there are additional steps here, it would be super helpful to point a user to the documentation.

**Comment by SMillerDev** [comment]
The install portion would rarely ever be seen. You're looking for a caveat but even those are usually ignored.

**Comment by kfishster** [comment]
Got it. I'll try to create this via caveats, even if they are not usually read, it would just make it consistent across our install surfaces.

**Pull request closed without merging**
