### PR TITLE
dotnet 8.0.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
On Linux:

```
gzip: stdout: No space left on device
```

**Comment by ZhongRuoyu** [comment]
Ah wait, it's `stdout`, and [the file doesn't seem to be large](https://github.com/Homebrew/homebrew-core/actions/runs/7928895403/job/21648227618?pr=162703#step:4:153).

**Comment by SMillerDev** [comment]
> Can this be merged? The newest version of EF Core CLI doesn't work without it.

No, because it doesn't work

**Comment by ffried** [comment]
For those blocked by EF Core CLI not working w/o this, you can downgrade the CLI tools:

```bash
dotnet tool uninstall --global dotnet-ef
dotnet tool install --global --version 8.0.1 dotnet-ef
```

This first uninstalls the `dotnet-ef` tools, then re-installs them by explicitly using version 8.0.1.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
