### PR TITLE
fheroes2 1.0.11

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>- Expand Battle Only mode with saving functionality and updated UI
- Add Town and Ocean objects placement in the Editor, and implement base file format for maps (accessible only for developers at the moment)
- Improve the logic of AI defensive tactics
- Rework multiple dialogs, fix and speed up several rendering issues
- Over _**30**_ issues have been closed since the 1.0.10 release

Full list of changes can be found [here](https://github.com/ihhub/fheroes2/wiki/Change-Log).</pre>
</details>

### CODE REVIEW

**Comment by p-linnane** [comment]
@ihhub Would you mind helping to debug this build failure?

**Comment by ihhub** [comment]
Hi @p-linnane , I don't have macOS machine at the moment but from the logs I can see something is wrong with translation generation, in particular:
```bash
  sed -e '1,20 s/UTF-8/CP1252/' de.po | iconv -f utf-8 -t CP1252 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o de.mo --no-convert; else msgfmt - -o de.mo; fi
  sed -e '1,20 s/UTF-8/CP1252/' dk.po | iconv -f utf-8 -t CP1252 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o dk.mo --no-convert; else msgfmt - -o dk.mo; fi
  sed -e '1,20 s/UTF-8/CP1252/' es.po | iconv -f utf-8 -t CP1252 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o es.mo --no-convert; else msgfmt - -o es.mo; fi
  /usr/bin/ranlib libsmacker.a
  sed -e '1,20 s/UTF-8/CP1252/' fr.po | iconv -f utf-8 -t CP1252 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o fr.mo --no-convert; else msgfmt - -o fr.mo; fi
  sed -e '1,20 s/UTF-8/CP1250/' hu.po | iconv -f utf-8 -t CP1250 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o hu.mo --no-convert; else msgfmt - -o hu.mo; fi
  sed -e '1,20 s/UTF-8/CP1252/' it.po | iconv -f utf-8 -t CP1252 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o it.mo --no-convert; else msgfmt - -o it.mo; fi
  sed -e 'y/äëïöőüűÄËÏŐÖÜŰ/aeioouuAEIOOUU/' lt.po | iconv -f utf-8 -t ascii//TRANSLIT | msgfmt - -o lt.mo
  sed -e '1,20 s/UTF-8/CP1252/' nb.po | iconv -f utf-8 -t CP1252 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o nb.mo --no-convert; else msgfmt - -o nb.mo; fi
  sed -e '1,20 s/UTF-8/CP1252/' nl.po | iconv -f utf-8 -t CP1252 | if msgfmt --help | grep -q no-convert >/dev/null 2>/dev/null; then msgfmt - -o nl.mo --no-convert; else msgfmt - -o nl.mo; fi
  <stdin>:2763: end-of-line within string
  <stdin>:3830: keyword "e" unknown
  <stdin>:3830:15: syntax error
  iconv: warning: invalid characters: 679
  msgfmt: found 3 fatal errors
  make[3]: *** [lt.mo] Error 1
```

I believe that this is a problem with installed packages (different version, perhaps). We also build macOS app using CMake (see [this workflow](https://github.com/ihhub/fheroes2/blob/master/.github/workflows/cmake.yml)). macos-latest is 12.7.2 according to [GitHub Runners documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners) and to output of our builds. The failed build is on macOS 14.

Therefore, I suggest to run the full pipeline and see which flavor of macOS fails. If all of them then something is wrong with fheroes2 source files, if only 1 or 2 then the problem lies in a build setup.

**Comment by p-linnane** [comment]
This appears to only be affecting macOS 14. All other versions completed successfully.

**Comment by ihhub** [comment]
Hi @p-linnane , the possible solution was introduced in [this pull request](https://github.com/ihhub/fheroes2/pull/8278). You can apply the changes to proceed with the compilation. Alternatively, we have to wait for the new fheroes2 release which is going to be on 7th February.

**Comment by p-linnane** [comment]
Thanks for letting me know @ihhub. I will push that patch to this PR.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
