### PR TITLE
ansible 2.9.1

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — COMMENTED** [review]
you might also need to try to upgrade the python dependencies as well.

**Comment by dawidd6** [comment]
Is there any tool that could help with that?

**Comment by chenrui333** [comment]
To my knowledge, there is no tool for managing those dependencies changes (I also asked Eric on this too, :) ), but we can ask in the slack.

**Comment by dawidd6** [comment]
Upgraded the dependencies, I think it's all of them.

**Pull request closed without merging**
