### PR TITLE
librealsense 2.9.0

### PR DESCRIPTION
**Pull request by OrganicIrradiation**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
2.9.0 just came out if you want to make this a version upgrade too :)

also it needs an alias added `ln -s ../Formula/librealsense.rb Aliases/librealsense@2`

**Comment by OrganicIrradiation** [comment]
Bumping to librealsense 2.9.0!

**Comment by ilovezfs** [comment]
Thanks @OrganicIrradiation! Shipped.

**Comment by ilovezfs** [comment]
@OrganicIrradiation you should update your GitHub profile to associate the email address you're using for commits otherwise the contributor stats don't show up correctly.

**Comment by OrganicIrradiation** [comment]
Thanks @ilovezfs, I've added/updated my profile so hopefully it accounts for the contribution.

**Pull request closed without merging**
