### PR TITLE
oq 1.3.3

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Automated bump.

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by Porkepix** [comment]
Read the previous messages/threads from log, but is the `pcre` dependency still needed for the bottling process (not sure I understood why was it needed), if yes, can it use `pcre2` instead?

I wanted to check also for the requirement of other dependencies, but without information I guess that's needed even at runtime :)

**Comment by Blacksmoke16** [comment]
@Porkepix It's a dependency for the runtime of crystal itself so I'm pretty sure it's still needed given the resulting binary will link it. And Crystal is currently using the 1.x version of PCRE, so we're unable to update the dep to `pcre2` either.

**Comment by Porkepix** [comment]
> @Porkepix It's a dependency for the runtime of crystal itself so I'm pretty sure it's still needed given the resulting binary will link it. And Crystal is currently using the legacy 8.x version of PCRE, so we're unable to update the dep to `pcre2` either.

But considering it's a crystal dependency, shouldn't the fact the formula depends on crystal bring its runtime dependencies with it, rather than having to specify them here on the formula? I mean, every formula shouldn't need to know what are crystal dependencies, just that they depends on crystal, right?

**Comment by Blacksmoke16** [comment]
My thinking was the `crystal` itself is only a build dependency, so it, nor any of its dependencies, would be installed by default if you're not building from source. Because of this, `oq` wouldn't have its runtime dependencies available if they weren't explicitly declared in `oq`'s formula.

**Comment by Porkepix** [comment]
> My thinking was the `crystal` itself is only a build dependency, so it, nor any of its dependencies, would be installed by default if you're not building from source. Because of this, `oq` wouldn't have its runtime dependencies available if they weren't explicitly declared in `oq`'s formula.

Okay, didn't thought of Crystal as a compiled language at first, and then I would have think these dependencies would be linked and embedded directly to the binary, rather than need them as static dependencies.

**Comment by Blacksmoke16** [comment]
Yea, ideally i could statically build the binary and then not require the end user to have the libs available as dynamic libraries. However this just isn't possible due to macOS not supporting static linking. So is what it is :shrug:.

https://developer.apple.com/library/archive/qa/qa1118/_index.html

**Pull request closed without merging**
