### PR TITLE
irssi 1.2.0

### PR DESCRIPTION
**Pull request by FrankSansC**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by FrankSansC** [comment]
Hmmm... Maybe the 'inreplace' is still needed for High Sierra?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@FrankSansC not sure what to think about that error at the moment, lets let it rerun the ci and see if it reoccurs

**Comment by javian** [comment]
Issue was seen here #35864 as well but not resolved.

**Pull request closed without merging**
