### PR TITLE
octant 0.16.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> go run build.go web-build
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://build-artifactory.eng.vmware.com/api/npm/npm/latest-version/-/latest-version-5.1.0.tgz failed, reason: getaddrinfo ENOTFOUND build-artifactory.eng.vmware.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by wwitzel3** [comment]
0.16.2 is released and has this fixed

**Comment by chenrui333** [comment]
> 0.16.2 is released and has this fixed

Thanks, I will submit a new PR on this.

**Comment by chenrui333** [comment]
relates to #65406

**Pull request closed without merging**
