### PR TITLE
zsh-completions 0.31.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by equal-l2** [comment]
```
==> brew linkage --test termius
==> FAILED
Broken dependencies:
  /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (libyaml)
```

**Comment by chenrui333** [comment]
Seems working fine in my local install.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Seems like `brew linkage` continuously failed
```
03:51:38 ==> brew linkage --test termius
03:51:39 ==> FAILED
03:51:39 Broken dependencies:
03:51:39   /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (libyaml)
```

**Comment by EricFromCanada** [comment]
@BrewTestBot Test this please

**Pull request merged**
