### PR TITLE
llvm@11, chapel: migrate to Python 3.10

### PR DESCRIPTION
**Pull request by XuehaiPan**
Migrate `llvm@11` family to Python 3.10. See https://github.com/Homebrew/homebrew-core/pull/87075#issuecomment-988102123

### CODE REVIEW

**Comment by carlocab** [comment]
Needs `CI-long-timeout`. Let's wait for the CI queue to clear up a bit before doing that though.

**Comment by iMichka** [comment]
```
2021-12-14T06:18:57.1166640Z [34m==>[0m [1mbrew audit chapel --online --git --skip-style[0m
2021-12-14T06:19:05.7617800Z [31m==>[0m [1m[31mFAILED[0m[0m
2021-12-14T06:19:05.7629790Z ##[group]Full audit chapel --online --git --skip-style output
2021-12-14T06:19:05.7630420Z chapel:
2021-12-14T06:19:05.7631250Z   * Binaries built for a non-native architecture were installed into chapel's prefix.
2021-12-14T06:19:05.7631930Z     The offending files are:
2021-12-14T06:19:05.7632930Z       /opt/homebrew/Cellar/chapel/1.25.0_2/libexec/third-party/qthread/qthread-src/installed/lib/libqthread.19.dylib	(x86_64)
2021-12-14T06:19:05.7633810Z     Unexpected universal binaries were found.
2021-12-14T06:19:05.7634300Z     The offending files are:
2021-12-14T06:19:05.7635420Z       /opt/homebrew/Cellar/chapel/1.25.0_2/libexec/third-party/chpl-venv/install/chpldeps/markupsafe/_speedups.cpython-310-darwin.so
2021-12-14T06:19:05.7636400Z   * Libraries were compiled with a flat namespace.
2021-12-14T06:19:05.7636940Z     This can cause linker errors due to name collisions, and
2021-12-14T06:19:05.7637460Z     is often due to a bug in detecting the macOS version.
2021-12-14T06:19:05.7638520Z       /opt/homebrew/Cellar/chapel/1.25.0_2/libexec/third-party/gmp/install/darwin-arm64-native-clang-none/lib/libgmp.10.dylib
2021-12-14T06:19:05.7639920Z       /opt/homebrew/Cellar/chapel/1.25.0_2/libexec/third-party/gmp/install/darwin-arm64-native-llvm-none/lib/libgmp.10.dylib
2021-12-14T06:19:05.7649500Z [31mError:[0m 2 problems in 1 formula detected
```

**Comment by iMichka** [comment]
`chapel` was fixed in #91257. Rebased.

**Comment by iMichka** [comment]
```
Collecting breathe==4.30.0
  Downloading breathe-4.30.0.tar.gz (82 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/Cellar/chapel/1.25.1_1/libexec/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-6nsocf1v
       cwd: /private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/
  Complete output (23 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/setup.py", line 10, in <module>
      from breathe import __version__
    File "/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/breathe/__init__.py", line 1, in <module>
      from . import directives
    File "/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/breathe/directives.py", line 1, in <module>
      from breathe.directive.base import create_warning
    File "/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/breathe/directive/base.py", line 1, in <module>
      from breathe.finder.factory import FinderFactory
    File "/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/breathe/finder/__init__.py", line 1, in <module>
      from breathe.project import ProjectInfo
    File "/private/tmp/pip-install-aji4udoc/breathe_f963b1e178e4496e97476b20a3cc4462/breathe/project.py", line 4, in <module>
      from sphinx.application import Sphinx
    File "/opt/homebrew/Cellar/chapel/1.25.1_1/libexec/third-party/chpl-venv/build/build-venv/lib/python3.10/site-packages/sphinx/application.py", line 31, in <module>
      from sphinx.config import Config
    File "/opt/homebrew/Cellar/chapel/1.25.1_1/libexec/third-party/chpl-venv/build/build-venv/lib/python3.10/site-packages/sphinx/config.py", line 21, in <module>
      from sphinx.util import logging
    File "/opt/homebrew/Cellar/chapel/1.25.1_1/libexec/third-party/chpl-venv/build/build-venv/lib/python3.10/site-packages/sphinx/util/__init__.py", line 41, in <module>
      from sphinx.util.typing import PathMatcher
    File "/opt/homebrew/Cellar/chapel/1.25.1_1/libexec/third-party/chpl-venv/build/build-venv/lib/python3.10/site-packages/sphinx/util/typing.py", line 37, in <module>
      from types import Union as types_Union
  ImportError: cannot import name 'Union' from 'types' (/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/types.py)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/95/76/0c9adb4b20082091a0236e558797455ce819b0d9db86570c9a01139c66e2/breathe-4.30.0.tar.gz#sha256=363dec85abc0c4b3f22628b0cf82cc2dc46c4397d8a18312d1a7d1365d49b014 (from https://pypi.org/simple/breathe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement breathe==4.30.0 (from versions: 0.7.0, 0.7.5, 1.0.0, 1.1.0, 1.2.0, 2.0.0, 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.8.0, 4.9.0, 4.9.1, 4.10.0, 4.11.0, 4.11.1, 4.12.0, 4.13.0, 4.13.0.post0, 4.13.1, 4.14.0, 4.14.1, 4.14.2, 4.15.0, 4.16.0, 4.17.0, 4.18.0, 4.18.1, 4.19.0, 4.19.1, 4.19.2, 4.20.0, 4.21.0, 4.22.0, 4.22.1, 4.23.0, 4.24.0, 4.24.1, 4.25.0, 4.25.1, 4.26.0, 4.26.1, 4.27.0, 4.28.0, 4.29.0, 4.29.1, 4.29.2, 4.30.0, 4.31.0)
ERROR: No matching distribution found for breathe==4.30.0
make[2]: *** [/opt/homebrew/Cellar/chapel/1.25.1_1/libexec/third-party/chpl-venv/install/chpldeps/__main__.py] Error 1
make[1]: *** [test-venv] Error 2
make: *** [third-party-test-venv] Error 2
```

**Comment by iMichka** [comment]
There was a commit to sphinx to fix this: https://github.com/sphinx-doc/sphinx/commit/36e06d67c9e4ef6d3d0881aac76066b5c1982ccd

Need to check how this is can be fixed in chapel first. @Maxrimus, @bradcray, @mppf or @ronawho might know how to help.
We are trying to migrate to Python 3.10 and are getting the error you can see in the message just above.

**Comment by lydia-duncan** [comment]
Hi - sorry, most of the folks you've pinged are on holiday break right now.  I don't know much about homebrew formulas and such, but it does look like updating the Sphinx version we rely on to 4.3.2 doesn't cause problems for us and should include the commit you mentioned.

So I think modifying line 193 and 215 to use 4.3.2 would be okay?

**Comment by lydia-duncan** [comment]
I've opened https://github.com/chapel-lang/chapel/pull/18894 on our repo, if that helps with adjusting the patches at the end of the formula

**Comment by lydia-duncan** [comment]
In looking at the failure on that PR, this is not just a simple change, I believe we need to update a separate repository we distribute so that it's compatible with the new version of Sphinx.  I'll be taking a deeper look, but since the majority of our team are on holiday break, it might not be able to be reviewed until the new year.  What's your timeframe on making this change?

**Comment by carlocab** [comment]
I don't think this is urgent. It can wait till people have come back from holidays.

**Comment by mlevkov** [comment]
Hello, just curious to know if this is on the plate to be resolved soon? I'd very much appreciate your input. Thank you all for all you do.

**Comment by lydia-duncan** [comment]
Yup, I've got the update to our alternate repo made and have a PR incorporating it into our main repo.  I expect it to go in soon, thank you for your patience :)

**Comment by lydia-duncan** [comment]
https://github.com/chapel-lang/chapel/pull/18894 has been merged and appears to be passing our nightly testing so far.  Only one of the file changes is relevant to homebrew, the adjustments to `third-party/chpl-venv/chpldoc-requirements.txt`.  

@mppf also merged a PR this morning to integrate the patches we'd included as part of the Chapel formula into the main repo itself, which performs the split of that file into three files and includes the changes from my PR: https://github.com/chapel-lang/chapel/pull/18926

I'd advise waiting until that second PR has had a night of testing on it but I think we're probably in good shape.  Is there anything more we can do to help?

**Comment by lydia-duncan** [comment]
Second PR was clean!

**Comment by mlevkov** [comment]
Is this still being worked on?

**Comment by XuehaiPan** [comment]
> Is this still being worked on?

We're waiting for the next version release of `chapel`.

**Comment by mppf** [comment]
The next Chapel release (1.26) will be in the March/April timeframe. In the meantime, it would be possible to update the Chapel formula to include https://github.com/chapel-lang/chapel/pull/18894 and https://github.com/chapel-lang/chapel/pull/18926 as patches.

However, it is unclear to me how urgent this is. If it is important to do before Chapel 1.26, I don't know who will update the formula to include the patches from those PRs.

**Comment by iMichka** [comment]
I tried to apply the patches to `chapel` 1.25.1, but some of them don't apply.
So unless someone provides backported patches, it might be hard to do.
If the patches are given, I can add them to the formula and trigger a rebuild.

But we might wait for March/April. I would like to move the Python 3.10 migration forward, but I also know this takes time so we have plenty of other formulae to fix until this one is ready.

**Comment by lydia-duncan** [comment]
Can you go more into what you tried and how it didn't work?

**Comment by XuehaiPan** [comment]
> So unless someone provides backported patches, it might be hard to do.

These patches are already hosted on GitHub. They can download by `<PR URL>.patch` or `<PR URL>.diff`:

- https://github.com/chapel-lang/chapel/pull/18894.patch
- https://github.com/chapel-lang/chapel/pull/18926.patch

**Comment by XuehaiPan** [comment]
> Can you go more into what you tried and how it didn't work?

Install `chapel` 1.25.1 with patch 18894 and 18926:

```diff
diff --git a/Formula/chapel.rb b/Formula/chapel.rb
index 0eebb5cba99..fddf02c3b27 100644
--- a/Formula/chapel.rb
+++ b/Formula/chapel.rb
@@ -4,6 +4,7 @@ class Chapel < Formula
   url "https://github.com/chapel-lang/chapel/releases/download/1.25.1/chapel-1.25.1.tar.gz"
   sha256 "0c13d7da5892d0b6642267af605d808eb7dd5d4970766f262f38b94fa2405113"
   license "Apache-2.0"
+  revision 1
 
   bottle do
     sha256 arm64_monterey: "e11d484b8dbeb19649b46ebadb1ff063e79a3fa7c3e1befc258c6fd28a4712a2"
@@ -16,11 +17,21 @@ class Chapel < Formula
 
   depends_on "gmp"
   depends_on "llvm@11"
-  depends_on "python@3.9"
+  depends_on "python@3.10"
 
   # can be removed after https://github.com/chapel-lang/chapel/pull/18880 merged
   patch :DATA
 
+  patch do
+    url "https://github.com/chapel-lang/chapel/pull/18894.patch"
+    sha256 "ff27ffcd76aa89b3b7722b02918bfe3d315469b398bdc9b47e7ee2285246ebe6"
+  end
+
+  patch do
+    url "https://github.com/chapel-lang/chapel/pull/18926.patch"
+    sha256 "c888619ca8e7dc29cb054b137af82b0d9ace42dc3e040182fdc98eaede39f48a"
+  end
+
   def install
     libexec.install Dir["*"]
     # Chapel uses this ENV to work out where to install.
diff --git a/Formula/llvm@11.rb b/Formula/llvm@11.rb
index 1e76fbe2e94..b7ce2827671 100644
--- a/Formula/llvm@11.rb
+++ b/Formula/llvm@11.rb
@@ -5,7 +5,7 @@ class LlvmAT11 < Formula
   sha256 "74d2529159fd118c3eac6f90107b5611bccc6f647fdea104024183e8d5e25831"
   # The LLVM Project is under the Apache License v2.0 with LLVM Exceptions
   license "Apache-2.0" => { with: "LLVM-exception" }
-  revision 3
+  revision 4
 
   # This should be removed when LLVM 13 is released, so we only check the
   # current version (the `llvm` formula) and one major version before it
@@ -35,7 +35,7 @@ class LlvmAT11 < Formula
   # See: Homebrew/homebrew-core/issues/35513
   depends_on "cmake" => :build
   depends_on "swig" => :build
-  depends_on "python@3.9"
+  depends_on "python@3.10"
 
   uses_from_macos "libedit"
   uses_from_macos "libffi", since: :catalina
```

Got:

```
==> Installing chapel
==> Patching
==> Applying 18894.patch
patching file third-party/chpl-venv/chpldoc-requirements.txt
Hunk #1 succeeded at 1 with fuzz 2.
patching file third-party/chpl-venv/chpldoc-requirements.txt
Hunk #1 succeeded at 6 with fuzz 1.
patching file third-party/chpl-venv/chpldoc-requirements.txt
Hunk #1 FAILED at 4.
1 out of 1 hunk FAILED -- saving rejects to file third-party/chpl-venv/chpldoc-requirements.txt.rej
can't find file to patch at input line 101
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|
|From 4b5f1ea7e41d1b0891e1c909a5f33daecaf6e937 Mon Sep 17 00:00:00 2001
|From: Lydia Duncan <lydia-duncan@users.noreply.github.com>
|Date: Thu, 6 Jan 2022 15:22:46 -0600
|Subject: [PATCH 4/4] Replace use of distutils.spawn.find_executable with
| shutils.which in skipif
|
|distutils is deprecated in Python 3.10 and will be removed in Python 3.12.
|shutils.which has existed since Python 3.3 so should be usable in its place
|
|----
|Signed-off-by: Lydia Duncan <lydia-duncan@users.noreply.github.com>
|---
| .../library/packages/ProtobufProtocolSupport/anyRunner.skipif | 4 ++--
| 1 file changed, 2 insertions(+), 2 deletions(-)
|
|diff --git a/test/library/packages/ProtobufProtocolSupport/anyRunner.skipif b/test/library/packages/ProtobufProtocolSupport/anyRunner.skipif
|index 17da6c43929..b46578a86a9 100755
|--- a/test/library/packages/ProtobufProtocolSupport/anyRunner.skipif
|+++ b/test/library/packages/ProtobufProtocolSupport/anyRunner.skipif
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
```

**Comment by mppf** [comment]
Right I would expect that `git` can apply the patches in those PRs cleanly if you cherry pick them starting from the 1.25.1 release branch. 

But also note that the 1.25.1 chapel.rb has patches at the bottom. To get everything to apply cleanly, we need to regenerate the patches for chapel.rb to include the changes needed in the formula from https://github.com/chapel-lang/chapel/pull/18894 and https://github.com/chapel-lang/chapel/pull/18926 . .

The PR https://github.com/chapel-lang/chapel/pull/18880 has a summary of patches that were included in the formula. Going to the individual PRs and grabbing commit shas led me to these commands:

```
# starting from a git clone of chapel main
git checkout 1.25.1
# these commits are from PR 18820 (was already in formula)
git cherry-pick 0b994b00b165463bdd57fbad127beac0e54a1371 d928be2a849d74dd35f7e20aff5c5fceb60cffce
# these commits are from PR 18857 (was already in formula)
git cherry-pick a70bf57c6f1cb1a25b6a597a61bfbb14a7b9cc96
# these commits are from PR 18894 (was not yet in formula)
git cherry-pick 007373efb703c5b9ab0e4ddb326e7088292d4e67 aa59486ece5d884b7b3d5075b43b1583536984dd 9e49eba6f11419796798bc979a15fed69632f42a 4b5f1ea7e41d1b0891e1c909a5f33daecaf6e937
# these commits are are from PR 18926 (a similar change was in the formula)
git cherry-pick 2e8711055fd240c4a469083684094712f7a2462e af29e6e1c5b4e5bcdb5888f1e9bd64060b031647 a6f377e6a457d46e7e05ff829767d5eb5200e205 ab8bd0368a33d6bc3247b7b40694bc0bf944c9ef 0863f384eb3abd636de266c7803950937c73f9aa cb7bdf64cf18f5a5dad69031d7b79e168fdca2d5
```

From there I grabbed the chapel.rb from this PR and made these changes:
 * removed the diffs after the `__END__`
 * used `git diff 1.25.1 >> chapel.rb` to regenerate them. Please note that this diff is sensitive to spaces vs tabs because it changes Makefile rules.
 * changed lines like `with_env(CHPL_PIP_INSTALL_PARAMS: "--no-binary :all:")` to `with_env(CHPL_PIP_FROM_SOURCE: "1")` as per the note in PR https://github.com/chapel-lang/chapel/pull/18926

I have uploaded the resulting chapel.rb to https://gist.github.com/mppf/e3a77526d7d6e1795150d8f36d8fab45 but I have not tested it at all. Hope that is helpful to you & you can either re-run the commands above or use that file.

**Comment by mppf** [comment]
Oh, I think I forgot to include one commit from PR https://github.com/chapel-lang/chapel/pull/18880 in the above -- https://github.com/chapel-lang/chapel/pull/18880/commits/60df1925ad6ee77e774205054fd0022f2755474c . I will update it.

**Comment by XuehaiPan** [comment]
I removed some unrelated diffs in patch <https://gist.github.com/mppf/32869664c6bb251dcd1101d783763780>. Then, I can build `chapel` 1.25.1 with Python 3.10 successfully in Ubuntu 20.04 docker container.

For testing, I got:

```console
$ brew install -s llvm@11
$ brew install -s chapel

$ brew test chapel
==> Testing chapel
==> util/test/checkChplInstall
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/chapel/test.01.checkChplInstall:
[Info] Compiling $CHPL_HOME/examples/hello6-taskpar-dist.chpl
[Info] Compiling with CHPL_TARGET_COMPILER=
[Fail] Test job failed to compile - Chapel is not installed correctly
[Fail] Compilation output:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/util/chplenv/printchplenv.py", line 48, in <module>
    from chplenv import *
  File "/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/util/chplenv/chplenv.py", line 1, in <module>
    import chpl_cpu
  File "/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/util/chplenv/chpl_cpu.py", line 9, in <module>
    import chpl_comm, chpl_compiler, chpl_platform, overrides
  File "/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/util/chplenv/chpl_compiler.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
error: 'CHPL_HOME=/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec CHPL_RUNTIME_INCL=/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/runtime/include CHPL_RUNTIME_LIB=/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/lib CHPL_THIRD_PARTY=/home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/third-party CHPLENV_SUPPRESS_WARNINGS=true /home/linuxbrew/.linuxbrew/Cellar/chapel/1.25.1_1/libexec/util/printchplenv --all --internal --no-tidy --simple' did not run successfully
Error: chapel: failed
An exception occurred within a child process:
  BuildError: Failed executing: util/test/checkChplInstall
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2309:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2245:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2245:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chapel.rb:81:in `block (3 levels) in <class:Chapel>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:588:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chapel.rb:80:in `block (2 levels) in <class:Chapel>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chapel.rb:79:in `block in <class:Chapel>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2109:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:588:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2108:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:948:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2107:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2360:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2101:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

**Comment by XuehaiPan** [comment]
May need label `CI-long-timeout`. All tests passed on my docker container (Ubuntu 20.04).

**Comment by mppf** [comment]
@XuehaiPan -

Regarding

> distutils.core.setup            --> setuptools.setup
> distutils.spawn.find_executable --> shutil.which

I wouldn't expect that you need to patch anything in third-party/llvm/llvm-src since this directory will not be used since Chapel is using the Homebrew LLVM 11.

Also we would appreciate it upstream if you can make a PR with the changes to util/chplenv.

Regarding this

> I removed some unrelated diffs in patch https://gist.github.com/mppf/32869664c6bb251dcd1101d783763780. 

Can you say more about which diffs you removed from there? Thanks

**Comment by XuehaiPan** [comment]
@mppf

> I wouldn't expect that you need to patch anything in `third-party/llvm/llvm-src` since this directory will not be used since Chapel is using the Homebrew LLVM 11.

Get it. I will remove them then.

> Also we would appreciate it upstream if you can make a PR with the changes to `util/chplenv`.

- chapel-lang/chapel#19168

> Regarding this
> > I removed some unrelated diffs in patch https://gist.github.com/mppf/32869664c6bb251dcd1101d783763780.
> Can you say more about which diffs you removed from there? Thanks

Files where their paths start with `/test/*` (do not exist in the release tar file).

**Comment by mppf** [comment]
Sounds great, thanks for clarifying

**Comment by XuehaiPan** [comment]
All checks have passed.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Nice. Thanks all. I naively tried to apply the patches above, but I see there was more work to get things done correctly. Thanks all!

**Comment by carlocab** [comment]
Can we move the embedded Chapel patch to [formula-patches](https://github.com/Homebrew/formula-patches)? It can wait until this is merged.

**Pull request closed without merging**
