### PR TITLE
aws-iam-authenticator 0.6.11

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
I think we have livecheck for a reason.

**Comment by chenrui333** [comment]
also gonna file an upstream issue for raise some awareness.

**Comment by osalbahr** [comment]
> I think we have livecheck for a reason.

I agree. I am also buzzled by what happened. `brew bump --open-pr` logs:

```console
...
==> aws-iam-authenticator
Current formula version:  0.6.10
Latest livecheck version: 0.6.11
Latest Repology version:  0.6.11
Open pull requests:       none
Closed pull requests:     none
==> Cloning https://github.com/kubernetes-sigs/aws-iam-authenticator.git
Cloning into '/Users/dracula/Library/Caches/Homebrew/aws-iam-authenticator--git'...
==> Checking out tag v0.6.11
HEAD is now at 08f0ebc9 Merge pull request #615 from nnmin-aws/nnmin-rel
==> replace /tag:(\s+")v0.6.10(?=")/ with "tag:\\1v0.6.11\\2"
==> replace "ea9bcaeb5e62c110fe326d1db58b03a782d4bdd6" with "08f0ebc973028f5b77c
M	Formula/aws-iam-authenticator.rb
Switched to a new branch 'bump-aws-iam-authenticator-0.6.11'
[bump-aws-iam-authenticator-0.6.11 22fe7bc5e49] aws-iam-authenticator 0.6.11
 1 file changed, 2 insertions(+), 2 deletions(-)
remote: 
remote: Create a pull request for 'bump-aws-iam-authenticator-0.6.11' on GitHub by visiting:        
remote:      https://github.com/osalbahr/homebrew-core/pull/new/bump-aws-iam-authenticator-0.6.11        
remote: 
To https://github.com/osalbahr/homebrew-core.git
 * [new branch]              bump-aws-iam-authenticator-0.6.11 -> bump-aws-iam-authenticator-0.6.11
branch 'bump-aws-iam-authenticator-0.6.11' set up to track 'https://******@github.com/osalbahr/homebrew-core.git/bump-aws-iam-authenticator-0.6.11'.
https://github.com/Homebrew/homebrew-core/pull/138578
...
```

But when I run it manually (now that GitHub is no longer mad at me):

```console
$ brew bump aws-iam-authenticator
==> aws-iam-authenticator
Current formula version:  0.6.10
Latest livecheck version: 0.6.10
Latest Repology version:  0.6.11
Open pull requests:       none
Closed pull requests:     aws-iam-authenticator 0.6.10 (https://github.com/Homebrew/homebrew-core/pull/135345)
```

Note the difference in the "Latest livecheck version" lines.

**Comment by chenrui333** [comment]
they have updated the release notes for 0.6.11, reopen the PR.

**Comment by chenrui333** [comment]
> > I think we have livecheck for a reason.
> 
> I agree. I am also buzzled by what happened. `brew bump --open-pr` logs:

that is my oversight, should be good now, thanks for opening this PR 👍

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
