### PR TITLE
pyenv: fix add option to install bash_completions

### PR DESCRIPTION
**Pull request by rgant**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
Any reason to even provide an option here?

**Comment by rgant** [comment]
All the examples I looked at ([git](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb#L15), [node](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node.rb#L17)) included that option, so I was consistent with that. I don't see any reason not to include it.

**Comment by DomT4** [comment]
> I don't see any reason not to include it.

Most options in Homebrew end up being almost entirely unused, and thus end up being code bulk for the sake of code bulk. Unless the completions are incompatible with the system version of `bash` my inclination would be to include them by default, without an opt-out, but I'll defer to @ilovezfs.

**Comment by rgant** [comment]
I have almost no understanding of how all of this works, but as best I can tell the default for an option without-* is to include the option. Certainly for me it installs with bash completions without my adding any special flags about it to the brew install command.

**Comment by ilovezfs** [comment]
Is this an option you're planning on using yourself? If so, why?

**Comment by rgant** [comment]
It's not an option I would use. Not having it also not a case which I have tested. To me it seems more important to follow conventions than to save 3 lines of boilerplate code. If you want to remove install options, that sounds like a separate ticket.

**Comment by rgant** [comment]
I just noticed that there are other possible completions included with pyenv now fish and zsh. Seems like that is something we should discuss adding or not.

**Comment by ilovezfs** [comment]
@rgant convention is not to add options for their own sake, so unless you had a particular use case in mind for yourself here, I'm going to pass on this. But thanks for the PR nonetheless!

>I just noticed that there are other possible completions included with pyenv now fish and zsh. 

Yep, if someone wants to add those to the formula that would be fine.

**Comment by rgant** [comment]
To be clear, this pull requests adds installing bash_completions to pyenv formula. It wraps that in an options check because that is how git and node do it. Those are two separate things. You've closed both of them, I can remove the options check if that is what is desired, but please add the completions so I don't have to do this manually every time pyenv updates.

**Comment by ilovezfs** [comment]
Ah OK. Go ahead and add fish and zsh too please :)

**Comment by rgant** [comment]
Well it looks like I forgot to rebase. I might just close this and do a new pull request

**Comment by ilovezfs** [comment]
@rgant just `git reset origin/master; git checkout .`, commit and push -f

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @rgant! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
