### PR TITLE
vapoursynth: split optional plugins from core

### PR DESCRIPTION
**Pull request by CL-Jeremy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Continuing with the discussion at #36689, now taking the core-with-add-ons approach, using the respective configure options suggested by @dubhater.

The postinstall approach might not be ideal in this case, but I honestly could not come up with something better. I have actually taken a look at `keg.rb` and do not believe `vapoursynth` should be added to the exception list for those formulae, which are mainly programming languages with a well-maintained package ecosystem. If only there were a general-purpose flag to create the folder `$HOMEBREW_PREFIX/lib/vapoursynth` before `brew link` it would have been perfect to let everything stay where they are (just a single `"--with-plugindir=#{HOMEBREW_PREFIX}/lib/vapoursynth"` would suffice).

As with caveats and stuff, I have done it to meet my own understanding of aesthetics, so suggestions on that are highly welcome (if there is free time for that). I noticed that several formulae are using markdown-like backticks for quoting commands, which seems pretty non-sensical to me.
caveats

### CODE REVIEW

**Comment by CL-Jeremy** [comment]
Hmm... this looks weird to me. I cannot tell which command in the CI uninstalled `zimg`, but that definitely does not happen on my own machines...

```
==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/38217
Homebrew/brew 2.0.5-36-ga4deff262 (Merge pull request #5909 from Homebrew/dependabot/bundler/docs/jekyll-watch-2.2.1)
homebrew/core origin/master 3a73768744 (ffsend: update 0.2.38 bottle.)
homebrew/core HEAD 5ed41b092e (fix a typo)

==> brew doctor

==> brew --env

==> brew config

==> brew readall --aliases homebrew/core

==> brew uses --recursive vapoursynth

==> brew fetch --retry autoconf automake gdbm libtool nasm openssl pkg-config python readline sqlite xz zimg

==> brew fetch --retry vapoursynth --build-bottle --force

==> brew install --only-dependencies --verbose --build-bottle vapoursynth

==> brew install --verbose --build-bottle vapoursynth

==> brew audit vapoursynth --online

==> brew style vapoursynth

==> brew bottle --verbose --json vapoursynth

==> brew bottle --merge --write --no-commit ./vapoursynth--45.1_1.mojave.bottle.json

==> brew uninstall --force vapoursynth

==> brew uninstall --force autoconf automake libtool nasm pkg-config

==> brew install --only-dependencies ./vapoursynth--45.1_1.mojave.bottle.tar.gz

==> brew install ./vapoursynth--45.1_1.mojave.bottle.tar.gz

==> brew linkage --test vapoursynth

==> brew install --only-dependencies --include-test vapoursynth

==> brew test vapoursynth --verbose

==> brew fetch --retry mps-youtube

==> brew install --only-dependencies mps-youtube

==> brew install mps-youtube

==> brew install --only-dependencies mps-youtube

==> brew linkage --test mps-youtube

==> brew install --only-dependencies --include-test mps-youtube

==> brew test --verbose mps-youtube

==> brew install --only-dependencies mpv

==> brew linkage --test mpv

==> brew install --only-dependencies --include-test mpv

==> brew test --verbose mpv

==> brew fetch --retry mvtools

==> brew install --only-dependencies mvtools

==> brew install mvtools

==> brew install --only-dependencies mvtools

==> brew linkage --test mvtools

==> brew install --only-dependencies --include-test mvtools

==> brew test --verbose mvtools

==> brew uninstall --force gdbm openssl python readline sqlite xz zimg

==> brew uses --recursive vapoursynth-imwri

==> brew fetch --retry autoconf automake cmake doxygen gdbm ilmbase imagemagick intltool libde265 libheif libomp libtool meson ninja openexr openssl python readline shared-mime-info sphinx-doc sqlite xz zimg

==> brew fetch --retry vapoursynth-imwri --build-bottle --force

==> brew install --only-dependencies --verbose --build-bottle vapoursynth-imwri

==> brew install --verbose --build-bottle vapoursynth-imwri

==> brew audit vapoursynth-imwri --online --new-formula

==> brew bottle --verbose --json vapoursynth-imwri

==> brew bottle --merge --write --no-commit ./vapoursynth-imwri--45.1.mojave.bottle.json

==> brew uninstall --force vapoursynth-imwri

==> brew uninstall --force autoconf automake cmake doxygen intltool meson ninja sphinx-doc

==> brew install --only-dependencies ./vapoursynth-imwri--45.1.mojave.bottle.tar.gz

==> brew install ./vapoursynth-imwri--45.1.mojave.bottle.tar.gz

==> brew linkage --test vapoursynth-imwri

==> brew install --only-dependencies --include-test vapoursynth-imwri

==> brew test vapoursynth-imwri --verbose

==> brew uninstall --force vapoursynth-imwri

==> brew uninstall --force gdbm ilmbase imagemagick libde265 libheif libomp libtool openexr openssl python readline shared-mime-info sqlite xz zimg

==> brew uses --recursive vapoursynth-ocr

==> brew fetch --retry autoconf autoconf-archive automake cmake doxygen gdbm libtool openssl python readline sphinx-doc sqlite xz zimg

==> brew fetch --retry vapoursynth-ocr --build-bottle --force

==> brew install --only-dependencies --verbose --build-bottle vapoursynth-ocr

==> brew install --verbose --build-bottle vapoursynth-ocr

==> brew audit vapoursynth-ocr --online --new-formula

==> brew bottle --verbose --json vapoursynth-ocr

==> brew bottle --merge --write --no-commit ./vapoursynth-ocr--45.1.mojave.bottle.json

==> brew uninstall --force vapoursynth-ocr

==> brew uninstall --force autoconf autoconf-archive automake cmake doxygen libtool sphinx-doc

==> brew install --only-dependencies ./vapoursynth-ocr--45.1.mojave.bottle.tar.gz

==> brew install ./vapoursynth-ocr--45.1.mojave.bottle.tar.gz

==> brew linkage --test vapoursynth-ocr

==> brew install --only-dependencies --include-test vapoursynth-ocr

==> brew test vapoursynth-ocr --verbose

==> brew uninstall --force vapoursynth-ocr

==> brew uninstall --force gdbm openssl python readline sqlite xz zimg

==> brew uses --recursive vapoursynth-sub

==> brew fetch --retry ant autoconf autoconf-archive automake cmake doxygen gdbm gobject-introspection libtool meson ninja openssl python readline sphinx-doc sqlite xz yasm

==> brew fetch --retry vapoursynth-sub --build-bottle --force

==> brew install --only-dependencies --verbose --build-bottle vapoursynth-sub

==> brew install --verbose --build-bottle vapoursynth-sub

==> brew audit vapoursynth-sub --online --new-formula

==> brew bottle --verbose --json vapoursynth-sub

==> brew bottle --merge --write --no-commit ./vapoursynth-sub--45.1.mojave.bottle.json

==> brew uninstall --force vapoursynth-sub

==> brew uninstall --force ant autoconf autoconf-archive automake cmake doxygen gobject-introspection libtool meson ninja sphinx-doc yasm

==> brew install --only-dependencies ./vapoursynth-sub--45.1.mojave.bottle.tar.gz

==> brew install ./vapoursynth-sub--45.1.mojave.bottle.tar.gz

==> brew linkage --test vapoursynth-sub

==> brew install --only-dependencies --include-test vapoursynth-sub

==> brew test vapoursynth-sub --verbose
==> FAILED
Testing vapoursynth-sub
/usr/bin/sandbox-exec -f /private/tmp/homebrew20190323-20799-1bpv4ii.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.66.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.5.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.2.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.28.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.14.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.1:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.22/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.19.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.12.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.2.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib:/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib:/Library/Ruby/Gems/2.3.0/gems/power_assert-0.2.6/lib:/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib:/Library/Ruby/Site/2.3.0:/Library/Ruby/Site/2.3.0/x86_64-darwin18:/Library/Ruby/Site/2.3.0/universal-darwin18:/Library/Ruby/Site:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vapoursynth-sub.rb --verbose
==> python3 -c from vapoursynth import core; core.sub
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/vapoursynth.so, 2): Library not loaded: /usr/local/opt/zimg/lib/libzimg.2.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/vapoursynth.so
  Reason: image not found
Error: vapoursynth-sub: failed
```

**Comment by CL-Jeremy** [comment]
Alright, my bad for being really careless this time... sorry for the very long delay.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @CL-Jeremy

**Pull request closed without merging**
