### PR TITLE
jfrog-cli-go 1.26.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
12:35:02 No credentials specified
12:35:02  > git rev-parse --is-inside-work-tree # timeout=10
12:35:02 Fetching changes from the remote Git repository
12:35:02  > git config remote.origin.url https://github.com/Homebrew/homebrew-core/ # timeout=10
12:35:02 Fetching upstream changes from https://github.com/Homebrew/homebrew-core/
12:35:02  > git --version # timeout=10
12:35:02  > git fetch --no-tags --force --progress https://github.com/Homebrew/homebrew-core/ +refs/pull/*:refs/remotes/origin/pr/* # timeout=60
12:45:30 ERROR: Error fetching remote repo 'origin'
12:45:30 hudson.plugins.git.GitException: Failed to fetch from https://github.com/Homebrew/homebrew-core/
```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by scpeters** [comment]
~~~
==> go build -o /usr/local/Cellar/jfrog-cli-go/1.26.0/bin/jfrog jfrog-cli/jfrog/main.go
stat jfrog-cli/jfrog/main.go: no such file or directory
~~~

**Comment by chenrui333** [comment]
Fixed the build and passed the test locally.

**Pull request closed without merging**
