### PR TITLE
gitlab-runner 12.9.0

### PR DESCRIPTION
**Pull request by clementpadovani**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@clementpadovani  looks like the upstream repo has moved to go-modules for the build, do you want to give a try of removing the GOPATH?

**Comment by clementpadovani** [comment]
@chenrui333 it looks all good now! Thanks for the tip

**Comment by chenrui333** [comment]
You might need to do the whole thing, I can help a bit after the work.

**Comment by clementpadovani** [comment]
@chenrui333 we should be golden now with all of the green lights?

**Comment by SMillerDev** [comment]
Can you just squash your commits into one with just the `name version` structure?

**Comment by clementpadovani** [comment]
@SMillerDev done! tests look good, just waiting on the jenkins build

**Comment by chenrui333** [comment]
Thanks @clementpadovani!!

**Pull request closed without merging**
