### PR TITLE
hfstospell 0.5.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
```
==> make install
...
In file included from /usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:53:
/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/parsers/saxparser.h:224:8: error: no template named 'auto_ptr' in namespace 'std'
  std::auto_ptr<_xmlSAXHandler> sax_handler_;
  ~~~~~^
In file included from ZHfstOspeller.cc:27:
In file included from /usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:54:
/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/parsers/textreader.h:260:10: error: no template named 'auto_ptr' in namespace 'std'
    std::auto_ptr<PropertyReader> propertyreader;
    ~~~~~^
In file included from ZHfstOspeller.cc:27:
In file included from /usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:69:
/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/relaxngschema.h:108:8: error: no template named 'auto_ptr' in namespace 'std'
  std::auto_ptr<Impl> pimpl_;
  ~~~~~^
In file included from ZHfstOspeller.cc:27:
In file included from /usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:70:
/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/xsdschema.h:99:8: error: no template named 'auto_ptr' in namespace 'std'
  std::auto_ptr<Impl> pimpl_;
  ~~~~~^
In file included from ZHfstOspeller.cc:27:
In file included from /usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:73:
/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/validators/relaxngvalidator.h:159:8: error: no template named 'auto_ptr' in namespace 'std'
  std::auto_ptr<Impl> pimpl_;
  ~~~~~^
In file included from ZHfstOspeller.cc:27:
In file included from /usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:75:
/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/validators/xsdvalidator.h:149:8: error: no template named 'auto_ptr' in namespace 'std'
  std::auto_ptr<Impl> pimpl_;
  ~~~~~^
6 errors generated.
make: *** [libhfstospell_la-ZHfstOspeller.lo] Error 1
make: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -g -O2 -std=c++2a -I/usr/local/Cellar/libarchive/3.3.3/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.58.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.58.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libsigc++/2.10.1/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.10.1/lib/sigc++-2.0/include -I/usr/local/Cellar/glibmm/2.58.0/include/glibmm-2.4 -I/usr/local/Cellar/glibmm/2.58.0/lib/glibmm-2.4/include -I/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6 -I/usr/local/Cellar/libxml++/2.40.1/lib/libxml++-2.6/include -I/usr/include/libxml2 -g -O2 -std=c++2a -c hfst-ol.cc -o libhfstospell_la-hfst-ol.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -g -O2 -std=c++2a -I/usr/local/Cellar/libarchive/3.3.3/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.58.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.58.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libsigc++/2.10.1/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.10.1/lib/sigc++-2.0/include -I/usr/local/Cellar/glibmm/2.58.0/include/glibmm-2.4 -I/usr/local/Cellar/glibmm/2.58.0/lib/glibmm-2.4/include -I/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6 -I/usr/local/Cellar/libxml++/2.40.1/lib/libxml++-2.6/include -I/usr/include/libxml2 -g -O2 -std=c++2a -c ospell.cc -o libhfstospell_la-ospell.o >/dev/null 2>&1
```

**Pull request closed without merging**
