### PR TITLE
meson-internal: delete

### PR DESCRIPTION
**Pull request by iMichka**
meson-internal was introduced in https://github.com/Homebrew/homebrew-core/pull/25667

A patch was proposed upstream in
https://github.com/mesonbuild/meson/pull/2577, but never merged.

It looks like the issues were fixed by
https://github.com/mesonbuild/meson/issues/3555
https://github.com/mesonbuild/meson/pull/3691
https://github.com/mesonbuild/meson/pull/3356

Now that we are one year later, and things have settled down,
try to use meson everywhere and drop meson-internal, which is outdated.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Looks like this is still not fixed, getting a lot of errors like:

```
==> ./test
dyld: Library not loaded: /usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib
  Referenced from: /usr/local/opt/jsonrpc-glib/lib/libjsonrpc-glib-1.0.1.dylib
  Reason: Incompatible library version: libjsonrpc-glib-1.0.1.dylib requires version 401.0.0 or later, but libjson-glib-1.0.0.dylib provides version 0.0.0
Error: jsonrpc-glib: failed
```

I'll read through the tens of issues opened around that topic to try to understand what is going on, and what upstream was thinking when they said "this is fixed".

**Comment by iMichka** [comment]
Here is the content of the library provided by the bottle, before my change:
```
otool -L /usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib
/usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib:
	/usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib (compatibility version 401.0.0, current version 401.4.0)
```

Once I use the newest meson, here is what we get, and this is why all the reverse dependencies of that libraries are broken:
```
otool -L /usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib
/usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib:
	/usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib (compatibility version 0.0.0, current version 0.0.0)
```

I see that there is a patch in json-glib hacking around version numbers. Removing it and using the newest meson gives me:
```
otool -L /usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib
/usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib:
	/usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib (compatibility version 1.0.0, current version 400.4.0)
```

I am a little bit lost right now ... I think the version numbers with the newest meson look ok, but I will need to revision bump the reverse dependencies to make this work. I tested this locally and this seems to work.

**Comment by javian** [comment]
I added the do not merge since this seems to be wip that requires a few more formula updates before its complete. Feel free to remove it whenever =)

**Comment by tschoonj** [comment]
As the original author of this formula, my recommendation is to keep this formula for now. My plan is to gradually replace formulas that are currently using it, to use the regular meson instead, when an update for them becomes available. This approach has led to me being able to remove most of them already.

For this switch to the regular meson to be possible, the meson build scripts of the package may need to be updated: I have been adding patches for this whenever necessary, which are then accepted upstream.

It should certainly not be used for new formulas.

**Comment by fxcoudert** [comment]
Closing for now, we have to remove its use from formulas over time, then we can delete.

**Pull request closed without merging**
