### PR TITLE
cpm 0.997000

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
maybe resources need to be updated?

**Comment by carlocab** [comment]
I'm not sure how... Do you?

**Comment by carlocab** [comment]
Checked all the resources manually. They're all up to date.

**Review by Moisan — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks!

**Comment by chenrui333** [comment]
I used to have a way to generate some sort of perl lockfile (which would help with checking the dependencies versions), and it got lost somehow.

**Pull request closed without merging**
