### PR TITLE
ammonite-repl-scala-2.10 0.5.7 (new formula)

### PR DESCRIPTION
**Pull request by Atry**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

This formula is like https://github.com/Homebrew/homebrew-core/blob/master/Formula/ammonite-repl.rb , except this formula is for Scala 2.10 instead of Scala 2.11

### CODE REVIEW

**Comment by apjanke** [comment]
The `scala` brew formula is already at Scala 2.11. Maybe we should just bump the version in the existing `ammonite-repl` instead? (And maybe make the command name simply `ammonite-repl`? We normally don't accept multiple versions of formulae in core Homebrew.

And should `ammonite-repl` depend on `scala`? It's a "cleanroom reimplementation of the REPL", but it looks like the implementation is at least partly in the Scala language, even if it's not using the Scala REPL.

**Comment by Atry** [comment]
The `ammonite-repl` script embedded Scala compiler and standard library in itself, hence it does not depend on `scala` formula.

0.5.7 is the version of `ammonite-repl`.
2.11 or 2.10 is the embedded Scala version.

**Comment by Atry** [comment]
I think we did accept multiple versions of formulae in core Homebrew. For example, [Python 2](https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb) vs [Python 3](https://github.com/Homebrew/homebrew-core/blob/master/Formula/python3.rb).

**Comment by apjanke** [comment]
> I think we did accept multiple versions of formulae in core Homebrew. For example, Python 2 vs Python 3.

Only for a few exceptions where there are multiple major versions in simultaneous use by various programs. E.g. Python 2 and 3, GTK+ 2 and 3, and that's about it. The general rule is "only one version of a given package in core".

Let's just bump the existing version of `ammonite-repl` in this case. If there is really a need for multiple versions of Scala and `ammonite` to coexist, that would probably be a case for an external Tap.

**Comment by Atry** [comment]
The point is backward compatibility. Scala 2.10 and 2.11 are different major versions, as the version does not follow [semver](http://semver.org)



The upstream releases different binaries of the same Ammonite version for different Scala versions: https://github.com/lihaoyi/Ammonite/releases

**Comment by apjanke** [comment]
Thoughts from other maintainers on this? Will we accept multiple major versions of Scala and Scala-related tools in core Homebrew?

I lean toward "no", because making those exceptions is a pretty big deal, and I see this ballooning out in to a lot of formula variations because Scala is currently young and fast-moving. Might be a case for a Scala-specific tap run by people who actually know Scala. I don't think we have any Scala hackers among the Homebrew maintainers.

Added "maintainer feedback" label to solicit input from other folks.

**Comment by Atry** [comment]
I found that Debian also treat backward incompatible stuffs as different packages, for example:


- https://packages.debian.org/search?keywords=libboost1.60-dev
- https://packages.debian.org/search?keywords=libboost1.58-dev
- https://packages.debian.org/search?keywords=libboost1.55-dev
- https://packages.debian.org/search?keywords=libboost1.54-dev

This approach allows other packages of Debian depends on different versions of boost in one Debian release.

**Comment by apjanke** [comment]
True, and we recognize the advantages of that approach. But compared to Debian, Homebrew is faster-moving, a smaller organization, and doesn't have the version-specific dependency support that Debian does. So we generally stick with one major version in core Homebrew, and push support for multiple major versions (like that Boost 1.54/1.55/1.58/1.60) out to independently-maintained taps.

We've attempted support for multiple versions with the [homebrew-versions tap](https://github.com/homebrew/homebrew-versions), and the result has not been great; we don't have the resources or tech to support it adequately.

I think this still points to just bumping the version of `ammonite-repl` in core Homebrew, and leaving multiple versions to an outside Tap.

**Comment by Atry** [comment]
You are right, I found Scala 2.10 there: https://github.com/Homebrew/homebrew-versions/blob/master/scala210.rb

**Comment by apjanke** [comment]
Yeah. If you'd like to have both of these available, submit this on homebrew/versions instead of here on core; we'll merge it there. If there's a Scala 2.10 version there, it's legit to have a corresponding ammonite-repl.

**Comment by mikemcquaid** [comment]
Agreed on homebrew-versions.

**Pull request closed without merging**
