### PR TITLE
Go 1.9

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by fxcoudert** [comment]
`devel` needs to be removed (or updated if a new devel version is already available)

**Comment by leonklingele** [comment]
Sorry, was about to push that. audit passes again.

**Comment by fxcoudert** [comment]
also, please squash into one commit

**Comment by leonklingele** [comment]
Why does CI also test godep (and fails)? https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7279/version=sierra/testReport/brew-test-bot/sierra/test_godep/

**Comment by JCount** [comment]
Because `godep` directly depends on `go`.

**Comment by leonklingele** [comment]
Hmm, `brew test --verbose godep` passes for me.

**Comment by ilovezfs** [comment]
@leonklingele you probably still have the prior version of `go` installed locally as well. Please bump the godep revision, in a separate commit `godep: revision for go`.

**Comment by DomT4** [comment]
You'll need to pull that PR into this one. Other tools such as `glide`, `govendor` & `gpm` will likely want rebuilding from source locally to make sure there's no weirdness with those.

Also, IIRC, this is the first release of `go` that drops support for macOS 10.8, so maintainers will need to decide whether to enforce that or wait and see if anything breaks.

**Comment by DomT4** [comment]
Damn, ILZ beat me to it 😄.

**Comment by ilovezfs** [comment]
It's still working on 10.8 for the time being.

**Comment by ilovezfs** [comment]
I have pushed the revision bump.

**Comment by ilovezfs** [comment]
Thanks @leonklingele! Shipped. :tada:

**Comment by aren55555** [comment]
@leonklingele looks like you forgot to update the version of Go used to bootstrap the install; I've done so here: https://github.com/Homebrew/homebrew-core/pull/17368

**Comment by ilovezfs** [comment]
@aren55555 see the comment in the formula.

**Pull request closed without merging**
