### PR TITLE
eye-d3 0.9.7

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [ ] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
> The formula version (0.9.7) is newer than the version from `brew livecheck` (0.9.6).

**Comment by osalbahr** [comment]
Looking at https://eyed3.readthedocs.io/en/latest/ it looks like latest might be 0.9.7? Or maybe that number is just for `pip`, not sure.

https://pypi.org/project/eyed3/

Screenshot 2023-08-04 at 9 47 16 PM

```console
% brew bump eye-d3
==> eye-d3 is up to date!
Current formula version:  0.9.6
Latest livecheck version: 0.9.6
Latest Repology version:  not found
Open pull requests:       eye-d3 0.9.7 (https://github.com/Homebrew/homebrew-core/pull/138588)
Closed pull requests:     none
```

- - -

Note: I did not manually create the PR, I used `brew bump --open-pr` (without args).

**Comment by chenrui333** [comment]
raised an upstream question about this. good catch!

**Comment by chenrui333** [comment]
close it for now, once the issue resolved, we can reopen it.

**Pull request closed without merging**
