### PR TITLE
nift 2.0

### PR DESCRIPTION
**Pull request by n-ham**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
```
==> /usr/local/Cellar/nift/2.0/bin/nsm init
error: 1 parameters is not the 2 parameters expected
parameters given: init
```

**Comment by n-ham** [comment]
Oops sorry I forgot that I had changed `nsm init` to `nsm init-html` (`nsm init` now does something else). I have updated the test and it is now passing.

**Comment by bayandin** [comment]
No problem at all! Thanks @n-ham

**Comment by n-ham** [comment]
@bayandin I pushed the required changes to the branch you just closed the PR for, is there a different way I should be pushing the changes?

**Comment by bayandin** [comment]
@n-ham, the PR with all your changes was merged in https://github.com/Homebrew/homebrew-core/commit/d41157e3fbf468d1c2ff92567560e5f75efc20c0. Because the formula requires bottles update we have a non-GitHub UI flow for merging it.

**Comment by n-ham** [comment]
Okay cool, thanks for updating me so I know for the future, and thanks in general :).

**Pull request closed without merging**
