### PR TITLE
bloaty 1.1

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by issyl0** [comment]
```
Error: The `brew link` step did not complete successfully
==> Cleaning
==> Finishing up
ln -s ../Cellar/bloaty/1.1/bin/bloaty bloaty
rm /usr/local/bin/bloaty
The formula built, but is not symlinked into /usr/local
Could not symlink bin/protoc
Target /usr/local/bin/protoc
is a symlink belonging to protobuf. You can unlink it:
  brew unlink protobuf
```

**Comment by alebcay** [comment]
I'm not able to reproduce this issue locally.

```
bloaty/1.1/bin
❯ ls
bloaty
```

**Comment by dawidd6** [comment]
CMake can't find our protobuf:

```
-- System re2 not found, using bundled version
-- System capstone not found, using bundled version
-- System protobuf not found, using bundled version
```

**Comment by alebcay** [comment]
Looks like `depends_on "pkg-config" => :build` was needed to properly pick up system dependencies, avoiding the extra `protobuf` binaries from being built. Somehow CMake was picking up on the shim and not getting a valid `pkg-config` version but still proceeding anyways.

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
