### PR TITLE
dbt 0.8.1

### PR DESCRIPTION
**Pull request by cmcarthur**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by fxcoudert — DISMISSED** [review]
Thanks for the pull request!

Can you update the resources to their latest versions? In particular, `cryptography` needs to be updated to 1.8.1, which in turn will allow us to get rid of the `inreplace` hack we currently do (and which was fixed in cryptography 1.8).

**Comment by cmcarthur** [comment]
@fxcoudert dbt 0.8.1 is already deployed to pip with a hard dependency on cryptography 1.7.1, but i'll follow up and upgrade these packages for the next version (should be 0.8.2)

**Comment by cmcarthur** [comment]
Opened an issue in dbt for this: https://github.com/fishtown-analytics/dbt/issues/423

**Comment by ilovezfs** [comment]
Thanks @cmcarthur

**Pull request closed without merging**
