### PR TITLE
gjs 1.46.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Sorry didn't realize you opened a PR for this already. Usually I am the only one updating the GNOME stuff 😄

**Comment by ilovezfs** [comment]
No problem at all Tom!

**Comment by DomT4** [comment]
> Usually I am the only one updating the GNOME stuff 

I finished up the last huge GNOME PR and it made me never want to touch the stuff again 😆.

**Comment by ilovezfs** [comment]
GNOME vs. Qt: discuss.

**Comment by DomT4** [comment]
Is there an option for 💀 🔫 ?

**Comment by MikeMcQuaid** [comment]
Thanks again @tschoonj!

**Pull request closed without merging**
