### PR TITLE
ffmpeg 4.1

### PR DESCRIPTION
**Pull request by dericed**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
`mpv` needs a revision bump. Please add a second commit, that add a `revision 1` line before the `head` line in `mpv.rb`. Commit message should be `mpv: bump revision for ffmpeg`.

**Comment by dericed** [comment]
@fxcoudert done

**Comment by fxcoudert** [comment]
Stupid `qmmp` linking fails again… no worries

**Comment by fxcoudert** [comment]
Thanks @dericed for the pull request!

**Pull request closed without merging**
