### PR TITLE
usbredir 0.10.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Meson is now the only build option. Autotools build was removed in this release.
https://gitlab.freedesktop.org/spice/usbredir/-/commit/75c87f568c2c96ec9a091a2d3cead68ae66512c0

**Comment by carlocab** [comment]
The linker doesn't support `--version-script`. See https://github.com/xkbcommon/libxkbcommon/issues/24.

This should probably be reported upstream.

**Comment by nandahkrishna** [comment]
Reported: https://gitlab.freedesktop.org/spice/usbredir/-/issues/18.

**Comment by chenrui333** [comment]
Close it for now.

**Comment by nandahkrishna** [comment]
Included a patch from upstream merge request (https://gitlab.freedesktop.org/spice/usbredir/-/merge_requests/32), builds locally (`11.3` Intel).

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
