### PR TITLE
rust 1.64.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by branchvincent** [comment]
Cargo is now

```ruby
    resource "cargo" do
      url "https://github.com/rust-lang/cargo.git",
          tag:      "0.65.0",
          revision: "387270bc7f446d17869c7f208207c73231d6a252"
    end
```

**Comment by chenrui333** [comment]
> Cargo is now
> 
> ```ruby
>     resource "cargo" do
>       url "https://github.com/rust-lang/cargo.git",
>           tag:      "0.65.0",
>           revision: "387270bc7f446d17869c7f208207c73231d6a252"
>     end
> ```

but it not the commit in the source tree, https://github.com/rust-lang/rust/tree/1.64.0/src/tools
?

How should I proceed?

**Comment by Bo98** [comment]
> > Cargo is now
> > ```ruby
> >     resource "cargo" do
> >       url "https://github.com/rust-lang/cargo.git",
> >           tag:      "0.65.0",
> >           revision: "387270bc7f446d17869c7f208207c73231d6a252"
> >     end
> > ```
> 
> but it not the commit in the source tree, https://github.com/rust-lang/rust/tree/1.64.0/src/tools?
> 
> How should I proceed?

It is? 

image

**Comment by chenrui333** [comment]
> > > Cargo is now
> > > ```ruby
> > >     resource "cargo" do
> > >       url "https://github.com/rust-lang/cargo.git",
> > >           tag:      "0.65.0",
> > >           revision: "387270bc7f446d17869c7f208207c73231d6a252"
> > >     end
> > > ```
> > 
> > 
> > but it not the commit in the source tree, https://github.com/rust-lang/rust/tree/1.64.0/src/tools?
> > How should I proceed?
> 
> It is?
> 
> image

my bad, I thought the tag and commit were done at the same time, let me update it.

**Comment by carlocab** [comment]
`watchman` fails to build on Monterey with
```
Undefined symbols for architecture x86_64:
    "folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()", referenced from:
        folly::f14::detail::F14Table<folly::f14::detail::VectorContainerPolicy<unsigned int, folly::Range<char const*>, void, void, void, std::__1::integral_constant<bool, true> > >::rehashImpl(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)::'lambda'()::operator()() const in libeden_service_thrift.a(eden_types.cpp.o)
```
Not sure what that's about, but I don't think it's Rust-related.

It smells like the `-march` flags issue, but I'm pretty sure we always pass the same `-march` flags on macOS.

**Comment by carlocab** [comment]
Failed on Catalina as well. Superenv doesn't seem to be adding `-march` flags, so that might be why. Logs: [watchman.tar.gz](https://github.com/Homebrew/homebrew-core/files/9640272/watchman.tar.gz)

**Comment by carlocab** [comment]
Catalina is done, and Big Sur is midway through building `watchman`, so should be done in an hour and a half or so.

**Review by carlocab — APPROVED** [review]
Failures look unrelated.

**Pull request closed without merging**
