### PR TITLE
helix 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by matoous**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Requesting also approval from the main maintainer of Helix, @archseer.

Helix was already available through this tap: https://github.com/helix-editor/homebrew-helix, this PR follows the previous implementation with small adjustments to follow the linting and test requirements of Homebrew.

Adding this formula was mentioned in this PR: https://github.com/helix-editor/helix/pull/1371 in helix.

### CODE REVIEW

**Comment by archseer** [comment]
It's not enough to simply compile the `helix-term` binary, you need to install the `runtime/` dir to somewhere then wrap `hx` to point to it https://github.com/helix-editor/homebrew-helix/blob/7baef9eb259fce9e912554c01409a7ed771b0dd5/Formula/helix.rb#L9-L10

**Comment by matoous** [comment]
@archseer I must be missing something here, but when I install, it all succeeds but running `hx` hangs, would you please have any idea of what might be wrong?

**Comment by Mathspy** [comment]
> @archseer I must be missing something here, but when I install, it all succeeds but running `hx` hangs, would you please have any idea of what might be wrong?

If I’m not mistaken running `hx` hangs by design, since it opens the editor until it’s closed manually, you probably wanna run `hx —version` instead

**Comment by matoous** [comment]
Sorry, didn't have time to fix this, closing in favor of: https://github.com/Homebrew/homebrew-core/pull/93816

**Pull request closed without merging**
