### PR TITLE
cassandra: does not support Python 3

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Not sure how this ever passed tests given the resources were installed under 3.8.

Can you remove the use of `python@3.8` in the `install` block?

**Review by bayandin — CHANGES_REQUESTED** [review]
Hmm, I'm not sure this will work.
Will `python@2` work with `cython` generated code (`cython` uses `python@3.8`)?

And we have a couple of `Formula["python@3.8"]` itself in a formula.

**Comment by Bo98** [comment]
Good catch. `Cython` could probably be pulled as a resource. It should really not be used as a dependency since it is `python@3.8`.

**Comment by iMichka** [comment]
I have no clue how it worked in the tests. But basically what happened in our CI, is that the `cqlsh` is calling `python` internally, and python points to python 2 on mac. So when running cassandra, it would use plain system Python 2. And I am not going to patch this script, as this is what https://issues.apache.org/jira/browse/CASSANDRA-10190 is trying to solve.

**Pull request closed without merging**
