### PR TITLE
xerces-c 3.2.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[34m==>[0m [1mbrew test --verbose geant4[0m
Testing geant4
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200412-62765-1lblalg.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/geant4.rb --verbose
[34m==>[0m [1mcmake /usr/local/Cellar/geant4/10.5.1/share/Geant4-10.5.1/examples/basic/B1[0m
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/geant4-test-20200412-62766-1bfruf6
[34m==>[0m [1mmake[0m
Scanning dependencies of target exampleB1
[ 12%] Building CXX object CMakeFiles/exampleB1.dir/exampleB1.cc.o
[ 25%] Building CXX object CMakeFiles/exampleB1.dir/src/B1ActionInitialization.cc.o
[ 37%] Building CXX object CMakeFiles/exampleB1.dir/src/B1DetectorConstruction.cc.o
[ 50%] Building CXX object CMakeFiles/exampleB1.dir/src/B1EventAction.cc.o
[ 62%] Building CXX object CMakeFiles/exampleB1.dir/src/B1PrimaryGeneratorAction.cc.o
[ 75%] Building CXX object CMakeFiles/exampleB1.dir/src/B1RunAction.cc.o
make[2]: *** No rule to make target `/usr/local/lib/libxerces-c.so', needed by `exampleB1'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 87%] Building CXX object CMakeFiles/exampleB1.dir/src/B1SteppingAction.cc.o
make[1]: *** [CMakeFiles/exampleB1.dir/all] Error 2
make: *** [all] Error 2
[31mError:[0m geant4: failed
Failed executing:
```

**Comment by chenrui333** [comment]
Let's do another round of bottle builds

**Comment by Bo98** [comment]
The bottle is too big to be handled by the bottle publish tools just now.

**Comment by chenrui333** [comment]
> The bottle is too big to be handled by the bottle publish tools just now.

where can I see the error log?

**Comment by Bo98** [comment]
By clicking the link @BrewTestBot posted

**Comment by chenrui333** [comment]
Finally. 😄

**Pull request closed without merging**
