### PR TITLE
code-server 4.2.0

### PR DESCRIPTION
**Pull request by jsjoeio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jsjoeio** [comment]
This looks similar to what happened last time. https://github.com/Homebrew/homebrew-core/pull/96254

**Comment by cho-m** [comment]
```
    Errno::ENOENT: No such file or directory @ apply2files - /private/tmp/code-server-20220322-39351-vcoi0t/package/vendor/modules/code-oss-dev/node_modules/@parcel/watcher/prebuilds/darwin-x64
```

This means the remove logic in formula install block need to be updated
```rb
    prebuilds = buildpath/"vendor/modules/code-oss-dev/node_modules/@parcel/watcher/prebuilds"
    (prebuilds/"darwin-x64").rmtree if Hardware::CPU.arm?
    (prebuilds/"darwin-arm64").rmtree if Hardware::CPU.intel?
```

If these are no longer being installed, then lines can be deleted.

**Comment by jsjoeio** [comment]
Ahh! We moved that directory and didn't catch since it was a search and replace. Very sorry about that. I'll push the new fix.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @jsjoeio!

**Pull request closed without merging**
