### PR TITLE
docbook-xsl 1.79.2

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

Plus update homepage/source URLs and add docs.

### CODE REVIEW

**Comment by Bo98** [comment]
This was deliberately not done before but I don't entirely know why: #23916.

**Comment by Bo98** [comment]
@iMichka Do you happen to know what the issues around 1.79.2 were?

**Comment by iMichka** [comment]
I don't remember. Back then the project looked dead, and I guess that the update broke some stuff.

Does the build bot test the revers build dependencies?
To be sure, I would check if all the `depends_on "docbook-xsl" => :build` formulae correctly build.

**Comment by Bo98** [comment]
> Does the build bot test the revers build dependencies?

Only for those on a whitelist. I can add `docbook-xsl`.

**Comment by chenrui333** [comment]
Thanks @pthariensflame!

**Comment by Bo98** [comment]
I guess that also works.

**Comment by iMichka** [comment]
I am wondering if this failure is related: https://github.com/Homebrew/homebrew-core/pull/51984 ?

**Comment by Bo98** [comment]
gtk-doc has a check based on the old XSL URLs on SourceForge so the answer is yes. There’s probably many others affected.

With that said, other package managers have been able to update 1.79.2 so there must be something we can do on our side that’s not just downgrading to 1.79.1.

I’ll start by getting so docbook-xsl on the build from source whitelist tomorrow so we can test things properly.

**Comment by iMichka** [comment]
Yes, I have seen that too. And others have been able to use that new version. Weird.

**Comment by iMichka** [comment]
http://www.linuxfromscratch.org/blfs/view/8.2/pst/docbook-xsl.html

There is some url rewriting that can be done, see `Configuration Information`.

**Comment by pthariensflame** [comment]
#52041 is now open.

**Comment by pthariensflame** [comment]
@iMichka I'll work on a second commit that add that rewriting to the formula, and put it into #52041.

**Pull request closed without merging**
