### PR TITLE
bullet: patch for Xcode 11

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like the Catalina build bot has run out of disk space.

**Comment by Bo98** [comment]
Orka 3 specifically, which is the first one picked.

**Comment by fxcoudert** [comment]
Since it's a compile error, we shouldn't bump the revision. Users who already have it installed don't need the latest binaries.

**Comment by Bo98** [comment]
Ok, I'll revert that. The CI should handle the missing Cataline bottle fine I presume?

**Comment by Bo98** [comment]
Or actually, this library supplies headers so a revision may be worthwhile since the change is in a header file?

**Comment by fxcoudert** [comment]
Actually yes, given it affects a header, I suppose a revision is good. Thanks!

**Pull request closed without merging**
