### PR TITLE
kube-aws 0.15.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
`v0.15.0-rc1` appears to be a pre-release version.

**Comment by alebcay** [comment]
```
==> brew test kube-aws --verbose
==> FAILED
Testing kube-aws
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191120-37321-1ev7zmn.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kube-aws.rb --verbose
==> /usr/local/Cellar/kube-aws/0.15.0/bin/kube-aws
Manage Kubernetes clusters on AWS

Usage:
  kube-aws [command]

Available Commands:
  apply       Create or Update your cluster
  calculator  Discover the monthly cost of your cluster
  destroy     Destroy an existing Kubernetes cluster
  diff        Compare the current and the desired states of the cluster
  help        Help about any command
  init        Initialize default node pool configuration
  render      Render deployment artifacts
  show        Show info about certificates in credentials directory
  status      Describe an existing Kubernetes cluster
  up          DEPRECATED: Create a new Kubernetes cluster
  update      DEPRECATED: Update an existing Kubernetes cluster
  validate    Validate cluster assets
  version     Print version information and exit

Flags:
      --color     use color for messages
  -h, --help      help for kube-aws
  -s, --silent    do not show messages
  -v, --verbose   show debug messages

Use "kube-aws [command] --help" for more information about a command.
==> /usr/local/Cellar/kube-aws/0.15.0/bin/kube-aws init --cluster-name test-cluster --external-dns-name dns --region us-west-1 --availability-zone zone --key-name key --kms-key-arn arn --no-record-set --s3-uri s3://examplebucket/mydir
Error: error exec-ing default config template: Error exec-ing default config template: template: cluster.yaml:1653:57: executing "cluster.yaml" at <.Config.AdminAPIEndpoint.DNSName>: can't evaluate field Config in type config.InitialConfig
Error: kube-aws: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1927:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1864:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1864:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kube-aws.rb:28:in `block in <class:KubeAws>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1740:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1739:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:865:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1738:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1977:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1976:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1732:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:30:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:29:in `<main>'
```

**Comment by chenrui333** [comment]
> `v0.15.0-rc1` appears to be a pre-release version.

I guess we can wait for `0.15.0`?

**Comment by igas** [comment]
My bad, I'll adjust check

**Comment by chenrui333** [comment]
no worries!

**Pull request closed without merging**
