### PR TITLE
swift 3.0.1

### PR DESCRIPTION
**Pull request by valkjsaaa**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

updated swift version to 3.0.1

### CODE REVIEW

**Comment by valkjsaaa** [comment]
Well, it seems that Swift requires Xcode 8 which macOS / OS X Yosemite does not support.

**Comment by valkjsaaa** [comment]
This is weird. What does this supposed to mean?

Result of `brew audit swift` on macOS / OS X El Capitan

```
        Error: 1 problem in 1 formula
swift:
  * The installation was broken.
    Broken dylib links found:
      /System/Library/Frameworks/Intents.framework/Versions/A/Intents
```

**Comment by ilovezfs** [comment]
It means the file doesn't exist, which on El Capitan is true.

**Comment by ilovezfs** [comment]
@zmwangx looks like the failure has shifted from being fails-on-Sierra to being fails-on-not-Sierra lol

**Comment by valkjsaaa** [comment]
@ilovezfs So are there anything wrong within this formula? Or this is a homebrew audit bug?

**Comment by ilovezfs** [comment]
The formula is broken. The final binaries should not be linked against non-existent files.

**Comment by valkjsaaa** [comment]
Could you give my some suggestion about how to fix that? This seems like a upstream problem to me.

**Comment by ilovezfs** [comment]
This is actually probably a new `brew audit` problem.

```
otool -l /usr/local/Cellar/swift/3.0.1/lib/swift/macosx/libswiftIntents.dylib
```
shows

```
Load command 11
          cmd LC_LOAD_WEAK_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/Intents.framework/Versions/A/Intents (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 1.0.0
```

and my guess is we shouldn't be failing something for a weak framework link against a file that doesn't exist when the build system explicitly requested `-weak_framework` due to that possibility. CC @UniqMartin

An unrelated thing that is actually a bit concerning though is the warnings
```
ld: warning: object file (/tmp/swift-20161106-41114-les5db/build/llvm-macosx-x86_64/./lib/libclangCodeGen.a(CGBuiltin.cpp.o)) was built for newer OSX version (10.11) than being linked (10.9)
```
since the configure arguments explicitly request 10.11, I'm not sure why it's only half honoring that. That seems like either it's an upstream build system bug, or we're missing a second option that should also be set to 10.11, or both. I'm tempted to just do string replacements of the offending 10.9 in the CMakeLists.txt, but it would be better to figure out why that's happening.

**Comment by MikeMcQuaid** [comment]
> and my guess is we shouldn't be failing something for a weak framework link against a file that doesn't exist when the build system explicitly requested -weak_framework due to that possibility. CC @UniqMartin

CC @woodruffw in case you have thoughts, too.

**Comment by woodruffw** [comment]
> and my guess is we shouldn't be failing something for a weak framework link against a file that doesn't exist when the build system explicitly requested -weak_framework due to that possibility.

This sounds correct to me. We currently enumerate linked dylibs without any consideration for what *type* they are, via `MachOFile#linked_dylibs` in ruby-macho. There's a more flexibility way to do this (`MachOFile#dylib_load_commands` + filtering), which I could expose like this (in Homebrew):

```ruby
file.dynamically_linked_libraries(except: :weak) do |dylib|
 # normal magic here
end
```

That would give us the behavior we desire in places like `LinkageChecker#check_dylibs`, which is what's currently causing the error.

Thoughts?

**Comment by MikeMcQuaid** [comment]
@woodruffw Sounds like the right approach 👍

**Comment by MikeMcQuaid** [comment]
Pulling this as it's an `audit` bug.

Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by woodruffw** [comment]
@MikeMcQuaid Great! I'll have a PR for the correct behavior today.

**Comment by ilovezfs** [comment]
>Pulling this as it's an audit bug.

It looks like this PR unintentionally led to dropping Yosemite support. Only a 10.11 bottle and a 10.12 bottle were pulled, and neither 3.0.1 nor 3.0.2 are building on 10.10.


3.0.1: https://bot.brew.sh/job/Homebrew%20Testing/1181/version=yosemite/console
3.0.2: https://bot.brew.sh/job/Homebrew%20Core/13231/version=yosemite/console

**Comment by MikeMcQuaid** [comment]
Yes, sorry. It's likely this is an Xcode/Clang version dependency rather than an OS one so 👍 to restricting this formula to that.

**Comment by ilovezfs** [comment]
Assumed Apple intends Swift 3 to have some level of Yosemite compatibility (not sure one way or another yet), I think this may very well be related to what I had mentioned above: https://github.com/Homebrew/homebrew-core/pull/6645#issuecomment-258668325

Specifically, that I don't think we're actually setting SDK to the current macOS version of the build machine in the correct way for their build system.

**Comment by MikeMcQuaid** [comment]
> Specifically, I don't think we're actually setting SDK to the current macOS version of the build machine in the correct way for their build system.

Sounds likely 👍

**Pull request closed without merging**
