### PR TITLE
afflib 3.7.14

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@umireon any thoughts here? Looks like upstream broke it again lol

**Comment by umireon** [comment]
Is [this](https://gist.github.com/umireon/4dbe4adbb2849be612f2d0b7dfd1d019) fix the problems?
I don't see any build problems outside brew.

**Comment by umireon** [comment]
sshock/AFFLIBv3#21 will fix the problem with prefix.
Formula: https://gist.github.com/umireon/4dbe4adbb2849be612f2d0b7dfd1d019

**Comment by ilovezfs** [comment]
>I don't see any build problems outside brew.

Good. It would be nice if upstream enabled Travis or something so we're not playing Whac-a-mole every release.

>will fix the problem ...

Great. I'll merge this as-is and then you can open a PR with that new work so we can verify it's still :green_apple:

**Comment by ilovezfs** [comment]
@umireon shipped.

**Pull request closed without merging**
