### PR TITLE
pytouhou: build a bottle after Python 3.8 update

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
If it's just a Mojave bottle you need and not a revision bump then I can set Jenkins to do that.

**Comment by iMichka** [comment]
Right, if you can build a mojave bottle, then go for it. I guess that you can trigger a manual build from the jenkins GUI. I'll close this PR then. Thanks!

**Comment by Bo98** [comment]
e95acb4f6045f7a57e012bba9d0d8e16ad22f1b6

**Comment by iMichka** [comment]
Thanks !

**Pull request closed without merging**
