### PR TITLE
apache-drill: migrate to openjdk@8

### PR DESCRIPTION
**Pull request by mattrussi**
openjdk@8 migration (#63290)

### CODE REVIEW

**Comment by bayandin** [comment]
Probably we need to change `Language::Java.java_home_env("1.8")` to `Language::Java.java_home_env("8")` to have it consistent with other openjdk formulae

**Comment by mattrussi** [comment]
`Language::Java.java_home_env("1.8")` is the consistent pattern across all of the formulae that utilize this function. java_home_env interprets this properly. https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/java.rb

```shell
λ grep Language::Java.java_home_env Formula/apache-drill.rb
    bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("1.8"))

λ brew test -v apache-drill
==> Testing apache-drill
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201028-92533-13rv9ju.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apache-drill.rb --verbose
==> /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline -u jdbc:drill:zk=local
Picked up _JAVA_OPTIONS: -Duser.home=/Users/<user>/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
Apache Drill 1.17.0
"What ever the mind of man can conceive and believe, Drill can query."

λ cat /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline
#!/bin/bash
JAVA_HOME="/usr/local/opt/openjdk@8/libexec/openjdk.jdk/Contents/Home" exec "/usr/local/Cellar/apache-drill/1.17.0/libexec/bin/sqlline"  "$@"
```

`Language::Java.java_home_env("8")` doesn't work properly.
```shell
λ grep Language::Java.java_home_env Formula/apache-drill.rb
    bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("8"))

λ brew test -v apache-drill
==> Testing apache-drill
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201028-90796-1c0kqyd.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apache-drill.rb --verbose
==> /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline -u jdbc:drill:zk=local
Unable to locate an executable at "/System/Library/Frameworks/JavaVM.framework/Versions/A/bin/java" (-1)

Error: apache-drill: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<2>.

λ cat /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline
#!/bin/bash
JAVA_HOME="$(/usr/libexec/java_home --version 8 --failfast 2>/dev/null)" exec "/usr/local/Cellar/apache-drill/1.17.0/libexec/bin/sqlline"  "$@"

λ /usr/libexec/java_home --version 8 --failfast
Unable to find any JVMs matching version "8".
```

**Comment by SMillerDev** [comment]
Please use `Language::Java.overridable_java_home_env("8")` as the other formula that use openjdk are doing. The current usage is only used with casks.

**Comment by mattrussi** [comment]
@SMillerDev  Sorry, just as `Language::Java.java_home_env("8")` failed (mentioned above), so does `Language::Java.overridable_java_home_env("8")`. (shown below) 

`/usr/libexec/java_home` is not recognizing openjdk@8. Whereas, `Language::Java.java_home_env("1.8")` and `Language::Java.overridable_java_home_env("1.8")` work successfully. Possibly some tweaks needed in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/java.rb or https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/os/mac/language/java.rb?

I'm not seeing any other Formula use `Language::Java.overridable_java_home_env("8")` successfully. The only Formula I see specifying a version are micronaut and solr which are on openjdk@11. 

```shell
λ grep -ir "Language::Java.overridable_java_home_env("8")" Formula
λ

λ grep -ir 'Language::Java.overridable_java_home_env("11")' Formula/
Formula//micronaut.rb:    (bin/"mn").write_env_script libexec/"bin/mn", Language::Java.overridable_java_home_env("11")
Formula//solr@7.7.rb:    env = Language::Java.overridable_java_home_env("11")
```
**Using `"8"`**
The test fails as `Language::Java.overridable_java_home_env("8")` is defaulting to utilize `/usr/libexec/java_home` which returns:
> Unable to find any JVMs matching version "8".
```shell
λ grep Language::Java. Formula/apache-drill.rb
    bin.env_script_all_files(libexec/"bin", Language::Java.overridable_java_home_env("8"))

λ brew uninstall -f apache-drill
Uninstalling apache-drill... (434 files, 333.3MB)

λ brew install -s apache-drill
Updating Homebrew...
==> Downloading https://www.apache.org/dyn/closer.lua?path=drill/drill-1.17.0/apache-drill-1.17.0.tar.gz
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/71ebefa7b38ae593930dc94120e56792504c629e362d390e0f00fddb5ba1b58e--apache-drill-1.17.0.tar.gz
🍺  /usr/local/Cellar/apache-drill/1.17.0: 434 files, 333.3MB, built in 9 seconds

λ brew test -v apache-drill
==> Testing apache-drill
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201028-5103-136zn32.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apache-drill.rb --verbose
==> /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline -u jdbc:drill:zk=local
Unable to locate an executable at "/System/Library/Frameworks/JavaVM.framework/Versions/A/bin/java" (-1)

Error: apache-drill: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<2>.

λ cat /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-$(/usr/libexec/java_home --version 8 --failfast 2>/dev/null)}" exec "/usr/local/Cellar/apache-drill/1.17.0/libexec/bin/sqlline"  "$@"

λ /usr/libexec/java_home --version 8 --failfast
Unable to find any JVMs matching version "8".
```
**Using `"1.8"`**
```shell
λ grep Language::Java. Formula/apache-drill.rb
    bin.env_script_all_files(libexec/"bin", Language::Java.overridable_java_home_env("1.8"))

λ brew uninstall -f apache-drill
Uninstalling apache-drill... (434 files, 333.3MB)

λ brew install -s apache-drill
Updating Homebrew...
==> Downloading https://www.apache.org/dyn/closer.lua?path=drill/drill-1.17.0/apache-drill-1.17.0.tar.gz
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/71ebefa7b38ae593930dc94120e56792504c629e362d390e0f00fddb5ba1b58e--apache-drill-1.17.0.tar.gz
🍺  /usr/local/Cellar/apache-drill/1.17.0: 434 files, 333.3MB, built in 9 seconds

λ brew test -v apache-drill
==> Testing apache-drill
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201028-8305-cytfm8.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apache-drill.rb --verbose
==> /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline -u jdbc:drill:zk=local
Picked up _JAVA_OPTIONS: -Duser.home=/Users/<user>/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
Apache Drill 1.17.0
"Say hello to my little Drill."

λ cat /usr/local/Cellar/apache-drill/1.17.0/bin/sqlline
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk@8/libexec/openjdk.jdk/Contents/Home}" exec "/usr/local/Cellar/apache-drill/1.17.0/libexec/bin/sqlline"  "$@"
```

**Comment by SMillerDev** [comment]
That's because openjdk@8 is very new in comparison. It hasn't had these brew changes yet as you noticed. But I don't think we should work around a bug in brew like that.

**Comment by mattrussi** [comment]
Sure, that's understandable, and I'm not suggesting to work around a bug. Rather, I was just pointing out that the approach being recommended does not currently work.

**Comment by jonchang** [comment]
Thanks for your help with this migration @mattrussi!

**Pull request merged**
