### PR TITLE
Allow gnutls install using XCode 11.4

### LINKED ISSUE #52348: gnutls install with --build-from-source fails on 10.15.4
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 

`brew gist-logs` output is:
Error: Not Found

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Here is the gist with `brew config`; `brew doctor`; and `brew install ...` output:

https://gist.github.com/dbart/f86efefabbeedeccafc5a1a8fc6e57fa

## What you were trying to do (and why)

Eventually I want to compile a static gnutls library. The default recipe includes `--disable-static`, so eventually I will use `brew edit gnutls` to change that option to `--enable-static`, but before I do that it should be able to actually compile with no changes, so for now I'm running `brew install --build-from-source gnutls` with no changes to the gnutls recipe.

Based on https://github.com/Homebrew/homebrew-core/issues/2938 I ran

`xcode-select --install` but the command-line tools are already installed, and `brew reinstall nettle` but that doesn't change the outcome. I've included the output of these commands in the command output section below.

## What happened (include command output)

clang throws an error

<details>
  <summary>Command output</summary>
  <pre>
legolas:~ admin$ brew install --build-from-source gnutls
==> Downloading https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.12.tar.xz
######################################################################## 100.0%
==> ./configure --disable-static --prefix=/usr/local/Cellar/gnutls/3.6.12 --sysconfdir=/usr/local/etc --with-default-trust-store-file=/usr/local/etc/openssl/cert.pem --disable-guile --disable-heartbeat-support --with-p11-kit gl_cv_func_ft
==> make install
Last 15 lines from /Users/admin/Library/Logs/Homebrew/gnutls/02.make:
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [gnutls-cli-debug] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: link: clang -fno-common -W -Wabsolute-value -Waddress -Waddress-of-packed-member -Wall -Wattributes -Wbad-function-cast -Wbuiltin-macro-redefined -Wcast-align -Wchar-subscripts -Wcomment -Wcomments -Wcpp -Wdangling-else -Wdate-time -Wdeprecated -Wdeprecated-declarations -Wdisabled-optimization -Wdiv-by-zero -Wdouble-promotion -Wduplicate-decl-specifier -Wempty-body -Wendif-labels -Wenum-compare -Wexpansion-to-defined -Wextra -Wformat-extra-args -Wformat-security -Wformat-zero-length -Wignored-attributes -Wignored-qualifiers -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wincompatible-pointer-types -Winit-self -Wint-conversion -Wint-to-pointer-cast -Winvalid-pch -Wlogical-not-parentheses -Wmain -Wmemset-transposed-args -Wmissing-braces -Wmissing-declarations -Wmissing-field-initializers -Wmissing-include-dirs -Wmissing-prototypes -Wmultichar -Wnarrowing -Wnested-externs -Wnonnull -Wnull-dereference -Wodr -Wold-style-definition -Woverflow -Woverride-init -Wpacked -Wparentheses -Wpointer-arith -Wpointer-sign -Wpointer-to-int-cast -Wpragmas -Wreturn-type -Wsequence-point -Wshadow -Wshift-count-negative -Wshift-count-overflow -Wshift-negative-value -Wsizeof-array-argument -Wsizeof-pointer-div -Wsizeof-pointer-memaccess -Wstrict-aliasing -Wstrict-prototypes -Wswitch -Wswitch-bool -Wtautological-compare -Wtrigraphs -Wtype-limits -Wuninitialized -Wunknown-pragmas -Wunused -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-parameter -Wunused-result -Wunused-value -Wunused-variable -Wvarargs -Wvariadic-macros -Wvolatile-register-var -Wwrite-strings -Wno-missing-field-initializers -Wno-unused-parameter -fdiagnostics-show-option -g -O2 -Wl,-no_weak_imports -o .libs/gnutls-serv serv.o udp-serv.o common.o -Wl,-framework -Wl,CoreFoundation  ../lib/.libs/libgnutls.dylib -L/usr/local/Cellar/p11-kit/0.23.20/lib -lp11-kit -lidn2 -lunistring -L/usr/local/Cellar/libtasn1/4.16.0/lib -ltasn1 -L/usr/local/Cellar/nettle/3.4.1/lib -lnettle -lhogweed -lgmp ./.libs/libcmd-serv.a libopts/.libs/libopts.a ../gl/.libs/libgnu.a gl/.libs/libgnu_gpl.a -lintl -framework CoreFoundation -framework Security
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [gnutls-serv] Error 1
libtool: link: clang -fno-common -W -Wabsolute-value -Waddress -Waddress-of-packed-member -Wall -Wattributes -Wbad-function-cast -Wbuiltin-macro-redefined -Wcast-align -Wchar-subscripts -Wcomment -Wcomments -Wcpp -Wdangling-else -Wdate-time -Wdeprecated -Wdeprecated-declarations -Wdisabled-optimization -Wdiv-by-zero -Wdouble-promotion -Wduplicate-decl-specifier -Wempty-body -Wendif-labels -Wenum-compare -Wexpansion-to-defined -Wextra -Wformat-extra-args -Wformat-security -Wformat-zero-length -Wignored-attributes -Wignored-qualifiers -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wincompatible-pointer-types -Winit-self -Wint-conversion -Wint-to-pointer-cast -Winvalid-pch -Wlogical-not-parentheses -Wmain -Wmemset-transposed-args -Wmissing-braces -Wmissing-declarations -Wmissing-field-initializers -Wmissing-include-dirs -Wmissing-prototypes -Wmultichar -Wnarrowing -Wnested-externs -Wnonnull -Wnull-dereference -Wodr -Wold-style-definition -Woverflow -Woverride-init -Wpacked -Wparentheses -Wpointer-arith -Wpointer-sign -Wpointer-to-int-cast -Wpragmas -Wreturn-type -Wsequence-point -Wshadow -Wshift-count-negative -Wshift-count-overflow -Wshift-negative-value -Wsizeof-array-argument -Wsizeof-pointer-div -Wsizeof-pointer-memaccess -Wstrict-aliasing -Wstrict-prototypes -Wswitch -Wswitch-bool -Wtautological-compare -Wtrigraphs -Wtype-limits -Wuninitialized -Wunknown-pragmas -Wunused -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-parameter -Wunused-result -Wunused-value -Wunused-variable -Wvarargs -Wvariadic-macros -Wvolatile-register-var -Wwrite-strings -Wno-missing-field-initializers -Wno-unused-parameter -fdiagnostics-show-option -g -O2 -Wl,-no_weak_imports -o .libs/gnutls-cli cli.o common.o socket.o benchmark-cipher.o benchmark.o benchmark-tls.o ocsptool-common.o -Wl,-framework -Wl,CoreFoundation  ../lib/.libs/libgnutls.dylib -L/usr/local/Cellar/p11-kit/0.23.20/lib -L/usr/local/Cellar/libtasn1/4.16.0/lib -L/usr/local/Cellar/nettle/3.4.1/lib -lm ../libdane/.libs/libgnutls-dane.dylib /private/tmp/gnutls-20200330-63870-c9h72u/gnutls-3.6.12/lib/.libs/libgnutls.dylib -lp11-kit -lidn2 -lunistring -ltasn1 -lnettle -lhogweed -lgmp -lunbound ./.libs/libcmd-cli.a libopts/.libs/libopts.a ../gl/.libs/libgnu.a gl/.libs/libgnu_gpl.a -lintl -framework CoreFoundation -framework Security
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [gnutls-cli] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

legolas:~ admin$ pkg-config --libs hogweed
-L/usr/local/Cellar/nettle/3.4.1/lib -lhogweed

legolas:~ admin$ ls -l /usr/local/Cellar/nettle/3.*/lib/libhogweed*
-rw-r--r--  1 admin  staff  210260 Mar 30 15:04 /usr/local/Cellar/nettle/3.4.1/lib/libhogweed.4.5.dylib
lrwxr-xr-x  1 admin  staff      20 Dec  4  2018 /usr/local/Cellar/nettle/3.4.1/lib/libhogweed.4.dylib -> libhogweed.4.5.dylib
-r--r--r--  1 admin  staff  346192 Dec  4  2018 /usr/local/Cellar/nettle/3.4.1/lib/libhogweed.a
lrwxr-xr-x  1 admin  staff      20 Dec  4  2018 /usr/local/Cellar/nettle/3.4.1/lib/libhogweed.dylib -> libhogweed.4.5.dylib

legolas:~ admin$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

legolas:~ admin$ brew reinstall nettle
==> Reinstalling nettle 
==> Downloading https://homebrew.bintray.com/bottles/nettle-3.4.1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/33/338da826ad5127a98f1658c01f2bd128aa9383b3581c9beebc0f0ebc88b0d089?__gda__=exp=1585595813~hmac=41c40dfd2304c616ea5ccdb81af37a1bf501b6d91efbb3ce3980fbe27fa0c72f&response-content-disposition=
######################################################################## 100.0%
==> Pouring nettle-3.4.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/nettle/3.4.1: 85 files, 2.1MB

  </pre>
</details>

## What you expected to happen

I expected brew to compile and install gnutls.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install --build-from-source gnutls

### PR DESCRIPTION
**Pull request by citosid**
Attempt to fix #52348 according to [this comment][1]. 

[1]: https://github.com/Homebrew/homebrew-core/issues/52348#issuecomment-611809279

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
It might be good idea to add a comment to the file saying what the `LDFLAGS=` is for.

**Comment by EricFromCanada** [comment]
Besides adding a link to [this issue](https://gitlab.com/gnutls/gnutls/-/issues/966), ideally this PR would also bump the formula to 3.6.13, since [some packages](https://github.com/Homebrew/homebrew-core/pull/53102) actively refuse to compile against earlier versions.

**Comment by citosid** [comment]
@EricFromCanada @Bo98, could you review the commit I just pushed?

I have one question though, the rb file has this:

```ruby
  bottle do
    sha256 "3368ca58ab6284e849a47ac03c5634b799d550f6348b9dd0794d68bc747c6ca6" => :catalina
    sha256 "f05a5a764d462c533d5f0777d3bedb3c26847255ce246c6b4eb8b6b2dfd18e15" => :mojave
    sha256 "323964700f54c32854c860baef7f310a8a8c6b886912c22cff6503cc42f5e224" => :high_sierra
  end
```

What are those hashes?

**Comment by EricFromCanada** [comment]
They're the hashes for the current bottle versions. You can ignore them; they'll be updated automatically by [Brew Test Bot](https://github.com/BrewTestBot).

**Comment by citosid** [comment]
@EricFromCanada the tests passed. Who should merge?

**Pull request closed without merging**
