### PR TITLE
acmetool: add HEAD build

### PR DESCRIPTION
**Pull request by CL-Jeremy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR adds the ability to build the formula with ```--HEAD``` to enable/transition to ACMEv2.

```brew test``` and ```brew audit``` aren't passing. For the test part I might be able to come up with something more meaningful. For the other I'd like to sort out with https://github.com/Homebrew/linuxbrew-core/pull/16264 first as I'm not quite sure about the current policy regarding ditching ```go_resource```, and whether that solution is sound.

Also, I'm not quite familiar about submitting PRs for Linuxbrew. Should I first work on Homebrew and then merge the result there? The diff is simply ```depends_on "libcap"```.

### CODE REVIEW

**Comment by issyl0** [comment]
> Also, I'm not quite familiar about submitting PRs for Linuxbrew. Should I first work on Homebrew and then merge the result there? The diff is simply depends_on "libcap".

Changes here get merged into Homebrew/linuxbrew-core at least once a day. Linux dependencies live in that repo for now, and periodically get merged back here in chunks. So this PR looks good to go, and you can add `depends_on "libcap"` in a separate PR to Homebrew/linuxbrew-core. Thanks!

**Comment by SMillerDev** [comment]
Doesn't head support go modules yet?

**Comment by CL-Jeremy** [comment]
> Doesn't head support go modules yet?

No, and I don't think the author intends to provide consistent builds with versioned dependencies. It might simply not matter for this project. The official CI (from which the official Copr is build - directly from CI binaries!) is dead for ages and the (outdated) official PPA did nothing more than calling ```make``` on a minimally patched Makefile - like I am doing here for the HEAD build. The author has gone inactive for a while, leaving several important PRs open.

The effort by the Debian team in this context is significant, but having that many dependency packages in the repo universe is undoubtedly impractical (they still keep on doing so).

So, either we keep this thing as is for the meantime, or if we intend to deprecate the current dependency staging functionality, we could embed the text definition of module into the formula, should that make more sense.

That leads me to another question to the Linuxbrew side. A PR quietly removed the frozen dependencies and let those fall back to golang's implicit dependency resolution, resulting in a versionless build, and bottled that binary for Linux. That seems really weird to me.

**Comment by CL-Jeremy** [comment]
Oh, another question, probably better asked at the Homebrew/brew repo: are HEAD builds supposed to be bottled? It's definitely broken, but somehow half works... (cf. https://github.com/hlandau/acmetool/issues/322#issuecomment-638711327). I am tempted to make a PR there but it still seems a silly thing to do.

**Comment by issyl0** [comment]
> ... are HEAD builds supposed to be bottled?

No, we only build bottles on Homebrew's infrastructure for stable, tagged releases (ie `acmetool v0.0.67`. `HEAD` builds exist for developer convenience, but are also officially unsupported by us.

**Comment by CL-Jeremy** [comment]
> No, we only build bottles on Homebrew's infrastructure for stable, tagged releases (ie `acmetool v0.0.67`). `HEAD` builds exist for developer convenience, but are also officially unsupported by us.

I mean, I actually thought of hosting bottles in my own tap. If I were to do that I suppose it's okay if it only works with devel (just tested for completeness' sake, cf. https://github.com/CL-Jeremy/homebrew-core/commit/775cd0b5df290148c53a5d9f8d0016344713e780) but not with head. As mentioned earlier, I actually managed to bottle the build, but pouring them resulted in an error – the steps were carried out successfully, just that it wasn't able to find ```$HOMEBREW_PREFIX/Cellar/acmetool/HEAD``` but got ```HEAD-<head hash>``` instead – which could be "fixed" by the following minimal patch, plus replacing the remaining instances of ```formula.prefix``` with ```@target_prefix```).
```diff --git a/Library/Homebrew/formula_installer.rb b/Library/Homebrew/formula_installer.rb
index 41298db9e..34ac64a87 100644
--- a/Library/Homebrew/formula_installer.rb
+++ b/Library/Homebrew/formula_installer.rb
@@ -47,6 +47,7 @@ class FormulaInstaller

   def initialize(formula)
     @formula = formula
+    @target_prefix = formula.prefix
     @link_keg = !formula.keg_only?
     @show_header = false
     @ignore_deps = false
@@ -293,17 +294,18 @@ class FormulaInstaller
     self.class.attempted << formula

     if pour_bottle?(warn: true)
+      @target_prefix = formula.rack/(Utils::Bottles.resolve_version formula.path)
       begin
         pour
       rescue Exception => e # rubocop:disable Lint/RescueException
```
But this eliminates the use of ```--HEAD``` and ```--devel``` completely for determining versions while pouring bottles. Again I can live with the current status (as ```--devel``` is deprecated anyway). Once we settle with a solution for dependency management, I'll be creating ```acmetool@0.2```, bump the revision of ```acmetool``` and have them bottled. Existing users will remain unaffected by the update, while new users will be greeted by a caveat that they will not be able to get new certificates and should use ```acmetool@0.2``` instead.

A preliminary ```go.mod``` looks like this:
```
module github.com/hlandau/acme

require (
    eithub.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 // indirect
    github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d // indirect
    github.com/btcsuite/winsvc v1.0.0 // indirect
    github.com/erikdubbelboer/gspt v0.0.0-20190125194910-e68493906b83 // indirect
    github.com/fatih/color v1.9.0 // indirect
    github.com/hlandau/buildinfo v0.0.0-20161112115716-337a29b54997 // indirect
    github.com/hlandau/dexlogconfig v0.0.0-20161112114350-244f29bd2608
    github.com/hlandau/goutils v0.0.0-20160722130800-0cdb66aea5b8
    github.com/hlandau/xlog v1.0.0
    github.com/jmhodges/clock v0.0.0-20160418191101-880ee4c33548
    github.com/mattn/go-colorable v0.1.6 // indirect
    github.com/mattn/go-runewidth v0.0.9 // indirect
    github.com/mitchellh/go-wordwrap v1.0.0
    github.com/ogier/pflag v0.0.1 // indirect
    github.com/peterhellberg/link v1.1.0
    github.com/satori/go.uuid v1.2.0
    github.com/shiena/ansicolor v0.0.0-20151119151921-a422bbe96644 // indirect
    github.com/stretchr/testify v1.6.1 // indirect
    golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
    golang.org/x/net v0.0.0-20200602114024-627f9648deb9
    gopkg.in/alecthomas/kingpin.v2 v2.2.6
    gopkg.in/cheggaaa/pb.v1 v1.0.28
    gopkg.in/hlandau/configurable.v1 v1.0.1 // indirect
    gopkg.in/hlandau/easyconfig.v1 v1.0.17
    gopkg.in/hlandau/service.v2 v2.0.16
    gopkg.in/hlandau/svcutils.v1 v1.0.10
    gopkg.in/square/go-jose.v1 v1.1.2
    gopkg.in/tylerb/graceful.v1 v1.2.15
    gopkg.in/yaml.v2 v2.3.0
)
```

**Pull request closed without merging**
