### PR TITLE
php@7.2 7.2.23

### PR DESCRIPTION
**Pull request by chapeupreto**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by SMillerDev** [comment]
Thanks @chapeupreto! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @chapeupreto !!

**Pull request closed without merging**
