### PR TITLE
borgbackup: switch to pypi source and update livecheck

### PR DESCRIPTION
**Pull request by chenrui333**
borgbackup: switch to pypi source

### CODE REVIEW

**Review by Rylan12 — COMMENTED** [review]
Maybe add the GitHub repo as `head`?

**Review by Rylan12 — APPROVED** [review]

**Comment by chenrui333** [comment]
not sure if actually make sense to include the head builds for the python formulae (considering the python resources), but it is what is for most of our python formulae right now 🤷‍♂️

**Comment by Rylan12** [comment]
I don't think it affects the resources, right? `brew install borgbackup --HEAD` will still download the resources I think.

**Comment by SeekingMeaning** [comment]
They'll still be downloaded, but they might (or might not) be outdated for `HEAD` (i.e. the developers could have updated the dependencies to newer versions)

**Pull request closed without merging**
