### PR TITLE
scala: Update to 2.13.0, add scala@2.12 & scala@2.13

### PR DESCRIPTION
**Pull request by dwijnand**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

PR #40793 is also doing this update, but it's a shallow approach (which is failing preflight checks).  I had these changes in-flight before that was submitted.

### CODE REVIEW

**Comment by dwijnand** [comment]
GitHub diff doesn't present it so I'll just describe that: `scala@2.12.rb` is a copy of what `scala.rb` was, with `:versioned_formula` added (and the formula renamed).

**Comment by fxcoudert** [comment]
- Not yet officially announced:
  Capture d’écran 2019-06-08 à 14 22 50
- Let's remove `scala@2.10`, it has low usage and apparently is not seeing further releases

**Comment by dwijnand** [comment]
> * Not yet officially announced:

Sure.  (Progress tracked in https://github.com/scala/scala-dev/issues/633)

> * Let's remove `scala@2.10`, it has low usage and apparently is not seeing further releases

Sure, done.

Also pushed some deprecation removals, which I'd accidentally left in my dirty workspace.

**Comment by dwijnand** [comment]
It's officially announced now:

image

https://www.scala-lang.org/

**Comment by dwijnand** [comment]
Review by @MikeMcQuaid, kindly?

**Comment by MikeMcQuaid** [comment]
Thanks @dwijnand! In future please only modify one formula per-commit.

**Comment by dwijnand** [comment]
Sure.  (Apologies if I missed that in that docs anywhere.)

**Pull request merged**
