### PR TITLE
bee 1.68

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by Moisan** [comment]
Test failure:
```
==> /usr/local/Cellar/bee/1.68/bin/bee -d /private/tmp/bee-test-20190513-3200-y6qe9u/bee dbchange:create new-file
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Bee - v. 1.68 - Bluesoft (2013-2019) - GPL - All rights reserved
Exception in thread "main" java.lang.NullPointerException: Cannot invoke method validateParameters() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:43)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at br.com.bluesoft.bee.runner.BeeModule.parseOptions(BeeModule.groovy:16)
	at br.com.bluesoft.bee.runner.BeeModule$parseOptions$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at br.com.bluesoft.bee.runner.BeeModule.run(BeeModule.groovy:25)
	at br.com.bluesoft.bee.runner.BeeModule$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at br.com.bluesoft.bee.Bee.main(Bee.groovy:103)
Error: bee: failed
```

**Comment by chenrui333** [comment]
@Moisan ack.

**Comment by angeliski** [comment]
@chenrui333 You can update the version to 1.69?

**Comment by chenrui333** [comment]
@angeliski sure, I will do it.

**Comment by angeliski** [comment]
@chenrui333 You can update the test too?
The line 25 should be `system bin/"bee", "-d", testpath/"bee", "dbchange:create", "new-file"` 
to work properly

**Comment by chenrui333** [comment]
@angeliski sure, thanks! 😄

**Comment by chenrui333** [comment]
failed in my local.
```
$ brew test bee
Testing bee
==> /usr/local/Cellar/bee/1.69/bin/bee -d /private/tmp/bee-test-20190516-39382-k8gx6a/bee dbchange:creat
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/bee/test.01.bee:
	at br.com.bluesoft.bee.dbchange.DbChangeManager$createDbChangeFile.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at br.com.bluesoft.bee.dbchange.BeeDbChangeCreateAction.run(BeeDbChangeCreateAction.groovy:11)
	at br.com.bluesoft.bee.runner.ActionRunner$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at br.com.bluesoft.bee.runner.BeeModule.run(BeeModule.groovy:27)
	at br.com.bluesoft.bee.runner.BeeModule$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at br.com.bluesoft.bee.Bee.main(Bee.groovy:108)
Error: bee: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1914:in `block in system'
```

**Comment by chenrui333** [comment]
Push a new commit for visibility.

**Comment by chenrui333** [comment]
@angeliski looks like there is new release, I will try with `1.70`.
Once that passed, I will create a new PR.

**Comment by chenrui333** [comment]
relates to https://github.com/bluesoft/bee/releases/tag/1.70

**Comment by angeliski** [comment]
@chenrui333 You can update the version to 1.71?
I made a local test, that version will work.

**Comment by chenrui333** [comment]
Sure, I will to bee-1.71!

**Comment by chenrui333** [comment]
@angeliski looks good with bee-1.71, will file a new PR now :)

**Comment by chenrui333** [comment]
Thanks @angeliski !

**Pull request closed without merging**
