### PR TITLE
pango 1.44.0

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tschoonj** [comment]
@MikeMcQuaid @fxcoudert 

Any thoughts on how to fix the remaining [issue](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/45806/):

```
Error: Cannot install pcb because conflicting formulae are installed.
  gts: because both install a `gts.h` header

```

**Comment by tschoonj** [comment]
@MikeMcQuaid if you have a moment, could you take a look at these failures please? 

Thanks!

**Comment by MikeMcQuaid** [comment]
@tschoonj That failure can kinda just be ignored as it's going to try and install them both at once so can't test them both. I recommend ignoring and then immediately kicking off another PR making a non-revision change to the relevant formula to test if it's broken (I suspect it won't be).

**Comment by tschoonj** [comment]
Hi @MikeMcQuaid, can you merge this one in? Afterwards I will open PRs for `pcb` and `gts`

Thanks!

**Comment by MikeMcQuaid** [comment]
@tschoonj I can but is there a reason you'd like me to rather than doing so yourself? Are you unable to for some reason (I'd love to fix that if possible). Thanks!

**Comment by tschoonj** [comment]
I haven't had commit privileges for quite some time AFAIK... which is absolutely fine btw!

**Comment by MikeMcQuaid** [comment]
@tschoonj I double-checked and it seems you do? Can you try and merge/push and message me on Slack with any errors you experience. Thanks!

**Comment by tschoonj** [comment]
How does this work again? Haven't done this in like two years or so...

**Comment by MikeMcQuaid** [comment]
@tschoonj `brew pull --bottle https://github.com/Homebrew/homebrew-core/pull/42536`, verify the output, `git rebase origin/master`, `git push`.

**Comment by retokromer** [comment]
FYI: on my end, this gives: 

```
==> Upgrading 1 outdated package:
pango 1.42.4_2 -> 1.44.3
==> Upgrading pango 
==> Downloading https://homebrew.bintray.com/bottles/pango-1.44.3.mojave.bottle.

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "pango"
Download failed: https://homebrew.bintray.com/bottles/pango-1.44.3.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

(Building from source works fine.)

**Comment by tschoonj** [comment]
I know... I screwed up... It will be fixed later today

**Comment by lembacon** [comment]
I've republished those bottles, this should have been fixed now.

**Comment by tschoonj** [comment]
Many thanks @lembacon!

**Comment by retokromer** [comment]
Yep, @lembacon, it works fine now. Thanks!

**Pull request closed without merging**
