### PR TITLE
netperf: remove as non-free

### PR DESCRIPTION
**Pull request by cho-m**
The latest 2.7.0 release is under a non-free license as defined by DFSG. However, the last commit in HEAD does switch the license to MIT but there has been no new release including this change.

See https://github.com/HewlettPackard/netperf/commit/3bc455b23f901dae377ca0a558e1e32aa56b31c4

---

Alternatively, we could distribute the latest commit. This is what Debian and Fedora do.

There is a large number of repositories that do ship `netperf` in case that is important in our decision - https://repology.org/project/netperf/versions

On the other hand, the install count within Homebrew isn't that high:
```
install: 23 (30 days), 78 (90 days), 414 (365 days)
install-on-request: 23 (30 days), 78 (90 days), 414 (365 days)
build-error: 0 (30 days)
```

### CODE REVIEW

**Comment by sgerrand** [comment]
> Alternatively, we could distribute the latest commit. This is what Debian and Fedora do.

This gets my non-maintainer vote as an end user.

**Review by p-linnane — APPROVED** [review]
Are we able to patch in the latest commit with the license change? Otherwise I think we should remove this.

**Review by SMillerDev — APPROVED** [review]

**Comment by cho-m** [comment]
> Are we able to patch in the latest commit with the license change? Otherwise I think we should remove this.

Pretty large commit due to modifying every file with new license. Given there are commits between this and last release (2015-07-20), I doubt it cleanly applies.

**Comment by p-linnane** [comment]
>A license is only really valid if we cherry picked every change in between too. While upstream signed off the state at the time the license change, they did not sign off the previous release.
> 
> ([HewlettPackard/netperf@`netperf-2.7.0...3bc455b23f901dae377ca0a558e1e32aa56b31c4`.patch](https://github.com/HewlettPackard/netperf/compare/netperf-2.7.0...3bc455b23f901dae377ca0a558e1e32aa56b31c4.patch))

I hadn't checked to see the full diff. If it's that much...then we should definitely remove this.

**Pull request merged**
