### PR TITLE
kubernetes-helm: include option to bundle tiller

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by cblecker** [comment]
@ilovezfs here's that odd kubernetes-helm commit issue again. The test I wrote caught it. For some reason, there's a different git commit coming out of CI than the checked out repo. Locally, this works every time with the right commit.

**Comment by cblecker** [comment]
Including these changes in https://github.com/Homebrew/homebrew-core/pull/13178

**Comment by ilovezfs** [comment]
@cblecker wow. well at least we know where the revision is coming from now: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/289/console

**Comment by ilovezfs** [comment]
CC @MikeMcQuaid there's a rather nasty `test-bot` that's causing the git revision from the CI checkout intermittently to override the git revision of the tag. @cblecker's [test](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-helm.rb#L51) just caught it happening again https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/289/version=sierra/testReport/junit/brew-test-bot/sierra/test_kubernetes_helm/

**Pull request closed without merging**
