### PR TITLE
lazygit 0.7.2

### PR DESCRIPTION
**Pull request by jesseduffield**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-- I'm getting an error running this, similar to in this issue: https://github.com/Homebrew/brew/issues/5561
I can't see a clear outcome for that. Looks like CI runs the audit anyway though so I'm ticking this box

-----

### CODE REVIEW

**Comment by jesseduffield** [comment]
hey it passed CI :) Can I get some eyes on this PR?

**Comment by SMillerDev** [comment]
Looks good to me

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thank you @jesseduffield for your contribution to Homebrew!

**Pull request closed without merging**
