### PR TITLE
sqlite 3.35.4

### PR DESCRIPTION
**Pull request by cho-m**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Only ARM failure is
```
Error: 1 failed step!
brew test --retry --verbose cash-cli
```
However, this looks to be pre-existing, as `cash-cli`'s test fails even before the `sqlite` version bump.

**Comment by carlocab** [comment]
We're about to hit the 3-day timeout, and it doesn't look like the CI run is going to finish. However, it's taken so long because of two formulae with problematic tests that I think I've fixed now (#74592, #74567).

Rebased against master to pull in those fixes.

**Comment by carlocab** [comment]
ARM:

```
Error: 1 failed step!
brew test --retry --verbose cash-cli
```

Big Sur: TBD

Catalina:

```
Error: 6 failed steps!
brew test --retry --verbose caffe
brew test --retry --verbose cash-cli
brew test --retry --verbose howdoi
brew test --retry --verbose hyperkit
brew test --retry --verbose wasm-pack
brew test --retry --verbose youtube-dlc
```

Mojave:

```
Error: 7 failed steps!
brew test --retry --verbose cash-cli
brew test --retry --verbose howdoi
brew test --retry --verbose hyperkit
brew test --retry --verbose opencascade
brew test --retry --verbose swift
brew test --retry --verbose wasm-pack
brew test --retry --verbose youtube-dlc
```

The Catalina runner looks like it encountered a pretty bad failure.

**Comment by carlocab** [comment]
The logs are a lot to get through right now, but these failures need investigating:
- `caffe`
- `dynare`
- `libtensorflow`

If `dynare` is just a test timeout, then it should be safe to ignore.

**Comment by cho-m** [comment]
Just looking at log output...

`caffe test` seems to be timing out. In 11.0 logs, it gets to 41 out of 50 iterations before Homebrew test times out.
```
2021-04-06T19:53:00.4956750Z ==> /usr/local/Cellar/caffe/1.0_31/bin/caffe test -model /usr/local/Cellar/caffe/1.0_31/share/caffe/models/bvlc_reference_caffenet/deploy.prototxt -solver /usr/local/Cellar/caffe/1.0_31/share/caffe/models/bvlc_reference_caffenet/solver.prototxt -weights bvlc_reference_caffenet.caffemodel
...
2021-04-06T19:53:00.6702660Z I0406 20:43:28.632457 227286528 caffe.cpp:290] Running for 50 iterations.
...
2021-04-06T19:54:12.1914030Z I0406 20:52:57.932752 168484352 caffe.cpp:313] Batch 41, prob = 0.000966262
2021-04-06T19:54:12.1916750Z Error: caffe: failed
2021-04-06T19:54:12.1918070Z An exception occurred within a child process:
2021-04-06T19:54:12.1925640Z   Timeout::Error: execution expired
2021-04-06T19:54:12.1929010Z /usr/local/Homebrew/Library/Homebrew/formula.rb:2102:in `write'
```

`libtensorflow` install runs out of disk space.
```
2021-04-07T09:13:13.3160150Z ==> Pouring libtensorflow-2.4.1.big_sur.bottle.tar.gz
2021-04-07T09:13:13.3162260Z cp: /usr/local/Cellar/libtensorflow/2.4.1/bin/transform_graph: No space left on device
2021-04-07T09:13:13.3164340Z cp: /usr/local/Cellar/libtensorflow/2.4.1/.brew: No space left on device
```

**Comment by carlocab** [comment]
Thanks for looking into this, @cho-m. It would be good to test `caffe` and `libtensorflow` locally just to be sure. I'll try to find time to do this soon.

**Review by carlocab — APPROVED** [review]
Managed to test `caffe` and `libtensorflow` on Big Sur locally. They're fine. `dynare` was an execution timeout, which happens sometimes.

Thanks, @cho-m!

**Pull request closed without merging**
