### PR TITLE
ice - fix sha256

### PR DESCRIPTION
**Pull request by externl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The tag was moved, so new sha. No need to rebuild bottles, nothing affecting brew was changed with new tag.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Was an issue reported upstream about the retagging?

**Comment by externl** [comment]
I work for upstream, we had to move to the tag.

**Comment by SMillerDev** [comment]
Is there any public record of this? And is there a way to know the difference between a tag and a release?

**Comment by externl** [comment]
No, we moved the tag before finishing our full release. During building of all of our packages we realized we needed to move the tag. Unfortunately someone noticed that we tagged and quickly submitted a PR to brew. The change is minor and affected a js file not included by anything brew builds.

**Comment by externl** [comment]
Is there anything else needed to be done here?

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Pull request merged**
