### PR TITLE
mono 5.12.0.226

### PR DESCRIPTION
**Pull request by Hazardius**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
@ilovezfs Should we drop `fsharp` from `mono`, the `4.1.23` tag is almost a year old?

**Comment by Hazardius** [comment]
Maybe `fsharp` can stay in the formula as an option? I suppose it was put in there for some reason.
After quick search I couldn't find any separate `fsharp` formula and [`README.md` file of `fsharp`](https://github.com/fsharp/fsharp/blob/master/README.md) points out to this one as a way of installing it with homebrew.

**Comment by fxcoudert** [comment]
Can't we update it to the latest version, i.e. either 4.1.34 or 10.0.2? (they changed version numbering scheme recently)

**Comment by Hazardius** [comment]
screen shot 2018-06-14 at 09 50 49
I just checked [their page](https://www.mono-project.com/download/stable/) and `5.12.0.226` is still the most recent Stable version in there - as shown on the screenshot.

**Comment by Hazardius** [comment]
We may change it to the latest one present in the [fsharp sources on the mono page](http://download.mono-project.com/sources/fsharp/) - `4.1.33`.

**Comment by Hazardius** [comment]
Just found out issue #21607.
I'm reverting changes for `fsharp` update in this PR.

**Comment by ilovezfs** [comment]
Based on https://github.com/mono/msbuild/releases it looks like we should be able to build msbuild with mono now.

**Comment by ilovezfs** [comment]
It may also be possible to just use those bootstrapper versions of msbuild directly.

**Comment by ilovezfs** [comment]
We should be able to build the new fsharp with this diff
```
diff --git a/Formula/mono.rb b/Formula/mono.rb
index 5d715d3..4890ca8 100644
--- a/Formula/mono.rb
+++ b/Formula/mono.rb
@@ -36,6 +36,12 @@ class Mono < Formula
         :revision => "95b66263420b62ae0e246bd1bf3c2641e9fb9625"
   end
 
+  resource "msbuild" do
+    url "https://github.com/mono/msbuild/releases/download/v0.05/mono_msbuild_port2-394a6b5e.zip"
+    version "0.05"
+    sha256 "b832ccf29ede89724f9217fe074f688e011dc15dd9ada2258f4caf6ae2c992e8"
+  end
+
   def install
     args = %W[
       --prefix=#{prefix}
@@ -56,6 +62,8 @@ class Mono < Formula
     # Now build and install fsharp as well
     if build.with? "fsharp"
       resource("fsharp").stage do
+        (Pathname.pwd/"msbuild").install resource("msbuild")
+        ENV.prepend_path "PATH", Pathname.pwd/"msbuild"
         ENV.prepend_path "PATH", bin
         ENV.prepend_path "PKG_CONFIG_PATH", lib/"pkgconfig"
         system "./autogen.sh", "--prefix=#{prefix}"
```
That's not really what that particular `msbuild` is intended for, but I don't think we need to be overly picky unless someone finds a problem with the resultant F#.

**Comment by ldexterldesign** [comment]
@Hazardius 🍻 https://discourse.brew.sh/t/update-for-mono/2064/3?u=ldexterldesign

**Comment by ilovezfs** [comment]
Thanks again @Hazardius!

**Comment by ldexterldesign** [comment]
Hey all,

Hope you're well

Thanks for software

I followed the mono uninstall instructions[s] then installed homebrew mono and now none of my (mono-dependant) apps work 😞

I reinstalled the mono-dependant apps again with homebrew in the hope any links would get updated but no luck. If I use mono installer the mono-dependant apps run fine.

I ran ``find / -name "mono" -print`` (feel free to suggest a better command) on my file system after both installer and homebrew uninstalls which didn't uncover any uninstall remnants so the uninstalls seem pretty clean

Before I pursue mono on how to cleanly uninstall are there any homebrew linkages that need to happen on install?

Happy to migrate this to an issue if preferred

Let me know if you have any issues - happy to help

Hope to hear back

Thanks (in advance)

[s] http://www.mono-project.com/docs/about-mono/supported-platforms/osx/#uninstalling-mono-on-mac-os-x

**Comment by ldexterldesign** [comment]
Hey @hazardius,

Thanks for reply, I know this will be a ballache for anyone not running OS X to bother with

Sorry if I wasn't clear, I have (always had) both sonarr and radarr installed via ``brew cask``:

> I reinstalled the mono-dependant apps again with homebrew in the hope any links would get updated but no luck. If I use the standalone the mono-dependant apps run fine.

As you mention, jackett isn't currently available via homebrew so I just have a standalone install

> I don't really think it's homebrew-core's issue, but maybe you can post some error messages that pops up when those apps aren't working?

I'm inclined to agree, after having mono, sonarr and radarr all running off homebrew installs and, with jackett functioning fine, then reverting to the same setup (albeit with the latest hombrew mono version) touching the mono standalone install has broken everything

https://github.com/Radarr/Radarr/issues/2840#issuecomment-397821976 - at first this comment made me feel completely inept but I knew/know just enough about Docker not to dismiss it...

Quick parlay into Docker[r] land and I see this:

screen shot 2018-06-18 at 01 07 10

Is python a mono dependency?:

If yes, perhaps I should ensure I have homebrew python installed - don't know why homebrew doesn't take care of this

If no, ignore me, my hunch is way off

Hope to hear back

Cheers

[r] https://github.com/Jackett/Jackett#installation-using-docker > https://hub.docker.com/r/linuxserver/jackett/

**Pull request closed without merging**
