### PR TITLE
docbook-xsl 1.79.2

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Since https://lists.oasis-open.org/archives/docbook-apps/201612/msg00011.html,
docbook-xsl has moved to github. This is also the version distributed by arch-linux.

**Comment by ilovezfs** [comment]
Sorry passing on this. It causes a ton of problems.

**Comment by monofy** [comment]
So how can i solve this issue??? I am trying to install libimobiledevice which pulls systemd which fails due to docbook-xsl. As I understand this issue is solved with docbook-xsl 1.79.2. Tried to install it thru brew but i couldn’t do it. Are there any other solutions that might solve this issue?

**Comment by ilovezfs** [comment]
Does
```
--- docbook-xsl-1.78.1+dfsg.orig/docbook-xsl/lib/lib.xsl
+++ docbook-xsl-1.78.1+dfsg/docbook-xsl/lib/lib.xsl
@@ -10,7 +10,10 @@
      This module implements DTD-independent functions
 
      ******************************************************************** -->
-<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
+<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
+                xmlns:str="http://exslt.org/strings"
+                exclude-result-prefixes="str"
+                version="1.0">
 
 <xsl:template name="dot.count">
   <!-- Returns the number of "." characters in a string -->
@@ -56,6 +59,9 @@
   <xsl:param name="replacement"/>
 
   <xsl:choose>
+    <xsl:when test="function-available('str:replace')">
+      <xsl:value-of select="str:replace($string, string($target), string($replacement))"/>
+    </xsl:when>
     <xsl:when test="contains($string, $target)">
       <xsl:variable name="rest">
         <xsl:call-template name="string.subst">
```
fix it?

**Comment by iMichka** [comment]
It's a shame that it breaks other stuff. The project seems a little bit dead anyway, as there was no activity since some time on it.

I tried that patch, and it failed to apply. Just had another look, and in fact the paths need to be fixed, as this is "wrong":
```
--- docbook-xsl-1.78.1+dfsg.orig/docbook-xsl/lib/lib.xsl
+++ docbook-xsl-1.78.1+dfsg/docbook-xsl/lib/lib.xsl
```

I'll continue the discussion/test on the linuxbrew repo, as this does not seem to be an issue for mac. Thanks :)

**Comment by ilovezfs** [comment]
@iMichka it's from the Debian tarball's debian/patches directory if that helps: http://http.debian.net/debian/pool/main/d/docbook-xsl/docbook-xsl_1.79.1+dfsg-2.debian.tar.xz

**Pull request closed without merging**
