### PR TITLE
qt 5.14.0

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like the build failure is due to the flaky postinstall with `shared-mime-info` seen in https://github.com/Homebrew/homebrew-core/pull/47795 https://github.com/Homebrew/homebrew-core/issues/38213. This can probably be merged despite the test issue.

**Comment by droidmonkey** [comment]
KeePassXC team would appreciate this merge very soon because 5.13 exhibits several bugs with file dialogs.

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by SMillerDev** [comment]
@droidmonkey we don't really merge builds that aren't passing CI. Maybe you can help resolve the CI issues?

**Comment by droidmonkey** [comment]
Sure I can take a look

**Comment by scpeters** [comment]
[failed: brew install --only-dependencies dynare](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/53827/version=mojave/testReport/junit/brew-test-bot/mojave/install___only_dependencies_dynare/) on mojave and catalina, but I don't see what the error was; it looked like the dependencies all installed correctly

**Comment by jonchang** [comment]
I think I finally fixed the shared-mime-info postinstall issue. That was an interesting one to track down!

**Comment by fxcoudert** [comment]
The High Sierra bottle was not produced correctly (json file missing) during archiving. Retriggering a build.

@BrewTestBot test this please

**Comment by bayandin** [comment]
Looks good now, thanks @yurikoles

**Pull request closed without merging**
