### PR TITLE
istioctl 1.18.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Copying /private/tmp/istioctl-20230607-4535-17aw0bt/out/linux_arm64/release/ztunnel-1d4a38f0fbeaecd63501b047645e9f7b03b9a133 to /private/tmp/istioctl-20230607-4535-17aw0bt/out/linux_arm64/release/ztunnel
  /private/tmp/istioctl-20230607-4535-17aw0bt
  Copying '/private/tmp/istioctl-20230607-4535-17aw0bt/out/linux_arm64/release/ztunnel-1d4a38f0fbeaecd63501b047645e9f7b03b9a133' to /private/tmp/istioctl-20230607-4535-17aw0bt/out/linux_arm64/ztunnel
  
  real	0m1.953s
  user	0m0.417s
  sys	0m0.110s
  cp: usr/local/bin/envoy: No such file or directory
  Unexpected failure
```

**Comment by chenrui333** [comment]
- relates to https://github.com/istio/istio/pull/43414

**Comment by chenrui333** [comment]
have some issues building ztunnel in my local, but I think we should also modify the build process as well (the build is actually downloading the pre-built binaries)

**Comment by osalbahr** [comment]
> * relates to [ambient upsteam: upstream most of the misc stuff istio/istio#43414](https://github.com/istio/istio/pull/43414)

Looks like it got merged. Should this PR get reopened?

**Comment by chenrui333** [comment]
> > * relates to [ambient upsteam: upstream most of the misc stuff istio/istio#43414](https://github.com/istio/istio/pull/43414)
> 
> Looks like it got merged. Should this PR get reopened?

build got changed.

**Comment by chenrui333** [comment]
#137088

**Pull request closed without merging**
