### PR TITLE
dfix: build on Apple Silicon using `ldc`

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
I'm guessing there is something wrong in current version of `dmd` for Intel Monterey bottle. Seems to be failing on all DLang-based PRs I created even though there is no change related to that build.

**Comment by danielnachun** [comment]
What's the failure we are hitting for `dmd` for Monterey?  I feel like this is something we should investigate before switching compiler tool chains.

**Comment by Bo98** [comment]
I agree with the switch to ldc since dmd lacks a range of architectures, but if there's something broken with dmd we should also fix that.

**Comment by cho-m** [comment]
Monterey linker failure:
```
dmd src/dfix.d libdparse/src//dparse/rollback_allocator.d libdparse/src//dparse/ast.d libdparse/src//dparse/entities.d libdparse/src//dparse/stack_buffer.d libdparse/src//dparse/lexer.d libdparse/src//dparse/formatter.d libdparse/src//dparse/parser.d libdparse/src//std/experimental/lexer.d stdx-allocator/source//stdx/allocator/common.d stdx-allocator/source//stdx/allocator/package.d stdx-allocator/source//stdx/allocator/building_blocks/free_list.d stdx-allocator/source//stdx/allocator/building_blocks/bucketizer.d stdx-allocator/source//stdx/allocator/building_blocks/package.d stdx-allocator/source//stdx/allocator/building_blocks/quantizer.d stdx-allocator/source//stdx/allocator/building_blocks/region.d stdx-allocator/source//stdx/allocator/building_blocks/segregator.d stdx-allocator/source//stdx/allocator/building_blocks/affix_allocator.d stdx-allocator/source//stdx/allocator/building_blocks/scoped_allocator.d stdx-allocator/source//stdx/allocator/building_blocks/kernighan_ritchie.d stdx-allocator/source//stdx/allocator/building_blocks/null_allocator.d stdx-allocator/source//stdx/allocator/building_blocks/fallback_allocator.d stdx-allocator/source//stdx/allocator/building_blocks/allocator_list.d stdx-allocator/source//stdx/allocator/building_blocks/bitmapped_block.d stdx-allocator/source//stdx/allocator/building_blocks/free_tree.d stdx-allocator/source//stdx/allocator/building_blocks/stats_collector.d stdx-allocator/source//stdx/allocator/typed.d stdx-allocator/source//stdx/allocator/gc_allocator.d stdx-allocator/source//stdx/allocator/showcase.d stdx-allocator/source//stdx/allocator/internal.d stdx-allocator/source//stdx/allocator/mmap_allocator.d stdx-allocator/source//stdx/allocator/mallocator.d -Ilibdparse/src/ -Istdx-allocator/source/ -wi -g -dip25 -ofbin/dfix
  libdparse/src//dparse/rollback_allocator.d(28): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
  libdparse/src//dparse/lexer.d(1862): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
  libdparse/src//dparse/lexer.d(2057): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
  libdparse/src//dparse/lexer.d(2156): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
  libdparse/src//dparse/lexer.d(2204): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
  libdparse/src//dparse/parser.d(4075): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
  ld: section __DATA/__thread_bss has type zero-fill but non-zero file offset file 'bin/dfix.o' for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Error: linker exited with status 1
  make: *** [dfix_binary] Error 1
```

---

Based on https://wiki.dlang.org/Compilers, `ldc` and `gdc` should produce faster/optimized binaries.

ArchLinux also builds everything with `ldc`: https://archlinux.org/packages/community/x86_64/ldc/

I chose to avoid both on Homebrew's Linux build to avoid risk of pulling in new runtime dependencies on either LLVM or GCC libraries.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
