### PR TITLE
trzsz 1.0.0

### PR DESCRIPTION
**Pull request by lonnywong**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
Thanks @lonnywong.
Duplicate of #97835

**Comment by lonnywong** [comment]
> Thanks @lonnywong. Duplicate of #97835

Thanks.

**Comment by chenrui333** [comment]
`trzsz 1.0.0` is shipped. :)

**Comment by lonnywong** [comment]
> `trzsz 1.0.0` is shipped. :)

I tested it. It works. Thanks again.

**Comment by lonnywong** [comment]
I removed `trzsz-iterm2` package from `trzsz`.

Maybe I should add `trzsz-iterm2` back to `extras_require` in the next version.

**Comment by chenrui333** [comment]
> I removed `trzsz-iterm2` package from `trzsz`.

Any reference links?

> Maybe I should add `trzsz-iterm2` back to `extras_require` in the next version.

Right now, it is already managed as below (do you mean specify in the `setup.py`?)

https://github.com/Homebrew/homebrew-core/blob/cce34c7d5d6dc013611507a2b9540ecbf1ef2fed/pypi_formula_mappings.json#L496-L499

**Comment by lonnywong** [comment]
> 
> Right now, it is already managed as below (do you mean specify in the `setup.py`?)

Yes, I will specify it in the `setup.py` in the next version.

**Pull request closed without merging**
