### PR TITLE
asciiquarium: run with system perl

### LINKED ISSUE #4936: asciiquarium segfaults with brewed perl
`asciiquarium` is segfaulting for me on OS X 10.11, both when poured from bottle and installed from source.

```
[~]
$ brew install asciiquarium
==> Downloading https://homebrew.bintray.com/bottles/asciiquarium-1.1.el_capitan.bottle.ta
Already downloaded: /Users/janke/Library/Caches/Homebrew/asciiquarium-1.1.el_capitan.bottle.tar.gz
==> Pouring asciiquarium-1.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/asciiquarium/1.1: 16 files, 366.7K
[~]
$ asciiquarium
[1]    40607 segmentation fault  asciiquarium
[✘ ~]
$
```

Updating the `Curses` resource to the latest did not fix.

Is this still working for people on earlier versions of OS X? Should we put a `MaximumMacOS` requirement on this or boneyard it?

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

This fixes a segfault on 10.11 with brewed perl installed.

Fixes #4936.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍

**Comment by zmwangx** [comment]
Pretty sure this doesn't fix anything: the problem is in runtime selection of `perl` with `#!/usr/bin/env perl` shebang in `libexec/bin/asciiquarium`. Building with a hard coded `/usr/bin/perl` (already that way when we built the bottles) just makes it a certain death when `#!/usr/bin/env perl` selects brewed perl.

**Comment by ilovezfs** [comment]
yes, @zmwangx is correct as mentioned here: https://github.com/Homebrew/homebrew-core/issues/4936#issuecomment-247830251

**Comment by apjanke** [comment]
You're right: it only appeared to work because my brewed `perl` was still unlinked from the last time I was working with `asciiquarium`. Closing.

**Pull request closed without merging**
