### PR TITLE
cargo-crev: remove `rust` dependency except for building

### PR DESCRIPTION
**Pull request by rami3l**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Resolves https://github.com/Homebrew/homebrew-core/pull/134129#issuecomment-1596781336.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Thanks! This seems to also vendor `libgit2`, `libssh2`, and `openssl` (let's use `@3`).

Can we see if we can replace those with Homebrew versions so those dependencies can get updated independently of version bumps to `cargo-crev`? This will need a `--no-default-features` flag too.

**Comment by rami3l** [comment]
It is impossible to use `openssl@3` with this formula at the moment:

```
cargo-crev
    * cargo-crev contains conflicting version recursive dependencies:
        openssl@1.1, openssl@3
      View these with `brew deps --tree cargo-crev`.
  Error: 1 problem in 1 formula detected
```

**Comment by carlocab** [comment]
Ok, let's use `openssl@1.1` here then.

**Comment by rami3l** [comment]
`cargo-crev` unfortunately does not build with `libgit2@1.5`.

**Comment by rami3l** [comment]
@carlocab Since `cargo-crev` always links with `libgit2` and `libssh2` statically, I have reverted most changes and choose to link it dynamically with `openssl@3` only.

**Review by carlocab — APPROVED** [review]
Thanks!

The `libgit2` problem is actually because the `libgit2-sys` crate this wants to use is too old and requires `libgit2` 1.4, which is no longer supported.

This project needs to update their dependencies so they stop using an unmaintained `libgit2`.

**Pull request merged**
