### PR TITLE
azure-cli: use python-certifi

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by p-linnane** [comment]
I think upstream has some kind of automation that will cause problems with this...

cc @Homebrew/core for thoughts

**Comment by chenrui333** [comment]
> I think upstream has some kind of automation that will cause problems with this...
> 
> cc @Homebrew/core for thoughts

yeah, this cannot be using the vendor version, same deal for cffi, pycparser, pyyaml stuff

**Comment by woodruffw** [comment]
Makes sense. Probably a close here then?

**Comment by p-linnane** [comment]
Unfortunately. Wondering if we should open an issue with upstream regarding all these problems. I know @singingwolfboy had some PR's that were waiting for months to help resolve them.

**Comment by chenrui333** [comment]
let's close it for now. (need upstream issue for this)

**Pull request closed without merging**
