### PR TITLE
micronaut: pin openjdk version to 11 for M1 support

### PR DESCRIPTION
**Pull request by areese**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

```
 % brew reinstall micronaut --build-from-source      
==> Downloading https://github.com/micronaut-projects/micronaut-starter/archive/v2.4.4.tar.gz
Already downloaded: Library/Caches/Homebrew/downloads/0804fb19a859147b69edd1b737af8cb85a084cf043e4ff7850f9d43ab2de0959--micronaut-starter-2.4.4.tar.gz
==> Reinstalling micronaut 
==> ./gradlew micronaut-cli:assemble -x test
🍺  /opt/homebrew/Cellar/micronaut/2.4.4_1: 66 files, 27.3MB, built in 18 seconds
 % brew test micronaut                               
==> Testing micronaut
==> /opt/homebrew/Cellar/micronaut/2.4.4_1/bin/mn create-app hello-world
 % brew audit --strict micronaut 
 % mn --version
Micronaut Version: 2.4.4
 % mn          
mn> 
Unmatched argument at index 0: ''
Usage: mn [-hvVx] [COMMAND]
Micronaut CLI command line interface for generating projects and services.
Application generation commands are:

*  create-app NAME
*  create-cli-app NAME
*  create-function-app NAME
*  create-grpc-app NAME
*  create-messaging-app NAME

Options:
  -h, --help         Show this help message and exit.
  -v, --verbose      Create verbose output.
  -V, --version      Print version information and exit.
  -x, --stacktrace   Show full stack trace when exceptions occur.

Commands:
  create-app            Creates an application
  create-cli-app        Creates a CLI application
  create-function-app   Creates a Cloud Function
  create-grpc-app       Creates a gRPC application
  create-messaging-app  Creates a messaging application
mn> create-cli-app foo
| Application created at /opt/homebrew/Library/Taps/homebrew/homebrew-core/foo
mn> 
 % 
```

### CODE REVIEW

**Comment by carlocab** [comment]
You need to pass `"11"` to ` Language::Java.overridable_home_env`

**Comment by cho-m** [comment]
Note, this will cause a merge conflict in openjdk PR #72535
If we plan to merge that one, we should hold off on any changes that can cause conflicts.

**Comment by areese** [comment]
@carlocab I was wondering, I tried java_version: 11.  I'll figure out how to pass 11.
@cho-m I guess I should update to a newer Micronaut as well to avoid the merge conflict.
I'll work on that thank you

**Comment by areese** [comment]
@cho-m Would you like me to remove the gradle dep?  it looks like `golo.rb` uses `gradlew` and doesn't have a gradle build dep.

Pushing a new fix to not conflict with https://github.com/Homebrew/homebrew-core/pull/72535/files

**Comment by areese** [comment]
@carlocab  Updated to pass "11" in
@cho-m Updated micronaut version to 2.5.4 to avoid merge conflict, and removed gradle dep as gradlew is being used.

still passes brew test and brew audit --strict on m1.

**Comment by carlocab** [comment]
Seems to have tested fine in #72535 though. Maybe we don't need this anymore?

**Comment by areese** [comment]
We don’t if openjdk16 works

**Comment by cho-m** [comment]
@carlocab @areese We still need it for ARM since we are running JDK17 there.
Also haven't bottled ARM yet.

`micronaut` restricts the JDKs that are supported https://github.com/micronaut-projects/micronaut-starter/blob/v2.5.4/starter-core/src/main/java/io/micronaut/starter/options/JdkVersion.java#L31 to LTS releases and latest GA:
```java
public enum JdkVersion {
    JDK_8(8),
    JDK_11(11),
    JDK_16(16);
```

Whether we want to downgrade both Intel & ARM or just ARM to `openjdk@11` is a side question.

**Comment by areese** [comment]
Ok I’ll see if I restrict 11 to just arm tomatoes tomoo

**Pull request closed without merging**
