### PR TITLE
vault 1.5.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Review by dtrodrigues — COMMENTED** [review]
Can the hard-coded port 8200 in the test be removed?

**Comment by chenrui333** [comment]
definitely. 👍

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/vault/1.5.4/bin/vault status
Error checking seal status: Get "http://127.0.0.1:51542/v1/sys/seal-status": dial tcp 127.0.0.1:51542: connect: connection refused
Killing child processes...
==> Vault shutdown triggered

```

**Comment by chenrui333** [comment]
Should be good now

**Review by dtrodrigues — DISMISSED** [review]
Nice!

**Pull request closed without merging**
