### PR TITLE
carthage 0.16

### PR DESCRIPTION
**Pull request by mdiep**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by jdhealy** [comment]
> ```ruby
depends_on :xcode => ["7.1", :build]
```

This should probably be changed to `7.3`. The [failed build](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/280/) lists `Xcode: 7.2.1`.

But, looking at sourcekitten 0.12.0 #87:
> This might require Xcode 7.3, but Homebrew CI doesn't appear to have that version available.

@apjanke, anything else/special required to get carthage built and bottled as sourcekitten was?

**Comment by DomT4** [comment]
Presume you need to update the `depends_on :xcode => ["7.1", :build]` line to `7.3`?

**Comment by jdhealy** [comment]
@DomT4 haha, jinx

**Comment by DomT4** [comment]
@jdhealy Whoops :smile:. The 10.11 CI has 7.3, but 10.10 is stuck on 7.2.x because Apple stopped supporting 10.10 with 7.3's release.

**Comment by mdiep** [comment]
> This should probably be changed to 7.3.

Oops! You're right. I've updated it.

**Comment by apjanke** [comment]
[Carthage 0.16 release notes](https://github.com/Carthage/Carthage/releases/tag/0.16) confirm Xcode 7.3 is required.

```
0.16: Tentacular Future

This release updates to Swift 2.2. Building Carthage now requires Xcode 7.3.
```

> @apjanke, anything else/special required to get carthage built and bottled as sourcekitten was?

I don't think so; this looks good to go.

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

For future reference: you can keep PRs to a single commit by using `git commit --amend` or `git rebase -i master` and `git push --force`.

**Pull request closed without merging**
