### PR TITLE
Migrate MySQL and Elasticsearch formulae from homebrew/versions

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Second test after https://github.com/Homebrew/brew/pull/1371 and https://github.com/Homebrew/homebrew-core/pull/6533 were merged of importing formulae from homebrew/versions to the new version scheme.

Will hold off merging for a few days to spot any issues with https://github.com/Homebrew/homebrew-core/pull/6533.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
CC @jasontedor to note that this will happen at some point and after that you won't need to update homebrew/versions for Elasticsearch any more.

**Comment by MikeMcQuaid** [comment]
Only error:
```
mysql@5.6:
  * The homepage is not reachable (curl exit code 56)
```

This is a lie, I can connect to it fine 😉

**Comment by jasontedor** [comment]
Thanks again for the heads-up @MikeMcQuaid.

**Comment by mistydemeo** [comment]
🙌

**Pull request closed without merging**
