### PR TITLE
scala 2.13.0-M2 (devel)

### PR DESCRIPTION
**Pull request by DieBauer**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR introduces the devel and stable options to switch between the new scala 2.13.0 milestone releases. 

This milestone release can be installed with `brew install --build-from-source scala --devel`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Error Message

failed: brew test --devel scala --verbose

Stacktrace

        Testing scala
/usr/bin/sandbox-exec -f /tmp/homebrew20171015-11151-1ah6zj7.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scala.rb --devel --verbose --devel
==> /usr/local/Cellar/scala/2.13.0-M2/bin/scala /tmp/scala-test-20171015-11152-rnoib9/Test.scala
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Error: scala: failed
execution expired
```
Execution times out in the test block.

**Comment by DieBauer** [comment]
That's unfortunate, let me look into that.

**Comment by ilovezfs** [comment]
I'm confused by the test change given https://github.com/Homebrew/homebrew-core/pull/19484/files#diff-940a7218abf94056e4958c677386a11dR91

It sounds like there's a bug that needs to be reported here.

**Comment by som-snytt** [comment]
I don't normally use a mac, but I'm on my daughter's macbook this week.

I can confirm that for scala 2.12.3, `scala test.scala ; fsc -shutdown` claims `[No compilation server running.]`. I have to kill the process manually. So the bug already exists, `fsc` is evil and `-nc` should be the default. The test here should just use `-nc` and skip the `-shutdown`, which is extraneous in that case.

**Comment by SethTisue** [comment]
rebase?

**Comment by DieBauer** [comment]
Rebased and squashed.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by SethTisue** [comment]
if I try to view the test log I get "HTTP ERROR 404: Problem accessing /job/Homebrew%20Core%20Pull%20Requests/12725/"

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
```
Error Message

failed: brew style scala

Stacktrace

        warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scala.rb ==
C: 10:  1: Trailing whitespace detected.
C: 12:  1: Trailing whitespace detected.

1 file inspected, 2 offenses detected

```

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @DieBauer!

**Pull request merged**
