### PR TITLE
libtensorflow: add tools

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR upgrades version of TensorFlow to 2.1, adds graph/model tools (benchmark_model, summarize_graph, and transform_graph) and migrates this formula to python@3.8 (https://github.com/Homebrew/homebrew-core/issues/47274)

### CODE REVIEW

**Comment by fxcoudert** [comment]
On Catalina only:

```
==> /usr/local/Cellar/libtensorflow/2.1.0-rc2/bin/transform_graph --in_graph=/private/tmp/libtensorflow-test-20191224-10860-13oxfub/graph.pb --out_graph=/private/tmp/libtensorflow-test-20191224-10860-13oxfub/graph-new.pb --inputs=n/a --outputs=n/a --transforms="obfuscate_names" 2>&1
sh: line 1: 10882 Segmentation fault: 11  /usr/local/Cellar/libtensorflow/2.1.0-rc2/bin/transform_graph --in_graph=/private/tmp/libtensorflow-test-20191224-10860-13oxfub/graph.pb --out_graph=/private/tmp/libtensorflow-test-20191224-10860-13oxfub/graph-new.pb --inputs=n/a --outputs=n/a --transforms="obfuscate_names" 2>&1
```

**Comment by bayandin** [comment]
Regarding crash on Catalina, it works if I build it locally, but crashes if I install a bottle from CI:
```
Application Specific Information:
dyld: launch, running initializers
/usr/local/Cellar/libtensorflow/2.1.0-rc2/bin/transform_graph

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   transform_graph               	0x000000010b8a0000 Eigen::internal::EvalRange<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::__1::complex<float>, 6, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorReshapingOp<Eigen::DSizes<long, 6> const, Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::__1::complex<float> >, Eigen::DSizes<long, 1> const, Eigen::TensorMap<Eigen::Tensor<std::__1::complex<float> const, 6, 1, long>, 16, Eigen::MakePointer> const, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice>, long, true>::run(Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::__1::complex<float>, 6, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorReshapingOp<Eigen::DSizes<long, 6> const, Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::__1::complex<float> >, Eigen::DSizes<long, 1> const, Eigen::TensorMap<Eigen::Tensor<std::__1::complex<float> const, 6, 1, long>, 16, Eigen::MakePointer> const, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice>*, long, long) + 1216
1   dyld                          	0x000000011a5b715d ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 539
2   dyld                          	0x000000011a5b7582 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
3   dyld                          	0x000000011a5b1dc7 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 493
4   dyld                          	0x000000011a5afe58 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 188
5   dyld                          	0x000000011a5afef8 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
6   dyld                          	0x000000011a59e6b1 dyld::initializeMainExecutable() + 199
7   dyld                          	0x000000011a5a3cd0 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6797
8   dyld                          	0x000000011a59d227 dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 453
9   dyld                          	0x000000011a59d025 _dyld_start + 37

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000011a632268  rbx: 0x00007ffee4b5c3e0  rcx: 0x00007ffee4b5ea90  rdx: 0x00007ffee4b5e848
  rdi: 0x0000000000000006  rsi: 0x00007ffee4b5e810  rbp: 0x00007ffee4b5c530  rsp: 0x00007ffee4b5c3d8
   r8: 0x000000011a632330   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x000000010b0a94c0  r13: 0x0000000000000000  r14: 0x00007fff9bb25198  r15: 0x0000000000000000
  rip: 0x000000010b8a0000  rfl: 0x0000000000010a86  cr2: 0x000000010b8a0000
```

**Comment by bayandin** [comment]
Okay, it's tar bug strikes again (https://github.com/Homebrew/brew/issues/6539):
```
$ xxd benchmark_model | head -10
00000000: 320a 300a 3430 3936 0a38 3338 3836 3038  2.0.4096.8388608
00000010: 0a32 3130 3830 3337 3136 0a00 0000 0000  .210803716......
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

**Comment by bayandin** [comment]
So, TensorFlow 2.1 has been released, all checks/tests have passed for Mojave and High Sierra, a test on Catalina fails due to Homebrew/brew#6539.

**Maintainer**, please remove Catalina bottle before a push, thanks!

**Comment by fxcoudert** [comment]
The Catalina bug doesn't usually manifest itself with segfaults. Are you in a position to investigate and get a stack trace of that segfault?

**Comment by bayandin** [comment]
> The Catalina bug doesn't usually manifest itself with segfaults. Are you in a position to investigate and get a stack trace of that segfault?

Here it is for transform_graph (installed it from a bottle from bintray): https://gist.github.com/bayandin/3e3f3e11df65f262eced2770342350e4

Also, I've mentioned before about zeroes in benchmark_model (https://github.com/Homebrew/homebrew-core/pull/47330#issuecomment-570306162), so for the last rebuild I don't have it (could be related to building 2.1.0 instead of 2.1.0-rc2 or changing python to python@3.8)

**Comment by bayandin** [comment]
And want to mention that some `bazel` scripts are crashing during the build (https://github.com/bazelbuild/bazel/issues/10142). Probably it's not a reason for the current problem because it affects all macOS versions.

**Comment by fxcoudert** [comment]
- Yes, the bottle corruption is semi-random, so it can appear and disappear with seemingly minor changes.
- That stack trace is not a bottle corruption, it looks like a real problem. Can you report it to tensorflow?

**Comment by bayandin** [comment]
> * That stack trace is not a bottle corruption, it looks like a real problem. Can you report it to tensorflow?

Thanks, will do it a bit later!

**Comment by bayandin** [comment]
Extracted library update into separate PR to get that merged (https://github.com/Homebrew/homebrew-core/pull/48957). And has changes this PR to just adding tool (+ Catalina problems investigation)

**Comment by fxcoudert** [comment]
As of today, the bottle corruption bug is fixed on our CI machines. @BrewTestBot test this please, to confirm whether that fixes the issue here or not

**Comment by bayandin** [comment]
It's green, yay 🎉 
Thanks for the help @fxcoudert!

**Pull request closed without merging**
