### PR TITLE
ocaml 4.13.1 + patch incorrect -flat_namespace usage

### PR DESCRIPTION
**Pull request by carlocab**
This is needed for bottling on Monterey.

### CODE REVIEW

**Comment by Bo98** [comment]
LGTM if upstream don't support PowerPC.

**Comment by carlocab** [comment]
MacPorts haven't been able to build this for anything [earlier than Mavericks](https://ports.macports.org/port/ocaml/details/) (though maybe their older buildbots are just not running anymore?) so I think this should be good.

**Comment by carlocab** [comment]
Also, there's a `4.13.1` version bump. Maybe we should wait until after that.

**Comment by Bo98** [comment]
OCaml updates are usually annoying and can take ages but yeah that would be a good opportunity to test this against dependents, not that I suspect any issues.

**Comment by Bo98** [comment]
Or actually, if you want you can do 4.12.1 since that should be compatible with everything.

**Comment by carlocab** [comment]
> OCaml updates are usually annoying and can take ages but yeah that would be a good opportunity to test this against dependents, not that I suspect any issues.

Oh yea, they do. Let's see how this one goes. If it's too painful I'll just drop the version bump for now.

**Comment by carlocab** [comment]
Getting this over the line will take a bit, so I've split off the `-flat_namespace` patches to #88925.

**Comment by Bo98** [comment]
Sorry for not looking at this sooner.

`infer` is known. Others looks like it might be a CI bug. Or at least I remember fixing that a while back. I'll have a look again at the weekend.

**Comment by Bo98** [comment]
I think I've fixed this: https://github.com/Homebrew/homebrew-test-bot/pull/746

Going to prioritise keg-only openssl@1.1 and Rust before this PR though.

**Comment by Bo98** [comment]
Or maybe not actually since this fails before dependent testing. Which is odd as I'm not sure where the behaviour has changed - it definitely used to work before.

**Pull request closed without merging**
