### PR TITLE
r 3.6.3

### PR DESCRIPTION
**Pull request by gorisanson**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
The `gss` resource here shhould be bumped to 2.1-12.

**Comment by gorisanson** [comment]
> The `gss` resource here should be bumped to 2.1-12.

Thanks!

**Comment by Bo98** [comment]
Thank you @gorisanson. Merged now.

**Pull request closed without merging**
