### PR TITLE
tectonic 0.1.12

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Error on 10.13 only: 
```
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AppleEvents.h:597:165: error: expected function body after function declarator
cargo:warning=extern OSStatus AEDeterminePermissionToAutomateTarget( const AEAddressDesc* target, AEEventClass theAEEventClass, AEEventID theAEEventID, Boolean askUserIfNeeded ) __OSX_AVAILABLE_STARTING( __MAC_10_14, __IPHONE_NA );
cargo:warning=                                                                                                                                                                    ^
cargo:warning=/usr/include/Availability.h:216:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
cargo:warning=    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
cargo:warning=                                                 ^
cargo:warning=<scratch space>:19:1: note: expanded from here
cargo:warning=__AVAILABILITY_INTERNAL__MAC_10_14
cargo:warning=^
```

**Comment by samford** [comment]
The Tectonic test failed in the Rust 1.40.0 PR (#48090), so I'm trying to figure out why it fails on CI but builds and tests fine locally for me (macOS 10.15.2).  I'm going to run this test again to see how it does now that Rust 1.40.0 is merged.

@BrewTestBot test this please

**Comment by samford** [comment]
Would you mind rebasing this, when you get a chance?  I would like to see how it does with Rust 1.40.0 and if encounters the test error I saw in that PR.

**Comment by samford** [comment]
This is still only failing on 10.13 and the error during build is similar to above, so this lets me know that it isn't an issue with Rust 1.40.0, at least.  Thanks.

**Pull request closed without merging**
