### PR TITLE
kubernetes-cli 1.3.4

### PR DESCRIPTION
**Pull request by antoineco**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

kubernetes-cli (`kubectl`) v1.3.4 (stable)

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Devel install is failing everywhere: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5822/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install___devel_kubernetes_cli/

**Comment by antoineco** [comment]
Sorry, I pushed the second commit without testing, shame on me. Let's remove devel from this PR until I figure this out.

**Comment by MikeMcQuaid** [comment]
@antoineco Decided to pull this without the devel build so people could get the stable update immediately. Merged in c267f68

**Comment by MikeMcQuaid** [comment]
And: thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
