### PR TITLE
apache-arrow: use `DPython3_EXECUTABLE` instead of `DPYTHON_EXECUTABLE`

### PR DESCRIPTION
**Pull request by daipom**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does this actually break anything?

**Comment by daipom** [comment]
Currently `DPYTHON_EXECUTABLE` is not used, and this parameter is ignored.
(ref: https://cmake.org/cmake/help/latest/module/FindPython3.html#artifacts-specification)

It seems to be detecting well automatically now, but it may not be able in the future.

**Review by SMillerDev — APPROVED** [review]
Thanks @daipom  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by daipom** [comment]
Thanks @SMillerDev! :)

**Comment by carlocab** [comment]
Could we add `CI-no-bottles` for changes like this? That will minimise the number of misplaced Monterey bottles I need to keep track of 😅

**Comment by SMillerDev** [comment]
Sorry about that

**Comment by carlocab** [comment]
No problem; you didn't know.

**Pull request closed without merging**
