### PR TITLE
python@3.9: update pip, wheel

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
updates to latest `pip` and `wheel` for python 3.9. `pip` includes bug fixes for the dependency resolver and `wheel` includes a macOS specific change.

### CODE REVIEW

**Comment by fxcoudert** [comment]
[One more time](https://www.youtube.com/watch?v=FGBhQbmPwH8)

**Comment by fxcoudert** [comment]
CI failed, and I believe we should close this in favour of #67004
Thanks @dtrodrigues for the PR!

**Comment by alebcay** [comment]
> CI failed, and I believe we should close this in favour of #67004

This is #67004 - @fxcoudert did you mean to refer to some other PR?

**Comment by fxcoudert** [comment]
@alebcay infinite recursion, stack exceeded 😢 

I meant https://github.com/Homebrew/homebrew-core/pull/67030

**Pull request closed without merging**
