### PR TITLE
gh: delete

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] ~Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?~
- [x] ~Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?~
- [x] ~Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?~

-----

- Building from source here uses the GitHub CLI (dev) OAuth app, whereas the one from the third-party `github/homebrew-gh` tap has full permissions. The formulae in that tap install binaries directly.
- We shouldn't be shipping sub-optimal software, and we can't change any of this behaviour.
- See https://github.com/cli/cli/pull/400 for further context.

### CODE REVIEW

**Comment by mislav** [comment]
> * It turns out that this isn't entirely open source.

GitHub CLI is entirely open source. It's just that pre-built binaries are configured with the correct OAuth app for full access, whereas building from source was intended for development and has limited access to org-owned repos. We might change this in future releases, as it's causing confusion.

But yes, for now we prefer that people use `github/gh/gh` instead of this formula.

**Comment by issyl0** [comment]
@mislav Thanks. I amended the commit message to remove the "not open source" sentence.

**Comment by dawidd6** [comment]
https://github.com/cli/cli/pull/492

Can we revert this now? @mislav @issyl0

**Comment by mislav** [comment]
@dawidd6 @issyl0 Yes, gh now configures the correct OAuth app when built from source, which fixed the main reason why this formula was reverted.

**Comment by issyl0** [comment]
Thanks, @mislav. Also sorry for my too quick merging of this deletion, I didn't realise you had instant plans to fix the authentication, or that this had so many users. :flushed:

@dawidd6 If you'd like to raise a new PR for re-adding this, please do. (Remove the bottle lines etc.) 🌟

**Comment by mislav** [comment]
BTW we would prefer if this part of test block was gone:

```rb
assert_match "Work with GitHub issues.", shell_output("#{bin}/gh issue 2>&1")	
assert_match "Work with GitHub pull requests.", shell_output("#{bin}/gh pr 2>&1")
```

Our software is beta and changing rapidly, so it's highly likely that we might tweak the help output of these commands.

I realize that the test block should ideally exercise some functionality of the executable, but all current GitHub CLI functionality relies on authentication and API requests against GitHub, and exercising that in a test block isn't really feasible.

**Comment by MikeMcQuaid** [comment]
@mislav We'd rather have something that needs tweaked or updated on a version bump than no test or a `--help` test.

**Comment by mislav** [comment]
> Also sorry for my too quick merging of this deletion, I didn't realise you had instant plans to fix the authentication, or that this had so many users. 😳

No worries; we were surprised too. Because a considerable amount of people were building from source to add to their package manager of choice, including Homebrew, and subsequently ran into problems accessing org repos, we had to address the OAuth issue quickly.

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-core/pull/50541

**Pull request merged**
