### PR TITLE
Test ARM triage flags

### PR DESCRIPTION
**Pull request by carlocab**
Testing https://github.com/Homebrew/homebrew-core/pull/68067.

### CODE REVIEW

**Comment by Rylan12** [comment]
Forgot a comma...

**Comment by carlocab** [comment]
Yup, fixing.....

**Comment by Rylan12** [comment]
You'll probably need to rebase

**Comment by carlocab** [comment]
success!! 🎉

**Comment by carlocab** [comment]
My editor let me down. It usually yells at me when I have broken JSON syntax. ...it seems it doesn't mind broken YAML?

**Pull request closed without merging**
