### PR TITLE
dvc 2.5.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
re-queue the build.

**Comment by nandahkrishna** [comment]
```
   Added file:///private/tmp/dvc--networkx-20210708-46173-vax1fd/networkx-2.6 to build tracker '/private/tmp/pip-req-tracker-wm5i16sj'
     Running setup.py (path:/private/tmp/pip-req-build-fdn5vra4/setup.py) egg_info for package from file:///private/tmp/dvc--networkx-20210708-46173-vax1fd/networkx-2.6
     Created temporary directory: /private/tmp/pip-pip-egg-info-mj1j5ldg
     Running command python setup.py egg_info
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/private/tmp/pip-req-build-fdn5vra4/setup.py", line 165, in <module>
         install_requires = parse_requirements_file("requirements/default.txt")
       File "/private/tmp/pip-req-build-fdn5vra4/setup.py", line 159, in parse_requirements_file
         with open(filename) as fid:
     FileNotFoundError: [Errno 2] No such file or directory: 'requirements/default.txt'
 WARNING: Discarding file:///private/tmp/dvc--networkx-20210708-46173-vax1fd/networkx-2.6. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nandahkrishna** [comment]
The `requirements` folder is missing from the `networkx` source archive from PyPI.

**Comment by jarrodmillman** [comment]
I just released 2.6.1, which should have the requirements files:
https://pypi.org/project/networkx/

**Comment by nandahkrishna** [comment]
Thanks for the quick fix, @jarrodmillman!

**Comment by nandahkrishna** [comment]
@chenrui333 I tried this already, the changes I pushed were to try and avoid build failures with `numpy` by bringing it in as a formula dependency, but that didn't work either (it still tried to build `numpy` from source again).

**Comment by chenrui333** [comment]
let me build on my machine to see how it goes.

**Comment by efiop** [comment]
Thanks for looking into this! Maybe we could just uninstall numpy (and maybe other new packages that new version of networkx brought in)? Dvc should work fine without those.

**Comment by jarrodmillman** [comment]
I yanked NetworkX 2.6 and 2.6.1 from PyPI.  We are revisiting our decision to change the default dependencies:
https://github.com/networkx/networkx/pull/4967

It looks likely that we we release 2.6.2 (or maybe we will call if 2.7, not sure) soon with no dependencies.  Feel free to comment on the above PR.

**Pull request closed without merging**
