### PR TITLE
pcre2 10.41

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
grantlee test failure (looks like c++17 issue)

```
  /opt/homebrew/include/QtCore/qglobal.h:106:6: error: "Qt requires a C++17 compiler"
  #    error "Qt requires a C++17 compiler"
       ^
  /opt/homebrew/include/QtCore/qglobal.h:1009:26: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
           typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                      ~~~~~^
```

**Comment by cho-m** [comment]
`grantlee` is still mixing up Qt6 and Qt5.

**Comment by chenrui333** [comment]
> grantlee test failure (looks like c++17 issue)
> 
> ```
>   /opt/homebrew/include/QtCore/qglobal.h:106:6: error: "Qt requires a C++17 compiler"
>   #    error "Qt requires a C++17 compiler"
>        ^
>   /opt/homebrew/include/QtCore/qglobal.h:1009:26: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
>            typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
>                       ~~~~~^
> ```

cc @yurikoles

**Comment by yurikoles** [comment]
`grantlee`'s test fails when Qt6 is installed.

**Comment by yurikoles** [comment]
As I said in #116439, I don't know the solution.
> Test are failing when Qt 6 is installed, so please add label `help wanted`.

**Comment by chenrui333** [comment]
> `grantlee`'s test fails if Qt6 is installed.

ok, should we revert the formulae change (like disable for now) or maybe ignore the test part until it has been fixed in the upstream

**Comment by yurikoles** [comment]
How about return `true` if Qt6 is installed?

**Comment by chenrui333** [comment]
That works for me

**Comment by yurikoles** [comment]
I fixed at least one example with `grantlee` built with `Qt6`, I'm going to file a PR upstream and switch formula to `Qt6`.

**Pull request closed without merging**
