### PR TITLE
vulkan-* 1.3.271

### PR DESCRIPTION
**Pull request by osalbahr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
Note: Similarly to https://github.com/Homebrew/homebrew-core/pull/155921#issuecomment-1832753816, I did:
```console
% for f in vulkan-extensionlayer vulkan-loader vulkan-tools vulkan-utility-libraries vulkan-validationlayers
do
brew bump-formula-pr $f --version 1.3.271 --no-audit --write-only && git commit -am "$f 1.3.271" && git push
done
```

**Comment by osalbahr** [comment]
Not sure what this means, I will try again without the `inreplace "mac_common.cmake"`.

```
Full install --build-bottle vulkan-tools output
  ==> Fetching vulkan-tools
  ==> Downloading https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/v1.3.271.tar.gz
  Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/9123b8bd591a2bb9deb2d27b90ab1759ec7b2c529f5aae034afcddd124ec45ac--Vulkan-Tools-1.3.271.tar.gz
  ==> Verifying checksum for '9123b8bd591a2bb9deb2d27b90ab1759ec7b2c529f5aae034afcddd124ec45ac--Vulkan-Tools-1.3.271.tar.gz'
  /usr/bin/env tar --extract --no-same-owner --file /Users/brew/Library/Caches/Homebrew/downloads/9123b8bd591a2bb9deb2d27b90ab1759ec7b2c529f5aae034afcddd124ec45ac--Vulkan-Tools-1.3.271.tar.gz --directory /private/tmp/d20231129-11341-6b2rmr
  /usr/bin/env cp -pR /private/tmp/d20231129-11341-6b2rmr/Vulkan-Tools-1.3.271/. /private/tmp/vulkan-tools-20231129-11341-n8ofdr/Vulkan-Tools-1.3.271
  Error: An exception occurred within a child process:
    Errno::ENOENT: No such file or directory @ rb_sysopen - mac_common.cmake
```

Related:
- https://github.com/Homebrew/homebrew-core/pull/128749#issuecomment-1517019287

**Comment by osalbahr** [comment]
It looks like `mac_common.cmake` is no longer part of the tarball, [removed](https://github.com/KhronosGroup/Vulkan-Tools/pull/920/files#diff-b59fe6d7a4d18d0dc5491560de10a5c6ba1451d7867d86e2434b574943ff67a8) in the following PR:
- https://github.com/KhronosGroup/Vulkan-Tools/pull/920
```console
% ls Vulkan-Tools-1.3.2*
Vulkan-Tools-1.3.268:
BUILD.gn			CODE_OF_CONDUCT.md		LICENSE.txt			icd				tests
BUILD.md			CONTRIBUTING.md			README.md			mac_common.cmake		vulkaninfo
CMakeLists.txt			GOVERNANCE.md			cube				scripts				windows-runtime-installer

Vulkan-Tools-1.3.271:
BUILD.gn			CODE_OF_CONDUCT.md		LICENSE.txt			icd				vulkaninfo
BUILD.md			CONTRIBUTING.md			README.md			scripts				windows-runtime-installer
CMakeLists.txt			GOVERNANCE.md			cube				tests
% find . -name '*mac*cmake*'
./Vulkan-Tools-1.3.268/mac_common.cmake
% find . -name '*mac*common*'
./Vulkan-Tools-1.3.268/mac_common.cmake
% 
```

**Comment by osalbahr** [comment]
Could you see if this PR passes in the Linux CI at least?

**Comment by osalbahr** [comment]
I still don't know if this bump passes in the Linux CI.

**Comment by chenrui333** [comment]
#167085

**Pull request closed without merging**
