### PR TITLE
ruby 3.0.3

### PR DESCRIPTION
**Pull request by nevack**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by iMichka** [comment]
Fix for `libstfl`: #89981

**Comment by nevack** [comment]
rebased after #89981 merged

**Comment by jdmartin** [comment]
Wanted to keep this alive. Important to note it's a security release. See: https://www.ruby-lang.org/en/news/2021/11/24/ruby-3-0-3-released/

**Comment by Bo98** [comment]
Thanks!

**Pull request closed without merging**
