### PR TITLE
when: update repo location

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — COMMENTED** [review]
Website still refers to GitHub, how do we know to use bitbucket?

**Comment by chenrui333** [comment]
> Website still refers to GitHub, how do we know to use bitbucket?

the github repo is 404 now.

**Comment by chenrui333** [comment]
Looks like there is no way to create an issue in the bitbucket side, I am gonna @bcrowell you in here (the website needs to also update the github ref)
When

**Comment by SMillerDev** [comment]
> the github repo is 404 now.

That explains why not GitHub, but why BitBucket?

**Comment by chenrui333** [comment]
> > the github repo is 404 now.
> 
> That explains why not GitHub, but why BitBucket?

It was casually mentioned in the mastondon chat, https://toot.community/@ben_crowell_fullerton/109780109512577473

**Comment by bcrowell** [comment]
Sorry about the confusion. I've updated the web page to point to bitbucket. If you look on my github account page, it explains that I've moved off of github to bitbucket for ethical reasons: https://github.com/bcrowell?tab=repositories , but I guess the problem is that you don't see that page if you just try to go to the project's old github URL.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
