### PR TITLE
rgbds 0.7.0

### PR DESCRIPTION
**Pull request by ISSOtm**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Hello again from upstream! And happy new year :)

By the way, we now publish [statically-linked binaries, compatible all the way to 10.9](https://github.com/gbdev/rgbds/blob/08f3e360c9525b65291db9cee66fc5eb6e4a45e4/.github/workflows/create-release-artifacts.yml#L86). Let me know if you're interested in using those.

### CODE REVIEW

**Comment by chenrui333** [comment]
> Hello again from upstream! And happy new year :)

Happy new year!!

> 
> By the way, we now publish [statically-linked binaries, compatible all the way to 10.9](https://github.com/gbdev/rgbds/blob/08f3e360c9525b65291db9cee66fc5eb6e4a45e4/.github/workflows/create-release-artifacts.yml#L86). Let me know if you're interested in using those.

We'd still prefer to build from source. :)

**Comment by ISSOtm** [comment]
> We'd still prefer to build from source. :)

Alright, fair. (I'm aware of the "redistributing someone else's binary problem.)

I mentioned them because we've had reports from some people trying to `brew install rgbds` on 10.15 or so, and not understanding why Rust was being built from source. Currently we're instructing them to manually install those binaries to `/usr/local`, but I was wondering if there would be a way to make it work with `brew` directly; that's fine if not.

AIUI the argument is "those are not supported by Apple anymore", which sounds like the Windows XP then 7 situation all over again :sob:

**Comment by SMillerDev** [comment]
> AIUI the argument is "those are not supported by Apple anymore", which sounds like the Windows XP then 7 situation all over again 😭

Yeah, we don't have the resources to keep support for macOS versions that nobody else in the stack supports.

**Comment by ISSOtm** [comment]
> Yeah, we don't have the resources to keep support for macOS versions that nobody else in the stack supports.

Yeah, fair. [We've made a note](https://github.com/gbdev/rgbds-www/issues/59#issuecomment-1873400327) to explain how to install those binaries, so let's put that to rest.

---

I have no idea why CI failed for macOS 14 x86_64? The last two lines in the log are
```
 ==> brew install --only-dependencies --verbose --build-bottle rgbds
Error: The operation was canceled.
```
...and for some reason the indicated runtime is 1h 28m 45s?? I don't think I can do anything on my side to fix this. (Since you have push access to this PR's branch, feel free to go ham!)

**Comment by ISSOtm** [comment]
Thank you @SMillerDev! Looks like that was just a transient failure, after all.

**Review by chenrui333 — APPROVED** [review]

**Comment by ISSOtm** [comment]
Thank you everyone!

Ah, and, a word of warning: we're working on [converting RGBDS to Rust entirely](//github.com/ISSOtm/rsgbds#motivation), so the next (non-patch) update should be in a while, but more involved :P

(Let me know if there's anything we can do in advance to make your job easier!)

**Pull request merged**
