### PR TITLE
tmpmail 1.2.3 (new formula)

### LINKED ISSUE #55: tmpmail on Homebrew!
Would be great to update tmpmail via Homebrew.
Thanks

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

fixes https://github.com/sdushantha/tmpmail/issues/55
package inclusions, https://repology.org/project/tmpmail/versions

### CODE REVIEW

**Review by lodenrogue — COMMENTED** [review]
Looks good to me

**Comment by vszakats** [comment]
`xclip` wasn't working on my system, and it also requires a bunch of heavy dependencies, like XQuartz. This patch fixes it to use the OS-native `pbpaste`:
```diff
--- tmpmail-ori	2024-08-16 22:12:25.767706296 +0200
+++ tmpmail	2024-08-16 22:12:37.722729009 +0200
@@ -13,7 +13,7 @@
 
 # The default command that will be used to copy the email address to
 # the user's clipboard when running 'tmpmail --copy'
-copy_to_clipboard_cmd="xclip -selection c"
+copy_to_clipboard_cmd="pbcopy"
 
 # If the value is set to 'true' tmpmail will convert the HTML email
 # to raw text and send that to stdout

```

**Comment by lodenrogue** [comment]
pbcopy works on Linux?

**Comment by vszakats** [comment]
No, this is for macOS only.

**Comment by vszakats** [comment]
For portability, something like this can work:
```shell
if command -v pbcopy >/dev/null 2>&1; then
  copy_to_clipboard_cmd="pbcopy"
else
  copy_to_clipboard_cmd="xclip -selection c"
fi
```

or:
```shell
case "$(uname)" in
  Darwin*) copy_to_clipboard_cmd="pbcopy";;
  *)       copy_to_clipboard_cmd="xclip -selection c";;
esac
```

**Comment by chenrui333** [comment]
> `xclip` wasn't working for me on macOS, and it also requires a bunch of heavy dependencies, like XQuartz. This patch fixes it to use the OS-native `pbcopy`:
> 
> ```diff
> --- tmpmail-ori
> +++ tmpmail
> @@ -13,7 +13,7 @@
>  
>  # The default command that will be used to copy the email address to
>  # the user's clipboard when running 'tmpmail --copy'
> -copy_to_clipboard_cmd="xclip -selection c"
> +copy_to_clipboard_cmd="pbcopy"
>  
>  # If the value is set to 'true' tmpmail will convert the HTML email
>  # to raw text and send that to stdout
> ```

can you submit that to the upstream?

also if just XQuartz concern, I think it is probably okay? as `xclip` use the same dep tree for both linux and macOS from homebrew perspective

**Review by carlocab — APPROVED** [review]

**Comment by vszakats** [comment]
Maybe it's just me but `xclip` didn't work (or worked oddly?) though the machine already had XQuartz. Using the native tool is just overall nicer.

I prefer to leave the upstreaming to someone else, too much other open source stuff to do at the moment.
(feel free take my snippets as-is)

**Comment by chenrui333** [comment]
> Maybe it's just me but `xclip` didn't work (or worked oddly?) though the machine already had XQuartz. Using the native tool is just overall nicer.
> 
> I prefer to leave the upstreaming to someone else, too much other open source stuff to do at the moment. (feel free take my snippets as-is)

sounds good, I am gonna merge it for now, we can always followup to improve it for everyone. Thanks for the input though! 👍

**Pull request merged**
