### PR TITLE
libpng 1.6.36

### PR DESCRIPTION
**Pull request by tommyang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tommyang** [comment]
Mojave `make test` failure. Can't repro locally on macOS 0.14.1 (18B75) + Xcode Version 10.1 (10B61)

**Comment by fxcoudert** [comment]
I can reproduce locally with `--build-bottle` (`brew install -s --verbose --debug --build-bottle libpng`)

**Comment by fxcoudert** [comment]
From `test-suite.log`:

```
FAIL: tests/pngtest
===================


 Testing libpng version 1.6.36
   with zlib   version 1.2.11

libpng version 1.6.36
Copyright (c) 2018 Cosmin Truta
Copyright (c) 1998-2002,2004,2006-2018 Glenn Randers-Pehrson
Copyright (c) 1996-1997 Andreas Dilger
Copyright (c) 1995-1996 Guy Eric Schalnat, Group 42, Inc.
 library (10636): libpng version 1.6.36 - December 1, 2018

 pngtest (10636): libpng version 1.6.36 - December 1, 2018

 Testing ./pngtest.png:
   Text compression[0]=-1

 stereo mode = 1
 vpAg = 100 x 100, units = 0

   Text compression[0]=0
 eXIf type MM, 52 bytes

 Image width = 91, height = 69

Files ./pngtest.png and pngout.png are of a different size
   Was ./pngtest.png written with the same maximum IDAT chunk size (8192 bytes),
   filtering heuristic (libpng default), compression level (zlib default),
   and zlib version (1.2.11)?

 FAIL
 libpng FAILS test
 Default limits:
  width_max  = 1000000
  height_max = 1000000
  cache_max  = 1000
  malloc_max = 8000000
FAIL tests/pngtest (exit status: 1)
```

After the test, `pngout.png` has size 0 bytes, which is worrying.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Hum, it may be a race condition in the test suite. It only triggers like 5% of the time on `make -j12 test`.

**Comment by fxcoudert** [comment]
Thanks @tommyang for the pull request

**Comment by fxcoudert** [comment]
Fix for libagar test coming in #34765

**Pull request closed without merging**
