### PR TITLE
Various

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

More fixes related to https://github.com/Homebrew/homebrew-core/issues/342.

### CODE REVIEW

**Comment by apjanke** [comment]
[Failed](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/859/) on Mavericks only.

```
/bin/sh ./libtool  --tag=CXX   --mode=link clang++ -Wl,-lstdc++  -O2 -g -pipe -nostdlib -shared  -export-dynamic -version-info 2:0:0  -o libgexiv2.la -rpath /usr/local/Cellar/gexiv2/0.10.3_2/lib gexiv2/libgexiv2_la-gexiv2-metadata.lo gexiv2/libgexiv2_la-gexiv2-metadata-exif.lo gexiv2/libgexiv2_la-gexiv2-metadata-gps.lo gexiv2/libgexiv2_la-gexiv2-metadata-iptc.lo gexiv2/libgexiv2_la-gexiv2-metadata-xmp.lo gexiv2/libgexiv2_la-gexiv2-stream-io.lo gexiv2/libgexiv2_la-gexiv2-preview-properties.lo gexiv2/libgexiv2_la-gexiv2-preview-image.lo gexiv2/libgexiv2_la-gexiv2-log.lo gexiv2/libgexiv2_la-gexiv2-startup.lo  -L/usr/local/Cellar/exiv2/0.25/lib -lexiv2 -L/usr/local/Cellar/glib/2.46.2/lib -L/usr/local/opt/gettext/lib -lgobject-2.0 -lglib-2.0 -lintl 
libtool: link: clang++ -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libgexiv2.2.dylib  gexiv2/.libs/libgexiv2_la-gexiv2-metadata.o gexiv2/.libs/libgexiv2_la-gexiv2-metadata-exif.o gexiv2/.libs/libgexiv2_la-gexiv2-metadata-gps.o gexiv2/.libs/libgexiv2_la-gexiv2-metadata-iptc.o gexiv2/.libs/libgexiv2_la-gexiv2-metadata-xmp.o gexiv2/.libs/libgexiv2_la-gexiv2-stream-io.o gexiv2/.libs/libgexiv2_la-gexiv2-preview-properties.o gexiv2/.libs/libgexiv2_la-gexiv2-preview-image.o gexiv2/.libs/libgexiv2_la-gexiv2-log.o gexiv2/.libs/libgexiv2_la-gexiv2-startup.o   -L/usr/local/Cellar/exiv2/0.25/lib -lexiv2 -L/usr/local/Cellar/glib/2.46.2/lib -L/usr/local/opt/gettext/lib -lgobject-2.0 -lglib-2.0 -lintl  -Wl,-lstdc++ -O2   -install_name  /usr/local/Cellar/gexiv2/0.10.3_2/lib/libgexiv2.2.dylib -compatibility_version 3 -current_version 3.0 -Wl,-single_module
libtool: link: (cd ".libs" && rm -f "libgexiv2.dylib" && ln -s "libgexiv2.2.dylib" "libgexiv2.dylib")
libtool: link: ( cd ".libs" && rm -f "libgexiv2.la" && ln -s "../libgexiv2.la" "libgexiv2.la" )
g-ir-scanner --verbose                          \
		--namespace=GExiv2                      \
		--nsversion=0.10              \
		--symbol-prefix=gexiv2              \
		-I.							 \
		--include=GObject-2.0                   \
		--add-include-path=gexiv2         \
		--output GExiv2-0.10.gir                             \
		-I gexiv2                           \
		./gexiv2/gexiv2.h ./gexiv2/gexiv2-metadata.h ./gexiv2/gexiv2-managed-stream.h ./gexiv2/gexiv2-preview-properties.h ./gexiv2/gexiv2-preview-image.h ./gexiv2/gexiv2-log.h ./gexiv2/gexiv2-startup.h ./gexiv2/gexiv2-version.h      \
		--library libgexiv2.la                \
		/bin/sh ./libtool                              \
		--pkg=gobject-2.0
Caught exception: <type 'exceptions.AttributeError'> AttributeError("'NoneType' object has no attribute 'get'",)
> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/sysconfig.py(171)customize_compiler()
-> if not _config_vars.get('CUSTOMIZED_OSX_COMPILER', ''):
(Pdb) 
make: *** [GExiv2-0.10.gir] Error 1
```

Couldn't tell you what that means.

**Comment by DomT4** [comment]
It's certainly an interesting one. I suspect I'm going to have to roll a Mavericks VM later today/tomorrow to look it over, which is a minor annoyance.

**Comment by apjanke** [comment]
Could it possibly be related to homebrew/brew#141, which is now merged?

@BrewTestBot test this please.

**Comment by ilovezfs** [comment]
@DomT4 The problem is Maverick's python.

```
libtool: link: (cd ".libs" && rm -f "libgexiv2.dylib" && ln -s "libgexiv2.2.dylib" "libgexiv2.dylib")
libtool: link: ( cd ".libs" && rm -f "libgexiv2.la" && ln -s "../libgexiv2.la" "libgexiv2.la" )
g-ir-scanner --verbose                          \
		--namespace=GExiv2                      \
		--nsversion=0.10              \
		--symbol-prefix=gexiv2              \
		-I.							 \
		--include=GObject-2.0                   \
		--add-include-path=gexiv2         \
		--output GExiv2-0.10.gir                             \
		-I gexiv2                           \
		./gexiv2/gexiv2.h ./gexiv2/gexiv2-metadata.h ./gexiv2/gexiv2-managed-stream.h ./gexiv2/gexiv2-preview-properties.h ./gexiv2/gexiv2-preview-image.h ./gexiv2/gexiv2-log.h ./gexiv2/gexiv2-startup.h ./gexiv2/gexiv2-version.h      \
		--library libgexiv2.la                \
		/bin/sh ./libtool                              \
		--pkg=gobject-2.0
Caught exception: <type 'exceptions.AttributeError'> AttributeError("'NoneType' object has no attribute 'get'",)
> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/sysconfig.py(171)customize_compiler()
-> if not _config_vars.get('CUSTOMIZED_OSX_COMPILER', ''):
(Pdb)
```

A workaround, at least for the bottle case, is
```
depends_on :python if MacOS.version <= :mavericks
```

@tdsmith Is there a typical workaround for this particular failure other than resorting to brew's python?

**Comment by DomT4** [comment]
I'd forgotten about this to be honest with everything else going on.

```ruby
depends_on "python" if MacOS.version <= :mavericks
```
Seems a fine compromise to me given the formula depends on `gobject-introspection` to build which has the same dependency for similar reasons.

**Pull request closed without merging**
