### PR TITLE
newt 0.52.21

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can't find the snack module in python

**Comment by alebcay** [comment]
Is this looking all right now?

**Comment by SMillerDev** [comment]
@brewtestbot test this please

**Comment by timothybasanov** [comment]
While tests are indeed failing, it's not a new behavior. 0.52.20 fails it as well.
We probably should let this upgrade happen or delete existing formulae completely due to Mojave issues https://github.com/Homebrew/homebrew-core/pull/37479

**Comment by jonchang** [comment]
tests look ok on this now

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by timothybasanov** [comment]
@jonchang @SMillerDev: Hmm, this means newt/python bindings are still broken. We have just disabled a test for that.
See https://github.com/Homebrew/homebrew-core/pull/37479 and https://github.com/Homebrew/homebrew-core/issues/39855

Example:
```bash
$ brew reinstall newt byobu
$ byobu-config
ERROR: Could not import the python snack module
```

Should I open/reopen/clone some other ticket? I'm not sure if I understand how Homebrew ticket-management process works.

**Comment by jonchang** [comment]
@timothybasanov If you can open a pull request to fix the issue that would be great.

**Pull request closed without merging**
