### PR TITLE
inko 0.13.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
👋 trying to build the latest release, but run into some build issue. The error log is as below:


<details>
<summary>error build log</summary>

```
  ==> /opt/homebrew/Cellar/inko/0.13.0/bin/inko run hello.inko
  hello.inko:1:11 error(invalid-syntax): Expected a top-level expression, found ':' instead
```

</details>

this is the hello.inko:

```
import std::stdio::STDOUT

class async Main {
  fn async main {
    STDOUT.new.print('Hello, world!')
  }
}
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6518955982/job/17704959702
relates to Homebrew/homebrew-core#150895

**Comment by Bo98** [comment]
That'll be because the syntax changed: https://github.com/inko-lang/inko/commit/8026b29d

> Imports and constant references no longer use "::" to separate modules
from other modules or constants, instead using ".". So instead of this:
>
>     import foo::bar::(A, B)
>
> You now write this:
>
>     import foo.bar.(A, B)

**Comment by chenrui333** [comment]
> That'll be because the syntax changed: [inko-lang/inko@8026b29d](https://github.com/inko-lang/inko/commit/8026b29d)
> 
> > Imports and constant references no longer use "::" to separate modules
> > from other modules or constants, instead using ".". So instead of this:
> > ```
> > import foo::bar::(A, B)
> > ```
> > 
> > 
> > You now write this:
> > ```
> > import foo.bar.(A, B)
> > ```
> 
> So our test will need updating to reflect that

yeah, I did not look deep (but their docs also needs some update 😅 )

**Comment by chenrui333** [comment]
that works for me, thanks @Bo98!

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
