### PR TITLE
mesos 0.28.1

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Bump stable version from 0.28.0 to 0.28.1

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Checksums seem wrong: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2139/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/fetch_mesos/

**Comment by Jerzerak** [comment]
@MikeMcQuaid already on it, pushing a new commit in a sec

**Comment by MikeMcQuaid** [comment]
Thanks!

**Comment by DomT4** [comment]
Still failing. You'll probably have to switch over to pypi's new URL system:
```
https://pypi.python.org/packages/b3/1d/3022db30af1ba551b285d771716ad5bb24a5f82c2b941017a33de2d86793/boto-2.39.0.tar.gz
```

**Comment by Jerzerak** [comment]
Thanks @DomT4 I'll get right on that...strange that it fetches and compiles fine locally for me, even after clearing all the caches...

**Comment by Jerzerak** [comment]
Done...let me know if there's anything else that's needs doing :)

**Comment by DomT4** [comment]
That did the trick. Merged in https://github.com/Homebrew/homebrew-core/commit/1b7fc19cc26697df631ce8010ae5fc133f98744b. Thank you once again @Jerzerak 😺

**Pull request closed without merging**
