### PR TITLE
c-ares 1.17.2

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
`roswell` failure on Linux is pre-existing.

**Comment by cho-m** [comment]
> `roswell` failure on Linux is pre-existing.

Off topic from this PR, but I wonder if there there is a way to fix `roswell`. It looks like `ros init` will download a `sbcl` binary and try to run it. The problem is `sbcl` was compiled on OS with newer `glibc` (GLIBC_2.28) while Homebrew CI uses Ubuntu 16.04 with v2.23.

I guess we could just disable the testcase on Linux, but `roswell` is potentially unusable on older Linux distros. Not sure what level of compatibility we have for Linuxbrew.

**Comment by carlocab** [comment]
What is strange is that the test seems to be failing now when it didn't when we bottled `roswell` the first time around.

**Comment by cho-m** [comment]
Our `roswell` testcase will default  to the latest binary the upstream provides. Previously, this was v2.1.6, which needed at most glibc 2.17 

The current v2.1.7 https://github.com/roswell/sbcl_bin/releases/tag/2.1.7 has references to glibc 2.28.

It looks like this had occurred previously (https://github.com/roswell/roswell/issues/468) and was fixed then. Seems like upstream CI is again building binaries on newer glibc.

We could try `variant=glibc2.10` for the oldest binary that is offered. Or try to force an older/fixed `sbcl` version so that the testcase is not dependent on upstream.

**Comment by carlocab** [comment]
Doing either one seems like a huge improvement to what we're doing now. Fixing the `sbcl` version might be preferrable as it sounds like it'll suit for both macOS and Linux. Setting `variant=glibc2.10` sounds like it requires Linux-specific logic in the `test` block.

**Pull request closed without merging**
