### PR TITLE
openstackclient: Add heatclient

### PR DESCRIPTION
**Pull request by laserscout**
Including all of its dependencies and updates to the rest of the
packages.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

For me the openstack client needs to have the `stack` subcommand which allows for "launching stacks from templates, views details of running stacks including events and resources, and updates and deletes stacks".
I've added the heatclient package which is necessary for running `openstack stack` commands.

### CODE REVIEW

**Comment by SMillerDev** [comment]
> For me the openstack client needs to have the stack subcommand which allows for "launching stacks from templates, views details of running stacks including events and resources, and updates and deletes stacks".

Is this the default install configuration from upstream?

**Comment by laserscout** [comment]
@SMillerDev No, the pure openstackclient installation is the previous state of the formula.
But as documented in the [installation documentation](https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html] you select which service clients you would like to use by pip installing on top of the vanilla installation.

**Comment by Rylan12** [comment]
> @SMillerDev No, the pure openstackclient installation is the previous state of the formula.
> But as documented in the [installation documentation]([https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html]](https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html%5D) you select which service clients you would like to use by pip installing on top of the vanilla installation.

That link is broken and I'm struggling to find the page you're talking about. I looked under the [Installation Guide](https://docs.openstack.org/install-guide/) but didn't find a satisfactory link. Can you send a working version of the link?

Assuming we want to include the `python-heatclient` as a resource, can you add `python-heatclient` to the `extra_packages` list for `openstackclient` in the [`pypi_formula_mappings.json`](https://github.com/Homebrew/homebrew-core/blob/master/pypi_formula_mappings.json) file? There are several examples in the file of what it should look like.

Then, you can run `brew update-python-resources openstackclient` to automatically update and add all the necessary resources. This will ensure we always have the necessary dependencies for each formula and all the resources it requires.

That way, our auto-update capability will keep all the resources up to date and won't automatically remove `python-heatclient` in the future.

**Comment by laserscout** [comment]
@Rylan12 Sorry for the broken link... I had closed the link markdown tag with a `]` and it was rendered as part of the link :/ .

Furthermore, it wasn't clear to me what you were talking about with the `pypi_formula_mappings` file, but I slept on it and now I think I understand what's up.

The `brew update-python-resources` is a tool for quickly updating the resources of python formulas, but since this PR's adds extra resources to the openstackclient formula, running `brew update-python-resources` in the future will remove them; unless the argument `--extra-packages python-heatclient` is provided. That argument can be implicitly added to every `brew update-python-resources openstackclient` run by mapping it in `pypi_formula_mappings.json`. Did I get that right?

**Comment by laserscout** [comment]
Additional changes were committed that:
* add `python-heatclient` as an extra package of openstackclient in `pypi_formula_mappings.json`
* further update the formula's resources with `update-python-resources`
* add a test for the existence of the `stack` sub command; the test will fail if the `python-heatclient` is removed

**Comment by Rylan12** [comment]
> Did I get that right?

Exactly right!

The only thing I'd add is that `brew update-python-resources` is called automatically by `brew bump-formula-pr` for packages which it applies to.

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
Thanks, @laserscout!

**Comment by gromgit** [comment]
> * fought with the test-bot on style guidelines

@laserscout, if you're not already doing so, you might want to run `brew audit --strict --online --git --fix <formula>` before pushing PRs (add the `--new` option for new formulae). It automatically fixes most issues it finds, and I've found that it greatly reduces the round-tripping involved, especially when one fix inadvertently exposes another issue.

**Comment by laserscout** [comment]
@gromgit Thanks for the info! Didn't know about `--online --git --fix` I just ran `brew audit --strict <formula>` just like the PR template told me.
Maybe it's worth extending it!

**Comment by laserscout** [comment]
:( The failure seems to be gitlab actions related.

There's nothing to do on the formula

**Comment by SMillerDev** [comment]
Yeah, please do.

**Comment by laserscout** [comment]
Done @SMillerDev

**Pull request closed without merging**
