### PR TITLE
ocaml 4.11.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

Follow up PR of #57386

### CODE REVIEW

**Comment by chenrui333** [comment]
cross all three OSX builds:

```
brew install --build-from-source unison
brew install --verbose --build-bottle ocaml-num
brew install --build-from-source ocaml-num
brew install --only-dependencies --verbose --build-bottle coq
brew install --verbose --build-bottle coq
brew install --verbose --build-bottle ocamlsdl
```

**Review by ahesford — CHANGES_REQUESTED** [review]
This is missing a revbump for `unison`, which currently fails to build because the patch for ocaml 4.10 does not apply cleanly to `unison-2.51.2`. This is remedied by building `ocaml` with the `--disable-force-safe-string` configure argument and dropping the 4.10 patch for `unison`.

Please merge this with commits from my fork: 46ef9c0ff80e43ccdfde45c5da985754419ce9cd to include the `--disable-force-safe-string` option and with 526267ad87920a593096ea55d32a2e2a6866d768 to make `unison` build again.

**Comment by chenrui333** [comment]
Going to make a new PR for 4.11.1

**Comment by chenrui333** [comment]
@ahesford I will do in the new PR, thanks for the direction!

**Comment by chenrui333** [comment]
actually, we are probably not going to enable it, see #61480

**Comment by avsm** [comment]
From the OCaml perspective, we'd really prefer you distribute the stock OCaml and not a version compiled with `--disable-force-safe-string`.  If Unison's the only blocker I'm sure we can figure out how to make it work with safe-string enabled (cc @gdt)

**Comment by gdt** [comment]
There have been patches lately to unison to adapt to language changes, and we have a new unison release 2.51.3.   If that doesn't work with a default build of any released ocaml >= 4.08 (really earlier, but earlier is on thin ice), please file a bug.

**Pull request closed without merging**
