### PR TITLE
infer 0.9.3

### PR DESCRIPTION
**Pull request by jberdine**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
Build is failing.

**Comment by wingyplus** [comment]
I see build result on sierra is about git checkout error not formula error. https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8208/version=sierra/console

**Comment by MikeMcQuaid** [comment]
@wingyplus @jberdine It's part of the formula build process so still needs fixed.

**Comment by jberdine** [comment]
We are going to have to roll another release of infer in order to resolve this issue.  Closing, will open a new PR for the next version.

**Comment by MikeMcQuaid** [comment]
@jberdine Any news on this? Thanks!

**Comment by jberdine** [comment]
Superseded by #7057

**Comment by ilovezfs** [comment]
0.9.4 shipped.

**Pull request closed without merging**
