### PR TITLE
pyenv 1.0.3

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
```
  * version should not decrease
```

Seems to be a bug in audit, unless my brain isn't functioning at the moment, which is possible.

**Comment by ilovezfs** [comment]
@zmwangx regression due to https://github.com/Homebrew/brew/commit/ef58225749cc9688b86293861f7e087a0edafc5e if you feel like reporting it.

**Comment by zmwangx** [comment]
Yep apparently `version_scheme` is disregarded.

**Comment by ilovezfs** [comment]
@zmwangx may be worse than that: https://github.com/Homebrew/homebrew-core/pull/6835#issuecomment-260132724

**Comment by zmwangx** [comment]
@ilovezfs Isn't that the known `devel` problem, or did I miss something?

**Comment by zmwangx** [comment]
https://github.com/Homebrew/brew/issues/1489

**Comment by ilovezfs** [comment]
@zmwangx it says version not revision, and the PR touches neither.

**Comment by zmwangx** [comment]
@ilovezfs Okay, naughty history 72837459fa34293dfc50450e0271b1aee8015ac2.

**Comment by ilovezfs** [comment]
ridiculous.

**Comment by zmwangx** [comment]
@ilovezfs Should just compare to the latest version. No point in gathering all versions and compare to versions.max.

**Comment by tdsmith** [comment]
Assuming we can pull despite the bogus audit failure; yell at me later ;)

**Comment by tdsmith** [comment]
Thanks Zhiming!

**Pull request merged**
