### PR TITLE
curl, curl-openssl: merge

### LINKED ISSUE #57795: Install curl with same options as macOS builtin curl
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Can you install curl with the same options as the macOS builtin curl (/usr/bin/curl)?

That would allow users to use Homebrew curl for all the same cases as the macOS builtin, just with the newest version.

On my macOS 10.15.5 machine, the builtin curl has all of the installed features that the latest Homebrew curl has, but the builtin also has additional installed features.

Builtin curl is:

```bash
$ /usr/bin/curl --version
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

Whereas latest Homebrew curl is:

```bash
$ /usr/local/opt/curl/bin/curl --version
curl 7.71.1 (x86_64-apple-darwin19.5.0) libcurl/7.71.1 SecureTransport zlib/1.2.11
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

## What you expected to happen

Homebrew curl should have the same options as the macOS builtin curl.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install curl
/usr/local/opt/curl/bin/curl --version
/usr/bin/curl --version
```

I don't have any gist logs because:

```bash
brew gist-logs curl
Error: No logs.
```

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Before:

```
curl 7.71.1 (x86_64-apple-darwin18.7.0) libcurl/7.71.1 SecureTransport zlib/1.2.11
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

After:

```
curl 7.71.1 (x86_64-apple-darwin18.7.0) libcurl/7.71.1 (SecureTransport) OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 c-ares/1.16.1 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

System Curl on Catalina (for comparison):

```
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

---

Dependencies introduced from `curl-openssl` that system Curl also uses:

* `nghttp2` (note that the system library cannot be used in this case - it is private and called `libapple_nghttp2`)
* System Kerberos framework

Dependencies intentionally different than system Curl:

* `openssl@1.1` in place of `libressl` - functionally the same for most purposes and using OpenSSL means we don't have to provide two versions like we did before.
* `openldap` instead of system LDAP.framework - matches what we are doing with dependents (PHP), plus Apple's documentation clearly states to not use LDAP.framework: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html

Other dependencies introduced from `curl-openssl` that system Curl does _not_ use - feel free to dicuss these:

* `brotli`
* `c-ares` (`nghttp2` depends on this so this isn't really an extra dependency - Apple avoids this dependency with a closed-source customised version of nghttp2)
* `libmetalink`
* `libssh2`
* `rtmpdump`

Differences compared to former `curl-openssl`:

* MultiSSL is enabled.
  - _Both_ SecureTransport and OpenSSL backends are available, with the OpenSSL backend being the default. This closely matches how Apple's build works.
* Depend on `libidn2` rather than `libidn`
  - The `libidn` dependency was incorrect so wasn't actually compiling with IDN support.
  - Alternatively, we can drop `libidn2` support completely - clearly no one noticed it not working before.

### CODE REVIEW

**Review by MikeMcQuaid — DISMISSED** [review]

**Comment by SeekingMeaning** [comment]
```
==> brew test --verbose fb-client
==> FAILED
Testing fb-client
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200720-21207-fir1g7.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fb-client.rb --verbose
==> /usr/local/Cellar/fb-client/2.0.4_3/bin/fb -h
Traceback (most recent call last):
  File "/usr/local/Cellar/fb-client/2.0.4_3/libexec/bin/fb", line 15, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (none/other) is different from compile-time ssl backend (openssl)
Error: fb-client: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/fb-client/2.0.4_3/bin/fb -h
```

**Comment by Bo98** [comment]
That is a pycurl bug. I'm preparing a patch to submit upstream.

**Comment by SeekingMeaning** [comment]
Perhaps add these lines to `fb-client.rb`?

```patch
@@ -22,6 +22,18 @@ class FbClient < Formula
   resource "pycurl" do
     url "https://files.pythonhosted.org/packages/ef/05/4b773f74f830a90a326b06f9b24e65506302ab049e825a3c0b60b1a6e26a/pycurl-7.43.0.5.tar.gz"
     sha256 "ec7dd291545842295b7b56c12c90ffad2976cc7070c98d7b1517b7b6cd5994b3"
+
+    # https://github.com/pycurl/pycurl/pull/630
+    patch do
+      url "https://github.com/pycurl/pycurl/commit/8b186617241817ca0ecd31a8856561519b9a7696.patch?full_index=1"
+      sha256 "40412d4554adc2b30ee2be0ac128d5408b40f8d66acea0d318b2559b7c0d2eab"
+    end
+
+    # https://github.com/pycurl/pycurl/pull/639
+    patch do
+      url "https://github.com/pycurl/pycurl/commit/e01ba85cd1de5bbf0c07c564ef6b61fecc7b5ecf.patch?full_index=1"
+      sha256 "4289efe639d39d5dc858bab6e77cbb99efd226eab3616439a2f62001540b2f35"
+    end
   end
 
   resource "pyxdg" do
```

**Comment by MikeMcQuaid** [comment]
@SeekingMeaning Could you push those changes directly to this PR? Thanks!

**Comment by Bo98** [comment]
Since the main patch is mine (I was waiting for upstream to respond but I have given them two weeks now), I can backport it if desired. Though, the other one is pretty low risk.

**Comment by MikeMcQuaid** [comment]
@bo98 Yeh, I reckon fine to backport 👍🏻

**Comment by SeekingMeaning** [comment]
Looks like Bo is still working on this so I'll just give a `compare` link for the updated branch: https://github.com/Homebrew/homebrew-core/compare/master...SeekingMeaning:pull/curl

**Comment by Bo98** [comment]
The patch is merged upstream but there's a couple of follow-up fixes proposed against said patch (albeit for scenarios which don't affect Homebrew). I'll squash this all together into a Homebrew/formula-patches file at the weekend - I don't want to rush this and ship anything buggy.

**Comment by Bo98** [comment]
I think this is okay to merge if the migration works - I haven't had time to test that.

**Comment by rgoldberg** [comment]
What must be done to move this along?

**Comment by SMillerDev** [comment]
Someone must test the migration

**Comment by bayandin** [comment]
Let's have a look what's going on here

**Comment by bayandin** [comment]
`php@7.2` fails with https://bugs.php.net/bug.php?id=80171. Hopefully will be fixed in https://github.com/Homebrew/homebrew-core/pull/61828

**Comment by pgrenaud** [comment]
_I know this might not be the best place, but since I just found out about this merge and I'm having issue with `curl-openssl`, I thought it would be best to post this here._

I'm having DNS resolution issues with `curl` only when using `php` (installed with homebrew). And after hours of debugging, I finally found that DNS resolution of `curl-openssl` is broken (and only this "version" of curl). This stackoverflow question gave me the hint that `curl-openssl`/`c-ares` were the culprit: https://stackoverflow.com/a/60122841 And I seems to have found a similar issue in the curl mailing list: https://curl.se/mail/lib-2020-01/0052.html

To confirm my findings, I run those two commands (`example.domain` is not the real domain):

```
/usr/local/opt/curl/bin/curl --verbose example.domain
/usr/local/opt/curl-openssl/bin/curl --verbose example.domain
```

The first one works as expected, but the second one, I get `Could not resolve: example.domain (Domain name not found)`

My questions are: **Could someone explain why is `c-ares` enabled on this package (and why `c-ares` was a dependency of `curl-openssl` in the first place)? Is it necessary or could we remove this dependency and rely on macOS DNS resolution instead?**

Furthermore, looking at the `curl-openssl` formula history, @MikeMcQuaid was the one who added the `c-ares` depencency, and I see that he is present in this discussion. Would you mind sharing why you added this dependency? Thanks!

**Comment by bayandin** [comment]
`c-ares` dependency was added to `curl-openssl` (https://github.com/Homebrew/homebrew-core/pull/36065) because `with-c-ares` option was removed from `curl` formula (https://github.com/Homebrew/homebrew-core/pull/36066). I don't see or know any particular reason for it

**Comment by pgrenaud** [comment]
> `c-ares` dependency was added to `curl-openssl` (#36065) because `with-c-ares` option was removed from `curl` formula (#36066). I don't see or know any particular reason for it

Thanks for pointing that out! From what I understand, the others dependencies add features or functionalities, but that is not the case with `c-ares` which replaces macOS DNS resolution. If someone is able to confirm that, would it then be possible to remove the `c-ares` dependency?

**Comment by bayandin** [comment]
> > `c-ares` dependency was added to `curl-openssl` (#36065) because `with-c-ares` option was removed from `curl` formula (#36066). I don't see or know any particular reason for it
> 
> Thanks for pointing that out! From what I understand, the others dependencies add features or functionalities, but that is not the case with `c-ares` which replaces macOS DNS resolution. If someone is able to confirm that, would it then be possible to remove the `c-ares` dependency?

Given quite a big numbers of `curl` and `curl-openssl` installs:
- `curl`:
install: 26,717 (30 days), 92,363 (90 days), 423,642 (365 days)
install-on-request: 22,434 (30 days), 78,161 (90 days), 357,599 (365 days)
- `curl-openssl`:
install: 58,569 (30 days), 203,901 (90 days), 706,909 (365 days)
install-on-request: 19,622 (30 days), 55,677 (90 days), 104,947 (365 days)

I'd like to ask @Homebrew/core about their opinion about dropping `c-ares` dependency because it doesn't resolve some local hosts:
```
$ /usr/local/opt/curl/bin/curl --show-error --silent -o /dev/null my.local.domain
$ /usr/local/opt/curl-openssl/bin/curl --show-error --silent -o /dev/null my.local.domain
curl: (6) Could not resolve: my.local.domain (Domain name not found)
```
See also https://discourse.brew.sh/t/brews-curl-openssl-cant-resolve-localhost-hostnames-set-up-in-dnsmasq-system-curl-has-no-issue/5327/5

**Comment by MikeMcQuaid** [comment]
> I'd like to ask @Homebrew/core about their opinion about dropping `c-ares` dependency because it doesn't resolve some local hosts:

This seems fine/sensible to me 👍🏻

**Comment by iMichka** [comment]
I would not look too much at the curl/curl-openssl numbers, they are biased because we decided to split the formulae at one point. We should really merge both.

I agree that we can drop c-ares.

**Comment by bayandin** [comment]
Thanks @MikeMcQuaid and @iMichka!

`c-ares` dependency won't be moved to `curl` from `curl-openssl`. Thanks, @pgrenaud for highlighting the issue!

I've tested migration from `curl-openssl` to `curl`, and it worked fine for me:
```
$ export FORMULAE="curl-openssl curl fb-client php php@7.4 php@7.3 php@7.2"
$ `git checkout master`
$ `brew install $FORMULAE`
$ `brew test $FORMULAE` no errors here
$ `brew pr-pull 58274`
$ `brew upgrade` no errors here
$ `brew test $FORMULAE` no errors here
$ # delete bottles from bintray
```

If there's anything else we'd like to test before merging it, please let me know, otherwise, I believe, this PR is ready to go

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Ok for me, if we can ship this today I'll keep an eye on the linux side of things; but I do not expect any issue.

**Comment by pgrenaud** [comment]
Thanks a lot for the quick reply/intervention about `c-ares`. You guys rocks! 💪

**Comment by fxcoudert** [comment]
Thanks to everyone involved!

**Comment by reitermarkus** [comment]
`Homebrew/brew` CI is failing due to this:

```
onedrive:
  * Dependency 'curl-openssl' was renamed; use new name 'curl'.
````

**Comment by iMichka** [comment]
Fix incoming (on linux: https://github.com/Homebrew/linuxbrew-core/pull/21683)

**Comment by iMichka** [comment]
@reitermarkus it should be fixed now.

**Comment by reitermarkus** [comment]
Thanks, @iMichka!

**Pull request closed without merging**
