### PR TITLE
irssi 1.4.4

### PR DESCRIPTION
**Pull request by osalbahr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
```console
    CCLD     botti
  Undefined symbols for architecture arm64:
    "_default_formats", referenced from:
        _perl_signal_args_to_c in libperl_core_static.a(perl-signals.o)
        _sig_func in libperl_core_static.a(perl-signals.o)
    "_format_find_tag", referenced from:
        _perl_signal_args_to_c in libperl_core_static.a(perl-signals.o)
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[3]: *** [botti] Error 1
  make[2]: *** [all-recursive] Error 1
  make[1]: *** [all-recursive] Error 1
  make: *** [all] Error 2
```

I don't know if this error is ARM-specific, the other jobs were stopped. There's also a few `Warning: No files were found with the provided path: /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs. No artifacts will be uploaded.`.

**Comment by carlocab** [comment]
Same failure everywhere I think.

**Comment by osalbahr** [comment]
Thx! Seeing that it also fails on Linux makes it easier for me to test locally.

**Comment by osalbahr** [comment]
It looks like the issue is upstream at irssi/irssi#1435, irssi/irssi#1397 -> mesonbuild/meson#11165, PR mesonbuild/meson#11945. I've subscribed to them.

```console
@homebrew-brew:~$ brew install --build-from-source irssi
==> Fetching irssi
==> Downloading https://github.com/irssi/irssi/releases/download/1.4.4/irssi-1.4
Already downloaded: /var/home/dracula/.cache/Homebrew/downloads/1a8ac58cd83a3b1d584aba5f1a9130c1a9c3fce268e172ec86f914d531f3e29d--irssi-1.4.4.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/irssi/1.4.4 --sysconf
==> make
Last 15 lines from /var/home/dracula/.cache/Homebrew/Logs/irssi/02.make:
  CC       irssi.o
  CCLD     botti
/usr/bin/ld: ../perl/.libs/libperl_core_static.a(perl-signals.o): in function `perl_signal_args_to_c':
perl-signals.c:(.text+0x6a4): undefined reference to `format_find_tag'
/usr/bin/ld: perl-signals.c:(.text+0xac3): undefined reference to `default_formats'
/usr/bin/ld: ../perl/.libs/libperl_core_static.a(perl-signals.o): in function `sig_func':
perl-signals.c:(.text+0x2033): undefined reference to `default_formats'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:451: botti] Error 1
make[3]: Leaving directory '/tmp/irssi-20230707-123300-20edzl/irssi-1.4.4/src/fe-none'
make[2]: *** [Makefile:463: all-recursive] Error 1
make[2]: Leaving directory '/tmp/irssi-20230707-123300-20edzl/irssi-1.4.4/src'
make[1]: *** [Makefile:584: all-recursive] Error 1
make[1]: Leaving directory '/tmp/irssi-20230707-123300-20edzl/irssi-1.4.4'
make: *** [Makefile:443: all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
irssi 1.4.4 https://github.com/Homebrew/homebrew-core/pull/135874
```

**Comment by chenrui333** [comment]
should be good with #136747

**Pull request closed without merging**
