### PR TITLE
argyll-cms 2.0.1

### PR DESCRIPTION
**Pull request by jd-a**
version update

- [ X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jd-a** [comment]
SMillerDev, I am not sure what exactly you mean, I tried 'bump-formula-pr' without specifying the version, that did not work.

**Comment by DomT4** [comment]
> Does it also work without specifying the version?

Looks like it picks up the `V`, slightly annoyingly:
```
argyll-cms: stable V2.0.1
```

**Comment by fxcoudert** [comment]
@SMillerDev if the version autodetected would be the same as the explicit `version`, this gives an audit failure. So if you have no audit failure, it means you can trust that the `version` is needed :)

**Comment by fxcoudert** [comment]
Thanks @jd-a for the pull request. Please note our standardised commit message for an update should be `argyll-cms 2.0.1`

**Pull request closed without merging**
