### PR TITLE
taskell 1.9.1

### PR DESCRIPTION
**Pull request by smallhadroncollider**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by smallhadroncollider** [comment]
Getting a 404 when I try to see what went wrong with the build?

**Comment by SMillerDev** [comment]
Builds get automatically removed after some time.

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by smallhadroncollider** [comment]
Fair enough! Thanks.

**Comment by Moisan** [comment]
Thank you @smallhadroncollider !

**Pull request closed without merging**
