### PR TITLE
duckdb 0.7.0

### PR DESCRIPTION
**Pull request by Mytherin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at tools/shell/cmake_install.cmake:60 (file):
    file INSTALL cannot find "/tmp/duckdb-20230213-3906-f02mqy/build/duckdb":
    No such file or directory.
```

**Comment by Mytherin** [comment]
Thanks for having a look. I fixed the issue but now I need to push a new tag. I will update it later.

**Comment by Mytherin** [comment]
We are pushing a new bug-fix release next week (0.7.1) which should include a fix for this issue.

**Comment by chenrui333** [comment]
Sounds good! 😄

**Pull request closed without merging**
