### PR TITLE
util-linux: install bash completions

### PR DESCRIPTION
**Pull request by glensc**
Followup to https://github.com/Homebrew/homebrew-core/pull/26353#issuecomment-381234797

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by glensc** [comment]
@Habbie can you do something so the stale bot doesn't annoy and this gets actually merged?

**Comment by Habbie** [comment]
I am not a homebrew maintainer; I'm unsure what I can do, sorry!

**Comment by glensc** [comment]
don't see anything in [CONTRIBUTING.md](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) what to do when maintainers are not "seeing" PR.

**Comment by ilovezfs** [comment]
it's seen. patience.

**Comment by glensc** [comment]
@ilovezfs patience exist, just the stale bot is scary and agressive.

**Comment by ilovezfs** [comment]
We could rename it Terminator if that would help.

**Comment by ilovezfs** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @glensc

**Comment by ilovezfs** [comment]
Nothing in particular. Sorry you had to wait so long.

**Pull request closed without merging**
