### PR TITLE
fig2dev: renamed from transfig

### PR DESCRIPTION
**Pull request by tchajed**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`transfig` is a utility that generates Makefiles for figure conversion while `fig2dev` is the main conversion tool. Most users are likely to be looking for `fig2dev` rather than `transfig` (though this formula continues to install both tools).

### CODE REVIEW

**Review by fxcoudert — DISMISSED** [review]

**Review by ilovezfs — CHANGES_REQUESTED** [review]
You need to add an alias for the old name too.

**Comment by tchajed** [comment]
@ilovezfs: are you sure I need an alias as well? The [Rename a Formula](https://github.com/Homebrew/brew/blob/master/docs/Rename-A-Formula.md) guide doesn't mention adding an alias, and adding an entry to `formula_renames.json` already means operations on `transfig` continue to work.

**Comment by ilovezfs** [comment]
Yes I am sure.
```
iMac-TMP:homebrew-core joe$ rm Aliases/speedtest_cli 
iMac-TMP:homebrew-core joe$ brew install speedtest-cli
==> Using the sandbox
==> Downloading https://github.com/sivel/speedtest-cli/archive/v1.0.6.tar.gz
==> Downloading from https://codeload.github.com/sivel/speedtest-cli/tar.gz/v1.0.6
######################################################################## 100.0%
🍺  /usr/local/Cellar/speedtest-cli/1.0.6_1: 7 files, 66.6KB, built in 2 seconds
iMac-TMP:homebrew-core joe$ ls -l /usr/local/opt/|grep speed
lrwxr-xr-x  1 joe  admin  31 Aug  1 09:27 speedtest-cli -> ../Cellar/speedtest-cli/1.0.6_1
iMac-TMP:homebrew-core joe$ brew rm speedtest-cli
Uninstalling /usr/local/Cellar/speedtest-cli/1.0.6_1... (7 files, 66.6KB)
iMac-TMP:homebrew-core joe$ git checkout -- Aliases/speedtest_cli 
iMac-TMP:homebrew-core joe$ brew install speedtest-cli
==> Using the sandbox
==> Downloading https://github.com/sivel/speedtest-cli/archive/v1.0.6.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/speedtest-cli-1.0.6.tar.gz
🍺  /usr/local/Cellar/speedtest-cli/1.0.6_1: 7 files, 66.6KB, built in 1 second
iMac-TMP:homebrew-core joe$ ls -l /usr/local/opt/|grep speed
lrwxr-xr-x  1 joe  admin  31 Aug  1 09:28 speedtest-cli -> ../Cellar/speedtest-cli/1.0.6_1
lrwxr-xr-x  1 joe  admin  31 Aug  1 09:28 speedtest_cli -> ../Cellar/speedtest-cli/1.0.6_1
iMac-TMP:homebrew-core joe$ 
```

**Comment by tchajed** [comment]
Ok, just added the alias

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @tchajed!

**Pull request closed without merging**
