### PR TITLE
libxkbfile 1.1.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`.xz` file is smaller than `.tgz` file and preferred, so we should update whenever there is `.xz` file available.

**Comment by Porkepix** [comment]
> `.xz` file is smaller than `.tgz` file and preferred, so we should update whenever there is `.xz` file available.

I asked about this choice a couple of weeks ago for many X.org packages that stopped having the `.bz2` available. Another maintainer (carlocab, I think?) answered me that unless the archive file was significantly big to a have an important size difference, the tarball was better due to having less dependencies. Also, the file extension wasn't even changed in this bump. But my personnal choice would have lean toward `.tar.xz` if I wasn't answered otherwise.

Also curious if that'll be kept for long, ArchLinux used `.tar.xz` for years but changed it for LZMA (`.tar.zst`), because it's a lot less CPU intensive.

**Comment by chenrui333** [comment]
we just generally chose whatever artifact smaller

**Comment by chenrui333** [comment]
> Also curious if that'll be kept for long, ArchLinux used `.tar.xz` for years but changed it for LZMA (`.tar.zst`), because it's a lot less CPU intensive.

that actually also makes sense.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
