### PR TITLE
macvim: revision for system Ruby upgrade, remove options.

### LINKED ISSUE #32464: Macvim install fails on MacOS 10.14
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

### What you were trying to do (and why)
I was attempting to install macvim with lua on a fresh install of MacOS 10.14.

```
brew install macvim --with-lua
```

### What happened (include command output)
https://gist.github.com/agrieser/ddc9c2fc4faec2db971ed11cf7617492

```
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
```

### What you expected to happen
Compile without errors

### Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install macvim --with-lua
```

Xcode and command line tools are installed and up to date.

Changing the command line tool direction between `/Library/Developer/CommandLineTools` and `/Applications/Xcode.app/Contents/Developer` did not make a difference.

### LINKED ISSUE #33656: Homebrew macvim will not run after Sierra Security Update
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
$ brew gist-logs macvim
https://gist.github.com/a5b31f056914bca8346c18edd0244a69

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to run macvim from the command line via the gvim shell script.

- What happened (include command output)

$ gvim
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib
Referenced from: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/bin/…/MacOS/Vim
Reason: image not found
Abort

- What you expected to happen

I expected macvim to launch as it normally does.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install macvim (I've also done a brew reinstall macvim and vim)
Then run /usr/local/bin/gvim.

Note that my PATH is:
/Users/willf/bin:/usr/local/bin:/usr/local/sbin:/usr/local/MacGPG2/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11/bin

$ type gvim
gvim is a tracked alias for /usr/local/bin/gvim

$ brew gist-logs macvim
https://gist.github.com/a5b31f056914bca8346c18edd0244a69

$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 1.8.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 422257067cc46d86138baa0e8e453348c2829cee
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bfe0d507a7c13120bff3aa3d05aee131bd905f1d
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_25
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11

More detail:

After I updated my Mini running Sierra (there are reasons I have not updated the OS on that system) with the latest Security update from Apple, the homebrew version of macvim (and gvim, etc…) became unable to run giving this error:

$ gvim
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib
Referenced from: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/bin/…/MacOS/Vim
Reason: image not found
Abort

I have checked /System/Library/Frameworks/Ruby.framework/Versions and there is now a 2.3 folder which contains the ruby binary unlike the 2.0 folder. Looking at a Time Machine backup of the Versions folder I see that 2.3 was introduced by the security update.

As an aside, there is also a Current symlink in Versions that points to the most recent version of Ruby, so I’m wondering if it is possible to compile macvim to use that symlink instead of specifying the version of ruby to use? Or use the homebrew variant of ruby?

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This is based on their `brew info --analytics` usage and build errors.

Part of https://github.com/Homebrew/homebrew-core/issues/31510.

Closes #34387.
References #10951.
Fixes #32464.
Fixes #33656.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
#34387 might be related as well to some extent

**Comment by javian** [comment]
```
13:18:36 ==> brew audit macvim --online
13:19:09 ==> FAILED
13:19:09 Error: 2 problems in 1 formula detected
13:19:09 macvim:
13:19:09   * C: 21: col 3: dependency "lua" (line 21) should be put before dependency "python" (line 20)
13:19:09   * C: 22: col 3: dependency "luajit" (line 22) should be put before dependency "python" (line 20)
```

**Comment by sethdeckard** [comment]
There are some Vim plugins that do not work with LuaJIT enabled, could we consider making LuaJIT optional?

**Comment by MikeMcQuaid** [comment]
@sethdeckard See https://github.com/Homebrew/homebrew-core/issues/31510. We're open to debate on what the defaults should be but we're not going to add any options back.

**Comment by sethdeckard** [comment]
Thanks @MikeMcQuaid, that makes sense. I'll look into creating a "without luajit" tap if one doesn't already exist.

**Comment by MikeMcQuaid** [comment]
@sethdeckard Perfect, thanks for being so understanding. Excuse my ignorance but presumably there are some plugins that _don't_ work without LuaJIT?

**Comment by sethdeckard** [comment]
@MikeMcQuaid There are some plugins that depend on Lua but don't work with LuaJIT (because it doesn't embed well in shared libraries). So basically you want a MacVim with Lua support configured in the build but with LuaJIT disabled.

**Comment by MikeMcQuaid** [comment]
@sethdeckard Again excuse my ignorance but: why would some people wish to have LuaJIT enabled in MacVim?

**Comment by sethdeckard** [comment]
@MikeMcQuaid Here's a [good thread](https://www.freelists.org/post/luajit/OSx-load-luajit-64bit-from-plugin,1) on the topic, the short answer is that LuaJIT cannot be reliably embedded in shared objects.

**Comment by sethdeckard** [comment]
@MikeMcQuaid Just to clarify that explains why people **would not** want LuaJIT enabled in MacVim but would still want Lua support. I believe the primary reason as to why some **would** want LuaJIT support is for increased performance.

**Comment by MikeMcQuaid** [comment]
@sethdeckard Have opened https://github.com/Homebrew/homebrew-core/pull/34548 to address this. Thanks for explaining ❤️

**Comment by sethdeckard** [comment]
Thank you @MikeMcQuaid, I think removing LuaJIT is the best solution as there's likely less people looking to build MacVim with LuaJIT and thus creating a tap to support that specially would seem to make more sense.

**Pull request closed without merging**
