### PR TITLE
chdig 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by azat**
### Checklist

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?
  - almost:
    - `line 14, col 3: Formulae in homebrew/core should not use 'depends_on "pyoxidizer" => [:build]'.`

### CODE REVIEW

**Comment by azat** [comment]
```
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/c/chdig.rb:14:3: C: FormulaAudit/PyoxidizerCheck: Formulae in homebrew/core should not use 'depends_on "pyoxidizer" => [:build]'.
    depends_on "pyoxidizer" => [:build]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  6995 files inspected, 1 offense detected
```

Hm, can someone suggest on this? How can I make dependency from `pyoxidizer`? (it requires for build)

**Comment by p-linnane** [comment]
`pyoxidizer` is not allowed in homebrew-core as it downloads prebuilt binaries of Python and Rust and embeds that Python into the binaries it produces. This goes against our packaging policies.

**Comment by azat** [comment]
So there is no way to build it with pyoxidizer?
And downloading pre-build binaries is also against policy I guess?

**Comment by p-linnane** [comment]
I'm not familiar with this software, so can't speak to it's build process and requirements.

Everything in homebrew-core must build from source. We cannot use pre-built binaries.

**Comment by azat** [comment]
Got it, thanks.
And what if I will install pyoxidizer into virtualenv via pip for building, will this be against your policies?

**Comment by p-linnane** [comment]
CC @Homebrew/core for thoughts.

**Comment by MikeMcQuaid** [comment]
`pyoxidizer` seems like a tool designed to that Python is not required at runtime as it is baked into the binary. This goes against the approach we want to use in Homebrew (and pretty much any other package manager will agree): instead Python should just be a runtime dependency.

**Pull request closed without merging**
