### PR TITLE
dhall 1.26.0

### PR DESCRIPTION
**Pull request by nbouscal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nbouscal** [comment]
This package fails to build on GHC 8.8.1 but builds successfully on GHC 8.6.5. Is there a way to update it using the previous version of the compiler, or do we need to wait for it to successfully build on the current (quite recently released) version?

**Comment by nbouscal** [comment]
I've added a versioned formula for GHC 8.6.5, created from a copy of the last formula prior to the 8.8 upgrade, modified to attempt to follow all of the versioning guidelines. On my machine this makes the updated `dhall` formula build successfully. The only violation when running `brew audit --strict --online` is the use of a binary for bootstrapping, because `ghc@8.6` isn't in the [`BINARY_FORMULA_URLS_WHITELIST`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/urls.rb) (`ghc` and `ghc@8.2` are). I'd add it as part of the PR, but it's in a different repository.

Most Haskell projects won't build on GHC 8.8.1 yet, so hopefully that's sufficient reason to add a versioned formula. Happy to make any necessary changes.

**Comment by nbouscal** [comment]
Looks like the only remaining failure is the aforementioned audit failure due to GHC requiring a binary formula URL for bootstrapping. What should my next steps be here?

**Comment by fxcoudert** [comment]
We'll ignore that. Thanks, merging!

**Pull request closed without merging**
