### PR TITLE
libnfs 5.0.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Matches this upstream issue: https://github.com/sahlberg/libnfs/issues/371

**Comment by carlocab** [comment]
Hmm, guess the suggested fix in the issue is unrelated.

**Comment by heitbaum** [comment]
> Matches this upstream issue: [sahlberg/libnfs#371](https://github.com/sahlberg/libnfs/issues/371)

Non pthread build fixed with
- https://github.com/sahlberg/libnfs/issues/372

**Comment by carlocab** [comment]
Thanks for the update, @heitbaum.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/94217 looks almost done, so adding the `CI-long-timeout` label.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
