### PR TITLE
tkdiff 5.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
I guess this needs a `uses_from_macos "tcl-tk"`?

**Comment by chenrui333** [comment]
much better

>   ==> /home/linuxbrew/.linuxbrew/Cellar/tkdiff/5.3/bin/tkdiff --help
>   application-specific initialization failed: no display name and no $DISPLAY environment variable

**Comment by SMillerDev** [comment]
That's not really a fix for the unix test, now we don't know if it works at all. Is there nothing else we can check?

**Comment by chenrui333** [comment]
> That's not really a fix for the Linux test, now we don't know if it works at all. Is there nothing else we can check?

The issue is with the tk initialization is linux build and I adopted the same test from the `tcl-tk` formula.

**Comment by chenrui333** [comment]
I tried to do some display setup, but did not quite work in the linux container.

**Comment by chenrui333** [comment]
@SMillerDev Any thoughts?

**Comment by chenrui333** [comment]
I think we can merge this.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
