### PR TITLE
Deprecate :ruby - part 1

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
not ready to do these yet

**Comment by commitay** [comment]
Sorry!

**Comment by commitay** [comment]
Should I close this and reopen later?

**Comment by ilovezfs** [comment]
yeah let's hold off on these for now

**Comment by commitay** [comment]
I've done the other `:ruby` Formulae so I can submit them when you are ready for them.

Just not sure if `bottle :unneeded ` and `:optional` / `:recommended` need a revision line?

**Comment by ilovezfs** [comment]
optional doesn't. anything else does. but I doubt we'll be using straight up `depends_on "ruby"` for any of them

**Comment by ilovezfs** [comment]
@commitay so I think what we should do here is convert

```
depends_on :ruby => "2.3"
depends_on :ruby => "2.2"
depends_on :ruby => "2.1"
```
into
```
depends_on "ruby" if MacOS.version <= :sierra
```

```
depends_on :ruby => "2.0"
depends_on :ruby => "1.9"
```
into
```
depends_on "ruby" if MacOS.version <= :mountain_lion
```

```
depends_on :ruby => "1.8"
```
into

nothing (since even Tiger had 1.8)

**Comment by ilovezfs** [comment]
@commitay do you want to handle the `:perl` ones too?

OS X 10.6 had 5.10
OS X 10.8, OS X 10.7 had 5.12.4
OS X 10.9 had 5.16.2
OS X 10.10, OS X 10.11, macOS 10.12, macOS 10.13 have 5.18.2

```
5.26 => depends_on "perl"
5.25 => depends_on "perl"
5.24 => depends_on "perl"
5.23 => depends_on "perl"
5.22 => depends_on "perl"
5.21 => depends_on "perl"
5.20 => depends_on "perl"
5.19 => depends_on "perl" 
5.18 => depends_on "perl" if MacOS.version <= :mavericks
5.17 => depends_on "perl" if MacOS.version <= :mavericks
5.16 => depends_on "perl" if MacOS.version <= :mountain_lion
5.15 => depends_on "perl" if MacOS.version <= :mountain_lion
5.14 => depends_on "perl" if MacOS.version <= :mountain_lion
5.13 => depends_on "perl" if MacOS.version <= :mountain_lion
5.12 => depends_on "perl" if MacOS.version <= :snow_leopard
5.11 => depends_on "perl" if MacOS.version <= :snow_leopard
5.10 => nothing
5.9 => nothing
5.8 => nothing
5.7 => nothing
5.6 => nothing
5.5 => nothing
5.4 => nothing
5.3 => nothing
```

**Comment by commitay** [comment]
Sure, I'll split them up into a couple of PRs. 

`git` and `openssl@1.1` look like they need their options tweaked a little, should I use what you have in https://github.com/Homebrew/homebrew-core/pull/22703?

I missed `vim@7.4` out of `:ruby`, should I update it based on the changes made to `vim`?

**Comment by ilovezfs** [comment]
As a first pass, yes and yes.

**Pull request closed without merging**
