### PR TITLE
aom 3.7.0

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
CI on arm64 has already taken more than 14 hours (and is still running). That's very unusual.

**Comment by bayandin** [comment]
> Update: and it should still be quick; tested on an M1 machine and this only took ~2 mins.

I've tried to run it locally, and it also stuck for me (on M1). Running `cmake` with `--trace` shows that it is stuck on 
```
/opt/homebrew/Cellar/cmake/3.27.4/share/cmake/Modules/Compiler/GNU.cmake(77):  execute_process(COMMAND ${CMAKE_ASM_COMPILER} -Wl,--help OUTPUT_VARIABLE _linker_capabilities ERROR_VARIABLE _linker_capabilities )
```
(or doing something after it, but not saying it)

`brew config` for the reference:
```
% brew config
HOMEBREW_VERSION: 4.1.7-43-ge7d0625
ORIGIN: https://github.com/Homebrew/brew
HEAD: e7d0625776dca58c81b03c19eeda1af8bd6bb58e
Last commit: 86 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1e7b85ce531c0747f17825d501f08b3613d4621f
Core tap last commit: 18 hours ago
Core tap branch: bump-aom-3.7.0
Core tap JSON: 02 Sep 23:18 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

**Review by bayandin — COMMENTED** [review]
And we can address a couple of comments in the formula:

```
    # `jpeg-xl` is currently not bottled on Linux
    ...
    # Make unconditional when `jpeg-xl` is bottled on Linux
```

`jpeg-xl` has a bottle for linux.

```
    ENV.runtime_cpu_detection unless Hardware::CPU.arm?
    ...
    # Runtime CPU detection is not currently enabled for ARM on macOS.
    args << "-DCONFIG_RUNTIME_CPU_DETECT=0" if Hardware::CPU.arm?
```

This might have been fixed

**Comment by ZhongRuoyu** [comment]
> I've tried to run it locally, and it also stuck for me (on M1).

As it turned out, I checked out the wrong tag initially. My bad!

This was due to [this change](https://aomedia.googlesource.com/aom.git/+/a250c26cade747ead5ff434ba4c69ca012115e5b%5E%21/#F0) where `CMAKE_ASM_COMPILER` was set to `as`. `as` didn't like the `-Wl,--help` argument, and instead waits for input from stdin:

```console
$ /usr/bin/as -Wl,--help
clang: warning: -Wl,--help: 'linker' input unused [-Wunused-command-line-argument]
[and it hangs]
```

Fix proposed at https://aomedia-review.googlesource.com/c/aom/+/180942.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
