### PR TITLE
Upload bottles to GitHub Packages

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Revert the reverts.

TODO: need to figure out how to get `skopeo` to not be built from source.

It may be https://github.com/Homebrew/brew/pull/11010 is enough to find it in the Ubuntu image 🤞🏻 

Edit: it was.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Trying `gatsby-cli`: https://github.com/Homebrew/homebrew-core/actions/runs/712175043

**Comment by MikeMcQuaid** [comment]
Actually, holding off until https://github.com/Homebrew/brew/pull/11012 is merged.

**Comment by MikeMcQuaid** [comment]
Hmm, no idea what's going on this time. Something credential related but they are creating packages fine on Homebrew/brew 🤔.

**Comment by Bo98** [comment]
`pr-pull` needs adjusting more to avoid a duplicate cherry-pick: https://github.com/Homebrew/homebrew-core/runs/2277978810?check_suite_focus=true#step:11:19

**Pull request merged**
