### PR TITLE
subversion: need SWIG 3.x

### PR DESCRIPTION
**Pull request by xu-cheng**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Find this issue in https://github.com/Homebrew/linuxbrew-core/pull/13100

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is swig 3 still officially supported by upstream?

**Comment by xu-cheng** [comment]
> Is swig 3 still officially supported by upstream?

Which upstream? SVN or SWIG?

AFAIK, swig 4.0 is a major update with several breaking changes. And SVN build system only works with SWIG 3.x or below.

**Comment by SMillerDev** [comment]
Swig upstream. Otherwise it's not really allowed: https://docs.brew.sh/Versions#acceptable-versioned-formulae

**Comment by xu-cheng** [comment]
While without SWIG 3.x, current subversion is broken. (You can try: `brew install svn -s` locally).

Also, there is `swig@3.04` formula in homebrew-core.

**Comment by golddranks** [comment]
LLDB and Rust's LLDB bindings are also currently broken because they need `>= Swig 3.0.11`. Making 3.0.x uninstallable through `brew` after a few days from the release of 4.0 has surely broken other things too. I'm going to ask about the support from SWIG mailing list.

**Comment by golddranks** [comment]
Asked. We'll hear the answer hopefully soon. Meanwhile, I'd like to point out that ending support for a major version without any deprecation period is not a good practice. I'd like to see these kinds of situations addressed somehow – for example, making the older major versions being installable at least for some automatic deprecation period such as 6 months.

**Comment by golddranks** [comment]
Got an answer: https://sourceforge.net/p/swig/mailman/message/36690602/ There is no support for 3.0.x. This also makes the existence of the recipe for `swig@3.04' suspect, according to the standards of Homebrew project.

**Comment by SMillerDev** [comment]
Homebrew can't really provide support for software that upstream doesn't support. The best/only way to get support is to convince the software development world that they should maintain old versions longer.

As for the 3.04 version, yeah that should probably be removed

**Comment by zbeekman** [comment]
Here are my thoughts on the matter:

Given that swig is critical build system infrastructure (e.g., llvm, tbb, scipy), and that the 4.0.0 release had breaking changes, I think it is reasonable to maintain a `swig@3` for a brief period while other packages get updated to use the latest `4.0.x`.

However, I do not think we should accept dependencies on `swig@3` or other packages where upstream has dropped support without evidence of a corresponding bug report to the package that needs the deprecated version.

I also agree that `swig@3.0.4` needs to go.

**Review by zbeekman — CHANGES_REQUESTED** [review]
@xu-cheng: Could you please also delete `swig@3.0.4` in this PR? 

Can someone either find a bug report for this with SVN, or open a new one? Then link to it at least in the commit message, or, better yet, (assuming the URL is not unreasonably long) link to it in a comment next to the dependency so we can assess when it should be upgraded to depend on the latest swig?

Thanks!

**Comment by golddranks** [comment]
There seems to be a bug for supporting SWIG 4: https://issues.apache.org/jira/browse/SVN-4818?jql=project%20%3D%20SVN%20AND%20text%20~%20%22SWIG%22
I'm going to send a patch to LLVM unless it's already done.

**Comment by zbeekman** [comment]
> I'm going to send a patch to LLVM unless it's already done.

Sorry, I'm not following. Are you sending a patch *to* llvm or a patch (to us) *for* llvm to use swig@3? Or do you know the work around that lets llvm use swig 4?

**Comment by golddranks** [comment]
I am going to report a bug and send a patch to LLVM project that allows their Python wrappers to work with SWIG 4.

**Comment by zbeekman** [comment]
Awesome! Thanks!

**Comment by golddranks** [comment]
I figured that the Swig changes would be merged faster if I did the needed changes and sent a new PR, so here it is. https://github.com/Homebrew/homebrew-core/pull/40882 After these changes there is still a need to update the SVN package. I'd like to leave that to @xu-cheng since I know little about that package.

**Comment by xu-cheng** [comment]
Updated PR after #40882

**Review by lembacon — APPROVED** [review]

**Comment by lembacon** [comment]
Thanks @xu-cheng and everyone else for the effort!

**Pull request closed without merging**
