### PR TITLE
hasura-cli 2.0.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@carlocab `hasura-cli`, `netlify-cli` #81621  and `gatsby-cli` #81623 are all failing with the universal binaries inside of fsevents. Same as what we saw on #81582 

I would expect this same situation to occur on a vast majority of nodejs formula.

**Comment by carlocab** [comment]
This one is different:
```
make[2]: *** No rule to make target `bin/cli-ext-hasura-node12-linux-x64.sha256'.  Stop.
```
`netlify-cli` and `gatsby-cli` also install x86 binaries (likely pre-built) on ARM:
```
netlify-cli:
  * Binaries built for an incompatible architecture were installed into netlify-cli's prefix.
    The offending files are:
      /opt/homebrew/Cellar/netlify-cli/5.1.0/libexec/lib/node_modules/netlify-cli/node_modules/term-size/vendor/macos/term-size
```
```
gatsby-cli:
  * Binaries built for an incompatible architecture were installed into gatsby-cli's prefix.
    The offending files are:
      /opt/homebrew/Cellar/gatsby-cli/3.10.0/libexec/lib/node_modules/gatsby-cli/node_modules/term-size/vendor/macos/term-size
```
```
❯ file libexec/lib/node_modules/netlify-cli/node_modules/term-size/vendor/macos/term-size
libexec/lib/node_modules/netlify-cli/node_modules/term-size/vendor/macos/term-size: Mach-O 64-bit executable x86_64
```

We could probably add `netlify-cli` and `gatsby-cli` to the allowlist, and I already have an open PR (Homebrew/brew#11756) that should allow us to extract the native slices from the universal binaries.

We still need to decide what we want to do about x86 binaries getting installed on ARM though. I think we can ignore the audit failures for now. I'll open an issue to start a discussion about what to do about them.

**Comment by carlocab** [comment]
Opened #81666 so we can decide what to do about these.

**Comment by carlocab** [comment]
Per #81666, if we can't find a way to build native versions of the x86 binaries, we should just delete them. And maybe add some caveats saying so.

**Comment by chenrui333** [comment]
#83354

**Pull request closed without merging**
