### PR TITLE
sleuthkit 4.7.0

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
compile:
    [javac] Compiling 81 source files to /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/build
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:33: error: package javafx.beans.property does not exist
    [javac] import javafx.beans.property.BooleanProperty;
    [javac]                             ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:34: error: package javafx.beans.property does not exist
    [javac] import javafx.beans.property.Property;
    [javac]                             ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:35: error: package javafx.beans.property does not exist
    [javac] import javafx.beans.property.SimpleBooleanProperty;
    [javac]                             ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:36: error: package javafx.beans.property does not exist
    [javac] import javafx.beans.property.SimpleStringProperty;
    [javac]                             ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:37: error: package javafx.collections does not exist
    [javac] import javafx.collections.FXCollections;
    [javac]                          ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:38: error: package javafx.collections does not exist
    [javac] import javafx.collections.ObservableList;
    [javac]                          ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:342: error: cannot find symbol
    [javac] 		UnionFilter(ObservableList<SubFilterType> subFilters) {
    [javac] 		            ^
    [javac]   symbol:   class ObservableList
    [javac]   location: class UnionFilter<SubFilterType>
    [javac]   where SubFilterType is a type-variable:
    [javac]     SubFilterType extends TimelineFilter declared in class UnionFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:371: error: cannot find symbol
    [javac] 		private final SimpleStringProperty descriptionSubstring = new SimpleStringProperty();
    [javac] 		              ^
    [javac]   symbol:   class SimpleStringProperty
    [javac]   location: class TextFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:426: error: cannot find symbol
    [javac] 		public Property<String> substringProperty() {
    [javac] 		       ^
    [javac]   symbol:   class Property
    [javac]   location: class TextFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:887: error: cannot find symbol
    [javac] 		private final BooleanProperty eventSourcesHaveHashSetHits = new SimpleBooleanProperty();
    [javac] 		              ^
    [javac]   symbol:   class BooleanProperty
    [javac]   location: class HashHitsFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:249: error: cannot find symbol
    [javac] 		private final BooleanProperty eventSourcesAreTagged = new SimpleBooleanProperty();
    [javac] 		              ^
    [javac]   symbol:   class BooleanProperty
    [javac]   location: class TagsFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:733: error: cannot find symbol
    [javac] 		private final ObservableList<SubFilterType> subFilters = FXCollections.observableArrayList();
    [javac] 		              ^
    [javac]   symbol:   class ObservableList
    [javac]   location: class CompoundFilter<SubFilterType>
    [javac]   where SubFilterType is a type-variable:
    [javac]     SubFilterType extends TimelineFilter declared in class CompoundFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:740: error: cannot find symbol
    [javac] 		public final ObservableList<SubFilterType> getSubFilters() {
    [javac] 		             ^
    [javac]   symbol:   class ObservableList
    [javac]   location: class CompoundFilter<SubFilterType>
    [javac]   where SubFilterType is a type-variable:
    [javac]     SubFilterType extends TimelineFilter declared in class CompoundFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/SleuthkitCase.java:8449: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 	protected void finalize() throws Throwable {
    [javac] 	               ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/SleuthkitCase.java:8453: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 			super.finalize();
    [javac] 			     ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/AbstractFile.java:1036: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 	protected void finalize() throws Throwable {
    [javac] 	               ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/AbstractFile.java:1040: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 			super.finalize();
    [javac] 			     ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/FileSystem.java:184: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 	public void finalize() throws Throwable {
    [javac] 	            ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/FileSystem.java:191: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 			super.finalize();
    [javac] 			     ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/Image.java:144: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 	public void finalize() throws Throwable {
    [javac] 	            ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/Image.java:151: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 			super.finalize();
    [javac] 			     ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/Volume.java:88: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 	public void finalize() throws Throwable {
    [javac] 	            ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/Volume.java:92: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 			super.finalize();
    [javac] 			     ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/VolumeSystem.java:127: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 	public void finalize() throws Throwable {
    [javac] 	            ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/VolumeSystem.java:131: warning: [deprecation] finalize() in Object has been deprecated
    [javac] 			super.finalize();
    [javac] 			     ^
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:77: warning: [cast] redundant cast to S
    [javac] 		from.getSubFilters().forEach(subFilter -> to.addSubFilter((S) subFilter.copyOf()));
    [javac] 		                                                          ^
    [javac]   where S,T are type-variables:
    [javac]     S extends TimelineFilter declared in method <S,T>copySubFilters(T,T)
    [javac]     T extends CompoundFilter<S> declared in method <S,T>copySubFilters(T,T)
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:733: error: cannot find symbol
    [javac] 		private final ObservableList<SubFilterType> subFilters = FXCollections.observableArrayList();
    [javac] 		                                                         ^
    [javac]   symbol:   variable FXCollections
    [javac]   location: class CompoundFilter<SubFilterType>
    [javac]   where SubFilterType is a type-variable:
    [javac]     SubFilterType extends TimelineFilter declared in class CompoundFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:103: warning: [cast] redundant cast to SubFilterType
    [javac] 			List<SubFilterType> subfilters = Lists.transform(getSubFilters(), f -> (SubFilterType) f.copyOf()); //make copies of all the subfilters.
    [javac] 			                                                                       ^
    [javac]   where SubFilterType is a type-variable:
    [javac]     SubFilterType extends TimelineFilter declared in class IntersectionFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:347: error: cannot find symbol
    [javac] 			super(FXCollections.<SubFilterType>observableArrayList());
    [javac] 			      ^
    [javac]   symbol:   variable FXCollections
    [javac]   location: class UnionFilter<SubFilterType>
    [javac]   where SubFilterType is a type-variable:
    [javac]     SubFilterType extends TimelineFilter declared in class UnionFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:152: error: cannot find symbol
    [javac] 			super(FXCollections.observableArrayList());
    [javac] 			      ^
    [javac]   symbol:   variable FXCollections
    [javac]   location: class EventTypeFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:249: error: cannot find symbol
    [javac] 		private final BooleanProperty eventSourcesAreTagged = new SimpleBooleanProperty();
    [javac] 		                                                          ^
    [javac]   symbol:   class SimpleBooleanProperty
    [javac]   location: class TagsFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:371: error: cannot find symbol
    [javac] 		private final SimpleStringProperty descriptionSubstring = new SimpleStringProperty();
    [javac] 		                                                              ^
    [javac]   symbol:   class SimpleStringProperty
    [javac]   location: class TextFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:585: error: cannot find symbol
    [javac] 			super(FXCollections.observableArrayList(descriptionSubstringFilter, knownFilesFilter, tagsFilter, dataSourcesFilter, hashSetHitsFilter, fileTypesFilter, eventTypesFilter));
    [javac] 			      ^
    [javac]   symbol:   variable FXCollections
    [javac]   location: class RootFilter
    [javac] /private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/src/org/sleuthkit/datamodel/TimelineFilter.java:887: error: cannot find symbol
    [javac] 		private final BooleanProperty eventSourcesHaveHashSetHits = new SimpleBooleanProperty();
    [javac] 		                                                                ^
    [javac]   symbol:   class SimpleBooleanProperty
    [javac]   location: class HashHitsFilter
    [javac] 20 errors
    [javac] 14 warnings

BUILD FAILED
/private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/build.xml:181: The following error occurred while executing this line:
/private/tmp/sleuthkit-20191017-59336-yaxp4k/sleuthkit-4.7.0/bindings/java/build.xml:132: Compile failed; see the compiler error output for details.
```

**Comment by esaunders** [comment]
This appears to be due to the fact that sleuthkit needs to be built against a Java 8 distribution and requires OpenJFX.
At a minimum we should probably change the "depends_on: java" to be "depends_on: adoptopenjdk8" but that still won't solve the fact that FX is missing.
I don't know of an easy fix for this at this point. Ideally, if the following issue gets fixed by the AdoptOpenJDK folks we will have a Java 8 version of OpenJDK that includes Java FX.

https://github.com/AdoptOpenJDK/openjdk-build/issues/577

**Comment by esaunders** [comment]
If I want to contribute a possible fix for this issue should I open a new pull request?

**Comment by Moisan** [comment]
@esaunders: Yes, feel free to open a new pull request if you found a fix and it would be quicker that way.

**Comment by esaunders** [comment]
I created https://github.com/Homebrew/homebrew-core/pull/46628 but it has the same build issue that this PR has...i.e. the version of Java does not have FX.
My PR builds and installs fine on a clean local machine. Two things stand out in the Jenkins build log for my PR. 

1. it appears as though the build machine has 2 versions of Java installed:
> Java: 13, 1.8.0_222
2. The Java 1.8 version is AdoptOpenJDK 1.8.**0_222** whereas the latest cask version for adoptopenjdk8 is 1.8.0.**232**

Perhaps we just need to wait for the build systems to be updated?
Given that the only difference between this PR and mine is the Java version dependency I'll go ahead and close mine.
I believe that (a) once the build systems have been updated to use the latest version of adoptopenjdk8 and (b) the java dependency in the sleuthkit formula is updated to "1.8" that this PR will build successfully.

**Comment by Moisan** [comment]
Closing for now since this seems to be an upstream issue.

**Pull request closed without merging**
