### PR TITLE
ncspot 0.2.4 (new formula)

### PR DESCRIPTION
**Pull request by codetheweb**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds [ncspot](https://github.com/hrkfdn/ncspot).

### CODE REVIEW

**Comment by codetheweb** [comment]
It appears 10.14 is failing because of the [coreaudio-rs](https://github.com/RustAudio/coreaudio-rs) dependency. Unclear on why this is happening, any advice is appreciated.
Maybe the Core Audio libraries changed slightly between versions? Didn't see any relevant issues.

**Comment by jonchang** [comment]
Try the fix in https://github.com/Homebrew/homebrew-core/pull/62784

The test needs to be improved.

**Comment by codetheweb** [comment]
Thank you for figuring out the Core Audio issue so quickly!

Could you give some more details on what you want the test to do? `ncspot` only provides a few flags:

```
ncspot 0.2.4
Henrik Friedrichsen <henrik@affekt.org> and contributors
cross-platform ncurses Spotify client

USAGE:
    ncspot [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -b, --basepath <PATH>    custom basepath to config/cache files
    -d, --debug <FILE>       Enable debug logging to the specified file

Audio backends: rodio, pipe, subprocess
```

Other formulas I found that use ncurses [have](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lnav.rb) [very similar](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ncmpc.rb) tests.

**Comment by jonchang** [comment]
See the test for `spotify-tui` as an example of what it might look like.

**Comment by codetheweb** [comment]
I had a hard time getting it to capture the curses output properly (following the spotify-tui example) so I used the debug log instead. Hopefully that's acceptable.

**Comment by jonchang** [comment]
Thanks for contributing to Homebrew, @codetheweb!

**Pull request closed without merging**
