### PR TITLE
Update open-zwave.rb

### PR DESCRIPTION
**Pull request by irundaia**
Hi, 

I was asking for [help](https://github.com/homebrew/homebrew-core/issues/3252) while updating open-zwave. @DomT4 asked me to submit a pull request, so here it is. 

Please do not merge this as-is.
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Update open-zwave to version 1.4.164.

### CODE REVIEW

**Comment by DomT4** [comment]
```
cpp/build/support.mk
94:pkgconfigdir ?= $(shell if [ -d "/usr/lib64/pkgconfig" ]; then echo "/usr/lib64/pkgconfig"; else echo "/usr/lib/pkgconfig"; fi)

ozw_config
19:pcfile=/usr/lib/pkgconfig/libopenzwave.pc
```

That's probably why. It's ended up hardcoded to `/usr/lib`, regardless of the `prefix` being passed, partly because there's no `pkg-config` dependency in this formula so it assumes what upstream presumably think is a safe default _(Very much isn't on OS X)_. Adding a `pkg-config => :build` dep doesn't entirely resolve the problem though:

```
install: chmod 755 //usr/local/lib/pkgconfig: Operation not permitted
cp: //usr/local/lib/pkgconfig/libopenzwave.pc: Operation not permitted
```

This'll work:
```diff
diff --git a/Formula/open-zwave.rb b/Formula/open-zwave.rb
index 718accf..cc641f7 100644
--- a/Formula/open-zwave.rb
+++ b/Formula/open-zwave.rb
@@ -4,11 +4,13 @@ class OpenZwave < Formula
   url "http://old.openzwave.com/downloads/openzwave-1.4.164.tar.gz"
   sha256 "4ecf39787aaf278c203764069b581dbc26094ce57cafeab4a0c1f012d2c0ac69"
 
+  depends_on "pkg-config" => :build
+
   def install
     ENV["BUILD"] = "release"
     ENV["PREFIX"] = prefix
 
-    system "make", "install"
+    system "make", "install", "pkgconfigdir=#{lib}/pkgconfig"
   end
 
   test do
```

**Comment by irundaia** [comment]
Great thanks, I can confirm that this works now. But the files still aren't installed in /usr/local. I'll have another look at it soon. 

Thanks for the effort!

**Comment by DomT4** [comment]
Are you sure they aren't there in symlink form? Homebrew doesn't place anything, well, except perhaps `npm`, into `/usr/local` _directly_.

We install into, for example, `/usr/local/Cellar/open-zwave/1.4.164` and then anything in that directory + `bin`, `include`, `lib` or `share` gets linked into `/usr/local` via symlink.

**Comment by irundaia** [comment]
I couldn't find them with an `ls -l` in `/usr/local/lib` I'll make sure to have another look.

**Comment by irundaia** [comment]
You are correct! Sorry for the mixup :(

**Comment by DomT4** [comment]
Yes, indeed. It's a very odd one:
```
Warning: The installation was broken.
Broken dylib links found:
  /private/tmp/open-zwave-20160728-22096-xjz6t2/openzwave-1.4.164/libopenzwave-1.4.dylib
==> Summary
🍺  /usr/local/Cellar/open-zwave/1.4.164: 386 files, 3.0M, built in 15 seconds
```

@ilovezfs: You're good at mysteries. Any thoughts here?

**Comment by ilovezfs** [comment]
Yeah, the problem is that install_name is not set so the example binary MinOZW gets linked with the path to the library at link time, which happens to be the buildpath in this case.

```
+    inreplace "cpp/build/Makefile",
+      "LDFLAGS += -dynamiclib",
+      "LDFLAGS += -dynamiclib -install_name #{lib}/$(SHARED_LIB_NAME)"
```
fixes it.

**Comment by irundaia** [comment]
Indeed that works :+1:  Thanks a bunch!

**Comment by ilovezfs** [comment]
@irundaia you're welcome. It would be helpful if you could report that upstream and include a comment above the inreplace with the URL to the bug report and brief note (can be one line) about what bug it fixes.

Also, the sysconfdir is currently set incorrectly because it's defaulting to #{prefix}/etc (i.e., /usr/local/Cellar/open-zwave/1.4.164/etc, which is incorrect), not #{etc} or #{etc}/open-wave (i.e., /usr/local/etc or /usr/local/etc/open-wave, which is correct). Since it's dumping quite a few files in etc, it would best to make it #{etc}/open-wave in this case.

```
system "make", "install", "pkgconfigdir=#{lib}/pkgconfig", "sysconfdir=#{etc}/open-wave"
```
will fix that.

**Comment by DomT4** [comment]
> Yeah, the problem is that install_name is not set so the example binary MinOZW gets linked with the path to the library at link time, which happens to be the buildpath in this case.

That is, er, quite something 👀. Nice spot, thanks.

**Comment by DomT4** [comment]
Test is failing:
```
==> ./test
�[31m2016-07-28 15:55:02.477 Error, Cannot find a path to the configuration files at . Exiting...
�[39m�[31m2016-07-28 15:55:02.478 Error, Exception: Options.cpp:91 - 1 - Cannot Find Configuration Files
�[39mError: Options.cpp:91 - Cannot Find Configuration Files
Error: open-zwave: failed
Failed executing: ./test 
```

**Comment by MikeMcQuaid** [comment]
Closing due to no response.

**Pull request closed without merging**
