### PR TITLE
at-spi2-core: update sha256

### PR DESCRIPTION
**Pull request by iMichka**
Upstream confirmed the retag.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Retag confirmed by @mgorse by email.

**Comment by tschoonj** [comment]
Wow that is scary... I have never seen that happen before with GNOME packages!

I think something went wrong as they just added [`at-spi2-core` 2.32.0](https://mail.gnome.org/archives/ftp-release-list/2019-March/msg00173.html).

I will open a PR for the new version later today, but in the meantime feel free to merge this one in.

**Review by tschoonj — APPROVED** [review]

**Comment by iMichka** [comment]
You mean, they added 2.31.92? I wanted to bump using that one, but brew told me it was a development version.

And yes, it is worrying that this happened on a gnome project.
I had a hard time contacting anyone at first, it is totally unclear from their readme and different bug tracker/mailing-lists who you should contact, so I contacted one of the latests committers ...
See https://github.com/Homebrew/linuxbrew-core/pull/11940#issuecomment-471176499

**Comment by tschoonj** [comment]
No I do mean 2.32.0, which was released just hours ago. 2.31.92 is indeed a development version, and we don't use those.

If you would like to open an issue about this, I recommend doing it [here](https://gitlab.gnome.org/GNOME/at-spi2-core/issues)

**Comment by iMichka** [comment]
Weird. I was on that issue tracker and could not find the project the first time I looked. Maybe a bug in the search field.

**Pull request closed without merging**
