### PR TITLE
pinocchio 2.6.19

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

closes #134062
closes #133537
relates to https://github.com/stack-of-tasks/pinocchio/issues/1995

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
Looks like there are no arm bottles with this PR.

**Comment by carlocab** [comment]
This is because `hpp-fcl` is also missing ARM bottles. Dispatched builds at https://github.com/Homebrew/homebrew-core/actions/runs/5314104675.

**Comment by carlocab** [comment]
Let's just merge this and then dispatch ARM bottles after #134172 and this are merged. This way we won't have to work out how to delete the uploaded bottles.

**Comment by chenrui333** [comment]
👍

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/5314364499

**Pull request merged**
