### PR TITLE
expat 2.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
### linux

```
brew test --retry --verbose citus
brew test --retry --verbose llvm
brew test --retry --verbose llvm@16
brew test --retry --verbose organize-tool
brew test --retry --verbose rpm2cpio
brew test --retry --verbose sigma-cli
brew test --retry --verbose temporal_tables
```

**Comment by chenrui333** [comment]
> brew test --retry --verbose organize-tool

```
==> Testing organize-tool
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/o/organize-tool.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/g/gcc@11.rb
==> /home/linuxbrew/.linuxbrew/Cellar/organize-tool/3.1.2/bin/organize sim /tmp/organize-tool-test-20240217-10768-gkc551/config.yaml
==> /home/linuxbrew/.linuxbrew/Cellar/organize-tool/3.1.2/bin/organize run /tmp/organize-tool-test-20240217-10768-gkc551/config.yaml
Config: "/tmp/organize-tool-test-20240217-10768-gkc551/config.yaml"

⚙ Rule #0 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/tmp/organize-tool-test-20240217-10768-gkc551
  ./homebrew.txt
    - (echo) Found: homebrew.txt
    - (delete) Deleting /tmp/organize-tool-test-20240217-10768-gkc551/homebrew.txt

success 1 / fail 0
```

passed the test

**Comment by chenrui333** [comment]
> brew test --retry --verbose citus
> brew test --retry --verbose temporal_tables

addressed per #163050

**Comment by chenrui333** [comment]
> brew test --retry --verbose llvm
> brew test --retry --verbose llvm@16

passed my regression check

```
runner@fv-az847-865:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ brew test llvm@16
==> Testing llvm@16
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/llvm-config --prefix
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/llvm-config --libs
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/llvm-config --libfiles
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang -L/home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/lib -fopenmp -nobuiltininc -I/home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/lib/clang/16/include omptest.c -o omptest
==> ./omptest
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang++ -v -std=c++11 test.cpp -o test++
==> ./test++
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang -v test.c -o test
==> ./test
==> /usr/bin/gcc-11 -v fake_ld.c -o bin/ld
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang -v test.c -o test_lld -fuse-ld=lld
==> ./test_lld
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang++ -v -isystem /home/linuxbrew/.linuxbrew/opt/llvm@16/include/c++/v1 -std=c++11 -stdlib=libc++ test.cpp -o testlibc++ -rtlib=compiler-rt -L/home/linuxbrew/.linuxbrew/opt/llvm
==> ./testlibc++
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang++ -v -o test_pie_runtimes -pie -fPIC test.cpp -L/home/linuxbrew/.linuxbrew/opt/llvm@16/lib -stdlib=libc++ -rtlib=compiler-rt -static-libstdc++ -lpthread -ldl
==> ./test_pie_runtimes
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang++ -v -o test_plugin.so -shared -fPIC test_plugin.cpp -L/home/linuxbrew/.linuxbrew/opt/llvm@16/lib -stdlib=libc++ -rtlib=compiler-rt -static-libstdc++ -lpthread -ldl
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang -v test_plugin_main.c -o test_plugin_libc++ test_plugin.so -Wl,-rpath=/tmp/llvmA16-test-20240217-21371-jylzrr -rtlib=compiler-rt
==> ./test_plugin_libc++
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/mlir-opt --split-input-file --verify-diagnostics test.mlir
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/scan-build make scanbuildtest 2>&1
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang-format -style=google clangformattest.c
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/clang --analyze -Xanalyzer -analyzer-constraints=z3 unreachable.c
==> python3.12 -c from clang import cindex
cindex.Config().get_cindex_library()
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/lldb --print-script-interpreter-info
==> python3.12 -c 'import pathlib, sys; print(pathlib.Path(sys.prefix).resolve())'
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/lldb
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.

now exiting InteractiveConsole...
==> /home/linuxbrew/.linuxbrew/Cellar/llvm@16/16.0.6/bin/llvm-config --system-libs

runner@fv-az847-865:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ brew test llvm
==> Testing llvm
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/llvm-config --prefix
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/llvm-config --libs
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/llvm-config --libfiles
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang -L/home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/lib -fopenmp -nobuiltininc -I/home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/lib/clang/17/include omptest.c -o omptest
==> ./omptest
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang++ -v -std=c++11 test.cpp -o test++
==> ./test++
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang -v test.c -o test
==> ./test
==> /usr/bin/gcc-11 -v fake_ld.c -o bin/ld
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang -v test.c -o test_lld -fuse-ld=lld
==> ./test_lld
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang++ -v -isystem /home/linuxbrew/.linuxbrew/opt/llvm/include/c++/v1 -std=c++11 -stdlib=libc++ test.cpp -o testlibc++ -rtlib=compiler-rt -L/home/linuxbrew/.linuxbrew/opt/llvm/lib
==> ./testlibc++
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang++ -v -o test_pie_runtimes -pie -fPIC test.cpp -L/home/linuxbrew/.linuxbrew/opt/llvm/lib -stdlib=libc++ -rtlib=compiler-rt -static-libstdc++ -lpthread -ldl
==> ./test_pie_runtimes
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang++ -v -o test_plugin.so -shared -fPIC test_plugin.cpp -L/home/linuxbrew/.linuxbrew/opt/llvm/lib -stdlib=libc++ -rtlib=compiler-rt -static-libstdc++ -lpthread -ldl
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang -v test_plugin_main.c -o test_plugin_libc++ test_plugin.so -Wl,-rpath=/tmp/llvm-test-20240217-21652-jgzur4 -rtlib=compiler-rt
==> ./test_plugin_libc++
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/mlir-opt --split-input-file --verify-diagnostics test.mlir
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/scan-build make scanbuildtest 2>&1
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang-format -style=google clangformattest.c
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/clang --analyze -Xanalyzer -analyzer-constraints=z3 unreachable.c
==> python3.12 -c from clang import cindex
cindex.Config().get_cindex_library()
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/lldb --print-script-interpreter-info
==> python3.12 -c 'import pathlib, sys; print(pathlib.Path(sys.prefix).resolve())'
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/lldb
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.

now exiting InteractiveConsole...
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/17.0.6_1/bin/llvm-config --system-libs
runner@fv-az847-865:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$
```

**Pull request merged**
