### PR TITLE
rstudio-server 1.1.383 (new formula)

### PR DESCRIPTION
**Pull request by randy3k**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

migrate `rstudio-server` from homebrew-science

### CODE REVIEW

**Comment by ilovezfs** [comment]
The resource blocks have prebuilt binaries. Everything in homebrew/core must build from source.

**Comment by randy3k** [comment]
I don't think there is an easy way to build all the resources from source. As homebrew-science is deprecating, is there any other options for `rstudio-server`?

**Comment by sjackman** [comment]
A number of those resources have a Homebrew formula. Could a dependency on the Homebrew formula be used instead? For example `gwt`, `chromedriver`, `pandoc`, and `pandoc-citeproc`.

**Comment by randy3k** [comment]
But it is likely that RStudio only works with specific versions of those dependencies, I am not sure if it worths the effort to try.

**Comment by randy3k** [comment]
switch back to homebrew-science as homebrew-core doesn't accept formula with binary resources.

I guess ultimately `rstudio-server` may need its own tap due to the complexity of formula.

https://github.com/Homebrew/homebrew-science/pull/6431

**Pull request closed without merging**
