### PR TITLE
postgresql@9.5 9.5.12

### PR DESCRIPTION
**Pull request by jjoos**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by tomdev** [comment]
I successfully installed postgres 9.5.12 using this change.

**Comment by commitay** [comment]
@jjoos Can you squash this down to one commit please?

**Comment by jjoos** [comment]
I squashed it, it seems that the CI fails randomly in half of the runs, but the previous version which was exactly the same succeeded.

**Comment by fxcoudert** [comment]
We have CI issues right now :(

@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @jjoos for the pull request!

**Pull request closed without merging**
