### PR TITLE
ghostscript 9.50

### PR DESCRIPTION
**Pull request by seisman**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failure for libspectre

09:14:19 ==> /usr/bin/clang test.c -o test -I/usr/local/Cellar/libspectre/0.2.8_8/include -L/usr/local/Cellar/libspectre/0.2.8_8/lib -lspectre
09:14:19 ==> ./test
09:14:19 dyld: Library not loaded: /usr/local/opt/ghostscript/lib/libgs.9.27.dylib
09:14:19   Referenced from: /usr/local/opt/libspectre/lib/libspectre.1.dylib
09:14:19   Reason: image not found
09:14:19 Error: libspectre: failed
09:14:19 Failed executing:

**Comment by seisman** [comment]
libspectre needs libgs.9.27.dylib but the new ghostscript provides libgs.9.50.dylib. Should it be a problem of libspectre?

**Comment by alebcay** [comment]
Maybe see if bumping the revision for `libspectre` will let it see the new `libgs.9.50.dylib` (bumping the revision will trigger a rebuild for `libspectre`). Otherwise (if the reliance on `libgs.9.27.dylib` is hardcoded into the `libspectre` build process somewhere), it would probably be best to wait for `libspectre` to update and support ghostscript 9.50 before merging this through.

**Comment by seisman** [comment]
@chenrui333 @alebcay After rebuilding libspectre, the builds pass now.

**Comment by chenrui333** [comment]
Nice. Merging this now.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
