### PR TITLE
cockroach 1.1.0

### PR DESCRIPTION
**Pull request by lgo**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Updating cockroach to the latest stable release.

### CODE REVIEW

**Comment by tamird** [comment]
Failures: `/bin/bash: autoconf: command not found`

1.1 depends on autoconf, but 1.0 didn't. paging @benesch

**Comment by lego** [comment]
Thanks Tamir, I didn't notice it was failing.

Added the dependency and fixed the test.

**Comment by ilovezfs** [comment]
A new dependency on autoconf when the build system already uses CMake is pretty strange. Do we know why this is the case? That smells like a bug.

**Comment by tamird** [comment]
It's not a bug; we internally depend on jemalloc, which uses autoconf.

**Comment by ilovezfs** [comment]
>we internally depend on jemalloc

In that case it should depend on the `jemalloc` formula rather than building it again.

**Comment by tamird** [comment]
We intentionally avoid depending on system-wide libraries. CockroachDB
internally builds several native dependencies and control over those build
systems (and software versions) is essential.

**Comment by ilovezfs** [comment]
>We intentionally avoid depending on system-wide libraries. CockroachDB internally builds several native dependencies and control over those build systems (and software versions) is essential.

In that case this software may not belong in Homebrew.

**Comment by tamird** [comment]
Are these requirements codified somewhere? This sounds like an ideological objection that will do little more than inconvenience Homebrew/CockroachDB users.

**Comment by ilovezfs** [comment]
@tamird you're welcome to read through our documentation, but referring to what I'm saying as "ideological" isn't going to advance your cause. Most importantly, we want to avoid situations where a library has a security vulnerability that is patched in the relevant formula but is not patched in a vendored submodule, which is much harder for us to monitor or detect, and is one of the reason we build everything with dynamic not static linkage whenever possible. I'm sorry that this was not noticed when the formula was originally added.

**Comment by benesch** [comment]
Concretely, Cockroach is incompatible with jemalloc 5.0 (see https://github.com/jemalloc/jemalloc/issues/956) and requires a patched version of RocksDB (https://github.com/facebook/rocksdb/compare/5.5.fb...cockroachdb:crl-release-5.5.1). We could theoretically dynamically link snappy and libprotobuf, given how stable those libraries are, but I'm not sure we want to officially support binaries that could be linking against arbitrary versions of shared libraries.

Still, CockroachDB is open source and we're going to run into this problem in other package managers sooner or later. Paging @bdarnell.

**Comment by bdarnell** [comment]
> jemalloc...RocksDB...snappy and libprotobuf

And that's just our C++ dependencies. We also embed dozens of Go packages in our vendor subtree (some of which are good about cross-version compatibility; others less so), and embed a pre-built version of our UI with its javascript dependencies. 

I appreciate the desire to dynamically link everything, but it's quite challenging in this case. We (Cockroach Labs) are committed to monitoring our dependencies and issuing security updates as needed. We'd strongly prefer that packagers of CockroachDB use our vendored source tree as much as possible instead of breaking everything out into shared libraries and potentially introducing issues like jemalloc/jemalloc#956. If that means we need to go back to our own tap instead of being packaged in homebrew-core, so be it.

**Comment by benesch** [comment]
There's precedent for statically linking Go dependencies in Homebrew, so that shouldn't be a problem. For example:  https://github.com/Homebrew/homebrew-core/blob/13d74c40bb6785aaa32d731afc90bcbf81bca642/Formula/mailhog.rb#L12-L110 If necessary, we could extract `go_resource` blocks automatically from the vendor submodule. (There's already a [tool for that](https://github.com/Homebrew/homebrew-dev-tools/blob/master/cmd/brew-go-resources.rb), in fact.)

@ilovezfs, sounds like it comes down to whether you trust us to issue timely security updates if a vulnerability is discovered in one of our statically-linked dependencies. Thoughts? Having bottles available in the main Homebrew repo has been a huge usability win for our users, so would love to work something out.

**Comment by ilovezfs** [comment]
In terms of Go, we do prefer everything to be vendored with one of the Go vendor systems, and that is actually a requirement for new formulae. Using `go_resource` blocks is a huge pain for us to maintain and we're not about to start having formulae for every single Go library under the sun.

However, it would be good if this formula didn't require a string replacement just to use our Go formula. Specifically I had to add this:
```
    # unpin the Go version
    go_version = Formula["go"].installed_version.to_s.split(".")[0, 2].join(".")
    inreplace "src/github.com/cockroachdb/cockroach/.go-version",
              /^GOVERS = go.*/, "GOVERS = go#{go_version.gsub(".", "\\.")}.*"
```
which is something I haven't had to do for any other formula that uses Go.

>embed a pre-built version of our UI with its javascript dependencies.

Can you elaborate on what that means (e.g., Is it vendoring a copy of node?)

>Still, CockroachDB is open source and we're going to run into this problem in other package managers sooner or later. Paging @bdarnell.

Yes, this is less a Homebrew thing, and more a package-managers-usually-expect-you-to-use-their-packages thing.

>We could theoretically dynamically link snappy and libprotobuf, given how stable those libraries are, but I'm not sure we want to officially support binaries that could be linking against arbitrary versions of shared libraries.

Yes it would be good if this used our snappy and protobuf formulae.

>requires a patched version of RocksDB

That is unfortunate but would be a good reason for using a vendored version. Ditto the situation with jemalloc.

>We'd strongly prefer that packagers of CockroachDB use our vendored source tree as much as possible instead of breaking everything out into shared libraries and potentially introducing issues like jemalloc/jemalloc#956.

This is not an uncommon sentiment but usually not warranted by the facts. Out of the 4,378 formulae in homebrew/core, we have less than forty non-versioned formulae (formulae with an `@` in their name) that actually have to depend on a versioned formula (excluding ones that we've voluntarily migrated to openssl@1.1).

I'm not opposed to vendoring a specific version when there is a known bug that cannot be readily fixed, but pre-vendoring everything to try to stave off bugs that haven't happened yet is not particularly consistent with the idea of package management and a good way to end up just delaying the discovery of such bugs.

**Comment by bdarnell** [comment]
> However, it would be good if this formula didn't require a string replacement just to use our Go formula. Specifically I had to add this:

You can avoid modifying this file by setting it on the command line: `make GOVERS='.*'`. But I agree that we are being overly prescriptive here and should change this to be a minimum requirement instead of a strict match.

> > embed a pre-built version of our UI with its javascript dependencies.
>
> Can you elaborate on what that means (e.g., Is it vendoring a copy of node?)

No, we're not vendoring node. We're just embedding our (compiled, minified) javascript bundle, base64-encoded in pkg/ui/embedded.go.

> This is not an uncommon sentiment but usually not warranted by the facts.

I respectfully disagree. Two of our four c++ dependencies have issues in their current versions that prevent upgrading (and we've seen others in the past - even when the current issues are resolved I wouldn't want to un-pin jemalloc or rocksdb to allow them to move to versions we haven't specifically qualified). We've earned this paranoia :) And the issues here are subtle: it's not "fails to build" or "crashes immediately on startup", it's "server uses twice as much memory as it should", or "data gets corrupted when restoring a backup produced by an older version". Discovering and diagnosing these issues is hard. It's not something a package integrator is generally equipped to do, and we don't have the resources to expand our testing coverage of different package versions. 

It's true that snappy and libprotobuf have had good track records with compatibility, so I'm not too worried about version differences causing trouble there. But linking them externally when the other half of our C++ dependencies and our much larger set of Go dependencies are all vendored would make them into the odd ones out in our build system. We don't have much interest at this time in changing our build to accommodate external linking of these two libraries.

Anyway, I think we've both made our positions clear, so it's time for a decision. Can we keep CockroachDB in homebrew-core (vendoring and all) or do we need to go back to our own tap?

**Comment by ilovezfs** [comment]
>even when the current issues are resolved I wouldn't want to un-pin jemalloc or rocksdb to allow them to move to versions we haven't specifically qualified

>We don't have much interest at this time in changing our build to accommodate external linking of these two libraries.

@bdarnell I hope you'll change your mind about this at some point, and I would not have signed off on the addition of this formula given the situation, but I'm not going to pull the rug out from under Homebrew users over it at this time. The next time an unpatched CVE arises, we'll need to reevaluate the situation, and I cannot promise cockroach won't be removed without much notice as a result.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @lego!

**Pull request closed without merging**
