### PR TITLE
open-completion 1.0.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> brew test open-completion --verbose
==> FAILED
Testing open-completion
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200310-59504-1idcuu7.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/open-completion.rb --verbose
==> source /usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open && complete -p open
/usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open: line 23: syntax error near unexpected token `<'
/usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open: line 23: `        while IFS=$'\n' read -r line; do COMPREPLY+=("$line"); done < <(IFS=$'\n' compgen -W "$applications" -- "$cur")'
Error: open-completion: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by chenrui333** [comment]
manually tested locally, seems ok
```
$ source /usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open && complete -p open
complete -o filenames -F _open open
```

**Comment by moshen** [comment]
https://github.com/Homebrew/homebrew-core/blob/b970895a6e9fa07bcc0e1f089ac758e733fc7550/Formula/open-completion.rb#L16 needs to be changed to force the test to run using `bash`.

**Comment by chenrui333** [comment]
@moshen Thanks for the direction, that is helpful!

**Pull request merged**
