### PR TITLE
terraform 0.11

### PR DESCRIPTION
**Pull request by jeichhorn**
- [/] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [/] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [/] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [/] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [/] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zbeekman** [comment]
Can you please elaborate on your need for this? I know 0.12 had some breaking changes but, from what I've heard, they have pretty thorough tools and documentation to help with the upgrade process.

Thanks!

**Comment by issyl0** [comment]
If this isn't accepted as a new formula, @jeichhorn, you can `brew install tfenv`, a Terraform version manager, and from there install any version you like. (In case you didn't know. :flushed:)

**Comment by jeichhorn** [comment]
@zbeekman: The reason of this formula is because of the breaking changes. The migration tools help in upgrading to 0.12, but there is still a lot of work todo until complex existing inventories work again.
Having the possibility to use the latest 0.11 makes it more convenient to upgrade to 0.12.

I was not aware of the tfenv tool @issyl0 suggested. This could also solve the problem, but I still would prefer to only have one terraform tool installed.

**Comment by zbeekman** [comment]
In that case I'm open to the idea. Can you please add a symlinink `terraform@0.12` that points to `../Formula/terraform.rb` in the [Aliases](https://github.com/Homebrew/homebrew-core/tree/master/Aliases) directory?

**Comment by sudoforge** [comment]
> Can you please elaborate on your need for this? I know 0.12 had some breaking changes but, from what I've heard, they have pretty thorough tools and documentation to help with the upgrade process.

In addition to the reasons described above... **yes**, Terraform 0.12 itself works and is great. The issue, however, is that 0.12 support across providers is still not consistent. Not having availability of pre-0.12.0 versions breaks the workflow for new users joining our team who have not yet installed Terraform.

We're currently solving this by having them manually install it. It would obviously be preferable to use Homebrew. What would be the best way for me to open a discussion regarding version retention?

**Comment by zbeekman** [comment]
> The issue, however, is that 0.12 support across providers is still not consistent.

:+1: Useful info!



> We're currently solving this by having them manually install it.

Oh no! Sorry for the delays! This seems completely reasonable, merging.

**Review by zbeekman — APPROVED** [review]
LGTM

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

CC: @chenrui333 b/c I know you were interested in this too

**Comment by chenrui333** [comment]
This is great!

**Pull request closed without merging**
