### PR TITLE
gox: fix test for M1

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Second attempt at #69452.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Sorry @carlocab I retriggered CI because I want to see if our new Apple M1 nodes are working fine ;)

**Comment by carlocab** [comment]
```
Current runner version: '2.276.1'
Runner name: 'bigsur-arm-1'
Runner group name: 'Default'
Machine name: 'HMBRW-A-001-M1-001'
```
Looks like a yes?

**Comment by fxcoudert** [comment]
I swear I feel it's even faster 🚀

**Comment by carlocab** [comment]
I think the last ARM run on the DTK definitely took longer, so it may not be your imagination

**Pull request closed without merging**
