### PR TITLE
curaengine 4.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
Bump the version

### CODE REVIEW

**Comment by chenrui333** [comment]
```
23:49:43 ==> make VERSION=4.5.0
23:49:43 make: *** No targets specified and no makefile found.  Stop.
```

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-livecheck/pull/487

**Comment by Ghostkeeper** [comment]
This fails because you're upgrading through 5 years of development. 5 years ago we switched to using CMake as the build tool. You'd need to adjust this to use CMake as well.

**Comment by chenrui333** [comment]
@Ghostkeeper thanks for the direction, I am going to change the steps and revive the formula.

**Comment by chenrui333** [comment]
Current diff:
```
 class Curaengine < Formula
   desc "C++ 3D printing GCode generator"
   homepage "https://github.com/Ultimaker/CuraEngine"
-  url "https://github.com/Ultimaker/CuraEngine/archive/15.04.6.tar.gz"
-  sha256 "4f2e3c5e74001b39cf5894a1e3f436a7724be0ae9ee30cd02bd2e3fd676ca4b1"
+  url "https://github.com/Ultimaker/CuraEngine/archive/4.5.0.tar.gz"
+  sha256 "c6e63526f860ef42950236333c8a33db9f5beb9493ac5c8b69f5336501f1179e"
+  # Looks like new version scheme was used for most recent releases since 15.04.6 in March 2016
+  # https://github.com/Ultimaker/CuraEngine/releases?after=2.6.1
+  version_scheme 1
   head "https://github.com/Ultimaker/CuraEngine.git"

   bottle do
@@ -13,9 +16,31 @@ class Curaengine < Formula
     sha256 "2f2c5d334057a9e99ef969f7f2cb66d357ab0c98e501a22103b4c53faa0ca8e8" => :sierra
   end

+  depends_on "cmake" => :build
+  depends_on "python" => :build
+  depends_on "protobuf"
+
+
+  resource "libArcus" do
+    url "https://github.com/Ultimaker/libArcus/archive/4.5.0.tar.gz"
+    sha256 "f29078901840d25f826cbaa6bdfa1f9d48b30e5e04674bc8a21e448fdcc58367"
+  end
+
   def install
-    system "make", "VERSION=#{version}"
-    bin.install "build/CuraEngine"
+    resource("libArcus").stage do
+      mkdir "build" do
+        system "cmake", "..", *std_cmake_args
+        system "make"
+        system "make", "install"
+      end
+    end
+
+    mkdir "build" do
+      system "cmake", "..", *std_cmake_args,
+                            "-DCMAKE_INSTALL_PREFIX=#{libexec}"
+      system "make"
+      system "make", "install"
+    end
   end
```

missing sip module when building `libArcus`

```
==> Downloading https://github.com/Ultimaker/libArcus/archive/4.5.0.tar.gz
Already downloaded: /Users/ruichen/Library/Caches/Homebrew/downloads/33003c99076388f5ddec4618d4bcf19300bb0775d4d00d34d62d756a798661ad--libArcus-4.5.0.tar.gz
==> cmake ..
Last 15 lines from /Users/ruichen/Library/Logs/Homebrew/curaengine/01.cmake:
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found suitable version "3.11.4", minimum required is "3.0.0")
-- Found Python3: /usr/bin/python3 (found suitable version "3.7.3", minimum required is "3.4") found components: Interpreter Development
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sip'
CMake Error at /usr/local/Cellar/cmake/3.17.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find SIP (missing: SIP_EXECUTABLE SIP_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSIP.cmake:91 (find_package_handle_standard_args)
  CMakeLists.txt:38 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/curaengine--libArcus-20200401-5839-ho1pug/libArcus-4.5.0/build/CMakeFiles/CMakeOutput.log".

READ THIS: https://docs.brew.sh/Troubleshooting
```

When check out this weekend on this.

**Comment by Ghostkeeper** [comment]
If you set `ENABLE_ARCUS` to `OFF` in CMake you won't be able to connect to CuraEngine via a local socket as a background process. However if you only use command line slicing it makes it easier to compile CuraEngine.

**Pull request closed without merging**
