### PR TITLE
terragrunt 0.21.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
==> go build -o /usr/local/Cellar/terragrunt/0.20.5/bin/terragrunt -ldflags -X main.VERSION=v0.20.5
remote/remote_state_gcs.go:17:2: cannot find package "github.com/hashicorp/terraform/helper/pathorcontents" in any of:
	/private/tmp/terragrunt-20191019-67078-h49isr/src/github.com/gruntwork-io/terragrunt/vendor/github.com/hashicorp/terraform/helper/pathorcontents (vendor tree)
	/usr/local/Cellar/go/1.13.1/libexec/src/github.com/hashicorp/terraform/helper/pathorcontents (from $GOROOT)
	/private/tmp/terragrunt-20191019-67078-h49isr/src/github.com/hashicorp/terraform/helper/pathorcontents (from $GOPATH)
```

**Comment by chenrui333** [comment]
circle back on this now.

**Comment by chenrui333** [comment]
Submitted an upstream issue, the reason why it failed to do the upgrade is because terraform 0.12.12 is using the `github.com/hashicorp/hcl/v2` which requires go modules for the build, however the latest terrragrunt does not use `go modules` though.

**Comment by chenrui333** [comment]
Upgrade to `terragrunt v0.21.0 `

**Comment by chenrui333** [comment]
11:28:20 ==> dep ensure -vendor-only
11:28:20 ==> go build -o /usr/local/Cellar/terragrunt/0.21.0/bin/terragrunt -ldflags -X main.VERSION=v0.21.0
11:28:20 remote/remote_state_gcs.go:17:2: cannot find package "github.com/hashicorp/terraform/helper/pathorcontents" in any of:
11:28:20 	/private/tmp/terragrunt-20191024-95902-1gr2b3j/src/github.com/gruntwork-io/terragrunt/vendor/github.com/hashicorp/terraform/helper/pathorcontents (vendor tree)
11:28:20 	/usr/local/Cellar/go/1.13.3/libexec/src/github.com/hashicorp/terraform/helper/pathorcontents (from $GOROOT)
11:28:20 	/private/tmp/terragrunt-20191024-95902-1gr2b3j/src/github.com/hashicorp/terraform/helper/pathorcontents (from $GOPATH)
11:28:20

**Comment by chenrui333** [comment]
Fixed the build issue and passed the build locally.

**Comment by chenrui333** [comment]
Closed in favor of new PR, https://github.com/Homebrew/homebrew-core/pull/45837

**Pull request closed without merging**
