### PR TITLE
singular 4.3.0

### PR DESCRIPTION
**Pull request by slel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by slel** [comment]
Help wanted.

**Comment by slel** [comment]
Can we retry? The only CI complaint is that

> The homepage URL https://www.singular.uni-kl.de/ is not reachable

That page may have been temporary down, but I can access it now.

**Comment by dimpase** [comment]
@hannes14  - it seems that https://www.singular.uni-kl.de/ is still down.

**Comment by slel** [comment]
There might be a way to use a different url as was done at

- https://github.com/Macaulay2/homebrew-tap/issues/134
- https://github.com/Macaulay2/homebrew-tap/issues/135

**Review by SMillerDev — APPROVED** [review]

**Comment by slel** [comment]
Seems we have mostly green lights.
Should we instead use 4.3.0p1 though?

**Comment by slel** [comment]
I'm stuck here. Hopefully someone can take over.

In the file `Formula/singular.rb`, I can change the url to
`https://www.singular.uni-kl.de/ftp/pub/Math/Singular/src/4-3-0/singular-4.3.0.tar.gz`
and the sha256 to
`9ecf2228c9238d23456b8ffbe60b1b8d20f6f45b36e7af0ab2945e80d7c86e9b`
but should the other sha256 in `bottle do` be changed too?

Or should one start `brew bump-formula-pr` from scratch
for 4.3.0p1? I tried that too, but it seemed to have trouble
detecting `4.3.0p1` as a version number.

**Comment by cho-m** [comment]
Looks like 4.3.0 was merged in #104053, so I'll close this as superseded.

If you want to update to `4.3.0p1`, you can use `brew bump-formula-pr` but probably need to set `--url` and `--version` since Homebrew's logic doesn't work with that version format.

This formula probably needs a `livecheck` to detect patch releases.

**Comment by slel** [comment]
> Looks like 4.3.0 was merged in #104053, so I'll close this as superseded.
> 
> If you want to update to `4.3.0p1`, you can use `brew bump-formula-pr`
> but probably need to set `--url` and `--version` since Homebrew's logic
> doesn't work with that version format.

Thanks for the tip. See #104604 for the upgrade to Singular 4.3.0p1.
 
> This formula probably needs a `livecheck` to detect patch releases.

Don't know what that is, sorry.

**Comment by dimpase** [comment]
https://docs.brew.sh/Brew-Livecheck

**Pull request closed without merging**
