### PR TITLE
protobuf 3.19.1

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
[The removal of `SetTotalBytesLimit` with two arguments](https://github.com/protocolbuffers/protobuf/pull/8794) is one of the main build failure culprit. The upstream change for all those projects is quite simple: remove the second argument of the call, it was ignored anyway until now.

**Comment by Moisan** [comment]
`opencv` issue has been fixed upstream and should be in the next release: https://github.com/opencv/opencv/pull/20386

**Comment by nipunn1313** [comment]
> [The removal of `SetTotalBytesLimit` with two arguments](https://github.com/protocolbuffers/protobuf/pull/8794) is one of the main build failure culprit. The upstream change for all those projects is quite simple: remove the second argument of the call, it was ignored anyway until now.

Can we accelerate this PR by changing dependencies of broken upstream formulas from `protobuf` to `protobuf@3.17.3` until the upstreams fix themselves (eg zbackup)? It seems unwise to wait on all these upstreams in the PR. As the individual upstreams fix themselves, they can switch back.

**Comment by SMillerDev** [comment]
The best option is to make upstream pull requests, the second best is upstream issues. If upstream says they won't fix it we can always switch to an older protobuf, but that should be a last resort.

**Comment by nipunn1313** [comment]
Making PRs to update the upstreams makes sense to me - but it also seems like having a tree of blockers on other projects like this will cause delays in making protobuf 3.18.0 available to folks (eg it's already been 2 weeks). To me - these delays seem unnecessary. For example - we can invert the sequencing and release protobuf 3.18.0 and fix the upstreams w/ PRs to follow.

I'm here to learn - so please let me know if there's some hole in my reasoning or something I'm not considering that's important here.

**Comment by SMillerDev** [comment]
History has taught us that if we point projects to older versions of dependencies, we are then stuck with the older version forever. I don't think I've ever seen a PR by someone who went to upstream to fix compatibility with newer versions if they weren't somehow forced to.

For reference you can read the discussions in the PRs about Go 1.17, Go 1.16, Go 1.15 and probably every Go version since Homebrew started packaging Go.

**Comment by Moisan** [comment]
`shogun` doesn't currently build on master and the issue has been known for more than a year upstream: https://github.com/shogun-toolbox/shogun/issues/4870

**Comment by nipunn1313** [comment]
For zbackup - there's a PR here to fix https://github.com/zbackup/zbackup/pull/158 and https://github.com/zbackup/zbackup/pull/159. It appears zbackup doesn't build on mac off of master (`/Users/nipunn/src/zbackup/buse.c:23:10: fatal error: 'linux/types.h' file not found
`), but does build off the stable branch. Also I noted that there haven't been commits in 5 years.

**Comment by cclauss** [comment]
This branch has conflicts that must be resolved.

**Comment by cclauss** [comment]
Can zbackup be removed?  https://github.com/Homebrew/homebrew-core/blob/master/Formula/zbackup.rb#L19

**Comment by carlocab** [comment]
I am merging #87287; this will need rebasing after.

**Comment by carlocab** [comment]
> Can `zbackup` be removed? https://github.com/Homebrew/homebrew-core/blob/master/Formula/zbackup.rb#L19

Why?

> Please add the [`python-3.10-migration` label](https://github.com/Homebrew/homebrew-core/labels/python-3.10-migration) to this PR because it is blocking:
> 
> * [protobuf: build python bindings for 3.10 too #87287](https://github.com/Homebrew/homebrew-core/pull/87287)

But this isn't blocking #87287.

**Comment by iMichka** [comment]
Rebased again. I disabled `zbackup`. It does not build and we can't rev-bump it. It has been deprecated for over a month now.

**Comment by iMichka** [comment]
Rebased. I added patches for `mitmproxy` and disabled `zbackup`. I also added a few more missing rev bumps.

**Comment by thibault-ml** [comment]
That's great! Are there any other dependencies blocking this now? If so, how can anyone else?

**Comment by iMichka** [comment]
We got at least one green build!

`percona-server` fails to build on 12-arm64 now:

```
2021-12-20T21:29:29.4966130Z /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -std=c++14 -fno-omit-frame-pointer -ftls-model=initial-exec  -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Woverloaded-virtual -Wcast-qual -Wno-null-conversion -Wno-unused-private-field -Wconditional-uninitialized -Wdeprecated -Wextra-semi -Wheader-hygiene -Wnon-virtual-dtor -Wundefined-reinterpret-cast -Winconsistent-missing-destructor-override -Winconsistent-missing-override -Wshadow-field -DNDEBUG -D_FORTIFY_SOURCE=2 -ffunction-sections -fdata-sections -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -bundle -Wl,-headerpad_max_install_names -o ../../plugin_output_directory/rewrite_example.so CMakeFiles/rewrite_example.dir/rewrite_example.cc.o  ../../libservices/libmysqlservices.a -Wl,-bundle_loader,/tmp/percona-server-20211220-11565-12w3ev6/percona-server-8.0.25-15/runtime_output_directory/mysqld 
2021-12-20T21:29:29.4971810Z /tmp/percona-server-20211220-11565-12w3ev6/percona-server-8.0.25-15/plugin/data_masking/src/udf/udf_utils.cc:189:8: error: unknown type name 'uint'; did you mean 'int'?
2021-12-20T21:29:29.4973040Z   for (uint index = 0; index < args->arg_count; ++index) {
2021-12-20T21:29:29.4973380Z        ^~~~
2021-12-20T21:29:29.4973610Z        int
2021-12-20T21:29:29.4975300Z cd /tmp/percona-server-20211220-11565-12w3ev6/percona-server-8.0.25-15/plugin/rewrite_example && install_name_tool -change libcrypto.1.1.dylib @loader_path/libcrypto.1.1.dylib /tmp/percona-server-20211220-11565-12w3ev6/percona-server-8.0.25-15/plugin_output_directory/rewrite_example.so
2021-12-20T21:29:29.4976950Z 1 error generated.
2021-12-20T21:29:29.4977540Z make[2]: *** [plugin/data_masking/CMakeFiles/data_masking.dir/src/udf/udf_utils.cc.o] Error 1
2021-12-20T21:29:29.4979420Z cd /tmp/percona-server-20211220-11565-12w3ev6/percona-server-8.0.25-15/plugin/rewrite_example && install_name_tool -change libssl.1.1.dylib @loader_path/libssl.1.1.dylib /tmp/percona-server-20211220-11565-12w3ev6/percona-server-8.0.25-15/plugin_output_directory/rewrite_example.so
2021-12-20T21:29:29.4981140Z make[1]: *** [plugin/data_masking/CMakeFiles/data_masking.dir/all] Error 2
2021-12-20T21:29:29.4981670Z make[1]: *** Waiting for unfinished jobs....
```

**Comment by thibault-ml** [comment]
Looks like it's failing on macOS 12 only, and for something unrelated to protobuf. I tried to look at Percona's Jira to see if they are aware of the issue but I cannot find a specific ticket for it (the Jira search seems not to be working for me).

It looks like they're building with macOS 15 though, so not sure why the issue is there:
https://github.com/percona/percona-server/pull/4563

Quick question because I am a noob: I see [in their pipeline](https://github.com/percona/percona-server/blob/8.0/azure-pipelines.yml) they require the following:
```
         brew update
         brew install ccache protobuf lz4 re2 rapidjson openssl@1.1
```

But these dependencies do not match what we have in the formula. Is that on purpose?

**Comment by carlocab** [comment]
`percona-server` has no bottle for the versions it failed on, so the related failures are pre-existing.

**Review by carlocab — DISMISSED** [review]
Linux failures have really low usage statistics (single-digit monthly installs), so I suggest we fix those separately to avoid complicating this PR further (with, e.g., merge conflicts from waiting too long to merge this).

**Review by iMichka — DISMISSED** [review]

**Comment by iMichka** [comment]
Yes, let's merge this. I'll have a look at the other issues.

**Comment by iMichka** [comment]
> Error: Bottles are for libpulsar 2.9.0_1 but formula is version 2.9.1_1!

**Comment by iMichka** [comment]
`libpulsar` got an update. We will need to rebase I guess? If so, please add a rev bump to `sysdig` for Linux.

**Comment by iMichka** [comment]
Let's re-run this, `grpc` got an update too ... I'll try to merge this tomorrow morning.

**Comment by carlocab** [comment]
Oops, I guess we did wait too long. Let's merge it ASAP when CI finishes (assuming no new failures).

**Comment by carlocab** [comment]
Fixed the alias (it was still named `protobuf@3.18`) and added `bear` and `mavsdk`.

**Review by carlocab — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Done. I'll check what is going on with `qt-percona-server` and `percona-xtrabackup` later today.

**Comment by thibault-ml** [comment]
Thanks all! Appreciate the effort of all involved!

**Pull request closed without merging**
