### PR TITLE
go 1.23.0, go@1.22 1.22.6 (new formula)

### PR DESCRIPTION
**Pull request by stefanb**
Announcements: 
* rc1: https://groups.google.com/g/golang-announce/c/8ciOP5ve_CM
* rc2: https://groups.google.com/g/golang-announce/c/jW315Nz132s
* Final: https://groups.google.com/g/golang-announce/c/RQjbRNOcV74

Release notes: https://go.dev/doc/go1.23

Go 1.23 milestone: [GitHub milestone details](https://github.com/golang/go/milestone/212)

Go 1.23 release dashboard: https://dev.golang.org/release

Downloads: https://go.dev/dl/

Related previous: 
* Major release: https://github.com/Homebrew/homebrew-core/pull/157782
* New legacy formula: https://github.com/Homebrew/homebrew-core/pull/162713

Build logs:
* rc1: https://github.com/Homebrew/homebrew-core/actions/runs/9617673150?pr=175310
* rc2: https://github.com/Homebrew/homebrew-core/actions/runs/9960334403?pr=175310
* rc2 + go@1.22 1.22.5: https://github.com/Homebrew/homebrew-core/actions/runs/10045313744?pr=175310
* rc2 + go@1.22 1.22.6: https://github.com/Homebrew/homebrew-core/actions/runs/10298474265?pr=175310
* 1.23.0 & 1.22.6: https://github.com/Homebrew/homebrew-core/actions/runs/10375471363?pr=175310

----

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by p-linnane** [comment]
@stefanb Let me know when you want the `no-fail-fast` label here.

**Comment by stefanb** [comment]
@p-linnane, please add the `no-fail-fast` label, or whatever is needed to not abort the builds after the first failure. 
Perhaps also `long build` (or something similar) label will be needed.
Thanks!

**Comment by chenrui333** [comment]
need to have long build jobs for deps (cancelled and re-ran)

**Comment by stefanb** [comment]
I am not sure that formula dependants check is actually running, as there is no more output from the jobs.

**Comment by stefanb** [comment]
Not sure what to do with [frugal](https://formulae.brew.sh/formula/frugal), which failed to build with [error](https://github.com/Homebrew/homebrew-core/actions/runs/9617673150/job/26535459459?pr=175310#step:3:7720):
````
  ==> Downloading https://github.com/Workiva/frugal/archive/refs/tags/v3.17.13.tar.gz
  curl: (22) The requested URL returned error: 404
````
The original repository https://github.com/Workiva/frugal is gone, but it wasn't simply renamed, in case of which github would take care of redirects, but a new repository https://github.com/Workiva/frugal-public was created with NO tags, so we cant just point the formula there and the new repository doesn't accepts issues, so we can't ask them there about such weird renaming process.

**Comment by SMillerDev** [comment]
I'd disable frugal with `:repo_removed`

**Comment by blacktop** [comment]
https://twitter.com/golang/status/1823404920583663807

Go 1.23.0 released 🎉

**Comment by bstncartwright** [comment]
Just wanna give a big shoutout to you @stefanb for all your hard work on this! 🤘 Thank you!

**Review by carlocab — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by TristanSpeakEasy** [comment]
what are causing the failures here in the CI? Something that needs to be addressed in this PR?

**Comment by stefanb** [comment]
@TristanSpeakEasy so far it seems that most of the failures can be tackled in follow-up PRs after this is merged.

Some formulae are not yet compatible with Go 1.23 and will need to be pinned to 1.22 until they are compatible.

Some formulae have hash mismatches or have some other problems that should be investigated.

**Comment by mprimeaux** [comment]
Hi all. Just catching up on this PR and related comments. What is the expected time frame for this PR to be merged?  I am ready to help with any remaining testing, documentation, code, or related tasks. Sincerely appreciate the insight.

**Comment by stefanb** [comment]
Relevant discussion:
https://github.com/orgs/Homebrew/discussions/2618

**Comment by stefanb** [comment]
Follow-ups needed based on [build logs](https://github.com/Homebrew/homebrew-core/actions/runs/10375471363?pr=175310):

Incompatible with Go 1.23 (pin to Go 1.22 unless upstreams have releases compatible version in the mean time)
* [ ] aliyunpan
* [ ] baidupcs-go
* [ ] bigquery-emulator
* [ ] cloudpan189-go
* [ ] grafana
* [ ] grafana-agent
* [ ] hof
* [ ] influxdb@1
* [ ] juicefs
* [ ] kuttl
* [ ] logcli
* [ ] loki
* [ ] mimirtool
* [ ] neosync
* [ ] nexttrace
* [ ] pcp
* [ ] promtail
* [ ] pulumi
* [ ] rdb
* [ ] serf
* [ ] teleport
* [ ] vitess
* [ ] zoro

Checksum changed:
* [ ] https://github.com/Homebrew/homebrew-core/pull/181402
* [ ] meek
* [ ] wireguard-go
* [ ] zrok

Other:
* [ ] cortex
* [ ] dissent
* [ ] func-e
* [ ] garble
* [ ] govulncheck
* [ ] imgproxy
* [ ] kapacitor
* [ ] llgo
* [ ] logdy
* [ ] navidrome
* [ ] operator-sdk
* [ ] podsync
* [ ] staticcheck
* [ ] twty
* [ ] vhs

**Pull request merged**
