### PR TITLE
haskell-language-server 1.5.1

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fishtreesugar** [comment]
@SMillerDev @carlocab pls add `CI-long-timeout` label

**Comment by carlocab** [comment]
I've cancelled CI for now, since there are still a few long-running jobs going. We can restart it when they're done.

**Comment by carlocab** [comment]
Big Sur ARM has been going at it for a while now. I wonder if it's stuck.

**Review by carlocab — APPROVED** [review]
Ok, not stuck. Just slow.

**Pull request closed without merging**
