### PR TITLE
buf 1.10.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bufdev** [comment]
@p-linnane this should be reverted - the Buf team maintains its own tap at https://github.com/bufbuild/homebrew-buf, which is what we've documented and told all of our customers, and also fits into our release strategy (it is significantly easier for us to upgrade the version of `buf` from there). We can't maintain this in homebrew core - can you revert or should we put up a revert PR?

**Comment by bufdev** [comment]
I've put up https://github.com/Homebrew/homebrew-core/pull/118255 to revert this addition.

**Comment by p-linnane** [comment]
@bufdev Our policy is to not remove software from `homebrew-core` in favor of an upstream or "official" tap. You can read more here: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#official-vendor-taps

**Comment by chenrui333** [comment]
> @p-linnane this should be reverted - the Buf team maintains its own tap at https://github.com/bufbuild/homebrew-buf, which is what we've documented and told all of our customers, and also fits into our release strategy (it is significantly easier for us to upgrade the version of `buf` from there). We can't maintain this in homebrew core - can you revert or should we put up a revert PR?

We are not asking you to maintain the core tap, and inclusion the formula into the core would help developing core tap ecosystem as well as helping tool adoption in general. You can continue maintaining the custom tap, and we can help maintaining the core tap

**Comment by bufdev** [comment]
That seems strictly worse for end OSS users, as there's now two ways to do things, and the core formula will always be out-of-date relative to the tap we maintain as we update our tap immediately on every release (and won't be doing the same here). This saddens me as a longtime Homebrew fan.

**Comment by chenrui333** [comment]
> That seems strictly worse for end OSS users, as there's now two ways to do things, and the core formula will always be out-of-date relative to the tap we maintain as we update our tap immediately on every release (and won't be doing the same here). This saddens me as a longtime Homebrew fan.

You can easily add this action into the release pipeline, and there are so many repos doing the same.

**Comment by bufdev** [comment]
We won't be doing so - we don't have time to commit to changing our Homebrew release process, and we rather the documented way to install Buf always be up to date (which, given that we don't have merge access on homebrew-core obviously, is not possible in homebrew-core). The formula in homebrew-core will not be maintained by the Buf team.

In my view, he above policy strictly harms OSS users in these cases. However, I am not a maintainer of homebrew-core, and it is obviously not my decision (which is a good thing), and understand there are competing points of view.

**Comment by chenrui333** [comment]
just to note for future reference, everyone is allowed to ship custom tap, including homebrew-core. I mean everyone.

**Pull request closed without merging**
