### PR TITLE
Use gobject-introspection as build time dependency wherever possible

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Review by ilovezfs — COMMENTED** [review]
the libgee commit and bottle should be left out while pulling

**Comment by ilovezfs** [comment]
🍥

**Comment by tschoonj** [comment]
Thx. Do I revbump all formulas that depend on libgee in my new PR as well? They have been rebuilt with a runtime dependency on gobject introspection through libgee?

**Comment by ilovezfs** [comment]
yes

**Pull request closed without merging**
