### PR TITLE
monkeysphere: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by chenrui333**
See #134251.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  RSA.xs:647:22: error: ‘RSA_SSLV23_PADDING’ undeclared (first use in this function); did you mean ‘RSA_NO_PADDING’?
    647 |     p_rsa->padding = RSA_SSLV23_PADDING;
        |                      ^~~~~~~~~~~~~~~~~~
        |                      RSA_NO_PADDING
  RSA.xs:647:22: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by cho-m** [comment]
Probably need to update resources.

**Comment by cho-m** [comment]
On ARM:
```
  ==> /opt/homebrew/Cellar/monkeysphere/0.44_6/bin/openpgp2pem --help 2>&1
  sh: line 1: 10910 Abort trap: 6           /opt/homebrew/Cellar/monkeysphere/0.44_6/bin/openpgp2pem --help 2>&1
  Error: monkeysphere: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /We\ need\ at\ least/ to match "dyld[10910]: missing symbol called\n".
```

**Comment by cho-m** [comment]
Probably issue linking to OpenSSL.

Can either add `pkg-config` as build dependency or manually set `OPENSSL_PREFIX`.

**Comment by chenrui333** [comment]
> Probably issue linking to OpenSSL.
> 
> Can either add `pkg-config` as build dependency or manually set `OPENSSL_PREFIX`.

yeah, we can try `pkg-config` route

**Review by carlocab — APPROVED** [review]

**Pull request merged**
