### PR TITLE
texlab 3.0.0

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Test fails on ARM. Might be from this:

https://github.com/Homebrew/homebrew-core/blob/952ee83354c264b55eb4f8b351199e3d4fbe365f/Formula/texlab.rb#L35-L37

**Comment by clason** [comment]
Hmm. I did not change that part; so this should still be working. I also don't know enough about the test setup. Should I just remove it?

**Comment by clason** [comment]
No, they all fail; it seems I have to change the test input.

**Comment by carlocab** [comment]
Try emulating the `clojure-lsp` test. Running multiple processes in a `test` block is usually a headache.

**Comment by clason** [comment]
Actually, `rust-analyzer` is the better formula to ~~steal from~~ be inspired by. (Texlab switched to using that as a basis.)

**Comment by clason** [comment]
(I can include the license update while I'm at it?)

**Comment by carlocab** [comment]
> (I can include the license update while I'm at it?)

Go ahead.

**Comment by clason** [comment]
...and all green now \o/

**Review by carlocab — APPROVED** [review]
🎉 

Thanks @clason!

**Pull request closed without merging**
