### PR TITLE
zssh: update license to `GPL2.0-only`

### PR DESCRIPTION
**Pull request by shivansh-13**
…udit

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Where did you find this info? I can't seem to find it anywhere in the source

**Comment by shivansh-13** [comment]
> Where did you find this info? I can't seem to find it anywhere in the source

Well, I checked in chatGPT first, so changed it to 2-or-later, but after your comment, I changed it back to 2-only as even I could not find it explicitly mentioned anywhere in some documentation.
Thanks

**Comment by SMillerDev** [comment]
But what does the project license conditions say? Unless ChatGPT became a lawyer it can't determine that.

**Comment by shivansh-13** [comment]
> But what does the project license conditions say? Unless ChatGPT became a lawyer it can't determine that.

Yes 😅
I've found it is GPLv2 only, according to the original documentation. [https://sourceforge.net/projects/zssh/](url)
Thanks for teaching.

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
