### PR TITLE
libuv 1.21.0

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
`uv-version.h` is now `uv/version.h` so it'll need to be fixed in libwebsockets

**Comment by DomT4** [comment]
https://github.com/warmcat/libwebsockets/pull/1316

**Comment by ilovezfs** [comment]
I guess no inreplace needed if we use the final commits?

**Comment by DomT4** [comment]
Checked already; Unhelpfully refuses to apply cleanly.

**Comment by ilovezfs** [comment]
Also we cannot use the PR url anymore because you deleted your fork and GitHub has a bug where the PR url because unusable even though the commit is still visible in the GUI.

**Comment by DomT4** [comment]
Terrific. I’ll just submit a patch to Homebrew’s formula patches repo shortly to handle that & the inreplace.

**Comment by ilovezfs** [comment]
thanks

**Comment by ilovezfs** [comment]
FWIW I just sent GitHub support a bug report about this since it keeps coming up.

**Comment by DomT4** [comment]
Thanks for that. Will be in with a PR to patches soon; had to grab some sleep & whatnot.

**Comment by DomT4** [comment]
https://github.com/Homebrew/formula-patches/pull/247

**Comment by DomT4** [comment]
As long as CI is content we should be good here finally.

**Comment by ilovezfs** [comment]
Thanks @DomT4!

**Comment by DomT4** [comment]
Thanks Joe. Next thing on my list is taking another look at my `HOME` PR on the `brew` side 😅.

**Pull request closed without merging**
