### PR TITLE
node 13.10.1

### PR DESCRIPTION
**Pull request by mistydemeo**
Created with `brew bump-formula-pr`.

Closes #50437.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like the 13.10.0 tarball is also broken.

**Comment by Bo98** [comment]
Yikes.

**Review by chenrui333 — APPROVED** [review]
💯

**Comment by Bo98** [comment]
`ungit` is a pre-existing test failure. Need to track that down at some point.

**Pull request closed without merging**
