### PR TITLE
scrcpy 1.9

### PR DESCRIPTION
**Pull request by rom1v**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

After [v1.8](https://github.com/Homebrew/homebrew-core/pull/37715), here is v1.9.

### CODE REVIEW

**Comment by rom1v** [comment]
Oops, something is probably wrong. Please wait (don't merge it now).

**Comment by rom1v** [comment]
I just updated the PR, because the default value for a meson option flag was wrong: https://github.com/Homebrew/homebrew-core/pull/40909/commits/1e24ef4c3f1587f2ef625a8f4799ca7e5af411a4

I have no Mac to test, so please test everything works correctly before merging :wink:
Thank you.

**Comment by schwabe** [comment]
This does not work. You need to add include the patch to make this actually build.

**Comment by rom1v** [comment]
> This does not work.

:disappointed: 

What is the problem?

> You need to add include the patch to make this actually build.

Which patch? Even if the default value is `true`, I set `-Dportable=false` in this PR, so it should work. If it does not, there is probably another problem.

**Comment by schwabe** [comment]
I added a PR with the  the commit that fixes building portable as patch as PR #40918. That one builds and works on my mac.

**Comment by rom1v** [comment]
@schwabe Ah yes, thank you :+1:

**Comment by rom1v** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/40918.

**Pull request closed without merging**
