### PR TITLE
netcdf 4.8.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by Bo98** [comment]
I think `hdf5@1.10` is sufficient for this case.

**Comment by carlocab** [comment]
Switching `netcdf` to `hdf5@1.10` looks like it's going to be a lot of work.

**Comment by chenrui333** [comment]
what I think we can do is either rebuild `hdf5` formula with `with-default-api-version=v18` or have its own version of `hdf5` in here.

**Comment by carlocab** [comment]
> what I think we can do is either rebuild `hdf5` formula with `with-default-api-version=v18`

I'm wary about doing this, since this could break the API for its current users.

> or have its own version of `hdf5` in here.

That just dodges the mixed-version dependency audit. We really shouldn't have `netcdf` have its own vendored `hdf5` that isn't used by all its dependents.

**Comment by carlocab** [comment]
MacPorts configure `hdf5` with `--with-default-api-version=v110`. I suppose it might not hurt to follow them here.

**Comment by carlocab** [comment]
ARM:

```
Error: 16 failed steps!
brew linkage --test field3d
brew test --retry --verbose field3d
brew linkage --test cdo
brew test --retry --verbose cdo
brew linkage --test eccodes
brew linkage --test f3d
brew test --retry --verbose f3d
brew linkage --test gdal
brew test --retry --verbose gdal
brew linkage --test gdcm
brew linkage --test ncview
brew test --retry --verbose ncview
brew test --retry --verbose pdal
brew test --retry --verbose simple-tiles
brew linkage --test vtk
brew test --retry --verbose vtk
```

Big Sur:

```
Error: 23 failed steps!
brew linkage --test cdo
brew test --retry --verbose cdo
brew linkage --test eccodes
brew linkage --test f3d
brew test --retry --verbose f3d
brew linkage --test gdal
brew test --retry --verbose gdal
brew linkage --test gdcm
brew linkage --test gmt
brew test --retry --verbose gmt
brew linkage --test gmt@5
brew test --retry --verbose gmt@5
brew test --retry --verbose mapserver
brew linkage --test nco
brew test --retry --verbose nco
brew linkage --test ncview
brew test --retry --verbose ncview
brew test --retry --verbose osmcoastline
brew test --retry --verbose pdal
brew test --retry --verbose points2grid
brew test --retry --verbose simple-tiles
brew linkage --test vtk
brew test --retry --verbose vtk
```

Catalina:

```
Error: 23 failed steps!
brew linkage --test cdo
brew test --retry --verbose cdo
brew linkage --test eccodes
brew linkage --test f3d
brew test --retry --verbose f3d
brew linkage --test gdal
brew test --retry --verbose gdal
brew linkage --test gdcm
brew linkage --test gmt
brew test --retry --verbose gmt
brew linkage --test gmt@5
brew test --retry --verbose gmt@5
brew test --retry --verbose mapserver
brew linkage --test nco
brew test --retry --verbose nco
brew linkage --test ncview
brew test --retry --verbose ncview
brew test --retry --verbose osmcoastline
brew test --retry --verbose pdal
brew test --retry --verbose points2grid
brew test --retry --verbose simple-tiles
brew linkage --test vtk
brew test --retry --verbose vtk
```

Mojave:

```
Error: 29 failed steps!
brew install --only-dependencies dynare
brew install dynare
brew linkage --test field3d
brew test --retry --verbose field3d
brew install --only-dependencies octave
brew install octave
brew linkage --test cdo
brew test --retry --verbose cdo
brew linkage --test eccodes
brew linkage --test f3d
brew test --retry --verbose f3d
brew linkage --test gdal
brew test --retry --verbose gdal
brew linkage --test gdcm
brew linkage --test gmt
brew test --retry --verbose gmt
brew linkage --test gmt@5
brew test --retry --verbose gmt@5
brew test --retry --verbose mapserver
brew linkage --test nco
brew test --retry --verbose nco
brew linkage --test ncview
brew test --retry --verbose ncview
brew test --retry --verbose osmcoastline
brew test --retry --verbose pdal
brew test --retry --verbose points2grid
brew test --retry --verbose simple-tiles
brew linkage --test vtk
brew test --retry --verbose vtk
```

**Review by carlocab — DISMISSED** [review]
Only failures are `dynare` and `octave` on Mojave, but that's from the missing `plotutils` bottle.

Merging now to avoid issues with merge conflicts later.

**Comment by tschoonj** [comment]
I don't think that this was the right approach to solve `netcdf`'s build failure: there's a good chance you will now have broken lots of users' software linked against hdf5.

HDF5 suggests to use [compatibility macros](https://portal.hdfgroup.org/display/HDF5/API+Compatibility+Macros) is a case like this. Have you tried passing `-DH5Literate_vers=1` to NetCDF's cmake CFLAGS?

**Comment by carlocab** [comment]
Sorry, I was under the impression this change would be safe. Let me test adding those to NetCDF's CMake flags.

Should we revert the updates? They haven't been up for long.

**Comment by tschoonj** [comment]
I would certainly vote for reverting these updates.

If assume you had to rebuild all these dependent packages because there were runtime linker issues?

**Comment by carlocab** [comment]
Linkage failures, yes. But it looked mostly like linkages through cellar paths that were invalidated by the `hdf5` revision bump.

I'll revert them.

**Comment by tschoonj** [comment]
Thanks!

**Comment by carlocab** [comment]
Passing `-DH5Literate_vers=1` didn't work. Still the same error:
```
CMake Error at CMakeLists.txt:794 (MESSAGE):
  /usr/local/lib/libhdf5.dylib does not contain symbol '_H5Literate'.  Please
  recompile your libhdf5 install using '--with-default-api-version=v18'.
```

**Comment by tschoonj** [comment]
Can you try the suggested solution [here](https://github.com/Unidata/netcdf-c/issues/1965#issuecomment-813094669)?

**Comment by carlocab** [comment]
No luck; same error.

**Comment by tschoonj** [comment]
I will give this a try later today and get back to you.

**Comment by carlocab** [comment]
Thanks very much.

**Comment by tschoonj** [comment]
This works for me:

```
cmake -DCMAKE_C_FLAGS="-I/usr/local/opt/hdf5/include -DH5Literate_vers=1" ..
```

It seems important to pass the location of the HDF5 headers through `CMAKE_C_FLAGS`, as `H5public.h` is not found otherwise in the [macro check](https://github.com/Unidata/netcdf-c/blob/master/CMakeLists.txt#L784-L788).

**Comment by carlocab** [comment]
Huh, I was looking at their macro check. Didn't realise it needed the include path too. Thanks!

**Comment by tschoonj** [comment]
No problem.

Please never get tempted to change the default API in HDF5 again 😄

**Comment by carlocab** [comment]
Sorry 😞

Let's put that change through CI. Will add another revision bump to all these formulae for the people who did `brew upgrade` before the revert.

**Pull request closed without merging**
