### PR TITLE
circleci 0.1.2061

### PR DESCRIPTION
**Pull request by zzak**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Thank you always for your support! :bow:

### CODE REVIEW

**Comment by zzak** [comment]
It seems this test is failing because I'm unable to use pipes?

To be honest, it would be better for us if we could just remove this test. It's likely this behavior could change, and we don't worry about incidentally breaking the homebrew formula if we decide to.

I've seen plenty of formula that only have a "version" test to verify it works.

Would that be sufficient enough?

(pinging @commitay and @DomT4 as they've been particularly helpful in the past :bow:)

**Comment by SMillerDev** [comment]
We're trying to move away from version tests and trying to test some actual function now. Would there be anything else that can test the actual functionality?

**Comment by zzak** [comment]
@SMillerDev From our perspective we already have CI for integration testing this project, so having to maintain another set of tests that we can't easily and quickly modify or update is painful.

Most of the functionality of our program is reading config files from disk or sending it over the wire. This means we would need some mechanism, such as a pipe, to generate test data. Do you have any suggestions about this?

**Comment by zzak** [comment]
It seems now that the `brew audit` is failing:

```
22:31:19 ==> FAILED
22:31:19 Error: 1 problem in 1 formula detected
22:31:19 circleci:
22:31:19   * 'revision 1' should be removed
```

Any ideas?

**Pull request closed without merging**
