### PR TITLE
azure-cli 2.0.47

### PR DESCRIPTION
**Pull request by troydai**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by troydai** [comment]
I'm looking into the failures.

**Comment by troydai** [comment]
Is this problem related to my change or is it the CI's issue?

**Comment by commitay** [comment]
CI issue, I've restarted the build.

**Comment by troydai** [comment]
Cool. Thanks.

**Comment by commitay** [comment]
Thanks @troydai!

**Pull request closed without merging**
