### PR TITLE
dosbox-staging 0.78.1

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by oturpe** [comment]
I am not sure if commenting on a closed pull request is a proper place to discuss this,
but here goes:

[According to Repology][repology],
Homebrew packages dosbox-staging version 0.78.1.
Such release does not actually exist,
see [this discussion][discussion]
for explanation of the v0.78.1 tag in upstream GitHub.

I am not a regular Alpine contributor or user,
(but maintaining the dosbox-staging pakcage in Fedora,)
but perhaps you want to revert to the latest released version v0.78.0
or mark the package as a release candidate or such?

[repology]: https://repology.org/project/dosbox-staging/versions
[discussion]: https://github.com/dosbox-staging/dosbox-staging/issues/1488

**Comment by pthariensflame** [comment]
@chenrui333 Thoughts on how to proceed?

**Comment by chenrui333** [comment]
@pthariensflame we have to revert the change and reset the version.

The livecheck does show me 0.78.1 is not the latest release

```
$ brew livecheck dosbox-staging
dosbox-staging : 0.78.1 ==> 0.78.0
```

**Comment by chenrui333** [comment]
@oturpe do we know when this is going to be released? (if it would be next week, I guess we can just wait a bit)

**Comment by oturpe** [comment]
> @oturpe do we know when this is going to be released? (if it would be next week, I guess we can just wait a bit)

I do not think upstream has given any estimated release date for 0.78.1.
I suppose you could ask about that in the linked discussion,
I am not very close to upstream, just packaging it for Fedora.

**Comment by samford** [comment]
Thanks for raising the issue upstream and commenting here, @oturpe. I came across this after I noticed the version mismatch in `brew livecheck`. I usually flag yanked versions by replying to the version bump PR and mentioning any maintainers who were involved, so this is what I would have done as well 👍

Since it's unclear when the next release will happen and there aren't many installs of `dosbox-staging`, I went ahead and created a PR to downgrade the formula to 0.78.0 in the interim time (#92523).

**Pull request closed without merging**
