### PR TITLE
aws-sam-cli 1.70.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
on linux build
```
    * Binaries built for a non-native architecture were installed into aws-sam-cli's prefix.
      The offending files are:
        /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.70.0/libexec/lib/python3.11/site-packages/samcli/local/rapid/aws-lambda-rie-arm64	(arm64)
```

**Review by p-linnane — APPROVED** [review]

**Comment by mndeveci** [comment]
Hi @chenrui333 & @p-linnane 

This is Mehmet from SAM CLI team, can we remove AWS SAM CLI from core repo until we align about its distribution? We've just made a SAM CLI release but it hasn't been updated in Homebrew yet.

**Comment by torresxb1** [comment]
Following up on @mndeveci 's message above, we tried running `brew bump-formula-pr aws-sam-cli --version 1.70.1`, but got:

```
Warning: This formula has resources that may need to be updated.
Error: You need to bump this formula manually since the new URL
and old URL are both:
  https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.70.1
```

To unblock our releases we think this file might need to be removed until we're aligned on this, since this seems to be causing our formula to not auto-update like it used to before.

**Comment by chenrui333** [comment]
Let's not revert this change, I just created [a new PR](https://github.com/Homebrew/homebrew-core/pull/121366) making sure the formula is up to date.

There are several solutions that I can see:
- azure-cli team has some sort of template to populate resources that your team can probably do the same
- or I will need to add some fix into that junit-xml dependency issue (it is not an issue for this formula, but for all python formulae depending on junit-xml), right now `brew bump --open-pr` is using pypi to resolve the dependencies, which is not quite ideal
- or we as maintainers/contributors will ensure it is always up to date. 

Does that sound good?

**Comment by torresxb1** [comment]
Hi @chenrui333, thanks for the response. But how do we ensure in the short term that our releases are automatically updated? `brew install aws-sam-cli` used to grab the latest version as soon as we published it, but now we'd have to rely on the homebrew maintainers. For now we had to point users to install with `brew install aws/tap/aws-sam-cli` to get the latest version, and it's probably not a good experience from SAM CLI to our users to suddenly change the installation command for customers (and a lot might miss this)

**Comment by chenrui333** [comment]
> Hi @chenrui333, thanks for the response. But how do we ensure in the short term that our releases are automatically updated? `brew install aws-sam-cli` used to grab the latest version as soon as we published it, but now we'd have to rely on the homebrew maintainers. For now we had to point users to install with `brew install aws/tap/aws-sam-cli` to get the latest version, and it's probably not a good experience from SAM CLI to our users to suddenly change the installation command for customers (and a lot might miss this)

for users who are using tap, they will continue using tap until there is a tap migration. For users who choose to use core tap, that means, they need to wait for the maintainer/contributor to bump it (yeah, there is some delay)

**Comment by chenrui333** [comment]
I will see if I can work out some workaround for `brew bump` experience.

**Comment by chenrui333** [comment]
alright, we just shipped aws-sam-cli 1.71.0.

**Comment by chenrui333** [comment]
@mndeveci @torresxb1, hope you are doing well today, thanks to @brianebeyer's efforts of uploading the new pypi resource for junit-xml, the bump should work smoothly now. Let me know if you have issues of creating new version bump PRs. 🎉

**Comment by chenrui333** [comment]
I also create [this PR](https://github.com/aws/aws-sam-cli/pull/4614) for automate the version bump, let me know if that works.

**Comment by torresxb1** [comment]
Hi @chenrui333 , thanks for the quick followup! I just tried running the version brew command to bump the version again but got this at the end: `Error: "aws-sam-cli" contains non-PyPI resources. Please update the resources manually.`

Then I tried running again and:
```
$ brew bump-formula-pr aws-sam-cli --version 1.71.0
Warning: This formula has resources that may need to be updated.
Error: You need to bump this formula manually since the new URL
and old URL are both:
  https://files.pythonhosted.org/packages/bf/a3/d31cca8dc6a6b129fa316d26280ee2a01904907eda0f58c3169181c37c7c/aws-sam-cli-1.71.0.tar.gz
```

Any pointers on if there's something else we should do?

**Comment by chenrui333** [comment]
> Hi @chenrui333 , thanks for the quick followup! I just tried running the brew command to bump the version again but got this at the end: `Error: "aws-sam-cli" contains non-PyPI resources. Please update the resources manually.`
> 
> Then I tried running again and:
> 
> ```
> $ brew bump-formula-pr aws-sam-cli --version 1.71.0
> Warning: This formula has resources that may need to be updated.
> Error: You need to bump this formula manually since the new URL
> and old URL are both:
>   https://files.pythonhosted.org/packages/bf/a3/d31cca8dc6a6b129fa316d26280ee2a01904907eda0f58c3169181c37c7c/aws-sam-cli-1.71.0.tar.gz
> ```
> 
> Any pointers on if there's something else we should do?

there is a open PR for fixing the non-pypi resource #121430 

And that should be resolved after it. But I dont know why you have the resources being the same

**Comment by p-linnane** [comment]
@torresxb1 Is your local copy of the formula already on 1.71.0? You won't be able to use `bump-formula-pr` unless its on an outdated version.

**Comment by torresxb1** [comment]
@p-linnane ah gotcha. Is `brew update-reset` the recommended approach to resetting the local copy of the formula in case of failures to bump like this one? That seemed to work (although the bump still fails because of the fix that's waiting on a PR linked above)

**Comment by chenrui333** [comment]
Yes, `brew update-reset` is the one 😄

**Comment by chenrui333** [comment]
@torresxb1 can you give the `brew bump` a retry? Should be good now.

**Comment by torresxb1** [comment]
@chenrui333 I see our latest version is already up on brew, but I'll try on our next release. Thank you so much! 🙏

**Pull request closed without merging**
