### PR TITLE
mono: switch to openssl@3

### PR DESCRIPTION
**Pull request by mchoo7**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fel1x-developer** [comment]
I don't know why this fails on macOS 12/arm64. On my mac (macOS14/arm64), this should be

```
==> ./build.sh --configuration Release
/private/tmp/mono--fsharp-20240309-12847-9d8n5s/.dotnet/dotnet-install.sh: line 594: wget: command not found
/private/tmp/mono--fsharp-20240309-12847-9d8n5s/.dotnet/dotnet-install.sh: line 594: wget: command not found
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.405/dotnet-sdk-3.1.405-osx-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.405/dotnet-sdk-3.1.405-osx-x64.tar.gz
dotnet-install: Adding to current process PATH: `/private/tmp/mono--fsharp-20240309-12847-9d8n5s/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
FSharp.sln:

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.405

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
```

**Comment by cho-m** [comment]
If I recall correctly, mono's `fsharp` is too old and needs Rosetta on Apple Silicon to build (not available on CI) and it is not compatible with OpenSSL 3 on Linux.

`mono` doesn't seem to be syncing with recent `dotnet/fsharp` so the likelihood of this formula surviving is low.

At best we can kill off Linux and ARM builds and maybe support Intel macOS only if it still builds.

**Comment by fel1x-developer** [comment]
> At best we can kill off Linux and ARM builds and maybe support Intel macOS only if it still builds.

How can I disable for specific arch/OS?

**Comment by cho-m** [comment]
> How can I disable for specific arch/OS?

Intel macOS restriction would be adding following:
```rb
depends_on arch: :x86_64
depends_on :macos
```

Optionally removing all the related `on_linux`, `OS.linux?`, `on_arm`, `Hardware::CPU.arm?` stuff. Could leave it if someone wants to `brew extract` formula to source build on one of those platforms.

**Comment by fel1x-developer** [comment]
Followed by #166109

**Pull request closed without merging**
