### PR TITLE
networkit libnetworkit 10.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fabratu** [comment]
@SMillerDev @chenrui333 Thanks for taking care of updating! Once ttmath is available as a package, it might require a patch to networkit to actually use it. Can provide this if needed.

**Comment by SMillerDev** [comment]
If it's submitted upstream you can already submit the patch.

**Comment by chenrui333** [comment]
> @SMillerDev @chenrui333 Thanks for taking care of updating! Once ttmath is available as a package, it might require a patch to networkit to actually use it. Can provide this if needed.

Yeah, feel free to show it in here. Thanks!

**Comment by fabratu** [comment]
> > @SMillerDev @chenrui333 Thanks for taking care of updating! Once ttmath is available as a package, it might require a patch to networkit to actually use it. Can provide this if needed.
> 
> Yeah, feel free to show it in here. Thanks!

Re-reading my comment from yesterday - I think the wording was not precise enough. I was referring to a possible patch for networkit. Checked the cmake code afterwards and there is no indication, that a patch would be needed. Also seems that tests are now running fine. 

I also did (successfully) `brew install --build-from-source <formula>`, `brew test <formula>` and `brew audit --strict <formula>` on the PR-branch.

**Comment by chenrui333** [comment]
I see, make sense.

**Comment by chenrui333** [comment]
I think we are good to merge this.

**Pull request closed without merging**
