### PR TITLE
ansible 2.4.0.0 & remove obsolete workaround

### PR DESCRIPTION
**Pull request by rdewaele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The other version bump pull request (https://github.com/Homebrew/homebrew-core/pull/18252) seems to fail checks and diff shows it has not removed the failing workaround.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Please do not open duplicates.

**Comment by rdewaele** [comment]
How is this a duplicate if the other build is failing?

**Comment by ilovezfs** [comment]
Also, please do not ask rhetorical questions.

**Comment by rdewaele** [comment]
I am sorry, this is really not intended to be a rhetorical question. I am honestly requesting how I should proceed to help fixing the failing build. If this pull request is not the way to do it, please advice how I should proceed.

**Comment by ilovezfs** [comment]
>I am honestly requesting how I should proceed to help fixing the failing build.

other PR is just waiting on me to update the resource blocks, which I will do ASAP. has nothing to do with a failing build.

**Pull request closed without merging**
