### PR TITLE
fn 0.4.11 fix

### PR DESCRIPTION
**Pull request by treeder**
fn 0.4.11 version update with test fix.

### CODE REVIEW

**Comment by treeder** [comment]
Looks like issue with jenkins:

```
Fetching upstream changes from https://github.com/Homebrew/homebrew-core/
18:47:28  > git --version # timeout=10
18:47:28  > git fetch --tags --progress https://github.com/Homebrew/homebrew-core/ +refs/pull/*:refs/remotes/origin/pr/*
18:47:37 ERROR: Error fetching remote repo 'origin'
18:47:37 hudson.plugins.git.GitException: Failed to fetch from https://github.com/Homebrew/homebrew-core/
18:47:37 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:817)
18:47:37 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1084)
18:47:37 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @treeder! Shipped :)

**Pull request closed without merging**
