### PR TITLE
imagemagick: update checksum

### PR DESCRIPTION
**Pull request by ctd**
I don't know where the previous sum came from, but it was invalid for me. New sum was obtained from https://imagemagick.org/archive/digest.rdf and matches what I received as at time of commit.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Both #134953 and #134954 had the same checksum.

**Comment by chenrui333** [comment]
Looks like upstream did a re-release.

**Comment by chenrui333** [comment]
raised an upstream issue on this.

**Comment by chenrui333** [comment]
this is good to be merged, we can followup separately to see if we want to add/update livecheck

**Comment by Bo98** [comment]
Maybe worth checking imagemagick@6 too.

**Comment by chenrui333** [comment]
> Maybe worth checking imagemagick@6 too.

yeah, that is right, thing deal for [imagemagick@6](https://github.com/Homebrew/homebrew-core/pull/135036)

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @ctd!!

**Pull request merged**
