### PR TITLE
eturnal 1.10.1 (new formula)

### PR DESCRIPTION
**Pull request by sando38**
STUN/TURN server
https://eturnal.net
https://github.com/processone/eturnal

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Reopening due to accidental closing of #133099

### CODE REVIEW

**Comment by sando38** [comment]
Again, the build succeeds in my github actions, including testing:
https://github.com/sando38/eturnal/actions/runs/5220495560/jobs/9423628658

Is there a way that you provide me the output of the logs of the service? They can be found in `$(brew --prefix)/opt/eturnal/log`

**Comment by sando38** [comment]
Hm.. Maybe it is a missing dependency then. 

Is there a way that you can provide me the output of the logs of the service? They can be found in `$(brew --prefix)/opt/eturnal/log`

**Comment by sando38** [comment]
Ping

**Comment by sando38** [comment]
Ping, need feedback. Thanks :+1:

**Comment by sando38** [comment]
> > Ping, need feedback. Thanks +1
> 
> Ping 🎸

I need feedback. Thanks in advance.

**Comment by sando38** [comment]
eturnal dependency openssl can also be bumped to openssl 3. Not doing it currently to not run another CI.

**Comment by sando38** [comment]
Ping, need feedback. Thanks +1

**Comment by SMillerDev** [comment]
I think this is much too brittle for us to ship in Homebrew. A lot of patching is required, the files are moved manually and it doesn't work on Linux.

**Comment by weiss** [comment]
Upstream here (together with @sando38).  I'm all for improving packaging-friendliness of our code, so just to make sure I understood the current issues correctly:

1. **Patches**
    Do you think this would need _additional_ patches for some reason?  Or is this about the _existing_ patches in @sando38's formula, which as far as I can see are literally just [editing four lines][4]?
2. **Installation**
   Is this about using 

[4]: https://github.com/sando38/homebrew-core/blob/6e334ac814386f03d26b26a9cb9b02eca52d27dc/Formula/eturnal.rb#L22-L37

**Comment by weiss** [comment]
Upstream here (together with @sando38). I'm all for improving packaging-friendliness of our code, so just to make sure I understood the current issues correctly:

- **Patches**
  Do you think this would need additional patches for some reason? Or is this about the existing patches in @sando38's formula, which as far as I can see are literally just editing four lines?
- **Installation**
  Is this about using `.install` calls rather than some `make install` command for

**Pull request closed without merging**
