### PR TITLE
grakn 0.13.0

### PR DESCRIPTION
**Pull request by merqurio**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by merqurio** [comment]
For a possible future pull request:
As grakn is a DB, it feel right to me to store the data somewhere else other than the `libexec`. Maybe in `/usr/local/var` and link the directory to the `libexec` ? I would like to know your opinion on this and if it's a usual practice; if you can point me out a Formula where something similar is done, just to try to be as close to it as possible to it, and maintain a coherence. 

Thanks !

**Comment by ilovezfs** [comment]
@merqurio thanks for the PR. Shipped! Maybe take a look at the `mysql` formula.

**Comment by merqurio** [comment]
Thanks for the recommendation @ilovezfs !
What about Formula/[cassandra.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cassandra.rb)? as both are Java based, are more similar. Is this a good formula to learn(copycat) from ? 

`grakn` itself uses `cassandra` as storage would it be better to install the `cassandra` formula and then connect `grakn` to it ?

Thanks for your time I really appreciate it.

**Comment by ilovezfs** [comment]
>What about Formula/cassandra.rb? as both are Java based, are more similar. Is this a good formula to learn(copycat) from ?

Yes that's a reasonable example, too. `mysql` has a better situation than `cassandra` since it can do `-DMYSQL_DATADIR=#{datadir}` where `datadir` is `var/"mysql"`.

`cassandra` has to do
```
      s.gsub! "cassandra_storagedir\=\"$CASSANDRA_HOME/data\"", "cassandra_storagedir\=\"#{var}/lib/cassandra\""
```
which isn't ideal.

```
grakn itself uses cassandra as storage would it be better to install the cassandra formula and then connect grakn to it ?
```
Possibly, if it works!

**Pull request merged**
