### PR TITLE
idris 0.12

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@UniqMartin Generated by typing `bfpr idris` :)

**Comment by UniqMartin** [comment]
@ilovezfs Are you pointing this out because it shows the `revision`-removal logic in action? :wink:

**Comment by ilovezfs** [comment]
@UniqMartin No I'm pointing it out because I have it using `brew livecheck` to figure out the parameters on its own :)

**Comment by UniqMartin** [comment]
Oh, right. I completely missed the fact that you didn't provide any other arguments. That's almost a bit scary and completely ignores all the things we normally ask contributors to do in our PR template. 😜

**Comment by UniqMartin** [comment]
:+1: This PR seems fine nonetheless.

**Comment by ilovezfs** [comment]
@UniqMartin Yes, I know automation is scary.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Feature request: make this something in a `brew test-bot`-type form that we can make @BrewTestBot run nightly to open lots of PRs for us.

**Comment by ilovezfs** [comment]
@MikeMcQuaid Yep, baby steps, but that is indeed the goal. Right now I

1. run live check against all formulae
2. extract a list of upgrades for core formulae
3. diff the list from step two against the prior list from step two, which yields the set of potential new upgrades (as opposed to outstanding stale upgrades we haven't gotten around to yet).
4. manually verify the new versions from step 3 are actually stable specs and not false positive RCs
5. open PRs bfpr

1: https://gist.githubusercontent.com/ilovezfs/7d8c418985a684a8b7634e3e6b88044d/raw/11b821f55de0262dfea8886ad78da93e4882b88b/gistfile1.txt
2: livecheck_to_core_list(){(grep '==>' $1|sed -e 's/(guessed) //'|awk '{print $1" "$3" "$5}'|awk '($2 != $3) {print}'|grep -v php|awk '{print $1}'|sed -e "s/\(.*\)/\1.rb/"|xargs -n1 -I % stat $(brew --repo homebrew/core)/Formula/"%" 2>/dev/null|awk -F '/' '{print $NF}'|xargs -n1 basename -s .rb)}
3. new(){(f=$(ls -tr|grep -v txt|tail -2|tr '\n' ' '); A=$(echo $f|awk '{print $1}'); B=$(echo $f|awk '{print $2}'); diff $A $B|grep '>')}
4. `ag` + :eyes: 
5. bfpr(){(blc=$(brew livecheck $1|awk -F ':' '{print $2}'|awk '{print $1" "$NF}'); export F=$1 R=$(echo $blc|awk '{print $1}')/$(echo $blc|awk '{print $NF}'); brew bump-formula-pr --url="$(brew ruby -e "puts Formula[\""$F"\"].stable.url"|sed -e s/$R/g)" $F)} with my customized bump-formula-pr.rb: https://gist.githubusercontent.com/ilovezfs/8cd12a679e5b95b6e19aa519fdb860f8/raw/88204a64abd6b44fda1ec9ec6b552aea36812ba5/gistfile1.txt

**Comment by MikeMcQuaid** [comment]
@ilovezfs Neat.

**Comment by ilovezfs** [comment]
@MikeMcQuaid BTW some progress on the Idris GHC 8 issue. They've managed to figure out the underlying problem is a "bug" (or at least behavioral change in GHC 8): https://ghc.haskell.org/trac/ghc/ticket/12201.

Also, there is now an Idris PR (https://github.com/idris-lang/Idris-dev/pull/3226) with a work around that lets it build with GHC 8. However, [upstream is leaning toward](https://github.com/idris-lang/Idris-dev/pull/3226#issuecomment-226933553) waiting on GHC to "fix" it and relying on Stack+GHC 7 indefinitely until Stack moves to GHC 8, to which [I have objected](https://github.com/idris-lang/Idris-dev/pull/3226#issuecomment-227463968).

**Comment by MikeMcQuaid** [comment]
@ilovezfs Thanks for following up.

**Pull request closed without merging**
