### PR TITLE
cassandra@2.2 2.2.15

### PR DESCRIPTION
**Pull request by iMichka**
as we will delete the python@2 formula end of the year.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Shouldn't this versioned formula be removed? Will upstream keep supporting it?

**Comment by bayandin** [comment]
Current URL doesn't work, it seems they have changed it to `http://archive.apache.org/dist/cassandra/2.2.14/apache-cassandra-2.2.14-bin.tar.gz` (`sha256` should be the same)

**Comment by Bo98** [comment]
The current URL scheme only works for the latest version - which is 2.2.15 (for the 2.2 branch). archive.apache.org has does not delete old versions so we should indeed use that, and perhaps do the 2.2.15 update while we are here.

In terms of support, 2.1 and 2.2 are supported until 4.0 is released (date TBD).

**Comment by iMichka** [comment]
Thanks. Updated to 2.2.15. This will use system Python 2, until either system Python 2 does not exist anymore, or cassandra 2.2 is EOL.

**Pull request closed without merging**
