### PR TITLE
mdless 2.0.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre></pre>
</details>

### CODE REVIEW

**Comment by Bo98** [comment]
This doesn't seem like a real version bump

image

The default `develop` branch has none of the new commits so also points to 1.0.37.

New commits are in `master` but tag still points to the tip of `develop`.

**Comment by chenrui333** [comment]
yeah, looks like is a fake tag

image

**Comment by chenrui333** [comment]
- https://github.com/ttscoff/mdless/issues/91

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/155235

**Pull request closed without merging**
