### PR TITLE
imagemagick: add liblqr dependency.

### PR DESCRIPTION
**Pull request by galaxy001**
Add libLQR support.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
* add `revision 1` since we're changing dependencies 
* squash your commits together with a [message formatted per our guidelines](https://docs.brew.sh/Formula-Cookbook#commit)
* `fftw` is a pretty heavy dependency since it brings in all of `gcc`. I would be more comfortable with including this if we can get `fftw` to build with clang + libomp rather than GCC to avoid bringing an entire compiler toolchain in.

**Comment by SMillerDev** [comment]
Yeah, agreed with @jonchang . Recursively depending on GCC for something as widely used as ImageMagick is too much.

**Comment by MikeMcQuaid** [comment]
Also agreed.

**Comment by galaxy001** [comment]
Personally I just need liblqr, during search I find someone posted how to add fftw.
And I read that `optional` cannot be used here.

So it is ok for me to remove fftw.

**Review by MikeMcQuaid — DISMISSED** [review]
Looks good to me. `liblqr` depends on `glib` but `imagemagick` already does, too.

**Comment by galaxy001** [comment]
@jonchang

Is there a way to use GitHub web interface to squash the commits ?

Is this commit message OK ?
```
Add liblqr support to imagemagick

Add lqr to delegates.
```

**Comment by MikeMcQuaid** [comment]
> Is there a way to use GitHub web interface to squash the commits ?

Unfortunately not.



> Is this commit message OK ?

No, please read https://docs.brew.sh/Formula-Cookbook#commit.

> for fixes is `foobar: fix flibble matrix.`

**Review by sjackman — DISMISSED** [review]

**Comment by MikeMcQuaid** [comment]
@sjackman dismissing your review as it'll auto merge otherwise.

**Comment by sjackman** [comment]
> @sjackman dismissing your review as it'll auto merge otherwise.

Sorry! I'm behind the times on core workflow.

**Comment by SMillerDev** [comment]
Next time please don't make a new pull request for your squashed commit.

**Comment by galaxy001** [comment]
@SMillerDev

Would you tell me how to do it within same pull request ?

**Comment by SMillerDev** [comment]
`git rebase -i origin/master`
Then mark which commits you want to squash
`git push --force-with-lease`

**Pull request closed without merging**
