### PR TITLE
platformio 3.4.1

### PR DESCRIPTION
**Pull request by ivankravets**
* Pre/Post extra scripting for advanced control of PIO Build System ([issue #891](https://github.com/platformio/platformio-core/issues/891))
* New [lib_archive](http://docs.platformio.org/page/projectconf/section_env_library.html#lib-archive) option to control library archiving and linking behavior ([issue #993](https://github.com/platformio/platformio-core/issues/993))
* Add "inc" folder automatically to CPPPATH when "src" is available (works for project and library) ([issue #1003](https://github.com/platformio/platformio-core/issues/1003))
* Use a root of library when filtering source code using [library.json](http://docs.platformio.org/page/librarymanager/config.html)  and ``srcFilter`` field
* Added ``monitor_*`` options to white-list for [Project Configuration File "platformio.ini"](http://docs.platformio.org/page/projectconf.html) ([issue #982](https://github.com/platformio/platformio-core/issues/982))
* Do not ask for board ID when initializing project for desktop platform
* Handle broken PIO Core state and create new one
* Fixed an issue with a custom transport for [PIO Unit Testing](http://docs.platformio.org/page/plus/unit-testing.html) when multiple tests are present
* Fixed an issue when can not upload firmware to SAM-BA based board (Due)

### CODE REVIEW

**Comment by fxcoudert** [comment]
Shouldn't `requests` be updated to the latest, i.e. 2.18.3? And check the others

**Comment by ivankravets** [comment]
I used your "poet". Does it fetch the latest versions?

**Comment by ivankravets** [comment]
It seems that `poet` uses local package versions. I've just updated all dependencies to the latest versions.

**Comment by fxcoudert** [comment]
Thanks for the pull request!

**Comment by ilovezfs** [comment]
@ivankravets `poet` should be run in a `virtualenv`

**Comment by ivankravets** [comment]
@ilovezfs it was run in vritualenv. See https://github.com/platformio/platformio-core/blob/develop/tox.ini#L18

**Comment by ilovezfs** [comment]
@ivankravets I mean in a new, clean virtualenv. Then all the packages will be current.

**Comment by ivankravets** [comment]
Thanks, got you.

**Comment by ilovezfs** [comment]
You're welcome!

**Pull request closed without merging**
