### PR TITLE
ruby 3.0.2

### PR DESCRIPTION
**Pull request by jerryskye**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by bayandin** [comment]
`rubygems` resource should be updated to the latest one — 3.2.22

**Review by jmonteiro — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Thanks, @jerryskye.

`rav1e` failure on Linux looks more like a problem with `curl` rather than `ruby`.

```
==> Testing rav1e
==> Downloading https://media.xiph.org/video/derf/y4m/bus_qcif_7.5fps.y4m
/home/linuxbrew/.linuxbrew/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.2.1-28-g7c2a8f6\ \(Linux\;\ x86_64\ Ubuntu\ 16.04.7\ LTS\)\ curl/7.47.0 --header Accept-Language:\ en --fail --silent --retry 3 --location --remote-time --output /home/linuxbrew/.cache/Homebrew/downloads/84dee343cc5619f633a22fc51045e2ae977ead573b95e40f02aa7b9dea7908ea--bus_qcif_7.5fps.y4m.incomplete https://media.xiph.org/video/derf/y4m/bus_qcif_7.5fps.y4m
/home/linuxbrew/.linuxbrew/bin/curl: error while loading shared libraries: libldap-2.5.so.0: cannot open shared object file: No such file or directory
```

CC @iMichka @dawidd6

**Comment by dawidd6** [comment]
We should be using system curl rather than brewed one I believe. This looks like a bug to me. And I think it occurred in the past but with git?

**Comment by iMichka** [comment]
Yes, I think we use system curl to download resources. This is a bug in `brew`.

The error looks fishy though:
> /home/linuxbrew/.linuxbrew/bin/curl: error while loading shared libraries: libldap-2.5.so.0

Looking at curl's linkage in homebrew-core, everything looks fine. So it might be that brewed `curl` was still present; but `openldap` got removed. I checked the linkage and everything is fine on my machine, so this is probably a weird test-bot thing.

**Comment by iMichka** [comment]
See https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/curl.rb#L17-L26

We might want to invert the order between system curl and PATH curl. At least on linux, or for CI only.

**Comment by dawidd6** [comment]
Or just set HOMEBREW_CURL_PATH in test-bot to /usr/bin/curl.

**Pull request closed without merging**
