### PR TITLE
wasm-pack 0.9.1 (new-formula)

### PR DESCRIPTION
**Pull request by rajivshah3**
Add wasm-pack (https://github.com/rustwasm/wasm-pack)

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rajivshah3** [comment]
I'm having some trouble with the test - I tried following https://rustwasm.github.io/wasm-pack/book/quickstart.html

**Comment by rajivshah3** [comment]
I'm not too familiar with `rustup` so I'm not sure why it's talking about `sudo` [here](https://github.com/Homebrew/homebrew-core/pull/54924/checks?check_run_id=687224903#step:6:48) 🤔

**Comment by SMillerDev** [comment]
It seems to have issues with the build sandbox. Please check other formula for rustup usage.

**Comment by rajivshah3** [comment]
> Please check other formula for rustup usage.

I'm not sure if there are any other formulae using `rustup` 🤔  a search for `rustup` in the repo and running `brew uses rustup` didn't seem to find anything

**Comment by rajivshah3** [comment]
I could try a non-`rustup` approach but that looks a bit messy: https://rustwasm.github.io/docs/wasm-pack/prerequisites/non-rustup-setups.html

**Comment by chenrui333** [comment]
> I could try a non-`rustup` approach but that looks a bit messy: https://rustwasm.github.io/docs/wasm-pack/prerequisites/non-rustup-setups.html

let me play around a little bit (right now suffering rustc issue installed by rustup-init).

**Comment by chenrui333** [comment]
Should be good now.

**Comment by rajivshah3** [comment]
Ooh nice, thanks @chenrui333 !

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
