### PR TITLE
binaryen 97, emscripten 2.0.5

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
asm2wasm was removed per https://github.com/WebAssembly/binaryen/pull/3042

**Comment by chenrui333** [comment]
we are little bit behind with `emscripten` upgrade
```
Error: 1 failed steps!
brew test --retry --verbose emscripten
```

**Comment by alebcay** [comment]
Did some research on the `emscripten` situation. `emscripten` 2 disables the `fastcomp` backend (which was already deprecated), so we need to make it depend on `llvm`. The `llvm` we ship has the necessary backends compiled in already, but seems to be too old:
```
==> /usr/local/Cellar/emscripten/2.0.4/bin/emcc test.c -o test.js -s NO_EXIT_RUNTIME=0
emcc: warning: LLVM version appears incorrect (seeing "10.0", expected "12.0") [-Wversion-check]
shared:INFO: (Emscripten: Running sanity checks)
clang-10: error: unknown argument: '-fignore-exceptions'
emcc: error: '/usr/local/opt/llvm/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=2 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/include/compat -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/include -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/include/libc -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/local/include -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/include/SSE -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/include/neon -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/lib/compiler-rt/include -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/lib/libunwind/include -Xclang -isystem/private/tmp/emscripten-test-20200921-99393-1nuit2r/.emscripten_cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -o test.js test.c -Xclang -isystem/usr/local/Cellar/emscripten/2.0.4/libexec/system/include/SDL -c -o /private/tmp/emscripten_temp_wridtz84/test_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
```
The `-fignore-exceptions` flag is only available right now in tip-of-tree `llvm` (note that `emcc` expects llvm/clang `12.0` while we're on `10.0`). So for an `emscripten` upgrade right now, we will need to build/ship an unreleased `llvm` with it.

**Comment by chenrui333** [comment]
I think LLVM 12.0 is way early from the stable release, probably we can bundle one llvm for emscripten

**Comment by chenrui333** [comment]
> I think LLVM 12.0 is way early from the stable release, probably we can bundle one `llvm` for `emscripten`

agree, right now, LLVM is far from the stable release.

**Review by SMillerDev — DISMISSED** [review]

**Comment by alebcay** [comment]
I'm working locally on bundling LLVM with `emscripten` 2.x, looks like it currently depends on `binaryen` >= 97.

**Comment by chenrui333** [comment]
> I'm working locally on bundling LLVM with `emscripten` 2.x, looks like it currently depends on `binaryen` >= 97. If preferred, we could probably do both version bumps in this PR.

Sounds like a plan!

**Review by chenrui333 — APPROVED** [review]
💯 Nice work!

**Pull request closed without merging**
