### PR TITLE
libcue 2.1.0

### PR DESCRIPTION
**Pull request by ilovezfs**
use CMake
add a test

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Error: No such file or directory - autogen.sh
```

**Comment by vladshablinsky** [comment]
@ilovezfs they now use CMake. There should be correct inreplace, but I can't come up with one. I'm not that experienced with CMake.

```diff
diff --git a/Formula/libcue.rb b/Formula/libcue.rb
index b00f6a2..0803306 100644
--- a/Formula/libcue.rb
+++ b/Formula/libcue.rb
@@ -13,15 +13,11 @@ class Libcue < Formula
     sha256 "f61624f74ef918f2b90bdfc9157f7a08829153dd2655ad73126e0a0ddd60127d" => :mavericks
   end
 
-  depends_on "automake" => :build
-  depends_on "autoconf" => :build
-  depends_on "libtool" => :build
+  depends_on "cmake" => :build
 
   def install
-    inreplace "autogen.sh", "libtoolize", "glibtoolize"
-    system "./autogen.sh"
-    system "./configure", "--disable-dependency-tracking",
-                          "--prefix=#{prefix}"
+    inreplace "CMakeLists.txt", "${CMAKE_INSTALL_PREFIX}", "#{prefix}"
+    system "cmake", "CMakeLists.txt"
     system "make", "install"
   end
 end
```

**Comment by MikeMcQuaid** [comment]
`std_cmake_args` will set `CMAKE_INSTALL_PREFIX`.

**Comment by dunn** [comment]
Revision bump I guess:
```
==> /usr/local/Cellar/cmus/2.7.1_1/bin/cmus --plugins
dyld: Library not loaded: /usr/local/opt/libcue/lib/libcue.1.dylib
  Referenced from: /usr/local/Cellar/cmus/2.7.1_1/bin/cmus
  Reason: image not found
Error: cmus: failed

**Pull request closed without merging**
