### PR TITLE
grafana 6.4.0

### PR DESCRIPTION
**Pull request by hugohaggmark**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
# golang.org/x/xerrors
../../../../pkg/mod/golang.org/x/xerrors@v0.0.0-20190410155217-1f06c39b4373/adaptor_go1_13.go:16:14: undefined: errors.Frame
../../../../pkg/mod/golang.org/x/xerrors@v0.0.0-20190410155217-1f06c39b4373/format_go1_13.go:12:18: undefined: errors.Formatter
```

**Comment by chenrui333** [comment]
@hugohaggmark looks like grafana has switched to go modules, you need to update the formula to use go modules :)

**Comment by hugohaggmark** [comment]
> @hugohaggmark looks like grafana has switched to go modules, you need to update the formula to use go modules :)

@chenrui333 do you have any documentation about how to solve this?

**Comment by chenrui333** [comment]
@hugohaggmark I was trying to apply this PR change (https://github.com/grafana/grafana/pull/19502), but somehow got rejected with the Dockerfile.

```
patching file vendor/gopkg.in/macaron.v1/fixtures/basic2/hello2.tmpl
patching file vendor/gopkg.in/macaron.v1/fixtures/custom_funcs/index.tmpl
patching file vendor/modules.txt
patching file scripts/go/go.mod
patching file scripts/go/go.mod
patching file scripts/go/go.sum
patching file pkg/setting/setting.go
patching file pkg/tsdb/elasticsearch/elasticsearch.go
patching file Dockerfile
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file Dockerfile.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/grafana--patch-20191004-292-1sibes4/19502.patch` exited with 1.
```

If I do not have patch, I will encounter a `go.mod` issue.

I will take another look tomorrow.

**Comment by chenrui333** [comment]
If you are interested, you can checkout the other golang formula by search (`depends_on "go" => :build`)

**Comment by hugohaggmark** [comment]
@chenrui333 thank you for looking at this, is this because of this latest build error for `catalina`: 
```
An exception occurred within a child process:
  RuntimeError: can't get Master/Slave device
```
BTW I work at grafana so the 6.4.0 version only supports go version 1.12.10.

**Comment by chenrui333** [comment]
Sounds good!

**Comment by chenrui333** [comment]
but how should I applied a merged change for the build issue? when is the next release for Grafana? Thanks!

**Comment by hugohaggmark** [comment]
> but how should I applied a merged change for the build issue? when is the next release for Grafana? Thanks!

I'm not sure I follow you. I could need help with this error that prevents this PR from being merged. Both Mojave & HighSierra passes but not Catalina.

```
An exception occurred within a child process:
  RuntimeError: can't get Master/Slave device
```

**Comment by chenrui333** [comment]
Yeah, you are right. There is known workaround that we can try. Let me do it.

**Comment by chenrui333** [comment]
OK, I was wrong, that is for `gnulib` on Catalina build.

**Comment by chenrui333** [comment]
10:11:44 ==> /usr/local/Cellar/grafana/6.4.0/bin/grafana-server -v
10:11:44 Version 6.4.0 (commit: unknown-dev, branch: master)
10:11:44 Error: grafana: failed
10:11:44 An exception occurred within a child process:
10:11:44   RuntimeError: can't get Master/Slave device

**Comment by chenrui333** [comment]
I think I am OK with the merge.

Thanks @hugohaggmark!!

**Review by chenrui333 — APPROVED** [review]
👍

**Comment by hugohaggmark** [comment]
> I think I am OK with the merge.
> 
> Thanks @hugohaggmark!!

Thank you @chenrui333!

**Pull request closed without merging**
