### PR TITLE
duktape 2.6.0

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Looks like CI is failing due to the `openrct2` formula no longer working. This is ironic, considering my affiliation. It appears the bottle just requires to be relinked to `duktape`, though, as the path has changed with the new version.

What would be the best way to move forward with this?

**Comment by SMillerDev** [comment]
You can add `revision 1` to openrtc2 to rebuild it.

**Comment by SMillerDev** [comment]
Can you make it 2 commits?

- `duktape 2.6.0`
- `openrtc2: revision for duktape`

**Comment by AaronVanGeffen** [comment]
Should be good now. 🙂

**Review by SMillerDev — APPROVED** [review]
Thanks @AaronVanGeffen  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
