### PR TITLE
osmosis 0.49.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

license ref:

```
Osmosis consists of all files in this archive with the exception of the
third party libraries in the lib sub-directory, and the osmosis-osm-binary
library which is a re-packaged version of a third-party library.

Osmosis is placed into the public domain and where this is not legally
possible everybody is granted a perpetual, irrevocable license to use
this work for any purpose whatsoever.

DISCLAIMERS
By making Osmosis publicly available, it is hoped that users will find the
software useful.  However:
* Osmosis comes without any warranty, to the extent permitted by applicable
law.
* Unless required by applicable law, no liability will be accepted by
the authors and distributors of this software for any damages caused
as a result of its use. 
```

### CODE REVIEW

**Comment by iMichka** [comment]
Don't we need to document all the licences of the project?

**Comment by chenrui333** [comment]
> Don't we need to document all the licences of the project?

you mean homebrew-core, or just osmosis

**Comment by iMichka** [comment]
Lol. `osmosis` is enough right now :) 

I see `Licensed under the Apache License, Version 2.0 (the "License");` in the bin folder. For the lib folder ... it's a bunch of .jar files so IDK.

**Comment by chenrui333** [comment]
> Lol. `osmosis` is enough right now :)
> 
> I see `Licensed under the Apache License, Version 2.0 (the "License");` in the bin folder. For the lib folder ... it's a bunch of .jar files so IDK.

maybe ad an upstream license issue and move forward?

this is the only copying.txt file I have seen, https://github.com/openstreetmap/osmosis/blob/main/osmosis/src/dist/copying.txt#L1-L16

**Comment by chenrui333** [comment]
per this commit, https://github.com/openstreetmap/osmosis/commit/fa97a35d7cf02675bd009d822267ff409d3301f8, I think we should be good with the public domain declaration (if there is apache-2.0, that might be a bug)

**Review by iMichka — APPROVED** [review]
Let's merge this then

**Pull request merged**
