### PR TITLE
kplex 1.3.4 (new formula)

### PR DESCRIPTION
**Pull request by caesar**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

New formula for kplex, an NMEA-0183 multiplexer (http://www.stripydog.com/kplex/index.html, https://github.com/stripydog/kplex/)

### CODE REVIEW

**Comment by caesar** [comment]
This is my first homebrew formula, so I'd be happy to receive suggestions on anything I may be doing wrong! Pretty much everything is copied from other formulae.

**Comment by caesar** [comment]
Just modified this to download from Github releases rather than the project website.

**Comment by caesar** [comment]
Hmm, seems to be failing with `GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)` now that I've changed to point to Github instead of the project website. :-/

@ilovezfs does this mean the formula will not be accepted?
It is indeed niche, but highly valuable within that niche (primarily marine navigation systems) – so if it won't be accepted here I'll create my own tap for it.

**Comment by fxcoudert** [comment]
Hi @caesar, thanks for your contribution! We are going to pass on it for now, given the low notability of the project… and as you said, you can host it in a personal tap for others to use. And we'll be glad to reconsider in a bit of time, if you see increased usage of the software.

Thanks again for the suggestion.

**Comment by caesar** [comment]
Thanks for clarifying @fxcoudert. I will have to consider whether I am able to keep a tap of my own up to date… but I might suggest that the project's maintainer creates a tap and maintains it himself, I suppose that would be a better solution anyway.

**Pull request closed without merging**
