### PR TITLE
dav1d 1.0.0 gst-plugins-rs 0.8.3

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
`gst-plugins-rs` also needs a revision bump.

**Comment by carlocab** [comment]
`gst-plugins-rs` may not be compatible with this version of `dav1d`.

@ford-prefect, any chance that you could take a look?

**Comment by ford-prefect** [comment]
@carlocab sure thing, let me take a look -- the `dav1d-rs` package has been updated and is pending a release, and I'll work on bumping `gst-plugins-rs` with this as well.

**Comment by ford-prefect** [comment]
We should be able to get this done upstream soon: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/698

**Comment by ford-prefect** [comment]
ruh roh, sorry about the delay here. Would it make sense to pull in this patch to get things moving: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/698/diffs?commit_id=b4ba27a89152248bd7afacd8182c62108b626da0

**Comment by owine** [comment]
I've added the patch to my branch - hopefully a maintainer can reopen this so CI can run

**Comment by owine** [comment]
@carlocab sorry to tag - are you willing to open this PR?

**Comment by chenrui333** [comment]
Filed [a new PR](https://github.com/Homebrew/homebrew-core/pull/102566) to continue this effort, #97196 (Sorry about the delay)

**Pull request closed without merging**
