### PR TITLE
octant: add completions

### PR DESCRIPTION
**Pull request by max-ae**
split from #110148

### CODE REVIEW

**Comment by SMillerDev** [comment]
Needs a rebase

**Comment by max-ae** [comment]
Build failure looks like a regression unrelated to these changes

**Comment by cho-m** [comment]
Can you try downgrading node dependency?

**Comment by max-ae** [comment]
> Can you try downgrading node dependency?

Did not work... Previous attempt https://github.com/Homebrew/homebrew-core/pull/106816, related issue https://github.com/vmware-tanzu/octant/issues/3329 and PR https://github.com/vmware-tanzu/octant/pull/3311, but has not had progress in the last months...

**Comment by cho-m** [comment]
The last time we successfully built `octant`, we were using `node` 17.6.0 with `npm` 8.5.1. I would assume behavior is related to `npm` version.

One problem is `npm` is usually updated along with NodeJS release so even `node@16` is using a newer `npm` 8.19.2. `node@14` is running `npm` 6.14.17 which may be why upstream PR uses that as a "fix". The additional workaround in upstream PR (manually running `npm install`) is probably due to changes in `npm` major releases - v6 vs v8.

Not sure if possible, but another potential workaround could be locally installing an older `npm` v8 that still works with `npm-force-resolutions`.

---

A more proper upstream fix would be replacing `npm-force-resolutions` with something that actually works with recent `npm` versions.

**Comment by cho-m** [comment]
The last version of `npm` that seemed to work with caret syntax (e.g. `"version": "^x.y.z"`) in package-lock.json was 8.5.5. The changes in 8.6.0 causes this syntax to error.

So, the workarounds that appear to work are either
- using recent `node` and locally install `npm@8.5.5` prepending `PATH` with that binary.
- using older `node@14` and running `npm install` from `web` directory

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
