### PR TITLE
qt 5.14.2

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Noctem** [comment]
I experienced the same building issue as the CI:
```
  File "/private/tmp/qt-20200403-94387-60r62i/qt-everywhere-src-5.14.2/qtwebengine/src/3rdparty/chromium/build/mac/find_sdk.py", line 96, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 10.15.4+ SDK found

See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:64:1: which caused the file to be included.
group("gn_all") {
^----------------
Project ERROR: GN run error!
make[3]: *** [sub-gn_run-pro-make_first] Error 3
make[2]: *** [sub-core-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtwebengine-make_first] Error 2
```

**Comment by Bo98** [comment]
Yes, Apple changed their SDKs to report a patch version for the first time. They have not done this before so it's breaking things.

`-device-option QMAKE_MAC_SDK.macosx.SDKVersion=#{MacOS.sdk.version}` might workaround this but it's a terrible hack.

**Comment by EricFromCanada** [comment]
Apparently not; `configure` eventually fails with `Unknown command line option '-device-option QMAKE_MAC_SDK.macosx.SDKVersion=10.15'`.

**Comment by Bo98** [comment]
Maybe it needs to be separate strings but it doesn't matter, the patch has landed:

https://github.com/qt/qtwebengine/commit/5d2026cb04ef8fd408e5722a84e2affb5b9a3119.patch?full_index=1

Probably will need a `directory "qtwebengine"` or something.

**Comment by Bo98** [comment]
The changes I've just merged in https://github.com/Homebrew/brew/pull/7426 may help some of the test failures here.

**Comment by EricFromCanada** [comment]
The sole failure is now:
```
==> brew audit --skip-style qt --online
==> FAILED
Error: 1 problem in 1 formula detected
qt:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      mkspecs/qmodule.pri
```

**Comment by Bo98** [comment]
It's probably easiest in this case to inreplace `^PKG_CONFIG_EXECUTABLE = .*$` or similar in that file to equal `Formula["pkg-config"].opt_bin/pkg-config`.

**Comment by Bo98** [comment]
The rest of the failures aren't 5.14.2 related:

* qbs (Catalina only) - broke with Xcode 11.4: https://bugreports.qt.io/browse/QBS-1543
* quazip (Catalina only) - likely needs `depends_on :xcode`
* qwtpolar (Mojave and Catalina) - likely needs `depends_on :xcode`
* qxmpp - fixed in #52532

**Pull request closed without merging**
