### PR TITLE
rancher-compose 0.8.3

### PR DESCRIPTION
**Pull request by crunchtime-ali**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by dj-hedgehog** [comment]
There is an open PR https://github.com/Homebrew/homebrew-core/pull/1692 but there hasn't been any response to it.

**Comment by apjanke** [comment]
Build is failing with some missing dependencies. Maybe it needs some go resources added?

```
==> go build -ldflags -w -X github.com/rancher/rancher-compose/version.VERSION 0.8.3 -o /usr/local/Cellar/rancher-compose/0.8.3/bin/rancher-compose
main.go:8:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/Sirupsen/logrus (from $GOROOT)
	/private/tmp/rancher-compose-20160617-18908-1iz8skw/rancher-compose-0.8.3/src/github.com/Sirupsen/logrus (from $GOPATH)
	/private/tmp/rancher-compose-20160617-18908-1iz8skw/rancher-compose-0.8.3/Godeps/_workspace/src/github.com/Sirupsen/logrus
main.go:9:2: cannot find package "github.com/codegangsta/cli" in any of:
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
	/private/tmp/rancher-compose-20160617-18908-1iz8skw/rancher-compose-0.8.3/src/github.com/codegangsta/cli (from $GOPATH)
	/private/tmp/rancher-compose-20160617-18908-1iz8skw/rancher-compose-0.8.3/Godeps/_workspace/src/github.com/codegangsta/cli
main.go:10:2: cannot find package "github.com/docker/libcompose/cli/command" in any of:
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/docker/libcompose/cli/command (from $GOROOT)
	/private/tmp/rancher-compose-20160617-18908-1iz8skw/rancher-compose-0.8.3/src/github.com/docker/libcompose/cli/command (from $GOPATH)
	/private/tmp/rancher-compose-20160617-18908-1iz8skw/rancher-compose-0.8.3/Godeps/_workspace/src/github.com/docker/libcompose/cli/command
==> Formula
Path: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/rancher-compose.rb
```

**Comment by DomT4** [comment]
They've moved from a godep-based system to a vendoring system. It's possible the formula needs some rewriting to accommodate this. Some things move across seamlessly... Others, not so much.

**Comment by dj-hedgehog** [comment]
I'm working on it but can't build `rancher-compose` at all from source because of some package hiccups. Getting back as soon as I've heard from the rancher-guys.
Does anyone know why Go isn't using the packages inside the `vendor` folder?

**Comment by DomT4** [comment]
Merged as part of https://github.com/Homebrew/homebrew-core/pull/2746. You still get the commit credit for this commit, I just moved it over to another PR & added a commit of my own to fix the vendor build & handle another update.

Thank you for your contribution to Homebrew @dj-hedgehog; we appreciate it! 😺

**Comment by dj-hedgehog** [comment]
Oh thanks a lot. I completely forgot about this one.

**Pull request closed without merging**
