### PR TITLE
ripgrep 0.2.1 (new formula)

### PR DESCRIPTION
**Pull request by moshen**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?
  
  ~~I can't because of https://github.com/Homebrew/brew/issues/1140~~
  
  Switched to master and was able to run audit.

---

### CODE REVIEW

**Comment by moshen** [comment]
😦  1 failing check, but when I click the link there are no failing checks.

**Comment by bfontaine** [comment]
It failed on Sierra:
```
==> brew install --only-dependencies --build-bottle --verbose ripgrep
Build timed out (after 60 minutes). Marking the build as aborted.
```

**Comment by justinmayer** [comment]
@moshen: When you update this PR to pass tests on Sierra, you might as well update it to the just-released ripgrep 0.2.1 version as well.  (^_^)

**Comment by moshen** [comment]
```
==> brew install --only-dependencies --build-bottle --verbose ripgrep
Build timed out (after 60 minutes). Marking the build as aborted.
```

Is this related to: https://github.com/Homebrew/homebrew-core/issues/4841 ? Specifically rust being in that list?

**Comment by halilim** [comment]
BTW, there is [a formula](https://github.com/BurntSushi/ripgrep/blob/master/pkg/brew/ripgrep.rb) in the ripgrep repo itself which uses pre-built binaries.

**Comment by wkral** [comment]
Looks like the rust issue was resolved for sierra in  #4960 so the build may work now.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
