### PR TITLE
remove head spec from versioned formulae

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Goes with https://github.com/Homebrew/brew/pull/4411

### CODE REVIEW

**Comment by ilovezfs** [comment]
https://github.com/commitay/homebrew-core/blob/4c345e860cddf24b500a08e83a82d4e2de9cc2c6/Formula/redis%402.8.rb#L21

**Comment by commitay** [comment]
case-sensitive grep 😆

**Comment by ilovezfs** [comment]
shall we retire the `stable do` blocks from guile@2.0, llvm@* or just leave them?

**Comment by commitay** [comment]
Yeah, I'll get rid of them now otherwise I'll end up doing another PR for it next week.

**Comment by ilovezfs** [comment]
🚫  🎧

**Pull request merged**
