### PR TITLE
clang-format: use git for head

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
@fxcoudert we use git for `llvm`, it's simply faster.

**Comment by yurikoles** [comment]
@fxcoudert should we also use Make here?

**Comment by yurikoles** [comment]
bump?

**Comment by yurikoles** [comment]
bump?

**Comment by fxcoudert** [comment]
Sorry… why not, yes. Thanks @yurikoles for the PR!

**Pull request merged**
