### PR TITLE
webp 0.5.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
This actually passed okay. The problem was with the reverse `linkage`, which I'm having some serious doubts about us turning on by default already.

**Comment by ilovezfs** [comment]
What exactly do you mean by "the reverse linkage"? The fact that there are "possible undeclared dependencies" or something else?

**Comment by DomT4** [comment]
Aye, [that change](https://github.com/Homebrew/brew/commit/080ddd8804be14f4b18f9558b58270456ff313c2).

It's not that there's actual breakage there AFAIK, because the dependencies are part of the reverse deps tree, it seems to just be nagging that we've not explicitly included _all_ of them in the formula, which is going to make for some ridiculous formulae when it comes to GTK stuff.

**Comment by ilovezfs** [comment]
Sorry to be blunt, but that change is nuts. We will literally fail just about everything, and fixing it will require writing a bunch of makeshift tests and audit fixes for the entire universe just to get things green.

**Comment by ilovezfs** [comment]
I also have serious doubts that declaring "undeclared" dependencies unconditionally across the board is going to scale. And good luck ever turning uses --recursive back on.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
:green_apple: now that https://github.com/Homebrew/brew/pull/471 was merged.

**Pull request closed without merging**
