### PR TITLE
python-markdown: build with std_pip_args

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to #141912

### CODE REVIEW

**Comment by jasonlyle88** [comment]
@chenrui333 Just taking a look at this to try and help myself better understand how everything here works. 

I noticed that you made the switch from resouce to dependency for `python-markdown` in the `redo` formula, but it does not have an entry in the `pypi_formula_mappings.json` file. Does this need to be added?

**Comment by chenrui333** [comment]
> I noticed that you made the switch from resouce to dependency for `python-markdown` in the `redo` formula, but it does not have an entry in the `pypi_formula_mappings.json` file. Does this need to be added?

that file is mostly used by `brew update-python-resources` and it does not work for redo

```
$ brew update-python-resources redo
==> Retrieving PyPI dependencies for "https://github.com/apenwarr/redo/archive/redo-0.42d.tar.gz"...
Error: Unable to determine dependencies for "https://github.com/apenwarr/redo/archive/redo-0.42d.tar.gz" because of a failure when running
```

**Comment by jasonlyle88** [comment]
Ah, thank you for the information. I was sure that it was just something I didn't understand... but I wanted to understand! Thanks for the explanation 😄 Also good to know what that file is used for!

**Comment by chenrui333** [comment]
no worries :)

**Review by branchv — APPROVED** [review]

**Pull request merged**
