### PR TITLE
gnuradio 3.8.0.0

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
```

**Comment by Bo98** [comment]
Upstream did handle that but they removed it in 3.8.0.0: https://github.com/gnuradio/gnuradio/commit/ab2fb35677e38a384df3f9503d1f45f64bbc0374#diff-45856d0ec64e3d28b38f044024648892L163

**Comment by chenrui333** [comment]
FYI, also there is a new release on Feb 15
https://github.com/gnuradio/gnuradio/tree/v3.7.14.0

**Comment by iMichka** [comment]
I opened an issue upstream: https://github.com/gnuradio/gnuradio/issues/3279

**Comment by iMichka** [comment]
Upstream is looking at this, let's give them a few more days.

**Comment by warnes** [comment]
Any news on this?

**Comment by iMichka** [comment]
As long as https://github.com/gnuradio/gnuradio/issues/3279 is not fixed, we can not do the upgrade. This is an upstream regression.

**Comment by icpz** [comment]
For people who wants to use brewed gnuradio temporarily, you can ship this formulae to your own tap [gnuradio.rb](https://github.com/icpz/homebrew-collection/blob/master/Formula/gnuradio.rb)

This formulae patches the `cmake/Modules/GrPython.cmake` to add `dynamic_lookup` ldflags.

**Comment by iMichka** [comment]
@icpz: can you submit this patch upstream? I bet they will accept it. I can also try to add your patch here: if it works we can have it directly updated here; no need for a tap.

The issues is that nobody provided a patch before, so we where waiting for anybody to fix this.

**Comment by icpz** [comment]
Here is the patch
```patch
diff --git a/cmake/Modules/GrPython.cmake b/cmake/Modules/GrPython.cmake
index fd9b7583a..388da7371 100644
--- a/cmake/Modules/GrPython.cmake
+++ b/cmake/Modules/GrPython.cmake
@@ -56,7 +56,12 @@ set(QA_PYTHON_EXECUTABLE ${QA_PYTHON_EXECUTABLE} CACHE FILEPATH "python interpre
 add_library(Python::Python INTERFACE IMPORTED)
 # Need to handle special cases where both debug and release
 # libraries are available (in form of debug;A;optimized;B) in PYTHON_LIBRARIES
-if(PYTHON_LIBRARY_DEBUG AND PYTHON_LIBRARY_RELEASE)
+if(APPLE)
+    set_target_properties(Python::Python PROPERTIES
+      INTERFACE_INCLUDE_DIRECTORIES "${PYTHON_INCLUDE_DIRS}"
+      INTERFACE_LINK_LIBRARIES "-undefined dynamic_lookup"
+      )
+elseif(PYTHON_LIBRARY_DEBUG AND PYTHON_LIBRARY_RELEASE)
     set_target_properties(Python::Python PROPERTIES
       INTERFACE_INCLUDE_DIRECTORIES "${PYTHON_INCLUDE_DIRS}"
       INTERFACE_LINK_LIBRARIES "$<$<NOT:$<CONFIG:Debug>>:${PYTHON_LIBRARY_RELEASE}>;$<$<CONFIG:Debug>:${PYTHON_LIBRARY_DEBUG}>"
```

I think it's a little dirty work... But I don't have time to find a better solution.

Also, there's a new audit error that I have no idea:
```
icpz/collection/gnuradio:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/libgnuradio-runtime.3.8.1.0.dylib
      lib/libvolk.2.0.dylib
Error: 1 problem in 1 formula detected
```

Seems that these dylibs links with path under `/usr/local/opt`

**Pull request closed without merging**
