### PR TITLE
r 3.4.4

### PR DESCRIPTION
**Pull request by luispuerto**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by luisspuerto** [comment]
Hi! just today was released the new version... I did this pull with the command  `brew bump-formula-pr` and it's my first contribution here, so, I'll be clad to learn if something can be improved. 

😃

**Comment by fxcoudert** [comment]
`Stable: The URL http://cran.r-project.org/src/base/R-3/R-3.4.4.tar.gz should use HTTPS rather than HTTP`

**Comment by luisspuerto** [comment]
thanks @fxcoudert I knew but I just c&p from the info about the release they sent.

**Comment by fxcoudert** [comment]
Thanks @luisspuerto for the pull request!

**Pull request closed without merging**
