### PR TITLE
hwloc 2.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sthibaul** [comment]
Hello,
This is not really a good idea: hwloc 2 breaks the API compatibility. I have seen something like half of the Debian packages using hwloc break due to this.

**Comment by ilovezfs** [comment]
@sthibaul if upstream hwloc chooses to break their API, that's up to them. We won't refuse to release the current version of their software because someone doesn't agree with the API breakage.

**Comment by sthibaul** [comment]
It is not a question of agreeing on the API or not, it is really a different API. Think of it like gtk2 vs gtk3, or qt4 vs qt5. Nobody would "just release the new version of gtk" by merely replacing the gtk2 library by a gtk3 library, because it basically breaks everything.

**Comment by ilovezfs** [comment]
@sthibaul it doesn't break anything in homebrew/core so there's no issue here. If this affects some of your own projects, I suggest you update them to use the current API.

**Comment by sthibaul** [comment]
It's not only a question of my own projects, but also other projects (mpich, openmpi, etc.). Their users are using homebrew to pull hwloc, and then other projects' software break.

**Comment by ilovezfs** [comment]
@sthibaul that is normal. Those other projects then need to update to the latest API as well.

**Comment by sthibaul** [comment]
Sure, but leaving them time rather than releasing just days after the release would be more than welcome. As of now, they're broken until they make a release, which can take them some time depending on their agenda.

**Pull request closed without merging**
