### PR TITLE
ginac 1.7.2

### PR DESCRIPTION
**Pull request by hrjonashansen**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
The test fails now; mind looking into that? https://bot.brew.sh/job/Homebrew%20Core/14425/

**Comment by hrjonashansen** [comment]
Which compiler (and version) is used? It works using: g++ (Homebrew GCC 6.3.0) 6.3.0

**Comment by dunn** [comment]
https://github.com/Homebrew/homebrew-core/pull/8712/files#diff-104750301e51efc4d162601eb836db35R43

Does `brew test ginac` succeed for you locally?

**Comment by hrjonashansen** [comment]
I get the same error regardless of ginac version, the C++11 flag was missing before too.

**Comment by hrjonashansen** [comment]
Why is the lib compiled with g++ (installed through brew), but the test is compiled with clang++?

**Comment by dunn** [comment]
Someone who installs ginac via the precompiled binary might not have Homebrew's GCC installed.

**Comment by dunn** [comment]
Merged, thanks!

**Pull request closed without merging**
