### PR TITLE
flow-cli 0.26.0

### PR DESCRIPTION
**Pull request by devbugging**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — APPROVED** [review]
Thanks, @sideninja!

**Comment by sideninja** [comment]
@nandahkrishna the version tag was pointing to the wrong commit, how could we update the version 0.26.0 to point to the current commit? I've recreated the v0.26.0 tag in flow-cli repo but I'm not allowed to bump the formula anymore.

**Comment by nandahkrishna** [comment]
Was 0.26.0 retagged? The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says retagging is "the insane thing" to do, so generally an incremental tag would be welcome. For now, you could create a separate PR to change the `sha256` checksum and add `revision 1` to the formula – along with confirmation that the retag was intentional and not malicious.

**Comment by sideninja** [comment]
I will do another incremental tag to comply with best practices. Thank you for your reply.

**Pull request closed without merging**
