### PR TITLE
cdparanoia: Deprecate, fix buffer overrun

### PR DESCRIPTION
**Pull request by chrstphrchvz**
~~Pending merge of homebrew/formula-patches#885~~

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
If we're deprecating it we shouldn't be adding another patch that will never be upstreamed

**Comment by chrstphrchvz** [comment]
I appreciate the response, however this sentence in https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#deprecation gave me the opposite impression:
> Deprecated formulae should continue to be maintained by the Homebrew maintainers so they still build from source and their bottles continue to work (even if unmaintained upstream).

I will revise this PR to only deprecate unless told otherwise.

**Comment by carlocab** [comment]
We should follow the docs here, so updating the patch makes sense to me.

**Comment by chrstphrchvz** [comment]
I notice MacPorts already has patches to avoid needing `-Wno-implicit-function-declaration`: https://github.com/macports/macports-ports/commit/f210a6061bc53c746730a37922399c6de6d69cb7 . Can they be linked to directly or would they need to go through formula-patches?

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
The `cflags` workaround is ok, we are already doing this in other formulae.

**Pull request merged**
