### PR TITLE
awscli 1.14.1

### PR DESCRIPTION
**Pull request by twulf**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
It's only been a couple releases since we last upgraded this but thanks for the PR nonetheless.

**Comment by twulf** [comment]
@ilovezfs There are a decent number of new features being added since re:Invent is going on that users of this formula will not be able to take advantage of until it is updated. Please reconsider merging this.

https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst

**Comment by ilovezfs** [comment]
We'll update it at 1.14.10

**Comment by tomvachon** [comment]
@ilovezfs they seem to be rolling more semantically than before.  There have been 7 releases since 1.11.190.  If that holds true, shouldn't it be more like 1.14.3, 1.15.1 or 1.16.0?

**Comment by ilovezfs** [comment]
@tomvachon we'll see how it goes. We may end up needing to throttle by time instead of release number depending on their behavior. The nice thing about release number is that you don't have to go do a look up when exactly the last upgrade was, but we'll see.

**Comment by twulf** [comment]
@ilovezfs Not to be contrarion, but I'm curious as to the reasoning behind throttling. Why not always update to the latest version?

**Comment by ilovezfs** [comment]
Mainly because the formula has a bottle, so a maintainer has to manually pull it from the CLI (as opposed to merging it with the GitHub GUI) and the bottles occupy space on Bintray.

**Pull request closed without merging**
