### PR TITLE
folly: migrate to boneyard

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

`folly` is blocking the Boost 1.61.0 update (in #1200). No stable upstream releases have been created since August 2015 (almost a year ago) and discussion with upstream yielded that `master` is considered stable. Since this isn't helpful to us as a package manager, facebook/folly#424 didn't yield anything yet, and homebrew/head-only does no longer accept new formulae, we sadly need to boneyard `folly` to unblock the Boost update PR.

### CODE REVIEW

**Comment by bhamiltoncx** [comment]
Sorry about the delay. Folly will now be tagged automatically with weekly release tags in the form `vYYYY.MM.DD.XX`. You can revert this diff if you'd like so Homebrew users can use Folly again.

**Comment by DomT4** [comment]
I'd be fine with us reinstating `folly` if we're going to get regular releases back, but may be sane to wait for https://github.com/Homebrew/homebrew-core/pull/1200 to get done & then reinstate `folly` to avoid reintroducing it & immediately having to revision bump it for `boost`.

**Comment by UniqMartin** [comment]
I agree with @DomT4. Let's do it like this in the hopes we'll be shipping #1200 very soon. And thanks for reinstating the weekly release tags! I'm pretty sure we're not the only downstream project happy about this.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/3590

**Comment by UniqMartin** [comment]
Thanks, @DomT4! :heart: Was meaning to get to that, but have hardly been around lately.

**Comment by DomT4** [comment]
No worries! It hasn't proven _too_ much trouble to restore. Currently stuck on https://github.com/facebook/folly/issues/451, but looks good on El Cap at least.

**Pull request merged**
