### PR TITLE
postgresql@10 10.10

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
01:17:38 running bootstrap script ... 2019-08-11 06:17:37.046 BST [78065] FATAL:  could not create shared memory segment: No space left on device
01:17:38 2019-08-11 06:17:37.046 BST [78065] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
01:17:38 2019-08-11 06:17:37.046 BST [78065] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
01:17:38 	The PostgreSQL documentation contains more information about shared memory configuration.
01:17:38 child process exited with exit code 1
01:17:38 initdb: removing data directory "/private/tmp/postgresql@10-test-20190811-78007-arzde/test"
01:17:38 Error: postgresql@10: failed

**Comment by chenrui333** [comment]
image

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
No need to bump the revision of `libpqxx` here: the dependency is on `postgresql`, not `postgresql@10`.

**Comment by chenrui333** [comment]
ok, I will remove it then.

**Pull request closed without merging**
