### PR TITLE
Updated CppUTest version from 3.8 to 4.0

### PR DESCRIPTION
**Pull request by basvodde**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Updated from 3.8 to 4.0

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please squash your commits into one `cpputest 4.0`

**Comment by basvodde** [comment]
Sure, done.

**Comment by SMillerDev** [comment]
The squash is done, but could you also follow the commit naming convention I requested?

**Comment by basvodde** [comment]
Oki. Like now?

**Comment by SMillerDev** [comment]
Yes, thanks. Should be good to go when CI is done.

**Comment by basvodde** [comment]
Tnx

**Review by SMillerDev — DISMISSED** [review]
Thanks @basvodde! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by SMillerDev** [comment]
Could you rebase on master and tag me when you did?

**Comment by SMillerDev** [comment]
Nevermind, that was a bug in our tooling. Thanks for the PR

**Comment by basvodde** [comment]
Ok, tnx

**Comment by iMichka** [comment]
Looks like the release tag was moved:
> 2020-05-30T06:54:37.3842516Z [34m==>[0m [1mDownloading https://github.com/cpputest/cpputest/releases/download/v4.0/cpputest-4.0.tar.gz[0m
2020-05-30T06:54:37.3842838Z [31mError:[0m SHA256 mismatch
2020-05-30T06:54:37.3842972Z Expected: 81c4958a3ec20ebe87b2cb658c334d27496c715972ddb71262357f449a7c1df3
2020-05-30T06:54:37.3843101Z   Actual: 21c692105db15299b5529af81a11a7ad80397f92c122bd7bf1e4a4b0e85654f7
2020-05-30T06:54:37.3843476Z  Archive: /github/home/.cache/Homebrew/downloads/1cf6e771ecc22eb7719fa40bf58370ee565b89901ebc69f7d2e6e790f950ad96--cpputest-4.0.tar.gz

**Comment by basvodde** [comment]
Yes, some very stupid person (me!), released before accepting the pull-request that changed the release version in the autoconf and make file. Let me update this SHA asap and make a PR.

**Pull request closed without merging**
