### PR TITLE
rustfmt 1.7.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

continuing #152112

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[WARN] entry 4099 in symbol table refers to a non existing section, skipping
Error: An exception occurred within a child process:
  TypeError: no implicit conversion of nil into Integer
```

**Comment by chenrui333** [comment]
Give this PR another go after https://github.com/Homebrew/homebrew-core/pull/162122

**Comment by chenrui333** [comment]
same error with linux build cc @Bo98

**Comment by chenrui333** [comment]
```
  [WARN] entry 4099 in symbol table refers to a non existing section, skipping
  Error: An exception occurred within a child process:
    TypeError: no implicit conversion of nil into Integer
```

**Comment by Bo98** [comment]
The warning part is a Rust bug, `librustc_driver` contains a bad symbol:

```
 4099: 0000000000000000 15155 OBJECT  GLOBAL DEFAULT bad section index[ 49] rust_metadata_ru[...]
```

Given we're using nightly here, bugs are probably expected. This warning will likely display during a `brew install` too.

Patchelf itself shouldn't crash however. I have a fix for this but might take a few days to get through to a brew release.

**Comment by chenrui333** [comment]
- need https://github.com/david942j/patchelf.rb/pull/46

closing for now, will reopen later.

**Comment by chenrui333** [comment]
it is good now 🎉 thanks @Bo98!

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
