### PR TITLE
bartycrouch 4.15.0

### PR DESCRIPTION
**Pull request by Jeehut**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
install: .build/artifacts/swift-syntax/_InternalSwiftSyntaxParser.xcframework/macos-arm64_x86_64/lib_InternalSwiftSyntaxParser.dylib: No such file or directory
```

**Comment by alexdeem** [comment]
> The never ending story ... 😆
> 
> @alexdeem Any ideas?

I expect something to do with:
```
warning: /Users/brew/Library/org.swift.swiftpm/configuration is not accessible or not writable, disabling user-level cache features.
``` 

(later on the build errors due to a cached file being missing).

This feels more like a ci infrastructure issue than something with the codebase, but tbh I don’t have any experience with publishing to brew 🤷‍♂️

**Comment by Jeehut** [comment]
help wanted

**Comment by alebcay** [comment]
The problem is that SwiftPM is attempting to write into `~/Library/Caches/org.swift.swiftpm`. When building packages, Homebrew sandboxes the build process into a temporary directory; writes into other locations are not permitted.

Is there some way to tell SwiftPM to store and load caches in a custom location?

**Comment by Jeehut** [comment]
Closing this in favor of a new 4.15.1 release I'm about to push with this attempt to fix the issue: https://github.com/FlineDev/BartyCrouch/pull/280

**Pull request closed without merging**
