### PR TITLE
cspice 66

### PR DESCRIPTION
**Pull request by blogabe**
with updated homepage link

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
I'm a bit concerned by the unversioned URL here. Is there a versioned URL available? If not, we may need to remove this formula from Homebrew.

**Comment by blogabe** [comment]
Wow.  Serious clean up going on.  Best as I can tell is version number is listed on this webpage https://naif.jpl.nasa.gov/naif/toolkit.html

**Comment by blogabe** [comment]
Bump.  Really hope we can keep this as part of Homebrew.

**Comment by blogabe** [comment]
@ilovezfs So any decisions been made on using the unversioned URL since there is no versioned URL available?

**Comment by ilovezfs** [comment]
@blogabe let's use Bintray to mirror a versioned tarball.

**Review by ilovezfs — APPROVED** [review]

**Comment by blogabe** [comment]
Great.  Thanks.  Anything more I need to do here?

**Comment by ilovezfs** [comment]
@blogabe nope! Shipped :rocket: 

thanks for the PR!

**Pull request closed without merging**
