### PR TITLE
Minipro

### PR DESCRIPTION
**Pull request by DavidGriffith**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add formula for open source software for Minipro TL866xx chip programmers.

### CODE REVIEW

**Comment by SMillerDev** [comment]
That's a lot of commits that aren't in homebrew-core. Either rebase in this repo or make a pr to linuxbrew-core

**Comment by DavidGriffith** [comment]
> That's a lot of commits that aren't in homebrew-core. Either rebase in this repo or make a pr to linuxbrew-core

I don't know why all those commits are showing up like that for adding just one file.

**Comment by SMillerDev** [comment]
Because you're making a pull request to homebrew-core instead of linuxbrew-core using the latest commit in linuxbrew-core

**Comment by DavidGriffith** [comment]
So if I do a pull request to linuxbrew-core with this, that'll work?

**Pull request closed without merging**
