### PR TITLE
youtube-dl 2017.10.15.1

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
:tv:

**Comment by ilovezfs** [comment]
@zmwangx any thoughts on this https://github.com/macports/macports-ports/commit/7d99b8745ac13ccf48ea24d987f28a970b01d7a4 ?

**Comment by zmwangx** [comment]
@ilovezfs I can't think of a single reason why you'd want a global youtube-dl config. I'd say let's not carry a downstream patch that no user requested.

**Comment by ilovezfs** [comment]
:+1:

**Pull request merged**
