### PR TITLE
llvm: enable installing utils

### PR DESCRIPTION
**Pull request by tamird**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

See https://github.com/llvm-mirror/llvm/commit/c18ea8d96eaf7ccd8e69967b

### CODE REVIEW

**Comment by apjanke** [comment]
Test bot [build failed](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/949/) due to a failed `linkage --test creduce` check.

```
failed: brew linkage --test creduce

Stacktrace

        Missing libraries:
  /usr/local/opt/llvm/lib/libc++.1.dylib
```

Not caused by this PR; I can reproduce with the current `llvm`. It's only showing up now because `linkage --test` is a recently-added test step. Looks like an indication that we need to add `--with-libcxx` to `creduce`'s `depends_on "llvm"`.

**Comment by apjanke** [comment]
What's included in the LLVM utils? Is this maybe something we would want to enable by default?

**Comment by apjanke** [comment]
FYI, `creduce` is fixed in #615, so if you amend or rebase this, the build & test will work the next time it runs.

**Comment by tamird** [comment]
Rebased.

I don't know the exhaustive list of utils - the one I needed was FileCheck, which is used by the rust compiler. I'm not sure we should enable this by default, honestly.

**Comment by apjanke** [comment]
Okeedoke. Merging as-is.

Thank you for your contribution to Homebrew!

**Comment by tamird** [comment]
Thanks!

**Comment by UniqMartin** [comment]
> I don't know the exhaustive list of utils - the one I needed was FileCheck, which is used by the rust compiler. I'm not sure we should enable this by default, honestly.

We prefer to keep the list of options short and to provide good defaults. This formula is probably not the best example of this policy, but we'd like to improve. If you feel like spending a bit more time with this:

Build once with and once without this option, note down the build time, installed size, and probably make a list of stuff being installed using `find $(brew --cellar)/llvm`. Compare this data for both builds and if all of this indicates that building the utilities doesn't have a noticeable negative impact, remove the option and make it a default in a follow-up PR. That way more people will benefit from this change (and fewer people will have to build `llvm` from source just to get those utilities.) Thanks!

**Comment by tamird** [comment]
For the time being, building from source is the only way to get these utilities anyway, since the upstream commit in question is not even present until LLVM 3.7.

However, I do think "install everything" is probably a good default (in a post-3.7) world since that's what gets bottled and doesn't really have any downsides.

**Comment by apjanke** [comment]
Martin's probably right on this. (Also check the list of installed binaries to see if there are any command names likely to conflict with other stuff.)

Related FYI: A while ago I tried to get `with-clang` and `with-rtti` enabled by default, but wasn't able to make it work. https://github.com/Homebrew/legacy-homebrew/pull/48462. If you or someone else know LLVM better and are able to get those enabled by default too, that would be great. Having these be off by default is a bummer because some formulae depend on them, so people who install those dependents end up having to build LLVM from source instead of using a bottle.

**Comment by autosquid** [comment]
hi, this may be  a little off-optic: why openmp support is not build in with the `with-clang` option?

**Pull request closed without merging**
