### PR TITLE
libressl 2.6.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ilovezfs — COMMENTED** [review]
homepage is still pretending this doesn't exist http://www.libressl.org/

**Comment by ilovezfs** [comment]
https://github.com/libressl-portable/portable/issues/370

**Comment by fxcoudert** [comment]
> LibreSSL 2.6.4 released December 19th, 2017

**Comment by ilovezfs** [comment]
And yet https://www.libressl.org says 2.6.3 is stable.

**Comment by DomT4** [comment]
It's been updated now.

**Comment by ilovezfs** [comment]
Nope. https://www.libressl.org/ still says

> The latest stable release is 2.6.3

**Comment by DomT4** [comment]
Oh, you're correct. I'm reading the wrong chunk of the website. Sorry 🙈.

**Comment by ilovezfs** [comment]
We could just pretend that sentence isn't there. But somehow that offends my sense of decency.

**Comment by ilovezfs** [comment]
OK, I think we've learned that they don't pay any attention to their issue tracker.

**Comment by ilovezfs** [comment]
OK that line has been updated. I feel better now.

**Comment by fxcoudert** [comment]
Breathe @ilovezfs :)

**Pull request closed without merging**
