### PR TITLE
dagger 0.2.23

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by gerhard** [comment]
How does this formula get bumped @chenrui333 & @SMillerDev?

We released https://github.com/dagger/dagger/releases/tag/v0.2.24 yesterday, but I am not seeing a new PR for `0.2.24` and I'm wondering how this is wired. GoReleaser running part of [our weekly auto-release went through just fine](https://github.com/dagger/dagger/runs/7413831657?check_suite_focus=true#step:8:360), as did [dagger/homebrew-tap](https://github.com/dagger/homebrew-tap/commit/cc6317d4ed187a41ec64678c5c4e0499ef56b449).

Thanks!

cc @marcosnils

**Comment by SMillerDev** [comment]
A human runs `brew bump --open-pr dagger` and that creates a bump.

**Comment by gerhard** [comment]
I see! Should we add this to our pipeline?

Since this is part of https://github.com/dagger/dagger/actions/workflows/auto-release.yml, I would be tempted to add it there. WDYT @SMillerDev?

**Comment by SMillerDev** [comment]
There is a `bump-formula-pr` github action that can do it.

**Comment by jpadams** [comment]
`HOMEBREW_DEVELOPER=1 brew bump-formula-pr dagger` perhaps

**Pull request closed without merging**
