### PR TITLE
qmmp 2.0.4

### PR DESCRIPTION
**Pull request by cho-m**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by cho-m** [comment]
Linux still needs `projectm` to attempt bottling. Will try bottling in #98440

**Comment by danielnachun** [comment]
I think this will also need `musepack`, whose bottling status on Linux is still uncertain: https://github.com/Homebrew/homebrew-core/pull/96781.

**Comment by cho-m** [comment]
> I think this will also need `musepack`, whose bottling status on Linux is still uncertain: #96781.

I moved `musepack` to macOS dependency. If it complains, we can force disable via `-DUSE_MPC`

**Comment by cho-m** [comment]
Rebased to see Linux build. Guessing it may fail due to `-Wl,-undefined,dynamic_lookup`.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
