### PR TITLE
grc: remove `bottle :unneeded`.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
It should have an identical checksum on all platforms.

### CODE REVIEW

**Comment by carlocab** [comment]
All Intel bottles the same, but ARM differs. Prefix-replacement related, in `bin/grc`:
```diff
--- grc--1.12.big_sur.bottle.tar.gz
+++ grc--1.12.arm64_big_sur.bottle.tar.gz
@@ -83,15 +83,15 @@
 
 if cfile == "":
     home = os.environ.get('HOME')
     xdg  = os.environ.get('XDG_CONFIG_HOME')
     if not xdg and home:
         xdg = home + '/.config'
 
-    conffilenames = ['@@HOMEBREW_PREFIX@@/etc/grc.conf', '@@HOMEBREW_PREFIX@@@@HOMEBREW_PREFIX@@/etc/grc.conf']
+    conffilenames = ['@@HOMEBREW_PREFIX@@/etc/grc.conf', '/usr/local@@HOMEBREW_PREFIX@@/etc/grc.conf']
     if xdg:
         conffilenames += [xdg + '/grc/grc.conf']
     if home:
         conffilenames += [home + '/.grc/grc.conf']
 
     for conffile in conffilenames:
         # test if conffile exists, it can be also a pipe
```

**Comment by Bo98** [comment]
That looks like a bug with our `inreplace` lines.

**Comment by carlocab** [comment]
Yep, this is caused by the `inreplace` for `grc`.

https://github.com/Homebrew/homebrew-core/blob/a66ad3db4ba2bce08c8418a676374572f68f1357/Formula/grc.rb#L19-L20

This is the relevant line in `grc` before the `inreplace`.

```python3
    conffilenames = ['/etc/grc.conf', '/usr/local/etc/grc.conf']
```

**Comment by MikeMcQuaid** [comment]
Pushed `inreplace` fix in 51941d12ef

**Comment by carlocab** [comment]
Fixed:
```
❯ sha256sum *.tar.gz
8853ca1088ea0598d4eed82cae88748f677372487ed1794b1e0ee564d2c1b783  grc--1.12.arm64_big_sur.bottle.tar.gz
8853ca1088ea0598d4eed82cae88748f677372487ed1794b1e0ee564d2c1b783  grc--1.12.big_sur.bottle.tar.gz
8853ca1088ea0598d4eed82cae88748f677372487ed1794b1e0ee564d2c1b783  grc--1.12.catalina.bottle.tar.gz
8853ca1088ea0598d4eed82cae88748f677372487ed1794b1e0ee564d2c1b783  grc--1.12.mojave.bottle.tar.gz
```

**Pull request closed without merging**
