### PR TITLE
clang-format: set CMAKE_OSX_SYSROOT=/ for CLT only

### PR DESCRIPTION
**Pull request by ilovezfs**
Closes https://github.com/Homebrew/homebrew-core/issues/3347.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @DomT4

**Comment by DomT4** [comment]
👍. Hopefully this is one of the things we can kill off once `scons` plays nicely under `superenv`.

**Comment by ilovezfs** [comment]
> Hopefully this is one of the things we can kill off once scons plays nicely under superenv.

Do we have an open issue or PR for that currently?

**Comment by DomT4** [comment]
No. Think we used to have one in `legacy`. It's something @mistydemeo knows the most about, but Misty isn't around much for now.

**Pull request closed without merging**
