### PR TITLE
sqlite: build regexp extension

### PR DESCRIPTION
**Pull request by smammy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
    - `brew audit --strict` complains about a changed sha256sum. I explain this below.

-----

This commit enables the building the SQLite regexp extension, which allows users
to use SQLite's non-standard REGEXP operator in SELECT statements. Users must
take positive action to load the extension, so there is little danger of
regressions for users who don't care to use it.

I attempt to address the concerns raised in Homebrew/legacy-homebrew#26354 by
using the implementation that is included in the SQLite source code, rather than
[a third-party implementation](https://github.com/ralight/sqlite3-pcre/).

Unfortunately, this means that this formula can no longer use the "autoconf
amalgamation" download of the SQLite source code, as it does not which include
the regexp extension. Instead, we must download the full tarball. This changes
the sha256sum without a version bump, which annoys `brew audit`. I hope this is
acceptable.

I added caveats describing how to load the extension and where to find docs on
the regular expression syntax that it supports (which is a subset of PCRE).

### CODE REVIEW

**Comment by fxcoudert** [comment]
It needs to be built manually (it's not built by default), installed manually, it's documented only inside the source code, and users need to load it manually. Sounds like we simply shouldn't ship it, really.

Are there other known distros/packages that distribute it? What do Debian and others do?

**Comment by smammy** [comment]
> It needs to be built manually (it's not built by default), installed manually, it's documented only inside the source code, and users need to load it manually.

Sounds like a perfect job for Homebrew, to be honest! It'd be a bit difficult for end-users to sort it all out, so why not automate it?

> Are there other known distros/packages that distribute it? What do Debian and others do?

I will check and get back to you.

**Comment by smammy** [comment]
Debian doesn't build the bundled `ext/misc/regexp.c` extension. It does include a [separate package](https://tracker.debian.org/pkg/sqlite3-pcre) for Alexey Tourbin's [sqlite3-pcre](http://git.altlinux.org/people/at/packages/?p=sqlite3-pcre.git).

I did submit formula for this extension in #37150, but then decided that using first-party code would be better than an apparently-unmaintained, head-only, third-party implementation.

The way I see it there are three ways forward:
1. Modify the `sqlite` formula to build the bundled `ext/misc/regexp.c` extension (as in this PR).
2. Create a separate formula (e.g. `sqlite3-pcre`) that will build Alexey Tourbin's `sqlite3-pcre` extension (as in #37150).
3. Create a separate formula (e.g. `sqlite-regexp`) that will build the bundled `ext/misc/regexp.c` extension separately.

I'm leaning towards number 3 myself, since it doesn't require any modification to the `sqlite` formula and also doesn't pull in any potentially-worrisome third-party code.

Let me know how you'd like me to proceed.

**Comment by fxcoudert** [comment]
#1 does not seem appropriate, I'd say start with #3 and if there is an important number of users, contribute that formula to Homebrew core. Thanks again @smammy for opening this PR and starting this discussion.

**Pull request closed without merging**
