### PR TITLE
sbcl 2.2.9

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Catalina failed at building SBCL. No idea about the error though.

**Comment by cho-m** [comment]
Upstream issue https://bugs.launchpad.net/sbcl/+bug/1991485

**Comment by carlocab** [comment]
Upstream have a patch: https://sourceforge.net/p/sbcl/sbcl/ci/171cef936ad8

**Comment by metayan** [comment]
A working `sbcl` formula using the mentioned patch is at
https://github.com/metayan/homebrew-core/blob/sbcl-2.2.9-temp/Formula/sbcl.rb

It is also updated to use the correct build flags (`--fancy`) and can even make use of an already installed SBCL for cross-compilation. (Building with ECL takes around half an hour, while with SBCL it takes around two minutes.)

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
