### PR TITLE
openssl 1.0.2i

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by alex** [comment]
Build timed out, someone from the homebrew team will need to whitelist.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by alex** [comment]
Failing tests don't look to have been caused by this PR.

**Comment by DomT4** [comment]
No, it's mostly the usual unlink/link/too much linking to handle in one build garbage. The `conan` failing test is interesting & should probably be double-checked after this is merged shortly, but everything else is expected.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/8ed8cde887f36047438813d3014a44d9a4a05df6. Thanks again @alex! 😺

**Pull request closed without merging**
