### PR TITLE
flake8 2.6.2

### PR DESCRIPTION
**Pull request by sigmavirus24**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by sigmavirus24** [comment]
```
+ brew update
Already up-to-date.
+ brew test-bot --ci-pr
HEAD is now at cab97cf Revert "keg_relocate: Exclude hardlinks from mach_o_files."
Already on 'master'
==> git checkout origin/master
==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/2460
==> FAILED
fatal: ref HEAD is not a symbolic ref
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/2460.patch
Error: Failure while executing: /usr/bin/curl --fail --progress-bar --remote-time --location --user-agent Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.9.5)\ curl/7.30.0 https://github.com/Homebrew/homebrew-core/pull/2460.patch -s -o /Users/brew/Library/Caches/Homebrew/2460.patch --silent
```

I'm not sure why that fails on Mavericks. Can someone with more context/experience help me fix this?

**Comment by DomT4** [comment]
GitHub has had some issues today unrelated to Homebrew itself. It's back in the CI queue, and should hopefully pass this time.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/8d48c4e4fa5b4a6abe413227471a12992a7c95f3. Thank you for your contribution to Homebrew @sigmavirus24; we appreciate it! :smiley_cat:

**Comment by sigmavirus24** [comment]
You're very welcome @DomT4!

**Pull request closed without merging**
