### PR TITLE
megatools: update curl dep

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by Bo98** [comment]
Given this is removing a dependency, it probably needs new bottles otherwise we'd be installing bottles linked to Homebrew curl without having a curl dependency.

**Comment by fxcoudert** [comment]
I'm not sure whether it's linked or simply using the binary. But in any case, new bottles don't hurt.

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
> Given this is removing a dependency, it probably needs new bottles otherwise we'd be installing the original bottles linked to Homebrew curl without having a curl dependency.

yeah, it is not linked for osx builds, but new bottle does not hurt though.

**Comment by Bo98** [comment]
> I'm not sure whether it's linked or simply using the binary. But in any case, new bottles don't hurt.

Existing bottle does link:

```
==> brew linkage --cached megatools
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /opt/homebrew/opt/curl/lib/libcurl.4.dylib (curl)
  /opt/homebrew/opt/gettext/lib/libintl.8.dylib (gettext)
  /opt/homebrew/opt/glib/lib/libgio-2.0.0.dylib (glib)
  /opt/homebrew/opt/glib/lib/libglib-2.0.0.dylib (glib)
  /opt/homebrew/opt/glib/lib/libgobject-2.0.0.dylib (glib)
  /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib (openssl@3)
  /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib (openssl@3)
Indirect dependencies with linkage:
  gettext
Dependencies with no linkage:
  glib-networking
```

**Pull request merged**
