### PR TITLE
teleport: enable Touch ID support on macOS

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Upstream leave this off by default to avoid breaking their cross-builds.
We don't do cross-compilation so we can enable this.

Additionally,
1. Fix the `version` output to show the Git tag instead of a
   non-existent Git hash
2. Fix finding the `pam_appl.h` header on macOS.
3. Set `BUILDDIR` to `bin` so that we don't need to do `bin.install`.

### CODE REVIEW

**Comment by carlocab** [comment]
> The header fix looks like it should go upstream.

Yea, thought you'd say that. Making it cross-platform is a bit annoying though. Let me see if I can figure out an upstreamable patch.

**Comment by SMillerDev** [comment]
If you can't make it work as a patch you can always create an issue.

**Comment by carlocab** [comment]
https://github.com/gravitational/teleport/pull/14558

**Review by SMillerDev — DISMISSED** [review]

**Comment by zmb3** [comment]
TouchID support requires that the app is signed and notarized, so I don't think this will be enough.

**Comment by codingllama** [comment]
Zac is correct, touch ID needs a signed and notarized app. Not only that, you need an Apple Developer Program account to get Secure Enclave access, a free account won't cut it. Sadly, touch ID support would require a cask.

I've just opened #106359, which enables libfido2 support for Teleport. It's not touch ID, but you can get passwordless via YubiKeys and the like with it.

**Comment by SMillerDev** [comment]
@carlocab can you rebase this one?

**Review by SMillerDev — APPROVED** [review]

**Comment by codingllama** [comment]
Hey folks, upstream dev here. Just to reiterate, this is not sufficient to enable Touch ID, you need notarization for that. You won't get much out of this PR, apart from a slightly more complex build process.

**Comment by carlocab** [comment]
🤷 seemed to worked fine for me when I gave it a very brief test before I opened this PR.

Do you need to notarise teleport for touch ID to work even when you build it from source yourself locally?

**Comment by codingllama** [comment]
@carlocab yes, I need to either sign/notarize or sign and install a provisioning profile to test locally, both of which require access to Teleport-owned private keys (which I obviously can't share).

The binary will work, but Touch ID won't. Try doing `tsh mfa add --type=TOUCHID` and you'll see it isn't enabled.

A free Apple Developer account won't cut it either, and even if you get a payed account and sign/notarize it, the keys you create with this binary won't interact with official Teleport products because it would be a different account.

If we could make Touch ID work for the Brew version I'd be all for it, but sadly it isn't this easy.

**Pull request closed without merging**
