### PR TITLE
mkvtoolnix 42.0.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
only failed on HighSierrra

checking for support for C++17 feature "std::optional"... no
The following features of the C++11/C++14/C++17 standards are not supported by clang++:
  * std::optional (C++17)
If you are using the GNU C compiler collection (gcc), you need
at least v7; for clang v4 and newer should work.
configure: error: support for required C++11/C++14/C++17 features incomplete

**Comment by alebcay** [comment]
I'm confused by this error. The `clang` version on the High Sierra CI is based on `clang v5` (Xcode 10), which should have full ISO C++17 support.

**Comment by dawidd6** [comment]
Maybe build depend on `llvm` formula?

**Comment by EricFromCanada** [comment]
I read somewhere that 10.13 has full C++17 language support, but not full library support. What seems to work so far is:
1. add `depends_on "llvm" if DevelopmentTools.clang_build_version < 1100`
2. conditionally add `llvm` to the `features` array so the formula uses its `libc++`

**Comment by alebcay** [comment]
Would the `llvm` dependency be `=> :build` or not?

**Comment by EricFromCanada** [comment]
Probably not, but currently getting `ld: library not found for -lmtxcommon`.

**Comment by alebcay** [comment]
I was seeing that too after I added `fails_with :clang if MacOS.version <= :high_sierra`, which is why I added the `fails_with :gcc` line, which evidently does not work.

**Pull request closed without merging**
