### PR TITLE
qt@5 5.15.15

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
After current run finishes, will try adding https://invent.kde.org/qt/qt/qtlocation-mapboxgl/-/commit/35d566724c48180c9a372c2ed50a253871a51574 to fix Linux

**Comment by ipatch** [comment]
is there any chance y'all (homebrew maintainers) would include the following patch file in this updated qt version? it'd allow building pyside2 against python3.12.

https://github.com/OpenMandrivaAssociation/qt5-qtbase/blob/master/qtbase-5.15.9-work-around-pyside2-brokenness.patch

**Comment by Bo98** [comment]
That's really a Pyside bug and that's where we fixed that issue:

https://github.com/Homebrew/homebrew-core/blob/c3038fc3c41d6fb52e06ca90656a638ecde94a9c/Formula/p/pyside@2.rb#L54-L65

**Comment by cho-m** [comment]
Newer LLVM support part is patched in.

Python 3.12 support may also be possible with Debian or another repositories patches.

Debian's patches require building without `FORCE_LIMITED_API` as they backported in `_PepRuntimeVersion()` usage:

https://sources.debian.org/patches/pyside2/5.15.14-1/Support-running-PySide-on-Python-3.12.patch/#L176

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
