### PR TITLE
libdnet 1.14

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why does upstream change?

**Comment by gromgit** [comment]
GitHub actually redirects the original homepage to https://github.com/ofalk/libdnet, which is consistent with the new tarball URL. (@chenrui333 , probably a good idea to update the homepage too.)

As for the complete change in URL, it's probably related to the existing release being done in 2007, eight years before Google Code sent out a closure notice: https://github.com/ofalk/libdnet/issues/34

**Comment by claui** [comment]
> probably a good idea to update the homepage too.

I concur. `homepage` needs an update.

**Comment by chenrui333** [comment]
Good point, updating the url now.

**Review by claui — APPROVED** [review]

**Pull request closed without merging**
