### PR TITLE
gdrive-downloader

### PR DESCRIPTION
**Pull request by Freed-Wu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — CHANGES_REQUESTED** [review]
This does not pass `brew audit --new`:
```
❯ brew audit --new gdrive-downloader
gdrive-downloader:
  * 2: col 59: Description shouldn't end with a full stop.
  * 4: col 3: Formulae in homebrew/core should specify a revision for git URLs
  * 4: col 3: Formulae in homebrew/core should specify a tag for git URLs
  * 7: col 3: `license` (line 7) should be put before `head` (line 6)
Error: 4 problems in 1 formula detected
```
Please don't mark items in the PR template as done if you did not do them.

The lack of a Git tag makes this unacceptable for Homebrew/core. See https://docs.brew.sh/Acceptable-Formulae#stable-versions.

**Comment by Freed-Wu** [comment]
> The lack of a Git tag makes this unacceptable for Homebrew/core

Okay :smile:

**Comment by Akianonymus** [comment]
> > The lack of a Git tag makes this unacceptable for Homebrew/core
> 
> Okay smile @Akianonymus Can a git tag be added?

There you go.

https://github.com/Akianonymus/gdrive-downloader/releases/tag/v1.0

I didn't do it before because every commit felt like a significant change and would be a hassle to create new release everytime. Bleeding edge forever, xD.

Anyway, i will probably make new releases now and then. Also thank you for adding it to homebrew ( i am too lazy to even pr ), i don't use but probably will be helpful to many.

**Comment by Freed-Wu** [comment]
Okay, can we reopen this pr? Thanks!

**Pull request closed without merging**
