### PR TITLE
grafana 6.6.0

### PR DESCRIPTION
**Pull request by alexanderzobnin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on catalina build

```
==> brew test grafana --verbose
==> FAILED
Testing grafana
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200127-64068-dtetvg.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/grafana.rb --verbose
==> /usr/local/Cellar/grafana/6.6.0/bin/grafana-server -v
/usr/local/Cellar/grafana/6.6.0/bin/grafana-server: /usr/local/Cellar/grafana/6.6.0/bin/grafana-server: cannot execute binary file
Error: grafana: failed
Failed executing:
```

**Comment by SMillerDev** [comment]
this works for me locally, seems to be the apfs bug. @fxcoudert ideas?

**Comment by alexanderzobnin** [comment]
@SMillerDev how can I test it on my local machine? Could you point me to some instructions or docs?

**Comment by SMillerDev** [comment]
It works now. But you could pull the change with https://docs.brew.sh/Manpage#pull-options-patch

**Comment by SMillerDev** [comment]
Thanks @alexanderzobnin! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
