### PR TITLE
node 16.0.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by carlocab — CHANGES_REQUESTED** [review]
You can update `npm` to 7.10.0.

See https://github.com/nodejs/node/releases/tag/v16.0.0, https://github.com/nodejs/node/pull/38254

**Comment by carlocab** [comment]
There are three failures: `bcoin`, `cash-cli`, and `jhipster`. `bcoin` and `cash-cli` look unrelated. (e.g. #75622)

`jhipster` looks like it could be fixed by depending on `node@15` instead (c/o #75598). However, if there's an upstream patch we can use to get `jhipster` to work with this version of Node we should probably use that.

**Comment by chrmoritz** [comment]
```
Error: Module did not self-register: '/usr/local/Cellar/bcoin/2.1.2_2/libexec/lib/node_modules/bcoin/node_modules/bcrypto/build/Release/bcrypto.node'.
```

`bcoin` just needs a revision bump, because of the native addon I think.

**Comment by carlocab** [comment]
`cash-cli` is definitely just broken (#75709). `jhipster` fixed in #75637. Switched `bcoin` to `node@14` in #75704, so this can be merged as soon as #75704 is.

Or we can try giving `bcoin` revision bump here, but that sounds a little speculative to me at the moment.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks @branchvincent!

**Comment by carlocab** [comment]
@chrmoritz: you were right about `bcoin`: #75714 thanks for the hint!

**Pull request closed without merging**
