### PR TITLE
stress 1.0.6

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by vbendel** [comment]
Can you test with [commit](https://github.com/vbendel/stress/commit/7ae7ebe50f389054f5a78873867b5eef92b8cf97) on top? (I don't have an OSX build env)
Feel free to grab a checkout from my [fork](https://github.com/vbendel/stress). I'll submit a pull request only once confirmed it fixes this problem.

**Comment by p-linnane** [comment]
@vbendel Thanks for the patch. Unfortunately it does not apply cleanly. There appear to have been some changes to `src/stress.c` that have not made it into your fork.

**Comment by chenrui333** [comment]
let me give a shot.

**Comment by p-linnane** [comment]
Just pushed a commit where I applied the changes to the current release. It built and tested successfully.

**Comment by chenrui333** [comment]
> Just pushed a commit where I applied the changes to the current release. It built and tested successfully.

Shit, we did exactly the same thing (but I added some code comments). 👍

**Comment by chenrui333** [comment]
@vbendel can you PR that change for the next release? Thanks!

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
