### PR TITLE
gitg 44

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
```
  ../libgitg/gitg-stage.vala:473.17-473.49: error: The name `create_commit_buffer' does not exist in the context of `Gitg.Repository'
    473 | 					var data = d_repository.create_commit_buffer(author,
        | 					           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        
  ../libgitg/gitg-stage.vala:487.12-487.52: error: The name `create_commit_with_signature' does not exist in the context of `Gitg.Repository'
    487 | 					ret = d_repository.create_commit_with_signature(data, signature, null);
        | 					      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     
```

**Comment by ZhongRuoyu** [comment]
These functions were added in https://github.com/GNOME/libgit2-glib/commit/7f36e18f41e0b28b35c85fe8bf11d844a0001305. They are not included in the latest `libgit2-glib` release (v1.1.0).

**Comment by ZhongRuoyu** [comment]
```
  ==> Testing gitg
  ==> /opt/homebrew/Cellar/gitg/44/bin/gitg --version
  Error: gitg: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /44/ to match "gitg 45.alpha\n".
```

https://gitlab.gnome.org/GNOME/gitg/-/issues/411

**Comment by chenrui333** [comment]
Thanks @ZhongRuoyu!

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
