### PR TITLE
lua 5.3.6

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adding a lua@5.3 formula to try to address build failures in
https://github.com/Homebrew/homebrew-core/pull/57133

Not sure if this is going to work, but I figured that it couldn't hurt.

The tap syntax test blocks the build tests, but this does build for
me locally on Big Sur. The only changes I've made relative to the
existing lua formula is a version bump to 5.3.6.

[lua.patch.txt](https://github.com/Homebrew/homebrew-core/files/5620121/lua.patch.txt)

### CODE REVIEW

**Comment by fxcoudert** [comment]
This needs to be coordinated with #57133 in the same PR.

**Comment by carlocab** [comment]
I did try doing both in the same PR, but it seems to have tripped up the test bot: https://github.com/Homebrew/homebrew-core/pull/65976

Not sure if I did something wrong though.

**Comment by fxcoudert** [comment]
@carlocab I've commented on that PR, you can fix the symlink and it should work fine

**Comment by carlocab** [comment]
Not sure if there's something wrong with my browser, but I can't see your comment.

In any case, ok. Let me try that again.

**Pull request closed without merging**
