### PR TITLE
Remove Gobject-introspection rpath patches

### PR DESCRIPTION
**Pull request by tschoonj**
No longer necessary since gobject-introspection has been fixed...

### CODE REVIEW

**Comment by tschoonj** [comment]
See also #38790 and #38779

**Comment by kleisauke** [comment]
Perhaps https://github.com/Homebrew/homebrew-core/blob/9e64f0318f85c12ce363d6dfe72d3077446e8e2f/Formula/poppler.rb#L74-L78 could be removed as well?

**Comment by tschoonj** [comment]
Yep, done!

**Comment by kleisauke** [comment]
And
https://github.com/Homebrew/homebrew-core/blob/9e64f0318f85c12ce363d6dfe72d3077446e8e2f/Formula/libsoup.rb#L32-L35
https://github.com/Homebrew/homebrew-core/blob/37f4aa7c45e87ec774bb9e0de55c7c57bf4aa51a/Formula/libdazzle.rb#L31-L33?

**Comment by tschoonj** [comment]
`libsoup` is in a separate PR I opened earlier today: #38779

**Comment by tschoonj** [comment]
@fxcoudert any idea what's going on Jenkins? 

This PR can actually be merged as is, since there is no need to update the bottles.

**Comment by fxcoudert** [comment]
@tschoonj yes CI is a mess right now… merging

**Pull request merged**
