### PR TITLE
Fixed updated 2.13 head SHA.

### PR DESCRIPTION
**Pull request by tillt**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This has to be reported to, and explained by, upstream before we merge it, in order to rule out malicious circumstances.

**Comment by tillt** [comment]
https://github.com/Andersbakken/rtags/issues/1040

**Comment by tillt** [comment]
@ilovezfs please see https://github.com/Andersbakken/rtags/issues/1040#issuecomment-325402069

**Comment by ilovezfs** [comment]
@tillt Thanks. Since it was about fixing a significant bug, the revision should be bumped as well.

**Pull request closed without merging**
