### PR TITLE
flow 0.94.0

### PR DESCRIPTION
**Pull request by skeet70**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by skeet70** [comment]
Thanks @mroch for the fix it seems to have worked. To get the missing versions between .94 and .81 on Homebrew I'd assume changes to the ocaml version used in the formula would need to be made for those tags?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please, again

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by skeet70** [comment]
Looks like tests passed.

**Comment by fxcoudert** [comment]
Thanks @skeet70, merging this

**Pull request closed without merging**
