### PR TITLE
cockroach 1.0.2

### PR DESCRIPTION
**Pull request by mberhault**

### CODE REVIEW

**Comment by mberhault** [comment]
@benesch: can you take a look?

**Comment by ilovezfs** [comment]
The link to the source tarball on https://www.cockroachlabs.com/docs/install-cockroachdb.html still seems to indicate 1.0.1 is the latest stable released version.

**Comment by mberhault** [comment]
Yup, we're in the process of announcing the release: https://github.com/cockroachdb/docs/pull/1541
We expect to merge this around the time the release notes are published, the tarball has already been pushed (see the preview link in the docs PR).

**Comment by ilovezfs** [comment]
@mberhault Cool. I assume you'll want the homepage to reference the new version before we ship this?

**Comment by mberhault** [comment]
Definitely. We try to get the release notes published on our site and announced through our various channels before bumping the version everywhere. This should be done within a few hours, at which point this can be merged.
Shall I ping here when we're ready?

**Comment by ilovezfs** [comment]
Yup. That would be great.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
wait for upstream to give the go ahead

**Comment by mberhault** [comment]
Release notes are out: https://www.cockroachlabs.com/docs/v1.0.2.html
This is now good to merge on our end.

Thank you.

**Review by ilovezfs — APPROVED** [review]

**Comment by benesch** [comment]
(Also LGTM, for what it's worth.)

**Comment by ilovezfs** [comment]
Thanks for the pull request @mberhault. Shipped!

**Pull request closed without merging**
