### PR TITLE
hashcat: fix metal library detection, skip OpenCL on virtualized ARM

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Superseding #181921 for working on test failure on CI.

EDIT: cherry-picked commit from other PR and thus closes #181921

---

Needs a new bottle due to attestation

### CODE REVIEW

**Comment by carlocab** [comment]
Do you not need the patch from #181921?

**Comment by cho-m** [comment]
> Do you not need the patch from #181921?

Maybe. Locally, I can install existing Monterey bottle and it finds Metal but may have some issues with recent builds
```console
❯ hashcat_bin --benchmark -m 0 -D 1,2 -w 2 --backend-ignore-opencl
hashcat (v6.2.6) starting in benchmark mode

METAL API (Metal 343.21)
========================
...

-------------------
* Hash-Mode 0 (MD5)
-------------------

Speed.#1.........:  1519.7 MH/s (9.93ms) @ Accel:512 Loops:128 Thr:32 Vec:1
```

---

Could be that `__METAL_MACOS__` was only defined on older Xcode.

There are still remnants of macro usage in Xcode.app though none in CLT:
```console
❯ rg __METAL_MACOS__ /Applications/Xcode.app/Contents/Developer/**/macos
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/32023.155/include/metal/metal_stdlib
39:#if defined(__METAL_MACOS__) && !defined(__METAL__)
67:#endif // __METAL_MACOS__

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/32023.155/include/metal/metal_config
598:#ifdef __METAL_MACOS__
1170:#endif // __METAL_MACOS__
```

**Review by carlocab — APPROVED** [review]

**Comment by cho-m** [comment]
Still can't find any devices. Locally, I can confirm:

* Old ARM Monterey bottle works
* Source build w/o patch fails to find Metal
* Source build w/ patch finds Metal

I think we have Metal on CI given other formulae like:
https://github.com/Homebrew/homebrew-core/blob/a9ae5dc950ca4d055f5f0f02b9ebbd8f9910728c/Formula/v/vulkan-profiles.rb#L70-L71

---

May need to see what code path to reach Metal detection is and what version of Metal is on runners.

**Comment by Bo98** [comment]
Well it's not printing `clGetDeviceIDs(): CL_INVALID_VALUE` anymore at least so this is progress.

> Could be that `__METAL_MACOS__` was only defined on older Xcode.

It was a Metal 3.0 change. I think `__METAL_VERSION__` technically covers both old and new but if it's an upstream patch then we'll use that upstream have.

**Comment by cho-m** [comment]
Might just have to check failure or `--help` or `--version`.

Not sure if `MTLCreateSystemDefaultDevice()` is available. At least wasn't back in https://github.com/actions/runner-images/issues/1779

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
