### PR TITLE
rust 1.68.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Was attempting https://github.com/Homebrew/homebrew-core/labels/openssl-3-migration. It seems that `cargo-outdated` is the only blocker:

```
$ rg '^\s*depends_on "rust"$'    
Formula/cargo-zigbuild.rb
20:  depends_on "rust"

Formula/cargo-bloat.rb
21:  depends_on "rust"

Formula/cargo-outdated.rb
21:  depends_on "rust"

Formula/maturin.rb
20:  depends_on "rust"

Formula/cargo-llvm-lines.rb
19:  depends_on "rust"
$ brew deps --tree cargo-zigbuild cargo-bloat cargo-outdated maturin cargo-llvm-lines
cargo-bloat
└── rust
    ├── openssl@1.1
    │   └── ca-certificates
    └── pkg-config

cargo-llvm-lines
└── rust
    ├── openssl@1.1
    │   └── ca-certificates
    └── pkg-config

cargo-outdated
├── libgit2
│   └── libssh2
│       └── openssl@1.1
│           └── ca-certificates
├── openssl@1.1
│   └── ca-certificates
└── rust
    ├── openssl@1.1
    │   └── ca-certificates
    └── pkg-config

cargo-zigbuild
├── rust
│   ├── openssl@1.1
│   │   └── ca-certificates
│   └── pkg-config
└── zig
    ├── z3
    └── zstd
        ├── lz4
        └── xz

maturin
└── rust
    ├── openssl@1.1
    │   └── ca-certificates
    └── pkg-config
```

**Comment by Porkepix** [comment]
This other formula is also compatible with OpenSSL 3.
Also, maybe rust could be switched as build dependency only there, and is Openssl still required on every OS for that dependents?

**Comment by ZhongRuoyu** [comment]
> is Openssl still required on every OS for that dependents?

Supposedly yes (and its dependency `libgit2` needs it too). But it seems that it's already using a vendored `libgit2`. Mmm.

**Comment by Porkepix** [comment]
> > is Openssl still required on every OS for that dependents?
> 
> Supposedly yes (and its dependency `libgit2` needs it too). But it seems that it's already using a vendored `libgit2`. Mmm.

Both `libgit2` and `openssl` can be used vendored from the repository I think. But homebrew's maintainer's policy is to use the dependency from homebrew's formulas when they exist rather than vendored ones.

**Comment by ZhongRuoyu** [comment]
Actually, `cargo-outdated` looks fine as it only requires [`git2-curl`](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L34), which [does not opt in to the `vendored-libgit2` feature](https://github.com/rust-lang/git2-rs/blob/master/git2-curl/Cargo.toml#L19) so there were really no linkage.

But I missed some more dependencies (I updated the original list). And among those, `cargo-edit` *is* linked to `libgit2` (https://github.com/Homebrew/homebrew-core/pull/124404).

**Comment by ZhongRuoyu** [comment]
As for `cargo-edit`, before we make its dependency `libgit2` depend on `openssl@3`, maybe we can temporarily get rid of the audit failure by adding it to [`versioned_dependencies_conflicts_allowlist.json`](https://github.com/Homebrew/homebrew-core/blob/master/audit_exceptions/versioned_dependencies_conflicts_allowlist.json). Since it's only a CLI tool.

**Comment by ZhongRuoyu** [comment]
## Failures

### On ARM

- [ ] `brew test --retry --verbose bvm`: `Error installing https://bvm.land/deno/1.3.2.json.` (website seems down)
- [ ] `brew test --retry --verbose cargo-c`: `No linkage with libssl.dylib! Cargo is likely using a vendored version.`
- [ ] `brew test --retry --verbose cargo-edit`: `No linkage with libssl.dylib! Cargo is likely using a vendored version.`
- [ ] `brew install --build-from-source fst`: ``the method `next` exists for mutable reference `&mut DeserializeRecordsIntoIter<Box<(dyn Read + Send + Sync + 'static)>, (BString, u64)>`, but its trait bounds were not satisfied`` ([log](https://github.com/Homebrew/homebrew-core/actions/runs/4383986144/jobs/7675070208#step:11:3313))
- [ ] `brew test --retry --verbose lexicon`: #118944 (pre-existing)
- [ ] `brew install --build-from-source page`, `brew link page`, `brew test --retry --verbose page`: #125376
- [ ] `brew fetch --build-from-source --retry tuc`: `Warning: Formula reports different sha256`

#### On ARM Ventura

- [ ] `brew test --retry --verbose boringtun`: `Timeout::Error: execution expired` ([log](https://github.com/Homebrew/homebrew-core/actions/runs/4383986144/jobs/7675069840#step:11:1350))

**Comment by chenrui333** [comment]
lexicon should be good now, https://github.com/Homebrew/homebrew-core/pull/118944

**Review by chenrui333 — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Merging. Will follow up as per https://github.com/Homebrew/homebrew-core/pull/125208#issuecomment-1464859606.

**Pull request closed without merging**
