### PR TITLE
libgr 0.40.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
New version 0.40.0, let's see if it works better

**Comment by igas** [comment]
@fxcoudert I think it does, we have error but I think different one. Last time was about `error.c`.

```
ld: library not found for -lglut
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [tiffgt] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [/private/tmp/libgr-20190605-93881-1c1wbea/gr-0.40.0/3rdparty/build/lib/libtiff.a] Error 2
make[1]: *** [extras] Error 2
make: *** [self] Error 2
```

**Comment by fxcoudert** [comment]
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C qt -f makefile.mak install
ditto: can't get real path for source 'gksqt.app'
```

**Pull request closed without merging**
