### PR TITLE
ghc@8.8: migrate to python@3.8

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by jonchang — DISMISSED** [review]

**Comment by jonchang** [comment]
@Bo98 do these need to build dependents from source?

**Comment by Bo98** [comment]
For a pull request like this which only changes a build time dependency and should have no effect on how it behaves at runtime, it should be fine.

**Comment by iMichka** [comment]
Yes, we do not need to bump the revision here, as this is just a build time dependency. @Rylan12 can you remove the `revision 1` line?

**Comment by Rylan12** [comment]
Yep! Thanks for the catch @jonchang.

**Pull request merged**
