### PR TITLE
makensis: generate test-script using compiler flags

### PR DESCRIPTION
**Pull request by idleberg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR builds the test-script using compiler flags, rather than writing a file to the disk and then compiling it

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why do you want to change this? The current test seems fine.

**Comment by idleberg** [comment]
The test itself is unchanged. I find it unnecessary to write an extra file when you can do it like this.

**Comment by fxcoudert** [comment]
From a non-NSIS expert and Homebrew maintainer, I find writing the file a lot more readable. I'm going to close this, but thanks for the suggestion!

**Comment by idleberg** [comment]
Speaking of real tests, [here](https://github.com/kichik/nsis/blob/6e91299e9c4454a6629d6c65ec46c5b345c2d37b/.travis.yml) is how the NSIS developers are testing. I wonder if line 10 is speaking against adapting their test.

**Pull request closed without merging**
