### PR TITLE
libgxps 0.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tschoonj** [comment]
This one uses meson now. I am not sure if this is a stable release by the way.

**Comment by ilovezfs** [comment]
ok closing.

**Comment by tschoonj** [comment]
I sent the release manager an email asking if this release is stable or unstable.

By the way, we are going to see a lot more gnome formulas migrating to meson soon... unfortunately meson is currently not handling library versioning properly on macOS, which will cause trouble for us.

There is a ticket open [here](https://github.com/mesonbuild/meson/issues/1451)

**Comment by ilovezfs** [comment]
jpeg https://bugzilla.gnome.org/show_bug.cgi?id=786093

**Comment by tschoonj** [comment]
Reply from principal developer:

> In libgxps we don't follow the pattern of stable/unstable releases,
mainly because it's still 0.x. Maybe it's time to change that, but for
now I simply do releases bumping patch/micro version when there are mainly
bug fixes or small api additions and I bump the minor version when there
are important new features or API additions. This time I released 0.3
because of the resource dictionaries support and the meson build system.

**Pull request closed without merging**
