### PR TITLE
python@3.11 python-gdbm@3.11 python-tk@3.11 3.11.6

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by Bo98** [comment]
The libedit issue in 3.12 is likely failing silently here:

```
Dependencies with no linkage:
  libedit
```

Will take a look at this shortly.

**Comment by Bo98** [comment]
Patch that might fix libedit (will submit upstream if it works): https://github.com/Bo98/cpython/commit/755295a25a41d65cc507a2c5564583a10f566c2f (different than 3.12 as configure code changed a little)

**Comment by p-linnane** [comment]
Looks like this latest version of the patch worked.

**Comment by Bo98** [comment]
Added a test too so we don't accidentally break it again in the future.

**Comment by p-linnane** [comment]
`pip-audit` was fixed by @branchvincent in https://github.com/Homebrew/homebrew-core/pull/149406. Other failures are either pre-existing, or unrelated.

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
