### PR TITLE
llvm: add devel v7.0.0rc1

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/llvm/7.0.0rc1/bin/clang -L/usr/local/Cellar/llvm/7.0.0rc1/lib -fopenmp -nobuiltininc -I/usr/local/Cellar/llvm/7.0.0rc1/lib/clang/7.0.0rc1/include omptest.c -o omptest
omptest.c:3:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
Error: llvm: failed
```

**Comment by yurikoles** [comment]
there is version missmatch in include path
```
/usr/local//Cellar/llvm/7.0.0rc1/lib/clang/7.0.0/include/omp.h
```
vs 
```
/usr/local/Cellar/llvm/7.0.0rc1/lib/clang/7.0.0rc1/include/omp.h
```
The `#{version}` is evaluated as `7.0.0rc1`, but actual path in actual path it's `7.0.0`. 

I'm not sure how to fix this.

**Comment by fxcoudert** [comment]
```
     system "#{bin}/clang", "-L#{lib}", "-fopenmp", "-nobuiltininc",
                            "-I#{lib}/clang/#{version}/include",
                            "omptest.c", "-o", "omptest"
```

Actually this is weird: why doesn't `clang` already know where its own headers are, once installed?

**Comment by yurikoles** [comment]
@fxcoudert I had fixed it. But I'm not sure why sierra build failed. Could you trigger rebuild?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@yurikoles I see the fix, but I'm still puzzled: why does `clang` need to be passed `-I` option to its own internal headers? It should know where they are.

**Comment by yurikoles** [comment]
@fxcoudert as we see from test fail it simply can't find it. I had also tried commenting out this include and I see same error.

**Pull request merged**
