### PR TITLE
kops 1.11.0

### PR DESCRIPTION
**Pull request by cienijr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
1.10.1 is still marked as “latest release”:

capture d ecran 2019-01-02 a 14 49 33

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
It's marked now.

**Comment by fxcoudert** [comment]
Merged in 
https://github.com/Homebrew/homebrew-core/commit/663f7770233bf74f235606061d331105015419c2

**Comment by igas** [comment]
Thank you @cienijr!

**Pull request closed without merging**
