### PR TITLE
python@3.8: install pip3 and wheel3 to /usr/local/bin/

### LINKED ISSUE #57651: Upgrading or installing Python latest version (3.8) does not override pip3 link
- [X] ran `brew update` and can still reproduce the problem? Yes
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem? Yes
- [X] ~~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~ no formula failed, see below
- [X] ~~if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~~ n/a

## What you were trying to do (and why)

*I include links to the CircleCI output when possible, these should be accessible if logged to a CircleCI account.)*

We run a number of CI tests on macOS for the [datadog-agent](https://github.com/DataDog/datadog-agent) repository. For this tests, we use `brew` to install several packages including `python`. 

## What happened (include command output)

Since around 11 am (CET) the tests started failing because the `pip` command could not be found (example [logs available here](https://app.circleci.com/pipelines/github/DataDog/datadog-agent/4096/workflows/c288f2ec-f7b3-4231-9bcc-fd2cf3e851d9/jobs/240489/steps)).

Before the fix, we used [this script](https://github.com/DataDog/datadog-agent-buildimages/blob/ce265d7c0e9e1278eb08b58abd0f179469f4479d/macos/builder_setup.sh#L24-L26) for the setup.
The relevant lines are:

```sh
brew uninstall python@2 || true
brew upgrade python -f || brew install python -f
ln -s /usr/local/bin/pip3 /usr/local/bin/pip
```

We then use `pip` (which links to `pip3`) to install some packages ([see here](https://github.com/DataDog/datadog-agent-buildimages/blob/ce265d7c0e9e1278eb08b58abd0f179469f4479d/macos/build_script.sh#L29)), which is where the CI fails.
After some digging, we believe the likely culprit to be PR #54912. [The logs](https://app.circleci.com/pipelines/github/DataDog/datadog-agent/4100/workflows/b2f47b21-b9ea-4bbd-932c-651fc4e372c4/jobs/240570/parallel-runs/0/steps/0-102) show that some links get overwritten:

<details>
  <summary><code>python@3.8</code> install overwrites</summary>
  <pre>
==> Installing python@3.8
==> Pouring python@3.8-3.8.3_1.high_sierra.bottle.tar.gz
Warning: These files were overwritten during `brew link` step:
/usr/local/bin/2to3
/usr/local/bin/idle3
/usr/local/bin/pydoc3
/usr/local/bin/python3
/usr/local/bin/python3-config
/usr/local/share/man/man1/python3.1
/usr/local/lib/pkgconfig/python3.pc </pre>
</details>

but the `pip3` link does not get overwritten, which seems to be what caused our CI to fail. The fix was to call `pip` as a module, see DataDog/datadog-agent-buildimages#61

Alternatively, we could have fixed it by rewriting the `pip3` link ourselves, since the output from `brew` says

```
You can install Python packages with
 
  /usr/local/opt/python@3.8/bin/pip3 install <package>
```

## What you expected to happen

We expected it to work correctly as it did before 11 am CET ([example of successful log from yesterday](https://app.circleci.com/pipelines/github/DataDog/datadog-agent/4079/workflows/cad9101b-53e7-4378-9b6a-b21bf98781b4/jobs/240368/steps))

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew upgrade python -f || brew install python -f
pip3
```

### PR DESCRIPTION
**Pull request by Bo98**
Fixes https://github.com/Homebrew/homebrew-core/issues/57651

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Thanks, I missed that part during the migration.

**Comment by MikeMcQuaid** [comment]
Shouldn't block this PR but: a `test do` block to catch this would be handy.

**Comment by MikeMcQuaid** [comment]
Hmm, wonder why `system bin/"pip3", "list", "--format=columns"` in the test didn't catch this...

**Comment by Bo98** [comment]
`bin` is `/usr/local/Cellar/python@3.8/3.8.3_1/bin` - not `/usr/local/bin`.

**Comment by MikeMcQuaid** [comment]
Perhaps we could adjust the test to use `HOMEBREW_PREFIX/bin`?

**Comment by Bo98** [comment]
Possibly, but likely wouldn't have prevented the issue happening. It was _intentionally_ missing from `/usr/local/bin` when `python@3.8` was keg-only (and so such test couldn't have existed then) and it was just forgotten to add it when it was made non-keg-only.

**Comment by MikeMcQuaid** [comment]
Thanks. Fine to leave as-is then 👍

**Pull request closed without merging**
