### PR TITLE
go@1.11 1.11.5 (new formula)

### PR DESCRIPTION
**Pull request by vincepri**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you add (new formula) at the end of the title/commit?
In addition to that, what's the need to ship this particular version as a seperate formula? Is it still supported by upstream?

**Comment by fxcoudert** [comment]
We have too many Go versions in core, if we want to add this one we'd have to drop at least one older.

**Comment by vincepri** [comment]
@SMillerDev Sure can do, can you give some guidance on how to fix `bottle do`?
@fxcoudert Completely agree, I see there is still 1.4, 1.8 and 1.9, which have been deprecated. Go supports only N-2 releases as specified here https://golang.org/doc/devel/release.html.

**Comment by vincepri** [comment]
@fxcoudert Let me know if I should remove the unsupported version as part of this PR or open a new one.

**Comment by fxcoudert** [comment]
I think we were keeping go 1.4 because it's the last version that builds without bootstrap… but not sure if that makes sense to keep going forward.

I'd say: remove 1.4 and 1.8, which have low usage *and* are not supported.

**Comment by vincepri** [comment]
@fxcoudert Added a commit to remove the versions specified.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Build is failing on Sierra and High Sierra:

```
==> go build
../../godoc/redirect/redirect.go:22:2: cannot find package "golang.org/x/net/context/ctxhttp" in any of:
	/usr/local/Cellar/go@1.11/1.11.5/libexec/go/src/golang.org/x/net/context/ctxhttp (from $GOROOT)
	/private/tmp/go@1.11-20190311-9501-zj40qh/go/src/golang.org/x/net/context/ctxhttp (from $GOPATH)
```

**Comment by vincepri** [comment]
@fxcoudert Unfortunately I don't have Sierra/High Sierra to test. What do you think about removing those completely from the formula?

**Comment by fxcoudert** [comment]
Thanks @vincepri for the pull request, build appeared to succeed in #38018 so we're going to merge that one.

**Comment by vincepri** [comment]
Apologies, I forgot to follow-up. Thanks though!

**Pull request closed without merging**
