### PR TITLE
cmake: use modern Git URL

### PR DESCRIPTION
**Pull request by mathstuf**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
I'm not on a Mac, so I can't test, but it's trivial.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Homebrew is also available on Linux, why did this URL change by the way? And is there any documentation about it?

**Comment by mathstuf** [comment]
We migrated to our own GitLab instance in 2015: <https://blog.kitware.com/kitware-migrates-project-repositories-to-gitlab/>

We're looking at turning off the infrastructure for the old gitweb/git-daemon/gitolite configuration to reduce the number of unnecessary services we need. Since it has been so long, we decided to go with an "ask for forgiveness" plan to flush out users of the old URLs (there are many repos and they've all been migrated for contribution for years, but for fetching, it is hard to contact all the users specifically because we don't *know* what they are). We're likely to turn back on cmake.git, but I'm going to look into making it be *very* noisy when cloning that the URL is going away imminently pointing folks to the new location (I'd like to be aggressive and say by February, but we'll see what we end up with).

**Comment by mathstuf** [comment]
> We're likely to turn back on cmake.git, but I'm going to look into making it be very noisy when cloning that the URL is going away imminently pointing folks to the new location (I'd like to be aggressive and say by February, but we'll see what we end up with).

From some investigation, I don't see a way to make *fetch* be noisy. Only push has a server-side `post-receive` hook to use. No hooks are called on the simple fetch/clone code path AFAICT. So it's going to be a game of whack-a-mole :/ .

**Comment by jonchang** [comment]
> We migrated to our own GitLab instance in 2015: https://blog.kitware.com/kitware-migrates-project-repositories-to-gitlab/

Should future tarballs `url`s point to Gitlab instead then?

**Comment by jonchang** [comment]
This will need to be force merged from desktop because I don’t think the CI failures apply to this change.

**Comment by mathstuf** [comment]
On December 14, 2019 2:18:16 AM EST, Jonathan Chang <notifications@github.com> wrote:
>> We migrated to our own GitLab instance in 2015:
>https://blog.kitware.com/kitware-migrates-project-repositories-to-gitlab/
>
>Should future tarballs `url`s point to Gitlab instead then? 

The status hosting isn't going anywhere. The git hosting was on another set of services not used for anything else. However, the GitHub hosted tarballs under releases are now available too. That is CDN-backed and probably better for those.

**Comment by chenrui333** [comment]
Thanks @mathstuf!!

**Pull request merged**
