### PR TITLE
Feature/boost 1.63 locked version

### PR DESCRIPTION
**Pull request by kheyse-autodesk**
Readded the old boost formula as boost@1.63

What are the criteria for adding a formula for a specific version of a project?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> What are the criteria for adding a formula for a specific version of a project?

Explain to us why this is needed. Thanks!

**Comment by kheyse-autodesk** [comment]
We have a project that uses boost@1.63. Switching to a newer version of boost is something we want to do in a controlled way so that we can test everything for backwards compatibility.

**Comment by MikeMcQuaid** [comment]
If you want to do that for a single project a tap is the best bet. Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!

**Comment by kheyse-autodesk** [comment]
Can I ask when a specific version of a project can be added? It seems there are already 4 versions of boost in homebrew-core.

**Comment by MikeMcQuaid** [comment]
The barrier on removing them is higher than adding them. Generally we want a reason like "this version is required for this open source project because it breaks backwards compatibility in this way".

**Pull request closed without merging**
