### PR TITLE
cgal 4.8.1

### PR DESCRIPTION
**Pull request by ilovezfs**
use QT5 instead of QT4

Closes #321.

Closes #195.

cc @dunn

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
As far as I can see the homepage can still be `https://`, but feel free to do that in post to save the CI. :shipit:.

**Comment by ilovezfs** [comment]
Yeah I noticed that too, though Firefox did complain about some elements on the page being insecure.

**Comment by ilovezfs** [comment]
:ship:'d

**Comment by DomT4** [comment]
Yeah, they're loading Google Fonts explicitly over `http://` even though there's absolutely no reason to do that 👀. Trying to load an insecure script as well. Yay for website design.

**Comment by dunn** [comment]
🎉

**Pull request closed without merging**
