### PR TITLE
bedtools: import from homebrew/science

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/homebrew-science/pull/6343

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like an Xcode 9 related build error. I will download that now to try to fix it.

**Comment by jonchang** [comment]
The solution was to de-`const` StrandQueue.cpp. I will write a patch for upstream and then include it in the formula.

**Comment by ilovezfs** [comment]
Thanks @jonchang :)

**Comment by jonchang** [comment]
* patch from https://github.com/arq5x/bedtools2/pull/574 added

**Comment by ilovezfs** [comment]
patch needs to be accepted and merged upstream and a new release cut

**Comment by jonchang** [comment]
I've notified upstream of this requirement

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Review by ilovezfs — CHANGES_REQUESTED** [review]
@jonchang what's the status on `make install` here?

**Comment by jonchang** [comment]
I'll open an issue with upstream about it.

**Comment by ilovezfs** [comment]
@stale leave @jonchang alone, please.

**Comment by ilovezfs** [comment]
@jonchang it has a had `make install` target for 3 years. https://github.com/arq5x/bedtools2/commit/e7379ae8f22ea712fc09059992fbf025058b466e

I think you just need to make it
```
    system "make", "install", "prefix=#{prefix}"
```

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @jonchang!

**Pull request closed without merging**
