### PR TITLE
wine 1.9.20 (devel)

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by tobbi** [comment]
On OS X 10.12, this fails with:

info.c:787:1: error: use of undeclared identifier 'cupsGetPPD'; did you mean 'cupsGetFd'?
CUPS_FUNCS;
^
info.c:779:13: note: expanded from macro 'CUPS_FUNCS'
    DO_FUNC(cupsGetPPD); \
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/cups/cups.h:392:22: note: 'cupsGetFd' declared here
extern http_status_t    cupsGetFd(http_t *http, const char *resource, int fd);
                        ^
info.c:805:29: error: too few arguments to function call, expected 3, have 1
    ppd = pcupsGetPPD( name );
          ~~~~~~~~~~~       ^

Seems like this needs an upstream fix for Sierra?

**Comment by AlexanderNeilson** [comment]
hi @tobbi 

Can you please confirm which part of the formula you are trying to install (brew install wine? brew install wine --devel?)

This is an update to the --devel branch which already includes a patch for this error experienced during pre release testing.

The current version in non --devel doesn't include the patch but homebrew should be pulling the patch down correctly from WineHQ.

The latest stable version now includes the patch and should be updated (I am planning a pull request once I work out why I am getting rejections trying to submit it).

This builds fine for me when manually applied into my macOS Sierra machine, the test failure causing this rejection seemed to be in an older version when I last looked.

Regards
Alexander

**Comment by tobbi** [comment]
@AlexanderNeilson I was just quoting directly from the CI output (failure) for this PR. If this PR succeeds, can it be merged?

**Comment by MikeMcQuaid** [comment]
> If this PR succeeds, can it be merged?

Yes.

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by tobbi** [comment]
The CI error that happens on wine stable (not on devel) was fixed in the 1.9.19 stable release of wine (current stable is 1.9.20). Care to update that as well?

**Comment by AlexanderNeilson** [comment]
hi @tobbi 

The stable 1.8.3 in the existing wine formula should include the patch for 40851 in the stable patch section. However I have now submitted a PR [https://github.com/Homebrew/homebrew-core/pull/5755](url) to update to 1.8.5 which has integrated the patch from WineHQ Bug ID 40851 (and also 40830).

Hopefully this will resolve this CI failure and this can follow through to be pulled in.

Regards
Alexander

**Comment by MikeMcQuaid** [comment]
Could someone else submit a PR to apply the relevant patch/release updates? Thanks!

**Comment by tobbi** [comment]
I submitted #5847 with the proper checksum and all other parts unchanged.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
