### PR TITLE
faiss 1.7.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> ./configure --without-cuda --prefix=/usr/local/Cellar/faiss/1.7.0 ac_cv_prog_cxx_openmp=-Xpreprocessor -fopenmp LIBS=-lomp
Failed to execute: ./configure
```

**Comment by carlocab** [comment]
They switched to a CMake build. https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

I'll fix this later.

**Comment by carlocab** [comment]
@ankane, if you have a minute, I'd appreciate your help fixing the test here.

**Comment by ankane** [comment]
Hey @carlocab, switching to the shared library seems to fix it - `-DBUILD_SHARED_LIBS=ON`.

**Comment by carlocab** [comment]
Thanks very much, @ankane!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
