### PR TITLE
llvm 7.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
llvm:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/llvm.rb llvm@7
  * Formula has invalid versioned aliases:
      llvm@6
```

**Comment by alex** [comment]
@fxcoudert done, hopefully correct 😬

**Review by commitay — DISMISSED** [review]

**Comment by kristate** [comment]
Looking forward to this! Thanks.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @alex for the pull request!

**Comment by javian** [comment]
@vszakats no, thanks for noticing. Its currently queued for a rebuild so we can merge it once its done.

**Pull request closed without merging**
