### PR TITLE
gdm: add support for go 1.16

### PR DESCRIPTION
**Pull request by roopakv**
add support for go 1.16

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is this issue raised upstream?

**Comment by roopakv** [comment]
@SMillerDev it is now, but the project seems unmaintained: https://github.com/sparrc/gdm/issues/29

**Review by Bo98 — APPROVED** [review]

**Comment by SMillerDev** [comment]
Can you add a `deprecate! date:, reason: ` statement with today's date then?

**Comment by SMillerDev** [comment]
oh, in a new PR I guess

**Pull request merged**
