### PR TITLE
lsof 4.96.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  dlsof.h:60:10: fatal error: rpc/rpc.h: No such file or directory
     60 | #include <rpc/rpc.h>
        |    
```

**Comment by chenrui333** [comment]
need libntirpc-dev, as #109914

**Comment by danielnachun** [comment]
Actually it probably needs to depend on `libtirpc` on LInux, for which we already have a formula.

**Comment by danielnachun** [comment]
I had to test this locally, and it turns out `LSOF_INCLUDE` must also be specified for `lsof` to find the `libtirpc` headers.  But with that change it works locally.

**Review by danielnachun — APPROVED** [review]
Linux is fixed.  We can merge this once CI is done.

**Comment by chenrui333** [comment]
Thanks @danielnachun!! :)

**Pull request closed without merging**
