### PR TITLE
openblas 0.3.9

### PR DESCRIPTION
**Pull request by zbeekman**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zbeekman** [comment]
I'm pretty sure the recursive dependencies need to be rev-bumped, but I'm starting with direct dependencies as an experiment.

**Comment by Bo98** [comment]
> I'm pretty sure the recursive dependencies need to be rev-bumped.

Ultimately, it depends on the formula. I suppose we can make some more explicit and depend on openblas directly.

**Comment by zbeekman** [comment]
@Bo98 I don’t think that necessarily makes sense... I just wanted to incrementally update dependencies to see if rev-bumping some direct dependencies resolves any of the indirect ones.

**Comment by zbeekman** [comment]
Mostly as a sanity check. It seems like the fast majority of these failures are due to transient dynamic linkage, perhaps some due to soversion changes or linking to the cellar rather than /use/local/opt.

**Comment by Bo98** [comment]
> I just wanted to incrementally update dependencies to see if rev-bumping some direct dependencies resolves any of the indirect ones.

Yes, that's fine. I wasn't disputing that. I think I maybe misread your comment as "_all_ recursive dependencies need revision bumping".

**Comment by zbeekman** [comment]
FYI, GHA failures are timeout, it would appear. If Jenkins is green this should be good to merge. If not, I may have missed some revision bumps.

**Pull request closed without merging**
