### PR TITLE
wireguard-go: Fix linux test

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
cc @gromgit I got a different output on Linux: https://github.com/Homebrew/linuxbrew-core/actions/runs/551358531

**Comment by SMillerDev** [comment]
Any way we could test this on linux to be sure?

**Comment by iMichka** [comment]
Yes, you can look at the output in the build log: https://github.com/Homebrew/linuxbrew-core/actions/runs/551358531
I don't know why @gromgit got a different output.

**Comment by gromgit** [comment]
Very sorry, got distracted while working on the original PR, and ran the test on a real host instead of a Docker container. :facepalm:

**Pull request closed without merging**
