### PR TITLE
vault 1.7.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
@Bo98 I keep seeing ARM node failures like the one here. I wasn't able to check if it's always the same one though. If you've got a minute, maybe you'd like to take a look.

**Comment by Bo98** [comment]
Thanks for the ping - I'll have a look at this machine now.

**Comment by carlocab** [comment]
Ah, it's not always the same node. It's `bigsur-arm-4` here: https://github.com/Homebrew/homebrew-core/pull/73062/checks?check_run_id=2188435796#step:1:2

**Review by carlocab — APPROVED** [review]

**Comment by Bo98** [comment]
The runner crashed:

```
Crashed Thread:        22  com.apple.rosetta.exceptionserver

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       EXC_ARM_BREAKPOINT at 0x00007ffdffe2536c (brk 1)
Exception Note:        EXC_CORPSE_NOTIFY
```

It seems to randomly happen. Not sure if there's much that can be done about that though.

**Pull request closed without merging**
