### PR TITLE
libcds: adding new formula - a C++ library of Concurrent Data Structures

### PR DESCRIPTION
**Pull request by tekn0ir**
- [*] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [*] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [*] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [*] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Does not build on Yosemite:

```
[ 20%] Building CXX object CMakeFiles/cds.dir/src/hp_gc.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -Dcds_EXPORTS -I/tmp/libcds-20170312-8156-hluvo0/libcds-2.2.0 -I/usr/local/include  -DCDS_USE_BOOST_ATOMIC -std=c++11 -Wall -Wextra -pedantic -fno-strict-aliasing -mcx16 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -fPIC   -o CMakeFiles/cds.dir/src/hp_gc.cpp.o -c /tmp/libcds-20170312-8156-hluvo0/libcds-2.2.0/src/hp_gc.cpp
In file included from /tmp/libcds-20170312-8156-hluvo0/libcds-2.2.0/src/init.cpp:47:
/tmp/libcds-20170312-8156-hluvo0/libcds-2.2.0/cds/threading/details/cxx11_manager.h:46:16: error: thread-local storage is not supported for the current target
        static thread_local ThreadDataPlaceholder CDS_DATA_ALIGNMENT(8) s_threadData;
               ^
/tmp/libcds-20170312-8156-hluvo0/libcds-2.2.0/cds/threading/details/cxx11_manager.h:47:16: error: thread-local storage is not supported for the current target
        static thread_local ThreadData * s_pThreadData;
               ^
/tmp/libcds-20170312-8156-hluvo0/libcds-2.2.0/src/init.cpp:71:5: error: thread-local storage is not supported for the current target
    thread_local threading::cxx11_internal::ThreadDataPlaceholder CDS_DATA_ALIGNMENT(8) threading::cxx11_internal::s_threadData;
    ^
/tmp/libcds-20170312-8156-hluvo0/libcds-2.2.0/src/init.cpp:72:5: error: thread-local storage is not supported for the current target
    thread_local threading::ThreadData * threading::cxx11_internal::s_pThreadData = nullptr;
    ^
4 errors generated.
make[2]: *** [CMakeFiles/cds-s.dir/src/init.cpp.o] Error 1
```

**Comment by tekn0ir** [comment]
Trying to fix it...

**Comment by fxcoudert** [comment]
Have a look at `needs :cxx11` and `ENV.cxx11`

**Comment by tekn0ir** [comment]
Ok, I have not full knowledge, earlier versions of clang's stdlib does not support thread_local, so a -stdlib=libc++ should do the trick, right?

See:
http://stackoverflow.com/questions/23791060/c-thread-local-storage-clang-503-0-40-mac-osx
http://stackoverflow.com/questions/28094794/why-does-apple-clang-disallow-c11-thread-local-when-official-clang-supports

I guess you have more knowledge about this so if my commit doesn't work, I go with your suggestions! :-)

**Comment by fxcoudert** [comment]
Forcing GCC that way won't work, because it may not be installed. What if you replace all the workarounds with a simple: `depends_on "gcc" if MacOS.version <= :yosemite`?

**Comment by fxcoudert** [comment]
The `gcc` dependency is not restricted to build. Please use `depends_on "gcc" if MacOS.version <= :yosemite`. And that should be enough for cmake to pick up the right compiler and library, so I would try turning off the special case in cmake.

**Comment by ilovezfs** [comment]
I've been throwing
```
chaiscript.rb:14:  depends_on :macos => :el_capitan # needs thread-local storage
dar.rb:19:  depends_on :macos => :el_capitan # needs thread-local storage
```
at these.

But if you want to go down the gcc rabbit hole, you should be able to do

```
if DevelopmentTools.clang_build_version < 800
  depends_on "gcc"
  fails_with :clang
end
```
or an equivalent variation on that theme with `fails_with :clang do` and a truck load of `build` build numbers.

**Comment by tekn0ir** [comment]
Yes, was just doing that before I saw your comment. My problem is just that. I don't know what is installed.
My problem is that Yosemite has clang 7, the thread_local support came in clang 8.
I still need the CMAKE instructions, I think? And I still want to build it with clang 8 in > :yosemite.

**Comment by fxcoudert** [comment]
I'm happy with removing all the special cases and simply doing `depends_on :macos => :el_capitan`

**Comment by tekn0ir** [comment]
Lets see if this works, if not, I do depends_on :macos => :el_capitan

**Comment by ilovezfs** [comment]
It will work if you also put in the fails_with :clang. Otherwise, it won't work since it will use clang regardless of your gcc dependency or lack thereof.

**Comment by tekn0ir** [comment]
Aight, that was what I thought, I think I go with the depends_on :macos => :el_capitan

**Comment by ilovezfs** [comment]
Might as well try
```
if DevelopmentTools.clang_build_version < 800
  depends_on "gcc"
  fails_with :clang
end
```
just for fun ;)

**Comment by tekn0ir** [comment]
kk, lets try then! :-)

**Comment by tekn0ir** [comment]
Awesome! Thanks a lot for all the help! Goldstars if I could give them! Now its just up to you to decide if this is a good contribution to home-brew! Cheers!

**Comment by fxcoudert** [comment]
Thanks @tekn0ir for your contribution to Homebrew!

**Pull request closed without merging**
