### PR TITLE
Bulk import from homebrew/versions (7/7)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Import formulae from homebrew/versions. Those that fail to build will likely be killed.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Fail to build: `subversion@1.8` and `unison@2.40`.
Test fails for `srtp@1.5` and `zeromq@4.0` (missing header in both cases).
The rest look good.

**Comment by ilovezfs** [comment]
subversion problem is that the inline patch was not copied verbatim so the white space is borked.

**Comment by ilovezfs** [comment]
I pushed a fix for unison@2.40

**Comment by ilovezfs** [comment]
subversion
```
Possible unintended interpolation of @1 in string at (eval 26) line 1.
```

**Comment by ilovezfs** [comment]
Build succeeds if the formula is named subversion18 instead of subversion@1.8.

**Comment by ilovezfs** [comment]
I've pushed a fix for subversion@1.8.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Some style issues, some deprecated 

```
unison@2.40:
  * Stable: The URL http://www.seas.upenn.edu/~bcpierce/unison/download/releases/unison-2.40.128/unison-2.40.128.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.cis.upenn.edu/~bcpierce/unison/ could use HTTPS rather than HTTP
subversion@1.8:
  * `depends_on` (line 38) should be put before `resource` (line 21)
  * :apr is deprecated. Usage should be "apr-util"
  * `env :userpaths` in formulae is deprecated
selenium-server-standalone@2.45:
  * A `test do` test block should be added
```

**Comment by MikeMcQuaid** [comment]
Let's hold off merging this until we have a new tag with https://github.com/Homebrew/brew/pull/1732.

@fxcoudert Thanks, will look at cleaning them up.

**Comment by MikeMcQuaid** [comment]
Thanks for the help @fxcoudert, @ilovezfs!

**Comment by ilovezfs** [comment]
yw

:confetti_ball:

**Pull request closed without merging**
