### PR TITLE
apache-spark 2.4.1

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
- [V] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [V] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [V] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?

This PR is based on the change which is created by `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Two of three tests are passed. `Mojave` seems to complain at `brew doctor`, but I have no idea. Could anyone retriever the test please?
```
Error Message
failed: brew doctor
```

**Comment by dongjoon-hyun** [comment]
The `brew doctor` failure on `Mojave` is not on this PR. All recent PRs fail with that error.
```
08:43:48 ==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/38660
08:43:52 Homebrew/brew 2.0.6-107-g1337da0f8 (Merge pull request #5940 from lembacon/xcode-10.2)
08:43:52 homebrew/core origin/master 684f2002f6 (carthage: fix macOS version check.)
08:43:52 homebrew/core HEAD fd7546ce4e (apache-spark 2.4.1)
08:43:52 
08:43:52 ==> brew doctor
08:43:55 ==> FAILED
08:43:55 Please note that these warnings are just used to help the Homebrew maintainers
08:43:55 with debugging if you file an issue. If everything you use Homebrew for is
08:43:55 working fine: please don't worry or file an issue; just ignore this. Thanks!
08:43:55 
08:43:55 Warning: A newer Command Line Tools release is available.
08:43:55 Update them from Software Update in System Preferences.
```

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by fxcoudert** [comment]
One audit error on Mojave due to CI nodes having not yet been updated to latest CLT. Merging, thanks @dongjoon-hyun for the pull request!

**Comment by dongjoon-hyun** [comment]
Thank you all!

**Pull request merged**
