### PR TITLE
Idris 0.99

### PR DESCRIPTION
**Pull request by Termina1**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks @Termina1!

**Comment by ilovezfs** [comment]
Pretty sure 0.99 is still considered pre-release which is why I did not do this bump.

**Comment by ilovezfs** [comment]
Yeah: http://www.idris-lang.org/towards-version-1-0/

"We’ll shortly be releasing Idris version 0.99, which is essentially an alpha release of 1.0, and we’ll keep releasing updates until 1.0 is ready, probably around February 2017"

But I suppose it's _possible_ upstream considers 0.99 to supersede 0.12.3, even if it's calling 0.99 **alpha**? Of course in that case, I'm not sure why idris is in core at all.

**Comment by Termina1** [comment]
@ilovezfs I asked on irc channel if this version is stable, and received an answer "stable as the language is".

**Comment by ilovezfs** [comment]
@Termina1 OK. Looks like we're the only ones that have moved to 0.99 but so be it.
```
Distributions 	Arch:0.12.3, LTSHaskell:0.12.3, NixOS:0.12.3, Tumbleweed:0.12.3
```

**Comment by Termina1** [comment]
May be we could ask @jfdm to tell us more?

**Comment by woodruffw** [comment]
Hmm, I didn't realize. If we're the only ones on 0.99, it might make sense to roll back.

**Comment by ilovezfs** [comment]
@woodruffw given that @edwinb uploaded it to Hackage, I think it'll be fine.

**Comment by jfdm** [comment]
Dear all;

When @Termina1 asked his question about Idris' stability it came across as being a general questions and not in reference to home brew formula. In response I referred to the blog posting: 

  http://www.idris-lang.org/towards-version-1-0/

in which our notion of stability and what '1.0' is defined.

Yes, Version 0.99 of Idris is stable, but we make explicit reference to language stability. Some parts of Idris' internals might be revised, and may need some refinement. Specifically:

> Mostly, what we mean by calling a release “1.0” is that there are large parts of the language and libraries that we now consider stable, and we promise not to change them without also changing the version number appropriately. 

To some degree, and this is a personal opinion, notions of '1.0' and alpha and beta and production readiness are not necessarily conducive to research software. This is partly why alpha was not used in the release notes, and why we define our own notion of stability.

@ilovezfs Idris developers are not responsible for downstream release of Idris outside precompiled binaries. There will naturally be a lag: 0.99 is less than a week old.

@woodruffw If the version number in home-brew is the same as seen in Hackage then it is fine.

If future it would be nice to if people contacted: the developers of Idris directly; the mailing list; or ask in IRC with direct reference to home-brew.

**Comment by ilovezfs** [comment]
@jfdm the bottom line here is whether upstream wants us distributing 0.99 or 0.12.3 right now.

**Comment by Termina1** [comment]
@jfdm I guess, this is why I mentioned you in this thread, I'm not sure how to be more specific than that. Also, there wasn't a question about Idris overall stability, but specifically about 0.99 version. But I apologise if I interpreted you words in a wrong way.

**Comment by jfdm** [comment]
> the bottom line here is whether upstream wants us distributing 0.99 or 0.12.3 right now.

Version 0.99. It is a *normal* release that just so happens to be a precursor to our v1.0.

**Comment by ilovezfs** [comment]
@jfdm thanks for making that explicit. I apologize for reading too much into "essentially an alpha release of 1.0." Around here, we usually won't even package software that designates itself "beta," so "alpha" is like putting a red flag in front of a bull :)

**Pull request closed without merging**
