### PR TITLE
volta 1.0.1

### PR DESCRIPTION
**Pull request by callmesangio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
That's weird.
```
==> brew audit volta --online --git --skip-style
==> FAILED
volta:
  * v1.0.1 is not a GitHub pre-release but 'volta' is in the GitHub prerelease allowlist.
Error: 1 problem in 1 formula detected
```

CC @Rylan12

**Comment by Rylan12** [comment]
It's just telling you that `volta` should be removed from `audit_exceptions/github_prerelease_allowlist.json` as the new version isn't a prerelease

**Comment by carlocab** [comment]
The pre-release audit didn't come up in #67414, and I don't think it was a pre-release then?

**Comment by carlocab** [comment]
On ARM:
```
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to run custom build command for `miniz-sys v0.1.12`
```
Looks like this is the newest miniz-sys (https://crates.io/crates/miniz-sys), so that dependency really just needs an update to work on ARM.

**Review by carlocab — APPROVED** [review]

**Comment by Rylan12** [comment]
I had messed up the logic for handling formulae with that audit so the logic wasn't really finalized until https://github.com/Homebrew/brew/pull/10138 which was merged two days after https://github.com/Homebrew/homebrew-core/pull/67414.

Wow, I guess I haven't been around homebrew/core much in a while! 😅 Do we need the `11-arm` check to be passing to merge?

**Comment by carlocab** [comment]
Yea, I think @BrewTestBot won't merge this if `11-arm` is red. This can be merged manually with `brew pr-publish` (at least, I've seen it work on other PRs...).

Otherwise, we can just remove the CI-force-arm flag and rerun CI, but that feels like a waste.

**Comment by Rylan12** [comment]
Well, it won't auto-merge anyway because of the `automerge-skip`. Just not sure if we need to rerun without `CI-force-arm` before `pr-publish` to make sure everything's green

**Pull request closed without merging**
