### PR TITLE
imgproxy 3.13.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Test failure only on Ventura Intel:
```
 ==> curl -s -o /private/tmp/imgproxy-test-20230111-22920-17vajob/test-converted.png http://127.0.0.1:50459/insecure/resize:fit:100:100:true/plain/local:///test.jpg@png
  WARNING [2023-01-11T22:47:04Z] No keys defined, so signature checking is disabled 
  WARNING [2023-01-11T22:47:04Z] No salts defined, so signature checking is disabled 
  Error: imgproxy: failed
  An exception occurred within a child process:
    BuildError: Failed executing: curl -s -o /private/tmp/imgproxy-test-20230111-22920-17vajob/test-converted.png http://127.0.0.1:50459/insecure/resize:fit:100:100:true/plain/local:///test.jpg@png
```

**Comment by chenrui333** [comment]
this is weird, the curl is the same between 13-arm and 13, but 13-arm build succeeded

> Curl: 7.84.0 => /usr/bin/curl

**Comment by p-linnane** [comment]
I thought it was network flakiness or something so I ran it all again and it was the same failure on the same OS 😕

**Comment by chenrui333** [comment]
test passed after rerun 😮‍💨

**Review by chenrui333 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
