### PR TITLE
llvm: 10.0.1_2

### PR DESCRIPTION
**Pull request by terencehonles**
Copies llvm.rb at b32d4a62eba6d6ab843e331dee7ea9852d9b9c8a as llvm@10.rb

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by terencehonles** [comment]
@fxcoudert not sure if you mind reviewing this. You were the one to change `llvm.rb` most recently and I noticed there was no llvm@10. I don't use a Mac, but I believe this is what is probably needed and missed when converting the formula to llvm 11.

**Comment by fxcoudert** [comment]
Here are our criteria for versioned formulas in Homebrew: https://docs.brew.sh/Versions
Please comment on how whether they are satisfied for this formula.

In particular:

> Upstream should have a release branch for each formula version, and release security updates for each version when necessary

**Comment by terencehonles** [comment]
> Here are our criteria for versioned formulas in Homebrew: https://docs.brew.sh/Versions
> Please comment on how whether they are satisfied for this formula.
> 
> In particular:
> 
> > Upstream should have a release branch for each formula version, and release security updates for each version when necessary

This is for LLVM, there is already `llvm@6`, `llvm@7`, `llvm@8`, and `llvm@9` so I expect the answer to your question is yes, but you tell me. As mentioned I'm not a Mac/homebrew user. I am just trying to unblock https://github.com/apache/arrow/pull/8386 until https://github.com/apache/arrow/pull/8492 which you opened is actually supported (It looks like there are LLVM changes needed to arrow's build system)

**Comment by fxcoudert** [comment]
Thanks for proposing the pull request.

- We've fixed Arrow in homebrew-core by switching it to LLVM 9 (which we provide, as you noted).
- Older LLVM versions were needed because other software relied on them. Let's not introduce yet another LLVM version.

**Comment by terencehonles** [comment]
> Thanks for proposing the pull request.
> 
> * We've fixed Arrow in homebrew-core by switching it to LLVM 9 (which we provide, as you noted).
> * Older LLVM versions were needed because other software relied on them. Let's not introduce yet another LLVM version.

Ok, I'll try updating arrow's Brewfile to use llvm@9 the same way you are suggesting you did. Thanks for the update.

**Pull request closed without merging**
