### PR TITLE
xcbeautify 0.9.0

### PR DESCRIPTION
**Pull request by thii**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> make install PREFIX=/usr/local/Cellar/xcbeautify/0.9.0
/usr/bin/swift build --arch x86_64 --arch arm64 --configuration release --disable-sandbox
error: unknown option --arch; use --help to list available options
```

Can we make this build as a non-universal binary? That would make it work on 10.14

**Comment by SMillerDev** [comment]
In addition to that, we don't really want to ship a universal binary anyway because we build specifically for an architecture/OS so it's useless in Homebrew.

**Comment by thii** [comment]
Copying the failing log here—it seems it was because of either a network issue on the build machine or a bug with an old Swift version.
```
==> swift build --disable-sandbox --configuration release
Fetching https://github.com/getGuaka/Colorizer.git
Fetching https://github.com/apple/swift-argument-parser.git
error: the package dependency graph could not be resolved; unable to find any available tag for the following requirements:
    https://github.com/apple/swift-argument-parser.git @ 0.3.1..<1.0.0
```

**Comment by thii** [comment]
Reproduced locally with Xcode 11.3.1 (the version that the build machine uses).

This is actually a bug with SwiftPM prior to 5.2’s dependency resolver, according to the authors https://bugs.swift.org/browse/SR-4400?focusedCommentId=54520&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-54520.

Apparently we need Xcode 11.4+ (Swift 5.2+) for Swift formulae.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
