### PR TITLE
qt5: cleanup formula (many changes).

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Remove all options except `with-dbus`
  - Build docs/examples/qtwebkit by default
  - Remove all other options, they aren't reliable or widely used enough
- Add patch from #6708.
- Remove caveats. Unnecessary now Qt is LGPL.

Will probably hold off merging until https://github.com/Homebrew/brew/issues/1399 is fixed.

Closes #6708.

### CODE REVIEW

**Comment by ilovezfs** [comment]
No revision bump?

**Comment by MikeMcQuaid** [comment]
> No revision bump?

Done.

**Review by ilovezfs — DISMISSED** [review]

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
👍 on making docs and examples build by default and minimizing options.

Do we have some numbers on how widely used the msyql and postgresql options are?

**Comment by apjanke** [comment]
Oh, nevermind: I see you posted it over in #6766.

**Comment by DomT4** [comment]
Aren't the docs huge? I seem to remember they took up wild disk space. Maybe that's changed. Pretty 😭 about `qtwebkit` by default given the "lol security" aspect around WebKit but have no power to dump on it anymore, so.

**Comment by RandomDSdevel** [comment]
@apjanke, @DomT4, @ilovezfs, @MikeMcQuaid:  As an extension of [this comment](https://github.com/Homebrew/homebrew-core/issues/6766#issuecomment-260083889) I made on [Issue #6766, 'Qt v5.7.0 Still Fails to Build on OS X v10.11.6 'El Capitan' After Resolution of Issue #6032'](https://github.com/Homebrew/homebrew-core/issues/6766), would it possibly be a good idea to split this PR into its constituent parts and continue discussing each individual change separately?

**Comment by ilovezfs** [comment]
@DomT4 looks like it balloons from 91 MB to 445 MB

**Comment by ilovezfs** [comment]
@MikeMcQuaid at this point I'm tempted to just leave the formula the way it was. The examples result in a broken installation (see below), the docs are huge, the sql removal is unnecessary since it works now, and the webkit security is questionable. I think it's fine for people to add any, all, or none of those components if they want them, but the formula seems to be "correct" as-is without any of these changes, except perhaps the caveats change, which is cosmetic.

**Comment by ilovezfs** [comment]
Broken installation from examples
```
Error: 1 problem in 1 formula
qt5:
  * The installation was broken.
    Broken dylib links found:
      libgruesensor.1.dylib
```

**Comment by MikeMcQuaid** [comment]
> The examples result in a broken installation (see below)

Let's remove the examples option. Pretty sure it was me who added in the first place for my personal use.

> the docs are huge

They are generated in multiple formats. I'll try and slim them down and if not let's remove them and the option. They are available online or as a separate download.

> the sql removal is unnecessary since it works now

works (for) now. It's not widely used and will very likely break again.

> webkit security is questionable

Happy to leave that as optional if someone can point to some known security issues with the current version?

**Comment by ilovezfs** [comment]
Not sure what the impetus for a change here is. The formula is actually fine as is. I'd prefer we just close this out.

**Comment by MikeMcQuaid** [comment]
> Not sure what the impetus for a change here is.

Having to deal with Qt5 build issues every time there's a new macOS or upstream release. The large number of options combined with the build time means we're unable to support this formula effectively. We're having to apply increasing numbers of patches for optional functionality it's not clear anyone is using beyond "I want to build Qt5 with all the options enabled".

**Comment by ilovezfs** [comment]
>we're unable to support this formula effectively

Can you point to something broken?

> build time

Your changes increase build time.

>We're having to apply increasing numbers of patches for optional functionality it's not clear anyone is using beyond "I want to build Qt5 with all the options enabled".

Every patch in the formula currently, except the examples patch, applies regardless of options.

**Comment by MikeMcQuaid** [comment]
> Can you point to something broken?

I can point to the amount of work both by contributors, maintainers and the CI machines in the last few weeks that's been spent on this formula to fix options analytics shows a tiny number of people are using.

> Your changes increase build time.

As I mentioned above but perhaps wasn't clear: I'm proposing we remove examples and the option to build them.

> except the examples patch, applies regardless of options.

I'm proposing we remove the examples option and patch.

-- 

I don't feel strongly about what the defaults are for this formula but I do feel strongly that we should remove some if not all of the non-dbus options. You've generally been in favour in the past of removing options, what's changed here?

**Comment by ilovezfs** [comment]
>I'm proposing we remove the examples option and patch.

My point was the patching has nothing to do with the options.

>I can point to the amount of work both by contributors, maintainers and the CI machines in the last few weeks that's been spent on this formula to fix options analytics shows a tiny number of people are using.

This is an overreaction to what happened with mysql, which was mostly my fault.

>I don't feel strongly about what the defaults are for this formula but I do feel strongly that we should remove some if not all of the non-dbus options. You've generally been in favour in the past of removing options, what's changed here?

qt-webkit was only installed by 691/31300, which is probably enough to warrant keeping it, but not enough to justify making it always-on until I have reason to dismiss @DomT4's concern, which I don't at this point.

>I don't feel strongly about what the defaults are for this formula but I do feel strongly that we should remove some if not all of the non-dbus options. You've generally been in favour in the past of removing options, what's changed here?

The ballooning from 91 MB to 445 MB and Dom's concern about the webkit option. I think this is a case of if-it-ain't-broke-don't-fix-it.

To be clear, I really don't care if we drop the options, but I fully expect the qt5 formula to continue to need patches and support galore in perpetuity regardless of the options kept or removed.

**Comment by MikeMcQuaid** [comment]
> I really don't care if we drop the options

Ok, cool. Let's leave it as-is for now, then, and we'll drop them liberally next time they break.

**Pull request closed without merging**
