### PR TITLE
akka 2.4.4

### PR DESCRIPTION
**Pull request by yous**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

Bump [akka](http://akka.io/) to 2.4.4.

### CODE REVIEW

**Comment by UniqMartin** [comment]
The “builds” succeeds, so that's good. 😸

The formula unfortunately doesn't have a test yet, which makes it harder for our build infrastructure to check whether it's broken despite building fine and makes it more likely to break in the future. Would you be willing to try and add a test to the formula? [This section of the Formula Cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#add-a-test-to-the-formula) should get you started, and I'm happy to answer any related questions you might have. It's okay if you rather not, but it would be much appreciated if you could give this a try.

**Comment by yous** [comment]
Thank you for pointing that out. I found a nice HelloWorld example for Akka, ["Akka Main in Java"](http://www.lightbend.com/activator/template/akka-sample-main-java). Although it can't be ran without Java, akka formula actually doesn't have `depends_on :java` line. The example run with Lightbend Activator, but we can run it Maven as the post describes at the last. I can confirm it runs with Maven, but we have another dependency now. This is the sample test script, but depends on Java and Maven. Do you have any idea?

``` diff
diff --git a/Formula/akka.rb b/Formula/akka.rb
index 90f7323..d730c9b 100644
--- a/Formula/akka.rb
+++ b/Formula/akka.rb
@@ -24,4 +24,98 @@ class Akka < Formula
     bin.install_symlink libexec/"bin/akka"
     bin.install_symlink libexec/"bin/akka-cluster"
   end
+
+  test do
+    (testpath/"pom.xml").write <<-EOS.undent
+      <?xml version="1.0" encoding="UTF-8"?>
+      <project xmlns="http://maven.apache.org/POM/4.0.0"
+               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+               xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
+
+        <modelVersion>4.0.0</modelVersion>
+        <artifactId>akka-sample-main-java</artifactId>
+        <groupId>com.typesafe.akka.samples</groupId>
+        <name>Akka Main in Java</name>
+        <version>1.0</version>
+
+        <properties>
+          <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
+        </properties>
+
+        <dependencies>
+          <dependency>
+            <groupId>com.typesafe.akka</groupId>
+            <artifactId>akka-actor_2.11</artifactId>
+            <version>2.4.4</version>
+          </dependency>
+        </dependencies>
+
+      </project>
+    EOS
+    (testpath/"src/main/java/sample/hello/HelloWorld.java").write <<-EOS.undent
+      package sample.hello;
+
+      import akka.actor.Props;
+      import akka.actor.UntypedActor;
+      import akka.actor.ActorRef;
+
+      public class HelloWorld extends UntypedActor {
+
+        @Override
+        public void preStart() {
+          // create the greeter actor
+          final ActorRef greeter = getContext().actorOf(Props.create(Greeter.class), "greeter");
+          // tell it to perform the greeting
+          greeter.tell(Greeter.Msg.GREET, getSelf());
+        }
+
+        @Override
+        public void onReceive(Object msg) {
+          if (msg == Greeter.Msg.DONE) {
+            // when the greeter is done, stop this actor and with it the application
+            getContext().stop(getSelf());
+          } else
+            unhandled(msg);
+        }
+      }
+    EOS
+    (testpath/"src/main/java/sample/hello/Greeter.java").write <<-EOS.undent
+      package sample.hello;
+
+      import akka.actor.UntypedActor;
+
+      public class Greeter extends UntypedActor {
+
+        public static enum Msg {
+          GREET, DONE;
+        }
+
+        @Override
+        public void onReceive(Object msg) {
+          if (msg == Msg.GREET) {
+            System.out.println("Hello World!");
+            getSender().tell(Msg.DONE, getSelf());
+          } else
+            unhandled(msg);
+        }
+
+      }
+    EOS
+    (testpath/"src/main/java/sample/hello/Main.java").write <<-EOS.undent
+      package sample.hello;
+
+      public class Main {
+
+        public static void main(String[] args) {
+          akka.Main.main(new String[] { HelloWorld.class.getName() });
+        }
+      }
+    EOS
+    (testpath/"src/main/resources/application.conf").write <<-EOS.undent
+      akka {
+        loglevel = INFO
+      }
+    EOS
+    system "mvn compile exec:java -Dexec.mainClass='akka.Main' -Dexec.args='sample.hello.HelloWorld'"
+  end
 end
```

**Comment by apjanke** [comment]
I like the test overall.

If `akka` can't run without Java, then it should have a `depends_on :java` in the formula. Let's add it. This was probably an oversight in the original formula, and the sort of thing adding tests is designed to catch. :)

And the Maven use here is trivial: it's functioning mainly to download Akka, which isn't needed in this case because we already know where it's downloaded and located. The Maven config file and `mvn` call could be replaced with a simple `javac` call (maybe that sets `-classpath` appropriately) and then a `java` call to actually run it.

**Comment by yous** [comment]
@apjanke Thanks for explanation! I think I got this. The test works with my local machine, OS X 10.11. I introduced `depends_on :java` line as Akka 2.4.4 seems [work with Scala 2.11 and Java 8+](http://akka.io/downloads/). If it's wrong, please let me know.

**Comment by apjanke** [comment]
LGTM at first glance. Let's see how BrewTestBot likes it...

**Comment by apjanke** [comment]
TestBot likes it!

Merged. Thank you for your contribution to Homebrew!

**Comment by UniqMartin** [comment]
@yous Thanks for taking the time to contribute a good test for this formula! You rock!

**Pull request closed without merging**
