### PR TITLE
ruby 2.6.3

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@hsbt A new version of `ruby-build` for ruby 2.6.3 is still not released, is this intentional?

**Comment by 6temes** [comment]
@fxcoudert Sorry, just out of curiosity, why was this PR closed four days ago? 

There has been already a five days delay between the moment when ruby 2.6.3 was released, and it's availability through Brew. Is there anything that can be done to accelerate this?

**Comment by 6temes** [comment]
(my question is just to know what was wrong with @lembacon PR)

**Comment by lembacon** [comment]
@6temes This had actually been merged in https://github.com/Homebrew/homebrew-core/commit/6f105c2702cef90dd0a5acd9542ea66b765bce58.

**Comment by 6temes** [comment]
Right! I was confused with https://github.com/Homebrew/homebrew-core/pull/39175

Sorry for the trouble.

**Pull request closed without merging**
