### PR TITLE
libxml2 2.9.12

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Patch no longer applies. Upstream issue still seems to be open though: https://gitlab.gnome.org/GNOME/libxml2/-/issues/64

**Comment by bayandin** [comment]
> Patch no longer applies. Upstream issue still seems to be open though: https://gitlab.gnome.org/GNOME/libxml2/-/issues/64

This patch actually applies without problem, but the other two are not required anymore 🎉

**Comment by bayandin** [comment]
Fails:
- `brew linkage --test spatialite-tools` the same as in https://github.com/Homebrew/homebrew-core/pull/77693#issuecomment-846388303 but wasn't caught there because `spatialite-tools` doesn't depend on `proj@7` directly
- `brew test --retry --verbose lanraragi` (looks the same as in https://github.com/Homebrew/homebrew-core/pull/76601):
```
==> Testing lanraragi
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210523-13959-14abjdy.sb ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lanraragi.rb --verbose --retry
==> /usr/local/Cellar/lanraragi/0.7.6_2/bin/lanraragi
usage: dirname path
Can't do inplace edit on /usr/local/Cellar/lanraragi/0.7.6_2/bin//../libexec/redis.conf: Cannot make temp name: Operation not permitted.
Can't do inplace edit on /usr/local/Cellar/lanraragi/0.7.6_2/bin//../libexec/redis.conf: Cannot make temp name: Operation not permitted.

*** FATAL CONFIG FILE ERROR (Redis 6.2.3) ***
Reading the configuration file, at line 171
>>> 'logfile "<LRR_LOG_DIRECTORY>/redis.log"'
Can't open the log file: No such file or directory
SSLeay.c: loadable library and perl binaries are mismatched (got handshake key 0xfa80080, needed 0xf880080)
```
- On Mojave only `brew test --retry --verbose libxslt`
```
==> Testing libxslt
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210523-27898-lyjg03.sb ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libxslt.rb --verbose --retry
==> /usr/local/Cellar/libxslt/1.1.34_2/bin/xslt-config --version
==> /usr/local/Cellar/libxslt/1.1.34_2/bin/xslt-config --cflags --libs
==> /usr/bin/clang test.c -o test -I/usr/local/Cellar/libxml2/2.9.10_2/include/libxml2 -I/usr/local/Cellar/libxslt/1.1.34_2/include -L/usr/local/Cellar/libxslt/1.1.34_2/lib -L/usr/local/Cellar/libxml2/2.9.10_2/lib -lxslt -lxml2 -lz -lpthread -liconv -lm -lexslt
In file included from test.c:1:
/usr/local/Cellar/libxslt/1.1.34_2/include/libexslt/exslt.h:5:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

**Comment by bayandin** [comment]
The only failure left is preexisted `brew test --retry --verbose lanraragi`  (https://github.com/Homebrew/homebrew-core/pull/76601#issuecomment-834855562)

**Pull request closed without merging**
