### PR TITLE
monero 0.18.1.2

### PR DESCRIPTION
**Pull request by selsta**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
Thanks @selsta!

**Comment by chenrui333** [comment]
relates to #109752

**Review by chenrui333 — DISMISSED** [review]

**Comment by selsta** [comment]
Should I rebase and set revision back to 0 again?

**Comment by selsta** [comment]
@chenrui333 now it should work

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
