### PR TITLE
spirv-tools 2022.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
/tmp/spirv-tools-20220127-62855-1g4ahpa/SPIRV-Tools-2022.1/source/val/validate_image.cpp:75:10: error: use of undeclared identifier 'SpvImageOperandsNontemporalMask'
    case SpvImageOperandsNontemporalMask:
         ^
/tmp/spirv-tools-20220127-62855-1g4ahpa/SPIRV-Tools-2022.1/source/val/validate_image.cpp:635:14: error: use of undeclared identifier 'SpvImageOperandsNontemporalMask'
  if (mask & SpvImageOperandsNontemporalMask) {
             ^
```

**Comment by carlocab** [comment]
Bumping the resources might help.

**Comment by Porkepix** [comment]
> Bumping the resources might help.

I updated both `re2` and `spirv_headers` dependencies according to https://github.com/KhronosGroup/SPIRV-Tools/blob/v2022.1/DEPS
However this file also have some googletest thing as dependency which was not yet here, so I don't know if something have to be done about it.

**Comment by carlocab** [comment]
Thanks. Let's leave `googletest` alone for now. We can add it if we find that it's needed.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
