### PR TITLE
guile 3.0.9

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
non-surprised networking failure for `rtags` on 12

**Review by carlocab — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
networking failures on 11 and linux, merging now.

**Comment by xeron** [comment]
I'm getting:

```
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/ilarionov/Library/Caches/Homebrew/downloads/834d775e5d03dc39c416e2ade041ed0e4e8f01cc0b605fc21cef66bf13a34c31--b54263dc98b2700fa777745405ad7651601bcdc6..3bdcc3668fd8f9a5b6c9a313ff8d70acb32b2a52.patch
```

**Comment by p-linnane** [comment]
Run `brew update`. There should no longer be any patching in this version of the formula.

**Comment by xeron** [comment]
```
(dev) ilarionov@C02FG4HJMD6M:/opt/brew/Library/Taps/homebrew/homebrew-core[master]$ brew update
Already up-to-date.
(dev) ilarionov@C02FG4HJMD6M:/opt/brew/Library/Taps/homebrew/homebrew-core[master]$ git pull
Updating 821ee7cc0c5..5733f28160b
```

😮

**Pull request closed without merging**
