### PR TITLE
envoy 1.18.2

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Patch needs to be removed.

**Comment by nandahkrishna** [comment]
Latest is now `1.18.2`, removed the patch.

**Comment by carlocab** [comment]
Probably just doesn't support Mojave. Would be good to clarify this upstream.

**Comment by carlocab** [comment]
Based on your upstream issue it looks like others aren't able to build this on Mojave too. We can do `depends_on macos: :catalina` until that's resolved.

**Review by nandahkrishna — APPROVED** [review]

**Pull request closed without merging**
