### PR TITLE
php 8.3.0

### PR DESCRIPTION
**Pull request by RSickenberg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@RSickenberg thanks for the PR, can you update your commit msg as `php 8.3.0`, it is already in https://docs.brew.sh/Formula-Cookbook#commit

**Comment by RSickenberg** [comment]
> @RSickenberg thanks for the PR, can you update your commit msg as `php 8.3.0`, it is already in https://docs.brew.sh/Formula-Cookbook#commit

Sure.

**Comment by RSickenberg** [comment]
The issue here is this: 

```
PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.2.*.
  Current PHP version: 8.3.0.
  To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
  If you use PHP version higher than supported, you may experience code modified in a wrong way.
  Please report such cases at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer .
  Error: php-cs-fixer: failed
```

**Comment by RSickenberg** [comment]
@derrabus Do you have a suggestion here?

**Comment by derrabus** [comment]
Yes, it's this time of the year again. PHP CS Fixer always causes trouble here. In the past, we've solved this by forcing PHP CS Fixer to use the versioned formula of the previous PHP release.

Does that help you already? If not, I could take over and open a new PR where I cherry-pick your commit, #155312 and a patch that forces PHP CS Fixer to use PHP 8.2.

**Comment by RSickenberg** [comment]
Thanks @derrabus ! I found another approach which is to use the ENV `PHP_CS_FIXER_IGNORE_ENV` until they patch it but probably your solution is better. 

If this run doesn't pass, you can do your PHP PR ☺️

**Comment by derrabus** [comment]
> I found another approach which is to use the ENV `PHP_CS_FIXER_IGNORE_ENV` until they patch it

Please let's not go down that road. PHP CS Fixer tells us that they're not ready yet for PHP 8.3 and we should respect that.

**Comment by derrabus** [comment]
I've opened #155397.

**Comment by RSickenberg** [comment]
Closed in favor of #155397

**Pull request closed without merging**
