### PR TITLE
solarus 1.6.4

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
On Catalina and Mojave only:

```
/tmp/solarus-20200422-47930-1rowstt/include/solarus/core/Size.h:22:10: fatal error: 'glm/vec2.hpp' file not found
[  3%] Building CXX object CMakeFiles/solarus.dir/src/core/CurrentQuest.cpp.o
#include <glm/vec2.hpp>
         ^~~~~~~~~~~~~~
/usr/bin/clang++  -DSOLARUS_DEFAULT_QUEST=\".\" -DSOLARUS_DEFAULT_QUEST_HEIGHT=240 -DSOLARUS_DEFAULT_QUEST_WIDTH=320 -DSOLARUS_FILE_LOGGING -DSOLARUS_WRITE_DIR=\"Solarus\" -Dsolarus_EXPORTS -I/tmp/solarus-20200422-47930-1rowstt/build/include -I/tmp/solarus-20200422-47930-1rowstt/include -isystem /tmp/solarus-20200422-47930-1rowstt/include/solarus/third_party -isystem /tmp/solarus-20200422-47930-1rowstt/include/solarus/third_party/snes_spc -isystem /usr/local/include/libmodplug -isystem /usr/local/include/SDL2 -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenAL.framework/Headers -isystem /usr/local/opt/libvorbis/include -isystem /usr/local/opt/libogg/include -isystem /usr/local/include/luajit-2.0 -iframework /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks  -std=c++11 -stdlib=libc++ -I/usr/local/opt/physfs/include -Wno-error -Wall -Wextra -Wno-unknown-pragmas -Wno-fatal-errors -DNDEBUG -O3 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.7 -fPIC   -o CMakeFiles/solarus.dir/src/core/CurrentQuest.cpp.o -c /tmp/solarus-20200422-47930-1rowstt/src/core/CurrentQuest.cpp
1 error generated.
```

**Comment by EricFromCanada** [comment]
I'm going to see how it fares after updating `glm`.

**Comment by bayandin** [comment]
> I'm going to see how it fares after updating `glm`.

Let me try one more random thing

**Comment by bayandin** [comment]
So it magically works. We can merge this one or we could try to update `glm` and then revisit this one (to check if we still need to have this explicit inclusion).

**Comment by Bo98** [comment]
`glm` was awkward to update because upstream removed the install target so it all needs to be installed "manually" with `include.install` etc. Upstream have no intentions of restoring the install target.

**Pull request closed without merging**
