### PR TITLE
CONTRIBUTING: add environment var to ensure local formula is used

### PR DESCRIPTION
**Pull request by jonclayden**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Simple documentation update to reflect changes in Homebrew 4.0.

### CODE REVIEW

**Review by Rylan12 — COMMENTED** [review]
Thanks, this is a really good start! I think we might want to update the paragraph before this one, too, to mention that you may need to run `brew tap homebrew/core` if it's not installed already.

**Comment by jonclayden** [comment]
Thanks for the review, and the helpful feedback. I've amended that paragraph, and also the list of steps further down.

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me!

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @jonclayden!

**Pull request merged**
