### PR TITLE
arduino-cli 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by Efrat19**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by dawidd6 — APPROVED** [review]

**Comment by fxcoudert** [comment]
- This version is tagged as prerelease, which is not acceptable for Homebrew core:

Capture d’écran 2019-10-07 à 00 19 25

- Please squash all changes into a single commit, with commit message `formula x.y.z (new formula)`

**Comment by Efrat19** [comment]
@fxcoudert I downgraded the version and squashed the commits according to your guide

**Comment by dawidd6** [comment]
One more thing, commit should be named like the PR title: `arduino-cli 0.5.0 (new formula)`.

**Comment by Efrat19** [comment]
@dawidd6 I named the commit according to @fxcoudert comment:
`Please squash all changes into a single commit, with commit message formula x.y.z (new formula)`

now I changed the pr name accordingly.
Is that ok now?

**Comment by dawidd6** [comment]
Will be ok without the `formula` at the beginning and without the underscore.

**Comment by dawidd6** [comment]
Nice, thanks for your contribution to Homebrew!

**Comment by Efrat19** [comment]
@dawidd6 done

**Comment by SMillerDev** [comment]
Thanks @Efrat19! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
