### PR TITLE
rethinkdb: replace download server url

### PR DESCRIPTION
**Pull request by gabor-boros**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

~- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?`~

~- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?~

~- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?~

-----

This PR is opened because RethinkDB download server [will be replaced](https://rethinkdb.com/blog/download-server-changes) at 29th of May (this Friday). We would like to make sure we are prepared, so if you agree with the change, please approve the PR but let us merge it 😊 😇

### CODE REVIEW

**Comment by gabor-boros** [comment]
@Moisan / @iMichka May I have a review on this please?

**Comment by SMillerDev** [comment]
CI needs to be green, and for that we have to wait until the change is done. There isn't much to review either, either it works or it doesn't.

**Comment by gabor-boros** [comment]
@SMillerDev Thanks for the quick response. By reviewing I meant Approve/Decline the PR. As far as I can see the tests are failing with a `'revision 1' should be removed` error. Although it seems to be straightforward, should I remove the revision or should be replaced by something else?

**Comment by SMillerDev** [comment]
I know what reviewing means, but since approval will mean automated merge we can't do that until the new URL is ready.

If it says `x should be removed` you should remove x.

**Comment by gabor-boros** [comment]
Thanks, revision removed. Waiting for the status checks.

**Comment by gabor-boros** [comment]
@SMillerDev The first failure reason was `revision should be removed` now it's `revision should not decrease (from 1 to 0)` so what's the truth? :D

**Comment by gabor-boros** [comment]
@SMillerDev / @Moisan / @iMichka How could I fix this issue?

**Comment by gabor-boros** [comment]
@dawidd6 sorry for pinging you, but you seem active. 

> The first failure reason was revision should be removed now it's revision should not decrease (from 1 to 0) so what's the truth?

How could I fix this issue? We have replaced our download servers and users cannot install via brew because this PR is pending.

**Comment by dawidd6** [comment]
To be honest I would leave the revision line as it was. Cause the source archive is still the same and nothing really changed.

**Comment by gabor-boros** [comment]
If I leave the revision line I get an error to remove that.

**Comment by dawidd6** [comment]
Just ignore it.

**Comment by gabor-boros** [comment]
I'd ignore it, but CI tests will fail: https://github.com/Homebrew/homebrew-core/runs/719464515.

If you say that I have to put it back and you will merge the PR with the failing test I'll be fine too, but I guess thats not the point.

**Comment by dawidd6** [comment]
Put it back. I'll merge it.

**Comment by gabor-boros** [comment]
@dawidd6 `revision 1` is back. Thank you in advance!

**Comment by gabor-boros** [comment]
@dawidd6 / @SMillerDev  any update on this?

**Comment by dawidd6** [comment]
Thanks for the ping, forgot about it. Merged.

**Pull request merged**
