### PR TITLE
go 1.7.5

### PR DESCRIPTION
**Pull request by tsuna**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cblecker** [comment]
The upstream patch block on line 18-23 needs to be removed from the stable section :)

**Comment by tsuna** [comment]
Gosh, that'll teach me to skip building it – I'm already on go 1.8rc2 and just upgraded to 1.8rc3 and I couldn't find a way to convince homebrew to let me install 1.7.5 without uninstalling the 1.8* versions that I have (and would like to keep around).

**Comment by tsuna** [comment]
OK, I amended my commit and I temporarily moved the 1.8* versions I had out of the way to be able to convince homebrew to build 1.7.5, so I can confirm it works.

**Comment by cblecker** [comment]
LGTM

**Review by cblecker — APPROVED** [review]
LGTM

**Comment by DomT4** [comment]
May wish to update the `gotools` hash too. It's trailing behind the current 1.7 branch a bit, most recent commit seems to be `6220cba6419b2bf78aad19d85c347ecc0fda2b53`.

**Comment by tsuna** [comment]
I'd be happy to do that in a separate pull request.

**Comment by DomT4** [comment]
It'd be better to do it in this one, if we're gonna do it, otherwise you'll get some people pouring bottles with the older tools until CI rolls a new set of bottles with the newer tools. Given there's a Qt5 build in the CI queue currently this PR is a fair while off being green either way, alas.

**Comment by tsuna** [comment]
Fair enough.  Done.

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
