### PR TITLE
catch2 3.0.1

### PR DESCRIPTION
**Pull request by ChrisThrasher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
Building on https://github.com/Homebrew/homebrew-core/pull/101783 and fixing more CI issues.

**Comment by ChrisThrasher** [comment]
CI is failing on the `pprint` downstream project which also uses Catch2. Because it expects Catch2 v2 header names, I'm not sure how we can make it work with Catch2 v3 unless we can ship both major versions simultaneously.

**Comment by bayandin** [comment]
> tream project which also uses Catch2. Because it expects Catch2 v2 header names, I'm not sure how we can make it work with Catch2 v3 unless we can ship both major versions simultaneously.

I've removed `catch2` dependency from `pprint`

**Comment by ChrisThrasher** [comment]
Looks like `pprint` is still giving us problems in CI.

**Comment by bayandin** [comment]
Test fails on linux:

```==> Testing catch2
==> /home/linuxbrew/.linuxbrew/bin/g++-11 test.cpp -std=c++14 -L/home/linuxbrew/.linuxbrew/Cellar/catch2/3.0.1/lib -lCatch2 -lCatch2Main -o test
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/catch2/3.0.1/lib/libCatch2Main.a(catch_main.cpp.o): in function `main.cold':
catch_main.cpp:(.text.unlikely+0x4): undefined reference to `Catch::Session::~Session()'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/catch2/3.0.1/lib/libCatch2Main.a(catch_main.cpp.o): in function `main':
catch_main.cpp:(.text.startup+0x1b): undefined reference to `Catch::Session::Session()'
/home/linuxbrew/.linuxbrew/bin/ld: catch_main.cpp:(.text.startup+0x2d): undefined reference to `Catch::Session::~Session()'
/home/linuxbrew/.linuxbrew/bin/ld: catch_main.cpp:(.text.startup+0x4a): undefined reference to `Catch::Session::applyCommandLine(int, char const* const*)'
/home/linuxbrew/.linuxbrew/bin/ld: catch_main.cpp:(.text.startup+0x59): undefined reference to `Catch::Session::run()'
collect2: error: ld returned 1 exit status
```

**Comment by ChrisThrasher** [comment]
> Test fails on linux:

Could it be that we're linking the libraries in the wrong order?

**Comment by ChrisThrasher** [comment]
I just realized in fixing the linker issue I accidentally removed [this commit](https://github.com/Homebrew/homebrew-core/commit/2a9f8308e2805c4d04906b322f3310523bd645c8). My apologies. I can't cherry pick that commit back into this branch I will re-add those changes.

**Review by SMillerDev — APPROVED** [review]
Thanks @ChrisThrasher  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
