### PR TITLE
organize-tool 2.4.2

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by p-linnane** [comment]
Looks like the new `pyobjc-framework-cocoa` resource is macOS-only.

**Comment by p-linnane** [comment]
Opened an upstream issue: https://github.com/tfeldmann/organize/issues/305

**Comment by tfeldmann** [comment]
I don't understand why `pyobjc-core` and `pyobjc-framework-cocoa` are even added here. They are optional dependencies of `send2trash`. In organize they have the correct platform markers:

`poetry.lock`
```toml
[package.dependencies]
pyobjc-framework-Cocoa = {version = "*", optional = true, markers = "sys_platform == \"darwin\" and extra == \"nativelib\""}
pywin32 = {version = "*", optional = true, markers = "sys_platform == \"win32\" and extra == \"nativelib\""}
```

**Comment by cho-m** [comment]
> I don't understand why `pyobjc-core` and `pyobjc-framework-cocoa` are even added here. They are optional dependencies of `send2trash`. In organize they have the correct platform markers:
> 
> `poetry.lock`
> 
> ```toml
> [package.dependencies]
> pyobjc-framework-Cocoa = {version = "*", optional = true, markers = "sys_platform == \"darwin\" and extra == \"nativelib\""}
> pywin32 = {version = "*", optional = true, markers = "sys_platform == \"win32\" and extra == \"nativelib\""}
> ```

Homebrew uses `pipgrip` to resolve dependencies. It sees `pyproject.toml` has https://github.com/tfeldmann/organize/blob/main/pyproject.toml#L38:
```toml
Send2Trash = { version = "^1.8.2", extras = ["nativeLib"] }
```

And then resolves dependencies in `Send2Trash` based on setup.cfg with the extras applied https://github.com/arsenetar/send2trash/blob/master/setup.cfg#L46-L48
```cfg
nativeLib = 
    pywin32; sys_platform == "win32"
    pyobjc-framework-Cocoa; sys_platform == "darwin"
```

As long as `brew [bump|bump-formula-pr]` was run on macOS, then these will get added to formula. 

If command is run on Linux, then they may get removed from formula.

**Comment by p-linnane** [comment]
Resource names were normalized (since that's the default now) when the PR was opened. That required normalizing them manually in the `install` block to prevent the macOS-only resources from installing on Linux. That's been fixed here now, so we should be good. Thanks @branchvincent for the pointer. Apologies for the confusion @tfeldmann 🙏

**Review by iMichka — APPROVED** [review]

**Comment by chenrui333** [comment]
👍

**Pull request merged**
