### PR TITLE
mkvtoolnix 9.9.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by felixbuenemann** [comment]
@ilovezfs Does this compile fine for you?

I'm getting the following error (also for `--HEAD`):

```
checking for DocBook XSL root directory... not found
configure: error: DocBook XSL stylesheets are required for building.
```

It looks like docbook is required since commit https://github.com/mbunkus/mkvtoolnix/commit/113450f23cbf5e1881d4fd2e52db31a74314c005.

I had to add the following patch to get the build to succeed:

```patch
--- mkvtoolnix.rb.orig	2017-02-20 23:30:40.000000000 +0100
+++ mkvtoolnix.rb	2017-02-20 23:30:22.000000000 +0100
@@ -21,6 +21,7 @@
 
   depends_on "pkg-config" => :build
   depends_on :ruby => ["1.9", :build]
+  depends_on "docbook-xsl" => :build
   depends_on "libogg"
   depends_on "libvorbis"
   depends_on "flac" => :recommended
@@ -50,12 +51,14 @@
     vorbis = Formula["libvorbis"]
     ebml = Formula["libebml"]
     matroska = Formula["libmatroska"]
+    docbook_xsl = Formula["docbook-xsl"]
 
     args = %W[
       --disable-debug
       --prefix=#{prefix}
       --without-curl
       --with-boost=#{boost.opt_prefix}
+      --with-docbook-xsl-root=#{docbook_xsl.opt_prefix/"docbook-xsl"}
       --with-extra-includes=#{ogg.opt_include};#{vorbis.opt_include};#{ebml.opt_include};#{matroska.opt_include}
       --with-extra-libs=#{ogg.opt_lib};#{vorbis.opt_lib};#{ebml.opt_lib};#{matroska.opt_lib}
     ]
```

I didn't add a dependency on docbook itself, because it was happy with using `/usr/bin/xsltproc`.

**Comment by ilovezfs** [comment]
Yuck. Did upstream stop including the docs or something?

**Comment by ilovezfs** [comment]
```

## Build system changes

* Up to and including release 9.8.0 the man pages and their translations came
  pre-built and bundled with the source code. Those pre-built files have now
  been removed and must be built during the build process. Therefore the tool
  "xsltproc" and the DocBook XSL stylesheets for man pages are now required
  dependencies. Additionally the tool "po4a" must be installed for the
  translated man pages to be built and installed, though this is optional.

  In order to facilitate finding the new requirements new options have been
  added to confiure: "--with-xsltproc=prog", "--with-docbook-xsl=dir",
  "--with-po4a=prog" and "--with-po4a-translate=prog.
* pugixml detection will be attempted via "pkg-config" first. If that fails,
  "configure" will fall back to the previous method of trying just to compile
  and link a test program with the standard include and library locations.
  Implements #1891.
```

**Comment by ilovezfs** [comment]
@felixbuenemann PR refreshed.

**Pull request closed without merging**
