### PR TITLE
chromaprint: enable `fpcalc` utility

### PR DESCRIPTION
**Pull request by kolen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Enable build of `fpcalc` utility which prints acoustid of audio file. Used by [Musicbrainz Picard](https://picard.musicbrainz.org/) (IMHO the most popular use of chromaprint is via this app), also [can be used](http://beets.readthedocs.io/en/v1.4.3/plugins/chroma.html) by [beets](http://beets.io/) however seems that it can consume library version too.

To be able to decode various audio formats, it needs ffmpeg, so ffmpeg `:recommended` dependency is added. `fpcalc` is built only if `ffmpeg` is enabled.

### CODE REVIEW

**Comment by ilovezfs** [comment]
This was removed because it can cause a circular dependency with ffmpeg. We'll either need to vendor chromaprint into the ffmpeg formula, or have a separate fpcalc formula. The latter is probably a cleaner solution.

**Comment by JCount** [comment]
@kolen So, probably the simplest way to prevent a recursive dependency issue is to remove the `--with-chromaprint` option from the `ffmpeg` formula, and simply build the `fpcalc` utility by default using the audio conversion libraries from `ffmpeg`, (as your PR currently does).

When comparing the features and utility of `fpcalc` to what `ffmpeg` offers when built with `chromaprint`, `fpcalc` seems to offer several advantages.

Given these two facts, the logical decision seems to be to build `fpcalc` by default and simply kill the `--with-chromaprint` option in `ffmpeg`.

Any thoughts here @ilovezfs?

**Comment by ilovezfs** [comment]
@JCount that may work.

CC @zmwangx for any thoughts on removing the chromaprint option from ffmpeg.

**Comment by zmwangx** [comment]
No problem with removing --with-chromaprint personally, but what does analytics say (when you exclude install-with-all-options-under-the-sun events)?

**Comment by ilovezfs** [comment]
https://gist.github.com/ilovezfs/1b8f932cd4738aee7e649e7c3a3a1f73

You'll have to scroll to the far right to get past the sun.

**Comment by ilovezfs** [comment]
(install events for last 30 days)

**Comment by zmwangx** [comment]
A less obstructed view:
shot

I'm slightly worried about the ~1000 events for the chromaprint, fdk-aac, fontconfig combo and ~500 events for the chromaprint, vidstab, vorbis combo. But I strongly suspect I'm misinterpreting the leftmost column. Are those counts or ranks?

> When comparing the features and utility of fpcalc to what ffmpeg offers when built with chromaprint, fpcalc seems to offer several advantages.

**Comment by ilovezfs** [comment]
Those are ranks. The counts are on the far right.

**Comment by zmwangx** [comment]
Okay, pretty safe removal then.

(The counts only fit into one screen when I reduce the font size to 2px...)

**Comment by ilovezfs** [comment]
To be fair to the tool, this is the output in a normal size terminal:
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics ffmpeg|grep chromaprint
  13 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |    240 |   0.32%
  44 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |     26 |   0.03%
  53 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |     21 |   0.03%
  74 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |     15 |   0.02%
 123 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      8 |   0.01%
 138 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      7 |   0.01%
 155 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      6 |   0.01%
 181 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      5 |   0.01%
 199 | ffmpeg --with-libebur128 --with-chromaprint --with-lib |      5 |   0.01%
 220 | ffmpeg --with-chromaprint                              |      4 |   0.01%
 221 | ffmpeg --with-chromaprint --with-fdk-aac               |      4 |   0.01%
 274 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      3 |   0.00%
 275 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      3 |   0.00%
 276 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      3 |   0.00%
 277 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      3 |   0.00%
 278 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      3 |   0.00%
 279 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      3 |   0.00%
 409 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      2 |   0.00%
 410 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      2 |   0.00%
 453 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 454 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 455 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 456 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 457 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 458 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 459 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 460 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 461 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 462 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 463 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 464 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 465 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 466 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 467 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      2 |   0.00%
 468 | ffmpeg --with-chromaprint --with-fdk-aac --with-tesser |      2 |   0.00%
 469 | ffmpeg --with-chromaprint --with-libvidstab --with-lib |      2 |   0.00%
 470 | ffmpeg --with-chromaprint --with-tesseract --with-open |      2 |   0.00%
 933 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      1 |   0.00%
 934 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      1 |   0.00%
 935 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      1 |   0.00%
 936 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      1 |   0.00%
 937 | ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with |      1 |   0.00%
 995 | ffmpeg --with-chromaprint --with-fdk-aac --with-fontco |      1 |   0.00%
 996 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      1 |   0.00%
 997 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      1 |   0.00%
 998 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      1 |   0.00%
 999 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      1 |   0.00%
1000 | ffmpeg --with-chromaprint --with-fdk-aac --with-libass |      1 |   0.00%
```

**Comment by zmwangx** [comment]
I wonder why --with-libebur128 is before --with-chromaprint.

**Comment by ilovezfs** [comment]
I think because it doesn't exist?

**Comment by zmwangx** [comment]
Yeah, that makes sense.

**Comment by nijikon** [comment]
Will take a look at this tomorrow.

**Comment by JCount** [comment]
@probot-stale[bot] this is not stale unless @nijikon decides it is.

**Comment by ilovezfs** [comment]
@nijikon what's the status here?

**Comment by ilovezfs** [comment]
@kolen Thank you for this PR. We're going to pass on it for now since it creates a circular dependency.

**Pull request closed without merging**
