### PR TITLE
clojure: make "rlwrap" recommended dependency

### PR DESCRIPTION
**Pull request by arkrost**

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can you explain why? Context and impact of the change

**Comment by rakkesh** [comment]
@fxcoudert this seems like a reasonable change for users to avoid couple of additional dependencies, `rlwrap` and `readline`, which are not required unless one is performing command line editing or using `readline` history.

We can accept this change if @puredanger, who maintains a `homebrew` [formula](https://github.com/clojure/brew-install/blob/946c0755a3d249c9b36da232b56e523a72713dd4/src/main/resources/clojure.rb) under clojure's github organization, doesn't have any objections.

**Comment by fxcoudert** [comment]
Given that the dependencies are very small compared to the `clojure` install itself, we are going to decline for now and keep this formula optionless. Thanks @arkrost for the suggestion, and @rakkesh for the context.

**Comment by puredanger** [comment]
This would be ok with me, but I would prefer to make the change in our next release of the clj tool.

**Pull request closed without merging**
