### PR TITLE
open-scene-graph: Update links

### PR DESCRIPTION
**Pull request by ts826848**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Development appears to have moved to GitHub; the latest release on the
OSG website is 3.4.0, but the GitHub repo is on 3.5.5.

### CODE REVIEW

**Comment by aw1621107** [comment]
Build of 3.4.0 failed with ffmpeg errors, which has been fixed for some time. 3.5.5 still fails, but it appears to be a known failure, as [this](https://github.com/Homebrew/legacy-homebrew/pull/46388) PR tries to address it.

Applying those changes manually, though, still result in a build failure due to the linker being unable to find the symbol `_locale_charset`.

**Comment by aw1621107** [comment]
Gist [here](https://gist.github.com/aw1621107/8c2e4573d562ec2e7f851d1fe1b72094)

**Comment by MikeMcQuaid** [comment]
> Have you built your formula locally with brew install --build-from-source <formula>, where <formula> is the name of the formula you're submitting?

Did this work for you locally?

**Comment by aw1621107** [comment]
No, the problem now is different than the problem with 3.4.0. It was with pretty much all the options, though... I'll try a build after vtk finishes compiling

**Comment by aw1621107** [comment]
I guess my other question is should I take out the "revision 1" in the formula even if it isn't really related to the rest of the PR?

**Comment by MikeMcQuaid** [comment]
Yes, please. Thanks!

**Comment by aw1621107** [comment]
No, it doesn't build. It fails with the same error as the one mentioned in issue [#46356](https://github.com/Homebrew/legacy-homebrew/issues/46356) from legacy-homebrew.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `open-scene-graph 3.5.5`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
