### PR TITLE
molecule: move to correct Formula directory

### PR DESCRIPTION
**Pull request by dunn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Thanks for catching this @alyssais!

### CODE REVIEW

**Review by alyssais — APPROVED** [review]

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by woodruffw** [comment]
@jvrplmlmn Any thoughts on this failure?

**Comment by dunn** [comment]
Looks like the URL it's trying to hit is `http+docker://localunixsocket/version`, which means Docker need to be running, I guess.

**Comment by MikeMcQuaid** [comment]
Thanks @dunn. I'd avoid test failures in this case.

**Comment by jvrplmlmn** [comment]
Weird, why was the CI failure not detected on https://github.com/Homebrew/homebrew-core/pull/8609 ? When I wrote the tests and ran them locally the Docker daemon was available, so I didn't thought of that scenario.

I guess that since the `test` section runs Ruby code, that it will be possible to verify that Docker is running, and if not, do not run the second test scenario.

Thoughts?

**Pull request merged**
