### PR TITLE
cataclysm 0.F

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> An exception occurred within a child process:
  Minitest::Assertion: User template directory should exist.

**Comment by chenrui333** [comment]
This is an UI app.

**Comment by chenrui333** [comment]
Close for now (dont know how to fix the test even though I can run it successfully in my local)

**Comment by EricFromCanada** [comment]
When launching the app it finds a bunch of [issues in its JSON files](https://www.reddit.com/r/cataclysmdda/comments/kfynyp/after_a_couple_hours_fixing_failed_to_visit/) which need to be paged through to get to the main screen. It initially creates only the `config` directory; only after that's done does it create `templates` and `save`. The game still launches fine, though. Removing the last two checks should allow the test to pass.

**Pull request closed without merging**
