### PR TITLE
zero-install 2.14.1

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-system failed at "/private/tmp/zero-install-20191102-59564-161pchu/0install-2.14.1/opamroot/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml".

#=== ERROR while compiling ocaml-system.4.08.1 ================================#
# context              2.0.5 | macos/x86_64 |  | https://opam.ocaml.org#9aeec911
# path                 /private/tmp/zero-install-20191102-59564-161pchu/0install-2.14.1/opamroot/default/.opam-switch/build/ocaml-system.4.08.1
# command              /private/tmp/zero-install-20191102-59564-161pchu/0install-2.14.1/opamroot/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml
# exit-code            71
# env-file             /private/tmp/opam-brew-59576/ocaml-system-59576-548b09.env
# output-file          /private/tmp/opam-brew-59576/ocaml-system-59576-548b09.out
### output ###
# sandbox-exec: sandbox_apply_container: Operation not permitted
```

**Comment by Bo98** [comment]
Try `--disable-sandboxing` as per [Infer](https://github.com/Homebrew/homebrew-core/blob/064775d94596e11e29e491ae888db7efb6f60108/Formula/infer.rb#L48). It interferes with Homebrew's sandbox.

**Comment by Bo98** [comment]
Oh boy, OCaml never fails to liven things up.

**Comment by fxcoudert** [comment]
```
==> opam config exec make
dune build --root=. --profile=release @install
File "opamroot/default/bin/dune", line 1, characters 0-0:
Error: Invalid dune file
make: *** [all] Error 1
```

**Comment by Bo98** [comment]
Blergh.

Apparently `dune` recursively checks and _expects_ every single file called `dune` to be a "dune file". The problem is, it can recursively get to `opamroot/default/bin/dune` which is the `dune` binary itself...

Could not find any option to prevent this behaviour so I guess we'll try put the `OPAMROOT` at `Dir.mktmpdir`. I should have probably made it something like
```
Dir.mktmpdir("opamroot") do |opamroot|
   ENV["OPAMROOT"] = opamroot
   # build ...
end
```
so that it cleans up after itself.

**Comment by Bo98** [comment]
Gonna have to use the SDK fix to get curl working on Mojave anyway

**Pull request closed without merging**
