### PR TITLE
passenger: fix vendored boost lib compilation issue with latest clang

### PR DESCRIPTION
**Pull request by CamJN**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
> 373 changed files with 18,295 additions and 5,541 deletions

1. How huge is that patch? What is it doing?
2. Can we modify the test so it fails when `nginx` is updated?

**Comment by CamJN** [comment]
@fxcoudert the patch upgrades boost like the title says. As for the test, i'd love to help but i've asked why the test isn't run and no-one answered me.

**Comment by daBee** [comment]
Is there a rollback for this?  The history isn't print out properly:

https://github.com/Homebrew/homebrew-core/commits/master/Formula/passenger.rb

**Comment by iMichka** [comment]
Has this patch been merged upstream? Can you provide a link to the pull request?

**Comment by CamJN** [comment]
It’s a modified version of this commit  (https://github.com/phusion/passenger/commit/f57413297c91090656a6130b60c2a2a63e5d7d67) It has been made to apply cleanly to 6.0.2.

This one doesn’t touch the changelog or dev directory. Since it’s based on a release tarball it doesn’t have a dev dir and the changelog at head is different than at 6.0.2’s release so that part of the patch would not apply cleanly.

There’s no PR because I’m a passenger dev.

**Comment by daBee** [comment]
I'm sorry, but I'm unclear as to where this stands.  I can't roll back. Is there an update coming to fix this?

**Comment by CamJN** [comment]
@daBee you can build passenger from source, that should work.

**Comment by CamJN** [comment]
So can somebody please describe the process where the tests are run for dependant formulae when their dependencies are updated? I manually recreated the test I made for passenger, and if I have a matching nginx + passenger it starts and runs with a zero return value, and if I test with a mismatch it returns non-zero. There's obviously something more that I need to do, but I don't know what and I can't fix the test until I know why it's broken.

**Comment by CamJN** [comment]
Anyone? I honestly want to help improve this situation, I don't want to cause more breakage in the future.

**Comment by daBee** [comment]
Sorry, can't help ya.  Wish I could.

**Comment by SMillerDev** [comment]
> So can somebody please describe the process where the tests are run for dependant formulae when their dependencies are updated? I manually recreated the test I made for passenger, and if I have a matching nginx + passenger it starts and runs with a zero return value, and if I test with a mismatch it returns non-zero. There's obviously something more that I need to do, but I don't know what and I can't fix the test until I know why it's broken.

Bringing in the techsupport 😄 . @MikeMcQuaid could you explain this?

**Comment by MikeMcQuaid** [comment]
> So can somebody please describe the process where the tests are run for dependant formulae when their dependencies are updated?

If formula B depends on formula A then when formula A is updated and if formula B has a bottle and a test it will install the existing bottle of B and run the `test do` block and check `brew linkage` on formula B. If this fails: it will fail CI. As nothing `brew uses passenger` this is not happening for this PR.

**Comment by CamJN** [comment]
@MikeMcQuaid So am I correct that because `brew uses nginx ` doesn't return `passenger` the CI won't test passenger when nginx is updated? Is that because passenger only depends on nginx for build & test, not for install (to make it optional)? If so might it be a good idea to extend the dependency check to include things that use the recently updated formula for build or test?

**Comment by daBee** [comment]
@CamJN I would say that should be the case.  I would suggest treat each package as independent as possible due to the experience I've had, outside of these internal version conflicts.  `Passenger` directives inside nginx.conf change, such as **passenger_root**, **passenger_ruby** and the **load_module ngx_http_passenger_module.so**.  Even on `CentOS 7`, all of these are pinched off into a file of its own:  **include /etc/nginx/conf.d/*.conf;** so feedback would have to reflect that, as all of these directives are basically dependencies.  And you know that `Passenger` has its own feedback coming back from **brew info passenger**.  

As I see it, the Mac is a huge development platform, and newcomers to the `Passenger` package can spend a lot of time troubleshooting all these, as I have.

**Comment by MikeMcQuaid** [comment]
> I just checked and `brew uses` has `--include-build` and `--include-test` already, so the change to the CI script would likely be very small and simple, if that is indeed what needs to happen.

That change to the CI script would be small and simple but will massively increase the amount of CI time spent building reverse dependencies so I'd be strongly 👎. Additionally, if changes to `nginx` can break `passenger`'s bottle then it's not really a build-time dependency at that point.

**Comment by CamJN** [comment]
@MikeMcQuaid Yeah, Nginx's dynamic module support is still very immature. So when Nginx updates all dynamic modules need to be rebuilt. I guess that Passenger is the first formula to ship a dynamic nginx module so it's the guinea pig for figuring out how to deal with such issues. It feels a bit odd to make Passenger depend on nginx at runtime since Apache+Passenger works without Nginx, as does Passenger standalone, but I suppose we could just tell people in the caveats that uninstalling nginx is fine if they don't use it. 

I just checked, and there are only 30 additional dependencies in all of the homebrew-core formulae if you add just the the `--include-test` flag. While I realize certain formulae are updated far more often than others, the numbers here don't seem too bad.

```
   4 "cmake"
   3 "php"
   3 "httpd"
   2 "python@2"
   2 "python"
   2 "pkg-config"
   2 "consul"
   1 :xcode
   1 :java
   1 "ruby"
   1 "ocaml"
   1 "nginx"
   1 "lua@5.1"
   1 "libfaketime"
   1 "glslang"
   1 "glm"
   1 "freeglut"
   1 "cabal-install"
   1 "bind"
```

**Comment by MikeMcQuaid** [comment]
> I just checked, and there are only 30 additional dependencies in all of the homebrew-core formulae if you add just the the `--include-test` flag. While I realize certain formulae are updated far more often than others, the numbers here don't seem too bad.

Thanks for digging in there. Yes, `--include-test` seems to be a reasonable addition in this case. Could you submit a PR to modify https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb accordingly? Thanks!

**Comment by CamJN** [comment]
@MikeMcQuaid done: https://github.com/Homebrew/homebrew-test-bot/pull/245

**Comment by zbeekman** [comment]
The CI files have been deleted. Is this ready? Should we push this through CI again to re-bottle?

**Comment by CamJN** [comment]
Depends if the patch is deemed acceptable. I know it's huge, but boost is huge and it needed upgrading to allow the new cli tools to build it on mojave.

**Comment by MikeMcQuaid** [comment]
@CamJN Is the patch committed to an upstream stable/master branch? If not: when would it be?

**Comment by CamJN** [comment]
@MikeMcQuaid I addressed this here: https://github.com/Homebrew/homebrew-core/pull/38435#issuecomment-478615324

Basically the commit I landed on the then-HEAD of the stable branch won’t apply cleanly to the 6.0.2 release due to conflicts in the changelog and dev scripts directory. So this commit omits the conflicting changes (they aren’t needed for homebrew anyway)

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Review by MikeMcQuaid — APPROVED** [review]
@CamJN Sorry for making you repeat yourself but thanks for explaining. 👍 from me.

**Comment by CamJN** [comment]
Thanks @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
Thanks to you too, @CamJN!

**Pull request closed without merging**
