### PR TITLE
fmt 5.0.0

### PR DESCRIPTION
**Pull request by SuperWig**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The test isn't passing:
```
==> brew test fmt --verbose
==> FAILED
Testing fmt
/usr/bin/sandbox-exec -f /tmp/homebrew20180522-29032-1fa2lum.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fmt.rb --verbose
==> /usr/bin/clang++ test.cpp -o test -I/usr/local/Cellar/fmt/5.0.0/include -L/usr/local/Cellar/fmt/5.0.0/lib -lfmt
In file included from test.cpp:3:
In file included from /usr/local/Cellar/fmt/5.0.0/include/fmt/format.h:40:
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:193:15: error: no template named 'add_rvalue_reference' in namespace 'std'; did you mean 'add_lvalue_reference'?
typename std::add_rvalue_reference<T>::type declval() FMT_NOEXCEPT;
         ~~~~~^~~~~~~~~~~~~~~~~~~~
              add_lvalue_reference
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1083:50: note: 'add_lvalue_reference' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS add_lvalue_reference
                                                 ^
In file included from test.cpp:3:
In file included from /usr/local/Cellar/fmt/5.0.0/include/fmt/format.h:40:
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:311:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  FMT_DISALLOW_COPY_AND_ASSIGN(basic_buffer);
  ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:168:24: note: expanded from macro 'FMT_DISALLOW_COPY_AND_ASSIGN'
    Type(const Type &) FMT_DELETED; \
                       ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:164:23: note: expanded from macro 'FMT_DELETED'
#define FMT_DELETED = delete
                      ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:311:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:169:34: note: expanded from macro 'FMT_DISALLOW_COPY_AND_ASSIGN'
    void operator=(const Type &) FMT_DELETED
                                 ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:164:23: note: expanded from macro 'FMT_DELETED'
#define FMT_DELETED = delete
                      ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:415:7: error: too many arguments provided to function-like macro invocation
      "formatting of wide characters into a narrow output is disallowed");
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:783:12: note: macro 'static_assert' defined here
#   define static_assert(__b, __m) _Static_assert(__b, __m)
           ^
In file included from test.cpp:3:
In file included from /usr/local/Cellar/fmt/5.0.0/include/fmt/format.h:40:
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:413:3: error: use of undeclared identifier 'static_assert'
  static_assert(
  ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:428:38: error: a space is required between consecutive right angle brackets (use '> >')
struct is_named_arg<named_arg<T, Char>> : std::true_type {};
                                     ^~
                                     > >
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:498:19: error: too many arguments provided to function-like macro invocation
                  "incompatible string types");
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:783:12: note: macro 'static_assert' defined here
#   define static_assert(__b, __m) _Static_assert(__b, __m)
           ^
In file included from test.cpp:3:
In file included from /usr/local/Cellar/fmt/5.0.0/include/fmt/format.h:40:
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:503:19: error: too many arguments provided to function-like macro invocation
                  "incompatible string types");
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:783:12: note: macro 'static_assert' defined here
#   define static_assert(__b, __m) _Static_assert(__b, __m)
           ^
In file included from test.cpp:3:
In file included from /usr/local/Cellar/fmt/5.0.0/include/fmt/format.h:40:
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:497:5: error: use of undeclared identifier 'static_assert'
    static_assert(std::is_same<char, char_type>::value,
    ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:502:5: error: use of undeclared identifier 'static_assert'
    static_assert(std::is_same<char, char_type>::value,
    ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:530:5: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    auto &&parse_ctx = ctx.parse_context();
    ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:530:10: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    auto &&parse_ctx = ctx.parse_context();
         ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:627:28: warning: use of right-shift operator ('>>') in template argument will require parentheses in C++11 [-Wc++11-compat]
    typed_value<C, int_type>>::type
                           ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:627:32: error: no member named 'type' in the global namespace
    typed_value<C, int_type>>::type
                             ~~^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:632:24: error: use of undeclared identifier 'Char'; did you mean 'char'?
    !convert_to_int<T, Char>::value &&
                       ^~~~
                       char
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:633:47: error: use of undeclared identifier 'Char'; did you mean 'char'?
    !std::is_convertible<T, basic_string_view<Char>>::value,
                                              ^~~~
                                              char
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:633:51: error: a space is required between consecutive right angle brackets (use '> >')
    !std::is_convertible<T, basic_string_view<Char>>::value,
                                                  ^~
                                                  > >
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:636:31: warning: use of right-shift operator ('>>') in template argument will require parentheses in C++11 [-Wc++11-compat]
    typed_value<C, custom_type>>::type
                              ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:636:35: error: no member named 'type' in the global namespace
    typed_value<C, custom_type>>::type
                                ~~^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:641:5: error: expected '>'
    make_value(const named_arg<T, typename C::char_type> &val) {
    ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:631:1: error: type name does not allow function specifier to be specified
inline typename std::enable_if<
^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:625:1: error: 'inline' can only appear on functions
inline typename std::enable_if<
^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:656:31: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
template <typename F, typename... Args>
                              ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:678:19: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    visit(Visitor &&vis, basic_format_arg<Ctx> arg);
                  ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:766:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  FMT_DISALLOW_COPY_AND_ASSIGN(arg_map);
  ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:168:24: note: expanded from macro 'FMT_DISALLOW_COPY_AND_ASSIGN'
    Type(const Type &) FMT_DELETED; \
                       ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:164:23: note: expanded from macro 'FMT_DELETED'
#define FMT_DELETED = delete
                      ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:766:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:169:34: note: expanded from macro 'FMT_DISALLOW_COPY_AND_ASSIGN'
    void operator=(const Type &) FMT_DELETED
                                 ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:164:23: note: expanded from macro 'FMT_DELETED'
#define FMT_DELETED = delete
                      ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:780:24: error: expected '(' for function-style cast or type construction
    map_[size_] = entry{named.name, named.template deserialize<Context>()};
                  ~~~~~^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:791:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto it = map_, end = map_ + size_; it != end; ++it) {
         ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:881:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  FMT_DISALLOW_COPY_AND_ASSIGN(basic_format_context);
  ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:168:24: note: expanded from macro 'FMT_DISALLOW_COPY_AND_ASSIGN'
    Type(const Type &) FMT_DELETED; \
                       ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:164:23: note: expanded from macro 'FMT_DELETED'
#define FMT_DELETED = delete
                      ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:881:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:169:34: note: expanded from macro 'FMT_DISALLOW_COPY_AND_ASSIGN'
    void operator=(const Type &) FMT_DELETED
                                 ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:164:23: note: expanded from macro 'FMT_DELETED'
#define FMT_DELETED = delete
                      ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:911:58: error: a space is required between consecutive right angle brackets (use '> >')
    std::back_insert_iterator<internal::basic_buffer<Char>>, Char> type;
                                                         ^~
                                                         > >
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:927:51: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
template <typename Context, typename Arg, typename... Args>
                                                  ^
/usr/local/Cellar/fmt/5.0.0/include/fmt/core.h:941:56: error: a space is required between consecutive right angle brackets (use '> >')
inline typename std::enable_if<IS_PACKED, value<Context>>::type
                                                       ^~
                                                       > >
fatal error: too many errors emitted, stopping now [-ferror-limit=]
14 warnings and 20 errors generated.
Error: fmt: failed
```

**Comment by SuperWig** [comment]
Ah, forgot about the partial C++11 support requirement now. Added the -std=c++11 flag to the test.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @SuperWig! You're awesome.

As a side note, please make sure Git is configured so that it's using an email associated with your GitHub account.

**Comment by SuperWig** [comment]
Was it not already?

**Comment by ilovezfs** [comment]
Nope. I squashed it down for you and changed the author so it would reflect your GitHub account, but the first commit was attributed to
```
 Author: Dan <dan@Dans-iMac.local>
```

**Comment by SuperWig** [comment]
Ah okay. I know what the problem is now, thanks. :)

**Comment by ilovezfs** [comment]
No problem!

**Pull request closed without merging**
