### PR TITLE
tectonic 0.1.10

### PR DESCRIPTION
**Pull request by weinshel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/tectonic/0.1.10/bin/tectonic -o /private/tmp/tectonic-test-20181104-29240-ydqmnu /usr/local/Cellar/tectonic/0.1.10/share/tectonic/tests/xenia/paper.tex
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
note: indexing https://purl.org/net/pkgwpub/tectonic-default
error: could not get backend summary digest
caused by: The certificate was not trusted.
caused by: The certificate was not trusted.
caused by: The certificate was not trusted.
Error: tectonic: failed
```

**Comment by weinshel** [comment]
Looks like the site it's trying to load something from (https://purl.org/net/pkgwpub/tectonic-default) has an expired certificate.

**Comment by fxcoudert** [comment]
Can you file a bug report with Tectonic?

**Comment by weinshel** [comment]
Looks like it's already open in https://github.com/tectonic-typesetting/tectonic/issues/131. Seems to be a recurring problem, there is a workaround but probably isn't desired for brew.

**Comment by fxcoudert** [comment]
OK, will merge

**Pull request closed without merging**
