### PR TITLE
anime-downloader: use python-certifi

### PR DESCRIPTION
**Pull request by woodruffw**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@woodruffw you need to rebase to the latest master, also your fork base branch is way too outdated 😬 

Another thing, we also need push access (see https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+label%3A%22no+push+access%22+)

**Comment by woodruffw** [comment]
Yeah, sorry about that -- I did a merge in this PR and subsequent ones should be on a later base. Let me know if you'd like me to do a force-push here as well to bring it up.

> Another thing, we also need push access (see https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+label%3A%22no+push+access%22+)

I use an org for my forks, but I'll see if I can give `brew-test-bot` dedicated push access. No idea if that will work.

(Is that a new requirement? I remember using my org fork without problems a few months ago.)

**Comment by chenrui333** [comment]
> I use an org for my forks, but I'll see if I can give `brew-test-bot` dedicated push access. No idea if that will work.

yeah, you should, otherwise, I can help handling these PR updates.

**Comment by woodruffw** [comment]
> yeah, you should, otherwise, I can help handling these PR updates.

Thanks. I just sent a membership invite to @BrewTestBot -- let me know if that can't be accepted, and I'll switch to an account fork :slightly_smiling_face:

**Comment by chenrui333** [comment]
also you might need to do the PR rebase.

**Comment by p-linnane** [comment]
@woodruffw I accepted the invite as BrewTestBot. Let me know if it looks good.

**Comment by woodruffw** [comment]
Thanks @p-linnane! Confirmed accepted and force-pushed here.

**Comment by chenrui333** [comment]
Thanks @p-linnane! 🚀

**Review by chenrui333 — DISMISSED** [review]

**Pull request closed without merging**
