### PR TITLE
dotnet 6.0.300

### PR DESCRIPTION
**Pull request by alexreg**
Upgrade formula. Looks like this didn't happen automatically because some patches and an `inreplace` need to be removed now.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
> Looks like this didn't happen automatically because some patches and an `inreplace` need to be removed now.

It's because:

> .NET Source-Build is supported on the oldest available .NET SDK feature update. For example, if both .NET 6.0.1XX and 6.0.2XX feature updates are available from [dotnet.microsoft.com](https://dotnet.microsoft.com/en-us/download/dotnet/6.0), Source-Build will support 6.0.1XX. For the latest information about Source-Build support for new .NET versions, please check our [GitHub Discussions page](https://github.com/dotnet/source-build/discussions) for announcements.

**Comment by alexreg** [comment]
@Bo98 Thanks. I don't mind using the cask, or another install method, though I think we need add a specialised `depends_on` clause, that accepts either — so formulas can use this.

**Comment by Bo98** [comment]
> I don't mind using the cask, or another install method, though I think we need add a specialised `depends_on` clause, that accepts either — so formulas can use this.

This is possible and the way to do this is via the requirement system (see glibc formula for examples). Though it's up to third-party taps to do this.

**Comment by alexreg** [comment]
@Bo98 Well, .NET obviously doesn't ship with macOS, but can we not just create a requirement (as you describe) that looks for .NET in standard locations, and uses that? So, if the users installed .NET manually or through the Cask, or by whatever means, that would suffice?

**Comment by SMillerDev** [comment]
Well, it's not just the locations that are the problem. It's also the versions. What if someone modified their .NET install somehow? Stuff will break and people will file issues with Homebrew. The overwhelming experience of maintainers is that these requirements make the overall experience of formula worse since they're practically untested.

Additionally, the .NET formula exists and builds from source. Why would we use a more complicated system instead?

**Comment by alexreg** [comment]
@SMillerDev The version can be checked easily. The issue is that a decent bit of .NET stuff depends on the very latest version (e.g. Maui), and is evolving quite rapidly, as I understand. This sort of thing would also be very useful for depending on either `mono-mdk` vs `mono-mdk-for-visual-studio`, though perhaps a different approach can be used for that.

**Comment by danielnachun** [comment]
The real issue here is .NET upstream not supporting source builds for the latest version.  In the era of integrated CI this should not be the that difficult to do and it's not clear to me why they don't prioritize it more.  I am obviously biased here but I think that dedicated package managers like `brew` do a much better job of distributing binaries than upstream developers who don't have as much expertise in packaging.

Another issue with relying on casks in formulae is that casks don't exist on Linux, which is now a fully supported platform for Homebrew.  

Given that the CLR languages are byte-compiled and not producing native binaries, isn't it more convenient (on macOS) to use the .NET cask and then use NuGet to install packages that need the newest .NET?  For byte-compiled languages (CLR, JVM, Python, etc.) it's pretty manageable to use a dedicated package manager for that language if the packages don't need extra native dependencies.  Things admittedly get more difficult if a byte-compiled package also needs to use or build native dependencies, but in that case I'd hope the developers would design their software to use versions of dependencies that can be provided by native package managers.

**Comment by Bo98** [comment]
> can we not just create a requirement (as you describe) that looks for .NET in standard locations, and uses that?

Yes, but it won't be shipped in either brew or homebrew-core. Taps may of course do that however if they'd like.

> The issue is that a decent bit of .NET stuff depends on the very latest version (e.g. Maui), and is evolving quite rapidly, as I understand.

You're going to find every open-source package manager has the same issue then: https://repology.org/project/dotnet/versions

No open-source package manager ships anything newer than 6.0.1xx because newer versions are not yet fully open-source.

**Comment by alexreg** [comment]
@Bo98 Wow, so most releases of .NET are open-source, but the very latest aren't? What a terribly odd release model. Fair enough though.

**Comment by danielnachun** [comment]
I don't think there's anymore we can do here so I'm going to close this, but this will be useful to point other users to in the future if they have questions about how we package `dotnet`.

**Pull request closed without merging**
