### PR TITLE
ghcup 0.21

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
I did not see any upstream issues for cabal 3.8 support, so let's try building with ghc 9.4

**Comment by chenrui333** [comment]
also this did not get marked as latest release yet.

**Comment by p-linnane** [comment]
https://github.com/haskell/ghcup-hs/commit/a427146de5ddedb2577ffff723bad658398636bc

**Comment by chenrui333** [comment]
> [haskell/ghcup-hs@a427146](https://github.com/haskell/ghcup-hs/commit/a427146de5ddedb2577ffff723bad658398636bc)

somehow that commit did not show in the 0.21 git tag.

**Comment by chenrui333** [comment]
works in my local with latest ghc for 0.1.19.2 build.

**Comment by p-linnane** [comment]
Might be worth opening an issue to ask what the latest version if supposed to be. We may just want to`livecheck` for the latest tag and build 0.1.19.2 with `ghc@9.4`.

**Comment by chenrui333** [comment]
sounds good

**Comment by p-linnane** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/120676.

**Pull request closed without merging**
