### PR TITLE
mpg123 1.32.3

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Comment by manxorist** [comment]
I am no Homebrew expert, so I am not sure why an automatic test failed.

What I do know is that this is an extremely important bugfix for mpg123 1.32.0/1.32.1 because these versions have missing symbols on macOS that were exported previously and should continue to be exported. See https://mpg123.org/#2023-09-27:
> libmpg123: Re-introduce _64 symbols on native 64 bit offset platforms. This was a regression since 1.31 series. Sorry, too much cleanup, not enough testing.

This causes build failures of my project libopenmpt. I helped mpg123 upstream diagnosing and fixing this problem (https://github.com/madebr/mpg123/commit/a8dceb87b485f15e9d12325192dbddc46aaea3fa).

**Comment by SMillerDev** [comment]
Bumped to the last release now, lets see

**Review by SMillerDev — APPROVED** [review]

**Comment by manxorist** [comment]
... well, this should get merged

**Comment by manxorist** [comment]
... well ... ?!?!?!?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
failures are irrelevant to the formula upgrade (like get_iplayer linux regression test failure)

**Pull request merged**
