### PR TITLE
sslyze: use system Python

### PR DESCRIPTION
**Pull request by iMichka**
because we will delete the Python@2 formula end of 2019.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> python -s /private/tmp/sslyze--homebrew-virtualenv-20191216-47002-bkot3v/target/bin/virtualenv -p python /usr/local/Cellar/sslyze/1.4.3_1/libexec
python: can't open file '/private/tmp/sslyze--homebrew-virtualenv-20191216-47002-bkot3v/target/bin/virtualenv': [Errno 2] No such file or directory
```

**Comment by EricFromCanada** [comment]
Should probably just merge #45750 instead, which upgrades `sslyze` to a version supporting Python 3.

**Comment by iMichka** [comment]
We could, but the build of the new version seems to have failed. And I would like to not clash with the Python 3 migration which seems hard enough by itself.

**Comment by EricFromCanada** [comment]
See: #47993

**Comment by iMichka** [comment]
Superseded by #47993.

**Pull request closed without merging**
