### PR TITLE
fonttools 3.1.2

### PR DESCRIPTION
**Pull request by Jolg42**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

I updated the repository's name too.

There is an opened PR #5303 by @ilovezfs

Is everything ok now @ilovezfs ?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Jolg42 Yes. The reason I had "do not merge" on the other PR is that the formula "should" be converted to use the new virtualenv feature. You can see an example here: https://github.com/Homebrew/homebrew-core/pull/4410 if you'd like to give that a try.

**Comment by Jolg42** [comment]
@ilovezfs The update is ready 😉
Thank you for the quick answer!

**Comment by ilovezfs** [comment]
@Jolg42 thanks, and you're welcome. I think we can live without the blank lines 26 and 28 :)

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@Jolg42 actually I'll just remove those two lines in post. Don't worry about it.

**Comment by ilovezfs** [comment]
@Jolg42 Thanks for your contribution to Homebrew! :100:

**Pull request closed without merging**
