### PR TITLE
questdb 4.2.0

### PR DESCRIPTION
**Pull request by TheTanc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/questdb/4.2.0/bin/questdb stop

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

Stopped 88390
Error: questdb: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<7>.
```

**Comment by Moisan** [comment]
The tests pass locally for me, maybe increasing slightly the `sleep` calls could solve the issue on the CI.

**Comment by TheTanc** [comment]
It seems issue was with `version` which was redundant with the `url`. Having changed this, the tests pass now.

**Comment by TheTanc** [comment]
> The tests pass locally for me, maybe increasing slightly the `sleep` calls could solve the issue on the CI.

Thanks for the suggestion, I increased the sleep time.

**Comment by chenrui333** [comment]
Thanks @TheTanc, @Moisan!!

**Pull request merged**
