### PR TITLE
newsboat 2.16.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
```

**Comment by chenrui333** [comment]
07:14:18      Running `rustc --crate-name gettext_sys /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/gettext-sys-0.19.8/lib.rs --color never --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="gettext-system"' -C metadata=1d5edff512fb5085 -C extra-filename=-1d5edff512fb5085 --out-dir /private/tmp/newsboat-20190627-25220-nihc42/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190627-25220-nihc42/newsboat-2.16.1/target/release/deps --cap-lints allow -L native=/private/tmp/newsboat-20190627-25220-nihc42/newsboat-2.16.1/target/release/build/gettext-sys-60c70d5a2f6d7cc6/out/lib -l framework=CoreFoundation -l dylib=iconv -l static=intl`
07:14:18      Running `/private/tmp/newsboat-20190627-25220-nihc42/newsboat-2.16.1/target/release/build/libnewsboat-791b93a250235218/build-script-build`
07:14:18 error: could not find native static library `intl`, perhaps an -L flag is missing?
07:14:18 
07:14:18 error: aborting due to previous error
07:14:18 
07:14:18 error: Could not compile `gettext-sys`.
07:14:18 
07:14:18 Caused by:
07:14:18   process didn't exit successfully: `rustc --crate-name gettext_sys /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/gettext-sys-0.19.8/lib.rs --color never --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="gettext-system"' -C metadata=1d5edff512fb5085 -C extra-filename=-1d5edff512fb5085 --out-dir /private/tmp/newsboat-20190627-25220-nihc42/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190627-25220-nihc42/newsboat-2.16.1/target/release/deps --cap-lints allow -L native=/private/tmp/newsboat-20190627-25220-nihc42/newsboat-2.16.1/target/release/build/gettext-sys-60c70d5a2f6d7cc6/out/lib -l framework=CoreFoundation -l dylib=iconv -l static=intl` (exit code: 1)
07:14:18 make: *** [target/release/libnewsboat.a] Error 101

**Comment by SMillerDev** [comment]
```
    Running `/private/tmp/newsboat-20190627-38176-8otnjx/newsboat-2.16.1/target/release/build/libnewsboat-791b93a250235218/build-script-build`
error: could not find native static library `intl`, perhaps an -L flag is missing?

error: aborting due to previous error

error: Could not compile `gettext-sys`.

Caused by:
  process didn't exit successfully: `rustc --crate-name gettext_sys /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/gettext-sys-0.19.8/lib.rs --color never --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="gettext-system"' -C metadata=1d5edff512fb5085 -C extra-filename=-1d5edff512fb5085 --out-dir /private/tmp/newsboat-20190627-38176-8otnjx/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190627-38176-8otnjx/newsboat-2.16.1/target/release/deps --cap-lints allow -L native=/private/tmp/newsboat-20190627-38176-8otnjx/newsboat-2.16.1/target/release/build/gettext-sys-60c70d5a2f6d7cc6/out/lib -l framework=CoreFoundation -l dylib=iconv -l static=intl` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [target/release/libnewsboat.a] Error 101
```

**Comment by Minoru** [comment]
Hi, Newsboat maintainer here. Thank you for packaging and distributing my software!

I'm building Newsboat on macOS on Travis, and one thing I do that I don't see in the formula here is "brew link --force gettext". I admit I don't fully understand how Homebrew works, but I believe this is needed for gettext library to be found by the compiler without specifying the path via -L.

**Comment by SMillerDev** [comment]
From what I see in the formula there is no `./configure` which might be the solution we need here. It would allow brew to specify the location of gettext rather than make depending on forcing a link which is impossible for our CI.

**Comment by Minoru** [comment]
The error comes from one of Newsboat's dependencies, so ./configure in Newsboat wouldn't help much. I'm looking into ways to influence how that dependency is looking for gettext. First order of business is to reproduce this on Travis. I'll keep you posted.

**Comment by Minoru** [comment]
If I `brew install gettext` without `brew link`ing it, I do get errors on my CI, but not the same as yours: https://travis-ci.org/newsboat/newsboat/jobs/553420595 For me, C++ can't find gettext, but Rust stuff builds just fine. (The error you quote is from a Rust crate called gettext-sys).

I don't have a Mac to test this locally, and since I can't even reproduce it on CI, I can only theorize about possible causes and fixes. The most likely cause is "gettext-system" feature which asks gettext-sys to use system-wide gettext instead of building its own version. So if you patch [rust/libnewsboat/Cargo.toml](https://github.com/newsboat/newsboat/blob/c89659a5a7b8e601896da90f3cc64f22129a411d/rust/libnewsboat/Cargo.toml#L38-L42):

```toml
[dependencies.gettext-sys]
version = "0.19.8"
# Don't let the crate build its own copy of gettext; force it to use the one
# built into glibc.
features = [ "gettext-system" ]
```

to read:

```toml
[target.'cfg(not(target_os = "macos"))'.dependencies.gettext-sys]
version = "0.19.8"
# Don't let the crate build its own copy of gettext; force it to use the one
# built into glibc.
features = [ "gettext-system" ]

[target.'cfg(target_os = "macos")'.dependencies.gettext-sys]
version = "0.19.8"
```

it'll build its own statically linked copy of gettext, and should work fine. This is ugly, which is the reason I opted out, but this is the easiest way out as far as I can see. Can you try this, please?

**Comment by chenrui333** [comment]
Cool, I will try to patch [rust/libnewsboat/Cargo.toml](https://github.com/newsboat/newsboat/blob/c89659a5a7b8e601896da90f3cc64f22129a411d/rust/libnewsboat/Cargo.toml#L38-L42) now, once it works, it is probably preferred to have it in the source code instead.

**Comment by Minoru** [comment]
Sure, I'll incorporate the change upstream once we got it working.

**Comment by chenrui333** [comment]
Does not work, same error. Will push the change though for visibility.

**Comment by Minoru** [comment]
When I try to view the CI job at https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/45404/, I get a connection timeout. The output is not public?

It's weird that the error is the same. Can you diff the current and previous build log to see if it even tried to compile gettext?

**Comment by chenrui333** [comment]
😄 that might be because the cert got expired yesterday. But now the link should be accessible (which I just tried and it works)

**Comment by chenrui333** [comment]
The error log:

19:35:38    Compiling once_cell v0.1.8
19:35:38      Running `rustc --crate-name once_cell /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/once_cell-0.1.8/src/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="parking_lot"' -C metadata=c1a3980f05a4a3fc -C extra-filename=-c1a3980f05a4a3fc --out-dir /private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/deps --extern parking_lot=/private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/deps/libparking_lot-e2222400a2d47110.rlib --cap-lints allow`
19:35:38      Running `rustc --crate-name gettext_sys /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/gettext-sys-0.19.8/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="gettext-system"' -C metadata=fbfbf08f4c2802f5 -C extra-filename=-fbfbf08f4c2802f5 --out-dir /private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/deps --cap-lints allow -L native=/private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/build/gettext-sys-5739282cd4e1f661/out/lib -l framework=CoreFoundation -l dylib=iconv -l static=intl`
19:35:38      Running `/private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/build/libnewsboat-abe50914d672b72f/build-script-build`
19:35:38 error: could not find native static library `intl`, perhaps an -L flag is missing?
19:35:38 
19:35:38 error: aborting due to previous error
19:35:38 
19:35:38 error: Could not compile `gettext-sys`.
19:35:38 
19:35:38 Caused by:
19:35:38   process didn't exit successfully: `rustc --crate-name gettext_sys /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/gettext-sys-0.19.8/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="gettext-system"' -C metadata=fbfbf08f4c2802f5 -C extra-filename=-fbfbf08f4c2802f5 --out-dir /private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/deps --cap-lints allow -L native=/private/tmp/newsboat-20190721-77756-v6dcqn/newsboat-2.16.1/target/release/build/gettext-sys-5739282cd4e1f661/out/lib -l framework=CoreFoundation -l dylib=iconv -l static=intl` (exit code: 1)
19:35:38 make: *** [target/release/libnewsboat.a] Error 101

**Comment by Minoru** [comment]
Connection problem is on my end—I can fetch that URL from my VPS in another country. I'll figure it out.

Apparently that change that I suggested doesn't work the way I intended—https://github.com/rust-lang/cargo/issues/1197 says I can't turn features on and off depending on target platform. Sorry for wasting your time with that one. I implemented the suggested workaround: created a dummy crate that enables the feature, and now `libnewsboat` depends on either "featureless" `gettext-sys` or the dummy crate.

@chenrui333, can you please grab [this patch](https://github.com/newsboat/newsboat/commit/5a6a26c75756e8c44de8b917f4323694ce146958.patch) and see if it will work on Homebrew's CI?

**Comment by chenrui333** [comment]
Sure, applying that patch now.

**Comment by chenrui333** [comment]
Still the same error:
12:56:25      Running `rustc --crate-name gettext_sys /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/gettext-sys-0.19.8/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="gettext-system"' -C metadata=fbfbf08f4c2802f5 -C extra-filename=-fbfbf08f4c2802f5 --out-dir /private/tmp/newsboat-20190721-71525-ycr1pe/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190721-71525-ycr1pe/newsboat-2.16.1/target/release/deps --cap-lints allow -L native=/private/tmp/newsboat-20190721-71525-ycr1pe/newsboat-2.16.1/target/release/build/gettext-sys-5739282cd4e1f661/out/lib -l framework=CoreFoundation -l dylib=iconv -l static=intl`
12:56:25 error: could not find native static library `intl`, perhaps an -L flag is missing?
12:56:25 
12:56:25 error: aborting due to previous error
12:56:25 
12:56:25 error: Could not compile `gettext-sys`.
12:56:25 
12:56:25 Caused by:
12:56:25   process didn't exit successfully: `rustc --crate-name gettext_sys /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/gettext-sys-0.19.8/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="gettext-system"' -C metadata=fbfbf08f4c2802f5 -C extra-filename=-fbfbf08f4c2802f5 --out-dir /private/tmp/newsboat-20190721-71525-ycr1pe/newsboat-2.16.1/target/release/deps -L dependency=/private/tmp/newsboat-20190721-71525-ycr1pe/newsboat-2.16.1/target/release/deps --cap-lints allow -L native=/private/tmp/newsboat-20190721-71525-ycr1pe/newsboat-2.16.1/target/release/build/gettext-sys-5739282cd4e1f661/out/lib -l framework=CoreFoundation -l dylib=iconv -l static=intl` (exit code: 1)

**Comment by Minoru** [comment]
Yep. I'm trying to get it to work here on Linux; looks like I still 
misunderstand something about Cargo. I'll keep you posted. Thanks for 
sticking with me!

**Comment by Minoru** [comment]
My solutions here are becoming more and more esoteric. I'm now moving 
some code into a separate crate. The patch won't be short :)

While I'm at it, you can try another route (which I can't because 
I can't reproduce the actual problem)—remove all the patches, and try 
tweaking the environment variables described here: 
https://github.com/Koka/gettext-rs#manual-configuration This is 
essentially the same as ./configure, only manual.

**Comment by Minoru** [comment]
Nope, can't figure out how to trick Cargo into building gettext-sys with different features depending on the target. Maybe I just need to take a step back, so I'm putting this away until tomorrow.

Please try those environment variables—they might be our only hope.

**Comment by chenrui333** [comment]
ok, let's touch base on this tomorrow then, no rush at all. Have a good day or night!

**Comment by Minoru** [comment]
Taking another look didn't help, so I'm [asking on forums](https://users.rust-lang.org/t/tweak-dependencys-features-depending-on-target-os/30612) and trying to attract outside help. Did you have time to try those environment variables?

**Comment by chenrui333** [comment]
No, I did not.

**Comment by Minoru** [comment]
My forum post haven't gotten any responses still. To get this PR unblocked, you can just [remove these three lines](https://github.com/newsboat/newsboat/blob/39a177741a683ba61040f87dd4f4278d033e732d/rust/libnewsboat/Cargo.toml#L40-L42); the build will then compile and statically link its own copy of gettext. The binary size will increase a bit, but at least it *will* build.

**Comment by chenrui333** [comment]
Circle back on this.

**Comment by Minoru** [comment]
My forum post got no responses :( I think the only remaining options are environment variables, and removing the feature from Cargo.toml. I can't try either of them because I can't reproduce the issue neither locally nor on CI. Is there anything else I can do to help?

**Comment by chenrui333** [comment]
@Minoru, I am actually rethinking the git diff. Looks like the r2.16.1 tree is little bit different from master branch, right?

**Comment by Minoru** [comment]
Yes, we merge all new things in master, and tag a release every three months. But there is nothing in master that'll affect this build failure.

**Comment by chenrui333** [comment]
yeah, i know, I am asking mainly from the code reference perspective.

**Comment by chenrui333** [comment]
you might be interested using Formula to link the build references. 

```
gettext = Formula["gettext"]
```

https://www.rubydoc.info/github/Homebrew/brew/Formula:opt_lib

**Comment by chenrui333** [comment]
I am still trying to understand your exact patch to at least kick start the build. Can you be more specific.

**Comment by Minoru** [comment]
Which patch do you have in mind? [This one](https://github.com/newsboat/newsboat/commit/5a6a26c75756e8c44de8b917f4323694ce146958.patch)? But we already tried it and found it doesn't work?

Not sure where to put that Formula line. Doesn't it go into the Homebrew recipe?

**Comment by chenrui333** [comment]
Something like what I am trying to fix in this PR, `https://github.com/Homebrew/homebrew-core/pull/42540/files`

**Comment by Minoru** [comment]
Ah, got it. Yes, I think you can add the following to the recipe:

```
gettext = Formula["gettext"]

ENV["GETTEXT_BIN_DIR"] = "#{gettext.opt_bin}"
ENV["GETTEXT_LIB_DIR"] = "#{gettext.lib}"
ENV["GETTEXT_INCLUDE_DIR"] = "#{gettext.include}"
```

I'm not quite sure how this will interact with the patch that removes `features` line. Can you try both *with* and *without* the patch, to see which one builds?

**Comment by Minoru** [comment]
The build failed because static version of `intl` library couldn't be found. So much for that idea, then. Can you try the environment variables?

**Comment by chenrui333** [comment]
I see. I will try once arriving home.

**Comment by chenrui333** [comment]
@Minoru added, 🤞

**Comment by chenrui333** [comment]
00:02:50 ==> brew style newsboat
00:02:54 ==> FAILED
00:02:54 == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/newsboat.rb ==
00:02:54 C: 28: 30: Prefer to_s over string interpolation.
00:02:54 C: 29: 30: Prefer to_s over string interpolation.
00:02:54 C: 30: 34: Prefer to_s over string interpolation.
00:02:54 
00:02:54 1 file inspected, 3 offenses detected

**Comment by chenrui333** [comment]
that is promising.

**Comment by chenrui333** [comment]
Should be good for merge now, cc @lembacon, @Moisan, @javian

**Comment by Minoru** [comment]
Can you check if it builds without the patch, i.e. with environment variables alone? It would be nice if it did, because I can't incorporate the patch upstream.

**Comment by chenrui333** [comment]
yeah, you are right, I just removed the patch, and re-kick in a new build.

**Comment by chenrui333** [comment]
Looks like the patch is not really needed, I will remove the patch now.

**Comment by Moisan** [comment]
Thank you @chenrui333 and @Minoru !

**Pull request closed without merging**
