### PR TITLE
node 13.3.0

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

### CODE REVIEW

**Review by chenrui333 — CHANGES_REQUESTED** [review]
please also update npm to `v6.13.2`

**Comment by chenrui333** [comment]
Timeout error on anime-downloader

09:07:48 ==> brew test --verbose anime-downloader
09:12:53 ==> FAILED
09:12:53 Testing anime-downloader
09:12:53 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191204-69025-l8n2b2.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/anime-downloader.rb --verbose
09:12:53 ==> /usr/local/Cellar/anime-downloader/4.0.1/bin/anime --version
09:12:53 ==> sh -c echo 1 | /usr/local/Cellar/anime-downloader/4.0.1/bin/anime watch -n Kaguya-sama --provider kissanime; echo 1 | /usr/local/Cellar/anime-downloader/4.0.1/bin/anime watch -l | grep 0/12 > out
09:12:53 [32manime[0m: anime-downloader 4.0.1
09:12:53 Killing child processes...
09:12:53 Error: anime-downloader: failed
09:12:53 An exception occurred within a child process:
09:12:53   Timeout::Error: execution expired

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Give another try on the CI.

**Comment by diogoazevedos** [comment]
Any ideas how to fix the issue?

**Comment by yeliex** [comment]
@diogoazevedos any progress? it has been 5 days after node@13.3.0 released

**Comment by yeliex** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
```
==> sh -c echo 1 | /usr/local/Cellar/anime-downloader/4.0.1/bin/anime watch -n Kaguya-sama --provider kissanime; echo 1 | /usr/local/Cellar/anime-downloader/4.0.1/bin/anime watch -l | grep 0/12 > out
�[32manime�[0m: anime-downloader 4.0.1
Killing child processes...
Error: anime-downloader: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

No amount of restarting the job is going to fix this error. Someone should fix the tool to work with the update.

**Review by chenrui333 — APPROVED** [review]
With knowing only `anime-downloader` failed in the PR, I would give this PR a pass.

**Comment by chenrui333** [comment]
Thanks @diogoazevedos!!

**Comment by chenrui333** [comment]
I installed `anime-downloader`, the issue might be with `9anime introduced captcha.`

**Pull request closed without merging**
