### PR TITLE
azure-cli: depend on pygments, pyyaml, python-typing-extensions, and six

### PR DESCRIPTION
**Pull request by singingwolfboy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Azure have some automation that would undo these changes on the next version bump.

You'll need to open a PR against their repo too. See https://github.com/Azure/azure-cli/pull/23788

**Comment by chenrui333** [comment]
Looks like the upstream PR is still open, maybe let's merge after that one gets merged

**Comment by chenrui333** [comment]
upstream PR is still open.

**Comment by iMichka** [comment]
Upstream PR has been merged, @singingwolfboy can you rebase this please?

**Comment by singingwolfboy** [comment]
> Upstream PR has been merged, @singingwolfboy can you rebase this please?

I just rebased the pull request, but https://github.com/Azure/azure-cli/pull/23849 has not yet been merged.

**Pull request closed without merging**
