### PR TITLE
mold: drop GCC dependency

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
  gmake[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpthread.so', needed by 'mold'.  Stop.
```

**Comment by danielnachun** [comment]
The reason this seems to be failing is because there is only a `libpthread.so.1` and `librt.so.1` in Ubuntu 22.04, but the Makefile expects `libpthread.so` and `librt.so` to exist as unversioned symlinks.  I'm not exactly sure how it ends up truncating the versions but if we can stop it from doing so the problem should be fixed.

**Comment by carlocab** [comment]
I think that dependency is coming from `tbb` or `mimalloc`. I don't think it's coming from `mold`.

**Comment by danielnachun** [comment]
I will try rebuilding those locally and see if `mold` builds at that point.  They might just need a revision bump to point to the proper sonames.

**Comment by danielnachun** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/110376, because a revision bump is needed there making this redundant.

**Pull request closed without merging**
