### PR TITLE
lapack 3.11

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
      /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: libVerifyFortran.a(VerifyFortran.f.o): relocation R_X86_64_32S against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
      /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: failed to set dynamic section sizes: bad value
```

**Comment by chenrui333** [comment]
cc @Homebrew/linux

**Comment by danielnachun** [comment]
I think this needs `-DCMAKE_Fortran_FLAGS=-fPIE` to be added on Linux.  I will test this locally and push a fix if it works.

**Comment by chenrui333** [comment]
> I think this needs `-DCMAKE_Fortran_FLAGS=-fPIE` to be added on Linux. I will test this locally and push a fix if it works.

any update on that? :)

**Comment by danielnachun** [comment]
I believe once https://github.com/Homebrew/homebrew-core/pull/116656 is merged, we should be able to just build this with no issues, as that will have the effect of adding `-fPIE` to all `gfortran` builds instead of us having to manually do it.

**Review by danielnachun — APPROVED** [review]
As we had hoped https://github.com/Homebrew/homebrew-core/pull/116656 has fixed this issue.

**Pull request closed without merging**
