### PR TITLE
afl-fuzz 2.54

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Upstream (http://lcamtuf.coredump.cx/afl/) still considers 2.52b as the latest release.

**Comment by bayandin** [comment]
@fxcoudert according to the "official" twitter thread https://twitter.com/Dor3s/status/1154443414076739584 the https://github.com/google/AFL now it's the official AFL repo. Will it be ok to update the homepage as well?

**Comment by fxcoudert** [comment]
Thanks! And yes, please update the homepage as well.

**Comment by bayandin** [comment]
@fxcoudert done.

There is a fail on [mojave](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/47512/version=mojave/testReport/junit/brew-test-bot/mojave/install___build_bottle_afl_fuzz/) because of `No space left on device`.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by bayandin** [comment]
@BrewTestBot test this please

**Comment by bayandin** [comment]
@fxcoudert yay, it finally built!

**Pull request closed without merging**
