### PR TITLE
macvim 8.2-162

### PR DESCRIPTION
**Pull request by mvcouwen**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ychin** [comment]
This version contains a new `configure` parameter that can disable the Sparkle updater. Since Homebrew usually likes to manage its own software, it may help if you use that to disable Sparkle in the configure script.

See https://github.com/macvim-dev/macvim/pull/982 for details.

**Comment by chenrui333** [comment]
@mvcouwen Thanks for your contribution.

@ychin Thanks for bringing this up, the context is really helpful. Do you mean we should update configure to include `--disable-sparkle` for the build?

**Comment by ychin** [comment]
Yes that's what I meant, unless there are reasons why we would want Homebrew users to update outside of Homebrew's own management.

**Comment by mvcouwen** [comment]
I have now included `--disable-sparkle` in the configuration for the build.

**Comment by chenrui333** [comment]
Sounds about right. 😄

**Pull request closed without merging**
