### PR TITLE
alluxio 2.5.0-2

### PR DESCRIPTION
**Pull request by gromgit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
I see they got rid of `lib/libjnifuse.dylib`. You can remove

https://github.com/Homebrew/homebrew-core/blob/e4789405e71db54991439dfac0f3988acb4c65dc/Formula/alluxio.rb#L18-L20

now.

**Comment by nandahkrishna** [comment]
[This](https://docs.alluxio.io/os/user/edge/en/deploy/Requirements.html#fuse-requirements) seems to suggest that FUSE is still required. Also, some changes mentioned in the [release notes](https://www.alluxio.io/download/releases/alluxio-2-5-0-2-release/) are FUSE-related (to improve the FUSE integration).

**Comment by carlocab** [comment]
>There are Alluxio-specific requirements for nodes running the fuse process.

This makes it sound like you can use Alluxio without running fuse.

**Comment by gromgit** [comment]
Based on [this](https://docs.alluxio.io/ee/user/stable/en/api/POSIX-API.html?q=fuse), it seems FUSE use is limited to `alluxio-fuse`, which dynamically loads whichever `libfuse` it can find at runtime. On macOS, that of course means macFUSE, but on Linux, it almost certainly won't find Homebrew `libfuse` anyway, without an appropriate `LD_LIBRARY_PATH`.

In that case, I'll drop FUSE as a dependency across all platforms, and add a note about installing macFUSE (macOS) or system FUSE (Linux) in the caveats.

**Comment by gromgit** [comment]
Replacing this PR with #76149 , since it's no longer a simple version bump.

**Pull request closed without merging**
