### PR TITLE
go 1.20rc1

### PR DESCRIPTION
**Pull request by andig**
Created with `brew bump-formula-pr` to start testing for the Go1.20 release cycle.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by andig** [comment]
Not sure why the audit failure appears. Tried to bump using

    brew bump-formula-pr golang --version 1.20rc1  --force --no-audit

**Comment by SMillerDev** [comment]
Because that's only for the checks before the pull request. It doesn't impact CI.

**Comment by andig** [comment]
Anything I can do as we're still stuck on the syntax check?

**Comment by andig** [comment]
Apart from moving on I'm suddenly seeing

```
You have 2 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Upgrading 2 outdated packages:
go 1.19.4 -> 1.20rc1
uchardet 0.0.7 -> 0.0.8
==> Fetching go
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.20rc1
curl: (22) The requested URL returned error: 404

Error: go: Failed to download resource "go_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/go/manifests/1.20rc1
```

Could this be in any way related to this PR?

**Comment by SMillerDev** [comment]
You have this branch checked out so Homebrew thinks it can install 1.20rc1 but that doesn't have any bottles yet. You should switch branches or build from source.

**Comment by chenrui333** [comment]
```
  ==> ./make.bash --no-clean
  Building Go cmd/dist using /private/tmp/go-20221210-48032-1hk4l73/go/gobootstrap. (go1.16 darwin/arm64)
  found packages main (build.go) and building_Go_requires_Go_1_17_13_or_later (notgo117.go) in /private/tmp/go-20221210-48032-1hk4l73/go/src/cmd/dist
```

**Comment by andig** [comment]
The gcsfuse issue seems similar to https://github.com/ska-sa/homebrew-tap/issues/20. There are a number of google matches for this error. Seems this might be solved in the homebrew wrapper instead of per-formula?

**Comment by andig** [comment]
@chenrui333 I was just gonna follow up with the build errors and found https://github.com/goplus/gop/issues/1350. Seems you're already doing that and I'll step down. Would be nice to link those here to avoid double work.

**Comment by fxcoudert** [comment]
```
Error: 40 failed steps!
brew install --build-from-source caddy
brew install --build-from-source cloudflared
brew test --retry --verbose counterfeiter
brew install --build-from-source dnscrypt-proxy
brew install --build-from-source eksctl
brew test --retry --verbose emp
brew test --retry --verbose git-appraise
brew test --retry --verbose git-appraise
brew test --retry --verbose github-markdown-toc
brew test --retry --verbose github-markdown-toc
brew test --retry --verbose gomplate
brew test --retry --verbose goplus
brew test --retry --verbose goplus
brew install --build-from-source gost
brew test --retry --verbose grafana-agent
brew fetch --build-from-source --retry hasura-cli
brew install --build-from-source hysteria
brew test --retry --verbose ibazel
brew test --retry --verbose ibazel
brew install --build-from-source ipfs
brew install --build-from-source istioctl
brew install --build-from-source k3d
brew install --build-from-source kt-connect
brew install --build-from-source liqoctl
brew test --retry --verbose logcli
brew install --build-from-source octant
brew install --build-from-source ooniprobe
brew test --retry --verbose promtail
brew test --retry --verbose qpm
brew test --retry --verbose qpm
brew test --retry --verbose staticcheck
brew test --retry --verbose staticcheck
brew install --build-from-source storj-uplink
brew install --build-from-source sync_gateway
brew install --build-from-source syncthing
brew test --retry --verbose totp-cli
brew install --build-from-source traefik
brew install --build-from-source vault
brew fetch --build-from-source --retry whalebrew
brew install --build-from-source xray
```

**Comment by chenrui333** [comment]
For many formulae using quic-go, creating [go1.20 support issue](https://github.com/lucas-clemente/quic-go/issues/3630)

**Pull request closed without merging**
