### PR TITLE
fastlane 2.157.3

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by SMillerDev** [comment]
@dawidd6 could you try and make it use macOS ruby since Mojave?

**Comment by joshdholtz** [comment]
@SMillerDev  Looks like I forgot to create `2.157.3` myself. I have a new PR for `2.158.0` that needs to go out so I’ll be creating another PR for that version. I don’t have time today to enable macOS ruby but I will do that next week if that’s okay!

**Comment by joshdholtz** [comment]
Here is the PR that I created - https://github.com/Homebrew/homebrew-core/pull/60692

**Comment by dtrodrigues** [comment]
New PR mentioned above.

**Pull request closed without merging**
