### PR TITLE
elasticsearch 5.4.0

### PR DESCRIPTION
**Pull request by jasontedor**
This pull request updates the Elasticsearch version from 5.3.2 to 5.4.0.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@jasontedor looks like the versioned alias needs an update:
```
iMac-TMP:homebrew-core joe$ readlink Aliases/elasticsearch\@5.2 
../Formula/elasticsearch.rb
```
Ditto for logstash & kibana

**Comment by jasontedor** [comment]
Thanks, I pushed for all three.

**Comment by ilovezfs** [comment]
@jasontedor thanks for the upgrade!

**Comment by jasontedor** [comment]
Thanks so much @ilovezfs.

**Pull request closed without merging**
