### PR TITLE
Icecream fixes

### PR DESCRIPTION
**Pull request by torarnv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by torarnv** [comment]
@timblechmann already fixed the deamonization it seems :)

**Comment by zbeekman** [comment]
@torarnv What's the status then? Shall we close this? Or is there something remaining to be done here?

**Comment by torarnv** [comment]
@zbeekman the remaining commit in this PR (6d09f5b93d6) is still valid. Did it break the build @SMillerDev ?

**Comment by torarnv** [comment]
My [comment](https://github.com/Homebrew/homebrew-core/pull/40879#issuecomment-500861917) earlier was about a second commit I had in the PR that was already fixed.

**Review by zbeekman — APPROVED** [review]
LGTM,

Although, I'm not sure what will happen regarding the plists, without a revision bump.

**Comment by torarnv** [comment]
> Although, I'm not sure what will happen regarding the plists, without a revision bump.

Not sure I follow 😄

**Pull request merged**
