### PR TITLE
llvm@8: fix Big Sur build, use CLT and system libffi

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

These are the same changes from #81345, along with a patch to make this
formula usable on Big Sur.

The patch is just a backport of the same patch for LLVM 9.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
Oops. Slight mistake in the patch. I think this should do it.

**Comment by carlocab** [comment]
Ok, that didn't work for some reason... Let's try making it prioritise the sysroot C++ headers instead of the bundled ones. It might be that they're just too old.

**Comment by carlocab** [comment]
Tested these patches out elsewhere and this should work now.

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
Right, 60-minute timeout. I forgot.

**Pull request closed without merging**
