### PR TITLE
solarus: fix build

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by DomT4** [comment]
Should this be getting applied to `HEAD` or?

**Comment by ilovezfs** [comment]
stable do block :)

**Comment by fxcoudert** [comment]
Fix now only applied to stable

**Comment by DomT4** [comment]
`unless build.head?` outside of `def install` is 🤢 😷, heh.

**Comment by fxcoudert** [comment]
@DomT4 yet it makes life easier when the patch has to be removed in next version

**Comment by DomT4** [comment]
> yet it makes life easier when the patch has to be removed in next version

Beauty isn't effortless 😉.

**Comment by fxcoudert** [comment]
Beauty is subjective, effort is not :)

**Comment by DomT4** [comment]
I'm still here 2800 commits to core later; not demanding everyone else picks up my style quirks without any assistance 😄.

**Comment by ilovezfs** [comment]
Just so we're all clear: spec blocks today, spec blocks tomorrow, spec blocks forever.

**Pull request closed without merging**
