### PR TITLE
rust 1.71.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Cargo `0.72.0` expected: https://github.com/rust-lang/cargo/tags

**Comment by SMillerDev** [comment]
```
  FAILED: lib/Support/CMakeFiles/LLVMSupport.dir/NativeFormatting.cpp.o 
  /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DGTEST_HAS_RTTI=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/build/x86_64-apple-darwin/llvm/build/lib/Support -I/tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/src/llvm-project/llvm/lib/Support -I/tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/build/x86_64-apple-darwin/llvm/build/include -I/tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/src/llvm-project/llvm/include -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -ffunction-sections -fdata-sections -fPIC --target=x86_64-apple-darwin -stdlib=libc++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -Werror=global-constructors -O3 -DNDEBUG -std=c++17 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.6  -fno-exceptions -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/NativeFormatting.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/NativeFormatting.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/NativeFormatting.cpp.o -c /tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/src/llvm-project/llvm/lib/Support/NativeFormatting.cpp
  /tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/src/llvm-project/llvm/lib/Support/NativeFormatting.cpp:172:12: error: expected unqualified-id
    if (std::isnan(N)) {
             ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/math.h:165:5: note: expanded from macro 'isnan'
      ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
      ^
  /tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/src/llvm-project/llvm/lib/Support/NativeFormatting.cpp:175:19: error: expected unqualified-id
    } else if (std::isinf(N)) {
                    ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/math.h:160:5: note: expanded from macro 'isinf'
      ( sizeof(x) == sizeof(float)  ? __inline_isinff((float)(x))          \
      ^
  /tmp/rust-20230713-6371-1825lt2/rustc-1.71.0-src/src/llvm-project/llvm/lib/Support/NativeFormatting.cpp:176:16: error: expected unqualified-id
      S << (std::signbit(N) ? "-INF" : "INF");
                 ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/math.h:170:5: note: expanded from macro 'signbit'
      ( sizeof(x) == sizeof(float)  ? __inline_signbitf((float)(x))        \
      ^
```

**Comment by ZhongRuoyu** [comment]
[The error on ARM and Linux](https://github.com/Homebrew/homebrew-core/actions/runs/5547012541/jobs/10128176275?pr=136514#step:3:7730) is different:

```
==> cargo install --root /opt/homebrew/Cellar/rust/1.71.0 --path . --features curl-sys/force-system-lib-on-osx
error: binary `cargo` already exists in destination
Add --force to overwrite
```

**Comment by chenrui333** [comment]
# current track list
aws-elasticbeanstalk, cython 3+, https://github.com/Homebrew/homebrew-core/pull/136977
aws-sam-cli, cython 3+, covered with new releases
azure-cli, cython 3+, https://github.com/Homebrew/homebrew-core/pull/137367
bindgen
bottom, sha issue, https://github.com/Homebrew/homebrew-core/pull/137181
charm-tools, cython 3+, https://github.com/Homebrew/homebrew-core/pull/137368
cloudflare-quiche, https://github.com/cloudflare/quiche/issues/1571
cyral-gimme-db-token, https://github.com/Homebrew/homebrew-core/pull/137369
flintrock, https://github.com/Homebrew/homebrew-core/pull/137370
git-interactive-rebase-tool, new PR should cover it
gluon, https://github.com/gluon-lang/gluon/issues/951
grin, https://github.com/mimblewimble/grin/issues/3764
grin-wallet, https://github.com/mimblewimble/grin-wallet/issues/683
gyb, need followup
jaq, https://github.com/01mf02/jaq/issues/97
keepkey-agent
onlykey-agent, cython 3+, fixed
pipe-rename, sha issue, fixed
roapi, https://github.com/roapi/roapi/issues/287
slither-analyzer, https://github.com/Homebrew/homebrew-core/pull/137371
smartdns, https://github.com/mokeyish/smartdns-rs/issues/159
sslyze, 
tremor-runtime, https://github.com/tremor-rs/tremor-runtime/issues/2340
trezor-agent, https://github.com/Homebrew/homebrew-core/pull/137372
uutils-findutils, sha issue

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
