### PR TITLE
snowpack 3.8.3

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Also part of https://github.com/Homebrew/homebrew-core/issues/81666.

**Comment by carlocab** [comment]
Since this is just universal binaries being installed, I suggest adding this to the allowlist so that your PR isn't blocked by the CI failure.

The bottle current has universal binaries in it already anyway, so there's no need to delay a version bump now that we've started checking for them.

**Comment by alebcay** [comment]
```
snowpack:
  * Binaries built for an incompatible architecture were installed into snowpack's prefix.
    The offending files are:
      /opt/homebrew/Cellar/snowpack/3.8.3/libexec/lib/node_modules/snowpack/node_modules/bufferutil/prebuilds/darwin-x64/node.napi.node
      /opt/homebrew/Cellar/snowpack/3.8.3/libexec/lib/node_modules/snowpack/node_modules/rollup/node_modules/fsevents/fsevents.node
      /opt/homebrew/Cellar/snowpack/3.8.3/libexec/lib/node_modules/snowpack/node_modules/utf-8-validate/prebuilds/darwin-x64/node.napi.node
    Unexpected universal binaries were found.
    The offending files are:
      /opt/homebrew/Cellar/snowpack/3.8.3/libexec/lib/node_modules/snowpack/node_modules/fsevents/fsevents.node
```

My understanding from reading this is that `fsevents.node` is a universal/fat binary in it and that the other two `node.napi.node`s are not universal but only x86_64.

So I agree the universal binary can get a pass with the allowlist, but there's still the other two to be addressed in that case.

**Comment by carlocab** [comment]
Ah, yes, I missed the audit failure about the x86 binaries. Strangely enough there seem to be two different versions of `fsevents` here -- one universal, and the other x86-only.

**Comment by carlocab** [comment]
Per #81666 if we can't find a way to build native versions of the x86 binaries, we should just delete them on ARM.

**Comment by chenrui333** [comment]
#83666

**Pull request closed without merging**
