### PR TITLE
ansible 2.0.2.0-0.4.rc4 (devel)

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by apjanke** [comment]
Part of this [failed to build on Mavericks](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/420/version=mavericks/). Do you know what's going on here?

```

==> Verifying ansible--debtcollector-1.2.0.tar.gz checksum
tar xvf /Library/Caches/Homebrew/ansible--debtcollector-1.2.0.tar.gz
x debtcollector-1.2.0/
x debtcollector-1.2.0/.mailmap
x debtcollector-1.2.0/test-requirements.txt
x debtcollector-1.2.0/debtcollector/
x debtcollector-1.2.0/debtcollector/removals.py
x debtcollector-1.2.0/debtcollector/updating.py
x debtcollector-1.2.0/debtcollector/_utils.py
x debtcollector-1.2.0/debtcollector/tests/
x debtcollector-1.2.0/debtcollector/tests/base.py
x debtcollector-1.2.0/debtcollector/tests/test_deprecation.py
x debtcollector-1.2.0/debtcollector/tests/__init__.py
x debtcollector-1.2.0/debtcollector/__init__.py
x debtcollector-1.2.0/debtcollector/renames.py
x debtcollector-1.2.0/debtcollector/fixtures/
x debtcollector-1.2.0/debtcollector/fixtures/__init__.py
x debtcollector-1.2.0/debtcollector/fixtures/disable.py
x debtcollector-1.2.0/debtcollector/moves.py
x debtcollector-1.2.0/debtcollector.egg-info/
x debtcollector-1.2.0/debtcollector.egg-info/dependency_links.txt
x debtcollector-1.2.0/debtcollector.egg-info/top_level.txt
x debtcollector-1.2.0/debtcollector.egg-info/PKG-INFO
x debtcollector-1.2.0/debtcollector.egg-info/SOURCES.txt
x debtcollector-1.2.0/debtcollector.egg-info/requires.txt
x debtcollector-1.2.0/debtcollector.egg-info/pbr.json
x debtcollector-1.2.0/debtcollector.egg-info/not-zip-safe
x debtcollector-1.2.0/.testr.conf
x debtcollector-1.2.0/ChangeLog
x debtcollector-1.2.0/babel.cfg
x debtcollector-1.2.0/tox.ini
x debtcollector-1.2.0/setup.cfg
x debtcollector-1.2.0/README.rst
x debtcollector-1.2.0/HACKING.rst
x debtcollector-1.2.0/doc/
x debtcollector-1.2.0/doc/source/
x debtcollector-1.2.0/doc/source/contributing.rst
x debtcollector-1.2.0/doc/source/installation.rst
x debtcollector-1.2.0/doc/source/conf.py
x debtcollector-1.2.0/doc/source/history.rst
x debtcollector-1.2.0/doc/source/examples.rst
x debtcollector-1.2.0/doc/source/api.rst
x debtcollector-1.2.0/doc/source/index.rst
x debtcollector-1.2.0/PKG-INFO
x debtcollector-1.2.0/.coveragerc
x debtcollector-1.2.0/CONTRIBUTING.rst
x debtcollector-1.2.0/MANIFEST.in
x debtcollector-1.2.0/LICENSE
x debtcollector-1.2.0/requirements.txt
x debtcollector-1.2.0/setup.py
x debtcollector-1.2.0/AUTHORS
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/ansible/2.0.1.0/libexec/vendor --single-version-externally-managed --record=installed.txt

Installed /private/tmp/ansible--debtcollector20160413-92807-1cjwxjh/debtcollector-1.2.0/pbr-1.9.0-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/private/tmp/ansible--debtcollector20160413-92807-1cjwxjh/debtcollector-1.2.0/pbr-1.9.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/private/tmp/ansible--debtcollector20160413-92807-1cjwxjh/debtcollector-1.2.0/pbr-1.9.0-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/private/tmp/ansible--debtcollector20160413-92807-1cjwxjh/debtcollector-1.2.0/pbr-1.9.0-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
AttributeError: 'module' object has no attribute 'evaluate_marker'
error in setup command: Error parsing /private/tmp/ansible--debtcollector20160413-92807-1cjwxjh/debtcollector-1.2.0/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'
==> Formula
```

**Comment by tdsmith** [comment]
It looks like it needs a newer setuptools; I'll take a look.

**Comment by Jerzerak** [comment]
Thanks for all the input Tim, just realized I was an idiot and accidentally checkout out the master branch when testing everything that's been failing. I'll get around to making some fixes tomorrow if you don't get around to it.

**Comment by tdsmith** [comment]
:+1:; no problem and thanks!

**Comment by Jerzerak** [comment]
Can't seem to figure this one out, builds fine locally for me

**Pull request closed without merging**
