### PR TITLE
mysql mysql-client mysql-connector-c++ 8.0.22

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
license info:
```
Q5: What open source licensing options does Oracle offer for its MySQL software?
A: Oracle makes its MySQL database server and MySQL Client Libraries available under the GPLv2, plus an additional permission for included software under other licenses.

For the MySQL Client Libraries, Oracle adds the further additional permission of the Universal FOSS Exception, allowing a qualifying FOSS application to use them without subjecting the entirety of the application to the reciprocal license requirement of the GPLv2. (See the License Information User Manual for each MySQL related download for license information specific to that distribution, including the terms and conditions of the GPLv2, the additional permission for included software under separate licenses, and the Universal FOSS Exception.)
```

**Comment by chenrui333** [comment]
license info for `mysql-connector-c++`:

```
Licensing Information User Manual

MySQL Connector/C++ 8.0
     __________________________________________________________________

Introduction

   This License Information User Manual contains Oracle's product license
   and other licensing information, including licensing information for
   third-party software which may be included in this distribution of
   MySQL Connector/C++ 8.0.

   Last updated: July 2020

Licensing Information

   This is a release of MySQL Connector/C++ 8.0, brought to you by the
   MySQL team at Oracle. This software is released under version 2 of the
   GNU General Public License (GPLv2), as set forth below, with the
   following additional permissions:

   This distribution of MySQL Connector/C++ 8.0 is distributed with
   certain software (including but not limited to OpenSSL) that is
   licensed under separate terms, as designated in a particular file or
   component or in the license documentation. Without limiting your rights
   under the GPLv2, the authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have included with the program.

   Without limiting the foregoing grant of rights under the GPLv2 and
   additional permission as to separately licensed software, this
   Connector is also subject to the Universal FOSS Exception, version 1.0,
   a copy of which is reproduced below and can also be found along with
   its FAQ at http://oss.oracle.com/licenses/universal-foss-exception.

   Copyright (c) 2008, 2020, Oracle and/or its affiliates.
```

**Comment by Rylan12** [comment]
The main `mysql` license seems to be `"GPL-2.0-only" => { with: "Universal-FOSS-exception-1.0" }`. It turns out that the `LICENSE` file is 8,563 lines long. After skimming the first 300 lines I came across this list:

```ruby
license all_of: [
  "GPL-2.0-only" => { with: "Universal-FOSS-exception-1.0" },
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSD-4-Clause",
  "MIT",
  "BSL-1.0",
]
```

I'm not really sure what to do about that. Do we need to go through the entire file? We might want to do that in a follow-up PR.

**Comment by chenrui333** [comment]
> The main `mysql` license seems to be `"GPL-2.0-only" => { with: "Universal-FOSS-exception-1.0" }`. It turns out that the `LICENSE` file is 8,563 lines long. After skimming the first 300 lines I came across this list:
> 
> ```ruby
> license all_of: [
>   "GPL-2.0-only" => { with: "Universal-FOSS-exception-1.0" },
>   "BSD-2-Clause",
>   "BSD-3-Clause",
>   "BSD-4-Clause",
>   "MIT",
>   "BSL-1.0",
> ]
> ```
> 
> I'm not really sure what to do about that. Do we need to go through the entire file? We might want to do that in a follow-up PR.

yeah, doing in the followup PR is a good idea. :)

**Review by Rylan12 — APPROVED** [review]

**Pull request closed without merging**
