### PR TITLE
migrate crystax-ndk to caskroom

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
-----
In addition to #11468 I think we should migrate `crystax-ndk` to caskroom

We haven't figured out yet how to better implement this casks in caskroom https://github.com/caskroom/homebrew-cask/issues/31234

### CODE REVIEW

**Comment by dunn** [comment]
Let us know when it's no longer WIP and we'll remove the do-not-merge label.

**Comment by miccal** [comment]
@dunn this is no longer WIP.

**Comment by yurikoles** [comment]
@dunn please merge, we are ready on our side

**Comment by ilovezfs** [comment]
Thanks @yurikoles

**Pull request merged**
