### PR TITLE
pulumi: Use a Go proxy to download deps

### PR DESCRIPTION
**Pull request by lblackstone**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why?

**Comment by lblackstone** [comment]
@fxcoudert Using a proxy makes the build much faster (25% in this case). I think it would make sense to update other Go formulas as well, although the status of this particular proxy is still "beta", so that may be a consideration.

Here's a comparison of the two builds:
No proxy (11 mins): https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/43984/
With proxy (8.25 mins): https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/44019/

Here's a blog post explaining the speedup: https://jfrog.com/blog/gocenter-is-fast-how-does-it-do-that/

**Comment by chenrui333** [comment]
Seems pretty cool stuff!

**Comment by fxcoudert** [comment]
Most users don't build from source, and if it's still beta I'd rather avoid it, for now. If we go ahead, we should integrate it into `brew` itself so that all go-based formulas benefit.

Thanks @lblackstone!

**Pull request closed without merging**
