### PR TITLE
open-mpi 4.1.0

### PR DESCRIPTION
**Pull request by ggouaillardet**
- bump to 4.1.0
 - use ENV.refurbish_args to fix AVX512 detection
 - do not force autogen.pl on Big Sur

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@fxcoudert per our discussion on open-mpi/ompi#8306 I used `ENV.refurbish_args`.

Unfortunately it did not help.

`02.make.cc` says that `-march=skylake-avx512` is indeed replaced with `-march=nehalem` by `superenv`.

But `01.configure.cc` reports that `-march=skylake-avx512` is **not** replaced, so `superenv` behavior is different between `configure` and `make`, in spite of `ENV.refurbish_args` being used, and them `make` fails as before.

Is this me doing something wrong? misunderstanding how `brew` works? A bug in how `ENV.refurbish_args` is being handled?

**Comment by fxcoudert** [comment]
@ggouaillardet I'll try to look into it, in my understanding it would be a superenv bug. But `refurbish_args` is really rare (used in 4 formulas in homebrew-core) that it's a bit of a corner case.

**Comment by fxcoudert** [comment]
It appears I misunderstood the workings of `ENV.refurbish_args`, so I apologize.
I don't really see a way other than turning off AVX completely, so let's do that.

**Comment by fxcoudert** [comment]
So we have a series of failures to build on ARM:

```
2020-12-28T16:04:59.0201020Z In file included from pmix_mca_base_close.c:26:
2020-12-28T16:04:59.0202550Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/util/output.h:76:
2020-12-28T16:04:59.0204530Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0206570Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0208620Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0211330Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0213200Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0213870Z            ^                            ~~~~
2020-12-28T16:04:59.0214520Z In file included from pmix_mca_base_component_compare.c:25:
2020-12-28T16:04:59.0216100Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/mca/base/base.h:31:
2020-12-28T16:04:59.0218100Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0220120Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0222180Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0224880Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0226740Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0227410Z            ^                            ~~~~
2020-12-28T16:04:59.0228090Z In file included from pmix_mca_base_component_repository.c:38:
2020-12-28T16:04:59.0229710Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_list.h:77:
2020-12-28T16:04:59.0231700Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0233710Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0235740Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0238400Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0240220Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0240950Z            ^                            ~~~~
2020-12-28T16:04:59.0241510Z In file included from pmix_mca_base_cmd_line.c:26:
2020-12-28T16:04:59.0243000Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/util/cmd_line.h:121:
2020-12-28T16:04:59.0244970Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0247010Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0249020Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0251730Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0253560Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0254200Z            ^                            ~~~~
2020-12-28T16:04:59.0254830Z In file included from pmix_mca_base_components_open.c:31:
2020-12-28T16:04:59.0256380Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_list.h:77:
2020-12-28T16:04:59.0258360Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0260350Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0262360Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0265020Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0266840Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0267950Z /opt/homebrew/Library/Homebrew/shims/scm/git --version
2020-12-28T16:04:59.0268580Z            ^                            ~~~~
2020-12-28T16:04:59.0269050Z 1 error generated.
2020-12-28T16:04:59.0269700Z In file included from pmix_mca_base_component_find.c:49:
2020-12-28T16:04:59.0271380Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/mca/pinstalldirs/pinstalldirs.h:21:
2020-12-28T16:04:59.0273440Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/mca/base/base.h:31:
2020-12-28T16:04:59.0275410Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0277420Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0279430Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0282090Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0283900Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0284550Z            ^                            ~~~~
2020-12-28T16:04:59.0285260Z In file included from pmix_mca_base_components_close.c:25:
2020-12-28T16:04:59.0286810Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_list.h:77:
2020-12-28T16:04:59.0288780Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0290910Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0292030Z 1 error generated.
2020-12-28T16:04:59.0293450Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0296100Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0297920Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0298580Z            ^                            ~~~~
2020-12-28T16:04:59.0299040Z 1 error generated.
2020-12-28T16:04:59.0299620Z make[5]: *** [pmix_mca_base_close.lo] Error 1
2020-12-28T16:04:59.0300270Z make[5]: *** Waiting for unfinished jobs....
2020-12-28T16:04:59.0300860Z 1 error generated.
2020-12-28T16:04:59.0301380Z 1 error generated.
2020-12-28T16:04:59.0302060Z make[5]: *** [pmix_mca_base_component_repository.lo] Error 1
2020-12-28T16:04:59.0302880Z make[5]: *** [pmix_mca_base_component_compare.lo] Error 1
2020-12-28T16:04:59.0303590Z make[5]: *** [pmix_mca_base_cmd_line.lo] Error 1
2020-12-28T16:04:59.0304290Z make[5]: *** [pmix_mca_base_components_open.lo] Error 1
2020-12-28T16:04:59.0304910Z 1 error generated.
2020-12-28T16:04:59.0305430Z 1 error generated.
2020-12-28T16:04:59.0306120Z In file included from pmix_mca_base_components_select.c:25:
2020-12-28T16:04:59.0307690Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_list.h:77:
2020-12-28T16:04:59.0309650Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/class/pmix_object.h:131:
2020-12-28T16:04:59.0311660Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/threads/thread_usage.h:31:
2020-12-28T16:04:59.0313650Z In file included from /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/atomic.h:168:
2020-12-28T16:04:59.0316300Z /private/tmp/open-mpi-20201228-52672-1jln4sf/openmpi-4.1.0/opal/mca/pmix/pmix3x/pmix/src/atomics/sys/gcc_builtin/atomic.h:197:12: error: address argument to atomic operation must be a pointer to integer or pointer ('pmix_atomic_int128_t *' (aka '_Atomic(pmix_int128_t) *') invalid)
2020-12-28T16:04:59.0318120Z     return __atomic_compare_exchange_n (addr, oldval, newval, false,
2020-12-28T16:04:59.0318770Z            ^                            ~~~~
2020-12-28T16:04:59.0319360Z make[5]: *** [pmix_mca_base_components_close.lo] Error 1
2020-12-28T16:04:59.0320100Z make[5]: *** [pmix_mca_base_component_find.lo] Error 1
2020-12-28T16:04:59.0320820Z 1 error generated.
2020-12-28T16:04:59.0321470Z make[5]: *** [pmix_mca_base_components_select.lo] Error 1
2020-12-28T16:04:59.0322410Z make[4]: *** [all-recursive] Error 1
2020-12-28T16:04:59.0323300Z make[3]: *** [all-recursive] Error 1
2020-12-28T16:04:59.0324180Z make[2]: *** [all-recursive] Error 1
2020-12-28T16:04:59.0325050Z make[1]: *** [all-recursive] Error 1
2020-12-28T16:04:59.0325940Z make: *** [all-recursive] Error 1
```

**Comment by ggouaillardet** [comment]
thanks for the report.

can you please confirm you are using Apple's `clang` to build Open MPI?

At this stage, you can only suggest you give a try to configuring with `--disable-builtin-atomics` and see if it is enough to workaround the issue.

tagging @hjelmn

**Comment by fxcoudert** [comment]
> can you please confirm you are using Apple's clang to build Open MPI?

Yes, we use gfortran for the Fortran parts, and Apple's clang as C compiler

**Pull request closed without merging**
