### PR TITLE
e2fsprogs 1.44.5

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
```
making install in e2fsck
	MKDIR_P /usr/local/Cellar/e2fsprogs/1.44.5/sbin /usr/local/Cellar/e2fsprogs/1.44.5/share/man/man8
make[1]: config/install-sh: No such file or directory
make[1]: *** [installdirs] Error 1
make: *** [install-progs-recursive] Error 1
```

**Comment by fxcoudert** [comment]
`configure` defines `MKDIR_P` as `MKDIR_P='config/install-sh -c -d'`, but since this is a relative path (not absolute), it fails to work in subdirectories. I can't report this upstream, because the sourceforge project does not accept creating tickets. Sad.

A workaround is to reassure configure that macOS's `mkdir` is thread-safe.

**Comment by fxcoudert** [comment]
@Moisan @igas can someone else try to report this upstream?

**Comment by Moisan** [comment]
I reported the issue upstream in the [discussion board](https://sourceforge.net/p/e2fsprogs/discussion/7053/thread/edec6de279/). I think the tickets were closed to the public due to a lot of spam.

**Pull request closed without merging**
