### PR TITLE
opencommit 2.0.0 (new formula)

### PR DESCRIPTION
**Pull request by Moulick**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Moulick** [comment]
Draft: Waiting for https://github.com/di-sukharev/opencommit/issues/144 as this conflicts with `openshift-cli`

Closes https://github.com/di-sukharev/opencommit/issues/143

**Comment by di-sukharev** [comment]
why is it draft?

**Comment by SMillerDev** [comment]
> Draft: Waiting for https://github.com/di-sukharev/opencommit/issues/144 as this conflicts with openshift-cli

**Comment by Moulick** [comment]
waiting for https://github.com/di-sukharev/opencommit/pull/178

**Comment by Moulick** [comment]
unstale?

**Pull request closed without merging**
