### PR TITLE
fstar 0.9.4.0

### PR DESCRIPTION
**Pull request by derekmorr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
did you mean to close that?

**Comment by derekmorr** [comment]
No, that was accidental.

**Comment by ilovezfs** [comment]
@derekmorr I've pushed a commit that should fix it.

**Comment by derekmorr** [comment]
Thanks much. This was my first PR for homebrew, and I'm very new to F*, so I appreciate the help.

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by ilovezfs** [comment]
@derekmorr Thanks for your first contribution to Homebrew! :sparkles:

**Pull request closed without merging**
