### PR TITLE
git 2.25.1

### PR DESCRIPTION
**Pull request by shigemk2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Pull request of git 2.25.1 is already opened in https://github.com/Homebrew/homebrew-core/pull/50335, but the test is still failing, so I re-sent PR again.

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like you haven't made any changes compared to #50335. The same issue applies:

```
==> /usr/local/Cellar/git/2.25.1/bin/git send-email --to=dev@null.com --smtp-server=smtp.gmail.com --smtp-encryption=tls --confirm=never HEAD^ 2>&1
Error: git: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <255> expected but was
<127>.
```

**Comment by shigemk2** [comment]
I don't have any idea why the test "git send-email" returns not 255 but 127 because the test succeeded in my environment(MacOS Mojave 10.14.6).

**Comment by samford** [comment]
In the interest of moving this forward, I installed Git 2.25.1 from source and tested it. At least for me (macOS 10.15.3), it hangs on the same `send-email` part of the test and eventually times out.

If I run the test manually, the output looks roughly like this:

```
/var/folders/jh/sbzk6gss0vb3v8kxz9rwn74h0000gn/T/To6FjFZTDC/0001-Second-Commit.patch
(mbox) Adding cc: Test <example@example.com> from line 'From: Test <example@example.com>'

Unable to initialize SMTP properly. Check config and use --smtp-debug. VALUES: server=smtp.gmail.com encryption=tls hello=mycomputername.localdomain port=25 at /usr/local/Cellar/git/2.25.1/libexec/git-core/git-send-email line 1558.
```

The test also fails in the same way for me on the current version in Homebrew (2.25.0), so this doesn't seem to be a new issue. Looking back at old Git PRs, they failed on CI as far back as I went (a few versions), which seems to support this idea.

The `send-email` part of the test is the only bit that fails, so we'll need to either fix this or remove it. Previous PRs have been merged with the test failing on CI but I think we should address this rather than kicking the can down the road.

**Comment by SMillerDev** [comment]
I'd say to just remove the test? Can we see when/why it was added?

**Comment by samford** [comment]
> Can we see when/why it was added?

It was added in [fdc60059](https://github.com/Homebrew/homebrew-core/commit/fdc600597198f14853672fb69fa382a4017a0ba4) on 2018/12/28 as part of #35446. This is where the Git `send-email` feature was added, so that part of the test was also added to test it.

I worked on this a bit and discovered that the `send-email` part of the test can be fixed by adding `--smtp-server-port=587` to the arguments. I pushed a commit to this PR's branch to fix the test, so it will hopefully be good on CI this time around (and going forward).

**Comment by samford** [comment]
```
==> /usr/local/Cellar/git/2.25.1/bin/git send-email --from=test@example.com --to=dev@null.com --smtp-server=smtp.gmail.com --smtp-server-port=587 --smtp-encryption=tls --confirm=never HEAD^ 2>&1
Error: git: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <255> expected but was
<127>.
```

This time around, the test failed on Catalina and Mojave and inexplicably passed on High Sierra. I was testing this locally on Catalina, so it's surprising it failed there. The `send-email` part of the test is slow so, unless something is different on CI, it may just be a coin toss how it's going to play out on a given run.

**Comment by Bo98** [comment]
The idea behind the test I imagine is to try and see if `Net::SMTP::SSL` is installed correctly.

If you want me to test it on a CI node directly, I can do that.

**Comment by samford** [comment]
> The idea behind the test is to try and see if `Net::SMTP::SSL` is installed correctly, so it would be ideal to make sure it's doing that and a dry run doesn't just skip that.

I can look into it later, when I get a free moment.

> If you want me to try it on a CI node directly, I can do that.

I was just thinking, "I wonder if it's possible to debug this on CI", so you must have been reading my mind, ahah. At least from my local testing, if you temporarily modify the test to match the value it's reporting (e.g., 127 on CI rather than 255), it should display the SMTP error when running `brew test --verbose git`. You can also just comment out the `send-email` lines and run the command using `system` and output the result.

I'll be gone for a bit but I'll check back later.

**Comment by Bo98** [comment]
Local machine (exit code 255):

```
==> /usr/local/Cellar/git/2.25.0_1/bin/git send-email --to=dev@null.com --smtp-s
5.7.0 Authentication Required. Learn more at
5.7.0  https://support.google.com/mail/?p=WantAuthError j14sm55252929wrn.32 - gsmtp
/private/tmp/oJ27D0CYYG/0001-Second-Commit.patch
(mbox) Adding cc: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org> from line 'From: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>'
```

CI (exit code 127):

```
==> /usr/local/Cellar/git/2.25.0_1/bin/git send-email --to=dev@null.com --smtp-s
/private/tmp/hRfjxgiKsv/0001-Second-Commit.patch
(mbox) Adding cc: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org> from line 'From: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>'
5.7.0 Authentication Required. Learn more at
5.7.0  https://support.google.com/mail/?p=WantAuthError u127sm15491568ywb.68 - gsmtp
```

🤷‍♂

**Comment by samford** [comment]
Oh, that's actually good news. Thanks for running this on CI, so I could see what's actually happening.

The output is different when it's failing like it was before (you get `Unable to initialize SMTP properly` as in my original comment) and the output from CI above is what you see when `send-email` is working properly. With the `Authentication Required` text in the output (as above), the `assert_match` _should_ match but `shell_output` compares the exist status and the mismatch doesn't let us get that far.

I imagine we primarily care about matching "Authentication Required" in the output and not so much the exit status, so I pushed a modified version of the test fix that uses `pipe_output` instead of `shell_output`. Fingers crossed this fixes it on CI, for real this time.

**Comment by samford** [comment]
We have a winner! Everything looks good on CI now, so as long as we don't care about matching the exit status (allowing us to use `pipe_output` as mentioned before), this should be good to go.

**Review by chenrui333 — APPROVED** [review]
🚀

**Pull request closed without merging**
