### PR TITLE
cloudflare-wrangler 1.19.3

### PR DESCRIPTION
**Pull request by luc122c**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
looks like they updated their error message, we can update the test to something like:

```diff
diff --git a/Formula/cloudflare-wrangler.rb b/Formula/cloudflare-wrangler.rb
index 2131c48378..ff74075390 100644
--- a/Formula/cloudflare-wrangler.rb
+++ b/Formula/cloudflare-wrangler.rb
@@ -20,6 +20,6 @@ class CloudflareWrangler < Formula
 
   test do
     output = shell_output("CF_API_TOKEN=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA #{bin}/wrangler whoami 2>&1", 1)
-    assert_match(/Code 9109: (?:Invalid access token|Max auth failures reached)/, output)
+    assert_match "Failed to retrieve information about the email", output
   end
 end
```

**Comment by luc122c** [comment]
Yes, the change seems to have been made here: https://github.com/cloudflare/wrangler/compare/v1.19.2...v1.19.3#diff-3901dd7db5d17051a4fbd2a9b08a9319377d27469a11a9cfaabb600018f8ba94

**Comment by luc122c** [comment]
The build failures don't looks to be due to the test. I'm seeing `warning: spurious network error (1 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 147 was not closed cleanly before end of the underlying stream)` in the logs. Can the tests be re-run?

**Comment by samford** [comment]
I've pushed a temporary commit to test a `cargo` environment variable in hopes that it will address the spurious network errors. If it ends up reliably helping, I'll remove it from here and look into integrating it into test-bot or our CI workflow (so we hopefully don't have to manually add this to all the formulae that use `cargo` in the `install` block).

Pardon the dust while I test this out on CI.

**Comment by samford** [comment]
I tested this twice, both without and with the `CARGO_HTTP_MULTIPLEXING=false` environment variable. Without it, Ubuntu CI predictably failed with spurious network errors. With the environment variable, Ubuntu CI didn't encounter spurious network errors and ran to completion.

This workaround seems promising so far. I've removed the temporary commit in this PR and I'll work on creating a separate PR for a more permanent fix.

**Comment by luc122c** [comment]
Thank you @samford ! I don't know enough about cargo or homebrew development or GitHub actions to really help, so thanks so much for tackling this 😄

**Comment by samford** [comment]
I mentioned this internally and it was brought to my attention that cURL 7.79.1 (releasing on 2021-09-22) will include a fix for this issue. I'm going to sit on this workaround for the moment and see how it plays out in the coming days but it's good to know that we have a backup plan, if needed.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
