### PR TITLE
vcpkg 2022.02.01

### PR DESCRIPTION
**Pull request by k06a**
Hello, I'm new to the process of Homebrew formula update submission. I have an issue with vcpkg on the latest macOS 12.2, so trying to find out how to solve it.

My issue: https://github.com/microsoft/vcpkg/discussions/22926
Similar issue: https://github.com/Homebrew/homebrew-core/issues/74905

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
  Error: vcpkg: SHA256 mismatch
  Expected: c32c8e98ba705d054dced56003dd7a9b7e367d0908b0b57730be54dc4024abf4
    Actual: 5c3dbfca94763a0651d02a3f1c181e4d797b39ad4f82445963e0c1b5a387f30c
```

**Comment by k06a** [comment]
@carlocab thanks for your help!

**Comment by carlocab** [comment]
CI isn't running properly. Probably because of https://www.githubstatus.com/incidents/vvthhf8gxt80

**Review by SMillerDev — APPROVED** [review]
Thanks @k06a  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
