### PR TITLE
Migrate style exceptions to homebrew/core

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Migrate style exceptions to homebrew/core.

Corresponds with https://github.com/Homebrew/brew/pull/9326

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by PatTheMav** [comment]
@Rylan12 Since this was merged I ran into the issue that `brew style` marks formulas as incompatible even though they worked before the merge, e.g.:

`uses_from_macos should only be used for macOS dependencies, not bzip2`

Is it expected that custom taps keep a copy of these allowlists and maintain them as well or should the "default" lists be inherited from the core? I'm fine with keeping these files in my custom tap as well, it'd be just good to know what the intended procedure for custom taps is (if so, having `brew tap-new` add them by default could fix this as well).

**Comment by Rylan12** [comment]
Sorry about that.

If you'd like `brew style` to not complain, then yes, adding these lists to your personal tap should solve the problem. It's intentional that the default lists are _not_ inherited as these are pretty tap-specific (`brew audit` will actually complain if you include a formula in one of these lists that isn't in the tap).

As for the intended procedure, simply adding a `style_exceptions/list.json` containing a list of formulae should be all you need. Without knowing the details of your situation I'd guess that you're looking at `style_exceptions/non_keg_only_provided_by_macos_formulae.json`.

Since these lists are empty by default and are very tap-specific, I don't think it makes much sense to add them automatically with `tap-new`. It would just be creating several blank and needed files.

I have tested this on a custom tap (although not extensive) so It's possible that there are some bugs. If you're having an issue, feel free to open a new issue or discussion (and cc me).

**Comment by PatTheMav** [comment]
@Rylan12 Check my update above - on my macOS machine it doesn't complain, but by default the `test-bot` workflow created by `brew tap-new` creates a Linux+macOS matrix and for now it fails with this on Linux, aborting the macOS run as well.

**Comment by MikeMcQuaid** [comment]
> PROVIDED_BY_MACOS_FORMULAE NON_KEG_ONLY_PROVIDED_BY_MACOS_FORMULAE

@Rylan12 Arguably these aren't actually tap specific, though, and there's probably an argument to move them back to Homebrew/brew as a result.

**Comment by Rylan12** [comment]
> @Rylan12 Check my update above - on my macOS machine it doesn't complain, but by default the `test-bot` workflow created by `brew tap-new` creates a Linux+macOS matrix and for now it fails with this on Linux, aborting the macOS run as well.

Hmm, interesting. I'll have to take a look. Might be an issue with the difference between homebrew-core and linuxbrew-core... Not sure off the top of my head.

> > PROVIDED_BY_MACOS_FORMULAE NON_KEG_ONLY_PROVIDED_BY_MACOS_FORMULAE
> 
> @Rylan12 Arguably these aren't actually tap specific, though, and there's probably an argument to move them back to Homebrew/brew as a result.

Yeah, that's a good point.

To both: I've got a busy day today so I may not have a chance to really look into this until later. Thanks for raising the issue, though.

**Comment by Rylan12** [comment]
PR with a fix opened https://github.com/Homebrew/brew/pull/9397

**Pull request merged**
