### PR TITLE
mercurial: add a HEAD download

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
I can't seem to find a way to make this work unless I were to provide an hg external to brew. Did you find a way?

**Comment by alex** [comment]
Ugh, I don't know how I missed this, I had an `hg` lingering around that I'd installed with `pip`.

I'll switch it to using the `tar.gz` export of the VCS.

**Comment by ilovezfs** [comment]
The tarball export will still be problematic because it won't actually update unless you clear your cache. Any chance there's a Git mirror of the mercurial repository?

**Comment by alex** [comment]
I don't know if such a thing exists. @durin42 -- do you know?

**Comment by durin42** [comment]
Nope. I'd be somewhat opposed to doing a build from that too, because it'd be hard for us to get useful data from `hg version` output.

**Comment by durin42** [comment]
A thought from chatting on irc: could we make the HEAD build of hg bootstrap using a known-good release version, and just not expose that bootstrap hg to the user? It's kind of groty, but I don't have better ideas offhand.

(Soon we hope to have a Mac buildbot, and might be able to build some kind of prebuilt binary ~nightly if that would help, but I'm not sure how prebuilt binaries and homebrew work...)

**Comment by ilovezfs** [comment]
@durin42 the problem there is that the known good version would need to be available before the formula can even fetch HEAD, which precedes execution of the install method.

**Comment by durin42** [comment]
What if it was a keg-only (I think that's the term?) `_bootstrap_hg` package or something that installed a release hg from a tarball?

(I'm just throwing ideas out here, not in love with any of this.)

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ PATH=/usr/local/opt/mercurial-pypi/bin:$PATH brew install --HEAD hg
==> Using the sandbox
==> Cloning https://www.mercurial-scm.org/repo/hg
Updating /Users/joe/Library/Caches/Homebrew/mercurial--hg
warning: connecting to www.mercurial-scm.org using legacy security technology (TLS 1.0); see https://mercurial-scm.org/wiki/SecureConnections for more info
==> make PREFIX=/usr/local/Cellar/mercurial/HEAD-b647b923486f install-bin
```

;)

It would require a new formula and the user to manually pass that PATH though :(

**Comment by ilovezfs** [comment]
Actually if we were to declare a dependency on it works without manually passing the PATH.

```
  head do
    url "https://www.mercurial-scm.org/repo/hg", :using => :hg

    depends_on "mercurial-pypi" => :build
  end
```

**Comment by ilovezfs** [comment]
In any case, I think I'd be hard-pressed to justify adding another formula just to a support a head spec here.

**Comment by ilovezfs** [comment]
If anyone wants to play with that idea more, `mercurial-pypi.rb` is
```
class MercurialPypi < Formula
  include Language::Python::Virtualenv

  desc "Scalable distributed version control system from PyPI"
  homepage "https://mercurial-scm.org/"
  url "https://files.pythonhosted.org/packages/76/77/653194e51b0d73f5e4be9a1083ff6ef6947e47da0363cdab2a1aa301d88e/mercurial-4.2.tar.gz"
  sha256 "23a412308fc9c2b354a0e91a89588a4af2af061b47da80bc4233ccb0cceef47d"

  keg_only "Allows it to be installed alongside the main mercurial formula"

  def install
    virtualenv_install_with_resources
  end

  test do
    system "#{bin}/hg", "init"
  end
end
```

**Comment by ilovezfs** [comment]
OK so this works:
```
brew install mercurial
brew unlink mercurial
PATH=/usr/local/Cellar/mercurial/4.2/bin:$PATH brew install --HEAD mercurial
```

So if someone can make a `brew` backend change that makes the `PATH=/usr/local/Cellar/mercurial/4.2/bin:$PATH` part unnecessary, that should be an acceptable approach.

**Comment by ilovezfs** [comment]
Or even better get it do the first two steps automatically.

**Comment by ilovezfs** [comment]
Closing here for now but we can reconsider this if appropriate backend changes are made in brew to support it.

**Pull request closed without merging**
