### PR TITLE
grafana 7.5.6

### PR DESCRIPTION
**Pull request by aknuds1**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — COMMENTED** [review]
Re-licensed in https://github.com/grafana/grafana/pull/33184.

**Comment by nandahkrishna** [comment]
Thanks for the clarification, I think we can ignore the audit failure then.

**Review by carlocab — APPROVED** [review]

**Comment by nandahkrishna** [comment]
Seems like there was a build failure on Catalina:
```
error https://registry.yarnpkg.com/glob-parent/-/glob-parent-5.1.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/private/tmp/grafana-20210511-90219-cat2je/grafana-7.5.6/.brew_home/Library/Caches/Yarn/v6/npm-glob-parent-5.1.0-5f4c1d1e748d30cd73ad2944b3577a81b081e8c2-integrity/node_modules/glob-parent/index.js'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by carlocab** [comment]
Oops. I was pretty sure to check all the runners for errors before triggering the merge...

**Comment by nandahkrishna** [comment]
I tried that earlier and it failed with the same error. Seems to happen often with YARN?

**Pull request closed without merging**
