### PR TITLE
pgplot: migrate to brewed X11

### PR DESCRIPTION
**Pull request by carlocab**
Tracking issue: https://github.com/Homebrew/homebrew-core/issues/64166

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----
- [x] `brew install FORMULA` on this list (should be poured from a bottle, not built from source)
- [x] Run `brew linkage FORMULA` and observe which X11 libraries it links against
- [x] Modify the formula to remove `depends_on :x11` and replace it with e.g. `depends_on "libx11"` and any additional X libraries
- [x] Update `/opt/X11` or `MacOS::XQuartz` references to instead point them to the brewed formula paths
- [x] `revision` bump
- [x] `brew install -s FORMULA` and `brew linkage FORMULA` to check that it's now linking against brewed X and not XQuartz
-----
I missed the license, but `brew audit --strict` didn't complain about its absence, weirdly enough.

The license for this appears to be this: https://sites.astro.caltech.edu/~tjp/pgplot/#copyright

>PGPLOT is not public-domain software. However, it is freely available for non-commercial use. The source code and documentation are copyrighted by California Institute of Technology, and may not be redistributed or placed on public Web servers without permission. The software is provided ``as is'' with no warranty.
-----
Before:

    ❯ brew linkage pgplot
    System libraries:
      /opt/X11/lib/libX11.6.dylib
      /usr/lib/libSystem.B.dylib
      /usr/lib/libz.1.dylib
    Homebrew libraries:
      /usr/local/lib/gcc/10/libgcc_s.1.dylib (gcc)
      /usr/local/opt/gcc/lib/gcc/10/libgfortran.5.dylib (gcc)
      /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib (gcc)
      /usr/local/opt/libpng/lib/libpng16.16.dylib (libpng)
      /usr/local/Cellar/pgplot/5.2.2_9/lib/libcpgplot.dylib (pgplot)
      /usr/local/Cellar/pgplot/5.2.2_9/lib/libpgplot.dylib (pgplot)
    Variable-referenced libraries:
      @loader_path/libpgplot.dylib

After:

    ❯ brew linkage pgplot
    System libraries:
      /usr/lib/libSystem.B.dylib
      /usr/lib/libz.1.dylib
    Homebrew libraries:
      /usr/local/lib/gcc/10/libgcc_s.1.dylib (gcc)
      /usr/local/opt/gcc/lib/gcc/10/libgfortran.5.dylib (gcc)
      /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib (gcc)
      /usr/local/opt/libpng/lib/libpng16.16.dylib (libpng)
      /usr/local/opt/libx11/lib/libX11.6.dylib (libx11)
      /usr/local/Cellar/pgplot/5.2.2_10/lib/libcpgplot.dylib (pgplot)
      /usr/local/Cellar/pgplot/5.2.2_10/lib/libpgplot.dylib (pgplot)
    Variable-referenced libraries:
      @loader_path/libpgplot.dylib

### CODE REVIEW

**Comment by jonchang** [comment]
Not sure this license is acceptable for Homebrew/core. @homebrew/plc thoughts?

**Comment by carlocab** [comment]
I was under that impression re the license as well.

Debian seems to package pgplot, but perhaps their license requirements are a bit more permissive. There was a [question](https://lists.debian.org/debian-legal/2008/03/msg00119.html) about the status of pgplot's license on the DebianLegal list, but no one appeared to respond to that.

**Comment by jonchang** [comment]
I looked into the links and read some more documentation and it seems that pgplot is non-free, so we'll have to remove it. Thanks for helping out!

**Comment by carlocab** [comment]
That's a shame. Not the end of the world though!

**Comment by jonchang** [comment]
Debian uses [giza](http://giza.sourceforge.net/) to partially replace pgplot functionality, so it might be worth adding if another formula eventually ends up needing pgplot libraries.

**Comment by carlocab** [comment]
Yes, I noticed you mentioned it in another thread. I'll look into a PR for a new formula for Giza. I'll let you know if I'm not able to figure it out, though I'll give it plenty of time since I imagine this a relatively low-priority issue.

**Comment by carlocab** [comment]
@jonchang I've added a formula for giza: https://github.com/Homebrew/homebrew-core/pull/64787

**Pull request merged**
