### PR TITLE
codemod 1.0.0

### PR DESCRIPTION
**Pull request by orip**
- Also fix HEAD installation by using virtualenv_install_with_resources
- Also add meaningful test

### CODE REVIEW

**Review by ilovezfs — DISMISSED** [review]
I'd like to avoid using virtualenv here even it means we need to remove head. But the test is a welcome addition.

**Comment by orip** [comment]
Removed virtualenv, fixed install instead (was needed for 1.0.0 too - binary name has changed)

**Comment by ilovezfs** [comment]
Do you know what the deal is with 1.0.0 not being tagged on GitHub?

**Comment by orip** [comment]
Nope - I'm assuming that on a tiny tool like codemod FB doesn't setup the full release scripts, but I don't know.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @orip! :white_check_mark:

**Pull request merged**
