### PR TITLE
opencv: fix Adding with-qt formula option

### PR DESCRIPTION
**Pull request by mabrowning**
- [y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
I need the Qt interface for my OpenCV tool. The science/opencv formula had this option, so I've added the option to core/opencv as well. Since we can build OpenGL "for free" when Qt is available, I've bundled those OpenCV options into one formula option.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Going to pass on this because we'd like to keep the formula option free but thanks for the pull request, nonetheless. You may want to host this [in your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).

**Comment by mabrowning** [comment]
Would you consider an option-free formula that treats Qt as an optional dependency and builds WITH_QT=ON if it is detected? (obviously only works for --build-from-source)

**Comment by ilovezfs** [comment]
>Would you consider an option-free formula that treats Qt as an optional dependency and builds WITH_QT=ON if it is detected? (obviously only works for --build-from-source)

`superenv` will actively block that from working.

**Comment by mabrowning** [comment]
Fair enough, I'm obviously new to writing formulae... Thanks for the feedback!

**Pull request closed without merging**
