### PR TITLE
openssl 1.0.2j

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by alex** [comment]
This will probably exceed the timeout and need to be whitelisted.

**Comment by alex** [comment]
@DomT4 it looks like the build got aborted again?

**Comment by alex** [comment]
wait, nevermind, it just got restarted.

**Comment by DomT4** [comment]
Yeah, aborted by @zmwangx. Maybe he missed that I'd already bumped the timeout or something. No harm done at least, wasn't far into the build.

**Comment by zmwangx** [comment]
> Maybe he missed that I'd already bumped the timeout or something. 

No, I aborted the build because Jenkins failed both yosemite and el_capitan, so two or three hours later you'll end up with a useless build with only one bottle.

**Comment by DomT4** [comment]
Ah, right you are, thanks.

**Comment by zmwangx** [comment]
Feel free to abort the Sierra bottling jobs midway; I'll requeue the unbottled ones. My current estimate is it takes at least another week to finish bottling everything that we can.

**Comment by zmwangx** [comment]
Actually, my current and previous bottling jobs were running on sierra_2, not sierra which is the only machine used for Core PRs; you should yell at the Brew PR occupying sierra instead...

**Comment by alex** [comment]
Some of the derived builds failed, I'm not sure the failures are relevant though.

**Comment by zmwangx** [comment]
They're not, it's mostly due to a bug in `test-bot` code (unlink to avoid conflict then fail to link when needed by a dependent).

**Comment by DomT4** [comment]
Yeah, just CI gunk again. Merged in https://github.com/Homebrew/homebrew-core/commit/8c523f908be5feb3e73b8fa07cd000d9840bf009. Thank you for another contribution to Homebrew @alex 😺.

**Pull request closed without merging**
