### PR TITLE
condure 1.0.1 (new formula)

### PR DESCRIPTION
**Pull request by jkarneges**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jkarneges** [comment]
Looks like the CI checks failed, but there is no specific error message. Any advice? Thank you.

**Comment by jkarneges** [comment]
Ah, I see extra information now. Not notable enough! Hah, well then.

I wonder if I can get an exception? A future version of pushpin (an existing formula) will be using condure as a dependency.

**Comment by Rylan12** [comment]
Thanks for the PR, @jkarneges!

You can view the logs by clicking the `details` button to the right of the check. Here's the error message you're getting:

```
==> brew audit condure --online --new-formula
==> FAILED
Error: 1 problem in 1 formula detected
condure:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

Unfortunately, as you can see, this doesn't meet all of our [requirements for new formulae](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff).

However, you can (and are encouraged) to [maintain your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) which would still allow users to install your package using Homebrew

**Comment by Rylan12** [comment]
> I wonder if I can get an exception? A future version of pushpin (an existing formula) will be using condure as a dependency.

We do sometimes make exceptions in these circumstances, but I think we should wait until `condure` is required by `pushpin`. Feel free to bring this up again at that point, though.

**Comment by jkarneges** [comment]
Thanks @Rylan12, that seems reasonable. Will report back soon.

**Comment by jkarneges** [comment]
Hi, `pushpin` 1.30.0 is now in Homebrew with optional support for `condure`. It would be great to see this dependency merged.

**Comment by Rylan12** [comment]
Can you create a new PR for this to be discussed (these older ones tend to go under the radar)?

FYI, it's possible that this still won't be accepted. If that happens, you can try adding `condure` to `pushpin` in a `resource` block.

**Comment by jkarneges** [comment]
Thanks @Rylan12, will repost.

**Pull request closed without merging**
