### PR TITLE
swiftgen 6.1.0

### PR DESCRIPTION
**Pull request by AliSoftware**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] 🚨 Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?  
🚨 **No, because I hit https://github.com/Homebrew/brew/issues/5561**

-----

\cc @djbe

### CODE REVIEW

**Comment by AliSoftware** [comment]
Is it normal for the CI to take that long to start? Is the queue of pending builds _that_ long so that it takes a day to start? Or is it because I force-pushed on the PR and it messed up the trigger?
\cc @fxcoudert

**Comment by AliSoftware** [comment]
Idk, we could try, but contribution guidelines say we should squash our commits in our PRs, so that they keep a clean main branch, so…

ping @MikeMcQuaid ?

**Comment by MikeMcQuaid** [comment]
@AliSoftware Not sure why this didn't trigger. Should do now.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @AliSoftware!

**Comment by AliSoftware** [comment]
Awesome @MikeMcQuaid, thanks a lot for intervening on this so quickly! Here, take a 🍺  😉

**Pull request closed without merging**
