### PR TITLE
hledger 1.19

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> stack init --resolver=lts-15.16
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- hledger-1.19/
- hledger-lib/
- hledger-ui/
- hledger-web/

Selected resolver: lts-15.16
Resolver 'lts-15.16' does not have all the packages to match your requirements.
    hledger version 1.19 found
        - hledger-ui requires >=1.18.1 && <1.19
        - hledger-web requires >=1.18.1 && <1.19
    hledger-lib version 1.18.1 found
        - hledger requires ==1.19.*
    Using package flags:
        - hledger: FlagName "terminfo" = True, FlagName "threaded" = True
        - hledger-ui: FlagName "threaded" = True
        - hledger-web: FlagName "dev" = False, FlagName "library-only" = False, FlagName "threaded" = True

This may be resolved by:
    - Using '--omit-packages' to exclude mismatching package(s).
    - Using '--resolver' to specify a matching snapshot/resolver
```

**Comment by athas** [comment]
The hledger formula uses `stack`, and hardcodes a specific stack snapshot (lts-15.16).  The new version of hledger [uses lts-16.3](https://github.com/simonmichael/hledger/blob/e95a222ad248a5944fe2c0d1960b0f657f55b3a6/stack.yaml#L7).  Bumping the hardcoded snapshot in the formula is likely to fix this.

**Comment by chenrui333** [comment]
```
==> stack install --system-ghc --no-install-ghc --local-bin-path=/usr/local/Cellar/hledger/1.19/bin
No compiler found, expected minor version match with ghc-8.8.3 (x86_64) (based on resolver setting in /private/tmp/hledger-20200906-10775-6o1u69/stack.yaml).
To install the correct GHC into /private/tmp/hledger-20200906-10775-6o1u69/hledger-1.19/.brew_home/.stack/programs/x86_64-osx/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```

**Comment by athas** [comment]
Urgh, right, it also needs to depend on the right GHC, since `stack` is picky.

Maybe we should just use cabal for this formula, like most other Haskell formulae?  Is there a reason it uses stack?  I will have access to macOS tomorrow, and then I can try changing the formula to use cabal instead.

**Comment by chenrui333** [comment]
alright, adopt this commit change, https://github.com/simonmichael/hledger/commit/5f1e040ad78f165ef68f25a99c7d5251510e9d3a, let's see how it goes. :)

**Comment by chenrui333** [comment]
I think it is fine, it was actually updated by Simon to use stack some time ago.

**Comment by chenrui333** [comment]
Should be good now (just squashed my commits)

**Comment by simonmichael** [comment]
@chenrui333 thanks for working on this!

I made the formula use stack to prevent occasional homebrew CI failures due to unreliable cabal install plans. And as an experiment to see how stack and homebrew coexist. If you don't get it working, I'll take a look as soon as I clear the backlog of release tasks. I'll be releasing hledger 1.19.1 soon.

**Comment by chenrui333** [comment]
I think it is working fine now. Thanks Simon!

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
