### PR TITLE
pytorch 2.1.0 torchvision 0.16.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on linux

```
  ==> /usr/bin/g++-11 -std=c++17 test.cpp -o test -fopenmp -I/home/linuxbrew/.linuxbrew/opt/pytorch/include -I/home/linuxbrew/.linuxbrew/opt/pytorch/include/torch/csrc/api/include -L/home/linuxbrew/.linuxbrew/opt/pytorch/lib -ltorch -ltorch_cpu -lc10 -L/home/linuxbrew/.linuxbrew/Cellar/torchvision/0.16.0/lib -ltorchvision
  In file included from test.cpp:4:
  /home/linuxbrew/.linuxbrew/opt/torchvision/include/torchvision/vision.h:10:40: warning: ‘_register_ops’ initialized and declared ‘extern’
     10 | extern "C" VISION_INLINE_VARIABLE auto _register_ops = &cuda_version;
        |                                        ^~~~~~~~~~~~~
  ==> ./test
  test: test.cpp:8: int main(): Assertion `ops.size() == 1' failed.
```

**Comment by iMichka** [comment]
```
  ==> ./test
  Value ops.size() : 0
  test: test.cpp:9: int main(): Assertion `ops.size() == 1' failed.
```

**Comment by iMichka** [comment]
I asked upstream if they could help: https://github.com/pytorch/vision/issues/2134#issuecomment-1793846900

**Review by iMichka — CHANGES_REQUESTED** [review]
Ok hold of merging this then, I will check for both Python 3.12 and protobuf locally before submitting this to CI again.

**Comment by iMichka** [comment]
`protobuf` is in `pytorch`.

I tested and it worked, will do a rerun with that change.

The Python change can't be done:

```
==> python3.12 -m pip --python=/home/linuxbrew/.linuxbrew/Cellar/pytorch/2.1.0/libexec/bin/python install --verbose --no-deps --no-binary=:all: --ignore-installed --no-compile /tmp/pytorch--opt-einsum-20231108-10677-wpda34/opt_einsum-3.3.0
Using pip 23.2.1 from /home/linuxbrew/.linuxbrew/lib/python3.12/site-packages/pip (python 3.12)
Processing /tmp/pytorch--opt-einsum-20231108-10677-wpda34/opt_einsum-3.3.0
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-68.2.2-py3-none-any.whl
  Collecting wheel
    Using cached wheel-0.41.3-py3-none-any.whl
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-68.2.2 wheel-0.41.3

  [notice] A new release of pip is available: 23.2.1 -> 23.3.1
  [notice] To update, run: python -m pip install --upgrade pip
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  /tmp/pytorch--opt-einsum-20231108-10677-wpda34/opt_einsum-3.3.0/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
    LONG_VERSION_PY['git'] = '''
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/linuxbrew/.linuxbrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-dip7ea7k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-dip7ea7k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-dip7ea7k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-dip7ea7k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 17, in <module>
    File "/tmp/pytorch--opt-einsum-20231108-10677-wpda34/opt_einsum-3.3.0/versioneer.py", line 1480, in get_version
      return get_versions()["version"]
             ^^^^^^^^^^^^^^
    File "/tmp/pytorch--opt-einsum-20231108-10677-wpda34/opt_einsum-3.3.0/versioneer.py", line 1412, in get_versions
      cfg = get_config_from_root(root)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pytorch--opt-einsum-20231108-10677-wpda34/opt_einsum-3.3.0/versioneer.py", line 342, in get_config_from_root
      parser = configparser.SafeConfigParser()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/linuxbrew/.linuxbrew/Cellar/pytorch/2.1.0/libexec/bin/python /home/linuxbrew/.linuxbrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp7wx8mkmd
  cwd: /tmp/pytorch--opt-einsum-20231108-10677-wpda34/opt_einsum-3.3.0
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Review by iMichka — APPROVED** [review]
This should be good to go now, once it is built.

**Comment by chenrui333** [comment]
> This should be good to go now, once it is built.

💯

**Review by p-linnane — APPROVED** [review]
Nicely done!

**Pull request merged**
