### PR TITLE
ghc 9.6.2

### PR DESCRIPTION
**Pull request by trinitronx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [⚠️ℹ️ ✔︎?] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
  - Rebased: #136863 on latest master
  - Add missing dependency: `libffi`
  - Fixed [FTBFS][1] issue w/sphinx >=`v6.1.3`
    - Tested w/sphinx `v7.0.1`
    - Summary:
      - FTBFS with sphinx >=6.1.3 when generating HTML docs (the default).
        Upstream says it's a known issue, requiring backport of patches and
        supposedly fixed in 9.6.1, but testing reveals it still fails w/sphinx v7.0.1
        
        History of this formula applied patch for ghc 9.4.4, sphinx-doc 6+, but this
        still failed to build with or without that patch.
        Homebrew maintainer removed this patch in 23262c32bc3 PR #136863
        
        Suggest that we disable HTML doc generation to avoid this & future FTBFS issues.

        Upstream issues:

        - https://gitlab.haskell.org/ghc/ghc/-/issues/23286
        - https://gitlab.haskell.org/ghc/ghc/-/issues/23477
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

[1]: https://en.wiktionary.org/wiki/FTBFS

### CODE REVIEW

**Comment by trinitronx** [comment]
CI Matrix for `macOS 11-arm64` passed, but rest failed with:

     Error: The operation was canceled.

Then, post-build steps failed to upload logs (probably network congestion or other problem on GitHub's side).

@branchvincent: This probably needs `CI-long-timeout` label, as it's a long build.

**Comment by chenrui333** [comment]
rerun

**Comment by trinitronx** [comment]
Thanks @chenrui333!  Looks like the CI pipeline got further this time, so now we see some more errors during formula test phase:

- [ ] `Linux`: `/bin/sh: 1: xz: not found`
  - Seems simple... missing build dep: `xz`
- [ ] `macOS*`: 2 dependent formula tests failed:
  - [ ] `haskell-language-server`: Somehow it's missing the binary:

         sh: /usr/local/Cellar/haskell-language-server/2.0.0.1/bin/haskell-language-server-9.6: No such file or directory
        Error: haskell-language-server: failed

  - [ ] `bnfc`: Not sure about this one... I'm not a Haskell user/developer (just need `ghc` as dependency of `shellcheck`) :shrug: 
    - First error looks like a stacktrace from Homebrew / Ruby... it wasn't expecting `nil` for a block:

          [19 of 20] Compiling MAlonzo.Code.Calc.Main ( /private/tmp/agda-test-20230722-13438-85ypkg/MAlonzo/Code/Calc/Main.hs, /private/tmp/agda-test-20230722-13438-85ypkg/MAlonzo/Code/Calc/Main.o )
          [20 of 20] Linking /private/tmp/agda-test-20230722-13438-85ypkg/Main
          ==> ./Calc/Test /private/tmp/bnfc-test-20230722-13438-bjzz3z/test.calc
          ==> ./Main /private/tmp/bnfc-test-20230722-13438-bjzz3z/test.calc
          Error: bnfc: failed
          An exception occurred within a child process:
            TypeError: Block parameter 'block': Expected type T.proc.params().returns(T.untyped), got type NilClass
          Caller: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bnfc.rb:146
          Definition: /usr/local/Homebrew/Library/Homebrew/extend/ENV/std.rb:94
          /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
          /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
          /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'

    - It's not clear what the actual failure is, but truncated output has the following:


      - <details><summary><b>EXPAND</b> Truncated <code>test bnfc</code> output</summary><p>

            
              Error: Compiling Calc.Main in /private/tmp/agda-test-20230722-11708-dm4oa2/Calc/Main.agdai to /private/tmp/agda-test-20230722-11708-dm4oa2/MAlonzo/Code/Calc/Main.hs
              Calling: ghc -O -o /private/tmp/agda-test-20230722-11708-dm4oa2/Main -Werror -Wwarn -i/private/tmp/agda-test-20230722-11708-dm4oa2 -main-is MAlonzo.Code.Calc.Main /private/tmp/agda-test-20230722-11708-dm4oa2/MAlonzo/Code/Calc/Main.hs --make -fwarn-incomplete-patterns
              [3 of 7] Compiling Calc.Par         ( Calc/Par.hs, Calc/Par.o )
              [4 of 7] Compiling Calc.Print       ( Calc/Print.hs, Calc/Print.o )
              [5 of 7] Compiling Calc.Skel        ( Calc/Skel.hs, Calc/Skel.o )
              [ 1 of 20] Compiling Calc.Abs         ( Calc/Abs.hs, Calc/Abs.o ) [Optimisation flags changed]
              [6 of 7] Compiling Main             ( Calc/Test.hs, Calc/Test.o )
              [7 of 7] Linking Calc/Test
              [ 2 of 20] Compiling Calc.ErrM        ( Calc/ErrM.hs, Calc/ErrM.o )
              [ 3 of 20] Compiling Calc.Lex         ( Calc/Lex.hs, Calc/Lex.o ) [Optimisation flags changed]
              [ 4 of 20] Compiling Calc.Par         ( Calc/Par.hs, Calc/Par.o ) [Optimisation flags changed]
              [ 5 of 20] Compiling Calc.Print       ( Calc/Print.hs, Calc/Print.o ) [Optimisation flags changed]
              [ 6 of 20] Compiling MAlonzo.RTE      ( MAlonzo/RTE.hs, MAlonzo/RTE.o )
              [ 7 of 20] Compiling MAlonzo.Code.Agda.Primitive ( MAlonzo/Code/Agda/Primitive.hs, MAlonzo/Code/Agda/Primitive.o )
              [ 8 of 20] Compiling MAlonzo.Code.Agda.Builtin.Unit ( MAlonzo/Code/Agda/Builtin/Unit.hs, MAlonzo/Code/Agda/Builtin/Unit.o )
              [ 9 of 20] Compiling MAlonzo.Code.Agda.Builtin.String ( MAlonzo/Code/Agda/Builtin/String.hs, MAlonzo/Code/Agda/Builtin/String.o )
              [10 of 20] Compiling MAlonzo.Code.Agda.Builtin.Nat ( MAlonzo/Code/Agda/Builtin/Nat.hs, MAlonzo/Code/Agda/Builtin/Nat.o )
              [11 of 20] Compiling MAlonzo.Code.Agda.Builtin.Maybe ( MAlonzo/Code/Agda/Builtin/Maybe.hs, MAlonzo/Code/Agda/Builtin/Maybe.o )
              [12 of 20] Compiling MAlonzo.Code.Agda.Builtin.List ( MAlonzo/Code/Agda/Builtin/List.hs, MAlonzo/Code/Agda/Builtin/List.o )
              [13 of 20] Compiling MAlonzo.Code.Agda.Builtin.Int ( MAlonzo/Code/Agda/Builtin/Int.hs, MAlonzo/Code/Agda/Builtin/Int.o )
              [14 of 20] Compiling MAlonzo.Code.Calc.AST ( MAlonzo/Code/Calc/AST.hs, MAlonzo/Code/Calc/AST.o )
              [15 of 20] Compiling MAlonzo.Code.Agda.Builtin.IO ( MAlonzo/Code/Agda/Builtin/IO.hs, MAlonzo/Code/Agda/Builtin/IO.o )
              [16 of 20] Compiling MAlonzo.Code.Calc.IOLib ( MAlonzo/Code/Calc/IOLib.hs, MAlonzo/Code/Calc/IOLib.o )
              [17 of 20] Compiling MAlonzo.Code.Agda.Builtin.Char ( MAlonzo/Code/Agda/Builtin/Char.hs, MAlonzo/Code/Agda/Builtin/Char.o )
              [18 of 20] Compiling MAlonzo.Code.Calc.Parser ( MAlonzo/Code/Calc/Parser.hs, MAlonzo/Code/Calc/Parser.o )
              [19 of 20] Compiling MAlonzo.Code.Calc.Main ( /private/tmp/agda-test-20230722-11708-dm4oa2/MAlonzo/Code/Calc/Main.hs, /private/tmp/agda-test-20230722-11708-dm4oa2/MAlonzo/Code/Calc/Main.o )
              [20 of 20] Linking /private/tmp/agda-test-20230722-11708-dm4oa2/Main
              ==> ./Calc/Test /private/tmp/bnfc-test-20230722-11708-1qznro4/test.calc
              ==> ./Main /private/tmp/bnfc-test-20230722-11708-1qznro4/test.calc
              ==> Testing bnfc (again)
              ==> cabal v2-update
              Config file path source is default config file.
              Config file not found:
              /private/tmp/bnfc-test-20230722-13438-bjzz3z/.cabal/config
              Writing default configuration to
              /private/tmp/bnfc-test-20230722-13438-bjzz3z/.cabal/config
              Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.8.1.0 supports
              'ghc' version < 9.6): /usr/local/bin/ghc is version 9.6.2
              Downloading the latest package list from hackage.haskell.org
              Package list of hackage.haskell.org has been updated.
              The index-state is set to 2023-07-21T23:50:30Z.
              ==> cabal v2-install --jobs=6 --max-backjumps=100000 --install-method=copy --installdir=/private/tmp/bnfc-test-20230722-13438-bjzz3z/tools-bin alex happy
              Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.8.1.0 supports
              'ghc' version < 9.6): /usr/local/bin/ghc is version 9.6.2
              Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.8.1.0 supports
              'ghc' version < 9.6): /usr/local/bin/ghc is version 9.6.2
              Resolving depend
            ==> brew uninstall --force bnfc
            ==> brew install --only-dependencies cabal-install
            ==> brew linkage --test cabal-install
            ==> brew linkage --cached --test --strict cabal-install
            ==> brew install --only-dependencies --include-test cabal-install
            ==> brew test --retry --verbose cabal-install
            ==> brew uninstall --force cabal-install
            ==> brew fetch --retry haskell-language-server
            ==> brew install --only-dependencies haskell-language-server
            ==> brew install haskell-language-server
            ==> brew install --only-dependencies haskell-language-server
            ==> brew linkage --test haskell-language-server
            ==> brew linkage --cached --test --strict haskell-language-server
            ==> brew install --only-dependencies --include-test haskell-language-server
            ==> brew test --retry --verbose haskell-language-server
            ==> FAILED
  </p>
  </details>

    - Seems like `ERROR: ` prefix in `bnfc` tests may be coming from `brew test-bot` rather than an actual compilation failure of `MAlonzo.Code.Calc.Main` because the following output seems to continue onwards.
        - May be an issue with `bnfc` Formula, or actually failure from (possibly) parallel-running `brew test --retry --verbose haskell-language-server`?
        - Not sure if it's related to bumping `ghc`... :shrug:

**Comment by trinitronx** [comment]
Looks like I spoke too soon... Just realized `CI-no-fail-fast` was set, so 2 errors were hidden up above in CI output too:

- [ ] `agda`: Needs bump & relink against `ghc-9.6.2`:

  - <details><summary><b>EXPAND</b> Full <code>linkage --test agda</code> output</summary><p>

        Full linkage --test agda output
          Broken dependencies:
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSarray-0.5.4.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSbase-4.17.0.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSbinary-0.8.9.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSbytestring-0.11.3.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHScontainers-0.6.6-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSdeepseq-1.4.8.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSdirectory-1.3.7.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSexceptions-0.10.5-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSfilepath-1.4.2.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSghc-bignum-1.3-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSghc-prim-0.9.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHShaskeline-0.8.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSmtl-2.2.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSparsec-3.1.15.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSpretty-1.1.3.6-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSprocess-1.6.16.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSstm-2.5.1.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStemplate-haskell-2.19.0.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStext-2.0.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStime-1.12.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStransformers-0.5.6.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSunix-2.7.3-ghc9.4.4.dylib (ghc)


  </p></details>
- [ ] `allureofthestars`: Same as above... needs bump & relink against `ghc-9.6.2`:
  - <details><summary><b>EXPAND</b> Full <code>linkage --test allureofthestars</code> output</summary>

        Full linkage --test allureofthestars output
          Broken dependencies:
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSarray-0.5.4.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSbase-4.17.0.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSbinary-0.8.9.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSbytestring-0.11.3.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHScontainers-0.6.6-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSdirectory-1.3.7.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSexceptions-0.10.5-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSfilepath-1.4.2.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSghc-bignum-1.3-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSghc-prim-0.9.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSmtl-2.2.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSparsec-3.1.15.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSpretty-1.1.3.6-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSprocess-1.6.16.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSstm-2.5.1.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStemplate-haskell-2.19.0.0-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStext-2.0.1-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStime-1.12.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHStransformers-0.5.6.2-ghc9.4.4.dylib (ghc)
            /usr/local/opt/ghc/lib/ghc-9.4.4/lib/x86_64-osx-ghc-9.4.4/libHSunix-2.7.3-ghc9.4.4.dylib (ghc)

  </p></details>

**Comment by trinitronx** [comment]
Please add label: `help wanted`

**Comment by cho-m** [comment]
This will need to be tested with `CI-build-dependents-from-source`. Auto-labelling does work that well when alias is also modified:
https://github.com/Homebrew/homebrew-core/blob/aaacfc6152494213df2b796866989d067942c42c/.github/workflows/triage.yml#L203-L204

---

Note that new GHC versions are often slow to adopt. For example, Stack only added nightly support last month (https://www.stackage.org/blog/2023/06/announce-lts-21-nightly-ghc9.6)

Many formulae that use `haskell-stack` won't built and a bunch of formulae have `base`/etc. upper bounds as constraints that will prevent building with GHC 9.6. These need to be identified and will require either backporting fixes or downgrading GHC version.

---

Example for work needed in last migrations:

### GHC 8.10 -> 9.2
- #110086 #110460 #110461 #110460 #110470 #110481 #110483 #110484 #110485 #110493 #110492 #110480 #110507 #110494 #105842

### GHC 9.2 -> 9.4
- #110865 #117690 #117689 #117680 #117691 #117692 #117693 #117694 #117695 #117681 #117696 #117683 #117698 #117685 #117686 #117688 #117687

**Comment by trinitronx** [comment]
> This will need to be tested with `CI-build-dependents-from-source`. Auto-labelling does work that well when alias is also modified:
> https://github.com/Homebrew/homebrew-core/blob/aaacfc6152494213df2b796866989d067942c42c/.github/workflows/triage.yml#L203-L204

Thank you for the helpful explanation.  I didn't know about the `CI-build-dependents-from-source` label yet.  I did see that workflow file for the `long build` label patterns, and also the [GitHub Actions task here][1].  It seems to check that all PR modified files must match constraints:

```js
// Only consider labelling when all PR files match a constraint
for (const constraintAndMatchingFiles of constraintToMatchingFiles) {
    const constraint = constraintAndMatchingFiles[0]
    const matchingFiles = constraintAndMatchingFiles[1]

    if (matchingFiles.length == files.data.length) {
        continue
    }

    constraintToMatchingFiles.delete(constraint)
}
```

It looks like it was not labeling due to the renamed file: `Aliases/ghc@9.4 -> Aliases/ghc@9.6`, which was not added to the list of constraints.  It's likely that only `Formulas/ghc.rb` would match the RegEx.


> Note that new GHC versions are often slow to adopt. For example, Stack only added nightly support last month (https://www.stackage.org/blog/2023/06/announce-lts-21-nightly-ghc9.6)

Noted!  I was a bit over optimistic when I saw @branchvincent's PR: #136863
I did expect that since `ghc` is the Haskell compiler that it would have a lot of dependents, but didn't think that there would be so many instances of FTBFS on those too given that it's not a major release bump like `8.x -> 9.x`.

> Example for work needed in last migrations:
> [...SNIP...]

It looks like this could involve a lot of coordination for the dependent formulae.  Happy to help where I can, but like I said I'm not a Haskell developer.

[1]: https://github.com/Homebrew/actions/blob/master/label-pull-requests/main.js#L130

**Pull request closed without merging**
