### PR TITLE
navi 0.8.1 (new formula)

### PR DESCRIPTION
**Pull request by denisidoro**
Related: https://github.com/denisidoro/navi

### CODE REVIEW

**Comment by denisidoro** [comment]
I've run `HOMEBREW_DEVELOPER=true brew audit --new-formula navi` to test the formula but I get no result. Am I doing something wrong?

**Comment by aaronliu0130** [comment]
Oh, snap! I was going to contribute that! (No offense)

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by SMillerDev** [comment]
>I've run `HOMEBREW_DEVELOPER=true brew audit --new-formula navi` to test the formula but I get no result. Am I doing something wrong?

@denisidoro there's no need to set the developer variable. But if nothing is wrong nothing will be reported.

**Pull request closed without merging**
