### PR TITLE
gcc 11.1.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
We maybe want to merge some of the 10.3.0 fixes into the ARM64 branch.

**Comment by fxcoudert** [comment]
- Also need to be updated: `libgccjit` (in the same PR), `i686-elf-gcc mingw-w64 x86_64-elf-gcc` (can be in separate PRs to make things easier).
- Work is ongoing on a patch for ARM rebased on 10.3.0, will post it as soon as it's done (a couple of days).

**Comment by fxcoudert** [comment]
Added the ARM backport, let's see how it goes.

**Comment by carlocab** [comment]
```
make[3]: *** No rule to make target `libgcc_ext.10.4.dylib', needed by `all'.  Stop.
```

**Comment by fxcoudert** [comment]
GCC 11.1 is released, so let's focus on that for now

**Comment by carlocab** [comment]
How exciting. Will update this.

**Comment by carlocab** [comment]
Extra GCC formulae updated in #76039.

**Comment by carlocab** [comment]
No ARM support yet 😞
```
*** Configuration aarch64-apple-darwin20 not supported
```

**Comment by cielavenir** [comment]
@carlocab Thank you for working on this. It seems they added macOS support finally. So would you mind adding these lines?

```
diff --git a/Formula/gcc.rb b/Formula/gcc.rb
index 4da0d09d1c..d3856bbbd3 100644
--- a/Formula/gcc.rb
+++ b/Formula/gcc.rb
@@ -59,7 +59,7 @@ class Gcc < Formula
     #  - Ada, which requires a pre-existing GCC Ada compiler to bootstrap
     #  - Go, currently not supported on macOS
     #  - BRIG
-    languages = %w[c c++ objc obj-c++ fortran]
+    languages = %w[c c++ objc obj-c++ d fortran]
 
     pkgversion = "Homebrew GCC #{pkg_version} #{build.used_options*" "}".strip
     cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
@@ -70,6 +70,7 @@ class Gcc < Formula
       --disable-nls
       --enable-checking=release
       --enable-languages=#{languages.join(",")}
+      --enable-libphobos
       --program-suffix=-#{version_suffix}
       --with-gmp=#{Formula["gmp"].opt_prefix}
       --with-mpfr=#{Formula["mpfr"].opt_prefix}
@@ -108,6 +109,7 @@ class Gcc < Formula
       system "make", "install"
 
       bin.install_symlink bin/"gfortran-#{version_suffix}" => "gfortran"
+      bin.install_symlink bin/"gdc-#{version_suffix}" => "gdc"
     end
 
     # Handle conflicts between GCC formulae and avoid interfering
@@ -165,5 +167,16 @@ class Gcc < Formula
     EOS
     system "#{bin}/gfortran", "-o", "test", "test.f90"
     assert_equal "Done\n", `./test`
+
+    (testpath/"hello_d.d").write <<~EOS
+      import std.stdio;
+      int main()
+      {
+        writeln("Hello, world!");
+        return 0;
+      }
+    EOS
+    system "#{bin}/gdc-#{version_suffix}", "-o", "hello-d", "hello_d.d"
+    assert_equal "Hello, world!\n", `./hello-d`
   end
 end

```

**Comment by carlocab** [comment]
Thanks for the update on this, @cielavenir! Given the work that needs to go into this PR to get it merged (see CI log), I'd suggest that we limit the changes we make to `gcc` to the minimum required to merge it for this PR.

When this is merged, we can then open a separate PR to add support for `gdc`.

**Comment by carlocab** [comment]
Big Sur:

<details><summary>Error: 119 failed steps!</summary>
<p>

```
Error: 119 failed steps!
brew linkage --test abyss
brew test --retry --verbose abyss
brew linkage --test adios2
brew test --retry --verbose adios2
brew test --retry --verbose arcade-learning-environment
brew test --retry --verbose armadillo
brew linkage --test arpack
brew test --retry --verbose arpack
brew test --retry --verbose arrayfire
brew test --retry --verbose astrometry-net
brew test --retry --verbose aubio
brew linkage --test augustus
brew test --retry --verbose augustus
brew test --retry --verbose biosig
brew test --retry --verbose bzt
brew test --retry --verbose caffe
brew test --retry --verbose cbc
brew test --retry --verbose ceres-solver
brew test --retry --verbose cgl
brew linkage --test cgns
brew test --retry --verbose cgns
brew test --retry --verbose clp
brew test --retry --verbose coinutils
brew linkage --test cp2k
brew test --retry --verbose cp2k
brew test --retry --verbose csound
brew test --retry --verbose dlib
brew linkage --test dungeon
brew test --retry --verbose dungeon
brew linkage --test dynare
brew test --retry --verbose dynare
brew linkage --test eccodes
brew test --retry --verbose faiss
brew linkage --test fastme
brew test --retry --verbose fastme
brew linkage --test fftw
brew test --retry --verbose fftw
brew linkage --test giza
brew test --retry --verbose giza
brew test --retry --verbose gmt
brew test --retry --verbose gmt@5
brew test --retry --verbose gnuradio
brew test --retry --verbose graph-tool
brew linkage --test gromacs
brew test --retry --verbose gromacs
brew linkage --test hdf5
brew linkage --test hdf5-mpi
brew test --retry --verbose hdf5-mpi
brew linkage --test hdf5@1.10
brew linkage --test hdf5@1.8
brew test --retry --verbose igraph
brew test --retry --verbose imake
brew linkage --test ipopt
brew test --retry --verbose ipopt
brew linkage --test json-fortran
brew test --retry --verbose json-fortran
brew linkage --test kahip
brew test --retry --verbose kahip
brew test --retry --verbose khiva
brew linkage --test kim-api
brew test --retry --verbose kim-api
brew test --retry --verbose lammps
brew linkage --test lapack
brew test --retry --verbose lapack
brew test --retry --verbose libbi
brew linkage --test libxc
brew test --retry --verbose matplotplusplus
brew test --retry --verbose minizinc
brew test --retry --verbose mlpack
brew install mpich
brew linkage --test netcdf
brew test --retry --verbose netcdf
brew test --retry --verbose networkit
brew test --retry --verbose numpy
brew test --retry --verbose numpy@1.16
brew linkage --test nwchem
brew test --retry --verbose nwchem
brew linkage --test octave
brew test --retry --verbose octave
brew linkage --test open-mpi
brew test --retry --verbose open-mpi
brew linkage --test openblas
brew test --retry --verbose openblas
brew test --retry --verbose opencoarrays
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
brew linkage --test openfast
brew test --retry --verbose openfast
brew linkage --test openkim-models
brew test --retry --verbose openkim-models
brew linkage --test openmodelica
brew test --retry --verbose openmodelica
brew test --retry --verbose or-tools
brew test --retry --verbose osi
brew linkage --test packmol
brew test --retry --verbose packmol
brew linkage --test petsc
brew test --retry --verbose petsc
brew linkage --test petsc-complex
brew test --retry --verbose petsc-complex
brew linkage --test plplot
brew linkage --test pnetcdf
brew test --retry --verbose pnetcdf
brew test --retry --verbose proteinortho
brew linkage --test qrupdate
brew test --retry --verbose qrupdate
brew linkage --test r
brew test --retry --verbose r
brew test --retry --verbose reprepro
brew linkage --test root
brew linkage --test scalapack
brew linkage --test scipy
brew test --retry --verbose scipy
brew test --retry --verbose shogun
brew test --retry --verbose shtools
brew test --retry --verbose siril
brew test --retry --verbose superlu
brew test --retry --verbose urh
brew test --retry --verbose xdot
```

</p>
</details>

Catalina:

<details><summary>Error: 120 failed steps!</summary>
<p>

```
Error: 120 failed steps!
brew linkage --test abyss
brew test --retry --verbose abyss
brew linkage --test adios2
brew test --retry --verbose adios2
brew test --retry --verbose arcade-learning-environment
brew test --retry --verbose armadillo
brew linkage --test arpack
brew test --retry --verbose arpack
brew test --retry --verbose arrayfire
brew test --retry --verbose astrometry-net
brew test --retry --verbose aubio
brew linkage --test augustus
brew test --retry --verbose augustus
brew test --retry --verbose biosig
brew test --retry --verbose bzt
brew test --retry --verbose caffe
brew test --retry --verbose cbc
brew test --retry --verbose ceres-solver
brew test --retry --verbose cgl
brew linkage --test cgns
brew test --retry --verbose cgns
brew test --retry --verbose clp
brew test --retry --verbose coinutils
brew linkage --test cp2k
brew test --retry --verbose cp2k
brew test --retry --verbose csound
brew test --retry --verbose dlib
brew linkage --test dungeon
brew test --retry --verbose dungeon
brew linkage --test dynare
brew test --retry --verbose dynare
brew linkage --test eccodes
brew test --retry --verbose faiss
brew linkage --test fastme
brew test --retry --verbose fastme
brew linkage --test fftw
brew test --retry --verbose fftw
brew linkage --test giza
brew test --retry --verbose giza
brew test --retry --verbose gmt
brew test --retry --verbose gmt@5
brew test --retry --verbose gnuradio
brew test --retry --verbose graph-tool
brew linkage --test gromacs
brew test --retry --verbose gromacs
brew linkage --test hdf5
brew linkage --test hdf5-mpi
brew test --retry --verbose hdf5-mpi
brew linkage --test hdf5@1.10
brew linkage --test hdf5@1.8
brew test --retry --verbose igraph
brew test --retry --verbose imake
brew linkage --test ipopt
brew test --retry --verbose ipopt
brew linkage --test json-fortran
brew test --retry --verbose json-fortran
brew linkage --test kahip
brew test --retry --verbose kahip
brew test --retry --verbose khiva
brew linkage --test kim-api
brew test --retry --verbose kim-api
brew test --retry --verbose lammps
brew linkage --test lapack
brew test --retry --verbose lapack
brew test --retry --verbose libbi
brew linkage --test libxc
brew test --retry --verbose matplotplusplus
brew test --retry --verbose minizinc
brew test --retry --verbose mlpack
brew install mpich
brew linkage --test netcdf
brew test --retry --verbose netcdf
brew test --retry --verbose networkit
brew test --retry --verbose numpy
brew test --retry --verbose numpy@1.16
brew linkage --test nwchem
brew test --retry --verbose nwchem
brew linkage --test octave
brew test --retry --verbose octave
brew linkage --test open-mpi
brew test --retry --verbose open-mpi
brew linkage --test openblas
brew test --retry --verbose openblas
brew test --retry --verbose opencoarrays
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
brew linkage --test openfast
brew test --retry --verbose openfast
brew linkage --test openkim-models
brew test --retry --verbose openkim-models
brew linkage --test openmodelica
brew test --retry --verbose openmodelica
brew test --retry --verbose or-tools
brew test --retry --verbose osi
brew linkage --test packmol
brew test --retry --verbose packmol
brew linkage --test petsc
brew test --retry --verbose petsc
brew linkage --test petsc-complex
brew test --retry --verbose petsc-complex
brew linkage --test plplot
brew linkage --test pnetcdf
brew test --retry --verbose pnetcdf
brew test --retry --verbose proteinortho
brew linkage --test qrupdate
brew test --retry --verbose qrupdate
brew linkage --test r
brew test --retry --verbose r
brew linkage --test reprepro
brew test --retry --verbose reprepro
brew linkage --test root
brew linkage --test scalapack
brew linkage --test scipy
brew test --retry --verbose scipy
brew test --retry --verbose shogun
brew test --retry --verbose shtools
brew test --retry --verbose siril
brew test --retry --verbose superlu
brew test --retry --verbose urh
brew test --retry --verbose xdot
```

</p>
</details>

Mojave:

<details><summary>Error: 124 failed steps!</summary>
<p>

```
Error: 124 failed steps!
brew linkage --test abyss
brew test --retry --verbose abyss
brew linkage --test adios2
brew test --retry --verbose adios2
brew test --retry --verbose arcade-learning-environment
brew test --retry --verbose armadillo
brew linkage --test arpack
brew test --retry --verbose arpack
brew test --retry --verbose arrayfire
brew test --retry --verbose astrometry-net
brew test --retry --verbose aubio
brew linkage --test augustus
brew test --retry --verbose augustus
brew test --retry --verbose biosig
brew test --retry --verbose bzt
brew test --retry --verbose caffe
brew test --retry --verbose cbc
brew test --retry --verbose ceres-solver
brew test --retry --verbose cgl
brew linkage --test cgns
brew test --retry --verbose cgns
brew test --retry --verbose clp
brew test --retry --verbose coinutils
brew linkage --test cp2k
brew test --retry --verbose cp2k
brew test --retry --verbose csound
brew test --retry --verbose dlib
brew linkage --test dungeon
brew test --retry --verbose dungeon
brew linkage --test dynare
brew test --retry --verbose dynare
brew linkage --test eccodes
brew test --retry --verbose faiss
brew linkage --test fastme
brew test --retry --verbose fastme
brew linkage --test fftw
brew test --retry --verbose fftw
brew linkage --test giza
brew test --retry --verbose giza
brew test --retry --verbose gmt
brew test --retry --verbose gmt@5
brew test --retry --verbose gnuradio
brew test --retry --verbose graph-tool
brew linkage --test gromacs
brew test --retry --verbose gromacs
brew linkage --test hdf5
brew linkage --test hdf5-mpi
brew test --retry --verbose hdf5-mpi
brew linkage --test hdf5@1.10
brew linkage --test hdf5@1.8
brew test --retry --verbose igraph
brew test --retry --verbose imake
brew linkage --test ipopt
brew test --retry --verbose ipopt
brew linkage --test json-fortran
brew test --retry --verbose json-fortran
brew linkage --test kahip
brew test --retry --verbose kahip
brew test --retry --verbose khiva
brew linkage --test kim-api
brew test --retry --verbose kim-api
brew test --retry --verbose lammps
brew linkage --test lapack
brew test --retry --verbose lapack
brew test --retry --verbose libbi
brew linkage --test libxc
brew linkage --test matplotplusplus
brew test --retry --verbose matplotplusplus
brew test --retry --verbose minizinc
brew test --retry --verbose mlpack
brew install mpich
brew linkage --test netcdf
brew test --retry --verbose netcdf
brew test --retry --verbose networkit
brew test --retry --verbose numpy
brew test --retry --verbose numpy@1.16
brew linkage --test nwchem
brew test --retry --verbose nwchem
brew linkage --test octave
brew test --retry --verbose octave
brew linkage --test open-mpi
brew test --retry --verbose open-mpi
brew linkage --test openblas
brew test --retry --verbose openblas
brew test --retry --verbose opencoarrays
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
brew linkage --test openfast
brew test --retry --verbose openfast
brew linkage --test openkim-models
brew test --retry --verbose openkim-models
brew linkage --test openmodelica
brew test --retry --verbose openmodelica
brew test --retry --verbose or-tools
brew test --retry --verbose osi
brew linkage --test packmol
brew test --retry --verbose packmol
brew test --retry --verbose pegtl
brew linkage --test petsc
brew test --retry --verbose petsc
brew linkage --test petsc-complex
brew test --retry --verbose petsc-complex
brew linkage --test plplot
brew linkage --test pnetcdf
brew test --retry --verbose pnetcdf
brew test --retry --verbose proteinortho
brew linkage --test qrupdate
brew test --retry --verbose qrupdate
brew linkage --test r
brew test --retry --verbose r
brew linkage --test reprepro
brew test --retry --verbose reprepro
brew linkage --test root
brew linkage --test scalapack
brew linkage --test scipy
brew test --retry --verbose scipy
brew test --retry --verbose shogun
brew test --retry --verbose shtools
brew test --retry --verbose siril
brew test --retry --verbose superlu
brew test --retry --verbose urh
brew linkage --test vcpkg
brew test --retry --verbose vcpkg
brew test --retry --verbose xdot
```

</p>
</details>

Going to rev bump the linkage failures.

**Comment by carlocab** [comment]
Linkage failures:
```
abyss
adios2
arpack
augustus
cgns
cp2k
dungeon
dynare
eccodes
fastme
fftw
giza
gromacs
hdf5
hdf5-mpi
hdf5@1.10
hdf5@1.8
ipopt
json-fortran
kahip
kim-api
lapack
libxc
matplotplusplus
netcdf
nwchem
octave
open-mpi
openblas
openfast
openkim-models
openmodelica
packmol
petsc
petsc-complex
plplot
pnetcdf
qrupdate
r
reprepro
root
scalapack
scipy
vcpkg
```

**Comment by carlocab** [comment]
Looking forward to all the opportunistic linkage.

@fxcoudert, any updates on the ARM build? No rush, just wanted to check in if you knew anything about it. I tried to look in https://github.com/iains/gcc-darwin-arm64 but I'll admit to having no idea about what's going on there. 😅

**Comment by carlocab** [comment]
```
Error: pegtl: failed
An exception occurred within a child process:
  NoMethodError: undefined method `gcc-11_build_version' for DevelopmentTools:Class
```
https://github.com/Homebrew/homebrew-core/pull/74843/checks?check_run_id=2483469805#step:7:205

Needs to be fixed in `brew`.

**Comment by carlocab** [comment]
Homebrew/brew#11299 has been merged, but this PR will need to wait for at least the next `brew` release tag to merge. (Not that I expect this to be done before then.)

**Comment by carlocab** [comment]
All three Intel nodes:

```
Error: 16 failed steps!
brew test --retry --verbose imake
brew linkage --test mpich
brew test --retry --verbose mpich
brew test --retry --verbose flann
brew test --retry --verbose armadillo
brew test --retry --verbose ensmallen
brew test --retry --verbose mlpack
brew audit abyss --online --git --skip-style
brew audit fastme --online --git --skip-style
brew test --verbose giza
brew install --verbose --build-bottle gromacs
brew install --verbose --build-bottle openfast
brew link hdf5
brew install --verbose --build-bottle openmodelica
brew link hdf5
brew link hdf5
```

The `brew link hdf5` failures are from `hdf5-mpi` still being linked when test-bot attempts to do `brew link`. Should probably be fixed in `test-bot`.

**Comment by carlocab** [comment]
Might need rebasing when #73062 is merged. Though I'd want to resolve at least some of the other failures before trying again.

**Comment by Bo98** [comment]
> Should probably be fixed in `test-bot`.

It should be fixed by adding a `conflicts_with`.

---

`imake` and `mpich` require a revision bump.

`armadillo` does too because `hdf5` has been revision bumped, but it should be fixed to not rely on the Cellar path.

`giza` needs a fix to the `gcc` binary invoked in the test.

**Comment by carlocab** [comment]
> > Should probably be fixed in `test-bot`.
> 
> It should be fixed by adding a `conflicts_with`.

Huh, I thought `hdf5` already had that. It seems only `hdf5-mpi` does.

**Comment by carlocab** [comment]
All Intel nodes:
```
Error: 8 failed steps!
brew test --retry --verbose flann
brew audit abyss --online --git --skip-style
brew install --verbose --build-bottle gromacs
brew fetch --retry mlpack --build-bottle --force
brew install --verbose --build-bottle mlpack
brew audit mlpack --online --git --skip-style
brew install --verbose --build-bottle openfast
brew install --verbose --build-bottle openmodelica
```

Plus an extra (but spurious) test failure for `caffe` on Mojave.

**Comment by fxcoudert** [comment]
I'm hoping to find time for an ARM backport this week.

**Comment by fxcoudert** [comment]
I've tried a backport at https://github.com/fxcoudert/gcc/tree/gcc-11.1.0-arm, let's see how it goes

**Comment by carlocab** [comment]
It worked! ARM runner its testing deps now 🎉

**Comment by fxcoudert** [comment]
Hum… ARM status is not excellent:

```
brew livecheck gcc --full-name --debug
brew linkage --test open-mpi
brew test --retry --verbose open-mpi
brew test --retry --verbose opencoarrays
brew install --verbose --build-bottle openblas
brew test --retry --verbose flann
brew install --only-dependencies urh
brew install urh
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle arpack
brew install --verbose --build-bottle arpack
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle scalapack
brew install --verbose --build-bottle scalapack
brew install --verbose --build-bottle netcdf
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle qrupdate
brew install --verbose --build-bottle qrupdate
brew install --build-from-source arpack openblas
brew install --only-dependencies --verbose --build-bottle armadillo
brew install --verbose --build-bottle armadillo
brew audit armadillo --online --git --skip-style
brew install --build-from-source arpack openblas qrupdate
brew install --only-dependencies --verbose --build-bottle octave
brew install --verbose --build-bottle octave
brew install --build-from-source armadillo arpack openblas
brew install --only-dependencies --verbose --build-bottle ensmallen
brew install --verbose --build-bottle ensmallen
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle adios2
brew install --verbose --build-bottle adios2
brew install --build-from-source openblas scalapack
brew install --only-dependencies --verbose --build-bottle cp2k
brew install --verbose --build-bottle cp2k
brew install --build-from-source netcdf
brew install --only-dependencies --verbose --build-bottle eccodes
brew install --verbose --build-bottle eccodes
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle gromacs
brew install --verbose --build-bottle gromacs
brew install --verbose --build-bottle hdf5-mpi
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle ipopt
brew install --verbose --build-bottle ipopt
brew install --build-from-source armadillo arpack ensmallen openblas
brew fetch --retry mlpack --build-bottle --force
brew install --only-dependencies --verbose --build-bottle mlpack
brew install --verbose --build-bottle mlpack
brew audit mlpack --online --git --skip-style
brew install --build-from-source netcdf openblas scalapack
brew install --only-dependencies --verbose --build-bottle petsc-complex
brew install --verbose --build-bottle petsc-complex
brew install --build-from-source netcdf openblas scalapack
brew install --only-dependencies --verbose --build-bottle petsc
brew install --verbose --build-bottle petsc
brew test --verbose pnetcdf
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle r
brew install --verbose --build-bottle r
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle root
brew install --verbose --build-bottle root
brew install --build-from-source openblas
brew install --only-dependencies --verbose --build-bottle scipy
brew install --verbose --build-bottle scipy
```

**Comment by fxcoudert** [comment]
- `open-mpi` revision needs to be further bumped after fd96511a54edbdacbbb53ac90b2492deab121819
- `opencoarrays` needs a revision bump
- gcc livecheck needs to be adjusted back for ARM
- `openblas` fails with:

----

```
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -fopenmp -fPIC -march=armv8.3-a  -all_load -headerpad_max_install_names -install_name "/private/tmp/openblas-20210504-81004-e68xc6/OpenBLAS-0.3.15/exports/../libopenblas.0.dylib" -dynamiclib -o ../libopenblasp-r0.3.15.dylib ../libopenblasp-r0.3.15.a -Wl,-exported_symbols_list,osx.def  -L/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0 -L/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0/../../.. -Wl,-rpath,,loader_path -Wl,-rpath,/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0 -Wl,-rpath,/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0/../../.. -L/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0 -L/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0/../../.. -Wl,-rpath,,loader_path -Wl,-rpath,/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0 -Wl,-rpath,/opt/homebrew/Cellar/gcc/11.1.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0/../../..  -lgfortran -lgomp -lm -lSystem -lgfortran -lgomp -lm -lSystem  
ld: file not found: loader_path
```

That `-Wl,-rpath,,loader_path` is wrong, we need to find where it comes from.

**Comment by carlocab** [comment]
Thanks for looking at this, FX. Will try to fix this soon.

**Comment by fxcoudert** [comment]
I think the openblas issue is on their side, and I've asked for help there: https://github.com/xianyi/OpenBLAS/issues/3222

**Comment by carlocab** [comment]
Thanks. I was hoping the OpenBLAS version bump would help (not yet in this PR), but I didn't push it yet because I wanted to try to resolve some of the other failures first.

**Comment by fxcoudert** [comment]
@carlocab I have a patch for openblas at https://github.com/xianyi/OpenBLAS/issues/3222#issuecomment-833468521
but I can't push or create a PR for it right now. If you have time to stick it here and test it, that would be very much appreciated!

**Comment by carlocab** [comment]
Sure, I can do that. Thanks!

**Comment by carlocab** [comment]
I adopted the patch in this comment: https://github.com/xianyi/OpenBLAS/issues/3222#issuecomment-833475703

I was hoping to resolve more failures before re-running CI, but I don't quite have time at the moment, and it would be good to test the `openblas` patch and some of the revision bumps from https://github.com/Homebrew/homebrew-core/pull/74843#issuecomment-832487709.

**Comment by carlocab** [comment]
Looks like `netcdf`'s `cxx-compat` module got bitten by the `#include <version>` bug. Fixing this should fix a bunch of the other failures, I think.

**Comment by fxcoudert** [comment]
Is the netcdf failure ARM-specific? (Other than that, ARM is looking really good)

**Comment by Bo98** [comment]
It's Xcode 12.5 specific which only the ARM runner has been updated to (Intel coming this weekend).

It's not a Xcode bug though - Apple have just added some C++20 headers and of them is called "version" which conflicts with some projects,

**Comment by fxcoudert** [comment]
> Apple have just added some C++20 headers and one of them is called "version" which conflicts with some projects that have random version files lying around in the include path

Yeah I've seen that crop in other places, as well. Case-insensitivity of the filesystem also means it's pretty much an issue only on macOS/iOS, so it's not likely to get fixed fast :(

**Comment by fxcoudert** [comment]
Re. `netcdf-cxx-compat`: we've considered dropping it before, so this might be the time. It is pretty much unmaintained, having been released in 2011 (https://www.unidata.ucar.edu/software/netcdf/release-notes-cxx-4.2.html) and it was already noted at the time:

> This library is provided for backward compatibility only. New C++ development should be done with the netCDF CXX4 C++ library.

**Comment by fxcoudert** [comment]
I'm attempting a removal of `netcdf-cxx-compat` in a separate PR, to speed things up: https://github.com/Homebrew/homebrew-core/pull/76817

**Comment by carlocab** [comment]
Thanks @fxcoudert. I was contemplating looking for the errant `/version/i` file to try to rename it, but just haven't found the time yet. Removing it is fine by me too.

**Comment by fxcoudert** [comment]
The `mlpack` error is because it can't download the `stb` headers.

```
mlpack:
  * Stable resource "stb_image": The source URL https://mlpack.org/files/stb-2.22/stb_image.h is not reachable (HTTP status code 404)
  * Stable resource "stb_image_write": The source URL https://mlpack.org/files/stb-1.13/stb_image_write.h is not reachable (HTTP status code 404)
```

It's replaced by an unversioned tar file, which is not great for us: https://mlpack.org/files/stb.tar.gz

**Comment by carlocab** [comment]
Killing the test. Will rebase again when #76835 is merged.

**Comment by fxcoudert** [comment]
- `flann` and `abyss` are network/server issues
- `openfast` is a Fortran error:

```
      |                      CALL CleanUp()
      |                                   2    
......
      |             do nb=1,size(y_BD_perturb)
      |                                       1
Error: Index variable 'nb' redefined at (1) in procedure 'cleanup' called from within DO loop at (2)
```

**Comment by fxcoudert** [comment]
- `openmodelica` failure is weird:

```
==> autoconf
configure.ac:95: warning: AC_OUTPUT should be used without arguments.
configure.ac:95: You should run autoupdate.
==> ./configure --prefix=/usr/local/Cellar/openmodelica/1.16.5_1 --disable-debug --disable-modelica3d --with-cppruntime --with-hwloc --with-lapack=-lopenblas --with-omlibrary=core --with-omniORB
configure: error: cannot find required auxiliary files: config.guess config.sub
```

I have no idea why that would be compiler-dependent, really.

**Comment by Bo98** [comment]
Just needs changing to `autoreconf -i` really.

**Comment by carlocab** [comment]
> Just needs changing to `autoreconf -i` really.

#76836

**Comment by carlocab** [comment]
Nope, #76836 didn't cut it for `openmodelica`.

Tempted to disable this as `:does_not_build`: it's blocking a few PRs, and it vendors its own stuff (e.g. `ipopt`).

**Comment by carlocab** [comment]
Rebased again. Switched `openblas` to the patch at https://github.com/xianyi/OpenBLAS/pull/3223 instead.

**Comment by carlocab** [comment]
ARM test turned out pretty well:

```
Error: 4 failed steps!
brew test --retry --verbose flann
brew test --retry --verbose libbi
brew audit abyss --online --git --skip-style
brew install --verbose --build-bottle gromacs
```

**Comment by carlocab** [comment]
Intel failures:

```
Error: 4 failed steps!
brew test --retry --verbose flann
brew audit abyss --online --git --skip-style
brew install --verbose --build-bottle gromacs
brew install --verbose --build-bottle openmodelica
```

`openmodelica` should be fixed in #76836. (Admittedly not tested against the new `gcc`, though.) Not sure about `gromacs`, but that failed on ARM too.

**Comment by carlocab** [comment]
`gromacs` is pre-existing. Probably an issue with a CMake that is too new. Dropping the revision bump from this PR, as I don't know how to fix it.

**Comment by fxcoudert** [comment]
Agreed, let's merge and fix gromacs later

**Comment by carlocab** [comment]
Thanks @fxcoudert!

**Pull request closed without merging**
