### PR TITLE
git-review: vendor Python deps

### PR DESCRIPTION
**Pull request by timsutton**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Vendor Python deps in `git-review`.

### CODE REVIEW

**Review by p-linnane — CHANGES_REQUESTED** [review]
Looks like `patch :DATA` got separated from it's associated comment.

**Comment by timsutton** [comment]
@p-linnane `brew style --fix` moved it down below the `resource` blocks here: https://github.com/Homebrew/homebrew-core/pull/163270/files#diff-ad898ee95cb304ea1b885d95ea33a975e05eacc26498fc925a7ac02f4e630cc3R48

**Comment by p-linnane** [comment]
Yeah `brew style --fix` doesn't respect comments attached to things. It's a manual fix for now.

**Comment by timsutton** [comment]
D'oh, when I read 'comment' my brain just replaced it with `content`, didn't realize the comment bit. Fixing!

**Review by p-linnane — APPROVED** [review]
Thanks!

**Pull request merged**
