### PR TITLE
Fix cloog formula dependencies

### PR DESCRIPTION
**Pull request by stephengroat**
Fixing cloog dependencies from hard versions to following head(s).

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This requires changing all of the GCC reverse dependencies as well.

**Comment by stephengroat** [comment]
What gcc reverse dependencies? I don't see anything when i run `brew deps --tree gcc`?

The website current states that `cloog` should be targeting `gmp-6.0.0` or higher (http://www.bastoul.net/cloog/download.php)

**Comment by ilovezfs** [comment]
https://bot.brew.sh/job/Homebrew%20Core/14924/

**Comment by stephengroat** [comment]
I understand, just there is also an issue that `0.18.4` states a requirement of 

> GMP 6.0.0 (or any later version).

**Comment by ilovezfs** [comment]
@stephengroat it's possible those gcc's and their other dependencies could be updated to use gmp 6.

**Comment by MikeMcQuaid** [comment]
> Fixing cloog dependencies from hard versions to following head(s).

Can you elaborate what this was planned to fix?

**Comment by stephengroat** [comment]
Sure, I was trying to address #9037 which has cyclic dependencies due to the library requirement(s) of this package

**Comment by ilovezfs** [comment]
Can you elaborate on what the cyclic dependencies are there?

**Comment by stephengroat** [comment]
update to show failing tests in current configuration

**Comment by ilovezfs** [comment]
Did I miss something, or did it fail both times regardless of the versions?

**Comment by stephengroat** [comment]
worked on my box

**Comment by MikeMcQuaid** [comment]
> Can you elaborate on what the cyclic dependencies are there?

@stephengroat Still need this information.

**Comment by MikeMcQuaid** [comment]
Also, regardless, this is going to be a non-starter. The only things that currently depend on Cloog also depend on GMP@4 so we need the dependency tree as-is or it's going to break them. Regardless of whether this is preferable or not: you need to fix the formulae currently depending on `cloog` at the same time as making any adjustments like this and, if they can't live side-by-side with the mingw stuff, it can't be merged.

**Comment by MikeMcQuaid** [comment]
> Regardless of whether this is preferable or not: you need to fix the formulae currently depending on cloog at the same time as making any adjustments like this and, if they can't live side-by-side with the mingw stuff, it can't be merged.

**Pull request closed without merging**
