### PR TITLE
srt 1.5.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Previous attempt at #103688.

**Comment by cho-m** [comment]
Previous Linux error for `tsduck` revision bump:
```
/home/linuxbrew/.linuxbrew/bin/ld: /tmp/tsduck-20220615-128946-egbhki/tsduck-3.30-2710/bin/release-x86_64-d17df2b80ab0/libtsduck.so: undefined reference to `__atomic_store_16'
/home/linuxbrew/.linuxbrew/bin/ld: /tmp/tsduck-20220615-128946-egbhki/tsduck-3.30-2710/bin/release-x86_64-d17df2b80ab0/libtsduck.so: undefined reference to `__atomic_load_16'
```

Could be missing `-latomic`.

**Comment by carlocab** [comment]
Seems to be in `Makefile.inc`, though:
```
LDLIBS += -lstdc++ -lpthread $(if $(MACOS),,-lrt -latomic) -lm
```
`Makefile.inc` is included in `Makefile`.

**Comment by cho-m** [comment]
Previous PR was on v3.30-2710. `-latomic` was added in https://github.com/tsduck/tsduck/commit/c99ffdb834709e68ca0808376c967f840a0db748 and released with v3.31-2761

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
