### PR TITLE
autojump 22.3.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
@DomT4 Something is wrong with CI here. It refuses to update this tag https://github.com/BrewTestBot/homebrew-core/tree/pr-2989 regardless of rebase/push or jenkins rebuild of the upstream or downstream jobs.

**Comment by DomT4** [comment]
Seems okay now?

**Comment by ilovezfs** [comment]
yup. what was needed?

**Comment by DomT4** [comment]
Your PR was first processed when Mike updated Jenkins this morning, which temporary broke _all the build jobs_ silently. Mike fixed that fairly quickly & very thoroughly, but the ones that were triggered whilst in that state ended up kind of frozen. I whacked the Rebuild button, which worked previously to escape that frozen state.

**Comment by ilovezfs** [comment]
@DomT4 Ah OK. Thanks for fixing it!

**Pull request closed without merging**
