### PR TITLE
sysstat 12.5.4

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by Rylan12 — DISMISSED** [review]
Heads up @alebcay you've got an issue with your GPG signing.

I'm approving as this commit (and the changes to the `sysstat` source code) do still look genuine and you being a maintainer would not have affected whether I approved this PR or not.

**Comment by alebcay** [comment]
@Rylan12 Is it just this one? I signed this one the same as the other PRs in this batch. Not sure what's up with that.

**Comment by alebcay** [comment]
Force pushed and the commit is now verified.

**Review by nandahkrishna — APPROVED** [review]

**Comment by Rylan12** [comment]
Could have just been a fluke. I've seen that happen a few times.

**Pull request merged**
