### PR TITLE
Conan 0.9.4

### PR DESCRIPTION
**Pull request by lasote**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

The python dep is required always, if don't this error is raised:

```
/usr/local/Library/Formula$ conan --version
Traceback (most recent call last):
  File "/usr/local/Cellar/conan/0.0.15/libexec/bin/conan", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: setuptools>=11.3
```

OpenSSL is now needed too.

### CODE REVIEW

**Comment by DomT4** [comment]
We don't need to enforce a hard `:python` dependency to fix that; can add a `setuptools` resource like [this](https://github.com/Homebrew/homebrew-core/blob/237c5eb054962af82a6cfb03e6a39fd9407ec689/Formula/protobuf.rb#L53-L56).

**Comment by lasote** [comment]
Hi, I've tried to add setuptools and remove python dependency. Now the setuptools error is not raised but it fails when we try to download conan packages from TLS servers (I've changed the test to download OpenSSL sources and build the conan package from the official server that requires a modern security protocol). It happens when python is using an old version of OpenSSL with old protocols. What do you think?

```
OpenSSL: EOF occurred in violation of protocol (_ssl.c:590)
```

The curious thing is if I execute `brew test conan --devel --keep-tmp` all is working fine in the sandbox...

**Comment by UniqMartin** [comment]
I have honestly no idea why this is failing. Maybe @tdsmith can help …

**Comment by lasote** [comment]
Could we keep the python dependency?

**Comment by lasote** [comment]
Well, I'm closing this PR because it's stopped with no exit. I'll submit another one with the python dependency, will see if CI is ok and if you have any concern about it.

**Pull request closed without merging**
