### PR TITLE
dotnet 9.0.0

### PR DESCRIPTION
**Pull request by cho-m**
Going to start pre-release testing .NET 9 to check on state of various workarounds/patches.

TODO:
- [x] Update to .NET 9 on November 12th, 2024  - https://github.com/dotnet/core/blob/main/release-notes/9.0/README.md
- [x] Add `dotnet@8` formula - #197537
- [x] Switch `jackett` to `dotnet@8` - #197827
- [x] Switch `kiota` to `dotnet@8` - #197015
- [x] Switch `sbom-tool` to `dotnet@8` - #197883

### CODE REVIEW

**Comment by cho-m** [comment]
Noting down current status:

* macOS seems okay now at https://github.com/Homebrew/homebrew-core/commit/6ff4ee79d60bfff2847fc01a87208daaa886f168. There are annoying sporadic failures which has some upstream issues. May be fixed when newer bootstrap is available.

*Linux is building now, but test is showing some extra characters.
  ```
    ==> /home/linuxbrew/.linuxbrew/Cellar/dotnet/9.0.0/bin/dotnet run --framework net9.0 /tmp/dotnet-test-20241103-142887-5xaely/test.dll a b c
    Error: dotnet: failed
    An exception occurred within a child process:
      Minitest::Assertion: --- expected
    +++ actual
    @@ -1,2 +1,2 @@
    -"/tmp/dotnet-test-20241103-142887-5xaely/test.dll,a,b,c
    +"\e]9;4;3;\e\\\e]9;4;0;\e\\/tmp/dotnet-test-20241103-142887-5xaely/test.dll,a,b,c
     "
  ```

May try switching back to Clang build on Linux which is probably better supported.

**Comment by cho-m** [comment]
Same test failure with Clang build. Looks like ANSI codes so may need to disable some terminal detection or colorization.
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/dotnet/9.0.0/bin/dotnet run --framework net9.0 /tmp/dotnet-test-20241109-138875-37worn/test.dll a b c
  Error: dotnet: failed
  An exception occurred within a child process:
    Minitest::Assertion: --- expected
  +++ actual
  @@ -1,2 +1,2 @@
  -"/tmp/dotnet-test-20241109-138875-37worn/test.dll,a,b,c
  +"\e]9;4;3;\e\\\e]9;4;0;\e\\/tmp/dotnet-test-20241109-138875-37worn/test.dll,a,b,c
   "
```

**Comment by cho-m** [comment]
.NET 8 successfully built on non-self-hosted Linux after switching to tarball. Trying out if possible with .NET 9.

**Comment by cho-m** [comment]
Ready to merge as 14-x86_64 is an existing issue with a broken bottle. May need to be tested on Intel Sequoia to see if it is happening on all Intel macOS running Xcode 16.

**Review by stefanb — APPROVED** [review]

**Pull request merged**
