### PR TITLE
s3ql 3.3

### PR DESCRIPTION
**Pull request by bfontaine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/s3ql/3.3/libexec/bin/python3 setup.py build_ext --inplace
MANIFEST.in exists, running in developer mode
running build_ext
building 's3ql.deltadump' extension
creating build
creating build/temp.macosx-10.14-x86_64-3.7
creating build/temp.macosx-10.14-x86_64-3.7/src
creating build/temp.macosx-10.14-x86_64-3.7/src/s3ql
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/s3ql/deltadump.c -o build/temp.macosx-10.14-x86_64-3.7/src/s3ql/deltadump.o -Wall -Wextra -Wconversion -Wsign-compare -Werror -Werror=conversion -Werror=sign-compare -Wno-unused-function
clang: error: no such file or directory: 'src/s3ql/deltadump.c'
clang: error: no input files
error: command 'clang' failed with exit status 1
```

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by bfontaine** [comment]
Test fails on Catalina only:
```
==> /usr/local/Cellar/s3ql/3.3/bin/mkfs_s3ql --plain local:///private/tmp/s3ql-test-20191014-9593-elrbrh 2>&1
sh: line 1:  9609 Abort trap: 6           /usr/local/Cellar/s3ql/3.3/bin/mkfs_s3ql --plain local:///private/tmp/s3ql-test-20191014-9593-elrbrh 2>&1
Error: s3ql: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<134>.
```

**Comment by bfontaine** [comment]
I don’t have time to investigate this.

**Pull request closed without merging**
