### PR TITLE
ungit 1.5.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test step only failed on Mojave build

08:33:49 ==> brew test ungit --verbose
08:33:53 ==> FAILED
08:33:53 Testing ungit
08:33:53 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191122-78651-1mdpyhl.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb --verbose
08:33:53 Error: ungit: failed
08:33:53 An exception occurred within a child process:
08:33:53   TypeError: no implicit conversion from nil to integer

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
I think there's another error but the way the test is written makes it so we can't see it. Let's see what it is now.

**Comment by Bo98** [comment]
```
==> brew test ungit --verbose
==> FAILED
Testing ungit
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191122-60797-j1qzry.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb --verbose
Error: ungit: failed
An exception occurred within a child process:
  LoadError: cannot load such file -- nokogiri
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb:22:in `block in <class:Ungit>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1740:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1739:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:865:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1738:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1977:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1976:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1732:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:30:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:29:in `<main>'
```

**Comment by chenrui333** [comment]
Works on my catalina machine:


$ brew test --verbose ungit
Testing ungit
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191122-4133-1dcv9tj.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb --verbose
^[## Ungit started ##

Took 805ms to start server.
==> curl -s 127.0.0.1:56821/
==> ps -o pid,ppid

**Comment by Bo98** [comment]
`nokogiri` should be shipped with brew. I'm not sure why it's seen as missing.

**Comment by chenrui333** [comment]
I can see it is in there, https://github.com/Homebrew/brew/blob/master/Library/Homebrew/Gemfile.lock#L48?

**Comment by Bo98** [comment]
Ok so those are only installed on `brew audit` and `brew style` - but those should have run at least once on those machines...

Maybe it's better to avoid `nokogiri` for the tests.

Anyway, I think it's fixed so let's try it again.

@BrewTestBot test this please

**Pull request closed without merging**
