### PR TITLE
grafana 7.3.7

### PR DESCRIPTION
**Pull request by alexanderzobnin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
On ARM:
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - bin/darwin-amd64/grafana-cli
```

Maybe this

https://github.com/Homebrew/homebrew-core/blob/2cec30052e5dfb4c69d56264807f20cdf684854e/Formula/grafana.rb#L34-L37

needs to be changed on ARM?

**Comment by carlocab** [comment]
Ok, I don't know what I'm supposed to be looking for on ARM, but let's see if the change I just pushed works...

**Comment by carlocab** [comment]
Right, that worked, except I have now picked up too much:
```
==> brew audit grafana --online --git --skip-style
==> FAILED
grafana:
  * Non-executables were installed to "/opt/homebrew/opt/grafana/bin"
    The offending files are:
      /opt/homebrew/opt/grafana/bin/grafana-cli.md5
      /opt/homebrew/opt/grafana/bin/grafana-server.md5
Error: 1 problem in 1 formula detected
```

**Review by carlocab — APPROVED** [review]

**Comment by alexanderzobnin** [comment]
@carlocab is it something we can fix in Grafana? Or it's `brew bump-formula-pr` issue?

**Comment by carlocab** [comment]
It's all fixed now. Grafana has been updated. You don't need to worry about it. Thanks for following up!

**Pull request closed without merging**
