### PR TITLE
Make RSA to work with libtommath library

### PR DESCRIPTION
**Pull request by mika314**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for your contribution, however the build seems to fail because of it. Could you check if you can fix it?

**Comment by antonte** [comment]
I do not know how to fix, I assume I need to add dependency out of libtommath, but I do not know how to do it in brew, can you do it?

Thanks

**Comment by antonte** [comment]
!build

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Why use `libtommath` and not `gmp`? Or both?

**Comment by antonte** [comment]
@fxcoudert personally difference in license public domain vs GPL

**Comment by fxcoudert** [comment]
Thanks @antonte for the pull request, if there is no added feature beneficial for all users, we are going to continue shipping the formula as it is.

**Comment by antonte** [comment]
RSA does not work at all without my changes.

**Pull request closed without merging**
