### PR TITLE
operator-sdk 0.8.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by Moisan** [comment]
```
==> /usr/local/Cellar/operator-sdk/0.8.0/bin/operator-sdk new test
time="2019-05-17T22:45:15+01:00" level=info msg="Creating new Go operator 'test'."
time="2019-05-17T22:45:15+01:00" level=fatal msg="Dependency manager \"modules\" has been selected but go modules are not active. Activate modules then run \"operator-sdk new test\"."
Error: operator-sdk: failed
```

**Comment by chenrui333** [comment]
checking now.

**Comment by chenrui333** [comment]
Filed a ticket to `operator-sdk` repo

**Comment by joelanford** [comment]
@chenrui333 @Moisan I was working on a PR to add the necessary `GO111MODULE=on` in the formula test section, which worked, but I noticed that the current build from source breaks the `operator-sdk version` command which we changed in `v0.8.0`.

It looks like the formula downloads source from the github tarball of the release, which doesn't contain the git metadata that the Makefile uses to inject the version information. Is there a suggested way to handle this?

**Comment by chenrui333** [comment]
Thanks for taking care of it!

**Pull request closed without merging**
