### PR TITLE
fluid-synth 2.0.9

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like I need to completely replace the test because they forgot to update `--version`.

**Comment by SMillerDev** [comment]
If you can make the test better that would be awesome. Regardless you might want to report it upstream.

**Comment by Bo98** [comment]
I've made it run a 8 second midi file with the volume set to 0 (to not spook the user). Because it's audio, it might well fail in the CI - we'll see. There's other audio-related formulae which have that issue.

**Comment by SMillerDev** [comment]
```
=> /usr/local/Cellar/fluid-synth/2.0.9/bin/fluidsynth -acoreaudio -mcoremidi -i -g0 /usr/local/Cellar/fluid-synth/2.0.9/share/fluid-synth/sf2/VintageDreamsWaves-v2.sf2 Drum_sample.mid
fluidsynth: warning: Sample 'SineWave': ROM sample ignored
Killing child processes...
Error: fluid-synth: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

**Comment by Bo98** [comment]
Yes, that only happens on the CI. I’m not sure what where the timeout comes from, but it seems like 8 seconds is too long for it.

**Comment by Bo98** [comment]
Looking to move this forward considering 2.0.8 is simply broken and we should update to 2.0.9 as soon as we can.

Considering the lack of audio support on the CI, I can't see any way to have a meaningful test that also works on the CI. Any thoughts anyone?

**Comment by bayandin** [comment]
`fluid-synth` 2.1.0 has been released: https://github.com/FluidSynth/fluidsynth/archive/v2.1.0.tar.gz

**Comment by fkmclane** [comment]
Generating a .wav file like below would probably be an appropriate test. It wouldn't have caught #46643 since that was caused by undefined behaviour in the CoreAudio driver which apparently hangs in CI. I've only sparingly touched Ruby but taking inspiration from https://github.com/Homebrew/homebrew-core/blob/master/Formula/ffmpeg.rb#L106, the below works on my system. I'm happy to make a PR for v2.1.0 with this test unless @Bo98 wants to update this PR.

```ruby
test do
  # Synthesize wav file from example midi
  resource("example_midi").stage testpath
  wavout = testpath/"Drum_sample.wav"
  system bin/"fluidsynth", "-F", wavout, pkgshare/"sf2/VintageDreamsWaves-v2.sf2", testpath/"Drum_sample.mid"
  assert_predicate wavout, :exist?
end
```

Additionally, should `make check` be run before `make install` like quite a few formulae already seem to have (e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnupg.rb#L36)? That includes all of the built-in unit tests at https://github.com/FluidSynth/fluidsynth/tree/master/test and is recommended by FluidSynth at https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#common-tips-for-compiling-from-source. If so, I'm happy to include this change in the v2.1.0 PR as well.

**Comment by issyl0** [comment]
Superseded by #48863 which updates the version to the latest release.

**Pull request closed without merging**
