### PR TITLE
glib 2.50.0

### PR DESCRIPTION
**Pull request by tschoonj**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
nice

**Comment by tschoonj** [comment]
I screwed up actually, used glibmm instead of glib 😄 

By the way, it would be cool if `brew bump-formula-pr` would actually also try building the updated formula before submitting the PR

**Comment by tschoonj** [comment]
@ilovezfs  What happened to Jenkins? Is there any way I can track the build?

**Comment by ilovezfs** [comment]
>I screwed up actually, used glibmm instead of glib

I deleted the glibmm one from the queue

>By the way, it would be cool if brew bump-formula-pr would actually also try building the updated formula before submitting the PR

```
brew pull https://github.com/Homebrew/brew/pull/871
brew bump-formula-pr --dry-run --write ... foo
brew install -dvs foo
git checkout -- Formula/foo.rb
brew bump-formula-pr ... foo
```

**Comment by ilovezfs** [comment]
> What happened to Jenkins

we changed the icon!

your build will be https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8105 when it starts

**Comment by tschoonj** [comment]
It's more than just the icon that changed, I cannot seem to find a link on this page that will take me to Jenkins anymore.

**Comment by tschoonj** [comment]
Oops sorry, didn't see that build hadn't started yet!

**Comment by ilovezfs** [comment]
That's always been true. The link won't exist until the build is actually staged. The full queue is here https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/

**Comment by ilovezfs** [comment]
@tschoonj build has finished

**Comment by tschoonj** [comment]
This will need some time to fix...

**Comment by ilovezfs** [comment]
@tschoonj with the amount of patching in this formula, perhaps we should call it a macOS fork of glib :see_no_evil:

**Comment by DomT4** [comment]
The `gio` patch is failing to apply. Maybe that merged that upstream, or the patch needs a rebase 😢.

**Comment by tschoonj** [comment]
I am looking into it but I am not getting this:

````bash
==> Upgrading 1 outdated package, with result:
glib 2.50.0
==> Upgrading glib
==> Using the sandbox
==> Downloading https://download.gnome.org/sources/glib/2.50/glib-2.50.0.tar.xz
Already downloaded: /Users/schoon/Library/Caches/Homebrew/glib-2.50.0.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/59e4d
Already downloaded: /Users/schoon/Library/Caches/Homebrew/glib--patch-a4cb96b5861672ec0750cb30ecebe1d417d38052cac12fbb8a77dbf04a886fcb.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/59e4d
Already downloaded: /Users/schoon/Library/Caches/Homebrew/glib--patch-cc3f0f6d561d663dfcdd6154b075150f68a36f5a92f94e5163c1c20529bfdf32.patch
==> Patching
==> Applying hardcoded-paths.diff
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/gio/gdbusprivate.c b/gio/gdbusprivate.c
|index 54659c1..7e9d49e 100644
|--- a/gio/gdbusprivate.c
|+++ b/gio/gdbusprivate.c
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 27
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/gio/xdgmime/xdgmime.c b/gio/xdgmime/xdgmime.c
|index 42dda58..06f9947 100644
|--- a/gio/xdgmime/xdgmime.c
|+++ b/gio/xdgmime/xdgmime.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 40
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/glib/gutils.c b/glib/gutils.c
|index e229d0d..aba028c 100644
|--- a/glib/gutils.c
|+++ b/glib/gutils.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/glib--patch-20160925-48832-1fga8ah/hardcoded-paths.diff
````

Any idea why this could happen? On the buildbot the files for the patch are at least found.

**Comment by ilovezfs** [comment]
neat. fixed?

**Comment by tschoonj** [comment]
Compiles here at least

The Mountain Lion fixes I cannot test unfortunately. Wouldn't be surprised if they're broken.

**Comment by tschoonj** [comment]
Any idea as to why the `libgit2-glib` test fails on El Capitan and Yosemite?

**Comment by DomT4** [comment]
Ugh 😢. We rearranged our internals a while back, and apparently it remembers where one of those scripts used to be. If you revision bump `libgit2-glib` it'll be happy again.

**Comment by tschoonj** [comment]
Now the test for `mdk` fails on Sierra... And the error messages appear to be in German :smile:

**Comment by ilovezfs** [comment]
Yes, I love that failure so much, I'm reluctant to fix it.

**Comment by DomT4** [comment]
Merged this with a minor tweak to use a commit hash rather than `master` for the patch in https://github.com/Homebrew/homebrew-core/commit/c318fd84addbf2d6d16f69fe1d2171337b08747e & `libgit2-glib` in https://github.com/Homebrew/homebrew-core/commit/e095bcb2636ed0359f21fa904f48a97f710f1721. Also merged https://github.com/Homebrew/homebrew-core/commit/3c038073606d0a725094a40de1d25340de820797, https://github.com/Homebrew/homebrew-core/commit/b15490e4089b9f50101b6f0dc99ef64cc7ffddba, https://github.com/Homebrew/homebrew-core/commit/963caa6c08c0a37f3da6d1b65d7d3f857b1d8dac, https://github.com/Homebrew/homebrew-core/commit/fc019123d771129d89bd7c50c4d528b387289e69, https://github.com/Homebrew/homebrew-core/commit/ecfe42f41dd1bdf4b3192ea41f4f0e59aae55043 & https://github.com/Homebrew/homebrew-core/commit/1ffb63fb76bae5f5d0a53c96342463749408aee4.

Thank you as always for your contributions to Homebrew Tom. Appreciate you taking the time to keep on top of the GTK stuff, which is always various degrees of "fun".

**Comment by tschoonj** [comment]
You're welcome.  I will add more over the next couple of days whenever I can.

**Comment by tschoonj** [comment]
Oh btw I also opened PRs in gui and tex :smile:

**Comment by DomT4** [comment]
If you need a hand just shout. Don't mind finding the time to do a few version bumps.

Thanks for pointing out the tap PRs, takes me a while to remember to check those sometimes. Merged the `tex` one, re-queued the `gui` one because CI had some strange tantrum.

**Pull request closed without merging**
