### PR TITLE
clasp-cl, cando 2.0.0 (new formula).

### PR DESCRIPTION
**Pull request by yitzchak**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Add Clasp Common Lisp and Cando. Cando is an extension of Clasp for Chemistry.

### CODE REVIEW

**Comment by yitzchak** [comment]
Clasp is currently only available for x86-64. Is it possible to mark the formula as non-ARM?

**Comment by SMillerDev** [comment]
Please make one commit per formula

**Comment by yitzchak** [comment]
@SMillerDev Will it let me do that with `conflicts_with`? The local homebrew audit required both formula to exist.

**Comment by yitzchak** [comment]
@SMillerDev I've split the commits. Is there a way to stop the arm build? This is a x86_64 only formula.

**Comment by yitzchak** [comment]
I've found a problem building these formula on Homebrew for Linux since we don't currently do that on homebrew-clasp. I'll resubmit once I fix it.

**Pull request closed without merging**
