### PR TITLE
vim 8.1.2300

### PR DESCRIPTION
**Pull request by shigemk2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
20:25:33 Error: Failed to import: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb
20:25:37 vim: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb:5: syntax error, unexpected <<, expecting end
20:25:37 <<<<<<< HEAD
20:25:37 ^~
20:25:37 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb:8: syntax error, unexpected ===, expecting end
20:25:37 =======
20:25:37 ^~~
20:25:37 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb:11: syntax error, unexpected >>, expecting end
20:25:37 >>>>>>> vim 8.1.2300
20:25:37 ^~
20:25:37 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb:11: unexpected fraction part after numeric literal
20:25:37 >>>>>>> vim 8.1.2300
20:25:37             ^~~
20:25:37 + brew test-bot --ci-pr
20:25:38 Homebrew/homebrew-test-bot 7246f55 (Merge pull request #298 from Homebrew/missing-fileutils)
20:25:38 ARGV: --ci-pr --cleanup --test-default-formula --local --junit
20:25:39

**Comment by chenrui333** [comment]
Somehow there is a conflict for the `vim.rb`

**Comment by Bo98** [comment]
Let us know when you fix the merge conflict.

In the meantime, we're going to wait until Python 3.8 is merged (#45337) since this will again conflict with that.

**Comment by Bo98** [comment]
Superseded by #47232.

**Pull request closed without merging**
