### PR TITLE
python@3.9: use system expat, fix postinstall & sitecustomize issues

### LINKED ISSUE #71691: Upgrading python deletes pip-run.py file
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

`brew config`:

```
HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 54165dddaeabe05f0ad03ff3dea217e6da8d0cdd
Core tap last commit: 31 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

`brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1
```

(Yes, I checked the box saying that the `brew doctor` output contains no "Warning" lines, but only because I had to; I can't do anything about the warning without uninstalling software I need, and the warning is irrelevant to my problem anyway.)

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Upgrade the `python@3.9` formula from 3.9.1_8 to 3.9.2, because it's newer and better.

**What happened (include all command output)?**

Prior to running `brew upgrade`, as part of [an issue for pip-run](https://github.com/jaraco/pip-run/pull/50), I had confirmed that `/usr/local/lib/python3.9/site-packages/pip-run.py` existed.  After upgrading Python, the file disappeared.  I believe this behavior to be due to [these lines](https://github.com/Homebrew/homebrew-core/blob/4b438c71ac1265f69092f8049f0e9d71cc50ff07/Formula/python%403.9.rb#L299-L307) in the `python@3.9` formula.

```
$ brew upgrade
==> Upgrading 8 outdated packages:
pango 1.48.1 -> 1.48.2
glib 2.66.6 -> 2.66.7
gcc 10.2.0_3 -> 10.2.0_4
libgcrypt 1.9.1 -> 1.9.2
ghc 8.10.3 -> 8.10.4
graphviz 2.46.0 -> 2.46.1
openssl@1.1 1.1.1i -> 1.1.1j
python@3.9 3.9.1_8 -> 3.9.2
==> Upgrading openssl@1.1 1.1.1i -> 1.1.1j
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_su
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/5725361adcd088a5b4fb2
######################################################################## 100.0%
==> Pouring openssl@1.1-1.1.1j.big_sur.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1j: 8,071 files, 18.5MB
Removing: /usr/local/Cellar/openssl@1.1/1.1.1i... (8,067 files, 18.5MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/openssl@1.1--1.1.1i.big_sur.bottle.tar.gz... (5.4MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/openssl@1.1--1.1.1i.tar.gz... (9.4MB)
==> Upgrading glib 2.66.6 -> 2.66.7
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.2.big_sur.
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/b139e4a193c191b8afd45
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/glib-2.66.7.big_sur.bottle.
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/d5769584a13c0abc5a761
######################################################################## 100.0%
==> Installing dependencies for glib: python@3.9
==> Installing glib dependency: python@3.9
==> Pouring python@3.9-3.9.2.big_sur.bottle.tar.gz
==> /usr/local/Cellar/python@3.9/3.9.2/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.2/bin/pip3 install -v --global-option=--no-
==> /usr/local/Cellar/python@3.9/3.9.2/bin/pip3 wheel --wheel-dir=/usr/local/Cel
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.9/3.9.2: 3,936 files, 66.0MB
==> Installing glib
==> Pouring glib-2.66.7.big_sur.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/glib/2.66.7: 441 files, 20.8MB
Removing: /usr/local/Cellar/glib/2.66.6... (441 files, 20.8MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/glib--2.66.6.big_sur.bottle.tar.gz... (6.2MB)
==> Upgrading gcc 10.2.0_3 -> 10.2.0_4
==> Downloading https://homebrew.bintray.com/bottles/gcc-10.2.0_4.big_sur.bottle
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/9c412d919eb6808625ac6
######################################################################## 100.0%
==> Pouring gcc-10.2.0_4.big_sur.bottle.1.tar.gz
🍺  /usr/local/Cellar/gcc/10.2.0_4: 1,465 files, 339.5MB
Removing: /usr/local/Cellar/gcc/10.2.0_3... (1,465 files, 339.5MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/gcc--10.2.0_2.big_sur.bottle.tar.gz... (100.4MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/gcc--10.2.0_3.big_sur.bottle.tar.gz... (100.8MB)
==> Upgrading libgcrypt 1.9.1 -> 1.9.2
==> Downloading https://homebrew.bintray.com/bottles/libgcrypt-1.9.2.big_sur.bot
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/3de65930f6d96b90ef2d9
######################################################################## 100.0%
==> Pouring libgcrypt-1.9.2.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/libgcrypt/1.9.2: 23 files, 3MB
Removing: /usr/local/Cellar/libgcrypt/1.9.1... (23 files, 3MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/libgcrypt--1.9.1.big_sur.bottle.tar.gz... (1.2MB)
==> Upgrading ghc 8.10.3 -> 8.10.4
==> Downloading https://homebrew.bintray.com/bottles/ghc-8.10.4.big_sur.bottle.t
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/965f94c14b56e3db7b239
######################################################################## 100.0%
==> Pouring ghc-8.10.4.big_sur.bottle.tar.gz
==> /usr/local/Cellar/ghc/8.10.4/bin/ghc-pkg recache
🍺  /usr/local/Cellar/ghc/8.10.4: 6,907 files, 1.5GB
Removing: /usr/local/Cellar/ghc/8.10.3... (6,905 files, 1.5GB)
Removing: /Users/jwodder/Library/Caches/Homebrew/ghc--8.10.3.big_sur.bottle.tar.gz... (297.0MB)
==> Upgrading graphviz 2.46.0 -> 2.46.1
==> Downloading https://homebrew.bintray.com/bottles/pango-1.48.2.big_sur.bottle
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/c6fc514ae39aa3825f98b
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/graphviz-2.46.1.big_sur.bot
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/e5c6de435b4890fe00d96
######################################################################## 100.0%
==> Installing dependencies for graphviz: pango
==> Installing graphviz dependency: pango
==> Pouring pango-1.48.2.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/pango/1.48.2: 64 files, 3MB
==> Installing graphviz
==> Pouring graphviz-2.46.1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/graphviz/2.46.1: 462 files, 12.2MB
Removing: /usr/local/Cellar/graphviz/2.46.0... (462 files, 12.2MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/graphviz--2.46.0.big_sur.bottle.tar.gz... (6.7MB)
==> Upgrading pango 1.48.2 -> 1.48.2
Removing: /usr/local/Cellar/pango/1.48.1... (64 files, 3MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/pango--1.48.1.big_sur.bottle.tar.gz... (734.3KB)
==> Upgrading python@3.9 3.9.2 -> 3.9.2
Removing: /usr/local/Cellar/python@3.9/3.9.1_8... (4,048 files, 67.4MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/python@3.9--3.9.1_8.big_sur.bottle.tar.gz... (17.1MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/python@3.9--3.9.1_2.big_sur.bottle.tar.gz... (16.6MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/python@3.9--3.9.1.tar.xz... (18MB)
Removing: /Users/jwodder/Library/Caches/Homebrew/python@3.9--3.9.1_6.big_sur.bottle.tar.gz... (16.7MB)
==> Caveats
==> openssl@1.1
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> python@3.9
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> glib
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

**What did you expect to happen?**

`/usr/local/lib/python3.9/site-packages/pip-run.py`, being part of the pip-run Python package rather than part of the pip provided by ensurepip, should not have been deleted.

**Step-by-step reproduction instructions (by running `brew` commands)**

* Install pip-run with `python3 -m pip install pip-run`
* Confirm that `/usr/local/lib/python3.9/site-packages/pip-run.py` exists
* Upgrade/reinstall Python
    * Note: I have not reproduced this step, as I am not clear how to do it without causing an even bigger headache.
* Confirm that `/usr/local/lib/python3.9/site-packages/pip-run.py` no longer exists

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Build:

* Use system expat rather than the bundled one.

Postinstall:

* Fix some pip and setuptools directories being erroneously removed when only one is updated.
* Fix some non-pip files being deleted, such as `pip-run` (fixes #71691).
* Fix inreplace error when running postinstall twice.

Sitecustomize:

* Fix `sys._base_executable` not being set like `sys.executable`.
  - This fixes the `home` value in `pyvenv.cfg` using the Cellar path.
* Change `sys.(base_)prefix` and `sys.(base_)exec_prefix` to use `opt_prefix`.
  - This fixes some `virtualenv` extensions to `pyvenv.cfg` using the Cellar path.
* Tighten version comparison to also match the minor version.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
```
Error: 3 failed steps!
brew test --retry --verbose cargo-edit
brew test --retry --verbose rbtools
brew test --retry --verbose svtplay-dl
```
All pre-existing. `svtplay-dl` should be fixable, though knowing Swedish would help.

**Comment by Bo98** [comment]
`svtplay-dl` is fixed upstream (https://github.com/spaam/svtplay-dl/commit/7440e3f12ad1b66e7b7c112e509f2da8a543be16), but if we don't want to wait then we can just change the video used in the test to another one.

**Comment by carlocab** [comment]
I tried to use the example video on their website:
```
❯ svtplay-dl https://www.svtplay.se/video/15367465/var-tid-ar-nu/var-tid-ar-nu-sasong-1-freden
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue
```
#73013

**Comment by carlocab** [comment]
Mojave:
```
Error: 6 failed steps!
brew test --retry --verbose cargo-edit
brew test --retry --verbose hyperkit
brew test --retry --verbose rbtools
brew test --retry --verbose svtplay-dl
brew test --retry --verbose swift
brew test --retry --verbose wasm-pack
```

**Comment by carlocab** [comment]
It looks like the Big Sur node encountered an out-of-space error.

Catalina:

```
Error: 7 failed steps!
brew test --retry --verbose cargo-edit
brew test --retry --verbose hyperkit
brew fetch --retry pass-otp
brew test --retry --verbose rbtools
brew test --retry --verbose svtplay-dl
brew test --retry --verbose wapm
brew test --retry --verbose wasm-pack
```

Big Sur:

```
Error: 40 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose aws-google-auth
brew test --retry --verbose cargo-edit
brew install --only-dependencies creduce
brew install creduce
brew test --retry --verbose hyperkit
brew install libtensorflow
brew install llvm@7
brew install llvm@8
brew install llvm@9
brew install --only-dependencies nvc
brew install nvc
brew install --only-dependencies oclgrind
brew install oclgrind
brew install --only-dependencies odin
brew install odin
brew install --only-dependencies pyside
brew install pyside
brew install --only-dependencies pyside@2
brew linkage --test pyside@2
brew install --only-dependencies --include-test pyside@2
brew test --retry --verbose pyside@2
brew test --retry --verbose rbtools
brew install root
brew install --only-dependencies rtags
brew install rtags
brew install --only-dependencies standardese
brew install standardese
brew test --retry --verbose svtplay-dl
brew install swift
brew install tesseract-lang
brew install --only-dependencies --include-test tree-sitter
brew test --retry --verbose tree-sitter
brew test --retry --verbose wapm
brew test --retry --verbose wasm-pack
brew install --only-dependencies wllvm
brew install --only-dependencies --include-test wllvm
brew test --retry --verbose wllvm
brew install --only-dependencies zig
brew install zig
```

**Comment by Bo98** [comment]
I will look into that out-of-space stuff at some point. Might be Bazel tmp directories again.

**Pull request closed without merging**
