### PR TITLE
kubernetes-helm 2.1.2 (new formula)

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

New formula. This would migrate the CLI tool `helm` from [caskroom/homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/helm.rb) to homebrew-core.

### CODE REVIEW

**Comment by dunn** [comment]
```
Error: 1 problem in 1 formula
helm:
  * Formula name conflicts with homebrew/emacs/helm
```
I'm open to renaming the Emacs formula, but if there's a good suffix or something here, that'd be nice.

**Comment by dunn** [comment]
The `make` task seems to be ignoring `GLIDE_HOME`:
```
==> make bootstrap
go get -u github.com/mitchellh/gox
glide install --strip-vendor
�[0;32m[INFO]	�[mDownloading dependencies. Please wait...
�[0;31m[ERROR]	�[mCache directory unavailable: mkdir /Users/brew/.glide: operation not permitted
make: *** [bootstrap] Error 1

**Comment by cblecker** [comment]
Hi @dunn --
I initially named it the same as the Cask so that the tap migration would be simple. I renamed it to kubernetes-helm, similar to kubernetes-cli existing formula, but then the audit identified that this was a Formula that was moved to the boneyard.

As for GLIDE_HOME, I was initially specifying GLIDE_TMP. Changing it to glide_home seems to have fixed it up.

**Comment by ilovezfs** [comment]
This should use a glide home in the cache.
```
Josephs-MacBook-Pro:Formula joe$ ag glide_home
algernon.rb
21:    ENV["GLIDE_HOME"] = buildpath/"glide_home"

cayley.rb
24:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

consul-backinator.rb
20:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

dvm.rb
20:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

ironcli.rb
19:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

peco.rb
20:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

piknik.rb
21:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

snap-telemetry.rb
22:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

terragrunt.rb
21:    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"
```

**Comment by cblecker** [comment]
Well messed it up a couple times, but I think it should be good now. Thanks for your help!

**Comment by cblecker** [comment]
The build passed 🎉 !

Two questions:
- Is there anything else we need to do to move https://github.com/Homebrew/homebrew-boneyard/blob/master/kubernetes-helm.rb out of the boneyard?
- What's the best way to go about migrating https://github.com/caskroom/homebrew-cask/blob/master/Casks/helm.rb into this formula?

**Comment by cblecker** [comment]
Any update on this?

**Comment by ilovezfs** [comment]
@cblecker do you mind also opening the PR to delete it from the boneyard?

**Comment by cblecker** [comment]
Yup, can do.

**Comment by cblecker** [comment]
Opened https://github.com/Homebrew/homebrew-boneyard/pull/262

**Comment by ilovezfs** [comment]
@cblecker :rocket: thanks for resurrecting the formula!

**Pull request closed without merging**
