### PR TITLE
workflows: update token usage

### PR DESCRIPTION
**Pull request by carlocab**
Let's avoid using PATs where we can.

### CODE REVIEW

**Comment by Bo98** [comment]
We've done a decent job avoiding third-party actions, with the only real exception being the `google-github-actions/setup-gcloud` that we're going to phase out (my next project).

While I'm not against third-party actions where it makes sense, some of these seem so trivial that it doesn't seem worth setting up Dependabot and having people vet those PRs that it's not a bad/compromised update.

Maybe I'm wrong but it feels like a simplification could be:

```yml
on:
  issue_comment:
    types: [created]

...

  if: github.event.issue.pull_request && github.event.comment.body == "/rebase" # perhaps too restrictive of forbidding whitespace etc but this is an example

...

    # use setup-homebrew (faster for homebrew-core if we also run on macos-latest, because cloning is slow)

...

    gh pr checkout ${{ github.event.issue.number }}
    git rebase master
    git push --force

...

    await github.rest.reactions.createForIssueComment{
      ...context.repo,
      context.payload.comment.id,
      "+1",
    })
```

**Comment by carlocab** [comment]
Yes, not that keen on new external actions either, but the PRs adding these were merged before I was able to review them. But, if we were ok with keeping these actions, we should still use `GITHUB_TOKEN` where we can.

**Comment by p-linnane** [comment]
Reverted in #139664 and #139665.

**Comment by carlocab** [comment]
Not sure if GitHub supports repository-scoped action permissions, but I think we can remove `peter-evans`' actions from the list of allowed ones. Our only other use of it was removed in 69e085bb513db3c04eb5d1bc15adada8cecb3ba9.

CC @Bo98 @issyl0 @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
> Yes, not that keen on new external actions either, but the PRs adding these were merged before I was able to review them. But, if we were ok with keeping these actions, we should still use `GITHUB_TOKEN` where we can.

I'm fine with (these) new actions from an existing author like this that we already use and trust. Will ✅ a new PR.

**Pull request closed without merging**
