### PR TITLE
clipper 1.0

### PR DESCRIPTION
**Pull request by wincent**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
@BrewTestBot test this please

**Review by ilovezfs — CHANGES_REQUESTED** [review]
https://github.com/wincent/clipper/releases/latest still points to 0.4.2

**Comment by wincent** [comment]
1.0 now marked as latest on GitHub: https://github.com/wincent/clipper/releases/tag/1.0

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @wincent! Shipped.

**Pull request closed without merging**
