### PR TITLE
talloc, xkeyboardconfig: migrate to Python 3.10

### PR DESCRIPTION
**Pull request by cclauss**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@cclauss thanks for the PR, can you separate into two commits(`talloc: migrate to Python 3.10` and `xkeyboardconfig: migrate to Python 3.10`)? In this way, it can be automerged by the bot, thanks!

**Comment by cclauss** [comment]
> can you separate into two commits

That contradicts https://github.com/Homebrew/homebrew-core/pull/90767#issuecomment-989771220

**Comment by chenrui333** [comment]
> > can you separate into two commits
> 
> That contradicts [#90767 (comment)](https://github.com/Homebrew/homebrew-core/pull/90767#issuecomment-989771220)

We probably meant two separate things, in here it is more for `one commit per formula`, while in that PR, it makes sense to squash commit changes for one formula.

**Comment by chenrui333** [comment]
The bottom line is it should be always at least `one commit per formula`, it is actually documented in here, https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

> Make a separate commit for each changed formula with git add and git commit.
Please note that our preferred commit message format for simple version updates is “<FORMULA_NAME> <NEW_VERSION>”, e.g. “source-highlight 3.1.8”.

Let me know if it makes better sense now.

**Pull request closed without merging**
