### PR TITLE
node 11.2.0

### PR DESCRIPTION
**Pull request by shinnn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lembacon** [comment]
```
00:03:15 ==> Downloading https://nodejs.org/dist/v11.2.0/node-v11.2.0.tar.gz
00:03:15 Error: An exception occurred within a child process:
00:03:15   ChecksumMismatchError: SHA256 mismatch
00:03:15 Expected: cd17fafcdb21ae80fb94e455e63567c70b3bceedf982b93ae9e4aea411f6a6ea
00:03:15 Actual: 2766fea693bc7a4750feef16d3c109df44d4319d4763678d60a5e8f177d0fa9e
```

**Comment by shinnn** [comment]
Interesting. I just copied SHA256 from the Node.js official hash list https://nodejs.org/dist/v11.2.0/SHASUMS256.txt.asc but, yes, it actually doesn't match.

**Comment by shinnn** [comment]
The test is failing but it's a known issue. https://github.com/Homebrew/homebrew-core/pull/33690#issuecomment-435671842

**Comment by lembacon** [comment]
Shipped. Thanks @shinnn!

**Comment by shinnn** [comment]
No problem. Thanks for the review, @lembacon!

**Pull request closed without merging**
