### PR TITLE
monero: update to v0.14.02

### PR DESCRIPTION
**Pull request by adamgall**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by adamgall** [comment]
this is an important update, as it's REQUIRED for the current blockchain versions (v10 and v11) to stay in sync. see https://github.com/monero-project/monero#scheduled-software-upgrades

**Comment by Moisan** [comment]
Thank you @adamgall  for your first contribution! Without people like you, we couldn't run this project.

Note that next time you can use `brew bump-formula-pr` to quickly bump a formula version.

**Comment by adamgall** [comment]
Thanks for the kind words @Moisan ! I was having troubles with `brew bump-formula-pr`, getting a Github API error, throwing from this line: 

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L341

The message was "Unable to Fork: Not Found!" I couldn't really figure out what the problem was, so I just did the manual thing. Any ideas there?

**Comment by adamgall** [comment]
Also just noticed my version number typo in this PR title 😑

**Pull request closed without merging**
