### PR TITLE
loki 1.5.0 (new formula)

### PR DESCRIPTION
**Pull request by ankane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

There are three binaries: `promtail` gathers logs and sends them to `loki`, which can be queried with `logcli`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Are these usually packaged in one?

**Comment by ankane** [comment]
They're all part of the same Graphana project and repo, but you can download them separately on the releases page: https://github.com/grafana/loki/releases. Also, no package on Ubuntu or Debian.

**Comment by SMillerDev** [comment]
I think we want to package them separately as well then.

**Comment by ankane** [comment]
Since logcli requires loki to test, will wait to submit that one.

**Review by chenrui333 — APPROVED** [review]
lgtm

**Comment by SeekingMeaning** [comment]
Thanks again for your contribution to Homebrew/core, Andrew! 🌟

**Comment by ankane** [comment]
Thanks @chenrui333 and @SeekingMeaning!

**Pull request closed without merging**
