### PR TITLE
netdata - enable `dbengine` save mode for the netdata package

### PR DESCRIPTION
**Pull request by samm-git**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Starting from version 0.18 dbengine is [default and recommended](https://docs.netdata.cloud/database/) engine for the netdata package. MacOS build does not have it, due to dependencies. 

This patch adds missing dependencies, including judy which is not present as normal brew package due to upstream issues (was removed at some point) so added as static dependency, same way as one of the other package doing. 

Tested on MacOS 10.14

### CODE REVIEW

**Review by chenrui333 — CHANGES_REQUESTED** [review]

**Comment by chenrui333** [comment]
Also, please squash the commits into one commit, `netdata: enable dbengine`, thanks!

**Comment by chenrui333** [comment]
> Also, please squash the commits into one commit, netdata: enable dbengine, thanks!!

Please squash the commits as well

**Comment by samm-git** [comment]
@chenrui333 any chance to finally get it merged? :)

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @samm-git, merging it now!

**Pull request closed without merging**
