### PR TITLE
qt 6.4.0

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
This was likely caused by the storage system crashing. Sorry about that - will look into what happened.

**Comment by fxcoudert** [comment]
Requeuing

**Review by fxcoudert — DISMISSED** [review]

**Comment by fxcoudert** [comment]
CI failed on macOS 11 and 12. It got stuck after 6 hours, and did not have output for the last 5 hours. I'm killing it.

**Comment by Bo98** [comment]
Looks like it was just trying to rebuild Qt again because it tried do the other parts of the PR, which needed Qt. Hence the apparent slowness.

We probably should handle that better.

Failure was:

```
[7083/28458] ACTION //third_party/dav1d:dav1d_asm_action(//build/toolchain/mac:clang_x64)
FAILED: obj/third_party/dav1d/dav1d_asm/cdef16_avx2.o 
/usr/local/bin/python3 ../../../3rdparty/chromium/build/gn_run_binary.py nasm -fmacho64 --macho-min-os=macos11 -P ../../../3rdparty/chromium/third_party/dav1d/config/linux/x64/config.asm -I../../../3rdparty/chromium/third_party/dav1d/libdav1d/src// -I../../../3rdparty/chromium/third_party/dav1d/config/linux/x64/ -I./ -I../../../3rdparty/chromium/ -Igen/ -DSTACK_ALIGNMENT=32 -DPREFIX -MD obj/third_party/dav1d/dav1d_asm/cdef16_avx2.o.d -o obj/third_party/dav1d/dav1d_asm/cdef16_avx2.o ../../../3rdparty/chromium/third_party/dav1d/libdav1d/src/x86/cdef16_avx2.asm
nasm: fatal: failed to set minimum os for mach-o 'macos11'
Type ./nasm -h for help.
nasm failed with exit code 1
```

**Comment by Bo98** [comment]
Looking at the code, I think it might not like us using `-DCMAKE_OSX_DEPLOYMENT_TARGET=11` and Chromium might be insisting on `-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0`

**Comment by jrozner** [comment]
Any updates on this? Waiting on qt 6.4 landing

**Comment by fxcoudert** [comment]
> Any updates on this?

@jrozner please look at the history of the PR. You're welcome to help fix the outstanding issues.

**Comment by cho-m** [comment]
> Looking at the code, I think it might not like us using `-DCMAKE_OSX_DEPLOYMENT_TARGET=11` and Chromium might be insisting on `-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0`

Sounds right. I also saw Chromium's `nasm` has its own code to parse macOS version number which caused issues. For now, I just appended a `.0` to fix. Not sure if this will cause any issues elsewhere, but at least worked for our CI runners.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
