### PR TITLE
knot 2.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
🤔 
```
contrib/test_time...............ABORTED (killed by signal 5)

**Comment by woodruffw** [comment]
Failure on Yosemite might be slightly more elucidative:

```
contrib/time.c:22:16: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &result);
```

**Comment by vcunat** [comment]
This should be fixed by applying https://gitlab.labs.nic.cz/labs/knot/merge_requests/664.

**Comment by fcelda** [comment]
PR in #9526 includes the patch above. And tweaks configuration file slightly.

**Pull request closed without merging**
