### PR TITLE
rabbitmq 3.8.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> brew install --verbose rabbitmq
==> FAILED
==> Downloading https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.4/rabbitmq-server-generic-unix-3.8.4.tar.xz
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/b60532700305f678de20a137443a1d14b59806d42a08d858e00ed7f2ddf7b32b--rabbitmq-server-generic-unix-3.8.4.tar.xz
==> Verifying b60532700305f678de20a137443a1d14b59806d42a08d858e00ed7f2ddf7b32b--rabbitmq-server-generic-unix-3.8.4.tar.xz checksum
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200525-7688-1fis3pi.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rabbitmq.rb --verbose
tar xof /Users/brew/Library/Caches/Homebrew/downloads/b60532700305f678de20a137443a1d14b59806d42a08d858e00ed7f2ddf7b32b--rabbitmq-server-generic-unix-3.8.4.tar.xz -C /private/tmp/d20200525-7689-16jakor
cp -pR /private/tmp/d20200525-7689-16jakor/rabbitmq_server-3.8.4/. /private/tmp/rabbitmq-20200525-7689-hng46z/rabbitmq_server-3.8.4
chmod -Rf +w /private/tmp/d20200525-7689-16jakor
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
/usr/local/Cellar/rabbitmq/3.8.4/sbin/rabbitmq-defaults:
  expected replacement of /^ERL_DIR=$/ with "ERL_DIR=/usr/local/opt/erlang/bin/"
```

**Comment by bayandin** [comment]
The huge refactoring was done in https://github.com/rabbitmq/rabbitmq-server/commit/d3bd7d769be5bc50d029af4832c8b0121bd6b5bf#diff-61953dcde9674a28c7d945e8153d8e84
We need to reassess (or tune) a way of setting up defaults for `rabbitmq`.

**Comment by chenrui333** [comment]
let me update it really quick.

**Comment by chenrui333** [comment]
not actively working on this, closing the PR now.

**Comment by Rylan12** [comment]
@chenrui333 if you get this working, can you also separate the arguments in the `Utils.safe_popen_read` command on line 53?

It should become:

```ruby
(bash_completion/"rabbitmqadmin.bash").write Utils.safe_popen_read("#{sbin}/rabbitmqadmin", "--bash-completion")
```

This is in preparation for a PR to make this change universally, so if you can make it here instead that would be great!

**Comment by chenrui333** [comment]
@Rylan12 Nice, I will definitely have the change in this PR.

**Comment by chenrui333** [comment]
Currently failed with a different message now, debugging locally.
```
==> /usr/local/Cellar/rabbitmq/3.8.4/sbin/rabbitmq-server -detached
==> /usr/local/Cellar/rabbitmq/3.8.4/sbin/rabbitmqctl status
Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.
Arguments given:
	status

Usage
```

**Comment by chenrui333** [comment]
Close the PR for now (going to work a little bit in my local before reopening it)

**Comment by Rylan12** [comment]
@chenrui333  FYI I added the change separating the shell commands to #57066 along with some of the other similar changes. If you get this working, though, there's no need to wait for that to be merged.

**Pull request closed without merging**
