### PR TITLE
infer 0.9.4.1

### PR DESCRIPTION
**Pull request by akotulski**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by akotulski** [comment]
This is followup PR after discussion in https://github.com/Homebrew/homebrew-core/pull/7184
Somehow I couldn't run `brew audit --strict infer`:
```
akotulski$ brew audit --strict infer
Error: Error while running RuboCop
```

**Comment by ilovezfs** [comment]
>Somehow I couldn't run brew audit --strict infer

That's odd

```
HOMEBREW_DEVELOPER=1 brew audit -dv --strict infer
```

**Comment by akotulski** [comment]
Output still looks useless to me:
```
$ HOMEBREW_DEVELOPER=1 brew audit -dv --strict infer
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/infer.rb
Error: Error while running RuboCop
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:76:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:45:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:66:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Try to run `rubocop` manually.

**Comment by akotulski** [comment]
It was crashing with an error that points to inconsistent versions of `ruby`. I cleaned up my ruby installation and now `brew audit --strict infer` succeeds.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew and being so flexible with the release! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
