### PR TITLE
emacs 28.1

### PR DESCRIPTION
**Pull request by peeweep**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @peeweep !

**Comment by tani** [comment]
@peeweep Is it possible to build with `--with-native-comp` option? It might be better for all users.

**Comment by peeweep** [comment]
Hi @tani, I tried to add `native-comp` option, but the emacs I compiled is very slow, you can try it.
``` diff
diff --git a/Formula/emacs.rb b/Formula/emacs.rb
index 6b31d986e63..3514375c4eb 100644
--- a/Formula/emacs.rb
+++ b/Formula/emacs.rb
@@ -26,6 +26,8 @@ class Emacs < Formula
   depends_on "pkg-config" => :build
   depends_on "gnutls"
   depends_on "jansson"
+  depends_on "libgccjit"
+  depends_on "gcc" => :build
 
   uses_from_macos "libxml2"
   uses_from_macos "ncurses"
@@ -40,12 +42,22 @@ class Emacs < Formula
     # https://github.com/Homebrew/homebrew-core/pull/70421
     ENV["ac_cv_func_aligned_alloc"] = "no" if MacOS.version == :mojave
 
+    gcc_ver = Formula["gcc"].any_installed_version
+    gcc_ver_major = gcc_ver.major
+    gcc_lib="#{HOMEBREW_PREFIX}/lib/gcc/#{gcc_ver_major}"
+    ENV.append "CFLAGS", "-I#{Formula["gcc"].include}"
+    ENV.append "CFLAGS", "-I#{Formula["libgccjit"].include}"
+    ENV.append "LDFLAGS", "-L#{gcc_lib}"
+    ENV.append "LDFLAGS", "-I#{Formula["gcc"].include}"
+    ENV.append "LDFLAGS", "-I#{Formula["libgccjit"].include}"
+
     args = %W[
       --disable-silent-rules
       --enable-locallisppath=#{HOMEBREW_PREFIX}/share/emacs/site-lisp
       --infodir=#{info}/emacs
       --prefix=#{prefix}
       --with-gnutls
+      --with-native-compilation
       --without-x
       --with-xml2
       --without-dbus
```

**Comment by tani** [comment]
According to EmacsWiki, we take a minute to launch emacs for the first time.
The reasons are;

- Module/package compilation is deferred by default.
- Anti-virus system scans the native modules for initial loading.

However, we can use the AOT compilation by `ENV["NATIVE_FULL_AOT"] = "1"` .
Moreover, we can launch fast the second time.
In my opinion, we still have enough advantages to enable this option.
In fact, some modern emacs packages suggest enabling this option.

---

From Emacs Wiki,
> ## Ahead-of-time compilation
> Sometimes it is useful to compile ahead-of-time, for example if you are packaging Emacs for others.
> 
> Emacs distribution
> It is possible to native compile ahead-of-time all the Emacs distribution using the NATIVE_FULL_AOT, for example:
> 
>     $ make NATIVE_FULL_AOT=1 -j$(nproc)

> ## Very slow load times
> If you’re running anti-virus software, each native-compiled library may get scanned for viruses when loaded, which can have a dramatic impact on loading performance, especially when starting Emacs for the first time in a session.
> 
> If you’re experiencing such slowness, test disabling your anti-virus to see whether that’s the cause.

From, lsp-mode

> ## gccemacs[#](https://emacs-lsp.github.io/lsp-mode/page/performance/#gccemacs)
> [gccemacs](https://akrl.sdf.org/gccemacs.html) is a bleeding-edge version of Emacs that compiles elisp to native code, resulting in more than 200% speedup. For everyone looking for optimal performance, gccemacs is the way to go.

**Comment by jrimmer-housecallpro** [comment]
@peeweep -- Is there another pull request with that change in it?

**Comment by peeweep** [comment]
I've observed that no distribution has this option enabled by default yet, and I don't think this change should be pushed to all users of homebrew-core. Adding options like https://github.com/railwaycat/homebrew-emacsmacport/commit/09504b43 should be a good choice, but now core no longer allows adding options. So I think tap can be used if anyone needs

**Comment by tani** [comment]
Okay, thank you for the explanation.

**Pull request closed without merging**
