### PR TITLE
fileicon 0.3.3

### PR DESCRIPTION
**Pull request by mklement0**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
https://www.githubstatus.com/incidents/qfby3shb6r3w

**Comment by mklement0** [comment]
Thanks for letting me know, @chenrui333.
Does this mean that - once the problem is resolved by GitHub - the CI actions will run automatically, or is there something I need to do to trigger them again?

**Comment by chenrui333** [comment]
@mklement0 can you rebase to the latest master, I think it should be good now.

**Comment by mklement0** [comment]
@chenrui333, since I didn't know how to do that, I bumped the version number and created https://github.com/Homebrew/homebrew-core/pull/124695

**Pull request closed without merging**
