### PR TITLE
insect 4.6.0 (new formula)

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

insect is a high precision scientific calculator with support for physical units. It was recently [HN'ed](https://news.ycombinator.com/item?id=14625795), and has 689 stars on [GitHub](https://github.com/sharkdp/insect) at the time of submission. Looks like this will be a more productive replacement for Mathematica/MathKernel for some of my physics calculations, especially on machines where I don't want to install Mathematica or can't have it licensed.

Note to self: submit a PR to sharkdp/insect to add `brew install insect` to their README.

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:new: :beetle:

**Comment by ilovezfs** [comment]
@zmwangx so I was looking at adding HEAD, so that `brew livecheck` will work, but it gives a little error in the test. I may add it anyway, though.

```
==> /usr/local/Cellar/insect/HEAD-9e00870/bin/insect '1 min + 60 s -> ms'
module.js:487
    throw err;
    ^

Error: Cannot find module './output/Insect/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/insect/HEAD-9e00870/libexec/lib/node_modules/insect/index.js:3:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by zmwangx** [comment]
@ilovezfs You can't npm install from the repo directly, since it's lacking an `output` directory which is generated somehow (didn't look into how it's generated, but I got that same error when I first started with the release tarball on GitHub).

I have added it to my `github-release-monitor` though, so I should be able to take care of updates.

**Comment by zmwangx** [comment]
Okay, you can generate `output/` by installing purescript and pulp, pulling in all bower deps, and finally running pulp to build the JS. The npm package is essentially the build artifect.

**Comment by ilovezfs** [comment]
OK, thanks.

**Comment by ilovezfs** [comment]
@zmwangx voilà: https://github.com/Homebrew/homebrew-livecheck/commit/6468a1e4e7a20cc0c3a2155334ad3d0d624f78e7

**Comment by zmwangx** [comment]
Huh, didn't know the Homebrew org absorbed homebrew-livecheck.

**Comment by ilovezfs** [comment]
@zmwangx yup! https://github.com/Homebrew/homebrew-livecheck/issues/16

**Pull request closed without merging**
