### PR TITLE
`htop-osx`: remove and set alias to `htop`

### PR DESCRIPTION
**Pull request by KarlAmort**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
```htop-osx``` is an 8-year old fork of htop, which, in the meantime, has advanced from version 0.8.x to 2.0 and has long added support for MacOS. See the note at the top of the Readme at [https://github.com/max-horvath/htop-osx](https://github.com/max-horvath/htop-osx): 

```
This Mac OS X fork is outdated
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

htop 1.x has been released for Linux, but this Mac fork is based
on htop 0.8.x from 2009. Check the original htop webpage for Mac
OS X support.
http://hisham.hm/htop/
```

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Please add an entry to formula_renames.json too so that the htop-osx people get automatically switched over.

**Comment by ilovezfs** [comment]
@MatthiasWinkelmann ping

**Comment by MatthiasWinkelmann** [comment]
@ilovezfs Entry to formula_renames.json added and rebased on current master.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks again for your contribution to Homebrew, @MatthiasWinkelmann!

**Pull request merged**
