### PR TITLE
goocanvas 3.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
filed a bucket report for license, https://gitlab.gnome.org/GNOME/goocanvas/-/issues/12

**Comment by chenrui333** [comment]
Current license is `LGPL-2.0`

**Comment by chenrui333** [comment]
`configure: error: Gpredict requires libgoocanvas-2.0-dev` looks like we need to create `goocanvas@2`

**Comment by carlocab** [comment]
Is gpredict maintained? If it is I think we want to find out what their timeline for supporting goocanvas 3.0 is.

I'm also currently inclined to just include goocanvas 2.0 as a resource in gpredict, since I'm not sure having just one formula that needs it is enough to justify an additional versioned formula.

**Comment by chenrui333** [comment]
> Is gpredict maintained? If it is I think we want to find out what their timeline for supporting goocanvas 3.0 is.
> 
> I'm also currently inclined to just include goocanvas 2.0 as a resource in gpredict, since I'm not sure having just one formula that needs it is enough to justify an additional versioned formula.

yeah, we should use resource rather than versioned formula.

**Comment by chenrui333** [comment]
I am gonna check if they do have a ticket to support `goocanvas 3` or not

**Comment by chenrui333** [comment]
another idea is that we also try patch to see if it can be built against `goocanvas 3`

**Pull request closed without merging**
