### PR TITLE
apache-pulsar 3.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Given this is a major update, are we sure it still requires the older openjdk, and still doesn't support ARM?

**Comment by chenrui333** [comment]
> Given this is a major update, are we sure it still requires the older openjdk, and still doesn't support ARM?

I think it still requires jdk 17 as shown in here, https://pulsar.apache.org/contribute/setup-building/ (jdk 17 is also LTS though)

**Comment by glingy** [comment]
I had an M1 and a moment, so it's attempting to build with this patch updated to JDK 20 and without the x86_64 requirement. So far it has not complained.

**Comment by glingy** [comment]
It appears there is an issue with that configuration:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:33 min
[INFO] Finished at: 2023-08-05T00:26:44Z
[INFO] ------------------------------------------------------------------------
[DEBUG] State transition from 'API_LOCKED' to 'CLOSED' for Gradle Enterprise Maven extension version '1.17.1'.
[DEBUG] Setting Maven session to null.
[DEBUG] Transitioning to 'EXECUTION_FINISHED'.
[INFO] 537 goals, 537 executed
[DEBUG] Finishing project 'Pulsar Functions :: Worker'
[DEBUG] Transitioning to 'CLOSED'.
[DEBUG] State transition from 'CLOSED' to 'CLOSED' for Gradle Enterprise Maven extension version '1.17.1'.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project pulsar-functions-worker: Compilation failure: Compilation failure: 
[ERROR] /private/tmp/apache-pulsar-20230804-76435-ra7wzu/apache-pulsar-3.0.1-src/pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java:[933,25] incompatible types: org.apache.pulsar.functions.proto.Function.FunctionMetaData cannot be converted to lombok.val
[ERROR] /private/tmp/apache-pulsar-20230804-76435-ra7wzu/apache-pulsar-3.0.1-src/pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java:[938,29] no suitable method found for setFunctionMetaData(lombok.val)
[ERROR]     method org.apache.pulsar.functions.proto.Function.Instance.Builder.setFunctionMetaData(org.apache.pulsar.functions.proto.Function.FunctionMetaData) is not applicable
[ERROR]       (argument mismatch; lombok.val cannot be converted to org.apache.pulsar.functions.proto.Function.FunctionMetaData)
[ERROR]     method org.apache.pulsar.functions.proto.Function.Instance.Builder.setFunctionMetaData(org.apache.pulsar.functions.proto.Function.FunctionMetaData.Builder) is not applicable
[ERROR]       (argument mismatch; lombok.val cannot be converted to org.apache.pulsar.functions.proto.Function.FunctionMetaData.Builder)
[ERROR] /private/tmp/apache-pulsar-20230804-76435-ra7wzu/apache-pulsar-3.0.1-src/pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java:[952,24] incompatible types: org.apache.pulsar.functions.proto.Function.Assignment cannot be converted to lombok.val
[ERROR] /private/tmp/apache-pulsar-20230804-76435-ra7wzu/apache-pulsar-3.0.1-src/pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java:[958,79] cannot find symbol
[ERROR]   symbol:   method getInstance()
[ERROR]   location: variable ass of type lombok.val
[ERROR] /private/tmp/apache-pulsar-20230804-76435-ra7wzu/apache-pulsar-3.0.1-src/pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java:[1092,45] incompatible types: java.lang.String cannot be converted to lombok.val
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project pulsar-functions-worker: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1212)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:199)
    at com.gradle.maven.cache.extension.d.c.a (SourceFile:26)
    at com.gradle.maven.cache.extension.d.n.a (SourceFile:23)
    at com.gradle.maven.cache.extension.d.h.a (SourceFile:28)
    at com.gradle.maven.cache.extension.d.m.a (SourceFile:27)
    at com.gradle.maven.cache.extension.d.a.c (SourceFile:115)
    at com.gradle.maven.cache.extension.d.a.a (SourceFile:61)
    at com.gradle.maven.cache.extension.d.e.a (SourceFile:27)
    at com.gradle.maven.cache.extension.d.l.a (SourceFile:17)
    at com.gradle.maven.cache.extension.d.d.a (SourceFile:42)
    at com.gradle.maven.cache.extension.d.b.a (SourceFile:26)
    at com.gradle.maven.cache.extension.d.f$1.run (SourceFile:35)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:29)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:26)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:66)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:59)
    at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:157)
    at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:59)
    at org.gradle.internal.operations.DefaultBuildOperationRunner.run (SourceFile:47)
    at com.gradle.maven.cache.extension.d.f.a (SourceFile:31)
    at com.gradle.maven.cache.extension.d.k.a (SourceFile:65)
    at com.gradle.maven.cache.extension.h.b.lambda$createProxy$0 (SourceFile:65)
    at jdk.proxy24.$Proxy97.execute (Unknown Source)
    at com.gradle.maven.scan.extension.internal.d.a.executeMojo (SourceFile:114)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pulsar-functions-worker
[DEBUG] Shutting down adapter factory; available factories [file-lock, rwlock-local, semaphore-local, noop]; available name mappers [discriminating, file-gav, file-hgav, file-static, gav, static]
[DEBUG] Shutting down 'file-lock' factory
[DEBUG] Shutting down 'rwlock-local' factory
[DEBUG] Shutting down 'semaphore-local' factory
[DEBUG] Shutting down 'noop' factory
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --version
/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
BuildError: Failed executing: mvn -X clean package -DskipTests -Pcore-modules
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Pull request closed without merging**
