### PR TITLE
mobile-shell 1.2.6_3

### LINKED ISSUE #5220: mobile-shell (mosh) fails with _clock_gettime error on 10.11.6 with Xcode 8
mosh compiles and runs, but when I try to connect to a server with an SSH key, it fails with "Symbol not found: _clock_gettime". The binary from https://mosh.org/#getting or building from source does not have this problem.

```
$ brew config

HOMEBREW_VERSION: 1.0.4-7-g6e57355
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6e5735565b9a31ec2b01e02a479a361189729c22
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 109939afe4af2dd8742cbc31af1bc2b0e04a6556
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/var/pyenv/shims/python => /usr/local/var/pyenv/versions/2.7.12/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_66, 1.7.0_45
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

```
$ mosh --version

mosh 1.2.6 [build mosh 1.2.6]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
$ mosh --ssh="ssh -i /Users/user/.ssh/id_rsa" root@1.2.3.4

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/mobile-shell/1.2.6_2/bin/mosh-client
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/mobile-shell/1.2.6_2/bin/mosh-client
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

### PR DESCRIPTION
**Pull request by yanokwa**
Fixes #5220 and updates homepage and url to new mosh website

### CODE REVIEW

**Comment by yanokwa** [comment]
Just to be transparent, I'm not sure I understand the implications of this change. I followed the example of other brew fixes for this issue and worst case, the [build logs](https://gist.github.com/yanokwa/17802c7ff700860ce0aa148f37de3890) suggest that the HAVE_MACH_ABSOLUTE_TIME and HAVE_GETTIMEOFDAY both exist and will be run in timestamp.cc.

**Comment by ilovezfs** [comment]
Since this is an Autotools based build, a more straightforward fix should be possible here. I'll take a look

**Comment by ilovezfs** [comment]
@yanokwa I'll reopen this and do you mind using this patch instead?
```
iMac-TMP:homebrew-core joe$ git diff
diff --git a/Formula/mobile-shell.rb b/Formula/mobile-shell.rb
index 58b934f..9713e7f 100644
--- a/Formula/mobile-shell.rb
+++ b/Formula/mobile-shell.rb
@@ -27,6 +27,8 @@ class MobileShell < Formula
   depends_on :perl => "5.14" if MacOS.version <= :mountain_lion
 
   def install
+    ENV["ac_cv_search_clock_gettime"] = "no"
+
     # teach mosh to locate mosh-client without referring
     # PATH to support launching outside shell e.g. via launcher
     inreplace "scripts/mosh.pl", "'mosh-client", "\'#{bin}/mosh-client"
```

**Comment by ilovezfs** [comment]
It should be wrapped in the ` if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"` guard as well as you had with the inreplace.

**Comment by ilovezfs** [comment]
@yanokwa perfect thanks. Also,
```
    # Reported 26 Sep 2016 https://github.com/Homebrew/homebrew-core/issues/5220 
```
That actually needs to be a link to an upstream report so that a proper fix can makes its way into a future release.

**Comment by ilovezfs** [comment]
@yanokwa upstream issues in this case should be reported here: https://github.com/mobile-shell/mosh/issues

Also, CC @cgull

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@yanokwa awesome, thanks. I'll :ship: it as soon as it's :green_apple:

**Comment by ilovezfs** [comment]
@yanokwa merged! and new bottles shipped! Thanks for your contribution to Homebrew and restoring this formula to good health. :tada:

**Pull request closed without merging**
