### PR TITLE
mednafen 1.24.1

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`  depends_on :macos => :sierra # needs clock_gettime`
that line is obsolete?

**Comment by EricFromCanada** [comment]
> that line is obsolete?

No, several other formulae have similar lines

**Comment by jonchang** [comment]
I'd like to keep this unmerged for now for new CI testing.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
NICE

**Pull request closed without merging**
