### PR TITLE
bash-completion@2 2.10

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by xeron** [comment]
@chenrui333 my bash completion is broken after this update. Even `brew` subcommands don't complete anymore.

**Comment by SMillerDev** [comment]
Did you try restarting your shell or sourcing your bashrc again?

**Comment by xeron** [comment]
Yes. Some completions work actually. Mostly from `$BREW_PREFIX/share/bash-completion/completions/`.

However what used to work and doesn't work anymore, at least what I use every day:

* git
* brew
* probably more

**Comment by xeron** [comment]
Ok found the problem. `bash-completion@2` notes tell:

```
==> bash-completion@2
Add the following to your ~/.bash_profile:
  [[ -r "/opt/brew/etc/profile.d/bash_completion.sh" ]] && . "/opt/brew/etc/profile.d/bash_completion.sh"

If you'd like to use existing homebrew v1 completions, add the following before the previous line:
  export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
```

However line about `BASH_COMPLETION_COMPAT_DIR` doesn't use `brew --prefix` so path could be incorrect on systems with non-default prefix. Note that previous line about `/opt/brew/etc/profile.d/bash_completion.sh` uses correct path.

**Comment by ryenus** [comment]
Possible to revert this until the linked issue gets fixed?

**Comment by yumitsu** [comment]
@xeron Do you really source `$(brew --prefix)/etc/profile.d/bash_completion.sh` __after__ exporting `BASH_COMPLETION_COMPAT_DIR`?

**Comment by xeron** [comment]
@yumitsu yes. I don't have any issues anymore after fixing `BASH_COMPLETION_COMPAT_DIR`. My current config is:

```
export BASH_COMPLETION_COMPAT_DIR="/opt/brew/etc/bash_completion.d"
[[ -r "/opt/brew/etc/profile.d/bash_completion.sh" ]] && . "/opt/brew/etc/profile.d/bash_completion.sh"
```

We should still fix `BASH_COMPLETION_COMPAT_DIR` formula note to use `#{etc}` instead of hardcoded path.

**Pull request closed without merging**
