### PR TITLE
Tintin 2.01.92

### PR DESCRIPTION
**Pull request by number5**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Please fix the failing test instead of removing it.

**Comment by number5** [comment]
@EricFromCanada I got the test passed on my MBP (macOS 10.14.6) but it failed all 3 jenkins build, any idea how can I fix this?

I'm running `brew test tintin --verbose` locally with following result:

```
λ brew test tintin --verbose                                                                                        [11-10 22:36]
Testing tintin
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191110-29228-4aj7zi.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tintin.rb --verbose
==> /usr/local/Cellar/tintin/2.01.92/bin/tt++ -e "#nop; #buffer write /private/tmp/tintin-test-20191110-29229-17wor8c/version.txt; #end;"

















                New Worlds Ateraan  -  http://www.ateraan.com

Ateraan is a world of Intensive Roleplaying offering many unique and powerful
guilds, races, politics, religion, justice, economy, and a storyline that is
dominantly player controlled and based on a novel. The game is based on a
Kingdom with fighters, merchants, mages, and thieves, and a fierce southern
state that has warriors, shaman, slaves, and servants. Ships rule the seas and
caravans travel the lands. With 100's of players and features like invasions,
ship creation, house building, clans, theaters, leatherball fields, and massive
events, the game is incredibly robust and diverse.

To connect to New Worlds Ateraan enter: #session nwa ateraan.com 4002

      ####################################################################
Goodbye from TinTin++       T I N T I N + +   2.01.92                    #
      #                                                                  #
      #                 The Kickin Tickin DikuMUD Client                 #
```

**Comment by EricFromCanada** [comment]
Something in the new version is preventing the command's output from being redirected to somewhere other than the console. Looking into it.

**Comment by number5** [comment]
> Something in the new version is preventing the command's output from being redirected to somewhere other than the console. Looking into it.

The new test is using tintin's command to write the output to file (`#buffer write`) I can get the file written with the output and the test passed on my local environment, but on jenkins it failed to write the file, is the testpath writable on jenkins?

**Comment by EricFromCanada** [comment]
Try: 
```
  test do
    touch testpath/"version.txt"    
    system bin/"tt++", "-e \"#nop; #log o #{testpath}/version.txt; #help greeting; #end;\""
    assert_match /#{version}/, File.read(testpath/"version.txt")
  end
```

**Comment by number5** [comment]
@EricFromCanada still failed :(

**Comment by EricFromCanada** [comment]
Not sure why the test can write to a file when run directly but not when run via `test-bot`. An alternative is to just have `shell_output` check its exit status:
```
  test do
    shell_output("#{bin}/tt++ -e \"#nop; #info system; #end;\"")
  end
```

**Comment by number5** [comment]
@EricFromCanada thanks, looks good now

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @number5 @EricFromCanada!!

**Pull request closed without merging**
