### PR TITLE
ansible: fix python@3.8 warnings

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR fixes python@3.8 warnings/errors reported in https://github.com/Homebrew/homebrew-core/pull/48645#issuecomment-574912306

I've patched the first one, for sorting out the seconds one I need more information, so putting "do not merge" for now

### CODE REVIEW

**Comment by gabrieljones** [comment]
how do I tell stale bot this is still an issue?

**Comment by dawidd6** [comment]
You just did.

**Comment by SMillerDev** [comment]
Preferably by contributing more fixes though. Stalebot is here for a reason. Activity should be more than people talking to stalebot

**Comment by apple4ever** [comment]
Can we get this in? I'm running Ansible and these warnings are peppering every task run, making it hard to read.

**Comment by SMillerDev** [comment]
No, it's broken

**Comment by apple4ever** [comment]
Yes I see. So can we get it fixed and then in?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Now it'll retest the formula so you can see the error. Once you make it build without errors you can make a pull request or post a patch here. Then it'll be reviewed whenever a volunteer has time and eventually be merged if it meets all standards.

**Comment by bayandin** [comment]
I still have no idea how to reproduce/fix this 
```
/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching. Some resources might leak.
warnings.warn('resource_tracker: process died unexpectedly, '
Traceback (most recent call last):
File "", line 1, in
ModuleNotFoundError: No module named 'multiprocessing.resource_tracker'
```

Let's get this merged to get rid of warnings

**Comment by apple4ever** [comment]
@bayandin Not sure, but I don't see that error with Ansible 2.9.4 (and FYI most recent in Homebrew because I believe this is preventing updating to 2.9.5, as when I did a `brew bump-formula-pr` it directed me here).

And thank you both for working on this.

**Comment by bayandin** [comment]
The patch is merged @apple4ever, you could update ansible now 👍

**Comment by apple4ever** [comment]
@bayandin Great thank you! This let me open up #50504 to update Ansible.

**Pull request closed without merging**
