### PR TITLE
curl-openssl: enable zstd

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by Bo98** [comment]
I'm not really convinced this is used on much web servers outside Facebook yet, but it does seem lightweight enough and will likely get some use eventually so I don't have a problem with merging it.

**Review by SMillerDev — APPROVED** [review]

**Review by Bo98 — APPROVED** [review]

**Comment by vszakats** [comment]
G. How could I forget to bump to revision... Will do ASAP.

**Comment by Bo98** [comment]
It's ok because I'm hoping to merge https://github.com/Homebrew/homebrew-core/pull/58274 in the next few days anyway.

Plus people who haven't already upgraded to 7.72 will get the new bottles anyway.

**Comment by vszakats** [comment]
@Bo98: Phew, thanks! Leaving it as-is then. Till then, it's easy to update via `brew uninstall` → `brew install`.

**Pull request closed without merging**
