### PR TITLE
geant4 10.6.1

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tschoonj** [comment]
@fxcoudert any thoughts on how to fix this? The build itself works fine but the test fails. I have tried unsetting SDKOOT and HOMEBREW_SDKROOT but doesn't seem to work... 😢

**Comment by equal-l2** [comment]
@tschoonj Judging from the test log, tests require to be built with C++11.

**Comment by tschoonj** [comment]
Nope that doesn't seem to fix it

**Comment by tschoonj** [comment]
@fxcoudert could you have a look at this if you have a moment?

Thanks!!

**Comment by Bo98** [comment]
Considering the logs have expired, what was the exact error you got?

**Comment by tschoonj** [comment]
I think it was a test failure. I rebased against origin/master and kicked off a new build.

**Comment by Bo98** [comment]
The include order is all wrong:

```
 <...> search starts here:
 /usr/local/Cellar/geant4/10.6.1/share/Geant4-10.6.1/examples/basic/B1/include
 /usr/local/include/Geant4
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
 /usr/local/opt/qt/lib/QtGui.framework/Headers
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers
 /usr/local/opt/qt/lib/QtCore.framework/Headers
 /usr/local/opt/qt/./mkspecs/macx-clang
 /usr/local/opt/qt/lib/QtWidgets.framework/Headers
 /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers
 /usr/local/opt/qt/lib/QtOpenGL.framework/Headers
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
 /usr/local/opt/qt/lib (framework directory)
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

In particular that `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include` appearing early on (it needs to be later on, probably after the c++ v1 stuff, or really not there at all).

I think the problem here is Geant4PackageCache.cmake located at `/usr/local/lib/Geant4-10.6.1/Geant4PackageCache.cmake`. It contains hardcoded paths like:

```
geant4_set_and_check_package_variable(EXPAT_INCLUDE_DIR "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include" PATH "Path to a file.")
```

The package cache can be disabled by passing `-DGEANT4_INSTALL_PACKAGE_CACHE=OFF` to CMake at build time. Try that out and see if everything works. [It appears that upstream also recommend this for us (page 19)](https://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/InstallationGuide/fo/Geant4InstallationGuide.pdf):

> Geant4 10.6 and newer use CMake Imported Targets to link to external dependencies such as CLHEP, avoiding direct hard-coding of paths into the Geant4 install. The package cache file is installed by default to retain the pre-10.6 behaviour for basic installs, and stores these paths for reuse.
> If you are packaging (e.g. rpm, deb, spack, Homebrew, etc) Geant4, you can set this option to `OFF` to disable install of the cache file and make the package _relocatable_. Your install of Geant4 will then rely on `CMAKE_PREFIX_PATH` and other variables used by CMake to refind any needed dependencies.

And indeed we should do that since there's some `/usr/local` hardcoding going on which we want to avoid.

**Comment by tschoonj** [comment]
Even with disabling the cache, the tests still fail.

I also tried passing the sysroot explicitly to cmake but that didn't seem to make a difference :-(

**Pull request closed without merging**
