### PR TITLE
minimal-racket 8.3

### PR DESCRIPTION
**Pull request by xxyzz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by xxyzz** [comment]
The build error on Monterey should be fixed by https://github.com/racket/racket/commit/3a8a7102abff334ee4e054c3597bebba32bda307, but it's not included in this release.

**Comment by carlocab** [comment]
This is linking with the macOS-provided `libcrypto` and `libssl` on Monterey

**Comment by carlocab** [comment]
We might need to add `-L#{Formula["openssl@1.1"].opt_lib` to `LDFLAGS` to try to convince this to link with Homebrew OpenSSL.

**Comment by xxyzz** [comment]
Why the openssl test passed on action `12-arm64` but failed on `12`?

**Comment by carlocab** [comment]
No idea 🤷

**Review by carlocab — APPROVED** [review]
This has no Monterey bottle currently, so it should be fine to merge this.

**Pull request closed without merging**
