### PR TITLE
xidel: use openssl@3

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Comment by SMillerDev** [comment]
@Homebrew/ops any idea why it can't update an existing version of the bottles?

**Comment by Bo98** [comment]
We have technically had Xidel rebuild 1 before before the formula was removed and revived again later. When the formula was readded a few months ago, it went back to rebuild 0 because that didn't exist since we only copied the latest builds from Bintray.

**Comment by SMillerDev** [comment]
@Bo98 any suggestions for a fix? Should I remove the old one?

**Comment by Bo98** [comment]
I think when we reintroduced it, it should have been added starting with `revision 1`. It still can be if you're fine with a revision bump.

**Comment by iMichka** [comment]
Yeah let's just revision bump this.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
