### PR TITLE
publish-commit-bottles: fix missing `then`

### PR DESCRIPTION
**Pull request by carlocab**
See https://github.com/Homebrew/homebrew-core/actions/runs/4478227760/jobs/7870736526.

### CODE REVIEW

**Review by dawidd6 — APPROVED** [review]
3rd time the charm?

**Comment by carlocab** [comment]
> 3rd time the charm?

Hopefully! 😄

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by dawidd6** [comment]
```
Run gh pr merge --auto 126206
--merge, --rebase, or --squash required when not running interactively

Usage:  gh pr merge [<number> | <url> | <branch>] [flags]

Flags:
      --admin            Use administrator privileges to merge a pull request that does not meet requirements
      --auto             Automatically merge only after necessary requirements are met
  -b, --body text        Body text for the merge commit
  -F, --body-file file   Read body text from file (use "-" to read from standard input)
  -d, --delete-branch    Delete the local and remote branch after merge
      --disable-auto     Disable auto-merge for this pull request
  -m, --merge            Merge the commits with the base branch
  -r, --rebase           Rebase the commits onto the base branch
  -s, --squash           Squash the commits into one commit and merge it into the base branch
  -t, --subject text     Subject text for the merge commit
  
Error: Process completed with exit code 1.
```

**Comment by carlocab** [comment]
Yup, on it.

**Pull request merged**
