### PR TITLE
PostgreSQL 9.6.0

### PR DESCRIPTION
**Pull request by ear**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

🎉 official release announcement: https://www.postgresql.org/about/news/1703/

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
`brew uses postgresql` things need their `revision`s increased.

**Comment by ear** [comment]
```
$ brew uses postgresql
check_postgres
citus
ephemeralpg
libpqxx
libzdb
osm2pgrouting
osm2pgsql
pex
pg_top
pgcli
pgloader
pgpool-ii
pgroonga
pgrouting
pldebugger
postgis
postgrest
psql2csv
psqlodbc
zabbix
```

Should I bump each and every one or only the ones that actually break, I don't know about most of these projects.

**Comment by MikeMcQuaid** [comment]
> Should I bump each and every one or only the ones that actually break?

Could start with just the ones that break.

**Comment by ear** [comment]
In cases like [osm2pgsql](https://github.com/Homebrew/homebrew-core/blob/master/Formula/osm2pgsql.rb) where does the `revision 1` need to appear? after *every* sha1?

**Comment by DomT4** [comment]
`revision`s should never live inside a block, they apply universally to a formula. In most cases:
```ruby
desc "SSL/TLS cryptography library"
homepage "https://openssl.org/"
url "https://www.openssl.org/source/openssl-1.0.2j.tar.gz"
sha256 "e7aff292be21c259c6af26469c7a9b3ba26e9abaaffd325e3dccc9785256c431"
revision 1
```

Where there's a `stable do` block preventing that:
```ruby
desc "OpenStreetMap data to PostgreSQL converter"
homepage "https://wiki.openstreetmap.org/wiki/Osm2pgsql"
revision 1

head "https://github.com/openstreetmap/osm2pgsql.git"
```

**Comment by ear** [comment]
Thank you, it was not super clear from the [wording](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#formulae-revisions)  in the cookbook.

**Comment by unklphil** [comment]
What is the status of this PR? What still needs to be done, and what can I do to help things along?

It's been five days without any interaction, and I'd really like to start using this.

**Comment by ear** [comment]
I am not sure. I have tried to see what the failed check is on the @BrewTestBot but I can't find it.

Could it be that the other formulae must be updated individually with different PRs instead of here as I tried to do above?

**Comment by MikeMcQuaid** [comment]
I'm going to rebuild the build as it timed out.

**Comment by ear** [comment]
OK! Links to the el cap errors:

- [ ] [citus](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8790/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_citus/) does not support pg 9.6
- [ ] [pgrouting](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8790/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_pgrouting/) depends on postgis that needs to be updated
- [ ] [pldebugger](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8790/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_pldebugger/) can't find a symbol
- [ ] [zabbix](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8790/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_zabbix/) can't find a symbol

I have removed the citus version bump but does it need some more special handling? (Move/depend on Homebrew-versions?)

Bumped postgis version. Tested on elcap. Should I remove the `bottle` block?

Not sure about the other two symbol errors.

**Comment by JanStevens** [comment]
Small googling and guessing:

- **pldebugger** does not support 9.6 yet, seems there is some activity to get it working but no official release yet. https://git.postgresql.org/gitweb/?p=pldebugger.git;a=summary
- **zabbix** no clue

**Comment by justinclift** [comment]
@ear For the citus one, it's probably going to depend on this: https://github.com/citusdata/citus/pull/850

Seems to be getting actively worked on, so might not be a long wait.

**Comment by jasonmp85** [comment]
What's the precedent here? The `citus` formula can be updated to point to `HEAD` for now, but we won't have 9.6 support until our next release (which isn't too far off, but we're not e.g. issuing a minor version just to add 9.6 support).

**Comment by MikeMcQuaid** [comment]
@jasonmp85 Generally: wait for new releases for everything until we upgrade `postgresql`. This isn't ideal, we realise.

**Comment by deepj** [comment]
Hello, PostgreSQL 9.6.1 has been released today (https://www.postgresql.org/about/news/1712/)

Is it possible to merge this PR? I get you need to keep some compatibility with other formulas. But I don't think this PR would be blocked due to them. There are other users who don't use any of them (like me). And it's a bit shame, they block this PR.

**Comment by jasonmp85** [comment]
@deepj, FWIW I much prefer installing PostgreSQL via this tap anyway: https://github.com/petere/homebrew-postgresql

**Comment by justinclift** [comment]
Looking at the citus issue again, it seems like PG 9.6 support is merged in now.  Haven't checked if that's made it's way into a release yet or not, nor looked at the others.

**Comment by jasonmp85** [comment]
@justinclift, it's in the `6.0.0-rc.1` tag, though that's not a "final" release yet.

**Comment by deepj** [comment]
@jasonmp85 Thank you help and your tip. But I'd prefer to use the core formulae than using an alternative taps.

**Comment by eagleflo** [comment]
It's been over a month now. This PR has 'in progress' label but it's not clear to me what is actually being done. What can I do to move things forward? Are we waiting for each broken dependent to release a new version?

Is it possible to move PostgreSQL 9.5 into https://github.com/Homebrew/homebrew-versions and have the remaining broken dependent formula depend on that instead?

Is it possible to move broken dependent formula with few users into https://github.com/Homebrew/homebrew-boneyard?

**Comment by JLHwung** [comment]
ping @ear @MikeMcQuaid @DomT4

**Comment by MikeMcQuaid** [comment]
> Are we waiting for each broken dependent to release a new version?

Yes or be otherwise fixed up or have the software that doesn't work with the new version moved to the homebrew/boneyard if it's not widely used. The tests need to be green and merge conflicts need to be fixed. Feel free to open your own PR to make progress on this.

> Is it possible to move PostgreSQL 9.5 into https://github.com/Homebrew/homebrew-versions and have the remaining broken dependent formula depend on that instead?

No.

> Is it possible to move broken dependent formula with few users into https://github.com/Homebrew/homebrew-boneyard?

Yes.

> ping @ear @MikeMcQuaid @DomT4

@JLHwung Don't do this, please. It's rude and doesn't add anything to the conversation. I was going to reply to @eagleflo when I got back from vacation (which I'm still on).

**Comment by JLHwung** [comment]
@MikeMcQuaid I am pretty sorry about that. I thought it sunk so I try to reach. This PR has hung for a month.

**Comment by MikeMcQuaid** [comment]
@JLHwung That's ok, thanks for the apology.

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/5381.

**Comment by justinclift** [comment]
@MikeMcQuaid Err.... should that be "6698" ?

**Comment by ilovezfs** [comment]
@justinclift fixed, thanks!

**Pull request closed without merging**
