### PR TITLE
k*: replace `plist` with `service` block

### PR DESCRIPTION
**Pull request by branchv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
See #79367

### CODE REVIEW

**Comment by branchvincent** [comment]
looks like this will need a `CI-long-timeout`

**Review by SMillerDev — DISMISSED** [review]

**Comment by branchvincent** [comment]
test failure: `connect: connection refused`

seems like a fluke, should we rerun it?

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Can you rebase these?

**Comment by branchvincent** [comment]
> Can you rebase these?

done! thanks for the reminder

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
