### PR TITLE
gnome-icon-theme: change built-time only symbols for dependecies

### PR DESCRIPTION
**Pull request by claucece**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@claucece can you please explain why this is needed?

**Comment by tschoonj** [comment]
I second @ilovezfs here: please explain why this is necessary. Did you run into trouble because of these dependencies being build-time only?

**Comment by claucece** [comment]
Hi, yes. 

A lot of functionalities of gtk will not show up, unless `icon-naming-utils` and `librsvg` are also installed. The majority of times when the person installing runs with the issue, it's only asked to install this formula, but still a lot of functionalities will not work. Most of them are due to not having installed `icon-naming-utils` and `librsvg`. Gtk.Spinner for example will not show up on Mac unless librsvg is installed. I thought it might be easier for the person installing this formula to have also `icon-naming-utils` and `librsvg`. I guess `gettext` and `gtk+3` can still be built-time only.

**Comment by tschoonj** [comment]
I agree that `librsvg` should probably a run-time dependency.

Apparently `icon-naming-utils` (https://github.com/GNOME/adwaita-icon-theme/commit/52330b92bb069c073e4f31577499745480ee973f) was dropped quite some time ago as dependency for this package, so that line should just be removed

**Comment by claucece** [comment]
@tschoonj ok, I will update. Thanks!

**Review by tschoonj — APPROVED** [review]
Thanks for putting the changes in!

**Comment by fxcoudert** [comment]
Thanks a lot @claucece for your contribution to Homebrew!

**Pull request merged**
