### PR TITLE
opencolorio 2.3.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
  using ::signbit;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace
  using ::fpclassify;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:323:9: error: no member named 'isfinite' in the global namespace
  using ::isfinite;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:324:9: error: no member named 'isinf' in the global namespace
  using ::isinf;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:325:9: error: no member named 'isnan' in the global namespace
  using ::isnan;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:326:9: error: no member named 'isnormal' in the global namespace
  using ::isnormal;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:327:9: error: no member named 'isgreater' in the global namespace
  using ::isgreater;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:328:9: error: no member named 'isgreaterequal' in the global namespace
  using ::isgreaterequal;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:329:9: error: no member named 'isless' in the global namespace
  using ::isless;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:330:9: error: no member named 'islessequal' in the global namespace
  using ::islessequal;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:331:9: error: no member named 'islessgreater' in the global namespace
  using ::islessgreater;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:332:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:333:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:339:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
  using ::abs;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/math.h:417:15: note: 'fabs' declared here
  extern double fabs(double);
                ^
```

**Comment by Bo98** [comment]
Mixing up various SDKs.

It seems to be happening in a vendored dependency. We should consider setting `-DOCIO_INSTALL_EXT_PACKAGES=NONE` so that it'll instead fail when it can't find a dependency.

**Comment by chenrui333** [comment]
```
  -- If your OpenImageIO's files are located in different root directory, please provide the OpenImageIO_ROOT where the include files are located.
  -- Could NOT find OpenEXR (minimum version: "3.0.5", recommended version: "3.1.5")
```

**Comment by SMillerDev** [comment]
Actual problems are here, not sure why though.
```console
  -- Could NOT find pystring (minimum version: "1.1.3", recommended version: "1.1.3")
  --    pystring_ROOT was: /opt/homebrew/opt/pystring 
  CMake Error at share/cmake/macros/ocio_handle_dependency.cmake:220 (message):
    pystring is required, will abort at the end.
  -- Could NOT find minizip-ng (minimum version: "3.0.6", recommended version: "3.0.7")
  CMake Error at share/cmake/macros/ocio_handle_dependency.cmake:220 (message):
    minizip-ng is required, will abort at the end.
```

**Comment by chenrui333** [comment]
gonna close it for now, and will open a new one for another try.

**Comment by chenrui333** [comment]
let me file an upstream issue about that too.

**Comment by chenrui333** [comment]
- https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1897

**Pull request closed without merging**
