### PR TITLE
cri-tools 1.24.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by badouralix** [comment]
@Porkepix the test failure likely comes from the change introduced in https://github.com/kubernetes-sigs/cri-tools/pull/889

The actual error shows that this piece of code is executed https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/pkg/kubelet/cri/remote/remote_runtime.go#L102-L129

I suggest we update the formula test as follow

https://github.com/Homebrew/homebrew-core/blob/3765b92808273da1b63e8003131f20cb1f5bf6e7/Formula/cri-tools.rb#L40-L43

```diff
- assert_match "context deadline exceeded", crictl_output 
+ assert_match "connect: no such file or directory", crictl_output 
```

Let me know if you want to recreate your pull request
Otherwise I can take care of it

**Comment by Porkepix** [comment]
Is there no way for people to reopen the PR? Because some other staled ones I tried to push changes before didn't result in the PR reopening :/

**Comment by badouralix** [comment]
> Is there no way for people to reopen the PR?

I'm not sure, I guess opening a new pull request can help gain traction on visibility and reviewability

**Comment by Porkepix** [comment]
On the other hand it also create more noise in searches, notifications and so on, right?

**Comment by badouralix** [comment]
That's a fair point, probably worth mentioning it to the homebrew core maintainers to get their input on the matter
This discussion should not prevent us to bump to cri-tools 1.24.0 though

**Comment by SMillerDev** [comment]
> Is there no way for people to reopen the PR?

Only as a maintainer or creator of the PR and since brew automation prohibits making duplicate PRs I think a lot of the PRs you opened and let expire will never be updated unless upstream complains.

**Comment by Porkepix** [comment]
> > Is there no way for people to reopen the PR?
> 
> Only as a maintainer or creator of the PR and since brew automation prohibits making duplicate PRs I think a lot of the PRs you opened and let expire will never be updated unless upstream complains.

So how, as the creator of the Pr, can I reopen it? Because I never found any way to reopen one, neither to use some of the tags. The result is that even if the branch is updated, it doesn't even rerun the CI on it.

**Comment by SMillerDev** [comment]
Labels are only for maintainers, but next to the comment button there is generally a reopen button

**Comment by Porkepix** [comment]
> Labels are only for maintainers, but next to the comment button there is generally a reopen button

That's what I thought I remembered from other repositories, but not here: 
Screenshot 2022-05-09 at 15 04 45

**Comment by chenrui333** [comment]
> @Porkepix the test failure likely comes from the change introduced in [kubernetes-sigs/cri-tools#889](https://github.com/kubernetes-sigs/cri-tools/pull/889)
> 
> The actual error shows that this piece of code is executed https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/pkg/kubelet/cri/remote/remote_runtime.go#L102-L129
> 
> I suggest we update the formula test as follow
> 
> https://github.com/Homebrew/homebrew-core/blob/3765b92808273da1b63e8003131f20cb1f5bf6e7/Formula/cri-tools.rb#L40-L43
> 
> ```diff
> - assert_match "context deadline exceeded", crictl_output 
> + assert_match "connect: no such file or directory", crictl_output 
> ```
> 
> Let me know if you want to recreate your pull request Otherwise I can take care of it

yeah, just came up with the same update in #101488 :)

**Pull request closed without merging**
