### PR TITLE
graph-tool 2.45

### PR DESCRIPTION
**Pull request by count0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by count0** [comment]
@BrewTestBot test this please.

**Comment by count0** [comment]
@danielnachun @carlocab @iMichka @Moisan @fxcoudert The test seems to be failing due to reasons unrelated to graph-tool... Any hints would be appreciated.

**Comment by SMillerDev** [comment]
No need to tag a bunch of maintainers, someone will get to your PR when they want to spend time on it.

As for the build failure, this is due to a pip bug so you'll have to wait for #102092 to fix that

**Review by branchv — APPROVED** [review]
thanks! @count0

**Pull request closed without merging**
