### PR TITLE
flow 0.47.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@gabelevi looks like there is a little problem with the version constraints:

```
flowtype needs to be installed.
[ERROR] flowtype.0.46.0 is not available because your system doesn't comply
        with ocaml-version >= "4.03.0" & ocaml-version < "4.04.0".
[NOTE] Pinning command successful, but your installed packages may be out of
       sync.
make: *** [all-homebrew] Error 66
```

**Comment by gabelevi** [comment]
Ah, yeah, in an effort to sync our `opam` file with opam-repository, we reverted a change in https://github.com/facebook/flow/commit/8a811a4b443ec545d89aa201d5ebcc254ae220e4 that was needed for the homebrew build.

I'll check to see if opam needs it. If not, I think we can just delete it from everywhere.

**Comment by gabelevi** [comment]
Ok, I've put up a PR to fix this (https://github.com/facebook/flow/pull/4024) and I'm getting it merged. I'll comment here when it lands.

If you like, feel free to abandon this PR, and I can put one up with the fix patched in. Sorry for the trouble!

**Comment by ilovezfs** [comment]
Thanks @gabelevi 

I'll close this one.

**Pull request closed without merging**
