### PR TITLE
go 1.15.4

### PR DESCRIPTION
**Pull request by qinxin0720**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dtrodrigues** [comment]
On all three platforms:
```
Error: 5 failed steps!
brew install --build-from-source charm
brew install --build-from-source cig
brew install --build-from-source octant
brew install --build-from-source terragrunt
brew install --build-from-source the_platinum_searcher
```

**Comment by chenrui333** [comment]
For terragrunt, #64096

**Comment by ivanovaleksey** [comment]
What is wrong with the code? It seems to be pretty standard version update but tests are failing unexpectedly.

**Comment by chenrui333** [comment]
will address these error builds separately, proceeding with a merge.
```
brew install --build-from-source charm
brew test --retry --verbose faas-cli
brew install --build-from-source octant
```

**Comment by chenrui333** [comment]
for charm, https://github.com/juju/charmstore-client/issues/218

**Pull request closed without merging**
