### PR TITLE
pypy 6.0.0

### PR DESCRIPTION
**Pull request by chuanconggao**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
```
[translation:ERROR] CompilationError: CompilationError(err="""
	/private/tmp/pypy-20180426-21417-57bc62/pypy2-v6.0.0-src/usession-release-pypy2.7-v6.0.0-0/platcheck_77.c:87:10: fatal error: 'openssl/comp.h' file not found
	#include <openssl/comp.h>
	         ^
	1 error generated.
	""")
```

Either that's a mistake or upstream now mandate `openssl@1.1` here. That header does not exist for releases/branches below 1.1.0.

**Comment by chuanconggao** [comment]
The header `openssl/comp.h` is indeed included in [source](https://bitbucket.org/search?q=repo%3Apypy%20openssl%2Fcomp.h&account=%7Bf122f6a4-9111-4431-9f88-884d8cedd194%7D) of both PyPy2-v6.0.0 and PyPy3-v6.0.0 at `rpython/rlib/ropenssl.py` at line 47.

I do not know why the pypy3 formula works without mandating `openssl@1.1`.

**Comment by DomT4** [comment]
> I do not know why the pypy3 formula #27109 works without mandating openssl@1.1.

No idea what's going on here either, to be honest.

> Edit - Just remembered something. Checking it out.

I forgot something which initially confused me. We build `openssl@1.1` with `no-zlib` rather than `no-comp`, but in 3e491e80c3259f5eac958ec753a278390e1977a6 set `no-comp` in the `openssl` formula, which apparently disables installing the header entirely.

I'm going to go ahead and guess we'll find this assumption in other places over time, but upstream should be checking whether or not OpenSSL was built with compression before assuming the header is available. In C I guess you'd do something like `#ifndef OPENSSL_NO_COMP` but I'm not sure how to achieve that in Python.

**Comment by ilovezfs** [comment]
Feel free to reopen when the issue has been resolved upstream!

**Comment by DomT4** [comment]
https://bitbucket.org/pypy/pypy/issues/2811/ropensslpy-incorrectly-assumes-presence-of

**Comment by iMichka** [comment]
FYI the bug is also in pypy2-v5.10.0, and `pypy` can not be rebuilt from source in brew. The bottles were probably built before the `nocomp` change in `openssl`.

Debian and arch have the comp.h file:
https://www.archlinux.org/packages/core/x86_64/openssl-1.0/files/
https://packages.debian.org/jessie/amd64/libssl-dev/filelist

@fxcoudert do you remember what was the rationale for the `nocomp` change in 3e491e80c32 ?

**Comment by fxcoudert** [comment]
Quoting https://github.com/Homebrew/homebrew-core/pull/23938:

> Disable unsafe TLS compression. `no-zlib` implies `no-comp`, but I think it's best to make our intent absolutely clear

**Comment by ilovezfs** [comment]
Debian is passing `no-zlib` without passing `no-comp`, which means they still get `comp.h`

Nonetheless, I don't think `pypy` should require comp.

**Comment by ilovezfs** [comment]
@DomT4 interestingly the problem is more than just the include. If I remove it from the array,
```
[c:writing] rpython_rtyper.c
[c:writing] rpython_rtyper_lltypesystem.c
[c:writing] rpython_rtyper_lltypesystem_1.c
[c:writing] rpython_rtyper_lltypesystem_2.c
[c:writing] rpython_rtyper_lltypesystem_3.c
[c:writing] rpython_rtyper_lltypesystem_4.c
[c:writing] rpython_rtyper_lltypesystem_module.c
[c:writing] rpython_tool.c
[c:writing] rpython_translator.c
[c:writing] rpython_translator_c.c
[translation:info] written: /private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/usession-release-pypy2.7-v6.0.0-0/testing_1/testing_1.c
[314bc] translation-task}
[translation:info] Compiling c source...
[314bc] {translation-task
starting compile_c
[platform:execute] make -j 8 in /private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/usession-release-pypy2.7-v6.0.0-0/testing_1
[platform:Error] implement_12.c:54727:14: error: incomplete definition of type 'struct comp_method_st'
[platform:Error]         l_v317422 = COMP_get_type(l_a0_401);
[platform:Error]                     ^             ~~~~~~~~
[platform:Error] ./common_header.h:225:36: note: expanded from macro 'COMP_get_type'
[platform:Error] #  define COMP_get_type(meth) (meth->type)
[platform:Error]                                ~~~~^
[platform:Error] /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:181:16: note: forward declaration of 'struct comp_method_st'
[platform:Error] typedef struct comp_method_st COMP_METHOD;
[platform:Error]                ^
[platform:Error] implement_12.c:54741:14: error: incomplete definition of type 'struct comp_method_st'
[platform:Error]         l_v317427 = COMP_get_name(l_a0_402);
[platform:Error]                     ^             ~~~~~~~~
[platform:Error] ./common_header.h:224:36: note: expanded from macro 'COMP_get_name'
[platform:Error] #  define COMP_get_name(meth) (meth->name)
[platform:Error]                                ~~~~^
[platform:Error] /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:181:16: note: forward declaration of 'struct comp_method_st'
[platform:Error] typedef struct comp_method_st COMP_METHOD;
[platform:Error]                ^
[platform:Error] 2 errors generated.
[platform:Error] make: *** [implement_12.o] Error 1
[platform:Error] make: *** Waiting for unfinished jobs....
[314de] translation-task}
[Timer] Timings:
[Timer] annotate                       ---  247.8 s
[Timer] rtype_lltype                   ---  520.0 s
[Timer] pyjitpl_lltype                 ---  622.0 s
[Timer] backendopt_lltype              ---   99.9 s
[Timer] stackcheckinsertion_lltype     ---  203.4 s
[Timer] database_c                     ---  215.8 s
[Timer] source_c                       ---  100.0 s
[Timer] compile_c                      ---   55.2 s
[Timer] ===========================================
[Timer] Total:                         --- 2064.1 s
[translation:info] Error:
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/goal/translate.py", line 318, in main
    drv.proceed(goals)
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/driver.py", line 554, in proceed
    result = self._execute(goals, task_skip = self._maybe_skip())
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/tool/taskengine.py", line 114, in _execute
    res = self._do(goal, taskcallable, *args, **kwds)
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/driver.py", line 278, in _do
    res = func()
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/driver.py", line 521, in task_compile_c
    cbuilder.compile(**kwds)
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/c/genc.py", line 346, in compile
    extra_opts)
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/platform/posix.py", line 242, in execute_makefile
    self._handle_error(returncode, stdout, stderr, path.join('make'))
   File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/platform/__init__.py", line 155, in _handle_error
    raise CompilationError(stdout, stderr)
[translation:ERROR] CompilationError: CompilationError(err="""
	implement_12.c:54727:14: error: incomplete definition of type 'struct comp_method_st'
	        l_v317422 = COMP_get_type(l_a0_401);
	                    ^             ~~~~~~~~
	./common_header.h:225:36: note: expanded from macro 'COMP_get_type'
	#  define COMP_get_type(meth) (meth->type)
	                               ~~~~^
	/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:181:16: note: forward declaration of 'struct comp_method_st'
	typedef struct comp_method_st COMP_METHOD;
	               ^
	implement_12.c:54741:14: error: incomplete definition of type 'struct comp_method_st'
	        l_v317427 = COMP_get_name(l_a0_402);
	                    ^             ~~~~~~~~
	./common_header.h:224:36: note: expanded from macro 'COMP_get_name'
	#  define COMP_get_name(meth) (meth->name)
	                               ~~~~^
	/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:181:16: note: forward declaration of 'struct comp_method_st'
	typedef struct comp_method_st COMP_METHOD;
	               ^
	2 errors generated.
	make: *** [implement_12.o] Error 1
	make: *** Waiting for unfinished jobs....
	""")
[translation] start debugger...
in get_rpath_flags, rel_libdirs is not fixed up ['/usr/local/Cellar/openssl/1.0.2o_1/lib', '/usr/lib']
> /private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/platform/__init__.py(155)_handle_error()
-> raise CompilationError(stdout, stderr)
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
    exitcode = 1
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/bin/rpython", line 20, in <module>
    main()
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/goal/translate.py", line 325, in main
    debug(True)
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/goal/translate.py", line 278, in debug
    pdb_plus_show.start(tb)
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/tool/pdbplus.py", line 442, in start
    fn(*args)
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/tool/pdbplus.py", line 25, in post_mortem
    self.interaction(t.tb_frame, t)
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/bootstrap/lib-python/2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/bootstrap/lib-python/2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "/private/tmp/pypy-20180510-52228-678j0j/pypy2-v6.0.0-src/rpython/translator/tool/pdbplus.py", line 29, in preloop
    raise NoTTY("Cannot start the debugger when stdout is captured.")
NoTTY: Cannot start the debugger when stdout is captured.
```

**Comment by DomT4** [comment]
> Nonetheless, I don't think pypy should require comp.

Agreed. If OpenSSL provide a legitimate way to not install the header, upstreams should be expected to handle that.

> If I remove it from the array

Thanks for checking this out. It'd been on my list to try and `inreplace` it out of existence temporarily and see what happened. Annoying that there's another underlying issue and it isn't that simple to resolve 🙃.

**Comment by ilovezfs** [comment]
@DomT4 as a stop-gap, I guess we could depend on the libressl formula since that hasn't been de-compat'd yet.

**Comment by DomT4** [comment]
@ilovezfs Is that going to mess with `reposurgeon` given it has both `pypy` and `python@2` deps, which would then be using different crypto backends?

**Comment by DomT4** [comment]
Sounds about right.

**Pull request closed without merging**
