### PR TITLE
superlu: explicitly enable shared library on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Backport of https://github.com/Homebrew/linuxbrew-core/pull/22309.

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
We can enable them for Mac too. You'll need to bump the revision for that too.

**Comment by danielnachun** [comment]
Okay, good point.  I should have asked about this earlier, but since I already merged this into Linuxbrew/core, what happens now when you do the merge?  Should I change the formula in Linxubrew/core to match this?

**Comment by iMichka** [comment]
The flag will probably be added twice, so we will have to do some cleanup. Either just after the merge, or later when looking at the diff between both repos.

**Review by iMichka — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
Can you bump the revision to 1 to ship the shared libs to our mac users too?

**Comment by danielnachun** [comment]
Whoops I forgot!  Done now.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
