### PR TITLE
erlang@21 21.3.8.21

### PR DESCRIPTION
**Pull request by gromgit**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~ No change in doc tarball.

Also removed patches that have since been incorporated upstream.

### CODE REVIEW

**Comment by carlocab** [comment]
Is the patch still needed? https://github.com/erlang/otp/pull/4524#issuecomment-782043757

**Comment by gromgit** [comment]
> Is the patch still needed? [erlang/otp#4524 (comment)](https://github.com/erlang/otp/pull/4524#issuecomment-782043757)

Nope. I was waiting for my (slow) Big Sur VM to finish the build & test before pushing that change.

**Comment by gromgit** [comment]
@carlocab , upstream says this release also enables Apple Silicon support, so please remove the "no ARM bottle" tag and let's see for sure. Thanks much!

**Comment by carlocab** [comment]
I think you need to remove the
```ruby
depends_on arch: :x86_64
```
to get this to build on ARM.

**Comment by gromgit** [comment]
> `depends_on arch: :x86_64`

Oh. :facepalm:

**Comment by carlocab** [comment]
Nope, no ARM yet:
```
make[3]: *** [../ebin/hipe_gensym.beam] Segmentation fault: 11
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [../ebin/hipe_consttab.beam] Segmentation fault: 11
```

**Comment by gromgit** [comment]
Argh, will be tied up this weekend. I'll set up a draft AS-only PR for this later, as I don't have AS hardware to test on.

**Pull request closed without merging**
