### PR TITLE
mosquitto 1.6.9

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
```
/tmp/mosquitto-20200229-2681-1b73mrs/mosquitto-1.6.9/lib/messages_mosq.c:22:10: fatal error: 'utlist.h' file not found
```

**Comment by Bo98** [comment]
Try `-DUSE_BUNDLED_DEPS=ON`.

**Comment by EricFromCanada** [comment]
Adding `-DWITH_BUNDLED_DEPS=ON` will fix it. ([This line](https://github.com/eclipse/mosquitto/blob/master/src/CMakeLists.txt#L67) is missing from `lib/CMakeLists.txt`.)

**Comment by Bo98** [comment]
Apologies - my typo for mentioning `USE` rather than `WITH`.

**Pull request closed without merging**
