### PR TITLE
triage(CI-linux-self-hosted): add sui

### PR DESCRIPTION
**Pull request by johnjmartin**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/pull/163308

### CODE REVIEW

**Comment by chenrui333** [comment]
there is some internal chat about the linux runner, so maybe need to hold off this PR.

**Review by p-linnane — APPROVED** [review]
I think we can merge this. We have no definite answer for the Linux runner yet.

**Comment by Bo98** [comment]
This one is for OOM anyway rather than disk space.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> This one is for OOM anyway rather than disk space.

yeah, I was mostly thinking of linux runner in general

**Pull request merged**
