### PR TITLE
subversion: build javahl on Apple Silicon

### PR DESCRIPTION
**Pull request by markphip**
This was initially disabled due to OpenJDK not
being available.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I verified that the JavaHL library works by using it via Subclipse in Eclipse.
Note there is a sqlite related problem with JavaHL that already exists on Intel
and also exists on Apple Silicon. This either came about with Big Sur or Homebrew 3.0
I am investigating options and will possibly submit a separate PR for that.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Thanks for your PR, @markphip.

Please bump the `revision` (either add `revision 1` or increment the `revision` right after `license`) so that users who have this installed get the updated version of the formula when they do `brew upgrade`.

**Comment by markphip** [comment]
ok, thanks @carlocab I was not sure if I was supposed to do that or not since this formula did not already have revision specified. I have added it to the formula.

**Comment by carlocab** [comment]
That's fine. Forgot to mention: please squash your commits together. Thanks!

**Comment by markphip** [comment]
Thanks for the help @carlocab

**Comment by carlocab** [comment]
Sorry, one last thing: let's put the `--with-jdk` and `--enable-javahl` flags back in the `args` array, reverting the relevant parts from this commit: https://github.com/Homebrew/homebrew-core/commit/41f685f68a8e41a6ea2c079892739a7ee3e6d780 (squash your changes again please, thanks)

**Review by carlocab — APPROVED** [review]
Thanks for your first contribution to Homebrew/core, @markphip.

BrewTestBot will merge this soon after the CI run is complete.

**Comment by moonfruit** [comment]
Why not build subversion Perl module for Apple Silicon?

**Comment by carlocab** [comment]
Does it work? It was deactivated in https://github.com/Homebrew/homebrew-core/commit/bdd7b9fbe387aefa9b6c8013e3458fb768882304 because it didn't at the time. But if you know it works, you are welcome to open a PR to enable it.

**Comment by markphip** [comment]
This is what removing sqlite dependency would look like: https://github.com/markphip/homebrew-core/commit/cf8b319f97eb22fdc968a1c81722f273adfe9294

**Comment by markphip** [comment]
@moonfruit I tried to remove the Intel conditions on the Perl bindings. It seems to build and install OK but when you run the tests it fails.

```
brew test subversion
==> Testing subversion
==> /opt/homebrew/Cellar/subversion/1.14.1_2/bin/svnadmin create test
==> /opt/homebrew/Cellar/subversion/1.14.1_2/bin/svnadmin verify test
==> /usr/bin/perl -e use SVN::Client; new SVN::Client()
Last 15 lines from /Users/markphip/Library/Logs/Homebrew/subversion/test.03.perl:
2021-05-10 10:26:58 -0400

/usr/bin/perl
-e
use SVN::Client; new SVN::Client()

Can't locate SVN/Client.pm in @INC (you may need to install the SVN::Client module) (@INC contains: /opt/homebrew/Cellar/subversion/1.14.1_2/lib/perl5/site_perl/5.30.2/darwin-thread-multi-2level /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.2 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
Error: subversion: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/bin/perl -e use\ SVN::Client;\ new\ SVN::Client()
```

**Comment by carlocab** [comment]
`subversion` has used brewed `sqlite` forever, and it's hard to say what the consequences of changing it will be. I'd be reluctant to make that change given that no one's really asking for it (since you have your own workaround).

Still, you may wish to open a PR so that it can be reviewed and discussed appropriately.

**Comment by markphip** [comment]
> `subversion` has used brewed `sqlite` forever, and it's hard to say what the consequences of changing it will be. I'd be reluctant to make that change given that no one's really asking for it (since you have your own workaround).
> 
> Still, you may wish to open a PR so that it can be reviewed and discussed appropriately.

I agree and I am also reluctant. I am a member of the Subversion PMC and the maintainer for Subclipse. I have already pinged some others from Subversion to see if they have any other ideas on better workarounds I could pursue or try to understand what has changed to cause the problem.

I would feel slightly more comfortable if this was limited to Big Sur where I can at least see that Apple is providing a fairly current version of sqlite in the OS. I have no idea what version is provided in Mojave and Catalina.

I will submit the PR. I just did not know if that was an acceptable way to start this conversation.

**Comment by Bo98** [comment]
> it's hard to say what the consequences of changing it will be.

There was some consistency issues where some dependents used system libs and some did not. That's no longer the case so I'm happy to just use system SQLite if it works.

**Comment by markphip** [comment]
Thanks @Bo98 .. I opened a new PR https://github.com/Homebrew/homebrew-core/pull/76970 so let's move the conversation over there.

**Comment by carlocab** [comment]
> I will submit the PR. I just did not know if that was an acceptable way to start this conversation.

Code changes are usually small and relatively isolated in Homebrew/core, so PRs are always our preferred means of discussion.

I suspect also that the issue you mention in https://github.com/Homebrew/homebrew-core/pull/76900#issuecomment-836739570 could be a bug in Eclipse, as it sounds like it is assuming the default library search path, but shouldn't be.

**Comment by moonfruit** [comment]
@markphip Sorry, I have no M1 chip MacBook, so I cannot know what's happened.

But according to the output you provide, I think you should find what's in `/opt/homebrew/Cellar/subversion/1.14.1_2/lib/perl5/site_perl/5.30.2/darwin-thread-multi-2level `. It seems there is no subversion perl module in that directory.
Maybe this path is not correct on Apple Silicon macOS.  Can you paste what you see in `/opt/homebrew/Cellar/subversion/1.14.1_2/lib/perl5/`, `/opt/homebrew/Cellar/subversion/1.14.1_2/lib/perl5/site_perl` and `/opt/homebrew/Cellar/subversion/1.14.1_2/lib/perl5/site_perl/5.30.2`

**Comment by markphip** [comment]
@moonfruit it looks like the issue is that the folder name that gets installed in that folder is `5.32.1` not `5.30.2` ?

**Comment by moonfruit** [comment]
This patch mostly applies to #76964 and will be solved there. If there are some problems, you can post there.

**Pull request closed without merging**
