### PR TITLE
swift 5.6.2

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew update-swift`. 🚀

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
> Created with `brew update-swift`. 🚀

What sorcery is this

**Comment by carlocab** [comment]
```
  python: error: Failed to locate 'python'.
```

**Comment by Bo98** [comment]
> What sorcery is this

https://gist.github.com/Bo98/81e18bc5f4c2a00bd809d21e018f5a9f

Doesn't have code for adding resources yet because that's only needed when 5.7 arrives.

**Comment by Bo98** [comment]
> ```
>   python: error: Failed to locate 'python'.
> ```

I guess my dreadful hack didn't work.

Maybe because I forgot about the execute permission.

**Comment by carlocab** [comment]
> Maybe because I forgot about the execute permission.

I wondered that too, but I don't think symlinks need execute permissions.

**Comment by Bo98** [comment]
Because python3 isn't actually a part of the OS, it looks like we're just totally confusing the `/usr/bin` stub which is probably shared among all tools and just takes the `$0` basename.

```
$ ln -s /usr/bin/python3 xcodeisconfused
$ ./xcodeisconfused
xcodeisconfused: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find xcodeisconfused 2> /dev/null' failed with exit code 17664: (null) (errno=Invalid argument)
xcode-select: Failed to locate 'xcodeisconfused', requesting installation of command line developer tools.
```

I guess I'll run it through `xcrun -find` first?

**Comment by carlocab** [comment]
```
❯ ln -s /usr/bin/python3 clang
❯ ./clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Heh.

**Comment by Bo98** [comment]
```
$ sha256sum /usr/bin/clang
803930eed139265f08bc70e006d8d63c0a5a86b08782cac03880f1ae4d471cf4  /usr/bin/clang
$ sha256sum /usr/bin/python3
803930eed139265f08bc70e006d8d63c0a5a86b08782cac03880f1ae4d471cf4  /usr/bin/python3
```

**Comment by Bo98** [comment]
Well 12-arm64's lasted longer than 3 minutes this time so I guess that worked and it should be safe for me to go sleep.

I don't anticipate any other issues. We even tested the macOS 12.3 SDK last time round since it fell under that time period where we stuck with 12.2 but updated the dev tools.

**Comment by carlocab** [comment]
> $ sha256sum /usr/bin/clang
> 803930eed139265f08bc70e006d8d63c0a5a86b08782cac03880f1ae4d471cf4  /usr/bin/clang
> $ sha256sum /usr/bin/python3
> 803930eed139265f08bc70e006d8d63c0a5a86b08782cac03880f1ae4d471cf4  /usr/bin/python3

They even have the same inode.
```
❯ stat -c '%i' /usr/bin/{clang,python3}
1152921500312779808
1152921500312779808
```
It's a bit of a shame that this breaks this neat little feature of `clang`:
```
❯ $(brew --prefix llvm)/bin/clang --version
Homebrew clang version 14.0.6
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
❯ ln -s $(brew --prefix llvm)/bin/clang arm64-apple-macos-clang
❯ ./arm64-apple-macos-clang --version
Homebrew clang version 14.0.6
Target: arm64-apple-macos
Thread model: posix
InstalledDir: /var/folders/kb/pf4wbfc512z47l56g5072l900000gn/T/tmp.RuSPknRakq/.
```

**Comment by Bo98** [comment]
Ah, our libxml2 icu4c change is causing issues:

```
/home/linuxbrew/.linuxbrew/include/libxml2/libxml/encoding.h:31:10: fatal error: 'unicode/ucnv.h' file not found
#include <unicode/ucnv.h>
         ^~~~~~~~~~~~~~~~
```

**Comment by carlocab** [comment]
> Or better yet, let's backport this: https://gitlab.gnome.org/GNOME/libxml2/-/commit/b66ce0bba83febe2f4d119097a0391f5d886c3b4

👍 patch applies with an offset. Though, it does patch `configure.ac`, which might upset the `Makefile`.

**Comment by Bo98** [comment]
I can make a custom patch which modifies `configure` instead. We don't need the patch for HEAD builds.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
