### PR TITLE
bmake 20210420

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
this `bmake` has been broken for 11 and 11-arm for quite a while.

**Comment by carlocab** [comment]
Can we report this upstream?

**Comment by chenrui333** [comment]
Definitely, somehow, I thought I reported in the upstream a while back. Let me report it again.

**Comment by chenrui333** [comment]
Reached out to `help@crufty.net`

**Comment by chenrui333** [comment]
Close the PR for now.

**Pull request closed without merging**
