### PR TITLE
zabbix: revision for postgresql

### PR DESCRIPTION
**Pull request by neutric**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Shipped! Thanks again @neutric 

So did you want to open PRs for dbt, pgcli, pgpool-ii, postgis, temporal_tables, and possibly libpqxx, too?

**Comment by neutric** [comment]
I can work on them a while later. Have to run some errands now. Local install from source for updated postgis is running. A PR for dbt is already open by someone else. I'd gladly leave libpqxx for you and see/learn how you switch that one to building from trunk.

**Comment by ilovezfs** [comment]
@neutric no problem. Take your time.

>how you switch that one to building from trunk.

Like this: https://github.com/Homebrew/homebrew-science/commit/dbaa4880770d69be108dc12d729ef5c8e41c6785

But we'll actually need to get a new release out of them or use one of those development versions from 2015.

**Comment by ilovezfs** [comment]
Looks like they have a pseudo release here: https://github.com/jtv/libpqxx/commit/23376d4c8c4f28335e7ed408f6b63d30fe954e17

**Pull request closed without merging**
