### PR TITLE
lua@5.3: revision bump to fix dylib & pc versioning

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Split from https://github.com/Homebrew/homebrew-core/pull/21282.

### CODE REVIEW

**Comment by ilovezfs** [comment]
2 of 4

**Comment by ilovezfs** [comment]
At some point the dylib thing needs to get upstreamed …

**Comment by DomT4** [comment]
Aye, indeed. It’s on my list. I seem to have adopted the Lua formulae over the years & unlike the Node stuff very few others have stepped forwards to help out.

**Comment by ilovezfs** [comment]
is macports doing the same patching?

**Comment by DomT4** [comment]
Slightly different way, but essentially, [yes](https://github.com/macports/macports-ports/blob/207dc39c3210c80ea3df9347cba1596d227a4b83/lang/lua/files/patch-Makefile-52.diff) and [yes](https://github.com/macports/macports-ports/blob/207dc39c3210c80ea3df9347cba1596d227a4b83/lang/lua/files/patch-src-Makefile-52.diff).

**Comment by ilovezfs** [comment]
#sad

**Comment by DomT4** [comment]
Aye. The ship has almost certainly sailed on ever getting 5.1 and 5.2 fixed but if someone upstreams it maybe we can get something in the next version of 5.3, maybe 😓.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:cookie:

**Pull request closed without merging**
