### PR TITLE
no version 6.22.04 listed on cern website

### PR DESCRIPTION
**Pull request by kkeefe**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please open an issue with Root to ask them what happened.

**Comment by henryiii** [comment]
Usually it's just slow updating, but this is longer than usual, IIRC anyway. I've poked the ROOT team on Mattermost.

**Comment by henryiii** [comment]
6.22.04 had a major bug, so was pulled and 6.22.06 will be announced in the near future.

**Comment by henryiii** [comment]
The only bug I know so far of doesn't affect homebrew, so I think/hope this is just fine to use for now.

**Pull request closed without merging**
