### PR TITLE
Revert "cmake: fix breaking build tree on version/revision bumps"

### LINKED ISSUE #198772: CMake doesn't find packages properly
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.4.6-45-g3b1d59d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3b1d59d8c4fbf8c0ba0c9752007ff27bec3bc8b3
Last commit: 26 hours ago
Core tap JSON: 23 Nov 21:45 UTC
Core cask tap JSON: 23 Nov 21:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Building a C++ project which depends on Eigen3 as well as on Ceres. It's reproducible on 2 different machines.

### What happened (include all command output)?

Running `cmake` on a project which finds Eigen3 before it finds Ceres results in an error.
```
CMake Error at /opt/homebrew/lib/cmake/Ceres/CeresConfig.cmake:89 (message):
  Failed to find Ceres - Found Eigen dependency, but the version of Eigen
  found () does not exactly match the version of Eigen Ceres was compiled
  with (3.4.0).  This can cause subtle bugs by triggering violations of the
  One Definition Rule.  See the Wikipedia article
  http://en.wikipedia.org/wiki/One_Definition_Rule for more details
Call Stack (most recent call first):
  /opt/homebrew/lib/cmake/Ceres/CeresConfig.cmake:204 (ceres_report_not_found)
  CMakeLists.txt:2 (find_Package)
```

### What did you expect to happen?

The same project used to build in previous Cmake versions.

Here is a minimal `CMakeLists.txt` which reproduces this error:
```
find_package(Eigen3)
find_package(Ceres)
```

This project works on the current upstream Cmake version, but fails with the above error on brew's Cmake. I've narrowed it down to the following patch:
d69d9821e263e4fcdcc114e44694f07e6524971e

Without this patch, the project builds and with it it doesn't. I suspect the reason is that it fails to find the `Eigen3Config.cmake` with the patch. Without the patch I can see in the `CMakeCache.txt` that the variable
```
//The directory containing a CMake configuration file for Eigen3.
Eigen3_DIR:PATH=/opt/homebrew/share/eigen3/cmake
```
is set. With the patch it is not set:
```
//The directory containing a CMake configuration file for Eigen3.
Eigen3_DIR:PATH=Eigen3_DIR-NOTFOUND
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# This formula works on the minimal CMakeLists.txt:
brew uninstall cmake; rm ./cmake.rb; wget https://raw.githubusercontent.com/Homebrew/homebrew-core/c893863cdc5766f3aaea2a54cb6fae61ac9caea4/Formula/c/cmake.rb && brew install ./cmake.rb
rm -rf build; mkdir build && cd build && cmake ..; cd ..

# This formula with the patch doesn't work:
brew uninstall cmake; rm ./cmake.rb; wget https://raw.githubusercontent.com/Homebrew/homebrew-core/961a45133d237882bb410cdf2b72384798d2ae7a/Formula/c/cmake.rb && brew install ./cmake.rb
rm -rf build; mkdir build && cd build && cmake ..; cd ..
```

### PR DESCRIPTION
**Pull request by akretz**
This backports https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9987 to 3.31.1

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can we use the patch that was merged upstream instead?

**Comment by akretz** [comment]
> Can we use the patch that was merged upstream instead?

That's possible. I've tried to apply the fix
https://github.com/Kitware/CMake/compare/87cb3036e59bf37f3e063c37ae0395ced9856cd0...0994bc7929289ba56f13cf8270312b9607ab80d1
directly on 3.31.1, but it failed with conflicts. So I've resolved them and pushed it onto my fork. I've also had to cherry-pick the helper function
Kitware/CMake@2503b43b6c8554e4d97ba723ef651012ed841510
which it depends on.

**Comment by akretz** [comment]
Actually, the upstream patch also fails on my minimal example of #198772, so I removed it again. The interesting thing is that exactly the same patch works when I build CMake not using brew. So right now the situation with regards to that minimal example is


|                     | 3.31.1 | 3.31.1 patched |
| ------------------- | ------ | -------------- |
| Build independently | ✅     | ✅             |
| Build brew formula  | ✅     | ❌             |

Probably @carlocab has a better insight on what is going on.

**Comment by carlocab** [comment]
> Actually, the upstream patch also fails on my minimal example of #198772, so I removed it again.

If I'm understanding this correctly: it seems like this needs to be reported upstream then. Because we can revert #197088 now, but that's just going to break again when upstream changes regarding symlink handling land in a CMake release.

Can you try building `cmake` from their `master` branch to double-check that you see the problem from #198772 there?

**Comment by akretz** [comment]
> Can you try building `cmake` from their `master` branch to double-check that you see the problem from #198772 there?

I have now built upstream `master` [^1] using `./bootstrap --prefix=/opt/homebrew/Cellar/cmake/master`. The situation with #198772 is as follows:
```bash
brew install cmake
cmake .. # fails
/opt/homebrew/bin/cmake .. # fails
/opt/homebrew/Cellar/cmake/3.31.1/bin/cmake .. # succeeds
brew unlink cmake
ln -s ../Cellar/cmake/master/bin/cmake /opt/homebrew/bin/cmake
cmake .. # succeeds
```
I have started from a clean build folder with each `cmake` invokation.

[^1]: (Kitware/CMake@51f43b61bcf99d6ba57ed3d9680790c698f0dfca)

**Comment by carlocab** [comment]
Great, can we backport https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9987?

**Comment by akretz** [comment]
> Great, can we backport https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9987?

I've done that now and put the diff inside the formula in this PR.

For some reason, this still fails on #198772 when I install it via brew. But when I build exactly the same status via
```
./bootstrap --prefix=/opt/homebrew/Cellar/cmake/master
make
make install
ln -s ../Cellar/cmake/master/bin/cmake /opt/homebrew/bin/cmake
```
it works. I'm not sure what brew is doing here that breaks it when I build via brew.

**Comment by akretz** [comment]
I have figured out what is happening now:
- The Eigen package provides an `Eigen3Config.cmake` as well as a deprecated `FindEigen3.cmake`
- Ceres doesn't play well with `FindEigen3.cmake`
- Previously, CMake's discovery algorithm found `Eigen3Config.cmake` to set the CMake variables accordingly
- Now, with CMake's algorithm starting from `/opt/homebrew/bin/cmake`, it finds `/opt/homebrew/share/cmake/Modules/FindEigen3.cmake` instead
- I didn't pass `--datadir` to the configure script on my build of CMake, so it still found `Eigen3Config.cmake`

So it's not an issue with CMake. I propose deleting
https://github.com/Homebrew/homebrew-core/blob/9a7cff21861ca4da4c44d56c871c2a6a4a1ecbf9/Formula/e/eigen.rb#L27
to fix this issue, because it has been deprecated by Eigen. The file has been deleted on their master branch.

@carlocab Is it okay if I open another PR for that one? Feel free to close or merge this PR.

**Comment by cho-m** [comment]
Partly an issue in Eigen as current Eigen installs both FindEigen3.cmake (module) and Eigen3Config.cmake (config). Modules should be removed in future - https://gitlab.com/libeigen/eigen/-/commit/f2984cd0778dd0a1d7e74216d826eaff2bc6bfab

CMake defaults to searching module before config. With realpath handling, this means it would only pick modules installed by CMake. After no longer resolving realpath, this means it picks up modules installed by other formulae and linked into `share/cmake/Modules` (like FindEigen3.cmake).

The problem is FindEigen3.cmake adds a default version number (2.91.0) which causes havoc in the package lookup.

Can see this by trying workarounds like:
```cmake
find_package(Eigen3 3.4.0)
```
```cmake
find_package(Eigen3 CONFIG)
```

**Comment by carlocab** [comment]
> I'm not sure what brew is doing here that breaks it when I build via brew.

That's because it isn't sufficient to symlink only `bin/cmake` to `HOMEBREW_PREFIX/bin` to replicate what `brew` is doing -- you need to symlink everything in `Cellar/cmake/master` into `HOMEBREW_PREFIX`. This will change the behaviour of CMake, as you've observed.

> Is it okay if I open another PR for that one?

This seems fine to me.

**Pull request closed without merging**
