### PR TITLE
rustup-init 1.24.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/wasm-pack/0.9.1/bin/wasm-pack new hello-wasm
[INFO]: Installing cargo-generate...
error: the `--vers` provided, `latest`, is not a valid semver version: cannot parse 'latest' as a semver

Error: Installing cargo-generate with cargo
Caused by: failed to execute `cargo install`: exited with exit code: 101
  full command: "cargo" "install" "--force" "cargo-generate" "--version" "latest" "--root" "/private/tmp/wasm-pack-test-20210427-44219-1rcl6q5/Library/Caches/.wasm-pack/.cargo-generate-cargo-install-latest"
Error: wasm-pack: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/wasm-pack/0.9.1/bin/wasm-pack new hello-wasm
```

**Comment by cho-m** [comment]
`wasm-pack` upstream issue https://github.com/rustwasm/wasm-pack/issues/907
Can probably ignore this test failure.

**Comment by akiekintveld** [comment]
Looks like Rustup 1.24.0 [got reverted to 1.23.1 due to a regression](https://blog.rust-lang.org/2021/04/27/Rustup-1.24.0.html). I've opened #76800 for Rustup 1.24.1 which fixes this regression.

**Comment by chenrui333** [comment]
relates to #76800

**Pull request closed without merging**
