### PR TITLE
cntlm: fix typo

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by p-linnane** [comment]
This typo is in upstream's code. I'll open a PR to fix it.

**Comment by p-linnane** [comment]
Upstream is on Sourceforge and hasn't responded in over 10 years, so adding the fix directly to the formula.

**Review by nandahkrishna — APPROVED** [review]

**Comment by nandahkrishna** [comment]
Actually, if we go ahead with this change and don't update the bottles, this will cause test failures when installing from the (old) bottles. On the other hand, I'm not sure if the change is worth discarding bottles for older macOSes. Any comments?

**Comment by chenrui333** [comment]
yeah, we dont want to discard the old bottles. so no-bottles label makes sense to me

**Comment by nandahkrishna** [comment]
> yeah, we dont want to discard the old bottles. so no-bottles label makes sense to me

In that case we probably want to drop these changes – the formula installed from the bottle would fail the test.

**Comment by p-linnane** [comment]
> In that case we probably want to drop these changes – the formula installed from the bottle would fail the test.

Do we really care about `brew test` failing on unsupported OS's? The actual function of the bottle isn't affected.

**Comment by nandahkrishna** [comment]
The test would fail on supported OSes too unless we update the bottle though, right? And if we di that we lose bottles for older OSes. While I agree they're unsupported, we should still try to support them on a best-effort basis.

**Comment by chenrui333** [comment]
> The test would fail on supported OSes too unless we update the bottle though, right? And if we do that we lose bottles for older OSes. While I agree they're unsupported, we should still try to support them on a best-effort basis.

I would say the typo fix is more forward compatible meaning, when we build the new bottle for the new OS, the runtime behavior would be different, while the existing bottles for the old OS would still carry the typos in runtime.

It is indeed a bit tricky. 😄

**Comment by carlocab** [comment]
I'd rather not patch software to fix small typos TBH. We can leave this be.

**Comment by p-linnane** [comment]
Opened #136059 to add a comment about the typo rather than patching in a fix.

**Pull request closed without merging**
