### PR TITLE
libosinfo: formula tweaks

### PR DESCRIPTION
**Pull request by ilovezfs**
- sort build dependencies to the top
- add linked library dependency gettext
- make gobject-introspection recommended instead of optional since it will be installed anyway
- remove the patch for "ld: unknown option" since it's been upstreamed
- fix indentation of the heredoc in the test

### CODE REVIEW

**Comment by DomT4** [comment]
Seems reasonable.

**Comment by ilovezfs** [comment]
CC @nijikon RE: #2688

**Comment by nijikon** [comment]
Based on the `gobject-introspection` change I think that this needs a revision bump.

**Comment by ilovezfs** [comment]
@nijikon Are you sure? The primary reason for the change is that configure treats it as opt-out not opt-in if gobject-instrospection is installed during the build, which it is:
```
checking for gobject-introspection... yes
```

**Comment by ilovezfs** [comment]
In other words, I think the bottles you shipped actually have introspection turned on, despite the fact that it's supposedly optional not recommended.

**Comment by nijikon** [comment]
@ilovezfs interesting, let's merge this 👍

**Comment by ilovezfs** [comment]
okie dokie

**Pull request closed without merging**
