### PR TITLE
harlequin: add mysql plugin

### PR DESCRIPTION
**Pull request by mfinelli**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Enables the `harlequin-mysql` plugin. I'll follow up for `harlequin-postgresql` and `harlequin-odbc`

### CODE REVIEW

**Comment by SMillerDev** [comment]
This will be deleted on the next update unless you also add them to https://github.com/Homebrew/homebrew-core/blob/master/pypi_formula_mappings.json

**Comment by mfinelli** [comment]
This complains because there is no setup.py (which is true), but a regular pip install works. Are there some other options that need to be set?

```  ==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install --verbose --no-deps --no-binary=:all: --ignore-installed --no-compile /private/tmp/harlequin--mysql-connector-python-20241201-17558-e3g4zn/mysql-connector-python-8.4.0
  Using pip 24.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)
  
  Notice:  A new release of pip is available: 24.2 -> 24.3.1
  Notice:  To update, run: /opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python -m pip install --upgrade pip
  ERROR: Directory '/private/tmp/harlequin--mysql-connector-python-20241201-17558-e3g4zn/mysql-connector-python-8.4.0' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
  ```

**Comment by branchvincent** [comment]
Looks like a broken sdist (it's [missing setup.py](https://inspector.pypi.io/project/mysql-connector-python/8.4.0/packages/78/b6/a6ee4697f95e4bc6f402dd12872ed467d5a1b2f4589079e5966ccb10a2fd/mysql-connector-python-8.4.0.tar.gz/) plus some other files), you can reproduce this with pip using `pip install --no-binary=:all: mysql-connector-python`

Do you mind filing a bug with https://github.com/mysql/mysql-connector-python? I pushed a workaround in the meantime

**Review by p-linnane — APPROVED** [review]

**Comment by mfinelli** [comment]
The github project doesn't have issues activated, but there is already a bug report for the main mysql project (which publishes the connector):  https://bugs.mysql.com/bug.php?id=113396

**Pull request merged**
