### PR TITLE
gobject-introspection 1.80.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
there is some `'GObject', version '2.0' not found` change which breaks lots of things.

**Comment by chenrui333** [comment]
> there is some `'GObject', version '2.0' not found` change which breaks lots of things.
> 
> https://gitlab.gnome.org/GNOME/gobject-introspection/-/releases/1.80.0
> 
> > Only allow loading GIRepository-2.0

https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/497

**Comment by chenrui333** [comment]
also rebase to refresh the build.

**Comment by chenrui333** [comment]
- https://discourse.gnome.org/t/dealing-with-glib-and-gobject-introspection-circular-dependency/18701/4

**Comment by cho-m** [comment]
Added some extra steps to `glib`. I did try building old and new copies of bottles to compare and it looks like only difference is new introspection files and formula file:
```console
❯ diffoscope old.glib--2.80.0_1.arm64_sonoma.bottle.1.tar.gz new.glib--2.80.0_1.arm64_sonoma.bottle.1.tar.gz --diff-context 0 --exclude 'glib/*/.brew/gl
--- old.glib--2.80.0_1.arm64_sonoma.bottle.1.tar.gz
+++ new.glib--2.80.0_1.arm64_sonoma.bottle.1.tar.gz
│   --- old.glib--2.80.0_1.arm64_sonoma.bottle.1.tar
├── +++ new.glib--2.80.0_1.arm64_sonoma.bottle.1.tar
│ ├── file list
│ │ @@ -3 +3 @@
│ │ --rw-r--r--   0        0        0     7062 2024-03-07 21:35:05.000000 glib/2.80.0_1/.brew/glib.rb
│ │ +-rw-r--r--   0        0        0     8476 2024-03-07 21:35:05.000000 glib/2.80.0_1/.brew/glib.rb
│ │ @@ -347,0 +348,8 @@
│ │ +drwxr-xr-x   0        0        0        0 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/
│ │ +-r--r--r--   0        0        0    24332 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/GIRepository-3.0.typelib
│ │ +-r--r--r--   0        0        0   227740 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/GLib-2.0.typelib
│ │ +-r--r--r--   0        0        0     2092 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/GLibUnix-2.0.typelib
│ │ +-r--r--r--   0        0        0     1912 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/GModule-2.0.typelib
│ │ +-r--r--r--   0        0        0    66628 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/GObject-2.0.typelib
│ │ +-r--r--r--   0        0        0   365000 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/Gio-2.0.typelib
│ │ +-r--r--r--   0        0        0    10180 2024-03-07 21:35:05.000000 glib/2.80.0_1/lib/girepository-1.0/GioUnix-2.0.typelib
│ │ @@ -404,0 +413,8 @@
│ │ +drwxr-xr-x   0        0        0        0 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/
│ │ +-rw-r--r--   0        0        0   397493 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/GIRepository-3.0.gir
│ │ +-rw-r--r--   0        0        0  3908443 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/GLib-2.0.gir
│ │ +-rw-r--r--   0        0        0    12135 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/GLibUnix-2.0.gir
│ │ +-rw-r--r--   0        0        0    63324 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/GModule-2.0.gir
│ │ +-rw-r--r--   0        0        0  1292511 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/GObject-2.0.gir
│ │ +-rw-r--r--   0        0        0  6175734 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/Gio-2.0.gir
│ │ +-rw-r--r--   0        0        0   103171 2024-03-07 21:35:05.000000 glib/2.80.0_1/share/gir-1.0/GioUnix-2.0.gir

```

**Review by krehel — APPROVED** [review]

**Pull request merged**
