### PR TITLE
activemq 5.18.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Release not announced yet:
https://activemq.apache.org/components/classic/download/
https://activemq.apache.org/news/

**Review by nandahkrishna — COMMENTED** [review]
Seems to have been announced now https://activemq.apache.org/activemq-5018000-release but the Downloads page hasn't been updated.

**Comment by ZhongRuoyu** [comment]
> Seems to have been announced now https://activemq.apache.org/activemq-5018000-release but the Downloads page hasn't been updated.

It's strange that the line below the title reads:

> This is an older release. To get the current release, please see the [download page](https://activemq.apache.org/components/classic/download).

My guess is that only the one listed on the download page counts as the latest; but it should be there before long.

**Comment by p-linnane** [comment]
It's listed as latest on the download page now.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
