### PR TITLE
vim: deprecate stdenv

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

Will fail until the PR at `homebrew/brew` is merged, but this shows what would be changed after that.

Ref: Homebrew/legacy-homebrew#43371.
Ref: Homebrew/brew#184.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Nice 👍

**Comment by DomT4** [comment]
It'll keep failing on CI until https://github.com/Homebrew/brew/pull/184 is merged, but will be fine after that. Addressed Martin's code comments there earlier, will address his thread comment shortly.

**Comment by DomT4** [comment]
Should pass now. It's back in the queue, when it'll reach the queue remains to be seen, but at some point.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Only failing on Yosemite:
```
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -DRUBY_VERSION=20 -o objects/if_ruby.o if_ruby.c
In file included from if_ruby.c:113:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^
```
❓❓❓

**Comment by DomT4** [comment]
Yeah, me and a Yosemite VM need to spend some time together. https://github.com/Homebrew/homebrew-core/pull/1046 is also failing on Yosemite. I'm coming to like Yosemite less and less as time goes on 🙈.

**Comment by mikemcquaid** [comment]
I'm wondering given what @ilovezfs has said before if we shouldn't just be using the latest/10.11 SDK on 10.10.

**Comment by ilovezfs** [comment]
The issue is not restricted to this PR, but this fixes it:
```
diff --git a/Formula/vim.rb b/Formula/vim.rb
index 6698a67..6b2d014 100644
--- a/Formula/vim.rb
+++ b/Formula/vim.rb
@@ -75,6 +75,7 @@ class Vim < Formula
       opts << "--with-luajit"
       opts << "--enable-luainterp"
     end
+ENV.append "CFLAGS", "-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15"
 
     # We specify HOMEBREW_PREFIX as the prefix to make vim look in the
     # the right place (HOMEBREW_PREFIX/share/vim/{vimrc,vimfiles}) for
vm1010:homebrew-core joe$
```

**Comment by MikeMcQuaid** [comment]
:shipit:?

**Comment by DomT4** [comment]
Want to do a little bit more testing locally to check it doesn't hate the new Perl release, but otherwise it's pretty much ready, yeah.

**Comment by DomT4** [comment]
Alright, merged. Let's see how that goes. Passed all CI and pretty thoroughly tested locally, so fingers crossed.

**Comment by ilovezfs** [comment]
:tada: :balloon: :rocket: :cake: :dancers:

**Comment by ilovezfs** [comment]
So how does a bottle sound now? *ducks*

**Comment by DomT4** [comment]
😆 Let's not bust open that debate just yet. Trying to get everyone to agree on how to move forwards with the `default_formula` situation wasn't fun.

**Comment by ilovezfs** [comment]
Given the existence of `--build-from-source`, those against a bottle have their work cut out for them to make the case now that it builds with superenv.

**Pull request closed without merging**
