### PR TITLE
llvm 7.0.0rc3 (devel)

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
Failures are unrelated to this PR.

**Comment by claui** [comment]
I managed to install this on a clean Sierra VM but got an error from `brew test`:

```
Vagrants-Mac:~ vagrant$ brew install -s --devel llvm
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
folly                                    node@8

==> Installing dependencies for llvm: libffi, cmake
==> Installing llvm dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.2.1.sierra.bottle.
######################################################################## 100.0%
==> Pouring libffi-3.2.1.sierra.bottle.tar.gz
==> Caveats
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

==> Summary
🍺  /usr/local/Cellar/libffi/3.2.1: 16 files, 297.0KB
==> Installing llvm dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.12.2.sierra.bottle.
==> Downloading from https://akamai.bintray.com/10/10dd90b3aedb656af4ef26f53ff62
######################################################################## 100.0%
==> Pouring cmake-3.12.2.sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.12.2: 2,417 files, 33.9MB
==> Installing llvm --devel
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/llvm-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/cfe-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/clang-tools-extra-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/openmp-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/libcxx-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/libunwind-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/lld-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/polly-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> Downloading https://prereleases.llvm.org/7.0.0/rc3/compiler-rt-7.0.0rc3.src.tar.xz
######################################################################## 100.0%
==> cmake -G Unix Makefiles /private/tmp/llvm-20180911-4923-1yj9kmt/llvm-7.0.0rc3.src -DCMAKE_C_FLAGS_RELEASE=-DN
==> make
==> make install
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH run:
  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/usr/local/opt/llvm/lib"
  export CPPFLAGS="-I/usr/local/opt/llvm/include"

==> Summary
🍺  /usr/local/Cellar/llvm/7.0.0rc3: 2,697 files, 1.4GB, built in 124 minutes 8 seconds
==> Caveats
==> libffi
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

==> cmake
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> llvm
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH run:
  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/usr/local/opt/llvm/lib"
  export CPPFLAGS="-I/usr/local/opt/llvm/include"

Vagrants-Mac:~ vagrant$ brew test llvm
Testing llvm
==> /usr/local/Cellar/llvm/7.0.0rc3/bin/llvm-config --prefix
==> /usr/local/Cellar/llvm/7.0.0rc3/bin/clang -L/usr/local/Cellar/llvm/7.0.0rc3/lib -fopenmp -nobuiltininc -I/usr
==> ./omptest
==> /usr/local/Cellar/llvm/7.0.0rc3/bin/clang++ -v -nostdinc -I/Library/Developer/CommandLineTools/usr/include/c+
==> ./testCLT++
==> /usr/local/Cellar/llvm/7.0.0rc3/bin/clang -v -nostdinc -I/usr/include test.c -o testCLT
==> ./testCLT
==> /usr/local/Cellar/llvm/7.0.0rc3/bin/clang++ -v -nostdinc -std=c++11 -stdlib=libc++ -I/Toolchains/XcodeDefault
Last 15 lines from /Users/vagrant/Library/Logs/Homebrew/llvm/test.04.clang++:
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/7.0.0rc3/bin
 "/usr/local/Cellar/llvm/7.0.0rc3/bin/clang-7" -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -faligned-alloc-unavailable -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 305 -v -nostdsysteminc -nobuiltininc -resource-dir /usr/local/Cellar/llvm/7.0.0rc3/lib/clang/7.0.0 -I /Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I /include -I /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include -I/usr/local/include -stdlib=libc++ -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /private/tmp/llvm-test-20180911-37295-1lto1mt -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.12.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -o /private/tmp/test-8c0768.o -x c++ test.cpp
clang -cc1 version 7.0.0 based upon LLVM 7.0.0 default target x86_64-apple-darwin16.7.0
ignoring nonexistent directory "/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include
 /usr/local/include
End of search list.
test.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:80:in `block in test'
	from /usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:29:in `each'
	from /usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:29:in `test'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: llvm: failed
undefined method `map' for nil:NilClass
Did you mean?  tap
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:363:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:13:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:13:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:78:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:399:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:57:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:80:in `block in test'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:29:in `test'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Vagrants-Mac:~ vagrant$
```

**Comment by claui** [comment]
Looks like [the `if build_libcxx?` subtest](https://github.com/Homebrew/homebrew-core/blob/cf1d034f031b4ae8f66a2c52102a7d8b157b8ed6/Formula/llvm.rb#L444-L455) belongs inside the `Xcode.installed?` block.
Would it make sense to fix that right away in this PR?

**Comment by commitay** [comment]
> Looks like the if build_libcxx? subtest belongs inside the Xcode.installed? block.

Nice catch!

> Would it make sense to fix that right away in this PR?

I'd open a separate PR.

**Comment by claui** [comment]
> I'd open a separate PR.

Fair enough.

**Review by claui — APPROVED** [review]

**Pull request merged**
