### PR TITLE
glibc: only bootstrap on Intel CPUs

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
> Error: can't modify frozen Resource
@Homebrew/brew what's this about?  `brew audit` directed me to put the resources inside an `on_intel` block instead of using `if Hardware::CPU.intel?` but now I get this error.

**Comment by carlocab** [comment]
Probably poor interaction between Homebrew/brew#13753 and the `SimulateSystem` code. CC @Bo98 @Rylan12

**Comment by Bo98** [comment]
Actually comes from `BrewedGlibcNotOlderRequirement`. I'm prepping a fix now.

**Comment by Bo98** [comment]
https://github.com/Homebrew/brew/pull/13791

**Comment by danielnachun** [comment]
@Bo98 did you mean to close this without merging?  I can reopen if needed.

**Comment by Bo98** [comment]
No sorry, didn't mean to tag it as closing this.

**Comment by danielnachun** [comment]
This is ready to go.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Does this need a new brew tag before being merged?

**Comment by Bo98** [comment]
No, the mentioned bug is not present in the latest tag. And unrelated to these changes for that matter.

**Review by Bo98 — APPROVED** [review]
Will test this on a Pi later if I can find one lying somewhere. This can be merged now though.

**Pull request merged**
