### PR TITLE
jpeg-turbo 3.0.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
Failed on macOS 12 with
>   565/590 Test #541: djpeg12-static-3x2-float-prog-cmp ...................***Failed    0.00 sec
  testout12-static_3x2_float.ppm: FAILED.  Checksum is 42876ab9e5c2f76a87d08db5fbd57956

**Comment by chenrui333** [comment]
also failed on 12-arm

```
  The following tests FAILED:
  	246 - djpeg12-shared-3x2-float-prog-cmp (Failed)
  	541 - djpeg12-static-3x2-float-prog-cmp (Failed)
  Errors while running CTest
```

**Comment by chenrui333** [comment]
rerun

**Comment by chenrui333** [comment]
https://github.com/libjpeg-turbo/libjpeg-turbo/issues/734

**Pull request closed without merging**
