### PR TITLE
fswatch: add pkg-config libfswatch.pc file

### PR DESCRIPTION
**Pull request by bcardiff**
This will simplify linking libfswatch via pkg-config.

### CODE REVIEW

**Review by SMillerDev — COMMENTED** [review]
Please use a patch block integrating the commit from upstream instead of writing it again here

**Comment by bcardiff** [comment]
Done @SMillerDev

**Comment by bcardiff** [comment]
I'm not sure why the CI complains. Locally, I am able to build the formula from source.

**Comment by bcardiff** [comment]
I would need a bit of guidance to understand why I can build the formula from source but the CI fails to build the bottle.

```
==> ./configure CONFIG_SHELL=/bin/bash --prefix=/usr/local/Cellar/fswatch/1.14.0 --disable-dependency-tracking --disable-silent-rules
./configure: line 2991: syntax error near unexpected token `$SHELL'
./configure: line 2991: `$SHELL "$ac_aux_dir/config.sub" sun4 >/dev/null 2>&1 ||'
```

Otherwise I can rollback these changes and submit the original patch that generates only the .pc file.

**Comment by SMillerDev** [comment]
What do you use to build from source locally?

**Comment by bcardiff** [comment]
`$ brew reinstall --build-from-source Formula/fswatch.rb` from my working copy with this PR

**Comment by SMillerDev** [comment]
Did you install using `--HEAD` before?

**Comment by bcardiff** [comment]
There is no `def head` in this formula.

If I add is, with none of the changes in this PR so far I got some errors

```
  head do
    url "https://github.com/emcrisostomo/fswatch.git"
  end
```

<details>
  <summary>Error output</summary>

```
$ brew install --build-from-source Formula/fswatch.rb --HEAD
==> Cloning https://github.com/emcrisostomo/fswatch.git
Updating /Users/bcardiff/Library/Caches/Homebrew/fswatch--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 6acf477 Replace OS X with macOS
==> ./configure --prefix=/usr/local/Cellar/fswatch/HEAD-6acf477
Last 15 lines from /Users/bcardiff/Library/Logs/Homebrew/fswatch/01.configure:
2020-06-29 11:30:41 -0300

./configure
--prefix=/usr/local/Cellar/fswatch/HEAD-6acf477
--disable-dependency-tracking
--disable-silent-rules


Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
        23: from /usr/local/Homebrew/Library/Homebrew/build.rb:202:in `<main>'
        22: from /usr/local/Homebrew/Library/Homebrew/build.rb:118:in `install'
        21: from /usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
        20: from /usr/local/Homebrew/Library/Homebrew/build.rb:123:in `block in install'
        19: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1166:in `brew'
        18: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2141:in `stage'
        17: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
        16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:81:in `stage'
        15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:106:in `unpack'
        14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:196:in `mktemp'
        13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
        12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
        11: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
        10: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `block in mktemp'
         9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:111:in `block in unpack'
         8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2166:in `block in stage'
         7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
         6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2167:in `block (2 levels) in stage'
         5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1173:in `block in brew'
         4: from /usr/local/Homebrew/Library/Homebrew/build.rb:152:in `block (2 levels) in install'
         3: from /Users/bcardiff/Projects/crystal/homebrew-core/Formula/fswatch.rb:32:in `install'
         2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1962:in `system'
         1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1962:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2024:in `block in system': Failed executing: ./configure --prefix=/usr/local/Cellar/fswatch/HEAD-6acf477 --disable-dependency-tracking --disable-silent-rules (BuildError)
        5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:45:in `<main>'
        4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:151:in `rescue in <main>'
        3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:413:in `dump'
        2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:359:in `issues'
        1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:363:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:296:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```
</details>

Adding build dependencies and adding autoreconf make things work for me locally.

```
  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "gettext" => :build
  depends_on "libtool" => :build

  def install
    ENV.cxx11
    system "autoreconf", "--install"
    system "./configure", "--prefix=#{prefix}",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules"
    system "make", "install"
  end
```

Which is one of the configuration that failed with just the patch. But, again, it also worked locally. The `CONFIG_SHELL` override didn't seem to change a thing for the CI.

**Comment by bcardiff** [comment]
Sorry, but I am out of ideas. From wanting to add the .pc file this is turning into support fswatch head.

I am not proficient with autotools nor with how bottles are built

@emcrisostomo / @SMillerDev do you have any ideas I could try?

**Comment by gromgit** [comment]
Late to the party, so I might be missing a lot of context. Still, I can safely say that your patch is b0rked:
```
+PKG_INSTALLDIR()
```
should be:
```
+PKG_INSTALLDIR
```
Also, I suspect your local build stubbornly succeeds because your fornula doesn't run `autoconf` to regenerate the configure script (required since you patch modifies `configure.ac`), so it's still running the original upstream script. If it had, it would've failed in exactly the same way as the CI build.

Dunno if that's the only problem, but this should at least get you past this roadblock.

**Comment by emcrisostomo** [comment]
I agree with @gromgit analysis: `autogen.sh` is failling in those builds.
I've released the `pkg-config` feature upstream, in [1.15.0](https://github.com/emcrisostomo/fswatch/releases/tag/1.15.0).

**Comment by SMillerDev** [comment]
Closing this since there's a PR for the update. Thanks @emcrisostomo and @bcardiff

**Comment by bcardiff** [comment]
Thanks for the analysis. I'm happy to see the new version of fswatch available.

**Pull request closed without merging**
