### PR TITLE
erlang 23.0

### PR DESCRIPTION
**Pull request by thelightcosine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
`resource "man"` and `resource "html"` should be updated as well

**Comment by thelightcosine** [comment]
@bayandin Done

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
actually, we might need a legacy formula for the erlang@22.x

**Comment by SMillerDev** [comment]
I'd really rather we only make versioned formula when there's demand rather than for any update.

**Comment by bayandin** [comment]
I've created a PR which will run tests on all erlang-dependant formula. 
It should help us to decide if we need a versioned formula right now: 
https://github.com/Homebrew/homebrew-test-bot/pull/399

**Comment by bayandin** [comment]
Changes to homebrew-test-bot have been merged.
I've deleted versioned formula to retrigger CI (sorry @chenrui333, will revert it back if needed)

**Comment by bayandin** [comment]
```
Error: 6 failed steps!
brew install --build-from-source couchdb
brew install --build-from-source ejabberd
brew install ejabberd
brew test --verbose rabbitmq
brew install --build-from-source wrangler
brew install --build-from-source yaws
```

**Comment by Bo98** [comment]
* `couchdb` needs `erlang@22`: `ERROR: OTP release 23 does not match required regex 19|20|21|22`
* `ejabberd` needs `erlang@22`: `library not found for -lerl_interface` ("The old legacy erl_interface library (functions with prefix erl_) is deprecated as of OTP 22, and will be removed in OTP 23. This does not apply to the ei library.")
* `rabbitmq` needs investigating. 3.8.3 was supposed to work with OTP 23.
* `wrangler` needs `erlang@22`: same error as `ejabberd`
* `yaws` fails on a deprecation warning: erlyaws/yaws#401 - can be patched to stop treating warnings as errors or it can use `erlang@22`.

**Comment by bayandin** [comment]
`ejabberd` conflicts with `couchdb`:
```
The formula built, but is not symlinked into /usr/local
Could not symlink lib/jiffy-1.0.4/ebin/jiffy.app
Target /usr/local/lib/jiffy-1.0.4/ebin/jiffy.app
is a symlink belonging to couchdb. You can unlink it:
  brew unlink couchdb

To force the link and overwrite all conflicting files:
  brew link --overwrite ejabberd

To list all files that would be deleted:
  brew link --overwrite --dry-run ejabberd

Possible conflicting files are:
/usr/local/lib/jiffy-1.0.4/ebin/jiffy.app -> /usr/local/Cellar/couchdb/3.1.0_1/lib/jiffy-1.0.4/ebin/jiffy.app
/usr/local/lib/jiffy-1.0.4/ebin/jiffy.beam -> /usr/local/Cellar/couchdb/3.1.0_1/lib/jiffy-1.0.4/ebin/jiffy.beam
/usr/local/lib/jiffy-1.0.4/ebin/jiffy_utf8.beam -> /usr/local/Cellar/couchdb/3.1.0_1/lib/jiffy-1.0.4/ebin/jiffy_utf8.beam
/usr/local/lib/jiffy-1.0.4/priv/jiffy.so -> /usr/local/Cellar/couchdb/3.1.0_1/lib/jiffy-1.0.4/priv/jiffy.so
```

**Comment by bayandin** [comment]
It's green now 🎉

**Review by Bo98 — APPROVED** [review]

**Comment by bayandin** [comment]
Thanks @thelightcosine!

**Comment by michaelklishin** [comment]
FTR, the only [known incompatibility with Erlang 23](https://groups.google.com/forum/#!topic/rabbitmq-users/wlPIWz3UYHQ) in RabbitMQ `3.8.3` is around a memory allocator metric format change that breaks `rabbitmq_prometheus`. This has been addressed for `3.8.4` which should ship in about a week.

**Pull request closed without merging**
