### PR TITLE
jfrog-cli-go 1.6.0

### PR DESCRIPTION
**Pull request by eyalbe4**
- [yes ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [yes ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [yes ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [yes ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
1.6.0 is not designated as a release by upstream.

**Comment by eyalbe4** [comment]
@ilovezfs, can you please explain what you mean by "not designated as a release by upstream"?

**Comment by ilovezfs** [comment]
@eyalbe4 oh, sure. Take a look at https://github.com/JFrogDev/jfrog-cli-go/releases.

Feel free to prod upstream to see if they're ready to designate 1.6.0 as the latest release.

**Comment by eyalbe4** [comment]
@ilovezfs, 1.6.0 is now the latest release. Please let me know if anything else is needed. Thanks.

**Comment by ilovezfs** [comment]
@eyalbe4 thanks

**Comment by ilovezfs** [comment]
@eyalbe4 :rocket: thanks for the upgrade!

**Pull request closed without merging**
