### PR TITLE
deno 1.38.2

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
`  Minitest::Assertion: No linkage with libsqlite3.dylib! Cargo is likely using a vendored version.`

**Comment by mmastrac** [comment]
We added a new reference to sqlite in the `denokv_sqlite` crate which is likely breaking the unvendoring script. Unvendoring sqlite fully may require editing Cargo.lock rather than Cargo.toml, but we can take some patches upstream to help unvendor.

**Comment by chenrui333** [comment]
@mmastrac happy to try out any build patch.

**Comment by mmastrac** [comment]
@chenrui333  I finally figured out what the probable fix is:

Can you try patching this? We can probably fix it by 1.38.2.

```
    inreplace "Cargo.toml",
              /^denokv_sqlite = "0.2.1"$/,
              'denokv_sqlite = { default-features = false, "0.2.1" }'
```

**Comment by mmastrac** [comment]
@ZhongRuoyu 

With some changes we made in this most recent release, you probably need to add `--no-default-features` to the cargo build flags. This should hopefully get us past the release problems.

**Comment by ZhongRuoyu** [comment]
Looks like it built fine. Thanks for your help @mmastrac!

**Comment by mmastrac** [comment]
@ZhongRuoyu Great, thanks for getting it working! I'm going to see what we can do to make the build easier for the future.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
