### PR TITLE
grafana 8.3.6

### PR DESCRIPTION
**Pull request by marefr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by branchv — DISMISSED** [review]
Thanks @marefr

**Comment by marefr** [comment]
> warning Bottle publish [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1847414231).

Looking at the output of the failure I have no idea. Any ideas if this is on us or on you?

**Review by SMillerDev — DISMISSED** [review]
That definitely looks like a brew issue, let's try again

**Comment by SMillerDev** [comment]
@Homebrew/ops any ideas?

**Comment by carlocab** [comment]
I think this happened in the mariadb PR too

**Comment by Bo98** [comment]
Still looking into it. I think it might be a Monterey bug but I’ll narrow it down more.

**Pull request closed without merging**
