### PR TITLE
mongodb 3.6.0, mongodb@3.4 3.4.10 (new formula)

### PR DESCRIPTION
**Pull request by Ben305**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
The @3.4 should be in a separate commit with commit subject `mongodb@3.4 3.4.10 (new formula)`, shouldn't have a bottle block since it's a new formula, and should be `keg_only :versioned_formula`

**Comment by Ben305** [comment]
@ilovezfs Thanks for your feedback, I've updated my branch now.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @Ben305! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
