### PR TITLE
libgsm 1.0.20

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
patch needs to be updated

**Comment by chenrui333** [comment]
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
  can't find file to patch at input line 3
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |--- a/configure
  |+++ b/configure
  --------------------------
  No file to patch.  Skipping patch.
  1 out of 1 hunk ignored

**Comment by carlocab** [comment]
Alternatively, remove the patch.

**Review by carlocab — APPROVED** [review]

**Comment by Jerry1144** [comment]
Apparently the resource file has been modified. Can you confirm this?
```
==> Downloading http://www.quut.com/gsm/gsm-1.0.20.tar.gz
Already downloaded: /Users/-------/Library/Caches/Homebrew/downloads/2dad12c11dd1c8873d7ccc3fb6b89afa710c351e45f760a3d474ba2001c02213--gsm-1.0.20.tar.gz
Error: SHA256 mismatch
Expected: b0e6cf4d5ac81387cf74cbe431f77302db3b2f62fc7cb5e21a5670ac30963979
  Actual: 6315c38518b81e899c3fc2ed463cc623af29c5c231a48c137b24302234ae90bf
    File: /Users/-------/Library/Caches/Homebrew/downloads/2dad12c11dd1c8873d7ccc3fb6b89afa710c351e45f760a3d474ba2001c02213--gsm-1.0.20.tar.gz
To retry an incomplete download, remove the file above.
```
I retried a few times by `rm`-ing the files, but the SHA256 is not changing. The download is not in HTTPS so no way to verify if this is a Man-in-the-Middle attack. Thus I pledge you, looking from other parts of the world, to see if the SHA256 truly has changed.

**Comment by carlocab** [comment]
I get the same checksum that you're getting: `6315c38518b81e899c3fc2ed463cc623af29c5c231a48c137b24302234ae90bf`

Please ask upstream about the change in the tarball checksum.

**Pull request closed without merging**
