### PR TITLE
tarantool 1.7.5.101

### PR DESCRIPTION
**Pull request by bigbes**
Added libcurl dependency

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Added libcurl dependency

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can't this build with system curl?

**Review by ilovezfs — CHANGES_REQUESTED** [review]
@bigbes agreed with @fxcoudert. This should be able to use the macOS system provided libcurl and not depend on the duplicate curl formula.

**Comment by bigbes** [comment]
It can use system one, but limitations with system keychain are not good: https://mackyle.github.io/git-osx-installer/iscurlsick.html
+
```
* WARNING: SSL: CURLOPT_SSLKEY is ignored by Secure Transport. The private key must be in the Keychain.
* WARNING: SSL: The Security framework only supports loading identities that are in PKCS#12 format.
```
+
etc

**Comment by ilovezfs** [comment]
Nonetheless, please use the system version.

**Comment by bigbes** [comment]
Maybe option is compromise?

**Comment by ilovezfs** [comment]
Nope, we don't depend on system duplicates.

**Comment by bigbes** [comment]
We already depends on openssl, which is system duplicate. And a lot of packages uses `openssl` package it too.

**Comment by ilovezfs** [comment]
See discussion on that here: https://github.com/Homebrew/brew/blob/97c75bfd40084cfa2512fe55a7b292886ff6d023/docs/Formula-Cookbook.md#check-for-dependencies

**Comment by bigbes** [comment]
Thank you, Formula Cookbook was evolved since last time I've read it.
As an example I'll show [`git` brewspec](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb#L34):

```
option "with-curl", "Use Homebrew's version of cURL library"
```

Sorry for my behaviour (someone may call it altercation/dispute), but it's important for us

**Comment by ilovezfs** [comment]
I'm well aware of the options in the git formula. Please remove the curl dependency.

**Comment by ilovezfs** [comment]
@bigbes what's the status here?

**Comment by bigbes** [comment]
Sorry, @ilovezfs. Problem is:
```
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/1.7.5
Last 15 lines from /Users/blikh/Library/Logs/Homebrew/tarantool/01.cmake:
-- Looking for getprogname - found
-- Tarantool version is 1.7.5-101-g622c4bc (1.7.5.101)
-- Lua package.path: /usr/local/share/tarantool/?.lua;/usr/local/share/tarantool/?/init.lua;/usr/local/Cellar/tarantool/1.7.5.101/share/tarantool/?.lua;/usr/local/Cellar/tarantool/1.7.5.101/share/tarantool/?/init.lua;/usr/share/tarantool/?.lua;/usr/share/tarantool/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/Cellar/tarantool/1.7.5.101/share/lua/5.1/?.lua;/usr/local/Cellar/tarantool/1.7.5.101/share/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua
-- Lua package.cpath: /usr/local/lib/tarantool/?.dylib;/usr/local/Cellar/tarantool/1.7.5.101/lib/tarantool/?.dylib;/usr/lib/tarantool/?.dylib;/usr/local/lib/lua/5.1/?.dylib;/usr/local/Cellar/tarantool/1.7.5.101/lib/lua/5.1/?.dylib;/usr/lib/lua/5.1/?.dylibCMake Error at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCURL.cmake:64 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:293 (find_package)
```

It can't be built with system one :( I'm talking with Tarantool team about this difficulty.

**Comment by ilovezfs** [comment]
@bigbes
```
diff --git a/Formula/tarantool.rb b/Formula/tarantool.rb
index 6d3bea811d..c8924c93b8 100644
--- a/Formula/tarantool.rb
+++ b/Formula/tarantool.rb
@@ -14,7 +14,6 @@ class Tarantool < Formula
   end
 
   depends_on "cmake" => :build
-  depends_on "curl"
   depends_on "openssl"
   depends_on "readline"
 
@@ -27,7 +26,8 @@ class Tarantool < Formula
     args << "-DENABLE_DIST=ON"
     args << "-DOPENSSL_ROOT_DIR=#{Formula["openssl"].opt_prefix}"
     args << "-DREADLINE_ROOT=#{Formula["readline"].opt_prefix}"
-    args << "-DCURL_ROOT=#{Formula["curl"].opt_prefix}"
+    args << "-DCURL_INCLUDE_DIR=#{MacOS.sdk_path}/usr/include"
+    args << "-DCURL_LIBRARY=/usr/lib/libcurl.dylib"
 
     system "cmake", ".", *args
     system "make"
```

**Comment by ilovezfs** [comment]
For bonus points, you can try to get it to work with
```
args << "-DCURL_ROOT=#{MacOS.sdk_path}/usr"
```
which means it needs to know how to understand
```
lrwxr-xr-x  1 joe  admin    13 Dec 28  2016 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libcurl.3.tbd -> libcurl.4.tbd
-rw-r--r--@ 1 joe  admin  1953 Nov 30  2016 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libcurl.4.tbd
lrwxr-xr-x  1 joe  admin    13 Dec 28  2016 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libcurl.tbd -> libcurl.4.tbd
```
which means it needs to not puke on tbd files.

**Review by ilovezfs — APPROVED** [review]

**Comment by bigbes** [comment]
Thank you, that've worked out. Simple copy-paste of `args << "-DCURL_ROOT=#{MacOS.sdk_path}/usr"` haven't worker for me, needed further investigation. Is it necessary to push this patch?

**Comment by ilovezfs** [comment]
@bigbes no what you have here currently is fine. I just mean if you want to take that problem back to your team, it's probably worth working through since `"-DCURL_ROOT=#{MacOS.sdk_path}/usr"` should work, but doesn't due to the tbd files confusing it, I believe.

**Comment by ilovezfs** [comment]
@bigbes thanks for the upgrade and another contribution to Homebrew!

**Comment by bigbes** [comment]
Thank you, @ilovezfs

**Pull request closed without merging**
