### PR TITLE
repo 2.10

### PR DESCRIPTION
**Pull request by Nef10**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why the changed source?

**Comment by Nef10** [comment]
I changed it from the mirror to the official source as the mirror is not kept up-to-date and is missing the new release tag.

**Comment by Nef10** [comment]
I put a post on the mailing list: https://groups.google.com/g/repo-discuss/c/CXcVM95e_6o

**Comment by Nef10** [comment]
@SMillerDev @fxcoudert The problem with the mirror has been fixed, should we change it back to the GitHub mirror or keep it at the original repo?

**Pull request merged**
