### PR TITLE
Add dte v1.8.2

### PR DESCRIPTION
**Pull request by yumitsu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hi @yumitsu  this is a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by yumitsu** [comment]
Well, it's really funny to see how obsolete garbage with 10-20 stars happily housed in `homebrew-core`, while actively supported software gets rejected because of the small forks number.

**Comment by fxcoudert** [comment]
We happily accept constructive criticism. Sarcasm aimed at an all-volunteer maintainer team is, on the other hand, rarely beneficial to anyone.

**Comment by yumitsu** [comment]
I wasn't being sarcastic, rather the opposite - it's really sad to realise that OSS notability now depends on count of 'likes` and 'reposts', instead of numbers of commits,  open issues and frequency of updates.

As for constructive criticism, I want to propose a cleanup on `homebrew-core` with purpose to (re)move obsolete and long time dead software with it's optional replacement by modern replacemene,

**Comment by fxcoudert** [comment]
We welcome PRs adding tests to existing formulas, for sure! That's what allows us to know when a new macOS version is released, whether the software still works.

**Comment by yumitsu** [comment]
Deal.

**Comment by craigbarnes** [comment]
@fxcoudert The [`dex`](https://github.com/tihirvon/dex) editor is currently packaged in homebrew-core, but the project hasn't been maintained since 2015. `dte` is a maintained fork of `dex`, with about 2000 additional commits and dozens of bug fixes (some of which are security related).

**Pull request closed without merging**
