### PR TITLE
macvim: enable terminal

### PR DESCRIPTION
**Pull request by junegunn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Related #16015

### CODE REVIEW

**Comment by ilovezfs** [comment]
Nice! :rocket:

**Comment by chdiza** [comment]
Upstream just today or yesterday made it so that `--enable-terminal` is not needed anymore.  It's now included by default in a `huge` build, which is itself the default size of build.

**Comment by ilovezfs** [comment]
@chdiza upstream vim or macvim and >= what version?

**Comment by chdiza** [comment]
Upstream vim, 8.0.1050 and up.  MacVim hasn't yet got to 8.0.1050.

**Pull request closed without merging**
