### PR TITLE
terraform 0.9.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cblecker** [comment]
@ilovezfs There's been a couple of these vet issues.. Perhaps we should remove the vet step from Line 67? If upstream isn't concerned with these errors, should we be? There would still be the go test steps, and the binary still compiles/works,

**Comment by cblecker** [comment]
Either way, I've opened up a PR with the upstream to fix: https://github.com/hashicorp/terraform/pull/13121

**Comment by ilovezfs** [comment]
@cblecker ideally we'd remove it from the formula just _after_ upstream adds it to _their_ CI :)

**Comment by ilovezfs** [comment]
@cblecker PR refreshed.

**Comment by ilovezfs** [comment]
@cblecker looks like we're having parallelization issues again :(
```
--- FAIL: TestWaitForState_inconsistent_negative (0.09s)
	state_test.go:111: Errors don't match.
		Expected: "timeout while waiting for state to become 'done' (last state: 'done', timeout: 90ms)"
		Given: "timeout while waiting for state to become 'done' (last state: 'replicating', timeout: 90ms)"
```
and
```
--- FAIL: TestDiffStringMap (0.00s)
    --- FAIL: TestDiffStringMap/4 (0.00s)
    	patch_operations_test.go:121: Operations don't match.
    		Expected: [{"path":"/parent/two","op":"remove"} {"path":"/parent/one","op":"remove"}]
    		Given:    [{"path":"/parent/one","op":"remove"} {"path":"/parent/two","op":"remove"}]
```

**Comment by analytically** [comment]
So no brew for 0.9.2?

**Comment by cblecker** [comment]
@ilovezfs I'm not sure how though... those tests pass locally, and parallelization has been turned off for make by upstream as the build process creates temp files that can break it: https://github.com/hashicorp/terraform/blob/master/Makefile#L107-L110

**Comment by emoshaya-cognito** [comment]
any update on this please?

**Comment by ilovezfs** [comment]
@cblecker it's coming from https://github.com/hashicorp/terraform/blob/master/Makefile#L44

**Comment by mgaffney** [comment]
any updates?

**Comment by cblecker** [comment]
@ilovezfs Ahh.. they're batch testing in groups of four. It's still odd that it consistently passes locally, but is failing in CI.

I see you've dropped those tests from the build formula. Is that something you're looking at keeping? If so, you can probably drop the patch too, and just build off the tag/tarball.

**Comment by mindlace** [comment]
Can this be merged? the checks pass and this release of TF fixes a bug in remote state environments.

**Comment by ilovezfs** [comment]
The urgency of the "Can we merge it?" calls here makes me think both upstream and we need to be more careful, not less careful, about what is published as a supposedly stable release.

**Comment by cblecker** [comment]
@ilovezfs I was able to track down the issue with one specific test, and opened an upstream issue for it (https://github.com/hashicorp/terraform/issues/13230).

I know it's not ideal, but I'd suggest we comment out the vet and test steps for the v0.9.2 build and just run `make bin`. Hopefully upstream can fix this for v0.9.3, and we can restore those steps. That way we can at least push this version out.

**Comment by ilovezfs** [comment]
In general, we don't even run "make test' or "make vet" for anything that isn't security software, so I doubt we'll add it back.

**Comment by ilovezfs** [comment]
Shipped against my better judgment but :man_shrugging:

**Comment by radeksimko** [comment]
Hi folks,
sorry, this was my fault 🙈  - that flaky test was fixed just a few hours after the 0.9.2 release and it didn't affect the user in any way (i.e. the implementation itself wasn't broken, just the test).

See https://github.com/hashicorp/terraform/pull/13117

**Comment by ilovezfs** [comment]
@radeksimko thanks for chiming in. No worries.

**Pull request closed without merging**
