### PR TITLE
icu4c 60.2

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`sqlite3` optionally depends on `icu4c`, the linkage will break if the option has been turned on. I am not sure whether a revision bump for such case is acceptable.

### CODE REVIEW

**Comment by ilovezfs** [comment]
This is a minor version bump. Why are we revision bumping everything?

**Comment by lembacon** [comment]
@ilovezfs Because the library version has been changed. By inspecting binaries such as `sqlite3` and `libharfbuzz-icu.dylib` via `otool -L`, `libicudata.60.1.dylib` is being linked, where the minor library version matters.

**Comment by ilovezfs** [comment]
>sqlite3 optionally depends on icu4c, the linkage will break if the option has been turned on. I am not sure whether a revision bump for such case is acceptable.

nope we don't revision bump for non-default options.

**Comment by ilovezfs** [comment]
@lembacon the checksum of icu4c has a `<paste>` character at the end.

**Comment by lembacon** [comment]
> nope we don't revision bump for non-default options.

Removed.

> @lembacon the checksum of icu4c has a <paste> character at the end.

Fixed. 😂

**Comment by ilovezfs** [comment]
Thanks @lembacon! Shipped.

**Pull request closed without merging**
