### PR TITLE
libunistring 1.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
`gnunet` failed on Monterey ARM with
```
  ld: in libgnunetregextest.a(libgnunetutil.la), archive member 'libgnunetutil.la' with length 1112 is not mach-o or llvm bitcode file 'libgnunetregextest.a' for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [perf-regex] Error 1
```
Doesn't seem related to `libunistring`. OTOH, not sure why this error didn't show up before either. Maybe an Xcode 14 issue?

**Comment by carlocab** [comment]
Same error with the existing version of `libunistring`. Maybe an Xcode 14 linker thing?

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
😢 needs a rebase again

**Comment by cho-m** [comment]
I think we still need a `gnunet` fix/workaround for Xcode 14. #113789 wasn't merged.

Otherwise, we will lose Monterey and Ventura bottles.

**Comment by SMillerDev** [comment]
Since older bottles will work I don't think that's a huge problem.

**Comment by p-linnane** [comment]
Rebased and re-running.

**Comment by SMillerDev** [comment]
```
  ld: in libgnunetregextest.a(libgnunetutil.la), archive member 'libgnunetutil.la' with length 1112 is not mach-o or llvm bitcode file 'libgnunetregextest.a' for architecture arm64
```

**Comment by cho-m** [comment]
I assume `gnunet` is the same failure as previous runs, so how do we want to proceed? Do we want to temporarily drop Monterey bottles and only provide Big Sur bottles for `gnunet`?

**Comment by p-linnane** [comment]
It looks like the newest version of `gnunet` was bumped in https://github.com/Homebrew/homebrew-core/pull/117533, but it went stale and closed without anyone checking it out. I will open a new PR and hopefully we can make some progress there.

**Comment by cho-m** [comment]
After another rebase and run, we should just decide how we want to merge this:
- Can just merge without `gnunet` bottles for Monterey and later (Ventura was never bottled). Significantly less installs on demand for `gnunet` than `libunistring`. 
- Can add `llvm` lld hack from #113789 for `gnunet`. Easy enough to add for another run.
- Can add `.a -> .la` fix from same PR. This will probably take some more time as we need to test and upstream a patch.

**Comment by iMichka** [comment]
I think the hack in #113789 is fine. It's just using a different compiler/ld stack than the one of the OS, so it's still a valid solution.
We should open an upstream issue for that problem though, with the hope something gets done about it.

Anyway, 16 downloads over the last 30 days is not that a big deal ... if it ends up as a huge pile of hacks, it can be made linux-only ... / or removed.

**Comment by Porkepix** [comment]
> Anyway, 16 downloads over the last 30 days is not that a big deal ... if it ends up as a huge pile of hacks, it can be made linux-only ... / or removed.

There are a couple of other formulas depending on it, though?

**Comment by iMichka** [comment]
>> Anyway, 16 downloads over the last 30 days is not that a big deal ... if it ends up as a huge pile of hacks, it can be made linux-only ... / or removed.

>There are a couple of other formulas depending on it, though?

I see none. Or am I wrong?

**Comment by Porkepix** [comment]
> > > Anyway, 16 downloads over the last 30 days is not that a big deal ... if it ends up as a huge pile of hacks, it can be made linux-only ... / or removed.
> 
> > There are a couple of other formulas depending on it, though?
> 
> I see none. Or am I wrong?

```
brew uses --eval-all libunistring
bigloo          boxes           gnunet          gnutls          guile           guile@2         libidn2         notcurses
```

To be fair, though, I also find ` brew uses` to providing me very erratic results sometimes, especially since I'm running it from a Linux, I could several times notice the results lacking some formulas I believe, but couldn't understand yet the details of what was missing/why.

**Comment by cho-m** [comment]
> ```
> brew uses --eval-all libunistring
> bigloo          boxes           gnunet          gnutls          guile           guile@2         libidn2         notcurses
> ```
> 
> To be fair, though, I also find ` brew uses` to providing me very erratic results sometimes, especially since I'm running it from a Linux, I could several times notice the results lacking some formulas I believe, but couldn't understand yet the details of what was missing/why.

We are discussing the `gnunet` failure. `gnunet` has no dependents and install count can be seen on https://formulae.brew.sh/formula/gnunet#default

**Comment by SMillerDev** [comment]
`mpv` failure on `CI / tests (12-3826620086-1)` was a failure to download dependencies.

**Comment by cho-m** [comment]
If Linux run is good, then we can merge.

If someone has an account for upstream issue tracker, can report build issue as I think it still exists in git repo - https://git.gnunet.org/gnunet.git/tree/src/regex/Makefile.am#n25.

If there is a PR process, can also try upstreaming patch provided by @Bo98 - https://github.com/Homebrew/homebrew-core/pull/113789#issuecomment-1288125182

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
https://bugs.gnunet.org/view.php?id=7550

**Pull request closed without merging**
