### PR TITLE
ttfautohint 1.8.3

### PR DESCRIPTION
**Pull request by lemzwerg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zbeekman** [comment]
Is there a way that we could add a better test to this?

**Comment by lemzwerg** [comment]
Testing what?

**Comment by zbeekman** [comment]
Functionality beyond being able to print the version number to the screen. I'm not familiar with the package myself. But if it takes input and creates files the existence and/or content of the file could be checked, or if it runs commands, stdout could be searched for expected output.

**Comment by lemzwerg** [comment]
Yes, this could be certainly added.  However, I'm not a MacOS user at all, only providing this recipe as a convenience.  So in case you want to contribute an improvement:  Take the path of an existing TrueType font as the first argument, add the name of a new output file as the second argument and execute the program; it should generate a new TrueType font.  @anthrotype?

**Comment by fxcoudert** [comment]
Thanks @lemzwerg for the pull request and the test suggestion.

**Pull request closed without merging**
