### PR TITLE
[RFC] infer 0.16.0

### PR DESCRIPTION
**Pull request by jvillard**
This doesn't work locally for me but I'm stumped as to how to fix it so sending this PR anyway.

The issue I encounter is that some OCaml dependency in opam (mlgmpidl more precisely) fails to build when doing `brew install --build-from-source --verbose --debug /Users/jul/code/homebrew-core/Formula/infer.rb`:

```
#=== ERROR while compiling mlgmpidl.1.2.7 =====================================#
# path                 /private/tmp/infer-20190423-14452-kxskqq/opamroot/ocaml-variants.4.07.1+flambda/.opam-switch/build/mlgmpidl.1.2.7
# command              /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make
#         /private/tmp/infer-20190423-14452-kxskqq/opamroot/ocaml-variants.4.07.1+flambda/bin/camlidl -no-include -prepro cpp ${tmpdir}/mpz.idl;                \
# clang: error: no input files
```

If I drop into a shell inside the Homebrew sandbox then sure enough I get the same error:

```console
$ cd /private/tmp/infer-20190423-14452-kxskqq/opamroot/ocaml-variants.4.07.1+flambda/.opam-switch/build/mlgmpidl.1.2.7
$ mktemp -d tmp.XXXXXX
tmp.lbmrl3
$ cp mpz.idl tmp.lbmrl3/mpz.idl
$ /private/tmp/infer-20190423-14452-kxskqq/opamroot/ocaml-variants.4.07.1+flambda/bin/camlidl -no-include -prepro cpp tmp.lbmrl3/mpz.idl
clang: error: no input files
mpz.idl: error during preprocessing
```

Bypassing the clang shim makes that command go through, so it seems like it's a problem with that:

```console
$ PATH=/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/cmake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/ocaml/bin:/usr/local/opt/opam/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/sqlite/bin:/usr/bin:/bin:/usr/sbin:/sbin /private/tmp/infer-20190423-14452-kxskqq/opamroot/ocaml-variants.4.07.1+flambda/bin/camlidl -no-include -prepro cpp tmp.lbmrl3/mpz.idl 
$ # succeeded
```

Is there something I can do in the formula to make it work?

### CODE REVIEW

**Comment by Amar1729** [comment]
I didn't think `gmp` or `mpfr` are necessary to build infer 0.16.0, and I actually don't get your errors when I add them to the formula.  

However when I try to build, the issue seems to be because of the differences between `opam` version `1.2` (which infer-0.15.0 used) and `2.0`, which 0.16.0 uses. Ocaml compilers are now opam packages rather than something separate, so creating a switch is more simple, but the old `infer.rb` line that changed the configure arguments in the `ocaml-version.comp` file is no longer valid.  

We still need to change the compilation of `ocaml-variants.4.07.1+flambda` to include the `-no-graph` argument, since we don't want to depend on X11, but I'm not yet sure how to do that. It should be some combination of `opam pin add edit` and `opam pin show`?  

This is the end of my current build error:

```
==> ./build-infer.sh all --yes
initializing opam...

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ocaml-variants.4.07.1+flambda] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at "/usr/local/Homebrew/Library/Homebrew/shims/mac/super/make world".

#=== ERROR while compiling ocaml-variants.4.07.1+flambda ======================#
# context              2.0.4 | macos/x86_64 |  | https://opam.ocaml.org#b70ba5e4
# path                 /private/tmp/infer-20190424-15106-15sisy/opamroot/ocaml-variants.4.07.1+flambda/.opam-switch/build/ocaml-variants.4.07.1+flambda
# command              /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make world
# exit-code            2
# env-file             /private/tmp/infer-20190424-15106-15sisy/opamroot/log/ocaml-variants-19174-a71bb4.env
# output-file          /private/tmp/infer-20190424-15106-15sisy/opamroot/log/ocaml-variants-19174-a71bb4.out
### output ###
# [...]
# ../../boot/ocamlrun ../../ocamlc -nostdlib -I ../../stdlib -I ../../otherlibs/unix -w +33..39 -warn-error A -bin-annot -g -safe-string -c unix.ml
# ../../boot/ocamlrun ../../tools/ocamlmklib -ocamlc '../../boot/ocamlrun ../../ocamlc -nostdlib -I ../../stdlib -I ../../otherlibs/unix' -o unix -linkall unix.cmo ../unix/unixLabels.cmo
# cc -c -O2 -fno-strict-aliasing -fwrapv -Wall  -I/usr/X11/include -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -I../../byterun -o open.o open.c
# In file included from open.c:19:
# ./libgraph.h:17:10: fatal error: 'X11/Xlib.h' file not found
# #include <X11/Xlib.h>
#          ^~~~~~~~~~~~
# 1 error generated.
# make[3]: *** [open.o] Error 1
# make[2]: *** [otherlibraries] Error 2
# make[1]: *** [all] Error 2
# make: *** [world] Error 2

```

**Comment by jvillard** [comment]
@Amar1729 interesting, thanks for looking into this. I don't know why I don't get the same error as you locally but yours is the same as the one in Jenkins. That step goes fine for me and the failure I pasted happens afterwards when opam tries to build the "mlgmpidl" package.

I think I've found a workaround to edit the opam file for the compiler we want:

```bash
opam show ocaml-variants.4.07.1+flambda --raw > opam
# make some edits to the opam file to change the "version" and the "build" fields
opam pin add .
```

Then we can tell the build script of infer to use the `ocaml-variants.4.07.1+flambda+no-graph` switch:

```bash
INFER_OPAM_SWITCH=ocaml-variants.4.07.1+flambda+no-graph ./build-infer.sh
```

[As a side note it's also unclear why the auto-detection of X11 in OCaml's own `./configure` is not working here: if the X11 headers are not found then it shouldn't enable the graph library from what I understand: https://github.com/ocaml/ocaml/blob/4.07/configure#L1672-L1839]

**Comment by jvillard** [comment]
Ok editing the switch was not as simple as that it turns out, trying another way now: Homebrew and infer agree that 4.07.1 is the version to use so let's try with that.

**Comment by Amar1729** [comment]
Yeah I'm trying with `opam show`, editing the file, and `opam pin add`, but it fails with this odd error:

```
amar-ml1% opam install .
[ocaml-variants.4.07.1+flambda] no changes from file:///private/tmp/infer-20190425-36860-m0x8ns/custom-switch
The following actions will be performed:
  ∗ install ocaml-variants 4.07.1+flambda*
  ∗ install ocaml-config   1
  ∗ install ocaml          4.07.1
===== ∗ 3 =====
Do you want to continue? [Y/n] Y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫

#=== ERROR while compiling ocaml-variants.4.07.1+flambda ======================#
"./configure": command not found.


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build ocaml-variants 4.07.1+flambda
└─
╶─ No changes have been performed
```


And this is the opam file I'm using:  
```
opam-version: "2.0"
name: "ocaml-variants"
version: "4.07.1+flambda"
synopsis: "Official release 4.07.1, with flambda activated"
maintainer: "platform@lists.ocaml.org"
depends: [
  "ocaml" {= "4.07.1" & post}
  "base-unix" {post}
  "base-bigarray" {post}
  "base-threads" {post}
]
conflict-class: "ocaml-core-compiler"
flags: compiler
setenv: CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"
build: [
  ["./configure" "-prefix" prefix "-with-debug-runtime" "-flambda"]
    {os != "openbsd" & os != "freebsd" & os != "macos"}
  [
    "./configure"
"-no-graph"
    "-prefix"
    prefix
    "-with-debug-runtime"
    "-flambda"
    "-cc"
    "cc"
    "-aspp"
    "cc -c"
  ] {os = "openbsd" | os = "freebsd" | os = "macos"}
  [make "world"]
  [make "world.opt"]
]
install: [make "install"]
url {
  src: "https://github.com/ocaml/ocaml/archive/4.07.1.tar.gz"
  checksum: "md5=352fe8d46cb238a26aa10c38bad6ecb6"
}
```

The `-no-graph` param is added and there's still a `url` directive with the proper source, so I have no clue why `opam install` isn't pulling down the source

**Comment by Amar1729** [comment]
Using the homebrew version of `ocaml` won't work because it's not build with `+flambda`. I tried creating a custom version of the current `ocaml` package that uses it and telling `infer.rb` to depend on that custom package, but `opam` still needs to download and compile when creating a new switch _using_ the system compiler.

Unless there's a way to force `opam` using the system compiler somehow? Problem with this would be adding another `ocaml-flambda.rb` to homebrew

**Comment by jvillard** [comment]
@Amar1729 actually +flambda is only to enable some compiler optimisations that make infer go a bit faster but it's not a hard requirement.

This version of the PR went a bit further: the opam dependencies have been installed but compiling clang failed with this on sierra:

```
CMake Error at bindings/ocaml/llvm/cmake_install.cmake:44 (file):
  file cannot create directory: /usr/local/lib/ocaml/llvm.  Maybe need
  administrative privileges.
```

We could disable the OCaml bindings in the build of llvm since infer doesn't need them.

On mojave it's the same error I get locally about the mlgmpidl opam dependency:

```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of mlgmpidl failed at "/usr/local/Homebrew/Library/Homebrew/shims/mac/super/make".

#=== ERROR while compiling mlgmpidl.1.2.9 =====================================#
# context              2.0.4 | macos/x86_64 | ocaml-system.4.07.1 | https://opam.ocaml.org#1ad879fc
# path                 /private/tmp/infer-20190425-55323-cu9uga/opamroot/default/.opam-switch/build/mlgmpidl.1.2.9
# command              /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make
# exit-code            2
# env-file             /private/tmp/infer-20190425-55323-cu9uga/opamroot/log/mlgmpidl-98654-e4db2f.env
# output-file          /private/tmp/infer-20190425-55323-cu9uga/opamroot/log/mlgmpidl-98654-e4db2f.out
### output ###
# tmpdir=$(mktemp -d tmp.XXXXXX);				\
# [...]
# 	{ cp mpz.idl ${tmpdir}/mpz.idl;					\
# 	  /private/tmp/infer-20190425-55323-cu9uga/opamroot/default/bin/camlidl -no-include -prepro cpp ${tmpdir}/mpz.idl;		\
# 	  /usr/bin/perl perlscript_c.pl < ${tmpdir}/mpz_stubs.c >mpz_caml.c;	\
# 	  /usr/bin/perl perlscript_caml.pl < ${tmpdir}/mpz.ml >mpz.ml;		\
# 	  /usr/bin/perl perlscript_caml.pl < ${tmpdir}/mpz.mli >mpz.mli; }
# clang: error: no input files
# mpz.idl: error during preprocessing
# /bin/sh: tmp.ZXyxM6/mpz_stubs.c: No such file or directory
# /bin/sh: tmp.ZXyxM6/mpz.ml: No such file or directory
# /bin/sh: tmp.ZXyxM6/mpz.mli: No such file or directory
# make: *** [mpz.ml] Error 1
```

Maybe it's to do with the new location of C headers in Mojave.

**Comment by Amar1729** [comment]
Ah rip I can't test on sierra.  

Weirdly I am not running into the mojave issues you're getting, even when I add
```ruby
  depends_on "camlp4"
  depends_on "gmp"
  depends_on "mpfr"
```

**Comment by Amar1729** [comment]
> We could disable the OCaml bindings in the build of llvm since infer doesn't need them.

also - I'm not sure about in 0.16.0, but I'm fairly sure the version of clang in 0.15.0 required ocaml bindings enabled? otherwise the infer build would fail out.

**Comment by zbeekman** [comment]
> This version of the PR went a bit further: the opam dependencies have been installed but compiling clang failed with this on sierra:
> 
> ```
> CMake Error at bindings/ocaml/llvm/cmake_install.cmake:44 (file):
>   file cannot create directory: /usr/local/lib/ocaml/llvm.  Maybe need
>   administrative privileges.
> ```

Your vendored llvm is trying to put itself in the default CMake installation prefix. Your build system should have a way of telling it where it should be installed, somewhere inside `infer`'s Cellar.

> Using the homebrew version of `ocaml` won't work because it's not build with `+flambda`

I know zero about ocaml, but it could be revision bumped and shipped with `+flambda` if it won't break other packages and is widely useful.

`# mpz.idl: error during preprocessing` indicates to me that
```
# 	  /private/tmp/infer-20190425-55323-cu9uga/opamroot/default/bin/camlidl -no-include -prepro cpp ${tmpdir}/mpz.idl;
```
failed. This may be due to `camlidl` not working properly, bad flags passed to it, or a problem in `mpz.idl`; or possibly a problem creating the temp directory and copying the file in. If you can do anything to try to reproduce this outside of the homebrew environment that might be helpful.

Finally, I will note that you may want to add a build dependency on perl unless it is transitively pulled in from another tool.

**Comment by Amar1729** [comment]
@jvillard ah I see the error you're having - I added `depends_on :x11` just to see where I'd get, and ran into the same `mlgmpidl` issue you're having.

```
#=== ERROR while compiling mlgmpidl.1.2.7 =====================================#
# context              2.0.4 | macos/x86_64 | ocaml-variants.4.07.1+flambda | https://opam.ocaml.org#45b0aff7
# path                 /private/tmp/infer-20190426-13348-1ve9b4h/opamroot/ocaml-variants.4.07.1+flambda/.opam-switch/build/mlgmpidl.1.2.7
# command              /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make
# exit-code            2
# env-file             /private/tmp/infer-20190426-13348-1ve9b4h/opamroot/log/mlgmpidl-40498-457257.env
# output-file          /private/tmp/infer-20190426-13348-1ve9b4h/opamroot/log/mlgmpidl-40498-457257.out
### output ###
# tmpdir=$(mktemp -d tmp.XXXXXX);                               \
# [...]
#       { cp mpz.idl ${tmpdir}/mpz.idl;                                 \
#         /private/tmp/infer-20190426-13348-1ve9b4h/opamroot/ocaml-variants.4.07.1+flambda/bin/camlidl -no-include -prepro cpp ${tmpdir}/mpz.idl;               \
#         /usr/bin/perl perlscript_c.pl < ${tmpdir}/mpz_stubs.c >mpz_caml.c;    \
#         /usr/bin/perl perlscript_caml.pl < ${tmpdir}/mpz.ml >mpz.ml;          \
#         /usr/bin/perl perlscript_caml.pl < ${tmpdir}/mpz.mli >mpz.mli; }
# clang: error: no input files
# mpz.idl: error during preprocessing
# /bin/sh: tmp.bXWk7m/mpz_stubs.c: No such file or directory
# /bin/sh: tmp.bXWk7m/mpz.ml: No such file or directory
# /bin/sh: tmp.bXWk7m/mpz.mli: No such file or directory
# make: *** [mpz.ml] Error 1

```

**Comment by Amar1729** [comment]
@zbeekman 

i don't know enough about ocaml either, but I'm worried that added `+flambda` to the homebrew ocaml formula might end up breaking unintended formulae elsewhere. Also, after some testing on my own it might not help much in this case: creating a switch compiles the ocaml version you want _using_ the system compiler, so I think that compilation has to happen somewhere during the build process.

for anyone following this, I did create the switch and install `mlgmpidl` outside the homebrew environment. One thing i had to do first was set `PATH=/usr/bin:$PATH` as a fix for [this issue compiling ocaml on macOS](https://github.com/ocaml/opam/issues/3650) - having homebrew tools first in the path when compiling certain ocaml libs seems to confuse the configure scripts. 

Due to this `PATH` change I had to make, I can only assume the issue is with `ENV.compiler`, the compilation flags in `ENV`, or possibly a problem stemming from the shims homebrew uses (e.g. `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang` for clang)? I think there's a way to inspect the environment with `brew install --debug` and the environment when running `opam install -v`, so I guess I'll check that out to see what's different.

**Comment by Amar1729** [comment]
Ah finally (some) progress -

As far as I can tell, build of `mlgmpidl` is failing in a related way to `opam switch create` outside of homebrew from my previous comment - there's some mix of system and homebrew tools that are causing the confusion in the build process. It feels like a bit of a hack, but I added this to the package:

```ruby
    oPATH = ENV["PATH"]
    ENV["PATH"] = "/usr/bin:" + ENV["PATH"]
    system "opam", "install", "mlgmpidl=#{mlgmpidl_version}"
    ENV["PATH"] = oPATH
```

(since `ENV.prepend_path` will no-op on adding system paths like `/usr/bin`). Got past the `opam install` step, but now building java models is failing on an error that _looks_ similar to [this open infer issue](https://github.com/facebook/infer/issues/1002). Not sure if it's actually the same though.

**Comment by Amar1729** [comment]
This is what I have currently for working java analyzers - right now I have the clang plugin building, but when I try to run infer's `./configure`, it errors thinking clang doesn't work. Specifically, clang errors with: 

`fatal error: 'stdio.h' file not found`

```ruby
class Infer < Formula
  desc "Static analyzer for Java, C, C++, and Objective-C"
  homepage "https://fbinfer.com/"
  # pull from git tag to get submodules
  url "https://github.com/facebook/infer.git",
      :tag      => "v0.16.0",
      # I think it should be 4a9161 but homebrew doesn't like that
      # :revision => "4a91616390c058382c703f47653adfaecd31a7d7"
      :revision => "7be696a0ed9e3a8e09869ed468ef2b22715f6f5f"

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "cmake" => :build
  depends_on "gnu-sed" => :build
  depends_on "libtool" => :build
  depends_on "pkg-config" => :build
  depends_on "perl" => :build
  depends_on "camlp4"
  depends_on "gmp"
  depends_on "mpfr"
  depends_on "ocaml"
  depends_on "opam"
  depends_on "python@2"
  depends_on :java => "1.7+"
  depends_on :x11

  def install
    # needed to build clang
    ENV.permit_arch_flags

    # Apple's libstdc++ is too old to build LLVM
    ENV.libcxx if ENV.compiler == :clang

    # using cache to avoid long waits on rebuilds
    #opamroot = HOMEBREW_CACHE/"opam"
    opamroot = libexec/"opam"
    ENV["OPAMROOT"] = opamroot
    ENV["OPAMYES"] = "1"

    # do not attempt to use the clang in facebook-clang-plugins/ as it hasn't been built yet
    ENV["INFER_CONFIGURE_OPTS"] = "--prefix=#{prefix} --without-fcp-clang"

    llvm_args = %w[
      -DLLVM_INCLUDE_DOCS=OFF
      -DLLVM_INSTALL_UTILS=OFF
      -DLLVM_TARGETS_TO_BUILD=all
      -DLIBOMP_ARCH=x86_64
      -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON
      -DLLVM_BUILD_LLVM_DYLIB=ON
    ]

    # infer 0.16.0: ocaml_version = ocaml-variants.4.07.1+flambda
    ocaml_version = File.read("build-infer.sh").match(/INFER_OPAM_DEFAULT_SWITCH=\"([^\"]+)\"/)[1]

    # infer 0.16.0: mlgmpidl_version = 1.2.7
    mlgmpidl_version = File.read("opam.locked").match(/mlgmpidl\".+\"(.+)\"/)[1]

    # so that `infer --version` reports a release version number
    inreplace "infer/src/base/Version.ml.in", "@IS_RELEASE_TREE@", "yes"
    inreplace "facebook-clang-plugins/clang/setup.sh", "CMAKE_ARGS=(", "CMAKE_ARGS=(\n  " + llvm_args.join("\n  ")

    # setup opam
    # disable opam sandboxing because homebrew is sandboxed already
    system "opam", "init", "--bare", "--no-setup", "--disable-sandboxing"
    system "opam", "switch", "create", "#{ocaml_version}"

    oPATH = ENV["PATH"]
    ENV["PATH"] = "/usr/bin:" + ENV["PATH"]
    system "opam", "install", "mlgmpidl=#{mlgmpidl_version}"
    ENV["PATH"] = oPATH
    system "opam", "install", "utop"

    system "./build-infer.sh", "java", "--yes"
    #system "find", "#{opamroot}/log", "-name", "'ocaml-variants*env'", "-exec", "cat", "{}", "\;"
    system "opam", "config", "exec", "--switch=#{ocaml_version}", "--", "make", "install"
  end

  test do
    (testpath/"FailingTest.c").write <<~EOS
      #include <stdio.h>

      int main() {
        int *s = NULL;
        *s = 42;

        return 0;
      }
    EOS

    (testpath/"PassingTest.c").write <<~EOS
      #include <stdio.h>

      int main() {
        int *s = NULL;
        if (s != NULL) {
          *s = 42;
        }

        return 0;
      }
    EOS

    #shell_output("#{bin}/infer --fail-on-issue -- clang -c FailingTest.c &> /dev/null", 2)
    #shell_output("#{bin}/infer --fail-on-issue -- clang -c PassingTest.c &> /dev/null")

    (testpath/"FailingTest.java").write <<~EOS
      class FailingTest {

        String mayReturnNull(int i) {
          if (i > 0) {
            return "Hello, Infer!";
          }
          return null;
        }

        int mayCauseNPE() {
          String s = mayReturnNull(0);
          return s.length();
        }
      }
    EOS

    (testpath/"PassingTest.java").write <<~EOS
      class PassingTest {

        String mayReturnNull(int i) {
          if (i > 0) {
            return "Hello, Infer!";
          }
          return null;
        }

        int mayCauseNPE() {
          String s = mayReturnNull(0);
          return s == null ? 0 : s.length();
        }
      }
    EOS

    shell_output("#{bin}/infer --fail-on-issue -- javac FailingTest.java &> /dev/null", 2)
    shell_output("#{bin}/infer --fail-on-issue -- javac PassingTest.java &> /dev/null")
  end
end

```

**Comment by zbeekman** [comment]
Any @Homebrew/maintainers out there who have experience with ocaml able to take a look at this?

**Comment by fxcoudert** [comment]
Sadly, ocaml is one area where I don't believe we have any experienced maintainer :(
Closing due to lack of activity, hopefully we have better luck with the next release!

**Pull request closed without merging**
