### PR TITLE
you-get 0.4.523

### PR DESCRIPTION
**Pull request by ilovezfs**
use new virtualenv feature

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @UniqMartin @MikeMcQuaid @tdsmith 

Is it just me, or is this really awkward?
```
    virtualenv_create(libexec, "python3")
    virtualenv_install_with_resources
```

If the formula declares `depends_on :python3`, the `virtualenv_create(libexec, "python3")` seems redundant, but if I don't add that, install fails.

**Comment by tdsmith** [comment]
This is the syntax I anticipated.

**Comment by ilovezfs** [comment]
Why would you anticipate `depends_on :python3` + `virtualenv_install_with_resources` not being sufficient for the python3 formulae? That makes no sense to me.

**Comment by tdsmith** [comment]
Spooky action at a distance, man.

**Comment by ilovezfs** [comment]
Sorry but just defaulting to python2 unconditionally even though the formula explicitly depends on python3 is goofy, to put it gently.

**Comment by tdsmith** [comment]
PRs welcome?

**Comment by ilovezfs** [comment]
I'm not in the habit of opening spooky PRs.

**Comment by tdsmith** [comment]
_That_ is demonstrably false :P

**Comment by ilovezfs** [comment]
@tdsmith https://github.com/Homebrew/brew/pull/636.

**Comment by UniqMartin** [comment]
I have to agree with @ilovezfs that

```ruby
virtualenv_create(libexec, "python3")
virtualenv_install_with_resources
```

seems fairly inelegant and hard-coding a preference for Python 2 seems weird (but maybe is warranted given that this is still the system Python on macOS).

Making `virtualenv_install_with_resources` detect the desired Python for unambiguous cases would be great, but I wonder if we have such unambiguous cases. A `depends_on :python3` doesn't seem to be a sufficient indicator as that could still mean that Python 2 is equally fine (as we don't specify `depends_on :python` unless a Python 2 newer than the system Python is required, if I recollect correctly how the current Python handling is supposed to work).

**Comment by ilovezfs** [comment]
pulling this as-is until Homebrew/brew#636 is completed and merged.

**Pull request closed without merging**
