### PR TITLE
icu4c 65.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`libpqxx` revision bump, and then we should be “good”

**Comment by fxcoudert** [comment]
For reasons unknown, CI is hanging whenever it is trying to fetch tarantool source. I cannot reproduce locally, but we need to find a fix 😢 I killed the build for now.

**Comment by Bo98** [comment]
Let's revisit this after Python 3.8 (#45337).

**Comment by fxcoudert** [comment]
Fresh try in https://github.com/Homebrew/homebrew-core/pull/48349

**Pull request closed without merging**
