### PR TITLE
latexml 0.8.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
Did Big Sur Perl get broken again? @Bo98

**Comment by Bo98** [comment]
Yes, honestly a pain in the arse at this point.

Crypt::OpenSSL::RSA I think works fine now though?

Do we know when this broke?

**Comment by Bo98** [comment]
I'll file a bug but we've probably seen the last Big Sur release so we might just have to resource `XML::LibXSLT` on Big Sur.

**Comment by carlocab** [comment]
CI last ran successfully on this in #77154 (at least). It could've been tested elsewhere after that, though.

**Comment by Bo98** [comment]
I reckon it broke at the same time as the OpenSSL one, and nobody noticed so it hasn't been fixed.

**Comment by carlocab** [comment]
```
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/latexml/0.8.6/libexec
running pkg-config libxslt... using fallback values for LIBS and INC
failed
options:
  LIBS='-L/usr/local/lib -L/usr/lib -lxslt -lxml2 -lz -lm'
  INC='-I/usr/local/include -I/usr/include'
If this is wrong, Re-run as:
  $ perl Makefile.PL LIBS='-L/path/to/lib' INC='-I/path/to/include'

looking for -lxslt... libxslt not found
```
Let's try building with `pkg-config`.

**Comment by Bo98** [comment]
Logs don't even show it trying `-lxslt`:

```
cc called with: -c -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os -DVERSION="1" -DXS_VERSION="1" -iwithsysroot /System/Library/Perl/5.30/darwin-thread-multi-2level/CORE Conftest.c
superenv removed:  -g
superenv added:    -w -march=nehalem -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=nehalem -c -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -DVERSION="1" -DXS_VERSION="1" -iwithsysroot /System/Library/Perl/5.30/darwin-thread-multi-2level/CORE Conftest.c -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

cc called with: -bundle -undefined dynamic_lookup -fstack-protector-strong Conftest.o -o blib/arch/auto/Conftest/Conftest.bundle
superenv added:    -pipe -w -Os -march=nehalem -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -w -Os -march=nehalem -bundle -undefined dynamic_lookup -fstack-protector-strong Conftest.o -o blib/arch/auto/Conftest/Conftest.bundle -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
```

Try pass `DEBUG=1` (or whatever value really) to the Makefile.pl call and see if it outputs more.

**Comment by Bo98** [comment]
```
Warning (mostly harmless): No library found for -lxslt
Warning (mostly harmless): No library found for -lxml2
Warning (mostly harmless): No library found for -lz
Warning (mostly harmless): No library found for -lpthread
Warning (mostly harmless): No library found for -licucore
Warning (mostly harmless): No library found for -lm
Warning (mostly harmless): No library found for -lxml2
```

Oh ok sure. Seems content to go ahead and test without any linker flags? Bit of a pointless test then.

Though it can't even do that because:

```
Can't load 'blib/arch/auto/Conftest/Conftest.bundle' for module Conftest: dlopen(blib/arch/auto/Conftest/Conftest.bundle, 0x0002): open("", O_RDONLY) failed with errno=2 at /System/Library/Perl/5.30/darwin-thread-multi-2level/DynaLoader.pm line 197.
```

I swear I've seen this somewhere before around here.

**Comment by carlocab** [comment]
Can we add a `uses_from_macos "perl", until: :catalina`?

**Pull request closed without merging**
