### PR TITLE
WIP: tmux: Apply backported patch to fix server crash

### PR DESCRIPTION
**Pull request by aleksandrs-ledovskis**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Ref: https://github.com/Homebrew/homebrew-core/pull/44866

### CODE REVIEW

**Comment by aleksandrs-ledovskis** [comment]
Closing as uncomplete:
1. Breaks `--HEAD` builds (could possibly do conditional patching?)
2. More crucially, doesn't fully fix `[lost server]` issues. Need to investigate more

**Comment by aleksandrs-ledovskis** [comment]
Reported crashes in https://github.com/tmux/tmux/issues/1930

**Comment by igas** [comment]
@aleksandrs-ledovskis you can use `stable` block to execute code only on stable.

**Comment by aleksandrs-ledovskis** [comment]
@igas Thanks, noted. Though I'm not currently sure that following with this PR's approach of `2.9a` + patch indeed would work for all cases of reported crash.

IMO, better advise is to wait for tmux/tmux#1930 resolution and afterwards just use formula with `--HEAD`

**Comment by aleksandrs-ledovskis** [comment]
As tmux have landed https://github.com/tmux/tmux/commit/38396e6dcad03ba4e91962f27f275a6ad1950db5, my attempt to land backports on `2.9a` is reanimated.

First step is to get both patches hosted in https://github.com/Homebrew/formula-patches/pull/278

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by aleksandrs-ledovskis** [comment]
@SMillerDev Not sure that @BrewTestBot can help this PR in any way. First there is need to merge https://github.com/Homebrew/formula-patches/pull/278 and afterwards I will update this PR to include both patches.

**Comment by aleksandrs-ledovskis** [comment]
Closing as https://github.com/Homebrew/formula-patches/pull/278 was rejected.

Per @fxcoudert, application of backported patches belonging to unreleased version of tmux isn't a route that is acceptable for Homebrew maintainers.

**Pull request closed without merging**
