### PR TITLE
Go 1.13.2

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ipfans** [comment]
Go1.13.3 released soon after 1.13.2, can we update this pr？

**Comment by imjm** [comment]
go 1.13.2 is released

**Comment by cixtor** [comment]
@imjm go 1.13.3 was released and includes the fixes in 1.13.2

**Review by AlekSi — CHANGES_REQUESTED** [review]
Please update to Go 1.13.3.

**Comment by leonklingele** [comment]
#45512

**Pull request closed without merging**
