### PR TITLE
grokj2k 8.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Testing grokj2k
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210221-74592-1wc7ocl.sb ruby -W1 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/grokj2k.rb --verbose
==> /usr/bin/clang -I/opt/homebrew/Cellar/grokj2k/8.0.1/include/grok-8.0 -L/opt/homebrew/Cellar/grokj2k/8.0.1/lib -lgrokj2k test.c -o test
test.c:8:11: error: implicit declaration of function 'grk_image_create' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  image = grk_image_create(1, &cmptparm, color_space,false);
          ^
test.c:8:11: note: did you mean 'grk_image_new'?
/opt/homebrew/Cellar/grokj2k/8.0.1/include/grok-8.0/grok.h:1314:33: note: 'grk_image_new' declared here
GRK_API grk_image* GRK_CALLCONV grk_image_new(uint16_t numcmpts,
                                ^
test.c:8:9: warning: incompatible integer to pointer conversion assigning to 'grk_image *' (aka 'struct _grk_image *') from 'int' [-Wint-conversion]
  image = grk_image_create(1, &cmptparm, color_space,false);
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.c:10:3: error: implicit declaration of function 'grk_image_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  grk_image_destroy(image);
  ^
1 warning and 2 errors generated.
Error: grokj2k: failed
```

**Comment by carlocab** [comment]
Looks like the test block needs updating. @boxerab, do you have suggestions for a new test? Thanks.

**Comment by boxerab** [comment]
> Looks like the test block needs updating. @boxerab, do you have suggestions for a new test? Thanks.

Thanks, @carlocab . I have updated the test code in this PR :  https://github.com/Homebrew/homebrew-core/pull/71845

**Comment by carlocab** [comment]
Superseded by #71845.

**Comment by boxerab** [comment]
@carlocab when I try to test locally, it looks like my Cellar has an older version of Grok library, with old API, so I get errors:

```
/usr/bin/ld: /tmp/cctaqsOA.o: in function `main':
test.c:(.text+0x37): undefined reference to `grk_image_new'
/usr/bin/ld: test.c:(.text+0x47): undefined reference to `grk_object_unref'
collect2: error: ld returned 1 exit status
Error: grokj2k: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/bin/gcc-10 -I/home/linuxbrew/.linuxbrew/Cellar/grokj2k/8.0.1/include/grok-8.0 -L/home/linuxbrew/.linuxbrew/Cellar/grokj2k/8.0.1/lib -lgrokj2k test.c -o test
```
How do I fix this ?

**Comment by carlocab** [comment]
Ah, it looks like you still have the old version installed, because you updated the formula in your local homebrew-core repository. You need to also update the formula in your local linuxbrew-core repo, and then build that updated version from source.

The PR you opened will get merged to linuxbrew-core shortly after it's merged here, so you don't actually need to do anything right now.

**Comment by boxerab** [comment]
Great, thanks!. For future reference, how do I update in local linuxbrew-core repo ?

**Comment by carlocab** [comment]
I think you should be able to navigate to it with `cd $(brew --repo homebrew/core)`.

**Comment by boxerab** [comment]
Thanks!

**Pull request closed without merging**
