### PR TITLE
Remove old keg_only reasons.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Deprecating these from Homebrew/brew in https://github.com/Homebrew/brew/pull/4081 so remove them here first.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@ilovezfs any objections or test failures in here that seem related to this PR?

**Comment by MikeMcQuaid** [comment]
@ilovezfs to provide more elaboration: https://travis-ci.org/Homebrew/homebrew-core/jobs/367366419 indicated that some Linux porting needed done for those and I'm not convinced it's worth investing the time for stuff that's not going to be used on any versions we support.

**Comment by ilovezfs** [comment]
I think that explains why you'd want to kill off `keg_only :provided_until_xcode43` and `:provided_until_xcode5` but why the others?

**Comment by ilovezfs** [comment]
Also isn't checking `installed?` supposed to be unnecessary now?

**Comment by MikeMcQuaid** [comment]
> Also isn't checking installed? supposed to be unnecessary now?

Yeh, it should be.

> I think that explains why you'd want to kill off keg_only :provided_until_xcode43 and :provided_until_xcode5 but why the others?

It feels weird to have DSL values that are specific to old versions of OS X that we no longer support. Additionally, having behaviours that differ on that versions smells like something that's more likely to break in future than matching the behaviour of later versions.

**Review by ilovezfs — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
@Homebrew/core it may be worth checking the other uses of `keg_only :provided_by_macos` and `keg_only :shadowed_by_macos` to see if they all still apply on High Sierra 🤔.

**Pull request merged**
