### PR TITLE
dasm: install machine files too

### PR DESCRIPTION
**Pull request by felipebalbi**
These files are useful for developing atari SW as they provide macros
for every register in the system.

Signed-off-by: Felipe Balbi <felipe@balbi.sh>

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you add `revision 1` to the formula, just below the sha256? That'll make sure everyone gets this immediatly

**Comment by felipebalbi** [comment]
Updated, thanks for the hint.

**Review by SMillerDev — APPROVED** [review]
Thanks @felipebalbi! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by felipebalbi** [comment]
That's very nice of you to say, @SMillerDev. Thanks for merging ;-)

**Pull request closed without merging**
