### PR TITLE
ldc: add a build dependency on LLVM

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is because of the `fails_with :gcc`, whose behaviour changed with
Homebrew/homebrew-test-bot#675. Note that this didn't come up in #85898.

CC @Bo98

### CODE REVIEW

**Comment by carlocab** [comment]
Failed CI run: https://github.com/Homebrew/homebrew-core/actions/runs/1337212216

**Comment by carlocab** [comment]
Point taken. Suggestions for fixing this?

**Comment by carlocab** [comment]
That said, this seems to have worked. No linkage failure after uninstalling `llvm`...

**Comment by Bo98** [comment]
Are you referring to it picking it up via `libcxx`? That's a good point that it's probably a bit fragile which `libcxx` it is picking up and that's perhaps when the compiler + lib version mismatch may not be ideal, in particular if it uses C++ headers from a different version than what it is linking against.

What's the current `libcxx` linking behaviour on macOS?

**Pull request merged**
