### PR TITLE
caf 0.18.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
I updated the configure step. I supposed that `--disable-shared-libs` is equivalent to `--build-static`.

**Comment by SMillerDev** [comment]
Why do we actually disable shared libs? That's fairly unusual for homebrew.

**Comment by Moisan** [comment]
> Why do we actually disable shared libs? That's fairly unusual for homebrew.

It was done in https://github.com/Homebrew/homebrew-core/pull/49914 although there is no explanation for this point. I don't mind enabling them back.

**Comment by bayandin** [comment]
> > Why do we actually disable shared libs? That's fairly unusual for homebrew.
> 
> It was done in #49914 although there is no explanation why. I don't mind enabling them back.

I think this was like that from the very beginning in https://github.com/Homebrew/legacy-homebrew/pull/21952
As per comment https://github.com/Homebrew/legacy-homebrew/pull/21952#commitcomment-3884825:

> --build-static build libcppa as static and shared library

**Comment by Moisan** [comment]
The latest configure script doesn't mention static and builds a shared library by default. I think the current state of that PR is correct then.

**Comment by Moisan** [comment]
`zeek` fails to build due to changes in caf. One of the multiple error:
```
error: type 'caf::binary_deserializer' does not provide a call operator
```

**Comment by Neverlord** [comment]
Just in case you weren't aware: there's actually been a PR for this prior: https://github.com/Homebrew/homebrew-core/pull/69712. It has been closed as stale because it could not make progress without Zeek 4.0 releasing first.

However, Zeek 4.0 officially released on March 1 (GH release page: https://github.com/zeek/zeek/releases/tag/v4.0.0), so hopefully this PR is more successful. 🤞

**Comment by Neverlord** [comment]
```
 ==> FAILED
caf:
  * The URL https://actor-framework.org/ is not reachable
Error: 1 problem in 1 formula detected
```

At least this CI issue is easy to fix, the URL just needs a `www`: https://www.actor-framework.org.

**Comment by carlocab** [comment]
Merged in #72925.

**Pull request closed without merging**
