### PR TITLE
apcupsd: fix build for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Not sure how this formula will behave on non Debian systems.
It detects the Linux distro and has different build/install behavior for other distros like Redhat, Gentoo, ...

https://github.com/Homebrew/homebrew-core/runs/3052016304?check_suite_focus=true
```
  ------------------------------------------------------------
  debian distribution installation
  ------------------------------------------------------------
insserv: fopen(.depend.stop): Permission denied
  COPY  apcupsd => /etc/init.d/apcupsd
/usr/bin/install: cannot create regular file '/etc/init.d/apcupsd': Permission denied
Makefile:10: recipe for target 'install-debian' failed
make[3]: *** [install-debian] Error 1
../../autoconf/targets.mak:68: recipe for target 'install' failed
make[2]: *** [install] Error 2
../autoconf/targets.mak:110: recipe for target 'debian_DIR' failed
make[1]: *** [debian_DIR] Error 2
autoconf/targets.mak:110: recipe for target 'platforms_DIR' failed
make: *** [platforms_DIR] Error 2
```

### CODE REVIEW

**Comment by carlocab** [comment]
If it has distro-dependent behaviour at build-time I think we might not want to package this on Linux.

**Comment by cho-m** [comment]
Will probably require some additional look-through, but I think part of behavior is the exact install path of some files, and other scripts, e.g. 
- Debian/Ubuntu: /etc/init.d/apcupsd , /usr/sbin/update-rc.d
- Fedora/RedHat: /etc/rc.d/init.d/apcupsd

Or, could use `DISTNAME=unknown` which uses `platforms/unknown/Makefile`:
```make
topdir:=../..

SUBDIRS =
include $(topdir)/autoconf/targets.mak

all-install: install-unknown
all-uninstall: uninstall-unknown

install-unknown:
	$(call DISTINST,Unknown)
	@echo "You have to manually install apcupsd boot script and"
	@echo "halt script for clean emergency shutdown."
	@echo "Please contribute your distribution install to apcupsd team."
	@echo "I'm sorry: you are on your own."

uninstall-unknown:
	$(call DISTUNINST,Unknown)
	@echo "You have to manually uninstall apcupsd boot script and"
	@echo "halt script."
	@echo "Please contribute your distribution install to apcupsd team."
	@echo "I'm sorry: you are on your own."
```

**Comment by SMillerDev** [comment]
> I guess we don't support Linux in services.

I'm working on supporting it, but it doesn't use any upstream provided files.

**Comment by carlocab** [comment]
We could also try contributing a Linuxbrew install, as suggested by their `{un,}install-unknown` targets.

**Comment by cho-m** [comment]
> We could also try contributing a Linuxbrew install, as suggested by their `{un,}install-unknown` targets.

I think that is supposed to be related to how services are managed, so probably will have to wait for us to have an official way of managing Linux services via Linuxbrew.

---

Currently experimenting with `unknown` install. It builds, but I don't know if anything is missing.

Linux bottle files are:
```
.
├── COPYING
├── ChangeLog
├── sbin
│   ├── apcaccess
│   ├── apctest
│   ├── apcupsd
│   └── smtp
└── share
    ├── hal
    │   └── 80-apcupsd-ups-policy.fdi
    └── man
        ├── man5
        │   └── apcupsd.conf.5
        └── man8
            ├── apcaccess.8
            ├── apccontrol.8
            ├── apctest.8
            └── apcupsd.8
```

macOS bottle files are:
```
.
├── COPYING
├── ChangeLog
├── Library
│   └── Extensions
│       └── ApcupsdDummy.kext
│           └── Contents
│               ├── Info.plist
│               └── _CodeSignature
│                   ├── CodeDirectory
│                   ├── CodeRequirements
│                   ├── CodeResources
│                   └── CodeSignature
├── apcagent.app
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── apcagent
│       ├── PkgInfo
│       └── Resources
│           ├── English.lproj
│           │   └── MainMenu.nib
│           ├── charging.png
│           ├── commlost.png
│           ├── onbatt.png
│           └── online.png
├── lib
│   └── Library
│       └── LaunchDaemons
│           └── org.apcupsd.apcupsd.plist
├── sbin
│   ├── apcaccess
│   ├── apctest
│   ├── apcupsd
│   ├── apcupsd-start
│   └── smtp
└── share
    └── man
        ├── man5
        │   └── apcupsd.conf.5
        └── man8
            ├── apcaccess.8
            ├── apccontrol.8
            ├── apctest.8
            └── apcupsd.8
```

**Comment by SMillerDev** [comment]
> I think that is supposed to be related to how services are managed, so probably will have to wait for us to have an official way of managing Linux services via Linuxbrew.

Any official way for homebrew is through the `service do` or `plist` block, this formula can be made compatible without any services work.

**Comment by cho-m** [comment]
For now, I think we can just bottle with `DISTNAME=unknown`. It will be up to users to determine way to make into a service for their specific Linux distro. We can revisit later on to add Homebrew service support for Linux.

The general executables should all be available, just not the platform-specific `init.d`/`systemd` scripts.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
