### PR TITLE
Bump samtools and htslib 1.11

### PR DESCRIPTION
**Pull request by cmdcolin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Samtools and htslib are related packages and so they are bumped together, although it is possible the code would function with individual bumps

### CODE REVIEW

**Review by sjackman — DISMISSED** [review]
Thanks again, Colin!

**Comment by cmdcolin** [comment]
@sjackman, huge thanks to you also :)


anything about this bottle publish error that needs handling?

**Comment by SMillerDev** [comment]
Nothing about the particular error, but please squash your commits into one per formula (without the merge commit)

**Comment by chenrui333** [comment]
@cmdcolin just heads up, I have bumped all three formulae (htslib, bcftools, samtools) in #61976

**Comment by cmdcolin** [comment]
righto :) forgot about bcftools

**Comment by chenrui333** [comment]
no worries. :)

**Pull request closed without merging**
