### PR TITLE
conjure-up: fix for ARM and Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Just making a wild guess as to why we do not have an ARM bottle; and that the issue is just the path to juju no being defined correctly on ARM.

**Comment by SMillerDev** [comment]
Is this submitted upstream?

**Comment by iMichka** [comment]
No, I am just testing a run first here to see what happens on ARM. I have no ARM machine.

**Comment by iMichka** [comment]
I submitted my patch upstream: https://github.com/conjure-up/conjure-up/pull/1655

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
