### PR TITLE
imessage-exporter 0.1.9 (new formula)

### PR DESCRIPTION
**Pull request by ReagentX**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
please host your own tap

**Comment by chenrui333** [comment]
Duplicate of #120296 #120496 #120498

**Comment by chenrui333** [comment]
If you wish, you can host this formula in your own tap. Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by ReagentX** [comment]
Why would you do this? All I wanted to do was create a clean pull request for you.

**Comment by chenrui333** [comment]
you are basically wasting resources and spam our CI

**Comment by chenrui333** [comment]
And you also deleted my comments in your issue without clean communications, I dont quite understand.

**Comment by ReagentX** [comment]
If I make new pushes or rebases, CI runs as well… this PR was clean and would build. My project is notable and I want to get it to as many people as possible so they may preserve their data. I would really appreciate it if you allowed my software to be a part of `homebrew-core`.

**Comment by ReagentX** [comment]
I removed your comments on my issue tracker because they are spam. I use the issue tracker to keep track of tasks I need to do.

**Comment by chenrui333** [comment]
> I removed your comments on my issue tracker because they are spam. I use the issue tracker to keep track of tasks I need to do.

when is that a spam? why what you are doing is fair to homebrew-core project?

**Comment by ReagentX** [comment]
Your comments were on *my personal ticket* to submit my package to homebrew. I didn't delete your comments on the PR.

**Comment by ReagentX** [comment]
All I wanted to do was create a clean pull request for you. What do I need to do to get `imessage-exporter` into this repo?

**Comment by chenrui333** [comment]
> Your comments were on _my personal ticket_ to submit my package to homebrew. I didn't delete your comments on the PR.

that is because you cannot delete any comments in this repo?

**Comment by chenrui333** [comment]
> All I wanted to do was create a clean pull request for you. What do I need to do to get `imessage-exporter` into this repo?

you dont have to create many PRs, do you know anything about `git rebase`?

**Comment by chenrui333** [comment]
> * [x]  Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
> * [x]  Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
> * [x]  Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
> * [x]  Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
> * [x]  Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
> * [x]  Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

and you filled that checklist in all three previous PRs? did you actually do that?

**Comment by ReagentX** [comment]
I am sorry if removing comments made in my own repository offends you. I like to keep my personal issue tracker clean.

I think `imessage-exporter` is a useful and important tool to help people own their data. I would be very appreciative if you could provide me with a way to rectify this situation.

**Comment by chenrui333** [comment]
> I am sorry if removing comments made in my own repository offends you.

it is really annoying, I hope this could be a lesson for your future.

**Comment by chenrui333** [comment]
> > * [x]   Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
> > * [x]   Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
> > * [x]   Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
> > * [x]   Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
> > * [x]   Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
> > * [x]   Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?
> 
> and you filled that checklist in all three previous PRs? did you actually do that?

let me ask again, did you do when you submitted the PR?

**Comment by chenrui333** [comment]
especially the style part.

**Comment by ReagentX** [comment]
Yes, which is why I wanted to create a clean pull request for you.

**Comment by chenrui333** [comment]
> Yes, which is why I wanted to create a clean pull request for you. This one passes all of the tests, yet you closed it.

so does that mean, you falsify the checklist in all three previous PRs?

**Comment by chenrui333** [comment]
> I made follow-up commits because I made mistakes in my code. We all do that.

You know you need to fill the checklist before the PR submission, right?

**Comment by ReagentX** [comment]
I don't really know what you want from me. You closed my pull request even though it met all of the requirements.

**Comment by chenrui333** [comment]
> I don't really know what you want from me. You closed my pull request even though it met all of the requirements. If you want me to do something, please tell me.

What you did in this PR cannot justify what you did in #120296 #120496 #120498

And I dont really understand what you did in all those three PRs.

**Comment by ReagentX** [comment]
I am sorry that I made mistakes in my code. What do I need to do to rectify them?

**Comment by chenrui333** [comment]
that is why we have the PR checklist to prevent this unnecessary discussions.

**Comment by chenrui333** [comment]
Let me ask my fellow maintainers on this situation.

**Comment by chenrui333** [comment]
yeah, they will as well as all three previous PRs.

**Comment by ReagentX** [comment]
Alright, please let me know what steps I need to take to get this into `homebrew-core`!

**Comment by p-linnane** [comment]
Chiming in as a maintainer. I've taken a look at the previous PR's.

The way this normally works is that a PR is opened for a new formula, feedback is given, and you and maintainers are free to push new commits and rebase as needed. We can't keep track of feedback if there are multiple PR's for the same formula. If you have some kind of constraint (web UI only) that don't allow you to rebase PR's, that is not our problem.

This is a project run entirely by volunteers and we ask you to respect our feedback and time rather than argue with us and open multiple PR's. Our goal is to make it easy to add software to the main Homebrew repos.

Regarding the steps needed to get this into `homebrew-core`: Open a PR, listen to feedback, discuss if you disagree, push commits and rebase as needed (do not open multiple PR's), ask for additional feedback, wait for approval & merge. If you can respect/follow these steps we will have no issues.

Please let me know if you need additional clarification here.

**Comment by ReagentX** [comment]
I understand. Can we please reopen this pull request?

**Comment by p-linnane** [comment]
Reopened. This is the only PR we will accept for adding this piece of software, so let's collaborate here. Please let us know if you have any issues.

**Comment by SMillerDev** [comment]
> We frown on authors submitting their own work unless it is very popular.

https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

**Comment by MikeMcQuaid** [comment]
Having read all the issue/PR threads and the DM you sent me:
- I am disappointed as to how you have been speaking to other maintainers
- It looks a lot like you have gamed the system to meet our e.g. star requirements in 3 days
- This is self-submitted and we don't like that: https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

I am closing this PR. Do not submit this software yourself again. If there's any rude outburst or negative reaction to this here, on your issue tracker or on Twitter: you will be blocked from Homebrew indefinitely.

**Comment by ReagentX** [comment]
I did not "game the system," my project organically grew due to a poplar Reddit post on /r/DataHoarder: https://old.reddit.com/r/DataHoarder/comments/108gnnh/i_wanted_to_be_able_to_exportbackup_imessage

I understand that you don't like self-submitted formula, so I won't make another request.

**Pull request closed without merging**
