### PR TITLE
Update jrnl.rb with current release

### PR DESCRIPTION
**Pull request by maebert**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
Looks like some of the Python resources need updating: https://bot.brew.sh/job/Homebrew%20Core/16643/version=sierra/testReport/junit/brew-test-bot/sierra/test_jrnl/

**Comment by ilovezfs** [comment]
Closing due to lack of activity

**Comment by ilovezfs** [comment]
@maebert thanks for the PR nonetheless

**Comment by maebert** [comment]
Sorry, I got swamped -- I'll send a fixed PR when I've got some free cycles.

**Pull request closed without merging**
