### PR TITLE
tracker 3.2.1

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Program python3 (gi) found: NO

../meson.build:83:0: ERROR: python3 is missing modules: gi
```
Needs `pygobject3`. Not sure if it's a runtime dep though.

**Comment by chenrui333** [comment]
let's try to make it build dependency first. cc @tschoonj

**Comment by tschoonj** [comment]
Looks like a build-time dependency to me.

**Comment by EricFromCanada** [comment]
```
Tracker:ERROR:../src/libtracker-sparql/tracker-remote-module.c:82:tracker_init_remote: code should not be reached
Bail out! Tracker:ERROR:../src/libtracker-sparql/tracker-remote-module.c:82:tracker_init_remote: code should not be reached
Command '['/private/tmp/tracker-20211003-56732-16wfwv5/tracker-3.2.0/build/tmp-introspectns1jyfpc/Tracker-3.0', '--introspect-dump=/private/tmp/tracker-20211003-56732-16wfwv5/tracker-3.2.0/build/tmp-introspectns1jyfpc/functions.txt,/private/tmp/tracker-20211003-56732-16wfwv5/tracker-3.2.0/build/tmp-introspectns1jyfpc/dump.xml']' died with <Signals.SIGABRT: 6>.
```

**Pull request closed without merging**
