### PR TITLE
arm-none-eabi-binutils 2.41 arm-none-eabi-gcc 13.2.0 arm-none-eabi-gdb 13.2 (new formulae)

### PR DESCRIPTION
**Pull request by glingy**
Add arm-none-eabi-binutils (2.41), arm-none-eabi-gcc (13.2.0), and arm-none-eabi-gdb (13.2).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @glingy for your contribution to Homebrew! I'm adding checks so that the versions of binutils, gcc and gdb in those new formulas stay in sync with other targets.

**Review by fxcoudert — APPROVED** [review]

**Comment by glingy** [comment]
I didn't know that version check file existed, thanks!

**Review by chenrui333 — APPROVED** [review]

**Comment by glingy** [comment]
@chenrui333 Is there a way to manually re-run the failing test? It doesn't seem to have a good failure reason except something got stuck and the build froze?

**Comment by ZhongRuoyu** [comment]
> Is there a way to manually re-run the failing test?

I've triggered a rerun.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Thanks @glingy!

**Comment by fauxpark** [comment]
Hi, what is the point of this? It does not include newlib nor have multilib enabled. It also conflicts with the `osx-cross` tap which has a much more functional ARM toolchain in several versions.

**Comment by fxcoudert** [comment]
We would be glad to consider improvements to the formula, to make a more complete toolchain.

**Pull request merged**
