### PR TITLE
mesa: switch to normal meson

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
```
Program python3 found: YES (/usr/local/opt/python@3.8/bin/python3)

../meson.build:799:2: ERROR: Problem encountered: Python (3.x) mako module >= 0.8.0 required to build mesa.
```

**Comment by yurikoles** [comment]
#58943

**Comment by yurikoles** [comment]
Please add a label `help wanted`.

**Comment by chenrui333** [comment]
I found out the root cause, because it used to use `meson-internal`, it always used the system python instead of `python@3.8`, that is why you did the meson dep switch, it reported error now.

```
==> meson --prefix=/usr/local/Cellar/mesa/20.1.5_1 --libdir=/usr/local/Cellar/mesa/20.1.5_1/lib --buildtype=release .. -Db_ndebug=true -Dplatforms=surfaceless -Dglx=disabled -Dpython=/usr/local/opt/python@3.8/bin/python3
The Meson build system
Version: 0.46.1
Source dir: /private/tmp/mesa-20200816-54538-e7hzbd/mesa-20.1.5
Build dir: /private/tmp/mesa-20200816-54538-e7hzbd/mesa-20.1.5/build
Build type: native build
Program python found: YES (/usr/bin/python)
WARNING: Unknown command line options: "python"
This will become a hard error in a future Meson release.
```

Error log:

```
==> meson --prefix=/usr/local/Cellar/mesa/20.1.5_1 --libdir=/usr/local/Cellar/mesa/20.1.5_1/lib --buildtype=release .. -Db_ndebug=true -Dplatforms=surfaceless -Dglx=disabled
The Meson build system
Version: 0.55.0
Source dir: /private/tmp/mesa-20200816-47592-p5ylbp/mesa-20.1.5
Build dir: /private/tmp/mesa-20200816-47592-p5ylbp/mesa-20.1.5/build
Build type: native build
Program python found: YES
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/python@3.8/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/python@3.8/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig'
Project name: mesa
Project version: 20.1.5
Using 'CC' from environment with value: 'clang'
Using 'CXX' from environment with value: 'clang++'
Using 'CC' from environment with value: 'clang'
C compiler for the host machine: clang (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.12)")
C linker for the host machine: clang ld64 520
Using 'CXX' from environment with value: 'clang++'
C++ compiler for the host machine: clang++ (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.12)")
C++ linker for the host machine: clang++ ld64 520
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/local/opt/python@3.8/bin/python3)
../meson.build:799:2: ERROR: Problem encountered: Python (3.x) mako module >= 0.8.0 required to build mesa.
```

**Comment by chenrui333** [comment]
Closing this, will revisit this later. Thanks @yurikoles!

**Pull request closed without merging**
