### PR TITLE
lua-language-server 3.6.23

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by clason** [comment]
I don't see why that failing test is even run...

**Comment by chenrui333** [comment]
```
  1) filewatch.test_2
  bee.lua/test/test_filewatch.lua:69: expected: nil, actual: <userdata:/private/tmp/test_bee/temp/test1>
  stack traceback:
  	bee.lua/test/test_filewatch.lua:69: in local 'assertHas'
  	bee.lua/test/test_filewatch.lua:71: in local 'f'
  	bee.lua/test/test_filewatch.lua:28: in upvalue 'test'
  	bee.lua/test/test_filewatch.lua:38: in upvalue 'filewatch.test_2'
```

**Comment by clason** [comment]
Yes, I saw the test output, but I've patched the formula _not_ to run any tests -- which worked fine with previous releases, and I haven't seen any changes that would explain why this is no longer working.

**Comment by chenrui333** [comment]
> Yes, I saw the test output, but I've patched the formula _not_ to run any tests -- which worked fine with previous releases, and I haven't seen any changes that would explain why this is no longer working.

looks like just failed on 11-arm build, rerunning

**Pull request merged**
