### PR TITLE
x264: add tag

### PR DESCRIPTION
**Pull request by davidomullan**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Original error:
`$ brew audit --strict x264`
`  * line 5, col 3: Formulae in homebrew/core should specify a tag for git URLs`
`Error: 1 problem in 1 formula detected.`

x264 does not have a tag, so I set the tag symbol to empty string. Error clears and passes all tests.

### CODE REVIEW

**Comment by davidomullan** [comment]
`➜  homebrew-core git:(x264-audit) ✗ brew install --build-from-source x264`
`==> Downloading https://formulae.brew.sh/api/formula.jws.json`

`==> Downloading https://formulae.brew.sh/api/cask.jws.json`

`Warning: x264 r3095 is already installed and up-to-date.`
`To reinstall r3095, run:`
`  brew reinstall x264`
`➜  homebrew-core git:(x264-audit) ✗ brew test x264`
`==> Testing x264`
`==> /usr/local/Cellar/x264/r3095/bin/x264 --version`
`==> /usr/bin/clang -L/usr/local/Cellar/x264/r3095/lib test.c -lx264 -o test`
`==> ./test`
`➜  homebrew-core git:(x264-audit) ✗ brew audit --strict --online x264`

**Comment by davidomullan** [comment]
`➜  homebrew-core git:(master) brew tests`
.
.
.
```
Failures:

  1) Cask::Artifact::App upgrade when the directory is owned by root reuses the same directory
     Failure/Error: app.install_phase(command: command, adopt: adopt, force: force, predecessor: cask)
     
     Timeout::Error:
       execution expired
     # ./system_command.rb:229:in `join'
     # ./system_command.rb:229:in `each_output_line'
     # ./system_command.rb:47:in `run!'
     # ./system_command.rb:34:in `run'
     # ./system_command.rb:38:in `run!'
     # ./system_command.rb:26:in `system_command!'
     # ./cask/quarantine.rb:181:in `copy_xattrs'
     # ./cask/artifact/moved.rb:94:in `move'
     # ./cask/artifact/moved.rb:19:in `install_phase'
     # ./test/cask/artifact/app_spec.rb:369:in `block (4 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:51:in `block (2 levels) in <top (required)>'



Took 226 seconds (3:46)
Tests Failed
```

**Comment by davidomullan** [comment]
```
HOMEBREW_VERSION: 4.0.26-24-g36fc91b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 36fc91b7c1999d42e9e9d4af40b594a4416a93dc
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: db7fe2f4f3f46b53d7e838401d3624e1afef154c
Core tap last commit: 20 minutes ago
Core tap branch: x264-audit
Core tap JSON: 29 Jun 20:03 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
```

**Comment by davidomullan** [comment]
Rerun

**Review by SMillerDev — CHANGES_REQUESTED** [review]
This isn't a fix for the problem "upstream does not tag things". Please contact upstream to request actual tagging of versions.

**Comment by davidomullan** [comment]
> This isn't a fix for the problem "upstream does not tag things". Please contact upstream to request actual tagging of versions.

Makes sense, will do.

**Pull request closed without merging**
