### PR TITLE
llvm 15.0.4

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like this needs https://github.com/llvm/llvm-project/commit/81fc5f7909a4ef5a8d4b5da2a10f77f7cb01ba63.

**Comment by ZhongRuoyu** [comment]
> Looks like this needs [llvm/llvm-project@81fc5f7](https://github.com/llvm/llvm-project/commit/81fc5f7909a4ef5a8d4b5da2a10f77f7cb01ba63).

Thanks, I've added the patch. Let's see.

**Comment by carlocab** [comment]
This will need a re-run with a long timeout label. Might be a good time to switch this to `python@3.11`.

**Comment by ZhongRuoyu** [comment]
> Might be a good time to switch this to `python@3.11`.

I've made my first attempt in 3cfc5e7466c8a29dbb61fc4ab28f8590220dfede, bumping all versioned Python references to 3.11. Not sure if that's sufficient, so I'd appreciate it if you could help to address the potential issues, if any. Please feel free to push to this PR if necessary.

**Comment by carlocab** [comment]
Looks fine. But we need https://github.com/Homebrew/homebrew-core/pull/114521 too.

**Comment by ZhongRuoyu** [comment]
> Looks fine. But we need #114521 too.

Alright. Then I'll do a rebase after #114521 gets merged. Thanks.

**Comment by ZhongRuoyu** [comment]
```
[100%] Building CXX object tools/lldb/source/API/CMakeFiles/liblldb.dir/__/__/bindings/python/LLDBWrapPython.cpp.o
cd /tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/source/API && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DHAVE_ROUND -DLLDB_IN_LIBLLDB -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/source/API -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/lldb/source/API -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/lldb/include -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/include -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/include -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/../clang/include -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/../clang/include -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/lldb/source -I/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/source -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/libxml2 -stdlib=libc++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -Wno-deprecated-register -Wno-vla-extension -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -fPIC -std=c++14  -w -MD -MT tools/lldb/source/API/CMakeFiles/liblldb.dir/__/__/bindings/python/LLDBWrapPython.cpp.o -MF CMakeFiles/liblldb.dir/__/__/bindings/python/LLDBWrapPython.cpp.o.d -o CMakeFiles/liblldb.dir/__/__/bindings/python/LLDBWrapPython.cpp.o -c /tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp
/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp:22096:19: error: non-const lvalue reference to type 'lldb::FileSP' (aka 'shared_ptr<lldb_private::File>') cannot bind to a value of unrelated type 'SwigValueWrapper<std::shared_ptr<lldb_private::File>>'
    lldb::FileSP &sp = result;
                  ^    ~~~~~~
/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp:22136:19: error: non-const lvalue reference to type 'lldb::FileSP' (aka 'shared_ptr<lldb_private::File>') cannot bind to a value of unrelated type 'SwigValueWrapper<std::shared_ptr<lldb_private::File>>'
    lldb::FileSP &sp = result;
                  ^    ~~~~~~
/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp:22176:19: error: non-const lvalue reference to type 'lldb::FileSP' (aka 'shared_ptr<lldb_private::File>') cannot bind to a value of unrelated type 'SwigValueWrapper<std::shared_ptr<lldb_private::File>>'
    lldb::FileSP &sp = result;
                  ^    ~~~~~~
/tmp/llvm-20221108-36181-1v8pl4z/llvm-project-15.0.4.src/llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp:30738:19: error: non-const lvalue reference to type 'lldb::FileSP' (aka 'shared_ptr<lldb_private::File>') cannot bind to a value of unrelated type 'SwigValueWrapper<std::shared_ptr<lldb_private::File>>'
    lldb::FileSP &sp = result;
                  ^    ~~~~~~
4 errors generated.
make[2]: *** [tools/lldb/source/API/CMakeFiles/liblldb.dir/__/__/bindings/python/LLDBWrapPython.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [tools/lldb/source/API/CMakeFiles/liblldb.dir/all] Error 2
make: *** [all] Error 2
```

This was caused by a change in `swig` 4.1.0 (see swig/swig#2377), and should be fixed by llvm/llvm-project@f0a25fe0b746f56295d5c02116ba28d2f965c175.

**Comment by ZhongRuoyu** [comment]
### Failure on Catalina x86_64

<details>
<summary><code>brew install --only-dependencies coin3d</code></summary>
<pre><code>==> brew install --only-dependencies coin3d
==> FAILED
Full install --only-dependencies coin3d output
  Warning: You are using macOS 10.15.
  We (and Apple) do not provide support for this old version.
  It is expected behaviour that some formulae will fail to build in this old version.
  It is expected behaviour that Homebrew will be buggy and slow.
  Do not create any issues about this on Homebrew's GitHub repositories.
  Do not create any issues even if you think this message is unrelated.
  Any opened issues will be immediately closed without response.
  Do not ask for help from MacHomebrew on Twitter.
  You may ask for help in Homebrew's discussions but are unlikely to receive a response.
  Try to figure out the problem yourself and submit a fix as a pull request.
  We will review it but may or may not accept it.
  
  ==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/manifests/71.1
  ==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:0182e3999a76593888bc2b5d54c275b6d7f0eb75db354a3a37925179a9e91d84
  ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:0182e3999a76593888bc2b5d54c275b6d7f0eb75db354a3a37925179a9e91d84?se=2022-11-10T11%3A45%3A00Z&sig=%2FDuVoEt7fSyE2P%2BY%2Fh3idNkx03Db%2FNryxtoqeMBKNS0%3D&sp=r&spr=https&sr=b&sv=2019-12-12
  ==> Downloading https://ghcr.io/v2/homebrew/core/boost/manifests/1.80.0
  ==> Downloading https://ghcr.io/v2/homebrew/core/boost/blobs/sha256:a75afcf9ab1eee0eecb592820[70](https://github.com/Homebrew/homebrew-core/actions/runs/3426362265/jobs/5726471983#step:10:71)b0559c56b7a00d5b3ab29c6a2d52c9b51b8a5
  ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a75afcf9ab1eee0eecb59282070b0559c56b7a00d5b3ab29c6a2d52c9b51b8a5?se=2022-11-10T11%3A45%3A00Z&sig=%2BL%2Ff9xDWNirgOp%2BlAXEAXEkyDPlJCl%2BqHh5jZqBjHp8%3D&sp=r&spr=https&sr=b&sv=2019-12-12
  curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
  Error: coin3d: Failed to download resource "boost"
  Download failed: https://ghcr.io/v2/homebrew/core/boost/blobs/sha256:a75afcf9ab1eee0eecb59282070b0559c56b7a00d5b3ab29c6a2d52c9b51b8a5
  Warning: HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK is set: not checking for outdated
  dependents or dependents with broken linkage!
</code></pre>
</details>

Should be a transient network error.

### Failure on Linux

<details>
<summary><code>brew linkage --test pyside@2</code></summary>
<pre><code>==> brew linkage --test pyside@2
==> FAILED
Full linkage --test pyside@2 output
  Missing libraries:
    unexpected (libQt5Core.so.5)
    unexpected (libQt5Designer.so.5)
    unexpected (libQt5DesignerComponents.so.5)
    unexpected (libQt5Gui.so.5)
    unexpected (libQt5Network.so.5)
    unexpected (libQt5PrintSupport.so.5)
    unexpected (libQt5Widgets.so.5)
    unexpected (libQt5Xml.so.5)
</code></pre>
</details>

<details>
<summary><code>brew test --retry --verbose pyside@2</code></summary>
<pre><code>==> brew test --retry --verbose pyside@2
==> FAILED
Full test pyside@2 output
  ==> Testing pyside@2
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import shiboken2
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtCore
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtGui
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtLocation
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtMultimedia
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtNetwork
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtQuick
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtSvg
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtWebEngineWidgets
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtWidgets
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtXml
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10-config --includes
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10-config --ldflags --embed
  ==> /usr/bin/g++-11 -std=c++11 test.cpp -I/home/linuxbrew/.linuxbrew/Cellar/pyside@2/5.15.5_3/include/shiboken2 -L/home/linuxbrew/.linuxbrew/Cellar/pyside@2/5.15.5_3/lib -lshiboken2.abi3 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/pyside@2/5.15.5_3/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/python@3.10/lib -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include/python3.10 -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include/python3.10 -L/home/linuxbrew/.linuxbrew/opt/python@3.10/lib -lpython3.10 -lcrypt -ldl -lm -lm -o test
  ==> ./test
  ==> Testing pyside@2 (again)
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import shiboken2
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtCore
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtGui
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtLocation
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtMultimedia
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtNetwork
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtQuick
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtSvg
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtWebEngineWidgets
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtWidgets
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10 -c import PySide2.QtXml
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10-config --includes
  ==> /home/linuxbrew/.linuxbrew/bin/python3.10-config --ldflags --embed
  ==> /usr/bin/g++-11 -std=c++11 test.cpp -I/home/linuxbrew/.linuxbrew/Cellar/pyside@2/5.15.5_3/include/shiboken2 -L/home/linuxbrew/.linuxbrew/Cellar/pyside@2/5.15.5_3/lib -lshiboken2.abi3 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/pyside@2/5.15.5_3/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/python@3.10/lib -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include/python3.10 -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include/python3.10 -L/home/linuxbrew/.linuxbrew/opt/python@3.10/lib -lpython3.10 -lcrypt -ldl -lm -lm -o test
  ==> ./test
  Error: pyside@2: failed
  An exception occurred within a child process:
    BuildError: Failed executing: ./test
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2510:in `block in system'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2446:in `open'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2446:in `system'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pyside@2.rb:124:in `block in <class:PysideAT2>'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2285:in `block (3 levels) in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:605:in `with_env'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2284:in `block (2 levels) in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:967:in `with_logging'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2283:in `block in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2561:in `mktemp'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2277:in `run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:50:in `<main>'
</code></pre>
</details>

<details>
<summary><code>brew test --retry --verbose quazip</code></summary>
<pre><code>==> brew test --retry --verbose quazip
==> FAILED
Full test quazip output
  ==> Testing quazip
  ==> /home/linuxbrew/.linuxbrew/opt/qt/bin/qmake test.pro
  Info: creating stash file /tmp/quazip-test-20221111-561353-1ik8q38/.qmake.stash
  ==> make
  g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtGui -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/share/qt/mkspecs/linux-g++ -o test.o test.cpp
  g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -Wl,-rpath-link,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -o test  test.o   -L/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/lib -lquazip1-qt6 /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Gui.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Core.so -lpthread -lGL   
  ==> ./test
  ./test: error while loading shared libraries: libquazip1-qt6.so.1.3.0: cannot open shared object file: No such file or directory
  ==> Testing quazip (again)
  ==> /home/linuxbrew/.linuxbrew/opt/qt/bin/qmake test.pro
  Info: creating stash file /tmp/quazip-test-20221111-561551-qlysnl/.qmake.stash
  ==> make
  g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtGui -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/share/qt/mkspecs/linux-g++ -o test.o test.cpp
  g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -Wl,-rpath-link,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -o test  test.o   -L/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/lib -lquazip1-qt6 /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Gui.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Core.so -lpthread -lGL   
  ==> ./test
  ./test: error while loading shared libraries: libquazip1-qt6.so.1.3.0: cannot open shared object file: No such file or directory
  Error: quazip: failed
  An exception occurred within a child process:
    BuildError: Failed executing: ./test
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2510:in `block in system'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2446:in `open'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2446:in `system'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/quazip.rb:59:in `block in <class:Quazip>'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2285:in `block (3 levels) in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:605:in `with_env'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2284:in `block (2 levels) in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:967:in `with_logging'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2283:in `block in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2561:in `mktemp'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2277:in `run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:50:in `<main>'
</code></pre>
</details>

All Qt related.

**Review by cho-m — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
