### PR TITLE
app-engine-java 1.9.73

### PR DESCRIPTION
**Pull request by pcavadas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
```
Error: app-engine-java: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: Dev App Server terminated prematurely.
<nil> expected to not be nil.
```

**Pull request closed without merging**
