### PR TITLE
json-c 0.13.1

### PR DESCRIPTION
**Pull request by dirker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Looks like this needs some revision bumps for things that depend on it. 

- fastd
- gdal
- gmt
- gmt@4
- liblwgeom
- libmypaint
- libu2f-host
- libu2f-server
- mapserver
- mpw
- ndpi
- newsboat
- ntopng
- pam-u2f
- pam_yubico
- pdal
- pgrouting
- pianobar
- pianod
- points2grid
- postgis
- riemann-client
- rsyslog
- shogun
- simple-tiles
- tracebox
- ttyd
- ykpers
- zmap

**Comment by ilovezfs** [comment]
Yes, and several of them were incompatible when I last attempted it in https://github.com/Homebrew/homebrew-core/pull/21454

**Comment by ilovezfs** [comment]
@dirker to be clear, those revision bumps need to be added by you to this PR or we cannot merge it.

**Comment by ilovezfs** [comment]
rsyslog and shogun too

**Comment by dirker** [comment]
@ilovezfs, yes, these are still blocking the upgrade. Both fail to compile with json-c 0.13.1. I am currently working on upgrading rsyslog, then I'll take a look at shogun.

**Comment by dirker** [comment]
Shogun has been adapted for json-c 0.13.1 in https://github.com/shogun-toolbox/shogun/issues/4098, but it's not released, yet. What's the homebrew take on this: wait for release? Add patch?

**Comment by dirker** [comment]
@ilovezfs, I have created https://github.com/Homebrew/formula-patches/pull/240 for compiling shogun with json-c 0.13.1.

**Comment by ilovezfs** [comment]
What's the story with the rsyslog patch? Was it already fixed upstream?

Patching shogun is fine if it was already fixed in master.

**Comment by dirker** [comment]
rsyslog 7.4.5 is actually already compatible with json-c 0.13.1, it only contains some old leftover includes of private headers. This only got cleaned up in rsyslog 8.18.0 in 8e26927f5264a82302c4ad4f5e15039108a20294. I guess I could have mentioned the original commit in the patch, want me to change this?

**Comment by ilovezfs** [comment]
For shogun I think we can use
```
patch do
  url "https://github.com/shogun-toolbox/shogun/commit/365ce4c4c7.patch?full_index=1"
  sha256 "e7d90ed1ff448d86762449223b926de247e49ae6eeffa7f38c2395f69b1e16fc"
end
```
instead of a formula-patches patch.

I've shipped this PR without the rsyslog or shogun revisions. Excellent work, @dirker!

Can you please open separate PRs for rsyslog and shogun for the remaining revisions? For rsyslog, I think a PR for the latest version would be better than patching the old one, if you have the time.

**Pull request closed without merging**
