### PR TITLE
pillar 2.1.0

### PR DESCRIPTION
**Pull request by ilovezfs**
needed to patch an sbt assembly deduplicate error

### CODE REVIEW

**Comment by ilovezfs** [comment]
@UniqMartin :ship:?

**Comment by UniqMartin** [comment]
Looks reasonable to me. :shipit:

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
patch was merged upstream and got a new tag too! https://github.com/comeara/pillar/pull/32#issuecomment-231751727

**Pull request closed without merging**
