### PR TITLE
vault 1.8.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
```
Stderr: # github.com/hashicorp/vault
github.com/sethvargo/go-limiter/memorystore.(*store).purge: relocation target runtime.walltime not defined
github.com/sethvargo/go-limiter/memorystore.newBucket: relocation target runtime.walltime not defined
github.com/sethvargo/go-limiter/memorystore.(*bucket).take: relocation target runtime.walltime not defined
```

The specific version of dependency (v0.3.0) doesn't compile with go 1.17: 
- Issue: https://github.com/sethvargo/go-limiter/issues/23
- Fix in v0.7.0: https://github.com/sethvargo/go-limiter/pull/25

Since we didn't test dependents on Linux for go 1.17 update, this wasn't caught. Probably need to inform upstream.

A couple options:
- Use `go@1.16` on Linux.
- Patch `go-limiter` for Linux

**Comment by SMillerDev** [comment]
I don't think we should be depending on different versions of the same software depending on the OS. Can't we just apply the patch?

**Review by dawidd6 — DISMISSED** [review]

**Review by dawidd6 — DISMISSED** [review]

**Comment by chenrui333** [comment]
linux build still failed, reporting it to the upstream PR.

**Comment by cho-m** [comment]
It's still trying to use the old version of dependency. Not sure why though:
`go: downloading github.com/sethvargo/go-limiter v0.3.0`

**Pull request closed without merging**
