### PR TITLE
hashcat 6.0.0

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

+ license added

### CODE REVIEW

**Comment by bayandin** [comment]
That's interesting

```
==> brew fetch --retry hashcat --build-bottle --force
==> FAILED
==> Downloading https://hashcat.net/files/hashcat-6.0.0.tar.gz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by crunchtime-ali** [comment]
The following commands sheds some light on the issue. The certificate is different from the one used when accessing via browser. You should use the contact form or the hashcat forum.

```bash
curl --insecure -v https://hashcat.net/files/hashcat-5.1.0.tar.gz 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
```

* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL; CN=hashcat.net
*  start date: Nov 26 00:00:00 2019 GMT
*  expire date: Nov 25 23:59:59 2021 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd532009600)
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!

**Comment by chenrui333** [comment]
rebased to latest master and give it another run.

**Comment by SeekingMeaning** [comment]
GitHub source download is an option, it even has the same SHA256(!)

https://github.com/hashcat/hashcat/archive/v6.0.0.tar.gz

**Comment by bayandin** [comment]
> GitHub source download is an option, it even has the same SHA256(!)
> 
> https://github.com/hashcat/hashcat/archive/v6.0.0.tar.gz

I've added it as a mirror.
Thanks for the suggestion 👍

**Comment by dtrodrigues** [comment]
This is related to https://security.stackexchange.com/questions/232445/https-connection-to-specific-sites-fail-with-curl-on-macos and also occurred https://github.com/Homebrew/homebrew-core/pull/55519 . Last time it was resolved by upstream changing their cert chain and solutions for a user include setting `CURL_SSL_BACKEND=secure-transport`, removing `AddTrust` from `/etc/ssl/cert.pem`, or using `curl` from homebrew instead of using the default mac curl.

The path of least resistance may be to to set the GitHub page (https://github.com/hashcat/hashcat) as the homepage and only have the GitHub source tar as the as the source url and have https://hashcat.net/hashcat/ left as a comment in the formula as the "real" homepage.

**Comment by bayandin** [comment]
There is an audit failure, which is expected:

```
==> brew audit hashcat --online --git --skip-style
==> FAILED
Error: 2 problems in 1 formula detected
hashcat:
  * The URL https://hashcat.net/hashcat/ is not reachable
  * Stable: The URL https://hashcat.net/files/hashcat-6.0.0.tar.gz is not reachable
```

**Pull request closed without merging**
