### PR TITLE
folly 2018.11.12.00

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
facebook/folly#961 has now been fixed via https://github.com/facebook/folly/commit/613f048bfb95c2a992d9446b5cc22a6a26214c39.

**Comment by lembacon** [comment]
Still failing on Sierra. 🙃

**Comment by Orvid** [comment]
What error is showing up on Sierra? (the CI link 404's)

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
`2018.11.19.00` is released.

**Pull request closed without merging**
