### PR TITLE
Bigloo 4.3b

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adapted from #23314.

cc @ilovezfs

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
/private/tmp/bigloo-20180208-85087-bq6bp8/bigloo4.3b/bin/bigloo.sh  -srfi enable-resolv -srfi enable-gmp -srfi enable-unistring -srfi enable-pcre -unsafe -q -mkheap -mklib -s -no-hello  -L /private/tmp/bigloo-20180208-85087-bq6bp8/bigloo4.3b/lib/bigloo/4.3b Llib/make_lib.scm -heap bigloo.heap
dyld: Library not loaded: /usr/local/Cellar/bigloo/4.3b/lib/bigloo/4.3b/libunistring.2.dylib
  Referenced from: /private/tmp/bigloo-20180208-85087-bq6bp8/bigloo4.3b/bin/bigloo
  Reason: image not found
```

**Comment by mistydemeo** [comment]
Couldn't repro at first, but it turns out that's because I have libunistring installed. Must not be installing the bundled version.

**Comment by mistydemeo** [comment]
OK, think this is fixed. Let's see what CI thinks, but it worked for me.

**Comment by mistydemeo** [comment]
```
dyld: Library not loaded: /usr/local/Cellar/bigloo/4.3b/lib/bigloo/4.3b/libpcre.1.dylib
  Referenced from: /private/tmp/bigloo-20180209-67566-f8imwh/bigloo4.3b/bin/bigloo
  Reason: image not found
make[1]: *** [heap-c] Abort trap: 6
make: *** [boot-c] Error 2
```

I guess the bundled pcre, too. :/

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thank you!

**Comment by iMichka** [comment]
```
Error: SHA256 mismatch
Expected: 5c6c864ebc9bce6d6f768da912e3cd099256ebb08c38c69f3181f71a7d424b55
Actual: 66cc535da9bd9e05cc30c40b4184398cee23341f9f5d49a18f371d7d3d2384da
Archive: /Users/michkapopoff/Library/Caches/Homebrew/bigloo-4.3b.tar.gz
```

We should have a newrule: for each sha256 mismatch, the package is directly removed from homebrew :)

**Comment by ilovezfs** [comment]
:(

**Comment by ilovezfs** [comment]
Wow it's even worse than that. See https://github.com/Homebrew/homebrew-core/pull/23314. The original PR had yet a different checksum from both of these.

**Comment by iMichka** [comment]
I subscribed to their mailing list and wrote them an email.

**Pull request closed without merging**
