### PR TITLE
coq 8.10.2

### PR DESCRIPTION
**Pull request by tchajed**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
math-comp test failed here, but I've merged 1.10.0 now so let's retry first in case the update fixes the issue.

@BrewTestBot test this please

**Comment by Bo98** [comment]
```
Compiled library mathcomp.ssreflect.ssreflect (in file /usr/local/Cellar/math-comp/1.10.0/lib/coq/user-contrib/mathcomp/ssreflect/ssreflect.vo) makes inconsistent assumptions over library Coq.ssr.ssreflect
```

Does math-comp need a revision bump? Or is there a deeper problem?

**Comment by tchajed** [comment]
It just needs a revision bump - it got built against Coq 8.10.1.

**Comment by Bo98** [comment]
Thanks

**Pull request closed without merging**
