### PR TITLE
git-cola 3.12.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to #93493

### CODE REVIEW

**Comment by davvid** [comment]
Thank you for fixing this!

**Comment by chenrui333** [comment]
yeah, trying to fix the build step, but I dont think it is re-buildable at the moment.

**Comment by branchvincent** [comment]
One observation: [`bin/git-cola`](https://github.com/git-cola/git-cola/blob/v3.11.0/bin/git-cola) is no longer getting installed, which is what allows `git-cola` to find its vendored `qtpy` (which is [the error that we're seeing](https://github.com/git-cola/git-cola/blob/ba15d5d8e1ab4e0ad5350fbc20e037bd9c952ea7/cola/app.py#L15-L27)). Instead it's just 

```python
#!/usr/local/opt/python@3.9/bin/python3.9
# EASY-INSTALL-SCRIPT: 'git-cola==3.11.0','git-cola'
__requires__ = 'git-cola==3.11.0'
__import__('pkg_resources').run_script('git-cola==3.11.0', 'git-cola')
```

**Comment by branchvincent** [comment]
Ok looks like an incompatibility with the `disutils` vendored by setuptools. Pushed a fix

**Comment by davvid** [comment]
Thanks for the fix @branchvincent !

I filed https://github.com/git-cola/git-cola/issues/1201 because I plan to drop py2 support (in the build system) and switch over to setuptools instead of distutils soon. If anyone has any recommendations as to how I should go about doing that, (eg. "please go look at this project and copy what they're doing because it makes it easier for packagers") please let me know.

I'll probably add PyQt5 as an official dependency to our requirements.txt at the same time. Just a heads-up that this is my top issue right now. I'm leaning towards making the next release a major version bump. If that plays out then we can drop the setuptools/distutils workaround in git-cola v4.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
