### PR TITLE
semgrep 0.112.0

### PR DESCRIPTION
**Pull request by brendongo**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Please also apply this patch:
```diff
diff --git a/Formula/semgrep.rb b/Formula/semgrep.rb
index cb35d108837..8d55daaa81d 100644
--- a/Formula/semgrep.rb
+++ b/Formula/semgrep.rb
@@ -36,10 +36,6 @@ class Semgrep < Formula
 
   uses_from_macos "rsync" => :build
 
-  on_linux do
-    depends_on "gcc"
-  end
-
   fails_with gcc: "5"
 
   resource "attrs" do
```
We build on Ubuntu 22.04 now, so it is no longer needed and will fail `brew audit` on Linux.

**Comment by chenrui333** [comment]
same audit dependency failure as #109943
```
  semgrep:
    * Libraries were compiled with a flat namespace.
      This can cause linker errors due to name collisions, and
      is often due to a bug in detecting the macOS version.
        /opt/homebrew/Cellar/semgrep/0.112.0/libexec/lib/python3.10/site-packages/semgrep/bin/semgrep_bridge_core.so
```

**Comment by carlocab** [comment]
@brendongo It looks like you are compiling `semgrep_bridge_core.so` as a `dylib` (by passing `-dylib` to the linker, perhaps indirectly through the compiler driver, which creates a file of type `MH_DYLIB`). This likely needs to be compiled with the `-bundle` flag instead, which creates an `MH_BUNDLE`.

**Comment by iMichka** [comment]
Superseded by #109943

**Pull request closed without merging**
