### PR TITLE
tclreadline 2.2.0 (new formula)

### PR DESCRIPTION
**Pull request by Mr-Tao**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren’t other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install —build-from-source <formula>`, where `<formula>` is the name of the formula you’re submitting?
- [x] Does your build pass `brew audit —strict <formula>` (after doing `brew install <formula>`)?
-----
_Tclreadline_ is indispensable tool for tinkering wit Tcl. Sadly it’s PITA to get it working on macOS. This formula applies latest patches from **Gentoo** and **Debian**.

### CODE REVIEW

**Comment by dbohdan** [comment]
Please consider using the [FlightAware fork](https://github.com/flightaware/tclreadline), which includes the Debian and Gentoo patches and more, has tests and is maintained. Disclosure: I worked on its v2.2.0 release.

**Comment by Mr-Tao** [comment]
I have no idea why checks are failing with CI machines. Only difference I can spot is that I do not have Xcode installed.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Since there does not appear to be an active upstream to which we can report any issues that may arise, I'm closing this, but thanks for the PR nonetheless @Mr-Tao. I think this might be a good fit for a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).

**Comment by Mr-Tao** [comment]
@ilovezfs the FlightAware fork that latest PR is using could be considered actively maintained. Why the formula is failing with build bots I have no idea. I bet the fact that this is my first attempt at writing a formula might have something to do with it. Shall anyone find it useful I have put it in the [tclreadline tap](https://github.com/Mr-Tao/homebrew-tclreadline).

**Pull request closed without merging**
