### PR TITLE
terraform 0.12.21

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by efernandes-ANDigital** [comment]
Any idea on when this will get merged in?

**Comment by SMillerDev** [comment]
When someone has time to merge it. We're all volunteers and you'll just have to wait until we volunteer our time to the thing you want.

**Comment by efernandes-ANDigital** [comment]
@SMillerDev That's fair

**Pull request closed without merging**
