### PR TITLE
telegraf 1.10.0

### PR DESCRIPTION
**Pull request by stevebang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by stevebang** [comment]
@fxcoudert Anything I need to do?

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
@stevebang Nothing to do on your side. The Mojave node of the CI had some hiccups recently. I relaunched it, we'll see how it goes.

**Comment by stevebang** [comment]
> @stevebang Nothing to do on your side. The Mojave node of the CI had some hiccups recently. I relaunched it, we'll see how it goes.

Thanks, @Moisan!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please
Should be fixed, now 🤞

**Comment by fxcoudert** [comment]
Thanks @stevebang

**Pull request closed without merging**
