### PR TITLE
imagemagick 7.0.11-14

### PR DESCRIPTION
**Pull request by nandahkrishna**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
ARM:
```
Error: 17 failed steps!
brew linkage --test blockhash
brew test --retry --verbose blockhash
brew linkage --test chafa
brew test --retry --verbose chafa
brew linkage --test dmtx-utils
brew test --retry --verbose dmtx-utils
brew test --retry --verbose imgproxy
brew linkage --test lanraragi
brew test --retry --verbose lanraragi
brew linkage --test pqiv
brew test --retry --verbose pqiv
brew linkage --test vapoursynth-imwri
brew test --retry --verbose vapoursynth-imwri
brew linkage --test vips
brew test --retry --verbose vips
brew linkage --test zbar
brew test --retry --verbose zbar
```
Will wait for Intel nodes to finish before pushing any more commits. Some, like `lanraragi` were pre-existing failures IIRC.

**Comment by carlocab** [comment]
`lanraragi` has a pre-existing `test` failure, but this is a linkage failure. The version bump here will break existing `lanraragi` installs (that I suspect are actually still working).

**Comment by carlocab** [comment]
In case `lanraragi` fails again, I wonder if setting
```ruby
ENV["LRR_LOG_DIRECTORY"] = testpath
```
would help.

**Comment by carlocab** [comment]
I don't think the `imgproxy` revision bump is needed. It's not a linkage failure. Indeed, the error log shows
```
==> Testing imgproxy
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210601-55365-1c508t.sb ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/imgproxy.rb --verbose --retry
dyld: Library not loaded: /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.9.dylib
  Referenced from: /usr/local/opt/vips/lib/libvips.42.dylib
  Reason: image not found
```
which means the `vips` revision bump should take care of the test failure.

**Comment by nandahkrishna** [comment]
Sorry, didn't look carefully enough. I'll drop that commit.

**Comment by nandahkrishna** [comment]
`lanraragi` built and tested fine locally, and on ARM CI as well.l

**Comment by Difegue** [comment]
> In case `lanraragi` fails again, I wonder if setting
> ```ruby
> ENV["LRR_LOG_DIRECTORY"] = testpath
> ```
> would help.
> 
> @Difegue, would this work? Or is there some other way to set the path where it writes its logs?

If the failure comes from the app being unable to write its logs, then yes this env var allows you to change it. 👍

**Comment by carlocab** [comment]
Cool, thanks. Let's give that a try. #78466

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
> 🤖 A scheduled task has [triggered a merge](https://github.com/Homebrew/homebrew-core/actions/runs/896395293).

This won't work. Will merge manually.

**Pull request closed without merging**
