### PR TITLE
skaffold@1.39 1.39.4 (new formula)

### PR DESCRIPTION
**Pull request by andrasmaroy**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions) and why we might want to ship an older version?

**Comment by andrasmaroy** [comment]
The motivation behind shipping the older version is that as noted by the major version change there are breaking changes between version 1.x and 2.x of Skaffold that make it incompatible with existing projects without significant effort on the user's side updating markup files used by Skaffold.

This effort is not always feasible hence the preference to use the older, still compatible version.

As far as the versioned formula requirements this should fit all, the only one I don't have data about is the number of users using this, I can see that the Skaffold formula is on number 346 on the top used list with almost 64k events, so I'd assume it's a fairly safe bet that 3000 people will use the versioned formula as well.
Does this answer your question @SMillerDev?

**Comment by SMillerDev** [comment]
Can you link me to the support page for the 1.x branch?

**Comment by andrasmaroy** [comment]
I'm not sure about a specific support page, but they have a specific site for v1: https://skaffold-v1.web.app/

They are actively supporting v1, the latest release was just over a month ago: https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.39.4

**Comment by SMillerDev** [comment]
That page says the following though:

> Version v1.39 of the documentation is no longer actively maintained. The site that you are currently viewing is an archived snapshot. For up-to-date documentation, see the latest version.

**Comment by SMillerDev** [comment]
Long story short, if you can get upstream to set an EOL for v1 so we can add a deprecation accordingly I'm fine with merging this.

**Comment by andrasmaroy** [comment]
Found the actual support site: https://cloud.google.com/deploy/docs/using-skaffold/select-skaffold#skaffold_version_deprecation_and_maintenance_policy

They are maintaining 1.39 until October 18, 2023

**Comment by andrasmaroy** [comment]
> Found the actual support site: https://cloud.google.com/deploy/docs/using-skaffold/select-skaffold#skaffold_version_deprecation_and_maintenance_policy
> 
> They are maintaining 1.39 until October 18, 2023

Added this as deprecation date to the formula.

**Review by SMillerDev — APPROVED** [review]
Thanks @andrasmaroy  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
