### PR TITLE
yle-dl 20200419

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
```
 ==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/yle-dl/20200419/libexec/vendor --install-scripts=/usr/local/Cellar/yle-dl/20200419/libexec/vendor/bin --single-version-externally-managed --record=installed.txt
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 7, in <module>
    from setuptools import Feature, setup
ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.7/site-packages/setuptools/__init__.py)
```

**Comment by chenrui333** [comment]
This is little bit weird, didn't the CI show green?

**Comment by Bo98** [comment]
Because of a bug in homebrew-test-bot. No pull requests in the last ~8 hours or so until about 30 minutes ago will have shown red.

**Comment by chenrui333** [comment]
relates to https://github.com/pypa/setuptools/issues/2017

> If it causes problems for you I think pinning to setuptools < 46 while you find another solution is the right way to go.

**Pull request closed without merging**
