### PR TITLE
kind 0.8.1

### PR DESCRIPTION
**Pull request by lonre**
kind 0.8.0

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks @lonre! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by northrup** [comment]
🤔 I guess I don't understand how bottles work given this setup?

**Comment by Bo98** [comment]
It was a network blip it looks like. GitHub's upload workflow isn't exactly reliable.

A rebase to trigger a new CI run should work.

**Comment by chenrui333** [comment]
Updated to the latest release 0.8.1 and rebased to the master.

**Pull request closed without merging**
