### PR TITLE
python@3.9 3.9.5

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__init__.py:
  expected replacement of "    (\"pip\", _PIP_VERSION, \"py2.py3\")," with "    (\"pip\", _PIP_VERSION, \"py3\"),"
```

**Comment by carlocab** [comment]
Looks like the last `inreplace` here is failing:

https://github.com/Homebrew/homebrew-core/blob/7fd84fcfb65ae8a5faa90356020c2ae00bfbc8ad/Formula/python%403.9.rb#L280-L285

Maybe it's no longer needed? CC @Bo98

**Comment by Bo98** [comment]
Yes, the last one was temporary until upstream also bundled Pip 21+, which they now do and thus have also made that change.

The others are permanent.

**Comment by carlocab** [comment]
```diff
diff --git a/Formula/python@3.9.rb b/Formula/python@3.9.rb
index e4216301dbe..703fdae4fdf 100644
--- a/Formula/python@3.9.rb
+++ b/Formula/python@3.9.rb
@@ -66,13 +66,13 @@ class PythonAT39 < Formula
   link_overwrite "Frameworks/Python.framework/Versions/Current"
 
   resource "setuptools" do
-    url "https://files.pythonhosted.org/packages/94/75/05e1d69c61c4dfaf65ad12785cd18bedc1e0129976c55914d6aea59c7da8/setuptools-54.2.0.tar.gz"
-    sha256 "aa9c24fb83a9116b8d425e53bec24c7bfdbffc313c2159f9ed036d4a6dd32d7d"
+    url "https://files.pythonhosted.org/packages/f6/e9/19af16328705915233299f6f1f02db95899fb00c75ac9da4757aa1e5d1de/setuptools-56.0.0.tar.gz"
+    sha256 "08a1c0f99455307c48690f00d5c2ac2c1ccfab04df00454fef854ec145b81302"
   end
 
   resource "pip" do
-    url "https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz"
-    sha256 "99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5"
+    url "https://files.pythonhosted.org/packages/94/b0/e10bdc8809c81796c80aa3644a8e3dc16594fb1bd68f5996929f26cad980/pip-21.1.1.tar.gz"
+    sha256 "51ad01ddcd8de923533b01a870e7b987c2eb4d83b50b89e1bf102723ff9fed8b"
   end
 
   resource "wheel" do
```

**Comment by branchvincent** [comment]
will take care of both of those issues soon

**Comment by branchvincent** [comment]
```
Error: 9 failed steps!
brew test --retry --verbose cargo-watch
brew test --retry --verbose flann
brew test --retry --verbose game-music-emu
brew test --retry --verbose innotop
brew test --retry --verbose libbi
brew test --retry --verbose monkeysphere
brew test --retry --verbose mytop
brew install --only-dependencies paket
brew install paket
```

**Comment by carlocab** [comment]
All ARM failures look pre-existing.

**Comment by carlocab** [comment]
Big Sur

```
Error: 7 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose cargo-watch
brew test --retry --verbose creduce
brew test --retry --verbose flann
brew test --retry --verbose hyperkit
brew test --retry --verbose wasm-pack
brew test --retry --verbose youtube-dlc
```

Catalina

```
Error: 5 failed steps!
brew test --retry --verbose cargo-watch
brew test --retry --verbose flann
brew test --retry --verbose hyperkit
brew test --retry --verbose wasm-pack
brew test --retry --verbose youtube-dlc
```

Mojave

```
Error: 7 failed steps!
brew test --retry --verbose caffe
brew test --retry --verbose cargo-watch
brew test --retry --verbose flann
brew test --retry --verbose hyperkit
brew test --retry --verbose swift
brew test --retry --verbose wasm-pack
brew test --retry --verbose youtube-dlc
```

All look either pre-existing or spurious. `caffe` test failures happen intermittently, and `flann` is from a resource download failure.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
