### PR TITLE
cargo-outdated: use libgit2@1.7

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
See https://github.com/Homebrew/homebrew-core/issues/177686

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
@alex small audit fix:

```
Full style homebrew/core output
  Taps/homebrew/homebrew-core/Formula/c/cargo-outdated.rb:13:3: C: [Correctable] FormulaAudit/ComponentsOrder: revision (line 13) should be put before head (line 12)
    revision 1
    ^^^^^^^^^^
```

**Comment by p-linnane** [comment]
Fixes https://github.com/Homebrew/homebrew-core/issues/177686.

**Review by woodruffw — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by alex** [comment]
Thanks for the cleanups! (Sorry I sent this and then immediately went out for 6 hours)

**Pull request merged**
