### PR TITLE
rbenv-readline: migrate to boneyard

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
See https://github.com/tpope/rbenv-readline/commit/7d9eb3919ecee1437d7ddf40a5c9983e668590f3

"Document obsolescence"

**Comment by MikeMcQuaid** [comment]
Oh neat. I had this installed and never noticed 😬

**Comment by ilovezfs** [comment]
@MikeMcQuaid looks like it was @mislav's handiwork! https://github.com/tpope/rbenv-readline/issues/3

**Comment by MikeMcQuaid** [comment]
Ouch, more than two years ago!

**Review by mislav — APPROVED** [review]

**Pull request merged**
