### PR TITLE
terraform 0.6.16

### PR DESCRIPTION
**Pull request by chulkilee**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- use built-in `make`

### CODE REVIEW

**Comment by DomT4** [comment]
> use built-in make

Please keep it how it was. The `Makefile` executes a `go get` if it can't find `gox` and we don't _intentionally_ let build processes do remote fetching.

**Comment by mikemcquaid** [comment]
Also: feel free to add a comment explaining this 😆

**Comment by chulkilee** [comment]
I understand the concern, but for me it is much simpler to update the formula. Note that that `go get` will install files inside the private tmp directory anyway. Also using `make` is more future-proof for building the head.

I'd leave it for other contributors - thanks for the feedback!

**Comment by mikemcquaid** [comment]
@chulkilee We need it changed back to merge this formula.

**Comment by dunn** [comment]
Closing this; if you'd like to make the requested changes let us know and we'll re-open it.  Either way, thank you for the submission!

**Pull request closed without merging**
