### PR TITLE
hg-fast-export: fix python3 reference

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
This is a very odd failure - it only affects 12 but not older macOS or Linux.

**Comment by cho-m** [comment]
We seen some git-related formulae recently fail test on Monterey runner, which seems to be from  `git init` defaulting to `main` branch rather than `master`. Could be impacting `hg-fast-export` too.

**Comment by danielnachun** [comment]
Yeah I see those now after Python 3.10.7.  I will try that fix here.

**Comment by cho-m** [comment]
I fixed the others in #112138 with 
```rb
system "git", "config", "--global", "init.defaultBranch", "master"
```

I tried a few other options but they had issues on older git versions like `git init -b master` (not supported on older git) and `git branch -M master` (older git needs at least one commit before rename).

**Comment by danielnachun** [comment]
I tried that fix locally and it seems to work.  We'll see now if that is true in CI.

**Comment by danielnachun** [comment]
That fixed it. Thanks @cho-m!  This is ready to go when CI is done.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
