### PR TITLE
typst 23-03-28 (new formula)

### PR DESCRIPTION
**Pull request by bobby-b-song**
Grabs the newest release from typst, **NOTE** that the current latest release won't compile by cargo (even manually) on M2 machines <https://github.com/typst/typst/issues/110>. Please use the `--HEAD` option if it doesn't work on your machine.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bsong0** [comment]
Any followups on this?

**Comment by SMillerDev** [comment]
I'm still not sure what other people can do about that

**Comment by bsong0** [comment]
I updated the release version of the formula; it works rn.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
let's also make sure the commit got squashed before the straight merge

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@bsong0, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request merged**
