### PR TITLE
ffmpeg 6.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

---

closes #156455

### CODE REVIEW

**Comment by chenrui333** [comment]
```
brew install --only-dependencies openai-whisper
brew link pytorch
brew test --retry --verbose openai-whisper
```

**Comment by xqq** [comment]
Is this pull request trying to create an FFmpeg 6.1 release? If so, the title should be changed :)

@chenrui333 
Excuse me. I have a feature request here.

Could you please enable the libaribcaption dependence since FFmpeg 6.1? It has been [officially included in the 6.1 release](https://github.com/FFmpeg/FFmpeg/blob/master/Changelog#L8) which has been already [provided as a package in Homebrew](https://github.com/Homebrew/homebrew-core/pull/147410).

Simply add a `depend_on "libaribcaption"` and then turn on `--enable-libaribcaption` for the configure options.

Thank you!

Regards

Reference:
https://github.com/Homebrew/homebrew-core/pull/117592/files
https://github.com/BtbN/FFmpeg-Builds/pull/319
https://github.com/BtbN/FFmpeg-Builds/commit/9a0acacbd1d8a668528b9f7c32bef09d86eab639

**Comment by chenrui333** [comment]
just updated the PR title.

will do the deprecation and build option change, need to sort out some dependency issues first.

**Comment by ilya-lavrenov** [comment]
> Is this pull request trying to create an FFmpeg 6.1 release? If so, the title should be changed :)
> 
> @chenrui333 Excuse me. I have a feature request here.
> 
> Could you please enable the libaribcaption dependence since FFmpeg 6.1? It has been [officially included in the 6.1 release](https://github.com/FFmpeg/FFmpeg/blob/master/Changelog#L8) which has been already [provided as a package in Homebrew](https://github.com/Homebrew/homebrew-core/pull/147410).
> 
> Simply add a `depend_on "libaribcaption"` and then turn on `--enable-libaribcaption` for the configure options.
> 
> Thank you!
> 
> Regards
> 
> Reference: https://github.com/Homebrew/homebrew-core/pull/117592/files [BtbN/FFmpeg-Builds#319](https://github.com/BtbN/FFmpeg-Builds/pull/319) [BtbN/FFmpeg-Builds@9a0acac](https://github.com/BtbN/FFmpeg-Builds/commit/9a0acacbd1d8a668528b9f7c32bef09d86eab639)

similarly, we can add `openvino` dependency

reference https://github.com/Homebrew/homebrew-core/pull/141230/files

**Comment by bevanjkay** [comment]
@chenrui333 Is this ready for a rebase / rerun after #154197 fixed the conflict?

**Comment by bevanjkay** [comment]
@chenrui333 Is this ready for a rebase / rerun after https://github.com/Homebrew/homebrew-core/pull/154197 fixed the conflict?

**Comment by dericed** [comment]
I see two open ffmpeg 6.1 pull requests. I suggest prioritizing https://github.com/Homebrew/homebrew-core/pull/156455. Between ffpmeg 6.0 and 6.1, the drawtext filter added a dependency on libharfbuzz, so PR #156455 would maintain drawtext, whereas that filter (an important one) would be lost in this update from a newly unmet dependency.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
