### PR TITLE
gflags: added static libraries

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Most other distributions of gflags contain static gflags as well: e.g. all Debian systems.
So, the goal is to be aligned here, so users can use the same way of linking independently on package managers.

Added tests that linker is able to find both static and dynamic versions of libraries.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
```
Error: PR requires the CI-long-timeout label but it is not set!
[142](https://github.com/Homebrew/homebrew-core/actions/runs/3786752297/jobs/6437993624#step:2:143)
Error: If the longer timeout is not required, remove the "long build" label.
[143](https://github.com/Homebrew/homebrew-core/actions/runs/3786752297/jobs/6437993624#step:2:144)
Error: Otherwise, add the "CI-long-timeout" label.
[144](https://github.com/Homebrew/homebrew-core/actions/runs/3786752297/jobs/6437993624#step:2:145)
Error: No more than 2 PRs at a time may use "CI-long-timeout".
```

**Comment by chenrui333** [comment]
> ```
> Error: PR requires the CI-long-timeout label but it is not set!
> [142](https://github.com/Homebrew/homebrew-core/actions/runs/3786752297/jobs/6437993624#step:2:143)
> Error: If the longer timeout is not required, remove the "long build" label.
> [143](https://github.com/Homebrew/homebrew-core/actions/runs/3786752297/jobs/6437993624#step:2:144)
> Error: Otherwise, add the "CI-long-timeout" label.
> [144](https://github.com/Homebrew/homebrew-core/actions/runs/3786752297/jobs/6437993624#step:2:145)
> Error: No more than 2 PRs at a time may use "CI-long-timeout".
> ```

no need to post that, we are aware of all the `long build` PRs.

**Comment by chenrui333** [comment]
rebased the PR to the latest master for the style fixes ([failure run](https://github.com/Homebrew/homebrew-core/actions/runs/3786752297/jobs/6457659959))

**Comment by chenrui333** [comment]
```
  ==> cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/gflags/2.2.2 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  CMake Error: Unable to (re)create the private pkgRedirects directory:
  /tmp/gflags-20221230-4194-16ng8x6/gflags-2.2.2/build/CMakeFiles/pkgRedirects
```

**Comment by ilya-lavrenov** [comment]
> ==> cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/gflags/2.2.2 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
>   CMake Error: Unable to (re)create the private pkgRedirects directory:
>   /tmp/gflags-20221230-4194-16ng8x6/gflags-2.2.2/build/CMakeFiles/pkgRedirects

It's internal cmake error, wondering why it happens.. 
The reason is [this](e0bd80f439656494ac6a68a9bc7741130bf2fa27) commit, which uses `-B` option. With old syntax everything works well locally. I've reverted the commit

**Comment by chenrui333** [comment]
> > ==> cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/gflags/2.2.2 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
> > CMake Error: Unable to (re)create the private pkgRedirects directory:
> > /tmp/gflags-20221230-4194-16ng8x6/gflags-2.2.2/build/CMakeFiles/pkgRedirects
> 
> It's [internal cmake error](https://gitlab.kitware.com/cmake/cmake/blob/master/Source/cmake.cxx#L2293-2306), wondering why it happens.. The reason is [this](e0bd80f439656494ac6a68a9bc7741130bf2fa27) commit, which uses `-B` option. With old syntax everything works well locally. I've reverted the commit

can we submit a PR to update the cmake syntax in the upstream?

**Comment by chenrui333** [comment]
rerun the job.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
