### PR TITLE
pgcli: use python2.7 instead of python

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
cc @sjackman @ilovezfs

**Comment by ilovezfs** [comment]
for now, only interested in doing these if there's a mixed python 2 and python 3 dependency tree or it's in the test block

**Comment by iMichka** [comment]
Will this not use brewed python3 if python3 is installed and in the path?

Your call, I'll make the change in Linuxbrew only then :)

**Comment by ilovezfs** [comment]
superenv filters that out unless we're in the test block.

**Comment by iMichka** [comment]
Also if it is in /usr/bin? (which will not happen on mac because there python is system python, but on Linux that version can be some random python 2 or 3). So this is not a real argument.

Also, you have:
> depends_on "python@2" if MacOS.version <= :snow_leopard

This means that on snow leopard you install python@2 but you use system python to build?

**Comment by ilovezfs** [comment]
>depends_on "python@2" if MacOS.version <= :snow_leopard

Yeah, I've left those there for now so that we know what uses system Python not because I expect them to work.

**Comment by iMichka** [comment]
Ok. In case you change your mind, I can help here and make the needed changes. I think there are around 190 places in brew where this might need to be changed. If the snow leopard people want to help, that would be great too.

I'm off for the weekend with limited internet connection; but I can help change this next week if you want. I'll make the changes in Linuxbrew only in the meantime.

**Pull request closed without merging**
