### PR TITLE
istioctl 1.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>Build failure</summary>
23:33:28 go: downloading istio.io/pkg v0.0.0-20200204185554-47b6d38ec784
23:33:28 go: downloading k8s.io/api v0.17.2
23:33:28 go: downloading k8s.io/client-go v0.17.2
23:33:28 go: downloading github.com/spf13/cobra v0.0.5
23:33:28 go: downloading istio.io/api v0.0.0-20200227213531-891bf31f3c32
23:33:28 go: downloading k8s.io/apimachinery v0.17.2
23:33:28 go: downloading github.com/gogo/protobuf v1.3.0
23:33:28 go: downloading github.com/envoyproxy/go-control-plane v0.9.4
23:33:28 go: downloading google.golang.org/grpc v1.26.0
23:33:28 go: downloading github.com/gorilla/websocket v1.4.1
23:33:28 go: downloading github.com/istio/viper v1.3.3-0.20190515210538-2789fed3109c
23:33:28 go: downloading github.com/google/uuid v1.1.1
23:33:28 go: downloading github.com/ghodss/yaml v1.0.0
23:33:28 go: downloading github.com/golang/protobuf v1.3.2
23:33:28 go: downloading github.com/fsnotify/fsnotify v1.4.7
23:33:28 go: downloading github.com/spf13/afero v1.2.2
23:33:28 go: downloading sigs.k8s.io/yaml v1.1.0
23:33:28 go: downloading golang.org/x/tools v0.0.0-20191216173652-a0e659d51361
23:33:28 go: downloading github.com/opentracing/opentracing-go v1.0.2
23:33:28 go: downloading go.opencensus.io v0.22.2
23:33:28 go: downloading github.com/coreos/go-oidc v2.1.0+incompatible
23:33:28 go: downloading github.com/hashicorp/go-multierror v1.0.0
23:33:28 go: downloading github.com/uber/jaeger-client-go v0.0.0-20190228190846-ecf2d03a9e80
23:33:28 go: downloading github.com/spf13/cast v1.3.1
23:33:28 go: downloading istio.io/gogo-genproto v0.0.0-20200130224810-a0338448499a
23:33:28 go: downloading golang.org/x/text v0.3.2
23:33:28 go: downloading contrib.go.opencensus.io/exporter/prometheus v0.1.0
23:33:28 go: downloading github.com/mitchellh/mapstructure v1.1.2
23:33:28 go: downloading golang.org/x/net v0.0.0-20191014212845-da9a3fd4c582
23:33:28 go: downloading github.com/cncf/udpa/go v0.0.0-20191209042840-269d4d468f6f
23:33:28 go: downloading github.com/spaolacci/murmur3 v0.0.0-20180118202830-f09979ecbc72
23:33:28 go: downloading github.com/google/go-cmp v0.3.1
23:33:28 go: downloading google.golang.org/genproto v0.0.0-20191223191004-3caeed10a8bf
23:33:28 go: downloading github.com/Azure/go-autorest/autorest v0.9.0
23:33:28 go: downloading github.com/google/gofuzz v1.0.0
23:33:28 go: downloading github.com/json-iterator/go v1.1.9
23:33:28 go: downloading github.com/modern-go/reflect2 v1.0.1
23:33:28 go: downloading k8s.io/kube-openapi v0.0.0-20191107075043-30be4d16710a
23:33:28 go: downloading github.com/istio/klog v0.0.0-20190424230111-fb7481ea8bcf
23:33:28 go: downloading go.uber.org/atomic v1.4.0
23:33:28 go: downloading github.com/spf13/jwalterweatherman v1.1.0
23:33:28 go: downloading k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
23:33:28 go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
23:33:28 go: downloading k8s.io/apiextensions-apiserver v0.17.2
23:33:28 go: downloading github.com/cpuguy83/go-md2man v1.0.10
23:33:28 go: downloading github.com/golang/sync v0.0.0-20180314180146-1d60e4601c6f
23:33:28 go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
23:33:28 go: downloading github.com/uber/jaeger-lib v2.0.0+incompatible
23:33:28 go: downloading github.com/hashicorp/consul v1.3.1
23:33:28 go: downloading github.com/gophercloud/gophercloud v0.1.0
23:33:28 go: downloading github.com/googleapis/gnostic v0.3.1
23:33:28 go: downloading github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20171214222146-0e7658f8ee99
23:33:28 go: downloading github.com/prometheus/client_golang v1.1.0
23:33:28 go: downloading github.com/davecgh/go-spew v1.1.1
23:33:28 go: downloading gopkg.in/inf.v0 v0.9.1
23:33:28 go: downloading github.com/hashicorp/hcl v1.0.0
23:33:28 go: downloading github.com/pquerna/cachecontrol v0.0.0-20180306154005-525d0eb5f91d
23:33:28 go: downloading github.com/hashicorp/errwrap v1.0.0
23:33:28 go: downloading go.uber.org/zap v1.10.0
23:33:28 go: downloading gopkg.in/yaml.v2 v2.2.7
23:33:28 go: downloading github.com/natefinch/lumberjack v2.0.0+incompatible
23:33:28 go: downloading github.com/magiconair/properties v1.8.1
23:33:28 go: downloading github.com/envoyproxy/protoc-gen-validate v0.1.0
23:33:28 go: downloading github.com/yl2chen/cidranger v0.0.0-20180214081945-928b519e5268
23:33:28 go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
23:33:28 go: downloading github.com/google/cel-go v0.2.0
23:33:28 go: downloading github.com/imdario/mergo v0.3.7
23:33:28 go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
23:33:28 go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.0.1-0.20190118093823-f849b5445de4
23:33:28 go: downloading github.com/openshift/api v3.9.1-0.20191008181517-e4fd21196097+incompatible
23:33:28 go: downloading cloud.google.com/go v0.50.0
23:33:28 go: downloading go.uber.org/multierr v1.1.0
23:33:28 go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
23:33:28 go: downloading github.com/Azure/go-autorest/tracing v0.5.0
23:33:28 go: downloading github.com/gorilla/mux v1.7.3
23:33:28 go: downloading github.com/Azure/go-autorest/autorest/adal v0.5.0
23:33:28 go: downloading github.com/howeyc/fsnotify v0.9.0
23:33:28 go: downloading github.com/mitchellh/copystructure v1.0.0
23:33:28 go: downloading github.com/cenkalti/backoff v2.0.0+incompatible
23:33:28 go: downloading github.com/aws/aws-sdk-go v1.23.20
23:33:28 go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
23:33:28 go: downloading github.com/go-redis/redis v6.10.2+incompatible
23:33:28 go: downloading github.com/prometheus/common v0.6.0
23:33:28 go: downloading github.com/mitchellh/reflectwalk v1.0.1
23:33:28 go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
23:33:28 go: downloading gopkg.in/square/go-jose.v2 v2.3.1
23:33:28 go: downloading github.com/beorn7/perks v1.0.1
23:33:28 go: downloading github.com/openzipkin/zipkin-go v0.1.7
23:33:28 go: downloading github.com/googleapis/gax-go v2.0.2+incompatible
23:33:28 go: downloading github.com/pelletier/go-toml v1.3.0
23:33:28 go: downloading golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
23:33:28 go: downloading sigs.k8s.io/controller-runtime v0.4.0
23:33:28 go: downloading contrib.go.opencensus.io/exporter/zipkin v0.1.1
23:33:28 go: downloading github.com/Azure/go-autorest/autorest/date v0.1.0
23:33:28 go: downloading github.com/go-logr/logr v0.1.0
23:33:28 go: downloading contrib.go.opencensus.io/exporter/stackdriver v0.12.9
23:33:28 go: downloading github.com/Azure/go-autorest/logger v0.1.0
23:33:28 go: downloading github.com/hashicorp/vault/api v1.0.3
23:33:28 go: downloading cloud.google.com/go/logging v1.0.0
23:33:28 go: downloading github.com/spf13/pflag v1.0.5
23:33:28 go: downloading google.golang.org/api v0.15.0
23:33:28 go: downloading github.com/census-instrumentation/opencensus-proto v0.2.1
23:33:28 go: downloading github.com/prometheus/procfs v0.0.8
23:33:28 go: downloading github.com/hashicorp/golang-lru v0.5.4
23:33:28 go: downloading github.com/hashicorp/vault/sdk v0.1.12
23:33:28 go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
23:33:28 go: downloading github.com/googleapis/gax-go/v2 v2.0.5
23:33:28 go: downloading github.com/fluent/fluent-logger-golang v1.3.0
23:33:28 go: downloading github.com/open-policy-agent/opa v0.8.2
23:33:28 go: downloading github.com/golang/groupcache v0.0.0-20191027212112-611e8accdfc9
23:33:28 go: downloading github.com/tinylib/msgp v1.0.2
23:33:28 go: downloading github.com/mattn/go-isatty v0.0.12
23:33:28 go: downloading github.com/hashicorp/go-version v1.2.0
23:33:28 go: downloading github.com/russross/blackfriday v1.5.2
23:33:28 go: downloading github.com/ryanuber/go-glob v1.0.0
23:33:28 go: downloading github.com/golang/snappy v0.0.1
23:33:28 go: downloading github.com/pkg/errors v0.8.1
23:33:28 go: downloading github.com/pierrec/lz4 v2.2.7+incompatible
23:33:28 go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
23:33:28 go: downloading golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898
23:33:28 go: downloading github.com/docker/spdystream v0.0.0-20181023171402-6480d4af844c
23:33:28 go: downloading github.com/hashicorp/go-rootcerts v1.0.1
23:33:28 go: downloading github.com/antlr/antlr4 v0.0.0-20190223165740-dade65a895c2
23:33:28 go: downloading github.com/hashicorp/serf v0.8.5
23:33:28 go: downloading github.com/evanphx/json-patch v4.5.0+incompatible
23:33:28 go: downloading github.com/pmezard/go-difflib v1.0.0
23:33:28 go: downloading github.com/yashtewari/glob-intersection v0.0.0-20180206001645-7af743e8ec84
23:33:28 go: downloading github.com/prometheus/prom2json v1.2.2
23:33:28 go: downloading gopkg.in/fsnotify.v1 v1.4.7
23:33:28 go: downloading github.com/DataDog/datadog-go v2.2.0+incompatible
23:33:28 go: downloading github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
23:33:28 go: downloading k8s.io/helm v2.14.3+incompatible
23:33:28 go: downloading github.com/mholt/archiver v3.1.1+incompatible
23:33:28 go: downloading gomodules.xyz/jsonpatch/v2 v2.0.1
23:33:28 go: downloading github.com/dchest/siphash v1.1.0
23:33:28 go: downloading golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
23:33:28 go: downloading github.com/kr/pretty v0.1.0
23:33:28 go: downloading github.com/cactus/go-statsd-client v3.1.1+incompatible
23:33:28 go: downloading github.com/philhofer/fwd v1.0.0
23:33:28 go: downloading k8s.io/cli-runtime v0.17.2
23:33:28 go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
23:33:28 go: downloading github.com/docker/distribution v2.7.1+incompatible
23:33:28 go: downloading github.com/circonus-labs/circonus-gometrics v2.3.1+incompatible
23:33:28 go: downloading github.com/hashicorp/go-sockaddr v1.0.2
23:33:28 go: downloading github.com/xi2/xz v0.0.0-20171230120015-48954b6210f8
23:33:28 go: downloading github.com/kr/text v0.1.0
23:33:28 go: downloading github.com/kylelemons/godebug v1.1.0
23:33:28 go: downloading k8s.io/kubectl v0.17.2
23:33:28 go: downloading github.com/mitchellh/go-homedir v1.1.0
23:33:28 go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
23:33:28 go: downloading sigs.k8s.io/kustomize v2.0.3+incompatible
23:33:28 go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
23:33:28 go: downloading github.com/nwaples/rardecode v1.0.0
23:33:28 go: downloading github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79
23:33:28 go: downloading github.com/google/btree v1.0.0
23:33:28 go: downloading github.com/tv42/httpunix v0.0.0-20191220191345-2ba4b9c3382c
23:33:28 go: downloading github.com/ulikunitz/xz v0.5.6
23:33:28 go: downloading github.com/armon/go-metrics v0.0.0-20180917152333-f0300d1749da
23:33:28 go: downloading github.com/circonus-labs/circonusllhist v0.1.4
23:33:28 go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
23:33:28 go: downloading github.com/hashicorp/go-immutable-radix v1.0.0
23:33:28 go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
23:33:28 go: downloading github.com/dsnet/compress v0.0.1
23:33:28 go: downloading github.com/cyphar/filepath-securejoin v0.2.2
23:33:28 go: downloading github.com/BurntSushi/toml v0.3.1
23:33:28 go: downloading github.com/Masterminds/sprig v2.14.1+incompatible
23:33:28 go: downloading github.com/emicklei/go-restful v2.9.6+incompatible
23:33:28 go: downloading github.com/gobwas/glob v0.2.3
23:33:28 go: downloading github.com/go-openapi/spec v0.19.5
23:33:28 go: downloading github.com/Masterminds/semver v1.4.2
23:33:28 go: downloading github.com/huandu/xstrings v1.2.1
23:33:28 go: downloading github.com/aokoli/goutils v1.0.1
23:33:28 go: downloading github.com/satori/go.uuid v1.2.0
23:33:28 go: downloading github.com/go-openapi/jsonreference v0.19.3
23:33:28 go: downloading github.com/go-openapi/swag v0.19.6
23:33:28 go: downloading github.com/go-openapi/jsonpointer v0.19.3
23:33:28 go: downloading github.com/PuerkitoBio/purell v1.1.1
23:33:28 go: downloading github.com/mailru/easyjson v0.7.0
23:33:28 go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
23:33:28 
23:33:28 real	3m20.886s
23:33:28 user	9m3.733s
23:33:28 sys	2m21.956s
23:33:28 Error: An exception occurred within a child process:
23:33:28   Errno::ENOENT: No such file or directory - /private/tmp/istioctl-20200306-77887-zlyi53/out/darwin_amd64/release/istioctl
</details>

**Comment by oreissig** [comment]
What's the state here? any need for help?

**Comment by Bo98** [comment]
@chenrui333 Upstream use Go modules now so the build steps can probably be simplified to avoid `GOPATH`.

**Review by howardjohn — APPROVED** [review]

**Comment by chenrui333** [comment]
Closing in favor of the new release.

**Pull request closed without merging**
