### PR TITLE
pulumi 1.3.1

### PR DESCRIPTION
**Pull request by pgavlin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by pgavlin** [comment]
Test failure appears to be an unreachable server when running `go mod vendor`. Hopefully this is a transient issue and a re-run will be successful.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by pgavlin** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @pgavlin !!

**Pull request closed without merging**
