### PR TITLE
kubectx 0.4.1

### PR DESCRIPTION
**Pull request by ahmetb**
Created manually.

- stop installing utils.bash, as it no longer exists
- add fish completion script

### CODE REVIEW

**Comment by ilovezfs** [comment]
https://github.com/ahmetb/kubectx/releases/latest is still pointing at 0.4.0

**Comment by ahmetb** [comment]
I wasn't aware that homebrew needed a release to be made from the tag.

Thanks for notifying. Just fixed.

**Comment by ilovezfs** [comment]
>I wasn't aware that homebrew needed a release to be made from the tag.

We want `https://github.com/ahmetb/kubectx/releases/latest` to match. So that means if you ever do GitHub releases, you should always do GitHub releases. The alternative would be to remove the explicit GitHub releases (removing them won't delete the tags), in which `https://github.com/ahmetb/kubectx/releases/latest` just becomes a redirect to `https://github.com/ahmetb/kubectx/releases`, and then you only need to do tags.

There's an API for GitHub releases if you want to avoid doing it manually: https://developer.github.com/v3/repos/releases/

**Comment by ahmetb** [comment]
That makes sense, thanks!

**Comment by ilovezfs** [comment]
Thanks @ahmetb!

**Pull request merged**
