### PR TITLE
clickhouse-cpp 2.2.0

### PR DESCRIPTION
**Pull request by traceon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by traceon** [comment]
Closing, until fixed.

**Comment by chenrui333** [comment]
/opt/homebrew/Cellar/clickhouse-cpp/2.2.0/include/clickhouse/columns/../exceptions.h:3:10: fatal error: 'server_exception.h' file not found
  #include "server_exception.h"
           ^~~~~~~~~~~~~~~~~~~~
  1 error generated.

**Comment by chenrui333** [comment]
Do we have any upstream issue tracker?

**Comment by traceon** [comment]
Opened a fixed one: #107158

**Pull request closed without merging**
