### PR TITLE
cocoapods 1.9.0

### PR DESCRIPTION
**Pull request by samford**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by samford** [comment]
```
==> gem install cocoapods-1.9.0.gem
Successfully installed ruby-macho-1.4.0
Successfully installed nap-1.1.0
Successfully installed gh_inspector-1.1.3
Successfully installed fourflusher-2.3.1
Successfully installed escape-0.0.4
Successfully installed colored2-3.1.2
Successfully installed thread_safe-0.3.6
Successfully installed tzinfo-1.2.6
Successfully installed concurrent-ruby-1.1.6
Successfully installed i18n-0.9.5
Successfully installed activesupport-4.2.11.1
Successfully installed atomos-0.1.3
Successfully installed CFPropertyList-3.0.2
Successfully installed claide-1.0.3
Successfully installed nanaimo-0.2.6
Successfully installed xcodeproj-1.15.0
Successfully installed molinillo-0.6.6
Successfully installed cocoapods-try-1.1.0
Successfully installed netrc-0.11.0
Successfully installed cocoapods-trunk-1.4.1
Successfully installed cocoapods-stats-1.1.0
Successfully installed cocoapods-search-1.0.0
Successfully installed cocoapods-plugins-1.0.0
Successfully installed cocoapods-downloader-1.3.0
Successfully installed cocoapods-deintegrate-1.0.4
Successfully installed fuzzy_match-2.0.4
Successfully installed httpclient-2.8.3
Successfully installed algoliasearch-1.27.1
Building native extensions.  This could take a while...
ERROR:  Error installing cocoapods-1.9.0.gem:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/Cellar/cocoapods/1.9.0/libexec/gems/ffi-1.12.2/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20200229-74843-12oz9d8.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
```

**Comment by robinvw1** [comment]
Is there something I can do to move this forward? :)

**Comment by Bo98** [comment]
I know what the issue is and will fix it properly in brew very soon.

@samford Feel free to use this workaround: https://github.com/Homebrew/homebrew-core/blob/3ba0438784e7ccfa7e2bb3e5cde31516eb99b6ab/Formula/weechat.rb#L40-L42

**Comment by samford** [comment]
That workaround does the trick and now it looks good on CI. Thanks, @Bo98!

**Pull request closed without merging**
