### PR TITLE
sqlite 3.15.1

### PR DESCRIPTION
**Pull request by neutric**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Do you mind adding the `dbhash`, `sqldiff`, and `sqlite-analyzer` updates to this PR too?

**Comment by ilovezfs** [comment]
Separate PRs work too! I see you've opened #6601 (sqldiff), #6602 (dbhash), and #6603 (sqlite-analyzer). Thanks!

**Comment by neutric** [comment]
Saw that too late, sorry. Will do so next time, okay?

**Comment by ilovezfs** [comment]
@neutric either way is great. I didn't realize you were already planning to do those other ones.

**Comment by ilovezfs** [comment]
@neutric Thanks for doing this upgrade!

**Pull request closed without merging**
