### PR TITLE
gyp 1.0 (new formula)

### PR DESCRIPTION
**Pull request by eoger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Published stable release tags are one of the requirements for a homebrew formula.

https://docs.brew.sh/Acceptable-Formulae#stable-versions

Maybe you can ask upstream to just tag each month?

**Comment by eoger** [comment]
Sorry @onpaws I do not have more time to invest in this.

**Comment by onpaws** [comment]
> Sorry @onpaws I do not have more time to invest in this.

No worries. Would you have objections if I try to pick things up?

**Comment by eoger** [comment]
Go ahead!

**Comment by onpaws** [comment]
https://groups.google.com/forum/#!searchin/gyp-developer/tags%7Csort:date/gyp-developer/r-0PC-IGIXw/Wxp2nIU3BgAJ

Found what I believe to be the right mailing list. We'll see :)

**Pull request closed without merging**
