### PR TITLE
libgit2 0.28.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tschoonj** [comment]
`libgit2-glib` has also just been [updated](https://mail.gnome.org/archives/ftp-release-list/2019-February/msg00103.html) by the way

**Comment by lembacon** [comment]
We'll have to update `meson-internal` beforehand.

```
20:45:48 ==> meson --prefix=/usr/local/Cellar/libgit2-glib/0.27.8 -Dpython=false -Dvapi=true ..
20:45:48 The Meson build system
20:45:48 Version: 0.46.1
20:45:48 Source dir: /private/tmp/libgit2-glib-20190213-27945-12jwqil/libgit2-glib-0.27.8
20:45:48 Build dir: /private/tmp/libgit2-glib-20190213-27945-12jwqil/libgit2-glib-0.27.8/build
20:45:48 Build type: native build
20:45:48 
20:45:48 meson.build:1:0: ERROR:  Meson version is 0.46.1 but project requires >= 0.48.0.
20:45:48 
20:45:48 A full log can be found at /private/tmp/libgit2-glib-20190213-27945-12jwqil/libgit2-glib-0.27.8/build/meson-logs/meson-log.txt
```

cc @tschoonj

**Comment by tschoonj** [comment]
ah crap... leave updating `libgit2-glib` to the latest version to me then. Just revbump the current one to get this PR through.

Thanks

**Comment by lembacon** [comment]
`libgit2-glib` 0.27.7 won't work with `libgit2` 0.28.0.

```
13:17:27 Undefined symbols for architecture x86_64:
13:17:27   "_git_buf_free", referenced from:
13:17:27       _ggit_config_find_global in ggit-config.c.o
13:17:27       _ggit_config_find_system in ggit-config.c.o
13:17:27       _ggit_diff_format_email in ggit-diff.c.o
13:17:27       _ggit_message_prettify in ggit-message.c.o
13:17:27       _ggit_patch_to_string in ggit-patch.c.o
13:17:27       _ggit_repository_discover_full in ggit-repository.c.o
13:17:27       _ggit_repository_get_default_notes_ref in ggit-repository.c.o
13:17:27       ...
13:17:27   "_giterr_last", referenced from:
13:17:27       __ggit_error_set in ggit-error.c.o
13:17:27   "_giterr_set_str", referenced from:
13:17:27       _create_repository_wrapper in ggit-clone-options.c.o
13:17:27       _create_remote_wrapper in ggit-clone-options.c.o
13:17:27       _credentials_wrap in ggit-remote-callbacks.c.o
```

**Comment by tschoonj** [comment]
Thanks I will have a look at this

**Comment by tschoonj** [comment]
`libgit2` 0.28.0 is [broken](https://github.com/libgit2/libgit2/issues/4978), which is why you are seeing this errors when building `libgit2-glib`. 

All we can do is wait for 0.28.1...

**Comment by ethomson** [comment]
@tschoonj apologies for this, v0.28.1 should provide the proper compatibility for those deprecated symbols.

**Comment by tschoonj** [comment]
@lembacon would you like to try again with `0.28.1`? Otherwise I can give it a go myself...

**Comment by lembacon** [comment]
@tschoonj Updated.

**Comment by lembacon** [comment]
Now we'll have to wait for `pygit2` to release a new version that is compatible with `libgit2` 0.28.1, otherwise `gitfs`, `gitless` and `salt` will all fail to build:

```
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/blob.c -o build/temp.macosx-10.14-x86_64-3.7/src/blob.o
    In file included from src/blob.c:30:
    In file included from src/blob.h:34:
    src/types.h:36:2: error: You need a compatible libgit2 version (v0.27.x)
    #error You need a compatible libgit2 version (v0.27.x)
     ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    Running setup.py install for pygit2: finished with status 'error'
```

**Pull request closed without merging**
