### PR TITLE
pgroonga 2.4.7

### PR DESCRIPTION
**Pull request by askdkc**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`  pg_ctl: could not start server`

**Comment by askdkc** [comment]
> pg_ctl: could not start server

yep. need to fix this.

**Comment by kou** [comment]
We can't install PostgreSQL extension with the current `postgresql@15` formula.

PostgreSQL extensions need to place their `.control`/`.sql` files to PostgreSQL's `share/postgresql/` directory and their `.so` files to PostgreSQL's `lib/postgresql/` directory.
We can add a custom path such as `$(brew --prefix pgroonga)/lib/postgresql/` for the latter (`.so` files) by `dynamic_library_path` https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DYNAMIC-LIBRARY-PATH but can't add a custom path for the former (`.control`/.`sql` files).

PstgreSQL extension fomulae including PGroonga formula can't change PostgrSQL's directory (`$(brew --prefix postgresql@15)`) because it's denied by `sandbox-exec`.

How about using `postgresql@14` for now?

**Comment by kou** [comment]
FYI: `pg_ctl: could not start server` is happen because `pgroonga.so` can't be loaded.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@askdkc it would be better that you could squash the commits, maybe next time. Thanks!

**Comment by askdkc** [comment]
@chenrui333 

My bad. I should have done better.

**Comment by chenrui333** [comment]
@askdkc @kou might need your input on this new PR, #130758 (failed with `pg_ctl: could not start server` issue again)

**Pull request closed without merging**
