### PR TITLE
folly 2017.04.03.00

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Orvid @wez any idea why this is failing?

**Comment by fxcoudert** [comment]
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c experimental/EnvUtil.cpp  -fno-common -DPIC -o experimental/.libs/EnvUtil.o
experimental/EnvUtil.cpp:48:15: error: use of undeclared identifier 'clearenv'
  PCHECK(0 == clearenv());
              ^
1 error generated.
make[2]: *** [experimental/EnvUtil.lo] Error 1
```

**Comment by fxcoudert** [comment]
Reported upstream: https://github.com/facebook/folly/issues/567

**Comment by Orvid** [comment]
I'm on it :) It was an issue I should have noticed during the review but didn't :(

**Comment by ilovezfs** [comment]
Thanks @Orvid

**Comment by ilovezfs** [comment]
@Orvid @wez note that after applying https://github.com/facebook/folly/pull/568 compilation still fails with a different error:
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c init/Init.cpp  -fno-common -DPIC -o init/.libs/Init.o
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c init/Init.cpp -o init/Init.o >/dev/null 2>&1
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include   -std=gnu++1y -g -O2 -c -o io/Compression.lo io/Compression.cpp
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c io/Compression.cpp  -fno-common -DPIC -o io/.libs/Compression.o
io/Compression.cpp:506:43: error: no matching function for call to 'max'
    const auto guessUncompressedLen = 4 * std::max(blockSize, in.size());
                                          ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2654:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long long' vs. 'unsigned long')
max(const _Tp& __a, const _Tp& __b)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2664:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'unsigned long long'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2646:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2672:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
1 error generated.
make[2]: *** [io/Compression.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by ilovezfs** [comment]
Closing since it looks like we'll just need to skip this release.

**Comment by ilovezfs** [comment]
Still broken. Oh well.

**Pull request closed without merging**
