### PR TITLE
harfbuzz 1.3.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
They seem to have broken the Mavericks build, which is problematic. We can't cut off `harfbuzz` without cutting off the `gtk` trees 🙈.

**Comment by ilovezfs** [comment]
LOL
```
  /* crbug.com/576941 and crbug.com/625902 and the investigation in the latter
   * bug indicate that the cascade list reconfiguration occasionally causes
   * crashes in CoreText on OS X 10.9, thus let's skip this step on older
   * operating system versions. Except for the emoji font, where _not_
   * reconfiguring the cascade list causes CoreText crashes. For details, see
   * crbug.com/549610 */
  if (&CTGetCoreTextVersion != NULL && CTGetCoreTextVersion() < kCTVersionNumber10_10) {
    CFStringRef fontName = CTFontCopyPostScriptName (ct_font);
    bool isEmojiFont = CFStringCompare (fontName, CFSTR("AppleColorEmoji"), 0) == kCFCompareEqualTo;
    CFRelease (fontName);
    if (!isEmojiFont)
      return ct_font;
  }
```
ironic, much?

**Comment by ilovezfs** [comment]
@DomT4 :green_apple: 

*ilovezfs sighs*

**Comment by ilovezfs** [comment]
I suppose it might be worth trying <= kCTVersionNumber10_9 too ...

**Comment by ilovezfs** [comment]
Yeah, that works, too, but the original patch is actually a better idea since the simple replacement will cause build failure for <= 10.8 for the same reason.

**Comment by DomT4** [comment]
That's an impressive little bug they've introduced there. Maybe worth punting upstream to see if they'll adopt your fix.

**Comment by ilovezfs** [comment]
Fixed in 1.3.2.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/5293

**Pull request closed without merging**
