### PR TITLE
envoy 1.24.0

### PR DESCRIPTION
**Pull request by dio**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change? I found https://github.com/Homebrew/homebrew-core/pull/113451 but seems like that needs tweaking.
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This supersedes https://github.com/Homebrew/homebrew-core/pull/113451. This PR makes sure we build from the source code archive of a tagged release (vs. git clone) and set the build info to "Distribution" vs. "Modified" (via providing the SOURCE_VERSION file before building).

### CODE REVIEW

**Comment by dio** [comment]
We do have the v1.23.2 release https://github.com/envoyproxy/envoy/releases/tag/v1.23.2. @carlocab @cho-m do you think we should aim for that first?

**Comment by dio** [comment]
Seems like it requires the `long-build` label.

**Comment by dio** [comment]
Thanks, @SMillerDev! Also, probably we need the `CI-linux-self-hosted` label as the previous PR: https://github.com/Homebrew/homebrew-core/pull/110883

**Comment by dio** [comment]
Sorry I needed to update one of the pre-build script args.

**Comment by chenrui333** [comment]
> We do have the v1.23.2 release https://github.com/envoyproxy/envoy/releases/tag/v1.23.2. @carlocab @cho-m do you think we should aim for that (#114215) first?

yeah, always doing the latest. :)

**Comment by dio** [comment]
Thanks for the confirmation @chenrui333! Really appreciated. 

Hope we can move this forward, with some additional labels.

**Comment by chenrui333** [comment]
🏃

**Comment by dio** [comment]
Thank you, @chenrui333!

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
