### PR TITLE
aptos 2.0.2

### PR DESCRIPTION
**Pull request by gregnazario**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes https://github.com/Homebrew/homebrew-core/pull/136021

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error[E0599]: no method named `disable_lifo_slot` found for mutable reference `&mut tokio::runtime::Builder` in the current scope
    --> crates/aptos-runtimes/src/lib.rs:34:10
     |
  29 | /     builder
  30 | |         .thread_name_fn(move || {
  31 | |             let id = atomic_id.fetch_add(1, Ordering::SeqCst);
  32 | |             format!("{}-{}", thread_name_clone, id)
  33 | |         })
  34 | |         .disable_lifo_slot()
     | |         -^^^^^^^^^^^^^^^^^ private field, not a method
     | |_________|
     | 
```

**Comment by gregnazario** [comment]
Yeah, I see it's still there.  I'm trying to work through it, there's a missing feature flag that I don't know what changed on why it's no longer there

**Comment by gregnazario** [comment]
Looks like it succeeds on ARM and fails on x86, so that makes sense (I do all my work on an ARM mac)

**Comment by gregnazario** [comment]
After testing on an x86 Mac, I've determined that Rustflags usage path either changed in the Rust or cargo compiler in recent updates.  I've changed to rustflags specifically in the formula to fix this.

**Comment by gregnazario** [comment]
@chenrui333 let me know if this works!  Finally, got everything working last night

**Comment by 0xjinn** [comment]
Hi @chenrui333 , wanted to check in again to see if we can get an approval for this PR? :)

**Comment by p-linnane** [comment]
@gregnazario Please squash your commits into one with thee message `aptos 2.0.2`. Thanks.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
