### PR TITLE
dashing: bump version of test resource

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
I don't think the revision bump is needed, since the update affects only the test. Is there a reason why the test resource needs updating?

**Comment by pthariensflame** [comment]
I'll remove the revision bump if it's unneeded, although it would be nice to build Big Sur bottles for this.  Regardless, the test resource doesn't strictly _need_ updating but I figured while I was looking at this formula anyway I might as well in order to ensure that builds continue to support recent versions of Ruby's docs.  If _neither_ change is wanted then I can close this.

**Comment by pthariensflame** [comment]
I'm also thoroughly nonplussed by the error on 10.14.  Why is `curl` complaining about an expired certificate when it didn't for the other two?

**Comment by carlocab** [comment]
A Big Sur bottle would be good, and it seems this run would have produced one. Merging it would break the Mojave bottle, though, so it won't do. (A revision bump isn't necessary for the Big Sur bottle.)

As for the Mojave CI failure, I have no idea. The error message reads:
```
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
```
so maybe the default bundle isn't adequate? One way to get around this might be to force Homebrew `curl` on the Mojave runner, but that's not something you can fix in this PR.

Is there a different `resource` you could use for the test block? If we can find one works with Mojave `curl` then we can get this bottled for Big Sur. (Just drop the revision bump.)

**Comment by mitchblank** [comment]
> As for the Mojave CI failure, I have no idea. The error message reads:

This was already being discussed on the other dashing PR: https://github.com/Homebrew/homebrew-core/pull/65648#issuecomment-751350898

See @SMillerDev's diagnosis here: https://github.com/Homebrew/homebrew-core/pull/67614#issuecomment-751361248

**Comment by pthariensflame** [comment]
Pushed a new version of this PR with a workaround.  (Using GitHub seems safe.)

**Comment by pthariensflame** [comment]
@carlocab @mitchblank This seems okay now.

**Review by carlocab — APPROVED** [review]
Thanks, @pthariensflame!

**Pull request closed without merging**
