### PR TITLE
bash-completion@2 2.9

### PR DESCRIPTION
**Pull request by yumitsu**
Created with `brew bump-formula-pr`.

---

Updated bash-completion v2.8 -> v2.9

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
 .././install-sh -c -d '/usr/local/Cellar/bash-completion@2/2.9/share/bash-completion/completions'
/bin/sh: .././install-sh: /usr/bin/sh: bad interpreter: No such file or directory
make[2]: *** [install-bashcompDATA] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
```

**Comment by yumitsu** [comment]
@fxcoudert Uh-oh, gonna look into it.

**Comment by yumitsu** [comment]
@fxcoudert I looked into the matter, it can be fixed in two ways. 

1. If `coreutils` installed, `configure` will pick GNU versions of tools and `install-sh` will not be invoked at all:
```
λ ./configure --prefix=$HOME/tmp/bash-completion@2
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/local/bin/gsed
checking that generated files are newer than configure... done
configure: creating ./config.status

Making install in test
Making install in t
Making install in unit
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for `install-data-am'.
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for `install-data-am'.
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.

 ======= OMITTED  =======

make[2]: Nothing to be done for `install-exec-am'.
 /usr/local/bin/gmkdir -p '/Users/yumitsu/tmp/bash-completion@2/share/cmake/bash-completion/'
 /usr/local/bin/ginstall -c -m 644 bash-completion-config.cmake bash-completion-config-version.cmake '/Users/yumitsu/tmp/bash-completion@2/share/cmake/bash-completion/'
 /usr/local/bin/gmkdir -p '/Users/yumitsu/tmp/bash-completion@2/share/pkgconfig'
 /usr/local/bin/ginstall -c -m 644 bash-completion.pc '/Users/yumitsu/tmp/bash-completion@2/share/pkgconfig'
 /usr/local/bin/gmkdir -p '/Users/yumitsu/tmp/bash-completion@2/share/bash-completion'
 /usr/local/bin/ginstall -c -m 644 bash_completion '/Users/yumitsu/tmp/bash-completion@2/share/bash-completion'
 /usr/local/bin/gmkdir -p '/Users/yumitsu/tmp/bash-completion@2/etc/profile.d'
 /usr/local/bin/ginstall -c -m 644 bash_completion.sh '/Users/yumitsu/tmp/bash-completion@2/etc/profile.d'
make  install-data-hook
tmpfile=`mktemp ${TMPDIR:-/tmp}/bash_completion.XXXXXX` && \
        /usr/local/bin/gsed -e 's|-/etc/bash_completion\.d|-/Users/yumitsu/tmp/bash-completion@2/etc/bash_completion.d|' \
            /Users/yumitsu/tmp/bash-completion@2/share/bash-completion/bash_completion >$tmpfile && \
        cat $tmpfile >/Users/yumitsu/tmp/bash-completion@2/share/bash-completion/bash_completion && \
        rm $tmpfile
```
2. If no `coreutils` installed, it will use available ones, but we need to `inreplace` shebang in `install-sh` helper.

I guess the second option is more preferable.

**Comment by fxcoudert** [comment]
Preferable option is 3: report the issue so it's fixed upstream. `/usr/bin/sh` is not the correct path (in UNIX standard) to hardcode for a shell.

**Comment by yumitsu** [comment]
@fxcoudert Looks like `install-sh` script was added to release tarball by mistake - it is in `.gitignore`. So, we can just do `autoreconf -if` instead of `autoreconf -i` and be happy.
Anyway, I'm gonna report this to upstream.

**Comment by fxcoudert** [comment]
OK, I'll close it at this point, hopefully this is fixed for the next release!

**Pull request closed without merging**
