### PR TITLE
python@3.9 3.9.8

### PR DESCRIPTION
**Pull request by tuzi3040**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

`setuptools` updated to `58.5.3` and `pip` updated to `21.3.1`.

### CODE REVIEW

**Comment by carlocab** [comment]
`mathlibtools` is a `test-bot` bug. The Linux failures are probably unrelated, and being investigated at #84886.

We should investigate the `jupyterlab` test failure.

**Comment by tuzi3040** [comment]
`jupyterlab` bumped to `3.2.2`, reopened pr for a workflow rerun.

**Comment by carlocab** [comment]
You'll probably need to rebase to make sure you're using the new version of `jupyterlab`.

**Review by carlocab — APPROVED** [review]
Failures look unrelated. Let's move this along.

**Pull request closed without merging**
