### PR TITLE
cheat 2.5.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
19:29:51     running install_data
19:29:51     creating /usr/share/cheat
19:29:51     error: could not create '/usr/share/cheat': Operation not permitted
19:29:51   Running setup.py install for cheat: finished with status 'error'
19:29:51 Cleaning up...
19:29:51   Removing source in /private/tmp/pip-req-build-f2_p4sqr
19:29:51 Removed build tracker '/private/tmp/pip-req-tracker-umh3c87a'
19:29:51 ERROR: Command "/usr/local/Cellar/cheat/2.5.1/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-f2_p4sqr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-ccjf9er9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/cheat/2.5.1/libexec/bin/../include/site/python3.7/cheat" failed with error code 1 in /private/tmp/pip-req-build-f2_p4sqr/
19:29:51 Exception information:
19:29:51 Traceback (most recent call last):
19:29:51   File "/usr/local/Cellar/cheat/2.5.1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
19:29:51     status = self.run(options, args)
19:29:51   File "/usr/local/Cellar/cheat/2.5.1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
19:29:51     use_user_site=options.use_user_site,
19:29:51   File "/usr/local/Cellar/cheat/2.5.1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
19:29:51     **kwargs
19:29:51   File "/usr/local/Cellar/cheat/2.5.1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
19:29:51     spinner=spinner,
19:29:51   File "/usr/local/Cellar/cheat/2.5.1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
19:29:51     % (command_desc, proc.returncode, cwd))
19:29:51 pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/cheat/2.5.1/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-f2_p4sqr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-ccjf9er9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/cheat/2.5.1/libexec/bin/../include/site/python3.7/cheat" failed with error code 1 in /private/tmp/pip-req-build-f2_p4sqr/
19:29:51 
19:29:51 ==> Formula
19:29:51 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cheat.rb
```

**Comment by chenrui333** [comment]
Relies on this PR, https://github.com/cheat/cheat/pull/432

**Comment by chenrui333** [comment]
Pushed some deps refresh.

**Comment by chenrui333** [comment]
Poking back on the `cheat/cheat#432` PR

**Comment by chenrui333** [comment]
looks like the upstream issue got fixed, waiting on the new release for helping this PR move forward.

**Comment by fxcoudert** [comment]
No need to keep the PR open, let's close for now and open a new  one with the next release

**Comment by chenrui333** [comment]
sounds good!!

**Pull request closed without merging**
