### PR TITLE
bear 3.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
-- Looking for gRPC::grpc++ dependency
CMake Error at /usr/local/Cellar/cmake/3.18.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

      Reason given by package: The command
        "/usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config" --version
      failed with output
        /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: /usr/local/opt/pkg-config/bin/pkg-config: No such file or directory
      /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 9: exec: /usr/local/opt/pkg-config/bin/pkg-config: cannot execute: No such file or directory

Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.18.3/share/cmake/Modules/FindPkgConfig.cmake:59 (find_package_handle_standard_args)
  third_party/grpc/CMakeLists.txt:2 (find_package)
```

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
<details>
<summary>build error log</summary>

```
Scanning dependencies of target intercept_unit_test
[ 80%] Building CXX object intercept/CMakeFiles/intercept_unit_test.dir/test/ReporterTest.cc.o
Scanning dependencies of target wrapper
[ 82%] Building CXX object intercept-wrapper/CMakeFiles/wrapper.dir/main.cc.o
[ 84%] Building CXX object intercept/CMakeFiles/intercept_unit_test.dir/test/SessionTest.cc.o
[ 85%] Linking CXX executable intercept
[ 87%] Linking C executable wrapper
Undefined symbols for architecture x86_64:
  "_BIO_get_mem_data", referenced from:
      peer_from_x509(x509_st*, int, tsi_peer*) in libgrpc.a(ssl_transport_security.cc.o)
      tsi_ssl_get_cert_chain_contents(stack_st_X509*, tsi_peer_property*) in libgrpc.a(ssl_transport_security.cc.o)
  "_BIO_get_mem_ptr", referenced from:
      aes_gcm_format_errors(char const*, char**) in libgrpc.a(aes_gcm.cc.o)
  "_BIO_pending", referenced from:
      ssl_handshaker_next(tsi_handshaker*, unsigned char const*, unsigned long, unsigned char const**, unsigned long*, tsi_handshaker_result**, void (*)(tsi_result, void*, unsigned char const*, unsigned long, tsi_handshaker_result*), void*) in libgrpc.a(ssl_transport_security.cc.o)
      ssl_protector_protect(tsi_frame_protector*, unsigned char const*, unsigned long*, unsigned char*, unsigned long*) in libgrpc.a(ssl_transport_security.cc.o)
      ssl_protector_protect_flush(tsi_frame_protector*, unsigned char*, unsigned long*, unsigned long*) in libgrpc.a(ssl_transport_security.cc.o)
  "_BIO_should_retry", referenced from:
      ssl_handshaker_next(tsi_handshaker*, unsigned char const*, unsigned long, unsigned char const**, unsigned long*, tsi_handshaker_result**, void (*)(tsi_result, void*, unsigned char const*, unsigned long, tsi_handshaker_result*), void*) in libgrpc.a(ssl_transport_security.cc.o)
  "_CFRelease", referenced from:
      absl::lts_2020_02_25::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetCString", referenced from:
      absl::lts_2020_02_25::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetLength", referenced from:
      absl::lts_2020_02_25::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetMaximumSizeForEncoding", referenced from:
      absl::lts_2020_02_25::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneCopyDefault", referenced from:
      absl::lts_2020_02_25::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneGetName", referenced from:
      absl::lts_2020_02_25::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_EVP_DigestSignUpdate", referenced from:
      compute_and_encode_signature(grpc_auth_json_key const*, char const*, char const*) in libgrpc.a(json_token.cc.o)
      absl::lts_2020_02_25::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_EVP_DigestSignUpdate", referenced from:
      compute_and_encode_signature(grpc_auth_json_key const*, char const*, char const*) in libgrpc.a(json_token.cc.o)
  "_EVP_MD_CTX_create", referenced from:
      compute_and_encode_signature(grpc_auth_json_key const*, char const*, char const*) in libgrpc.a(json_token.cc.o)
  "_EVP_MD_CTX_destroy", referenced from:
      compute_and_encode_signature(grpc_auth_json_key const*, char const*, char const*) in libgrpc.a(json_token.cc.o)
  "_OPENSSL_free", referenced from:
      peer_from_x509(x509_st*, int, tsi_peer*) in libgrpc.a(ssl_transport_security.cc.o)
  "_OpenSSL_add_all_algorithms", referenced from:
      init_openssl() in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_add_extra_chain_cert", referenced from:
      populate_ssl_context(ssl_ctx_st*, tsi_ssl_pem_key_cert_pair const*, char const*) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_get_ex_new_index", referenced from:
      init_openssl() in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_set_max_proto_version", referenced from:
      tsi_set_min_and_max_tls_versions(ssl_ctx_st*, tsi_tls_version, tsi_tls_version) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_set_min_proto_version", referenced from:
      tsi_set_min_and_max_tls_versions(ssl_ctx_st*, tsi_tls_version, tsi_tls_version) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_set_session_cache_mode", referenced from:
      tsi_create_ssl_client_handshaker_factory_with_options(tsi_ssl_client_handshaker_options const*, tsi_ssl_client_handshaker_factory**) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_set_tlsext_servername_arg", referenced from:
      tsi_create_ssl_server_handshaker_factory_with_options(tsi_ssl_server_handshaker_options const*, tsi_ssl_server_handshaker_factory**) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_set_tlsext_servername_callback", referenced from:
      tsi_create_ssl_server_handshaker_factory_with_options(tsi_ssl_server_handshaker_options const*, tsi_ssl_server_handshaker_factory**) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_set_tlsext_ticket_keys", referenced from:
      tsi_create_ssl_server_handshaker_factory_with_options(tsi_ssl_server_handshaker_options const*, tsi_ssl_server_handshaker_factory**) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_CTX_set_tmp_ecdh", referenced from:
      populate_ssl_context(ssl_ctx_st*, tsi_ssl_pem_key_cert_pair const*, char const*) in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_library_init", referenced from:
      init_openssl() in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_load_error_strings", referenced from:
      init_openssl() in libgrpc.a(ssl_transport_security.cc.o)
  "_SSL_set_tlsext_host_name", referenced from:
      create_tsi_ssl_handshaker(ssl_ctx_st*, int, char const*, tsi_ssl_handshaker_factory*, tsi_handshaker**) in libgrpc.a(ssl_transport_security.cc.o)
  "_sk_new_null", referenced from:
      x509_store_load_certs(x509_store_st*, char const*, unsigned long, stack_st_X509_NAME**) in libgrpc.a(ssl_transport_security.cc.o)
  "_sk_num", referenced from:
      peer_from_x509(x509_st*, int, tsi_peer*) in libgrpc.a(ssl_transport_security.cc.o)
      tsi_ssl_get_cert_chain_contents(stack_st_X509*, tsi_peer_property*) in libgrpc.a(ssl_transport_security.cc.o)
  "_sk_pop_free_ex", referenced from:
      peer_from_x509(x509_st*, int, tsi_peer*) in libgrpc.a(ssl_transport_security.cc.o)
      x509_store_load_certs(x509_store_st*, char const*, unsigned long, stack_st_X509_NAME**) in libgrpc.a(ssl_transport_security.cc.o)
  "_sk_push", referenced from:
      x509_store_load_certs(x509_store_st*, char const*, unsigned long, stack_st_X509_NAME**) in libgrpc.a(ssl_transport_security.cc.o)
  "_sk_value", referenced from:
      peer_from_x509(x509_st*, int, tsi_peer*) in libgrpc.a(ssl_transport_security.cc.o)
      tsi_ssl_get_cert_chain_contents(stack_st_X509*, tsi_peer_property*) in libgrpc.a(ssl_transport_security.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [intercept/intercept_unit_test] Error 1
make[4]: *** [intercept/CMakeFiles/intercept_unit_test.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [subprojects/Stamp/BearSource/BearSource-build] Error 2
make[1]: *** [CMakeFiles/BearSource.dir/all] Error 2
make: *** [all] Error 2
```

</details>

**Comment by alebcay** [comment]
`bear` 3.0.2 is now available.

**Comment by chenrui333** [comment]
I tried on my machine, does not work for favor.

**Pull request closed without merging**
