### PR TITLE
zeek: remove SDK path from zeek-config

### PR DESCRIPTION
**Pull request by philrz**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
The changes in this PR address a problem that was preventing the install of the [Zeek Package for Community ID](https://github.com/corelight/zeek-community-id) as first discussed in issue https://github.com/corelight/zeek-community-id/issues/15. That issue spawned a discussion with the core Zeek dev team in https://github.com/zeek/zeek/issues/1468. The ultimate conclusion was that cmake's finding of the OSX-provided pcap/zlib headers ended up locking in paths in the bottle that might not be present in the system where the bottle ultimately gets installed, which results in the failure to compile the code needed to install a package such as the Community ID one. The fix avoids the problem by pointing at the Homebrew-provided dependencies for pcap/zlib.

@bbannier from the Zeek team correctly pointed out that this could be prone to regression, so the test here attempts to make sure such paths don't get locked in again. There may be better ways to go about performing this check, but it seems to be doing the trick.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @philrz. You probably want to increment the `revision` so that users who have this installed get the updated version with `brew upgrade`.

I'm still unsure about this point, though:

>The ultimate conclusion was that cmake's finding of the OSX-provided pcap/zlib headers ended up locking in paths in the bottle that might not be present in the system where the bottle ultimately gets installed

The header paths you're seeing are to the SDK provided by the Xcode Command Line Tools. If the system where the bottle is installed also has a CLT installation, do you still get the failures that you're seeing?

**Comment by philrz** [comment]
@carlocab: Thanks for reminding me about incrementing the revision. I totally forgot. :blush: 

Regarding the CLT, yes, the original repro of corelight/zeek-community-id#15 was on my own system which has CLT installed. The comments in both that issue and [zeek/zeek#1468](https://github.com/zeek/zeek/issues/1468) show the compilation errors that occur due to the locked-in paths and describe the failure and reason for the workaround in more detail. You can also see a recipe for reproducing the problem on GitHub Actions runners (which have CLT installed) at https://github.com/philrz/zeek-macos-brew-cid-fail/blob/main/.github/workflows/runtest.yaml.

If it helps further make the case, the Zeek from MacPorts at [https://github.com/macports/macports-ports/blob/master/net/zeek/Portfile](https://github.com/macports/macports-ports/blob/master/net/zeek/Portfile) didn't have the problem installing the Community ID package and happens to be built in a way similar to what's being proposed in this PR.

**Comment by carlocab** [comment]
Ok, I'm confused then. The issue can't be this

>locking in paths in the bottle that might not be present in the system where the bottle ultimately gets installed

because you still see failures even when those paths are present in the system. We should try to understand where the error is coming from first in order to identify the correct fix for it.

**Comment by philrz** [comment]
It looks like I misspoke then. Rather than try again and maybe get it wrong once more, I'll see if [**@bbannier**](https://github.com/bbannier) is up for chiming in on this PR. I'm ultimately not a C++ developer.

**Comment by carlocab** [comment]
I still need to read the linked issues more carefully (will try to find the time for this tomorrow), but my impression is that `zkg` is built to use headers provided by a full Xcode (i.e. app bundle) install, rather than just the stripped-down CLT. This is why it gets confused when it tries to interact with a `zeek` built only with the CLT rather than the complete Xcode.

If I'm right, then the correct fix here might actually be one of:
1. Re-configure `zkg` to be compatible with CLT-only installs
2. Add a dependency on Xcode to the `zeek` formula, so it uses the headers and libraries from an Xcode install (I think this should avoid `zkg` getting confused about the headers)

Not needing an Xcode dependency would be, in my view, ideal here. Managing an Xcode installation can get complicated, and takes up significantly more space (~10 GB) than a CLT-only install (~1 GB).

**Comment by carlocab** [comment]
I think we can try this, without needing to add extra dependencies that duplicate system libraries:
```diff
diff --git a/Formula/zeek.rb b/Formula/zeek.rb
index 892a039de85..3517b3476fd 100644
--- a/Formula/zeek.rb
+++ b/Formula/zeek.rb
@@ -27,6 +27,7 @@ class Zeek < Formula
 
   uses_from_macos "flex"
   uses_from_macos "libpcap"
+  uses_from_macos "zlib"
 
   resource "pcap-test" do
     url "https://raw.githubusercontent.com/zeek/zeek/59ed5c75f190d4401d30172b9297b3592dd72acf/testing/btest/Traces/http/get.trace"
@@ -34,6 +35,13 @@ class Zeek < Formula
   end
 
   def install
+    # Remove SDK paths from zeek-config. This breaks usage with other SDKs.
+    # https://github.com/corelight/zeek-community-id/issues/15
+    inreplace "zeek-config.in" do |s|
+      s.gsub! ":@ZEEK_CONFIG_PCAP_INCLUDE_DIR@", ""
+      s.gsub! ":@ZEEK_CONFIG_ZLIB_INCLUDE_DIR@", ""
+    end
+
     mkdir "build" do
       system "cmake", "..", *std_cmake_args,
                       "-DBROKER_DISABLE_TESTS=on",
```

**Comment by philrz** [comment]
@carlocab: Thanks very much for looking so closely at that. @bbannier and I spoke offline and he also thinks your patch is an improvement over what we had in the first pass. He also pointed out to me that the approach you took is along the lines of what @jsiwek seemed to have in mind in [this zeek/zeek#1468 comment](https://github.com/zeek/zeek/issues/1468#issuecomment-809842598), so indeed it does seem like everyone's on the same page.

It's basically just reading your own patch back to you, but FWIW I just pushed a commit to this branch that also has the revision increment and the test still intact.

**Comment by carlocab** [comment]
Great. I suspect you've done the same, but I tested this too and it seems to work. (Or, at least, there are no more errors from the steps you took to produce then originally.)

One last thing: can you squash your commits into a single one? After that this should be good to go.

Thanks!

**Review by carlocab — APPROVED** [review]
Thanks, @philrz.

**Comment by philrz** [comment]
Thanks @carlocab! Just to respond to your last comment, indeed I did test it. Just so the info is here in case others should look at the PR in the future, here's the validation steps after having done `brew install --build-from-source zeek`:

```
$ sudo pip3 install zkg
$ sudo zkg autoconfig
$ sudo zkg install --force https://github.com/corelight/zeek-community-id
$ wget https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz
$ gunzip wrccdc.2018-03-23.010014000000000.pcap.gz 
$ zeek -C -r wrccdc.2018-03-23.010014000000000.pcap --exec "@load packages" local
$ cat conn.log | zeek-cut community_id | head -1
1:Ok4Im3EoUdvUUsMuVAIMNfYoKfg=
```

In the past the `zkg install` step would have failed, but now we know the Zeek Package installed and is working ok because we saw a `community_id` value attached to a `conn` record.

**Pull request closed without merging**
