### PR TITLE
nwchem 7.2.1

### PR DESCRIPTION
**Pull request by edoapra**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by edoapra** [comment]
CI-long-timeout needed.

**Comment by edoapra** [comment]
@chenrui333 I think that CI-long-timeout  is needed.

**Comment by p-linnane** [comment]
Only 2 PR's can use that label at a time, and 2 currently are. We can take care of it after one of those finishes.

**Comment by edoapra** [comment]
> Only 2 PR's can use that label at a time, and 2 currently are. We can take care of it after one of those finishes.

Thanks for the explanation. Not sure why two tasks have been taken more than the 90 minutes limit.   
Could we try to restart the two failed tasks, instead of using the CI-long-timeout label?

**Comment by p-linnane** [comment]
Sure. I can rerun them. If they time out again, we will need to wait for the label.

**Pull request merged**
