### PR TITLE
pybind11 2.6.0

### PR DESCRIPTION
**Pull request by henryiii**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please hold for https://github.com/Homebrew/homebrew-core/pull/62560

**Comment by henryiii** [comment]
Actually, in its current form, this recipe does not need or touch a specific version of Python. It only installs headers and CMake files. We could change it so the Python module is also installed, or we could change it so that Python is not searched on the configure step and drop the Python requirement except for testing.

**Comment by fxcoudert** [comment]
Why does it depend on python, then?

**Comment by henryiii** [comment]
> Why does it depend on python, then?

Historical, the CMake files were not flexible enough to not look for Python even if all you were doing was installing headers and configure files. Now there is a switch.

Keep in mind, if any other formulas use this one to build, there is a bug in CPython 3.9.0 that causes pybind11 < 2.6 extensions to segfault (UB on all platforms, but random segfaulta on macOS). It's worked around in pybind11 2.6, and patched in CPython 3.9 and dev branches. Conda-forge has already applied the patch to their Python 3.9.0 build, maybe homebrew should too?

**Comment by fxcoudert** [comment]
Formulas using this one: `libtorch ocrmypdf scipy`. At least the issue is not triggered in our tests.

We can update to pybind11 2.6.0 fast once those formulas are migrated: I'll rebase this PR and merge it ASAP.

**Comment by henryiii** [comment]
Many libraries bundle pybind11 via submodule or use the PyPI package (even PyTorch does, even if libTorch does not), so it can't be fully controlled here. So I think it still might be a good idea. PyTorch is currently working on upgrading past 2.3, due to a change in 2.4 that broke mixing compilers (which PyTorch could do when JIT compiling).

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
