### PR TITLE
libopusenc 0.1

### PR DESCRIPTION
**Pull request by rillian**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Packaging this since it will soon be a dependency of opus-tools.

### CODE REVIEW

**Comment by rillian** [comment]
I'm not sure what to do about the test failures. I need the include flags with the header locations of the dependent packages to build the test program. Calling `pkg-config` works great for that, but the error seems to indicate the test sandbox doesn't have it installed. I don't know how to declare it as a test-time dependency, or if there's another way to construct the include line?

The test does pass locally. I guess I could make pkg-config an unconditional dependency?

**Comment by rillian** [comment]
@DomT4 Any suggestions here?

**Comment by JCount** [comment]
@rillian There is no way to declare something as a test time dependency, because the test should not require anything that the installed formula itself does not. In the test, the headers and library paths need to be defined without the need for an outside agent to resolve their locations. Homebrew's DSL provides a means for doing this.

**Comment by rillian** [comment]
Thanks @JCount. Can you be more specific about how I can generate the compiler options line? I found variables `#{lib}` and `#{include}` I can use for the project itself, but not how to get the equivalent for dependencies.

**Comment by JCount** [comment]
Something like this:
```
diff --git a/Formula/libopusenc.rb b/Formula/libopusenc.rb
index 0c30e9f033..5cfd2e0d61 100644
--- a/Formula/libopusenc.rb
+++ b/Formula/libopusenc.rb
@@ -43,16 +43,16 @@ class Libopusenc < Formula
         ope_comments_destroy(comments);
 
         int16_t *buffer = calloc(1920, 2*sizeof(*buffer));
-        ope_encoder_write(enc, buffer, 1920*2*sizeof(*buffer));
+        error = ope_encoder_write(enc, buffer, 1920*2*sizeof(*buffer));
 
-        ope_encoder_drain(enc);
+        error |= ope_encoder_drain(enc);
         ope_encoder_destroy(enc);
 
-        return 0;
+        return error;
       }
     EOS
-    system ENV.cc, "test.c", "-o", "test",
-      *`pkg-config --cflags --libs libopusenc`.chomp.split
+    system ENV.cc, "-I#{Formula["opus"].opt_include}/opus", "-I#{include}/opus",
+                   "-L#{lib}", "-lopusenc", "test.c", "-o", "test"
     system "./test"
   end
 end
```
I added the extra error checks because we might as well use the return values since we have them anyway. 😉

**Comment by rillian** [comment]
That's excellent. Thanks so much!

**Comment by rillian** [comment]
Bump.

**Comment by JCount** [comment]
@rillian I am rebuilding this against `opus 1.2` which was just updated in Homebrew.

**Comment by JCount** [comment]
@rillian Thank you for contributing to Homebrew! 🎆

**Pull request closed without merging**
