### PR TITLE
geni 1.0.3 (new formula)

### PR DESCRIPTION
**Pull request by emilpriver**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Hello, I want to add Geni to homebrew. 
It's a database CLI migration tool

Thank you :D

### CODE REVIEW

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by SMillerDev** [comment]
In the future please don't remove the checklist. It's there because the information helps maintainers.

**Comment by SMillerDev** [comment]
Check the output of `brew audit --formula geni --online --new` in CI here, it shows the issue

**Comment by emilpriver** [comment]
yes got ya, I did look for this audit here https://github.com/Homebrew/homebrew-core/actions/runs/8702634639/job/23867417010 but didn't find it. Did you look at the old CI job?

For context: I did publish a PR some days ago when I had 70 stars and now re-publish the same pr when I have 75 stars. 

I think the amount of stars was the only thing that I wasn't OK on. I ran the command locally and didn't get a issue

**Pull request closed without merging**
