### PR TITLE
ghc 8.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
- [ ] agda
- [ ] arx
- [ ] cabal-install
- [ ] cgrep
- [ ] cless
- [ ] cryptol
- [ ] darcs
- [ ] dhall-json
- [ ] elm-format
- [ ] elm
- [ ] ghc
- [ ] git-annex
- [ ] hadolint
- [ ] haskell-stack
- [ ] highlighting-kate
- [ ] hledger
- [ ] hopenpgp-tools
- [ ] idris
- [ ] mighttpd2
- [ ] pandoc-citeproc
- [ ] pandoc-crossref
- [ ] pandoc
- [ ] postgrest
- [ ] purescript
- [ ] qriollo
- [ ] shellcheck
- [ ] texmath

**Comment by ilovezfs** [comment]
@joeyh Have you had a chance to look at the Cabal 2.0 issue and the pipe: resource exhausted issue? http://git-annex.branchable.com/bugs/Cannot_build_with_GHC_8.2.1/#comment-9590daecaf78ba094a56d0f56f3fc7f1

**Comment by joeyh** [comment]
ilovezfs wrote:
> @joeyh Have you had a chance to look at the Cabal 2.0 issue and the pipe:
> resource exhausted issue? http://git-annex.branchable.com/bugs/
> Cannot_build_with_GHC_8.2.1/#comment-9590daecaf78ba094a56d0f56f3fc7f1

Only as far as the Cabal 2.0 issue. I'm traveling for the next while.

-- 
see shy jo

**Comment by ilovezfs** [comment]
@joeyh no problem. Thanks for the quick response :)

**Comment by joeyh** [comment]
ilovezfs wrote:
> @joeyh Have you had a chance to look at the Cabal 2.0 issue and the pipe:
> resource exhausted issue? http://git-annex.branchable.com/bugs/
> Cannot_build_with_GHC_8.2.1/#comment-9590daecaf78ba094a56d0f56f3fc7f1

The resource exhausted issue should be fixed by
5c32196a376cdaf231a9ccde9bb97297f651a132

-- 
see shy jo

**Pull request closed without merging**
