### PR TITLE
libheif 1.15.2

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
I'm stumped on the dependent testing failure here.

https://github.com/Homebrew/homebrew-core/actions/runs/4577145818/jobs/8082883041?pr=127133#step:7:40

CC @Homebrew/core in case anyone has the chance to take a look.

**Comment by ZhongRuoyu** [comment]
I couldn't reproduce this locally. Even if I run the exact `brew test-bot` commands by hand. 😶

**Comment by carlocab** [comment]
It seems that this is a bug in `brew install --only-dependencies`. This is what happens when we try to do that:
```
  Warning: libheif 1.15.2 is already installed, it's just not linked.
  To link this version, run:
    brew link libheif
```
https://github.com/Homebrew/homebrew-core/actions/runs/4577145818/jobs/8095530104?pr=127133#step:7:28

**Comment by p-linnane** [comment]
@carlocab Looks like you fixed it. Big Sur Intel timed out at the end of dep testing. Do we want to rerun with `ci-long-timeout` or are we good to merge?

**Review by carlocab — APPROVED** [review]

**Pull request merged**
