### PR TITLE
shellcheck 0.6.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Mikewl** [comment]
```
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 4e6c46751f031095f33f46ad4a4cf51c79fd2398031260132d6b57390a59d293
Actual: 78f90aa8e618dc468bc1c36b6929216dc7a0c2679cd157e50919f7d8cc1899bc
```
I am getting the above when trying to upgrade. Downloaded the file and got the same hash as what brew downloaded.

**Comment by fxcoudert** [comment]
@Mikewl please open an issue with the upstream project, ask them why the downloads have changed. It could be malicious

**Comment by leonklingele** [comment]
Reported @ upstream: https://github.com/koalaman/shellcheck/issues/1407.

**Comment by leonklingele** [comment]
Fix is in #34780.

**Pull request closed without merging**
