### PR TITLE
cbmc 5.14.2

### PR DESCRIPTION
**Pull request by db-ci-cprover**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Rylan12** [comment]
Thanks for the PR, @db-ci-cprover!

These changes are based off of an old version of `cbmc.rb` so you'll need to rebase onto the latest version and force push to resolve the conflicts.

**Comment by dtrodrigues** [comment]
I'm pretty sure this was generated by a bot as part of their release process: https://github.com/diffblue/cbmc/blob/1cc1bf8be157412a12b509d6e42213e73133b29f/.github/workflows/release-packages.yaml#L56

**Comment by hannes-steffenhagen-diffblue** [comment]
Aye, part of our automatic release process. Checking what went wrong here

**Comment by dtrodrigues** [comment]
If the line I linked to before is the code being run, you can try running `brew update` first to update to update the local formula to the most recent version prior to `brew bump-formula-pr`.

**Comment by hannes-steffenhagen-diffblue** [comment]
@dtrodrigues the script is run against a newly installed version of homebrew, I think what happened here was we created two releases very close to each other and the version with the slightly older release being merged hadn't quite passed brew internal CI or something yet

**Comment by hannes-steffenhagen-diffblue** [comment]
@here can we close this please? This isn't really up to date anymore and keeping this open will prevent the next release from getting a PR

**Pull request closed without merging**
