### PR TITLE
remake 4.3-1.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Undefined symbols for architecture x86_64:
  "_history_list", referenced from:
      _dbg_cmd_show_command in cmd.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [make] Error 1
make: *** [install-recursive] Error 1
```

**Comment by SeekingMeaning** [comment]
Can be fixed by adding `readline` as a dependency

**Comment by chenrui333** [comment]
> Can be fixed by adding `readline` as a dependency

Going to give a shot now, thanks for the direction.

**Comment by chenrui333** [comment]
Going to make a new PR (so that more advice and attentions can be brought along)

**Pull request closed without merging**
