### PR TITLE
llvm: add missing flag for macOS Catalina

### LINKED ISSUE #45061: Homebrew Clang does not have correct search path for system include directory on MacOS Catalina
Homebrew Clang does not search the correct include directories in MacOS Catalina.

# What you were trying to do (and why)
If I try to compile the following C file after installing LLVM+Clang from homebrew
```c
#include <stdio.h>

int main() {
    printf("hi");
}
```

# What happened
I get the error
```
» which clang                                                                                                                                                                                             1 ↵
/usr/local/opt/llvm/bin/clang
» clang test.c
In file included from test.c:1:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
#include <stdio.h>
              ^~~~~~~~~
1 error generated.
```

# What you expected to happen
The program to compile correctly.

However, if I alias clang to the system clang, everything works!
```
» alias clang=/usr/bin/clang                                                                                                                                                                              1 ↵
» clang test.c
» ./a.out
hi%
```

By default the Homebrew clang has the following search paths
```
» echo | clang -E -Wp,-v -
clang -cc1 version 9.0.0 based upon LLVM 9.0.0 default target x86_64-apple-darwin19.0.0
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 352 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

The system clang looks in different folders
```
» alias clang=/usr/bin/clang
» echo | clang -E -Wp,-v -
clang -cc1 version 11.0.0 (clang-1100.0.33.8) default target x86_64-apple-darwin19.0.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 362 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

I think the problem is that until recently `/usr/include` would have the header files that the compiler requires, however, that directory does not exist anymore (since Catalina update).

I can currently work around this by explicitly setting `CPATH`. But I think this is a bug, not sure if it is a homebrew problem or upstream in LLVM.

# Step-by-step reproduction instructions (by running brew commands)
```
brew install llvm
export PATH="/usr/local/opt/llvm/bin:$PATH"
clang test.c
```

My homebrew is updated to the latest version and doctor does not report any problems.

```
» brew -v                                                                                                                                                                                                 1 ↵
Homebrew 2.1.13
Homebrew/homebrew-core (git revision 4d523; last commit 2019-10-09)
Homebrew/homebrew-cask (git revision c4f9d3; last commit 2019-10-09)

» brew doctor
Your system is ready to brew.

» brew config
HOMEBREW_VERSION: 2.1.13
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: aa043c1d678afd26f50156a83417c296cb9d5a4b
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4d5233f01f792cb83661ccc1a6abfb139c168951
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: nvim
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.1, 1.8.0_131, 1.8.0_40
macOS: 10.15-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: 11.1
CLT headers: 11.0.0.0.1.1567737322
XQuartz: 2.7.11 => /opt/X11
```

### PR DESCRIPTION
**Pull request by smorimoto**
Fixes #45061

### CODE REVIEW

**Comment by imbsky** [comment]
@fxcoudert What do you think about this? I'm an LLVM beginner and would like to hear your opinion. 

https://github.com/llvm/llvm-project/blob/cdbeaf548f1ff1ac49dfd26de25a67c8ac081996/clang/CMakeLists.txt#L229-L230

CC: @jamiesnape @tschoonj

**Comment by imbsky** [comment]
`-DDEFAULT_SYSROOT` works for me.

Screen Shot 2019-10-14 at 12 48 48

**Comment by imbsky** [comment]
Apple provided a `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` for Mojave users in the past, but it's a first aid. I'm wondering which macOS version should apply this. I would like to hear opinions of the core members.

**Comment by fxcoudert** [comment]
With the compiler from this pull request, can you take a simple C file (one line `#include <stdio.h>` will do), run `clang -v a.c`, and paste the output here?

With an unpatched llvm, I get:

```
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```

**Comment by imbsky** [comment]
@fxcoudert Sure.

```
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

**Comment by dominiklohmann** [comment]
Have you considered using the output of `xcrun --sdk macosx --show-sdk-path` instead of hardcoding the path?

```
$ xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
```

**Comment by imbsky** [comment]
> The Command Line Tools package installs the macOS system headers inside the macOS SDK. Software that compiles with the installed tools will search for headers within the macOS SDK provided by either Xcode at:

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk`

> or the Command Line Tools at:

`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`

> depending on which is selected using xcode-select.

> The command line tools will search the SDK for system headers by default. However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. As a workaround, an extra package is provided which will install the headers to the base system. In a future release, this package will no longer be provided. You can find this package at:

`/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

> To make sure that you're using the intended version of the command line tools, run `xcode-select -s <path to Xcode> or xcode select -s /Library/Developer/CommandLineTools` after installing.

https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624

**Comment by fxcoudert** [comment]
```
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
```

This is a problem. Ideally, we want the compiler to look for `/usr/local/include` and `/Library/Frameworks` (and not inside sysroot).

**Comment by imbsky** [comment]
@fxcoudert If I understand correctly, old `/usr/include` and `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` are the same.

**Comment by imbsky** [comment]
Screen Shot 2019-10-14 at 21 16 56

**Comment by imbsky** [comment]
I still don't fully understand Apple's intentions... So I'm not surprised even if I'm wrong.

**Comment by imbsky** [comment]
@dominiklohmann This directory does not exist on older than Mojave, So we will not merge this PR with current code. (This is a placeholder-like code for many Catalina developers to checkout and test it.)

**Comment by dominiklohmann** [comment]
@imbsdky the point is that `xcrun --sdk macosx --show-sdk-path` returns the SDKROOT for the currently used toolchain instead of hardcoding the toolchain to the command line tools. You can also use `DEVELOPER_DIR=/Library/Developer/CommandLineTools xcrun --sdk macosx --show-sdk-path` if you always want to use the basic toolchain. 

This just seems more future-proof to me, because who knows what paths Apple will deprecated next. 🤷‍♂

**Comment by fxcoudert** [comment]
@dominiklohmann if you know of a way to make `clang` get the sysroot at runtime rather than hard code it, we welcome a PR. I have not found a way to do it.

**Comment by imbsky** [comment]
@fxcoudert I found this.

https://github.com/llvm/llvm-project/blob/master/clang/CMakeLists.txt#L225-L226

**Comment by imbsky** [comment]
@dominiklohmann Same opinion with @fxcoudert.

**Comment by imbsky** [comment]
@fxcoudert I think this config will probably give you the result you want.

```
-DDEFAULT_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
-DC_INCLUDE_DIRS= /usr/local/include:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
```

**Comment by imbsky** [comment]
It will take about 30~40 minutes, but I can try to build LLVM again with this configuration.

**Comment by dominiklohmann** [comment]
For me, no configuration is needed aside from setting the environment variable `SDKROOT` so the paths are set at runtime.

```
$ export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
$ clang -v test.c
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
 "/usr/local/Cellar/llvm/9.0.0/bin/clang-9" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-sdk-version=10.15 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 512.4 -v -resource-dir /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/local/include -internal-isystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -fdebug-compilation-dir /Users/dominiklohmann/Desktop -ferror-limit 19 -fmessage-length 97 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-8146ce.o -x c test.c
clang -cc1 version 9.0.0 based upon LLVM 9.0.0 default target x86_64-apple-darwin19.0.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/usr/bin/ld" -demangle -lto_library /usr/local/Cellar/llvm/9.0.0/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.15.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -o a.out /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-8146ce.o -lSystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
```

```
$ export SDKROOT="$(DEVELOPER_DIR=/Library/Developer/CommandLineTools xcrun --sdk macosx --show-sdk-path)"
$ clang -v test.c
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
 "/usr/local/Cellar/llvm/9.0.0/bin/clang-9" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-sdk-version=10.15 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 512.4 -v -resource-dir /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -fdebug-compilation-dir /Users/dominiklohmann/Desktop -ferror-limit 19 -fmessage-length 97 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-fd3139.o -x c test.c
clang -cc1 version 9.0.0 based upon LLVM 9.0.0 default target x86_64-apple-darwin19.0.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/usr/bin/ld" -demangle -lto_library /usr/local/Cellar/llvm/9.0.0/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.15.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o a.out /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-fd3139.o -lSystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
```

**Comment by imbsky** [comment]
Hmm...

```
/tmp/llvm-20191014-18453-28x8sy/llvm-9.0.0.src/projects/compiler-rt/lib/builtins/os_version_check.c:16:10: fatal error: 'TargetConditionals.h' file not found
```

**Comment by imbsky** [comment]
@dominikschmid Oh it works for me too.

**Comment by jamiesnape** [comment]
I guess we could set `SDKROOT` in a wrapper script around `clang`, etc., but a user would not expect to have to set `SDKROOT` to get a working compiler.

**Comment by imbsky** [comment]
Yes, I agree. But it might be enough to add information to caveats. (I would like to hear opinions of the core members and users.) Well, I think it would be better for beginners to set the default path on the homebrew-core side.

**Comment by imbsky** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb#L178-L182

**Comment by imbsky** [comment]
Well, there is still one concern. Is `SDKROOT` for the LLVM? and if it becomes a de facto standard citizen with the new macOS, is it right to show it as an LLVM caveats?

**Comment by jamiesnape** [comment]
It will certainly affect other clang/llvm tools if it is set, which may be an unintended consequence, I suppose.

**Comment by dominiklohmann** [comment]
Not a core member, but I think upstream should be patched to check for the actual `SDKROOT` by default. The current situation should be considered a bug in llvm.

**Comment by jamiesnape** [comment]
I would disagree it is a bug, since it was Apple that unilaterally removed the canonical path for C includes that other Unix systems use, but it would certainly be a helpful feature request.

**Comment by imbsky** [comment]
Apple seems to have changed to the current directory structure to allow multiple development versions to coexist. Most of the compiler was designed to be able to do that. and whether it was a bug or not, I don't know whether macOS-specific changes should be made on the LLVM side. Because they already provide DEFAULT_SYSROOT and something like that.

**Comment by imbsky** [comment]
Apple (and Google, etc...) have also been working on clang, but they didn't add any change for Catalina yet. I guess that means they won't do it.

**Comment by imbsky** [comment]
The files of `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` and `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include` are completely the same, I create a report and publish it to the following URL via Netlify.

https://adoring-shannon-4d70da.netlify.com

**Comment by imbsky** [comment]
@fxcoudert I think directories directly under `Xcode.app` are mostly for Xcode or Apple Clang. So I wonder if LLVM Clang, which is installed via brew, needs to search for them by default.

**Comment by imbsky** [comment]
I think it's enough to set `sysroot` with `DEFAULT_SYSROOT` by default. (In the case of Mojave or later.)

**Comment by jamiesnape** [comment]
Yes, I think setting `DEFAULT_SYSROOT` is strictly an improvement.

**Comment by imbsky** [comment]
> It will certainly affect other clang/llvm tools if it is set, which may be an unintended consequence, I suppose.

I'm also concerned this.

**Comment by jamiesnape** [comment]
Is there really an objection with setting `DEFAULT_SYSROOT` and referencing the command line tools? That seems like it fits perfectly within the Homebrew ecosystem.

If people need something special (i.e., runtime resolution out of the box), they can either send another PR (here or to LLVM) or build LLVM themselves.

I would really like this to move forward (I want to fix a few other LLVM tools the same way, if everyone is happy with it as a solution).

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
🤷‍♂️

```
Error: csound: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <true> expected but was
<false>.
```

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by jacksoom** [comment]
> For me, no configuration is needed aside from setting the environment variable `SDKROOT` so the paths are set at runtime.
> 
> ```
> $ export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
> $ clang -v test.c
> clang version 9.0.0 (tags/RELEASE_900/final)
> Target: x86_64-apple-darwin19.0.0
> Thread model: posix
> InstalledDir: /usr/local/opt/llvm/bin
>  "/usr/local/Cellar/llvm/9.0.0/bin/clang-9" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-sdk-version=10.15 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 512.4 -v -resource-dir /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/local/include -internal-isystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -fdebug-compilation-dir /Users/dominiklohmann/Desktop -ferror-limit 19 -fmessage-length 97 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-8146ce.o -x c test.c
> clang -cc1 version 9.0.0 based upon LLVM 9.0.0 default target x86_64-apple-darwin19.0.0
> ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/local/include"
> ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/Library/Frameworks"
> #include "..." search starts here:
> #include <...> search starts here:
>  /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include
>  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
>  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
> End of search list.
>  "/usr/bin/ld" -demangle -lto_library /usr/local/Cellar/llvm/9.0.0/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.15.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -o a.out /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-8146ce.o -lSystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
> ```
> 
> ```
> $ export SDKROOT="$(DEVELOPER_DIR=/Library/Developer/CommandLineTools xcrun --sdk macosx --show-sdk-path)"
> $ clang -v test.c
> clang version 9.0.0 (tags/RELEASE_900/final)
> Target: x86_64-apple-darwin19.0.0
> Thread model: posix
> InstalledDir: /usr/local/opt/llvm/bin
>  "/usr/local/Cellar/llvm/9.0.0/bin/clang-9" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-sdk-version=10.15 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 512.4 -v -resource-dir /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -fdebug-compilation-dir /Users/dominiklohmann/Desktop -ferror-limit 19 -fmessage-length 97 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-fd3139.o -x c test.c
> clang -cc1 version 9.0.0 based upon LLVM 9.0.0 default target x86_64-apple-darwin19.0.0
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
> #include "..." search starts here:
> #include <...> search starts here:
>  /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
> End of search list.
>  "/usr/bin/ld" -demangle -lto_library /usr/local/Cellar/llvm/9.0.0/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.15.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o a.out /var/folders/93/jmj7tkp53c53vblwy2m63h9m0000gn/T/test-fd3139.o -lSystem /usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
> ```

it works, thks

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
The test succeeded on my MacBook Pro, but failed on Jenkins.

**Comment by imbsky** [comment]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50081/version=catalina/testReport/junit/brew-test-bot/catalina/test_llvm

**Comment by imbsky** [comment]
Hmm...

**Comment by jamiesnape** [comment]
`stdarg.h` is in clang's internal include directory `/usr/local/opt/llvm/lib/clang/9.0.0/include`. Not sure if `-nostdinc` suppresses that.

**Comment by jamiesnape** [comment]
(several of the tests need rewriting anyway, they don't necessarily make sense with the current state of macOS and this formula)

**Comment by imbsky** [comment]
@jamiesnape I'm sorry! I couldn't reply because I was sick for the past few days... I also checked #45693, Could I port that changes to this?

**Comment by jamiesnape** [comment]
Sure, the changes there should work perfectly for this formula.

**Comment by imbsky** [comment]
Thank you, I just ported the changes from #45693!

**Comment by imbsky** [comment]
We still have these versions in homebrew-core, except for `llvm.rb` and `llvm@4.rb`. and I'm ready to create a PR to update these all at once.

```
Formula/llvm@4.rb
Formula/llvm@7.rb
Formula/llvm@8.rb
```

**Comment by imbsky** [comment]
@fxcoudert @jamiesnape The Rust team may combine several changes into a single PR in a way called Rollup to reduce the time it takes to CI build. These CI builds take a lot of time (about 2 hours per single change), so it would be great if possible. It will be too complicated if we close already opened PRs. So I would only rollup 4, 7 and 8. What do you think about this?

**Comment by imbsky** [comment]
I'm not familiar with the homebrew team's conventions and the bottle build process, so I don't know if it's technically possible.

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
Why build failed without test.

**Comment by jamiesnape** [comment]
> The Rust team may combine several changes into a single PR in a way called Rollup to reduce the time it takes to CI build. These CI builds take a lot of time (about 2 hours per single change), so it would be great if possible. It will be too complicated if we close already opened PRs. So I would only rollup 4, 7 and 8. What do you think about this?

I will defer to @fxcoudert. I have no problem with closing my PR; I mostly just opened it to serve as a concrete example.

**Comment by imbsky** [comment]
Test succeeded.

**Comment by imbsky** [comment]
Let's stop the trying to complex workflow and merge his PR and this one. It helps many people.

**Comment by imbsky** [comment]
friendly reminder @fxcoudert @chenrui333 @SMillerDev

**Comment by chenrui333** [comment]
I will defer this PR to @fxcoudert @SMillerDev for the merge.

@imbsky Thanks a lot for your endless efforts on this!!

**Comment by imbsky** [comment]
I get it.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
Test passed yey!

**Review by chenrui333 — APPROVED** [review]
Thanks a lot!

**Comment by imbsky** [comment]
I will create PR for other llvm versions soon.

**Comment by imbsky** [comment]
I forgot, should I have added a revision to a change that is not a version upgrade?

**Comment by zbeekman** [comment]
@imbsky: I think did warrant a revision bump. Otherwise users will use the old version. At any rate, if we give it a revision bump we should hear back pretty quickly whether or not this causes problems for people.

Would you mind opening a new PR with the revision bump? The other versions probably need a revision bump too.

Without a revision bump, users won't see the fixed/improved behavior (until the next version of LLVM is released).

**Comment by imbsky** [comment]
@zbeekman Yes... I will create revision bump PR tonight.

**Comment by imbsky** [comment]
@zbeekman I just sent the PR because I have much free time.

**Pull request closed without merging**
