### PR TITLE
mydumper 0.9.1: Test that myloader binary is installed

### PR DESCRIPTION
**Pull request by CharlesJUDITH**
The mydumper package is also installing the myloader binary.

This will test that the myloader binary is installed.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can't the tool test some real world usage instead of just a help message?

**Comment by CharlesJUDITH** [comment]
We can print the version but the --help is the same thing.

**Comment by fxcoudert** [comment]
We need a test that exercises the some of the functionality of the app. Version checks or usage checks (`foo --version` or `foo --help`) are not sufficient, as explained in the [formula cookbook](https://docs.brew.sh/Formula-Cookbook).

In most cases, a good test would involve running a simple test case: run `#{bin}/foo input.txt`.
- Then you can check that the output is as expected (with `assert_equal` or `assert_match` on the output of `shell_output`)
- You can also check that an output file was created, if that is expected: `assert_predicate testpath/"output.txt", :exist?`

Some advice for specific cases:
- If the formula is a library, compile and run some simple code that links against it. It could be taken from upstream's documentation / source examples.
- If the formula is for a GUI program, try to find some function that runs as command-line only, like a format conversion, reading or displaying a config file, etc.
- If the software cannot function without credentials, a test could be to try to connect with invalid credentials (or without credentials) and confirm that it fails as expected.
- Same if the software requires a virtual machine, docker instance, etc. to be running.

**Comment by CharlesJUDITH** [comment]
Thanks for your feedback. The current package is having only `--help`.

**Comment by fxcoudert** [comment]
Given no response, closing for now.

**Pull request closed without merging**
