### PR TITLE
libmicrohttpd 0.9.56

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

Build failure reported upstream http://lists.gnu.org/archive/html/libmicrohttpd/2017-11/msg00006.html

### CODE REVIEW

**Comment by Karlson2k** [comment]
Will check build fail.
In addition: libgcrypt is not required anymore.
Also I'd recommend to use '--disable-examples' to speedup builds.

**Comment by ilovezfs** [comment]
Thanks @Karlson2k!

**Comment by Karlson2k** [comment]
@ilovezfs Not related: your build failed to find GnuTLS.
You can use `--enable-https` / `--disable-https` or `--enable-https=yes` / `--enable-https=no` depending on TLS option to ensure that build will contain or will exclude HTTPS support.

**Comment by ilovezfs** [comment]
@Karlson2k right it won't find gnutls unless the user does `brew install --with-ssl libmicrohttpd`

**Comment by Karlson2k** [comment]
My suggestion is about additional configure flags to ensure that you will build required version: otherwise it possible to accidentally build MHD with TLS support when it is not requested or vice versa.

Do you use optimisation for size? Like `-Os` flag? Code automatically select version optimised for small size (which is less tested), selection is based on compiler flags.

**Comment by ilovezfs** [comment]
Yes `-Os`

**Comment by Karlson2k** [comment]
Fixed in git.
We may do a bugfix release soon.

**Pull request closed without merging**
