### PR TITLE
deno 1.28.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
okay, we might have to rerun this PR, as the reopen thing triggered a new run. 🤦

**Comment by lino-levan** [comment]
What does "rerun this PR" mean in this context.

**Comment by chenrui333** [comment]
> What does "rerun this PR" mean in this context.

the merge got blocked as the action thought it is unfinished. (and [that run](https://github.com/Homebrew/homebrew-core/actions/runs/3457284350) is indeed in the queued phase)

**Comment by branchvincent** [comment]
I cancelled the queued job (for some reason it never kicked off, hence why I re-opened the PR). Let's try merging one more time

**Comment by chenrui333** [comment]
> I cancelled the queued job (for some reason it never kicked off, hence why I re-opened the PR). Let's try merging one more time

Interesting, I wonder if we should file a github ticket if we are interested to go down the rabbit hole 😄 

Anyway, another run should resolve our issue.

**Review by chenrui333 — APPROVED** [review]

**Comment by lino-levan** [comment]
LGTM

**Pull request closed without merging**
