### PR TITLE
bartycrouch 4.12.0

### PR DESCRIPTION
**Pull request by Jeehut**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Jeehut** [comment]
Is there anything I can do to get the tests passing? To me, it looks like it's an issue with the server configuration ... maybe Xcode 14 with Swift 5.7 is not the default tooling on it? It needs to be, I think, for the Swift-Syntax-Parser to link properly.

**Comment by Jeehut** [comment]
@SMillerDev Which criteria does the latest stable release Xcode 14.0.1 not meet? I don't understand...

**Comment by SMillerDev** [comment]
You're suggesting that xcode 14 isn't on the server. But since you declare it as a dependency it would fail the install if it wasn't. The problem is in the test though.

**Comment by Jeehut** [comment]
@SMillerDev I was suggesting that Xcode 14.0.1 is not the default Xcode toolset on the server, not that it was not installed. For local Macs, that's the most common reason from my experience for the failure `Library not loaded: '@rpath/lib_InternalSwiftSyntaxParser.dylib'` which is happening here. Users who have an `Xcode.app` which is set as the default toolset and is of version 14 shouldn't see this error. I'm not sure how things are on Brew CI servers though.

**Comment by SMillerDev** [comment]
AFAIK there is only one XCode on the CI servers that is installed through the appstore. I don't think this is the issue you are encountering here.

**Comment by Jeehut** [comment]
All I changed here in this version is to upgrade the SwiftSyntax parser dependency to the one shipped with Xcode 14. I've done these changes in the past as well and we had the same issue on the CI, but things were figured out somehow. See for example [release `4.10.0`](https://github.com/Homebrew/homebrew-core/pull/97188/files) where this same issue arised on the CI. Maybe that helps.

**Comment by SMillerDev** [comment]
Wait, this is bundling parts of XCode? I don't think that's allowed under the XCode license.

**Comment by Jeehut** [comment]
@SMillerDev No, BartyCrouch is not bundling parts of Xcode. It's simply expecting Xcode to be installed and **using** tools bundles with Xcode, such as SwiftySyntaxParser or `ibtool` and `genstrings`. But it's not bundling them.

**Comment by Jeehut** [comment]
@Bo98 Thank you for the information, that really clarifies some things. A bummer that Swift-Syntax is making these kind of changes without notice, nothing in the README about it.

But I just found that a new release was made which seems to aim to solve this issue:
https://github.com/apple/swift-syntax/releases/tag/0.50700.1

I'm now making a new release of BartyCrouch with the updated dependency version, hope it'll work.

**Comment by Jeehut** [comment]
Closing this in favor of https://github.com/Homebrew/homebrew-core/pull/112470.

**Comment by chenrui333** [comment]
##112557

**Pull request closed without merging**
