### PR TITLE
pypy3 7.3.2

### PR DESCRIPTION
**Pull request by lovasoa**
created with `brew bump-formula-pr`

### CODE REVIEW

**Comment by lovasoa** [comment]
The failing CI does not seem to be related to the PR : 

```
'/home/runner/work/homebrew-core/homebrew-core' -> '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'
/home/runner/work/_actions/Homebrew/actions/master/setup-homebrew/main.sh: line 17: fetch: command not found
/home/runner/work/_actions/Homebrew/actions/master/setup-homebrew/main.sh: line 21: MAX_GIT_RETRIES: unbound variable
```

**Comment by SMillerDev** [comment]
Current CI failure is related to the build

**Comment by fxcoudert** [comment]
```
  Utils::Inreplace::Error: inreplace failed
lib_pypy/_tkinter/tklib_build.py:
  expected replacement of "/System/Library/Frameworks/Tk.framework/Versions/Current/Headers/" with "/usr/local/Cellar/pypy3/7.3.2/opt/tcl-tk/include"
```

**Review by fxcoudert — APPROVED** [review]

**Comment by anhdle14** [comment]
I got some issues when trying to install pypy3-7.3.2. Is this related

```bash
Last 15 lines from $HOME/Library/Logs/Homebrew/pypy3/01.pypy:
  File "/private/tmp/pypy3-20201203-25095-wjhb62/pypy3.6-v7.3.2-src/rpython/translator/goal/translate.py", line 327, in main
    debug(True)
  File "/private/tmp/pypy3-20201203-25095-wjhb62/pypy3.6-v7.3.2-src/rpython/translator/goal/translate.py", line 280, in debug
    pdb_plus_show.start(tb)
  File "/private/tmp/pypy3-20201203-25095-wjhb62/pypy3.6-v7.3.2-src/rpython/translator/tool/pdbplus.py", line 442, in start
    fn(*args)
  File "/private/tmp/pypy3-20201203-25095-wjhb62/pypy3.6-v7.3.2-src/rpython/translator/tool/pdbplus.py", line 25, in post_mortem
    self.interaction(t.tb_frame, t)
  File "$HOME/homebrew/opt/pypy/libexec/lib-python/2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "$HOME/homebrew/opt/pypy/libexec/lib-python/2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "/private/tmp/pypy3-20201203-25095-wjhb62/pypy3.6-v7.3.2-src/rpython/translator/tool/pdbplus.py", line 29, in preloop
    raise NoTTY("Cannot start the debugger when stdout is captured.")
NoTTY: Cannot start the debugger when stdout is captured.
```

**Pull request closed without merging**
