### PR TITLE
cargo-zigbuild 0.17.0

### PR DESCRIPTION
**Pull request by messense**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* Use `gnueabihf` for `powerpc-unknown-linux-gnu target`
* Add basic support for WASM by @messense in https://github.com/rust-cross/cargo-zigbuild/pull/155

**Full Changelog**: https://github.com/rust-cross/cargo-zigbuild/compare/v0.16.12...v0.17.0</pre>
</details>

### CODE REVIEW

**Comment by messense** [comment]
I'm unable to reproduce the error locally:

```bash
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source cargo-zigbuild
==> Fetching cargo-zigbuild
==> Downloading https://github.com/rust-cross/cargo-zigbuild/archive/refs/tags/v0.17.0.tar.gz
Already downloaded: /Users/messense/Library/Caches/Homebrew/downloads/b228268d231d1f5be5fa6dbcdfe44f65b6c99a58527e9a89d61a7113826b8e3c--cargo-zigbuild-0.17.0.tar.gz
==> cargo install
🍺  /opt/homebrew/Cellar/cargo-zigbuild/0.17.0: 7 files, 2.7MB, built in 19 seconds
==> Running `brew cleanup cargo-zigbuild`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/messense/Library/Caches/Homebrew/cargo-zigbuild--0.16.12.tar.gz... (49.1KB)

$ brew test -vv cargo-zigbuild
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
==> Testing cargo-zigbuild
==> /opt/homebrew/opt/rustup-init/bin/rustup-init -y --no-modify-path
error: $HOME differs from euid-obtained home directory: you may be using sudo
error: $HOME directory: /private/tmp/cargo-zigbuild-test-20230729-88891-13t7ihg
error: euid-obtained home directory: /Users/messense
info: profile set to 'default'
info: default host triple is aarch64-apple-darwin
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2023-07-13, rust version 1.71.0 (8ede3aae2 2023-07-12)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
info: default toolchain set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin installed - rustc 1.71.0 (8ede3aae2 2023-07-12)


Rust is installed now. Great!

To get started you need Cargo's bin directory
(/Users/messense/Library/Caches/Homebrew/cargo_cache/bin) in your PATH
environment variable. This has not been done automatically.

To configure your current shell, run:
source "/Users/messense/Library/Caches/Homebrew/cargo_cache/env"
==> rustup target add aarch64-unknown-linux-gnu
info: downloading component 'rust-std' for 'aarch64-unknown-linux-gnu'
info: installing component 'rust-std' for 'aarch64-unknown-linux-gnu'
==> cargo new hello_world --bin
     Created binary (application) `hello_world` package
==> cargo zigbuild --target aarch64-unknown-linux-gnu.2.17
   Compiling hello_world v0.1.0 (/private/tmp/cargo-zigbuild-test-20230729-88891-13t7ihg/hello_world)
    Finished dev [unoptimized + debuginfo] target(s) in 2.88s
```

**Comment by chenrui333** [comment]
it might be the path issue, let me check it out in my local.

**Comment by chenrui333** [comment]
only happened for 11-arm

**Comment by chenrui333** [comment]
```
  ==> cargo zigbuild --target aarch64-unknown-linux-gnu.2.17
  Error: Failed to find zig
```

only happened for 11-arm, maybe we can retry after #138490

**Comment by chenrui333** [comment]
okay, looks like same 11-arm build failure in #139864

**Comment by chenrui333** [comment]
let's maybe drop 11-arm bottle (hope someone can pick it up)

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
merging.

**Pull request merged**
