### PR TITLE
Add libgda dependency to enable mysql connector

### PR DESCRIPTION
**Pull request by technicalpickles**
libgda has a notion of different providers for different databases. Currently, only sqlite3 is installed. This PR adds a dependency on mysql-client, which is enough for the build to detect and compile the mysql connector

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

cc @fxn who I was talking to about using @tenderlove's [gda gem](https://github.com/tenderlove/gda) that needs this for mysql support

### CODE REVIEW

**Comment by technicalpickles** [comment]
I found a previous PR to add support, but it was closed as stale https://github.com/Homebrew/homebrew-core/pull/27034 ... I don't see an obvious reason that kept it from being merged, aside from becoming stale.

**Comment by technicalpickles** [comment]
I am looking at the commit style error, and I can't figure out what I did wrong 🤔 

- prefixed with `libgda:`
- less than 50 lines
- 2 newlines

**Comment by technicalpickles** [comment]
> prefixed with libgda:

actually prefixed with `libda:` 🤦🏻

**Review by MikeMcQuaid — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
