### PR TITLE
radare2-0.10.4

### PR DESCRIPTION
**Pull request by G-Square**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Build failing _(quite impressively)_ on all three OS X versions.

**Comment by apjanke** [comment]
And the output includes a bunch of terminal control sequences, even though it's being piped to a file. That might be worth a minor upstream bug report, too.

**Comment by DomT4** [comment]
Status update on this?

**Comment by AlexKornitzer** [comment]
I assume we can close this now as 0.10.5 is out.

**Comment by MikeMcQuaid** [comment]
Yep, thanks.

**Pull request closed without merging**
