### PR TITLE
protobuf 25.2

### PR DESCRIPTION
**Pull request by bevanjkay**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
`opencv` failure
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2' 

Error: opencv: failed 
An exception occurred within a child process: 
Minitest::Assertion: 
Expected: 0
Actual: 1
```

Has been seen before when bumping to `python@3.12`.
https://github.com/Homebrew/homebrew-core/pull/153377

**Comment by cho-m** [comment]
May need to wait for https://github.com/Homebrew/homebrew-core/pull/158712 to get https://github.com/opencv/opencv/commit/00ca8f455e6a5588d905e3a0b268f18ee3fda5dd

**Comment by timsutton** [comment]
> May need to wait for #158712 to get [opencv/opencv@00ca8f4](https://github.com/opencv/opencv/commit/00ca8f455e6a5588d905e3a0b268f18ee3fda5dd)

https://github.com/Homebrew/homebrew-core/pull/158712 is now green so can potentially be re-reviewed / merged?

**Review by chenrui333 — APPROVED** [review]

**Comment by bevanjkay** [comment]
```
brew linkage --test sysdig
brew test --retry --verbose sysdig
brew test --retry --verbose knot
```

`sysdig` can be rev bumped in a follow up PR.

I'm not sure why `knot` is failing on linux.

**Pull request merged**
