### PR TITLE
jbig2dec 0.15

### PR DESCRIPTION
**Pull request by igas**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
Fails on test
```
==> /usr/bin/clang test.c -DJBIG_NO_MEMENTO -L/usr/local/Cellar/jbig2dec/0.15/lib -ljbig2dec -o test
test.c:10:11: warning: implicit declaration of function 'jbig2_image_new' is invalid in C99 [-Wimplicit-function-declaration]
  image = jbig2_image_new(ctx, 10, 10);
          ^
test.c:10:9: warning: incompatible integer to pointer conversion assigning to 'Jbig2Image *' (aka 'struct _Jbig2Image *') from 'int' [-Wint-conversion]
  image = jbig2_image_new(ctx, 10, 10);
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.c:11:3: warning: implicit declaration of function 'jbig2_image_release' is invalid in C99 [-Wimplicit-function-declaration]
  jbig2_image_release(ctx, image);
  ^
3 warnings generated.
==> ./test
Error: jbig2dec: failed
```

**Comment by apjanke** [comment]
The `jbig2.h` header has changed substantially between 0.14 and 0.15, removing `jbig2_image_new` and other functions. This effectively changes jbig2enc's API (if indeed it's intended to be a public API).

The change happened here: https://github.com/ArtifexSoftware/jbig2dec/commit/d48429529c894d2402edbf4bd718be316bea12c1#diff-06566a9d4c939de862ca6f5ee7705de5

I suggest changing the test to exercise the `jbig2dec` command instead of compiling something against `-ljbig2`. It looks to me like this package is intended to be a command line tool, not a public library API.

**Comment by apjanke** [comment]
According to https://bugs.ghostscript.com/show_bug.cgi?id=700144, the removal was intentional. Those functions were helper functions that were not intended to be part of the public API. We'll need to work on changing the test program.

**Comment by fxcoudert** [comment]
Reworked the test to check an actual file. Removed libpng option.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@fxcoudert or @igas any more ideas on fixing this?

**Comment by apjanke** [comment]
From the failed CI build log:

```
        Testing jbig2dec
[...]
==> /usr/local/Cellar/jbig2dec/0.15/bin/jbig2dec -t pbm --hash testJBIG2.jb2
Error: jbig2dec: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <1> expected but was
<0>.
```

It looks like the test program call is returning 0 (success) but the test is expecting an exit status of 1 (error/non-standard). 

Maybe all that needs to be tweaked is the expected exit status in the `shell_output` call here?

```
output = shell_output("#{bin}/jbig2dec -t pbm --hash testJBIG2.jb2", 1)
```

###  Details

The exit status of `jbig2dec` is not documented in `man jbig2dec`, but I would think that `0` would be fine and expected.

I glanced through the source code for `jbig2dec.c` from version 0.15, and it looks like `0` is indeed the exit status when things go normally.

```
int
main(int argc, char **argv)
{
[...]
    int result = 1;
[...]
    /* fin */
    result = 0;

cleanup:
    [... cleanup code omitted...]

    return result;
}
```

So it looks like unless something bad happens and "`goto cleanup`" is called, it should be exiting with exit status 0.

**Pull request closed without merging**
