### PR TITLE
lua-language-server 3.6.25

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by clason** [comment]
Hmm, looks like the same spurious macOS-11 failure as last time (#136038)...

**Comment by SMillerDev** [comment]
```
  Failed tests:
  -------------
  1) filewatch.test_2
  bee.lua/test/test_filewatch.lua:69: expected: nil, actual: <userdata:/private/tmp/test_bee/temp/test1>
  stack traceback:
  	bee.lua/test/test_filewatch.lua:69: in local 'assertHas'
  	bee.lua/test/test_filewatch.lua:71: in local 'f'
  	bee.lua/test/test_filewatch.lua:28: in upvalue 'test'
  	bee.lua/test/test_filewatch.lua:38: in upvalue 'filewatch.test_2'
```

**Comment by clason** [comment]
yep, that's the exact same failure.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Looks like some flaky test, we can merge it now.

**Pull request merged**
