### PR TITLE
apache-drill 1.19.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> Error: openjdk@8: no bottle available!
You can try to install from source with:
  brew install --build-from-source openjdk@8
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**Comment by cho-m** [comment]
`openjdk@8` isn't available for ARM.
Officially, Apache Drill requires Java 8: https://drill.apache.org/docs/embedded-mode-prerequisites/
Though, it looks like upstream has fixed bugs reported on Java 11.

So, either can keep Java 8 and drop ARM, or try with Java 11.

**Comment by carlocab** [comment]
This diff is weird:
```
❯ diffoscope *.arm64_big_sur.bottle*tar.gz *.big_sur.bottle*tar.gz
--- apache-drill--1.19.0.arm64_big_sur.bottle.tar.gz
+++ apache-drill--1.19.0.big_sur.bottle.tar.gz
│   --- apache-drill--1.19.0.arm64_big_sur.bottle.tar
├── +++ apache-drill--1.19.0.big_sur.bottle.tar
│ ├── file list
│ │ @@ -10,15 +10,15 @@
│ │  -r-xr-xr-x   0        0        0      169 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/drill-conf
│ │  -r-xr-xr-x   0        0        0      174 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/drill-config.sh
│ │  -r-xr-xr-x   0        0        0      173 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/drill-embedded
│ │  -r-xr-xr-x   0        0        0      177 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/drill-embedded.bat
│ │  -r-xr-xr-x   0        0        0      174 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/drill-localhost
│ │  -r-xr-xr-x   0        0        0      175 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/drill-on-yarn.sh
│ │  -r-xr-xr-x   0        0        0      170 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/drillbit.sh
│ │ --r-xr-xr-x   0        0        0      173 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/hadoop-excludes.txt
│ │ +-r-xr-xr-x   0        0        0      167 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/hadoop-excludes.txt
│ │  -r-xr-xr-x   0        0        0      165 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/runbit
│ │  -r-xr-xr-x   0        0        0      166 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/sqlline
│ │  -r-xr-xr-x   0        0        0      170 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/sqlline.bat
│ │  -r-xr-xr-x   0        0        0      170 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/submit_plan
│ │  -r-xr-xr-x   0        0        0      175 2021-06-05 06:27:33.000000 apache-drill/1.19.0/bin/yarn-drillbit.sh
│ │  drwxr-xr-x   0        0        0        0 2021-06-05 06:27:33.000000 apache-drill/1.19.0/libexec/
│ │  -rw-r--r--   0        0        0    65501 2021-06-05 06:27:33.000000 apache-drill/1.19.0/libexec/KEYS
│ ├── apache-drill/1.19.0/bin/hadoop-excludes.txt
│ │ @@ -1,2 +1,2 @@
│ │  #!/bin/bash
│ │ -JAVA_HOME="/opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" exec "/opt/homebrew/Cellar/apache-drill/1.19.0/libexec/bin/hadoop-excludes.txt"  "$@"
│ │ +JAVA_HOME="/usr/local/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" exec "/usr/local/Cellar/apache-drill/1.19.0/libexec/bin/hadoop-excludes.txt"  "$@"
```
I see now why we needed Homebrew/brew#11537.

Though, I don't understand why keg relocation isn't replacing `/opt/homebrew` and `/usr/local` with `@HOMEBREW_PREFIX@` (or `@HOMEBREW_CELLAR@` for `/{opt/homebrew,usr/local}/Cellar`).

This would be a problem if you tried to install this in a non-default prefix since this is [`any_skip_relocation`](https://github.com/Homebrew/homebrew-core/pull/79575/checks?check_run_id=2866629904#step:8:36).

@Rylan12, any idea of what's going on here? (In case you're not on 🏖️ yet...)

**Comment by cho-m** [comment]
Looks more like a file we shouldn't be doing `env_script_all_files` on.

It's a txt file containing:
```
asm
jackson
mockito
jets3t
log4j
logging
slf4j
jetty
jasper
jersey
eclipse
common
guava
servlet
parquet
```

It appears to be used in a Windows file `sqlline.bat`
```console
❯ rg hadoop-exclude
bin/hadoop-excludes.txt
2:JAVA_HOME="/opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" exec "/opt/homebrew/Cellar/apache-drill/1.19.0/libexec/bin/hadoop-excludes.txt"  "$@"

libexec/bin/sqlline.bat
150:    for /F "tokens=*" %%A in (%DRILL_BIN_DIR%\hadoop-excludes.txt) do (
172:    for /F "tokens=*" %%A in (%DRILL_BIN_DIR%\hadoop-excludes.txt) do (
```

**Comment by carlocab** [comment]
Good spot. I wasn't paying attention to what this file even was. It's possible we don't relocate text in `.txt` files, which is fine (though I don't see where in our keg relocation code we do that), and the fix would be to just remove the `.txt` files from `bin`.

If we don't have such an exclusion, this may be a sign that something needs fixing in our relocation code, though.

**Comment by carlocab** [comment]
Yup, I think we just exclude `.txt` files. For example, in `drillbit.sh`:
```sh
#!/bin/bash
JAVA_HOME="@@HOMEBREW_PREFIX@@/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" exec "@@HOMEBREW_CELLAR@@/apache-drill/1.19.0/libexec/bin/drillbit.sh"  "$@"
```

**Comment by cho-m** [comment]
TXT is probably rejected as part of metadata files:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg_relocate.rb#L194
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/metafiles.rb#L10-L13

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
