### PR TITLE
sshpass 1.10 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
`    Minitest::Assertion: Expected /SSHPASS:\ searching\ for\ password\ prompt\ using\ match\ "foo"/ to match "".`

**Comment by alebcay** [comment]
The test works locally for me, would appreciate some help with understanding why it's failing in CI.

Also looking for feedback regarding the `caveats`.

**Comment by chenrui333** [comment]
rebased to latest master

**Comment by chenrui333** [comment]
```
Full /usr/bin/git /Library/Taps/homebrew/homebrew-core fetch origin 7489e4fd01dfe617bbac37cec7b76d0a42f4fc04 output
  fatal: remote error: upload-pack: not our ref 7489e4fd01dfe617bbac37cec7b76d0a42f4fc04
fatal: bad object 7489e4fd01dfe617bbac37cec7b76d0a42f4fc04
```

**Pull request closed without merging**
