### PR TITLE
fastlane 2.171.0

### PR DESCRIPTION
**Pull request by joshdholtz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Your local copy of the core repo is outdated, so you need to do `brew update` then rebase this PR against `origin/master`.

**Comment by carlocab** [comment]
Does this still need `ruby@2.7`?

**Comment by chenrui333** [comment]
ci actually still use 2.4-2.6 😂 
https://github.com/fastlane/fastlane/blob/master/.circleci/config.yml#L228-L232

**Review by carlocab — APPROVED** [review]

**Comment by ainame** [comment]
@chenrui333 Good catch👍 🙈

**Comment by chenrui333** [comment]
[ruby bump PR](https://github.com/fastlane/fastlane/pull/17861) by @ainame

**Pull request closed without merging**
