### PR TITLE
advancemame: remove

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> License: https://github.com/amadvance/advancemame/blob/master/COPYING Dunno what should be picked.

should all of `GPL-2.0-or-later` and `BSD-3-Clause` as it is showed on their site

> The MAME project as a whole is distributed under the terms of the [GNU General Public License, 2](https://opensource.org/licenses/GPL-2.0) (GPL-2.0), since it contains code made available under multiple GPL-compatible licenses. A great majority of files (over 90% including core files) are under the [BSD-3-Clause License](https://opensource.org/licenses/BSD-3-Clause) and we would encourage new contributors to distribute files under this license.

https://www.mamedev.org/

**Comment by p-linnane** [comment]
According to the headers, the advancemame stuff itself is `GPL-2.0-or-later:

>  * This file is part of the Advance project.
>  *
>  * Copyright (C) 2003, 2004 Andrea Mazzoleni
>  *
>  * This program is free software; you can redistribute it and/or modify
>  * it under the terms of the GNU General Public License as published by
>  * the Free Software Foundation; either version 2 of the License, or
>  * (at your option) any later version.

Regarding that MAME license...that is problematic as it's not an open source license. cc @Homebrew/core for thoughts.

**Comment by p-linnane** [comment]
> > License: https://github.com/amadvance/advancemame/blob/master/COPYING Dunno what should be picked.
> 
> should all of `GPL-2.0-or-later` and `BSD-3-Clause` as it is showed on their site
> 
> > The MAME project as a whole is distributed under the terms of the [GNU General Public License, 2](https://opensource.org/licenses/GPL-2.0) (GPL-2.0), since it contains code made available under multiple GPL-compatible licenses. A great majority of files (over 90% including core files) are under the [BSD-3-Clause License](https://opensource.org/licenses/BSD-3-Clause) and we would encourage new contributors to distribute files under this license.
> 
> https://www.mamedev.org/

It uses an old version of MAME that is not covered under this license apparently.

**Review by p-linnane — DISMISSED** [review]
Need to resolve the license issue. Requesting changes so this doesn't accidentally get merged.

**Comment by chenrui333** [comment]
> Need to resolve the license issue. Requesting changes so this doesn't accidentally get merged.

Since the project is using OSS license, maybe we can just move the license change into a separate PR and get the change out?

**Comment by MikeMcQuaid** [comment]
> Since the project is using OSS license

Is it? It sounds like @p-linnane said the opposite?

**Comment by krehel** [comment]
I suspect this may be what @p-linnane is referring to (please correct me if I'm wrong) -

http://www.advancemame.it/doc-faq#8

> 8.1 Is MAME 0.106 Open Source/Free Software ?
> 
> No. The MAME 0.106 License is not an Open Source License as defined at http://www.opensource.org/ and not a Free Software License as defined at http://www.gnu.org/.
> 
> 8.2 How can be MAME 0.106 not Open Source/Free Software when the latest MAME is released with the GPL 2 License ?
> 
> MAME 0.106 was never released with the GPL 2 License. Most, if not all, same source code can be found released with the GPL 2 in the latest MAME, but it's safer to assume that MAME 0.106 is not GPL 2.

As mentioned in https://github.com/Homebrew/homebrew-core/pull/162335#issuecomment-1937841805, the current versions of MAME appear to be GPL 2 or BSD-3-Clause, but this version of MAME used in this software (from 2006, version 0.106, found [here](https://www.mamedev.org/?p=87)) may not be.  

The same source may be equivalent in later versions, though.

**Comment by p-linnane** [comment]
Correct. That is my exact concern.

**Comment by chenrui333** [comment]
oh, ok, I mis-interpret a bit (I was mostly reading the latest mame license part, as we already have mame formula). 

Sounds like we either need to dig a bit with 0.106 source code (to see the license situation) or maybe disable the formula due to the license implication.

----

Actually I could not find mame 0.106 source code anywhere. And from [the earliest legal notice snapshot](https://web.archive.org/web/20100311021704/http://mamedev.org/legal.html) in the internetarchive, this is the COPYRIGHT notice

> Copyright
> The code in MAME is the work of hundreds of developers, each of whom owns the copyright to the code they wrote. There is no central copyright authority you can license the code from. The proper way to use the MAME source code is to examine it, using it to understand how the games worked, and then write your own emulation code. Sorry, there is no free lunch here.

**Comment by chenrui333** [comment]
For mamedev/mame repo, the earliest tag is with [mame0121u1](https://github.com/mamedev/mame/releases/tag/mame0121u1)

**Comment by chenrui333** [comment]
I think I found the distribution license per internetarchive in here, 

This is the release archive page, https://web.archive.org/web/20060603230620/http://mamedev.org/release.html
And this is the distribution license page, https://web.archive.org/web/20060615013918/http://mamedev.org/license.html
This is a separate license https://web.archive.org/web/20060615013955/http://mamedev.org/licensees.html (for `Who is allowed to include MAME with their commercial product`)

**Comment by p-linnane** [comment]
Great find!

>Redistributions may not be sold, nor may they be used in a commercial product or activity.

Goes against free redistribution as defined in https://opensource.org/osd/. We should remove this package from Homebrew.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
> Goes against free redistribution as defined in https://opensource.org/osd/. We should remove this package from Homebrew.

Agreed, sorry.

**Review by MikeMcQuaid — APPROVED** [review]

**Review by krehel — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
