### PR TITLE
Revert "calceph 4.0.2"

### PR DESCRIPTION
**Pull request by gastineau**
Reverts Homebrew/homebrew-core#200289

### CODE REVIEW

**Comment by gastineau** [comment]
The original archive of calceph 4.à.2 was invalid. It has been replaced on the original server.

**Comment by stefanb** [comment]
> Full audit --formula calceph --online --git --skip-style output
  calceph
    * stable version should not decrease (from 4.0.2 to 4.0.1)

🤔  can thet tag a new version instead?

**Comment by gastineau** [comment]
Could you force the change of the hash? I try but the CI fails due to the change of hash.

**Comment by gastineau** [comment]
We will tag a new version and remove the previous one

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/200301

**Comment by chenrui333** [comment]
just for future, we can just add a label like [CI-version-downgrade](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+label%3ACI-version-downgrade) (the installed users would need to reinstall the formula)

But it would be definitely favorable to have a new release.

**Pull request closed without merging**
