### PR TITLE
kustomize 3.2.1

### PR DESCRIPTION
**Pull request by mgoodness**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
fatal: Remote branch v3.2.1 not found in upstream origin
```

**Comment by richardmarshall** [comment]
The new structure of kustomize repo with the binary being a separate module in the `kustomize` subdirectory necessitates building it from within the subdirectory. Otherwise the top level `go.mod` will be used producing the error seen here.

```
kustomize/main.go:9:2: use of internal package sigs.k8s.io/kustomize/kustomize/v3/internal/commands not allowed
```

**Comment by chenrui333** [comment]
Should be good now, tested locally.

Thanks @richardmarshall for the direction.

**Comment by chenrui333** [comment]
14:29:57 ==> /usr/local/Cellar/kustomize/3.2.1/bin/kustomize version
14:29:57 /usr/local/Cellar/kustomize/3.2.1/bin/kustomize: /usr/local/Cellar/kustomize/3.2.1/bin/kustomize: cannot execute binary file
14:29:57 Error: kustomize: failed
14:29:57 An exception occurred within a child process:
14:29:57   Test::Unit::AssertionFailedError: <0> expected but was
14:29:57 <126>.

**Pull request closed without merging**
