### PR TITLE
marathon-swift: don't unconditionally call Xcode version

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
I am not really sure what's going on with that test failure 🙃.

**Comment by ilovezfs** [comment]
Not sure this makes sense since we already have a hard Xcode dependency above.

**Comment by DomT4** [comment]
Thinking about it this one _should_ be guarded by being inside `def install`, so shouldn't be problematic to remain as-is. The other two however do cause `readall` failures.

**Comment by ilovezfs** [comment]
Yeah, I'd be surprised if this could cause a problem from within `def install`.

**Pull request closed without merging**
