### PR TITLE
ideviceinstaller: add license

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Hmm, the GitHub API  ( https://api.github.com/repos/libimobiledevice/ideviceinstaller/license )says it's under GPL-2.0 as well as the COPYING file, but COPYING.lesser and the sidebar says it's LGPL-2.1. When GitHub displays the COPYING file, the contents of the file say GPL-2.0 but the header says LGPL-2.1: https://github.com/libimobiledevice/libimobiledevice/blob/master/COPYING

**Comment by dtrodrigues** [comment]
The website also says LGPL-2.1: https://libimobiledevice.org/docs/libimobiledevice/latest/

**Comment by Bo98** [comment]
> When GitHub displays the COPYING file, the contents of the file say GPL-2.0 but the header says LGPL-2.1: https://github.com/libimobiledevice/libimobiledevice/blob/master/COPYING

Are you looking at the right repo?

https://github.com/libimobiledevice/ideviceinstaller

**Comment by dtrodrigues** [comment]
You're right - I was looking at a different repo when verifying. I had clicked on the github repo on the formula homepage which took me to `libimobiledevice/libimobiledevice` which is exhibiting the strange licenses. `GPL-2.0` in this PR is indeed correct based on the source repository for this formula, so this should be good to be merged in.

**Pull request merged**
