### PR TITLE
pgbadger 8.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Is there a reason why 555 and 444 aren't OK?

**Comment by MikeMcQuaid** [comment]
Pretty sure they are sorted up after installation anyway 😥

**Comment by ilovezfs** [comment]
@MikeMcQuaid I'm confused what the goal is.

**Comment by MikeMcQuaid** [comment]
I guess to fix the permissions that are then autofixed again regardless 😀. Remove it and if tests/audit pass then 👍

**Comment by ilovezfs** [comment]
@MikeMcQuaid perhaps it's a secret test to see if the permissions fixer works :)

**Pull request closed without merging**
