### PR TITLE
getmail: use /usr/bin/python shebangs

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes https://github.com/Homebrew/homebrew-core/issues/24875.

### CODE REVIEW

**Comment by telemachus** [comment]
@DomT4 Thanks so much! (I never would have thought of that beautifully simple fix.)

**Comment by DomT4** [comment]
No worries! I guess there's possibly a discussion here that it might be _"the right thing to do"_ to switch this to using Homebrew's `python@2` for the SSL/TLS benefits on older platforms, which would be limited to TLSv1.0 using the system `python` there, but I'll let ILZ chime in on that.

**Comment by ilovezfs** [comment]
Let's avoid depending on @ formulae whenever possible as usual.

**Comment by ilovezfs** [comment]
Thanks @DomT4!

**Pull request closed without merging**
