### PR TITLE
Separate shell variables to hash

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Changes `"SHELL=bash foo bar"` to `{ "SHELL" => "bash" }, "foo", "bar"`

This is needed for https://github.com/Homebrew/brew/pull/7696

Can someone in @Homebrew/linux take a look at these? Last time there was a similar change it broke something on Linux (I believe the problem related to `zsh` not being installed)

### CODE REVIEW

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Thank you for this style fix, Rylan!

When a PR is not expected to change the bottles (a style fix) do we merge it without updating the bottles?

**Comment by Rylan12** [comment]
My understanding is that a "Squash and merge" will do the trick here.

The purpose of the `safe_popen_read` is to throw an error if the command fails. In this case, the commands all worked normally in the original formulae so there is no functionality change (and, therefore, no need to rebuild bottles). In the future, though, if the commands stop doing what they were expected to do, `safe_popen_read` will throw an error (instead of just ignoring it) and bring it to someone's attention.

An example of a change that did require rebuilding bottles is #55682. In that case, the failure was ignored by `popen_read` so the completion wasn't generated. Rebuilding the bottles was necessary so that users wouldn't have to wait for the next version to be able to install pipenv with the correct completion.

Let me know if that is incorrect.

**Comment by SMillerDev** [comment]
I think that's spot on @Rylan12

**Comment by Rylan12** [comment]
> Edit: except for the squash actually. That should be rebase since you have one commit per formula as it should be.

In what situation would you use squash instead of rebase?

**Comment by SMillerDev** [comment]
> Makes sense. In what situation would you use squash instead of rebase?

When people don't follow the [commit guidelines](https://docs.brew.sh/Formula-Cookbook#commit). 

> Also, to clarify, is the reviewer usually the one who merges or does the author merge (after an approving review and assuming they have write access)

Usually it's neither (the bot does it). But for things that don't need bottle changes the reviewer usually merges directly (if they don't wait for the bot).

**Comment by Rylan12** [comment]
Just to confirm my understanding (while we're talking about this):

- If bottles need to be updated:
    - The reviewer approves and runs `brew pr-publish` on their machine which takes care of everything
    - If the author didn't follow the commit guidelines, the reviewer runs `brew pr-pull` which will let the reviewer squash commits appropriately before publishing
- If bottles don't need to be updated:
    - The reviewer approves and clicks Rebase and Merge (if it's only one formula, though, squash and merge will do the same thing)
    - If the author didn't follow guidelines the reviewer clicks Squash and Merge (to squash commits before the merge)

**Comment by SMillerDev** [comment]
> The reviewer approves and runs brew pr-publish on their machine which takes care of everything

This is only the case for new formula, version bumps happen automagically.

>        If the author didn't follow the commit guidelines, the reviewer runs brew pr-pull which will let the reviewer squash commits appropriately before publishing

Same as bellow, but that's only if you want to merge it right a way. It's perfectly fine to ask contributors to fix their commits.

>        The reviewer approves and clicks Rebase and Merge (if it's only one formula, though, squash and merge will do the same thing)

Yeah, or you wait for the bot

>        If the author didn't follow guidelines the reviewer clicks Squash and Merge (to squash commits before the merge)

Unless it's multiple formula, then asking the committer or `pr-pull` are your only options

**Comment by Rylan12** [comment]
Ah, thanks for the clarification.

Is `pr-pull` also only for new formulae?

> >   The reviewer approves and clicks Rebase and Merge (if it's only one formula, though, squash and merge will do the same thing)
> 
> Yeah, or you wait for the bot

Essentially what you're saying is that after approval, the bot will take care of everything including rebuilding bottles. If rebuilding bottles isn't necessary, manually merging before the bot does will take care of it. Correct?

**Comment by SMillerDev** [comment]
> Is pr-pull also only for new formulae?

`pr-pull` is only in case you need to manually change things which in 99% of cases shouldn't happen (since you should ask people to fix their mistakes). `pr-publish` is for when you don't want to wait for the bot (or new formulae).

> Essentially what you're saying is that after approval, the bot will take care of everything including rebuilding bottles. If rebuilding bottles isn't necessary, manually merging before the bot does will take care of it. Correct?

Yes, although technically the PR rebuilds the bottles and the bot just makes them available.

**Pull request merged**
