### PR TITLE
radare2 2.9.0

### PR DESCRIPTION
**Pull request by jrozner**
- [X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jrozner** [comment]
@javian that's not a pre-release tag it's just specifying that the release is pre-r2con which is their conference for the software. Per discussion with the project head the release schedule is a minor release every 6 weeks and a major release every year after the conference. https://github.com/radare/radare2/pull/11272#issuecomment-417347397

I can look into the build failure and see what's going on. I haven't had that issue locally but maybe something has changed with dependencies.

**Comment by jrozner** [comment]
I'm not able to replicate this on my own computer. What are my options for understanding what's going on and why it's not building correctly on the Jenkins boxes? I'm trying to figure out how to get to the actual build logs but haven't found them.

**Comment by fxcoudert** [comment]
Actually, there is an earlier error: 

```
asm_x86_udis.c:59:11: error: passing 'RStrBuf' to parameter of incompatible type 'const void *'
        strncpy (op->buf_asm, ud_insn_asm (&d), R_ASM_BUFSIZE-1);
                 ^~~~~~~~~~~
/usr/include/secure/_string.h:124:62: note: expanded from macro 'strncpy'
                __builtin___strncpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                                                           ^~~~
/usr/include/secure/_common.h:39:54: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                     ^~~~~~
asm_x86_udis.c:60:13: error: subscripted value is not an array, pointer, or vector
        op->buf_asm[R_ASM_BUFSIZE-1] = 0;
        ~~~~~~~~~~~^~~~~~~~~~~~~~~~
asm_x86_udis.c:61:26: error: passing 'RStrBuf' to parameter of incompatible type 'const char *'
        if (opsize<1 || strstr (op->buf_asm, "invalid"))
                                ^~~~~~~~~~~
/usr/include/string.h:89:26: note: passing argument to parameter '__big' here
char    *strstr(const char *__big, const char *__little);
                            ^
asm_x86_udis.c:65:17: error: passing 'RStrBuf' to parameter of incompatible type 'const char *'
                if (!strncmp (op->buf_asm, "je ", 3)) {
                              ^~~~~~~~~~~
/usr/include/string.h:84:26: note: passing argument to parameter '__s1' here
int      strncmp(const char *__s1, const char *__s2, size_t __n);
                             ^
asm_x86_udis.c:66:12: error: passing 'RStrBuf' to parameter of incompatible type 'const void *'
                        memcpy (op->buf_asm, "jz", 2);
                                ^~~~~~~~~~~
/usr/include/secure/_string.h:62:62: note: expanded from macro 'memcpy'
                __builtin___memcpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                                           ^~~~
/usr/include/secure/_common.h:38:55: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                      ^~~~~~
asm_x86_udis.c:67:24: error: passing 'RStrBuf' to parameter of incompatible type 'const char *'
                } else if (!strncmp (op->buf_asm, "jne ", 4)) {
                                     ^~~~~~~~~~~
/usr/include/string.h:84:26: note: passing argument to parameter '__s1' here
int      strncmp(const char *__s1, const char *__s2, size_t __n);
                             ^
asm_x86_udis.c:68:12: error: passing 'RStrBuf' to parameter of incompatible type 'const void *'
                        memcpy (op->buf_asm, "jnz", 3);
                                ^~~~~~~~~~~
/usr/include/secure/_string.h:62:62: note: expanded from macro 'memcpy'
                __builtin___memcpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                                           ^~~~
/usr/include/secure/_common.h:38:55: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                      ^~~~~~
7 errors generated.
make[1]: *** [asm_x86_udis.o] Error 1
```

see the output at https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/30796/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_radare2/

**Comment by jrozner** [comment]
Building radare2 seems to work fine but I'm able to get somewhat similar build errors now on the radare2-extras tarball. Trying to track down exactly what is going on

**Comment by jrozner** [comment]
Since this has been published there has been another release and the current version is now up to 3.0.

In talking with the head of the project it is apparently unintended to build the extras package directly and distribute it as a whole. Instead it is recommended to package the individual project individually or use the r2 package manage to install them. There are currently build failures that exist due to API changes and these are being addressed.

Due to the above information I'm going to bump the version up to 3.0 (the current version) and remove the build step for extras so that the rest can be currently built

**Comment by fxcoudert** [comment]
I'd suggest we do this in a clean PR. Closing this one.

**Pull request closed without merging**
