### PR TITLE
buildozer 3.3.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/bazelbuild/homebrew-tap/pull/98#issuecomment-652086509

cc @philwo @alexeagle

### CODE REVIEW

**Comment by chenrui333** [comment]
Some audit failure (while license is in here `https://github.com/bazelbuild/buildtools/blob/master/LICENSE`)
```
==> brew audit --skip-style buildozer --new-formula
==> FAILED
Error: 1 problem in 1 formula detected
buildozer:
  * No license specified for package.
```

**Comment by Bo98** [comment]
Please ignore that audit until brew 2.4.3 releases.

**Comment by chenrui333** [comment]
Sounds good!

**Comment by chenrui333** [comment]
rebased to latest master

**Pull request closed without merging**
