### PR TITLE
luvit 2.18.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by SMillerDev** [comment]
`lit` should be bumped to 3.8.5 according to the comments: https://github.com/luvit/luvit/blob/2.18.0/Makefile
`luvi` should be downgraded according to https://raw.githubusercontent.com/luvit/lit/3.8.5/get-lit.sh

**Comment by carlocab** [comment]
That doesn't look right. Opened luvit/lit#291 to clarify.

**Comment by carlocab** [comment]
Upstream confirmed the correct versions, so I updated them appropriately.

**Comment by carlocab** [comment]
Upstream retagged `lit`, so updated the commit hash. Confirmed to be intentional in luvit/lit#291.

**Review by SMillerDev — APPROVED** [review]

**Comment by creationix** [comment]
Sorry for the trouble.  I've not been maintaining it for many years and there are some bumps getting back into it.

**Pull request closed without merging**
