### PR TITLE
perl 5.28.0

### PR DESCRIPTION
**Pull request by ilovezfs**
- work around DYLD_LIBRARY_PATH problem with a symlink
- run `make test` while bottling
- re-enable option to run `make test` on El Capitan and later (was 
  already enabled on prior versions), but make it opt-in
- remove unneeded clock_gettime fix for 10.11

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 it seems the bug from https://rt.perl.org/Ticket/Display.html?id=126706 has now infected the main build 😿

**Comment by DomT4** [comment]
Finally found some time, and the answer is nope; you've found the easiest way around the issue. Nothing I can come up with is easier/nicer/better.

I can only think at this point that `perl` either don't test stuff against macOS themselves, do so in a SIP-disabled environment, or do so on an old version of macOS. I think it's probably worth merging this in because getting this fixed will _take time_, but we should make some noise upstream about `DYLD_LIBRARY_PATH` because clearly there's some gap in communication there.

**Comment by ilovezfs** [comment]
>I can only think at this point that perl either don't test stuff against macOS themselves, do so in a SIP-disabled environment, or do so on an old version of macOS.

@mistydemeo pointed out yesterday that as noted on https://rt.perl.org/Public/Bug/Display.html?id=126706 it's specific to -Duseshrplib builds so the problem is most likely that upstream doesn't test -Duseshrplib on macOS, as opposed to everyone running with SIP disabled 🙈

**Comment by DomT4** [comment]
> it's specific to -Duseshrplib builds so the problem is most likely that upstream doesn't test -Duseshrplib on macOS

Yeah, this seems likely. I'm faintly bemused as to why they _wouldn't test it_ when us, MacPorts & Apple themselves have been shipping Perl on macOS with `-Duseshrplib`.

**Comment by DomT4** [comment]
Do you want to do the honours & reporting this or do you want me to go poke the bear again?

**Comment by ilovezfs** [comment]
Probably for the same reason lua requires patching to build a shared library. Because they like to torture us.

**Comment by DomT4** [comment]
> Probably for the same reason lua requires patching to build a shared library

Aye, I've been meaning to poke them on at some point, with the vague hope that it might ever get fixed for the 5.3 branch at least.

**Comment by ilovezfs** [comment]
>Do you want to do the honours & reporting this or do you want me to go poke the bear again?

If you don't mind, that would be lovely. FWIW I think that modern build systems tend to use `@rpath` to get around the fact that DYLD_LIBRARY_PATH is useless now.

**Comment by DomT4** [comment]
Will do. Spent the last 10 minutes trying to find a `New Ticket` button on the website before remembering bugs get emailed in & then displayed on the public interface. Today is a strong day for my mind functioning properly, evidently.

**Comment by ilovezfs** [comment]
>Today is a strong day for my mind functioning properly, evidently.

💊

**Comment by DomT4** [comment]
I'm going to be terribly British and guess that going from about 10 cups of tea yesterday down to a mere 3 today has mentally ruined me.

**Comment by ilovezfs** [comment]
☕️ is obviously the solution.

**Comment by DomT4** [comment]
https://rt.perl.org/Ticket/Display.html?id=133306

**Comment by ilovezfs** [comment]
Awesome thanks @DomT4 

Interestingly, I'm seeing one test fail during `make test`

```
cpan/DB_File/t/db-hash ......................................... Use of uninitialized value $value in string eq at t/db-hash.t line 224.
Use of uninitialized value $values[0] in string eq at t/db-hash.t line 224.
Use of uninitialized value $value in lc at t/db-hash.t line 224.
Use of uninitialized value $h{""} in string eq at t/db-hash.t line 243.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value in numeric eq (==) at t/db-hash.t line 252.
Use of uninitialized value $foo[18] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[36] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[48] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[58] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[59] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[60] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[62] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[63] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[92] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[114] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[140] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[187] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[188] in join or string at t/db-hash.t line 261.
Use of uninitialized value $foo[189] in join or string at t/db-hash.t line 261.
Use of uninitialized value $h{"Fred"} in string eq at t/db-hash.t line 572.
Use of uninitialized value $v in concatenation (.) or string at t/db-hash.t line 748.
FAILED at test 23
```
Do you get the same?

**Comment by chdiza** [comment]
FYI, I couldn't get this version of perl to compile on El Capitan even with the adjustments in this PR.  Error messages similar to the bug report.

**Comment by ilovezfs** [comment]
@chdiza odd since it passed CI. How are you building?

**Comment by DomT4** [comment]
> Do you get the same?

No, couldn't reproduce that.

```
cpan/DB_File/t/db-btree ........................................ ok
cpan/DB_File/t/db-hash ......................................... ok
cpan/DB_File/t/db-recno ........................................ ok
...

==> Summary
🍺  /usr/local/Cellar/perl/5.28.0: 2,459 files, 63MB, built in 23 minutes 28 seconds
```

**Comment by ilovezfs** [comment]
Odd. Thank you for testing that.

**Comment by DomT4** [comment]
FWIW:

```
HOMEBREW_VERSION: 1.6.9-29-ga75a8c6
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a75a8c69b39aa9584c299d37826a1700256e8ab8
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e6b1bda11a730d3c61c56f97e91fb1e900c96d7f
Core tap last commit: 35 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /usr/local/var/homebrewcache
HOMEBREW_CASK_OPTS: --require-sha
HOMEBREW_DEVELOPER: 1
HOMEBREW_GIT: /usr/local/opt/git/bin/git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LINKAGE_CACHE: 1
HOMEBREW_LOGS: /usr/local/var/homebrewcache/logs
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_SANDBOX: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/opt/git/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

**Comment by ilovezfs** [comment]
PR refreshed.

**Review by DomT4 — APPROVED** [review]

**Comment by ilovezfs** [comment]
`make test` fails on 10.11. How wonderful.

**Comment by ilovezfs** [comment]
Interestingly the error mentions one of the files subjected to our `inreplace` so that may be the cause.

**Comment by ilovezfs** [comment]
I think we can ditch the `inreplace` since we stopped setting SDKROOT and require CLT on <= 10.12.

**Comment by ilovezfs** [comment]
🚀

**Comment by DomT4** [comment]
Definitely nice to see that chunky `inreplace` disappear, that's for sure. Thanks for getting this update pushed through.

**Comment by ilovezfs** [comment]
You did the hard part! Thank you, too

**Pull request closed without merging**
