### PR TITLE
terraform 0.7.9

### PR DESCRIPTION
**Pull request by cblecker**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by akerl** [comment]
@cblecker does this formula work for you?

I get the following:

```
==> make bin
Last 15 lines from /Users/akerl/Library/Logs/Homebrew/terraform/05.make:
2016-11-05 20:50:56 -0700

make
bin

go generate $(go list ./... | grep -v /terraform/vendor/)
==> Checking that code complies with gofmt requirements...
2016/11/05 20:51:01 Generated command/internal_plugin_list.go
gofmt needs running on the following files:
./command/internal_plugin_list.go
You can use the command: `make fmt` to reformat code.
make: *** [fmtcheck] Error 1
```

**Comment by akerl** [comment]
And of course now I've retried so I can capture more debug info, and it worked this time.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Passed on CI, so merged as 1fe6cad2ed8e1ab7aad76ef80985b45190aca0d0.  Thanks!

**Pull request closed without merging**
