### PR TITLE
harfbuzz 3.1.2

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by miccal** [comment]
Just two failures on Linux:
```
Warning: 1 failed step ignored!
brew linkage --cached --test --strict easyrpg-player
Error: 1 failed step!
brew test --retry --verbose plantuml
```
Should I revision bump `easyrpg-player`?

**Comment by SMillerDev** [comment]
Sounds like a good plan

**Comment by carlocab** [comment]
No, please don't rev bump `easyrpg-player` here. The strict linkage test is for opportunistic linkage -- rev bumps with other formulae only makes that worse.

**Review by carlocab — APPROVED** [review]
`plantuml` failure on Linux is pre-existing. Everything else is a warning.

**Pull request closed without merging**
