### PR TITLE
rawdog 0.1.5 (new formula)

### PR DESCRIPTION
**Pull request by jakethekoenig**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]

**Comment by jakethekoenig** [comment]
Hey sorry for the mess up. I saw your comment about opening from a non org fork but thought I could open this and then change the settings to allow you to push. But then couldn't figure out how. I'll open a 3rd one with a fork under my account :(

**Comment by p-linnane** [comment]
> Hey sorry for the mess up. I saw your comment about opening from a non org fork but thought I could open this and then change the settings to allow you to push. But then couldn't figure out how. I'll open a 3rd one with a fork under my account :(

No need. I've got it this time,

**Review by p-linnane — APPROVED** [review]

**Comment by jakethekoenig** [comment]
> > Hey sorry for the mess up. I saw your comment about opening from a non org fork but thought I could open this and then change the settings to allow you to push. But then couldn't figure out how. I'll open a 3rd one with a fork under my account :(
> 
> No need. I've got it this time,

Okay great. I'll close [this one](https://github.com/Homebrew/homebrew-core/pull/162988) then.

**Comment by p-linnane** [comment]
Need to let CI run through once more and then we can get it merged.

**Comment by p-linnane** [comment]
Actually, since you already have that other PR open, let's just use that one. Sorry for all the back and forth.

**Pull request closed without merging**
