### PR TITLE
xmrig-amd: new formula, v2.8.4

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
Seems like it can't be tested in Jenkins, since it requires AMD GPU :(

**Comment by yurikoles** [comment]
bump?

**Comment by yurikoles** [comment]
Bump?

**Comment by SMillerDev** [comment]
@Homebrew/core any opinions on something that can't be tested on Jenkins?

**Comment by yurikoles** [comment]
@MikeMcQuaid Ok.

**Comment by MikeMcQuaid** [comment]
@yurikoles Yup, sorry about that ❤️

**Comment by yurikoles** [comment]
This formula can be installed not via:
```brew install yurikoles/yurikoles/xmrig-amd```

**Pull request closed without merging**
