### PR TITLE
license-eye: update to use apache archive dist

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

seen in https://github.com/Homebrew/homebrew-core/actions/runs/7284497233/job/19850411474?pr=157782
relates to #157782

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @kezhenxu94 (sorry to tag you in here, but did not find a good way to file an upstream issue, can you confirm if there was release re-tagging happened? Thanks! 🙏 )

**Comment by kezhenxu94** [comment]
> cc @kezhenxu94 (sorry to tag you in here, but did not find a good way to file an upstream issue, can you confirm if there was release re-tagging happened? Thanks! 🙏 )

Hi, thanks for tagging me for the information. From the ASF release policy we won't retag a release that was announced , but before an announced official release it can happen that we retag a draft release(on GitHub it's not displayed as the latest release), does it have an impact here?

**Comment by SMillerDev** [comment]
Do you know if that happened for this release? 

We'll need to make sure we don't ship pre-releases @chenrui333

**Comment by chenrui333** [comment]
> > cc @kezhenxu94 (sorry to tag you in here, but did not find a good way to file an upstream issue, can you confirm if there was release re-tagging happened? Thanks! 🙏 )
> 
> Hi, thanks for tagging me for the information. From the ASF release policy we won't retag a release that was announced , but before an announced official release it can happen that we retag a draft release(on GitHub it's not displayed as the latest release), does it have an impact here?

what is the best place to track the new releases (blog or mailing list)? Thanks!

**Comment by chenrui333** [comment]
or would this `https://archive.apache.org/dist/skywalking/eyes/0.5.0/` a better place (we actually use apache archive for the other apache formulae)?

**Comment by kezhenxu94** [comment]
> or would this `https://archive.apache.org/dist/skywalking/eyes/0.5.0/` a better place (we actually use apache archive for the other apache formulae)?

This is the source of truth of a release in ASF, all current and legacy releases will be in this place so you can safely use this link to track the releases

**Comment by chenrui333** [comment]
> > or would this `https://archive.apache.org/dist/skywalking/eyes/0.5.0/` a better place (we actually use apache archive for the other apache formulae)?
> 
> This is the source of truth of a release in ASF, all current and legacy releases will be in this place so you can safely use this link to track the releases

Sounds great, I will use that then.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
