### PR TITLE
ppsspp 1.4

### PR DESCRIPTION
**Pull request by wickles**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bfontaine** [comment]
Install failed:
```
CMake Error at /usr/local/Cellar/cmake/3.8.0/share/cmake/Modules/FindPkgConfig.cmake:471 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.8.0/share/cmake/Modules/FindPkgConfig.cmake:589 (_pkg_check_modules_internal)
  cmake/Modules/FindFFmpeg.cmake:98 (pkg_check_modules)
  cmake/Modules/FindFFmpeg.cmake:120 (find_ffmpeg)
  CMakeLists.txt:462 (find_package)
```

**Comment by wickles** [comment]
I don't understand the problem. Does this just mean it needs `pkg-config` added as a build dependency?

**Comment by ilovezfs** [comment]
probably!

**Comment by bfontaine** [comment]
Thank you for your contribution to Homebrew, @wickles; we appreciate it! 🎉

**Pull request closed without merging**
