### PR TITLE
dep 0.2.0 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`goose` and `pilosa` should be able to use this.

### CODE REVIEW

**Comment by AlekSi** [comment]
Thank you!

**Comment by ilovezfs** [comment]
@AlekSi you're welcome!

**Comment by AlekSi** [comment]
But you may want to update it to v0.2.1 😆 https://github.com/golang/dep/releases/tag/v0.2.1

**Comment by ilovezfs** [comment]
@AlekSi voilà https://github.com/Homebrew/homebrew-core/pull/16387

**Comment by AlekSi** [comment]
And to v0.3.0: https://github.com/golang/dep/releases/tag/v0.3.0 😂

**Pull request closed without merging**
