### PR TITLE
rubyfmt 0.3.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by claui** [comment]
Looks like the tool was [Rewritten In Rust](https://github.com/penelopezone/rubyfmt/commit/a52acfed2b6466118b67daac39b7d3a50a5657bd#diff-04c6e90faac2675aa89e2176d2eec7d8R8) some time ago so we need `depends_on "rust" => :build`.

**Comment by dtrodrigues** [comment]
Thanks for the tip @claui

**Comment by claui** [comment]
You’re welcome @dtrodrigues!

```

error: 'ruby/config.h' file not found
188
warning: #include "ruby/config.h"
189
warning:          ^~~~~~~~~~~~~~~
190
warning: 1 error generated.
```

Hmm, I have no idea why this error occurs.
And why only on High Sierra?

**Comment by dtrodrigues** [comment]
Me neither - the project checks out the entire Ruby source code as a submodule which seems strange to me. It does build locally for me on Catalina (as well as in CI for 10.15).

The README currently states
```
Does it work right now?

No, but it's getting really close
```

I'm going to close this PR in case somebody else wants to work on it.

**Comment by claui** [comment]
> I'm going to close this PR in case somebody else wants to work on it.

Fair enough.
Thanks @dtrodrigues anyway!

**Pull request closed without merging**
