### PR TITLE
ocrmypdf 10.3.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dtrodrigues** [comment]
`brew update-python-resources` from https://github.com/Homebrew/brew/pull/8059 did not update `Pillow` from `7.1.2` to `7.2.0`.

**Comment by jonchang** [comment]
Odd, this is what I got from `pipgrip`:

```
% pipgrip --no-cache-dir ocrmypdf==10.3.0
ocrmypdf==10.3.0
cffi==1.14.0
pycparser==2.20
coloredlogs==14.0
humanfriendly==8.2
img2pdf==0.3.6
pillow==7.2.0
pdfminer-six==20200517
chardet==3.0.4
pycryptodome==3.9.8
sortedcontainers==2.2.2
pikepdf==1.17.2
lxml==4.5.2
pluggy==0.13.1
reportlab==3.5.46
tqdm==4.48.0
```

**Comment by dtrodrigues** [comment]
It does find `pillow`, but since the resource was defined as `Pillow`, it wasn't an exact match so it didn't update the resource block.

**Comment by Rylan12** [comment]
`bump-python-resources` should now be case insensitive.

Thanks for testing it out and finding these issues!

**Comment by dtrodrigues** [comment]
The lastest version updates the `Pillow` resource block as expected.

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
