### PR TITLE
cpp-httplib 0.10.9 (new formula)

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
It seems odd that
1. `meson` doesn't generate the `cmake` config files if `cmake` is also available
2. `cmake` doesn't generate the `pkg-config` files

This way, you can generate both by calling one of `cmake` or `meson`, and not both. (But you need CMake installed to generate the CMake config files.)

Can you open an issue upstream to see if they can fix this?

**Comment by paperchalice** [comment]
> It seems odd that
> 
> 1. `meson` doesn't generate the `cmake` config files if `cmake` is also available
> 2. `cmake` doesn't generate the `pkg-config` files
> 
> This way, you can generate both by calling one of `cmake` or `meson`, and not both. (But you need CMake installed to generate the CMake config files.)
> 
> Can you open an issue upstream to see if they can fix this?

For `meson`, there is a WIP PR https://github.com/mesonbuild/meson/pull/9978
For `cmake`, there is an issue https://gitlab.kitware.com/cmake/cmake/-/issues/22621

**Comment by carlocab** [comment]
Thanks; let's see what upstream says.

**Comment by paperchalice** [comment]
Because cmake target file varies based on build settings, e.g. build as non header only library, so upstream thinks it is not a good choice.

**Review by carlocab — COMMENTED** [review]
I can see that supporting generating CMake config files through `meson` might be too involved, but what about generating the `pkg-config` file through `cmake`?

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
