### PR TITLE
cheat 2.5.1

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
It's not obeying the prefix:

```
    running install_data
    creating /usr/share/cheat
    error: could not create '/usr/share/cheat': Operation not permitted
    Running setup.py install for cheat: finished with status 'error'
```

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by equal-l2** [comment]
@Moisan Could you trigger the CI? 
I'd like to see why the CI failed, but it's too old and log have deleted already.

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by fxcoudert** [comment]
@equal-l2 the relevant part of the log was copied above:

```
    copying config/cheat -> /etc
    error: could not create '/etc/cheat': Operation not permitted
    Running setup.py install for cheat: finished with status 'error'
```

**Comment by equal-l2** [comment]
@SMillerDev @fxcoudert Thanks!

**Comment by equal-l2** [comment]
Found a relevant pull request on cheat : https://github.com/cheat/cheat/pull/432

**Pull request closed without merging**
