### PR TITLE
ghc: fix postinstall failure on linux

### PR DESCRIPTION
**Pull request by mizunashi-mana**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fix https://github.com/Homebrew/linuxbrew-core/issues/20475

See also https://github.com/NixOS/nixpkgs/pull/85446

### CODE REVIEW

**Comment by jonchang** [comment]
This will need a revision bump.

**Comment by mizunashi-mana** [comment]
Test failure caused by
* Some bottles depend cabal v1 system which is deprecated: agda
* Some bottles does not support GHC 8.10: hledger

**Comment by mizunashi-mana** [comment]
> This will need a revision bump.

I fixed.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
for all builds
```
brew test --retry --verbose agda
brew test --retry --verbose agda
brew install --build-from-source bup
brew install --build-from-source hledger
```

for 10.15:

```
brew install --build-from-source bond
```

**Comment by chenrui333** [comment]
agda test failure is known issue, #58984

**Pull request closed without merging**
