### PR TITLE
tomcat 8.0.39

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Because the Java IDE eclipse use the apache tomcat 8.0 for runtime and the current tomcat version in brew is 8.5.9. And eclipse cannot accept tomcat version 8.5.x. So I make a tomcat@80 for the tomcat version 8.0.x. Please merge it to home-brew. Thank you.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> And eclipse cannot accept tomcat version 8.5.x.

Can you elaborate on this more, please (and what the differences are between 8.5.x and 8.0.x)? Thanks!

**Comment by laizhifei** [comment]
## **Eclipse cannot accept the tomcat 8.5.9.**
new server runtime environment 2017-01-01 07-47-22
edit server runtime environment 2017-01-01 07-49-28

Basically tomcat 8.5.x is the same as tomcat 8.0.x. But tomcat 8.5.x includes JASPIC Spec.
JASPIC is [Java Authentication SPI for Containers (JASPIC)](https://jaspic-spec.java.net).
apache tomcat - which version do i want 2017-01-01 07-54-11

**Comment by laizhifei** [comment]
It's done. Please merge it.

**Comment by MikeMcQuaid** [comment]
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
