### PR TITLE
libgcrypt 1.10.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Can't find a release announcement for this. Might be a prerelease.

**Comment by carlocab** [comment]
There is the `NEWS` file, however: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=blob;f=NEWS;h=c46b3470856e972e4a0892ef7b760ffa8eede09d;hb=refs/heads/master#l6

**Comment by SMillerDev** [comment]
Fedora has updated this, and I don't see a way to ask Upstream about it.

**Comment by carlocab** [comment]
I did see that Fedora updated too. I asked upstream but I'm not really sure what to make of the response: https://dev.gnupg.org/T5691

**Comment by SMillerDev** [comment]
I'd say lets follow Fedora and just ship it. This seems to be a real release but not fully tested.

**Review by carlocab — APPROVED** [review]
It's definitely a real release, I just don't know if it's the one we want. OTOH, it does fix a CVE...

**Pull request closed without merging**
