### PR TITLE
terraform@0.13: terraform 0.13.5 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
follow up PR of #66095

terraform 0.14 is a major release.
https://www.terraform.io/upgrade-guides/0-14.html

> Terraform v0.14 is a major release and so it includes some small changes in behavior that you may need to consider when upgrading. This guide is intended to help with that process.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is terraform 0.13 gonna be supported long term by upstream?

**Comment by NeckBeardPrince** [comment]
Updated to Terraform 14 but most of m

> Is terraform 0.13 gonna be supported long term by upstream?

Hashicorp normally supports the last release for quite sometime. Normally, just bug fixes.

**Comment by chenrui333** [comment]
> Is terraform 0.13 gonna be supported long term by upstream?

It is going to be supported, and we have lots of folks in my company using 0.13 at the moment.

**Comment by chenrui333** [comment]
@SMillerDev I am inclined to do the merge after lunch.

**Comment by SMillerDev** [comment]
> It is going to be supported, and we have lots of folks in my company using 0.13 at the moment.

The latter is not an argument for homebrew-core. But if upstream announced their long term support somewhere I'm okay with merging this.

**Comment by chenrui333** [comment]
so the funny thing, they don't have LTS commitments. But if there is a bug with terraform v0.13 (I don't find it so far), they will have to make the change (it would break tons of builds).

Also, right now the terraform 0.13 is built with go 1.14 as well.

**Comment by SMillerDev** [comment]
> they don't have LTS commitments. But if there is a bug with terraform v0.13 (I don't find it so far), they will have to make the change 

If they don't have an LTS commitment they don't have to. They might, but that's not really meeting the kind of commitment brew needs to ship it.

This sounds like it should be in a tap to me.

**Comment by NeckBeardPrince** [comment]
> > they don't have LTS commitments. But if there is a bug with terraform v0.13 (I don't find it so far), they will have to make the change
> 
> If they don't have an LTS commitment they don't have to. They might, but that's not really meeting the kind of commitment brew needs to ship it.
> 
> This sounds like it should be in a tap to me.

Terraform 0.12.29 and 0.11.14 are currently available https://formulae.brew.sh/formula/terraform#default.
What would be the issue with having 13.5 be a formula?

**Comment by SMillerDev** [comment]
>  What would be the issue with having 13.5 be a formula?

It needs to meet the criteria. It either needs to be supported by upstream, or required in brew. If the other versions aren't meeting those criteria they should be removed too.

**Comment by chenrui333** [comment]
second to Sean's comment, homebrew does have some lifecycle management (for ease to manage the ecosystem changes) to better serve the users.

With that being said, I think we can pass on this formula. :)

**Comment by NeckBeardPrince** [comment]
> second to Sean's comment, homebrew does have some lifecycle management (for ease to manage the ecosystem changes) to better serve the users.
> 
> With that being said, I think we can pass on this formula. :)

Only downside is that I can't use brew to downgrade to the last 0.13 releases. My 3rd party modules don't support 0.14, yet.

**Comment by chenrui333** [comment]
yeah, that is a known inconvenience.

**Comment by SMillerDev** [comment]
> Only downside is that I can't use brew to downgrade to the last 0.13 releases. My 3rd party modules don't support 0.14, yet.

You could do `brew extract` and use that one.

**Pull request closed without merging**
