### PR TITLE
erlang@21 21.3.8.23

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by cho-m** [comment]
This might fail if `otp_build` exists in tarball (it did for other erlang).

I think this is only `erlang` formula I didn't update to new build steps.
It may need some changes from `erlang@22` or `erlang@23`.

**Comment by cho-m** [comment]
See #77644 for reference. Similar fixes are probably needed.
Also, I think fossies mirror is probably dead for this version too (maybe too old)

**Comment by carlocab** [comment]
```
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
```

**Comment by cho-m** [comment]
Maybe:
https://github.com/erlang/otp/pull/2577
https://bugs.erlang.org/browse/ERL-1205

It wasn't ported to v21.

**Comment by carlocab** [comment]
Ah, right. Not sure I understand why it only affects Catalina though.

I'm also coming around a bit to an `autoconf@2.69` formula. It seems like it'd be generally useful (even if not necessarily for Homebrew/core), and it's not as if the formula carries much maintenance burden.

**Comment by carlocab** [comment]
Ok, guess that worked. The only failure is an audit failure for `autoconf@2.69`, but it looks like a transient network error.

**Review by nandahkrishna — APPROVED** [review]
I wonder why this didn't get the `automerge-skip` or `new formula` labels.

**Pull request closed without merging**
