### PR TITLE
xcinfo 1.0.3

### PR DESCRIPTION
**Pull request by trispo**
Updates xcinfo to 1.0.3

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by trispo** [comment]
@SMillerDev Why did bottle publishing fail? What do I need to change?

**Comment by SMillerDev** [comment]
```
 ! [remote rejected]         bump-xcinfo-1.0.3 -> bump-xcinfo-1.0.3 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/publish-commit-bottles.yml` without `workflow` scope)
```

Not sure why, @Homebrew/ops

**Comment by carlocab** [comment]
Yea, our `GITHUB_TOKEN` lacks permissions. I can fix this here when I get back to my computer, but we need to work out a better solution for cases like this.

**Review by carlocab — APPROVED** [review]
Thanks for the PR! For future reference: please try to set up your PR branches so that only one commit modifies one formula, and vice-versa (one formula is modified in one, and only one commit).

**Comment by trispo** [comment]
Great, thanks. I try to avoid multiple commits.

**Pull request merged**
