### PR TITLE
sundials 3.2.0

### PR DESCRIPTION
**Pull request by alexmerkel**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Octave java test has been failing for some time now :(

**Comment by fxcoudert** [comment]
Please do no modify bottle blocks, they are handled automatically when merging.

**Comment by alexmerkel** [comment]
> Please do no modify bottle blocks, they are handled automatically when merging.

Sorry, my bad!

**Comment by alexmerkel** [comment]
> Octave java test has been failing for some time now :(

Yeah, I don't think it has anything to do with the updated sundials version, the same error occurred when I tested it with sundials 3.1.2

**Comment by fxcoudert** [comment]
Thanks @alexmerkel !

**Pull request closed without merging**
