### PR TITLE
spidermonkey 38.2.1, with dependent revision bumps

### PR DESCRIPTION
**Pull request by apjanke**
This PR subsumes #820 (preserving author credit) and adds a revision bump for `couchdb`.

This is not urgent; I'm primarily doing this to test recent `brew pull` updates and practice with GitHub's issue functionality.

Closes #820

### CODE REVIEW

**Comment by apjanke** [comment]
Hmm. `couchdb` is failing at the configure stage. Did something with the headers change in this release of spidermonkey?

```

checking js/jsapi.h usability... no
checking js/jsapi.h presence... no
checking for js/jsapi.h... no
configure: error: Could not find the jsapi header.

Are the Mozilla SpiderMonkey headers installed?
```

Might need a couchdb update in addition to a revision bump.

**Comment by yan12125** [comment]
I'm looking forward to a recent SpiderMonkey version in Homebrew, but upgrading this package is not the correct way. Just like Google's V8, SpiderMonkey constantly changes its API, upgrading it will definitely break other packages. I suggest Homebrew to create another package, something like spidermonkey38.

From https://github.com/Homebrew/homebrew-core/pull/820#issuecomment-217206383:

> Looks like the spidermonkey headers don't get installed properly. Will investigate..

It's because header files are installed as symbolic links by default, and seems Homebrew delete invalid symlinks after the installation. I have a patch for SpiderMonkey 45: https://aur.archlinux.org/cgit/aur.git/tree/install-copy-files.patch?h=js45. I guess it works for version 38, too.

> Might need a couchdb update in addition to a revision bump.

From CouchDB's configure.ac: [1]
```
AC_CHECK_LIB([mozjs185], [JS_NewContext], [JS_LIB_BASE=mozjs185], [
    AC_CHECK_LIB([mozjs185-1.0], [JS_NewContext], [JS_LIB_BASE=mozjs185-1.0], [
        AC_CHECK_LIB([mozjs], [JS_NewContext], [JS_LIB_BASE=mozjs], [
            AC_CHECK_LIB([js], [JS_NewContext], [JS_LIB_BASE=js], [
                AC_CHECK_LIB([js3250], [JS_NewContext], [JS_LIB_BASE=js3250], [
                    AC_CHECK_LIB([js32], [JS_NewContext], [JS_LIB_BASE=js32], [
                        AC_MSG_ERROR([Could not find the js library.

Is the Mozilla SpiderMonkey library installed?])
                    ])
                ])
            ])
        ])
    ])
])
```
Seems CouchDB 1.6.1 claims to be compatible with SpiderMonkey 1.8.5 and 32.5. It might not be a good idea to build it against SpiderMonkey 38, as lots of APIs are changed and I guess many patches are needed.
[1] https://git1-us-west.apache.org/repos/asf?p=couchdb.git;a=blob;f=configure.ac;h=103f02999f8c884e6b22348f269572be4dd92140;hb=31dc5960d418e17eb454563330338abfd5fbbc23#l244

**Comment by apjanke** [comment]
Closing this out in view of the header issue and the major-version compatibility problem. Like yan12125 says, this upgrade might be a no-go and need to be handled with a separate versioned formula.

**Comment by yan12125** [comment]
Just sent a pull request to https://github.com/Homebrew/homebrew-versions/pull/1341.

**Pull request closed without merging**
