### PR TITLE
direvent 5.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>license ref</summary>

```
/* direvent - directory content watcher daemon
   Copyright (C) 2012-2021 Sergey Poznyakoff

   GNU direvent is free software; you can redistribute it and/or modify it
   under the terms of the GNU General Public License as published by the
   Free Software Foundation; either version 3 of the License, or (at your
   option) any later version.

   GNU direvent is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License along
   with direvent. If not, see <http://www.gnu.org/licenses/>. */
```


</details>

**Comment by carlocab** [comment]
Can you report the test failures upstream?

**Comment by chenrui333** [comment]
yeah, I did already.

**Comment by chenrui333** [comment]
There is still no response from upstream on the build issue. :(

**Comment by carlocab** [comment]
Can you link to your upstream report?

**Comment by chenrui333** [comment]
I did shoot email, I did not find any place to submit the ticket.

**Comment by chenrui333** [comment]
I think I was using the wrong email earlier. Retry this time.

**Comment by chenrui333** [comment]
#119542

**Pull request closed without merging**
