### PR TITLE
postgis: bump revision

### PR DESCRIPTION
**Pull request by ruurd**
- [X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ruurd** [comment]
==> Installing postgis dependency: hdf5
==> Pouring hdf5-1.12.0_1.catalina.bottle.tar.gz
Warning: hdf5 dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/hdf5/1.12.0_1: 268 files, 16.3MB
==> Installing postgis dependency: netcdf
==> Pouring netcdf-4.7.4_1.catalina.bottle.tar.gz
Warning: netcdf dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/netcdf/4.7.4_1: 90 files, 6.2MB
==> Installing postgis dependency: gdal
==> Pouring gdal-3.1.3_3.catalina.bottle.tar.gz
Warning: gdal dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/gdal/3.1.3_3: 270 files, 56.2MB
==> Installing postgis dependency: protobuf-c

So hdf5 and netcdf and gdal also need to be bumped?

**Comment by nertzy** [comment]
I would love to get this merged, but it looks like the 10.15 test is stuck.

**Comment by ruurd** [comment]
Hah yes. Now what? Retry this?

**Comment by ruurd** [comment]
OK I think this is effed up.

**Comment by fxcoudert** [comment]
We have had CI troubles, now it should be back up and working.
Could you please rebase and force-push a single commit? Empty commits are confusing the CI.

**Comment by ruurd** [comment]
OK this is going nowhere from what I can see...

**Comment by ruurd** [comment]
OK abandoned this - see https://github.com/Homebrew/homebrew-core/pull/62995 please. I redid the changes in postsgis and added a license as per the postgis homepage.

**Comment by ruurd** [comment]
> We have had CI troubles, now it should be back up and working.
> Could you please rebase and force-push a single commit? Empty commits are confusing the CI.

Reddi it. I was afraid I would have messed up homebrew-core with that amount of changes...

**Pull request closed without merging**
