### PR TITLE
tinyxml: deprecate

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Waiting on https://github.com/ros/urdfdom/pull/99 for urdfdom

### CODE REVIEW

**Comment by cho-m** [comment]
Do we know status of https://github.com/ros/urdfdom/pull/99? Last comment there was from over 3 years ago.

**Comment by SMillerDev** [comment]
Yeah, that doesn't seem active anymore. I wonder if Homebrew could sponsor someone to work on that since the formula is too popular to deprecate I think.

**Comment by SMillerDev** [comment]
Made https://github.com/ros/urdfdom/pull/178 to continue that work. Another Homebrew maintainer @scpeters seems to work on some parts of urdfdom so I'm hoping for some assistance there.

**Comment by scpeters** [comment]
> Made [ros/urdfdom#178](https://github.com/ros/urdfdom/pull/178) to continue that work. Another Homebrew maintainer @scpeters seems to work on some parts of urdfdom so I'm hoping for some assistance there.

sure thing I'll take a look

**Comment by scpeters** [comment]
the `urdfdom` formula has migrated to use `tinyxml2`, so this could be revisited

**Comment by scpeters** [comment]
it seems like the other formulae are picking up `tinyxml` anyway because it's installed due to being modified in this PR? Should we try to split out the commits that modify the tinyxml dependents into a separate PR?

**Comment by scpeters** [comment]
> Yeah, I think that would be best. Do you want to make a PR with the tinyxml > tinyxml2 changes @scpeters ? I'm not near a PC now.

I've split out biosig and rarian in https://github.com/Homebrew/homebrew-core/pull/159362

**Comment by scpeters** [comment]
> > Yeah, I think that would be best. Do you want to make a PR with the tinyxml > tinyxml2 changes @scpeters ? I'm not near a PC now.
> 
> I've split out biosig and rarian in #159362

rarian was failing to build, so I just made the changes for biosig in #159362

**Comment by scpeters** [comment]
I've split out the openclonk deprecation into https://github.com/Homebrew/homebrew-core/pull/159373

**Comment by scpeters** [comment]
I've glanced at the `rarian` source code, and the `ENABLE_SK_COMPAT` option appears to use a vendored version of `tinyxml`, but it still fails while searching for `tinyxml.h`, so some further investigation is needed. I don't know autotools well enough to debug this further, but it may be a path to removing the `tinyxml` dependency.

**Comment by scpeters** [comment]
> I've glanced at the `rarian` source code, and the `ENABLE_SK_COMPAT` option appears to use a vendored version of `tinyxml`, but it still fails while searching for `tinyxml.h`, so some further investigation is needed. I don't know autotools well enough to debug this further, but it may be a path to removing the `tinyxml` dependency.
> 
> https://github.com/0mp/rarian/blob/master/util/Makefile.am#L39-L49

actually that's not the canonical repo for rarian. It looks like tinyxml was vendored as of [0.8.2](https://gitlab.freedesktop.org/rarian/rarian/-/tree/0.8.2/util?ref_type=tags), but it was removed in [0.8.3](https://gitlab.freedesktop.org/rarian/rarian/-/tree/0.8.3/util?ref_type=tags)

**Comment by SMillerDev** [comment]
Created https://gitlab.freedesktop.org/rarian/rarian/-/issues/9 for Rarian support.

**Pull request closed without merging**
