### PR TITLE
nutcracker 0.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- use pkgshare
- match version in the test

### CODE REVIEW

**Comment by DomT4** [comment]
Identical comment to https://github.com/Homebrew/homebrew-core/pull/1732#issuecomment-223862006 😄

**Comment by ilovezfs** [comment]
I've removed the symlink because I think that's a bad idea.

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
👍. Nice spot that some audit checks weren't looking at the `+`-style syntax as well, by the way! Always the little things that creep through testing, however extensive.

**Comment by ilovezfs** [comment]
Thanks. I was pretty surprised, actually.

**Pull request closed without merging**
