### PR TITLE
libvpx 1.15.0

### PR DESCRIPTION
**Pull request by khipp**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@khipp it needs rev bumps for the dependant formulae.

**Comment by khipp** [comment]
Thanks for the help, @carlocab. Unfortunately, it seems like the build fails without the `--disable-neon_i8mm` flag:

```
Last 15 lines from /Users/klaush/Library/Logs/Homebrew/libvpx/02.make:
  417 |   int32x4_t sum1 = vusdotq_lane_s32(vdupq_n_s32(0), samples1_lo, filters, 0);
      |                    ^
/Library/Developer/CommandLineTools/usr/lib/clang/16/include/arm_neon.h:35960:15: note: expanded from macro 'vusdotq_lane_s32'
 35960 |   __ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
       |               ^
../vpx_dsp/arm/vpx_convolve8_neon_i8mm.c:418:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_v' that is compiled without support for 'i8mm'
  418 |   sum1 = vusdotq_lane_s32(sum1, samples1_hi, filters, 1);
      |          ^
/Library/Developer/CommandLineTools/usr/lib/clang/16/include/arm_neon.h:35960:15: note: expanded from macro 'vusdotq_lane_s32'
 35960 |   __ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
       |               ^
15 errors generated.
make[1]: *** [vpx_dsp/arm/vpx_convolve8_neon_i8mm.c.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [.DEFAULT] Error 2
```

**Comment by carlocab** [comment]
> Thanks for the help, @carlocab. Unfortunately, it seems like the build fails without the `--disable-neon_i8mm` flag:

That's because you removed my fix for it. You need to add `ENV.runtime_cpu_detection` on both ARM and Intel or else `brew` will mess with `-march` flags which causes the build to fail.

**Comment by carlocab** [comment]
Not sure what the need to replace the changes I made from 2851a147c84eb482e306399b3806482f7e6f4351 was?

**Comment by khipp** [comment]
I'm sorry for this mess. I didn't realize that someone had already pushed to my branch before I continued working on it locally.

**Comment by carlocab** [comment]
Ah, cool, that's fine! I should've warned you.

**Comment by carlocab** [comment]
You also have too many revision bumps though -- we should start only with the ones that fail `brew linkage` (because that will usually also fix the `brew test` failures that aren't accompanied by a `brew linkage` failure).

Going to push to your branch now, FYI!

**Comment by khipp** [comment]
Thank you! I will be more careful next time.

**Review by carlocab — APPROVED** [review]
I'll just open follow-up PRs for `handbrake` and `qt@5` since they're showing linkage failures only on Linux.

**Pull request merged**
