### PR TITLE
youtube-dl 2016.10.07

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks for updating this @neutric :movie_camera:

**Comment by neutric** [comment]
@ilovezfs: You're very welcome. :)

**Pull request closed without merging**
