### PR TITLE
Update rethinkdb 2.3.6

### PR DESCRIPTION
**Pull request by kkdd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
It looks like 2.3.5 is still the current version on both GitHub (https://github.com/rethinkdb/rethinkdb/releases/latest) and https://github.com/rethinkdb/rethinkdb/archive/ so we'll need to wait until 2.3.6 is designated latest, not just posted as a tag. Thanks for the PR nonetheless.

**Comment by kkdd** [comment]
v2.3.6 is here: https://github.com/rethinkdb/rethinkdb/releases/tag/v2.3.6
 (https://github.com/rethinkdb/rethinkdb/archive/v2.3.6.tar.gz)

**Comment by AtnNn** [comment]
The github release page has been updated with the 2.3.6 release.

**Comment by ilovezfs** [comment]
@AtnNn thanks for the heads up!

**Comment by ilovezfs** [comment]
Thanks @kkdd!

**Pull request closed without merging**
