### PR TITLE
seal 4.1.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at CMakeLists.txt:154 (message):
    Microsoft GSL: not found
```

**Comment by chenrui333** [comment]
need a rebase for the PR after #120029 merge

**Comment by p-linnane** [comment]
4.1.1 is out

**Comment by chenrui333** [comment]
```
  CMake Warning at CMakeLists.txt:226 (find_package):
    Could not find a configuration file for package "HEXL" that is compatible
    with requested version "1.2.4".
  
    The following configuration files were considered but not accepted:
  
      /home/linuxbrew/.linuxbrew/Cellar/seal/4.1.1/lib/cmake/hexl-1.2.5/HEXLConfig.cmake, version: 1.2.5
```

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
