### PR TITLE
nushell 0.64.0

### PR DESCRIPTION
**Pull request by hustcer**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by hustcer** [comment]
Need https://github.com/Homebrew/homebrew-core/pull/98823 to be merged

**Comment by fellnerse** [comment]
@hustcer  Do you when this probably will be merged?

**Comment by hustcer** [comment]
> @hustcer Do you when this probably will be merged?

Depends on when rust v1.60 will be available in homebrew, ref: https://github.com/Homebrew/homebrew-core/pull/98823

**Comment by hustcer** [comment]
No, there is no need to update it, 0.63.1 is just a tag , not a public release

**Comment by bennetfabian** [comment]
> No, there is no need to update it, 0.63.1 is just a tag , not a public release

Okay, just wanted to check cause there are some package managers on other platforms that do handle it as if it was a public release. What I mean by that is that they added 0.63.0 as well as 0.63.1 to their package manager repositories.

**Comment by hustcer** [comment]
Any update on this issue?

**Comment by hustcer** [comment]
I think it's ready to merge now

**Comment by hustcer** [comment]
@chenrui333 @cho-m Anything else should I do?

**Review by branchv — DISMISSED** [review]
@hustcer sorry for the long delay!

**Comment by branchvincent** [comment]
```
Error: No artifact with the name `bottles` was found!
```

Not sure what happened there, but let's try another run

**Review by branchv — APPROVED** [review]

**Pull request closed without merging**
