### PR TITLE
wine 2.2 (devel)

### PR DESCRIPTION
**Pull request by nthansen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Working updated version of Wine formula.
- Separated patches for stable/devel
- Removed unnecessary patch https://bugs.winehq.org/show_bug.cgi?id=14939 for devel 
- Updated devel patch for https://bugs.winehq.org/show_bug.cgi?id=34166 (necessary for 2.3)

### CODE REVIEW

**Comment by nthansen** [comment]
Saw there was another one in the pull request but the pr hasn't been updated in 8 days and it only updated the devel version.

**Comment by adamzap** [comment]
wine 2.3 (devel) is out now: https://www.winehq.org/news/2017030301

Thanks for this branch. I used it to install 2.2!

**Comment by fxcoudert** [comment]
We have recently merged a bit refactoring of the `wine` formula: all universal dependencies are now included as part of the formula. Could you rebase this PR to the current formula? And possibly update it for 2.3, checking that the patches do not need to be adapted again.

**Comment by nthansen** [comment]
Sounds good, I'll work on that in a few.

**Comment by nthansen** [comment]
Alright, rebased my repo and added a commit to update wine devel to 2.3.

**Comment by fxcoudert** [comment]
☹️

```
winebuild: ld failed with status 255
winegcc: ../../tools/winebuild/winebuild failed
make[1]: *** [api-ms-win-core-synch-l1-1-0.dll.so] Error 2
make: *** [dlls/api-ms-win-core-synch-l1-1-0] Error 2
```

**Comment by nthansen** [comment]
Hmm so only for Yosemite. I'll dig around and see what I can come up with.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
If the tests pass for 2.2, I'll merge that and we can open another PR for 2.3 (getting that working).

**Comment by fxcoudert** [comment]
Thanks @nthansen! We'll be happy to consider a PR for version 2.3 once the Yosemite issue is solved :)

**Pull request closed without merging**
