### PR TITLE
openjdk 16.0.2

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
Dependent tests are being skipped on ARM because of the audit failure. Merging #81612 now so that those dependent tests can happen. You'll need to rebase.

**Comment by carlocab** [comment]
Merged; please rebase so that the dependent tests run.

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/81917 fixes nifi-registry, I send an email to the FastBit maintainers since the source is now only accessible from within Berkley Labs.

**Comment by SMillerDev** [comment]
These failures all seem unrelated to the version bump:
```
brew install --build-from-source link-grammar
brew install --build-from-source semgrep
brew install --build-from-source subversion

brew install --build-from-source pdfpc
brew test --retry --verbose opensearch
brew fetch --build-from-source --retry acme
```

The link-grammar error is the only error across macOS versions, but that seems to be due to a recent brew change. Not OpenJDK.
```
Making install in python
  CXX      _clinkgrammar_la-lg_python_wrap.lo
  CXXLD    _clinkgrammar.la
 ../.././install-sh -c -d '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar'
 ../.././install-sh -c -d '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
 ../.././install-sh -c -d '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar'
 /usr/bin/install -c -m 644 ./linkgrammar.pth '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
install: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar.pth: Operation not permitted
make[3]: *** [install-pkgpypathPYTHON] Error 71
make[3]: *** Waiting for unfinished jobs....
mkdir: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar: Operation not permitted
make[3]: *** [install-pkgpyexecLTLIBRARIES] Error 1
mkdir: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar: Operation not permitted
make[3]: *** [install-pkgpythonPYTHON] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Review by dawidd6 — APPROVED** [review]

**Comment by chenrui333** [comment]
> These failures all seem unrelated to the version bump:
> 
> ```
> brew install --build-from-source link-grammar
> brew install --build-from-source semgrep
> brew install --build-from-source subversion
> 
> brew install --build-from-source pdfpc
> brew test --retry --verbose opensearch
> brew fetch --build-from-source --retry acme
> ```
> 
> The link-grammar error is the only error across macOS versions, but that seems to be due to a recent brew change. Not OpenJDK.
> 
> ```
> Making install in python
>   CXX      _clinkgrammar_la-lg_python_wrap.lo
>   CXXLD    _clinkgrammar.la
>  ../.././install-sh -c -d '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar'
>  ../.././install-sh -c -d '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
>  ../.././install-sh -c -d '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar'
>  /usr/bin/install -c -m 644 ./linkgrammar.pth '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
> install: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar.pth: Operation not permitted
> make[3]: *** [install-pkgpypathPYTHON] Error 71
> make[3]: *** Waiting for unfinished jobs....
> mkdir: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar: Operation not permitted
> make[3]: *** [install-pkgpyexecLTLIBRARIES] Error 1
> mkdir: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar: Operation not permitted
> make[3]: *** [install-pkgpythonPYTHON] Error 1
> make[2]: *** [install-am] Error 2
> make[1]: *** [install-recursive] Error 1
> make: *** [install-recursive] Error 1
> ```

seen the same issue in the latest [link-grammar 5.10.0](https://github.com/Homebrew/homebrew-core/pull/84708) release as well.

Any solution idea?

**Pull request closed without merging**
