### PR TITLE
zstd 1.5.1

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by owine** [comment]
Release appears to have been pulled.

**Comment by SMillerDev** [comment]
This should be re-ran with long timeout once we have a runner available

**Comment by carlocab** [comment]
Linux failures:

jolie:
```
[32m==>[0m [1mTesting jolie[0m
[34m==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/jolie/1.10.5/bin/jolie /tmp/jolie-test-20211224-193504-yys0nk/test.ol[0m
Picked up _JAVA_OPTIONS: -Duser.home=/github/home/.cache/Homebrew/java_cache -Djava.io.tmpdir=/tmp
jolie.lang.parse.module.ModuleException: /tmp/jolie-test-20211224-193504-yys0nk/test.ol:1: error: jolie.lang.parse.module.exceptions.ModuleNotFoundException: Module "[Console]" not found from lookup path [Module "[Console]" not found from lookup path [Console.ol, /tmp/jolie-test-20211224-193504-yys0nk/lib/Console.jap, /home/linuxbrew/.linuxbrew/Cellar/jolie/1.10.5/libexec/packages/Console.ol, ./packages/Console.ol]]
```

lc0:
```
[34m==>[0m [1mbrew test --re
[31m==>[0m [1m[31mFAILED
##[group]Full test lc0 output
[32m==>[0m [1mTesting lc0[
[34m==>[0m [1mlc0 benchmark 
Illegal instruction (core dumped)
```

mrbayes:
```
==>[0m [1mTesting mrbayes[0m
==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/mrbayes/3.2.7_2/bin/mb primates.nex[0m
==>[0m [1mTesting mrbayes (again)[0m
==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/mrbayes/3.2.7_2/bin/mb primates.nex[0m
Error:[0m mrbayes: failed
eption occurred within a child process:
dError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/mrbayes/3.2.7_2/bin/mb primates.nex
```

I've seen `mrbayes` for sure in other PRs. `jolie` looks unrelated.

fauna-shell also failed, but that's pre-existing -- the test just stalls indefinitely until it's manually killed (which I did the other day).

**Comment by iMichka** [comment]
I have a patch for `lc0`: #92028 (this is a weird one though).

`jolie` and `mrbayes` are known, it's on my todo. But if someone wants to have a look; feel free to beat me to it.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
