### PR TITLE
GHC 8.8.1 patched for Alex requirement in configure

### PR DESCRIPTION
**Pull request by lukel97**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Based off of #43464

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
In file included from compiler/parser/cutils.c:6:0: error: 

In file included from includes/Rts.h:191:0: error: 

includes/rts/storage/ClosureMacros.h:211:25: error:
     error: use of undeclared identifier 'TAG_MASK'
        return (StgWord)p & TAG_MASK;
                            ^
    |
211 |     return (StgWord)p & TAG_MASK;
    |                         ^

includes/rts/storage/ClosureMacros.h:217:40: error:
     error: use of undeclared identifier 'TAG_MASK'
        return (StgClosure*)((StgWord)p & ~TAG_MASK);
                                           ^
    |
217 |     return (StgClosure*)((StgWord)p & ~TAG_MASK);
    |                                        ^

includes/rts/storage/ClosureMacros.h:223:46: error:
     error: use of undeclared identifier 'TAG_MASK'
        return (const StgClosure*)((StgWord)p & ~TAG_MASK);
                                                 ^
    |
223 |     return (const StgClosure*)((StgWord)p & ~TAG_MASK);
    |                                              ^
3 errors generated.
`clang' failed in phase `C Compiler'. (Exit code: 1)
```

**Comment by fishtreesugar** [comment]
related upstream issue: https://gitlab.haskell.org/ghc/ghc/issues/17146

cc @mpickering

**Comment by bubba** [comment]
@fxcoudert fixed now by building with ghc-8.6.5

**Comment by fxcoudert** [comment]
Thanks @bubba, merging

**Pull request closed without merging**
