### PR TITLE
imapsync 2.140

### PR DESCRIPTION
**Pull request by barchard**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @barchard. Helped you out with the resources here.

**Comment by barchard** [comment]
Thanks!

**Comment by carlocab** [comment]
...or not. Updating the resources seems to have broken something. Let me look into it.

**Review by SMillerDev — APPROVED** [review]
Thanks @barchard ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by gilleslamiral** [comment]
Thanks!
If you have a script to generate this file or make it release number independent, I'm in to put it in the Makefile and provide a
`make brew`

**Comment by barchard** [comment]
@gilleslamiral I followed:

> brew bump-formula-pr

Specifically, as described here:

https://github.com/Homebrew/discussions/discussions/1876

**Comment by carlocab** [comment]
Thanks, @gilleslamiral. Do you mean you want to automate updating the Homebrew `imapsync` formula in your `Makefile` with a `make brew` target?

**Comment by gilleslamiral** [comment]
If it can help imapsync brew users, I'm in

**Pull request closed without merging**
