### PR TITLE
openssl@3: add HTTP mirror

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is needed for use as a dependency of `curl`. See #133144.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by Bo98** [comment]
There's should probably have the `/old/` URLs too if it's going to be used in something as important as curl.

**Comment by carlocab** [comment]
I tried the `/old/` URLs with 3.1.0 and they didn't seem to work though.

**Comment by Bo98** [comment]
Works fine for me? https://www.openssl.org/source/old/3.1/openssl-3.1.0.tar.gz

**Comment by carlocab** [comment]
Hmmm, odd. Not sure why that didn't work for me earlier. #133436

**Pull request merged**
