### PR TITLE
xcodegen 2.18.0

### PR DESCRIPTION
**Pull request by yonaskolb**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @yonaskolb

**Comment by SMillerDev** [comment]
FYI @yonaskolb : for next time, please use the same commit format as the PR title has now. It saves maintainers from manually merging and rewording it. Or even easier, use `brew bump-formula-pr`.

**Comment by chenrui333** [comment]
Second to @SMillerDev's comment. Thanks for the PR!!

**Comment by yonaskolb** [comment]
@SMillerDev Will do. I was having issues ruby issues with `brew bump-formula-pr`, so just created the PR via github

**Pull request closed without merging**
