### PR TITLE
livekit-cli 1.3.3

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`    Minitest::Assertion: Expected /livekit\-cli\ version\ 1\.3\.3/ to match "livekit-cli version 1.3.2\n".`

**Comment by chenrui333** [comment]
https://github.com/livekit/livekit-cli/releases

**Comment by chenrui333** [comment]
- https://github.com/livekit/livekit-cli/issues/263

**Comment by Sean-Der** [comment]
@chenrui333 can you run again please? I published the release, thank you!

**Comment by chenrui333** [comment]
@Sean-Der thanks for the quick turnaround, can you also fix the version number as well :)

**Comment by chenrui333** [comment]
for now, I am gonna create a PR to have this PR moving forward.

it would be also good to refactor the config to have the version info overridable.

**Comment by chenrui333** [comment]
rolling forward with 1.6.4 is a better route. :)

**Comment by Sean-Der** [comment]
@chenrui333 rolled forward. 1.3.4 is available now!

**Comment by krehel** [comment]
#157270

**Pull request closed without merging**
