### PR TITLE
ppsspp: drop formula in favour of ppsspp cask

### PR DESCRIPTION
**Pull request by vit9696**
REF: https://github.com/Homebrew/homebrew-cask/pull/113569

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
The formula has a reasonable number of downloads (~400 monthly installs) and few complaints. I'm in favour of keeping it to allow users the choice as to which to install. Doing `brew install ppsspp` will warn users of the existence of a cask of the same name anyway.

**Comment by vit9696** [comment]
The users had to install `ppsspp` formula for two reasons:

- There was no cask despite the thing being an app, not a cli tool.
- There were no official releases on the ppsspp end.

Also, I believe that the current formula violates brew rules: https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app.

**Comment by vit9696** [comment]
> Even if what you say is true, surely it would be better to wait and see what the analytics data looks like regarding which version users prefer to install before forcing a choice upon them, is it not?

That sounds like a good idea. Maybe keep this PR open for a couple of months and then decide? Fine by me.

**Comment by carlocab** [comment]
The stale bot is likely to close this before that happens, so why don't we just revisit this in a new PR in a couple of months?

**Comment by carlocab** [comment]
Since we agreed to revisit this after a few months:

I've come to the conclusion that we **shouldn't** drop the formula in favour of the cask. The first reason is that the formula still has many more downloads. In the past 30 days:

Index | Name (with options)                                                                                                         | Count |  Percent
-----:|-----------------------------------------------------------------------------------------------------------------------------|------:|--------:
1     | ppsspp                                                                                                                      |   725 |   99.72%
2     | ppsspp --HEAD                                                                                                               |     2 |    0.28%
Total |                                                                                                                             |   727 |  100.00%

vs the cask:

Index | Name (with options)                                                                                                         | Count |  Percent
-----:|-----------------------------------------------------------------------------------------------------------------------------|------:|--------:
1     | ppsspp                                                                                                                      |    89 |  100.00%

The second reason is that deleting the formula means our Linux users won't be able to install this, as casks are not supported on Linux.

**Pull request closed without merging**
