### PR TITLE
fluent-bit 1.4.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
Undefined symbols for architecture x86_64:
  "_flb_thread_key", referenced from:
      _main in fluent-bit.c.o
      _flb_engine_start in libfluent-bit.a(flb_engine.c.o)
      _flb_input_collector_fd in libfluent-bit.a(flb_input.c.o)
      _flb_engine_dispatch_retry in libfluent-bit.a(flb_engine_dispatch.c.o)
      _flb_engine_dispatch in libfluent-bit.a(flb_engine_dispatch.c.o)
      _flb_proxy_cb_flush in libfluent-bit.a(flb_plugin_proxy.c.o)
      _create_conn in libfluent-bit.a(flb_upstream.c.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by chenrui333** [comment]
Will work on this tomorrow locally before reopening this PR.

**Comment by lht** [comment]
Adding flag `-fno-common` can work around the issue. It's also included in upstream by https://github.com/fluent/fluent-bit/pull/2303

```
@@ -21,7 +21,7 @@ class FluentBit < Formula

   def install
     # Work around Xcode 11 clang bug
-    ENV.append_to_cflags "-fno-stack-check" if DevelopmentTools.clang_build_version >= 1010
+    ENV.append_to_cflags "-fno-stack-check -fno-common" if DevelopmentTools.clang_build_version >= 1010

     # Per https://luajit.org/install.html: If MACOSX_DEPLOYMENT_TARGET
     # is not set then it's forced to 10.4, which breaks compile on Mojave.
```

**Comment by chenrui333** [comment]
@lht thanks for the direction, doing that now.

**Comment by chenrui333** [comment]
tested our locally (works for me), rebased to master.

**Comment by chenrui333** [comment]
only failed on 10.13
```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -Wall -D__FILENAME__='"$(subst /tmp/fluent-bit-20200703-31345-1pdolhg/fluent-bit-1.4.6/,,$(abspath $<))"' -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names  -o ../lib/libfluent-bit.dylib -install_name /tmp/fluent-bit-20200703-31345-1pdolhg/fluent-bit-1.4.6/lib/libfluent-bit.dylib CMakeFiles/fluent-bit-shared.dir/flb_mp.c.o CMakeFiles/fluent-bit-shared.dir/flb_kv.c.o CMakeFiles/fluent-bit-shared.dir/flb_api.c.o CMakeFiles/fluent-bit-shared.dir/flb_lib.c.o CMakeFiles/fluent-bit-shared.dir/flb_log.c.o CMakeFiles/fluent-bit-shared.dir/flb_env.c.o CMakeFiles/fluent-bit-shared.dir/flb_uri.c.o CMakeFiles/fluent-bit-shared.dir/flb_hash.c.o CMakeFiles/fluent-bit-shared.dir/flb_pack.c.o CMakeFiles/fluent-bit-shared.dir/flb_pack_gelf.c.o CMakeFiles/fluent-bit-shared.dir/flb_sds.c.o CMakeFiles/fluent-bit-shared.dir/flb_pipe.c.o CMakeFiles/fluent-bit-shared.dir/flb_meta.c.o CMakeFiles/fluent-bit-shared.dir/flb_kernel.c.o CMakeFiles/fluent-bit-shared.dir/flb_input.c.o CMakeFiles/fluent-bit-shared.dir/flb_input_chunk.c.o CMakeFiles/fluent-bit-shared.dir/flb_filter.c.o CMakeFiles/fluent-bit-shared.dir/flb_output.c.o CMakeFiles/fluent-bit-shared.dir/flb_config.c.o CMakeFiles/fluent-bit-shared.dir/flb_config_map.c.o CMakeFiles/fluent-bit-shared.dir/flb_network.c.o CMakeFiles/fluent-bit-shared.dir/flb_utils.c.o CMakeFiles/fluent-bit-shared.dir/flb_slist.c.o CMakeFiles/fluent-bit-shared.dir/flb_engine.c.o CMakeFiles/fluent-bit-shared.dir/flb_engine_dispatch.c.o CMakeFiles/fluent-bit-shared.dir/flb_task.c.o CMakeFiles/fluent-bit-shared.dir/flb_unescape.c.o CMakeFiles/fluent-bit-shared.dir/flb_scheduler.c.o CMakeFiles/fluent-bit-shared.dir/flb_io.c.o CMakeFiles/fluent-bit-shared.dir/flb_storage.c.o CMakeFiles/fluent-bit-shared.dir/flb_upstream.c.o CMakeFiles/fluent-bit-shared.dir/flb_upstream_ha.c.o CMakeFiles/fluent-bit-shared.dir/flb_upstream_node.c.o CMakeFiles/fluent-bit-shared.dir/flb_router.c.o CMakeFiles/fluent-bit-shared.dir/flb_worker.c.o CMakeFiles/fluent-bit-shared.dir/flb_thread.c.o CMakeFiles/fluent-bit-shared.dir/flb_time.c.o CMakeFiles/fluent-bit-shared.dir/flb_sosreport.c.o CMakeFiles/fluent-bit-shared.dir/flb_sha512.c.o CMakeFiles/fluent-bit-shared.dir/flb_plugin.c.o CMakeFiles/fluent-bit-shared.dir/flb_gzip.c.o CMakeFiles/fluent-bit-shared.dir/flb_parser.c.o CMakeFiles/fluent-bit-shared.dir/flb_parser_regex.c.o CMakeFiles/fluent-bit-shared.dir/flb_parser_json.c.o CMakeFiles/fluent-bit-shared.dir/flb_parser_decoder.c.o CMakeFiles/fluent-bit-shared.dir/flb_parser_ltsv.c.o CMakeFiles/fluent-bit-shared.dir/flb_parser_logfmt.c.o CMakeFiles/fluent-bit-shared.dir/flb_io_tls.c.o CMakeFiles/fluent-bit-shared.dir/flb_oauth2.c.o CMakeFiles/fluent-bit-shared.dir/flb_http_client.c.o CMakeFiles/fluent-bit-shared.dir/flb_plugin_proxy.c.o CMakeFiles/fluent-bit-shared.dir/flb_signv4.c.o CMakeFiles/fluent-bit-shared.dir/flb_luajit.c.o CMakeFiles/fluent-bit-shared.dir/flb_regex.c.o CMakeFiles/fluent-bit-shared.dir/flb_sqldb.c.o CMakeFiles/fluent-bit-shared.dir/flb_record_accessor.c.o CMakeFiles/fluent-bit-shared.dir/flb_ra_key.c.o  -lm ../library/libmk_core.a ../library/libjsmn.a ../library/libmsgpackc.a ../library/libmpack-static.a ../library/libchunkio-static.a ../library/libminiz.a ../library/libflb-plugin-in_emitter.a ../library/libflb-plugin-in_tail.a ../library/libflb-plugin-in_dummy.a ../library/libflb-plugin-in_head.a ../library/libflb-plugin-in_health.a ../library/libflb-plugin-in_collectd.a ../library/libflb-plugin-in_statsd.a ../library/libflb-plugin-in_storage_backlog.a ../library/libflb-plugin-in_stream_processor.a ../library/libflb-plugin-in_serial.a ../library/libflb-plugin-in_stdin.a ../library/libflb-plugin-in_syslog.a ../library/libflb-plugin-in_exec.a ../library/libflb-plugin-in_tcp.a ../library/libflb-plugin-in_mqtt.a ../library/libflb-plugin-in_lib.a ../library/libflb-plugin-in_forward.a ../library/libflb-plugin-in_random.a ../library/libflb-plugin-out_azure.a ../library/libflb-plugin-out_bigquery.a ../library/libflb-plugin-out_counter.a ../library/libflb-plugin-out_datadog.a ../library/libflb-plugin-out_es.a ../library/libflb-plugin-out_exit.a ../library/libflb-plugin-out_file.a ../library/libflb-plugin-out_forward.a ../library/libflb-plugin-out_http.a ../library/libflb-plugin-out_influxdb.a ../library/libflb-plugin-out_kafka_rest.a ../library/libflb-plugin-out_nats.a ../library/libflb-plugin-out_null.a ../library/libflb-plugin-out_plot.a ../library/libflb-plugin-out_slack.a ../library/libflb-plugin-out_splunk.a ../library/libflb-plugin-out_stackdriver.a ../library/libflb-plugin-out_stdout.a ../library/libflb-plugin-out_tcp.a ../library/libflb-plugin-out_td.a ../library/libflb-plugin-out_lib.a ../library/libflb-plugin-out_flowcounter.a ../library/libflb-plugin-out_gelf.a ../library/libflb-plugin-filter_aws.a ../library/libflb-plugin-filter_expect.a ../library/libflb-plugin-filter_record_modifier.a ../library/libflb-plugin-filter_rewrite_tag.a ../library/libflb-plugin-filter_throttle.a ../library/libflb-plugin-filter_grep.a ../library/libflb-plugin-filter_kubernetes.a ../library/libflb-plugin-filter_parser.a ../library/libflb-plugin-filter_nest.a ../library/libflb-plugin-filter_modify.a ../library/libflb-plugin-filter_lua.a ../library/libflb-plugin-filter_stdout.a ../library/libflb-plugin-proxy-go.a ../library/libmbedtls.a ../library/libco.a ../library/librbtree.a ../lib/libonigmo.a ../lib/libluajit.a ../library/libsqlite3.a ../library/libtutf8e.a ../library/libflb-ra-parser.a ../library/libflb-sp.a -lpthread ../library/libfluent-bit.a ../library/libflb-plugin-in_emitter.a ../library/libflb-plugin-in_tail.a ../library/libflb-plugin-in_dummy.a ../library/libflb-plugin-in_head.a ../library/libflb-plugin-in_health.a ../library/libflb-plugin-in_collectd.a ../library/libflb-plugin-in_statsd.a ../library/libflb-plugin-in_storage_backlog.a ../library/libflb-plugin-in_stream_processor.a ../library/libflb-plugin-in_serial.a ../library/libflb-plugin-in_stdin.a ../library/libflb-plugin-in_syslog.a ../library/libflb-plugin-in_exec.a ../library/libflb-plugin-in_tcp.a ../library/libflb-plugin-in_mqtt.a ../library/libflb-plugin-in_lib.a ../library/libflb-plugin-in_forward.a ../library/libflb-plugin-in_random.a ../library/libflb-plugin-out_azure.a ../library/libflb-plugin-out_bigquery.a ../library/libflb-plugin-out_counter.a ../library/libflb-plugin-out_datadog.a ../library/libflb-plugin-out_es.a ../library/libflb-plugin-out_exit.a ../library/libflb-plugin-out_file.a ../library/libflb-plugin-out_forward.a ../library/libflb-plugin-out_http.a ../library/libflb-plugin-out_influxdb.a ../library/libflb-plugin-out_kafka_rest.a ../library/libflb-plugin-out_nats.a ../library/libflb-plugin-out_null.a ../library/libflb-plugin-out_plot.a ../library/libflb-plugin-out_slack.a ../library/libflb-plugin-out_splunk.a ../library/libflb-plugin-out_stackdriver.a ../library/libflb-plugin-out_stdout.a ../library/libflb-plugin-out_tcp.a ../library/libflb-plugin-out_td.a ../library/libflb-plugin-out_lib.a ../library/libflb-plugin-out_flowcounter.a ../library/libflb-plugin-out_gelf.a ../library/libflb-plugin-filter_aws.a ../library/libflb-plugin-filter_expect.a ../library/libflb-plugin-filter_record_modifier.a ../library/libflb-plugin-filter_rewrite_tag.a ../library/libflb-plugin-filter_throttle.a ../library/libflb-plugin-filter_grep.a ../library/libflb-plugin-filter_kubernetes.a ../library/libflb-plugin-filter_parser.a ../library/libflb-plugin-filter_nest.a ../library/libflb-plugin-filter_modify.a ../library/libflb-plugin-filter_lua.a ../library/libflb-plugin-filter_stdout.a ../library/libfluent-bit.a -lm ../library/libmk_core.a ../library/libjsmn.a ../library/libmsgpackc.a ../library/libmpack-static.a ../library/libchunkio-static.a ../library/libcio-crc32.a ../library/libminiz.a ../library/libflb-plugin-proxy-go.a ../library/libmbedtls.a ../library/libmbedx509.a ../library/libmbedcrypto.a ../library/libco.a ../lib/libonigmo.a ../lib/libluajit.a ../library/libsqlite3.a ../library/libtutf8e.a ../library/libflb-ra-parser.a ../library/libflb-sp.a ../library/librbtree.a ../library/libflb-sp-parser.a 
[ 98%] Built target fluent-bit-shared
make: *** [all] Error 2
```

**Pull request closed without merging**
