### PR TITLE
nnn 4.3

### PR DESCRIPTION
**Pull request by jarun**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jarun** [comment]
@nandahkrishna can you please take a look why CI fails?

**Comment by jarun** [comment]
Probably happening due to the change in https://github.com/jarun/nnn/commit/f6856f61f74977a7929a601a4fc28168d2cc043c but I don't see why because in this case `NNN_TMPFILE` will not be set and the regular file should be written to.

**Comment by jarun** [comment]
OK, I see the completion scripts are installed. So `NNN_TMPFILE` will be exported as (for bash/zsh).

    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

Is it not resolved?

**Comment by jarun** [comment]
@carlocab the checks have passed now. Please have a look.

**Review by chenrui333 — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Likely because it no longer checks anything

**Comment by jarun** [comment]
Yes, the check is prone to changes. Feel free to add it back if you can debug the behaviour.

**Comment by jarun** [comment]
Also, in general, that check isn't relevant to Homebrew.

**Comment by jarun** [comment]
I have added the check for version. CI passes. Please take a look.

**Comment by chenrui333** [comment]
you could probably rebase to `upstream/master` and forced-push to date this PR instead of creating [a new one](https://github.com/Homebrew/homebrew-core/pull/86152).

**Comment by jarun** [comment]
Thanks for the tip! This was unattended for several hours and given how prompt Homebrew maintainers are I wasn't sure if it was going to be re-looked at.

**Comment by chenrui333** [comment]
I think the CI status is a bit confusing, that is why we did not look it thru. Yeah, a new PR is fine though.

**Comment by carlocab** [comment]
Fixed in #86369.

**Pull request closed without merging**
