### PR TITLE
libssh 0.9.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Failure appears to be related to `curl` DNS resolution issue, so @BrewTestBot, test this please.

**Comment by alebcay** [comment]
Looks like the issue is still persisting. I'm unable to reproduce this network-related failure on my end.

**Comment by fxcoudert** [comment]
Could we find a mirror?

**Comment by alebcay** [comment]
I found https://git.libssh.org/projects/libssh.git/snapshot/libssh-0.9.0.tar.xz. Would we want to specify this one as primary `url` or as a `mirror`?

**Comment by SMillerDev** [comment]
Let's try as a mirror

**Comment by alebcay** [comment]
Still seeing network-related issue on High Sierra; Mojave and Sierra pass without issue.

**Comment by alebcay** [comment]
@BrewTestBot test this please!

**Comment by alebcay** [comment]
It looks like `libssh`'s own GitLab is also experiencing the same resolution problems as the original site itself. Is [this](https://gitlab.com/libssh/libssh-mirror/-/tags) an acceptable mirror to use? I tried downloading the tarballs from either git site and found that the checksums don't match, so we'd just have to change `url`s entirely, not set it as a `mirror`.

**Comment by alebcay** [comment]
I guess the network issues are fixed now; this is passing now.

**Pull request closed without merging**
