### PR TITLE
mysqltuner: contains deprecated SPDX licenses

### PR DESCRIPTION
**Pull request by el7cosmos**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @el7cosmos. How were you able to determine it was `GPL-3.0-or-later` rather than `GPL-3.0-only`?

**Comment by el7cosmos** [comment]
> Thanks, @el7cosmos. How were you able to determine it was `GPL-3.0-or-later` rather than `GPL-3.0-only`?

By looking at LICENSE at their repository, https://github.com/major/MySQLTuner-perl/blob/bf8d1e69c1d2849b72147e6ff65e8a5466ecc50d/LICENSE#L640

**Comment by carlocab** [comment]
I also looked at their repository, but I couldn't tell.

The part of the `LICENSE` document you are referring to is not part of their license, that's why it appears [after the end of the terms and conditions](https://github.com/major/MySQLTuner-perl/blob/bf8d1e69c1d2849b72147e6ff65e8a5466ecc50d/LICENSE#L621). It's part of the GPL template that [explains how others can use the GPL](https://github.com/major/MySQLTuner-perl/blob/bf8d1e69c1d2849b72147e6ff65e8a5466ecc50d/LICENSE#L623).

Do you mind opening an issue to clarify their license? It looks to me like it might be `GPL-3.0-only`.

**Comment by Bo98** [comment]
Source files indicate `-or-later`: https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L9-L12

**Review by carlocab — APPROVED** [review]
Thanks, @el7cosmos, @Bo98!

**Pull request merged**
