### PR TITLE
knot-resolver 5.2.1

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Cf. https://github.com/Homebrew/homebrew-core/pull/66433

**Review by fxcoudert — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
Error: Bottles are for knot-resolver 5.2.1 but formula is version 5.2.1_1!
```

**Comment by carlocab** [comment]
I don't understand the error 😕

**Comment by fxcoudert** [comment]
I have no idea. Can you try to force-push so it retests?

**Comment by carlocab** [comment]
```
==> brew audit knot-resolver --online --git --skip-style
==> FAILED
knot-resolver:
  * 'revision 1' should be removed
```

Think I know what's going on. This just needs to be rebased against master. Going to try that.

**Comment by Rylan12** [comment]
The `root_keys` method isn't being used after 0a92f59a521d75201eba2697a2c039c3a19c4670, right? I think it can be removed.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
