### PR TITLE
gnumeric: remove vendored formulae resources.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This looks from the linked issue like it should now be able to use a modern `itstool` and `libxml2`.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@tschoonj Any chance of an assist here 🙇

**Comment by tschoonj** [comment]
The solution is not to remove these resources 😄

**Comment by MikeMcQuaid** [comment]
@tschoonj That's not a solution though, really, for a few reasons:

- how are those resources getting bug fix/security updates?
- the build is already broken on Mojave due to libxml2 issues
- the referenced issue states that this is fixed in the version of libxml2 we use

**Comment by tschoonj** [comment]
I see.

You may want to try patching `itstool` with the patch at https://build.opensuse.org/request/show/535476.

**Comment by tschoonj** [comment]
True, but the patch is not officially merged upstream since the bug is really in `libxml2`'s python bindings. 

This patch merely allows `itstool` to work around the `libxml2` [bug](https://gitlab.gnome.org/GNOME/libxml2/issues/12).

**Comment by MikeMcQuaid** [comment]
@tschoonj Thanks for the pointers! Let's see how this goes.

**Comment by MikeMcQuaid** [comment]
@tschoonj Still no joy. Any ideas? The alternative approach is figuring out a way for the current formula to find `libxml2` on modern macOS versions. Otherwise I think this formula is heading towards deletion...

**Comment by tschoonj** [comment]
From [here](https://github.com/itstool/itstool/issues/22#issuecomment-353988374) it appears that problem is with the `cs` translation (Czech language??) so disabling it in `gnumeric` appears to work as suggested in the discussion.

**Comment by MikeMcQuaid** [comment]
It works with that libxml2 patch, woohoo. Going to try and see if it works without a patched `itstool` now.

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
