### PR TITLE
ollama 0.1.10

### PR DESCRIPTION
**Pull request by 0xdevalias**
Created with `brew bump-formula-pr`.

- https://github.com/jmorganca/ollama/releases/tag/v0.1.10

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ollama
    * v0.1.10 is a GitHub pre-release.
```

**Comment by chenrui333** [comment]
image

**Comment by 0xdevalias** [comment]
@chenrui333 This isn't pre-release anymore.

**Comment by EricFromCanada** [comment]
@0xdevalias If you restore your deleted branch, this PR can be reopened.

**Comment by 0xdevalias** [comment]
@EricFromCanada Restored :)

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks!

**Pull request merged**
