### PR TITLE
qt5 5.7.0

### PR DESCRIPTION
**Pull request by ilovezfs**
re-add patch for restoring .pc files for framework builds
patch for qt3d parallelized build failure
patch for can't-run-xcrun-with-xcrun-in-Xcode-8
patch for CUPS build failure on Sierra
refresh qtwebengine patch for bluetooth so it still applies successfully
move patches already merged upstream into the stable block

CC @schoeps

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @schoeps

**Comment by schoeps** [comment]
Did not compile here...
```
==> make
Last 15 lines from /Users/admin/Library/Logs/Homebrew/qt5/02.make:
Some of the required modules (linux:!android) are not available.
Skipped.
cd qtconnectivity/ && ( test -e Makefile || /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtbase/bin/qmake /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtconnectivity/qtconnectivity.pro -qtconf /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtbase/bin/qt.conf -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
Info: creating cache file /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtconnectivity/.qmake.cache
Checking for bluez... no
Checking for bluez_le... no
Checking for linux_crypto_api... no
cd src/ && ( test -e Makefile || /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtbase/bin/qmake /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtconnectivity/src/src.pro -qtconf /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtbase/bin/qt.conf -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
cd bluetooth/ && ( test -e Makefile || /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtbase/bin/qmake /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtconnectivity/src/bluetooth/bluetooth.pro -qtconf /private/tmp/qt5-20161015-51566-1azycwa/qt-everywhere-opensource-src-5.7.0/qtbase/bin/qt.conf -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
Makefile:5894: warning: overriding commands for target `.moc/moc_qbluetoothtransferreply_osx_p.cpp'
Makefile:5728: warning: ignoring old commands for target `.moc/moc_qbluetoothtransferreply_osx_p.cpp'
make[3]: *** No rule to make target `osx/corebluetoothwrapper_p.h', needed by `../../lib/QtBluetooth.framework/Versions/5/Headers/5.7.0/QtBluetooth/private/corebluetoothwrapper_p.h'.  Stop.
make[2]: *** [sub-bluetooth-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtconnectivity-make_first] Error 2
```

**Comment by RandomDSdevel** [comment]
@schoeps:  Looks to me like @ilovezfs may have accidentally re-introduced some old patches that are no longer applicable to this Qt release here…

**Comment by ilovezfs** [comment]
@schoeps please try again. It looks like the newer of their two bluetooth patches isn't ready for prime time yet. I'd already removed it before you posted the above hehe.

**Comment by ilovezfs** [comment]
@schoeps parallelization fix applied now too! http://code.qt.io/cgit/qt/qt3d.git/commit/src/src.pro?id=db3baec236841f9390e9450772838cb7ba878069.

**Comment by schoeps** [comment]
I can confirm that `qt5` and `qscintilla2` build. Now compiling `octave`....

**Comment by schoeps** [comment]
`gnuplot` compiles without modifications and my [`octave`](https://raw.githubusercontent.com/schoeps/homebrew-science/octave/octave.rb),  too. Please push :)

**Comment by ilovezfs** [comment]
@schoeps shipped!

**Pull request closed without merging**
