### PR TITLE
libvirt: add HEAD

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by justinclift** [comment]
@novel :smile:
@Jerzerak This may be of interest to you.

**Comment by ilovezfs** [comment]
@justinclift mind updating the test in some way so that it passes for HEAD?

**Comment by justinclift** [comment]
Ahhh, didn't think of that.  Yeah, no worries. :smile:

**Comment by justinclift** [comment]
In theory (!), it should be ok now. 😁

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
