### PR TITLE
ipmiutil 3.1.8

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>license ref (`COPYING`)</summary>

```
Format:  http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: ipmiutil
Upstream-Contact: Andy Cress <arcress at users.sourceforge.net>
Source:  http://ipmiutil.sourceforge.net
Comment: This COPYING file includes detail about each source file in ipmiutil

Files: *
Copyright: 2001-2008, Intel Corporation
   2009-2012, Kontron America
   2013, Andy Cress <arcress at users.sourceforge.net>
License: BSD-3-clause

Files: lib/lanplus/*
Copyright: 2003 Sun Microsystems, Inc.
License:   BSD-3-clause

Files: util/itsol.c
Copyright: 2005 Tyan Computer Corp.
License:   BSD-3-clause

Files: util/iekanalyzer.c
Copyright: 2007 Kontron Canada, Inc.
           2003 Sun Microsystems, Inc.
License:   BSD-3-clause

Files: util/md2.h
Copyright: 2003 FreeIPMI Core Team
Comment:   Build does not include this file, unless 'configure --enable-gpl'
License:   GPL-2.0

Files: util/AnsiTerm.cpp
Copyright: 2009 Robert Nelson <robertnelson at users.sourceforge.net>
License:   BSD-2-clause

Files: util/oem_dell.c
Copyright: 2008, Dell Inc
License:   BSD-3-clause

Files: util/oem_sun.c
Copyright: 2005 Sun Microsystems, Inc.
License:   BSD-3-clause

Files: util/ifirewall.c
Copyright: 2010 Kontron America Inc.
	   2005 International Business Machines, Inc.
	   2003 Sun Microsystems, Inc.
License:   BSD-3-clause

Files: util/ifwum.c util/ihpm.c
Copyright: 2004-2006 Kontron Canada, Inc.
           2003 Sun Microsystems, Inc.
License:   BSD-3-clause

Files: util/md5.c
Copyright: 1999, 2000, 2002 Aladdin Enterprises.
Comment: Aladdin unrestricted license is compatible with BSD-3-clause
License: Aladdin
  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.
  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:
  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
  L. Peter Deutsch
  ghost@aladdin.com

License:   BSD-3-clause
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
   a. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   b. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
   c. Neither the name of Kontron, nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

License:   BSD-2-clause
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
  a. Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.
  b. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

License:   GPL-2.0
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  A copy of the GNU General Public License is available as
  /usr/share/common-licenses/GPL-2 in the Debian distribution or on
  the World Wide Web at http://www.gnu.org/copyleft/gpl.html. You can
  also obtain it by writing to the Free Software Foundation, Inc.,
  51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

```


</details>

**Comment by chenrui333** [comment]
>   clang: error: no such file or directory: '../lib/libipmi_lanplus.a'

**Comment by chenrui333** [comment]
> To build a standalone binary without IPMI LAN 2.0 (lanplus plugin),
> which may be desirable for use on bootable media (USB/CDROM), to 
> decrease the size or to avoid using libcrypto, you can specify the 
> following during configure:
>    "./configure --disable-lanplus"
> or
>    "./configure --enable-standalone"
> builds it without lanplus libs and without GPL code.

**Comment by chenrui333** [comment]
only build failure on `12-arm64` cc @Homebrew/core

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
