### PR TITLE
rethinkdb 2.3.0

### PR DESCRIPTION
**Pull request by danielmewes**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by apjanke** [comment]
Build failure is a plist-related audit failure.

```
failed: brew audit rethinkdb

Stacktrace

        Error: 1 problem in 1 formula
rethinkdb:
 * Please set plist_options when using a formula-defined plist.
```

I believe this particular plist audit check was introduced recently (https://github.com/Homebrew/brew/pull/19) which is why it wouldn't have been flagged in earlier versions.

**Comment by danielmewes** [comment]
Thanks for the explanation @apjanke. I was indeed running the audit against an older version. My mistake.
Just updated the pull request.

**Comment by gcoderre** [comment]
I think there's a typo in there!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/e0296a79b7c464722b70afe1bfa9366c34eca61e. Thank you for another contribution to Homebrew @danielmewes! :smiley_cat:

**Pull request closed without merging**
