### PR TITLE
get-flash-videos 1.25.92

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like there's a resource missing or they haven't been sufficiently updated or something.

**Comment by rakkesh** [comment]
Two additional resources are required,

```rb
  resource "Term::ProgressBar" do
    url "https://cpan.metacpan.org/authors/id/S/SZ/SZABGAB/Term-ProgressBar-2.17.tar.gz"
    sha256 "c1e0602c738a91fe54b01bcaa0d1a898b07ef6815c55eb2ebd6da4e3be20f696"
  end

  resource "Class::MethodMaker" do
    url "https://cpan.metacpan.org/authors/id/S/SC/SCHWIGON/class-methodmaker/Class-MethodMaker-2.24.tar.gz"
    sha256 "5eef58ccb27ebd01bcde5b14bcc553b5347a0699e5c3e921c7780c3526890328"
  end
```

**Comment by ilovezfs** [comment]
@rakkesh I'll close the PR if you'd like to fix this one :)

**Comment by rakkesh** [comment]
@ilovezfs Or I could send you a pull request?

**Comment by ilovezfs** [comment]
@rakkesh It's all yours.

**Pull request closed without merging**
