### PR TITLE
xclogparser: staticly link Swift stdlib on Linux

### PR DESCRIPTION
**Pull request by Bo98**
This doesn't build on Swift 6 on macOS so might not on Linux. We won't be offering a `swift@5`.

Revision bump as the Swift PR will otherwise break this.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by Bo98** [comment]
Ok looks like I need to merge Swift 6 first for this to work so will do that.

**Comment by cho-m** [comment]
Interesting that Sonoma works. I thought it would fail with Xcode 16.

**Comment by Bo98** [comment]
I think it's a change in Foundation rather than the compiler. Something like https://github.com/MobileNativeFoundation/XCLogParser/pull/217 probably fixes it (though does assume the input is null-terminated which I'm not entirely sure is safe or not).

**Comment by chenrui333** [comment]
this is needed for xclogparser 0.2.40 build, https://github.com/1024jp/GzipSwift/pull/71

**Comment by Bo98** [comment]
There's already an `inreplace` here to fix that. Ideally an upstream fix would be something that allows any arbitrary include path. That upstream patch as-is wouldn't really work for us as it would we would want to prioritise Homebrew over system in our case.

**Pull request closed without merging**
