### PR TITLE
qca 2.1.1

### PR DESCRIPTION
**Pull request by dakcarto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

Switches source code provenance to KDE mirrored github account. QCA is an official subproject of KDE.

### CODE REVIEW

**Comment by dakcarto** [comment]
Duplicate of #5162

**Comment by dakcarto** [comment]
Duh, reopening, thought this was the `qwt` PR I had formatted but forgot to submit.

**Comment by dakcarto** [comment]
Fixed test binary name and finished removal of Qt4 support.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
