### PR TITLE
Remove `terraform` dependency from `terragrunt` formula

### PR DESCRIPTION
**Pull request by bingtsingw**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bingtsingw** [comment]
`terragrunt` with `terraform` as its dependency conflicts with `tfenv`.
In fact, there is no need to add terraform as a dependency, one can always install `terraform` on his own way.
https://github.com/gruntwork-io/terragrunt/issues/580

**Comment by SMillerDev** [comment]
Can you run it without having any version of terraform installed?

**Comment by bingtsingw** [comment]
> Can you run it without having any version of terraform installed?

Hi, it's hard to give a simple conclusion, I'll try to explain the relationship between `terraform` and `terragrunt`, and why I 
want to remove the dependency.

`terragrunt` is a wrapper for `terraform`, it extends many features of `terraform`, so some of its commands will use `terraform` behind the scenes:

```shell
# I uninstalled terraform before the test
❯ terraform --version
No versions of terraform installed. Please install one with: tfenv install

# can run help command without terraform
❯ terragrunt --version
terragrunt version v0.28.14

# can run `hclfmt` command without terraform
❯ terragrunt hclfmt
INFO[0000] Formatting terragrunt.hcl files from the directory tree xxx

# CANNOT run `apply` command without terraform
❯ terragrunt apply
ERRO[0000] exit status 1
```

In fact, to make `terragrunt` usefull, `terraform` is necessary, but since it's a wrapper of `terraform`, I suppose anyone who use `terragrunt` should know the necessity of installing `terraform` first.

In my term, I have multiple projects which use different version of `terraform`, so I use `tfenv` to manage multiple versions of `terraform`, like `nvm` for `node` or `pyenv` for `python`.

To support flexible installation methods, we can remove `terraform` as a dependency and let the users choose their way to install `terraform`, so that some would just run `brew install terraform`, others would use `tfenv install` for multiple version management.

**Comment by bingtsingw** [comment]
Maybe we can add a message telling users to install `terraform` manually for better hint.

**Comment by SMillerDev** [comment]
> To support flexible installation methods, we can remove terraform as a dependency and let the users choose their way to install terraform, so that some would just run brew install terraform, others would use tfenv install for multiple version management.

This would mean that if you're a new user who just got refered to terragrunt your new install will be broken. This is not a good user experience. If you want this formula without the dependency I suggest using `brew extract` to maintain it in a personal tap.

**Comment by bingtsingw** [comment]
> This would mean that if you're a new user who just got refered to terragrunt your new install will be broken. This is not a good user experience. If you want this formula without the dependency I suggest using `brew extract` to maintain it in a personal tap.

Yes, you are right, it do harm the user experience, not a perfect solution.

Thank you for your patience and hint on `brew extract`, maintaining a personal tap seems to be a better solution.

**Pull request closed without merging**
