### PR TITLE
gradle 4.0

### PR DESCRIPTION
**Pull request by kunickiaj**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by JCount** [comment]
@kunickiaj Why is it necessary to create a new versioned `gradle@3.5` formula? I understand that there are potentially breaking changes in this update, but we try and avoid creating versioned formulae without solid justification as to why they are necessary. Upstream also does still continue to provide older versions of `gradle` for those who need them.

**Comment by kunickiaj** [comment]
wasn't aware, happy to remove it.

**Comment by y3rsh** [comment]
Was hoping this was here.  Thank you for all you do @JCount and for getting this PR in @kunickiaj

**Comment by ilovezfs** [comment]
Thanks for the PR @kunickiaj!

**Pull request merged**
