### PR TITLE
ttyd 1.7.2

### PR DESCRIPTION
**Pull request by maaslalani**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
libwebsocket issue on linux

```
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libwebsockets.a(unix-sockets.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
```

**Comment by chenrui333** [comment]
cc @Homebrew/linux

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/116656

**Comment by danielnachun** [comment]
Actually this one is because `libwebsockets` needs to be rebottled.  But I got a weird error when I tried to do that: https://github.com/Homebrew/homebrew-core/actions/runs/3536188543/jobs/5934997615

**Comment by chenrui333** [comment]
> Actually this one is because `libwebsockets` needs to be rebottled. But I got a weird error when I tried to do that: https://github.com/Homebrew/homebrew-core/actions/runs/3536188543/jobs/5934997615

yeah, I tried `libwebsockets` rebottle idea as well, it did not work, that is why I was also trying to force a rebuild by bumping the revision, got some push back on that

**Pull request closed without merging**
