### PR TITLE
Secure URLs (2/2)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
t1lib puked on Yosemite.

**Comment by ilovezfs** [comment]
Interestingly not even the URL you're changing …

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by vszakats** [comment]
It should be something pre-existing.

**Comment by ilovezfs** [comment]
yup

**Comment by ilovezfs** [comment]
:1st_place_medal:

**Comment by MikeMcQuaid** [comment]
Do we know why the audit didn't catch any of these?

**Comment by ilovezfs** [comment]
Nope.

**Comment by ilovezfs** [comment]
iMac-TMP:~ joe$ for f in znc cdargs t1lib; do echo "$f ..."; brew audit --strict --online $f; done
znc ...
znc:
  * Stable: The URL http://znc.in/releases/archive/znc-1.6.5.tar.gz could use HTTPS rather than HTTP
Error: 1 problem in 1 formula
cdargs ...
cdargs:
  * A `test do` test block should be added
  * Stable: The URL http://www.skamphausen.de/downloads/cdargs/cdargs-1.35.tar.gz could use HTTPS rather than HTTP
Error: 2 problems in 1 formula
t1lib ...
t1lib:
  * A `test do` test block should be added
  * The URL http://www.t1lib.org/ could use HTTPS rather than HTTP
Error: 2 problems in 1 formula
iMac-TMP:~ joe$

**Pull request merged**
