### PR TITLE
mesa 19.0.5

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zbeekman** [comment]
tarball missing from url source (yanked release?)

**Comment by yurikoles** [comment]
There was a typo, I had built in on macOS, but committed and pushed from Linux.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

P.S. For future reference, please rebase and squash/fixup commits like the second one. You can discard their commit messages and then force-push to your branch. Thanks!

**Comment by yurikoles** [comment]
@zbeekman, thank you for good words.

Cask maintenaners asked be not to force-push, because GH doesn't notify in this case.

**Comment by zbeekman** [comment]
> Cask maintenaners asked be not to force-push, because GH doesn't notify in this case.

Fair enough. cask and core have slightly different workflows and expectations. For core I would say try to squash and force push, and you can always @mention a maintainer who started reviewing to let them know what you're up to. I think force pushes will (now at least) still cause the PR to rise to the top when sorted by activity.

Basically the first line of the commit message (one per formula) should read:

```
<formula-name> <formula-version> [(new formula)]
```

where `(new formula)` is only included for new formula. Then a blank line. Then, if there are additional important points to add, you can add bullet points on the 3rd and following lines describing any additional tweaks or changes that were needed.

The homebrew-core workflow is different because we build binaries and deploy them. To merge formulae we use `brew pull` which automates publishing binary bottles on bintray. `brew pull goes and gets & applies patches, one per commit, from the PR and then applies additional patches for the bottle info. If a maintainer GPG signs commits by default and uses a SC w/ password (like I do) then the rebasing process involved in pulling the original commits as patches is more time consuming with additional commits. Then, if the commit message needs further cleanup before pushing, that requires more rebasing and gpg signing. So 1 commit per PR for single formula PRs please. For more complex things requiring formula revisions and patching (like when trying to merge a new boost release) then there should be 1 commit per formula.

For homebrew-cask, please continue to follow the advice that cask maintainers have already given you.

Thanks!

**Comment by yurikoles** [comment]
Thanks for explanation.

**Pull request closed without merging**
