### PR TITLE
ca-certificates: validate pem file

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
I applaud testbots enthusiasm, but that's not my issue to fix IYAM
```
 ==> FAILED
openssl@3:
  * Stable: should always include at least one HTTP mirror
```

**Comment by carlocab** [comment]
It is now that you've made it a dependency of `ca-certificates`. Though the audit should maybe not apply to test dependencies. You can probably get around it by using `openssl@1.1` instead.

**Comment by Bo98** [comment]
I'm surprised this dependency loop works. I suspected we would've needed to use something like Ruby's `OpenSSL::X509::Store`.

Does `openssl verify` actually parse check the whole bundle or just the first certificate?

**Comment by SMillerDev** [comment]
It just outputs okay, I didn't check the implementation 😅

**Comment by SMillerDev** [comment]
I'll redo this based on cURL to avoid a dependency loop

**Comment by carlocab** [comment]
> I'm surprised this dependency loop works.

We have one other formula with a dependency loop like this that seems to work fine. I think the only time we're in trouble is if the build/runtime dependencies have a loop. Still, probably better to avoid it.

**Pull request closed without merging**
