### PR TITLE
infer 0.15.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
infer:
  * The URL https://fbinfer.com/ is not reachable
```
was fixed in https://github.com/Homebrew/homebrew-core/pull/28831

**Comment by ilovezfs** [comment]
CC @jvillard

**Comment by jvillard** [comment]
Thanks @ilovezfs!

**Comment by ilovezfs** [comment]
@jvillard you're welcome!

**Pull request closed without merging**
