### PR TITLE
cockroach 2.1.7

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
13:24:41 tar xof /Users/brew/Library/Caches/Homebrew/downloads/af0196d886dbaae1bb8c23b91f4cc38ef4dabdee0ede47364776c6f4094859ca--cockroach-v2.1.7.src.tgz -C /private/tmp/d20190519-47502-nel76u
13:24:41 cp -pR /private/tmp/d20190519-47502-nel76u/cockroach-v2.1.7/. /private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7
13:24:41 chmod -Rf +w /private/tmp/d20190519-47502-nel76u
13:24:41 ==> make buildoss
13:24:41 make -C src/github.com/cockroachdb/cockroach buildoss
13:24:41 make[1]: Entering directory '/private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7/src/github.com/cockroachdb/cockroach'
13:24:41 GOPATH set to /private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7
13:24:41 go 1.12+ is known to produce invalid crdb builds, see https://github.com/cockroachdb/cockroach/issues/35637
13:24:41 Disable this check with IGNORE_GOVERS=1.
13:24:41 make[1]: *** [Makefile:660: build/defs.mk] Error 1
13:24:41 make[1]: Leaving directory '/private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7/src/github.com/cockroachdb/cockroach'
13:24:41 make: *** [Makefile:6: buildoss] Error 2
13:24:41 
13:24:41 ==> Formula
13:24:41 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cockroach.rb
```

**Comment by zbeekman** [comment]
This smells like an upstream problem... Also, someone needs to clarify their versioning convention.

**Comment by chenrui333** [comment]
@zbeekman there is version 19 upgrade before in this PR, https://github.com/Homebrew/homebrew-core/pull/39432

**Comment by chenrui333** [comment]
I think currently they have two major lines running. But yeah, we need to confirm that.

**Comment by zbeekman** [comment]
We should ship the latest version that we can build, *without downgrading*. If that is 19.x then we should ship 19.x. Otherwise, if 2.x will build we should ship 2.x.

**Comment by bdarnell** [comment]
> I think currently they have two major lines running. But yeah, we need to confirm that.

It's actually 3 :) (2.0, 2.1, and 19.1)

Homebrew currently has 2.1.6 (because 19.1.0 had some issues building in homebrew's CI: cockroachdb/cockroach#35657), so it could technically upgrade to either 2.1.7 or 19.1.1 without downgrading. But it's our intention to move to the latest branch, so this PR should be closed in favor of #40103.

**Pull request closed without merging**
