### PR TITLE
git: include native prompt for zsh as well

### PR DESCRIPTION
**Pull request by dijonkitchen**
File supports both bash and zsh: https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh#L1

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zbeekman** [comment]
LGTM, but @dijonkitchen could you please run fill out the issue template, especially running the `brew audit` step?

Thanks

**Comment by dijonkitchen** [comment]
Will try; getting some weird errors and installation complications. 

Can the tests and audit be automated via the CI? Seems weird to make this manual for every person's PR.

**Comment by SMillerDev** [comment]
It is, we just don't want to waste CI time on things people should have checked before committing.

**Comment by dijonkitchen** [comment]
Unfortunately, I'm going to close this since I couldn't get the test and audit working properly. 

I do think this should be a simple addition if anyone is interested.

**Pull request closed without merging**
