### PR TITLE
xz 5.4.4

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
Looks like the latest is still 5.4.3? I can't find a mention of 5.4.4 in https://tukaani.org/xz/ or in repology.

```console
$ brew bump xz
==> xz
Current formula version:  5.4.3
Latest livecheck version: 5.4.4
Latest Repology version:  5.4.3
Open pull requests:       xz 5.4.4 (https://github.com/Homebrew/homebrew-core/pull/138323)
Closed pull requests:     none
```

**Comment by chenrui333** [comment]
I can see it on the homepage

> 5.4.4 was released on 2023-08-02
image

**Comment by chenrui333** [comment]
actually the two archive.org mirrors have not been populated with `xz-5.4.4.tar.gz`, cancelled the builds

**Comment by osalbahr** [comment]
> I can see it on the homepage
> 
> > 5.4.4 was released on 2023-08-02
> 

Yeah you're right. I guess my browser decided to cache the page because 5.4.4 appears in a private browsing window.

Screenshot 2023-08-03 at 12 49 33 PM


Screenshot 2023-08-03 at 12 51 17 PM

**Comment by chenrui333** [comment]
> Yeah you're right. I guess my browser decided to cache the page because 5.4.4 appears in a private browsing window.

that is interesting to know LOL

**Review by carlocab — APPROVED** [review]
Dependent failures are unrelated.

**Pull request merged**
