### PR TITLE
verilator: revision for gcc

### PR DESCRIPTION
**Pull request by iMichka**
Follow up of #106755

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
We should find a way to avoid relying on a specific `g++-*` and just use whatever's available.

**Comment by iMichka** [comment]
Here was the error:

```
2022-08-04T18:17:43.6750992Z [32m==>[0m [1mTesting verilator[0m
2022-08-04T18:17:43.6756895Z [34m==>[0m [1m/usr/bin/perl /home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/bin/verilator -Wall --cc test.v --exe test.cpp[0m
2022-08-04T18:17:43.6757729Z [34m==>[0m [1mmake -j -f Vtest.mk Vtest[0m
2022-08-04T18:17:43.6759606Z g++-11 -Os -w -pipe -march=native -isystem/home/linuxbrew/.linuxbrew/include -I.  -MMD -I/home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/share/verilator/include -I/home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow      -std=gnu++14 -Os -c -o test.o ../test.cpp
2022-08-04T18:17:43.6762877Z g++-11 -Os -w -pipe -march=native -isystem/home/linuxbrew/.linuxbrew/include -I.  -MMD -I/home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/share/verilator/include -I/home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow      -std=gnu++14 -Os -c -o verilated.o /home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/share/verilator/include/verilated.cpp
2022-08-04T18:17:43.6764992Z make: g++-11: Command not found
2022-08-04T18:17:43.6766198Z /home/linuxbrew/.linuxbrew/opt/perl/bin/perl /home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/share/verilator/bin/verilator_includer -DVL_INCLUDE_OPT=include Vtest.cpp Vtest___024root__DepSet_hc07518e4__0.cpp Vtest___024root__Slow.cpp Vtest___024root__DepSet_hc07518e4__0__Slow.cpp Vtest__Syms.cpp > Vtest__ALL.cpp
2022-08-04T18:17:43.6767112Z Vtest.mk:61: recipe for target 'test.o' failed
2022-08-04T18:17:43.6767520Z make: *** [test.o] Error 127
2022-08-04T18:17:43.6767911Z make: *** Waiting for unfinished jobs....
2022-08-04T18:17:43.6768382Z make: g++-11: Command not found
2022-08-04T18:17:43.6769106Z /home/linuxbrew/.linuxbrew/Cellar/verilator/4.224/share/verilator/include/verilated.mk:268: recipe for target 'verilated.o' failed
2022-08-04T18:17:43.6769660Z make: *** [verilated.o] Error 127
```

**Comment by carlocab** [comment]
Yup, it seems to rely on the `g++-*` it found during the build. I wonder if an `inreplace` in `post_install` is worth trying.

**Comment by fxcoudert** [comment]
I've been thinking about issues like this: maybe we want to provide a stable path with unversioned binary names (`gcc` and `g++`), outside of `bin`?

**Comment by carlocab** [comment]
That would be nice for users, but probably doesn't help formulae too much; not without changes to superenv or related code, anyway. It'll probably also require a bunch of env scripts to add that directory to `PATH` which I'd like to avoid.

**Comment by cho-m** [comment]
`share/verilator/include/verilated.mk`
```
AR = ar
CXX = g++-11
LINK = g++-11
```

https://github.com/verilator/verilator/blob/master/include/verilated.mk.in
```
AR = @AR@
CXX = @CXX@
LINK = @CXX@
```

**Comment by carlocab** [comment]
So maybe something like
```ruby
  def post_install
     return if OS.mac?

     # Ensure the hard-coded versioned `gcc` reference does not go stale.
     ohai "Fixing up GCC references..."
     gcc_version = Formula["gcc"].any_installed_version.major
     inreplace(pkgshare/"include/verilated.mk") do |s|
       s.change_make_var! "CXX", "g++-#{gcc_version}"
       s.change_make_var! "LINK", "g++-#{gcc_version}"
     end
   end
```

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
