### PR TITLE
kontena 1.5.2

### PR DESCRIPTION
**Pull request by kke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apjanke** [comment]
Test is failing on the CI server.

```
        Testing kontena
/usr/bin/sandbox-exec -f /tmp/homebrew20180312-56763-rxbro8.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kontena.rb --verbose
==> /usr/local/Cellar/kontena/1.5.2/bin/kontena --version
==> /usr/local/Cellar/kontena/1.5.2/bin/kontena complete kontena master
==> /usr/local/Cellar/kontena/1.5.2/bin/kontena plugin search digitalocean
==> /usr/local/Cellar/kontena/1.5.2/bin/kontena stack reg show kontena/hello-world
 [error] 500 : An unhandled lowlevel error occurred. The application logs may have details.
 (/v2/organizations/kontena/stacks/hello-world/stack-versions)
Error: kontena: failed
<0> expected but was
<1>.
```

**Comment by kke** [comment]
Weird. Seems to run fine locally™️ 

Could have been a temporary glitch on the stack registry service that this test relies on, can you restart the test job?

image

**Comment by kke** [comment]
It might be a good idea to drop/replace the tests that require online connecticity (the `plugin search` and the `stack reg show`)

**Comment by commitay** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @kke for the pull request!

**Pull request closed without merging**
