### PR TITLE
libtasn1 4.17.0

### PR DESCRIPTION
**Pull request by JeffreyBytes**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Need to update `patch` block.

Upstream issue is still open: https://gitlab.com/gnutls/libtasn1/-/issues/30
So, probably need to see if new patch is necessary on 4.17.0.

**Comment by spaz926** [comment]
I see the upstream issue is still open, but when I remove the `patch` block the build and `brew test` succeed.
Do you think patch is no longer necessary?

I was reading over the `patch` block in the formula cookbook, and don't completely understand what it is doing.

**Comment by carlocab** [comment]
The patch isn't for a build failure, but to fix an issue with UB. I think we need a different patch.

**Comment by cho-m** [comment]
It looks like they may have just forgot to close the issue.

I think it is fine to simply remove `patch` block in this case.

**Comment by carlocab** [comment]
Asked for clarification at https://gitlab.com/gnutls/libtasn1/-/issues/30. Let's wait for a response there before dropping the patch.

**Comment by roolebo** [comment]
@cho-m, @carlocab yeah, it should be ok to drop the patch. Thanks!

**Comment by carlocab** [comment]
Thanks, @roolebo.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
On ARM:

```
Error: 1 failed step!
brew test --retry --verbose monkeysphere
```

We can fix this by bumping the revision now that Perl shebang handling has been merged.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks, @spaz926.

**Pull request closed without merging**
