### PR TITLE
ftjam: fix build for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/runs/3062567638?check_suite_focus=true
```
Cc bin.unix/fileunix.o 
Cc bin.unix/pathunix.o 
Yacc1 jamgram.c jamgram.h 
/bin/sh: 2: yacc: not found

yacc -d jamgram.y

...failed Yacc1 jamgram.c jamgram.h ...
```

### CODE REVIEW

**Comment by danielnachun** [comment]
Can we figure what the license is:
```
    /+\
    +\	Copyright 1993-2002 Christopher Seiwald and Perforce Software, Inc.
    \+/

    This is Release 2.5 of Jam, a make-like program.

    License is hereby granted to use this software and distribute it
    freely, as long as this copyright notice is retained and modifications
    are clearly marked.

    ALL WARRANTIES ARE HEREBY DISCLAIMED.
```

**Comment by SMillerDev** [comment]
Debian doesn't seem to define a license either. https://packages.debian.org/bullseye/ftjam

**Comment by cho-m** [comment]
Is there a SPDX that works here?
Or should we just use `license :cannot_represent`

**Comment by danielnachun** [comment]
I think we'll have to do `:cannot_represent`, as Arch Linux just calls it "custom" as well.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
