### PR TITLE
Testing. DO NOT MERGE.

### PR DESCRIPTION
**Pull request by carlocab**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
I was trying to simulate someone making a PR from their master branch to see what the `gh pr checkout` looks like, but it seems I need another user to do it. 😅

**Comment by ZhongRuoyu** [comment]
If you still want to test this, I can open a PR :)

**Comment by carlocab** [comment]
That would help! I was thinking someone else would eventually open another PR from their master branch...

**Comment by ZhongRuoyu** [comment]
Here you go: #126779

**Pull request closed without merging**
