### PR TITLE
qwt: port qwt to qt5

### PR DESCRIPTION
**Pull request by j-rivero**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

I was able to compile `qwt` using `qt5` (related to #1705) on my ElCapitan machine with this set of changes. `brew test` also finished just fine. I was able to compile `gnuradio` (revdep) using this modified version but I'm unsure that the commands that I run from gnuradio really tests loading and runtime so please feel free to propose an application (or gnuradio command) to test that runtime is fine.

Thanks.

### CODE REVIEW

**Comment by zmwangx** [comment]
Pretty sure `gnuradio` does not support Qt5 (I read from an upstream maintainer a short while ago). Thanks though.

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by dakcarto** [comment]
This looks pretty good to me (came up with much the same just 10 mins ago, then found this PR). Would like to see it merged, when convenient. Thanks @j-rivero 

I have a couple suggestions:

- Strip the version from description
- Bump revision, due to Qt dep change
- Force Qt5-specific `qmake` to be used (I _think_ this is necessary)

```
diff --git a/Formula/qwt.rb b/Formula/qwt.rb
index e11ca22..e1a050b 100644
--- a/Formula/qwt.rb
+++ b/Formula/qwt.rb
@@ -1,8 +1,9 @@
 class Qwt < Formula
-  desc "Qt Widgets for Technical Applications (v5.1)"
+  desc "Qt Widgets for Technical Applications"
   homepage "http://qwt.sourceforge.net/"
   url "https://downloads.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.3.tar.bz2"
   sha256 "f3ecd34e72a9a2b08422fb6c8e909ca76f4ce5fa77acad7a2883b701f4309733"
+  revision 1
 
   bottle do
     cellar :any
@@ -44,7 +45,7 @@ class Qwt < Formula
       prefix.install "textengines/mathml/qtmmlwidget-license"
     end
 
-    system "qmake", *args
+    system Formula["qt5"].bin/"qmake", *args
     system "make"
     system "make", "install"
   end
```

**Comment by MikeMcQuaid** [comment]
> Strip the version from description
> Bump revision, due to Qt dep change
> Force Qt5-specific qmake to be used (I think this is necessary)

Agreed 👍

**Comment by scpeters** [comment]
I'll just chime in that I think @j-rivero is traveling at the moment, so I'm not sure when he will have a chance to respond (we are co-workers). Those suggested changes look good to me too.

**Comment by j-rivero** [comment]
Thanks Larry for the comments and patches. I've committed it in a single commit 87897ee, let me know if you prefer me to squash the two commits or you will do it by yourself when merging.

**Comment by scpeters** [comment]
The test is failing to compile with many complaints about c++11. The following fixes it for me:

~~~
diff --git a/Formula/qwt.rb b/Formula/qwt.rb
index 26941a0..4f2169a 100644
--- a/Formula/qwt.rb
+++ b/Formula/qwt.rb
@@ -73,6 +73,7 @@ class Qwt < Formula
       }
     EOS
     system ENV.cxx, "test.cpp", "-o", "out",
+      "-std=c++11",
       "-framework", "qwt", "-framework", "QtCore",
       "-F#{lib}", "-F#{Formula["qt5"].opt_lib}",
       "-I#{lib}/qwt.framework/Headers",
~~~

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
