### PR TITLE
movgrab 3.1.2

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Build failed, mostly from `getxattr`-related failures:

```
FileSystem.c:240:33: error: too few arguments to function call, expected 6, have 4
len=getxattr(Path, Name, NULL, 0);
    ~~~~~~~~                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
^
FileSystem.c:244:34: error: too few arguments to function call, expected 6, have 4
        getxattr(Path, Name, RetStr, len);
        ~~~~~~~~                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
^
FileSystem.c:259:42: error: too few arguments to function call, expected 6, have 5
return(setxattr(Path, Name, Value, Len, 0));
       ~~~~~~~~                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/xattr.h:65:1: note: 'setxattr' declared here
int setxattr(const char *path, const char *name, const void *value, size_t size, u_int32_t position, int options);
^
FileSystem.c:410:10: error: expected ';' after expression
result=-1
         ^
         ;
4 errors generated.
make[1]: *** [FileSystem.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

Looks like this is an incompatibility between the macOS and Linux functions of the same name. Neither version is POSIX.

**Comment by mistydemeo** [comment]
Looked into this. This patch fixes the two errors, but it still fails to build due to the use of the Linux-only function `setresuid`. For the latter, we can probably adapt the change made upstream: https://github.com/ColumPaget/Movgrab/blob/master/libUseful/Process.c#L95-L99

```diff
diff --git a/Formula/movgrab.rb b/Formula/movgrab.rb
index 4e9ab45b40..60c7d97dcb 100644
--- a/Formula/movgrab.rb
+++ b/Formula/movgrab.rb
@@ -16,6 +16,15 @@ class Movgrab < Formula
   end
 
   def install
+    # libUseful's configure script incorrectly detects macOS's getxattr functions,
+    # expecting them to be functionally equivalent to Linux's. They're not!
+    ENV["ac_cv_lib_c_getxattr"] = "no"
+    ENV["ac_cv_lib_c_setxattr"] = "no"
+
+    # Can you believe this? A forgotten semicolon! Probably got missed because it's
+    # behind a conditional #ifdef.
+    inreplace "libUseful-2.8/FileSystem.c", "result=-1", "result=-1;"
+
     system "./configure", "--prefix=#{prefix}", "--disable-debug", "--disable-dependency-tracking"
     system "make"
 
```

**Comment by mistydemeo** [comment]
https://github.com/ColumPaget/libUseful/issues/1

**Comment by EricFromCanada** [comment]
Neat. I've also found a way to enable SSL using `libressl`, which slightly increases the number of sites that the released version works with (cf. https://github.com/ColumPaget/Movgrab/issues/3).

**Pull request closed without merging**
