### PR TITLE
libdap: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by chenrui333**
See #134251.

### CODE REVIEW

**Comment by chenrui333** [comment]
`configure: error: Cannot determine DODS XDR integer sizes`

**Comment by carlocab** [comment]
Looks like https://bugs.gentoo.org/638494

**Comment by Bo98** [comment]
Error is a little confusing but it makes more sense given the:

```
configure: WARNING: Cannot locate library containing xdr functions.
```

Needs a `depends_on "libtirpc"` on Linux.

**Comment by carlocab** [comment]
```
  checking for xdr_void in -l-L/home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.3/lib -ltirpc... no
  checking for xdr_uint32_t in -l-L/home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.3/lib -ltirpc... no
  checking for xdr_u_int32_t in -l-L/home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.3/lib -ltirpc... no
  checking for xdr_uint in -l-L/home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.3/lib -ltirpc... no
  checking for xdr_u_int in -l-L/home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.3/lib -ltirpc... no
  configure: error: Cannot determine DODS XDR integer sizes
```
Seems to be mishandling the flags from `pkg-config`.

**Comment by Bo98** [comment]
https://github.com/OPENDAP/libdap4/pull/228

**Comment by cho-m** [comment]
Do we want to patch build scripts?

Could also temporarily override `TIRPC_LIBS` to allow current logic to work (since superenv should handle `-L` paths already).

**Review by carlocab — APPROVED** [review]

**Pull request merged**
