### PR TITLE
trunk 0.14.0

### PR DESCRIPTION
**Pull request by thedodd**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by thedodd** [comment]
Transient CI error: https://github.com/Homebrew/homebrew-core/pull/85597/checks?check_run_id=3654572452 Just needs a restart.

**Comment by chenrui333** [comment]
```
Caused by:
  failed to download from `https://crates.io/api/v1/crates/unicase/2.6.0/download`

Caused by:
  [18] Transferred a partial file (transfer closed with 20841 bytes remaining to read)
```

**Comment by thedodd** [comment]
@chenrui333 @carlocab I've seen this sort of error take place with brew CI before. The CI pipeline should just be restarted.

**Comment by thedodd** [comment]
Our ubuntu-latest linux build for this release: https://github.com/thedodd/trunk/runs/3654373998?check_suite_focus=true

**Comment by carlocab** [comment]
I've already restarted this twice. Let's try again, but it really just makes more sense to wait for the fix for this issue in today's `curl` release.

**Comment by thedodd** [comment]
Thanks for the info @carlocab .

**Review by carlocab — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
