### PR TITLE
citus 8.3.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
09:17:35 selecting dynamic shared memory implementation ... posix
09:17:35 creating configuration files ... ok
09:17:35 running bootstrap script ... 2019-08-09 14:17:33.831 BST [53819] FATAL:  could not create shared memory segment: No space left on device
09:17:35 2019-08-09 14:17:33.831 BST [53819] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
09:17:35 2019-08-09 14:17:33.831 BST [53819] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
09:17:35 	The PostgreSQL documentation contains more information about shared memory configuration.
09:17:35 child process exited with exit code 1
09:17:35 initdb: removing data directory "/private/tmp/citus-test-20190809-53760-tgvskq/test"
09:17:35 Error: citus: failed

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
The CI error is documented in #43142.

**Comment by alebcay** [comment]
CI error should be fixed now. @BrewTestBot test this please.

**Comment by chenrui333** [comment]
20:27:41 ==> brew doctor
20:27:42 ==> FAILED
20:27:42 Please note that these warnings are just used to help the Homebrew maintainers
20:27:42 with debugging if you file an issue. If everything you use Homebrew for is
20:27:42 working fine: please don't worry or file an issue; just ignore this. Thanks!
20:27:42 
20:27:42 Warning: Broken symlinks were found. Remove them with `brew cleanup`:
20:27:42   /usr/local/lib/libfuseprivate.0.dylib
20:27:42   /usr/local/lib/libfuseprivate.dylib
20:27:42 
20:27:42 ==> brew --env

**Comment by chenrui333** [comment]
Re-kick in a new build.

**Comment by chenrui333** [comment]
good for the merge now.

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Pull request closed without merging**
