### PR TITLE
librsvg 2.42.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Review by queengooborg — APPROVED** [review]

**Comment by RandomDSdevel** [comment]
@tschoonj, @vinyldarkscratch, and/or @fxcoudert:  For _some_ odd reason, my machine seems to think this PR introduced a dependency cycle between `librsvg.rb` and `rust.rb` even though, _looking_ at it, the latter doesn't seem to _have_ a dependency on the former declared in it…  _Whatever_ the reason, _that's **stragne!**_  In _any_ case, I'm going to try some more troubleshooting tactics beyond what I've already gone through here on my end before I file an issue, and those will also have to wait until I finish filing _another_ issue I'm currently collecting logs for (_boy_, when it _rains_, it definitely _pours_ for me…_grrrrr._)  Hopefully it's probably just something wonky to do with my local configuration and/or odd Homebrew usage tendencies, but I'm not exactly looking forward to debugging this (on top of libRSVG and Rust not liking at the moment, their antics are blocking an ImageMagick upgrade for me, the scurvy dogs.)  

P. S.:  Please pardon the scathing rhetoric, folks; I'm just a _bit_ peeved at computers in general at the moment, but it'll pass…; deep breaths, _deep_ breaths…  (_Takes some._)

**Comment by RandomDSdevel** [comment]
@tschoonj, @vinyldarkscratch, and/or @fxcoudert:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Never mind, I found the source of Rust's dependency on libRSVG:  it's through its formula's `--with-llvm` option (I was trying to avoid waiting for Homebrew to finish building Rust's vendors LLVM since I already have a copy of the compiler toolchain suite installed, you see)…and I have Homebrew's LLVM built and installed with its formula's `--with-graphviz` option and my Homebrew copy of Graphviz built and installed with its formula's `--with-librsvg` option.  Then libRSVG tries to pull in Rust again since the former now requires the latter, and…Homebrew makes itself a bit dizzy.  _Fun._  I think I'll ask what exactly I should do about this as a continuation of this discussion on the project Discourse, quoting the stuff I've posted here, so that I don't bloat this PR discussion thread further.

**Comment by RandomDSdevel** [comment]
@tschoonj, @vinyldarkscratch, and/or @fxcoudert:  As the last peep I intend to make here (though I might be persuaded otherwise if any of _really_ need a reply from me here on/about something) bond pointing toward the Discourse thread I said I'd start, I just wanted to leave a heads up:  I think I'm going to save _this_ mess for tomorrow, so said thread likely won't appear until some time tomorrow.

**Comment by tschoonj** [comment]
Not sure what the best course of action is here. You ran into trouble because of three librsvg dependencies that were built with `:optional` dependencies, which is not going to be a very commonly observed scenario... How about removing the `--with-llvm` option from the `rust` formula?

**Comment by RandomDSdevel** [comment]
@tschoonj:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If you mean to say that's what you propose globally for all users of Homebrew Core, then that would only be a solution until Rust finishes getting all of its LLVM patches upstreamed, after which the language's in-tree copy of the compiler toolchain suite would likely go away.  If you mean to suggest that I simply attempt a build of Rust without `--with-llvm` _locally_, then I've tried that before and gotten a different error which I'll report separately.  Just for full preliminary disclosure, said issue appears to occur whether libRSVG takes care of its own dependencies and  triggers a Rust build all by itself when I just `brew upgrade` the former package only or I attempt to build Rust separately to satisfy this new libRSVG dependency beforehand.  This gives the impression that its independent of any difference between what happens when libRSVG's invokes its automated Rust build without `--with-racer` or when I have Homebrew build Rust separately `--with-racer` (I'd appreciate code completion, personally.)

**Comment by RandomDSdevel** [comment]
@tschoonj:  [Here](https://discourse.brew.sh/t/librsvg-rust-circular-dependency-issue/1623), finally, is that Discord thread I promised.  We can continue discussion there.  In the meantime, I'll start putting together an issue report for Rust failing to build without `--with-llvm` on my system.

**Comment by RandomDSdevel** [comment]
@tschoonj:  As I note a bit too exasperatedly [here](https://discourse.brew.sh/t/librsvg-rust-circular-dependency-issue/1623/3?u=randomdsdevel), another attempt of mine to build Rust without `--with-llvm` actually _succeeded_, funnily, crazily, and inexplicably enough, so I guess I _won't_ be submitting that issue report…_grumbles about the irascibility of decade-old electronics…_

**Pull request closed without merging**
