### PR TITLE
Changed licenses and removed build runtime check

### PR DESCRIPTION
**Pull request by mkleinschnitker**
- changed license for geoip, git-gui, gzip, osxutils handbrake and rsync
- removed "build runtime check" for geoip

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @mkleinschnitker.

How were you able to determine that these are all `-or-later` as opposed to `-only`? Note that *GPL licenses often contain the text "or (at your option) any later version" in the boilerplate, even though the software itself isn't licensed under (say) GPLv2+, but is instead GPLv2-only.

**Comment by mkleinschnitker** [comment]
I referenced to the linked license on the GitHub pages. 

I wasn't aware, that the license text is just boilerplate.

Please give ne some time to investigate the licenses again.

**Comment by carlocab** [comment]
Yes, it's a bit misleading. I usually try to check the source headers for an indication of the license. Searching for the words "license" or "at your option" in the GitHub repo is usually informative.

**Comment by mkleinschnitker** [comment]
Hi @carlocab, 

just for clarification. I found the following sequence in one of the source files of gzip

```
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3, or (at your option) any later version.
```

It sounds to me as if the -or-later-option applies, doesn't it?

**Comment by carlocab** [comment]
It means that particular source file is GPLv3+. It'd be useful to check if the same thing appears in the others.

**Comment by mkleinschnitker** [comment]
So, I checked all source files in the repos.

- **geoip**: some files are LGPLv2.1+, some files do no have a license annotation, some file have a different copyright annotation
- **git-gui**: no source file has a GPLv2 annotation, most of the file have a copyright annotation or no license text
- **gzip**: all source files are GPLv3+
- **osxutils**: most of the files don't have a license text, all files with a license text are GPLv2+
- **handbrake**: the license text in source headers is GPLv2-only
- **rsync**:  all source files are GPLv3+

I think only with gzip and rsync the license change to GPLv3+ is ok. Handbrake should be changed to GPLv2-only. 
I am unsure about the other three formulas. What is the correct way here?

**Comment by carlocab** [comment]
Thanks very much for your work on this. Let me look into geoip, git-gui, and osxutils.

However, I would guess that git-gui should have the same license as git, which `GPL-2.0-only`.

**Comment by carlocab** [comment]
I think `geoip` is `LGPL-2.1-or-later`. Its own source files (e.g. `apps/geoiplookup.c`, `lib/GeoIP.c`) indicate this license, whereas the ones that don't are build scripts that are used to build the software, but aren't actually part of the software itself.

I'll check on the other two soon.

**Comment by mkleinschnitker** [comment]
Thanks for your support. 
I´ll make the changes on the formula files after your final feedback.

**Comment by carlocab** [comment]
For `git-gui`, I think we can just follow `git`'s license. I'm still unsure about `osxutils`.

Do you mind filing an issue on their repo to clarify whether their license is GPLv2 or GPLv2+? It may help to mention that the identifier `GPL-2.0` is deprecated. See the later half of https://spdx.org/licenses/, or https://www.gnu.org/licenses/identify-licenses-clearly.en.html.

**Comment by mkleinschnitker** [comment]
So we currently have the following interim status: 

- **geoip**: `LGPL-2.1-or-later`
- **git-gui**: `GPL-2.0-only`
- **gzip**: `GPLv3+`
- **osxutils**: unclear, issue created in osxutils repo
- **handbrake**: `GPLv2-only`
- **rsync**: `GPLv3+`

Regarding osxutils, I am unsure if this will be successful because the last update was 3 years ago. 
Is it possible to implement part of my PR (everything without osxutils)?

**Comment by carlocab** [comment]
Yes. You can do `git rebase -i HEAD~3`, then drop the commit that modifies `osxutils` (just replace `pick` with `drop` when `git` opens your editor). Then do `git push --force`.

**Comment by mkleinschnitker** [comment]
I´m not sure, if I did it the right way, but I´ve pushed the commits with the new license labels written here (https://github.com/Homebrew/homebrew-core/pull/73102#issuecomment-798849596)

**Comment by carlocab** [comment]
Thanks. You actually needed to make sure there's only one commit per formula modified. Fixing that is a little complicated, so let me help you with it.

**Comment by mkleinschnitker** [comment]
Thanks. 
One question for my new PR.  
Is it better to create a separate PR for each change to a formula or is it better to combine changes to several formulas?

**Comment by carlocab** [comment]
You can combine changes for separate formula, but you need to keep it to one-commit-per-formula (and one-formula-per-commit). Being comfortable with `git rebase` is essential for when you need to make changes with that.

**Review by carlocab — APPROVED** [review]
Thanks again, @mkleinschnitker.

**Pull request merged**
