### PR TITLE
wine 1.9.21 (devel)

### PR DESCRIPTION
**Pull request by tobbi**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by AlexanderNeilson** [comment]
Hi Team

This appears to be Jenkins terminating the build after 61 Minutes on Sierra.

I don't usually see wine take that long to build on my machines however I see El Cap also built in 60 minutes and succeeded so possibly the general spare cycles on the Jenkins test box.

One part of this may be to either find out a reason for slow compilation to try avoid hitting the timeout, that should help avoid a few delays.

The second thing seems to be that despite this change being to the devel part of the formula (not stable) Jenkins still built stable. Critically:
* Is there something we could code / change to allow Jenkins to build the changed part of the formula and not always stable?
* What changed between this and the other day when this formula (stable) built correctly and was accepted on your previous pull request?

Regards
Alexander

**Comment by MikeMcQuaid** [comment]
> Is there something we could code / change to allow Jenkins to build the changed part of the formula and not always stable?

I think we always want to build both as development changes can often break those in stable.

> What changed between this and the other day when this formula (stable) built correctly and was accepted on your previous pull request?

Probably just entropy. I've requeued the CI.

**Comment by tobbi** [comment]
Requeueing didn't seem to have worked. It's still aborting after roughly an hour.

**Comment by AlexanderNeilson** [comment]
Can an attempt be tried either with a longer timeout in the system doing a hard kill in general? Or a single time override for this build.

Apologies Mike, I may have misunderstood the build process, just seeing the line / residual building stable but not seeing the devel step. (My worry was around not catching failures with the devel). But this could also explain the longer than I expected build time.

It does appear that the issue is a timeout of some overall time limit in the Jenkins build system killing it. Obviously there could be a risk with extending systemwide timeout for builds and would be great to have the builds complete faster but also there could be an issue with managing individual exceptions / overrides if there is even an option to extend the timeout on a job by job basis.

Regards
Alexander

**Comment by MikeMcQuaid** [comment]
> overrides if there is even an option to extend the timeout on a job by job basis.

I've requeued this with a longer timeout CC @ilovezfs

**Comment by tobbi** [comment]
This appears to have worked. Can this be merged?

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew and sorry for the delay! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
