### PR TITLE
gputils 1.5.0-rc2 (devel)

### PR DESCRIPTION
**Pull request by ilovezfs**
~~needed to patch two -Wreturn-type errors~~
fixed in rc2

### CODE REVIEW

**Comment by ilovezfs** [comment]
Woo hoo upstream merged the patch https://sourceforge.net/p/gputils/code/1277/tree//trunk/gputils/libgputils/gpcoffgen.c?diff=50279599fd48f80fdc30d8c5:1276

**Comment by DomT4** [comment]
👍 whenever you're 😸

**Comment by ilovezfs** [comment]
also clang-specific warnings reported upstream: https://sourceforge.net/p/gputils/bugs/290/

**Comment by DomT4** [comment]
Nice, that's impressive dedication 😺

**Pull request closed without merging**
