### PR TITLE
libcotp 3.0.0 (new formula)

### PR DESCRIPTION
**Pull request by Un1Gfn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

#159059 is [libcotp](https://github.com/paolostivanin/libcotp)

#159058 is [otpclient](https://github.com/paolostivanin/OTPclient)

1. CI failed with error *GitHub repository not notable enough*, but this one is a dependency of otpclient, and otpclient has 406 stars and should be "notable enough". Is there a way to skip this check so that the CI can proceed and look for some *actual* build errors?

1. It seems possible to work around the aforementioned error by bundling libcotp and otpclient together into 1 formula. But it would break the [no bundling](https://docs.brew.sh/Acceptable-Formulae#stuff-that-requires-vendored-versions-of-homebrew-formulae) rule and you might eat me.

1. otpclient will never succeed in CI because it can never find the dependency libcotp unless libcotp is accepted and merged into homebrew-core.

1. I have been repeatedly closing and opening new PR because there is a *one formula per commit; one commit per formula* rule [here](https://docs.brew.sh/Formula-Cookbook#push). If I add a new commit to an existing PR instead of opening a new one it would go against this rule since it would leave more than 1 comment in this PR 

1. I am confused. Could somebody help me?

### CODE REVIEW

**Comment by Un1Gfn** [comment]
CI failed with error *GitHub repository not notable enough*, but this one is a dependency of #159058, which [is notable enough](https://github.com/paolostivanin/OTPClient)

What am I supposed to do?

**Comment by SMillerDev** [comment]
> I have been repeatedly closing and opening new PR because there is a one formula per commit; one commit per formula rule [here](https://docs.brew.sh/Formula-Cookbook#push). If I add a new commit to an existing PR instead of opening a new one it would go against this rule since it would leave more than 1 comment in this PR

So amend to the commit

**Comment by Un1Gfn** [comment]
> > I have been repeatedly closing and opening new PR because there is a one formula per commit; one commit per formula rule [here](https://docs.brew.sh/Formula-Cookbook#push). If I add a new commit to an existing PR instead of opening a new one it would go against this rule since it would leave more than 1 comment in this PR
> 
> So amend to the commit

It seems that I need to force-push to my branch after an amend. Does force-push trigger CI the same way as normal push?

**Comment by Un1Gfn** [comment]
Thanks. I shall make this PR a draft until I manage to fix things mentioned in the review of #159058.

**Pull request closed without merging**
