### PR TITLE
needle 0.9.0

### PR DESCRIPTION
**Pull request by neakor**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you change the test to something that actually tests functionality? Version tests rarely give a good indication of state of the build.

**Comment by neakor** [comment]
@SMillerDev unfortunately that's not possible, since test currently doesn't support reaching out of the sandbox. Needle uses SourceKit which is another process outside of the test sandbox. Please refer to the original PR for details https://github.com/Homebrew/homebrew-core/pull/34752

**Comment by SMillerDev** [comment]
In that case could you add the check for version output back?

**Comment by neakor** [comment]
@SMillerDev does that make sense though? I removed it since the `brew-update-formular-pr` script won't update the test. So we would have to manually update the test every time we publish a new version. Is that more desired? After all, that assert doesn't do much anyways.

**Comment by SMillerDev** [comment]
You can check if it matches `#{version}` which would work with bump-formula

**Comment by neakor** [comment]
Thanks for the suggestion @SMillerDev I updated the PR.

**Comment by neakor** [comment]
@SMillerDev Did I get the syntax wrong here? The build is failing on the assertion.

**Comment by SMillerDev** [comment]
I think it needs to be quoted as well.

**Comment by neakor** [comment]
@SMillerDev Hmmm still not working. I can't seem to find an example anywhere.

**Comment by neakor** [comment]
@SMillerDev can you please help here?

**Comment by SMillerDev** [comment]
@brewtestbot test this please

**Comment by neakor** [comment]
@BrewTestBot test this please

**Comment by neakor** [comment]
Looks like a CI failure unrelated to the test itself.

**Comment by neakor** [comment]
@SMillerDev looks like this is good to merge :)

**Comment by fxcoudert** [comment]
Thanks @neakor

**Pull request closed without merging**
