### PR TITLE
xeora 1.0.17506 (new formula)

### PR DESCRIPTION
**Pull request by freakmaxi**
- [ x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Hi,

This is the brew formula addition for Xeora Web Development Framework Command-line Interface

http://www.xeora.org
https://github.com/xeora

Thanks

### CODE REVIEW

**Comment by fxcoudert** [comment]
Homebrew formulas must be open-source and built from source. Please see our [documentation](https://docs.brew.sh/Acceptable-Formulae.html) for more information about acceptable formulas.

**Comment by freakmaxi** [comment]
this formula requires .NET Core as a dependency to able to build. But .NET Core formula is not there. So should I create a formula to build the .NET Core and put that formula as a dependency to my project to build it from Xeora source?

**Comment by fxcoudert** [comment]
We have Mono, does that work?

**Comment by freakmaxi** [comment]
honestly, I don't know. I didn't test it using Mono. Let me test it, if it works, I'll update my formula according to the result but if it won't work, what should be the solution?

**Comment by freakmaxi** [comment]
Okay, I checked. It is working to compile. But the problem is not compiling. I also need dotnet cli to make external calls. So any idea?

**Comment by fxcoudert** [comment]
If you really need to install binaries, a Homebrew Cask is the right way to distribute

**Comment by freakmaxi** [comment]
Okay, I'll take a look at that. thank you! 👍

**Pull request closed without merging**
