### PR TITLE
Create yarn@latest.rb

### PR DESCRIPTION
**Pull request by JacopKane**
For nightly builds of Yarn

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Clever idea but we don't use @ formulae for this. See https://github.com/Homebrew/brew/blob/master/docs/Versions.md

This would be the purview of a `--HEAD` spec for the main `yarn` formula, which was previously removed in https://github.com/Homebrew/homebrew-core/issues/16083 as no one was using it and it was broken.

**Comment by JacopKane** [comment]
@ilovezfs cheers, maybe I'll try to add explicitly tagged RC versions later, although couldn't make this version aliasing work somehow yet :)

**Comment by ilovezfs** [comment]
tagged RCs go in `devel do`

**Comment by JacopKane** [comment]
Wow, I didn't know that, cheers

**Comment by ilovezfs** [comment]
@JacopKane you're welcome. Yeah that's what `brew install --devel` ties into.

**Pull request closed without merging**
