### PR TITLE
riak: use secure homepage and update it (redirect to http)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

also:
- use brew openssl to fix CI failure

### CODE REVIEW

**Comment by apjanke** [comment]
Since we're changing the openssl linkage, this one will need a `revision` bump as well, so users pick up the new installation process or bottle. Could you add that, and include "use brewed openssl" in the commit summary and PR headline?

Maintainers: let this one run through test-bot. It's an actual build change, and will need a new bottle.

**Comment by xu-cheng** [comment]
This is a binary formula. So `depends_on "openssl"` should do little help. My suggestion is either changing this formula to build from source or moving to `homebrew/binary`.

**Comment by apjanke** [comment]
Oh, darn. Thanks for catching that, xu-cheng.

Riak's written in erlang so we can compile it. Let's change it to [build from source](http://docs.basho.com/riak/kv/2.1.4/setup/installing/source/).

**Comment by vszakats** [comment]
Adding a revision and proper commit text is fine and thanks for the reminders, but indeed this is a binary package, so I'd vote to just close this PR and let these issues be handled separately. The homepage update is the lightest case, because https is redirected to http anyway, so not much is lost.

**Comment by vszakats** [comment]
Removed the useless `openssl` dependency.

**Comment by vszakats** [comment]
Would you prefer merge this only for the homepage, or may I close?

**Comment by apjanke** [comment]
I'll take this for the homepage update. Thanks!

**Comment by apjanke** [comment]
Merged. Thanks for all these contributions!

**Pull request closed without merging**
