### PR TITLE
platformio 6.1.6

### PR DESCRIPTION
**Pull request by ivankravets**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

* Added support for Python 3.11
* Added a new [name](https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/generic/description.html) configuration option to customize a project name ([pull #4498](https://github.com/platformio/platformio-core/pull/4498))
* Made assets (templates, ``99-platformio-udev.rules``) part of Python's module ([issue #4458](https://github.com/platformio/platformio-core/issues/4458))
* Updated [Clang-Tidy](https://docs.platformio.org/en/latest/plus/check-tools/clang-tidy.html) check tool to v15.0.5 with new diagnostics and bugfixes
* Removed dependency on the "zeroconf" package and install it only when a user lists mDNS devices (issue with zeroconf's LGPL license)
* Show the real error message instead of "Can not remove temporary directory" when ["platformio.ini"](https://docs.platformio.org/en/latest/projectconf.html) configuration file is broken ([issue #4480](https://github.com/platformio/platformio-core/issues/4480))
* Fixed an issue with an incorrect test summary when a testcase name includes a colon ([issue #4508](https://github.com/platformio/platformio-core/issues/4508))
* Fixed an issue when [extends](https://docs.platformio.org/en/latest/projectconf/sections/env/options/advanced/extends.html) did not override options in the right order ([issue #4462](https://github.com/platformio/platformio-core/issues/4462))
* Fixed an issue when [pio pkg list](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_list.html) and [pio pkg uninstall](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_uninstall.html) commands fail if there are circular dependencies in the [library.json](https://docs.platformio.org/en/latest/manifests/library-json/index.html) manifests ([issue #4475](https://github.com/platformio/platformio-core/issues/4475))

### CODE REVIEW

**Comment by ivankravets** [comment]
How does CI work here?  I see in the log `6.1.5` version, where the latest is 6.1.6 and `zeconf` was removed. Is it possible to use real 6.1.6 tag?

**Comment by SMillerDev** [comment]
> How does CI work here? I see in the log 6.1.5 version, where the latest is 6.1.6 and zeroconf was removed. Is it possible to use a real 6.1.6 tag?

Well, your pull request didn't change the package source. When you update that I guess it'll work.

**Comment by ivankravets** [comment]
Sorry, I'll create a new PR.

**Comment by ivankravets** [comment]
Done in https://github.com/Homebrew/homebrew-core/pull/121330

**Pull request closed without merging**
