### PR TITLE
jsoncpp 1.7.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
If you're feeling as anal as me you could split that ridiculously long `cmake_args` line, but 👍.

**Comment by ilovezfs** [comment]
>as anal as me

Pretty sure I'm actually "worse," truth be told.

**Comment by ilovezfs** [comment]
@DomT4 Looks like I found the person responsible for approving that long line: https://github.com/Homebrew/legacy-homebrew/pull/50040#issuecomment-199631469

**Comment by DomT4** [comment]
@ilovezfs Yeah, it was me. I remember, there was a lot of hassle around getting that PR shipped and I was anxious to just be done with it 😅.

**Comment by ilovezfs** [comment]
Obviously you should be deeply ashamed. I think ten lashes is probably fair.

**Comment by DomT4** [comment]
Wednesday morning has been hectic enough already, let's reschedule 😇.

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
