### PR TITLE
lexido 1.4.2

### PR DESCRIPTION
**Pull request by Emberzo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by swayz8148** [comment]
I tried doing `brew bump-formula-pr --url=https://github.com/micr0-dev/lexido/archive/refs/tags/v1.4.2.tar.gz --sha256=fb1c6e750ce1dc30d2a6cd461cf6917197191a3546e5bf37ed1eadbf8bb922e2 lexido` but it said lexido is part of the autobump list so im making this to update it again

**Comment by chenrui333** [comment]
@swayz8148 yeah, this is part of autobump list so no need to do such PRs manually.

**Comment by chenrui333** [comment]
also this is a duplicate of #172129? closing for now.

**Comment by swayz8148** [comment]
yea i was gone for a few days and seen the git repo got updated so i tried to auto bump didn't know what it meant but part of autobump already and didn't check if it was already updated sorry

**Pull request closed without merging**
