### PR TITLE
lean 3.46.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
waiting this line to be updated, https://github.com/leanprover-community/mathlib/blob/master/leanpkg.toml#L4

**Comment by chenrui333** [comment]
Should be good now per https://github.com/leanprover-community/mathlib/pull/15993

**Comment by Porkepix** [comment]
> Should be good now per [leanprover-community/mathlib#15993](https://github.com/leanprover-community/mathlib/pull/15993)

The first link you provided hasn't seen lean's version changed, though?

**Comment by chenrui333** [comment]
> leanprover-community/mathlib#15993

my mistake, looks like that PR did not get merged, gonna chime in there.

**Comment by fanninpm** [comment]
https://github.com/leanprover-community/mathlib/pull/15994 has been merged, so this can go ahead.

**Comment by chenrui333** [comment]
Thanks @fanninpm!

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
