### PR TITLE
glib 2.74.3

### PR DESCRIPTION
**Pull request by triallax**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by fxcoudert** [comment]
Not sure what cancelled the linux build. The macOS errors appear network-related, or known unrelated issues.

**Comment by chenrui333** [comment]
need a rerun

**Comment by cho-m** [comment]
On side note, `glib` dependents may fail on Linux CI due to Homebrew's Docker + glibc version combo. Not sure if we want to merge workaround (#112473) to clean up those failures.

**Comment by chenrui333** [comment]
> On side note, some `glib` dependents may fail on Linux CI due to Homebrew's Docker + glibc version combo. Not sure if we want to merge workaround (#112473) to clean up those failures.

why didn't we pursue that PR?

**Comment by danielnachun** [comment]
It's probably good to get in put from @Homebrew/core on adding the fix I opened in https://github.com/Homebrew/homebrew-core/pull/112473 to fix these failures.  We'll be able to drop it when the Docker fix makes its way into GitHub Actions.

**Comment by chenrui333** [comment]
> It's probably good to get in put from @Homebrew/core on adding the fix I opened in #112473 to fix these failures. We'll be able to drop it when the Docker fix makes its way into GitHub Actions.

@danielnachun can you also link the docker upstream issue tracker for that PR?

**Review by cho-m — APPROVED** [review]

**Comment by cho-m** [comment]
Will trigger merge. Failures don't seem related (not too sure on `teku` failure but it passed everywhere else):
- `fourstore` (Linux) - #109825 
- `abcl` (11) - test-bot issue
- `torchvision` (13) - test-bot issue
- `trino` (13) - timeout? `Query 20221205_192718_00000_nqjew failed: Trino server is still initializing`
- `teku` (13) - don't know. Doesn't seem related based on quick glance.

**Pull request closed without merging**
