### PR TITLE
formulae: use new bottle syntax

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR modifies all formulae with bottles to use the new bottle syntax from https://github.com/Homebrew/brew/pull/10453.

To minimize mixing old and new bottle syntax, @jonchang and I will plan on merging this PR (as well as handling the linuxbrew/core merge and the brew PR) in around 24 hours when homebrew/core is relatively quiet.

These changes shouldn't affect any functionality. The changes are only moving existing bottles to a new syntax (which is already fully supported and partially in use in homebrew/core). If issues pop up where bottles don't seem to working anymore, feel free to ping me and I can take a look to try to see where the issue is. While I'm not expecting any issues (certainly not widespread panic and chaos), it's possible that I missed a few edge cases with the auto-correct that will need to be looked at.

CC: @homebrew/core

### CODE REVIEW

**Comment by carlocab** [comment]
>The changes are only moving existing bottles to a new syntax

Perhaps it would be better to do this in a few batches over a few days/week? Unsure, but might be worth considering.

**Comment by iMichka** [comment]
> Perhaps it would be better to do this in a few batches over a few days/week? Unsure, but might be worth considering.

Yes, please, can we have a few batches. I expect some git conflicts when merging this to linux, and I would like to have 1 single massive commit to handle. Can we split this in blocks of 500 or less?

**Comment by jonchang** [comment]
There shouldn't be much of a merge conflict since we would do a style fix on both Linux and macOS followed by a regular core merge. I can handle this if you'd like.

**Comment by MikeMcQuaid** [comment]
> There shouldn't be much of a merge conflict since we would do a style fix on both Linux and macOS followed by a regular core merge. I can handle this if you'd like.

I'd really like this to get landed on the timescale planned by @rylan12 and @jonchang. It's a release blocker for 3.0.0. I trust them both to be able to do this in a single merge.

**Review by MikeMcQuaid — DISMISSED** [review]

**Comment by fxcoudert** [comment]
@jonchang We can lock homebrew-core for an hour if it makes things easier

**Comment by Rylan12** [comment]
I want to do this in the way that makes the most sense for everyone and adds the least amount of work for other maintainers who didn't sign up to handle a 5,000 file PR, so I'm happy to adjust this PR as needed.

@jonchang let me know what the best format for this PR is. I'm happy to split the commits into smaller chunks or even one-commit-per-formula if that's preferred for your workflow.

Would it be helpful for me to open a similar PR in linuxbrew/core in preparation?

---

If it would be helpful, we can also manually modify a few bottle blocks here and in linuxbrew/core to test and make sure the merge process is seamless. Just let me know what's best.

**Comment by MikeMcQuaid** [comment]
> I want to do this in the way that makes the most sense for everyone and adds the least amount of work for other maintainers who didn't sign up to handle a 5,000 file PR, so I'm happy to adjust this PR as needed.

If you and @jonchang are doing the merges and we end up with Homebrew/brew, homebrew-core and linuxbrew-core all with green CI and the changes merged: I don't think the implementation matters beyond your personal preferences.

> Would it be helpful for me to open a similar PR in linuxbrew/core in preparation?

Yes, makes sense to me 👍🏻 

> If it would be helpful, we can also manually modify a few bottle blocks here and in linuxbrew/core to test and make sure the merge process is seamless. Just let me know what's best.

Will the style checks all work as expected with that? If so, that's not a bad idea to do before the PR is merged. I'd suggest picking a formula using the new `cellar: :any` format in both homebrew-core and linuxbrew-core and commit to their `master` branches for testing.

**Comment by carlocab** [comment]
>one-commit-per-formula

Not sure it's a good idea here. I think it'll make vanilla `git log` basically unusable if all the commits you see for a while are just bottle-syntax migration commits.

**Comment by Rylan12** [comment]
> > If it would be helpful, we can also manually modify a few bottle blocks here and in linuxbrew/core to test and make sure the merge process is seamless. Just let me know what's best.
> 
> Will the style checks all work as expected with that? If so, that's not a bad idea to do before the PR is merged. I'd suggest picking a formula using the new `cellar: :any` format in both homebrew-core and linuxbrew-core and commit to their `master` branches for testing.

I believe so (although I could be wrong). If not, though, that's an indication that something is awry with the anticipated process. There aren't any style rules currently being applied to the bottle blocks (that I know of) so (I think 🤞) it should be fine.

I'll need a Linux person to be around to do this with me as I can't do the Linux merges, so if one is around and wants to test it out feel free to ping me on Slack (that's just a little faster than on GitHub).

**Comment by Rylan12** [comment]
Actually, since the `tap_syntax` check is failing, we know that there will be an issue. It looks like it's a line-length error.

If we can, we should probably just disable that cop for the bottle block.

**Comment by carlocab** [comment]
> If we can, we should probably just disable that cop for the bottle block.

This was supposed to have been done in https://github.com/Homebrew/brew/pull/10452

**Comment by iMichka** [comment]
> This was supposed to have been done in Homebrew/brew#10452

Yes, but only lines which had a cellar information, not for the others. I wanted to be more general initially, but we thought being specific was enough; https://github.com/Homebrew/brew/pull/10452#discussion_r566326669

**Pull request merged**
