### PR TITLE
faas-cli 0.9.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
image

**Comment by chenrui333** [comment]
13:50:04 ==> /usr/local/Cellar/faas-cli/0.9.0/bin/faas-cli deploy -yaml test.yml 2>&1
13:50:04 ==> /usr/local/Cellar/faas-cli/0.9.0/bin/faas-cli template pull 2>&1
13:50:04 ==> /usr/local/Cellar/faas-cli/0.9.0/bin/faas-cli new --list
13:50:04 ==> /usr/local/Cellar/faas-cli/0.9.0/bin/faas-cli deploy -yaml test.yml
13:50:04 Error: faas-cli: failed
13:50:04 An exception occurred within a child process:
13:50:04   Test::Unit::AssertionFailedError: <0> expected but was
13:50:04 <1>.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Pull request closed without merging**
