### PR TITLE
ckan 1.26.2

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Created upstream issue at https://github.com/KSP-CKAN/CKAN/issues/2830.

**Comment by HebaruSan** [comment]
See #35848. That error started happening with a new version of mono, not the new version of CKAN.

**Comment by alebcay** [comment]
Thanks for your input. In this case, it may be time to remove ckan from Homebrew.

**Comment by alebcay** [comment]
This should be fixed after https://github.com/Homebrew/homebrew-core/pull/41728 is merged.

**Comment by alebcay** [comment]
Closing this to just add these changes in with the `mono` pull request.

**Pull request closed without merging**
