### PR TITLE
Java: drop a couple options

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
:fire:

**Comment by DomT4** [comment]
Did check `portmidi` built fine without the patch locally & it did, so I'm assuming that has nothing to do with the CI failures for the older versions of macOS here.

**Comment by ilovezfs** [comment]
@DomT4 https://github.com/Homebrew/homebrew-core/pull/23736

**Comment by DomT4** [comment]
Ah, that bundle of joy. Thanks.

**Pull request merged**
