### PR TITLE
arangodb 3.11.1

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Trying some things out...

### CODE REVIEW

**Comment by cho-m** [comment]
Sadly no idea if there is way to workaround current failure:
```
  /tmp/arangodb-20230630-89543-1vkojor/ArangoDB-3.11.1/lib/Inspection/include/Inspection/Access.h:52:3: error: static assertion failed due to requirement 'detail::IsInspectable()'
    static_assert(detail::IsInspectable<TT, Inspector>());
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'll experiment with downgrading LLVM and/or switching to GCC. Upstream has stated they will not support compiler versions outside of https://github.com/arangodb/arangodb/blob/v3.11.1/VERSIONS 

Afterward, we can decide whether to go this route or to deprecate.

**Comment by Bo98** [comment]
> Upstream has stated they will not support compiler versions outside of https://github.com/arangodb/arangodb/blob/v3.11.1/VERSIONS

Thing is that it fails across all macOS versions. Using LLVM 12, 14 and 15 based compilers. It's tricky to track down why but I'll

Linux error is however caused by us using GCC 10 here, which is too old. We should try 11 again.

**Comment by cho-m** [comment]
> Thing is that it fails across all macOS versions. Using LLVM 12, 14 and 15 based compilers. It's tricky to track down why but I'll see if I can see anything.

We are using brewed `llvm` so LLVM 16. In addition to original reason, upstream has added a version checker that will reject AppleClang (https://github.com/arangodb/arangodb/blob/v3.11.1/cmake/CheckCompilerVersion.cmake)

> Linux error is however caused by us using GCC 10 here, which is too old. We should try 11 again.

Yeah. Looks like minimum GCC 11.2 is needed for `std::atomic<T>::wait`. Will try default GCC 11.3 again, but may need to apply workaround patch if it hits bug.

**Comment by Bo98** [comment]
> > Thing is that it fails across all macOS versions. Using LLVM 12, 14 and 15 based compilers. It's tricky to track down why but I'll see if I can see anything.
> 
> We are using brewed `llvm` so LLVM 16. In addition to original reason, upstream has added a version checker that will reject AppleClang (https://github.com/arangodb/arangodb/blob/v3.11.1/cmake/CheckCompilerVersion.cmake)

Oh oops misread that.

**Comment by carlocab** [comment]
We should probably just deprecate this formula TBH. It had ~500 downloads in the past month (numbers based on GitHub Packages). I don't think that's worth the amount of CI/maintainer time this formula takes up. (Unless there actually is a maintainer that uses this formula and is willing to work on it.) I'm pretty sure it vendors all sorts of dependencies too.

CC @Homebrew/core for thoughts.

**Comment by cho-m** [comment]
> We should probably just deprecate this formula TBH.

That is fine with me. Upstream also sounds like they want us to deprecate/remove it as their response to any issues is to install their version.

> I'm pretty sure it vendors all sorts of dependencies too. 

Yeah, it does https://github.com/arangodb/arangodb/tree/devel/3rdParty which is part of reason build fails (V8 and Boost copies have issues with LLVM 16).

**Comment by p-linnane** [comment]
Agreed with deprecating it.

**Comment by MikeMcQuaid** [comment]
Agreed on deprecation 👍🏻

**Comment by p-linnane** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/135907 to deprecate.

**Pull request closed without merging**
