### PR TITLE
gomplate 3.1.0

### PR DESCRIPTION
**Pull request by hairyhenderson**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Note: the build will probably fail for the same reasons as #32405 😞

**Comment by fxcoudert** [comment]
Yes, I think we're stuck here until upx ships a new release. Sorry :(

**Comment by hairyhenderson** [comment]
@fxcoudert is it possible to revert UPX to 3.94 in homebrew until a new version is shipped? It's effectively busted for all macOS users from what I can tell...

**Comment by fxcoudert** [comment]
`upx` does work for some executables, it appears to be broken for go programs, but not other executables. We could consider patching `upx` if you can identify a specific commit in their history that fixes the issue.

Otherwise, probably the best option is to try and get gomplate not to compress its executable.

**Comment by hairyhenderson** [comment]
Ah, right - forgot that detail! Another option would be to add the fix as a patch to the UPX formula, similar to https://github.com/Homebrew/homebrew-core/blob/master/Formula/upx.rb#L18..L23

I could play with that as an option...

I really don't like the non-compressed option, because it's 5x larger. I also maintain a personal tap at https://github.com/hairyhenderson/homebrew-tap/ where I reference the "official" binary that I ship to GitHub Releases.

**Pull request closed without merging**
