### PR TITLE
tfenv: add curl to macos dependency list

### PR DESCRIPTION
**Pull request by stephengroat-dd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

see https://github.com/tfutils/tfenv/blob/3fcd913666d75b0fbd413d0abf7aa62db388d6ba/lib/helpers.sh#L81

### CODE REVIEW

**Review by iMichka — COMMENTED** [review]
Thanks! Note that this will use system curl on macOS, and brewed curl on Linux.

**Review by carlocab — COMMENTED** [review]
Homebrew itself requires an installation of `curl` to work, so `brew install tfenv` already guarantees a `curl` executable.

We only need this if the minimum version of `curl` required by Homebrew is too old, but this doesn't look to be the case.

**Comment by iMichka** [comment]
Should we close this PR then? Or is `uses_from_macos "curl"`, as it's already used in 144 other formula?

**Comment by carlocab** [comment]
Let's not make `curl` tests longer than necessary, please.

If we actually need a new `curl` then this is fine. If not then this just installs something users don't need and hurts our CI throughout.

**Comment by iMichka** [comment]
Let's close this then.

**Pull request closed without merging**
