### PR TITLE
xcodegen 2.28.0

### PR DESCRIPTION
**Pull request by yonaskolb**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yonaskolb** [comment]
Not sure why this is failing?

**Comment by yonaskolb** [comment]
Thanks @chenrui333!

**Comment by yonaskolb** [comment]
Will this mean it won't be available on linux?

**Comment by SMillerDev** [comment]
Not if it depends on macOS, no.

**Comment by chenrui333** [comment]
until we fix the linux build, this is a way to get the formula out sooner than later. :(

**Comment by chenrui333** [comment]
> Ok happy to merge I guess. Just so I understand, was the way the formula was before allowing for linux, but not anymore? Just confused, as looks like it was already restricting to macOS, but the original CI failed on a linux build. I don't use linux and am not familiar with how `depends_on` works.
> 
> > until we fix the linux build
> 
> To fix this does something need to be done in XcodeGen, the formula, or homebrew?

Can be done by any of us.

**Comment by SMillerDev** [comment]
So there was a successful Linux build at one time, but this version does not build on Linux. Therefore we can drop Linux support (since XCode does not work on Linux anyway).

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
