### PR TITLE
ghc@8.2: delete formula

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Related to #45514

Also see #50604

### CODE REVIEW

**Comment by Bo98** [comment]
Does any formulae use `ghc@8.2` still?

**Comment by SeekingMeaning** [comment]
Now that you mention it, I don't think so but let me check with a grep search.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you @SeekingMeaning!

**Review by zbeekman — APPROVED** [review]
LGTM

**Pull request closed without merging**
