### PR TITLE
ghr 0.12.0 (new formula)

### PR DESCRIPTION
**Pull request by danielbayley**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by danielbayley** [comment]
…

**Comment by danielbayley** [comment]
@commitay Is there a problem with this?

**Comment by sgerrand** [comment]
@commitay this formula would be useful to have in the Homebrew library.

**Comment by danielbayley** [comment]
Not stale…

**Comment by SMillerDev** [comment]
Could you make the test a bit more meaningful? Checking the version rarely tells you anything about the resulting install.

**Comment by danielbayley** [comment]
> Could you make the test a bit more meaningful? Checking the version rarely tells you anything about the resulting install.

@SMillerDev Do you have any examples or ideas here? The functionality of this utility is for easily cutting GitHub releases; don't really want to be doing that on the tests…

**Comment by igas** [comment]
@danielbayley the simpliest would be to try to do something and see it complains about wrong token or something.

**Comment by danielbayley** [comment]
~~~ ruby
test do
  ENV['GITHUB_TOKEN'] = nil
  args = "-username testbot -repository #{testpath} v#{version} #{Dir.pwd}"
  assert_match /token not found$/, shell_output("#{bin}/ghr #{args}")
end
~~~

@igas This is what I have so far… the problem is `assert_match`ing the multiline error output of the resultant failure; is that possible using only the RegEx?

**Comment by igas** [comment]
Thank you @danielbayley! You rock! 🤘🏼

**Pull request closed without merging**
