### PR TITLE
terrahub 0.2.33

### PR DESCRIPTION
**Pull request by eistrati**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Bumping up terrahub version to 0.2.33

### CODE REVIEW

**Comment by Moisan** [comment]
The latest version seems to be `0.2.33`. Could you bump to that version instead?

**Comment by eistrati** [comment]
@Moisan done

**Comment by Moisan** [comment]
You also need to update the sha256 to match this new version file.

**Comment by eistrati** [comment]
Closing this PR. Will open new one.

**Pull request closed without merging**
