### PR TITLE
workflows/tests: cache style cache

### PR DESCRIPTION
**Pull request by Bo98**
Might make it faster?

It currently takes up to 10 minutes. Will run this twice to see.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by Bo98** [comment]
Now takes 3 minutes.

I may look into optimising that further. Some of the slowness is from us iterating through the formula files three times - `brew readall`, `brew audit` and `brew generate-formula-api`.

**Comment by MikeMcQuaid** [comment]
Woohoo, great work here @bo98!

> Some of the slowness is from us iterating through the formula files three times - `brew readall`, `brew audit` and `brew generate-formula-api`, causing the merge queue to taking like 15 minutes to merge.

If these are all on Linux workers: could consider parallelising by having multiple jobs. Another, potentially bonkers, option to consider would be sticking all the formula files in a `tmpfs` for this case, if that speeds anything up?

**Comment by Bo98** [comment]
> Another, potentially bonkers, option to consider would be sticking all the formula files in a `tmpfs` for this case, if that speeds anything up?

I reckon it is more Ruby parsing overhead than file I/O.

One option is to maybe merge some of those. I still reckon we could merge API generation and readall into one. Having audit have a `--readall` could also make sense?

**Comment by MikeMcQuaid** [comment]
> One option is to maybe merge some of those commands. I still reckon we could merge API generation testing and readall into one. Having audit have a `--readall` could also make sense? Particular since `readall` is already modularised into its own file that can be called.

@Bo98 Yeh, they are all basically run in the same context for the same reasons so having an optional way of running them all at once makes sense to me, if it's faster. Also saves having multiple failures for the same underlying issues.

**Pull request merged**
