### PR TITLE
fastlane 2.189.0

### PR DESCRIPTION
**Pull request by joshdholtz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Same error as before:
```
==> brew audit fastlane --online --git --skip-style
==> FAILED
fastlane:
  * Binaries built for a non-native architecture were installed into fastlane's prefix.
    The offending files are:
      /opt/homebrew/Cellar/fastlane/2.189.0/libexec/gems/terminal-notifier-2.0.0/vendor/terminal-notifier/terminal-notifier.app/Contents/MacOS/terminal-notifier	(x86_64)
Error: 1 problem in 1 formula detected
```

**Comment by joshdholtz** [comment]
@carlocab Yeaaahhh, I didn't get a chance to fix yet 😔

**Comment by carlocab** [comment]
We can make the changes here. I'll fix it for you.

**Comment by joshdholtz** [comment]
@carlocab You are my hero 🥰

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
  NoMethodError: undefined method `/' for #<Array:0x00007fd8a92127d8>
```

**Comment by carlocab** [comment]
Oops, should be fixed now.

**Review by kortenkamp — APPROVED** [review]
This fixes the vendor binary problem, indeed. I do not see any issues here.

**Review by joshdholtz — COMMENTED** [review]
Yeaaahh, I would have not come to this same solution quickly at all 🙈 Thank you so much for fixing this for me!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
