### PR TITLE
Fix brew install clozure-cl --HEAD

### PR DESCRIPTION
**Pull request by dimitri**
Current head requires a newer CCL image.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
`Heap image is too new for this kernel.` on the stable version. You would need a `head do` block with the resource inside. But…

- if we have to track the latest devel image every time, this is likely to be broken often
- which would mean we should possibly remove head

**Comment by fxcoudert** [comment]
OK then. But it still needs to go inside a `head do` block, because right now it is making the build fail on Sierra and High Sierra.

**Comment by fxcoudert** [comment]
Closing this as no changes were made. Upstream needs to be encouraged to cut a new release that supports the latest macOS, or we will have to consider dropping the software from Homebrew core.

**Comment by dimitri** [comment]
CC @xrme

**Pull request closed without merging**
