### PR TITLE
Nift 2 3 11

### PR DESCRIPTION
**Pull request by n-ham**
- [y ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [y ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [y ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [y ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [y ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Please don't push merge commits. I've helped you get rid of yours. As I mentioned in your other PR, use `git rebase`, not `git merge`.

**Comment by n-ham** [comment]
I haven't used merge or rebase. I just forked and cloned the homebrew-core repo, created a new branch, added the changes, pushed to the fork and created a PR from github. I'm not quite sure where you mean to use rebase in there sorry? I've never really spent the time learning git beyond the basics sorry.

**Comment by carlocab** [comment]
You have this merge commit from your fork: https://github.com/Homebrew/homebrew-core/commit/41d3fdf113dc2e254a3e45218cae1de1d794aa7e

I don't know how you could've created a merge commit without `git merge`.

It might help to start with a clean fork for your next PR. i.e. When this one is merged, delete your fork from GitHub, and remove your fork from your remotes in your local homebrew-core repo. When you open a new PR, follow the instructions at https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.

**Comment by n-ham** [comment]
I just committed and pushed the files to a new branch from a fresh fork, then used GitHub to put in the PR. I have added that link to  a text file used for releasing new versions of Nift for future reference, cheers.

**Comment by carlocab** [comment]
The fork isn't fresh, because it has this commit: https://github.com/n-ham/homebrew-core/commit/41d3fdf113dc2e254a3e45218cae1de1d794aa7e

It might be a merge commit you've been carrying around in your local core repo. A `brew update-reset` should fix that. It'll make sure your local master branch is perfectly in sync with homebrew/core.

**Review by carlocab — APPROVED** [review]
Thanks, @n-ham.

**Pull request closed without merging**
