### PR TITLE
kumactl 0.7.2

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Review by dtrodrigues — APPROVED** [review]

**Comment by tharun208** [comment]
@dawidd6  wanted to know `formulae updates` now happen automatically in homebrew when a new release is done or we need to raise a pr ?.

**Comment by dawidd6** [comment]
It is not guaranteed that those bump PRs will be raised every time there is a new release, but I have this automated in dawidd6/ba-bump for now.

**Comment by tharun208** [comment]
to need to work with ur `workflow` should the `live check` to be added to the formulae?

**Comment by dawidd6** [comment]
No.

**Pull request closed without merging**
