### PR TITLE
swiftgen 5.2.0

### PR DESCRIPTION
**Pull request by AliSoftware**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- `brew test` passes

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@AliSoftware didn't minimum Xcode go up?

**Comment by AliSoftware** [comment]
Ohhhh good catch!!

**Comment by AliSoftware** [comment]
@ilovezfs fixed. I wonder how you spotted that tbh, do you follow our PRs _that_ closely so you knew we switched recently? ^^

**Comment by ilovezfs** [comment]
@AliSoftware I wish I could say I followed your PRs that closely. No, I just looked over your diff and the formula, and wondered if the xcode minimum had changed, so I checked your repository.

**Comment by AliSoftware** [comment]
Good work, sir! Nice catch then 👍

**Comment by ilovezfs** [comment]
Thanks :) Shipped and thanks for the upgrade! :tada:

**Pull request closed without merging**
