### PR TITLE
gdal: allow opencl only on macOS

### PR DESCRIPTION
**Pull request by iMichka**
We don't have an opencl formula for Linux

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Trying to build poppler-qt5 here: https://github.com/Homebrew/homebrew-core/actions/runs/1177951992

**Comment by cho-m** [comment]
> Trying to build poppler-qt5 here: https://github.com/Homebrew/homebrew-core/actions/runs/1177951992

Need to add propagate `gcc` dependency.

**Comment by danielnachun** [comment]
This will also need to be built with GCC 11, and we need to add back the fix that was removed here: https://github.com/Homebrew/linuxbrew-core/commit/16611cd315441bc840fcb3fbfd4ca064fe53d98e#diff-a53acf9779b5f8b0187e56c247859e3b61d412c9ec70ec6accbc2a47ac9732d8.  With those changes I got this to build locally.

**Comment by iMichka** [comment]
```
2021-08-29T09:02:47.3927232Z The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
2021-08-29T09:02:47.3927977Z Could not symlink etc/bash_completion.d/mount
2021-08-29T09:02:47.3928731Z Target /home/linuxbrew/.linuxbrew/etc/bash_completion.d/mount
2021-08-29T09:02:47.3929668Z is a symlink belonging to util-linux. You can unlink it:
2021-08-29T09:02:47.3930411Z   brew unlink util-linux
2021-08-29T09:02:47.3930739Z 
2021-08-29T09:02:47.3931247Z To force the link and overwrite all conflicting files:
2021-08-29T09:02:47.3932091Z   brew link --overwrite bash-completion
2021-08-29T09:02:47.3932496Z 
2021-08-29T09:02:47.3932931Z To list all files that would be deleted:
2021-08-29T09:02:47.3933755Z   brew link --overwrite --dry-run bash-completion
2021-08-29T09:02:47.3934195Z 
2021-08-29T09:02:47.3934728Z Possible conflicting files are:
2021-08-29T09:02:47.3935688Z mkdir -p /home/linuxbrew/.linuxbrew/etc/bash_completion.d/helpers
2021-08-29T09:02:47.3937156Z /home/linuxbrew/.linuxbrew/etc/bash_completion.d/mount -> /home/linuxbrew/.linuxbrew/Cellar/util-linux/2.37/etc/bash_completion.d/mount
2021-08-29T09:02:47.3938835Z /home/linuxbrew/.linuxbrew/etc/bash_completion.d/rfkill -> /home/linuxbrew/.linuxbrew/Cellar/util-linux/2.37/etc/bash_completion.d/rfkill
2021-08-29T09:02:47.3940375Z /home/linuxbrew/.linuxbrew/etc/bash_completion.d/rtcwake -> /home/linuxbrew/.linuxbrew/Cellar/util-linux/2.37/etc/bash_completion.d/rtcwake
```

**Comment by danielnachun** [comment]
I think we need to fix the file conflicts between `bash-completion` and `util-linux`.  I don't think we can make `util-linux` keg-only because, at the very least, some formulae will not be able to find `libuuid`.  I'm also not sure how functional `bash-completion` would be if it was keg-only either.  We may have to resort to deleting files to make this work.

**Comment by danielnachun** [comment]
Whoops I misunderstood the problem.  We just need to depend on `util-linux`.  I think you still have the wrong order for `fails_with` and `conflicts`, which I pushed a fix to, but I guess it was pulled back to your branch.  To avoid confusion maybe you should commit the fix.

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
