### PR TITLE
gleam 0.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lpil** [comment]
Very cool!

Would it be a good idea to use the precompiled macos binary instead of compiling from source? They can be downloaded from the releases page.

**Comment by chenrui333** [comment]
That would belong to homebrew-cask.

**Comment by chenrui333** [comment]
@lpil I think installation from source is preferred way as long as that is an option. I might be biased.

**Comment by chenrui333** [comment]
Homebrew is package manager ecosystem, in this way, the relevant things would be crossed-managed and cross-built for installation verification. I guess in this way, it does make sense to build from the source in here :)

**Comment by lpil** [comment]
Thanks for the info :)

**Pull request closed without merging**
