### PR TITLE
paket 4.1.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Do we really want to download a single pre-compiled `.exe`? Doesn't sound like our line of business…

**Comment by ilovezfs** [comment]
It's platform independent, it should be fine. That's why it's bottle unneeded.

**Comment by fxcoudert** [comment]
Is it open source?

**Comment by ilovezfs** [comment]
https://github.com/fsprojects/Paket/

**Comment by fxcoudert** [comment]
Then shouldn't we build from source?

**Comment by ilovezfs** [comment]
That could equally be said of all the jar files we install without building them.

**Comment by MikeMcQuaid** [comment]
Agreed with @ilovezfs here. We build from source to make ourselves friendlier to a variety of macOS and even Linux systems but if they can use an identical binary, it simplifies our formulae and upstream is still open source: this seems fine to me.

**Comment by MikeMcQuaid** [comment]
Also: Homebrew is more useful the number of things we install and Homebrew is better maintained the less effort we spend on things that users don't care about.

**Pull request merged**
