### PR TITLE
Neo4j 3.3.0

### PR DESCRIPTION
**Pull request by jgaskins**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks @jgaskins! For future reference, please note that the commit subject should be all lower-case.

**Comment by jgaskins** [comment]
Ahh, of course. Will make sure to do that next time!

**Comment by jgaskins** [comment]
… by which I mean, actually run the command in the contributing guidelines. :-)

**Comment by ilovezfs** [comment]
Thanks!

**Pull request merged**
