### PR TITLE
libgit2 0.99.0

### PR DESCRIPTION
**Pull request by rundel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like the examples are either not building properly or some of them don't exist anymore.

**Comment by bayandin** [comment]
> Looks like the examples are either not building properly or some of them don't exist anymore.

Yup, now they produce a single binary: https://github.com/libgit2/libgit2/pull/4956

**Comment by bayandin** [comment]
Along with revision bumps for other formulae, it's required to update `pygit2` resource

**Comment by Bo98** [comment]
`pygit2` has a new dependency `cached-property` as well which will need to be included.

**Comment by bayandin** [comment]
Submitted a patch for `gitless`: https://github.com/gitless-vcs/gitless/pull/230 and applied it to the formula.

Nevertheless, `gitg` fails (the same problem as mentioned in https://github.com/Homebrew/homebrew-core/issues/50815). Do you have any ideas regarding it @Bo98?

**Comment by Bo98** [comment]
That's the only one I haven't really figured out yet. It looks like it's not compiling in Objective-C mode but it does have a `-xobjective-c`.

It's probably because it's a .c rather than a .m and Meson is very picky. Though I've not had the time to go through the hoops of trying it out, submitting a patch etc.

**Comment by bayandin** [comment]
An upstream `gitg` issue: https://gitlab.gnome.org/GNOME/gitg/-/issues/277

With the latest meson (0.54.0) it started to fail with an error:
```
../libgitg/meson.build:115:2: ERROR: Dependency "appleframeworks" not found, tried framework
```

**Comment by Bo98** [comment]
I cannot reproduce that problem on 0.54.0 - just the original one.

**Comment by bayandin** [comment]
> I cannot reproduce that problem on 0.54.0 - just the original one.

Then I could be an issue of my local brew set up, will check it. Could you please add a comment to the upstream issue, please, while I'm sorting out my setup.

**Comment by bayandin** [comment]
Thanks @rundel

Thanks for the help with patching @Bo98

**Pull request closed without merging**
