### PR TITLE
openssl 1.0.2s

### PR DESCRIPTION
**Pull request by reaperhulk**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
All the failing packages are going to need to have "revision 1" added to the formula (or a higher number if it's already there) could you add those @reaperhulk?

**Comment by fxcoudert** [comment]
@SMillerDev no, if you look at the issues they are not linkage errors, so the new version appears ABI-compatible with previous one. The errors are likely unrelated to the update, but we need to understand them and fix them anyway…

**Comment by kmark** [comment]
> Changes between 1.0.2r and 1.0.2s [28 May 2019]
>
> - Change the default RSA, DSA and DH size to 2048 bit instead of 1024.
This changes the size when using the genpkey app when no size is given. It fixes an omission in earlier changes that changed all RSA, DSA and DH generation apps to use 2048 bits by default.
[Kurt Roeckx]
>
> - Add FIPS support for Android Arm 64-bit
Support for Android Arm 64-bit was added to the OpenSSL FIPS Object Module in Version 2.0.10. For some reason, the corresponding target 'android64-aarch64' was missing OpenSSL 1.0.2, whence it could not be built with FIPS support on Android Arm 64-bit. This omission has been fixed.
[Matthias St. Pierre]

Sounds like the new (corrected) default could be causing an issue?

**Comment by kmark** [comment]
Looking more into the individual test failures I don't see the googler project ever call the "genpkey" utility so it shouldn't be impacted by this change. If the case is that none of these failed tests are related to this PR I wouldn't think this should hold back a merge.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Mojave node timed out. @BrewTestBot test this please

**Comment by scpeters** [comment]
@BrewTestBot test this please

**Comment by scpeters** [comment]
the mojave build seems to be consistently failing when testing `brew test --verbose sslsplit`:

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/43207/version=mojave/console

~~~
20:41:31 ==> brew install sslsplit
20:41:35 
20:41:35 ==> brew install --only-dependencies sslsplit
20:41:36 
20:41:36 ==> brew linkage --test sslsplit
20:41:38 
20:41:38 ==> brew install --only-dependencies --include-test sslsplit
20:41:39 
20:41:39 ==> brew test --verbose sslsplit
20:46:41 FATAL: command execution failed
20:46:41 java.io.EOFException
20:46:41 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
20:46:41 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
20:46:41 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
20:46:41 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
20:46:41 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
20:46:41 	at hudson.remoting.Command.readFrom(Command.java:140)
20:46:41 	at hudson.remoting.Command.readFrom(Command.java:126)
~~~

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/43176/version=mojave/console

~~~
06:23:22 ==> brew install sslsplit
06:23:26 
06:23:26 ==> brew install --only-dependencies sslsplit
06:23:27 
06:23:27 ==> brew linkage --test sslsplit
06:23:28 
06:23:28 ==> brew install --only-dependencies --include-test sslsplit
06:23:29 
06:23:29 ==> brew test --verbose sslsplit
06:28:31 FATAL: command execution failed
06:28:31 java.io.EOFException
06:28:31 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
06:28:31 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
06:28:31 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
06:28:31 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
06:28:31 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
06:28:31 	at hudson.remoting.Command.readFrom(Command.java:140)
06:28:31 	at hudson.remoting.Command.readFrom(Command.java:126)
~~~

**Comment by scpeters** [comment]
The sslsplit test failure appears after 5 minutes on mojave, while the sslsplit test takes about 4 seconds on high sierra

**Comment by fxcoudert** [comment]
The formula test passes if it is built from source: https://jenkins.brew.sh/job/Homebrew%20Testing/1177/
I'm merged new bottles, hoping this will help.

@BrewTestBot test this please

**Comment by scpeters** [comment]
I can't reproduce the sslsplit failure locally, but given that it fails after 5 minutes, and I see that the test calls `fork` to start processes and then manually tries to kill them, I'm guessing that there's a leaked process somewhere.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/sslsplit.rb#L33-L56

**Comment by fxcoudert** [comment]
New `sslsplit` version merged in https://github.com/Homebrew/homebrew-core/pull/40802
Hopefully it will now pass.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please, one more time…

**Comment by fxcoudert** [comment]
Reworking the `sslsplit` test so it doesn't make CI crash anymore: https://github.com/Homebrew/homebrew-core/pull/40842

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
- Linkage test failures: `openimageio` (will rebottle), `podofo` and `xrootd` (both false positives).
- Test failures: `baresip haste-client mariadb pulledpork uwsgi ydcv` all unrelated.

**Pull request closed without merging**
