### PR TITLE
libgeotiff 1.5.0

### PR DESCRIPTION
**Pull request by DennisOSRM**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Formulas needing a revision bump: `gdal libgaiagraphics liblas librasterlite pdal`

**Comment by DennisOSRM** [comment]
Thanks. Will bump the revisions. Any preference whether to do it in individual commits or a single one?

**Comment by fxcoudert** [comment]
@DennisOSRM one commit per formula (i.e. per file modified), with message: `gdal: revision for libgeotiff`

**Comment by fxcoudert** [comment]
Thanks, you rock @DennisOSRM

**Comment by fxcoudert** [comment]
Apparently there is a new patch for libgeotiff, probably needed until gdal 2.5.0: https://github.com/OSGeo/libgeotiff/commit/f4956251737b29ccc3f6366cd5b21520689f21d9

**Comment by DennisOSRM** [comment]
> Apparently there is a new patch for libgeotiff, probably needed until gdal 2.5.0: [OSGeo/libgeotiff@f495625](https://github.com/OSGeo/libgeotiff/commit/f4956251737b29ccc3f6366cd5b21520689f21d9)

Thanks for the link. Updated the Formula to apply it.

**Comment by fxcoudert** [comment]
`liblas` failure in `make check`:

```
==> make test
Running tests...
/usr/local/Cellar/cmake/3.14.0/bin/ctest --force-new-ctest-process 
Test project /tmp/liblas-20190328-79345-11en1fd/libLAS-1.8.1/macbuild
    Start 1: liblas_test
1/1 Test #1: liblas_test ......................***Failed    0.26 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.26 sec

The following tests FAILED:
	  1 - liblas_test (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Is it a fluke? @BrewTestBot test this please

**Comment by scpeters** [comment]
Hope you don't mind I just resolved the conflicts on this branch by rebasing onto master

**Comment by fxcoudert** [comment]
```
==> make test
Running tests...
/usr/local/Cellar/cmake/3.14.3/bin/ctest --force-new-ctest-process 
Test project /tmp/liblas-20190423-9154-mswr1l/libLAS-1.8.1/macbuild
    Start 1: liblas_test
1/1 Test #1: liblas_test ......................***Failed    0.26 sec

0% tests passed, 1 tests failed out of 1
```

**Comment by fxcoudert** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/39340

**Pull request closed without merging**
