### PR TITLE
gitlab-ci-multi-runner 1.5.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍 if you are resource happy.

**Comment by ilovezfs** [comment]
not resource happy. they need to ship the new prebuilt :(

**Comment by DomT4** [comment]
Ah okay. We shall have to exercise some patience I guess 🙈

**Comment by doits** [comment]
Changing the prebuilt location seems to work fine for me, see https://github.com/doits/homebrew-core/commit/ad1cd87a0c868159061bdc06d8af3ac5adb5aab6

**Comment by ilovezfs** [comment]
@doits you're awesome. Looks like they switched from gz to xz. I guess I can stop checking if the new link has been posted every day like a fool.

**Comment by ilovezfs** [comment]
@doits PR is refreshed.

**Pull request closed without merging**
