### PR TITLE
Remove stale aliases

### PR DESCRIPTION
**Pull request by carlocab**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The formulae these aliases point to no longer have alternate versions,
so we don't need to keep their versioned aliases around anymore.

### CODE REVIEW

**Comment by Bo98** [comment]
This seems like a breaking change. Might be something we do gradually on major version bumps.

https://github.com/search?q=%22brew+install+sbt%401%22&type=code
https://github.com/search?q=%22brew+install+helm%403%22&type=code
https://github.com/search?q=%22brew+install+swig%404%22&type=code

**Review by p-linnane — APPROVED** [review]
Seems fine to me.

**Comment by carlocab** [comment]
I'll keep `sbt@1` since it has at least 100 matches. The rest I'll split into separate PRs for ease of review.

**Comment by carlocab** [comment]
Each alias split into a separate PR.

**Comment by carlocab** [comment]
All done.

**Pull request closed without merging**
