### PR TITLE
duplicity: add support for more backends

### LINKED ISSUE #44783: formula "duplicity" 0.8.03 does not include "paramiko" library (required for SFTP) macOS Sierra 10.12.6
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
No output from `brew gist-logs duplicity`
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
https://gist.github.com/colini/95f7b8b020555f6efc34ef015171256c

To help us debug your issue please explain:

- What you were trying to do (and why)
Formula "duplicity" 0.8.03 installs correctly and runs.  But if you attempt to backup via SFTP it fails because the required pypi library "paramiko" is not installed by the formula.

- What happened (include command output)
duplicity installs and runs successfully, but since the formula does not include the paramiko dependency, you cannot backup via SFTP.  See below for steps to reproduce.

- What you expected to happen
I expect duplicity to be able to backup via SFTP.  Or add an option flag to the formula to include paramiko.

- Step-by-step reproduction instructions (by running `brew install` commands)
~ $ brew install duplicity
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/duplicity-0.8.03.sierra.bottle.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/1d65afdc1aebb5b3649591def2664b51687e68a69754abaed6b8ee1b2a0e4ea3--duplicity-0.8.03.sierra.bottle.tar.gz
==> Pouring duplicity-0.8.03.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/duplicity/0.8.03: 1,044 files, 11MB

~ $ duplicity --verbosity 8 ~ sftp://example.com/backups
Using archive dir: /Users/user/.cache/duplicity/a723146404b98358ec19e2c2517bbaae
Using backup name: a723146404b98358ec19e2c2517bbaae
Import of duplicity.backends.adbackend Succeeded
Import of duplicity.backends.azurebackend Succeeded
Import of duplicity.backends.b2backend Succeeded
Import of duplicity.backends.botobackend Succeeded
Import of duplicity.backends.cfbackend Succeeded
Import of duplicity.backends.dpbxbackend Succeeded
Import of duplicity.backends.gdocsbackend Succeeded
Import of duplicity.backends.giobackend Succeeded
Import of duplicity.backends.hsibackend Succeeded
Import of duplicity.backends.hubicbackend Succeeded
Import of duplicity.backends.imapbackend Succeeded
Import of duplicity.backends.jottacloudbackend Succeeded
Import of duplicity.backends.lftpbackend Succeeded
Import of duplicity.backends.localbackend Succeeded
Import of duplicity.backends.mediafirebackend Succeeded
Import of duplicity.backends.megabackend Succeeded
Import of duplicity.backends.multibackend Succeeded
Import of duplicity.backends.ncftpbackend Succeeded
Import of duplicity.backends.onedrivebackend Succeeded
Import of duplicity.backends.par2backend Succeeded
Import of duplicity.backends.pcabackend Succeeded
Import of duplicity.backends.pydrivebackend Succeeded
Import of duplicity.backends.rsyncbackend Succeeded
Import of duplicity.backends.ssh_paramiko_backend Succeeded
Import of duplicity.backends.ssh_pexpect_backend Succeeded
Import of duplicity.backends.swiftbackend Succeeded
Import of duplicity.backends.sxbackend Succeeded
Import of duplicity.backends.tahoebackend Succeeded
Import of duplicity.backends.webdavbackend Succeeded
Using temporary directory /var/folders/5w/vydk493s747f327twkqjprhw0000gr/T/duplicity-me4_bj9g-tempdir
Backend error detail: Traceback (innermost last):
  File "/usr/local/bin/duplicity", line 101, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 87, in with_tempdir
    fn()
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/dup_main.py", line 1520, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/commandline.py", line 1201, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/commandline.py", line 1072, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/backend.py", line 229, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/backend.py", line 217, in get_backend_object
    raise BackendException(_(u"Could not initialize backend: %s") % str(sys.exc_info()[1]))
 duplicity.errors.BackendException: Could not initialize backend: No module named 'paramiko'

**BackendException: Could not initialize backend: No module named 'paramiko'**

**As a workaround:**
Since duplicity is installed into a virtual environment, it's possible to workaround by installing paramiko manually:
~ $ source /usr/local/Cellar/duplicity/0.8.03/libexec/bin/activate
(libexec) ~ $ pip install paramiko
Collecting paramiko
<... snip ...>
Successfully installed asn1crypto-0.24.0 bcrypt-3.1.7 cffi-1.12.3 cryptography-2.7 paramiko-2.6.0 pycparser-2.19 pynacl-1.3.0
(libexec) ~ $ deactivate

It is now possible to backup using SFTP.

Gist of my config: https://gist.github.com/colini/95f7b8b020555f6efc34ef015171256c

### PR DESCRIPTION
**Pull request by azenla**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This adds support for more back-ends for duplicity. This fixes #44783

Included are Dropbox, Google Drive, Backblaze B2, and SFTP.

### CODE REVIEW

**Comment by kendfinger** [comment]
Note that I am awaiting the Catalina release to hopefully have the test failure fixed.

**Comment by fxcoudert** [comment]
We probably don't want to ship with a degraded test…

**Comment by kendfinger** [comment]
@fxcoudert 
Yes, it's not optimal. It's part of a bigger problem I think: expect is failing in brew test on Catalina due to "The system has no more ptys.  Ask your system administrator to create more."

For reference, it works fine if ran outside of brew test, so I suspect it's something to do with Catalina permissions or security changes.

The test that is in it's place is functionally equivalent (although, admittedly, does not check the exact output of the command). It will still check if the command succeeds and that it produces a backup signature, so I believe it should be good enough to ship.

**Comment by fxcoudert** [comment]
Makes sense. And yes, there is a `tty`-related change in Catalina that is breaking a few tests — we need to better understand where it comes from. Probably something sandbox-related.

Can you squash your changes into a single commit please?

**Comment by kendfinger** [comment]
@fxcoudert Squashed 👍

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
