### PR TITLE
jp: fix build for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

ARM is probably going to fail as it is currently building x86_64 binary.

### CODE REVIEW

**Comment by danielnachun** [comment]
If this does not support ARM, maybe it needs `depends_on arch: :x86_64`.

**Comment by cho-m** [comment]
Makefile doesn't support ARM; however, it should be possible to at least attempt build by patching Makefile with target that uses correct Arch.

I'll at least try it out in a bit. If it doesn't work, we can restrict to x86_64.

**Review by danielnachun — APPROVED** [review]
Nice work fixing this for ARM!

**Comment by cho-m** [comment]
How do we update ARM bottle without losing older (e.g. sierra) bottle?

**Comment by danielnachun** [comment]
Can we merge and then dispatch a bottle build for ARM like we do for Linux?

**Comment by cho-m** [comment]
I am not familiar with Upload workflow.
I have seen it reject uploading when there is an existing bottle.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Dispatched, https://github.com/Homebrew/homebrew-core/actions/runs/1106695071

**Pull request merged**
