### PR TITLE
ninja: support installing `libninja.a`

### PR DESCRIPTION
**Pull request by ken-matsui**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR allows us to install `libninja.a`, a library of Ninja, as well.

### CODE REVIEW

**Comment by fxcoudert** [comment]
What's your use case? I find documentation saying:

> libninja is an implementation detail of ninja-the-binary, it's not designed to be a reusable library. 

The executable is how ninja is supposed to be used, not the library.

**Comment by ken-matsui** [comment]
@fxcoudert 
Umm... I am using Ninja as a library as shown below:

https://github.com/poacpm/poac/blob/main/cmake/AddNinja.cmake#L19

I think the reason why the `libninja` & `libninja-re2c` are provided is for library users like me, IMO...

https://github.com/ninja-build/ninja/blob/55f54511d35716c43637dee2bcb5fbc7839f967b/CMakeLists.txt#L47

**Comment by fxcoudert** [comment]
Is it stable and documented? I can't see it mentioned anywhere: https://ninja-build.org/manual.html

**Comment by ken-matsui** [comment]
Alright, I close this.

**Pull request closed without merging**
