### PR TITLE
git, subversion: fixes for system Perl

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Revision bump for https://github.com/Homebrew/brew/pull/11286 and add fixes to PERL5LIB in `git-svn` when running on an OS without a system `svn`.

### CODE REVIEW

**Comment by moonfruit** [comment]
@Bo98, Can you apply the patch I mentioned in [#76900](https://github.com/Homebrew/homebrew-core/pull/76900#issuecomment-838372469)?

This is used to build the subversion perl module for system perl. And also build on Apple Silicon.

**Comment by Bo98** [comment]
`VERSIONER_PERL_VERSION` should in theory cover that.

**Comment by moonfruit** [comment]
`subversion` use homebrew's perl on not macOS, and `git` use perl in the PATH.
For macOS this will be fine, but I think this will make `git-svn` not working on not macOS? 

git.rb:
```ruby
    ENV["PERL_PATH"] = which("perl")
    on_macos do
      ENV["PERL_PATH"] = "/usr/bin/perl"
    end
```

subversion.rb:
```ruby
    perl = Formula["perl"].opt_bin/"perl"
    on_macos do
      perl = "/usr/bin/perl"
    end
```

**Comment by Bo98** [comment]
Yeah I've been talking to the Linux folk about Perl on Linux. There is a desire not to depend on Perl (since it's an extra dependency on a critical component that `brew` can rely on).

The approach I took here clearly didn't work because:

> `on_macos` cannot include `uses_from_macos`.

**Comment by moonfruit** [comment]
I means that on Linux git depends on perl in the PATH, and subversion depends on homebrew's perl.
These two may not the same. So maybe on Linux git-svn is not working.
I think we should let subversion on Linux also depends on perl in the PATH.

like this:
```rb
    perl = which("perl")
    on_macos do
      perl = "/usr/bin/perl"
    end
```

**Comment by Bo98** [comment]
Subversion already depends on brewed Perl on Linux so `which("perl")` will prioritise that. Brewed Perl is kinda needed there since SVN builds native Perl modules and thus isn't compatible with versions of Perl not matching whatever it was built with.

**Pull request closed without merging**
