### PR TITLE
sonarqube: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by nandahkrishna**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Split from #79448.

### CODE REVIEW

**Comment by Moisan** [comment]
```
❯ sha256sum *.tar.gz
3dcee2d9de05efa6019ea3b84e2b5625f9408663b91fa23b6a4aab10abee52f4  sonarqube--8.9.0.43852.arm64_big_sur.bottle.tar.gz
e7a9bee29eccc49d0743752a9aa98193de3f299e0f1d5f7727de020664957df0  sonarqube--8.9.0.43852.big_sur.bottle.tar.gz
e7a9bee29eccc49d0743752a9aa98193de3f299e0f1d5f7727de020664957df0  sonarqube--8.9.0.43852.catalina.bottle.tar.gz
4c49c9acea99203b6595d05b3125b99fdc4e63e473d1ee5b21b0494c70a84890  sonarqube--8.9.0.43852.mojave.bottle.tar.gz
```
❌

**Comment by carlocab** [comment]
The diff comes from `libexec/web/js/docs.1619792615098.chunk.js` and `libexec/web/js/docs.m.955a5ed9.chunk.js`. The text diff from diffoscope is unreadable, but the HTML one is a bit easier to read in a browser: [diff.html.txt](https://github.com/Homebrew/homebrew-core/files/6690076/diff.html.txt)

**Comment by cho-m** [comment]
What I was curious about was diff between Mojave vs. Big Sur / Catalina, which happens in the `.map` variants of the same JS files (corresponding to same lines that ARM64 vs Big Sur has diff).
- `sonarqube/8.9.0.43852/libexec/web/js/docs.1619792615098.chunk.js.map`
- `sonarqube/8.9.0.43852/libexec/web/js/docs.m.955a5ed9.chunk.js.map`

It looks like Mojave has 2 more `@@HOMEBREW_PREFIX@@`, which are probably match the lines in `.js` files
- Copy the server's CA certs to `/usr/local/share/ca-certificates`
- Copy the server's CA certs to `@@HOMEBREW_PREFIX@@/share/ca-certificates`

I would have thought Mojave, Catalina, and Big Sur would produce same replacements.

**Comment by cho-m** [comment]
Given the diff is only in the generated docs, we should probably merge this

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
