### PR TITLE
icu4c 66.1

### PR DESCRIPTION
**Pull request by pOmelchenko**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Duplicate of #48349.

Would you like to work on this? If yes, you will need to move all the changes from #48349 to this PR.

**Comment by pOmelchenko** [comment]
> Would you like to work on this?
Sorry, my first attempt to update the formula :) I wait for the CI to finish the work, and I can see the result.

I think today I finally make that PR with changes from # 48349 too

**Comment by chenrui333** [comment]
Please dont use "Merge branch 'master' into icu4c_66.1" commit?

**Comment by pOmelchenko** [comment]
why?

**Comment by chenrui333** [comment]
That is because the homebrew PR merge process does not work well with this process. Please use rebase process instead.

**Comment by pOmelchenko** [comment]
Ok, I create fresh branch and PR with all changes and comments :) I will back soon

**Comment by chenrui333** [comment]
Thanks, be sure incorporating all the changes have been done in #48349.

**Pull request closed without merging**
