### PR TITLE
code-cli 1.85.1

### PR DESCRIPTION
**Pull request by dnhn**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>The update addresses these [issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22November+2023+Recovery+1%22+is%3Aclosed).

For the complete release notes go to [Updates](https://code.visualstudio.com/updates/v1_85) on [code.visualstudio.com](https://code.visualstudio.com/).</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
`  Minitest::Assertion: Expected /1\.85\.1/ to match "code-oss 1.85.0 (commit unknown)\n".`

**Comment by chenrui333** [comment]
> ` Minitest::Assertion: Expected /1\.85\.1/ to match "code-oss 1.85.0 (commit unknown)\n".`

I dont know where this 1.85.0 comes from.

**Comment by krehel** [comment]
Looks like something was updated, as I re-ran the CI and the `sha256` had changed (also confirmed locally).

Updated that value, we'll see if it builds now.

**Comment by chenrui333** [comment]
much better now, thanks @krehel!

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
