### PR TITLE
c-ares 1.17.1

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Nothing in their changelog suggests that we need to change anything. It seems it needs itself to bootstrap a build in this version though.

**Comment by bayandin** [comment]
Should be fixed by https://github.com/c-ares/c-ares/commit/a88f01e2fd6cb2fd2474ecf0ceae8f9bb05e2b36 
Meanwhile, we could try to build it from a GitHub archive (or to wait for a re-release).

**Comment by bayandin** [comment]
There-re going to re-release it as 1.17.1 (https://github.com/c-ares/c-ares/commit/155049d17556f4e2c38c8f265804210f0b8a215c).

Btw, we should change head to https://github.com/c-ares/c-ares (from https://github.com/bagder/c-ares.git)

**Comment by bayandin** [comment]
> c-ares 1.17.0

Commit message should be `c-ares 1.17.1` I guess

**Comment by SMillerDev** [comment]
> Commit message should be c-ares 1.17.1 I guess

Autosquash will fix it

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
