### PR TITLE
ansible: fix ssh issues with netconf

### PR DESCRIPTION
**Pull request by gaige**
Recent updates to netconf (for working with routers) require pylibssh in order to
work consistently. This commit adds ansible-pylibssh in order to resolve errors when
communicating with routers using vyos and junos (at a minimum).

Adds libssh as a dependency, which is necessary for build and will cause an error
if run without it.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
This will be removed in the next version bump unless it's also added to the pypy configuration JSON at the root of the repo

**Comment by gaige** [comment]
> This will be removed in the next version bump unless it's also added to the pypy configuration JSON at the root of the repo

I wasn't aware. Updating, testing, re-auditing now.

**Comment by gaige** [comment]
@SMillerDev Updated with changes to the additional file. LMK if there is anything else.

Thanks!

**Review by SMillerDev — APPROVED** [review]
Thanks @gaige  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by gaige** [comment]
@SMillerDev Curious about the merge failure here. Any recommendations?

**Comment by SMillerDev** [comment]
Could you rebase this PR?

**Comment by gaige** [comment]
On it

**Review by carlocab — APPROVED** [review]

**Pull request merged**
