### PR TITLE
ghc: patch for ARM Ventura

### PR DESCRIPTION
**Pull request by fxcoudert**
Trying to use the upstream patch

### CODE REVIEW

**Comment by Bo98** [comment]
Unfortunately, this needs to apply to the bootstrap as well.

Using 9.2.5 bootstrap is an option but requires a rewrite of the install method to use Hadrian rather than Make.

**Comment by cho-m** [comment]
Just noting that the register doesn't seem to be as aggressively zeroed on my local machine compared to upstream issue. At least I could build following so the resulting binaries weren't crashing immediately:
- GHC 9.4.3 bootstrapped with GHC 9.2.5 and pre-built `cabal-install`. I assume this has smallest chance of segfault since only `cabal-install` should have problem and it is used for a short timeframe to prepare Hadrian build (which should be compiled by GHC 9.2.5 without bug?)
- GHC 9.2.5 bootstrapped with GHC 9.0.2. Interesting that I didn't hit a failure here since 9.0.2 should have bug.

Did hit a segfault while building GHC 9.2.4 but was somewhat later into run. Tried 2 times and both attempts failed.

---

However, still hitting sporadic segfaults while building `pandoc` with my locally built copy of GHC 9.4.3 and a locally built copy of `cabal-install` (which was built with GHC 9.4.3 & the pre-built `cabal-install`)

And hitting sporadic build termination while running a copy of `haskell-stack` built with GHC 9.2.5. Had tried building `hledger` and `purescript`.

Anyways, I'm curious if ARM Ventura CI will be able to build anything in #110865.

**Comment by fxcoudert** [comment]
Any reason why you chose not to apply the patch to 9.2.4 in that other PR? I don't think it hurts, it was approved upstream, and it will make code generated on older macOS run on Ventura.

**Comment by cho-m** [comment]
> Any reason why you chose not to apply the patch to 9.2.4 in that other PR? I don't think it hurts, it was approved upstream, and it will make code generated on older macOS run on Ventura.

No reason. I wasn't able to build GHC 9.2.4 on Ventura ARM so had ignored it, but can add for next run since it may help even if we only have Monterey ARM bottles.

I do want to get first CI run as there may be some failures that I need to look into.

**Comment by cho-m** [comment]
Looks like CI is behaving similar to my experiences. GHC 9.4.3 (`ghc`) built, GHC 9.2.4 (`ghc@9.2`) failed, and some dependents builds are still segfaulting (e.g. `pinboard-notes-backup`, `mighttpd2`, `pandoc-plot`). The most common location the segfault happens is while building `tls-1.6.0` but I have seen it happen in other Haskell packages:
```
Error: cabal: Failed to build tls-1.6.0 (which is required by exe:pnbackup
from pinboard-notes-backup-1.0.5.5). The build process segfaulted (i.e.
SIGSEGV).

Error: cabal: Failed to build tls-1.6.0 (which is required by exe:mighty from
mighttpd2-4.0.2 and exe:mightyctl from mighttpd2-4.0.2). The build process
segfaulted (i.e. SIGSEGV).

Error: cabal: Failed to build tls-1.6.0 (which is required by exe:pandoc-plot
from pandoc-plot-1.5.5). The build process terminated with exit code -10
```
It also occasionally passes as seen by how `pandoc` and `pandoc-crossref` both built. These share a Haskell dependency tree via `pandoc` and all sporadically fail to build.

**Comment by cho-m** [comment]
Backported patch into #110865 which is merged. However, I couldn't figure out other ARM Ventura issues so out bottles for `ghc` and `ghc@9.2` are not fully stable yet.

Probably need someone more familiar with GHC or upstream to look into why we still see segfaults on GHC 9.4.3.

**Pull request closed without merging**
