### PR TITLE
dcd 0.9.2

### PR DESCRIPTION
**Pull request by John-Colvin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
any idea why https://github.com/dlang-community/DCD/releases/latest still points to 0.9.0?

**Comment by John-Colvin** [comment]
Other than the obvious "not all tags are marked as github releases", no idea. @wilzbach do you know anything about how the @dlang-bot release tagging works?

**Comment by wilzbach** [comment]
Release tagging has nothing to do with dlang-bot (at least at the moment).

I think there is a confusion between git tags and GitHub releases. The tag 0.9.2 exists:

https://github.com/dlang-community/DCD/tags

But GitHub only marks tags released through their UI as latest release. Is this required?

**Comment by ilovezfs** [comment]
@wilzbach we require releases/latest to point to whatever we're merging for stable if GitHub releases are used at all in order to try to respect upstream intent. Since upstream intent is clear here despite the mismatch, we don't have to block on it, but it would be nice to get this fixed. Note that you definitely do not need to use the GUI to make GitHub releases. There is an API:
https://developer.github.com/v3/repos/releases/

**Pull request closed without merging**
