### PR TITLE
Bazel only needs Java at build time, not when installing from a bottle

### PR DESCRIPTION
**Pull request by alexeagle**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
We're using Java wrapper scripts here. It's not build time only.

**Comment by alexeagle** [comment]
@ilovezfs can you help me understand that? What are the Java wrapper scripts?

Bazel itself ships with a JDK, so brew should not prompt all users to install one. The current situation in brew is giving users the impression that Bazel is hard to install because of a Java dependency, this makes Bazel very hard to sell in communities like NodeJS/Javascript where they are suspicious of such a dependency.

**Comment by alexeagle** [comment]
@ilovezfs could you take another look here please? Or else I'll open a new PR so we can discuss.
I'm working directly with the Bazel team, and this is high priority for us. We need to correct the misconception that Bazel is hard to install due to the Java runtime.

**Comment by ilovezfs** [comment]
@alexeagle Sorry, I'm afraid not.

**Comment by dslomov** [comment]
@ilovezfs I am not sure what the concern is? Bazel needs Java at build time, but not at runtime (because JDK is bundled)

**Comment by ilovezfs** [comment]
@dslomov I tested the PR locally and if Java is not installed then it failed on an error about calling `java_home`. That won't show up on our CI since Java is always installed.

**Comment by ilovezfs** [comment]
Note that was with the wrapper scripts removed as well.

**Comment by philwo** [comment]
I think `compile.sh` does not build a Bazel with bundled JDK yet, so I'm not surprised that this PR doesn't work yet - but we can easily *make* it work and I'd love to do so :) (I'm the author of the "let's bundle a JDK with Bazel" feature, fwiw.)

This would also solve an issue in that some users have Java installed, but an incompatible version (e.g. older JDK 8). Bazel works best with certain versions of OpenJDK that include all recent bugfixes that we need. It can otherwise exhibit weird bugs, e.g. [[1]](https://github.com/bazelbuild/bazel/issues/4648) [[2]](https://github.com/bazelbuild/bazel/issues/4516) [[3]](https://github.com/bazelbuild/bazel/issues/4483).

This also seems to be the recommendation from Oracle: "Instead of relying on a pre-installed standalone JRE, we encourage application developers to deliver JREs with their applications. More details will be made available through early 2018." [(source)](http://www.oracle.com/technetwork/java/javase/eol-135779.html)

@ilovezfs Would you be open to merge a PR similar to this, when I tested locally on a system without installed JRE / JDK that it works and thus we can prove that the Java dependency is really for build time only?

**Comment by ilovezfs** [comment]
@philwo yes that would be fine assuming it does not involve bundling prebuilt binaries.

**Pull request closed without merging**
