### PR TITLE
rust 1.8.0

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
```
configure: error: bad APPLE CLANG version: 7.3.0, need >=7.0
```

On the El Cap builder, looks like a bug?

**Comment by cryon** [comment]
There's a [PR](https://github.com/rust-lang/rust/pull/32425) that supposedly resolved this that was merged to the rust-lang's master branch 22 days ago. Strange that the error still exists!

**Comment by alex** [comment]
I don't think Rust cuts releases from master, so that would explain that. Did that check not exist in Rust 1.7?

**Comment by cryon** [comment]
Ah, you're right, they release from `stable` where the commit is not present.

The check is identical between 1.7 an 1.8:

```bash
case $CFG_OSX_CLANG_VERSION in
                (7.0* | 7.1* | 7.2*)
                step_msg "found ok version of APPLE CLANG: $CFG_OSX_CLANG_VERSION"
```

This is the old issue: https://github.com/rust-lang/rust/issues/32442

**Comment by tdsmith** [comment]
@alex: Can you add:

```ruby
# Build on Xcode 7.3
# https://github.com/rust-lang/rust/issues/32442
patch do
  url "https://github.com/rust-lang/rust/commit/79da64a.diff"
  sha256 "78ebf373cb19be5fef053776729109824cc7bbbd2bd375e9c444bef7ea41faf7"
end
```

to the formula body? Thanks!

**Comment by alex** [comment]
@tdsmith done and done!

**Comment by tdsmith** [comment]
Thanks!

(Sorry maintainers, meant to squash those and got distracted!)

**Pull request closed without merging**
