### PR TITLE
libpng 1.6.37

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
Looks like libpng's own tests are failing.

@ctruta it looks like you were involved in the latest release, is this a known issue?

**Comment by fxcoudert** [comment]
One test, which failed on Mojave only:

```
16:46:40 /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
16:46:40 FAIL: tests/pngtest
```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by ctruta** [comment]
I am aware of the issue reported in #34765, and I'm sorry to see that it's happening again. On my machine (running High Sierra) it never happened, but I'll keep an eye on it. For example, I'll try to run tests in more stressful conditions (e.g. `make -j20`) and see what happens.

Alternatively, I can create a special branch that you could run on your bots and then let me know of your results, so that I can have more information as I debug this issue -- if such a trick would work for you.

**Comment by fxcoudert** [comment]
Thank you @alex for the pull request

**Pull request closed without merging**
