### PR TITLE
libxcb 1.15

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Not sure if related to error, but looks like this is picking up macOS's Python 2 and using `/usr/bin/python`.
```
  checking for a Python interpreter with version >= 2.6... python
  checking for python... /usr/bin/python
  checking for python version... 2.7
  checking for python platform... darwin
  checking for GNU default python prefix... ${prefix}
  checking for GNU default python exec_prefix... ${exec_prefix}
  checking for python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python2.7/site-packages
  checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python2.7/site-packages
```

**Comment by Porkepix** [comment]
I see many of the python errors refering to `xcb-proto` which was updated yesterday but after the PR, so might be worth a retry?

And looking at https://github.com/Homebrew/homebrew-core/blob/master/Formula/libxcb.rb#L19= python 3 is only requested on build time, so I guess it's a normal behavior if it tries to run it through mac's own python, which is desperately stuck on python 2…?

**Comment by cho-m** [comment]
Should try overriding the python `configure` picks up. There is sometimes a flag (maybe look for something like `--with-python......`) or an environment variable (often `PYTHON`) to do this.

Mixing Python2 executable with Python3-built libraries are going to cause issues:
```
/usr/bin/python ./c_client.py	-c "libxcb 1.15" -l "X Version 11" \
  		-s "3" -p //opt/homebrew/Cellar/xcb-proto/1.14.1_1/lib/python3.10/site-packages
```

**Review by SMillerDev — DISMISSED** [review]

**Comment by fxcoudert** [comment]
```
curl: (28) Failed to connect to xcb.freedesktop.org port 443: Operation timed out
```

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
😞 it's complaining about an empty commit. I think this needs a rebase and re-run

**Comment by bayandin** [comment]
`xcb-proto` was updated in #100730, dropping it from this PR.

**Pull request closed without merging**
