### PR TITLE
nginx 1.14.0

### PR DESCRIPTION
**Pull request by apeschel**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apeschel** [comment]
Took a look through the code base, and there's not a great way to solve the audit failure at the moment.

I've corrected the failing audit check by prepending a large number to the devel version string. Please let me know if this is a sufficient work-around or if there is a better approach.

**Comment by apeschel** [comment]
There's also https://github.com/Homebrew/homebrew-core/commit/8e70ac0569b6c337c829fe34770c5b18bd12ac62 which suggests maybe we want to keep the repo tracking the mainline and not even switch to 1.14?

**Comment by fxcoudert** [comment]
Merged, with a simpler/shorter comment added. If devel numbering is inconsistent, let's just skip that.

**Comment by ilovezfs** [comment]
Using main line is intentional as it's the recommended upstream branch. "Stable" is an LTS branch not the recommended branch.

**Comment by ilovezfs** [comment]
I have reverted ecb604ddf03d4feb6c047ea8795d7e5ab30c55c4 and 85f85ddfd3d90edbb69bc8f2bf7874920e75a3ec

**Comment by ilovezfs** [comment]
Comment about using mainline only added in https://github.com/Homebrew/homebrew-core/pull/27111

**Pull request closed without merging**
