### PR TITLE
micropython 1.13

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> brew audit micropython --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
micropython:
  * The URL https://micropython.org/ is not reachable
```

**Comment by SMillerDev** [comment]
Did we let upstream know this was the case?

**Comment by chenrui333** [comment]
I think this is more issue with the system curl rather than the site cert issue?

The issue is in here, https://github.com/libressl-portable/portable/issues/595

**Comment by chenrui333** [comment]
```
$ /usr/bin/curl --version
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

$ /usr/local/opt/curl/bin/curl --version
curl 7.71.1 (x86_64-apple-darwin18.7.0) libcurl/7.71.1 SecureTransport zlib/1.2.11
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

**Comment by chenrui333** [comment]
it does not affect brewed version though

**Comment by gromgit** [comment]
> I think this is more issue with the system curl rather than the site cert issue?

Based on the output of `/usr/local/opt/curl/bin/curl -v https://micropython.org/`, it's the Sectigo issue again: https://github.com/Homebrew/homebrew-core/issues/58854

**Comment by bayandin** [comment]
For homepages there's [`CERT_ERROR_ALLOWLIST`](https://github.com/Homebrew/brew/blob/7bd2f511c43a25f9589a580f610fea09b5f58804/Library/Homebrew/dev-cmd/audit.rb#L549), we could use it to silent the error.

**Comment by jonchang** [comment]
Merged the cert error PR in brew and rebased.

**Review by jonchang — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @jonchang!

**Pull request closed without merging**
