### PR TITLE
cruft: depend on cookiecutter

### PR DESCRIPTION
**Pull request by singingwolfboy**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by jonchang** [comment]
This needs a revision bump since you're changing dependencies.

**Review by jonchang — CHANGES_REQUESTED** [review]
This needs a `revision` bump since you're changing dependencies.

**Comment by chenrui333** [comment]
> This needs a `revision` bump since you're changing dependencies.

The dependencies are actually the same, but more like dep style change

**Comment by singingwolfboy** [comment]
I have no problem with bumping the revision number, particularly since some of the dependencies provided in the `cookiecutter` formula may have a different version from the ones specified in this formula.

**Comment by chenrui333** [comment]
> I have no problem with bumping the revision number, particularly since some of the dependencies provided in the `cookiecutter` formula may have a different version from the ones specified in this formula.

yeah, we dont have to bump the revision as it would mess up the semantics (the change is really moving from the resource to the existing formula, no technical changes involved)

**Comment by singingwolfboy** [comment]
Well, I'm fine either way. I bumped the revision in a separate commit -- if you want to include it, great. If you want me to revert it, it's easy to remove that commit.

**Review by carlocab — DISMISSED** [review]
Thanks!

**Review by jonchang — DISMISSED** [review]

**Review by jonchang — APPROVED** [review]

**Pull request closed without merging**
