### PR TITLE
minidlna 1.3.0

### PR DESCRIPTION
**Pull request by mprince**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Testing minidlna
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201127-43040-r33gm7.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/minidlna.rb --verbose
==> curl localhost:61177
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 61177: Connection refused

Killing child processes...
Error: minidlna: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<7>.
```

**Comment by chenrui333** [comment]
11.0 test failure is pre-existing issue, good for the merge after the build.

**Comment by chenrui333** [comment]
```
==> curl localhost:49341
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 49341: Connection refused

Killing child processes...
An exception occurred within a child process:
Error: minidlna: failed
  Test::Unit::AssertionFailedError: <0> expected but was
<7>.
```

**Comment by gromgit** [comment]
@mprince , I fixed the test block in #69087, so a rebase should fix things.

**Review by SeekingMeaning — APPROVED** [review]

**Pull request closed without merging**
