### PR TITLE
python@3.9: update pip, setuptools

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Update to the latest pip and setuptools.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Canceling CI for now, pending resolution of https://github.com/pypa/pip/issues/9506

**Comment by carlocab** [comment]
On ARM:

```
Error: 2 failed steps!
brew test --retry --verbose emscripten
brew test --retry --verbose tree-sitter
```

The `tree-sitter` failure appears to be from `emscripten` being broken.

**Comment by dtrodrigues** [comment]
```
11.0
Error: 9 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose creduce
brew test --retry --verbose geant4
brew test --retry --verbose glyr
brew test --retry --verbose howdoi
brew test --retry --verbose hyperkit
brew test --retry --verbose pinboard-notes-backup
brew test --retry --verbose qxmpp
brew test --retry --verbose treefrog


10.15
Error: 4 failed steps!
brew test --retry --verbose hyperkit
brew test --retry --verbose pinboard-notes-backup
brew test --retry --verbose qxmpp
brew test --retry --verbose treefrog


10.14
Error: 7 failed steps!
brew test --retry --verbose cp2k
brew test --retry --verbose glyr
brew test --retry --verbose howdoi
brew test --retry --verbose hyperkit
brew test --retry --verbose nwchem
brew test --retry --verbose swift
brew test --retry --verbose treefrog
```

**Comment by dtrodrigues** [comment]
Added failures to https://github.com/Homebrew/homebrew-core/issues/66450, none seem related to the python upgrade.

**Pull request closed without merging**
