### PR TITLE
bitcoin 0.15.0.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> brew test bitcoin --verbose
==> FAILED
Testing bitcoin
/usr/bin/sandbox-exec -f /tmp/homebrew20170915-61695-16s4tl.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bitcoin.rb --verbose
==> /usr/local/Cellar/bitcoin/0.15.0.1/bin/test_bitcoin
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /usr/local/Cellar/bitcoin/0.15.0.1/bin/test_bitcoin
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /usr/local/Cellar/bitcoin/0.15.0.1/bin/test_bitcoin
  Expected in: /usr/lib/libSystem.B.dylib

Error: bitcoin: failed
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
The `gnutls` formula has this:

```
    # Fix "dyld: lazy symbol binding failed: Symbol not found: _getentropy"
    # Reported 18 Oct 2016 https://gitlab.com/gnutls/gnutls/issues/142
    if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
      inreplace "configure", "getentropy(0, 0);", "undefinedgibberish(0, 0);"
    end
```

**Comment by ilovezfs** [comment]
I know. I put it there.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by akurdyukov** [comment]
Please check my patch. Tests work for me on 10.11.
```
diff --git a/Formula/bitcoin.rb b/Formula/bitcoin.rb
index 018ef7f..5067b61 100644
--- a/Formula/bitcoin.rb
+++ b/Formula/bitcoin.rb
@@ -1,9 +1,8 @@
 class Bitcoin < Formula
   desc "Decentralized, peer to peer payment network"
   homepage "https://bitcoin.org/"
-  url "https://github.com/bitcoin/bitcoin/archive/v0.14.2.tar.gz"
-  sha256 "e0ac23f01a953fcc6290c96799deeffb32aa76ca8e216c564d20c18e75a25219"
-  revision 2
+  url "https://github.com/bitcoin/bitcoin/archive/v0.15.0.1.tar.gz"
+  sha256 "a2d28632be6918ce23d2fd589f0aecbb2a90579c9345f47fdfe1e77ec31f023e"
   head "https://github.com/bitcoin/bitcoin.git"
 
   bottle do
@@ -28,6 +27,13 @@ class Bitcoin < Formula
 
   def install
     system "./autogen.sh"
+
+    # Fix "dyld: lazy symbol binding failed: Symbol not found: _getentropy"
+    # Reported 18 Oct 2016 https://gitlab.com/gnutls/gnutls/issues/142
+    if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
+      inreplace "configure", "getentropy(nullptr, 32)", "undefinedgibberish(0, 0)"
+    end
+
     system "./configure", "--disable-dependency-tracking",
                           "--disable-silent-rules",
                           "--with-boost-libdir=#{Formula["boost"].opt_lib}",
```

**Comment by ilovezfs** [comment]
Yes, we know that's possible. This needs to be fixed upstream, however.

**Pull request closed without merging**
