### PR TITLE
xonsh 0.3.3

### PR DESCRIPTION
**Pull request by pgoelz**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/129f00a42e9f80bb00cfea39617ebd76ef100734. Thank you for your contribution to Homebrew @pgoelz; we appreciate it! :smiley_cat:

**Comment by pgoelz** [comment]
Thank you! It's amazing how easily accessible all of this is :)

**Comment by DomT4** [comment]
Thanks! Nice to hear you're finding it accessible; we do our best on that but the complexities of package management makes it difficult sometimes. Feel free to shout if there's anything we can make easier or more obvious.

**Comment by pgoelz** [comment]
The only thing where I had to improvise was finding out where the `homebrew-core` repo was located in the file system for committing.
I found it out because vim showed the path to the formula on saving, but if there is a generic way to find the path, this might be a helpful information to add.

**Pull request closed without merging**
