### PR TITLE
carrot2 4.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - /usr/local/Cellar/carrot2/4.0.0/libexec/dcs.sh
```

**Comment by dawidd6** [comment]
Try `libexec/"dcs/dcs.sh"`

**Comment by chenrui333** [comment]
> Try `libexec/"dcs/dcs.sh"`

yeah, they did rewrite the dcs folder completely, the startup script for the jar also needs to be changed.

**Comment by chenrui333** [comment]
> Hey @chenrui333, I have a version to build this from source if you'd like me to submit it (I maintain a Ruby gem for Carrot2).

go ahead, closing this PR now :)

**Pull request closed without merging**
