### PR TITLE
sqlmap 1.0.7

### PR DESCRIPTION
**Pull request by ilovezfs**
Also, test tweaks to excise the backticks and reduce repetition

### CODE REVIEW

**Comment by DomT4** [comment]
The backtics in `test do` are slightly grim but not your fault. 👍.

**Comment by ilovezfs** [comment]
I wonder if there's a technical term for the fear of backticks.

**Comment by DomT4** [comment]
Domitus.

**Comment by ilovezfs** [comment]
@DomT4 Better?
```
    data = %w[Bob 14 Sue 12 Tim 13]
    create = "create table students (name text, age integer);\n"
    data.each_slice(2) do |n, a|
      create << " insert into students (name, age) values ('#{n}', '#{a}');\n"
    end
    pipe_output("/usr/bin/sqlite3 school.sqlite", create, 0)
    select = "select name, age from students order by age asc;"
    args = %W[--batch -d sqlite://school.sqlite --sql-query "#{select}"]
    output = shell_output("#{bin}/sqlmap #{args.join(" ")}")
    data.each_slice(2) { |n, a| assert_match "#{n}, #{a}", output }
```

**Comment by DomT4** [comment]
👍 ❤️, although no need to hardcode `/usr/bin/sqlite3` unless you really want to.

**Pull request closed without merging**
