### PR TITLE
php 7.2.12

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@SMillerDev do you think we can combine that with the changes in #33909 to make one fewer upgrade for users?

**Comment by SMillerDev** [comment]
Sure, I'll ask there to drop the revision

**Comment by fxcoudert** [comment]
Or just incorporate into this PR. Either way, we'll need to re-test to build bottles that have both changes.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please now that https://github.com/Homebrew/homebrew-core/pull/33651 is merged

**Pull request closed without merging**
