### PR TITLE
swiftlint 0.28.2

### PR DESCRIPTION
**Pull request by jpsim**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jpsim** [comment]
This appears to have the same failure on Mojave as #34049. I don't know what that failure means, so I'd appreciate any help from maintainers to address this.

**Comment by norio-nomura** [comment]
I opened https://github.com/realm/SwiftLint/pull/2473 that can be used for avoiding the issue.

**Comment by jpsim** [comment]
Thanks! Updated the has here to hopefully resolve.

**Comment by norio-nomura** [comment]
Oops! Sorry, I didn't explain that It needs to set `SWIFTLINT_DISABLE_SOURCEKIT=1` on executing test for using realm/SwiftLint#2473.

**Comment by jpsim** [comment]
Ah yes of course. Updated.

**Comment by javian** [comment]
It currently fails saying
```
10:10:33   RuntimeError: 0.28.1 tag should be b458e20f2720a52f69a1d45ffebf45ac264ed20e
10:10:33 but is actually 4955c173a097b6b0dc49c495b462112da09ed099
```

**Comment by norio-nomura** [comment]
It seems to need new tag `0.28.2` or force move `0.28.1`.

**Comment by javian** [comment]
We can only do stable releases so it would have to be `0.28.1` since `.2` isn't released yet.

**Comment by jpsim** [comment]
Just released 0.28.2 https://github.com/realm/SwiftLint/releases/tag/0.28.2

**Comment by javian** [comment]
Thanks @jpsim !

**Pull request closed without merging**
