### PR TITLE
webkitgtk 2.14.5

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@tschoonj weren't we avoiding upgrading this further for the time being?

**Review by tschoonj — COMMENTED** [review]
Let's first see if this compiles properly...

@nijikon Have you tried compiling this locally? And tried running the MiniBrowser or any other software package that uses webkitgtk?

**Comment by DomT4** [comment]
Good news, more CVEs have been assigned to the [existing version](https://webkitgtk.org/security/WSA-2017-0002.html) 😓.

**Comment by MikeMcQuaid** [comment]
I think we need to think seriously (but sadly) about killing this formula and everything that depends on it.

**Comment by DomT4** [comment]
Nudged for that a while back without much luck, but I think Homebrew has now shown a consistent problem updating this formula on macOS without having to constantly go through the report bug => wait for fix => apply fix cycle, whilst in the mean time known CVEs sit there and get shipped out to users.

IIRC it's not actually used by other formulae much _by default_. And maybe this version and everything that can use it now work fine, but that hasn't been the long-term situation so far 😢.

**Comment by ilovezfs** [comment]
:-1: to killing this over some new CVs and irrelevant prior breakage.

**Comment by DomT4** [comment]
Yes, Homebrew definitely has no prior history of killing formulae that have persistently proven prone to breakage on macOS. None at all. And who needs security 👀.

**Comment by ilovezfs** [comment]
Not taking the bait. Nope, not gonna do it.

**Comment by tschoonj** [comment]
Feel free to boneyard it. The quartz backend is not really supported upstream anyway.

**Comment by ilovezfs** [comment]
I defer to @tschoonj since the MiniBrowser is unhappy https://gist.github.com/ilovezfs/c5a735bb9cf803048de011640c37c4ec

**Comment by nijikon** [comment]
What is our decision? Are we killing it?

**Comment by ilovezfs** [comment]
>I defer to @tschoonj since the MiniBrowser is unhappy https://gist.github.com/ilovezfs/c5a735bb9cf803048de011640c37c4ec (which is 2.14.4 built locally)

Yes. :fire:

**Pull request closed without merging**
