### PR TITLE
gdk-pixbuf 2.36.8

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by fxcoudert** [comment]
Same as pango:

```
failed: brew linkage --test open-scene-graph
        Missing libraries:
  /usr/local/opt/ilmbase/lib/libHalf.12.dylib
  /usr/local/opt/ilmbase/lib/libIex-2_2.12.dylib
  /usr/local/opt/ilmbase/lib/libIlmThread-2_2.12.dylib
  /usr/local/opt/liblas/lib/liblas.3.dylib
  /usr/local/opt/liblas/lib/liblas_c.3.dylib
  /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib
```

**Comment by fxcoudert** [comment]
After retest, still the same failure with `open-scene-graph`

**Comment by ilovezfs** [comment]
@fxcoudert it should be fixed now. See https://github.com/Homebrew/homebrew-core/issues/16531.

**Comment by ilovezfs** [comment]
:green_apple:

**Pull request closed without merging**
