### PR TITLE
goreleaser 0.107.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Comment by zbeekman** [comment]
We need to be better about checking for OpenPRs. I'm guilty of this too, for sure. But upstream wants to transition to tag & sha versioning to help make adjustments to the build, and doing it when a new release drops is the best time, otherwise audit complains about sha256 missmatch. (See #39167)

**Comment by chenrui333** [comment]
@zbeekman Sure, I will be aware of this when doing the update next time!

**Comment by chenrui333** [comment]
@zbeekman I thought this formula is already using `go modules`?

**Pull request closed without merging**
