### PR TITLE
pre-commit 0.13.6

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by fxcoudert — CHANGES_REQUESTED** [review]
`aspy.yaml 0.2.2` is the latest version, other resources are up to date

**Comment by ilovezfs** [comment]
feel free to update it

**Comment by fxcoudert** [comment]
I will if I get the time, I still haven't fully figured out how to push to your branches. Last time I tried, I completely messed up my git setup :(

**Comment by ilovezfs** [comment]
note you can make the change in the gui and squash at pull time

**Comment by fxcoudert** [comment]
I'm using the github source release for `aspy.yaml` because on [pypi](https://pypi.python.org/pypi/aspy.yaml/0.2.2) it only has a `.whl`.

**Review by fxcoudert — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @fxcoudert. That would explain why homebrew-pypi-poet always blows up on that one. CC @tdsmith

**Comment by tdsmith** [comment]
Nothing actionable from poet's end, I think; wheels are binary formats. We *could* add a case for pure-python wheels but declining to publish sdists seems like a weird decision to me.

**Comment by ilovezfs** [comment]
@tdsmith this is what happens:
```
bash-3.2$ mkdir ~/Developer/precommitblowsup
bash-3.2$ cd ~/Developer/precommitblowsup/
bash-3.2$ virtualenv venv
Using base prefix '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/joe/Developer/precommitblowsup/venv/bin/python3.6
Also creating executable in /Users/joe/Developer/precommitblowsup/venv/bin/python
Installing setuptools, pip, wheel...done.
bash-3.2$ source venv/bin/activate
(venv) bash-3.2$ pip install pre-commit
Collecting pre-commit
  Downloading pre_commit-0.13.6-py2.py3-none-any.whl (135kB)
    100% |████████████████████████████████| 143kB 1.1MB/s 
Collecting nodeenv>=0.11.1 (from pre-commit)
  Using cached nodeenv-1.1.2.tar.gz
Collecting pyyaml (from pre-commit)
Collecting aspy.yaml (from pre-commit)
  Using cached aspy.yaml-0.2.2-py2.py3-none-any.whl
Requirement already satisfied: six in ./venv/lib/python3.6/site-packages (from pre-commit)
Collecting cached-property (from pre-commit)
  Using cached cached_property-1.3.0-py2.py3-none-any.whl
Collecting virtualenv (from pre-commit)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Building wheels for collected packages: nodeenv
  Running setup.py bdist_wheel for nodeenv ... done
  Stored in directory: /Users/joe/Library/Caches/pip/wheels/b8/d5/01/5e8f6e846212747b154528bfc49796590883bedb4137793b08
Successfully built nodeenv
Installing collected packages: nodeenv, pyyaml, aspy.yaml, cached-property, virtualenv, pre-commit
Successfully installed aspy.yaml-0.2.2 cached-property-1.3.0 nodeenv-1.1.2 pre-commit-0.13.6 pyyaml-3.12 virtualenv-15.1.0
(venv) bash-3.2$ pip install homebrew-pypi-poet
Collecting homebrew-pypi-poet
  Using cached homebrew_pypi_poet-0.9.0-py2.py3-none-any.whl
Collecting jinja2 (from homebrew-pypi-poet)
  Using cached Jinja2-2.9.5-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from homebrew-pypi-poet)
Collecting MarkupSafe>=0.23 (from jinja2->homebrew-pypi-poet)
Requirement already satisfied: six>=1.6.0 in ./venv/lib/python3.6/site-packages (from setuptools->homebrew-pypi-poet)
Requirement already satisfied: packaging>=16.8 in ./venv/lib/python3.6/site-packages (from setuptools->homebrew-pypi-poet)
Requirement already satisfied: appdirs>=1.4.0 in ./venv/lib/python3.6/site-packages (from setuptools->homebrew-pypi-poet)
Requirement already satisfied: pyparsing in ./venv/lib/python3.6/site-packages (from packaging>=16.8->setuptools->homebrew-pypi-poet)
Installing collected packages: MarkupSafe, jinja2, homebrew-pypi-poet
Successfully installed MarkupSafe-1.0 homebrew-pypi-poet-0.9.0 jinja2-2.9.5
(venv) bash-3.2$ poet -f pre-commit
/Users/joe/Developer/precommitblowsup/venv/lib/python3.6/site-packages/poet/poet.py:97: PackageVersionNotFoundWarning: Could not find an exact version match for aspy.yaml version 0.2.2; using newest instead
  format(name, version), PackageVersionNotFoundWarning)
Traceback (most recent call last):
  File "/Users/joe/Developer/precommitblowsup/venv/bin/poet", line 11, in <module>
    sys.exit(main())
  File "/Users/joe/Developer/precommitblowsup/venv/lib/python3.6/site-packages/poet/poet.py", line 238, in main
    print(formula_for(args.formula, args.also))
  File "/Users/joe/Developer/precommitblowsup/venv/lib/python3.6/site-packages/poet/poet.py", line 156, in formula_for
    nodes = merge_graphs(make_graph(p) for p in [package] + also)
  File "/Users/joe/Developer/precommitblowsup/venv/lib/python3.6/site-packages/poet/poet.py", line 182, in merge_graphs
    for g in graphs:
  File "/Users/joe/Developer/precommitblowsup/venv/lib/python3.6/site-packages/poet/poet.py", line 156, in <genexpr>
    nodes = merge_graphs(make_graph(p) for p in [package] + also)
  File "/Users/joe/Developer/precommitblowsup/venv/lib/python3.6/site-packages/poet/poet.py", line 142, in make_graph
    package_data = research_package(package, dependencies[package]['version'])
  File "/Users/joe/Developer/precommitblowsup/venv/lib/python3.6/site-packages/poet/poet.py", line 105, in research_package
    d['url'] = artefact['url']
TypeError: 'NoneType' object is not subscriptable
(venv) bash-3.2$
```

**Comment by ilovezfs** [comment]
@tdsmith https://github.com/asottile/aspy.yaml/issues/5

**Comment by asottile** [comment]
@tdsmith  the choice to not push a sdist here is intentional (for python2.6's sake) -- you can see the reasoning here: https://github.com/asottile/aspy.yaml/issues/5#issuecomment-290083837

That said, I don't care for python2.6 any more and will release a new version which both doesn't support python2.6 and has a source distribution if it appeases brew.

poet should really allow pure python wheels, they do not contain the binary bits you are attempting to exclude.  If you're using modern pip in some way, the `--no-binary :all:` option does what you want.

**Comment by tdsmith** [comment]
https://github.com/tdsmith/homebrew-pypi-poet/pull/50 will fix the crash.

**Pull request closed without merging**
