### PR TITLE
Python 3.8: ansible, ansible-lint

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Ref https://github.com/Homebrew/homebrew-core/issues/47274

### CODE REVIEW

**Comment by oschrenk** [comment]
Not sure where to report this but I see a bunch of errors when working with ansible 2.9.2_1 and python@3.8

```
PLAY [apply common configuration to all nodes] **********************************************
/usr/local/Cellar/ansible/2.9.2_1/libexec/lib/python3.8/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py:28: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sys.version_info[0] is 2 and  sys.version_info[1] is 1:
/usr/local/Cellar/ansible/2.9.2_1/libexec/lib/python3.8/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py:28: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sys.version_info[0] is 2 and  sys.version_info[1] is 1:

TASK [Gathering Facts] **********************************************************************
/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
  warnings.warn('resource_tracker: process died unexpectedly, '
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocessing.resource_tracker'
```

Is there a way to still use ansible with 3.7 ?

**Comment by bayandin** [comment]
> /usr/local/Cellar/ansible/2.9.2_1/libexec/lib/python3.8/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py:28: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if sys.version_info[0] is 2 and  sys.version_info[1] is 1:
> /usr/local/Cellar/ansible/2.9.2_1/libexec/lib/python3.8/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py:28: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if sys.version_info[0] is 2 and  sys.version_info[1] is 1:

These warning definetely came from `python@3.8` and I know how to fix them.


> /usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
>   warnings.warn('resource_tracker: process died unexpectedly, '
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocessing.resource_tracker'

Regarding this one, It's unclear for me right now, could you run ansible with [`-vvvv`](https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-v) flag (to get verbose output)

**Comment by oschrenk** [comment]
See https://gist.github.com/oschrenk/b88f84c2a0321f5564180805a679f287

**Comment by oschrenk** [comment]
I also found this: https://github.com/spack/spack/issues/13256

Let me know if I can do anything to help debug

**Pull request closed without merging**
