### PR TITLE
mailhog: references to specific dependency revisions removed.

### PR DESCRIPTION
**Pull request by maijs**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

This PR removes references to specific dependency revisions and makes sure that, if built from source, MailHog is using the latest versions of its dependencies. This issue was originally mentioned by @swrobel in #2501.

### CODE REVIEW

**Comment by dunn** [comment]
My comment at https://github.com/Homebrew/homebrew-core/issues/2501#issuecomment-230158489 might have been poorly worded.  Since Go usually pulls the latest code, when we add a `go_resource` to a formula we generally use the latest commit, but we still want to pin the dependency to that commit so things don't shift around underneath us and cause breakages.

**Comment by DomT4** [comment]
Yeah, we're not going to accept this as-is.

99% of the reason `go_resource`s became a thing is because Go's old dependency system of simply fetching the latest commit from the master branch of a dependency was a disaster for consistency. No desire to go back there.

**Comment by swrobel** [comment]
@DomT4 would this be acceptable for building the HEAD version? Maybe we could have the versioned released in homebrew-binary and this formula would just build from HEAD...

**Comment by dunn** [comment]
The HEAD build can use unpinned resources in its `head do` block (see e.g., [`telegraf.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/telegraf.rb)), but we don't allow HEAD-only formula.

**Comment by swrobel** [comment]
but, but...

Monty Python

(that was my attempt at a head-only joke if that wasn't obvious)

**Comment by maijs** [comment]
I will pin down the commits that correspond to the 0.2.0 release. Stay tuned.

**Comment by MikeMcQuaid** [comment]
Closing due to lack of response.

**Comment by swrobel** [comment]
Honestly I don't see how that's a reasonable solution: the current formula is broken

**Comment by DomT4** [comment]
Did something a bit naughty: https://github.com/Homebrew/homebrew-core/pull/4488. Not completely ideal, but increasingly it's either this or the boneyard, so let's try one form of drastic before trying the other form of drastic 😅.

**Pull request closed without merging**
