### PR TITLE
node: updated to python@3.8 and revision bump

### PR DESCRIPTION
**Pull request by domrim**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
updates node to use python@3.8, adding progress to #47274

### CODE REVIEW

**Comment by bayandin** [comment]
We have formulae depend on both `node`  and `python` (for example `emscripten`) and if we bump only `node` to use `python@3.8` it could make such formula linked with both `python` and `python@3.8` so we need to update them at once

**Comment by chenrui333** [comment]
Bump node to the latest, #52192

**Comment by chenrui333** [comment]
Like @bayandin said, we might want to make sure dual dependency build bumped to use python 3.8

**Comment by bayandin** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/52781

**Pull request closed without merging**
