### PR TITLE
macpine: depends on qemu

### PR DESCRIPTION
**Pull request by gpanders**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Add QEMU as a dependency of macpine.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why? What doesn't work without it?

**Comment by p-linnane** [comment]
Per the repo's readme:
>Macpine depends on QEMU >= 6.2.0_1
#brew update
#brew upgrade
brew install qemu

**Review by p-linnane — DISMISSED** [review]

**Comment by fxcoudert** [comment]
Always? Qemu says it's an emulator for x86 and powerpc, but alpine can also create aarch64 instances: does it need qemu then?

**Comment by p-linnane** [comment]
@gpanders can you please provide some additional context here?

**Comment by gpanders** [comment]
This is indeed in response to the note in the README, as @p-linnane already pointed out.

>Always? Qemu says it's an emulator for x86 and powerpc, but alpine can also create aarch64 instances: does it need qemu then? If so, maybe we need a better test?

QEMU is an emulator for x86 and Power PC but also acts a hypervisor (using Apple's Hypervisor.framework) on ARM Macs to create aarch64 virtual machines. Macpine uses QEMU to perform all of its virtualization. It is a critical dependency (I should have included it when I first packaged macpine, it was an oversight on my part).

Just as a demonstration, running `alpine launch` without QEMU installed results in:

```
2022/11/30 12:38:45 unable to resize disk: qemu-img is not available on $PATH. ensure qemu is installed
```

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
