### PR TITLE
mysql@5.5: removed due to EOL

### PR DESCRIPTION
**Pull request by Bo98**
This one still got 1,132 installs in the last 30 days (though move active formulae have been removed - see PHP). However it is approaching 1 year since EOL and there is very likely unfixed security issues.

If removed, it is also one less formula on OpenSSL 1.0 to worry about :-)

If you still feel it is too early, feel free to leave this on the backburner.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does anything depend on it? That's a high amount of installs.
If nothing depends on it I'm good with removing it.

**Comment by Bo98** [comment]
In terms of `depends_on` there's nothing that I can see.

**Comment by hanchenxu** [comment]
When installing MySQL-python, I rely on MySQL @ 5.5. I hope to continue to support the mysql@5.5 installation.

**Comment by SMillerDev** [comment]
Then you'll have to maintain it in your own tap. https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap explains how to do so.

**Pull request merged**
