### PR TITLE
signal-cli 0.8.1

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/signal-cli/0.8.1/bin/signal-cli --version
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
Error: signal-cli: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /tsdevice:\/\?uuid=/ to match "Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp\nWARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup\nMissing required native library dependency: libsignal-client\n".
```

**Comment by carlocab** [comment]
Not really sure what's going on with the test. It works if I run them directly, but fails when run in `brew test`.

**Comment by carlocab** [comment]
Looks like we need to do something like this: https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

Based on the error
```
Missing required native library dependency: libsignal-client
```

**Comment by mtigas** [comment]
Hi y'all; I've opened #74837 which is my attempt at fixing this formula. That PR provides a build-from-source step for libsignal-client and also fetches the prebuilt `libzkgroup.dylib` for MacOS x86_64.

**Pull request closed without merging**
