### PR TITLE
brew-gem 0.9.0

### PR DESCRIPTION
**Pull request by nicksieger**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zbeekman** [comment]
Would you be able to add a more meaningful test in addition to this formula bump?

**Comment by nicksieger** [comment]
@zbeekman not sure what you're looking for; is there an example of the kinds of tests you like to see that accompany new versions of formulas?

**Comment by zbeekman** [comment]
Well it's just an effort to improve the quality of the packages within Homebrew and better detect breakage in the future. A test of the functionality of the package beyond just the help or version string would be good. I.e., a test to verify basic functionality.

Any chance you have a test that gets run during development that we could recycle here? Or we could try installing and uninstalling a pinned version of some trivial gem?

**Comment by nicksieger** [comment]
I see. So I tried something like this:
```ruby
  test do
    begin
      system bin/"brew-gem", "install", "gli"
      assert (bin/"gli").exists?
    ensure
      system bin/"brew-gem", "uninstall", "gli"
    end
  end
```
but I'm not sure whether it's possible for that to work due to sandboxing around the tests. Any suggestions?

**Comment by fxcoudert** [comment]
Could we run `brew gem info` on something and check its output?

**Comment by fxcoudert** [comment]
Merged now, to avoid delaying the update. We'd welcome another pull request with an improved test, @nicksieger !

**Pull request merged**
