### PR TITLE
pangomm 2.48.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>build failure</summary>

```
==> meson --prefix=/usr/local/Cellar/pangomm/2.48.0 --libdir=/usr/local/Cellar/pangomm/2.48.0/lib --buildtype=release --wrap-mode=nofallback ..
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/libsigc++@2/lib/pkgconfig:/usr/local/opt/cairomm@1.14/lib/pkgconfig:/usr/local/opt/glibmm/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/libsigc++@2/lib/pkgconfig:/usr/local/opt/cairomm@1.14/lib/pkgconfig:/usr/local/opt/glibmm/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig'
The Meson build system
Version: 0.56.0
Source dir: /private/tmp/pangomm-20201219-4658-bie2vb/pangomm-2.48.0
Build dir: /private/tmp/pangomm-20201219-4658-bie2vb/pangomm-2.48.0/build
Build type: native build
Project name: pangomm
Project version: 2.48.0
Using 'CXX' from environment with value: 'clang++'
C++ compiler for the host machine: clang++ (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.17)")
C++ linker for the host machine: clang++ ld64 530
Using 'CXX' from environment with value: 'clang++'
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/local/opt/python@3.9/bin/python3)
Found pkg-config: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config (0.29.2)
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/libsigc++@2/lib/pkgconfig:/usr/local/opt/cairomm@1.14/lib/pkgconfig:/usr/local/opt/glibmm/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig'
Run-time dependency pangocairo found: YES 1.48.0
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency cairomm-1.16 found: NO (tried pkgconfig and framework)

../meson.build:109:0: ERROR: Dependency "cairomm-1.16" not found, tried pkgconfig and framework

A full log can be found at /private/tmp/pangomm-20201219-4658-bie2vb/pangomm-2.48.0/build/meson-logs/meson-log.txt
```

</details>

**Comment by chenrui333** [comment]
> ../meson.build:109:0: ERROR: Dependency "cairomm-1.16" not found, tried pkgconfig and framework

relates to #65090

**Comment by chenrui333** [comment]
license ref:
```
# This file is part of pangomm.

project('pangomm', 'cpp',
  version: '2.48.0',
  license: 'LGPLv2.1+',
  default_options: [
    'cpp_std=c++17'
  ],
  meson_version: '>= 0.50.0', # required for python3.path()
)
```

**Comment by fxcoudert** [comment]
pinging @tschoonj who knows this stuff best

**Comment by chenrui333** [comment]
Here is my current diff:

<details>
<summary>diff</summary>

```
diff --git a/Formula/pangomm.rb b/Formula/pangomm.rb
index 7f4d7160eba..cecac1d6b05 100644
--- a/Formula/pangomm.rb
+++ b/Formula/pangomm.rb
@@ -19,19 +19,19 @@ class Pangomm < Formula
   depends_on "meson" => :build
   depends_on "ninja" => :build
   depends_on "pkg-config" => :build
-  depends_on "cairomm@1.14"
+  depends_on "cairomm"
   depends_on "glibmm"
   depends_on "pango"

   def install
-    ENV.cxx11
-
     mkdir "build" do
       system "meson", *std_meson_args, ".."
+
       system "ninja"
       system "ninja", "install"
     end
   end
+
   test do
     (testpath/"test.cpp").write <<~EOS
       #include <pangomm.h>
@@ -42,7 +42,7 @@ class Pangomm < Formula
       }
     EOS
     cairo = Formula["cairo"]
-    cairomm = Formula["cairomm@1.14"]
+    cairomm = Formula["cairomm"]
     fontconfig = Formula["fontconfig"]
     freetype = Formula["freetype"]
     gettext = Formula["gettext"]
```

</details>

And still has same error in my local.

**Comment by tschoonj** [comment]
Yep I was going to do this one tonight as well as the new atkmm

Basically the devs of the C++ bindings have decided to break backwards compatibility and came up with these new releases whose shared libs and pkgconfig files have different abi versions in their names.

**Comment by chenrui333** [comment]
Sounds good, closing this PR. :)

**Pull request closed without merging**
