### PR TITLE
libplctag 2.0.31

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Using a `send` flag that macOS seens to be missing: https://linux.die.net/man/2/send

```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -I/tmp/libplctag-20200214-46275-13ekzhd/libplctag-2.0.30/src -I/tmp/libplctag-20200214-46275-13ekzhd/libplctag-2.0.30/src/platform/linux -I/tmp/libplctag-20200214-46275-13ekzhd/libplctag-2.0.30/src/protocols  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk   -std=c99  -Wall -pedantic -Wextra -Wc99-c11-compat -Wconversion -fms-extensions -fno-strict-aliasing -D__USE_POSIX=1 -D_POSIX_C_SOURCE=200809L -std=c99 -o CMakeFiles/plctag_static.dir/src/platform/linux/platform.c.o   -c /tmp/libplctag-20200214-46275-13ekzhd/libplctag-2.0.30/src/platform/linux/platform.c
/tmp/libplctag-20200214-46275-13ekzhd/libplctag-2.0.30/src/platform/linux/platform.c:997:46: error: use of undeclared identifier 'MSG_NOSIGNAL'
    rc = (int)send(s->fd, buf, (size_t)size, MSG_NOSIGNAL);
                                             ^
1 error generated.
make[2]: *** [CMakeFiles/plctag.dir/src/platform/linux/platform.c.o] Error 1
make[1]: *** [CMakeFiles/plctag.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/tmp/libplctag-20200214-46275-13ekzhd/libplctag-2.0.30/src/platform/linux/platform.c:997:46: error: use of undeclared identifier 'MSG_NOSIGNAL'
    rc = (int)send(s->fd, buf, (size_t)size, MSG_NOSIGNAL);
                                             ^
1 error generated.
make[2]: *** [CMakeFiles/plctag_static.dir/src/platform/linux/platform.c.o] Error 1
make[1]: *** [CMakeFiles/plctag_static.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mistydemeo** [comment]
`v2.0.31` apparently adds Mac support: https://github.com/kyle-github/libplctag/releases

**Review by mistydemeo — COMMENTED** [review]
`sha256` issue?

```
==> Downloading https://github.com/kyle-github/libplctag/archive/v2.0.31.tar.gz
==> Downloading from https://codeload.github.com/kyle-github/libplctag/tar.gz/v2.0.31
Warning: Formula reports different SHA256: 9453e194542f2a6c070cbd06b1f5b5ee749817aa9d599e3b52bd4a8bb9db4bfd
Downloaded to: /Users/brew/Library/Caches/Homebrew/downloads/68aa178f8e09e4db9e1d5a47b4a4ead2a821ff4deaf282d5f0bece12b1237d68--libplctag-2.0.31.tar.gz
SHA256: 9106381ae2ee742360ec2a2d7bbdcd1b4a4caabfa7037a5315364382b7b5335a
```

**Comment by zachauten** [comment]
@mistydemeo Looks like I didn't follow the redirect when I downloaded to get the sha256. Fixed!

**Pull request closed without merging**
