### PR TITLE
badtouch 0.7.2

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
License: https://github.com/kpcyrd/badtouch/blob/28a5813bac90ec86a1b47998a88849225e4e7a2e/README.md#license

**Comment by chenrui333** [comment]
```
==> Testing badtouch
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210111-34196-4uhex3.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/badtouch.rb --verbose
==> /usr/local/Cellar/badtouch/0.7.2/bin/badtouch oneshot -vvx /private/tmp/badtouch-test-20210111-34197-1dl6wbi/true.lua foo
[2021-01-11T19:14:29Z DEBUG badtouch::ulimit] soft_limit=10240, hard_limit=9223372036854775807
[2021-01-11T19:14:29Z INFO  badtouch::ulimit] setting NOFILE limit to 9223372036854775807
Error: Failed to set RLIMIT_NOFILE

Caused by:
    Invalid argument (os error 22)
```

**Comment by carlocab** [comment]
Error is explained in https://github.com/kpcyrd/badtouch/issues/76

**Comment by carlocab** [comment]
Superseded by #69022.

**Pull request closed without merging**
