### PR TITLE
cfn-lint 0.29.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by PatMyron** [comment]
[There seem to be issues with this Homebrew release missing the new `networkx` dependency](https://github.com/aws-cloudformation/cfn-python-lint/issues/1434)

**Comment by miparnisari** [comment]
@chenrui333 do we have to manually update this file to bring in the new dependency?

**Comment by chenrui333** [comment]
let me filed a patch for this. Give me a second.

**Comment by PatMyron** [comment]
@chenrui333 does [`brew bump-formula-pr`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb) need to be fixed as well to prevent this from re-occuring?

**Pull request closed without merging**
