### PR TITLE
openjdk 19.0.2

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
This should be a long build.

**Comment by iMichka** [comment]
Fix for `smali`: #121270

**Comment by iMichka** [comment]
Attempt to update `verapdf`: #121273

**Comment by iMichka** [comment]
Attempt to fix `teku`: #121275

**Comment by chenrui333** [comment]
As we have already regression tested the build (and found the issues), I think we can skip-dependants check for the next run.

**Comment by chenrui333** [comment]
previous workflow run ref, https://github.com/Homebrew/homebrew-core/actions/runs/3977833276/jobs/6819288636

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
