### PR TITLE
syncthing-inotify 0.8.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Apparently they've broken their `godep` setup.

**Comment by ilovezfs** [comment]
@DomT4 Apparent would be the key word. I cannot reproduce this failure locally. Can you?

**Comment by DomT4** [comment]
Yup:
```
==> godep restore
godep: Dep (github.com/cenkalti/backoff) restored, but was unable to load it with error:
	Package (math/rand) not found
godep: Dep (github.com/syncthing/syncthing/lib/ignore) restored, but was unable to load it with error:
	Package (bufio) not found
godep: Dep (github.com/zillode/notify) restored, but was unable to load it with error:
	Package (runtime/cgo) not found
godep: Error checking some deps.
```

**Comment by ilovezfs** [comment]
@DomT4 Unfortunately,
```
iMac-TMP:homebrew-core joe$ git bisect bad
40543c601bb1f3e12eb79b68cbabc50f095ab2ab is the first bad commit
commit 40543c601bb1f3e12eb79b68cbabc50f095ab2ab
Author: Gabriel Handford <gabrielh@gmail.com>
Date:   Mon Jul 18 11:37:03 2016 -0700

    go 1.6.3
    
    Closes #3092.
    
    Signed-off-by: Dominyk Tiller <dominyktiller@gmail.com>

:040000 040000 d4b8cc7ecee6217b1e1ea291a3796f9dc6a2ad8a 49020a8b398c39b7bdc43292f26a08070a3125e9 M	Formula
```

The current version in core (0.8.2) is also broken now.

**Comment by DomT4** [comment]
Not a lot we can do about that, Go 1.6.3 contained security fixes. Any idea if the problem is with `go` itself or `godep`?

**Comment by ilovezfs** [comment]
investigating further... not sure yet

**Comment by ilovezfs** [comment]
Looks like rebuilding godep fixed it. Revision bump time :)

**Comment by DomT4** [comment]
That'd make sense, I let `godep` pour from bottle for testing locally, as would CI.

**Comment by ilovezfs** [comment]
@DomT4 :green_apple:

**Comment by DomT4** [comment]
🎉 👍

**Comment by ilovezfs** [comment]
@DomT4 it makes me wonder if any of our other go tools are busted at the moment (e.g., govendor).

**Pull request closed without merging**
