### PR TITLE
node 6.7.0

### PR DESCRIPTION
**Pull request by JLHwung**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Does npm need to be bumped?

**Comment by DomT4** [comment]
Nope. We bumped it too hard quite considerably last time, so upstream are going to be playing catchup for a while, heh.

Merged in https://github.com/Homebrew/homebrew-core/commit/bd05ec39385a7e68737dd418aa44defd290509e1. Thank you for another contribution to Homebrew @JLHwung! 😺.

**Comment by JLHwung** [comment]
@DomT4 What's the policy of bumping `npm` version of `node`? Here is the comments from the source
```
# We track major/minor from upstream Node releases.
# We will accept *important* npm patch releases when necessary.
```
I would like to make sure if this is the bumping policy.

AFAIK `node` 6.7.0 does not bundle `npm` 3.10.7. So, is 3.10.7 an *important* patch releases or just a situation where it is bumped accidentally?

**Comment by DomT4** [comment]
We track what Node bundles upstream, unless what Node bundles upstream has security or major usability problems resolved in a newer release. Our last bump was just too heavy on the npm update, but no point reverting, will just try to avoid further npm updates till upstream catches us up.

**Comment by DomT4** [comment]
Nobody's reported any problems so let's leave it where it is and just try to remember in future to keep it as in sync as possible.

**Comment by mech** [comment]
Encounter the strange:

```
(node:4558) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
```

with NPM -v3.10.7, reportedly fixed on -v3.10.8

Just annoying warnings, but NPM appear still working.

**Pull request closed without merging**
