### PR TITLE
git-annex 10.20230126

### PR DESCRIPTION
**Pull request by nirgo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by nirgo** [comment]
Looks like a similar [failure](https://github.com/Homebrew/homebrew-core/pull/117054#issuecomment-1336199453).

**Comment by yarikoptic** [comment]
on that failed arm:
```
  Error: cabal: Failed to build tls-1.6.0 (which is required by
  git-annex-10.20230126). The build process terminated with exit code -10
```

**Comment by nirgo** [comment]
> on that failed arm:
> 
> ```
>   Error: cabal: Failed to build tls-1.6.0 (which is required by
>   git-annex-10.20230126). The build process terminated with exit code -10
> ```

Is it possible that this issue is either CI-specific or intermittent? I ran 5x builds on both macOS 13.2 (M1 Pro) and 13.2.1 (M1) without issues. To eliminate intermittent, is it possible to only rerun the 13-arm64 job?

**Comment by nirgo** [comment]
It looks like 13-arm64 is an ephemeral runner. Is there an easy way to replicate its config for more verbose testing?

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
