### PR TITLE
ghc 8.0.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- run the upstream tests if building a bottle
- add a workaround for a segfault that occurs on at least Skylake
- simplify the workaround for the nm POSIX compliance bug

### CODE REVIEW

**Comment by DomT4** [comment]
@ilovezfs Feel free to just bump the timeout to a crazy number if the first build fails in future 😺.

**Comment by ilovezfs** [comment]
Yeah I thought 120 was going to be enough. Apparently 60^2 would have been a better idea than 60*2.

**Comment by DomT4** [comment]
😆 Don't tempt fate, with GHC you might actually need 60^2.

**Comment by ilovezfs** [comment]
Locally,
```
==> Summary
/usr/local/Cellar/ghc/8.0.1: 5,715 files, 1G, built in 57 minutes 52 seconds
```
So one would hope not.

**Comment by ilovezfs** [comment]
@DomT4 woo hoo! :green_apple:

**Comment by DomT4** [comment]
Nice! Took almost three times longer on CI than it did for you locally 🙈.

**Comment by ilovezfs** [comment]
BTW, apparently setting `-O0` speeds up build times for ghc by 3-4 times: https://github.com/snowleopard/hadrian

**Comment by ilovezfs** [comment]
Got git-annex to build with this. Only required a couple tweaks and :tada: 
```
All 273 tests passed (179.27s)
iMac-TMP:~ joe$
```

**Comment by ilovezfs** [comment]
This is the status of the GHC dependent formulae with respect to GHC 8.0.1. I have set up a tap with the "minor patches" mentioned below: https://github.com/ilovezfs/homebrew-ghc/tree/master/Formula

build without changes:
x agda
x arx
x cabal-install
x hadolint
x highlighting-kate
x mighttpd2
x purescript
x qriollo
x shellcheck
x texmath

build with minor patches:
 - [x] cgrep
 - [x] cless
 - [x] darcs
 - [x] elm
 - [x] git-annex
 - [x] haskell-stack
 - [x] hledger
 - [x] pandoc
 - [x] pandoc-citeproc
 - [x] homebrew/devel-only/elm-format

broken: (not all necessarily due to GHC 8)
 - [ ] cryptol
 - [ ] idris
 - [ ] pandoc-crossref
 - [ ] postgrest
 - [ ] homebrew/gui/threadscope

**Comment by ilovezfs** [comment]
This fixes cryptol, but it uses a heretical method: https://github.com/ilovezfs/homebrew-ghc/blob/482b6dfe74066b17eba62fc1d077f770acaf858e/Formula/cryptol.rb#L47

If only `resource do` blocks could have their own `patch do` blocks …

**Comment by ilovezfs** [comment]
And this fixes `postgrest`:
```
diff --git a/Formula/postgrest.rb b/Formula/postgrest.rb
index 01a68d4..3f4d3ea 100644
--- a/Formula/postgrest.rb
+++ b/Formula/postgrest.rb
@@ -21,7 +21,29 @@ class Postgrest < Formula
   depends_on "postgresql"
 
   def install
-    install_cabal_package :using => ["happy"]
+    # GHC 8 compat
+    cabalcfg = "allow-newer: base,transformers"
+    cabalcfg << "\nconstraints:"
+    cabal_sandbox do
+      %w[
+        bytestring-tree-builder 0.2.6
+        postgresql-binary 0.9
+        hasql-transaction 0.4.4.1
+      ].each_slice(2) do |pkg, ver|
+        cabalcfg << "\n#{pkg} ==#{ver}"
+        system "cabal", "get", pkg
+        cabal_sandbox_add_source "#{pkg}-#{ver}"
+        inreplace "#{pkg}-#{ver}/#{pkg}.cabal" do |s|
+          if pkg == "hasql-transaction"
+            s.gsub! "build-depends:", "build-depends: base,"
+          else
+            s.gsub! "ghc-options:", "ghc-options: -XNoImpredicativeTypes"
+          end
+        end
+      end
+      (buildpath/"cabal.config").write(cabalcfg)
+      install_cabal_package :using => ["happy"]
+    end
   end
 
   test do

```

**Comment by ilovezfs** [comment]
`pandoc-crossref` is fixed by https://github.com/ilovezfs/homebrew-ghc/commit/5a6e6a8181af0454e65efdb2f7cd969829cfad57

```
diff --git a/Formula/pandoc-crossref.rb b/Formula/pandoc-crossref.rb
index 128d5c3..833b1dd 100644
--- a/Formula/pandoc-crossref.rb
+++ b/Formula/pandoc-crossref.rb
@@ -21,9 +21,37 @@ class PandocCrossref < Formula
   depends_on "pandoc" => :run
 
   def install
-    args = []
-    args << "--constraint=cryptonite -support_aesni" if MacOS.version <= :lion
-    install_cabal_package *args
+    # GHC 8 compat
+    cabal_sandbox do
+      # https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#template-haskell-2.11.0.0
+      # http://git.haskell.org/ghc.git/commitdiff/575abf42e218925e456bf765abb14f069ac048a0
+      inreplace "lib/Text/Pandoc/CrossRef/Util/Settings/Template.hs" do |s|
+        s.gsub! "DataD _ _ params cons' _", "DataD _ _ params _ cons' _"
+        s.gsub! "NewtypeD _ _ params con' _", "NewtypeD _ _ params _ con' _"
+        s.gsub! "VarI _ t' _ _ <- reify accName", "VarI _ t' _ <- reify accName"
+      end
+      (buildpath/"cabal.config").write <<-EOS.undent
+        allow-newer: base,time
+        constraints: data-accessor-template ==0.2.1.12
+      EOS
+      system "cabal", "get", "data-accessor-template"
+      cd "data-accessor-template-0.2.1.12" do
+        inreplace "data-accessor-template.cabal",
+          "Build-Depends:  template-haskell >=2.4 && <2.11",
+          "Build-Depends:  template-haskell >=2.4 && <2.12"
+        inreplace "src-5/Data/Accessor/Template.hs" do |s|
+          s.gsub! "DataD _ _ params cons' _ -> return (params, cons')",
+            "DataD _ _ params _ cons' _ -> return (params, cons')"
+          s.gsub! "NewtypeD _ _ params con' _ -> return (params, [con'])",
+            "NewtypeD _ _ params _ con' _ -> return (params, [con'])"
+        end
+      end
+      cabal_sandbox_add_source "data-accessor-template-0.2.1.12"
+
+      args = []
+      args << "--constraint=cryptonite -support_aesni" if MacOS.version <= :lion
+      install_cabal_package *args
+    end
   end
 
   test do
```

**Comment by ilovezfs** [comment]
With only one core formula not able to build with GHC 8 at this point, I think this is probably ready to merge, unless people are unhappy with the proposed patches: https://github.com/ilovezfs/homebrew-ghc/commits/master/Formula. If that's the case, then we may need to keep GHC 7 around in core and add a separate GHC 8 formula, or vice versa, or add GHC 8 to homebrew/versions, but I'm inclined to go with the patching and demote GHC 7 to homebrew/versions.

CC @MikeMcQuaid @mistydemeo @DomT4 @zmwangx @mietek @csstaub

**Comment by MikeMcQuaid** [comment]
@ilovezfs I'm 👍 on shipping this but we'll need to boneyard any formulae not working.

**Comment by ilovezfs** [comment]
@MikeMcQuaid Great. I'll merge this and then open PRs for each of the formulae in the tap.

**Pull request closed without merging**
