### PR TITLE
pympress 1.5.3

### PR DESCRIPTION
**Pull request by Cimbali**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
There's a conflict

**Comment by Cimbali** [comment]
Apparently caused by 25b656c7cfa0bf9ecd52812e4fc18cda9d264b44. I’m not sure why `brew bump-formula-pr` would not have imported that commit though. Maybe I need to manually update my fork before running that?

**Comment by SMillerDev** [comment]
Yeah, `brew  bump-formula-pr` only makes a change from your local install. It does not pull in updates.

**Comment by jonchang** [comment]
Thanks @Cimbali!

**Pull request closed without merging**
