### PR TITLE
volta 1.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Could use `openssl@3`.

**Comment by jasikpark** [comment]
why does this version need openssl@v3 and not the previous version?

**Comment by jasikpark** [comment]
https://github.com/volta-cli/volta/pull/1214 looks like it no longer depends on it? this pr was released in 1.1.0

**Comment by Porkepix** [comment]
> [volta-cli/volta#1214](https://github.com/volta-cli/volta/pull/1214) looks like it no longer depends on it? this pr was released in 1.1.0

Mmmh, you're right so it can even be removed, even better I guess (though from what I read on other PRs Homebrew team prefer an OpenSSL depedency rather than `rustls` one so that when a security fix is issued it doesn't rely on the software developer to publish a new version)).

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
