### PR TITLE
dotnet@6 6.0.406

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Failed to load a, error: dlopen(/private/tmp/dotnetA6-20230221-19249-14yowwr/installer/.dotnet/host/fxr/6.0.13/libhostfxr.dylib, 0x0001): tried: '/private/tmp/dotnetA6-20230221-19249-14yowwr/installer/.dotnet/host/fxr/6.0.13/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/dotnetA6-20230221-19249-14yowwr/installer/.dotnet/host/fxr/6.0.13/libhostfxr.dylib' (no such file), '/private/tmp/dotnetA6-20230221-19249-14yowwr/installer/.dotnet/host/fxr/6.0.13/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
The library libhostfxr.dylib was found, but loading it from /private/tmp/dotnetA6-20230221-19249-14yowwr/installer/.dotnet/host/fxr/6.0.13/libhostfxr.dylib failed
```

**Comment by Bo98** [comment]
source-build still only supports 6.0.1xx still AFAIK: https://github.com/dotnet/source-build/discussions/3246

**Comment by chenrui333** [comment]
> source-build still only supports 6.0.1xx still AFAIK: [dotnet/source-build#3246](https://github.com/dotnet/source-build/discussions/3246)
> 
> > .NET Source-Build is supported on the oldest available .NET SDK feature update for each major release, and on Linux only. For example, if .NET 6.0.1xx, 6.0.2xx, 7.0.1xx, and 7.0.2xx feature updates are available from [dotnet.microsoft.com](https://dotnet.microsoft.com/en-us/download/dotnet/6.0), Source-Build will support 6.0.1xx and 7.0.1xx.
> 
> (though we ignore the Linux part a bit - they only decided to drop macOS _after_ we started using it)
> 
> `brew livecheck dotnet@6` should already be tracking the right version.

if I understand correctly, the latest sdk version is 6.0.4xx, while runtime is 6.0.14 (which is described in the 6.x series release json, https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json). If that is the case, then it should also have an entry in [this folder](https://github.com/dotnet/core/tree/main/release-notes/6.0/6.0.14) as well. I wish they can make it more clear to understand.

**Comment by chenrui333** [comment]
Another side note on this is this is needed for building paket from source

```
Requested SDK version: 6.0.403
global.json file: /private/tmp/paket-20230222-94874-xsxsky/Paket-7.2.0/global.json
```

**Comment by chenrui333** [comment]
no response from upstream, closing the PR for now.

**Comment by chenrui333** [comment]
- also relates to #125669

**Pull request closed without merging**
