### PR TITLE
terraform 0.9.4

### PR DESCRIPTION
**Pull request by JamesBelchamber**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JamesBelchamber** [comment]
hashicorp/terraform#13983 created to track vet failures identified in Jenkins

**Comment by ilovezfs** [comment]
@cblecker here we go again :)

**Comment by JamesBelchamber** [comment]
:) I don't want to recommend we remove the tests (as in #11733) because I'm not confident the failures are benign. Let's see what the Terraform developers say.

**Comment by cblecker** [comment]
@ilovezfs UGHHHHHHHHHH lol
I can't duplicate this locally:
- Checked out https://github.com/hashicorp/terraform/commit/277bbf65d1141207dbb30485bf124b1dba08f80f which is head of [v0.9.4](https://github.com/hashicorp/terraform/releases/tag/v0.9.4).
- go 1.8.1 running on 10.12.4
- Run `make vet`. No vet errors.
- Use Ubuntu Vagrant VM with a clean go1.8.1 install. Still no vet errors.

I'm wondering what the difference is between my local and the Jenkins CI environment.

**Comment by JamesBelchamber** [comment]
I can replicate it here:

- `go version go1.8.1 darwin/amd64`
- 10.12.4

But I'm running it using brew. Try checking out this PR and running `brew upgrade terraform`

**Comment by cblecker** [comment]
Thanks for the lead @JamesBelchamber. Was able to figure out what was up with my repo, and then was able to duplicate. Submitting PR to upstream to fix.

**Comment by cblecker** [comment]
@JamesBelchamber:

**Comment by cblecker** [comment]
@JamesBelchamber:
So what I suggest we do is:
- Create two patch blocks similar to https://github.com/Homebrew/homebrew-core/blob/563007456c1c845602d0de6c0f30b15bde7f420d/Formula/terraform.rb#L19-L24 with the following patches:
  - https://github.com/hashicorp/terraform/commit/fc942c620213858cfae5885431c897204d3a14f3.patch
  - TBD, once https://github.com/hashicorp/terraform/pull/14001 merges we can grab the patch URL.
- Line 43 can also be updated with `5682db0e919ed9cfc6f52ac32e170511a106eb3b` as that is the latest commit in the 1.8 go tools branch: https://go.googlesource.com/tools/+/release-branch.go1.8

**Comment by JamesBelchamber** [comment]
Terraform 0.9.4 only came out today - let's give upstream a chance to consider the issue and take their lead :)

**Comment by cblecker** [comment]
https://github.com/hashicorp/terraform/pull/14001 has merged into upstream. Updated my previous comment with the patch links.

**Comment by JamesBelchamber** [comment]
Okay. Is it a good idea to diverge from upstream? Can we instead skip the vet tests for this version so 0.9.4 brew matches 0.9.4 official binary? We should also be matching their go tools version probably..

**Comment by cblecker** [comment]
Upstream has merged these patches to master. There is no functional change in these patches, other than to fix vet errors. It's safe to patch these in, and what we've done historically. I've also asked upstream try and prioritize fixing there CI so these issues get caught before they're merged in the first place.

**Comment by JamesBelchamber** [comment]
Diverge is the wrong word, I mean moving ahead of upstream. My understanding if that the changes are to functional code rather than tests. But I'm just the guy that ran `brew bump-formula-pr`, if @ilovezfs is satisfied then I'm satisfied :)

**Comment by mengesb** [comment]
So with hashicorp merging 14001; likely this will make it into 0.9.5 but what's that mean for 0.9.4 and brew?

**Comment by JamesBelchamber** [comment]
Based on precedent from #12363, `brew bump-formula-pr` will automatically add them back on the next release. Avoids awkward patchwork.

**Comment by cblecker** [comment]
@JamesBelchamber `brew bump-formula-pr` will not automatically add them back in. The patch statements are the better route here, as I recommended. We've used the patch blocks before successfully https://github.com/Homebrew/homebrew-core/commit/96a7e51052faf1e062f64377a79f34416a5d27ab and https://github.com/Homebrew/homebrew-core/commit/563007456c1c845602d0de6c0f30b15bde7f420d.

**Comment by cblecker** [comment]
It's also worth noting that I've identified the issue with upstream CI that was missing vet errors, and it's been fixed. Hopefully this issue won't keep cropping back up.

**Comment by JamesBelchamber** [comment]
Sorry @cblecker but I don't agree, these are not just changes to the test (from my understanding of the code) but changes to functional parts of the application so that they _pass_ the `go vet` tests. I appreciate that the changes are minor, but as an engineer I want to be sure that the code on my machine (installed using `brew`) matches the code on a colleague's (installed by downloading the official binary) - since they are both affecting the same state file.

My understanding was that #12363 was created by `brew bump-formula-pr` - if not then yes the tests will need to be added back manually. This would also be true of removing the patches. I did follow the upstream work and I'm happy they've solved their testing issue :)

Anyway, this passes, and this approach has precedent too (#11733) so now we know the issue we can merge this safely.

**Comment by cblecker** [comment]
We'll have to agree to disagree then. Disabling those vet/test in the formula doesn't fix the issue, only masks it. You're right that the patches would need to be removed in the next version, but the patches wouldn't work on the next version so the build would fail CI anyways alerting to the fact that the patch blocks needed to be removed. This is not true for removing the vet/test statements -- they would pass the next version without needing to be replaced.

The patch functionality exists for exactly these types of issues, and has been used in many cases to make the software distributed via homebrew more reliable than official upstream versions. The functional difference between the upstream binary and one with these patches applied would be a potential bug is avoided if the Fastly provider is used. The patches are scoped to the specific issue, and have been accepted by upstream into the code.

If you're sure you want to go this route, perhaps only remove vet instead of both vet/test (as the unit tests pass), and put in a comment suggesting it can be added back in the next revision.

**Comment by heythisisnate** [comment]
any chance this can get merged today so we can get unblocked on updating to 0.9.4? 🙇

**Comment by fxcoudert** [comment]
Let's go with @cblecker's suggestion please:

> Create two patch blocks similar to https://github.com/Homebrew/homebrew-core/blob/563007456c1c845602d0de6c0f30b15bde7f420d/Formula/terraform.rb#L19-L24 with the following patches:
>  - https://github.com/hashicorp/terraform/commit/fc942c620213858cfae5885431c897204d3a14f3.patch
>  - https://github.com/hashicorp/terraform/commit/0ffb5aa1d6dbcf298a046a2c2c9b322ad69f024e.patch
>
> Line 43 can also be updated with `5682db0e919ed9cfc6f52ac32e170511a106eb3b` as that is the latest commit in the 1.8 go tools branch: https://go.googlesource.com/tools/+/release-branch.go1.8

**Comment by JamesBelchamber** [comment]
Sorry all, I haven't been keeping up with this. The PR as it stands passes tests and matches upstream 0.9.4, and I'm obviously not going to write and put my name to code I don't agree with. @cblecker is welcome to open his own PR, @ilovezfs or others that can merge are welcome to choose between them.

None of this holds up getting 0.9.4 into Homebrew, a choice simply has to be made by those empowered to make it.

**Pull request closed without merging**
