### PR TITLE
ddgr 1.1 (new formula)

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Submitting this at the request of a friend.

### CODE REVIEW

**Comment by ilovezfs** [comment]
It would be good to avoid virtualenv if possible.

**Comment by zmwangx** [comment]
Hm, are we moving towards a virtualenv-less direction? What’s the replacement?

**Comment by ilovezfs** [comment]
Yes, I'd love to get rid of it entirely or at least to the maximum extent possible.

>What’s the replacement?

The pre-virtualenv way (e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/snakemake.rb)

**Comment by zmwangx** [comment]
Any problem virtualenvs are causing? I pretty much live and breathe in virtualenvs.

**Comment by ilovezfs** [comment]
Yeah. Anyone who wants to use external plugins comes complaining that they don't work and then asks us to add them to the formulae.

https://github.com/mitmproxy/mitmproxy/issues/2238
https://github.com/Homebrew/homebrew-core/pull/20844
https://github.com/Homebrew/homebrew-core/pull/19763
https://github.com/Homebrew/homebrew-core/issues/18227

and other issues
https://github.com/Homebrew/brew/issues/3167

**Comment by ilovezfs** [comment]
Also, they cause what Little Snitch considers code signing violations whenever we use system Python:
https://github.com/Homebrew/homebrew-core/issues/18870
https://github.com/Homebrew/homebrew-core/issues/20193
https://github.com/Homebrew/homebrew-core/issues/19514
https://github.com/pypa/virtualenv/issues/968

**Comment by zmwangx** [comment]
@ilovezfs I understand the struggle here, but the pre-virtualenv way isn't the perfect solution, and it's even more limiting in a way.

With the virtualenv way, sure, user plugins are usually out of the way, but I'm surprised that no one ever asked users to set their own `PYTHONPATH` (say, to `/usr/local/lib/python3.6/site-packages:$PYTHONPATH`) pointing to wherever the plugins are installed, which is respected by virtualenv. It's like setting a `PLUGINS_PATH` env var — not that unreasonable.

In contrast, the pre-virtualenv way (without modifications) hardcodes `PYTHONPATH` due to `env_script_all_files `. The python used is hardcoded as `/usr/local/opt/python3/bin/python3.6`, so the places where the user could install their plugins, without custom .pth configurations, are limited to `/usr/local/lib/python3.6/site-packages` and `~/Library/Python/3.6/lib/python/site-packages` (framework build; `~/.local/lib/python3.6/site-packages` for non-framework build). In general, a monolithic dependency tree like this for the entire system is asking for trouble; it goes against our spirit too.

Basically, the difference between the two approaches is that the virtualenv approach intentionally doesn't tap into the system site (but it can if the user asks it to), where things shouldn't be installed to anyway (but in reality people do install stuff there, sigh). Also, currently the pre-virtualenv approach hardcodes `PYTHONPATH` and makes expansion impossible, but that could be changed.

> Homebrew/brew#3167

The ansible problem is hard to solve, it's an intrinsic problem with their sloppy subprocess invocation (I do understand the invoked scripts may not be in Python, making it hard to use `sys.executable`). Switching from a virtualenv python to `/usr/local/bin/python` may appear to solve the problem, but wait until `/usr/local/bin/python` is not the first Python on your PATH — bam, same problem with the subprocess. It's unfair to attribute this problem to virtualenv.

> Little Snitch 

This is a python3 package so the python is unsigned either way. (On a personal note, code signing bullshit is th e only thing I hate about LS4; it has given me nothing but headaches.)

**Comment by zmwangx** [comment]
Regarding this particular package, by the way, I'm trying to convince my friend to drop the single `requests` dependency, so it may not matter in the end.

**Comment by ilovezfs** [comment]
It doesn't seem unreasonable for people to expect stuff installed via `pip2 install foo` to be accessible to ansible. If they set `PYTHONPATH` to `/usr/local/lib/python2.7/site-packages:$PYTHONPATH` in their environment, doesn't that break all of our virtualenv stuff using python3? (See https://github.com/Homebrew/homebrew-core/issues/20343)

**Comment by zmwangx** [comment]
> If they set PYTHONPATH to /usr/local/lib/python2.7/site-packages:$PYTHONPATH in their environment, doesn't that break all of our virtualenv stuff using python3?

Yes, it should be set on a per-program basis, like `alias ansible='PYTHONPATH=... ansible'`. Of course it's not ideal, so for ansible not using virtualenv is fine. However, as I pointed out above, not using virtualenv doesn't actual solve the whole problem, it's still there.

**Comment by zmwangx** [comment]
By the way I sure as hell ain't advocating putting `/usr/local/lib/python2.7/site-packages` in `PYTHONPATH`; that's horrendous. Ansible plugins should be installed to a prefix exclusive to ansible, mitmproxy plugins should be installed to a prefix exclusive to mitmproxy, etc.

**Comment by ilovezfs** [comment]
>Yes, it should be set on a per-program basis, like alias ansible='PYTHONPATH=... ansible'.

Right, so it becomes a bit of a documentation/UX issue compared to advising `pip2 install`.


>so for ansible not using virtualenv is fine.

And yet ansible was the original justification for virtualenv: https://github.com/Homebrew/brew/pull/344

**Comment by zmwangx** [comment]
From Homebrew/brew#344,

> Another is PYTHONPATH propagates to child processes, which makes it difficult for a script installed with python2 to launch another script written in python3, since the Python 2 packages in PYTHONPATH may be incompatible. This has been a problem for e.g. Ansible.

Wow I didn't think of this, this is retarded. Goes to show ansible should be run in a controlled environment where shebangs of plugins are absolute, or you'll have problems left and right. Maybe in docker.

**Comment by ilovezfs** [comment]
I don't know what the best answer is, but the status quo of no extensions for ansible/certbot/mitmproxy/whatever except the ones we're willing to add and maintain in the formulae has been pretty awful IMO.

**Comment by zmwangx** [comment]
I'm out of ideas. I don't use ansible, don't use certbot on macOS and is well-served by stock ppa:certbot/certbot on Ubuntu (do people actually serve from macOS?), and don't use plugins with mitmproxy, so constructive advice I can give is limited.

Anyway, I find the virtualenv approach much more pleasant than [this](https://github.com/Homebrew/homebrew-core/blob/17a2c4b730ef5cc9023d543dbb6e2a3bbbd59871/Formula/snakemake.rb#L68-L80) for programs that don't require extensibility. Going back seems backwards.

**Comment by ilovezfs** [comment]
I can't get worked up about boilerplate.

**Comment by zmwangx** [comment]
I'll submit this again when neither virtualenv nor boilerplate is needed.

**Pull request closed without merging**
