### PR TITLE
a*: move to a/ subdirectory.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Continuing the sharding work now that `ack.rb` was moved without issue.

### CODE REVIEW

**Comment by carlocab** [comment]
Aliases need updating. The [code for tracking style exceptions](https://github.com/Homebrew/brew/blob/a8022e6040d03b9d19fa1066cf9759f33bba0775/Library/Homebrew/rubocops/extend/formula_cop.rb#L173) also needs to be modified to take sharding into account. It seems to me that a lot of this would be simplified if we had code for finding the repository root given a file.

**Comment by MikeMcQuaid** [comment]
> Aliases need updating. The [code for tracking style exceptions](https://github.com/Homebrew/brew/blob/a8022e6040d03b9d19fa1066cf9759f33bba0775/Library/Homebrew/rubocops/extend/formula_cop.rb#L173) also needs to be modified to take sharding into account.

Will do these, thanks 👍🏻.



> It seems to me that a lot of this would be simplified if we had code for finding the repository root given a file.

Can you elaborate a bit on that? I think we might do.

**Comment by carlocab** [comment]
> Can you elaborate a bit on that? I think we might do.

This is just following-up from my observation at https://github.com/Homebrew/brew/pull/15740#discussion_r1280060925. It seems like there are a few places where we have a path but we want to know the tap repository it came from.

Actually, I think we kind of already have one: `Tap.from_path(pn).path`, so something like this should work:
```diff
diff --git a/Library/Homebrew/rubocops/extend/formula_cop.rb b/Library/Homebrew/rubocops/extend/formula_cop.rb
index 2ad09eaa4..59cdc38b8 100644
--- a/Library/Homebrew/rubocops/extend/formula_cop.rb
+++ b/Library/Homebrew/rubocops/extend/formula_cop.rb
@@ -159,19 +159,19 @@ module RuboCop
 
       # Returns the formula tap.
       def formula_tap
-        return unless (match_obj = @file_path.match(%r{/(homebrew-\w+)/}))
+        return unless (file_tap = Tap.from_path(@file_path))
 
-        match_obj[1]
+        file_tap
       end
 
       # Returns whether the given formula exists in the given style exception list.
       # Defaults to the current formula being checked.
       def tap_style_exception?(list, formula = nil)
-        if @tap_style_exceptions.nil? && !formula_tap.nil?
+        if @tap_style_exceptions.nil? && formula_tap.present?
           @tap_style_exceptions = {}
 
-          style_exceptions_dir = "#{File.dirname(File.dirname(@file_path))}/style_exceptions/*.json"
-          Pathname.glob(style_exceptions_dir).each do |exception_file|
+          style_exceptions_dir = "style_exceptions/*.json"
+          formula_tap.path.glob(style_exceptions_dir).each do |exception_file|
             list_name = exception_file.basename.to_s.chomp(".json").to_sym
             list_contents = begin
               JSON.parse exception_file.read
```
The other callers of `formula_tap` will need fixing though.

**Comment by MikeMcQuaid** [comment]
> ```diff
> +        return unless (file_tap = Tap.from_path(@file_path))
> ```

Almost certainly can't use `Tap` class in `rubocop` as it `require`s too much stuff which needs Homebrew's various environment variables set.

> It might also be useful for maintenance to make sure that sharding logic is encoded only inside a `Tap` object instead of in a bunch of different places.

Generally agree but: see above 😁

**Review by fxcoudert — APPROVED** [review]

**Review by issyl0 — APPROVED** [review]
🅰️

**Pull request merged**
