### PR TITLE
pcap_dnsproxy: fix plist issues

### PR DESCRIPTION
**Pull request by blackgear**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

1. case sensitivity fixed in the plist, via this [issue](https://github.com/chengr28/Pcap_DNSProxy/issues/190).
2. network error 24 fixed by increasing max open files, via this [issue](https://github.com/chengr28/Pcap_DNSProxy/pull/185).

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Let's install the `Source/ExampleConfig/pcap_dnsproxy.service.plist` file instead of duplicating it ourselves in our `plist` method.

**Comment by blackgear** [comment]
@MikeMcQuaid 
I read the Formula-Cookbook and found *Nothing* like:
```ruby
plist.install "Source/ExampleConfig/pcap_dnsproxy.service.plist"
```
Should I use this one?
```ruby
def plist
    File.open("Source/ExampleConfig/pcap_dnsproxy.service.plist", 'rb') { |f| f.read }
end
```

**Comment by MikeMcQuaid** [comment]
`prefix.install "Source/ExampleConfig/pcap_dnsproxy.service.plist"` is what you want

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
