### PR TITLE
cointop 1.2.2

### PR DESCRIPTION
**Pull request by miguelmota**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
Could you squash your commits in one please?

**Comment by miguelmota** [comment]
@Moisan commits squashed

**Comment by SMillerDev** [comment]
There's a merge conflict when trying to check out the branch. Can you rebase the one commit on master please

**Comment by miguelmota** [comment]
@SMillerDev hope it's good now

**Comment by SMillerDev** [comment]
Looks like it, thanks a ton @miguelmota. Without people like you it would be impossible to maintain homebrew to the standards people have come to expect from us.

**Pull request closed without merging**
