### PR TITLE
cgit 1.2.3

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

previous failed attempt (1.2.2, #51244)

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>build failure log</summary>

```
 [34m==>[0m [1mmake prefix=/usr/local/Cellar/cgit/1.2.3 CGIT_SCRIPT_PATH=/usr/local/Cellar/cgit/1.2.3/share/cgit CGIT_DATA_PATH=/usr/local/var/www/htdocs/cgit CGIT_CONFIG=/usr/local/etc/cgitrc CACHE_ROOT=/usr/local/var/cache/cgit install[0m
     SUBDIR git
 GIT_VERSION = 2.25.1
 CGIT_VERSION = v1.2.3
     * new build flags
     * new CGit build flags
     CC common-main.o
     CC abspath.o
     CC add-interactive.o
     CC add-patch.o
     CC advice.o
     * new link flags
     CC alias.o
     CC alloc.o
     CC apply.o
     CC archive.o
     CC archive-tar.o
     CC archive-zip.o
     CC argv-array.o
     * new prefix flags
     CC base85.o
     CC bisect.o
     CC blame.o
     CC blob.o
     CC branch.o
     CC bulk-checkin.o
     CC bundle.o
     CC cache-tree.o
     CC chdir-notify.o
     CC checkout.o
     CC color.o
     CC column.o
     CC combine-diff.o
     CC commit.o
     CC commit-graph.o
     CC commit-reach.o
     CC compat/obstack.o
     CC compat/terminal.o
     CC config.o
     CC connect.o
     CC connected.o
     CC convert.o
     CC copy.o
     CC credential.o
     CC csum-file.o
     CC ctype.o
     CC date.o
     CC decorate.o
     CC delta-islands.o
     CC diffcore-break.o
     CC diffcore-delta.o
     CC diffcore-order.o
     CC diffcore-pickaxe.o
     CC diffcore-rename.o
     CC diff-delta.o
     CC diff-lib.o
     CC diff-no-index.o
     CC diff.o
     CC dir.o
     CC dir-iterator.o
     CC editor.o
     CC entry.o
     CC environment.o
     CC ewah/bitmap.o
     CC ewah/ewah_bitmap.o
     CC ewah/ewah_io.o
     CC ewah/ewah_rlw.o
     CC exec-cmd.o
     CC fetch-negotiator.o
     CC fetch-pack.o
     CC fsck.o
     CC fsmonitor.o
     CC gettext.o
     CC gpg-interface.o
     CC graph.o
     CC grep.o
     CC hashmap.o
     CC linear-assignment.o
     GEN command-list.h
     CC hex.o
     CC ident.o
     CC interdiff.o
     CC json-writer.o
     CC kwset.o
     CC levenshtein.o
     CC line-log.o
     CC line-range.o
     CC list-objects.o
     CC list-objects-filter.o
     CC list-objects-filter-options.o
     CC ll-merge.o
     CC lockfile.o
     CC log-tree.o
     CC ls-refs.o
     CC mailinfo.o
     CC mailmap.o
     CC match-trees.o
     CC mem-pool.o
     CC merge.o
     CC merge-blobs.o
     CC merge-recursive.o
     CC mergesort.o
     CC midx.o
     CC name-hash.o
     CC negotiator/default.o
     CC negotiator/skipping.o
     CC notes.o
     CC notes-cache.o
     CC notes-merge.o
     CC notes-utils.o
     CC object.o
     CC oidmap.o
     CC oidset.o
     CC packfile.o
     CC pack-bitmap.o
     CC pack-bitmap-write.o
     CC pack-check.o
     CC pack-objects.o
     CC pack-revindex.o
     CC pack-write.o
     CC pager.o
     CC parse-options.o
     CC parse-options-cb.o
     CC patch-delta.o
     CC patch-ids.o
     CC path.o
     CC pathspec.o
     CC pkt-line.o
     CC preload-index.o
     CC pretty.o
     CC prio-queue.o
     CC progress.o
     CC promisor-remote.o
     CC prompt.o
     CC protocol.o
     CC quote.o
     CC range-diff.o
     CC reachable.o
     CC read-cache.o
     CC rebase-interactive.o
     CC reflog-walk.o
     CC refs.o
     CC refs/files-backend.o
     CC refs/iterator.o
     CC refs/packed-backend.o
     CC refs/ref-cache.o
     CC refspec.o
     CC ref-filter.o
     CC remote.o
     CC replace-object.o
     CC repo-settings.o
     CC repository.o
     CC rerere.o
     CC resolve-undo.o
     CC revision.o
     CC run-command.o
     CC send-pack.o
     CC sequencer.o
     CC serve.o
     CC server-info.o
     CC setup.o
     CC sha1-array.o
     CC sha1-lookup.o
     CC sha1-file.o
     CC sha1-name.o
     CC shallow.o
     CC sideband.o
     CC sigchain.o
     CC split-index.o
     CC stable-qsort.o
     CC strbuf.o
     CC streaming.o
     CC string-list.o
     CC submodule.o
     CC submodule-config.o
     CC sub-process.o
     CC symlinks.o
     CC tag.o
     CC tempfile.o
     CC thread-utils.o
     CC tmp-objdir.o
     CC trace.o
     CC trace2.o
     CC trace2/tr2_cfg.o
     CC trace2/tr2_cmd_name.o
     CC trace2/tr2_dst.o
     CC trace2/tr2_sid.o
     CC trace2/tr2_sysenv.o
     CC trace2/tr2_tbuf.o
     CC trace2/tr2_tgt_event.o
     CC trace2/tr2_tgt_normal.o
     CC trace2/tr2_tgt_perf.o
     CC trace2/tr2_tls.o
     CC trailer.o
     CC transport.o
     CC transport-helper.o
     CC tree-diff.o
     CC tree.o
     CC tree-walk.o
     CC unpack-trees.o
     CC upload-pack.o
     CC url.o
     CC urlmatch.o
     CC usage.o
     CC userdiff.o
     CC utf8.o
     CC varint.o
     CC versioncmp.o
     CC walker.o
     CC wildmatch.o
     CC worktree.o
     CC wrapper.o
     CC write-or-die.o
     CC ws.o
     CC wt-status.o
     CC xdiff-interface.o
     CC zlib.o
     CC unix-socket.o
     CC sha256/block/sha256.o
     CC compat/sha1-chunked.o
     CC compat/precompose_utf8.o
     CC compat/fopen.o
     CC compat/memmem.o
     CC compat/qsort_s.o
     CC compat/regex/regex.o
     CC xdiff/xdiffi.o
     CC xdiff/xprepare.o
     CC xdiff/xutils.o
     CC xdiff/xemit.o
     CC xdiff/xmerge.o
     CC xdiff/xpatience.o
     CC xdiff/xhistogram.o
     CC ../cgit.o
     CC ../cache.o
     CC ../cmd.o
     CC ../configfile.o
     CC ../filter.o
     CC ../html.o
     CC ../parsing.o
     CC ../scan-tree.o
     CC ../shared.o
     CC ../ui-atom.o
     CC ../ui-blame.o
     CC ../ui-blob.o
     CC ../ui-clone.o
     CC ../ui-commit.o
     CC ../ui-diff.o
     CC ../ui-log.o
     CC ../ui-patch.o
     CC ../ui-plain.o
     CC ../ui-refs.o
     CC ../ui-repolist.o
     CC ../ui-shared.o
     CC ../ui-snapshot.o
     CC ../ui-ssdiff.o
     CC ../ui-stats.o
     CC ../ui-summary.o
     CC ../ui-tag.o
     CC ../ui-tree.o
     CC attr.o
     CC help.o
     CC version.o
     AR xdiff/lib.a
     AR libgit.a
     * linking without autodetected Lua support
     LINK ../cgit
 Undefined symbols for architecture x86_64:
   "_memrchr", referenced from:
       _cgit_set_title_from_path in ui-shared.o
 ld: symbol(s) not found for architecture x86_64
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
 make[1]: *** [../cgit] Error 1
 make: *** [cgit] Error 2
```

</details>

**Comment by alebcay** [comment]
`memchr` is non-POSIX and macOS C library does not implement it. A patch like https://github.com/slact/nchan/commit/e023c63147aac7ef17dccfa02c17fde9970a2c43 would be needed upstream.

**Comment by chenrui333** [comment]
> `memchr` is non-POSIX and macOS C library does not implement it. A patch like [slact/nchan@e023c63](https://github.com/slact/nchan/commit/e023c63147aac7ef17dccfa02c17fde9970a2c43) would be needed upstream.

Got you, I will try to submit something to our patch repo on fixing this.

**Comment by alebcay** [comment]
Realized I typoed in my comment - to be clear, `cgit` needs `memrchr` (I originally wrote `memchr` by accident, which is something else).

**Comment by chenrui333** [comment]
> Realized I typoed in my comment - to be clear, `cgit` needs `memrchr` (I originally wrote `memchr` by accident, which is something else).

yeah, I saw Bo's comment, so I (somehow) did not mistaken with the typo. but thanks for calling it out. :)

**Comment by chenrui333** [comment]
Close the PR for now.

**Pull request closed without merging**
