### PR TITLE
gearboy: migrate to cask

### PR DESCRIPTION
**Pull request by drhelius**
This  App is being moved to a cask: https://github.com/Homebrew/homebrew-cask/pull/80261

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
If it's going to be added as a cask, then you need to add an entry to `tap_migrations.json`

**Comment by drhelius** [comment]
Added "gearboy" to `tap_migrations.json`

**Comment by vitorgalvao** [comment]
Cask is now merged.

**Comment by SMillerDev** [comment]
Why is it being moved? Does it no longer compile? Is it not open source software anymore?

**Comment by drhelius** [comment]
It is now being distributed as an App bundle. 

Gearboy is a GUI application after all.

If you feel this is a wrong move just let me know.

**Comment by SMillerDev** [comment]
If all functions work, the tool is open source and it still compiles I see no reason to change the strategy.

**Comment by drhelius** [comment]
But it's not a tool, is a GUI application and should be placed in the `Applications` directory.

Shouldn't be GUI applications installed with `brew cask`?

**Comment by bayandin** [comment]
I would agree with moving `gearboy` this to a cask, since we have a note regarding building .app: https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app

**Comment by SMillerDev** [comment]
If it's just a `.app` file that should live in `Applications` moving to a cask is fine

**Comment by bayandin** [comment]
Thanks @drhelius 🎉

**Pull request merged**
