### PR TITLE
bluepill 4.1.1

### PR DESCRIPTION
**Pull request by reececomo**

### CODE REVIEW

**Comment by ob** [comment]
Can you give me a sec before merging this? I just realized there is a minor fix with versioning that I need to put in (I suspect if you run `bluepill version` it'll still say 3.1.1 even though this is 4.1.0.

**Comment by ob** [comment]
Ok, https://github.com/linkedin/bluepill/tree/v4.1.1 is the new release. Thanks!

**Comment by reececomo** [comment]
@ob Bumped to 4.1.1 👍

**Comment by lembacon** [comment]
Thanks @reececomo!

**Pull request closed without merging**
