### PR TITLE
lsd 0.12.0

### PR DESCRIPTION
**Pull request by sal0max**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
The test is failing, I think the README is no longer installed? Could you check if you could change the test?

**Comment by sal0max** [comment]
Thanks for the note!

Problem isn't a missing `README.md` (still present), but the `shell_output("#{bin}/lsd #{prefix}")` returns `101` instead `0`.
That's strange, because if I check it manually, everything seems fine:
```bash
mac:~ maks$ /usr/local/Cellar/lsd/0.12.0/bin/lsd /usr/local/Cellar/lsd/0.12.0
bin  CHANGELOG.md  INSTALL_RECEIPT.json  LICENSE  README.md
mac:~ maks$ echo $?
0
```
Any idea?

**Comment by SMillerDev** [comment]
What about running `brew test lsd`?

**Comment by sal0max** [comment]
_Heads-up_: Problem seems to be that lsd crashes when trying to determine the window size. Here's the error message when running `brew test lsd`:
```
thread 'main' panicked at 'failed to retrieve terminal size', src/display.rs:29:17
```
Hence the 101 return code.

I'm no expert in homebrew nor Rust (lsd), so is this an issue within `shell_output` or lsd itself?

**Comment by sjackman** [comment]
I have seen the window size returning nothing cause a `brew test` failure in at least one other package (digging back in my memory here). In that case I was able to work around it by setting the environment variable `COLUMNS=80`. That may work here. It'd be awesome to address the root cause.

**Comment by sal0max** [comment]
Thanks for the help! Sadly setting the environment variable didn't work.

However a different solution is to not just use `lsd` but `lsd -l` in the test.
With this _oneline_ flag (_Display one entry per line_) set, the piece of code causing the trouble doesn't get called.

**Review by MikeMcQuaid — APPROVED** [review]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @sal0max!

**Pull request closed without merging**
