### PR TITLE
pocl and its dependents: Update to opencl-icd-loader from ocl-icd

### PR DESCRIPTION
**Pull request by Ishaanahuja7**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

1. opencl-icd-loader is more actively maintained than ocl-icd at the moment. Looks like people use opencl-icd-loader more because it has more number of stars (193 vs 58)
2. All tests seem to pass

### CODE REVIEW

**Comment by Ishaanahuja7** [comment]
Anybody to review and approve this?

**Comment by Ishaanahuja7** [comment]
@chenrui333 @carlocab @cho-m Can anyone review this?

**Comment by SMillerDev** [comment]
Please squash all commits into one commit per formula, something like `viennacl: use opencl-ics-loader`

**Comment by Ishaanahuja7** [comment]
@SMillerDev Done. All checks are passing.

**Comment by Ishaanahuja7** [comment]
@SMillerDev Please review soon! Thanks!

**Comment by Ishaanahuja7** [comment]
Can anybody review and approve?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
