### PR TITLE
doxygen 1.9.8

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
On Big Sur:

```
==> brew link libssh2
==> FAILED
Full link libssh2 output
  Error: No such keg: /usr/local/Cellar/libssh2
==> brew link rtmpdump
==> FAILED
Full link rtmpdump output
  Error: No such keg: /usr/local/Cellar/rtmpdump
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
let's ship and followup on the big_sur builds.

**Comment by chenrui333** [comment]
```
brew link libssh2
brew link rtmpdump
```

**Comment by chenrui333** [comment]
passed my regression checks:
- https://github.com/chenrui333/github-action-test/actions/runs/6000749972/job/16273492818 (libssh2)
- https://github.com/chenrui333/github-action-test/actions/runs/6000749020/job/16273489811 (rtmpdump)

**Pull request merged**
