### PR TITLE
evince 40.1

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> brew audit --tap=homebrew/core
==> FAILED
evince:
  * 40.1 is a development release
Error: 40.1 is a development release
Error: 1 problem in 1 formula detected
```

**Comment by tschoonj** [comment]
This is a false positive, triggered by the new GNOME versioning scheme. I will try and change the audit.

**Comment by tschoonj** [comment]
@carlocab I lack the necessary Ruby skills to modify the audit warning.. would you mind helping out here? Based on [their new versioning scheme](https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235), I think it should be sufficient to allow any version that consists of two numbers (major and minor).

Probably a one-liner in [brew](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_auditor.rb#L548-L552), but no idea what it should be... 😢

**Comment by carlocab** [comment]
If I understand the new version scheme and what it applies to correctly, shouldn't we be able to remove the GNOME audit? My understanding is that anything that doesn't end in `alpha`, `beta`, or `rc` is a stable release. However, catching those (`alpha`, `beta`, `rc`) versions is already done [here](https://github.com/Homebrew/brew/blob/ab99855c12c02eebd185ca1402c33cccf62374f6/Library/Homebrew/formula_auditor.rb#L541-L545).

**Comment by tschoonj** [comment]
You understand the scheme correctly, but it will unfortunately not get applied to all GNOME projects. Gtk, GLib, pango etc will continue to use the old versioning scheme AFAIK.

**Comment by carlocab** [comment]
I was afraid of that. Are there more projects adopting the new scheme, or will the majority stay with the old one? Depending on which, the right thing to do here might be to maintain an allowlist, just like in the audit just above the one for GNOME.

Ping @Rylan12 who will know a lot more about this than I do.

**Comment by Rylan12** [comment]
There's a `gnome_devel_allowlist` allowlist but it won't work right out of the bat because it would need a specific version to be specified. I'll open a brew PR to add the ability to use `all` in these lists.

Agreed, though, if this new version scheme is going to be the standard we should change the audit.

**Review by Rylan12 — APPROVED** [review]

**Comment by tschoonj** [comment]
Many thanks @Rylan12 for writing the audit exception!!

**Pull request closed without merging**
