### PR TITLE
webtorrent-cli: style tweaks

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

🙃 🔫 😭

### CODE REVIEW

**Comment by ilovezfs** [comment]
Domitus flare up?

**Comment by DomT4** [comment]
Current status: Nervous twitching in the left eye, rapidly progressing across to the other eye.

**Comment by ilovezfs** [comment]
I wonder if Domitus should be spelled Domitis.

**Comment by DomT4** [comment]
I'm going to leave that one down to you, for the sake of my tentative grip on sanity.

**Comment by ilovezfs** [comment]
:pill:

**Comment by DomT4** [comment]
Thanks! 😸

**Pull request merged**
