### PR TITLE
update fltk devel

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by pthariensflame** [comment]
I'm pretty sure the failure here is spurious, since it's only checking the stable version and the only thing I changed was the devel version.

**Comment by DomT4** [comment]
Urgh. @ilovezfs Is this likely to be one of those joyous `SDKROOT` issues again?

**Comment by ilovezfs** [comment]
@DomT4 Yup, but upstream has actually already fixed the problem. (Note that the issue does not affect the devel spec). Here's the upstream patch:

https://gist.githubusercontent.com/ilovezfs/7f91b78dc431f55d31ff3e3dbd91c7bf/raw/36e92ac56eb273a6fab879a1025313725d0f6bae/fltk%2520sdk%2520patch

**Comment by DomT4** [comment]
@ilovezfs Does that apply cleanly against stable or will it need some reworking?

**Comment by ilovezfs** [comment]
I tested it against stable before opening my mouth ;)

**Comment by ilovezfs** [comment]
I'll see if I can find the corresponding svn (yuck) commit

**Comment by ilovezfs** [comment]
@DomT4 
```
Josephs-MacBook-Pro:fltk-1.3 joe$ svn log -r 10794
------------------------------------------------------------------------
r10794 | manolo | 2015-07-17 09:16:09 -0700 (Fri, 17 Jul 2015) | 5 lines

Fix compilation errors with Mac OS 10.11 that no longer accepts
  enum CGLineCap
but wants
  CGLineCap
as type name.
------------------------------------------------------------------------
Josephs-MacBook-Pro:fltk-1.3 joe$ svn diff -r 10793:10794
Index: src/fl_line_style.cxx
===================================================================
--- src/fl_line_style.cxx	(revision 10793)
+++ src/fl_line_style.cxx	(revision 10794)
@@ -35,8 +35,8 @@
 
 #ifdef __APPLE_QUARTZ__
 float fl_quartz_line_width_ = 1.0f;
-static enum CGLineCap fl_quartz_line_cap_ = kCGLineCapButt;
-static enum CGLineJoin fl_quartz_line_join_ = kCGLineJoinMiter;
+static /*enum*/ CGLineCap fl_quartz_line_cap_ = kCGLineCapButt;
+static /*enum*/ CGLineJoin fl_quartz_line_join_ = kCGLineJoinMiter;
 static CGFloat *fl_quartz_line_pattern = 0;
 static int fl_quartz_line_pattern_size = 0;
 void fl_quartz_restore_line_style_() {
@@ -110,9 +110,9 @@
   DeleteObject(fl_current_xmap->pen);
   fl_current_xmap->pen = newpen;
 #elif defined(__APPLE_QUARTZ__)
-  static enum CGLineCap Cap[4] = { kCGLineCapButt, kCGLineCapButt, 
+  static /*enum*/ CGLineCap Cap[4] = { kCGLineCapButt, kCGLineCapButt,
                                    kCGLineCapRound, kCGLineCapSquare };
-  static enum CGLineJoin Join[4] = { kCGLineJoinMiter, kCGLineJoinMiter, 
+  static /*enum*/ CGLineJoin Join[4] = { kCGLineJoinMiter, kCGLineJoinMiter, 
                                     kCGLineJoinRound, kCGLineJoinBevel };
   if (width<1) width = 1;
   fl_quartz_line_width_ = (float)width; 
```

**Comment by DomT4** [comment]
@ilovezfs Thanks! Any chance I can sweet-talk you into pushing that to `formula-patches`? 😉

**Comment by ilovezfs** [comment]
Sure, but I'll insist on a :star2: as my reward.

**Comment by ilovezfs** [comment]
@DomT4 interestingly this seems to be all that's needed to remove the <= Yosemite restriction.

**Comment by DomT4** [comment]
Nice! If we can remove the "El Cap isn't welcome here" logic in `stable` that'd certainly be a big upside. We were hoping devel would become stable by now, but we've been carrying that assumption for a fair while.

**Comment by ilovezfs** [comment]
Ideally, we'd probably apply some of the other 10.11 integration fixes that are in the tree, but this is sufficient to get it to compile and pass the test-do block at least.

**Comment by ilovezfs** [comment]
@DomT4 https://github.com/Homebrew/formula-patches/pull/25
(https://github.com/ilovezfs/fltk/commit/7767f015258942f1ea8ebec322ee7e218903a6b8)

https://github.com/ilovezfs/fltk if you feel like perusing other 10.11 commits, such as
https://github.com/ilovezfs/fltk/commit/02425496cf3725a1f5a487703489a96b7628dcf6
https://github.com/ilovezfs/fltk/commit/67bef1a6958e729b11e4899843532abf4c1835c0
etc.

**Comment by ilovezfs** [comment]
@DomT4 https://github.com/Homebrew/homebrew-core/pull/1600

**Comment by ilovezfs** [comment]
@pthariensflame if you rebase your PR on master, it should now pass CI.

**Comment by pthariensflame** [comment]
@ilovezfs Done!  Let's see if this builds.  :)

**Comment by pthariensflame** [comment]
Yay!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/6c12bac2501c0a3179fc99ced102fae7ba2a1f7d. Thank you for your contribution to Homebrew @pthariensflame; we appreciate it! :smiley_cat:

**Pull request closed without merging**
