### PR TITLE
mesa 24.2.1

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
I'm sorry that refactoring of drivers for different Linux arches isn't included, it tooks too much time, which I currently dont't have.

### CODE REVIEW

**Comment by yurikoles** [comment]
An audit gives me locally on macOS:

```
Taps/homebrew/homebrew-core/Formula/m/mesa.rb:95:3: C: FormulaAudit/ResourceRequiresDependencies: Add depends_on lines above for "libyaml".
  resource "pyyaml" do
  ^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m/mesa.rb: * line 95, col 3: Add `depends_on` lines above for `"libyaml"`.
Error: 1 problem in 1 formula detected.
```

**Comment by yurikoles** [comment]
A `CI / tap_syntax` gives the very same error.

**Comment by yurikoles** [comment]
The formula doesn't refer to `libyaml`, but has `pyyaml` resource because the corresponding formula is disabled.

**Comment by yurikoles** [comment]
Oh, I got it, `pyyaml` formula `depends_on "libyaml"`, which is a C library. I hope to push a fix soon.

**Comment by yurikoles** [comment]
According to Arch Linux [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/mesa/-/blob/a2a363a6c160f5b0e206afc3513633209ffc8531/PKGBUILD#L71), `libyaml` is a build dependency.

**Comment by yurikoles** [comment]
So, as usual, on Linux, we have some failed linkage and unrelated `quazip` test fail, which can't find `<zlib.h>`.

```
Warning: 18 failed steps ignored!
brew linkage --cached --test --strict claws-mail
brew linkage --cached --test --strict eiffelstudio
brew linkage --cached --test --strict erlang
brew linkage --cached --test --strict erlang@25
brew linkage --cached --test --strict fltk
brew linkage --cached --test --strict geomview
brew linkage --cached --test --strict gl2ps
brew linkage --cached --test --strict gsmartcontrol
brew linkage --cached --test --strict librealsense
brew linkage --cached --test --strict mame
brew linkage --cached --test --strict nestopia-ue
brew linkage --cached --test --strict partio
brew linkage --cached --test --strict pioneers
brew linkage --cached --test --strict qt
brew linkage --cached --test --strict qt@5
brew linkage --cached --test --strict quazip
brew linkage --cached --test --strict suil
brew linkage --cached --test --strict wxwidgets
Error: 1 failed step!
brew test --retry --verbose quazip
```

**Comment by yurikoles** [comment]
I sent a fix for `quazip` test in #183162.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@yurikoles thanks!! <3

**Pull request merged**
