### PR TITLE
kibana 5.4.2

### PR DESCRIPTION
**Pull request by jasontedor**
This pull request updates the Kibana version from version 5.4.1 to version 5.4.2.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@jasontedor looks like no one has pushed the publish button for 5.4.2 https://github.com/elastic/kibana/releases

**Comment by jasontedor** [comment]
@ilovezfs Why does that matter since this formula builds from source?

**Comment by ilovezfs** [comment]
@jasontedor as a general rule we want to build from whatever is marked as latest release based on https://github.com/elastic/kibana/releases/latest. Since you _are_ upstream, I'm not particularly fussed about it in this case, but if nothing else, it does help me with keeping the livecheck stuff sane if latest tag (most current tag in the repository) and latest release (latest release according to the GitHub API) do not diverge.

**Comment by ilovezfs** [comment]
Here's what I mean:
```
bash-4.4$ brew livecheck kibana
kibana (guessed) : 5.4.1 ==> 6.0.0-alpha2
bash-4.4$ latest kibana
5.4.1
```
So 5.4.2 is effectively invisible to me.

**Comment by ilovezfs** [comment]
Contrast with `filebeat`:
```
bash-4.4$ brew livecheck filebeat
filebeat (guessed) : 5.4.1 ==> 6.0.0-alpha2
bash-4.4$ latest filebeat
5.4.2
```

**Comment by jasontedor** [comment]
@ilovezfs We build from the [tag here](https://github.com/elastic/kibana/tree/v5.4.2), and that tag was used for the official distributions that were released earlier this afternoon. The release will show up as https://github.com/elastic/kibana/releases/latest eventually (note that it appears under releases, it is just not yet marked as latest).

**Comment by ilovezfs** [comment]
@jasontedor yup. As long as someone eventually hits the publish button on GitHub for 5.4.2 we're all good :)

**Comment by ilovezfs** [comment]
@jasontedor thanks for the three upgrades! :tada:

**Comment by jasontedor** [comment]
Thanks git the three integrations. Much appreciated.

**Comment by ilovezfs** [comment]
@jasontedor you're welcome!

**Pull request closed without merging**
