### PR TITLE
gnutls 3.7.3

### PR DESCRIPTION
**Pull request by domrim**
Created with `brew bump-formula-pr`.

follow up for #92186

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
This is on the "Next" branch, but this is also the branch used by Debian stable, so LGTM.

I'm fairly certain the failures have shown up in other PRs (e.g. `samba` typically goes away on a re-run), so this should be good to merge.

**Review by iMichka — CHANGES_REQUESTED** [review]
https://www.gnutls.org/download.html#fn2
> 2. Next will be the next stable release; while it is believed to be sufficiently stable it is not as well tested as the stable branch.

I think we should wait for 3.7.x to become a stable branch, especially as `gnutls` is quite important.

**Comment by domrim** [comment]
> https://www.gnutls.org/download.html#fn2
> 
> > 2. Next will be the next stable release; while it is believed to be sufficiently stable it is not as well tested as the stable branch.
> 
> I think we should wait for 3.7.x to become a stable branch, especially as `gnutls` is quite important.

i still believe that something, thats stable enough for debian should be stable enough for us, but if you think so, you can close this MR, and i will include the formula in my personal Tap.

**Comment by carlocab** [comment]
> https://www.gnutls.org/download.html#fn2
> 
> > 2. Next will be the next stable release; while it is believed to be sufficiently stable it is not as well tested as the stable branch.
> 
> 
> 
> I think we should wait for 3.7.x to become a stable branch, especially as `gnutls` is quite important.

This is the version shipped by Arch and Debian Stable. It also fixes two (minor) CVEs

**Review by iMichka — APPROVED** [review]
LGTM then. The footnote on the `gnutls` website looked concerning. On the other hand if other stable distros ship it and it brings in fixes for CVEs, then let's ship it too.

**Comment by iMichka** [comment]
Thanks @domrim !

**Pull request closed without merging**
