### PR TITLE
llvm: remove libcxxabi option.

### LINKED ISSUE #4081: Doxygen v1.8.11 Installs Successfully on OS X v10.11.6 'El Capitan,' but Crashes When Run (Using Non-Standard Options)
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whom) $(brew --prefix)`?~~  N/A

### Bug reports:

The options I used were `--with-graphviz`, `--with-llvm`, and `--with-qt5`.  [Here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Doxygen) are my build logs.  The build and installation phases both succeed, but later invocations of Doxygen via the command line fail; some example output follows:  

```
Bryces-HD-1-TB:~ zadmin$ doxygen -v
dyld: Library not loaded: @rpath/libc++abi.1.dylib
  Referenced from: /usr/local/opt/llvm/lib/libc++.1.dylib
  Reason: image not found
Trace/BPT trap: 5
```

Note that running these commands…:  

```
brew uninstall -vd --doxygen
brew install -vd --build-from-source doxygen --with-graphviz --with-qt5
```

…(that is, manually reinstalling Doxygen from a build of it from source completed successfully _without_ the `--with-llvm` option, bypassing any option caching Homebrew appeared it might do in `brew reinstall` even when supplied new options) resolved the issue.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

It's pretty broken (as noted in their own README and our comment) and causes failures with other formulae.

Fixes #4081.

### CODE REVIEW

**Comment by DomT4** [comment]
Not sure what's going on with `libunwind` here.

It's apparently default on, but the only conditionals it is referenced by are tied to `libcxxabi`. Given that possibly should be removing the `libunwind` resources as well, given they're orphaned now.

**Comment by ilovezfs** [comment]
```
==> brew install ./llvm-3.8.1.el_capitan.bottle.1.tar.gz
==> brew test llvm --verbose
==> FAILED
Testing llvm
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160823-4706-fka779.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb --verbose
==> /usr/local/Cellar/llvm/3.8.1/bin/llvm-config --prefix
==> /usr/local/Cellar/llvm/3.8.1/bin/clang -L/usr/local/Cellar/llvm/3.8.1/lib -fopenmp -nobuiltininc -I/usr/local/Cellar/llvm/3.8.1/lib/clang/3.8.1/include omptest.c -o omptest
==> ./omptest
Error: llvm: failed
Calling MacOS.clang_version is deprecated!
Use DevelopmentTools.clang_version instead.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:342:in `block in <class:Llvm>'
Please report this to the homebrew/core tap!
/usr/local/Library/Homebrew/utils.rb:156:in `odeprecated'
/usr/local/Library/Homebrew/compat/macos.rb:126:in `clang_version'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:342:in `block in <class:Llvm>'
/usr/local/Library/Homebrew/formula.rb:1422:in `block (2 levels) in run_test'
/usr/local/Library/Homebrew/formula.rb:762:in `with_logging'
/usr/local/Library/Homebrew/formula.rb:1421:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1415:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```
lol

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/commit/da291e8b3a25f9355d6d9ecfa2b1c44c0aa52300

**Comment by ilovezfs** [comment]
@DomT4 thanks. Going to pull this as-is then, or wait for @MikeMcQuaid to rebase it and send it through CI again?

**Comment by DomT4** [comment]
I'd like a bit more clarity on the `libunwind` situation.

**Comment by MikeMcQuaid** [comment]
Fixed `libunwind` case. Pushing!

**Pull request merged**
