### PR TITLE
libgccjit: add RPATH reference on Intel macOS

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Fixes Homebrew/discussions#5364.

Also, update the test to avoid breaking this again.

### CODE REVIEW

**Comment by carlocab** [comment]
Linux is failing because it can't find the zlib headers. Maybe related to the removal of zlib from the Docker container? CC @Bo98

**Comment by Bo98** [comment]
Looks like this has never been using Homebrew zlib properly then 🙂 

Upstream zlib detection doesn't look like it's very good: https://github.com/gcc-mirror/gcc/blob/releases/gcc-14.1.0/config/zlib.m4. So sounds like we have to pass CFLAGS ourselves, unlike every other dependency where we can pass it properly as an option.

**Comment by carlocab** [comment]
Note: there is an alternative approach at https://github.com/Homebrew/homebrew-core/pull/171822.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @carlocab

**Pull request merged**
