### PR TITLE
gettext 0.20.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tschoonj** [comment]
Wow, looks like this PR will become a gigantic revbump fest 😄

**Comment by fxcoudert** [comment]
- Seeing `pygobject` build failure, @tschoonj can you give a look?

<details>
<pre>
==> ./configure --prefix=/usr/local/Cellar/pygobject/2.28.7_2 --disable-introspection
==> make install
Last 150 lines from /Users/brew/Jenkins/workspace/core/logs/pygobject/02.make:
libtool: install: /usr/bin/install -c .libs/libpyglib-2.0-python.lai /usr/local/Cellar/pygobject/2.28.7_2/lib/libpyglib-2.0-python.la
Byte-compiling python modules...
__init__.pyoption.py
Byte-compiling python modules (optimized versions) ...
__init__.pyoption.py
Making install in gobject
  CC     _gobject_la-gobjectmodule.lo
  CC     _gobject_la-pygboxed.lo
  CC     _gobject_la-pygenum.lo
  CC     _gobject_la-pygflags.lo
  CC     _gobject_la-pyginterface.lo
  CC     _gobject_la-pygobject.lo
  CC     _gobject_la-pygparamspec.lo
  CC     _gobject_la-pygpointer.lo
  CC     _gobject_la-pygtype.lo
  CC     _gobject_la-ffi-marshaller.lo
  CCLD   _gobject.la
make[2]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/usr/local/Cellar/pygobject/2.28.7_2/include/pygtk-2.0'
 .././install-sh -c -d '/usr/local/Cellar/pygobject/2.28.7_2/lib/python2.7/site-packages/gobject'
 .././install-sh -c -d '/usr/local/Cellar/pygobject/2.28.7_2/lib/python2.7/site-packages/gobject'
 /usr/bin/install -c -m 644 pygobject.h '/usr/local/Cellar/pygobject/2.28.7_2/include/pygtk-2.0'
mkdir: /usr/local/Cellar/pygobject/2.28.7_2/lib/python2.7/site-packages/gobject: File exists
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   _gobject.la '/usr/local/Cellar/pygobject/2.28.7_2/lib/python2.7/site-packages/gobject'
 /usr/bin/install -c -m 644 __init__.py constants.py propertyhelper.py '/usr/local/Cellar/pygobject/2.28.7_2/lib/python2.7/site-packages/gobject'
libtool: install: /usr/bin/install -c .libs/_gobject.so /usr/local/Cellar/pygobject/2.28.7_2/lib/python2.7/site-packages/gobject/_gobject.so
libtool: install: /usr/bin/install -c .libs/_gobject.lai /usr/local/Cellar/pygobject/2.28.7_2/lib/python2.7/site-packages/gobject/_gobject.la
Byte-compiling python modules...
__init__.pyconstants.pypropertyhelper.py
Byte-compiling python modules (optimized versions) ...
__init__.pyconstants.pypropertyhelper.py
Making install in gio
(cd .\
	 && /usr/local/opt/python@2/bin/python ../codegen/codegen.py \
	    --py_ssize_t-clean \
	    --register gio-types.defs \
	    --register unix-types.defs \
	    --override gio.override \
	    --prefix pygio gio.defs) > ./gen-gio.c \
	&& cp ./gen-gio.c ./gio.c \
  CC     _gio_la-giomodule.lo
	&& rm -f ./gen-gio.c
  CC     _gio_la-pygio-utils.lo
Could not write method GCancellable.connect: No ArgType for GCallback
Warning: generating old-style constructor for:g_emblemed_icon_new
Could not write method GFileInfo.get_attribute_data: No ArgType for GFileAttributeType*
Could not write method GFileInfo.get_attribute_stringv: No ArgType for char**
Could not write method GFileInfo.set_attribute: No ArgType for gpointer
Could not write method GBufferedInputStream.peek: No ArgType for void*
Could not write method GBufferedInputStream.peek_buffer: No ArgType for gsize*
Could not write method GSocketAddress.to_native: No ArgType for gpointer
Warning: generating old-style constructor for:g_inet_socket_address_new
Warning: generating old-style constructor for:g_network_address_new
Warning: generating old-style constructor for:g_network_service_new
Warning: generating old-style constructor for:g_socket_new
Could not write method GSocket.receive_from: No ArgType for GSocketAddress**
Could not write method GSocket.receive_message: No ArgType for GSocketAddress**
Could not write method GSocket.send_message: No ArgType for GOutputVector*
Could not write method GSocket.create_source: No ArgType for GIOCondition
Could not write method GSocketControlMessage.serialize: No ArgType for gpointer
Warning: generating old-style constructor for:g_threaded_socket_service_new
Warning: generating old-style constructor for:g_simple_async_result_new
Could not write constructor for GSimpleAsyncResult: No ArgType for GAsyncReadyCallback
Warning: generating old-style constructor for:g_file_icon_new
Could not write method GAsyncInitable.init_async: No ArgType for GAsyncReadyCallback
Could not write method GFile.load_partial_contents_async: No ArgType for GFileReadMoreCallback
Could not write method GFile.load_partial_contents_finish: No ArgType for char**
Could not write function async_initable_new_async: varargs functions not supported
Could not write function async_initable_newv_async: No ArgType for GParameter*
Could not write function async_initable_new_valist_async: No ArgType for va_list
Could not write function content_type_guess_for_tree: No ArgType for char**
Could not write function initable_new: varargs functions not supported
Could not write function initable_newv: No ArgType for GParameter*
Could not write function initable_new_valist: No ArgType for va_list
Could not write function resolver_free_addresses: No ArgType for GList*
Could not write function resolver_free_targets: No ArgType for GList*
Could not write function resolver_error_quark: No ArgType for GQuark
Could not write function simple_async_result_new_from_error: No ArgType for GAsyncReadyCallback
Could not write function simple_async_report_gerror_in_idle: No ArgType for GAsyncReadyCallback
Could not write function socket_address_new_from_native: No ArgType for gpointer
Could not write function socket_control_message_deserialize: No ArgType for gpointer
Could not write function srv_target_list_sort: No ArgType for GList*
Warning: Constructor for GEmblemedIcon needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GNetworkAddress needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GNetworkService needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GSocket needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GInetSocketAddress needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GThreadedSocketService needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GMemoryOutputStream needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GSimpleAsyncResult needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GFileIcon needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
***INFO*** The coverage of global functions is 72.73% (40/55)
***INFO*** The coverage of methods is 97.27% (535/550)
***INFO*** There are no declared virtual proxies.
***INFO*** There are no declared virtual accessors.
***INFO*** There are no declared interface proxies.
  CC     unix_la-unixmodule.lo
(cd .\
	 && /usr/local/opt/python@2/bin/python ../codegen/codegen.py \
	    --py_ssize_t-clean \
	    --register gio-types.defs \
	    --register unix-types.defs \
	    --override unix.override \
	    --prefix pyunix unix.defs) > ./gen-unix.c \
	&& cp ./gen-unix.c ./unix.c \
	&& rm -f ./gen-unix.c
  CC     _gio_la-gio.lo
Warning: generating old-style constructor for:g_desktop_app_info_new
Could not write method GUnixFDMessage.steal_fds: No ArgType for gint*
Warning: generating old-style constructor for:g_unix_input_stream_new
Warning: generating old-style constructor for:g_unix_output_stream_new
Warning: generating old-style constructor for:g_unix_socket_address_new
Could not write function g_desktop_app_info_new_from_keyfile: No ArgType for GKeyFile*
Could not write function unix_mount_points_get: No ArgType for guint64*
Could not write function unix_mounts_get: No ArgType for guint64*
Could not write function unix_mount_at: No ArgType for guint64*
Warning: Constructor for GUnixConnection needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GDesktopAppInfo needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GUnixFDMessage needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GUnixInputStream needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GUnixOutputStream needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
Warning: Constructor for GUnixSocketAddress needs to be updated to new API
         See http://live.gnome.org/PyGTK_2fWhatsNew28#update-constructors
***INFO*** The coverage of global functions is 81.82% (18/22)
***INFO*** The coverage of methods is 92.86% (13/14)
***INFO*** There are no declared virtual proxies.
***INFO*** There are no declared virtual accessors.
***INFO*** There are no declared interface proxies.
  CC     unix_la-unix.lo
unix.override:27:10: fatal error: 'gio/gdesktopappinfo.h' file not found
#include <gio/gdesktopappinfo.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [unix_la-unix.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1
</pre>
</details>

- `vte3` also failing to build, with:
<details>
<pre>
  DOC   Building HTML
  DOC   Fixing cross-references
Traceback (most recent call last):
  File "/usr/local/Cellar/gtk-doc/1.30/libexec/bin/gtkdoc-fixxref", line 28, in <module>
    from gtkdoc import common, config, fixxref
  File "/usr/local/Cellar/gtk-doc/1.30/share/gtk-doc/python/gtkdoc/fixxref.py", line 28, in <module>
    from . import common, highlight
  File "/usr/local/Cellar/gtk-doc/1.30/share/gtk-doc/python/gtkdoc/highlight.py", line 28, in <module>
    from pygments import highlight
ModuleNotFoundError: No module named 'pygments'
make[2]: *** [html-build.stamp] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
</pre>
</details>

- `orbit` fails to build, with:
<details>
<pre>
Making install in inhibit
(rm -f baa.h baa-stubs.c baa-skels.c baa-common.c baa-imodule.c baa-skelimpl.c || true) > /dev/null
(rm -f foo.h foo-stubs.c foo-skels.c foo-common.c foo-imodule.c foo-skelimpl.c || true) > /dev/null
../../src/idl-compiler/orbit-idl-2 --showcpperrors -I. --deps ./.deps/baa.idl.P baa.idl
../../src/idl-compiler/orbit-idl-2 --showcpperrors -I. --deps ./.deps/foo.idl.P foo.idl
orbit-idl-2 2.14.19 compiling
  mode, show preprocessor errors, passes: stubs skels common headers 

Processing file baa.idl
orbit-idl-2 2.14.19 compiling
  mode, show preprocessor errors, passes: stubs skels common headers 

Processing file foo.idl

** (orbit-idl-2:74983): WARNING **: 12:28:19.151: failed to create '.deps' directory 'File exists'
make[3]: *** [foo.h] Segmentation fault: 11
make[3]: *** Deleting file `foo.h'
make[3]: *** Waiting for unfinished jobs....
for I in baa.h baa-stubs.c baa-skels.c baa-common.c baa-imodule.c baa-skelimpl.c; do \
		if test -f $I; then \
			sed -e 's,OObject,Object,g' -e 's,TTypeCode,TypeCode,g' $I > $I.out; \
			mv $I.out $I ; \
		fi; \
	done
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
</pre>
</details>

- `exiv2` source fails to download

**Comment by tschoonj** [comment]
Looks like `pygobject` doesn't like the new `glib` 😢 

How about simply removing `pygobject` (which is python2 only anyway) and the formulas that depend on it?

**Comment by fxcoudert** [comment]
That's a lot, isn't it?

```
$ brew uses --recursive --include-build pygobject
diffuse               gnome-builder         gtk-mac-integration   gwyddion              pygtkglext            vte
evince                gnome-latex           gtksourceview         lablgtk               pygtksourceview       zim
gedit                 gnome-recipes         gtksourceviewmm       nicotine-plus         siril
glade                 gspell                gtranslator           pygtk                 terminator
```

Some are very often used, like `gtk-mac-integration`, `evince`, `gspell`, …

**Comment by tschoonj** [comment]
It's not bad as it looks actually, most of these depend on pygobject indirectly through gtk-mac-integration which has an optional dependency on pygtk, and these formulas don't even use that functionality anyway.

The problematic ones really are gwyddion, diffuse, nicotine-plus, which are all python2 only and therefore problematic regardless.

**Comment by fxcoudert** [comment]
I'm killing the current build after 9 h 30 min, because it's failing many many times over `pygobject`.

Missing revision bumps: `baobab cracklib easy-tag efl file-roler geocode-lib ghex gitg glib gnome-autoar gnumeric gradio gstreamer gucharmap gxml libgweather makepkg php php@7.1 php@7.2 prefixsuffix simplescan`

**Comment by tschoonj** [comment]
see #39657 for the `pygobject` fix

**Comment by fxcoudert** [comment]
`exiv2` being dealt with in https://github.com/Homebrew/homebrew-core/pull/39671

**Comment by lembacon** [comment]
gettext 0.20.1 is released, updated.

**Comment by fxcoudert** [comment]
Testing so far:

- formulas that were accidentally revision-bumped twice: `glib gstreamer`
- test failures: `opentsdb octave pgrouting` (not always, not on all macOS versions)

We're 13 hours in, and Mojave node has built 68 bottles out of 307.

**Comment by fxcoudert** [comment]
- Bottles job failed because of conflicts, so we are going to have to rerun the CI 😢

**Comment by lembacon** [comment]
> * Bottles job failed because of conflicts, so we are going to have to rerun the CI 😢

My bad, sorry. 😢

**Comment by fxcoudert** [comment]
@lembacon let's merge as much as we can now, and fix the minor issues above. I'll rebase and rerun CI. Maybe we can lock core for 48 hours to prevent issues in the next run.?

**Comment by lembacon** [comment]
> @lembacon let's merge as much as we can now, and fix the minor issues above. I'll rebase and rerun CI. Maybe we can lock core for 48 hours to prevent issues in the next run.?

I'm 👍 on doing this. 😅

**Comment by fxcoudert** [comment]
@lembacon problems fixed, re-running CI.
Locked homebrew-core, so nobody merges anything until this is over.

**Comment by SMillerDev** [comment]
Do we want to do another run of this? @lembacon and @fxcoudert ?

**Comment by fxcoudert** [comment]
Rebased, trying again. Let's see where we're at now.

**Comment by fxcoudert** [comment]
The commits to `gobject-introspection` and `mutt` conflict and prevented the bottles from being uploaded 😭

**Comment by tschoonj** [comment]
Sorry! Forgot about this! Please reinstate  that 5 required review condition so this won’t happen again...

**Comment by fxcoudert** [comment]
- `r` and `gst-validate` fail to download some files: 
- `mikutter` fails to build with:

```
==> gem install /Users/brew/Library/Caches/Homebrew/downloads/9e23b9b5bbe27157f2a1cb1a9dfef74ff3becf404da33046d36edfd0648caee9--pluggaloid-1.1.1.gem --no-document --install-dir /usr/local/Cellar/mikutter/3.7.4_3/lib/mikutter/vendor
ERROR:  Error installing /Users/brew/Library/Caches/Homebrew/downloads/9e23b9b5bbe27157f2a1cb1a9dfef74ff3becf404da33046d36edfd0648caee9--pluggaloid-1.1.1.gem:
	delayer requires Ruby version >= 2.4.0.
```

- `libhttpseverywhere` fails with various `vala` issues:

```

**Comment by lembacon** [comment]
I've completely forgotten about this, sorry 😢

**Comment by tschoonj** [comment]
The `libhttpseverywhere` problem should be fixed by applying https://gitlab.gnome.org/GNOME/libhttpseverywhere/commit/6da08ef1ade9ea267cecf14dd5cb2c3e6e5e50cb

**Comment by fxcoudert** [comment]
Merged, but we still need to deal with:
- `libhttpseverywhere` (see above)
- `rpm` rebottling

**Comment by tschoonj** [comment]
I'll take care of `libhttpseverywhere`

Thanks for merging this monster in!

**Pull request closed without merging**
