### PR TITLE
wcslib 7.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
```
==> brew livecheck cpl --full-name --debug
==> FAILED
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cpl.rb

Formula:          cpl
Livecheckable?:   Yes

URL:              https://www.eso.org/sci/software/cpl/download.html
Strategy:         PageMatch
Regex:            /href=.*?cpl[._-]v?(\d+(?:\.\d+)+)\.t/i
Error: cpl: curl: (28) Operation timed out after 15010 milliseconds with 0 bytes received
```

**Comment by carlocab** [comment]
We should try to fix that, as those failures prevent dependents from being tested (which we should probably fix too...)

**Comment by iMichka** [comment]
Can this be rebased?

If the live check does not work, it can also be removed, so that we can at least ship the package's update.

**Comment by iMichka** [comment]
Blocked by #88604 for `cpl`.

**Comment by iMichka** [comment]
Tested locally on macOS 11. `astrometry-net` test passes with `wcslib` 7.6, but not with 7.7. But I have no clue how to fix this.

I'll open an issue upstream.

**Comment by iMichka** [comment]
Reported upstream https://github.com/dstndstn/astrometry.net/issues/241

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Merging. The `astronometry-net` test failure is unrelated. A fix is incoming with dstndstn/astrometry.net#241.

**Pull request closed without merging**
