### PR TITLE
bazarr: don't fail test on GitHub API error

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Another attempt at #139008.

### CODE REVIEW

**Comment by chenrui333** [comment]
this does not work, you can try it on the CI runner (I actually removed this line and still does not work)

**Comment by chenrui333** [comment]
that is basically this log about

> error message would be as below for server start
> 
> ```
> Bazarr starting...
> 2023-08-08 14:04:51,926 - root                             (10e0c8e00) :  ERROR (check_update:25) - Error trying to get releases from Github. Http error.
> 2023-08-08 14:04:54,155 - root                             (10e0c8e00) :  ERROR (check_update:25) - Error trying to get releases from Github. Http error.
> Traceback (most recent call last):
>   File "/usr/local/Cellar/bazarr/1.2.4/libexec/bazarr/main.py", line 35, in <module>
>     check_if_new_update()
>   File "/usr/local/Cellar/bazarr/1.2.4/libexec/bazarr/app/check_update.py", line 62, in check_if_new_update
>     with open(os.path.join(args.config_dir, 'config', 'releases.txt'), 'r') as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/bazarr-test-20230808-7412-y55jsd/config/releases.txt'
> Bazarr exited.
> ```

**Comment by ZhongRuoyu** [comment]
Weird. I believe with `--no-update` it should work, as `check_if_new_update` won't be executed at all: https://github.com/morpheus65535/bazarr/blob/v1.2.4/bazarr/main.py#L28-L35

Will try to reproduce on CI.

**Comment by ZhongRuoyu** [comment]
I repeated the test 50 times on Ubuntu and Intel macOS (11, 12, & 13). I could still see the failure on `master` ([run](https://github.com/ZhongRuoyu/actions-test/actions/runs/5805809986)), but couldn't reproduce it anymore on this branch ([run](https://github.com/ZhongRuoyu/actions-test/actions/runs/5805804995)).

> I actually removed this line and still does not work

To be sure, did you also add `--no-update` when you ran the test?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
okay, let's give it a try.

**Comment by chenrui333** [comment]
i take it back, it works pretty well now. Great work!
image

**Pull request merged**
