### PR TITLE
mcap 0.0.20

### PR DESCRIPTION
**Pull request by foxglovebot**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by carlocab** [comment]
Test broke. It seems too fragile to be a good test.

**Comment by jhurliman** [comment]
> Test broke. It seems too fragile to be a good test.

The problem it caught is `* Formula license ["Apache-2.0"] does not match GitHub license ["MIT"].` It looks like a legitimate issue rather than test fragility.

**Comment by carlocab** [comment]
> > Test broke. It seems too fragile to be a good test.
> 
> The problem it caught is `* Formula license ["Apache-2.0"] does not match GitHub license ["MIT"].` It looks like a legitimate issue rather than test fragility.

Nope, that's the [`brew audit` failure](https://github.com/Homebrew/homebrew-core/actions/runs/3140608644/jobs/5102219677#step:6:31). The [`brew test` failure](https://github.com/Homebrew/homebrew-core/actions/runs/3140608644/jobs/5102219677#step:6:56) is from a change in the format of the output of calling `mcap info`:
```
  ==> /opt/homebrew/Cellar/mcap/0.0.20/bin/mcap info OneMessage-ch-chx-mx-pad-rch-rsh-st-sum.mcap
  Error: mcap: failed
  An exception occurred within a child process:
    Minitest::Assertion: --- expected
  +++ actual
  @@ -1 +1 @@
  -["library:", "profile:", "messages: 1", "duration: 0s", "start: 0.000", "end: 0.000", "compression:", ": [1/1 chunks] (0.00%)", "channels:", "(1) example  1 msgs (+Inf Hz)   : Example [c]", "attachments: 0"]
  +["library:", "profile:", "messages: 1", "duration: 0s", "start: 0.000", "end: 0.000", "compression:", ": [1/1 chunks] (0.00%)", "channels:", "(1) example  1 msgs (+Inf Hz)   : Example [c]", "attachments: 0", "metadata: 0"]
```
In particular, `mcap info` now produces an extra line that says `metadata: 0` which the `test` does not expect.

**Comment by jhurliman** [comment]
I see this failure as well:

```
  -["library:", "profile:", "messages: 1", "duration: 0s", "start: 0.000", "end: 0.000", "compression:", ": [1/1 chunks] (0.00%)", "channels:", "(1) example  1 msgs (+Inf Hz)   : Example [c]", "attachments: 0"]
  +["library:", "profile:", "messages: 1", "duration: 0s", "start: 0.000", "end: 0.000", "compression:", ": [1/1 chunks] (0.00%)", "channels:", "(1) example  1 msgs (+Inf Hz)   : Example [c]", "attachments: 0", "metadata: 0"]
```

**Comment by jtbandes** [comment]
@carlocab fixed, please take another look when you get a chance! Thanks.

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
