### PR TITLE
ansible@2.8 depends on python (3.8) but should on python@3.7

### LINKED ISSUE #57719: ansible@2.8 depends on python@3.8 but should on python@3.7
I need ansible@2.8 but IMHO that formula has a bug making it impossible to work.
https://github.com/Homebrew/homebrew-core/blob/99decbea6523c2c47d5bd15e1b7398eb142eed84/Formula/ansible%402.8.rb#L22-L24

The problem with python version is even stated in the comment. The ansible 2.8 should be paired with max python 3.7, but right now it depends on `python` formula which now points to `3.8`. I think the issue happen because previously `python` formula was pointing to `3.7` - which was correct for ansible 2.8, but now `python` formula points to `3.8` so I guess ansible@2.8 formula should have dependency on `python@3.7` formula instead of `python`.

Is there any easy and quick way to hot modify this formula to get it properly installed on my local machine?

### PR DESCRIPTION
**Pull request by arvenil**
Fixes #57719

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you add `revision 1`, that'll make sure everyone gets this update.

**Comment by arvenil** [comment]
@SMillerDev Thanks, I've bumped it to revision 2, should be correct now?

**Comment by SMillerDev** [comment]
It should be, but something is breaking CI.

**Comment by Rylan12** [comment]
The issue should be fixed in https://github.com/Homebrew/brew/pull/7959

**Comment by arvenil** [comment]
@Rylan12 Thank you again! Exactly I just debugged that `virtualenv_install_with_resources` fails, then I found out issue https://github.com/Homebrew/brew/pull/6858 and then I noticed missing python@3.7 locally I've also used `virtualenv_install_with_resources using: "python3.8"` and it works! Thank you again!

**Comment by Rylan12** [comment]
No problem! The PR has been merged so I'm going to give this another go

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Thanks for your first contribution to Homebrew, @arvenil! 🥳 🎉🥇

Thanks to contributors like you, we're able to maintain Homebrew to the high standards that users expect. Thanks again for your work! 👍

**Pull request closed without merging**
