### PR TITLE
pmd 5.5.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
I believe this needs `-Xdoclint:none` though I'm not sure how to pass that to mvn.

**Comment by apjanke** [comment]
It should probably go in the POM file that controls the Maven build. Any options that affect build behavior generally go in that file instead of being passed to the `mvn` command at build time. I'll have a swing at adding it.

**Comment by ilovezfs** [comment]
@apjanke cool, thank you!

**Comment by apjanke** [comment]
#4139

**Comment by apjanke** [comment]
Closed in favor of #4139, which is now merged.

**Pull request closed without merging**
