### PR TITLE
groonga 10.0.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
license header ref:
```
/* -*- c-basic-offset: 2 -*- */
/*
  Copyright(C) 2009-2018 Brazil
  Copyright(C) 2018-2020 Sutou Kouhei <kou@clear-code.com>

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License version 2.1 as published by the Free Software Foundation.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
```

**Comment by chenrui333** [comment]
```
## Bundled software

### mruby

  * Path: vendor/mruby-source
  * License: The MIT license. See vendor/mruby-source/MITL for details.

### Onigmo

  * Path: vendor/onigmo-source
  * License: BSD license. See vendor/onigmo-source/COPYING for details.

### nginx

  * Path: vendor/nginx-${VERSION}
  * License: BSD license. See vendor/nginx-${VERSION}/LICENSE for details.
```

**Comment by chenrui333** [comment]
license for this seems little bit complicated, will file a separate one for license discussions.

**Comment by SMillerDev** [comment]
Please remove the license then

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
