### PR TITLE
bluepill 5.1.8

### PR DESCRIPTION
**Pull request by shwang53**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
need to double check on this,  `depends_on :xcode => ["11.2", :build]`

**Comment by Bo98** [comment]
The README stills states 11.2.

**Comment by chenrui333** [comment]
Sounds good, move to `ready to merge`.

**Pull request closed without merging**
