### PR TITLE
spades 3.14.0

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by mistydemeo** [comment]
Build failed only on Mojave:

```
/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include-fixed/stdio.h:222:7: error: conflicting declaration of 'char* ctermid(char*)' with 'C' linkage
  222 | char *ctermid(char *);
      |       ^~~~~~~
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:525,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/boost/config/stdlib/libstdcpp3.hpp:78,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/boost/config.hpp:49,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/boost/numeric/ublas/matrix.hpp:17,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/ConsensusCore/Matrix/DenseMatrix.hpp:42,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/ext/src/ConsensusCore/Matrix/DenseMatrix.cpp:39:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_ctermid.h:26:10: note: previous declaration with 'C++' linkage
   26 | char    *ctermid(char *);
      |          ^~~~~~~
```

**Comment by jonchang** [comment]
Fixed by  #50623

**Comment by tseemann** [comment]
@dawidd6 are you able to assist with the response from the upstream author?

https://github.com/ablab/spades/issues/439

_Yes. The problem is that gcc has the process called "fixincludes" that at the build time patches on-fly some system headers and stores their copies into the gcc's internal include directory so patched variants are included first. This is very error-prone process on Darwin as headers could change after SDK update and the "fixincluded" one would be bogus like here.

The solution is either "fix" the header inside brew or to build gcc from source, so it'd pick fresh header from SDK. Sorry, but it's not SPAdes bug at all :)_

**Comment by jonchang** [comment]
@tseemann can you test the bottle to see if openmp threading works?

**Comment by zbeekman** [comment]
Just to confirm, Spades is a stand alone application, correct? I.e., not a library or toolkit that gets called from other tools?

**Comment by sjackman** [comment]
> Just to confirm, Spades is a stand alone application, correct? I.e., not a library or toolkit that gets called from other tools?

Correct.

**Comment by tseemann** [comment]
@sjackman @jonchang @zbeekman thank you all for your help. i would have never figured out those patches!

**Comment by issyl0** [comment]
Rebased this on master, fixed the conflicts, and squashed the two commits. One more run of CI and  then I'll merge. Thanks, @tseeman!

**Comment by tseemann** [comment]
Thanks @issyl0 - this is a key tool in my field.

**Pull request closed without merging**
