### PR TITLE
chakra 1.11.15

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
With Xcode 11:

```
/tmp/chakra-20191009-92499-1eshv12/ChakraCore-1.11.14/lib/Backend/amd64/LinearScanMdA.S:54:34: error: unknown token in expression
    movups xmmword ptr [rax + 80h], xmm0
                                 ^
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@chenrui333 I'm not sure why you wanted to rerun the CI? There is a clear error

**Comment by chenrui333** [comment]
That is true, I will submit a upstream request to get some help on this.

**Comment by fxcoudert** [comment]
OK, we need this for https://github.com/Homebrew/homebrew-core/pull/48349
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Trying upstream commit for https://github.com/microsoft/ChakraCore/pull/6112

**Pull request closed without merging**
