### PR TITLE
go 1.16.6

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
ARM:
```
 Error: 23 failed steps!
brew test --retry --verbose akamai
brew test --retry --verbose awsweeper
brew install --build-from-source cf-tool
brew test --retry --verbose chezmoi
brew install --build-from-source --only-dependencies clair
brew install --build-from-source clair
brew install --build-from-source --only-dependencies docker-machine-driver-hyperkit
brew install --build-from-source docker-machine-driver-hyperkit
brew install --build-from-source --only-dependencies dockviz
brew install --build-from-source dockviz
brew install --build-from-source dvm
brew install --build-from-source envoy
brew install --build-from-source envoy@1.17
brew test --retry --verbose func-e
brew install --build-from-source --only-dependencies ironcli
brew install --build-from-source ironcli
brew install --build-from-source mpdviz
brew install --build-from-source packer
brew install --build-from-source pilosa
brew test --retry --verbose server-go
brew install --build-from-source --only-dependencies vert
brew install --build-from-source vert
brew install --build-from-source virgil
```

**Comment by nandahkrishna** [comment]
ARM Big Sur:

- [x] akamai: no bottle
- [x] awsweeper: no bottle
- [x] cf-tool: no bottle
- [x] chezmoi: weirdly enough, test failure seems to be because it is using the formula installed from the bottle, which is version 2.1.1 built prior to this PR. In-between that version bump and this PR, #80608 was merged without bottles and the test was changed. We can ignore the failure in this PR but I'm unsure if `test-bot` behaviour is as expected.
- [x] clair: no bottle
- [x] docker-machine-driver-hyperkit: no bottle
- [x] dockviz: no bottle
- [x] dvm: no bottle
- [x] envoy: no bottle
- [x] envoy@1.17: no bottle
- [x] func-e: no bottle
- [x] ironcli: no bottle
- [x] mpdviz: no bottle
- [ ] packer: bottled, build failure
- [x] pilosa: no bottle
- [x] server-go: no bottle
- [x] vert: no bottle
- [x] virgil: no bottle

Intel Big Sur:
- [x] chezmoi: same as ARM
- [ ] orgalorg: bottled, test failure
- [ ] packer: bottled, build failure

Catalina:
- [x] chezmoi: same as ARM
- [ ] envoy: bottled, build failure
- [ ] envoy@1.17: bottled, build failure
- [ ] packer: bottled, build failure

Mojave:

- [x] chezmoi: same as ARM
- [ ] fn: bottled, test failure, usually flaky
- [ ] orgalorg: bottled, test failure
- [ ] packer: bottled, build failure

**Comment by nandahkrishna** [comment]
Built and tested `orgalorg` successfully on Intel Big Sur (local). The test is probably flaky because it involves `free_port`, and it failed even when being installed from the bottle on CI (hence the double failure for `brew test --retry orgalorg`).

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Ok. Envoy is still outstanding, but the bottles should still work (AFAIK, and there's no reason why this PR should break those...), and is currently in progress. Let's move this along.

**Comment by carlocab** [comment]
Thanks for the work here, all!

**Pull request closed without merging**
