### PR TITLE
percona-server 8.0.25-15

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/actions/runs/1002437576

```make
-- KERBEROS path is none, disabling kerberos support.
CMake Warning at cmake/sasl.cmake:264 (MESSAGE):
  Could not find SASL
Call Stack (most recent call first):
  CMakeLists.txt:1395 (MYSQL_CHECK_SASL)

...


CMake Error at CMakeLists.txt:1418 (MESSAGE):
  Please install the patchelf(1) utility.
```

### CODE REVIEW

**Comment by cho-m** [comment]
```
==> ./mysql-test-run.pl status --vardir=/tmp/d20210706-9039-x70zuu
Logging: ./mysql-test-run.pl  status --vardir=/tmp/d20210706-9039-x70zuu
MySQL Version 8.0.23
Checking supported features
Using 'all' suites
Collecting tests
Removing old var directory
Creating var directory '/tmp/d20210706-9039-x70zuu'
Installing system database
Using parallel: 1

==============================================================================
                  TEST NAME                       RESULT  TIME (ms) COMMENT
------------------------------------------------------------------------------
[ 50%] main.status                               [ fail ]  Found warnings/errors in error log file!
        Test ended at 2021-07-06 20:08:13
line
Warning: 6T20:07:36.741264Z 0 [Warning] [MY-011825] [InnoDB] Setting thread 31563 nice to 0 failed, current nice 10, errno 13
Warning: 6T20:07:36.741375Z 0 [Warning] [MY-011825] [InnoDB] Failed to set I/O thread priority to 19 the current priority is 9
```

**Comment by cho-m** [comment]
The Linux error may be related to Docker container restrictions 
https://docs.docker.com/config/containers/resource_constraints/#configure-individual-containers
Perhaps using `--cap-add=sys_nice`. 

May just disable build-time test for now.

**Comment by cho-m** [comment]
Mainly need a review of Linux changes as it is majority of diff.

The version bump is only `url`/`sha256` update.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Nice work.

**Pull request closed without merging**
