### PR TITLE
crosstool-ng 1.23.0 add lzip dependency to install

### PR DESCRIPTION
**Pull request by troian**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by mistydemeo — DISMISSED** [review]
Can you please place this dependency in a `head do` block, if it's only needed by `head`? You can look at `fish` as one example of a formula that does this.

**Comment by troian** [comment]
Changed description it is not only build dependency, some of packages can be lzipped.
https://github.com/crosstool-ng/crosstool-ng/commit/1a3b562c75e40f9c2914727aa909d7605786eddc

**Comment by mistydemeo** [comment]
Is this used in the stable version yet or just in HEAD? The commit you linked is from the 1.24.0 prereleases.

**Comment by troian** [comment]
For now it’s HEAD only, when 1.24.0 released it will be required to stable releases as well

**Comment by troian** [comment]
It's not quite right. This change not only for HEAD

**Comment by fxcoudert** [comment]
You said above:

> For now it’s HEAD only, when 1.24.0 released it will be required to stable releases as well

**Pull request merged**
