### PR TITLE
srm: delete

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`srm` not only doesn't work as intended on SSDs, but also reduces their lifespan.

CC @MikeMcQuaid @fxcoudert

See https://github.com/Homebrew/homebrew-dupes/issues/725#issuecomment-281058503.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Seems reasonable to me.

**Comment by chdiza** [comment]
Why the middle finger at people who own spinning platter disks?

**Comment by MikeMcQuaid** [comment]
> Why the middle finger at people who own spinning platter disks?

@chdiza Ask Apple 😉

**Comment by chdiza** [comment]
Homebrew is adding its own middle finger to the chorus, and for no good reason.

**Pull request merged**
