### PR TITLE
gtk-vnc 0.6.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by DomT4** [comment]
The deps block not being in tag order is mildly distressing if you're feeling particularly lovely, but otherwise 👍.

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed. I also removed the patch because upstream closed the PR on 2016-07-21 due to lack of activity: https://bugzilla.gnome.org/show_bug.cgi?id=602371

**Comment by ilovezfs** [comment]
Presumably this will now fail on Mavericks but pass on yosemite since we use 7.2. Not sure how to deal with a fails_with though since 700 seems to be used for 7.1 and 7.2.

**Comment by DomT4** [comment]
Generally we have to be careful about capping parts of the GTK+/GTK+3 tree because it pretty quickly blows up the entire tree in a lot of circumstances 🙈, but this doesn't seem to be used by anything at all, so 👍.

**Comment by ilovezfs** [comment]
so just ignore the problem with fails with that both <7.2 fails but 7.1 & 7.2 have same 700 build number and cross our fingers yosemite users are running 7.2?

**Comment by DomT4** [comment]
We don't officially support running anything but the latest stable Xcode for that particular OS X version, so that seems fine, yeah.

**Pull request closed without merging**
