### PR TITLE
krakend 0.5.0

### PR DESCRIPTION
**Pull request by alombarte**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@alombarte the sha256 has not changed since https://github.com/Homebrew/homebrew-core/pull/28821. So we should expect the same test failure as over there:

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/25524/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/test_krakend/

**Comment by alombarte** [comment]
Will fix test and come back when ready

**Comment by ilovezfs** [comment]
Thanks!

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/28849

**Pull request closed without merging**
