### PR TITLE
kubernetes-cli 1.21.0

### PR DESCRIPTION
**Pull request by billinghamj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by billinghamj** [comment]
It's not too clear what's wrong with the ARM build - no logs etc. I think it may just need re-running.

I'm running on an M1 MacBook, and the build/test runs fine there

**Review by carlocab — APPROVED** [review]
Thanks, @billinghamj!

The ARM node since to have glitched, so I restarted CI. However, it looks like this should be good after another run.

**Comment by billinghamj** [comment]
Hmm seems like this is the error:

```ERROR: 
	 KUBE API rule check failed. Reported violations differ from known violations. Please read api/api-rules/README.md to resolve the failure in api/api-rules/violation_exceptions.list. 

make[1]: *** [pkg/generated/openapi/zz_generated.openapi.go] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [generated_files] Error 2
```

Doesn't make a ton of sense to me, the same build works fine on my machine

**Comment by billinghamj** [comment]
Sounds like sometimes it could be resolved with `make clean`, but wouldn't think too relevant in a CI environment: https://github.com/kubernetes/kubernetes/issues/82271

**Comment by carlocab** [comment]
Smells like a race condition to me. Let's try restarting the build and see if we get the same error.

**Comment by carlocab** [comment]
In your local successful build, did you use `brew` or is that a vanilla `make` build?

**Comment by billinghamj** [comment]
@carlocab it was with the brew command! Anyway who knows, thanks for merging :)

**Pull request closed without merging**
