### PR TITLE
lima 0.6.0

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Created with `brew bump-formula-pr` + updated the repo URL (`github.com/AkihiroSuda/lima` -> `github.com/lima-vm/lima`)

Release note: https://github.com/lima-vm/lima/releases/tag/v0.6.0

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
```
==> brew audit lima --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
Error: No such file or directory @ realpath_rec - /home/runner
lima:
  * Binaries built for a non-native architecture were installed into lima's prefix.
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/lima/0.6.0/share/lima/lima-guestagent.Linux-aarch64	(arm64)
```
https://github.com/Homebrew/homebrew-core/pull/82723/checks?check_run_id=3249657409

This is expected behavior, to support running ARM guests on an Intel host.

**Comment by SMillerDev** [comment]
I don't think this should be patched like this. The audit is correct, there is a non-native binary. This is on purpose though so upstream shouldn't try and trick the audit. Instead it needs to be added to the Homebrew allowlist.

**Comment by AkihiroSuda** [comment]
@SMillerDev PTAL https://github.com/Homebrew/brew/pull/11832

**Comment by AkihiroSuda** [comment]
in progress, waiting for https://github.com/Homebrew/brew/pull/11832 To be merged

**Comment by AkihiroSuda** [comment]
Updated PR to avoid patching, as https://github.com/Homebrew/brew/pull/11832 is merged

**Comment by AkihiroSuda** [comment]
@carlocab @chenrui333 @SMillerDev Could you take a look?

**Review by carlocab — APPROVED** [review]
Sorry, missed your update here. LGTM. Thanks!

**Pull request closed without merging**
