### PR TITLE
frei0r 2.3.0

### PR DESCRIPTION
**Pull request by osalbahr**
Created with `brew bump-formula-pr`.

***
```console
% brew bump frei0r
Running `brew update --auto-update`...
==> frei0r
Current formula version:  1.8.0
Latest livecheck version: 1.8.0
Latest Repology version:  2.3.0
Open pull requests:       frei0r 2.3.0 (https://github.com/Homebrew/homebrew-core/pull/135869)
Closed pull requests:     none
```

### CODE REVIEW

**Comment by osalbahr** [comment]
```console
  Error: An exception occurred within a child process:
    Errno::ENOENT: No such file or directory @ rb_sysopen - CMakeLists.txt
```

**Review by p-linnane — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by osalbahr** [comment]
I thought the CI failed for this PR https://github.com/Homebrew/homebrew-core/actions/runs/5467747485

**Comment by p-linnane** [comment]
You're looking at an old run.

https://github.com/Homebrew/homebrew-core/actions/runs/5467929728/jobs/9956630268

**Comment by osalbahr** [comment]
Oh, I guess rerunning the CI tests was necessary because of the repo location update. I see now. On that note, should the output of `brew bump <>` be automatically included in the PR to make it instantly obvious that the bump is to a version higher than livecheck? I edited the PR afterwards to add that.

**Comment by p-linnane** [comment]
The version should never be higher than livecheck unless there is a problem with livecheck. In this case, livecheck automatically pulls tags from GitHub, so we don't need to specify one. That's why I removed the livecheck pointing at the old site that had outdated versions.

**Comment by osalbahr** [comment]
Oh, I see. Thank you for explaining. Should another livecheck that points to the new repo be added?

**Comment by p-linnane** [comment]
Livecheck automatically uses the `:git` strategy on GitHub URL's, so that's not necessary.

https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy/Git.html

**Pull request merged**
