### PR TITLE
Migrate formulae to depend on `openjdk`.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by bayandin** [comment]
Is it necessary to migrate all these formulae at once? 
I see that the list is increasing and the time it takes on CI is increasing as well

**Comment by reitermarkus** [comment]
@bayandin, the list isn't increasing, it's decreasing. I'm always moving the failing formulae into separate PRs.

**Comment by bayandin** [comment]
Ah, probably I misread something. Thanks for the explanation!
Are we good to go? CI is green now

**Comment by reitermarkus** [comment]
Yep, let's merge this before there are conflicts again.

**Comment by jonchang** [comment]
Nice work everyone!! 🎆

**Pull request closed without merging**
