### PR TITLE
rust: actually fix duplicate object file bug

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

It seems the build doesn't make use of the vendored crate sources unless
one passes `--enable-vendor`.

### CODE REVIEW

**Comment by Bo98** [comment]
> It seems the build doesn't make use of the vendored crate sources unless
> one passes `--enable-vendor`.

Is it worth doing that? Feels unnecessary to have it download the sources again? What's the disadvantage?

(btw Rust 1.58 should release on Thursday, but it won't contain this fix)

**Comment by carlocab** [comment]
> Is it worth doing that? It feels unnecessary to have it download the sources again. What's the disadvantage?

Well, the disadvantage is that patching the vendored sources also requires updating some checksums somewhere, and I haven't worked out where those checksums are (and how exactly they are generated).

We probably do want `--enable-vendor` when we don't need to patch the builtins though.

**Comment by Bo98** [comment]
Are you referring to `.cargo-checksum.json`?

I agree though it might be easier to roll with this for now.

**Comment by carlocab** [comment]
#93099 seems stuck, so restarting this.

**Pull request closed without merging**
