### PR TITLE
itk 5.3.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Opened an issue upstream: https://github.com/InsightSoftwareConsortium/ITK/issues/3821

**Comment by p-linnane** [comment]
@cho-m Do we need to revision bump `pyqt@5` here? Or is there another issue I'm not seeing?

**Comment by cho-m** [comment]
We lost the Linux `pyqt@5` bottle in #117089. We'll first need a new Linux `qt@5` bottle as it is broken right now (not sure of our stance on revision bumping only Linux side right now vs rebottling).

**Comment by p-linnane** [comment]
Upstream [has confirmed](https://github.com/InsightSoftwareConsortium/ITK/issues/3821#issuecomment-1366194873) that that `ITK_USE_GPU` is not well supported and is going to be replaced. Their reommendation is to remove it from the formula, which we have done here.

**Comment by p-linnane** [comment]
Requires https://github.com/Homebrew/homebrew-core/pull/119257

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
