### PR TITLE
yt-dlp 2021.9.2

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by branchv — APPROVED** [review]

**Comment by bevanjkay** [comment]
@branchvincent A bit of deja vu on this one haha. Thanks 😄

**Comment by branchvincent** [comment]
@bevanjkay you're too quick!

**Comment by pukkandan** [comment]
> A bit of deja vu on this one haha

Sorry about that. There was an issue in the 09.01 release causing me to have to re-release immediately

**Comment by bevanjkay** [comment]
@pukkandan No worries there. It was just coincidental timing 😄

**Pull request closed without merging**
