### PR TITLE
hwloc 2.7.1

### PR DESCRIPTION
**Pull request by cho-m**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
The livecheck seems to only detect major/minor version right now. Download page for 2.7 shows patch version is now 2.7.1: https://www.open-mpi.org/software/hwloc/v2.7/

**Review by chenrui333 — DISMISSED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
I was able to fix the live check with:

```
livecheck do
    url :homepage
    regex(%r{hwloc v?(\d+(?:\.\d+)+)}i)
  end
```

It's looking at the `hwloc v.2.7.1` stable release box on the main page, right side. It's as fragile as the previous one, but better than nothing.

**Comment by cho-m** [comment]
Ping @samford for livecheck since current livecheck was added in previous PR #91250

**Comment by samford** [comment]
Unfortunately the `hwloc` `livecheck` block was just outside of where I could add a suggestion, so I simply pushed an updated `livecheck` block and cancelled CI, since it seemed like a long-ish one and I wasn't sure if other changes were needed here before the next run. For reference, the previous failed Linux run can be found here: https://github.com/Homebrew/homebrew-core/runs/6664049724.

From what I could see, checking the download page would require two requests (e.g., like `bash`), since the download page is versioned (e.g., [/software/hwloc/v2.7/](https://www.open-mpi.org/software/hwloc/v2.7/)) but doesn't include the full version in the URL. That is to say, it would require one request to identify the current download page URL from the homepage and another request to fetch the download page (matching the version from the tarball link).

I opted to simply match versions on the mailing list announce page, which provides version information in a somewhat reliable format. I had to leave the regex a bit looser than I would have liked (since one of the announcements list three versions in comma-separated fashion) but it works for all the current versions on the page (while also not matching `4.01` from the HTML DOCTYPE).

If we run into any issues with this in the future, just let me know and I can rework the `livecheck` block to check the download page in the two-request fashion. [For what it's worth, checking the Git tags doesn't seem like an option, as versions are tagged days (even a week) before the release is announced.]

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
