### PR TITLE
Fix berkeley-db@4 on mojave

### PR DESCRIPTION
**Pull request by DesWurstes**
- [ v] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ √ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [√ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Patch taken from here: https://gist.github.com/LnL7/5153b251fd525fe15de69b67e63a6075

Related: https://github.com/bitcoin/bitcoin/issues/14327

### CODE REVIEW

**Comment by DesWurstes** [comment]
But, before merging:

@LnL7 Do you allow the devs to embed your patch in Homebrew?

**Comment by LnL7** [comment]
I don't remember the details and don't know if that gist is still used (eg. https://github.com/NixOS/nixpkgs/pull/21049).
I would recommend looking at the patches/configure flags currently used in [nixpkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/db) instead.

That said I have no problem with including it in homebrew.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Patch is OK, renaming to avoid clashing with atomic builtins supported in recent clang.
Modified slightly to host the patch externally, making the formula easier to maintain.

**Comment by fxcoudert** [comment]
Thanks @DesWurstes for the pull request!

**Pull request closed without merging**
