### PR TITLE
fnm 1.22.9

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
❯ brew unbottled --tag=arm64_big_sur fnm
==> Populating dependency tree...
==> :arm64_big_sur bottle status
fnm: ready to bottle
```

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
```
Error: fnm--1.22.9.arm64_big_sur.bottle.tar.gz for upload doesn't exist!
```
Big Sur bottle is missing for some reason.

**Review by carlocab — APPROVED** [review]

**Comment by Schniz** [comment]
Hi @carlocab, is there something I can do to make sure there's an ARM build for fnm? Can we see the error somewhere?

**Comment by carlocab** [comment]
I've triggered a build at https://github.com/Homebrew/homebrew-core/actions/runs/525454392

That may give you abbreviated logs. If that's the case, you may wish to ask for the build logs from the user who asked about an ARM bottle. They can generate those with
```
brew install -sv fnm
brew gist-logs fnm
```
They may need to set `HOMEBREW_GITHUB_API_TOKEN` in order to use the `gist-logs` command. `man brew` will contain more details about how to do this.

**Comment by carlocab** [comment]
Ah, I see. The build succeeds, but the test fails.
```
==> /opt/homebrew/Cellar/fnm/1.22.9/bin/fnm install 12.0.0
Installing Node v12.0.0
error: Can't download the requested version: Can't find version upstream
```

**Comment by Schniz** [comment]
Ah alright. I will probably update all the versions to use latest Node which actually distributes ARM 😃 
Thanks!

**Pull request closed without merging**
