### PR TITLE
haskell-stack 1.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @borsboom

### CODE REVIEW

**Comment by ilovezfs** [comment]
Um ... upstream still hasn't fixed this on Sierra? What in the world …

**Comment by ilovezfs** [comment]
@borsboom is this not able to build on Sierra? I thought that had been fixed :(

**Comment by borsboom** [comment]
The problem isn't in Stack, it's in GHC.  It's been fixed in GHC 8.0.2, but the default `stack.yaml` is still using GHC 7.10.3 for this release (will be switching to 8.0.2 for the next one).  We do support building on GHC 8.0.2, however, and provide an alternate `stack-8.0.yaml` for that purpose.  You can use `stack --stack-yaml=stack-8.0.yaml` for that.

**Comment by ilovezfs** [comment]
Shipped! Thanks for the help @borsboom

**Pull request closed without merging**
