### PR TITLE
boost: add option to compile with C++14 support

### LINKED ISSUE #3133: add --c++14 to boost
Compiling my software with *boost* from Homebrew gives me error (posted on bottom of issue). It looks that `boost::context::execution_context::current()` used by Boost.Coroutines2 is missing from Homebrew's version. Searching for solutions led me to [this](http://lists.boost.org/Archives/boost/2016/03/228734.php) thread and it looks that `execution_context` from Boost.Context is added only if *boost* is compiled with `c++14` support.

So I propose adding possibility to compile *boost* with `--c++14` flag.

Linking error:
```c++
Undefined symbols for architecture x86_64:
  "boost::context::execution_context::current()", referenced from:
      boost::coroutines2::detail::pull_coroutine<int>::control_block::control_block<boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}>(boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}&&, bool) in ccNSDx9Q.o
      boost::coroutines2::detail::pull_coroutine<int>::control_block::control_block<boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}>(boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}&&, bool) in ccNSDx9Q.o
      boost::context::detail::activation_record* boost::context::execution_context::create_context<boost::context::basic_fixedsize_stack<boost::context::stack_traits>, boost::coroutines2::detail::pull_coroutine<int>::control_block::control_block<boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}>(boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}&&, bool)::{lambda(void*)#1}, std::tuple<> >(main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}, boost::context::preallocated, boost::coroutines2::detail::pull_coroutine<int>::control_block::control_block<boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}>(boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}&&, bool)::{lambda(void*)#1}, std::tuple<>&&) in ccNSDx9Q.o
      boost::coroutines2::detail::push_coroutine<int>::control_block::resume(int const&) in ccNSDx9Q.o
      boost::coroutines2::detail::pull_coroutine<int>::control_block::resume()  in ccNSDx9Q.o
  "___emutls_v._ZN5boost7context6detail17activation_record11current_recE", referenced from:
      TLS wrapper function for boost::context::detail::activation_record::current_rec in ccNSDx9Q.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by Marqin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Fixes #3133.

### CODE REVIEW

**Comment by DomT4** [comment]
Not being able to build with _any_ stable system Clang currently is a big temporary 👎 for me; we'd probably want to wait until there's at least one stable Clang that can handle it.

If we're going to start with `c++14` stuff perhaps it's time to introduce the logic to the core with a `:cxx14` addition. Feels pretty hostile to introduce these blobs into formulae directly. @UniqMartin maybe has thoughts/feelings. I try to avoid compiler discussions to protect my sanity.

**Comment by MikeMcQuaid** [comment]
> Not being able to build with any stable system Clang currently is a big temporary 👎 for me; we'd probably want to wait until there's at least one stable Clang that can handle it.



> If we're going to start with c++14 stuff perhaps it's time to introduce the logic to the core with a :cxx14 addition.

Agreed on both 👍

**Comment by Marqin** [comment]
Problem is that Apple's Clang for some reason doesn't support `thread_local` (it's supported in open-source version), but from what I see it started to be supported in XCode 8 Beta (that's why I put "799" as failing version) + it was said on WWDC 2016 that new Clang [will support it](http://asciiwwdc.com/2016/sessions/405#t=356.216).

So I should wait for Xcode 8 with this?

**Comment by tdsmith** [comment]
> So I should wait for Xcode 8 with this?

At least I think we won't merge it before then.

Can you help me understand what the net effect of this change is? Does this change the compiled libraries so that client code using C++14 can link against them? Is there new API vs boost compiled in C++11 mode? Can code built in C++11 mode link against a "C++14" boost? Happy to go rtfm if there's a good source!

**Comment by Marqin** [comment]
Problem is that Boost.Coroutine2 uses execution_context from Boost.Context,
which is marked as "*execution_context* requires C++14." -
http://www.boost.org/doc/libs/1_60_0/libs/context/doc/html/context/econtext.html

So if you want to use Boost.Coroutine2, you need to link with C++14
execution_context from C++14 Boost.Context

2016-07-21 14:37 GMT+02:00 Tim D. Smith <notifications@github.com>:

**Comment by tdsmith** [comment]
FWIW the 1.61.0 release notes say that it works in C++11 mode now: http://www.boost.org/users/history/version_1_61_0.html

**Comment by Marqin** [comment]
Oh, ok, so you can close this, and make issue to upgrade to 1.61

2016-07-21 19:18 GMT+02:00 Tim D. Smith <notifications@github.com>:

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/1200 then.

**Pull request closed without merging**
