### PR TITLE
qbs 1.6.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by jakepetroules** [comment]
How on earth did you get to this before me? :D Is this through some automated process?

**Comment by ilovezfs** [comment]
@jakepetroules semi-automated :)

**Comment by DomT4** [comment]
> Is this through some automated process?

ILZ is a bot 😜.

**Pull request closed without merging**
