### PR TITLE
mgba 0.8.3

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
CMake Warning at src/platform/cmake/FindFeature.cmake:16 (message):
  Requested module minizip missing for feature USE_MINIZIP.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:467 (find_feature)


-- Found SQLite3: /usr/local/opt/sqlite/include (found version "3.32.1") 
-- Checking for one of the modules 'sqlite3'
-- Checking for one of the modules 'libelf'
CMake Warning at src/platform/cmake/FindFeature.cmake:16 (message):
  Requested module libelf missing for feature USE_ELF.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:473 (find_feature)


-- Checking for one of the modules 'libavresample'
-- Checking for one of the modules 'libswresample'
CMake Error at CMakeLists.txt:617 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
```

**Comment by Bo98** [comment]
libzip contains a bug which is preventing this from building. It looks like it might be fixed in 1.7.2.

**Comment by chenrui333** [comment]
> libzip contains a bug which is preventing this from building. It looks like it might be fixed in 1.7.2.

@Bo98 is there any libzip bug issue that we can follow?

**Comment by Bo98** [comment]
Nope. Just some commits like https://github.com/nih-at/libzip/commit/3fc0ac40ecd4d8e6d6b08482919891bdde5650a3

**Comment by chenrui333** [comment]
Got you! Thanks!

**Comment by Bo98** [comment]
Try apply https://github.com/mgba-emu/mgba/commit/a921c891876e2e7895374742592a66b7e970118e

**Comment by alebcay** [comment]
Tried applying the mentioned diff and got this error on the `make install` stage:
```
undef: _zip_fread
undef: _zip_stat_index
undef: _zip_fopen
undef: _zip_stat
undef: _zip_open
undef: _zip_close
undef: _zip_fclose
undef: _zip_get_num_entries
Undefined symbols for architecture x86_64:
  "_zip_fread", referenced from:
      __vfzRead in lto.o
  "_zip_stat_index", referenced from:
      __vdezName in lto.o
  "_zip_fopen", referenced from:
      __vdzOpenFile in lto.o
  "_zip_stat", referenced from:
      __vdzOpenFile in lto.o
  "_zip_open", referenced from:
      _VDirOpenZip in lto.o
  "_zip_close", referenced from:
      __vdzClose in lto.o
  "_zip_fclose", referenced from:
      __vfzClose in lto.o
  "_zip_get_num_entries", referenced from:
      __vdzListNext in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by alebcay** [comment]
Rebuild/retry pending #57843.

**Comment by Bo98** [comment]
Try this patch too: https://github.com/mgba-emu/mgba/commit/9295c3c893646713d8fce7f9d15be320787b9d97.patch?full_index=1

**Comment by alebcay** [comment]
The second patch fails to apply, both when applied alone or when tried in succession after the first one you linked above earlier.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
