### PR TITLE
recon-ng: fix `python3` reference.

### PR DESCRIPTION
**Pull request by miles170**
See #108008.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
Can you replace:

```
# Replace shebang with virtualenv python
inreplace libexec/"recon-ng", "#!/usr/bin/env python3", "#!#{libexec}/bin/python"
```

with:
`rewrite_shebang detected_python_shebang, libexec/"recon-ng"`

You will also need to add `include Language::Python::Shebang` just below the class in the formula.

**Comment by miles170** [comment]
> Can you replace:
> 
> ```
> # Replace shebang with virtualenv python
> inreplace libexec/"recon-ng", "#!/usr/bin/env python3", "#!#{libexec}/bin/python"
> ```
> 
> with: `rewrite_shebang detected_python_shebang, libexec/"recon-ng"`
> 
> You will also need to add `include Language::Python::Shebang` just below the class in the formula.

Rewrite with `rewrite_shebang detected_python_shebang, libexec/"recon-ng"` breaks test.

**Comment by iMichka** [comment]
Ha yes, gotcha. So `virtualenv_create` will still always create a `libexec/bin/python`, even after the changes related to Python 3 paths described in https://github.com/Homebrew/homebrew-core/issues/108008?

**Review by iMichka — APPROVED** [review]

**Comment by carlocab** [comment]
> So `virtualenv_create` will still always create a `libexec/bin/python`, even after the changes related to Python 3 paths described in #108008?

Yes. `virtualenv_create("foo", "python99")` is just a wrapper around doing `python99 -m venv foo` (that plus fixing up symlinks so they use `opt` paths).

**Pull request closed without merging**
