### PR TITLE
gimme-aws-creds 2.1.3

### PR DESCRIPTION
**Pull request by chenrui333**
- bump the version

### CODE REVIEW

**Comment by SMillerDev** [comment]
That's the wrong URL.

**Comment by chenrui333** [comment]
@SMillerDev Do you prefer pypi gzip file over github archive?

**Comment by SMillerDev** [comment]
Since that is the official distribution platform, yes.

**Comment by chenrui333** [comment]
@SMillerDev Updated to native format. :)

**Pull request closed without merging**
