### PR TITLE
mockolo 1.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
**Build failure:** `error: package at '/private/tmp/mockolo-20210429-85533-1q1zih5/mockolo-1.4.0' is using Swift tools version 5.4.0 but the installed version is 5.3.0`

May need to increase XCode version to 12.5
https://swift.org/download/#releases

**Comment by chenrui333** [comment]
relates to discussions in #76206

**Comment by carlocab** [comment]
Can we confirm this dependency upstream? Their docs don't mention needing Xcode 12.5/Swift 5.4. https://github.com/uber/mockolo#system-requirements

**Comment by carlocab** [comment]
Actually, I think it's here: https://github.com/uber/mockolo/blob/e723dc2360398e402ffcb0d8ce8c988d675f6c32/Package.swift#L4-L8

Even then, upstream need to be informed that their docs are out of date.

**Comment by cho-m** [comment]
Related PR https://github.com/uber/mockolo/pull/143

**Comment by carlocab** [comment]
I've opened https://github.com/uber/mockolo/issues/147.

**Review by carlocab — APPROVED** [review]
Confirmed upstream

**Pull request closed without merging**
