### PR TITLE
pyenv-virtualenv 1.1.5

### PR DESCRIPTION
**Pull request by j9ac9k**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> eval "$(pyenv init -)" && pyenv virtualenvs
/usr/local/bin/pyenv-virtualenvs: line 10: /usr/local/bin/../libexec/pyenv-virtualenv-realpath: No such file or directory
Error: pyenv-virtualenv: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by j9ac9k** [comment]
Is there anything I can do to help address this issue?  I haven't had much experience editing formula on here, but would be happy to do some testing.

**Comment by fxcoudert** [comment]
You need to test the formula locally, and understand why the test is failing.

**Comment by lcdtyph** [comment]
@fxcoudert 
Is that ok to use inreplace here to fix the issue?
This formula use relative paths linked to `../libexec` which does not link to HOMEBREW_PREFIX.

We can replace it to absolute path.

**Comment by SMillerDev** [comment]
@lcdtyph It'd be much preferred to submit a PR to upstream to fix this issue. Fixing it in the formula is only allowed after a PR to upstream is reviewed and preferably accepted.

**Comment by j9ac9k** [comment]
Would this PR address the upstream issue?

https://github.com/pyenv/pyenv-virtualenv/pull/308

**Comment by iMichka** [comment]
As this is an upstream issue, and the proposed patch has been waiting for more than 6 months upstream, and there was no agreement to merge it, it looks like this has stalled. I will close this pull request.

A new pull request can be opened once this has been fixed by upstream. Sorry for this but we try to avoid using patches that will not be maintained by upstream when possible.

**Pull request closed without merging**
