### PR TITLE
numpy 1.25.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
pre-existing failure `bazarr` on 11 build

**Comment by chenrui333** [comment]
cc @Homebrew/core

**Comment by MikeMcQuaid** [comment]
@chenrui333 what's the question here?

**Comment by MikeMcQuaid** [comment]
@chenrui333 Gotcha. Can you add Homebrew/core as a reviewer in future? That makes the ask more obvious. ✅ incoming!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> pre-existing failure with `bazarr` on 11 build

Can this get an issue or PR opened if there isn't one already?

**Comment by chenrui333** [comment]
> > pre-existing failure with `bazarr` on 11 build
> 
> Can this get an issue or PR opened if there isn't one already?

not really, i can followup on it.

**Pull request merged**
