### PR TITLE
blazegraph 2.1.5

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
brew test failed
```
21:48:35 ==> brew test blazegraph --verbose
21:48:42 ==> FAILED
21:48:42 Testing blazegraph
21:48:42 /usr/bin/sandbox-exec -f /private/tmp/homebrew20190518-19167-1k78wbi.sb 
```

**Comment by chenrui333** [comment]
looks like even 2.1.4 does not quite work. 

Relates to PR, https://github.com/Homebrew/homebrew-core/pull/10929

**Comment by beebs-systap** [comment]
@chenrui333 It looks like there is a corrupt Git repo in [Jenkins](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/42194/console).

```
20:21:32  > git rev-parse --is-inside-work-tree # timeout=10
20:21:32 ERROR: Workspace has a .git repository, but it appears to be corrupt.
20:21:32 hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:
20:21:32 stdout: 
20:21:32 stderr: fatal: Not a git repository (or any of the parent directories): .git
20:21:32 
20:21:32 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2318)
2
```

**Comment by chenrui333** [comment]
@beebs-systap I will do a rerun.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
May be related to migration to OpenJDK?

```
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
INFO: com.bigdata.util.config.LogUtil: Configure: jar:file:/usr/local/Cellar/blazegraph/2.1.4/libexec/blazegraph.jar!/log4j.properties

BlazeGraph(TM) Graph Engine

                   Flexible
                   Reliable
                  Affordable
      Web-Scale Computing for the Enterprise

Copyright SYSTAP, LLC DBA Blazegraph 2006-2016.  All rights reserved.

10.88.172.144
Sun May 19 19:49:30 BST 2019
Mac OS X/10.12.6 x86_64
Mac OS X 10.12.6 x86_64 #CPU=4
AdoptOpenJDK 12.0.1
freeMemory=122099736
buildVersion=2.1.4
gitCommit=738d05f08cffd319233a4bfbb0ec2a858e260f9c

Dependency         License                                                                 
ICU                http://source.icu-project.org/repos/icu/icu/trunk/license.html          
bigdata-ganglia    http://www.apache.org/licenses/LICENSE-2.0.html                         
blueprints-core    https://github.com/tinkerpop/blueprints/blob/master/LICENSE.txt         
colt               http://acs.lbl.gov/software/colt/license.html                           
commons-codec      http://www.apache.org/licenses/LICENSE-2.0.html                         
commons-fileupload http://www.apache.org/licenses/LICENSE-2.0.html                         
commons-io         http://www.apache.org/licenses/LICENSE-2.0.html                         
commons-logging    http://www.apache.org/licenses/LICENSE-2.0.html                         
dsiutils           http://www.gnu.org/licenses/lgpl-2.1.html                               
fastutil           http://www.apache.org/licenses/LICENSE-2.0.html                         
flot               http://www.opensource.org/licenses/mit-license.php                      
high-scale-lib     http://creativecommons.org/licenses/publicdomain                        
httpclient         http://www.apache.org/licenses/LICENSE-2.0.html                         
httpclient-cache   http://www.apache.org/licenses/LICENSE-2.0.html                         
httpcore           http://www.apache.org/licenses/LICENSE-2.0.html                         
httpmime           http://www.apache.org/licenses/LICENSE-2.0.html                         
jackson-core       http://www.apache.org/licenses/LICENSE-2.0.html                         
jetty              http://www.apache.org/licenses/LICENSE-2.0.html                         
jquery             https://github.com/jquery/jquery/blob/master/MIT-LICENSE.txt            
jsonld             https://raw.githubusercontent.com/jsonld-java/jsonld-java/master/LICENCE
log4j              http://www.apache.org/licenses/LICENSE-2.0.html                         
lucene             http://www.apache.org/licenses/LICENSE-2.0.html                         
nanohttp           http://elonen.iki.fi/code/nanohttpd/#license                            
rexster-core       https://github.com/tinkerpop/rexster/blob/master/LICENSE.txt            
river              http://www.apache.org/licenses/LICENSE-2.0.html                         
semargl            https://github.com/levkhomich/semargl/blob/master/LICENSE               
servlet-api        http://www.apache.org/licenses/LICENSE-2.0.html                         
sesame             http://www.openrdf.org/download.jsp                                     
slf4j              http://www.slf4j.org/license.html                                       
zookeeper          http://www.apache.org/licenses/LICENSE-2.0.html                         

ERROR: Banner.java:160: Uncaught exception in thread
java.lang.NullPointerException
	at com.bigdata.rdf.sail.webapp.StandaloneNanoSparqlServer.main(StandaloneNanoSparqlServer.java:142)
Error: blazegraph: failed
```

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
#50936

**Pull request closed without merging**
