### PR TITLE
glslang 7.13.3496

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
00:01:59 cp -pR /private/tmp/d20191103-55271-1g34h78/glslang-7.13.3496/. /private/tmp/glslang-20191103-55271-1pq0b1f/glslang-7.13.3496
00:01:59 chmod -Rf +w /private/tmp/d20191103-55271-1g34h78
00:01:59 ==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/glslang/7.13.3496 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
00:01:59 -- The C compiler identification is AppleClang 11.0.0.11000033
00:01:59 -- The CXX compiler identification is AppleClang 11.0.0.11000033
00:01:59 -- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang
00:01:59 -- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -- works
00:01:59 -- Detecting C compiler ABI info
00:01:59 -- Detecting C compiler ABI info - done
00:01:59 -- Detecting C compile features
00:01:59 -- Detecting C compile features - done
00:01:59 -- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
00:01:59 -- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -- works
00:01:59 -- Detecting CXX compiler ABI info
00:01:59 -- Detecting CXX compiler ABI info - done
00:01:59 -- Detecting CXX compile features
00:01:59 -- Detecting CXX compile features - done
00:01:59 CMake Error at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
00:01:59   Could NOT find PythonInterp: Found unsuitable version "2.7.10", but
00:01:59   required is at least "3" (found /usr/bin/python)
00:01:59 Call Stack (most recent call first):
00:01:59   /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
00:01:59   /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindPythonInterp.cmake:160 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
00:01:59   CMakeLists.txt:160 (find_package)
00:01:59 
00:01:59 
00:01:59 -- Configuring incomplete, errors occurred!
00:01:59 See also "/tmp/glslang-20191103-55271-1pq0b1f/glslang-7.13.3496/CMakeFiles/CMakeOutput.log".
00:01:59

**Comment by chenrui333** [comment]
@igas I think it might work now. 

I just rebuild and tested on my catalina machine.

**Comment by chenrui333** [comment]
Reopen and give it a try.

**Comment by igas** [comment]
@chenrui333 I think I tried adding `python` as a dep before... Wanna try again? To bump to 3.

**Comment by chenrui333** [comment]
🎉 it is green now.

**Comment by chenrui333** [comment]
cc @Bo98 @bayandin

**Comment by Bo98** [comment]
Should be good to merge. :+1:

This won't even require a revision bump for 3.8 - looks to just be a couple of Python scripts in the build process.

**Comment by chenrui333** [comment]
Sounds good, thanks for confirming it. :)

**Pull request closed without merging**
