### PR TITLE
miller 5.6.2

### PR DESCRIPTION
**Pull request by johnkerl**
- [Y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [Y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [Y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [Y] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [Y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
On macOS Mojave with Xcode 11, we get a build failure:

```
clang: error: the clang compiler does not support -pg option on versions of OS X 10.9 and later
```

Can you report this upstream?

**Comment by johnkerl** [comment]
Happy to, although it's a separate question why we're even attempting a profiler build on a standard release build ... this should be getting invoked only for manual analysis.

**Comment by fxcoudert** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
