### PR TITLE
mmix: update to use archive.org urls

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

```
$ curl mmix.cs.hm.edu
curl: (6) Could not resolve host: mmix.cs.hm.edu
```

### CODE REVIEW

**Comment by dawidd6** [comment]
Is this project maintained elsewhere now or should we deprecate it?

**Comment by chenrui333** [comment]
I dont think it is maintained anywhere, but since the artifact can still be built, I would say we can keep it?

**Comment by SMillerDev** [comment]
We can do both, deprecation does not equate removal

**Comment by nandahkrishna** [comment]
The homepage (https://mmix.cs.hm.edu/) is back up.

**Comment by chenrui333** [comment]
looks like it is down again, 
```
$ curl mmix.cs.hm.edu
curl: (6) Could not resolve host: mmix.cs.hm.edu
```

**Comment by nandahkrishna** [comment]
Weird, I'm still able to access it:
```
➜ curl -I mmix.cs.hm.edu
HTTP/1.1 200 OK
Date: Sat, 21 Aug 2021 18:04:54 GMT
Server: Apache/2.4.38 (Debian)
Last-Modified: Wed, 04 Aug 2021 18:08:19 GMT
Accept-Ranges: none
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-UA-Compatible: IE=edge
Content-Length: 13514
Content-Type: text/html
```

**Comment by chenrui333** [comment]
that is indeed weird.

**Comment by chenrui333** [comment]
yeah, I can access over my phone. :(

Any way gonna close this PR now, as it does not seem like an issue 😓

**Pull request closed without merging**
