### PR TITLE
ffmpeg: enable libdav1d

### PR DESCRIPTION
**Pull request by rcombs**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This improves performance when decoding AV1 video.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you squash the commits?

**Comment by rcombs** [comment]
Done.

**Review by SMillerDev — DISMISSED** [review]

**Comment by bayandin** [comment]
A for `ffmpeg` was bumped also in https://github.com/Homebrew/homebrew-core/pull/54297 (and it was merged already).
Could you please rebase master again and bump revision to 5, thanks @rcombs!

**Comment by rcombs** [comment]
Done.

**Comment by rcombs** [comment]
(Whoops! Sorry about the accidental close.)

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
