### PR TITLE
sbt 1.3.4

### PR DESCRIPTION
**Pull request by eed3si9n**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like the test might need tweaking:

```
==> /usr/local/Cellar/sbt/1.3.4/bin/sbt sbtVersion
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Dsbt.log.noformat=true
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Dsbt.log.noformat=true
Error: sbt: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </\[info\]\ 1\.3\.4/> was expected to be =~
<"Copying runtime jar.\n">.
```

**Comment by eed3si9n** [comment]
@Bo98 Earlier version of `tgz` file had problem, but I fixed it before sending this PR.

The test ran fine on my local machine, and it still does now:

```
$ brew uninstall --force sbt
Uninstalling sbt... (777 files, 55.1MB)
$ brew install --build-from-source sbt
==> Downloading https://github.com/sbt/sbt/releases/download/v1.3.4/sbt-1.3.4.tgz
Already downloaded: /Users/eed3si9n/Library/Caches/Homebrew/downloads/3e45e1a8c7c82f37747bd8466da930d402d725fb22237665d9dd50838c219c7a--sbt-1.3.4.tgz
==> Caveats
You can use $SBT_OPTS to pass additional JVM options to sbt.
Project specific options should be placed in .sbtopts in the root of your project.
Global settings should be placed in /usr/local/etc/sbtopts
==> Summary
🍺  /usr/local/Cellar/sbt/1.3.4: 777 files, 55.1MB, built in 4 seconds
$ brew test sbt
Testing sbt
==> /usr/local/Cellar/sbt/1.3.4/bin/sbt sbtVersion
Picked up _JAVA_OPTIONS: -Duser.home=/Users/eed3si9n/Library/Caches/Homebrew/java_cache -Dsbt.log.noformat=true
```

**Comment by eed3si9n** [comment]
Actually `"Copying runtime jar.\n"` sounds like it's running on something other than JDK 8. Was the testing infrastructure updated recently?

**Comment by Bo98** [comment]
The formula contains `depends_on :java => "1.8+"` so it could use any Java from Java 8 upwards. I imagine the default is something newer than Java 8 (I'll need to check how exactly it behaves), though Java 8 can still be used if it's a requirement.

**Comment by eed3si9n** [comment]
sbt in general functions fine on JDK 11 but it's outputting extra stuff on the log the first time it runs, so I added `sbt about` to get it out of the system.

**Comment by Bo98** [comment]
Thanks!

**Pull request merged**
