### PR TITLE
buku: use PyPI url

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @samford

**Comment by dtrodrigues** [comment]
I can't replicate the test failure locally (running 10.15).

**Comment by samford** [comment]
> I can't replicate the test failure locally (running 10.15).

It works fine for me locally on macOS 11.0.1 (Intel), too. I started another run to see if it was just an intermittent issue on CI.

**Review by samford — APPROVED** [review]
GitHub decided it wanted to delete my previous comment when I updated it, so I'll just reiterate here that this built/installed/tested fine for me locally on macOS Big Sur (11.0.1), too.

The changes here look good to me, so I'm going to go ahead and approve this now that it's passing on CI.

**Pull request closed without merging**
