### PR TITLE
dvc 2.55.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error in kombu setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
      pytz>dev
          ^
  error: subprocess-exited-with-error
```

**Comment by efiop** [comment]
Related https://github.com/celery/kombu/pull/1652#issuecomment-1442300039

Suggested solution for now is to downgrade setuptools below 67 https://github.com/celery/kombu/issues/1677#issuecomment-1488801850

**Comment by efiop** [comment]
Ok, seeing similar hacks elsewhere: https://github.com/Homebrew/homebrew-core/pull/128147/files#diff-8ccf7ec7d2ddeaacc6c51b2dddf17877fbfff2ef8b9b16904b24f8eafee2559eR74 So I suppose we can temporarily put setuptools <67 in here as a resource while waiting for a new kombu release.

kombu has some new pre-releases out with that fixed, but I don't feel comfortable relying on it for now. So `setuptools` resources hack seems preferable.

**Comment by chenrui333** [comment]
> Ok, seeing similar hacks elsewhere: https://github.com/Homebrew/homebrew-core/pull/128147/files#diff-8ccf7ec7d2ddeaacc6c51b2dddf17877fbfff2ef8b9b16904b24f8eafee2559eR74 So I suppose we can temporarily put setuptools <67 in here as a resource while waiting for a new kombu release.
> 
> kombu has some new pre-releases out with that fixed, but I don't feel comfortable relying on it for now. So `setuptools` resources hack seems preferable.

yeah, that setuptools hack did not work as it caused version conflict issue.

**Comment by efiop** [comment]
@chenrui333 Hm, could you share which package it had a conflict with?

**Comment by chenrui333** [comment]
oh I was mostly referring to the patch that used by the other formula. I can give this approach a shot and see.

**Comment by efiop** [comment]
@chenrui333 Let me know if you would rather have me create an alternative PR.

**Comment by pmrowla** [comment]
dvc-task & dvc work with the kombu 5.3 beta, so using the source tarball for 5.3.0b3 would also fix this issue (https://pypi.org/project/kombu/5.3.0b3/#files)

(not sure what homebrew's policy is on using pre-release packages)

**Comment by chenrui333** [comment]
Since this is just resource (not formula), it is fine, let me update the formula to use the latest release 2.55.0

**Review by SMillerDev — APPROVED** [review]

**Comment by efiop** [comment]
Thank you, @chenrui333 ! 🙏

**Pull request merged**
