### PR TITLE
cabal-install 3.10.2.1

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Haven't had chance to check, but I think many errors are probably because we didn't test them in GHC 9.8 release. I have another PR to work on these.

**Comment by cho-m** [comment]
Following dependents are failing on GHC 9.8 (see #154540)
- `dhall-bash`
- `dhall-json`
- `git-annex`
- `hlint`
- `pandoc`
- `pandoc-crossref`
- `stylish-haskell`
- `taskell`

---

New failures are:
- `fourmolu`
- `ghcup`
- `haskell-language-server`
- `ormolu`
- `texmath`

**Comment by cho-m** [comment]
`ghcup` is only failure that remains after PRs and upstream fixes. I am checking with Cabal upstream on what is way to handle `c-sources` changes for Objective-C files as that is causing failure when compiling streamly https://github.com/composewell/streamly/blob/master/streamly.cabal#L459

**Review by iMichka — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by iMichka** [comment]
Same issue with `git-annex`:

```
 Failed to build hfsevents-0.1.6.
  Build log (
  /private/tmp/git-annex-20240106-81217-knz79z/git-annex-10.20231227/.brew_home/.cache/cabal/logs/ghc-9.6.3/hfsvnts-0.1.6-a910fc59.log
  ):
  Configuring library for hfsevents-0.1.6..
  clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/opt/homebrew/opt/ghc@9.6/lib' [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
  Preprocessing library for hfsevents-0.1.6..
  Building library for hfsevents-0.1.6..
  [1 of 1] Compiling System.OSX.FSEvents ( System/OSX/FSEvents.hs, dist/build/System/OSX/FSEvents.o, dist/build/System/OSX/FSEvents.dyn_o )
  ar: dist/build/cbits/c_fsevents.o: No such file or directory
  Error: cabal: Failed to build hfsevents-0.1.6 (which is required by
  git-annex-10.20231227). See the build log above for details.
```

**Comment by cho-m** [comment]
Let me try a different workaround in `cabal-install`.

**Comment by cho-m** [comment]
Should be good now. Remaining failure is unrelated test bot issue where it incorrectly tries to source build some dependencies.

**Review by branchv — APPROVED** [review]

**Pull request merged**
