### PR TITLE
nng 1.1.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
```
FAILED: docs/man/nng_dialer_setopt.3.html 
cd /tmp/nng-20181127-89583-gowuu4/nng-1.1.1/build/docs/man && /usr/local/bin/asciidoctor -a nofooter -atoc=left -aicons=font -d manpage -b html5 -o nng_dialer_setopt.3.html /tmp/nng-20181127-89583-gowuu4/nng-1.1.1/docs/man/nng_dialer_setopt.3.adoc
/usr/local/bin/asciidoctor: /usr/local/Cellar/asciidoctor/1.5.8/libexec/bin/asciidoctor: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/asciidoctor: line 2: /usr/local/Cellar/asciidoctor/1.5.8/libexec/bin/asciidoctor: Undefined error: 0
[247/782] Linking C executable perf/inproc_thr
[248/782] Building C object perf/CMakeFiles/inproc_lat.dir/perf.c.o
[249/782] Building C object perf/CMakeFiles/local_thr.dir/perf.c.o
[250/782] Building C object perf/CMakeFiles/local_lat.dir/perf.c.o
[251/782] Building C object tools/nngcat/CMakeFiles/nngcat.dir/nngcat.c.o
ninja: build stopped: subcommand failed.
```

**Comment by fxcoudert** [comment]
I've pulled new bottles for `asciidoctor`, it should fix the issue: https://github.com/Homebrew/homebrew-core/commit/14d03f35f2b54e1e3e367589681f36b6ff1283f2

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
It helped. Thank you @fxcoudert

**Pull request closed without merging**
