### PR TITLE
rust-analyzer 2022-06-20

### PR DESCRIPTION
**Pull request by peeweep**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by peeweep** [comment]
crates/proc-macro-srv cause build fail, I think this bug should report to upstream.

**Comment by inc-osaulenko** [comment]
This issue appears to be already fixed. https://github.com/rust-lang/rust-analyzer/pull/12492

**Comment by peeweep** [comment]
> This issue appears to be already fixed. [rust-lang/rust-analyzer#12492](https://github.com/rust-lang/rust-analyzer/pull/12492)

In fact, it was this commit that introduced the problem.

**Comment by icewind** [comment]
There is a new version available. Maybe we can skip this one and update it to 2022-06-20?

**Comment by peeweep** [comment]
Thanks for the follow-up! I will try to remove the patch to see if it can compile.

**Review by iMichka — APPROVED** [review]
Thanks!

**Pull request closed without merging**
