### PR TITLE
joplin 1.0.165

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```
==> brew test --verbose joplin
==> FAILED
Testing joplin
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200710-5311-5poi9e.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/joplin.rb --verbose
==> /usr/local/Cellar/joplin/1.0.165/bin/joplin config editor subl
Killing child processes...
Error: joplin: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

**Comment by SeekingMeaning** [comment]
I get this prompt when I run `brew test` locally:

```
% brew test joplin
Testing joplin
==> /usr/local/Cellar/joplin/1.0.165/bin/joplin config editor subl
```

Screen Shot

And then when I click Cancel:

```
% brew test joplin
Testing joplin
==> /usr/local/Cellar/joplin/1.0.165/bin/joplin config editor subl
Last 15 lines from ~/Library/Logs/Homebrew/joplin/test.01.joplin:
2020-07-10 17:56:51 -0700

/usr/local/Cellar/joplin/1.0.165/bin/joplin
config
editor
subl

Fatal error:
[Error: The authorization was canceled by the user.]
Error: joplin: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/joplin/1.0.165/bin/joplin config editor subl
```

**Comment by chenrui333** [comment]
sounds like we should either update the test, or ask the upstream to fix this (if it is indeed an issue) to ship out an update.

**Comment by SeekingMeaning** [comment]
Apparently opening an issue is not an option:

> Unsupported methods
>
> There are other ways to install the terminal application. However, they are not supported and problems must be reported to the upstream projects.
>
> `brew install joplin`
> 
> &mdash; https://www.npmjs.com/package/joplin

**Pull request closed without merging**
