### PR TITLE
Azure CLI 2.0.74

### PR DESCRIPTION
**Pull request by azclibot**
The latest release of the Azure CLI

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
please do not merge this PR. need to fix the PR for 2.0.73 first.

**Comment by fxcoudert** [comment]
Why shouldn't we skip directly to the latest version?

**Comment by fxcoudert** [comment]
> please release 2.0.74

I do not understand. You first asked us not to ship this, and now want the opposite, but without giving us a reason in any case.

> can you help fix the `depends_on "openssl@1.1"`

All Homebrew formulas that support OpenSSL 1.1 were migrated to that version. Again, please explain why you would want to go back to the previous OpenSSL version (which will reach EOL on 2019-12-31).

**Comment by fengzhou-msft** [comment]
@fxcoudert I followed your advice from the comment [here](https://github.com/Homebrew/homebrew-core/pull/44532#issuecomment-534554656). So please skip 2.0.73 and release 2.0.74 directly.

For the OpenSSL, I mean fix it by adding `@1.1`. Our formula is generated through a template, and it is still `depends_on "openssl"`, which should be `depends_on "openssl@1.1"`. I will change it in our template so next time it will be correct. As for this auto generated PR,I do not have permission to modify the code . If you can edit the file, please make it `depends_on "openssl@1.1"`.

**Pull request closed without merging**
