### PR TITLE
workflows/tests: set test-bot arguments.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Follow-up to https://github.com/Homebrew/homebrew-core/pull/76761

This allows passing `--fail-fast` or `--skip-recursive-dependents` to `brew test-bot` using labels.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
CI is green, but the Actions UI shows this error:

>GitHub Actions CI : .github#L1
>```
>Error when evaluating 'strategy' for job 'tests'. (Line: 127, Col: 18): Unexpected value 'true'
>```

**Comment by MikeMcQuaid** [comment]
Reapplying https://github.com/Homebrew/homebrew-core/pull/76761 in this PR: sadly it looks like we cannot set timeout or matrix fail fast through labels (as they don't accept strings as input). CC @rylan12 and @dawidd6 as some actions people in case you have any thoughts of workarounds.

**Comment by carlocab** [comment]
We have other workflows that seem to be able to take arbitrary inputs. Would it work if the actual tests were run as a separate workflow file that took the timeout and whether to fail fast as an input?

And I suppose the tap syntax test would need to call that other workflow somehow, but I think @iMichka has workflows that do something similar.

**Comment by MikeMcQuaid** [comment]
> We have other workflows that seem to be able to take arbitrary inputs. Would it work if the actual tests were run as a separate workflow file that took the timeout and whether to fail fast as an input?

I think the issue is that arbitrary inputs are always strings and the YAML linter for these needs them to be integers or booleans accordingly. It may be possible do cast to a boolean with `== "somestring"` but no idea if it's possible/how to do this for an integer.

**Comment by Rylan12** [comment]
I think we could make the initial `tap_syntax` job output one JSON string (that would contain booleans/integers/strings as needed). Then, in the other jobs, use [`fromJSON`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) in the `${{ }}` expression. I haven't tried this but I assume it gets around the mismatched types issue.

**Comment by carlocab** [comment]
Ah, I think we can also define a `matrix` of timeouts, but exclude one timeout or other depending on the output of checking for the timeout label.

**Comment by MikeMcQuaid** [comment]
> I think we could make the initial `tap_syntax` job output one JSON string (that would contain booleans/integers/strings as needed). Then, in the other jobs, use [`fromJSON`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) in the `${{ }}` expression. I haven't tried this but I assume it gets around the mismatched types issue.

That's a good idea, I'll try it out.

**Comment by dawidd6** [comment]
Relevant docs example: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-returning-a-json-data-type

**Comment by Rylan12** [comment]
Slightly off-topic but might be worth mentioning: In https://github.com/Homebrew/homebrew-core/pull/76761#pullrequestreview-660252873, I commented this:

> I think the major thing that is lacking in this label setup is that all the labels need to be present at the start of the run. I don't think there's much that we can do here, but I've definitely been in situations where I realized "oh I wanted to put CI-syntax-only on this PR" after the checks have started and when it's too late. I can definitely see the same thing being desired here (e.g. adding CI-long-timeout after the run has already started but before the short timeout is reached). Again, these may not be solvable in a simple enough way that makes it worthwhile but I figured I'd mention it as a drawback to the labeling system.

I've since noticed that we have something that's similar working in the cask repos using [`reitermarkus/rerun-workflow`](https://github.com/reitermarkus/rerun-workflow) with the [`rerun-workflow.yml`](https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/rerun-workflow.yml) job. This runs when any of the `ci-*` labels are added to a PR and it causes CI to be automatically rerun. I wonder if this would be useful if adapted to homebrew/core as well (e.g. maybe adding one of these labels causes the current run to be cancelled and restarted with the new labels)

**Comment by MikeMcQuaid** [comment]
> I've since noticed that we have something that's similar working in the cask repos using [`reitermarkus/rerun-workflow`](https://github.com/reitermarkus/rerun-workflow) with the [`rerun-workflow.yml`](https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/rerun-workflow.yml) job. This runs when any of the `ci-*` labels are added to a PR and it causes CI to be automatically rerun. I wonder if this would be useful if adapted to homebrew/core as well (e.g. maybe adding one of these labels causes the current run to be cancelled and restarted with the new labels)

Something like this sounds good.

I'd really like to get any workflows that we depend on like this to be pulled into Homebrew/actions, though. Ideally we'd rely entirely on Homebrew/* or github/* actions for security reasons.

**Comment by MikeMcQuaid** [comment]
Merged, this is working as expected. I think the next steps will be adding more functionality to `brew test-bot` that's exposed via command-line options.




> I think we could make the initial `tap_syntax` job output one JSON string (that would contain booleans/integers/strings as needed). Then, in the other jobs, use [`fromJSON`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) in the `${{ }}` expression. I haven't tried this but I assume it gets around the mismatched types issue.

@rylan12 @dawidd6 I didn't pick this up to handle timeouts or fail-fast but if either of you were willing and/or able: I think it would be a great thing to explore.

**Pull request merged**
