### PR TITLE
openmotif: patch incorrect -flat_namespace usage

### PR DESCRIPTION
**Pull request by carlocab**
This is needed for bottling on Monterey.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> FAILED
openmotif:
  * 'revision 1' should be removed
Error: 1 problem in 1 formula detected
```

**Comment by Bo98** [comment]
Audit failure is because the previous version (2.3.8 revision 0) is old enough that it cannot be read by modern `brew` (bottle block changes). The previous readable veresion is 2.3.6 revision 1 (initial version - no bottle block) so it's seen as an update from 2.3.6_1 to 2.3.8_1.

This is not a trivial fix so I'm fine with this being merged when CI is done.

**Comment by carlocab** [comment]
CI did complete just fine. I had just completely forgotten I had this PR open already and force-pushed to a branch named `openmotif-libtool` to fix https://github.com/Homebrew/homebrew-core/issues/87708#issuecomment-979346524. But we can wait for CI to finish again.

You should approve this PR though so I can merge it

**Review by Bo98 — APPROVED** [review]
Ah yes, oops

**Pull request merged**
