### PR TITLE
7-zip 21.06 (new formula)

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
We already ship `p7zip`

**Comment by paperchalice** [comment]
This is the [official port](https://sourceforge.net/p/sevenzip/discussion/45797/thread/cec5e63147/), `p7zip` is a fork based on an old version.

**Review by carlocab — COMMENTED** [review]
I'm fine with the formula, but we don't want to carry a patch. Can you submit your patch upstream in a form they can merge it? You can probably just gate the lines you removed behind a `WITHOUT_RAR` variable, or something like that.

**Comment by icpz** [comment]
Hi, could you please check my patch (https://github.com/icpz/homebrew-collection/blob/master/Formula/sevenzip.rb) ? I've tested for 21.02a (https://github.com/Homebrew/homebrew-core/pull/76860).

**Pull request closed without merging**
