### PR TITLE
go 1.15.3

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by roopakv** [comment]
@Bo98 could we re-run the tests please

**Comment by SMillerDev** [comment]
I'm not sure why you tagged Bo for that, it's easier to just tag `Homebrew/maintainers`. I restarted them.

**Comment by roopakv** [comment]
@SMillerDev thank you, did not know the team. tagged Bo because I remember he helped with this once in the past. Will keep this in mind for the future

**Comment by moonfruit** [comment]
@SMillerDev Don't know why the tests fail.
It seems that all 3 tests on different versions macOS did not execute the `Run brew test-bot --only-formulae`.

**Comment by chenrui333** [comment]
```
brew install --build-from-source charm
brew install --build-from-source kamel
brew install --build-from-source mmctl
brew install --build-from-source tfsec
```

tfsec and mmctl are sha issue, kamel and charm are build issues.

**Comment by chenrui333** [comment]
Will follow up separately.

**Pull request closed without merging**
