### PR TITLE
emacs 25.2-rc1 (devel)

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Look at that beautiful https URL

**Comment by zmwangx** [comment]
For those interested, here's `NEWS` for 25.2:

```
* Changes in Emacs 25.2
This is a bug-fix release with (almost) no new features.

---
** 'find-library', 'help-function-def' and 'help-variable-def' now run
'find-function-after-hook'.

+++
** New basic face 'fixed-pitch-serif', for a fixed-width font with serifs.
The 'Info-quoted' and 'tex-verbatim' faces now default to inheriting
from it.

---
** New variable 'use-default-font-for-symbols' for backward compatibility.
This variable allows to get back pre-Emacs 25 behavior whereby the
font for displaying symbol and punctuation characters was always
selected according to your fontset setup.  Emacs 25 by default tries
to use the default face's font for such characters, disregarding the
fontsets if the default font supports these characters.  Set this
variable to nil to disable the new behavior and get back the old
behavior.

+++
** 'electric-quote-mode' is no longer suppressed in a buffer whose
whose coding system cannot represent curved quote characters.
Instead, users can deal with the unrepresentable characters in the
usual way when they save the buffer.

---
** New variable 'inhibit-compacting-font-caches'.
Set this variable to a non-nil value to speed up display of characters
using large fonts, at the price of a larger memory footprint of the
Emacs session.

+++
** The version number of CC Mode has been changed from 5.33 to
5.32.99, although the software itself hasn't changed.  This aims to
reduce confusion with the standalone CC Mode 5.33 (available from
http://cc-mode.sourceforge.net), which is a more mature version than
the one in Emacs 25.2.
```

**Comment by zmwangx** [comment]
@ilovezfs A quote from someone I know:

> people don't seem to understand that if the checksum matches, it can come from warez4u.ru for all I care.

**Comment by ilovezfs** [comment]
Exactly.

**Comment by dunn** [comment]
🎊

**Pull request closed without merging**
