### PR TITLE
orc-tools 1.6.8

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /opt/homebrew/Cellar/orc-tools/1.6.8/bin/orc-tools meta -h
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:328)
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:341)
	at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:423)
	at org.apache.orc.tools.Driver.main(Driver.java:100)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Preconditions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 4 more
```

**Comment by chenrui333** [comment]
relates to https://github.com/apache/orc/pull/507

**Comment by chenrui333** [comment]
looks like guava dependency is not part of uber jar.
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @chenrui333 . Yes, it landed after the release unfortunately. It will be a part of next release.
- https://github.com/apache/orc/commit/5ed1a732826affdfb64a7ea8fd36cacf70e231eb

**Comment by chenrui333** [comment]
Sounds good, let's wait for the next release then. :)

**Pull request closed without merging**
