### PR TITLE
openimageio: fix ARM build

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Trying #70469 again.

### CODE REVIEW

**Comment by carlocab** [comment]
Nope, still doesn't work.

**Comment by cho-m** [comment]
Just noting that although I see the same failure on latest 2.2.15.0 for Homebrew's test JPEG, I am able to run `oiiotool` on a locally generated JPEG:
```
❯ file /opt/homebrew/Library/Homebrew/test/support/fixtures/test.jpg
/opt/homebrew/Library/Homebrew/test/support/fixtures/test.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 1x1, components 3

❯ oiiotool --info /opt/homebrew/Library/Homebrew/test/support/fixtures/test.jpg
oiiotool ERROR: read : "/opt/homebrew/Library/Homebrew/test/support/fixtures/test.jpg": unknown error
Full command line was:
> oiiotool --info /opt/homebrew/Library/Homebrew/test/support/fixtures/test.jpg
```

```
❯ convert -size 1x1 -density 72 xc:orange test.jpg

❯ file test.jpg
test.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, baseline, precision 8, 1x1, components 3

❯ oiiotool --info test.jpg
test.jpg             :    1 x    1, 3 channel, uint8 jpeg
```

**Comment by carlocab** [comment]
Weird. Let's try this again.

**Comment by cho-m** [comment]
It is probably still going to fail, but it seems to be something wrong with file path logic.

The basic parts of tool seems to work.
I will probably need to debug a little more to find out what is happening.

**Comment by cho-m** [comment]
Still failed. I think it is related to the pathname of file.

For some reason, the logic to deal with more than one folder in path is not working on ARM.

If I have time, I'll take another look. It is likely something that needs to be fixed upstream.

**Comment by cho-m** [comment]
New datapoint. Rather than directories, it is failing on length of input.
22 characters work. 23 characters fail:
```console
❯ oiiotool --info test12345678901234.jpg
test12345678901234.jpg :    1 x    1, 3 channel, uint8 jpeg

❯ oiiotool --info test123456789012345.jpg
oiiotool ERROR: read : "test123456789012345.jpg": unknown error
Full command line was:
> oiiotool --info test123456789012345.jpg

❯ oiiotool --info test12345678901234.jpeg
oiiotool ERROR: read : "test12345678901234.jpeg": unknown error
Full command line was:
> oiiotool --info test12345678901234.jpeg
```

**Comment by carlocab** [comment]
Intriguing. Can you get LLDB to give you a backtrace of the failure when the input is too long? Might not be too useful since we build without debug symbols though...

**Comment by cho-m** [comment]
I rebuilt with Debug build type and tried running commands again:
```console
❯ /opt/homebrew/bin/oiiotool --info test12345678901234.jpg
test12345678901234.jpg :    1 x    1, 3 channel, uint8 jpeg

❯ /opt/homebrew/bin/oiiotool --info test123456789012345.jpg
/tmp/openimageio-20210603-27391-guutbe/oiio-Release-2.2.15.0/src/libutil/ustring.cpp:396: TableRep: Assertion 'str.c_str() == c_str() && str.size() == length' failed.
 0# OpenImageIO_v2_2::Sysutil::stacktrace() in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
 1# OpenImageIO_v2_2::stacktrace_signal_handler(int) in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
 2# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 3# pthread_kill in /usr/lib/system/libsystem_pthread.dylib
 4# abort in /usr/lib/system/libsystem_c.dylib
 5# OpenImageIO_v2_2::ustring::TableRep::TableRep(OpenImageIO_v2_2::string_view, unsigned long) in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
 6# OpenImageIO_v2_2::TableRepMap<256u, 4096u>::insert(OpenImageIO_v2_2::string_view, unsigned long) in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
 7# OpenImageIO_v2_2::ustring::make_unique(OpenImageIO_v2_2::string_view) in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
 8# input_file(int, char const**) in /opt/homebrew/bin/oiiotool
 9# std::__1::function<void (OpenImageIO_v2_2::ArgParse::Arg&, OpenImageIO_v2_2::span<char const* const, -1l>)>::operator()(OpenImageIO_v2_2::ArgParse::Arg&, OpenImageIO_v2_2::span<char const* const, -1l>) const in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
10# OpenImageIO_v2_2::ArgParse::Impl::parse_args(int, char const**) in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
11# OpenImageIO_v2_2::ArgParse::parse_args(int, char const**) in /opt/homebrew/Cellar/openimageio/2.2.15.0/lib/libOpenImageIO.2.2.15.dylib
12# getargs(int, char**) in /opt/homebrew/bin/oiiotool
13# main in /opt/homebrew/bin/oiiotool
zsh: abort      /opt/homebrew/bin/oiiotool --info test123456789012345.jpg
```

**Comment by cho-m** [comment]
@carlocab So with workaround to disable problematic code, we can deal with current failure and restore original testcase.

However, from local test, I see that the Python test hits an RPATH issue:
```make
==> /opt/homebrew/opt/python@3.9/bin/python3
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/OpenImageIO.cpython-39-darwin.so, 2): Library not loaded: @rpath/libOpenImageIO.2.2.dylib
  Referenced from: /opt/homebrew/lib/python3.9/site-packages/OpenImageIO.cpython-39-darwin.so
  Reason: image not found
Error: openimageio: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 1
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:183:in `assert'
```

**Comment by carlocab** [comment]
Should be fixable. Just `s/rpath/opt_lib`. Will think about whether there's a better fix.

**Comment by carlocab** [comment]
Superseded by #78675.

**Pull request closed without merging**
