### PR TITLE
rgbds 0.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
...
  clang: error: unsupported argument 'auto' to option 'flto='
  clang: error: unsupported argument 'auto' to option 'flto='
  clang: error: unsupported argument 'auto' to option 'flto='
  clang: error: unsupported argument 'auto' to option 'flto='
```

**Comment by ISSOtm** [comment]
I would also suggest:
```diff
   resource "rgbobj" do
-    url "https://github.com/gbdev/rgbobj/archive/refs/tags/v0.1.0.tar.gz"
-    sha256 "359a3504dc5a5f7812dfee602a23aec80163d1d9ec13f713645b5495aeef2a9b"
-
-    # Fix support for clap 3.2+. Remove in the next release.
-    # Issue ref: https://github.com/gbdev/rgbobj/issues/4
-    patch do
-      url "https://github.com/gbdev/rgbobj/commit/b4e1fe42dbc297d67d67ed17004a3f6956de199f.patch?full_index=1"
-      sha256 "27aceed0020c7561e8259308df0868d19e0b7f21ad5e0f2a389d591e8b60027d"
-    end
+    url "https://github.com/gbdev/rgbobj/archive/refs/tags/v0.2.0.tar.gz"
+    sha256 "9ddb14fab5ba7af170b061c2e771426fac9d3d0a39c4109b522abbc2c3b839aa"
   end
```

**Comment by ISSOtm** [comment]
The `-flto=auto` change seems to have been a bit premature on our side :/

It should be sufficient to `make C{,XX}FLAGS='-O3 -flto=thin -DNDEBUG'` on Big Sur.

**Comment by chenrui333** [comment]
> I would also suggest:
> 
> ```diff
>    resource "rgbobj" do
> -    url "https://github.com/gbdev/rgbobj/archive/refs/tags/v0.1.0.tar.gz"
> -    sha256 "359a3504dc5a5f7812dfee602a23aec80163d1d9ec13f713645b5495aeef2a9b"
> -
> -    # Fix support for clap 3.2+. Remove in the next release.
> -    # Issue ref: https://github.com/gbdev/rgbobj/issues/4
> -    patch do
> -      url "https://github.com/gbdev/rgbobj/commit/b4e1fe42dbc297d67d67ed17004a3f6956de199f.patch?full_index=1"
> -      sha256 "27aceed0020c7561e8259308df0868d19e0b7f21ad5e0f2a389d591e8b60027d"
> -    end
> +    url "https://github.com/gbdev/rgbobj/archive/refs/tags/v0.2.0.tar.gz"
> +    sha256 "9ddb14fab5ba7af170b061c2e771426fac9d3d0a39c4109b522abbc2c3b839aa"
>    end
> ```

make sense, I think it was not available when I did the PR. but updated now.

**Comment by ISSOtm** [comment]
Yeah, I pushed it shortly before making that comment.

**Comment by ISSOtm** [comment]
Just pushed v0.2.1 to fix this.

**Comment by chenrui333** [comment]
Should be good now, passed in my local

**Comment by cho-m** [comment]
Still need to override `-flto=auto` as LLVM needs https://reviews.llvm.org/D99501 to ignore GCC option (which was added in LLVM 13 -- XCode 13.3).

Makefile would need CFLAGS/CXXFLAGS variable override. Alternatively, the CMake build might handle this better.

**Comment by ISSOtm** [comment]
I'd personally recommend the CMake route, as it's what we are currently preferring for the longer term. I'm open to any pushback you might have regarding that, though.

**Comment by chenrui333** [comment]
#112963

**Comment by chenrui333** [comment]
> I'd personally recommend the CMake route, as it's what we are currently preferring for the longer term. I'm open to any pushback you might have regarding that, though.

make sense, thanks for creating the new PR.

**Pull request closed without merging**
