### PR TITLE
kakoune 2019.07.01

### PR DESCRIPTION
**Pull request by timjs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by vnagarnaik** [comment]
How can we resolve this issue? I also tested locally and the binary works well. I would like to install the binary from official brew formula.

**Comment by SMillerDev** [comment]
@brewtestbot test this please

**Comment by SMillerDev** [comment]
Builds just get removed after a couple of days. There's no need to log in, it just can't find the build.

**Comment by vnagarnaik** [comment]
The build fails for Sierra. High Sierra and Mojave builds are successful.

The change in Kakoune is to use Xcode10.1 for C++17 support. However, it looks like there is no way to update Sierra with Xcode10.1. Given this, should this formula drop support for Sierra?

Error lines copied below for posterity:
```
clang++ -I/opt/local/include -O3 -pedantic -std=c++17 -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-address -MD -MP -MF .buffer.opt.d -c -o .buffer.opt.o buffer.cc
errorerror: : errorinvalid value 'c++17' in '-std=c++17'error: 
invalid value 'c++17' in '-std=c++17': invalid value 'c++17' in '-std=c++17'

invalid value 'c++17' in '-std=c++17'
```

**Comment by vnagarnaik** [comment]
@SMillerDev Does removing support for Sierra sound like a good approach? I am not sure what the support policy for individual formula is in brew.

@timjs can you remove support for Sierra and re-upload?

**Comment by fxcoudert** [comment]
Thanks @timjs for your contribution to Homebrew!

**Pull request closed without merging**
