### PR TITLE
openjdk 15.0.1

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Failures from 10.13:

- `brew install --build-from-source carrot2`
```
* Where:
Script '/private/tmp/carrot2-20200916-39333-h5f7yj/gradle/validation/check-environment.gradle' line: 27

* What went wrong:
A problem occurred evaluating script.
> Gradle 6.5.1 is required (hint: use the gradlew script): this gradle is Gradle 6.6.1
```
- `brew install --build-from-source cbmc`
```
cd /tmp/cbmc-20200916-41918-159rf3b/src/ansi-c && /usr/bin/bison -pyyansi_c -d -o /tmp/cbmc-20200916-41918-159rf3b/build/src/ansi-c/ansi_c_y.tab.cpp /tmp/cbmc-20200916-41918-159rf3b/src/ansi-c/parser.y
Checking /tmp/cbmc-20200916-41918-159rf3b/src/ansi-c/library/cegis.c
clang: error: -Wl,-headerpad_max_install_names: 'linker' input unused [-Werror,-Wunused-command-line-argument]
rm: __libcheck.s: No such file or directory
gmake[2]: *** [src/ansi-c/CMakeFiles/ansi-c.dir/build.make:247: src/ansi-c/library-check.stamp] Error 1
```
- `brew install --build-from-source gosu` should be fixed by https://github.com/Homebrew/homebrew-core/pull/61257
```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Java.java_home_cmd is disabled! Use Language::Java.java_home or Language::Java.overridable_java_home_env instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gosu.rb:22
```
- `brew install --build-from-source htmlcleaner`
- `brew install --build-from-source jmxtrans` should be fixed by https://github.com/Homebrew/homebrew-core/pull/61257
```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Java.java_home_cmd is disabled! Use Language::Java.java_home or Language::Java.overridable_java_home_env instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jmxtrans.rb:20
```
- `brew install --build-from-source komposition`
```
Failed to build gi-glib-2.0.23. The failure occurred during the configure
step.
Build log (
/private/tmp/komposition-20200917-102-1u1wpbh/komposition-0.2.0/.brew_home/.cabal/logs/ghc-8.8.4/g-glb-2.0.23-82204c21.log
):
[1 of 1] Compiling Main             ( /private/tmp/cabal-install.-397/dist-newstyle/tmp/src-397/gi-glib-2.0.23/dist/setup/setup.hs, /private/tmp/cabal-install.-397/dist-newstyle/tmp/src-397/gi-glib-2.0.23/dist/setup/Main.o )
Linking /private/tmp/cabal-install.-397/dist-newstyle/tmp/src-397/gi-glib-2.0.23/dist/setup/setup ...
Unknown GIR element "docsection" when processing namespace "GLib", aborting.
CallStack (from HasCallStack):
  error, called at lib/Data/GI/CodeGen/API.hs:199:16 in hskll-g-0.23.1-542485de:Data.GI.CodeGen.API
cabal: Failed to build gi-glib-2.0.23 (which is required by exe:komposition
from komposition-0.2.0 and exe:komposition-split from komposition-0.2.0). See
the build log above for details.
```
- `brew install --build-from-source opencv@3`
```
CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/wrappers.pb.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/usr/bin/ranlib ../lib/liblibprotobuf.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[ 28%] Built target libprotobuf
make: *** [all] Error 2
```
- `brew install --build-from-source parquet-tools`
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Running org.apache.parquet.tools.read.TestJsonRecordFormatter
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.44 sec
Running org.apache.parquet.tools.read.TestSimpleMapRecord
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.apache.parquet.tools.read.TestSimplePrimitiveRecord
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.apache.parquet.tools.read.TestSimpleRecordConverter
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.372 sec <<< FAILURE!

Results :

Tests in error: 
  testConverter(org.apache.parquet.tools.read.TestSimpleRecordConverter)

Tests run: 6, Failures: 0, Errors: 1, Skipped: 0
```
- `brew install --build-from-source swagger-codegen` should be fixed by https://github.com/Homebrew/homebrew-core/pull/61257
```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Java.java_home_cmd is disabled! Use Language::Java.java_home or Language::Java.overridable_java_home_env instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/swagger-codegen.rb:21
```
- `brew install --build-from-source swagger-codegen@2` should be fixed by https://github.com/Homebrew/homebrew-core/pull/61257
```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Java.java_home_cmd is disabled! Use Language::Java.java_home or Language::Java.overridable_java_home_env instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/swagger-codegen@2.rb:27
```
- `brew install --build-from-source tomcat-native` should be fixed by https://github.com/Homebrew/homebrew-core/pull/61255
```
==> FAILED
==> Downloading https://www.apache.org/dyn/closer.lua?path=tomcat/tomcat-connectors/native/1.2.24/source/tomcat-native-1.2.24-src.tar.gz
==> Downloading from http://mirror.metrocast.net/apache/tomcat/tomcat-connectors/native/1.2.24/source/tomcat-native-1.2.24-src.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://archive.apache.org/dist/tomcat/tomcat-connectors/native/1.2.24/source/tomcat-native-1.2.24-src.tar.gz--sha256=037f52f9a345e766a7dde8361c55b3b69045928f9a8068a406612b603819e76c
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://downloads.apache.org/tomcat/tomcat-connectors/native/1.2.24/source/tomcat-native-1.2.24-src.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "tomcat-native"
Download failed: https://downloads.apache.org/tomcat/tomcat-connectors/native/1.2.24/source/tomcat-native-1.2.24-src.tar.gz
```
- `brew test --retry --verbose mesos`
```
==> Testing mesos
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200917-61050-1ktim57.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mesos.rb --verbose --retry
==> /usr/local/Cellar/mesos/1.8.1_1/sbin/mesos-agent --version
==> /usr/local/Cellar/mesos/1.8.1_1/sbin/mesos-master --version
==> /usr/local/Cellar/mesos/1.8.1_1/bin/mesos 2>&1
==> python -c import mesos.native
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/mesos/native/__init__.py", line 17, in <module>
    from mesos.executor import MesosExecutorDriver
  File "/usr/local/lib/python2.7/site-packages/mesos/executor/__init__.py", line 17, in <module>
    from ._executor import MesosExecutorDriverImpl as MesosExecutorDriver
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/mesos/executor/_executor.so, 2): Symbol not found: __ZN6google14FlagRegistererC1INSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEPKcSA_SA_PT_SC_
  Referenced from: /usr/local/lib/python2.7/site-packages/mesos/executor/_executor.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/mesos/executor/_executor.so
```
- `brew test --retry --verbose metabase`
```
==> /usr/local/Cellar/metabase/0.36.6/bin/metabase migrate up
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
Warning: environ value /usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home for key :java-home has been overwritten with /usr/local/Cellar/openjdk/15/libexec/openjdk.jdk/Contents/Home
09-17 02:46:29 INFO metabase.util :: Loading Metabase...
09-17 02:46:29 INFO metabase.util :: Maximum memory available to JVM: 3.6 GB
WARNING: not-empty already refers to: #'clojure.core/not-empty in namespace: metabase.mbql.schema, being replaced by: #'metabase.mbql.schema/not-empty
09-17 02:46:42 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. ? 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
...
	at metabase.core.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.JSObject
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
...
```
- `brew test --retry --verbose micronaut`
```
==> Testing micronaut
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200917-73552-125l4k8.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/micronaut.rb --verbose --retry
==> /usr/local/Cellar/micronaut/2.0.2/bin/mn create-app hello-world
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
| Error Unsupported JDK version: 15. Supported values are [8, 9, 10, 11, 12, 13, 14]
```
- `brew test --retry --verbose pax-construct`
```
==> brew test --retry --verbose pax-construct
==> FAILED
==> Testing pax-construct
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200917-69926-1n34ese.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pax-construct.rb --verbose --retry
==> /usr/local/Cellar/pax-construct/1.5/bin/pax-create-project -g Homebrew -a testing -v alpha-1
/usr/local/Cellar/pax-construct/1.5/libexec/bin/pax-create-project: line 83: exec: mvn: not found
==> Testing pax-construct (again)
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200917-70194-15m4i4w.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pax-construct.rb --verbose --retry
==> /usr/local/Cellar/pax-construct/1.5/bin/pax-create-project -g Homebrew -a testing -v alpha-1
/usr/local/Cellar/pax-construct/1.5/libexec/bin/pax-create-project: line 83: exec: mvn: not found
Error: pax-construct: failed
```
- `brew test --retry --verbose solr@7.7`
```
==> Testing solr@7.7
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200917-95998-ihjepq.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/solr@7.7.rb --verbose --retry
==> /usr/local/Cellar/solr@7.7/7.7.3/bin/solr -i
==> /usr/local/Cellar/solr@7.7/7.7.3/bin/solr start -p 64902 -Djava.io.tmpdir=/tmp
==> /usr/local/Cellar/solr@7.7/7.7.3/bin/solr -i

Found 1 Solr nodes: 

Solr process 96066 from /usr/local/var/run/solr/solr-64902.pid not found.
```

**Comment by asbjornu** [comment]
I'd love to see this merged. Is there any way I can help progress this, @bayandin?

**Comment by SMillerDev** [comment]
You can help fix all posted build failures.

**Comment by bayandin** [comment]
Fails on all macOS versions:
- `brew install --build-from-source cbmc`
- `brew install --build-from-source komposition`
- `brew install --build-from-source parquet-tools`
- `brew test --retry --verbose pax-construct`
- `brew test --retry --verbose solr@7.7`

Fails on **10.15** only (I believe the failures could be related to Xcode 12 update):
- `brew fetch --retry structurizr-cli`
- `brew install --build-from-source astrometry-net`
- `brew install --build-from-source mercury`
- `brew install --build-from-source root`

**Comment by jonchang** [comment]
I fixed mercury in https://github.com/Homebrew/homebrew-core/pull/62606, no clue why this run didn't pick it up.

**Comment by bayandin** [comment]
> I fixed mercury in #62606, no clue why this run didn't pick it up.

It looks like it was merged after tests were triggered (I don't see the patch in my branch).
No worries, we'll need at least one more run (hopefully only one)

**Comment by bayandin** [comment]
Also, it seems we need to add `--with-sysroot=#{MacOS.sdk_path}` to make it possible to build OpenJDK on CLT-only systems

**Comment by bayandin** [comment]
> * brew install --build-from-source cbmc

Wasn't able to reproduce the same failure, but got a similar problem (https://github.com/diffblue/cbmc/issues/4956) by switching CMake generator to ninja, and applying suggested workaround (`-DCMAKE_C_COMPILER=/usr/bin/clang `) helped. Will try to use it, to see it helps.

**Comment by bayandin** [comment]
- `brew install --build-from-source carrot2` should be fixed by https://github.com/Homebrew/homebrew-core/pull/63059
- `brew install --build-from-source freeswitch`
- `brew install --build-from-source kamel`
- `brew install --build-from-source komposition`
- `brew test --retry --verbose pax-construct`

- `brew install --build-from-source opencv@3` only on macOS 10.13

**Comment by bayandin** [comment]
Regarding `opencv@3` failure on High Sierra:
```
/tmp/opencv@3-20201017-92788-1i4yuk4/opencv-3.4.12/modules/core/include/opencv2/core/hal/intrin_sse_em.hpp:151:12: error: always_inline function '_mm_packus_epi32' requires target feature 'sse4.1', but would be inlined into function '_v128_packs_epu32' that is compiled without support for 'sse4.1'
    return _mm_packus_epi32(am, bm);
           ^
/tmp/opencv@3-20201017-92788-1i4yuk4/opencv-3.4.12/modules/core/include/opencv2/core/hal/intrin_sse_em.hpp:111:1: error: always_inline function '_mm_min_epu32' requires target feature 'sse4.1', but would be inlined into function '_v128_min_epu32' that is compiled without support for 'sse4.1'
OPENCV_HAL_SSE_WRAP_2(min_epu32, __m128i)
^
/tmp/opencv@3-20201017-92788-1i4yuk4/opencv-3.4.12/modules/core/include/opencv2/core/hal/intrin_sse_em.hpp:21:14: note: expanded from macro 'OPENCV_HAL_SSE_WRAP_2'
    { return _mm_##fun(a, b); }
             ^
<scratch space>:122:1: note: expanded from here
_mm_min_epu32
^
2 errors generated.
```

It looks like cmake flags that we set (`args << "-DENABLE_SSE41=OFF" << "-DENABLE_SSE42=OFF" unless MacOS.version.requires_sse42?`) are inconsistent with what it detects itself:
```
-- Performing Test HAVE_CPU_SSE4_1_SUPPORT - Success
-- Performing Test HAVE_CPU_POPCNT_SUPPORT (check file: cmake/checks/cpu_popcnt.cpp)
-- Performing Test HAVE_CPU_POPCNT_SUPPORT - Failed
-- Performing Test HAVE_CXX_MPOPCNT (check file: cmake/checks/cpu_popcnt.cpp)
-- Performing Test HAVE_CXX_MPOPCNT - Success
-- Performing Test HAVE_CPU_SSE4_2_SUPPORT (check file: cmake/checks/cpu_sse42.cpp)
-- Performing Test HAVE_CPU_SSE4_2_SUPPORT - Failed
```

It happens because Penryn processor (that we have on out High Sierra agens) supports sse4.1 and doesn't support 4.2.

Since `opencv` suggests to use CPU_BASELINE/CPU_DISPATCH options instead of those we use, I'll try to replace them and hopefully it became consistent 
```
-- WARNING: Option ENABLE_SSE41='OFF' is deprecated and should not be used anymore
--          Behaviour of this option is not backward compatible
--          Refer to 'CPU_BASELINE'/'CPU_DISPATCH' CMake options documentation
-- WARNING: Option ENABLE_SSE42='OFF' is deprecated and should not be used anymore
--          Behaviour of this option is not backward compatible
--          Refer to 'CPU_BASELINE'/'CPU_DISPATCH' CMake options documentation
-- WARNING: Option ENABLE_AVX='OFF' is deprecated and should not be used anymore
--          Behaviour of this option is not backward compatible
--          Refer to 'CPU_BASELINE'/'CPU_DISPATCH' CMake options documentation
-- WARNING: Option ENABLE_AVX2='OFF' is deprecated and should not be used anymore
--          Behaviour of this option is not backward compatible
--          Refer to 'CPU_BASELINE'/'CPU_DISPATCH' CMake options documentation
```

**Comment by jonchang** [comment]
komposition: https://github.com/Homebrew/homebrew-core/pull/63449

**Comment by bayandin** [comment]
`cmus` broken linkage should be fixed by https://github.com/Homebrew/homebrew-core/pull/63595

**Comment by bayandin** [comment]
There're only 2 failed tests on High Sierra: already known `opencv@3` and `synfig` with some random download error:
```
==> FAILED
==> Downloading https://downloads.sourceforge.net/project/synfig/releases/1.2.2/source/synfig-1.2.2.tar.gz
==> Downloading from https://master.dl.sourceforge.net/project/synfig/releases/1.2.2/source/synfig-1.2.2.tar.gz
curl: (22) The requested URL returned error: 503 Service Unavailable
Error: Failed to download resource "synfig"
```
@jonchang I believe we're finally ready to merge it 🎉

**Comment by jonchang** [comment]
Yeah let's do it 😅

**Pull request closed without merging**
