### PR TITLE
llvm@9: use elfutils on Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Retrying #83780 here to see if new branch/PR can help merge issue.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Weird:
```
Error: docker://ghcr.io/homebrew/core/oclgrind:19.10_4 already exists!
```

**Comment by carlocab** [comment]
Only one download though, and this has never been published to Homebrew/core. Let's try removing it.

**Review by carlocab — DISMISSED** [review]

**Comment by cho-m** [comment]
It might be from the previous upload attempt in #83780.

**Comment by cho-m** [comment]
Still failing. At this point, it may be something wrong with GitHub package or Homebrew's upload.

May need to try manually uploading this.

**Review by SMillerDev — DISMISSED** [review]

**Comment by cho-m** [comment]
The error is the same as TexLive PR #83738, so it seems that manual upload will be required to get around the current failure.

**Comment by iMichka** [comment]
Rebased with updated revisions

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Merging this manually.

**Comment by carlocab** [comment]
```
Error: docker://ghcr.io/homebrew/core/oclgrind:19.10_4 already exists!
```
Needs another rev bump.

**Comment by carlocab** [comment]
Deleted the new revision (`4`) in this PR for `llvm@9` from GitHub Packages to prevent another upload failure.

**Pull request closed without merging**
