### PR TITLE
watchman: use Python 3

### PR DESCRIPTION
**Pull request by singingwolfboy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
why the switch?

**Comment by singingwolfboy** [comment]
Because [watchman's Python integration supports Python 3](https://github.com/facebook/watchman/blob/master/python/setup.py#L40), and Homebrew has a policy of using the latest available stable software. Python 3 is the latest available stable version of Python, so watchman should use Python 3.

**Comment by ilovezfs** [comment]
We're not actively switching reverse dependencies of python@2 from Python 2 to 3 without a reason so I'm closing this out. But thanks for the PR nonetheless.

**Comment by kylecbrodie** [comment]
Is it possible to have it use python 3 if it is already installed and if not, install python 2?

**Pull request closed without merging**
