### PR TITLE
swift 5.2.2

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Here we go again.

### CODE REVIEW

**Comment by bayandin** [comment]
```
14:08:31 --- Installing swift ---
14:08:31 + env DESTDIR=/usr/local/Cellar/swift/5.2.1/ /usr/local/opt/cmake/bin/cmake --build /private/tmp/swift-20200405-19812-12y1x8u/build/swift-macosx-x86_64 -- install-swift-components
14:08:31 + env DESTDIR=/usr/local/Cellar/swift/5.2.1/ /usr/local/opt/cmake/bin/cmake --build /private/tmp/swift-20200405-19812-12y1x8u/build/swift-macosx-x86_64 -- install-swift-components
14:08:31 [0/14][  0%][0.000s] cd /tmp/swift-20200405-19812-12y1x8u/build/swift-macosx-x86_64 && /usr/local/Cellar/cmake/3.17.0_1/bin/cmake -DCMAKE_INSTALL_COMPONENT="clang-builtin-headers-in-clang-resource-dir" -P /tmp/swift-20200405-19812-12y1x8u/build/swift-macosx-x86_64/cmake_install.cmake
14:08:31 -- Install configuration: "Release"
14:08:31 CMake Error at stdlib/public/SwiftShims/cmake_install.cmake:102 (file):
14:08:31   file INSTALL cannot find
14:08:31   "/tmp/swift-20200405-19812-12y1x8u/build/llvm-macosx-x86_64/./lib/lib/clang":
14:08:31   No such file or directory.
14:08:31 Call Stack (most recent call first):
14:08:31   stdlib/public/cmake_install.cmake:37 (include)
14:08:31   stdlib/cmake_install.cmake:38 (include)
14:08:31   cmake_install.cmake:41 (include)
14:08:31 
14:08:31 
14:08:31 FAILED: CMakeFiles/install-clang-builtin-headers-in-clang-resource-dir 
14:08:31 cd /tmp/swift-20200405-19812-12y1x8u/build/swift-macosx-x86_64 && /usr/local/Cellar/cmake/3.17.0_1/bin/cmake -DCMAKE_INSTALL_COMPONENT="clang-builtin-headers-in-clang-resource-dir" -P /tmp/swift-20200405-19812-12y1x8u/build/swift-macosx-x86_64/cmake_install.cmake
14:08:31 ninja: build stopped: subcommand failed.
```

**Comment by SMillerDev** [comment]
```
2020-04-17T04:50:32.1997730Z /usr/bin/sandbox-exec -f /private/tmp/homebrew20200417-71204-143jkmp.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/swift.rb --verbose
2020-04-17T04:50:38.2931310Z [34m==>[0m [1m/usr/local/Cellar/swift/5.2.2/Swift-5.2.2.xctoolchain/usr/bin/swift test.swift[0m
2020-04-17T04:50:38.4570530Z /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2/libxml/module.modulemap:1:8: error: redefinition of module 'libxml2'
2020-04-17T04:50:38.4571040Z module libxml2 [system] [extern_c] {
2020-04-17T04:50:38.4571260Z        ^
2020-04-17T04:50:38.4571500Z /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
2020-04-17T04:50:38.4571750Z module libxml2 [system] [extern_c] {
2020-04-17T04:50:38.4571880Z        ^
2020-04-17T04:50:38.6176340Z 
2020-04-17T04:50:38.7555140Z [31mError:[0m swift: failed
2020-04-17T04:50:38.7575300Z An exception occurred within a child process:
2020-04-17T04:50:38.7576790Z   Test::Unit::AssertionFailedError: <0> expected but was
2020-04-17T04:50:38.7577100Z <1>.
```

**Comment by Bo98** [comment]
Ok so if I do `ENV["SDKROOT"] = MacOS::Xcode.sdk_path` on Catalina it starts complaining about broken parts of the CLT SDK even though I explicitly tell it to use the Xcode SDK. If I don't set `SDKROOT` it passes the test without issue???

Oh and I need to still set `SDKROOT` on Mojave as the Xcode SDK is newer than those in the CLT and this version of Swift doesn't work with old SDKs. It behaves as expected there and happily uses the Xcode SDK.

**Comment by Bo98** [comment]
Fixed it. Finally.

Only took several months of failed attempts.

**Comment by Bo98** [comment]
Maybe I should annoy the Linux folk and request a Linux bottle for this.

**Pull request closed without merging**
