### PR TITLE
simgrid 3.26

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
license file

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: SimGrid
Source: https://simgrid.org/

Files: *
Copyright: 2003-2020. The SimGrid team. All rights reserved.
License: LGPL-2.1

Files: src/xbt/snprintf.c
Copyright: 1999, Mark Martinec <mark.martinec@ijs.si.
License: Artistic
Comment: Heavily adapted by the SimGrid team but remains under the original license

Files: src/xbt/mmalloc/* src/include/xbt/mmalloc.h
Copyright: 
  Copyright (C) 1991, 1992 Free Software Foundation, Inc.
  Copyright (C) 2003-2020. The SimGrid team.
License: LGPL-2.1
Comment: these files used to be part of gdb, but were removed there

Files: 
 teshsuite/smpi/mpich3-test/*
Copyright: 
 (C) 2001-2014 by Argonne National Laboratory.
 (C) 2008 by University of Illinois.
 (C) 2011-2012 Intel Corporation. 
License: other
```

**Comment by chenrui333** [comment]
seems complicated. cc @carlocab @Rylan12

**Comment by carlocab** [comment]
@chenrui333 It does look complicated. Better to look at the headers in the source tarball, I think. I'll try to have a look later.

**Comment by Rylan12** [comment]
If this comes up again, `license :cannot_represent` may be the way to go. Didn't look that closely but not sure about the "other" license. Otherwise, looked like mostly `LGPL-2.1-only`. Didn't check which `Artistic` version it is.

**Pull request closed without merging**
