### PR TITLE
z3 4.12.1

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Looking at previous one, will require linux self-hosted runners @chenrui333

**Comment by chenrui333** [comment]
> Looking at previous one, will require linux self-hosted runners @chenrui333

The previous was due to the revision bump for `long build` formulae, I dont think it is needed this time, but we will see.

**Comment by Porkepix** [comment]
> > Looking at previous one, will require linux self-hosted runners @chenrui333
> 
> The previous was due to the revision bump for `long build` formulae, I dont think it is needed this time, but we will see.

And here the same revision bumps aren't needed? :o

also, is it possible to restart only  `12-arm64`'s job? Feels like it'll take years, while other ARM runners took 25 minutes and 40 minutes, this one is at almost 3H run time and only at the 'd' letter for dependents testing. Dunno why it's going so slowly…

**Comment by ZhongRuoyu** [comment]
> And here the same revision bumps aren't needed? :o

No, since the soname only requires a minor version match:

```plaintext
$ patchelf --print-soname /home/linuxbrew/.linuxbrew/lib/libz3.so.4.12
libz3.so.4.12
$ brew linkage zig
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib64/ld-linux-x86-64.so.2
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libncursesw.so.6 (ncurses)
  /home/linuxbrew/.linuxbrew/lib/libz3.so.4.12 (z3)
Dependencies with no linkage:
  zlib
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
only `rtags` failed on 12-arm, merging.

**Comment by chenrui333** [comment]
> > > Looking at previous one, will require linux self-hosted runners @chenrui333
> > 
> > 
> > The previous was due to the revision bump for `long build` formulae, I dont think it is needed this time, but we will see.
> 
> And here the same revision bumps aren't needed? :o
> 
> also, is it possible to restart only `12-arm64`'s job? Feels like it'll take years, while other ARM runners took 25 minutes and 40 minutes, this one is at almost 3H run time and only at the 'd' letter for dependents testing. Dunno why it's going so slowly…
> 
> EDIT: Looks like it decided to suddenly go faster, 20 minutes later it now reached the 'l' letter. The job still took much more time than it should have though.

i agree, there is probably som runner issue.

**Pull request closed without merging**
