### PR TITLE
libX11 1.8.3

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

continuing #118272

### CODE REVIEW

**Comment by cho-m** [comment]
`11-arm64` will need another run as `dronedb` test killed current run:
```
==> brew test --retry --verbose dronedb
Error: SIGTERM
/opt/homebrew/Library/Homebrew/system_command.rb:216:in `join'
```

May need to figure out why CI didn't continue as bottle/cleanup/etc steps were all skipped.

**Comment by chenrui333** [comment]
> `11-arm64` will need another run as `dronedb` test killed current run:
> 
> ```
> ==> brew test --retry --verbose dronedb
> Error: SIGTERM
> /opt/homebrew/Library/Homebrew/system_command.rb:216:in `join'
> ```
> 
> May need to figure out why CI didn't continue as upload/cleanup/etc steps were all skipped.

this is really bad and waste lots of CI time.

**Comment by chenrui333** [comment]
openslide test failure should be addressed in [this PR](https://github.com/Homebrew/homebrew-core/pull/118939)

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
==> brew test --retry --verbose dronedb
Error: SIGTERM
```
image

**Comment by chenrui333** [comment]
🤞 for this run

**Comment by chenrui333** [comment]
## `13`

`brew test --retry --verbose prestodb` 

## `12`

`brew install --only-dependencies pyside` (github networking failure)

## linux

```
brew linkage --test qt
brew linkage --test qt@5
```
would be addressed with revision bumps

**Comment by xeron** [comment]
This fails for me with:

```
==> Installing tesseract dependency: libx11
==> ./configure --prefix=/opt/brew/Cellar/libx11/1.8.3 --sysconfdir=/opt/brew/etc --localstatedir=/opt/brew/var --enable-unix-transport --enable-tcp-transport --enable-ipv6 --enable-local-transport --enable-
Last 15 lines from /Users/ilarionov/Library/Logs/Homebrew/libx11/01.configure:
checking for BIGFONT... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for nl_langinfo... yes
checking for X11... no
configure: error: Package requirements (xproto >= 7.0.25 xextproto xtrans xcb >= 1.11.1 kbproto inputproto) were not met:

Package 'pthread-stubs', required by 'xcb', not found
```

**Comment by cho-m** [comment]
> This fails for me with:
> 
> ```
> ==> ./configure --prefix=/opt/brew/Cellar/libx11/1.8.3 --sysconfdir=/opt/brew/etc --localstatedir=/opt/brew/var --enable-unix-transport --enable-tcp-transport --enable-ipv6 --enable-local-transport --enable-
> Last 15 lines from /Users/ilarionov/Library/Logs/Homebrew/libx11/01.configure:
> checking for BIGFONT... yes
> checking for getpagesize... yes
> checking for working mmap... yes
> checking for nl_langinfo... yes
> checking for X11... no
> configure: error: Package requirements (xproto >= 7.0.25 xextproto xtrans xcb >= 1.11.1 kbproto inputproto) were not met:
> 
> Package 'pthread-stubs', required by 'xcb', not found
> ```

Please reinstall `libxcb` first to get #111928

**Comment by xeron** [comment]
Thanks, this helped, but I assume it should've happened automatically?

**Comment by cho-m** [comment]
> Thanks, this helped, but I assume it should've happened automatically?

We've recently started reducing revision bumps (now mainly for important security fixes and total breakages) based on user feedback, so it won't get auto-updated until next version.

**Pull request closed without merging**
