### PR TITLE
swift: fix build script argument

### PR DESCRIPTION
**Pull request by Crazor**
build-script argument --build-jobs has been renamed to --jobs.

### CODE REVIEW

**Comment by DomT4** [comment]
Is the change just in `HEAD`, not stable yet?
```
==> /private/tmp/swift-20160828-8642-3tafsv/swift-swift-2.2.1-RELEASE/utils/build-script -R --build-subdir= --no-llvm-assertions --no-swift-assertions --no-swift-stdlib-assertions -- --workspace=/private/tmp/swift-20160828-8642-3tafsv --build-args=-j4 --lldb-use-system-debugserver --install-prefix=/usr/local/Cellar/swift/2.2.1 --darwin-deployment-version-osx=10.10 --jobs=4
Error: Unknown setting: jobs
```

**Comment by Crazor** [comment]
You're absolutely right. I pushed a fix.

**Comment by DomT4** [comment]
I think the fix here is a little overcomplicated for the situation. Keeping the block mostly how it was originally, but tweaking it to use an `args` array and then tacking on:
```ruby
if build.head?
  args << "--jobs=#{ENV.make_jobs}"
else
  args << "--build-jobs=#{ENV.make_jobs}"
end
```
Is probably the simplest way of getting this done.

**Comment by ilovezfs** [comment]
Closing for now but please feel free to reopen with the above suggested change.

**Comment by apjanke** [comment]
Following up with the suggested change in #6307.

**Pull request closed without merging**
