### PR TITLE
Update tracebox.rb

### PR DESCRIPTION
**Pull request by gdavila**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apjanke** [comment]
It looks like upstream has been moving the `v0.3.1` tag in the repo. Instead of using a `:tag` and `:revision`, could you change the formula to point at the actual [release](https://github.com/tracebox/tracebox/releases/tag/v0.3.1) of `v0.3.1`?

**Comment by gdavila** [comment]
Do I have just remove the :tag and :revision? This is my first time with home brew so maybe I'm ignoring the right way to update the repo. I've cloned the tracebox.rb and  formula seems to work. Updating the :tag it seems to point to the latest tracebox commit.

**Comment by apjanke** [comment]
Yes, it works, but it might not in the future, because git tags are not stable. (Which, from the looks of things, is exactly why the test failed for this PR here.) Releases are more permanent.

Instead of this:

```
   url "https://github.com/tracebox/tracebox.git", :tag => "v0.3.1",
         :revision => "5a0792a9749a2c941646000bf62bcbde280a8b71"
```

Try this:

```
url "https://github.com/tracebox/tracebox/archive/v0.3.1.tar.gz"
```

And I realize that this isn't something you've introduced with this change. It's a pre-existing issue with the formula. But while we're here, let's try to clean it up.

**Comment by gdavila** [comment]
I've closed the PR. I noticed my fault: I was trying to point the formula to the the last tracebox commit but it seems that the last commit has no tag (version/release) and home brew doesn't allow this updates (so it needs to be solved first)

Thanks a lot for the support.

**Pull request closed without merging**
