### PR TITLE
pssh: fix for Python 3

### PR DESCRIPTION
**Pull request by btriller**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
The comment below says there already is one.

**Comment by btriller** [comment]
This one is for stdin string handling. Without it one gets:
```python
Traceback (most recent call last):
  File "/usr/local/bin/pssh", line 118, in <module>
    do_pssh(hosts, cmdline, opts)
  File "/usr/local/bin/pssh", line 89, in do_pssh
    statuses = manager.run()
  File "/usr/local/Cellar/pssh/2.3.1_2/libexec/lib/python3.8/site-packages/psshlib/manager.py", line 75, in run
    self.iomap.poll(wait)
  File "/usr/local/Cellar/pssh/2.3.1_2/libexec/lib/python3.8/site-packages/psshlib/manager.py", line 257, in poll
    handler(fd, self)
  File "/usr/local/Cellar/pssh/2.3.1_2/libexec/lib/python3.8/site-packages/psshlib/task.py", line 170, in handle_stdin
    self.byteswritten = start + os.write(fd, chunk)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by SMillerDev** [comment]
This should be submitted to upstream too

**Comment by btriller** [comment]
[Upstream](https://github.com/nplanel/parallel-ssh) seems pretty inactive. Anyways, lets try it nplanel/parallel-ssh#103

**Comment by fxcoudert** [comment]
- There is no clear upstream at this point (several low-visibility low-activity forks).
- It's not actively maintained
- It requires patch after patch

I suggest removing it

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
It has a lot of users, so… merging this one, at least the patch is straightforward.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
