### PR TITLE
kibana 6.2.0

### PR DESCRIPTION
**Pull request by tylerjl**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> brew audit kibana --online
==> FAILED
Error: 2 problems in 1 formula
kibana:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/kibana.rb kibana@6.2
  * Formula has invalid versioned aliases:
      kibana@6.1
```

**Comment by tylerjl** [comment]
Moved the alias to `kibana@6.2`, I don't think there's any reason to keep around the minor version alias for 6.1 (just let me know if that isn't the correct pattern moving forward 🐱 )

**Comment by ilovezfs** [comment]
Yup, renaming the symlink is the right thing to do.

**Comment by fxcoudert** [comment]
Thanks @tylerjl for the pull requests!

**Pull request closed without merging**
