### PR TITLE
ucspi-tcp: fix build on Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can we disable the tests?

**Comment by cho-m** [comment]
I think the error happens during basic compilation (`make`) when generating `hasshsgr.h`, which is needed as dependency of library: `unix.a --> prot.o --> hasshsgr.h`
```
hasshsgr.h: \
choose compile load tryshsgr.c hasshsgr.h1 hasshsgr.h2 chkshsgr \
warn-shsgr
	./chkshsgr || ( cat warn-shsgr; exit 1 )
	./choose clr tryshsgr hasshsgr.h1 hasshsgr.h2 > hasshsgr.h
```

Didn't seem possible to avoid

**Comment by SMillerDev** [comment]
That's annoying, if we patch this could you at least ask upstream for a way to compile without root? I doubt were the only package manager doing that.

**Comment by cho-m** [comment]
> That's annoying, if we patch this could you at least ask upstream for a way to compile without root?

Hard to say if this will get anywhere given how old the current version is (22 years ago):
```
ucspi-tcp 0.88, beta.
20000318
Copyright 2000
D. J. Bernstein
```

---

> I doubt were the only package manager doing that.

To preface, in case of macOS, Homebrew's user seems to have sufficient `setgroups` permissions to avoid root requirement so this is specific to Linux.

I think many Linux repositories are 1st party so would have root or sufficient permissions.

From quick glance, I only saw NixOS hack around this issue at https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/networking/ucspi-tcp/default.nix#L33-L40
```
  # Also, assume getgroups and setgroups work, instead of doing a build time
  # test that breaks on NixOS (I think because nixbld users lack CAP_SETGID
  # capability).
  preBuild = ''
    echo "$out" > conf-home

    echo "main() { return 0; }" > chkshsgr.c
  '';
```

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
> Hard to say if this will get anywhere given how old the current version is (22 years ago):

Ouch, yeah that won't work

**Pull request closed without merging**
