### PR TITLE
terraform 0.13.4

### PR DESCRIPTION
**Pull request by benesch**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by faucherb94** [comment]
Looks like one of the GH CI checks has hung.

**Comment by benesch** [comment]
Possibly there's just a giant backlog? 10.14 was the same for hours, but did eventually complete.

**Comment by benesch** [comment]
Indeed, seems happy now!

**Comment by miccal** [comment]
Thank you @benesch.

**Review by miccal — APPROVED** [review]

**Comment by ffloimair** [comment]
postinstall steps fails (with no reason)

**Comment by SMillerDev** [comment]
There is no postinstall step, what does the log say?

**Pull request closed without merging**
