### PR TITLE
riak 2.2.1

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nijikon** [comment]
#10839

**Comment by nijikon** [comment]
```
riak:
  * The installation was broken.
    Broken dylib links found:
      /usr/local/opt/wxmac/lib/libwx_osx_cocoau_stc-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_osx_cocoau_xrc-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_osx_cocoau_html-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_osx_cocoau_adv-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_baseu_xml-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_osx_cocoau_core-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_baseu-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_osx_cocoau_gl-3.0.dylib
        /usr/local/opt/wxmac/lib/libwx_osx_cocoau_aui-3.0.dylib
```

**Comment by fxcoudert** [comment]
Is this formula actually open source software? It installs a whole lot of precompiled Mach-O binaries :(

**Comment by nijikon** [comment]
https://github.com/basho/riak

**Comment by nijikon** [comment]
Maybe we can build instead...

**Comment by MikeMcQuaid** [comment]
Yeh, I've been requesting we build this from source for a while.

**Comment by raza15** [comment]
@MikeMcQuaid can i try to solve this? Or some other simple issue that would serve as a good first commit to the project? Thanks.

**Comment by MikeMcQuaid** [comment]
@raza15 That'd be good but it might not be an easy first commit. Check out https://github.com/Homebrew/brew#contributing

**Comment by ilovezfs** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/11783.

**Pull request closed without merging**
