### PR TITLE
subversion: use macOS's perl

### LINKED ISSUE #52490: git-svn no longer working after upgrade to Catalina 10.15.4
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

for svn formular: https://gist.github.com/627d85f2c1fc341b76f8f98f162331c8
for git formular: https://gist.github.com/0597eb212b85e92f35d8e35fc91d866a 

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
 ```
$brew doctor 
Your system is ready to brew.
```

```
$brew config
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6949fc6f36de1261dffbe37f3b2216cf903431ed
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.4.0.0.1.1583798712
Xcode: 11.4
XQuartz: 2.7.11 => /opt/X11
```

## What you were trying to do (and why)
Try to using git-svn to checkout and mange some svn repos with git

## What happened (include command output)
git svn is no longer working. There are some problems with the perl bindings.

<details>
  <summary>Command output</summary>
  <pre>

 $ git svn rebase   
Can't locate SVN/Core.pm in @INC (you may need to install the SVN::Core module) (@INC contains: /usr/local/Cellar/git/2.26.0/share/perl5 /Applications/Xcode.app/Contents/Developer/Library/Perl/5.18/darwin-thread-multi-2level /Library/Developer/CommandLineTools/Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/Cellar/git/2.26.0/share/perl5/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at /usr/local/Cellar/git/2.26.0/share/perl5/Git/SVN/Utils.pm line 6.
Compilation failed in require at /usr/local/Cellar/git/2.26.0/share/perl5/Git/SVN.pm line 25.
BEGIN failed--compilation aborted at /usr/local/Cellar/git/2.26.0/share/perl5/Git/SVN.pm line 32.
Compilation failed in require at /usr/local/Cellar/git/2.26.0/libexec/git-core/git-svn line 22.
BEGIN failed--compilation aborted at /usr/local/Cellar/git/2.26.0/libexec/git-core/git-svn line 22.

  </pre>
</details>

## What you expected to happen

That `git svn rebase` update my repository. 

## Step-by-step reproduction instructions (by running `brew install` commands)

Installed Git and SVN on Catalina 10.15.3
<pre>
brew install svn
brew install git
</pre>

`git svn` works fine. 

Upgraded my system from Catalina 10.15.3 to Catalina 10.15.4 and `git svn` no longer works. 
Reinstall git and svn don't solved the problem.

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fix #52490 by built `subversion` against system `perl`. To make `git svn` work, we also have to add an environment variable `PERL5LIB=/usr/local/lib/perl5/site_perl/#{perl_version}/darwin-thread-multi-2level`. It's not that convenient but this way we do not have to edit `/usr/local/opt/git/libexec/git-core/git-svn` after every update of `git`.

And remove dependency `perl` also makes `subversion` smaller.

And previous pull request #64221 makes someone's `subversion` broken. Now I have some solutions.

For @ergl's [issue](https://github.com/Homebrew/homebrew-core/pull/64221#issuecomment-726227280):
This is because he installs `subversion` from the source with brewed `perl`. Now I add code to respect `perl` in `PATH`. I treat `perl` as brewed first. if it does not meet the conditions, I use the `perl` as system. This should solve this problem. And I test in both system `perl` and brewed `perl`, it worked well.

For @lstomberg's [issue](https://github.com/Homebrew/homebrew-core/pull/64221#issuecomment-727008931):
This is because he updates macOS to Big Sur before it releases. At that time, homebrew has no bottle for Big Sur. Now that is not a problem.

### CODE REVIEW

**Comment by carlocab** [comment]
Restarting the tests. It looks like the 10.14 test skipped lots of steps for some reason.

For comparison,

10.14: https://github.com/Homebrew/homebrew-core/runs/1656632908?check_suite_focus=true
ARM: https://github.com/Homebrew/homebrew-core/runs/1656632857?check_suite_focus=true

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @moonfruit!

**Comment by carlocab** [comment]
`subversion` is failing tests on 10.14 and 10.15 at https://github.com/Homebrew/homebrew-core/pull/67378/checks, and I can't help suspecting it's related to this change.

@moonfruit, can you look into this?

**Comment by moonfruit** [comment]
OK, I will look into it.

**Comment by carlocab** [comment]
Thank you!

**Comment by moonfruit** [comment]
I think this because `subversion` bottle built with system `perl` which is 5.18. And macOS already install brewed `perl` which is 5.32.

In the meantime, the test finds `perl` version by the `perl` in PATH which is brewed `perl`, but `subversion` has not been built `perl` binding for this version. So test failed.

Should I always use `/usr/bin/perl` in the test? Or add some checks before the test? @carlocab

**Comment by carlocab** [comment]
Thanks for investigating.

>Should I always use `/usr/bin/perl` in the test?

I think this solution should be fine.

**Comment by moonfruit** [comment]
I made pull request #68747 for this. Please review.

**Comment by carlocab** [comment]
Thanks again, @moonfruit!

**Pull request closed without merging**
