### PR TITLE
ansible 2.9.5

### PR DESCRIPTION
**Pull request by apple4ever**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
One thing that I can see is we probably also want to update the dependency resource versions too.

**Comment by apple4ever** [comment]
@chenrui333 I can do that. I pushed this up with `brew bump-formula-pr`. How do I update the dependencies?

**Comment by zbeekman** [comment]
@apple4ever something like this:
```
$ pip3 install homebrew-pypi-poet
$ pip3 install -U ansible
$ poet ansible
  resource "ansible" do
    url "https://files.pythonhosted.org/packages/ec/17/1057cd4fa1c672dde8cc6a2ebc5df29e35170bcbd178291c918b435fe285/ansible-2.9.5.tar.gz"
    sha256 "51ae50d33264eb644ecb79a0208a20569a1127ec3440e8de60eda3a2b3d9caa5"
  end
  resource "cffi" do
    url "https://files.pythonhosted.org/packages/05/54/3324b0c46340c31b909fcec598696aaec7ddc8c18a63f2db352562d3354c/cffi-1.14.0.tar.gz"
    sha256 "2d384f4a127a15ba701207f7639d94106693b6cd64173d6c8988e2c25f3ac2b6"
  end
  resource "cryptography" do
    url "https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz"
    sha256 "3cda1f0ed8747339bbdf71b9f38ca74c7b592f24f65cdb3ab3765e4b02871651"
  end
  resource "Jinja2" do
    url "https://files.pythonhosted.org/packages/7b/db/1d037ccd626d05a7a47a1b81ea73775614af83c2b3e53d86a0bb41d8d799/Jinja2-2.10.3.tar.gz"
    sha256 "9fe95f19286cfefaa917656583d020be14e7859c6b0252588391e47db34527de"
  end
  resource "MarkupSafe" do
    url "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz"
    sha256 "29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b"
  end
  resource "pycparser" do
    url "https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz"
    sha256 "a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3"
  end
  resource "PyYAML" do
    url "https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz"
    sha256 "b4bb4d3f5e232425e25dda21c070ce05168a786ac9eda43768ab7f3ac2770955"
  end
  resource "six" do
    url "https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz"
    sha256 "70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9"
  end
```

Then update the matching resource blocks in the formula with the output from `homebrew-pypi-poet`. (And add any missing ones, don't add ansible as a resource since this is the formula we're updating.)

**Comment by samford** [comment]
> How do I update the dependencies?

Just to keep you up to date, I've been discussing how to go about this with other maintainers and writing up some comprehensive instructions on how to update `ansible`'s resource blocks. Doing this properly is a little tricky the first time you attempt it but I don't think it's too difficult to understand with some guidance. The forthcoming explanation will benefit anyone who works on updating Python formulae and I wanted to make sure to take the time to get it right (in case we reference it in the future).

Anyway, hang tight for the moment but know that I'll have a proper guide for you in due time!

**Comment by samford** [comment]
This took a bit longer than expected, since there are some resources that end up being removed when following these instructions and I had to spend time researching them.  In the end, I wasn't able to account for a number of the packages but it would also take quite a long time to go through Ansible, as well as all of the listed dependencies, and try to determine whether the packages really aren't used _anywhere_.

After discussing the situation with other maintainers, as well as our project lead, we decided it was best to avoid removing any resources for the moment.  With this in mind, I made sure the instructions explain how to work around `homebrew-pypi-poet` not including all the resources that are currently in this formula.


## Updating Resource Blocks in Ansible

Basically, you need to install the main packages used in this formula ([listed above the resource blocks in this case](https://github.com/Homebrew/homebrew-core/blob/fdf0a3d74e5512838d50f65392968cd477dc1117/Formula/ansible.rb#L26-L46)) using `pip3` and then use [`homebrew-pypi-poet`](https://github.com/tdsmith/homebrew-pypi-poet) to compute the combined resource blocks (omitting the `ansible` resource block, since that's handled in the main part of the formula).  We update the resources in this way because we want to identify the correct resource versions that the package(s) in the formula ask for, not just the newest version from PyPI.

If you're familiar with [`virtualenvwrapper`](https://virtualenvwrapper.readthedocs.io), you can do the following steps within a temporary environment but I can't really help with this.  I don't use Python very often, so I typically just install the packages and then remove them all afterward.  If you have any other packages installed via `pip3`, you'll probably want to figure out how to do this in a temporary environment (to keep things tidy for yourself).

Anyway, the workflow goes a little like this:

### Generate the New Resource Blocks

1. Install the packages listed in the formula using `pip3`: `pip3 install -U ansible docker-py python-neutronclient shade pywinrm kerberos xmltodict boto boto3 botocore apache-libcloud python-keyczar passlib zabbix-api junos-eznc jxmlease dnspython pysphere python-consul requests-credssp openshift pexpect`

2. Install `homebrew-pypi-poet`: `pip3 install -U homebrew-pypi-poet`

3. Run `poet` with the packages listed in the formula: `poet ansible -a docker-py -a python-neutronclient -a shade -a pywinrm -a kerberos -a xmltodict -a boto -a boto3 -a botocore -a apache-libcloud -a python-keyczar -a passlib -a zabbix-api -a junos-eznc -a jxmlease -a dnspython -a pysphere -a python-consul -a requests-credssp -a openshift -a pexpect`


### Collect New Versions for Other Packages in the Formula

As mentioned above, there are a number of resources that aren't accounted for when running `poet` above, so we need to handle them manually. From my own testing, these are the packages that are currently in the formula but weren't installed when we ran `pip` earlier:

* `asn1crypto`
* `backports.ssl_match_hostname`
* `contextlib2`
* `deprecation`
* `funcsigs`
* `ipaddress`
* `monotonic`
* `packaging`
* `subprocess32`
* `unicodecsv`

You can run `poet -s <package_name>` with each of these to get a resource block for the latest version.  I don't know what these packages are related to (they were mostly added in typical Ansible version updates), so we can only assume the newest version is the most appropriate.


### Replace the Old Resource Blocks

1. Replace the resources in the formula using the new resources from `poet` and the other resources we generated manually.  Be careful when you do this, as you want to make sure to put the resource blocks in the same place as before and avoid overwriting any other changes that might be nested in or between resources.  Please don't copy and paste resources in large chunks because there are some manual modifications in the current formula that would be overwritten (e.g., the patch in the `pycrypto` resource block).  Also, be sure you copy any new resources from `poet`, as there are a couple new packages this time around.

2. Check the diff for your changes in Git and make sure you didn't remove any packages or overwrite other code in the process of updating the resource blocks.

3. Save the changes to the formula.


### Sort the Formula's Resource Blocks

1. Run `poet_lint $(brew formula ansible)` to obtain a sorted list of the resources.  Note that this puts all the resources in the formula together, even though some are separated in the formula near the top.

2. Integrate this list of resources into the formula like before, making sure to properly deal with the resources that are above the main list (i.e., pbr/pytz, cryptography/idna/pyOpenSSL).

3. Check the diff for your changes in Git again, to make sure you've done everything correctly up to this point.


### Install, Audit, Test

Ansible takes a while to build from source, so I usually like to run an audit first (`brew audit --strict ansible`) before installing the formula, to catch errors and save myself from wasting time.  We also run an audit after installation, so it's up to you.

1. Reinstall `ansible`, building it from source: `brew reinstall --build-from-source ansible`.  You can pass the `--verbose` flag if you want to watch everything that happens behind the scenes. [You can also use short versions of the flags (`-s` to build from source and `-v` for verbose or `-sv` for both).

2. If there are any errors, make any necessary changes in the formula and try again.

3. If the formula installs without errors, run a strict audit: `brew audit --strict --online ansible`.  If any errors are returned, make changes in the formula to address them (and start from the beginning of this section again).

4. If the audit doesn't return any errors, run a test: `brew test ansible`.  If any errors occur during the test, we have a problem somewhere that needs to be addressed.


### Final Steps

1. Please add a `  #   pexpect (expect module support)` line at the end of the list of packages above the resources, so anyone who edits this formula in the future will know to also include `pexpect`.  The previous commits adding `pexpect` and `ptyprocess` (to support Ansible's expect module) didn't note this requirement in the comments and I only discovered it while researching.

3. If the audit and test run without errors, update the PR with these changes.  In this case, the PR should only have one commit when you're finished (not another commit after the existing one).

2. Clean up any mess that you've made locally in the process of this update (e.g., uninstall `ansible`, switch back to the master branch, install `ansible` *not* from source (if you use it regularly), run `brew cleanup`, etc.).


## Closing

I may have overlooked some things but this is what I've come up with in relation to my own workflow and from discussions with other maintainers.  This process may be a bit daunting the first time you go through it but hopefully these instructions help.

Let me know if you have any questions along the way or if anything is unclear.  I've worked through this update myself while creating these instructions, so I can review your changes afterward to make sure everything's good.

In the future, we may be able to avoid this lengthy process if someone is able to modify the formula to use `pip` in place of all these resource blocks (while still accounting for all the packages currently in the formula). If anyone wants to try their hand at that, please feel free.

**Comment by apple4ever** [comment]
Great instructions! I will work through this in the next few days.

Once that's done, I'll try to do the `pip` tasks you mentioned in your last paragraph, though that may take more time and will have to wait until Ansible 2.9.6 or 2.10 comes out, because I'd like to get this version out now.

I'll let you know how it goes!

**Comment by samford** [comment]
Ansible 2.9.6 was released yesterday and I thought I would save you some trouble by creating a PR for the new version along with the necessary resource block updates (#51212). You at least have a guide now for handling this in the future, so please feel free to try your hand at this again when a new version comes along and you have the time.

For what it's worth, you can work on converting the `ansible` formula to use `pip` without having to wait for a new version to release (though it _is_ easier on our CI to handle these two tasks together, if possible). I'm not terribly familiar with how to convert a Python formula from using resource blocks to `pip` but you may get an idea of how to handle this by searching for other formulae that use it.

**Comment by apple4ever** [comment]
Ah great thanks. I will still try this on 2.9.5 and compare to yours to make sure I did it right, but then close the PR. 

I will work on the `pip` conversion in the future too

**Pull request closed without merging**
