### PR TITLE
Cake 0.10.1

### PR DESCRIPTION
**Pull request by gep13**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

For the last two, I don't have a Mac to test it on, so no, these have not been done.  I haven't done this for the last three submissions for the same formula.  Is this going to be a requirement going forward?

Thanks!

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/c60e3855aeec85ca4e57e12ecef47c8d61abf7a8. Thank you for another contribution to Homebrew @gep13! :smiley:.

> . I haven't done this for the last three submissions for the same formula. Is this going to be a requirement going forward?

`brew audit --strict --online` isn't a requirement on _existing formulae_ going forwards, no. This doesn't even have a build process as such, so there wouldn't be much value _in this case_ of it being built locally, even though we encourage people to test it that way prior to submission.

**Comment by gep13** [comment]
@DomT4 ok, thanks for letting me know.  The only viable option for me, i.e. no Mac, would be to use something like Bitrise.io, to run the commands locally after I create the PR.  That is something I can look at, if additional validation is required.

**Comment by DomT4** [comment]
You could potentially employ Travis upstream to test the Homebrew script for you in advance, but as long as you can help fix any errors that occur here, and there haven't been any to date, I'm happy for you to keep doing what you're doing.

**Comment by gep13** [comment]
@DomT4 perfect :+1:

**Comment by gep13** [comment]
@DomT4 thank you for your continued support!

**Pull request merged**
