### PR TITLE
bilix 0.18.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/bin/bilix info https://www.bilibili.com/video/av20203945/
  INFO     Directory videos not exists, auto created                              
  
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/bin/bilix", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/cli/main.py", line 374, in main
      loop.run_until_complete(cor)
    File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/asyncio/base_events.py", line 6[53](https://github.com/Homebrew/homebrew-core/actions/runs/5576975395/jobs/10189742481?pr=136811#step:4:54), in run_until_complete
      return future.result()
             ^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/sites/bilibili/informer.py", line 88, in temp
      await informer.info_key(key)
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/sites/bilibili/informer.py", line 23, in info_key
      await self.parse_url(key)(self, key)
    File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/sites/bilibili/informer.py", line 48, in info_video
      cors = [ensure_size(m) for m in dash.videos] + [ensure_size(m) for m in dash.audios]
                                      ^^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'videos'
```

**Comment by linbuxiao** [comment]
I tried to use homebrew's docker image to reproduce the problem:

1. docker run -it homebrew/brew
2. copy new bilix.rb file into container
3. HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug bilix.rb
4. bilix info https://www.bilibili.com/video/av20203945/
image
It works fine.

5. brew config in container
```bash
linuxbrew@550100b4c560:~$ brew config
HOMEBREW_VERSION: 4.0.28-110-g6b012b6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6b012b6592c97a6564010cecd9ec121b64f89bd4
Last commit: 15 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 13e3061feeaba4de35b1e3015c664c41332f0a62
Core tap last commit: 16 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit unknown_0x0_0x0
Clang: N/A
Git: 2.41.0 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.3.12-orbstack-00209-ga2cd8129a099 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
==> Downloading https://formulae.brew.sh/api/formula.jws.json
####################################################################################################################################################################### 100.0%
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

The question now is, is there a difference between the environment in the homebrew image and the ci?

**Comment by chenrui333** [comment]
I also try some test tomorrow.

**Comment by chenrui333** [comment]
I can actually reproduce this on the linux runner, 

```
  File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/sites/bilibili/informer.py", line 48, in info_video
    cors = [ensure_size(m) for m in dash.videos] + [ensure_size(m) for m in dash.audios]
                                    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'videos'
```

**Comment by chenrui333** [comment]
still the same issue

```
  File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/sites/bilibili/informer.py", line 48, in info_video
    cors = [ensure_size(m) for m in dash.videos] + [ensure_size(m) for m in dash.audios]
                                    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'videos'
```

**Comment by linbuxiao** [comment]
> still the same issue
> 
> ```
>   File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/sites/bilibili/informer.py", line 48, in info_video
>     cors = [ensure_size(m) for m in dash.videos] + [ensure_size(m) for m in dash.audios]
>                                     ^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'videos'
> ```


This appears to be a network issue. When I use another country's network via VPN, there is a probability that getting the video will fail.

**Comment by chenrui333** [comment]
> > still the same issue
> > ```
> >   File "/home/linuxbrew/.linuxbrew/Cellar/bilix/0.18.4/libexec/lib/python3.11/site-packages/bilix/sites/bilibili/informer.py", line 48, in info_video
> >     cors = [ensure_size(m) for m in dash.videos] + [ensure_size(m) for m in dash.audios]
> >                                     ^^^^^^^^^^^
> > AttributeError: 'NoneType' object has no attribute 'videos'
> > ```
> 
> This appears to be a network issue. When I use another country's network via VPN, there is a probability that getting the video will fail.

I actually directly run the command inside the action runner, and I can get the same failure (unfortunately, I dont have a linux box to try on)

**Comment by linbuxiao** [comment]
How can I change the test case if the video downloader is not working properly in linux environment due to network problem?

**Comment by chenrui333** [comment]
Since we are able to manually run the `bilix info` in the linux runtime, let's skip the CI test for now. and get it rolled out.

**Comment by chenrui333** [comment]
> How can I change the test case if the video downloader is not working properly in linux environment due to network problem?

Let's skip the linux CI check then (there are sometimes the linux CI does not work properly), I can followup with some manual checks on the linux action runners.

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
