### PR TITLE
platformio 3.0.1

### PR DESCRIPTION
**Pull request by ivankravets**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Thanks!

### CODE REVIEW

**Comment by zmwangx** [comment]
Failed on Mavericks since setuptools bundled with system Python is too old:

```python
pkg_resources.VersionConflict: (setuptools 0.6c12dev-r88846 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=0.8'))
```

Maybe use our own Python?

```ruby
depends_on :python if MacOS.version <= :mavericks
```

**Comment by zmwangx** [comment]
CC @tdsmith

**Comment by ivankravets** [comment]
I use your guidelines and tested on my Mac. Why does it work for me? Very strange :(

**Comment by zmwangx** [comment]
You mean it works on your Mavericks machine/box? It could be using more up-to-date setuptools.

**Comment by ivankravets** [comment]
I got it :( PlatformIO 3.0 depends on a new package [python-semanticversion](https://github.com/rbarrois/python-semanticversion). I've just take a look at their `setup.py` and they really depend on [setuptools >=0.8](https://github.com/rbarrois/python-semanticversion/blob/master/setup.py#L54). Very strange :(

Can we add dependency on new setuptools to Formula?

**Comment by zmwangx** [comment]
> Very strange :(

It's fine, we know what the problem is so it should be easy to fix.

> Can we add dependency on new setuptools to Formula?

Our brewed Python has setuptools 23.1.0, which is why I'm proposing to use that on Mavericks, but I'm personally not sure if `depends_on :python if MacOS.version <= :mavericks` is the right thing because I typically don't work on legacy systems. Another option is to vendor setuptools in the formula, but I'm not sure if setuptools could bootstrap itself; things might get complicated. I have CC'ed our in-house Python expert so it will be sorted out.

---

By the way, I think this formula could be migrated to using the relatively new `virtualenv_install_with_resources`.

**Comment by zmwangx** [comment]
This might be a worthy read: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md.

**Comment by ivankravets** [comment]
> I have CC'ed our in-house Python expert so it will be sorted out.

Thanks, let's wait for @tdsmith

**Comment by ilovezfs** [comment]
@zmwangx we vendor setuptools all the time
```
Josephs-MacBook-Pro:Formula joe$ ag setuptools|grep url
aws-elasticbeanstalk.rb:19:    url "https://files.pythonhosted.org/packages/32/3c/e853a68b703f347f5ed86585c2dd2828a83252e1216c1201fa6f81270578/setuptools-26.1.1.tar.gz"
cassandra.rb:19:    url "https://files.pythonhosted.org/packages/7a/a8/5877fa2cec00f7678618fb465878fd9356858f0894b60c6960364b5cf816/setuptools-24.0.1.tar.gz"
certbot.rb:23:    url "https://pypi.python.org/packages/13/e8/35d9c7528b3c266a17e888bea1e02eb061e9ab6cdabc7107dfb7da83a1d2/setuptools-21.2.1.tar.gz"
conan.rb:18:    url "https://pypi.python.org/packages/source/s/setuptools/setuptools-20.9.0.tar.gz"
docker-compose.rb:24:    url "https://files.pythonhosted.org/packages/9c/25/fa63da717a694ecf3bdb27f438450f535cdcabd77a955b5b05113f1abd11/setuptools-25.1.1.tar.gz"
euca2ools.rb:28:    url "https://pypi.python.org/packages/source/s/setuptools/setuptools-15.0.tar.gz"
mitmproxy.rb:26:    url "https://pypi.python.org/packages/5b/6e/a4bf49ddc41f144fd511f24c096dfa7600bffaf348563e08ef381dd6323e/setuptools-21.2.2.tar.gz"
protobuf.rb:54:    url "https://pypi.python.org/packages/source/s/setuptools/setuptools-20.9.0.tar.gz"
pypy.rb:31:    url "https://pypi.python.org/packages/32/3c/e853a68b703f347f5ed86585c2dd2828a83252e1216c1201fa6f81270578/setuptools-26.1.1.tar.gz"
pypy3.rb:21:    url "https://pypi.python.org/packages/source/s/setuptools/setuptools-19.4.tar.gz"
python.rb:45:    url "https://files.pythonhosted.org/packages/9f/7c/0a33c528164f1b7ff8cf0684cf88c2e733c8ae0119ceca4a3955c7fc059d/setuptools-23.1.0.tar.gz"
python3.rb:56:    url "https://files.pythonhosted.org/packages/9f/32/81c324675725d78e7f6da777483a3453611a427db0145dfb878940469692/setuptools-25.2.0.tar.gz"
sops.rb:95:    url "https://pypi.python.org/packages/source/s/setuptools/setuptools-20.8.1.tar.gz"
```

**Comment by zmwangx** [comment]
@ilovezfs Cool, so looks like `setuptools` can bootstrap itself and subsequent runs of `setup_install_args` will pick it up.

**Comment by ivankravets** [comment]
I added setuptool to requirements list

**Comment by zmwangx** [comment]
Why 21.2.1, out of interest?

**Comment by ivankravets** [comment]
I found it here https://github.com/Homebrew/homebrew-core/blob/master/Formula/certbot.rb#L22

**Comment by zmwangx** [comment]
Okay whatever.

**Comment by ilovezfs** [comment]
current is
```
iMac-TMP:~ joe$ poet --single setuptools
  resource "setuptools" do
    url "https://files.pythonhosted.org/packages/32/3c/e853a68b703f347f5ed86585c2dd2828a83252e1216c1201fa6f81270578/setuptools-26.1.1.tar.gz"
    sha256 "475ce28993d7cb75335942525b9fac79f7431a7f6e8a0079c0f2680641379481"
  end
```

**Comment by zmwangx** [comment]
Could you please also migrate to `virtualenv_install_with_resources` as I mentioned above? (See https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md#installing.)

@ilovezfs From my understanding that's now considered stable and recommendable, right?

**Comment by ilovezfs** [comment]
@zmwangx yes. you just need to make sure it any non-boilerplate actually makes it over to the updated version and that the commit subject is "foo: use new virtualenv feature` or if it's a new formula or version bump, then the commit subject is the usual standard one and the first line of the commit message is `use new virtualenv feature`.

**Comment by ilovezfs** [comment]
```
class Platformio < Formula
  include Language::Python::Virtualenv

  desc "Ecosystem for IoT development (Arduino and ARM mbed compatible)"
  homepage "http://platformio.org"
  url "https://files.pythonhosted.org/packages/8b/55/456733321ed1177f4d3dce533347fb4b7507ed14e682aa1bed4ebd2b84cf/platformio-3.0.1.tar.gz"
  sha256 "55aa64adc759344d6f8799efdceb169a6e27320dc3efd7842e347ea211c31012"

  bottle do
    cellar :any_skip_relocation
    sha256 "5d45f91af97d9f33506242698c46aedda6980533ce47c27de877214bf12a79ee" => :el_capitan
    sha256 "ff3353c2c28952b50d27031555fbe7c33bf94c517725f40feee2bcdea9f37d50" => :yosemite
    sha256 "4bfd207f3c466e00fab1f4136c4cc9a28aa0759cebd5b4850eda96d42731dac0" => :mavericks
  end

  depends_on :python if MacOS.version <= :snow_leopard

  resource "setuptools" do
    url "https://files.pythonhosted.org/packages/32/3c/e853a68b703f347f5ed86585c2dd2828a83252e1216c1201fa6f81270578/setuptools-26.1.1.tar.gz"
    sha256 "475ce28993d7cb75335942525b9fac79f7431a7f6e8a0079c0f2680641379481"
  end

  resource "bottle" do
    url "https://files.pythonhosted.org/packages/d2/59/e61e3dc47ed47d34f9813be6d65462acaaba9c6c50ec863db74101fa8757/bottle-0.12.9.tar.gz"
    sha256 "fe0a24b59385596d02df7ae7845fe7d7135eea73799d03348aeb9f3771500051"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/b7/34/a496632c4fb6c1ee76efedf77bb8d28b29363d839953d95095b12defe791/click-5.1.tar.gz"
    sha256 "678c98275431fad324275dec63791e4a17558b40e5a110e20a82866139a85a5a"
  end

  resource "colorama" do
    url "https://files.pythonhosted.org/packages/f0/d0/21c6449df0ca9da74859edc40208b3a57df9aca7323118c913e58d442030/colorama-0.3.7.tar.gz"
    sha256 "e043c8d32527607223652021ff648fbb394d5e19cba9f1a698670b338c9d782b"
  end

  resource "lockfile" do
    url "https://files.pythonhosted.org/packages/17/47/72cb04a58a35ec495f96984dddb48232b551aafb95bde614605b754fe6f7/lockfile-0.12.2.tar.gz"
    sha256 "6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799"
  end

  resource "pyserial" do
    url "https://files.pythonhosted.org/packages/3c/d8/a9fa247ca60b02b3bebbd61766b4f321393b57b13c53b18f6f62cf172c08/pyserial-3.1.1.tar.gz"
    sha256 "d657051249ce3cbd0446bcfb2be07a435e1029da4d63f53ed9b4cdde7373364c"
  end

  resource "requests" do
    url "https://files.pythonhosted.org/packages/2e/ad/e627446492cc374c284e82381215dcd9a0a87c4f6e90e9789afefe6da0ad/requests-2.11.1.tar.gz"
    sha256 "5acf980358283faba0b897c73959cecf8b841205bb4b2ad3ef545f46eae1a133"
  end

  resource "semantic_version" do
    url "https://files.pythonhosted.org/packages/8e/0e/33052dd97ab9d07dae8ddffcfb2740efe58c46d72efbc060cf6da250439f/semantic_version-2.5.0.tar.gz"
    sha256 "3baad35dcb074a49419539cea6a33b484706b6c2dd03f05b67763eba4c1bb65c"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    system bin/"platformio"
    system bin/"pio"
  end
end
```

**Comment by ivankravets** [comment]
@ilovezfs Thanks a lot!!! I've just updated formula.

**Comment by ilovezfs** [comment]
you're welcome

**Comment by zmwangx** [comment]
Merged as 6f8ff2e. Thank you for your contribution to Homebrew! For future reference, please squash your commits.

**Comment by ivankravets** [comment]
@zmwangx  Thank you

**Comment by tdsmith** [comment]
Oops, sorry I missed this discussion. Fwiw the virtualenv provides a recent
setuptools automatically but there's no harm to installing it again :)

**Comment by zmwangx** [comment]
@tdsmith Thanks, will keep that in mind next time.

**Pull request closed without merging**
