### PR TITLE
ppsspp: depend on `libpng` only on Intel

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This formula has no linkage with `libpng`. Also, the build uses only [the `libpng` headers](https://github.com/hrydgard/ppsspp/blob/52fd81129971def1b30df1533ebe8d42e16346cf/CMakeLists.txt#L985-L989).

### CODE REVIEW

**Comment by carlocab** [comment]
Huh. That's weird. There's linkage on Linux.

**Comment by cho-m** [comment]
I think it is using bundled copy on ARM due to version
https://github.com/hrydgard/ppsspp/blob/v1.13/CMakeLists.txt#L978-L983
```cmake
# Arm platforms require at least libpng17.
if(ANDROID OR ARMV7 OR ARM64 OR ARM OR IOS)
	set(PNG_REQUIRED_VERSION 1.7)
else()
	set(PNG_REQUIRED_VERSION 1.6)
endif()
```

**Comment by carlocab** [comment]
Hmm, right, missed that. Why do they need a newer version though?

**Comment by cho-m** [comment]
Looks like originally to fix iOS https://github.com/hrydgard/ppsspp/commit/85c42e69323b39899a67c4440d28262ee2ec5d16

Another ref: https://github.com/hrydgard/ppsspp/pull/12748#issuecomment-602247386

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
