### PR TITLE
gcc@7 7.5.0

### PR DESCRIPTION
**Pull request by fxcoudert**
New version released

### CODE REVIEW

**Comment by fxcoudert** [comment]
Failing on macOS 10.15 because of a Catalina SDK bug reported as FB7338312. Basically, a faulty if/else logic leads to `__OSX_AVAILABLE_STARTING` not being defined at all with non-clang compilers (like GCC).

We could use GCC's fixinclude mechanism to avoid it (as done for the main GCC formula: https://github.com/Homebrew/homebrew-core/pull/44762) but it appears that this will be fixed in Xcode 11.3, so maybe the simpler solution for now is to wait.

**Comment by chenrui333** [comment]
20:48:37 ==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/master/gcc%407/gcc7-xcode10.2.patch
20:48:37 cp -p /Users/brew/Library/Caches/Homebrew/downloads/e2986ba6be3664b18519b65bd6812afb2df563f08d8351fa6c79d98f125dcf15--gcc7-xcode10.2.patch /private/tmp/gcc@7--patch-20191124-49994-1jw69cz/gcc7-xcode10.2.patch
20:48:37 Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/e2986ba6be3664b18519b65bd6812afb2df563f08d8351fa6c79d98f125dcf15--gcc7-xcode10.2.patch
20:48:37 ==> Verifying e2986ba6be3664b18519b65bd6812afb2df563f08d8351fa6c79d98f125dcf15--gcc7-xcode10.2.patch checksum
20:48:37 ==> Patching
20:48:37 ==> Applying gcc7-xcode10.2.patch
20:48:37 patch -g 0 -f -p1 -i /private/tmp/gcc@7--patch-20191124-49994-1jw69cz/gcc7-xcode10.2.patch
20:48:37 patching file fixincludes/fixincl.x
20:48:37 Hunk #1 FAILED at 2.
20:48:37 Hunk #2 FAILED at 15.
20:48:37 Hunk #3 succeeded at 3470 (offset 208 lines).
20:48:37 Hunk #4 FAILED at 10389.
20:48:37 Hunk #5 FAILED at 10472.
20:48:37 Hunk #6 succeeded at 11054 with fuzz 2 (offset 238 lines).
20:48:37 4 out of 6 hunks FAILED -- saving rejects to file fixincludes/fixincl.x.rej
20:48:37 patching file fixincludes/inclhack.def

Looks like failed to apply the patches for Mojave and Catalina

**Comment by Bo98** [comment]
Unlike gcc@8, the patch _is_ ok the remove here as it is included in 7.5.0.

The release schedules aren't in sync with each other.

**Comment by fxcoudert** [comment]
Hum… I could have sworn without the patch it was also failing (before I force-pushed). Well, let's see again.

**Pull request closed without merging**
