### PR TITLE
phpstan: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by nandahkrishna**
See #75943.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by nandahkrishna** [comment]
```
e9412fe4c1df1f93873d5a2a457269a2dae86cdd1271dcf0b5c6cd59b45acb23  phpstan--0.12.85.arm64_big_sur.bottle.tar.gz
89a53b12d107be98a3d0195480c649599e958977881b8de8dcebe4392a5dfeb6  phpstan--0.12.85.big_sur.bottle.tar.gz
89a53b12d107be98a3d0195480c649599e958977881b8de8dcebe4392a5dfeb6  phpstan--0.12.85.catalina.bottle.tar.gz
89a53b12d107be98a3d0195480c649599e958977881b8de8dcebe4392a5dfeb6  phpstan--0.12.85.mojave.bottle.tar.gz
```

The difference is because of `@@HOMEBREW_PREFIX@@`.

**Comment by carlocab** [comment]
Just `inreplace` `/usr/local/ to `HOMEBREW_PREFIX` here, I think.

**Comment by nandahkrishna** [comment]
```
PHP Fatal error:  Uncaught PharException: phar "/opt/homebrew/Cellar/phpstan/0.12.85/bin/phpstan" SHA1 signature could not be verified: broken signature in /opt/homebrew/Cellar/phpstan/0.12.85/bin/phpstan:4
```

I think `phar` files shouldn't be modified with `inreplace`s.

**Comment by SMillerDev** [comment]
Nope, most of them are signed "binaries"

**Comment by Bo98** [comment]
If there's a way to detect if they are "signed", we should probably be skipping relocation on `phar` files.

(Though there's still the issue of how to tell `brew` if it should be `cellar: :any` - the `/usr/local` reference will make it not so and thus we won't be able to create a `all` bottle.)

**Comment by SMillerDev** [comment]
Why does it even have a cellar reference? It's a single "binary" file. Nothing is done in terms of installing so brew should just be able to put the file some other place right?

**Comment by Bo98** [comment]
`brew` pretty aggressively checks for `/usr/local` references and assumes that means it is referring to the Homebrew prefix. We can perhaps adjust this a bit.

**Comment by SMillerDev** [comment]
This will check if a phar file is signed (`./script file.phar`). Unfortunately, it won't work unless the file ends in `.phar` because PHP is a mess of a language at times 😄 

```php
#!/usr/bin/env php
<?php
$phar = new Phar($argv[1]);
if ($phar->getSignature() === false) {
    echo 'unsigned';
    return;
}
echo $phar->getSignature()['hash'];
```

**Pull request closed without merging**
