### PR TITLE
fuse-overlayfs 1.6 (new formula)

### PR DESCRIPTION
**Pull request by henryhchchc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
Is this even functional? This kernel module which is mentioned in the test, is it available after installation and loadable from Homebrew prefix?

**Comment by henryhchchc** [comment]
> Is this even functional? This kernel module which is mentioned in the test, is it available after installation and loadable from Homebrew prefix?

It requires root permission to load the enable loading the kernel module. As the previous test execution shows, the module is not loaded in the CI, but it is loaded by default on most Linux distributions.

**Comment by danielnachun** [comment]
Please squash your commits here as well.

**Comment by henryhchchc** [comment]
👌

**Comment by danielnachun** [comment]
Is this trying to install outside of the cellar?  It looks like it's installing into `/` instead of the cellar directory:
```
 system "autoreconf", "-fis"
 system "./configure", "--prefix=/", "--sbindir=/sbin"
 system "make"
 system "make", "install", "DESTDIR=#{prefix}"
```
This is passing CI which doesn't have `sudo` access so maybe I'm misunderstanding this?  But generally I think we don't want formulae to modify files outside of `$HOMEBREW_PREFIX`.

**Comment by gromgit** [comment]
The `configure`/`DESTDIR` combo strongly suggests a staged install that's typical of Autotools-managed projects, i.e. all embedded paths are referenced from a (virtual) `/`, but physically installed under `$HOMEBREW_PREFIX`.

**Comment by danielnachun** [comment]
Ah that makes sense, I've seen that before.  Thanks for clarifying.

**Review by danielnachun — APPROVED** [review]

**Comment by henryhchchc** [comment]
Actually the install will concatenate the `DESTPATH` and the value set by `--prefix`, and install the binaries to that location. I adopted the configuration from [ArchLinux PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/fuse-overlayfs/trunk/PKGBUILD).

Would it be better if we set `--prefix=#{prefix}` and set `DESTDIR` to `/`?

**Comment by gromgit** [comment]
> Actually the installer will concatenate the `DESTPATH` and the value set by `--prefix`, and install the binaries to that location. I adopted the configuration from [ArchLinux PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/fuse-overlayfs/trunk/PKGBUILD).

For future reference, copying the config paths verbatim from _system_ package managers like `PKGBUILD` and `apt` is generally the wrong thing to do, because the latter all assume installation under the _real_ root, and therefore base all internal paths under `/` instead of `$HOMEBREW_PREFIX`.

> Would it be better if we set `--prefix=#{prefix}` and set `DESTDIR` to `/`?

The general rule of thumb for autotools-based installs in Homebrew is:
* `configure --prefix=#{prefix}`
* don't specify `DESTDIR` at all

A quick look at the `fuse-overlayfs` sources suggests that this should've been the way to configure it (also, `--sbindir` should not have been needed even in your original formula, unless the source is doing something strange). Probably worth fixing it, though I'm not sure what the protocol for that is, now that this PR has been committed.

**Comment by danielnachun** [comment]
It can just be a revision.  I wasn't sure if we had a general rule about this, but I think @gromgit is right.  Luckily this can be fixed easily.

**Comment by danielnachun** [comment]
Actually it doesn't even need a revision bump.  This can be made as a regular PR, because it won't change the binaries at all.

**Comment by gromgit** [comment]
It actually changes one baked-in path in `fuse-overlayfs`, so it's probably better to revision-bump (though I'm not sure how that path is used):
```
$ diff -u <(strings - ~/tmp/fuse-overlayfs/1.6/bin/fuse-overlayfs) <(strings - ~/tmp/fuse-overlayfs/1.6-root/bin/fuse-overlayfs)
--- /dev/fd/63	2021-07-23 13:49:06.575195787 +0800
+++ /dev/fd/62	2021-07-23 13:49:06.575195787 +0800
@@ -1,4 +1,5 @@
 /lib64/ld-linux-x86-64.so.2
+ j$|ow
 _ITM_deregisterTMCloneTable
 __gmon_start__
 _ITM_registerTMCloneTable
@@ -751,6 +752,7 @@
 mountpoint=%s
 plugins=%s
 fsync=%s
+//libexec/fuse-overlayfs
 %s/%s:%s
 fuse-overlayfs: stat upperdir
 /work
@@ -830,7 +832,6 @@
 fuse-overlayfs: cannot set nofile rlimit
 FUSE_OVERLAYFS_DISABLE_OVL_WHITEOUT
 fuse-overlayfs: cannot convert %s
-/home/aho/tmp/fuse-overlayfs/1.6/libexec/fuse-overlayfs
 fuse-overlayfs: cannot read lower dirs
 fuse-overlayfs: cannot read lower dirs
 fuse-overlayfs: cannot read upper dir
```

**Comment by danielnachun** [comment]
Nice catch!  @henryhchchc feel free to open a PR to fix this.  I'm also happy to do so since I missed this before committing the publishing the bottle.

**Comment by henryhchchc** [comment]
> Nice catch! @henryhchchc feel free to open a PR to fix this. I'm also happy to do so since I missed this before committing the publishing the bottle.

Sure, please find https://github.com/Homebrew/homebrew-core/pull/81860.

**Pull request closed without merging**
