### PR TITLE
hashcat 6.2.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`hashcat` test failure on `11-arm`

```
==> /private/tmp/hashcat-test-20210518-97762-mvyoen/hashcat --benchmark -m 0
hashcat (v6.2.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

No devices found/left.

Started: Tue May 18 18:38:50 2021

Stopped: Tue May 18 18:38:50 2021
Error: hashcat: failed
An exception occurred within a child process:
  BuildError: Failed executing: /private/tmp/hashcat-test-20210518-97762-mvyoen/hashcat --benchmark -m 0
```

**Comment by jdmartin** [comment]
So, I wonder how we can get this moving again?  The error "No devices found/left." is all about Hashcat not having a device to do hashing on.

In this video, you can see what happens when I try the test's way (CPU-only), my way (GPUs-only), and then a third way with a bad device specified... this third way looks exactly like the above error.

https://user-images.githubusercontent.com/1966209/119278699-cc045500-bbdb-11eb-8a2f-fe6526b06768.mov

As far as I can tell, the reason the 11-intel test passes is that it doesn't perform the benchmark test.  So, what can we do to resolve this?

**Comment by SMillerDev** [comment]
Preferably: find a way to fix the tests.

**Comment by jdmartin** [comment]
Right.  Seems the easiest way is to remove the benchmark attempts from the tests.  If we need something to prove it's installed correctly, `hashcat --help` exits with 0 even if I specify a bad option (So, `hashcat --help -D 3`). 

By contrast, as seen in the video above, `hashcat -b -m 0 -D 3` exits with 255.

Maybe `hashcat --help` could take the place of `hashcat --benchmark -m 0` in the above tests?

**Comment by SMillerDev** [comment]
We need a test that exercises the some of the functionality of the app. Version checks or usage checks (foo --version or foo --help) are not sufficient, as explained in the formula cookbook.

In most cases, a good test would involve running a simple test case: run #{bin}/foo input.txt.

- Then you can check that the output is as expected (with assert_equal or assert_match on the output of shell_output)
- You can also check that an output file was created, if that is expected: assert_predicate testpath/"output.txt", :exist?

Some advice for specific cases:

- If the formula is a library, compile and run some simple code that links against it. It could be taken from upstream's documentation / source examples.
- If the formula is for a GUI program, try to find some function that runs as command-line only, like a format conversion, reading or displaying a config file, etc.
- If the software cannot function without credentials, a test could be to try to connect with invalid credentials (or without credentials) and confirm that it fails as expected.
- Same if the software requires a virtual machine, docker instance, etc. to be running.

**Comment by jdmartin** [comment]
Thanks for the clarifications, and sorry not to have been more familiar with the formula cookbook.

So, here are the problems that have occurred:

- 10.14: 'The source URL https://hashcat.net/files/hashcat-6.2.1.tar.gz is not reachable'
-- Tested just now, and the download is fine.  So, likely a transient issue.
- 10.15: 'clLinkProgram(): CL_LINK_PROGRAM_FAILURE
              *Device #1: Kernel /private/tmp/hashcat-test-20210522-99006-msruld/OpenCL/shared.cl build failed.'
- 11-arm64: 'No devices found/left.'

Some suggestions (help definitely appreciated!):
- 10.14: Tested just now, and the download is fine.  So, likely a transient issue.  Try again?
- 10.15: This could potentially be fixed by modifiying the test.  I'm afraid I don't know the GitHub infrastructure well enough, but I think it might be helpful to try either `hashcat -b -m0 -d1` or `hashcat -b -m0 -O`.
- 11-arm64: My first instinct would be to try the same changes as above.  Some anecdotal observations ([one](https://hashcat.net/forum/thread-9833.html), [two](https://github.com/hashcat/hashcat/issues/2728)) suggests that appending `--force` may solve the issue.

Summary:
I'd recommend modifying line 31 of the [formula](https://github.com/Homebrew/homebrew-core/blob/11d3369762a7eccf2349eefc732ffe183cb0ba13/Formula/hashcat.rb).  I'm not sure what would really work best, so I would try changes in this order:

- system testpath/"hashcat --benchmark -m 0 -d1"
- system testpath/"hashcat --benchmark -m 0 -O"
- system testpath/"hashcat --benchmark -m 0 --force"

I'd prefer to avoid making further mistakes, so I'll wait for advice on how to proceed.  I'm happy to do what I can to help.  Thank you!

**Comment by SMillerDev** [comment]
> 10.15: This could potentially be fixed by modifiying the test. I'm afraid I don't know the GitHub infrastructure well enough, but I think it might be helpful to try either hashcat -b -m0 -d1 or hashcat -b -m0 -O.

I think the test should be modified too, the tests run in a Macstadium Orka VM if that helps you in any way. If we can't find a way to test succesfully we can always expect an error code and the output `No devices found/left.`

**Comment by jdmartin** [comment]
Thanks for the quick response!  I'll read up on Orka, and see if I can figure out what might be going wrong.  In the meantime, I'll see if tweaking the tests will yield any interesting/helpful results. :)

**Comment by SMillerDev** [comment]
Making a new PR is fine

**Pull request closed without merging**
