### PR TITLE
irssi 1.1.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by mistydemeo — COMMENTED** [review]
You should be able to remove the `inreplace`, which is the reason it failed; the commit made it into this release: https://github.com/irssi/irssi/commit/04497ed69d35cf44b0700437bf427f48dbc42871#diff-67e997bcfdac55191033d57a16d1408a

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by jalmansor** [comment]
Any update on this? It would be great for this to get resolved/merged considering the security fix. 

Sorry to nag :-/

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Test failing:

```
==> perl -e use Irssi
Can't locate Irssi.pm in @INC (you may need to install the Irssi module) (@INC contains: /usr/local/Cellar/irssi/1.1.2/lib/perl5/site_perl /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

**Pull request closed without merging**
