### PR TITLE
traefik 2.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by djerfy** [comment]
@chenrui333 Is it possible to keep compatibility with the old version? (ex: `brew install traefik@1.7.16`), else a lot of changes are mandatory (config).

**Comment by djerfy** [comment]
For the build error remove `node` and `yarn` dependencies and lines 26 to 30 (related with webui).

**Comment by chenrui333** [comment]
@djerfy, yeah, I think we might need to create a `traefik@1.7.16` formula. Does traefik 1.7 still get support?

**Comment by chenrui333** [comment]
> For the build error remove `node` and `yarn` dependencies and lines 26 to 30 (related with webui).

I dont quite understand why we need to remove the webui installation step? I think we just need to replace yarn step with npm one (yarn usage seems got deprecated), that should be it?

**Comment by djerfy** [comment]
> @djerfy, yeah, I think we might need to create a `traefik@1.7.16` formula. Does traefik 1.7 still get support?

I think that `traefik@1.7` will be good. There is still support on this version, I don't know for how long.



> > For the build error remove `node` and `yarn` dependencies and lines 26 to 30 (related with webui).
> 
> I dont quite understand why we need to remove the webui installation step? I think we just need to replace yarn step with npm one (yarn usage seems got deprecated), that should be it?

There has been a redesign the UI interface, these things are no longer needed. My tests are good locally.

**Comment by chenrui333** [comment]
Cool, I will just remove those lines then.

**Comment by djerfy** [comment]
> Cool, I will just remove those lines then.

Thanks. 
This command run Traefik with http (:80) and ui (:8080) entrypoints:

```bash
traefik --api=true --api.dashboard=true --api.debug=true --api.insecure=true --log.level=DEBUG --accesslog
```

**Comment by djerfy** [comment]
My git patch for Traefik v2.0.0:
```text
diff --git i/Formula/traefik.rb w/Formula/traefik.rb
index 5f1969a1d0..640906e513 100644
--- i/Formula/traefik.rb
+++ w/Formula/traefik.rb
@@ -1,9 +1,9 @@
 class Traefik < Formula
   desc "Modern reverse proxy"
   homepage "https://traefik.io/"
-  url "https://github.com/containous/traefik/releases/download/v1.7.16/traefik-v1.7.16.src.tar.gz"
-  version "1.7.16"
-  sha256 "3ff5316f26ba552d758f97fa645e43ffe2fc2078edd67c81e6ce7d5a171655e0"
+  url "https://github.com/containous/traefik/releases/download/v2.0.0/traefik-v2.0.0.src.tar.gz"
+  version "2.0.0"
+  sha256 "dc1da8bf5d56401cebc6a812c9f7865d2001e9a5fd8c2e9e4c7bee707ac8673f"
   head "https://github.com/containous/traefik.git"

   bottle do
@@ -15,19 +15,13 @@ class Traefik < Formula

   depends_on "go" => :build
   depends_on "go-bindata" => :build
-  depends_on "node" => :build
-  depends_on "yarn" => :build

   def install
+    ENV["GO111MODULE"] = "on"
     ENV["GOPATH"] = buildpath
     (buildpath/"src/github.com/containous/traefik").install buildpath.children

     cd "src/github.com/containous/traefik" do
-      cd "webui" do
-        system "yarn", "upgrade"
-        system "yarn", "install"
-        system "yarn", "run", "build"
-      end
       system "go", "generate"
       system "go", "build", "-o", bin/"traefik", "./cmd/traefik"
       prefix.install_metafiles
@@ -70,19 +64,33 @@ class Traefik < Formula
   test do
     require "socket"

-    web_server = TCPServer.new(0)
+    ui_server = TCPServer.new(0)
     http_server = TCPServer.new(0)
-    web_port = web_server.addr[1]
+    ui_port = ui_server.addr[1]
     http_port = http_server.addr[1]
-    web_server.close
+    ui_server.close
     http_server.close

     (testpath/"traefik.toml").write <<~EOS
-      [web]
-      address = ":#{web_port}"
-
-      [entryPoints.http]
-      address = ":#{http_port}"
+      [global]
+        checkNewVersion = false
+        sendAnonymousUsage = false
+      [serversTransport]
+        insecureSkipVerify = true
+      [entryPoints]
+        [entryPoints.http]
+          address = ":#{http_port}"
+        [entryPoints.traefik]
+          address = ":#{ui_port}"
+      [log]
+        level = "ERROR"
+        format = "common"
+      [accessLog]
+        format = "common"
+      [api]
+        insecure = true
+        dashboard = true
+        debug = true
     EOS

     begin
@@ -90,8 +98,11 @@ class Traefik < Formula
         exec bin/"traefik", "--configfile=#{testpath}/traefik.toml"
       end
       sleep 5
-      cmd = "curl -sIm3 -XGET http://localhost:#{web_port}/dashboard/"
-      assert_match /200 OK/m, shell_output(cmd)
+      cmd_http = "curl -sIm3 -XGET http://localhost:#{http_port}/"
+      assert_match /404 Not Found/m, shell_output(cmd_http)
+      sleep 1
+      cmd_ui = "curl -sIm3 -XGET http://localhost:#{ui_port}/dashboard/"
+      assert_match /200 OK/m, shell_output(cmd_ui)
     ensure
       Process.kill("HUP", pid)
     end
```

All tests are good for me, here audit:
```text
╰> brew audit --strict traefik
brew audit --strict traefik  6.28s user 1.45s system 89% cpu 8.642 total
```

And test:
```text
╰> brew test traefik
Testing traefik
INFO[0000] Configuration loaded from file: /private/tmp/traefik-test-20190917-89381-15r8kw4/traefik.toml
==> curl -sIm3 -XGET http://localhost:50664/
::1 - - [17/Sep/2019:17:02:39 +0000] "GET / HTTP/1.1" - - "-" "-" 1 - - 0ms
==> curl -sIm3 -XGET http://localhost:50663/dashboard/
```

**Comment by chenrui333** [comment]
@djerfy Applied your patch, thanks for the input. :)

**Comment by chenrui333** [comment]
meanwhile, can you submit a formula for `traefik@1.7.16`, appreciate it!!

**Comment by djerfy** [comment]
> meanwhile, can you submit a formula for `traefik@1.7.16`, appreciate it!!

Okay but you prefer `traefik@1.7.16` directly or `traefik@1.7` (for future releases in 1.7.xx)?

**Comment by chenrui333** [comment]
Sorry for getting back late on this, and thanks for opening the PR!

`traefik@1.7` would be a better choice :)

**Pull request closed without merging**
