### PR TITLE
yarn-completion 0.7.4 (new formula)

### PR DESCRIPTION
**Pull request by jasonkarns**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jasonkarns** [comment]
This completion script requires bash 4+ (which is almost implied by the use of bash-completion itself which depends on 4+). However, the CI tests seem to be running on the macOS default 3.2, thus causing the tests to fail. Suggestions? I'm not certain how to declare a specific _version_ in "depends_on", and even if I did, I'm not sure that would help with the travis test?

Another option is removing the test, but I know that's not desired. Any other suggestions?

**Comment by jasonkarns** [comment]
@fxcoudert agree. I'll be removing bash as a dep... Should I keep bash-completion as a dep? A cursory glance at other completion-only formula doesn't seem to indicate a pattern for including bash-completion as a dep. Opinions?

Regarding the test failure, I've submitted a PR (which has been merged) that makes the script source-able for bash 3.2. Once a new release is available, I'll update this PR which should make the tests green.

**Comment by jasonkarns** [comment]
This is ready to be re-opened and merged.

The upstream package has accepted my PR (and has cut a release including the changes) which means the script is now source-able on bash 3.2.

And I've removed bash as a dep in the formula as discussed.

@fxcoudert Are you able to re-open?

**Comment by jasonkarns** [comment]
bump

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/ffb3d7980dede35715f6c75fec9e1b7f009d0789. Thank you for your contribution to Homebrew @jasonkarns; we appreciate it! :smiley_cat:

**Pull request closed without merging**
