### PR TITLE
Remove redundant inreplace @@HOMEBREW_PREFIX@@

### PR DESCRIPTION
**Pull request by pkryger**
This functionality is now available in `Homebrew/brew`.

This is a follow up to https://github.com/Homebrew/homebrew-core/pull/195569,
https://github.com/Homebrew/homebrew-core/pull/193855, and
https://github.com/Homebrew/brew/pull/18613. The latter has been available since 4.4.3.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Thanks @pkryger! Looks good when CI is 🟢

**Comment by pkryger** [comment]
> Thanks @pkryger! Looks good when CI is 🟢

I wish it was green. Although, not sure what to do here. Appreciate your input.

* If I understood logs correctly `python-freethreading` fails to `brew link`. My understanding is that it conflicts with `python@3.13`, but I don't think this PR is a place to address this.  Anyway, the build continued after the error has been reported.
```
2024-11-01T10:24:03.6293041Z ##[error]The `brew link` step did not complete successfully
2024-11-01T10:24:03.6293803Z Could not symlink lib/libpython3.so
2024-11-01T10:24:03.6293970Z Target /home/linuxbrew/.linuxbrew/lib/libpython3.so
2024-11-01T10:24:03.6294166Z is a symlink belonging to python@3.13. You can unlink it:
2024-11-01T10:24:03.6294272Z   brew unlink python@3.13
2024-11-01T10:24:03.6294278Z 
2024-11-01T10:24:03.6294456Z To force the link and overwrite all conflicting files:
2024-11-01T10:24:03.6294683Z   brew link --overwrite python-freethreading
2024-11-01T10:24:03.6294689Z 
2024-11-01T10:24:03.6294813Z To list all files that would be deleted:
2024-11-01T10:24:03.6295025Z   brew link --overwrite python-freethreading --dry-run
2024-11-01T10:24:03.6295030Z 
```

* `swift` build on Linux has failed because lack of space (the last error in log). I believe this is what stopped the build.
```
  Errno::ENOSPC: No space left on device @ fptr_finalize_flush - /github/home/bottles/logs/swift/01.build-script
```

There's a few other failures in log (which I am not sure what to do about either), yet build continued after these errors were reported:
* `python@3.11`:
```
==> brew linkage --cached --test --strict python@3.11
==> FAILED
Full linkage --cached --test --strict python@3.11 output
  Indirect dependencies with linkage:
    libtirpc
Truncated linkage --cached --test --strict python@3.11 output
  Warning:   libtirpc
```
* `glib`
 ```
==> brew linkage --cached --test --strict glib
==> FAILED
Full linkage --cached --test --strict glib output
  Indirect dependencies with linkage:
    zlib
Truncated linkage --cached --test --strict glib output
  Warning:   zlib
```
* `python@3.10`
```
==> FAILED
Full linkage --cached --test --strict python@3.10 output
  Indirect dependencies with linkage:
    libtirpc
Truncated linkage --cached --test --strict python@3.10 output
  Warning:   libtirpc
```

**Comment by Bo98** [comment]
> There's a few other failures in log (which I am not sure what to do about either),

Oh and to clarify "Indirect dependencies" ones are warnings at the moment and wouldn't turn the CI red so they're expected for now.

**Comment by carlocab** [comment]
> This is a bug. The condition to us even accepting `python-freethreading` was it didn't conflict with `python@3.13`. I guess we never actually checked in the end.

I checked -- I just neglected to check Linux properly. My mistake; apologies. (If it helps, there is no conflict on macOS.)

**Comment by Bo98** [comment]
Ah that's good - no worries. Can easily iterate on that.

**Comment by carlocab** [comment]
#196376

**Pull request merged**
