### PR TITLE
clojure 1.9.0.348

### PR DESCRIPTION
**Pull request by puredanger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Note: added man pages.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@puredanger why not install the man pages with the install script?

**Comment by puredanger** [comment]
I could - wasn't sure if I knew in there where to install them to?

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> :clojure.f.man1
=> #<Pathname:/usr/local/Cellar/clojure/1.9.0.326/share/man/man1>
irb(main):002:0> :clojure.f.man
=> #<Pathname:/usr/local/Cellar/clojure/1.9.0.326/share/man>
irb(main):003:0> :clojure.f.man1.relative_path_from(:clojure.f.prefix)
=> #<Pathname:share/man/man1>
irb(main):004:0> 
```
Hopefully that helps :)

**Comment by ilovezfs** [comment]
@puredanger hopefully the install script can be enhanced to include the man pages for the next release. Shipping this as-is though

**Comment by puredanger** [comment]
Sorry, I've been offline all weekend. I'll update in the next rev - thanks!

**Pull request merged**
