### PR TITLE
istioctl 1.4.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
12:15:27 chmod -Rf +w /private/tmp/d20191211-54384-qy6dvz
12:15:27 ==> make istioctl
12:15:27 Building with your local toolchain.
12:15:27 ISTIO_OUT=/private/tmp/istioctl-20191211-54384-t9m0x2/out/darwin_amd64/release bin/init.sh
12:15:27 /private/tmp/istioctl-20191211-54384-t9m0x2/out/linux_amd64/debug /private/tmp/istioctl-20191211-54384-t9m0x2/src/istio.io/istio
12:15:27 Downloading Envoy: curl -fLSs https://storage.googleapis.com/istio-build/proxy/envoy-debug-a7b2578494d79fe098f0e99282e0236946562fa0.tar.gz to /private/tmp/istioctl-20191211-54384-t9m0x2/out/linux_amd64/debug/envoy-debug-a7b2578494d79fe098f0e99282e0236946562fa0
12:15:27 curl: (22) The requested URL returned error: 404 
12:15:27 make[1]: *** [/private/tmp/istioctl-20191211-54384-t9m0x2/out/darwin_amd64/release/istio_is_init] Error 22
12:15:27 make: *** [istioctl] Error 2

**Comment by cagataygurturk** [comment]
Hey @chenrui333 do you have an ETA for this?

**Comment by chenrui333** [comment]
@cagataygurturk catching up on this now.

**Comment by chenrui333** [comment]
Installed and tested locally on my Catalina machine, did not find any issue. Let's see how CI goes.

**Pull request closed without merging**
