### PR TITLE
fauna-shell 0.9.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Test fails:
```
==> /usr/local/Cellar/fauna-shell/0.9.3/bin/fauna add-endpoint https://endpoint1:8443
Endpoint Key: 
Endpoint Alias [endpoint1]: Error: Cannot read property 'headers' of undefined
==> /usr/local/Cellar/fauna-shell/0.9.3/bin/fauna list-endpoints
Error: No endpoints defined.
See fauna add-endpoint --help for more details.
Error: fauna-shell: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by chenrui333** [comment]
Submit the issue in the upstream repo.

**Comment by chenrui333** [comment]
waiting for the fix PR, https://github.com/fauna/fauna-shell/pull/14

**Comment by chenrui333** [comment]
PR got merged. Try the new release 0.9.4 now.

**Comment by chenrui333** [comment]
Should be good now, cc @SMillerDev @lembacon @Moisan

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Pull request closed without merging**
