### PR TITLE
groovy: fix groovysh on Java 18 and Apple Silicon

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #98584

### CODE REVIEW

**Comment by cho-m** [comment]
I guess another option would be to check every binary and see what is/isn't compatible with M1 and then remove incompatible ones & put in caveat list.

**Review by Bo98 — DISMISSED** [review]

**Comment by Bo98** [comment]
> I guess another option would be to check every binary and see what is/isn't compatible with M1

I suppose it depends how integral it is. If it's one minor component then maybe but if it's something major it'll be better to just force using Rosetta.

**Comment by cho-m** [comment]
Would need some user input on what is common workflow with Groovy. Especially if there are any users who are fine with current behavior and can work with just the compiler (`groovyc`) or GUI (`groovyConsole`).

If users are more likely to be confused over missing `groovysh`, then current approach may be best to avoid issues.

**Comment by Bo98** [comment]
If it's just REPL, I'm fine with removing just that part.

Though some day we also really should do something about these native Java components that really shouldn't be shipped prebuilt.

**Comment by cho-m** [comment]
On side note, `groovysh` also doesn't work as-is on x86_64 after we updated to Java 18 since it uses deprecated Security Manager and that causes an exception.

We either need to:
- Set `-Djava.security.manager=allow`
- Downgrade to Java 17.

**Comment by cho-m** [comment]
Reworked some code from #92477 to try to build `jansi-native` for `jline2` on macOS.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
