### PR TITLE
fmt 8.0.1 spdlog 1.9.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
all build issues with the revision bump, will take a look later.

**Comment by carlocab** [comment]
Most of the failures should be fixed by getting `spdlog` to build. See https://github.com/gabime/spdlog/issues/1975, https://github.com/gabime/spdlog/issues/1941

`watchman` is tricky. It doesn't build at all at the moment, so we probably have to wait until it gets an update that will allow it to build first.

**Comment by bayandin** [comment]
> Most of the failures should be fixed by getting `spdlog` to build. See [gabime/spdlog#1975](https://github.com/gabime/spdlog/issues/1975), [gabime/spdlog#1941](https://github.com/gabime/spdlog/issues/1941)

This was fixed by updating `spdlog` to 1.9.1 in this PR.

> `watchman` is tricky. It doesn't build at all at the moment, so we probably have to wait until it gets an update that will allow it to build first.

The only problem left is `watchman`: https://github.com/facebook/watchman/issues/930

**Comment by SMillerDev** [comment]
Watchman hasn't build for 2 months, I think we can try and disable it.

**Comment by carlocab** [comment]
`watchman` is vastly more popular (~40k installs-on-request per month) than any of the formulae it's blocking (no more than 1,000 monthly installs-on-request), though. We should try to fix it...

**Comment by cho-m** [comment]
> `watchman` is vastly more popular (~40k installs-on-request per month) than any of the formulae it's blocking (no more than 1,000 monthly installs-on-request), though. We should try to fix it...

I finally got around to working on `watchman` in #82474. At least the ARM CI is passing right now.

Since I am also working on Linux fixes, it may take a few more attempts if Linux CI fails.

**Comment by carlocab** [comment]
`watchman` fixed in #82474. Thanks, @cho-m.

Rebased this to incorporate the fix.

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
