### PR TITLE
node 16.1.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

see https://github.com/nodejs/node/releases/tag/v16.1.0

### CODE REVIEW

**Review by dawidd6 — APPROVED** [review]

**Comment by derrabus** [comment]
Is there something I can do about the failure on ARM? Or did I catch a random NPM hiccup here?

```
Failure:
Error: Package '@microsoft.azure/autorest.nodejs' - '2.1.128' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.nodejs/-/autorest.nodejs-2.1.128.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.nodejs/-/autorest.nodejs-2.1.128.tgz' -- Error: Process Failed.
    at Yarn.install (/opt/homebrew/Cellar/autorest/3.2.0/libexec/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:1751:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExtensionManager.installPackage (/opt/homebrew/Cellar/autorest/3.2.0/libexec/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:1124:13)
    at ConfigurationLoader.resolveExtension (/opt/homebrew/Cellar/autorest/3.2.0/libexec/lib/node_modules/autorest/dist/app.js:4814:35)
    at ConfigurationLoader.load (/opt/homebrew/Cellar/autorest/3.2.0/libexec/lib/node_modules/autorest/dist/app.js:4707:43)
    at Object.findCoreVersionUsingConfiguration (/opt/homebrew/Cellar/autorest/3.2.0/libexec/lib/node_modules/autorest/dist/app.js:457:24)
    at Object.resolveCoreVersion (/opt/homebrew/Cellar/autorest/3.2.0/libexec/lib/node_modules/autorest/dist/app.js:493:28)
    at main (/opt/homebrew/Cellar/autorest/3.2.0/libexec/lib/node_modules/autorest/dist/app.js:186:33)
```

**Comment by dawidd6** [comment]
Rerunning jobs, so we can check if it was a hiccup.

**Comment by chrmoritz** [comment]
The dotnet framework issue doesn't look to be npm related at all:

```
{"type":"error","data":"/private/tmp/autorest-test-20210505-67548-18as1rk/.autorest/@microsoft.azure_autorest.nodejs@2.1.128/node_modules/dotnet-2.0.0: Command failed.\nExit code: 1\nCommand: node -e \"/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}\"\nArguments: \nDirectory: /private/tmp/autorest-test-20210505-67548-18as1rk/.autorest/@microsoft.azure_autorest.nodejs@2.1.128/node_modules/dotnet-2.0.0\nOutput:\nUnable to install/use dotnet framework."}
```

**Comment by cho-m** [comment]
@chrmoritz It looks like `autorest` previously wasn't bottled for ARM.
The latest update a few days ago #76561 has created an `all:` bottle section: https://github.com/Homebrew/homebrew-core/commit/f0597e87332c0258d62a597d898939ec6a43d2dc

**Comment by Bo98** [comment]
Yeah, just a slight oversight. We should probably adjust it to be `depends_on arch: :x86_64`

**Comment by carlocab** [comment]
ARM failure resolved in #76749.

**Comment by derrabus** [comment]
Thanks!

**Pull request closed without merging**
