### PR TITLE
netdata 1.15.0

### PR DESCRIPTION
**Pull request by rickard-von-essen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
This fails with

```
 * object files were linked against system openssl
    These object files were linked against the deprecated system OpenSSL or
    the system's private LibreSSL.
    Adding `depends_on "openssl"` to the formula may help.
      /usr/local/Cellar/netdata/1.15.0/libexec/netdata/plugins.d/cups.plugin
            /usr/local/Cellar/netdata/1.15.0/sbin/netdata
```
On Sierra, I'm not sure what to do about that. I'll try to add `openssl` as dep for Sierra..

**Comment by zbeekman** [comment]
@Homebrew/maintainers Can someone please remind me: under what conditions should we be linking to brewed openssl? This formula has `depends_on "openssl" if MacOS.version == :sierra` but I'm wondering if the condition is correct or should be changed. Thanks!

**Comment by MikeMcQuaid** [comment]
> @Homebrew/maintainers Can someone please remind me: under what conditions should we be linking to brewed openssl? This formula has `depends_on "openssl" if MacOS.version == :sierra` but I'm wondering if the condition is correct or should be changed. Thanks!

There is no specific rule. I'd make it `=< :sierra` if anything but an unconditional dep would also be fine.

**Comment by rickard-von-essen** [comment]
Changed to `=< :sierra`

**Comment by rickard-von-essen** [comment]
Looks like something weird happened with Jenkins there..?

**Comment by javian** [comment]
@BrewTestBot test this please

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @rickard-von-essen!

**Pull request closed without merging**
