### PR TITLE
node-sass: 1.23.7 (new formula)

### PR DESCRIPTION
**Pull request by JarryShaw**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Following discussion in Homebrew/homebrew-core#43388, this formula is from the original pull request.

For dart implementation, please refer to #47438

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you move the require inside of the class?

**Comment by JarryShaw** [comment]
Could someone tell why the CI failed? The link to [details](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/52939/) seems not existing anymore...

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by yumitsu** [comment]
@JarryShaw 

```
15:28:50 Error: No available formula with the name "dart-sass" 
15:28:51 Build step 'Execute shell' marked build as failure
```

**Comment by yumitsu** [comment]
@JarryShaw 

```
19:13:48 ==> brew audit node-sass --online --new-formula
19:13:57 ==> FAILED
19:13:57 Error: 1 problem in 1 formula detected
19:13:57 node-sass:
19:13:57   * C: 12: col 3: Missing space after `#`.
```

Please do `brew audit <formulae>` on your edits before commit them.

**Comment by JarryShaw** [comment]
Just tried to squash all commits... is there a guild or something to walk through the procedure? 😞

**Comment by yumitsu** [comment]
@BrewTestBot test this please

**Comment by yumitsu** [comment]
@JarryShaw Look like you'd broke something with that squash attempt:
```
20:53:54 ==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/47439
20:54:30 ==> FAILED
20:54:30 fatal: ref HEAD is not a symbolic ref
20:54:30 fatal: Not possible to fast-forward, aborting.
20:54:30 Error: Failure while executing; `git merge --quiet --ff-only --no-edit FETCH_HEAD` exited with 128.
```

**Comment by JarryShaw** [comment]
Made new PR at #48167

**Pull request closed without merging**
