### PR TITLE
vectorscan: build for arm, and have snort depends_on it

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

`hyperscan` is no longer being maintained upstream…because it's instead transitioned to a closed-source license available from Intel with payment.  `vectorscan` is an open-source drop-in replacement/fork (for the version of `hyperscan` we supported) and is still maintained; it already supports x86_64.

### CODE REVIEW

**Comment by pthariensflame** [comment]
Should be ready for review!

**Comment by chenrui333** [comment]
@pthariensflame can you move the `deprecate` commit into its own PR? and then have this PR as followup for it?

**Comment by pthariensflame** [comment]
@chenrui333 How should I handle `snort` in that case?  I can't leave it depending on `hyperscan` (`audit` rejects that) and I can't move it to `vectorscan` without the other commit here opening it to x86_64 builds.

**Comment by chenrui333** [comment]
in this way, we dont need to bottle for the deprecated formula (and also be linked to the upstream issues separately as well)

**Comment by pthariensflame** [comment]
So this PR is kind of stuck as an atomic unit unless we can untangle the `snort` reverse-dep situation somehow.

**Comment by chenrui333** [comment]
> I can't leave it depending on `hyperscan` (`audit` rejects that)

that is fine, we can ignore the warning (even though quite ideal)

**Comment by pthariensflame** [comment]
Okay!

**Comment by chenrui333** [comment]
I think it should be other way around 😅 , you have formulae not depends on hyperscan, so that we can deprecate it. Does that make sense.

**Comment by pthariensflame** [comment]
@chenrui333 That is exactly what I would have done, but there's a dependency snarl involved:

- `snort` depends on `hyperscan` on x86, so has to be moved to `vectorscan` there (which it already uses on Arm),
- but `vectorscan` is not built for x86, only for Arm.

I can't update `snort` before I update `vectorscan` (because it won't be available for use on x86); I can't deprecate hyperscan before I update `snort` (because `audit` complains); I can't update `vectorscan` before I deprecate `hyperscan` (because the original logic for why `vectorscan` was only built for Arm is that x86 was `hyperscan`'s exclusive territory).

**Comment by pthariensflame** [comment]
The only way out here in multiple PRs that would generate no complaints from audit is to update vectorscan, then update snort, then deprecate hyperscan, accepting in the process that there will be an intermediate state where both vectorscan and hyperscan are available on x86_64.

**Comment by chenrui333** [comment]
> I can't update `snort` before I update `vectorscan` (because it won't be available for use on x86); I can't deprecate hyperscan before I update `snort` (because `audit` complains); 

this all makes sense

> I can't update `vectorscan` before I deprecate `hyperscan` (because the original logic for why `vectorscan` was only built for Arm is that x86 was `hyperscan`'s exclusive territory).

this is a bit confusing

**Comment by chenrui333** [comment]
> > I can't update `vectorscan` before I deprecate `hyperscan` (because the original logic for why `vectorscan` was only built for Arm is that x86 was `hyperscan`'s exclusive territory).
> 
> this is a bit confusing

this is the reason why we never included the x86 bottle, https://github.com/VectorCamp/vectorscan/issues/111

**Comment by pthariensflame** [comment]
@chenrui333 I suppose the bottom line is:  are you okay with updating vectorscan in one PR, then 

> > > I can't update `vectorscan` before I deprecate `hyperscan` (because the original logic for why `vectorscan` was only built for Arm is that x86 was `hyperscan`'s exclusive territory).
> > 
> > 
> > this is a bit confusing
> 
> this is the reason why we never included the x86 bottle, [VectorCamp/vectorscan#111](https://github.com/VectorCamp/vectorscan/issues/111)

Oh, I see; I missed that!

**Comment by pthariensflame** [comment]
It seems as if that problem no longer exists, though, if you look at the CI.

**Comment by pthariensflame** [comment]
So we do have a way out, then.  It's the order I described:  `vectorscan`, `snort`, `hyperscan`.

**Comment by chenrui333** [comment]
> It seems as if that problem no longer exists, though, if you look at the CI.

the issue is very subtle, hard to audit (with rebottling hyperscan, we would lose the big_sur bottle, that is it)

**Comment by chenrui333** [comment]
> Or we can merge the `hyperscan` deprecation first and then this PR, accepting that it will briefly cause `audit` to fail.

it is not mergeable, unfortunately.

**Comment by chenrui333** [comment]
Should be good, the deprecate PR can rebase to this one.

**Review by chenrui333 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
