### PR TITLE
heksa 1.12.1 (new formula)

### PR DESCRIPTION
**Pull request by merces**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on the test
```
==> /usr/local/Cellar/heksa/1.12.1/bin/heksa -l 16 -f asc -o no /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.gif
Error: heksa: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </G.*I.*F.*8.*9.*a/> was expected to be =~
<"">.
```

**Comment by merces** [comment]
@chenrui333 does the test environment have the [test_fixtures](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/test/support/fixtures)? I've used one of its files for testing  the program. I see there's no output so I'm assuming the file is not in the test environment?

Thanks.

**Comment by SMillerDev** [comment]
It does have those

**Comment by merces** [comment]
It runs fine here:

    $ brew test heksa
    Testing heksa
    ==> /usr/local/Cellar/heksa/1.12.1/bin/heksa -l 16 -f asc -o no 
    /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.gif
    ~ $ echo $?
    0
I don't know what to do then. Any recommendations?

**Comment by chenrui333** [comment]
@merces let me checkout the branch and test it on my local.

**Comment by chenrui333** [comment]
I did not see gif test failure in my local either, let's try png file on the CI to see if the issue is recurring.

**Comment by chenrui333** [comment]
This becomes very interesting now 🤣

**Comment by merces** [comment]
Hehe agreed. I still "feel" it may have something to do with the test files. Or the color codes heksa generates?

**Comment by chenrui333** [comment]
> Hehe agreed. I still "feel" it may have something to do with the test files. Or the color codes heksa outputs?

let me try out a actual test file to assert it.

**Comment by vladimyr** [comment]
> > Hehe agreed. I still "feel" it may have something to do with the test files. Or the color codes heksa outputs?
> 
> let me try out an actual test file to assert it.

Actually it is due to `heksa` failing to produce any output if it isn't attached to tty. See #56674 for working version 😉

**Comment by chenrui333** [comment]
@vladimyr thanks a lot for your efforts to get this formula to move forward.

@merces I am gonna close this PR in favor of the other one (can you do a review check over there?) Many thanks!

**Comment by vladimyr** [comment]
> @vladimyr thanks a lot for your efforts to get this formula to move forward.

It is a pleasure  😉

> @merces I am gonna close this PR in favor of the other one (can you do a review check over there?) Many thanks!

Hm, please don't - I really don't want to steal their contribution. I'll close my instead 😉

**Comment by SMillerDev** [comment]
Yours is building @vladimyr, this isn't.

**Comment by vladimyr** [comment]
> Yours is building @vladimyr, this isn't.

I know, I know, I just wanted to give the time to @merces to copy things over instead so he gets a credit 👐

**Comment by merces** [comment]
Hi! Sorry for the delay. I'm ok with closing this one. Actually @vladimyr also contributed - and solved the mystery - so also deserve credits here. And the goal of making brew users happy with one more program in their toolset will be achieved anyway. Please, go for the easiest solution. 😉

Thanks for your efforts here! It was nice to learn from this process.

Cheers!

**Comment by vladimyr** [comment]
> Hi! Sorry for the delay.

I'm sorry if that stream of notifications created a sense of urgency, there is absolutely zero need for rushing and furthermore I believe everybody here understands and accounts for communication delays. 👐 

> Additionally, the goal of making brew users happy with one more program in their toolset will be achieved anyway. So, please, go for the easiest solution. 😉
> 
> Thanks for your efforts here! It was nice to learn from this process.

It is my pleasure, I absolutely enjoy helping people with such honorable and wonderful goals. ❤️

**Comment by chenrui333** [comment]
Closing this PR and merging the other one. Thanks @vladimyr and @merces!! ❤️

**Comment by chenrui333** [comment]
🎉 :
```
$ brew install heksa
==> Downloading https://homebrew.bintray.com/bottles/heksa-1.12.1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/48/481e0b181ff88978df7804ff8f657821b7802a9c2f
######################################################################## 100.0%
==> Pouring heksa-1.12.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/heksa/1.12.1: 5 files, 2.2MB
```

**Pull request closed without merging**
