### PR TITLE
notcurses 2.4.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dankamongmen** [comment]
Hey @alebcay , can you give me some details on this arm64 timeout? I'm the upstream author, and there were no changes between 2.3.17 and 2.3.18 that I would expect to lead to such a failure.

**Comment by alebcay** [comment]
The timeout is upwards of 1-2 minutes I think (not certain off the top of my head). And I understand that `notcurses-info` is not supposed to be computationally intensive. So I imagine that the program just hung for some reason.

The program did print some output, not sure if it's of any help:
```
==> /opt/homebrew/Cellar/notcurses/2.3.18/bin/notcurses-info
c0qc2026$p1;3;256S2;1;0S1;1;0S1h
```

Re-running all checks to verify we can reproduce this (and see if it occurs on x86_64).

**Comment by carlocab** [comment]
The timeout is 5 minutes.

**Comment by dankamongmen** [comment]
what we're seeing there is the query string sent to the terminal on startup. it shouldn't be sending it unless it thinks it's connected to a true terminal (i.e. some device for which `isatty(3)` returned 1. did something change in the way it's run?

**Comment by alebcay** [comment]
My guess is that this may be stemming from https://github.com/Homebrew/brew/pull/11914. Looks like it's failing in x86_64 tests too. I will try a few things locally and see if I can work around this.

**Comment by carlocab** [comment]
Hi @Bo98

**Comment by dankamongmen** [comment]
> My guess is that this may be stemming from [Homebrew/brew#11914](https://github.com/Homebrew/brew/pull/11914). Looks like it's failing in x86_64 tests too. ~I will try a few things locally and see if I can work around this.~ I tried a thing and it didn't work. So hopefully Bo can take a look

that looks like exactly the kind of change that would cause this breakage. if you didn't have a pty connected before, it would never emit these queries. now you have a pty attached, and so it lets loose with them, and blocks on a result.

what are you using to implement this pty?

fwiw, i don't see this problem when running interactively in Terminal.App, iTerm2, nor Kitty on macOS. nor do i see it from a daemonized process (which will have no controlling tty).

**Comment by alebcay** [comment]
The implementation is [Ruby's built-in `pty` module](https://ruby-doc.org/stdlib-2.5.3/libdoc/pty/rdoc/PTY.html), the source for which is probably [here](https://github.com/ruby/ruby/blob/ruby_2_6/ext/pty/pty.c) (the exact version may differ; we use whatever version of Ruby ships on each macOS version, but it seems like the issue is similar across the board anyways).

**Comment by dankamongmen** [comment]
> The implementation is [Ruby's built-in `pty` module](https://ruby-doc.org/stdlib-2.5.3/libdoc/pty/rdoc/PTY.html), the source for which is probably [here](https://github.com/ruby/ruby/blob/ruby_2_6/ext/pty/pty.c) (the exact version may differ; we use whatever version of Ruby ships on each macOS version, but it seems like the issue is similar across the board anyways).

a quick look suggests that this is a very minimal, non-VT102-compliant terminal implementation. what TERM are you exporting? i assume it has its own terminfo entry, as it doesn't appear to be implementing very much. i can avoid querying on such a TERM, if we need to. otherwise i'd say just disable the test if you're going to be using this.

**Comment by Bo98** [comment]
> it shouldn't be sending it unless it thinks it's connected to a true terminal

That is one key difference: the CI environment previously did not connect `stdout` to a tty but now it will since there's a pty. Arguably though, in some cases that makes the CI run more similarly to how `brew test <formula>` worked locally, since most would be running that in Terminal.app and thus have stdout connected to that (though this is now also a pty).

> what TERM are you exporting?

This hasn't changed with the pty changes, so maybe it needs tweaking: but what the behaviour has been is that `TERM` is set to "dumb" in the test block and matching the user's terminal everywhere else.

**Comment by dankamongmen** [comment]
> However, it looks like the test here is overriding that with `xterm` for some reason.

we had no `TERM` defined previously, IIRC, and i need some `TERM` defined.

i think it would be sensible not to query for a `TERM=dumb` environment. i can make that change for 2.3.19, and i can do it in a single commit, so it's an easy patch for this formula. how does that sound?

**Comment by dankamongmen** [comment]
no, nevermind, TERM was defined as `dumb` before. the problem is:

```
[schwarzgerat](0) $ env TERM=dumb ./notcurses-info
interrogate_terminfo:820:Required terminfo capability 'cup' not defined
notcurses_core_init:1263:Alas, you will not be going to space today.
[schwarzgerat](1) $ 
```

**Comment by carlocab** [comment]
That sounds fine. We can get rid of the `xterm` override and just check that we get that error message + exit code.

**Comment by carlocab** [comment]
```
Error: test failed
c0qc2026$p1;3;256S2;1;0S1;1;0Sinterrogate_terminfo:822:Required terminfo capability 'cup' not defined
notcurses_core_init:1260:Alas, you will not be going to space today.
notcurses-info(34703,0x1010f7d40) malloc: *** error for object 0x11e62ac70: pointer being freed was not allocated
notcurses-info(34703,0x1010f7d40) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by dankamongmen** [comment]
> ```
> Error: test failed
> c0qc2026$p1;3;256S2;1;0S1;1;0Sinterrogate_terminfo:822:Required terminfo capability 'cup' not defined
> notcurses_core_init:1260:Alas, you will not be going to space today.
> notcurses-info(34703,0x1010f7d40) malloc: *** error for object 0x11e62ac70: pointer being freed was not allocated
> notcurses-info(34703,0x1010f7d40) malloc: *** set a breakpoint in malloc_error_break to debug
> ```

that double-free was fixed up this morning, but the `TERM=dumb` problem stands. it's not meant to run on dumb terminals, where dumb is defined as lacking the ability to do arbitrary cursor movements. i'm going to think about this. the correct thing to do might end up being patching that ruby pty code to properly answer Device Primary Attributes, the most basic query =[. but let me think about it a bit more.

(other CIs, such as Debian, Fedora, Alpine, etc, are running in environments where the Linux console is the backing tty, and it properly answers DA1)

**Comment by carlocab** [comment]
Checking that `notcurses` errors out somewhat gracefully when `TERM=dumb` seems like a reasonable test to do here to me.

**Comment by dankamongmen** [comment]
> Checking that `notcurses` errors out somewhat gracefully when `TERM=dumb` seems like a reasonable test to do here to me.
> But if you've got a fix for our sandbox code, we can try that too.

to get this through, do you mean "check that it exits with 1", and remove the `TERM=xterm`? i'm down with that. if you'd like, i can even match the error text, but that seems a bit fragile IMHO. your call; i'll proceed however you recommend.

**Comment by carlocab** [comment]
> to get this through, do you mean "check that it exits with 1", and remove the `TERM=xterm`? i'm down with that. if you'd like, i can even match the error text, but that seems a bit fragile IMHO. your call; i'll proceed however you recommend.

This sounds good. We can match a substring of the error text too -- perhaps a part that isn't likely to change too much.

**Comment by dankamongmen** [comment]
> > to get this through, do you mean "check that it exits with 1", and remove the `TERM=xterm`? i'm down with that. if you'd like, i can even match the error text, but that seems a bit fragile IMHO. your call; i'll proceed however you recommend.
> 
> This sounds good. We can match a substring of the error text too -- perhaps a part that isn't likely to change too much.

great, getting on this now (and bumping the pull to 2.4.0).

**Comment by dankamongmen** [comment]
i can't commit to @alebcay's branch. i'm going to create a new PR, and this one ought be closed (unless you'd like some other procedure).

**Comment by carlocab** [comment]
Merged in #84851.

**Pull request closed without merging**
