### PR TITLE
erlang@26 26.2.5 (new formula)

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Allow for dependants to depend on this new formula (as copied from `erlang.rb`) - check #178020 

```diff
1c1
< class Erlang < Formula
---
> class ErlangAT26 < Formula
15,23c15
<   bottle do
<     sha256 cellar: :any,                 arm64_sonoma:   "c431396f5317abe1127f09e050f09b9e95b19ba1a5182a21fc5a77699bcd7e13"
<     sha256 cellar: :any,                 arm64_ventura:  "110213139fc017f108a06e1f206a5ddf7272d5807c4764ead9dd5cf6db1e620b"
<     sha256 cellar: :any,                 arm64_monterey: "f69832dec4aaf28bbb576bf0b6d4e09365ba9ab8e5f70116f58873db576c57ce"
<     sha256 cellar: :any,                 sonoma:         "f0de0d4ee8cba0a67d9c90489fa2da82e12b2e3c4649643a8952ab88b4ec7b57"
<     sha256 cellar: :any,                 ventura:        "a339941ffc01c6eac2bc0d6ef07601466573de08cb5e9765e59a56ac9168a16c"
<     sha256 cellar: :any,                 monterey:       "0ca685f448bb8ea692a2f61d283420c29a82c674923f6ec408cc6ab879db19df"
<     sha256 cellar: :any_skip_relocation, x86_64_linux:   "3b2d280cd03af37844d763fb9e1c1955be8e203cc7f65271e4e65b2143b07c99"
<   end
---
>   keg_only :versioned_formula
25,32d16
<   head do
<     url "https://github.com/erlang/otp.git", branch: "master"
<
<     depends_on "autoconf" => :build
<     depends_on "automake" => :build
<     depends_on "libtool" => :build
<   end
<
41d24
<     mirror "https://fossies.org/linux/misc/otp_doc_html_26.2.5.tar.gz"
```

## Further considerations

This is a new take on:

* https://github.com/Homebrew/homebrew-core/pull/178237
* https://github.com/Homebrew/homebrew-core/pull/183630

in preparation for #178020, since I can't understand how to add a formula and change existing ones to depend on it (tests fail). I don't mind rebasing and following up later with @27/base.

### CODE REVIEW

**Review by NelsonVides — COMMENTED** [review]
Looks good to me!

**Comment by paulo-ferraz-oliveira** [comment]
@chenrui333, is there anything I can do to help move this forward? Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
@chenrui333, is there anything I can do to help move this forward? Thanks.

**Comment by ahankinson** [comment]
@chenrui333 it would be great to merge this so that we can get Erlang up to 0.27 in homebrew!

**Review by chenrui333 — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Seems ok, though I don't really follow:
- how this makes adding Erlang 27 any easier
- why the mirror for the `html` resource was dropped

Would be good to understand these two points a bit more before proceeding.

**Comment by NelsonVides** [comment]
> Seems ok, though I don't really follow:
> 
>     * how this makes adding Erlang 27 any easier
> 
>     * why the mirror for the `html` resource was dropped
> 
> 
> Would be good to understand these two points a bit more before proceeding.

Hey there!

On point one, it's coming from https://github.com/Homebrew/homebrew-core/pull/178020, there are many other formulas that have an implicit dependency on Erlang 26, and @paulo-ferraz-oliveira decided not to have to update all of them in a single PR (many of them fall too far of Erlang even, like Gleam or RabbitMQ) but rather create an explicit 26 formula and then mark all others as depending on this one explicitly, not interfering with the erlang upgrade.

On point two, I can't tell, maybe @paulo-ferraz-oliveira?

**Comment by carlocab** [comment]
Great, sounds good. Which dependents of `erlang` need to be switched to `erlang@26`? Are any of them compatible with Erlang 27?

**Comment by NelsonVides** [comment]
From what we saw at https://github.com/Homebrew/homebrew-core/pull/178020, we have gleam, lfe, erlang-ls, rebar3, wrangler, and emqx as far as I know. I'm pretty sure rebar3 can be upgraded to 27 too, with the others I'm not familiar, I don't use them 🥲 We can try to have a look but nevertheless I'd rather bring some gleam expert (I may know whom to ping) to upgrade gleam itself than to upgrade everything in one big and complex PR 🙈

**Comment by paulo-ferraz-oliveira** [comment]
@carlocab, what @NelsonVides said: there's a few that are compatible with Erlang 27, but they won't be updated in a single pull request (it's up to the maintainers of those tools to first updated them for compatibility then we can revisit the formula dependencies). The ones that are/aren't are identified in #178020.

> Yeap, as quickly as possible is what we want at #178020 🙂

As soon as this is done I'll rebase the other PR and take care of required updates. You can see that I've been coming here often so there's a high change that I can do it pretty soonish.

> rebar3 can be upgraded to 27 too

Can't, because one of the dependencies depends on rebar3 and erlang@26, which means brew errors out (commit-by-commit you'll see the issues I ran into in the other PR).

...

Mirror was dropped because https://fossies.org/linux/misc/otp_doc_html_26.2.5.tar.gz is 404'ing.

**Comment by NelsonVides** [comment]
@carlocab @chenrui333 is there anything we need to do to get this one merged already? I see approvals and a merge tag but I'm not familiar with the merge policies here 🥲

**Comment by carlocab** [comment]
Thanks; I've removed the https://github.com/Homebrew/homebrew-core/labels/automerge-skip label so this should be merged shortly.

**Comment by paulo-ferraz-oliveira** [comment]
Cool stuff. I'll get on the other one right away.

**Pull request merged**
