### PR TITLE
mariadb@11.1 11.1.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at cmake/libfmt.cmake:44 (MESSAGE):
    system libfmt library is not found or unusable
```

**Comment by ZhongRuoyu** [comment]
fmtlib/fmt#3835

**Review by bevanjkay — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Seems that upstream wants a different fix: https://github.com/MariaDB/server/pull/3064#issuecomment-1943272981

**Comment by bevanjkay** [comment]
We will have to skip this version, unless the later fix can still be back ported.

**Comment by ZhongRuoyu** [comment]
Upstream confirmed that we can ship this: https://github.com/MariaDB/server/pull/3064#issuecomment-1943642672

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
