### PR TITLE
mdloader 1.0.5 (new formula)

### PR DESCRIPTION
**Pull request by fauxpark**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

mdloader is a flashing tool for Massdrop (Drop)'s ALT and CTRL mechanical keyboards.

By default, the program will only look in the CWD for the "applet-flash.bin" file it needs to upload to the microcontroller. The included patch modifies this behaviour to first look in the CWD, then in `#{prefix}/share/mdloader` (where the applet file will be stored).

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
 Error: 2 problems in 1 formula detected
mdloader:
  * GitHub fork (not canonical repository)
  * Formulae should not require patches to build. Patches should be submitted and accepted upstream first.
```

The fork is okay here, but the patches really need to be submitted upstream

**Comment by fauxpark** [comment]
Massdrop are unlikely to merge the patch, at least not in any reasonable time frame. Would it be acceptable to just move it to formula-patches?

**Comment by SMillerDev** [comment]
Not for new formulae, it really needs to be working correctly when it's added to Homebrew.

**Comment by fauxpark** [comment]
> it really needs to be working correctly when it's added to Homebrew.

The thing is, it *is* working correctly, as far as Massdrop is concerned. As I mentioned, the stock behaviour is to look for the applet file in the current working directory, but this obviously won't do for a package installed by Homebrew, as it ought to live in `#{prefix}/share/mdloader`.

I'm not really sure how to proceed. I can submit the PR to the mdloader repo, but I can almost guarantee it will sit there forever, as they seem to be suffering from a lack of manpower and motivation to do anything more than the bare minimum to keep it compiling. I hope that doesn't block this formula from being merged as is.

**Comment by SMillerDev** [comment]
> I'm not really sure how to proceed. I can submit the PR to the mdloader repo, but I can almost guarantee it will sit there forever, as they seem to be suffering from a lack of manpower and motivation to do anything more than the bare minimum to keep it compiling. I hope that doesn't block this formula from being merged as is.

That seems it doesn't meet the requirements defined in: https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by fauxpark** [comment]
It meets all of the requirements, as far as I can tell.

 - be maintained: last release was October 7th, it does indeed work without patching (but you would have to copy the applet file to your CWD every time you wanted to use it if the formula were submitted without this patch) There is actually not much to maintain, but it would be nice to see a migration to autotools.
 - be known: Drop/Massdrop are a fairly well known company selling a few different kinds of products, not just mechanical keyboards. mdloader is the tool they actively recommend for flashing the firmware for their keyboards: https://drop.com/talk/9382/how-to-configure-your-ctrl-keyboard
 - be stable (e.g. not declared “unstable” or “beta” by upstream)
 - be used - there are a decent amount of people who own & use Drop keyboards; they appear to be somewhat mass produced.
 - have a homepage - https://drop.com/, I guess?

**Comment by gromgit** [comment]
> The thing is, it _is_ working correctly, as far as Massdrop is concerned.
> ...
> it does indeed work without patching

Then why does your patch also select a different `limits.h` on macOS? That sounds more like a _build_ issue.

**Comment by gromgit** [comment]
> I can submit the PR to the mdloader repo, but I can almost guarantee it will sit there forever, as they seem to be suffering from a lack of manpower and motivation to do anything more than the bare minimum to keep it compiling.

That's really pushing the definition of _be maintained_.

**Comment by fxcoudert** [comment]
I agree that it's not sufficiently actively maintained for us.

**Pull request closed without merging**
