### PR TITLE
openttd: exclude beta release

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

```
$ curl https://cdn.openttd.org/openttd-releases/latest.yaml
latest:
- version: 13.4
  name: stable
  category: openttd
  date: 2023-07-29T23:01:00-00:00
- version: 14.0-beta1
  name: testing
  category: openttd
  date: 2024-02-03T19:50:00-00:00
```

### CODE REVIEW

**Comment by Bo98** [comment]
Filtering on `name: stable` would be nice if we have a proper YAML parser here.

**Comment by chenrui333** [comment]
yeah, we would need a yaml strategy.

**Review by samford — COMMENTED** [review]
> Filtering on `name: stable` would be nice if we have a proper YAML parser here.

I added a generic `Yaml` strategy a while back (https://github.com/Homebrew/brew/pull/14868), so we can do exactly that 👍

**Comment by samford** [comment]
Looks like we will also need to update the `resource` `livecheck` blocks, so duplicating the `strategy` block for each will end up a little verbose. I can push a commit if we want to go that route.

However, we can also restrict matching to stable versions by simply adding `$` to the end of these regexes (i.e., `regex(/version:\s*?v?(\d+(?:\.\d+)+)$/i)`).

**Review by samford — APPROVED** [review]
I updated the commit to add the `strategy` block to the `resource` `livecheck` blocks as well. Someone else will need to approve this since I'm the last pusher but this should be good to go now.

**Review by branchv — APPROVED** [review]

**Pull request merged**
