### PR TITLE
widelands: rationalize dependencies

### PR DESCRIPTION
**Pull request by gromgit**
Also added proper test and license.

Followup from #65993

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by fxcoudert — DISMISSED** [review]

**Comment by gromgit** [comment]
```
Graphics: Try to set Videomode 800x600
glewInit returns 1
Your OpenGL installation must be __very__ broken. Missing GL version
```
Is this an expected failure, or a config issue with the CI hardware?

**Comment by gromgit** [comment]
@Homebrew/core, could use some advice from someone more experienced in OpenGL, as to why calling `glewInit()` would work in CI for #59779 and when running this PR locally, but not in CI. Thanks much!

**Comment by iMichka** [comment]
On linux, `glew` depends on `mesa` and `mesa-glu`. Can you try adding both here and see if it helps?

**Comment by gromgit** [comment]
Whoops, forgot about this one. Resuming..

**Pull request closed without merging**
