### PR TITLE
rust-nightly 2019-08-25 (new formula)

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This exists mainly to serve to build other Homebrew packages which use Rust and which need a nightly build, rather than to be used as a tool by most users. Because it's not intended for most users, I've left out racer. To avoid unnecessary CI builds, we should update this monthly or less frequently unless newer features are absolutely needed at a faster frequency.

cc @chenrui333 
Refs #43440.
Refs #41304.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
👍

**Comment by SMillerDev** [comment]
Are nightlies a stable, tagged version as per https://docs.brew.sh/Acceptable-Formulae#stable-versions? Without knowing anything about rust it seems to be in violation of that requirement.

**Comment by iMichka** [comment]
Why is "head" not enough? If people need bottled versions, they can host this on their own taps. I am also -1 to host this in homebrew-core.

**Comment by iMichka** [comment]
And for the formulae that need it: it is a shame that features from nightly builds where used at all ... why did upstream do that? Shipping a release, knowing that almost nobody will have the nightly builds at hand (and especially as rust takes forever to compile ...).

I would be in favour of vendoring for this case ... :(

We have versioned formulae for deprecated packages, not for nightly builds.

We could also keep the 2 formulae as-is, until a proper rust release is made.

**Pull request closed without merging**
