### PR TITLE
libdbusmenu-qt: rename with-d-bus qt build option to with-dbus

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
This thing smells like :skull: if no one has fixed this by now.

**Comment by DomT4** [comment]
Zero installations according to analytics.

**Comment by ilovezfs** [comment]
Well, zero is a number.

Also, in the qt5 tracking thread it says "libdbusmenu-qt - Has Qt5 support in upstream, but no new release in 4 years," and yet
```
-- Check for working CXX compiler: /usr/local/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindQt4.cmake:1328 (message):
  Found unsuitable Qt version "5.6.1" from /usr/local/opt/qt5/bin/qmake, this
  code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:47 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/libdbusmenu-qt-20160806-56692-1abz7zp/libdbusmenu-qt-0.9.2/macbuild/CMakeFiles/CMakeOutput.log".
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/libdbusmenu-qt/0.9.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Comment by ilovezfs** [comment]
@MikeMcQuaid it looks like you added this formula originally in 2011. Any thoughts on :skull:?

**Comment by DomT4** [comment]
Unless you're building from `HEAD` that's expected. Qt5 support has been upstream since 2013, but for some reason they've stopped cutting releases.

**Comment by ilovezfs** [comment]
formula doesn't define `head` so I wasn't sure if it was supposed to work out of the box

**Comment by ilovezfs** [comment]
Looks like this is used by `kdelibs`, which is in the boneyard for one reason or another.

**Comment by MikeMcQuaid** [comment]
> Looks like this is used by kdelibs, which is in the boneyard for one reason or another.

That'll be why I added it: back in the day I was unsuccessfully trying to keep KDE ported to Mac.

**Comment by MikeMcQuaid** [comment]
So: 💀 away.

**Pull request closed without merging**
