### PR TITLE
protobuf 3.15.1

### PR DESCRIPTION
**Pull request by Loyalsoldier**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
You'll probably need the same revision bumps as in #71477.

**Comment by carlocab** [comment]
You forgot to remove the patch.

**Comment by Loyalsoldier** [comment]
I use `brew bump-revision $(brew uses protobuf)` to automatically bump revisions of related formulas. Am I doing right?

**Comment by carlocab** [comment]
Yes, that's fine. Ideally, you would have included the flag `--message="(protobuf 3.15.1)"` so we know what the revision bump is for, but this isn't too bad too.

**Comment by carlocab** [comment]
Actually, no, wait. We should avoid revision bumps when they're not needed, so we shouldn't be rev-bumping all the formulae that depend on `protobuf`.

**Comment by Loyalsoldier** [comment]
> Actually, no, wait. We should avoid revision bumps when they're not needed, so we shouldn't be rev-bumping all the formulae that depend on `protobuf`.

Are you suggesting that let the test fail again and again and fix them one by one? 😂

**Comment by carlocab** [comment]
Well you should already know which ones need revision bumps from the previous PR... start with revision bumps for the linkage failures. That should fix at least some test failures.

**Comment by Loyalsoldier** [comment]
The failure in Big Sur arm64 is weird:

```shell
==> Running Formulae#formula!(opencv)
/Users/brew/actions-runner-x86_64/_work/_temp/82f9125d-ef83-402c-bc03-444ee61d7462.sh: line 3: 59214 Illegal instruction: 4  brew test-bot --only-formulae
Error: Process completed with exit code 132.

Run cat bottles/steps_output.txt
cat: bottles/steps_output.txt: No such file or directory
Error: Process completed with exit code 1.
```

**Comment by Bo98** [comment]
I'm actually surprised if there's revision bumps required. Patch updates should not be changing ABI.

**Comment by carlocab** [comment]
This is a version bump from 3.14.0 to 3.15.1 though, so a bit more than a patch version update.

**Comment by Bo98** [comment]
Oh oops, I thought 1.50.0 was merged - nevermind!

**Comment by Loyalsoldier** [comment]
Any idea about how to fix `apache-arrow` build error?

**Comment by carlocab** [comment]
It might not be compatible with protobuf 3.15+ yet. Try checking their issue tracker.

**Comment by carlocab** [comment]
`apache-arrow` and `bear` will need extra revision bumps from here: #71898

**Comment by Loyalsoldier** [comment]
You know what. Protobuf v3.15.2 has been released. Closed. Brilliant. 😂 

https://github.com/Homebrew/homebrew-core/pull/71937

**Pull request closed without merging**
