### PR TITLE
fibjs 0.37.0

### PR DESCRIPTION
**Pull request by xicilion**
update fibjs to 0.37.0

Support for napi addons, etc.
The full changelog is https://github.com/fibjs/fibjs/blob/v0.37.0/CHANGELOG.md

### CODE REVIEW

**Comment by chenrui333** [comment]
@xicilion can you amend your commit msg as `fibjs 0.37.0`

**Comment by xicilion** [comment]
> @xicilion can you amend your commit msg as `fibjs 0.37.0`

thanks.

**Comment by chenrui333** [comment]
@xicilion you still need to do the commit msg change, right now it failed the commit style check.

**Comment by xicilion** [comment]
> @xicilion you still need to do the commit msg change, right now it failed the commit style check.

already changed.

**Comment by chenrui333** [comment]
I was referring to this

image

**Comment by chenrui333** [comment]
I just went ahead of creating a replacement PR #163095

**Comment by xicilion** [comment]
thanks.

**Pull request closed without merging**
