### PR TITLE
hashcat 6.2.0

### PR DESCRIPTION
**Pull request by jdmartin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failure

```
==> /private/tmp/hashcat-test-20210515-79103-1ftz4s6/hashcat --benchmark -m 0
hashcat (v6.2.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

No devices found/left.

Started: Sat May 15 03:30:06 2021

Stopped: Sat May 15 03:30:06 2021
```

**Comment by jdmartin** [comment]
If it helps, I think this error is due to the CI not having access to a suitable device for hashing.  (It seems the 11 (intel) test doesn't have this step?)  Compare the above output with what happens when I startup 6.1.1 on my MacBook Pro (2019):

Screen Shot 2021-05-15 at 2 15 25 PM

**Comment by jdmartin** [comment]
Testing issues aside, this release has been superseded by [6.2.1](https://github.com/hashcat/hashcat/releases/tag/v6.2.1).  So, closing.

**Comment by chenrui333** [comment]
relates to #77546

**Pull request closed without merging**
