### PR TITLE
flow 0.45.0

### PR DESCRIPTION
**Pull request by gabelevi**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@gabelevi This seems to fix it:
```
diff --git a/Formula/flow.rb b/Formula/flow.rb
index cdcb0f0..8e64e82 100644
--- a/Formula/flow.rb
+++ b/Formula/flow.rb
@@ -13,10 +13,18 @@ class Flow < Formula
   end
 
   depends_on "ocaml" => :build
-  depends_on "ocamlbuild" => :build
+  depends_on "opam" => :build
 
   def install
-    system "make"
+    ENV["OPAMROOT"] = buildpath/"opamroot"
+    ENV["OPAMYES"] = "1"
+
+    inreplace "Makefile", "-use-ocamlfind -pkgs sedlex",
+                          "-no-hygiene -use-ocamlfind -pkgs sedlex"
+
+    system "opam", "init", "--no-setup"
+    system "opam", "install", "ocamlfind", "sedlex"
+    system "opam", "config", "exec", "--", "make"
     bin.install "bin/flow"
 
     bash_completion.install "resources/shell/bash-completion" => "flow-completion.bash"
```

It would be good if we could get that Makefile change upstreamed, though.

**Comment by gabelevi** [comment]
Sorry about that! You're right, we've messed around with our build a little bit. Thanks for suggesting the fix! I'll make sure to upstream this into the Makefile!

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by ilovezfs** [comment]
@gabelevi it doesn't look like https://github.com/facebook/flow/pull/3830 handles the `-no-hygiene` piece.

**Comment by gabelevi** [comment]
So I tried removing the `no-hygiene` line from the v0.45.0 brew formula, and got the following error

```
$ brew install flow
==> Downloading https://homebrew.bintray.com/bottles/flow-0.45.0.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "flow"
Download failed: https://homebrew.bintray.com/bottles/flow-0.45.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://github.com/facebook/flow/archive/v0.45.0.tar.gz
Already downloaded: /Users/glevi/Library/Caches/Homebrew/flow-0.45.0.tar.gz
==> opam init --no-setup
==> opam install ocamlfind sedlex
==> opam config exec -- make
Last 15 lines from /Users/glevi/Library/Logs/Homebrew/flow/03.opam:
  File ast_convenience.cmx in opamroot/system/lib/ppx_tools has suffix .cmx
  File ppx_tools.cma in opamroot/system/lib/ppx_tools has suffix .cma
  File ppx_tools.cmxa in opamroot/system/lib/ppx_tools has suffix .cmxa
ERROR: Leftover object files:
  File sedlexing.a in opamroot/system/lib/sedlex has suffix .a
  File sedlex.a in opamroot/system/lib/sedlex has suffix .a
ERROR: Leftover OCaml compilation files:
  File sedlexing.cmi in opamroot/system/lib/sedlex has suffix .cmi
  File sedlexing.cmx in opamroot/system/lib/sedlex has suffix .cmx
  File sedlexing.cma in opamroot/system/lib/sedlex has suffix .cma
  File sedlex.cma in opamroot/system/lib/sedlex has suffix .cma
  File sedlexing.cmxa in opamroot/system/lib/sedlex has suffix .cmxa
  File sedlex.cmxa in opamroot/system/lib/sedlex has suffix .cmxa
Exiting due to hygiene violations.
make: *** [build-flow] Error 1
```

It looks like `buildpath` is the project root, from which `make` is executed. By installing opam into `buildpath/opamroot`, we're putting build artifacts into the directory from which `make` is executed. `ocamlbuild` does not like that.

https://github.com/facebook/flow/pull/3830 instead uses a temp directory as the opam directory, which side-steps the problem

**Comment by ilovezfs** [comment]
@gabelevi neat. In that case, I'd suggest this:
```
diff --git a/Formula/flow.rb b/Formula/flow.rb
index cdcb0f0..746be38 100644
--- a/Formula/flow.rb
+++ b/Formula/flow.rb
@@ -1,10 +1,20 @@
 class Flow < Formula
   desc "Static type checker for JavaScript"
   homepage "https://flowtype.org/"
-  url "https://github.com/facebook/flow/archive/v0.45.0.tar.gz"
-  sha256 "9a76cb1669d5d1f07a55b3163edb0329c46565033eaf7ed9320058b6e3a9cbbf"
   head "https://github.com/facebook/flow.git"
 
+  stable do
+    url "https://github.com/facebook/flow/archive/v0.45.0.tar.gz"
+    sha256 "9a76cb1669d5d1f07a55b3163edb0329c46565033eaf7ed9320058b6e3a9cbbf"
+
+    # Remove for > 0.45.0
+    # Upstream PR from 28 Apr 2017 "Add `make all-homebrew`"
+    patch do
+      url "https://github.com/facebook/flow/pull/3830.patch"
+      sha256 "4f034a263a834441a5397223710d1888885e8bb947c651d8f9eedc06fb5442c8"
+    end
+  end
+
   bottle do
     cellar :any_skip_relocation
     sha256 "438f3f4f9ba716cf284de96c6b281b539aacd06079afb1309f569845a448488f" => :sierra
@@ -13,10 +23,10 @@ class Flow < Formula
   end
 
   depends_on "ocaml" => :build
-  depends_on "ocamlbuild" => :build
+  depends_on "opam" => :build
 
   def install
-    system "make"
+    system "make", "all-homebrew"
     bin.install "bin/flow"
 
     bash_completion.install "resources/shell/bash-completion" => "flow-completion.bash"
```

**Comment by ilovezfs** [comment]
@gabelevi looks like it's not thrilled with your latest commit:
```
flowtype is now path-pinned to /private/tmp/flow-20170428-28143-1eoqvwr/flow-0.45.0

[flowtype: local]
[WARNING] Rsync partially failed:
          symlink has no referent:
          "/private/tmp/flow-20170428-28143-1eoqvwr/flow-0.45.0/website/_assets/css/bootstrap"
          rsync error: some files could not be transferred (code 23) at
          /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(992)
          [sender=2.6.9]

[flowtype] /private/tmp/flow-20170428-28143-1eoqvwr/flow-0.45.0/ synchronized
[flowtype] Conflicting update of the metadata from
/private/tmp/flow-20170428-28143-1eoqvwr/flow-0.45.0:
  - The contents of "opam" changed

Override files in
/var/folders/w6/9r0nb9011glb8fdz__srd78c0000gq/T/tmp.GRwUBEGB/system/overlay/flowtype
(there will be a backup) ? [Y/n] y
User metadata backed up in
/var/folders/w6/9r0nb9011glb8fdz__srd78c0000gq/T/tmp.GRwUBEGB/backup/flowtype.bak

flowtype needs to be installed.
[ERROR] flowtype.0.44.0 is not available because your system doesn't comply
        with ocaml-version >= "4.03.0" & ocaml-version < "4.04.0".
[NOTE] Pinning command successful, but your installed packages may be out of
       sync.
make: *** [all-homebrew] Error 66
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```
I assume it's because Homebrew's `ocaml` formula is OCaml 4.04.1.

**Comment by gabelevi** [comment]
You mean using your suggestion to patch stable? Yeah, I'm seeing the same thing. I'm going to try relaxing the upper bound on ocaml-version, since brew uses 4.04 and seems to be fine.

**Comment by ilovezfs** [comment]
>You mean using your suggestion to patch stable?

yep

>Yeah, I'm seeing the same thing. I'm going to try relaxing the upper bound on ocaml-version, since brew uses 4.04 and seems to be fine.

Nice! Thanks :)

**Comment by gabelevi** [comment]
Ok, I've updated the PR and locally it seems to work. I'm going to hold off updating this PR until that PR lands, to make sure we don't accidentally break the homebrew formula

**Comment by ilovezfs** [comment]
@gabelevi sounds good to me.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Let's wait for https://github.com/facebook/flow/pull/3830 and https://github.com/facebook/flow/pull/3833 to land.

**Comment by gabelevi** [comment]
Well, looks like the CLI for `mktemp` changed between yosemite and el capitan :(

https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x

**Comment by gabelevi** [comment]
I don't have access to Yosemite, so taking advantage of your CI to see if this works :)

**Comment by ilovezfs** [comment]
@gabelevi oh yes I've seen this annoyance before: https://github.com/elasticdog/transcrypt/issues/34#issuecomment-270794221

**Comment by ilovezfs** [comment]
@gabelevi :green_apple:

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@gabelevi shipped! Thank you for the upgrade and the speedy upstream fixes. :rocket:

**Comment by gabelevi** [comment]
And thank you @ilovezfs for all the help! This would have taken me way longer on my own!

**Comment by ilovezfs** [comment]
You're welcome!

**Pull request closed without merging**
