### PR TITLE
libpqxx 7.0.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
In file included from test.cpp:1:
In file included from /usr/local/Cellar/libpqxx/7.0.4/include/pqxx/pqxx:3:
In file included from /usr/local/Cellar/libpqxx/7.0.4/include/pqxx/binarystring:4:
In file included from /usr/local/Cellar/libpqxx/7.0.4/include/pqxx/binarystring.hxx:21:
In file included from /usr/local/Cellar/libpqxx/7.0.4/include/pqxx/result.hxx:25:
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:98:8: warning: constexpr if is a C++17 extension [-Wc++17-extensions]
    if constexpr (from_max > to_max)
       ^
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:104:11: warning: constexpr if is a C++17 extension [-Wc++17-extensions]
  else if constexpr ((from_limits::max)() > (to_limits::max)())
          ^
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:193:15: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
namespace pqxx::internal
              ^~~~~~~~~~
               { namespace internal
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:261:21: warning: 'constexpr' non-static member function will not be implicitly 'const' in C++14; add 'const' to avoid a change in behavior [-Wconstexpr-not-const]
  constexpr unique &operator=(unique const &) = delete;
                    ^
                                              const
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:262:21: warning: 'constexpr' non-static member function will not be implicitly 'const' in C++14; add 'const' to avoid a change in behavior [-Wconstexpr-not-const]
  constexpr unique &operator=(unique &&rhs)
                    ^
                                            const
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:271:18: warning: 'constexpr' non-static member function will not be implicitly 'const' in C++14; add 'const' to avoid a change in behavior [-Wconstexpr-not-const]
  constexpr void register_guest(GUEST *G)
                 ^
                                          const
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:277:18: warning: 'constexpr' non-static member function will not be implicitly 'const' in C++14; add 'const' to avoid a change in behavior [-Wconstexpr-not-const]
  constexpr void unregister_guest(GUEST *G)
                 ^
                                            const
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:259:5: warning: use of this statement in a constexpr constructor is a C++14 extension [-Wc++14-extensions]
    rhs.m_guest = nullptr;
    ^
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:264:5: warning: use of this statement in a constexpr function is a C++14 extension [-Wc++14-extensions]
    m_guest = rhs.m_guest;
    ^
/usr/local/Cellar/libpqxx/7.0.4/include/pqxx/util.hxx:271:18: error: constexpr function's return type 'void' is not a literal type
  constexpr void register_guest(GUEST *G)
                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
17 warnings and 20 errors generated.
Error: libpqxx: failed
Failed executing:
```

**Comment by Bo98** [comment]
Might need to do `ENV.append "CXXFLAGS", "-std=c++17"` or something. Though I would've expected that to be handled upstream.

**Comment by chenrui333** [comment]
Tested the build locally.

**Comment by Bo98** [comment]
`osm2pgrouting` requires a revision bump.

**Comment by Bo98** [comment]
Hmm, looks like `osm2pgrouting` isn't compatible with libpqxx 7.x.

**Pull request closed without merging**
