### PR TITLE
libpq 10.3

### PR DESCRIPTION
**Pull request by rakkesh**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
I did not use `brew bump-formula-pr` as there was a need to update `homepage` URL for version 10.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why close this?

**Comment by rakkesh** [comment]
I wasn't sure if this was needed in `homebrew` at the moment, as it seemed that the build was aborted by human intervention. Apologies for my wild assumptions.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Many thanks @rakkesh for the pull request!

(minor nit: please, next time include revision bumps as a separate commit)

**Pull request closed without merging**
