### PR TITLE
faust 2.41.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
```
  csound:
    * csound contains conflicting version recursive dependencies:
        python@3.10, python@3.9
      View these with `brew deps --tree csound`.
  Error: 1 problem in 1 formula detected
  Error: csound contains conflicting version recursive dependencies:
    python@3.10, python@3.9
  View these with `brew deps --tree csound`.
  ```

But the tree only shows `python@3.9` deps, no `python@3.10` there.

**Comment by Porkepix** [comment]
> > brew deps --tree csound
> 
> Did you run that?

Yes, my above comment relates to the fact I didn't found any `python@3.10` occurrences in it.

**Comment by SMillerDev** [comment]
It does show python@3.10 if you add `--include-build`

**Comment by Porkepix** [comment]
> It does show python@3.10 if you add `--include-build`

But if it's only used for build, then it shouldn't cause any dependencies conflicts, right?

**Comment by SMillerDev** [comment]
Well, if it builds python modules but doesn't use those itself at runtime you'll have a conflict.

**Comment by carlocab** [comment]
`csound` needs a revision bump since it linked to `llvm@12`'s `libc++`.

**Comment by cho-m** [comment]
> Added `csound` to the conflict allowlist. It seems unlikely to be an issue, unless `csound` links with `liblldb` or otherwise uses its Python bindings.

@carlocab We hit an issue with `csound` on Linux which has been built with conflicting Python versions in dependency tree.

As I mentioned in https://github.com/Homebrew/homebrew-core/pull/103879#issuecomment-1168183894
> EDIT: `csound` is a "good" example of potential risk in having multiple Python's in build environment. Looks like the .pth file was created for Python 3.9 but libraries were built with linkage to Python 3.10, so both Pythons are being used in formula. Removing `python@3.10` from `llvm` will clean up the dependency tree and we can rebuild bottle, maybe with some absolute paths to avoid mixing in future.

**Comment by carlocab** [comment]
Hm, can we just let `csound` use `python@3.10`?

**Comment by cho-m** [comment]
> Hm, can we just let `csound` use `python@3.10`?

We could probably find a way to force the build to only use `python@3.10`. I think the .pth and plugins are part of issue: 
```rb
    (prefix/Language::Python.site_packages("python3")/"homebrew-csound.pth").write <<~EOS
      import site; site.addsitedir('#{libexec}')
    EOS
    resource("csound-plugins").stage do
```
- In case of `homebrew-csound.pth` file, we need to change `"python3"` to an absolute path as Homebrew seems to be inconsistent in which version it picks up. On Linux, it has been using `python@3.9`, but it looks like it is using `python@3.10` on macOS.
- `csound-plugins` uses `find_package(Python3 COMPONENTS Interpreter Development)` to detect which Python. On Linux, it picks up `python@3.10`. Not sure what it is using on macOS.

---

In case of a cleaner dependency tree, it is easier to use `python@3.9` as #103879 should be enough for that while `python@3.10` is pending on `glib` split.

**Comment by carlocab** [comment]
I wonder if also we should consider:

1. installing the `csound-plugins` into `prefix` so we don't have to write a `.pth` file.
2. separating `csound-plugins` into a separate formula. This might make it easier to manage its dependency tree.

Thoughts? CC @nwhetsell

**Comment by cho-m** [comment]
The `.pth` file is actually for [`ctcsound.py`](https://github.com/csound/csound/blob/master/interfaces/ctcsound.py) which is included with `csound`.

The plugin that has linked to Python library is separate https://github.com/csound/plugins/tree/develop/py

So, each feature may still function if they are set to use different Python, but functionality will break if we remove the indirect Python.

**Comment by carlocab** [comment]
Where do we install `ctsound`?

**Comment by cho-m** [comment]
> Where do we install `ctsound`?

https://github.com/Homebrew/homebrew-core/blob/aa1bbde6150233e8cb5c7c632e0d4d283cf4e0b3/Formula/csound.rb#L106

**Comment by carlocab** [comment]
I wonder if we should just install that into `site-packages`. It doesn't even look picky about the Python version, except that it seems to require `numpy`.

**Comment by nwhetsell** [comment]
@carlocab

> I wonder if we should just install that into `site-packages`.

As far as I know, `ctcsound.py` will work with any Python version, so if installing directly into `site-packages` will fix this, I’d say that’s the way to go.

@cho-m

> For splitting formula, I think it is worth considering given the number of `csound` revision bumps we've seen in order to update the plugins resource.

I absolutely trust Homebrew maintainers’ judgment on this, but the pace of updates to the `csound-plugins` resource should be much, much slower going forward. Many, if not all, of the previous updates were related to me fixing upstream issues to make things work with Homebrew, not from direct development of the plugins.

**Pull request closed without merging**
