### PR TITLE
GCC: Xcode 10 2 patches

### PR DESCRIPTION
**Pull request by zbeekman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zbeekman** [comment]
@fxcoudert This patches 5, 6, 7 and updates the patch for GCC.

i.e., #39041

**Comment by fxcoudert** [comment]
Thanks @zbeekman!
I don't see the point of guarding it with `if MacOS::Xcode.version >= "10.2"` given that the `fixinclude` itself is restricted to `*-*-darwin18*`… but it cannot hurt, so let's not rerun the whole thing on CI.

**Comment by zbeekman** [comment]
@fxcoudert Ok, but don’t we need bottles for gcc@5, gcc@6 and gcc@7? These
are the first time the patches are applied to them with revision bumps.
Users will be building from source unless we bottle them.

**Comment by mbhall88** [comment]
gcc@4.9 also needs this patch as I am also getting the same `_Atomic` related errors.

**Comment by zbeekman** [comment]
@mbhall88: Generate a patch for us, and we can apply it. 😉

I have no intention of using 4.9 anytime soon, and, given that I can't build and test it locally on my Mojave machines, I'll need someone else to come up with the patch for 4.9. fink only has patches as far back as 5, AFAICT.

**Comment by mbhall88** [comment]
Ah ok fair enough. I would have no idea how to do that sorry otherwise I would have done it myself.

**Comment by zbeekman** [comment]
I inquired if someone has a patch handy on the gcc bug tracker. We’ll see
if anyone bites.

**Pull request closed without merging**
