### PR TITLE
svt-av1: fix sha256 checksum

### PR DESCRIPTION
**Pull request by qianbinbin**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by qianbinbin** [comment]
I tried different versions of `curl`,

when downloading from `gitlab.com` they behaves differently:

```sh
❯ /usr/bin/curl -V
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
❯ /usr/bin/curl -L https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.4.1/SVT-AV1-v1.4.1.tar.bz2 | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9222k    0 9222k    0     0   489k      0 --:--:--  0:00:18 --:--:--  706k
2ddef549e1eaeecc1fc48f0d8332ea3545809e46509db69beb3a0a4bf19ef906  -

❯ /usr/local/opt/curl/bin/curl -V
curl 8.0.1 (x86_64-apple-darwin19.6.0) libcurl/8.0.1 (SecureTransport) OpenSSL/1.1.1t zlib/1.2.11 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
❯ /usr/local/opt/curl/bin/curl -L https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.4.1/SVT-AV1-v1.4.1.tar.bz2 | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9218k    0 9218k    0     0   344k      0 --:--:--  0:00:26 --:--:--  574k
0e988582f315fe76c909accf5e7f81b975c5bd2b850ee760d8e9fac297f70b5d  -
```

but for `github.com` they just behaves the same:

```sh
❯ /usr/bin/curl -L https://github.com/Homebrew/homebrew-core/raw/master/Formula/svt-av1.rb | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100  1995  100  1995    0     0    227      0  0:00:08  0:00:08 --:--:--   557
a95e6e7106cd49e8478b32b17faa39c3d812d257e474159a83a9880b7b6c6933  -
❯ /usr/local/opt/curl/bin/curl -L https://github.com/Homebrew/homebrew-core/raw/master/Formula/svt-av1.rb | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  1995  100  1995    0     0    536      0  0:00:03  0:00:03 --:--:--  4182
a95e6e7106cd49e8478b32b17faa39c3d812d257e474159a83a9880b7b6c6933  -
```

Hi @carlocab , is this a problem by `curl` or gitlab? Thanks in advance.

**Comment by qianbinbin** [comment]
It seems a problem caused by gitlab: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12494

```sh
❯ /usr/bin/curl -fsSL https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.4.1/SVT-AV1-v1.4.1.tar.bz2 >old
❯ /usr/local/opt/curl/bin/curl -fsSL https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.4.1/SVT-AV1-v1.4.1.tar.bz2 >new
❯ diff -u <(xxd old | head -n 1) <(xxd new | head -n 1)
--- /dev/fd/13	2023-03-30 23:27:25.000000000 +0800
+++ /dev/fd/14	2023-03-30 23:27:25.000000000 +0800
@@ -1 +1 @@
-00000000: 425a 6839 3141 5926 5359 ba6f a988 04cb  BZh91AY&SY.o....
+00000000: 425a 6839 3141 5926 5359 ce3b f655 04cf  BZh91AY&SY.;.U..
```

**Comment by qianbinbin** [comment]
Thank you @carlocab , sorry I made a mistake, but it still seems a problem of gitlab, what should we do with that?

**Comment by carlocab** [comment]
I don't think it's a problem with GitLab. It seems to me more like a configuration problem on your machine.

**Comment by qianbinbin** [comment]
No, I can confirm that and I have no reason to waste our time here. I'm stuck by this for hours.

For some reason gitlab returns 2 different files with exactly the same URL, I can reproduce in macOS and 4 different Linux servers.
In my Linux servers, even with the same `curl` but at different times, gitlab may return different files.

Maybe I should give up, feel free to close the PR. But I doubt someone may encounter similar problem too.
Thanks for your reply.

**Comment by carlocab** [comment]
Ok, then it's probably best to report this upstream to see what they have to say about it.

**Comment by qianbinbin** [comment]
True that it's not a good idea to simply update the checksum..

**Comment by qianbinbin** [comment]
Follow up: https://forum.gitlab.com/t/different-checksums-for-the-same-archive/84143

**Comment by qianbinbin** [comment]
Closing due to [Gitlab's lack of interest](https://gitlab.com/gitlab-org/gitlab/-/issues/403597).

For now the bug cannot be reproduced, hope nobody would encounter the same problem.

**Comment by qianbinbin** [comment]
The issue should be fixed in https://gitlab.com/gitlab-org/gitlab/-/issues/402616 , brief explanation from a maintainer of Gitlab:

> The root cause was discussed in a confidential issue, but I can share a general idea what went wrong.
>
> One of deployed fixes had a side-effect of changing the hash sum of the archived files.
> When it was discovered, we reverted the code.
> However, Cloudflare still responded with old archive files for some regions.
> We updated the cache and that resolved the problem.

But `frotz` still seems affected, see https://github.com/Homebrew/homebrew-core/pull/127298

**Pull request closed without merging**
