### PR TITLE
openfortivpn 1.13.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
src/main.c:477:27: error: expected ')'
                        printf("%s%s%s%s%s%s", usage, summary, help_options,
                                               ^
src/main.c:76:24: note: expanded from macro 'usage'
"                    " RESOLVCONF_USAGE "[--ca-file=<file>]\n" \
                       ^
src/main.c:477:10: note: to match this '('
                        printf("%s%s%s%s%s%s", usage, summary, help_options,
                              ^
src/main.c:603:24: error: expected ')'
        fprintf(stderr, "%s", usage);
                              ^
src/main.c:76:24: note: expanded from macro 'usage'
"                    " RESOLVCONF_USAGE "[--ca-file=<file>]\n" \
                       ^
src/main.c:603:9: note: to match this '('
        fprintf(stderr, "%s", usage);
               ^
2 errors generated.
make: *** [src/openfortivpn-main.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by DimitriPapadopoulos** [comment]
We experienced the same error while packaging 1.13.0 for _Fedora_:
https://koji.fedoraproject.org/koji/taskinfo?taskID=42689499

It should be fixed in 1.13.1:
https://github.com/adrienverge/openfortivpn/commit/fa4be5b

**Comment by DimitriPapadopoulos** [comment]
Please skip 1.13.0 and package 1.13.1.

**Comment by chenrui333** [comment]
@DimitriPapadopoulos Thanks for letting us know, this PR is already pointing to use `v1.131`.

**Comment by chenrui333** [comment]
@DimitriPapadopoulos the new release it out, thanks for the help!

**Pull request closed without merging**
