### PR TITLE
gradle 7.3.2

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
```
  ==> Verifying checksum for 'd845dc3ef372b5eb13f6a75cc78c960ba9a0168520204ffa3cfa7a4a7ef6b5cf--gradle-7.3.2-all.zip'
  Error: gradle: SHA256 mismatch
  Expected: dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb103184582
    Actual: 8d4b75c97c5b74fcda1b049d1e9a3ef45c0d8af4974b2d384cc26d69deb8d46b
```

**Comment by bayandin** [comment]
This is weird

```
  ==> Verifying checksum for 'd845dc3ef372b5eb13f6a75cc78c960ba9a0168520204ffa3cfa7a4a7ef6b5cf--gradle-7.3.2-all.zip'
  Error: gradle: SHA256 mismatch
  Expected: 8d4b75c97c5b74fcda1b049d1e9a3ef45c0d8af4974b2d384cc26d69deb8d46b
    Actual: dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb10318458
```

**Comment by chenrui333** [comment]
that is not very good, seeing it with a different PR as well.

**Comment by bayandin** [comment]
Still no luck... 
It looks like on Apple Silicon checksum is `8d4b75c97c5b74fcda1b049d1e9a3ef45c0d8af4974b2d384cc26d69deb8d46b`, while on Intel it is`dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb103184582`

**Comment by bayandin** [comment]
> Still no luck... It looks like on Apple Silicon checksum is `8d4b75c97c5b74fcda1b049d1e9a3ef45c0d8af4974b2d384cc26d69deb8d46b`, while on Intel it is`dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb103184582`

**Comment by bayandin** [comment]
According to upstream `dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb103184582bayandin` is the right checksum:
```
$ curl -L https://services.gradle.org/distributions/gradle-7.3.2-all.zip.sha256
dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb103184582
```

**Comment by bayandin** [comment]
Reported upstream https://github.com/gradle/gradle/issues/19341. 
Fill free to add more details there

**Comment by big-guy** [comment]
Could you check this again? I think we've purged the right caches now.

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
