### PR TITLE
accio 0.5.5 (new formula)

### LINKED ISSUE #15: Add Accio to Homebrew Core
Now that Accio has passed the 50 stars, before everyone gets used to installing Accio via its Tap too much, we should try adding it to Homebrew Core. That also seems reasonable now given that Accio has stabilized a lot lately.

### PR DESCRIPTION
**Pull request by Jeehut**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This fixes https://github.com/JamitLabs/Accio/issues/15.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Fails to build on Sierra and High Sierra:

```
==> make install prefix=/usr/local/Cellar/accio/0.5.5
/private/tmp/accio-20190405-96610-lwy27y: error: package at '/private/tmp/accio-20190405-96610-lwy27y' requires a minimum Swift tools version of 5.0.0 (currently 4.2.0)
make: *** [accio] Error 1
```

**Comment by Dschee** [comment]
@fxcoudert I'm not sure how to fix that, I've already added the minimum Xcode 10.2 requirement, but if Swift 4.2.0 is used, then it has Xcode 10.1 installed only, isn't that the reason why it's failing?

Also please note that I haven't tested this with Sierra and High Sierra and I'm not even sure if with Swift 5 as a requirement support is even possible. Do you have any suggestions regarding that?

**Comment by fxcoudert** [comment]
Hum if it builds on limited platforms, is not widely tested, has few contributors… I'm worried it's not a good fit for Homebrew core at this stage. How about maintaining it in a personal/organisation tap for now? https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap We can then migrate it to core if it has many users.

**Comment by Dschee** [comment]
If it is ready for Homebrew Core now or later, I can't tell. It depends on the rules.

But I do have unit tests, even [integration tests](https://github.com/JamitLabs/Accio/blob/work/1000-frameworks/Demo/Package.swift) with many popular projects. But you probably meant that many people have tested it, well in that regard it's a relatively new project, therefore not many people have probably had the time to use it. In our company, about a dozen people use it on a daily basis.

Please note that I already maintain is as a tap. I just saw the project slowly getting known in the iOS community and thought it would make sense to get rid of the tap rather early, so people don't get into trouble with switching from tap to Core. Or isn't that a problem? I mean, does Homebrew Core prioritize Core over Taps?

Well, if it's too early now in you opinion, I will get back to here once I prepare the version 1.0.0 release, which I plan to make once most problems that might arise from the community are fixed.

**Comment by thii** [comment]
@Dschee FYI Xcode 10.2 requires macOS Mojave 10.14.3+.

**Comment by Dschee** [comment]
Thanks @thii for pointing that out. That might be the issue with the CI.
I will update this PR when I feel the project is ready to be part of Homebrew Core.

**Comment by Dschee** [comment]
We now have a version [1.0.0 milestone](https://github.com/JamitLabs/Accio/milestone/1) which we plan to finish before the end of june. As part of the milestone, I will also update this since I think when coming closer to version 1.0.0 Accio should fulfill the requirements mentioned by @fxcoudert regarding usage in the community (e.g. it's been mention in 4 different weekly Swift newsletters that I know of in the last 2 weeks). GitHub stars have [tripled](https://star-history.t9t.io/#JamitLabs/Accio), too since my last commit in this PR. I hope those are good signs!

**Comment by thii** [comment]
Since it requires Mojave to build, you may need to wait for another two years because Homebrew tends to support the last 3 major macOS versions.

**Comment by fxcoudert** [comment]
Closing, we'll consider 1.0.0 when it is ready.

**Pull request closed without merging**
