### PR TITLE
osmcoastline: remove lz4 dep

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

followup of #89042

### CODE REVIEW

**Comment by iMichka** [comment]
I saw that you added it in that PR, so I thought you were fixing something which was broken. Why remove it now?

**Comment by chenrui333** [comment]
> I saw that you added it in that PR, so I thought you were fixing something which was broken. Why remove it now?

Yeah, it got introduced when the test failed on 11-arm, and this PR mainly to assert that. (I did not wait for that gdal PR runs completely before jump on introducing the dependency)

**Comment by carlocab** [comment]
> I saw that you added it in that PR, so I thought you were fixing something which was broken. Why remove it now?

opportunistic linkage

**Comment by iMichka** [comment]
Removing it does make it fail, but only on 10.15 and 11. Weird.

**Comment by cho-m** [comment]
It is failing everywhere but the others are not bottled yet so CI passes.

Build-time dependency `libosmium` pulls in `lz4` and causes linkage.

You will need to set `-DWITH_LZ4=OFF` to prevent `osmcoastline` from automatically picking up `lz4`: https://github.com/osmcode/osmcoastline/blob/v2.3.1/CMakeLists.txt#L32
```cmake
option(WITH_LZ4 "Build with lz4 support for PBF files" ON)
```

Or, just keep `lz4` as dependency/feature.

**Comment by carlocab** [comment]
Oh, looks like it's on by default rather than just opportunistic linkage. I guess we can keep it.

**Comment by iMichka** [comment]
Agreed, let's keep it.

**Pull request closed without merging**
