### PR TITLE
redo 0.33

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Fails during install
```
==> ./redo install
env: python2: No such file or directory
```

I'm suprised this compiled before since the upstream states it [requires python2.7 and the sqlite3 module for python2.7](https://redo.readthedocs.io/en/latest/GettingStarted/). I would suggest adding `python@2` as a dependencies and maybe adding the `sqlite3` resource from pypi.

**Comment by igas** [comment]
@Moisan it builds now, but there is no `man` branch to install manpages. What should I do?

**Comment by Moisan** [comment]
You can remove the resource. It seems that the `redo install` builds the documentation and copies it at the right place. You can also remove the last two lines of the install block.

**Comment by igas** [comment]
Thanks @Moisan 

I've updated it.

**Comment by igas** [comment]
```
IOError: [Errno 6] Device not configured: '/dev/tty'
```

Not sure if it's CI or not.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
0.31 has been release as well. Can you update @igas ?

**Comment by igas** [comment]
@javian done

**Comment by fxcoudert** [comment]
```
Traceback (most recent call last):
  File "./md2man.py", line 2, in <module>
    import sys, os, markdown, re
ImportError: No module named markdown
Warning: md2man.py missing modules; can't generate manpages.
Warning: try this: sudo easy_install markdown BeautifulSoup
```

**Comment by igas** [comment]
I give up here...

**Pull request closed without merging**
