### PR TITLE
leptonica 1.83.1

### PR DESCRIPTION
**Pull request by osalbahr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
I'm not sure how `livecheck` works but to address the warnings here is the announcement of leptonica 1.83.1: https://github.com/DanBloomberg/leptonica/releases/tag/1.83.1

**Comment by chenrui333** [comment]
> I'm not sure how `livecheck` works but to address the warnings here is the announcement of leptonica 1.83.1: https://github.com/DanBloomberg/leptonica/releases/tag/1.83.1
> 
> ```
> % brew bump leptonica
> ==> leptonica
> Current formula version:  1.82.0
> Latest livecheck version: 1.83.0
> Latest Repology version:  1.83.1
> Open pull requests:       leptonica 1.83.1 (https://github.com/Homebrew/homebrew-core/pull/135822)
> Closed pull requests:     none
> % brew livecheck leptonica
> leptonica: 1.82.0 ==> 1.83.0
> ```

We should adjust livecheck per the `url` change

**Comment by osalbahr** [comment]
> We should adjust livecheck per the `url` change

Oh, makes sense.

As for the build errors, I noticed that `brew install leptonica && brew test-bot --only-formulae-dependents --junit --testing-formulae="leptonica"` fails in an Ubuntu VM too (on 1.82.0):
```console
Error: 5 failed steps!
brew install --only-dependencies aravis
brew install aravis
brew install --only-dependencies audacious
brew install --only-dependencies geeqie
brew install --only-dependencies mkvtoolnix
$ brew config
HOMEBREW_VERSION: 4.0.27
ORIGIN: https://github.com/Homebrew/brew
HEAD: 32ff40f688a49e02428eb3f20232aac69ffeeea0
Last commit: 12 hours ago
Core tap JSON: 05 Jul 12:54 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 16.0.6
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.0-76-generic x86_64 GNU/Linux
OS: Ubuntu 22.04.2 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mariadb
  mysql
```

**Comment by chenrui333** [comment]
why rollback?

**Comment by osalbahr** [comment]
> why rollback?

Sorry, forgot to write a comment I wanted to double-check that the CI failure was due to the version bump (as explained very briefly in the commit message). I wanted to undo the commit but forgot.

**Comment by osalbahr** [comment]
```console
==> brew install --only-dependencies ffmpeg
==> brew linkage --test ffmpeg
==> brew linkage --cached --test --strict ffmpeg
==> brew install --only-dependencies --include-test ffmpeg
==> brew test --retry --verbose ffmpeg
==> FAILED
Full test ffmpeg output
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
  ==> Testing ffmpeg
  ==> /home/linuxbrew/.linuxbrew/Cellar/ffmpeg/6.0/bin/ffmpeg -filter_complex testsrc=rate=1:duration=1 /tmp/ffmpeg-test-20230706-57771-17a9mud/video.mp4
  /home/linuxbrew/.linuxbrew/Cellar/ffmpeg/6.0/bin/ffmpeg: error while loading shared libraries: liblept.so.5: cannot open shared object file: No such file or directory
  ==> Testing ffmpeg (again)
  ==> /home/linuxbrew/.linuxbrew/Cellar/ffmpeg/6.0/bin/ffmpeg -filter_complex testsrc=rate=1:duration=1 /tmp/ffmpeg-test-20230706-57969-15ogahh/video.mp4
  /home/linuxbrew/.linuxbrew/Cellar/ffmpeg/6.0/bin/ffmpeg: error while loading shared libraries: liblept.so.5: cannot open shared object file: No such file or directory
  Error: ffmpeg: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/ffmpeg/6.0/bin/ffmpeg -filter_complex testsrc=rate=1:duration=1 /tmp/ffmpeg-test-20230706-57969-15ogahh/video.mp4
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2631:in `block in system'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2567:in `open'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2567:in `system'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ffmpeg.rb:148:in `block in <class:Ffmpeg>'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2406:in `block (3 levels) in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2405:in `block (2 levels) in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:987:in `with_logging'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2404:in `block in run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2682:in `mktemp'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2398:in `run_test'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

for some reason `ffmpeg` and others can't find the `liblept` library anymore.

**Pull request closed without merging**
