### PR TITLE
gucharmap 9.0.0

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
That's a slightly bizarre version jump for GNOME stuff. Definitely stable?

**Comment by dunn** [comment]
cc @tschoonj

**Comment by tschoonj** [comment]
This is legit. They seem to have abandoned the GNOME release versioning scheme for no obvious reason.

I remember that I tried updating the formula for 8.0.0 but that I ran into trouble with the external unicode files it tries to download.

**Comment by nijikon** [comment]
@DomT4 @tschoonj will this work?

**Comment by tschoonj** [comment]
You appear to have removed the checksum verification of the downloaded packages in that patch. Why was this necessary?

**Comment by nijikon** [comment]
You are correct. There is no `sha512sum` and I was not able to make `shasum` work with the checksum file. That's why I removed it.

**Comment by DomT4** [comment]
Can you elaborate on your efforts re `shasum`? The syntax, except the executable name, should be identical & work in the same manner.

I'm pretty dicey about completely killing off checksums here. We have a pretty firm policy against remote downloads executed by make processes already, let alone with no verification in place 🙈.

**Comment by nijikon** [comment]
@DomT4 `shasum -a 512 -c <checksum_file>`

**Comment by DomT4** [comment]
You don't need to specify the `-a 512`. `shasum` is intelligent enough to know what kind of checksum it is & as long as `shasum` can handle the algorithm will run through fine.

**Comment by tschoonj** [comment]
`sha512sum` is provided by `coreutils` (though the executable is prefixed with `g`). Could you give this one a try?

**Comment by nijikon** [comment]
I did also check without `-a`, it did not work.

**Comment by nijikon** [comment]
@tschoonj Oh, let me try that now.

**Comment by DomT4** [comment]
> I did also check without -a, it did not work.

```
shasum --check gucharmap-9.0.0.sha256sum
gucharmap-9.0.0.tar.xz: OK
```
That kind of thing works fine locally. Not in the `Makefile`?

**Comment by tschoonj** [comment]
Alternatively, you can add the unicode packages it downloads as resources, and point the `configure` script to their download location via the `--with-unicode-data` option. It is possible that it will try to run `sha512sum` on these files though...

**Comment by nijikon** [comment]
```
bash-3.2$ pwd
/private/tmp/gucharmap-20160704-67210-lmbz80/gucharmap-9.0.0
bash-3.2$ shasum --check gucharmap/unicode.sha512sums
shasum: gucharmap/unicode.sha512sums: no properly formatted SHA1 checksum lines found
```

**Comment by DomT4** [comment]
> shasum: gucharmap/unicode.sha512sums: no properly formatted SHA1 checksum lines found

Can you provide this file?

**Comment by nijikon** [comment]
```
bash-3.2$ cat gucharmap/unicode.sha512sums
SHA512 (Blocks.txt) = b841d4274de846d6931db8a4cc8fa5ec1a6b72e43b0693b53376015b121a38ca921ef1bf67dcc827ce93822d48806ec3afd4864fc123c5c4163c6372585377d7
SHA512 (DerivedAge.txt) = d2c0cfaccd936255c3c04907b16e74cc992c70a35283885e1e35c36bebe7199c4c50813309f5ffbfcd09b979c0201cc3953a40d0b2faad485b670d68700e0945
SHA512 (NamesList.txt) = 8651b522364b999f15052a2f1585a356f69a0ca69f248a75b7b610a163d45a84fc5eb8146c7a9ea72c913a160a9f2276a0f6dd06a72e3b60951a06f9843380a0
SHA512 (Scripts.txt) = 9c5e17c4731c1d9fb5e733b81b49ae815b36a390f6c3f02c0c4637e62dc59dde8e503956fa4378f85c215af2effad7907e846f49c514e640f494e5baf8b46ae6
SHA512 (UnicodeData.txt) = 43eaf66d9cb3748012b2dfd77da1b41f667c5c7602a56bea8186b796b215bde82d555d79ab053378c2222521396354dcce5cf23a78fa3b1456062c47771c8433
SHA512 (Unihan.zip) = 9856d30afe5d7b0b088bde36c12431eae267992b315944ca8a7ddb3559adee7474fedd2d0d6b22716439f9cddad573a4bb45c6209036b0066a85fbd19412852e
```

**Comment by nijikon** [comment]
Adding coreutils to build solves this, I think that we should go with that.

**Comment by DomT4** [comment]
They're apparently using GNU-exclusive syntax in their checksum file. Absolutely hilarious.

```
SHA512 (gucharmap-9.0.0.tar.xz) = 6054a392d719ebdb98205cb451b6971ca2ddc9d83b2de8b25412b0a561143d5ddb5b4fa0174ae997697b28dc79d60f477208bc6a112cb06346b250aa90e78fd7
```

```
gsha512sum --check gucharmap-9.0.0.sha512sum_p
gucharmap-9.0.0.tar.xz: OK

shasum --check gucharmap-9.0.0.sha512sum_p
shasum: gucharmap-9.0.0.sha512sum_p: no properly formatted SHA1 checksum lines found
```

I have no explanation for why you'd choose syntax that isn't portable in a _checksum file_.

**Comment by nijikon** [comment]
😸

**Pull request closed without merging**
