### PR TITLE
boost 1.79.0

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yhu266** [comment]
Are we fixing all of these revisions by hand? Is there a script to automate this process?

**Comment by SMillerDev** [comment]
The revisions depend on what's broken so it's all by hand.

**Comment by iMichka** [comment]
Closing in favour of #101577

**Comment by iMichka** [comment]
Sorry I had to close this PR @owine but boost is a slightly more complex update, and needs maintainer intervention to get proper build slots on our CI.
You can help at https://github.com/Homebrew/homebrew-core/pull/101577 nevertheless to fix any issues that would pop up.

**Pull request closed without merging**
