### PR TITLE
cstore_fdw: rename to citus

### PR DESCRIPTION
**Pull request by mchoo7**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

[Reference 1](https://github.com/citusdata/cstore_fdw/blob/master/README.md) [Reference 2](https://github.com/citusdata/cstore_fdw/blob/master/README.md)

cstore_fdw is now integrated into Citus since Citus 10.

### CODE REVIEW

**Comment by chenrui333** [comment]
I think it should be `deprecate` rather than removal.

**Comment by fel1x-developer** [comment]
> I think it should be `deprecate` rather than removal.

The reason that I think this should be removed is that the development of cstore_fdw is still ongoing on citus. Most people who want to use cstore_fdw might want the latest version, which is in the latest version of Citus. If we deprecate this, those people will still use the old version and that is not what they want.

**Comment by SMillerDev** [comment]
If you remove it, they will never know. If you deprecate it they will get a warning. I think the warning is better.

**Comment by fel1x-developer** [comment]
> If you remove it, they will never know. If you deprecate it they will get a warning. I think the warning is better.

How can I make .rb file to print warning?

**Comment by SMillerDev** [comment]
Deprecate the formula

**Comment by fel1x-developer** [comment]
Should the deprecation date be the date when the migration was announced or today?

**Comment by fel1x-developer** [comment]
I found the reason why this is failing. On ARM Mac, there is no `cstore_fdw-1.7.0/stage/opt/homebrew/`**`Cellar`**`/postgresql@13/13.9/lib/postgresql`. Instead there is `cstore_fdw-1.7.0/stage/opt/homebrew/`**`opt`**`/postgresql@13/13.9/lib/postgresql`

**Review by heatherleeann — COMMENTED** [review]
Fix

**Review by heatherleeann — COMMENTED** [review]
Formula/cstore_fdw.rb

**Review by SMillerDev — APPROVED** [review]
Thanks @fel1x-developer  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
