### PR TITLE
pipenv: enhance post-install

### PR DESCRIPTION
**Pull request by amancevice**
When users have an older version of Python linked, the post_install step breaks the installation..
This change gets the correct prefix for the *currently linked* version of the python formula.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
Won't this break anyway if you `brew switch python x`?

**Comment by amancevice** [comment]
I have both Python 3.6.5 and 3.7.0 installed with Homebrew on my machine. I occasionally switch to 3.7, but I do the vast majority of my development on 3.6 so for formulae that depend on Python I end up installing them with `--build-from-source`. For most formulae (eg, `awscli`, `ipython`) this works just fine but `pipenv` never did and I had to pin a version I had installed prior to the 3.7 change.

I opened an issue about this here: https://github.com/pypa/pipenv/issues/2965

**Comment by commitay** [comment]
As this formula is revision bumped for each python release it isn't expected that the current version will work with a pinned python.

**Comment by commitay** [comment]
> I do the vast majority of my development on 3.6

We usually recommend using something like `pyenv` rather than pinning.

**Comment by amancevice** [comment]
Sure, or Docker. This seemed like a pretty trivial change to me, though. And it should be functionally equivalent to the existing formula for folks on 3.7 but offers backwards compatibility for everyone else. I get that the backwards compatibility of the other formulae may be incidental but it's nice that they work.

**Comment by amancevice** [comment]
That’s disappointing, but thanks for taking the time to review.

**Pull request closed without merging**
