### PR TITLE
minizip2 2.8.9 (new formula)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

(Test fails with `Error: cannot load such file -- test/unit/assertions`. Investigating.)

### CODE REVIEW

**Comment by fxcoudert** [comment]
Yes, it is a fork of the original project, released under the same name. Some other distributions have integrated it as `minizip2` but that does not really fit with our usually naming scheme.
- If it were two versions of the same project, then it would simply be `minizip`, and the older one would be removed or become `minizip@1`
- If it's a fork, and it is sufficiently widely used for inclusion, then `nmoinvaz-minizip` is probably its name.

**Comment by vszakats** [comment]
@javian Yes, it was originally forked from there, but it's completely rewritten by now, and offers support for AES encryption, LZMA, ZIP64, BZ2, in-memory operation, volumes and lots more. Plus a retrofitted minizip 1.x compatibility interface.

**Comment by vszakats** [comment]
I'm not aware of other popular modern forks of the original (and long abandoned) minizip 1.x, so either `@2`, or the old one renamed to `@1` or even to `zlib-minizip` (as it was and still is [embedded](https://github.com/madler/zlib/tree/master/contrib/minizip) as a contrib inside the `zlib` source tree. `macports` [settled](https://www.macports.org/ports.php?by=name&substr=minizip) with `minizip2`. Other distros under discussion [here](https://github.com/nmoinvaz/minizip/issues/358).

No hard preference though. We may also rename later, when there is a general agreement amongst distros.

**Comment by vszakats** [comment]
@BrewTestBot Test this please.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
