### PR TITLE
jruby: prefix `erb` to avoid conflict

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

follow up of #122313

```
$ ls -1 /opt/homebrew/Cellar/ruby/3.2.0/bin/
bundle
bundler
erb
gem
irb
racc
rake
rbs
rdbg
rdoc
ri
ruby
typeprof

$ ls -1 /opt/homebrew/Cellar/jruby/9.4.0.0/bin/
erb
install_doc
jast
jbundle
jbundler
jgem
jirb
jirb_swing
jracc
jrake
jrdoc
jri
jruby
jruby.sh
jrubyc
lock_jars
```

### CODE REVIEW

**Comment by cho-m** [comment]
The install of `jruby` intentionally modifies executable names (e.g. `bundle -> jbundle`)  to avoid conflicting with `ruby`.

**Comment by chenrui333** [comment]
> The install of `jruby` intentionally modifies executable names (e.g. `bundle -> jbundle`) to avoid conflicting with `ruby`.

yeah, but the `erb` binary is using the same name.

**Comment by cho-m** [comment]
> yeah, but the `erb` binary is using the same name.

Which means it needs to be handled the same way.

**Review by carlocab — CHANGES_REQUESTED** [review]
Just add `erb` here:

https://github.com/Homebrew/homebrew-core/blob/15cc58f490ef218e460352ccd00ebf79f35b2491/Formula/jruby.rb#L31

**Comment by chenrui333** [comment]
that makes sense. Let me update the PR.

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Needs rebase.

**Comment by chenrui333** [comment]
Sorry about the delay. Should be good now.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
