### PR TITLE
kibana 7.13.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — COMMENTED** [review]
Isn't this the non-open-source license version? I thought the license changed for `7.11+`.

**Comment by chenrui333** [comment]
you are right, missed the license comment. Closing the PR and cancelled the build.

**Comment by carlocab** [comment]
Can we have an audit for this?

**Comment by nandahkrishna** [comment]
Homebrew/brew#11483

**Pull request closed without merging**
