### PR TITLE
urlview: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by danielnachun** [comment]
It looks like I botched the `inreplace` and it breaks the build on macOS.  The string interpolation is tricky because it has to be put inside double quotes.

**Comment by danielnachun** [comment]
The issues with quoting have been fixed now.

**Comment by danielnachun** [comment]
The issues with quoting have been fixed now.

**Review by SMillerDev — DISMISSED** [review]
@danielnachun please upstream the Linux fix or at least make an issue upstream.

**Review by chenrui333 — DISMISSED** [review]

**Comment by danielnachun** [comment]
I misunderstood the nature of this problem and realized after some test that no patching is actually need for building on Linux just an extra `CFLAG`.  For some reason now the build is failing on Big Sur suddenly.  This might need autoreconf to be run on macOS as well.

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Can you also add a test?

**Comment by danielnachun** [comment]
I've now added a very simple test to this.  `urlview` is intended to be a pure TUI interface that does not output anything to `stdout` or write any files, so the only thing we can do is launch it in a PTY and make sure it quits properly afterward.

**Review by chenrui333 — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
