### PR TITLE
deno 1.6.0

### PR DESCRIPTION
**Pull request by crunchtime-ali**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    Finished release [optimized] target(s) in 83m 03s
  Installing /usr/local/Cellar/deno/1.6.0/bin/deno
   Installed package `deno v1.6.0 (/private/tmp/deno-20201208-18034-ywy33s/deno/cli)` (executable `deno`)
warning: be sure to add `/usr/local/Cellar/deno/1.6.0/bin` to your PATH to be able to run the installed binaries
Error: Failure while executing; `/usr/local/Cellar/deno/1.6.0/bin/deno completions zsh` exited with 101. Here's the output:
```

**Comment by carlocab** [comment]
This appears to have been fixed here: https://github.com/denoland/deno/pull/8718

Any chance this can be turned into a patch? It would help me a great deal with https://github.com/Homebrew/homebrew-core/pull/66285

**Comment by carlocab** [comment]
I think this patch should work:

    # Remove at next version bump. Check that new release includes:
    # https://github.com/denoland/deno/pull/8718
    patch do
      url "https://github.com/denoland/deno/compare/df87bf1..e52ac4f.patch?full_index=1"
      sha256 "af8fb4b041bb8656187c9e0b2d270decc82a4a29dd8abd5269a02730810018ed"
    end

**Comment by crunchtime-ali** [comment]
> I think this patch should work:
> 
> ```
> # Remove at next version bump. Check that new release includes:
> # https://github.com/denoland/deno/pull/8718
> patch do
>   url "https://github.com/denoland/deno/compare/df87bf1..e52ac4f.patch?full_index=1"
>   sha256 "af8fb4b041bb8656187c9e0b2d270decc82a4a29dd8abd5269a02730810018ed"
> end
> ```

I just applied this patch. Thank you for the hint.

**Comment by carlocab** [comment]
Ok, guess the patch didn't apply cleanly. Sorry about that!

**Comment by gromgit** [comment]
Try this instead:
```
patch do
  url "https://github.com/denoland/deno/commit/cea42bec3272a8020f1d94afcf1a4cd7e3985553.patch?full_index=1"
  sha256 "640ece7aab8e7486ea0ec4bfd29ac7e980822a57d12123e802d022bdc7bbaed7"
end
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @crunchtime-ali!

**Pull request closed without merging**
