### PR TITLE
pcl 1.9.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
`pdal` needs to have its revision bumped.

**Comment by igas** [comment]
I've made revision changes but I don't think CI picked that one up.

**Comment by SMillerDev** [comment]
it did a build a couple of hours ago. I think it's just having issues keeping up.

**Comment by igas** [comment]
Ok, thanks @SMillerDev, I'll check in the morning than if it needs any changes.

**Comment by SMillerDev** [comment]
It does cause there's build errors like these:
`simulation is required but glew was not found`

**Comment by igas** [comment]
Failed due to CI issue, should be ok now

**Comment by fxcoudert** [comment]
Thanks @igas, almost there: we need it to be squashed into two separate commit: one for `pcl`, and one for the `pdal` revision bump (commit message: `pdal: bump revision for pcl`).

**Comment by SergioRAgostinho** [comment]
FYI: We're releasing 1.9.1 today or tomorrow. I might be worth to jump to that version directly.

**Comment by SergioRAgostinho** [comment]
It's out https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.9.1 . Thank you for submitting the update.

**Comment by igas** [comment]
Ready to merge.

**Comment by fxcoudert** [comment]
Thanks @igas and @SergioRAgostinho

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
