### PR TITLE
SVN/Git protocol upgrades and audit fixes around (1/2)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
looks like we'll need some branching here
```
==> brew fetch --retry clang-format --build-bottle --force
==> FAILED
==> Cloning https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2016-12-09/
svn: E170013: Unable to connect to a repository at URL 'https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2016-12-09'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted
==> Retrying download
==> Cloning https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2016-12-09/
svn: E170013: Unable to connect to a repository at URL 'https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2016-12-09'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted
Error: Failed to download resource "clang-format"
Failure while executing: svn checkout -q https://llvm.org/svn/llvm-project/llvm/tags/google/stable/2016-12-09/ /Users/brew/Library/Caches/Homebrew/clang-format--svn
```

**Comment by vszakats** [comment]
Added all four of them.

**Comment by vszakats** [comment]
Seems okay now. Failures were due to `downloads.sourceforge.net` connection problems.

**Comment by ilovezfs** [comment]
Thanks @vszakats

**Pull request merged**
