### PR TITLE
yq 2.1.0

### PR DESCRIPTION
**Pull request by mikefarah**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
looks like your orchestrated.io email isn't associated with your GitHub account?

**Comment by mikefarah** [comment]
Oh that's my work email - did I use that accidently? Can't see where it is...

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/29924.patch
https://github.com/Homebrew/homebrew-core/pull/29924/commits/2946d07380f6315151da01a8a66cef8c62ff8f2c.patch

**Comment by ilovezfs** [comment]
https://help.github.com/articles/setting-your-commit-email-address-in-git/
https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by mikefarah** [comment]
done - cheers @ilovezfs

**Comment by ilovezfs** [comment]
Thanks again @mikefarah! Shipped.

**Pull request closed without merging**
