### PR TITLE
luvit: build from source + depend on luajit-openresty

### PR DESCRIPTION
**Pull request by carlocab**
Follow up to #68787.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
There are three problems with this formula. It:
1. looks for an ARM version of `luvi`. This doesn't exist.
2. downloads un-checksummed (but versioned) files, and pipes at least one of them into `sh`.
3. downloads binary executables.

**Comment by SMillerDev** [comment]
All three are reasons for immediate disabling iyam.

**Comment by carlocab** [comment]
I actually have a fix for all three now. Except that it still won't build on ARM. Working on that right now.

**Comment by carlocab** [comment]
Resource `luvi` doesn't yet build on ARM. Upstream report: https://github.com/luvit/luvi/issues/243

**Review by SeekingMeaning — APPROVED** [review]

**Pull request closed without merging**
