### PR TITLE
libfuse 3.10.3

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
chown: changing ownership of '/home/linuxbrew/.linuxbrew/Cellar/libfuse/3.10.3/bin/fusermount3': Operation not permitted
```

Interesting

**Comment by carlocab** [comment]
`libfuse` seems to need root by default. Try passing `-Duseroot=false`.

https://github.com/Homebrew/homebrew-core/pull/74760

**Comment by dawidd6** [comment]
```
install: cannot create regular file '/etc/init.d/fuse3': Permission denied
```

**Comment by carlocab** [comment]
https://github.com/conda-forge/libfuse-feedstock/blob/fb966bfef17fa050eb0d2b819f7c6c06575962b9/recipe/0001-Install-fusermount-init-script-into-sysconfdir.patch

**Review by dawidd6 — APPROVED** [review]

**Pull request merged**
