### PR TITLE
freetype 2.6.4

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like `freetype` isn't building:

```
/private/tmp/freetype-20160705-8286-14yjavi/freetype-2.6.4/objs/.libs/ftbzip2.o /private/tmp/freetype-20160705-8286-14yjavi/freetype-2.6.4/objs/.libs/psaux.o /private/tmp/freetype-20160705-8286-14yjavi/freetype-2.6.4/objs/.libs/psnames.o   -lz -lbz2 -L/usr/local/Cellar/libpng/1.6.23/lib -lpng16    -install_name  /usr/local/Cellar/freetype/2.6.4/lib/libfreetype.6.dylib -compatibility_version 19 -current_version 19.4 -Wl,-single_module -Wl,-exported_symbols_list,/private/tmp/freetype-20160705-8286-14yjavi/freetype-2.6.4/objs/.libs/libfreetype-symbols.expsym
Undefined symbols for architecture x86_64:
  "_FT_GetFilePath_From_Mac_ATS_Name", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_GetFile_From_Mac_ATS_Name", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_GetFile_From_Mac_Name", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_New_Face_From_FOND", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_New_Face_From_FSRef", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_New_Face_From_FSSpec", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/private/tmp/freetype-20160705-8286-14yjavi/freetype-2.6.4/objs/libfreetype.la] Error 1
```
Failed on all three platforms.

**Comment by lembacon** [comment]
@DomT4 https://github.com/Homebrew/homebrew-core/pull/2740/commits/476a2f8c898f21c47f2c19b9d7ec99ce04738b83#diff-fdb4b3da74ad7dd5b0b0da20c510cc4aR28

Removed `include/freetype/ftmac.h` for now since this header (which will cause `apinames` to generate nonexistent symbols from it which will then cause the linker to fail) is completely useless unless `--with-old-mac-fonts` is enabled. And, I will later report it upstream.

**Comment by lembacon** [comment]
(FYI: This is introduced by a recent change set. http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=771d3c8ae25d5042a3f6b76a329ad3dd782eca66)

**Comment by DomT4** [comment]
We'll definitely need that reporting upstream before we can merge this, but it seems a reasonable enough workaround temporarily.

**Comment by lembacon** [comment]
It seems that someone has already filed the bug upstream. https://savannah.nongnu.org/bugs/?48417

**Comment by lembacon** [comment]
(too busy this week to find a time to write a bug report)

**Comment by lembacon** [comment]
Werner Lemberg, the maintainer of the FreeType project, [suggested](https://savannah.nongnu.org/bugs/?48417#comment1) to remove problematic symbols from the generated `libfreetype-symbols.expsym`, however, removing `include/freetype/ftmac.h` seems not an unacceptable workaround.

Suzuki Toshiya [confirmed](https://savannah.nongnu.org/bugs/?48417#comment3) that he is working on a fix in a week or so.

**Comment by lembacon** [comment]
Suzuki Toshiya has already [fixed](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=783cbcd67dee48e431cea376e16d350dcbfcb317) this.

I've updated the formula to use the official patch. cc @DomT4

**Comment by ilovezfs** [comment]
```
==> brew linkage --test libdrawtext
==> FAILED
Missing libraries:
  /usr/local/lib/libGLEW.1.12.0.dylib
```

**Comment by DomT4** [comment]
Leave it be. I'll handle that myself after merging this PR, I'm keen to avoid another 1hr+ CI run.

**Comment by ilovezfs** [comment]
@DomT4 I'm writing a test for libdrawtest now ;)

**Comment by DomT4** [comment]
Alright, I'll merge this in & let you get on with that then 😉.

**Comment by DomT4** [comment]
Merged. Thank you for your contributions to Homebrew @lembacon; we appreciate them! 😺

**Pull request closed without merging**
