### PR TITLE
aws-sdk-cpp 0.12.4

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Bump stable version from 0.10.15 to 0.12.4

### CODE REVIEW

**Comment by ilovezfs** [comment]
lol broken on Mavericks again

**Comment by ilovezfs** [comment]
You should be able to add `typedef int32_t CCStatus;` to CryptoImpl.cpp if it's 10.9 to
 shut it up. That type wasn't part of the public API until 10.10 but did exist in 10.9 under the hood.

**Comment by Jerzerak** [comment]
@ilovezfs should I patch that in or do an `inreplace`?

**Comment by ilovezfs** [comment]
@Jerzerak I'd start with the upstream report. You can point them to the following:

10.11: public
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60075.20.1
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60075.20.1/include/CommonCryptoError.h

10.9: private
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60049
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60049/include/CommonBigNum.h
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60049/include/CommonCryptoPriv.h

Hopefully they'll fix it with a commit we can then apply as a patch in the formula until their next release.

**Comment by Jerzerak** [comment]
@ilovezfs ok thanks!

**Comment by ilovezfs** [comment]
Since upstream doesn't seem to be testing this on 10.9 at all, perhaps the right course of action would be to limit the formula to >= Yosemite, rather than forcing 10.9 back compatibility on them each time it breaks.

@MikeMcQuaid thoughts?

**Comment by MikeMcQuaid** [comment]
@ilovezfs I think that's a question worth raising with upstream and whatever they decide to "officially" support we can do the same 👍

**Comment by Jerzerak** [comment]
@MikeMcQuaid @ilovezfs Fix was just pushed [here](https://github.com/aws/aws-sdk-cpp/commit/c39a76bf8d49688281cca27e628668dd823d39ca)...should we wait until they respond per their "official" 10.9 support stance or am I ok to PR [0.12.4](https://github.com/aws/aws-sdk-cpp/releases/tag/0.12.4)?

**Comment by ilovezfs** [comment]
@Jerzerak 0.12.4 is fine. I was mainly just wanting to communicate to them that they shouldn't feel compelled to support 10.9 just for our sake. If they've fixed the 10.9 API issue, that's good enough for me :). Feel free to change the title of this PR and force push 0.12.4 or close it and open a fresh one.

**Comment by Jerzerak** [comment]
@ilovezfs Any chance of getting this merged now?

**Comment by ilovezfs** [comment]
@Jerzerak :tada: Thanks for handling the upstream issue and getting this :100:

**Pull request closed without merging**
