### PR TITLE
vercel-cli: rename from now-cli

### PR DESCRIPTION
**Pull request by unitof**
Rename `now-cli` to `vercel-cli`

Also removes scheduled deprecations and fixes Brew's `vercel update` override

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by unitof** [comment]
Workflow action github.com/Homebrew/actions/label-pull-requests is failing with `Error: Unexpected token t in JSON at position 2731`. I don't have access to that Action repo to diagnose what's going on though.

**Comment by unitof** [comment]
`tests` failing because `New formulae in homebrew/core should not have a `bottle do` block`, likely because this is a formula rename. I'm leaving the `bottle do ... end` block as-is, as [instructed](https://docs.brew.sh/Formula-Cookbook#updating-formulae) but let me know if anything else is needed.

**Comment by Rylan12** [comment]
Thanks for your first PR, @unitof!

> `triage` Workflow action github.com/Homebrew/actions/label-pull-requests is [failing](https://github.com/Homebrew/homebrew-core/pull/65904/checks?check_run_id=1470678794) with `Error: Unexpected token t in JSON at position 2731`. I don't have access to that Action repo to diagnose what's going on though.

No worries here, not your fault (actually, it was mine 😅). Should be fixed next time you push.

> `tests` failing because `` New formulae in homebrew/core should not have a `bottle do` block ``, likely because this is a formula rename. I'm leaving the `bottle do ... end` block as-is, as [instructed](https://docs.brew.sh/Formula-Cookbook#updating-formulae) but let me know if anything else is needed.

I appreciate you reading the docs ahead of time! It turns out that we _do_ need the bottle blocks removed here, though. Even though it's technically a rename, it's as if we're creating a new formula and deleting the old one.

**Comment by unitof** [comment]
Thanks a bunch! On it.

**Review by Rylan12 — APPROVED** [review]

**Comment by unitof** [comment]
@Rylan12 Heads up that Triage task is still conkin' out

**Comment by Rylan12** [comment]
Thanks, yeah, not sure what's going on. It seems to be working on other PRs...

Don't worry about it though, I'll manually merge in a minute. Thanks so much for your first Homebrew PR! Contributors like you are the reason we're able to keep Homebrew maintained to the standard that we can, so thanks again!

**Pull request closed without merging**
