### PR TITLE
harfbuzz 7.3.0

### PR DESCRIPTION
**Pull request by chiefmikey**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Comment by SMillerDev** [comment]
`macOS 13-arm64 (deps)` had `trino` and `walkmod` failing with issues where I can't see the relevance to this PR.

**Review by carlocab — APPROVED** [review]

**Comment by fxcoudert** [comment]
11-arm64 is stuck, but we saw no related failure on any of the other dependents.

**Comment by carlocab** [comment]
It did get stuck, but somehow got unstuck at some point:
```
Thu, 11 May 2023 16:33:52 GMT
==> brew fetch --retry visp
Thu, 11 May 2023 16:35:11 GMT
==> brew install --only-dependencies visp
Thu, 11 May 2023 22:32:12 GMT
==> brew install visp
Thu, 11 May 2023 23:11:21 GMT
==> brew install --only-dependencies visp
Thu, 11 May 2023 23:13:19 GMT
==> brew linkage --test visp
```

**Comment by carlocab** [comment]
It looks like there are a bunch of broken Java formulae though. We should open a tracking issue and probably migrate them to an older Java.

**Comment by fxcoudert** [comment]
It's weird because when I cancelled it, I had a window open for several hours and it was not streaming anything anymore.

**Pull request merged**
