### PR TITLE
Install VTK Python modules to correct location

### LINKED ISSUE #43953: VTK Python modules installed to incorrect location
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [-] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

Not exactly. `brew install` works fine. VTK is installed and working. It is the Python component of VTK which is incorrect.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/0a211ba4dfb18791f45f0d2f88dcfbfd

When I look at that gist, I notice this is my supposed fix.?. Which I have been mocking with `brew edit vtk` (hence revision 3). I am not going to pretend to know how `brew gist-logs` figured that out, even after I started over by removing /usr/local/*

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Import VTK using Python.

- What happened (include command output)

The path to python/site-packages is not where it should be. It appears to be located at:

   /usr/local/opt/vtk/lib/usr/local/Cellar/vtk/8.2.0_2/lib/python3/site-packages

Not at all where the Ruby formula says it should be.

- What you expected to happen

I expect site-packages to reside at:

   /usr/local/opt/vtk/lib/python3.7/site-packages

- Step-by-step reproduction instructions (by running `brew install` commands)

Install Homebrew...
```pre
brew update
brew install vtk
```

### PR DESCRIPTION
**Pull request by milljm**
Install python site-packages to correct location.
Add caveat to assist the user with environment variables.

Closes #43953

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

The audit is failing at line 73. It does not like the slice command.

-----

### CODE REVIEW

**Comment by milljm** [comment]
Brew audit failure:

```pre
vtk:
  * C: 73: col 10: Prefer `to_s` over string interpolation.
Error: 1 problem in 1 formula detected
```

**Comment by iMichka** [comment]
Wondering why we need the caveat for the PYTHONPATH at all. I think there is a default caveats for python modules in brew, or at least if should work out of the box. I need to test this.

**Comment by milljm** [comment]
I... do recall brew install telling me _something_ about PKG_CONFIG_PATH, but not PYTHONPATH.
Not 100% sure. I'll spend some time over here and test as well. I also wonder if by me adding caveats, does brew install now _not_ tell me about PKG_CONFIG_PATH.

**Comment by fxcoudert** [comment]
Different formulas will have different ways of working. Some Python formulas are apps, so nothing needs to be set. Some Python formulas provide modules, where `PYTHONPATH` needs to be set.

Other formulas typically don't have a caveat for `PYTHONPATH`, so I'd skip it here. If we want to start including it, it should be systematic indeed.

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
