### PR TITLE
swiftlint 0.50.0

### PR DESCRIPTION
**Pull request by jpsim**
Created with brew `bump-formula-pr`.

Released here: https://github.com/realm/SwiftLint/releases/tag/0.50.0

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
> SwiftLint now requires Swift 5.7 or higher to build.

**Comment by chenrui333** [comment]
@jpsim there is some build issue

```
  [31/32] Compiling SwiftLintTestHelpers RuleDescription+Examples.swift
  /private/tmp/swiftlint-20221118-10407-1bgd35w/Tests/SwiftLintTestHelpers/TestHelpers.swift:3:18: error: module 'SwiftLintFramework' was not compiled for testing
  @testable import SwiftLintFramework
  ~~~~~~~~~~       ^
  swift_driver/main.swift:42: Fatal error: Invalid state, could not kill process
```

**Comment by jpsim** [comment]
Yes I know what’s happening here and will fix it shortly.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks!

**Pull request closed without merging**
