### PR TITLE
syncthing 0.12.22

### PR DESCRIPTION
**Pull request by mbi**
This is a security release. https://twitter.com/syncthing/status/720190819936944129
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by apjanke** [comment]
Audit failure.

```
failed: brew audit syncthing

Stacktrace

        Error: 1 problem in 1 formula
syncthing:
 * Please set plist_options when using a formula-defined plist.
```

This check was added recently. Could you try and add a plist_options line? Check other formulae for usage but it's basically a manual start instruction e.g. plist_options :manual => "mysql.server start"

**Comment by mbi** [comment]
@apjanke surething. Updated and audited the formula.

**Comment by apjanke** [comment]
:+1:

Merged. Thank you for your contribution to Homebrew!

**Comment by apjanke** [comment]
Closed by  132c5a062f2a08bd6ed0b43bcd4c30dd713ce9d8

**Comment by mbi** [comment]
@apjanke whelp! So the current value of `plist_options` is not working and synchthing doesn't start any longer with the current value.

Basically what we need is that the launchctl plist is copied to `~/Library` like before, but with the current value it is copied to `/Library`.

Is there any way we can get back to this state?

```
To reload syncthing after an upgrade:
  launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist
==> Summary
🍺  /usr/local/Cellar/syncthing/0.12.22: 6 files, 13.9M, built in 17 seconds
```

**Comment by apjanke** [comment]
Does `plist_options :manual => "syncthing"` work?

**Comment by mbi** [comment]
It does, thank you, I'm going to create a new PR.

**Comment by mbi** [comment]
@apjanke here it is, for reference PR #279

**Pull request closed without merging**
