### PR TITLE
tinytex 2020.09.19 (new formula)

### PR DESCRIPTION
**Pull request by yihui**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Hi, I'm trying to add a new formula for TinyTeX: https://github.com/yihui/tinytex. Thanks!

### CODE REVIEW

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by yihui** [comment]
Thanks! I didn't actually expect this to be merged into homebrew-core, but was hoping to contribute it as a cask instead. I submitted the PR just because the cask repo requested that authors try to submit a PR to this repo (and get rejected) before contributing there.

```
GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

BTW, for the criteria for notability, it should check the repo https://github.com/yihui/tinytex (which has more than 500 stars at the moment). The repo https://github.com/yihui/tinytex-releases is only a repo to store the released versions of TinyTeX. Will 500 stars be considered notable?

**Comment by SMillerDev** [comment]
Yes, 500 would be okay. The reason it can't be a cask is because it's open source software so you should just make a formula that builds it from source. That way it'll also met the notability requirements because you're using the actual source.

**Comment by yihui** [comment]
Building from source will be a much much more complicated task (http://www.tug.org/texlive/build.html). I don't think I'll have time to figure that out. TinyTeX is based on TeX Live, and it's much easier to obtain TeX Live through its installer (http://www.tug.org/texlive/acquire-netinstall.html), which basically downloads precompiled binaries.

In the unlikely event that I figure it out, there is still an obstacle that would prevent this formula from being included in homebrew-core. That is, the `bin` directory doesn't have any binaries, and the actual binaries are placed under a subdirectory `bin/x86_64-darwin/`. Homebrew doesn't like this, but unfortunately there isn't a way to change this path (I've confirmed with TeX Live developers).

So it is much easier to install TinyTeX as a precompiled binary package, which is a self-contained folder. With a cask, it won't matter what the `bin/` directory structure is. 

> The reason it can't be a cask is because it's open source software so you should just make a formula that builds it from source.

That reason doesn't seem to be valid. A lot of casks are open-source software, such as Atom and Firefox.

**Comment by gromgit** [comment]
> the `bin` directory doesn't have any binaries, and the actual binaries are placed under a subdirectory `bin/x86_64-darwin/`. Homebrew doesn't like this, but unfortunately there isn't a way to change this path (I've confirmed with TeX Live developers).

That's true for pretty much every Java formula too. They generally get around it by installing everything under a subdirectory of `#{libexec}`, then generating wrapper scripts for each executable JAR to be placed in `#{bin}`. You can also take this approach if some environment variables need to be set before running TinyTeX binaries, but if all you really need is just to make them visible in `#{bin}`, then `bin.install_symlink` is your friend.

> A lot of casks are open-source software, such as Atom and Firefox.

Atom and Firefox are casks for the same reason as most other open-source casks: They install macOS _applications_ (i.e. `/Applications/Firefox.app`), while Homebrew core only supports installation under `/usr/local`. If they were only meant to be launched from the command line, I'm sure they would've been in the core long ago.

I think @SMillerDev's point is:
* TinyTeX is open-source _and_ meant to be run from the command line, therefore it doesn't _have_ to be a cask
* its installation peculiarities aren't enough to prevent it from being in the core (other formulae successfuly work around their own quirks with wrapper scripts and/or symlinks)

So unless it can't be built from source for technical reasons, it should be a core formula, not a cask. The non-availability of TeX Live as a formula _might_ be one such reason.

**Comment by yihui** [comment]
@gromgit Thanks for your reply and explanation! I really appreciate it.

Creating symlinks to `bin/` is exactly what I did in this formula. The problem is this:

```
Error: 2 problems in 1 formula detected
tinytex:
  * Non-executables were installed to "/usr/local/opt/tinytex/bin"
    The offending files are:
      /usr/local/opt/tinytex/bin/x86_64-darwin
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

I can't get rid of the subdirectory `x86_64-darwin`. TeX Live requires this subdirectory to exist.

If I could get around this issue, I might be able to investigate more about how to build TeX Live from source.

**Comment by gromgit** [comment]
> I can't get rid of the subdirectory `x86_64-darwin`

You don't have to, and linking a directory into `/usr/local/bin` doesn't make sense anyway. Just link everything _inside_ that directory, so something like (untested):
```
libexec.install "bin"
bin.install_symlink Dir["#{libexec}/bin/*"]
```

**Comment by yihui** [comment]
@gromgit Oh I see now. I was using `prefix.install Dir["*"]` previously, which made Homebrew complain about the `bin/x86_64-darwin/` subdirectory. I'll try `libexec.install` instead. Thanks a lot for your tip!

**Pull request closed without merging**
