### PR TITLE
xmake: fix shasum

### PR DESCRIPTION
**Pull request by waruqi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by waruqi** [comment]
I need fix some problems for v2.3.1 tar archive.

**Comment by waruqi** [comment]
https://github.com/Homebrew/homebrew-core/issues/50797

**Comment by SMillerDev** [comment]
Why did the file change?

**Comment by waruqi** [comment]
> Why did the file change?

Because the original tar archive exists some problems. The installed program do not work very well. I need fix it.

run `xmake --version` and nothing happened after `brew install xmake`. But it works on ci.

And I need also fix some problems to support for other package repositories(termux/pkg).   https://github.com/termux/termux-packages/issues/4974

**Comment by waruqi** [comment]
@SMillerDev @Bo98 What should I do to modify shasum? The previous package had some problems and it need to be fixed

Since no other major changes have been made, there is no need to release a new version specifically.

**Comment by Bo98** [comment]
I've merged this pull request. Has it changed again?

**Comment by waruqi** [comment]
> I've merged this pull request ([1095cc0](https://github.com/Homebrew/homebrew-core/commit/1095cc06f961b0d3049262417c1c7dc9ee978083)). Has it changed again?

oh, I did not see this. I am sorry. No other changes again.

**Comment by Bo98** [comment]
No problem. The way we merge pull requests isn't very clear. We can't use GitHub's merge function as when we merge we need to add another commit with the updated bottles. Unfortunately, this means the pull request shows as "closed" rather than "merged".

**Comment by waruqi** [comment]
> No problem. The way we merge pull requests isn't very clear. We can't use GitHub's merge function as when we merge we need to add another commit with the updated bottles. Unfortunately, this means the pull request shows as "closed" rather than "merged".

Got it, thanks!

**Pull request closed without merging**
