### PR TITLE
lua 5.3.3

### PR DESCRIPTION
**Pull request by nloveladyallen**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
This won't work as-is. Last time we checked there remained incompatibilities with other formulae, which is why _this_ version of `lua` currently lives in `homebrew/versions/lua53`. See: https://github.com/Homebrew/legacy-homebrew/pull/47766.

If you actually want to try & update this you'll need to locally rebuild (using the `-s` flag) & test at least this bunch of formulae. Note some don't use `lua` by default so you'd need to invoke those options where necessary:
```
gegl
gnuplot
highlight
imapfilter
kyoto-tycoon
kyua
libquvi
libswiften
libucl
lsyncd
lutok
macvim
monotone
mpv
osm2pgsql
pdns
pdnsrec
rrdtool
sile
suricata
tracebox
vim
weechat
wireshark
homebrew/gui/cardpeek
homebrew/gui/hexchat
homebrew/versions/gegl02
homebrew/versions/gnuplot4
homebrew/x11/yarp
```

**Comment by nloveladyallen** [comment]
@DomT4 I tried a few of those, and they all seem to work, even though several failed in the CI.

**Comment by ilovezfs** [comment]
@nloveladyallen the CI failures are because it's testing the bottles which were built against the old lua. In most cases, you just need to "revision bump" them in a separate commit, one per formula, as part of this same pull request. That means, for example, increasing a `revision 1` in a formula to `revision 2`, or if the formula doesn't yet have a revision, it means adding `revision 1` to it. Here's an example for you: https://github.com/Homebrew/homebrew-core/pull/3269/commits

**Comment by DomT4** [comment]
Note that we'll pretty much need everything tested here.

**Comment by ilovezfs** [comment]
Closing for now, but please let us know if you'd like to try to handle this including the requisite revisions.

**Pull request closed without merging**
