### PR TITLE
cabal-install 3.4.0.0

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Second attempt at #71600.

### CODE REVIEW

**Comment by carlocab** [comment]
`cabal-install` 3.4 needs an existing `cabal-install` to bootstrap with.

I've currently gone the route of adding a formula for `cabal-install@3.2` (that doesn't need to be bootstrapped with yet another `cabal-install`) to bootstrap `cabal-install`.

Alternatives to this:

1. Download the `bootstrap.py` script from the Cabal repo.
2. Build a bootstrap `cabal-install@3.2` in the `cabal-install` formula first, then build `cabal-install`.

Using `bootstrap.py` will be tricky to pull off, since it requires a JSON file specifying its dependencies from Hackage. The only ones I could find upstream were for Linux.

The second is a bit more straightforward but doubles the time it takes to build `cabal-install`, and makes the `cabal-install` formula a bit more complicated to maintain.

Thoughts on this appreciated.

**Comment by jonchang** [comment]
Usually when bootstrapping we try to use an upstream binary from a previous version rather than making a daisy chain of brewed build dependencies. Could we use something in https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/ and add it as a `resource`?

**Comment by carlocab** [comment]
Whoops -- I was looking in Hackage and GitHub for a pre-built binary and couldn't find one. Thanks for tracking that down.

**Comment by carlocab** [comment]
Only failure is `pulp` on Catalina and Big Sur. Failure looks unrelated. Merging.

**Pull request closed without merging**
