### PR TITLE
grafana: fix sha256

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
... you know the question

**Comment by iMichka** [comment]
Sigh. Yes, I will open an issue upstream ...

I just noticed that while merging core into Linuxbrew ...

**Comment by iMichka** [comment]
Issue opened here: Issue opened here: https://github.com/grafana/grafana/issues/8815

**Comment by ilovezfs** [comment]
:bowing_man: thanks @iMichka

**Pull request closed without merging**
