### PR TITLE
haproxy 2.1.5

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/runs/724218316
```
==> Downloading https://www.haproxy.org/download/2.1/src/haproxy-2.1.5.tar.gz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Failed to download resource "haproxy"
Download failed: https://www.haproxy.org/download/2.1/src/haproxy-2.1.5.tar.gz
```

**Comment by chenrui333** [comment]
Let's try another run.

**Comment by alebcay** [comment]
I saw the same error locally when trying to install `ant` today (from Apache servers). Not sure what's going on.

**Comment by chenrui333** [comment]
> I saw the same error locally when trying to install `ant` today via Homebrew (which pulls from Apache servers). Not sure what's going on.

not quite sure either, the local ssl cert test seems ok too.

**Comment by dtrodrigues** [comment]
The sha should be `42174ac5836ab243565b888299ec30115c1259e75872696708528260c6700ea1`.

**Comment by dtrodrigues** [comment]
The expiration of the AddTrust CA probably explains the failure on 10.14: 
https://security.stackexchange.com/questions/232445/https-connection-to-specific-sites-fail-with-curl-on-macos

**Comment by dcorbett-haproxy** [comment]
The intermediate certificate has been updated.

**Comment by LeeHampton** [comment]
Just pinging this since I'm depending on 2.1.5 for a project. ;-) Is the only thing blocking this the sha mentioned by @dtrodrigues ?

**Comment by alebcay** [comment]
Presumably so. The rest of the CI can't run if we can't fetch the source code, of course, so if there's any issues with this release somehow, we've yet to find out.

**Comment by dcorbett-haproxy** [comment]
You should be able to fetch the source code now that the intermediate certificate was fixed. Are you still seeing issues?

**Comment by alebcay** [comment]
No, everything should be fixed now. Also was partly an error on my part. 🙃

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
