### PR TITLE
composer: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by Amar1729**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See #75943

### CODE REVIEW

**Comment by Amar1729** [comment]
```
> sha256sum *.tar.gz

5c57fc24e730c474ef5431a702b2a38cdbb39edbac9aa5869e163226172dc526  composer--2.0.12.arm64_big_sur.bottle.tar.gz
c477095403f8ea044a721282e8ebbb76557c52a1e3b75bd1a5552ed99a6f46fe  composer--2.0.12.big_sur.bottle.tar.gz
c477095403f8ea044a721282e8ebbb76557c52a1e3b75bd1a5552ed99a6f46fe  composer--2.0.12.catalina.bottle.tar.gz
a9fe04d8a2219b65c27e4e239d0133cbbb0ebd78564dc9c641085d38468a040c  composer--2.0.12.mojave.bottle.tar.gz
```

unpacked x86 big sur/mojave bottles don't differ.

```
> diff -r composer--2.0.12.arm64_big_sur.bottle composer--2.0.12.big_sur.bottle

Binary files composer--2.0.12.arm64_big_sur.bottle/composer/2.0.12/bin/composer and composer--2.0.12.big_sur.bottle/composer/2.0.12/bin/composer differ

> grep -a "PREFIX" composer--2.0.12.big_sur.bottle/composer/2.0.12/bin/composer                     

'@@HOMEBREW_PREFIX@@/share/certs/ca-root-nss.crt',
'@@HOMEBREW_PREFIX@@/share/curl/curl-ca-bundle.crt',
'@@HOMEBREW_PREFIX@@/etc/ssl/cert.pem',
'@@HOMEBREW_PREFIX@@/etc/openssl/cert.pem',
'@@HOMEBREW_PREFIX@@/etc/openssl@1.1/cert.pem',

> grep -a "PREFIX" composer--2.0.12.arm64_big_sur.bottle/composer/2.0.12/bin/composer

(no results)

>

```

**Comment by carlocab** [comment]
Rebased to pull in changes from #76020.

**Comment by Amar1729** [comment]
After rebuild:
```
> sha256sum *.tar.gz

dc169158657b27b6aa567165b59307fed32154d81cea584ea321e1fabb328503  composer--2.0.13.arm64_big_sur.bottle.tar.gz
4ba039c3ef483e8828ba7a65353e6af28da49227305566d9619ff58ba96ac281  composer--2.0.13.big_sur.bottle.tar.gz
4ba039c3ef483e8828ba7a65353e6af28da49227305566d9619ff58ba96ac281  composer--2.0.13.catalina.bottle.tar.gz
4ba039c3ef483e8828ba7a65353e6af28da49227305566d9619ff58ba96ac281  composer--2.0.13.mojave.bottle.tar.gz
```

**Comment by nandahkrishna** [comment]
Like `phpstan`, we won't be able to `inreplace` here as `phar` files are signed. (https://github.com/Homebrew/homebrew-core/pull/76044#issuecomment-828331054)

**Pull request closed without merging**
