### PR TITLE
lapack: import from homebrew/dupes

### PR DESCRIPTION
**Pull request by fxcoudert**
- Vendoring cmake 3.6.3 because lapack won't build with 3.7 or later
- Removing `with-doxygen` option: never used, requires special `doxygen` llvm build

### CODE REVIEW

**Comment by fxcoudert** [comment]
Test links fine, but fails to run with `dyld: Library not loaded: @rpath/liblapacke.dylib`

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by ilovezfs** [comment]
I think we may want to modify that rpath to be the opt path since this is keg_only. Really learning to regret https://github.com/Homebrew/brew/pull/2036.

**Comment by ilovezfs** [comment]
CC @woodruffw for thoughts.

**Comment by woodruffw** [comment]
> I think we may want to modify that rpath to be the opt path since this is keg_only.

Agreed, and I think https://github.com/Homebrew/brew/pull/2036 is going to continue to give us pain. I can make a PR to undo it tonight.

**Comment by MikeMcQuaid** [comment]
> Agreed, and I think Homebrew/brew#2036 is going to continue to give us pain. I can make a PR to undo it tonight.

Done in https://github.com/Homebrew/brew/pull/2450

**Review by MikeMcQuaid — APPROVED** [review]

**Review by ilovezfs — APPROVED** [review]

**Pull request closed without merging**
