### PR TITLE
pulumi 0.17.9

### PR DESCRIPTION
**Pull request by timmyers**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by timmyers** [comment]
Currently failing on this newly introduced dependency: https://github.com/pulumi/pulumi/blame/55b233fbdc4d59706f17d64e7618f28ddab6412d/go.mod#L43

**Comment by justinvp** [comment]
```
go: gocloud.dev@v0.13.0: unexpected status (https://gocenter.io/gocloud.dev/@v/v0.13.0.info): 404 Not Found
```

Hmm, was this just an intermittent network issue? Is there a way to restart Jenkins?

**Comment by justinvp** [comment]
It looks like v0.13.0 of go-cloud is missing on gocenter.io: https://search.gocenter.io/github.com~2Fgoogle~2Fgo-cloud/versions

@timmyers, Could you try updating this PR to remove the GOPROXY line?

https://github.com/timmyers/homebrew-core/blob/6376433a88e72167b8ec767cfee47e8dc2159b3e/Formula/pulumi.rb#L20

**Comment by lembacon** [comment]
Thanks @timmyers and @justinvp!

**Pull request closed without merging**
