### PR TITLE
imagemagick 7.0.2-1

### PR DESCRIPTION
**Pull request by nadavshatz**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
This will break other things without further changes. Please see https://github.com/Homebrew/homebrew-core/issues/1828. CC @rakkesh.

**Comment by nadavshatz** [comment]
Ah, bummer. got you.

**Comment by nadavshatz** [comment]
Rebased and updated version, PR title and commit message for when it's ready.

**Comment by rakkesh** [comment]
@nadavshatz for `ImageMagick` to build fine on the CI, this PR needs to contain the revision bump for all the dependent formulae. Currently few of the dependent formulae are broken due to change in path of  `MagickWand` headers. If the respective upstream devs for the broken packages don't respond in time, we need to use `inreplace` or a patch to fix them in `Homebrew`.

**Comment by nadavshatz** [comment]
@rakkesh got you. Wanted to make sure this is updated for that case to reduce friction. Sorry for the extra noise.

**Comment by gabrielmaldi** [comment]
Hi, I'd love to be able to install ImageMagick 7 with Homebrew. Are we still waiting for the broken dependent formulae to be fixed? Is there something we could do to help move this PR forward? Thanks.

**Comment by MikeMcQuaid** [comment]
@gabrielmaldi Open your own PR and do what [@rakkesh suggested](https://github.com/Homebrew/homebrew-core/pull/2209#issuecomment-229368489). Thanks!

**Comment by DomT4** [comment]
This seems to have gone dead so closing, but we will happily take an ImageMagick 7.x PR if anyone wants to do the work around [this](https://github.com/Homebrew/homebrew-core/pull/2209#issuecomment-229368489).

Thank you nonetheless for the submission to Homebrew @nadavshatz ❤️.

**Pull request closed without merging**
