### PR TITLE
*-binutils 2.40

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by satmandu** [comment]
Does this build for you on i686?

(I'm getting a build failure for binutils 2.40 for i686 on Chromebrew, so I thought I would ask over here...)

**Comment by chenrui333** [comment]
> Does this build for you on i686?
> 
> (I'm getting a [build failure](https://sourceware.org/bugzilla/show_bug.cgi?id=30006) for binutils 2.40 for i686 on Chromebrew, so I thought I would ask over here...)

I dont actually have a i686.

**Comment by chenrui333** [comment]
need a self-runner for texlive linux build (space issue).

**Comment by chenrui333** [comment]
only `packmol` failed, I think we follow up with it.

```
  ==> /home/linuxbrew/.linuxbrew/Cellar/packmol/20.12.0/bin/packmol < interface.inp
  
  ################################################################################
  
   PACKMOL - Packing optimization for the automated generation of
   starting configurations for molecular dynamics simulations.
   
                                                                Version 20.12.0 
  
  ################################################################################
  
    Packmol must be run with: packmol < inputfile.inp 
  
    Userguide at: http://m3g.iqm.unicamp.br/packmol 
  
    Reading input file... (Control-C aborts)
    Warning: Number of molecules not set for type            3 : assuming 1 
    Seed for random number generator:      1234567
  
  Program received signal SIGILL: Illegal instruction.
  
  Backtrace for this error:
  #0  0x7f3e44d139f2 in ???
  #1  0x7f3e44d12b85 in ???
  #2  0x7f3e449b151f in ???
  #3  0x55f804be3fa5 in ???
  #4  0x55f804bbb400 in ???
  #5  0x55f804bd479d in ???
  #6  0x55f804b912fe in ???
  #7  0x7f3e44998d8f in ???
  #8  0x7f3e44998e3f in ???
  #9  0x55f804b91344 in ???
  #10  0xffffffffffffffff in ???
  Illegal instruction (core dumped)
  Error: packmol: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/packmol/20.12.0/bin/packmol < interface.inp
```

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
merging and will followup on `packmol` on linux build

**Comment by chenrui333** [comment]
finished regression test, https://github.com/chenrui333/github-action-test/actions/runs/3940814839/jobs/6742400908

**Pull request closed without merging**
