### PR TITLE
kibana 7.8.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chrmoritz** [comment]
This shouldn't be merged either, because (unlike the `beats`) `kibana` requires the same minor version as `elasticsearch` according to [their compatibility matrix](https://www.elastic.co/de/support/matrix#matrix_compatibility) and the `elasticsearch` upgrade is blocked by `openjdk` 14.

**Comment by chenrui333** [comment]
relates to #51883

**Comment by SMillerDev** [comment]
@chrmoritz it's a test failure with the plugin, got any suggestions?

**Comment by chrmoritz** [comment]
After looking into it locally it looks like the plugin issue is only a warning and the real error comes from the test now trying to access a running `elasticsearch` instance to do some migration work.

```
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200710-67420-kraxz9.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kibana.rb --verbose
  log   [02:53:15.178] [warning][plugins-discovery] Expect plugin "id" in camelCase, but found: apm_oss
  log   [02:53:16.304] [info][plugins-service] Plugin "visTypeXy" is disabled.
  log   [02:53:16.509] [info][plugins-system] Setting up [42] plugins: [usageCollection,telemetryCollectionManager,telemetry,kibanaLegacy,devTools,newsfeed,mapsLegacy,uiActions,statusPage,share,kibanaUtils,kibanaReact,inspector,embeddable,esUiShared,indexPatternManagement,discover,charts,bfetch,expressions,data,home,console,apm_oss,management,advancedSettings,telemetryManagementSection,navigation,visualizations,visTypeVislib,visTypeVega,visTypeTimeseries,visTypeTimelion,visTypeMetric,visTypeTagcloud,visTypeTable,visTypeMarkdown,inputControlVis,savedObjects,visualize,dashboard,savedObjectsManagement]
==> curl -s 127.0.0.1:65453
  log   [02:53:16.741] [info][savedobjects-service] Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations...
  log   [02:53:16.765] [error][admin][elasticsearch] Request error, retrying
GET http://localhost:9200/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip => connect ECONNREFUSED 127.0.0.1:9200
  log   [02:53:16.783] [warning][admin][elasticsearch] Unable to revive connection: http://localhost:9200/
  log   [02:53:16.785] [warning][admin][elasticsearch] No living connections
  log   [02:53:16.786] [error][savedobjects-service] Unable to retrieve version information from Elasticsearch nodes.

```

**Comment by ankane** [comment]
Increasing the `sleep` to 10 or 20 seconds should fix the test.

**Comment by ankane** [comment]
Also needs license and alias to be updated to pass audit.

**Pull request closed without merging**
