### PR TITLE
lxi-tools 2.7

### PR DESCRIPTION
**Pull request by ghost**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>Changes since lxi-tools v2.6:

 * Fix print() when using lxi-gui

   Redirect output of print() to gui console window.

 * Disable getenv in lua example

   Maybe crash if TERM is not defined (nil)

 * Do not use deprecated math.pow in lua example

 * Add simple connect examples

 * Add homebrew to installation notes

 * Add NGL202 to list of tested instruments
</pre>
</details>

### CODE REVIEW

**Comment by robcarruthers** [comment]
[The extra commit](https://github.com/Homebrew/homebrew-core/pull/139973/commits/51d18a03708a31d86b23c76699ec9863142d407e) (fix glib error), fixes an error introduced in the original formula: `GLib-GIO-ERROR **: No GSettings schemas are installed on the system`. We mistakenly removed the schemas to workaround an error in the brew CI. This update regenerates the schema post install.

**Comment by iMichka** [comment]
> [The extra commit](https://github.com/Homebrew/homebrew-core/pull/139973/commits/51d18a03708a31d86b23c76699ec9863142d407e) (fix glib error), fixes an error introduced in the original formula: `GLib-GIO-ERROR **: No GSettings schemas are installed on the system`. We mistakenly removed the schemas to workaround an error in the brew CI. This update regenerates the schema post install.

- Is that error in the brew CI fixed, if not can you tell us which issue it is, just for reference
- Is the post install block always necessary or should it be removed with the next release?

**Comment by robcarruthers** [comment]
>     * Is that error in the brew CI fixed, if not can you tell us which issue it is, just for reference
I couldn't replicate the [linking error](https://github.com/Homebrew/homebrew-core/pull/137867#issuecomment-1656385421) locally, so rather than hit the CI until a solution was found we just worked around it.

>     * Is the post install block always necessary or should it be removed with the next release?
It's required for the current solution, where we remove `/opt/homebrew/share/glib-2.0/schemas/gschemas.compiled` during install, then `glib-compile-schemas` recreates the file in post_install. We observed this approach in other formula, but open to better solutions if you can help.

**Review by iMichka — DISMISSED** [review]
Ok this makes sense now. I guess we should add the same postinstall step for the `pulseaudio` formula, what do you think?

**Comment by iMichka** [comment]
Can you squash this to a single commit and remove the draft from the pull request?

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
