### PR TITLE
circleci 0.1.11062

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by Rylan12** [comment]
Last update was 3 days ago: https://github.com/Homebrew/homebrew-core/pull/62974

https://github.com/Homebrew/homebrew-core/blob/4bb8c2d58c1cccd854ad08dda4d121565fc6e8da/Formula/circleci.rb#L4

**Comment by chenrui333** [comment]
> Last update was 3 days ago: #62974
> 
> https://github.com/Homebrew/homebrew-core/blob/4bb8c2d58c1cccd854ad08dda4d121565fc6e8da/Formula/circleci.rb#L4

I think we can remove that (as we discussed this before).

**Comment by Rylan12** [comment]
> I think we can remove that (as we discussed this before).

I don't think we should remove it. I thought our decision was to continue to update at most once per week _rather than_ adding an official audit that wouldn't allow more frequent updates.

**Comment by chenrui333** [comment]
Either way sounds good with me, I will close this PR then. Thanks!

**Pull request closed without merging**
