### PR TITLE
apache-brooklyn-cli: add go 1.16 support

### PR DESCRIPTION
**Pull request by roopakv**
add support for go 1.16

#47627

Cannot open issue upstream, issues not enabled

### CODE REVIEW

**Comment by SMillerDev** [comment]
https://issues.apache.org/jira/projects/BROOKLYN/issues/BROOKLYN-545?filter=allopenissues is the issue tracker

**Comment by roopakv** [comment]
@SMillerDev i eventually got there, maybe it is just me but it didn't seem like anonymous users could open an issue on jira (or maybe i just don't understand JIRA :) )

**Comment by SMillerDev** [comment]
I didn't check that (but yeah, Jira sucks)

**Comment by roopakv** [comment]
I'm an idiot! open sign ups: https://issues.apache.org/jira/browse/BROOKLYN-629

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
