### PR TITLE
yq: update sha256

### LINKED ISSUE #754: Checksum issues when installing v4.6.2 with Brew AMD64
Version of yq: 4.6.2
Operating system: Linux x86 WSL2
Installed via: brew

Hi,

I'm hitting some issues while trying to upgrade `yq` via brew on Linux- Not sure some issues with the tar ball on the remote? I noticed some SHA256 checksum complaints. 

```sh
$> brew install --verbose --debug yq
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yq.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.0.7\ \(Linux\;\ x86_64\ Ubuntu\ 20.04.2\ LTS\)\ curl/7.68.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/mikefarah/yq/archive/v4.6.2.tar.gz
==> Downloading https://github.com/mikefarah/yq/archive/v4.6.2.tar.gz
==> Downloading from https://codeload.github.com/mikefarah/yq/tar.gz/v4.6.2
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.0.7\ \(Linux\;\ x86_64\ Ubuntu\ 20.04.2\ LTS\)\ curl/7.68.0 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://codeload.github.com/mikefarah/yq/tar.gz/v4.6.2
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.0.7\ \(Linux\;\ x86_64\ Ubuntu\ 20.04.2\ LTS\)\ curl/7.68.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /home/myuser/.cache/Homebrew/downloads/28ad2f8ceb85bc8366a8d75adf30776367015c22404aea8b53b5325e8e7bf48a--yq-4.6.2.tar.gz.incomplete https://codeload.github.com/mikefarah/yq/tar.gz/v4.6.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95176  100 95176    0     0   206k      0 --:--:-- --:--:-- --:--:--  206k
==> Verifying checksum for '28ad2f8ceb85bc8366a8d75adf30776367015c22404aea8b53b5325e8e7bf48a--yq-4.6.2.tar.gz'
Error: SHA256 mismatch
Expected: 767b6413738479c1f8446689ff6963a1db552bab6c7e27309be115146baf36b7
  Actual: 3edee5bae40afdf8869803c6f81eb15adbaaf373ba27e4907d6dd5dceebaf65c
    File: /home/myuser/.cache/Homebrew/downloads/28ad2f8ceb85bc8366a8d75adf30776367015c22404aea8b53b5325e8e7bf48a--yq-4.6.2.tar.gz
To retry an incomplete download, remove the file above.
```

### PR DESCRIPTION
**Pull request by felipecrs**
Fixes https://github.com/mikefarah/yq/issues/754.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @felipecrs.

Can you check upstream why the checksum changed? See also the CI output:
```
==> brew audit yq --online --git --skip-style
==> FAILED
yq:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
Error: 1 problem in 1 formula detected
```

For future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings. For example, your commit message here might have been
```
yq: update sha256
```
Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

**Comment by felipecrs** [comment]
Hey @mikefarah, do you know why the checksum of the archive for [v4.6.2](https://github.com/mikefarah/yq/releases/tag/v4.6.2) changed after its creation? Was the tag updated?

**Comment by felipecrs** [comment]
@carlocab thank you for the tip. Can this be merged before @mikefarah's answer? This is breaking `brew upgrade` for everyone who has `yq`.

**Comment by SMillerDev** [comment]
No, if this is a compromised release that would ship it to everyone.

**Comment by felipecrs** [comment]
Got it, thanks.

**Comment by felipecrs** [comment]
@carlocab @SMillerDev as stated by the yq's author, the tag was updated because of build error.

https://github.com/mikefarah/yq/issues/754#issuecomment-804380386

**Review by carlocab — APPROVED** [review]
Thanks, @felipecrs.

**Comment by mikefarah** [comment]
Sorry guys - won't update the tag again :(

**Comment by carlocab** [comment]
No worries @mikefarah. Plenty of people do it, so I know how tempting it is. It does cause a headache for your friends downstream tho 😅

**Pull request closed without merging**
