### PR TITLE
pytorch: use Homebrew deps, remove venv, add python@3.12

### PR DESCRIPTION
**Pull request by singingwolfboy**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/tmp/pytorch-20231112-11593-g4yxk3/torch/csrc/dynamo/eval_frame.c:784:5: error: call to undeclared function 'THP_PyFrame_Clear'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```

**Comment by singingwolfboy** [comment]
```
/tmp/pytorch-20231112-11541-1p5h9zn/torch/csrc/dynamo/eval_frame.c:784:5: error: implicit declaration of function 'THP_PyFrame_Clear' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      THP_PyFrame_Clear(shadow);
      ^
```

Any ideas? 😅

**Comment by chenrui333** [comment]
> ```
> /tmp/pytorch-20231112-11541-1p5h9zn/torch/csrc/dynamo/eval_frame.c:784:5: error: implicit declaration of function 'THP_PyFrame_Clear' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>       THP_PyFrame_Clear(shadow);
>       ^
> ```
> 
> Any ideas? 😅

there might be some upstream API change.

**Comment by chenrui333** [comment]
filed a new PR to bump pytorch to 2.1.1, https://github.com/Homebrew/homebrew-core/pull/154693

**Pull request closed without merging**
