### PR TITLE
node 13.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by billinghamj** [comment]
@chenrui333 Could you please remove these lines: https://github.com/Homebrew/homebrew-core/pull/47042/files#diff-d3ef2414308e30df24a517ca9a1324eeL25-L30

**Review by dio-az — CHANGES_REQUESTED** [review]
Could you also update `npm` to `6.13.1`?

**Comment by chenrui333** [comment]
> @chenrui333 Could you please remove these lines: https://github.com/Homebrew/homebrew-core/pull/47042/files#diff-d3ef2414308e30df24a517ca9a1324eeL25-L30

how is that related to this python3 tracker, https://github.com/nodejs/node/issues/25789

**Review by dio-az — APPROVED** [review]

**Comment by billinghamj** [comment]
Maybe it'll need a different patch or something.

**Comment by chenrui333** [comment]
Relates to my ungit PR, https://github.com/Homebrew/homebrew-core/pull/47057

**Comment by chenrui333** [comment]
ungit test step only failed on Mojave build though

12:21:21 ==> brew test --verbose ungit
12:21:24 ==> FAILED
12:21:24 Testing ungit
12:21:24 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191122-43085-w1oo9s.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb --verbose
12:21:24 Error: ungit: failed

**Comment by chrmoritz** [comment]
@chenrui333 The Python 3 patch is no longer needed because it's part of node `13.2.0` (that's what I've meant with 'remove with next version').

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Review by billinghamj — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks all for the participations and help!!

**Pull request closed without merging**
