### PR TITLE
usbutils 018

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
need to move to meson build and update the patch

**Comment by carlocab** [comment]
@nevack, do you mind taking a look at updating the patch? Thanks!

**Comment by nevack** [comment]
> @nevack, do you mind taking a look at updating the patch? Thanks!

Yes, I've seen the release and already tried something locally to make it buildable again.

I can't commit for specific timespan to upload the patch, but I will ask upfront - do we need to submit a PR to upstream repo for the patch to be accepted here like previous time?

**Comment by nevack** [comment]
https://github.com/Homebrew/formula-patches/pull/947

**Comment by nevack** [comment]
@carlocab usbreset should not be built for macOS.

> ```shell
> $ meson setup _build --buildtype release
> $ ninja -C _build lsusb usbhid-dump
> ```

This is why I mentioned explicit ninja command, as meson builds all targets by default.

Should I adjust the patch to exclude usbreset target altogether or would you adjust build cmdline in this PR?

**Comment by nevack** [comment]
Updated patch to not include unbuildable/unusable targets
https://github.com/Homebrew/formula-patches/pull/948

**Comment by nevack** [comment]
@carlocab @chenrui333 Friendly ping

**Review by daeho-ro — APPROVED** [review]

**Pull request merged**
