### PR TITLE
librsvg 2.54.1

### PR DESCRIPTION
**Pull request by joh-klein**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by issyl0** [comment]
```
checking for rst2man.py... no
configure: error: rst2man is required.  Please install python3-docutils.
```

**Comment by joh-klein** [comment]
```
checking for gi-docgen... no
configure: error: gi-docgen is required.  Please install it.
```

**Comment by SMillerDev** [comment]
https://pypi.org/project/gi-docgen/

> You should not depend on a system-wide installation until GI-DocGen is declared stable.

Lovely

**Comment by joh-klein** [comment]
Maybe the maintainer of librsvg @federicomenaquintero can help? (I hope that it is OK to ping him …)

**Comment by cho-m** [comment]
It is packaged by major Linux distros https://repology.org/project/gi-docgen/versions

Looks like various GNOME projects have migrated from `gtk-doc` to `gi-docgen` (like `gtk4` - https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3222), so I think it is probably fine to use and it will probably replace `gtk-doc` in other actively maintained GNOME formulae.

We will want a new formula for this.

**Comment by joh-klein** [comment]
What do I have to do to get this moving again?

**Comment by SMillerDev** [comment]
Should be fine with a rebase

**Comment by joh-klein** [comment]
Hope that was the right way …

**Comment by SMillerDev** [comment]
```
   gi-docgen generate -C ./librsvg.toml --content-dir=../doc ../Rsvg-2.0.gir
  ERROR: Could not find GIR dependency in the search paths: GLib-2.0
```

**Comment by cho-m** [comment]
I am guessing this will pass on Intel macOS as default search path includes https://gitlab.gnome.org/GNOME/gi-docgen/-/blob/main/gidocgen/utils.py#L876
```
xdg_data_dirs = os.environ.get("XDG_DATA_DIRS", "/usr/share:/usr/local/share").split(":")
```

One option would be to set `ENV["XDG_DATA_DIRS"]` in dependents like `librsvg`. Another option would be to `inreplace` the default paths in `gi-docgen`.

**Comment by federicomenaquintero** [comment]
>  ERROR: Could not find GIR dependency in the search paths: GLib-2.0

I think this means it's not finding some of the GObject Introspection files.  Does Homebrew have a girepository package?

**Comment by joh-klein** [comment]
Anyone have ideas how to get this out the door?

**Comment by cho-m** [comment]
Alternatively, you can drop the docs dependencies and try patching in commit from merge request https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/687, which makes it optional

**Comment by cho-m** [comment]
Dropped doc generation for now as it is optional with 2.54.1.

Can reconsider in future once some bugs in `gi-docgen` are fixed. Particularly the malformed output from non-thread safe code that I reported. May also need to adjust `gi-docgen` default directories based on previous errors.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
