### PR TITLE
eigen 3.3.8

### PR DESCRIPTION
**Pull request by alexmerkel**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alexmerkel** [comment]
The tests fail because `ceres-solver` was built with eigen 3.3.7 and CMake does not like the mismatch:

```
CMake Error at /usr/local/lib/cmake/Ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Found Eigen dependency, but the version of Eigen
  found (3.3.8) does not exactly match the version of Eigen Ceres was
  compiled with (3.3.7).  This can cause subtle bugs by triggering violations
  of the One Definition Rule.  See the Wikipedia article
  http://en.wikipedia.org/wiki/One_Definition_Rule for more details
Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:223 (ceres_report_not_found)
  CMakeLists.txt:3 (find_package)
```

The problem does not occur (at least on my machine) when building `ceres-solver` from source after installing eigen 3.3.8.

**Comment by jonchang** [comment]
> The problem does not occur (at least on my machine) when building ceres-solver from source after installing eigen 3.3.8.

Please increment the `revision` in `ceres-solver` in a separate commit. Thanks!

**Comment by alexmerkel** [comment]
Thanks for the hint @jonchang, this seems to fix the problem.
Now, there is an audit failure in `ceres-solver` 

```
==> brew audit ceres-solver --online --git --skip-style
==> FAILED
[...]
ceres-solver:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
[...]
```

but I think this has nothing to do with `eigen` and should be addressed in a separate PR.

**Comment by jonchang** [comment]
This audit will need to get fixed. Run `grep -r CMakeFiles $(brew --repo homebrew/core)` for some examples on how to address this issue.

**Review by SMillerDev — APPROVED** [review]
Thanks @alexmerkel  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
