### PR TITLE
hub 2.3.0-pre8 (devel)

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
$ brew info hub
hub: stable 2.2.9, devel 8, HEAD
...
```

It needs an explicit version or brew will interpret this as version 8.

**Comment by alcaeus** [comment]
Ah, I see. Fixed it.

**Comment by ilovezfs** [comment]
@alcaeus Thanks for the devel spec and your contribution to Homebrew!

**Comment by alcaeus** [comment]
That was quick, thank you!

**Pull request closed without merging**
