### PR TITLE
bump to postgresql@15 in all postgresql extensions. see #125481.

### PR DESCRIPTION
**Pull request by mtesch-um**
After `postgresql@15` is the default these changes can(?) be made.

More information in comments under #125481

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by mtesch-um** [comment]
When `pgvector` Formula is merged, bumping it to `@15` should also be added to this PR.

**Comment by chenrui333** [comment]
@mtesch-um 👋  can you do one commit per each formula update and rebase to the latest master?

**Comment by mtesch-um** [comment]
@chenrui333 👋 yes of course, could you help figuring out an approach to resolve the linked issue with pgvector?   Then I could follow that solution pattern - not enough of homebrew expert to know how to solve that.

**Comment by rafbm** [comment]
Is there any interest in this? Would the right / easy solution be to have `@14`, `@15`, `@16` equivalents of extensions, each depending on the corresponding `postgresql@XX` formula?

```sh
postgresql@14
postgresql@15
postgresql@16

pgvector@14 # `depends_on "postgresql@14"`
pgvector@15 # `depends_on "postgresql@15"`
pgvector@16 # `depends_on "postgresql@16"`

pg_cron@14 # `depends_on "postgresql@14"`
pg_cron@15 # `depends_on "postgresql@15"`
pg_cron@16 # `depends_on "postgresql@16"`

...
```

Seems to be the only way different folks could install different Postgres versions plus extensions.

@mtesch-um @chenrui333 @carlocab @ankane

**Comment by mtesch-um** [comment]
@rafbm that would be fine with me - not that my opinion is authoritative :)

I did promise (but not followup on) bumping each extension's pg version in individual MRs: https://github.com/Homebrew/homebrew-core/pull/125481#discussion_r1135693398

**Pull request closed without merging**
