### PR TITLE
akku 1.1.0 (new formula)

### PR DESCRIPTION
**Pull request by weekOldRoadkill**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@weekOldRoadkill can you rebase your commits to the latest master rather doing the merge commit? Thanks!

**Comment by chenrui333** [comment]
Also, please amend the commit message as `akku 1.1.0 (new formula)` (it is documented in [the commit style guide](https://docs.brew.sh/Formula-Cookbook#commit))

**Comment by weekOldRoadkill** [comment]
I don't know how to do such a thing (the rebasing). I'm sorry I am not too good at all this git stuff I just want a place where I can easily install Akku.

**Comment by weekOldRoadkill** [comment]
Is there any way you could do it for me @chenrui333?

**Comment by chenrui333** [comment]
let me see what I can help with

**Review by chenrui333 — APPROVED** [review]

**Comment by weekOldRoadkill** [comment]
Is there anything else to do or is it all in order and will be added? @chenrui333

**Comment by chenrui333** [comment]
let's have other maintainers also have a chance to review this, I can merge tomorrow or next week.

**Comment by weekOldRoadkill** [comment]
Sounds good. Thank you!

**Comment by chenrui333** [comment]
@weekOldRoadkill, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
