### PR TITLE
cuba: fix checksum mismatch

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to #88329

### CODE REVIEW

**Comment by chenrui333** [comment]
let me also reach out to the upstream to check if we do need to rebottle this (even though I think we should)

**Comment by chenrui333** [comment]
added `do not merge` tag to wait for original author's comments

**Comment by iMichka** [comment]
Any answer from upstream?

**Comment by chenrui333** [comment]
no update from upstream. Let me re-send another email.

**Comment by iMichka** [comment]
Superseded by #89836

**Pull request closed without merging**
