### PR TITLE
ruby@2.7 2.7.6

### PR DESCRIPTION
**Pull request by swrobel**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by swrobel** [comment]
> `rubygems` needs to be updated?

@chenrui333 good point - done!

**Comment by swrobel** [comment]
@chenrui333 interestingly, tests passed before I updated rubygems, but they're failing now... any ideas?

**Comment by Mcdostone** [comment]
According to the [CI logs](https://github.com/Homebrew/homebrew-core/runs/5999460738?check_suite_focus=true#step:6:55), it fails because of the a test in the formula [ruby.rb:240](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ruby.rb#L240). Same issue with #99123 

```log
  ==> Testing ruby@2.7
  ==> /opt/homebrew/Cellar/ruby@2.7/2.7.6/bin/ruby -e 'puts :hello'
  ==> /opt/homebrew/Cellar/ruby@2.7/2.7.6/bin/gem install json
  Building native extensions. This could take a while...
  Successfully installed json-2.6.1
  Parsing documentation for json-2.6.1
  Installing ri documentation for json-2.6.1
  Done installing documentation for json after 0 seconds
  1 gem installed
  ==> /opt/homebrew/Cellar/ruby@2.7/2.7.6/bin/bundle exec ls                              🧪 The test
  --- ERROR REPORT TEMPLATE -------------------------------------------------------
  
  Gem::GemNotFoundException: can't find gem bundler (= 2.3.11) with executable bundle     🔥 The fail
    /opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems.rb:265:in `find_spec_for_exe'
    /opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems.rb:245:in `bin_path'
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @swrobel !!

**Pull request closed without merging**
