### PR TITLE
ddev 3.3.0 (new formula)

### PR DESCRIPTION
**Pull request by swang392**
[ddev](https://github.com/DataDog/integrations-core/tree/master/ddev) is a developer toolkit for Datadog Agent integrations. ddev can be used to test integrations, and provides an interface to manage E2E environments and maintain repositories.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
some space issue, you can use `brew style --fix xx` to fix it.

**Comment by swang392** [comment]
@chenrui333 Hi, do you know why the `CI / conclusion (pull request)` workflow run is failing? Thanks!

**Comment by swang392** [comment]
@chenrui333 Hi! I've been trying to investigate why the CI checks are failing but I haven't able to figure it out. Any advice or help would be really appreciated, thank you!

**Comment by chenrui333** [comment]
let me check in my local.

**Comment by chenrui333** [comment]
> @chenrui333 I think I've got it working now -- could you add the CI-long-timeout label to the PR so the CI checks can run? Thank you!

🤞 😄

**Comment by chenrui333** [comment]
ideally, it would be awesome that we can also get `brew update-python-resources ddev` working with the formula (this is how we manage the version bump with `brew bump --open-pr xxx`)

**Comment by swang392** [comment]
@chenrui333 Ok! Is there documentation for that which I could look at?

**Comment by chenrui333** [comment]
we probably dont have docs for it, it is dev/maintainer command thoguh

**Comment by swang392** [comment]
@chenrui333 Could you add the label back again? I think last time it failed because `cython` updated versions and I pushed before `PyYaml` bumped versions. Also, how should I configure the `brew update-python-resources` command?

**Comment by chenrui333** [comment]
looks like hitting some traffic, https://github.com/Homebrew/homebrew-core/labels/CI-long-timeout, gonna do that shortly after the other PRs are done.

**Comment by chenrui333** [comment]
rerun

**Comment by swang392** [comment]
@chenrui333 I saw that you made a PR (https://github.com/Homebrew/homebrew-core/pull/136977) that referenced an AttributeError for cython_sources --  I am having the same attribute error on my PR. Do you have any guidance on how to fix this?  
Screenshot 2023-07-19 at 3 02 25 PM

**Comment by chenrui333** [comment]
You just need to depends_on pyyaml formula. That would be good.

**Comment by swang392** [comment]
@chenrui333 I already have the `depends_on "pyyaml"` statement on line 19 of my formula.

**Comment by chenrui333** [comment]
actually bit challenging than I think. I will do that later.

**Comment by chenrui333** [comment]
also how did these dependencies got derived? like
- tornado
- snowballstemmer
- smmap

**Comment by chenrui333** [comment]
- memray 1.8.1 failed to build with cython 3+, https://github.com/bloomberg/memray/issues/426

**Comment by swang392** [comment]
@chenrui333 I'm not sure how those got derived. My process for adding dependencies was to go through each resource and add any of its dependencies to the bottom of the file, and keep going down the list until I didn't have any more new resources to add. Is there any reason why you listed those 4 dependencies? Do you know if they are unnecessary?

**Comment by chenrui333** [comment]
> @chenrui333 I'm not sure how those got derived. My process for adding dependencies was to go through each resource and add any of its dependencies to the bottom of the file, and keep going down the list until I didn't have any more new resources to add. Is there any reason why you listed those 4 dependencies? Do you know if they are unnecessary?

oh you dont have to, you can just use:
- setup python3.11 virtualenv
- pip install ddev
- pip freeze to get the full dependency list
- and then you use `homebrew-pypi-poet` to get the full list for the formula

that is how I am doing it

**Comment by swang392** [comment]
@chenrui333 Gotcha, I just did that and updated the formula -- now I am seeing the memray issue that you mentioned above.

**Comment by chenrui333** [comment]
memray issue seems resolved, https://github.com/bloomberg/memray/issues/426#issuecomment-1656113780

Gonna refresh this PR and have another run.

**Comment by chenrui333** [comment]
`ModuleNotFoundError: No module named 'black'` looks like path issue

**Comment by chenrui333** [comment]
have some issue building hatching-1.18.0 locally

```
        ERROR: Could not find a version that satisfies the requirement setuptools>=45.0 (from versions: none)
        ERROR: No matching distribution found for setuptools>=45.0
```

**Comment by swang392** [comment]
@chenrui333 could you add the CI-long-timeout tag? I was able to install and test locally.

**Comment by swang392** [comment]
@chenrui333 Just wanted to bump this!

**Comment by chenrui333** [comment]
currently, I think we run of runners.

**Comment by chenrui333** [comment]
actually we have one now. one sec

**Comment by swang392** [comment]
@chenrui333 I fixed the Linux error, but I am getting a `ModuleNotFoundError: No module named 'black'`error on all of the MacOS CI checks even though I have added a dependency statement for the `black` module. I was looking at some of the other formulas in the repository --  do I need to add something like the lines below? 
https://github.com/Homebrew/homebrew-core/blob/85a8f43224d4abb112d96452ed3dc7ab60a4d6f1/Formula/snakefmt.rb#L39-L40

**Comment by chenrui333** [comment]
yeah, we need to have that, can't we reproduce the CI error in the local?

**Comment by swang392** [comment]
@chenrui333 I added it in! I was not getting any of these errors on my local computer even though I have a mac. Is there a way to match the environment to get the same results?
I tried to do brew install with the new clause for black but I got an error saying `undefined local variable or method 'site_packages'` but I see other homebrew formulas with it. Would you be able to add the tag back?

**Pull request closed without merging**
