### PR TITLE
riemann-client 1.9.0

### PR DESCRIPTION
**Pull request by ilovezfs**
had to patch improper use of `#ifdef` where `#if` is needed

### CODE REVIEW

**Comment by ilovezfs** [comment]
Fixed in https://github.com/algernon/riemann-c-client/pull/11

**Comment by ilovezfs** [comment]
Woo hoo! The PR was just accepted upstream :)

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
🌟 👍

**Comment by ilovezfs** [comment]
*ilovezfs buries his gold star with his bone in the backyard*

**Comment by DomT4** [comment]
Why does ILZ become a dog when appreciated? 🙈

**Pull request closed without merging**
