### PR TITLE
Ballerina 0.964.0

### PR DESCRIPTION
**Pull request by rasika**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @rasika 
Next time, please try to update the existing PR rather than open several pull requests for a single update.

**Comment by rasika** [comment]
@fxcoudert I was referring https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md. It says "One formula per commit; one commit per formula". Please correct me If I am wrong.

**Comment by fxcoudert** [comment]
Inside a pull request, you can squash your changes into a single commit :)

**Comment by rasika** [comment]
@fxcoudert  Ack. Thanks for the info and sup!

**Pull request merged**
