### PR TITLE
Add tls support to tcl.

### PR DESCRIPTION
**Pull request by pozix604**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Is Tcl usually distributed with TLS support?

**Comment by pozix604** [comment]
The complication with this formula is that 1)`tcl-tk` is 1) installed keg only, and 2) `tcltls` is installed into a subdirectory inside `tcl-tk` and 3) if `tcltls` is not installed together, then it is not possible for tcl to make use to https. Is there a way to package `tcltls` separately such that it will install into `tcl-tk`'s key-only directory?

**Comment by fxcoudert** [comment]
Thanks @pozix604

**Comment by pozix604** [comment]
Sorry, I'm still unfamiliar with homebrew formulas. I tried installing this again from bottle and it still doesn't have the tcltls addition. Did I have to `brew install --build-bottle tcl-tk` from my side and update the formula for the bottle to be updated?

**Comment by fxcoudert** [comment]
Apparently you didn't run `brew update`, because otherwise you would have a bottle named `8.6.8_1`.

**Comment by pozix604** [comment]
@SMillerDev That was it. Getting back onto master gave me the right bottle. Thanks!

**Pull request closed without merging**
