### PR TITLE
elvis: add completions for Bash and Zsh

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Opening as draft, for now, since the Elvis version that'll contain the shell completions is not yet out (waiting on https://github.com/inaka/elvis/pull/591). If all goes well, as was the case for #191632, for example, Elvis 3.2.5+ will get released soon, the formula will be auto-updated and then this pull request will go from _Draft_ to **Ready for review** to merged almost (?) without intervention.

### CODE REVIEW

**Comment by stefanb** [comment]
Probably to be combined with the version that actually brings the shell completion:
* https://github.com/Homebrew/homebrew-core/pull/191831

**Comment by stefanb** [comment]
Re-started the checks now that #191831 was merged.

**Comment by stefanb** [comment]
Nah, it seems it must be rebased to use v3.2.6.

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request merged**
