### PR TITLE
splint: upstream Linux fix

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

For the record I tested this locally in Docker and it is still needed.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by iMichka** [comment]
We should report this to upstream, as I consider this an upstream bug.

**Comment by danielnachun** [comment]
Upstream seems rather inactive on this project - no activity since 2015: https://sourceforge.net/projects/splint/.

**Comment by danielnachun** [comment]
It turns out the Makefile hack is unneeded entirely - we just have to provide the flex library location with the variable `LEXLIB` when calling the configure script.  @iMichka do you want me to merge the proper fix here or should I change anything in linuxbrew-core first?

**Comment by SMillerDev** [comment]
I'd say the proper fix should be here

**Comment by danielnachun** [comment]
I pushed the fix which I tested locally.  Hopefully this isn't too complicated to resolve for the merge conflict, but it does seem to be a better solution because there is no patching involved.

**Review by iMichka — APPROVED** [review]

**Pull request merged**
