### PR TITLE
juju 3.1.2

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Not a stable release? Then again, neither is 3.1.1. 3.1.0 seems to be, though.

**Comment by ZhongRuoyu** [comment]
> Not a stable release? Then again, neither is 3.1.1. 3.1.0 seems to be, though.

Mmm, indeed. Upstream's [release notes](https://discourse.charmhub.io/t/roadmap-releases/5064) always mention Snap. According to https://snapcraft.io/juju, 3.1.0 is the "stable", 3.1.1 is the "candidate", and 3.1.2 is the "edge".

The `version_scheme` was incremented in #57456. Will this be the first in Homebrew/core to have `version_scheme 2`? 😶

**Comment by carlocab** [comment]
I'd say just wait for upstream to make this a proper release, unless someone complains about it. Would be good to add a `livecheck` that prevents us from picking up non-stable tags tho.

**Comment by ZhongRuoyu** [comment]
> Would be good to add a `livecheck` that prevents us from picking up non-stable tags tho.

Calling @samford for help -- any idea how to update the `livecheck` block here?

**Comment by samford** [comment]
> any idea how to update the `livecheck` block here?

It looks like we can either check the [GitHub releases](https://github.com/juju/juju/releases?q=prerelease%3Afalse) or [Launchpad](https://launchpad.net/juju).

The trouble with checking the GitHub releases is that there are only ten releases per page and they appear to be publishing releases for 2.9.x, 3.0.x, and 3.1.x at the moment, so there's a real concern that the highest stable version could be pushed off the first page. If that were to happen, then livecheck would start reporting a lower version as newest, which would be a problem. It's the closest check to the `stable` source but I'm somewhat concerned about it potentially being incorrect at some point. That said, there's a good amount of time between releases, so it may be okay in practice.

Checking Launchpad seems like it would give us the correct latest version (3.1.0) but there's no guarantee on whether the Launchpad release will come before or after the GitHub release. However, upstream presumably tags a version on GitHub before it's released (like 3.1.1, 3.1.2), so maybe it's fine (i.e., the tag would almost certainly be available whenever a Launchpad release occurs). The only concern is if they ever retag and whether that would happen between when a Launchpad release occurs and the GitHub release happens. However, if the Launchpad release consistently happens after the GitHub release, then it's moot. I haven't looked into this deeply but it seems to be the case for 3.1.0, at least.

I have a commitment that I'm running off to but I'll come back to this later today. If we come to a consensus on which of these options (or something different) to go with, I'll add a suggested `livecheck` block (I have them worked up for the above options already). If there isn't a preference, we could simply start by checking GitHub releases and switch to Launchpad if/when something goes wrong.

**Comment by carlocab** [comment]
Checking Launchpad seems ideal here. Is there no source tarball there that we can use too? Though presumably we'll have to wait until we actually have a stable version...

**Comment by ZhongRuoyu** [comment]
Launchpad seems like a better choice to me, too.

> Is there no source tarball there that we can use too?

Yes for latest stable versions: https://launchpad.net/juju/3.1/3.1.0/+download/juju-core_3.1.0.tar.gz, for example. If we switch to checking Launchpad for new releases, then we can also use the tarball there and be less concerned about whether GitHub release or Launchpad release comes first, I think. Given that this project is maintained by Canonical, Launchpad should be a reasonably reliable source of information.

**Comment by samford** [comment]
Looks like the only notable difference between the GitHub tarball and the Launchpad one is that the latter has a `vendor` directory. The tweaks to switch to the Launchpad tarball ended up being pretty simple when I tested it. If we go that route, we can simply remove the `livecheck` block and default to checking the `stable` URL using the `Launchpad` strategy.

There's something to be said for downgrading the formula to 3.1.0 so, if there aren't any objections, I can open a separate PR for those changes (since we don't want to upgrade to 3.1.2 here).

**Comment by ZhongRuoyu** [comment]
> There's something to be said for downgrading the formula to 3.1.0 so, if there aren't any objections, I can open a separate PR for those changes (since we don't want to upgrade to 3.1.2 here).

I don't object to that, but alternatively, we can wait for the official 3.1.1 release and switch to using the Launchpad tarball. In that case we won't have to increment `version_scheme` again.

I looked at the difference between the tag time on [GitHub](https://github.com/juju/juju/tags) and the release date on [Launchpad](https://launchpad.net/juju) for recent releases. That averages to about two weeks. So I suggest that we wait for 3.1.1 to be officially released. I can keep an eye on this if we agree to go with this option.

**Comment by samford** [comment]
Looking at recent tag/release dates, I agree that 3.1.1 probably isn't far off, so waiting sounds fine to me. In the interim time, I've pushed a branch to my homebrew-core fork with a reference commit that may help whenever 3.1.1 is released: https://github.com/samford/homebrew-core/commit/8fea111e55cfc08c0176a17c2b0268f85360b511

**Comment by ZhongRuoyu** [comment]
I'll close this for now. I'm still waiting for the official 3.1.1 release on [Canonical](https://launchpad.net/juju).

**Comment by ZhongRuoyu** [comment]
@samford (No 3.1.1 release yet, but...) I noticed that [Launchpad](https://launchpad.net/juju) now displays `3.2-beta1` as the latest version. I've checked out your branch and noticed that the livecheck fell back on the Git strategy and matched `3.1.2`. Can we prevent this?

```console
$ brew livecheck --debug juju
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/juju.rb

Formula:          juju
Livecheckable?:   No

URL:              https://launchpad.net/juju/3.1/3.1.0/+download/juju-core_3.1.0.tar.gz
Strategy:         Launchpad
URL (strategy):   https://launchpad.net/juju/
Regex (strategy): /class="[^"]*version[^"]*"[^>]*>\s*Latest version is (.+)\s*<\//

URL:              https://github.com/juju/juju.git
Strategy:         Git

Matched Versions:
2.8.0, s, -, 1.19.3, 1.19.4, 1.20.0, 1.20.1, 1.20.10, 1.20.11, 1.20.12, 1.20.13, 1.20.14, 1.20.2, 1.20.5, 1.20.6, 1.20.7, 1.20.8, 1.20.9, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.22.5, 1.22.6, 1.22.7, 1.22.8, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.24.5, 1.24.6, 1.24.7, 1.25.0, 1.25.1, 1.25.10, 1.25.11, 1.25.12, 1.25.13, 1.25.14, 1.25.2, 1.25.3, 1.25.4, 1.25.5, 1.25.6, 1.25.7, 1.25.8, 1.25.9, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0, 2.6.1, 2.6.10, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.8.1, 2.8.10, 2.8.11, 2.8.12, 2.8.13, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.9.0, 2.9.1, 2.9.10, 2.9.11, 2.9.12, 2.9.13, 2.9.14, 2.9.15, 2.9.16, 2.9.17, 2.9.18, 2.9.19, 2.9.2, 2.9.20, 2.9.21, 2.9.22, 2.9.23, 2.9.24, 2.9.25, 2.9.26, 2.9.27, 2.9.28, 2.9.29, 2.9.3, 2.9.30, 2.9.31, 2.9.32, 2.9.33, 2.9.34, 2.9.35, 2.9.36, 2.9.37, 2.9.38, 2.9.39, 2.9.4, 2.9.40, 2.9.41, 2.9.42, 2.9.5, 2.9.6, 2.9.7, 2.9.8, 2.9.9, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0, 3.1.1, 3.1.2

juju: 3.1.0 ==> 3.1.2
```

**Comment by samford** [comment]
> I noticed that [Launchpad](https://launchpad.net/juju) now displays `3.2-beta1` as the latest version. I've checked out your branch and noticed that the livecheck fell back on the Git strategy and matched `3.1.2` again. Can we prevent this?

@ZhongRuoyu When a formula doesn't contain a `livecheck` block, `brew livecheck` will [collect the checkable URLs](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/livecheck/livecheck.rb#L536-L541) (`stable`, mirrors, `head`, `homepage`) and iterate through them until it finds versions. Without a `livecheck` block, livecheck automatically filters out versions that appear to be unstable (like `3.2-beta1`), so the `Launchpad` strategy doesn't return any versions and it falls back to checking the `head` URL using the `Git` strategy instead. In this specific case, the way to address this would be to add a `livecheck` block again.

Since the latest version on the Launchpad project's main page (which the `Launchpad` strategy checks) isn't guaranteed to be stable, we'll have to check the Download page instead, so we need a `livecheck` block anyway. I've opened a PR (#127454) to update the existing `livecheck` block into something that will still be applicable after the formula is updated to use a stable tarball from Launchpad in the future.

**Pull request closed without merging**
