### PR TITLE
ocaml 5.0.0 ocaml@4.14 4.14.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

4.14 is LTS release, https://discuss.ocaml.org/t/the-road-to-ocaml-5-0/8584

> Long term support for OCaml 4.14
While OCaml 5 is stabilising, we plan to extend the support period for OCaml 4.14 by publishing minor bugfix releases whenever needed. In particular, OCaml 4.14 will be supported until all tier-1 architectures and operating systems are available in OCaml 5, and OCaml 5 sequential performance is close enough to that of OCaml 4.

### CODE REVIEW

**Comment by chenrui333** [comment]
failed to build camlp5, upstream issue, https://github.com/camlp5/camlp5/issues/95

**Comment by chenrui333** [comment]
lablgtk failed to build with ocaml5, https://github.com/garrigue/lablgtk/issues/156

**Comment by smorimoto** [comment]
What is the status of this PR?

**Comment by SMillerDev** [comment]
Build is failing so not mergable

**Comment by osalbahr** [comment]
> What is the status of this PR?

I opened a new PR since the build errors were resolved upstream.

- #138134

**Comment by chenrui333** [comment]
> I opened a new PR since the build errors were resolved upstream. There are however errors with a couple dependents.
> 
> * [ocaml 5.0.0 #138134](https://github.com/Homebrew/homebrew-core/pull/138134)

that would be the issue of upgrading the formula

**Comment by osalbahr** [comment]
> > I opened a new PR since the build errors were resolved upstream. There are however errors with a couple dependents.
> > 
> > * [ocaml 5.0.0 #138134](https://github.com/Homebrew/homebrew-core/pull/138134)
> 
> that would be the issue of upgrading the formula

Are you saying `ocaml@4.14` is needed for `ocaml-findlib` and/or `camlp-streams`?

**Pull request closed without merging**
