### PR TITLE
sqlite 3.32.3

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-core/pull/56508
https://github.com/Homebrew/homebrew-core/pull/56509
https://github.com/Homebrew/homebrew-core/pull/56510

**Comment by miccal** [comment]
```
Error: 6 failed steps!
brew test --verbose agda
brew test --verbose alure
brew fetch --retry breezy
brew test --verbose genometools
brew test --verbose spdylay
brew test --verbose yle-dl
```

**Comment by miccal** [comment]
`genometools` has been bumped in https://github.com/Homebrew/homebrew-core/pull/55922 which has fixed its failing tests.

**Comment by chenrui333** [comment]
looks like the breezy bottles did not get published:
image

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-core/issues/56641#issuecomment-648617863

**Comment by chenrui333** [comment]
cancelled the two builds in favor of the latest one.

**Comment by miccal** [comment]
Thanks @chenrui333 -- is there a way that I can do that when I add commits?

**Comment by miccal** [comment]
`breezy`, `genometools` and `yle-dl` now pass, but: 
```
Error: 6 failed steps!
brew test --verbose agda
brew test --verbose alure
brew test --verbose percona-server
brew install root
brew test --verbose ship
brew test --verbose spdylay
```

**Comment by chenrui333** [comment]
@miccal let's merge this PR and fix the tests in separate one. Nice work!

**Comment by miccal** [comment]
Thanks @chenrui333, this one is proving to be a lot of work :)

**Comment by SMillerDev** [comment]
@henryiii Any ideas for the failing ROOT formula?

**Comment by miccal** [comment]
@SMillerDev https://github.com/Homebrew/homebrew-core/pull/56904#issue-440243935 may be relevant?

**Comment by henryiii** [comment]
Yes, it appears that libGLEW is colliding. A fix as shown above should do it.

**Comment by miccal** [comment]
@henryiii the error here for `root` was:
```
==> Pouring root-6.22.00.catalina.bottle.tar.gz
Warning: root dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/libGLEW.dylib
Target /usr/local/lib/libGLEW.dylib
is a symlink belonging to glew. You can unlink it:
  brew unlink glew
To force the link and overwrite all conflicting files:
  brew link --overwrite root
To list all files that would be deleted:
  brew link --overwrite --dry-run root
Possible conflicting files are:
10699
/usr/local/lib/libGLEW.dylib -> /usr/local/Cellar/glew/2.1.0_1/lib/libGLEW.dylib
```
while in https://github.com/Homebrew/homebrew-core/pull/56906 (which is similar to https://github.com/Homebrew/homebrew-core/pull/56904) the error was:
```
-- Found GLEW: /usr/local/lib/cmake/glew/glew-config.cmake  
CMake Error at cmake/modules/SearchInstalledSoftware.cmake:524 (message):
  Please enable builtin Glew due bug in latest CMake (use cmake option
  -Dbuiltin_glew=ON).
```
so I do not think the suggested changes in https://github.com/Homebrew/homebrew-core/pull/56906 and https://github.com/Homebrew/homebrew-core/pull/56904 will immediately solve this issue.

**Comment by miccal** [comment]
I have updated `breezy` [in a separate PR](https://github.com/Homebrew/homebrew-core/pull/57028) and the revision bump for `spdylay` was not necessary -- is there a way I can remove these commits from this PR _without_ re-triggering the tests?

**Comment by chenrui333** [comment]
Circle back on this PR.

**Comment by chenrui333** [comment]
Only keep sqlite version bump and rebased to the latest master

**Comment by chenrui333** [comment]
## 10.15
```
 Error: 11 failed steps!
 brew test --verbose agda
 brew test --verbose alure
 brew test --verbose ddgr
 brew test --verbose dps8m
 brew test --verbose howdoi
 brew test --verbose mysql
 brew test --verbose ncview
 rm -rf /Users/brew/Library/Caches/Homebrew
 brew test --verbose opentsdb
 brew install root
 brew test --verbose spdylay
``` 

## 10.14
```
 Error: 8 failed steps!
 brew test --verbose agda
 brew test --verbose alure
 brew test --verbose ddgr
 brew test --verbose howdoi
 brew test --verbose opentsdb
 brew test --verbose percona-server
 brew install root
 brew test --verbose spdylay
``` 

## 10.13
```
 Error: 7 failed steps!
 brew test --verbose agda
 brew test --verbose alure
 brew test --verbose ddgr
 brew test --verbose howdoi
 brew test --verbose opentsdb
 brew install root
 brew test --verbose spdylay
```

**Comment by chenrui333** [comment]
agda failed due to `cabal_sandbox` deprecation which is expected.

**Comment by chenrui333** [comment]
alure test works for me without sqlite upgrade.

**Comment by miccal** [comment]
For `myslq` see https://github.com/Homebrew/homebrew-core/pull/56400
For `opentsdb` see https://github.com/Homebrew/homebrew-core/pull/57232

**Comment by chenrui333** [comment]
@Homebrew/core looks like the PR is in the good to 🚀 state now, going to merge it and address the opening PRs.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
