### PR TITLE
get_iplayer 3.31

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
All the resources need to be updated.

**Comment by chenrui333** [comment]
I think I might complicate myself with the dependency updates on the linux build, but I will do action test run before the next CI run.

**Comment by chenrui333** [comment]
```
  Can't locate Path/Tiny.pm in @INC (you may need to install the Path::Tiny module) (@INC contains: /home/linuxbrew/.linuxbrew/Cellar/get_iplayer/3.31/libexec/lib/perl5/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/get_iplayer/3.31/libexec/lib/perl5 /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/site_perl/5.36/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/site_perl/5.36 /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/5.36/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/5.36 /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.36/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.36) at /home/linuxbrew/.linuxbrew/Cellar/get_iplayer/3.31/libexec/lib/perl5/Alien/Build.pm line 6.
```

**Comment by olivergrabinski** [comment]
@chenrui333 could this PR be reopened?

**Comment by osalbahr** [comment]
Should I force a new bump?

**Comment by olivergrabinski** [comment]
@osalbahr That’d be great 🙏

**Pull request closed without merging**
