### PR TITLE
terraforming: Fix on Linux

### PR DESCRIPTION
**Pull request by iMichka**
Goal: get rid of the the :all / other bottles mix in the bottle block

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Does dispatch-rebottle not work here?

**Comment by iMichka** [comment]
I want also to see if I can build a Linux bottle, I hit an error with some obscure missing dependency in the GemFile. I want to have a full clean build so I can call the ruby experts for help :)

**Comment by iMichka** [comment]
```
2022-02-22T22:15:54.2936422Z [32m==>[0m [1mTesting terraforming[0m
2022-02-22T22:15:54.2936852Z [34m==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/bin/terraforming help ec2[0m
2022-02-22T22:15:54.2937530Z <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick/httputils (LoadError)
2022-02-22T22:15:54.2938428Z 	from <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2022-02-22T22:15:54.2939076Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/gems/aws-sdk-s3-1.36.1/lib/aws-sdk-s3/legacy_signer.rb:5:in `<top (required)>'
2022-02-22T22:15:54.2939568Z 	from <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2022-02-22T22:15:54.2940009Z 	from <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2022-02-22T22:15:54.2940636Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/gems/aws-sdk-s3-1.36.1/lib/aws-sdk-s3/customizations.rb:7:in `<top (required)>'
2022-02-22T22:15:54.2941278Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/gems/aws-sdk-s3-1.36.1/lib/aws-sdk-s3.rb:36:in `require_relative'
2022-02-22T22:15:54.2941897Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/gems/aws-sdk-s3-1.36.1/lib/aws-sdk-s3.rb:36:in `<top (required)>'
2022-02-22T22:15:54.2942344Z 	from <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2022-02-22T22:15:54.2942779Z 	from <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2022-02-22T22:15:54.2943390Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/gems/terraforming-0.18.0/lib/terraforming.rb:14:in `<top (required)>'
2022-02-22T22:15:54.2943848Z 	from <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2022-02-22T22:15:54.2944279Z 	from <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2022-02-22T22:15:54.2945014Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/gems/terraforming-0.18.0/bin/terraforming:3:in `<top (required)>'
2022-02-22T22:15:54.2945464Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/bin/terraforming:25:in `load'
2022-02-22T22:15:54.2945862Z 	from /home/linuxbrew/.linuxbrew/Cellar/terraforming/0.18.0_1/libexec/bin/terraforming:25:in `<main>'
2022-02-22T22:15:54.2946078Z 
```

**Comment by carlocab** [comment]
None of that requires a `revision` bump, though.

**Comment by cho-m** [comment]
May not have full dependencies for Ruby 3. Quick fix would be to try Ruby 2. Otherwise, may need to find out what Gems are missing in Ruby 3.

**Comment by Bo98** [comment]
When we had bad `all` bottles before (brew bug), all we did was remove that bottle line rather than a full rebuild. It's a mistake there's even an `all` bottle to begin with.

**Comment by iMichka** [comment]
Fixed. Let's ship just a new set of bottles then.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
