### PR TITLE
imagemagick@6 6.9.8-9

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @zmwangx

**Comment by zmwangx** [comment]
Thanks. I missed one of my cron emails.

**Comment by ilovezfs** [comment]
@zmwangx I knew there had to be an explanation! :)

**Comment by zmwangx** [comment]
Ah actually I have `bump-imagemagick6 6.9.8-9` in my Zsh history... Apparently when I tried to bump it the tarball wasn't there yet ;)

**Comment by ilovezfs** [comment]
And the plot thickens.

**Comment by ilovezfs** [comment]
:unicorn:

**Pull request closed without merging**
