### PR TITLE
formulae: depend on util-linux on Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
This will need a new homebrew release, with the new DSL: https://github.com/Homebrew/brew/pull/7257

**Comment by issyl0** [comment]
Oh you got my hopes up that it was released! But why so many changes to formulae that didn't have this dependency before?

**Comment by issyl0** [comment]
[2.2.13](https://github.com/Homebrew/brew/releases/tag/2.2.13) is released now so this can come out of draft. 🙏

**Comment by iMichka** [comment]
Let's wait a little bit, I want to have the audit setup before proceeding with this.

**Pull request closed without merging**
