### PR TITLE
sbcl 1.5.8

### PR DESCRIPTION
**Pull request by wahjava**
-  [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
21:33:26 debugger invoked on a SIMPLE-ERROR in thread
21:33:26 #<THREAD "main thread" RUNNING {10005885B3}>:
21:33:26   Error opening shared object "/usr/local/opt/openssl/lib/libcrypto.dylib":
21:33:26   dlopen(/usr/local/opt/openssl/lib/libcrypto.dylib, 10): image not found.
21:33:26 Killing child processes...
21:33:26 Error: pgloader: failed
21:33:26 An exception occurred within a child process:
21:33:26   Timeout::Error: execution expired

**Comment by wahjava** [comment]
> 21:33:26 debugger invoked on a SIMPLE-ERROR in thread
> 21:33:26 #<THREAD "main thread" RUNNING {10005885B3}>:
> 21:33:26 Error opening shared object "/usr/local/opt/openssl/lib/libcrypto.dylib":
> 21:33:26 dlopen(/usr/local/opt/openssl/lib/libcrypto.dylib, 10): image not found.
> 21:33:26 Killing child processes...
> 21:33:26 Error: pgloader: failed
> 21:33:26 An exception occurred within a child process:
> 21:33:26 Timeout::Error: execution expired

That is more of a problem with `pgloader`, than `sbcl`.

**Comment by Bo98** [comment]
pgloader issue should be fixed now.

@BrewTestBot test this please

**Comment by Bo98** [comment]
Thank you @wahjava.

**Pull request closed without merging**
