### PR TITLE
cidr2ip 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by UmanShahzad**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is part of the CLI utilities we offer our customers at https://github.com/ipinfo/cli

### CODE REVIEW

**Comment by carlocab** [comment]
Isn't this already part of the `ipinfo-cli` formula?

**Comment by UmanShahzad** [comment]
@carlocab Yeah it is. We ship it as a separate binary for people who don't want to install the whole thing.

**Comment by carlocab** [comment]
We don't target embedded environments, so there really isn't a very compelling reason to avoid installing the whole thing. Let's just keep things less confusing for users and easier to maintain by keeping this all in the `ipinfo-cli` formula.

**Comment by UmanShahzad** [comment]
@carlocab Good idea! Will push the changes in a moment to this and `range2ip`.

**Comment by UmanShahzad** [comment]
@carlocab one thing I wanna mention, though: the `ipinfo-cli` formula, although it "includes" all these others like `cidr2ip`, it's only via subcommands and not as separate binaries (i.e. `ipinfo cidr2ip <cidr>`). When you mentioned using an alias, did you think that `cidr2ip` would automatically get installed as a separate binary when `ipinfo-cli` was installed?

We can make that happen too and I think users would be potentially less confused in that scenario, but need to clarify.

**Comment by UmanShahzad** [comment]
@carlocab just made https://github.com/Homebrew/homebrew-core/pull/89582 as well in the same manner as this, but I guess we really need to know what path to take on these as a whole - should we make `ipinfo-cli` install all of these, or continue as we were before with e.g. `grepip`, etc., by making them separate formulas?

We have many Homebrew users who use this stuff actively and would really like all of these on Homebrew, so just trying to help them out here.

**Comment by carlocab** [comment]
> @carlocab one thing I wanna mention, though: the `ipinfo-cli` formula, although it "includes" all these others like `cidr2ip`, it's only via subcommands and not as separate binaries (i.e. `ipinfo cidr2ip <cidr>`). When you mentioned using an alias, did you think that `cidr2ip` would automatically get installed as a separate binary when `ipinfo-cli` was installed?

No, but we can do something like that too. If we could just install symlinks to `ipinfo` that allow it to be called as `cidr2ip` and executes `ipinfo cidr2ip`, even better. These are all tools that are part of the same project, and we typically like to keep things simple by packaging them in the same formula. If `grepip` is actually a subcommand if `ipinfo`, then we should probably just do the same with `grepip` too.

**Comment by UmanShahzad** [comment]
Alright, I totally get what you're looking for now - to simplify things to one formula.

I think the only way to make `cidr2ip` automatically execute as `ipinfo cidr2ip` would be to use a shell alias; not sure how we feel about that or if that can be done reliably for different shells.

So let's go with the option of simply building the remaining CLIs within the same `ipinfo-cli` formula and installing them all.

I'll close all these PRs so far and make a single one that'll combine the work to make it clearer what's happening.

**Comment by carlocab** [comment]
You should be able to do it without shell aliases by making `ipinfo` check the Go-equivalent of `argv[0]`.

**Comment by UmanShahzad** [comment]
Ah, that's really smart! I think we can make that work; will make a homebrew PR with an updated `ipinfo` if it does.

**Pull request closed without merging**
