### PR TITLE
wireshark 2.6.1

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Bug report for the missing folder/files in the release tarball: https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=14627

### CODE REVIEW

**Comment by DomT4** [comment]
There's a fair bit of detail in each commit message here, FYI.

**Comment by DomT4** [comment]
Getting broken linkage messages locally FWIW but I'm not sure quite where they're being thrown from at this point.
```
Variable-referenced libraries:
  @loader_path//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwireshark.0.dylib
  @loader_path//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwiretap.0.dylib
  @loader_path//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwscodecs.0.dylib
  @loader_path//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwsutil.0.dylib
  @loader_path/libwiretap.0.dylib
  @loader_path/libwsutil.0.dylib
Broken dependencies:
  /usr/local/Cellar/wireshark/2.6.0/lib//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwireshark.0.dylib (wireshark)
  /usr/local/Cellar/wireshark/2.6.0/lib//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwiretap.0.dylib (wireshark)
  /usr/local/Cellar/wireshark/2.6.0/lib//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwscodecs.0.dylib (wireshark)
  /usr/local/Cellar/wireshark/2.6.0/lib//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwsutil.0.dylib (wireshark)
```

**Comment by DomT4** [comment]
Okay, I see what's happened. `brew` has fixed the linkage for the stuff in `bin` but hasn't touched the linkage inside the `.app`:

```
/usr/local/bin/tshark:
	/usr/local/Cellar/wireshark/2.6.0/lib/libwireshark.0.dylib (compatibility version 0.0.0, current version 11.0.0)
```

```
/usr/local/Cellar/wireshark/2.6.0/Wireshark.app/Contents/MacOS/tshark:
	/usr/local/Cellar/wireshark/2.6.0/lib//tmp/wireshark-20180426-72667-1enu4az/run/Wireshark.app/Contents/Frameworks/libwireshark.0.dylib (compatibility version 0.0.0, current version 11.0.0)
```

**Comment by ilovezfs** [comment]
The repository is nearly 1 gig. I think we need a new tarball not this.

**Comment by ilovezfs** [comment]
This fixes lua
```
diff --git a/Formula/wireshark.rb b/Formula/wireshark.rb
index 2c1c2d2..25a5b3c 100644
--- a/Formula/wireshark.rb
+++ b/Formula/wireshark.rb
@@ -25,26 +25,28 @@ class Wireshark < Formula
   depends_on "gnutls"
   depends_on "libgcrypt"
   depends_on "libmaxminddb"
+  depends_on "lua@5.1"
   depends_on "libsmi" => :optional
   depends_on "libssh" => :optional
   depends_on "nghttp2" => :optional
   depends_on "qt" => :optional
 
   def install
-    args = std_cmake_args + %w[
+    args = std_cmake_args + %W[
       -DENABLE_CARES=ON
       -DENABLE_GNUTLS=ON
+      -DENABLE_LUA=ON
       -DENABLE_MAXMINDDB=ON
       -DBUILD_wireshark_gtk=OFF
       -DENABLE_PORTAUDIO=OFF
+      -DLUA_INCLUDE_DIR=#{Formula["lua@5.1"].opt_include}/lua-5.1
+      -DLUA_LIBRARY=#{Formula["lua@5.1"].opt_lib}/liblua5.1.dylib
+      -DCARES_INCLUDE_DIR=#{Formula["c-ares"].opt_include}
+      -DGCRYPT_INCLUDE_DIR=#{Formula["libgcrypt"].opt_include}
+      -DGNUTLS_INCLUDE_DIR=#{Formula["gnutls"].opt_include}
+      -DMAXMINDDB_INCLUDE_DIR=#{Formula["libmaxminddb"].opt_include}
     ]
 
-    # This is intended to be temporary. Upstream explicitly rejects Lua 5.3
-    # and so we need to switch this to using Lua@5.1, but I'm still working
-    # on a way to do that that doesn't involve rewriting enormous chunks of
-    # FindLUA.cmake to prevent CMake brazenly ignoring superenv. /DomT4
-    args << "-DENABLE_LUA=OFF"
-
     if build.with? "qt"
       args << "-DBUILD_wireshark=ON"
       args << "-DENABLE_APPLICATION_BUNDLE=ON"
```

**Comment by brunchboy** [comment]
In the mean time, how can I get back to having a working Wireshark since my `brew upgrade` has left me with a broken 2.6.0?

**Comment by DomT4** [comment]
@ilovezfs Currently still hitting build failures locally with that:
```
[  7%] Linking C static library ../run/libui.a
cd /tmp/wireshark-20180426-89231-yqnytq/ui && /usr/local/Cellar/cmake/3.11.1/bin/cmake -P CMakeFiles/ui.dir/cmake_clean_target.cmake
cd /tmp/wireshark-20180426-89231-yqnytq/ui && /usr/local/Cellar/cmake/3.11.1/bin/cmake -E cmake_link_script CMakeFiles/ui.dir/link.txt --verbose=1
/usr/bin/ar qc ../run/libui.a  CMakeFiles/ui.dir/alert_box.c.o CMakeFiles/ui.dir/capture.c.o CMakeFiles/ui.dir/capture_ui_utils.c.o CMakeFiles/ui.dir/commandline.c.o CMakeFiles/ui.dir/console.c.o CMakeFiles/ui.dir/decode_as_utils.c.o CMakeFiles/ui.dir/dissect_opts.c.o CMakeFiles/ui.dir/export_object_ui.c.o CMakeFiles/ui.dir/export_pdu_ui_utils.c.o CMakeFiles/ui.dir/help_url.c.o CMakeFiles/ui.dir/failure_message.c.o CMakeFiles/ui.dir/file_dialog.c.o CMakeFiles/ui.dir/filter_files.c.o CMakeFiles/ui.dir/firewall_rules.c.o CMakeFiles/ui.dir/iface_toolbar.c.o CMakeFiles/ui.dir/iface_lists.c.o CMakeFiles/ui.dir/io_graph_item.c.o CMakeFiles/ui.dir/language.c.o CMakeFiles/ui.dir/mcast_stream.c.o CMakeFiles/ui.dir/packet_list_utils.c.o CMakeFiles/ui.dir/packet_range.c.o CMakeFiles/ui.dir/persfilepath_opt.c.o CMakeFiles/ui.dir/preference_utils.c.o CMakeFiles/ui.dir/profile.c.o CMakeFiles/ui.dir/proto_hier_stats.c.o CMakeFiles/ui.dir/recent.c.o CMakeFiles/ui.dir/rtp_media.c.o CMakeFiles/ui.dir/rtp_stream.c.o CMakeFiles/ui.dir/service_response_time.c.o CMakeFiles/ui.dir/software_update.c.o CMakeFiles/ui.dir/ssl_key_export.c.o CMakeFiles/ui.dir/summary.c.o CMakeFiles/ui.dir/tap_export_pdu.c.o CMakeFiles/ui.dir/tap-iax2-analysis.c.o CMakeFiles/ui.dir/tap-rtp-common.c.o CMakeFiles/ui.dir/tap-sctp-analysis.c.o CMakeFiles/ui.dir/tap-rlc-graph.c.o CMakeFiles/ui.dir/tap-tcp-stream.c.o CMakeFiles/ui.dir/text_import.c.o CMakeFiles/ui.dir/time_shift.c.o CMakeFiles/ui.dir/traffic_table_ui.c.o CMakeFiles/ui.dir/util.c.o CMakeFiles/ui.dir/voip_calls.c.o CMakeFiles/ui.dir/text_import_scanner.c.o
/usr/bin/ranlib ../run/libui.a
[  7%] Built target ui
[  7%] Built target dissectors-corba
make: *** [all] Error 2
```

@brunchboy If it just failed to `upgrade` you can `brew pin wireshark` to stop it trying to upgrade temporarily. Just remember to `brew unpin wireshark` when it is working again.

**Comment by brunchboy** [comment]
Thanks, @DomT4 but even after `brew pin wireshark` whenever I launch wireshark it immediately crashes with a SIGSEGV. Is there something else I need to do as well?

**Comment by DomT4** [comment]
That's a strange one. Try `brew link wireshark` first, just in case?

**Comment by brunchboy** [comment]
Huh, the problem may be deeper, or from earlier, it tells me:
> Warning: Already linked: /usr/local/Cellar/wireshark/2.4.5
> To relink: brew unlink wireshark && brew link wireshark

**Comment by DomT4** [comment]
Oh, yeah, you missed an update somewhere along the way. The most recent one prior to this was 2.4.6. If your repo is a deep clone you could do something like this:

```
=> cd $(brew --repo homebrew/core)
=> git checkout c3e60183659c3d2dabd8b681710f5dbf16cffad9
=> brew upgrade wireshark
=> git checkout master
=> brew pin wireshark
```

**Comment by brunchboy** [comment]
Hmm, must not be a deep clone? The first two steps seem to work, but the upgrade step is still trying to go to wireshark 2.6.0 for whatever reason. I’ve checked out master again, I will just hold out for 2.6.0 to be fixed.

**Comment by ilovezfs** [comment]
>presume tested with both lua and lua@5.1 installed? That's the issue I was having; it kept wandering off into /usr/local by itself and trying to mesh the 5.1 headers with the 5.3 libs 🙃.

Yes. The cause is that it finds the headers for some of the dependencies in /usr/local/include and as a result passes `-isystem /usr/local/include`. The order of `-isystem /somewhere` seems to be basically random, and so `-isystem /usr/local/include` ends up coming before the lua@5.1 headers. So a workaround is to specify all of the header locations explicitly so that none of them are using /usr/local/include. Another possible workaround would be to move the lua 5.3 headers into a subdirectory.

**Comment by DomT4** [comment]
>  Another possible workaround would be to move the lua 5.3 headers into a subdirectory.

Yeah, I might look into this one.

**Comment by DomT4** [comment]
I've asked upstream to cut a new release for the GUI build issue FWIW, so we'll see where that goes.

**Comment by brunchboy** [comment]
Fingers crossed that upstream can get this fixed. I miss wireshark!

**Comment by DomT4** [comment]
Release is due to land tomorrow FYI.

**Comment by DomT4** [comment]
PR updated.

**Comment by DomT4** [comment]
> Yeah, I might look into this one.

There's a separate PR incoming for this `lua` change by the way. I think it's a sensible step to take and it resolves the issues discussed here with `cmake` tripping over itself.

**Comment by DomT4** [comment]
I forgot to put it in the commit message & it's probably not worth pushing it back through CI just for this, so for reference https://github.com/Homebrew/homebrew-core/issues/27079 can be closed after this is folded in.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/28143 shipped so the hacks can be backed out of this one.

**Comment by DomT4** [comment]
It seems less like tempting fate to leave the directory specifications in but I'll check it out sans those.

**Comment by DomT4** [comment]
Yeah, it's still tripping over something.
```
[ 80%] Built target dissectors
make: *** [all] Error 2
```

Adding:
```
      -DLUA_INCLUDE_DIR=#{Formula["lua@5.1"].opt_include}/lua-5.1
      -DLUA_LIBRARY=#{Formula["lua@5.1"].opt_lib}/liblua5.1.dylib
```
back to the formula doesn't resolve it, so the trip definitely isn't `lua`.

**Comment by ilovezfs** [comment]
I assume you can still trip it with any of `--with-libsmi`, `--with-libssh`, or `--with-nghttp2` since

```
bash-3.2$ cmake -LAH . 2>&1|grep -E '/usr\/local\/include$'
-- LIBSSH includes: /usr/local/include
-- NGHTTP2 includes: /usr/local/include
-- SMI includes: /usr/local/include
LIBSSH_INCLUDE_DIR:PATH=/usr/local/include
NGHTTP2_INCLUDE_DIR:PATH=/usr/local/include
SMI_INCLUDE_DIR:PATH=/usr/local/include
```

**Comment by ilovezfs** [comment]
🦈

**Comment by ilovezfs** [comment]
Shipping as is, though we may want to tighten it up with explicit LIBSSH_INCLUDE_DIR, NGHTTP2_INCLUDE_DIR and SMI_INCLUDE_DIR if you can still trigger a build failure without them.

**Comment by DomT4** [comment]
Apologies, I somehow have a giant cold in late May so I've not been as glued to my emails as I normally am. Some good news, sorta: The build failure I hit last night wasn't as a result of search path silliness but rather the issue fixed by https://github.com/Homebrew/homebrew-core/pull/28192, so the explicit inclusion of `INCLUDE_DIR` variables here can go away after all.

**Comment by brunchboy** [comment]
So is this waiting for a 2.6.2? Or will there be some way to download a new version of 2.6.1 that will bild for me?

**Comment by DomT4** [comment]
This is merged. The new issue is because of changes Qt made with the latest release, which https://github.com/Homebrew/homebrew-core/pull/28192 will resolve.

**Pull request closed without merging**
