### PR TITLE
cheat 2.1.26

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by DomT4** [comment]
(Unless you want to move this across to the `virtualenv` system first)

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
@DomT4 yeah this may be fine, but I'm a bit hesitant to merge any virtualenv stuff at the moment given what I saw in https://github.com/Homebrew/homebrew-core/pull/3685.

**Comment by DomT4** [comment]
Aye, no problem. Let's wait for Tim's feedback there then.

**Pull request closed without merging**
