### PR TITLE
avfs 1.1.2

### PR DESCRIPTION
**Pull request by crunchtime-ali**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by crunchtime-ali** [comment]
`modules/urar.c` needs a `#include <limits.h>` added.
What can I do in such a case?

```c
urar.c:827:24: error: use of undeclared identifier 'PATH_MAX'
    if (name_length <= PATH_MAX) {
                       ^
1 error generated.
```

**Comment by Moisan** [comment]
The first thing to do is to advise upstream of the issue. avfs seems to have a mailing list. If you can fix the issue you can even send them a patch, or at least a pointer how to fix it. 

Then, until upstream fixes the issue, you can fix the formula. If the whole thing is only an `#include` missing, you should use the [`inreplace` function](https://docs.brew.sh/Formula-Cookbook#inreplace).

**Comment by chenrui333** [comment]
I just subscribed the mailinglist, still did not figure out how to send out a email.

@crunchtime-ali, did you get a chance to ask the maintainer for help? Thanks!

**Comment by crunchtime-ali** [comment]
> I just subscribed the mailinglist, still did not figure out how to send out a email.
> 
> @crunchtime-ali, did you get a chance to ask the maintainer for help? Thanks!

I just joined the mailing list as well and sent a mail to avf-user@lists.sourceforge.net explaining the issue. So far I can't see it in the web UI.

If I don't get an answer by Friday I will use `inreplace` as you described @chenrui333

**Comment by dtrodrigues** [comment]
It's been patched upstream: https://sourceforge.net/p/avf/git/ci/ea83e0559f65ab89e81b4105e38b39a40cf9900e/

**Comment by crunchtime-ali** [comment]
I deleted my tracking branch accidentally but re-opened a new one with the upstream patch here https://github.com/Homebrew/homebrew-core/pull/58257/files.
Thank you for the hint @dtrodrigues

**Pull request closed without merging**
