### PR TITLE
yaml-cpp: Fix CMake Variable Name & Do Not Build Test Code

### PR DESCRIPTION
**Pull request by sanssecours**
👋 Hi,

after this pull request `brew` will build the shared version of the library `yaml-cpp` instead of the static version. I don’t know if the formula for yaml-cpp 0.6.2 included both a static and shared library. However, as far as I can tell the options to build a shared and a static library [now exclude each other](https://github.com/jbeder/yaml-cpp/blob/yaml-cpp-0.6.3/CMakeLists.txt#L255-L259). 

I am not sure if you prefers static or shared libraries for `homebrew-core`? Personally I favor the shared library, since linking the static version of the library introduces strange parsing errors in a project I am working on. That of course might be my fault 😊. Anyway, if you prefer static libraries, I think it would make sense to remove 
`"-DBUILD_SHARED_LIBS=ON"`, since `yaml-cpp` does not use the variable `BUILD_SHARED_LIBS` any more.

----
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by Bo98** [comment]
I'm happy with this. Would it pehaps be worth revision bumping `skafos` to make it rebuild using  the shared library?

**Comment by sanssecours** [comment]
> I'm happy with this - thank you! Would it pehaps be worth revision bumping `skafos`, which depends on `yaml-cpp`, to make it rebuild using the shared library?

Thank you for the suggestion. I increased the minor revision for `skafos` like you requested.

**Comment by Bo98** [comment]
Thanks! It'll be a good chance to as well to see if the build still works with the change.

**Comment by Bo98** [comment]
Oh I almost forgot - you'll need to revision bump `yaml-cpp` so the people actually get the changes. Sorry for missing that!

**Comment by Bo98** [comment]
Thanks @sanssecours. Much appreciated.

**Pull request closed without merging**
