### PR TITLE
gtk+3 3.24.10

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
FAILED: docs/reference/gtk/gtk-query-immodules-3.0.1 
/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/reference/gtk/gtk-query-immodules-3.0.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../docs/reference/gtk/gtk-query-immodules-3.0.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
```

**Comment by tschoonj** [comment]
@fxcoudert This is strange... runtime linker problems on Sierra and High Sierra, but not on Mojave! 🤔

**Comment by fxcoudert** [comment]
I checked the bottles built from this PR, and both Mojave and High Sierra provide version 2401.10.0 for libgtk-3.0.dylib. However, the bottles for the previous version indeed provided version 2405.5.0:

```
rmeur ~/Downloads $ otool -L gtk+3-3/3.24.9/lib/libgtk-3.0.dylib
gtk+3-3/3.24.9/lib/libgtk-3.0.dylib:
	@@HOMEBREW_PREFIX@@/opt/gtk+3/lib/libgtk-3.0.dylib (compatibility version 2405.0.0, current version 2405.5.0)
```

so, at the very least, it is a bug for gtk+3 to decrease its library version number. (Why it does not show up on Mojave, I do not know, because the old bottles there also have 2405.0.0 as version number.)

**Comment by tschoonj** [comment]
It's a bug in their meson scripts, testing it now...

**Comment by tschoonj** [comment]
🍏 

Switching to meson really speeds the build up...

**Pull request closed without merging**
