### PR TITLE
ntp: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by cho-m** [comment]
Issue with livecheck SSL certs:
```console
❯ brew livecheck ntp
curl: (60) SSL: no alternative certificate subject name matches target host name 'www.ntp.org'
Error: ntp: Unable to get versions
```

**Comment by danielnachun** [comment]
I see that https://www.ntp.org gives a certificate error when I try to load it in a web browser as well.  @samford any thoughts how to handle this case?  In the worse case scenario I suppose the livecheck could be disabled entirely, but this is not my area of expertise.

**Comment by samford** [comment]
I couldn't add a suggestion for the `livecheck` block, so I pushed a commit with a temporary workaround. The new `livecheck` block checks the releases RSS feed, as it doesn't have the same SSL certificate issue and contains a link to the stable tarball.

I don't think we should use this particular check long-term (the download page is probably more likely to stay updated), so I commented out the previous URL/regex to make it easy to restore in the future. If it ends up being preferable to remove the old URL/regex (leaving it up to whoever reinstates it to look through the Git history), feel free to modify the `livecheck` block.

As an aside, I still need to get around to adding a `CI-skip-livecheck` label/feature. It isn't entirely relevant here but there was a `livecheck` block in the recent past (`juman`) that worked locally but failed on CI and we couldn't figure out why. When we're faced with removing a `livecheck` block that works locally but fails on CI, it may be preferable to be able to simply skip the check. Anyway, that's something to tackle once I finish with some more pressing things on my to-do list.

**Comment by danielnachun** [comment]
Thanks for the quick fix @samford!  Now everything is passing in CI.  Hopefully this ends up just being a temporary problem with the site's SSL certificate and the site owners can fix it soon.

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
looks like the SSL cert issue is resolved now, reverting the livecheck update in #112721

**Pull request closed without merging**
