### PR TITLE
cocoapods 1.9.2

### PR DESCRIPTION
**Pull request by nonewcode**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by issyl0** [comment]
Thanks for your first PR to Homebrew, @codecog! 💪 We do have a failure on CI. And if I'm honest, I'm not sure what it means or what the fix is! I'll have to do some investigation to be able to advise you!

```
==> brew audit --skip-style cocoapods --online
==> FAILED
Error: 1 problem in 1 formula detected
cocoapods:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      libexec/extensions/universal-darwin-19/2.6.0/ffi-1.12.2/mkmf.log
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/man/page-Makefile.ri
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/page-config_status.ri
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/include/page-Makefile.ri
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/testsuite/page-Makefile.ri
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/page-Makefile.ri
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/page-libtool.ri
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/doc/page-Makefile.ri
      libexec/doc/ffi-1.12.2/ri/ext/ffi_c/libffi-x86_64/page-config_log.ri
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/man/Makefile
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/libtool
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/Makefile
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/include/Makefile
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/testsuite/Makefile
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/config.status
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/doc/Makefile
      libexec/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/config.log
```

**Comment by issyl0** [comment]
I can't reproduce these shims audit warnings locally - I'm going to push a commit or two to see if I can get any further with CI.

**Comment by codecog** [comment]
it’s likely something on my machine not playing nice. Appreciate the assist :)

**Comment by Bo98** [comment]
Looks like there is an incompatibility between system Ruby on High Sierra and the FFI gem. It is trying to compile for 32-bit which will not work:

`The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)`

**Pull request closed without merging**
