### PR TITLE
eigen 3.3.2

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Please fix the audit --strict issue here :)

**Comment by fxcoudert** [comment]
Audit issue was fixed by removing universal build option.

**Comment by ilovezfs** [comment]
@fxcoudert Thanks for the PR! Do you mind doing the `ceres-solver: revision for eigen` PR for this?

**Comment by fxcoudert** [comment]
Why do we need to rebuild `ceres-solver` when one of its dependencies is updated?

**Comment by ilovezfs** [comment]
Because upstream is paranoid and assumes every release will break ABI compatibility. Hence:
```
iMac-TMP:homebrew-core joe$ brew test ceres-solver
Testing homebrew/science/ceres-solver
==> Using the sandbox
==> cmake -DCeres_DIR=/usr/local/Cellar/ceres-solver/1.12.0_1/share/Ceres .
Last 15 lines from /Users/joe/Library/Logs/Homebrew/ceres-solver/test.01.cmake:
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:217 (ceres_report_not_found)
  CMakeLists.txt:3 (find_package)


CMake Error at CMakeLists.txt:3 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/Ceres/CeresConfig.cmake

  but it set Ceres_FOUND to FALSE so package "Ceres" is considered to be NOT
  FOUND.


-- Configuring incomplete, errors occurred!
See also "/tmp/ceres-solver-test-20170203-56212-1mci7vn/CMakeFiles/CMakeOutput.log".
Error: homebrew/science/ceres-solver: failed
Failed executing: cmake -DCeres_DIR=/usr/local/Cellar/ceres-solver/1.12.0_1/share/Ceres .
/usr/local/Homebrew/Library/Homebrew/formula.rb:1834:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1772:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1772:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/ceres-solver.rb:66:in `block in <class:CeresSolver>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1671:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:884:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1670:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1664:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Pull request closed without merging**
