### PR TITLE
various: remove emojis

### PR DESCRIPTION
**Pull request by razvanazamfirei**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR removes emojis from the description.

### CODE REVIEW

**Comment by p-linnane** [comment]
I've switched the labels since we aren't making any changes that necessitate testing the builds.

**Comment by chenrui333** [comment]
> This PR removes emojis from the description.

why do we want to remove emojis?

**Comment by razvanazamfirei** [comment]
> why do we want to remove emojis?

They don't really add useful information to the description and are visually distracting. 

Our [guideline](https://docs.brew.sh/Cask-Cookbook#stanza-desc) for casks already suggests concise descriptions and the avoidance of fluff.

**Comment by chenrui333** [comment]
> > why do we want to remove emojis?
> 
> They don't really add useful information to the description and are visually distracting.
> 
> Our [guideline](https://docs.brew.sh/Cask-Cookbook#stanza-desc) for casks already suggests concise descriptions and the avoidance of fluff.

is there anyway that we can also update formula-cookbook as well as adding an `audit`?

**Comment by p-linnane** [comment]
> > why do we want to remove emojis?
> 
> They don't really add useful information to the description and are visually distracting.
> 
> Our [guideline](https://docs.brew.sh/Cask-Cookbook#stanza-desc) for casks already suggests concise descriptions and the avoidance of fluff.

I am :+1: on this for the same reasons. Most of the ones removed by this PR are completely unrelated to the description as well.

**Review by p-linnane — APPROVED** [review]

**Comment by p-linnane** [comment]
I've added https://github.com/Homebrew/homebrew-core/labels/automerge-skip to allow others to chime in.

cc @Homebrew/core

**Review by branchv — APPROVED** [review]

**Review by SMillerDev — DISMISSED** [review]
> Our guideline for casks already suggests concise descriptions and the avoidance of fluff.

Those don't apply here though, and have never really applied to emoji afaik. Currently this pr is just personal preference so this should be added as an actual rule first, preferably with an audit.

**Comment by MikeMcQuaid** [comment]
Agreed with @SMillerDev that this is the sort of things where we should change automated checks first and only then, if there's ✅ and consensus, remove these sorts of things. Otherwise they will just get added back.

**Comment by razvanazamfirei** [comment]
> Those don't apply here though, and have never really applied to emoji afaik.

That's true, but I believe the spirit of the rule should apply regardless of whether it made it on the Formula Cookbook. Even if `desc` rules are not appropriate to `core`, not allowing emojis would be consistent with previous project decisions. `HOMEBREW_NO_EMOJI` already recognizes that emojis can be divisive.

> this pr is just personal preference 
💯 

> so this should be added as an actual rule first, preferably with an audit.

Happy to do this, but given the small number of formulae impacted, the effort felt disproportionate.

**Comment by fxcoudert** [comment]
I agree that this rule should exist. We will need to merge this PR to get https://github.com/Homebrew/brew/pull/15572 tests to pass.

**Review by fxcoudert — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
