### PR TITLE
Sandrasi/fix lixuxbrew postgis install

### PR DESCRIPTION
**Pull request by sandrasi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes the installation of the PostGIS under Linuxbrew.

Currently, when running `$ brew install postgis` under Linux everything seems to work out fine except no files are copied from the temporary build directory:
```
==> Downloading https://download.osgeo.org/postgis/source/postgis-2.5.3.tar.gz
Already downloaded: /home/sandrasi/.cache/Homebrew/downloads/bb221060ce3d64d32854a7ca9a65cbbe770c0295584e7ac13082343149ced0eb--postgis-2.5.3.tar.gz
==> ./configure --with-projdir=/home/linuxbrew/.linuxbrew/opt/proj --with-jsondir=/home/linuxbrew/.linuxbrew/opt/json-c --with-pgconfig=/home/linuxbrew/.linuxbrew/
==> make
==> make install DESTDIR=/tmp/postgis-20190906-11061-10nmsqm/postgis-2.5.3/stage
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/postgis/2.5.3/bin
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/postgis/2.5.3/share/doc/postgis/postgresql/extension
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/postgis/2.5.3/share/postgresql/extension
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/postgis/2.5.3/share/postgis
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/postgis/2.5.3/share/postgis_topology
🍺  /home/linuxbrew/.linuxbrew/Cellar/postgis/2.5.3: 24 files, 3.8MB, built in 43 seconds
```
It is because the PostGIS formula uses Ruby's `Dir` class to find all the files that need to be installed, but that class - as it's currently used in the formula - doesn't match on dotfiles. Linuxbrew, by default, is installed into the _/home/linuxbrew/.linuxbrew_ hidden directory - a directory that has a dot in its name. This path also appears in the temporary build path so when the formula is about to install the built files, `Dir["some/**/path/*"]` silently ignores all of them. This results in an incomplete install and when later trying to install the PostGIS extension into a database the following error occurs:
```
$ psql postgis_test
psql (11.5)
Type "help" for help.

postgis_test=# CREATE EXTENSION postgis;
2019-09-06 23:00:48.149 PDT [29777] ERROR: could not open extension control file "/home/linuxbrew/.linuxbrew/share/postgresql/extension/postgis.control": No such file or directory
```
This PR attempts to fix it by replacing all the `Dir` instances with a custom `dir(pattern)` method that matches on all files - including those whose name contains a dot. It also filters out the current (`.`) and the parent (`..`) directories.

Additional notes:
- A global fix would be preferable, in my opinion, so that hidden directories are never a problem when trying to find files with `Dir`, but I can't say for sure that every single formula could benefit from this. It works for the PostGIS formula, though.
- This is most likely never an issue in Homebrew as on a MacBook it's installed into the _/usr/local_ directory (so no dotfiles are on the path). This fix should not affect the Homebrew installations of PostGIS.
- This PR fixes the PostGIS installation but as of [this](https://github.com/Homebrew/linuxbrew-core/commit/aaf4e4e5d15b5d2718f8cab5f8007e175292db2c) very recent version upgrade of _Boost_ PostGIS errors out with a different runtime error (it works with Boost 1.70.0).

For more details see: https://github.com/Homebrew/linuxbrew-core/issues/15275

### CODE REVIEW

**Comment by sandrasi** [comment]
I have no idea why this PR shows 10k commits and 2k+ changed files. I've followed everything step by step on [this page](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request). I have even deleted my first attempt and started over but I got the same result at my second attemp. It looks like my branch is compared to an incorrect base?

**Comment by issyl0** [comment]
Hey @sandrasi, thanks for making this change! I think I know why it's showing so many commits.

You say you followed [these instructions](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#formulae-related-pull-request) about `brew --repo homebrew/core` and then setting a remote pointing to your fork. This is where it gets slightly confusing. The directory `brew --repo homebrew/core` on Linux actually has its git remote set to `Homebrew/linuxbrew-core`, so anything you push from that directory to the fork remote you configured, even if it's _named_ `homebrew-core`, will include all of the Linuxbrew commits as well. :sweat:

It's late, sorry if I didn't explain that very well! Let me know if anything's unclear and I'll can try again tomorrow?

What I do when I want to push changes upstream (to _this_ repo, not Linuxbrew) is to have an entirely separate checkout and fork of this repo in an entirely separate directory (eg "~/Projects/Homebrew/homebrew-core`) and make my changes there, isolated, so that the two will never conflict.

**Comment by sandrasi** [comment]
Hi @issyl0, thanks for the update! That makes sense. I'll close this PR then and make sure the right repo is forked.

**Comment by sandrasi** [comment]
Closed in favor of https://github.com/Homebrew/homebrew-core/pull/44014

**Pull request closed without merging**
