### PR TITLE
smlnj 110.79

### PR DESCRIPTION
**Pull request by rprimus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Added bits from @bfontaine PR [49530](https://github.com/Homebrew/legacy-homebrew/pull/49530)
as was also getting (inexplicable) install failure as reported in
issue [#49524](https://github.com/Homebrew/legacy-homebrew/issues/49524)

### CODE REVIEW

**Comment by rprimus** [comment]
Fri Aug 12 10:52:40 BST 2016

Builds cleanly on Yosemite, El Capitan
Failing on Mavericks:

```
FATAL:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../libexec/as/i386/as: I don't understand 'm' flag!
```

**Comment by MikeMcQuaid** [comment]
It may be worth asking upstream if they wish to support Mavericks. If not, we can add a `depends_on ` for Yosemite and above.

**Comment by rprimus** [comment]
Sun Aug 14 12:22:35 BST 2016

Email sent to [upstream](mailto:smlnj-dev-list@mailman.cs.uchicago.edu) and CC'd to
[homebrew-discuss](https://groups.google.com/forum/#!topic/homebrew-discuss/DULMlLQhJR8)

**Comment by MikeMcQuaid** [comment]
Thanks @rprimus!

**Comment by rprimus** [comment]
Tue Aug 16 17:15:39 BST 2016

Prof. John Reppy has [replied](https://groups.google.com/d/msg/homebrew-discuss/DULMlLQhJR8/VU5SH-y7BAAJ) stating that the build script will be updated for version ```110.80```.

Would it be OK to add the ```depends on``` for 110.79?

**Comment by MikeMcQuaid** [comment]
@rprimus I'm wondering if it's worth holding off until that version is released so we don't block folks on Mavericks and below?

**Comment by rprimus** [comment]
Thu Aug 18 00:40:52 BST 2016

@MikeMcQuaid It would be good to know if either of the (Yosemite, El Capitan) bottles work on Mavericks.

The smlnj team do have a [pkg](http://smlnj.cs.uchicago.edu/dist/working/110.79/smlnj-x86-110.79.pkg) (for Snow Leopard or later).  (My macOS foo does not yet extend to dmg/pkg building.)

I'll defer to your experience on what's best here.

**Comment by rprimus** [comment]
Thu Aug 18 08:38:45 BST 2016

Looking into the ```pkg``` file (at the Bom), there appears to be a single ```darwin``` executable and object file:

```
rprimus@mbp /usr/local/Cellar/smlnj/110.79/SMLNJ_HOME/bin/.run
 % ls -la
total 512
drwx------   4 rprimus  staff     136 12 Aug 09:56 .
drwx------  18 rprimus  staff     612 12 Aug 09:57 ..
-rwx------   1 rprimus  staff  125584 12 Aug 09:56 run.x86-darwin
-rw-------   1 rprimus  staff  133220 12 Aug 09:56 runx.x86-darwin
rprimus@mbp /usr/local/Cellar/smlnj/110.79/SMLNJ_HOME/bin/.run
 % file *
run.x86-darwin:  Mach-O executable i386
runx.x86-darwin: Mach-O object i386
rprimus@mbp /usr/local/Cellar/smlnj/110.79/SMLNJ_HOME/bin/.run
 % otool -L run.x86-darwin
run.x86-darwin:
       	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

From the ```readme.html``` file (in Resources), these work on the following:

```
  x86
    Mac OS X 10.6 (Snow Leopard)
    Mac OS X 10.7 (Lion)
    Mac OS X 10.8 (Mountain Lion)
    Mac OS X 10.9 (Mavericks)
    Mac OS X 10.10 (Yosemite)
    Mac OS X 10.11 (El Capitan)
```

Do you have any pointers to info where I can find what makes a single ```osx``` binary compatible with multiple versions of the OS (for a specific architecture)?

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid It would be good to know if either of the (Yosemite, El Capitan) bottles work on Mavericks.

We don't support that configuration, unfortunately.

**Comment by rprimus** [comment]
Fri Aug 19 09:03:26 BST 2016

@MikeMcQuaid 

As upstream provides a ```.pkg``` (which accommodates many more older versions of macOS), would it make sense to remove this formula and create a cask instead?

**Comment by MikeMcQuaid** [comment]
@rprimus Nah, we're trying to keep Cask only for GUI .apps. Let's let this sit for a while and see if we get a new release in the near future.

**Comment by apjanke** [comment]
110.80 is out!  http://www.smlnj.org/dist/working/110.80/index.html

**Comment by rprimus** [comment]
Tue 23 Aug 2016 07:51:40 BST

@apjanke @MikeMcQuaid 

New pull request submitted #4161 for ```110.80```

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/4161 then.

**Pull request closed without merging**
