### PR TITLE
dockerize 0.6.1 (new formula)

### PR DESCRIPTION
**Pull request by ruudk**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Replaces #34840

### CODE REVIEW

**Comment by ruudk** [comment]
@fxcoudert what do you think?

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Looks good to me, will give the other maintainers some time to chime in if they want.

**Comment by SMillerDev** [comment]
👍

**Comment by fxcoudert** [comment]
Thanks @ruudk for the pull request!

**Pull request closed without merging**
