### PR TITLE
gtk+3 3.24.18

### PR DESCRIPTION
**Pull request by tschoonj**
@bo98 @jonchang I hope this one is not cursed like #52817 :-)

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
I'm beginning to think @BrewTestBot hates gtk+3.

**Comment by tschoonj** [comment]
😢

**Comment by Bo98** [comment]
It's the `+` that broke everything.

Homebrew/brew#7351

**Comment by tschoonj** [comment]
Wow, great catch!

**Pull request closed without merging**
