### PR TITLE
jpeg-turbo 3.0.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  The following tests FAILED:
  	135 - djpeg-shared-3x2-float-prog-cmp (Failed)
  	246 - djpeg12-shared-3x2-float-prog-cmp (Failed)
  	430 - djpeg-static-3x2-float-prog-cmp (Failed)
  	541 - djpeg12-static-3x2-float-prog-cmp (Failed)
  Errors while running CTest
```

**Comment by timsutton** [comment]
> @timsutton I was under the impression upstream would work on a patch Monday, weren't they?

That's what they said, but that doesn't imply a new release anytime soon. Including this small patch, if all the deps are able to pass in CI, would unblock the 3.0.2 release in brew, since it's just a small build fix related to CMake.

**Comment by timsutton** [comment]
> Yes I'm not sure they'll cut out a new release, it's just that I thought the preferred policy was to always rely on upstream's patch when they exist (and that it'd also allow to know if the patch is valid within the CI).
> 
> But maybe their patch will be the same, I don't know enough about CMake here.

When an upstream patch exists, I agree that we should use it. One doesn't yet exist in an "official" capacity from the maintainer(s), but we have two options which both work.

**Comment by timsutton** [comment]
```
==> brew install mapserver
==> brew install --only-dependencies mapserver
==> brew linkage --test mapserver
==> brew linkage --cached --test --strict mapserver
==> FAILED
Full linkage --cached --test --strict mapserver output
  Files with missing rpath:
    /opt/homebrew/Cellar/mapserver/8.0.1_3/lib/python3.12/site-packages/mapscript/_mapscript.so
```

**Comment by timsutton** [comment]
I misread the failures, the reason CI failed on macOS workers was `qbs` and `yewtube`'s tests being reproducibly broken.

**Comment by timsutton** [comment]
* https://github.com/Homebrew/homebrew-core/pull/166412
* https://github.com/Homebrew/homebrew-core/pull/166417

**Comment by timsutton** [comment]
I think this is now unblocked, just need to find time for a full CI re-run with `CI-long-timeout`

**Review by fxcoudert — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by fxcoudert** [comment]
For minor/patchlevel updates like this, we could run with `skip-recursive-dependents`.

**Comment by timsutton** [comment]
> For minor/patchlevel updates like this, we could run with `skip-recursive-dependents`.

I was also noticing this on some other formula PRs.

I got the sense that in a number of cases minor bumps can still break downstream formulae. But from what I can understand, assuming ABI compatibility is held properly, downstream formulae shouldn't break for the reason of a minor bump – it may be that downstream formulae fail for other reasons unrelated to the actual version bump. So yeah, that would definitely help speed this up in the future, thanks!

**Pull request merged**
