### PR TITLE
libgit2 1.5.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
brew install --verbose --build-bottle dvc
brew install --verbose --build-bottle gitless
brew install --verbose --build-bottle literate-git
brew install --verbose --build-bottle salt

**Comment by chenrui333** [comment]
let's do a complete run first before applying the `revision bump` for all the formulae.

**Comment by Porkepix** [comment]
> let's do a complete run first before applying the `revision bump` for all the formulae.

I already had one, prior to all those revision bumps.

**Comment by chenrui333** [comment]
> > let's do a complete run first before applying the `revision bump` for all the formulae.
> 
> I already had one, prior to all those revision bumps.

yeah, the gitg should not be included

**Comment by chenrui333** [comment]
> brew install --verbose --build-bottle dvc 
> brew install --verbose --build-bottle gitless 
> brew install --verbose --build-bottle literate-git 
> brew install --verbose --build-bottle salt

@Porkepix, and the above build failures should also be addressed.

**Comment by Porkepix** [comment]
> > > let's do a complete run first before applying the `revision bump` for all the formulae.
> > 
> > 
> > I already had one, prior to all those revision bumps.
> 
> yeah, the gitg should not be included

Well, it was listed as not finding the `.dylib` here: https://github.com/Homebrew/homebrew-core/runs/7337032420?check_suite_focus=true so my understanding was that it needed it?

**Comment by chenrui333** [comment]
Yeah, that sounds about right, missed some checks with your commits earlier, now we are on the same page.

**Comment by nijikon** [comment]
@Porkepix will you be able to get back to this, or is it no longer an interest of yours?

**Comment by Bo98** [comment]
> Well, it was listed as not finding the `.dylib` here: https://github.com/Homebrew/homebrew-core/runs/7337032420?check_suite_focus=true so my understanding was that it needed it?

No, it's because of its `libgit2-glib` dependency rather than `gitg` itself:

```
 Library not loaded: /opt/homebrew/opt/libgit2/lib/libgit2.1.4.dylib
    Referenced from: /opt/homebrew/Cellar/libgit2-glib/1.0.0.1_1/lib/libgit2-glib-1.0.0.dylib
```

It's pretty common for these type of errors to appear as test failures for dependents further down the tree.

**Comment by Porkepix** [comment]
> > Well, it was listed as not finding the `.dylib` here: [Homebrew/homebrew-core/runs/7337032420?check_suite_focus=true](https://github.com/Homebrew/homebrew-core/runs/7337032420?check_suite_focus=true) so my understanding was that it needed it?
> 
> No, it's because of its `libgit2-glib` dependency rather than `gitg` itself:
> 
> ```
>  Library not loaded: /opt/homebrew/opt/libgit2/lib/libgit2.1.4.dylib
>     Referenced from: /opt/homebrew/Cellar/libgit2-glib/1.0.0.1_1/lib/libgit2-glib-1.0.0.dylib
> ```
> 
> It's pretty common for these type of errors to appear as test failures for dependents further down the tree, so whenever it's a test failure rather than a linkage failure it's worth reading the actual error output.

I'm not sure I understand what the current status is and what's now additionally broken? Doesn't seems like linkage issues anymore. I believe I had green tests at the beginning of this PR, but some revisions bumps were gotten rid of, and I get the feeling additional errors popped up?

> @Porkepix will you be able to get back to this, or is it no longer an interest of yours?

I can't reopen this anyway

**Comment by Bo98** [comment]
> I'm not sure I understand what the current status is and what's now additionally broken? Doesn't seems like linkage issues anymore. I believe I had green tests at the beginning of this PR, but some revisions bumps were gotten rid of, and I get the feeling additional errors popped up?

No it fails because `dvc`, `gitless`, `literate-git` and `salt` all fail to build from source because their `pygit2` resources need updating to 1.10.0 to support libgit2 1.5.0:

```
src/types.h:36:2: error: You need a compatible libgit2 version (1.4.x)
```

**Comment by Porkepix** [comment]
> > I'm not sure I understand what the current status is and what's now additionally broken? Doesn't seems like linkage issues anymore. I believe I had green tests at the beginning of this PR, but some revisions bumps were gotten rid of, and I get the feeling additional errors popped up?
> 
> No it fails because `dvc`, `gitless`, `literate-git` and `salt` all fail to build from source because their `pygit2` resources need updating to 1.10.0 to support libgit2 1.5.0:
> 
> ```
> src/types.h:36:2: error: You need a compatible libgit2 version (1.4.x)
> ```

Tried to push rev bumps for those and to update this module.
For my information, I did it manually but is there automated ways to update those modules? When those are updated through `brew bump`, it's most of the time updated automatically (with `pipgrip` iirc?) but in a few cases it doesn't, why in those case?

**Comment by Bo98** [comment]
> Tried to push rev bumps for those and to update this module.

You've got double (+2) revision bumps for those now.

> For my information, I did it manually but is there automated ways to update those modules? When those are updated through `brew bump`, it's most of the time updated automatically (with `pipgrip` iirc?) but in a few cases it doesn't, why in those case?

If you want to update everything then there's `brew update-python-resources`. `brew bump` does not look at dependents and `brew bump-revision` doesn't touch resources.

---

Looks like `libgit2-glib` also needs `depends_on "glib-utils" => :build`

**Comment by Porkepix** [comment]
> > Tried to push rev bumps for those and to update this module.
> 
> You've got double (+2) revision bumps for those now.

Damn. Fixed all those up.

> > For my information, I did it manually but is there automated ways to update those modules? When those are updated through `brew bump`, it's most of the time updated automatically (with `pipgrip` iirc?) but in a few cases it doesn't, why in those case?
> 
> If you want to update everything then there's `brew update-python-resources`. `brew bump` does not do revision bumps and `brew bump-revision` doesn't touch resources.

I've been quite confused here; `brew bump` do update python resources most of the time, right? But maybe it does so by running `brew update-python-resources`? But there are some times where it doesn't do those resources updates, right?

> Looks like `libgit2-glib` also needs `depends_on "glib-utils" => :build`

Pushed this change in the rev bump, but why only as a build dependency for `glib-utils` while `glib` is a full dependency? Also, previous run saw a bottle missing on this dependency for `gitg`.

Finally, runs will now needs a long CI run.

**Comment by Porkepix** [comment]
I don't understand why the syntax test fails on files that are not edited at all in this PR?

**Comment by Bo98** [comment]
You'll need to rebase on master to fix that.

**Comment by Porkepix** [comment]
Added a rev bump for `gitfs` which strangely seemed to be needed only for Linux (Why?)
There's still an issue of bottle not found (404) for gitg, and this whole PR now needs long CI runs now.

**Comment by Bo98** [comment]
> Added a rev bump for `gitfs` which strangely seemed to be needed only for Linux (Why?)

`gitfs` is a Linux-only formula.

> There's still an issue of bottle not found (404) for gitg, and this whole PR now needs long CI runs now.

Because you should be able to see that `libgit2-glib` still fails to build. Looks like it might need a `depends_on "python@3.10" => :build`.

**Comment by Porkepix** [comment]
> > There's still an issue of bottle not found (404) for gitg, and this whole PR now needs long CI runs now.
> 
> Because you should be able to see that `libgit2-glib` still fails to build. Looks like it might need a `depends_on "python@3.10" => :build`.

I tried to add it, however I'm not sure it's what is needed; this really seems like a missing bottle, I don't remember why but I know in the past weeks many bottles were removed and maintainers recreated and readded a bunch of them, maybe this one was not taken care of?

**Comment by Bo98** [comment]
> > > There's still an issue of bottle not found (404) for gitg, and this whole PR now needs long CI runs now.
> > 
> > 
> > Because you should be able to see that `libgit2-glib` still fails to build. Looks like it might need a `depends_on "python@3.10" => :build`.
> 
> I tried to add it, however I'm not sure it's what is needed; this really seems like a missing bottle, I don't remember why but I know in the past weeks many bottles were removed and maintainers recreated and readded a bunch of them, maybe this one was not taken care of?

The bottle it is complaining about is `libgit2-glib`. You've revision bumped that here so it is now at version 1.0.0.1_2, but the bottle of course will only be uploaded after this PR is merged so it doesn't exist yet.

The issue is that it's even trying to fetch a bottle. The reason it's trying to is because it failed to build and thus is not already installed. `brew test-bot` should skip testing `gitg` entirely in such scenarios - I'll look into fixing that - but the error will go away when `libgit2-glib` build is fixed which we would need to before merging anyway.

**Comment by Porkepix** [comment]
> > > > There's still an issue of bottle not found (404) for gitg, and this whole PR now needs long CI runs now.
> > > 
> > > 
> > > Because you should be able to see that `libgit2-glib` still fails to build. Looks like it might need a `depends_on "python@3.10" => :build`.
> > 
> > 
> > I tried to add it, however I'm not sure it's what is needed; this really seems like a missing bottle, I don't remember why but I know in the past weeks many bottles were removed and maintainers recreated and readded a bunch of them, maybe this one was not taken care of?
> 
> The bottle it is complaining about is `libgit2-glib`. You've revision bumped that here so it is now at version 1.0.0.1_2, but the bottle of course will only be uploaded after this PR is merged so it doesn't exist yet.
> 
> The issue is that it's even trying to fetch a bottle. The reason it's trying to is because `libgit2-glib` failed to build and thus is not already installed (and has no locally-generated bottle because the build failed). `brew test-bot` should skip testing `gitg` entirely in such scenarios - I'll look into fixing that - but the error will go away anyway when `libgit2-glib` build is fixed, which we would need to before merging in any case.

yeah didn't realized it was trying to get the revision bumped bottle…
So is the build failure related to something else you want to fix, as I read it, or is the `"python@3.10" => :build` required nonetheless?

**Comment by Bo98** [comment]
`"python@3.10" => :build` should fix it. The error was:

```
  --- stderr ---
  /usr/bin/env: ‘python3’: No such file or directory
  
  FAILED: install script '/tmp/libgit2-glib-20220809-123349-1dwzyoq/libgit2-glib-1.0.0.1/meson_vapi_link.py /home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/1.0.0.1_2/share' exit code 127, stopped
  FAILED: meson-internal__install 
```

**Comment by Porkepix** [comment]
Still needs a slot for a long build (or temporarily remove the long build tag so that it could be checked for Linux, which seemed to be the only job that was having failures; arm builds could end iirc and non-arm mac builds are to timeout).

**Review by carlocab — APPROVED** [review]

**Comment by nijikon** [comment]
Thank you for this 💜

**Pull request closed without merging**
