### PR TITLE
glib 2.56.2

### PR DESCRIPTION
**Pull request by tschoonj**
Will update commit when https://github.com/Homebrew/formula-patches/pull/251 is merged in and Jenkins build passes...

### CODE REVIEW

**Comment by DomT4** [comment]
Patches PR merged.

**Comment by DomT4** [comment]
Is this okay to ship now?

**Comment by tschoonj** [comment]
Ready to go

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/f814af8a3882215b4fb511784d12071eb7cf8feb. Thank you as always 🙇.

**Pull request closed without merging**
