### PR TITLE
octave, qscintilla2: migrate to Qt 6 (for real)

### PR DESCRIPTION
**Pull request by fxcoudert**
Let's try this again!
See https://savannah.gnu.org/bugs/?64498

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is head only, so CI will not be able to test it.

**Comment by mmuetzel** [comment]
@fxcoudert: Sorry to bother you. I'm not sure if you are receiving notifications from Savannah. So, I'm trying here as well:
I'd like to add CI for Octave with Qt6 on macOS. Do you know to which actual paths expressions like `-F#{Formula["qt"].opt_prefix}/Frameworks` (and the others in this PR) correspond when installing Qt6 with Homebrew (on a GitHub hosted runner)?

**Comment by fxcoudert** [comment]
@mmuetzel `Formula["qt"].opt_prefix` is `/opt/homebrew/opt/qt` on ARM and `/usr/local/opt/qt` on Linux. Or `${HOMEBREW_PREFIX}/opt/qt` if `HOMEBREW_PREFIX` is set to the output of `brew --prefix`.

**Comment by mmuetzel** [comment]
Thank you for that information. That was quite helpful.

I added runners to the CI of Octave that build with Qt6 on macOS using Homebrew:
https://github.com/gnu-octave/octave/commit/7374513687c0432d2f653367d672887118aed09d

Currently, these runners can't build the built-in editor. That's because the version of QScintilla distributed by Homebrew is built against Qt5.

Would it be possible (at least for a transition period) that Homebrew shipped two versions of QScintilla? One version that links against Qt5 and another one that links against Qt6.
That might help testers to catch early on if something isn't quite right...

**Comment by mmuetzel** [comment]
@fxcoudert: Sorry to bother. Would it be possible (at least for a transition period) that Homebrew shipped two versions of QScintilla? One version that links against Qt5 and another one that links against Qt6.

**Comment by fxcoudert** [comment]
@mmuetzel if it helps with the transition, we could consider it, yes

**Comment by mmuetzel** [comment]
@fxcoudert: Thanks. I'd appreciate that.
I'm on Windows. So, I don't know if I could test this at all. I'd need to work completely in the dark when trying to add it. Would you be able to add the Qt6 version of QScintilla to Homebrew please?
In case you'll add it: Could you please ping me when it is ready?

**Pull request closed without merging**
