### PR TITLE
liblbfgs 1.10 (new formula)

### PR DESCRIPTION
**Pull request by parsiad**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
There has been no release since 2010, and no code changes since then either (except trivial MSCV compatibility fixes every 3 years). I am not sure this qualifies as actively maintained…

**Comment by parsiad** [comment]
@fxcoudert I just followed the Homebrew guidelines to create this formula. I did not see anything there about the project being actively maintained being a prerequisite for inclusion (perhaps I missed it, in which case can I trouble you for a link?). liblbfgs is a very stable piece of software and it is widely used. As far as I know, it is the most widely used C implementation of L-BFGS.

**Comment by fxcoudert** [comment]
https://docs.brew.sh/Acceptable-Formulae

> The software in question must:
> - be maintained (i.e. the last release wasn’t ages ago, it works without patching on all supported macOS releases and has no outstanding, unpatched security vulnerabilities)

**Comment by fxcoudert** [comment]
Other question is: why does it depend on gcc? Does it not build with the system compiler?

**Comment by parsiad** [comment]
@fxcoudert The dependence on gcc might have been a mistake on my part. I apologize.

**Comment by fxcoudert** [comment]
Also of note is: this library is a single C file (and a single header file). From a GitHub search, it appears a lot of software using it is simply including the C file (and header) into their source

**Comment by parsiad** [comment]
@fxcoudert: I always viewed that approach as a bit inelegant (from a software-engineering perspective), hence why I created the formula.

**Comment by ilovezfs** [comment]
Agreed with fxcoudert that given there has been no release since 2010 and that it's a single C file under the MIT license that this is best off vendored in projects that need it. Thanks for the PR nonetheless @parsiad

**Pull request closed without merging**
