### PR TITLE
boost, boost-python3, boost-mpi 1.76.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
@scpeters would you know why we build `boost` and `boost-python3` with `c++14`, but `boost-mpi` with `c++11`? That doesn't seem right, but perhaps it's intentional?

**Comment by carlocab** [comment]
ARM:
```
Error: 15 failed steps!
brew test --retry --verbose avro-cpp
brew test --retry --verbose cucumber-cpp
brew test --retry --verbose freeling
brew test --retry --verbose ledger
brew test --retry --verbose lgogdownloader
brew test --retry --verbose libbitcoin-client
brew test --retry --verbose libbitcoin-explorer
brew test --retry --verbose libbitcoin-protocol
brew test --retry --verbose libbitcoin-server
brew test --retry --verbose libpulsar
brew test --retry --verbose monero
brew test --retry --verbose ncmpcpp
brew test --retry --verbose source-highlight
brew test --retry --verbose widelands
brew test --retry --verbose wownero
```

**Comment by carlocab** [comment]
Intel nodes are basically the same, except for a spurious `caffe` failure on Catalina, plus `libbitcoin-protocol` on Catalina and Big Sur.

**Comment by carlocab** [comment]
Lots of breakage here. Working this out will take a while.

**Comment by scpeters** [comment]
> @scpeters would you know why we build `boost` and `boost-python3` with `c++14`, but `boost-mpi` with `c++11`? That doesn't seem right, but perhaps it's intentional?

looking back through some github history:

* comment in the first attempt at boost 1.68.0: https://github.com/Homebrew/homebrew-core/pull/30914#issuecomment-412118646
* mentioned in description of 2nd attempt at 1.68.0: https://github.com/Homebrew/homebrew-core/pull/32610
* actual merge of c++14 changes in https://github.com/Homebrew/homebrew-core/commit/bb637405d0d7123b800964aca93fe10f58ec508d / https://github.com/Homebrew/homebrew-core/pull/33336

**Comment by carlocab** [comment]
I did try doing digging through the logs and related PRs, but came up empty 😅 I also don't know why we use `-1.66` here

https://github.com/Homebrew/homebrew-core/blob/ae0e1117848c478522497fe375aff8a5891eccec/Formula/boost.rb#L75

But these are both secondary to fixing all the build failures. The majority of them look related to changes in the Interprocess library (and perhaps with a bit of Regex on the side). But haven't really figured much beyond that.

**Comment by carlocab** [comment]
Well this is weird (Catalina):
```
Error: 17 failed steps!
brew linkage --test field3d
brew test --retry --verbose field3d
brew install --verbose --build-bottle source-highlight
brew install --build-from-source source-highlight
brew test --verbose libbitcoin-protocol
brew install --build-from-source source-highlight
brew test --verbose libbitcoin-client
brew install --verbose --build-bottle cucumber-cpp
brew install --verbose --build-bottle ledger
brew install --build-from-source source-highlight
brew test --verbose libbitcoin-explorer
brew install --build-from-source source-highlight
brew test --verbose libbitcoin-server
brew install --build-from-source source-highlight
brew install --verbose --build-bottle monero
brew install --build-from-source source-highlight
brew install --verbose --build-bottle wownero
```
Any idea what's going on here, @Bo98?

**Comment by carlocab** [comment]
`field3d` failure is due to opportunistic linkage to `open-mpi`. #75010

**Comment by carlocab** [comment]
Let's see if switching some of these dependencies will help...

**Comment by Bo98** [comment]
Boost 1.75 currently does not pass our versioned formula policy so it would be nice to avoid that if possible.

> I also don't know why we use `-1.66` here

This activates a legacy library naming system from 1.66. Without it, it puts the arch into the file library name, which is somewhat unusual and we decided against using it.

---

The linkage errors look like it could potentially be a mismatch of C++ versions. Boost::Regex now has a C++03 compatibility mode, which is deprecated and replaced by the newer the C++11 (and later) mode. It will be compiling Boost in the newer mode (because of the C++14 flag), but the nature of the changes means that users of Boost::Regex must also be compiling with C++11 or later or it will expect C++03 parts at link time which are simply not present.

It affects linkage because the newer C++11 and later mode is header-only (so no implementation part is present to link to in the library) while the legacy C++03 mode is not.

**Comment by carlocab** [comment]
> Boost 1.75 currently does not pass our versioned formula policy so it would be nice to avoid that if possible.

Yea, I just wanted to test what CI thought of it while I was figuring out a better solution.

> The linkage errors look like it could potentially be a mismatch of C++ versions. `Boost::Regex` now has a C++03 compatibility mode, which is deprecated and replaced by the newer the C++11 (and later) mode. It will be compiling Boost in the newer mode (because of the C++14 flag), but the nature of the changes means that users of Boost::Regex must also be compiling with C++11 or later or it will expect C++03 parts at link time which are simply not present.
> 
> It affects linkage because the newer C++11 and later mode of `Boost::Regex` does not have an implementation of `static_mutex::scoped_lock` (and thus will not be in the library file), but it is referenced internally by `Boost::Regex` headers when included under C++03 compatibility mode.

The `libbitcoin` formulae look to already be compiling with C++11, if the tests are of any indication. Will have a closer look at their build scripts, along with the rest of the formulae that don't work.

**Comment by carlocab** [comment]
Though, re https://github.com/Homebrew/homebrew-core/pull/75459#issuecomment-826398917, I was also wondering about the multiple appearances of `source-highlight`.

**Comment by Bo98** [comment]
> Though, re [#75459 (comment)](https://github.com/Homebrew/homebrew-core/pull/75459#issuecomment-826398917), I was also wondering about the multiple appearances of `source-highlight`.

This happens because `source-highlight` is a dependency that needs to be installed for other formulae like `libbitcoin` (via `asciidoc`), though evidently the absence of it doesn't seem to break too much.

Perhaps we should be skipping testing dependents in such scenarios. You can assign me a homebrew-test-bot issue if you want.

**Comment by Bo98** [comment]
> The `libbitcoin` formulae look to already be compiling with C++11

You're right. Though there's still something odd going on here. If it's using Boost::Regex V5 (C++11 and later mode), it should _not_ be referencing `boost::scoped_static_mutex_lock` at all. `boost::cpp_regex_traits<char>::get_catalog_name()`, which appears in the linker backtrace, instead uses `std::lock_guard` ([old v4](https://github.com/boostorg/regex/blob/boost-1.76.0/include/boost/regex/v4/cpp_regex_traits.hpp#L1098-L1100), [new v5](https://github.com/boostorg/regex/blob/boost-1.76.0/include/boost/regex/v5/cpp_regex_traits.hpp#L935-L937)).

V5 is automatically used in `boost/regex.hpp` depending on whether C++03 mode is activated: https://github.com/boostorg/regex/blob/boost-1.76.0/include/boost/regex.hpp#L31-L35. `BOOST_REGEX_CXX03` is set in `config.hpp` in a few conditionals.

**Comment by carlocab** [comment]
Ok, that is weird, and now I'm even more confused than before 🙂

**Comment by Bo98** [comment]
It's a hack, but an effective way to test would be to install Boost 1.76 locally and edit `include/boost/regex/config.hpp` to instead `#error` where it would normally define `BOOST_REGEX_CXX03`, and then try out some of the broken dependents.

**Comment by carlocab** [comment]
From the [release notes](https://www.boost.org/users/history/version_1_76_0.html):

> - Regex is now header only except in C++03 mode.

I wonder if formulae are still trying to link with the `boost_regex` library (when they shouldn't be at all) and that messes things up somehow.

**Comment by carlocab** [comment]
> From the [release notes](https://www.boost.org/users/history/version_1_76_0.html):
> 
> > * Regex is now header only except in C++03 mode.
> 
> I wonder if formulae are still trying to link with the `boost_regex` library (when they shouldn't be at all) and that messes things up somehow.

-----

If I'm reading this correctly (I may not), [this](https://github.com/libbitcoin/libbitcoin-system/blob/v3.6.0/m4/ax_boost_regex.m4#L78-L83) might be where it's happening for `libbitcoin`.

**Comment by Bo98** [comment]
It shouldn't invent symbols from nowhere though.

**Comment by carlocab** [comment]
It shouldn't, but that looks a lot like what was happening there, no?

**Comment by Bo98** [comment]
Which is why I gave the suggestion about finding out where `BOOST_REGEX_CXX03` is defined and why. I can have a look in a bit.

**Comment by carlocab** [comment]
Yup, no rush. I was going to try the same as well, just haven't gotten around to it.

**Comment by carlocab** [comment]
Another alternative here is to instead add a versioned `boost@1.73`. It seems like this one can be used by the current ones that don't work with Boost 1.76, plus can be used for some formulae where we vendor boost (`percona-server`, `percona-xtrabackup`).

**Comment by Bo98** [comment]
The version that Percona uses changes regularly. MySQL is the same, except that they bundle Boost so we use that.

**Comment by carlocab** [comment]
Yup, I was thinking more a second boost formula that isn't necessarily version-pinned.

**Comment by Bo98** [comment]
* `cucumber-cpp` - `-DCMAKE_CXX_STANDARD=11` works
* `source-highlight` - `ENV.cxx11` works.
* `libbitcoin` - haven't tested but I imagine `ENV.cxx11` works.
  - Other `libbitcoin-*` formulae are broken becuse the parent `libbitcoin` is broken.

---

* `ledger` - https://github.com/ledger/ledger/issues/2030 - I'll perhaps look at submitting a patch for this
* `monero`/`wownero` - probably a missing #include

**Comment by carlocab** [comment]
Tried setting `CMAKE_CXX_STANDARD` for `monero` and `wownero`. No dice. I can't even file an issue for `monero` because of repo restrictions.

**Comment by carlocab** [comment]
For monero: https://github.com/monero-project/monero/issues/7728

**Comment by loqs** [comment]
@carlocab does https://github.com/loqs/monero/commit/5e902e5e32c672661dfe5677c4a950c4dd409198 fix the monero build failure with boost 1.76.0 for you?

**Comment by carlocab** [comment]
Looks like it should. A similar fix should work for `wownero`. So I think that only leaves `ledger`?

**Comment by carlocab** [comment]
Ok, all the previous failures gone, but a new one emerged: `freeling`. Seems to have succeeded on Catalina though.

**Comment by carlocab** [comment]
CI is all ✅. Merging.

**Comment by carlocab** [comment]
```
Error: Autosquash can't squash commits that modify non-formula files.
```
Oops. I keep forgetting about that flag.

**Pull request closed without merging**
