### PR TITLE
wechat-plugin 1.7.2 (new formula) 

### PR DESCRIPTION
**Pull request by sfdye**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Why adding this formula?
[WeChatPlugin-MacOS](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS) is handy plugin for wechat on MacOS. There has been [request](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/94) for `brew install` support. The tool has a large user base and is actively maintained.

### CODE REVIEW

**Comment by lembacon** [comment]
This formula installs a prebuilt framework, however, per [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae), we are expecting formulae to be built from source.

**Comment by sfdye** [comment]
@lembacon I see. But does the jenkins pipeline support building macOS framework (Cocoapods)?

**Comment by lembacon** [comment]
@sfdye Yes, our CI does support building frameworks (e.g. `python`, `chisel`, `carthage`, and etc.). However, using CocoaPods is somehow impractical at this point, see https://github.com/Homebrew/homebrew-core/pull/31058#issuecomment-413991294. Unless you could figure out an alternative approach, you may want submit this to [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) instead.

**Comment by sfdye** [comment]
@lembacon Thank you for the input, that was very helpful. Seems like #33104 is happening soon. I will discuss with the original author of wechat plugin to see the possibility of switching from Cocoapods to Carthage.

**Comment by sfdye** [comment]
Probably won't have to the time to complete this before stale bot does its thing, so closing it for now.

**Pull request closed without merging**
