### PR TITLE
go@1.8: delete

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Go 1.8 hasn't been supported for six months.

### CODE REVIEW

**Comment by fxcoudert** [comment]
I think @MikeMcQuaid would like our policy to be: once it's included, don't remove it unless it's broken… or we have too many versions of the same formula.

I've launched a Mojave job to see if it builds fine: https://jenkins.brew.sh/job/Homebrew%20Mojave%20Testing/401/
If it does, I'd say we keep it around some more; if it doesn't then ☠️ 

(How about `go@1.4` which is clearly less used?)

**Comment by MikeMcQuaid** [comment]
> I think @MikeMcQuaid would like our policy to be: once it's included, don't remove it unless it's broken… or we have too many versions of the same formula.

Agreed 👍. It's not got a lot of installs (https://formulae.brew.sh/formula/go@1.8) but it's got enough that I think it's worth keeping unless we're getting user issues.

**Comment by fxcoudert** [comment]
It builds fine on Mojave and I have pushed a bottle.

**Comment by DomT4** [comment]
I'm not opposed to this PR/removing `go@1.8`. Baring in mind the last [go 1.8](https://groups.google.com/forum/#!topic/golang-announce/X7N1mvntnoU) release, and indeed, 2 of the last 4 releases IIRC, were security releases - if upstream is no longer checking or accepting security fixes for that branch as far as I'm concerned it should go.

**Review by DomT4 — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> if upstream is no longer checking or accepting security fixes for that branch as far as I'm concerned it should go.

Are there CVEs that affect this version?

**Comment by DomT4** [comment]
I don't think we can assume people are doing active security analysis on it at this point.

If people are absolutely determined to keep this around I'm content doing so until the next `go` security release, but at that point without firm information 1.8 is unaffected I strongly believe the right thing to do is to 🗑 it.

**Comment by MikeMcQuaid** [comment]
@DomT4 I don't think we should be removing software that non-trivial numbers of people are relying on if it's not a) broken, b) vulnerable or c) causing us grief in some other fashion.

**Comment by MikeMcQuaid** [comment]
When there's vulnerabilities that end up patched against future versions (even if it's unclear if they apply to this version) we can reconsider removing this.

**Comment by DomT4** [comment]
Till then, then.

**Comment by DomT4** [comment]
Till then, then.

**Pull request closed without merging**
