### PR TITLE
oil 0.12.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
linux test failure

```
  FATAL: couldn't import from app bundle '/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/bin/osh' (-1)
  Stripping the oil.ovm binary may cause this error.
  See https://github.com/oilshell/oil/issues/47
  Error: oil: failed
```

**Comment by carlocab** [comment]
Ideas, @Homebrew/linux?

**Comment by dawidd6** [comment]
I tried but failed. Arch and Alpine skip stripping of the resulting binary. Dunno if we do something like stripping in our superenv or elsewhere which could lead to the issue.

**Comment by dawidd6** [comment]
Yep, seems to work fine on my machine (in our container):
```
linuxbrew@17c7bd1c295d:~$ brew install -sv oil
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Downloading https://ghcr.io/v2/homebrew/core/ncurses/manifests/6.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ncurses/blobs/sha256:09c1d079d3b5cf1c855afa9da1fc7251234b73971d4cbe0bf7b9fca1cbea353c
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:09c1d079d3b5cf1c855afa9da1fc7251234b73971d4cbe0bf7b9fca1cbea353c?se=2022-10-13T07%3A15%3A00Z&sig=rXPzE2JMaZPlORHTJBBoTrGfPwKRF
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.2.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:7dc8f7ebbfcb22adcd5535a8da083ed8aa3c42c8579c465a2263d778868bc058
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:7dc8f7ebbfcb22adcd5535a8da083ed8aa3c42c8579c465a2263d778868bc058?se=2022-10-13T07%3A15%3A00Z&sig=k7qjHzIOJ8Ae0sYgLMAxCbub1XOab
######################################################################## 100.0%
==> Downloading https://www.oilshell.org/download/oil-0.12.7.tar.gz
######################################################################## 100.0%
==> Installing dependencies for oil: ncurses and readline
==> Installing oil dependency: ncurses
==> Pouring ncurses--6.3.x86_64_linux.bottle.tar.gz
==> Finishing up
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/ncurses/6.3: 3,958 files, 9.9MB
==> Installing oil dependency: readline
==> Pouring readline--8.2.1.x86_64_linux.bottle.tar.gz
==> Finishing up
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/readline/8.2.1: 50 files, 2MB
==> Installing oil
tar --extract --no-same-owner --file /home/linuxbrew/.cache/Homebrew/downloads/328e70571e8d80fead1b8eee1e8a2bac6b345f348b76b5866adc7022ff79501c--oil-0.12.7.tar.gz --directory /tmp/d20221013-2541-7cmc2o
cp -pR /tmp/d20221013-2541-7cmc2o/oil-0.12.7/. /tmp/oil-20221013-2541-d45zgw/oil-0.12.7
chmod -Rf +w /tmp/d20221013-2541-7cmc2o
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7 --with-readline=/home/linuxbrew/.linuxbrew/opt/readline
./configure INFO: Argument '--with-readline=/home/linuxbrew/.linuxbrew/opt/readline' not used by this configure script
./configure: Wrote _build/detected-config.sh and _build/detected-config.h
==> make
build/ovm-compile.sh build-opt _build/oil/ovm-opt _build/oil/module_init.c _build/oil/main_name.c _build/oil/c-module-srcs.txt
/tmp/oil-20221013-2541-d45zgw/oil-0.12.7/Python-2.7.13 /tmp/oil-20221013-2541-d45zgw/oil-0.12.7

real	0m21.489s
user	0m20.314s
sys	0m1.441s
/tmp/oil-20221013-2541-d45zgw/oil-0.12.7
objcopy --only-keep-debug _build/oil/ovm-opt _build/oil/ovm-opt.symbols
strip -o _build/oil/ovm-opt.stripped _build/oil/ovm-opt  # What's the difference with debug symbols?
# We need a relative path since it will be _bin/oil.ovm
objcopy --add-gnu-debuglink=_build/oil/ovm-opt.symbols _build/oil/ovm-opt.stripped
cat _build/oil/ovm-opt.stripped _build/oil/bytecode-opy.zip > _bin/oil.ovm
chmod +x _bin/oil.ovm
==> ./install
install: creating directory '/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/bin/'
'_bin/oil.ovm' -> '/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/bin/oil.ovm'
    Installed executable
    Created 'osh' symlink
    Created 'oil' symlink
install: creating directory '/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/share'
install: creating directory '/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/share/man'
install: creating directory '/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/share/man/man1/'
    Installed man page
'doc/osh.1' -> '/home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/share/man/man1/osh.1'
==> Cleaning
==> Finishing up
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7: 7 files, 4.3MB, built in 24 seconds
==> Running `brew cleanup oil`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
linuxbrew@17c7bd1c295d:~$ brew test -v oil
==> Testing oil
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/bin/osh -c shopt -q parse_backticks
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/bin/osh -c 'echo `pwd -P`'
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/bin/oil -c shopt -u parse_equals
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.7/bin/oil -c 'var foo = "bar"; write $foo'
```

**Comment by chenrui333** [comment]
a new PR, #116717

**Pull request closed without merging**
