### PR TITLE
stanc3 2.35.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

---

previously:
- #141480
- #143339
- #160142

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> Bottling stanc3--2.35.0.x86_64_linux.bottle.tar.gz...
  /home/linuxbrew/.linuxbrew/opt/gnu-tar/bin/tar --create --numeric-owner --mtime=2024-06-03 14:19:43 --sort=name --owner=0 --group=0 --numeric-owner --format=pax --pax-option=globexthdr.name=/GlobalHead.%n,exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime --file /github/home/bottles/stanc3--2.35.0.x86_64_linux.bottle.tar stanc3/2.35.0
  ==> Detecting if stanc3--2.35.0.x86_64_linux.bottle.tar.gz is relocatable...
  Error: data truncated
  Error: data truncated
```

same issue as before cc @Bo98 @caarlos0

**Comment by caarlos0** [comment]
wront @ @chenrui333

**Comment by Bo98** [comment]
> same issue as before

Thanks - will take a look tonight.

**Comment by Bo98** [comment]
This is caused by a bad `test/integration/good/array-expr/validate_array_expr_primitives`. I'm not entirely sure why upstream are shipping precompiled executables, but this one is corrupt.

I recommend slimming down `pkgshare.install "test"` to just the one file we use (or just download it as a resource).

**Comment by chenrui333** [comment]
now it works, thanks @Bo98!

**Review by carlocab — APPROVED** [review]

**Pull request merged**
