### PR TITLE
mono 4.4.0.182, fsharp 4.0.1.1

### PR DESCRIPTION
**Pull request by mfilippov**
Update mono version to latest release.

### CODE REVIEW

**Comment by DomT4** [comment]
`nant` (which uses `mono`) blew up on testing:

```
==> /usr/local/Cellar/nant/0.92/bin/nant
NAnt 0.92 (Build 0.92.4543.0; release; 09/06/2012)
Copyright (C) 2001-2012 Gerry Shaw
http://nant.sourceforge.net


BUILD FAILED

Mono 4.0 Profile (mono-4.0) is not installed, or not correctly configured.

    The 'System.dll' assembly does not exist in framework assembly directory '/usr/local/lib/pkgconfig/../../lib/mono/4.0'.

For more information regarding the cause of the build failure, run the build again in debug mode.

Try 'nant -help' for more information
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Error: nant: failed
```

That smells like an upstream issue, but `nant` is pretty slowly developed at the moment, so if there's not a simple way to fix this we may have to 💀 `nant` for a time.

**Comment by mfilippov** [comment]
Can I help resolve this issue?

**Comment by mfilippov** [comment]
I see nant use .NET 4.0 version as max but mono drop it start from 4.0 http://www.mono-project.com/docs/about-mono/releases/4.0.0/ I think is bad project for testing.

**Comment by DomT4** [comment]
I opened https://github.com/Homebrew/homebrew-core/pull/2013 to remove `nant`. This PR will pass fine without that.

**Comment by mfilippov** [comment]
When can I wait merge it PR?

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/fc080a10b19cb4f835c2fade4bbce81a8d5cd7d2. Thank you for your contribution to Homebrew @mfilippov; we appreciate it! :smiley_cat:

**Pull request closed without merging**
