### PR TITLE
vlang 0.3.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on linux
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/vlang/0.3.2/bin/v -o test hello_world.v
  ==================
  /usr/bin/ld: failed to set dynamic section sizes: bad value
  collect2: error: ld returned 1 exit status
```

**Comment by chenrui333** [comment]
@Homebrew/linux can someone help with the linux build? thanks!

**Comment by danielnachun** [comment]
This error is reminiscent of the issues we have when we need to set `-fPIE` for GCC.  I haven't found a way to set this yet - it ignores `CFLAGS` and does not accept `-fPIE` as an argument like GCC/Clang do.  If I can't figure this out in the next day or so I will open an upstream issue about this because this seems like a rather fundamental problem with using `v`.

**Comment by chenrui333** [comment]
Sounds good, thanks @danielnachun!!

**Comment by alebcay** [comment]
I added flags `-cg` on the `v` test command and it provided a bit more context:

```
==> /home/linuxbrew/.linuxbrew/Cellar/vlang/0.3.2/bin/v -cg -o test hello_world.v
/usr/bin/ld: /home/linuxbrew/.linuxbrew/opt/bdw-gc/lib/libgc.a(malloc.o): relocation R_X86_64_32 against symbol `GC_allocate_ml' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

@danielnachun - please correct me if I'm wrong (I'm not very familiar with the prior `-fPIE` changes made) but it looks like this is an issue with brewed `bdw-gc`?

**Comment by danielnachun** [comment]
@alebcay thanks for digging deeper into this!  Everything I had found for this was indicating that `v` was supposed to just be using the same default options as GCC so I couldn't understand why it was still giving `-fPIE` errors - this explanation makes a lot more sense.

I can also see that the latest release of `bdw-gc` was still built on Ubuntu 16.04 https://github.com/Homebrew/homebrew-core/pull/108995, so it makes total sense that it wasn't built with `-fPIE`.  I have dispatched a rebottle of `bdw-gc` - when that is done we can rebase this and it should work!

**Review by danielnachun — APPROVED** [review]
Linux now passes the test.  This should be ready to go when the macOS runners are done.

**Pull request merged**
