### PR TITLE
python-tabulate: use venv

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

For #167905

Decided to keep since this provides a CLI

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
I don't feel strongly either way but: https://github.com/astanin/python-tabulate

The project pretty clearly looks to me like it's called "python-tabulate".

If we ever end up packaging https://github.com/p-ranav/tabulate: it seems like a better fit for the name.

I'd vote to leave as-is (but don't feel strongly).

**Comment by branchvincent** [comment]
Don't feel strongly either so I'm fine keeping it as `python-tabulate`, just figured we would drop all our `python-` name prefixes for consistency. [Repology](https://repology.org/project/python:tabulate/versions) does show mostly `python-tabulate`[^1], but some packagers follow their own python package naming conventions, such as 

* `py3-tabulate` (alpine)
* `py-tabulate` (macports)
* `tabulate` (OpenIndiana)

And although the repo is called `python-tabulate`, the PyPI [package](https://pypi.org/project/tabulate/), import name, and CLI are all just `tabulate`. I'm assuming we'll eventually drop this anyway because its mostly a library, I doubt many people know it has a CLI. Even in its current form being installed as a library in global site packages, it's not that popular:

```
install-on-request: 192 (30 days), 695 (90 days), 6,395 (365 days)
```

---

I'll let folks add any additional thoughts before updating the PR to keep it as `python-tabulate`

[^1]: But this isn't too surprising since most packagers use a `python-` prefix for any PyPI package, for example https://github.com/pypa/setuptools is just called `setuptools` but instead mostly `python-setuptools` on [repology](https://repology.org/project/python:setuptools/versions)

**Review by p-linnane — APPROVED** [review]
Makes sense to me based off the above comment.

**Comment by MikeMcQuaid** [comment]
> Don't feel strongly either so I'm fine keeping it as `python-tabulate`, just figured we would drop all our `python-` name prefixes for consistency.

I think we should be primarily consistent with upstream naming and then consistent with our own "rules" (which can be changed more easily).

>for example [pypa/setuptools](https://github.com/pypa/setuptools) is just called `setuptools` but instead mostly `python-setuptools` on [repology](https://repology.org/project/python:setuptools/versions)

Yeh, I think this is an example of where if upstream was calling it "python-setuptools" I'd say we should do the same, too.

**Comment by branchvincent** [comment]
Restored the name, now this PR just switches to a venv so we only expose the CLI

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
