### PR TITLE
grakn 1.5.3

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
```
10:40:12 ==> Downloading https://github.com/graknlabs/grakn/releases/download/1.5.3/grakn-core-all-mac-1.5.3.zip
10:40:12 Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/3b23688ea0cadddbbc200f2a5ade9ce1da3597dde98d591df9f9a4f56a3615aa--grakn-core-all-mac-1.5.3.zip
10:40:12 ==> Verifying 3b23688ea0cadddbbc200f2a5ade9ce1da3597dde98d591df9f9a4f56a3615aa--grakn-core-all-mac-1.5.3.zip checksum
10:40:12 unzip /Users/brew/Library/Caches/Homebrew/downloads/3b23688ea0cadddbbc200f2a5ade9ce1da3597dde98d591df9f9a4f56a3615aa--grakn-core-all-mac-1.5.3.zip -d /private/tmp/d20190512-88985-13ox91n
10:40:12 cp -pR /private/tmp/d20190512-88985-13ox91n/grakn-core-all-mac-1.5.3/. /private/tmp/grakn-20190512-88985-8iq0zr/grakn-core-all-mac-1.5.3
10:40:12 chmod -Rf +w /private/tmp/d20190512-88985-13ox91n
10:40:12 Error: An exception occurred within a child process:
10:40:12   Errno::ENOENT: No such file or directory - /usr/local/Cellar/grakn/1.5.3/libexec/graql
10:40:12 
10:40:12 ==> brew audit grakn --online
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
The layout of the distributed archive has changed, so you need to adapt the formula

**Comment by chenrui333** [comment]
Cool, I will update the formula now.

**Pull request closed without merging**
