### PR TITLE
percona-server 8.0.16-7

### PR DESCRIPTION
**Pull request by chelout**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
07:54:25 -- Detecting CXX compile features - done
07:54:25 -- Source directory /private/tmp/percona-server-20191016-31716-t4ma64/percona-server-8.0.16-7
07:54:25 -- Binary directory /private/tmp/percona-server-20191016-31716-t4ma64/percona-server-8.0.16-7
07:54:25 CMake Error at CMakeLists.txt:304 (MESSAGE):
07:54:25   Please do not build in-source.  Out-of source builds are highly
07:54:25   recommended: you can have multiple builds for the same source, and there is
07:54:25   an easy way to do cleanup, simply remove the build directory (note that
07:54:25   'make clean' or 'make distclean' does *not* work)
07:54:25 
07:54:25   You *can* force in-source build by invoking cmake with
07:54:25   -DFORCE_INSOURCE_BUILD=1
07:54:25 
07:54:25 
07:54:25 -- Configuring incomplete, errors occurred!
07:54:25 See also "/tmp/percona-server-20191016-31716-t4ma64/percona-server-8.0.16-7/CMakeFiles/CMakeOutput.log".
07:54:25

**Comment by chelout** [comment]
@chenrui333 made a fix in the morning, but check is pending is it ok?

**Comment by SMillerDev** [comment]
Why does this not use homebrews boost?

**Comment by chelout** [comment]
@SMillerDev mysql and percona needs exact version of boost.

**Comment by chelout** [comment]
> -- BOOST_VERSION_NUMBER is #define BOOST_VERSION 106700
> CMake Warning at cmake/boost.cmake:288 (MESSAGE):
>   Boost minor version found is 67 we need 69
> Call Stack (most recent call first):
>   CMakeLists.txt:878 (INCLUDE)
> 
> 
> -- BOOST_INCLUDE_DIR /tmp/percona-server-20191017-96803-1ahdkzb/percona-server-8.0.16-7/boost
> -- LOCAL_BOOST_DIR /tmp/percona-server-20191017-96803-1ahdkzb/percona-server-8.0.16-7/boost
> -- LOCAL_BOOST_ZIP LOCAL_BOOST_ZIP-NOTFOUND
> -- Could not find (the correct version of) boost.
> -- MySQL currently requires boost_1_69_0

**Comment by SMillerDev** [comment]
Can you squash all your commits into one named `percona-server 8.0.16-7`?

**Comment by chelout** [comment]
@SMillerDev done

**Comment by SMillerDev** [comment]
Thanks @chelout! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by chelout** [comment]
Thanks @SMillerDev just my 2 cents to open source ;)

**Pull request closed without merging**
