### PR TITLE
chromaprint 1.3.2

### PR DESCRIPTION
**Pull request by dunn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by dunn** [comment]
Does this mean it expects it to be installed and it's not?
```
https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8198/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/linkage___test_libgroove/

**Comment by DomT4** [comment]
Try chucking a `revision` bump onto `libgroove`. Usually solves the issue.

**Comment by dunn** [comment]
Oh wow, I must have been tired; I thought that was a lib installed by chromaprint itself.

**Comment by dunn** [comment]
Wheeee
```
In file included from /tmp/libgroove-20160925-12053-1ov8e3y/libgroove-4.3.0/grooveplayer/player.c:18:
/tmp/libgroove-20160925-12053-1ov8e3y/libgroove-4.3.0/grooveplayer/osx_time_shim.h:21:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.

**Comment by dunn** [comment]
https://github.com/andrewrk/libgroove/issues/129

**Comment by fxcoudert** [comment]
There's a newer version now, and another PR for it (with the same issue): #8595

**Pull request closed without merging**
