### PR TITLE
mkcert 1.0.0

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
🔒

**Comment by 0rvar** [comment]
Why was this closed?

**Comment by ilovezfs** [comment]
everything with a bottle is "closed" not "merged". look above and you'll see 

```
@ilovezfs ilovezfs closed this in 042b848 6 days ago
```
which shows in which commit it was integrated

**Comment by 0rvar** [comment]
Ah, sorry!

**Comment by ilovezfs** [comment]
@0rvar no worries. it's confusing to everyone

**Pull request closed without merging**
