### PR TITLE
dartsim: revision bump for bullet

### PR DESCRIPTION
**Pull request by scpeters**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The `bullet` formula switched from single-precision floating point to double precision in #67504, then back to single precision in #68634. The `dartsim` bottle was not rebuilt in #68634, which is causing some `dyld: Symbol not found` errors (details in https://github.com/Homebrew/homebrew-core/issues/68623#issuecomment-758509115). This revision  bump should fix the ABI.

It's possible that `efl` needs to be rebuilt as well, but I have not confirmed, so I am just bumping `dartsim` for now.

### CODE REVIEW

**Comment by carlocab** [comment]
FYI, this will cause a merge conflict with https://github.com/Homebrew/homebrew-core/pull/65763

**Comment by carlocab** [comment]
```
make[2]: *** No rule to make target `/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/lib/libm.tbd', needed by `lib/libdart.6.9.5.dylib'.  Stop.
```
Same problem as #67615.

**Comment by scpeters** [comment]
> FYI, this will cause a merge conflict with #65763

I can defer to #65763 if it will be ready soon, but if not, then I'll let you suggest a timing for merging this, once we resolve the 11.0 sdk issue

**Comment by carlocab** [comment]
Let's wait for the current CI run at #65763 to finish and we can assess.

That said, this one is a bit harder to resolve, as pretty much all of the `dartsim`'s dependencies will depend on `libm`/`libSystem`.

I guess we can start by looking at all of `dartsim`'s dependencies that have not been rebuilt since https://github.com/Homebrew/brew/pull/10072 was merged.

**Comment by scpeters** [comment]
> Let's wait for the current CI run at #65763 to finish and we can assess.
> 
> That said, this one is a bit harder to resolve, as pretty much all of the `dartsim`'s dependencies will depend on `libm`/`libSystem`.
> 
> I guess we can start by looking at all of `dartsim`'s dependencies that have not been rebuilt since [Homebrew/brew#10072](https://github.com/Homebrew/brew/pull/10072) was merged.

I just did a grep on a Big Sur machine and saw a reference to `MacOSX11.0.sdk` in `libccd`, so I've added a revision bump to that too (sorry I didn't see you comment to wait). Is there a label we could add to say to wait before merging this?

**Comment by carlocab** [comment]
Well, that was quick. I'll keep an eye on the `icu4c` PR to determine when this one can be merged.

**Comment by scpeters** [comment]
> Well, that was quick. I'll keep an eye on the `icu4c` PR to determine when this one can be merged.

thanks!

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Another merge conflict emerged somehow, so no point in waiting on this one any longer.

**Review by chenrui333 — COMMENTED** [review]
👍

**Pull request closed without merging**
