### PR TITLE
perl 5.36.1

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

continuing #129146

### CODE REVIEW

**Comment by carlocab** [comment]
We shouldn't break `subversion`, since that will break other formulae that use `svn` to download.

**Comment by chenrui333** [comment]
we can proceed and I can regression test after the PR merge, and update the test for subversion on linux build if needed.

**Review by carlocab — CHANGES_REQUESTED** [review]
Given that breaking `svn` will break installation of other formulae, I think we should make sure `svn` is not broken _before_ merging this rather than after.

**Comment by iMichka** [comment]
As the path for the SVN perl client is versioned in subversion on Linux, you need to rev bump subversion.
It's looking in `/home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2_1/lib/perl5/site_perl/5.36.1/x86_64-linux-thread-multi`, which does not exist, unless you rebuild SVN.

**Comment by carlocab** [comment]
> As the path for the SVN perl client is versioned in subversion on Linux, you need to rev bump subversion.
> 
> It's looking in `/home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2_1/lib/perl5/site_perl/5.36.1/x86_64-linux-thread-multi`, which does not exist, unless you rebuild SVN.

We should find a way to make at least the patch version in that path go away, so it looks in something like `$prefix/lib/perl5/site_perl/5.36/...`.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
