### PR TITLE
libtorch 1.5.0

### PR DESCRIPTION
**Pull request by ankane**
Created with `brew bump-formula-pr`.

Edit: Sorry for the noise. This version bump wasn't as straightforward as expected.

### CODE REVIEW

**Comment by Bo98** [comment]
Untested, but this might fix the High Sierra build:

```rb
# Fix compile with Apple Clang 10.
patch do
  url "https://github.com/google/XNNPACK/commit/b18783570f0643560be641b193367d3906955141.patch?full_index=1"
  sha256 "5c17f0e38885ba48234cb89a9a0b101f9a760fa335efd1372b8fd1690dee5b21"
  directory "third_party/XNNPACK"
end
```

Xcode 11.4 compiler crash is known: https://github.com/Homebrew/homebrew-core/pull/52415#issuecomment-607446033

**Comment by ankane** [comment]
Awesome, thanks @Bo98. Trying the patch now. Will file an issue with the PyTorch team for the segmentation fault on Catalina.

**Comment by ankane** [comment]
For High Sierra, we could also try `USE_XNNPACK=OFF` if that's better than patching.

**Comment by Bo98** [comment]
I think the patch is fine if it works.

For the compiler crash, I believe https://github.com/pytorch/pytorch/issues/30584 and https://github.com/pytorch/pytorch/issues/36676 are related.

I think I've pinned it down to https://bugs.llvm.org/show_bug.cgi?id=43175 (mentions regex, but the problem is more general) which was fixed in https://github.com/llvm/llvm-project/commit/bead8bf31fb4a6bf02af67bd3029adb5dedf704f. This was fixed in Clang 9.0.1 but Xcode 11.4 (Apple Clang 11.0.3) is based on 9.0.0.

**Comment by Bo98** [comment]
> libtorch 0.1.5

1.5.0 :-)

**Comment by ankane** [comment]
(facepalm) that should have been the easiest part of the PR. Thanks @Bo98 :)

**Comment by Bo98** [comment]
There's a bit of debate upstream about the approach to take to solve the compiler crash. I think they're now settling on https://github.com/pytorch/pytorch/pull/37086.

Though the current patch is fine and harmless - I'll let you decide whether it's worth applying the new approach or not.

**Comment by ankane** [comment]
I'd lean towards the current patch since tests are green and it'll be removed in the next release.

**Comment by Bo98** [comment]
Cool, thanks @ankane!

**Comment by ankane** [comment]
Thanks for the help!

**Pull request closed without merging**
