### PR TITLE
open-scene-graph: fix build on 10.12

### PR DESCRIPTION
**Pull request by ilovezfs**
CMakeLists.txt can't grapple with 10.12 when it expects 10.12.0

Fixes issue #5389.

### CODE REVIEW

**Comment by zmwangx** [comment]
Hmm, OS X never had 10.x.0 releases as far back as my memory goes. Wonder how this worked before.

**Comment by ilovezfs** [comment]
it probably never did lol

**Comment by MikeMcQuaid** [comment]
Looks like `head` has moved to https://github.com/openscenegraph/OpenSceneGraph and there's much newer releases there that don't seem to have this same text so probably worth trying an upgrade instead?

**Comment by ilovezfs** [comment]
it looks like it worked
```
==> brew audit open-scene-graph
==> FAILED
Error: 1 problem in 1 formula
open-scene-graph:
  * Use MacOS.version instead of MACOS_VERSION
```
is the reason for CI failure. But yes an upgrade would be nice.

**Comment by ilovezfs** [comment]
Also the audit issue is a false positive. "MACOS_VERSION" is part of the source code LOL

**Comment by ilovezfs** [comment]
OK, new version compiles, so let's do that instead.

**Pull request closed without merging**
