### PR TITLE
abyss 2.3.1

### PR DESCRIPTION
**Pull request by jwong-1**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Previous attempt #73779

**Comment by jowong4** [comment]
```
pabyss:
  * The homepage URL https://www.bcgsc.ca/resources/software/abyss is not reachable
  ```

 I don't have any problem reaching the website: https://www.bcgsc.ca/resources/software/abyss .

**Comment by schutzekatze** [comment]
> Previous attempt #73779

That attempt has failed because of a bug fixed in this pull request.

This pull request seems to be failing because it can't reach the software homepage. Could this have been a temporary error, because we're able to reach the website? If so, perhaps it makes sense to restart the CI.

**Review by carlocab — APPROVED** [review]
Audit errors seem spurious, so we can ignore them.

**Comment by carlocab** [comment]
Thanks, @jowong4.

**Pull request closed without merging**
