### PR TITLE
dbt: migrate to tap

### PR DESCRIPTION
**Pull request by cmcarthur**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Migrates the dbt formula to https://github.com/fishtown-analytics/homebrew-dbt. We've built a CI process similar to homebrew's Jenkins over there. Added to tap_migrations.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Is there a reason? We generally only migrate formulae from third party taps into core, not vice versa. Exceptions are when something is actually in violation of a Homebrew policy.

**Comment by cmcarthur** [comment]
@ilovezfs yeah, we'd like to support installation of multiple versions, which we can more easily maintain from our own tap.

**Comment by ilovezfs** [comment]
In such cases we recommend maintaining the versioned formulae that wouldn't meet the https://github.com/Homebrew/brew/blob/master/docs/Versions.md#acceptable-versioned-formulae in a third-party tap. But that in itself isn't a reason to remove the main unversioned formula.

**Comment by cmcarthur** [comment]
@ilovezfs I'm the sole maintainer of this dbt formula, it's far more convenient for me to maintain a tap than (a) maintaining a single formula here, which only supports one version of dbt, or (b) maintain a tap AND the formula here, which is more work for me as a contributor.

Is your suggestion that I can't remove a formula that I maintain from homebrew-core?

**Comment by ilovezfs** [comment]
@cmcarthur moving it out of core will mean a worse user experience because it won't benefit from the automatic revision bumps when openssl and postgresql have changed library numbers. I'm surprised you'd want to make the users' installations more subject to random breakage when we make changes in core.

**Comment by cmcarthur** [comment]
The user experience of dbt is closely tied to our users having the ability to install a consistent version across their entire team. We understand the tradeoffs of using taps vs. versioned formulas vs. a single core formula. And we've decided to go the tap route, as it gives us the ability to distribute those versions most effectively.

I appreciate your concerns about the setup. At this point the benefits of having a tap outweigh the cons for us as the maintainers, as well as for our users.

**Comment by ilovezfs** [comment]
OK. As a note to anyone who may read this in the future and try to use it as a precedent for a similar pull request, I'm approving this because there have been only 72 installs in the last month according to the analytics.

@cmcarthur By the way, the `postgresql` dependency can probably be switched to the lighter weight `libpq` dependency, which is a formula we recently added.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@cmcarthur thanks for taking care of the formula while it was here :)

**Comment by cmcarthur** [comment]
thank you @ilovezfs !

**Pull request merged**
