### PR TITLE
openssl 1.0.2h

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by alex** [comment]
Tests failing because openssl.org is getting hammered so the binary can't be downloaded. Not sure if there's much to do besides retry?

**Comment by mikemcquaid** [comment]
@alex Have uploaded it to our mirror. Retrying.

**Comment by alex** [comment]
@mikemcquaid Thanks!

**Comment by DomT4** [comment]
You'll want to remove the patches here, I'd imagine.

**Comment by DomT4** [comment]
(Unless it wasn't fixed in the 1.0.2 branch, you'll need to check).

**Comment by alex** [comment]
@DomT4 good catch, removed (I'm almost positive they were upstreamed)

**Comment by DomT4** [comment]
Forgot about the timeout. Once the queue clears up a little I'll bump that and re-queue this, again.

**Comment by alex** [comment]
Thanks

**Comment by DomT4** [comment]
It's back in the queue, somewhere. Given it three hours this time, but realistically it should pass inside two comfortably.

**Comment by connorshea** [comment]
@DomT4 2 hours later, any progress?

**Comment by DomT4** [comment]
You took me a little too literally 😉. Build is finishing up, should be merged in the next 10/15 minutes hopefully.

**Comment by connorshea** [comment]
It's been exactly two hours, where is it!!!!1!!! 😉 

In seriousness, thank you for maintaining Homebrew, very useful for me :D

**Comment by DomT4** [comment]
Currently waiting for the [Yosemite](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1300/version=yosemite/console) build to finish up. It seems to have decided to take a nap. As much as I'd like to claim the CI obeys our whims more often than not it's the other way around 😄.

> In seriousness, thank you for maintaining Homebrew, very useful for me :D

Thanks! We're glad you find the project useful.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/7539b7d1b47b228a80988561ec13ff6b88958440. Thank you for your contribution to Homebrew @alex; we appreciate it! :smiley_cat:

**Pull request closed without merging**
