### PR TITLE
node 9.7.1

### PR DESCRIPTION
**Pull request by zulaica**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
`npm` resource can be updated to `5.7.1`
```
resource "npm" do
  url "https://registry.npmjs.org/npm/-/npm-5.7.1.tgz"
  sha256 "f65f1349c0f6f87f8d8bffcb1def622996f72062372a96f561bb5a12b90ba29e"
end
```

**Comment by DomT4** [comment]
@commitay FWIW, unless someone tweaked the general rule, Homebrew tends to track upstream on this barring some kind of security issue that mandates moving quicker than they can.

**Comment by commitay** [comment]
@DomT4 Yep, sorry. Misread the comment in the formula.

**Comment by zulaica** [comment]
@commitay No worries!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by commitay** [comment]
Thanks for your first contribution to Homebrew @zulaica!

**Pull request closed without merging**
