### PR TITLE
crystal-lang 0.24.2

### PR DESCRIPTION
**Pull request by msbit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@matiasgarciaisaia what is the status here?

Thanks for the PR @msbit but this is not marked as the latest release yet upstream.
https://github.com/crystal-lang/crystal/releases/latest

**Comment by msbit** [comment]
👌

**Comment by matiasgarciaisaia** [comment]
Current status: almost there, but not yet.

Maybe tomorrow/on Monday. I'll try to recall to update the formula 👍

Thanks @msbit for paying attention!

**Comment by matiasgarciaisaia** [comment]
Hey, @ilovezfs - [0.24.2 is officially out now](https://github.com/crystal-lang/crystal/releases/tag/0.24.2), so we're good to merge this PR. Would you reopen+merge, or should I send a new one?

**Comment by ilovezfs** [comment]
@msbit can you please update the bootstrap resource block too please? Thanks! @matiasgarciaisaia what url do we want for that

**Comment by matiasgarciaisaia** [comment]
Oh -- forgot about boot.

The new block should be:

```
  resource "boot" do
    url "https://github.com/crystal-lang/crystal/releases/download/v0.24.1/crystal-0.24.1-2-darwin-x86_64.tar.gz"
    version "0.23.1"
    sha256 "2be256462f4388cd3bb14b1378ef94d668ab9d870944454e828b4145155428a0"
  end
```

I might as well send a new PR if you can't edit this one, @ilovezfs - not sure about @msbit times now.

**Comment by ilovezfs** [comment]
@matiasgarciaisaia I can edit it :)

**Comment by ilovezfs** [comment]
Thanks @msbit and @matiasgarciaisaia! Shipped. 🔮

**Comment by msbit** [comment]
Thanks @ilovezfs and @matiasgarciaisaia!

**Pull request closed without merging**
