### PR TITLE
signal-cli 0.8.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Duplicate of #73002

Is this still a GitHub API issue, @dawidd6? Is your bump action passing the `--force` flag for some reason, @chenrui333?

**Comment by carlocab** [comment]
Is this still a GitHub API issue, @dawidd6? Is your bump action passing the `--force` flag for some reason, @chenrui333?

**Comment by dawidd6** [comment]
I believe so. It happens randomly for time to time.

**Comment by carlocab** [comment]
Weird; one would have thought the previous PR was old enough to be spotted. I think @chenrui333 might have too many formulae running on the bump action...

**Pull request closed without merging**
