### PR TITLE
pango 1.40.8

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Not sure where that comes from, but…

```
failed: brew linkage --test open-scene-graph
        Missing libraries:
  /usr/local/opt/ilmbase/lib/libHalf.12.dylib
  /usr/local/opt/ilmbase/lib/libIex-2_2.12.dylib
  /usr/local/opt/ilmbase/lib/libIlmThread-2_2.12.dylib
  /usr/local/opt/liblas/lib/liblas.3.dylib
  /usr/local/opt/liblas/lib/liblas_c.3.dylib
  /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib
```

**Comment by ilovezfs** [comment]
the open-scene-graph revision is not needed. it's already going in the homebrew testing job.

**Comment by tschoonj** [comment]
ok, thanks, removed the commit

**Comment by RandomDSdevel** [comment]
Actually, Pango release 1.40.8 has already been superseded by v1.40.9 upstream due to unexamined circumstances, strange as that is.  I can't file a PR to propagate that change down here into Homebrew Core right now, so anyone feel free to beat me to it if you want.

**Comment by ilovezfs** [comment]
[1.40.9](https://github.com/Homebrew/homebrew-core/pull/16565)

**Comment by RandomDSdevel** [comment]
Thanks, @ilovezfs, and I'll try to be more proactive about filing PRs to resolve situations like this myself when I notice them in the future.

**Pull request closed without merging**
