### PR TITLE
igraph 0.9.0

### PR DESCRIPTION
**Pull request by ntamas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> ./configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/igraph/0.9.0 --with-external-blas --with-external-lapack --with-external-glpk --enable-tls
Failed to execute: ./configure
```
Looks like they switched their build system to CMake.

**Comment by ntamas** [comment]
Whoops, indeed. I'll fix the PR soon.

**Comment by ntamas** [comment]
This version of the formula now uses CMake.

Additional changes worth mentioning:

* `igraph_diameter` now uses `igraph_real_t` as its output, not `igraph_integer_t`, so the test case had to be adjusted.
* The CMake build system autodetects BLAS, LAPACK, GLPK and GMP so there is no need to specify that we want to link to the external copies of these libraries instead of the vendored ones.
* igraph's CMake build file builds everything in release mode by default.

**Review by carlocab — APPROVED** [review]
Thanks, @ntamas.

**Pull request closed without merging**
