### PR TITLE
Fix openjdk8 hashsums

### PR DESCRIPTION
**Pull request by raspla**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rook59** [comment]
Not sure why OpenJDK uploaded a new archive for the same version. How do we proceed here?
```
  * stable sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

**Comment by SMillerDev** [comment]
Contact the OpenJDK project and ask if it was intentional

**Comment by rook59** [comment]
I contacted them via #openjdk OFTC IRC, waiting for a reply now

**Comment by jonchang** [comment]
> I contacted them via #openjdk OFTC IRC, waiting for a reply now

Thanks, keep us posted.

**Comment by rook59** [comment]
No reply so far, sent an email to jdk8u-dev@openjdk.java.net

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/64845 should fix this as well, closing this.

But please let us know if they ever respond.

**Comment by rook59** [comment]
Reply:
```
That's not an upload, but an auto-generated Mercurial archive (and thus
subject to change).

The source tarballs for the releases are those listed (with checksums) in
the release announcements:

8u272: https://bitly.com/openjdk8u272
8u275: https://bitly.com/openjdk8u275
```

**Pull request closed without merging**
