### PR TITLE
add libressl and pcre2 as dependencies

### PR DESCRIPTION
**Pull request by Theodus**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by dunn** [comment]
Are these required, or optional?

**Comment by Theodus** [comment]
They are required by the new version of the compiler.

**Comment by DomT4** [comment]
When you say "new" do you mean the current release or the current `HEAD` upstream?

**Comment by SeanTAllen** [comment]
@DomT4 they are required by the current 0.2.1 version as well as HEAD upstream.

**Comment by DomT4** [comment]
Okay. Can you add a `revision 1` line under the `sha256` then if they should have been added previously? Thanks.

**Pull request closed without merging**
