### PR TITLE
xmake: 2.5.9

### PR DESCRIPTION
**Pull request by waruqi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> brew audit xmake --online --git --skip-style
==> FAILED
xmake:
  * Binaries built for a non-native architecture were installed into xmake's prefix.
    The offending files are:
      /opt/homebrew/Cellar/xmake/2.5.9/share/xmake/templates/nim/console/project/src/main	(x86_64)
Error: 1 problem in 1 formula detected
```

**Comment by waruqi** [comment]
I remove this file on master, but I cannot update tar file, because it has been released.

**Comment by carlocab** [comment]
> I remove this file on master, but I cannot update tar file, because it has been released.

That's fine then. It should be fixed in an upcoming release.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks!

**Comment by waruqi** [comment]
thanks

**Pull request closed without merging**
