### PR TITLE
fastfec 0.1.9

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Error: Failed changing install name in /opt/homebrew/Cellar/fastfec/0.1.9/bin/fastfec
    from /opt/homebrew/opt/pcre/lib/libpcre.1.dylib
      to @@HOMEBREW_PREFIX@@/opt/pcre/lib/libpcre.1.dylib
```

**Comment by SMillerDev** [comment]
```
  ==> zig build -Dvendored-pcre=false --search-prefix /home/linuxbrew/.linuxbrew/opt/curl
  error: ld.lld: relocation R_X86_64_32S cannot be used against local symbol; recompile with -fPIC
      note: defined in /home/linuxbrew/.linuxbrew/Cellar/pcre/8.45/lib/libpcre.a(libpcre_la-pcre_compile.o)
      note: referenced by pcre_compile.c
      note:               libpcre_la-pcre_compile.o:(find_fixedlength) in archive 
```

**Comment by carlocab** [comment]
Oops, didn't see that you had worked on this already. Merged in https://github.com/Homebrew/homebrew-core/pull/123946.

**Comment by iMichka** [comment]
Thanks! No issue :)

**Pull request closed without merging**
