### PR TITLE
apache-arrow and friends: use unversioned `protobuf`, `grpc`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- apache-arrow: use unversioned `grpc` and `protobuf`
- dvc: use unversioned `protobuf`

### CODE REVIEW

**Comment by ORIOLESFan02** [comment]
For `protobuf`, a way I figured out how to get it working (it took me over three hours to find a solution that worked for me) is to 

1. Download the latest version of protobuf (https://github.com/protocolbuffers/protobuf/releases/latest) for your machine [I chose v23.3 {as of the time of making this comment} osx x86_64, but make sure to choose the correct version for your machine.
2. Extract the file(s) and locate protoc using the command `which protoc`. Save that location for later.
2a. During the time this has been written, the version i was previously on was 21.12 which was located in `/usr/local/Cellar/protobuf` (Case Sensitive)
3. Either using terminal, or Finder (assuming you're on MacOS), create a folder with the version that is available (for me, it's 23.3). Using Terminal, you can create the file by doing `mkdir <version.number>` (example: `mkdir 23.3`) in `/usr/local/Cellar/protobuf/`, or y'know, you can also use Finder using a couple clicks and your keyboard to accomplish the same task. Whichever way you prefer.
4.  Go back to the unzipped protobuf/protoc folder and copy everything to the new folder you created in `/usr/local/Cellar/protobuf/`
4a. You are now going to need to go to `/usr/local/bin` as we're going to remove `protoc` and `protoc-3.<version.number>.0` (example old file: `protoc-3.21.12.0`)
5. You're going to have to create a Symbolic Link,
5a. How I created the Symbolic Link was by doing this while in `/usr/local/Cellar/protobuf/<version.number>` (ex: ...`/protobuf/23.3`): `ln -s "$PWD/./protoc-3.<version.number>.0" protoc` (example: `ln -s "$PWD/./protoc-3.23.3.0" protoc`)
5b. ***COPY*** (meaning leave the symbolic link in `/usr/local/Cellar/protobuf/<version.number>/`) `protoc` into `/usr/local/bin/` (I would personally recommend putting the previous version of the protoc symbolic link from `/usr/local/bin/` to the trash, but don't remove it in case you need it again)
5c. Create another symbolic link, this one for `protoc-3.<version.number>.0`. Create it in `/usr/local/Cellar/protobuf/<version.number>`, but how I did it was by doing `ln -s "$PWD/./protoc-3.<version.number>.0" protoc-3.<version.number>.`  [example: ...Create it in `/usr/local/Cellar/protobuf/23.3` ...was by doing `ln -s "$PWD/./protoc-3.23.3.0" protoc-3.23.3.`] (omitting the '0' at the end, or it wouldn't create the symbolic link.
5d. ***MOVE*** (NOT copy) `protoc-3.<version.number>.` to `/usr/local/bin/` and then ***RENAME*** `protoc-3.<version.number>.` to `protoc-3.<version.number>.0` (example: rename `protoc-3.23.3.` to `protoc-3.23.3.0`)
5e. After all of that, remove the previous `protoc-3-<oldversion.number>.0`  [example: `protoc-3-21.12.0` (by that, i mean put it in the trash for right now in case you need it again)

6. In the Terminal, I'd recommend opening another instance, just to be sure in case something goes wrong.
6a. While in that new Terminal instance (assuming you're in your user directory [if not, just type `cd`]), type `protoc --version`
6b. If `protoc --version` shows "`libprotoc <latestversion.number>`" (Example: "`libprotoc 23.3`", then you have successfully installed protobuf.

7. I would now recommend running `brew update` and `brew upgrade` and you should no longer see anything about `protobuf` needing to be built and/or updated or whatever it does.

I am aware that this is pretty long, but this is the way that I solved it. I'm very positive that this could be condensed down A LOT more, but again, this is the way that I did it, and this is the way that it worked for me.

If anyone wants to modify the way I did it, and possibly make it easier to do and/or understand, please, be my guest.

I hope this helps in some way, shape, or form.

**Comment by scpeters** [comment]
I've worked up a patch in https://github.com/protobuf-c/protobuf-c/pull/556 that lets `protobuf-c` compile, though I haven't tried running it at all

**Comment by scpeters** [comment]
> I've worked up a patch in [protobuf-c/protobuf-c#556](https://github.com/protobuf-c/protobuf-c/pull/556) that lets `protobuf-c` compile locally on my machine, though I haven't tried running it at all (aside from `brew test protobuf-c`, which passes)
> 
> EDIT: built with `brew install --HEAD protobuf-c` with [scpeters@be56ca6](https://github.com/scpeters/homebrew-core/commit/be56ca6be2ee50234f1b0f0d93184d093d14220a)

@carlocab I think my changes in https://github.com/scpeters/homebrew-core/commit/be56ca6be2ee50234f1b0f0d93184d093d14220a for testing with `--HEAD` were a bit messy, but I'd be happy to clean it up if you have any recommendations. The patch works for me locally, but I haven't gotten any feedback on my upstream pull request

**Comment by carlocab** [comment]
Thanks for working on that! Apologies for the delayed response; I've been finishing off #134251.

Let's give your patch a try.

**Comment by carlocab** [comment]
@scpeters I'm afraid we might still be blocked on `netdata` 🥲 The good news is that I _think_ that should be the last one to fix.

**Comment by carlocab** [comment]
It looks like `netdata` have defined a really generic macro
```c
#define info(args...)
```
and this is messing with the `abseil` headers.

**Comment by carlocab** [comment]
I have a gigantic patch that enables me to build `netdata` locally against this PR. https://github.com/netdata/netdata/pull/15266

**Review by p-linnane — APPROVED** [review]

**Comment by scpeters** [comment]
thanks for fixing this!

**Pull request merged**
