### PR TITLE
node 19.9.0

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by moonfruit** [comment]
Why not use `npm` 9.6.4? This is the latest version. @ZhongRuoyu

**Comment by ZhongRuoyu** [comment]
> Why not use `npm` 9.6.4? This is the latest version.

Because node 19.9.0 [ships npm 9.6.3](https://nodejs.org/en/download/current). Patch releases are accepted only if they are important.

**Comment by moonfruit** [comment]
Oh, sorry for the forced push.

**Comment by chenrui333** [comment]
only `llnode` failed on ventura builds, we can follow up on it.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
regression tested out fine for `llnode` in my local (`ventura arm`) against `node 19.9.0`

**Pull request merged**
