### PR TITLE
gitui 0.9.1

### PR DESCRIPTION
**Pull request by extrawurst**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by dawidd6** [comment]
@extrawurst could you please look at the test?

**Comment by extrawurst** [comment]
@vladimyr sorry to bother you again. I need your help getting the test to work again. since the last release in the log view you cannot press arrow-right anymore, you first have to press enter. I thought e6740ed would do that... 😢

**Comment by vladimyr** [comment]
This is an excellent example of why we should stop changing stuff and introducing new features 🤣

I'm away from my beloved MacBook atm but I'll take a look tomorrow. In the meantime please deprecate all keybindings and introduce proper vim like command input system so we can sleep safely while `:InspectCommit` continues to operate flawlessly 🤣

**Comment by extrawurst** [comment]
It was a bug that I have fixed.
Thanks for your support ❤️

**Comment by extrawurst** [comment]
@vladimyr any luck?

**Comment by SMillerDev** [comment]
Does it fail to start off you're not in a git repo? Because in that case we should just test for that error. The current test is too prone to failure and too difficult to maintain, as is demonstrated here.

**Comment by vladimyr** [comment]
> Does it fail to start off you're not in a git repo?

If you run `gitui` outside of git repo you'll get the following error on stderr:
```
❯ gitui
invalid path
please run gitui inside of a non-bare git repository
```

> The current test is too prone to failure and too difficult to maintain, as is demonstrated here.

Well, it failed because @extrawurst altered required keystroke sequence used to inspect commit but it is not that hard to maintain. In fact in order to make it green simple change is required:
```diff
diff --git a/Formula/gitui.rb b/Formula/gitui.rb
index 9e4ee1b5b8..b3759f0350 100644
--- a/Formula/gitui.rb
+++ b/Formula/gitui.rb
@@ -32,7 +32,7 @@ class Gitui < Formula
     input.puts "2"
     sleep 1
     # inspect commit (return + right arrow key)
-    input.puts "\n"
+    input.puts "\r"
     sleep 1
     input.puts "\e[C"
     sleep 1

```

**Comment by extrawurst** [comment]
@vladimyr changed *newline* to *return* - should work like this now?

**Comment by vladimyr** [comment]
@extrawurst I was literally leaving commit suggestion in place and noticed that you already did it. So fast ⚡  💯

**Comment by vladimyr** [comment]
Yes, it works with a carriage return, tested locally.

**Comment by SMillerDev** [comment]
> If you run gitui outside of git repo you'll get the following error on stderr

That seems like a much easier test to maintain and it'll also check if the program is behaving as expected without getting into specifics.

**Comment by extrawurst** [comment]
@dawidd6 tests pass now 🥳

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
