### PR TITLE
solr: fix download and bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Trying to fix:
https://issues.apache.org/jira/browse/SOLR-15558
https://github.com/apache/solr/pull/250

**Comment by iMichka** [comment]
The patch fixes the issue on Linux.
I am a little bit annoyed that the patch has not been reviewed yet. I wrote a message to upstream in the PR to see if we can move things forward. Let's wait a little bit for their response.

**Comment by SMillerDev** [comment]
Can't we use the commit directly?

**Comment by iMichka** [comment]
No. The initial commit fixed its, but they made one more change which is breaking our test. 
They added `exit 1` so now the return code is different in docker: https://github.com/apache/solr/pull/250/commits/a62fcab470f56b8c018e72c0a8fb6f5d0034f77d#diff-49c29c8f653341f48008c38f5f2cf970fa430cdca29181c819d7bdcfcc722980R895

Don't know what is the best strategy here. Upstream discussed it, we could ask them to revert that bit.

**Comment by SMillerDev** [comment]
Can't we just expect a different return code on Linux?

**Comment by iMichka** [comment]
The patch is only a part of the full patch, because upstream made a changelog.txt change which can't be applied. I extracted only the necessary part.

**Comment by Bo98** [comment]
What's wrong with the original download link? Works fine for me (`brew fetch -s solr`).

**Review by SMillerDev — APPROVED** [review]

**Comment by iMichka** [comment]
The link is fine but the patch does not apply as-is. I extracted only the code part.

**Pull request closed without merging**
