### PR TITLE
node 6.9.1

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by diogoazevedos** [comment]
@ilovezfs why the commit failed? How can I fix?

**Comment by febLey** [comment]
I think there's a problem with lines 9 - 11, the hashes need to be updated, but i'm not sure.

**Comment by ilovezfs** [comment]
it didn't actually fail ... just the mechanism that reports back success or failure from test-bot to GitHub choked

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
:green_apple:

**Comment by ilovezfs** [comment]
@diogoazevedos Thanks for your contribution to Homebrew! :tada:

**Pull request closed without merging**
