### PR TITLE
percona-toolkit 3.0.1

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Should I run CI again or do you remember what the failure was?

**Comment by nijikon** [comment]
https://bugs.launchpad.net/percona-toolkit/+bug/1653331

**Comment by nijikon** [comment]
@percona-csalguero

**Comment by nijikon** [comment]
https://gist.github.com/nijikon/8c3376cd3153ef556e786030c0a7d4e0

**Comment by nijikon** [comment]
Upstream does not care to fix `pt-summary` on macOS. Switching test to bogus one, cause other commands can still be used.

**Comment by nijikon** [comment]
Killing this for now as we tested with @ilovezfs and there is couple of more things broken here.

**Pull request closed without merging**
