### PR TITLE
znapzend: Add HEAD option to the formula

### PR DESCRIPTION
**Pull request by JMoVS**
Signed-off-by: Justin Scholz <git@justinscholz.de>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @JMoVS for the suggestion. Given there is very little usage for this formula, adding HEAD is probably not a good idea.

**Comment by JMoVS** [comment]
Sorry @fxcoudert , I don't get your point. What causal link do you see between little usage and HEAD being not a good idea?

**Comment by fxcoudert** [comment]
I'm reopening, so other maintainers may see the PR and voice their opinion.

**Comment by JMoVS** [comment]
Thank you @fxcoudert for the explanation. I see your point but my intuitive guess (you have access to hard data) would be that with such low numbers, it wouldn't hurt because out of these 7 people, even if it's 1 % of those installs, the average time until 1 person uses HEAD is long.

If I remember correctly, I got znapzend merged as a formula with the help of ilovezfs_, I'm personally closely following the znapzend repo and would probably run into new issues myself and try to fix them as well.

**Comment by fxcoudert** [comment]
cc @Homebrew/maintainers

**Comment by vitorgalvao** [comment]
> with such low numbers, it wouldn't hurt because out of these 7 people, even if it's 1 % of those installs, the average time until 1 person uses HEAD is long.

> I'm personally closely following the znapzend repo and would probably run into new issues myself and try to fix them as well.

I find those to be good arguments, but weirdly they’re good to justify both inclusion or refusal.

My opinion should not be given too much weight here, but if this were in HBC I’d accept it since @JMoVS is offering to take care of problems. But I’d also be ready to remove it again if at the first signs of it being too much trouble to maintain.

**Comment by JMoVS** [comment]
sounds good, I won't mind it getting removed if it turns out it produces too much maintenance. Then it at least had a run at it. ;-)

**Comment by MikeMcQuaid** [comment]
> We add head specs when a user wants to use them (see #6540 (comment)) provided head isn't overly complicated or troublesome. In general, head specs should not be reflexively added to new formulae.

Agreed 👍

**Pull request merged**
