### PR TITLE
gtk-mac-integration: Apply latest patches to fix a bug and add support for --HEAD

### PR DESCRIPTION
**Pull request by maoe**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Currently the released versions have [a bug](https://github.com/jralls/gtk-mac-integration/pull/11) that crashes an application. Installing HEAD fixes the issue.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Instead of adding head, it would be better to backport the patch to stable so that everyone benefits from the fix.

**Comment by maoe** [comment]
Ah that sounds like a good idea. Is the patching process documented somewhere?

**Comment by ilovezfs** [comment]
Here's a good example https://github.com/Homebrew/homebrew-core/pull/26812

**Comment by jayapsrivastava** [comment]
Hi Maoe,

I am also getting this error and would like to know how to access the fix or it is already part of the build?
This way I can test the same.

Thanks,

PS: Have recently started using OSX as part of my project, kindly cooperate with me.

**Comment by maoe** [comment]
@jayapsrivastava you can `brew edit gtk-mac-integration` then make the same change as this PR. Then uninstall it and reinstall it with —HEAD.

I’m meaning to update the PR but haven’t gotten around to it.

**Comment by maoe** [comment]
@ilovezfs I backported the patches to fix the bug and confirmed that `brew install -s gtk-mac-integration` fixed it.

**Comment by maoe** [comment]
Fixed the CI errors.

**Comment by ksallberg** [comment]
I tried applying the diff that this PR shows, and then do as below. Did I detect something weird or did I do something wrong? Not familiar with homebrew, just trying to install threadscope

`
kristiansallberg@Kristians-Mini:~/Documents/purestyle$ brew install gtk-mac-integration --HEAD
==> Cloning https://github.com/jralls/gtk-mac-integration.git
Updating /Users/kristiansallberg/Library/Caches/Homebrew/gtk-mac-integration--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 6d7b278 Merge Daniel Hodan's 'fix-cgbitmapinfo-typo' into master.
==> Downloading https://github.com/jralls/gtk-mac-integration/pull/11.patch?full_index=1
Already downloaded: /Users/kristiansallberg/Library/Caches/Homebrew/gtk-mac-integration--patch-4523207ea652b9048d01a58c05369c871def4e187db267ab7bad85ae1e102c31.patch
==> Downloading https://github.com/jralls/gtk-mac-integration/pull/13.patch?full_index=1
Already downloaded: /Users/kristiansallberg/Library/Caches/Homebrew/gtk-mac-integration--patch-b0ecfb9a3c5cd9651584b33191b69915627cc9e09e78fb4623fcaa64915ee13d.patch
==> Patching
==> Applying 11.patch
patching file src/gtk-mac-image-utils.c
Hunk #1 FAILED at 30.
Hunk #2 FAILED at 48.
2 out of 2 hunks FAILED -- saving rejects to file src/gtk-mac-image-utils.c.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/gtk-mac-integration--patch-20180731-9788-isadnu/11.patch` exited with 1.

`

**Comment by ksallberg** [comment]
Well, I managed to install "gtk-mac-integration 2.0.8_2" so I can now run ThreadScope

**Comment by maoe** [comment]
@ksallberg I see. I guess the patches need to be moved under `stable do ... end`. I'll fix it later.

**Comment by maoe** [comment]
Fixed

**Comment by maoe** [comment]
Fixed brew audit errors.

**Comment by ksallberg** [comment]
@maoe I can confirm that `--HEAD gtk-mac-integration` works for me now

**Comment by DomT4** [comment]
@tschoonj Mind taking a look at this?

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Review by tschoonj — APPROVED** [review]
Looks legit to me

**Comment by fxcoudert** [comment]
Thanks @maoe for the pull request!

**Pull request closed without merging**
