### PR TITLE
mosh: Rename from mobile-shell

### PR DESCRIPTION
**Pull request by daylightbrightledlight**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Renaming `mobile-shell` to `mosh` to be consistent with actual package name.
See: https://mosh.org/

### CODE REVIEW

**Comment by daylightbrightledlight** [comment]
The cask `mosh` is actually a duplicate of this formula. Not sure why it's there.

**Comment by ilovezfs** [comment]
There's already a mosh alias so I don't think this is necessary but thanks for the PR nonetheless.

**Comment by ilovezfs** [comment]
Changed my mind. There's enough references in the upstream project to `mosh` not `mobile-shell` that we might as well rename it.

**Comment by DomT4** [comment]
What's with the removal of `revision 1` here?

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @daylightbrightledlight! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
