### PR TITLE
datomic 0.9.5372

### PR DESCRIPTION
**Pull request by sdegutis**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by UniqMartin** [comment]
Builds are failing, apparently because the version of the bundled Clojure version has changed and this is being used in the formula test, so that needs to be updated. (See e.g. [this build log](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2577/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_datomic/) for details.)

**Comment by sdegutis** [comment]
@UniqMartin Thanks. Just pushed an edited commit that fixes it.

**Comment by UniqMartin** [comment]
Merged. Thank you for this contribution to Homebrew, @sdegutis! :tada:

For future reference: The preferred commit subject and PR title for a simple version bump like this is `datomic 0.9.5372` as detailed in our linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md). Thanks!

**Comment by sdegutis** [comment]
@UniqMartin Thanks. Noted.

**Pull request merged**
