### PR TITLE
texlive 2022

### PR DESCRIPTION
**Pull request by max-ae**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR is a draft to update TeXLive to the recently released 2022 version.

I had to change the source URL as the SVN mirror on GitHub did not host a tag for the 2022 release revision r62882, only a branch (https://github.com/TeX-Live/texlive-source/tree/tags/texlive-2022.0).
If someone finds a different mirror or has a preferred way of downloading the source from the previous mirror, let me know.

**TODOs**

- [x] switch source URL?
- [x] update livecheck?
~- [ ] use `pygments` formula as dependency?~

Pinging @danielnachun since he authored a large chunk of the initial formula 😄

### CODE REVIEW

**Comment by danielnachun** [comment]
The current failure is:
```
clang -DHAVE_CONFIG_H -I. -I./w2c  -I./mfluadir/potrace    -g -O2 -c -o mfluadir/potrace/libmfluapotrace_a-luafunc.o `test -f 'mfluadir/potrace/luafunc.c' || echo './'`mfluadir/potrace/luafunc.c
In file included from mfluadir/potrace/decompose.c:6:
./w2c/config.h:23:10: fatal error: 'kpathsea/config.h' file not found
#include <kpathsea/config.h>
```

I believe this is occurring because `mfluadir/potrace` and `w2c` both contain `config.h` files, and the preprocessor is using the one from `w2c` when it should be using the one from `mfluadir/potrace`.  This happens because the flag ordering should probably be `-l./mfluadir/potrace -I./w2c` instead of `-I./w2c -I./mfluadir/potrace`. I don't know these flags are ordered this way but we can try to fix this and notify upstream if that is the problem.

**Comment by max-ae** [comment]
I tried to look into this, but could not figure out a way to fix the issue, at least not in the limited amount of time I spent.
Maybe someone else can take a look?

However, it seems like MacPorts did not run into this issue when upgrading to texlive 2022, as far as I can tell (https://github.com/macports/macports-ports/commit/9ae2bae895d32a97ae2fed2c05cffbb7b3ea53f0).

**Comment by danielnachun** [comment]
Thanks for looking into this so far.  I can see the potential source of the problem in the `Makefile.in` for `web2c`.  However before resorting to patching, I'm wondering if running `auroreconf --force --verbose --install` before `./configure` would help in this situation.

**Comment by danielnachun** [comment]
On a related note, I see that MacPorts uses a different source for upstream packages: https://www.ambulatoryclam.net/texlive/.  @Homebrew/core I wish I had known about this resource when I worked on the original formula because they already split up the massive `texlive-texmf` into set of much smaller packages.  Looking at the sizes, I think we could consider adding all the resources except `texlive-fonts-extra`, `texlive-latex-extra`, `texlive-pstricks`, and `texlive-pictures` (the 4 largest ones), and make each of them their own formula.

The disadvantages of doing this are that it will make the formula even longer from needing to add more resources (we could make this a little better by putting all the non-English `texlive-lang` resources in a separate `texlive-lang-extra` formula, since there are so many of them).  We'd also have to make `TEXMFDIR` be `HOMEBREW_PREFIX/share` so that `texlive` could find the resources from the other formula.  This would mean that `texlive` would break if `brew unlink` were run, and neither `texlive` nor any of the other related formula could ever be keg-only.

Making these changes would be a lot of work but could be worth it in the long run because it could make `texlive` a lot smaller.  Do we think this is worth the effort?  Should we try to build this formula as is and tackle the splitting later?

**Comment by SMillerDev** [comment]
> Making these changes would be a lot of work but could be worth it in the long run because it could make texlive a lot smaller. Do we think this is worth the effort? Should we try to build this formula as is and tackle the splitting later?

For me, yes on both counts. Texlive as it currently is is just too big to be tested by CI essentially and this will help. I don't think updating it needs to wait for that though.

**Comment by MikeMcQuaid** [comment]
> Making these changes would be a lot of work but could be worth it in the long run because it could make `texlive` a lot smaller. Do we think this is worth the effort?

Do we see these other resource-to-formulas being depended on by any other formulae or being useful standalone? If not: let's not split.

> Should we try to build this formula as is and tackle the splitting later?

Yes, split later, if we do so.

**Comment by SMillerDev** [comment]
> Do we see these other resource-to-formulas being depended on by any other formulae or being useful standalone? If not: let's not split.

It's mostly that in the current situation the bottles are unreasonably big which causes issues with PRs like the python updates

**Comment by danielnachun** [comment]
Everything is passing CI here now.  I'm going to send email out the TeXLive mailing list explaining this issue and see what they say, and will link to that in a comment.  Now that is building we can address the other issues brought up by @maxae:
>  switch source URL?

This is probably not a bad idea, as I think the upstream you linked to is supposed to be "final" version of the TeXLive native code for a given annual release.  It also seems like that URL might be a more reliable livecheck.  I'm curious to hear other maintainer's thoughts on this.

>  update livecheck?

If we switch to the alternate upstream, then we'd want to update the livecheck as well.

>  use pygments formula as dependency?

That's probably fine though we have to make sure the Python scripts can find the libraries for the `pygments` formula.  @maxae feel free to test this locally now that the build should be working.  

I do think we should still consider ways to split this up, but we should focus for now on addressing these above issues.  We might even consider publishing the bottles now because we are already quite behind, and addressing the remaining issues in a follow up PR.

**Comment by max-ae** [comment]
Great that everything is building now! 🎉

However you would like to proceed is fine with me, I'll either open a new PR for the livecheck update and `pygments` changes or push to this one, depending on your decision.

One question regarding the livecheck, though: which version do we want to use? 
The previous version from the GitHub source used the svn tag, the new source URL yields the autodetected version 20220321. Do we want to use this as the version going forward or instead use the year only (2022)? The former may make the livecheck a bit more complicated, but the decision is up to you.

**Comment by SMillerDev** [comment]
I have no doubt brew now detects the version as `20220321` so that should also be the version that the livecheck returns.

**Comment by danielnachun** [comment]
> However you would like to proceed is fine with me, I'll either open a new PR for the livecheck update and pygments changes or push to this one, depending on your decision.

We can fix everything up in this PR, as the build takes a few hours but isn't unreasonably long.  
 
> I have no doubt brew now detects the version as `20220321` so that should also be the version that the livecheck returns.

Yeah it looks like this alternate upstream uses a more consistent tag name than the GitHub tags, which were more variable.  @samford could you suggest the right livecheck strategy here that now we've got a different upstream?  Feel free to push a commit if that's the easiest way to make the change.

**Comment by samford** [comment]
I couldn't find any version information on the homepage site (www.tug.org), so I opted to check the directory listing where the `stable` tarball is found. Unfortunately, since the tarballs are kept in separate year directories (e.g., `2022/`), we have to make two requests (like the `bash` `livecheck` block), first to identify the newest year directory and then to check the related directory listing page to match the version from the tarball filename. I'm not overly fond of checks that require multiple requests but they're necessary in rare cases like this.

**Comment by danielnachun** [comment]
> I couldn't find any version information on the homepage site ([www.tug.org](http://www.tug.org)), so I opted to check the directory listing where the `stable` tarball is found. Unfortunately, since the tarballs are kept in separate year directories (e.g., `2022/`), we have to make two requests (like the `bash` `livecheck` block), first to identify the newest year directory and then to check the related directory listing page to match the version from the tarball filename. I'm not overly fond of checks that require multiple requests but they're necessary in rare cases like this.

That's definitely quite a hefty livecheck block.  I didn't realize they were putting the tarballs in separate directories for each year but I guess it makes sense given that this is an annual release.  However I think this is worth the extra code given that this upstream seems to use very consistent tag names, whereas the GitHub upstream explicitly said they do not have a consistent naming scheme which seems to be a bigger challenge in the long term.

**Comment by danielnachun** [comment]
I reported the issue we had to patch to the TeXLive mailing list: https://www.tug.org/pipermail/tex-live/2022-May/048183.html.  The upstream response was that the change in their commit which added `config.h` to `mfluadir/potrace` was probably a mistake as that file is supposed be generated by `configure`, and they are unsure why this hasn't caused failures elsewhere.  I will follow up if they ask me to help with any testing or patching, but I think for now we should use our workaround until they've sorted out the best solution.  I'm going to push a change to add the link in a comment above the `inreplace`, but for now I think this is all we can really do on our end.

**Comment by max-ae** [comment]
Thanks @samford for the livecheck!

I looked into using the `pygments` formula instead of a resource locally, but it looks like this requires further changes to the `pygments` formula to not install into its own virtualenv, but rather behave comparable to the `six` and `numpy` formula, for example.
I would argue that this should be addressed in a followup (if at all), meaning that this PR should be good to go once the reference to the mailing list submission is added.

**Comment by danielnachun** [comment]
> Thanks @samford for the livecheck!
> 
> I looked into using the `pygments` formula instead of a resource locally, but it looks like this requires further changes to the `pygments` formula to not install into its own virtualenv, but rather behave comparable to the `six` and `numpy` formula, for example. I would argue that this should be addressed in a followup (if at all), meaning that this PR should be good to go once the reference to the mailing list submission is added.

Thanks for looking into this.  I agree with you that if `pygments` requires changes to the formula to be used like `six` or `numpy`, that needs to be handled separately from this.  I will push the last change to add the link to the TeXLive mailing list, and we can start the final CI run to build the bottles we will publish.

**Comment by max-ae** [comment]
Sounds good!
But I fear the livecheck commit got dropped during your force push 😅

**Comment by danielnachun** [comment]
Yes, it did. Let me see how to fix that.

**Comment by max-ae** [comment]
I still have it locally, give me a second

**Comment by danielnachun** [comment]
Whew!  Nice save!  Now we just need wait for a free CI-long-timeout label and we should be ready to go.

**Review by danielnachun — DISMISSED** [review]
Everything is read to go so I am publishing the bottles now.

**Comment by Bo98** [comment]
That was me cancelling that duplicate one

**Pull request closed without merging**
