### PR TITLE
systemd: build man pages

### PR DESCRIPTION
**Pull request by jnooree**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Build man pages for systemd.

### Rationale

Once systemd is installed via linuxbrew, the executables provided by the formula shadows the system-provided ones. In most systems the two would very likely to have different versions, and often behave differently.

Building man pages with the formula gives the users reference to those discrepancies (at least).

### CODE REVIEW

**Comment by jnooree** [comment]
Oops, forgot to update revision... Should I trigger the CI again just for the revision update?

**Comment by SMillerDev** [comment]
There shouldn't be a revision since that forces a reinstall, and I don't think we should build the manpages either. We generally don't since docs are almost always available online.

**Comment by jnooree** [comment]
That's correct, but `man systemctl` is much faster than googling for the man page of the specific version installed by homebrew.

**Comment by jnooree** [comment]
@SMillerDev If the man page build option will not likely be turned on for the systmed formula, will be a new formula (say systmed-man) accepted?

**Comment by SMillerDev** [comment]
No, while we generally don't install documentation we never package documentation separately.

**Comment by carlocab** [comment]
We don't normally go out of our way to build manpages, but the reason for doing it here sounds convincing to me, so I'd be fine with doing this (especially since this formula is Linux-only anyway).

I'm more unsure about the extra resources required for it, though: why are they needed? Is this the only way to support building the manpages?

**Comment by jnooree** [comment]
> I'm more unsure about the extra resources required for it, though: why are they needed? Is this the only way to support building the manpages?

Yes, without the patches (inreplace ~) to the man page templates, the external resources are being downloaded during the man page build process, effectively violating the homebrew sandboxing policy. The resource blocks and patches are workaround to make things work.

**Comment by jnooree** [comment]
For those who might be concerned about broken builds due to upstream version updates of the resources:

- [docbook-xsl](https://sourceforge.net/projects/docbook/files/docbook-xsl) have never been updated since 2015. 
- Two `oasis-open` dependencies are more related to the xml schema; seems rarely updated. For one example, the line in `systemctl.xml` was last updated [4 years ago](https://github.com/systemd/systemd/blame/main/man/systemctl.xml#L3).

**Review by singingwolfboy — APPROVED** [review]
Seems like a good change to me.

**Comment by jnooree** [comment]
Should I rebase or do something else? Seems automerge has been stuck at merge conflict.

**Review by chenrui333 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @jnooree!

**Pull request merged**
