### PR TITLE
hyperscan 4.2.0

### PR DESCRIPTION
**Pull request by flier**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ x Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by flier** [comment]
build failed at OSX mavericks with clang 6.0, submitted issue to upstream

https://github.com/01org/hyperscan/issues/27

**Comment by tdsmith** [comment]
Please let us know if there's progress on that ticket.

**Comment by ilovezfs** [comment]
@flier I think you can apply https://github.com/01org/hyperscan/commit/e9cfbae68f69b06bb4fdcd2abd7c1ee5afec0262 as a patch rather than waiting for a new release as you were saying here https://github.com/01org/hyperscan/issues/27#issuecomment-231261563

**Comment by flier** [comment]
seems the patch passed all checks

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Thanks! Merged as cb25ddfcac80828bc241ca46b0732963ea334615, 6b97a355e5b8a6b0218bf5b20307c75dcb698474, and 93d65148cebe80eb292e0c94e01e840f4261c75a.

**Pull request closed without merging**
