### PR TITLE
coturn 4.5.2

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Why close the PR?

**Comment by chenrui333** [comment]
```
==> brew audit coturn --online --git --skip-style
==> FAILED
coturn:
  * The plist first ProgramArguments value does not exist:
      /usr/local/opt/coturn/bin/turnserver
Error: 1 problem in 1 formula detected
```

**Comment by carlocab** [comment]
Didn't have the patience to fix at the moment; was planning to revisit it later. 😅 

You can reopen it if you want to add commits that will fix it

**Comment by chenrui333** [comment]
totally understandable.

At least you should comment in here about the issue and it would be good for future revisits.  😄

**Comment by carlocab** [comment]
Same errors...

**Comment by chenrui333** [comment]
I will debug a bit later.

**Comment by SeekingMeaning** [comment]
`configure` error:

```
ERROR: Libevent2 development libraries are not installed properly in required location.
ERROR: may be you have just too old libevent tool - then you have to upgrade it.
See the INSTALL file.
```

**Review by SeekingMeaning — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks, @SeekingMeaning. Did the failed bottles go where you wanted them to?

**Comment by SeekingMeaning** [comment]
They did, @carlocab! 🎉

**Pull request closed without merging**
