### PR TITLE
fig: remove outdated reference to docker-compose

### PR DESCRIPTION
**Pull request by brendanfalk**
Hi there. I am Brendan, founder of [Fig](fig.io) and one of the maintainers of [withfig/autocomplete](https://github.com/withfig/autocomplete).

I am requesting that this PR be merged so our users can run `brew install fig` to download Fig rather than `brew install --cask fig` Currently, fig is aliased to `docker-compose` and does not allow this.

**History**
The original Fig started in July 2014 (see [wayback machine](https://web.archive.org/web/20140727000724/https://fig.sh/)) but by March 2015 was bought by Docker and became `docker-compose` (see [wayback machine](https://web.archive.org/web/20150304014352/http://www.fig.sh/)).

**Who we are**
Fig owns the following: 
* https://fig.io
* https://fig.sh
    * This was the URL of the original Fig but the Docker team actually kindly gave us this domain as they weren't using it
* [@fig](https://twitter.com/fig) on twitter 
* the [fig](https://www.npmjs.com/package/fig) package on NPM

I think we have a pretty fair claim to this request given:
1. Fig already has brand name recognition as just "Fig" across so many platforms
2. the original Fig was deprecated > 6 years ago and only existed for ~ 9 months
3. the Docker team released the fig.sh domain name to us indicating they no longer have a need for it
4. `docker-compose` itself is being phased out in favour of `docker compose` and `docker stack`  (see [article](https://vsupalov.com/difference-docker-compose-and-docker-stack/))
5. we already have 10s of thousands of users and this number is only going to grow as we launch publicly. Many users will unintentionally install docker-compose rather than Fig and I expect this number to be far far greater than the number of users who will install Fig rather than docker-compose

Finally, if the above isn't enough, I'd be happy to get Ben Firshman (the original creator of Fig / docker-compose) and/or the Docker team to give the thumbs up that they are okay with this change.

If there are any issues with this, please let me know. I'm willing to do the leg work to make this happen!

Thanks for your time.

### CODE REVIEW

**Comment by brendanfalk** [comment]
As a separate note, the Fig team has been quite active in contributing to Brew:
* https://github.com/Homebrew/brew/pull/11990
* https://github.com/withfig/fig/discussions/300
* https://github.com/Homebrew/install/pull/557

**Review by branchv — DISMISSED** [review]
thanks @brendanfalk for all the info, this makes perfect sense to me!

let's wait for a second opinion just in case

**Review by Bo98 — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
@SMillerDev you can't automerge non-formula changes.

**Review by carlocab — APPROVED** [review]

**Comment by brendanfalk** [comment]
@branchvincent @SMillerDev @carlocab 

Thank you so very much!! :)

**Pull request merged**
