### PR TITLE
taskwarrior-tui 0.23.1

### PR DESCRIPTION
**Pull request by kdheepak**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@kdheepak version tag has some issue.

**Comment by kdheepak** [comment]
Thanks for letting me know. I accidentally tagged the wrong commit. I made a new release with v0.23.2. I'll open a new PR.

**Comment by chenrui333** [comment]
#100290

**Comment by chenrui333** [comment]
> Thanks for letting me know. I accidentally tagged the wrong commit. I made a new release with v0.23.2. I'll open a new PR.

no worries

**Pull request closed without merging**
