### PR TITLE
ringojs 0.12.0

### PR DESCRIPTION
**Pull request by saghul**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by saghul** [comment]
The last step fails because there isn't a `test do` test block in the formula.

**Comment by DomT4** [comment]
Could you possibly add a `test do`, if you know of a reasonable test to add? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test.

**Comment by saghul** [comment]
@DomT4 I force-pushed adding a simple test.

**Comment by UniqMartin** [comment]
Merged in fcdf83a9076a75a75da6409a79a8fdd66b5dfa1c. Thank you for this contribution to Homebrew, @saghul! :tada:

**Comment by botic** [comment]
Big thanks goes to @saghul for this update from the Ringo core team! We just wanted to upgrade the formula to 0.12.0 and saw it already been done.

**Comment by saghul** [comment]
Cheers @botic, glad I could help!

**Pull request merged**
