### PR TITLE
x3270: add OpenSSL dependency on macOS

### LINKED ISSUE #150202: x3270 on macOS now depends on OpenSSL
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.1.14-60-g5349b76
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5349b762929b51785bcd40c1df101f9479a0dd13
Last commit: 2 hours ago
Core tap JSON: 08 Oct 20:21 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.6.9-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2

% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run c3270 in secure (TLS) mode, i.e., set up a TLS wrapper around the TELNET session.

### What happened (include all command output)?

% c3270
c3270 v4.3ga3 Thu Sep  7 18:16:40 UTC 2023 brew
Copyright 1989-2023 by Paul Mattes, GTRC and others.

Type 'show copyright' for full copyright information.
Type 'help' for help information.

c3270> show tlsprovider
None
c3270> 

What this means is that the 'homebrew' version of c3270 was built without TLS support. This is probably due to the switch from Secure Transport for OpenSSL as the TLS provider for x3270. The fix is simple: add OpenSSL as a dependency of x3270.

### What did you expect to happen?

c3270> show tlsprovider
OpenSSL 3.1.3 19 Sep 2023
c3270>

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install c3270
```

### PR DESCRIPTION
**Pull request by pmattes**
x3270: add OpenSSL dependency on macOS. Closes https://github.com/Homebrew/homebrew-core/issues/150202.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by pmattes** [comment]
I'm going to need some assistance addressing the 'Commit style' check. How do I change my commit(s) to conform to its requirements?

**Comment by pmattes** [comment]
Hopefully better now.

**Comment by p-linnane** [comment]
Please change the actual commit to match the PR title and it'll be good to go.

**Comment by pmattes** [comment]
Abandoning this PR.

**Comment by pmattes** [comment]
The new PR is https://github.com/Homebrew/homebrew-core/pull/150351.

**Comment by p-linnane** [comment]
You can force push the change next time instead of opening a new PR.

**Comment by pmattes** [comment]
I'll need to experiment with that a bit before trying it.

**Pull request closed without merging**
