### PR TITLE
remove aqbanking and gwenhywfar

### PR DESCRIPTION
**Pull request by yurikoles**
- remove aqbanking
- remove gwenhywfar

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
See #98904. Upstream site is broken for at least 2 weeks, we can't even deprecate it correctly due to lint failure. So, since nothing depends on them, let's remove both.

### CODE REVIEW

**Comment by bayandin** [comment]
I believe broken livecheck is not a good enough reason to delete them. We should fix livecheck instead.

**Comment by yurikoles** [comment]
It's not the only case, a lot of vendor site pages return `403`, e.g. app's homepages, even the root of the site. So they look like unmaintained. I switched formulas homepages to their respective redmine projects on the same site. As of `livecheck` I don't know how to fix it, since it works absolutely fine on my local machine, but times-out on CI after 10s.

**Comment by Bo98** [comment]
> It's not the only case, a lot of vendor site pages return `403`, e.g. app's homepages, even the root of the site.

Seems to all work for me?

> So they look like unmaintained.

I disagree given there was commit activity a week ago.

> I switched formulas homepages to their respective redmine projects on the same site.

Given the old URLs redirect to the redmine URLs that makes sense to do.

> As of `livecheck` I don't know how to fix it, since it works absolutely fine on my local machine, but times-out on CI after 10s.

I wonder if there's aggressive firewalling going on here and something that's not a webpage like `https://www.aquamaniac.de/rdm/projects/gwenhywfar/files.json` would work better.

**Comment by cho-m** [comment]
I also agree that this doesn't warrant removal yet.

Closing based on current responses. We can instead focus on figuring out how to improve livecheck/audit in #98904. Seems more of an issue on Homebrew's side (CI runner environment, back-to-back curl calls, etc.) based on how it is working locally.

May be worth logging into CI runner to see if reproducible outside of workflow.

**Pull request closed without merging**
