### PR TITLE
cargo-*: do not depend on `rust` on runtime

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@equal-l2 any rationale or posts that we should read before reviewing this PR?

**Comment by equal-l2** [comment]
Rust from Homebrew conflicts with the installation via `rustup`.
Rust users usually install `cargo` via `rustup` because it enables users to easily select versions of Rust.

The binaries of `cargo-*` don't depend on Rust from Homebrew, but just need a `cargo` in any form.

**Comment by equal-l2** [comment]
Currently, dependency on Rust by `cargo-*` is not consistent.
For example, `cargo-audit` doesn't depend on Rust on runtime, while `cargo-bloat` does.

**Comment by equal-l2** [comment]
This PR fixes the problem by removing all runtime dependencies to Rust.

**Comment by iMichka** [comment]
Could we depend on `rustup` and install `cargo` for the tests? Just to make sure everything works, and no-one tries to re-introduce the `rust` runtime dependency ?

> depends_on "rust" => :build
> depends_on "rustup" => :test

**Comment by equal-l2** [comment]
I'm going to close this PR as I don't have enough time to maintain this.
Thank you to the maintainers for considering this!

**Pull request closed without merging**
