### PR TITLE
swift-format 510.1.0

### PR DESCRIPTION
**Pull request by emauricio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
The formula version (510.1.0) is newer than the version from `brew livecheck` (5.10).
```

**Comment by iMichka** [comment]
Hello; this is not marked as the latest release on https://github.com/apple/swift-format/releases/

@emauricio can you open an upstream issue and ask them if this intentional?

**Comment by emauricio** [comment]
@iMichka done
https://github.com/apple/swift-format/issues/707

**Review by p-linnane — APPROVED** [review]
Thanks!

**Pull request merged**
