### PR TITLE
mpfr: use latest patches

### PR DESCRIPTION
**Pull request by fxcoudert**
MPFR publishes patch releases as separate patches on their website (and links to the corresponding branch commits). Use those.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Should we use the numbered patches and bump the version to `4.1.0-p13`?

Numbered patches:
https://www.mpfr.org/mpfr-current/patch01
https://www.mpfr.org/mpfr-current/patch02
https://www.mpfr.org/mpfr-current/patch03
...
https://www.mpfr.org/mpfr-current/patch13

These can be applied similarly to `readline` and `bash`.

**Comment by fxcoudert** [comment]
What I don't like about the numbered patches is their URL is not permanent, which is why I chose the commits.

**Comment by carlocab** [comment]
You can use
https://www.mpfr.org/mpfr-4.1.0/patch01
https://www.mpfr.org/mpfr-4.1.0/patch02
...

**Comment by Bo98** [comment]
Given `mpfr_get_version` changes, I wonder if we should also specify `version "4.1.0-p13"` like we do with bash etc.

**Comment by fxcoudert** [comment]
I don't have a strong opinion either way, let me know what you think is best.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
