### PR TITLE
ejabberd 21.01

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> ./configure --prefix=/usr/local/Cellar/ejabberd/21.01 --sysconfdir=/usr/local/etc --localstatedir=/usr/local/var --enable-pgsql --enable-mysql --enable-odbc --enable-pam
Failed to execute: ./configure
```
I guess they got rid of their configure script.

**Comment by carlocab** [comment]
Not sure what's going on with their source tarball:
```
Permissions Size User       Date Modified Name
drwxr-xr-x     - carlocab   30 Jan 02:45  .brew_home
.rw-r--r--@  59k carlocab   30 Jan 02:45  ejabberd
❯ file ejabberd
ejabberd: HTML document text, UTF-8 Unicode text, with very long lines, with CRLF, LF line terminators
```

**Comment by chenrui333** [comment]
cc @mremond

**Comment by carlocab** [comment]
Here's why:
```
❯ curl -Ls -o /dev/null -w '%{url_effective}\n' https://www.process-one.net/downloads/ejabberd/21.01/ejabberd-21.01.tgz
https://www.process-one.net/en/ejabberd/
```
The URL doesn't exist, so you're just being redirected to the homepage.

**Comment by chenrui333** [comment]
not sure how i got that, just corrected the source. :)

**Comment by carlocab** [comment]
```
❯ brew unbottled --tag=arm64_big_sur ejabberd
==> Populating dependency tree...
==> :arm64_big_sur bottle status
ejabberd: unbottled deps: erlang@22
```

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
