### PR TITLE
gstreamer family 1.12.0

### PR DESCRIPTION
**Pull request by neutric**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by baadc0de** [comment]
Looking forward to this landing :)

**Comment by dunn** [comment]
A number of build errors to look at https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/896/#showFailuresLink

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Alias issues for `gstreamer` and `gst-plugins-{base,good,bad,ugly}`:

```
gstreamer:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/gstreamer.rb gstreamer@1.12
  * Formula has invalid versioned aliases:
      gstreamer@1.10
```

```
gst-python:
  * Dependency pygobject3 should not use option with-python3
```

And test failure in `gst-validate`:

```
==> /usr/local/Cellar/gst-validate/1.12.0/bin/gst-validate-launcher --usage
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/usr/local/Cellar/gst-validate/1.12.0/bin/gst-validate-launcher", line 68, in <module>
    from launcher.main import main
  File "/usr/local/Cellar/gst-validate/1.12.0/lib/gst-validate-launcher/python/launcher/main.py", line 21, in <module>
    from . import utils
  File "/usr/local/Cellar/gst-validate/1.12.0/lib/gst-validate-launcher/python/launcher/utils.py", line 34, in <module>
    import urllib.request
ImportError: No module named request
Error: gst-validate: failed
```

**Comment by tschoonj** [comment]
FYI: 1.12.1 has been released

**Comment by nijikon** [comment]
Are we bumping everything to 1.12.1?

**Comment by philn** [comment]
I can have a look at this today unless someone else steps up.

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/issues/15057.

**Pull request closed without merging**
