### PR TITLE
aarch64-elf-gcc 11.2.0 (new formula)

### PR DESCRIPTION
**Pull request by relokin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by relokin** [comment]
This depends on PR: [aarch64-elf-binutils 2.38 (new formula) #95167 ](https://github.com/Homebrew/homebrew-core/pull/95167). Once it has been merged, I will rebase on top of master, remove the formula for aarch64-elf-binutils and set it as ready for review.

**Comment by relokin** [comment]
As mentioned in [aarch64-elf-binutils 2.38 (new formula) #95167](https://github.com/Homebrew/homebrew-core/pull/95167), note that the audit fails due to gcc requiring a patch. This is the same patch as in x86_64-elf-gcc and the hope is that it won't be necessary with future versions of gcc.

**Comment by relokin** [comment]
Also just wanted to add that the patch has been accepted in gcc upstream: https://github.com/gcc-mirror/gcc/commit/834c8749ced550af3f17ebae4072fb7dfb90d271 . However, the patch is newer than the latest release 11.2.0.

**Review by chenrui333 — APPROVED** [review]

**Comment by relokin** [comment]
Thanks for all the help @chenrui333!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
