### PR TITLE
earthly 0.3.4

### PR DESCRIPTION
**Pull request by alexcb**
-------------

#### Debug data

PR generated by the [Earthly build](https://github.com/earthly/earthly/blob/master/release/Earthfile) (target +release-homebrew)

* `RELEASE_TAG=v0.3.4`

* `GIT_USERNAME=alexcb`

* `NEW_URL=https://github.com/earthly/earthly/archive/v0.3.4.tar.gz`

* `NEW_SHA256=f6aebf6124bb556e87ada7d8744ad1f36eb845171d7901da5d5356cdd43c8f97`

* `TAGS=dfrunmount dfrunsecurity dfsecrets dfssh dfrunnetwork`

* `LDFLAGS=-X main.DefaultBuildkitdImage=earthly/buildkitd:v0.3.4 -X main.Version=v0.3.4 -X main.GitSha=cd1225b21f409f4253e3c463174393498c4cb005 `

* `LDFLAGS1=-X main.DefaultBuildkitdImage=earthly/buildkitd:v0.3.4 -X main.Version=v0.3.4 -X`

* `LDFLAGS2= main.GitSha=cd1225b21f409f4253e3c463174393498c4cb005 `

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> brew test --verbose earthly
==> FAILED
==> Testing earthly
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200902-81310-hmrbw3.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/earthly.rb --verbose
==> /usr/local/Cellar/earthly/0.3.4/bin/earth --buildkit-host 127.0.0.1 +default 2>&1
Error: earthly: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Error\ while\ dialing\ invalid\ address\ 127\.0\.0\.1/> was expected to be =~
<"Warning: cannot create dir /Users/brew/.earthly\n" +
"time=\"2020-09-02T23:42:19+01:00\" level=error msg=\"failed to create run directory /Users/brew/.earthly/run: mkdir /Users/brew/.earthly/run: no such file or directory\" command=\"earth 127.0.0.1 +default\"\n" +
```

**Comment by alexcb** [comment]
At first the error was from attempting to make a directory under a directory that didn't exist, but we essentially changed a `mkdir` to a `mkdir -p`, and now we're seeing a permission error: `Error: failed to create run directory /Users/brew/.earthly/run: mkdir /Users/brew/.earthly: operation not permitted`.

I'm thinking that we might be able to change our test to run `earth --version` as a way to ensure the binary built (currently it tests to see if earth prints an error message saying that it can't connect to buildkit/docker).

**Comment by gromgit** [comment]
Homebrew runs both builds and tests in a sandbox, and sets `$HOME` to point inside said sandbox. Is there a reason `earth` doesn't use `$HOME` to locate its config dir?

**Comment by gromgit** [comment]
Since `earth` is written in Go, [`os.UserHomeDir`](https://golang.org/pkg/os/#UserHomeDir) is the blessed way to obtain the current user's home directory, in place of `user.Current().Homedir`: https://github.com/golang/go/issues/26463

**Comment by alexcb** [comment]
Thanks for pointing out the issue with `user.Current()`. We recently switched over to using that, but that's apparently something we should avoid, so we'll go back to using `$HOME` if it's set, otherwise fallback to `user.Current()`.

**Comment by SMillerDev** [comment]
That would be what `od.UserHomeDir` does.

**Comment by alexcb** [comment]
we updated our code to use `os.UserHomeDir` and rolled out a new version under #60606 

thanks for the help.

**Pull request closed without merging**
