### PR TITLE
cimg 2.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jconley** [comment]
getting mismatched sha:

**Comment by ilovezfs** [comment]
Probably a stealth update :(

**Comment by ilovezfs** [comment]
Diff between old and new is
```
Josephs-MacBook-Pro:cimg joe$ diff A/CImg-2.0.0/CImg.h B/CImg-2.0.0/CImg.h 
22238c22238
<         const unsigned int siz = (unsigned int)_mp_arg(3);
---
>         const unsigned int siz = (unsigned int)mp.opcode[3];
22246d22245
< 
26265c26264
<        \param[out] list_outputs In case of a mathematical expression, attach a list of images to the specified expression.
---
>        \param[out] list_outputs In case of a math expression, list of images atatched to the specified expression.
30373c30372,30373
<        \param boundary_conditions Boundary conditions. Can be <tt>{  0=dirichlet | 1=neumann | 2=periodic | 3=mirror }</tt>.
---
>        \param boundary_conditions Boundary conditions.
>               Can be <tt>{ 0=dirichlet | 1=neumann | 2=periodic | 3=mirror }</tt>.
30586c30586,30587
<        \param boundary_conditions Boundary conditions. Can be <tt>{  0=dirichlet | 1=neumann | 2=periodic | 3=mirror }</tt>.
---
>        \param boundary_conditions Boundary conditions.
>               Can be <tt>{  0=dirichlet | 1=neumann | 2=periodic | 3=mirror }</tt>.
```

**Comment by jconley** [comment]
there are also massive differences between the release at http://cimg.eu/files/ and https://github.com/dtschump/CImg/releases (lots of indent changes)

**Comment by ilovezfs** [comment]
I'll update the checksum as upstream has ruled out malicious circumstances github.com/dtschump/CImg/issues/136.

**Comment by ilovezfs** [comment]
@jconley should be fixed now https://github.com/Homebrew/homebrew-core/pull/14052.

**Pull request merged**
