### PR TITLE
librsvg 2.52.3

### PR DESCRIPTION
**Pull request by tschoonj**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tschoonj** [comment]
See https://gitlab.gnome.org/GNOME/librsvg/-/issues/787

The build goes without a hitch on my Intel MacBook Pro running 11.6

**Comment by chenrui333** [comment]
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: error: ./.libs/librsvg_c_api.a(std-fe51b9edd1d1eaed.std.99f315dd-cgu.0.rcgu.o) Unknown attribute kind (96) (Producer: 'LLVM12.0.1-rust-1.55.0-stable' Reader: 'LLVM APPLE_1_1205.0.22.9_0')

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: error: ./.libs/librsvg_c_api.a(std-fe51b9edd1d1eaed.std.99f315dd-cgu.10.rcgu.o) Unknown attribute kind (128) (Producer: 'LLVM12.0.1-rust-1.55.0-stable' Reader: 'LLVM APPLE_1_1205.0.22.9_0')

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: error: ./.libs/librsvg_c_api.a(std-fe51b9edd1d1eaed.std.99f315dd-cgu.11.rcgu.o) Unknown attribute kind (216) (Producer: 'LLVM12.0.1-rust-1.55.0-stable' Reader: 'LLVM APPLE_1_1205.0.22.9_0')
...
```

**Comment by SMillerDev** [comment]
Rebased, I'm hoping the Xcode update fixed something.

**Comment by SMillerDev** [comment]
It fails to build on ARM:
```
 cd /private/tmp/librsvg-20211017-63308-xtpjk9/librsvg-2.52.2 && mv /private/tmp/librsvg-20211017-63308-xtpjk9/librsvg-2.52.2/target/release/rsvg-convert rsvg-convert
    Finished release [optimized] target(s) in 1m 03s
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: .libs/librsvg_c_api.a the table of contents is empty (no object file members in the library define global symbols)
  CCLD     librsvg-2.la
./.libs/librsvg_c_api.a:addr2line-4174108a800ed70c.addr2line.f0613d02-cgu.5.rcgu.o: no symbols
./.libs/librsvg_c_api.a:rustc_std_workspace_alloc-39a37ce3deee7fd0.rustc_std_workspace_alloc.a091e09a-cgu.0.rcgu.o: no symbols
./.libs/librsvg_c_api.a:cfg_if-263742f878cd5cbc.cfg_if.acef5b15-cgu.0.rcgu.o: no symbols
./.libs/librsvg_c_api.a:rustc_std_workspace_core-347f56b9a3cedfe8.rustc_std_workspace_core.c840dad3-cgu.0.rcgu.o: no symbols
libtool:   error: object name conflicts in archive: .libs/librsvg-2.lax/librsvg_c_api.a//private/tmp/librsvg-20211017-63308-xtpjk9/librsvg-2.52.2/./.libs/librsvg_c_api.a
make[2]: *** [librsvg-2.la] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```
and does this error on 11 mean that we need to rebuild gdx-pixbuff?
```
 ==> /usr/local/Cellar/cherrytree/0.99.42/bin/cherrytree /private/tmp/cherrytree-test-20211017-77378-9h4xwa/homebrew.ctd --export_to_txt_dir /private/tmp/cherrytree-test-20211017-77378-9h4xwa --export_single_file
Warning: 17 14:02:38.847] [   ] [warning] /private/tmp/cherrytree-test-20211017-77378-9h4xwa/.config/cherrytree/config.cfg missing
[2021-10-17 14:02:38.850] [   ] [debug] export arguments are detected
[2021-10-17 14:02:38.850] [   ] [debug] file to export: /private/tmp/cherrytree-test-20211017-77378-9h4xwa/homebrew.ctd

(<unknown>:77392): Gtk-WARNING **: 14:02:39.536: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.
```

**Comment by carlocab** [comment]
There's an open upstream issue: https://gitlab.gnome.org/GNOME/librsvg/-/issues/787

It also affects the ARM build for the current version of `librsvg`. The issue suggests this has to do with the version of Rust we're using.

**Comment by Subsentient** [comment]
It has been suggested that this can be fixed by setting Rust's build-std option. Can anyone test to see if that fixes it? Seems homebrew eats all my environment variables.

**Comment by fxcoudert** [comment]
> It has been suggested that this can be fixed by setting Rust's build-std option

Can you have a more specific information, or provide a link? I've investigated the issue a bit further (see my comments on https://gitlab.gnome.org/GNOME/librsvg/-/issues/787), found that it's a rust runtime object file included too many times in a static archive.

**Comment by fxcoudert** [comment]
Thinking it may be a rust issue, filed at https://github.com/rust-lang/compiler-builtins/issues/443

**Comment by SMillerDev** [comment]
Thanks @fxcoudert for digging into that

**Comment by carlocab** [comment]
One thing worth noting is that MacPorts are able to build librsvg just fine with their Rust: https://ports.macports.org/port/librsvg/details/

So I wonder if the bug is somewhere on our side.

**Comment by fxcoudert** [comment]
Following my report upstream, here is a compiler-builtins PR that should fix the issue: https://github.com/rust-lang/compiler-builtins/pull/444

We could try to add that patch to rust, and recompile librsvg with it, see if that works.

**Comment by carlocab** [comment]
#90103 

Not sure if we want to put `librsvg` along with that PR (or include that change here). Feel free to amend my PR as needed.

**Comment by carlocab** [comment]
On Monterey ARM:
```
  libtool:   error: object name conflicts in archive: .libs/librsvg-2.lax/librsvg_c_api.a//private/tmp/librsvg-20220102-94168-h8oovk/librsvg-2.52.3/./.libs/librsvg_c_api.a
```

**Review by carlocab — APPROVED** [review]
All ✅ 🎉

**Pull request closed without merging**
