### PR TITLE
cocoapods 1.6.0.beta.1 (devel)

### PR DESCRIPTION
**Pull request by mxcl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Re: 3, I did `brew install cocoapods --devel` which did build from source.
Re: 4, installation of rubocop fails, probably because my Xcode/CLI-tools is all mucked up currently.

### CODE REVIEW

**Comment by mxcl** [comment]
Seems odd both the stable cocoapods and development versions fail to install on Sierra. Any clues about that?

**Comment by mxcl** [comment]
```
==> gem install cocoapods-1.5.3.gem
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: cocoapods requires cocoapods-core (= 1.5.3), claide (< 2.0, >= 1.0.2), cocoapods-deintegrate (< 2.0, >= 1.0.2), cocoapods-downloader (< 2.0, >= 1.2.0), cocoapods-plugins (< 2.0, >= 1.0.0), cocoapods-search (< 2.0, >= 1.0.0), cocoapods-stats (< 2.0, >= 1.0.0), cocoapods-trunk (< 2.0, >= 1.3.0), cocoapods-try (< 2.0, >= 1.1.0), molinillo (~> 0.6.5), xcodeproj (< 2.0, >= 1.5.7), activesupport (< 5, >= 4.0.2), colored2 (~> 3.1), escape (~> 0.0.4), fourflusher (~> 2.0.1), gh_inspector (~> 1.0), nap (~> 1.0), ruby-macho (~> 1.1)
```

**Comment by amorde** [comment]
At first glance I'm not really sure what the issue is, since the error isn't exactly helpful

**Comment by mxcl** [comment]
The stable url is the same as before this patch, anything changed on CI lately? I guess I'll try and figure it out.

**Comment by commitay** [comment]
Rubygems TLS deprecation.

> Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version

**Comment by MikeMcQuaid** [comment]
Thanks @mxcl for your contribution to Homebrew! Your username seems strangely familiar but I have no idea from where.

**Pull request merged**
