### PR TITLE
skafos 1.3.0

### PR DESCRIPTION
**Pull request by wess**
Introduces new configuration format which allows more flexible execution of user jobs.

- [ X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by wess** [comment]
So it's getting a 404 for the download URL, but it's the exact same, and done the same way as 1.2. Am I missing something?

**Comment by fxcoudert** [comment]
https://github.com/MetisMachine/skafos/releases shows a different URL
Please provide a single commit with message `skafos 1.3.0`

**Comment by wess** [comment]
All set, thanks @fxcoudert

**Comment by ilovezfs** [comment]
There 2 commits.

**Comment by commitay** [comment]
Thanks @wess!

**Pull request closed without merging**
