### PR TITLE
thefuck 3.30

### PR DESCRIPTION
**Pull request by jnozsc**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — CHANGES_REQUESTED** [review]
we still prefer `https://files.pythonhosted.org/packages/46/ed/11176f81a85876f4016c18907d6e085862df464a76628b91b3e91f080c7e/thefuck-3.30.tar.gz` over github archive.

Also you might need to refresh the dependencies as well.

**Comment by jnozsc** [comment]
Thanks.

The url is a easy change

About those dependencies, have they to be latest version or?
I check their source codes,  https://github.com/nvbn/thefuck/blob/3.30/setup.py#L36 I don't think they explicitly specify the version anywhere

**Comment by chenrui333** [comment]
@jnozsc so usually what I do is update all the dependencies to the latest if permits
There is some utility that you can use on this purpose.
https://github.com/dawidd6/homebrew-update-pypi-resources

**Comment by chenrui333** [comment]
Here is basically what I did:
- git checkout thefuck-3.30
- brew update-pypi-resources thefuck
- brew reinstall/test thefuck

And then commit and rebase stuff

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Now it should be sufficient.

**Comment by jnozsc** [comment]
thanks for the help

**Comment by chenrui333** [comment]
no problems!

**Pull request closed without merging**
