### PR TITLE
gsl 2.6

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Revision bumps needed for 

```
brew-test-bot.mojave.linkage --test astrometry-net
brew-test-bot.mojave.test bcftools
brew-test-bot.mojave.test dieharder
brew-test-bot.mojave.linkage --test dynare
brew-test-bot.mojave.test flowgrind
brew-test-bot.mojave.linkage --test gnuradio
brew-test-bot.mojave.test nco
brew-test-bot.mojave.linkage --test oscats
brew-test-bot.mojave.test qsoas
brew-test-bot.mojave.linkage --test root
brew-test-bot.mojave.test siril
brew-test-bot.mojave.linkage --test visp
```

**Comment by tschoonj** [comment]
`qsoas` does not compile against `mruby 2.0.x` due to some missing preprocessor macros. I opened an issue at https://sourceforge.net/p/qsoas/discussion/general/thread/88bcfd319e. They don't appear to have their version control repo publicly available so I cannot see if there's already a patch. 

Probably easily fixed by introducing an `mruby@1` Formula but that's perhaps a bit too much?

`flowgrind` fails to build on Sierra with a linker error:

```
ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
```

Not sure how to fix this: perhaps make HighSierra minimal required version of macOS?

**Comment by fxcoudert** [comment]
If you grep for `libsystem_darwin` in our formulas, it's a rather common issue (but I've never really understood it 😢). We usually do this:

```
    # Fix "ld: file not found: /usr/lib/system/libsystem_darwin.dylib" for lxml
    ENV["SDKROOT"] = MacOS.sdk_path if MacOS.version == :sierra
```

**Comment by tschoonj** [comment]
Thanks!

Any thoughts about fixing `qsoas`?

**Comment by fxcoudert** [comment]
> Any thoughts about fixing qsoas?

At 1 install per 30 days, I would be tempted to remove it if it doesn't build anymore with latest `mruby`. Especially since they, although it's open source, the development is not actually that open.

**Comment by fxcoudert** [comment]
Ho, just realised I actually know the qsoas main developer :) poke @fourmond 

Vincent, is there an easy way we can get `qsoas` building with recent `mruby` (2.0.1)? Otherwise we might have to drop it from Homebrew, as it is doesn't build anymore on our machines. Thanks!

**Comment by fourmond** [comment]
Heya !

Indeed -- seems like I know you too ;-) !

Next version will build with mruby 2.0 -- although there is a bug in mruby
or qsoas that makes it crash for certain involved uses...

I could probably extract a patch against 2.2, if you want.

Cheers !

Vincent

**Comment by fxcoudert** [comment]
@fourmond if that next release is not imminent, a patch would be appreciated. We tried to find the source repo, but it appears it is not public?

**Comment by fourmond** [comment]
I'll push the patch to the release branch. For the record, we're not
using a public git repository for the day-to-day changes since the commits
are far too revealing concerning the research activity of my team... But
the full history will be merged in the release branch for the next release.

  Cheers,

      Vincent

>

**Comment by fourmond** [comment]
Compilation and most of the tests are fixed with fourmond/QSoas@2bffb9ff68af68f7a4f597b5c3435c709af16344

**Comment by tschoonj** [comment]
@fourmond Unfortunately this patch cannot be applied to the 2.2.0 release cleanly, so I had to use all your commits since 2.2.0 was released instead.

**Pull request closed without merging**
