### PR TITLE
x3270 4.0ga10

### PR DESCRIPTION
**Pull request by chimurai**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chimurai** [comment]
Failed on: 
> stable version should not decrease (from 4.0ga9 to 4.0ga10)

Not sure how to fix this since the versioning scheme is not following semver.

**Comment by gromgit** [comment]
Since all released versions seem to have the same scheme, I think the way forward is to manually specify the version, so you need to add this to the formula:
```
version "4.0.10"
version_scheme 1
```
Please read https://rubydoc.brew.sh/Formula.html, in particular the class attributes `version` and `version_scheme`.

**Comment by chimurai** [comment]
Thanks @gromgit for the suggestion. I didn't know that.

Updated the PR.

**Comment by SMillerDev** [comment]
I don't think we should be using a different version than upstream unless they specifically mention that `x.x.x` is the version scheme and `x.xgax` is just for the archives

**Comment by chimurai** [comment]
When I print the version with `c3270 --version`, this is being outputted:

> c3270 v4.0ga10

@SMillerDev  do you have a suggestion how to proceed?

**Comment by SMillerDev** [comment]
You should define the version as upstream defines it. Don't define it as semver. And try without version scheme if possible.

**Comment by gromgit** [comment]
Since the CI is already complaining because "4.0ga10" < "4.0ga9", isn't at least a `version_scheme 1` declaration necessary?

**Comment by chimurai** [comment]
Getting same error message with or without version_scheme, when defining the same version as defined by x3270.

With just version (without version_scheme):
`version "4.0ga10"`

After `brew audit --strict x3270`
>   * Stable: version 4.0ga10 is redundant with version scanned from URL

---

With version including version_scheme:
`version "4.0ga10"`
 `version_scheme 1`


After `brew audit --strict x3270`
>   * Stable: version 4.0ga10 is redundant with version scanned from URL

**Comment by SMillerDev** [comment]
In that case you don't need to define the version line. I think this might be a @Homebrew/brew bug in that case though.

**Comment by MikeMcQuaid** [comment]
I don't think it's a bug. The `version` being redundant is unrelated to the `version_scheme`.

**Comment by gromgit** [comment]
@chimurai , just add `version_scheme 1` without the `version` line. That should tell Homebrew to "reset" its idea of the base version.

**Comment by MikeMcQuaid** [comment]
> Since the CI is already complaining because "4.0ga10" < "4.0ga9", isn't at least a `version_scheme 1` declaration necessary?

This is the bit that should be fixed in Homebrew/brew.

**Comment by SMillerDev** [comment]
What about it thinking the version is lower though @MikeMcQuaid ?

**Comment by MikeMcQuaid** [comment]
> What about it thinking the version is lower though @MikeMcQuaid ?

Yeh, I'd consider that a bug worth fixing in Homebrew/brew.

**Comment by chimurai** [comment]
@gromgit adding just `version_scheme 1` works. All checks passed.

Should this PR wait for the bugfix in `Homebrew/brew`?

**Comment by samford** [comment]
> Yeh, I'd consider that a bug worth fixing in Homebrew/brew.

I've drafted a fix for the version comparison issue in Homebrew/brew#8125, for what it's worth.

**Comment by gromgit** [comment]
> @gromgit adding just `version_scheme 1` works. All checks passed.
> 
> Should this PR wait for the bugfix in `Homebrew/brew`?

Yes, please wait for the outcome of @samford 's patch. If it goes through, then remove the `version_scheme` line and push it again.

**Comment by samford** [comment]
Homebrew/brew#8125 is merged, so the `version_scheme` line can be removed now.

**Comment by MikeMcQuaid** [comment]
But note this PR cannot be merged until that's in a tagged release.

**Comment by chimurai** [comment]
Removed `version_scheme` from the PR.

**Comment by jonchang** [comment]
License here is BSD-3-clause: http://x3270.bgp.nu/license.html

**Comment by chimurai** [comment]
Added `license "BSD-3-Clause" ` to this PR

**Review by samford — APPROVED** [review]
A new Homebrew/brew version has been tagged ([2.4.10](https://github.com/Homebrew/brew/releases/tag/2.4.10)), so we can merge this now. I rebased this and CI looks good.

Thanks, @chimurai!

**Comment by chimurai** [comment]
Thanks for the amazing support!

**Pull request closed without merging**
