### PR TITLE
tetra 0.9.0

### PR DESCRIPTION
**Pull request by mtardy**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* Update README.md by @michi-covalent in https://github.com/cilium/tetragon/pull/489
* tetragon: Add --rb-size/--rb-size-total options to setup perf ring buffer size by @olsajiri in https://github.com/cilium/tetragon/pull/480
* pkg:sensors: log loading BPF programs by @tixxdz in https://github.com/cilium/tetragon/pull/474
* mention LOCAL_CLANG in contributor's dev docs by @dmitris in https://github.com/cilium/tetragon/pull/503
* build(deps): bump golang from 1.16 to 1.19.2 by @dependabot in https://github.com/cilium/tetragon/pull/502
* program/loader: properly log verifier errors by @willfindlay in https://github.com/cilium/tetragon/pull/504
* build(deps): bump actions/download-artifact from 3 to 3.0.1 by @dependabot in https://github.com/cilium/tetragon/pull/501
* chore: remove binary accidentally checked in by @willfindlay in https://github.com/cilium/tetragon/pull/508
* Fix a deadlock in eventcache by @tpapagian in https://github.com/cilium/tetragon/pull/510
* minor README updates by @dmitris in https://github.com/cilium/tetragon/pull/512
* correct a sentence in 'Deploy Tetragon' by @dmitris in https://github.com/cilium/tetragon/pull/509
* server: drop events if listener channel is full by @kkourt in https://github.com/cilium/tetragon/pull/511
* Remove pidMap by @tpapagian in https://github.com/cilium/tetragon/pull/497
* build: sign Tetragon container images by @sandipanpanda in https://github.com/cilium/tetragon/pull/517
* Chore: registered probe types by @zhiyu0729 in https://github.com/cilium/tetragon/pull/519
* chore: sample memfd_create rule by @krol3 in https://github.com/cilium/tetragon/pull/484
* tetragon: fix graceful shutdown and exit code by @tixxdz in https://github.com/cilium/tetragon/pull/520
* ci/e2e: fix test failure file exports by @willfindlay in https://github.com/cilium/tetragon/pull/518
* add kubebuilder validation GetUrl;DnsLookup , it can't get "The Traci… by @sunnoy in https://github.com/cilium/tetragon/pull/525
* Update automatically generated files by @kevsecurity in https://github.com/cilium/tetragon/pull/528
* tetragon: Add bpf_printk helper from libbpf by @olsajiri in https://github.com/cilium/tetragon/pull/514
* vendor: update cilium/ebpf by @willfindlay in https://github.com/cilium/tetragon/pull/522
* cli: add field filters to the CLI and tetragon configmap by @willfindlay in https://github.com/cilium/tetragon/pull/513
* tetragon: improve how we read process info during startup by @tixxdz in https://github.com/cilium/tetragon/pull/523
* tetragon: Switch to clang-14 by @olsajiri in https://github.com/cilium/tetragon/pull/397
* various fixes motivated by a failure of the raw syscall test by @kkourt in https://github.com/cilium/tetragon/pull/531
* Fix for execve events that come after clone by @tpapagian in https://github.com/cilium/tetragon/pull/532
* Make size of event queue configurable by @kevsecurity in https://github.com/cilium/tetragon/pull/535
* cgroups: add basic cgroups tracking and make it part of the testing framework by @tixxdz in https://github.com/cilium/tetragon/pull/471
* tetragon: Add ReleasedPinnedBPF option to remove any old progs/maps by @jrfastab in https://github.com/cilium/tetragon/pull/542
* build(deps): bump docker/build-push-action from 3.1.1 to 3.2.0 by @dependabot in https://github.com/cilium/tetragon/pull/506
* tetragon: Add v6.0 bpf objects and related fixes by @olsajiri in https://github.com/cilium/tetragon/pull/537
* vmtests/doc: fix by @kkourt in https://github.com/cilium/tetragon/pull/547
* build(deps): bump github/codeql-action from 2.1.26 to 2.1.33 by @dependabot in https://github.com/cilium/tetragon/pull/546
* Makefile.cli: deal with {g,u}id collision by @kkourt in https://github.com/cilium/tetragon/pull/557
* tests:cgroups: add tests to emulate k8s hierarchies by @tixxdz in https://github.com/cilium/tetragon/pull/536
* tetragon: fix cobra command line usage by @tixxdz in https://github.com/cilium/tetragon/pull/565
* tetragon: Add pprof http support by @anjmao in https://github.com/cilium/tetragon/pull/551
* watcher cleanup by @kkourt in https://github.com/cilium/tetragon/pull/555
* support for using unix socket for gRPC by @kkourt in https://github.com/cilium/tetragon/pull/552
* tetragon: fixup generic tracepoint sensor create by @Y-dc in https://github.com/cilium/tetragon/pull/568
* tetragon: fix initialization deadlock by @kkourt in https://github.com/cilium/tetragon/pull/574
* build(deps): bump docker/login-action from 2.0.0 to 2.1.0 by @dependabot in https://github.com/cilium/tetragon/pull/572
* tetragon: Check and remove not compatible map pin paths on loading by @olsajiri in https://github.com/cilium/tetragon/pull/543
* build(deps): bump github/codeql-action from 2.1.33 to 2.1.36 by @dependabot in https://github.com/cilium/tetragon/pull/583
* Makefile: Fix potential uid/gid collision by using setpriv by @kkourt in https://github.com/cilium/tetragon/pull/586
* dockerfile: remove addgroup hubble by @tixxdz in https://github.com/cilium/tetragon/pull/588
* jsonchecker: retry on EOF/UnexpectedEOF in unmarshaller by @willfindlay in https://github.com/cilium/tetragon/pull/587
* tetragon: logging improvements for non k8s deployment by @tixxdz in https://github.com/cilium/tetragon/pull/582
* tests/e2e: make cilium version configurable by @willfindlay in https://github.com/cilium/tetragon/pull/591
* ci: bump golangci-lint to v1.50.1 by @rolinh in https://github.com/cilium/tetragon/pull/580
* tetragon: Make sure to read meaningful size data from char_buf args by @Y-dc in https://github.com/cilium/tetragon/pull/564
* vendor: bump golang-lru to v2 (requires Go >= v1.18 support for generics) by @rolinh in https://github.com/cilium/tetragon/pull/579
* build(deps): bump actions/checkout from 3.1.0 to 3.2.0 by @dependabot in https://github.com/cilium/tetragon/pull/592
* ci: replace deprecated set-output directives by @willfindlay in https://github.com/cilium/tetragon/pull/598
* add Code of Conduct by @xmulligan in https://github.com/cilium/tetragon/pull/600
* tetragon: Allow full exec path/args retrieval on 4.19 kernels by @olsajiri in https://github.com/cilium/tetragon/pull/156
* build(deps): bump ubuntu from `34fea4f` to `35fb073` by @dependabot in https://github.com/cilium/tetragon/pull/507
* logging: allow users to know more about the overall status by @tixxdz in https://github.com/cilium/tetragon/pull/590
* build(deps): bump github/codeql-action from 2.1.36 to 2.1.37 by @dependabot in https://github.com/cilium/tetragon/pull/596
* sensor cleanups by @kkourt in https://github.com/cilium/tetragon/pull/581
* eventcache: update PodInfoError on pod error by @kkourt in https://github.com/cilium/tetragon/pull/609
* build: Generate SBOM during image release by @sandipanpanda in https://github.com/cilium/tetragon/pull/559
* helm: use a specific conf.d directory for --config-dir by @tixxdz in https://github.com/cilium/tetragon/pull/599
* build(deps): bump golang from 1.19.2 to 1.19.4 by @dependabot in https://github.com/cilium/tetragon/pull/607
* build(deps): bump actions/download-artifact from 3.0.1 to 3.0.2 by @dependabot in https://github.com/cilium/tetragon/pull/610
* loader: support larger verifier log sizes by @willfindlay in https://github.com/cilium/tetragon/pull/595
* cgroups: ensure that cgroup IDs correlate with execve events by @tixxdz in https://github.com/cilium/tetragon/pull/541
* tests/e2e: remove GKE auth plugin, it's deprecated by @willfindlay in https://github.com/cilium/tetragon/pull/606
* ci: use large github runner by @willfindlay in https://github.com/cilium/tetragon/pull/615
* ci/formatting: various improvements by @willfindlay in https://github.com/cilium/tetragon/pull/617
* tetragon: Switch exit tracepoint to __put_task_struct kprobe by @olsajiri in https://github.com/cilium/tetragon/pull/558
* build(deps): bump library/alpine from 3.16.2 to 3.17.1 by @dependabot in https://github.com/cilium/tetragon/pull/614
* bpf:cgroups: error flags improvements by @tixxdz in https://github.com/cilium/tetragon/pull/594
* tetragon: Use probe task instead of current in event_exit_send by @olsajiri in https://github.com/cilium/tetragon/pull/630
* Fix SBOM image signing and update image siganture verification docs by @sandipanpanda in https://github.com/cilium/tetragon/pull/618
* Minor improvements to the README by @mtardy in https://github.com/cilium/tetragon/pull/632
* build(deps): bump golang from 1.19.4 to 1.19.5 by @dependabot in https://github.com/cilium/tetragon/pull/623
* tetragon: disable gops server by default by @tixxdz in https://github.com/cilium/tetragon/pull/642
* bpf_alignchecker.c: avoid unused var error by @dmitris in https://github.com/cilium/tetragon/pull/637
* tetragon: Cleanup func_id/id mess in struct msg_generic_kprobe by @olsajiri in https://github.com/cilium/tetragon/pull/604
* Add skb_adjust_room helper by @kevsecurity in https://github.com/cilium/tetragon/pull/648
* tetragon: better config handling mechanism by @tixxdz in https://github.com/cilium/tetragon/pull/635
* tetragon: loader sensor by @olsajiri in https://github.com/cilium/tetragon/pull/573
* gettid wrapper by @dmitris in https://github.com/cilium/tetragon/pull/639
* Update Makefile test target dependencies and run test as root by @mtardy in https://github.com/cilium/tetragon/pull/649
* encoder: pretty print bpf events by @willfindlay in https://github.com/cilium/tetragon/pull/650
* e2e-framework: force update when adding helm repo by @willfindlay in https://github.com/cilium/tetragon/pull/644
* tetra: Add a `GetFilter` var in getevents, add documentation and tests by @mtardy in https://github.com/cilium/tetragon/pull/643
* CRD examples: Replace invalid TracingPolicy names by @mtardy in https://github.com/cilium/tetragon/pull/652
* tetragon: tarball deployment by @tixxdz in https://github.com/cilium/tetragon/pull/647
* ci: pin docker buildx version to v0.9.1 by @willfindlay in https://github.com/cilium/tetragon/pull/659
* ci: add make tarball check and release by @tixxdz in https://github.com/cilium/tetragon/pull/665
* tetra: use field filters when reading via `io_reader_client` by @mtardy in https://github.com/cilium/tetragon/pull/668
* pkg/config: add k8s validation on `metadata.name` by @mtardy in https://github.com/cilium/tetragon/pull/661
* pkg/config: print name in validation error by @mtardy in https://github.com/cilium/tetragon/pull/670
* eventchecker: implement checker names by @willfindlay in https://github.com/cilium/tetragon/pull/662
* tetragon: Use lru.Cache for data events storage by @olsajiri in https://github.com/cilium/tetragon/pull/382
* tetragon: bpf/Makefile fixes by @olsajiri in https://github.com/cilium/tetragon/pull/602
* tetragon: log pinned bpf and maps status by @tixxdz in https://github.com/cilium/tetragon/pull/666
* tetragon: couple bpf fixes by @olsajiri in https://github.com/cilium/tetragon/pull/680
* data: silence annoying debug log messages by @willfindlay in https://github.com/cilium/tetragon/pull/676
* fix the URL for the "first good issue" list by @dmitris in https://github.com/cilium/tetragon/pull/685
* make:trivial: do sha256sum inside directory by @tixxdz in https://github.com/cilium/tetragon/pull/687
* deployment: minor tarball uninstall fixes by @tixxdz in https://github.com/cilium/tetragon/pull/684
* tetragon: set default value of release-pinned-bpf to true by @willfindlay in https://github.com/cilium/tetragon/pull/689
* Changing bpf prog load, map create event names to be more descriptive by @sharlns in https://github.com/cilium/tetragon/pull/667
* build(deps): bump github.com/emicklei/go-restful from 2.9.5+incompatible to 2.16.0+incompatible by @dependabot in https://github.com/cilium/tetragon/pull/691
* build(deps): bump github.com/emicklei/go-restful from 2.9.5+incompatible to 2.16.0+incompatible in /pkg/k8s by @dependabot in https://github.com/cilium/tetragon/pull/692
* tests/e2e: handle procRoot correctly in KinD clusters by @willfindlay in https://github.com/cilium/tetragon/pull/688
* tests/e2e: add ability to reset checker limits and retry demo app installation by @willfindlay in https://github.com/cilium/tetragon/pull/674
* tetragon: Minor include headers changes in loader by @olsajiri in https://github.com/cilium/tetragon/pull/690
* tetragon: Fix bpf_printk for single string argument by @olsajiri in https://github.com/cilium/tetragon/pull/693
* tetragon: Get proper exex cwd in case of no arguments by @olsajiri in https://github.com/cilium/tetragon/pull/683
* Add start time to event cache object by @kevsecurity in https://github.com/cilium/tetragon/pull/698
* runtime hooks support for tetragon by @kkourt in https://github.com/cilium/tetragon/pull/695
* Improve README and document tracing policies by @mtardy in https://github.com/cilium/tetragon/pull/673
* use  go 1.19.6 by @kkourt in https://github.com/cilium/tetragon/pull/715
* tetragon: introduce Cgroup ID Tracker by @tixxdz in https://github.com/cilium/tetragon/pull/677
* update go modules (manually) by @kkourt in https://github.com/cilium/tetragon/pull/717
* build(deps): bump actions/checkout from 3.2.0 to 3.3.0 by @dependabot in https://github.com/cilium/tetragon/pull/611
* build(deps): bump fedora from 36 to 37 by @dependabot in https://github.com/cilium/tetragon/pull/646
* tetragon: Fix action offset masking by @olsajiri in https://github.com/cilium/tetragon/pull/720
* tetragon: cleanup grpc unix socket by @tixxdz in https://github.com/cilium/tetragon/pull/716
* matchArgs: do not match on empty file by @tpapagian in https://github.com/cilium/tetragon/pull/718
* logging: log observer status only once 24h and for non k8s by @tixxdz in https://github.com/cilium/tetragon/pull/721
* tracing policies cleanups by @kkourt in https://github.com/cilium/tetragon/pull/700
* Handle multiple URL and DNS selectors correctly by @kevsecurity in https://github.com/cilium/tetragon/pull/719
* matchBinaries improvements by @tpapagian in https://github.com/cilium/tetragon/pull/686
* Fix multiple file match bugs by @kevsecurity in https://github.com/cilium/tetragon/pull/724
* tetra CLI: Fix rthook/create-container command arguments by @olsajiri in https://github.com/cilium/tetragon/pull/710
* Unpin buildx version in CI by @mtardy in https://github.com/cilium/tetragon/pull/735
* build(deps): bump docker/build-push-action from 3.2.0 to 4.0.0 by @dependabot in https://github.com/cilium/tetragon/pull/732
* introduce policyfilter mechanism by @kkourt in https://github.com/cilium/tetragon/pull/723
* build(deps): bump github.com/spf13/viper from 1.12.0 to 1.15.0 by @dependabot in https://github.com/cilium/tetragon/pull/745
* Make functions in pkg/selectors/kernel.go public by @tpapagian in https://github.com/cilium/tetragon/pull/742
* clang image: add support for arm64 and detect arch for BPF compilation by @mtardy in https://github.com/cilium/tetragon/pull/743
* development Quality-of-Life updates by @kkourt in https://github.com/cilium/tetragon/pull/748
* matchBinaries: Add NotIn in tracing policy by @tpapagian in https://github.com/cilium/tetragon/pull/754
* Create MAINTAINERS.md by @xmulligan in https://github.com/cilium/tetragon/pull/760
* build(deps): bump docker/setup-buildx-action from 2.2.1 to 2.4.1 by @dependabot in https://github.com/cilium/tetragon/pull/741
* tetragon: Get rid of generic_process_event* functions by @olsajiri in https://github.com/cilium/tetragon/pull/740
* build(deps): bump github.com/vishvananda/netlink from 1.1.1-0.20220125195016-0639e7e787ba to 1.2.1-beta.2 by @dependabot in https://github.com/cilium/tetragon/pull/762
* kprobe: detect and add missing syscall arch prefix by @mtardy in https://github.com/cilium/tetragon/pull/752
* build(deps): bump go.uber.org/multierr from 1.8.0 to 1.9.0 by @dependabot in https://github.com/cilium/tetragon/pull/767
* build(deps): bump golangci/golangci-lint-action from 3.3.1 to 3.4.0 by @dependabot in https://github.com/cilium/tetragon/pull/768
* build(deps): bump golangci/golangci-lint from v1.50.1 to v1.51.2 by @dependabot in https://github.com/cilium/tetragon/pull/769
* Export selector ops from pkg/selectors/kernel.go by @tpapagian in https://github.com/cilium/tetragon/pull/763
* build(deps): bump library/alpine from 3.17.1 to 3.17.2 by @dependabot in https://github.com/cilium/tetragon/pull/773
* build(deps): bump github.com/prometheus/client_golang from 1.12.2 to 1.14.0 by @dependabot in https://github.com/cilium/tetragon/pull/772
* contrib: script for dependabot PRs that failed by @kkourt in https://github.com/cilium/tetragon/pull/765
* pkg/cilium: retry if socket does not exist by @kkourt in https://github.com/cilium/tetragon/pull/759
* trivial:doc: add code documentation for nspid when getting Pod info by @tixxdz in https://github.com/cilium/tetragon/pull/775
* clang image: rework workflow to dry run on PR by @mtardy in https://github.com/cilium/tetragon/pull/777
* fix char buff matchargs by @kkourt in https://github.com/cilium/tetragon/pull/770
* Fix clang image build workflow SBOM step by @mtardy in https://github.com/cilium/tetragon/pull/782
* Fixing the build clang image build workflow by @mtardy in https://github.com/cilium/tetragon/pull/783
* Add a Tetragon documentation website and rename base folder `crds` into `examples` by @mtardy in https://github.com/cilium/tetragon/pull/778
* Fix workflow to build docs from `./docs` folder  by @mtardy in https://github.com/cilium/tetragon/pull/787
* Deploy docs if we manually trigger the workflow by @mtardy in https://github.com/cilium/tetragon/pull/788
* Add support for arm64 for building, running and testing by @mtardy in https://github.com/cilium/tetragon/pull/734
* build(deps): bump golang from 1.19.5 to 1.20.2 by @dependabot in https://github.com/cilium/tetragon/pull/792
* Doc: temporary hugo baseURL fix to serve website by @mtardy in https://github.com/cilium/tetragon/pull/798
* docs: use tetragon.cilium.io domain for website by @mtardy in https://github.com/cilium/tetragon/pull/800
* namespaced tracing policies: core implementation by @kkourt in https://github.com/cilium/tetragon/pull/749
* build(deps): bump library/alpine from `69665d0` to `ff6bdca` by @dependabot in https://github.com/cilium/tetragon/pull/801
* tetragon: Export podInformer by @tpapagian in https://github.com/cilium/tetragon/pull/799
* docs: improve namespace and caps changes filter doc by @tixxdz in https://github.com/cilium/tetragon/pull/804
* Documentation: add a links checker to the CI by @mtardy in https://github.com/cilium/tetragon/pull/805
* docs: missing space indent by @cjtim in https://github.com/cilium/tetragon/pull/809
* Docs: add netlify config file to ignore non-docs related PRs by @mtardy in https://github.com/cilium/tetragon/pull/814
* Workflow: fix netlify deploy preview by @mtardy in https://github.com/cilium/tetragon/pull/815
* Cross-compile arm64 container images by @mtardy in https://github.com/cilium/tetragon/pull/816
* Workflow: fix syntax of build image CI by @mtardy in https://github.com/cilium/tetragon/pull/819
* tetragon: Add generic uprobe sensor by @olsajiri in https://github.com/cilium/tetragon/pull/603
* tetragon: Fix multi kprobe attach data by @olsajiri in https://github.com/cilium/tetragon/pull/832
* dependaboit-fail: check app/dependabot login by @kkourt in https://github.com/cilium/tetragon/pull/803
* Makefile: add targets to build the docs via Docker by @mtardy in https://github.com/cilium/tetragon/pull/839
* Add conditional Dockerfile stage to build or download bpftool by @mtardy in https://github.com/cilium/tetragon/pull/837
* bugfix: matchBinaries in multiple selectors by @tpapagian in https://github.com/cilium/tetragon/pull/774
* eventchecker: output checker names in event mismatches by @willfindlay in https://github.com/cilium/tetragon/pull/840
* ignore .idea by @zhy76 in https://github.com/cilium/tetragon/pull/829
* docs: add link to kubernetes style guide by @kkourt in https://github.com/cilium/tetragon/pull/847
* build(deps): bump cilium/clang from `aeaada5` to `aeaada5` by @dependabot in https://github.com/cilium/tetragon/pull/818
* build(deps): bump github.com/stretchr/testify from 1.8.1 to 1.8.2 by @zhy76 in https://github.com/cilium/tetragon/pull/849
* kprobes: add a prevalidate kprobe semantics phase by @tixxdz in https://github.com/cilium/tetragon/pull/830
* build(deps): bump library/alpine from 3.17.2 to 3.17.3 by @dependabot in https://github.com/cilium/tetragon/pull/855
* tetragon: move all cli flags to options.Config by @YTGhost in https://github.com/cilium/tetragon/pull/858
* Helm chart: bump quay.io/cilium/hubble-export-stdout to v1.0.3 by @mtardy in https://github.com/cilium/tetragon/pull/856
* build(deps): bump sigstore/cosign-installer from 2.8.1 to 3.0.1 by @dependabot in https://github.com/cilium/tetragon/pull/771
* tetragon: Add --force-large-progs option to force large bpf programs by @olsajiri in https://github.com/cilium/tetragon/pull/795
* Revert "build(deps): bump sigstore/cosign-installer from 2.8.1 to 3.0.1" by @kkourt in https://github.com/cilium/tetragon/pull/861
* Fix Netlify ignore command to trigger build previews only on docs PR by @mtardy in https://github.com/cilium/tetragon/pull/846
* README: remove redundancy (trivial) by @kkourt in https://github.com/cilium/tetragon/pull/863
* tetragon: Bench script and multi kprobe fixes by @olsajiri in https://github.com/cilium/tetragon/pull/796
* ci: fixes for release automation by @willfindlay in https://github.com/cilium/tetragon/pull/865
* build(deps): bump golangci/golangci-lint from v1.51.2 to v1.52.2 by @dependabot in https://github.com/cilium/tetragon/pull/866
* build(deps): bump google.golang.org/protobuf from 1.28.1 to 1.30.0 by @YTGhost in https://github.com/cilium/tetragon/pull/842
* support for namespaced policies by @kkourt in https://github.com/cilium/tetragon/pull/694
* selectors: Export newKernelSelectorState function by @tpapagian in https://github.com/cilium/tetragon/pull/870
* Fix tests to run on arm64 by @mtardy in https://github.com/cilium/tetragon/pull/871
* Prepare for v0.9.0 release by @willfindlay in https://github.com/cilium/tetragon/pull/875

## New Contributors
* @sandipanpanda made their first contribution in https://github.com/cilium/tetragon/pull/517
* @zhiyu0729 made their first contribution in https://github.com/cilium/tetragon/pull/519
* @krol3 made their first contribution in https://github.com/cilium/tetragon/pull/484
* @sunnoy made their first contribution in https://github.com/cilium/tetragon/pull/525
* @anjmao made their first contribution in https://github.com/cilium/tetragon/pull/551
* @Y-dc made their first contribution in https://github.com/cilium/tetragon/pull/568
* @cjtim made their first contribution in https://github.com/cilium/tetragon/pull/809
* @zhy76 made their first contribution in https://github.com/cilium/tetragon/pull/829
* @YTGhost made their first contribution in https://github.com/cilium/tetragon/pull/858

**Full Changelog**: https://github.com/cilium/tetragon/compare/v0.8.3...v0.9.0</pre>
</details>

### CODE REVIEW

**Comment by p-linnane** [comment]
```
  ==> go build -trimpath -o=/opt/homebrew/Cellar/tetra/0.9.0/bin/tetra -ldflags=-s -w -X github.com/cilium/tetragon/pkg/version.Version=0.9.0 ./cmd/tetra
  github.com/cilium/tetragon/pkg/cgroups: build constraints exclude all Go files in /private/tmp/tetra-20230403-67570-1a9euh3/tetragon-0.9.0/pkg/cgroups
  # github.com/cilium/tetragon/pkg/bpf
  pkg/bpf/perf.go:106:24: undefined: unix.CBitFieldMaskBit34
```

**Comment by mtardy** [comment]
> ```
>   ==> go build -trimpath -o=/opt/homebrew/Cellar/tetra/0.9.0/bin/tetra -ldflags=-s -w -X github.com/cilium/tetragon/pkg/version.Version=0.9.0 ./cmd/tetra
>   github.com/cilium/tetragon/pkg/cgroups: build constraints exclude all Go files in /private/tmp/tetra-20230403-67570-1a9euh3/tetragon-0.9.0/pkg/cgroups
>   # github.com/cilium/tetragon/pkg/bpf
>   pkg/bpf/perf.go:106:24: undefined: unix.CBitFieldMaskBit34
> ```

I prepared a patch so that `0.9.1` should build https://github.com/cilium/tetragon/pull/883.

**Comment by mtardy** [comment]
Should I close this PR since 0.9.0 will never build for darwin?

**Comment by p-linnane** [comment]
Yes, we can try to package 0.9.1 when that's out.

**Pull request closed without merging**
