### PR TITLE
bigloo 4.3h

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
`ld: library not found for -lunistring`

**Comment by Moisan** [comment]
```
bigloo/pthread/bglpthread.java:126: error: invalid use of a restricted identifier 'yield'
      yield();
      ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
1 error
```

**Comment by alebcay** [comment]
Note that `bigloo` does build its own copy of `libunistring`, so I'm not sure if linking to system `libunistring` is the right move here.

**Comment by Moisan** [comment]
Good point. I'll try first fixing the Java issue by putting it as a running dependency. Then we can try to put back the building of `libunistring`.

**Comment by Moisan** [comment]
Ok I still cannot get it to work. I don't have this error locally so I wonder if setting a minimum java version would help.

**Comment by alebcay** [comment]
Same here. I am also not having any errors locally.

**Pull request closed without merging**
