### PR TITLE
gnupg: add option to enable large secmem

### PR DESCRIPTION
**Pull request by adam-moss**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
We've been here before, have we not? https://github.com/Homebrew/homebrew-core/pull/12145

**Comment by DomT4** [comment]
Posted my prior comment too soon, apologies.

We've been here [before](https://github.com/Homebrew/homebrew-core/pull/12145). Honestly would prefer to not see this as an option even, but at least it's not on by default. I repeat myself from the earlier thread because at some point I'm sure someone will try to turn it on by default 😅.

**Comment by adam-moss** [comment]
Ha ha yes I agree, having it on by default was not the best idea I could've had 😊 

I do now actually have a use case for it as an option however, so I would (personally) like to see it available, rather than having to maintain a separate tap.

As it is only applicable to `--batch` users, which I didn't clarify the last time, then there isn't any impact on anyone that does enable it and doesn't use `--batch`

**Comment by ilovezfs** [comment]
I'd like to see us get rid of _all_ options but I won't let ideology stand in the way here.

**Comment by ilovezfs** [comment]
I changed it to the upstream description in `configure --help`

**Comment by DomT4** [comment]
As long as it isn't enabled by default & doesn't mislead users into thinking they actually _need_ this or that it is even necessarily desirable for the extreme majority of use cases I don't have a strong objection, essentially.

**Comment by ilovezfs** [comment]
Thanks @adam-moss. Use your new toy well.

**Comment by adam-moss** [comment]
Much appreciated folks 🥇

**Pull request merged**
