### PR TITLE
rbenv: use new `Utils.git_short_head`

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See #68805

(Syntax-only since it only affects head builds)

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by SeekingMeaning** [comment]
Off-topic: is it still recommended to use squash merges?

**Comment by carlocab** [comment]
If you need to squash, yes. If a PR already has the right commit format then rebase-and-merge is fine.

**Comment by SeekingMeaning** [comment]
Ah okay, thanks

**Comment by carlocab** [comment]
I think the issue was clarified here: https://github.com/Homebrew/brew/pull/10178

**Pull request merged**
