### PR TITLE
dcd 0.13.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by dtrodrigues — COMMENTED** [review]
Can the test use `free_port` instead of hard-coding `9167`?

**Comment by chenrui333** [comment]
Sounds about right, doing it now.

**Review by dtrodrigues — APPROVED** [review]
Thanks for updating the test.

**Comment by chenrui333** [comment]
Thanks for the suggestion. 👍

**Pull request closed without merging**
