### PR TITLE
Linking against libraries when building libtorrent

### PR DESCRIPTION
**Pull request by devos50**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
The configure-based build system for `libtorrent-rasterbar` should determine automatically what flags are supposed to be used to link against system frameworks, if they want to use them. That they do not is a bug in libtorrent, and should be reported to them.

Forcing `LDFLAGS` in the homebrew formula is a hack. We may accept it as a temporary measure, but the root problem needs to be found and fixed. Please open a bug report for the issue, and once it is confirmed, add a comment in the formula to link to that bug report.

**Comment by fxcoudert** [comment]
Upstream developer states that (https://github.com/arvidn/libtorrent/issues/3784#issuecomment-528287872):

> The supported build systems are boost build and cmake

so we should move the build to use `cmake`, which should in turn fix the issue.

**Comment by devos50** [comment]
@fxcoudert I will have a look at it 👍

**Comment by devos50** [comment]
I will open a new PR with my changes.

**Pull request closed without merging**
