### PR TITLE
yarn 1.2.1

### PR DESCRIPTION
**Pull request by DanBuild**
Created with `brew bump-formula-pr`.

---

This PR was automatically created via a script. Contact @Daniel15 with any questions.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Daniel15 https://yarnpkg.com/en/ still says 1.2.0

**Comment by ilovezfs** [comment]
:tada: says 1.2.1 now

**Comment by ilovezfs** [comment]
Thanks @DanBuild :robot:!

**Comment by Daniel15** [comment]
> @Daniel15 yarnpkg.com/en still says 1.2.0


Sorry about that... The website build takes 5-10 minutes to run,  and these PRs are sent at the same time as the website update occurs, so there can be a brief delay :)

**Comment by ilovezfs** [comment]
@Daniel15 no worries. I'll keep that in mind next time!

**Pull request merged**
