### PR TITLE
bat 0.14.0

### PR DESCRIPTION
**Pull request by treuherz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by treuherz** [comment]
The Actions run hit an ["unexpected error"](https://github.com/Homebrew/homebrew-core/actions/runs/85823587) which I've bounced over to GH support. It might be related to the [current incident](https://www.githubstatus.com/incidents/2y6v4ltq26g7) or might just be transient, but either way I don't see a way to trigger a re-run 🤔

**Comment by Bo98** [comment]
Probably is related to the current issues. I can't re-run it either, so you'll have to rebase and force push to try and trigger another build.

**Comment by treuherz** [comment]
Same thing again. I've subscribed to the status issue, might be better to just wait until that turns green

**Comment by Bo98** [comment]
Seems to work now. Thanks!

**Pull request closed without merging**
