### PR TITLE
lc0: rebuild without -march=native

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

~~**TESTING**~~

### CODE REVIEW

**Comment by cho-m** [comment]
Rebuild works on self-hosted `CPU: octa-core 64-bit broadwell`, so probably another SIMD issue.

**Comment by Bo98** [comment]
> **EDIT:** Logs show nothing for SIMD and only related code is currently not enabled. Only thing I see as potential issue is `-march=native` is passed to underlying compiler.

The compiler shim should filter this out anyway, unless `ENV.runtime_cpu_detection` is called.

**Comment by cho-m** [comment]
> > **EDIT:** Logs show nothing for SIMD and only related code is currently not enabled. Only thing I see as potential issue is `-march=native` is passed to underlying compiler.
> 
> The compiler shim should filter this out anyway, unless `ENV.runtime_cpu_detection` is called, so this shouldn't make a difference unless the shim is being bypassed.

I downloaded the logs and they were being weren't being removed.

macOS logs:
```
clang++ called with: -Ilc0.p -I. -I../.. -I../../src -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework/Headers -I/usr/local/Cellar/eigen/3.4.0_1/include/eigen3 -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework/Headers -flto -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wthread-safety -march=native -DUSE_BLAS -DNO_PEXT -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework -isystem../../third_party -MD -MQ lc0.p/src_main.cc.o -MF lc0.p/src_main.cc.o.d -o lc0.p/src_main.cc.o -c ../../src/main.cc
superenv added:    -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang++ -Ilc0.p -I. -I../.. -I../../src -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework/Headers -I/usr/local/Cellar/eigen/3.4.0_1/include/eigen3 -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework/Headers -flto -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wthread-safety -march=native -DUSE_BLAS -DNO_PEXT -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework -isystem../../third_party -MD -MQ lc0.p/src_main.cc.o -MF lc0.p/src_main.cc.o.d -o lc0.p/src_main.cc.o -c ../../src/main.cc -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
```

Linux logs:
```
g++-11 called with: -Ilc0.p -I. -I../.. -I../../src -I/home/linuxbrew/.linuxbrew/Cellar/eigen/3.4.0_1/include/eigen3 -I/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/include -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -march=native -DUSE_OPENBLAS -DUSE_BLAS -DNO_PEXT -pthread -isystem../../third_party -MD -MQ lc0.p/src_utils_commandline.cc.o -MF lc0.p/src_utils_commandline.cc.o.d -o lc0.p/src_utils_commandline.cc.o -c ../../src/utils/commandline.cc
superenv added:    -isystem/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include
superenv executed: g++-11 -Ilc0.p -I. -I../.. -I../../src -I/home/linuxbrew/.linuxbrew/Cellar/eigen/3.4.0_1/include/eigen3 -I/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/include -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -march=native -DUSE_OPENBLAS -DUSE_BLAS -DNO_PEXT -pthread -isystem../../third_party -MD -MQ lc0.p/src_utils_commandline.cc.o -MF lc0.p/src_utils_commandline.cc.o.d -o lc0.p/src_utils_commandline.cc.o -c ../../src/utils/commandline.cc -isystem/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include
```

**Comment by Bo98** [comment]
Sounds like a serious regression that would explain the various tests failing. I'll have a look.

**Comment by Bo98** [comment]
Oh right, we don't strip args for `ninja` - only `make`. I think it's time to expand that.

**Comment by Bo98** [comment]
https://github.com/Homebrew/brew/pull/12990

I guess we'll see how many builds this breaks.

**Comment by Bo98** [comment]
Just a revision bump should hopefully be enough now.

**Comment by cho-m** [comment]
Snippet of macOS logs:
```
clang++ called with: -Ilc0.p -I. -I../.. -I../../src -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework/Headers -I/usr/local/Cellar/eigen/3.4.0_1/include/eigen3 -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework/Headers -flto -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wthread-safety -march=native -DUSE_BLAS -DNO_PEXT -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework -isystem../../third_party -MD -MQ lc0.p/src_benchmark_backendbench.cc.o -MF lc0.p/src_benchmark_backendbench.cc.o.d -o lc0.p/src_benchmark_backendbench.cc.o -c ../../src/benchmark/backendbench.cc
superenv removed:  -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -O3 -Wthread-safety -march=native
superenv added:    -pipe -w -Os -march=nehalem -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang++ -pipe -w -Os -march=nehalem -Ilc0.p -I. -I../.. -I../../src -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework/Headers -I/usr/local/Cellar/eigen/3.4.0_1/include/eigen3 -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework/Headers -flto -fcolor-diagnostics -DNDEBUG -std=c++17 -DUSE_BLAS -DNO_PEXT -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenCL.framework -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Accelerate.framework -isystem../../third_party -MD -MQ lc0.p/src_benchmark_backendbench.cc.o -MF lc0.p/src_benchmark_backendbench.cc.o.d -o lc0.p/src_benchmark_backendbench.cc.o -c ../../src/benchmark/backendbench.cc -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
```

No Linux logs available, but I assume it behaved similarly.

Also, Linux CI runner ran on Broadwell CPU this time, which is what we usually run on Self-Hosted, so I don't expect any CI issues (I think last native-build problems happened with Skylake or later CPUs, maybe due to AVX512 support and other features)

**Comment by Bo98** [comment]
> Also, Linux CI runner ran on Broadwell CPU this time

Yes, I've seen the GitHub-hosted Linux runners switch between a couple of CPU microarchitectures over at Homebrew/brew.

**Pull request closed without merging**
