### PR TITLE
fio 3.20

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fio] Error 1
```

**Comment by sitsofe** [comment]
@chenrui333 I believe this is a bug in Apple's XCode 11.4 (see https://openradar.appspot.com/FB7647406 ). I'm unsure how Apple can sensibly provide `-no_weak_imports` if they are going to change system headers to depend on weak linking being available (see https://github.com/mono/mono/issues/19393#issuecomment-606852342 ).

If homebrew no longer supports macOS 10.11 or lower then I'd recommend just nobbling the configure test over in https://github.com/axboe/fio/blob/63a4b9cca4ba3aa4101051402cbbe946ced17a49/configure#L341 for now...

**Comment by chenrui333** [comment]
not actively working on this, closing the PR now.

**Comment by jonathancross** [comment]
@sitsofe @chenrui333 Is such _"nobbling"_ the correct approach?

**Comment by sitsofe** [comment]
@jonathancross I guess you don't like my use of that word or wouldn't have scare quoted it :-(

Anyway, I say yes it is the correct approach for now - I would hope that some future Apple update undoes this breakage but only time will tell. If in (say) 8 months Apple keeps this behaviour then fio upstream can just say "we don't support macOS 10.11 or lower any more" and throw the check and flag usage away.

**Comment by jonathancross** [comment]
Sorry, didn't mean to scare quote it :-)
I just figured I shouldn't change the suggested course of action with my own interpretation of the funny word.

**Pull request closed without merging**
