### PR TITLE
luajit: apply upstream patch to devel

### LINKED ISSUE #1274: luajit --devel compiled with options that break correctness
# Please follow the general troubleshooting steps first:
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

The issue is tracked and explained in depth on this issue that I filed against luaJIT.
https://github.com/LuaJIT/LuaJIT/issues/180

Some aspect of the formula's build process causes the compiled artifact to use AVX instead of integer operations which clobber a register than LuaJIT expects to be available. This problem cannot be reproduced without changing the `CCOPT_x64` make flag to `-march=native` when building from source.

This leads to wildly incorrect behavior on trivial examples.

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Also:
- Switch to using a versioned release for devel rather than one which moves around constantly. We're trying to move in this direction because the end goal is to bottle devel as well, which we can't do if those can move around.
- Fix the dylib vanilla symlinking to work for stable/devel.
- Minor code compacting.

Closes #1274.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍 :shipit:?

**Comment by DomT4** [comment]
Hoping someone who reported the original issue can help test the fix since I can't reproduce the original error locally even before the change.

**Comment by MikeMcQuaid** [comment]
@DomT4 I'd maybe just 🚢 it and hope.

**Comment by DomT4** [comment]
If I don't hear anything back over the next 24 hours or so I'll push it and see what happens in terms of response.

**Pull request merged**
