### PR TITLE
imessage-exporter 0.1.9 (new formula) 

### PR DESCRIPTION
**Pull request by ReagentX**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@ReagentX why do you need to submit same PRs three times?

**Comment by ReagentX** [comment]
Can't rebase merge or squash from web UI

**Comment by chenrui333** [comment]
> Can't rebase merge or squash from web UI

You should be able to use codespace to do it.

**Comment by ReagentX** [comment]
I don't know what that is

**Comment by chenrui333** [comment]
> I don't know what that is

https://github.com/features/codespaces

**Comment by chenrui333** [comment]
like I said before, the merge commit wont do well in the homebrew-core setup.

**Comment by ReagentX** [comment]
Codespaces doesn't solve the problem: 
image

**Comment by chenrui333** [comment]
> Codespaces doesn't solve the problem: image

https://docs.github.com/en/codespaces/developing-in-codespaces/developing-in-a-codespace

**Comment by ReagentX** [comment]
I understand that, but without a shell, you can't rewind commits

**Comment by chenrui333** [comment]
isn't this shell?
image

**Comment by ReagentX** [comment]
I don't see that.

**Comment by chenrui333** [comment]
> I don't see that.

what does that mean?

**Comment by ReagentX** [comment]
CI looks good, what else needs to happen here?

**Pull request closed without merging**
