### PR TITLE
sqlite 3.27.2, dbhash 3.27.2, sqldiff 3.27.2, sqlite-analyzer 3.27.2

### PR DESCRIPTION
**Pull request by tommyang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tommyang** [comment]
@BrewTestBot test this please

**Comment by tommyang** [comment]
@BrewTestBot test this please

**Comment by tommyang** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
On Mojave and Sierra, we have:
- `streamlink` failure, fixed in 3811abef100a9d13da070072cef38f1082756fb2
- `bzt` failure

High Sierra machine crashed hard :(

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by lembacon** [comment]
💚! Merging.

**Comment by lembacon** [comment]
Thanks @tommyang!

**Pull request closed without merging**
