### PR TITLE
datree 1.6.26

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
upstream claimed the issue is resolved now, https://github.com/datreeio/datree/issues/782

But I am still seeing some problem

```
$ curl -I https://datree.io/
HTTP/2 301
server: openresty
date: Wed, 14 Sep 2022 00:39:01 GMT
content-type: text/html
content-length: 166
location: https://www.datree.io/

$ curl -I https://www.datree.io/
HTTP/2 301
server: openresty
date: Wed, 14 Sep 2022 00:39:03 GMT
content-type: text/html
content-length: 166
cache-control: private
content-security-policy: frame-ancestors 'self'
location: https://datree.io/
x-frame-options: SAMEORIGIN
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-iad-kcgs7200146-IAD
x-cache: MISS
x-cache-hits: 0
x-timer: S1663115944.562973,VS0,VE31
vary: x-wf-forwarded-proto
x-cluster-name: us-east-1-prod-edge-blue
```

**Comment by shimont** [comment]
Hi, I'm Shimon from Datree. I've implemented some fixes from our DNS + Webflow side. 
Could you please invalidate DNS and try again?
Thank you very much for your help

**Comment by SMillerDev** [comment]
We can't really invalidate DNS on our CI runners, but I can run it again.

**Review by Moisan — APPROVED** [review]

**Comment by chenrui333** [comment]
@shimont looks like it is good now 🎉

**Pull request closed without merging**
