### PR TITLE
gnuplot, mlt, pcl, qscintilla2, vtk: switch to Qt 6

### PR DESCRIPTION
**Pull request by fxcoudert**
vtk supports Qt 6 since the 9.2 branch

### CODE REVIEW

**Comment by fxcoudert** [comment]
So `siril` depends on `gnuplot`, which depends on `qt@5`. Sigh.

**Comment by fxcoudert** [comment]
gnuplot works if you give it the right paths to Qt 6. Kind of ugly, but does the job.

**Comment by fxcoudert** [comment]
Octave failure reported upstream: https://savannah.gnu.org/bugs/index.php?64498
I mean, Qt 6 is not supported in the latest release, but even with HEAD where it is supported, it fails anyway because of the lack of .pc files :(

I've also noticed that octave actually warns heavily against using gnuplot as a backend, so maybe we'd be better off removing that dependency (and migrating it to Qt 6 later). I've opened a PR for that: https://github.com/Homebrew/homebrew-core/pull/138117

**Comment by fxcoudert** [comment]
On macOS: only octave is now failing, and dynare because it needs octave.
On Linux: I forget to make my gnuplot changes mac-only, so it failed.

**Comment by fxcoudert** [comment]
Linux failure is due to `pyqt` not having a Linux bottle since https://github.com/Homebrew/homebrew-core/pull/126023 (and see follow-up investigation in https://github.com/Homebrew/homebrew-core/pull/126565, which was no conclusive).

**Review by SMillerDev — APPROVED** [review]

**Comment by mmuetzel** [comment]
Coming late to the party.

Fwiw, Octave doesn't link to gnuplot. It's calling the executable (via a one-way pipe). So, in theory it should be possible to use a gnuplot that links to Qt6 libraries together with an Octave that links to Qt5 libraries. (That is if Homebrew allows to install both versions of Qt at the same time.)
If you'd still want to build Octave with the (deprecated) gnuplot graphics toolkit or not is an independent question.

**Pull request merged**
