### PR TITLE
libelf: revision for ARM

### PR DESCRIPTION
**Pull request by fxcoudert**
Trying to bottle on ARM

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
checking build system type... configure: error: /bin/sh ./config.sub -apple-darwin20.2.0 failed
configure: WARNING: cache variable ac_cv_build contains a newline
```

**Comment by fxcoudert** [comment]
Try passing an explicit `--build` triplet

**Comment by fxcoudert** [comment]
```
checking build system type... Invalid configuration `aarch64-apple-darwin20.2.0': machine `aarch64-apple' not recognized
```

**Review by jknoetzke — COMMENTED** [review]
I am getting the same result on my M1 MBP after applying this patch:

```
==> ./configure --prefix=/opt/homebrew/Cellar/libelf/0.8.13_1 --disable-compat --build=aarch64-apple-darwin20.3.0
Last 15 lines from /Users/justin/Library/Logs/Homebrew/libelf/02.configure:
checking the coffee machine... empty - operator may not work as expected
checking whether 64-bit ELF support is sufficient... yes
checking whether to include 64-bit support... yes
checking whether versioning support is sufficient... yes
checking whether to include versioning support... yes
checking whether NLS is requested... yes
checking for dgettext... no
checking for catgets... yes
checking for gencat... /usr/bin/gencat
checking for gmsgfmt... msgfmt
checking for xgettext... xgettext
checking for catalogs to be installed... de
checking for gettext in -lintl... no
checking build system type... Invalid configuration `aarch64-apple-darwin20.3.0': machine `aarch64-apple' not recognized
configure: error: /bin/sh ./config.sub aarch64-apple-darwin20.3.0 failed
```

Has anyone made any headway on this ?

**Comment by jknotzke** [comment]
I downloaded the source for libelf, and if I do the following

echo 'echo arm-apple-darwin' > config.sub
./configure --prefix=/opt/homebrew/Cellar/libelf/0.8.13_1 --disable-compat
make

It can get it to build.

**Comment by carlocab** [comment]
Bottled in 2f6beae5992bfa43891b72264f2c39995ca9d10b.

**Pull request closed without merging**
