### PR TITLE
gh 2.11.0

### PR DESCRIPTION
**Pull request by mislav**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by bayandin** [comment]
I guess `gh` started to print version output to stderr (probably because of https://github.com/cli/cli/pull/5698), if that is ok we need to add `2>&1` to version command.

**Comment by mislav** [comment]
@bayandin Whoops, I'm sorry if there was a regression. But locally I see version output printed to stdout as before: 
```
$ bin/gh version 2>/dev/null
gh version 2.11.0 (2022-05-24)
https://github.com/cli/cli/releases/tag/v2.11.0
```

**Comment by mislav** [comment]
Ah! It's the `--version` flag that's going to stderr now! So there is a regression.

We could amend the test to do `gh version` instead of `gh --version`, but I think we might also push a bugfix release for this and supersede this PR.

**Comment by bayandin** [comment]
> We could amend the test to do `gh version` instead of `gh --version`, but I think we might also push a bugfix release for this in gh and supersede this PR.

I don't mind either of these solutions; I will leave this up to you. Feel free to amend or close the PR.

**Pull request closed without merging**
