### PR TITLE
pypy3 5.7.1

### PR DESCRIPTION
**Pull request by jeethu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tdsmith** [comment]
Hi! Thanks for the pull request.

We haven't pulled pypy3.5 yet because the pypy download page says that it's beta-quality and we don't accept beta releases in the formula's stable (default) spec.

On the other hand, several people have asked for it, it's almost inconceivable that anybody would want the old 3.2-compatible pypy3, and I've used it for routine work without any hiccups, so maybe it's time to move ahead.

**Comment by fxcoudert** [comment]
Let's ship this!

@jeethu could you please confirm (by local testing) that the `--without-bootstrap` option still works?

**Comment by jeethu** [comment]
@fxcoudert Thanks! I had to change it a bit to support `--without-bootstrap`. It needs either `pycparser` or `cffi` (which includes `pycparser`) installed. The bootstrap `pypy` ships with it `cffi` while the system `python` doesn't.

It takes about 70 minutes to build with the `--without-bootstrap` option on my late 2016 touch-bar retina MBP (2.9 Ghz i7, 16GB RAM).

**Comment by ilovezfs** [comment]
I'm confused about CI here. It looks like it took 1 hr 11 min on Sierra and El Capitan, but  2 hr 17 min on Yosemite. Do anyone have any idea why?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Review by fxcoudert — APPROVED** [review]

**Comment by tdsmith** [comment]
@ilovezfs Dunno, maybe clang got better?

@jeethu Awesome; thanks for this!

**Pull request closed without merging**
