### PR TITLE
needle 0.14.0

### PR DESCRIPTION
**Pull request by tianskylan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tianskylan** [comment]
Looks like a dependency failed to build on 10.13. Not sure if it's just a sporadic issue.
Is there a way to ask CI to test again?

**Comment by tianskylan** [comment]
Failure similar to https://github.com/Homebrew/homebrew-core/pull/26958

**Comment by Bo98** [comment]
> however the error message appears to be building with `MacOSX10.14.sdk` .

This is normal for `depends_on :xcode`. The latest Xcode on 10.13 does not contain the 10.13 SDK.

The issue however was it was getting some information from `/usr/include` and some information from `<SDK>/usr/include`. I've fixed that in https://github.com/Homebrew/brew/commit/ae6c58c7bc9913bfb40bb865d36a3898e77925ac and have restarted the CI run.

**Comment by Bo98** [comment]
Merged now - thanks!

**Comment by tianskylan** [comment]
@Bo98 Thank you so much for the quick fix and merge!

**Pull request closed without merging**
