### PR TITLE
swagger-codegen 2.3.1

### PR DESCRIPTION
**Pull request by wing328**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@wing328 the build fails with Java 9.

**Comment by wing328** [comment]
@ilovezfs let me look into it...

**Comment by ilovezfs** [comment]
@wing328 cool. Shall I merge as-is so that we're back to a working build?

**Comment by wing328** [comment]
@ilovezfs Does it work with both JDK7 and JDK8? If yes, I think we can go ahead to merge it and we'll figure out the JDK9 issue later.

**Comment by ilovezfs** [comment]
We've been specifically requiring Java 8 for this one since Dec 23. The reason is that `1.7+` would use Java 9 if the user happens to have it installed, whereas `1.8` will use Java 8 even if Java 9 is installed. There's no way to say less than or equal to Java 8.

**Comment by wing328** [comment]
If there's no way to specify only Java 1.7 and 1.8, then I think we've no choice but to merge this before we look into the problem with JDK1.9

(2.3.1 includes fixes to make the project compatible with Java 1.7 again)

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for the upgrade @wing328! :rocket:

**Pull request closed without merging**
