### PR TITLE
remove namebench

### PR DESCRIPTION
**Pull request by slhck**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

namebench has not been updated upstream since 2011 and does not work under Python 3.x, so it is almost useless to keep in Homebrew. It will likely only cause a bad experience for end users, since it installs fine, but errors out on execution with:

      File "/usr/local/Cellar/namebench/1.3.1/libexec/bin/namebench", line 28
        print '* Your Python version (%s) is too old! Please upgrade to 2.6+!' % your_version
              ^
    SyntaxError: invalid syntax

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you `disable!` instead? That's a much nicer experience for users.

**Comment by slhck** [comment]
Ah, I didn't know about this. Reading up on it, according to Homebrew's criteria:

> A formula should be removed if it does not meet our criteria for acceptable formulae or versioned formulae, has a non-open-source license, or has been disabled for over a year.

The criteria for acceptable formulae again state that:

> The software in question must (…) be maintained (…) [and] work without patching on all supported macOS releases

So for me it seems like it's a candidate for deletion.

But sure, I can change this to become a deprecation instead.

**Comment by SMillerDev** [comment]
With `disable!` for the current date it's no longer usable, same as a deletion. Users just get a much better error message when they try to install it (and it'll show up in the API).

**Comment by bayandin** [comment]
I'd say we should make it `depends_on :macos # Due to Python 2` and deprecate it (instead of disabling it due to lack of support). 

>   File "/usr/local/Cellar/namebench/1.3.1/libexec/bin/namebench", line 28
>     print '* Your Python version (%s) is too old! Please upgrade to 2.6+!' % your_version
>           ^
> SyntaxError: invalid syntax

@slhck `namebench` should use python2, and you shouldn't get this error. What command do you run exactly?

**Comment by slhck** [comment]
I just ran

    brew install namebench

and then

    namebench

**Comment by slhck** [comment]
I checked again and it seems that (well, in hindight it's obvious that) `namebench` is using `python` and not `python2`, so it uses my symlinked Python 3 from pyenv. So when I do:

    pyenv global system

and then run `namebench`, it still works.

I'll close this and provide a deprecation notice.

**Pull request closed without merging**
