### PR TITLE
jpeg-xl 0.10.1

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>### Added
 - decoder API: added `JxlDecoderGetBoxSizeContents` for getting the size of the
   content of a box without the headers.
 - encoder API: implemented new api functions for streaming encoding.

### Changed / clarified
 - decoder/encoder API: return failure when surface allocation fail.

 **Note:** This release is for evaluation purposes and may contain bugs, including security bugs, that may not be individually documented when fixed. See the [SECURITY.md](SECURITY.md) file for details. Always prefer to use the latest release.
 
Please provide feedback and report bugs [here](https://github.com/libjxl/libjxl/issues).</pre>
</details>

### CODE REVIEW

**Comment by miccal** [comment]
Resource checked via https://github.com/libjxl/libjxl/tree/v0.10.0/third_party and points to https://github.com/webmproject/sjpeg/tree/e5ab13008bb214deb66d5f3e17ca2f8dbff150bf, hence does not need updating.

**Comment by fxcoudert** [comment]
```
Error: 68 failed steps!
brew test --retry --verbose brogue
brew test --retry --verbose cataclysm
brew test --retry --verbose cdogs-sdl
brew test --retry --verbose chromaprint
brew test --retry --verbose corsixth
brew test --retry --verbose dosbox-staging
brew test --retry --verbose dsda-doom
brew test --retry --verbose enigma
brew test --retry --verbose faircamp
brew test --retry --verbose fceux
brew linkage --test ffmpeg
brew test --retry --verbose ffmpeg
brew test --retry --verbose ffmpegthumbnailer
brew test --retry --verbose ffms2
brew test --retry --verbose freedink
brew linkage --test gdal
brew test --retry --verbose gdal
brew linkage --test geeqie
brew test --retry --verbose geeqie
brew test --retry --verbose gifify
brew test --retry --verbose gifski
brew test --retry --verbose gmt
brew test --retry --verbose gource
brew linkage --test graphicsmagick
brew test --retry --verbose gstreamer
brew linkage --test imagemagick
brew test --retry --verbose instead
brew linkage --test libsail
brew test --retry --verbose logstalgia
brew test --retry --verbose mapserver
brew test --retry --verbose mgba
brew test --retry --verbose minidlna
brew test --retry --verbose mpd
brew test --retry --verbose mpv
brew test --retry --verbose notcurses
brew test --retry --verbose openai-whisper
brew test --retry --verbose opencv
brew test --retry --verbose openimageio
brew test --retry --verbose osmcoastline
brew test --retry --verbose pc6001vx
brew test --retry --verbose pdal
brew test --retry --verbose pdfsandwich
brew test --retry --verbose pianobar
brew test --retry --verbose pioneer
brew test --retry --verbose qcli
brew test --retry --verbose scrcpy
brew linkage --test sdl2_image
brew test --retry --verbose sdl2_image
brew test --retry --verbose sdlpop
brew test --retry --verbose simple-tiles
brew test --retry --verbose siril
brew test --retry --verbose solarus
brew test --retry --verbose spek
brew test --retry --verbose supertux
brew test --retry --verbose timg
brew test --retry --verbose unpaper
brew linkage --test vapoursynth-imwri
brew test --retry --verbose vapoursynth-imwri
brew test --retry --verbose vapoursynth-sub
brew test --retry --verbose vcs
brew test --retry --verbose vgmstream
brew linkage --test vips
brew test --retry --verbose vips
brew test --retry --verbose visp
brew test --retry --verbose widelands
brew test --retry --verbose zelda-roth-se
brew test --retry --verbose zsdx
brew test --retry --verbose zsxd
```

Need to go through these and revision bump some things: sdl2_image ffmpeg vips gdal geeqie graphicsmagick imagemagick libsail vapoursynth-imwri

**Comment by miccal** [comment]
Thank you @fxcoudert.

**Comment by fxcoudert** [comment]
Looking good, but was missing one linux-only revbump: webkitgtk
Re-running one last time, skipping recursive dependents.

**Review by cho-m — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
