### PR TITLE
hashcat 3.30

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
I wonder if they meant to introduce that trailing whitespace and carriage return...

```
==> ./hashcat -m 0 --potfile-disable --quiet 098f6bcd4621d373cade4e832627b4f6 /tmp/hashcat-test-20170109-66883-5cvd1e/my.dict
Error: hashcat: failed
<"098f6bcd4621d373cade4e832627b4f6:test"> expected but was
<"098f6bcd4621d373cade4e832627b4f6:test\n\r                                                          ">.
```

**Comment by ilovezfs** [comment]
We're running chomp already, so it was probably just reformatting I'd think ...

**Comment by woodruffw** [comment]
That makes sense. I'm always mixing `chomp` and `strip` up :sweat_smile:

**Comment by nijikon** [comment]
hashcat/hashcat#974

**Comment by iamehiz** [comment]
i tried using hashcat but i got this

> hashcat -m 400 -a 0 /root/hash.txt /root/crak.txt
> hashcat (v3.20) starting...
> 
> clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
> 
> clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
> 
> No devices found/left
> 
> Started: Thu Jan 19 05:48:34 2017
> Stopped: Thu Jan 19 05:48:34 2017

**Comment by philsmd** [comment]
Hey,
one of the hashcat devs here.

I had the chance today to get access to a OSX (Sierra) mac mini from a friend to test this "problem".
My conclusion is that this is completely unrelated to hashcat.
It is just a homebrew + sandboxing (sandbox.rb) permission error within your tests.

I manage to quickly put together an improved/working version of the tests/formula:
```
class Hashcat < Formula
  desc "World's fastest and most advanced password recovery utility"
  homepage "https://hashcat.net/hashcat/"
  url "https://hashcat.net/files/hashcat-3.30.tar.gz"
  sha256 "3acd1d783f13183c57383069403de0554534ac2b06a30e7e078544e524f940d2"

  bottle do
    sha256 "7b3326c6130d3a9efece4fea418653e3a1519ace066fe808a4ee172036cb9b92" => :sierra
    sha256 "8b949ce43ea720d7556ab6bea03193c9b7d680e5139fe813192330d2b9b6138a" => :el_capitan
    sha256 "779e7022d29291278cff532258596b74586a134d64819869854d3f5cb333ee50" => :yosemite
  end

  depends_on "gnu-sed" => :build

  # Upstream could not fix OpenCL issue on Mavericks.
  # https://github.com/hashcat/hashcat/issues/366
  # https://github.com/Homebrew/homebrew-core/pull/4395
  depends_on :macos => :yosemite

  def install
    system "make", "install", "CC=#{ENV.cc}", "PREFIX=#{prefix}"
  end

  test do
    binary = "hashcat"
    hash_type = "1500"     # -m 1500 = descrypt, DES(Unix), Traditional DES
    attack_mode = "3"      # mask attack
    hash = "48c/R8JAv757A" # from https://hashcat.net/wiki/example_hashes
    pass = "hashcat"
    mask = "?l?l?l?lcat"
    additional_arguments = " --force"           + # shouldn't be needed with a correct OpenCL installation
                           " --quiet"           + # we only need the hash:pass pair in the output
                           " --markov-disable"  + # we do not need markov
                           " --potfile-disable" + # we do not need to check/write the hashcat.potfile
                           " --logfile-disable" + # no need for logs
                           " --restore-disable" + # no need to restore the session
                           " --outfile-check-dir #{testpath} " # set a local outfile directory

    cmd = binary + " -m " + hash_type + " -a " + attack_mode + additional_arguments + hash + " " + mask 

    # suppress STDERR output
    cmd += " 2>/dev/null"

    assert_equal "#{hash}:#{pass}", shell_output(cmd).strip
  end
end
```

So the main problem was that the tests can't read/write outside of testpath. This is a restriction of sandbox.rb + homebrew and actually I wouldn't call this a hashcat problem.

The above modified test (which uses some further parameters) limits the file accesses to a bare minimum and therefore succeed.

---

BTW: what @iamehiz seems to be completely unrelated and most probably a faulty/corrupt/incorrect/missing OpenCL driver.

**Comment by nijikon** [comment]
@philsmd fair enough.

```

**Comment by nijikon** [comment]
Test fails.

```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170203-42012-7ed81n.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hashcat.rb
==> hashcat -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat 2>/dev/null
sh: line 1: 42023 Abort trap: 6           hashcat -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat 2> /dev/null
==> Sandbox log
Feb  3 18:32:08 kernel[0]: Sandbox: hashcat(42023) deny(1) file-write-create /Users/n/.hashcat/kernels/markov_le.353d3ad3.kernel
Error: hashcat: failed
<0> expected but was
<134>.
```

**Comment by philsmd** [comment]
Well, it works here.
Abort trap 6 seems to be an unrelated problem.

Does this command work independently (on the shell):
`hashcat -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat`
?
Please test

**Comment by nijikon** [comment]
```
balrog:homebrew-core n$ hashcat -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat
Abort trap: 6
balrog:homebrew-core n$ echo $?
134
```

**Comment by philsmd** [comment]
Does this problem also happen with newest version directly compiled from hashcat's git (https://github.com/hashcat/hashcat/ )?
What happens if you tune it a little bit, say with "-w 1" added to the command line?

**Comment by nijikon** [comment]
hashcat 3.30
```
balrog:~ n$ hashcat -w 1 -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat
Abort trap: 6
balrog:~ n$ echo $?
134
balrog:~ n$ hashcat -n 1 -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat
Abort trap: 6
balrog:~ n$ echo $?
134
```
hashcat head
```
balrog:~ n$ hashcat -w 1 -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat
Abort trap: 6
balrog:~ n$ echo $?
134
balrog:~ n$ hashcat -n 1 -m 1500 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable --outfile-check-dir /tmp/hashcat-test-20170203-42013-cy4a6h 48c/R8JAv757A ?l?l?l?lcat
Abort trap: 6
balrog:~ n$ echo $?
134
```

**Comment by philsmd** [comment]
This seems to be very specific to mac OSX (the trap: 6 error) and unfortunately I could not reproduce it with the mac mini (it just works even a full run of "hashcat -b" works).
Maybe as a temporarily fix we should switch to another hash type within the tests (maybe -m 8900), an example would be (from here: https://hashcat.net/wiki/example_hashes):
```
hash_type = "8900"     # -m 8900 = scrypt
attack_mode = "3"      # mask attack
hash = "SCRYPT:1024:1:1:MDIwMzMwNTQwNDQyNQ==:5FW+zWivLxgCWj7qLiQbeC8zaNQ+qdO0NUinvqyFcfo=" # from https://hashcat.net/wiki/example_hashes
pass = "hashcat"
mask = "?l?l?lhcat"
```

But of course you should first test it indipendently on the command line, e.g. something like:
```
hashcat -m 8900 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable 'SCRYPT:1024:1:1:MDIwMzMwNTQwNDQyNQ==:5FW+zWivLxgCWj7qLiQbeC8zaNQ+qdO0NUinvqyFcfo=' ?l?l?lhcat
a
```
It would be also helpful to have a full output of "hashcat -b" to see when these trap: 6 error occur exactly.
As far as I know it usually has to do with a hard restriction of the Apple OpenCL environment that permits to run the kernels for longer than some (let's say 10?) milliseconds.
If the kernel hasn't finished within this time, the operating systems basically forces a stop of the kernel-execution.

Maybe @matrix could hop in and help us to understand and resolve this problem (I'm completely lost when it comes to OSX-specific problems like this)?

**Comment by matrix** [comment]
Hi @philsmd,
there're some "hash mode" marked unstable on OSX, like 1500, due to broken OpenCL driver/compiler.
Please using other modes for testing, @jsteube already knows.

Thanks

**Comment by nijikon** [comment]
```

**Comment by nijikon** [comment]
```
pc6:homebrew-core n$ hashcat -m 8900 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable 'SCRYPT:1024:1:1:MDIwMzMwNTQwNDQyNQ==:5FW+zWivLxgCWj7qLiQbeC8zaNQ+qdO0NUinvqyFcfo=' ?l?l?lhcat
Abort trap: 6
```

**Comment by philsmd** [comment]
Thank you for your tests.

I have no solution for the trap: 6 error, but I think this improved formula might help to perform sufficient test that should always pass:
```
class Hashcat < Formula
  desc "World's fastest and most advanced password recovery utility"
  homepage "https://hashcat.net/hashcat/"
  url "https://hashcat.net/files/hashcat-3.30.tar.gz"
  sha256 "3acd1d783f13183c57383069403de0554534ac2b06a30e7e078544e524f940d2"

  bottle do
    sha256 "7b3326c6130d3a9efece4fea418653e3a1519ace066fe808a4ee172036cb9b92" => :sierra
    sha256 "8b949ce43ea720d7556ab6bea03193c9b7d680e5139fe813192330d2b9b6138a" => :el_capitan
    sha256 "779e7022d29291278cff532258596b74586a134d64819869854d3f5cb333ee50" => :yosemite
  end

  depends_on "gnu-sed" => :build

  # Upstream could not fix OpenCL issue on Mavericks.
  # https://github.com/hashcat/hashcat/issues/366
  # https://github.com/Homebrew/homebrew-core/pull/4395
  depends_on :macos => :yosemite

  def install
    system "make", "install", "CC=#{ENV.cc}", "PREFIX=#{prefix}"
  end

  test do
    #
    # General test settings
    #

    binary    = "./hashcat"
    pass      = "hash234"
    hash_type = "500" # -m 500 = md5crypt, MD5(Unix), FreeBSD MD5, Cisco-IOS MD5

    dict_file = "example.dict"
    hash_file = "example#{hash_type}.hash"

    additional_args = " --force" +         # shouldn't be needed with a correct OpenCL installation
                      " --quiet" +         # we only need the hash:pass pair in the output
                      " --potfile-disable" # we do not need to check or write the hashcat.potfile

    #
    # Copy some files to the test folder
    #

    # copy all files from share to test folder
    cp_r pkgshare.children, testpath

    # copy the example hash and the dictionary file to the test folder
    cp "#{doc}/#{hash_file}", testpath
    cp "#{doc}/#{dict_file}", testpath

    # copy the hashcat binary to test folder
    cp "#{bin}/#{binary}", testpath

    #
    # Test 1 (dictionary attack, -a 0):
    #

    hash = File.open(hash_file, "rb").read.strip

    attack_mode = "0"

    cmd = binary + " -m " + hash_type + " -a " + attack_mode + additional_args + " " + hash_file + " " + dict_file

    # suppress STDERR output
    cmd += " 2>/dev/null"

    assert_equal "#{hash}:#{pass}", shell_output(cmd).strip

    #
    # Test 2 (combinator attack, -a 1):
    #

    attack_mode = "1"

    dict1 = "dict1.txt"
    dict2 = "dict2.txt"

    File.write(dict1, pass[0..3])
    File.write(dict2, pass[4..-1])

    cmd = binary + " -m " + hash_type + " -a " + attack_mode + additional_args + " " + hash_file + " " + dict1 + " " + dict2

    # suppress STDERR output
    cmd += " 2>/dev/null"

    assert_equal "#{hash}:#{pass}", shell_output(cmd).strip

    #
    # Test 3 (mask attack, -a 3):
    #

    attack_mode = "3"

    mask = "?l?l?l" + pass[3..-1]

    cmd = binary + " -m " + hash_type + " -a " + attack_mode + additional_args + " " + hash_file + " " + mask

    # suppress STDERR output
    cmd += " 2>/dev/null"

    assert_equal "#{hash}:#{pass}", shell_output(cmd).strip

    #
    # Test 4 (hybrid attack, dict + mask, -a 6):
    #

    attack_mode = "6"

    mask = "?d?d?d"

    cmd = binary + " -m " + hash_type + " -a " + attack_mode + additional_args + " " + hash_file + " " + dict1 + " " + mask

    # suppress STDERR output
    cmd += " 2>/dev/null"

    assert_equal "#{hash}:#{pass}", shell_output(cmd).strip

    #
    # Test 5 (hybrid attack, mask + dict, -a 7):
    #

    attack_mode = "7"

    mask = "?l?l" + pass[2..3]

    cmd = binary + " -m " + hash_type + " -a " + attack_mode + additional_args + " " + hash_file + " " + mask + " " + dict2

    # suppress STDERR output
    cmd += " 2>/dev/nul"

    assert_equal "#{hash}:#{pass}", shell_output(cmd).strip
  end
end
```

Could you please test with this new hashcat.rb ?
Thanks

**Comment by Lutarisco** [comment]
Helo there! I'm sorry to interrupt about the update, but meanwhile, the hashcat-3.10.tar.gz file has changed its URL to `https://hashcat.net/files_legacy/hashcat-3.10.tar.gz`.
The actual URL in the v3.10 formula (`https://hashcat.net/files/hashcat-3.10.tar.gz`) now redirects to the hashcat's homepage, and so `brew install hashcat` (v3.10) downloads the homepage HTML, returning a SHA-256 mismatch.

However, a simple workaround to this (until the formula gets updated) is to download the file manually, replace the downloaded file (~/Library/Caches/Homebrew/hashcat-3.10.tar.gz) and re-run `brew install hashcat`.

I'm sorry if I don't belong here (and I'm quite sure of that), but I felt that it didn't worth it to open a new issue because the formula already needs to be updated.

**Comment by jsteube** [comment]
Wait, hashcat v3.10 is far outdated. Current version is v3.30 and soon
v3.40 will be released. I think the only correct update would be to update
hashcat version to latest version.

**Comment by ilovezfs** [comment]
@jsteube I think you've missed @Lutarisco's point, which was that the current formula is broken because the URL changed.

**Comment by jsteube** [comment]
It's an alternative solution. Instead update from

https://hashcat.net/files/hashcat-3.10.tar.gz

to

https://hashcat.net/files_legacy/hashcat-3.10.tar.gz

You should update to

https://hashcat.net/files/hashcat-3.30.tar.gz

**Comment by ilovezfs** [comment]
Yes, shipping this PR would also solve that problem, but we're not going to rush a PR review just because the prior URL happens to have changed for whatever reason.

**Comment by ilovezfs** [comment]
@jsteube I see above there are people getting abort trap 6. Is this the correct output?
```
iMac-TMP:~ joe$ hashcat -m 8900 -a 3 --force --quiet --markov-disable --potfile-disable --logfile-disable --restore-disable 'SCRYPT:1024:1:1:MDIwMzMwNTQwNDQyNQ==:5FW+zWivLxgCWj7qLiQbeC8zaNQ+qdO0NUinvqyFcfo=' ?l?l?lhcat
SCRYPT:1024:1:1:MDIwMzMwNTQwNDQyNQ==:5FW+zWivLxgCWj7qLiQbeC8zaNQ+qdO0NUinvqyFcfo=:hashcat
iMac-TMP:~ joe$
```

**Comment by ilovezfs** [comment]
@Lutarisco https://github.com/Homebrew/homebrew-core/pull/10226.

**Comment by jsteube** [comment]
Yeah that's correct. The trap 6 error is an issue from the OpenCL
runtime, not hashcat. That's why it's working for some and for some
other not.

**Comment by ilovezfs** [comment]
In that case, I suspect anyone getting abort trap 6 is going to see it with both 3.10 and 3.30. @nijikon can you confirm that this isn't actually regression?

**Comment by nijikon** [comment]
@ilovezfs with the test provided by @philsmd it works, so merging this for now. We will revisit when 3.40 will be available.

**Pull request closed without merging**
