### PR TITLE
rclone 1.53.3

### PR DESCRIPTION
**Pull request by mtrolley**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JayBrown** [comment]
I don't believe that the **deprecated** tag is correct for rclone. **FUSE** is *not* a requirement for rclone, and it's not even listed when you execute `brew info rclone`. The rclone utility works just fine without FUSE, and only offers the option to use it when it's present.

**Comment by SMillerDev** [comment]
> the alleged FUSE requirement is not even listed when you execute brew info rclone. 

That's because it was removed when we added the message. If you can disable the mount command you can remove the depreciation notice.

**Comment by trolley** [comment]
How do I re-trigger these failed tests?

**Comment by SMillerDev** [comment]
Well, they're failing because they can't find FUSE on the CI machines so that will have to be fixed. When you push the fix it'll run again.

**Comment by darthShadow** [comment]
@trolley I have merged the fix for this in the rclone formula. Please rebase with the master and that should get your tests passing again.

**Review by SMillerDev — APPROVED** [review]
Thanks @trolley  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
