### PR TITLE
protobuf 3.6.1

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
Blocked on `protobuf-swift` supporting `protobuf 3.6.1`.

**Comment by fxcoudert** [comment]
`protobuf` has 17,310 installs a month, `protobuf-swift` has 97. If `protobuf-swift` doesn't move to follow its "parent" package, at some point we'll have to leave it broken.

**Comment by JCount** [comment]
It turns out `protobuf-swift`'s build failure is easy to fix.
(I swear I was originally getting a different error 🤔...)

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
