### PR TITLE
pnpm 6.7.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Wanted to check on the version here.

The previous formula version (**6.7.5**) was a GitHub pre-release.

This PR version (**6.7.6**) is the newest Git tag.
Although it is not a pre-release, it is also not "GitHub Latest".

https://www.npmjs.com/package/pnpm still uses 6.7.4 as `latest` and marks 6.7.6 as `next`.

**Comment by chenrui333** [comment]
You are absolutely right, I wait a bit for the pnpm latest release.

**Comment by chenrui333** [comment]
We probably need to improve the npm registry livecheck later.

**Comment by chenrui333** [comment]
Now it is the latest release in github and npm registry

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
