### PR TITLE
clitest 0.4.0 (new formula)

### PR DESCRIPTION
**Pull request by mogeko**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]
Can you also ask them if they can make a new release? (it has been like two years since last one)

**Comment by mogeko** [comment]
> Can you also ask them if they can make a new release? (it has been like two years since last one)

I think its function is comprehensive and stable enough (even if its version is just `0.4.0`), so the author does not intend to add additional functions to it.

However, I will confirm whether the author is still maintaining this project.

**Comment by chenrui333** [comment]
> > Can you also ask them if they can make a new release? (it has been like two years since last one)
> 
> I think its function is comprehensive and stable enough (even if its version is just `0.4.0`), so the author does not intend to add additional functions to it.
> 
> However, I will confirm whether the author is still maintaining this project.

that is true.

**Review by chenrui333 — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by chenrui333** [comment]
@mogeko, thanks for your contribution to Homebrew! 🎉 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
