### PR TITLE
ffmpeg 3.4

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm enjoying the complete indifference to the openjpeg upgrades.

**Comment by zmwangx** [comment]
> I'm enjoying the complete indifference to the openjpeg upgrades.

No, it's included. It's just that I run bump first before making manual changes.

**Comment by ilovezfs** [comment]
ah ok

**Comment by zmwangx** [comment]
I'm slightly confused by the VDA situation, but according to my understanding we should leave it to autodetect now. Folks, correct me if I'm wrong.

**Comment by DomT4** [comment]
Question: Is it worth enabling `x265` as a `:recommended` option given Apple's new giant shove for HEVC?

**Comment by zmwangx** [comment]
Given how few devices can actually playback 4K HEVC at a reasonable speed, not sure about that.

**Comment by DomT4** [comment]
I don't have a strong opinion either way at this point. It was something I was throwing around in my head the other night & I decided it wasn't something I knew enough about `ffmpeg` to make a firm case around, heh.

I think you've mostly been the one handling `ffmpeg` for a while, so, whatever you think best I'm cool with.

**Comment by zmwangx** [comment]
> whatever you think best I'm cool with.

I honestly don't have the slightly clue how other people use FFmpeg, so take my opinions with a huge grain of salt. Anyway, x265 is crazy slow on my top end Mid-2015 MBP 15'' so if I really need to do H.265 encoding I push it to a server farm where I don't here the noise of grinding. IMO local H.265 encoding won't be remotely as popular as local H.264 encoding any time soon.

**Comment by zmwangx** [comment]
That said, analytics may have something to say about the popularity of x265.

**Comment by DomT4** [comment]
It doesn't look huge at this point. Standard `ffmpeg` reports 176,205 IORE hits, and beyond that `ffmpeg` installations that also explicitly request a `--with-x265` are:

5,211 IORE:
```
ffmpeg --with-fdk-aac --with-libass --with-sdl2 --with-x265 --with-freetype --with-libvorbis --with-libvpx --with-opus
```

2,779 IORE:
```
ffmpeg --with-fdk-aac --with-libass --with-tools --with-x265 --with-freetype --with-libvorbis --with-libvpx
```

If you broaden the scope to all install events we find 10,131 IE out of 577,719 total `ffmpeg` IE:
```
ffmpeg --with-fdk-aac --with-libass --with-sdl2 --with-x265 --with-freetype --with-libvorbis --with-libvpx --with-opus
```

**Comment by DomT4** [comment]
So `--with-x265` gets involved in 1.754% of all total known `ffmpeg` installations.

**Comment by zmwangx** [comment]
Let’s not make it recommended then. I’m on my phone now so can’t check, but I got the impression that back when I compiled in x265, I had to recompile FFmpeg for new x265 quite often. Maybe it’s more stable now though so ABI compat isn’t broken that often.

**Comment by ilovezfs** [comment]
:record_button:

**Comment by slhck** [comment]
Thanks everyone for the quick update.

Just to add my two cents here regarding x265:

* HEVC still seems to be a niche application, being [unsupported in most browsers](https://en.wikipedia.org/wiki/HTML5_video#Browser_support). Also, encoding is slow. And there is little support for option-mapping in `ffmpeg`, making it a second class citizen, even compared to `libvpx`.
* HEVC is never a default choice in ffmpeg when auto-selecting codecs for a given output format.
* That said, on the FFmpeg wiki we do have `x265` building and linking instructions in our compilation guides for Ubuntu and other platforms. But people are less likely to update such builds, so if you've found x265 to regularly break ABI, better not include it.

**Comment by zmwangx** [comment]
> That said, on the FFmpeg wiki we do have x265 building and linking instructions in our compilation guides for Ubuntu and other platforms. But people are less likely to update such builds, so if you've found x265 to regularly break ABI, better not include it.

There's no problem building and linking against x265; we already have such an option. I was referring to the fact that (at least once upon a time) x265 dylib version changed quite frequently, so if we ship FFmpeg with it by default, we need to revision-bump FFmpeg every time that happens, which means a recompilation for people who use FFmpeg but never touch x265.

**Comment by retokromer** [comment]
The solution chosen is the good one IRL, in my opinion. Thank you very much indeed!

**Comment by ilovezfs** [comment]
@zmwangx should we be passing `--enable-x86asm`? See https://github.com/macports/macports-ports/commit/d29cf89b54354dec54e7d6bd1e0322078a9580e4

**Comment by zmwangx** [comment]
@ilovezfs Pretty sure x86asm is enabled as long as you have a reasonable nasm (we do) or yasm and don't explicitly `--disable-x86asm`. It seems the x86asm theater in the Portfile is due to MacPorts supporting ppc (even then I'm not sure why they don't leave it to autodetection)?

**Comment by ilovezfs** [comment]
@zmwangx yes that seems strange that they don't leave it to autodetection.

**Pull request closed without merging**
