### PR TITLE
psftools: regenerate `configure`

### PR DESCRIPTION
**Pull request by carlocab**
This is needed for bottling on Monterey.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Either it doesn't apply or it's not enough

**Comment by carlocab** [comment]
Ah, I missed the `autoconf` call. We can't patch `configure` since that gets regenerated.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Can you also make sure the original issue is reported?

**Comment by carlocab** [comment]
I've put it on my to-do list, but that's getting quite long now...

**Pull request merged**
