### PR TITLE
scipy 1.10.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
`Error: Can't create reproducible gzip file without a valid mtime`

**Comment by carlocab** [comment]
From [here](https://github.com/Homebrew/brew/blob/a222a5bbc83923e4c9c09ed0ff07dfe64cf7d863/Library/Homebrew/utils/gzip.rb#L27-L36):

```ruby
      # Ideally, we would just set mtime = 0 if SOURCE_DATE_EPOCH is absent, but Ruby's
      # Zlib::GzipWriter does not properly handle the case of setting mtime = 0:
      # https://bugs.ruby-lang.org/issues/16285
      #
      # This was fixed in https://github.com/ruby/zlib/pull/10. Set mtime to 0 instead
      # of raising exception once we are using zlib gem version 1.1.0 or newer.
      if mtime.to_i.zero?
        raise ArgumentError,
              "Can't create reproducible gzip file without a valid mtime"
      end
```

The latest `mtime` in the scipy tarball is `0`, so bottling it errors out. I wonder if we should just set the `mtime` to `1` instead of bailing out here instead.

**Comment by fxcoudert** [comment]
The ruby bug was closed in 2019. Shouldn't we simply remove that whole block and let mtime be zero?

**Comment by carlocab** [comment]
Our zlib gem is not new enough. The error message was added recently in https://github.com/Homebrew/brew/pull/14316.

**Comment by fxcoudert** [comment]
> Our zlib gem is not new enough

Can't we update?

**Comment by carlocab** [comment]
The gem is provided by Apple. Vendoring one might be complicated since it links with the system `libz`. It seems simpler to just truncate the mtime TBH.

**Comment by alebcay** [comment]
Just to confirm my understanding, the bottle build here is trying to use `SOURCE_DATE_EPOCH` but that is 0 (presumably because the source mtime is also 0)? Is there some way to derive a more useful nonzero source mtime and use that as `SOURCE_DATE_EPOCH` instead?

**Comment by carlocab** [comment]
> Just to confirm my understanding, the bottle build here is trying to use `SOURCE_DATE_EPOCH` but that is 0 (presumably because the source mtime is also 0)? Is there some way to derive a more useful nonzero source mtime and use that as `SOURCE_DATE_EPOCH` instead?

The newest file in the source tarball has an mtime of 0:
```
❯ curl -LSfs https://files.pythonhosted.org/packages/84/a9/2bf119f3f9cff1f376f924e39cfae18dec92a1514784046d185731301281/scipy-1.10.1.tar.gz | tar x
❯ fd --type=file -X stat --format='%Y' | sort -u
0
```

Not sure what else we'd use as a basis for `SOURCE_DATE_EPOCH` other than the [newest mtime](https://github.com/Homebrew/brew/blob/ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f/Library/Homebrew/download_strategy.rb#L127-L130).

**Review by MikeMcQuaid — APPROVED** [review]
Looks good once https://github.com/Homebrew/brew/pull/14723 is merged.

**Pull request closed without merging**
