### PR TITLE
infer 0.16.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`gr-osmosdr` and `gnuradio` need revision bumps

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
The revision of infer should also be updated.

**Comment by fxcoudert** [comment]
Trying to add `--disable-sandboxing` to `opam init`.

**Pull request closed without merging**
