### PR TITLE
comby 1.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by rvantonder** [comment]
Hi homebrew friends. I'm releasing a new version to hopefully unblock the issues in https://github.com/Homebrew/homebrew-core/pull/71605#issuecomment-782928677. Once I get this built, it should be good to go for OCaml 4.10.2/ARM by adding `revision 1` if I understand correctly. Thanks for your patience!

CC @carlocab @andreypopp

**Comment by rvantonder** [comment]
Note: most builds appear green, but there is build issue for 10.14 I've run into before--I think it is a flake and might disappear by rebuilding the GH action, but that's less than ideal. Will see if I can get rid of the flake.

**Comment by rvantonder** [comment]
> Error: SHA256 mismatch
Expected: 1ce4c8b0b5b60c1522c52a70a5db86071c8e37729d84cc9d47ad91a15c664818
  Actual: c843c44dd75160454f49c9fad3785e840762e73ada35bd40adf394cb5933a505
  
I updated the release with to fix the `10.14` issue, which is causing the sha mismatch. I was hoping he change would be picked up and then force pushed for the new sha, but looks like that's not the case. I'm not sure if that happens periodically. Any way I can help with this?

**Comment by rvantonder** [comment]
Well, the good news is the update fixed the `10.14` issue. The bad news is I'm seeing the arm failure for `11-arm`. 

> Uncaught exception:
    (Unix.Unix_error "Invalid argument" ftruncate "")

This is strange because after looking at what the code is doing here, it should be OK. Unfortunately I can't debug the root cause without an arm machine. Strictly speaking, `comby` doesn't depend on the code that is executed here, so I will update things to fix that, but will take another day.

@chenrui333 I can open a separate PR as author so that I can update the sha with changes, if we close this one (I don't want you to have to bother you for pushing updates). Up to you, let me know.

**Comment by carlocab** [comment]
`comby` hadn't been built on ARM previously, so this can be merged as is, actually.

You can fix the ARM problem in another version bump. How does that sound?

**Comment by rvantonder** [comment]
Oh great, let's do that! I'll fix the arm issue in the version bump then. Thanks @carlocab .

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Great. This should be merged automatically shortly.

**Pull request closed without merging**
