### PR TITLE
openjdk@8: depend on awk

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I was able to get `openjdk@8` to build locally on Intel Monterey by adding a build dependency on `gawk`.  Without this the build fails with a locale processing error during a call to `/usr/bin/awk`.

**Comment by Bo98** [comment]
For future reference, what precisely was the error you were getting?

**Comment by danielnachun** [comment]
This is the error that happens when using the system `awk`:
```
## Starting jaxp
Compiling 1868 files for BUILD_JAXP
Updating jaxp/dist/lib/src.zip
/usr/bin/awk: towc: multibyte conversion failure on: '�vard Wigtil)'
```
I'm guessing it doesn't like a Unicode character in that name.

**Comment by carlocab** [comment]
It's weird that that's a problem on Monterey and not earlier, though. We can probably also skip dependent tests on this one, as this should no changes on anything we've currently built.

**Comment by danielnachun** [comment]
I deliberately set the dependency to Monterey-only to see if this fails in Big Sur or Catalina.  If it does not I suppose this would mean there is some issue with the Monterey CLT, but I'm not sure.

**Comment by danielnachun** [comment]
Odd as this fix is, it does seem to only be needed for Monterey.  I wish we knew what Azul was doing to build this on ARM (https://cdn.azul.com/zulu/bin/zulu8.58.0.13-ca-jdk8.0.312-macosx_aarch64.tar.gz), but I haven't been able to find a patch or build parameters.  

@iMichka should we revision bump the handful of dependent failures on Linux here like we've done for OpenJDK 17?

**Comment by iMichka** [comment]
> @iMichka should we revision bump the handful of dependent failures on Linux here like we've done for OpenJDK 17?

I guess, yes. But didn't you just rebottle for the openjdk 17 ones? If yes, then please do that instead as we just need to ship new bottles.

**Comment by carlocab** [comment]
Yes, let's just rebottle formulae that just need a `JAVA_HOME` fix. If multiple Linux users complain about having installed a bottle with an invalid `JAVA_HOME` then we can rev bump the specific formula complained about.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
I wonder if a similar fix would work for `openjdk@11`.

**Comment by Bo98** [comment]
OpenJDK 11 doesn't build on Monterey because the latest version with the fixes hasn't been merged yet.

**Comment by blattersturm** [comment]
I'm getting the same issue when trying to install `openjdk@8` (as needed for `apktool`), but even if I do `brew install gawk` before it still fails. Do I need to apply the changes in this PR, and where?

Or does @github-actions marking this as 'stale' mean the PR is wrong or this issue is not going to get fixed?

**Comment by blattersturm** [comment]
Thank you @github-actions for removing the label! @carlocab apparently marked this as approved so can you merge it too?

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Merged as-is. Failures on Linux are unrelated.

I triggered a build for Intel macOS 12 here: https://github.com/Homebrew/homebrew-core/actions/runs/1644663556

**Pull request merged**
