### PR TITLE
libxc 4.2.3

### PR DESCRIPTION
**Pull request by edditler**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Please do not remove the `bottle` block. It will be regenerated automatically when we merge the pull-request.

**Comment by edditler** [comment]
This turned out to be less straight-forward than I hoped 😅

I created the PR for CP2K: https://github.com/Homebrew/homebrew-core/pull/36155
You can take care of squashing the commits for this PR when merging, right?

**Comment by fxcoudert** [comment]
@edditler the revision bump needs to be a second commit in the same pull request, otherwise they can't be tested together

**Comment by edditler** [comment]
@fxcoudert So, would I then include another commit here, bumping CP2K to 6.1, or would that be a separate PR?

**Comment by fxcoudert** [comment]
@edditler include the version update of CP2K as the second commit of this PR

**Comment by fxcoudert** [comment]
Thanks @edditler for the pull request!

**Pull request closed without merging**
