### PR TITLE
jenkins-job-builder 1.6.1

### PR DESCRIPTION
**Pull request by sagar-khanna**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Upgrading the version to the latest. Have tested it locally using brew edit and then brew install. Also ran brew audit and it reported no errors/issues.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Installation is failing: https://bot.brew.sh/job/Homebrew%20Core/9078/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_jenkins_job_builder/

**Comment by sagar-khanna** [comment]
@MikeMcQuaid  - I'll try it on a new machine.
It worked for me locally though and I'm running the latest version now.
Will test and get back.

**Comment by MikeMcQuaid** [comment]
@sagar-khanna Any news on this? There's also conflicts that need addressed now. Thanks!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Afraid this needs to be rebased against the current master!

**Comment by fxcoudert** [comment]
No news from the author, and the PR has bitrotten. Closing.

**Pull request closed without merging**
