### PR TITLE
fdroidserver 1.1.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
20:11:33   Running setup.py install for Pillow: finished with status 'error'
20:11:33 Cleaning up...
20:11:33   Removing source in /private/tmp/pip-req-build-07bv8_fe
20:11:33 Removed build tracker '/private/tmp/pip-req-tracker-l08jm52q'
20:11:33 ERROR: Command "/usr/local/Cellar/fdroidserver/1.1.1/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-07bv8_fe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-z2dcizv1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/fdroidserver/1.1.1/libexec/bin/../include/site/python3.7/Pillow" failed with error code 1 in /private/tmp/pip-req-build-07bv8_fe/
20:11:33 Exception information:
20:11:33 Traceback (most recent call last):
20:11:33   File "/usr/local/Cellar/fdroidserver/1.1.1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
20:11:33     status = self.run(options, args)
20:11:33   File "/usr/local/Cellar/fdroidserver/1.1.1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
20:11:33     use_user_site=options.use_user_site,
20:11:33   File "/usr/local/Cellar/fdroidserver/1.1.1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
20:11:33     **kwargs
20:11:33   File "/usr/local/Cellar/fdroidserver/1.1.1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
20:11:33     spinner=spinner,
20:11:33   File "/usr/local/Cellar/fdroidserver/1.1.1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
20:11:33     % (command_desc, proc.returncode, cwd))
20:11:33 pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/fdroidserver/1.1.1/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-07bv8_fe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-z2dcizv1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/fdroidserver/1.1.1/libexec/bin/../include/site/python3.7/Pillow" failed with error code 1 in /private/tmp/pip-req-build-07bv8_fe/
20:11:33 
20:11:33 ==> Formula
20:11:33 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fdroidserver.rb
```

**Comment by AllanWang** [comment]
@chenrui333 will you be updating this PR?

**Comment by alebcay** [comment]
See previous attempt: https://github.com/Homebrew/homebrew-core/pull/38475

**Comment by chenrui333** [comment]
Has been fixed per #42980, #43196

**Pull request closed without merging**
