### PR TITLE
openstackclient 5.3.1

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Rylan12** [comment]
I bumped some versions for resources. Everything seems to work fine locally.

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
Thanks, @SeekingMeaning!

By the way, please let me know if you would rather I didn't push my own minor changes to your PRs (I should have asked before I started doing it). I've felt comfortable because you're a regular contributor who has many open PRs and I figured you wouldn't mind a little help on these smaller changes, but, if you would rather do them yourself, do let me know and I won't continue.

**Comment by SeekingMeaning** [comment]
I don’t mind

**Comment by Rylan12** [comment]
Thanks for the response! Of course, let me know if this changes 👍

**Comment by Rylan12** [comment]
This was closed in dc38f2742bc5824b84600101f61a2f51176bf0cb. Not sure why the commit didn't close the PR

**Comment by SeekingMeaning** [comment]
https://status.github.com

**Comment by Rylan12** [comment]
Ah yes, that's probably it. Thanks

**Pull request closed without merging**
