### PR TITLE
calceph 3.4.0 (new formula)

### PR DESCRIPTION
**Pull request by gastineau**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can you please squash everything into a single commit, on top of Homebrew's master? (no merge commit)

**Comment by dawidd6** [comment]
Also, you should name the commit: `calceph 3.4.0 (new formula)`

**Comment by SMillerDev** [comment]
The license for this formula doesn't seem to be OSI approved. That would mean we can't ship this in homebrew.

**Comment by gastineau** [comment]
THis licence is approved by OSI.
You can have a look to https://opensource.org/licenses/CECILL-2.1

**Comment by SMillerDev** [comment]
That one isn't on the webpage though. The page says: 
> This software is governed by the CECILL-C, CECILL-B or CECILL version 2 license

**Comment by gastineau** [comment]
This is a mistake in the webpage: the tarball is governed by CECILL-C, CECILL-B or CECILL version 2.1. We fix the webpage.
So for homebrew distribution, the chosen licence "CECILL version 2.1" in order to be compatible with homebrew-core.

**Pull request closed without merging**
