### PR TITLE
apache-arrow: expose parquet cmake configuration

### PR DESCRIPTION
**Pull request by ziyi-yan**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
symlink `lib/cmake/parquet` to `lib/cmake/arrow` to expose Parquet to cmake's find_package().

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why does cmake need to find parquet?

**Comment by ziyi-yan** [comment]
CMake's `find_package()` search [these paths](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure) to find packages. CMake can find arrow in `lib/cmake/arrow` without further configuration.
But, if we don't export parquet's cmake configurations via `lib/cmake/parquet`, CMake cannot find without explicit passing additional variable definitions, such as Parquet_DIR. We can test it using [this example project](https://github.com/apache/arrow/tree/master/cpp/examples/parquet/parquet-arrow) from arrow.

**Comment by carlocab** [comment]
What is the relationship between Parquet and Apache Arrow? Is it a subproject of Apache Arrow, or a separate project that the `apache-arrow` formula is vendoring? Why doesn't Apache Arrow create this symlink in their build system?

I just want to rule out the possibility that this is a bug in CMake or Apache Arrow's build system. Because if it is, then it should be fixed there and not papered over.

**Comment by ziyi-yan** [comment]
> What is the relationship between Parquet and Apache Arrow? Is it a subproject of Apache Arrow, or a separate project that the `apache-arrow` formula is vendoring? Why doesn't Apache Arrow create this symlink in their build system?

According to README.md of [its legacy repository](https://github.com/apache/parquet-cpp), Parquet (C++ library) has been merged into Arrow repository. I'm not sure why it didn't create this symlink.

> I just want to rule out the possibility that this is a bug in CMake or Apache Arrow's build system. Because if it is, then it should be fixed there and not papered over.

Apache Arrow installations on other OS usually separate packages. For example, in Ubuntu, they are `libarrow-dev` and `libparquet-dev`. How we handle such a situation in Homebrew?

**Comment by ziyi-yan** [comment]
> Should we have a separate formula for apache-parquet?

AFAIK, Parquet C++ library from `apache-arrow` always rely on Arrow. Parquet can also easily be found by `pkg-config`.
```bash
~ $ pkg-config --libs --cflags parquet
-I/opt/homebrew/Cellar/apache-arrow/3.0.0_4/include -L/opt/homebrew/Cellar/apache-arrow/3.0.0_4/lib -lparquet -larrow
```
So, I think we can just export Parquet's CMake configurations from this formula to make building CMake projects easier.

**Comment by carlocab** [comment]
Why isn't this a bug in CMake's `find_package`, if `pkg-config` can find Parquet just fine?

**Comment by SMillerDev** [comment]
So it's a problem with the way apache arrow distributes their components then.

**Pull request closed without merging**
