### PR TITLE
vultr: fix build with Go 1.16

### PR DESCRIPTION
**Pull request by nklmilojevic**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/homebrew-core/issues/47627 references this

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @nklmilojevic. For your future PRs, please put the name of the formula first in the commit message. For example, your message here might have been: `vultr: remove GOPATH for 1.16`.

Thanks again!

**Comment by nklmilojevic** [comment]
Sorry for the second push - was meant to be in the other branch for terraform-inventory.

**Comment by SMillerDev** [comment]
```
 ==> go build -trimpath -o /usr/local/Cellar/vultr/2.0.2/bin/vultr
vultr.go:6:2: cannot find package "github.com/JamesClonk/vultr/cmd" in any of:
	/usr/local/Cellar/go/1.15.8/libexec/src/github.com/JamesClonk/vultr/cmd (from $GOROOT)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/src/github.com/JamesClonk/vultr/cmd (from $GOPATH)
```

**Comment by nklmilojevic** [comment]
So weird - I've tried it locally (this and both https://github.com/Homebrew/homebrew-core/pull/71409) and it worked.

**Comment by nklmilojevic** [comment]
Found the issue - the formula has url https://github.com/JamesClonk/vultr/archive/v2.0.2.tar.gz which doesn't contain go.mod, but the master branch has it.

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
