### PR TITLE
goofys 0.11

### PR DESCRIPTION
**Pull request by gaul**
Changelog:

https://github.com/kahing/goofys/releases/tag/v0.0.11

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@andrewgaul do the `go_resource` need to be updated?

**Comment by ilovezfs** [comment]
I've updated the resources.

**Comment by ilovezfs** [comment]
@andrewgaul Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
