### PR TITLE
walkmod 3.0.0

### PR DESCRIPTION
**Pull request by rpau**
Here the upgrade of the new walkmod formula version

### CODE REVIEW

**Comment by woodruffw** [comment]
`test` is failing:

```
ERROR [main] - /private/tmp/walkmod-test-20170212-85567-cep15k/walkmod-core/walkmod.xml is invalid. Please, execute walkmod with -e to see the details.
ERROR [main] - /private/tmp/walkmod-test-20170212-85567-cep15k/walkmod-core/walkmod.xml is invalid. Please, execute walkmod with -e to see the details.
Exception in thread "main" java.lang.NullPointerException
	at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
	at org.walkmod.WalkModFacade.check(WalkModFacade.java:303)
	at org.walkmod.commands.CheckCommand.execute(CheckCommand.java:40)
	at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:173)
	at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:198)
Error: walkmod: failed
Failed executing: /usr/local/Cellar/walkmod/3.0.0/bin/walkmod check
```

**Comment by rpau** [comment]
Hi, one question: the test is downloading data from internet and storing it into the $HOME directory (.ivy). Is that enabled by the CI? Otherwise I will need to change the test.

I am running the same with the installed brew formula and works. 

How can I rerun the build in your Jenkins?

Thanks.

**Comment by MikeMcQuaid** [comment]
> Hi, one question: the test is downloading data from internet and storing it into the $HOME directory (.ivy). Is that enabled by the CI? Otherwise I will need to change the test.

That's fine but it needs to respect `ENV["HOME"]` which points to a different location.



> How can I rerun the build in your Jenkins?

Push a new commit.

**Comment by rpau** [comment]
Hi, are needed any special privileges to create that file?

/Users/brew/.ivy2/cache/resolved-org.walkmod-walkmod-license-applier-plugin-caller-working.xml

**Pull request closed without merging**
