### PR TITLE
fonttools 3.1.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Jolg42** [comment]
@ilovezfs I tried to update it locally with `brew edit fonttools` and your changes but when I want to link it I have this error:

```
Linking /usr/local/Cellar/fonttools/3.1.2...
Error: Could not symlink bin/pyftinspect
Target /usr/local/bin/pyftinspect
already exists. You may want to remove it:
  rm '/usr/local/bin/pyftinspect'

To force the link and overwrite all conflicting files:
  brew link --overwrite fonttools

To list all files that would be deleted:
  brew link --overwrite --dry-run fonttools
```

Is it normal? How can I fix it?

**Comment by Jolg42** [comment]
I tried to delete the file but it's asking to delete another one...

**Comment by Jolg42** [comment]
Maybe it's because of this line mentioning it 

`option "with-pygtk", "Build with pygtk support for pyftinspect"` 
https://github.com/Homebrew/homebrew-core/blob/bddbf56e127dc9c7d9fca266dcf57abd3f77a305/Formula/fonttools.rb#L17

But I don't if it's safe to delete all these files :(

**Comment by Jolg42** [comment]
After deleting 
```
/usr/local/bin/pyftinspect
/usr/local/bin/pyftmerge
/usr/local/bin/pyftsubset
```
It worked :) (brew test is ok & command working)

**Comment by ilovezfs** [comment]
Closing in favor of #5613.

**Pull request closed without merging**
