### PR TITLE
vowpal-wabbit 9.0.0

### PR DESCRIPTION
**Pull request by bassmang**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@bassmang you can use `brew bump-formula-pr` command to update the formula next time, it would take care of the `revision` management.

**Comment by ngam** [comment]
@carlocab @bassmang this error could be fixed by either restricting fmt and spdlog one version down (7.x for fmt, and 1.8.x for spdlog) or patch it up with this PR https://github.com/VowpalWabbit/vowpal_wabbit/pull/3667 when it is ready

**Comment by ngam** [comment]
Kinda weird it worked earlier and the deps are up to date here: https://formulae.brew.sh/formula/vowpal-wabbit#default

**Comment by ngam** [comment]
`brew install vowpal-wabbit --HEAD` works totally fine and results in `9.0.0 (git commit: 9471e85c8)` while using the `fmt--8.1.1_1` and `spdlog--1.9.2`. I am so confused how this is actually working!

**Comment by ngam** [comment]
> `brew install vowpal-wabbit --HEAD` works totally fine and results in `9.0.0 (git commit: 9471e85c8)` while using the `fmt--8.1.1_1` and `spdlog--1.9.2`. I am so confused how this is actually working!

Ohhhhh maybe because the underlying update to this already took place in: https://github.com/VowpalWabbit/vowpal_wabbit/pull/3669#event-5982736148

**Comment by jackgerrits** [comment]
I'm planning on putting out a patch release this week with the change you mentioned. Is it worth waiting for that instead of pinning a version or using a patch here?

**Comment by ngam** [comment]
> I'm planning on putting out a patch release this week with the change you mentioned. Is it worth waiting for that instead of pinning a version or using a patch here?

I would just wait, thanks @jackgerrits!!

**Pull request closed without merging**
