### PR TITLE
gnu-getopt 2.35.1

### PR DESCRIPTION
**Pull request by samford**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by samford** [comment]
```
failed: brew test --verbose git-flow-avh

        Testing git-flow-avh
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200217-69981-1lrr6pj.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-flow-avh.rb --verbose
==> git init
Initialized empty Git repository in /private/tmp/git-flow-avh-test-20200217-69982-2le3hk/.git/
==> /usr/local/Cellar/git-flow-avh/1.12.3/bin/git-flow init -d
Using default branch names.
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master] 
Branch name for "next release" development: [develop] 

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

This is the same sort of error that we've seen in other formulae that execute `git init` and git commands in the test. The latest discussion regarding this is in #50296, where I [commented](https://github.com/Homebrew/homebrew-core/pull/50296#issuecomment-586734220) asking about how this issue might be addressed in a general fashion without fixing individual tests as I've been doing (using git config).

**Comment by MikeMcQuaid** [comment]
This should be addressed by https://github.com/Homebrew/brew/pull/7046

**Comment by samford** [comment]
With the related change in Homebrew/brew merged, everything passed on CI this time around.

**Comment by MikeMcQuaid** [comment]
Thanks for checking this and rerunning it @samford!

**Comment by MikeMcQuaid** [comment]
@samford Can you email me when you get the chance at mike@mikemcquaid.com? I cannot find a public email for you. Thanks!

**Pull request closed without merging**
