### PR TITLE
netpbm 10.86.31

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
Revision bumped `gammaray` due to linkage failure on `12-arm64`.

**Comment by carlocab** [comment]
Ah, this isn't the kind of linkage failure that is fixed by a rev bump:
```
  Files with missing rpath:
    /opt/homebrew/Cellar/gammaray/2.11.3/GammaRay.app/Contents/PlugIns/gammaray/2.11/qt5_15-arm64/target/position/libgammaray_geopositioninfosource.so
```
This failure will have been pre-existing and is actually due to changes in `brew linkage` and not from the `netpbm` version bump. See https://github.com/Homebrew/brew/pull/12584.

This will require some tweaking of the flags passed to `cmake`, so is probably better handled in a separate PR.

**Comment by nandahkrishna** [comment]
Oops, didn't look at the actual `brew linkage` output. Thanks.

**Comment by carlocab** [comment]
That's fine; sorry for dropping a `brew linkage` change and not telling anyone 😅

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
