### PR TITLE
workflows/automerge: skip PRs with `pre-release` label

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Addressing https://github.com/Homebrew/homebrew-core/pull/128868#issuecomment-1516780334.

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]

**Review by p-linnane — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Agreed! As mentioned, though, I think we should ideally have this only apply to draft PRs and `CI-published-bottle-commits`

**Comment by carlocab** [comment]
> Agreed! As mentioned, though, I think we should ideally have this only apply to draft PRs and `CI-published-bottle-commits`

How about a job that makes PRs with these labels drafts? And marks them as ready for review upon removal?

**Comment by MikeMcQuaid** [comment]
> How about a job that makes PRs with these labels drafts? And marks them as ready for review upon removal?

I think we should just do that ourselves? It's not harder to mark something a draft than give it a label.

**Comment by carlocab** [comment]
> It's not harder to mark something a draft than give it a label.

It is to me! I always forget where the "mark as draft" link is, because it's in small text and nondescript. And I haven't found a way to mark PRs as draft with `gh`, whereas I already have aliases for quick addition/removal of common labels.

**Comment by MikeMcQuaid** [comment]
> It is to me! I always forget where the "mark as draft" link is, because it's in small text and nondescript. And I haven't found a way to mark PRs as draft with `gh`, whereas I already have aliases for quick addition/removal of common labels.

`gh pr create --draft`, `gh pr edit --draft`.

**Comment by carlocab** [comment]
😞

```
❯ gh pr edit --draft 128906
unknown flag: --draft

Usage:  gh pr edit [<number> | <url> | <branch>] [flags]

Flags:
      --add-assignee login      Add assigned users by their login. Use "@me" to assign yourself.
      --add-label name          Add labels by name
      --add-project name        Add the pull request to projects by name
      --add-reviewer login      Add reviewers by their login.
  -B, --base branch             Change the base branch for this pull request
  -b, --body string             Set the new body.
  -F, --body-file file          Read body text from file (use "-" to read from standard input)
  -m, --milestone name          Edit the milestone the pull request belongs to by name
      --remove-assignee login   Remove assigned users by their login. Use "@me" to unassign yourself.
      --remove-label name       Remove labels by name
      --remove-project name     Remove the pull request from projects by name
      --remove-reviewer login   Remove reviewers by their login.
  -t, --title string            Set the new title.
```

**Comment by ZhongRuoyu** [comment]
I agree that it's ideal to list fewer labels here, if possible. But currently, each of these labels does have its reason to be listed, IMO. For instance, to remove https://github.com/Homebrew/homebrew-core/labels/automerge-skip or https://github.com/Homebrew/homebrew-core/labels/new%20formula, we'll need to automatically convert those PRs to draft (which I think is pretty much debatable). Before we become clearer on the use of draft PRs: let's move this along.

**Comment by MikeMcQuaid** [comment]
> For instance, to remove [ automerge-skip](https://github.com/Homebrew/homebrew-core/labels/automerge-skip) `brew pr-automerge` will skip this pull request or [ new formula](https://github.com/Homebrew/homebrew-core/labels/new%20formula) PR adds a new formula to Homebrew/homebrew-core , we'll need to automatically convert those PRs to draft (which I think is pretty much debatable).

- `automerge-skip` should be set as draft manually 
- I don't see why a ✅ `new formula` should not be automerged

> And for [ pre-release](https://github.com/Homebrew/homebrew-core/labels/pre-release) Artifact is pre-release , it's because maintainers have been using this label for a long time, and I don't think we should expect everyone to remember to mark those PRs as draft.

Yes, we should expect people to mark these as draft. GitHub functionality is already changing and we've made a large number of changes this year which we've had for a long time.

Draft PRs are simply much safer. They cannot be merged without marking as draft. All the others can (and most have) be merged by a misclick or misreading.

**Comment by ZhongRuoyu** [comment]
> `automerge-skip` should be set as draft manually

Currently, the majority of `automerge-skip` PRs are actually those failing the commit style check. (Like this one itself.) And for those PRs, the label is added automatically. Should we automatically convert those to draft? (While adding labels require triage access, contributors are allowed to change the draft status without special permissions. That means we are actually giving contributors partial control over whether a PR can be merged.)

> I don't see why a ✅ `new formula` should not be automerged

We tend to be stricter with new formulae; `new formula` PRs often get two or more approvals before they are merged. Personally, I don't often `brew pr-publish` a new formula when I am the first reviewer because I do want a second eye on it.

**Comment by MikeMcQuaid** [comment]
> Currently, the majority of `automerge-skip` PRs are actually those failing the commit style check. (Like this one itself.)

Are we not able to autosquash those on merge CC @carlocab?

> That means we are actually giving contributors partial control over whether a PR can be merged.

Yes. That seems appropriate. A PR requires both the PR author agreeing it can be merged (setting not draft) and a maintainer (providing a ✅). This is how it works on most projects.

> Personally, I don't often `brew pr-publish` a new formula when I am the first reviewer because I do want a second eye on it.

There's other ways we can tackle this, I'd suggest, such as requiring a `Homebrew/core` review or creating a smaller team which we require reviews on before merge in these cases.

I appreciate that may not be entirely possible given the current GitHub branch protections we can use.

**Pull request merged**
