### PR TITLE
ktlint 0.43.2

### PR DESCRIPTION
**Pull request by shashachu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by shashachu** [comment]
hm.

**Comment by carlocab** [comment]
Try
```diff
diff --git a/Formula/ktlint.rb b/Formula/ktlint.rb
index fdb396bba4f..4fad693a37f 100644
--- a/Formula/ktlint.rb
+++ b/Formula/ktlint.rb
@@ -14,7 +14,10 @@ class Ktlint < Formula
   def install
     libexec.install "ktlint"
     (libexec/"ktlint").chmod 0755
-    (bin/"ktlint").write_env_script libexec/"ktlint", JAVA_HOME: Formula["openjdk@11"].opt_prefix
+    (bin/"ktlint").write_env_script libexec/"ktlint",
+                                    Language::Java.java_home_env("11").merge(
+                                      PATH: "#{Formula["openjdk@11"].opt_bin}:${PATH}",
+                                    )
   end
 
   test do
```

**Comment by shashachu** [comment]
Thanks @carlocab. Let me try one more time; I was having trouble attaching the proper binary to the release. If it still doesn't work I'll try your suggestion.

**Comment by carlocab** [comment]
Still the same error:
```
  /home/linuxbrew/.linuxbrew/Cellar/ktlint/0.43.2/libexec/ktlint: 3: exec: java: not found
```

**Comment by shashachu** [comment]
> Still the same error:
> 
> ```
>   /home/linuxbrew/.linuxbrew/Cellar/ktlint/0.43.2/libexec/ktlint: 3: exec: java: not found
> ```

Yup. Applied your changes. I'm pretty confused why it changed. 🤞

**Comment by carlocab** [comment]
> I'm pretty confused why it changed. 🤞

I don't think it did; this was probably just never tested properly on Linux before.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
