### PR TITLE
appscale-tools 3.6.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`The 'requests[security]<=2.19.1,>=2.16.0' distribution was not found and is required by appscale-tools`

**Comment by SMillerDev** [comment]
@igas could you also bump the `requests[security]` resource?

**Comment by SMillerDev** [comment]
@igas `The 'azure==2.0.0' distribution was not found and is required by appscale-tools` could you try installing it locally to see if all resources work now?

**Comment by igas** [comment]
Hm, ok...

But it's not in the queue https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/

**Comment by SMillerDev** [comment]
@brewtestbot test this please

**Comment by igas** [comment]
On the topic, it always worked for me locally with `brew install --build-from-source appscale-tools` but on CI I see what is missing.

**Pull request closed without merging**
