### PR TITLE
Convert elm-format, hpack, komposition, purescript, shellcheck to v2-build

### PR DESCRIPTION
**Pull request by athas**
This is part of the move away from the old DSL-ish way of writing
Haskell formulae.  See https://github.com/Homebrew/brew/pull/6974 for the discussion leading up to this.  The point of this PR is mostly to exercise the cabal-v2 approach, hopefully eventually leading to a good fix of https://github.com/Homebrew/homebrew-core/issues/48604. 

This change does not actually change what is built in the formulae.  As I understand it, this means that new revisions are *not* necessary.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by athas** [comment]
Looks like `purescript.rb` had a pre-existing wart in it (the homepage link wasn't `https://`).  Fixed that to make the CI (hopefully) go green.

**Comment by Bo98** [comment]
Can you separate them into diferent commits - one per formula?

**Comment by athas** [comment]
Nope, not for several weeks since my Mac is no longer easily accessible.

**Comment by Bo98** [comment]
Ok, don't worry - I'll handle it.

**Comment by Bo98** [comment]
Oops, I forgot about this. I'll do this in a moment.

**Comment by fishtreesugar** [comment]
I bump shellcheck's version in #52586, sorry for the disturbing.

**Comment by Bo98** [comment]
I'm going to merge this first. You will have to rebase your pull request.

**Pull request merged**
