### PR TITLE
mtools 4.0.18

### PR DESCRIPTION
**Pull request by ilovezfs**
punt with the UNUSED macro if ENV.cc is clang

### CODE REVIEW

**Comment by DomT4** [comment]
Can we report that as being problematic for Clang upstream?

**Comment by ilovezfs** [comment]
@DomT4 perhaps a better idea would be to do a check in superenv for whether the URL matches "gnu" and then slipstream in `fails_with :clang` if it does. :innocent:

**Comment by DomT4** [comment]
😆 However [distasteful Stallman](https://gcc.gnu.org/ml/gcc/2014-01/msg00247.html) personally finds Clang, most of the GNU folk have been happy enough to resolve Clang issues before thankfully.

**Comment by ilovezfs** [comment]
@DomT4 Yeah I just have [this dung pile](https://github.com/Homebrew/homebrew-core/pull/2137#issuecomment-227069300) in mind  and oh yeah [this one](https://github.com/Homebrew/formula-patches/pull/33), too.

**Comment by DomT4** [comment]
Heh. It is slightly annoying that so many of these are creeping in recently.

**Comment by ilovezfs** [comment]
It was reported: https://lists.gnu.org/archive/html/info-mtools/2014-02/msg00000.html

And ignored.

**Comment by DomT4** [comment]
Hilarious. I think GNU have a more formal bug reporting system beside mailing lists, maybe worth filing there as well 😕

**Comment by MikeMcQuaid** [comment]
:shipit:

**Pull request closed without merging**
