### PR TITLE
Added plist_options to be able to manage tomcat with `brew services`

### PR DESCRIPTION
**Pull request by Maskime**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
Dang, sorry this fell off the radar.  Could you just add `revision 1` underneath the homepage so it gets pushed out as an update to everyone?

**Comment by Maskime** [comment]
@dunn : It's dunn... (sorry for the dad joke)

**Comment by dunn** [comment]
Thanks! Could you also squash it into one commit and rebase?

**Comment by VonUniGE** [comment]
This pull request has been automatically closed but it's content is valuable and is needed by some users:
https://stackoverflow.com/questions/41871291/how-to-use-brew-service-to-start-tomcat
https://apple.stackexchange.com/questions/293163/how-do-i-add-tomcat-to-brew-services

As asked, I've squashed and rebased the proposed commits:
https://github.com/VonUniGE/homebrew-core-1/tree/patch-1

Do I need to open a new pull request or can you reopen this one?

**Comment by Maskime** [comment]
@VonUniGE : Thanks a lot ! I had forgot !

**Comment by dunn** [comment]
@VonUniGE if you do open a new PR please preserve authorship on the commit so @Maskime gets credit for their work.

**Comment by VonUniGE** [comment]
I would prefer to reopen the current pull request. Is it possible?

**Comment by VonUniGE** [comment]
@dunn Thank you for having reopened this pull request.
@Maskime Can you squash and rebase your commits, such that dunn can merge them into the master branch?

**Comment by Maskime** [comment]
@VonUniGE @dunn : should be ok now ?

**Comment by VonUniGE** [comment]
In my opinion, everything is OK for a merge.

**Comment by dunn** [comment]
Thank you both! Merged as 5faab57f3f61d4fc51e128db801195a437ccdcf2.

**Pull request closed without merging**
