### PR TITLE
Arcanist 2019 Week 25 (new formula)

### PR DESCRIPTION
**Pull request by zengxs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[Arcanist](https://github.com/phacility/arcanist) is command-line interface for [Phabricator](https://github.com/phacility/phabricator).

### CODE REVIEW

**Comment by javian** [comment]
Thank you for the submission @zengxs ! There is an issue with the versioning of this Formula since we accept only tagged releases see https://docs.brew.sh/Acceptable-Formulae and arcanist doesn't seem to be working with that and there we won't be able to include it in the core repository. I would suggest you create your own tap if you have a need to use it or check if someone else already have a homebrew version of it out there somewhere.

**Comment by zengxs** [comment]
Hi, @javian. Thank you for the information.

But I found the wikimedia's [arcanist repo](https://github.com/wikimedia/arcanist) has [tagged releases](https://github.com/wikimedia/arcanist/releases), and all commits of this repo are sync from upstream.

Could we use tags of wikimedia's arcanist repo in this formula?

**Comment by fxcoudert** [comment]
> Could we use wikimedia's tags in this formula?

That's not the same as if upstream releases / tags it.

**Comment by zengxs** [comment]
Ok, thanks! Maybe I should put the formula in my own tap.

**Pull request closed without merging**
