### PR TITLE
gedit 45.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  meson.build:29:2: ERROR: Command `/opt/homebrew/Library/Homebrew/shims/mac/super/git -C /private/tmp/gedit-20230623-11119-133i0cl/gedit-45.0 submodule update --init --recursive` failed with status 128.
```

**Review by nandahkrishna — COMMENTED** [review]
Need to do something like:
```diff
diff --git a/Formula/gedit.rb b/Formula/gedit.rb
index 8206019b333..772085374be 100644
--- a/Formula/gedit.rb
+++ b/Formula/gedit.rb
@@ -45,7 +45,8 @@ class Gedit < Formula
     ENV["XML_CATALOG_FILES"] = "#{etc}/xml/catalog"
     ENV.append "LDFLAGS", "-Wl,-rpath,#{lib}/gedit" if OS.linux?
 
-    system "meson", "setup", "build", *std_meson_args
+    meson_args = std_meson_args.map { |s| s.sub "release", "plain" }
+    system "meson", "setup", "build", *meson_args
     system "meson", "compile", "-C", "build", "--verbose"
     system "meson", "install", "-C", "build"
   end
```
to set the `buildtype` to `plain`. The FreeBSD Port does this too (see [here](https://cgit.freebsd.org/ports/tree/editors/gedit/Makefile#n41)).

This also needs `tepl >= 6.5.1`. Are we sure `gedit 45.0` is stable? CC @ZhongRuoyu who may be more knowledgeable about the `tepl` downgrade and version info.

**Comment by ZhongRuoyu** [comment]
> This also needs `tepl >= 6.5.1`.

`tepl` 6.5.1 (the latest version) is, according to upstream [^1], a development snapshot. It was downgraded from 6.5.1 to 6.4.0 in #130891 to fix #130859.

> Are we sure `gedit 45.0` is stable?

I can't really tell either, but I assume upstream maintainers are aware of the odd/minor version scheme [^1] used by `tepl`: https://gitlab.gnome.org/GNOME/gedit/-/issues/559#note_1739343

Let me file an upstream issue later today to confirm the status of `gedit` 45.0.

(Sorry for the late response here; I have limited access to my Mac but I'll be back soon.)

[^1]: https://gitlab.gnome.org/swilmet/tepl/-/blob/main/docs/more-information.md

**Comment by ZhongRuoyu** [comment]
Filed https://gitlab.gnome.org/GNOME/gedit/-/issues/564.

**Review by ZhongRuoyu — COMMENTED** [review]
`gedit` 45.0 [*is* a stable release](https://gitlab.gnome.org/GNOME/gedit/-/issues/564#note_1779263). `tepl` now has a new stable release (6.6.0), so this should be good after a rebase against #135295.

**Comment by Bo98** [comment]
> set the `buildtype` to `plain`

Alternative is https://gitlab.gnome.org/GNOME/gedit/-/merge_requests/160

**Comment by ZhongRuoyu** [comment]
#135295

**Pull request closed without merging**
