### PR TITLE
cutter 1.2.6

### PR DESCRIPTION
**Pull request by cosmo0920**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
I don't see this version here https://sourceforge.net/projects/cutter/files/

**Comment by cosmo0920** [comment]
> I don't see this version here https://sourceforge.net/projects/cutter/files/

Umm, I'll ask this issue to @kenhys.

**Comment by cosmo0920** [comment]
1.2.6 is appeared in : https://sourceforge.net/projects/cutter/files/cutter/

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @cosmo0920!

**Pull request closed without merging**
