### PR TITLE
Add formula for xchtmlreport

### PR DESCRIPTION
**Pull request by chrisballinger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Old PR: https://github.com/Homebrew/homebrew-core/pull/26977

The original PR from over a year ago was closed because the repo wasn't notable enough, however now [xchtmlreport](https://github.com/TitouanVanBelle/XCTestHTMLReport) has 232 stars.

I am not sure how to write a test for this formula because it would require downloading and building an external Xcode project.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Build fails on CI. And you're going to need to test something meaningful (even errors can be meaningful) for this to ever be merged.

**Comment by chrisballinger** [comment]
@SMillerDev Is there an example on how to test formulas that require external / downloaded resources? Or just generally formulas with good test examples?

**Comment by fxcoudert** [comment]
We need a test that exercises the some of the functionality of the app. Version checks or usage checks (`foo --version` or `foo --help`) are not sufficient, as explained in the [formula cookbook](https://docs.brew.sh/Formula-Cookbook).

In most cases, a good test would involve running a simple test case: run `#{bin}/foo input.txt`.
- Then you can check that the output is as expected (with `assert_equal` or `assert_match` on the output of `shell_output`)
- You can also check that an output file was created, if that is expected: `assert_predicate testpath/"output.txt", :exist?`

Some advice for specific cases:
- If the formula is a library, compile and run some simple code that links against it. It could be taken from upstream's documentation / source examples.
- If the formula is for a GUI program, try to find some function that runs as command-line only, like a format conversion, reading or displaying a config file, etc.
- If the software cannot function without credentials, a test could be to try to connect with invalid credentials (or without credentials) and confirm that it fails as expected.
- Same if the software requires a virtual machine, docker instance, etc. to be running.

**Comment by fxcoudert** [comment]
Build failure on Sierra with:

```
/tmp/xchtmlreport-20190528-68024-1kysmuy/XCTestHTMLReport-1.7.0/XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Command.swift:16:62: error: value of type '[Int?]' has no member 'compactMap'
        let flagIndexes = CommandLine.arguments.enumerated().map { $0.element.first == "-" ? $0.offset : nil }.compactMap { $0 }
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~
/tmp/xchtmlreport-20190528-68024-1kysmuy/XCTestHTMLReport-1.7.0/XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Test.swift:64:24: error: value of type '[Test]' has no member 'compactMap'
        return subTests!.compactMap({ (test) -> [Test]? in
               ~~~~~~~~^ ~~~~~~~~~~
/tmp/xchtmlreport-20190528-68024-1kysmuy/XCTestHTMLReport-1.7.0/XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Run.swift:24:24: error: value of type '[Test]' has no member 'compactMap'
        let subTests = tests.compactMap { (test) -> [Test]? in
                       ^~~~~ ~~~~~~~~~~
```

You can indicate a minimum Xcode version (if applicable) with:

```
depends_on :xcode => ["10.0", :build]
```

**Comment by chrisballinger** [comment]
@fxcoudert  Ah that's super helpful! Will update the PR with some improvements soon.

**Comment by SMillerDev** [comment]
Can be remade/reopened if the author wants to continue

**Pull request closed without merging**
