### PR TITLE
luajit-openresty 2.1-20201229 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
See discussion at #68013 for context.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
cc @fxcoudert

**Comment by fxcoudert** [comment]
The situation is bad, I'm a bit annoyed that we have to open another formula for a fork. The usage stats on github are not very high at all, so why that fork and not another one, is it widely used elsewhere, is it packaged by other distros?

**Comment by carlocab** [comment]
>The situation is bad, I'm a bit annoyed that we have to open another formula for a fork.

I think this is a consequence of the interaction between lua's nature as primarily an embedded language and Homebrew's approach to packaging software. The two don't really seem to mix... Though I suppose generally embedded languages don't really lend themselves easily to packaging.

>why that fork and not another one, is it widely used elsewhere

The other forks I'm aware of are:
https://github.com/luavela/luavela - appears to have diverged significantly from LuaJIT
https://github.com/raptorjit/raptorjit - not as actively maintained
https://github.com/moonjit/moonjit - no longer maintained

I think the OpenResty fork is a reasonable choice since:
- It's likely to stay maintained, given that it's what OpenResty uses for their web platform
- It doesn't appear to have deviated significantly from the original source and can, for now, serve as a drop-in replacement

It's what Gentoo is contemplating switching to, as mentioned in https://github.com/Homebrew/homebrew-core/issues/68013#issuecomment-753266518. It's also packaged by Arch, DPorts, FreeBSD Ports, and MidnightBSD mports. I suppose we could follow them and call this `luajit-openresty`. https://repology.org/project/luajit-openresty/versions

What other distros seem to be doing is building LuaJIT off the master branch at semi-regular intervals. I'm personally not hugely averse to this, but I know this isn't quite consistent with the way Homebrew does things. (But, see point above about lua and Homebrew packaging...)

**Comment by fxcoudert** [comment]
Thanks @carlocab, let's call it `luajit-openresty` and switch formulas to that if possible.

**Comment by carlocab** [comment]
Name change done ✅. Will try switching some formulae when this is merged.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
