### PR TITLE
git-cinnabar 0.5.0b2 (devel)

### PR DESCRIPTION
**Pull request by gsnedders**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
see https://github.com/glandium/git-cinnabar/releases/tag/0.5.0b2

### CODE REVIEW

**Comment by ilovezfs** [comment]
Did you actually test this locally? The patches are unlikely to apply.

**Comment by gsnedders** [comment]
@ilovezfs yes; note the patches are commits on master, more recent than 0.5.0b2 (and 0.5.0b1), hence it's not that surprising that they apply to 0.5.0b2 when they apply to 0.5.0b1.

**Comment by ilovezfs** [comment]
Ah so 0.5.0b2 isn't brand new. It looks like the test block failed.

**Comment by ilovezfs** [comment]
@gsnedders the issue seems to be fixed in `--HEAD` so we probably need to backport more patches :see_no_evil:

**Comment by gsnedders** [comment]
@ilovezfs Yay! I'll attempt to bisect this later.

**Comment by ilovezfs** [comment]
@gsnedders sounds good, thanks!

**Comment by gsnedders** [comment]
Okay, this is a test failure for this specific repo, and fixed by https://github.com/glandium/git-cinnabar/commit/fbce645abd6c6104712a680350e4f0700c5e8b77.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @gsnedders! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
