### PR TITLE
Import from homebrew/completions

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Move all formulae into homebrew/core.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by alyssais** [comment]
Should completion formulae maybe skip the notability check? It's unlikely somebody's going to star the completions for a tool, so we might be better judging based on the popularity of the tool itself.

**Comment by MikeMcQuaid** [comment]
@alyssais In general no, for this import yes.

**Comment by MikeMcQuaid** [comment]
I didn't import `ctest-completion` due to a test failure and `composer-completion` due to it not having a repo but just being a Gist.

**Pull request merged**
