### PR TITLE
mlkit 4.7.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by danielnachun** [comment]
`mlton` needs to be rebottled.  A revision bump should not be needed.

**Comment by Porkepix** [comment]
I have no idea how that's done though (nor why sometimes rebottle are needed).

**Comment by danielnachun** [comment]
No worries we'll take care of it, we just need to merge https://github.com/Homebrew/homebrew-core/pull/110825 to fix the rebottling workflow.

The reason it is needed is that Ubuntu 22.04 now requires that all binaries be built with `-fPIE`/`-fPIC`.  The current `mlton` bottle was built on Ubuntu 16.04 which doesn't set that flag by default. Simply rebottle `mlton` on Ubuntu 22.04 should fix the issue, after which we can rebase here and it should work.

For future reference, any Linux build failure that ends with `recompile with -fPIE` likely means that formula has dependency that needs to be rebuilt on Ubuntu 22.04.

**Comment by danielnachun** [comment]
@Homebrew/core are we okay with revision bumping `mlton` inside this PR?  Everything looks good on all platforms.

**Comment by MikeMcQuaid** [comment]
> @Homebrew/core are we okay with revision bumping `mlton` inside this PR?

@danielnachun I'd rather unless we need to for a `brew upgrade` for everyone.

**Comment by danielnachun** [comment]
> > @Homebrew/core are we okay with revision bumping `mlton` inside this PR?
> 
> @danielnachun I'd rather not unless we need to for a `brew upgrade` for everyone.

Okay I'll move the `mlton` fix over to its own PR.  It actually doesn't need a revision bump, just a new bottles.

**Comment by danielnachun** [comment]
I rebased this because the `mlton` bottle has been rebuilt on Linux.

**Review by danielnachun — APPROVED** [review]
The bottle builds on Linux now so this is ready to go once CI is done.

**Pull request closed without merging**
