### PR TITLE
Build gcc cross compilers on Apple Silicon

### PR DESCRIPTION
**Pull request by khirbat**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Uses gcc-11 branch with Apple Silicon support from @fxcoudert

https://github.com/Homebrew/homebrew-core/blob/d275312ad3aecdedfdcb40e87dcf49fd2415dab7/Formula/gcc.rb#L5-L8

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hum, why not. We could probably do that with a much more minimal patch, though. Most of the changes in the branch are for ARM target, not host. I'm wondering: what is the build failure you get if you try to build in the current state (official GCC 11.1.0)?

**Comment by khirbat** [comment]
```
$ brew install -s x86_64-elf-gcc
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-11.1.0.tar.xz
Already downloaded: /Users/anmol/Library/Caches/Homebrew/downloads/104cdaaeb30152af30fd8af2d3da5eb879ba1191832e8225d91f3538e4002fb6--gcc-11.1.0.tar.xz
==> ../configure --target=x86_64-elf --prefix=/opt/homebrew/Cellar/x86_64-elf-gcc/11.1.0 --infodir=/opt/homebrew/Cellar/x86_64-elf-gcc/11.1.0/share/info/x86_64-elf-gcc --disable-nls --without-isl -
==> make all-gcc
Last 15 lines from /Users/anmol/Library/Logs/Homebrew/x86_64-elf-gcc/02.make:
      gt_pch_save(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_save(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
      toplev::main(int, char**) in libbackend.a(toplev.o)
      toplev::main(int, char**) in libbackend.a(toplev.o)
ld: symbol(s) not found for architecture arm64
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [lto-dump] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [lto1] Error 1
rm gcc.pod
make: *** [all-gcc] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

```

**Comment by khirbat** [comment]
> Hum, why not. We could probably do that with a much more minimal patch, though. Most of the changes in the branch are for ARM target, not host. I'm wondering: what is the build failure you get if you try to build in the current state (official GCC 11.1.0)?

Updated with minimal patch.

**Comment by fxcoudert** [comment]
Excellent, thank you so much

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
