### PR TITLE
serf 0.9.3

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — COMMENTED** [review]
maybe we can remove `GOPATH`?

**Comment by dtrodrigues** [comment]
@chenrui33 any suggestions? I haven't done too much with go. Feel free to push to my branch.

**Review by dawidd6 — APPROVED** [review]

**Comment by dtrodrigues** [comment]
Thanks @dawidd6!

**Comment by chenrui333** [comment]
Thanks @dawidd6!!

**Comment by dawidd6** [comment]
Thanks for thanking me guys 😄

**Pull request closed without merging**
