### PR TITLE
wiggle 1.3

### PR DESCRIPTION
**Pull request by geofflangenderfer**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
I seen you put the homepage back to the original value, but that page gives an internal server error.

**Comment by geofflangenderfer** [comment]
@SMillerDev not sure the point of homepage, but this[1] seems reasonable

[1] https://github.com/neilbrown/wiggle

**Comment by SMillerDev** [comment]
Seems reasonable to me too, that's why I changed it in https://github.com/Homebrew/homebrew-core/pull/95291/commits/6ca85174f3450698dd481deeda07f18c8d7ad827

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @geofflangenderfer  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
