### PR TITLE
pgroonga 3.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by kou** [comment]
Ah, we need to bump Groonga version to 13.0.2 before PGroonga 3.1.0 because PGroonga 3.1.0 requires Groonga 13.0.2 or later:

https://github.com/Homebrew/homebrew-core/actions/runs/5548298916/jobs/10131179173?pr=136538#step:3:46

```text
  Requested 'groonga >= 13.0.2' but version of Groonga is 13.0.1
```

**Comment by chenrui333** [comment]
> Ah, we need to bump Groonga version to 13.0.2 before PGroonga 3.1.0 because PGroonga 3.1.0 requires Groonga 13.0.2 or later:
> 
> https://github.com/Homebrew/homebrew-core/actions/runs/5548298916/jobs/10131179173?pr=136538#step:3:46
> 
> ```
>   Requested 'groonga >= 13.0.2' but version of Groonga is 13.0.1
> ```

noted, 👍

**Comment by chenrui333** [comment]
@kou feel free to create a new PR whenever groonga 13.0.2 is ready

**Comment by kou** [comment]
Done: #136564

**Comment by chenrui333** [comment]
Thanks!

**Pull request closed without merging**
