### PR TITLE
fluid-synth 2.2.1

### PR DESCRIPTION
**Pull request by cho-m**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

Previous attempt: #74428 (2.2.0)

### CODE REVIEW

**Comment by cho-m** [comment]
Probably going to still fail again on `scummvm` while https://github.com/scummvm/scummvm/pull/2915 isn't in release. Quite large number of commits since last release, so may need to wait for official release.

**Comment by cho-m** [comment]
As expected, did fail. Closing as probably easier to just wait for next `scummvm` release with scummvm/scummvm#2915

```make
audio/softsynth/fluidsynth.cpp:252:3: error: no matching function for call to 'fluid_sfloader_set_callbacks'
                fluid_sfloader_set_callbacks(soundFontMemoryLoader,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/include/fluidsynth/sfont.h:172:20: note: candidate function not viable: no known conversion from 'int (void *, int, void *)' to 'fluid_sfloader_callback_read_t' (aka 'int (*)(void *, long long, void *)') for 3rd argument
FLUIDSYNTH_API int fluid_sfloader_set_callbacks(fluid_sfloader_t *loader,
                   ^
    C++      audio/softsynth/pcspk.o
1 error generated.
make: *** [audio/softsynth/fluidsynth.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by carlocab** [comment]
Please open a pull request for this, @pedrolcl.

**Comment by cho-m** [comment]
If `scummvm` is only formula that depends on `fluid-synth@2.1` then we can use a resource block for that formula.

Based on my understanding, HEAD of `scummvm` should be work fine with latest `fluid-synth`

If this is fine, I can reopen PR and work add resource.

**Comment by pedrolcl** [comment]
I've opened this discussion: https://github.com/Homebrew/discussions/discussions/1577

Currently there are 7 formulae depending on fluidsynth, affected by similar issues.

**Comment by cho-m** [comment]
@pedrolcl To be specific, the older release would be the new versioned formula, i.e.
- `fluid-synth@2.1` would be the new formula that is keg-only (not-linked)
- `fluid-synth` formula would be for latest 2.2.1 and a symlink for `fluid-synth@2.2` would point to it

---

If you want to try opening a PR for this, you will need to:
- do similar things this PR is doing
- add a new formula `Formula/fluid-synth@2.1` that is keg-only
- add a new alias `Aliases/fluid-synth@2.2` that is a symlink to `Formula/fluid-synth`
- update `depends_on "fluid-synth"` to `depends_on "fluid-synth@2.1"` for dependent formula that do not support latest 2.2

**Pull request closed without merging**
