### PR TITLE
Use resource patches

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Use https://github.com/Homebrew/brew/pull/3714.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
@ilovezfs You're a beautiful human.

**Comment by ilovezfs** [comment]
@DomT4 :blush:

**Comment by ilovezfs** [comment]
```
Error: 3 problems in 1 formula
audacious:
  * The URL http://audacious-media-player.org should use HTTPS rather than HTTP
  * Stable: The URL http://distfiles.audacious-media-player.org/audacious-3.9.tar.bz2 should use HTTPS rather than HTTP
  * Stable resource "plugins": The URL http://distfiles.audacious-media-player.org/audacious-plugins-3.9.tar.bz2 should use HTTPS rather than HTTP
```

**Comment by scpeters** [comment]
https://github.com/Homebrew/brew/issues/3750 might be related to this

**Pull request merged**
