### PR TITLE
jpeg-xl: switch to github and update license

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Error:
```
ld: unknown option: --exclude-libs=ALL
ld: unknown option: --exclude-libs=ALL
clangclang: error: : error: linker command failed with exit code 1 (use -v to see invocation)
linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libjxl_dec.0.6.0.dylib] Error 1make[2]: *** [libjxl.0.6.0.dylib] Error 1
```

Probably fixed by https://github.com/libjxl/libjxl/commit/88fe3fff3dc70c72405f57c69feffd9823930034
(corresponding GitLab commit https://gitlab.com/wg1/jpeg-xl/-/commit/88fe3fff3dc70c72405f57c69feffd9823930034)

**Comment by miccal** [comment]
FYI:
```
|-> brew livecheck jpeg-xl
jpeg-xl : 0.5 ==> 0.6
```

**Review by SMillerDev — APPROVED** [review]
Assuming that this works on the other macOS versions as well, let's go

**Comment by carlocab** [comment]
For `jpeg-xl: https://github.com/Homebrew/homebrew-core/actions/runs/1402792741

`aom` will need to be bottled for Monterey when that's completed. It might be a few hours.

**Pull request closed without merging**
