### PR TITLE
bazel 0.6.0

### PR DESCRIPTION
**Pull request by zuercher**

### CODE REVIEW

**Comment by zuercher** [comment]
I think I've taken the correct steps to preserve bazel@0.5 in addition to making the default install version the newly released bazel 0.6.0.

**Comment by ilovezfs** [comment]
I don't think we need a new bazel@0.5 formula. Let's just keep this to being a simple version upgrade.

**Comment by zuercher** [comment]
Ok. I've removed it.

**Comment by ilovezfs** [comment]
thanks!

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @zuercher! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
