### PR TITLE
sbt 1.4.0

### PR DESCRIPTION
**Pull request by fkoehler**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by fkoehler** [comment]
How and when can this be merged? Is there anything else needed from my side?

**Comment by SMillerDev** [comment]
It'll be merged by the bot in the next hour

**Comment by SethTisue** [comment]
looks like this doesn't add the new `sbtn` command?

**Comment by fkoehler** [comment]
> looks like this doesn't add the new `sbtn` command?

In my understanding sbtn is optional and a separate Package. Sbtn is built into sbt by using the `—client` option or exporting an env var. 

If the intention was to also add sbtn to this additionally I am sorry if this was released to early.

**Comment by SethTisue** [comment]
@eed3si9n wdyt?

**Comment by eed3si9n** [comment]
@SethTisue You're both right. The tar ball https://github.com/sbt/sbt/releases/download/v1.4.0/sbt-1.4.0.tgz contains `bin/sbtn-x86_64-apple-darwin`, and as @fkoehler noted, `sbt --client` will invoke it.

However, since Homebrew is used only by Mac users (?), it could be argued that Homebrew recipe should make a symbolic link directly to `bin/sbtn-x86_64-apple-darwin` as `sbtn` until ARM Mac ships. This has the advantage of slight speedup of not going through Bash.

We can continue the discussion on https://github.com/sbt/sbt/issues/5665.

**Comment by SethTisue** [comment]
(continuing the Homebrew-specific ,1.4.0-specific aspect here:)

regardless of whether something different happens later (which I guess is what sbt/sbt#5665 is about?), it seems to be that for 1.4.0, what I get with Homebrew ought to match what I get when I install sbt with the official installer from the sbt website, so that means it ought to include `sbtn`

at http://eed3si9n.com/sbt-1.4.0 it says "The headline features of sbt 1.4.0 are: ... sbtn: a native thin client for sbt", and it says "installer includes the sbtn binary" and it says "sbt 1.4.0 adds an official native thin client called sbtn that supports all tasks". Given all that, if someone get sbt 1.4.0 from Homebrew and it _doesn't_ include `sbtn`, I feel they will be surprised and confused.

**Pull request closed without merging**
