### PR TITLE
jupyterlab 1.2.0

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I have renamed `jupyter` formula to `jupyterlab` and bumped it to 1.2.0

### CODE REVIEW

**Comment by henryiii** [comment]
1.2.0 was just released today, FYI.

**Comment by bayandin** [comment]
Thanks @henryiii, bumped to 1.2.0

**Comment by bayandin** [comment]
@chenrui333 yup, already done https://github.com/Homebrew/homebrew-core/pull/45908/files?file-filters%5B%5D=.json#diff-1df8783161e0d794f82b4b77825ee6b8

**Comment by henryiii** [comment]
This looks great!

**Comment by chenrui333** [comment]
> @chenrui333 yup, already done https://github.com/Homebrew/homebrew-core/pull/45908/files?file-filters%5B%5D=.json#diff-1df8783161e0d794f82b4b77825ee6b8

Thanks for confirming it!

**Review by chenrui333 — APPROVED** [review]
👍

**Pull request closed without merging**
