### PR TITLE
ruby 2.4.1

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
```
Testing vim
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170322-71086-ziimp9.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb --verbose
==> /usr/local/Cellar/vim/8.0.0502/bin/vim -T dumb -s commands.vim test.txt
dyld: Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib
  Referenced from: /usr/local/Cellar/vim/8.0.0502/bin/vim
  Reason: image not found
```
It seems like vim bottle is need to be updated.

**Comment by neutric** [comment]
@yurikoles You need to bump the revision for `libstfl`, `mikutter` and `vim`, see e.g. [here](https://github.com/Homebrew/homebrew-core/pull/8201).

**Comment by yurikoles** [comment]
@neutric done

**Comment by nijikon** [comment]
@yurikoles revision bumps should be separate commits

**Comment by yurikoles** [comment]
@nijikon done

**Comment by nijikon** [comment]
@yurikoles Thanks! I don't want to be an asshole so I will fix the commit messages, but for future reference as @neutric pointed out in #8201, the commit messages in this particular case when you bump revision should be `<formula>: bump revision for ruby`.

**Comment by yurikoles** [comment]
@nijikon I had fixed commit messages.

**Comment by nijikon** [comment]
@yurikoles nice!

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by neutric** [comment]
👍

**Comment by viktorbenei** [comment]
Hi,

It seems (most likely) this change broke some symlink/paths - 24 hours ago with the previous 2.4.0 if you did:

```
brew install ruby
# gem install anything which installs an executable
gem install cocoapods
# try to run the installed executable
pod --version

1.2.0
```

it worked as expected, but with the current 2.4.1:

```
brew install ruby
gem install cocoapods
pod --version

-bash: pod: command not found
```

Tested with other gems which install executables (cocoapods, fastlane, xcpretty) and got the same error.

For comparison, installing `ruby@2.3` and then `gem install` works as expected:

```
brew install ruby@2.3
brew link --force ruby@2.3
gem install cocoapods
pod --version

1.2.0
```

Tested in identical virtual machines (same base image). If you need any other info just let me know!

**Comment by yurikoles** [comment]
@viktorbenei I had tried uninstall and install ruby from scratch and don't see your problem.
```0 ✓ yurikoles@iHack  ~ $ which pod
/usr/local/bin/pod
0 ✓ yurikoles@iHack  ~ $ pod --version
1.2.0
0 ✓ yurikoles@iHack  ~ $
 ```

**Comment by viktorbenei** [comment]
Did you have `pod` installed before?

I got the same on my Mac initially, where I had `pod` installed; `brew uninstall ruby && brew install ruby` then `gem install cocoapods` and `pod --version` worked.

But then:

```
brew uninstall ruby
rm /usr/local/bin/pod
brew install ruby
gem install cocoapods

pod --version
fish: Unknown command 'pod'
```

**Comment by viktorbenei** [comment]
I believe the issue is the change in `gem env` - `EXECUTABLE DIRECTORY`, not sure what changed it.

With `brew install ruby@2.3 && brew link --force ruby@2.3`:

```
gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/viktorbenei/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby@2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/viktorbenei/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby@2.3/2.3.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.3.0
     - /Users/viktorbenei/.gem/ruby/2.3.0
     - /usr/local/Cellar/ruby@2.3/2.3.3/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /Users/viktorbenei/develop/go/bin
     - /usr/local/opt/go/libexec/bin
```

While with `brew install ruby` (2.4.1):

```
gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.4.1 (2017-03-22 patchlevel 111) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /usr/local/Cellar/ruby/2.4.1/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: /Users/viktorbenei/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /usr/local/Cellar/ruby/2.4.1/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/Cellar/ruby/2.4.1/bin
  - SPEC CACHE DIRECTORY: /Users/viktorbenei/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.4.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /usr/local/Cellar/ruby/2.4.1/lib/ruby/gems/2.4.0
     - /Users/viktorbenei/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /Users/viktorbenei/develop/go/bin
     - /usr/local/opt/go/libexec/bin
```

-> the `EXECUTABLE DIRECTORY` changed

**Comment by yurikoles** [comment]
Yes, now I see, it's here now: `/usr/local/Cellar/ruby/2.4.1/bin/pod`

**Comment by yurikoles** [comment]
Temporary workaround: put the following in `~/.gemrc`: 

```
gem: --bindir /usr/local/bin
```

**Comment by viktorbenei** [comment]
@yurikoles the workaround works 👍 

In any case we can live with this / can work this around, just wanted to report this as this was a change our daily CI caught - should I create a separate issue somewhere?

**Comment by yurikoles** [comment]
@viktorbenei yes I think you need to create a new ticket for this.

**Comment by viktorbenei** [comment]
done, thanks @yurikoles !

**Pull request closed without merging**
