### PR TITLE
migrate arcanist v20180412 from homebrew-php

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by hevy-CC4477** [comment]
What is the issue here ? I would like to use this formula.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@yurikoles could you fix the audit failures?

**Comment by yurikoles** [comment]
@SMillerDev I had removed head section, but I can't fix issue:
 ```* GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)```
Since this repo is noly a mirror for gerrit. Another issue I'm facing is that it seems to be a fork? Maybe I should rename formula? The original repo latest tag was in 2012, so I want to use wikimedia's one.

**Comment by hevy-CC4477** [comment]
I am wondering, is this normal to use wikimedia instead of phacility (https://github.com/phacility/arcanist) ?

**Comment by brianmacdonald** [comment]
phacility would seem to be the repo to use since it's referenced in the phabricator documentation (https://secure.phabricator.com/book/phabricator/article/arcanist_quick_start/)

**Comment by fxcoudert** [comment]
phacility is the upstream repo, but they don't publish releases. They recommend installation of latest git, which we cannot accommodate in Homebrew. I am thus closing this pull request.

**Pull request closed without merging**
