### PR TITLE
joplin 0.10.82

### PR DESCRIPTION
**Pull request by laurent22**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by laurent22** [comment]
This I think should fix the sqlite3 issue. I've republished the app on npm.org and rebuild the formula with the "node@8" dependency. It works on my local machine.

**Comment by laurent22** [comment]
Closed as duplicate of #21486

**Comment by chrmoritz** [comment]
The python dependency wan't that wrong through. Because we need to run gyp here to build `node-sqlite3` (native addon) and gyp's python requirement (2.7.x), a `depends_on :python => :build if MacOS.version <= :snow_leopard` seems feasible.

**Comment by ilovezfs** [comment]
updated

**Comment by laurent22** [comment]
Also isn't the `node@8` dependency needed? I didn't test with node 9 and I suspect it won't work with it.

**Comment by ilovezfs** [comment]
@laurent22 the node@* formulae are basically exclusively for users not formulae at this point. So hopefully it does work with node 9.

**Comment by laurent22** [comment]
@ilovezfs, ok I just gave it a try and to my surprise it seems to work, so hopefully it should be fine.

**Comment by ilovezfs** [comment]
yay!

**Comment by ilovezfs** [comment]
Thanks @laurent22! Shipped.

**Comment by laurent22** [comment]
Working good, thanks @ilovezfs for the fast deployment!

**Pull request closed without merging**
