### PR TITLE
weechat 4.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at src/plugins/CMakeLists.txt:162 (message):
    Tcl not found
```

**Comment by chenrui333** [comment]
Looks like build is good now, mark this to be reviewed again.

**Review by carlocab — CHANGES_REQUESTED** [review]
No, this is mixing Tcl libraries from macOS and the headers from `tcl-tk`, which is why I converted this to draft.

**Comment by cho-m** [comment]
What was reason we are now using Homebrew's `tcl-tk` on macOS?

---

Also, looks like recent Linux `tcl-tk` failures may be a side effect of #124056. `include/tcl-tk` is a non-standard/uncommon directory structure and is forcing us to manually set the path.

We may want to either use a more common path or upstream Homebrew's new path to build systems - https://github.com/Kitware/CMake/blob/master/Modules/FindTCL.cmake#L170-L195
```cmake
set(TCLTK_POSSIBLE_INCLUDE_PATHS
  "${TCL_LIBRARY_PATH_PARENT}/include"
  "${TK_LIBRARY_PATH_PARENT}/include"
  "${TCL_INCLUDE_PATH}"
  "${TK_INCLUDE_PATH}"
  ${TCL_FRAMEWORK_INCLUDES}
  ${TK_FRAMEWORK_INCLUDES}
  "${TCL_TCLSH_PATH_PARENT}/include"
  "${TK_WISH_PATH_PARENT}/include"
  )

set(TCLTK_POSSIBLE_INCLUDE_PATH_SUFFIXES
  include/tcl${TK_LIBRARY_VERSION}
  include/tcl${TCL_LIBRARY_VERSION}
  include/tcl8.7
  include/tk8.7
  include/tcl8.6
  include/tk8.6
  include/tcl8.5
  include/tk8.5
  include/tcl8.4
  include/tk8.4
  include/tcl8.3
  include/tcl8.2
  include/tcl8.0
  )
```

**Review by SMillerDev — APPROVED** [review]

**Comment by cho-m** [comment]
#135694 is one way to allow CMake to find Homebrew's `tcl-tk` headers.

**Comment by SMillerDev** [comment]
> Is the macOS version being held up because of a linux issue? There have been 2 more releases of Weechat in the mean time. 4.0.1 and 4.0.2.

The Homebrew version is being held up because of a Homebrew issue. You're welcome to make a pull request that updates to 4.0.2 and addresses all concerns though.

**Comment by fxcoudert** [comment]
Let's try the latest version: https://github.com/Homebrew/homebrew-core/pull/141556

**Comment by ZhongRuoyu** [comment]
Covered by #141556.

**Pull request closed without merging**
