### PR TITLE
traefik@1 (new formula)

### PR DESCRIPTION
**Pull request by djerfy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Related with PR #44333

### CODE REVIEW

**Comment by SMillerDev** [comment]
Did you ever find out how long upstream is planning to support this?

**Comment by djerfy** [comment]
> Did you ever find out how long upstream is planning to support this?

No but I'm going to open an issue to ask, I do not think it's been a long time.
The upgrade to v2 is major, the idea was to keep a compatibility.

**Comment by fxcoudert** [comment]
_**If**_ we want to keep this older version around (provided it meets our criteria https://docs.brew.sh/Versions), it should be named `traefik@1`.

**Comment by chenrui333** [comment]
I think upstream still supports `traefik@1` :)
https://github.com/containous/traefik/releases/tag/v1.7.17

**Comment by SMillerDev** [comment]
> I think upstream still supports `traefik@1` :)
> https://github.com/containous/traefik/releases/tag/v1.7.17

I'd still like an official answer. For we all we know this is the last ever 1.x release.

**Comment by djerfy** [comment]
Issue opened: https://github.com/containous/traefik/issues/5475

**Comment by alebcay** [comment]
From the linked upstream issue:
> Hi, and thank you for your question.
The current plan is to support 1.7 for a year, starting with the v2.0.0 release. We want to give the community time to adapt their stack and time to provide feedback to make sure the transition to 2.0 is as great as expected.

**Comment by djerfy** [comment]
> From the linked upstream issue:
> 
> > Hi, and thank you for your question.
> > The current plan is to support 1.7 for a year, starting with the v2.0.0 release. We want to give the community time to adapt their stack and time to provide feedback to make sure the transition to 2.0 is as great as expected.

Thanks and it's a good news. I will make changes (rename + update to 1.7.17), good for everyone?

**Review by chenrui333 — APPROVED** [review]
👍

**Comment by chenrui333** [comment]
@djerfy Can you squash your commits?

**Comment by SMillerDev** [comment]
Can you rename the commit to use the format `<formula_name> <version> (new formula)`?

**Comment by djerfy** [comment]
> Can you rename the commit to use the format `<formula_name> <version> (new formula)`?

Yes sorry (and thank you for your time)

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by SMillerDev** [comment]
Thanks @djerfy! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by chenrui333** [comment]
Thanks for the work!

**Pull request closed without merging**
