### PR TITLE
pango: remove x11 option

### PR DESCRIPTION
**Pull request by stephengroat**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
X11-enabled installs of `pango` represent 0.27% of `pango` installs in Homebrew (94 in a month, out of 35,058). No other package depends on that option. And we recently introduced a policy of not depending on optionals.

So, I'd suggest we remove pango's X11 option.

**Comment by MikeMcQuaid** [comment]
> So, I'd suggest we remove pango's X11 option. @MikeMcQuaid an opinion?

Agreed.

**Comment by stephengroat** [comment]
That's to bad. I was getting chirp (a popular amateur/ham radio programming project) to use Travis and appveyor. 

Are there any plans for how I continue ​to use brew with these options?

**Comment by MikeMcQuaid** [comment]
> Are there any plans for how I continue ​to use brew with these options?

Maintain them in your own tap.

**Comment by jtanx** [comment]
If you looked at the git blame, that x11 option was *specifically* re-introduced for CI builds for FontForge. It would have been nice if you'd at least have pinged us that you're now removing it due to some arbitrary change in policy. 

Though not that I can see the need to remove this option from the formula at all.

**Pull request merged**
