### PR TITLE
bazel 0.5.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@damienmg looks like Yosemite is failing due to mktemp.
```
08:32:56 usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
08:32:56        mktemp [-d] [-q] [-u] -t prefix 
08:32:56 Target //src:bazel failed to build
```

See
https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
https://github.com/facebook/flow/pull/3833
https://github.com/elasticdog/transcrypt/issues/34

**Comment by ilovezfs** [comment]
@mhlopko unfortunately looks like 10.10 is unhappy.

**Comment by mhlopko** [comment]
Thanks @ilovezfs. Hypothetically, I assume there's no way to update the recipe only for os > yosemite?

**Comment by ilovezfs** [comment]
@mhlopko we can add `depends_on :el_capitan` but that will leave a bit over 3% of the Homebrew bazel out of luck. Also a `mktemp` fix should be trivial.

**Comment by ilovezfs** [comment]
@mhlopko https://github.com/bazelbuild/bazel/commit/9ab58211439d183fed38d3f8649c35c69591540c#diff-b7647fd114fcd88b2ec3bcd30fc8744aR80

**Comment by ilovezfs** [comment]
@mhlopko So we have :green_apple: now. Let me know how you'd like to proceed.

**Pull request closed without merging**
