### PR TITLE
mailcatcher 0.9.0

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [ ] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* Remove flexie library by @matthhan in https://github.com/sj26/mailcatcher/pull/505
* Correct the path for attachments by CID by @duncan3dc in https://github.com/sj26/mailcatcher/pull/504
* Support Ruby 3.1 by @sj26 in https://github.com/sj26/mailcatcher/pull/509
* Update Dockerfile to v0.8.1 by @ohbarye in https://github.com/sj26/mailcatcher/pull/493
* Switch from Skinny to Faye Websocket by @sj26 in https://github.com/sj26/mailcatcher/pull/510
* Update thin version by @mockdeep in https://github.com/sj26/mailcatcher/pull/530
* Add Ruby 3.2 to CI by @petergoldstein in https://github.com/sj26/mailcatcher/pull/536

## New Contributors
* @matthhan made their first contribution in https://github.com/sj26/mailcatcher/pull/505
* @duncan3dc made their first contribution in https://github.com/sj26/mailcatcher/pull/504
* @mockdeep made their first contribution in https://github.com/sj26/mailcatcher/pull/530
* @petergoldstein made their first contribution in https://github.com/sj26/mailcatcher/pull/536

**Full Changelog**: https://github.com/sj26/mailcatcher/compare/v0.8.2...v0.9.0</pre>
</details>

### CODE REVIEW

**Comment by osalbahr** [comment]
> resource blocks have been checked for updates.

Can't find resource blocks.

- - -

It might help to know whether the ruby gem error is ARM-only.

```console
 `brew test --verbose mailcatcher` failed on macOS Ventura (13) on Apple Silicon!

/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
==> Testing mailcatcher
==> /opt/homebrew/Cellar/mailcatcher/0.9.0/bin/mailcatcher
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'faye-websocket' (~> 0.11.1) among 60 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/private/tmp/mailcatcher-test-20230804-12131-4wk10m/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/opt/homebrew/Cellar/mailcatcher/0.9.0/libexec:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	from /opt/homebrew/Cellar/mailcatcher/0.9.0/libexec/bin/mailcatcher:23:in `<main>'
Error: mailcatcher: failed
An exception occurred within a child process:
  BuildError: Failed executing: /opt/homebrew/Cellar/mailcatcher/0.9.0/bin/mailcatcher
/opt/homebrew/Library/Homebrew/formula.rb:2741:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:2677:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2677:in `system'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/mailcatcher.rb:136:in `block in <class:Mailcatcher>'
/opt/homebrew/Library/Homebrew/formula.rb:2502:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2501:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:1055:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2500:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2792:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2494:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

**Comment by chenrui333** [comment]
Duplicate of #137980

**Comment by chenrui333** [comment]
just reopened that one, almost finished

**Comment by osalbahr** [comment]
Duplicate

**Pull request closed without merging**
