### PR TITLE
openvscode-server 1.84.0 (new formula)

### PR DESCRIPTION
**Pull request by JounQin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@JounQin thanks for the PR, can you use this commit msg style `openvscode-server 1.84.0 (new formula)`? Thanks! 🙏

**Comment by chenrui333** [comment]
```
error /private/tmp/openvscode-server-20231122-5651-vkyrbk/openvscode-server-openvscode-server-v1.84.0/node_modules/@parcel/watcher: Command failed.
  Exit code: 1
  Command: node-gyp-build
  Arguments: 
  Directory: /private/tmp/openvscode-server-20231122-[56](https://github.com/Homebrew/homebrew-core/actions/runs/6959611012/job/18937408979?pr=155154#step:3:57)51-vkyrbk/openvscode-server-openvscode-server-v1.84.0/node_modules/@parcel/watcher
  Output:
  node:events:495
        throw er; // Unhandled 'error' event
        ^
  
  Error: spawn node-gyp ENOENT
      at ChildProcess._handle.onexit (node:internal/child_process:284:19)
      at onErrorNT (node:internal/child_process:477:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  Emitted 'error' event on ChildProcess instance at:
      at ChildProcess._handle.onexit (node:internal/child_process:290:12)
      at onErrorNT (node:internal/child_process:477:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawn node-gyp',
    path: 'node-gyp',
    spawnargs: [ 'rebuild' ]
```

**Comment by JounQin** [comment]
@chenrui333 Any advice?

**Comment by JounQin** [comment]
> error Error: EPERM: operation not permitted, symlink '../../../private/tmp/openvscode-server-20231122-5247-zp2i1o/openvscode-server-openvscode-server-v1.84.0/.brew_home/.config/yarn/global/node_modules/.bin/node-gyp' -> '/opt/homebrew/bin/node-gyp'

How can I use `node-gyp` correctly. 🤣

**Comment by JounQin** [comment]
ping

**Comment by JounQin** [comment]
ping

**Comment by SMillerDev** [comment]
Since it doesn't build I don't think there is much use keeping this one open.

**Comment by JounQin** [comment]
image

@SMillerDev I think that's because https://github.com/gitpod-io/openvscode-server is a fork?

**Comment by SMillerDev** [comment]
That's why the audit fails, the install fails for other reasons

**Comment by JounQin** [comment]
```log
/bin/sh: 1: pkg-config: not found
  /bin/sh: 1: pkg-config: not found
  gyp: Call to '${PKG_CONFIG:-pkg-config} x11 xkbfile --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
  gyp ERR! configure error 
  gyp ERR! stack Error: `gyp` failed with exit code: 1
  gyp E
```

Do you have any advice to fix this?

**Pull request closed without merging**
