### PR TITLE
gammaray 2.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- always use Qt 5 (and remove the Qt 4 option).
- add option to run `make test` and always run it during CI
- fix case sensitivity issue with the old test

### CODE REVIEW

**Comment by DomT4** [comment]
This might be a good time to kill off that `qt4` option here, but if you want to do that elsewhere, 👍.

**Comment by ilovezfs** [comment]
@DomT4 Qt 4 option dead as a doornail now.

**Comment by DomT4** [comment]
I'm sure that'll immensely annoy some people, but upstream have been building against Qt5 by default for a while now & `qt4` is completely unsupported by Qt themselves, so. 👍 when 🍏.

**Comment by ilovezfs** [comment]
@DomT4 also I just modified the test because it was borked on case-sensitive file system (and because it was a silly test to begin with).

**Comment by DomT4** [comment]
Oh, it only generates an `.app` bundle? Heh. May well end up being Casked at some point soon anyway then, but 👍 on the changes and new test.

**Comment by MikeMcQuaid** [comment]
Upstream are my former coworkers and definitely won't mind the Qt4 option being killed. It doesn't seem they provide binaries otherwise I agree it'd be a good Cask candidate. @frankosterfeld are there any KDAB-provided OS X binaries for this?

**Comment by UniqMartin** [comment]
https://github.com/KDAB/homebrew-tap may be relevant and worth inspecting.

**Comment by ilovezfs** [comment]
been there, done that

**Comment by ilovezfs** [comment]
@DomT4 seems new test caused CI to hang. Let's see if `make test` does any better.

**Pull request closed without merging**
