### PR TITLE
utf8proc 2.9.0

### PR DESCRIPTION
**Pull request by bevanjkay**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by SMillerDev** [comment]
`securefs` still needs a bump

**Comment by fxcoudert** [comment]
There is now a conflict due to https://github.com/Homebrew/homebrew-core/pull/152092

**Comment by chenrui333** [comment]
> There is now a conflict due to #152092
if PR passed, we can still publish bottle commits into this PR and run a rebase.

**Comment by chenrui333** [comment]
git-svn issue is unrelated. 
```
  ==> git svn clone file:///tmp/git-svn-test-20231023-13149-rcb3d1/repo git-work
  Can't locate SVN/Core.pm in @INC (you may need to install the SVN::Core module) (@INC entries checked: /home/linuxbrew/.linuxbrew/opt/git/share/perl5 /home/linuxbrew/.linuxbrew/opt/subversion/lib/perl5/site_perl/5.36.1/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/site_perl/5.38/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/site_perl/5.38 /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/5.38/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/5.38 /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.38/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.38) at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN/Utils.pm line 6.
  BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN/Utils.pm line 6.
  Compilation failed in require at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN.pm line 32.
  BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN.pm line 32.
  Compilation failed in require at /home/linuxbrew/.linuxbrew/bin/git-svn line 23.
  BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/bin/git-svn line 23.
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> git-svn linux test failure is unrelated.
> 
> ```
>   ==> git svn clone file:///tmp/git-svn-test-20231023-13149-rcb3d1/repo git-work
>   Can't locate SVN/Core.pm in @INC (you may need to install the SVN::Core module) (@INC entries checked: /home/linuxbrew/.linuxbrew/opt/git/share/perl5 /home/linuxbrew/.linuxbrew/opt/subversion/lib/perl5/site_perl/5.36.1/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/site_perl/5.38/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/site_perl/5.38 /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/5.38/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/5.38 /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.38/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.38) at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN/Utils.pm line 6.
>   BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN/Utils.pm line 6.
>   Compilation failed in require at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN.pm line 32.
>   BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/opt/git/share/perl5/Git/SVN.pm line 32.
>   Compilation failed in require at /home/linuxbrew/.linuxbrew/bin/git-svn line 23.
>   BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/bin/git-svn line 23.
> ```

yeah, it is already broken in the master branch

```
Initialized empty Git repository in /tmp/git-svn-test-20231023-10460-a746uy/git-work/.git/
/home/linuxbrew/.linuxbrew/bin/perl: symbol lookup error: /home/linuxbrew/.linuxbrew/lib/libsvn_swig_perl-1.so.0: undefined symbol: Perl_newRV_noinc
```

https://github.com/chenrui333/github-action-test/actions/runs/6615793857/job/17968715399

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
