### PR TITLE
Add Apple Mach-O to COFF (mtoc) formula

### PR DESCRIPTION
**Pull request by rickmark**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Because https://github.com/tianocore/tianocore.github.io/wiki/Xcode is hard....

### CODE REVIEW

**Comment by ilovezfs** [comment]
This is already included in `cctools`.

**Comment by rickmark** [comment]
In that case, perhaps the best idea is for me to update "https://github.com/tianocore/tianocore.github.io/wiki/Xcode" with `brew install cctools`

**Comment by rickmark** [comment]
Is it possible to brew link `mtoc` selectively as it doesn't conflict with anything?

**Comment by ilovezfs** [comment]
>Is it possible to brew link mtoc selectively as it doesn't conflict with anything?

Not unless you do it manually. But you can run `"$(brew --prefix cctools)/bin/mtoc"`

**Comment by ilovezfs** [comment]
@rickmark thanks for the PR but passing on this since we already distribute it.

**Pull request closed without merging**
