### PR TITLE
meilisearch 1.0.0

### PR DESCRIPTION
**Pull request by curquiza**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by curquiza** [comment]
Also this
Capture d’écran 2023-02-06 à 09 52 34

should be `meilisearch` now, `meilisearch-http` does not exist anymore. Sorry for the issue! Do you want me to do a PR?

**Comment by curquiza** [comment]
As updated [here](https://github.com/Homebrew/homebrew-core/pull/122396#issuecomment-1418717294), our binary is well published, it was a network issue in our CI

**Comment by SMillerDev** [comment]
> Do you want me to do a new PR? or update this one?

This PR should be fixed, not a new one.

**Comment by curquiza** [comment]
Thanks @chenrui333 
Looks like there is a timeout issue in the CI, am I wrong?

**Comment by SMillerDev** [comment]
> Looks like there is a timeout issue in the CI, am I wrong?

No, it failed on macOS 13

**Comment by curquiza** [comment]
@SMillerDev sorry I don't understand the failure of the test in the CI

I saw the timeout here:

Capture d’écran 2023-02-07 à 18 32 18

**Comment by chenrui333** [comment]
test failures on intel builds, looking into it.

**Comment by chenrui333** [comment]
looks good now.

**Pull request closed without merging**
