### PR TITLE
insect: deprecate in favor of `numbat`

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
The upstream repository hasn't had a new release, and no commits for two months. But it may still be a genuine release.

**Review by bayandin — DISMISSED** [review]

**Comment by bevanjkay** [comment]
It looks like the only change made was to add a line to the readme pointing to the [`numbat`](https://numbat.dev/) project instead. Perhaps this should be `deprecated` while we are here.

**Comment by chenrui333** [comment]
yeah, deprecating makes sense to me 👍

**Comment by bevanjkay** [comment]
Should we use the `replacement` parameter for deprecate here?

**Comment by chenrui333** [comment]
good point 👍

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
