### PR TITLE
radare2: various plugin/lua fixes

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

* Place lua libraries correctly
* Stop core_yara attempting to violate sandbox
* Remove redundant inreplace.

Closes https://github.com/Homebrew/homebrew-core/issues/24270.

### CODE REVIEW

**Comment by DomT4** [comment]
It's all open for discussion here; this formula is pretty gross & we certainly ain't making it much better.

**Comment by DomT4** [comment]
Give me a minute on this, even if nobody has objections as-is. Going to see if I can bastardise `lua.c` a little so we don't have to place `json.lua` in such a global location.

**Comment by xzcvczx** [comment]
pancake from radare has advised that the lua plugin has not had many contributions in a rather long time so i still think there should be discussion as to whether or not to retain lua support in the homebrew build

**Comment by DomT4** [comment]
@ilovezfs Throwing this to you for a decision. This is about as pretty as it's gonna get if we want to retain `lua` support. I have no idea if `lua` support can actually be turned off completely here but I can look into it if we decide this isn't worth the hassle.

**Comment by DomT4** [comment]
Go away bot.

**Comment by DomT4** [comment]
Rebased against the recent update.

**Comment by ilovezfs** [comment]
🌔 Thanks, @DomT4!

**Comment by DomT4** [comment]
Thanks Joe.

**Pull request closed without merging**
