### PR TITLE
insect 5.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
07:06:12 npm sill postinstall insect@5.1.2
07:06:12 npm info lifecycle insect@5.1.2~postinstall: insect@5.1.2
07:06:12 
07:06:12 > insect@5.1.2 postinstall /usr/local/Cellar/insect/5.1.2/libexec/lib/node_modules/insect
07:06:12 > bower --allow-root install && npm run browserify && npm run copy
07:06:12 
07:06:12 sh: bower: command not found
07:06:12 npm verb lifecycle insect@5.1.2~postinstall: unsafe-perm in lifecycle true
07:06:12 npm verb lifecycle insect@5.1.2~postinstall: PATH: /usr/local/Cellar/node/12.5.0/libexec/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/Cellar/insect/5.1.2/libexec/lib/node_modules/insect/node_modules/.bin:/usr/local/Cellar/insect/5.1.2/libexec/lib/node_modules/.bin:/usr/local/opt/node/libexec/bin:/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/icu4c/bin:/usr/local/opt/node/bin:/usr/bin:/bin:/usr/sbin:/sbin
07:06:12 npm verb lifecycle insect@5.1.2~postinstall: CWD: /usr/local/Cellar/insect/5.1.2/libexec/lib/node_modules/insect
07:06:12 npm sill lifecycle insect@5.1.2~postinstall: Args: [
07:06:12 npm sill lifecycle   '-c',
07:06:12 npm sill lifecycle   'bower --allow-root install && npm run browserify && npm run copy'
07:06:12 npm sill lifecycle ]
```

bower cmd not found

**Comment by chenrui333** [comment]
Should be good now, cc @SMillerDev @lembacon @Moisan

**Comment by chenrui333** [comment]
🎉 🎉

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Pull request closed without merging**
