### PR TITLE
kubernetes-helm (revision for correct commit)

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

For some reason the bottle picked up commit `2342275b61e0539d259590975cfb78f23afcc1e3` instead of `d83c245fc324117885ed83afc90ac74afed271b4`

```
$ helm version --client 
Client: &version.Version{SemVer:"v2.3.0", GitCommit:"2342275b61e0539d259590975cfb78f23afcc1e3", GitTreeState:"clean"}
```

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
I think we need to understand exactly what happened here before merging.

**Comment by cblecker** [comment]
Original PR is #12167

**Comment by ilovezfs** [comment]
@cblecker thanks. Note that brew verifies the revisions of tags, so the only plausible explanation I have is that the build system used something other than the checked-out commit, and that would repeat despite a revision bump.

**Comment by cblecker** [comment]
@ilovezfs I tried the build local, and it pulled the right commit. Maybe a CI issue of some kind?

**Comment by ilovezfs** [comment]
The build wouldn't even get going if the tag and revision did not match. It would simply abort.

**Comment by cblecker** [comment]
Is there a variable we can use in testing to match the revision? lines 47/48 already do a `version` to verify the git tree is clean.

**Comment by ilovezfs** [comment]
I'm not even sure what 2342275b61e0539d259590975cfb78f23afcc1e3 is. Maybe upstream retagged? Did you have to update the original PR with a different commit?

**Comment by cblecker** [comment]
Nope. I don't believe I did, and I don't have any evidence of upstream retagging.

**Comment by ilovezfs** [comment]
@fxcoudert any idea what happened in #12167? This is falling into the befuddling column right now.

**Comment by fxcoudert** [comment]
No idea :(
And the build bot files are not there anymore, so hard to know why/how it passed

**Comment by cblecker** [comment]
@ilovezfs How would you suggest we proceed? I'm willing to help in any way I can.

**Comment by ilovezfs** [comment]
Thanks for taking care of this via #12403.

**Pull request closed without merging**
