### PR TITLE
neo4j@4.4 4.4.21 (new formula)

### PR DESCRIPTION
**Pull request by allen-ball**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions) and why we might want to ship an older version?

**Comment by allen-ball** [comment]
[Cartography](https://github.com/lyft/cartography) specifies it supports [neo4j](https://github.com/neo4j/neo4j) 4.4 and currently uses queries incompatible with 5.8.  The [4.4 branch](https://github.com/neo4j/neo4j/tree/4.4) is still active and has been recently updated.

**Comment by SMillerDev** [comment]
Okay, but does Neo4j say they will still support it?

**Comment by allen-ball** [comment]
<https://neo4j.com/developer/kb/neo4j-supported-versions/#_neo4j_database_enterprise_edition_4> indicates version 4.4 will be supported until June 30, 2025.

**Comment by SMillerDev** [comment]
It seems that's the enterprise edition though and Homebrew ships the community edition.

**Comment by carlocab** [comment]
You could try asking upstream about the development status of the community edition of the 4.4.x branch. Maybe in the [forums](https://community.neo4j.com)?

**Pull request closed without merging**
