### PR TITLE
gtk-sharp 2.12.45 (new formula)

### PR DESCRIPTION
**Pull request by DoomHammer**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
https://github.com/mono/gtk-sharp/releases shows 2.12.41 as the latest release.

**Review by ilovezfs — DISMISSED** [review]
https://github.com/mono/gtk-sharp/releases shows 2.12.41 as the latest release.

**Comment by tschoonj** [comment]
It [looks](http://www.mono-project.com/docs/gui/gtksharp/) like they are hosting downloads on the mono-project servers now, and are no longer using Gnome for that. 2.12.45 is indeed the latest release.

How far along are they in supporting Gtk3? It seems kind of silly adding new formulas that depend on gtk+2 when even gtk+3 had its latest minor release (3.22).

**Comment by ilovezfs** [comment]
>>How far along are they in supporting Gtk3? It seems kind of silly adding new formulas that depend on gtk+2 when even gtk+3 had its latest minor release (3.22).

Yes, this is a good point. We'd be happy to reconsider this software for inclusion in homebrew/core once it has gtk+3 support. Thanks for the PR nonetheless @DoomHammer!

**Pull request closed without merging**
