### PR TITLE
torxakis 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by harcokuppens**
Add a new tool called 'torxakis' which is a tool for Model Based Testing.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
@BrewTestBot test this please

**Comment by vinyldarkscratch** [comment]
@harcokuppens The Brew test bot isn't giving us any meaningful output, unfortunately.  Can you complete the checklist up above, and make sure `torxakis` installs/audits?

**Comment by ilovezfs** [comment]
>  depends_on "cvc4" => :optional

>Error: No available formula with the name "cvc4" 

Also, note building with stack isn't supported unless you can find a way to make it build everything from source. This needs to use `cabal`. See e.g. `agda`, `git-annex`, `hadolint`, etc.

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ brew audit --new-formula torxakis
torxakis:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
Error: 1 problem in 1 formula
iMac-TMP:~ joe$ 
```
You may want to host this software in your own tap: https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap

Thanks for the PR nonetheless @harcokuppens

**Pull request closed without merging**
