### PR TITLE
publish-commit-bottles: revert accidental changes

### PR DESCRIPTION
**Pull request by carlocab**
This reverts commit a8e0bce54eadd1b7cfb91cad4961f5d4c6a27a22.
This reverts commit fbc9fbcbfc2dea88b386f9c15699969b99e708e5.
This reverts commit 79f69746a94fb17163b97328da0f403863ec2d56.

### CODE REVIEW

**Comment by carlocab** [comment]
These are the changes from #15077. I think I worked out now how they made it to `master`, but only learned it a bit too late. Sorry all.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by chenrui333** [comment]
> These are the changes from #15077. I think I worked out now how they made it to `master`, but only learned it a bit too late. Sorry all.

The PR reference seems wrong.

**Comment by ZhongRuoyu** [comment]
Carlo might have copy-pasted that from  Homebrew/brew#15077. It's actually #126884.

**Comment by carlocab** [comment]
> Carlo might have copy-pasted that from [Homebrew/brew#15077](https://github.com/Homebrew/brew/pull/15077). It's actually #126884.

Yep, thanks!

**Pull request merged**
