### PR TITLE
elixir 1.15.0 elixir-ls 0.15.0

### PR DESCRIPTION
**Pull request by levex**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /opt/homebrew/Cellar/elixir-ls/0.14.6/bin/elixir-ls
  Content-Length: 377
  
  
  
  {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"** (MatchError) no match of right hand side value: {:error, :already_present}\n    lib/language_server/cli.ex:20: ElixirLS.LanguageServer.CLI.main/0\n    nofile:1: (file)\n    (stdlib 4.3.1.1) erl_eval.erl:748: :erl_eval.do_apply/7\n    (elixir 1.15.0) lib/code.ex:543: Code.validated_eval_string/3","type":2}}
```

**Comment by chenrui333** [comment]
- also seen the issue in #133327

**Comment by levex** [comment]
Could we build Elixir 1.15.0 with OTP/25? And wait for that issue to be resolved in OTP before we build for /26?

**Comment by chenrui333** [comment]
elixir-ls just made a release to support elixir 1.15, let's see how it goes.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks for the patience!

**Comment by levex** [comment]
Thanks @chenrui333 for helping land this :)

**Pull request merged**
