### PR TITLE
docker-machine-parallels 1.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
@DomT4 line 34.

**Comment by DomT4** [comment]
I saw it, I'm just not sure it's relevant here. As far as I can see it's not calling _this_ executable, but rather checking the mother executable works with this child.

**Comment by ilovezfs** [comment]
Ah ok.

BTW https://github.com/ilovezfs/homebrew-core/blob/1cb1f57f91d9d1b897758e040991d67aedb9548e/Formula/docker-machine-parallels.rb#L30

seems like an unfortunate hack to me and something we currently *ought* to be doing in *every* Go formula that's using the relocation pattern (`path.install Dir["*"]` or `path.install buildpath.children`), which is becoming increasingly common, as opposed to the symlink pattern (`ln_s buildpath, path`), which is becoming less common.

@DomT4 @UniqMartin any thoughts on how we could generalize this so that `prefix.install_metafiles path` doesn't need to be sprinkled all over the place?

**Pull request closed without merging**
