### PR TITLE
Create ext3fuse

### PR DESCRIPTION
**Pull request by zeilen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you add a description detailing why we should ship this alias?

**Comment by zeilen** [comment]
This is a helper for people who are not familar with this.
When people use `brew info ext3fuse` or `brew search ext3fuse` they will see immediately ext2fuse handles ext3.

**Comment by zeilen** [comment]
`brew search ext3` outputs `No formula or cask found for "ext3".`

**Comment by SMillerDev** [comment]
Generally we only use aliases to advertise other names people might know the software by. That doesn't seem to be the case here though. I'd say that advertising features is up to the upstream projects.

**Comment by Bo98** [comment]
We could maybe mention ext3 in the ext2fuse description which would help `brew search --desc` and https://formulae.brew.sh/, but an alias is probably not going to happen unless the software is also known under that name.

**Pull request closed without merging**
