### PR TITLE
cp2k 2024.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by p-linnane** [comment]
Opened an upstream issue: https://github.com/cp2k/cp2k/issues/3200

**Comment by ZhongRuoyu** [comment]
Probably just missing a `wget` dependency on Linux (not sure why it's not needed on macOS, though). Let's see if this works...

**Comment by p-linnane** [comment]
I've iterated through this a few times. It's downloading a feature we don't have enabled, and tries to build anyway. There's more beyond adding `wget` to the whole thing unfortunately.

**Review by ZhongRuoyu — APPROVED** [review]
Thanks @p-linnane!

**Pull request merged**
