### PR TITLE
libressl 2.5.4

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
```
 Stable: The URL https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.5.4.tar.gz is not reachable
```
Yosemite, obviously.

**Comment by DomT4** [comment]
@ilovezfs Can we get this merged? There's a vuln in 2.5.3 which this fixes.

**Comment by ilovezfs** [comment]
@DomT4 thank you for your contribution to Homebrew! :innocent:

**Comment by DomT4** [comment]
@ilovezfs Thanks for the quick reply! ❤️

**Pull request closed without merging**
