### PR TITLE
libbluray: prefer CDN url

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  libbluray:
    * Stable: The source URL https://get.videolan.org/libbluray/1.3.4/libbluray-1.3.4.tar.bz2 is not reachable
```

**Comment by SMillerDev** [comment]
Still the same issue.

**Comment by alebcay** [comment]
Yup. I guess I'm just going to have to manually try `GET`ing the file from each mirror in their rotation and see which one is failing. Still unable to reproduce this locally, might be a geographical thing (mirror closest to Atlanta/Dublin).

**Comment by alebcay** [comment]
I noticed that one of the mirrors based in Cyprus is unreachable. Assuming that the failed CI run is occurring in Dublin, it's possible that the Cyprus mirror is being selected.

I've sent an email to mirrors [at] videolan [dot] org to inquire further.

**Comment by alebcay** [comment]
The VideoLAN maintainers responded to my email and removed the broken mirror from the rotation, and I have subsequently re-ran the CI. So now I really don't know what could be causing this failure.

**Comment by SMillerDev** [comment]
Still failing for one, I think ephemeral runners are in Atlanta

**Comment by alebcay** [comment]
Is there some way to shell/VNC into the instance backing the `12-arm64` runners? I noticed it's that one failing both times and wondering if it's something specific to that instance. (Doesn't have to be me if access/security is a concern.)

Would appreciate if we could get some debug output or some further info about what's happening. This is not to say it's certainly an issue on our side, but I'm at a point where I probably need some more info than "it just doesn't connect" in order to discuss further with the VideoLAN folks.

**Comment by SMillerDev** [comment]
I don't think there is since they get deleted after the run AFAIK. But we might be able to re-run the job with debug mode enabled.

**Comment by alebcay** [comment]
Thanks for re-running with debug mode enabled. It looks like it failed for a different unrelated reason this time:
```
==> brew uninstall --force fontconfig freetype libpng pkg-config
/usr/bin/env brew uninstall --force fontconfig freetype libpng pkg-config
Error: unexpected token at 'opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libbluray.rb
[
  {
    "formula": "libbluray",
    "version": {
      "current": "1.3.4",
      "latest": "1.3.4",
      "outdated": false,
      "newer_than_upstream": false
    },
    "meta": {
      "livecheckable": true,
      "url": {
        "original": "https://download.videolan.org/pub/videolan/libbluray/"
      },
      "strategy": "PageMatch",
      "strategies": [
        "PageMatch"
      ],
      "regex": "/href=[\"']?v?(\\d+(?:\\.\\d+)+)\\/?[\"' >]/i"
    }
  }
]
'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:261:in `livecheck'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:432:in `formula!'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:22:in `block in run!'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:21:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:21:in `run!'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:213:in `run_tests'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:65:in `block in run!'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:53:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:53:in `run!'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:134:in `run!'
/opt/homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/test-bot.rb:103:in `test_bot'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Error: Process completed with exit code 1.
```

**Pull request closed without merging**
