### PR TITLE
gobject-introspection 1.50.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by DomT4** [comment]
Testing failure on a `brew uses` here. Not sure whether that's legit or gunk. The header it is looking for is somewhat buried on macOS, `/usr/include/libxml2/libxml/parser.h`, but our `ENV.libxml2` _should_ be handling that.

**Comment by tschoonj** [comment]
Anything I can do about this?

**Comment by DomT4** [comment]
It seems like `libgdata` is ignoring `CPPFLAGS`, even if I manually dump it in the formula instead of using the existing `ENV.libxml2` helper. However, if I drop `-I/usr/include/libxml2` in the flags passed directly, the test passes fine. I wonder how long that issue has been there.

**Comment by tschoonj** [comment]
Shall I just hardcore the paths in the `libgdata` test then?

**Comment by DomT4** [comment]
We could probably steal & adapt the logic for `ENV.libxml2` for now, yeah:

```ruby
if MacOS::CLT.installed?
  append "CPPFLAGS", "-I/usr/include/libxml2"
else
  # Use the includes form the sdk
  append "CPPFLAGS", "-I#{MacOS.sdk_path}/usr/include/libxml2"
end
```
So maybe:
```ruby
if MacOS::CLT.installed?
  flags << "-I/usr/include/libxml2"
else
  flags << "-I#{MacOS.sdk_path}/usr/include/libxml2"
end
```
Or something.

**Comment by DomT4** [comment]
Looking at some of these other updates locally there's a bunch of 10.12 errors that seem to not be fatal, but I'm not sure if they aren't causing any other issues somewhere along the line.

`gedit`:
```
CPPFLAGS="" CFLAGS="-g -O2" LDFLAGS="" CC="clang" PKG_CONFIG="/usr/local/opt/pkg-config/bin/pkg-config" DLLTOOL="false" CC="clang" /usr/local/Cellar/gobject-introspection/1.48.0/bin/g-ir-scanner  -I. --warn-all --namespace=Gedit --nsversion=3.0 --libtool="/bin/sh ./libtool"  --include=Gtk-3.0 --include=GtkSource-3.0 --pkg-export=gedit --program=./gedit/gedit  -D_REENTRANT -I/usr/local/Cellar/libffi/3.0.13/lib/libffi-3.0.13/include -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.50.0/include/gio-unix-2.0/ -I/usr/local/Cellar/glib/2.50.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.50.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.25/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.6_1/include/cairo -I/usr/local/Cellar/gobject-introspection/1.48.0/include/gobject-introspection-1.0 -I/usr/local/Cellar/gdk-pixbuf/2.36.0/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/atk/2.22.0/include/atk-1.0 -I/usr/local/Cellar/libepoxy/1.3.1/include -I/usr/local/Cellar/harfbuzz/1.3.2/include/harfbuzz -I/usr/local/Cellar/pango/1.40.3/include/pango-1.0 -I/usr/local/Cellar/gtk+3/3.22.1/include/gtk-3.0 -I/usr/local/Cellar/libxml2/2.9.4/include/libxml2 -I/usr/local/Cellar/libpeas/1.20.0/include/libpeas-1.0 -I/usr/local/Cellar/gtksourceview3/3.22.0/include/gtksourceview-3.0 -I/usr/local/Cellar/gsettings-desktop-schemas/3.22.0/include/gsettings-desktop-schemas  --c-include="gedit/gedit-app-activatable.h" --c-include="gedit/gedit-app.h" --c-include="gedit/gedit-commands.h" --c-include="gedit/gedit-debug.h" --c-include="gedit/gedit-document.h" --c-include="gedit/gedit-encodings-combo-box.h" --c-include="gedit/gedit-menu-extension.h" --c-include="gedit/gedit-message-bus.h" --c-include="gedit/gedit-message.h" --c-include="gedit/gedit-progress-info-bar.h" --c-include="gedit/gedit-statusbar.h" --c-include="gedit/gedit-tab.h" --c-include="gedit/gedit-utils.h" --c-include="gedit/gedit-view-activatable.h" --c-include="gedit/gedit-view.h" --c-include="gedit/gedit-window-activatable.h" --c-include="gedit/gedit-window.h" --cflags-begin  --cflags-end  gedit/gedit-app-activatable.h gedit/gedit-app.h gedit/gedit-commands.h gedit/gedit-debug.h gedit/gedit-document.h gedit/gedit-encodings-combo-box.h gedit/gedit-menu-extension.h gedit/gedit-message-bus.h gedit/gedit-message.h gedit/gedit-progress-info-bar.h gedit/gedit-statusbar.h gedit/gedit-tab.h gedit/gedit-utils.h gedit/gedit-view-activatable.h gedit/gedit-view.h gedit/gedit-window-activatable.h gedit/gedit-window.h gedit/gedit-app-activatable.c gedit/gedit-app.c gedit/gedit-close-confirmation-dialog.c gedit/gedit-commands-documents.c gedit/gedit-commands-edit.c gedit/gedit-commands-file.c gedit/gedit-commands-file-print.c gedit/gedit-commands-help.c gedit/gedit-commands-search.c gedit/gedit-commands-view.c gedit/gedit-debug.c gedit/gedit-dirs.c gedit/gedit-document.c gedit/gedit-documents-panel.c gedit/gedit-encoding-items.c gedit/gedit-encodings-combo-box.c gedit/gedit-encodings-dialog.c gedit/gedit-file-chooser-dialog.c gedit/gedit-file-chooser-dialog-gtk.c gedit/gedit-highlight-mode-dialog.c gedit/gedit-highlight-mode-selector.c gedit/gedit-history-entry.c gedit/gedit-io-error-info-bar.c gedit/gedit-menu-extension.c gedit/gedit-menu-stack-switcher.c gedit/gedit-message-bus.c gedit/gedit-message.c gedit/gedit-metadata-manager.c gedit/gedit-multi-notebook.c gedit/gedit-notebook.c gedit/gedit-notebook-popup-menu.c gedit/gedit-notebook-stack-switcher.c gedit/gedit-open-document-selector.c gedit/gedit-open-document-selector-helper.c gedit/gedit-open-document-selector-store.c gedit/gedit-plugins-engine.c gedit/gedit-preferences-dialog.c gedit/gedit-print-job.c gedit/gedit-print-preview.c gedit/gedit-progress-info-bar.c gedit/gedit-recent.c gedit/gedit-replace-dialog.c gedit/gedit-resources.c gedit/gedit-settings.c gedit/gedit-statusbar.c gedit/gedit-status-menu-button.c gedit/gedit-tab.c gedit/gedit-tab-label.c gedit/gedit-utils.c gedit/gedit-view-activatable.c gedit/gedit-view.c gedit/gedit-view-centering.c gedit/gedit-view-frame.c gedit/gedit-window-activatable.c gedit/gedit-window.c gedit/gedit-enum-types.c gedit/gedit-enum-types.h gedit/gedit --output gedit/Gedit-3.0.gir
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:79: syntax error, unexpected identifier, expecting ')' in 'void (* _Nullable bsd_signal(int, void (* _Nullable)(int)))(int);' at 'bsd_signal'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:79: syntax error, unexpected ')', expecting ',' or ';' in 'void (* _Nullable bsd_signal(int, void (* _Nullable)(int)))(int);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:99: syntax error, unexpected identifier, expecting ')' in 'void (* _Nullable sigset(int, void (* _Nullable)(int)))(int);' at 'sigset'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:99: syntax error, unexpected ')', expecting ',' or ';' in 'void (* _Nullable sigset(int, void (* _Nullable)(int)))(int);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:113: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  qos_class_t * _Nullable restrict __qos_class,' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:114: syntax error, unexpected INT, expecting identifier or '(' or '*' in '  int * _Nullable restrict __relative_priority);' at 'int'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:114: syntax error, unexpected ')', expecting ',' or ';' in '  int * _Nullable restrict __relative_priority);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:185: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  qos_class_t * _Nullable restrict __qos_class,' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:186: syntax error, unexpected INT, expecting identifier or '(' or '*' in '  int * _Nullable restrict __relative_priority);' at 'int'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:186: syntax error, unexpected ')', expecting ',' or ';' in '  int * _Nullable restrict __relative_priority);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:243: syntax error, unexpected '*', expecting ')' or ',' in '  void * _Nullable * _Nonnull restrict, size_t * restrict);' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:243: syntax error, unexpected ')', expecting identifier or '(' in '  void * _Nullable * _Nonnull restrict, size_t * restrict);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:247: syntax error, unexpected '*', expecting ')' or ',' in '  void * _Nullable * _Nonnull restrict);' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:295: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const pthread_condattr_t * _Nullable restrict)' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:304: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const struct timespec * _Nullable restrict)' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:326: syntax error, unexpected '*', expecting ')' or ',' in 'int pthread_create(pthread_t _Nullable * _Nonnull restrict,' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:327: syntax error, unexpected ',', expecting identifier or '(' or '*' or ';' in '  const pthread_attr_t * _Nullable restrict,' at ','
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:328: syntax error, unexpected '*' in '  void * _Nullable (* _Nonnull)(void * _Nullable),' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:328: syntax error, unexpected ')', expecting ',' or ';' in '  void * _Nullable (* _Nonnull)(void * _Nullable),' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:329: syntax error, unexpected ')', expecting identifier or '(' or '*' or ';' in '  void * _Nullable restrict);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:349: syntax error, unexpected RESTRICT, expecting ')' or ',' in 'int pthread_getschedparam(pthread_t , int * _Nullable restrict,' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:350: syntax error, unexpected ')', expecting identifier or '(' or '*' or ';' in '  struct sched_param * _Nullable restrict);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:353: syntax error, unexpected identifier, expecting ',' or ';' in 'void* _Nullable pthread_getspecific(pthread_key_t);' at 'pthread_getspecific'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:356: syntax error, unexpected '*', expecting ')' or ',' in 'int pthread_join(pthread_t , void * _Nullable * _Nullable)' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:374: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const pthread_mutexattr_t * _Nullable restrict);' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:432: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const pthread_rwlockattr_t * _Nullable restrict)' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:529: syntax error, unexpected '*', expecting ')' or ',' in '  pthread_t _Nullable * _Nonnull, const pthread_attr_t * _Nullable,' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected VOID, expecting identifier or '(' or '*' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at 'void'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected '*' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected ')', expecting ',' or ';' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected ')', expecting ',' or ';' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at ')'
```
Strange.

**Comment by ilovezfs** [comment]
It appears to have no impact on the output file Gedit-3.0.gir, which is the same as the file in the 3.20.2 bottle, so I think I wouldn't worry about it.

**Comment by tschoonj** [comment]
The `libgdata` Formula has been updated

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/dd5c883a6897e3e9171121e7ca2ad3a12d1f8d17 and https://github.com/Homebrew/homebrew-core/commit/87a4b4394e604592d04fee064b1fc06394bcb711. Thanks Tom 😃.

**Comment by tschoonj** [comment]
You're welcome!

**Pull request closed without merging**
