### PR TITLE
webpack 4.1.0

### PR DESCRIPTION
**Pull request by chrmoritz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is a workaround for `webpack` 4.x (Refs: https://github.com/Homebrew/homebrew-core/pull/24517) to continue installing it globally with homebrew (although [upstream has always recommended against it](https://webpack.js.org/guides/installation/#global-installation)).

This PR adds a new resource `webpack-cli` (where all CLI code now lives) and installs both packages together to `libexec` by using the trick to declare `webpack` as a bundled dependency of `webpack-cli`.

Also for backwards compatibility it still installs a symlink called `webpack`, although the new official binary name is `webpack-cli` now.

### CODE REVIEW

**Comment by chrmoritz** [comment]
```
npm verb stack FetchError: request to https://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
```

The high sierra bot again, but I wanted to do one more little change anyway.

**Comment by chrmoritz** [comment]
@MikeMcQuaid Do you know why I'm getting nearly consistently at least one `ENOTFOUND registry.npmjs.org` on `high_sierra_stadium_1` while all other bots (high_sierra_stadium_2 and sierra/el_capitan ones) doesn't seem to have problems accessing the npm registry at the same time?

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19865/
* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19864/
* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19809/
* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19752/
* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19749/
* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19740/

**Comment by ilovezfs** [comment]
I've now rebooted that vm.

**Comment by ilovezfs** [comment]
Thanks again @chrmoritz! ✅

**Pull request closed without merging**
