### PR TITLE
Remove ctunnel

### PR DESCRIPTION
**Pull request by queengooborg**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

`ctunnel` isn't noteable enough, and the download is broken as it is.  Probably better just to remove it?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
I think they fixed the download.

**Comment by vinyldarkscratch** [comment]
Oops -- what's embarrassing is the fact that _I_ confirmed it was working again!  Heheh...

There's still the issue of it not being noteable enough (doesn't meet the minimum watchers/stars/forks), but at least we've got a download.  😛

**Comment by ilovezfs** [comment]
>There's still the issue of it not being noteable enough (doesn't meet the minimum watchers/stars/forks)

only applies to `--new-formula`

**Comment by vinyldarkscratch** [comment]
Makes sense -- if it's in Homebrew, no need to take it out!

**Pull request closed without merging**
