### PR TITLE
upx 3.95

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by javian** [comment]
I created https://github.com/upx/upx/issues/218

**Comment by javian** [comment]
@DomT4 a patch is now available in the linked issue

**Comment by javian** [comment]
```
patch do
   url "https://github.com/upx/upx/commit/0dac6b7be3339ac73051d40ed4d268cd2bb0dc7c.patch?fullindex=1"
   sha256 "71f4048ba4edc4c4530ebdce63193503430d75110f35f0989726b7cfb00867f7"
end
```

**Comment by DomT4** [comment]
@javian Mind submitting a PR to replace mine? ❤️

**Comment by javian** [comment]
Absolutely not ^^

**Pull request closed without merging**
