### PR TITLE
Grafana 4.2.0

### PR DESCRIPTION
**Pull request by torkelo**
Version update to 4.2.0 and changed yarn to proper homebrew dependency. 

Tested and build works on my macbook running Sierra.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```

Running "karma:test" (karma) task
22 03 2017 15:14:53.207:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
22 03 2017 15:14:53.208:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
22 03 2017 15:14:53.212:INFO [launcher]: Starting browser PhantomJS
22 03 2017 15:14:53.454:ERROR [phantomjs.launcher]: 2017-03-22 15:14:53.453 phantomjs[72127:8788399] -[_NSXPCDistantObjectWithError performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: unrecognized selector sent to instance 0x7f8bf390cff0

22 03 2017 15:14:53.454:ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

22 03 2017 15:14:53.454:ERROR [launcher]: Cannot start PhantomJS
	
22 03 2017 15:14:53.457:INFO [launcher]: Trying to start PhantomJS again (1/2).
22 03 2017 15:14:53.681:ERROR [phantomjs.launcher]: 2017-03-22 15:14:53.680 phantomjs[72129:8788550] -[_NSXPCDistantObjectWithError performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: unrecognized selector sent to instance 0x7f8608701c40

22 03 2017 15:14:53.681:ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

22 03 2017 15:14:53.681:ERROR [launcher]: Cannot start PhantomJS
	
22 03 2017 15:14:53.682:INFO [launcher]: Trying to start PhantomJS again (2/2).
22 03 2017 15:14:53.913:ERROR [phantomjs.launcher]: 2017-03-22 15:14:53.912 phantomjs[72130:8788709] -[_NSXPCDistantObjectWithError performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: unrecognized selector sent to instance 0x7fd19303dfe0

22 03 2017 15:14:53.913:ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

22 03 2017 15:14:53.913:ERROR [launcher]: Cannot start PhantomJS
	
22 03 2017 15:14:53.914:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
Warning: Task "karma:test" failed. Use --force to continue.

Aborted due to warnings.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: node_modules/grunt-cli/bin/grunt build
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 
```
Same problem as identified on the other PR.

**Comment by torkelo** [comment]
Strange, looks to be an issue with phantomjs and osx sandbox mode? I am not getting any error on macbooks I have tested running it on. 

https://github.com/ariya/phantomjs/issues/13876

We have not changed anything related to running phantomjs based tests, since 4.0, anything changed with how you build bottles? 

Should we do like others have disable phantomjs tests when building the bottle? https://github.com/SalzzZ/rules_closure/commit/10148fd3a8def9c35bb4bf3cec3f1d0fc0da3875

**Comment by dunn** [comment]
Sorry for the delay on this, but could you rebase it against the latest master?

**Comment by torkelo** [comment]
ok, opened new rebased PR https://github.com/Homebrew/homebrew-core/pull/11991

**Pull request closed without merging**
