### PR TITLE
opencv 4.5.4

### PR DESCRIPTION
**Pull request by cclauss**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

Recapitulates #87064 and #89948

### CODE REVIEW

**Comment by cclauss** [comment]
@alalek Can you or someone on your team please help us to land the [current release of OpenCV](https://github.com/opencv/opencv/releases) on homebrew?  This is our third attempt after #87064 and #89945 but we have not yet found the secret sauce.

**Comment by alalek** [comment]
No idea on which OpenCV error should we take a look. OpenCV 4.5.3->4.5.4 update doesn't bring new dependencies.

There are reported several Apple M1 issues from other packages.
Changing with just adding new empty line probably would emit the same errors (IMO, it is Homebrew infrastructure issue).

Could we disable M1 platform or some dependencies which are not ready for M1 in OpenCV formula to unblock upgrade?

**Comment by SMillerDev** [comment]
> Could we disable M1 platform or some dependencies which are not ready for M1 in OpenCV formula to unblock upgrade?

Well, it works for the current version so that would break anything using OpenCV for anyone on ARM.

@cclauss the compilation doesn't fail for OpenCV so getting their developers to help won't add much. We need to fix the formulae that actually break.

**Comment by alalek** [comment]
> Well, it works for the current version

Open a new PR with adding new empty line into opencv.rb and ensure that Homebrew QA fails.
So it doesn't work actually. It just doesn't launched.

---

Infrastructure problem should be fixed by dropping of unmaintained dependencies: #90371

**Comment by cclauss** [comment]
The builds on M1 Macs work fine but the builds on Intel Macs timeout.

**Comment by cclauss** [comment]
Nice!

**Review by SMillerDev — DISMISSED** [review]
Thanks @cclauss  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by cclauss** [comment]
Will the bots merge a passing PR that has a [label: `test failure`](https://github.com/Homebrew/homebrew-core/labels/test%20failure)?

**Comment by SMillerDev** [comment]
No, but the `automerge-skip` label does. Try squashing all commits into one.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
