### PR TITLE
duckdb 0.2.4

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Hmm... build error suggests this might need c++14/17?

**Comment by chenrui333** [comment]
according to the site, it requires c++11

```
Simple
In-process, embedded
C++11, no dependencies, single file build
APIs for Python/R/Java/…
```

**Comment by domoritz** [comment]
Pinging @hannesmuehleisen for suggestions.

Screen Shot 2021-02-26 at 22 56 24

**Comment by carlocab** [comment]
Superseded by #73274.

**Pull request closed without merging**
