### PR TITLE
nvm 0.33.5

### PR DESCRIPTION
**Pull request by bepsvpt**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Sorry @BePsvPT :robot: but https://github.com/creationix/nvm/releases/latest still shows 0.33.4 as the latest version. But thanks nonetheless!

**Comment by BePsvPT** [comment]
@ilovezfs only release version should be updated instead of tag version?

**Comment by ilovezfs** [comment]
@BePsvPT correct (unless there are no explicit releases and there are only tags). If you suspect that the new tag actually _should_ be the latest release but someone hasn't marked it as such then a new issue needs to be filed such as these:
https://github.com/JFrogDev/jfrog-cli-go/issues/102
https://github.com/tracebox/tracebox/issues/52
https://github.com/etr/libhttpserver/issues/114
etc.
in order to prompt upstream to create a new explicit release.

**Comment by BePsvPT** [comment]
@ilovezfs thanks for explanation.

**Comment by ilovezfs** [comment]
@BePsvPT no worries :)

**Pull request closed without merging**
