### PR TITLE
Upgrade libosmium to 2.12.0

### PR DESCRIPTION
**Pull request by Zverik**
Updating `libosmium` to the latest v2.12.0.

### CODE REVIEW

**Review by JCount — DISMISSED** [review]
Please break this into two PRs. Adding a new formula and upgrading an existing one need to be able to be evaluated separately. Thanks.

**Comment by Zverik** [comment]
Done.

**Comment by JCount** [comment]
@Zverik Thank you for your contribution to Homebrew! 🎉

**Comment by Zverik** [comment]
Awesome, thanks!

**Pull request closed without merging**
