### PR TITLE
dosbox-staging 0.79.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`  ../meson.build:340:0: ERROR: Dependency 'iir' is required but not found.`

**Comment by carlocab** [comment]
Needs https://github.com/berndporr/iir1

**Comment by cho-m** [comment]
Adding `iir1` in #112595

**Comment by cho-m** [comment]
Linux:
```
Error: The `brew link` step did not complete successfully
  Could not symlink include/speex/speex_echo.h
  Target /home/linuxbrew/.linuxbrew/include/speex/speex_echo.h
  is a symlink belonging to speexdsp. You can unlink it:
    brew unlink speexdsp
```

**Comment by carlocab** [comment]
Needs a `speexdsp` dep. Also vendoring https://github.com/wolfpld/tracy.

**Comment by carlocab** [comment]
```
Dependencies with no linkage:
  libslirp
  opusfile
  speexdsp
```
Hmmm...

**Comment by cho-m** [comment]
Upstream automatically falls back to vendored copy if floating point checks fail so may need to check on this from meson log output. https://github.com/dosbox-staging/dosbox-staging/blob/v0.79.1/meson.build#L379-L403

**Comment by cho-m** [comment]
They are found, e.g.
```
Run-time dependency speexdsp found: YES 1.2.1
Checking if "SpeexDSP system library has reliable floating-point API" with dependency speexdsp runs: YES
Run-time dependency speexdsp found: YES 1.2.1
```

But statically linked:
```
[237/237] clang++  -o dosbox dosbox.p/meson-generated_.._version.cpp.o dosbox.p/src_main.cpp.o dosbox.p/src_dosbox.cpp.o dosbox.p/src_libs_ghc_fs_std_impl.cpp.o -flto -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -Wl,-rpath,/usr/local/lib src/misc/libmisc.a src/libs/loguru/libloguru.a src/libs/whereami/libwhereami.a src/cpu/libcpu.a src/dos/libdos.a src/libs/decoders/libdecoders.a src/fpu/libfpu.a src/gui/libgui.a src/libs/ppscale/libppscale.a src/hardware/libhardware.a src/libs/nuked/libnuked.a src/libs/residfp/libresidfp.a src/libs/YM7128B_emu/libym7128bemu.a src/libs/zmbv/libzmbv.a src/ints/libints.a src/midi/libmidi.a src/shell/libshell.a src/libs/sdlcd/libsdlcd.a src/libs/tal-chorus/libtalchorus.a /usr/local/lib/libSDL2.dylib -L/usr/local/Cellar/iir1/1.9.3/lib -liir -framework CoreFoundation /usr/local/Cellar/libslirp/4.7.0/lib/libslirp.a /usr/local/Cellar/glib/2.74.0/lib/libglib-2.0.a /usr/local/opt/gettext/lib/libintl.a -framework Foundation -framework CoreFoundation -framework AppKit -framework Carbon -lm /usr/local/Cellar/pcre2/10.40/lib/libpcre2-8.a -pthread -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/pcre2/10.40/lib -L/usr/local/Cellar/glib/2.74.0/lib -L/usr/local/Cellar/libslirp/4.7.0/lib -lresolv -liconv -ldl -L/usr/local/Cellar/iir1/1.9.3/lib -liir /usr/local/Cellar/opusfile/0.12/lib/libopusfile.a /usr/local/Cellar/libogg/1.3.5/lib/libogg.a /usr/local/Cellar/opus/1.3.1/lib/libopus.a -framework OpenGL -L/usr/local/Cellar/iir1/1.9.3/lib -liir -L/usr/local/Cellar/iir1/1.9.3/lib -liir -framework Foundation -framework CoreFoundation -framework AppKit -framework Carbon -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/pcre2/10.40/lib -L/usr/local/Cellar/glib/2.74.0/lib -L/usr/local/Cellar/libslirp/4.7.0/lib -lresolv -liconv /usr/local/Cellar/libpng/1.6.38/lib/libpng16.a -L/usr/local/Cellar/libpng/1.6.38/lib -lz /usr/local/lib/libSDL2_net.dylib /usr/local/Cellar/speexdsp/1.2.1/lib/libspeexdsp.a -lz -Wl,-framework,CoreAudio,-framework,AudioUnit -Wl,-framework,CoreMIDI,-framework,CoreServices /usr/local/Cellar/glib/2.74.0/lib/libgthread-2.0.a -framework Foundation -framework CoreFoundation -framework AppKit -framework Carbon -D_THREAD_SAFE /usr/local/Cellar/flac/1.4.1/lib/libFLAC.a /usr/local/Cellar/libvorbis/1.3.7/lib/libvorbisenc.a /usr/local/Cellar/libvorbis/1.3.7/lib/libvorbis.a /usr/local/Cellar/portaudio/19.7.0/lib/libportaudio.a -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework CoreFoundation -framework CoreServices /usr/local/Cellar/readline/8.2.1/lib/libreadline.a -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/pcre2/10.40/lib -L/usr/local/Cellar/glib/2.74.0/lib -L/usr/local/Cellar/libogg/1.3.5/lib -L/usr/local/Cellar/flac/1.4.1/lib -L/usr/local/Cellar/libvorbis/1.3.7/lib -L/usr/local/Cellar/opus/1.3.1/lib -L/usr/local/Cellar/libsndfile/1.1.0_1/lib -L/usr/local/Cellar/portaudio/19.7.0/lib -L/usr/local/Cellar/readline/8.2.1/lib -L/usr/local/Cellar/fluid-synth/2.3.0/lib -lfluidsynth -liconv -lsndfile -lncurses -L/usr/local/Cellar/mt32emu/2.7.0/lib -lmt32emu -framework CoreAudio -framework AudioUnit -framework AudioToolbox -framework CoreMIDI -framework CoreFoundation -L/usr/local/Cellar/iir1/1.9.3/lib -liir -framework CoreServices
````
- `/usr/local/Cellar/flac/1.4.1/lib/libFLAC.a`
- `/usr/local/Cellar/glib/2.74.0/lib/libglib-2.0.a`
- `/usr/local/Cellar/glib/2.74.0/lib/libgthread-2.0.a`
- `/usr/local/Cellar/libogg/1.3.5/lib/libogg.a`
- `/usr/local/Cellar/libpng/1.6.38/lib/libpng16.a`
- `/usr/local/Cellar/libslirp/4.7.0/lib/libslirp.a`
- `/usr/local/Cellar/libvorbis/1.3.7/lib/libvorbis.a`
- `/usr/local/Cellar/libvorbis/1.3.7/lib/libvorbisenc.a`
- `/usr/local/Cellar/opus/1.3.1/lib/libopus.a`
- `/usr/local/Cellar/opusfile/0.12/lib/libopusfile.a`
- `/usr/local/Cellar/pcre2/10.40/lib/libpcre2-8.a`
- `/usr/local/Cellar/portaudio/19.7.0/lib/libportaudio.a`
- `/usr/local/Cellar/readline/8.2.1/lib/libreadline.a`
- `/usr/local/Cellar/speexdsp/1.2.1/lib/libspeexdsp.a`
- `/usr/local/lib/libSDL2_net.dylib`
- `/usr/local/opt/gettext/lib/libintl.a`

**Comment by carlocab** [comment]
Better:
```
==> brew linkage --cached dosbox-staging
System libraries:
  /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
  /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
  /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /opt/homebrew/opt/fluid-synth/lib/libfluidsynth.3.dylib (fluid-synth)
  /opt/homebrew/opt/iir1/lib/libiir.1.dylib (iir1)
  /opt/homebrew/opt/libpng/lib/libpng16.16.dylib (libpng)
  /opt/homebrew/opt/libslirp/lib/libslirp.0.dylib (libslirp)
  /opt/homebrew/opt/mt32emu/lib/libmt32emu.2.dylib (mt32emu)
  /opt/homebrew/opt/opusfile/lib/libopusfile.0.dylib (opusfile)
  /opt/homebrew/opt/sdl2/lib/libSDL2-2.0.0.dylib (sdl2)
  /opt/homebrew/opt/sdl2_net/lib/libSDL2_net-2.0.0.dylib (sdl2_net)
  /opt/homebrew/opt/speexdsp/lib/libspeexdsp.1.dylib (speexdsp)
```

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
