### PR TITLE
mongo-atlas-cli: remove podman dependency

### PR DESCRIPTION
**Pull request by jeroenvervaeke**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Hi,

I'm a member of the team that works on the atlas cli.
We've removed the dependency on podman in our cli, this PR reflects those changes.

Thanks for reviewing!

### CODE REVIEW

**Comment by branchvincent** [comment]
we just need to remove the version, so just `mongo-atlas-cli: remove podman dependency`

**Comment by jeroenvervaeke** [comment]
> we just need to remove the version, so just `mongo-atlas-cli: remove podman dependency`

I've tried that before. I've reverted to that state, doesn't seem to work either.
I'm following the wiki to have a short description, then 2 blank lines and then a longer description.

**Comment by jeroenvervaeke** [comment]
I've tried multiple things:
- get rid of multiline long description in commit
- make long description message shorter
- alternate between 2 and 3 new lines characters in between summary and the long description

This is the command I've used for my  last attempt but it still seems broken:
```
git commit --amend -S -m $'mongo-atlas-cli: remove podman dependency\n\n\nmongo-atlas-cli no longer has a dependency on podman.'
```

Any suggestions on how I can fix this?

**Comment by bevanjkay** [comment]
> Any suggestions on how I can fix this?

The token is incorrect in the commit it should be `mongodb-atlas-cli` not `mongo-atlas-cli`.

**Comment by jeroenvervaeke** [comment]
Thanks @bevanjkay, that did the trick!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
