### PR TITLE
gopls 0.8.4

### PR DESCRIPTION
**Pull request by jidicula**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by SteVwonder** [comment]
Not sure if this is the right place to report this, but it looks like this version bump caused quite a few bottles for various architecture to no longer be present: https://github.com/Homebrew/homebrew-core/commit/2cc8a414b4d8172f20b8debca209d73a07d49978

**Comment by jidicula** [comment]
@SteVwonder in the meantime are you able to install the latest version of `gopls` with `go install golang.org/x/tools/gopls@latest`?

**Comment by gedge** [comment]
@SteVwonder - yes, I can `go install` (on my `darwin_amd64` arch)

**Comment by alebcay** [comment]
Thanks for pointing out this issue, I've brought it to attention with some other maintainers. In the meanwhile, `brew install --build-from-source gopls` should continue to work (although it may pull in `go` as a build dep).

**Comment by alebcay** [comment]
Missing bottles built in https://github.com/Homebrew/homebrew-core/actions/runs/2380510447. Hopefully a fix for the sporadic CI issue that caused the bottles to go missing in the first place is available at https://github.com/Homebrew/brew/pull/13321.

**Comment by chenrui333** [comment]
Thanks @SteVwonder for reporting this up. Thanks @alebcay for kicking a run to fix it. 👍

**Pull request closed without merging**
