### PR TITLE
docker-machine-driver-hyperkit: deprecate as it is unmaintained

### PR DESCRIPTION
**Pull request by andig**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks @andig. Please use Homebrew/core style when writing your commit messages, like so:
```
docker-machine-driver-hyperkit: deprecate as it is unmaintained
```
(or similar)

**Comment by alebcay** [comment]
Just curious, do you have any information about this being unmaintained?

**Comment by andig** [comment]
> Just curious, do you have any information about this being unmaintained?

I've checked the latest commits, see my comment above. Relying on deb in 2021 is unmaintained imho.

> docker-machine-driver-hyperkit: deprecate as it is unmaintained

@carlocab could you change these when squashing the commits this time? Will do in future...

**Comment by andig** [comment]
`dep` is deprecated according to https://github.com/golang/go/issues/38158. I did not analyze if we could provide a non-dep build. If that were possible, it would not require deprecation. If not I'd rather deprecate these than not have go 1.17 ;)

**Comment by carlocab** [comment]
We should verify first that it is impossible to build this without `dep` before deprecating it.

**Comment by andig** [comment]
Only has `Gopkg.toml`, no `go.mod`. One can:

- go mod init github.com/machine-drivers/docker-machine-driver-hyperkit
- go mod vendor
- go mod tidy
- patch the makefile to get rid of the vendor target
- ... and build

but why should we? It is unmaintained and has already caused pain during the go 1.16 cycle.

**Comment by SMillerDev** [comment]
> but why should we? It is unmaintained and has already caused pain during the go 1.16 cycle.

Because almost 500 people install it every month. Unless there is no way to fix this these people expect Homebrew packages to keep working.

**Comment by andig** [comment]
> Because almost 500 people install it every month. Unless there is no way to fix this these people expect Homebrew packages to keep working.

I fully understand. However, it is an abandoned product. If people keep expecting it to work they will have to face final breakdown sooner or later. You can keep it half-alive by patching everything in Homebrew or fork the repo and adopt the necessary changes at the root. 

I'm personally using Homebrew for simplicity of use. My personal preference would be not fixing outdated stuff where it hinders staying up to date with current releases, unless it can be done upstream.

This is of course personal taste. Happy to have this PR closed for a better solution.

**Comment by gromgit** [comment]
I've pinged upstream to resolve the current situation in an appropriate manner. Let's see what happens.

**Comment by SMillerDev** [comment]
> I fully understand. However, it is an abandoned product.

So we patch it and mark it deprecated, and next Go release we could drop it completely. Since people will have had some warning.

**Comment by andig** [comment]
Will update with patch

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
