### PR TITLE
pter 3.10.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
looks like still has some issue with py3.12 cc @vonshednob

`  Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/pter-test-20231016-7082-197tj9y/todo.txt`

**Comment by vonshednob** [comment]
I do not understand enough about homebrew or the test that's implemented in pter.rb to be of any help, sorry.

Maybe the original author @BuonOmo can be of help?

**Comment by BuonOmo** [comment]
I'm afraid I cannot now and for a long time. I'm traveling without a laptop. I hope you'll get it sorted out. It seems to be all in the test section :)

**Comment by chenrui333** [comment]
> I do not understand enough about homebrew or the test that's implemented in pter.rb to be of any help, sorry.
> 
> Maybe the original author @BuonOmo can be of help?

I can repro this issue with py3.12 (a simple virtualenv run in macos machine)

any logs that you need me dump out?

**Comment by chenrui333** [comment]
reverting the python dep change for now.

**Pull request merged**
