### PR TITLE
[makensis] Bump to 2.51

### PR DESCRIPTION
**Pull request by idleberg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by tdsmith** [comment]
Build failing; looks like something isn't been quoted when it should be:

```
scons: Building targets ...
/usr/bin/clang++ -stdlib=libstdc++ -o build/release/makensis/build.o -c -Wno-non-virtual-dtor -Wall -O2 -DNSISCALL=__attribute__((__stdcall__)) -D__BIG_ENDIAN__ -D_WIN32_IE=0x0500 -Ibuild/release/config Source/build.cpp
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `/usr/bin/clang++ -stdlib=libstdc++ -o "build/release/makensis/build.o" -c -Wno-non-virtual-dtor -Wall -O2 -DNSISCALL=__attribute__((__stdcall__)) -D__BIG_ENDIAN__ -D_WIN32_IE=0x0500 -Ibuild/release/config "Source/build.cpp"'
scons: *** [build/release/makensis/build.o] Error 2
scons: building terminated because of errors.
```

**Comment by idleberg** [comment]
Awaiting feedback from the developers, hold tight

**Comment by idleberg** [comment]
This requires a fix from the developers, so I'm closing this PR.

**Comment by tdsmith** [comment]
Thanks for the PR and for following up!

**Pull request closed without merging**
