### PR TITLE
curl 7.53.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
Tests are failing, but they don't appear related to this patch. Not sure what the correct fix is.

**Comment by rakkesh** [comment]
```
from grabber import urlgrab, urlopen, urlread
  File "/usr/local/Cellar/osc/0.155.1/libexec/lib/python2.7/site-packages/urlgrabber/grabber.py", line 427, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
Error: osc: failed
```
@alex probably need to revision bump `osc`.

**Comment by alex** [comment]
Good call, we are green!

**Review by JCount — CHANGES_REQUESTED** [review]
Curl now only supports `libidn2` which we currently do not have a formula for. If you could remove the `libidn` option, the related deprecated_options, the optional dependency, and the configure flag, it'd be great. It doesn't make any sense to be shipping a formula with a completely broken option, so I am thanking you ahead of time, thanks! 😄

**Comment by alex** [comment]
@JCount done.

**Comment by alex** [comment]
And we're green again.

**Review by JCount — APPROVED** [review]

**Comment by JCount** [comment]
@alex Thank you for your work, (and patience), on the PR! 😸

**Pull request closed without merging**
