### PR TITLE
mabel 0.1.6

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
This has not been marked as the latest release on GitHub

**Comment by Porkepix** [comment]
> This has not been marked as the latest release on GitHub

Then why is this using tags rather than release `.zip`? That's what induced the livecheck finding `0.1.6`.

**Comment by SMillerDev** [comment]
Because it needs to have git info to build

**Comment by iMichka** [comment]
I've asked upstream

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
