### PR TITLE
kafka, sonarqube, questdb: run tests (debug)

### PR DESCRIPTION
**Pull request by iMichka**
These 3 tests seem to always be broken, wondering if it is related.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by branchvincent** [comment]
`kafka` was fixed in https://github.com/Homebrew/homebrew-core/pull/133887

**Comment by SMillerDev** [comment]
Maybe SonarQube is just too slow?

**Comment by branchvincent** [comment]
Conclusion: definitely related 😄 

They are all the same issue as `kafka` https://github.com/Homebrew/homebrew-core/pull/133887#issuecomment-1679907729: scripts using `ps | grep long-process-name` but output is truncated to `$COLUMNS`

Fixes
* sonarqube:  #141658
* questdb: #141659

**Comment by iMichka** [comment]
Cool thanks for the fixes!

**Pull request closed without merging**
