### PR TITLE
txr 249

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
On ARM:
```
Undefined symbols for architecture arm64:
  "_jmp_restore", referenced from:
      _uw_unwind_to_exit_point in unwind.o
      _uw_abscond_to_exit_point in unwind.o
  "_jmp_save", referenced from:
      _txr_main in txr.o
      _parse_once in y.tab.o
      _parse in y.tab.o
      _v_fun in match.o
      _v_load in match.o
      _do_txeval in match.o
      _complex_open in match.o
      ...
ld: symbol(s) not found for architecture arm64
```

**Comment by gromgit** [comment]
As I mentioned [here](https://github.com/Homebrew/homebrew-core/pull/69461#issuecomment-764419098), `__aarch64__` may be the key to resolving the ARM build failure. Try building with `make PLATFORM_CFLAGS=-D__aarch64__`.

**Comment by gromgit** [comment]
> `ENV["PLATFORM_CFLAGS"] = "-D__aarch64__" if Hardware::CPU.arm?`

I think you actually have to pass the define as a command-line argument:
```
$ PLATFORM_CFLAGS=-D__aarch64__ make -n
...
cmd='cc -MMD -MT opt/jmp.o  -iquote . -std=c99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200112 -D_GNU_SOURCE -Wall -Wextra -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=strict-prototypes -Werror=old-style-definition -fno-diagnostics-show-caret -g -c -o opt/jmp.o jmp.S' ; if ! eval "$cmd" ; then printf "make: failing command:\n%s\n" "$cmd"; exit 1; fi

$ make -n PLATFORM_CFLAGS=-D__aarch64__ 
...
cmd='cc -MMD -MT opt/jmp.o  -iquote . -std=c99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200112 -D_GNU_SOURCE -Wall -Wextra -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=strict-prototypes -Werror=old-style-definition -fno-diagnostics-show-caret -g -D__aarch64__ -c -o opt/jmp.o jmp.S' ; if ! eval "$cmd" ; then printf "make: failing command:\n%s\n" "$cmd"; exit 1; fi
```

**Comment by carlocab** [comment]
Ugh, ok. Setting environment variables always worked for me otherwise...

**Comment by gromgit** [comment]
Huh, I'm out of ideas. Dropping an email to upstream for help...

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
