### PR TITLE
gcc@4.9: patch for Xcode 9

### PR DESCRIPTION
**Pull request by fxcoudert**
See #14418

### CODE REVIEW

**Comment by fxcoudert** [comment]
Patch allows compilation to proceed further, but it fails in building stage1 libdstdc++ with:

```
In file included from /usr/include/Availability.h:194:0,
                 from /usr/include/stdlib.h:61,
                 from /private/tmp/gcc@4.9-20170904-25667-7vg3pb/gcc-4.9.4/build/x86_64-apple-darwin17.0.0/li
bstdc++-v3/include/cstdlib:72,
                 from ../../../../libstdc++-v3/libsupc++/atexit_thread.cc:25:
/usr/include/AvailabilityInternal.h:25584:74: error: missing binary operator before token "("
 #if defined(__has_feature) && defined(__has_attribute) && __has_attribute(availability)
                                                                          ^
In file included from /usr/include/stdlib.h:61:0,
                 from /private/tmp/gcc@4.9-20170904-25667-7vg3pb/gcc-4.9.4/build/x86_64-apple-darwin17.0.0/libstdc++-v3/include/cstdlib:72,
                 from ../../../../libstdc++-v3/libsupc++/atexit_thread.cc:25:
/usr/include/Availability.h:387:74: error: missing binary operator before token "("
 #if defined(__has_feature) && defined(__has_attribute) && __has_attribute(availability)
                                                                          ^
```

Since this is in system headers, not sure how easy it will be to avoid.

**Comment by fxcoudert** [comment]
This error about `__has_attribute` in the `Availability.h` system header is actually a bug in Apple's 10.13 headers.

I've reported it to Apple: radar #34309937, whose content is the following: https://gist.github.com/fxcoudert/f5c6a3b5ae61461c56ebeedb2dc2b56b

**Comment by fxcoudert** [comment]
The 10.13 patch combines two fixes:

- unparallelize the libstdc++ headers installation, as was done for other GCC versions: https://github.com/Homebrew/homebrew-core/pull/17557
- fix the `__has_attribute` issue by using GCC's `fixinclude` mechanism on `Availability.h`, `AvailabilityInternal.h`, and `os/availability.h`. This is similar to what was done for other versions of GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61407

**Comment by ilovezfs** [comment]
CC @jeremyhu RE: https://github.com/macports/macports-ports/commit/449b6b5b24b65a8caa2521dbd7ca83a43780e0a9

**Pull request merged**
