### PR TITLE
libdrawtext 0.3

### PR DESCRIPTION
**Pull request by ilovezfs**
- remove glew dependency
- install examples
- install font2glyphmap tool
- add a test

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @DomT4

**Comment by DomT4** [comment]
Possibly one of the better URLs I've ever seen that. LGTM, nice work! 🚢 when 🍏.

**Comment by ilovezfs** [comment]
We could spoil the fun and use the GitHub archive tarball instead for the sake of https :trollface:

**Comment by DomT4** [comment]
Perhaps someone could preach the good word of `Let's Encrypt` to upstream 😜.

**Comment by ilovezfs** [comment]
surely you mean Certbot
*pukes*

**Comment by DomT4** [comment]
Technically speaking, `Let's Encrypt` is still the body that provides the certs. They just handed technical development of the client over to EFF, who renamed it to avoid confusion. But yeah, `certbot` is a little generic.

**Comment by DomT4** [comment]
Looks like the upstream `GLEW` removal wasn't entirely complete:
```
gcc -dynamiclib -o libdrawtext.dylib src/draw.o src/drawgl.o src/drawrast.o src/font.o src/utf8.o -L/usr/local/Cellar/libdrawtext/0.3/lib `pkg-config --libs freetype2` -framework OpenGL -lGLEW
ld: library not found for -lGLEW
```

**Comment by ilovezfs** [comment]
Yup, Makefile.in has a straggler.

**Comment by ilovezfs** [comment]
Mavericks failure is a ruby 1.8.7 issue. I'll take a look.

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by ilovezfs** [comment]
Woo hoo! upstream merged https://github.com/jtsiomb/libdrawtext/pull/2

**Comment by DomT4** [comment]
Nice work. 👍 whenever you're happy.

**Pull request closed without merging**
