### PR TITLE
lzws 1.4.1 (new formula)

### PR DESCRIPTION
**Pull request by andrew-aladev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by andrew-aladev** [comment]
> GitHub fork (not canonical repository)

Please provide a way to suppress this warning, I don't want to defork, it provides information about project history.

**Comment by carlocab** [comment]
Even if we could suppress that warning, we would get another one:
```
lzws:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

**Comment by andrew-aladev** [comment]
Ok, thank you.

**Comment by carlocab** [comment]
Sure. When your project becomes more widely adopted, you can consider submitting it again for inclusion in homebrew/core. If you decide to do that again, please include an explanation of how your project differs from the repo that you forked.

In the meantime, you may wish to host this formula in your own tap. Here are some related docs:
https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Pull request closed without merging**
