### PR TITLE
macvim 8.0-121

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
@ilovezfs You are fast! <3

**Comment by ilovezfs** [comment]
@neutric :smile: 

mind rebasing so it's just one commit?

**Comment by neutric** [comment]
@ilovezfs I hope this is how you wanted it! Thanks so much for your fix!

**Comment by ilovezfs** [comment]
:100: Thanks for the update!

**Pull request closed without merging**
