### PR TITLE
mesa 24.0.0

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is just an RC1, release dance started. So I decided to create this PR in front, in order to run CI against this new major release and catch any regressios.

### CODE REVIEW

**Comment by p-linnane** [comment]
Your base branch is outdated. Can you rebase please?

**Comment by yurikoles** [comment]
```
mesa
  * Stable version URLs should not contain rc1
```

**Comment by yurikoles** [comment]
Didn't know about `audit_exceptions/unstable_allowlist.json`, this is my first pre-release PR.😅

**Comment by chenrui333** [comment]
Since this is pre-release testing, maybe we can close this for now?

**Comment by yurikoles** [comment]
> Since this is pre-release testing, maybe we can close this for now?

Yes, this is pre-release testing, but why we need to close this? What's the principal difference with any other pre-release PRs? I want to remind that `mesa` is an essential package on Linux, almost any GUI app (r)depends on it.

**Comment by cho-m** [comment]
Should also try removing workaround I added. It was fixed in 23.3.1:
https://github.com/Homebrew/homebrew-core/blob/12f0f4824bf999491fc60eefbd96c6df52f3f1ca/Formula/m/mesa.rb#L109-L111

**Comment by yurikoles** [comment]
Whoops, I'm sorry for that, let maintainers decide best option.

**Comment by yurikoles** [comment]
I used ArchLinux' [package](https://gitlab.archlinux.org/archlinux/packaging/packages/mesa/-/blob/main/PKGBUILD?ref_type=heads) as a reference and imported almost all meson options except those that require `rust`, mainly `rusticl`.

**Comment by chenrui333** [comment]
> @chenrui333 There's the `24.0.1` to pick up and use instead of `24.0.0`. (And a linked PR opened by the bot for that version).

yeah, let's do it separately, no harm of it.

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
