### PR TITLE
media-info 0.7.99

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

### CODE REVIEW

**Comment by tommyang** [comment]
Hi, I am getting the same checksum mismatch error on multiple Macs with different ISPs when trying to upgrade this formula. 
```
Error: SHA256 mismatch
Expected: 099c06531bec1ecff18b2ac8626cdd2b64c4652b9aba5d0c869abafdd69e44d5
Actual: a365ea634b0188566eec25553a50483283a3a600cf69cd6d707e714ee329cb90
```
Not wanting to just open a pull request and update the checksum as I am not sure what happened. Somehow upstream changed the tarball without bumping the version?

**Comment by ilovezfs** [comment]
>Somehow upstream changed the tarball without bumping the version?

Yep. Someone will need to file an issue with upstream and find what happened exactly and why.

**Comment by tommyang** [comment]
Thanks for the pointers. I [posted](https://sourceforge.net/p/mediainfo/discussion/297610/thread/e547907b/) this question to their discussion forum, which seems to be monitored by project members.

**Comment by tommyang** [comment]
Resolved by #18080.

**Pull request closed without merging**
