### PR TITLE
aws-sdk-cpp 1.9.130

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by kou** [comment]
Can we enable Linux bottle of this?
#88797 wants it.

Do you know what is the problem for Linux bottle?

**Comment by chenrui333** [comment]
looks like OOM failure on linux build
```
{standard input}: Assembler messages:
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++-5: internal compiler error: Killed (program cc1plus)
```

**Comment by chenrui333** [comment]
Also there is some build issue with GCC 11.2.0, https://github.com/aws/aws-sdk-cpp/issues/1795

**Comment by kou** [comment]
Thanks.
Can we try the following once we fix aws/aws-sdk-cpp#1795 ?

```diff
diff --git a/Formula/aws-sdk-cpp.rb b/Formula/aws-sdk-cpp.rb
index e924449db8a..de8d5fa00a6 100644
--- a/Formula/aws-sdk-cpp.rb
+++ b/Formula/aws-sdk-cpp.rb
@@ -21,6 +21,12 @@ class AwsSdkCpp < Formula
 
   uses_from_macos "curl"
 
+  on_linux do
+    depends_on "gcc"
+  end
+
+  fails_with gcc: "5"
+
   def install
     ENV.append "LDFLAGS", "-Wl,-rpath,#{rpath}"
     mkdir "build" do
```

**Comment by kou** [comment]
I tried GCC 11.2 with aws-sdk-cpp 1.9.139 on Debian GNU/Linux sid and didn't get build error. (The reporter uses RHEL 7.)
We may be able to use GCC 11.2 because we use Ubuntu 16.04 not RHEL 7 to build Linux bottle.

Note that we can't use GCC 11.2 with aws-sdk-cpp 1.9.130. Because it doesn't include  https://github.com/aws/aws-sdk-cpp/commit/b6f0e3036b7f5142d77c2c4c50d4f1d5e38d64bd .

**Review by carlocab — APPROVED** [review]
This has no Linux bottle, so the Linux failure is non-blocking.

**Comment by carlocab** [comment]
We can fix the Linux build in a separate PR.

**Pull request closed without merging**
