### PR TITLE
wine 2.6 (devel)

### PR DESCRIPTION
**Pull request by yurikoles**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by uyjulian** [comment]
You can keep the `dl.winehq.org` url

**Comment by yurikoles** [comment]
@uyjulian updated and rebased

**Comment by yurikoles** [comment]
@ilovezfs why had you aborted the build?

**Comment by ilovezfs** [comment]
Because there were three instances of the wine build going on at once.

**Comment by yurikoles** [comment]
@ilovezfs oh sorry, I'm sometimes too fast on commits

**Comment by ilovezfs** [comment]
It's no problem

**Comment by ilovezfs** [comment]
Thanks for the update @yurikoles

**Pull request merged**
