### PR TITLE
maven@3.6 3.6.3 (new formula)

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/73645

**Comment by carlocab** [comment]
Is the 3.6.x branch of maven still maintained? i.e. Is there a 3.6.4 release planned?

**Comment by moonfruit** [comment]
I don't know whether there will be a 3.6.4. But according to [`maven`'s release history](https://maven.apache.org/docs/history.html), I think there will not be a 3.6.4.

But since `maven` 3.8 introduce some [incompatible features](https://maven.apache.org/docs/3.8.0/release-notes.html#why-does-this-version-have-the-value-3-8-0), I think someone will need `maven` 3.6. And now homebrew already has `maven@3.5`, `maven@3.3`, and  `maven@3.2`.

**Comment by carlocab** [comment]
It doesn't sound like `maven@3.6` doesn't meet the [requirements](https://docs.brew.sh/Versions#acceptable-versioned-formulae) for acceptable versioned formulae, then.

Of course, I'm aware that the other versions of Maven that we have probably don't meet them either, but it's possible they were added at a time when the requirements for versioned formulae were less demanding. At a minimum, we should probably deprecate/disable some of the older maven formulae before adding another versioned one.

**Comment by Bo98** [comment]
I'm very cautious about doing this. Maven 3.8.0 is a security release that would have been 3.6.4 if the changes weren't incompatible. 3.6.3 will contain known security vulnerabilities that will only be fixed by updating to 3.8.0.

The incompatible changes in 3.8.0 can also be disabled in your local settings should it be that disruptive.

**Comment by moonfruit** [comment]
Yes, you are right, @carlocab @Bo98.

For my own project, I already disable the incompatible features. so I'm OK for homebrew not having `maven@3.6'. Just because of `maven@3.5`, `maven@3.3.` and `maven@3.2`, I think there should be a `maven@3.6` in homebrew for someone. After all, someone needs a little extra tweak to use `maven` 3.8.

**Comment by Rylan12** [comment]
> I think there should be a `maven@3.6` in homebrew for someone.

Given the above points, until someone asks for it (and explains how it meets the requirements) let's not add it. I think it makes more sense for a discussion to occur then if that happens rather than speculating.

Even then, it may be better for someone to create a `maven` custom tap where they can include more versions than Homebrew does.

**Comment by moonfruit** [comment]
OK, I will close this.

**Comment by carlocab** [comment]
Thanks for the PR anyway, @moonfruit.

**Pull request closed without merging**
