### PR TITLE
sqlite 3.32.2

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
```
Error: 5 failed steps!
brew test --verbose agda
brew test --verbose alure
brew test --verbose bnfc
brew test --verbose bowtie2
brew test --verbose graphite2
```

**Comment by samford** [comment]
The `agda` and `bnfc` failures are due to `cabal_sandbox` being deprecated and will be handled as part of #55253 (there's already #55854 for `bnfc`). `alure` is simply one of the sound-related formulae with a test that regularly fails on CI (as in #55191). Failures for `bowtie2` and `graphite2` are as follows:

```
==> brew test --verbose bowtie2
==> FAILED
Testing bowtie2
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200605-30702-1dsyxk1.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bowtie2.rb --verbose
==> /usr/local/Cellar/bowtie2/2.4.1/bin/bowtie2-build /usr/local/Cellar/bowtie2/2.4.1/share/bowtie2/example/reference/lambda_virus.fa lambda_virus
env: python3: No such file or directory
Error: bowtie2: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/bowtie2/2.4.1/bin/bowtie2-build /usr/local/Cellar/bowtie2/2.4.1/share/bowtie2/example/reference/lambda_virus.fa lambda_virus
```

I'm not sure why the file didn't seem to be present on CI, as it worked fine for me locally.

```
==> brew test --verbose graphite2
==> FAILED
Testing graphite2
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200605-3286-5gciq0.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/graphite2.rb --verbose
==> Downloading https://scripts.sil.org/pub/woff/fonts/Simple-Graphite-Font.ttf
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.3.0-37-g49324ad\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --silent --retry 3 --location --remote-time --continue-at 0 --output /Users/brew/Library/Caches/Homebrew/downloads/f3defb70b069df7b82cf2d5e02caf9bf171a4c8d92a077d38ac3a16637c09ff0--Simple-Graphite-Font.ttf.incomplete https://scripts.sil.org/pub/woff/fonts/Simple-Graphite-Font.ttf
curl: (7) Failed to connect to scripts.sil.org port 443: Connection refused
Error: graphite2: failed
An exception occurred within a child process:
  DownloadError: Failed to download resource "graphite2--testfont"
Download failed: https://scripts.sil.org/pub/woff/fonts/Simple-Graphite-Font.ttf
```

The test file for `graphite2` wasn't accessible around the time of the test but it's back now.

---

Unless there's something actionable about the `bowtie2` failure (e.g., if someone has seen this failure before and/or it happens regularly on CI), I think we're fine merging this.

If you could also create a PR to bump `dbhash`, that would be helpful. We usually do `sqlite`, `dbhash`, `sqldiff`, and `sqlite-analyzer` all in one PR (like #55191) but you've already done the others separately.

**Comment by miccal** [comment]
@samford `dbhash` is [here](https://github.com/Homebrew/homebrew-core/pull/55801).

**Comment by samford** [comment]
> `dbhash` is [here](https://github.com/Homebrew/homebrew-core/pull/55801).

Ha, I searched for `dbhash` PRs but somehow overlooked it. Tired brain 😪

> bottle publish [failure](https://github.com/Homebrew/homebrew-core/actions/runs/126465341).

This again. I'll have to bother another maintainer to merge this, since the last `sqlite` PR ran into a bottle publish issue as well and it's a bit tricky to deal with.

Anyway, thanks @miccal!

**Comment by SMillerDev** [comment]
The bottles seem to be broken so I'm running this again.

**Comment by samford** [comment]
> The bottles seem to be broken so I'm running this again.

This is the same bottle issue that we encountered in #55191 and @Bo98 had to work some magic and manually merge that PR. Unless something has changed in the interim time, we won't be able to merge this after another run as well and it may be best to wait until Bo has time to take care of this. It requires some manual labor to merge `sqlite` at the moment and I don't know what Bo's process is (to be able to replicate it).

**Comment by miccal** [comment]
Closing as `3.32.3` is now available.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-core/pull/56512

**Pull request closed without merging**
