### PR TITLE
fzf 0.35.0

### PR DESCRIPTION
**Pull request by Moulick**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by Moulick** [comment]
what's wrong with navi?

**Comment by junegunn** [comment]
@chenrui333 

The error from navi is unrelated.

>   ==> Pouring navi--2.20.1.x86_64_linux.bottle.tar.gz
>  Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections

**Comment by SMillerDev** [comment]
Can you rebase the branch? We can't merge this with merge commits

**Comment by carlocab** [comment]
Closing in favour of #115693, which is closer to merging.

**Pull request closed without merging**
