### PR TITLE
riemann 0.2.11

### PR DESCRIPTION
**Pull request by apjanke**
Subsumes #1246 (preserving author credit) and adds a mirror per https://github.com/riemann/riemann/issues/716#issuecomment-241855800.

Closes #1246.

### CODE REVIEW

**Comment by DomT4** [comment]
👍. I presume you're aware your commits aren't aligning with your GitHub username?

**Comment by apjanke** [comment]
Uh oh. Thanks for the heads-up.

**Comment by apjanke** [comment]
Author fixed(ish), and I updated my local git config so it won't happen again. Thanks!

**Comment by DomT4** [comment]
No worries, just wanted to check you were aware of it. Can be easy to miss. LGTM on the PR here 👍.

**Pull request closed without merging**
