### PR TITLE
ford 6.1.6

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cclauss** [comment]
> depends_on "python@3.9"

python@3.10

**Comment by Porkepix** [comment]
@cclauss Doesn't seems to agree due to other dependencies. Some pretty used one among them.

**Comment by chenrui333** [comment]
yeah, the glib dependency is an issue for migrating to use python@3.10 #87277

**Comment by chenrui333** [comment]
#92937

**Pull request closed without merging**
