### PR TITLE
mandown 1.0.4

### LINKED ISSUE #35: mandown 1.0.3 failed to build on OSX
both 1.0.2 and 1.0.3 releases failed to build on OSX, error log is below:

```
formula   mdn
ld: can't map file, errno=22 file 'build/blender/blender.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mdn] Error 1
```

relates to 

- Homebrew/homebrew-core#70530
- Homebrew/homebrew-core#70650

cc @Titor8115

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

continuing #92452
fixes https://github.com/Titor8115/mandown/issues/35

### CODE REVIEW

**Comment by carlocab** [comment]
Build succeeds on Linux now, but the new test is failing.

**Comment by carlocab** [comment]
Tested in a Docker container; can't repro the failure. Not sure what's happening? CC @Homebrew/linux

**Comment by chenrui333** [comment]
maybe ignore linux test and move on?

**Comment by carlocab** [comment]
Fine with me.

**Review by carlocab — APPROVED** [review]

**Comment by p-linnane** [comment]
Are we merging this?

**Comment by carlocab** [comment]
We should.

**Comment by p-linnane** [comment]
Should we rebase first? I'm terrified of what's gonna happen if we add the autosquash label to this 😅

**Comment by carlocab** [comment]
Yea, probably. Though if you're already rebasing, may as well squash while you're at it.

**Pull request merged**
