### PR TITLE
nvc 1.5.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
Can the test resource be renamed to avoid the `resource blocks may require updates.` message?

**Comment by carlocab** [comment]
If you call the resource `homebrew-foo` then `bump-formula-pr` won't produce a message about the resource possibly requiring an update.

**Comment by chenrui333** [comment]
The linux build failure should be irrelevant to my change?

```
configure: error: GNU Flex not found
```

**Comment by chenrui333** [comment]
Since no linux bottle, we can ignore the linux build failure.

**Comment by carlocab** [comment]
You can also try adding `uses_from_macos "flex" => :build` since that's what the error is about:
```
configure: error: GNU Flex not found
```

**Comment by iMichka** [comment]
> configure: error: We could not detect the llvm libraries make sure that llvm-config is on your path or specified by --with-llvm.

Weird. Might need to pass the explicit path to llvm-config.

**Comment by carlocab** [comment]
You mean like this?

https://github.com/Homebrew/homebrew-core/blob/339a46a641b4ca8b1180cf5ff43b03f038006f87/Formula/nvc.rb#L41

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
