### PR TITLE
capnp: vendor gtest

### LINKED ISSUE #5435: capnp fails to build (downloading gtest fails)
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [X ] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

capnp fails to build (downloading gtest fails)

https://gist.github.com/66fb76aa836e1b14e04d30b3d2b2c7ea

### PR DESCRIPTION
**Pull request by dunn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Fixes #5435.

### CODE REVIEW

**Comment by zmwangx** [comment]
CI is seeing the same test failure as I did:

```
The following tests FAILED:
	  2 - kj-heavy-tests-run (Failed)
```

Only on Sierra.

**Comment by dunn** [comment]
Ohhh; I was testing on El Cap.  Dang.

**Comment by dunn** [comment]
The release we're trying to build is so old that I don't think that test even exists in the current `master`: https://github.com/sandstorm-io/capnproto/tree/master/c%2B%2B/src/kj

**Comment by zmwangx** [comment]
Yeah as I said in the other thread, gtest was yanked out completely.

**Comment by zmwangx** [comment]
Unfortunately the master branch seems to also fail the same test: https://github.com/sandstorm-io/capnproto/issues/375. (I didn't test it locally because the formula might need substantial modifications to work with master — at least merely running `./release.sh` doesn't work.)

**Comment by zmwangx** [comment]
@paulproteus, member of sandstorm-io (parent org of capnp), [claims](https://github.com/Homebrew/homebrew-core/issues/5435#issuecomment-264576618) that it's not essential to pass all tests (if I understood him correctly). Guess we can yank out `make check`.

**Comment by dunn** [comment]
¯\\\_(ツ)\_\/¯  ok

**Comment by MikeMcQuaid** [comment]
Thanks @dunn!

**Comment by kentonv** [comment]
FWIW the test failures here appear to be because Apple shipped a broken kernel. The test failures are very real, but it's the OS that's broken. What does one do in such a case? :/

**Comment by zmwangx** [comment]
File a radar.

**Pull request closed without merging**
