### PR TITLE
global: really use Python 3 for build

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by mitchblank** [comment]
The build failure issues are known from previous attempts to upgrade this formula to 6.6.5 (#61097 #64909) ..

The `realpath` issue may be fixed upstream ( http://cvs.savannah.gnu.org/viewvc/global/global/configure.ac?r1=1.204&r2=1.205&view=patch ) but I don't think anybody has tried to patch it in HB yet.   So either we're waiting for someone to deal with that or for `global` to do another upstream release with the fix.

**Comment by iMichka** [comment]
The actual configure error is:
```
configure:14276: checking whether POSIX.1-2008 realpath is equipped
configure:14293: clang -o conftest -g -O2   conftest.c  >&5
conftest.c:59:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
main(){ (void)realpath("/./tmp", (void *)0); return 0; }
^
conftest.c:59:15: error: implicit declaration of function 'realpath' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
main(){ (void)realpath("/./tmp", (void *)0); return 0; }
              ^
1 warning and 1 error generated.
configure:14293: $? = 1
```

**Comment by mitchblank** [comment]
Are you sure?  The match is to `configure.ac`, so you need to regenerate `configure` if you want the patch to take effect (or just make the equivalent patch to `configure` itself, of course)

**Comment by iMichka** [comment]
Got it, forgot to reconfigure. I always forget to do that ... I got it to build locally, let's see what happens on CI

**Pull request closed without merging**
