### PR TITLE
influxdb@1 1.9.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
This is going to need `rust`. Though, the `flux` version looks like one without Rust 1.54 fix (https://github.com/influxdata/flux/commit/c29d2c02ab42d591bb91e5d6321dacba3609e928)
```
Executing cargo build	{"dir": "/Users/brew/Library/Caches/Homebrew/go_cache/pkgconfig/github.com/influxdata/flux@v0.120.1/libflux", "target": ""}
Error installing library	{"name": "flux", "error": "exec: \"cargo\": executable file not found in $PATH"}
pkg-config: exit status 1
```

**Comment by chenrui333** [comment]
```
error: field is never read: `message`
  --> flux-core/src/parser/mod.rs:24:5
   |
24 |     pub message: String,
   |     ^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> flux-core/src/lib.rs:1:38
   |
1  | #![cfg_attr(feature = "strict", deny(warnings, missing_docs))]
   |                                      ^^^^^^^^
   = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`

error: aborting due to previous error

error: could not compile `flux-core`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: field is never read: `message`
  --> flux-core/src/parser/mod.rs:24:5
   |
24 |     pub message: String,
   |     ^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> flux-core/src/lib.rs:1:38
   |
1  | #![cfg_attr(feature = "strict", deny(warnings, missing_docs))]
   |                                      ^^^^^^^^
   = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`

error: aborting due to previous error

error: build failed
Error installing library	{"name": "flux", "error": "exit status 101"}

```

**Comment by cho-m** [comment]
Error is due to Rust 1.54 - https://github.com/influxdata/flux/commit/c29d2c02ab42d591bb91e5d6321dacba3609e928

Backporting and applying the fix is a bit tedious, which is what I tried in https://github.com/Homebrew/homebrew-core/pull/83691/files

The `libflux/go/libflux/buildinfo.gen.go` has a high chance of causing upstream commit to fail as it contains SHA checksums of various files. Whenever a file is modified, the file is updated, which makes it difficult to cleanly apply patches.

**Comment by SMillerDev** [comment]
We have a flux formula, isn't it possible to reference that?

**Comment by cho-m** [comment]
> We have a flux formula, isn't it possible to reference that?

Not sure if Go build can allow that. There is also the question if v0.120.1 and v0.127.3 have compatible APIs.

**Comment by chenrui333** [comment]
> > We have a flux formula, isn't it possible to reference that?
> 
> Not sure if Go build can allow that. There is also the question if v0.120.1 and v0.127.3 have compatible APIs.

go build wont allow the local file linkage.

**Comment by SMillerDev** [comment]
I thought that was the whole reason they wrote a pkg-config wrapper?

**Pull request closed without merging**
