### PR TITLE
d*: Fix `Homebrew/NoFileutilsRmrf` RuboCop offenses

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- Part of https://github.com/Homebrew/brew/pull/17705.
- Different approach from the previous massive PR - I'm splitting them up per-alphabet letter (ish) and letting CI do the full "no bottles" build. This is `d*`.

### CODE REVIEW

**Comment by issyl0** [comment]
I'll have to move `ddclient` to its own PR as it's not building for seemingly unrelated reasons.

**Comment by issyl0** [comment]
🤔 `dicebear` failed with:

```
Full audit --formula dicebear --git --skip-style output
  dicebear
    * stable version should not decrease (from 9.2.1 to 9.2.0)
  Error: 1 problem in 1 formula detected.
```

**Comment by bevanjkay** [comment]
https://github.com/Homebrew/homebrew-core/pull/178503 Was merged after this PR was opened.

**Comment by issyl0** [comment]
Oh, thanks, I'll rebase!

**Review by bevanjkay — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
