### PR TITLE
skopeo: build manpages.

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The `--help` text refers to manpages, but there are none that ship with
the formula. This is pretty confusing, so let's just ship the manpages.

### CODE REVIEW

**Comment by carlocab** [comment]
```
  make: command: Command not found
  sed -e 's/\((skopeo.*\.md)\)//' -e 's/\[\(skopeo.*\)\]/\1/' docs/skopeo.1.md  | /github/home/.cache/Homebrew/go_mod_cache/bin/go-md2man -in /dev/stdin -out docs/skopeo.1
  make: command: Command not found
  /bin/sh: 1: /github/home/.cache/Homebrew/go_mod_cache/bin/go-md2man: not found
  make: command: Command not found
  sed -e 's/\((skopeo.*\.md)\)//' -e 's/\[\(skopeo.*\)\]/\1/' docs/skopeo-list-tags.1.md  | /github/home/.cache/Homebrew/go_mod_cache/bin/go-md2man -in /dev/stdin -out docs/skopeo-list-tags.1
  make: command: Command not found
  /bin/sh: 1: /github/home/.cache/Homebrew/go_mod_cache/bin/go-md2man: not found
  make: command: Command not found
  Makefile:146: recipe for target 'docs/skopeo.1' failed
  make: *** [docs/skopeo.1] Error 127
```

**Comment by carlocab** [comment]
The `Makefile` checks `PATH` for `go-md2man` first, and then falls back to `GOBIN`:
```
GOMD2MAN ?= $(if $(shell command -v go-md2man),go-md2man,$(GOBIN)/go-md2man)
```
https://github.com/containers/skopeo/blob/ca1b0f34d1d2c3e2074c9c231249f1a0e4d3ceb7/Makefile#L34

No idea why `go-md2man` is not being found in `PATH` on Linux.

**Comment by carlocab** [comment]
Oh, I see:
```
make: command: Command not found
```
This is `make` complaining that it doesn't know what `command` is. Huh; I always thought that was portable.

**Comment by carlocab** [comment]
Ah, so `command` is portable -- it's just a peculiarity of (apparently newer versions of) `make` where it tries to avoid spawning a new shell:

https://stackoverflow.com/questions/12989869/calling-command-v-find-from-gnu-makefile
https://askubuntu.com/questions/1351696/gnu-make-executes-weird-shell

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
