### PR TITLE
chapel 2.3

### PR DESCRIPTION
**Pull request by arezaii**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Release for Chapel 2.3

* patch was removed because it was implemented in the source
* SHA and URL updates
* 2.3 supports up to llvm@19 - removed pinning to 18

### CODE REVIEW

**Comment by chenrui333** [comment]
move the pr to draft mode

**Comment by arezaii** [comment]
Chapel 2.3 was released today so this PR can be made ready and merged at your convenience. Thank you!

**Comment by arezaii** [comment]
@SMillerDev, @iMichka 
Checking back to see if we can remove the `prerelease-testing`/`pre-release` labels and merge.

**Review by branchv — APPROVED** [review]
LGTM thanks!

**Pull request merged**
