### PR TITLE
ocicl 2.3.7 - fix image restore

### PR DESCRIPTION
**Pull request by atgreen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is this an upstream bug? Or is the Homebrew wrapper just too fragile?

**Comment by atgreen** [comment]
It's a bug related to the way I build ocicl in homebrew.  The way I build
it in homebrew is unique, so it's OK to put the fix here as well.

**Comment by SMillerDev** [comment]
> It's a bug related to the way I build ocicl in homebrew.  The way I build
> it in homebrew is unique, so it's OK to put the fix here as well.

That seems like it would introduce bugs that only exist in Homebrew more often. Is there no way to use the normal upstream build system?

**Comment by dieggsy** [comment]
This was marked as stale, but I've been watching this PR as this is a needed fix for ocicl

**Comment by chenrui333** [comment]
should be `rebase` rather than `merge` to refresh the pr branch

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request merged**
