### PR TITLE
git-annex: remove foundation < 0.0.10 constraint

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

since the El Capitan build failure is fixed as of 0.0.11.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @joeyh The build failed here for a reason unrelated to the PR. I've just reported the issue here: https://git-annex.branchable.com/bugs/Build_failure__58___Utility__47__QuickCheck.hs__58__38__58__10__58___error__58___Duplicate_instance_declarations/

(I know it's unrelated because the build also failed in the same for the formula unmodified https://jenkins.brew.sh/job/Homebrew%20Testing/76/version=yosemite/consoleText)

**Comment by joeyh** [comment]
I've committed 75cecbbe3fdafdb6652e95ac17cd755c28e67f20 to git-annex to
fix this problem.

-- 
see shy jo

**Comment by ilovezfs** [comment]
Thanks for the super quick work @joeyh! I will apply the fix as a patch here.

**Comment by ilovezfs** [comment]
@joeyh looks like there are a couple of test failures with the new QuickCheck:
```
iMac-TMP:homebrew-core joe$ git annex test
Tests
  QuickCheck
    prop_isomorphic_deencode_git:                         FAIL
      *** Failed! Falsifiable (after 2 tests): 
      "\929184"
      Use --quickcheck-replay=873827 to reproduce.
    prop_isomorphic_deencode:                             FAIL
      *** Failed! Falsifiable (after 2 tests): 
      "\560422"
      Use --quickcheck-replay=169203 to reproduce.

...

2 out of 293 tests failed (164.60s)
  (This could be due to a bug in git-annex, or an incompatibility
   with utilities, such as git, installed on this system.)
```

**Comment by joeyh** [comment]
ilovezfs wrote:
> @joeyh looks like there are a couple of test failures with the new QuickCheck:

I've fixed those with commit da8e84efe997fcbfcf489bc4fa9cc835ed131d3a

-- 
see shy jo

**Comment by ilovezfs** [comment]
@joeyh thanks again! Shipped with 75cecbbe3fdafdb6652e95ac17cd755c28e67f20 and  da8e84efe997fcbfcf489bc4fa9cc835ed131d3a applied as patches.

**Pull request closed without merging**
