### PR TITLE
tailwindcss 3.3.3 (new formula)

### PR DESCRIPTION
**Pull request by ccostello97**
Creates formula for TailwindCSS standalone CLI tool

I first attempted adding this to Homebrew Cask but @bevanjkay helpfully pointed out this belongs in Core.

- [ x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
That's not actually a formula, it's a cask and it should actually build from source here

**Comment by ccostello97** [comment]
Hi @SMillerDev, this is my first contribution to Homebrew, not sure I follow. Where should I put this, and how would I go about building from source? Did you mean to link me to a piece of documentation I might have missed?

I did try to submit this to Homebrew-Cask first and was told it belongs in Core, https://github.com/Homebrew/homebrew-cask/pull/154332#event-10269592407.

**Comment by bevanjkay** [comment]
@ccostello97 To build from source you will need to create a `formula` not a `cask` - here are the docs - https://docs.brew.sh/Formula-Cookbook#page

**Comment by chenrui333** [comment]
#144327

**Pull request closed without merging**
