### PR TITLE
kontena 1.4.3

### PR DESCRIPTION
**Pull request by kke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Rubocop config seems out of sync?
```
Error: Error running `rubocop --format json --force-exclusion --parallel --except NewFormulaAudit --config /usr/local/Homebrew/Library/.rubocop_audit.yml /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kontena.rb`
```

### CODE REVIEW

**Comment by kke** [comment]
Jenkins says:

```
Error: 1 problem in 1 formula
kontena:
  * 'revision 1' should be removed
```

It was added by @lembacon in : 

https://github.com/Homebrew/homebrew-core/blame/a7455fc8537577913c59e8fa1b6535f448aa08df/Formula/kontena.rb#L5

**Comment by ilovezfs** [comment]
Revision counting starts from 0, is reset each version, and is unneeded when the revision is 0.

**Comment by kke** [comment]
I guess there was some reason it was added there? Should I remove or bump it?

**Comment by ilovezfs** [comment]
It should be removed since this is a new version. For a new version revision is reset to 0. So the revision should be 0. But a `revision 0` is never explicitly supposed to be in the formula.

It was added because this was linked to libruby.2.4.2.dylib and needed to be rebuilt so it would be linked to libruby.2.4.3.dylib.

**Comment by ilovezfs** [comment]
Also, are `kontena-plugin-cloud`, `rake`, and `websocket-extensions` still needed?

**Comment by kke** [comment]
`websocket-extensions` is a dependency of a dependency and has to be present. `rake` is probably there accidentally. The plugin is optional anyway and can be dropped.

Rebased + forcepushed.

**Comment by ilovezfs** [comment]
And what was the deal with kontena-plugin-cloud?

**Comment by ilovezfs** [comment]
>The plugin is optional anyway and can be dropped.

Does that mean it will be usable if we leave it in?

**Comment by ilovezfs** [comment]
Thanks again @kke!

**Comment by kke** [comment]
> Does that mean it will be usable if we leave it in?

Mostly convenience, it can be installed by `kontena plugin install cloud`.

**Pull request closed without merging**
