### PR TITLE
zsh-vi-mode: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by nandahkrishna**
See #75943.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by nandahkrishna** [comment]
```
6bd41a235238ffa0aa1016fa1f47626dac42be943209ceafecc6bdc146c29dde  zsh-vi-mode--0.8.2.arm64_big_sur.bottle.tar.gz
6bd41a235238ffa0aa1016fa1f47626dac42be943209ceafecc6bdc146c29dde  zsh-vi-mode--0.8.2.big_sur.bottle.tar.gz
6bd41a235238ffa0aa1016fa1f47626dac42be943209ceafecc6bdc146c29dde  zsh-vi-mode--0.8.2.catalina.bottle.tar.gz
e71dd512522b81a93fb0e8dfc34c7e4898d542b0582c113e140da2b57ee7f7ff  zsh-vi-mode--0.8.2.mojave.bottle.tar.gz
```

**Comment by MikeMcQuaid** [comment]
@nandahkrishna Interesting, perhaps we need to sort the input files somehow? @Bo98 any ideas?

**Comment by Bo98** [comment]
Wow, that's an interesting one. I think it might actually be sorted by `inode` number.

I'm not entirely sure if there's a fix for that beyond iterating the directory ourselves. Honestly, some more manual handling like that is beginning to look like the best solution. I'll play around with it a bit.

**Comment by Bo98** [comment]
gnu-tar does have `--sort=name`. `bsdtar` does not.

**Comment by MikeMcQuaid** [comment]
> gnu-tar does have `--sort=name`.

Would be interested if this alone is enough to fix this.

**Comment by nandahkrishna** [comment]
```
4ef061c362f1a957cb1ffb3bbf50763e34d1751ce9e46dca30bfeabc6e3f21ce  zsh-vi-mode--0.8.2.arm64_big_sur.bottle.tar.gz
4ef061c362f1a957cb1ffb3bbf50763e34d1751ce9e46dca30bfeabc6e3f21ce  zsh-vi-mode--0.8.2.big_sur.bottle.tar.gz
4ef061c362f1a957cb1ffb3bbf50763e34d1751ce9e46dca30bfeabc6e3f21ce  zsh-vi-mode--0.8.2.catalina.bottle.tar.gz
4ef061c362f1a957cb1ffb3bbf50763e34d1751ce9e46dca30bfeabc6e3f21ce  zsh-vi-mode--0.8.2.mojave.bottle.tar.gz
```
✅

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
