### PR TITLE
workflows: add `no Linux bottle` labeling

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

One problem: PRs modifying macOS-only formulae will also be labeled

### CODE REVIEW

**Comment by cho-m** [comment]
Does this end up labeling `all` bottles too?

**Comment by dawidd6** [comment]
Ye, it will label formulae with :all bottles too. I think we need to tweak our labeling Action to accept an Array of strings for `missing_content` key (might be a good idea to modify other keys too).

**Comment by dawidd6** [comment]
Action tweaked. Should be fine now.

**Comment by cho-m** [comment]
I tried it on #84190, but it didn't get labeled. Triage looks like it is using recents changes

[`Download action repository 'Homebrew/actions@master' (SHA:31951fc0704828df0d58848625d659ce92d181cf)`](https://github.com/Homebrew/homebrew-core/runs/3453794789?check_suite_focus=true#step:1:29)
[`          "label": "no Linux bottle",`](https://github.com/Homebrew/homebrew-core/runs/3453794789?check_suite_focus=true#step:3:26)

**Comment by cho-m** [comment]
@dawidd6 maybe the action should use `for ( ... of ... )` loop rather than `for ( ... in ...)` loop?

**Comment by dawidd6** [comment]
Geee. I specially read about the difference of those keywords and still used the wrong one...

https://github.com/Homebrew/actions/commit/1d5eb22309b91995537ecdea9287ac148b604a87

**Comment by cho-m** [comment]
Thanks for fix. At least one confirmation #84191 of correct label.

**Comment by cho-m** [comment]
New labeling issue for new formula in #84201. No idea what is best way to deal with this.

ARM avoids this by checking for Intel Big Sur bottle, which can only occur on existing formulae.

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-core/commit/f87b69819ec96bc1557c3bf856356f24e91a4d8d

**Pull request merged**
