### PR TITLE
pachi 12.70

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  josekifix.sgf
  josekifix/sgfdump: SGF perl module is missing, try:
  	$ cpan 
  	cpan[1]> install Games::SGF::Go 
```

**Comment by p-linnane** [comment]
Upstream has retagged the release fixing this issue.

**Comment by chenrui333** [comment]
Per upstream comment, I think we can also refine the formula a bit cc @lemonsqueeze

**Comment by chenrui333** [comment]
#123060

**Pull request closed without merging**
