### PR TITLE
erlang 24.1.

### PR DESCRIPTION
**Pull request by alaadahmed**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by alaadahmed** [comment]
what just happened? Why tests were cancelled? Due to long time they took?

**Comment by SMillerDev** [comment]
Yes, long builds are limited by default. If you can reopen the PR we can remove the restrictions and rerun the build.

**Comment by alaadahmed** [comment]
Sorry it seems I missed up something
```
Error: You need to bump this formula manually since the new URL
and old URL are both:
  https://github.com/erlang/otp/releases/download/OTP-24.1/otp_src_24.1.tar.gz
```

**Comment by alaadahmed** [comment]
unfortunately I deleted the PR

**Comment by alaadahmed** [comment]
OK I made a new one https://github.com/Homebrew/homebrew-core/pull/85721

**Pull request closed without merging**
