### PR TITLE
ipython: add ipykernel and man1 page

### PR DESCRIPTION
**Pull request by cglong**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
IPyKernel is a wrapper around `ipython` that allows [Jupyter](http://jupyter.org/) to talk to it; I'm working on a `jupyter` formula now 😄  IPyKernel needs to be located in the same virtualenv for this communication to work.

As this is the second item in [IPython's list of features](http://ipython.org/), it seems to make sense as part of the default formula.

### CODE REVIEW

**Comment by cglong** [comment]
Please see #14916 for the main discussion.

**Comment by ilovezfs** [comment]
not stale.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks again @cglong! :eye: :snake:

**Pull request closed without merging**
