### PR TITLE
python@*: setuptools 40.8.0, pip 19.0.2, wheel 0.33.0

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lembacon** [comment]
```
17:44:12 ==> brew audit python --online
17:45:11 ==> FAILED
17:45:11 Error: 1 problem in 1 formula detected
17:45:11 python:
17:45:11   * 'revision 1' should be removed
```

It shouldn't.

**Comment by lembacon** [comment]
Merging.

**Comment by lembacon** [comment]
For some reasons, the CI failed to recognize and thus increase the `rebuild` for `python`.

```
Error: python-3.7.2_1.mojave.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles/python/view#files
```

This build should yield `python-3.7.2_1.mojave.bottle.2.tar.gz` given that the `rebuild` is already `1`.

`python@2` is fine.

**Comment by lembacon** [comment]
@MikeMcQuaid Would you mind to take a look at this? Thanks!

**Comment by MikeMcQuaid** [comment]
@lembacon You can either ignore the audit in this case or add a `revision` if desired.

**Comment by lembacon** [comment]
🍏

**Pull request closed without merging**
