### PR TITLE
diff-so-fancy 1.0.0

### PR DESCRIPTION
**Pull request by stevemao**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

BTW diff-so-fancy shouldn't need node as a dependency. CC @paulirish @scottchiefbaker

-----

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
Is this a bug specifically for doing a brew release?

**Comment by stevemao** [comment]
@scottchiefbaker No it was a mistake to put nodejs as a dependency... We publish diff-so-fancy to npm and it's just for convenience. diff-so-fancy works well without nodejs.

**Comment by scottchiefbaker** [comment]
Oh I see what you're trying to do now... I have zero access to brew, so I can't test any of that. Is someone else able to do that?

**Comment by rakkesh** [comment]
@stevemao if the objective is to remove `node` as a `build` dependency for `diff-so-fancy`, we need a `Makefile` to install the scripts.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @stevemao. Shipped!

**Pull request closed without merging**
