### PR TITLE
flow-cli 0.39.1

### PR DESCRIPTION
**Pull request by haroldsphinx**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by sideninja** [comment]
@SMillerDev @iMichka can we fast-track this merge as soon as the CI is done because it's addressing a quite serious issue in the production? Thank you 🙏 I appreciate your help.

**Comment by sideninja** [comment]
cc @bayandin 🙏

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> @SMillerDev @iMichka can we fast-track this merge as soon as the CI is done because it's addressing a quite serious issue in the production? Thank you 🙏 I appreciate your help.

you got it.

**Comment by sideninja** [comment]
Thank you @chenrui333 !!

**Pull request closed without merging**
