### PR TITLE
sc-im: fix segfaults when used with Lua

### PR DESCRIPTION
**Pull request by 1dancook**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is not a version bump PR. It is a formula edit to rectify some build problems and program issues for sc-im. See [sc-im repo issue #629](https://github.com/andmarti1424/sc-im/issues/629) for more information.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Thanks, can we bump the `revision` to make sure this fix is shipped to users who already have this installed?

Also, please follow the commit style guide when formatting your commit messages and making further changes here. The guide is linked in the PR template. Here's a quick summary:

Please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings.

For new formulae:

> At Homebrew, we like to put the name of the formula up front like so: `foobar 7.3 (new formula)`.

For existing formulae:

> The preferred commit message format for simple version updates is `foobar 7.3` and for fixes is `foobar: fix flibble matrix.`.

Refer to the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit) for more details. Also, when making further changes to your pull request, use the following guidelines to make sure that @BrewTestBot can merge your commits:

> - One formula per commit; one commit per formula.
> - Keep merge commits out of the pull request.

**Comment by 1dancook** [comment]
Okay, I have changed revision from "3" to "4". Thank you!

**Comment by carlocab** [comment]
You missed this part:

> Also, when making further changes to your pull request, use the following guidelines to make sure that @BrewTestBot can merge your commits:
> 
> > * One formula per commit; one commit per formula.
> > * Keep merge commits out of the pull request.

Fixed that for you.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks for your first contribution to Homebrew! 🥳

**Comment by 1dancook** [comment]
Thank you @carlocab for your help! 👍😊

**Pull request closed without merging**
