### PR TITLE
img2pdf 0.4.4 (new formula)

### PR DESCRIPTION
**Pull request by ROpdebee**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Notes:
* `qpdf` is a dependency of `pikepdf`
* If this formula gets merged, `ocrmypdf` could get edited to depend on this formula instead of on the resource.
* Homepage is the official git repo, but there's a GitHub mirror too: https://github.com/josch/img2pdf

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by ROpdebee** [comment]
Side note: There are [32 other formulae](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core+%22resource+%5C%22lxml%22&type=code) that depend on the `lxml` package and thus also require the `uses_from_macos` stanzas for `libxml2` and `libxslt` (except for [8 which use a brewed `libxml2`](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core+%22resource+%5C%22lxml%5C%22%22+AND+NOT+%22uses_from_macos+%5C%22libxml2%5C%22%22&type=code) for whatever reason). Maybe it'd make sense to extract `lxml` into its own formula and depend on that instead?

**Comment by chenrui333** [comment]
yeah, that is a fair point, do you want to take the initiative on that. Thanks!

**Comment by chenrui333** [comment]
@ROpdebee, thanks for your contribution to Homebrew! :tada: 🥇

**Comment by ROpdebee** [comment]
Yeah sure, I could do that. I guess it'd be a similar process to the recent `python-cryptography` and `python-certifi` changes?

Couple of other questions before I get started on that:
1. I assume Homebrew formulae should always be preferred over resources? Because I think there might be a few formulae that use `packaging` as a resource instead of the `python-packaging` formula, so they could be changed too.
2. What is `pypi_formula_mappings.json`? I can't seem to find any documentation on it. Am I correct in assuming the brewed PyPI packages would need to be added to this, along with their resources?

**Pull request merged**
