### PR TITLE
sql-translator 1.62

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

---

osx resources are up to date

### CODE REVIEW

**Comment by chenrui333** [comment]
```
=head1 LICENSE

This library is free software and may be distributed under the same terms as
Perl 5 itself.
```

**Comment by SMillerDev** [comment]
Why did it change source?

**Comment by chenrui333** [comment]
> Why did it change source?

I can ask upstream, but from what I see, they never published the version to the registry. That is why I used the github artifact.

**Comment by chenrui333** [comment]
@SMillerDev all good now, did not find the right source earlier.

**Comment by chenrui333** [comment]
looks like my changes did not get pushed yet.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
