### PR TITLE
helmfile 0.59.0

### PR DESCRIPTION
**Pull request by Kriechi**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
tmpl/context_tmpl.go:5:2: cannot find package "github.com/Masterminds/sprig" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/Masterminds/sprig (from $GOROOT)
	/private/tmp/helmfile-20190510-89240-3w295g/helmfile-0.59.0/src/github.com/Masterminds/sprig (from $GOPATH)
state/create.go:11:2: cannot find package "github.com/imdario/mergo" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/imdario/mergo (from $GOROOT)
	/private/tmp/helmfile-20190510-89240-3w295g/helmfile-0.59.0/src/github.com/imdario/mergo (from $GOPATH)
state/state.go:26:2: cannot find package "github.com/tatsushid/go-prettytable" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/tatsushid/go-prettytable (from $GOROOT)
	/private/tmp/helmfile-20190510-89240-3w295g/helmfile-0.59.0/src/github.com/tatsushid/go-prettytable (from $GOPATH)
cmd/cmd.go:8:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/urfave/cli (from $GOROOT)
	/private/tmp/helmfile-20190510-89240-3w295g/helmfile-0.59.0/src/github.com/urfave/cli (from $GOPATH)
helmexec/exec.go:11:2: cannot find package "go.uber.org/zap" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/go.uber.org/zap (from $GOROOT)
	/private/tmp/helmfile-20190510-89240-3w295g/helmfile-0.59.0/src/go.uber.org/zap (from $GOPATH)
helmexec/exec.go:12:2: cannot find package "go.uber.org/zap/zapcore" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/go.uber.org/zap/zapcore (from $GOROOT)
	/private/tmp/helmfile-20190510-89240-3w295g/helmfile-0.59.0/src/go.uber.org/zap/zapcore (from $GOPATH)
tmpl/context_funcs.go:5:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/gopkg.in/yaml.v2 (from $GOROOT)
	/private/tmp/helmfile-20190510-89240-3w295g/helmfile-0.59.0/src/gopkg.in/yaml.v2 (from $GOPATH)
```

**Comment by Kriechi** [comment]
Mhm - do we need to depend on go modules?
I'm flying a bit in the dark here...

**Comment by Kriechi** [comment]
superseeded by #39830

**Comment by chenrui333** [comment]
@Kriechi they moved to `go modules` in 0.55, that is why we only have `0.54.2` in this formula. :)

**Comment by chenrui333** [comment]
relates to this commit, https://github.com/roboll/helmfile/commit/8f030d5eabc9b7ad7a8d16b6c384bbc8518a1e6f#diff-f949e2d81c8076ebbf8af38fcbb72c1f

**Pull request closed without merging**
