### PR TITLE
calabash 1.5.4-120

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Huh, [1.5.4-120](https://github.com/ndw/xmlcalabash1/releases/tag/1.5.4-120) was tagged *before* [1.5.4-110](https://github.com/ndw/xmlcalabash1/releases/tag/1.5.4-110).

**Comment by ZhongRuoyu** [comment]
- https://github.com/ndw/xmlcalabash1/issues/342

**Review by ZhongRuoyu — DISMISSED** [review]
According to upstream, since we are packaging [saxon](https://github.com/Homebrew/homebrew-core/blob/master/Formula/saxon.rb) 12, the `-120` releases should be the ones we ship.

**Comment by carlocab** [comment]
> CC @carlocab

This was a bright idea.

> [Here](https://github.com/Homebrew/homebrew-core/actions/runs/4721317384/jobs/8374455273#step:10:209):
> 
> ```
> ==> Uploading calabash--1.5.4-120.all.bottle.tar.gz
> Error: https://opencontainers.org/schema/image/manifest JSON schema validation failed!
> ```

No idea here. @Homebrew/brew?

**Comment by MikeMcQuaid** [comment]
@carlocab @ZhongRuoyu my guess would be https://github.com/Homebrew/brew/pull/15241 violates the defined schema so schema needs fixed (or PR reverted)?

**Comment by ZhongRuoyu** [comment]
Yes I think so. It needs to be a string. I will open a Homebrew/brew PR shortly.

**Review by carlocab — DISMISSED** [review]

**Pull request merged**
