### PR TITLE
fbthrift folly fizz wangle watchman 2022.01.31.00

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
@chenrui333 please don't remove the `CI-long-timeout` label when CI is still in progress.

**Comment by chenrui333** [comment]
Hmm, I thought the checks only happened during the `CI / setup_tests (pull_request)` phase.

**Comment by carlocab** [comment]
Yes, but `setup_tests` also checks for other long-running jobs, and it can't find them if there are long-running jobs without the label.

**Comment by chenrui333** [comment]
Noted, I have removed the ci-long-timeout label for the other one. :)

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
