### PR TITLE
ruby 2.3.2

### PR DESCRIPTION
**Pull request by frodsan**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
cc @MikeMcQuaid is this related to https://github.com/Homebrew/brew/commit/5e0b3d24e5f2a59bf715e34e8c0a62c1307d474d ?
```
        Error: 1 problem in 1 formula
ruby:
  * devel version should not decrease (from 2.4.0-preview1 to 2.4.0-beta3)
```

**Comment by MikeMcQuaid** [comment]
@dunn That output is correct as `preview1` is deemed to be "newer" than `beta3` so people won't get `brew upgraded` from the prior to the latter.

**Comment by ilovezfs** [comment]
So another retroactive need for version_scheme due to the new audit checks. Yuck.

**Comment by MikeMcQuaid** [comment]
> So another retroactive need for version_scheme due to the new audit checks. Yuck.

Another hidden, user-affecting bug found by the new audit checks. We can either ignore the bug, fix the audit checks or fix the version detection (e.g. make `preview` detected as an alpha release if it's an established convention).

**Comment by ilovezfs** [comment]
It is not user-affecting. The request to change that came from Martin literally minutes after the original push.

**Comment by MikeMcQuaid** [comment]
> It is not user-affecting. The request to change that came from Martin literally minutes after the original push.

And if you upgraded in those minutes: you'd be an affected user.

**Comment by ilovezfs** [comment]
I'll let that speak for itself.

**Comment by MikeMcQuaid** [comment]
@ilovezfs I welcome suggestions and particularly PRs on improving these audit checks. If there's better logic for us to be taking, let's do it. It's unclear to me that it's immediately obvious what they are, though.

**Comment by ilovezfs** [comment]
Reverting the false-positive-causing audit changes would be my preference. That, or running them against every existing formula, and maintaining a whitelist in perpetuity.

**Comment by MikeMcQuaid** [comment]
> Reverting the false-positive-causing audit changes would be my preference. That, or running them against every existing formula, and maintaining a whitelist in perpetuity.

The issue is that the are run against the last 10 commits which means they are catching times where we've made mistakes in the past. I'm open to suggestions to what the default behaviour instead should be as e.g. just the last 1 commit will be insufficient in a PR with more than a single commit and comparing to `origin/master` is not the right behaviour when running these locally (although maybe locally they should be a no-op).

**Comment by MikeMcQuaid** [comment]
> I'm open to suggestions to what the default behaviour instead should be as e.g. just the last 1 commit will be insufficient in a PR with more than a single commit and comparing to origin/master is not the right behaviour when running these locally (although maybe locally they should be a no-op).

I think this may be wrong, I think actually comparing just the last commit is sufficient.

**Comment by ilovezfs** [comment]
Looking forward, yes theoretically if the audit check is always done, then just comparing the last should be sufficient. It won't help anyone stranded in a prior mistake but I don't think that was the original goal of the new checks.

**Comment by ilovezfs** [comment]
Of course it assumes our version comparisons are all transitive, but we have much bigger problems if that's not the case LOL

**Comment by MikeMcQuaid** [comment]
> Looking forward, yes theoretically if the audit check is always done, then just comparing the last should be sufficient. It won't help anyone stranded in a prior mistake but I don't think that was the original goal of the new checks.

Yes. PR opened in https://github.com/Homebrew/brew/pull/1522

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
```
Error: 1 problem in 1 formula
ruby:
  * devel revision should not decrease (from 2 to 0)
```
@MikeMcQuaid I assume we're just supposed to ignore those?

**Comment by MikeMcQuaid** [comment]
@ilovezfs There was some previous code around this and it never quite made sense to me; there's no "devel revision". Yeh, just ignore it and I'll fix the audit.

**Comment by ilovezfs** [comment]
@frodsan Thanks for your contribution to Homebrew! :fireworks:

**Comment by frodsan** [comment]
Thanks! 👍

**Pull request closed without merging**
