### PR TITLE
gdrive 3.9.0 (new formula) gdrive@2 2.2.1 (new formula) 

### PR DESCRIPTION
**Pull request by indianets**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Current gdrive is obsolete, and repo is archived, author refers that as "gdrive2" in this new successor repo for which this PR is.

I have followed the naming guide https://docs.brew.sh/Formula-Cookbook#a-quick-word-on-naming and gdrive-cli should have been the original name of the current formula as well, but I am open to suggestions. gdrive-cli is how community refers to this, I considered naming it gdrive3 or a versioned gdrive@3, but they don't justify the state of this formula.

Also, the final thing is they are very different commands and have different approach, with the existing formula "gdrive" failing for most users because of Authentication issues.

PS: Closed PR #154875 due to the lack of insight initially.

### CODE REVIEW

**Comment by indianets** [comment]
What to do for this failure?

```
  gdrive
    * GitHub repo is archived
```
  
  If I do not declare the conflict to gdrive, the failure is due to conflict in gdrive-cli

```
gdrive-cli
  * Formula gdrive should also have a conflict declared with gdrive-cli
```

**Comment by chenrui333** [comment]
> What to do for this failure?
> 
> ```
>   gdrive
>     * GitHub repo is archived
> ```

this is the PR #154960

**Comment by chenrui333** [comment]
archilinux, seems directly adopt gdrive to replace gdrive2 (since it is just a rust rewrite)
nixpkg, adopts gdrive3 besides gdrive, https://github.com/NixOS/nixpkgs/commit/0ac4a39aad7419e2317e8f228f1f3c2833dca777
macport is also using gdrive3, https://ports.macports.org/port/gdrive3/details/

---

we should add gdrive3 instead of gdrive (or maybe just replace gdrive entirely, as they are the same thing)

**Comment by indianets** [comment]
> we should add gdrive3 instead of gdrive (or maybe just replace gdrive entirely, as they are the same thing)

I did have the same thought, and hence asked in discussion - https://github.com/orgs/Homebrew/discussions/4918 - I was suggested to make a new formula for new repo.

Another option could be to make a versioned formula and move the current gdrive to gdrive@2 and keep this as active and latest gdrive?

**Comment by iMichka** [comment]
Given that the package name did not change (gdrive): https://repology.org/project/gdrive/versions, that old upstream is okay that grive3 is the successor: I would recommend renaming the old one to `gdrive@2`, deprecate it right away, and update the current one to 3.9.0.

Users will be upgraded to version 3, but have a version 2 fallback.

**Comment by indianets** [comment]
I have pushed the changes as per current consensus for review.

While renaming following https://docs.brew.sh/Rename-A-Formula, the name `gdrive` was being reserved, so I have skipped updating `formula_renamed.json`.

**Comment by indianets** [comment]
Yes, the binary was being generated as `gdrive@2` before this, should pass now.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
should be good for the merge after the build is green.

**Review by iMichka — APPROVED** [review]

**Comment by indianets** [comment]
Everything went through. Thank you!

**Comment by chenrui333** [comment]
@indianets thanks for your contribution to homebrew-core! 🎉

**Pull request merged**
