### PR TITLE
Updated gstreamer formulae to support --devel option

### PR DESCRIPTION
**Pull request by dr-impossible**
N.B. This PR depends on https://github.com/Homebrew/brew/pull/625 to work correctly
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> N.B. This PR depends on Homebrew/brew#625 to work correctly

Will avoid further review here until that's merged or rejected.

**Comment by ilovezfs** [comment]
Is there a way to get this PR working properly without being blocked by Homebrew/brew#625 ?

**Comment by jeffheifetz** [comment]
The other option is to change this to specifically have a gstreamer-devel formula. Which sounds like where this is headed.

**Comment by MikeMcQuaid** [comment]
Passing on this until we get https://github.com/Homebrew/brew/pull/625 or similar merged.

**Pull request closed without merging**
