### PR TITLE
mt32emu 2.5.3 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is needed to enable MT32 emulation in dosbox-staging. See
dosbox-staging/dosbox-staging#1270.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
The Linux linker is the worst.

**Review by SMillerDev — APPROVED** [review]

**Comment by DominusExult** [comment]
I'm happy that it is now included but at the same time it's funny that my old pull request was rejected (understandably by the rules) because it was without a test and I was explicitly told just a version check is not sufficient https://github.com/Homebrew/homebrew-core/pull/72618

**Comment by carlocab** [comment]
I would've been fine with merging your PR if it had implemented this exact same test.

**Comment by DominusExult** [comment]
Oh well, I inderstood Smillerdev's reply that a simple version check IS not a valid function test 🤷‍♂️
Hence I gave up last time as everything beyond the version check needs the ROM files.

**Comment by carlocab** [comment]
To be clear, there is more going on here than just a simple version check. We’re also checking that we can link against the library, and that the dynamic linker is able to resolve that linkage at runtime.

A test that needs a ROM file would be an improvement, though. It could be as simple as checking we get the expected error when no ROM files are provided.

**Pull request closed without merging**
