### PR TITLE
calicoctl 3.5.2

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Looks like the `make` targets have changed. Will investigate this further today.

**Comment by alebcay** [comment]
The recommended way to build this now is to use `make build`, which actually spawns a Docker container to handle all the dependencies (go, glide, etc.). To avoid that, we now just run the `go build ...` command natively (instead of in the Docker container)

**Comment by fxcoudert** [comment]
Why does it need docker?

**Comment by alebcay** [comment]
Huh. I thought I removed that before I pushed (I was trying to coax it along to use Docker at some point). Leave it to me to focus on the minutia and neglect the obvious.

**Comment by fxcoudert** [comment]
Been there, done that. Plenty of times.

Thanks @alebcay, again and again

**Pull request closed without merging**
