### PR TITLE
semtag: reenable formula

### PR DESCRIPTION
**Pull request by mwarkentin**
License has been added: https://github.com/pnikosis/semtag/blob/master/LICENSE

Reverts https://github.com/Homebrew/homebrew-core/pull/58432

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please also add the license definition.

**Comment by mwarkentin** [comment]
@SMillerDev Oops, thanks! Added!

**Comment by Rylan12** [comment]
Do we need a new release before we can add this? Even though it's been added upstream the latest source we use still does not contain any license.

**Comment by SMillerDev** [comment]
I'd say it's okay.

**Pull request closed without merging**
