### PR TITLE
include-what-you-use: fix when processing C++ sources

### PR DESCRIPTION
**Pull request by jamiesnape**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Formula worked fine with C, but not C++. Fixed and test added. Unfortunate so many headers have to be copied, but it is a long-standing, well-known issue with IWYU.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by bayandin** [comment]
`include-what-you-use` 0.13 has been released. Maybe it worth to bump the version in this PR?

**Comment by bayandin** [comment]
@SMillerDev are we good to merge this PR?

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
