### PR TITLE
Disable results audit for inreplace calls that update HOMEBREW_PREFIX

### PR DESCRIPTION
**Pull request by pkryger**
Functionality of `patch` in `Homebrew/brew` has been updated to automatically update "@@HOMEBREW\_PREFIX@@" with a value of `HOMEBREW_PREFIX` in external patches.

This is to prevent `inreplace` calls from raising and error when nothing has been replaced in patched files. Yet the `inreplace` calls are still needed to ensure forumlae are still installable, until `brew` is updated.

See https://github.com/Homebrew/brew/pull/18613 for more information. Once the aforementioned PR is in a stable brew tag these lines can be removed.

-------

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting? (all except `swift`)
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting? (all, except `swift`)
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks! Could you split your commits so that each one only modifies one formula, and use the commit header
```
<formula-name>: disable results audit for inreplace calls that update HOMEBREW_PREFIX
```
(or similar)

**Comment by pkryger** [comment]
@carlocab Good point. I split commits. Do you insist on having a separate PR per formula?

**Comment by carlocab** [comment]
I think this should be fine, but let's wait for Homebrew/brew#18613 to merge.

**Comment by pkryger** [comment]
> I think this should be fine, but let's wait for Homebrew/brew#18613 to merge.

Somehow I assumed merge order should be the other way around: this goes first and the Homebrew/brew#18613 later. That way there will be no time when something is broken. @MikeMcQuaid any comments?

**Review by MikeMcQuaid — APPROVED** [review]
I agree with @pkryger. This seems appropriate to merge now. Thanks!

**Pull request merged**
