### PR TITLE
mu 1.8.1

### PR DESCRIPTION
**Pull request by tshu-w**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tshu-w** [comment]
help wanted

**Comment by tshu-w** [comment]
I don't quite understand, I just copy the url from the releases page and run:
```console
brew bump-formula-pr --force --url=https://github.com/djcb/mu/releases/download/v1.8.1/mu-1.8.1.tar.xz mu
```

**Comment by SMillerDev** [comment]
Well, clearly something changed between the old version and the new version that makes the build fail. The way to fix this is to try and build the new version locally.

**Comment by tshu-w** [comment]
> Well, clearly something changed between the old version and the new version that makes the build fail. The way to fix this is to try and build the new version locally.

Got it. I will open a new PR later.

**Pull request closed without merging**
