### PR TITLE
openjpeg 2.4.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
opencv failed on 10.14
```
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
```

**Comment by chenrui333** [comment]
opencv@3 3.4.13 #67515
opencv 4.5.1 #67482

**Comment by Moisan** [comment]
I force pushed to rebase against master.

**Comment by miccal** [comment]
Thank you @Moisan.

**Review by Moisan — APPROVED** [review]

**Pull request closed without merging**
