### PR TITLE
suite-sparse: depend on `libomp` on macOS

### LINKED ISSUE #129011: Suitesparse compiled without OpenMP (and without _POSIX_C_SOURCE enabled)
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew suitesparse
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I compiled a software based on CHOLMOD (a library included with suitesparse) and when running the function SuiteSparse_tic() to extract the time (and some other SuiteSparse functionalities) does not work.

I believe the problem is that in SuiteSparse, the function SuiteSparse_tic() is defined as in [SuiteSparse_config.c](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/SuiteSparse_config/SuiteSparse_config.c) as:
```
#if !defined ( SUITESPARSE_TIMER_ENABLED )

    /* ---------------------------------------------------------------------- */
    /* no timer */
    /* ---------------------------------------------------------------------- */

    void SuiteSparse_tic
    (
        double tic [2]      /* output, contents undefined on input */
    )
    {
        /* no timer installed */
        tic [0] = 0 ;
        tic [1] = 0 ;
    }

#elif defined ( _OPENMP )

    /* ---------------------------------------------------------------------- */
    /* OpenMP timer */
    /* ---------------------------------------------------------------------- */

    void SuiteSparse_tic
    (
        double tic [2]      /* output, contents undefined on input */
    )
    {
        tic [0] = omp_get_wtime ( ) ;
        tic [1] = 0 ;
    }

#else 

    /* ---------------------------------------------------------------------- */
    /* POSIX timer */
    /* ---------------------------------------------------------------------- */

    #include <time.h>
    void SuiteSparse_tic
    (
        double tic [2]      /* output, contents undefined on input */
    )
    {
        /* POSIX C 1993 timer, requires -lrt */
        struct timespec t ;
        clock_gettime (CLOCK_MONOTONIC, &t) ;
        tic [0] = (double) (t.tv_sec) ;
        tic [1] = (double) (t.tv_nsec) ;
    }

#endif
```
And the macro `SUITESPARSE_TIMER_ENABLED` is defined in [SuiteSparse_config.h](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/SuiteSparse_config/SuiteSparse_config.h) as:
```
#ifndef NTIMER
    #if defined ( _OPENMP )
        #define SUITESPARSE_TIMER_ENABLED
    #elif defined ( _POSIX_C_SOURCE )
        #if _POSIX_C_SOURCE >= 199309L
        #define SUITESPARSE_TIMER_ENABLED
        #endif
    #endif
#endif
```
So that the issue arises from the fact that when compiling with clang both `_OPENMP` and `_POSIX_C_SOURCE` are not defined and so the timer is not enabled. There are two possible solutions:
- make sure SuiteSparse is compiled with OpenMP (preferred option as it would improve the efficiency of the library)
- make sure SuiteSparse is compiled with the `_POSIX_C_SOURCE` macro active (will at least recover the timer)

### What happened (include all command output)?

The SuiteSparse_tic() function returned zero

### What did you expect to happen?

The SuiteSparse_tic() function should have returned the current time

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Create the following `main.c` file:

#include <stdio.h>
#include <SuiteSparse_config.h>

int main() {
  double toc [2] ;
  SuiteSparse_tic (toc) ;
  printf("%f\n", toc [0] + 1e-9 * toc [1]);
}
```
Then run:
```
clang main.c -lsuitesparseconfig && ./a.out
```
It will return:
```
0.000000
```
While it should return something like:
```
1682111871.575413
```
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Upstream relies on OpenMP by default, and even [warns](https://github.com/DrTimothyAldenDavis/SuiteSparse#compilation-options) about the lack of
thread-safety without OpenMP.

Multiple users have also already asked for this.

Fixes #129011.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Because this depends on OpenBLAS, where OpenMP is provided by GCC, it should do the same.

**Comment by carlocab** [comment]
That's going to be a problem for dependents, since this has C++ code.

**Comment by fxcoudert** [comment]
But we don't want to mix OpenMP libraries either…

**Comment by carlocab** [comment]
Yea, I figured that: https://github.com/Homebrew/homebrew-core/issues/129011#issuecomment-1519011772

Not really sure about the way out other than to make OpenBLAS use `libomp` too. But that'll require some care as well.

**Comment by ywwry66** [comment]
> make OpenBLAS use libomp too

Because of https://github.com/Homebrew/homebrew-core/pull/50252#issuecomment-588140508, I have been doing this on my own for a while (https://github.com/ywwry66/homebrew-core/commit/a47be5190ef450f1f7c24d6068944637681a84e4). And for my workflow (R user), it has been working pretty well.

**Comment by junghans** [comment]
And there is #129512, which also fails due to mixing.

**Comment by junghans** [comment]
@fxcoudert  I looked at your comment again(https://github.com/Homebrew/homebrew-core/pull/50252#issuecomment-588140508). Has anything changed in the last 2 years? What is the status of clang + openMP these days?

**Comment by junghans** [comment]
I think this is a more general issue and we should track all the packages that are build with gcc only and document why.

I see two main reasons, a.) OpenMP, but that can be mostly be achieved with clang + libomp these days, b.) Fortran and OpenMP, this one is harder, but it would be work a try to build with the new `flang` (`flang-new`) compiler.

**Pull request closed without merging**
