### PR TITLE
Bandwhich support for M1

### PR DESCRIPTION
**Pull request by safwanrahman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
You can't add a bottle by just adding a hash. Are you saying it builds successfully from source now? In that case the maintainers can try to create a bottle on CI.

**Comment by carlocab** [comment]
Doesn't build on M1. It likely does without passing `--locked` to `cargo install`, but we don't want that.

**Comment by safwanrahman** [comment]
@carabolic I have run `cargo install --locked --path .` with the bandwhich source and it works perfectly there! I dont know why it is not building in homebrew! any idea?

**Comment by cho-m** [comment]
```
error occurred: Command "clang" "-O3" ... "--target=aarch64-apple-darwin" 
```

Looks like one of the Rust libraries is passing Rust target `aarch64-apple-darwin` over to Clang, which expects `arm64-apple-darwin`.

Could be `cc`: https://github.com/alexcrichton/cc-rs/issues/542

**Pull request closed without merging**
