### PR TITLE
erlang@18: add head and branch information

### PR DESCRIPTION
**Pull request by goncalotomas**
See #14815 for the discussion behind this submission.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks again @goncalotomas!

**Comment by goncalotomas** [comment]
Thank _you_ for sticking with me. 👍

**Comment by ilovezfs** [comment]
@goncalotomas you're welcome! I look forward to your next contribution :)

**Pull request merged**
