### PR TITLE
flank 21.02.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Error: An exception occurred within a child process:
  NameError: uninitialized constant Language::Java
```

**Comment by carlocab** [comment]
Will be unblocked by https://github.com/Homebrew/brew/pull/10471.

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
```
==> /usr/local/Cellar/flank/21.02.0/bin/flank android doctor
/usr/local/Cellar/flank/21.02.0/bin/flank: line 3: /usr/local/opt/openjdk/libexec/bin/java: No such file or directory
/usr/local/Cellar/flank/21.02.0/bin/flank: line 3: exec: /usr/local/opt/openjdk/libexec/bin/java: cannot execute: No such file or directory

Error: flank: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<126>.
```

**Review by carlocab — APPROVED** [review]

**Comment by jonchang** [comment]
`     ENV["JAVA_HOME"] = Formula["openjdk"].opt_prefix ` shouldn't be necessary as `bin.write_jar_script` handles it. https://github.com/Homebrew/brew/pull/10479

**Comment by carlocab** [comment]
Test block change to be reverted in #70212.

**Pull request merged**
