### PR TITLE
tomee-plus 7.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Why did the url change?

**Comment by chenrui333** [comment]
yeah, you are right, I will switched the url back, sorry for the confusion. :)

**Comment by chenrui333** [comment]
I was kind of think unifying the apache url reference pattern, but I guess that is not very much needed though.

**Comment by SMillerDev** [comment]
Thanks @chenrui333! Without contributions like yours it'd be impossible to keep homebrew going! 👍 🎉

**Pull request merged**
