### PR TITLE
atkmm 2.28.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
We're shipping ATK 2.30.0, which I don't think is compatible with atkmm 2.28.0. I suspect we might be packaging an unstable ATK by accident. See:

https://github.com/GNOME/atkmm/commit/6b5dc62f53dd3a9113cc338f21b1715cb3644f8e
https://download.gnome.org/sources/atkmm/2.29/atkmm-2.29.1.news

**Comment by alebcay** [comment]
In that case, `atkmm` 2.24.2 is incompatible with `atk` 2.30.0 anyways; we'd have to downgrade `atk` to 2.28.1 or wait for `atkmm` to catch up, right?

**Comment by fxcoudert** [comment]
The atkmm 2.28.0 announcement says: (https://mail.gnome.org/archives/gnome-announce-list/2018-November/msg00002.html)

> atkmm 2.28.0 (stable):
> This release is identical to 2.24.3.

I can't find any official announcement of atk 2.30.0, but it is a stable version following gnome nomenclature (odd subversion numbers are devel, even are stable). Nothing in the "news" file says otherwise, either: https://download.gnome.org/sources/atk/2.30/atk-2.30.0.news

And we haven't had a report of it being broken or unsuitable in 6 months.

poke @tschoonj for clarification

**Comment by tschoonj** [comment]
I think this is all ok... Surprised to see that this one slipped through my fingers in November... I usually follow these release announcements religiously 😄 

Generally speaking there should never be an issue building one of the C++ GNOME bindings against their C counterparts, as long as the latter is more recent or as recent the former. Worst case scenario is that some of the newer functionality added in the C release will have no C++ counterpart.

LGTM

**Comment by fxcoudert** [comment]
Thanks @tschoonj, and thanks @alebcay

**Pull request closed without merging**
