### PR TITLE
gedit: fix test for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
It looks like the `LDFLAGS` need the usual order change in the test block.

**Comment by cho-m** [comment]
There is something worse happening as linkage is failing:
```
==> brew linkage --test gedit
==> FAILED
Missing libraries:
  unexpected (libgedit-40.0.so)
```

I think some `*.so` libraries have `#{lib}` directory in RPATH but the library is located at `#{lib}/gedit/libgedit-40.0.so`.

**Comment by danielnachun** [comment]
Can we make a symlink from `#{lib}/gedit/libgedit-40.0.so` to `#{lib}`?  I'm not sure if there's a reason they have it in a subdirectory like that.

**Comment by danielnachun** [comment]
Separate from the linking issue, does this ship a `pkg-config` file?  The number of flags used for that test is absurd, and seems like something that should be handled by `pkg-config` if at all possible.

**Comment by cho-m** [comment]
`gedit` is another GNOME formula. In Homebrew, these formulae currently using manual flags.

Their test blocks should probably be updated to `pkg-config` (or alternatively `cmake` for some others). `gedit` provides the following .pc file:
```
prefix=@@HOMEBREW_CELLAR@@/gedit/40.1
libdir=${prefix}/lib
includedir=${prefix}/include

Name: gedit
Description: GNOME text editor
Version: 40.1
Requires: gio-2.0 >=  2.64, gtk+-3.0 >=  3.7.10, tepl-6 >=  5.99.0, libpeas-gtk-1.0
Libs: -L${prefix}/lib/gedit -lgedit-40.0
Cflags: -I${includedir}/gedit-40.0
```

---

For current PR issue, a symlink would probably fix it; though, it would only be used by Homebrew test block. As seen in above, `pkg-config` will output `lib/gedit`.

**Comment by danielnachun** [comment]
>Their test blocks should probably be updated to pkg-config (or alternatively cmake for some others).

Once we've bottled all the GNOME formulae, this would probably a good mini-project for someone to tackle.  

>For current PR issue, a symlink would probably fix it; though, it would only be used by Homebrew test block.

Would that also fix the linkage failure too though?  Since at least one binary in `gedit` itself apparently can't find `libgedit-40.0`.

**Comment by cho-m** [comment]
> Would that also fix the linkage failure too though? Since at least one binary in `gedit` itself apparently can't find `libgedit-40.0`.

Forgot about that. Yes, it should fix it.

Another option would be to add subdirectory to RPATH.

---

I'll probably take a look through code to see if there is any other way.

The main binary `bin/gedit` has correct RPATH:
```
  RPATH        @@HOMEBREW_PREFIX@@/Cellar/gedit/40.1/lib/gedit:@@HOMEBREW_PREFIX@@/Cellar/gedit/40.1/lib ...
```

It is the plugin libraries that aren't aware of actual path, e.g. `lib/gedit/plugins/libdocinfo.so`:
```
  RPATH        @@HOMEBREW_PREFIX@@/Cellar/gedit/40.1/lib:@@HOMEBREW_PREFIX@@/lib:@@HOMEBREW_PREFIX@@/opt/xz/lib: ...
```

**Comment by danielnachun** [comment]
Perhaps the only reason to favor the symlink approach is that it would be easier for other tools to find `libgedit`.  It's also possible that there is a build option to tell `gedit` to put `libgedit` in `#{lib}` instead of the `gedit` subdirectory.

**Comment by cho-m** [comment]
I think the `lib/gedit` subdirectory is standard. It is how Linux distros package `gedit`:
- Debian: https://packages.debian.org/experimental/amd64/gedit/filelist
- Arch: https://archlinux.org/packages/extra/x86_64/gedit/

The reason why binary is okay is because meson build adds RPATH:
```meson
executable(
  'gedit',
  'gedit.c',
  dependencies: libgedit_dep,
  c_args: gedit_c_args,
  install: true,
  install_rpath: get_option('prefix') / get_option('libdir') / 'gedit',
  gui_app: true,
)
```

---

As the RPATH in shared libraries are due to Homebrew (I think the default is no RPATH? at least that is how Arch's libraries are distributed), we may want to add the directory to RPATH via LDFLAGS.

**Comment by cho-m** [comment]
RPATH modification helps fix shared library linkage.

Only test failure is left, which seems to be another RPATH issue in test binary. I guess doing `-Wl,rpath` should help.
```
==> ./test
./test: error while loading shared libraries: libgedit-40.0.so: cannot open shared object file: No such file or directory
Error: gedit: failed
An exception occurred within a child process:
  BuildError: Failed executing: ./test
```

**Review by danielnachun — APPROVED** [review]

**Pull request merged**
