### PR TITLE
Presto 307

### PR DESCRIPTION
**Pull request by martint**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the pull request, why are the endpoints changing? The old ones seem to still be valid and maintained and don't mention anything about a change.

**Comment by martint** [comment]
Recently, the Presto Software Foundation was founded (https://prweb.com/releases/prweb16070792.htm), and a new website and github for repository for the project were set up. It's where the majority of the committers and much of the community are doing active development now. The old site/version is where Facebook continues to develop their own version.

**Comment by martint** [comment]
Updated for Presto 307, which was released last week.

**Comment by findepi** [comment]
@SMillerDev  https://prestosql.io is the new how for Presto community, and this is the place where project creators, most active contributors and most of the community are.
Please have a look at contributors list (https://github.com/prestodb/presto/graphs/contributors or https://github.com/prestosql/presto/graphs/contributors). Please compare that list with the people giving thumbs-up here.

**Comment by jonchang** [comment]
Pinging some of the recent contributors to the prestodb repository: @mbasmanova @arhimondr @rongrong @wenleix @elonazoulay

Can Facebook comment on these changes? Also, who owns the "Presto" name (if anyone)?

**Comment by mbasmanova** [comment]
@jonchang Facebook continues to run the original Presto project as open source. https://prestodb.io and https://prestodb.github.io/ are the proper URLs for the project. PrestoSQL is a fork being run by a separate entity.

CC: @tdcmeehan @nezihyigitbasi

**Comment by SMillerDev** [comment]
I believe this should be a new formula then @martint . Could you change this pull request to make a new formula?

**Pull request closed without merging**
