### PR TITLE
kubernetes-cli v1.23 - keg only

### PR DESCRIPTION
**Pull request by m-kalai**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
I don't think we want to add a formula that will be deprecated in a few months.

If you wish, you can host this formula in your own tap. Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by m-kalai** [comment]
I was hoping it can replace kubernetes-cli@1.22 which is release currently in the maintenance mode, and will be at the end of the life by the end of the month - 2022-10-28.

Current version of kubernetes-cli formula is at 1.25 release which is outside of the allowed +/- 1 minor version skew if your cluster is still on 1.23 (which is still supported release).

But if that's the decision, thanks for the suggestion about private tap, i'll look into it!

**Comment by carlocab** [comment]
Versioned formulae in this repository have a bad habit of sticking around far longer than they ought to -- there are just too many formulae to keep track of them properly. This makes me reluctant to add it here with only three months until it goes into maintenance mode.

It might even help to organise a tap with other users who are interested in older versions of `kubernetes-cli` so you can share the work of maintaining it. CC @cglong, who might be open to collaborating on this/know others who will.

**Comment by cglong** [comment]
Thanks for the mention @carlocab!

@m-kalai, can we add some justification for why `kubernetes-cli@1.23` should be added to `homebrew/core`? Per [the Homebrew docs](https://docs.brew.sh/Versions#acceptable-versioned-formulae):

> Versioned formulae submitted should be expected to be used by a large number of people. If this ceases to be the case, they will be removed. We will aim not to remove those in the [top 3,000 `install_on_request` formulae](https://brew.sh/analytics/install-on-request/).

See https://github.com/Homebrew/homebrew-core/pull/90075#issuecomment-991436454 for the justification I used when submitting `kubernetes-cli@1.22` 🙂

**Comment by carlocab** [comment]
To be clear, I don't think we'll be adding this formulae to Homebrew/core. This is two months away from maintenance mode. This was not the case about 1.22 at the time it was added.

Please do feel free to coordinate on hosting it in an external tap instead.

**Comment by m-kalai** [comment]
> Thanks for the mention @carlocab!
> 
> @m-kalai, can we add some justification for why `kubernetes-cli@1.23` should be added to `homebrew/core`? Per [the Homebrew docs](https://docs.brew.sh/Versions#acceptable-versioned-formulae):
> 
> > Versioned formulae submitted should be expected to be used by a large number of people. If this ceases to be the case, they will be removed. We will aim not to remove those in the [top 3,000 `install_on_request` formulae](https://brew.sh/analytics/install-on-request/).
> 
> See [#90075 (comment)](https://github.com/Homebrew/homebrew-core/pull/90075#issuecomment-991436454) for the justification I used when submitting `kubernetes-cli@1.22` 🙂

@cglong I can only say pretty much what you said before. Latest EKS version is currently 1.23.7 which is outside of the version skew policy of current kubernetes-cli formula which is on 1.25.2.

@carlocab Sure, if it's a problem i'm fine with moving this to my tap instead. Should i close this PR then?

**Comment by cglong** [comment]
> @cglong I can only say pretty much what you said before. Latest EKS version is currently 1.23.7 which is outside of the version skew policy of current kubernetes-cli formula which is on 1.25.2.

You may consider creating a PR for v1.24 instead, which will have a much longer timeline before deprecation 🙂

**Comment by iMichka** [comment]
Closing here. I think we can accept v1.24 if necessary. But at this point someone might host every version in tap, which would be the preferred way.

**Pull request closed without merging**
