### PR TITLE
liblwgeom: remove livecheck

### PR DESCRIPTION
**Pull request by chenrui333**
skip livecheck as formula is deprecated

### CODE REVIEW

**Review by samford — CHANGES_REQUESTED** [review]
`brew livecheck` automatically skips deprecated formulae that don't have a `livecheck` block, so all you need to do here is remove the `livecheck` block.

I've been meaning to revisit some of the formulae that use `skip` in the `livecheck` block to see if there are any that can be deprecated but my plate's pretty full at the moment.

**Comment by chenrui333** [comment]
Somehow it still shows livecheck result for me.

<details>
<summary>livecheck result</summary>

```
$ brew livecheck liblwgeom
#<Homebrew::CLI::Args named=["liblwgeom"], remaining=["liblwgeom"], d?=true, debug?=true, v?=true, verbose?=true>
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/liblwgeom.rb

Formula:          liblwgeom
Livecheckable?:   Yes

URL:              https://download.osgeo.org/postgis/source/
Strategies:       PageMatch
Strategy:         PageMatch
Regex:            /href=.*?postgis[._-]v?(\d+(?:\.\d+)+)\.t/i

Matched Versions:
0.1 => #<Version:0x00007fd83c1b1c48 @version="0.1", @detected_from_url=false>
0.2 => #<Version:0x00007fd83c1b1ba8 @version="0.2", @detected_from_url=false>
0.5.0 => #<Version:0x00007fd83c1b1b30 @version="0.5.0", @detected_from_url=false>
0.5.1 => #<Version:0x00007fd83c1b1a40 @version="0.5.1", @detected_from_url=false>
0.6.0 => #<Version:0x00007fd83c1b19c8 @version="0.6.0", @detected_from_url=false>
0.6.1 => #<Version:0x00007fd83c1b1928 @version="0.6.1", @detected_from_url=false>
0.6.2 => #<Version:0x00007fd83c1b1860 @version="0.6.2", @detected_from_url=false>
0.7.0 => #<Version:0x00007fd83c1b17c0 @version="0.7.0", @detected_from_url=false>
0.7.1 => #<Version:0x00007fd83c1b16f8 @version="0.7.1", @detected_from_url=false>
0.7.2 => #<Version:0x00007fd83c1b1680 @version="0.7.2", @detected_from_url=false>
0.7.3 => #<Version:0x00007fd83c1b1608 @version="0.7.3", @detected_from_url=false>
0.7.4 => #<Version:0x00007fd83c1b1540 @version="0.7.4", @detected_from_url=false>
0.7.5 => #<Version:0x00007fd83c1b14a0 @version="0.7.5", @detected_from_url=false>
0.8.0 => #<Version:0x00007fd83c1b13d8 @version="0.8.0", @detected_from_url=false>
0.8.1 => #<Version:0x00007fd83c1b1298 @version="0.8.1", @detected_from_url=false>
0.8.2 => #<Version:0x00007fd83c1b11f8 @version="0.8.2", @detected_from_url=false>
0.9.0 => #<Version:0x00007fd83c1b1068 @version="0.9.0", @detected_from_url=false>
0.9.1 => #<Version:0x00007fd83c1b0ff0 @version="0.9.1", @detected_from_url=false>
0.9.2 => #<Version:0x00007fd83c1b0fa0 @version="0.9.2", @detected_from_url=false>
1.0.0 => #<Version:0x00007fd83c1b0f50 @version="1.0.0", @detected_from_url=false>
1.0.1 => #<Version:0x00007fd83c1b0ed8 @version="1.0.1", @detected_from_url=false>
1.0.2 => #<Version:0x00007fd83c1b0e88 @version="1.0.2", @detected_from_url=false>
1.0.3 => #<Version:0x00007fd83c1b0de8 @version="1.0.3", @detected_from_url=false>
1.0.4 => #<Version:0x00007fd83c1b0d98 @version="1.0.4", @detected_from_url=false>
1.0.5 => #<Version:0x00007fd83c1b0d20 @version="1.0.5", @detected_from_url=false>
1.0.6 => #<Version:0x00007fd83c1b0cd0 @version="1.0.6", @detected_from_url=false>
1.1.0 => #<Version:0x00007fd83c1b0c30 @version="1.1.0", @detected_from_url=false>
1.1.1 => #<Version:0x00007fd83c1b0bb8 @version="1.1.1", @detected_from_url=false>
1.1.2 => #<Version:0x00007fd83c1b0b40 @version="1.1.2", @detected_from_url=false>
1.1.3 => #<Version:0x00007fd83c1b0af0 @version="1.1.3", @detected_from_url=false>
1.1.4 => #<Version:0x00007fd83c1b0a50 @version="1.1.4", @detected_from_url=false>
1.1.5 => #<Version:0x00007fd83c1b0988 @version="1.1.5", @detected_from_url=false>
1.1.6 => #<Version:0x00007fd83c1b0910 @version="1.1.6", @detected_from_url=false>
1.1.7 => #<Version:0x00007fd83c1b07a8 @version="1.1.7", @detected_from_url=false>
1.2.0 => #<Version:0x00007fd83c1b0730 @version="1.2.0", @detected_from_url=false>
1.2.1 => #<Version:0x00007fd83c1b06b8 @version="1.2.1", @detected_from_url=false>
1.3.0 => #<Version:0x00007fd83c1b0668 @version="1.3.0", @detected_from_url=false>
1.3.1 => #<Version:0x00007fd83c1b05c8 @version="1.3.1", @detected_from_url=false>
1.3.2 => #<Version:0x00007fd83c1b0578 @version="1.3.2", @detected_from_url=false>
1.3.3 => #<Version:0x00007fd83c1b0528 @version="1.3.3", @detected_from_url=false>
1.3.4 => #<Version:0x00007fd83c1b04b0 @version="1.3.4", @detected_from_url=false>
1.3.5 => #<Version:0x00007fd83c1b0438 @version="1.3.5", @detected_from_url=false>
1.3.6 => #<Version:0x00007fd83c1b0398 @version="1.3.6", @detected_from_url=false>
1.4.0 => #<Version:0x00007fd83c1b0320 @version="1.4.0", @detected_from_url=false>
1.4.1 => #<Version:0x00007fd83c1b02d0 @version="1.4.1", @detected_from_url=false>
1.4.2 => #<Version:0x00007fd83c1b0280 @version="1.4.2", @detected_from_url=false>
1.5.0 => #<Version:0x00007fd83c1b0208 @version="1.5.0", @detected_from_url=false>
1.5.1 => #<Version:0x00007fd83c1b0190 @version="1.5.1", @detected_from_url=false>
1.5.2 => #<Version:0x00007fd83c1b0118 @version="1.5.2", @detected_from_url=false>
1.5.3 => #<Version:0x00007fd83c1bbe78 @version="1.5.3", @detected_from_url=false>
1.5.4 => #<Version:0x00007fd83c1bbd60 @version="1.5.4", @detected_from_url=false>
1.5.5 => #<Version:0x00007fd83c1bbc70 @version="1.5.5", @detected_from_url=false>
1.5.6 => #<Version:0x00007fd83c1bbb30 @version="1.5.6", @detected_from_url=false>
1.5.7 => #<Version:0x00007fd83c1bba18 @version="1.5.7", @detected_from_url=false>
1.5.8 => #<Version:0x00007fd83c1bb838 @version="1.5.8", @detected_from_url=false>
2.0.0 => #<Version:0x00007fd83c1bb608 @version="2.0.0", @detected_from_url=false>
2.0.1 => #<Version:0x00007fd83c1bb450 @version="2.0.1", @detected_from_url=false>
2.0.2 => #<Version:0x00007fd83c1bb220 @version="2.0.2", @detected_from_url=false>
2.0.3 => #<Version:0x00007fd83c1bb0e0 @version="2.0.3", @detected_from_url=false>
2.0.4 => #<Version:0x00007fd83c1bafc8 @version="2.0.4", @detected_from_url=false>
2.0.5 => #<Version:0x00007fd83c1baed8 @version="2.0.5", @detected_from_url=false>
2.0.6 => #<Version:0x00007fd83c1bae10 @version="2.0.6", @detected_from_url=false>
2.0.7 => #<Version:0x00007fd83c1bad20 @version="2.0.7", @detected_from_url=false>
2.1.0 => #<Version:0x00007fd83c1ba9b0 @version="2.1.0", @detected_from_url=false>
2.1.1 => #<Version:0x00007fd83c1ba780 @version="2.1.1", @detected_from_url=false>
2.1.2 => #<Version:0x00007fd83c1ba5a0 @version="2.1.2", @detected_from_url=false>
2.1.3 => #<Version:0x00007fd83c1ba4b0 @version="2.1.3", @detected_from_url=false>
2.1.4 => #<Version:0x00007fd83c1ba348 @version="2.1.4", @detected_from_url=false>
2.1.5 => #<Version:0x00007fd83c1ba028 @version="2.1.5", @detected_from_url=false>
2.1.6 => #<Version:0x00007fd83c1b9330 @version="2.1.6", @detected_from_url=false>
2.1.7 => #<Version:0x00007fd83c1b91f0 @version="2.1.7", @detected_from_url=false>
2.1.8 => #<Version:0x00007fd83c1b90b0 @version="2.1.8", @detected_from_url=false>
2.1.9 => #<Version:0x00007fd83c1b8f70 @version="2.1.9", @detected_from_url=false>
2.2.0 => #<Version:0x00007fd83c1b8e08 @version="2.2.0", @detected_from_url=false>
2.2.1 => #<Version:0x00007fd83c1b8a48 @version="2.2.1", @detected_from_url=false>
2.2.2 => #<Version:0x00007fd83c1b8868 @version="2.2.2", @detected_from_url=false>
2.2.3 => #<Version:0x00007fd83c1b8660 @version="2.2.3", @detected_from_url=false>
2.2.4 => #<Version:0x00007fd83c1c3d58 @version="2.2.4", @detected_from_url=false>
2.2.5 => #<Version:0x00007fd83c1c3b00 @version="2.2.5", @detected_from_url=false>
2.2.6 => #<Version:0x00007fd83c1c3628 @version="2.2.6", @detected_from_url=false>
2.2.7 => #<Version:0x00007fd83c1c3358 @version="2.2.7", @detected_from_url=false>
2.2.8 => #<Version:0x00007fd83c1c3060 @version="2.2.8", @detected_from_url=false>
2.3.0 => #<Version:0x00007fd83c1c2ae8 @version="2.3.0", @detected_from_url=false>
2.3.1 => #<Version:0x00007fd83c1c24f8 @version="2.3.1", @detected_from_url=false>
2.3.10 => #<Version:0x00007fd83c1c2340 @version="2.3.10", @detected_from_url=false>
2.3.11 => #<Version:0x00007fd83c1c2138 @version="2.3.11", @detected_from_url=false>
2.3.2 => #<Version:0x00007fd83c1c1f80 @version="2.3.2", @detected_from_url=false>
2.3.3 => #<Version:0x00007fd83c1c0bf8 @version="2.3.3", @detected_from_url=false>
2.3.4 => #<Version:0x00007fd83c1c0b58 @version="2.3.4", @detected_from_url=false>
2.3.5 => #<Version:0x00007fd83c1c0ab8 @version="2.3.5", @detected_from_url=false>
2.3.6 => #<Version:0x00007fd83c1c06d0 @version="2.3.6", @detected_from_url=false>
2.3.7 => #<Version:0x00007fd83c1c0450 @version="2.3.7", @detected_from_url=false>
2.3.8 => #<Version:0x00007fd83c1c03d8 @version="2.3.8", @detected_from_url=false>
2.3.9 => #<Version:0x00007fd83c1c02c0 @version="2.3.9", @detected_from_url=false>
2.4.0 => #<Version:0x00007fd83c1c01a8 @version="2.4.0", @detected_from_url=false>
2.4.1 => #<Version:0x00007fd83c1c0018 @version="2.4.1", @detected_from_url=false>
2.4.2 => #<Version:0x00007fd83c1cbf30 @version="2.4.2", @detected_from_url=false>
2.4.3 => #<Version:0x00007fd83c1cbda0 @version="2.4.3", @detected_from_url=false>
2.4.4 => #<Version:0x00007fd83c1cbcb0 @version="2.4.4", @detected_from_url=false>
2.4.5 => #<Version:0x00007fd83c1cb8a0 @version="2.4.5", @detected_from_url=false>
2.4.6 => #<Version:0x00007fd83c1cb850 @version="2.4.6", @detected_from_url=false>
2.4.7 => #<Version:0x00007fd83c1cb7b0 @version="2.4.7", @detected_from_url=false>
2.4.8 => #<Version:0x00007fd83c1cb5d0 @version="2.4.8", @detected_from_url=false>
2.4.9 => #<Version:0x00007fd83c1cadb0 @version="2.4.9", @detected_from_url=false>
2.5.0 => #<Version:0x00007fd83c1ca068 @version="2.5.0", @detected_from_url=false>
2.5.1 => #<Version:0x00007fd83c1c9aa0 @version="2.5.1", @detected_from_url=false>
2.5.2 => #<Version:0x00007fd83c1c9730 @version="2.5.2", @detected_from_url=false>
2.5.3 => #<Version:0x00007fd83c1c9618 @version="2.5.3", @detected_from_url=false>
2.5.4 => #<Version:0x00007fd83c1c9500 @version="2.5.4", @detected_from_url=false>
2.5.5 => #<Version:0x00007fd83c1c9410 @version="2.5.5", @detected_from_url=false>
3.0.0 => #<Version:0x00007fd83c1c9208 @version="3.0.0", @detected_from_url=false>
3.0.1 => #<Version:0x00007fd83c1c9078 @version="3.0.1", @detected_from_url=false>
3.0.2 => #<Version:0x00007fd83c1c8f10 @version="3.0.2", @detected_from_url=false>
3.0.3 => #<Version:0x00007fd83c1c8e70 @version="3.0.3", @detected_from_url=false>
3.1.0 => #<Version:0x00007fd83c1c8bf0 @version="3.1.0", @detected_from_url=false>
liblwgeom : 2.5.4 ==> 3.1.0
```

</details>

**Comment by samford** [comment]
The debug output says there's still a `livecheck` block in the formula (i.e., `Livecheckable?: Yes`). If you deleted the block, you may not have saved the change.

With this change:

```patch
diff --git a/Formula/liblwgeom.rb b/Formula/liblwgeom.rb
index c5cda3c1301d6b31fabbc3268e620fdb8d279452..fa132199c7e585d4332f58a1b7fc092e04ba88c4 100644
--- a/Formula/liblwgeom.rb
+++ b/Formula/liblwgeom.rb
@@ -6,11 +6,6 @@ class Liblwgeom < Formula
   revision 1
   head "https://git.osgeo.org/gitea/postgis/postgis.git"
 
-  livecheck do
-    url "https://download.osgeo.org/postgis/source/"
-    regex(/href=.*?postgis[._-]v?(\d+(?:\.\d+)+)\.t/i)
-  end
-
   bottle do
     cellar :any
     rebuild 1
```

I see this output:

```
$ brew livecheck --debug liblwgeom
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/liblwgeom.rb
liblwgeom : deprecated
```

**Comment by chenrui333** [comment]
that makes sense.

**Review by samford — APPROVED** [review]

**Pull request merged**
