### PR TITLE
dhall-text 1.0.18 (new formula)

### PR DESCRIPTION
**Pull request by Gabriella439**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Duplicate of https://github.com/Homebrew/homebrew-core/pull/41390

**Comment by Gabriel439** [comment]
@SMillerDev: I believe this is not a duplicate of #41390 (I authored both of these pull requests).  This is a pull request to add the `dhall-text` package to `brew` whereas #41390  is a pull request to add the `dhall-bash` package to `brew` (which is a distinct package).

**Comment by SMillerDev** [comment]
Whoops you're right I read it wrong. Could you make this PR again?

**Comment by vvv** [comment]
@SMillerDev Are you sure new PR is necessary?  It would take maintainer (you) a single click in GitHub UI to reopen this one...
Thanks.

**Comment by SMillerDev** [comment]
Afaik it doesn't work too well with CI but we can try.

**Comment by lorenzo** [comment]
Eagerly waiting for this :D

**Comment by vvv** [comment]
How long does it usually take for a PR like this to be merged?

**Comment by SMillerDev** [comment]
Until people have time to review it. Could be hours, could be months

**Comment by vvv** [comment]
Fair enough. Thanks, @SMillerDev.

**Comment by lorenzo** [comment]
@SMillerDev is that a process any of us can help with?

**Comment by Gabriel439** [comment]
Actually, we can close out this issue as the `dhall-text` package will be superseded by the next release of `dhall` (which will now provide a `dhall text` subcommand that does the same thing).  For more details, see: https://github.com/dhall-lang/dhall-haskell/pull/1090/

However, https://github.com/Homebrew/homebrew-core/pull/41390 still needs to be reviewed

**Pull request closed without merging**
