### PR TITLE
xmlsectool: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See #75943.

### CODE REVIEW

**Comment by carlocab** [comment]
```
❯ sha256sum *.tar.gz
07ce19346af91dbcc068fc78f00090ea3dd06bee72dc6c5e6901b12a0eef6bab  xmlsectool--3.0.0.arm64_big_sur.bottle.tar.gz
08f56219830aaf82a142dd338e4fd6ebc48f48ade7cc1a23646d78cc7ca7d48f  xmlsectool--3.0.0.big_sur.bottle.tar.gz
08f56219830aaf82a142dd338e4fd6ebc48f48ade7cc1a23646d78cc7ca7d48f  xmlsectool--3.0.0.catalina.bottle.tar.gz
08f56219830aaf82a142dd338e4fd6ebc48f48ade7cc1a23646d78cc7ca7d48f  xmlsectool--3.0.0.mojave.bottle.tar.gz
```
Still different, and still timestamp-related (I think)

**Comment by Bo98** [comment]
Looks like a `gzip` difference.

**Comment by Bo98** [comment]
Looks timezone related.

**Comment by Bo98** [comment]
https://github.com/Homebrew/brew/pull/11264

**Comment by Moisan** [comment]
Rebased on top of master.

**Comment by carlocab** [comment]
```
❯ sha256sum *.tar.gz
08f56219830aaf82a142dd338e4fd6ebc48f48ade7cc1a23646d78cc7ca7d48f  xmlsectool--3.0.0.arm64_big_sur.bottle.tar.gz
08f56219830aaf82a142dd338e4fd6ebc48f48ade7cc1a23646d78cc7ca7d48f  xmlsectool--3.0.0.big_sur.bottle.tar.gz
08f56219830aaf82a142dd338e4fd6ebc48f48ade7cc1a23646d78cc7ca7d48f  xmlsectool--3.0.0.catalina.bottle.tar.gz
08f56219830aaf82a142dd338e4fd6ebc48f48ade7cc1a23646d78cc7ca7d48f  xmlsectool--3.0.0.mojave.bottle.tar.gz
```
Thanks @Bo98, @Moisan.

**Review by Moisan — APPROVED** [review]

**Pull request closed without merging**
