### PR TITLE
chronograf (new formula)

### PR DESCRIPTION
**Pull request by gunnaraasen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is essentially a reopening of https://github.com/Homebrew/homebrew-core/pull/7800 now that Chronograf released its first stable, open source version 1.3.0. This formula also works now.

Chronograf is a time series monitoring/visualization project which seamlessly integrates with the TICK stack ([Telegraf](https://github.com/Homebrew/homebrew-core/blob/master/Formula/telegraf.rb), [InfluxDB](https://github.com/Homebrew/homebrew-core/blob/master/Formula/influxdb.rb), and [Kapacitor](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kapacitor.rb)). Currently available via [homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/chronograf.rb), it recently underwent a significant rewrite and was [open-sourced](https://www.influxdata.com/announcing-the-new-chronograf-a-ui-for-the-tick-stack-and-a-complete-open-source-monitoring-solution/).

Now that Chronograf can be built directly from the source, I'd like to move the formula to homebrew-core. I've opened a new PR on the homebrew-cask tap to remove and redirect that formula to homebrew-core (see https://github.com/caskroom/homebrew-cask/pull/33891). Note, there also used to be a Chronograf formula on the homebrew-binary tap that was migrated to the homebrew-cask tap (see https://github.com/Homebrew/homebrew-binary/pull/356).

Thanks for the review! Let me know if there are any questions.

### CODE REVIEW

**Comment by gunnaraasen** [comment]
Looks like `brew audit --online --new-formula chronograf` is failing due to the existence of `caskroom/cask/chronograf`.

**Comment by vitorgalvao** [comment]
Just need someone on this side to give the OK, and we’ll remove from HBC.

**Comment by dunn** [comment]
Looks good to me.

**Comment by vitorgalvao** [comment]
@dunn Thank you. I’ll be merging in HBC, then.

**Comment by gunnaraasen** [comment]
Thank you @vitorgalvao.

Now that the `chronograf` formula has been removed from HBC and tests pass, this formula is ready for review.

**Comment by dunn** [comment]
Looks good, thanks! Merged as 2cb17586799ae08928521b743be0b46542421e65.

**Pull request closed without merging**
