### PR TITLE
ns-3 3.37

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by FtZPetruska** [comment]
```ruby
# Starting 3.36, bindings are no longer installed
# https://gitlab.com/nsnam/ns-3-dev/-/merge_requests/1060
site_packages = Language::Python.site_packages("python3.10")
(prefix/site_packages).install (buildpath/"build/bindings/python").children
```

Starting 3.37, this workaround is no longer necessary. The bindings install directory can be set using `NS3_BINDINGS_INSTALL_DIR` in CMake. (https://gitlab.com/nsnam/ns-3-dev/-/merge_requests/1063)

```ruby
resource "pybindgen" do
  url "https://files.pythonhosted.org/packages/e0/8e/de441f26282eb869ac987c9a291af7e3773d93ffdb8e4add664b392ea439/PyBindGen-0.22.1.tar.gz"
  sha256 "8c7f22391a49a84518f5a2ad06e3a5b1e839d10e34da7631519c8a28fcba3764"
end
```

Pybindgen was dropped in 3.37 in favour of using Cppyy. One major difference is that **cppyy needs to be available at runtime**. (https://gitlab.com/nsnam/ns-3-dev/-/blob/master/RELEASE_NOTES.md?plain=1#L42)

**Comment by chenrui333** [comment]
This PR might still has some issue loading the library (at least in my local), and it would fail test.

cc @FtZPetruska feel free to file a new PR, I can just close this one.

**Comment by chenrui333** [comment]
```
  ==> /opt/homebrew/opt/python@3.11/bin/python3.11 /opt/homebrew/Cellar/ns-3/3.37/share/ns-3/first.py
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/ns-3/3.37/share/ns-3/first.py", line 16, in <module>
      from ns import ns
    File "/opt/homebrew/lib/python3.11/site-packages/ns/__init__.py", line 488, in <module>
      ns = load_modules()  # can be imported via 'from ns import ns'
           ^^^^^^^^^^^^^^
    File "/opt/homebrew/lib/python3.11/site-packages/ns/__init__.py", line 217, in load_modules
      raise Exception("ns-3 libraries were not found.")
  Exception: ns-3 libraries were not found.
  Error: ns-3: failed
```

**Comment by FtZPetruska** [comment]
> ```
>   ==> /opt/homebrew/opt/python@3.11/bin/python3.11 /opt/homebrew/Cellar/ns-3/3.37/share/ns-3/first.py
>   Traceback (most recent call last):
>     File "/opt/homebrew/Cellar/ns-3/3.37/share/ns-3/first.py", line 16, in <module>
>       from ns import ns
>     File "/opt/homebrew/lib/python3.11/site-packages/ns/__init__.py", line 488, in <module>
>       ns = load_modules()  # can be imported via 'from ns import ns'
>            ^^^^^^^^^^^^^^
>     File "/opt/homebrew/lib/python3.11/site-packages/ns/__init__.py", line 217, in load_modules
>       raise Exception("ns-3 libraries were not found.")
>   Exception: ns-3 libraries were not found.
>   Error: ns-3: failed
> ```

I was able to fix this through a rather small patch (changing the `DEFAULT_INCLUDE/LIB_DIR` to the Cellar directory):
```diff
diff --git a/Formula/ns-3.rb b/Formula/ns-3.rb
index 6f38aac93a9..090bc5d6783 100644
--- a/Formula/ns-3.rb
+++ b/Formula/ns-3.rb
@@ -45,6 +45,12 @@ class Ns3 < Formula
   end
 
   def install
+    # Set binding's search path to Homebrew installation
+    inreplace "bindings/python/ns__init__.py" do |s|
+      s.gsub! "sysconfig.get_config_var(\"INCLUDEDIR\")", "\"#{include}\""
+      s.gsub! "sysconfig.get_config_var(\"LIBDIR\")", "\"#{lib}\""
+    end
+
     # Fix binding's rpath
     linker_flags = ["-Wl,-rpath,#{loader_path}"]
     linker_flags << "-Wl,-undefined,dynamic_lookup" if OS.mac?
```

Unfortunately, the bindings now depend on `cppyy` at runtime (previously they used `pybindgen` only at build time).
I am not sure about Homebrew's stance on such issue:
- Should `cppyy` be offered as a formula and then added as a dependency of ns-3?
- Should `cppyy` be installed in ns-3's `libexec` and the python package be further patched to import it from there?
- Should python bindings be dropped altogether?

**Pull request closed without merging**
