### PR TITLE
qt: Add patch for QToolButton style issues

### PR DESCRIPTION
**Pull request by jonaski**
This fix was supposed to be included with Qt 6.2.2, but just missed it.
See: https://codereview.qt-project.org/c/qt/qtbase/+/383265

I haven't done the tests because I don't have a mac.

### CODE REVIEW

**Comment by Bo98** [comment]
Qt 6.2.3 is going to be released in a couple days, so we can just wait for that.

**Comment by carlocab** [comment]
> I haven't done the tests because I don't have a mac.

You can run the tests on Linux.

**Comment by carlocab** [comment]
The formula also needs this patch:
```diff
diff --git a/Formula/qt.rb b/Formula/qt.rb
index 5b29a1bc042..980c59209e5 100644
--- a/Formula/qt.rb
+++ b/Formula/qt.rb
@@ -170,7 +170,7 @@ class Qt < Formula
 
     rm bin/"qt-cmake-private-install.cmake"
 
-    inreplace lib/"cmake/Qt6/qt.toolchain.cmake", Superenv.shims_path, ""
+    inreplace lib/"cmake/Qt6/qt.toolchain.cmake", "#{Superenv.shims_path}/", ""
 
     # The pkg-config files installed suggest that headers can be found in the
     # `include` directory. Make this so by creating symlinks from `include` to
```
Otherwise, we get these lines in `qt.toolchain.cmake`:
```
    set(__qt_initial_c_compiler "/clang")
    set(__qt_initial_cxx_compiler "/clang++")
```

**Comment by jonaski** [comment]
Qt 6.2.3 is released now.

**Pull request closed without merging**
