### PR TITLE
fabric: upgrade cryptography resource to latest

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
I think you can also update the `cffi` resource. Please add `revision 1` right after the `license` line (so that users get this update when they do `brew upgrade`), and squash your commits together when you do.

This is the output of `brew update-python-resources`:

```diff
diff --git a/Formula/fabric.rb b/Formula/fabric.rb
index feb1235a3f..d9eb6966f4 100644
--- a/Formula/fabric.rb
+++ b/Formula/fabric.rb
@@ -24,13 +24,13 @@ class Fabric < Formula
   end
 
   resource "cffi" do
-    url "https://files.pythonhosted.org/packages/66/6a/98e023b3d11537a5521902ac6b50db470c826c682be6a8c661549cb7717a/cffi-1.14.4.tar.gz"
-    sha256 "1a465cbe98a7fd391d47dce4b8f7e5b921e6cd805ef421d04f5f66ba8f06086c"
+    url "https://files.pythonhosted.org/packages/a8/20/025f59f929bbcaa579704f443a438135918484fffaacfaddba776b374563/cffi-1.14.5.tar.gz"
+    sha256 "fd78e5fee591709f32ef6edb9a015b4aa1a5022598e36227500c8f4e02328d9c"
   end
 
   resource "cryptography" do
-    url "https://files.pythonhosted.org/packages/b7/82/f7a4ddc1af185936c1e4fa000942ffa8fb2d98cff26b75afa7b3c63391c4/cryptography-3.3.1.tar.gz"
-    sha256 "7e177e4bea2de937a584b13645cab32f25e3d96fc0bc4a4cf99c27dc77682be6"
+    url "https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz"
+    sha256 "2d32223e5b0ee02943f32b19245b61a62db83a882f0e76cc564e1cec60d48f87"
   end
 
   resource "invoke" do
```

Thanks!

**Comment by alex** [comment]
Thanks, will do that. I'm one of the maintainers of cryptography, hence my interest in updating it. Is it acceptable for me to send similar PRs to other brew formulas that are similarly running older versions?

**Comment by carlocab** [comment]
As long as it doesn't break anything, that's fine. Don't forget to increment the `revision` lines so that the update gets shipped to users.

If you have `brew` installed, you can also do `brew update-python-resources $formula` to check if anything else is outdated.

**Comment by alex** [comment]
Thanks, I appreciate the guidance. (The machine I do most of my dev on these days uses linuxbrew, so I'm not totally sure how that works from a contributing upstream perspective.)

**Comment by carlocab** [comment]
You might still be able to do `brew update-python-resources`; you'll just need to copy over the changes to your local homebrew-core repo. You may also wish to experiment with `HOMEBREW_FORCE_HOMEBREW_ON_LINUX` (see `man brew`), but I don't really work on Linux much so I'll admit to not really knowing how this works exactly.

I do know it's what we use on our CI nodes for homebrew/core that still run on Linux.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
