### PR TITLE
pup 0.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
- upstream now uses the vendor directory
- clean up the formula

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like all the resources except perhaps `gox` & its dependencies are safe to snip. Upstream introduced `/vendor`.

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
Test should be using `#{bin}/pup` but otherwise seems reasonable 👍.

**Comment by ilovezfs** [comment]
@DomT4 fixed.

**Comment by DomT4** [comment]
LGTM

**Pull request closed without merging**
