### PR TITLE
fq 0.10.8

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
See
https://github.com/Homebrew/homebrew-core/pull/17821
https://github.com/circonus-labs/fq/issues/27

**Comment by JCount** [comment]
@stale[bot] shoo

**Comment by ilovezfs** [comment]
minimal fix is
```
diff --git a/Makefile b/Makefile
index 0dcef6b..09cd544 100644
--- a/Makefile
+++ b/Makefile
@@ -134,7 +134,7 @@ fqc:        $(FQC_OBJ)
        $(Q)$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(FQC_OBJ) $(LIBS)
 
 fq-sample.so:  $(FQD_SAMPLE_OBJ)
-       $(Q)$(MODULELD) $(EXTRA_SHLDFLAGS) $(SHLDFLAGS) -o $@ $(FQD_SAMPLE_OBJ)
+       $(Q)$(MODULELD) $(EXTRA_SHLDFLAGS) $(SHLDFLAGS) -o $@ $(FQD_SAMPLE_OBJ) $(CLIENT_OBJ_LO)
 
 fq_sndr:       fq_sndr.o libfq.a
        @echo " - linking $@"
```
though I don't if it's "correct" https://github.com/circonus-labs/fq/issues/27#issuecomment-343671402

**Comment by ilovezfs** [comment]
0.10.8

**Pull request closed without merging**
