### PR TITLE
zbar 0.23.91

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
It's marked on GitHub as latest release but looks like an abrupt shift in version number - can we check with upstream to verify that this is actually supposed to be a stable release?

**Comment by mchehab** [comment]
It should be OK to use `zbar-0.23.90`, as the main changes from 0.23.1 are bug fixes.

That's said, I'm using `major.minor.9x` for test releases. In this specific case, what I'm testing is to use Github's actions, instead of Travis CI. One of the actions generates a per-OS set of binary files that can only be generated when a new release is trigged. That's due to two reasons:

1. the trigger for such action is `on: release`
2. it depends on the `github.event.release.upload_url`

While I don't see a way to override this limitation, I'll need to generate a couple of releases. So, you may expect some other `0.23.9x` releases soon. Once everything is OK with Github's actions, I'll release version `0.24.0`.

**Comment by SMillerDev** [comment]
You can mark those as pre-release in github. Actions should still trigger but homebrew will know not to use it.

**Comment by mchehab** [comment]
> You can mark those as pre-release in github. Actions should still trigger but homebrew will know not to use it.

Sorry for the Homebrew trigger noise.

I'm new using github actions (started using it last week), but, at least on my tests, `on: release` trigger is not working well. 

For it to be triggered, I needed to create an `on: tag` task that creates a release as not draft/not prerelease. Then, I need to manually delete the tag, re-push it (for the `on: tag` job to run again) and then edit the tag. I suspect that there's a bug somewhere at github's trigger code.

**Comment by SMillerDev** [comment]
We'll just ignore this one and wait for 0.24.0

**Pull request closed without merging**
