### PR TITLE
ocrmypdf: bump to 13.7.0 & migrate to python@3.10

### PR DESCRIPTION
**Pull request by unitof**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by unitof** [comment]
Seems to be same build error as https://github.com/Homebrew/homebrew-core/pull/106648 had

**Comment by unitof** [comment]
```
Successfully installed cffi-1.15.1 pycparser-2.21 semantic-version-2.10.0 setuptools-63.3.0 setuptools-rust-1.4.1 typing-extensions-4.3.0 wheel-0.37.1
[1168](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1169)
    WARNING: There was an error checking the latest version of pip.
[1169](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1170)
    Installing build dependencies: finished with status 'done'
[1170](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1171)
    Getting requirements to build wheel: started
[1171](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1172)
    Running command Getting requirements to build wheel
[1172](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1173)
  
[1173](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1174)
            =============================DEBUG ASSISTANCE==========================
[1174](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1175)
            If you are seeing an error here please try the following to
[1175](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1176)
            successfully install cryptography:
[1176](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1177)
  
[1177](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1178)
            Upgrade to the latest pip and try again. This will fix errors for most
[1178](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1179)
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
[1179](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1180)
            =============================DEBUG ASSISTANCE==========================
[1180](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1181)
  
[1181](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1182)
    Traceback (most recent call last):
[1182](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1183)
      File "/opt/homebrew/Cellar/ocrmypdf/13.7.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
[1183](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1184)
        main()
[1184](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1185)
      File "/opt/homebrew/Cellar/ocrmypdf/13.7.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
[1185](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1186)
        json_out['return_val'] = hook(**hook_input['kwargs'])
[1186](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1187)
      File "/opt/homebrew/Cellar/ocrmypdf/13.7.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
[1187](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1188)
        return hook(config_settings)
[1188](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1189)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
[1189](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1190)
        return self._get_build_requires(
[1190](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1191)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
[1191](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1192)
        self.run_setup()
[1192](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1193)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
[1193](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1194)
        exec(compile(code, __file__, 'exec'), locals())
[1194](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1195)
      File "setup.py", line 14, in <module>
[1195](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1196)
        from setuptools_rust import RustExtension
[1196](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1197)
      File "/private/tmp/pip-build-env-0d_6ubew/overlay/lib/python3.9/site-packages/setuptools_rust/__init__.py", line 1, in <module>
[1197](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1198)
        from .build import build_rust
[1198](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1199)
      File "/private/tmp/pip-build-env-0d_6ubew/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 20, in <module>
[1199](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1200)
        from setuptools.command.build import build as CommandBuild  # type: ignore[import]
[1200](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1201)
    ModuleNotFoundError: No module named 'setuptools.command.build'
[1201](https://github.com/Homebrew/homebrew-core/runs/7621646199?check_suite_focus=true#step:6:1202)
    error: subprocess-exited-with-error
```

Any way to update the `pip` used to build? Happy for help from anyone else! Out of my depth here in python packageland.

**Comment by carlocab** [comment]
`setuptools` in `python@3.9` needs updating.

**Comment by cho-m** [comment]
Alternatively, can you try switching to `python@3.10`? I think the dependency tree is ready now.

**Comment by unitof** [comment]
`python@3.10` worked locally! (on M1 Mac)

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
