### PR TITLE
netcdf 4.7.1

### PR DESCRIPTION
**Pull request by luzpaz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@luzpaz any update on this PR?

**Comment by luzpaz** [comment]
Sorry, ran out of steam trying to fix the issue here.

**Comment by Bo98** [comment]
We'll relook at this after Python 3.8 (#45337) is merged, which affects a number of the the formula changed here.

**Comment by luzpaz** [comment]
bump due to https://github.com/Homebrew/homebrew-core/pull/44233#issuecomment-570271616

**Comment by SMillerDev** [comment]
If you are just going to bump it instead of fixing the build failure I better close this now. Stalebot is here for a reason

**Comment by luzpaz** [comment]
Closing as I do not have ability ATM to fix this

**Pull request closed without merging**
