### PR TITLE
Rust version 1.13

### PR DESCRIPTION
**Pull request by mrageh**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `rust 1.13.0`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Comment by ilovezfs** [comment]
Um, I think 1.13.0 is still the beta version: https://www.rust-lang.org/en-US/downloads.html

Revert?

**Comment by MikeMcQuaid** [comment]
Argh. @ilovezfs Given stable release is forecast for today, maybe wait for it? I wonder if there's a way of checking with audit for stable/beta release? Two digits vs three?

**Comment by ilovezfs** [comment]
They don't tag until it's stable. So I noticed this had happened because
```
$ brew livecheck rust
rust (guessed) : 1.13.0 ==> 1.12.1
```

**Comment by mrageh** [comment]
My mistake @MikeMcQuaid and @ilovezfs I thought it was stable 😞

**Comment by ilovezfs** [comment]
@mrageh don't worry. I'm sure it will be soon :)

**Comment by ilovezfs** [comment]
It's been designated stable now, tagged, and the checksum has not changed, so we're :white_check_mark: 

Thanks again @mrageh

**Comment by MikeMcQuaid** [comment]
😅

**Pull request closed without merging**
