### PR TITLE
xmake: 2.7.4

### PR DESCRIPTION
**Pull request by waruqi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> ./configure checking for platform ... linux
checking for architecture ... x86_64
checking for make ... ok 
unknown tool gcc-11
```

Why do you need to run configure now, as it was not necessary before ?

**Comment by waruqi** [comment]
> ```
> ==> ./configure checking for platform ... linux
> checking for architecture ... x86_64
> checking for make ... ok 
> unknown tool gcc-11
> ```
> 
> Why do you need to run configure now, as it was not necessary before ?

We are going to switch to new build system (https://github.com/xmake-io/xmake.sh) and remove old makefiles.

```
./configure
make
```

**Comment by waruqi** [comment]
I added a patch to fix it and I will remove this patch in next release.

**Review by iMichka — APPROVED** [review]
Thanks!

**Pull request closed without merging**
