### PR TITLE
llvm: fix build on >= El Capitan

### PR DESCRIPTION
**Pull request by EtherTyper**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

See homebrew/homebrew-versions#1310 and homebrew/homebrew-versions#1315.

### CODE REVIEW

**Comment by DomT4** [comment]
Can you expand on why this is a problem? Is this an upstream problem or something exclusive to Homebrew?

**Comment by EtherTyper** [comment]
Upstream, which is why I submitted http://reviews.llvm.org/D22200, but @MikeMcQuaid suggested that I submit patches to the Homebrew maintainers, anyways.

**Comment by EtherTyper** [comment]
@DomT4 On second thought, I think he meant just for prebuilt **releases**. Sorry about that.

**Comment by DomT4** [comment]
This seems reasonable enough, if it's a problem that impacts the `llvm` formula here as well. The upstream report was the important thing; unlike a lot of package managers we don't like to carry patches indefinitely so we attempt to get stuff fixed upstream fairly proactively.

I notice we're only patching the test here, not sure if you meant to apply the patch to the whole package instead?

**Comment by EtherTyper** [comment]
@DomT4 Thanks for the catch! So should I keep it open for the time being?

**Comment by EtherTyper** [comment]
That was an accident.

**Comment by DomT4** [comment]
Sure! Is the problem here building against Xcode 8 or is it broader than that?

**Comment by EtherTyper** [comment]
Well, I believe from searching through bug reports of the same thing, like Homebrew/homebrew-versions#1298, it happens to El Capitan users as well as regular users. I guess not many of them have reported their `xcodebuild` versions, so I have no idea.

**Comment by maxim-belkin** [comment]
Looks like upstream replied and is waiting for your feedback. Can you follow up with them first?
It might be that it is not `include/string` but some other file that has to be fixed (e.g. definition of `_LIBCPP_STD_VER` in `include/__config`?, or maybe we have to use `-std=c++14` (instead of `-std=c++11`) so that `LIBCPP_STD_VER` is set correctly...) Also, I built llvm 3.8.x formula on two El Capitan machines so this problem is probably not related to the version of OS X but something else.

**Comment by RandomDSdevel** [comment]
@maxim-belkin:  From what I can tell from the conversation here, the issue reported here arises when you have _both_ OS X 10.11.x El Capitan _and_ an Xcode 8 beta installed.

**Comment by mchenja** [comment]
@RandomDSdevel - I had this same problem, but as far as I'm aware I don't have the Xcode 8 beta installed. When I get to work I can post my OS X version and Xcode version; is there any other information you think would be helpful to resolve the issue?

**Comment by RandomDSdevel** [comment]
@mchenja:  Other than following the steps outlined in `$(brew --repository)/brew/share/doc/homebrew/Troubleshooting.md` ([here](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)'s a GitHub copy,) nothing that I can think of off of the top of my head, though you might want to ask @DomT4 whether or not it might be better for you to report your problems in a new issue.

**Comment by EtherTyper** [comment]
@RandomDSdevel I am running Xcode 8, macOS Sierra beta 5 for the purposes of my encounter with this issue.

**Comment by mchenja** [comment]
@RandomDSdevel - thanks for the message; truth be told I'm not sure I'm really qualified to raise an issue since I hardly ever use llvm, but I can post my machine details here just to conclude my thread:

from `$ brew config`:
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 97a66aa513f515472b3c36256f4624060d5e365c
Last commit: 16 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b163b0d8271500557664422d6fdc3054d0ff7d31
Core tap last commit: 20 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: 1.8.0_92
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A

`$ brew doctor` reports no issues.

**Comment by RandomDSdevel** [comment]
@mchenja:  You _do_ know I meant a new _Homebrew_ issue, right…?

**Comment by RandomDSdevel** [comment]
@EtherTyper:  OK, but I'm not sure @maxim-belkin caught that, which is why I posted the clarification.

**Comment by maxim-belkin** [comment]
My first attempt to build llvm on macOS Sierra with XCode-beta [succeeded](https://gist.github.com/94ac2a71d7a7c4e7bbadb71a587f02e0).

**Comment by maxim-belkin** [comment]
Second build finished [successfully](https://gist.github.com/8cd6cd4cf4739d8211b78bcbb72d94b7).
// Used option: --with-all-targets

**Comment by maxim-belkin** [comment]
Third build finished [successfully](https://gist.github.com/8df220f6180bc3fa92d34cf6cb53665d)
//Used options: --with-graphviz --universal

**Comment by maxim-belkin** [comment]
Fourth build finished [successfully](https://gist.github.com/3cfab2d7aed6ff580c83b741d06fd0e1)
 // Used options: --with-shared-libs --with-python

**Comment by maxim-belkin** [comment]
So, what combination of build options leads to a failure?
And, if `llvm` build failed, was `--with-lldb` option used? Were the guidelines from [here](https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt) followed?

**Comment by RandomDSdevel** [comment]
@maxim-belkin:  As I recall, we've had problems with building LLDB before; see [Legacy Homebrew](https://github.com/Homebrew/legacy-homebrew) [Issue #39621:  '`brew install llvm --with-python --with-lldb --with-clang` fails'](https://github.com/Homebrew/legacy-homebrew/issues/39621), [Issue #42041:  'llvm --with-clang --with-lldb fails to build'](https://github.com/Homebrew/legacy-homebrew/issues/42041), and possibly some other issues there for more details.

**Comment by maxim-belkin** [comment]
I have just [successfully built](https://gist.github.com/8826a87c338347c4fde6ca17fef8e677) `llvm` with the `--with-lldb` option.
So, we need more details from those for whom it fails.

**Comment by RandomDSdevel** [comment]
@maxim-belkin:  I tried building LLVM `--with-lldb` a couple of times recently, and (for me, at least,) it kept failing when I passed the `llvm` formula the `--with-all-targets`, `--with-graphviz`, `--with-libcxxabi`, `--with-ocaml`, `--with-python`, `--with-test`, and `--with-toolchain` options all at once along with `--with-lldb`, so maybe it's one or more of those options that's causing the build problems…?

**Comment by Hywan** [comment]
Might related to https://github.com/Homebrew/homebrew-core/issues/3030.

**Comment by RandomDSdevel** [comment]
@Hywan:  Nope, I'm still on Xcode 7.3.1.

**Comment by MikeMcQuaid** [comment]
This doesn't seem to be a reproducible failure so passing on it for now.

**Pull request closed without merging**
