### PR TITLE
rust-analyzer 06-08

### PR DESCRIPTION
**Pull request by atetubou**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by issyl0 — CHANGES_REQUESTED** [review]
Thanks for your first contribution to Homebrew, @atetubou! The test is failing on CI, though. You can try debugging this yourself with:

```
cd $(brew --repo homebrew/core)
git checkout rust-analyzer-06-08
brew install --build-from-source rust-analyzer
brew test --verbose rust-analyzer
brew edit rust-analyzer # repeat these last two steps until the test works
```

Good luck!

**Comment by atetubou** [comment]
I fixed the test, take a look again?

**Comment by atetubou** [comment]
bump

**Review by SMillerDev — APPROVED** [review]
Thanks @atetubou  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by atetubou** [comment]
@SMillerDev thank you for approval. So can this pr be merged? Or do I need to wait approval from @issyl0 too?

**Review by issyl0 — APPROVED** [review]
This has my approval now. It should merge automatically within the next hour.

**Pull request closed without merging**
