### PR TITLE
cairomm: use secure homepage

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- add canonical source url

### CODE REVIEW

**Comment by vszakats** [comment]
Should the source package changed to the canonical location? (it's a `.gz` vs. current `.xz`, internal content being the same)

**Comment by apjanke** [comment]
I don't know. Anyone know why it's downloading from this alternate location in the first place?

**Comment by vszakats** [comment]
It was changed in 045dd7ccdb29b6110d93bb1cb9b6b058fcbb3aa9, possibly because the new release was made available on the other URL first, or else.

I'm updating to use the canonical one again.

**Comment by apjanke** [comment]
Sounds reasonable. I've also asked on that commit to see if they can confirm.

Can you verify that the SHA sums for the individual files inside the two archive files are the same? If not, we should probably bump the revision, strictly speaking.

**Comment by vszakats** [comment]
Yes, they do have the exact same set files with the exact same content, verified by `diff` and `shasum -a 256`. Only difference is in directory timestamps - but not content.

**Comment by apjanke** [comment]
Cool. No revision bump necessary then; will merge when green.

**Comment by vszakats** [comment]
Thank you!

**Comment by DomT4** [comment]
Bit of a shame to lose the `.xz` compression but otherwise seems okay.

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Pull request merged**
