### PR TITLE
erlang 21.0, erlang@20 20.3.8 (new formula)

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
All erlang reverse dependencies need to be checked to see if they still build. I'd suggest revision bumping all of them temporarily in the PR and then backing out whichever revision bumps were unneeded in a second run.

**Comment by commitay** [comment]
Thanks!

**Comment by ilovezfs** [comment]
wrangler https://github.com/RefactoringTools/wrangler/issues/87

**Comment by ilovezfs** [comment]
yaws https://github.com/klacke/yaws/issues/338

**Pull request closed without merging**
