### PR TITLE
karn 0.0.4

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
https://github.com/Homebrew/homebrew-core/issues/21801

### CODE REVIEW

**Comment by ilovezfs** [comment]
Hmmm this seems like a bug … do we know why that one isn't in their godep file?

**Comment by DomT4** [comment]
Was removed in https://github.com/prydonius/karn/commit/e67e61d24e18b54eb446d8a82a977e03457aebbf. Seems odd.

**Comment by ilovezfs** [comment]
:bug:

**Comment by DomT4** [comment]
Upstream responded to an unrelated issue a few days ago, so if we file a new one here it might get fixed, despite the lack of recent commits.

**Comment by ilovezfs** [comment]
CAN HAZ https://github.com/urfave/cli PLZ????!!!! MMK, THX :heart:

**Comment by DomT4** [comment]
That would potentially do the trick, yes 😉

**Comment by commitay** [comment]
I'll open an issue to request that the vendor be corrected/updated with a new tag.

**Comment by commitay** [comment]
https://github.com/prydonius/karn/issues/17

**Comment by prydonius** [comment]
Thanks @commitay! This has been fixed in https://github.com/prydonius/karn/pull/19 and I've released a new version (https://github.com/prydonius/karn/releases/tag/v0.0.4).

**Comment by commitay** [comment]
Thanks @prydonius!

**Comment by ilovezfs** [comment]
Thanks @commitay and @prydonius!

**Pull request closed without merging**
