### PR TITLE
mpv 0.34.0

### PR DESCRIPTION
**Pull request by nevack**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nevack** [comment]
```
<unknown>:0: error: fatal error encountered while reading from module 'Foundation'; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
```

```
1.	Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
2.	
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Mandatory Diagnostic Passes + Enabling Optimization Passes } on SIL for macOS_swift.macOS_swift)
4.	While running pass #13001 SILModuleTransform "MandatorySILLinker".
5.	While deserializing SIL function "free"
6.	*** DESERIALIZATION FAILURE ***
module 'Foundation' with full misc version '5.5(5.5)/Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'
top-level value not found
Cross-reference to module 'Darwin'
... free
... with type (UnsafeMutableRawPointer) -> ()
```

**Comment by nevack** [comment]
@carlocab Hi, have you seen this error before?

**Comment by carlocab** [comment]
I've seen similar looking errors in a few other formulae while building bottles for Monterey, but I have no idea what it's about. @Bo98 would know more than I would here.

**Comment by Bo98** [comment]
This is a bug in Xcode 13 fixed in 13.1. I will update the Big Sur runners later today if the queue is quiet.

**Comment by Bo98** [comment]
They shouldn’t be, no. We require a minimum of 13.1 on Monterey.

**Comment by nevack** [comment]
> I will update the Big Sur runners later today if the queue is quiet.

@Bo98 Are they good now?

**Comment by xxyzz** [comment]
The [v0.34.0 release note](https://github.com/mpv-player/mpv/releases/tag/v0.34.0) says "ytdl_hook.lua: search for yt-dlp by default (preferred over youtube-dl)" in "Features -> Added" section. I think `mpv` should depends on `yt-dlp`.

**Comment by carlocab** [comment]
> The [v0.34.0 release note](https://github.com/mpv-player/mpv/releases/tag/v0.34.0) says "ytdl_hook.lua: search for yt-dlp by default (preferred over youtube-dl)" in "Features -> Added" section. I think `mpv` should depends on `yt-dlp`.

That makes sense.

**Comment by nevack** [comment]
> The [v0.34.0 release note](https://github.com/mpv-player/mpv/releases/tag/v0.34.0) says "ytdl_hook.lua: search for yt-dlp by default (preferred over youtube-dl)" in "Features -> Added" section. I think `mpv` should depends on `yt-dlp`.

yt-dlp should be declared instead or along with youtube-dl?

**Comment by carlocab** [comment]
```
==> FAILED
mpv:
  * mpv contains conflicting version recursive dependencies:
      python@3.9, python@3.10
    View these with `brew deps --tree mpv`.
Error: 1 problem in 1 formula detected
```
A bunch of other formulae in the dep tree use `python@3.9` but `yt-dlp` uses `python@3.10`. We can leave a comment here to switch to `yt-dlp` when its dep tree is migrated, or we can add this to the versioned conflict allowlist. I suspect the  conflict is safe.

**Comment by matthewleon** [comment]
> I suspect the conflict is safe.

https://github.com/yt-dlp/yt-dlp#dependencies lists Python 3.6+ as a project dependency. This strongly suggests that the conflict is safe indeed.

**Comment by matthewleon** [comment]
@nevack @SMillerDev any possibility of unsticking this?

**Comment by carlocab** [comment]
> https://github.com/yt-dlp/yt-dlp#dependencies lists Python 3.6+ as a project dependency. This strongly suggests that the conflict is safe indeed.

The worry isn't really whether `yt-dlp` will keep working. It's more an issue for `mpv`.

**Comment by nevack** [comment]
> > https://github.com/yt-dlp/yt-dlp#dependencies lists Python 3.6+ as a project dependency. This strongly suggests that the conflict is safe indeed.
> 
> The worry isn't really whether `yt-dlp` will keep working (which is why the audit complains about `mpv`'s dep tree and not `yt-dlp`'s). It's more an issue for `mpv`.

Added mpv to ignore list, builds are okay

**Comment by SMillerDev** [comment]
But do they actually work?

**Comment by nevack** [comment]
> But do they actually work?

`brew install -s mpv`
`mpv some-youtube-link` 

Opens MPV window with youtube video playing.

**Comment by carlocab** [comment]
Can you try doing something that makes use of `vapoursynth`? That's probably the conflict that might cause issues, if any, since it seems that `vapoursynth` will using Python 3.9 at runtime.

**Comment by nevack** [comment]
> vapoursynth

Personally I don't use it.
Can you provide some usage example and I'll test it and share results.
Thanks!

**Comment by carlocab** [comment]
I don't even use `mpv` at all, so I'll have less luck than you will coming up with a usage example.

**Comment by nevack** [comment]
> I don't even use `mpv` at all, so I'll have less luck than you will coming up with a usage example.

With brewed `mvtools` and https://gist.github.com/phiresky/4bfcfbbd05b3c2ed8645

```
mpv ~/Downloads/native.mkv
 (+) Video --vid=1 (*) (h264 1920x1080 30.000fps)
File tags:
 Artist: Blender Foundation 2008, Janus Bager Kristensen 2013
 Comment: Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
 Composer: Sacha Goedegebure
 Genre: Animation
 Title: Big Buck Bunny, Sunflower version
VO: [libmpv] 1920x1080 yuv420p10
V: 00:00:04 / 00:00:20 (22%) Dropped: 16
Passing more than 1 argument to vf-toggle is deprecated!
V: 00:00:04 / 00:00:20 (22%) Dropped: 16
[autoconvert] Converting yuv420p10 -> yuv420p
Reflowing from 30.0000003 fps to 59.9938 fps (quality=low)
[vapoursynth] Frame requested during init! This is unsupported.
[vapoursynth] Returning black dummy frame with 0 duration.
[vapoursynth] Frame requested during init! This is unsupported.
[vapoursynth] Returning black dummy frame with 0 duration.
V: 00:00:04 / 00:00:20 (22%) Dropped: 16
VO: [libmpv] 1920x1080 yuv420p
V: 00:00:14 / 00:00:20 (72%) Dropped: 475
Passing more than 1 argument to vf-toggle is deprecated!
V: 00:00:14 / 00:00:20 (72%) Dropped: 475
VO: [libmpv] 1920x1080 yuv420p10
V: 00:00:15 / 00:00:20 (78%)
```

**Review by carlocab — APPROVED** [review]
Thanks @nevack!

**Pull request closed without merging**
