### PR TITLE
Update pipx bottled version

### PR DESCRIPTION
**Pull request by pgilad**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
Could you please provide some context for these changes @pgilad

**Comment by pgilad** [comment]
The bottled version sha for catalona is incorrect (sha mismatch)

**Comment by bayandin** [comment]
> The bottled version sha for catalona is incorrect (sha mismatch)

That's not really true:
```
$ curl https://homebrew.bintray.com/bottles/pipx-0.15.1.1_1.catalina.bottle.tar.gz | sha256sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  155k  100  155k    0     0   742k      0 --:--:-- --:--:-- --:--:--  742k
256bf6633c381e01c1ac56db6351497b03e3f5ec0baeba0d9de555c09e76489f  -
```

Do you download it or use already downloaded bottle (what `brew install pipx` says?)
Try to remove cached one and install it again (you can find it by `find $(brew --cache) -name *pipx-0.15.1.1_1.catalina.bottle.tar.gz`)

**Comment by pgilad** [comment]
Ok it works now after removing the cached item, I guess I had an old cache bottle :smile: - thanks for the help 📶

**Pull request closed without merging**
