### PR TITLE
mercurial 4.4

### PR DESCRIPTION
**Pull request by ngoldbaum**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ngoldbaum** [comment]
This broke `git-cinnabar` it seems. I guess that package needs to be updated to support mercurial 4.4.

**Comment by ngoldbaum** [comment]
ping  @zmwangx, since git-cinnabar depends on internals of mercurial via `get-remote-hg`, that means that `git-cinnabar` needs to vendor the copy of mercurial it depends on lest it get broken every time mercurial updates. I've done so here but have never used `git-cinnabar`. Since you added `git-cinnabar` getting some eyes on this would be appreciated.

**Comment by zmwangx** [comment]
IMO the proper way to handle this is to wait for revdeps to catch up. There's already https://github.com/glandium/git-cinnabar/issues/141. If you start vendoring older versions whenever there are breaking API changes, homebrew/core will quickly become an unmaintainable mess. IMO vendoring should be used very carefully as a last resort.

**Comment by ilovezfs** [comment]
Yep, we'll need to wait on a fix from git-cinnabar as @zmwangx said.

**Comment by ngoldbaum** [comment]
Issues like this will continue to happen, since packages like `git-cinnabar` and `git-remote-hg` depend on the internal mercurial python API which can and does change every major release. That's why I vendored mercurial in the `git-remote-hg` formula.

That said, if we do decide not to vendor mercurial in `git-remote-hg`, we'll need @glandium to cut a release with a fix.

**Comment by ilovezfs** [comment]
Whether this or that is private API is between git-cinnabar and mercurial to hash out. We're not going to vendor mercurial just to paper over it.

**Comment by ilovezfs** [comment]
We can probably just delete https://github.com/glandium/git-cinnabar/blob/release/cinnabar/remote_helper.py#L178-L188 since it has a fallback when `elif self._repo.capable('batch'):` is false.

**Comment by ngoldbaum** [comment]
I spoke with @glandium on IRC last night and he said that he can do a release. I'm hoping that will happen quickly. I don't think adding patches to a formula is any more desirable than vendoring a dependency. In fact less so, since vendoring would prevent recurrences of these issues in the future when mercurial does its next major release.

**Comment by ilovezfs** [comment]
@ngoldbaum If you're eager to ship this for some reason, I'm fine with breaking git-cinnabar temporarily. But we're not going to vendor mercurial.

**Comment by ngoldbaum** [comment]
Alright, I'll revert the changes to the `git-cinnabar` recipe.

**Comment by ilovezfs** [comment]
Thanks @ngoldbaum! Shipped.

**Comment by zmwangx** [comment]
I honestly can't quite understand the rush...

> I don't think adding patches to a formula is any more desirable than vendoring a dependency. In fact less so, since vendoring would prevent recurrences of these issues in the future when mercurial does its next major release.

That argument can be used for any breaking API change (private or not), so I don't find it too convincing...

**Comment by ilovezfs** [comment]
@zmwangx I would accept a patch for git-cinnabar :)

In terms of the rush,
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics mercurial
install events in the last 30 days for mercurial
=====================================================================================================
1 | mercurial                                                                      | 21,674 |  99.80%
2 | mercurial --with-custom-python                                                 |     43 |   0.20%
=====================================================================================================
Total                                                                              | 21,717 |    100%
=====================================================================================================
Josephs-MacBook-Pro:~ joe$ brew formula-analytics git-cinnabar
install events in the last 30 days for git-cinnabar
=====================================================================================================
1 | git-cinnabar                                                                       | 20 |  76.92%
2 | git-cinnabar --devel                                                               |  6 |  23.08%
=====================================================================================================
Total                                                                                  | 26 |    100%
=====================================================================================================
Josephs-MacBook-Pro:~ joe$
```
So it's just a greatest good for the greatest number thing :)

**Comment by zmwangx** [comment]
I mean, it's not too exciting: https://www.mercurial-scm.org/wiki/WhatsNew#Mercurial_4.4_.282017-11-01.29

> git-cinnabar ... 20

That seems to be an argument for removing git-cinnabar from core. I submitted it into core to just slim down my personal tap in the first place.

**Comment by ilovezfs** [comment]
It looks like genuinely useful software, so I don't mind keeping it at all.

**Comment by zmwangx** [comment]
Last time I checked it's basically the only mercurial->git bridge that's still alive.

**Comment by ilovezfs** [comment]
Yeah I suspect it will become more popular over time if that remains the case.

**Comment by ilovezfs** [comment]
I've backported the git-cinnabar fixes here: https://github.com/Homebrew/homebrew-core/pull/20614

**Pull request closed without merging**
