### PR TITLE
Change rust dependency to be optional, only if cargo command not found

### PR DESCRIPTION
**Pull request by phatblat**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by gromgit** [comment]
Related issue: https://github.com/Homebrew/homebrew-core/issues/124998.

One respondent speculated that `cargo-nextest` is "version-locked" to the Rust runtime in which it was built. Is this true?

**Comment by SMillerDev** [comment]
We don't do optional dependencies. If it needs rust it should install rust

**Comment by rami3l** [comment]
@SMillerDev `cargo-*` binaries are indeed a bit different.

Indeed, they require `cargo` to use, but this `cargo` being run can either come from `brew install rust`, or come from `rustup` installed via `brew install rustup-init`, or even be some in-development version of `cargo`.

This detail will not matter as long as the `cargo-*` binary in question is available in `$PATH`, and `brew` happens to be a very convenient way to inject them there.

[`cargo-watch`](https://github.com/Homebrew/homebrew-core/blob/17aa4a59969dc7ba12430a84b8b8723ea931a544/Formula/cargo-watch.rb) and [`cargo-udeps`](https://github.com/Homebrew/homebrew-core/blob/17aa4a59969dc7ba12430a84b8b8723ea931a544/Formula/cargo-udeps.rb) demonstrate very well what I personally expect from such formulae.

**Comment by weihanglo** [comment]
For your reference: <https://doc.rust-lang.org/nightly/cargo/reference/external-tools.html#custom-subcommands>

**Review by rami3l — COMMENTED** [review]
I personally think it would be better to maintain the consistency with existing formulae here:
https://github.com/Homebrew/homebrew-core/blob/17aa4a59969dc7ba12430a84b8b8723ea931a544/Formula/cargo-udeps.rb#L19

**Pull request closed without merging**
