### PR TITLE
git-trim 0.3.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/51653

`matches!` macro is part of rust 1.42 release

**Comment by chenrui333** [comment]
With Rust 1.42.0 release, this should be good to go.

**Comment by chenrui333** [comment]
test step failed
```
==> brew test git-trim --verbose
==> FAILED
Testing git-trim
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200326-98259-rtggr.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-trim.rb --verbose
==> git clone https://github.com/foriequal0/git-trim
Cloning into 'git-trim'...
==> git branch brew-test
==> git trim
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

Error: git-trim: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by Remagpie** [comment]
The test failure is fixed in [v0.3.0](https://github.com/foriequal0/git-trim/releases/tag/v0.3.0).
Would you bump the version to 0.3.0 instead of 0.2.5?

**Comment by chenrui333** [comment]
yeah, doing that now.

**Comment by chenrui333** [comment]
Bumped the version and rebased to master.

**Comment by chenrui333** [comment]
passed the test locally.

**Comment by foriequal0** [comment]
@chenrui333 Could you update it to v0.3.1? v0.3.0 has some bugs so I've fixed it.

**Comment by chenrui333** [comment]
@foriequal0 doing that now.

**Comment by chenrui333** [comment]
@foriequal0 done withe the update. :)

**Pull request closed without merging**
