### PR TITLE
ci: use ubuntu-latest

### PR DESCRIPTION
**Pull request by iMichka**
Align CI setup with what has been done in https://github.com/Homebrew/brew/pull/18704
Use ubuntu-latest when the ubuntu version does not matter.
ubuntu-latest is equivalent to 22.04 right now so this does not change anything

Our ubuntu 22.04 docker image is still used (this has not been modified)

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by iMichka** [comment]
Moving to draft, I realised there is some other code here that hard-codes the runner name: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/dispatch-build-bottle.rb#L68

We will have to make a change in brew too. Wondering if there is a way to make this slightly more robust (and not having to look at two different places for that logic).

**Comment by Bo98** [comment]
> We will have to make a change in brew too. Wondering if there is a way to make this slightly more robust (and not having to look at two different places for that logic).

Anything that's strictly Homebrew/core specific should generally live in Homebrew/core.

`brew dispatch-build-bottle` was however generalised enough to work with third-party taps due to the `--tap=` and `--workflow=` arguments.

However `dispatch-build-bottle` doesn't setup a Docker container so it probably shouldn't be changed for the reason of third-party taps.

**Review by carlocab — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by iMichka** [comment]
> > We will have to make a change in brew too. Wondering if there is a way to make this slightly more robust (and not having to look at two different places for that logic).
> 
> Anything that's strictly Homebrew/core specific should generally live in Homebrew/core (like `brew determine-rebottle-runners` is). `brew dispatch-build-bottle` was generalised enough to work with third-party taps due to the `--tap=` and `--workflow=` arguments.
> 
> However `dispatch-build-bottle` doesn't setup a Docker container so it probably shouldn't be changed for the reason of third-party taps. We made container setup Homebrew/core specific and do it within the workflow itself.

Makes sense, thanks for the explanation.

**Comment by iMichka** [comment]
Merging as this got approved. Let's see how this goes.

**Pull request merged**
