### PR TITLE
rsync: patch 4 CVEs

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Going to wait for a release here as those are all very low impact.

**Comment by DomT4** [comment]
Can't say I love the policy, but I've patched locally so the rest is down to you.

**Comment by ilovezfs** [comment]
@DomT4 It's down to upstream to decide when a new version is warranted. We're not responsible for applying every patch someone associates with a CVE number.

**Comment by DomT4** [comment]
Sorry, I wasn't really intending to throw shade at you. You know my position on this is somewhat complex; I tend to think package managers _should_ patch known CVEs but I'm also pretty fed up with upstreams fairly frequently _effectively_ going "well the Linux distros will patch so there's no rush on our end".

**Pull request closed without merging**
