### PR TITLE
Sbromberger/binwalk readd

### PR DESCRIPTION
**Pull request by sbromberger**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

References #5723.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by sbromberger** [comment]
My pleasure - thanks for stepping me through the process. Just curious - what made this PR unmergeable?

**Comment by MikeMcQuaid** [comment]
We don't do a merge for anything that needs a binary package so we can pull the binary package commit at the same time.

**Comment by sbromberger** [comment]
Ah, makes sense, I think :) Anyway - thanks for the assist. Glad I could contribute something (even as minor as it was) back to this great project. I rely on homebrew on a daily basis.

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words @sbromberger ❤️

**Pull request closed without merging**
