### PR TITLE
neovim: remove unnecessary dependency pkg-config

### PR DESCRIPTION
**Pull request by dundargoc**
This PR removes the dependency pkg-config, which is unnecessary.

### CODE REVIEW

**Comment by dundargoc** [comment]
Uh, unsure what more information is needed tbh. I'll try adding a description as well

**Comment by dundargoc** [comment]
Uh, I don't know 	how to write the title/description better. Any pointers?

**Comment by chenrui333** [comment]
> Uh, I don't know how to write the title/description better. Any pointers?

there is a PR template and ideally you should fill the checkbox items

**Comment by dundargoc** [comment]
I used the gh cli like a peasant. I'll just create a new PR

**Comment by dundargoc** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/152384

**Pull request closed without merging**
