### PR TITLE
crystal 1.8.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by ZhongRuoyu — DISMISSED** [review]

**Comment by bcardiff** [comment]
Hi! I noticed that with this PR we lost the arm64 mac os bottles. I don't see any reason why that happen. Do we need to enable that manually some how?

**Comment by ZhongRuoyu** [comment]
Thanks for reporting this @bcardiff -- I will rebuild `crystal` 1.8.1 shortly.

It seems there was some issue with the workflow and the ARM runners were not set up as they should. Any idea, @carlocab?

**Comment by carlocab** [comment]
Yea, it's because of

https://github.com/Homebrew/homebrew-core/blob/b068485a002871e2f63307860e3306b8ff5faff1/Formula/crystal.rb#L47-L49

We should probably get rid of that.

**Comment by ZhongRuoyu** [comment]
👍 on getting rid of `depends_on arch: :x86_64` on Linux, but I can't seem to reproduce `brew determine-test-runners`'s behaviour, somehow:

```console
$ export \
    HOMEBREW_LINUX_RUNNER=ubuntu-22.04 \
    HOMEBREW_LINUX_CLEANUP=false \
    GITHUB_RUN_ID=test \
    GITHUB_RUN_ATTEMPT=test \
    GITHUB_OUTPUT=$PWD/output.txt
$ brew determine-test-runners crystal
$ cat output.txt
runners=[{"name":"Linux","runner":"ubuntu-22.04","container":{"image":"ghcr.io/homebrew/ubuntu22.04:master","options":"--user=linuxbrew -e GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED"},"workdir":"/github/home","timeout":4320,"cleanup":false},{"name":"macOS 13-x86_64","runner":"13-test-test","cleanup":false},{"name":"macOS 13-arm64","runner":"13-arm64-test-test","cleanup":false},{"name":"macOS 12-x86_64","runner":"12-test-test","cleanup":false},{"name":"macOS 12-arm64","runner":"12-arm64-test-test","cleanup":false},{"name":"macOS 11-x86_64","runner":"11-test-test","cleanup":false},{"name":"macOS 11-arm64","runner":"11-arm64","cleanup":true}]
runners_present=true
```

**Comment by carlocab** [comment]
> but I can't seem to reproduce `brew determine-test-runners`'s behaviour

It will reproduce if you run it on Linux.

> It was added in #105805 to fix #105566. Given it's technically only supported on x86_86 Linux (because there is no prebuilt binary release to bootstrap it on aarch64 Linux), do we still want to remove that?

Yes, I don't think #105566 will re-emerge even if we remove it. We also don't really support ARM Linux at the moment anyway.

**Comment by ZhongRuoyu** [comment]
@bcardiff, now that #129230 is merged, `crystal` bottles should be back in place.

**Comment by bcardiff** [comment]
Thanks! That was really fast ⚡️

**Pull request merged**
