### PR TITLE
openssl 1.0.2r

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by scpeters** [comment]
`baresip` failed in the ongoing mojave build:

~~~
15:47:15 ==> brew test --verbose baresip
15:47:18 ==> FAILED
15:47:18 Testing baresip
...
15:47:18 ==> /usr/local/Cellar/baresip/0.5.10/bin/baresip -f /private/tmp/baresip-test-20190226-53175-1nedvq4/.baresip -t
15:47:18 baresip v0.5.10 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
15:47:18 config: creating config template /Users/brew/.baresip/config
15:47:18 [31mconfig: writing /Users/brew/.baresip/config: No such file or directory
15:47:18 [;m[31mmain: configure failed: No such file or directory
15:47:18 [;mua: stop all (forced=1)
15:47:18 Error: baresip: failed
~~~

**Comment by alex** [comment]
That doesn't seem like it'd be caused by this, looks like a pre-existing breakage?

**Comment by gonhidi** [comment]
The `baresip` formula's test can't work as expected because arguments are being ignored by the binary (and even if `~/.baresip/config` exists, the program enters and stays in an interactive mode). Defining`HAVE_GETOPT` for the build process enables option parsing and should allow the check to succeed.

**Comment by fxcoudert** [comment]
The `baresip` failure will be handled as part of #37254. What else is missing here?
@BrewTestBot test this please

**Comment by scpeters** [comment]
The build yesterday didn't finish, but it found the following failures:

* baresip on mojave (addressed by #37254)
* bzt failed on all three
* epic5 failed a linkage test on 10.12 to `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib` (seems unrelated)
* mariadb failed on all three
* md5sha1sum failed during `brew link` because `/usr/local/bin/md5sum` "is a symlink belonging to coreutils"
* osquery failed on 10.13 

~~~
02:48:25 ==> /usr/local/Cellar/osquery/3.3.2_1/bin/osqueryi -L
02:48:25 dyld: BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB has segment 7 which is out of range (0..3) in /usr/local/Cellar/osquery/3.3.2_1/bin/osqueryi
02:48:25 Error: osquery: failed
02:48:25 An exception occurred within a child process:
02:48:25   Test::Unit::AssertionFailedError: <0> expected but was
02:48:25 <nil>.
~~~
* passenger failed on all three
* percona-xtrabackup failed during `brew link` because `/usr/local/lib/plugin/keyring_vault.so` "is a symlink belonging to percona-server"
* php@7.2 failed on 10.13

~~~
03:14:20 ==> /usr/local/Cellar/php@7.2/7.2.15/bin/phpdbg -V
03:14:20 Error: php@7.2: failed
~~~

* podofo failed `brew linkage` on all 3 over `/tmp/podofo-20190105-21864-i7fghe/podofo-0.9.5/build/src/libpodofo.0.9.5.dylib`
* proselint failed on 10.13 

10.13 build failed while building pulledpork

* `brew test pulledpork` failed on 10.12, 10.14 "Can't locate LWP/UserAgent.pm in @INC"

10.12 failed while building pyside

* `brew test restund` failed on 10.14 "error loading configuration: /etc/restund.conf: No such file or directory"
* `brew test streamlink` failed on 10.14 

~~~
03:19:44 ==> /usr/local/Cellar/streamlink/1.0.0/bin/streamlink https://www.youtube.com/watch?v=he2a4xK8ctk 144p -o video.mp4
03:19:44 [cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=he2a4xK8ctk
03:19:44 error: The specified stream(s) '144p' could not be found.
03:19:44        Available streams: audio_mp4, audio_webm, 360p (worst), 720p, 720p60 (best)
03:19:44 Error: streamlink: failed
~~~

~~~
04:15:45 ==> brew linkage --test xrootd
04:15:47 ==> FAILED
04:15:47 Missing libraries:
04:15:47   /tmp/xrootd-20180822-13118-n98jyf/xrootd-4.8.3/build/src/XrdCl/libXrdCl.2.dylib
04:15:47   /tmp/xrootd-20180822-13118-n98jyf/xrootd-4.8.3/build/src/libXrdUtils.2.dylib
~~~

**Comment by gonhidi** [comment]
I don't know if this will amount to much, but with openssl 1.0.2r source-installed from a local formula matching this PR's changes on my macOS 10.14.3, brew source installations and tests of current bzt, mariadb and passenger formulas done in the last hour or so were successful.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by scpeters** [comment]
I've tried adding a conflict between `percona-server` and `percona-xtrabackup` in #38101 since that failed to install for 10.12-10.14

**Pull request closed without merging**
