### PR TITLE
colmap 3.9.1

### PR DESCRIPTION
**Pull request by timsutton**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* Version 3.9 changelog by @ahojnnes in https://github.com/colmap/colmap/pull/2325
* Fully encapsulate freeimage in bitmap library (#2332) by @ahojnnes in https://github.com/colmap/colmap/pull/2334

**Full Changelog**: https://github.com/colmap/colmap/compare/3.9...3.9.1</pre>
</details>

### CODE REVIEW

**Comment by p-linnane** [comment]
Guessing this failure was caused by https://github.com/colmap/colmap/pull/2332. Might need an upstream issue here.

**Comment by timsutton** [comment]
I can't repro the issue on my arm64 Sonoma machine, is it possible to add the 'no fast fail' label so we can confirm whether it's a Linux-only issue?

**Comment by p-linnane** [comment]
Yeah looks like it's just Linux.

**Comment by timsutton** [comment]
There's an upstream PR for this now: https://github.com/colmap/colmap/pull/2338

Confirmed it builds/tests with this patch, I can look to updating this with contents of that next (or waiting at least for it to merge upstream).

**Comment by p-linnane** [comment]
We can work around it for now by adding `patch :DATA` and then at the end of the formula:

```
__END__
diff --git a/src/colmap/image/line.cc b/src/colmap/image/line.cc
index 3637c3dc..33fff7da 100644
--- a/src/colmap/image/line.cc
+++ b/src/colmap/image/line.cc
@@ -27,6 +27,8 @@
 // ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 // POSSIBILITY OF SUCH DAMAGE.
 
+#include <memory>
+
 #include "colmap/image/line.h"
 
 #include "colmap/util/logging.h"
diff --git a/src/colmap/mvs/workspace.h b/src/colmap/mvs/workspace.h
index 73d21b78..6d2c862c 100644
--- a/src/colmap/mvs/workspace.h
+++ b/src/colmap/mvs/workspace.h
@@ -29,6 +29,8 @@
 
 #pragma once
 
+#include <memory>
+
 #include "colmap/mvs/consistency_graph.h"
 #include "colmap/mvs/depth_map.h"
 #include "colmap/mvs/model.h"
```

**Comment by timsutton** [comment]
> We can work around it for now by adding patch :DATA and then at the end of the formula:

Ah right! Forgot about that option already 😅

**Comment by p-linnane** [comment]
If this works, let's add a newline to the end of the file and then this will be good to merge.

**Comment by timsutton** [comment]
> If this works, let's add a newline to the end of the file and then this will be good to merge.

d'oh - I usually check for that but the patch with a trailing space threw me off. This should be good to go now.

**Review by p-linnane — APPROVED** [review]
Thanks for your efforts as always @timsutton!

**Pull request merged**
