### PR TITLE
ghc@9 9.2.4

### PR DESCRIPTION
**Pull request by triallax**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting? (I've been waiting for ages and it's still not done)
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fishtreesugar** [comment]
[the missing of configure script](https://github.com/Homebrew/homebrew-core/pull/101882#discussion_r884392987 ) already fixed, we can use `configure` bundled in tarball instead of generate by ourself

**Comment by mhmdanas** [comment]
@fishtreesugar done, hope I got it right.

**Comment by fishtreesugar** [comment]
@cho-m pls add back ci-long-timeout label

**Comment by cho-m** [comment]
The https://github.com/Homebrew/homebrew-core/labels/CI-long-timeout runners are all occupied. There are only 2 PRs allowed at a time.

There is also the discussion on whether to move `ghc` to 9.0 in #106859, which will require updating `ghc@9` naming/aliases.

**Comment by fishtreesugar** [comment]
@cho-m Thanks, good to know

**Comment by mhmdanas** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/107589.

**Pull request closed without merging**
