### PR TITLE
envoy 1.25.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
squashed the commits.

**Comment by ZhongRuoyu** [comment]
> squashed the commits.

Sorry, I'll remember to do so next time!

**Comment by chenrui333** [comment]
> > squashed the commits.
> 
> Sorry, I'll remember to do so next time!

yeah, that is the tricky part with the `automerge-skip` PRs

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
linux build got time out, was on the brink earlier

**Pull request closed without merging**
