### PR TITLE
killport 0.6.0 (new formula)

### PR DESCRIPTION
**Pull request by jkfran**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@jkfran you need to build the formula from the source code.

**Comment by chenrui333** [comment]
@jkfran Thanks for the PR. This looks like a nice piece of software, but it currently does not meet the notability requirements for inclusion into homebrew-core.

If you wish, you can host this formula in your own tap. Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by jkfran** [comment]
@chenrui333  I think I was too fast to open this PR, but I wanted to get your support. [Killport](https://github.com/jkfran/killport) is now heavily used worldwide. It has 1k stars on GitHub. It was mentioned and upvoted on Hackernews.

If I update my formula to follow the guidelines in a new PR, will the notability still be a problem?

I really appreciate any help you can provide. Thanks.

**Comment by chenrui333** [comment]
> If I update my formula to follow the guidelines in a new PR, will the notability still be a problem?

yeah, we just have notability requirement as part of the process, @jkfran can you file a new PR, happy to accept it.

**Comment by jkfran** [comment]
It looks like someone did it for me: https://github.com/Homebrew/homebrew-core/pull/137423

Thank you so much @chenrui333 !

**Pull request closed without merging**
