### PR TITLE
grakn 0.17.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fppt** [comment]
Hi why was this PR closed? We would like to update to the latest of grakn.

**Comment by ilovezfs** [comment]
@fppt it didn't work and I don't have the time at the moment to investigate it further.

**Comment by fppt** [comment]
We changed the startup scripts and did not accounr for that in `grakn.rb` we will make a manual PR to resolve this. Thanks for the response @ilovezfs

**Comment by ilovezfs** [comment]
@fppt I didn't you realize you're upstream. Specifically, it seemed not to work (as in it would fail to start) unless I chdir'd into the same directory as grakn.

**Pull request closed without merging**
