### PR TITLE
simple-obfs 0.0.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> FAILED
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170321-89821-1p3tq30.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/simple-obfs.rb --build-bottle --verbose
==> Downloading https://github.com/shadowsocks/simple-obfs/archive/v0.0.3.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/simple-obfs-0.0.3.tar.gz
==> Verifying simple-obfs-0.0.3.tar.gz checksum
tar xzf /Users/brew/Library/Caches/Homebrew/simple-obfs-0.0.3.tar.gz
==> ./configure --prefix=/usr/local/Cellar/simple-obfs/0.0.3
Failed to execute: ./configure
```
install method needs to be updated

**Comment by fxcoudert** [comment]
There are bug reports upstream about that, and they advise to run `./autogen.sh` (which will introduce build dependencies on `automake` and `autoconf`).

**Comment by lcdtyph** [comment]
Hello.
How can I add commit to this pr directly?
I'm not quite familiar github...

**Comment by fxcoudert** [comment]
You can open a new PR from your own branch.

**Comment by JCount** [comment]
🍁

**Pull request closed without merging**
