### PR TITLE
glassfish 5.0

### PR DESCRIPTION
**Pull request by adruiza**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Is `depends_on :java => "1.7+"` still correct?

**Comment by haidran** [comment]
Nope, just checked, sorry. Depends on Java 1.8+. Editing

**Comment by ilovezfs** [comment]
`brew cask install caskroom/versions/java8` should satisfy the requirement.

**Comment by ilovezfs** [comment]
Sorry meant to post that elsewhere.

**Comment by ilovezfs** [comment]
Thanks @haidran! Shipped :sparkler:

**Pull request merged**
