### PR TITLE
postgresql family security releases.

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes multiple CVEs. If you have an existing database that you don't intend to blow away & regenerate you may wish to read: https://www.postgresql.org/about/news/1772/

### CODE REVIEW

**Comment by ilovezfs** [comment]
libpq needs to be upgraded too.

**Comment by DomT4** [comment]
Ah, didn't even know that was a formula yet 😉. Give me just a second.

**Comment by ilovezfs** [comment]
:face_with_head_bandage:

**Comment by DomT4** [comment]
I feel like a whole bunch of CVEs for major projects got fixed over the last couple days. Here's hoping for a quieter weekend on the security front 😅.

**Pull request closed without merging**
