### PR TITLE
ocaml 4.04.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by apjanke** [comment]
Looks like a couple dependents just need revision bumps.

`brew test ocamlsdl4` failure:

```
==> /usr/local/opt/ocaml/bin/ocamlopt -I +sdl sdl.cmxa -cclib -lSDLmain -cclib -lSDL -cclib -Wl,-framework,Cocoa -o test test.ml
File "test.ml", line 1:
Error: /usr/local/lib/ocaml/sdl/sdl.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
Error: ocamlsdl: failed
Failed executing: /usr/local/opt/ocaml/bin/ocamlopt -I +sdl sdl.cmxa -cclib -lSDLmain -cclib -lSDL -cclib -Wl,-framework,Cocoa -o test test.ml
```

`brew test lablgtk` failure:

```
==> ocamlc -I /usr/local/opt/lablgtk/lib/ocaml/lablgtk2 lablgtk.cma gtkInit.cmo test.ml -o test -cclib -latk-1.0 -cclib -lcairo -cclib -lgdk-quartz-2.0 -cclib -lgdk_pixbuf-2.0 -cclib -lgio-2.0 -cclib -lglib-2.0 -cclib -lgobject-2.0 -cclib -lgtk-quartz-2.0 -cclib -lgtksourceview-2.0 -cclib -lintl -cclib -lpango-1.0 -cclib -lpangocairo-1.0
File "test.ml", line 1:
Error: /usr/local/opt/lablgtk/lib/ocaml/lablgtk2/gtkMain.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
Error: lablgtk: failed
Failed executing: ocamlc -I /usr/local/opt/lablgtk/lib/ocaml/lablgtk2 lablgtk.cma gtkInit.cmo test.ml -o test -cclib -latk-1.0 -cclib -lcairo -cclib -lgdk-quartz-2.0 -cclib -lgdk_pixbuf-2.0 -cclib -lgio-2.0 -cclib -lglib-2.0 -cclib -lgobject-2.0 -cclib -lgtk-quartz-2.0 -cclib -lgtksourceview-2.0 -cclib -lintl -cclib -lpango-1.0 -cclib -lpangocairo-1.0
```

**Comment by ilovezfs** [comment]
@apjanke, no, there's more significant breakage in other dependents. I'll update the PR with the info I've gathered so far when I have a chance.

**Comment by ilovezfs** [comment]
@apjanke OK, as promised, findings are below. TL;DR: camlp5 needs to be fixed.

ocamlbuild: needs revision bump

lablgtk: needs new version 2.18.5

ocamlsdl: needs revision bump

flow: fixed upstream in https://github.com/facebook/flow/commit/2edc61986ec7db0dcebccd032198f70b176222ee

zero-install: needs revision bump and resource versions bumped

homebrew/versions/unison240 is already broken

camlp5: broken
  https://groups.google.com/forum/#!topic/ocaml-aggregation-list/e-O_IYOTA7s

coq: builds if switched over to use the new camlp4 (until camlp5 is fixed, or permanently)

fstar: needs batteries bumped to batteries=2.5.3

ledit: broken because camlp5 is broken

ssreflect: broken since it needs camlp5 to build coq 8.4, but newer mathcomp may make that unnecessary since coq (8.5 above) builds with the new camlp4, but the ssreflect -> mathcomp upgrade is non-trivial

**Comment by ilovezfs** [comment]
@apjanke :rocket: camlp5 upstream came through for us after an email :)

**Comment by apjanke** [comment]
Nice!

**Comment by ilovezfs** [comment]
I should have included menhir as well: https://github.com/Homebrew/homebrew-core/pull/8297

**Pull request closed without merging**
