### PR TITLE
dnsviz 0.8.2

### PR DESCRIPTION
**Pull request by cdeccio**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
Resource `m2crypto` needs to be updated.

**Comment by cdeccio** [comment]
> Resource `m2crypto` needs to be updated.

Updating a dependency is a requirement for a patch-level update to a package?

**Comment by cdeccio** [comment]
I'm happy to make the change, but it just doesn't seem like that's the right thing for semantic versioning.

**Comment by Moisan** [comment]
Thank you for PR @cdeccio! 

Regarding the resource update, every time a Formula version is updated, we make sure the resource are up-to-date as well.

**Pull request closed without merging**
