### PR TITLE
uutils-coreutils 0.0.1.1

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
See also https://github.com/Homebrew/homebrew-core/pull/55987

**Comment by bayandin** [comment]
```
The manual pages are in _build/man.
make[1]: Leaving directory '/private/tmp/uutils-coreutils-20201210-68163-74pgfj/coreutils-0.0.1.1/docs'
    Updating git repository `https://github.com/uutils/uucore.git`
    Updating git repository `https://github.com/uutils/uucore.git`
error: failed to get `uucore` as a dependency of package `uu_arch v0.0.1 (/private/tmp/uutils-coreutils-20201210-68163-74pgfj/coreutils-0.0.1.1/src/uu/arch)`

Caused by:
  failed to load source for dependency `uucore`

Caused by:
  Unable to update https://github.com/uutils/uucore.git?branch=canary#9ada3336

Caused by:
  object not found - no match for id (9ada33368f1b8bfa3b39135a4a73c2b17d385b5f); class=Odb (9); code=NotFound (-3)
```

It looks like the patch has helped with an error from the previous attempt, but one of the dependency has changed. 
I would wait for the next release instead of continuing patching this one.

**Comment by carlocab** [comment]
Yes, upstream seems to have a bad habit of pulling the proverbial dependency rug out from under their tagged releases.

Don't think I'll keep patching it, but I'll leave the PR open for now to keep the build errors visible. Unless you think it's better I closed it?

**Comment by bayandin** [comment]
Closed PR will be searchable as well, so If you're not going to work on it, I would close it to not to distract maintainers.

**Pull request closed without merging**
