### PR TITLE
git-annex: try to fix the build on ARM

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Let's see if this one works.

### CODE REVIEW

**Comment by carlocab** [comment]
Nope. Even upping the verbosity of the logs just gives
```
ghc: could not execute: llc
/opt/homebrew/opt/ghc/bin/ghc returned ExitFailure 1
```

**Comment by cho-m** [comment]
If I try locally, I can build `git-annex` without any changes. Not sure if there is something in my local shell environment or something missing from CI runner environment:
```console
❯ file /opt/homebrew/opt/git-annex/bin/git-annex
/opt/homebrew/opt/git-annex/bin/git-annex: Mach-O 64-bit executable arm64

❯ brew audit --strict git-annex

❯ brew test git-annex
==> Testing git-annex
==> git init
==> git annex init
==> git annex add .
==> git commit -a -m Initial Commit
==> git annex version | grep 'remote types:'
==> git rm Hello.txt -f
==> git commit -a -m Farewell!
==> git annex unused
==> git annex dropunused 1 --force
==> git annex uninit
```

**Comment by carlocab** [comment]
Yes, a user reported having successfully been able to build this on their M1 machine. No idea why it's not working in CI.

**Comment by tarsius** [comment]
I got a different error than before with these commits:

```
==> cabal v2-install --jobs=8 --max-backjumps=100000 --install-method=copy --installdir=/opt/homebrew/Cellar/git-annex/10.20220127/bi
Last 15 lines from /Users/jonas/Library/Logs/Homebrew/git-annex/02.cabal:
[497 of 675] Compiling Command.ResolveMerge ( Command/ResolveMerge.hs, dist/build/git-annex/git-annex-tmp/Command/ResolveMerge.o, dist/build/git-annex/git-annex-tmp/Command/ResolveMerge.dyn_o )
[498 of 675] Compiling Command.Required ( Command/Required.hs, dist/build/git-annex/git-annex-tmp/Command/Required.o, dist/build/git-annex/git-annex-tmp/Command/Required.dyn_o )
[499 of 675] Compiling Command.Repair   ( Command/Repair.hs, dist/build/git-annex/git-annex-tmp/Command/Repair.o, dist/build/git-annex/git-annex-tmp/Command/Repair.dyn_o )
[500 of 675] Compiling Command.RenameRemote ( Command/RenameRemote.hs, dist/build/git-annex/git-annex-tmp/Command/RenameRemote.o, dist/build/git-annex/git-annex-tmp/Command/RenameRemote.dyn_o )
[501 of 675] Compiling Command.RemoteDaemon ( Command/RemoteDaemon.hs, dist/build/git-annex/git-annex-tmp/Command/RemoteDaemon.o, dist/build/git-annex/git-annex-tmp/Command/RemoteDaemon.dyn_o )
[502 of 675] Compiling Command.Reinject ( Command/Reinject.hs, dist/build/git-annex/git-annex-tmp/Command/Reinject.o, dist/build/git-annex/git-annex-tmp/Command/Reinject.dyn_o )

<no location info>: error:
    Error running clang! you need clang installed to use the LLVM backend
    (or GHC tried to execute clang incorrectly)
clang: runInteractiveProcess: posix_spawnp: already exists (File exists)
/opt/homebrew/opt/ghc/bin/ghc returned ExitFailure 1

cabal: Failed to build gt-nnx-10.20220127-e5b994bd.
```

Then I installed `llvm` and set all the variables that brew then suggested. After that I get this again:

```
==> cabal v2-install --jobs=8 --max-backjumps=100000 --install-method=copy --installdir=/opt/homebrew/Cellar/git-annex/10.20220127/bi
Last 15 lines from /Users/jonas/Library/Logs/Homebrew/git-annex/02.cabal:
[507 of 675] Compiling Command.Proxy    ( Command/Proxy.hs, dist/build/git-annex/git-annex-tmp/Command/Proxy.o, dist/build/git-annex/git-annex-tmp/Command/Proxy.dyn_o )
[508 of 675] Compiling Command.P2P      ( Command/P2P.hs, dist/build/git-annex/git-annex-tmp/Command/P2P.o, dist/build/git-annex/git-annex-tmp/Command/P2P.dyn_o )
[509 of 675] Compiling Command.NumCopies ( Command/NumCopies.hs, dist/build/git-annex/git-annex-tmp/Command/NumCopies.o, dist/build/git-annex/git-annex-tmp/Command/NumCopies.dyn_o )
[510 of 675] Compiling Command.NotifyChanges ( Command/NotifyChanges.hs, dist/build/git-annex/git-annex-tmp/Command/NotifyChanges.o, dist/build/git-annex/git-annex-tmp/Command/NotifyChanges.dyn_o )
[511 of 675] Compiling Command.Multicast ( Command/Multicast.hs, dist/build/git-annex/git-annex-tmp/Command/Multicast.o, dist/build/git-annex/git-annex-tmp/Command/Multicast.dyn_o )
[512 of 675] Compiling Command.MinCopies ( Command/MinCopies.hs, dist/build/git-annex/git-annex-tmp/Command/MinCopies.o, dist/build/git-annex/git-annex-tmp/Command/MinCopies.dyn_o )
[513 of 675] Compiling Command.MetaData ( Command/MetaData.hs, dist/build/git-annex/git-annex-tmp/Command/MetaData.o, dist/build/git-annex/git-annex-tmp/Command/MetaData.dyn_o )
[514 of 675] Compiling Command.MatchExpression ( Command/MatchExpression.hs, dist/build/git-annex/git-annex-tmp/Command/MatchExpression.o, dist/build/git-annex/git-annex-tmp/Command/MatchExpression.dyn_o )
[515 of 675] Compiling Command.Map      ( Command/Map.hs, dist/build/git-annex/git-annex-tmp/Command/Map.o, dist/build/git-annex/git-annex-tmp/Command/Map.dyn_o )
[516 of 675] Compiling Command.LookupKey ( Command/LookupKey.hs, dist/build/git-annex/git-annex-tmp/Command/LookupKey.o, dist/build/git-annex/git-annex-tmp/Command/LookupKey.dyn_o )
ghc: could not execute: opt
/opt/homebrew/opt/ghc/bin/ghc returned ExitFailure 1

cabal: Failed to build gt-nnx-10.20220127-e5b994bd.
```

**Comment by carlocab** [comment]
No idea how to progress on this, so I'm closing this. If someone wants to pick this up, you can open a new PR.

**Comment by tarsius** [comment]
I succeeded in building `git-annex` manually.

The problem I had to overcome is that `--extra-include-dirs` and `--extra-lib-dirs` only affect building "local packages" but not building dependencies. There's an open tread in the `cabal` repository about that. It's open since 2015, so I don't expect any useful changes to be merged any time soon.

[This](https://github.com/haskell/cabal/issues/2997#issuecomment-609608367) post from that thread explains how to work around the issue, add this to `cabal.project.local` at the top of the repository.

```
package *
  extra-include-dirs: /usr/local/opt/openssl/include
  extra-lib-dirs: /usr/local/opt/openssl/lib
```

(Of course adjust the paths; I am on Linux right now and most of the time, and have only ever used `brew` to install a single package so far (and failed to install a second) and therefore don't have internalized the Homebrew paths yet. I also don't know Ruby, so I cannot help making the necessary changes here.)

**Pull request closed without merging**
