### PR TITLE
terraforming 0.17.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by Moisan** [comment]
Test fails with error due to resources version. Many resources need to be updated.

**Comment by chenrui333** [comment]
@Moisan  Thanks for pointing out the issues, I have updated the dependencies. Let's see how it goes.

**Comment by Moisan** [comment]
A few more resources need to be updated such as `aws-sdk-elasticache` and `aws-sdk-elasticloadbalancing`. Our policy is to update the resources to their latest version when a formula version is bumped (unless the formula needs a specific resource version). Could you go trough the other resources?

**Comment by chenrui333** [comment]
Sure, I can do it right now.

**Comment by chenrui333** [comment]
@Moisan just updated all the dependencies to the latest.

**Comment by chenrui333** [comment]
Looks like we run into this issue, any reference that I can take to help with the `terraforming.gemspec`?
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'multi_json' (~> 1.12.1) - did find: [multi_json-1.13.1] (Gem::LoadError)
```

**Comment by chenrui333** [comment]
For now, I will just revert the `multi_json ` dependency.

**Comment by chenrui333** [comment]
Let's see how the new build goes.

**Comment by chenrui333** [comment]
@Moisan build issue got sorted out, please verify at your end.

**Comment by chenrui333** [comment]
@fxcoudert Can I get a merge on this?

**Comment by Moisan** [comment]
This looks good. Could you squash your commits in one commit please ?

**Comment by fxcoudert** [comment]
@Moisan I think you forgot to squash upon merging here :)

**Pull request closed without merging**
