### PR TITLE
neofetch 3.3.0

### PR DESCRIPTION
**Pull request by iandrewt**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Install failure:
```
Error: inreplace failed
Makefile:
  expected replacement of "$(DESTDIR)/etc" with "$(DESTDIR)$(SYSCONFDIR)"
```
So it looks like `def install` needs to be changed.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
The new Makefile is using `$(SYSCONFDIR)` now, so that `inreplace` line can probably just be removed.

**Comment by ilovezfs** [comment]
Thanks @iandrewt!

**Pull request closed without merging**
