### PR TITLE
openssl@1.1 1.1.1d

### PR DESCRIPTION
**Pull request by reaperhulk**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you put back the mirrors?

**Comment by reaperhulk** [comment]
Sure I can re-add them. Incidentally, `brew bump-formula-pr` is what deleted them here.

**Comment by fxcoudert** [comment]
Release is currently only half-announced: https://mta.openssl.org/pipermail/openssl-announce/2019-September/000157.html
We'll wait until it's all official to roll out…

**Comment by reaperhulk** [comment]
This release is officially out now.

**Pull request closed without merging**
