### PR TITLE
pieces 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by connor-oleary-pieces**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Mostly doing this for feedback/help, as this is my first time committing to homebrew-core or any public repo.

Pieces CLI is a command line interface version of an app that my company has built (https://code.pieces.app). It is built purely in Dart, so we compiled the binaries on our end and then serve them via GCP Cloud Storage.

In reading the docs for Formula, it says that anything in this core repo should be built from source instead of a binary, and if it is a binary, it should be PR'd into the cask repo. However the cask repo says that anything that is open-source and CLI only should be PR'd into here. Just looking for help on where exactly this should go, or if it should remain a Tap like it is currently.

Thanks!

### CODE REVIEW

**Comment by SMillerDev** [comment]
It should definitely be in homebrew/core. But it must be build from source.

**Comment by connor-oleary-pieces** [comment]
> It should definitely be in homebrew/core. But it must be build from source.

Thanks for the quick reply! So since this is built in Dart, I don't believe the homebrew compiler supports compiling Dart into binaries. Does this mean that this has to remain as a Tap or is there a different route we can take?

**Comment by SMillerDev** [comment]
You can add a dart compiler to homebrew.

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/103222 would add the dart SDK

**Pull request closed without merging**
