### PR TITLE
glib 2.66.7

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
I think the test failures might be related to the 10.14 SDK fix (ironically). cc @Bo98

**Comment by Bo98** [comment]
`gcc` is very, very picky. It needs to be - at compile time of `gcc` itself, it produces a bunch of "include fixes" against the SDK it is building against.

`gcc` was likely built against the 10.15 SDK while the VMs were broken - it needs to be revision bumped to build against the fixed SDK.

**Comment by carlocab** [comment]
Ok, I'll give `matplotplusplus` a revision bump. Not sure if we should do the same for `gcc` yet, perhaps the fix referenced in #70096 should be included in the next rev bump.

**Comment by Bo98** [comment]
No, I don't mean revision bump `matplotplusplus`. I mean revision bumping `gcc` will fix `matplotplusplus`.

**Comment by carlocab** [comment]
Yes, I just noticed it after looking more carefully at `matplotplusplus`: #71011

Should we wait for the `gcc` fix for ARM, or do we give `gcc` are rev bump now? CC @fxcoudert

**Comment by Bo98** [comment]
To clarify: it fails because it is using GCC in the test block of that formula to compile a program (because `fails_with :clang`).

The compile of it probably also fails but that isn't tested here.

**Comment by carlocab** [comment]
Huh, I thought `fails_with` applied only in the `install` block. Ok, yes, `gcc` rev bump + removing the `aligned_alloc` workaround should probably fix this.

**Review by carlocab — APPROVED** [review]
Mojave failures fixed in #71123.

**Pull request closed without merging**
