### PR TITLE
ghc 8.10.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
brew install --build-from-source agda
brew test --retry --verbose allureofthestars
brew install --build-from-source 
brew install --build-from-source cedille
brew install --build-from-source elm
brew install --build-from-source git-annex
brew install --build-from-source idris
brew install --build-from-source texmath
```

**Comment by chenrui333** [comment]
forr idris, https://github.com/idris-lang/Idris-dev/issues/4887

**Comment by hjelmn** [comment]
Once this one is in I have a change to add support for Apple Silicon. It will require an extensive patch based on commits to master but it works.

**Comment by carlocab** [comment]
`agda`: https://github.com/Homebrew/homebrew-core/pull/67014
`texmath`: https://github.com/Homebrew/homebrew-core/pull/67169

**Comment by carlocab** [comment]
A number of build failures on Big Sur (and potentially Xcode 12 more generally) is most likely due (at least in part) to a problem with `ghc`. For example, I believe this is the case with `git-annex` (https://github.com/Homebrew/homebrew-core/pull/64947).

This emerges whenever `ghc` tries to use system frameworks. https://gitlab.haskell.org/ghc/ghc/-/issues/18446, https://github.com/Homebrew/homebrew-core/pull/66599

The solution appears to be to either (https://github.com/Homebrew/homebrew-core/pull/66599#issuecomment-742608137)
- wait for the next release (this is supposedly fixed in 8.8.5 and 8.10.3); or
- use a third-party workaround https://github.com/yairchu/macos11-haskell-workaround

Given the state of haskell-based builds in Homebrew core and the relative lack of expertise among maintainers/contributors, I imagine the former is preferable. However, I am willing to invest time in the latter if it's a desirable solution. (I know zero Haskell though, so, no promises.)

**Comment by fishtreesugar** [comment]
GHC 8.10.3 already released, https://gitlab.haskell.org/ghc/ghc/-/issues/18446 should fixed in 8.10.3.

**Comment by carlocab** [comment]
Thanks, @fishtreesugar.

PR opened: https://github.com/Homebrew/homebrew-core/pull/67284

**Pull request closed without merging**
