### PR TITLE
tabiew 0.7.0

### PR DESCRIPTION
**Pull request by shshemi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> Testing tabiew
  Killing child processes...
  
  Session terminated, killing shell...::error::tabiew: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /you\ think\?/ to match "".
```

---


also please use rebase rather than merge commit to refresh the PR.

**Comment by shshemi** [comment]
Hey @gromgit,
Would you kindly help me with the error?

**Comment by gromgit** [comment]
Try adding `input.close` after the `input.puts ":q"` line.

**Comment by shshemi** [comment]
The test still fails on my local machine with this error:
```
Session terminated, killing shell...Error: tabiew: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /you\ think\?/ to match "".
```
Interestingly, I tried version 0.6.2, and that one failed as well!

**Comment by shshemi** [comment]
@chenrui333
The problems seem to be resolved. Please review the pull request again.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Looks good, thanks @shshemi!

**Pull request merged**
