### PR TITLE
nginx 1.17.5

### PR DESCRIPTION
**Pull request by metowolf**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
A revision bump for `passenger` is needed.

**Comment by CamJN** [comment]
While I was too late to look at the CI logs for this build so I don't know what failed, I believe that for the most recent xcode changes, it will be necessary to change the passenger formula to set `ENV["SDKROOT"] = MacOS::CLT.sdk_path` in the install method instead of unsetting that env var as it currently does.

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by alebcay** [comment]
```
==> brew audit passenger --online
==> FAILED
Error: 1 problem in 1 formula detected
passenger:
  * C: 7: col 3: `revision` (line 7) should be put before `head` (line 6)
```

```
==> /usr/local/opt/nginx/bin/nginx -t -c /private/tmp/passenger-test-20191105-43152-rg97kc/nginx.conf
nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (2: No such file or directory)
nginx: the configuration file /private/tmp/passenger-test-20191105-43152-rg97kc/nginx.conf syntax is ok
2019/11/05 22:12:08 [emerg] 43166#0: mkdir() "/usr/local/var/run/nginx/proxy_temp" failed (2: No such file or directory)
nginx: configuration file /private/tmp/passenger-test-20191105-43152-rg97kc/nginx.conf test failed
```

**Comment by CamJN** [comment]
The `/usr/local/var/run/nginx/proxy_temp` issue is something I'm working on, I'm surprised it only caused an issue now since it's been present in *most* passenger versions.

**Comment by CamJN** [comment]
There's a patch at https://github.com/phusion/passenger/commit/3fef0f2c8b67899a5b38600b86f6390c4a81846d.patch for the proxy temp path issue. Once it's added to passenger, you just have to add the `passenger_temp_path` config option to the nginx test config like the other `temp_path` options.

**Comment by Bo98** [comment]
Fixes have been made in passenger and have been merged. You'll need to rebase this on top of that.

**Pull request closed without merging**
