### PR TITLE
sbcl: add license

### PR DESCRIPTION
**Pull request by gromgit**
Ref: https://sourceforge.net/p/sbcl/sbcl/ci/master/tree/COPYING

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by gromgit** [comment]
CI failures related to #60516, and this PR only changes the license anyway.

**Comment by gromgit** [comment]
@Homebrew/core, need some help to resolve this. Because `sbcl` and `acl2` are tightly coupled, this PR really needs a `CI-syntax-only` tag.

**Comment by MikeMcQuaid** [comment]
> Because `sbcl` and `acl2` are tightly coupled (#60516), CI rebuilds of `sbcl` are guaranteed to fail in the test phase, so this PR really needs a `CI-syntax-only` tag.

Can you explain this a bit more? If this is a false positive it'd be good to remove or adjust the test accordingly.

**Comment by gromgit** [comment]
As I understand it, the `acl2` binary is essentially an SBCL core image with embedded ACL2-specific code. SBCL seems to version-stamp generated core images, and checks at runtime that any image loaded was created by the same SBCL version. Unfortunately, that version stamp includes the timestamp of the SBCL build itself.

This PR contains a metadata-only update (`license`), but CI rebuilds SBCL anyway, then goes on to test `acl2` with the new binary. Naturally, its version stamp doesn't match the one from `acl2`'s core image, so this happens:
```
==> Testing acl2
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200902-81828-189jjbn.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/acl2.rb --verbose --retry
==> /usr/local/Cellar/acl2/8.3_1/bin/acl2 < /private/tmp/acl2-test-20200902-81829-1mwf8c2/simple.lisp | grep 'ACL2 !>'
fatal error encountered in SBCL pid 81842 pthread 0x12c04dc0:
core was built for runtime "Catalina-brew-2020-09-02-14-01-32" but this is "Catalina-brew-2020-09-02-17-55-28"
```

**Comment by MikeMcQuaid** [comment]
I see, makes sense, thanks @gromgit.

**Pull request merged**
