### PR TITLE
cash-cli 3.0.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Test is failing because an API key is needed to make an API call in the test. Any thoughts on how to work around this?

**Comment by xxczaki** [comment]
@alebcay I'm open to suggestions :smile:

**Comment by xxczaki** [comment]
@alebcay Maybe we can just test if setting a API key works:

```ruby
  test do
    assert_match "Saved API key to", shell_output("#{bin}/cash --key foo")
  end
```

**Comment by alebcay** [comment]
@fxcoudert, would the proposed `test` be acceptable?

**Comment by fxcoudert** [comment]
Works for me.

**Comment by alebcay** [comment]
Left changes to `test` block as a new commit, please advise if squash is necessary.

**Comment by fxcoudert** [comment]
@alebcay we always squash to get one commit per formula… I'll do it while merging

**Pull request closed without merging**
