### PR TITLE
dbt 0.7.0

### PR DESCRIPTION
**Pull request by cmcarthur**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Reopened after build issues in #9810

### CODE REVIEW

**Comment by woodruffw** [comment]
El Cap failure: 

```
ImportError: dlopen(/usr/local/Cellar/dbt/0.7.0/libexec/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 2): Symbol not found: _getentropy
  Referenced from: /usr/local/Cellar/dbt/0.7.0/libexec/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/Cellar/dbt/0.7.0/libexec/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
Error: dbt: failed
```

**Comment by ilovezfs** [comment]
This will be fixed in the next version of cryptography, or we can copy the same cryptography patch we're using in all the other formulae that use this resource.

**Comment by cmcarthur** [comment]
@ilovezfs I'd be happy to implement that -- can you point me to another formula that uses the patch?

**Comment by ilovezfs** [comment]
ansible buku certbot fabric mitmproxy

**Comment by cmcarthur** [comment]
Thanks @ilovezfs for the help. I've incorporated the fix and tested with:

```
brew uninstall --force dbt
brew install --build-from-source dbt
brew test dbt
brew audit --strict
```

As well as functional tests for dbt itself.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
