### PR TITLE
cmake cmake-docs 3.25.2

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
seal test failure on linux build.

**Comment by chenrui333** [comment]
just seal test failure on linux, I will follow up on that.

**Comment by ZhongRuoyu** [comment]
Thanks @chenrui333!

**Comment by chenrui333** [comment]
seal just works fine on linux, https://github.com/chenrui333/github-action-test/actions/runs/3963360204/jobs/6791097723

**Pull request closed without merging**
