### PR TITLE
erlang 24.0

### PR DESCRIPTION
**Pull request by Fudoshiki**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by sxn** [comment]
Since there is an `erlang@20`, `erlang@21` and `erlang@22`, would it make sense to keep OTP 23 available as `erlang@23`?

**Comment by Fudoshiki** [comment]
> Since there is an `erlang@20`, `erlang@21` and `erlang@22`, would it make sense to keep OTP 23 available as `erlang@23`?

How do that?

**Comment by bayandin** [comment]
Resource should be updated as well
```
  resource "html" do
    url "https://www.erlang.org/download/otp_doc_html_23.3.tar.gz"
    mirror "https://fossies.org/linux/misc/otp_doc_html_23.3.tar.gz"
    sha256 "03d86ac3e71bb58e27d01743a9668c7a1265b573541d4111590f0f3ec334383e"
  end
```

**Comment by bayandin** [comment]
```
checking for netinet/sctp.h... no
configure: error: sctp support requested, but cannot be enabled since 'netinet/sctp.h' is missing
ERROR: /private/tmp/erlang-20210512-70836-u7vitn/otp-OTP-24.0/erts/configure failed!
```

**Comment by cho-m** [comment]
> ```
> checking for netinet/sctp.h... no
> configure: error: sctp support requested, but cannot be enabled since 'netinet/sctp.h' is missing
> ERROR: /private/tmp/erlang-20210512-70836-u7vitn/otp-OTP-24.0/erts/configure failed!
> ```

Looks like `--enable-sctp` wasn't enforced until 24.0: https://github.com/erlang/otp/commit/9ce3bcd57af647d2883700aadd761086e8852fda

**Comment by shutangyu** [comment]
erlang/otp#482

**Comment by gromgit** [comment]
Even without `--enable-sctp`, building Erlang 24.0 will fail with:
```
checking for OpenSSL in /usr/local/opt/openssl@1.1... configure: error: static linking against crypto library disabled by user, but no dynamic library found in /usr/local/opt/openssl@1.1
```
I've confirmed this locally, and it's being tracked upstream: https://github.com/erlang/otp/issues/4821

**Comment by cho-m** [comment]
@gromgit Yeah, I think I mentioned issue with newer `autoconf` on erlang@22: https://github.com/Homebrew/homebrew-core/pull/76587#issuecomment-832215086

**Comment by Fudoshiki** [comment]
Should I remove `-enable-sctp`?

**Comment by cho-m** [comment]
You should probably wait for referenced upstream issue to get a clear response as Formula will need some extra patches/workarounds for build.

A couple things this PR is probably missing:
1. Symlink `Aliases/erlang@23` should have been renamed to `Aliases/erlang@24`.
2. Need to check if `netinet/sctp.h` is available on macOS. If not, then `--enable-sctp` can probably be removed.
3. `autoconf` issue will need a fix. The workaround right now is to manually set `CPP` and `EGREP` for usage during `configure`. For example, using `"CPP=clang -E"` and `"EGREP=egrep"` as additional arguments to `./configure`

I have gotten `brew` to build `erlang` 24.0 using the last 2 points.
However, it is possible that `autoconf` update has broken other things, so an official upstream response would be best.

**Comment by cjntaylor** [comment]
> Might as well do all fixes at once to avoid CI repeatedly failing.
> 
> You should probably wait for referenced upstream issue to get a clear response as Formula will need some extra patches/workarounds for build.
> 
> A couple things this PR is probably missing:
> 
> 1. Symlink `Aliases/erlang@23` should have been renamed to `Aliases/erlang@24`.
> 2. Need to check if `netinet/sctp.h` is available on macOS. If not, then `--enable-sctp` can probably be removed.
> 3. `autoconf` issue will need a fix. The workaround right now is to manually set `CPP` and `EGREP` for usage during `configure`. For example, using `"CPP=clang -E"` and `"EGREP=egrep"` as additional arguments to `./configure`
> 
> I have gotten `brew` to build `erlang` 24.0 using the last 2 points.
> However, it is possible that `autoconf` update has broken other things, so an official upstream response would be best.

I just want to pop in here and mention a bit of an issue that's being missed here, still being discussed over at https://github.com/erlang/otp/issues/4821. Just setting `CPP` and `EGREP` does get it to build, but doesn't guarantee a functionally complete erlang build. 

We've confirmed that due to the changes in Autoconf 2.70 (http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob_plain;f=NEWS;hb=97fbc5c184acc6fa591ad094eae86917f03459fa), there are very likely other places that the configuration scripts are ***silently failing*** due to changes in how macro preprocessing is done, especially if brew's `autoconf` is called at any point during the build (this is definitely the case if you ever call `otp_build`. If you just build the binary against the pre-generated files, they were created with Autoconf 2.69 and won't be vulnerable to the macro problems.

The recommended solution, right now, is to either build from generated source without calling autoconf, or to build against Autoconf 2.69. I've submitted a PR (referenced above) for inclusion of a keg-only autoconf@2.69 just for this purpose. This would apply to older versions as well; the issue affects autoconf, not erlang/otp - other versioned erlang formulae would need to use the older autoconf as well for the same reason if this approach was taken.

I have a tap (https://github.com/cjntaylor/homebrew-personal) available, for anyone who would like to `brew install cjntaylor/personal/autoconf@2.69` for testing.

**Comment by Fudoshiki** [comment]
reopen?

**Comment by gromgit** [comment]
Given https://github.com/erlang/otp/pull/4835, I think it'll be best to wait for new tarballs to be released, or even a new minor release.

**Comment by cho-m** [comment]
@gromgit I wonder if there is any difference between waiting for a new released GitHub source tarball, or just using OTP's own official tarball:
https://github.com/erlang/otp/releases/download/OTP-24.0/otp_src_24.0.tar.gz

erlang/otp#4835 seems to be planning to just add a pre-built `configure` script using autoconf 2.69 to the Git repo, matching the behavior of the official tarball (i.e. the one linked above, not the one generated by GitHub).

**Comment by lucacorti** [comment]
@gromgit @cho-m yes, tarballs are already out with prebuilt scripts, they are adding those to git tags, so using the 24.0 release tarball should work.

**Comment by lucacorti** [comment]
https://github.com/erlang/otp/issues/4821#issuecomment-840192782

**Comment by cho-m** [comment]
I created a new PR #77620 based on other tarball.

Further discussion on whether worth using can continue there.
Probably still need to create `erlang@23` formula

**Pull request closed without merging**
