### PR TITLE
mpd 0.19.19

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 what's the point of the PR template when they just check all the boxes blindly anyway? :see_no_evil:

**Comment by DomT4** [comment]
Some people find it useful. Others read it once & check the boxes forevermore. Others don't bother to read any of it. Sadly there's no way to funnel everyone into the first category 😓.

**Comment by ilovezfs** [comment]
has "remote electrocution via keyboard" been patented yet? :laughing:

**Comment by DomT4** [comment]
I think we'd probably attract some controversy over that 😄

**Comment by ilovezfs** [comment]
too harsh? :innocent:

**Comment by DomT4** [comment]
I think people would want an opt-out 😉

**Pull request closed without merging**
