### PR TITLE
cython 0.25.2 (new formula)

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Gift for @tdsmith ref #1803.

### CODE REVIEW

**Comment by tdsmith** [comment]
Thanks Dom! Something we'll have to worry about at ~some~ point is that cython will only cythonize for the python x.y version we install it with. But that day is not today!

**Comment by ilovezfs** [comment]
Is there any reason to leave those with-cython/without-cython optional/recommended in there if there's now a bottle? It seems like we could flip them always on and remove the options now.

**Comment by tdsmith** [comment]
I think there isn't! Figured I'd do that separately. :)

**Comment by ilovezfs** [comment]
Cool. Thanks for the new formula Mr. T

**Comment by DomT4** [comment]
> Thanks Dom!

No worries! ❤️.

> Something we'll have to worry about at ~some~ point is that cython will only cythonize for the python x.y version we install it with. But that day is not today!

Presumably means when this formula is shunted over to `python3` one day if `python3` jumps from `3.6` to `3.7` we'd need to remember to revision bump `cython`? Which isn't hugely painful I guess, if I'm reading that correctly.

> Is there any reason to leave those with-cython/without-cython optional/recommended in there if there's now a bottle?

To be honest I just left them because AFAIK I no longer have access to the analytics data on this & didn't want to kill an option that was, unbeknownst to me, popular.

**Comment by RandomDSdevel** [comment]
@DomT4:  Thanks for being inspired to take care of this for me instead of waiting for me to follow up on #4254 after being inspired to do so independently of it by @tdsmith's earlier parallel [RFC](https://github.com/Homebrew/homebrew-core/issues/1803) (I probably should have just searched for similar issues in the archives instead of creating a new one, but I _guess_ it worked out OK…)  (_Man_, I _really_ need to go back through contributions I've made and make a list of cans I've kicked down the road so I can pick them back up and deal with them, don't I…?)

**Comment by DomT4** [comment]
> (Man, I really need to go back through contributions I've made and make a list of cans I've kicked down the road so I can pick them back up and deal with them, don't I…?)

I think most of us semi-regular contributors are in the same boat 😄.

This doesn't solve the `cython` issue for `nghttp2` because `nghttp2` uses `python3` and this is built around `python2` currently.

I thought about hacking `python3` support into this formula but at some point things become so complicated that only a few people end up completely comfortable touching any of it, which is something I've been burned on before, so I left it at simple.

**Comment by ilovezfs** [comment]
Probably `cython%python3` (or did people prefer `cython^python3`?) if it comes to that.

**Comment by DomT4** [comment]
I quite like the idea of bastardising the `@` but I think we've too thoroughly burned the logic into Homebrew & its users that `@` == different version of the _same_ upstream project rather than different configuration. So yeah, if we go down that path another symbol seems likely.

**Comment by RandomDSdevel** [comment]
@DomT4:  

> …
>
> This doesn't solve the `cython` issue for `nghttp2` because `nghttp2` uses `python3` and this is built around python2 currently.
>
> …

Oh, right.  I forgot about and/or overlooked that in my overly brief reassessment of the situation with respect to ngHTTP2.  

<hr />

@DomT4 and @ilovezfs w. r. t. versioning:  

Maybe `cython%python@3` or `cython^python@3`?  (Oh, wait; looks like Python hasn't been moved over to the new versioning syntax yet…:man_facepalming:.)

**Comment by tdsmith** [comment]
It starts to look like line noise.

We were bikeshedding about this somewhere else and I said I didn't care but I do like the %; cython%python3 is a nice pun on modular arithmetic and reads sort of like "cython in python3-land".

**Comment by RandomDSdevel** [comment]
@tdsmith:  

> It starts to look like line noise.
>
> …

:man_shrugging:  All of the suggestions I made look readable to me, _but_, since I'm only chiming in as an end user and some-time contributor, it's up to you maintainers to make the judgement call on whether you feel the same or not.  I agree concise expression of semantics in syntax is important.  

> …
>
> We were bikeshedding about this somewhere else and I said I didn't care but I do like the %; cython%python3 is a nice pun on modular arithmetic and reads sort of like "cython in python3-land".

It would be interesting to go back and read that discussion if either I could find it or you or one of the others could point me to it.  (What might I search for to find it, by the way…?)  That aside, `"$FORMULA"%"$DEPENDENCY"` (for any given set of values for `FORMULA` and `DEPENDENCY`, of course) reads like 'take the remainder of dividing `"$FORMULA"` by `"$DEPENDENCY"`, which doesn't really make any sense, in the context of modular arithmetic, since 'take the remainder of dividing the first argument by the second' is what the modulus operator means.  None of the character's [other possible usages](https://en.wikipedia.org/wiki/Percent_sign#Usage) seem quite suitable either.

**Comment by tdsmith** [comment]
I just meant that having more than one punctuation character in a name starts to look garbled.

Looks like the "discussion" was just the comment here: https://github.com/Homebrew/homebrew-core/pull/13149#issuecomment-298805838

The sense in which using % for flavors is a pun on modular arithmetic is similar to the [long-attested use](http://www.dourish.com/goodies/jargon.html) of "modulo" to mean "except for" or "in the context of," which was no doubt inspired by pleasant associative and distributive properties of the modulus operator.

It's not a very good pun, no.

**Comment by RandomDSdevel** [comment]
@tdsmith:  

> I just meant that having more than one punctuation character in a name starts to look garbled.
>
> …

I tend to be a bit more forgiving of punctuation in names myself as long as said names remain parseable, but, yeah, I agree there _is_ a point where the human brain just starts to see things only as 'token soup.'  

> …
>
> Looks like the "discussion" was just the comment here: [#13149 (comment)](https://github.com/Homebrew/homebrew-core/pull/13149#issuecomment-298805838)
>
> …

Ah, thanks!  

> …
>
> The sense in which using % for flavors is a pun on modular arithmetic is similar to the [long-attested use](http://www.dourish.com/goodies/jargon.html) of "modulo" to mean "except for" or "in the context of," which was no doubt inspired by pleasant associative and distributive properties of the modulus operator.
>
> …

OK, _now_ it makes sense.  

> …
>
> It's not a very good pun, no.

Indeed, which is why I have the concern that some users might not appreciate it, thinking it too esoteric and obtuse&thinsp;—&thinsp;heck, even _I_ didn't get it at first&thinsp;—, but whether such a convention could become a problem is a matter of opinion (and said worry could _also_ be alleviated by good documentation.)

**Comment by gwerbin** [comment]
I know this discussion is a bit old, but why not use the `--with-python3` and `--without-python` options that other Python formulas use?

**Pull request closed without merging**
