### PR TITLE
cake 0.38.2

### PR DESCRIPTION
**Pull request by gep13**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by issyl0 — COMMENTED** [review]
Audit failure because it's a GitHub pre-release. But all the previous versions (that we shipped) are also pre-releases.

**Comment by gep13** [comment]
@issyl0 This came up in the last PR that I did as well:

https://github.com/Homebrew/homebrew-core/pull/55500

I added a comment into the formula as requested.

**Review by issyl0 — APPROVED** [review]
So you did. Sorry, my eyes scanned the changed lines in the diff, not the whole formula. Cool, thanks! 👍

**Comment by gep13** [comment]
@issyl0 absolutely no need to apologise.  Thanks for getting this merged in, really appreciate it!

**Pull request closed without merging**
