### PR TITLE
kubernetes-helm 2.16.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cagataygurturk** [comment]
Hello @chenrui333 

May I ask if you are planning to create a different formula for Helm 3 or create a separated one for Helm 2, so people can pin the version?

We have some tooling depending on Helm 2 and I am afraid that when this formula is updated to Helm 3, it will break all our users' computers. 

Thanks.

**Comment by mikesplain** [comment]
@cagataygurturk, I've opened both cases. Please consider commenting on #46709 if you'd prefer that for the time being. I think that's the right thing to do today, then create a kubernetes-helm@2 and eventually migrate kubernetes-helm to @3.

**Comment by cagataygurturk** [comment]
I just had a discussion with @chenrui333 on Kubernetes Slack.

Options are:

**Option 1:**
- Kicking off `cncf-helm` as suggested here: https://github.com/Homebrew/homebrew-core/pull/45789#issuecomment-546190893 by @bacongobbler 
- Leaving `kubernetes-helm` with 2.x. 

This won't break any current user setup. People desiring to use Helm 3 will have to switch to `cncf-helm` proactively.

**Option 2:**
- Creating a `kubernetes-helm@2` and updating 2.x patches to that repo. `kubernetes-helm` continues with 3.x

This may break some systems if users are not aware of changes with the Helm 3. I see this option is risky.

**Option 3:**
- Kicking off `cncf-helm`, keeping `kubernetes-helm` with 2.x until EOL of 2.x. After that, `kubernetes-helm` can become an empty formula that only depends on `cncf-helm`. So current 2.x users would have some grace period until they upgrade.

Any feedback welcome.

**Comment by chenrui333** [comment]
I will also pass this comment to the brew maintainers for discussion.

**Comment by fxcoudert** [comment]
Homebrew's rules for versioned formulas are here: https://docs.brew.sh/Versions
Our way to handle such migrations is your option 2.

**Pull request closed without merging**
