### PR TITLE
libint: build shared lib

### PR DESCRIPTION
**Pull request by junghans**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

For #132494

### CODE REVIEW

**Comment by junghans** [comment]
@chenrui333 please have a look.

**Comment by junghans** [comment]
Any ideas how to solve:
```
2023-06-04T15:56:36.2470180Z libint
2023-06-04T15:56:36.2470340Z   * Libraries were compiled with a flat namespace.
2023-06-04T15:56:36.2470530Z     This can cause linker errors due to name collisions, and
2023-06-04T15:56:36.2470720Z     is often due to a bug in detecting the macOS version.
2023-06-04T15:56:36.2470910Z       /opt/homebrew/Cellar/libint/2.7.2/lib/libint2.2.dylib
```

**Comment by junghans** [comment]
> Any ideas how to solve:
> 
> ```
> 2023-06-04T15:56:36.2470180Z libint
> 2023-06-04T15:56:36.2470340Z   * Libraries were compiled with a flat namespace.
> 2023-06-04T15:56:36.2470530Z     This can cause linker errors due to name collisions, and
> 2023-06-04T15:56:36.2470720Z     is often due to a bug in detecting the macOS version.
> 2023-06-04T15:56:36.2470910Z       /opt/homebrew/Cellar/libint/2.7.2/lib/libint2.2.dylib
> ```

Found it!

**Review by carlocab — APPROVED** [review]
LGTM; thanks.

**Review by chenrui333 — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request merged**
