### PR TITLE
gcovr 3.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
@DomT4 is the `bin.install_symlink "../libexec/scripts/gcovr"` in the formula actually idiomatic?

**Comment by DomT4** [comment]
Er, nope. Not sure what the thinking was whenever someone added that line.

**Comment by ilovezfs** [comment]
mirror should be re-added once Debian updates

**Pull request closed without merging**
