### PR TITLE
arttime: update incorrect sha256.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Change confirmed in https://github.com/Homebrew/homebrew-core/pull/159173#issuecomment-1879757655

PR author unwilling or unable to make changes as requested so have made my own `sha256` update here.

Closes https://github.com/Homebrew/homebrew-core/pull/159173

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by poetaman** [comment]
@MikeMcQuaid Please remove arttime as per our prior conversation that you got locked to be visible only to collaborators. I am attaching it for homebrew arttime's users reference.

[now_hidden_conversation_about_arttime.pdf](https://github.com/Homebrew/homebrew-core/files/13865724/now_hidden_conversation_about_arttime.pdf)

**Comment by p-linnane** [comment]
> @MikeMcQuaid Please remove arttime from homebrew as per our prior conversation that you got locked to be visible only to collaborators. I am attaching it for homebrew arttime's users reference.
> 
> [hidden_conversation_about_arttime.pdf](https://github.com/Homebrew/homebrew-core/files/13865733/hidden_conversation_about_arttime.pdf)

A few things:
1. I locked the thread because it had become unproductive. The full conversation is visible by anyone, without logging in, so there's no reason to attach a PDF of it.
2. `arttime` is published under GPL 3.0. There is no clause that states "You must remove this software from distribution at the authors request". That completely goes against the ethos of open source software. `arttime` will not be removed from Homebrew, as we keep in line with free and open source software.
3. While we appreciate contributions from authors of software, you are not contributing anything except arguing with how we run our packaging and distribution project. To be frank, you have no say in how we do things, especially given the way you handled yourself in the other thread. Rational discussions are welcome, but in the event we decline to do what you'd like, you can't throw a fit and try to take your marbles home by demanding we remove your software.
4. I am unsure if it matters to you, but I am going to request that you please stop commenting. Nothing good or productive will come from it, and the alternative is a ban. Thanks.

**Comment by p-linnane** [comment]
That sounds like a problem you need to address _**within**_ your software. It's not Homebrew's job to print every upstream idiosyncrasy. Our job is to build and install open source software for our millions of users. This sort of thing belongs in either your documentation or a prompt upon launching the software for the first time.

With regard to `arttime` specifically, we are talking about a package that has been installed 310 times in the last 365 days. By my count, that ranks at position 5134 out of 6992 formulae. I understand that you believe we are acting irrationally, but we as volunteer maintainers have extremely limited time to maintain Homebrew, and don't want to spend it arguing with you on how we do things, especially for something that is not a popular piece of software.

This is the last I am going to comment on this.

**Comment by MikeMcQuaid** [comment]
I agree with everything @p-linnane has said here and his decisions to lock this and the other PR.

**Pull request merged**
