### PR TITLE
libsvg: revision bump for ARM

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
checking build system type... configure: error: /bin/sh ./config.sub -apple-darwin20.2.0 failed
```

**Comment by fxcoudert** [comment]
After forcing an autoreconf:

```
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoreconf: running: /opt/homebrew/Cellar/autoconf/2.69/bin/autoconf --force
configure.in:11: error: possibly undefined macro: LT_CURRENT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.in:15: error: possibly undefined macro: LT_REVISION
configure.in:20: error: possibly undefined macro: LT_AGE
```

**Comment by citelao** [comment]
@fxcoudert, I submitted a change to your branch (https://github.com/fxcoudert/homebrew-core/pull/3) that enables libsvg to build completely on my M1 MacBook Pro.

It looks to be successful, though I have not consumed it yet.

I adapted a [change from Cairo](https://cgit.freedesktop.org/cairo/commit/?id=afdf3917ee86a7d8ae17f556db96478682674a76):

```diff
diff --git a/configure.in b/configure.in
index a9f871e..c84d417 100755
--- a/configure.in
+++ b/configure.in
@@ -8,18 +8,18 @@ LIBSVG_VERSION=0.1.4
 # libtool shared library version
 
 # Increment if the interface has additions, changes, removals.
-LT_CURRENT=1
+m4_define(LT_CURRENT, 1)
 
 # Increment any time the source changes; set to
 # 0 if you increment CURRENT
-LT_REVISION=0
+m4_define(LT_REVISION, 0)
 
 # Increment if any interfaces have been added; set to 0
 # if any interfaces have been removed. removal has
 # precedence over adding, so set to 0 if both happened.
-LT_AGE=0
+m4_define(LT_AGE, 0)
 
-VERSION_INFO="$LT_CURRENT:$LT_REVISION:$LT_AGE"
+VERSION_INFO="LT_CURRENT():LT_REVISION():LT_AGE()"
 AC_SUBST(VERSION_INFO)
 
 dnl ===========================================================================
```

**Comment by fxcoudert** [comment]
Please open it as a PR to homebrew-core's repo, not on my branch

**Comment by citelao** [comment]
See #74623

**Pull request closed without merging**
