### PR TITLE
apache-arrow, gdal, pdal: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by carlocab**
See #134251.

### CODE REVIEW

**Comment by carlocab** [comment]
Needs:
- #134376

**Comment by carlocab** [comment]
`/home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: error: /home/linuxbrew/.linuxbrew/lib/libarrow_acero.so.1200.1.0: file too short`
😕

**Comment by carlocab** [comment]
Yep. Thinking about the best way to fix it.

**Comment by carlocab** [comment]
> `/home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: error: /home/linuxbrew/.linuxbrew/lib/libarrow_acero.so.1200.1.0: file too short`
> 😕

Happened again despite rebuilding `apache-arrow`. I wonder if it's an issue with the self-hosted runner.

**Comment by carlocab** [comment]
If we look at the just-built `libarrow_acero.so`, we have:
```
./libarrow_acero.so.1200.1.0:      ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, missing section headers at 9957704
```
which looks wrong, since the other libraries have something like
```
./libarrow.so.1200.1.0:            ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=3c013ee4f89efe46b2ba2f19cc7afb897f7a2c71, not stripped
```
Not really sure what's wrong with it. I've attached a [tarball of `libarrow_acero.so`](https://github.com/Homebrew/homebrew-core/files/11833844/libarrow_acero.tar.gz) in case someone wants to take a look at it.

@kou, any chance you could take a look at this?

**Comment by Bo98** [comment]
> I wonder if this is another Patchelf bug.

If it is, please check if it affects regular patchelf (`brew install patchelf`). If it does, then it ideally will need to be fixed there.

If not, then it may have been fixed recently and I can port that over.

**Comment by kou** [comment]
I've seen a similar broken `.so`. It was in a `.deb` package provided by MariaDB. But I didn't look into it at the time...

Can I see the build log when the `llibarrow_acero.so.1200.1.0` was built?

**Comment by carlocab** [comment]
I've lost the logs for the `libarrow_acero.so` that I uploaded above, but I have logs and bottles for an earlier build with the same problem.

I'll upload them here as a tarball shortly, but it's taking a little bit of time to download. If you don't want to wait and don't mind downloading them yourself:
```sh
gh run download 5343738024 --name 'bottles' --name 'logs-linux-self-hosted-1' -R Homebrew/homebrew-core
```

**Comment by carlocab** [comment]
Hmm, the cache is recycling the bad bottle. Let's try to build a new one...

**Comment by kou** [comment]
Thanks!
I took a look at the log but I couldn't find a strange point...
I'll try this on local machine.

**Comment by carlocab** [comment]
This is definitely a `brew` bug. Building `apache-arrow` from source, without bottling`, and then building `gdal` succeeds: https://github.com/carlocab/workflow-test/actions/runs/5361256572/jobs/9727036777

`libarrow_acero.so` [looks fine](https://github.com/carlocab/workflow-test/actions/runs/5361256572/jobs/9727036777#step:6:9) too:
```
/home/linuxbrew/.linuxbrew/opt/apache-arrow/lib/libarrow_acero.so.1200.1.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=9b70dc009bf1c837a3d458096725662fc23dc290, not stripped
```

The ELF header probably gets mangled by `patchelf`.

**Comment by Bo98** [comment]
I've not updated patchelf yet because there's a number of regressions which mean many aren't using the latest version. I'll see however if this specific issue is casued by it and if it happens upstream.

**Comment by Bo98** [comment]
I'm unable to reproduce this locally.

A copy of the file prior to `brew bottle` may be useful.

**Comment by carlocab** [comment]
Ok, let me dig a little more into this.

**Comment by carlocab** [comment]
[Here](https://github.com/carlocab/workflow-test/actions/runs/5365109286)'s a workflow that first does (from this PR branch)
```
brew install --build-bottle apache-arrow
brew install --build-from-source gdal
```
and succeeds. Then it does
```
brew uninstall gdal
brew bottle apache-arrow
brew uninstall apache-arrow
brew install ./apache-arrow*.tar.gz
brew install --build-from-source gdal
```
and then fails at building `gdal`.

I've uploaded the `libarrow_acero` built before calling `brew bottle` to the [logs artifact](https://github.com/carlocab/workflow-test/suites/13837509446/artifacts/768377313) (inside `logs-before`). The `apache-arrow` bottle has also been uploaded as the [arrow-bottle artifact](https://github.com/carlocab/workflow-test/suites/13837509446/artifacts/768377312).

**Comment by carlocab** [comment]
Looking at `libarrow_acero` before and after bottling, it looks like `brew bottle` definitely broke it:
```
❯ file libarrow_acero-pre-bottle.so.1200.1.0 libarrow_acero-post-bottle.so.1200.1.0
libarrow_acero-pre-bottle.so.1200.1.0:  ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=4149d5914641c14870178657327eafcc909a8a66, not stripped
libarrow_acero-post-bottle.so.1200.1.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, missing section headers at 9957704
```
Here's copies of `libarrow_acero.so` before and after `brew bottle`: [libarrow_acero.tar.gz](https://github.com/Homebrew/homebrew-core/files/11859263/libarrow_acero.tar.gz)

**Comment by Bo98** [comment]
Interesting, it's doing text replacements on the file...

I'm seeing `@@HOMEBREW_CELLAR@@` in there, which our patchelf stuff does not do.

**Comment by Bo98** [comment]
The opening 1024 bytes of the file contains the sequence `0C 23 21 0A`, triggering a very rare bug that will only occur with files containing that byte sequence (or maybe `0A`/`0D` instead of `0C`).

https://github.com/Homebrew/brew/pull/15586

**Comment by Bo98** [comment]
acero should hopefully work now. It will require a new brew release, but that will likely happen anyway before staging is merged to master.

**Comment by carlocab** [comment]
Looks like that worked. Thanks @Bo98!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
