### PR TITLE
chromaprint 1.4.2

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
`time.h` errors, yay:
```
/tmp/libgroove-20170107-60875-1cbrpw9/libgroove-4.3.0/grooveplayer/osx_time_shim.h:21:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.

**Comment by dunn** [comment]
Oh, right: https://github.com/andrewrk/libgroove/issues/129

**Comment by DomT4** [comment]
This should work now if you rebase it against master. `libgroove` went to formulae heaven.

**Comment by ilovezfs** [comment]
It is on a beautiful farm frolicking with its friends. Believe me.

**Comment by ilovezfs** [comment]
I believe the ffmpeg dependency is no longer needed for the examples.

**Comment by JCount** [comment]
🎊 🎉

**Pull request closed without merging**
