### PR TITLE
carina: fix 1.5.0 ref

### PR DESCRIPTION
**Pull request by mattrobenolt**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Apparently another commit came out on this tag and I can only assume, the tag was force pushed: https://github.com/getcarina/carina/commits/v1.5.0

### CODE REVIEW

**Comment by zmwangx** [comment]
Could you please confirm with upstream that the force push was intentional? It's our standard procedure to make sure nothing malicious is going on, thanks.

**Comment by mattrobenolt** [comment]
@zmwangx The only extra commit was fixing their build script which seems like it caused a bad build for them in Travis: https://github.com/getcarina/carina/commit/2d7f5c0afe28a3e9e794c99ce5024be283979e71 It's the only sha after 621b6ecc9d34bad00b016a9829210b33fd4f2355

But I'll cc @carolynvs in hopes that she confirms this. :) I have no affiliation with the Carina project personally.

**Comment by carolynvs** [comment]
Sorry about that! 😞 Yes, I pushed that extra commit under the same tag to workaround a bug in travis's deploy that sprang up last week...

**Comment by zmwangx** [comment]
@cacology No problem, thanks for the confirmation.

**Comment by zmwangx** [comment]
Merged as 32809d2. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
