### PR TITLE
nnn 4.0

### PR DESCRIPTION
**Pull request by jarun**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jarun** [comment]
I'm not sure why this is failing now. There is no change in this area that can lead to this issue. Will leave it open till someone fixes this issue in the script.

**Comment by nandahkrishna** [comment]
The issue with the test is that the older version of `nnn` always displayed the absolute path of the directory, whereas the current version uses `~` to represent the home directory (jarun/nnn#922).

**Comment by jarun** [comment]
@nandahkrishna Thanks a lot for checking this and the patch!

**Review by carlocab — APPROVED** [review]

**Comment by a-wing** [comment]
Hi, Maybe nnn need add `misc/quitcd` scripts

For example

`~/.zshrc`

```sh
source $(brew --prefix nnn)/quitcd/quitcd.bash_zsh
```

**Comment by jarun** [comment]
Sorry, no pans to install the scripts as shell preference varies among users.

**Comment by a-wing** [comment]
look like fzf

https://github.com/Homebrew/homebrew-core/blob/master/Formula/fzf.rb#L24

Only install. need user set enable `~/.zshrc`

```sh
source $(brew --prefix fzf)/shell/completion.zsh
source $(brew --prefix fzf)/shell/key-bindings.zsh
```

**Comment by jarun** [comment]
The scripts should be treated as examples. Also, it's a one-time activity.

**Pull request closed without merging**
