### PR TITLE
python-jinja: remove

### PR DESCRIPTION
**Pull request by cho-m**
```
==> Analytics
install: 8,152 (30 days), 45,306 (90 days), 58,716 (365 days)
install-on-request: 103 (30 days), 430 (90 days), 499 (365 days)
build-error: 0 (30 days)
```

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by rbalint** [comment]
Hi @chenrui333, this is a build dependency of Firebuild: https://github.com/firebuild/firebuild/blob/0c076a4d8fc7a5dc3add89993f80343867cb8381/Brewfile#L8
Any chance of adding it back?

**Comment by rbalint** [comment]
Or should I switch back to using [jinja2-cli](https://formulae.brew.sh/formula/jinja2-cli)? Will that formula stay?

**Comment by cho-m** [comment]
> Any chance of adding it back?

`python-jinja` does not meet our requirements to remain in `homebrew-core`

Ref: https://docs.brew.sh/Python-for-Formula-Authors#libraries
Ref: https://github.com/Homebrew/brew/pull/16662

---

> Or should I switch back to using [jinja2-cli](https://formulae.brew.sh/formula/jinja2-cli)? Will that formula stay?

`jinja2-cli` will probably remain as an app/executable.

Ref: https://docs.brew.sh/Python-for-Formula-Authors#applications

**Comment by rbalint** [comment]
@cho-m OK, thanks!

**Pull request merged**
