### PR TITLE
arttime: remove

### PR DESCRIPTION
**Pull request by poetaman**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Arttime project has different licensing for its different components and aspects of usage, and it isn't clear how to completely express it with homebrew's formula syntax. Moreover, some components and aspects of usage might not be compatible with [DebianFreeSoftwareGuidelines](https://wiki.debian.org/DebianFreeSoftwareGuidelines), which homebrew seemingly wants to adhere to.

Please check the files LICENSE_ART, LICENSE_CODE, and LICENSE_ADDENDUM_CFLA which have been present all along in the release tarballs as well as top directory of arttime's github homepage: https://github.com/poetaman/arttime from the initial commits to the repository. All the source file headers reference them as well. Here's a summary of problems or incompatibilities in licensing between homebrew and arttime:

1. All the text art files https://github.com/poetaman/arttime/tree/main/share/arttime/textart are individual artist's copyright. I see no mechanism in homebrew's documentation to specify that.
2. Arttime is also a curation of text art files. The curation is subject to CFLA, while the individual pieces of text art is not (as mentioned in LICENSE_ART).
3. The source code is GPL3 for usual development process: forking, editing source code, etc. But the usage of arttime or its derivates is not GPL3. The preamble leading to GPL3 section of license, [Lines 1-10](https://github.com/poetaman/arttime/blob/main/LICENSE_CODE#L1-L10) in file LICENSE_CODE says that in case of conflicting statement between GPL3 and CFLA (which focusses on usage), CFLA shall override the statements in that document (which includes GPL3).
4. CFLA requires that it is copied in all the derivates and forks. "If found in a repository, it must be retained in
the copies of work, and it's forks of any form.". There isn't a way I see to specify that with homebrew's formula syntax.

### CODE REVIEW

**Comment by chenrui333** [comment]
I did a bit reading on your PR comment, but I still dont quite comprehend why it has to be disabled/removed (also you should do the `disable!` route first so that users got notified with the reason and have a plan).

is this mostly due to the licensing thing?

**Comment by MikeMcQuaid** [comment]
@poetaman We told you before that we are not wanting to remove this formula. Do not send another PR attempting to remove it again or you will be blocked from the Homebrew organisation on GitHub.

**Comment by p-linnane** [comment]
The context for why this user actually wants to remove this software can be found in the following:
https://github.com/Homebrew/homebrew-core/pull/159173
https://github.com/Homebrew/homebrew-core/pull/159343

**Comment by chenrui333** [comment]
Aha, thanks @MikeMcQuaid @p-linnane for the context

**Comment by poetaman** [comment]
@MikeMcQuaid If you don't want to remove the software, you need to correct the license information on your platform to match arttime's release tarballs. There are many ways you can do that:

1. Completely remove license information from the webpage of arttime (https://formulae.brew.sh/formula/arttime), and one returned by ``brew info arttime``. This would make the user look for license information in arttime's tarball or GitHub page.
2. Update the webpage and ``brew info arttime`` to return more accurate information.

Regarding your threat to block me from homebrew while keeping to publish inaccurately licensed formula, that is unfair. The prior PR was not to remove arttime from homebrew, it was to add a caveat note for users; don't mislead the GitHub community here. This is the first and only PR asking to remove arttime for licensing incoherence between your platform, arttime't tarball and your platform's license attribution.

@p-linnane You are mistaken. I am following your documentation that says a formula should be "removed" from your platform if it doesn't meet the the acceptable formulae criterion. The page on acceptable formulae criterion says it has to adhere to [DebianFreeSoftwareGuidelines](https://wiki.debian.org/DebianFreeSoftwareGuidelines). And I just showed it doesn't.

There is precedence from your pull requests that show that you do indeed remove formulae that do not meet the DebianFreeSoftwareGuidelines, here are two examples: https://github.com/Homebrew/homebrew-core/pull/66609 (unrar), and https://github.com/Homebrew/homebrew-core/pull/74438 (atlassian-cli). There are other similar examples where a formula is removed because it doesn't meet your licensing requirement.

If you don't find a solution to correct the licensing information, or remove arttime from homebrew, I will have to raise this with GitHub as a case of developer harassment on their platform because you are changing your own policies on the fly in light of your conduct on https://github.com/Homebrew/homebrew-core/pull/159173, https://github.com/Homebrew/homebrew-core/pull/159343 and the resultant grudge. It doesn't make Github a safe place to collaborate.

Here are relevant links:
1. homebrew's formula removal policy: https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#removal.
2. homebrew's acceptable formule policy: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae
3. homebrew's licensing guideline: https://docs.brew.sh/License-Guidelines

The same are attached here as pdf's as am not sure if you constantly keep changing them:

1. [homebrew_deprecate_disable_remove.pdf](https://github.com/Homebrew/homebrew-core/files/13906520/homebrew_deprecate_disable_remove.pdf)
2. [homebrew_acceptable_formulae.pdf](https://github.com/Homebrew/homebrew-core/files/13906514/homebrew_acceptable_formulae.pdf)
3. [homebrew_license_guidelines.pdf](https://github.com/Homebrew/homebrew-core/files/13906495/homebrew_license_guidelines.pdf)

**Comment by MikeMcQuaid** [comment]
@poetaman As this was your third warning: on request from other maintainers you are now blocked from @Homebrew.

**Pull request closed without merging**
