### PR TITLE
numpy 1.15.2

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
Test failures of `dartsim` and `nlopt` on High Sierra and Mojave. #32384 #32385

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
```
09:54:26 ==> brew linkage --test arcade-learning-environment
09:54:28 ==> FAILED
09:54:28 Missing libraries:
09:54:28   /tmp/arcade-learning-environment-20180826-95697-s87ybl/Arcade-Learning-Environment-0.6.0/ale_python_interface/libale_c.so
```

This is endless. 🤦🏻‍♂️

**Comment by fxcoudert** [comment]
@BrewTestBot test this please
Let's ignore the arcade-learning-environment issue for now…

**Pull request closed without merging**
