### PR TITLE
php, php@8.2, php@8.1: enable ext-imap

### PR DESCRIPTION
**Pull request by derrabus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR enables the [IMAP extension for PHP](https://www.php.net/manual/en/book.imap.php). ext-imap is part of PHP's core repository and thus cannot be installed through PHP's PECL installer.

### CODE REVIEW

**Comment by derrabus** [comment]
I don't understand the build failure on Linux. Any help in that regard would be appreciated. Alternatively, I could skip building the extension on Linux.

If you think that the extension is too exotic to include it in the bottle, closing the PR would also be fine for me. I can work with a locally patched PHP for those projects where I need the extension.

**Comment by chenrui333** [comment]
```
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/opt/imap-uw/lib/libc-client.a(osdep.o): relocation R_X86_64_PC32 against symbol `auth_md5' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: final link failed: bad value
```

**Comment by SMillerDev** [comment]
```console
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/opt/imap-uw/lib/libc-client.a(osdep.o): in function `ssl_onceonlyinit.part.0':
  osdep.c:(.text+0x62d6): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/opt/imap-uw/lib/libc-client.a(osdep.o): in function `ssl_onceonlyinit.part.0':
  osdep.c:(.text+0x62d6): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/opt/imap-uw/lib/libc-client.a(nntp.o): warning: relocation against `nntpdriver' in read-only section `.text'
  /usr/bin/ld: warning: GNU indirect functions with DT_TEXTREL may result in a segfault at runtime; recompile with -fPIC
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/opt/imap-uw/lib/libc-client.a(osdep.o): relocation R_X86_64_PC32 against symbol `auth_md5' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: final link failed: bad value
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:183: libphp.la] Error 1
  make: *** Waiting for unfinished jobs....
```

**Comment by derrabus** [comment]
I've invested some time into fixing the build failure on Linux, but I'm giving up now, sorry. 😞 

I still need the extension for my project though. Would you accept this PR if I build the IMAP extension on MacOS only? Otherwise, I'd close this PR and keep my branch rebased for newer PHP releases.

**Comment by SMillerDev** [comment]
We can try it macOS only

**Comment by derrabus** [comment]
Done. The CI is failing on macOS on Intel, but I don't really see how my change is related. 😕

**Review by SMillerDev — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
