### PR TITLE
krakend 2.1.0

### PR DESCRIPTION
**Pull request by SMillerDev**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Relates to https://github.com/Homebrew/homebrew-core/pull/107165

### CODE REVIEW

**Comment by chenrui333** [comment]
update to use [the latest release](https://github.com/krakendio/krakend-ce/releases/tag/v2.0.6), `v2.0.6`

**Comment by SMillerDev** [comment]
The question if their repo was compromised isn't answered yet.

**Comment by alombarte** [comment]
Hi @SMillerDev, the repo is not compromised. v2.0.5 was retagged because was wrongly pushed.
The shasum of the v2.0.6 tar file is:
```
shasum -a 256 ~/repo/krakend-ce-2.0.6.tar.gz                                                                                                                    
76846b9a8758a8a679e13c4cce1c99e726a23d665a00dacf88e44d5494acd5e7
```
The code is hosted on Github with the same shasum. I will also update in a PR at some point the URL of the repository as the organization has moved from `devopsfaith` to `krakendio`.

Let me know if you have more questions

**Comment by alombarte** [comment]
Here is some activity

**Comment by chenrui333** [comment]
I think it is good to go at this moment.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
