### PR TITLE
minidlna 1.3.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    Minitest::Assertion: Expected /MiniDLNA\ 1\.3\.3/ to match "<HTML><HEAD><TITLE>400 Bad Request</TITLE></HEAD><BODY><H1>Bad Request</H1>The request is invalid for this HTTP version.</BODY></HTML>\r\n".
```

**Comment by cho-m** [comment]
Upstream issue: https://sourceforge.net/p/minidlna/bugs/346/

This causes `localhost` to fail. Although it is possible to use corresponding IP (127.0.0.1), I am not sure how users' use case would be impacted by upstream issue.

**Comment by MikeMcQuaid** [comment]
Have removed `help wanted` and/or `in progress` from this PR as there's been no progress in a few months. Maintainers: please don't add these labels as the stalebot is performing a useful service in continuing to bump these PRs and closing them if there's no activity after those bumps. Thanks ❤️

**Comment by chenrui333** [comment]
I am gonna close this PR for now, for whoever watching this, feel free to open a new one. :)

**Pull request closed without merging**
