### PR TITLE
xctesthtmlreport 2.3.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[3/5] Compiling XCResultKit CodeCoverage.swift
  remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[4/6] Compiling XCTestHTMLReportCore String+Path.swift
  /private/tmp/xctesthtmlreport-20230114-[77](https://github.com/Homebrew/homebrew-core/actions/runs/3920638949/jobs/6702412645#step:6:78)571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Helpers/ImageHelpers.swift:111:37: error: variable binding in a condition requires an initializer
          guard let tiffRepresentation,
                                      ^
  /private/tmp/xctesthtmlreport-20230114-77571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Models/Activity.swift:77:21: error: variable binding in a condition requires an initializer
          if let type {
                      ^
  /private/tmp/xctesthtmlreport-20230114-77571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Models/TestScreenshotFlow.swift:13:30: error: variable binding in a condition requires an initializer
          guard let activities else {
                               ^
  /private/tmp/xctesthtmlreport-20230114-77571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Helpers/ImageHelpers.swift:117:21: error: cannot infer contextual base in reference to member 'jpeg'
              using: .jpeg,
                     ~^~~~
```

**Comment by tylervick** [comment]
> ```
> [3/5] Compiling XCResultKit CodeCoverage.swift
>   remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[4/6] Compiling XCTestHTMLReportCore String+Path.swift
>   /private/tmp/xctesthtmlreport-20230114-[77](https://github.com/Homebrew/homebrew-core/actions/runs/3920638949/jobs/6702412645#step:6:78)571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Helpers/ImageHelpers.swift:111:37: error: variable binding in a condition requires an initializer
>           guard let tiffRepresentation,
>                                       ^
>   /private/tmp/xctesthtmlreport-20230114-77571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Models/Activity.swift:77:21: error: variable binding in a condition requires an initializer
>           if let type {
>                       ^
>   /private/tmp/xctesthtmlreport-20230114-77571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Models/TestScreenshotFlow.swift:13:30: error: variable binding in a condition requires an initializer
>           guard let activities else {
>                                ^
>   /private/tmp/xctesthtmlreport-20230114-77571-17flzd/XCTestHTMLReport-2.3.0/Sources/XCTestHTMLReportCore/Classes/Helpers/ImageHelpers.swift:117:21: error: cannot infer contextual base in reference to member 'jpeg'
>               using: .jpeg,
>                      ~^~~~
> ```

It looks like this is due a mismatch in the `swift-tools-version` in Package.swift and `--swiftversion` in `.swiftformat`, causing the formatter to create invalid changes in older Swift versions..

I'll create a patch release upstream now

**Comment by chenrui333** [comment]
Sounds good, thanks @tylervick!

**Comment by tylervick** [comment]
#120642 should have the needed changes (though the 11-arm64 check is still queued). Feel free to update this PR to reflect those changes or use that one 🙂

**Comment by chenrui333** [comment]
#120642

**Comment by chenrui333** [comment]
> #120642 should have the needed changes (though the 11-arm64 check is still queued). Feel free to update this PR to reflect those changes or use that one 🙂

yeah, totally! Thanks! 😄

**Comment by chenrui333** [comment]
#120642

**Pull request closed without merging**
