### PR TITLE
zeek 5.0.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Let's see if building this with the new `caf` works. If not we can try dropping the `caf` commits.

**Comment by carlocab** [comment]
```
  /tmp/zeek-20220920-32179-1u7ho3s/auxil/broker/caf-incubator/libcaf_net/src/multiplexer.cpp:591:26: error: no member named 'disposed' in 'caf::sec'
    mgr->handle_error(sec::disposed);
                      ~~~~~^
```
Nope, I don't think it likes the new `caf`.

**Comment by carlocab** [comment]
```
  /tmp/zeek-20220920-46057-c5cj3l/auxil/broker/caf-incubator/libcaf_net/caf/net/multiplexer.hpp:11:10: fatal error: 'caf/action.hpp' file not found
  #include "caf/action.hpp"
           ^~~~~~~~~~~~~~~~
```
Curious. I wonder what version of `caf` they're expecting then.

**Comment by Neverlord** [comment]
> Curious. I wonder what version of `caf` they're expecting then.

Zeek no longer supports external CAF versions. From a user's perspective, CAF is an inaccessible, internal implementation detail. The proper fix is not setting `CAF_ROOT` and have Zeek use its own, bundled version (a fork of CAF that has features not yet available in any mainstream CAF release). The resulting libraries (libbroker) embed CAF in a way that makes it fully opaque, i.e., there is no run-time dependency to any shared CAF library nor do any CAF symbols "leak out".

**Comment by SMillerDev** [comment]
That's contrary to all goals of package managers though. Is there really no way to allow system libraries.

**Comment by Neverlord** [comment]
Not for now. Eventually, the private fork probably becomes obsolete and we can maybe at some point consider following the official CAF release cycle again. However, Zeek actually bundles quite a few libraries internally to have tight control over the versions in use.

**Comment by SMillerDev** [comment]
Then it really shouldn't have been accepted into Homebrew. How do other package managers deal with that?

**Comment by ckreibich** [comment]
Our other packagers keep those dependencies internal to their family of Zeek packages. We feel the correct take here is to treat Zeek's CAF as its own internal library, not as the official CAF — it is not, since we need to make modifications on top of it. We certainly understand the desire to keep things modular. Fwiw, there's currently no other package in Homebrew depending on CAF, so the impact looks minimal.

**Comment by chenrui333** [comment]
zeek 5.1.0 got released now

**Pull request closed without merging**
