### PR TITLE
bullet 3.21

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
> Full audit bullet --online --git --skip-style output
  bullet:
    * The homepage URL https://bulletphysics.org/ is not reachable

Might be just a flacky connection. Re-running.

**Comment by iMichka** [comment]
`dartsim` will need a rev-bump.

**Comment by scpeters** [comment]
`efl` needs a rev-bump too

**Comment by scpeters** [comment]
LGTM aside from the unbottled portions

**Comment by Bo98** [comment]
dartsim isn't bottled on Monterey yet so that's expected.

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
