### PR TITLE
git-annex 8.20201127

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[174 of 649] Compiling Git.DiffTreeItem ( Git/DiffTreeItem.hs, dist/build/git-annex/git-annex-tmp/Git/DiffTreeItem.o )
[175 of 649] Compiling Database.Keys.SQL ( Database/Keys/SQL.hs, dist/build/git-annex/git-annex-tmp/Database/Keys/SQL.o )
<command line>: can't load framework: Cocoa (not found)
cabal: Failed to build git-annex-8.20201116. See the build log above for
details.
```

**Comment by chenrui333** [comment]
```
[174 of 650] Compiling Database.Keys.SQL ( Database/Keys/SQL.hs, dist/build/git-annex/git-annex-tmp/Database/Keys/SQL.o )
<command line>: can't load framework: Cocoa (not found)
cabal: Failed to build git-annex-8.20201127. See the build log above for
details.
```

**Comment by carlocab** [comment]
This is a problem with `ghc`: https://gitlab.haskell.org/ghc/ghc/-/issues/18446

Btw, I think you can do `s/ghc@8.6/ghc@8.8`. That's the compiler version `haskell-stack` will use if you let it choose one to compile with.

**Comment by carlocab** [comment]
This should hopefully be unblocked by https://github.com/Homebrew/homebrew-core/pull/67284

**Comment by carlocab** [comment]
Closed in 94097f99b6144069cdef5636607d5653370b2759.

**Pull request closed without merging**
