### PR TITLE
glpk 5.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Ok, this test is silly. Going to fix that.

**Comment by chenrui333** [comment]
looks like it is not in the main doc page yet?
https://www.gnu.org/software/glpk/

**Comment by carlocab** [comment]
There are no announcements on their main page... the version listed on their page is just an example for signature verification. (It's a version from before 2009.)

**Comment by chenrui333** [comment]
Got you. Sounds good!

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
