### PR TITLE
swftools: remove giflib option

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @fxcoudert

### CODE REVIEW

**Comment by fxcoudert** [comment]
You win by 6 minutes #12188
Although from the documentation, it seems that freetype is required for the same tool as jpeg is required, so if we're going to depend on that we should as well include jpeg (low cost) to make it useful.

**Comment by ilovezfs** [comment]
Will wait for users to request that before adding dependencies.

**Comment by fxcoudert** [comment]
But why was build failing before and not now?

**Comment by ilovezfs** [comment]
Because freetype was installed due to the other things going on in the PR, leading to its opportunistic use, superenv filtering, and :boom:

**Comment by ilovezfs** [comment]
@fxcoudert this is why the superenv filtering is there. We would have ended up with a bottle linked to freetype, but no `depends_on "freetype"` in the formula or any of its dependencies, leading to broken dylib errors for users but not CI.

**Comment by ilovezfs** [comment]
Um ... seems squash and merge decided to remove your authorship somehow. wtf? Sorry

**Pull request merged**
