### PR TITLE
uhd 3.14.1.1

### PR DESCRIPTION
**Pull request by Bo98**
Investigating a possible Catalina build issue I've just been told about. Let's see how the CI goes.

### CODE REVIEW

**Comment by Bo98** [comment]
I have no idea what's going on here.

**Comment by bayandin** [comment]
It seems we can work around it using real path instead of relative (which apparently causes a problem):

```diff
diff --git a/Formula/uhd.rb b/Formula/uhd.rb
index d559098db5..909a34b2ee 100644
--- a/Formula/uhd.rb
+++ b/Formula/uhd.rb
@@ -24,6 +24,11 @@ class Uhd < Formula
   end
 
   def install
+    # https://github.com/Homebrew/homebrew-core/pull/47101
+    inreplace "host/lib/transport/nirio/lvbitx/process-lvbitx.py",
+              "autogen_src_path = os.path.relpath(options.output_src_path) if (options.output_src_path is not None) else os.path.dirname(input_filename)",
+              "autogen_src_path = os.path.realpath(options.output_src_path) if (options.output_src_path is not None) else os.path.dirname(input_filename)"
+
     xy = Language::Python.major_minor_version "python3"
     ENV.prepend_create_path "PYTHONPATH", libexec/"vendor/lib/python#{xy}/site-packages"
```

**Comment by Bo98** [comment]
I did think the use of relative paths was a little odd. Though it doesn't make sense to me how this could possibly only affect Catalina. What has Catalina changed that has broken relative paths?

**Comment by EricFromCanada** [comment]
Probably Catalina’s sectioning off system files into a separate partition: https://eclecticlight.co/2019/10/08/macos-catalina-boot-volume-layout/

**Comment by Bo98** [comment]
Might be related: https://bugs.python.org/issue38295

**Comment by Bo98** [comment]
`python3 -m test -v test_py_compile`

**Comment by bayandin** [comment]
https://github.com/EttusResearch/uhd/issues/313

**Comment by Bo98** [comment]
Also filed FB7467762 since I managed to reproduce this in C.

**Comment by michaelld** [comment]
There are other `os.path.relpath` in that script. Do those also need to be changed? Seems to me that using the absolute path would work cleanly, so why use the relative path? hmmm ...

**Comment by michaelld** [comment]
OK so replacing all `relpath` with `realpath` works for me building UHD public GIT master _not_ in `/tmp`. Can you test / verify that it works for you too?

**Comment by michaelld** [comment]
I'll note that I'm still using Mojave ... but I do have a Catalina build computer setup that I can bring to life if necessary for testing ... just thinking if someone is on the other end here this would be faster ...

**Pull request closed without merging**
