### PR TITLE
crowdin@3 3.0.0

### PR DESCRIPTION
**Pull request by vasyl-khomko**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please do not create a new version of the formula, simply update the existing `crowdin` formula.

**Comment by vasyl-khomko** [comment]
@fxcoudert I created new version of the formula because it not compatible with old version.
New version use new format of configuration file. 
If users run a new version of the formula with an old configuration file, it will not work.

**Comment by SMillerDev** [comment]
Will crowdin keep actively supporting the old version?

**Comment by vasyl-khomko** [comment]
Yes, we keep supporting the old version.

**Comment by fxcoudert** [comment]
@SMillerDev we aim to have versioned formulas only for highly-used formulas, and this one doesn't look likely to be in the top 3000 of https://formulae.brew.sh/analytics/install/90d/ (which is our usual reference point).

**Comment by SMillerDev** [comment]
That's a good point. Closing this as "not up to standards" then

**Pull request closed without merging**
