### PR TITLE
julia 1.7.3

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by pthariensflame** [comment]
Need help correcting the `curl` patch, I think.

**Comment by pthariensflame** [comment]
Can I get “help requested” please?  😰

**Comment by cho-m** [comment]
`curl` fix may have been backported in this release.

- https://github.com/JuliaLang/julia/blob/v1.7.3/stdlib/Downloads.version shows 1.7.3 is using commit b0f23d0ed40cf7c5c5896f957d8163a68dfbc805
- https://github.com/JuliaLang/Downloads.jl/commit/b0f23d0ed40cf7c5c5896f957d8163a68dfbc805 has a bunch of backports including https://github.com/JuliaLang/Downloads.jl/pull/164 
- https://github.com/JuliaLang/Downloads.jl/issues/172 mentions that above PR should have fixed issue.

**Comment by pthariensflame** [comment]
Getting back around to this now!

**Pull request closed without merging**
