### PR TITLE
pcre2 10.42

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
`grantlee` failure looks expected... #117496

**Comment by yurikoles** [comment]
`grantlee` fix is in #118217

**Comment by yurikoles** [comment]
`grantlee` fixed in https://github.com/Homebrew/homebrew-core/pull/118217

**Comment by SMillerDev** [comment]
Yes, already rebased for that

**Comment by p-linnane** [comment]
Rebased and kicking off a run.

**Comment by fxcoudert** [comment]
I'm cancelling the workflow right now, because on Linux it's going to take forever rebuilding Qt from source, and cancelling will allow this https://github.com/Homebrew/homebrew-core/pull/118676 to run earlier and therefore fix the Qt bottle issue on Linux.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
walkmod test failure on osx seems nothing to do with pcre2 update
```
  FATAL [main] - The markup declarations contained or pointed to by the document type declaration must be well-formed. at (-//WALKMOD//DTD:1:3)
  org.xml.sax.SAXParseExceptionpublicId: -//WALKMOD//DTD; systemId: http://www.walkmod.com/dtd/walkmod-1.1.dtd; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.
```

**Comment by p-linnane** [comment]
@chenrui333 https://github.com/Homebrew/homebrew-core/pull/118338#issuecomment-1363846026

**Pull request closed without merging**
