### PR TITLE
pax: new formula

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
This is provided by macOS and will fail the audit because we have to add it the appropriate allowlist.  I'll do that once everything else here is ready to go.  We'll need `pax` as a build time dependency for `eiffelstudio` on Linux.

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Well, it won't build until that change is made (and macOS provides it already)

**Comment by danielnachun** [comment]
It looks like the only way we can make this work is to merge this without the `keg_only` line, then merge https://github.com/Homebrew/brew/pull/13489, and then add the `keg_only` line back in a syntax-only follow up PR.  I've added a comment to the formula so that we know we need to do this.

**Comment by danielnachun** [comment]
I ended up using a different solution to make this keg-only on macOS suggested in https://github.com/Homebrew/brew/pull/13489.  However I will still follow this up with a PR to use the normal `keg_only :provided_by_macos` line instead of putting it in an `on_macos` block.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
