### PR TITLE
cquery: add missing build time dependencies

### PR DESCRIPTION
**Pull request by xu-cheng**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why? It is building fine with system python and without `xz`.

**Comment by xu-cheng** [comment]
A sufficient new python is needed. As it will try to fetch some resource over TLS during the build.

I could make it `depends_on "python@2" if MacOS.version <= : snow_leopard`. However, it seems that it is recommended to use `depends_on "python@2"` in Homebrew now (#26287).

`xz` is needed to extract the resource, which is archived in`.tar.xz` format.

**Comment by ilovezfs** [comment]
>xz is needed to extract the resource, which is archived in.tar.xz format.

That'll be a Linuxbrew problem only, so is not a reason to add a dependency here.

**Comment by xu-cheng** [comment]
> That'll be a Linuxbrew problem only

I did not know that. I thought it is a universal problem. So I will submit this PR to Linuxbrew instead.

**Pull request closed without merging**
