### PR TITLE
ffmpeg 3.2.4

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@zmwangx what's the deal with mpv needing revision bumps on the patch releases? Are they just paranoid and proactively breaking it?

**Comment by zmwangx** [comment]
@ilovezfs 

```
mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.
```

Added in mpv-player/mpv@d057e7a142a327c653f3f0379014567028448b5d half a year ago.

Too tired of "bug reports" from people using older FFmpeg, I guess.

**Comment by ilovezfs** [comment]
I love when reverse dependencies decide to throw the ABI baby out with the bath water.

**Comment by zmwangx** [comment]
It's complicated. FFmpeg has bugs that are being fixed all the time. But to most end users of mpv, when something goes wrong it's not clear where the problem originates — mpv, or FFmpeg, or libass, etc. I assume FFmpeg problems (that have since been fixed) accounted for a significant slice of bogus bug reports.

**Comment by zmwangx** [comment]
Oh wait, this is not about old or not, what am I even talking about... I bow out.

**Comment by ilovezfs** [comment]
The other one that does this is ceres-solver whenever the eigen patch version changes.

**Comment by zmwangx** [comment]
Re ceres-solver: Google Inc. does it, so it must be good practice. 🙈

**Comment by MikeMcQuaid** [comment]
Smells like `mpv` vendoring `ffmpeg` may be a better solution.

**Comment by MikeMcQuaid** [comment]
(er, better long-term solution, happy with this as-is now)

**Comment by zmwangx** [comment]
> Smells like mpv vendoring ffmpeg may be a better solution.

Kinda confused. In that case the resource needs to be updated with each FFmpeg release, which is even harder. What's the advantage?

**Comment by MikeMcQuaid** [comment]
I don't think it does need to be updated with each FFmpeg release unless there's security vulnerabilities that manifest in `mpv`.

**Comment by zmwangx** [comment]
Oh okay (seems like I can't see through the obvious today...).

**Comment by ilovezfs** [comment]
:rocket: :tada: :confetti_ball: :100: :cake:

**Pull request closed without merging**
