### PR TITLE
hledger 1.16.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
19:36:25 Downloading  hledger-1.16
19:36:25 Downloading  hledger-web-0.18.2
19:36:25 Downloaded   hledger-1.16
19:36:25 Starting     hledger-1.16
19:36:25 Downloaded   hledger-web-0.18.2
19:36:25 Starting     hledger-web-0.18.2
19:36:25 Building     hledger-1.16
19:36:25 Building     hledger-web-0.18.2
19:36:25 Failed to install hledger-web-0.18.2
19:36:25 Build log ( /private/tmp/hledger-20191202-87536-131q3v3/hledger-1.16/.cabal-sandbox/logs/ghc-8.8.1/hledger-web-0.18.2-9y5WrHEQZkLKlFo69PmTMu.log ):
19:36:25 cabal: Entering directory '/private/tmp/cabal-tmp-97776/hledger-web-0.18.2'
19:36:25 Configuring hledger-web-0.18.2...
19:36:25 clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
19:36:25 clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
19:36:25 clang: warning: argument unused during compilation: '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
19:36:25 Preprocessing library for hledger-web-0.18.2..
19:36:25 Building library for hledger-web-0.18.2..
19:36:25 [1 of 8] Compiling Hledger.Web.Import ( Hledger/Web/Import.hs, dist/dist-sandbox-c320e478/build/Hledger/Web/Import.o )
19:36:25 
19:36:25 Hledger/Web/Import.hs:9:1: error:
19:36:25     Could not load module ‘Prelude’
19:36:25     It is a member of the hidden package ‘base-4.13.0.0’.
19:36:25     Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
19:36:25     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
19:36:25   |
19:36:25 9 | import Prelude hiding (writeFile, readFile, putStrLn)
19:36:25   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:36:25 
19:36:25 Hledger/Web/Import.hs:10:1: error:
19:36:25     Could not load module ‘Data.Monoid’
19:36:25     It is a member of the hidden package ‘base-4.13.0.0’.
19:36:25     Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
19:36:25     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
19:36:25    |
19:36:25 10 | import Data.Monoid (Monoid (mappend, mempty, mconcat))
19:36:25    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:36:25 
19:36:25 Hledger/Web/Import.hs:11:1: error:
19:36:25     Could not load module ‘Control.Applicative’
19:36:25     It is a member of the hidden package ‘base-4.13.0.0’.
19:36:25     Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
19:36:25     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
19:36:25    |
19:36:25 11 | import Control.Applicative ((<$>), (<*>), pure)
19:36:25    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:36:25 
19:36:25 Hledger/Web/Import.hs:12:1: error:
19:36:25     Could not load module ‘Data.Text’
19:36:25     It is a member of the hidden package ‘text-1.2.4.0’.
19:36:25     Perhaps you need to add ‘text’ to the build-depends in your .cabal file.
19:36:25     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
19:36:25    |
19:36:25 12 | import Data.Text (Text)
19:36:25    | ^^^^^^^^^^^^^^^^^^^^^^^
19:36:25 cabal: Leaving directory '/private/tmp/cabal-tmp-97776/hledger-web-0.18.2'
19:36:25 Completed    hledger-1.16
19:36:25 cabal: Error: some packages failed to install:
19:36:25 hledger-web-0.18.2-9y5WrHEQZkLKlFo69PmTMu failed during the building phase.
19:36:25 The exception was:
19:36:25 ExitFailure 1
19:36:25 
19:36:25

**Comment by simonmichael** [comment]
@chenrui333, thanks for working on this. I see the changelog missed it, but hledger-web 1.16.1 should fix this.

**Comment by simonmichael** [comment]
Though.. also I see it's trying to build the seven year old hledger-web-0.18.2. I guess cabal-install is being used. I don't know if you have control over this, but when using cabal you always want specify the desired versions or it may try too hard to get something, anything installed.

**Comment by chenrui333** [comment]
@simonmichael, Looks like it works fine now. Gonna to merge this! Thanks for taking a peek.

**Pull request closed without merging**
