### PR TITLE
cfitsio: fix lack of --enable-reentrant flag

### PR DESCRIPTION
**Pull request by devonhollowood**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This adds the `--with-reentrant` build option, which builds `cfitsio` with the `--enable-reentrant` configuration option enabled. This enables support for concurrency in `cfitsio`. See [here](https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node15.html) for details.

### CODE REVIEW

**Comment by fxcoudert** [comment]
What would be the downside to _always_ build `cfitsio` with `--enable-reentrant`?

**Comment by devonhollowood** [comment]
@fxcoudert looking through the `cfitsio` source, it seems like the cost is that there is some additional overhead (locking and unlocking a mutex) when accessing FITS files. That seems like a relatively small cost, so maybe it makes sense to have `--enable-reentrant` be the default and supply a `--without-reentrant` build flag for people who want to opt out of that overhead?

**Comment by devonhollowood** [comment]
I went ahead and modified this to make `--enable-reentrant` the default. I can always revert that though if you want.

**Comment by ilovezfs** [comment]
Please revert it back to being the upstream default.

**Comment by devonhollowood** [comment]
@ilovezfs Done.

**Comment by ilovezfs** [comment]
Thanks for your contribution to Homebrew, @devonhollowood!

**Pull request merged**
