### PR TITLE
rav1e 0.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~ [test resource]

### CODE REVIEW

**Comment by barrbrain** [comment]
Looking at the CI logs, there are quite few errors of similar form:
```
 dyld: Library not loaded: /usr/local/opt/rav1e/lib/librav1e.0.4.0.dylib
  Referenced from: /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib
  Reason: image not found
```

It appears that dependent formulae are linked to the precise version of librav1e. Point-release updates should be common scenario for a distribution like Homebrew. How are point-releases like this handled for other formulae?

**Comment by SMillerDev** [comment]
> It appears that dependent formulae are linked to the precise version of librav1e. Point-release updates should be common scenario for a distribution like Homebrew. How are point-releases like this handled for other formulae?

If upstream uses that to link to a library we won't change it so that means all dependent formulae with this issue need a rebuilt and/or an update

**Comment by barrbrain** [comment]
> If upstream uses that to link to a library we won't change it so that means all dependent formulae with this issue need a rebuilt and/or an update

I compared with bottles from linuxbrew and I guess this comes down to a difference in linking on Mac vs Linux. (The structure of symbolic links appears equivalent.) It was my first time to observe this so I was a little surprised.

**Comment by carlocab** [comment]
The issue is this:
```
==> brew linkage --test ffmpeg
==> FAILED
Broken dependencies:
  /opt/homebrew/opt/rav1e/lib/librav1e.0.4.0.dylib (rav1e)
```
`ffmpeg` links with `librav1e.0.4.0.dylib` which obviously no longer exists. I guess it might be better for `ffmpeg` to link with `librav1e.0.4.dylib` (if it exists) instead, but that doesn't seem to be how `ffmpeg`'s build system works. (Or perhaps there's a problem with `librav1e`'s install name).

**Review by Bo98 — APPROVED** [review]

**Comment by barrbrain** [comment]
Thank you for the insight. I'll take a closer look at `rav1e`, `cargo-c` and `ffmpeg`'s build system. Maybe it is possible we can avoid the revision bump in future with some upstream changes.

**Comment by carlocab** [comment]
Thanks, @barrbrain. That would help a lot. Thinking about it more, I suspect looking at `librav1e`'s install name might be the likeliest place to fix this.

**Pull request closed without merging**
