### PR TITLE
microplane 0.0.26

### PR DESCRIPTION
**Pull request by benwaffle**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can we remove `GOPATH`? It will be needed when go1.16 is released anyway

**Comment by benwaffle** [comment]
The repo still uses dep, not go modules, so I think it needs GOPATH

**Comment by carlocab** [comment]
I think adding `ENV["GO111MODULE"] = "auto"` will allow this to build on ARM

**Comment by fxcoudert** [comment]
@carlocab `dep` didn't bottle for ARM

**Comment by carlocab** [comment]
Oh whoops. I don't know how you even keep track of this anymore 😅

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
