### PR TITLE
meilisearch 0.10.1

### PR DESCRIPTION
**Pull request by curquiza**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by chenrui333** [comment]
audit failure with prerelease tag.

**Comment by SMillerDev** [comment]
@curquiza this is a pre-release. @mislav can you make the action check if that's the case (and not send the update)

**Comment by curquiza** [comment]
@SMillerDev @chenrui333 It's not a pre-release, we've just released the `0.10.1` today => https://github.com/meilisearch/MeiliSearch/releases/tag/v0.10.1

**Comment by SMillerDev** [comment]
When I just tagged it said "pre-release"

**Comment by chenrui333** [comment]
I think it is fine now, re-triggering the build.

**Comment by Bo98** [comment]
Yeah, I also saw it was tagged as a pre-release at first. It's now not so I'll merge this.

**Comment by mislav** [comment]
@SMillerDev The documentation for my action includes a bit about skipping prereleases

```yaml
- uses: mislav/bump-homebrew-formula-action@v1
  if: "!contains(github.ref, '-')" # skip prereleases
```

This needs to be explicitly configured since from the tag name alone the action can't determine if a tag is a prerelease or not (different projects, different naming conventions).

**Pull request closed without merging**
