### PR TITLE
gnutls 3.4.16

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

Shh, I'm not here. I get twitchy about crypto stuff not being updated, don't judge me.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I may have to insist you let me fix this so that you're not back to battling the weak symbols again.

**Comment by DomT4** [comment]
Heh, well, if you insist 😉. The branch is open to maintainer edits if you want to fix it on top of my commit, but if you want to do it yourself afresh feel free to punt this PR.

**Comment by ilovezfs** [comment]
Will do. On my phone at the moment so I'll not meddle with it just yet.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
:green_apple: now that https://github.com/Homebrew/homebrew-core/pull/6041 is merged.

**Comment by ilovezfs** [comment]
@DomT4 thank you for your contribution to Homebrew! :tada:

**Comment by DomT4** [comment]
Thanks ILZ ❤️

**Pull request closed without merging**
