### PR TITLE
openapi-generator: pin to Java 11

### LINKED ISSUE #15219: brew installed v6.5.0 generate python error
ruby is OK
image

but change to python, it report errors:

```
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/tmp/test2) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python' is considered stable.
[main] INFO  o.o.c.l.AbstractPythonCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractPythonCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/tmp/test2) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.c.languages.PythonClientCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.languages.PythonClientCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.languages.PythonClientCodegen - generateAliasAsModel is hard coded to true in this generator. Alias models will only be generated if they contain validations or enums
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'ApiResponse'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:569)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:926)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: com.github.jknack.handlebars.HandlebarsException: model.handlebars:3:3: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @b6ba78c
    model.handlebars:3:3
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:181)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:175)
        at com.github.jknack.handlebars.context.FieldValueResolver$FieldMember.setAccessible(FieldValueResolver.java:150)
        at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
        at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:54)
        at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:199)
        at com.github.jknack.handlebars.internal.path.PropertyPath.eval(PropertyPath.java:52)
        at com.github.jknack.handlebars.Context$PathExpressionChain.next(Context.java:361)
        at com.github.jknack.handlebars.Context$PathExpressionChain.eval(Context.java:381)
        at com.github.jknack.handlebars.Context.get(Context.java:618)
        at com.github.jknack.handlebars.internal.Partial.override(Partial.java:253)
        at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:226)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:113)
        at org.openapitools.codegen.templating.HandlebarsEngineAdapter.compileTemplate(HandlebarsEngineAdapter.java:92)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1072)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1059)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:408)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:560)
        ... 4 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @b6ba78c
```

my os is :
image

I installed it by homebrew and the version is : 6.5.0

### PR DESCRIPTION
**Pull request by SalvatoreT**
It's currently using whatever is the latest which seems to make it unhappy.

Closes https://github.com/OpenAPITools/openapi-generator/issues/15219

cc @spacether

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by spacether** [comment]
@wing328 can you review this too?

**Review by carlocab — COMMENTED** [review]
Thanks! Can we also update the `test` block to add a test case that fails with the wrong version of Java?

When you do that, please amend your existing commit (instead of adding a new one) and change the commit message so that it starts with the formula name, e.g:
```
openapi-generator: pin to Java 11
```

**Comment by SalvatoreT** [comment]
@carlocab, thanks for the quick feedback!

I've (1) updated the commit message and (2) add a test case which passes on Java 11 but not Java 20. Please let me know if this PR needs anything else!

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by wing328** [comment]
@SalvatoreT can you please pin it to Java 8 instead, which is the minimal Java version supported by openapi generator 6.x? Thanks.

**Comment by SalvatoreT** [comment]
Hey @wing328, I first tried to pin the formula to Java 8! 

Unfortunately, there's no Apple Silicon support for [OpenJDK Java 8](https://formulae.brew.sh/formula/openjdk@8). 
<p align="center">
  OpenJDK 8 supports only Intel silicon
</p>

[OpenJDK Java 11](https://formulae.brew.sh/formula/openjdk@11) is the next lowest long-term support version, so that's what I went with.
<p align="center">
   OpenJDK 11 supports both Intel and Apple silicon
</p>

Please let me know if this reasoning satisfies you or if you have another suggestion for how to proceed.

**Comment by SalvatoreT** [comment]
I took a quick spike on adding ARM64 support to the Java 8 package (https://github.com/Homebrew/homebrew-core/pull/131535). Let's hope that works. 🤞🏼

**Comment by wing328** [comment]
👌 

Thanks for the explanation.

FYI. We've just merged a PR to default OpenAPI Generator to JDK11 instead of JDK8 as part of the upcoming v7.0.0 release so it's fine if we can't find an easy way to support JDK8 in this brew formula.

**Pull request merged**
