### PR TITLE
v8 7.3.492.23

### PR DESCRIPTION
**Pull request by chrmoritz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
 Updating to the newest `v8` (following today's major Chrome stable release).

### CODE REVIEW

**Comment by chrmoritz** [comment]
Looks like `v8` 7.3.492.22 didn't get correctly tagged upstream. That's why [they retagged it](https://chromium.googlesource.com/v8/v8/+log/branch-heads/7.3) as 7.3.492.23 with zero code change. So we've to use this instead.

**Comment by fxcoudert** [comment]
All tests passed, but Sierra node had a cleanup problem.
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @chrmoritz

**Comment by jeroen** [comment]
I just found out that this new version of V8 installs and links another version of libc++ on the system, which resulted in all kind of linking errors for unrelated applications. Is this expected?

**Pull request closed without merging**
