### PR TITLE
lacework-cli:  updates

### PR DESCRIPTION
**Pull request by afiune**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This PR is refactoring the Lacework CLI formula to match the company's formula located at https://github.com/lacework/homebrew-tap/blob/main/Formula/lacework-cli.rb

A few notable changes are:
1. Avoid building from source and instead, use prebuilt binaries released by Lacework
1. Do not test via the command `lacework configure list` since upgrades will have the CLI configured already and won't have the error `No configuration file found`
1. Removed `livecheck` mainly because we will point to GH releases

Please, let me know if this refactor complies with the contributing guidelines to Homebrew.

### CODE REVIEW

**Comment by p-linnane** [comment]
Hi @afiune. Thanks for stopping by. I am the author of the `lacework-cli` formula for homebrew-core.

A few points:

1. Everything in homebrew-core is required to build from source, so we can't accept prebuilt binaries.
2. The `test` block is just to verify that the `lacework` binary built successfully. In that scenario we expect there is no configuration (this is mainly for our CI).
3. We added the `livecheck` block because we've noticed sometimes tags are created and it takes a while for an associated GitHub release to be created. This has caused premature bumping of the formula version.

Please let me know if this makes sense, and happy to answer any additional questions. If you're interested in redirecting users of the existing Lacework tap to homebrew-core, that's also something I can help you with. Just let me know. Thanks!

**Comment by afiune** [comment]
Two follow up questions @p-linnane 
1. You mentioned that everything in homebrew-core has to be build from source, are there any exceptions? where can I read more about these guidelines?
2. You also mentioned that If we're interested in redirecting users of the existing Lacework tap to homebrew-core you could help us, what does that process look like? Could you describe it so we can talk internally about it?

**Comment by p-linnane** [comment]
1. Here are the guidelines for homebrew-core: https://docs.brew.sh/Acceptable-Formulae. Building from source is one of our core requirements for homebrew-core, so there wouldn't be a way to get an exception.
2. Migration is simple, and seamless for your existing users. You can use a `tap_migrations.json` file to redirect existing users. Here is an example of a tap I recently helped migrate to homebrew-core as an example: https://github.com/orogene/homebrew-tap

**Comment by afiune** [comment]
@p-linnane Genious!



- I'll close this up for now until I know what next steps we want to take.

**Pull request closed without merging**
