### PR TITLE
afsctool: update to use maintained fork

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Since the original artifact is no longer downloadable, switch the formula
to a maintained fork

relates to #88329

### CODE REVIEW

**Comment by chenrui333** [comment]
Raised a question in the fork repo and ask for some feedback.

**Comment by RJVB** [comment]
@brkirch has requested that official packaging of my fork use a different name to distinguish it from his original product. I provide the `NEW_DRIVER_NAMES` build option for that (invoke CMake with `-DNEW_DRIVER_NAMES=ON`).

I don't see what other feedback I could give; I don't use HB.

**Comment by chenrui333** [comment]
Oh, @brkirch, hi, can you take a look at the google docs export? As it impacts the current Monterey release.

@RJVB that sounds like we should make another formula to use your fork?

**Comment by RJVB** [comment]
***@***.*** that sounds like we should make another formula to use your fork?

I have no idea how HB policies are for this. I guess you might, if they have the principle that the formula name must match the name of the project.

**Comment by carlocab** [comment]
I'm fine with switching to the fork. We should probably change the `homepage` though.

**Pull request closed without merging**
