### PR TITLE
boost and friends 1.82

### PR DESCRIPTION
**Pull request by SMillerDev**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
@SMillerDev what's the usual level of testing for merging openjdk updates? Do we need all dependents to build clean?

**Comment by SMillerDev** [comment]
Since boost will conflict with icu4c, I'm going to run https://github.com/Homebrew/homebrew-core/pull/128958 first

**Comment by SMillerDev** [comment]
Seems https://github.com/Homebrew/homebrew-core/actions/runs/4924672905/jobs/8797987482 can't post to PRs anymore

**Comment by SMillerDev** [comment]
`tfel` I'll fix, the other failures are pre-existing. We'll need `CI-no-fail-fast` indeed

**Comment by SMillerDev** [comment]
Okay, that should be the last ones.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
On all macOS runners:

```
Error: 3 failed steps!
brew fetch --retry avro-cpp --build-bottle --force
brew install --verbose --build-bottle avro-cpp
brew install --verbose --build-bottle pokerstove
```

**Comment by SMillerDev** [comment]
Those are pre-existing

**Comment by fxcoudert** [comment]
```
Error: Failure while executing; `/usr/bin/env PATH=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin unzip -qq -o /github/home/.cache/Homebrew/downloads/1b2ba6e7187da3e87752336e6e0ae398aee5d70eb349c812287393e6f3ce3dab--artifact.zip -d /tmp/d20230604-265-tt0lw9` exited with 50. Here's the output:
/tmp/d20230604-265-tt0lw9/vineyard--0.14.8_1.x86_64_linux.bottle.tar.gz:  write error (disk full?).  Continue? (y/n/^C) 
warning:  /tmp/d20230604-265-tt0lw9/vineyard--0.14.8_1.x86_64_linux.bottle.tar.gz is probably truncated
```

**Comment by fxcoudert** [comment]
Merge workflow at https://github.com/Homebrew/homebrew-core/actions/runs/5169092093 is hanging

**Comment by SMillerDev** [comment]
It was cancelled since then. Rebasing now. 😞

**Review by carlocab — APPROVED** [review]
I think this should be good after this re-run. 🤞

**Comment by fxcoudert** [comment]
All ARM runners get something like:

```
==> Downloading https://api.github.com/repos/Homebrew/homebrew-core/actions/artifacts/743973194/zip
curl: (56) Recv failure: Connection reset by peer
Error: Download failed: https://api.github.com/repos/Homebrew/homebrew-core/actions/artifacts/743973194/zip
```

**Review by carlocab — APPROVED** [review]
Builds are all 🍏

**Pull request merged**
