### PR TITLE
node@16 16.13.1

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like they backported the buggy commit: https://github.com/nodejs/node/commit/f778fa230ba544d2605d2fbb6ef94ed8bf887770. There's a PR upstream to fix it: https://github.com/nodejs/node/pull/40965.

I'm testing out that patch on Node 17: #89459

**Comment by carlocab** [comment]
We can probably use the same patch as the one for Node 17 here.

**Comment by derrabus** [comment]
The patch works fine locally. Let's see what the CI says. 🙂

**Comment by derrabus** [comment]
The build has passed on ARM but was cancelled on amd64 everywhere. 😢

**Comment by Bo98** [comment]
Oops, I'll restart it.

**Comment by derrabus** [comment]
Thanks!

**Comment by derrabus** [comment]
All green! 🎉

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
