### PR TITLE
Add Niels Provos somewhat ancient ScanSSH for finding SSHes

### PR DESCRIPTION
**Pull request by barn-stripe**
The patch for configure is necessary as the project was last touched in 2005, so I don't believe they're taking patches.

### CODE REVIEW

**Comment by barn-stripe** [comment]
And yeah, needs more work ):

**Comment by barn-stripe** [comment]
Added a "fix" for the setrlimit() noise.

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/scanssh/2.1/bin/scanssh -V
dyld: Library not loaded: /usr/local/opt/libevent/lib/libevent-2.1.6.dylib
  Referenced from: /usr/local/Cellar/scanssh/2.1/bin/scanssh
  Reason: image not found
```

**Comment by fxcoudert** [comment]
Latest release is dated 2005-03-05, and it doesn't compile without a patch 😧

**Comment by barn-stripe** [comment]
I did a
`brew uninstall --ignore-dependencies libevent scanssh`
and then tried
`brew install -vd scanssh && brew test scanssh`
And that worked for me.

does otool -L show the library missing on it?

**Comment by ilovezfs** [comment]
@barn-stripe This will be a better match for a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap), since there's no active upstream project. But thank you for the PR nonetheless, and we look forward to your next contribution!

**Pull request closed without merging**
