### PR TITLE
Azure CLI 2.27.1

### PR DESCRIPTION
**Pull request by azclibot**
The latest release of the Azure CLI

### CODE REVIEW

**Comment by cho-m** [comment]
Noting that we should check for python 3.9 support and possibly combine with #78022 if available.

**Comment by jiasli** [comment]
We currently have no bandwidth working on the migration to Python 3.9. Could you please merge this PR for now?

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/pull/18224 has been merged, please kindly help merge https://github.com/Homebrew/homebrew-core/pull/78022 as well. Thanks!

**Comment by carlocab** [comment]
This will need rebasing once #78022 is merged.

**Review by carlocab — APPROVED** [review]
Never mind; rebasing is no longer necessary.

**Comment by jiasli** [comment]
Thanks a lot @carlocab! Appreciate your great help! 😊

**Pull request closed without merging**
