### PR TITLE
vim 8.0.1171

### PR DESCRIPTION
**Pull request by Azakur4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for the PR. We're only upgrading this every 50 commits now, though.

**Comment by Azakur4** [comment]
oh sorry but vim have a problem with terminal in the actual version in homebrew and mac OS High Sierra was resolved in https://github.com/vim/vim/releases/tag/v8.0.1166

**Comment by Azakur4** [comment]
i was waiting for an update for the homebrew version :( was for that i send a PR

**Comment by ilovezfs** [comment]
@Azakur4 ah OK. I will make an exception then :)

**Comment by Azakur4** [comment]
ty 👍

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @Azakur4! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
