### PR TITLE
opencv: Add options for python, python3, and tbb

### PR DESCRIPTION
**Pull request by papr**
- python and python3 become recommended options
- tbb becomes an optional option

### CODE REVIEW

**Comment by ilovezfs** [comment]
Sorry we've deliberately kept this formula option free but thanks nonetheless for the PR.

**Comment by papr** [comment]
Oh ok, I was wondering why the migration did not include the options anymore. May I ask for the reasoning behind this?

**Comment by ilovezfs** [comment]
options -> source builds
source builds -> build failures
build failures -> issue reports
issue reports -> maintainer time spent on things affecting a small minority of users

**Comment by papr** [comment]
I understand. Thank you for elaborating on this issue.

**Pull request closed without merging**
