### PR TITLE
libidn 2.0.2

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

An alternative implementation of https://github.com/Homebrew/homebrew-core/pull/12885. Opening here so @ilovezfs & @MikeMcQuaid can keep track of how things are going. Feel free to tag with the `Do Not Merge` tag for now.

### CODE REVIEW

**Comment by DomT4** [comment]
Haven't forgotten this. Think upstream accidentally oversold how drop-in compatible these two versions of `libidn` would actually be in practice, but I will sink some more time into this soonish.

**Comment by ilovezfs** [comment]
Which formulae only work with v2?

**Comment by DomT4** [comment]
curl & wget at this point. Maybe there's another, but off the top of my head curl & wget moved over completely without retaining support for the older version.

**Comment by ilovezfs** [comment]
So far it's looking like they jumped the gun.

**Comment by MikeMcQuaid** [comment]
Yeh, `libidn@2` smells like a better option at this point.

**Comment by ilovezfs** [comment]
I'm not even sure we should do that.

**Comment by MikeMcQuaid** [comment]
@ilovezfs 👍 I mean if we did add the option back

**Pull request closed without merging**
