### PR TITLE
Qt 5.8

### PR DESCRIPTION
**Pull request by frederikvannoote**
Add Qt 5.8 again.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I really do not think we should be adding yet another qt version to Homebrew. Can you explain why you need this?

**Comment by frederikvannoote** [comment]
I'm working on a software which runs on Linux, Mac and Windows. I would like to keep the versions equal on the 3 platforms.
I'm using brew to control my environment on OSX for developer and CI environments (Travis CI).
To speed the preparation of my Travis environment up (run every build attempt), it would benefit from downloading 5.8 from the bottles.
We were using up to yesterday the 5.8 version, but this suddenly got removed in benefit of the 5.9. I find it a bit strange to just remove versions. (5.7 is still present though). I don't understand the policy on this.
If not possible to have 5.8, I can jump directly to 5.9 for OSX only (but less beneficial).

**Comment by MikeMcQuaid** [comment]
> I would like to keep the versions equal on the 3 platforms.

Can you explain why you would like to do this? Are there specific, breaking API changes, for instance?

**Comment by frederikvannoote** [comment]
In a regulated environment, it is important to use the same library on every OS so we can trust the library has the same functionality and behaviour.

**Comment by MikeMcQuaid** [comment]
Ok, cool. Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!

**Pull request closed without merging**
