### PR TITLE
python 3.8: migrate independent formulae

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR migrates to `python@3.8` independent formulae which:
- depends only on `python`
- doesn't have any depending formulae
- uses `virtualenv_install_with_resources` for installation
 
Ref: https://github.com/Homebrew/homebrew-core/issues/47274

### CODE REVIEW

**Comment by bayandin** [comment]
I hope `[skip ci]` works as expected 👀

**Comment by fxcoudert** [comment]
```
brew-test-bot.mojave.test bumpversion
brew-test-bot.mojave.test peru
brew-test-bot.mojave.test pyinstaller
brew-test-bot.mojave.install --build-bottle snakemake
brew-test-bot.mojave.test stormpath-cli
brew-test-bot.mojave.install ./tox--3.14.1_1.mojave.bottle.tar.gz
```

**Comment by bayandin** [comment]
- `bumpversion` — for me it works locally, let's try one more time
- `peru` — Looks like it calls python3 interpreter directly; dropped from the PR for now
- `pyinstaller` — added patch
- `snakemake` — doesn't support Python 3.8 because of resource dependency `datrie` which doesn't support Python 3.8; dropped from the PR
- `stormpath-cli` — deleted formula in #48350
- `tox` — fixed postinstall and test

**Comment by fxcoudert** [comment]
`pyinstaller` says:
```
ValueError: script '/usr/local/Cellar/pyinstaller/3.5_1/libexec/lib/python/site-packages/easy_install.py' not found
```

**Comment by bayandin** [comment]
> I recommend merging everything except `bumpversion` and `pyinstaller`, rather than rerun the whole thing again. Let me know if you're okay with that, and I can do it.

 Sounds good to me, let's do it.
Thanks @fxcoudert!

**Comment by fxcoudert** [comment]
It is done.

**Comment by fxcoudert** [comment]
For reference: I merged everything with `brew pull --bottle 48323`, then rebased to remove the 4 unwanted commits (`bumpversion`, `pyinstaller`, and their two bottle commits), then logged into bintray to delete the `bumpversion` and `pyinstaller` bottles (so they won't be a problem later, when we actually bump revision on these formulas).

**Pull request closed without merging**
