### PR TITLE
vegeta 7.0.1

### PR DESCRIPTION
**Pull request by tsenart**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
What happened to using a Makefile or build shell script?

**Comment by tsenart** [comment]
Creating a formula for goreleaser (vegeta’s release tool) in Homebrew core proved to take longer than I currently have available.

If you think it’s still better to have a Makefile even if used only with Homebrew, let me know.

**Comment by ilovezfs** [comment]
@tsenart a gift https://github.com/Homebrew/homebrew-core/pull/28188

**Comment by tsenart** [comment]
Thanks a lot @ilovezfs. I’ll change this PR to make use of it once it’s merged!

**Comment by ilovezfs** [comment]
`goreleaser` shipped.

**Comment by tsenart** [comment]
I just found out that there's not way to select a single architecture, OS pair with flags or environment variables with goreleaser. So the build step would be building windows, freebsd, linux and macOS versions for multiple architectures. I don't think this is worth it.

**Comment by tsenart** [comment]
I'll add a Makefile to a new release and bump the release number here.

**Comment by tsenart** [comment]
Superseded by #28193

**Pull request closed without merging**
