### PR TITLE
apg: migrate to boneyard

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew boneyard-formula-pr` because upstream is gone.

### CODE REVIEW

**Comment by jzaleski** [comment]
It looks like the original location the the referenced `Formula` is gone. I assume that is why this was migrated to the boneyard?

I have uploaded a patched for OSX version here: http://files.jzaleski.com/apg-2.2.3-osx.tar.gz -- I'd love to have it available through `brew` again.. @ilovezfs can you or someone else help me w/ this? I have never added a formula.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/pull/18111

**Comment by jzaleski** [comment]
Thank you for the quick response. Would you recommend I create my own tap/formula then?

**Comment by ilovezfs** [comment]
Yeah. Someone really should fork that project …

**Comment by jzaleski** [comment]
Followed the tap-guide and created: https://github.com/jzaleski/homebrew-jzaleski

---

For those interested in `apg` please `tap` the following:

```bash
brew tap jzaleski/homebrew-jzaleski
```

And install away:

```bash
brew install apg
```

**Pull request merged**
