### PR TITLE
starship 0.9.1

### PR DESCRIPTION
**Pull request by matchai**
Created with `brew bump-formula-pr`.

---

Automated release pull request using continuous integration.

### CODE REVIEW

**Comment by Moisan** [comment]
```
==> /usr/local/Cellar/starship/0.9.1/bin/starship module char
thread 'main' panicked at 'Unknown module: char', src/modules/mod.rs:38:14
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: starship: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<101>.
```

**Comment by matchai** [comment]
@Moisan The test has been updated to work with the latest version.

**Comment by Moisan** [comment]
Thanks! Could you squash your commit together with the original commit message (`starship 0.9.1`).

**Comment by matchai** [comment]
Done! 😄

**Pull request closed without merging**
