### PR TITLE
vgrep 2.3.3 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by yermulnik** [comment]
Apologies for resurrecting the old issue.
I'm not very familiar with Homebrew internals hence asking for assistance: how do I add Linux bottle support to this formulae?

**Comment by dawidd6** [comment]
Test the build locally. Open a PR if the build fails and changes are needed, if not then open a PR too but add a comment or something and we'll iterate from there.

**Comment by yermulnik** [comment]
Thanks
> open a PR too but add a comment or something and we'll iterate from there.

A `PR` or an `Issue`? :confused:

**Comment by yermulnik** [comment]
The `brew install --build-from-source vgrep` worked for me just fine on Linux x86_64

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/1418452665

**Comment by dawidd6** [comment]
Something's wrong with the test.

**Comment by yermulnik** [comment]
@dawidd6 I pinged `vgrep`'s repo with an ask to take a look: https://github.com/vrothberg/vgrep/issues/90

**Comment by yermulnik** [comment]
@dawidd6 How do I repro the behavior from https://github.com/Homebrew/homebrew-core/actions/runs/1418452665 ?

On my laptop it builds and passes test just fine:
```
> brew reinstall -s vgrep
==> Downloading https://github.com/vrothberg/vgrep/archive/v2.5.5.tar.gz
==> Downloading from https://codeload.github.com/vrothberg/vgrep/tar.gz/v2.5.5
# #=O#- #
==> Reinstalling vgrep
==> make release
==> make install PREFIX=/home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5
✔  /home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5: 6 files, 3.8MB, built in 3 seconds

> brew test vgrep
==> Testing vgrep
==> /home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5/bin/vgrep -w Homebrew --no-less .
```

**Comment by yermulnik** [comment]
Could you please add `-d` to `vgrep` command so that debug output is written to the job log?
```patch
diff --git a/Formula/vgrep.rb b/Formula/vgrep.rb
index 885d9f88602..fbf9651fb7a 100644
--- a/Formula/vgrep.rb
+++ b/Formula/vgrep.rb
@@ -31,7 +31,7 @@ class Vgrep < Formula

   test do
     (testpath/"test.txt").write "Hello from Homebrew!\n"
-    output = shell_output("#{bin}/vgrep -w Homebrew --no-less .")
+    output = shell_output("#{bin}/vgrep -d -w Homebrew --no-less .")
     assert_match "Hello from \e[01;31m\e[KHomebrew\e[m\e[K!\n", output
   end
 end
```

**Comment by dawidd6** [comment]
Maybe try in our docker container `homebrew/ubuntu16.04:master`

**Comment by yermulnik** [comment]
It works just fine inside this container :thinking: 
```
> docker run -ti homebrew/ubuntu16.04:master /bin/bash
Unable to find image 'homebrew/ubuntu16.04:master' locally
master: Pulling from homebrew/ubuntu16.04
58690f9b18fc: Pull complete
b51569e7c507: Pull complete
da8ef40b9eca: Pull complete
fb15d46c38dc: Pull complete
d60ae4ac0c2d: Pull complete
6be220c4db90: Pull complete
15fd6094a5e6: Pull complete
Digest: sha256:637546298d3299d8a840b7bba3b294fc648077a1e809ba7e5ad3d782ed9832e4
Status: Downloaded newer image for homebrew/ubuntu16.04:master
linuxbrew@51257e5e4171:~$ brew install -s vgrep
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.17.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:aa5fbcd2c12be4e08d5edbcbb5eb8a8859c48ecd036c697d2d8
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:aa5fbcd2c12be4e08d5edbcbb5eb8a8
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go-md2man/manifests/2.0.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go-md2man/blobs/sha256:8b39e17cacacb31eecfc3412dd251b536c717384c463
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:8b39e17cacacb31eecfc3412dd251b5
######################################################################## 100.0%
==> Downloading https://github.com/vrothberg/vgrep/archive/v2.5.5.tar.gz
==> Downloading from https://codeload.github.com/vrothberg/vgrep/tar.gz/v2.5.5
######################################################################## 100.0%
==> Installing dependencies for vgrep: go and go-md2man
==> Installing vgrep dependency: go
==> Pouring go--1.17.2.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/go/1.17.2: 10,810 files, 537.4MB
==> Installing vgrep dependency: go-md2man
==> Pouring go-md2man--2.0.1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/go-md2man/2.0.1: 6 files, 2.0MB
==> Installing vgrep
==> make release
==> make install PREFIX=/home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5
🍺  /home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5: 6 files, 3.8MB, built in 6 seconds
linuxbrew@51257e5e4171:~$ brew test vgrep
Warning: test is a developer command, so
Homebrew's developer mode has been automatically turned on.
To turn developer mode off, run brew developer off

==> Testing vgrep
==> /home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5/bin/vgrep -w Homebrew --no-less .
linuxbrew@51257e5e4171:~$
```
Anything else I can try and help with?

**Comment by yermulnik** [comment]
Though if I repeat all the commands to build bottle and install from it, then `vgrep` test fails :confused:

**Comment by yermulnik** [comment]
Though if I build it inside the same container using `go` installed with Homebrew, it jsut works :confused: 
```
linuxbrew@1d893cc6868d:~$ brew uninstall --force vgrep go go-md2man
Uninstalling vgrep... (6 files, 3.8MB)
Uninstalling go... (10,810 files, 537.4MB)
linuxbrew@1d893cc6868d:~$ git clone https://github.com/vrothberg/vgrep.git
Cloning into 'vgrep'...
remote: Enumerating objects: 3529, done.
remote: Counting objects: 100% (793/793), done.
remote: Compressing objects: 100% (592/592), done.
remote: Total 3529 (delta 349), reused 424 (delta 175), pack-reused 2736
Receiving objects: 100% (3529/3529), 5.87 MiB | 9.43 MiB/s, done.
Resolving deltas: 100% (2237/2237), done.
linuxbrew@1d893cc6868d:~$ cd ./vgrep && make clean && make release
rm -rf ./build docs/*.1
GO111MODULE=on go build -mod=vendor -buildmode=pie -o ./build/vgrep -ldflags "-s -w -X main.version=2.5.6-dev"
linuxbrew@1d893cc6868d:~/vgrep$ ./build/vgrep -w Homebrew --no-less .
Index File      Line Content
    0 README.md   11 * You can install `vgrep` on [Fedora](https://src.fedoraproject.org/rpms/vgrep), [openSUSE](https://software.opensuse.org/package/vgrep), [archlinux](https://aur.archlinux.org/packages/vgrep/), [Gentoo](https://packages.gentoo.org/packages/app-text/vgrep), and on Mac OS via [MacPorts](https://ports.macports.org/port/vgrep/summary) and [Homebrew](https://formulae.brew.sh/formula/vgrep).
linuxbrew@1d893cc6868d:~/vgrep$
```

**Comment by yermulnik** [comment]
I'm not familiar with debugging, but in case it could help:
```
linuxbrew@1d893cc6868d:~$ strace vgrep -w Homebrew --no-less vgrep/
execve("/home/linuxbrew/.linuxbrew/bin/vgrep", ["vgrep", "-w", "Homebrew", "--no-less", "vgrep/"], 0x7ffe0833d5f0 /* 11 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7fde3db56270) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x56efff} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by dawidd6** [comment]
Can't tell what's wrong really. Maybe building without `-ldflags` would help.

**Comment by yermulnik** [comment]
Though it works okay when being built outside Homebrew bottle magic.
Is there anything I can help with to investigate it further?
(I'm neither Homebrew, nor Golang, nor `vgrep` professional though)

**Comment by dawidd6** [comment]
Sorry, don't know, the problem seems to happen at random.

**Pull request closed without merging**
