### PR TITLE
percona-server 8.0.26-16

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I'm trying to see if we can build bottles for Monterey too.

**Comment by carlocab** [comment]
```
  CMake Error at CMakeLists.txt:1561 (MESSAGE):
    Inconsistent options for LDAP/SASL/KERBEROS/SSL
```

**Comment by iMichka** [comment]
This is because we can't mix system and brewed dependencies, as requested by their cmake file:
`# LDAP / SASL / KERBEROS / SSL must all be "system" or "custom", not a mix`

**Comment by carlocab** [comment]
> This is because we can't mix system and brewed dependencies

Does their build distinguish between system and brewed deps? Because that would be unusual.

```
CMake Error at cmake/kerberos.cmake:299 (MESSAGE):
  -DWITH_KERBEROS=<path> not supported on this platform
Call Stack (most recent call first):
  CMakeLists.txt:1521 (MYSQL_CHECK_KERBEROS)
```

**Comment by iMichka** [comment]
Making progress. This needs #92470 now.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
