### PR TITLE
Use opt_bin in service blocks

### PR DESCRIPTION
**Pull request by apainintheneck**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

These are fixes for the problems mentioned in https://github.com/Homebrew/brew/issues/15113. It is essentially the same fix as done in https://github.com/Homebrew/homebrew-core/pull/127197.

Basically, we shouldn't use `bin` inside service blocks because it's not necessary and it doesn't work well when serializing the service block for use with the API. `opt_bin` is a drop-in replacement which doesn't have those problems.

These are the only formulas that seemed to have this problem.

```
/u/l/H/L/T/h/homebrew-core (master|✔) $ awk '
                                        $1 == "service" && $2 == "do", $1 == "end" {
                                          if ($0 ~ /[\[ ]bin\//) print
                                        }' (find . -type f -name "*.rb")
    run [bin/"trojan-go", "-config", etc/"trojan-go/config.json"]
    run [bin/"sftpgo", "serve", "--config-file", etc/"sftpgo/sftpgo.json", "--log-file-path",
    run [bin/"pulsar", "standalone"]
    run bin/"influxd"
    run [bin/"nsqd", "-data-path=#{var}/nsq"]
    run [bin/"vlmcsd", "-i", etc/"vlmcsd/vlmcsd.ini", "-D"]
    run [bin/"v2ray", "run", "-config", etc/"v2ray/config.json"]
    run [bin/"languagetool-server", "--port", "8081", "--allow-origin"]
```

I'm not sure if I need to add `rebuild` here since this only affects how the service files are created. What really needs to happen is that people need to rewrite the service files which can already be done with `brew services restart` command if I remember correctly.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by apainintheneck** [comment]
Ah, would it be better if I split these up into separate PRs?

**Comment by carlocab** [comment]
Probably, yes.

**Comment by apainintheneck** [comment]
On second thought I'm actually not sure we really need to rebuild these at all. The service block is only used to generate service files in bottles which get overwritten on install anyway.

How does this sort of thing usually get handled when service blocks are changed?

**Comment by carlocab** [comment]
Ah, yes. If we don't need new bottles (and I believe we don't now that the `service` data is available on the API) then this can be merged as is.

**Review by carlocab — APPROVED** [review]
Feel free to merge whenever you're ready.

**Comment by apainintheneck** [comment]
Bold of you to assume that I have merge privileges here 😄. This is actually my first PR in this repo.

**Pull request merged**
