### PR TITLE
swiftgen 5.0.0

### PR DESCRIPTION
**Pull request by AliSoftware**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- And also passes `brew test swftgen`

-----

\cc @djbe @Liquidsoul 👍

### CODE REVIEW

**Comment by AliSoftware** [comment]
For the record, the test was failing on the El Capitan worker at first, because we used `xcode 8.0` (Swift 3.0) but `Sequence.drop(while: …)` [was introduced in Swift 3.1](https://swift.org/blog/swift-3-1-released/)).

I since updated the formula to use Xcode 8.3.

But now, even though the 3 workers' jobs  (el'cap, sierra, yosemite) are marked as SUCCESS, only the sierra bottle seem to have been actually built. Which makes sense, because Xcode 8.3 requires Sierra 10.12.

I'm wondering how that's gonna affect the users on 10.10 or 10.11.
To be clear, SwiftGen doesn't need 10.12 to run. It only requires Xcode 8.3 (thus 10.12) to build. Which is what is defined in the Formula btw. But a version of SwiftGen pre-built using Xcode 8.3 on Sierra should still work (= be able to be installed then run) on 10.10 & 10.11, and I fear that given what Homebrew workers did, this won't work for them as expected?

**Comment by AliSoftware** [comment]
In other words, maybe we should point everyone to the Sierra bottle so that yosemite & el'capitan users can get the pre-build version of SwiftGen anyway — even if there wouldn't be able to compile it on their own Mac themselves?

**Comment by ilovezfs** [comment]
We can manually set a bottle to be, for example, `:sierra_or_later` but we cannot set a bottle to be `:sierra_or_earlier`, so the formula will effectively only be available to users on >= macOS 10.12.

In the last thirty days, according to the analytics, about 95% of the users of this formula were on >= macOS 10.12.

**Comment by AliSoftware** [comment]
Mmmh did that mean that we're gonna have to bump the formula's minimum run version just because of this, despite SwiftGen being able to run on earlier macOS versions?
Or should we just merge the formula as is? (I hear some people manage to install Xcode 8.3 on pre-Sierra despite the official minimum macOS restriction, so…)

**Comment by ilovezfs** [comment]
>Mmmh did that mean that we're gonna have to bump the formula's minimum run version just because of this

It's effectively ` depends_on :macos => :sierra` but we don't have to specify that separately since it's redundant.

**Comment by ilovezfs** [comment]
Users on El Capitan will see
```
iMac-TMP:~ joe$ brew install swiftgen
swiftgen: A full installation of Xcode.app 8.3 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
iMac-TMP:~ joe$ 
```

**Comment by AliSoftware** [comment]
Right. And I'm assuming we can't use some custom error message to point them to alternate installation methods (like downloading the zip from GitHub)?

**Comment by ilovezfs** [comment]
Correct.

**Comment by AliSoftware** [comment]
Ok. I've updated the install instructions in the README for homebrew, to suggest to use other installation methods for people in pre-sierra. So I think we can merge this formula as is :wink:

**Comment by ilovezfs** [comment]
@AliSoftware Done! Thanks for the upgrade :)

**Comment by AliSoftware** [comment]
Thx @ilovezfs ! 🎉

**Pull request closed without merging**
