### PR TITLE
yaws 2.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by samford** [comment]
http://yaws.hyber.org no longer resolves but hyber.org links to the
`yaws` GitHub page, so I updated the commit to use the GitHub repository as the `homepage`.

**Comment by chenrui333** [comment]
> http://yaws.hyber.org no longer resolves but hyber.org links to the `yaws` GitHub page, so I updated the commit to use the GitHub repository as the `homepage`.

@samford did you miss the commit push? :)

**Comment by samford** [comment]
> did you miss the commit push? :)

Evidently I didn't save the file before committing 😆

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by samford** [comment]
Test failure on macOS 12-x86_64:

```
=INFO REPORT==== 15-Jul-2024::18:27:17.825880 ===
Yaws: Using config file /private/tmp/yaws-test-20240715-21808-9drz6j/yaws.conf

==> curl --silent localhost:49397/example.txt

Killing child processes...
=INFO REPORT==== 15-Jul-2024::18:27:19.477502 ===
SIGTERM received - shutting down

Logger - error: {removed_failing_handler,default}
```

**Review by samford — APPROVED** [review]

**Pull request merged**
