### PR TITLE
ncspot 0.9.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error: there is no argument named `content_len`
    --> src/ui/listview.rs:88:34
     |
  88 |         log::info!("content len: {content_len}");
     |                                  ^^^^^^^^^^^^^
  
  error: there is no argument named `loaded`
     --> src/ui/listview.rs:100:35
      |
  100 |         log::info!("can paginate: {loaded}");
      |                                   ^^^^^^^^
  
  warning: unused import: `error`
   --> src/queue.rs:4:18
    |
  4 | use log::{debug, error, info};
    |                  ^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default
  
  warning: `ncspot` (bin "ncspot") generated 1 warning
  error: failed to compile `ncspot v0.9.5 (/tmp/ncspot-20220119-18087-108fo7a/ncspot-0.9.5)`, intermediate artifacts can be found at `/tmp/ncspot-20220119-18087-108fo7a/ncspot-0.9.5/target`
```

**Comment by hrkfdn** [comment]
Hey there, to build the latest source you need Rust 1.58.0: https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings

**Comment by chenrui333** [comment]
Thanks @hrkfdn!

**Comment by chenrui333** [comment]
blocked by #93099

**Comment by chenrui333** [comment]
looks like CI runner hiccup with `11`, should be good for the merge after rerun

**Review by Moisan — APPROVED** [review]

**Pull request closed without merging**
