### PR TITLE
spigot: wrap test to 80 characters

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The current version makes the formula pretty unpleasant to read or edit.

### CODE REVIEW

**Comment by neutric** [comment]
@DomT4 Much easier to read! Most of the lines are actually 81 characters long, though, so leaving this open for now in case you feel like having it perfect. ;)

**Comment by DomT4** [comment]
I think it was 80 if you ignore the "hidden" character at the end of each line, but nonetheless I fixed it 😉

**Comment by neutric** [comment]
I like! 🌵

**Comment by DomT4** [comment]
Thanks! Having the one exceptionally long line annoyed me more than it should have 😸

**Pull request merged**
