### PR TITLE
qt: migrate to boneyard

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Created with `brew boneyard-formula-pr` because Qt4 is EOL.

Fixes https://github.com/Homebrew/homebrew-core/issues/1705.

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
@ilovezfs Note there's also an alias change and making qt5 not keg-only in here.

**Comment by ilovezfs** [comment]
Is it valid to have an alias that is equal to the same name as something still in another homebrew tap but referring to a different formula? Seems like we'll also need to rename the qt.rb in boneyard qt4.rb, or just delete it outright.

**Comment by MikeMcQuaid** [comment]
> Is it valid to have an alias that is equal to the same name as something still in another homebrew tap but referring to a different formula?

I'll test it out at some point and see what happens.

**Comment by MikeMcQuaid** [comment]
Merging into https://github.com/Homebrew/homebrew-core/pull/8306.

**Comment by MikeMcQuaid** [comment]
> I'll test it out at some point and see what happens.

I did, seems to work fine but I'm going to just remove the `tap_migrations` when pulling https://github.com/Homebrew/homebrew-core/pull/8306.

**Comment by MikeMcQuaid** [comment]
and, actually, not commit to boneyard to avoid clashes.

**Comment by scpeters** [comment]
This is just an FYI, not a complaint: this PR has broken some formulae in a tap I maintain (`osrf/simulation`) that use qt4, so I will probably fork the qt4 formula into that tap if it isn't in the boneyard. We are almost finished migrating the latest version of our software to use qt5 but want to support users on old versions as well.

Thanks for all your work maintaining homebrew!

**Comment by ilovezfs** [comment]
It's been relocated to https://github.com/cartr/homebrew-qt4/blob/master/qt.rb

**Pull request closed without merging**
