### PR TITLE
youtube-dl: update source and remove head

### PR DESCRIPTION
**Pull request by lpla**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As noted in their [main website](https://yt-dl.org) and [Hacker News](https://news.ycombinator.com/item?id=24872911), youtube-dl [dev repository](https://github.com/ytdl-org/youtube-dl/) is taken down due to [DMCA takedown notice by RIAA](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md).

This pull request updates links so they point to the mirror they set up.

### CODE REVIEW

**Review by chkpnt — COMMENTED** [review]
In my opinion, using the source from [pypi.org](https://pypi.org/project/youtube_dl/#files) would be a more natural choice than the server of a particular Linux distribution.

**Comment by chkpnt** [comment]
> In my opinion, using the source from [pypi.org](https://pypi.org/project/youtube_dl/#files) would be a more natural choice than the server of a particular Linux distribution.

Uh, sorry... just saw that you are just pointing to the source the link on [yt-dl.org](https://yt-dl.org/download.html) is directing. In this case your choice is of course absolutely okay.

**Comment by SMillerDev** [comment]
I'd prefer the pypy source since that works better with homebrew tooling.

**Comment by lpla** [comment]
Source file now points to Pypi.

**Comment by bayandin** [comment]
You need to make a couple of more changes since we're need to build what we downloaded from pypi. The formula should looks like this:

```ruby
class YoutubeDl < Formula
  include Language::Python::Virtualenv

  desc "Download YouTube videos from the command-line"
  homepage "https://yt-dl.org"
  url "https://files.pythonhosted.org/packages/12/8b/51cae2929739d637fdfbc706b2d5f8925b5710d8f408b5319a07ea45fe99/youtube_dl-2020.9.20.tar.gz"
  sha256 "67fb9bfa30f5b8f06227c478a8a6ed04af1f97ad4e81dd7e2ce518df3e275391"
  license "Unlicense"

  depends_on "python@3.9"

  def install
    virtualenv_install_with_resources
  end

  test do
    # commit history of homebrew-core repo
    system "#{bin}/youtube-dl", "--simulate", "https://www.youtube.com/watch?v=pOtd1cbOP7k"
    # homebrew playlist
    system "#{bin}/youtube-dl", "--simulate", "--yes-playlist", "https://www.youtube.com/watch?v=pOtd1cbOP7k&list=PLMsZ739TZDoLj9u_nob8jBKSC-mZb0Nhj"
  end
end
```

**Comment by lpla** [comment]
Makes sense. I am not that much experienced with Ruby code, so I will trust your example.

**Comment by stephen304** [comment]
Why not the source tarball link from `https://yt-dl.org/download.html`, which has the same sha as the tarball previously used from GH? (`https://yt-dl.org/downloads/2020.09.20/youtube-dl-2020.09.20.tar.gz`)

Seems like the natural choice.

**Comment by lpla** [comment]
It doesn’t match, check it. I already reported it to their Freenode chat several hours ago, but brew devs feel good with Pypi file, as noted above.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
audit failure with the site cert issue, proceeding with the merge.
```
==> brew audit youtube-dl --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
youtube-dl:
  * The URL https://yt-dl.org is not reachable
```

**Comment by chenrui333** [comment]
Thanks @lpla!

**Pull request closed without merging**
