### PR TITLE
molten-vk 1.2.8

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>- Add support for extensions:
	- `VK_KHR_shader_integer_dot_product`
- Improve support for _iOS App Store_ rules by using dynamic _XCFramework_, instead of naked `dylib`.
  - Static _XCFramework_ now available in `Package/Latest/MoltenVK/static/MoltenVK.xcframework`.
  - Dynamic _XCFramework_ now available in `Package/Latest/MoltenVK/dynamic/MoltenVK.xcframework`.
  - _macOS_ dynamic library now available in `Package/Latest/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib`.
- Add `MVK_USE_METAL_PRIVATE_API` build setting to allow **MoltenVK** to be built with access to _Metal_ private API calls.
  - `VkPhysicalDeviceFeatures::wideLines` enabled when `MVK_USE_METAL_PRIVATE_API` is enabled in a **MoltenVK** build.
  - `VkPhysicalDeviceFeatures::logicOp` enabled when `MVK_USE_METAL_PRIVATE_API` is enabled in a **MoltenVK** build.
  - `VkPhysicalDeviceFeatures::depthBounds` enabled on AMD GPUs when `MVK_USE_METAL_PRIVATE_API` is enabled in a **MoltenVK** build.
  - `VkPhysicalDevicePortabilitySubsetFeaturesKHR::samplerMipLodBias` enabled when `MVK_USE_METAL_PRIVATE_API` is enabled in a **MoltenVK** build.
  - _Metal_ native pipeline sample masks supported when `MVK_USE_METAL_PRIVATE_API` is enabled in a **MoltenVK** build.
- Enable use of native texture atomics where supported.
- Fix potential crash when using multi-planar images.
- Fix translation of fully remapped multi vertex attribute bindings.
- Fix unresolvable layered compute resolve.
- Fix visionOS build.
- Handle depth/stencil swizzle sample correctly.
- Ensure buffers available for buffer addresses in push constants.
- Don't update `currentExtent` of headless surface when swapchain attached.
- Don't return `VK_SUBOPTIMAL_KHR` for headless surfaces.
- `runcts` script also output a file containing a list of the failed CTS tests.
- Add documentation for using Metal GPU capture with **MoltenVK**.
- Update minimum _macOS_ deployment target to 10.15.
- Update minimum _iOS/tvOS_ deployment target to 13.0.
- Update dependency libraries to match _Vulkan SDK 1.3.280_.
- Update `MVK_PRIVATE_API_VERSION` to `40`.
- Update to latest SPIRV-Cross:
  - MSL: Plumb through member state to image/sampler types.
  - MSL: Support variable sized descriptor array in argument buffer.
  - MSL: Implement `spvDescriptorArray` path for SSBO/UBO.
  - MSL: Add support for SPV_EXT_integer_dot_product.
  - MSL: Fix misc sign issues with dot product impl and add more coverage.
  - MSL: Handle volatile properly for emulated image atomics.
  - MSL: OpCopyObject declare a temp var of base type, not pointer type.
  - MSL: Pass texture array index separately to atomic texture operations.
  - MSL: Test image atomic for image2DArray.
  - MSL: Improve handling of BDA + atomics.
  - MSL: Fix type hierarchy for extended vectors.
  - MSL: Fix type hierarchy for extended vectors.
  - MSL: `atomic_compare_exchange_weak()` support `CompilerMSL:msl_options.texture_1D_as_2D`.
</pre>
</details>

### CODE REVIEW

**Comment by timsutton** [comment]
```
2024-03-13T21:19:58.3085100Z xcframework successfully written out to: /tmp/molten-vk-20240313-4804-gwf4ex/MoltenVK-1.2.8/Package/Release/MoltenVKShaderConverter/MoltenVKShaderConverter.xcframework
2024-03-13T21:19:58.3085100Z 
2024-03-13T21:19:58.3085170Z ** BUILD SUCCEEDED **
2024-03-13T21:19:58.3085170Z 
2024-03-13T21:19:58.3085350Z [31mError:[0m An exception occurred within a child process:
2024-03-13T21:19:58.3094300Z   Errno::ENOENT: No such file or directory - Package/Release/MoltenVK/MoltenVK.xcframework
```

**Comment by pthariensflame** [comment]
Any news on this?

**Comment by chenrui333** [comment]
> Any news on this?

looks like the build issues only happened on 13/13-arm

**Comment by chenrui333** [comment]
- https://github.com/KhronosGroup/MoltenVK/issues/2204

**Comment by chenrui333** [comment]
#173793

**Pull request closed without merging**
