### PR TITLE
fabio 1.5.6

### PR DESCRIPTION
**Pull request by magiconair**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks again @magiconair!

**Comment by iMichka** [comment]
```
failed: brew install --build-bottle --verbose fabio

        Error: SHA256 mismatch
Expected: 07a0d77bb3f718bf9e4f3952726493f3c8610f0427127f0c43172896a4934730
Actual: 178764c8cba2298370166984a13f630a938c51ed8e627e24426538d7af2f3f3e
Archive: /home/linuxbrew/.cache/Homebrew/fabio-1.5.6.tar.gz
To retry an incomplete download, remove the file above.
```

@magiconair The tar file changed since two days. Any idea why?

**Comment by magiconair** [comment]
@iMichka I did a force push after a botched release but did the homebrew update only after everything was cleaned up. Maybe I've missed something. I'll have a look. Thx

**Comment by magiconair** [comment]
@iMichka you're right. I'll fix it. Thx for finding this.

**Comment by iMichka** [comment]
Thanks.

When you break a release, you should never force push, because if some users already downloaded the release, they will need to make a diff between both releases with the same version number to understand what is the diff.
The best solution to this (if it happens again) is to tag a 1.5.6.1 release, or something with a new version number. It happened to me once so there is no shame to do that :)

To fix this in homebrew, I propose that you make a pull request to update the sha256 and bump the revision to 1.

**Comment by magiconair** [comment]
Yeah, I need to let that habit go. I don't recall exactly what went wrong. Will the homebrew name then become fabio-1.5.6-1 ?

**Comment by magiconair** [comment]
https://github.com/Homebrew/homebrew-core/pull/22541

**Pull request closed without merging**
