### PR TITLE
spotbugs: depend on openjdk@12

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by chenrui333** [comment]
@reitermarkus I wonder if you can specify the reason as comment about why it does reply on openjdk@12, not the latest one. Thanks!

**Comment by reitermarkus** [comment]
The test fails with

```
java.lang.IllegalArgumentException: Unsupported class file major version 57
```

on OpenJDK > 12.

**Comment by chenrui333** [comment]
Thanks!!

**Comment by norrisjeremy** [comment]
This should be reverted as nothing about Spotbugs requires Java12+.

**Comment by reitermarkus** [comment]
@norrisjeremy, we are migrating to depend on `openjdk` formulae where possible. If you want to run with another Java version, you can do so by setting `JAVA_HOME`.

**Comment by norrisjeremy** [comment]
That's a shame to hear.

**Comment by rhwood** [comment]
Where is the discussion on making the decision to require users to install unwanted versions of Java on their systems? (Or to put another way, it was a rude surprise to have two OpenJDK 13 and 12 builds installed on a system where only the LTS versions are supposed to be allowed.)

**Comment by reitermarkus** [comment]
Our policy is to depend on the latest version of a given formula wherever possible.

**Pull request merged**
