### PR TITLE
svgexport 0.3.2 (new formula)

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by commitay** [comment]
> ⚠️ Mapzen is not currently supporting this code. ⚠️
>
> We may not be able to answer questions about svg-export. If you’re looking for an active project with SVG exporting functionality for Mapzen Vector Tiles, please check out https://github.com/hanbyul-here/svg-exporter for an excellent alternative.

**Comment by reitermarkus** [comment]
Seems like I copy-pasted the wrong homepage, should be https://github.com/shakiba/svgexport.

**Comment by commitay** [comment]
It hasn't add a release or any commits for two years, not sure where this would fall on the scale for "ages"

https://docs.brew.sh/Acceptable-Formulae
> be maintained i.e. the last release wasn’t ages ago

**Comment by ilovezfs** [comment]
@reitermarkus It also looks like there's a CVE that has been allocated with no response from upstream: https://github.com/shakiba/svgexport/issues/55

**Pull request closed without merging**
