### PR TITLE
hdf5 1.10.2

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
🚀

**Comment by tschoonj** [comment]
Already? I just restarted the build?

**Comment by ilovezfs** [comment]
- [ ] [pdal](https://github.com/Homebrew/homebrew-core/pull/26877)
- [ ] [shogun](https://github.com/Homebrew/homebrew-core/pull/26878)
- [ ] [sratoolkit](https://github.com/Homebrew/homebrew-core/pull/26879)

**Pull request closed without merging**
