### PR TITLE
update wxwidgets to 3.1.2 that support Mojave Dark mode

### PR DESCRIPTION
**Pull request by ra1nb0w**
see https://trac.wxwidgets.org/ticket/18146

Signed-off-by: Davide `rainbow` Gerhard <rainbow@irh.it>

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the pull request, there's some more changes that need to be made before we can merge this however. Could you change your commit to remove the "revision 1"?
And could you make new commits where you add such a statement to the following formula:

- [ ] couchdb
- [ ] diff-pdf
- [ ] erlang
- [ ] erlang@17
- [ ] erlang@18
- [ ] erlang@19
- [ ] erlang@20
- [ ] gambit
- [ ] homeworlds
- [ ] riak
- [ ] scummvm-tools
- [ ] spatialite-gui
- [ ] wxmaxima
- [ ] wxpython

**Comment by ra1nb0w** [comment]
Removed _revision 1_
Do you mean add/bump up the _revision_ in each formula?
thanks

**Comment by SMillerDev** [comment]
Yeah, they all need to be rebuild that way because they depend on wxmac

**Comment by ra1nb0w** [comment]
Ops. I followed GitHub and now I see in the site that it is a development release. So, how we can have dark mode? probably, I need to write that question to wxwidgets ml.

**Comment by fxcoudert** [comment]
@ra1nb0w yes, I suggest you ask the wxWidgets list for that

**Pull request closed without merging**
