### PR TITLE
singular 4.1.3p2

### PR DESCRIPTION
**Pull request by karimknaebel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]
Thanks @kabouzeid! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by iMichka** [comment]
@kabouzeid the sha256 of the file changed:

==> Downloading ftp://jim.mathematik.uni-kl.de/pub/Math/Singular/SOURCES/4-1-3/singular-4.1.3p2.tar.gz
Warning: Formula reports different SHA256: 573f4ea5f526c6d80da3feef56362e0069e3b1a889f320ef9882996fbc857587
Downloaded to: /github/home/.cache/Homebrew/downloads/cc449fae2facbc79b0b344ba366e7b3b8585391dbacf49d676a13771cc8fc09e--singular-4.1.3p2.tar.gz
SHA256: af2d8b8c73bef4f363cd1a924d51568b91e0720ecbf8b6903b4aac34d56a6e19

Did upstream retag their release?

**Comment by kabouzeid** [comment]
Not that I know of. Also the FTP server still shows the same upload date. I’ll see if the uploaded knows anything about this.

**Comment by kabouzeid** [comment]
I can now confirm that this was indeed a retag. The newer checksum is correct.

**Comment by iMichka** [comment]
Could you open a pull request to fix the sha256?

**Comment by kabouzeid** [comment]
@iMichka the new download also contains a hotfix. If I just update the sha256, will the bottle be rebuilt? Or should I additionally add "revision 1"?

**Pull request closed without merging**
