### PR TITLE
vtk 9.3.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
raised an upstream issue for f3d test failure, https://github.com/f3d-app/f3d/issues/1087

**Comment by bevanjkay** [comment]
Build is error because `f3d` is showing a checksum mismatch.

```
 Error: f3d: SHA256 mismatch
  Expected: 13d33b49bad71a5a1bb9d1ecc927cc2d26d767daebaa6dba145bcc411b8d5f27
    Actual: 9c2906b62f3066f075effbabd6501964391e8a8ffad6ed773c33db12580cc466
```

**Comment by iMichka** [comment]
I've opened an upstream issue: https://github.com/f3d-app/f3d/issues/1294

**Comment by bevanjkay** [comment]
Rebase after https://github.com/Homebrew/homebrew-core/pull/164330

**Comment by cho-m** [comment]
I think we still need to apply a fix in `f3d` before next run based on comments in https://github.com/f3d-app/f3d/issues/1087

Either patching in https://github.com/f3d-app/f3d/commit/a5ecb6bd6f631285bd380b5fa8d7c7fd369cfef9 or modifying test.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
