### PR TITLE
secure urls

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Audit warning (and two missing test blocks):

```
glm:
  * GitHub fork (not canonical repository)
```

### CODE REVIEW

**Comment by DomT4** [comment]
`bibclean` is repeatedly failing to download. Not sure what's going on there, but I can't reach it locally either:

```
        ==> Downloading http://ftp.math.utah.edu/pub/bibclean/bibclean-2.17.tar.gz
==> Retrying download
==> Downloading http://ftp.math.utah.edu/pub/bibclean/bibclean-2.17.tar.gz
Error: Failed to download resource "bibclean"
Download failed: http://ftp.math.utah.edu/pub/bibclean/bibclean-2.17.tar.gz
```

**Comment by vszakats** [comment]
It is down from here as well. Even using FTP protocol, so it seems that host/IP is not functioning at this moment. (The patched homepage URL is working though)

**Comment by DomT4** [comment]
Sigh, I'll try and see if Debian have a mirror or something. Would you mind rebasing this? Apparently someone caused a merge conflict somewhere.

**Comment by vszakats** [comment]
No worries, rebased now.

Quick search didn't reveal a `bibclean` mirror with this recent version, hopefully you'll have better luck. Possibly the server is just celebrating July 4th with the rest of the US :)

**Comment by DomT4** [comment]
Yeah, I couldn't find one either. MacPorts, Debian, FreeBSD all turned up nothing or older versions. Arch carries the same version as we do but seemingly don't mirror it.

**Comment by DomT4** [comment]
Merged. Thank you once again @vszakats! 🍻

**Pull request closed without merging**
