### PR TITLE
haskell-stack: update to 1.9.1

### PR DESCRIPTION
**Pull request by purcell**
Similar to #33078 (by @commitay) in spirit, but avoids the resulting build errors.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by purcell** [comment]
Hmm, I'm having trouble seeing what went wrong with the build after your additional commit, @fxcoudert...?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by purcell** [comment]
Not sure how to help with this, sorry: if I'm reading it correctly, the [build failure](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/33277/version=mojave/testReport/junit/brew-test-bot/mojave/install_haskell_stack/) indicates that cabal is failing, and that's provided by the general facilities in [`haskell.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/haskell.rb)

```
==> cabal v1-update
Downloading the latest package list from hackage.haskell.org
==> cabal v1-install --jobs=3 --max-backjumps=100000 happy
ghc: there is no package.cache in /usr/local/Cellar/ghc/8.4.4/lib/ghc-8.4.4/package.conf.d even though package database is not empty
```

Any pointers? I can't reproduce this locally.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by purcell** [comment]
Thanks @SMillerDev - build seems to be working now.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @purcell

**Comment by purcell** [comment]
Awesome, thanks folks.

**Pull request closed without merging**
