### PR TITLE
remove devel specs 6/6

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
https://github.com/Homebrew/brew/pull/5086

### CODE REVIEW

**Comment by commitay** [comment]
I've cancelled the build for this, I'll restart it after https://github.com/Homebrew/homebrew-core/pull/33211 is finished.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by commitay** [comment]
I forgot that `readline` is a multi hour build, I should have moved it to a separate PR. 😞

**Comment by fxcoudert** [comment]
If you ran audit locally on all of them, maybe simply kill the build and merge.

**Comment by commitay** [comment]
I've merged `readline` in https://github.com/Homebrew/homebrew-core/pull/33221 I'll let it test the others, should be quicker.

**Pull request merged**
