### PR TITLE
apache-arrow, apache-arrow-glib 10.0.0

### PR DESCRIPTION
**Pull request by kou**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Missing `arrow-csv`

**Comment by kou** [comment]
Oh, sorry. I've added missing options.

**Comment by kou** [comment]
@chenrui333 Could you help us to solve the current CI failure?

https://github.com/Homebrew/homebrew-core/actions/runs/3358041138/jobs/5564529057

> Error: PR requires the CI-long-timeout label but it is not set!
> Error: If the longer timeout is not required, remove the "long build" label.
> Error: Otherwise, add the "CI-long-timeout" label.
> Error: No more than 2 PRs at a time may use "CI-long-timeout".

**Comment by kou** [comment]
@SMillerDev What should we do to fix the following CI failure?

https://github.com/Homebrew/homebrew-core/actions/runs/3372894700/jobs/5596948239#step:2:143

```text
Error: PR requires the CI-long-timeout label but it is not set!
Error: If the longer timeout is not required, remove the "long build" label.
Error: Otherwise, add the "CI-long-timeout" label.
Error: No more than 2 PRs at a time may use "CI-long-timeout".
```

**Comment by chenrui333** [comment]
@kou yeah, we need available CI server to handle `long build` PRs.

**Comment by chenrui333** [comment]
The current available two slots have been taken, https://github.com/Homebrew/homebrew-core/labels/CI-long-timeout

**Comment by kou** [comment]
@chenrui333 Thanks! Should I push something to run tests again? Or should we wait for a CI server for `long build`?

**Comment by SMillerDev** [comment]
You need to wait for a CI slot

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
