### PR TITLE
lumo 1.2.0

### PR DESCRIPTION
**Pull request by anmonteiro**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by anmonteiro** [comment]
I think CI is failing with the same issue reported in https://github.com/nodejs/node/issues/11104. This project builds Node (7.5.0) as part of the release process. I wonder what the solution is?

**Comment by anmonteiro** [comment]
Looks like Node 7.6.0 is out and fixes the `clock_gettime` issue. Is it worth the trouble fixing the build on this PR or should I just make a new release with the new version?

**Comment by MikeMcQuaid** [comment]
Can this project not be made to use the `node` formula instead?

**Comment by anmonteiro** [comment]
I don't think that's going to be possible. The project uses [Nexe](https://github.com/nexe/nexe) to compile a single binary. This resulting binary is a slightly modified version of the Node.js build (with a custom init script to land users on a ClojureScript REPL).

**Comment by ilovezfs** [comment]
@anmonteiro mind creating a new release now that 7.7.1 is out?

**Comment by anmonteiro** [comment]
I'll do that. We don't need this anymore. Thanks.

**Comment by ilovezfs** [comment]
Cool. Thank you!

**Pull request closed without merging**
