### PR TITLE
llvm lld flang wasi-runtimes 19.1.5

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by carlocab** [comment]
Can't really see any relevant upstream changes, so maybe the config file didn't get written properly or something. Let's see if it works fine on a re-run.

**Review by carlocab — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Strange enough, I couldn't reproduce the CI error locally with the bottles built in the latest CI run. The `-syslibroot` flag was correctly set.

```
$ brew test -v flang
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/bin/bundle clean
==> Testing flang
==> /opt/homebrew/Cellar/flang/19.1.5/bin/flang-new -v hello.f90 -o hello
Homebrew flang-new version 19.1.5
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/flang/19.1.5/libexec
Configuration file: /opt/homebrew/Cellar/flang/19.1.5/libexec/flang.cfg
Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin24.cfg
System configuration file directory: /opt/homebrew/etc/clang
User configuration file directory: /private/tmp/flang-test-20241206-8269-xhugyt/.config/clang
 "/opt/homebrew/Cellar/flang/19.1.5/libexec/flang-new" -fc1 -triple arm64-apple-macosx15.0.0 -emit-obj -mrelocation-model pic -pic-level 2 -target-cpu apple-m1 -target-feature +zcm -target-feature +zcz -target-feature +v8.4a -target-feature +aes -target-feature +altnzcv -target-feature +ccdp -target-feature +complxnum -target-feature +crc -target-feature +dotprod -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +fptoint -target-feature +fullfp16 -target-feature +jsconv -target-feature +lse -target-feature +neon -target-feature +pauth -target-feature +perfmon -target-feature +predres -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +sb -target-feature +sha2 -target-feature +sha3 -target-feature +specrestrict -target-feature +ssbs -resource-dir /opt/homebrew/Cellar/flang/19.1.5/lib/clang/19 -mframe-pointer=non-leaf -o /private/tmp/hello-d7fbc2.o -x f95-cpp-input hello.f90
 "/usr/bin/ld" -demangle -lto_library /opt/homebrew/Cellar/flang/19.1.5/lib/libLTO.dylib -no_deduplicate -dynamic -arch arm64 -platform_version macos 15.0.0 15.1 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk -mllvm -enable-linkonceodr-outlining -o hello -lc++ -lto_library /opt/homebrew/opt/llvm/lib/libLTO.dylib /private/tmp/hello-d7fbc2.o -L/opt/homebrew/Cellar/flang/19.1.5/lib -lFortranRuntime -lFortranDecimal -lSystem
==> ./hello
==> /opt/homebrew/Cellar/flang/19.1.5/bin/flang-new -v test.f90 -o test
Homebrew flang-new version 19.1.5
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/flang/19.1.5/libexec
Configuration file: /opt/homebrew/Cellar/flang/19.1.5/libexec/flang.cfg
Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin24.cfg
System configuration file directory: /opt/homebrew/etc/clang
User configuration file directory: /private/tmp/flang-test-20241206-8269-xhugyt/.config/clang
 "/opt/homebrew/Cellar/flang/19.1.5/libexec/flang-new" -fc1 -triple arm64-apple-macosx15.0.0 -emit-obj -mrelocation-model pic -pic-level 2 -target-cpu apple-m1 -target-feature +zcm -target-feature +zcz -target-feature +v8.4a -target-feature +aes -target-feature +altnzcv -target-feature +ccdp -target-feature +complxnum -target-feature +crc -target-feature +dotprod -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +fptoint -target-feature +fullfp16 -target-feature +jsconv -target-feature +lse -target-feature +neon -target-feature +pauth -target-feature +perfmon -target-feature +predres -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +sb -target-feature +sha2 -target-feature +sha3 -target-feature +specrestrict -target-feature +ssbs -resource-dir /opt/homebrew/Cellar/flang/19.1.5/lib/clang/19 -mframe-pointer=non-leaf -o /private/tmp/test-06e3e6.o -x f95-cpp-input test.f90
 "/usr/bin/ld" -demangle -lto_library /opt/homebrew/Cellar/flang/19.1.5/lib/libLTO.dylib -no_deduplicate -dynamic -arch arm64 -platform_version macos 15.0.0 15.1 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk -mllvm -enable-linkonceodr-outlining -o test -lc++ -lto_library /opt/homebrew/opt/llvm/lib/libLTO.dylib /private/tmp/test-06e3e6.o -L/opt/homebrew/Cellar/flang/19.1.5/lib -lFortranRuntime -lFortranDecimal -lSystem
==> ./test
==> ar x /opt/homebrew/Cellar/flang/19.1.5/lib/libFortranCommon.a
==> file --brief /private/tmp/flang-test-20241206-8269-xhugyt/Fortran-features.cpp.o
==> file --brief /private/tmp/flang-test-20241206-8269-xhugyt/Fortran.cpp.o
==> file --brief /private/tmp/flang-test-20241206-8269-xhugyt/Version.cpp.o
==> file --brief /private/tmp/flang-test-20241206-8269-xhugyt/default-kinds.cpp.o
==> file --brief /private/tmp/flang-test-20241206-8269-xhugyt/idioms.cpp.o
```

**Comment by carlocab** [comment]
> Strange enough, I couldn't reproduce the CI error locally with the bottles built in the latest CI run. The `-syslibroot` flag was correctly set.

Weird. Seems like it should be a `test-bot` bug, but I also can't see any relevant changes in `test-bot` since `flang` was last built.

**Comment by carlocab** [comment]
Pushed a change that will make the test succeed in CI. It's not really ideal because it could mask issues that users have (e.g. #198106), but not really sure what the problem is so I have no clue how to fix it.

**Pull request merged**
