### PR TITLE
zeromq 4.3.1

### PR DESCRIPTION
**Pull request by emielwiedijk**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bluca** [comment]
Thanks!

**Comment by scpeters** [comment]
The `libzmq.pc` pkg-config file has changed in 4.3.1 (I think from https://github.com/zeromq/libzmq/pull/3336) to have the following line:

~~~
Requires.private:  libunwind
~~~

but there is no `libunwind.pc` file anywhere that I can find on macOS (I've checked high sierra and mojave), so downstream software that uses pkg-config to find zeromq fails to find it:

~~~
Package libunwind was not found in the pkg-config search path.
Perhaps you should add the directory containing `libunwind.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libunwind', required by 'libzmq', not found
~~~

**Comment by scpeters** [comment]
Maybe we can add a test invocation of `pkg-config` to the zeromq formula

**Comment by bluca** [comment]
Upstream's libunwind ships the pkgconfig file, so either fix the brew formula that builds it to install it, or disable libunwind in this formula
https://github.com/libunwind/libunwind/blob/master/src/unwind/libunwind.pc.in

**Comment by scpeters** [comment]
`libunwind` functionality is provided by macOS; this might be a time to add a `libunwind.pc` to https://github.com/Homebrew/brew/tree/master/Library/Homebrew/os/mac/pkgconfig

**Comment by bluca** [comment]
Ok. Note that if it's urgent you can disable libunwind manually with --disable-unwind

**Comment by EricLambrecht** [comment]
@bluca Which command is supposed to be run with `--disable-libunwind` exactly?

**Comment by bluca** [comment]
that's for ./configure

**Comment by bluca** [comment]
Also I see the libunwind flags are set manually via ENV - it would be sufficient to remove those so that autoconf doesn't find it

**Comment by bluca** [comment]
There's something I don't quite follow: the Requires.private are filled by autoconf ONLY if the dependency is found VIA pkg-config - in other words, if there's no libunwind.pc, there won't be a Requires.private: libunwind.
If I understand correctly there's no libunwind.pc at the moment - so how exactly is it being found at build time?
As the autoconf file currently is, unless libunwind.pc is found, it won't even build with libunwind - there's no fallback at all.

**Comment by scpeters** [comment]
Specifying the flags seems to make the configure script think that a `.pc` file exists.

**Comment by bluca** [comment]
That's really strange, it's the pkgconfig m4 macro that's used and that should just fail if the pc is not found, is homebrew shipping a custom one?

**Pull request closed without merging**
