### PR TITLE
v8 8.3.110.9

### PR DESCRIPTION
**Pull request by chrmoritz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jeroen** [comment]
Does xcode llvm no longer suffice?

**Comment by chrmoritz** [comment]
No, unfortunately not. Google tends to adopt the latest clang features quite quickly.

But it's likely that Apple clang 12 (which will be shipped with macOS 10.16 this autumn) will be based on llvm 10 and compatible again.

**Comment by chrmoritz** [comment]
On High Sierra:

```
[1357/1372] rm -f obj/third_party/zlib/google/libcompression_utils_portable.a && TOOL_VERSION=1589958237 python ../build/toolchain/mac/filter_libtool.py /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -D  -o obj/third_party/zlib/google/libcompression_utils_portable.a -filelist obj/third_party/zlib/google/libcompression_utils_portable.a.rsp
FAILED: obj/third_party/zlib/google/libcompression_utils_portable.a 
rm -f obj/third_party/zlib/google/libcompression_utils_portable.a && TOOL_VERSION=1589958237 python ../build/toolchain/mac/filter_libtool.py /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -D  -o obj/third_party/zlib/google/libcompression_utils_portable.a -filelist obj/third_party/zlib/google/libcompression_utils_portable.a.rsp
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `D' in: -D
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
```

Oh I forgot that we have to either drop High Sierra support or revert that specific `chromium/build` commit similar to like it was done in https://github.com/denoland/chromium_build/commit/56551e71dc0281cc1d9471caf6a02d02f18c830e.

**Comment by SMillerDev** [comment]
I think it allows patching resources. @jonchang was recently asking about that.

**Comment by jonchang** [comment]
https://github.com/Homebrew/brew/pull/7570 was the bug I think

**Comment by chrmoritz** [comment]
Can you tell me, how to do so? 

It tries to apply the patch for installing the resources if I try to use a normal top level patch block and fails because the resources files aren't there yet,

**Comment by chrmoritz** [comment]
Wait what, you can now nest a patch block into a resource block. That's great! 👍 
(This wasn't possible a few years ago when I've needed it the last time).

I've just applied the deno revert for now, instead of creating our own. I hope that's fine.

**Comment by bayandin** [comment]
Well done @chrmoritz, thanks!

**Review by bayandin — APPROVED** [review]

**Comment by jeroen** [comment]
@chrmoritz I'm trying to do a test build of v8 8.4 because there are some upcoming changes wrt/ pointer compression. I tried building `8.4.371.7` however it fails with the error below. Any guess what I need to change in the formula?

```
../src/objects/js-date-time-format.cc:62:41: error: unknown type name 'UDateFormatHourCycle'; did you mean 'UDateFormatStyle'?
JSDateTimeFormat::HourCycle ToHourCycle(UDateFormatHourCycle hc) {
                                        ^~~~~~~~~~~~~~~~~~~~
                                        UDateFormatStyle
../third_party/icu/source/i18n/unicode/udat.h:196:3: note: 'UDateFormatStyle' declared here
} UDateFormatStyle;
  ^
../src/objects/js-date-time-format.cc:64:10: error: use of undeclared identifier 'UDAT_HOUR_CYCLE_11'
    case UDAT_HOUR_CYCLE_11:
         ^
../src/objects/js-date-time-format.cc:66:10: error: use of undeclared identifier 'UDAT_HOUR_CYCLE_12'
    case UDAT_HOUR_CYCLE_12:
         ^
../src/objects/js-date-time-format.cc:68:10: error: use of undeclared identifier 'UDAT_HOUR_CYCLE_23'
    case UDAT_HOUR_CYCLE_23:
         ^
../src/objects/js-date-time-format.cc:70:10: error: use of undeclared identifier 'UDAT_HOUR_CYCLE_24'
    case UDAT_HOUR_CYCLE_24:
         ^
../src/objects/js-date-time-format.cc:1561:49: error: no member named 'getDefaultHourCycle' in 'icu_65::DateTimePatternGenerator'
  HourCycle hc_default = ToHourCycle(generator->getDefaultHourCycle(status));
```

**Comment by chrmoritz** [comment]
@jeroen Did you update all the resources according to the `DEPS` file? For me it looks like you could have missed the icu upgrade in: https://github.com/v8/v8/blob/8.4.371.7/DEPS#L79

**Pull request closed without merging**
