### PR TITLE
zookeeper 3.5.8

### PR DESCRIPTION
**Pull request by kylesm**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by kylesm** [comment]
I and some colleagues are suffering from the issues described here: https://issues.apache.org/jira/browse/ZOOKEEPER-3215

Bumped this to 3.5.8 instead of jumping it to 3.6.1.

**Comment by SMillerDev** [comment]
Why not 3.6.1?

**Comment by bayandin** [comment]
> Why not 3.6.1?

It looks like zookeeper 3.6 has changed build system https://github.com/Homebrew/homebrew-core/pull/51625#issuecomment-597998133

**Comment by chenrui333** [comment]
Indeed, zookeeper 3.6 would need some major update for the formula (ant to maven), good to move forward with this patch release (that bug seems impacting the 3.6 release line as well)

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
