### PR TITLE
dpkg@1.18 1.18.24 (new formula)

### PR DESCRIPTION
**Pull request by jsnrth**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for the suggestion @jsnrth! Unfortunately, older versions of dpkg are not maintained in a separate release line so they won't meet our criteria for versioned formulae. Please see

https://github.com/Homebrew/brew/blob/master/docs/Versions.md

**Comment by ilovezfs** [comment]
You may want to host this in your own tap
https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap

**Comment by jsnrth** [comment]
Hi @ilovezfs , I did not notice the versions documentation. We'll make our own tap to get the older version of dpkg. Thanks! -j

**Comment by ilovezfs** [comment]
You're welcome! BTW in terms of convention the formula name should be `dpkg@1.18` not `dpkg@118` (despite the class name)

**Pull request closed without merging**
