### PR TITLE
libqglviewer 2.6.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Weird
```
==> make install
make: *** No rule to make target `qglviewer_fr.qm', needed by `QGLViewer.framework/Versions/2/Headers/qglviewer_fr.qm'.  Stop.
make: *** Waiting for unfinished jobs....

**Comment by ilovezfs** [comment]
@dunn it doesn't happen if I build from the tag, so sort of packaging bug, I guess. Also this has qt5 support now!

**Comment by dunn** [comment]
💯

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Weird Yosemite failure: https://bot.brew.sh/job/Homebrew%20Core/8947/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_libqglviewer/

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
> libQGLViewer uses dual licensing: it is freely available under the terms of the GNU-GPL license for open source software development

GNU GPL for a library means if you use this in your application you need to GPL your whole application. We have no `brew uses libqglviewer` so I'd probably say given the build failure we should 💀 this.

**Comment by MikeMcQuaid** [comment]
The previous version builds with Qt5 but:

> GNU GPL for a library means if you use this in your application you need to GPL your whole application.

Boneyarding because of this.

**Pull request closed without merging**
