### PR TITLE
lua-language-server 2.6.0

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
 ==> /opt/homebrew/Cellar/lua-language-server/2.6.0/bin/lua-language-server
  Error: lua-language-server: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /Content-Length: \d+\r\n\r\n/ to match "".
```

**Comment by carlocab** [comment]
The timeout on the test is 5 minutes, so I don't think the timeout is the issue here. (But no, there isn't a way to increase the timeout.)

**Comment by clason** [comment]
Hmm. What happens locally is that I get the expected response, but it takes a few seconds, so I do suspect that the output check is too impatient. The full log is
```
==> Testing lua-language-server
==> /opt/homebrew/Cellar/lua-language-server/2.6.0/bin/lua-language-server
Error: lua-language-server: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /Content-Length: \d+\r\n\r\n/ to match "".
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.15.0/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.15.0/lib/minitest/assertions.rb:295:in `assert_match'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/lua-language-server.rb:50:in `block in <class:LuaLanguageServer>'
/opt/homebrew/Library/Homebrew/formula.rb:2108:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:588:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2107:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:948:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2106:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2359:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2100:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```
Especially the `timeout` at the end looks fishy...

**Comment by clason** [comment]
If I do the same thing from my shell, I get
```
~ ❯❯❯ lua-language-server
Content-Length: 120

{"jsonrpc":"2.0","method":"$/status/report","params":{"text":"😺Lua","tooltip":"Cached files: 0/0\nMemory usage: 2M"}}
```

**Comment by carlocab** [comment]
The `timeout` is a red herring -- that's just part of the call stack since the test is running inside a `timeout` object. An actual timeout raises a `Timeout::Error`. (Try doing `sleep 301` at the start of a `test` block.)

**Comment by carlocab** [comment]
Hmmm. Maybe we could do a `fork do ... exec` and `sleep` for a bit, and then read from `stdout`?

**Comment by clason** [comment]
Worth a try -- how would that look?

**Comment by carlocab** [comment]
Actually, we can probably mimic `yaml-language-server` here:
```diff
diff --git a/Formula/lua-language-server.rb b/Formula/lua-language-server.rb
index 0a9ed9c5d5f..4456d801bc8 100644
--- a/Formula/lua-language-server.rb
+++ b/Formula/lua-language-server.rb
@@ -45,8 +45,13 @@ class LuaLanguageServer < Formula
   end
 
   test do
+    require "open3"
     output = /Content-Length: \d+\r\n\r\n/
 
-    assert_match output, pipe_output("#{bin}/lua-language-server", 0)
+    Open3.popen2(bin/"lua-language-server") do |stdin, stdout|
+      stdin.write "\n"
+      sleep 10
+      assert_match output, stdout.readline
+    end
   end
 end
```
`popen2` is better than `fork` since `fork` doesn't let you capture stdin/stdout. Let's err on the side of `sleep`ing too long. VMs get a bit weird whenever you're doing things that require `sleep`.

**Comment by clason** [comment]
```
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/lua-language-server.rb:54:in `readline'
EOFError: end of file reached
```
:/

**Comment by carlocab** [comment]
Hmm. That's not good. Can we try passing it a Lua chunk? Maybe it doesn't like getting `\n`.

**Comment by carlocab** [comment]
Ah, yea, it'll want some JSON, won't it. Very strange...

**Comment by clason** [comment]
Yeah. Maybe I'm looking down the wrong pipe?

**Comment by carlocab** [comment]
Maybe? Is it sending stuff to `stderr` now?

**Comment by carlocab** [comment]
Try using `popen2e` instead. `popen2e` combines `stdout` and `stderr`

**Comment by carlocab** [comment]
Though, if `popen2e` works it's possible the original test also will with just a `2>&1` at the end of the command.

**Comment by clason** [comment]
Yeah, that makes no difference.

**Comment by carlocab** [comment]
Let's try this...
```diff
diff --git a/Formula/lua-language-server.rb b/Formula/lua-language-server.rb
index 0a9ed9c5d5f..c87be5d95b9 100644
--- a/Formula/lua-language-server.rb
+++ b/Formula/lua-language-server.rb
@@ -47,6 +47,11 @@ class LuaLanguageServer < Formula
   test do
     output = /Content-Length: \d+\r\n\r\n/
 
-    assert_match output, pipe_output("#{bin}/lua-language-server", 0)
+    lua_ls = spawn bin/"lua-language-server", out: "lua-ls.out"
+    sleep 30
+    assert_match output, (testpath/"lua-ls.out").read
+  ensure
+    Process.kill "TERM", lua_ls
+    Process.wait lua_ls
   end
 end
```
This works for me on the existing version.

**Comment by clason** [comment]
(although your snippet works locally; might as well push the changes)

**Comment by clason** [comment]
Hmm, doesn't seem to work on Linux (of course...) Guess we'll just have to wait for the next release and hope for the best...

Still, as always I appreciate your help! ❤️

**Comment by carlocab** [comment]
Really just on Linux then. Always such a pain...

**Comment by clason** [comment]
(we can still punt to 2.6.1...)

**Comment by carlocab** [comment]
We could, but I'm not convinced this will work on Linux in 2.6.1. I've been able to repro the Linux failure locally (need to run the test without a tty). I've checked that my change works under the same conditions that the previous test failed, so 🤞.

**Comment by carlocab** [comment]
Yes, I understand. My point is that I'm not convinced that the old test passes on Linux with `--HEAD`. Though I guess it would be easy for me to check now that I fired up my container...

**Review by carlocab — APPROVED** [review]
As it turns out, the original test works with `--HEAD` on Linux, even with no TTY.

Ah well. This should pass now, so I guess we don't have to punt? 🙂

**Comment by clason** [comment]
Might as well go with it, after all the work you put in! :D 

(But I can still revert for 2.6.1, if I remember to do so...)

**Comment by carlocab** [comment]
Compared to some other nonsense I've fixed around here, this was nothing 😄

**Pull request closed without merging**
