### PR TITLE
fourstore: depend on `avahi` on Linux.

### PR DESCRIPTION
**Pull request by carlocab**
Fixes a linkage failure spotted at #109781.

This looks like opportunistic linkage picked up at #103916.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Rebased

**Review by SMillerDev — DISMISSED** [review]

**Comment by cho-m** [comment]
Looks like stable code fails to build with our new Linux toolchain (glibc 2.35 + gcc 11):
```
  In file included from /usr/include/signal.h:62,
                   from /home/linuxbrew/.linuxbrew/Cellar/glib/2.74.0/include/glib-2.0/glib/gbacktrace.h:38,
                   from /home/linuxbrew/.linuxbrew/Cellar/glib/2.74.0/include/glib-2.0/glib.h:36,
                   from query-datatypes.h:4,
                   from filter.h:4,
                   from filter-datatypes.c:28:
  /usr/include/x86_64-linux-gnu/bits/types/sigval_t.h:13:3: error: #error "sigval_t defined for standard not including union sigval"
     13 | # error "sigval_t defined for standard not including union sigval"
        |   ^~~~~
```

Could try https://github.com/4store/4store/commit/c5a56d7c7504551a1f2fff6c16c4d9a440e4a317 to fix error.

May also need `-fcommon`.

---

Formula could also be considered for deprecation. Other repositories have been dropping it: https://repology.org/project/4store/history (Nix, Gentoo, Debian/Ubuntu)

**Comment by cho-m** [comment]
@carlocab, I think this is ready now and can remove `do not merge`.

Can consider follow up PR to deprecate once merged.

**Review by cho-m — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
cc @carlocab

**Comment by cho-m** [comment]
Removing `do not merge` as it has been a couple weeks since I added changes to this PR.

May follow up with deprecation PR.

**Pull request closed without merging**
