### PR TITLE
sourcekitten 0.14.1

### PR DESCRIPTION
**Pull request by jpsim**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

This is an update. Thanks!

### CODE REVIEW

**Comment by jpsim** [comment]
Going to bed now. @norio-nomura do you think you could investigate the failures? I suspect they're related to jpsim/SourceKitten#215.

**Comment by apjanke** [comment]
Looks like the error is in the post-install relocation steps.

```
==> Finishing up
ln -s ../Cellar/sourcekitten/0.14.0/bin/sourcekitten sourcekitten
mkdir -p /usr/local/Frameworks/SourceKittenFramework.framework
ln -s ../../Cellar/sourcekitten/0.14.0/Frameworks/SourceKittenFramework.framework/Resources Resources
ln -s ../../Cellar/sourcekitten/0.14.0/Frameworks/SourceKittenFramework.framework/SourceKittenFramework SourceKittenFramework
mkdir -p /usr/local/Frameworks/SourceKittenFramework.framework/Versions
ln -s ../../../Cellar/sourcekitten/0.14.0/Frameworks/SourceKittenFramework.framework/Versions/A A
ln -s ../../../Cellar/sourcekitten/0.14.0/Frameworks/SourceKittenFramework.framework/Versions/Current Current
Error: Failed changing dylib ID of /usr/local/Cellar/sourcekitten/0.14.0/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/A/SWXMLHash
  from @rpath/SWXMLHash.framework/Versions/A/SWXMLHash
    to /usr/local/opt/sourcekitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/A/SWXMLHash
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formula against it.
```

That's a long-looking path. Maybe it needs `headerpady_max_install_names` like `ffmpeg2theora` or [`shapelib` uses](https://github.com/Homebrew/homebrew-core/blob/b2301c6b46e135f5137b67c5584d4cf28a26d2ef/Formula/shapelib.rb#L26)? I can't tell if that other linked change makes the path lengths longer.

**Comment by norio-nomura** [comment]
I opened PR https://github.com/jpsim/SourceKitten/pull/257 for fix.
But I don't know how can I test `brew install --build-bottle --verbose sourcekitten` with using that commit.

**Comment by ilovezfs** [comment]
you add a `patch do` block.

**Comment by norio-nomura** [comment]
@ilovezfs Thanks!

I confirmed `brew install --HEAD --build-bottle --verbose sourcekitten` with following patch:
```diff
diff --git a/Formula/sourcekitten.rb b/Formula/sourcekitten.rb
index be7b42b..65c65eb 100644
--- a/Formula/sourcekitten.rb
+++ b/Formula/sourcekitten.rb
@@ -6,6 +6,8 @@ class Sourcekitten < Formula
       revision: "890c00b19875b2ac5de3d6936fbb5a3bdebec929"
   head "https://github.com/jpsim/SourceKitten.git"
 
+  head "https://github.com/jpsim/SourceKitten.git", :branch => "fix-homebrew-bottling-error", :revision => "334ea5d5043d5397877bb737c8ecbe2ac1dbd77d"
+
   bottle do
     cellar :any
     sha256 "6a1b1dfd5844e55e6282f32e3ca743af19855a645f8c6ccbf57b8944a99e6904" => :el_capitan
```

**Comment by jpsim** [comment]
I've cut a new release with jpsim/SourceKitten#257 and have updated the formula in this PR to point to it (0.14.1).

**Comment by jpsim** [comment]
and CI seems to agree 😄

**Comment by zmwangx** [comment]
Merged as c4e762a. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
