### PR TITLE
proj.4 4.9.3

### PR DESCRIPTION
**Pull request by jenshnielsen**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Needed rebuilding of a lot of formulas. Hope I got it right

**Comment by jenshnielsen** [comment]
Looks like this is now timing out on the brew build bot when building mapnik. I guess the timeout needs to be increased?

**Comment by zmwangx** [comment]
I wonder why `libproj.9.dylib => libproj.12.dylib` in `4.9.2 => 4.9.3`. Ugh.

**Comment by apjanke** [comment]
Everything's passing now. Looks like you got it right, and someone bumped the timeout so `mapnik` built.

I'm having trouble pulling this.

```

$ brew pull --bottle https://github.com/Homebrew/homebrew-core/pull/5289
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-core/pull/5289.patch
==> Applying patch
Applying: proj.4 4.9.3
Applying: GDAL: revision for proj
Applying: libgaiagraphics: revision for proj
Applying: libgeotiff: revision for proj
Applying: liblwgeom: revision for proj
Applying: libspatialite: revision for proj
Applying: mapnik: revision for proj
Applying: mapserver: revision for proj
Applying: osm2pgsql: revision for proj
Applying: postgis: revision for proj
Applying: spatialite-gui: revision for proj
Applying: spatialite-tools: revision for proj
Applying: librasterlite: revision for proj
==> Patch closes issue #5289
==> Fetching patch (bottle commit)
Patch: https://github.com/BrewTestBot/homebrew-core/compare/homebrew:master...pr-5289.patch
==> Applying patch
Applying: proj.4 4.9.3
Applying: GDAL: revision for proj
Applying: libgaiagraphics: revision for proj
Applying: libgeotiff: revision for proj
Applying: liblwgeom: revision for proj
Applying: libspatialite: revision for proj
Applying: mapnik: revision for proj
Applying: mapserver: revision for proj
Applying: osm2pgsql: revision for proj
Applying: postgis: revision for proj
Applying: spatialite-gui: revision for proj
Applying: spatialite-tools: revision for proj
Applying: librasterlite: revision for proj
Applying: gdal: update 1.11.5_1 bottle.
Applying: libgaiagraphics: update 0.5_2 bottle.
Applying: libgeotiff: update 1.4.1_2 bottle.
Applying: liblwgeom: update 2.1.5_3 bottle.
Applying: librasterlite: update 1.1g_2 bottle.
Applying: libspatialite: update 4.3.0a_3 bottle.
Applying: mapnik: update 3.0.12_1 bottle.
fatal: sha1 information is lacking or useless (Formula/mapnik.rb).
error: could not build fake ancestor
Patch failed at 0020 mapnik: update 3.0.12_1 bottle.
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Error: Patch failed to apply: aborted.
```

I can't see why this is happening. None of the commits in this PR messed with the `bottle` stanza. Maintainers, any ideas here?

**Comment by apjanke** [comment]
Might be caused by the recent update to the `mapnik` bottle.

```
$ brew log mapnik | cat
commit 97d4a9774ab03c8a97fe5dc759cb3e2a465c056a
Author: BrewTestBot <brew-test-bot@googlegroups.com>
Date:   Fri Sep 30 05:22:38 2016 +0100

    mapnik: update 3.0.12 bottle.
```

I'm going to try just rebasing this on `master` and see what happens.

**Comment by apjanke** [comment]
(And @jenshnielsen, if you see this and have time, could you rebase this PR on master yourself?)

**Comment by jenshnielsen** [comment]
rebased, there is also a bunch of formulas in science and versions that probably needs to be rebuild. I don't know the standard way of handling that.

**Comment by ilovezfs** [comment]
That is the responsibility of the tap. But it is considered courteous to at least give them a heads up, and if you're feeling nice to do the revision bumps for them in subsequent PRs after the core PR is merged.

**Comment by zmwangx** [comment]
@apjanke FYI you can always check out this branch's ancestor, `brew pull` from that, then rebase on master (resolving conflicts manually along the way if necessary). Avoids a lengthy rebuild that way.

**Comment by MikeMcQuaid** [comment]
Remember you can now commit to many maintainers PRs now, too.

**Comment by apjanke** [comment]
> you can always check out this branch's ancestor, `brew pull` from that, then rebase on master (resolving conflicts manually along the way if necessary).

That worked. Thanks @zmwangx!

Merged. Thank you for your contribution to Homebrew, @jenshnielsen!

**Comment by apjanke** [comment]
I put in revision bump PRs for `homebrew-science`, `homebrew-versions`, and `homebrew-x11`.

https://github.com/Homebrew/homebrew-science/pull/4395
https://github.com/Homebrew/homebrew-versions/pull/1409
https://github.com/Homebrew/homebrew-x11/pull/251

**Pull request closed without merging**
