### PR TITLE
imagemagick 7.0.9-6

### PR DESCRIPTION
**Pull request by ath0mas**
Should brew mirror imagemagick when merging

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @ath0mas!!

**Comment by chenrui333** [comment]
For the record.

Warning: The Bintray mirror https://dl.bintray.com/homebrew/mirror/ImageMagick-7.0.9-6.tar.xz is not reachable (HTTP status code 404).
Warning: Do you need to upload it with `brew mirror imagemagick`?

**Comment by Bo98** [comment]
Yeah, you need to do `brew mirror imagemagick`. Or I think I can do it.

**Comment by Bo98** [comment]
Just did it now. The mirror should be up now.

**Pull request closed without merging**
