### PR TITLE
gcc@11 13.2.0

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Invalid. Not sure what went wrong:

```console
$ brew livecheck gcc@11
gcc@11: 11.4.0 ==> 11.4.0
$ brew bump gcc@11
==> gcc@11 is up to date!
Current formula version:  11.4.0
Latest livecheck version: 11.4.0
Latest Repology version:  not found
Open pull requests:       gcc@11 13.2.0 (https://github.com/Homebrew/homebrew-core/pull/138590)
Closed pull requests:     none
```

**Comment by osalbahr** [comment]
> Invalid. Not sure what went wrong:
> 
> ```
> $ brew livecheck gcc@11
> gcc@11: 11.4.0 ==> 11.4.0
> $ brew bump gcc@11
> ==> gcc@11 is up to date!
> Current formula version:  11.4.0
> Latest livecheck version: 11.4.0
> Latest Repology version:  not found
> Open pull requests:       gcc@11 13.2.0 (https://github.com/Homebrew/homebrew-core/pull/138590)
> Closed pull requests:     none
> ```

Yeah, not sure either. For context, I was running`brew bump --open-pr`. Is that a bad idea?

**Comment by ZhongRuoyu** [comment]
> For context, I was running `brew bump --open-pr`. Is that a bad idea?

Not really a bad one. The problem is that it shouldn't really open these PRs even with `--open-pr`. Is your `brew` on the latest `master`?

**Comment by osalbahr** [comment]
> > For context, I was running `brew bump --open-pr`. Is that a bad idea?
> 
> Not really a bad one. The problem is that it shouldn't really open these PRs even with `--open-pr`. Is your `brew` on the latest `master`?

Yeah, I believe so.

```console
$ brew -v
Homebrew 4.1.3-58-g3f49592
Homebrew/homebrew-core (git revision 3203311860b; last commit 2023-08-04)
Homebrew/homebrew-cask (git revision 9b3e6f547c; last commit 2023-08-05)
$ brew config
HOMEBREW_VERSION: 4.1.3-58-g3f49592
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f4959218105749e219087a53fb136d22d86f071
Last commit: 9 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3203311860bec05349db0e5fba07f9fcab575f34
Core tap last commit: 15 minutes ago
Core tap branch: bump-criterion-2.4.2
Core tap JSON: 05 Aug 00:50 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
```

**Comment by osalbahr** [comment]
> > For context, I was running `brew bump --open-pr`. Is that a bad idea?
> 
> Not entirely a bad one (I believe many are doing this but we seldom see duplicate/invalid PRs). The problem is that it shouldn't really open these PRs even with `--open-pr`. Is your `brew` on the latest `master`?

Actually..... no, I wasn't on the latest `master`. I think `brew` commands don't know about `git bisect` and I forgot to terminate it. Anyways, I was 25 commits behind, so I don't know if it's the reason.

```console
$ git branch
* (no branch, bisect started on master)
  master
  stable
$ brew update
Already up-to-date.
$ git checkout master
Previous HEAD position was 3f4959218 Merge pull request #15811 from MikeMcQuaid/sharding_fixes
Switched to branch 'master'
Your branch is behind 'origin/master' by 25 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git pull
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 76 (delta 16), reused 73 (delta 16), pack-reused 0
Unpacking objects: 100% (76/76), 39.60 KiB | 488.00 KiB/s, done.
From https://github.com/Homebrew/brew
 * [new branch]          dependabot/bundler/Library/Homebrew/rubocop-sorbet-0.7.1 -> origin/dependabot/bundler/Library/Homebrew/rubocop-sorbet-0.7.1
Updating 6b2876c0e..3f4959218
Fast-forward
 .github/workflows/tests.yml                        |   2 +
 Library/Homebrew/Gemfile.lock                      |   4 +-
 Library/Homebrew/cask/audit.rb                     |  18 +-
 Library/Homebrew/cask/cask_loader.rb               |   5 +-
 Library/Homebrew/cli/named_args.rb                 |  60 +--
 Library/Homebrew/cmd/log.rb                        |   2 +-
 Library/Homebrew/dev-cmd/bottle.rb                 |  22 +-
 Library/Homebrew/dev-cmd/bump.rb                   | 440 ++++++++++++++-------
 Library/Homebrew/dev-cmd/create.rb                 |   2 +-
 Library/Homebrew/dev-cmd/extract.rb                |   2 +-
 Library/Homebrew/dev-cmd/pr-pull.rb                |   8 +-
 Library/Homebrew/development_tools.rb              |   2 +-
 Library/Homebrew/extend/os/dev-cmd/bottle.rb       |   6 +-
 Library/Homebrew/extend/os/linux/dev-cmd/bottle.rb |  12 -
 .../Homebrew/extend/os/linux/development_tools.rb  |   2 +-
 Library/Homebrew/extend/os/mac/dev-cmd/bottle.rb   |   5 +
 .../Homebrew/extend/os/mac/development_tools.rb    |   2 +-
 Library/Homebrew/formula_cellar_checks.rb          |   2 +
 Library/Homebrew/formula_creator.rb                |   2 +-
 Library/Homebrew/formula_path.sh                   |   2 +-
 Library/Homebrew/formulary.rb                      |  15 +-
 Library/Homebrew/readall.rb                        |   2 +-
 ...addressable@2.8.4.rbi => addressable@2.8.5.rbi} |   8 +-
 .../{zeitwerk@2.6.10.rbi => zeitwerk@2.6.11.rbi}   |   2 +-
 Library/Homebrew/tap.rb                            |  36 +-
 Library/Homebrew/test/cleanup_spec.rb              |   2 +-
 Library/Homebrew/test/dev-cmd/create_spec.rb       |   2 +-
 Library/Homebrew/test/formula_installer_spec.rb    |   8 +-
 Library/Homebrew/test/formula_spec.rb              |   4 +-
 Library/Homebrew/test/formulary_spec.rb            |   8 +-
 .../helper/spec/shared_examples/formulae_exist.rb  |   4 +-
 Library/Homebrew/upgrade.rb                        |  10 +-
 Library/Homebrew/vendor/bundle/bundler/setup.rb    |   4 +-
 .../data/unicode.data                              | Bin
 .../lib/addressable.rb                             |   0
 .../lib/addressable/idna.rb                        |   0
 .../lib/addressable/idna/native.rb                 |   0
 .../lib/addressable/idna/pure.rb                   |   0
 .../lib/addressable/template.rb                    |   0
 .../lib/addressable/uri.rb                         |  53 ++-
 .../lib/addressable/version.rb                     |   2 +-
 bin/brew                                           |  68 ++--
 42 files changed, 544 insertions(+), 284 deletions(-)
 delete mode 100644 Library/Homebrew/extend/os/linux/dev-cmd/bottle.rb
 rename Library/Homebrew/sorbet/rbi/gems/{addressable@2.8.4.rbi => addressable@2.8.5.rbi} (98%)
 rename Library/Homebrew/sorbet/rbi/gems/{zeitwerk@2.6.10.rbi => zeitwerk@2.6.11.rbi} (99%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/data/unicode.data (100%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/lib/addressable.rb (100%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/lib/addressable/idna.rb (100%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/lib/addressable/idna/native.rb (100%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/lib/addressable/idna/pure.rb (100%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/lib/addressable/template.rb (100%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/lib/addressable/uri.rb (98%)
 rename Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/{addressable-2.8.4 => addressable-2.8.5}/lib/addressable/version.rb (98%)
```

**Pull request closed without merging**
