### PR TITLE
icon: Fix audit --strict expression order.

### PR DESCRIPTION
**Pull request by kpearson**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by kpearson** [comment]
I'm not sure what the @BrewTestBot wants me to do here.
The recipe has a test block.
I have run:
  * `brew install icon`
  * `brew uninstall icon`
  * `brew install --build-from-source icon`
  * `brew test icon` (it passes)
  * `brew audit icon`
  * `brew audit --new-formula icon`
  * `brew audit --strict icon`  
All complete without complaint.

@MikeMcQuaid please help. I have a few other pr's with the same issue. I'd like to bring them all up to par, I just can't don't know what I'm missing.

**Comment by MikeMcQuaid** [comment]
@kpearson There's no issue here, the build is green. We're just a little understaffed/busy right now but will merge this soon. Thanks!

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by kpearson** [comment]
Sorry, no hurry. I was just concerned about the bot asking for a “test this please”.

a, pre, code, a:link, body { word-wrap: break-word !important; }

**Pull request merged**
