### PR TITLE
lumo 1.2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
----> cp /private/tmp/lumo-20170321-61080-1a8039/lumo-1.2.0/tmp/node/7.5.0/node-v7.5.0/out/Release/node build/lumo
----> copied
Finished bundling. Nexe binary can be found in build/lumo
### Compiling Macro Namespaces
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /private/tmp/lumo-20170321-61080-1a8039/lumo-1.2.0/build/lumo
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /private/tmp/lumo-20170321-61080-1a8039/lumo-1.2.0/build/lumo
  Expected in: /usr/lib/libSystem.B.dylib

./scripts/aot-bundle-macros.sh: line 44: 39754 Trace/BPT trap: 5       $(pwd)/build/lumo --quiet -c target -sdk lumo-cljs/out/macros-tmp  <<REPL_INPUT
```
the usual el cap clock fun

**Comment by jab** [comment]
(For any other potential lumo fans following this, we'll be able to try https://anmonteiro.com/2017/02/compiling-clojurescript-projects-without-the-jvm/ once this lands:)

**Comment by anmonteiro** [comment]
this won't build, related issue https://github.com/Homebrew/homebrew-core/pull/10169.

I'm working on the next release

**Comment by jab** [comment]
Following along at anmonteiro/lumo#110. Thanks for the work on this and your other great work @anmonteiro!

**Pull request closed without merging**
