### PR TITLE
nuxeo 8.10

### PR DESCRIPTION
**Pull request by akervern**

### CODE REVIEW

**Comment by akervern** [comment]
Hi, I got those error during the first build. But after doing some `brew tap XXX` as expected the build passed; I thought it was related to my environment. 
So... I just don't understand where those errors are tied from. Any hints?

**Comment by dunn** [comment]
I think there's an issue with Jenkins.  Hold tight.

**Comment by ilovezfs** [comment]
upgrading xcode.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by woodruffw** [comment]
Thanks @akervern! For future reference, `<name> <version>` is the preferred format for commits that update a packages' version.

**Pull request merged**
