### PR TITLE
tfschema: remove terraform dep

### PR DESCRIPTION
**Pull request by chenrui333**
tfschema: remove terraform dep

---

relates to 
- #139538
- https://github.com/minamijoyo/tfschema/issues/50

### CODE REVIEW

**Comment by iMichka** [comment]
Need to remove the `depends_on "terraform" => :test` line too

**Comment by minamijoyo** [comment]
Hi, all! Thanks for maintaining the Homebrew's formula. I am the author of tfschema.

For build dependencies, tfscehma depends on legacy hashicorp/terraform v0.15.0 for historical reasons. We cannot upgrade to the latest terraform as a build dependency, and we are planning to remove it: https://github.com/minamijoyo/tfschema/issues/32
So, the tfschema won't depend on BUSL's Terraform v1.6+.

For runtime dependencies, tfschema depends on the Terraform provider's cache but not on the Terraform CLI. Note that the provider binary remains MPL2.

For test dependencies, if you want to download the provider, you can do it with curl or something; if you test compatibility with the provider cache generated by OpenTofu, you will need OpenTofu anyway. It depends on how much you want to test.

**Comment by chenrui333** [comment]
per discussions, close this PR for now (waiting for opentofu release is ready)

**Comment by chenrui333** [comment]
@minamijoyo thanks for the writeup, we can revisit this PR once opentofo is ready for use :)

**Pull request closed without merging**
