### PR TITLE
Bottle unneeded (g)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Extracted from https://github.com/Homebrew/homebrew-core/pull/79448
Part of https://github.com/Homebrew/homebrew-core/issues/75943

### CODE REVIEW

**Comment by SMillerDev** [comment]
There's some chicken-egg issues with git-annex

```
 Error: The `brew link` step did not complete successfully
Could not symlink bin/gerrit-cherry-pick
Target /opt/homebrew/bin/gerrit-cherry-pick
is a symlink belonging to gerrit-tools. You can unlink it:
  brew unlink gerrit-tools

To force the link and overwrite all conflicting files:
  brew link --overwrite git-gerrit

To list all files that would be deleted:
  brew link --overwrite --dry-run git-gerrit
```
```
==> /opt/homebrew/Cellar/git-tf/2.0.3.20131219/bin/git-tf
The operation couldn’t be completed. Unable to locate a Java Runtime.
```
```
 ==> /opt/homebrew/Cellar/google-sql-tool/r10/bin/google_sql --version
The operation couldn’t be completed. Unable to locate a Java Runtime.
```
```
 ==> /opt/homebrew/Cellar/growly/0.2.0/bin/growly echo Hello, world!
/opt/homebrew/Cellar/growly/0.2.0/bin/growly: line 64: growlnotify: command not found
```
```
==> /opt/homebrew/Cellar/gwt/2.9.0/bin/webAppCreator sh.brew.test
The operation couldn’t be completed. Unable to locate a Java Runtime.
```
```
 golo:
  * Stable: The source URL https://www.eclipse.org/downloads/download.php?file=/golo/golo-3.3.0.zip&r=1 is not reachable
```

**Comment by cho-m** [comment]
Still going to fail on `growly` and `gwt`.
Haven't had chance to look at those.

**Comment by cho-m** [comment]
We should probably consider disabling/removing `growly`.

It has a dependency `growlnotify`:
```md
installing growlnotify
----------------------
you can install growlnotify from [homebrew](http://mxcl.github.com/homebrew/) using

	$ brew install growlnotify

```
Which was deleted back in 2011: https://github.com/Homebrew/legacy-homebrew/issues/8316

**Review by cho-m — DISMISSED** [review]

**Comment by cho-m** [comment]
`golo` randomly fails. I'll move it separate PR to avoid having to keep retrying here.

**Review by cho-m — APPROVED** [review]

**Review by nandahkrishna — APPROVED** [review]

**Comment by carlocab** [comment]
No `all` bottle:

`gibo` - 40e69fd93811d914ececb790ad5980f487fa82f2
`goenv` - 026a85252e214ce783610880e12986c37cbb7580
`gerrit-tools` - 9d49216a8af717a175df4f48714e518211d118a7

**Pull request closed without merging**
