### PR TITLE
slurm 0.4.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
👍. 🎉 for getting rid of `scons`.

**Comment by ilovezfs** [comment]
@DomT4 too bad we couldn't replace it with https://en.wikipedia.org/wiki/Scone

**Comment by DomT4** [comment]
Sc(own)es are definitely better than Sc(on)s 😉.

**Pull request closed without merging**
