### PR TITLE
rust 1.54.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by branchvincent** [comment]
10.14/10.15:
```
Error: 16 failed steps!
brew install --build-from-source audacious
brew install --build-from-source bat
brew install --build-from-source cargo-instruments
brew install --build-from-source flux
brew install --build-from-source gegl
brew install --build-from-source gifski
brew install --build-from-source git-interactive-rebase-tool
brew install --build-from-source grin-wallet
brew test --retry --verbose ktmpl
brew install --build-from-source leaf-proxy
brew install --build-from-source pdfpc
brew fetch --build-from-source --retry qmmp
brew install --build-from-source rover
brew install --build-from-source vice
brew install --build-from-source visp
brew install --build-from-source watchman
```

11:
```
# Above plus
brew test --retry --verbose asuka
brew test --retry --verbose asuka
brew install --build-from-source deno
brew install --build-from-source pc6001vx
```

**Comment by cho-m** [comment]
Some potentially fixed items:
- `gifski` - #82961
- `grin-wallet` - #82421 
- `pdfpc` - #83058 
- `watchman` - #82474

I think the `bat` failure (and any similar failure) is important to look into as it looks like a change in Rust from 1.53 to 1.54. Probably requires some additional analysis to determine if upstream(s) need a tracking issue.

Some other failures have been occurring for almost every recent Rust update, so probably should compare with last few PRs. Can probably ignore the common failures.

**Comment by cho-m** [comment]
Any formula that fails with `error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements` is due to current git2 version:
- `bat` is fix upstream https://github.com/sharkdp/bat/pull/1761 but it is not available in release. We can either ignore, or apply patch.
- `git-interactive-rebase-tool` is fixed upstream https://github.com/MitMaro/git-interactive-rebase-tool/commit/f4d3026f23118d29a263bbca6c83f963e76c34c4 but not in a release
- `cargo-instruments` - still using older version in master branch.

**Comment by carlocab** [comment]
`asuka` was bumped in #83156. Might be fixed already.

**Comment by branchvincent** [comment]
Opened a pr for `cargo-instruments`: https://github.com/cmyr/cargo-instruments/pull/43

**Comment by branchvincent** [comment]
I think this is pretty close!

Pre-existing failures:
* `vice`: missing glew

New failures:
* `audacious`
* `flux`: https://github.com/influxdata/flux/pull/3905 (included in `v0.124.0`)
* `ktmpl`: blocked on https://github.com/jimmycuadra/ktmpl/pull/6
* `leaf-proxy`: #83372
* `rover`: #83175
* `visp`

**Comment by carlocab** [comment]
`visp`'s dependency on Rust is pretty remote. It would be very surprising if the failure were related to this version bump.

**Comment by branchvincent** [comment]
Not seeing any build failure with `visp` after downloading the bottle and trying against latest `master`:
```
brew install ./rust--1.54.0.big_sur.bottle.tar.gz
brew install -s visp
```

also, double checked the arm failures and all were pre-existing.

i think this is ready?

**Review by carlocab — APPROVED** [review]
Nice work, @branchvincent!

**Pull request closed without merging**
