### PR TITLE
robot-framework 4.1

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
```
Error: 1 problem in 1 formula detected
Error: No such file or directory @ realpath_rec - /home/runner
robot-framework:
  * Binaries built for a non-native architecture were installed into robot-framework's prefix.
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/robot-framework/4.1/libexec/lib/python3.9/site-packages/selenium/webdriver/firefox/x86/x_ignore_nofocus.so
```

**Comment by carlocab** [comment]
Let's have a closer look at where this failure is coming from.

**Comment by carlocab** [comment]
This is what was caught by the audit on Linux:
```
❯ file x_ignore_nofocus.so
x_ignore_nofocus.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=e61dfc1eda85dd44faca4fdd7715f302a9077b63, not stripped
```
@Homebrew/linux do you want to do anything about this? Does this thing even work if you try to link to it on 64-bit Linux? Can we just delete it?

**Review by carlocab — APPROVED** [review]
Let's fix the audit failure at the next update, since the existing bottle will fail the audit anyway.

**Pull request closed without merging**
