### PR TITLE
grpc 1.24.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
In file included from src/core/lib/security/credentials/alts/alts_credentials.cc:21:
In file included from ./src/core/lib/security/credentials/alts/alts_credentials.h:26:
In file included from ./src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26:
In file included from ./src/core/tsi/alts/handshaker/transport_security_common_api.h:29:
src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.h:12:10: fatal error: 'upb/generated_util.h' file not found
#include "upb/generated_util.h"
         ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Need to wait for this (https://github.com/grpc/grpc/pull/20662) to be released to fix the compilation issue.

**Comment by chenrui333** [comment]
Created a new PR to hopefully solve the issue.
https://github.com/Homebrew/homebrew-core/pull/45711

**Pull request closed without merging**
