### PR TITLE
ltex-ls-plus 18.3.0 (new formula)

### PR DESCRIPTION
**Pull request by ivaquero**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ivaquero** [comment]
Failed due to this `ltex-ls-plus`'s repo is a fork of [ltex-ls](https://github.com/valentjn/ltex-ls), however, `ltex-ls` has not got an update for more than a year with lots of issues unsolved.

**Review by chenrui333 — APPROVED** [review]

**Comment by ivaquero** [comment]
@chenrui333 Thank you so much!

**Review by ZhongRuoyu — CHANGES_REQUESTED** [review]
Sorry, but unfortunately this project does not seem to be notable enough for inclusion in `homebrew/core`. I suggest hosting this formula in a third-party tap until it meets the criteria listed in our ["Acceptable Formulae"](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff) documentation. Specifically:

> GitHub repositories should have >=30 forks, >=30 watchers or >=75 stars

**Comment by ivaquero** [comment]
Hmmm... Alright. Since this project is a continuation of `ltex-ls` which is included in homebrew-core, I think it's necessary to add a suggestion in `ltex-ls.rb` to inform users to star this project to get it satisfy the criteria.

**Comment by ZhongRuoyu** [comment]
> I think it's necessary to add a suggestion in `ltex-ls.rb` to inform users to star this project to get it satisfy the criteria.

We don't do such advertisement to encourage users to have preference for one software project to another.

Thanks for submitting the PR, but passing on this, sorry! Though, as I said earlier, you may want to consider hosting this formula in a [tap](https://docs.brew.sh/Taps). In fact, this way of distributing software is already used by many, including [Apple](https://github.com/apple/homebrew-apple) and [Microsoft](https://github.com/powershell/homebrew-tap). When the repository becomes popular enough, we'll be happy to reconsider accepting it.

**Pull request closed without merging**
