### PR TITLE
llvm, lld and flang 19.1.4

### PR DESCRIPTION
**Pull request by eleanordoesntcode**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting? (I am not currently on a machine where I can compile it)
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting? (same as before)
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`? (untested, but it should)

-----

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
Thanks!

**Review by chenrui333 — APPROVED** [review]

**Comment by eleanordoesntcode** [comment]
It seems one of the runners is stuck on installing brew, should we merge (since all other tests succeeded) or rerun the tests?

**Comment by eleanordoesntcode** [comment]
no idea why it randomly fails on macOS 14-x86_64

**Comment by chenrui333** [comment]
> no idea why it randomly fails on macOS 14-x86_64

what is the error? I think the runner has some issue

**Pull request merged**
