### PR TITLE
libzzip 0.13.69

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
Release not yet announced upstream.

**Comment by ilovezfs** [comment]
where does it get announced?

**Comment by JCount** [comment]
@ilovezfs I was going by the information provided by https://sourceforge.net/projects/zziplib/ , which still shows version `0.13.68` as the current version.

**Comment by ilovezfs** [comment]
https://github.com/gdraheim/zziplib/issues/45

**Pull request closed without merging**
