### PR TITLE
secure urls

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

There is an open PR for `bash`: https://github.com/Homebrew/homebrew-core/pull/2332,
but they don't seem to step on each other's toes.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The bash fixes have already been merged to master, and yes the PRs do collide. Please just remove bash from this PR entirely.

**Comment by vszakats** [comment]
Removed!

**Comment by ilovezfs** [comment]
@vszakats Thanks! Sorry for not mentioning what I was doing with bash before in order to get #2332 to turn :green_apple:.

**Comment by vszakats** [comment]
(I should have known that this URL update will now be bot-enforced for any pending PR)
No worries at all :)

**Comment by UniqMartin** [comment]
Just a heads-up that the [failures in the 10.10/10.11 build](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/3690/) are probably related to Homebrew/brew#378 and (unsurprisingly) not caused by this PR. I'm looking into the problem! But this PR should still be safe to merge, assuming no bottles are being pulled.

**Comment by DomT4** [comment]
Yeah, no need for bottle updates purely for this change, so let's go ahead and get this shipped. Merged. Thanks once more Viktor 😺

**Pull request closed without merging**
