### PR TITLE
bzt 1.16.2

### PR DESCRIPTION
**Pull request by greyfenrir**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Try this:
```diff
diff --git a/Formula/bzt.rb b/Formula/bzt.rb
index 2be79a3eba0..2c2ed05e9da 100644
--- a/Formula/bzt.rb
+++ b/Formula/bzt.rb
@@ -190,9 +190,6 @@ class Bzt < Formula
     ENV["SDKROOT"] = MacOS.sdk_path if MacOS.version == :sierra
 
     virtualenv_install_with_resources
-
-    # remove non-native binary
-    (libexec/"lib/python3.9/site-packages/selenium/webdriver/firefox/x86/x_ignore_nofocus.so").unlink if OS.linux?
   end
 
   test do
```
I tried to push this fix but I have no access to your fork.

**Comment by cclauss** [comment]
> depends_on "python@3.9"

python@3.10

**Comment by greyfenrir** [comment]
> I tried to push this fix but I have no access to your fork.
thanks a lot!

**Review by SMillerDev — APPROVED** [review]

**Comment by greyfenrir** [comment]
sorry, I closed this by mistake

**Pull request closed without merging**
