### PR TITLE
docker-machine-driver-xhyve 0.2.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zchee** [comment]
@ilovezfs Thanks upgrade :)

But current version(v0.2.3) needs

```diff
diff --git a/Formula/docker-machine-driver-xhyve.rb b/Formula/docker-machine-driver-xhyve.rb
index 94b45e5..67a9e6e 100644
--- a/Formula/docker-machine-driver-xhyve.rb
+++ b/Formula/docker-machine-driver-xhyve.rb
@@ -27,10 +27,10 @@ class DockerMachineDriverXhyve < Formula
       if build.head?
         git_hash = `git rev-parse --short HEAD --quiet`.chomp
         git_hash = "HEAD-#{git_hash}"
-        ENV["CGO_LDFLAGS"] = "#{build_root}/vendor/build/lib9p/lib9p.a -L#{build_root}/vendor/lib9p"
-        ENV["CGO_CFLAGS"] = "-I#{build_root}/vendor/lib9p"
-        system "make", "lib9p"
       end
+      ENV["CGO_LDFLAGS"] = "#{build_root}/vendor/build/lib9p/lib9p.a -L#{build_root}/vendor/lib9p"
+      ENV["CGO_CFLAGS"] = "-I#{build_root}/vendor/lib9p"
+      system "make", "lib9p"
       system "go", "build", "-x", "-o", bin/"docker-machine-driver-xhyve",
       "-ldflags",
       "'-w -s'",
```

What should I do? Should I post a new PR?

**Comment by MikeMcQuaid** [comment]
@zchee Feel free to create a new PR 👍

**Comment by zchee** [comment]
@MikeMcQuaid got it, will send a new pull request.

BTW, Is there problem in posted diff?
I was tried brew install for test, but can't installing because occur `you use Sierra`(? I forgot) error.

**Comment by MikeMcQuaid** [comment]
@zchee Looks fine to me.

**Comment by zchee** [comment]
@MikeMcQuaid OK, thanks :)

**Comment by ilovezfs** [comment]
Yes, I know that's the required change as it's already in the head spec and I'd already tested that with the new version, but just hadn't gotten around to updating this PR yet but I guess I'll close it if someone else is now working on it ...

**Comment by zchee** [comment]
@MikeMcQuaid @ilovezfs I created new pull request. PTAL.

**Pull request closed without merging**
