### PR TITLE
jpeg-turbo 2.1.5.1

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Linux:
```
==> Pouring jruby--9.4.1.0.x86_64_linux.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink bin/erb
Target /home/linuxbrew/.linuxbrew/bin/erb
is a symlink belonging to ruby. You can unlink it:
  brew unlink ruby

To force the link and overwrite all conflicting files:
  brew link --overwrite jruby

To list all files that would be deleted:
  brew link --overwrite --dry-run jruby

Possible conflicting files are:
/home/linuxbrew/.linuxbrew/bin/erb -> /home/linuxbrew/.linuxbrew/Cellar/ruby/3.2.0/bin/erb
```

**Comment by chenrui333** [comment]
> Linux:
> 
> ```
> ==> Pouring jruby--9.4.1.0.x86_64_linux.bottle.tar.gz
> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
> Could not symlink bin/erb
> Target /home/linuxbrew/.linuxbrew/bin/erb
> is a symlink belonging to ruby. You can unlink it:
>   brew unlink ruby
> 
> To force the link and overwrite all conflicting files:
>   brew link --overwrite jruby
> 
> To list all files that would be deleted:
>   brew link --overwrite --dry-run jruby
> 
> Possible conflicting files are:
> /home/linuxbrew/.linuxbrew/bin/erb -> /home/linuxbrew/.linuxbrew/Cellar/ruby/3.2.0/bin/erb
> ```

that should be fixed in https://github.com/Homebrew/homebrew-core/pull/122356

**Comment by p-linnane** [comment]
All macOS jobs ran successfully.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
🚀

**Pull request closed without merging**
