### PR TITLE
Remove `bottle :unneeded` on Bintray

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Part of https://github.com/Homebrew/homebrew-core/issues/74335 and https://github.com/Homebrew/homebrew-core/issues/75943

Needed for https://github.com/Homebrew/brew/pull/11239

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Maintainers: feel free to commit directly to this on any failures. I'm almost 100% sure `denominator` will fail.

**Comment by samford** [comment]
Neither `denominator` nor `kaitai-struct-compiler` have migrated from Bintray yet, so we can't update the URLs to fix those. Do we want to keep those commits (with CI failing) or drop them to allow this PR to pass CI?

`groovysdk` was also failing but they've migrated to Artifactory and I updated the URL in #75955. Rebasing this PR will address that failure but I wanted to hear what we want to do with the other failures before unnecessarily setting off another CI run.

**Comment by Bo98** [comment]
Bintray had a brown-out so it will pass again if we re-run.

Obviously we still ideally want to update the URLs but there's not much we can do if there's simply no other source yet.

**Comment by samford** [comment]
The brownout seems to be over now, so I've rebased this to pick up the `groovysdk` update. Let's see how it does this time around.

**Comment by MikeMcQuaid** [comment]
I'm going to rebase/hold off on this until https://github.com/Homebrew/brew/pull/11253 is merged.

**Comment by samford** [comment]
This is currently failing because the `denominator` install step doesn't seem to make `denominator` executable or available in `bin`. I don't have much experience with Java formulae but I compared this to similar formulae and this seemed to be the minimum to make it work:

```ruby
(libexec/"bin").install "denominator-cli-#{version}-fat.jar" => "denominator"
(libexec/"bin/denominator").chmod 0755
(bin/"denominator").write_env_script libexec/"bin/denominator", JAVA_HOME: Formula["openjdk"].opt_prefix
```

**Comment by Bo98** [comment]
`bin.write_jar_script` is probably better:

```rb
(libexec/"bin").install "denominator-cli-#{version}-fat.jar"
bin.write_jar_script libexec/"bin/denominator-cli-#{version}-fat.jar", "denominator"
```

**Pull request closed without merging**
