### PR TITLE
workflows/tests: upload event payload

### PR DESCRIPTION
**Pull request by carlocab**
We can use this to improve our caching, because this allows us to track
down the last commit that has the artifact we're looking for.

### CODE REVIEW

**Comment by Bo98** [comment]
> this allows us to track down the last commit that has the artifact we're looking for.

Assuming both uploads happen? Sounds like it should be a part of the same artifact upload.

With this as is, it sounds like you could:

1. Push a bad commit allow it to upload the bottle
2. Force push a second commit removing the bad commit
3. Force push a third commit between the event payload updating and the bottles being uploaded, that appears as no change compared to the second commit

**Comment by Bo98** [comment]
Oh right I think I maybe follow now, I assume this isn't actually replacing the bottle artifact check but works in tandem?

**Comment by carlocab** [comment]
Homebrew/homebrew-test-bot#933

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by carlocab** [comment]
Oops. This broke any workflow that looks for the PR number (e.g. `automerge`). I'm away from my computer at the moment, but I'll have a fix this evening. FYI @Homebrew/core

**Comment by carlocab** [comment]
> Oops. This broke any workflow that looks for the PR number (e.g. `automerge`). I'm away from my computer at the moment, but I'll have a fix this evening. FYI @Homebrew/core

#132231

**Pull request merged**
