### PR TITLE
aws-okta 0.24.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by svanharmelen** [comment]
I'm getting this error when trying to update:

```
==> Updated Formulae
aws-okta ✔                     ffmpeg                         git-annex                      knot                           paket                          src                            webpack
==> Upgrading 1 outdated package:
aws-okta 0.23.1 -> 0.23.2
==> Upgrading aws-okta
==> Downloading https://homebrew.bintray.com/bottles/aws-okta-0.23.2.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "aws-okta"
Download failed: https://homebrew.bintray.com/bottles/aws-okta-0.23.2.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for aws-okta: govendor
==> Installing aws-okta dependency: govendor
==> Downloading https://homebrew.bintray.com/bottles/govendor-1.0.9.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/b5/b5bcf9c902173a5ea922be49153fb3a5f59d44534a7f4dbbb5b9f536c0607fa6?__gda__=exp=1569393903~hmac=1eac840a0b0591efcd8cf302ce14f4d6300fa76206dfd62102c2681e2a089bff&response-co
######################################################################## 100.0%
==> Pouring govendor-1.0.9.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/govendor/1.0.9: 5 files, 11.5MB
==> Downloading https://github.com/segmentio/aws-okta/archive/v0.23.2.tar.gz
==> Downloading from https://codeload.github.com/segmentio/aws-okta/tar.gz/v0.23.2
######################################################################## 100.0%
==> govendor sync
==> go build -ldflags -X main.Version=0.23.2
Last 15 lines from /Users/svanharmelen/Library/Logs/Homebrew/aws-okta/02.go:
go: finding github.com/spf13/pflag v1.0.0
go: finding github.com/segmentio/backo-go v0.0.0-20160424052352-204274ad699c
go: finding github.com/xtgo/uuid v0.0.0-20140804021211-a0b114877d4c
go: finding golang.org/x/sys v0.0.0-20190710143415-6ec70d6a5542
go: finding github.com/marshallbrekka/go-u2fhost v0.0.0-20170128051651-72b0e7a3f583
go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: finding github.com/vaughan0/go-ini v0.0.0-20130923145212-a98ad7ee00ec
go: finding golang.org/x/net v0.0.0-20190628185345-da137c7871d7
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/marshallbrekka/go.hid v0.0.0-20161227002717-2c1c4616a9e7
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/vitaminwater/cgo.wchar v0.0.0-20160320123332-5dd6f4be3f2a
# github.com/keybase/go-keychain
../../../../pkg/mod/github.com/keybase/go-keychain@v0.0.0-20190604185112-cc436cc9fe98/macos_1.10.go:89:13: could not determine kind of name for C.SecTrustedApplicationCreateFromPath

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by chenrui333** [comment]
Close in favor of https://github.com/Homebrew/homebrew-core/pull/44603

**Comment by chenrui333** [comment]
@svanharmelen that happened due to a merge mistake I made earlier, it should be fixed for you now. :)

**Comment by svanharmelen** [comment]
Thanks @chenrui333, works like a charm 👍

**Comment by chenrui333** [comment]
glad it works! 😄

**Pull request closed without merging**
