### PR TITLE
krb5 1.21.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Error: Operation already in progress for krb5.formula
  Another active Homebrew process is already using krb5.formula.
  Please wait for it to finish or terminate it to continue.
  Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew install --formula gnu-tar` exited with 1.
```

**Review by MikeMcQuaid — COMMENTED** [review]
Need to have a workaround for `gnu-tar` here, I'll take a look on the Homebrew/brew side.

**Comment by MikeMcQuaid** [comment]
Rerun CI.

**Review by fxcoudert — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks Mike! 🚀

**Pull request merged**
