### PR TITLE
scipy 1.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

previous efforts, #68097

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /opt/homebrew/opt/python@3.9/bin/python3 setup.py build --fcompiler=gnu95
Error: 'pybind11' must be installed before running the build.
```

**Comment by lordsutch** [comment]
It appears the formula for pybind11 is failing to install the Python bindings, and I don't see an obvious reason why it's not doing so. It might have something to do with this commit changing how the pybind11 installation process works: https://github.com/Homebrew/homebrew-core/commit/2ea148047054cbc18a51e3f65eb688e7b24d61b9

**Comment by carlocab** [comment]
Seems weird that the way pybind11 was installed would matter... but, @henryiii, would you happen to know how to fix this?

**Comment by henryiii** [comment]
Pybind11 never has installed the python tooling in Homebrew, that has not changed. What changed was that an `import pybind11` was added to scipy 1.6.0. That (obviously) requires the python parts, not just the headers and CMake files.

There are a few options. We could add the Python files in pybind11's formula, or we could download them in the recipe as a resource. Normally this would happen via pip & pyproject.toml, or pybind11 would be versioned in via a submodule and stored in the SDist as a copy.

If scipy provides external access to the ABI, then the formula addition is the correct way to go. If it doesn't provide access, then any option works.

**Comment by carlocab** [comment]
>We could add the Python files in pybind11's formula

This seems like the way to go, in order to avoid potential duplication of this sometime down the line.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/68342 is merged, so rebased this against master.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Big Sur failure:
```
Error: 1 failed steps!
brew test --retry --verbose networkit
```
Documented in https://github.com/Homebrew/homebrew-core/issues/66450.

**Pull request closed without merging**
