### PR TITLE
libmongoc: fix note conflict with libbson

### LINKED ISSUE #7291: `brew install libmongoc`: Error: The `brew link` step did not complete successfully
```
==> Pouring libmongoc-1.4.2.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /Users/timothee/homebrew
Could not symlink include/libbson-1.0/bcon.h
Target /Users/timothee/homebrew/include/libbson-1.0/bcon.h
is a symlink belonging to libbson. You can unlink it:
  brew unlink libbson

To force the link and overwrite all conflicting files:
  brew link --overwrite libmongoc

To list all files that would be deleted:
  brew link --overwrite --dry-run libmongoc

Possible conflicting files are:
/Users/timothee/homebrew/include/libbson-1.0/bcon.h -> /Users/timothee/homebrew/Cellar/libbson/1.4.0/include/libbson-1.0/bcon.h
/Users/timothee/homebrew/include/libbson-1.0/bson-atomic.h -> /Users/timothee/homebrew/Cellar/libbson/1.4.0/include/libbson-1.0/bson-atomic.h
/Users/timothee/homebrew/include/libbson-1.0/bson-clock.h -> /Users/timothee/homebrew/Cellar/libbson/1.4.0/include/libbson-1.0/bson-clock.h

```

```
brew upgrade libbson
Error: libbson 1.4.0 already installed
```

```
brew gist-logs libmongoc
Error: No logs. 
```
(the `no logs` may be caused by https://github.com/Homebrew/legacy-homebrew/issues/44706 Unable to do `brew gist-logs` for certain formulas)

### PR DESCRIPTION
**Pull request by timkuijsten**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

fixes #7291

### CODE REVIEW

**Comment by apjanke** [comment]
Conflicts are symmetric: the `libbson` formula should probably also get a `conflicts_with "libmongoc"`. Would you mind adding that as part of this PR?

**Comment by timkuijsten** [comment]
> Would you mind adding that as part of this PR?

Just did that :)

**Comment by apjanke** [comment]
Thanks!

Looks good to me.

**Comment by apjanke** [comment]
We should probably report this upstream to MongoDB, too. It's unusual behavior for a library to install its dependencies in the global location. Messes with dependency-tracking package managers. :)

**Comment by timkuijsten** [comment]
Yeah, maybe @ajdavis knows of a better solution..

**Comment by ajdavis** [comment]
Thanks everyone. I understand the arguments for unbundling libbson from libmongoc, but the arguments in *favor* of bundling outweigh them, so when you download libmongoc tarball you'll continue to get the libbson code along with it. *However*, when you're installing libmongoc as a Homebrew package, things should be different. I've just thought of a better approach for Homebrew.

Homebrew shouldn't consider these two packages as conflicting. Instead, libmongoc should depend on libbson. When libmongoc installs itself, it should add ``--with-libbson=system`` to its ``./configure`` arguments.

It may require a bit of tweaking to make that work, but I think it's the right approach.

Also, we need to ensure that libmongoc has the exact same version of libbson as its own version: if libmongoc is 1.4.2, libbson must also be 1.4.2.

**Comment by apjanke** [comment]
> Homebrew shouldn't consider these two packages as conflicting. Instead, libmongoc should depend on libbson. When libmongoc installs itself, it should add --with-libbson=system to its ./configure arguments.

Sounds good to me. As long as there's a supported option to do this, Homebrew can work with it.

> Also, we need to ensure that libmongoc has the exact same version of libbson as its own version: if libmongoc is 1.4.2, libbson must also be 1.4.2.

We don't have a mechanism for enforcing this programmatically. We'd have to make do with comments in the formulae reminding maintainers to keep them in sync, which seems doable to me.

I did a quick pass at building libmongoc this way, and got an error in the `configure` step.

```

checking for BSON... no
configure: error:

  --------------------------------------
   The libbson-1.0 library could not be
   found on your system. Please install
   libbson-1.0  development  package or
   set --with-libbson=auto.
  --------------------------------------

```

Might be a version mismatch, since our `libmongoc` is at 1.4.2, but `libbson` is at 1.4.0. I'll try updating our `libbson` and fiddling with things and see if I can make it work.

Thanks for the input and quick response, @ajdavis!

**Comment by ajdavis** [comment]
Happy to help - I'm not a Homebrew expert but I'll watch this ticket and pitch in where I can.

**Comment by apjanke** [comment]
I've put in a PR #7305 to bump `libmongoc` to 1.5.0, which gets it in sync with our current `libbson`, which just got bumped to 1.5.0. That'll make it easier to do these potential changes.

**Comment by apjanke** [comment]
Okay, Homebrew `libmongoc` is at 1.5.0 now, matching our `libbson`.

I tried building libmongoc with `--with-libbson=system` again, but still got that error. Full build logs here: https://gist.github.com/fc2e829805ffef20c95d9013c5da13dc

Not sure why it's not finding libbson. My pkg-config is reporting it as present.

```
$ pkg-config --libs libbson-1.0
-L/usr/local/Cellar/libbson/1.5.0/lib -lbson-1.0
```

**Comment by apjanke** [comment]
At any rate, I think we should go ahead and merge this for now, adding the `conflicts_with` stanzas, since they correctly reflect the current state of our packages, and try to work on getting `libmongoc` to use our provided `libbson` after that. Any objections?

**Comment by ajdavis** [comment]
Sounds good to me, for now.

**Comment by apjanke** [comment]
Aha, got it working: I just needed to make `pkg-config` available to the Homebrew formula. See #7306.

With that change, `libmongoc` and `libbson` can be installed without conflict, and `libmongoc` does not install its bundled `libbson`, which is what we want for Homebrew.

**Comment by timkuijsten** [comment]
Awesome progress!

Is it still possible to install 1.4.2? My package is only tested with that release.

**Comment by apjanke** [comment]
> Is it still possible to install 1.4.2? My package is only tested with that release.

I'm afraid not; Homebrew only has support for one version of a package.

If you'd like to install 1.4.2, you can grab the old version of the formula and add it to a custom tap as `mongo-c-driver@1.4.2.rb` and install that; then you'll have full control over the exact version installed.

(I think you could also check out an earlier revision of the `homebrew-core` tap that still has the 1.4.2 `libmongoc` formula, install it from there, and then `brew pin libmongoc`. But that's not a very reproducible workflow.)

**Comment by apjanke** [comment]
#7306 is now closed in favor of a larger refactor at #7352.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-core/pull/7352 was merged but thanks for this PR.

**Pull request closed without merging**
