### PR TITLE
node 7.2.0

### PR DESCRIPTION
**Pull request by JLHwung**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Please try bumping the vendored npm to 4.0.2 as well.

**Comment by JLHwung** [comment]
@ilovezfs The upstream said node 7.2.0 is bundled with npm 3.10.9, shall we track upstream dependencies and keep `npm` as 3.10.9?

[Quoted](https://github.com/Homebrew/homebrew-core/pull/5312#issuecomment-250073134) from @DomT4

> We track what Node bundles upstream, unless what Node bundles upstream has security or major usability problems resolved in a newer release.

**Comment by DomT4** [comment]
I quit, so it's pretty much up to ILZ, but I think both Homebrew and Node upstream find more stability in tracking the Node version as much as possible. I've seen less complaints directed at Node/npm at least since we adopted that policy.

**Comment by ilovezfs** [comment]
Sure 3.10.9 will be fine, though it's annoying since we don't have a separate npm formula and current stable npm is 4.0.2 not 3.10.9.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@JLHwung thanks for your contribution to Homebrew!

**Comment by JLHwung** [comment]
@ilovezfs You're very welcome.

**Comment by JLHwung** [comment]
@ilovezfs We might not see a `npm@4` bundled release on v7 according to https://github.com/nodejs/node/pull/9284#issuecomment-256406965. It is marked as *semver-major* and 8.0.0 milestone.

**Pull request closed without merging**
