### PR TITLE
rdb 1.0.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not marked as the latest release yet: https://github.com/HDT3213/rdb/releases

**Comment by carlocab** [comment]
> Not marked as the latest release yet: https://github.com/HDT3213/rdb/releases

Seems more like an oversight upstream. Probably worth filing an issue to check.

**Comment by ZhongRuoyu** [comment]
> > Not marked as the latest release yet: https://github.com/HDT3213/rdb/releases
> 
> Seems more like an oversight upstream. Probably worth filing an issue to check.

- https://github.com/HDT3213/rdb/issues/14

**Comment by ZhongRuoyu** [comment]
From https://github.com/HDT3213/rdb/issues/14:

> v1.0.7​ only updated the API, and the terminal tool has not changed, so homebrew package does not need to be updated.

🤔

**Review by carlocab — APPROVED** [review]

**Pull request merged**
