### PR TITLE
traefik@1 1.7.34

### PR DESCRIPTION
**Pull request by djerfy**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
```
021-12-12T09:29:39.6947660Z Done in 25.97s.
2021-12-12T09:29:39.6948140Z [34m==>[0m [1myarn install[0m
2021-12-12T09:29:39.6948480Z yarn install v1.22.17
2021-12-12T09:29:39.6948840Z [1/4] Resolving packages...
2021-12-12T09:29:39.6949380Z success Already up-to-date.
2021-12-12T09:29:39.6949740Z Done in 0.20s.
2021-12-12T09:29:39.6950190Z [34m==>[0m [1myarn run build[0m
2021-12-12T09:29:39.6950510Z yarn run v1.22.17
2021-12-12T09:29:39.6951160Z $ ng build --prod --no-delete-output-path --output-path ../static/
2021-12-12T09:29:39.6951970Z [0mDate: [1m[37m2021-12-12T09:29:33.720Z[39m[22m[0m
2021-12-12T09:29:39.6952580Z [0mHash: [1m[37m92fe05e183902681ce2d[39m[22m[0m
2021-12-12T09:29:39.6953130Z [0mTime: [1m[37m13875[39m[22mms[0m
2021-12-12T09:29:39.6953990Z [0mchunk {[1m[33m0[39m[22m} [1m[32mmain.3701bd4b7ac6c4ba2420.bundle.js[39m[22m (main) 802 kB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
2021-12-12T09:29:39.6955530Z [0mchunk {[1m[33m1[39m[22m} [1m[32mpolyfills.2e14d04e2d28adfd5d49.bundle.js[39m[22m (polyfills) 63.5 kB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
2021-12-12T09:29:39.6956780Z [0mchunk {[1m[33m2[39m[22m}  (styles) [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
2021-12-12T09:29:39.6957810Z [0mchunk {[1m[33m3[39m[22m} [1m[32minline.318b50c57b4eba3d437b.bundle.js[39m[22m (inline) 796 bytes [1m[33m[entry][39m[22m[1m[32m [rendered][39m[22m[0m
2021-12-12T09:29:39.6959140Z [0mchunk {[1m[33mscripts[39m[22m} [1m[32mscripts.3e6371d09f8b5694a1f9.bundle.js[39m[22m (scripts) 422 kB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
2021-12-12T09:29:39.6960030Z [0m[0m
2021-12-12T09:29:39.6960520Z [0m[1m[31mERROR in ./src/app.sass[39m[22m[0m
2021-12-12T09:29:39.6961220Z [0m[1m[31mModule build failed: Error: Cannot find module 'node-sass'[39m[22m[0m
2021-12-12T09:29:39.6961890Z [0m[1m[31mRequire stack:[39m[22m[0m
2021-12-12T09:29:39.6962900Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/sass-loader/lib/loader.js[39m[22m[0m
2021-12-12T09:29:39.6964450Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js[39m[22m[0m
2021-12-12T09:29:39.6966060Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js[39m[22m[0m
2021-12-12T09:29:39.6967660Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/NormalModule.js[39m[22m[0m
2021-12-12T09:29:39.6969390Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/NormalModuleFactory.js[39m[22m[0m
2021-12-12T09:29:39.6970970Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/Compiler.js[39m[22m[0m
2021-12-12T09:29:39.6972440Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/webpack.js[39m[22m[0m
2021-12-12T09:29:39.6973900Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/tasks/build.js[39m[22m[0m
2021-12-12T09:29:39.6975420Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/commands/build.js[39m[22m[0m
2021-12-12T09:29:39.6979260Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/lib/cli/index.js[39m[22m[0m
2021-12-12T09:29:39.6980660Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/bin/ng[39m[22m[0m
2021-12-12T09:29:39.6981810Z [0m[1m[31m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)[39m[22m[0m
2021-12-12T09:29:39.6982790Z [0m[1m[31m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)[39m[22m[0m
2021-12-12T09:29:39.6983630Z [0m[1m[31m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m[22m[0m
2021-12-12T09:29:39.6984470Z [0m[1m[31m    at require (internal/modules/cjs/helpers.js:93:18)[39m[22m[0m
2021-12-12T09:29:39.6985670Z [0m[1m[31m    at Object.<anonymous> (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/sass-loader/lib/loader.js:3:14)[39m[22m[0m
2021-12-12T09:29:39.6986900Z [0m[1m[31m    at Module._compile (internal/modules/cjs/loader.js:1085:14)[39m[22m[0m
2021-12-12T09:29:39.6987800Z [0m[1m[31m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m[22m[0m
2021-12-12T09:29:39.6988680Z [0m[1m[31m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m[22m[0m
2021-12-12T09:29:39.6989560Z [0m[1m[31m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)[39m[22m[0m
2021-12-12T09:29:39.6990440Z [0m[1m[31m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m[22m[0m
2021-12-12T09:29:39.6991220Z [0m[1m[31m    at require (internal/modules/cjs/helpers.js:93:18)[39m[22m[0m
2021-12-12T09:29:39.6992440Z [0m[1m[31m    at loadLoader (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js:18:17)[39m[22m[0m
2021-12-12T09:29:39.6994280Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)[39m[22m[0m
2021-12-12T09:29:39.6996290Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)[39m[22m[0m
2021-12-12T09:29:39.6998100Z [0m[1m[31m    at /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:176:18[39m[22m[0m
2021-12-12T09:29:39.6999790Z [0m[1m[31m    at loadLoader (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js:47:3)[39m[22m[0m
2021-12-12T09:29:39.7000940Z [0m[1m[31mERROR in ./src/app.sass[39m[22m[0m
2021-12-12T09:29:39.7001850Z [0m[1m[31mModule build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'node-sass'[39m[22m[0m
2021-12-12T09:29:39.7002650Z [0m[1m[31mRequire stack:[39m[22m[0m
2021-12-12T09:29:39.7003670Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/sass-loader/lib/loader.js[39m[22m[0m
2021-12-12T09:29:39.7005210Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js[39m[22m[0m
2021-12-12T09:29:39.7006860Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js[39m[22m[0m
2021-12-12T09:29:39.7008450Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/NormalModule.js[39m[22m[0m
2021-12-12T09:29:39.7010070Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/NormalModuleFactory.js[39m[22m[0m
2021-12-12T09:29:39.7011650Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/Compiler.js[39m[22m[0m
2021-12-12T09:29:39.7013150Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/webpack.js[39m[22m[0m
2021-12-12T09:29:39.7014630Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/tasks/build.js[39m[22m[0m
2021-12-12T09:29:39.7016100Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/commands/build.js[39m[22m[0m
2021-12-12T09:29:39.7017590Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/lib/cli/index.js[39m[22m[0m
2021-12-12T09:29:39.7019020Z [0m[1m[31m- /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/@angular/cli/bin/ng[39m[22m[0m
2021-12-12T09:29:39.7020230Z [0m[1m[31m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)[39m[22m[0m
2021-12-12T09:29:39.7021280Z [0m[1m[31m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)[39m[22m[0m
2021-12-12T09:29:39.7022160Z [0m[1m[31m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m[22m[0m
2021-12-12T09:29:39.7022960Z [0m[1m[31m    at require (internal/modules/cjs/helpers.js:93:18)[39m[22m[0m
2021-12-12T09:29:39.7024160Z [0m[1m[31m    at Object.<anonymous> (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/sass-loader/lib/loader.js:3:14)[39m[22m[0m
2021-12-12T09:29:39.7025420Z [0m[1m[31m    at Module._compile (internal/modules/cjs/loader.js:1085:14)[39m[22m[0m
2021-12-12T09:29:39.7026280Z [0m[1m[31m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m[22m[0m
2021-12-12T09:29:39.7027170Z [0m[1m[31m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m[22m[0m
2021-12-12T09:29:39.7028000Z [0m[1m[31m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)[39m[22m[0m
2021-12-12T09:29:39.7028840Z [0m[1m[31m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m[22m[0m
2021-12-12T09:29:39.7029610Z [0m[1m[31m    at require (internal/modules/cjs/helpers.js:93:18)[39m[22m[0m
2021-12-12T09:29:39.7030840Z [0m[1m[31m    at loadLoader (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js:18:17)[39m[22m[0m
2021-12-12T09:29:39.7032640Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)[39m[22m[0m
2021-12-12T09:29:39.7034710Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)[39m[22m[0m
2021-12-12T09:29:39.7036520Z [0m[1m[31m    at /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:176:18[39m[22m[0m
2021-12-12T09:29:39.7038170Z [0m[1m[31m    at loadLoader (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js:47:3)[39m[22m[0m
2021-12-12T09:29:39.7039820Z [0m[1m[31m    at /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/NormalModule.js:195:19[39m[22m[0m
2021-12-12T09:29:39.7041400Z [0m[1m[31m    at /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:367:11[39m[22m[0m
2021-12-12T09:29:39.7043020Z [0m[1m[31m    at /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:172:11[39m[22m[0m
2021-12-12T09:29:39.7044680Z [0m[1m[31m    at loadLoader (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js:32:11)[39m[22m[0m
2021-12-12T09:29:39.7046500Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)[39m[22m[0m
2021-12-12T09:29:39.7048440Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)[39m[22m[0m
2021-12-12T09:29:39.7050270Z [0m[1m[31m    at /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:176:18[39m[22m[0m
2021-12-12T09:29:39.7051960Z [0m[1m[31m    at loadLoader (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js:47:3)[39m[22m[0m
2021-12-12T09:29:39.7053760Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)[39m[22m[0m
2021-12-12T09:29:39.7055720Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)[39m[22m[0m
2021-12-12T09:29:39.7057510Z [0m[1m[31m    at /private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:176:18[39m[22m[0m
2021-12-12T09:29:39.7059200Z [0m[1m[31m    at loadLoader (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/loadLoader.js:47:3)[39m[22m[0m
2021-12-12T09:29:39.7061020Z [0m[1m[31m    at iteratePitchingLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)[39m[22m[0m
2021-12-12T09:29:39.7062860Z [0m[1m[31m    at runLoaders (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/loader-runner/lib/LoaderRunner.js:365:2)[39m[22m[0m
2021-12-12T09:29:39.7064660Z [0m[1m[31m    at NormalModule.doBuild (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/NormalModule.js:182:3)[39m[22m[0m
2021-12-12T09:29:39.7066520Z [0m[1m[31m    at NormalModule.build (/private/tmp/traefikA1-20211212-51435-1x98ja7/traefik-1.7.34/src/github.com/traefik/traefik/webui/node_modules/webpack/lib/NormalModule.js:275:15)[39m[22m[0m
2021-12-12T09:29:39.7067630Z error Command failed with exit code 1.
2021-12-12T09:29:39.7068260Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bayandin** [comment]
It looks like node-gyp (a dependency of node-sass) picks up `python3` instead of `python2` and failes to build node-sass module:
```
 gyp verb check python checking for Python executable \"python3\" in the PATH
  gyp verb `which` succeeded python3 /usr/bin/python3
  gyp ERR! configure error 
  gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];
  gyp ERR! stack   File \"<string>\", line 1
  gyp ERR! stack     import sys; print \"%s.%s.%s\" % sys.version_info[:3];
  gyp ERR! stack                       ^
  gyp ERR! stack SyntaxError: invalid syntax
```

**Comment by iMichka** [comment]
I thought node 14 supported Python3? Or am y mistaken?
Also, it might be a node-sass problem, not a node problem.

**Comment by bayandin** [comment]
> Also, it might be a node-sass problem, not a node problem.

This.

But it could be caused by something else, there's a recent issue in node-sass upstream https://github.com/sass/node-sass/issues/3217:

> Node 14 with 4.14 shouldn't be falling back to a manual build, you've got something else going on

**Comment by bayandin** [comment]
Ok, it looks like `node-sass` doesn't have prebuilt binaries for Apple Silicon. We could add `depends_on arch: :x86_64` to get a green build for this.
And I have no idea how did we get bottles for `arm64_big_sur` before.

**Comment by iMichka** [comment]
Yeah, something changed. There are other formulae with `node@14` impacted. `ship` for example. I don't think it's on our end, but I am unsure. We maybe missed something with all the red CI.

I'll go for `depends_on arch: :x86_64` then. Let me try that.

**Comment by bayandin** [comment]
I guess if all affected formulae depend on `yarn` and versioned `node@` then https://github.com/Homebrew/homebrew-core/pull/90839 could be the reason (before it worked because `yarn` used `node` and now it doesn't because it uses versioned `node@`)

**Comment by bayandin** [comment]
I don't think audit will allow to do so

**Comment by iMichka** [comment]
We can make an exception. I think there was already one in place as this formula already depended on both versions?

**Comment by bayandin** [comment]
It looks like we can build `node-sass` separately, and it will make node happy on Apple Silicon.
I'll create a separate formula for `node-sass@4` and use it for failed formulae.

**Comment by iMichka** [comment]
It worked. Is the `depends_on :macos # Due to Python 2` still needed?

**Comment by Bo98** [comment]
Yes node-sass 4 and earlier require Python 2.

**Comment by iMichka** [comment]
Ok, makes sense. So I guess a separate PR for `yarn` is now needed?

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
