### PR TITLE
z3 4.8.13

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Why are we rev-bumping `cryptol` and `klee`? Only `civl` had a linkage failure.

**Review by carlocab — CHANGES_REQUESTED** [review]
Are the `cryptol` and `klee` revision bumps necessary?

**Comment by carlocab** [comment]
```
  Missing libraries:
    unexpected (libaccapi.so)
    unexpected (libaccg.so)
    unexpected (libaccg2.so)
    unexpected (libaccn.so)
    unexpected (libcudadevice.so)
    unexpected (libnuma.so)
    unexpected (libpgc.so)
    unexpected (libpgmp.so)
```
Rev bumping `civl` isn't correct either, since `civl` has no linkage with `z3`. We don't even build anything in `civl`, so a rev bump doesn't change anything.

**Comment by chenrui333** [comment]
yeah, I was thinking it should be runtime dependencies on z3, so I updated those three.

I can revert the changes.

**Comment by carlocab** [comment]
Did you actually see any test failures for `cryptol` or `klee`? There aren't any from the first CI run. Only a linkage failure for `civl`. https://github.com/Homebrew/homebrew-core/runs/4260269082?check_suite_focus=true#step:10:101

`libz3` is unversioned, so we won't see any linkage failures from anything we actually built from source. We see it for `civl` since it ships pre-built binaries.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
