### PR TITLE
man-db 2.11.2

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
  man-db:
    * Stable: The source URL https://download.savannah.gnu.org/releases/man-db/man-db-2.11.2.tar.xz is not reachable (HTTP status code 404)
  Error: 1 problem in 1 formula detected
  Error: Stable: The source URL https://download.savannah.gnu.org/releases/man-db/man-db-2.11.2.tar.xz is not reachable (HTTP status code 404)
```

**Comment by SMillerDev** [comment]
re-running since that happened on ARM before too.

**Comment by dawidd6** [comment]
Aaand it happened on ARM now 😄

**Comment by dawidd6** [comment]
Maybe `using: :homebrew_curl` would help here?

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
