### PR TITLE
scala@2.11 2.11.12

### PR DESCRIPTION
**Pull request by 996refuse**
Update scala 2.11.11 to 2.11.12

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Looks like your test is failing:

```
        Testing scala@2.11
/usr/bin/sandbox-exec -f /tmp/homebrew20180129-58857-1fsyxvh.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scala@2.11.rb --verbose
==> /usr/local/Cellar/scala@2.11/2.11.12/bin/scala /tmp/scala@2.11-test-20180129-58858-udnyvh/Test.scala
cat: /release: No such file or directory
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
cat: /release: No such file or directory
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
error: Compile server encountered fatal condition: javax/tools/ToolProvider
Error: scala@2.11: failed
<0> expected but was
<1>.
```

Can you please follow the checklist and confirm if it works on your local machine, or if not, fix the test so that it functions?

**Comment by ilovezfs** [comment]
It's failing due to Java 9 as noted in https://github.com/Homebrew/homebrew-core/issues/19696.

Also, with Java 8 there is a problem with this version.

```
iMac-TMP:~ joe$ /usr/local/opt/scala\@2.11/bin/scala Test.scala 
cat: /release: No such file or directory
4
```

**Comment by muchrooms** [comment]
@vinyldarkscratch @ilovezfs 
/usr/local/Cellar/scala@2.11/2.11.12/bin/scala
Scala runner script trying to assume you have java 9 installed. And It looks like a regression bug.
https://github.com/scala/scala/pull/5588.

Finally, I patch [this](https://github.com/scala/scala/pull/5588/commits/60ea98e412de0a2a9f631a5b4b048107e0b251f0.patch) to the script, and It works fine on my mac (os x 10.9.5 java 1.6.0_65) .

**Comment by ilovezfs** [comment]
```
==> brew test scala@2.11 --verbose
==> FAILED
Testing scala@2.11
/usr/bin/sandbox-exec -f /tmp/homebrew20180130-52674-1g8aqwh.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scala@2.11.rb --verbose
==> /usr/local/Cellar/scala@2.11/2.11.12/bin/scala /tmp/scala@2.11-test-20180130-52675-jo8f0g/Test.scala
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
error: Compile server encountered fatal condition: javax/tools/ToolProvider
Error: scala@2.11: failed
<0> expected but was
<1>.
```

**Comment by ilovezfs** [comment]
Please feel free to open a fresh PR for this when it's working with Java 8 or Java 9.

**Pull request closed without merging**
