### PR TITLE
gnupg 2.2.23

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
See https://github.com/Homebrew/homebrew-core/pull/60282 regarding the `license`.

**Comment by SMillerDev** [comment]
Yeah, we might want to make that label less scary.

**Comment by miccal** [comment]
> Yeah, we might want to make that label less scary.

:ghost:

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @miccal  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
