### PR TITLE
infer 1.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
```
- Installed /private/tmp/infer-20201010-59941-152et32/opamroot/default/lib/stublibs/dllparmap_stubs.so.owner
Warning: nd: [WARNING] You have installed DLLs but the directory /private/tmp/infer-20201010-59941-152et32/opamroot/default/lib/stublibs is not mentioned in ld.conf
- Installed /private/tmp/infer-20201010-59941-152et32/opamroot/default/lib/parmap/META
- (cd _build; ocamldoc -man -man-mini parmap.ml parmap.mli)
- File "parmap.ml", line 209, characters 4-22:
- 209 |     Pervasives.at_exit finalize; (* register finalization function *)
-           ^^^^^^^^^^^^^^^^^^
- Alert deprecated: module Stdlib.Pervasives
- Use Stdlib instead.
- 
- If you need to stay compatible with OCaml < 4.07, you can use the 
- stdlib-shims library: https://github.com/ocaml/stdlib-shims
- File "parmap.ml", line 245, characters 4-22:
- 245 |     Pervasives.at_exit finalize; (* register finalization function *)
-           ^^^^^^^^^^^^^^^^^^
- Alert deprecated: module Stdlib.Pervasives
- Use Stdlib instead.
- 
- If you need to stay compatible with OCaml < 4.07, you can use the 
- stdlib-shims library: https://github.com/ocaml/stdlib-shims
- File "parmap.ml", line 321, characters 4-22:
- 321 | 	   Pervasives.at_exit finalize; (* register finalization function *)
-           ^^^^^^^^^^^^^^^^^^
- Alert deprecated: module Stdlib.Pervasives
- Use Stdlib instead.
- 
- If you need to stay compatible with OCaml < 4.07, you can use the 
- stdlib-shims library: https://github.com/ocaml/stdlib-shims
- File "parmap.ml", line 422, characters 4-22:
- 422 | 	   Pervasives.at_exit finalize; (* register finalization function *)
-           ^^^^^^^^^^^^^^^^^^
- Alert deprecated: module Stdlib.Pervasives
- Use Stdlib instead.
- 
- If you need to stay compatible with OCaml < 4.07, you can use the 
- stdlib-shims library: https://github.com/ocaml/stdlib-shims
- File "parmap.ml", line 573, characters 12-24:
- 573 |     let r = Array.create (l+1) (f lo (Array.unsafe_get a lo)) in
-                   ^^^^^^^^^^^^
- Alert deprecated: Stdlib.Array.create
- Use Array.make instead.
- test -d /private/tmp/infer-20201010-59941-152et32/opamroot/default/man/man3 || mkdir -p /private/tmp/infer-20201010-59941-152et32/opamroot/default/man/man3
- cp -p _build/Parmap.3o /private/tmp/infer-20201010-59941-152et32/opamroot/default/man/man3
∗ installed parmap.1.0-rc11
Done.
# Run eval $(opam env) to update the current shell environment
==> opam pin add ppx_tools 5.3+4.08.0 --locked
ppx_tools is now pinned to version 5.3+4.08.0

The following dependencies couldn't be met:
  - ppx_tools → ocaml < 4.10
      base of this switch (use `--unlock-base' to force)

[NOTE] Pinning command successful, but your installed packages may be out of sync.
'opam pin add ppx_tools 5.3+4.08.0 --locked' failed.
```

**Comment by jvillard** [comment]
I started tinkering with this and came up with https://github.com/jvillard/homebrew-core/commit/4cc9195c59e7fc3530e28250fa49c6a4bae952ed, which has a few more changes. Feel free to update your PR to incorporate these.

In particular it unlocks the hardcoded version of parmap that seems to be causing the compilation issues.

**Comment by chenrui333** [comment]
@jvillard, definitely welcome to open another PR to address this. I will focus on fixing the other PR build issues. Closing this for now.

**Comment by jvillard** [comment]
For reference: the new PR is at #62862.

**Comment by chenrui333** [comment]
Thanks @jvillard!

**Pull request closed without merging**
