### PR TITLE
dbhash 3.15.0

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks again @neutric. Do you think it may make sense to rename this to `sqlite-dbhash` for consistency with the other formulae you updated from the `sqlite` tarball?

**Comment by neutric** [comment]
@MikeMcQuaid That is a good idea. Makes it easier to discover when searching for `sqlite` without `--desc`. Feel free to quickly do the rename. Also: 👍  on https://changelog.com/podcast/223

**Comment by MikeMcQuaid** [comment]
Actually, may be fine as-is given there's also `sqldiff` and `sqlite-sqldiff` feels odd.

**Comment by neutric** [comment]
Fine with me.

**Pull request closed without merging**
