### PR TITLE
 ncspot: add clipboard functionality on macOS

### PR DESCRIPTION
**Pull request by mjclements**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

ncspot supports sharing via system clipboard, and it works on macOS. This PR just changes the build flags in the brew formula to enable it.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for the PR, @mjclements.

For future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings.

For new formulae:

> At Homebrew, we like to put the name of the formula up front like so: `foobar 7.3 (new formula)`.

For existing formulae:

> The preferred commit message format for simple version updates is `foobar 7.3` and for fixes is `foobar: fix flibble matrix.`.

Refer to the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

**Comment by carlocab** [comment]
Also, I noticed that your PR branch is also called `master`. Can you open a new PR that uses a PR branch of a different name? GitHub has issues with querying workflow runs associated with branches named `master`, and that means @BrewTestBot is unable to merge this PR.

When you do so, please amend your commit message to something like
```
ncspot: add clipboard functionality on macOS
```
or similar to adhere to our commit style guide.

You may also wish to bump the `revision` (either add `revision 1` or increment the `revision` right after `license`) so that users who have this installed get the updated version of the formula when they do `brew upgrade`. Thanks!

**Comment by Bo98** [comment]
Can you rebase this on the latest master so that it uses the correct OpenSSL version (which was recently pushed in 0f4ade2d5b00d299b398672ad0ca63fde8d3e5f0)?

**Comment by mjclements** [comment]
> Sorry for the information overload, but when you do the above can you rebase on the latest master so that it uses the correct OpenSSL version (which was recently pushed in [0f4ade2](https://github.com/Homebrew/homebrew-core/commit/0f4ade2d5b00d299b398672ad0ca63fde8d3e5f0))?

Will do!

**Comment by mjclements** [comment]
Thanks for being patient and helping me fix my mistakes. I've opened a new PR #85883 where I tried to take this.

**Pull request closed without merging**
