### PR TITLE
New Formula bazel@2.0.0

### PR DESCRIPTION
**Pull request by cxwx**
old version bazel for tensorflow build

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions) and why we might want to ship an older version?

**Comment by cxwx** [comment]
> Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions) and why we might want to ship an older version?
bazel of old version(<2.0.0) would help build tensorflow(2.1) tensorflow_cc(2.1). that cannot build with bazel-lastest.
And I'm not sure how to choose the name?  
bazel-for-tensorflow?

and I would try to add tensorflow_cc to formula after this formula.
If nobody need this formula, just delete this requset

**Comment by SMillerDev** [comment]
> Upstream should have a release branch for the versioned formulae version and still make security updates for that version, when necessary. For example, PHP 5.5 was not a supported version but PHP 7.2 was in January 2018.

Does it meet this criteria though?

**Comment by cxwx** [comment]
> > Upstream should have a release branch for the versioned formulae version and still make security updates for that version, when necessary. For example, PHP 5.5 was not a supported version but PHP 7.2 was in January 2018.
> 
> Does it meet this criteria though?

sadly not, I'm sorry

**Pull request closed without merging**
