### PR TITLE
Update mpv.rb

### PR DESCRIPTION
**Pull request by mathbunnyru**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

waf update to 1.9.2

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> waf update to 1.9.2

What's the benefit? Thanks!

**Comment by mathbunnyru** [comment]
@MikeMcQuaid just using the last version to prevent bugs.

**Comment by MikeMcQuaid** [comment]
What bugs in `mpv` manifest themselves by an outdated `waf`?

**Comment by mathbunnyru** [comment]
@MikeMcQuaid I think it's just a good choice to always use the most recent version. Of course, it's optional, but I think that's not a bad idea.

**Comment by MikeMcQuaid** [comment]
@mathbunnyru We're not in the habit of updating resources unless there's a known bug fixed by it. Thanks anyway!

**Pull request closed without merging**
