### PR TITLE
sha2: update homepage and download urls

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
- [x] passes `brew audit --online sha2`

verified sha256 of updated download url

### CODE REVIEW

**Comment by JCount** [comment]
Note this change is necessary because the site's cert expired on January 5, 2017.

**Comment by woodruffw** [comment]
Might be worth bugging upstream to fix their cert before making this change. If they don't respond/don't really care, this is :+1: by me.

**Comment by MikeMcQuaid** [comment]
> Might be worth bugging upstream to fix their cert before making this change.

Yeh, 👍 to at least notify them and 👍 to merge afterwards.

**Comment by JCount** [comment]
Okay, thanks. I will notify them.

**Review by ilovezfs — APPROVED** [review]

**Pull request merged**
