### PR TITLE
poppler 0.57.0

### PR DESCRIPTION
**Pull request by edporras**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Didn't bump dependency revisions as it was not needed for 0.56.0

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please bump revisions for `diff-pdf`, `pdf2htmlex`, `pdftoedn`, and `pdftoipe`.

**Comment by edporras** [comment]
Ok 😀

I saw the 1.3.0 notes stating `revision` is now deprecated and replaced by `rebuild` so I'll switch them and bump the number for each.

**Comment by ilovezfs** [comment]
@edporras rebuild pertains to the bottle block. At formula global scope, it still must be revision.

**Comment by edporras** [comment]
oh. Ok. Oops. Will fix.

**Comment by ilovezfs** [comment]
@edporras needs pdftopipe also

**Comment by edporras** [comment]
@ilovezfs Ok. I assume you mean `pdftoipe`, right? I don't see a `pdftopipe`.

**Comment by ilovezfs** [comment]
yep

**Comment by fxcoudert** [comment]
Thanks @edporras for the pull request!

**Pull request closed without merging**
