### PR TITLE
cantera 2.3.0 (migrated formula)

### PR DESCRIPTION
**Pull request by alishahm**
moved from Homebrew/science to Homebrew/core

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alishahm** [comment]
Please update https://github.com/Homebrew/homebrew-science/blob/master/tap_migrations.json if this PR is merged.

**Comment by vinyldarkscratch** [comment]
@alishahm Seems like there's a problem with building this formula.  Does this formula compile on your local machine?  This looks like a linkage problem with `fmt` in particular.

**Comment by alishahm** [comment]
Seems to have built previously. Removing it and rebuilding is giving me the same error. Cantera's list of issues on their Git mentions being able to resolve it using an older version of fmt. See https://github.com/Cantera/cantera/issues/470. Trying to figure out how to reference an older version without going in and modifying any files in cantera's repo. Any ideas?

**Comment by vinyldarkscratch** [comment]
Unfortunately, there isn't a way to refer to an older version of a formula now.  Because they're not supporting the latest `fmt` yet, all I can say is that it's an upstream issue that needs to be resolved before this PR can be accepted... 🙁

I'm looking at the issue you linked, and it seems that this might have been fixed in the HEAD version.  So, all we can really do is wait for them to submit a patch?

**Comment by speth** [comment]
Cantera maintainer here. The Cantera 2.3.0 maintenance branch already contains a patch for `fmt` 4.0.0: cantera/cantera@195469ecb19. I can tag this commit and the formula can be updated to reference that, or that particular patch can be included in the Homebrew formula.

**Comment by fxcoudert** [comment]
Hi @speth, thanks for commenting. We'd prefer to wait until a suitable version is released, with this change, rather than patch 2.3.0. When is 2.3.1 expected?

**Comment by speth** [comment]
Since Homebrew now also includes the backwards-incompatible upgrade to SCons 3.0, there are more extensive updates to Cantera which are not suitable for inclusion in a 2.3.1 release. That said, we are anticipating the release of Cantera 2.4.0 with support for these updated dependencies within the next month.

**Comment by fxcoudert** [comment]
I'll be closing this pull request for now, but we would welcome a new one once cantera 2.4.0 is released.

**Pull request closed without merging**
