### PR TITLE
node 14.1.0

### PR DESCRIPTION
**Pull request by rwoll**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by rwoll** [comment]
Node 14.0.0 (the current install target of `brew install node`) breaks several stream based libs (https://github.com/maxogden/extract-zip/issues/94#issuecomment-620059341); 14.1.0 patches some of the breaking changes.

Related: https://github.com/maxogden/extract-zip/issues/94, https://github.com/microsoft/playwright/issues/1988

**Comment by rwoll** [comment]
@issyl0 Could you help me determine the bottle SHAs for this latest update?

At first I looked here https://nodejs.org/dist/v14.1.0/SHASUMS256.txt, but the previous revision doesn't have the previous bottle hashes, so I'm assuming the bottles are different artifacts.

**Comment by rwoll** [comment]
> At first I looked here https://nodejs.org/dist/v14.1.0/SHASUMS256.txt, but the previous revision doesn't have the previous bottle hashes, so I'm assuming the bottles are different artifacts.

Ah, just read more on what bottles are and now realize they wouldn't be in Node's official repo. Based on https://github.com/Homebrew/brew/blob/master/docs/Bottles.md#creation, it looks like the bottle SHAs will get updated out of band once a Hombrew Team Member triggers a bot build. Is that correct, or should future MRs include the bottle SHA bumps?

**Comment by Bo98** [comment]
> Is that correct

Yes, you do not need to touch any part of the `bottle` block. It is automatically managed while merging (we don’t merge via GitHub UI).

**Comment by Bo98** [comment]
Thanks! Here's the automatic bottle commit if you are interested: 5a846a75b4f90f592abc226dab4b89ccbce4f5c7

**Pull request closed without merging**
