### PR TITLE
stoken 0.93

### PR DESCRIPTION
**Pull request by tomc603**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tomc603** [comment]
Bumping stoken version and pointing at the hew github repo rather than sourceforge.

**Comment by p-linnane** [comment]
Please drop that last commit. I've already added `libtool` and updated the build.

**Comment by tomc603** [comment]
I stepped on your change, sorry. Reverted.

**Comment by p-linnane** [comment]
Having multiple commits for the same formula triggers our autosquash workflow, which will open a replacement PR. So we need to only have one commit. I've dropped that commit and the revert commit so we can get this merged. Thanks!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
