### PR TITLE
Juju 2.6.10

### PR DESCRIPTION
**Pull request by SimonRichardson**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
21:49:23 ==> /usr/local/Cellar/conjure-up/2.6.9/bin/conjure-up --version
21:49:23 Error: conjure-up: failed
21:49:23 An exception occurred within a child process:
21:49:23   Test::Unit::AssertionFailedError: <0> expected but was
21:49:23 <nil>.

**Comment by chenrui333** [comment]
Relates to https://github.com/Homebrew/homebrew-core/pull/46001

**Comment by chenrui333** [comment]
Relates to https://github.com/Homebrew/homebrew-core/pull/46001

**Comment by SimonRichardson** [comment]
@chenrui333 This isn't related to #46001, it's the fact that `juju` client doesn't currently support Catalina with the 2.6 series. 2.7 which is soon to be released will support Catalina.

**Comment by chenrui333** [comment]
That is good to know. cc @fxcoudert @SMillerDev

**Comment by fxcoudert** [comment]
With statistics showing Catalina is 30% of our user base, it's difficult for us to distribute a known-broken version…

```
==> os-version (30 days)
Index | macOS Version                                    |      Count |  Percent
-----:|--------------------------------------------------|-----------:|--------:
01    | macOS Mojave (10.14)                             | 10,831,393 |   57.84%
02    | macOS Catalina (10.15)                           |  5,582,921 |   29.81%
03    | macOS High Sierra (10.13)                        |  1,597,401 |    8.53%
04    | macOS Sierra (10.12)                             |    507,754 |    2.71%
05    | OS X El Capitan (10.11)                          |    157,448 |    0.84%
```

**Comment by SimonRichardson** [comment]
@fxcoudert makes sense, we're releasing 2.7 within the next few weeks and that comes with Catalina support, so let's close this for now.

**Pull request closed without merging**
