### PR TITLE
vault 1.0.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails during test: 
```
!! Unable to generate a new root token: OTP string is wrong length
shutting down the Vault...
Error: safe: failed
```

**Comment by igas** [comment]
I think it's similar to https://github.com/starkandwayne/safe/issues/171

Lets hope that after 1.0 there would be less breaking changes.

**Comment by audip** [comment]
Vault 1.0.2 just dropped (https://github.com/hashicorp/vault/releases/tag/v1.0.2) and it'd be great to get this merged into master

**Comment by igas** [comment]
https://github.com/Homebrew/homebrew-core/pull/36320 merged, hopefully CI will pass now. Also updated to 1.0.2.

**Pull request closed without merging**
