### PR TITLE
libpqxx: revision for postgresql

### PR DESCRIPTION
**Pull request by EugenCazacu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by EugenCazacu** [comment]
I think there should be a better way to handle such dependencies. Every time postresql posts a new version, libpqxx must be recompiled. Until the revision is bumped, libpqxx is broken. It cannot be used with pkg-config and even worse there could be hidden dependencies, only crashing the library at runtime. Should the posgresql maintainers be forced to also bump the revision for libpqxx every time they post a new postgresql version? This doesn't sound like a nice solution, but could work by adding some failing test to the libpqxx, every time postgresql version changes, libpqxx test will fail. Can someone recommend a better way? Depending on how hard it can be achieved I am willing to put in the work. Unfortunately I am not much of a Ruby developer :).

**Comment by ilovezfs** [comment]
I don't think it actually needs to be recompiled to function because the linkage is not broken:
```
iMac-TMP:~ joe$ brew linkage libpqxx
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/opt/postgresql/lib/libpq.5.dylib (postgresql)
iMac-TMP:~ joe$ 
```
and that path still exists. So I think the problem is limited to the pkg-config file:

```
iMac-TMP:~ joe$ cat /usr/local/Cellar/libpqxx/5.0.1/lib/pkgconfig/libpqxx.pc 
prefix=/usr/local/Cellar/libpqxx/5.0.1
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libpqxx
Description: a C++ API to the PostgreSQL database management system.
Version: 5.0
Libs: -L${libdir} -L/usr/local/lib -lpqxx
Cflags: -I${includedir} -I/usr/local/Cellar/postgresql/10.0/include
```
which is indeed broken.

So we could either have libpqxx's test block verify whether that path exists, which would force the test to fail during the postgresql PRs unless libpqxx were revision bumped, or we could replace the postgresql Cellar path (`Cflags: -I${includedir} -I/usr/local/Cellar/postgresql/10.1/include`) with an opt path (`Cflags: -I${includedir} -I/usr/local/opt/postgresql/include`) in `libpqxx.pc`, which would avoid the need for the revision bump except when the linkage is actually broken.

**Comment by EugenCazacu** [comment]
I would prefer the revision bump option due to fear of binary incompatibility of the libpq library with its header interfaces from various previous or future versions. The binary incompatibility is not always visible as a broken linkage, but could be a much worse runtime error/crash when using the library. With a hard to identify root cause.

**Comment by ilovezfs** [comment]
@EugenCazacu that's the purpose of the test block, though. We generally don't want to be revision bumping anything that passes its test block.

**Comment by EugenCazacu** [comment]
I was thinking of how to implement such a failing test, but it is not very clear to me. I was thinking of something in the direction of changing to the test to having something like:

``system ENV.cxx, "test.cpp", *`pkg-config --cflags --libs libpqxx`.split, "-o", "test"``

This unfortunately passes, as the missing include is ignored by the compiler, and the postgres libpg headers are instaleld in the system include path `/usr/local//include`

**Comment by EugenCazacu** [comment]
@ilovezfs other tools, like cmake, which I use for my project are not as lenient with missing includes.

**Comment by ilovezfs** [comment]
If we go the always-revision-bump route, you'll probably want something like
```
    pc_contents = (lib/"pkgconfig/libpqxx.pc").read
    assert_match Formula["postgresql"].opt_include.realpath.to_s, pc_contents,
                 "Please revision bump libpqxx."
```

**Comment by ilovezfs** [comment]
Something like this would prevent us from always having to revision bump:
```
diff --git a/Formula/libpqxx.rb b/Formula/libpqxx.rb
index 93292e0..9a6b032 100644
--- a/Formula/libpqxx.rb
+++ b/Formula/libpqxx.rb
@@ -15,7 +15,18 @@ class Libpqxx < Formula
   depends_on :postgresql
 
   def install
-    system "./configure", "--prefix=#{prefix}", "--enable-shared"
+    pg_config = which("pg_config").realpath
+    pg = pg_config.relative_path_from(HOMEBREW_CELLAR).dirname.dirname.dirname
+    pg_formula = Formula[pg.to_s] if pg
+
+    args = ["--prefix=#{prefix}", "--enable-shared"]
+
+    if pg_formula
+      args << "--with-postgres-include=#{pg_formula.opt_include}"
+      args << "--with-postgres-lib=#{pg_formula.opt_lib}"
+    end
+
+    system "./configure", *args
     system "make", "install"
   end
```
Alternatively, we could try to fix `pg_config` so that it outputs opt paths.

**Comment by ilovezfs** [comment]
@EugenCazacu I've pushed a commit for that to this PR.

**Comment by EugenCazacu** [comment]
@ilovezfs Thank you!

**Comment by ilovezfs** [comment]
You're welcome.

Thanks for the PR @EugenCazacu! Shipped.

**Pull request closed without merging**
