### PR TITLE
PHP: removed dependency for pcre2

### PR DESCRIPTION
**Pull request by mkalkbrenner**

### CODE REVIEW

**Comment by nursefrancesco1977** [comment]
Hacker alert Leroy Prescott

**Comment by javian** [comment]
Thanks @mkalkbrenner ! Should adjust the other PHP formulae as well now that we are through with this one.

**Comment by driesvints** [comment]
Am I right to assume that this won't show up as an update when running `brew update`?

**Comment by iMichka** [comment]
Yes, as there was no bump of the revision. Brew will silently update this one.

**Comment by driesvints** [comment]
What would be the best way to remove php and reinstall so I definitely have it installed with this change? Tried with updating and upgrading with the `--force` flag but didn't work.

**Comment by SMillerDev** [comment]
>What would be the best way to remove php and reinstall so I definitely have it installed with this change? Tried with updating and upgrading with the `--force` flag but didn't work.

@driesvints that would be building from source but nothing changed here though. It always used the provided pcre sources and it still does.

**Comment by driesvints** [comment]
There's currently an issue with PHP on Homebrew involving the pcre extension and I thought that this PR would solve it. More info here: https://github.com/bobthecow/psysh/issues/540

**Pull request closed without merging**
