### PR TITLE
immortal 0.24.3

### PR DESCRIPTION
**Pull request by nbari**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Once this PR got merged or released, we can move the homebrew release better.

**Comment by SMillerDev** [comment]
```
Error: An exception occurred within a child process:
  Errno::EINVAL: Invalid argument @ rb_file_s_rename - (/private/tmp/immortal-20200322-80614-17uyp84/immortal-0.24.2/src, /private/tmp/immortal-20200322-80614-17uyp84/immortal-0.24.2/src/github.com/immortal/immortal/src)

```

**Comment by nbari** [comment]
hi @SMillerDev how to make the formula/Jenkins to ignore the `src` directory?

**Comment by chenrui333** [comment]
@nbari, let me pull my PR to see if I can make the build working. If possible, can you also make a new release with the `go modules` move?

**Comment by nbari** [comment]
@chenrui333 sure,  please give a try to do [0.24.3](https://github.com/immortal/immortal/releases/tag/0.24.3)

**Comment by chenrui333** [comment]
Thank you!!

**Comment by chenrui333** [comment]
The build works fine now, tested locally. Thanks for the new release.

**Pull request closed without merging**
