### PR TITLE
NGINX: Add --with-compat option

### PR DESCRIPTION
**Pull request by pandres95**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

By adding `--with-compat` option, it allows nginx to run any dynamic loaded module without having binary compatibility (a.k.a. signature checking) issues.

### CODE REVIEW

**Comment by SMillerDev** [comment]
could you remove the merge commit and rebase this branch on the latest master?

**Comment by pandres95** [comment]
Done @SMillerDev

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @pandres95

**Pull request closed without merging**
