### PR TITLE
apache-drill 1.9.0

### PR DESCRIPTION
**Pull request by howie**
- [ V] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [V] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [V] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [V] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Test is failing: https://bot.brew.sh/job/Homebrew%20Core/12730/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_apache_drill/

**Comment by houmam** [comment]
This formula update appears to be correct but unfortunately I can not see why the build failed.

Is there any way to rerun the build to see what the error was? I am trying to avoid creating a new PR for the same formula.

**Comment by woodruffw** [comment]
Closing in favor of #8755.

**Comment by woodruffw** [comment]
@houmam I'm going to re-queue the build, we should be able to see the failure then.

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by woodruffw** [comment]
This looks like the failure:

```
==> /usr/local/Cellar/apache-drill/1.9.0/bin/sqlline -u jdbc:drill:zk=local
mkdir: /usr/local/Cellar/apache-drill/1.9.0/libexec/log: Operation not permitted
ERROR: Log directory does not exist or is not writable: /usr/local/Cellar/apache-drill/1.9.0/libexec/log
Error: apache-drill: failed
<0> expected but was
<1>.
```

**Comment by houmam** [comment]
Very strange, I can not replicate this issue locally.

Do I have to explicitly create the log folder and make it writable for it to work with testbot?

Looking at my local checkout on a clean install it creates the folder on launch of the test command being issued:

"/usr/local/Cellar/apache-drill/1.9.0/bin/sqlline -u jdbc:drill:zk=local"

Is there anything permission wise preventing this log folder and files from being created on the test servers when the test is run?

**Comment by woodruffw** [comment]
I believe it's the sandbox preventing that folder from being created. Is there some environment variable or flag that we can pass to tell `apache-drill` not to log?

**Comment by houmam** [comment]
I managed to replicate the issue locally.

Unfortunately I could not find a way to disable logging completely but instead set an environment variable to use /tmp when testing, which appears to work fine.

Pull request is on the branch created by @howie here:

https://github.com/howie/homebrew-core/pull/1

Hopefully that should pull across when he merges my change.

**Comment by woodruffw** [comment]
Thanks. If @howie doesn't get around to it in a bit, let's go ahead and open a new PR to bump and fix this (or reopen the other one).

**Comment by nijikon** [comment]
Fixed in 6213cad2350961a94a1c59b8cb84a7212146167c

**Pull request closed without merging**
