### PR TITLE
trafficserver 7.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jbergstroem** [comment]
The spdy flag is gone. I suggest you read changelog before bumping!

**Comment by jbergstroem** [comment]
(Removing everything spdy-related in the formula should work just fine)

**Comment by nijikon** [comment]
@jbergstroem sorry about that, will fix that shortly.

**Comment by jbergstroem** [comment]
@nijikon all good; thanks for your quick response -- I should've pr:ed it myself :/

**Comment by nijikon** [comment]
@jbergstroem removed in 3b04df0c9256f0408fa9c9a16f86206ace5de2ac

**Pull request closed without merging**
