### PR TITLE
rocksdb 4.6.1 & osquery 1.7.4

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Bump `rocksdb` stable version from 4.5.1 to 4.6.1
- Bump `osquery` stable version from 1.7.3 to 1.7.4
  - Amend pypi resource url's
  - Bump `jinja2` resource version from 2.7.3 to 2.8
  - Remove `psutil` resource
  - Add `argparse`resource version 1.4.0

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@Jerzerak Mind adding a `depends_on "rocksdb"` to `osquery` to fix this: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2593/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/linkage___test_osquery/

Thanks!

**Comment by Jerzerak** [comment]
@MikeMcQuaid What you mean like [this](https://github.com/Homebrew/homebrew-core/blob/master/Formula/osquery.rb#L23) line?

**Comment by UniqMartin** [comment]
I think Mike meant to say `revision 1` line immediately following [these three lines](https://github.com/Homebrew/homebrew-core/blob/e8b284aa36f81c56ad0cfc88b57da39b7356b1e5/Formula/osquery.rb#L5-L7). `osquery` is linked against `rocksdb` and needs to be rebuilt to continue working once the `rocksdb` update is shipped.

**Comment by Jerzerak** [comment]
@UniqMartin Thanks Martin, that's what I figured he meant, but was just clarifying.

**Comment by UniqMartin** [comment]
Makes sense and is a good thing! If we handle them together in this PR (assuming none of them takes a horribly long time to build and is prone to breakage) we can avoid having to revision `rocksdb`.

**Comment by Jerzerak** [comment]
Alright, I'll add the commit later tonight!

**Comment by ilovezfs** [comment]
@Jerzerak there's a 1.7.5 now, if you'd like to refresh this.

**Comment by ilovezfs** [comment]
@Jerzerak there's now a 1.8.0 if you'd like this refresh this.

**Comment by DomT4** [comment]
Will happily review a fresh PR but this one seems to have gone dead, so closing. Thank you nonetheless for the submission to Homebrew ❤️

**Pull request closed without merging**
