### PR TITLE
mpv 0.35.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Building with `waf` is deprecated and will be removed. `meson` is the preferred method now, so I will work to convert this over.

**Comment by chenrui333** [comment]
```
  Checking for libarchive wrapper for reading zip files and more            : no ('libarchive >= 3.4.0' not found) 
  You manually enabled the feature 'libarchive', but the autodetection check failed.
```

**Comment by carlocab** [comment]
Ah, this is because `libarchive` has a broken `.pc` file. That's #117869.

**Comment by p-linnane** [comment]
Closing due to ongoing `iconv`/`libarchive` issues.

**Pull request closed without merging**
