### PR TITLE
python: apply patch to fix building on sierra

### LINKED ISSUE #4630: 10.12 - python --universal build failed
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I need to use universal version of Python. I use `brew install python --universal` and build all required libraries with `--universal` flag. When attempting to install python on fresh install of Sierra, I've run into error. See https://gist.github.com/3b23cad2266f54ba8b4af1d2c8c3dadd. 

Error happens because of [missing QuickTime/QuickTime.h](https://gist.github.com/anonymous/3b23cad2266f54ba8b4af1d2c8c3dadd#file-02-make-L122). 

Upstream [issue 27806](https://bugs.python.org/issue27806).

### PR DESCRIPTION
**Pull request by sashkab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Fixes #4630.

### CODE REVIEW

**Comment by sashkab** [comment]
@zmwangx -- is there any reason  why this wasn't reviewed/accepted yet?

**Comment by zmwangx** [comment]
When I last looked at this, it was an unofficial patch. Now that it's committed, could you please link to the official patch instead? Thanks.

**Comment by sashkab** [comment]
@zmwangx -- I've updated to use official patch; rebased to homebrew-core/master. 

No warnings during `brew audit python ` and `brew audit --new-formula python`.

Please let me know if you need anything else.

**Comment by zmwangx** [comment]
Thanks, I'll merge this once I've tried `brew install --universal python` on my VM.

Out of interest, do you think python3 needs a similar patch?

**Comment by ilovezfs** [comment]
do we know when the next python release is? that's quite a substantial patch ...

**Comment by sashkab** [comment]
No, python 3 doesn't require similar patch, "Since the old Python mac modules don't exist in Python 3.x, this is only a 2.7 issue.". Python 3 builds `--universal` without a problem.

Quoted from the [upstream issue](https://bugs.python.org/issue27806).

**Comment by sashkab** [comment]
@ilovezfs According to [PEP-373](https://www.python.org/dev/peps/pep-0373/#id4), it is December 2016 for Python 2.7.13.

**Comment by zmwangx** [comment]
@ilovezfs It only affects `--universal` so I'm fine with this. 2.7.13 is due in December 2016.

**Comment by ilovezfs** [comment]
yikes. maybe someone can convince them to issue a maintenance release.

**Comment by zmwangx** [comment]
Python releases are set in stone so I doubt it. Unless you have a more actionable concern I'll merge this.

**Comment by ilovezfs** [comment]
:ship:

**Comment by zmwangx** [comment]
Merged as 6e220da. Thank you for your contribution to Homebrew!

**Pull request merged**
