### PR TITLE
rust 1.50.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
Duplicate of #70922.

**Comment by SMillerDev** [comment]
@chenrui333 you really need to fix the script to stop sending duplicates

**Comment by chenrui333** [comment]
@SMillerDev we have discussed in [here](https://github.com/dawidd6/action-homebrew-bump-formula/issues/27), it is more of github API data issue.

**Comment by carlocab** [comment]
Can you maybe run your script less often so that it's less likely to query the GitHub API while it's outdated?

**Pull request closed without merging**
