### PR TITLE
chezscheme: fix the build on 10.11 with Xcode 8

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/Homebrew/homebrew-core/issues/10144.

### CODE REVIEW

**Comment by ararslan** [comment]
Awesome, thanks @ilovezfs! Would it be simpler to pass `LDFLAGS=-Wl,-no_weak_imports` in the call to `./configure`, or is something like this the brew-preferred solution?

**Comment by ilovezfs** [comment]
@ararslan that works if a) Xcode 7 and CLT 7 are not in the picture at all (they are) and if b) the use of clock_gettime is guarded by a variable like HAVE_CLOCK_GETTIME, and some kind of configure check for its availability (it's not).

**Review by ilovezfs — COMMENTED** [review]
needs to be reported upstream

**Comment by ararslan** [comment]
Good to know. Thanks for the explanation and thanks again for the fix! You rock! 🎸

**Comment by ararslan** [comment]
Reported upstream: https://github.com/cisco/ChezScheme/issues/146

**Comment by ilovezfs** [comment]
Shipped! @ararslan thanks for taking care of the upstream report. I've added a link to it in the formula.

**Pull request closed without merging**
