### PR TITLE
gradle 5.0

### PR DESCRIPTION
**Pull request by fobo66**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apjanke** [comment]
Readall and audit failed:

```
failed: brew readall --aliases homebrew/core
Stacktrace
        Error: Formula duplicating alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/gradle@4
```

```
failed: brew audit gradle@4 --online --new-formula
Stacktrace
        Error: 2 problems in 1 formula detected
gradle@4:
  * Formula name conflicts with existing aliases.
  * Versioned formulae should use `keg_only :versioned_formula`
```

Looks like the `gradle@4` alias should be removed since there's a real formula for it now, and `gradle@4` made keg-only.

**Comment by fxcoudert** [comment]
I don't think we want to create a new versioned formula

**Comment by fobo66** [comment]
I guess, we will need versioned formula for Gradle v4, because version 5.0 of Gradle contains some [breaking changes](https://docs.gradle.org/current/userguide/upgrading_version_4.html).

**Comment by SMillerDev** [comment]
As per https://docs.brew.sh/Versions breaking changes alone aren't enough of a reason to version a brew formula.

**Comment by seanjreilly** [comment]
@apjanke it's not unusual for Homebrew to accept new versions of Gradle within a day or two of release — I've personally submitted a version bump PR that was accepted on the day of release at least once (probably more than that).

Gradle provides specific functionality (the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html)) to specify that a specific version of gradle should be used to build a project, so breaking projects with new versions of Gradle shouldn't be a concern.

**Comment by fobo66** [comment]
@seanjreilly So, does it mean that I need to remove v4 alias?

**Comment by seanjreilly** [comment]
@fobo66 I don't think I'm the person who should make that decision. There may or may not be reasons that Homebrew might prefer to have an alias for each major version of Gradle (although @SMillerDev's comment suggests the opposite).

However, speaking as someone with a lot of Gradle experience currently working on multiple projects built with Gradle 4, **if the decision is to remove the v4 alias, that wouldn't cause me any issues**. It's also worth noting that the final version of Gradle 4 (4.10.2) is significantly different from 4.0.0, and if I was pinning a product to a version of Gradle I would need it to be more specific than just "version 4".

**Comment by SMillerDev** [comment]
> It's also worth noting that the final version of Gradle 4 (4.10.2) is significantly different from 4.0.0, and if I was pinning a product to a version of Gradle I would need it to be more specific than just "version 4".

For homebrew it's more like a "latest in the 4.x series" same as that unversioned it'd just be the "latest in the series".

**Comment by fxcoudert** [comment]
Thanks @fobo66

**Pull request merged**
