### PR TITLE
postgis: symlink `postgres` binary during build

### PR DESCRIPTION
**Pull request by 9999years**
While attempting to build PostGIS against PostgreSQL 16, I found a strange error:

```
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -fvisibility=hidden -bundle -o postgis_raster-3.dylib rtpostgis.o rtpg_internal.o rtpg_legacy.o rtpg_spatial_relationship.o rtpg_mapalgebra.o rtpg_utility.o rtpg_inout.o rtpg_wkb.o rtpg_geometry.o rtpg_raster_properties.o rtpg_band_properties.o rtpg_pixel.o rtpg_create.o rtpg_gdal.o rtpg_statistics.o -L/opt/homebrew/opt/postgresql@16/lib  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/openssl@3/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/Cellar/lz4/1.9.4/lib -L/opt/homebrew/opt/zstd/lib -Wl,-dead_strip_dylibs   -fvisibility=hidden ./../rt_core/librtcore.a ../../liblwgeom/.libs/liblwgeom.a ../../libpgcommon/libpgcommon.a -L/opt/homebrew/Cellar/gdal/3.9.1/lib -lgdal -L/opt/homebrew/Cellar/geos/3.12.2/lib -lgeos_c -L/opt/homebrew/opt/proj/lib -lproj -Wl,-rpath,/opt/homebrew/opt/proj/lib -L/opt/homebrew/opt/json-c/lib -ljson-c -L/opt/homebrew/opt/protobuf-c/bin/lib -lprotobuf-c -L/opt/homebrew/Cellar/libxml2/2.12.8/lib -lxml2 -lz -L/opt/homebrew/Cellar/icu4c/74.2/lib -licui18n -licuuc -licudata -liconv -L/opt/homebrew/Cellar/sfcgal/1.5.1_2/lib -lSFCGAL   -lm -bundle_loader /opt/homebrew/Cellar/postgis-for-postgresql-16/3.4.2_2/bin/postgres
ld: library '/opt/homebrew/Cellar/postgis-for-postgresql-16/3.4.2_2/bin/postgres' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [postgis_raster-3.dylib] Error 1
make[2]: *** [pglib] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 1
```

This was following @SMillerDev's [instructions][1] for creating a tap including PostGIS built against a particular PostgreSQL version.

At first, my build was failing unpredictably. Then, I noticed that when I uninstalled `postgresql@14` the build would produce a different error; this was very strange, as I assumed that the build would be isolated from the state of installed packages. Anyways, I eventually figured out that the symlink to the `postgres` binary is needed during the build.

I'm not sure why this isn't present already; a similar link was [added to the Nixpkgs PostGIS build in 2019][2], and at that time Nixpkgs included PostgreSQL versions 9.4 through 11.4.

Adding this link is not harmful and will make it easier to upgrade the PostgreSQL version that PostGIS is built against in the future.

[1]: https://github.com/Homebrew/homebrew-core/issues/86709#issuecomment-936462624
[2]: https://github.com/NixOS/nixpkgs/commit/330fff02a675f389f429d872a590ed65fc93aedb

This may unblock several issues related to upgrading the PostgreSQL and PostGIS versions:

- #167594
- #118138
- https://github.com/orgs/Homebrew/discussions/3987

---

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by 9999years** [comment]
Should I worry about the 'indirect linkage' warnings? I added this snippet:

```ruby
uses_from_macos "libxml2"
                          
on_linux do
  depends_on "libpq"
  depends_on "llvm"
end
```

But I'm still seeing this on macOS:

```
Indirect dependencies with linkage:
  libxml2
```

**Comment by 9999years** [comment]
Not stale. I just need a review. There's no way to ask for a review as far as I can tell for.

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me, thanks @9999years!

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @9999years!

**Pull request merged**
