### PR TITLE
ruby-build 20160913

### PR DESCRIPTION
**Pull request by hsbt**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
Thanks, but dupe of #4762.

**Comment by ilovezfs** [comment]
@zmwangx actually @hsbt is upstream in this case, so I shall defer to him ;)

**Comment by zmwangx** [comment]
sure.

**Comment by hsbt** [comment]
@zmwangx @liboyue Thank you for advice. It's first time used `brew bump-formula-pr` introduced https://github.com/rbenv/ruby-build/issues/980 for me.

I'm ok to merge #4762 :octocat:

**Comment by zmwangx** [comment]
Don't worry, I've submitted duplicates myself a couple of times in the past.

**Comment by ilovezfs** [comment]
@hsbt you can check for duplicates using these

```
brew tap homebrew/dev-tools
```

```
prs(){(brew ruby -e "formula=Formula[\"$1\"] ; GitHub.issues_for_formula(formula.name, :tap => formula.tap).each { |i| puts i[\"$2\"] }")}
prurls(){(prs "$1" "html_url")}
prtitles(){(prs "$1" "title")}
```

Example:
```
bash-4.3$ prurls ruby-build
https://github.com/Homebrew/homebrew-core/pull/4763
bash-4.3$ prtitles ruby-build
ruby-build 20160913
bash-4.3$
```

**Comment by hsbt** [comment]
@ilovezfs It's useful! I will setup it.

**Comment by zmwangx** [comment]
Merged as 6b44378. Thank you for your contribution to Homebrew!

**Pull request merged**
