### PR TITLE
entr: update SHA256

### PR DESCRIPTION
**Pull request by queengooborg**
New SHA256 was pulled directly from the URL.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.`

**Comment by vinyldarkscratch** [comment]
Issue created upstream (https://bitbucket.org/eradman/entr/issues/70/sha256-changed-for-release-of-entr-39) -- closing PR for now!

**Comment by vinyldarkscratch** [comment]
Hey, @ilovezfs and @fxcoudert, I think you're going to want to take a look at Eric's (the repo owner's), response to the issue.  He confirmed, though, that this new checksum that this PR includes is the correct one.  Essentially, what he's saying is that you guys grabbed the release for `entr` 3.9 before he had even created it?

**Comment by ilovezfs** [comment]
```
class Entr
  livecheck :url => "http://entrproject.org/code/",
            :regex => /href="entr-([0-9\.]+)\.t/
end
```
It was there to be had.

**Comment by ilovezfs** [comment]
@vinyldarkscratch we should bump the revision here too

**Comment by ilovezfs** [comment]
I will change that to
```
class Entr
  livecheck :url => "http://entrproject.org/",
            :regex => %r{href=.*?/entr-([0-9\.]+)\.t}
end
```
which hopefully will be more inline with what he's thinking.

**Comment by vinyldarkscratch** [comment]
I see, hmm...  Alrighty, bumping revision!

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks again @vinyldarkscratch!

**Comment by vinyldarkscratch** [comment]
Always glad to help out, @ilovezfs!  😄

**Pull request closed without merging**
