### PR TITLE
deno: downgrade to 1.43.1

### LINKED ISSUE #171317: Deno 1.43.2 homebrew build segmentation fault
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

The code in https://github.com/poolifier/poolifier-web-worker/tree/master/examples/deno/typescript segfault with Deno homebrew build version 1.43.2:

`[1]    30111 segmentation fault  deno run -A pool.ts`

All UTs instantiating a pool are also triggering a segfault.

Deno homebrew build version 1.43.1 and official Deno.com binaries works fine.

### What happened (include all command output)?

N/A

### What did you expect to happen?

N/A

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

closes #171317

### CODE REVIEW

**Comment by jerome-benoit** [comment]
If the root cause is the rust toolchain version 1.78 usage to build Deno, I'm afraid the version downgrade will not be enough.

**Comment by chenrui333** [comment]
seems working fine in my local?

```
$ clang --version
Homebrew clang version 18.1.5
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/llvm/18.1.5/bin


$ rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew)

$ brew test -d -v deno
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/bundle clean
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading deno
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading homebrew/core/deno
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading llvm
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading ninja
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading protobuf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading rust
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading sqlite
==> Testing deno
/opt/homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/d/deno.rb
==> /opt/homebrew/Cellar/deno/1.43.1/bin/deno run hello.ts
==> /opt/homebrew/Cellar/deno/1.43.1/bin/deno run https://deno.land/std@0.100.0/examples/welcome.ts
/opt/homebrew/Library/Homebrew/test.rb (Formulary::FromNameLoader): loading sqlite
```

**Comment by jerome-benoit** [comment]
> seems working fine in my local?

Does the resulting binary pass the repro: `deno eval "fetch('http://8.8.8.8')"`? 

If yes, then the root cause is narrowed down to rust 1.78 and Deno 1.43.2 code base build.

**Comment by chenrui333** [comment]
> > seems working fine in my local?
> 
> Does the resulting binary pass the repro: `deno eval "fetch('http://8.8.8.8')"`?
> 
> If yes, then the root cause is narrowed down to rust 1.78 and Deno 1.43.2 code base build.

yeah, that works with 1.43.1, not 1.43.2 (left a comment in the issue thread as well)

**Comment by carlocab** [comment]
> > > seems working fine in my local?
> > 
> > 
> > Does the resulting binary pass the repro: `deno eval "fetch('http://8.8.8.8')"`?
> > If yes, then the root cause is narrowed down to rust 1.78 and Deno 1.43.2 code base build.
> 
> yeah, that works with 1.43.1, not 1.43.2 (left a comment in the issue thread as well)
> 
> env: llvm 18.1.5, rust 1.78.0

I don't think @chenrui333 rebuilt `deno` from source with this, so new Rust/LLVM is still a candidate explanation for the failure. I'll give it a try.

**Comment by chenrui333** [comment]
I did not perform source build (the 1.43.1 was built with llvm 17 as well)


we can potentially try this patch for source build with llvm 18, https://github.com/denoland/deno_core/pull/735

**Review by carlocab — APPROVED** [review]
Ok with merging this for now.

**Review by Bo98 — APPROVED** [review]
OK with this given 1.43.3 will fix this.

Test seems a bit weird and I feel like it could be slimmed down but better than nothing.

**Comment by chenrui333** [comment]
thanks, merging!

**Comment by chenrui333** [comment]
> Test seems a bit weird and I feel like it could be slimmed down but better than nothing.

that just trying to reproduce the issue for the fresh-project checkout.

**Pull request merged**
