### PR TITLE
ldc 1.3.0-beta1 (devel)

### PR DESCRIPTION
**Pull request by John-Colvin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by neutric** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks for the PR @John-Colvin

**Comment by neutric** [comment]
Too late: libconfig is no longer a dependency starting with 1.3.0-beta1, something to watch out for come the next update...

**Comment by John-Colvin** [comment]
@neutric https://github.com/Homebrew/homebrew-core/pull/13279

**Comment by neutric** [comment]
Thanks John!

**Pull request merged**
