### PR TITLE
handbrake 1.3.2

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Amar1729** [comment]
Current failure:
```
==> brew audit --skip-style handbrake --online
==> FAILED
Error: 1 problem in 1 formula detected
handbrake:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      bin/HandBrakeCLI
```

What exactly does this mean? I've checked `bin/HandBrakeCLI` with `otool` and `objdump` but neither of them show the bin depending on things in `$(brew --repository)/Library/Homebrew/shims`. Only thing I could find was that it was compiled with `-cc=$(brew --repository)/Library/Homebrew/shims/cc`.

**Comment by DesWurstes** [comment]
The only place "shims" is mentioned in the executable is:

```
--prefix=/private/tmp/handbrake-20200107-969-1l8wunr/HandBrake-1.3.1/build/contrib/ --disable-shared --enable-static --enable-gpl --disable-doc --disable-programs --disable-avdevice --disable-muxers --disable-network --disable-hwaccels --disable-vdpau --disable-encoders --enable-libmp3lame --enable-encoder=aac --enable-encoder=ac3 --enable-encoder=eac3 --enable-encoder=flac --enable-encoder=mpeg2video --enable-encoder=mpeg4 --enable-encoder=libmp3lame --enable-libopus --enable-encoder=libopus --enable-libspeex --disable-encoder=libspeex --enable-decoder=libspeex --enable-libvpx --disable-decoder='libvpx_*' --enable-encoder=libvpx_vp8 --enable-encoder=libvpx_vp9 --disable-decoder='*_crystalhd' --enable-libdav1d --enable-decoder=libdav1d --cc=/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang --extra-ldflags='-arch x86_64 -mfpmath=sse -msse2 -L/private/tmp/handbrake-20200107-969-1l8wunr/HandBrake-1.3.1/build/contrib/lib' --disable-vaapi --enable-muxer=matroska --enable-muxer=webm --enable-muxer=mov --enable-muxer=mp4 --enable-muxer=psp --enable-muxer=ipod --disable-audiotoolbox --disable-coreimage --enable-encoder=h264_videotoolbox --enable-encoder=hevc_videotoolbox --arch=x86_64 --disable-debug --extra-cflags='-arch x86_64 -mfpmath=sse -msse2 -I/private/tmp/handbrake-20200107-969-1l8wunr/HandBrake-1.3.1/build/contrib/include -DNDEBUG
```

which is a derivative of `CFLAGS` processed [here](https://github.com/HandBrake/HandBrake/blob/2a64670a88521b33fcad02b8ab5752a7d0c60e0c/make/include/gcc.defs#L78) and [here](https://github.com/HandBrake/HandBrake/blob/22cfd6a1ec05a261284554b72109567392b91c9b/contrib/ffmpeg/module.defs#L117). Is it allowed to change the CFLAGS? I don't think so, but I can't find where the final CFLAGS is saved in Handbrake's source code.

To help debugging this => you might find this script useful:
```bash
strings /usr/local/Cellar/handbrake/1.3.1/bin/HandBrakeCLI  | grep "shims"
```

**Comment by alebcay** [comment]
@Bo98 would it be suitable to override the `CFLAGS` here? I'm fairly certain that would bypass the shims altogether in the build process.

**Comment by Bo98** [comment]
We don't want to bypass using the shims in the build process - just them remaining around in the output binary.

The reference seems to be in the ffmpeg portion. We don't have this issue with the ffmpeg formula, because when we compile there we don't pass the absolute path to the compiler to `--cc` while Handbrake does.

What might work is a inreplace for `contrib/ffmpeg/module.defs` replacing `$(FFMPEG.GCC.gcc)` with `clang` or maybe even `cc` as cross platform way.

**Comment by alebcay** [comment]
Looks like that did the trick.

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
