### PR TITLE
pipx 0.13.0.1 (new formula)

### PR DESCRIPTION
**Pull request by zbeekman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zbeekman** [comment]
@AlJohri Sorry, I fat finger force pushed to your branch... I'm not sure what you did, but `brew pull` wasn't working so I tried to reset your branch and in the process I accidentally closed PR #39411.

I think there were problems due to your git workflow. This PR should do the trick though, as soon as CI is green we can merge.

**Comment by AlJohri** [comment]
@zbeekman all good!

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew @AlJohri! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by AlJohri** [comment]
hi @zbeekman, could you provide some guidance on Formula that require modifying the PATH?

The `pipx` library currently depends on the [`userpath`](https://github.com/ofek/userpath) CLI tool for helping the user set the PATH. It takes into account which os/shell you are using to prevent writing dozens of lines of documentation explaining how to change the path for windows, bash, zsh, fish, etc.

Ideally, `userpath` would just become a homebrew package in of itself that `pipx` could depend on. Then in the `pipx` documentation the setup would simply be:

```
brew install pipx
userpath add ~/.local/bin/
```

Does `userpath` meet the notability requirements for creating a separate package? Or is there some other best practice for Formula that require PATH manipulation. Thanks!

**Comment by ofek** [comment]
Here are some stats, if that helps https://pepy.tech/project/userpath

**Comment by zbeekman** [comment]
@AlJohri: The criteria for new formulae are pretty well documented at https://docs.brew.sh/Acceptable-Formulae. The notability requirements should be more prominently documented somewhere, IMO, but creating a bare-bones formula with version, hash, and URL, then running `brew audit --strict --online <new-formula>` will tell you if there's a problem with the default notability.

But, fear not, it looks like ofek/userpath certainly meets the usability criteria, and would be a great tool to include in Homebrew. I have quite a bit of "real" work to attend to this week, so I would very much appreciate it if you or @ofek could open a PR to add `userpath` as a new formula.

**Comment by AlJohri** [comment]
Awesome- I'll submit the PR in the next few days. Thanks!

**Pull request closed without merging**
