### PR TITLE
go 1.16.4

### PR DESCRIPTION
**Pull request by Loyalsoldier**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
These formulas failed on Big Sur on Apple Silicon:

```
Error: 62 failed steps!
brew test --retry --verbose akamai
brew install --build-from-source argo
brew test --retry --verbose awsweeper
brew test --retry --verbose bazelisk
brew test --retry --verbose bitrise
brew install --build-from-source cf-tool
brew test --retry --verbose chart-testing
brew install --build-from-source chronograf
brew install --build-from-source circleci
brew install --build-from-source --only-dependencies clair
brew install --build-from-source clair
brew install --build-from-source consul
brew install --build-from-source --only-dependencies docker-machine-driver-hyperkit
brew install --build-from-source docker-machine-driver-hyperkit
brew install --build-from-source --only-dependencies dockviz
brew install --build-from-source dockviz
brew install --build-from-source drone-cli
brew install --build-from-source dvm
brew install --only-dependencies --include-test envconsul
brew test --retry --verbose envconsul
brew install --build-from-source --only-dependencies envoy
brew install --build-from-source envoy
brew test --retry --verbose etcd
brew install --build-from-source --only-dependencies fabio
brew install --build-from-source fabio
brew test --retry --verbose fortio
brew install --build-from-source --only-dependencies geoipupdate
brew install --build-from-source geoipupdate
brew install --build-from-source --only-dependencies git-annex-remote-rclone
brew install --build-from-source git-annex-remote-rclone
brew install --build-from-source gotop
brew install --build-from-source ioctl
brew install --build-from-source --only-dependencies ironcli
brew install --build-from-source ironcli
brew install --build-from-source istioctl
brew test --retry --verbose jabba
brew test --retry --verbose keptn
brew install --build-from-source kube-linter
brew install --build-from-source kustomize
brew install --build-from-source logcli
brew install --build-from-source mpdviz
brew install --build-from-source pilosa
brew install --build-from-source promtail
brew test --retry --verbose server-go
brew install --build-from-source ship
brew install --build-from-source source-to-image
brew install --build-from-source --only-dependencies ssh-vault
brew install --build-from-source ssh-vault
brew install --only-dependencies --include-test stolon
brew test --retry --verbose stolon
brew install --build-from-source td
brew install --build-from-source teleconsole
brew install --build-from-source telegraf
brew test --retry --verbose terrascan
brew test --retry --verbose terrascan
brew install --build-from-source traefik@1
brew install --build-from-source --only-dependencies vault
brew install --build-from-source vault
brew install --build-from-source --only-dependencies vert
brew install --build-from-source vert
brew install --build-from-source virgil
brew fetch --retry vitess
Error: Process completed with exit code 1.
```

**Comment by carlocab** [comment]
Most of the ARM failures haven't been bottled. These are the ones that have been:
```
chronograf
fortio
istioctl
kustomize
logcli
promtail
ship
td
telegraf
terrascan
traefik@1
```

**Comment by carlocab** [comment]
Catalina:

```
Error: 15 failed steps!
brew install --build-from-source chronograf
brew test --retry --verbose darksky-weather
brew test --retry --verbose darksky-weather
brew test --retry --verbose fortio
brew install --build-from-source grafana
brew install --build-from-source kustomize
brew install --build-from-source logcli
brew install --build-from-source promtail
brew install --build-from-source ship
brew install --build-from-source td
brew install --build-from-source telegraf
brew test --retry --verbose terrascan
brew test --retry --verbose terrascan
brew install --build-from-source traefik@1
brew install --build-from-source vitess
```

Mojave:

```
Error: 12 failed steps!
brew install --build-from-source aws-iam-authenticator
brew install --build-from-source chronograf
brew install --build-from-source kustomize
brew install --build-from-source logcli
brew install --build-from-source promtail
brew install --build-from-source ship
brew install --build-from-source td
brew install --build-from-source telegraf
brew test --retry --verbose terrascan
brew test --retry --verbose terrascan
brew install --build-from-source traefik@1
brew install --build-from-source vitess
```

**Comment by carlocab** [comment]
> Then what's next?

Investigate these test failures and try to fix as many as we can.

Big Sur:

```
Error: 12 failed steps!
brew install --build-from-source chronograf
brew test --retry --verbose fortio
brew install --build-from-source kustomize
brew install --build-from-source logcli
brew install --build-from-source promtail
brew install --build-from-source ship
brew install --build-from-source td
brew install --build-from-source telegraf
brew test --retry --verbose terrascan
brew test --retry --verbose terrascan
brew install --build-from-source traefik@1
brew install --build-from-source vitess
```

**Comment by andig** [comment]
I find this a bit confusing. Go 1.16.4 has zero changes that should not work where 1.16.3 has worked?

**Comment by jlk** [comment]
Folks - hey from terrascan team. :) Just saw this while passing through - we'll take a peek at this from our side, as well...

**Comment by cho-m** [comment]
May want to rebase and rerun CI to test on latest Homebrew state.

From previous run, the failures that probably will reoccur are 4 SHA checksum mismatch errors (`vitess`, `logcli`, `promtail`, and `td`), which require updating the `sha256` checksum in each formula after confirming with the upstream source that the new checksum is correct and not the result of a malicious actor.

It is possible that new failures will occur due to formulae being updating during the timeframe.

**Comment by cho-m** [comment]
Will update with latest failures here.
Can later decide if any are actually blocking failures.

ARM failures (focusing on bottled): Mostly checksum mismatches:
- [ ] `istioctl` - Doesn't build on ARM as-is, may be possible with https://github.com/Homebrew/homebrew-core/pull/77139#issuecomment-844297659 
- [ ] `linkerd` - SHA mismatch
    ```
    ==> Checking out tag stable-2.10.2
    HEAD is now at 5535e9c4 Add service annotations fix to stable 2.10.2 (#6126)
    Error: stable-2.10.2 tag should be fd03538b2641c56f6e6dc3bb5de1669ccd96278a
    but is actually 5535e9c4edda7f5a8d8d21e351b61425bd3a8208
    ```
- [ ] `td` - SHA mismatch
    ```
    Error: SHA256 mismatch
    Expected: fe81605196e9c1f9c5f930adf5067d0c0cb90e9c83c6a2d846e12dc0a18dd7e3
      Actual: 1fc8dcc1ad318be1a9f047fe617e8d93f33dcc6b09dde3accaa30417ff007bb5
    ```
- [ ] `teleport` - SHA mismatch
    ```
    Error: SHA256 mismatch
    Expected: 25195488a44a53ad1e2ecb552900631c176ac4449d0deaf823ada96513d6e864
      Actual: 4aa5ccf45ae440d68cc3bb5ebeb375d7121c67b8444ac42671e19be8014c5e0f
    ```

**Comment by cho-m** [comment]
@carlocab Can you check if we can go ahead with merge here?
Pretty much all failures are checksum errors (`linkerd`, `td`, `telegraf`, and `vitess`).
Only other one is `istioctl` on Catalina, which was a network issue on CI node.

---

Big Sur ARM
```
brew install --build-from-source linkerd
brew install --build-from-source td
brew install --build-from-source telegraf
```

Big Sur
```
brew install --build-from-source linkerd
brew install --build-from-source td
brew install --build-from-source telegraf
brew install --build-from-source vitess
```

Catalina
```
brew install --build-from-source istioctl
brew install --build-from-source linkerd
brew install --build-from-source td
brew install --build-from-source telegraf
brew install --build-from-source vitess
```

Mojave
```
brew install --build-from-source linkerd
brew install --build-from-source td
brew install --build-from-source telegraf
brew install --build-from-source vitess
```

**Review by carlocab — APPROVED** [review]
LGTM. Thanks for working on this, @cho-m.

**Comment by ldemailly** [comment]
#78670 maybe will eliminate the issue (though there shouldn't have been an issue at all so it's a bit mysterious)

**Pull request closed without merging**
