### PR TITLE
terraform 0.12.24

### PR DESCRIPTION
**Pull request by flo-sch**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Thanks @@flo-sch!!

**Comment by flo-sch** [comment]
My pleasure :)
I have an automated pipeline running `terraform plan` on PR, which locked my remote state with v0.12.24, so I cannot run `terraform plan` locally anymore until I can bump as well.

I anyone experiencing the same issues? Any workaround idea (despite not running plans from a Docker image targeting "latest")?

**Comment by efernandes-ANDigital** [comment]
@flo-sch Hey 👋  So if you just download the latest version of terraform from https://www.terraform.io/downloads.html and point to that locally, you should be able to run your terraform cmds :)

**Comment by flosch-hb** [comment]
Hey @efernandes-ANDigital, sure, but that means not using the homebrew version, right?

**Comment by efernandes-ANDigital** [comment]
@flo-sch yup until this PR gets merged in, it's a quick workaround

**Comment by chenrui333** [comment]
Merging it now. 🚀

**Pull request closed without merging**
