### PR TITLE
monit 5.20.0

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
The mirror takes a few days to update. I'll add it back in once it has the latest release.

**Comment by ilovezfs** [comment]
As long as the server itself responds, we just update the mirror URLs as if they are already valid, but I'll fix it in post. There's no need to go through CI again assuming this come up :green_apple:

**Comment by neutric** [comment]
@ilovezfs Thanks for fixing and merging!

**Comment by ilovezfs** [comment]
You're welcome! No problem at all. Thanks for your contribution to Homebrew :)

**Pull request closed without merging**
