### PR TITLE
percona-toolkit 3.0.2

### PR DESCRIPTION
**Pull request by damienlepage**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by nijikon** [comment]
#7812

**Comment by nijikon** [comment]
@damienlepage you need this particular version or you just bumping it?

**Comment by damienlepage** [comment]
@nijikon sorry I missed the previous PR #7812. I need this version but it looks like the pt-summary bug that you opened hasn't been fixed - https://bugs.launchpad.net/percona-toolkit/+bug/1653331

**Comment by nijikon** [comment]
@damienlepage yup, upstream does not care :)

**Comment by ilovezfs** [comment]
I think we should probably remove this formula if upstream has no intention of supporting macOS and the current version is broken.

**Comment by MikeMcQuaid** [comment]
Non-removal options: 

1. stay on the current version until this bug gets fixed (i.e. forever)
1. update the version and remove `pt-summary` if it's 100% broken

I favour 2, personally.

**Comment by ilovezfs** [comment]
We know `pt-summary` is broken because it's the only we test in the test block. Do we have any reason to believe the other commands aren't equally broken?

**Comment by MikeMcQuaid** [comment]
@damienlepage presumably does as he wants to use this.

**Comment by ilovezfs** [comment]
OK let's find some command that spits out a zero exit code with the latest version and ship.

**Comment by MikeMcQuaid** [comment]
👍

**Comment by damienlepage** [comment]
Other commands definitely work (at least some) but most of them require a database which makes it hard to test in the formula. I found the following that works fine when running directly but for some reason times out through homebrew. Any idea?
```
  test do
    system bin/"pt-fingerprint --query \"select 1\""
  end
```

**Comment by nijikon** [comment]
@damienlepage switch the test to that command and we will ship this.

**Comment by damienlepage** [comment]
I modified the test but the same timeout I was seeing on my laptop is also happening on Jenkins. It looks like `pt-fingerprint` is not returning after printing the output when launched from ruby. FWIW I tried switching the test to `pt-summary --version` with the same result. Is this also a problem on the percona side?

```
==> /usr/local/Cellar/percona-toolkit/3.0.2/bin/pt-fingerprint --query "select 1"
select ?
Error: percona-toolkit: failed
Failed executing: /usr/local/Cellar/percona-toolkit/3.0.2/bin/pt-fingerprint --query "select 1" 
/usr/local/Homebrew/Library/Homebrew/formula.rb:1840:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1778:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1778:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/percona-toolkit.rb:41:in `block in <class:PerconaToolkit>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1677:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:886:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1676:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1670:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
```

**Comment by ilovezfs** [comment]
@MikeMcQuaid thoughts?

**Comment by MikeMcQuaid** [comment]
It's more than likely the majority of these tests requires a running MySQL server (which is not there at test time) and will time out without one.

**Comment by damienlepage** [comment]
@MikeMcQuaid [pt-fingerprint](https://www.percona.com/doc/percona-toolkit/2.1/pt-fingerprint.html) is a standalone tool, so the issue shouldn't be the lack of a MySQL server. It completes immediately when running manually and I can't figure out why it's not the case through `brew test`.
```
$ pt-fingerprint --query "select 1"
select ?
```

**Comment by ilovezfs** [comment]
The exit code is 1 when using the `--query` option. This should work
```
  test do
    input = "SELECT name, password FROM user WHERE id='12823';"
    output = pipe_output("#{bin}/pt-fingerprint", input, 0)
    assert_equal "select name, password from user where id=?;", output.chomp
  end
```

**Comment by damienlepage** [comment]
Awesome! Thank you @ilovezfs! So, I guess it's good to go now?

**Comment by ilovezfs** [comment]
Yup! Shipped. Thanks for the PR @damienlepage 

A protest on upstream's front lawn until they fix the `pt-summary` issue would be much appreciated.

**Pull request merged**
