### PR TITLE
sake 0.4.0 (new formula)

### PR DESCRIPTION
**Pull request by Jeehut**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

  This fixes https://github.com/xcodeswift/sake/issues/19.

### CODE REVIEW

**Comment by pepibumur** [comment]
Looks good now @Dschee

**Review by queengooborg — APPROVED** [review]
All checks by the test bot pass, and the formula looks good.  I'm happy with it!

**Comment by pepibumur** [comment]
Nice :). Is there anything else that needs to be done before merging @vinyldarkscratch ?

**Comment by vinyldarkscratch** [comment]
@pepibumur Not that I would imagine or know of -- we should be all good to go!  Now we wait for it to be merged.  🙂

**Comment by pepibumur** [comment]
Nice, thank you very much @vinyldarkscratch 😛

**Comment by ilovezfs** [comment]
@Dschee @pepibumur we'll need something that lets us do

```
make PREFIX=#{prefix} install
```

or
```
./install.sh #{prefix}
```
or similar.

As it stands there's far too much logic in the `def install` section that should not be maintained by us in the formula but should be maintained by upstream in its install scripts or Makefiles.

**Comment by pepibumur** [comment]
@Dschee would you mind closing this PR in favour of [this other one](https://github.com/Homebrew/homebrew-core/pull/24314). This PR is from a fork that I don't have access to so I cannot address @ilovezfs's comments.

**Comment by Dschee** [comment]
Sure, if it helps. Closing.

**Pull request closed without merging**
