### PR TITLE
kubernetes-cli 1.22.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /opt/homebrew/Cellar/kubernetes-cli/1.22.2/bin/kubectl version --client 2>&1
Error: kubernetes-cli: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /GitTreeState:"clean"/ to match "Client Version: version.Info{Major:\"1\", Minor:\"22+\", GitVersion:\"v1.22.2-dirty\", GitCommit:\"8b5a19147530eaac9476b0ab82980b4088bbc1b2\", GitTreeState:\"dirty\", BuildDate:\"2021-09-15T21:31:32Z\", GoVersion:\"go1.17\", Compiler:\"gc\", Platform:\"darwin/arm64\"}\n".
```

Somehow the `git checkout` becomes `dirty` checkout.

Relates to https://github.com/kubernetes/kubernetes/blob/03ccab222b78bd00f57d9f677136bf7c22bd4f19/hack/lib/version.sh#L68-L95

**Comment by branchvincent** [comment]
upstream builds with go 1.16 while we're on 1.17, and somewhere they must be running `go fmt`. not sure how we didn't see this in #83413

```diff
diff --git a/cmd/kubeadm/app/apis/bootstraptoken/v1/zz_generated.deepcopy.go b/cmd/kubeadm/app/apis/bootstraptoken/v1/zz_generated.deepcopy.go
index 60e9998c35d..1dcf76cb9b9 100644
--- a/cmd/kubeadm/app/apis/bootstraptoken/v1/zz_generated.deepcopy.go
+++ b/cmd/kubeadm/app/apis/bootstraptoken/v1/zz_generated.deepcopy.go
@@ -1,3 +1,4 @@
+//go:build !ignore_autogenerated
 // +build !ignore_autogenerated
 
 /*
```

**Comment by branchvincent** [comment]
Interesting, what changed?

**Review by branchv — APPROVED** [review]

**Comment by chenrui333** [comment]
nothing changed, k8s-cli build is always weird like this.

**Pull request closed without merging**
