### PR TITLE
checkstyle 7.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
@DomT4 Are you sure? No fits of domitus?

**Comment by DomT4** [comment]
It looks grim, but I couldn't immediately think of a way for it not to look so grim so I left it, heh.

**Comment by ilovezfs** [comment]
I'll see if I can make it less awful.

**Comment by ilovezfs** [comment]
will worry about the test later

**Pull request closed without merging**
