### PR TITLE
Update duck.rb

### PR DESCRIPTION
**Pull request by jd-a**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
The resulting executable fails unfortunately, to me it is unclear how to fix the cause.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like something went wrong when building the dynamic library:

```
Error: Failed changing dylib ID of /usr/local/Cellar/duck/6.9.3.30061/libexec/Contents/Frameworks/libcore.dylib
  from /usr/local/opt/duck/libexec/Contents/Frameworks/libcore.dylib
    to @@HOMEBREW_PREFIX@@/opt/duck/libexec/Contents/Frameworks/libcore.dylib
==> Bottling duck--6.9.3.30061.high_sierra.bottle.tar.gz...
Error: Updated load commands do not fit in the header of /usr/local/Cellar/duck/6.9.3.30061/libexec/Contents/Frameworks/libcore.dylib. /usr/local/Cellar/duck/6.9.3.30061/libexec/Contents/Frameworks/libcore.dylib needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
```

**Comment by fxcoudert** [comment]
We need to pass `-headerpad_max_install_names` to the build process. Our shim should do it, but apparently it's failing (or not being called). Someone who understands `maven` could do it.

In `mas`, this is how we do it:

```
    xcconfig = buildpath/"Overrides.xcconfig"
    xcconfig.write <<~EOS
      OTHER_LDFLAGS = -headerpad_max_install_names
    EOS
    ENV["XCODE_XCCONFIG_FILE"] = xcconfig
```

**Comment by dkocher** [comment]
Previously discussed in https://github.com/Homebrew/homebrew-core/pull/36060.

**Comment by dkocher** [comment]
Superseded by #37466 which contains the suggested fix with the additional linker flag.

**Pull request closed without merging**
