### PR TITLE
brew-postgresql-upgrade-database: fix locale issues

### PR DESCRIPTION
**Pull request by Bo98**
Ref #47110.

Fixes two issues:
* Not all locale and encoding settings were migrated, resulting in errors in `pg_upgrade`.
* Potential failure to migrate if the the previous PostgreSQL server is up via `brew services`. Now code is there to ensure that service is stopped before migration.

I've done limited testing on this locally but it would be good if someone could have a little look over and see if they agree with what I've done.

### CODE REVIEW

**Comment by stevek123** [comment]
It fixed the issue for me.

**Comment by SMillerDev** [comment]
Isn't there a ruby call you can do to stop a brew service?

**Comment by Bo98** [comment]
No idea - this is based on the previous code above.

**Comment by mrleeio** [comment]
Also fixed my upgrade.  Thanks.

**Comment by Bo98** [comment]
Thanks for the testing feedback @stevek123 and @mrleeio.

**Pull request merged**
