### PR TITLE
zsh-history-enquirer 1.3.0 (new formula)

### PR DESCRIPTION
**Pull request by danielbayley**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by zthxxx** [comment]
test failed while installation

image

**Comment by danielbayley** [comment]
> test failed while installation

For some reason the `test` hangs and times out only on linux… I don’t know why; I only use macOS…

**Comment by danielbayley** [comment]
@zthxxx Any ideas?

**Comment by zthxxx** [comment]
seems npm global install permissions errors

**Comment by chenrui333** [comment]
looks like just linux test failure?

**Comment by danielbayley** [comment]
> seems npm global install permissions errors

So surely this is an issue with the CI, rather than this particular PR…?

**Comment by danielbayley** [comment]
> seems npm global install permissions errors

So surely this is an issue with the CI, rather than this particular PR…?

**Pull request closed without merging**
