### PR TITLE
libmatio 1.5.18

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
no need to update the test resource file

**Comment by chenrui333** [comment]
license file (`COPYING`):

```
Copyright (c) 2011-2020, Christopher C. Hulbert
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

```

**Comment by chenrui333** [comment]
```
 Traceback (most recent call last):
   File "/usr/local/Cellar/gobject-introspection/1.66.0/bin/g-ir-scanner", line 99, in <module>
     sys.exit(scanner_main(sys.argv))
   File "/usr/local/Cellar/gobject-introspection/1.66.0/lib/gobject-introspection/giscanner/scannermain.py", line 606, in scanner_main
     main.transform()
   File "/usr/local/Cellar/gobject-introspection/1.66.0/lib/gobject-introspection/giscanner/maintransformer.py", line 74, in transform
     self._add_standalone_doc_sections()
   File "/usr/local/Cellar/gobject-introspection/1.66.0/lib/gobject-introspection/giscanner/maintransformer.py", line 114, in _add_standalone_doc_sections
     self._namespace.append(node)
   File "/usr/local/Cellar/gobject-introspection/1.66.0/lib/gobject-introspection/giscanner/ast.py", line 461, in append
     raise ValueError("Namespace conflict: %r" % (node, ))
 ValueError: Namespace conflict: DocSection('interpolate')
 make[2]: *** [Vips-8.0.gir] Error 1
 make[1]: *** [install-recursive] Error 1
 make: *** [install-recursive] Error 1
```

**Comment by iMichka** [comment]
The vips build error was reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1880830

**Pull request closed without merging**
