### PR TITLE
qt 6.2.0

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by paperchalice** [comment]
[`kCGColorSpaceITUR_2100_PQ`](https://developer.apple.com/documentation/coregraphics/kcgcolorspaceitur_2100_pq?language=objc) is only available on macOS 11.0+, and [`chromium`](https://github.com/qt/qtwebengine-chromium/blob/202e34476e934633b3c2e4679a53c4b0847364a8/chromium/ui/gfx/mac/io_surface.cc#L167) seems just using the latest API.

**Comment by carlocab** [comment]
No wonder Catalina took ages; it attempted to build `qt` from source seven (!) times.

**Comment by paperchalice** [comment]
Seems `chromium` should be built with the latest SDK, because it uses `__builtin_available()` not macro.

**Review by carlocab — APPROVED** [review]
Thanks, @paperchalice!

**Pull request closed without merging**
