### PR TITLE
bzt 1.15.2

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Not sure this will work, but hopefully it addresses the CI failure in #71322.

### CODE REVIEW

**Comment by carlocab** [comment]
Nope, doesn't work.

**Comment by bayandin** [comment]
It looks like we need to add `cython` for fuzzyset: https://github.com/Blazemeter/taurus/pull/1437

**Comment by bayandin** [comment]
> It looks like we need to add `cython` for fuzzyset: [Blazemeter/taurus#1437](https://github.com/Blazemeter/taurus/pull/1437)

Didn't help (also there's a fuzzyset issue https://github.com/axiak/fuzzyset/issues/28)

@carlocab maybe we could switch it to python@3.8 at least?

**Comment by carlocab** [comment]
Hm, I was thinking we needed `python@3.9` because the linked issues suggested that the problem might have to do with `numpy` linking with macOS Accelerate -- so the solution should be to use our `numpy` which doesn't.

I suppose `python@3.8` is worth a try.

**Comment by carlocab** [comment]
Seems to work on python@3.8 on Mojave. Still doesn't build on ARM though.

**Comment by Bo98** [comment]
I sugggest regenerating/updating the resources. Some dependencies will no longer be needed with Python 3.8 and some like `numpy` will likely need an update to build properly.

Depending on both `cython` and `python@3.8` sounds like a bad idea - that means it's depending on both 3.8 and 3.9 during build time.

**Comment by jonchang** [comment]
I've updated the python resources using the pypi-poet method including Cython as a resource. This appears to build fine on my intel big sur machine. Since this is blocking a python security patch release we should try to merge this and the python update asap.

**Comment by carlocab** [comment]
Thanks @jonchang!

**Comment by jonchang** [comment]
(Also, can I point out how much _fun_ upgrades are going to be now that python cryptography also depends on rust?)

**Comment by Bo98** [comment]
Might need to consider multi-VM parallelism to test Rust update PRs.

**Comment by carlocab** [comment]
I've been thinking that, actually. Though more for any formulae with many dependents, so this also includes rust, go, Python, etc.

**Pull request closed without merging**
