### PR TITLE
Fix crash from the usage of %n in dynamic format strings on High Sierra

### PR DESCRIPTION
**Pull request by JCount**
Fix crash from the usage of %n in dynamic format strings on High Sierra

This should provide a fix for some of the issues mentioned in #14418.

cc @ilovezfs

### CODE REVIEW

**Review by mistydemeo — CHANGES_REQUESTED** [review]
The Macports patches need to be `patch :p0` - they won't apply with the default.

**Comment by JCount** [comment]
@mistydemeo Thanks, wow... I'm not certain where my brain was...

**Comment by mistydemeo** [comment]
Can confirm these fix the bugs after fixing the patch prefix level. Things that repro the crashes without a patch:

* `bison` - segfaults during `make`
* `coreutils` - `gtty sane`
* `gzip` - `gzip --help`
* `m4` - Run `m4` on any file
* `nano` - Try to edit any file in nano

**Review by mistydemeo — APPROVED** [review]

**Comment by JCount** [comment]
Thanks @mistydemeo 😄

**Comment by MikeMcQuaid** [comment]
Just to double check: have all these patches been submitted upstream?

**Comment by chdiza** [comment]
Is it really that all these projects have the same bug, or is it that Apple has made its yearly decision to break things for no reason?

**Pull request merged**
