### PR TITLE
swift: testing python version detection

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Seems like it's from https://github.com/apple/llvm-project/blob/swift-5.8.1-RELEASE/llvm/cmake/modules/CrossCompile.cmake#L70 (which doesn't passthrough Python) but that should only happen when crosscompling: https://github.com/apple/llvm-project/blob/swift-5.8.1-RELEASE/llvm/CMakeLists.txt#L1035-L1039 (https://github.com/apple/llvm-project/blob/swift-5.8.1-RELEASE/llvm/CMakeLists.txt#L681-L683).

Possibly because of https://github.com/Kitware/CMake/blob/6e7a1b5b8c42e8d5d0d70aaa9b929ae6d81a79b7/Modules/CMakeDetermineSystem.cmake#L181-L187 paired with https://github.com/apple/swift/blame/swift-5.8.1-RELEASE/utils/swift_build_support/swift_build_support/products/product.py#L312.

Looks like a `-DCMAKE_CROSSCOMPILING=OFF` might work?

**Comment by Bo98** [comment]
`--llvm-cmake-options=-DCROSS_TOOLCHAIN_FLAGS_LLVM_NATIVE=-DPython3_EXECUTABLE=#{python3}` probably works.

**Comment by Bo98** [comment]
Similarly, may need `-DCLANG_COMPILER_RT_CMAKE_ARGS=-DPython3_EXECUTABLE=#{python3}` passed to `--llvm-cmake-options`. `--llvm-cmake-options` is comma separated. https://github.com/llvm/llvm-project/blob/9596676e6586767e7ae412ed26fbd8e3a16a4c18/clang/runtime/CMakeLists.txt#L78

**Comment by Bo98** [comment]
It seems CMake might support reading `Python3_ROOT_DIR` from the environment so we could try that: https://github.com/Kitware/CMake/blob/2040b79a39a6d1ea3a60e9aba24907af54599134/Modules/FindPython/Support.cmake#L1825. Might work universally if so rather than chasing every cmake call.

**Comment by cho-m** [comment]
> It seems CMake might support reading `Python3_ROOT_DIR` from the environment so we could try that: https://github.com/Kitware/CMake/blob/2040b79a39a6d1ea3a60e9aba24907af54599134/Modules/FindPython/Support.cmake#L1825. Might work universally if so rather than chasing every cmake call, though it's tricky to follow how FindPython works.

Not sure if that will work if `Python3_FIND_STRATEGY` is default (`VERSION`) as I think it will try every location anyways. Making it select `LOCATION` in every CMake call is probably going to go the same way.

---

Worst case, I will just give up and try switching to `python@3.12`. Sadly makes the build less reproducible and may break if newer Python version is incompatible with scripts.

**Comment by Bo98** [comment]
> Not sure if that will work if `Python3_FIND_STRATEGY` is default (`VERSION`) as I think it will try every location anyways. Making it select `LOCATION` in every CMake call is probably going to go the same way.

Ah yes forgot about that. It will starting working with Swift 5.11 which bumps the minimum CMake for LLVM to above the policty change.

**Pull request closed without merging**
