### PR TITLE
Apache flink 1.4.0

### PR DESCRIPTION
**Pull request by juanmirocks**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See previous closed pull request due to not setting environment to java 8 (upstream doesn't support java 9): https://github.com/Homebrew/homebrew-core/pull/21823

### CODE REVIEW

**Comment by juanmirocks** [comment]
Sorry, but totally didn't get the error's reason.

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by vinyldarkscratch** [comment]
@BrewTestBot test this please

**Comment by vinyldarkscratch** [comment]
Logs indicate the following:
`log4j:WARN Please initialize the log4j system properly.`
`log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`

Snippet from the site listed above:
_This occurs when the default configuration files log4j.properties and log4j.xml can not be found and the application performs no explicit configuration. log4j uses Thread.getContextClassLoader().getResource() to locate the default configuration files and does not directly check the file system. Knowing the appropriate location to place log4j.properties or log4j.xml requires understanding the search strategy of the class loader in use. log4j does not provide a default configuration since output to the console or to the file system may be prohibited in some environments. Also see [FAQ: Why can't log4j find my properties in a J2EE or WAR application?](http://logging.apache.org/log4j/1.2/faq.html#a3.5)._

**Comment by JCount** [comment]
@juanmirocks What's your rationale for changing to a release variant that doesn't bundle hadoop binaries, given this is would be a marked change?

**Comment by juanmirocks** [comment]
@JCount Flink can pick up the hadoop version from the environment if existing. Otherwise it can also work without hadoop for clusters that do not need hdfs nor yarn.

More info: https://flink.apache.org/downloads.html

> Latest stable release (v1.4.0)

> Apache Flink® 1.4.0 is our latest stable release.

> An Apache Hadoop installation is not required to use Flink. If you plan to run Flink in YARN or process data stored in HDFS then select the version matching your installed Hadoop version.

> The binary releases marked with a Hadoop version come bundled with binaries for that Hadoop version, the binary release without bundled Hadoop can be used without Hadoop or with a Hadoop version that is installed in the environment, i.e. this version can pick up a Hadoop version from the classpath.

**Comment by vinyldarkscratch** [comment]
@juanmirocks This sounds like it could have some opportunistic linkage issues -- we'll want to make sure that Flink has a dependency upon Hadoop (either optional or recommended) and pass a flag to prevent it from linking to Hadoop if the user doesn't want it to.

**Comment by juanmirocks** [comment]
@vinyldarkscratch yes, putting a dependency is good -- I will do it.

I wouldn't know how to put in such a flag mechanism. Can this be done through homebrew? --  I will investigate if Flink has already a configuration builtin to do that.

**Comment by vinyldarkscratch** [comment]
@juanmirocks Thank you!  And, yes, Homebrew has a nice series of features to help you with this.  If the Flink installer can take an argument that says "don't use Hadoop" (like `--without-hadoop` for example), we could pass that in the following way:

```
args = %W[]
args << "--without-hadoop" if build.without? "hadoop"
(bin/"flink").write_env_script "#{libexec}/bin/flink", *args, Language::Java.java_home_env("1.8")
```

_Note: I could be wrong in how to pass the arguments into the binary.  My apologies if I am!_

**Pull request closed without merging**
