### PR TITLE
subversion 1.13.0

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Looks like our old friend from [last year](https://github.com/Homebrew/homebrew-core/pull/33530#issuecomment-450112779) is back:
```
checking for /usr/bin/ruby... /usr/bin/ruby
12:30:30 checking rb_hash_foreach... mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h
12:30:30 no
12:30:30 configure: WARNING: The detected Ruby is too old for Subversion to use
12:30:30 configure: WARNING: A Ruby which has rb_hash_foreach is required to use the
12:30:30 configure: WARNING: Subversion Ruby bindings
12:30:30 configure: WARNING: Upgrade to the official 1.8.2 release, or later
```
This occurs only on Mojave with Xcode 11; the mentioned command `/usr/bin/ruby -r mkmf -e 'exit(have_func("rb_hash_foreach") ? 0 : 1)'` also fails on there outside the brew environment. Mojave with Xcode 10 is unaffected.

**Comment by fxcoudert** [comment]
Can we build without ruby?

**Comment by EricFromCanada** [comment]
[Here's the problem](https://stackoverflow.com/a/58231417): Because Xcode 11 only ships with the 10.15 SDK with only Ruby 2.6 headers, Subversion needs to be compiled against the CLT's 10.14 SDK on Mojave even if Xcode is installed. What'd be the best way to do that?

**Comment by Bo98** [comment]
> Subversion needs to be compiled against the CLT's 10.14 SDK on Mojave

#46474 is somewhat related then. There's some discussion ongoing there.

**Comment by EricFromCanada** [comment]
Adding this gets past the above error:
```
    if MacOS.version >= :mojave && MacOS::CLT.installed? && MacOS::CLT.provides_sdk?
      ENV["SDKROOT"] = MacOS::CLT.sdk_path(MacOS.version)
    end
```
but then the `make swig-rb` step fails with:
```
/bin/sh "/private/tmp/subversion-20191108-12580-1nwg6x6/subversion-1.13.0/libtool" --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/gettext/include -I/usr/local/opt/openssl@1.1/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=nehalem -Xclang -target-feature -Xclang -aes -mmacosx-version-min=10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/include/darwin -O2  -DNDEBUG -Os -w -pipe -march=nehalem -Xclang -target-feature -Xclang -aes -mmacosx-version-min=10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/include/darwin  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl@1.1/include -I/usr/local/Cellar/subversion/1.13.0/libexec/serf/include/serf-1 -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/opt/sqlite/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/Cellar/lz4/1.9.2/include   -o subversion/libsvn_client/cleanup.lo -c subversion/libsvn_client/cleanup.c
subversion/bindings/swig/ruby/libsvn_swig_ruby/swigutil_rb.c:1628:38: error: use of undeclared identifier 'ruby_errinfo'; did you mean 'rb_errinfo'?
                                     ruby_errinfo,
                                     ^~~~~~~~~~~~
                                     rb_errinfo
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:651:7: note: 'rb_errinfo' declared here
VALUE rb_errinfo(void);
      ^
1 error generated.
```

**Comment by Bo98** [comment]
`-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk`

Looks like it's still mixing and matching SDKs. Although the solution I had was seemingly sufficient for Git (I'll double-check the logs), it perhaps isn't foolproof for everything.

**Comment by fxcoudert** [comment]
> Can we build without ruby?

**Comment by EricFromCanada** [comment]
Yes, but tracking down obscure SDK errors is SO much more fun!

**Comment by fxcoudert** [comment]
macOS interpreters, including Ruby, are going away at some point…

**Pull request closed without merging**
