### PR TITLE
zstd 1.1.3

### PR DESCRIPTION
**Pull request by mkjaer**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by JCount — CHANGES_REQUESTED** [review]
The patch has been merged, and I have confirmed it is included in the `1.1.3` release. If you could please remove it, this will probably be 🍏 . Thanks!

**Comment by mkjaer** [comment]
Sorry @JCount , I don't understand what you mean.

**Comment by JCount** [comment]
@mkjaer Ah, that is not an issue, I will say it differently. I keep forgetting that not everyone on Github speaks English as their primary language, I apologize.

What I am asking you to do is remove this section of code, because it is no longer needed and is preventing the formula from building:
```
diff --git a/Formula/zstd.rb b/Formula/zstd.rb
index 17359c6084..09a7e34f45 100644
--- a/Formula/zstd.rb
+++ b/Formula/zstd.rb
@@ -15,12 +15,6 @@ class Zstd < Formula
 
   depends_on "cmake" => :build
 
-  # https://github.com/facebook/zstd/pull/497
-  patch do
-    url "https://github.com/facebook/zstd/pull/497.patch"
-    sha256 "2bf9d85a083af66da3323f43b815fe41e21ebdab126dbbbe4d1e5f47d2e05036"
-  end
-
   def install
     system "make", "install", "PREFIX=#{prefix}/"
 ```

If you have any other questions, I will try to answer them. 😄

**Comment by mkjaer** [comment]
Thanks for the explanation.
English wasn't the problem (this time). The problem was I hadn't looked in the code, just used your `brew bump-formula-pr` tool so I wasn't aware there was a patch in the file 😄

**Comment by JCount** [comment]
😆 Well, that is what I get for looking at someone's Github profile and making assumptions.

**Review by JCount — APPROVED** [review]

**Comment by JCount** [comment]
@mkjaer Thank you for your contribution to Homebrew!! 🎉

**Comment by mkjaer** [comment]
And thank you for making such a great tool and make it so easy to contribute!

**Pull request closed without merging**
