### PR TITLE
jmxtrans 20160706-259

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- style tweaks
- move some items to `doc` and `pkgshare`

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
If you're happy, :shipit:

**Comment by ilovezfs** [comment]
@DomT4 I wouldn't say I'm remotely happy with the install method in this one, but at least it's sightly cleaner than I found it.

**Comment by DomT4** [comment]
Yeah, it's not glorious, but it'll do 😄.

**Pull request closed without merging**
