### PR TITLE
flann: remove resources

### PR DESCRIPTION
**Pull request by paperchalice**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why?

**Comment by paperchalice** [comment]
> Why?

https://www.cs.ubc.ca/research/flann is unavailable.

**Comment by paperchalice** [comment]
> Why?

https://www.cs.ubc.ca/research/flann is unavailable.

**Comment by SMillerDev** [comment]
Shouldn't we tell upstream about this instead of just removing the resources?

**Pull request closed without merging**
