### PR TITLE
qbs 2.0.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
It's supposed to be compatible with Qt6 according to pre-2.00 changelog; but I wanted to wait for the 6.5.0 to be merged maybe before opening with the change.

**Comment by p-linnane** [comment]
Odds are good that is going to be quite a while before 6.5.0 is ready. @fxcoudert has been working on it.

**Comment by Porkepix** [comment]
> Odds are good that is going to be quite a while before 6.5.0 is ready. @fxcoudert has been working on it.

To clarify, I don't think it needs it and it could be checked here, it's just that I usually prefer to check against the latest available versions, but it's a personal preference.

**Comment by p-linnane** [comment]
I agree that it should definitely use the latest that we can. Let me update to Qt6 here, assuming that it will work with 6.4.3

**Comment by fxcoudert** [comment]
Yes, there is still one blocking issue for Qt 6.5.0 on Intel. We will have to debug more, or wait for an upstream fix.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
