### PR TITLE
faas-cli 0.4

### PR DESCRIPTION
**Pull request by johnmccabe**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by johnmccabe** [comment]
@ilovezfs can you clarify how to get the `sha256` value, my reading of the docs imply that it should be that of the dowloaded source archive - `shasum -a 256 0.4.tar.gz`? This doesn't seem to match the sha256 generated when first creating a forumula?

**Comment by ilovezfs** [comment]
Any of these
```
curl -sL https://github.com/alexellis/faas-cli/archive/0.4.tar.gz | shasum -a256
shasum -a256 <(curl -sL https://github.com/alexellis/faas-cli/archive/0.4.tar.gz)
curl -sL https://github.com/alexellis/faas-cli/archive/0.4.tar.gz | openssl dgst -sha256
openssl dgst -sha256 <(curl -sL https://github.com/alexellis/faas-cli/archive/0.4.tar.gz)
```
or
```
curl -OL https://github.com/alexellis/faas-cli/archive/0.4.tar.gz
shasum -a256 0.4.tar.gz
```

**Comment by johnmccabe** [comment]
Thanks @ilovezfs I rechecked and it behaves as you point out, the sha256 is correct here then.
```
$ curl -sL https://github.com/alexellis/faas-cli/archive/0.4.tar.gz | shasum -a256
f7ecebde2545243e9f37f7feb9fc2a171585d3f9e7998f981611f038bbc93987  -
```

**Pull request closed without merging**
