### PR TITLE
libvirt: add HEAD & add devel version 1.3.5-rc1

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Add HEAD spec
- Add devel version 1.3.5-rc1

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@Jerzerak Not your bug but mind fixing this up while you're here: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2531/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/audit_libvirt/ ? Thanks!

**Comment by DomT4** [comment]
The `HEAD` will need extra steps, upstream doesn't keep a ready-made `configure` script in git.

**Comment by Jerzerak** [comment]
@MikeMcQuaid @DomT4 would you guys like a `test` block added as well?

**Comment by DomT4** [comment]
If you're comfortable writing one that'd be wonderful!

**Comment by justinclift** [comment]
@Jerzerak Out of curiosity, have you managed to get HEAD to compile on OSX?  I looked into it a while ago (last year maybe?), and it didn't work at the time.

Generating the configure script has a dependency on rpcgen, and the MacOS (BSD) based one doesn't have the capabilities required.  On Linux, the glibc provided rpcgen works fine... but there doesn't seem to be a Homebrew formula for that which we could add a `depends_on`.

If you've not managed to get HEAD working, this PR can probably be closed.  Newer versions of libvirt are already merged in Homebrew.

**Comment by dunn** [comment]
Closing per the above, but thank you for the submission <3

**Pull request closed without merging**
