### PR TITLE
deheader 1.6

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by apjanke** [comment]
Failure in the `untar` step?

```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161001-21745-6nqgub.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/deheader.rb --build-bottle --verbose
==> Downloading http://www.catb.org/~esr/deheader/deheader-1.6.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/deheader-1.6.tar.gz
==> Verifying deheader-1.6.tar.gz checksum
tar xzf /Users/brew/Library/Caches/Homebrew/deheader-1.6.tar.gz
deheader-1.6/deheader.1: Can't create 'deheader-1.6/deheader.1'
tar: Error exit delayed from previous errors.
Error: Failure while executing: tar xzf /Users/brew/Library/Caches/Homebrew/deheader-1.6.tar.gz
```

I get the same error if I manually download and extract it.

Looks like it might be an actual error with the distribution tarball, with `deheader.1` included twice.

```
$ tar tf deheader-1.6.tar.gz | grep deheader\\.1
deheader-1.6/deheader.1
deheader-1.6/deheader.1
```

**Comment by eric-s-raymond** [comment]
Bug acknowledged, fix made upstream.

I've never seen a version of tar that would error out like this on a duplicate before.

**Comment by ilovezfs** [comment]
Thanks @eric-s-raymond

**Comment by ilovezfs** [comment]
@eric-s-raymond PR refreshed with a workaround in case you're not ready to cut a new release.

**Pull request closed without merging**
