### PR TITLE
google-java-format 1.7

### PR DESCRIPTION
**Pull request by dpursehouse**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by dpursehouse** [comment]
This doesn't work yet.  Blocked on https://github.com/google/google-java-format/issues/338

**Comment by javian** [comment]
I guess you could do an inreplace and remove the snapshot part of the text in the Formula

**Comment by fxcoudert** [comment]
We're going to close this for now, we'll be happy to consider the next version, or this one once it's fixed. Thanks @dpursehouse

**Comment by dpursehouse** [comment]
@fxcoudert I have this working now, and have pushed a new version to the branch on my fork.  Can you re-open this PR?

@javian thanks for the suggestion.  `inreplace` didn't seem to work, but I fixed it using `mvn versions:set`.

**Comment by dpursehouse** [comment]
Replaced with #37083

**Pull request closed without merging**
