### PR TITLE
augustus: replace private method call

### PR DESCRIPTION
**Pull request by gromgit**
Per https://discourse.brew.sh/t/calling-one-formulas-methods-in-another/8382

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Do these need revision bumps?

**Comment by gromgit** [comment]
> Do these need revision bumps?

I think they should, if for no other reason than to force a verifying rebuild.

The `dynare` rebuild, for example, caught a stale Git archive.

**Comment by SMillerDev** [comment]
> I think they should, if for no other reason than to force a verifying rebuild.
> 
> The `dynare` rebuild, for example, caught a stale Git archive.

Any change will be built, no need to revision bump unless users need to be aware of the change.

**Comment by gromgit** [comment]
OK, noted. Since a revision bump isn't necessary, and there's an [ongoing discussion](https://discourse.brew.sh/t/calling-one-formulas-methods-in-another/8382/9) as to whether it might be better to just fix `version_suffix` in `gcc` instead, I'll close all these PRs for now.

**Pull request closed without merging**
