### PR TITLE
Shellshare - First release on homebrew

### PR DESCRIPTION
**Pull request by arthar360**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Passing on this now as it's a self-submission of a very new project. Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!

**Comment by arthar360** [comment]
@MikeMcQuaid I am new in brew PR's. Just for curiosity, I want to ask and say.. By creating tap, users will need to enter "brew tap user/repo/foo" , Which is a tiresome job. Users can also download the script and run it by doing _python shellshare_. I want this to be simple like "brew install shellshare". Why is the way I am trying to add PR not acceptable?

**Comment by MikeMcQuaid** [comment]
> By creating tap, users will need to enter "brew tap user/repo/foo"

They can do `brew install arthar360/tap/shellshare`

> Why is the way I am trying to add PR not acceptable?

Your repository is too new and it's not a popular enough project yet, sorry.

**Comment by vitorbaptista** [comment]
Hi @MikeMcQuaid, @arthar360 submitted this PR using his fork of shellshare. The original repository is https://github.com/vitorbaptista/shellshare, which as 100+ stars. I wonder if that's popular enough, or if you'd still advise me to create a tap.

**Comment by MikeMcQuaid** [comment]
It looks like a new PR was created in https://github.com/Homebrew/homebrew-core/pull/10518 so let's move conversation there.

**Pull request closed without merging**
