### PR TITLE
commitizen 2.4.2

### PR DESCRIPTION
**Pull request by harens**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by dtrodrigues — CHANGES_REQUESTED** [review]
`colorama`, `prompt-toolkit`, and `questionary` need to be updated

**Comment by dtrodrigues** [comment]
Changing the primary url to the PyPI one (https://files.pythonhosted.org/packages/f6/1f/d5d788c8098a151913e0cdf6d639f9b47ce2736d3dc79a7aec333cb06b64/commitizen-2.4.2.tar.gz)will allow `bump-formula-pr` to auto-update the resources.

**Comment by harens** [comment]
Thanks for your suggestions @dtrodrigues. I've added your changes and noted you as a co-author. I also included a `livecheck block`.

**Review by dtrodrigues — APPROVED** [review]
Thanks for those changes and for making this contribution to Homebrew @harens!

**Pull request closed without merging**
