### PR TITLE
licensefinder 7.1.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Not really sure about the `on_system` part nor the fact it seems to specify things for specific versions of macos such as mojave.

**Comment by chenrui333** [comment]
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/licensefinder/7.1.0/bin/license_finder
  /home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/specification.rb:1401:in `rescue in block in activate_dependencies': Could not find 'rexml' (>= 0) among 77 total gem(s) (Gem::MissingSpecError)
```

**Comment by chenrui333** [comment]
build/test out fine in my local. Give it a re-run.

**Comment by chenrui333** [comment]
```
  /home/linuxbrew/.linuxbrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'rexml' (>= 0) among 77 total gem(s) (Gem::MissingSpecError)
  Checked in 'GEM_PATH=/tmp/licensefinder-test-20221204-7772-1albw4m/gem_home:/home/linuxbrew/.linuxbrew/Cellar/licensefinder/7.1.0/libexec' , execute `gem env` for more information
```

**Pull request closed without merging**
