### PR TITLE
node@18 18.12.1

### PR DESCRIPTION
**Pull request by ljahier**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
15 minutes for ARM runners sounds like it'll needs less than 90 for x86, hence doesn't need long run? Maybe because this was inherited from unversioned formula?
Anyway tag is from 1H ago and jobs aren't picked up yet on x86, strangely.

**Comment by ljahier** [comment]
I also find it long. I don't know if I did something wrong

**Comment by SMillerDev** [comment]
> 15 minutes for ARM runners sounds like it'll needs less than 90 for x86, hence doesn't need long run? Maybe because this was inherited from unversioned formula?

It might not, we'll see. All node versions so far need it.

> Anyway tag is from 1H ago and jobs aren't picked up yet on x86, strangely.

There are 228 pull requests open, it's just busy.

**Comment by Porkepix** [comment]
> > 15 minutes for ARM runners sounds like it'll needs less than 90 for x86, hence doesn't need long run? Maybe because this was inherited from unversioned formula?
> 
> It might not, we'll see. All node versions so far need it.

I thought I saw only the unversioned one needing it because that's the one a lot of other formulas depends on, so tests are longer, my bad if that's not the case.

> > Anyway tag is from 1H ago and jobs aren't picked up yet on x86, strangely.
> 
> There are 228 pull requests open, it's just busy.

I always thought the long runs had their distinct, reserved, pool of runners and were not using the same as the "standard" PRs (They generally start quickly after the tag is set), so same, my bad if my observation was wrong.

**Comment by SMillerDev** [comment]
> I always thought the long runs had their distinct, reserved, pool of runners and were not using the same as the "standard" PRs (They generally start quickly after the tag is set), so same, my bad if my observation was wrong.

They don't, there's a shared pool and we're just limiting how many of them can be used for long runs.

**Review by SMillerDev — APPROVED** [review]
Thanks @ljahier  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
