### PR TITLE
Update CGAL  to 4.14

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR is a work in progress to update CGAL to version 4.14.
For now, it is an update to 4.14-beta2 and therefore should not be integrated. It will be updated to 4.14 when it is out, and the name of the PR will be changed then.

### CODE REVIEW

**Comment by maxGimeno** [comment]
@lrineau The checks you wanted me to pass with this WIP PR return:
"Error: Stable version URLs should not contain beta"
which seems to validate my thoughts that this preliminary step is more work for nothing.

**Comment by lrineau** [comment]
@fxcoudert You told me that we can check beta release with the CI of HomeBrew. Is there an extra declaration that has to be made in the formula?

**Comment by maxGimeno** [comment]
What I mean is that if the whole PR is entirely different in the beta phase than after it, I don't see the gain of time.

**Comment by fxcoudert** [comment]
You're welcome to use WIP pull requests to test if upcoming releases are working fine within Homebrew. You will get that audit warning, which is expected, so the question is: was there any other CI failure reported? If not, then it's good!

**Comment by maxGimeno** [comment]
It is the only problem that has been reported.

**Comment by lrineau** [comment]
[**@fxcoudert**](https://github.com/fxcoudert) commented on [Mar 18, 2019, 12:09 PM GMT+1](https://github.com/Homebrew/homebrew-core/pull/38008#issuecomment-473867080 "2019-03-18T11:09:16Z - Replied by Github Reply Comments"):
> PS: GitHub now has [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) which may be useful for that purpose. It makes it clear that it's a draft, and it can't be merged by mistake :)

Unfortunately, there is one big issue with draft PRs: the CI does not see them.

**Comment by fxcoudert** [comment]
> there is one big issue with draft PRs: the CI does not see them

Indeed… I thought it did.

**Comment by lrineau** [comment]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/39433/testReport/

The results are all good but the test `brew audit cgal --online` that reports the error about beta:
> Stable version URLs should not contain beta

That's good! Thanks, Maxime.

**Comment by fxcoudert** [comment]
@lrineau FYI, I just checked, and draft pull requests *are* indeed run on our CI system.

Regarding this pull request, do you want to close it for now? When is release expected?

**Comment by lrineau** [comment]
Since that beta2 release, there has been a beta3 (that showed an error with the vcpkg packages), and then a beta4, released about 10 minutes ago.

We plan to update this PR very soon.

As for the release date, I hope that it would be released this week, but probably it will only be released next week, maybe the 2nd of April (to avoid the 1st, because we have an April's joke every year).

**Comment by lrineau** [comment]
@maxGimeno Please add me as a collaborator to your fork. I would like to fix the `test` part of the formula.

**Comment by lrineau** [comment]
(Thanks Maxime.) I have pushed a patch to fix `brew test cgal`.

@fxcoudert I am surprised that the jenkins test do not run `brew test` of the formula.

**Comment by fxcoudert** [comment]
It does run the test, and it actually failed:

```
==> cmake -L -DCMAKE_BUILD_RPATH=/usr/local/lib -DCMAKE_PREFIX_PATH=/usr/local/Cellar/cgal/4.14-beta4 .
Failed to execute: cmake
Error: cgal: failed
```

You need to make `cmake` a test dependency too:

```
  depends_on "cmake" => [:build, :test]
```

**Comment by lrineau** [comment]
Strange. The test for CGAL-4.13 fails on my Linux machine:
```
lrineau@bonnard:~/Git/brew% ./bin/brew test --verbose cgal
Testing cgal
==> /usr/bin/g++ -I/home/lrineau/Git/brew/Cellar/cgal/4.13/include -L/home/lrineau/Git/brew/Cellar/cgal/4.13/lib surprise.cpp -o test -lCGAL
/usr/bin/ld: warning: libboost_thread-mt.so.1.68.0, needed by /home/lrineau/Git/brew/Cellar/cgal/4.13/lib/libCGAL.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/lrineau/Git/brew/Cellar/cgal/4.13/lib/libCGAL.so: undefined reference to `boost::detail::get_tss_data(void const*)'
/usr/bin/ld: /home/lrineau/Git/brew/Cellar/cgal/4.13/lib/libCGAL.so: undefined reference to `boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)'
collect2: error: ld returned 1 exit status
```

That is why I had to change it. And probably my local run of `brew test cgal.rb` was polluted by the system CMake `/usr/bin/cmake`.


Maybe the different behavior of the linker on MacOS made the CGAL-4.13 test works in Jenkins. @fxcoudert Do you know if the Homebrew project has the resources and the intention to add Windows and Linux builders, in the Jenkins tests?

**Comment by lrineau** [comment]
@fxcoudert CGAL-4.14 (final version) has been published, and @maxGimeno's commit https://github.com/Homebrew/homebrew-core/pull/38008/commits/df1ceed69b55b57a6c4bd7df9621af8b4ac41d78 has updated the formula to it. I think the title of this PR can be changed now (to remove "WIP").

**Comment by maxGimeno** [comment]
I changed the title

**Comment by fxcoudert** [comment]
Thanks @maxGimeno and @lrineau

**Pull request closed without merging**
