### PR TITLE
snappystream 0.2.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
```
/tmp/snappystream-20161118-17540-pxkkg0/snappystream-0.2.4/test/test.cpp:10:10: fatal error: 'gtest/gtest.h' file not found
#include <gtest/gtest.h>
```

Cursory online search suggests that it's from [googletest](https://github.com/google/googletest), which I don't believe we currently package.

**Comment by woodruffw** [comment]
Looks like upstream pushed a new version of the `0.2.4` tag that fixes the build for us:

```bash
$ sha256sum 0.2.4.tar.gz
d415c79a42033338c9327cee95fe10a8745f4373644fb8271f4bacc892c79eda  0.2.4.tar.gz
```

**Comment by vladshablinsky** [comment]
@woodruffw still seems to fail?

```
➜ vlad:homebrew-core$ brew install --build-bottle snappystream                                                                                                              master ✗
==> Using the sandbox
==> Downloading https://github.com/hoxnox/snappystream/archive/0.2.4.tar.gz
Already downloaded: /Users/vlad/Library/Caches/Homebrew/snappystream-0.2.4.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/snappystream/0.2.4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRA
==> make all test install
Last 15 lines from /Users/vlad/Library/Logs/Homebrew/snappystream/02.make:
cd /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4 && /usr/local/Cellar/cmake/3.7.0/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4 /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4 /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4 /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4 /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/CMakeFiles/test_snappystream.dir/DependInfo.cmake --color=
Scanning dependencies of target test_snappystream
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/test_snappystream.dir/build.make CMakeFiles/test_snappystream.dir/build
make[2]: *** No rule to make target `gtest/src/gtestlib-build/libgtest_main.a', needed by `test_snappystream'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 89%] Building CXX object CMakeFiles/test_snappystream.dir/src/snappystreamcfg.cpp.o
[ 89%] Building CXX object CMakeFiles/test_snappystream.dir/src/isnappystream.cpp.o
[ 89%] Building CXX object CMakeFiles/test_snappystream.dir/src/osnappystream.cpp.o
[ 94%] Building CXX object CMakeFiles/test_snappystream.dir/test/test.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++    -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/src -I/usr/local/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/gtest/src/gtestlib/include  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -o CMakeFiles/test_snappystream.dir/test/test.cpp.o -c /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/test/test.cpp
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++    -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/src -I/usr/local/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/gtest/src/gtestlib/include  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -o CMakeFiles/test_snappystream.dir/src/snappystreamcfg.cpp.o -c /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/src/snappystreamcfg.cpp
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++    -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/src -I/usr/local/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/gtest/src/gtestlib/include  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -o CMakeFiles/test_snappystream.dir/src/isnappystream.cpp.o -c /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/src/isnappystream.cpp
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++    -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/src -I/usr/local/include -I/tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/gtest/src/gtestlib/include  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -o CMakeFiles/test_snappystream.dir/src/osnappystream.cpp.o -c /tmp/snappystream-20161120-49632-z6iyzi/snappystream-0.2.4/src/osnappystream.cpp
make[1]: *** [CMakeFiles/test_snappystream.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
snappystream 0.2.4 https://github.com/Homebrew/homebrew-core/pull/7052

Error: Your Xcode (8.0) is outdated.
Please update to Xcode 8.1 (or delete it).
Xcode can be updated from the App Store.


Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

**Comment by ilovezfs** [comment]
This failure seems to be known: https://github.com/Homebrew/homebrew-core/issues/6408

So I'm closing this out.

**Pull request closed without merging**
