### PR TITLE
puzzles 20240302

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by krehel** [comment]
It seems this is the same as the [Cask](https://github.com/Homebrew/homebrew-cask/blob/b83189deb23dd685e3186282562daa6f670b6b00/Casks/p/puzzles.rb)?  Is there a reason we have this in both repos?

**Comment by chenrui333** [comment]
> It seems this is the same as the [Cask](https://github.com/Homebrew/homebrew-cask/blob/b83189deb23dd685e3186282562daa6f670b6b00/Casks/p/puzzles.rb)? Is there a reason we have this in both repos?

cask was introduced in https://github.com/Homebrew/homebrew-cask/pull/4933

for core, it was done via this commit, https://github.com/Homebrew/homebrew-core/commit/ec6c389d2ea3ef34f6bf15c7e6945359214e67a3

---

Since it exists in both, maybe deprecate cask in favor of core?

**Comment by krehel** [comment]
This looks like it installs a GUI application, but not into `/Applications`.  Running it from the command line with `puzzles` launches that GUI.

**Review by bevanjkay — APPROVED** [review]

**Comment by chenrui333** [comment]
> This looks like it installs a GUI application, but not into `/Applications`. Running it from the command line with `puzzles` launches that GUI.

i would say, if it is the same GUI as cask, we can probably just deprecate the cask one. I already filed a PR for discussion, https://github.com/Homebrew/homebrew-cask/pull/168128

**Pull request merged**
