### PR TITLE
lighthouse 2.3.1

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:329:9: error: no member named 'isless' in the global namespace
    using ::isless;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:330:9: error: no member named 'islessequal' in the global namespace
    using ::islessequal;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:331:9: error: no member named 'islessgreater' in the global namespace
    using ::islessgreater;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:332:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:333:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    13 errors generated.
```

**Comment by michaelsproul** [comment]
Hi @chenrui333, Lighthouse dev here :wave:

Have you seen errors like this on your CI before? As far as I can tell it's some issue that only occurs on Apple silicon, and it's in one of Lighthouse's dependencies (`prost`) not Lighthouse itself. Further I can't find anything on the `prost` issue tracker about it, and searching around it seems to be some quirk of macOS C/C++ libs (:weary:).

I don't have access to any Apple silicon to test on at the moment, but if I get my M2 Macbook before this is fixed I'll come back and try to debug it :pray:

**Comment by chenrui333** [comment]
@michaelsproul I have m1 machine, let me know if you need anything to provide from my side.

**Comment by michaelsproul** [comment]
Can we try re-running CI on this PR, @PythonCoderAS would you mind re-opening it?

**Comment by chenrui333** [comment]
> I'm hoping that something will have changed in the macOS 11 CI in the meantime that will fix everything 😅

Per my experience, that does not matter that much.

**Comment by chenrui333** [comment]
@michaelsproul you can see the new attempt in [this PR](https://github.com/Homebrew/homebrew-core/pull/106928)

**Pull request closed without merging**
