### PR TITLE
protobuf 24.2

### PR DESCRIPTION
**Pull request by SMillerDev**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Arrow is missing a thrift dependency

**Comment by Moisan** [comment]
`bear` failure is unrelated to protobuf bump, it also happens on master: it fails to build with `fmt` `10.1`: https://github.com/rizsotto/Bear/issues/542

**Comment by ZhongRuoyu** [comment]
`bear` still needs a revbump:

```
==> brew linkage --test bear
==> FAILED
Full linkage --test bear output
  Missing libraries:
    unexpected (libprotobuf.so.23.4.0)
```

`netdata` failed unexpectedly on ARM runners:

```
==> brew bottle --verbose --json netdata --only-json-tab
==> FAILED
Full bottle netdata --only-json-tab output
  Error: bottling failed
  ==> Determining netdata bottle rebuild...
  ==> Bottling netdata--1.42.1_1.arm64_ventura.bottle.tar.gz...
  /opt/homebrew/opt/gnu-tar/bin/gtar --create --numeric-owner --mtime=2023-08-16 10:58:50 --sort=name --owner=0 --group=0 --numeric-owner --format=pax --pax-option=globexthdr.name=/GlobalHead.%n,exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime --file /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/netdata--1.42.1_1.arm64_ventura.bottle.tar netdata/1.42.1_1
  ==> Detecting if netdata--1.42.1_1.arm64_ventura.bottle.tar.gz is relocatable...
  /opt/homebrew/Cellar/netdata/1.42.1_1/sbin/netdata
   --> match ''--disable-dependency-tracking' '--disable-silent-rules' '--prefix=/opt/homebrew/Cellar/netdata/1.42.1_1' '--sysconfdir=/opt/homebrew/etc' '--localstatedir=/opt/homebrew/var' '--libexecdir=/opt/homebrew/Cellar/netdata/1.42.1_1/libexec' '--with-math' '--with-zlib' '--enable-dbengine' '--with-user=netdata' 'UUID_LIBS=-lc' 'UUID_CFLAGS=-I/usr/include' 'CC=clang' 'CFLAGS=-DNDEBUG -I/private/tmp/netdata-202[308](https://github.com/Homebrew/homebrew-core/actions/runs/5997092347/job/16262953495?pr=139954#step:3:309)28-8141-y6c0tx/netdata-v1.42.1/resources/judy/include' 'LDFLAGS=-L/private/tmp/netdata-20230828-8141-y6c0tx/netdata-v1.42.1/resources/judy/lib' 'CXX=clang++' 'CXXFLAGS=-DNDEBUG' 'PKG_CONFIG_PATH=/opt/homebrew/opt/json-c/lib/pkgconfig:/opt/homebrew/opt/libuv/lib/pkgconfig:/opt/homebrew/opt/libyaml/lib/pkgconfig:/opt/homebrew/opt/lz4/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig:/opt/homebrew/opt/abseil/lib/pkgconfig:/opt/homebrew/opt/jsoncpp/lib/pkgconfig:/opt/homebrew/opt/protobuf/lib/pkgconfig:/opt/homebrew/opt/protobuf-c/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/opt/homebrew/Library' at offset 0x303cf4
  Warning: String '/opt/homebrew/Library' still exists in these files:
  Error: Bottle contains non-relocatable reference to /opt/homebrew/Library!
```

`netdata` saves all of the `configure` args. We can probably try to avoid referencing `HOMEBREW_LIBRARY` by unsetting `PKG_CONFIG_LIBDIR` (`PKG_CONFIG_PATH` should be sufficient for it to build).

**Review by ZhongRuoyu — APPROVED** [review]
Linux dep failures seem unrelated as the `brew test` steps succeeded. (Probably need to figure out why they happened, though...)

```
Error: 9 failed steps!
brew link berkeley-db
brew link gdbm
brew link perl
brew link berkeley-db
brew link gdbm
brew link perl
brew link berkeley-db
brew link gdbm
brew link perl
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> Linux dep failures seem unrelated as the `brew test` steps succeeded. (Probably need to figure out why they happened, though...)
> 
> ```
> Error: 9 failed steps!
> brew link berkeley-db
> brew link gdbm
> brew link perl
> brew link berkeley-db
> brew link gdbm
> brew link perl
> brew link berkeley-db
> brew link gdbm
> brew link perl
> ```

let's followup on the linux failures.

**Pull request merged**
