### PR TITLE
lzlib: revision bump to build on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
relates to #111560

### CODE REVIEW

**Comment by carlocab** [comment]
Not sure this is the right move here.

**Comment by iMichka** [comment]
I think this is how we handled it before. @danielnachun wrote on slack:

> As for the -fPIE/-fPIC, we’ve had mixed binaries up until this point with no issues, so I also think this is safe to rebottle.  The issue here is only relevant at compile time.

**Comment by carlocab** [comment]
Yes, we need to build new bottles, but I don't think we want the revision bump. This was discussed in one of @danielnachun's PRs here -- I just can't track the specific one down. See Homebrew/brew#13877.

**Comment by danielnachun** [comment]
No need for revision bumps as far as I can tell.  I guess what we are lacking here is a way to just rebottle and do dependent testing.  Could we just add some comment?  Even with the new tag, I feel like we should have a way to rebottle and test dependents in general as there will almost certainly be other situations where that will be needed.

**Comment by chenrui333** [comment]
what is the way of moving forward with this PR? Maybe we can just do a rebottle action trigger?

**Comment by danielnachun** [comment]
Given that we've now done dependent testing here with no issues, I think a rebottle is fine.

**Comment by chenrui333** [comment]
Doing the bottle step now.

**Comment by danielnachun** [comment]
I already saw this failing when I tried.  The problem seems to be that on some versions of macOS, the checksum is identical after the rebuild and throws an error.  I'm not sure if that's behavior we want to have the option to override but it's doesn't seem to be a bug.

**Pull request closed without merging**
