### PR TITLE
goose: fix brew style.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This should be a no-op but putting through CI to be sure.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Goose does not yet support vendoring. 0.7.0 does, but is still in release candidate stage (and has been for a year).

**Comment by MikeMcQuaid** [comment]
The options:
- hack around the rubocop failure
- make the rubocop check strict (which would be a shame for only one formula)
- leave it as-is to nudge its inclusion when this formula is updated

**Comment by Bo98** [comment]
If the formula is updated to 2.7.0 at some point (if a final version is ever released) then the entire install script can be simplified and the `dep` dependency can be removed. In fact, those changes will probably be done because it won't actually compile without making those changes rather than the audit itself.

The days of `dep` as a build dependency is numbered. Same with `godep`, which is now deprecated.

**Comment by MikeMcQuaid** [comment]
Cool, let's leave as-is.

**Pull request closed without merging**
