### PR TITLE
Deprecate :perl - part 2

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
For libgetdata, there is no extra cost to always build the bindings, no? I suggest we do that (and take care of the `:fortran` phase out as well): https://github.com/Homebrew/homebrew-core/pull/22774

**Comment by DomT4** [comment]
I'd prefer we change these to `depends_on "perl" => :optional` because otherwise there's no way to build `perl` bindings against the version of `perl` you may actually be using locally; they'll always be built against the system version, which due to the significant difference in version between system & Homebrew by this point, can lead to a wild lack of compatibility.

**Comment by ilovezfs** [comment]
I'm not sure I understand how this is different from anything else. We're using the system version where possible. What users do beyond that is up to them.

**Comment by ilovezfs** [comment]
@DomT4 if you think these are more useful as `depends_on "perl" => :optional` that sounds fine to me.

**Comment by ilovezfs** [comment]
@DomT4 
https://github.com/Homebrew/homebrew-core/commit/5cc680209449b5e9641bf6610ec0dfc3e712a01c
https://github.com/Homebrew/homebrew-core/commit/1ae3a675e935f59700e93eb5a4a8de94c698200e
https://github.com/Homebrew/homebrew-core/commit/6bd6321f64a4a0b33072f7e0ba89017fb332bba9

**Comment by DomT4** [comment]
> I'm not sure I understand how this is different from anything else. We're using the system version where possible.

The biggest difference is that almost universally bindings built against the system `python` work fine and can be found with either the system `python` or the brewed `python`. That's not the case with `perl`, generally speaking. There are exceptions, but not many.

```
~> perl -e "use Git"
$?
0

~> /usr/bin/perl -e "use Git"
Can't locate Git.pm in @INC (you may need to install the Git module) (@INC contains: <blah>)

~> /usr/bin/perl -e "use lib '/usr/local/lib/perl5/site_perl/5.26.1 '; use Git"
Can't locate Git.pm in @INC (you may need to install the Git module) (@INC contains: <blah>)
```
It only looks for bindings under the version of Perl running, so essentially if you have Homebrew's `perl` installed it's blind to all the bindings Homebrew is installing when those bindings are built against the system, at which point Homebrew's `perl` becomes an unhelpful paperweight 🙈.

**Comment by ilovezfs** [comment]
Note to self: don't use Perl.

**Comment by DomT4** [comment]
Yeah, I wouldn't strongly recommend it 😅.

**Pull request merged**
