### PR TITLE
flow-cli 0.17.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Not (yet) the latest release on GitHub. It's also not the version installed by their default installer:
```
❯ curl -s https://storage.googleapis.com/flow-cli/version.txt
v0.16.0
```
My impression is that this should change soon, but I'm often wrong about this.

**Comment by psiemens** [comment]
Hey @carlocab thanks for checking that! 

We just hit a bit of a snag getting our documentation site updated, so we haven't published this release yet. I'll tag you here when we create the GH release and are ready to update `flow-cli/version.txt`.

Once again, thanks! I had no idea y'all were checking these sorts of things -- super awesome to see 😄

**Comment by carlocab** [comment]
Yes, we try to make sure we only ship software that upstream intended. That would help a lot, @psiemens. Thanks.

**Comment by psiemens** [comment]
@chenrui333 @carlocab We've published the latest release: https://github.com/onflow/flow-cli/releases/tag/v0.17.0

Do you mind merging this PR now?

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks again, @psiemens.

**Pull request closed without merging**
