### PR TITLE
dopewars 1.6.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  libtool: install: /usr/bin/install -c dopewars /opt/homebrew/Cellar/dopewars/1.6.2/bin/dopewars
  /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-exec-hook
  chgrp: games: illegal group name
  chgrp: you are not a member of group wheel
  WARNING: Cannot change group of dopewars binary - the high
  score file may be unreadable or unwriteable by some users
  chmod 2755 /opt/homebrew/Cellar/dopewars/1.6.2/bin/dopewars
  chmod: Unable to change file mode on /opt/homebrew/Cellar/dopewars/1.6.2/bin/dopewars: Operation not permitted
```

**Comment by carlocab** [comment]
We should find out where that `chgrp` call is coming from and get rid of it.

**Comment by MikeMcQuaid** [comment]
@SMillerDev @carlocab @chenrui333 Can any of you reproduce this locally? If so, can you paste a `--debug` backtrace in here?

**Comment by SMillerDev** [comment]
Can't reproduce it on 12.5 unfortunately.

**Comment by carlocab** [comment]
Seems to be specific to `12.4` on M1.

**Comment by carlocab** [comment]
One of these may help:
```ruby
inreplace "src/Makefile.am", "2755", "755"
```
or
```ruby
inreplace "src/Makefile.am", "chmod 2755 ${DOPEBIN}", "chmod 2755 ${DOPEBIN} || true"
```
Can't test as I can't reproduce.

**Comment by Bo98** [comment]
I do not have an arm64 device to test on, but if someone does please send sandbox logs.

**Comment by Bo98** [comment]
If not, I could just hijack a CI machine in a bit and test there.

**Comment by carlocab** [comment]
> If not, I could just hijack a CI machine in a bit and test there.

Go ahead. It affects at least two PRs now.

**Comment by Bo98** [comment]
On the Intel runners we have the Homebrew installation set with permissions for `staff` rather than `admin`.

**Comment by chenrui333** [comment]
Looks like build/test runs fine on 12-arm machine locally now.

**Comment by Bo98** [comment]
It'll be based on the CI permissions. I could change the user permission setup during the next maintenance window (Monday). I would prefer if such change was backed up by a `brew doctor` check however.

**Comment by chenrui333** [comment]
> It'll be based on the user + group setup on the CI machines as per above. I could change the user permission setup during the next maintenance window (Monday). I would prefer if such change was backed up by a `brew doctor` check however.

Do you need me to provide anything?

**Comment by chenrui333** [comment]
Do we want to give this PR another try?

**Comment by chenrui333** [comment]
#117312

**Pull request closed without merging**
