### PR TITLE
mbedtls{,@2}: run `ctest`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

We run `make check` for other crypto libraries, so we should try to do the same here. (Hopefully, the tests pass.)

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like the same three tests fail in both versions. This will probably need to be reported upstream.

**Comment by SMillerDev** [comment]
Whenever you revisit this, can you add a comment to specify that we run this because it's a cryptography library? That wasn't really clear to me before.

**Comment by carlocab** [comment]
> Whenever you revisit this, can you add a comment to specify that we run this because it's a cryptography library? That wasn't really clear to me before.

I thought the formula description was enough, but a comment doesn't hurt. Added.

It seems the test failures were fixed by running things serially. I still intend to report the failure upstream, since they should probably support parallel test execution.

**Comment by carlocab** [comment]
Parallel testing issue reported at ARMmbed/mbedtls#4980.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
