### PR TITLE
dvm 0.7.0

### PR DESCRIPTION
**Pull request by carolynvs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carolynvs** [comment]
I'm not sure what's causing the build failure but after playing around locally, it looks like glide requires that the the root project contain a `.git` directory. Since the formula uses a compressed download from github, instead of a clone, I think that's why it's failing?

```
glide install
fatal: Not a git repository (or any of the parent directories): .git
```

Originally I was asked to make this formula not use a git tag + commit hash, and use a tar download instead. But it seems like that won't work with glide anymore? Let me know how you'd like me to fix this formula.

**Comment by carolynvs** [comment]
Found the problem. The homebrew build is now setting `MAKEFLAGS: -j4`, and the parallel targets aren't running in the correct order. I've updated the formula override that environment variable.

**Comment by ilovezfs** [comment]
It would be preferable to get it fixed (or at minimum reported) upstream so that parallelized builds work.

Also you should be able to use
```
  def install
    ENV.deparallelize
```
rather than passing the `-j1` yourself.

**Comment by carolynvs** [comment]
@ilovezfs  I've switched to `ENV.deparallelize` and have created an issue in dvm to update the Makefile https://github.com/getcarina/dvm/issues/151.

**Comment by ilovezfs** [comment]
Thanks! Please put the link into the formula with a note similar to https://github.com/Homebrew/homebrew-core/blob/master/Formula/xorriso.rb#L21-L25

**Comment by carolynvs** [comment]
I've added a note to the formula explaining why it's turned off with a link to the upstream issue.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Shipped! Thanks @carolynvs

**Pull request closed without merging**
