### PR TITLE
libepoxy 1.5.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tschoonj** [comment]
FYI, the following diff works fine for me (checked with `gtk+3`)

```diff
diff --git a/Formula/libepoxy.rb b/Formula/libepoxy.rb
index eb4fee770c..adf03f5c0e 100644
--- a/Formula/libepoxy.rb
+++ b/Formula/libepoxy.rb
@@ -1,9 +1,8 @@
 class Libepoxy < Formula
   desc "Library for handling OpenGL function pointer management"
   homepage "https://github.com/anholt/libepoxy"
-  url "https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.0.tar.xz"
-  sha256 "4c94995398a6ebf691600dda2e9685a0cac261414175c2adf4645cdfab42a5d5"
-  revision 1
+  url "https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.2.tar.xz"
+  sha256 "a9562386519eb3fd7f03209f279f697a8cba520d3c155d6e253c3e138beca7d8"
 
   bottle do
     cellar :any
@@ -76,13 +75,3 @@ index 3401075..031900f 100644
  epoxy_deps = [ dl_dep, ]
  if host_system == 'windows'
    epoxy_deps += [ opengl32_dep, gdi32_dep ]
-@@ -93,7 +88,7 @@ epoxy_has_wgl = build_wgl ? '1' : '0'
- # not needed when building Epoxy; we do want to add them to the generated
- # pkg-config file, for consumers of Epoxy
- gl_reqs = []
--if gl_dep.found()
-+if gl_dep.found() and host_system != 'darwin'
-   gl_reqs += 'gl'
- endif
- if build_egl and egl_dep.found()
-
```

**Comment by ilovezfs** [comment]
>FYI, the following diff works fine for me (checked with gtk+3)

The failure occurs during the test block not the build.

>what is the problem with this one?

```
inreplace "src/dispatch_common.c", '#define OPENGL_LIB "libOpenGL.so.0"', ""

```
That problem needs to be reported upstream and I haven't gotten to it yet.

**Comment by tschoonj** [comment]
Ok cool. By the way am seeing some implicit declaration warnings in the compilation of that test.

```
Testing libepoxy
/usr/bin/sandbox-exec -f /tmp/homebrew20180529-44951-1lvx86k.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libepoxy.rb -v
==> /usr/bin/clang test.c -L/usr/local/Cellar/libepoxy/1.5.2/lib -lepoxy -framework OpenGL -o test
test.c:12:5: warning: implicit declaration of function 'CGLChoosePixelFormat' is invalid in C99 [-Wimplicit-function-declaration]
    CGLChoosePixelFormat( attribs, &pix, &npix );
    ^
test.c:13:5: warning: implicit declaration of function 'CGLCreateContext' is invalid in C99 [-Wimplicit-function-declaration]
    CGLCreateContext(pix, (void*)0, &ctx);
    ^
test.c:16:5: warning: implicit declaration of function 'CGLReleasePixelFormat' is invalid in C99 [-Wimplicit-function-declaration]
    CGLReleasePixelFormat(pix);
    ^
test.c:17:5: warning: implicit declaration of function 'CGLReleaseContext' is invalid in C99 [-Wimplicit-function-declaration]
    CGLReleaseContext(pix);
    ^
4 warnings generated.
==> ls -lh test
-rwxr-xr-x  1 schoon  admin   8.6K May 29 12:36 test
==> file test
test: Mach-O 64-bit executable x86_64
==> ./test
Couldn't open libOpenGL.so.0: dlopen(libOpenGL.so.0, 5): image not found
Error: libepoxy: failed
Failed executing: ./test 
```

**Comment by ilovezfs** [comment]
>By the way am seeing some implicit declaration warnings in the compilation of that test.

Hmm... maybe the test needs a rewrite?

>Couldn't open libOpenGL.so.0: dlopen(libOpenGL.so.0, 5): image not found

Yup this is what the
```
inreplace "src/dispatch_common.c", '#define OPENGL_LIB "libOpenGL.so.0"', ""
```
fixes.

**Comment by ilovezfs** [comment]
Possibly related, yes. But that person's fork is missing the
```
#define OPENGL_LIB "/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL"
```
entirely

**Pull request closed without merging**
