### PR TITLE
duf 0.6.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Not (yet?) the latest release on GitHub.

**Comment by muesli** [comment]
It will become a proper release, and the git tag already points to the right commit. The only reason it's not "properly released" just yet, is an issue on the Snap store, that prevents me from publishing all the binaries/packages. :disappointed: 

This hopefully gets resolved this weekend.

**Comment by carlocab** [comment]
If you're happy for us to ship this as your latest stable release, I think we can go ahead and do that. Otherwise, we can wait until you sort out your Snap store issues. Please do try to update us on it if you can.

**Comment by muesli** [comment]
As this should be resolved soon, I'd suggest doing whatever means less work for you. If a bot picks up the new release automatically, we can just wait for that to happen.

**Comment by carlocab** [comment]
If you know for certain that `0.6.1` won't get re-tagged and the existing release tarball checksum won't change, then shipping this now would be less work. However, if there's a chance that one of the two above will happen, waiting a bit longer will be easier.

Waiting a bit is fine if you'd rather play it safe, as dealing with checksum mismatches can get quite inconvenient.

**Comment by muesli** [comment]
Just a heads up, duf 0.6.1 is now "properly" released on GitHub: https://github.com/muesli/duf/releases/tag/v0.6.1

**Comment by chenrui333** [comment]
Nice!!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
