### PR TITLE
gammu 1.37.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
`gettext` being `optional` here is a bit weird since `glib` which is `:recommended` has a mandatory dependency on `gettext`. Not your fault though.

👍

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
I'd be tempted to drop the dep entirely & let it filter through automatically depending on whether or not `glib` is used, but we seem to be moving away from that idea gradually. Maybe `:recommended`?

**Comment by ilovezfs** [comment]
no that idea is good. rage against the machine.

**Comment by ilovezfs** [comment]
@DomT4 voilà :smiling_imp: 
```
iMac-TMP:homebrew-core joe$ brew linkage gammu
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libcurl.4.dylib
  /usr/lib/libiconv.2.dylib
Homebrew libraries:
  /usr/local/Cellar/gammu/1.37.4/lib/libGammu.7.dylib (gammu)
  /usr/local/Cellar/gammu/1.37.4/lib/libgsmsd.7.dylib (gammu)
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
  /usr/local/opt/glib/lib/libglib-2.0.0.dylib (glib)
  /usr/local/opt/glib/lib/libgobject-2.0.0.dylib (glib)
Variable-referenced libraries:
  @loader_path/libGammu.7.dylib
Possible undeclared dependencies:
  gettext
```

**Comment by DomT4** [comment]
👍 🎉

**Pull request closed without merging**
