### PR TITLE
add : adding gno formula

### PR DESCRIPTION
**Pull request by faanrm**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by faanrm — COMMENTED** [review]
remove some unused function

**Comment by faanrm** [comment]
remove unused function in Formula/g/gno

**Comment by p-linnane** [comment]
Hi. Thanks for the PR. Unfortunately, this software doesn't meet our notability requirements, as the repo only has 2 stars. Additionally, we do not allow authors to submit their own work. This information can be found here: https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff.

**Comment by faanrm** [comment]
hello p-linnane thanks for feedback , but if author can't publish , how can the packag can be published ? thanks

**Comment by p-linnane** [comment]
The intent is that the software has enough users where one of them would be interested enough to submit it.

**Pull request closed without merging**
