### PR TITLE
cargo-completion: delete

### PR DESCRIPTION
**Pull request by gromgit**
Made redundant by #57029, installing alongside `rust` causes link failure, and no formulas depend on it.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
Considering that it's still seeing an average of about 10 installs/day, it may be worth adding a note about it [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/missing_formula.rb) (we already have a note there for `cargo` itself).

**Comment by chenrui333** [comment]
Do we also need tap_migration update too? I just filed a PR to specify the missing formula in the brew side.

**Comment by Bo98** [comment]
> Do we also need tap_migration update too?

No because it isn't migrating to another tap.

**Comment by jonchang** [comment]
This could wait on the new `brew` release to ensure users will see the migration message.

**Review by Bo98 — APPROVED** [review]
2.4.4 is out.

**Comment by Lekensteyn** [comment]
FWIW, I have `cargo-completion` installed but not `rust` because I use rustup to install an appropriate toolchain.
It looks like `~/.rustup/toolchains/stable-x86_64-apple-darwin/etc/bash_completion.d/cargo` provides the same completion file though.

**Comment by Bo98** [comment]
I reckon with completions it's best to take it from the installation to ensure the versions match, so that cargo 0.45 completions aren't used with a cargo 0.40 installation.

A separate completion package isn't exactly common to have in a package manager.

**Pull request merged**
