### PR TITLE
Add missing conflicts

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR adds missing conflicts to make all conflicts symmetric

### CODE REVIEW

**Comment by bayandin** [comment]
Oh, that's interesting
```
22:42:06 ==> brew test kafka --verbose
22:43:07 ==> FAILED
22:43:07 Testing kafka
22:43:07 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200405-32214-igyggz.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kafka.rb --verbose
22:43:07 ==> /usr/local/Cellar/kafka/2.4.1/bin/kafka-topics --zookeeper localhost:2181 --create --if-not-exists --replication-factor 1 --partitions 1 --topic test > /private/tmp/kafka-test-20200405-32215-1mch2m5/kafka/demo.out 2>/dev/null
22:43:07 ==> /usr/local/Cellar/kafka/2.4.1/bin/kafka-console-producer --broker-list localhost:9092 --topic test 2>/dev/null
22:43:07 ==> /usr/local/Cellar/kafka/2.4.1/bin/kafka-console-consumer --bootstrap-server localhost:9092 --topic test --from-beginning --max-messages 1 >> /private/tmp/kafka-test-20200405-32215-1mch2m5/kafka/demo.out 2>/dev/null
22:43:07 ==> /usr/local/Cellar/kafka/2.4.1/bin/kafka-topics --zookeeper localhost:2181 --delete --topic test >> /private/tmp/kafka-test-20200405-32215-1mch2m5/kafka/demo.out 2>/dev/null
22:43:07 ==> /usr/local/Cellar/kafka/2.4.1/bin/kafka-server-stop
22:43:07 dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
22:43:07   Referenced from: /usr/local/bin/awk
22:43:07   Reason: image not found
22:43:07 No kafka server to stop
```

**Comment by Bo98** [comment]
That'll be because the test bot code is not expecting `gawk` to be used but it is by regular `awk` operations. `gawk` should probably be `keg_only :provided_by_macos`.

**Comment by Bo98** [comment]
Or handled like `coreutils` where it is a installed as `gawk`.

**Comment by bayandin** [comment]
I've removed `gawk` from this PR and will handle it separately. 
Also it, probably, requires to mark `awk` as `keg_only :provided_by_macos` and check dependant formulae

**Comment by bayandin** [comment]
- `brew audit serveit --online`:
```
Stacktrace
        Error: 1 problem in 1 formula detected
serveit:
  * 'revision 1' should be removed
```

Not sure why do we get this error, probably because we have both `bottle :unneeded` and `revision 1` in the formula.

 
We're good to go right after the next release of homebrew. 
Since changes affect tests only it could be merged via GitHub UI (Rebase and merge).

**Comment by Bo98** [comment]
The serveit audit is because the last update didn't remove the `revision 1` line: #37835. I don't know how that got a green tick in the CI.

**Comment by bayandin** [comment]
> The serveit audit (from #52593 - not this one) is because the last update didn't remove the `revision 1` line: #37835. I don't know how that got a green tick in the CI.

Whoops, messed up with several open PR on several open browser tabs

**Pull request merged**
