### PR TITLE
mmseqs2 11-e1a1c

### PR DESCRIPTION
**Pull request by milot-mirdita**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by milot-mirdita** [comment]
We removed the dependency on GCC and use the same method as `lightgbm` uses to get libomp working. I copied their solution and it seems to work fine. I also added a `head` section since quite a few recipes seem to have it (again).

**Comment by bayandin** [comment]
@BrewTestBot test this please

**Comment by milot-mirdita** [comment]
Should I add the relevant `if OS.mac?` calls to fix the Linuxbrew build?

I noticed that no formulae in homebrew-core use that. Linuxbrew should not add the libomp dependency or the libomp string to cmake.

**Comment by SMillerDev** [comment]
No, that's up to linuxbrew to decide

**Comment by milot-mirdita** [comment]
Thanks, then everything is good to go.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @milot-mirdita! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
