### PR TITLE
ns-3 3.37

### PR DESCRIPTION
**Pull request by ryenus**
Update formula **ns-3** to use python@3.11 instead of python@3.10, see the related pr https://github.com/Homebrew/homebrew-core/pull/114154

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11/object.h:136:30: error: lvalue required as left operand of assignment
    136 | #  define Py_TYPE(ob) Py_TYPE(_PyObject_CAST(ob))
        |                       ~~~~~~~^~~~~~~~~~~~~~~~~~~~
  /tmp/ns-3-20221226-13121-7zel4b/ns-3-dev-ns-3.36.1/build/src/core/bindings/ns3module.cc:51869:5: note: in expansion of macro ‘Py_TYPE’
  51869 |     Py_TYPE(&PyNs3Length_Type) = &PyNs3LengthMeta_Type;
        |     ^~~~~~~
  /home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11/object.h:136:30: error: lvalue required as left operand of assignment
    136 | #  define Py_TYPE(ob) Py_TYPE(_PyObject_CAST(ob))
        |                       ~~~~~~~^~~~~~~~~~~~~~~~~~~~
  /tmp/ns-3-20221226-13121-7zel4b/ns-3-dev-ns-3.36.1/build/src/core/bindings/ns3module.cc:52056:5: note: in expansion of macro ‘Py_TYPE’
  52056 |     Py_TYPE(&PyNs3Int64x64_t_Type) = &PyNs3Int64x64_tMeta_Type;
        |     ^~~~~~~
  /home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11/object.h:136:30: error: lvalue required as left operand of assignment
    136 | #  define Py_TYPE(ob) Py_TYPE(_PyObject_CAST(ob))
        |                       ~~~~~~~^~~~~~~~~~~~~~~~~~~~
  /tmp/ns-3-20221226-13121-7zel4b/ns-3-dev-ns-3.36.1/build/src/core/bindings/ns3module.cc:52478:5: note: in expansion of macro ‘Py_TYPE’
  52478 |     Py_TYPE(&PyNs3NormalRandomVariable_Type) = &PyNs3NormalRandomVariableMeta_Type;
        |     ^~~~~~~
```

**Comment by iMichka** [comment]
Let's try to update to the latest version. They changed from `pybindgen` to `cppyy`.

**Comment by iMichka** [comment]
I removed the Python bindings, as I was not able to get them to build.

From the docs:
https://www.nsnam.org/docs/manual/html/python.html#introduction

> It is also important to note that the current capability is provided on a lightly maintained basis and not officially supported by the project (in other words, we are currently looking for a Python bindings maintainer). The Cppyy framework could be replaced if it becomes too burdensome to maintain as we are presently doing.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> I removed the Python bindings, as I was not able to get them to build.
> 
> From the docs: https://www.nsnam.org/docs/manual/html/python.html#introduction
> 
> > It is also important to note that the current capability is provided on a lightly maintained basis and not officially supported by the project (in other words, we are currently looking for a Python bindings maintainer). The Cppyy framework could be replaced if it becomes too burdensome to maintain as we are presently doing.

I logged an issue on their side about the decision we made in here, https://gitlab.com/nsnam/ns-3-dev/-/issues/833 :)

**Pull request closed without merging**
