### PR TITLE
use secure urls and other minor fixes #7

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by vszakats** [comment]
* I've seen a number of these while running audits, too:
```
Please set plist_options when using a formula-defined plist
```
* Plus failure to test against two different PHP versions.

**Comment by apjanke** [comment]
The `plist_options` audit failure is a new audit check we added recently. You can ignore it in these.

**Comment by apjanke** [comment]
And the failure to test under a couple different PHP versions is due to a bug in `brew test-bot`'s handling of dependency conflicts. That can probably be ignored as well.

**Comment by vszakats** [comment]
Thank you @apjanke!

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Comment by xu-cheng** [comment]
@apjanke just for future reference, we should probably avoid pulling new bottles for style change PR like this.

**Comment by apjanke** [comment]
You're right; I'll leave the `--bottle` off the remaining pulls for these.

**Pull request closed without merging**
