### PR TITLE
updating doctl to 1.5.0

### PR DESCRIPTION
**Pull request by bryanl**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by bryanl** [comment]
Is this a merge conflict? I don't see it on my side.

**Comment by MikeMcQuaid** [comment]
Yes. Rebase commits by running `brew update; git checkout $YOUR_BRANCH; git rebase origin/master` and then fix all merge conflicts then `git push --force-with-lease`. Thanks!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@bryanl thanks for your contribution to Homebrew and taking the time to resolve the conflict!

**Pull request closed without merging**
