### PR TITLE
pcre2 10.38

### PR DESCRIPTION
**Pull request by carenas**
Signed-off-by: Carlo Marcelo Arenas Belón <carenas@gmail.com>

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
`qt` failure on Linux is from #85898 and not due to the version bump. For some reason, CI skipped testing Qt on Linux. Is that intentional? CC @dawidd6

This is the [`test-bot` command](https://github.com/Homebrew/homebrew-core/pull/85898/checks?check_run_id=3816733957#step:10:2) for dependents on Linux:

```
  if [ "$RUNNER_OS" = 'macOS' ]; then
    cd bottles
    brew test-bot --only-formulae-dependents --junit --testing-formulae=llvm@12,castxml,ccls,clazy,enzyme,faust,halide,include-what-you-use,ispc,julia,klee,ldc,llvm,spirv-llvm-translator,v8 --skipped-or-failed-formulae=llvm,castxml,ccls,clazy,enzyme,faust,halide,ispc,julia,klee,ldc,spirv-llvm-translator,v8
  else
    docker exec ee9abf970359e8182ac77055ca52e089c2fa16cf brew test-bot --only-formulae-dependents --junit --testing-formulae=llvm@12,castxml,ccls,clazy,enzyme,faust,halide,include-what-you-use,ispc,julia,klee,ldc,llvm,spirv-llvm-translator,v8 --skipped-or-failed-formulae=llvm,castxml,ccls,clazy,enzyme,faust,halide,ispc,julia,klee,ldc,spirv-llvm-translator,v8
  fi
```

Notice, in particular, the `--skipped-or-failed-formulae` argument, which includes most formulae being tested. For comparison, [this](https://github.com/Homebrew/homebrew-core/pull/85898/checks?check_run_id=3816733706#step:10:2) is what it looks like on Intel Big Sur:
```
  if [ "$RUNNER_OS" = 'macOS' ]; then
    cd bottles
    brew test-bot --only-formulae-dependents --junit --testing-formulae=llvm@12,castxml,ccls,clazy,enzyme,faust,halide,include-what-you-use,ispc,julia,klee,ldc,llvm,spirv-llvm-translator,v8 --skipped-or-failed-formulae=
  else
    docker exec ee9abf970359e8182ac77055ca52e089c2fa16cf brew test-bot --only-formulae-dependents --junit --testing-formulae=llvm@12,castxml,ccls,clazy,enzyme,faust,halide,include-what-you-use,ispc,julia,klee,ldc,llvm,spirv-llvm-translator,v8 --skipped-or-failed-formulae=
  fi
```
The `--skipped-or-failed` flag has no arguments here.

There are formulae passed to `--skipped-or-failed` on [ARM macOS](https://github.com/Homebrew/homebrew-core/pull/85898/checks?check_run_id=3816733621#step:10:4), but those are just formulae with no ARM bottles.

The list of skipped formulae is from `steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae` and used here:

https://github.com/Homebrew/homebrew-core/blob/cfc698d7f13f8d9c5607a524a7e191725cb66ded/.github/workflows/tests.yml#L251-L259

The list appears to be generated here

https://github.com/Homebrew/homebrew-core/blob/cfc698d7f13f8d9c5607a524a7e191725cb66ded/.github/workflows/tests.yml#L229-L238

but I'm not sure how. I'll probably have to poke at `test-bot`.

**Review by carlocab — APPROVED** [review]
Thanks, @carenas!

**Comment by carlocab** [comment]
Huh, I see. That's why `llvm@12` was tested (built with GCC 5) but not `llvm`.

> It "skips" a formula but also not really.

Not sure what you mean here. To me it seems like many formulae were really skipped. e.g. all dependents of `llvm` that weren't modified in the PR were skipped. That means I missed probably more than a few revision bumps that I also needed to do.

**Comment by Bo98** [comment]
I almost feel like just deleting `install_gcc_if_needed` entirely, but there's probably a couple formulae which depend on it.

A quick fix might be to move it after dependencies are installed (and make the skip a hard error).

**Comment by Bo98** [comment]
yeah I think it should be hard failing instead

**Pull request closed without merging**
