### PR TITLE
audacious 4.3

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Review by ZhongRuoyu — DISMISSED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by radioactiveman** [comment]
@chenrui333: Thanks for maintaining Audacious for Homebrew. As Audacious developer, I have these minor suggestions:

1. Use the [official description](https://github.com/audacious-media-player): "[A] lightweight and versatile audio player", the current one refers to GTK but the actual Homebrew build uses Qt only.
2. Add `opusfile` as dependency to enable the native Opus decoder plugin, introduced with Audacious 4.3.
3. You may use Qt 6 instead of 5 which can be enabled for Meson with "-D qt6=true".

**Comment by ZhongRuoyu** [comment]
@radioactiveman Please see #126717.

**Comment by radioactiveman** [comment]
> @radioactiveman Please see #126717.

LGTM, thanks for the fast response. :)

**Comment by ZhongRuoyu** [comment]
And thanks for your suggestions, @radioactiveman!

**Pull request closed without merging**
