### PR TITLE
orc-tools 1.7.1

### PR DESCRIPTION
**Pull request by williamhyun**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
This is not (yet) the latest release: https://orc.apache.org/docs/releases.html

**Comment by dongjoon-hyun** [comment]
Hi, @Moisan . Please refresh your browser. It's released.
- http://orc.apache.org/news/2021/11/07/ORC-1.7.1/

**Review by dongjoon-hyun — COMMENTED** [review]
BTW, thank you for your swift update, @williamhyun .

To @Moisan , I'm the VP of Apache ORC project and @williamhyun is the PMC member of Apache ORC project. This is a valid Apache ORC artifact.

**Review by branchv — APPROVED** [review]
thank you @williamhyun, and @dongjoon-hyun for confirming it's the latest release!

**Comment by dongjoon-hyun** [comment]
Thank you so much, @branchvincent .

**Pull request closed without merging**
