### PR TITLE
imageoptim-cli 3.1.7

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
actually, let's see if we can build for arm this time as well. (seems working in my local)

**Comment by p-linnane** [comment]
No luck.
```
  imageoptim-cli
    * Binaries built for a non-native architecture were installed into imageoptim-cli's prefix.
      The offending files are:
        /opt/homebrew/Cellar/imageoptim-cli/3.1.7/libexec/lib/node_modules/imageoptim-cli/dist/imageoptim	(x86_64)
```

**Comment by JamieMason** [comment]
Hi @p-linnane @chenrui333
Maybe you can help me as I'm not sure what I need to do. I built version 3.1.7 with https://github.com/vercel/pkg using `node18-macos-x64`. There is also `node18-macos-arm64` but I chose `x64` because:

> macOS: possible to build x64 on arm64 with Rosetta 2 but not opposite.
> – https://github.com/vercel/pkg#targets

I could use the `arm64` option if we think that will fix this issue, but will that work on non `arm64` macs?

**Comment by chenrui333** [comment]
@JamieMason you can read the thread #98451 cc @cho-m

**Comment by chenrui333** [comment]
For now, we are just going to proceed with the merge, the arm build can be addressed separately.

**Pull request merged**
