### PR TITLE
llvm: add mlir

### PR DESCRIPTION
**Pull request by carlocab**
There's been some interest in the flang compiler for llvm:

https://github.com/Homebrew/discussions/discussions/143
https://github.com/Homebrew/homebrew-core/pull/63081

It seems possible to build flang separately from llvm, but it appears to
require having built mlir. See the flang [README](https://github.com/llvm/llvm-project/blob/master/flang/README.md). Aside from being a 
pre-requisite for flang, mlir is a mature project with [a number of
interesting applications](https://mlir.llvm.org/users/). 

mlir, therefore, seems worthy of inclusion in the llvm formula even if
flang is currently not suitable for homebrew/core. (flang does build
and test successfully upon declaring a dependency on llvm in this PR.)

Test failure appears to be [unrelated to the PR](https://github.com/Homebrew/homebrew-core/pull/65223#issuecomment-733654271), and has been reported
upstream: https://github.com/odin-lang/Odin/issues/792

---

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
I can get this to build locally when the only llvm project to be built is mlir, but that also duplicates a bunch of binaries already built for the llvm keg. Will see if there's some other way to fix this...

**Comment by carlocab** [comment]
Potential workaround: https://github.com/Homebrew/homebrew-core/pull/65226#issuecomment-730731128

But I still need to figure out how to avoid producing a bunch of duplicate binaries.

**Comment by carlocab** [comment]
This is the error in the log:
```sh
❯ cat test.01.odin
2020-11-25 05:22:08 +0000

/usr/local/Cellar/odin/0.13.0/bin/odin
build
hellope.odin

ld: library not found for -lc
```
Not really sure what's going on here, and why this error doesn't show up in 10.14 and 10.15.

**Comment by fxcoudert** [comment]
Not sure I understand why calling make through cmake works when calling make directly doesn't, but I don't think it can hurt. (Using ninja, on the other hand, has in the past lead to a huge increase in our binary size, so we don't want that)

**Comment by carlocab** [comment]
Yup, I really don't get it either. Who knows what's inside llvm's build scripts...

I experimented building with Ninja too, and it's not as bad as it used to be (~3GB install), but still worse than just Make.

Thanks!

**Pull request closed without merging**
