### PR TITLE
googler 2.7

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
Since 2.7 you need to run `make disable-self-upgrade` before `make install` to disable the in-place self-upgrade mechanism (which is mainly intended for users installing googler without a package manager). See https://github.com/jarun/googler#tips-for-packagers.

Disclosure: I'm a co-maintainer and I wrote the self-upgrade mechanism of googler.

**Comment by ilovezfs** [comment]
@zmwangx fixed!

**Comment by zmwangx** [comment]
Sorry, there's a subtle difference between the `-i` options of GNU and BSD sed which I didn't realize, which is causing the failure here. Could you please apply the patch https://github.com/jarun/googler/commit/6152bd3.patch (merged)?

**Comment by ilovezfs** [comment]
@zmwangx done. In the future when posting patch urls, I typically like to use 8 characters not 7 :)

**Comment by zmwangx** [comment]
Sure.

**Comment by ilovezfs** [comment]
@zmwangx I guess 7 is actually better, but I just had noticed a proliferation 8s around here. Ignore me. I'll do 7 from now on!

**Comment by ilovezfs** [comment]
@zmwangx :ship:'d. thx for the assist

**Pull request closed without merging**
