### PR TITLE
icu4c 65.1

### PR DESCRIPTION
**Pull request by fxcoudert**
Let's go ⏱

### CODE REVIEW

**Comment by fxcoudert** [comment]
A few more revision bumps:

```
Applying: node@12: revision for icu4c
Applying: php: revision for icu4c
Applying: php@7.2: revision for icu4c
Applying: php@7.3: revision for icu4c
Applying: postgresql@10: revision for icu4c
Applying: postgresql@11: revision for icu4c
Applying: urweb: revision for icu4c
```

**Comment by fxcoudert** [comment]
-  `chakra` build failure should be fixed by https://github.com/microsoft/ChakraCore/commit/20b819a5a7ff09577a61582059259f67729cde0c (or shipping a newer version)
- `freeling` fails to build with:

```
09:47:57 Undefined symbols for architecture x86_64:
09:47:57   "boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)", referenced from:
09:47:57       boost::filesystem::directory_iterator::directory_iterator(boost::filesystem::path const&) in build-dict.cc.o
```

**Comment by SMillerDev** [comment]
Was the freeling error reported upstream? I see some "fix macOS" commits in their history. Other than that I think this is ready for a rebase/rebuild

**Comment by fxcoudert** [comment]
- `mapnik` has not been fixed
- `freeling` issue is Boost, I think, not macOS-specific. I will report it.

I don't really see the point in rebasing (and having CI take another 2 days) given two of the formulas don't even build.

**Comment by SMillerDev** [comment]
I thought mapnik was fixed which would make the rebase "ready to merge" my bad

**Comment by fxcoudert** [comment]
I've tried to apply the mapnik master patches to 3.0.22 sources, but it fails. If `mapnik` continues to hold updates for a long time, because they do not fix issues, it may become time to remove it from Homebrew. It has many users, sadly, but nothing depends on it.

**Comment by fxcoudert** [comment]
Mapnik fix in https://github.com/Homebrew/homebrew-core/pull/49355

**Comment by Bo98** [comment]
Does the `freeling` thing still happen? I cannot reproduce locally.

Not sure what's up with mapnik 3.0.23 (#50582) but I'll have a look this weekend.

**Comment by Bo98** [comment]
Ok, the `freeling` thing happens if Homebrew's Boost is installed. It's because it gets mixed up between the libraries built from the Boost `resource` and the ones available globally. Not entirely sure why Boost is built from a resource here since there's no comment explaining why.

**Comment by iMichka** [comment]
Probably because of this: https://github.com/Homebrew/homebrew-core/pull/16737

**Comment by Bo98** [comment]
I suppose it could make the disk space usage less (_if_ the user doesn't already have Boost installed). Though it's the only formula in homebrew-core that vendors Boost for that reason.

**Comment by Bo98** [comment]
Read that wrong at first. Is it just to avoid using options? If that's the case then it doesn't apply anymore.

**Comment by samford** [comment]
Just a heads up, [the newest version is now 66.1](http://site.icu-project.org/download/66) (as of 2020/03/11).

**Comment by iMichka** [comment]
Superseded by #52481

**Pull request closed without merging**
