### PR TITLE
openvpn: enable pkcs11

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @DomT4 @BekoBou @nobecutan

### CODE REVIEW

**Comment by DomT4** [comment]
Seems rather a full-on solution IMO but if you're happier this way, 👍.

**Comment by ilovezfs** [comment]
As long as there's no reason someone would want openvpn specifically built without pkcs11, I don't see much downside here.

**Comment by DomT4** [comment]
I'm just unsure long-term how this is a better solution than allowing custom options, on the assumption this becomes a model for other formulae to follow, but that's what was decided around custom options, so I guess it is what it is.

Not that I thought custom options were ideal either but I'm forever dubious of people remembering to update embedded resources in a timely fashion as/when necessary.

**Comment by ilovezfs** [comment]
My interest here is to avoid having people move currently default `depends_on "foo" => "with-bar"` (especially in a certain tap which shall remain nameless) behind options to escape the audit.

**Comment by DomT4** [comment]
I think it's fine in this specific case; I just worry beyond this about it becoming a norm in formula until we reach a point where resource dependencies being way out of sync with the formula dependencies they replaced is the "solution".

**Comment by ilovezfs** [comment]
If it gets out of control, start making some sort of unpleasant sound.

**Comment by ilovezfs** [comment]
:motor_boat:

**Comment by BekoBou** [comment]
Awesome!

**Pull request closed without merging**
