### PR TITLE
composer: update checksum

### PR DESCRIPTION
**Pull request by codehexes**
Updated SHA256 to match current

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why did the hash change?

**Comment by codehexes** [comment]
Looks like it was incorrect to begin with: https://getcomposer.org/download/ shows this hash in the release table

**Comment by SMillerDev** [comment]
If I was a malicious actor I'd change the hash in the download table too. We clearly downloaded it with the current hash and that isn't the same as it currently is. This needs to be checked with upstream.

**Comment by codehexes** [comment]
Fair enough.  I also verified with the download from Github releases and the hash also matches.

**Comment by Seldaek** [comment]
Composer maintainer here, you can indeed find the explanation on https://github.com/composer/composer/issues/9746#issuecomment-793984249 - this is a valid hash change but was probably a mistake, I didn't realize this would have such an impact here, sorry for the trouble.

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
