### PR TITLE
v8: add head

### PR DESCRIPTION
**Pull request by jeroen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I need this to test my bindings against the master branch. Thanks!!

### CODE REVIEW

**Comment by chrmoritz** [comment]
I'm unfortunately not sure if we can provide a stable ´HEAD´ option for the `v8` formula, because `v8` master might require different version of dependencies we've put into the resources as specified in their `DEPS` file.

It might work at the moment, but there are no guarantees that `v8` master will always be buildable with the dependencies version of the stable branch.

**Comment by SMillerDev** [comment]
While a v8canary might be good I don't see any harm in allowing head builds. Those aren't supported anyway.

**Comment by chrmoritz** [comment]
@SMillerDev Sure we could go for it, if we're fine that the unsupported head build is broken from time to time. I just wanted to point out the the head build would pull the `v8` sources from their master branch, but still use not the correct dependency version for it (to old and maybe incompatible, because they are for stable and not canary). However I don't think that would be fixable here, because that would require parsing their `DEPS` file.

**Comment by jeroen** [comment]
It's expected that HEAD doesn't always work, that's exactly what we would want to test HEAD. 

By definition, git/svn trunk will break a formula from time to time, whenever upstream makes a change that affects the build (change a dependency, change a configure parameter, change code that breaks some patch, etc). I don't think this is a special case.

**Comment by chrmoritz** [comment]
Sure, I agree with that. However I've still the feeling that we don't even try to keep the head build working this way, because we don't use the upstream designated versions of the dependencies for it. For example every major `icu` update has the chance to break head builds until the `icu` upgrade lands in stable and we upgrade the resource for it. Though parsing the `DEPS` file in formula logic would be to much and I don't think there's another solution for it.

**Comment by fxcoudert** [comment]
It seems that it's too much of a moving target, really. Closing.

**Pull request closed without merging**
