### PR TITLE
openjdk@21 21.0.3

### PR DESCRIPTION
**Pull request by ryenus**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by ryenus** [comment]
For now the resource has openjdk `21.0.1` as boot jdk, should we update it to `21.0.2`?

And should we update the [autobump list][1] to include `openjdk@21` since [openjdk 21 is also LTS][2]?

[1]: https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt#L1696-L1699
[2]: https://openjdk.org/projects/jdk/21/

**Comment by chenrui333** [comment]
> For now the resource has openjdk `21.0.1` as boot jdk, should we update it to `21.0.2`?
> 
> And should we update the [autobump list](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt#L1696-L1699) to include `openjdk@21` since [openjdk 21 is also LTS](https://openjdk.org/projects/jdk/21/)?

we should do both

**Comment by calvinit** [comment]
I think the `openjdk` formula should point to the latest LTS version (currently 21.0.3) and be an alias to the formula with the specified major version (currently `openjdk@21`), instead of pointing to the latest non-LTS version 22.

My reasons are as follows:

1. Non-LTS major versions are updated every 6 months, while LTS major versions are updated every 2 years (you can refer to the update schedule [here](https://www.java.com/releases/)). If it points to a non-LTS version, it means we have to repeat operations similar to [this PR](https://github.com/Homebrew/homebrew-core/pull/168294) every 6 months (adding a new major version formula pointing to the previous version, pointing the `openjdk` formula to the latest LTS/non-LTS version, modifying the dependency lists of all formulas that depend on the `openjdk` formula, and rebuilding and requesting bottles). This operation usually takes a considerable amount of time, which leads to the problem mentioned in reason 2 below;

2. Operations similar to [this PR](https://github.com/Homebrew/homebrew-core/pull/168294), if they take a long time, might encounter a situation where a new minor version is released during [the PR](https://github.com/Homebrew/homebrew-core/pull/168294) review period (for example, when creating [this PR](https://github.com/Homebrew/homebrew-core/pull/168294), the latest minor version of `openjdk@21` was 21.0.2, but before [this PR](https://github.com/Homebrew/homebrew-core/pull/168294) was merged, it updated to 21.0.3 and already requested a bottle update). So, when [this PR](https://github.com/Homebrew/homebrew-core/pull/168294) is merged, it results in a "version rollback" situation. Specifically here, it means the latest minor version of 21 LTS rolled back to 21.0.2, requiring a new PR commit to update this bottle;

3. Generally, developers tend to use LTS versions more for stability.

Therefore, can we make the following changes?

1. Create one formula for each active LTS major version, i.e., one each for `openjdk@8`, `openjdk@11`, `openjdk@17`, and `openjdk@21`;

2. The `openjdk` formula points to the latest LTS major version, which is currently `openjdk@21`, similar to alias, symbolic link, or hard link in operating systems;

3. Formulas dependent on `openjdk` should explicitly use the one with the major version number, such as `openjdk@21`, instead of `openjdk`, to avoid large-scale impact on those dependent formulas when changing `openjdk`;

4. For those with non-LTS version needs, they can create corresponding non-LTS major version formulas themselves, such as `openjdk@22` currently, and `openjdk@23` in the future, etc.;

5. Add each active LTS major version formula (`openjdk@8`, `openjdk@11`, `openjdk@17`, and `openjdk@21`) as well as the `openjdk` formula to the [autobump list](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt#L1696-L1699).

@chenrui333 @ZhongRuoyu @SMillerDev

**Comment by chenrui333** [comment]
right now, openjdk is openjdk22, and we have alias for each lts version.

**Comment by ryenus** [comment]
> I think the `openjdk` formula should point to the latest LTS version (currently 21.0.3) and be an alias to the formula with the specified major version (currently `openjdk@21`), instead of pointing to the latest non-LTS version 22.

Not a decision maker but I like this idea, so :+1:

**Comment by SMillerDev** [comment]
> Generally, developers tend to use LTS versions more for stability.

I know Java devs like to stay on old and safe versions. But for Homebrew, an install without a specific version means "the latest version" and not "the latest version that upstream will support longer than some other version". If we change that only for OpenJDK it would become very messy.

---

> Create one formula for each active LTS major version, i.e., one each for openjdk@8, openjdk@11, openjdk@17, and openjdk@21;

We have this

> The openjdk formula points to the latest LTS major version, which is currently openjdk@21, similar to alias, symbolic link, or hard link in operating systems;

No, since it would be the only formula that works that way in Homebrew.

> Formulas dependent on openjdk should explicitly use the one with the major version number, such as openjdk@21, instead of openjdk, to avoid large-scale impact on those dependent formulas when changing openjdk;

That's counter to the formula requirement that Homebrew formulae should always use the latest working version of their dependencies.

> For those with non-LTS version needs, they can create corresponding non-LTS major version formulas themselves, such as openjdk@22 currently, and openjdk@23 in the future, etc.;

Or they can install `openjdk` and rely on it updating whenever upstream does, just like evey other formula.

> Add each active LTS major version formula (openjdk@8, openjdk@11, openjdk@17, and openjdk@21) as well as the openjdk formula to the [autobump list](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt?rgh-link-date=2024-06-06T03%3A45%3A08Z#L1696-L1699).

That's fine, please make a pull request for that.

---

We were unlucky with this last release since it upgraded from non-LTS to LTS, broke some formula, came at the same time as a major XCode linker update and was delayed by some Homebrew CI changes. These things don't happen all that often and definitely don't happen all that often in the same timespan. Java updates will always be difficult because developers rarely test with modern Java versions, but it is unlikely to be _this_ difficult anywhere in the near future.

**Comment by ZhongRuoyu** [comment]
Agreed with @SMillerDev. Just adding an additional note:

> Formulas dependent on openjdk should explicitly use the one with the major version number, such as openjdk@21, instead of openjdk, to avoid large-scale impact on those dependent formulas when changing openjdk

We could probably have done better in the recently-merged OpenJDK 22 update; we could have created a new `openjdk@21` first and start migrating incompatible formulae in separate PRs, similar to how LLVM 18 was handled recently (#169255). (I once thought it wasn't possible to have `openjdk` 21 and `openjdk@21` 21 at the same time, but I was wrong.)

One of the reasons why we build and test all dependents (https://github.com/Homebrew/homebrew-core/labels/CI-build-dependents-from-source) when bumping `openjdk` to a new major version is to make sure they really work. Normally, we point a formula to a versioned runtime only if it doesn't work with the latest (and this applies to other programming language runtimes as well). By switching a versioned OpenJDK, a formula effectively gets less attention (if at all) on compatibility updates, which means it may not switch to a newer major version even when a later update makes them compatible. That also brings troubles when we deprecate an EOL version.

Nevertheless, I appreciate your thoughtful suggestion, @calvinit.

**Review by chenrui333 — APPROVED** [review]

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by calvinit** [comment]
Thank you all, I got it.

**Pull request merged**
