### PR TITLE
gnome-latex 3.44.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by p-linnane** [comment]
Depends on https://github.com/Homebrew/homebrew-core/pull/119588.

**Comment by chenrui333** [comment]
> Depends on #119588.

maybe just merge this change into that PR instead of rev bump?

**Comment by p-linnane** [comment]
Yeah that's a good idea. Not working with the rev bump anyway.

**Comment by p-linnane** [comment]
Cherry picked into https://github.com/Homebrew/homebrew-core/pull/119588.

**Pull request closed without merging**
