### PR TITLE
dolt 0.22.3

### PR DESCRIPTION
**Pull request by oscarbatori**

### CODE REVIEW

**Comment by chenrui333** [comment]
@oscarbatori can you update the commit message as `formula version` format?

**Comment by oscarbatori** [comment]
Next release of thats alright? 

It's auto generated, don't want to cut another commit

**Comment by fxcoudert** [comment]
@oscarbatori please see my comment at https://github.com/Homebrew/homebrew-core/pull/66061#issuecomment-737499431

We'll merge with the next release, there was one merged 9 hours ago.

**Comment by oscarbatori** [comment]
@fxcoudert our bug fix is not included in a primary distribution channel? That's... pretty frustrating.

**Pull request closed without merging**
