### PR TITLE
Pango: Add back optional X11 support

### LINKED ISSUE #4602: Pango with X11 support
### Formula Requests:

I'd like to build Pango with X11 support. Is it possible to add back optional X11 support like how it's currently done with Cairo?

### PR DESCRIPTION
**Pull request by jtanx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Closes #4602

### CODE REVIEW

**Comment by DomT4** [comment]
CC @tschoonj

**Comment by tschoonj** [comment]
No objections

**Comment by MikeMcQuaid** [comment]
I'd personally rather we started tearing down X11 options but don't feel strongly either way.

**Comment by tschoonj** [comment]
It should be harmless since it's optional. 

As long as no one asks to add `:x11` back to `gtk+`, I am not worried.

**Comment by DomT4** [comment]
I can live with this as long as the hard red line of not reintroducing X11 to the GTK stuff in any form remains.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/8cbebad288fd3d0df9b3de5c4d20e867d2fa55e2. Thank you for your contribution to Homebrew @jtanx; we appreciate it! :smiley_cat:

**Pull request merged**
