### PR TITLE
terraform 0.8.0

### PR DESCRIPTION
**Pull request by cblecker**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by cblecker** [comment]
@woodruffw Was the test failing the first time? I thought I checked and it was green, but I can't quite remember now. Either way, it looks like it's passing now.

**Comment by woodruffw** [comment]
@cblecker No, I was just having trouble publishing the bottle (still am...) and I thought it might have had to do with the CI troubles earlier today.

**Comment by cblecker** [comment]
@woodruffw Okay! If there is anything I can do to help get this merged, let me know :). Thank you!

**Comment by woodruffw** [comment]
Yep, it was a build issue in our CI. One more re-build should do it, sorry for the delay.

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by woodruffw** [comment]
Thanks @cblecker, we should be good :tada:

**Pull request closed without merging**
