### PR TITLE
gnupg 2.2.17

### PR DESCRIPTION
**Pull request by MindTooth**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
```
04:24:01 ==> brew linkage --test gpgme
04:24:02 ==> FAILED
04:24:02 Broken dependencies:
04:24:02   /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore (qt)
```

`brew linkage --test` does not recognize `depends_on "qt" => [:build, :test]`.

See also #41225.

cc @fxcoudert

**Comment by danieletorelli** [comment]
Hi, any update about it?

**Comment by MindTooth** [comment]
> Hi, any update about it?

I'm unfortunately not in any capacity to debug such issue.  Just upped the version as a came across it on Lobste.rs.

**Comment by danieletorelli** [comment]
> > Hi, any update about it?
> 
> I'm unfortunately not in any capacity to debug such issue. Just upped the version as a came across it on Lobste.rs.

Could you please try to trigger the build again to check if the compilation issue is still valid?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by MindTooth** [comment]
Still the same issue.  I'm at a loss here.

**Comment by robertleeblairjr** [comment]
Looking at GPGME dependencies for the BLFS project, GPGME requires GnuPG 2.2.17 if QT is installed. The other PR #41225 changed the build dependencies to require QT because of not including --disable-gpg-test. But, GPGME build requires GnuPG 2.2.17 now for the testing of the brew linkage test which isn't installed for the test configuration. It seems like if the requirements for GPGME aren't met based upon an optional parameter, then you should pass a command to disable that portion of the GPG test. In this case GPGME shouldn't had required QT since it's optional.

[ftp://ftp7.freebsd.org/sites/www.linuxfromscratch.org/blfs/view/systemd/postlfs/gpgme.html](url)

[ftp://ftp7.freebsd.org/sites/www.linuxfromscratch.org/blfs/view/systemd/postlfs/gnupg.html](url)

**Comment by robertleeblairjr** [comment]
I'm kind of surprised this has been an open PR for almost three weeks. From my readings, GnuPG takes precedence over the interface library GPGME and its requirements/dependencies with configured language bindings. So, an exception for implementing GPGME with fixes in place that wouldn't force GnuPG updates/builds/tests/installs to take break should probably be followed. If it can't be fixed, then GPGME exception isn't implemented until it doesn't conflict with its requirement; GnuPG. GPGME is useless without GnuPG. But, some would argue that GPGME is useless without its bindings. However, GPGME doesn't have to be provided for all bindings. Those which are used by only a few could be built locally/forked much like that's happened with removing the '--with-options' in other formula in homebrew-core. For those bindings which pose a conflict by GPGME then they could be just have the caveat of being built from source by the users who want those bindings, such as QT, in this instance.

**Comment by jonathanmorgan** [comment]
It looks like the problem is a test in gnupg itself.  If you remove `"--enable-all-tests",` from the configure command at the bottom of `gnupg.rb`, that lets 2.2.17 install OK.  So, options I see:

- 1) remove `"--enable-all-tests"` from the configure line.
- 2) require qt as part of gnupg (this is overkill for my use, but not sure generally).
- 3) look into how to configure so it just skips test(s) that needs qt.

**Comment by robertleeblairjr** [comment]
> It looks like the problem is a test in gnupg itself. If you remove `"--enable-all-tests",` from the configure command at the bottom of `gnupg.rb`, that lets 2.2.17 install OK. So, options I see:
> 
> * 1. remove `"--enable-all-tests"` from the configure line.
> * 1. require qt as part of gnupg (this is overkill for my use, but not sure generally).
> * 1. look into how to configure so it just skips test(s) that needs qt.

If developers would remove the QT bindings requirement, then this would pass build and linkage tests. Or, disabling specific tests for GnuPG related to GPGME. If you've got a fix or suggestion for a fix, then you may need to file a bug issue outside of this PR.

**Comment by jonathanmorgan** [comment]
If I understand correctly, the problem for this pull request is that GPGME is being run when the gnupg recipe is run, as part of the tests when it builds gnupg (this might be new on their part as of 2.2.17?), and GPGME requires QT, so the gnupg recipe is now breaking if you don’t have QT installed, because it includes GPGME in its tests and GPGME won’t build without QT.

I looked into the flags you can pass to configure, and I couldn't find an granularity in the parameters you can pass related to testing.  It is either "`--enable-all-tests`" or nothing far as I could find.

If you are just working within the context of homebrew, not trying to swim upstream into the gnupg community, then if I understand correctly, we have two options:

- remove "--enable-all-tests" from the configure line.
- require qt as part of gnupg (this is overkill for my use, but not sure generally).

I am not sure if it is needed to run all the tests when you are installing from a release source archive.  I'd expect that they would have done that before building the release, though you never know.  If people feel strongly about that, then it seems you'd need to require qt for gnupg.

I am willing to file an issue with the gnupg people, but I am not sure where in their priorities it will fall to help users of homebrew to sort a recipe.  Perhaps we could start by asking if it is sane and reasonably secure to compile without all tests if we are building from a formal release of the source the checksum of which has been verified?

Each of the above options is a line of code either added (requiring QT) or commented out (the "`--enable-all-tests`" line in the configure command).

Personally, I think it is probably more secure triage to just require qt for gnupg to make it so all tests can pass, so we can update to the latest, in case we really do need to enable all tests to make sure this library is working correctly and is secure.  Then, if we did that, I could reach out to the gnupg people and explain this problem and see what they say.

**Comment by robertleeblairjr** [comment]
GnuPG is the encrypting/decrypting software engine. It does not require QT or even use it, at least, from my knowledge. It's any interfaces and those apis for frontends that require QT. GPGME is the API for passing data to/from the encrypting/decrypting software engine. The build fail for GnuPG, which is happening in the linkage test, is because GPGME requires QT now since a previous PR #41225 was made by someone adamant about having the QT framework as a requirement when in actuality it is optional to GPGME. I believe someone should have already stepped in with some prior knowledge because I don't believe this is the first time it's occurred. I would wager that this still shouldn't have caused it to fail, except that, from my limited knowledge it wasn't building QT with GPGME or wasn't including a GPGME with QT bindings during the make/build/install/test process for GnuPG in Travis. The devs/maintainers could and may force push it to repo but there's always a chance that you receive a flood of issues being submitted. So, my opinion is that GPGME needs to have a change of either requiring a specific version check of GnuPG and build/test process before a PR is accepted for it, if they're including the QT bindings. Maybe there's an easy workaround but it shouldn't require removing all tests. Of course, there's always the possibility that it's a bug with GnuPG and GPGME, permissions failure, etc. Checking the devs bug reporting at [https://dev.gnupg.org](url) hasn't produced anything viable.

**Comment by robertleeblairjr** [comment]
Not sure if this is part of or is the problem but executing `brew linkage gpgme` gives this output.

>System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/Cellar/gpgme/1.13.1/lib/libgpgme.11.dylib (gpgme)
  /usr/local/Cellar/gpgme/1.13.1/lib/libgpgmepp.6.dylib (gpgme)
  /usr/local/opt/libassuan/lib/libassuan.0.dylib (libassuan)
  /usr/local/opt/libgpg-error/lib/libgpg-error.0.dylib (libgpg-error)
  /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore (qt)
Undeclared dependencies with linkage:
  qt
The QT being an undeclared dependency with linkage could be the culprit during the test phase. I'll search to see if there's a proper method of declaring a dependency. I believe the GPGME formula should have passed this test before it was accepted with QT as a requirement.

**Comment by robertleeblairjr** [comment]
Maybe, GPGME formula dependency for QT can be changed to optional for the time being so that the few who require it can still pull the formula and pass '--with-qt'.
`depends_on "qt" => [:build, :test, :optional]`

**Comment by jonathanmorgan** [comment]
So, I made a fresh Homebrew development environment in a MacOS VM and I am not seeing any errors in just installing gnupg.rb with the changes outlined above.  Should I try a new, separate pull request and see if it generates any problems?  If I do that, then I'd be happy to troubleshoot if there are more problems.  With just gnupg, I'm not seeing any local problems with just the updated gnupg recipe after following the steps here: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula

**Comment by jonathanmorgan** [comment]
Also, on my dev environment, I tried installing and testing gpgme with the 2.2.16 version of gnupg, and it has the same problem.  I don't think the problems with gpgme are related to the version of gnupg, and so I'd consider if you need to hold this pull request up because of those problems.  It looks like the gpgme issue is present with the 2.2.16 version of gnupg (the current formula) and unchanged if you update this formula to 2.2.17.

**Comment by robertleeblairjr** [comment]
Awesome work. I opened another PR to remove the QT bindings for GPGME. However, if this will satisfy the linkage test error, then I'll close it. Do you want to close and reopen this PR for another round of test?

**Comment by jonathanmorgan** [comment]
I don't think I can close and reopen this pull request, since I didn't originate it (I'm just an interested third party).  I am actually not too familiar with how that all works, though, so is that correct?

Regarding the QT dependency, I'm pretty sure this change won't alter the linkage error, so I'd leave that other pull request open.

**Comment by MindTooth** [comment]
@BrewTestBot test this please

**Comment by robertleeblairjr** [comment]
@jonathanmorgan My fault; kind of assumed you opened it. I'm guessing since you said it passed link test fine with 2.2.17. Then, it would require either reverting GPGME to an older version or if the PR I submitted is accepted, then the QT bindings will have been removed as dependencies.

@MindTooth You'd be able to have it resubmitted or closed/reopened after the conflict with the current GPGME has been removed. Afterwards, GPGME would need another PR for adding QT bindings again. If they're accepted, since it failed the build previously. A maintainer pushed the addition of adding QT bindings in the other PR #41225  .

**Comment by robertleeblairjr** [comment]
@MindTooth I just submitted a PR for changes to revert the GPGME to prior to the QT bindings PR which caused problems. After PR #42617 passes and is accepted, then try this one again with reopening. At least, I don't believe there's an issue since the config is the same as 1.13.0.

**Comment by MindTooth** [comment]
I'll follow the development of this.

**Comment by robertleeblairjr** [comment]
Sounds good. We'll see if it passes build now since the PR for reverting GPGME back to pre-QT bindings passed and committed.

**Comment by robertleeblairjr** [comment]
Oh never mind. Another GnuPG PR #42680 passed check and awaiting commit.

**Comment by MindTooth** [comment]
Glad it got solved. 😄  Hate having PRs open.

**Comment by jonathanmorgan** [comment]
2.2.17 installed.  Thanks for the help everyone!

**Pull request closed without merging**
