### PR TITLE
bash 5.1

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by fxcoudert** [comment]
@bayandin for the record, this was missing `sha256`: https://github.com/Homebrew/homebrew-core/pull/66481
Currently wondering how it got past CI

**Comment by glensc** [comment]
The user experience of bash update to 5.1 terrible. any running bash 5.0 process (interactive shell) will abort with signal 9:

```
...
==> Upgrading 21 outdated packages:
bash 5.0.18 -> 5.1
...

...
$ date
Killed: 9
$ which bash
Killed: 9
```

**Comment by bayandin** [comment]
Do you have any ideas on how we can improve it?

**Comment by fxcoudert** [comment]
Upgrading the shell you're currently running is going to be difficult, in any case. I am not sure what we can do about that.

**Comment by glensc** [comment]
Can make brew emit some warning, not to panic and instructions? 

More UX friendly would be a confirmation not to do the upgrade without user consent?

I've seen this error the first time because I used to use system bash (`/bin/bash`), does it happen with every bash update or just update 5.0 -> 5.1?

**Comment by glensc** [comment]
In POSIX filesystems (macOS should be one too), it's perfectly fine to run executables that have been replaced (deleted). Probably bash is doing something extra on macOS that now it gets killed if the binary is replaced. Maybe it's a security measure?

**Pull request closed without merging**
