### PR TITLE
aptos 2.1.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    --- stderr
    Compiling, may take a little while to download git dependencies...
    BUILDING MoveStdlib
    Compiling, may take a little while to download git dependencies...
    INCLUDING DEPENDENCY MoveStdlib
    BUILDING AptosStdlib
    Compiling, may take a little while to download git dependencies...
    INCLUDING DEPENDENCY AptosStdlib
    INCLUDING DEPENDENCY MoveStdlib
    BUILDING AptosFramework
    thread 'main' panicked at 'release build failed: No such file or directory (os error 2)', aptos-move/framework/cached-packages/build.rs:83:14
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  error: failed to compile `aptos v2.1.1 (/private/tmp/aptos-20230927-5199-1qzfg4b/aptos-core-aptos-cli-v2.1.1/crates/aptos)`, intermediate artifacts can be found at `/private/tmp/aptos-20230927-5199-1qzfg4b/aptos-core-aptos-cli-v2.1.1/target`.
  To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by gregnazario** [comment]
Noted @chenrui333 will get someone from my team to look at it

**Comment by banool** [comment]
Debugging here: https://github.com/aptos-labs/aptos-core/issues/10284.

**Review by SMillerDev — APPROVED** [review]

**Comment by p-linnane** [comment]
Looks like the OpenSSL dep was removed in https://github.com/aptos-labs/aptos-core/pull/9961.

**Comment by banool** [comment]
Yes! I didn't realise brew would mandate that libssl is actually used if you depend on it, that's neat. I see you removed the openssl stuff, thanks!

**Comment by chenrui333** [comment]
> Looks like the OpenSSL dep was removed in [aptos-labs/aptos-core#9961](https://github.com/aptos-labs/aptos-core/pull/9961).

good find!

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
