### PR TITLE
macpine: add shell completion generation

### PR DESCRIPTION
**Pull request by xzinkus**
`macpine` supports shell completion file generation. Add this to the `brew` formula for convenience.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by maxzinkus** [comment]
Apologies, rubicop was giving me issues. Please feel free to squash & merge away the mess.

**Comment by maxzinkus** [comment]
we support `bash`, `fish`, `zsh`, and `powershell`. I left it using brew default (first 3) because I don't think powershell is officially supported by brew.

**Review by carlocab — APPROVED** [review]
Thanks for the PR! For future reference, we put the names of formulae first in our commit messages, like so:
```
macpine: add shell completion generation
```

**Comment by maxzinkus** [comment]
got it, thanks so much!

**Comment by carlocab** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/a0a7b74657996728caf039854bfc7e16dd7d7e0d.

**Pull request closed without merging**
