### PR TITLE
gpg-tui 0.9.5

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Now this is a good chance to try out https://github.com/Homebrew/homebrew-core/labels/autosquash.

**Review by carlocab — DISMISSED** [review]

**Review by chenrui333 — DISMISSED** [review]

**Comment by carlocab** [comment]
```
/usr/bin/git push --force https://github.com/ZhongRuoyu/homebrew-core.git bump-gpg-tui-0.9.5
To https://github.com/ZhongRuoyu/homebrew-core.git
 ! [remote rejected]         bump-gpg-tui-0.9.5 -> bump-gpg-tui-0.9.5 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/dispatch-build-bottle.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/ZhongRuoyu/homebrew-core.git'
```
Weird.

**Comment by carlocab** [comment]
I guess this means `autosquash` doesn't work when workflows have been recently updated? 😅

**Review by carlocab — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
> I guess this means `autosquash` doesn't work when workflows have been recently updated? 😅

Looks that way. 😶

**Comment by carlocab** [comment]
Should be fixed by #126975.

**Pull request merged**
