### PR TITLE
caddy: fix service when using sudo brew services

### PR DESCRIPTION
**Pull request by unbeatable-101**
Adding the "HOME" environment variable allows caddy to properly store its runtime files (see https://caddyserver.com/docs/conventions#data-directory) without erroring out when it is run with `sudo brew services start caddy`, otherwise it is not able to edit a readonly directory.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This change allows caddy to be run with `sudo brew services start caddy` without erroring due to wanting to save some runtime info in `$HOME/Library/Application Support/Caddy` (see https://caddyserver.com/docs/conventions#data-directory for more info).

Old PR: #158214

### CODE REVIEW

**Comment by SMillerDev** [comment]
We really should not set that to anything but the user's home directory. We can either set `XDG_DATA_HOME` like the documentation you linked offers, or we should report the possibility of `HOME` being empty to the developers.

**Comment by unbeatable-101** [comment]
That's a fair point, when running `brew services` without sudo, `HOME` does have a value. If `XDG_DATA_HOME` is set as the environment variable, would `etc/` be a good value for it? Caddy would then place its runtime files in `$(brew --prefix)/etc/caddy`.

**Comment by SMillerDev** [comment]
Isn't data usually something like `/var/lib`? And `_CONFIG_` would be `/etc`

**Comment by unbeatable-101** [comment]
Oh sorry, I must have not read the variable properly, I thought it was `_CONFIG_`. Guess I should get to bed. 

I don't have much experience with UNIX file location conventions, so I don't really know where `_DATA_` should point to.

**Comment by unbeatable-101** [comment]
I changed it so now `XDG_DATA_HOME` is set to `#{HOMEBREW_PREFIX}/var/lib/`

**Comment by unbeatable-101** [comment]
@SMillerDev could you take another look at this?

**Comment by unbeatable-101** [comment]
I tried adding a caveats block by adding this:

```ruby
  def caveats
    on_macos do
      <<~EOS
        When running the provided service, caddy's data dir will be set as
          `#{HOMEBREW_PREFIX}/var/lib`
        instead of the default location of
          `$HOME/Library/Application Support/Caddy`
      EOS
    end
    on_linux do
      <<~EOS
        When running the provided service, caddy's data dir will be set as
             `#{HOMEBREW_PREFIX}/var/lib`
          instead of the default location of
            `$HOME/.local/share/caddy`
      EOS
    end
  end
```
But it only worked if I commented out the `on_linux do` or `on_macos do` block, if both were left in it didn't show either of them.

**Review by SMillerDev — APPROVED** [review]

**Comment by unbeatable-101** [comment]
I think the issue with the failed build has to do with https://github.com/Homebrew/homebrew-core/pull/159005 being merged earlier today

**Comment by unbeatable-101** [comment]
I rebased my branch to include the rebuild in the current file, the bot should now properly increment it to 2

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
