### PR TITLE
git-interactive-rebase-tool 2.3.0

### PR DESCRIPTION
**Pull request by neersighted**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error: unknown lint: `ffi_unwind_calls`
    --> src/runtime/src/lib.rs:17:1
     |
  17 | / #![deny(
  18 | |     absolute_paths_not_starting_with_crate,
  19 | |     deprecated_in_future,
  20 | |     elided_lifetimes_in_paths,
  ...  |
  52 | |     variant_size_differences
  53 | | )]
     | |__^
     |
     = note: the `ffi_unwind_calls` lint is unstable
     = note: see issue #74990 <https://github.com/rust-lang/rust/issues/74990> for more information
  note: the lint level is defined here
    --> src/runtime/src/lib.rs:14:2
     |
  14 |     warnings
     |     ^^^^^^^^
     = note: `#[deny(unknown_lints)]` implied by `#[deny(warnings)]`
  
     Compiling girt-todo-file v2.3.0 (/private/tmp/git-interactive-rebase-tool-20230719-52883-1dfdoy8/git-interactive-rebase-tool-2.3.0/src/todo_file)
```

**Comment by MitMaro** [comment]
👋🏼 Maintainer of git-interactive-rebase-tool here!

The above error is caused by macOS having an older version of Rust installed. The failure is caused by using an older stable version of Rust. I'm not sure of the usual process for updated/fixing the rust version in Homebrew, but I believe the latest stable version of Rust should compile/build correctly.

**Comment by neersighted** [comment]
This should be green with Rust 1.71 (https://github.com/Homebrew/homebrew-core/pull/136514)

**Comment by MitMaro** [comment]
@neersighted , you may have some success getting this working with the older version of Rust by "capping" the lints. Inside the `def install` function, add `ENV["RUSTFLAGS"] = "--cap-lints warn"` ([example](https://github.com/Homebrew/homebrew-core/blob/60e775b0ede2445f9a0d277fa86bb7e594cd6778/Formula/csound.rb#L94)).


Since this is only failing due to a linting error and there isn't any reason why an older version should fail, disabling the linting shouldn't be a problem for a build.

**Comment by neersighted** [comment]
That's a fair point, though I was figuring that it would be better to skip a workaround as 1.71 is imminent. I'll go ahead and push it up with a FIXME; WDYT @chenrui333?

**Comment by neersighted** [comment]
@chenrui333 Could you please reopen this and give it the right lifecycle label?

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
