### PR TITLE
grafana 5.3.4

### PR DESCRIPTION
**Pull request by sc250024**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails on high_sierra only:
```
==> node_modules/grunt-cli/bin/grunt build
Failed to execute: node_modules/grunt-cli/bin/grunt
```

**Comment by sc250024** [comment]
@BrewTestBot Test this please

**Comment by sc250024** [comment]
Seeing if it happens again...

**Comment by sc250024** [comment]
@Moisan Looks like it was just a temporary hiccup. Tests pass now.

**Comment by Moisan** [comment]
Thank you @sc250024 !

**Pull request closed without merging**
