### PR TITLE
kibana 6.3.0

### PR DESCRIPTION
**Pull request by ddillinger**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jasontedor** [comment]
@ilovezfs @MikeMcQuaid Sorry for the ping, but we need some help here. We have changed the licensing on our artifacts here so they do not carry a Apache 2.0 license anymore starting with 6.3.0. We want to work with Homebrew to allow distribution in an appropriate way. Is there someone that can reach out to us to start a conversation? Until we can sort that out though, we want to be conservative and ask that any PRs bumping the formula to 6.3.0 not be merged. I am happy to have a conversation here, or I can be reached at my first name at elastic.co.

**Comment by commitay** [comment]
@jasontedor Does the license change also apply to the versioned formulae? `kibana@5.6` and `elasticsearch@5.6`  both have a new version `5.6.10`?

**Comment by jasontedor** [comment]
@commitay No, it only applies to 6.3.0 and later versions. All existing and future maintenance releases in the 5.6 series will continue to be under the same Apache 2.0 license as before. The 6.0, 6.1, and 6.2 series are also Apache 2.0 licensed. The change for the default distribution starts with the 6.3 series.

**Comment by ilovezfs** [comment]
What is the new license?

**Comment by ilovezfs** [comment]
OK, I see https://github.com/elastic/kibana/blob/master/licenses/ELASTIC-LICENSE.txt

Is there anything in the formula that is installing stuff from x-pack?

**Comment by ilovezfs** [comment]
@jasontedor my recommendation is that upstream provide a source tarball that doesn't have the x-pack components at all so there are no misunderstandings. If that's not something upstream is willing to do, we can `rm_rf "x-pack"` at the beginning of the `install` method.

**Comment by MikeMcQuaid** [comment]
Also agree with @ilovezfs here.

**Comment by JCount** [comment]
I agree with @ilovezfs on this matter as well.

**Comment by ilovezfs** [comment]
@jasontedor @ddillinger any update here?

**Comment by jasontedor** [comment]
Heya, sorry, I’m on vacation since last Friday until next Monday so my replies will be terse and with high latency.

Briefly, the x-pack folder is integrated into our build scripts for some of the projects (if not all, I can’t check right now) so removing it at build time or providing a source tarball without the x-pack folder would not be possible at this time.

**Comment by ilovezfs** [comment]
OK, we'll leave `kibana`, etc. at 6.2.x in Homebrew until upstream is able to provide an open source tarball and build script for 6.3.x. Thanks for the updated information @jasontedor

**Comment by ilovezfs** [comment]
Thanks for the PR nonetheless @ddillinger

**Comment by jrosengren** [comment]
Apache 2.0 licensed downloads (at least for metricbeat) appear to be available here:  https://www.elastic.co/downloads/beats/metricbeat-oss

Are you able to use the "-oss" versions of the beats or is there still a question about whether those are fully Apache 2.0 compatible?

**Comment by ilovezfs** [comment]
@jrosengren those should be fine! @jasontedor please correct me if that's not the case.

**Comment by ilovezfs** [comment]
@jrosengren I think the problem there is that there's no way for us to build those from source unless I'm not seeing it. So actually the situation is unchanged.

**Comment by felixbuenemann** [comment]
@jasontedor Would removing the `bin/x-pack` and `modules/x-pack` directories from the elasticsearch tar-ball be enough to keep only the Apache 2.0 licensed parts?

**Comment by jrosengren** [comment]
It seems somewhat ridiculous that this hasn't been resolved yet.  What are we waiting for to be able to include Metricbeat 6.3.x in Homebrew?

**Comment by MikeMcQuaid** [comment]
@jrosengren The ability to build a package from source with an open source license.

**Comment by jrosengren** [comment]
Elastic publishes -oss docker images that presumably only contain the open source bits, so it seems like it should be possible for Homebrew to build similarly open source bits.

https://raw.githubusercontent.com/elastic/beats/99824df163863478d27688206e18ec27bc1b3ac5/LICENSE.txt

Based on the text in the LICENSE.txt, should it be possible to just download the source, run the build, and only use the -oss package?  Or does Homebrew have a requirement to not download any non-open source bits?

**Comment by mschneid** [comment]
@MikeMcQuaid As I have seen, Elastic offers OSS downloads for the new 6.4.0 series:

- [Kibana 6.4.0](https://www.elastic.co/downloads/kibana-oss)
- [Elasticsearch 6.4.0](https://www.elastic.co/downloads/elasticsearch-oss)
- [Logstash 6.4.0](https://www.elastic.co/downloads/logstash-oss)
- [Filebeat 6.4.0](https://www.elastic.co/downloads/beats/filebeat-oss)
- [Metricbeat 6.4.0](https://www.elastic.co/downloads/beats/metricbeat-oss)
- [Auditbeat 6.4.0](https://www.elastic.co/downloads/beats/auditbeat-oss)
- [Packetbeat 6.4.0](https://www.elastic.co/downloads/beats/packetbeat-oss)

**Comment by MikeMcQuaid** [comment]
> Based on the text in the LICENSE.txt, should it be possible to just download the source, run the build, and only use the -oss package? Or does Homebrew have a requirement to not download any non-open source bits?

If there's a guaranteed way of building only the OSS version; yeh we can't do that, I don't think we're saying we can't download it.

**Comment by felixbuenemann** [comment]
@mschneid At least some of those packages contain platform specific tar-balls, so since they contain pre-built binaries I don't think they can be used for homebrew packages.

**Comment by chrmoritz** [comment]
At least `kibana` (not sure about the other ones) seems to have an [option `-oss` in their build script](https://github.com/elastic/kibana/blob/31eee3238d7ffe3fea7b27796d03308235ef66e8/src/dev/build/cli.js#L70) to build only the OSS version now.

I was able to build the OSS version after `rm_rf "x-pack"` with the upgraded formula in https://github.com/chrmoritz/homebrew-core/commit/1f31903a2093e559103bb681251db96109440f75, which also follows upstream by switching from `npm` to `yarn` and upgrades the bundled `node` to the 8.x release line (which should fix the 10.14 bottle #31741).

But I don't know if (and how) we could do similar OSS-only builds for the other elastic formulae.

**Comment by MikeMcQuaid** [comment]
@chrmoritz Sounds like a good call for a PR 👍

**Comment by chrmoritz** [comment]
@MikeMcQuaid The main problem is, that this PR would be blocked on upgrading `elasticsearch` to 6.4.0 (as `kibana@6.4.0` isn't compatible with `elasticsearch@6.2.0`), which itself is blocked on upgrading most (all?) other elastic formulae to 6.4.0.

I have no idea if (and how) building only the OSS part is possible for these other formulae as they are all using quite different build systems. But if you want I could open this as another do-not-merge PR to start the effort of upgrading the elastic formulae to 6.4.0 and hope that someone else, who is more familar with these build systems, will chime in and continue the work.

**Comment by MikeMcQuaid** [comment]
> I have no idea if (and how) building only the OSS part is possible for these other formulae as they are all using quite different build systems. But if you want I could open this as another do-not-merge PR to start the effort of upgrading the elastic formulae to 6.4.0 and hope that someone else, who is more familar with these build systems, will chime in and continue the work.

This sounds good 👍

**Comment by chrmoritz** [comment]
I've currently `kibana`, `elasticsearch` and `logstash` upgraded to 6.4.0.

Still need help for the `go` based:
* [ ] `packetbeat`
* [ ] `metricbeat`
* [ ] `heartbeat`
* [ ] `filebeat`
* [ ] `auditbeat`
* [ ] `apm-server`

**Pull request closed without merging**
