### PR TITLE
libgpg-error 1.25

### PR DESCRIPTION
**Pull request by woodruffw**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by aabdnn** [comment]
I attempted to rewind my libgpg-error formula to version 1.24 and then "brew install" it, but brew keeps wanting to auto-update first, before installing. I must say this is bloody irritating. It doesn't let me install the version that works!! Who decided that brew should unconditionally update every time before installing a package??

So what am I supposed to do now? My gpg doesn't work, and I can't revert to the older version of libgpg-error. Is there a flag or something that I can pass to brew to tell it not to update before installing?

Is there a "downgrade" option of any kind? With yum, I can do "yum downgrade <package>" to revert a broken package, and that's really useful.

I am quite annoyed at the forced auto-update before install "feature" in brew. Why isn't there a flag like "brew install --no-update <formula>" ?

**Comment by woodruffw** [comment]
> Why isn't there a flag like "brew install --no-update " ?

You can disable automatic updates by setting `HOMEBREW_NO_AUTO_UPDATE=1` in your environment.

**Comment by ilovezfs** [comment]
@aabdnn I'd recommend you vent here: https://lists.gnupg.org/pipermail/gnupg-devel/2016-November/032185.html

**Comment by aabdnn** [comment]
@woodruffw thanks for the hint about using HOMEBREW_NO_AUTO_UPDATE. I managed to use it to downgrade to libgpg-error 1.24 and get my gnupg21 working again. I've pinned libgpg-error for now to prevent it from being upgraded.

**Comment by woodruffw** [comment]
No problem. Just keep your eye out for that incoming gnupg fix.

**Pull request closed without merging**
