### PR TITLE
workflows/tests: use large Linux runner

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

See discussion at #124923.

### CODE REVIEW

**Comment by carlocab** [comment]
Ok, seems to work: https://github.com/Homebrew/homebrew-core/actions/runs/4373281379/jobs/7651370382

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Do we not want to keep self-hosted? And does this also need an upload change?

**Comment by carlocab** [comment]
> Do we not want to keep self-hosted?

It requires extra maintenance work, but no one seems to have the bandwidth for it so I think we can just get rid of it. I'm not sure what the advantage of our GCP self-hosted runner is over using a large GitHub runner tbh.

> And does this also need an upload change?

I don't think so, no.

**Comment by SMillerDev** [comment]
> I'm not sure what the advantage of our GCP self-hosted runner is over using a large GitHub runner tbh.

Doesn't the large runner still obey the default 6hr timeout for actions?

**Comment by carlocab** [comment]
> > I'm not sure what the advantage of our GCP self-hosted runner is over using a large GitHub runner tbh.
> 
> Doesn't the large runner still obey the default 6hr timeout for actions?

No, I don't think so, because large runners are paid for. But let me make sure.

**Comment by MikeMcQuaid** [comment]
> No, I don't think so, because large runners are paid for. But let me make sure.

I think they may still do but it'll be documented somewhere.

**Review by MikeMcQuaid — APPROVED** [review]
I see no downside in doing this for now given the previous one is hosed.

**Pull request merged**
