### PR TITLE
hdf5 1.10.4

### PR DESCRIPTION
**Pull request by tschoonj**
Will revbump dependents where necessary based on Jenkins build results...

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by tschoonj** [comment]
Any thoughts on why I am seeing those test errors? Looks like a Homebrew issue to me

**Comment by fxcoudert** [comment]
Test failures for `flann`, `caffe`, `libmatio`, and `nco` are due to https://github.com/Homebrew/brew/issues/5122

**Comment by fxcoudert** [comment]
See https://github.com/Homebrew/homebrew-core/pull/33076 for a separate PR on vtk, which restores the build for Mojave.

**Comment by fxcoudert** [comment]
With vtk fixed, and brew fixed, I think it's ready to go again!
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Random Jenkins failures on Mojave.
@BrewTestBot test this again please

**Comment by fxcoudert** [comment]
Random Jenkins failures on Mojave.
@BrewTestBot test this please, again

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@tschoonj yes, the “Downstream build view” link says “Homebrew bottles SUCCESS”

**Comment by commitay** [comment]
> `nco` was conflicting

Sorry!

**Comment by fxcoudert** [comment]
@commitay no problem, it helps me practice my `git rebase` and `git cherry-pick` skills :)

**Pull request closed without merging**
