### PR TITLE
k6 0.25.0

### PR DESCRIPTION
**Pull request by Vmihajlovic**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
👍

**Comment by Moisan** [comment]
Thank you @Vmihajlovic for your first contribution! Without people like you, we couldn't run this project.

**Comment by na--** [comment]
Quick question: do we need to submit a separate PR for the [linux homebrew k6 formula](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/k6.rb)? Or is there a bot that occasionally updates packages there after they are updated here?

**Comment by SMillerDev** [comment]
>Quick question: do we need to submit a separate PR for the [linux homebrew k6 formula](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/k6.rb)? Or is there a bot that occasionally updates packages there after they are updated here?

Just like it is here it's the most inefficient machines of all, people

**Pull request closed without merging**
