### PR TITLE
chapel 1.31

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by bradcray** [comment]
@SMillerDev / @carlocab : Thanks for the quick approvals on this and #134645!

This is the first I think we've seen the replacement PR bot fire on one of our PRs.  Is there something we could/should do in the future to prevent needing that step?  Or somewhere to read about what it does / why it's needed?  (I didn't find anything in a quick google or github issues search, but it's admittedly late in the day).

**Comment by carlocab** [comment]
No problem. Replacement PRs are created when one of the following occurs:
1. @BrewTestBot cannot push commits to the PR branch (not the case here)
2. The commit message is not in our preferred format (this is what happened)

For future PRs, use a commit message like
```
chapel 1.3x
```
Alternatively, use `brew bump-formula-pr` to simplify handling of this in the future.

**Comment by bradcray** [comment]
Great, thanks for the info, @carlocab!

**Comment by carlocab** [comment]
Sure. You can also look out for the https://github.com/Homebrew/homebrew-core/labels/autosquash label. When you see that, it means the pull request will be replaced.

**Pull request closed without merging**
