### PR TITLE
vim 8.0.1240

### PR DESCRIPTION
**Pull request by rtlechow**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for the PR. However, we only update this every 50 versions.

**Comment by rtlechow** [comment]
Ah kk. Just gave it a shot cuz I saw https://medium.com/@haya14busa/incsearch-vim-is-dead-long-live-incsearch-2b7070d55250

**Comment by ilovezfs** [comment]
Cool. Given how frequently vim gets a new version we should be at 1250 in about 10 minutes or so :see_no_evil:

**Comment by ilovezfs** [comment]
8.0.1250 has now shipped: https://github.com/Homebrew/homebrew-core/pull/20194

**Pull request closed without merging**
