### PR TITLE
Rebuild Citus 6.0

### PR DESCRIPTION
**Pull request by jasonmp85**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The tag contents changed, so the sha changed. I believe I'm doing this correctly, just checking.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@jasonmp85 Can you file an issue upstream asking them why the tag changed and if they've been hacked? We need to nicely ask them to not change tags in future.

**Comment by jasonmp85** [comment]
> Can you file an issue upstream asking them why the tag changed and if they've been hacked? We need to nicely ask them to not change tags in future.

In short, no hacking. In long:

So… I _am_ upstream, and _I_ changed the tag because it was less than a day old and I made a mistake in forgetting to cherry-pick something to our release branch.

I know, it's bad; I feel bad. Just didn't want to have to bump to `6.0.1` when we hadn't even built our own packages. Forgot I had already opened the homebrew pull request. Gah.

At any rate, the tag is signed with my GPG key; I'm jasonmp85 on [keybase](https://keybase.io/jasonmp85), and I've signed every single tag we've ever released, as well as every commit in all projects I am a part of. So there's that as some proof.

In addition, we sign our tarballs with a [company-wide packaging key](https://install.citusdata.com/packaging.key). The [release](https://github.com/citusdata/citus/releases/tag/v6.0.0) page has this signature for download (and indeed it is automatically downloaded and verified by the main Debian packaging system that pulls from us).

**Comment by ilovezfs** [comment]
>I know, it's bad; I feel bad.

It's OK. Don't feel bad. Thanks for clarifying.

**Comment by ilovezfs** [comment]
Shipped. @jasonmp85 thanks for updating the formula after the tag changed.

**Comment by MikeMcQuaid** [comment]
> So… I am upstream, and I changed the tag because it was less than a day old and I made a mistake in forgetting to cherry-pick something to our release branch.

For future reference: anyone who pulled your Git repository's tags will still be on the old tags because Git doesn't update tags by default (for hopefully fairly obvious security reasons).

> I know, it's bad; I feel bad. Just didn't want to have to bump to 6.0.1 when we hadn't even built our own packages. Forgot I had already opened the homebrew pull request. Gah.

I understand this is annoying but I'd like to ask in future you consider bumping to 6.0.1 (or 6.0.000000001 or whatever) as for both Git cloners and packagers.

**Comment by jasonmp85** [comment]
> For future reference: anyone who pulled your Git repository's tags will still be on the old tags because Git doesn't update tags by default (for hopefully fairly obvious security reasons).

Oh, I know!

> I understand this is annoying but I'd like to ask in future you consider bumping to 6.0.1 (or 6.0.000000001 or whatever) as for both Git cloners and packagers.

I certainly considered it. Next time I'll try to avoid tagging until absolutely sure the branch is ready. It's not quite that _I_ don't understand the severity; sometimes it's a little hard to adequately explain to non-tech people why the release needs to be bumped when we haven't even yet done a formal 6.0 announcement and I could "just delete it". Sorry about all this, and thanks for getting this merged!

**Pull request closed without merging**
