### PR TITLE
Add formula for samba.org version of smbd to enable QEMU usermode sharing

### PR DESCRIPTION
**Pull request by arichardson**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Samba can be used to share directories with the guest in QEMU user-mode
(SLIRP) networking with the `-net user,id=net0,smb=/share/this/with/guest`
option. However, without this formula QEMU will attempt use the system
/usr/sbin/smbd which does not understand the options and config file
generated by QEMU and therefore will silently fail to setup the share.

By providing the samba.org smbd as a keg-only formula we can use it as an
optional dependency for QEMU to support sharing host directories with SMB.

### CODE REVIEW

**Comment by arichardson** [comment]
> * Dependency 'krb5' may be unnecessary as it is provided by macOS; try to build this formula without it.

I tried using the version in /usr/ instead but the build failed because it needs version 1.9 or newer.

**Comment by fxcoudert** [comment]
`qemu` already has a lot of options, many of which are seldom used, so I'm not particularly happy to add yet another one. Is there evidence that this feature is widely used, or that it is enabled in typical binaries (Linux packages, upstream macOS binaries, etc.)?

```
install_on_request events in the last 30 days
================================================================================
 1 | qemu                                                      | 6,678 |  96.49%
 2 | qemu --with-sdl2                                          |   102 |   1.47%
 3 | qemu --with-vde --with-sdl2 --with-gtk+3 --with-libssh2 - |    17 |   0.25%
 4 | qemu --HEAD                                               |    14 |   0.20%
 5 | qemu --with-sdl2 --with-libssh2 --with-libusb             |    14 |   0.20%
 6 | qemu --with-vde --with-sdl2 --with-libssh2 --with-libusb  |    10 |   0.14%
 7 | qemu --with-libusb                                        |     7 |   0.10%
 8 | qemu --with-sdl2 --with-libusb                            |     7 |   0.10%
 9 | qemu --devel                                              |     6 |   0.09%
10 | qemu --with-gtk+3                                         |     5 |   0.07%
11 | qemu --with-libssh2                                       |     5 |   0.07%
12 | qemu --with-libssh2 --with-libusb                         |     5 |   0.07%
```

**Comment by arichardson** [comment]
Actually I think the option is not necessary. It looks like QEMU ./configure runs just fine if the --smbd= value doesn't exist. It is only a hardcoded value and the default that QEMU detects (/usr/sbin/smbd) won't work anyway so I think always setting it is fine. If samba is installed then the `-smb=/path` option will work and if not it won't.
Is it possible to declare an optional runtime dependency (I don't really know anything about writing formulas)?

**Comment by javian** [comment]
Samba was once removed from core since upstream support for macOS was questionable. See https://github.com/Homebrew/legacy-homebrew/issues/17820

**Comment by arichardson** [comment]
Well it works perfectly for the qemu sharing use case. It is extremely helpful to me since I don't have any other way of sharing host folders with my qemu guest os. I can certainly continue to build from source now that I have discovered the 20 ./configure flags that I need but by having this as part of homebrew will allow other users to easily use this qemu feature.

**Comment by fxcoudert** [comment]
Thanks @arichardson for the pull request. Given the prior history of Samba we are going to decline adding it back. One solution could be to vendor it (as a resource) inside qemu, but it would be rather fragile and for the benefit of relatively few users.

For your own needs, hosting this formula in a personal tap is probably a good solution: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Pull request closed without merging**
