### PR TITLE
torchvision: enable openmp

### PR DESCRIPTION
**Pull request by sabify**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This fixes the failed tests in #101666

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why should we use `openmp` as a dependency?

**Comment by sabify** [comment]
This is needed by #101705 tests to be passed.

**Comment by SMillerDev** [comment]
And why is that one needed?

**Comment by sabify** [comment]
To enable `openmp` in `libtorch` for multi-threaded training to gain huge performance by maximizing cpu utilization.

**Review by carlocab — APPROVED** [review]
LGTM, since `libomp` is already in `torchvision`'s dep tree.

**Pull request merged**
