### PR TITLE
akka 2.5.21

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yurikoles** [comment]
```
17:55:46 Error: An exception occurred within a child process:
17:55:46   Errno::ENOENT: No such file or directory @ unlink_internal - bin/akka.bat
```

**Comment by alebcay** [comment]
Yeah, I realized that after 2.4.17, the releases are source-only. Trying to figure out how to compile/package this dinosaur with `sbt` right now.

**Comment by alebcay** [comment]
It seems that `akka` has been [split into multiple packages](https://mvnrepository.com/search?q=com.typesafe.akka). Would it be a better idea to split this into multiple formulae or to install all of these in one formulae?

**Comment by Moisan** [comment]
Unless each package in isolation could be clearly useful, I would advise to use multiple resources and compile them all together in the `akka` formula. Nothing stops us from splitting them in different formulae afterward if needed.

**Pull request closed without merging**
