### PR TITLE
zsh 5.4.1

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hi @zmwangx thanks for the PR. I'm slightly hijacking it, removing the `revision` line and also removing the rarely used `--with-texi2html` option. We thus streamline the formula and requirements.

**Comment by fxcoudert** [comment]
Version not yet officially released…

**Comment by zmwangx** [comment]
@fxcoudert Officially released. http://www.zsh.org/mla/zsh-announce/133

**Comment by fxcoudert** [comment]
Thanks @zmwangx for the pull request!

**Pull request closed without merging**
