### PR TITLE
spaceship 3.11.2 (new formula)

### PR DESCRIPTION
**Pull request by danielbayley**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Audit failure:
```
Error: 1 problem in 1 formula detected
spaceship:
  * Non-libraries were installed to "/usr/local/opt/spaceship/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/opt/spaceship/lib/utils.zsh
            /usr/local/opt/spaceship/lib/hooks.zsh
            /usr/local/opt/spaceship/lib/section.zsh
```

Test failure:
```
==> zsh -c 'autoload -U promptinit; promptinit && prompt -p spaceship'
Error: spaceship: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </\->/> was expected to be =~
<"\e[39m\e[49m\n" +
"spaceship theme:\n" +
"\r$(spaceship_prompt)command arg1 arg2 ... argn\n" +
"\e[39m\e[49m\n">.
```

**Comment by carlocab** [comment]
Please format your commits according to the description here: https://docs.brew.sh/Formula-Cookbook#commit

>At Homebrew, we like to put the name of the formula up front like so: foobar 7.3 (new formula).

**Comment by danielbayley** [comment]
> Audit failure (all CI nodes):
> 
> ```
> Error: 1 problem in 1 formula detected
> spaceship:
>   * Non-libraries were installed to "/usr/local/opt/spaceship/lib"
>     Installing non-libraries to "lib" is discouraged.
>     The offending files are:
>       /usr/local/opt/spaceship/lib/utils.zsh
>             /usr/local/opt/spaceship/lib/hooks.zsh
>             /usr/local/opt/spaceship/lib/section.zsh
> ```

What defines 'non-libraries' exactly?

It can be really awkward to translate a projects' chosen folder structure into the one enforced by Homebrew, when files obviously depend on relative paths to other files and folders in many projects… @carlocab What is the correct way of going about this when, for example in this case, we just have a file `spaceship.zsh` (that needs to be linked into `zsh_functions` as `prompt_spaceship_setup`) that depends on stuff in [it's own] `lib` and `sections` folders?

**Comment by danielbayley** [comment]
> Please format your commits according to the description here: https://docs.brew.sh/Formula-Cookbook#commit
> 
> > At Homebrew, we like to put the name of the formula up front like so: foobar 7.3 (new formula).

No problem!

**Comment by SMillerDev** [comment]
> What defines 'non-libraries' exactly?

This directory is strictly for application libraries (`.so` or `.dylib` files). Anything else would need to go in an application specific library directory.

> It can be really awkward to translate a projects' chosen folder structure into the one enforced by Homebrew

We're really just enforcing the UNIX standards, making it easier for all packaging parties to work with the upstream sources.

**Comment by danielbayley** [comment]
> > It can be really awkward to translate a projects' chosen folder structure into the one enforced by Homebrew

> We're really just enforcing the UNIX standards, making it easier for all packaging parties to work with the upstream sources.

Maybe this way is correct? (Just pushed)…
~~~ rb
libexec.install "spaceship.zsh", "lib", "sections"
zsh_function.install_symlink libexec/"spaceship.zsh" => "prompt_spaceship_setup"
~~~

**Comment by danielbayley** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

> > > It can be really awkward to translate a projects' chosen folder structure into the one enforced by Homebrew
> 
> > We're really just enforcing the UNIX standards, making it easier for all packaging parties to work with the upstream sources.
> 
> Maybe this way is correct? (Just pushed)…
> 
> ```ruby
> libexec.install "spaceship.zsh", "lib", "sections"
> zsh_function.install_symlink libexec/"spaceship.zsh" => "prompt_spaceship_setup"
> ```

@SMillerDev …?

**Comment by carlocab** [comment]
Your test didn't pass on Mojave:
```
==> zsh -c 'autoload -U promptinit; promptinit && prompt -p spaceship'
Error: spaceship: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </\->/> was expected to be =~
<"\e[39m\e[49m\n" +
"spaceship theme:\n" +
"\r$(spaceship_prompt)command arg1 arg2 ... argn\n" +
"\e[39m\e[49m\n">.
```

Can you rebase your branch against master to restart the tests?

**Pull request closed without merging**
