### PR TITLE
Update cryptography 3.4.x resources

### PR DESCRIPTION
**Pull request by alex**
This ensures that all brew packages use the latest version in the 3.4.x series

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
`charm-tools` might fail because it might need https://github.com/juju/charm-tools/pull/611 (I can handle it in a separate PR). Rest should be good.

**Comment by alex** [comment]
Thanks! Happy to rebase when that happens.

(I'm one of the cryptography maintainers and I want to move the ecosystem to using the latest releases and getting to the latest within a version is the starting point.)

**Comment by alex** [comment]
Looks like CI timed out despite the labels (perhaps they were added after the job started?)

**Comment by alex** [comment]
Tests appear to be passing now, just timing out on some of the builders.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
