### PR TITLE
cmark-gfm 0.29.0.gfm.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Standardese needs a revision bump

**Comment by carlocab** [comment]
```
  /tmp/standardese-20220825-17801-1p2zitu/src/comment/command-extension/command_extension.cpp:192:35: error: 'strlen' is not a member of 'std'; did you mean 'mbrlen'?
    192 |          const auto length = std::strlen(previous);
        |                                   ^~~~~~
        |                                   mbrlen
```
_sigh_ https://en.cppreference.com/w/cpp/string/byte/strlen

**Comment by carlocab** [comment]
`standardese` has had two installs on Linux in the past year: https://formulae.brew.sh/formula/standardese#default

I suggest not letting that delay this update if only Linux is failing.

**Comment by carlocab** [comment]
`standardese` is fixed by https://github.com/standardese/standardese/pull/233.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
