### PR TITLE
ghc: migrate to python@3.10

### PR DESCRIPTION
**Pull request by triallax**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
I wonder if we should update this to 9.0, as that seems to be the primary stable release of GHC now.

**Comment by mhmdanas** [comment]
@carlocab sounds good to me, but I think we can leave that to another PR?

**Comment by carlocab** [comment]
Rebuilding GHC is very expensive, so we should avoid multiple PRs that modify it.

**Comment by mhmdanas** [comment]
Fair enough.

**Comment by fishtreesugar** [comment]
> I wonder if we should update this to 9.0, as that seems to be the primary stable release of GHC now.

IMO, GHC 9.2.4 added [Deep Subsumption](https://downloads.haskell.org/~ghc/9.2.4/docs/html/users_guide/9.2.4-notes.html#compiler) which revert a behavior to GHC prior 9.0, so it could let project easier upgrade from GHC 8.10 to GHC 9.2

More Context:
- [Was simplified subsumption worth it for industry Haskell programmers?](https://www.reddit.com/r/haskell/comments/ujpzx3/was_simplified_subsumption_worth_it_for_industry/)
- [Deep Subsumption](https://github.com/ghc-proposals/ghc-proposals/pull/511)

**Comment by carlocab** [comment]
Ok, that's even better. So we're can rename `ghc@9` to `ghc`. And then add a `ghc@8.10` and/or `ghc@9.0` after if needed (but preferably not both).

**Comment by mhmdanas** [comment]
So, I should open a PR to rename `ghc@9` to `ghc`, with the 9.2.4 bump and the `python@3.10` migration. Did I get that right?

**Comment by mhmdanas** [comment]
See https://github.com/Homebrew/homebrew-core/pull/107589.

**Pull request closed without merging**
