### PR TITLE
telegraf 1.26.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
At a cursory glance at the error, might need to restrict this formula to Monterey or newer if can't resolve upstream: https://github.com/cosmos/cosmos-sdk/issues/11364

**Comment by p-linnane** [comment]
Looks like it built successfully on Big Sur Intel, but not arm64. Very strange.

**Comment by ZhongRuoyu** [comment]
I suggest patching the build for now. I don't think it's worth dropping Big Sur support. (I recall @nandahkrishna doing something similar in https://github.com/Homebrew/homebrew-core/pull/123899.)

I'm not sure how to patch the build without `go get shoenig/go-m1cpu@<revision>`, though. `go get` reported this, presumably because it is only in my fork currently:

```console
$ go get -v github.com/shoenig/go-m1cpu@c5eb86b693d9d4307d6b01e188c81163846ed032
go: github.com/shoenig/go-m1cpu@c5eb86b693d9d4307d6b01e188c81163846ed032: invalid version: unknown revision c5eb86b693d9d4307d6b01e188c81163846ed032
```

If we use `go get`, we may need to at least wait for https://github.com/shoenig/go-m1cpu/pull/6 to get meged.

**Review by nandahkrishna — COMMENTED** [review]
Agreed with @ZhongRuoyu (thanks for opening a PR upstream). Since the change is relatively simple, I think it isn't worth dropping support for Big Sur (though that's going to happen soon when the next macOS is out).

**Comment by shoenig** [comment]
Thanks for the fix @ZhongRuoyu, it is now in [v0.1.5](https://github.com/shoenig/go-m1cpu/releases/tag/v0.1.5)

**Comment by ZhongRuoyu** [comment]
Sorry for the noise above. It turned out that `*.mod` was in my global `gitignore` 😅.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
