### PR TITLE
unicorn: add option install python bindings

### PR DESCRIPTION
**Pull request by jonatanlinden**
The unicorn emulator provides bindings to several languages. I've added an option to installing the python bindings.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jonatanlinden** [comment]
Just checking in. Is there an opinion against adding options to packages? Alternatively, I could change the package so that the python bindings are installed by default on newer macOSes, and add an python dependency for older OSes.

**Comment by SMillerDev** [comment]
Since options aren't tested it's preferable to not have any options at all.

**Comment by jonatanlinden** [comment]
I've removed the option, the python binding is now installed by default and is tested.

**Comment by MikeMcQuaid** [comment]
@jonatanlinden This means the bindings will be built against the system Python 2. Are they still usable with the `python@2` formula if that's the case? Thanks!

**Comment by jonatanlinden** [comment]
@MikeMcQuaid Yes, that's the way I'm using them.

**Comment by MikeMcQuaid** [comment]
@jonatanlinden Perfect!

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @jonatanlinden for the pull request!

**Pull request closed without merging**
