### PR TITLE
texlab 3.1.0

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
@clason Please avoid merge commits in `homebrew/core`, use `git rebase` instead of `git merge` (if that's what you were trying to do).

**Comment by clason** [comment]
@nandahkrishna Oh, shoot, I didn't realize this commit made it into the PR. The changed github (and homebrew) UX around forks and PRs messed up my routine.

**Comment by clason** [comment]
That looks better. Sorry again!

**Comment by nandahkrishna** [comment]
No problem!

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
