### PR TITLE
brev 0.6.218

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not the latest release: https://github.com/brevdev/brev-cli/releases

**Comment by SMillerDev** [comment]
Is there a reason we're not checking GitHub releases?

**Comment by chenrui333** [comment]
> Is there a reason we're not checking GitHub releases?

it is because the complexity, we sort of talked about that before.

**Comment by samford** [comment]
It looks like they didn't create a 0.6.216 release either, despite having tagged it, so we can't rely on just the tags here. I'll create a separate PR to update the `livecheck` block to use `GithubLatest` (and add an explanatory comment), as it's necessary in this situation.

-----

> Is there a reason we're not checking GitHub releases?

Basically, if `stable` is a GitHub tag archive, we use the `Git` strategy unless/until the `GithubLatest` strategy is necessary.

At the moment, the `GithubLatest` strategy ends up fetching the "latest" release page HTML even if all we need is the `location` header from the redirect, so it's almost always heavier than the `Git` strategy. Some checks do need to match text in the HTML but we don't have a way of controlling the behavior until we've implemented a way of passing options to strategies (it's forthcoming).

More importantly, with the number of GitHub related checks in a homebrew/core and/or homebrew/cask livecheck run, there's a chance we may hit a rate limit if we used `GithubLatest` in all related formulae/casks. I'm not sure there's a published rate limit for unauthorized github.com requests but I vaguely remember seeing it in the homebrew/homebrew-livecheck days when we had more github.com checks (unrelated to GitHub API checks).

Lastly, there are some cases where the "latest" release on GitHub is regularly or periodically incorrect (e.g., repositories that maintain multiple major/minor versions and release them in an unpredictable order, etc.). In general, using `GithubLatest` as the default may be more likely to report an incorrect version than the `Git` strategy. I haven't tested this theory but it's my thinking from what I've seen when creating/fixing checks over the years.

We can revisit this thinking if/when `GithubLatest` simply fetches the `location` header (ideally, without following the redirection) but it may end up being more detrimental than beneficial overall (i.e., increasing our maintenance burden in comparison to the current approach of using `Git` by default and switching to `GithubLatest` as needed).

**Comment by p-linnane** [comment]
Closing since the `livecheck` was updated in https://github.com/Homebrew/homebrew-core/pull/128634.

**Pull request closed without merging**
