### PR TITLE
rtx: add head

### PR DESCRIPTION
**Pull request by jdx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x]  Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x]  Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x]  Have you built your formula locally with brew install --build-from-source <formula>, where <formula> is the name of the formula you're submitting?
- [x]  Is your test running fine brew test <formula>, where <formula> is the name of the formula you're submitting?
- [x]  Does your build pass brew audit --strict <formula> (after doing brew install --build-from-source <formula>)? If this is a new formula, does it pass brew audit --new <formula>?

this doesn't actually work for me. I dug into it but couldn't figure out why:

```
$ brew install --HEAD rtx
Error: No head is defined for rtx
```

I was hoping to add an easy way for users to install the latest trunk version of rtx, is this the best way to do it?

### CODE REVIEW

**Comment by nandahkrishna** [comment]
> I was hoping to add an easy way for users to install the latest trunk version of rtx, is this the best way to do it?

Yeah, `brew install --HEAD` requires `head` to be specified in the formula. We don't test these on CI though, so does it install successfully now?

**Comment by jdxcode** [comment]
it isn't working, but I can't seem to understand why. If I run `brew install --HEAD sccache`, that works, but `brew install --HEAD rtx` gives me this error.

I tried a few different syntax types but no luck. Do you see any reason why this formula wouldn't work with `--HEAD`?

**Comment by jdxcode** [comment]
this is my brew config:

```
HOMEBREW_VERSION: 4.0.3-47-g4e0a9b8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e0a9b87715cb5a79f65fab962e829a52cd60786
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8ab7cb0f6c013dba4442e2db5c82fa4a67023e81
Core tap last commit: 9 minutes ago
Core tap branch: master
Core tap JSON: 22 Feb 15:54 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: N/A
Xcode: 14.2
Rosetta 2: false
```

however since this works for sccache I doubt it's a local issue

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
I just did a local head test, working fine

```
$ brew test rtx
==> Testing rtx
==> /opt/homebrew/Cellar/rtx/HEAD-df1c322/bin/rtx install nodejs@18.13.0
==> /opt/homebrew/Cellar/rtx/HEAD-df1c322/bin/rtx exec nodejs@18.13.0 -- node -v
```

**Comment by chenrui333** [comment]
Thanks @jdxcode!

**Pull request merged**
