### PR TITLE
curl 7.69.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
This should already be merged: #51089.

**Comment by chenrui333** [comment]
Cool, cool!

**Comment by chenrui333** [comment]
Surprisingly, it did not show as merge conflict. Gonna file a github support ticket on this. 

Let's keep this a little bit.

**Comment by chenrui333** [comment]
Filed a support ticket.

Ticket ID: 590093

**Comment by chenrui333** [comment]
Give this PR another week (I will close it out later)

**Comment by Nemesis19** [comment]
please upgrade curl formula to 7.69.0-4 (see https://bugs.archlinux.org/task/65739)

**Comment by Bo98** [comment]
Is there a source package available? I only see 7.69.0 here: https://curl.haxx.se/download/. Looks like a Arch Linux specific thing.

Curl 7.69.1 will be released on Wednesday however: https://twitter.com/bagder/status/1236589069163008000

**Comment by Nemesis19** [comment]
@Bo98 thanks for the nice news! that bug causes segfaults to php scripts :(

**Comment by SMillerDev** [comment]
It does define a patch that needs to be applied. @Bo98 got time to apply those patches that arch references?

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/commit/14f7ddce84cf18873b642c7c941a9d0e0d3e8ee2
https://github.com/Homebrew/linuxbrew-core/commit/2d0699e933bc42fd36b7fcdbf5e2196146d8c040

**Comment by Bo98** [comment]
Yikes. Quite a few bugs in this one. I’ll get something together asap.

**Comment by Bo98** [comment]
Linux specific or not, it has been sorted: #51351.

**Comment by chenrui333** [comment]
Still did not receive any feedback from github support, however, it has been long enough for this PR. Closing it now.

**Pull request closed without merging**
