### PR TITLE
deno 1.7.5

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by Bo98** [comment]
Similar to 1.7.4, this version just doesn't build properly. Seems like they didn't backport the fix to 1.7.x unfortunately.

1.8.0 is due for release on Tuesday however.

**Comment by hoangph271** [comment]
> Similar to 1.7.4, this version just doesn't build properly. Seems like they didn't backport the fix to 1.7.x unfortunately.
> 
> 1.8.0 is due for release on Tuesday however.

Deno 1.8 released today, do you think this would be resolved soon...?

**Comment by Bo98** [comment]
Sure, I'll open a PR just now.

**Comment by Bo98** [comment]
#72365

**Pull request closed without merging**
