### PR TITLE
 apache-arrow, apache-arrow-glib 11.0.0

### PR DESCRIPTION
**Pull request by raulcd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by raulcd** [comment]
I am trying to update the hombrew formula for the new released Apache Arrow but I am facing the following issue when trying to build from source:
```
$ brew install --build-from-source apache-arrow
==> Fetching apache-arrow
==> Downloading https://www.apache.org/dyn/closer.lua?path=arrow/arrow-10.0.1/apache-arrow-10.0.1.tar.gz
Already downloaded: /home/raulcd/.cache/Homebrew/downloads/cc59c33af7102dc55ce2e400649b5e82667099445015b9b9f207cea003c369d2--apache-arrow-10.0.1.tar.gz
==> cmake -S cpp -B build -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE -DCMAKE_INSTALL_RPATH=$ORIGIN/../lib -DARROW_COMPUTE=ON -DARROW_CSV=ON -DARROW_DATASET=ON -DA
==> cmake --build build
==> cmake --install build
Error: Empty installation
```
I have tested both with linuxbrew and brew on macOS with the same result.
The full log for `cmake --install build` on linuxbrew can be seen here, which seems correct: https://gist.github.com/raulcd/62a51e39a527b484e33e4090c3a58401
@kou any idea what might be going on here?

**Comment by kou** [comment]
The log for `brew install --build-from-source apache-arrow` shows that you use Apache Arrow 10.0.1 not 11.0.0.
Is it intentional?

BTW, could you uninstall `apache-arrow` and `apache-arrow-glib` and try again?

**Comment by raulcd** [comment]
> The log for `brew install --build-from-source apache-arrow` shows that you use Apache Arrow 10.0.1 not 11.0.0. Is it intentional?
> 
> BTW, could you uninstall `apache-arrow` and `apache-arrow-glib` and try again?

I found that download log strange too because I do have the local changes with 11.0.0, see:
```
# uninstall apache-arrow and apache-arrow-glib (not installed)
$ brew uninstall apache-arrow
Uninstalling /home/linuxbrew/.linuxbrew/Cellar/apache-arrow/11.0.0... (561 files, 198.4MB)
$ brew uninstall apache-arrow-glib
Error: No such keg: /home/linuxbrew/.linuxbrew/Cellar/apache-arrow-glib
# Validate changes are correct:
$ pwd
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
$ cat Formula/apache-arrow.rb | grep 10.0.1
$ cat Formula/apache-arrow.rb | grep 11.0.0
  url "https://www.apache.org/dyn/closer.lua?path=arrow/arrow-11.0.0/apache-arrow-11.0.0.tar.gz"
  mirror "https://archive.apache.org/dist/arrow/arrow-11.0.0/apache-arrow-11.0.0.tar.gz"
# build-from-source
$ brew install --build-from-source apache-arrow 
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 1c85a71 to 10845a1.
No changes to formulae.

==> Fetching apache-arrow
==> Downloading https://www.apache.org/dyn/closer.lua?path=arrow/arrow-10.0.1/apache-arrow-10.0.1.tar.gz
Already downloaded: /home/raulcd/.cache/Homebrew/downloads/cc59c33af7102dc55ce2e400649b5e82667099445015b9b9f207cea003c369d2--apache-arrow-10.0.1.tar.gz
==> cmake -S cpp -B build -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE -DCMAKE_INSTALL_RPATH=$ORIGIN/../lib -DARROW_COMPUTE=ON -DARROW_CSV=ON -DARROW_DATASET=ON -DA
==> cmake --build build
==> cmake --install build
Error: Empty installation
```
Even though on the log says downloading 10.0.1 (which I don't know where is coming from) the logs show is building 11.0.0:
```
# Logs are from the current try
$ ls -lrt /home/raulcd/.cache/Homebrew/Logs/apache-arrow/
total 7388
-rw-rw-r-- 1 raulcd raulcd      12 ene 27 11:40 00.options.out
-rw-rw-r-- 1 raulcd raulcd  153346 ene 27 11:40 01.cmake.cc
-rw-rw-r-- 1 raulcd raulcd   28274 ene 27 11:40 01.cmake
-rw-rw-r-- 1 raulcd raulcd 6154055 ene 27 11:44 02.cmake.cc
-rw-rw-r-- 1 raulcd raulcd 1143420 ene 27 11:44 02.cmake
-rw-rw-r-- 1 raulcd raulcd   58318 ene 27 11:44 03.cmake
drwxrwxr-x 7 raulcd raulcd    4096 ene 27 11:44 build
$ cat /home/raulcd/.cache/Homebrew/Logs/apache-arrow/01.cmake | grep 10.0.1
$ cat /home/raulcd/.cache/Homebrew/Logs/apache-arrow/01.cmake | grep 11.0.0
-DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/apache-arrow/11.0.0
-- Arrow version: 11.0.0 (full: '11.0.0')
-- Arrow SO version: 1100 (full: 1100.0.0)
-- Found cpplint executable at /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/cpp/build-support/cpplint.py
-- Found hdfs.h at: /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/cpp/thirdparty/hadoop/include/hdfs.h
-- Found ORC static library: /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/build/orc_ep-install/lib/liborc.a
-- Found ORC headers: /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/build/orc_ep-install/include
-- Creating bundled static library target arrow_bundled_dependencies at /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/build/release/libarrow_bundled_dependencies.a
-- Arrow version:                                 11.0.0
--   Source directory: /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/cpp
--   Install prefix: /home/linuxbrew/.linuxbrew/Cellar/apache-arrow/11.0.0
--   Outputting build configuration summary to /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/build/cmake_summary.json
-- Build files have been written to: /tmp/apache-arrow-20230127-297429-1lbvo3/apache-arrow-11.0.0/build

```

**Comment by asmaloney** [comment]
I'm now seeing this "Error: Empty installation" on every formula which tries to compile itself ([detail here](https://github.com/orgs/Homebrew/discussions/4144)) or which I try to force to compile with `--build-from-source`.

This PR is the only other recent reference I've found about this error (and I haven't found an explanation of what it means), so I'm adding a link to my question to add another data point...

**Comment by gromgit** [comment]
@raulcd, `export HOMEBREW_NO_INSTALL_FROM_API=1` and try your local source build again.

**Comment by raulcd** [comment]
Thanks @gromgit that solved the issues. It seems the change of behavior based on https://github.com/Homebrew/brew/pull/14412 requires now to define the environment variable `HOMEBREW_NO_INSTALL_FROM_API=1`. I'll update our scripts.
I've been able to install, test and audit the updated formulas successfully. I am marking the PR as ready for review. I am not entirely sure why there are some cancelled CI runs though.

**Comment by raulcd** [comment]
I think we have to add the `long-build` label, right? @SMillerDev I saw you did it for the last release, can you add it? Sorry for pinging you directly

**Comment by SMillerDev** [comment]
Could you rebase this?

**Comment by raulcd** [comment]
@SMillerDev I've rebased and solved the conflict. It seems the label to run CI still needs to be added: ` Error: PR requires the CI-long-timeout label but it is not set!`. Many Thanks!

**Comment by raulcd** [comment]
I am not sure what the issue is on CI but the `postgis` and `pgrouting` issues doesn't seem related:
```
   running bootstrap script ... 2023-02-01 05:21:15.367 PST [22640] FATAL:  could not create shared memory segment: No space left on device
  2023-02-01 05:21:15.367 PST [22640] DETAIL:  Failed system call was shmget(key=1585955892, size=56, 03600).
  2023-02-01 05:21:15.367 PST [22640] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
  	The PostgreSQL documentation contains more information about shared memory configuration.
  child process exited with exit code 1
```

**Comment by raulcd** [comment]
@carlocab it seems to fail with ` Error: PR requires the CI-long-timeout label but it is not set!`. Is there anything I can do?

**Comment by kou** [comment]
I think that we just need to wait for a CI slot: https://github.com/Homebrew/homebrew-core/pull/114034#issuecomment-1299835270

**Comment by chenrui333** [comment]
triggering a rerun.

**Comment by chenrui333** [comment]
build failure

```
  -- stderr output is:
  CMake Error at cmake_modules/FindProtobuf.cmake:88 (message):
    Could not find Protobuf.  Looked in /opt/homebrew.
  Call Stack (most recent call first):
    cmake_modules/ThirdpartyToolchain.cmake:376 (find_package)
    CMakeLists.txt:141 (INCLUDE)
```

**Comment by kou** [comment]
Hmm. https://github.com/Homebrew/homebrew-core/actions/runs/4137339315/jobs/7162633355#step:6:183 is strange:

```text
  -- Providing CMake module for ProtobufAlt as part of Arrow CMake package
  -- pkg-config package for protobuf for static link isn't found
  -- Found protoc: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND
```

ProtoBuf isn't found. ProtoBuf isn't installed properly?

**Comment by chenrui333** [comment]
I don't see the same issue in my local?? Gonna make a new run, if still failure, gonna test in the action runner.

**Comment by chenrui333** [comment]
checkin in the action runner.

**Comment by chenrui333** [comment]
The root cause is with the openssl caused grpc++ cannot be found

```
bash-3.2$ pkg-config --cflags grpc++
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openssl', required by 'grpc', not found
```

**Comment by chenrui333** [comment]
> Hmm. https://github.com/Homebrew/homebrew-core/actions/runs/4137339315/jobs/7162633355#step:6:183 is strange:
> 
> ```
>   -- Providing CMake module for ProtobufAlt as part of Arrow CMake package
>   -- pkg-config package for protobuf for static link isn't found
>   -- Found protoc: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND
> ```
> 
> ProtoBuf isn't found. ProtoBuf isn't installed properly?

that is because of the openssl mixed dependencies.

I am still getting `FindProtobuf.cmake` issue, need upstream patch for this.

**Comment by chenrui333** [comment]
```
-- Found protoc: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND
```

that is also weird to me.

**Comment by chenrui333** [comment]
Just raised a PR to update `PROTOBUF_PROTOC_EXECUTABLE` arg

**Comment by kou** [comment]
> checkin in the action runner.

Thanks!!!

> ```text
> -- Found protoc: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND
> ```

Can we enable debug log?

```diff
diff --git a/Formula/apache-arrow.rb b/Formula/apache-arrow.rb
index 0fd4c186a2d..92d089eca73 100644
--- a/Formula/apache-arrow.rb
+++ b/Formula/apache-arrow.rb
@@ -44,6 +44,7 @@ class ApacheArrow < Formula
     ENV.runtime_cpu_detection if Hardware::CPU.intel?
 
     args = %W[
+      -DCMAKE_FIND_DEBUG_MODE=ON
       -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE
       -DCMAKE_INSTALL_RPATH=#{rpath}
       -DARROW_COMPUTE=ON
```

I think that an unexpected `FindProtobuf.cmake` is used in CI.

Ah, I got it. `FindProtobuf.cmake` in CMake isn't used. `protobuf-config.cmake` in ProtoBuf used instead because we specify `-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE`.

**Comment by kou** [comment]
`protobuf-config.cmake` is incompatible with `FindProtobuf.cmake` by default.

Can we try this?

```diff
diff --git a/Formula/apache-arrow.rb b/Formula/apache-arrow.rb
index 0fd4c186a2d..cc419eb6319 100644
--- a/Formula/apache-arrow.rb
+++ b/Formula/apache-arrow.rb
@@ -68,6 +68,7 @@ class ApacheArrow < Formula
       -DARROW_WITH_BROTLI=ON
       -DARROW_WITH_UTF8PROC=ON
       -DARROW_INSTALL_NAME_RPATH=OFF
+      -Dprotobuf_MODULE_COMPATIBLE=ON
     ]
 
     args << "-DARROW_MIMALLOC=ON" unless Hardware::CPU.arm?
```

I'll add support for `protobuf-config.cmake` in upstream but we may be able to this as a workaround for the next Apache Arrow release.

**Comment by kou** [comment]
Ah, it may not be a workaround for us...

**Comment by kou** [comment]
This may be a workaround:

```diff
diff --git a/Formula/apache-arrow.rb b/Formula/apache-arrow.rb
index 0fd4c186a2d..47bdfa18d54 100644
--- a/Formula/apache-arrow.rb
+++ b/Formula/apache-arrow.rb
@@ -44,7 +44,7 @@ class ApacheArrow < Formula
     ENV.runtime_cpu_detection if Hardware::CPU.intel?
 
     args = %W[
-      -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE
+      -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=OFF
       -DCMAKE_INSTALL_RPATH=#{rpath}
       -DARROW_COMPUTE=ON
       -DARROW_CSV=ON
```

**Comment by ZhongRuoyu** [comment]
Maybe, the option `-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE` can be dropped? A local build in Docker (`homebrew/ubuntu22.04`) confirmed that this solves the build issue for both 10.0.1 and 11.0.0.

For context, this flag was added in #62893 when `re2` was added as a dependency. I couldn't tell what the error was at that time, but `brew linkage apache-arrow` looks fine:

<details>
<summary>
<code>brew linkage apache-arrow</code> output
</summary>
<pre><code>System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib64/ld-linux-x86-64.so.2
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/opt/abseil/lib/libabsl_synchronization.so.2206.0.0 (abseil)
  /home/linuxbrew/.linuxbrew/Cellar/apache-arrow/10.0.1_5/lib/../lib/libarrow.so.1000 (apache-arrow)
  /home/linuxbrew/.linuxbrew/Cellar/apache-arrow/10.0.1_5/lib/../lib/libarrow_flight.so.1000 (apache-arrow)
  /home/linuxbrew/.linuxbrew/Cellar/apache-arrow/10.0.1_5/lib/../lib/libparquet.so.1000 (apache-arrow)
  /home/linuxbrew/.linuxbrew/opt/aws-sdk-cpp/lib/libaws-cpp-sdk-core.so (aws-sdk-cpp)
  /home/linuxbrew/.linuxbrew/opt/aws-sdk-cpp/lib/libaws-cpp-sdk-identity-management.so (aws-sdk-cpp)
  /home/linuxbrew/.linuxbrew/opt/aws-sdk-cpp/lib/libaws-cpp-sdk-s3.so (aws-sdk-cpp)
  /home/linuxbrew/.linuxbrew/opt/brotli/lib/libbrotlidec.so.1 (brotli)
  /home/linuxbrew/.linuxbrew/opt/brotli/lib/libbrotlienc.so.1 (brotli)
  /home/linuxbrew/.linuxbrew/opt/bzip2/lib/libbz2.so.1.0 (bzip2)
  /home/linuxbrew/.linuxbrew/opt/gcc/lib/gcc/current/libgcc_s.so.1 (gcc)
  /home/linuxbrew/.linuxbrew/opt/gcc/lib/gcc/current/libstdc++.so.6 (gcc)
  /home/linuxbrew/.linuxbrew/opt/gflags/lib/libgflags.so.2.2 (gflags)
  /home/linuxbrew/.linuxbrew/opt/grpc/lib/libgpr.so.29 (grpc)
  /home/linuxbrew/.linuxbrew/opt/grpc/lib/libgrpc++.so.1.51 (grpc)
  /home/linuxbrew/.linuxbrew/opt/grpc/lib/libgrpc.so.29 (grpc)
  /home/linuxbrew/.linuxbrew/opt/lz4/lib/liblz4.so.1 (lz4)
  /home/linuxbrew/.linuxbrew/opt/ncurses/lib/libncursesw.so.6 (ncurses)
  /home/linuxbrew/.linuxbrew/opt/protobuf/lib/libprotobuf.so.32 (protobuf)
  /home/linuxbrew/.linuxbrew/opt/re2/lib/libre2.so.10 (re2)
  /home/linuxbrew/.linuxbrew/opt/snappy/lib/libsnappy.so.1 (snappy)
  /home/linuxbrew/.linuxbrew/opt/thrift/lib/libthrift-0.17.0.so (thrift)
  /home/linuxbrew/.linuxbrew/opt/utf8proc/lib/libutf8proc.so.2 (utf8proc)
  /home/linuxbrew/.linuxbrew/opt/zlib/lib/libz.so.1 (zlib)
  /home/linuxbrew/.linuxbrew/opt/zstd/lib/libzstd.so.1 (zstd)
Indirect dependencies with linkage:
  abseil
  gflags
  ncurses
  zlib
Dependencies with no linkage:
  glog
  rapidjson
</code></pre>
</details>

**Comment by SMillerDev** [comment]
Let's try that

**Comment by carlocab** [comment]
Cherry-picked onto #123507.

**Pull request closed without merging**
