### PR TITLE
ldc: update to 1.25.0

### PR DESCRIPTION
**Pull request by Geod24**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Geod24** [comment]
@p0nce: Are you interested in adding support for ARM to the recipe ?

**Comment by Bo98** [comment]
I think the `libLLVM` workaround can be removed with this version.

**Comment by Geod24** [comment]
I thought so too, but the tests failed.

**Review by carlocab — APPROVED** [review]
Thanks, @Geod24.

**Comment by Geod24** [comment]
Missing dependency on `pkg-config`, will submit a fix soon

**Comment by carlocab** [comment]
Yup, I had seen the build log; just forgot to add it to my PR.

**Comment by p0nce** [comment]
Hello @Geod24 , not using Homebrew but can sponsor the effort if you'd like to do it? (D Foundation donation or else)
Also the prebuilt x86_64 cross-compile to arm64 too and iphone so it's the most useful package right now.
The arm64 native LDC also won't work in previous versions of macOS, so right now it's a better experience to just get the x86_64 LDC?

**Comment by Geod24** [comment]
@p0nce : So far @calocab has made the changes required for ARM.
Regarding using the upstream-distributed binaries, I wouldn't be against, but it doesn't seem like something we'll do: https://github.com/ldc-developers/ldc/issues/3670#issuecomment-782957069

**Pull request closed without merging**
