### PR TITLE
cdktf remove depenecy on terraform

### PR DESCRIPTION
**Pull request by cmclaughlin**
I use tfenv to manage multiple installations/versions of terraform.
And I'd like to use homebrew to install cdktf, but it has a hard
depenecy on terraform. This PR removes that depenency.

I think it would be better to have some sort of optional or
recommended depency on terraform or tfenv, but I don't see a way
to do that with homebrew - please correct me if I'm wrong.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by cmclaughlin** [comment]
fyi @theabrar @anubhavmishra @chenrui333 since you worked on the original PR #60113

**Comment by SMillerDev** [comment]
Does it run without a terraform install? Cause otherwise this isn't gonna be merged. The idea is that a clean install will be working, if you want different dependencies your best option is to maintain a tap.

**Comment by cmclaughlin** [comment]
Technically yes is it would install... if that's what you mean by run, but ultimately no... `cdktf` would fail with errors :)

This is my first attempt at a commit to Homebrew, so I'm not sure about maintainging a tap. I'd probably just close the PR and move on to something else more fun and interesting.

If dropping the dependency is a problem, any objection to simply switching it to tfenv?

**Comment by SMillerDev** [comment]
If I buy a new Mac today and run `brew install cdktf` and then `cdktf`, or whatever command it installs, it needs to be fully functional as the developers intended it. So throwing errors or setting up a terraform environment is unfortunately not acceptable.


Hosting a personal tap, is very easy to do though: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by cmclaughlin** [comment]
So it sounds like there's no way for an or condition on the dependencies like yum, apt, etc.
I went ahead and pushed another commit to switch the dependency from terraform to tfenv - anyone using terraform at scale for more than a couple months will find that's the best practice. Feel feel to close out the PR though if you don't want to go that route.

**Comment by SMillerDev** [comment]
Thanks for the pull request but I think we're going to stay with the "official" dependency.

**Pull request closed without merging**
