### PR TITLE
openjdk 23

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Testing the final release candidate [^1][^2] before Sequoia mass bottling eats up CI resources.

[^1]: https://openjdk.org/projects/jdk/23/
[^2]: https://mail.openjdk.org/pipermail/jdk-dev/2024-August/009341.html

---

Update: The final release candidate (`jdk-23+37`), tested in https://github.com/Homebrew/homebrew-core/pull/182295#issuecomment-2312529800, is identical to the general-availability release (`jdk-23-ga`).

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
## Test failures

- [ ] `brew test --retry --verbose bbtools`: `BuildError: Failed executing: /usr/local/Cellar/bbtools/39.08/bin/uk.sh` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:1157))
- [ ] `brew test --retry --verbose parquet-cli`: `java.lang.UnsupportedOperationException: getSubject is supported only if a security manager is allowed` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:4659))
- [ ] `brew test --retry --verbose scala`: `Error: 23 is not a valid choice for -java-output-version` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:5583))

## Build failures

- [ ] (14-x86_64) `brew install --build-from-source bigloo`: `error: incompatible function pointer types` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:1400))
- [ ] `brew install --build-from-source opensearch`: `error: reference not found` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:4409))
- [ ] (x86_64) `brew install --build-from-source teku`: `Some library licenses are not allowed.` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:6320))

## Source fetch failures

- [x] `brew fetch --build-from-source --retry ammonite-repl`: `Formula reports different sha256` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:594)); #182409
- [ ] `brew fetch --build-from-source --retry bbtools`: `Formula reports different sha256` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:1134))
- [ ] `brew fetch --build-from-source --retry csound gmp libunistring libidn2 libtasn1 nettle p11-kit libevent libnghttp2 unbound gnutls libmicrohttpd libogg flac lame libvorbis mpg123 opus libsndfile z3 llvm faust fltk portaudio fluid-synth isl mpfr libmpc gcc libaec pkg-config hdf5 berkeley-db@5 libsamplerate aften jack liblo libuv libwebsockets openblas numpy portmidi stk wiiuse`: ``Error: Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/flac/flac-1.4.3.tar.xz`` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:1966))
- [ ] `brew fetch --build-from-source --retry joern brotli c-ares libnghttp2 libuv node astgen gmp coreutils apr apr-util argon2 aspell m4 autoconf libunistring libidn2 libssh2 rtmpdump curl libtool unixodbc freetds highway imath openexr webp jpeg-xl libvmaf aom libavif gd krb5 libpq libsodium libzip oniguruma openldap tidy-html5 php`: ``Error: Download failed: Homebrew-installed `curl` is not installed for: https://www.freetds.org/files/stable/freetds-1.4.22.tar.bz2`` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:3338))
- [ ] `brew fetch --build-from-source --retry octave eigen gmp isl mpfr libmpc gcc hwloc libevent pmix open-mpi openblas arpack jbig2dec libidn openjpeg ghostscript epstool fftw jasper netpbm fig2dev fltk gl2ps glpk brotli highway imath openexr webp jpeg-xl libvmaf aom libde265 shared-mime-info x265 libheif m4 libtool graphicsmagick libaec pkg-config hdf5 libogg flac lame libvorbis mpg123 opus libsndfile portaudio liblqr libomp libraw imagemagick plotutils pstoedit qhull qrupdate assimp dbus double-conversion hunspell libb2 libmng md4c qt pyqt qscintilla2 rapidjson metis suite-sparse sundials texinfo`: `Error: Failed to download resource "netpbm"` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:4188))
- [ ] `brew fetch --build-from-source --retry plantuml brotli highway imath openexr webp jpeg-xl libvmaf aom libavif gd jasper netpbm gts gdk-pixbuf fribidi pango librsvg m4 libtool graphviz`: `Error: Failed to download resource "netpbm"` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:5029))

## Unrelated failures

- [ ] `brew install --build-from-source bbot`: `ModuleNotFoundError: No module named 'setuptools.extern'` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070708#step:3:1046))
- [ ] `brew install texlive`: `No space left on device` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/10539878948/job/29205070604#step:4:2853))

**Comment by calvinit** [comment]
[jdk-23-ga](https://github.com/openjdk/jdk/releases/tag/jdk-23-ga) already released!

**Comment by calvinit** [comment]
Why is there no two checks of `CI / macOS 15-x86_64 (pull_request)` and `CI / macOS 15-x86_64 (deps) (pull_request)`? @ZhongRuoyu

**Comment by ZhongRuoyu** [comment]
The final release is identical to the final release candidate tested earlier, so all problems seen in [the latest run](https://github.com/Homebrew/homebrew-core/actions/runs/10914911237?pr=182295) have been already covered in previous test (minus several HTTP 403 failures connecting to Maven, which seem to be transient as they work now):

`scala` fails because it [doesn't seem to support JDK 23 yet](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#jdk-23-compatibility-notes). This will be handled by #191248.

`opensearch` and `teku` failures appear to be build-only issues with JDK 23 (specifically, with Javadoc and build-time checks respectively). Can look into this as a follow-up but the existing bottles should still work.

**Comment by ZhongRuoyu** [comment]
https://github.com/Homebrew/homebrew-core/labels/ready%20to%20merge after #191248.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
