### PR TITLE
lumo 1.8.0-beta

### PR DESCRIPTION
**Pull request by anmonteiro**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
00:13:42   * Devel: version 1.8.0-beta is redundant with version scanned from URL
00:13:45 C: 15:  1: Inconsistent indentation detected.
00:13:45 W: 19:  3: end at 19, 2 is not aligned with devel do at 15, 0.
```

**Comment by anmonteiro** [comment]
@fxcoudert happy to fix these, but it's not clear to me what the first warning is saying?

Should I just delete the `version ` line entirely?

**Comment by fxcoudert** [comment]
Yes, delete the `version` line, and squash all your changes into one commit please.

**Comment by anmonteiro** [comment]
Done!

**Comment by anmonteiro** [comment]
Any development on this? Is the build just queued?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @anmonteiro!

**Pull request merged**
