### PR TITLE
xcode-kotlin 1.3.1

### PR DESCRIPTION
**Pull request by TadeasKriz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by TadeasKriz** [comment]
Closed by mistake (thought we didn't bump version in sources, but it got bumped in a merge commit)

**Comment by iMichka** [comment]
This is not marked as the latest release upstream: https://github.com/touchlab/xcode-kotlin/releases

**Comment by TadeasKriz** [comment]
Thanks @iMichka, release created. It's been a long time since I've done a release and forgot the process, need to document it in the project 😬

**Review by bevanjkay — APPROVED** [review]

**Comment by chenrui333** [comment]
> Thanks @iMichka, release created. It's been a long time since I've done a release and forgot the process, need to document it in the project 😬

or maybe better automate it :)

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
