### PR TITLE
Remove in-formula 10.13 SDK Autotools hacks

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Follow-up to https://github.com/Homebrew/brew/pull/3196.

### CODE REVIEW

**Review by ilovezfs — COMMENTED** [review]
Wait for > brew 1.3.3 to ship.

**Comment by apjanke** [comment]
brew 1.3.3 has shipped. Can this go in now?

**Comment by ilovezfs** [comment]
No, > 1.3.3 (i.e. 1.3.4 or 1.4.0) needs to ship.

**Comment by apjanke** [comment]
Oh, sorry; misread that ">" as an arrow or list item bullet.

**Pull request merged**
