### PR TITLE
curl 7.78.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by SMillerDev** [comment]
I doubt this is curl related
```
==> Testing pyflow
==> /home/linuxbrew/.linuxbrew/Cellar/pyflow/0.3.1/bin/pyflow init
==> /home/linuxbrew/.linuxbrew/Cellar/pyflow/0.3.1/bin/pyflow install requests
Found lockfile
thread 'main' panicked at 'Can't find a valid version for charset-normalizer', src/dep_resolution.rs:396:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==> Testing pyflow (again)
==> /home/linuxbrew/.linuxbrew/Cellar/pyflow/0.3.1/bin/pyflow init
==> /home/linuxbrew/.linuxbrew/Cellar/pyflow/0.3.1/bin/pyflow install requests
Found lockfile
thread 'main' panicked at 'Can't find a valid version for charset-normalizer', src/dep_resolution.rs:396:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by carlocab** [comment]
It's not. That's been broken few a few different PRs already. It's also broken if you test `pyflow` in a Docker container without this version bump.

Merging.

**Comment by carlocab** [comment]
@branchvincent would you happen to know anything about the `pyflow` failure on Linux? We've seen this across a few PRs already.

**Comment by branchvincent** [comment]
> @branchvincent would you happen to know anything about the `pyflow` failure on Linux? We've seen this across a few PRs already.

@carlocab i don't but i will certainly look into it when a get a chance (hopefully later today)

**Pull request closed without merging**
