### PR TITLE
jansson 2.13.1

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by Moisan** [comment]
@chenrui333 please don't approve the PR unless the CI is green.

**Comment by SMillerDev** [comment]
Either the homebrew repo stopped existing or its a fluke. @Moisan Can you cancel and restart the job?

**Comment by chenrui333** [comment]
> @chenrui333 please don't approve the PR unless the CI is green.

noted!

**Comment by chenrui333** [comment]
This is certainly GHA flakiness.
```
From https://github.com/Homebrew/homebrew-core
 * branch                    master     -> FETCH_HEAD
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
##[error]Process completed with exit code 128.
```

**Comment by chenrui333** [comment]
Just did the re-run.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Looks green now 🎉

**Pull request closed without merging**
