### PR TITLE
fb303 fbthrift fizz folly wangle watchman 2022.05.16.00

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Folly patch needs to be removed.

**Comment by alebcay** [comment]
`fbthrift` build failure on Catalina:
```
  [ 14%] Building CXX object thrift/compiler/CMakeFiles/compiler_base.dir/parse/lexer.cc.o
  cd /tmp/fbthrift-20220519-10211-1306wff/fbthrift-2022.05.16.00/build/shared/thrift/compiler && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFMT_LOCALE -DFMT_SHARED -DTHRIFTY_HH=\"/tmp/fbthrift-20220519-10211-1306wff/fbthrift-2022.05.16.00/build/shared/thrift/compiler/thrifty.hh\" -DTHRIFT_HAVE_LIBSNAPPY=0 -Dcompiler_base_EXPORTS -I/tmp/fbthrift-20220519-10211-1306wff/fbthrift-2022.05.16.00 -I/tmp/fbthrift-20220519-10211-1306wff/fbthrift-2022.05.16.00/build/shared -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=c++17 -MD -MT thrift/compiler/CMakeFiles/compiler_base.dir/parse/lexer.cc.o -MF CMakeFiles/compiler_base.dir/parse/lexer.cc.o.d -o CMakeFiles/compiler_base.dir/parse/lexer.cc.o -c /tmp/fbthrift-20220519-10211-1306wff/fbthrift-2022.05.16.00/thrift/compiler/parse/lexer.cc
  /tmp/fbthrift-20220519-10211-1306wff/fbthrift-2022.05.16.00/thrift/compiler/source_location.cc:51:22: error: use of undeclared identifier 'errno'
      int error_code = errno;
                       ^
  1 error generated.
  make[2]: *** [thrift/compiler/CMakeFiles/compiler_base.dir/source_location.cc.o] Error 1
```

**Comment by carlocab** [comment]
That reads like a missing `#include <errno.h>`, but why would it only happen on Catalina?

**Comment by alebcay** [comment]
Knowing macOS, I'm not too surprised. In https://github.com/Homebrew/homebrew-core/pull/101522, we found that prior to Monterey, `<cstring>`/`<string.h>` was not needed for `strcpy`/`strlen` (these were available without the header in Big Sur and Catalina).

It's possible that they "fixed" it after Catalina so that `<errno.h>` isn't needed, who knows. 🤷

**Comment by carlocab** [comment]
Ok, let's try adding that `#include`. Will upstream the patch if it works.

**Comment by carlocab** [comment]
Upstream PR: facebook/fbthrift#500.

Will replace the in-line patch with the one from my PR when the 10.15 runner finishes.

**Review by SMillerDev — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
The audit failure for `wangle` is spurious. It wasn't there when the patch was inlined.

**Pull request closed without merging**
