### PR TITLE
mvtools 14

### PR DESCRIPTION
**Pull request by ilovezfs**
needed upstream commit "Depan: fix compilation with clang/libc++"

### CODE REVIEW

**Comment by ilovezfs** [comment]
This compiles with gcc but not clang. The regression occurred in https://github.com/dubhater/vapoursynth-mvtools/commit/10c370e19968fef2235e17eb9bad6b3431d46697, and when this commit is reverted, it compiles with clang again.

**Comment by ilovezfs** [comment]
Reported https://github.com/dubhater/vapoursynth-mvtools/issues/27

**Comment by ilovezfs** [comment]
OK, upstream fixed it for us.

**Comment by DomT4** [comment]
👍. Another helpful upstream, we're on a roll this week.

**Pull request closed without merging**
