### PR TITLE
knot-resolver service fails to start

### PR DESCRIPTION
**Pull request by bigsweater**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The paths for knot-resolver have changed from `kresd` to `knot-resolver`:

https://github.com/CZ-NIC/knot-resolver/blob/master/meson.build#L47-L62

...so the formula's LaunchDaemon crashes. (`brew services list` still shows `knot-resolver` as started, however.) This corrects the file references in the `plist`.

## Re-creating the bug

1. `brew install knot-resolver`
1. `tail -f /var/log/system.log`
1. `sudo brew services start knot-resolver`.
  `system.log` will show a failure:
  `Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /usr/local/var/kresd: 20B29: xpcproxy + 23862 [673][E1C74752-9AA7-343F-88EA-2ADD1A373AC5]: 0x2`
  That makes sense since the `/usr/local/var/kresd` directory is never created.

This also replaces the `-f` flag in the `kresd` command with `-n` ("noninteractive mode") since [`-f` has apparently been deprecated](https://manpages.debian.org/testing/knot-resolver/kresd.8.en.html). I'm not sure if this will have some unintended consequences but it seems to work okay on my system.

`kresd` still crashes even after the formula is fixed because it tries to bind to an IPv6 address, but maybe that depends on the system? Removing IPv6 from the configuration file fixes the issue.

Should this formula publish its own kresd.conf, sans IPv6 bindings, similar to how [the knot formula publishes its own configuration](https://github.com/Homebrew/homebrew-core/blob/1a60e2e6309cd922b8dc50cd514472daa71b5fb2/Formula/knot.rb#L55-L80)?

### CODE REVIEW

**Comment by SMillerDev** [comment]
The test should be improved to catch this next time. And the stderr path should be changed as well.

**Comment by bigsweater** [comment]
@SMillerDev Updated the log path to `knot-resolver.log`. The test also now checks for the existence of the workdir for the `plist`. Not sure if that's the best way to go about it!

I tried to write a more robust test for the `kresd` binary itself by starting a daemon, sort of how the nginx formula does it -- but kresd requires write access to its root.keys file in its own Cellar directory to even boot up:

```
❯ brew test knot-resolver
==> Testing knot-resolver
==> kresd -c /private/tmp/knot-resolver-test-20201210-64212-ygx9kt/kresd.conf -n /private/tmp/knot-resolver-test-20201210-64212-ygx9kt
Last 15 lines from /Users/vincent/Library/Logs/Homebrew/knot-resolver/test.01.kresd:
2020-12-10 13:25:36 -0500

kresd
-c
/private/tmp/knot-resolver-test-20201210-64212-ygx9kt/kresd.conf
-n
/private/tmp/knot-resolver-test-20201210-64212-ygx9kt

[warn] Knot Resolver is tested on Linux, other platforms might exhibit bugs.
Please report issues to https://gitlab.nic.cz/knot/knot-resolver/issues/
Thank you for your time and interest!
[system] error ...not-resolver/5.2.0_1/lib/knot-resolver/trust_anchors.lua:319: [ ta ] ERROR: write access needed to keyfile dir '/usr/local/Cellar/knot-resolver/5.2.0_1/etc/knot-resolver/root.keys'
```

**Comment by SMillerDev** [comment]
That's a weird place to write regardless of testability. Is there a way to set this location to something else?

**Comment by bigsweater** [comment]
Yeah it's weird. It took some digging to figure it out, but it looks like that option is set at build time by a file called `sandbox.lua`, which is produced during the build process. `sandbox.lua` is loaded _before_ the user's own config.

Hand-editing the `sandbox.lua` file to tell it the `root.keys` file is readonly fixes the test. 

Since `sandbox.lua` is produced at build time, would it make sense to update build options (in [meson_options.txt](https://github.com/CZ-NIC/knot-resolver/blob/08e3991fcb2ed76383e32943b89d2f4db0431cff/meson_options.txt#L11-L21)) to set the key file as readonly? 

I don't know enough about knot-resolver to know if that would impact end users. (I'm not a lua, meson, Knot Resolver, or really any other type of relevant expert here so all of this could be way off!)

It's worth noting that [you *can* supply your own key files](https://knot-resolver.readthedocs.io/en/stable/config-dnssec.html#trust_anchors.add_file) -- it just seems like it's always going to try to load the included `root.keys` first, no matter what.

**Review by SMillerDev — APPROVED** [review]
Thanks @bigsweater  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
