### PR TITLE
aspectj: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by carlocab**
See #75943.

### CODE REVIEW

**Comment by carlocab** [comment]
```
aspectj:
  * Stable: The source URL https://www.eclipse.org/downloads/download.php?r=1&file=/tools/aspectj/aspectj-1.9.6.jar is not reachable
```

**Comment by carlocab** [comment]
```
❯ sha256sum *.tar.gz
9036e23d27a962cc4716f3cc099c70d4739c404e4a109e87d354fc9a1c7d21a6  aspectj--1.9.6_1.arm64_big_sur.bottle.tar.gz
1bb26ecae448ad7803d0060355eea1880f56bcf36f081386a3558ed4ba952586  aspectj--1.9.6_1.big_sur.bottle.tar.gz
7e4efef88211224d798271e88dd9da813bdeb90460c5c30331d31518385ae491  aspectj--1.9.6_1.catalina.bottle.tar.gz
3cc17f269ce370ad843e6b5ef675c06d4bb4b48556deb241fc9c3ff698204a42  aspectj--1.9.6_1.mojave.bottle.tar.gz
```
All different. Weird.

**Comment by MikeMcQuaid** [comment]
@carlocab: I think it's good to fix this stuff up but I don't think it should block these PRs. We can make these fixes after stuff is bottled.

**Comment by carlocab** [comment]
I agree. That's why I removed the `do not merge` label; was just waiting for a second opinion. Will merge this, as the Mojave failure looks like a temporary network error.

**Pull request closed without merging**
