### PR TITLE
augustus 3.3.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
```
cd bam2wig; make;
gcc -Wall -O2 -I/private/tmp/augustus-20180515-4340-so6at/augustus-3.3.1/.brew_home/tools/samtools/ -I. -I/private/tmp/augustus-20180515-4340-so6at/augustus-3.3.1/.brew_home/tools/htslib/ -I/private/tmp/augustus-20180515-4340-so6at/augustus-3.3.1/.brew_home/tools/bcftools/ -I/private/tmp/augustus-20180515-4340-so6at/augustus-3.3.1/.brew_home/tools/tabix/ -c bam2wig.c -o bam2wig.o
bam2wig.c:18:10: fatal error: 'sam.h' file not found
#include "sam.h"
```
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/24119/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_augustus/

@suujia Hi, Susie. Could you please look into bumping Augustus to version 3.3.1 and addressing the above build error message on macOS?

**Comment by mistydemeo** [comment]
@suujia Hi! Just checking in to see if you've had any chance to look at this.

**Comment by suujia** [comment]
#include "sam.h" is in `"auxprogs/bam2wig/"` and `auxprogs/checkTargetSortedness/`

the main **README file** says: 
```
Compiling bam2wig requires:

   -htslib
   -bcftools
   -tabix
   -samtools
   For bam2wig, these four packages must be installed from github. An installation via Ubuntu packages is not sufficient.
```
and the **bam2wig github** says: `samtools <http://www.htslib.org/> is a required dependency. Install
    samtools to your PATH before running bam2wig.`

so perhaps it might be helpful to add `depends_on "samtools"`

========== 

```
    # Fix error: api/BamReader.h: No such file or directory
    inreplace "auxprogs/bam2hints/Makefile",
      "INCLUDES = /usr/include/bamtools",
      "INCLUDES = #{Formula["bamtools"].include/"bamtools"}"
```
 going off of the above fix (from history), we can do: 
```
    inreplace "auxprogs/bam2wig/Makefile",
      "INCLUDES = /usr/include/samtools",
      "INCLUDES = #{Formula["samtools"].include/"samtools"}"
```



error: 

```
Error: inreplace failed
auxprogs/bam2wig/Makefile:
  expected replacement of "INCLUDES = /usr/include/bamtools" with "INCLUDES = /home/{myusr}/.homebrew/opt/bamtools/include/bamtools"
```

**Comment by sjackman** [comment]
`auxprogs/bam2wig/` is not present in Augustus 3.3. It was added in Augustus 3.3.1.
`auxprogs/bam2wig/`requires `sam.h` and `bam.h`, which appear to be from an ancient legacy version of samtools 0.1.x. We could consider vendoring samtools 0.1.x into `augustus`.

I'd recommend not building `auxprogs/bam2wig/`. I do not believe it's core functionality of Augustus. We can reconsider this later if someone were to claim they needed this functionality.

The following patch works:
```diff
diff --git a/Formula/augustus.rb b/Formula/augustus.rb
index 00aa01625e..c95ef9b18e 100644
--- a/Formula/augustus.rb
+++ b/Formula/augustus.rb
@@ -1,9 +1,8 @@
 class Augustus < Formula
   desc "Predict genes in eukaryotic genomic sequences"
   homepage "http://bioinf.uni-greifswald.de/augustus/"
-  url "http://bioinf.uni-greifswald.de/augustus/binaries/augustus-3.3.tar.gz"
-  sha256 "b5eb811a4c33a2cc3bbd16355e19d530eeac6d1ac923e59f48d7a79f396234ee"
-  revision 1
+  url "http://bioinf.uni-greifswald.de/augustus/binaries/augustus-3.3.1.tar.gz"
+  sha256 "e0249bff0345f6a790b5c56432f292040254457da22f1a2c212f42d7d2104087"
 
   bottle do
     sha256 "6ffeac4edd4805321ea0957959f85da8cc1f5978cdc8a98903a78c407d5d183e" => :high_sierra
@@ -15,6 +14,9 @@ class Augustus < Formula
   depends_on "boost"
 
   def install
+    # Fix error: 'sam.h' file not found
+    inreplace "auxprogs/Makefile", "cd bam2wig; make;", "#cd bam2wig; make;"
+
     # Fix error: api/BamReader.h: No such file or directory
     inreplace "auxprogs/bam2hints/Makefile",
       "INCLUDES = /usr/include/bamtools",
```

@suujia Could you please open a PR with this fix?

**Comment by suujia** [comment]
Yes! Sounds good, thanks. I will do that. 

Side note though, I did check before and again just now and the file`auxprogs/bam2wig/` does exist on augustus 3.3

**Comment by sjackman** [comment]
Ah, you're right, it did exist; it just wasn't built by default previously.
```diff
diff --git a/augustus-3.3/auxprogs/Makefile b/augustus-3.3.1/auxprogs/Makefile
index b7ce475..88cef4a 100644
--- a/augustus-3.3/auxprogs/Makefile
+++ b/augustus-3.3.1/auxprogs/Makefile
@@ -9,9 +9,13 @@ all:
 	cd filterBam; make;
 	cd homGeneMapping; make;
 	cd joingenes; make;
+	cd bam2wig; make;
+	cd utrrnaseq/Debug; make all;
 clean:
 	cd bam2hints; make clean;
 	cd compileSpliceCands; make clean;
 	cd filterBam; make clean;
 	cd homGeneMapping; make clean;
 	cd joingenes; make clean;
+	cd bam2wig; make clean;
+	cd utrrnaseq/Debug; make clean;
```

**Comment by sjackman** [comment]
Thanks, Susie!

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/29323

**Pull request closed without merging**
