### PR TITLE
jupyterlab 3.5.3

### PR DESCRIPTION
**Pull request by singingwolfboy**
Replacement for #121353 -- let's see if this works!

### CODE REVIEW

**Comment by chenrui333** [comment]
Thanks @singingwolfboy!! ❤️ I am trying this PR in my local as well.

**Comment by chenrui333** [comment]
```
/opt/homebrew/opt/hatch/bin/hatch
build
-t
wheel

Field `build-system.build-backend` must be set to `hatchling.build`
```

**Comment by singingwolfboy** [comment]
I think this is finally working!

**Comment by miccal** [comment]
Thank you @singingwolfboy.

**Review by miccal — DISMISSED** [review]

**Comment by singingwolfboy** [comment]
@chenrui333 is this ready to be merged, or does it need anything else?

**Comment by chenrui333** [comment]
Thanks @singingwolfboy!!

**Pull request closed without merging**
