### PR TITLE
serialosc 1.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
wait for https://github.com/monome/serialosc/releases/latest

**Comment by artfwo** [comment]
Hey @ilovezfs, could you also create a PR for libmonome 1.4.1? Thanks!

**Comment by ilovezfs** [comment]
@artfwo I already shipped libmonome 1.4.1 in https://github.com/Homebrew/homebrew-core/pull/22994

**Comment by artfwo** [comment]
@ilovezfs wow, that was super fast, thanks!

**Comment by ilovezfs** [comment]
@artfwo you're welcome! Is serialosc 1.4.1 (this PR) still pre-release or do you want it shipped too?

**Comment by artfwo** [comment]
@ilovezfs serialosc 1.4.1 should be safe to ship in Homebrew. it's marked as pre-release, because the binary installers need a final check.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@artfwo shipped!

**Comment by artfwo** [comment]
:+1:

**Pull request closed without merging**
