### PR TITLE
traefik 2.3.0

### PR DESCRIPTION
**Pull request by djerfy**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/traefik/2.3.0/bin/traefik version 2>&1
Error: traefik: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </2\.3\.0/> was expected to be =~
<"Version:      dev\n" +
"Codename:     cheddar\n" +
"Go version:   go1.15.2\n" +
"Built:        I don't remember exactly\n" +
"OS/Arch:      darwin/amd64\n">.
```

**Comment by chenrui333** [comment]
looks like the version did not get consumed.

**Comment by djerfy** [comment]
> looks like the version did not get consumed.

Github repository has been renamed, update done (manually test on my laptop)

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
I see, make sense 👍  Thanks!

**Pull request closed without merging**
