### PR TITLE
git-town 4.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@charlierudolph it looks like the vendor directory or glide files are incomplete:
```
==> go build -o /usr/local/Cellar/git-town/4.2.0/bin/git-town
src/github.com/Originate/git-town/vendor/golang.org/x/oauth2/oauth2.go:18:2: cannot find package "golang.org/x/net/context" in any of:
	/private/tmp/git-town-20170815-82204-1shrnud/git-town-4.2.0/src/github.com/Originate/git-town/vendor/golang.org/x/net/context (vendor tree)
	/usr/local/Cellar/go/1.8.3/libexec/src/golang.org/x/net/context (from $GOROOT)
	/private/tmp/git-town-20170815-82204-1shrnud/git-town-4.2.0/src/golang.org/x/net/context (from $GOPATH)
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by charlierudolph** [comment]
Thanks for the heads up @ilovezfs, you can go ahead and close this. I'll release 4.2.1 with a fix

**Comment by charlierudolph** [comment]
4.2.1 released

**Comment by charlierudolph** [comment]
Thanks @ilovezfs

**Pull request closed without merging**
