### PR TITLE
swift-format 510.0.1

### PR DESCRIPTION
**Pull request by emauricio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by emauricio** [comment]
Hello there, I need a little help flagging this one 
https://github.com/Homebrew/homebrew-core/pull/166269 

same changes but i closed because bump_pr failed to created the PR due to the repo being https instead ssh, and pushing it manually did not work. 

thank you.

**Comment by Bo98** [comment]
There's some issues with this release: https://github.com/apple/swift-format/issues/697#issuecomment-1988278519. Might be worth waiting to see what the outcome of that is.

**Comment by emauricio** [comment]
@Bo98 seems they are working on the patch already,
https://github.com/apple/swift-format/pull/704

I got lucky and the version 5.10 works fine for me, but you are right, if they will release a patch soon waiting a bit is better.

**Comment by chenrui333** [comment]
> @Bo98 seems they are working on the patch already, [apple/swift-format#704](https://github.com/apple/swift-format/pull/704)
> 
> I got lucky and the version 5.10 works fine for me, but you are right, if they will release a patch soon waiting a bit is better.

should we just close this PR?

**Comment by emauricio** [comment]
@chenrui333 i created a new one, 
https://github.com/Homebrew/homebrew-core/pull/166647 

sorry for the trouble.

**Pull request closed without merging**
