### PR TITLE
cjson 1.7.12 (new formula)

### PR DESCRIPTION
**Pull request by ygj6**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why no bottle?

**Comment by ygj6** [comment]
> Why no bottle?

Thank you for replying so quickly. Should I delete this line?
```shell
bottle :unneeded
```

**Comment by SMillerDev** [comment]
Yes, otherwise it'll break pre-built binaries

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Looks good, thanks @ygj6 for the pull request!

**Pull request closed without merging**
