### PR TITLE
katago 1.3.3

### PR DESCRIPTION
**Pull request by dwt**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dwt** [comment]
Still work in progress - sorry, I'm a bit new to how bump-formula-pr works.

**Comment by dwt** [comment]
This looks like a complete update pull request from my side now.

What else can I do to get this mergeable?

**Comment by Bo98** [comment]
Just some nitpicks:

```
==> brew style katago
==> FAILED
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/katago.rb ==
C: 22:  1: Trailing whitespace detected.
C: 27:  1: Trailing whitespace detected.
C: 32:  1: Trailing whitespace detected.

1 file inspected, 3 offenses detected
```

**Comment by dwt** [comment]
> Just some nitpicks: [...] trailing whitespace

Like this?

**Comment by Bo98** [comment]
Yep. Thank you.

**Pull request closed without merging**
