### PR TITLE
diff-so-fancy: Add installation from HEAD

### LINKED ISSUE #243: Use of uninitialized value $value in substitution (s///) at /usr/local/bin/diff-so-fancy line 370
I'm getting the following error for any `git diff` operation after updating to 1.1.0 release via homebrew:

`Use of uninitialized value $value in substitution (s///) at /usr/local/bin/diff-so-fancy line 370`

[diff.txt](https://github.com/so-fancy/diff-so-fancy/files/1149992/diff.txt)

### PR DESCRIPTION
**Pull request by jeffbyrnes**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Ran into this when trying to fix so-fancy/diff-so-fancy#243

### CODE REVIEW

**Comment by mbanyar033** [comment]
😁

**Comment by jeffbyrnes** [comment]
Slight tweak, as it turns out, the `master` branch is not their bleeding edge.

**Comment by fxcoudert** [comment]
Thanks @jeffbyrnes for your contribution to Homebrew!

**Comment by jeffbyrnes** [comment]
You’re welcome! Glad to do it after so many years of being a happy user.

**Pull request merged**
