### PR TITLE
libedit 20230828-3.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
There's a 20230828-3.1 now, with the patch included.

**Comment by chenrui333** [comment]
that is pretty good!

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
I will followup with the tests.
```
brew link zip
brew link zip
brew link z3
brew link llvm
brew link z3
brew link llvm
brew link z3
brew link llvm
brew test --retry --verbose cake
brew linkage --test dotnet
brew test --retry --verbose kafka
brew test --retry --verbose libtirpc
brew link llvm
brew link llvm
brew link llvm
brew link llvm
brew link llvm
brew link llvm
brew link llvm
brew link llvm
brew link llvm
brew link llvm
brew test --retry --verbose pyqt@5
brew linkage --test qt@5
brew test --retry --verbose questdb
brew test --retry --verbose sonarqube
brew test --retry --verbose varnish
brew test --retry --verbose youtube-dl
```

**Comment by chenrui333** [comment]
see regression testing in https://github.com/chenrui333/github-action-test/actions/workflows/brew-regression.yml, looks like  only libtirpc has some ssiue.

**Pull request merged**
