### PR TITLE
rtv 1.22.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`Error: rtv is missing test dependencies: openssl python` 🤔

**Comment by fxcoudert** [comment]
Should be fixed by: https://github.com/Homebrew/brew/commit/d32fc4508fafd80665747083299fb9eb5700ea7d

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
> Should be fixed by: Homebrew/brew@d32fc45

@fxcoudert https://github.com/Homebrew/brew/commit/42fc339ee6b81e8b303eae388fe8016ae85e8d79 actually

**Pull request closed without merging**
