### PR TITLE
xcodegen 2.20.0

### PR DESCRIPTION
**Pull request by yonaskolb**
Created with brew bump-formula-pr.

### CODE REVIEW

**Comment by yonaskolb** [comment]
Seems to be failing with
```
clang: error: the clang compiler does not support '-march=nehalem'
```
No idea what that means?

**Comment by Bo98** [comment]
This is happening because you are cross-compiling for arm64 on a x86_64 machine. We don't have support for support universal binaries in Homebrew.

**Comment by thii** [comment]
@yonaskolb Can we use the canonnical Swift package build command instead of the Make command here? It also helps Homebrew to recognize that this is a Swift formula.

swift build --disable-sandbox -c release

**Comment by carlocab** [comment]
I'm not sure why you would make building a universal binary the default, with no option to opt-in or out in the `Makefile`. I'd guess building for the host architecture by default but making a universal build an option you can turn on would be preferable.

However, if you don't want to use the existing `Makefile`, you could do something like this:
```diff
diff --git a/Formula/xcodegen.rb b/Formula/xcodegen.rb
index 6d1b112e05e..6047d06ca9b 100644
--- a/Formula/xcodegen.rb
+++ b/Formula/xcodegen.rb
@@ -17,7 +17,9 @@ class Xcodegen < Formula
   depends_on :macos
 
   def install
-    system "make", "install", "PREFIX=#{prefix}"
+    system "swift", "build", "--disable-sandbox", "-c", "release"
+    bin.install ".build/release/#{name}"
+    pkgshare.install "SettingPresets"
   end
 
   test do
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
