### PR TITLE
util-linux: remove heavy asciidoctor dependency

### PR DESCRIPTION
**Pull request by SMillerDev**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Implements the idea from https://github.com/Homebrew/homebrew-core/pull/118926

### CODE REVIEW

**Review by fxcoudert — DISMISSED** [review]

**Comment by dawidd6** [comment]
Built a bottle locally without `asciidoctor` and checked the diff between original bottle and the modified one:
```diff
--- orig.txt	2022-12-30 12:47:47.469066791 +0000
+++ mod.txt	2022-12-30 12:48:07.361073260 +0000
@@ -439,11 +439,8 @@
 util-linux/2.38.1/share/man/man8/fsfreeze.8
 util-linux/2.38.1/share/man/man8/fstrim.8
 util-linux/2.38.1/share/man/man8/hwclock.8
-util-linux/2.38.1/share/man/man8/i386.8
 util-linux/2.38.1/share/man/man8/isosize.8
 util-linux/2.38.1/share/man/man8/ldattach.8
-util-linux/2.38.1/share/man/man8/linux32.8
-util-linux/2.38.1/share/man/man8/linux64.8
 util-linux/2.38.1/share/man/man8/losetup.8
 util-linux/2.38.1/share/man/man8/lsblk.8
 util-linux/2.38.1/share/man/man8/lslocks.8
@@ -469,9 +466,7 @@
 util-linux/2.38.1/share/man/man8/swapon.8
 util-linux/2.38.1/share/man/man8/switch_root.8
 util-linux/2.38.1/share/man/man8/umount.8
-util-linux/2.38.1/share/man/man8/uname26.8
 util-linux/2.38.1/share/man/man8/uuidd.8
 util-linux/2.38.1/share/man/man8/wdctl.8
 util-linux/2.38.1/share/man/man8/wipefs.8
-util-linux/2.38.1/share/man/man8/x86_64.8
 util-linux/2.38.1/share/man/man8/zramctl.8
```

so only a few manpages are missing after the change.

**Comment by dawidd6** [comment]
Diffoscope between original bottle and modified one:
```diff
--- 553fde3aab1934fc2973263404b4cb9b860d4dd530703398d88cbc3a5e07840c--util-linux--2.38.1.x86_64_linux.bottle.1.tar.gz
+++ util-linux--2.38.1.x86_64_linux.bottle.2.tar.gz
│   --- 553fde3aab1934fc2973263404b4cb9b860d4dd530703398d88cbc3a5e07840c--util-linux--2.38.1.x86_64_linux.bottle.1.tar
├── +++ util-linux--2.38.1.x86_64_linux.bottle.2.tar
│ ├── file list
│ │ @@ -1,10 +1,10 @@
│ │  drwxr-xr-x   0        0        0        0 2022-08-04 09:08:45.000000 util-linux/2.38.1/
│ │  drwxr-xr-x   0        0        0        0 2022-08-04 09:08:45.000000 util-linux/2.38.1/.brew/
│ │ --rw-r--r--   0        0        0     4159 2022-08-04 09:08:45.000000 util-linux/2.38.1/.brew/util-linux.rb
│ │ +-rw-r--r--   0        0        0     4160 2022-08-04 09:08:45.000000 util-linux/2.38.1/.brew/util-linux.rb
│ │  -rw-r--r--   0        0        0    41922 2022-08-04 09:08:45.000000 util-linux/2.38.1/AUTHORS
│ │  -rw-r--r--   0        0        0    18092 2022-08-04 09:08:45.000000 util-linux/2.38.1/COPYING
│ │  -rw-r--r--   0        0        0      107 2022-08-04 09:08:45.000000 util-linux/2.38.1/ChangeLog
│ │  -rw-r--r--   0        0        0    77371 2022-08-04 09:08:45.000000 util-linux/2.38.1/NEWS
│ │  -rw-r--r--   0        0        0     4836 2022-08-04 09:08:45.000000 util-linux/2.38.1/README
│ │  drwxr-xr-x   0        0        0        0 2022-08-04 09:08:45.000000 util-linux/2.38.1/bin/
│ │  -r-xr-xr-x   0        0        0    86248 2022-08-04 09:08:45.000000 util-linux/2.38.1/bin/cal
│ │ @@ -435,19 +435,16 @@
│ │  -rw-r--r--   0        0        0    14121 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/findmnt.8
│ │  -rw-r--r--   0        0        0    13048 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/fsck.8
│ │  -rw-r--r--   0        0        0     2031 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/fsck.cramfs.8
│ │  -rw-r--r--   0        0        0     4716 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/fsck.minix.8
│ │  -rw-r--r--   0        0        0     3599 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/fsfreeze.8
│ │  -rw-r--r--   0        0        0     6777 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/fstrim.8
│ │  -rw-r--r--   0        0        0    40157 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/hwclock.8
│ │ --rw-r--r--   0        0        0       19 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/i386.8
│ │  -rw-r--r--   0        0        0     2362 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/isosize.8
│ │  -rw-r--r--   0        0        0     5146 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/ldattach.8
│ │ --rw-r--r--   0        0        0       19 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/linux32.8
│ │ --rw-r--r--   0        0        0       19 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/linux64.8
│ │  -rw-r--r--   0        0        0     8015 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/losetup.8
│ │  -rw-r--r--   0        0        0    10635 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/lsblk.8
│ │  -rw-r--r--   0        0        0     4328 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/lslocks.8
│ │  -rw-r--r--   0        0        0     4072 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/lsns.8
│ │  -rw-r--r--   0        0        0     3417 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/mkfs.8
│ │  -rw-r--r--   0        0        0     2336 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/mkfs.bfs.8
│ │  -rw-r--r--   0        0        0     3030 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/mkfs.cramfs.8
│ │ @@ -465,13 +462,11 @@
│ │  -rw-r--r--   0        0        0    29246 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/sfdisk.8
│ │  -rw-r--r--   0        0        0     2985 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/sulogin.8
│ │  -rw-r--r--   0        0        0     2528 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/swaplabel.8
│ │  -rw-r--r--   0        0        0       12 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/swapoff.8
│ │  -rw-r--r--   0        0        0     7455 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/swapon.8
│ │  -rw-r--r--   0        0        0     2198 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/switch_root.8
│ │  -rw-r--r--   0        0        0    10545 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/umount.8
│ │ --rw-r--r--   0        0        0       19 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/uname26.8
│ │  -rw-r--r--   0        0        0     3588 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/uuidd.8
│ │  -rw-r--r--   0        0        0     3237 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/wdctl.8
│ │  -rw-r--r--   0        0        0     6302 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/wipefs.8
│ │ --rw-r--r--   0        0        0       19 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/x86_64.8
│ │  -rw-r--r--   0        0        0     4445 2022-08-04 09:08:45.000000 util-linux/2.38.1/share/man/man8/zramctl.8
│ ├── util-linux/2.38.1/.brew/util-linux.rb
│ │ @@ -11,15 +11,15 @@
│ │      "GPL-3.0-or-later",
│ │      "LGPL-2.1-or-later",
│ │      :public_domain,
│ │    ]
│ │  
│ │    keg_only :shadowed_by_macos, "macOS provides the uuid.h header"
│ │  
│ │ -  depends_on "asciidoctor" => :build
│ │ +  #depends_on "asciidoctor" => :build
│ │  
│ │    uses_from_macos "libxcrypt"
│ │    uses_from_macos "ncurses"
│ │    uses_from_macos "zlib"
│ │  
│ │    # Everything in following macOS block is for temporary patches other than `gettext`.
│ │    # TODO: Remove in the next release.
```

**Comment by p-linnane** [comment]
Do we want to run this again on self-hosted?

**Comment by iMichka** [comment]
I added `--disable-asciidoc` to the flags, see:
https://github.com/util-linux/util-linux/commit/236421a49103ea510bcba1e7ef90b57d24aeab76

Re-running without recursive dependent check to speed things up.

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
