### PR TITLE
protobuf 27.0

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
apache-arrow needs a revision bump

**Comment by carlocab** [comment]
`apache-arrow` is failing with:
```
  CMake Error at cmake_modules/FindProtobuf.cmake:115 (message):
    Could not find Protobuf.  Looked in /opt/homebrew.
  Call Stack (most recent call first):
    cmake_modules/ThirdpartyToolchain.cmake:417 (find_package)
    CMakeLists.txt:166 (INCLUDE)
  
  
  
  CMake Error at /tmp/apache-arrow-20240527-65133-ydh7ol/apache-arrow-16.1.0/build/orc_ep-prefix/src/orc_ep-stamp/orc_ep-configure-RELEASE.cmake:47 (message):
    Stopping after outputting logs.
```
Not really sure why it used to be able to find Protobuf but can't do it anymore.

**Comment by scpeters** [comment]
> `apache-arrow` is failing with:
> 
> ```
>   CMake Error at cmake_modules/FindProtobuf.cmake:115 (message):
>     Could not find Protobuf.  Looked in /opt/homebrew.
>   Call Stack (most recent call first):
>     cmake_modules/ThirdpartyToolchain.cmake:417 (find_package)
>     CMakeLists.txt:166 (INCLUDE)
>   
>   
>   
>   CMake Error at /tmp/apache-arrow-20240527-65133-ydh7ol/apache-arrow-16.1.0/build/orc_ep-prefix/src/orc_ep-stamp/orc_ep-configure-RELEASE.cmake:47 (message):
>     Stopping after outputting logs.
> ```
> 
> Not really sure why it used to be able to find Protobuf but can't do it anymore.

I'm not sure what changed either. I didn't find a `FindProtobuf.cmake` in the apache-arrow source code, but it looks like it's from [orc](https://github.com/apache/orc):

* https://github.com/apache/orc/blob/v2.0.0/cmake_modules/FindProtobuf.cmake#L115

**Comment by carlocab** [comment]
Needs an upstream issue with Apache Arrow/ORC.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
