### PR TITLE
redshift: moved caveats method to before the plist block

### PR DESCRIPTION
**Pull request by dj-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

initial, slight edit to Redshift formula aligning it to brew audit --strict guidelines with the caveats method running before the plist block. @MikeMcQuaid

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/c02cef102c44ea2633b7e2d369b8083c4f0eacf1. Thank you for your contribution to Homebrew @dj-m; we appreciate it! :smiley_cat:

**Comment by dj-m** [comment]
The first of many to come 🙌🏾; I hope! @DomT4

**Comment by DomT4** [comment]
PRs always welcome! Never unappreciative of fixes to meet our evolving style. A lot of formulae that go through CI regularly end up with our preferred style guidelines, but some of the things that are no longer updated upstream or only updated infrequently can take a while to catch up.

**Comment by MikeMcQuaid** [comment]
Thanks @dj-m, as you can see my fellow 🇬🇧 @DomT4 beat me to this one! Congrats on your first 🍺 pull request!

A tiny nit that @DomT4 was too kind to point out is that our preferred commit message format for changes like this is `redshift: move caveats method before plist block` to:
- prefix with the formula name to make quick scanning of the commit show what it changed
- use present tense (the commit _makes_ the change rather than _follows_ the change)
- keep the commit subject (i.e. the first line, like an email subject) at 50 characters or fewer

This is a good read on commit message ~~pedantry~~ style: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by DomT4** [comment]
To be honest, I rewrite so many commit messages to tweak them to our style I hadn't consciously noticed I'd done that here 😅. 👍 on Mike's clarification.

**Comment by dj-m** [comment]
Perfect, thank you for the info @MikeMcQuaid @DomT4! Will fold into future efforts posthaste.

**Comment by MikeMcQuaid** [comment]
💥 @dj-m!

**Pull request merged**
