### PR TITLE
kitchen-sync 1.7

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
-- Could NOT find PostgreSQL (missing: PostgreSQL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:105 (MESSAGE):
  Couldn't find the PostgreSQL, MySQL, or MariaDB client libraries.  This
  would produce a build of Kitchen Sync which doesn't support any databases,
  which is probably not what you want.  Please see 'Compiling in support for
  different databases' in INSTALL.md for help.  (If you really want to
  compile the shared part of Kitchen Sync without support far any databases,
  run cmake with the -DNO_DATABASES=1 option.)
```

**Comment by igas** [comment]
This is interesting. If we generally remove options, but here we have multiple db support. Which one we should choose? Should we build with all? Or this is going to be an exception?

**Comment by fxcoudert** [comment]
MySQL is the most used, so let's do that one unconditionally:

```
==> install_on_request (30 days)
Index | Name (with options)                                   | Count |  Percent
-----:|-------------------------------------------------------|------:|--------:
1     | kitchen-sync                                          |    49 |   50.52%
2     | kitchen-sync --without-mysql-client                   |    25 |   25.77%
3     | kitchen-sync --HEAD                                   |    20 |   20.62%
4     | kitchen-sync --with-postgresql                        |     2 |    2.06%
5     | kitchen-sync --without-mysql-client --with-postgresql |     1 |    1.03%
Total |                                                       |    97 |  100.00%
```

**Comment by igas** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
