### PR TITLE
automake: move mac-specific code to on_macos block

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
2020-11-09T22:21:52.8902640Z [34m==>[0m [1mbrew audit automake --online --git --skip-style[0m
2020-11-09T22:22:01.7536540Z [31m==>[0m [1m[31mFAILED[0m[0m
2020-11-09T22:22:01.7538270Z [31mError:[0m 1 problem in 1 formula detected
2020-11-09T22:22:01.7539090Z automake:
2020-11-09T22:22:01.7540490Z   * 'revision 1' should be removed
```

It should not, this change is a no-op on Mac.

**Comment by SMillerDev** [comment]
I believe that is a brew bug that should be fixed @dtrodrigues was working on this a while ago

**Comment by dtrodrigues** [comment]
I have a proposed fix here: https://github.com/Homebrew/brew/pull/9097

**Comment by iMichka** [comment]
Cool, thanks. I'll merge this as-is as this is a no-op on Mac, and the rest of CI is happy.

**Pull request merged**
