### PR TITLE
various: allow JAVA_HOME override

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by reitermarkus** [comment]
Why do these need to be overridable?

**Comment by alebcay** [comment]
I believe there was a conversation at some point (or perhaps several over time) about someone complaining that they could not use their own Java installation. The solution that we gave at some point was that people can just set `JAVA_HOME` and then they would be able to use whatever JDK they wanted with Java-based formulae.

This PR simply works to deliver on that solution. If this is not the direction we want to move in, that's fine, in which case this PR can be discarded. But also then I wonder what the point of having `Language::Java.overridable_java_home_env` is - after all, we don't really need it for any particular functionality.

**Comment by reitermarkus** [comment]
> The solution that we gave at some point was that people can just set `JAVA_HOME` 

Yes, I think this makes sense for formulae which are used for Java development, but not other formulae which are simply a command-line tool which happens to be written in Java. In that case I think it makes more sense to depend on the latest possible version and not allow overriding it.

**Comment by alebcay** [comment]
Fair enough. Closing this then; if there's any from the list that could benefit from the change, we can add it on a per-formula basis. Also to-do from this PR: `orientdb` 3.1.2, many license updates.

**Pull request closed without merging**
