### PR TITLE
pyenv 1.2.12

### PR DESCRIPTION
**Pull request by joshfriend**

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by scpeters** [comment]
@BrewTestBot test this please

**Comment by joshfriend** [comment]
```
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/40880.patch
==> Applying patch
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
Error: Patch failed to apply: aborted.
```

I'm guessing this is a weird failure from some dirty repo state on the jenkins worker?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @joshfriend

**Pull request closed without merging**
