### PR TITLE
perl 5.34.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
ARM

```
Error: 7 failed steps!
brew test --retry --verbose lanraragi
brew test --retry --verbose latexindent
brew test --retry --verbose mhonarc
brew test --retry --verbose po4a
brew linkage --test vim
brew test --retry --verbose vim
brew linkage --test weechat
```

Intel

```
Error: 8 failed steps!
brew test --retry --verbose asciiquarium
brew test --retry --verbose lanraragi
brew test --retry --verbose latexindent
brew test --retry --verbose mhonarc
brew test --retry --verbose po4a
brew linkage --test vim
brew test --retry --verbose vim
brew linkage --test weechat
```

**Comment by carlocab** [comment]
Oh hello `asciiquarium`. It's you again.

**Comment by carlocab** [comment]
`lanraragi` is the only failure, but that's pre-existing.

**Comment by carlocab** [comment]
>Perl 5.34.0 is the current stable version of Perl.

https://dev.perl.org/perl5/

**Review by nandahkrishna — APPROVED** [review]

**Pull request closed without merging**
