### PR TITLE
bitcoin: resource bdb4 so that the formula can be retired

### PR DESCRIPTION
**Pull request by cho-m**
All other usage was moved to `berkeley-db@5`, which is the default used by major Linux distros.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Maybe we should just deprecate this too? What do other packagers/distros do about the bdb4 dep?

**Comment by cho-m** [comment]
> Maybe we should just deprecate this too? What do other packagers/distros do about the bdb4 dep?

The dependency was added based on user usage of the deprecated wallet feature - https://github.com/Homebrew/homebrew-core/pull/108577

Fedora does something similar https://src.fedoraproject.org/rpms/bitcoin-core/blob/rawhide/f/bitcoin-core.spec#_43 

Arch just uses `--with-incompatible-bdb`, https://gitlab.archlinux.org/archlinux/packaging/packages/bitcoin/-/blob/main/PKGBUILD?ref_type=heads#L69

Same with Alpine - https://git.alpinelinux.org/aports/tree/community/bitcoin/APKBUILD#n35

**Comment by carlocab** [comment]
> Arch just uses `--with-incompatible-bdb`, https://gitlab.archlinux.org/archlinux/packaging/packages/bitcoin/-/blob/main/PKGBUILD?ref_type=heads#L69
> 
> 
> 
> Same with Alpine - https://git.alpinelinux.org/aports/tree/community/bitcoin/APKBUILD#n35

This seems nicer

**Comment by cho-m** [comment]
The previous PR mentioned some issues using newer BDB for existing users.

Upstream mentions https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions
> these will install Berkeley DB 5.3 or later. This will break binary wallet compatibility with the distributed executables, which are based on BerkeleyDB 4.8.

---

Supposedly, Bitcoin Core will remove feature in the future so hopefully won't stick around too long https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L288
> The legacy wallet type is being deprecated and support for creating and opening legacy wallets will be removed in the future. Legacy wallets can be migrated to a descriptor wallet with migratewallet.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
