### PR TITLE
teller 1.5.4

### PR DESCRIPTION
**Pull request by kaplanelad**
Bump Teller version to 1.5.4

### CODE REVIEW

**Comment by kaplanelad** [comment]
Bump Teller version to 1.5.4.

**Review by carlocab — COMMENTED** [review]
Please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings.

For new formulae:

> At Homebrew, we like to put the name of the formula up front like so: `foobar 7.3 (new formula)`.

For existing formulae:

> The preferred commit message format for simple version updates is `foobar 7.3` and for fixes is `foobar: fix flibble matrix.`.

Refer to the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit) for more details. Also, when making further changes to your pull request, use the following guidelines to make sure that @BrewTestBot can merge your commits:

> - One formula per commit; one commit per formula.
> - Keep merge commits out of the pull request.

**Comment by kaplanelad** [comment]
> Please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings.
> 
> For new formulae:
> 
> > At Homebrew, we like to put the name of the formula up front like so: `foobar 7.3 (new formula)`.
> 
> For existing formulae:
> 
> > The preferred commit message format for simple version updates is `foobar 7.3` and for fixes is `foobar: fix flibble matrix.`.
> 
> Refer to the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit) for more details. Also, when making further changes to your pull request, use the following guidelines to make sure that @BrewTestBot can merge your commits:
> 
> > * One formula per commit; one commit per formula.
> > * Keep merge commits out of the pull request.

done

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
