### PR TITLE
cln: Fix build on ARM

### PR DESCRIPTION
**Pull request by iMichka**
Fixes:
```console
  base/low/cl_low_div.cc:13:8: error: declaration of 'divu_16_rest' in global scope conflicts with declaration with C language linkage
  uint16 divu_16_rest;
         ^
  ./base/cl_low.h:447:21: note: declared with C language linkage here
    extern "C" uint16 divu_16_rest;                         // -> Rest r
                      ^
  base/low/cl_low_div.cc:104:8: error: declaration of 'divu_32_rest' in global scope conflicts with declaration with C language linkage
  uint32 divu_32_rest;
         ^
  ./base/cl_low.h:597:21: note: declared with C language linkage here
    extern "C" uint32 divu_32_rest;                         // -> Rest r
                      ^
  base/low/cl_low_div.cc:210:8: error: declaration of 'divu_64_rest' in global scope conflicts with declaration with C language linkage
  uint64 divu_64_rest;
         ^
  ./base/cl_low.h:987:21: note: declared with C language linkage here
    extern "C" uint64 divu_64_rest;                         // -> Rest r
                      ^
  3 errors generated.
  make[1]: *** [base/low/cl_low_div.lo] Error 1
  make[1]: *** Waiting for unfinished jobs....

```

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I will move the patch to formula patches if the build works on ARM

**Comment by SMillerDev** [comment]
Seems like you missed one:
```console
  base/low/cl_low_div.cc:210:8: error: declaration of 'divu_64_rest' in global scope conflicts with declaration with C language linkage
  uint64 divu_64_rest;
         ^
  ./base/cl_low.h:987:21: note: declared with C language linkage here
    extern "C" uint64 divu_64_rest;                         // -> Rest r
                      ^
```

**Comment by cho-m** [comment]
Does `cln` work for armv8 (64-bit) in current release?

I remember looking at this a while back and deciding to just add HEAD to get the ARM fixes from upstream (#112034) as I wasn't able to backport commits easily.

**Comment by iMichka** [comment]
I tried to register on their mailing list to ask about a new release, but was not accepted yet...

**Comment by iMichka** [comment]
`cln` ARM bottles have been built by #160623, closing here.

**Pull request closed without merging**
