### PR TITLE
pyside@2, coin3d: migrate to Python@3.10

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1902618
> https://codereview.qt-project.org/c/pyside/pyside-setup/+/348390

**Comment by Bo98** [comment]
Update pyside2 to 5.15.2.1 and it'll probably work: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.15.2.1-src/pyside-setup-opensource-src-5.15.2.1.tar.gz

**Comment by Bo98** [comment]
Upstream messed up one of the backports so it doesn't build without Python Limited API (PEP384) enabled, though that should be the default and I'm not sure why it's not enabling...

```cmake
option(FORCE_LIMITED_API "Enable the limited API." "yes")
```

**Comment by Bo98** [comment]
Managed to get this working on 10.15 and 11. But there's now 3 different errors across 11-arm64, 12 and 12-arm64, which sounds fun.

**Comment by cho-m** [comment]
Odd that only Intel Monterey fails to build `pyside@2`. I wonder if there is a parallelization issue.

**Comment by Bo98** [comment]
I suspect the Linux failure is caused by the issue described in https://github.com/Homebrew/homebrew-core/pull/98765#issue-1196427476.

> I wonder if there is a parallelization issue.

Possibly, yeah. 12-arm64 previously also failed.

**Comment by cho-m** [comment]
`coin3d` python binding test on Apple Silicon is causing a segfault:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000100000000
Exception Codes:       0x0000000000000001, 0x0000000100000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [78483]

VM Region Info: 0x100000000 is not in any region.  Bytes before following region: 40992768
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102718000-10271c000    [   16K] r-x/r-x SM=COW  .../MacOS/Python

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	       0x196c7e7f0 _platform_strnlen + 16
1   libsystem_platform.dylib      	       0x196c7f32c _platform_strncpy + 44
2   _coin.cpython-310-darwin.so   	       0x105fbd9dc cast_internal(_object*, _object*, char const*, int) + 100
3   _coin.cpython-310-darwin.so   	       0x105fbe4a0 cast(_object*, _object*) + 68
4   Python                        	       0x102efc1a0 cfunction_call + 96
5   Python                        	       0x102ea994c _PyObject_MakeTpCall + 136
```

**Comment by cho-m** [comment]
Does `ENV.deparallelize` impact `ninja`?

Looks like Intel Monterey still failed to build bottle, but it did successfully build-from-source during `coin3d`.

Could try directly passing flag to `ninja`. May be worth checking if we need `ninja` or if Unix Makefiles are sufficient.

**Comment by Bo98** [comment]
> Does `ENV.deparallelize` impact `ninja`?

No

**Comment by cho-m** [comment]
> > Does `ENV.deparallelize` impact `ninja`?
> 
> No

Although I am not sure if there is an easy way to do this via `ninja` (outside shims), since we have been switching some `cmake`-based builds to `cmake --build`, we could consider modifying `CMAKE_BUILD_PARALLEL_LEVEL` environment variable.

Anyway, currently trying a parallel build with just Unix Makefile first. Can switch back to Ninja and try `cmake --build --parallel 1` or `ninja install -j 1` on next attempt.

`coin3d` is going to keep failing until can figure out `pivy` segfault issue on Apple Silicon.

**Comment by Bo98** [comment]
> Can switch back to Ninja and try `cmake --build --parallel 1` or `ninja install -j 1` on next attempt.

Unless there's a substantial advantage to using Ninja, I usually see it as an unnecessary dependency.

**Comment by Bo98** [comment]
arm64 crash is a bit odd. I've reviewed the 2nd patch a bit and can't see anything obviously wrong. I don't have an Apple Silicon device and the confusing bit to me is what could possibly only affect arm64.

**Comment by Bo98** [comment]
Good spot with that - didn't even think about the `PY_SSIZE_T_CLEAN` half.

**Review by SMillerDev — APPROVED** [review]

**Comment by iMichka** [comment]
Nice work!

What's the hold up? Should we squash the commits manually?

**Comment by SMillerDev** [comment]
Ready when you are

**Comment by iMichka** [comment]
Thanks all!

**Pull request closed without merging**
