### PR TITLE
php@7.2 7.2.21

### PR DESCRIPTION
**Pull request by Toflar**
Updated formula to php 7.2.21.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by danherd** [comment]
Please merge this in! PHP 7.2.20 has an annoying bug related to Symfony that is fixed in 7.2.21 https://github.com/symfony/symfony/issues/32395

**Comment by SMillerDev** [comment]
Easy, we're just volunteers here. It'll be merged when someone has time to do so.

**Comment by SMillerDev** [comment]
Thanks @Toflar

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Pull request closed without merging**
