### PR TITLE
k6: migrate to homebrew/core

### PR DESCRIPTION
**Pull request by chenrui333**
Relates to https://github.com/Homebrew/homebrew-core/pull/40689
Relates to loadimpact/homebrew-k6#6

cc @na--

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please add it in the same pull request as the formula itself.

**Comment by chenrui333** [comment]
ok, will do. 

I will actually follow the instructions in here. 
https://docs.brew.sh/Migrating-A-Formula-To-A-Tap

**Comment by fxcoudert** [comment]
@chenrui333 actually you made me realize I was completely wrong.

This pull request is not valid, but neither is adding the suggestion I made. The formula needs to be added to the `tap_migrations.json` of the *previous* tap (where it will be deleted), not the destination tap (homebrew-core).

**Comment by chenrui333** [comment]
So you mean, I need to add into this repo, https://github.com/loadimpact/homebrew-k6?

**Pull request closed without merging**
