### PR TITLE
node 11.12.0

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ZYSzys** [comment]
Hi, folks, when can this be merged ?

**Comment by fxcoudert** [comment]
Does `npm` need to be updated?

**Comment by diogoazevedos** [comment]
Am I missing something?

**Comment by fxcoudert** [comment]
@diogoazevedos Does npm need to be updated?

**Comment by ZYSzys** [comment]
@fxcoudert I think no. We are using npm `6.7.0` in Node.js core now.(PRs that related upgrading npm are on the road)

**Comment by fxcoudert** [comment]
Merged, and `reactive-native-cli` test fixed in https://github.com/Homebrew/homebrew-core/commit/5b6aac7efb6aabe6e693481659c0f8f4e1d483bd

**Comment by fxcoudert** [comment]
Thanks @diogoazevedos for the pull request

**Pull request closed without merging**
