### PR TITLE
use secure urls #2

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by vszakats** [comment]
Getting an 'Access Denied' on the Jenkins 'Details' link.

**Comment by vszakats** [comment]
Split off `guile` to https://github.com/Homebrew/homebrew-core/pull/5782, because it had a CI failure on Sierra.

**Comment by ilovezfs** [comment]
Thanks again @vszakats :old_key:

**Comment by vszakats** [comment]
Thank you, @ilovezfs !

**Pull request merged**
