### PR TITLE
bazel 0.24.1

### PR DESCRIPTION
**Pull request by hawkingrei**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
It's failing on macOS Sierra.

**Comment by zbeekman** [comment]
[Specifically]():
```
==> ./compile.sh
Building Bazel from scratch....../usr/bin/xcrun clang -fobjc-arc -framework CoreServices -framework Foundation -o /private/tmp/bazel_7qI7yfV0/archive/_embedded_binaries/xcode-locator tools/osx/xcode_locator.m
tools/osx/xcode_locator.m:180:64: error: no visible @interface for 'NSDictionary' declares the selector 'initWithContentsOfURL:error:'
    NSDictionary *versionPlistContents = [[NSDictionary alloc] initWithContentsOfURL:versionPlistUrl
                                          ~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
==> ./output/bazel --output_user_root /private/tmp/bazel-20190404-95358-1icibs5/output_user_root build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --host_javabase=@bazel_tools//tools/jdk:jdk --javabase=@bazel_tools//tools/jdk:jdk scripts:bash_completion
Failed to execute: ./output/bazel
```

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by jmhodges** [comment]
This was fixed in bazel 0.25, so we could use that to upgrade https://github.com/bazelbuild/bazel/releases/tag/0.25.0 (see https://github.com/bazelbuild/bazel/commit/231270c67d5aa771462245531fa9b2ee7d3d0ae8 )

**Comment by jmhodges** [comment]
Trying do this myself but I keep getting errors when running bump-formula-pr

```
Error: GitHub You must be logged in to do that.:The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
```

The first command didn't work and I keep my bash_profile in the open so I can't put secrets in it. Would be cool to see this go in!

**Comment by zbeekman** [comment]
@hawkingrei Thanks for opening this PR. Since bazel was broken, and they've released a new version with a fix I've created a new PR to replace this one. Thanks for your contributions to Homebrew!

**Comment by zbeekman** [comment]
(New PR is #39571)

**Pull request closed without merging**
