### PR TITLE
zookeeper 3.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
22:28:04 cp -pR /private/tmp/d20200312-59072-1x3tfcv/apache-zookeeper-3.6.0/. /private/tmp/zookeeper-20200312-59072-1cyd296/apache-zookeeper-3.6.0
22:28:04 chmod -Rf +w /private/tmp/d20200312-59072-1x3tfcv
22:28:04 ==> ant compile_jute
22:28:04 Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
22:28:04 Buildfile: build.xml does not exist!
22:28:04 Build failed
```

**Comment by chenrui333** [comment]
zookeeper has moved to maven build system

**Comment by alistaire47** [comment]
I'm not quite sure how to fix this (I assume it needs to add a maven dep and then a `maven clean install` somewhere, but not quite sure where), but I'd be very grateful if somebody with more experience with how maven on brew works would contribute.

**Comment by chenrui333** [comment]
@alistaire47 feel free to submit a PR, I am going to close mine now.

**Pull request closed without merging**
