### PR TITLE
mongo-c-driver 1.23.4

### PR DESCRIPTION
**Pull request by kevinAlbs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failure with fastnetmon
```
    TypeError: no implicit conversion from nil to integer
```

**Comment by chenrui333** [comment]
looks like just flaky test

**Review by fxcoudert — DISMISSED** [review]
```
Error: fastnetmon: failed
An exception occurred within a child process:
  TypeError: no implicit conversion from nil to integer
```

Test failed on all runners, so it needs to be investigated and fixed.

**Comment by chenrui333** [comment]
my bad, makes sense then

**Comment by chenrui333** [comment]
cannot reproduce this issue in my local

```
==> Testing fastnetmon
/opt/homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/fastnetmon.rb
We will use custom path to configuration file: /private/tmp/fastnetmon-test-20230508-13289-2slxy5/fastnetmon.conf
We will log everything on console
[INFO] Logger initialized!
[ERROR] We can't find notify script /usr/local/bin/notify_about_attack.sh
[ERROR] Folder for attack details does not exist: /var/log/fastnetmon_attacks
[INFO] Read configuration file
[INFO] Totally we have 0 IPv4 subnets
[INFO] Totally we have 0 IPv6 subnets
[INFO] Total number of monitored hosts (total size of all networks): 0
[INFO] We need 0 MB of memory for storing counters for your networks
[INFO] We start total zerofication of counters
[INFO] We finished zerofication
[INFO] We loaded 0 IPv4 subnets to our in-memory list of networks
[INFO] Launch API server
[ERROR] Apple platforms do not support thread name changes
[ERROR] Apple platforms do not support thread name changes
[ERROR] Apple platforms do not support thread name changes
[ERROR] Apple platforms do not support thread name changes
[INFO] Run banlist cleanup thread, we will awake every 60 seconds
[ERROR] Apple platforms do not support thread name changes
[INFO] Starting Prometheus endpoint on 127.0.0.1:9209
[INFO] API server listening on 127.0.0.1:50052
```

**Comment by kevinAlbs** [comment]
This reproduces on my macOS M1 12.6.5 machine with the current mongo-c-driver version (1.23.3):
```
brew install fastnetmon
brew test fastnetmon
```
https://github.com/Homebrew/homebrew-core/pull/130482 has a proposed fix to the `fastnetmon` formula.

**Comment by chenrui333** [comment]
LGTM with the other PR for the test update, can you do a rebase after that one gets merged? Thanks!

**Review by iMichka — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
