### PR TITLE
jprq v2.2. 

### PR DESCRIPTION
**Pull request by DiyorbekAzimqulov**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
try out `brew style --fix xxx`

**Comment by DiyorbekAzimqulov** [comment]
> try out `brew style --fix xxx`

image
@chenrui333  thank you, i tried, but it did not find any `offenses`

**Comment by p-linnane** [comment]
You need to have the branch this PR is on checked out first:

```shell
brew style --fix jprq
j/jprq.rb:2:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    desc "Join Public Router, Quickly"
^^^^
j/jprq.rb:3:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    homepage "https://jprq.io/"
^^^^
j/jprq.rb:4:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    url "https://github.com/azimjohn/jprq/archive/refs/tags/2.2.tar.gz"
^^^^
j/jprq.rb:5:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    sha256 "6121e0ac74512052ed00c57c363f0f0b66910618ebd8134cfa72acca05b09163"
^^^^
j/jprq.rb:6:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    license "BSD-3-Clause"
^^^^
j/jprq.rb:7:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    depends_on "go" => :build
^^^^
j/jprq.rb:8:1: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
j/jprq.rb:9:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    def install
^^^^
j/jprq.rb:12:1: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
j/jprq.rb:13:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    test do
^^^^
j/jprq.rb:16:3: W: [Corrected] Layout/EndAlignment: end at 16, 2 is not aligned with class Jprq < Formula at 1, 0.
  end
  ^^^
j/jprq.rb:17:1: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.

1 file inspected, 12 offenses detected, 12 offenses corrected
```

**Comment by DiyorbekAzimqulov** [comment]
> You need to have the branch this PR is on checked out first:
> 
> ```shell
> brew style --fix jprq
> j/jprq.rb:2:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     desc "Join Public Router, Quickly"
> ^^^^
> j/jprq.rb:3:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     homepage "https://jprq.io/"
> ^^^^
> j/jprq.rb:4:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     url "https://github.com/azimjohn/jprq/archive/refs/tags/2.2.tar.gz"
> ^^^^
> j/jprq.rb:5:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     sha256 "6121e0ac74512052ed00c57c363f0f0b66910618ebd8134cfa72acca05b09163"
> ^^^^
> j/jprq.rb:6:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     license "BSD-3-Clause"
> ^^^^
> j/jprq.rb:7:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     depends_on "go" => :build
> ^^^^
> j/jprq.rb:8:1: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
> j/jprq.rb:9:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     def install
> ^^^^
> j/jprq.rb:12:1: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
> j/jprq.rb:13:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
>     test do
> ^^^^
> j/jprq.rb:16:3: W: [Corrected] Layout/EndAlignment: end at 16, 2 is not aligned with class Jprq < Formula at 1, 0.
>   end
>   ^^^
> j/jprq.rb:17:1: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
> 
> 1 file inspected, 12 offenses detected, 12 offenses corrected
> ```

thank you for your response. Sorry, but i did not get what you meant by saying 'You need to have the branch this PR is on checked out first'. I forked from homebrew-core to my repo and worked on master branch from my repo. then Opened PR to master branch of homebrew-core. And also style check found few errors and says corrected. Do I need to correct these and commit again?

Please, could you help me what to do step by step so this PR is approved and merged? Thank you.

**Pull request closed without merging**
