### PR TITLE
node 16.11.0

### PR DESCRIPTION
**Pull request by tuzi3040**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

`npm` updated to `8.0.0`.

### CODE REVIEW

**Comment by Bo98** [comment]
Python is not installed by default in Ubuntu images. How there was even one installed to begin with is not intentional.

Also note that we don’t just support Ubuntu. Homebrew formulae should be usable on a wide range of systems as long as your system uses Linux 2.6.32+, GCC 4.7+, Glibc 2.13+.

The solution here is to promote the Python dependency that already exists here at build time.

**Comment by ryenus** [comment]
What about using `python@3.10` instead of `python@3.9`?

**Comment by carlocab** [comment]
> What about using `python@3.10` instead of `python@3.9`?

Probably better to wait until later, as that would require migrating Node's entire dependency (sub-)graph to `python@3.10`.

**Comment by carlocab** [comment]
Not sure why the build failed earlier but succeeded now (race?), but the test is failing now because Node needs Python3 but Mojave doesn't provide one. (I was actually under the impression that it did, but that was wrong.)

**Review by carlocab — APPROVED** [review]
Thanks @tuzi3040!

**Pull request closed without merging**
