### PR TITLE
workflows/actionlint: run `zizmor`

### PR DESCRIPTION
**Pull request by carlocab**
This tool, written by a certain @woodruffw, seems like it would be useful.

See https://github.com/woodruffw/zizmor.

Needs #195936.

### CODE REVIEW

**Comment by woodruffw** [comment]
For viz: https://github.com/woodruffw/zizmor/issues/57 will make the SARIF output slightly friendlier for GitHub's SARIF support once fixed. Right now the SARIF results are well-formed and uploaded correctly, but don't rebase correctly on top of the repo root.

**Review by woodruffw — APPROVED** [review]
LGTM behaviorally. I leave it up to you whether you'd prefer I fix https://github.com/woodruffw/zizmor/issues/57 before merging here or not -- the results will show up as is, but won't be as easy to relate to existing files until that's fixed 🙂

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
Dropped `HOMEBREW_NO_INSTALL_FROM_API` to avoid erroring out when these formulae are updated.

> I leave it up to you whether you'd prefer I fix [woodruffw/zizmor#57](https://github.com/woodruffw/zizmor/issues/57) before merging here or not -- the results will show up as is, but won't be as easy to relate to existing files until that's fixed 🙂

May also just wait until this is fixed.

**Review by p-linnane — APPROVED** [review]

**Comment by woodruffw** [comment]
I've released v0.1.3, which contains the SARIF fix.

Example render:

https://github.com/woodruffw/zizmor/security/code-scanning/2

**Comment by carlocab** [comment]
Can't see, but we can re-run `actionlint / zizmor` after #196022 has hit the API.

**Comment by carlocab** [comment]
Cool. Let's give this a try. There are a lot of warnings though -- many of them would be difficult to address.

**Comment by carlocab** [comment]
Something that would be nice to fix is that the output on GitHub isn't quite as nice as on the command-line. For example:

https://github.com/Homebrew/homebrew-core/security/code-scanning/34

Compare this with:

```
warning[artipacked]: credential persistence through GitHub Actions artifacts
   --> /opt/homebrew/Library/Taps/homebrew/homebrew-core/.github/workflows/tests.yml:147:9
    |
147 |       - uses: actions/checkout@v4
    |         ------------------------- does not set persist-credentials: false
    |
```

On GitHub you don't see the recommendation to set `persist-credentials: false`.

**Comment by woodruffw** [comment]
> Something that would be nice to fix is that the output on GitHub isn't quite as nice as on the command-line. For example:

Yep, this is tracked with https://github.com/woodruffw/zizmor/issues/66. I'll try and fix that with the next release.

**Pull request merged**
