### PR TITLE
mono-4.6.1.5, fsharp-4.0.1.13

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Comment by DomT4** [comment]
Do we need to pick up the `fsharp` update at all or is it okay as-is?

**Comment by MikeMcQuaid** [comment]
> Do we need to pick up the fsharp update at all or is it okay as-is?

@mfilippov Ping on this?

**Comment by mfilippov** [comment]
@MikeMcQuaid I have problem with build with new fsharp. I try fix it and update PR.

**Comment by mfilippov** [comment]
@MikeMcQuaid I cannot reproduce problem on my machine. How can I run build like on CI?

**Comment by MikeMcQuaid** [comment]
@mfillippov: the `brew test-bot` command.

**Comment by mfilippov** [comment]
@MikeMcQuaid Where I can find docs about test-bot? I found link https://github.com/Homebrew/legacy-homebrew/blob/master/share/doc/homebrew/Brew-Test-Bot.md but it is 404 page now.

**Comment by MikeMcQuaid** [comment]
`brew test-bot --help` is your best bet.

**Comment by mfilippov** [comment]
Problem reproduced when build in sandbox:
```
Testing mono
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161005-99674-b7i4ec.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mono.rb --verbose
==> /usr/local/Cellar/mono/4.6.1.3/bin/mcs hello.cs
==> /usr/local/Cellar/mono/4.6.1.3/bin/mono hello.exe
==> /usr/local/Cellar/mono/4.6.1.3/bin/xbuild test.csproj
XBuild Engine Version 14.0
Mono, Version 4.6.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 10/5/2016 5:55:10 PM.
__________________________________________________
Project "/private/tmp/mono-test-20161005-99675-63ggxm/test.csproj" (default target(s)):
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
		Created directory "bin/Debug/"
		Created directory "obj/Debug/"
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	Target CoreCompile:
		Tool /usr/local/Cellar/mono/4.6.1.3/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /out:obj/Debug/HomebrewMonoTest.exe hello.cs obj/Debug/.NETFramework,Version=v4.5.AssemblyAttribute.cs /target:exe /nostdlib /reference:/usr/local/Cellar/mono/4.6.1.3/lib/mono/4.5-api/System.Core.dll /reference:/usr/local/Cellar/mono/4.6.1.3/lib/mono/4.5-api//mscorlib.dll
	Target DeployOutputFiles:
		Copying file from '/private/tmp/mono-test-20161005-99675-63ggxm/obj/Debug/HomebrewMonoTest.exe' to '/private/tmp/mono-test-20161005-99675-63ggxm/bin/Debug/HomebrewMonoTest.exe'
Done building project "/private/tmp/mono-test-20161005-99675-63ggxm/test.csproj".

Build succeeded.
	 0 Warning(s)
	 0 Error(s)

Time Elapsed 00:00:00.3859750
==> /usr/local/Cellar/mono/4.6.1.3/bin/fsharpi
==> /usr/local/Cellar/mono/4.6.1.3/bin/xbuild test.fsproj
XBuild Engine Version 14.0
Mono, Version 4.6.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 10/5/2016 5:55:13 PM.
__________________________________________________
Project "/private/tmp/mono-test-20161005-99675-63ggxm/test.fsproj" (default target(s)):
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	Target CoreCompile:
/usr/local/Cellar/mono/4.6.1.3/lib/mono/fsharp/Microsoft.FSharp.Targets: error : Error executing task Fsc: Object reference not set to an instance of an object
		Build FAILED.
		Errors:
		/private/tmp/mono-test-20161005-99675-63ggxm/test.fsproj (default targets) ->
		/usr/local/Cellar/mono/4.6.1.3/lib/mono/fsharp/Microsoft.FSharp.Targets (CoreCompile target) ->
			/usr/local/Cellar/mono/4.6.1.3/lib/mono/fsharp/Microsoft.FSharp.Targets: error : Error executing task Fsc: Object reference not set to an instance of an object
			 0 Warning(s)
			 1 Error(s)
		Time Elapsed 00:00:00.3548040
Error: mono: failed
```
Any idea why?

**Comment by mfilippov** [comment]
I found issue: https://github.com/Homebrew/homebrew-core/issues/5302

**Comment by MikeMcQuaid** [comment]
@mfilippov Does that problem need to block this PR, do you think?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by mfilippov** [comment]
@ilovezfs You can run brew test-bot mono on  this PR locally and get error when run ```xbuild test.fsproj``` in sandbox .

**Comment by mfilippov** [comment]
@MikeMcQuaid Yes #5302 block this PR.

**Comment by MikeMcQuaid** [comment]
@mfilippov Can you explain how? It looks like that's just relevant to a user-set environment variable? Thanks!

**Comment by mfilippov** [comment]
@MikeMcQuaid I think problem in sandbox build. I don't known how to diagnose it. After end brew test-bot, sandbox cleaned and I can't check anything. May be you known how prevent cleaning it?

**Comment by MikeMcQuaid** [comment]
@mfilippov If you use `--verbose` you may be able to see the logs of where it refused to allow writes. If not, `brew gist-logs fsharp` will upload them.

**Comment by mfilippov** [comment]
@MikeMcQuaid I fix problem.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `mono 4.6.1.5`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
