### PR TITLE
lnav 0.10.0

### PR DESCRIPTION
**Pull request by tstack**
Bumps the version and adds libarchive dependency

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Version bump already merged in https://github.com/Homebrew/homebrew-core/pull/82857.

Can we use the macOS-provided `libarchive`?

**Comment by tstack** [comment]
> Version bump already merged in #82857.

Ah, sorry, I had updated and thought I did a search of the PRs.  Just snuck in.

Can I use this PR to add the `--with-libarchive` fix?

> Can we use the macOS-provided libarchive?

I don't think the header file, `archive.h`, is installed with the command line tools.  Also, the macos version is 3.3.2, which is from 4 years ago.  I'd rather link against the more recent version in homebrew.

**Comment by carlocab** [comment]
> Can I use this PR to add the `--with-libarchive` fix?

Go ahead. You might want to bump the `revision` as well, but you'll need to rebase this first. Use `git rebase` and not `git merge`, please. (Apologies if that's obvious, but experience has shown this reminder is often useful.)

**Comment by tstack** [comment]
Sigh, I messed up something, going to close and open a new request.

**Pull request closed without merging**
