### PR TITLE
e2fsprogs 1.45.6

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
build failure
```
making all in lib/ext2fs
	CC gen_crc32ctable
	CC bb_compat.c
	CC inode_io.c
	CC write_bb_file.c
	CC dupfs.c
	CC imager.c
imager.c:70:2: error: unknown type name 'loff_t'; did you mean 'off_t'?
        loff_t          r;
        ^~~~~~
        off_t
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_off_t.h:31:33: note: 'off_t' declared here
typedef __darwin_off_t          off_t;
                                ^
1 error generated.
make[2]: *** [imager.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-libs-recursive] Error 1
make: *** [all] Error 2
```

**Comment by EricFromCanada** [comment]
It was originally [`off_t`](https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/lib/ext2fs/imager.c?id=382ed4a1c2b60acb9db7631e86dda207bde6076e); we could probably `inreplace` it back…

**Comment by chenrui333** [comment]
> It was originally [`off_t`](https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/lib/ext2fs/imager.c?id=382ed4a1c2b60acb9db7631e86dda207bde6076e); we could probably `inreplace` it back…

i tried the `off_t` approach, somehow it did not quite workout (runs into another issue)

**Comment by EricFromCanada** [comment]
Replacing `loff_t` with `off_t` in lib/ext2fs/imager.c and misc/e2fuzz.c worked for me.

**Comment by chenrui333** [comment]
Thanks, let me do it now (I cannot remember how exactly I did wrong last time), I think I used `patch`, instead of `inreplace`.

**Comment by chenrui333** [comment]
Thanks @EricFromCanada!! It does work. 🎉

**Pull request closed without merging**
