### PR TITLE
PostgreSQL 9.6.1

### PR DESCRIPTION
**Pull request by eagleflo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Let's get the ball rolling again after the progress in #5381 stalled. Bumped revision for every package in `brew uses postgresql`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
`pldebugger` and `zabbix` are last things that need fixed but given they both have fewer installs than `postgresql --devel` I think it'd be fine to use an upstream untagged commit, patch or, if it's still not fixed upstream, boneyard them.

**Comment by MikeMcQuaid** [comment]
Sorry, also `citus` but that's in the same boat.

**Comment by eagleflo** [comment]
Apparently Citus 6.0.0 was just released. Updated the PR to reflect that.

Zabbix only fails on El Capitan and it is most likely related to mac OS system library, not the updated PostgreSQL:

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/zabbix/3.0.1_1/sbin/zabbix_agentd
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/zabbix/3.0.1_1/sbin/zabbix_agentd
  Expected in: /usr/lib/libSystem.B.dylib
```

The other remaining failure is pgloader audit fail, which seems unrelated.

**Comment by MikeMcQuaid** [comment]
Great work @eagleflo. I've merged the Citus change and fixed the `pgloader` audit so you'll need to rebase.

CC @ilovezfs for thoughts/help on the `_clock_gettime`

**Comment by eagleflo** [comment]
Rebased. I can't reproduce the Zabbix issue on mac OS 10.12 and I don't have 10.11 virtualised. It's the only remaining issue.

**Comment by MikeMcQuaid** [comment]
CC @ilovezfs for help with a `_clock_gettime` issue.
@eagleflo Thanks for your patience, almost there!

**Comment by ilovezfs** [comment]
@MikeMcQuaid The clock_gettime problem is in zabbix, so it probably doesn't need to hold up this PR. Either way, this fix works for zabbix 3.0.1 (currently in core), zabbix 3.0.5 (LTS), and zabbix 3.2.1. Both zabbix 3.0.5 and 3.2.1 were released on 30 Sept 2016, so not sure which we want to upgrade to from 3.0.1.

```
diff --git a/Formula/zabbix.rb b/Formula/zabbix.rb
index 0aff1ec..a50db27 100644
--- a/Formula/zabbix.rb
+++ b/Formula/zabbix.rb
@@ -53,6 +53,11 @@ class Zabbix < Formula
       end
     end
 
+    if MacOS.version == :el_capitan && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
+      inreplace "configure", "clock_gettime(CLOCK_REALTIME, &tp);",
+                             "undefinedgibberish(CLOCK_REALTIME, &tp);"
+    end
+
     system "./configure", *args
     system "make", "install"
 
```

**Comment by MikeMcQuaid** [comment]
@eagleflo Could you apply that diff to the current PR and/or upgrade to zabbix 3.2.1 or zabbix 3.0.5 (in that order of preference) and see if either of them need this patch?

**Comment by ilovezfs** [comment]
zabbix 3.0.1, 3.0.5, and 3.2.1 all need the patch, so zabbix 3.2.1 failed as expected without it.

There are also more failed steps (https://bot.brew.sh/job/Homebrew%20Core/11446/)
```
    brew-test-bot.sierra.test pgloader
    brew-test-bot.sierra.test postgrest
    brew-test-bot.el_capitan.uninstall postgis
    brew-test-bot.el_capitan.audit postgis
    brew-test-bot.el_capitan.bottle postgis
    brew-test-bot.el_capitan.linkage --test virtualpg
    brew-test-bot.el_capitan.uninstall postgis
    brew-test-bot.el_capitan.test zabbix
    brew-test-bot.yosemite.uninstall postgis
    brew-test-bot.yosemite.audit postgis
    brew-test-bot.yosemite.bottle postgis
    brew-test-bot.yosemite.linkage --test virtualpg
    brew-test-bot.yosemite.uninstall postgis
```

**Comment by MikeMcQuaid** [comment]
A bunch of them can be ignored. Try the patch and we'll see where we are after.

**Comment by eagleflo** [comment]
All green, finally.

**Comment by MikeMcQuaid** [comment]
@eagleflo Thanks for your hard work and contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

Just a note for future reference: try to keep only one formula modified per-commit as I had to rewrite the history to get it like that. I may have accidentally removed some of your commit attribution in the process and I apologise profusely for that 😭

**Comment by eagleflo** [comment]
Thanks for merging this! I'll keep that in mind.

(Should it ever be truly necessary, you can change the author field in git commits with `git commit --amend --author "Andy Author <email@example.com>"`.)

**Comment by MikeMcQuaid** [comment]
> (Should it ever be truly necessary, you can change the author field in git commits with git commit --amend --author "Andy Author <email@example.com>".)

Yeh, I did that but then resquashed the commits and destroyed it again. Doh!

**Pull request closed without merging**
