### PR TITLE
ghostscript 9.24

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
This can be merged but Tavis has confirmed this version remains vulnerable to various trivial & severe security issues. Core may need to apply some patching if it decides it cares about that, but as far as I'm aware this release is in no worse a state than the status quo, so, not doing any harm.

**Review by fxcoudert — APPROVED** [review]

**Review by DomT4 — APPROVED** [review]
Let's fold this in. It seems likely we may want to consider additional patching in the near future but I'll take being able to start from a recent branch over having to lean on Debian doing a ton of backporting again.

**Comment by chdiza** [comment]
I don't know if anyone else has noticed, but `ghostscript` doesn't need `little-cms2` anymore.  It doesn't need it in 9.23 either.  They use their own internal fork now, and `./configure` doesn't even have a flag to attempt to force building against a brewed one.

**Comment by lembacon** [comment]
@chdiza Could you please open a PR for that? Thanks!

**Pull request closed without merging**
