### PR TITLE
vespa-cli 8.405.15

### PR DESCRIPTION
**Pull request by vespa-headless**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by stefanb** [comment]
Not yet on https://github.com/vespa-engine/vespa/releases

**Comment by chenrui333** [comment]
they never made a release for the cli stuff

image

**Comment by chenrui333** [comment]
- https://github.com/vespa-engine/vespa/issues/32365

**Comment by esolitos** [comment]
Thanks form opening the issue on the vespa repo, we created [the missing release](https://github.com/vespa-engine/vespa/releases/tag/v8.405.15).

_Background:_

We had some trouble with CI process in the past days, so Homebrew and Github releases got out of sync. 😊 

On homebrew we moved from v8.391.23 and v8.405.15, but on Github there was an additional release v8.403.12 so the script saw no changes from that version to v8.405.15 and created no release. 😓

**Review by fxcoudert — APPROVED** [review]

**Comment by chenrui333** [comment]
thanks @esolitos!

**Pull request merged**
