### PR TITLE
Secure URLs (plus minor fixes)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] [1] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

[1] `brew install`/`test` done for `pacparser`

-----

### CODE REVIEW

**Comment by vszakats** [comment]
Updated `pacparser` where I initially committed a non-final version.

**Comment by ilovezfs** [comment]
It looks like `jenkins-job-builder` is invisible to brew audit --online --strict.

**Comment by ilovezfs** [comment]
:closed_lock_with_key:

**Comment by vszakats** [comment]
Invisible to my standalone checker as well. It's a redirect to a different, but secure, page.
It'd be nice to detect redirects to HTTPS targets automatically - this case always needs manual verification though.

Thanks for the merge!

**Comment by vszakats** [comment]
There was another missed one in `gmsh`:
https://gitlab.onelab.info/gmsh/gmsh.git
Where the checked URL (https://gitlab.onelab.info/gmsh/gmsh.git/info/refs) returns 401 Unathorized, while the bare URL (https://gitlab.onelab.info/gmsh/gmsh.git) checks out fine.

I'll include that update in a future PR.

**Comment by ilovezfs** [comment]
hmm I wonder if that affects all gitlab.foo

**Comment by vszakats** [comment]
Since GitLab can be self-hosted there is a chance this is configured per-domain. Not idea if they have a custom domain option on the gitlab.com site though.

Running an updated check now to look for `/info` Git subdir instead of `/info/refs`. (no more http://gitlab.` examples in `homebrew-core` though)

**Pull request merged**
