### PR TITLE
python@3.8 3.8.6

### PR DESCRIPTION
**Pull request by jnozsc**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jnozsc** [comment]
for 10.14

```
Error: 9 failed steps!
brew test --retry --verbose bandcamp-dl
brew install --only-dependencies komposition
brew install --only-dependencies libmspub
brew install --only-dependencies libxmlsec1
brew install --only-dependencies mlt
brew linkage --test mlt
brew install --only-dependencies ola
brew install --only-dependencies pangomm
brew test --retry --verbose pcl
```

Most of them are reported at https://github.com/Homebrew/homebrew-core/pull/61539 as well

**Comment by SMillerDev** [comment]
Can you try running these commands outside of this PR to see if it's a pre-existing error?

**Comment by fxcoudert** [comment]
- I've submitted a PR for the `freexl` test failure
- `game-music-emu` fails with a clang-related error:

```
dyld: Library not loaded: @rpath/libclang_rt.ubsan_osx_dynamic.dylib
  Referenced from: /usr/local/opt/game-music-emu/lib/libgme.0.dylib
  Reason: image not found
```

- `gtksourceview3` has an undefined function, even though it is including the right header (I think?!):

```
test.c:4:17: error: implicit declaration of function 'gtk_source_utils_unescape_search_text' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  gchar *text = gtk_source_utils_unescape_search_text("hello world");
                ^
```

**Comment by fxcoudert** [comment]
- `gtksourceview3` was fixed in 62aea777512b44e2c00f398bdaed4a13a5e65143
- gdal is updated
- other test issues are fixed
- I'm trying to understand the `game-music-emu` failure here: https://github.com/Homebrew/homebrew-core/pull/62125

Restarting CI

**Comment by bsolomon1124** [comment]
Appreciate any attention that can be given to this as 3.8.6 contains a number of useful [bugfixes](https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-6-final) :)

**Comment by SMillerDev** [comment]
Feel free to make pull requests to fix failing tests.

**Comment by fxcoudert** [comment]
It looks like it didn't pick up the latest versions/revisions (tests fixed, gdal update, etc)

**Comment by SMillerDev** [comment]
Restarted CI.

**Comment by SMillerDev** [comment]
Just these and `stellar-core` for 10.13, but I'm fine with ignoring that seeing how close we are to dropping support for it.

```
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose pcl
```

**Comment by sharris40** [comment]
I commented at https://github.com/Homebrew/homebrew-core/pull/61539#issuecomment-705838078 about those two. bandcamp-dl is broken upstream, and pcl is failing tests because eigen is broken upstream.

**Comment by SMillerDev** [comment]
I'm 👍 for merging then, if @fxcoudert is okay too.

**Review by fxcoudert — APPROVED** [review]

**Comment by sharris40** [comment]
Just to note, that was a build failure with `pcl`, not just a test failure. Should we cherry-pick the patch for `eigen` so we can get `pcl` building again?

**Comment by fxcoudert** [comment]
> that was a build failure with pcl, not just a test failure

Ouch 😭 

Please open a PR with an eigen patch and pcl revision bump, we'll try to merge it quickly

**Pull request closed without merging**
