### PR TITLE
netlify-cli 2.67.0

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zachauten** [comment]
```
Error: An exception occurred within a child process:
  RuntimeError: npm failed to pack /private/tmp/netlify-cli-20201029-30656-1l0c26r/package
```
Anyone know what causes this?

**Comment by chenrui333** [comment]
> ```
> Error: An exception occurred within a child process:
>   RuntimeError: npm failed to pack /private/tmp/netlify-cli-20201029-30656-1l0c26r/package
> ```
> 
> Anyone know what causes this?

It might be due to the npm 7 change we made.

**Comment by chenrui333** [comment]
See https://github.com/Homebrew/brew/pull/8973

**Comment by chrmoritz** [comment]
The error from the `npm pack --ignore-scripts` command (swallowed by homebrew) is:

```
npm pack --ignore-scripts                                                                                                                                                                                                                1009  00:13:15  

> netlify-cli@2.67.0 prepack
> oclif-dev manifest && npm prune --prod

sh: oclif-dev: command not found
npm ERR! code 127
npm ERR! path /private/tmp/test/package
npm ERR! er.stdout.trim is not a function
```

Looks like the `--ignore-scripts` argument is ignored for some reasons and it tries to run the prepack script, which fails because of the missing devDependencies.

**Comment by zachauten** [comment]
Thanks @chrmoritz @chenrui333!

@Homebrew/core Has anyone else ran into this on other node formula? 

It seems like installing dev dependencies that aren't really necessary could take a lot of time for some formulae, would it be better to find a workaround to ignore scripts for `npm pack`?

**Comment by dtrodrigues** [comment]
I've run into this recently:
https://github.com/Homebrew/homebrew-core/pull/63513
https://github.com/Homebrew/homebrew-core/pull/63514
https://github.com/Homebrew/homebrew-core/pull/63515

**Comment by chrmoritz** [comment]
Also just installing all the devDependencies wouldn't be enough in a lot of cases, because the npm registry package often already contains only the transpiled files. It's just that the `npm pack --ignore-scripts` is part of our hack to get the global npm installation compatible with the homebrew way of installing software.

A possible workaround would be to just remove the `prepare` script from the `package.json` of all affected formulae (which would basically emulate what `--ignore-scripts` previously did.

**Comment by zachauten** [comment]
Going to close this for now, opened #63798 because there are multiple formulae with this issue.

**Comment by chenrui333** [comment]
#64235

**Pull request closed without merging**
