### PR TITLE
ansible 2.7.0

### PR DESCRIPTION
**Pull request by igas**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is my first time dealing with aliases and older versions, not sure if I have done it right.

### CODE REVIEW

**Review by commitay — COMMENTED** [review]
Please remove the `ansible@2.6` formula.

**Comment by igas** [comment]
@commitay done

**Review by paaloeye — APPROVED** [review]

**Comment by Paulche** [comment]
@commitay It appears to be a false negative. The CI failed to execute `brew audit ansible --online` with `Error: No such file or directory - rubocop`. It certainly has nothing to do with `ansible`. Are there any means to re-try this build?

**Comment by Paulche** [comment]
@mxcl How can I help to make it merged?

**Comment by mxcl** [comment]
Sorry I am not familiar with how brew’s CI works.

**Comment by Paulche** [comment]
@igas Hey Igor, could you please amend your commit (just to reset a hash of your commit) and force-push it again. This way you, hopefully, will give CI a chance to pass.

**Comment by fxcoudert** [comment]
Thank you @igas for your contribution. I am going to close this, as I have opened #32947 in order to track the update and migrate ansible to Python 3 at the same time.

**Pull request closed without merging**
