### PR TITLE
openldap 2.5.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
only on `11-arm64`
```
brew install --only-dependencies archi-steam-farm
brew install archi-steam-farm
```

**Comment by carlocab** [comment]
`archi-steam-farm` (and `gitversion`) depends on `dotnet`, which is not yet bottled for ARM. We can ignore those on ARM.

**Comment by SMillerDev** [comment]
Julia is failing on Ubuntu:

```
==> brew test --retry --verbose julia
==> FAILED
==> Testing julia
==> /home/linuxbrew/.linuxbrew/Cellar/julia/1.6.2_1/bin/julia -E '2 + 2'
ERROR: Unable to find compatible target in system image.

==> Testing julia (again)
==> /home/linuxbrew/.linuxbrew/Cellar/julia/1.6.2_1/bin/julia -E '2 + 2'
ERROR: Unable to find compatible target in system image.

Error: julia: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 1
```

**Comment by carlocab** [comment]
Probs just spurious. Linux CI was green before @chenrui333 force-pushed it to re-run the tests. See https://github.com/Homebrew/homebrew-core/runs/3177200875

**Review by carlocab — APPROVED** [review]

**Comment by chenrui333** [comment]
the julia test failure is interesting.

**Pull request closed without merging**
