### PR TITLE
velero: renamed from ark

### PR DESCRIPTION
**Pull request by nrb**
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
You opened a draft pull request which cannot be merged.

Also `velero` version `0.11.0` isn't released. The latest release is `0.10.1`.

**Comment by nrb** [comment]
I am aware - I’m on the Velero team and holding this in place until the release is made.

**Comment by skriss** [comment]
@nrb can we take this out of draft status now?

**Comment by skriss** [comment]
all of the tests LGTM

**Comment by nrb** [comment]
@Moisan v0.11.0 is out and the PR is now out of draft status.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @nrb for the pull request!

**Pull request closed without merging**
