### PR TITLE
ttylog 0.29

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Scanning dependencies of target ttylog
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/ttylog.dir/build.make CMakeFiles/ttylog.dir/build
[ 50%] Building C object CMakeFiles/ttylog.dir/ttylog.c.o
/usr/local/Homebrew/Library/Homebrew/shims/super/clang   -I/tmp/ttylog-20161128-42860-12odcf/ttylog-0.29 -I/tmp/ttylog-20161128-42860-12odcf/ttylog-0.29/build  -Wall -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -o CMakeFiles/ttylog.dir/ttylog.c.o   -c /tmp/ttylog-20161128-42860-12odcf/ttylog-0.29/ttylog.c
/tmp/ttylog-20161128-42860-12odcf/ttylog-0.29/ttylog.c:52:3: error: unknown type name 'timer_t'; did you mean 'time_t'?
  timer_t timerid;
  ^~~~~~~
  time_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sys/_types/_time_t.h:30:26: note: 'time_t' declared here
typedef __darwin_time_t         time_t; 
                                ^
/tmp/ttylog-20161128-42860-12odcf/ttylog-0.29/ttylog.c:140:27: error: variable has incomplete type 'struct itimerspec'
        struct itimerspec new_value;
                          ^
/tmp/ttylog-20161128-42860-12odcf/ttylog-0.29/ttylog.c:140:16: note: forward declaration of 'struct itimerspec'
        struct itimerspec new_value;
               ^
2 errors generated.
make[2]: *** [CMakeFiles/ttylog.dir/ttylog.c.o] Error 1
make[1]: *** [CMakeFiles/ttylog.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by vladshablinsky** [comment]
Seems like this version is not compatible with OS X `sys/time.h` and `sys/types.h` on OS X doesn't define `timer_t`.

**Comment by ilovezfs** [comment]
Yup, https://github.com/rocasa/ttylog/commit/9bede4f00583157385c9cae67732b7f50eb6eaba broke compatibility.

Reverting it (https://gist.github.com/ilovezfs/48d667ec4dd15655dbc71e26c090f2c6) fixes it but this will need to be reported as you said.

**Comment by ilovezfs** [comment]
Going to :skull: since https://github.com/rocasa/ttylog/issues/6 was closed.

**Comment by ilovezfs** [comment]
:skull_and_crossbones: https://github.com/Homebrew/homebrew-core/pull/7479.

**Pull request closed without merging**
