### PR TITLE
python@3.x: use f-string in sitecustomize.py

### PR DESCRIPTION
**Pull request by XuehaiPan**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by XuehaiPan** [comment]
Require label `CI-syntax-only` and `CI-no-bottles`.

**Comment by SMillerDev** [comment]
Why would we want to do it this way?

**Comment by XuehaiPan** [comment]
> Why would we want to do it this way?

The old approach with string concatenation (`+`) has been there since the first `python` formula (Python 3.5) in homebrew-core several years ago. F-strings are the recommended way to do string manipulation since Python 3.6. It is more "Pythonic" and reduces explicit type cast `str(...)` and string concatenation `"xxx" + str(...)`. This is more like we do string interpolation in Ruby (the `#{}` operator in double-quoted strings).

**Comment by iMichka** [comment]
I agree that f strings are the more modern way of writing this. +1 on the change

**Comment by XuehaiPan** [comment]
Would anyone be able to review this?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
