### PR TITLE
solr 6.4.1

### PR DESCRIPTION
**Pull request by steve0hh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
Thanks for your contribution! Would you mind putting the mirror back? And why not go to solr 6.5.0 while you are at it?

**Comment by steve0hh** [comment]
Hmm.. weird. it works on my end.

**Comment by neutric** [comment]
```
solr:
  * Formula has other versions so create an alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/solr.rb solr@6.4
```
@steve0hh All should be good now though, I added the missing alias for you.

**Comment by steve0hh** [comment]
Ahh.. thanks! anyway, once i'll get 6.5.0, I will create another PR.. 😄 

currently using 6.4.1 for my school assignment. don't want to mess the env up.

**Comment by neutric** [comment]
Okay! :D Thanks for the contribution and looking forward to your next PR!

**Comment by steve0hh** [comment]
@neutric just to check, let's say i've bumped the solr formula to version 6.5.0, do i also rename the alias to solr@6.5?

sorry, couldn't find any documentation on it.

**Comment by neutric** [comment]
@steve0hh Haven't done this one myself, but I believe that is all that needs to be done.

**Pull request merged**
