### PR TITLE
jboss-forge 3.9.3.Final - fixed download link

### PR DESCRIPTION
**Pull request by gastaldi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by gastaldi** [comment]
Can someone please merge this PR? The formula is broken with the current download link atm

**Comment by fxcoudert** [comment]
No, we cannot merge this until it is confirmed that the file re-release is intentional and not malicious:

```
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

**Comment by gastaldi** [comment]
@fxcoudert I am the project lead and maintainer of JBoss Forge, what do I need to do to confirm that this file re-release is not malicious?

**Comment by fxcoudert** [comment]
@gastaldi point us to an announcement on the product's page of the re-release. Right now, the main download link:

Capture d’écran 2019-07-04 à 16 11 22

points to `http://downloads.jboss.org/forge/releases/3.9.3.Final/forge-distribution-3.9.3.Final-offline.zip` and announces its checksum as `5a9cfe8b45c07766107043213a729a8125ef2b88c228762f48e27c36514ea7c1`

**Comment by gastaldi** [comment]
Hm, aparently our Akamai servers are still caching the old value. I'll release another version, that would be easier. Closing this now

**Pull request closed without merging**
