### PR TITLE
swc 1.2.82 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
The `musl` binary was probably compiled so that it would work on `musl` based systems and should be deleted.  My only concern about keeping the `glibc` linked binary is that it won't be using using brewed `glibc`, and may not work for users with older `glibc`.  We should see which ABI version of `glibc` the binary needs.  The oldest version of `glibc` supported by a distro I'm aware of is 2.11 in SUSE Linux Enterprise Server 11, which is supported through 2022, so if it is at or below that it's not a concern.  If it is higher than that it could be an issue, expecially if it is higher than 2.23, which is the version we currently ship in our `glibc` formula.  

The dependency on nightly `rust` is unfortunate.  IMO the `swc` upstream should be asked why they don't release a version that builds against the latest stable Rust.  I think we should start pushing back on `npm` and `maven` packages to do a better job of handling native code.  In many cases the authors may be unaware of how problematic shipping native binaries like this can be for package managers.

**Comment by cho-m** [comment]
We could always try stable Rust since it is possible that whatever Nightly features in-use are available in current stable, unless they are using Nightly-only syntax.

From binary:
```
Version References:
  required from libdl.so.2:
    0x09691a75 0x00 19 GLIBC_2.2.5
  required from librt.so.1:
    0x09691a75 0x00 15 GLIBC_2.2.5
  required from ld-linux-x86-64.so.2:
    0x0d696913 0x00 13 GLIBC_2.3
  required from libm.so.6:
    0x09691a75 0x00 07 GLIBC_2.2.5
  required from libgcc_s.so.1:
    0x09276060 0x00 12 GCC_4.2.0
    0x0b792650 0x00 10 GCC_3.0
    0x0b792653 0x00 06 GCC_3.3
  required from libpthread.so.0:
    0x09691973 0x00 17 GLIBC_2.3.3
    0x09691972 0x00 08 GLIBC_2.3.2
    0x09691a75 0x00 04 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696919 0x00 18 GLIBC_2.9
    0x06969195 0x00 16 GLIBC_2.15
    0x06969194 0x00 14 GLIBC_2.14
    0x0d696914 0x00 11 GLIBC_2.4
    0x06969198 0x00 09 GLIBC_2.18
    0x09691974 0x00 05 GLIBC_2.3.4
    0x09691a75 0x00 03 GLIBC_2.2.5
    0x0d696913 0x00 02 GLIBC_2.3
```

**Comment by danielnachun** [comment]
If we can try it that would be great.  This requires `glibc` 2.18, well above 2.11 and our official minimum supported version of 2.13.

**Comment by cho-m** [comment]
It may end up being a bit of work to directly use `rust` as dependency as we would need to manually run the commands.

Upstream has `npm run build` script, which uses `rustup` under-the-hood. This is what is run on upstream CI to build the binaries.

Also need to find where to manually install the binaries into npm hierarchy. The current formula does this by downloading pre-builts via npm:
- https://www.npmjs.com/package/@swc/core-linux-x64-gnu
- https://www.npmjs.com/package/@swc/core-darwin-arm64
- https://www.npmjs.com/package/@swc/core-darwin-x64

**Comment by chenrui333** [comment]
Anything that I can do in here to help getting the PR merged?

**Comment by danielnachun** [comment]
I'd like to see us try to build this with `cargo install`.  The source tree appears to have the files for this to work.  Assuming it does build, copying it into the right directories should not be difficult.

**Comment by cho-m** [comment]
I think the Rust code gets built using [`napi`](https://github.com/napi-rs/napi-rs), which runs `rustup` commands under-the-hood, e.g. https://github.com/napi-rs/napi-rs/blob/main/cli/src/build.ts#L57-L63
```ts
    const triple = this.targetTripleDir
      ? parseTriple(this.targetTripleDir)
      : getDefaultTargetTriple(
          execSync('rustup show active-toolchain', {
            env: process.env,
          }).toString('utf8'),
        )
```

Compiling Rust code would require GitHub source (as npmjs.org source only has JS/TS code) and `rustup-init` formula dependency. Afterward, similar steps as upstream CI can be done https://github.com/swc-project/swc/blob/master/.github/workflows/publish-node.yml
```yaml
      - name: Install node dependencies
        run: npm i

      - name: Build
        shell: bash
        run: npm run build
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"
```

`npm run build` ends up running `tsc -d && napi build --platform --release --cargo-name node --cargo-flags=\"-p node\"` (`tsc` and `napi` are installed via npm).

---

The part I don't know is if it is possible to use GitHub source for npm dependency.

The easy way would be to keep current install and just replace the pre-built binary with locally compiler version, but it adds overhead of extra resource.

When I quickly attempted using GitHub source in place of npmjs.org source for npm install steps, I think it installed a lot of extra stuff.

**Pull request closed without merging**
