### PR TITLE
swi-prolog 8.0.0

### PR DESCRIPTION
**Pull request by ghost**
Created with `brew bump-formula-pr`.

---

New version of swi-prolog

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by Zialus** [comment]
What's the current status of swi-prolog on homebrew?

**Comment by pvaibhav** [comment]
I've sent a PR to update the formula to the current stable version 8.0.2

Until it's merged, `brew install --HEAD swi-prolog` should work to install the dev branch.

**Pull request closed without merging**
