### PR TITLE
ghc 8.4.1

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can we take this opportunity to try and use Homebrew's gmp rather than vendoring it?

**Comment by MikeMcQuaid** [comment]
@fxcoudert I added a better comment in 2fcf0c6620aaa8b3547f9ef34f696f045c25b933.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@MikeMcQuaid thanks! I'm not sure why we couldn't statically link to the existing Homebrew gmp (where we build static libs), but if you feel vendoring is the best way to go…

The `ENV.deparallelize` in installing gmp is unnecessary, it installs well in parallel nowadays. Also forcing `MPN_PATH` is probably a little less robust that the gmp formula's solution of `args << "--build=core2-apple-darwin#{`uname -r`.to_i}"`

On the other hand, this formula's use of `--with-pic` for static lib is much nicer that `gmp.rb`'s performance-killing `--disable-assembly`. Will open a PR for that one.

**Comment by MikeMcQuaid** [comment]
> I'm not sure why we couldn't statically link to the existing Homebrew gmp (where we build static libs), but if you feel vendoring is the best way to go…

If this can all be done with no negative side-effects: I'm interested!

**Comment by fxcoudert** [comment]
> If this can all be done with no negative side-effects: I'm interested!

I'll look at it.

To me it seems that dynamic linking by default is not a bug, but a feature: not duplicating libraries for every haskell program seems like a win to me. And ghc can be asked to compile statically if need be with `-optl-static` (https://ro-che.info/articles/2015-10-26-static-linking-ghc)

Two solutions come to mind, to avoid duplication. Both are ugly:

- have `ghc` depend on `gmp` at build, and copy its static lib to put it inside its own cellar
- create in `gmp` a `lib/static` directory, and add a symbolic link to the static library there; that way we can point `ghc` to that directory

**Comment by MikeMcQuaid** [comment]
> To me it seems that dynamic linking by default is not a bug, but a feature: not duplicating libraries for every haskell program seems like a win to me.

It's not clear to me every Haskell program needs `gmp` just because `ghc` is  built with it.



> have ghc depend on gmp at build, and copy its static lib to put it inside its own cellar

Can't it use the static `gmp` to build into the binary?

**Comment by fxcoudert** [comment]
`ghc` links the binaries it produces against `gmp` for integer arithmetic (maybe not all, and only the ones that depend on bit int operations).

**Comment by ilovezfs** [comment]
Let's leave this as it is. There's no user reported issue here.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
@ilovezfs Agreed, apologies for taking this further than necessary.

**Comment by fxcoudert** [comment]
@ilovezfs agreed… the time it takes for CI to build leaves ample time for chatting about potential improvements :)

**Pull request closed without merging**
