### PR TITLE
wxmac: backport upstream High Sierra build fixes

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
Ref: https://github.com/Homebrew/formula-patches/pull/156

**Comment by DomT4** [comment]
Failure looks extremely unrelated.

**Comment by DomT4** [comment]
@BrewTestBot try again.

**Comment by DomT4** [comment]
@BrewTestBot Come on, you can do better than that.

**Comment by ilovezfs** [comment]
I'd prefer we just request a new release upstream.

**Comment by DomT4** [comment]
I can ask but some of the patched-here files in the current stable branch haven't been touched for 4+ years and that doesn't make me think they're desperate to fix the existing stable before 10.13 lands.

**Review by ProfessorCoal — APPROVED** [review]

**Comment by ilovezfs** [comment]
>I can ask but some of the patched-here files in the current stable branch haven't been touched for 4+ years and that doesn't make me think they're desperate to fix the existing stable before 10.13 lands.

If they say, "we'll release a new stable version once 10.13 GM is out," while not ideal, that would make me more comfortable with merging a 1,366 line patch.

**Comment by DomT4** [comment]
I'll open an Issue upstream shortly. If it would make you feel any better, a lot of the patch could be turned into a rather extensive `inreplace` to achieve the same thing.

**Comment by ilovezfs** [comment]
@DomT4 na, it's just about starting the bidding process :)

**Comment by DomT4** [comment]
Alright, cool. Upstream don't have Issues open on GitHub so I'll get to dig out my old `wxWidgets` Trac account, how fun 😭.

**Comment by DomT4** [comment]
https://trac.wxwidgets.org/ticket/17929#ticket

**Comment by DomT4** [comment]
Discussion ongoing with upstream. Not sure how much you're watching the ticket but waiting to find out how desperately they want to keep 10.5 support in the 3.0.3x branch.

**Comment by ilovezfs** [comment]
>Concerning the release plan, I'm pretty sure 3.0.4 won't be released before 2 months

In that case, a maximum macOS requirement is called for until the situation changes.

>please submit the patch (attach it here or open a PR on Github if you prefer) nevertheless

sounds like a reasonable request

>but waiting to find out how desperately they want to keep 10.5 support in the 3.0.3x branch.

If 10.5 support is more important to them than 10.13 support, then I don't really know what to say other than :disappointed: and maximum macOS requirement.

**Comment by ilovezfs** [comment]
I guess another option would be to start treating 3.1.x as stable.

**Comment by DomT4** [comment]
> sounds like a reasonable request

Plan to file a PR or several later today. Just want clarification on the 10.5 situation. IMO I think 10.5 support at this point is utterly pointless but I entirely appreciate `wxWidgets` as a project certainly has more heft than I do, so one way or another I'm going to have to respect their wishes.

> In that case, a maximum macOS requirement is called for until the situation changes.

We had a very similar situation when Yosemite was pre-release IMO but I can't remember how we chose to handle it at the time. Right now I can't remember if you were a maintainer then? Not that it matters, simply hoping you can remember what I cannot 😆. My memory is not exactly ideal given I'm not really that old 🤔.

> If 10.5 support is more important to them than 10.13 support, then I don't really know what to say other than 😞

Yeah. I just can't with the 10.5 support. It has been, what, 7+ years since 10.5 even received security updates? I'm hoping upstream responds to my last message with an acknowledgement that moving to 10.6 as a minimum requirement isn't unreasonable, but we'll see.

**Comment by ilovezfs** [comment]
>Right now I can't remember if you were a maintainer then?

No.

>We had a very similar situation when Yosemite was pre-release IMO but I can't remember how we chose to handle it at the time.

The Git history shows three rounds of patching for 10.10. :see_no_evil:

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
> No.

To be honest I'm not even sure whether I was. I think I "served" as a whole-brew maintainer rather than simply part-brew from like May 2015, so yeah, that would be after Yosemite went stable 🤔.

> The Git history shows three rounds of patching for 10.10. 🙈

I thought I remembered it being a nightmare 😄. Yosemite was fun.

I've left a message on the upstream commit, which I hate doing to be honest but eh, asking the author of the change to weigh in on the idea of backporting it to the existing stable/devel branches. I don't mind adding some kind of silly compatibility layer but at the same time if upstream turn around & go eh 10.5 support can go away I don't want to have invested a chunk of time thinking about that layer for no reason.

**Comment by ilovezfs** [comment]
@DomT4 on the ticket

>Changed 22 hours ago by csomor
>
>For 3.0 I'd suggest defining __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES to >1 when building, this way the source doesn't have to be changed, and we maintain builds under macOS < 10.6

https://trac.wxwidgets.org/ticket/17929#comment:3

**Comment by DomT4** [comment]
Aye, noticed. I upgraded my own machine to High Sierra, albeit passing on the APFS change for now, so I'll do some more testing later today.

**Comment by fxcoudert** [comment]
Suggested alternatives (as per [this header](https://opensource.apple.com/source/CarbonHeaders/CarbonHeaders-18.1/AssertMacros.h), look for “For time immemorial”) to the ugly patch:

- compile with `-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1` in your `CFLAGS`
- massive `inreplace`
- `find . -name '*.[c|cc|cp|cpp|m|mm|h]' -print0 |  xargs -0 tops replace "verify_noerr(<b args>)" with "__Verify_noErr(<args>)"`

**Comment by ilovezfs** [comment]
I'd still like to see a release here. If the fix is actually just to add `__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES` then they should do that.

**Comment by DomT4** [comment]
Apologies, life is sometimes time-demanding sigh. The `CPPFLAGS` addition works as directed.

Weird little message popped up at the end of the install process, especially given `wxmac` doesn't have a `post_install` stage. Trying to work out what's going on there or if it happens regularly 😅
```
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall wxmac`
==> Summary
🍺  /usr/local/Cellar/wxmac/3.0.3.1: 810 files, 23.7MB, built in 4 minutes 35 seconds
```

**Comment by DomT4** [comment]
No idea about the above. I reproduced it multiple times by doing `brew reinstall wxmac` but after doing `brew rm wxmac && brew install wxmac` the problem no longer reproduces. Odd but 🤷‍♂️.

**Comment by ilovezfs** [comment]
@MikeMcQuaid I wonder if it's a regression from https://github.com/Homebrew/brew/pull/2959.

**Comment by MikeMcQuaid** [comment]
> Weird little message popped up at the end of the install process, especially given wxmac doesn't have a post_install stage.

That message is printed unconditionally regardless of whether or not a `post_install` method is defined, FYI.

**Comment by ilovezfs** [comment]
@MikeMcQuaid But presumably only if you've actually passed `--build-bottle` …

**Comment by MikeMcQuaid** [comment]
Yes, should be. Is that not the case here? Apologies for 💤

**Comment by DomT4** [comment]
Yeah. Definitely didn't pass `--build-bottle` as a flag.

**Comment by DomT4** [comment]
> I'd still like to see a release here

I'll ask upstream about this shortly FYI. Or I might just try and come up with a patch to do that or something, I don't know, maybe that's the path of least resistance 🤷‍♂️.

**Comment by MikeMcQuaid** [comment]
> Yeah. Definitely didn't pass --build-bottle as a flag.

Should be resolved by https://github.com/Homebrew/brew/commit/eaea27c960de3bf76fc9976bfad037c0a559018d if it's what we thought.

**Comment by ilovezfs** [comment]
:tada:

**Comment by DomT4** [comment]
I'm handing this off to ILZ per the discussion in https://github.com/Homebrew/homebrew-core/pull/16453.

**Pull request closed without merging**
