### PR TITLE
rust 1.69.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
I think it's because https://github.com/Homebrew/homebrew-core/labels/CI-no-fail-fast was not added when `github.event` was captured.

**Comment by ZhongRuoyu** [comment]
## ARM Failures

- [ ] `brew test --retry --verbose asuka`
- [ ] `brew install --build-from-source buku`
- [ ] `brew test --retry --verbose charm-tools`
- [ ] `brew install --build-from-source duplicity`
- [ ] `brew install --build-from-source dvc`
- [ ] `brew test --retry --verbose exa`
- [ ] `brew test --retry --verbose geph4`
- [ ] `brew install --build-from-source gfold`
- [ ] `brew link gfold`
- [ ] `brew test --retry --verbose gfold`
- [ ] `brew install --build-from-source grin`
- [ ] `brew install --build-from-source mitmproxy`
- [ ] `brew fetch --build-from-source --retry qsv`
- [ ] `brew install --build-from-source roapi`
- [ ] `brew test --retry --verbose snapcraft`
- [ ] `brew install --build-from-source tremor-runtime`
- [ ] `brew install --build-from-source trezor-agent`
- [ ] (13-arm64) `brew install --build-from-source newsboat`
- [ ] (12-arm64, 11-arm64) `brew test --retry --verbose drill`
- [ ] (12-arm64)`brew fetch --build-from-source --retry page`
- [ ] (11-arm64) `brew test --retry --verbose drill`
- [ ] (11-arm64) `brew install --build-from-source chatblade`

**Comment by jqnatividad** [comment]
> * [ ]  `brew fetch --build-from-source --retry qsv` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/4784368511/jobs/8509780504?pr=128865#step:7:9056)): [qsv 0.100.0 #128734 (comment)](https://github.com/Homebrew/homebrew-core/pull/128734#issuecomment-1520774952)

qsv shouldn't be counted as the error was fetching the yanked 0.100.0 release

**Comment by ZhongRuoyu** [comment]
Yes, thanks for pointing that out, @jqnatividad. The purpose of this checklist is only to list all the failures to follow up. They are not necessarily blockers.

**Comment by ZhongRuoyu** [comment]
We should be good to ship this now. All Rust-related issues are identified (see [checklist](https://github.com/Homebrew/homebrew-core/pull/128865#issuecomment-1521797468)) and are either fixed or to be fixed after the merge.

Many issues seem to be related to the recent `setuptools` upgrade, which shouldn't block us from shipping the Rust release.

---

A note on the `grin` failure (`warning: variable 'run_count' set but not used`): it is due to an unused variable and the `-Wall` flag. A simple fix would be `ENV.append_to_cflags "-Wno-unused-but-set-variable"`. But this error comes from the `croaring-sys` crate, and aside from `oniguruma`, it seems to be vendoring `libgit2`, `libz`, and some more (see https://github.com/mimblewimble/grin/blob/v5.1.2/Cargo.lock). It's not a blocker so I will have a closer look at it later this week.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
