### PR TITLE
qemu: backport M1 HVF patches to support recent Linux guests

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**Update** (Mar 14, 2022): The content of this PR was merged into QEMU 6.2.0_1: https://github.com/Homebrew/homebrew-core/commit/0301a2b3a8781d2fa4d3d46bec29644d69cf13db

- - -
Backport the following commits from QEMU master (QEMU 7):
- qemu/qemu@ad99f64f hvf: arm: Use macros for sysreg shift/masking
- qemu/qemu@7f6c295c hvf: arm: Handle unknown ID registers as RES0

These patches are required for running the following guests:
- Linux 5.17 https://github.com/torvalds/linux/commit/9e45365f1469ef2b934f9d035975dbc9ad352116
- Ubuntu 21.10, kernel 5.13.0-35.40  (March 2022) https://kernel.ubuntu.com/git/ubuntu/ubuntu-impish.git/commit/?id=7936f2a576f1d7c3e1a80f8a07a217cdfa2b7338
- Ubuntu 20.04, kernel 5.4.0-103.117 (March 2022) https://kernel.ubuntu.com/git/ubuntu/ubuntu-focal.git/commit/?id=0d9955120cd5b59c6082668fd235cdf77a33a880

See https://gitlab.com/qemu-project/qemu/-/issues/899

Thanks to @fuzmish for testing: https://github.com/lima-vm/lima/issues/712#issuecomment-1065828766

> |`images.location`|default qemu|patched qemu|
> |-|-|-|
> |[impish/20220309](https://cloud-images.ubuntu.com/impish/20220309/)\*1|:x:|:white_check_mark:|
> |[impish/20220204](https://cloud-images.ubuntu.com/impish/20220204/)|:white_check_mark:|:white_check_mark:|
> |[impish/20220201](https://cloud-images.ubuntu.com/impish/20220201/)|:white_check_mark:|:white_check_mark:|
> |[focal/20220308](https://cloud-images.ubuntu.com/focal/20220308/)|:x:|:white_check_mark:|
> |[focal/20220307](https://cloud-images.ubuntu.com/focal/20220307/)|:white_check_mark:|:white_check_mark:|
> |[focal/20220302](https://cloud-images.ubuntu.com/focal/20220302/)|:white_check_mark:|:white_check_mark:|

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by scalp42** [comment]
definitely needed 🙏

**Comment by SMillerDev** [comment]
Those seem like serious problems. Is QEMU not going to release a fixed version for this?

**Comment by fuzmish** [comment]
@SMillerDev According to their [wiki](https://wiki.qemu.org/Planning/7.0), the next version, v7.0, is scheduled for release in mid-April. (Note: I am not a member/contributor of QEMU.)

| | |
|-|-|
2022-03-15 | Hard feature freeze. Tag rc0
2022-03-22 | Tag rc1
2022-03-29 | Tag rc2
2022-04-05 | Tag rc3
2022-04-12 | Release; or tag rc4 if needed
2022-04-19 | Release if we needed an rc4

If the homebrew project does not encourage manual patching, it may be acceptable to provide a version based on some RC tag.

**Comment by AkihiroSuda** [comment]
> If the homebrew project does not encourage manual patching, it may be acceptable to provide a version based on some RC tag.


Homebrew does not accept RC, IIUC
https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

**Comment by Bo98** [comment]
Given the patches will only be around for a month I'm provisionally ok with this, but I'll probably open a PR rolling this and #96655 together rather than two revision bumps.

**Comment by carlocab** [comment]
Will be merged in #96655.

**Comment by carlocab** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/0301a2b3a8781d2fa4d3d46bec29644d69cf13db.

**Pull request closed without merging**
