### PR TITLE
i2p: fix i2prouter cannot start

### PR DESCRIPTION
**Pull request by scientificworld**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Because the appropriate path is not set, i2prouter will not start. Here is a log as an example.

```
$ i2prouter console
Running I2P Service...
wrapper  | ERROR: Could not write pid file /opt/homebrew/Cellar/i2p/2.4.0/libexec/_USER_HOME/.i2p/i2p.pid: No such file or directory
wrapper  | Unable to write to the configured log file: _USER_HOME/.i2p/wrapper.log (No such file or directory)
wrapper  |   Falling back to the default file in the current working directory: /opt/homebrew/Cellar/i2p/2.4.0/libexec/wrapper.log
**Failed to load the wrapper**

The most likely reason is that a supported version of the java
wrapper is not available in the I2P installation package for your
platform. It may be possible to manually download and install
a compatible wrapper for your system.
See https://geti2p.net/en/misc/manual-wrapper for hints.

In the meantime, you may start I2P by running the script
/opt/homebrew/Cellar/i2p/2.4.0/libexec/runplain.sh
```

After replacing the paths, it can start properly.

### CODE REVIEW

**Comment by SMillerDev** [comment]
How do those variables get there? Since it just seems like an upstream bug

**Comment by scientificworld** [comment]
> How do those variables get there? Since it just seems like an upstream bug

The comment in `libexec/i2prouter` says:

```
# Note that (percent)INSTALL_PATH, (percent)USER_HOME,  and (percent)SYSTEM_java_io_tmpdir
# should have been replaced by the izpack installer.
# If you did not run the installer, replace them with the appropriate paths.
```

I think it's not an upstream bug.

**Review by chenrui333 — COMMENTED** [review]
LGTM

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@scientificworld thanks for the patch and your first PR to homebrew-core! 🎉

**Pull request merged**
