### PR TITLE
jhipster 4.10.0

### PR DESCRIPTION
**Pull request by jdubois**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jdubois** [comment]
Sorry, I'm closing the PR as the build failed -> I already did lots of homebrew PRs with this script, which is very simple, maybe something changed in the testing process?

**Comment by ilovezfs** [comment]
I think it's just because you changed the output to be a sentence.

```
JHipster execution is complete!
```

vs.
```
Execution complete
```

**Comment by jdubois** [comment]
Oh yes, I'm stupid!!!!

**Comment by jdubois** [comment]
Oh you corrected my build, thank you so much @ilovezfs

**Comment by ilovezfs** [comment]
@jdubois you're welcome! Shipped :rocket:

**Pull request closed without merging**
