### PR TITLE
python@2: delete

### PR DESCRIPTION
**Pull request by iMichka**
EOL 1 January 2020.
We gave it 1 month more to live so that people had time to migrate.
All in all, developers had 11 years to do their migration.

You can use the `brew extract` command and maintain python@2 in your own
tap if necessary:
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
As decided during FOSDEM with the other maintainers, and announced here:
https://twitter.com/MacHomebrew/status/1224356881122189313

We will remove python@2 on Monday February 10.

**Review by jonchang — APPROVED** [review]

**Comment by SMillerDev** [comment]
Needs the alias removed too

**Comment by lithammer** [comment]
Are the bottles also removed? I guess what I'm asking is, would it make sense to keep this in a tap?

```rb
  bottle do
    sha256 "accfaa922708f00afb69ab230199f96e6ecdddd248a1eca586ce1e5e5cfd732b" => :catalina
    sha256 "54d3351d6be8268b2f5017894dcc8e083811dfa3812bdb9f79f989873b9a4542" => :mojave
    sha256 "cfd5c6eeac37065d19f527bb0798a9caf1928bab3340cd545224861a3c82f219" => :high_sierra
  end
```

**Comment by SMillerDev** [comment]
They might be removed, they might be removed in the future. Bottles are only supposed to work for the current formula.

**Comment by Stargator** [comment]
The problem is, I have some a brew formula that depends on python@2. `libimobiledevice`. SoI learned that python@2 was removed when I updated Homebrew and now `extract` is not working.

So is there another way to put it in a tap?

**Comment by SMillerDev** [comment]
If it's for macOS, the OS also ships with a python 2 version.
If that's not possible, maybe you can just copy an older revision of the python 2 formula in the github UI to your tap?

**Comment by benmwebb** [comment]
Just FYI, https://docs.brew.sh/Homebrew-and-Python still says Homebrew provides `python@2`. `brew info python` also recommends `brew install python@2`. And the `each_python` function in `/usr/local/Homebrew/Library/Homebrew/language/python.rb` fails because it looks for `python@2`.

**Comment by SMillerDev** [comment]
@iMichka got time to fix that?

**Comment by iMichka** [comment]
I'm working on a PR for brew.

**Comment by iMichka** [comment]
> And the each_python function in /usr/local/Homebrew/Library/Homebrew/language/python.rb fails because it looks for python@2.

I can’t reproduce this. Can you give an example?

**Comment by iMichka** [comment]
See https://github.com/Homebrew/brew/pull/7019 for the documentation and code update in brew.

**Comment by benmwebb** [comment]
> > And the each_python function in /usr/local/Homebrew/Library/Homebrew/language/python.rb fails because it looks for python@2.
> 
> I can’t reproduce this. Can you give an example?

Sure:

```
brew update
brew edit pkg-config
```

Modify the test section to read
```
  test do
    system "#{bin}/pkg-config", "--libs", "libpcre"
    Language::Python.each_python(build) do |python, version|
      system python
    end
  end
```

Then `brew test pkg-config` fails with
```
Testing pkg-config
==> /usr/local/Cellar/pkg-config/0.29.2/bin/pkg-config --libs libpcre
Error: pkg-config: failed
An exception occurred within a child process:
  FormulaUnavailableError: No available formula with the name "python@2" 
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:331:in `factory'
/usr/local/Homebrew/Library/Homebrew/language/python.rb:33:in `block in each_python'
/usr/local/Homebrew/Library/Homebrew/language/python.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/language/python.rb:32:in `each_python'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb:37:in `block in <class:PkgConfig>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1756:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1755:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:865:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1754:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1993:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1992:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1748:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
```

**Pull request merged**
