### PR TITLE
gnupg 2.3.0

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

Previous attempt https://github.com/Homebrew/homebrew-core/pull/74768
Announce of the release https://lists.gnupg.org/pipermail/gnupg-devel/2021-April/034828.html

### CODE REVIEW

**Comment by bayandin** [comment]
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _native_to_utf8 in libcommon.a(libcommon_a-utf8conv.o)
      _do_utf8_to_native in libcommon.a(libcommon_a-utf8conv.o)
      _jnlib_iconv in libcommon.a(libcommon_a-utf8conv.o)
     (maybe you meant: _jnlib_iconv_open, _jnlib_iconv , _jnlib_iconv_close )
  "_iconv_close", referenced from:
      _set_native_charset in libcommon.a(libcommon_a-utf8conv.o)
      _native_to_utf8 in libcommon.a(libcommon_a-utf8conv.o)
      _do_utf8_to_native in libcommon.a(libcommon_a-utf8conv.o)
      _jnlib_iconv_close in libcommon.a(libcommon_a-utf8conv.o)
     (maybe you meant: _jnlib_iconv_close)
  "_iconv_open", referenced from:
      _set_native_charset in libcommon.a(libcommon_a-utf8conv.o)
      _native_to_utf8 in libcommon.a(libcommon_a-utf8conv.o)
      _do_utf8_to_native in libcommon.a(libcommon_a-utf8conv.o)
      _jnlib_iconv_open in libcommon.a(libcommon_a-utf8conv.o)
     (maybe you meant: _jnlib_iconv_open)
ld: symbol(s) not found for architecture x86_64
```

Also we need to tune configure arguments a bit:
```
configure: WARNING: unrecognized options: --enable-symcryptrun
```

**Comment by carlocab** [comment]
Try this:
```diff
diff --git a/Formula/gnupg.rb b/Formula/gnupg.rb
index a0cb561a4e4..98497446163 100644
--- a/Formula/gnupg.rb
+++ b/Formula/gnupg.rb
@@ -29,7 +29,13 @@ class Gnupg < Formula
   depends_on "npth"
   depends_on "pinentry"
 
+  uses_from_macos "libiconv"
+
   def install
+    libiconv = MacOS.sdk_path_if_needed/"usr"
+    on_linux do
+      libiconv = nil
+    end
     system "./configure", "--disable-dependency-tracking",
                           "--disable-silent-rules",
                           "--prefix=#{prefix}",
@@ -37,7 +43,8 @@ class Gnupg < Formula
                           "--sysconfdir=#{etc}",
                           "--enable-all-tests",
                           "--enable-symcryptrun",
-                          "--with-pinentry-pgm=#{Formula["pinentry"].opt_bin}/pinentry"
+                          "--with-pinentry-pgm=#{Formula["pinentry"].opt_bin}/pinentry",
+                          libiconv
     system "make"
     system "make", "check"
     system "make", "install"
```
Though I'm pretty sure the compiler shims should be taking care of this already, so I'm not sure why it's needed.

**Comment by carlocab** [comment]
Hmmm actually no that won't help:
```
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
```

**Comment by carlocab** [comment]
This worked for me, except it failed at `make check`:

```diff
diff --git a/Formula/gnupg.rb b/Formula/gnupg.rb
index 23f8501ab8c..1476213ad7a 100644
--- a/Formula/gnupg.rb
+++ b/Formula/gnupg.rb
@@ -30,6 +30,10 @@ class Gnupg < Formula
   depends_on "pinentry"
 
   def install
+    ENV.append "CPPFLAGS", "-I#{MacOS.sdk_path_if_needed}/usr/include"
+    ENV.append "LDFLAGS", "-L#{MacOS.sdk_path_if_needed}/usr/lib -liconv"
+    ENV.append "CFLAGS", "-Wno-implicit-function-declaration"
+
     system "./configure", "--disable-dependency-tracking",
                           "--disable-silent-rules",
                           "--prefix=#{prefix}",
```

**Comment by cho-m** [comment]
I think `make check` runs `gpg` which appears to look for some binaries in install directories.

`keyboxd` is expected to be installed in `#{prefix}/libexec/keyboxd`, but it is only available in the build directory `/private/tmp/gnupg-.../gnupg-2.3.0/kbx/keyboxd`.

From [**common/homedir.c**](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=common/homedir.c;h=8b54f9ddaa126440319d9f2bb833b9b4cfa09b2e;hb=HEAD#l1174)
```c
1123 #define X(a,b,c) do {                                                   \
1124     static char *name;                                                  \
1125     if (!name)                                                          \
1126       name = gnupg_build_directory                                      \
1127         ? xstrconcat (gnupg_build_directory,                            \
1128                       DIRSEP_S b DIRSEP_S c EXEEXT_S, NULL)             \
1129         : xstrconcat (gnupg_ ## a (), DIRSEP_S c EXEEXT_S, NULL);       \
1130     return name;                                                        \
1131   } while (0)
...
1174       X(libexecdir, "kbx", KEYBOXD_NAME);
```

`gnupg_build_directory` is only available in development builds (and in `make distcheck`) for security reasons. Probably not a good idea for Homebrew releases, but can pass tests with configure option `--enable-gnupg-builddir-envvar` and `GNUPG_BUILDDIR` env variable.

Another option would be to find a way to modify testcases to use gpg's `--keyboxd-program` option.

---

I think some of the other build issue workarounds probably should be fixed in gnupg.
1. **iconv** - Probably need to change [`sm/Makefile.am`](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=sm/Makefile.am;h=9e768aaf129615bccb8dff5cf0cfd12aa510fc82;hb=HEAD#l82) so that `t_common_ldadd` has `$(LIBICONV)`. Similar to old macOS build fix for [g13/Makefile.am](https://dev.gnupg.org/rGf8ce31a7bf1ee85e5010b628a66e6f69486e5213).
2. **implicit-function-declaration** - Probably need to change [`tools/gpg-card.c`](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=tools/gpg-card.c;h=d9d626c5f99b541fd33df6f22198180f9fa98d23;hb=HEAD#l20) to `#include <ctype.h>`.

---

For `configure: WARNING: unrecognized options: --enable-symcryptrun`,
symcryptrun was remove in commit: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=209b7113f3493bd829ec5c90275ff95a273d9dd4

**Comment by carlocab** [comment]
Thanks for looking into this, @cho-m.

What doesn't make sense to me is that running `make check` before `make install` outside `brew` works just fine -- `make check` doesn't go looking for executables in the install prefix in this case. Not clear why it's behaving differently when run from `brew`.

The second issue is none of the workarounds in my previous comment were needed in 2.2.7, so these all look like regressions to me.

**Comment by cho-m** [comment]
@carlocab
I tried build outside `brew` on my Mac and saw similar failures.

For possible regressions, it looks like code was added with following new features:
1. iconv issue introduced with new Makefile targets for feature - https://dev.gnupg.org/rG5da6925a334c68d736804d8f19a684a678409d99
2. implicit function issue with "apdu" feature - https://dev.gnupg.org/rGed0759f39be04dd6108237f5ed03c7cfd1cb4642

**Comment by carlocab** [comment]
Ah, yes, I think I know why: I neglected to pass the `--enable-all-tests` flag to `configure` when trying to build outside of `brew`.

**Comment by carlocab** [comment]
Indeed, passing that flag to `configure` results in the same error seen when I run it with `brew`.

@cho-m, it seems like you have a handle on the sources of the regressions. Do you mind reporting this upstream?

**Comment by cho-m** [comment]
@carlocab Sure, I'll open the issues in GPG.

As for `keyboxd`, that probably needs to be looked into more.
I see that `gnupg_set_builddir` is called when using `gpg-conf --build-prefix` argument.
Not too sure why this isn't working for `keyboxd`

**Comment by cho-m** [comment]
Regression issues are now fixed: https://dev.gnupg.org/rG5fe60576d50f7c857d0a865a9630212422fa1ad1
I believe it should make it into 2.3.1 release.

**Comment by carlocab** [comment]
That was fast! Thanks for your work on getting this turned around so quickly, @cho-m.

**Comment by cho-m** [comment]
**GnuPG 2.3.1** released today - https://dev.gnupg.org/T5386 with build fixes.

Still fails on `make check` though.


---

Not too sure if there is a decent workaround for Homebrew.
- Modifying `PATH` doesn't work for me.
- Disabling `keyboxd` is an option via `./configure --disable-keyboxd`, but hard to say if this is a good idea. 2.3.0 release did call it an _"experimental key database daemon"_
- Using `GNUPG_BUILDDIR` only works with less secure `./configure --enable-gnupg-builddir-envvar`

---

In the case of upstream, it may be possible for them to modify testcase config to set `keyboxd-program` path (which is what they do for `agent-program` and `pinentry-program`):
```diff
--- a/tests/openpgp/defs.scm
+++ b/tests/openpgp/defs.scm
@@ -338,6 +338,7 @@
   (create-file "common.conf"
               (if (flag "--use-keyboxd" *args*)
                   "use-keyboxd" "#use-keyboxd")
+              (string-append "keyboxd-program " (tool 'keyboxd))
               )
```

**Comment by carlocab** [comment]
Why tests are omitted by removing `--enable-all-tests`? If it still covers all the important ones, we might consider omitting this flag while upstream fix their tests.

Your proposed fix makes sense, though. I'm a bit surprised they're not already doing something like that.

**Comment by cho-m** [comment]
@carlocab 
On separate note, should Homebrew be updating to this **devel** (2.3.x) or stick with the **LTS** (2.2.27).

Previously GnuPG only listed the **LTS** releases on their webpage, but it looks like they starting including **devel** releases.

If the **LTS** is preferred as stable, then it may be better to change `livecheck` instead.

---

Not too sure about extent of tests. GnuPG mainly mentions:
>   The "make check" is optional but highly recommended.  To run even
>   more tests you may add "--enable-all-tests" to the configure run.

Given that macOS is probably not the main build platform, it is probably better to make sure all tests are working.

---

Whether we stick with 2.2.27 or not, getting the fixes into 2.3.x would probably help whenever Homebrew decides to update (whether now or in future).

I opened a separate issue to see if tests can be fixed: https://dev.gnupg.org/T5406

**Comment by carlocab** [comment]
> On separate note, should Homebrew be updating to this **devel** (2.3.x) or stick with the **LTS** (2.2.27).

I did wonder about this. We usually look for the stable release, which often isn't the LTS release, but it often isn't the development release either.

I was under the impression that we had been using the version newer than the LTS release this whole time, but if their listing of a development version is new, and they only used to list an LTS one, then I suspect we actually do want to stay on the LTS version.

**Comment by cho-m** [comment]
Most references I see refer to **LTS** version as Stable release.

https://www.gnupg.org/index.html
> The current version of GnuPG is 2.2.27. See the download page for other maintained versions.

https://git.gnupg.org/
> GnuPG
> - [View the GnuPG development branch](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=shortlog;h=refs/heads/master)
> - [View the GnuPG stable (2.2) branch](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=shortlog;h=refs/heads/STABLE-BRANCH-2-2)

https://www.gnupg.org/ftp/gcrypt/gnupg/
> GnuPG 2.2.x is the current stable branch of GnuPG

Search from `archive.org`:
| March 25, 2021 | April 20, 2021 (Current) |
| --- | --- |
| march | april |

**Comment by Frederick888** [comment]
Many thanks to everyone here for the effort of trying to bring GPG 2.3.x to Homebrew.

Regarding if the 2.3.x series is a 'devel' release, just wanna drop a reference to their mailing list:

https://lists.gnupg.org/pipermail/gnupg-announce/2021q2/000459.html

> Although some bugs might linger in the 2.3 versions, they are intended
> to replace the 2.2 series.  2.3 may even be used for production purposes
> if either the risk of minor regressions is acceptable or the new
> features are important.

So while their website probably needs some update, 2.3.x can be considered production-ready I think.

**Comment by carlocab** [comment]
Ah, right. A similar email is actually linked in the first post: https://lists.gnupg.org/pipermail/gnupg-devel/2021-April/034828.html

Had forgotten all about it. Thanks for the reminder, @Frederick888. We might actually want to update to 2.3.x then.

Thoughts, @Homebrew/core?

**Comment by MikeMcQuaid** [comment]
> 2.3 may even be used for production purposes
> if either the risk of minor regressions is acceptable or the new
> features are important.

Yeh, 2.3 sounds right to me 👍🏻

**Comment by cho-m** [comment]
In that case, some ways I have built **GnuPG 2.3.1** include:

- Disabling the full test suite (remove: `"--enable-all-tests"`) - Probably cleaner change, built for me in **1 minute 35 seconds**:
    ```diff
    @@ -1,8 +1,8 @@
     class Gnupg < Formula
       desc "GNU Pretty Good Privacy (PGP) package"
       homepage "https://gnupg.org/"
    -  url "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.27.tar.bz2"
    -  sha256 "34e60009014ea16402069136e0a5f63d9b65f90096244975db5cea74b3d02399"
    +  url "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.3.1.tar.bz2"
    +  sha256 "c498db346a9b9a4b399e514c8f56dfc0a888ce8f327f10376ff984452cd154ec"
       license "GPL-3.0-or-later"
    
       livecheck do
    @@ -41,8 +41,6 @@ class Gnupg < Formula
                               "--prefix=#{prefix}",
                               "--sbindir=#{bin}",
                               "--sysconfdir=#{etc}",
    -                          "--enable-all-tests",
    -                          "--enable-symcryptrun",
                               "--with-pinentry-pgm=#{Formula["pinentry"].opt_bin}/pinentry"
         system "make"
         system "make", "check"
    ```

- Patching the test with `keyboxd-program` - Probably a bit odd to patch testcase though, built for me in **3 minutes 6 seconds**:
    ```diff
    @@ -1,8 +1,8 @@
     class Gnupg < Formula
       desc "GNU Pretty Good Privacy (PGP) package"
       homepage "https://gnupg.org/"
    -  url "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.27.tar.bz2"
    -  sha256 "34e60009014ea16402069136e0a5f63d9b65f90096244975db5cea74b3d02399"
    +  url "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.3.1.tar.bz2"
    +  sha256 "c498db346a9b9a4b399e514c8f56dfc0a888ce8f327f10376ff984452cd154ec"
       license "GPL-3.0-or-later"
    
       livecheck do
    @@ -36,13 +36,16 @@ class Gnupg < Formula
       end
    
       def install
    +    inreplace "tests/openpgp/defs.scm",
    +              "\"#use-keyboxd\")",
    +              "\"#use-keyboxd\")\n(string-append \"keyboxd-program \" (tool 'keyboxd))"
    +
         system "./configure", "--disable-dependency-tracking",
                               "--disable-silent-rules",
                               "--prefix=#{prefix}",
                               "--sbindir=#{bin}",
                               "--sysconfdir=#{etc}",
                               "--enable-all-tests",
    -                          "--enable-symcryptrun",
                               "--with-pinentry-pgm=#{Formula["pinentry"].opt_bin}/pinentry"
         system "make"
         system "make", "check"
    ```

**Comment by SMillerDev** [comment]
For security software like this I'd keep the tests and patch them.

**Comment by cho-m** [comment]
Upstream has added patch I requested: https://dev.gnupg.org/rGd36c4dc95b72b780375d57311bdf4ae842fd54fa

**Comment by carlocab** [comment]
Thanks, @cho-m. Would you like to open a new PR for 2.3.1 that applies your patch, along with other necessary fixes? I think @bayandin is a bit busy to update their PR at the moment.

**Comment by carlocab** [comment]
Superseded by #75755.

**Pull request closed without merging**
