### PR TITLE
bulk_extractor 2.0.3

### PR DESCRIPTION
**Pull request by chiefmikey**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
`Error: docker://ghcr.io/homebrew/core/bulk_extractor:2.0.3 already exists!`

**Comment by carlocab** [comment]
> Error: docker://ghcr.io/homebrew/core/bulk_extractor:2.0.3 already exists!

Please do not rebase after bottles have already been published.

**Review by carlocab — APPROVED** [review]

**Comment by chenrui333** [comment]
> > Error: docker://ghcr.io/homebrew/core/bulk_extractor:2.0.3 already exists!
> 
> Please do not rebase/squash after bottles have already been published.

I will pay more attentions on it next time (but i believe it might already fail couple of times already)

**Comment by carlocab** [comment]
Yes, it failed a couple of times already, but that doesn't mean you can rebase and squash the PR.

**Pull request merged**
