### PR TITLE
clasp-cl, cando 2.0.0 (new-formula)

### PR DESCRIPTION
**Pull request by yitzchak**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Add Clasp Common Lisp and Cando. Cando is an extension of Clasp for Chemistry.

### CODE REVIEW

**Comment by yitzchak** [comment]
These are both x86-64 only formula. Is there something required besides `depends_on arch: :x86_64` in order for the BrewTestBot to attach the "no ARM bottle" label? Or if everything is correct can a maintainer please attach that label?

**Comment by chenrui333** [comment]
```
  cando:
    * Dependency 'expat' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
```

**Comment by yitzchak** [comment]
@chenrui333 Done.

**Comment by yitzchak** [comment]
Not sure if the CI cancel was due to a timeout. Clasp takes about 2.5 hours to build on the GitHub runners and Cando about 3.5 hours. If they are build sequentially then I'm guessing it will be about 6 hours.

**Comment by SMillerDev** [comment]
We're not using GitHub runners, but there is a 90 minute timeout.

**Comment by yitzchak** [comment]
Ok, can that be extended? Packages like LLVM surely take longer then 90 minutes.

**Comment by SMillerDev** [comment]
If it takes that long they definitely must be separate reviews. Otherwise this PR will be building forever. You can leave the conflicts and add them in a PR afterwards

**Comment by yitzchak** [comment]
Ok. I'll resubmit.

**Pull request closed without merging**
