### PR TITLE
tomee-jax-rs: delete formula and add to formula_renames.json

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Wait, this is the same as `tomee-plus`

**Comment by chenrui333** [comment]
maybe we should remove the formula and merge it into the existing one.

**Comment by SeekingMeaning** [comment]
Does the new commit look good or ...?

**Comment by chenrui333** [comment]
lgtm, @SMillerDev, can you also take a look? Thanks!

**Comment by SMillerDev** [comment]
I think it should be formula_renames, not an alias

**Comment by SeekingMeaning** [comment]
Honest question, should I ping PRs when the build succeeds? Or do you already get notifications for that?

**Comment by SMillerDev** [comment]
Please don't unless it's really time sensitive. While I don't specifically get notifications for builds succeeding (I have those disabled) maintainers regularly go over all open pull requests to check for ones that succeeded and aren't merged.

**Review by SMillerDev — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
