### PR TITLE
buildifier 4.0.1

### PR DESCRIPTION
**Pull request by Loyalsoldier**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Since upstream has released a new version(v4.0.1) that uses Go modules. It's time to re-enable this.

**Review by carlocab — DISMISSED** [review]
Thanks, @Loyalsoldier.

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]
Looks like GitHub Actions still aren't working properly yet. But, well, third time's the charm?

**Comment by Loyalsoldier** [comment]
Do I need to place the built binary somewhere so that homebrew knows where to find it?

```
system "go", "build", *std_go_args, "./buildifier"
```
or

```
system "go", "build", *std_go_args, "./buildifier" "-o" "#{bin}/buildifier"
```

**Comment by carlocab** [comment]
`-o bin/"buildifier"` is already part of `std_go_args`, so what you've done is fine.

**Review by carlocab — DISMISSED** [review]

**Comment by Loyalsoldier** [comment]
One day, the `BrewTestBot` becomes Ultron 🤖️😂

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Comment by Loyalsoldier** [comment]
Any progress?

**Review by SMillerDev — DISMISSED** [review]
Let's try this again

**Pull request closed without merging**
