### PR TITLE
mongodb@3.4 3.4.16

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
```
==> ./build.sh ssl
Building bsondump...
# crypto/x509
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
# github.com/10gen/openssl
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
# github.com/mongodb/mongo-tools/common/db/openssl
.gopath/src/github.com/mongodb/mongo-tools/common/db/openssl/openssl_fips.go:21:12: undefined: openssl.FIPSModeSet
```

**Comment by benbek** [comment]
Hi, I would really like this to be merged. Can anything be done about the failure though? Maybe build it without openssl?

**Comment by mistydemeo** [comment]
The failure comes from the version of the `github.com/10gen/openssl` Go library they've vendored. That version of the library's FIPS module is tagged with `// +build !darwin`, so the functions are not defined on Darwin at all. However, mongodb instead tries to use FIPS features if `MONGO_CONFIG_HAVE_FIPS_MODE_SET` is defined, which is true if the C function `FIPS_mode_set` is defined. Our OpenSSL *is* built with FIPS enabled, which means that mongodb tries to use it.

This can be fixed upstream by upgrading their openssl library. We can also try to override `MONGO_CONFIG_HAVE_FIPS_MODE_SET`.

**Comment by mistydemeo** [comment]
Upstream issue: https://jira.mongodb.org/browse/TOOLS-2066

**Comment by mistydemeo** [comment]
Upstream issue has been fixed - should be fixed by https://github.com/mongodb/mongo/commit/ed4332c7936c591f6f721dae8b00ae1921dc73c9

**Comment by fxcoudert** [comment]
I guess that means we can close this PR, and will merge only the next 3.4.x release.
(Please @commitay @mistydemeo reopen if I missed something…)

**Pull request closed without merging**
