### PR TITLE
sshguard 1.6.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Noticed a manually created bintray mirror https://dl.bintray.com/homebrew/mirror/sshguard-1.6.1.tar.xz

Is that needed again? The SourceForge link seems ok.

**Comment by DomT4** [comment]
I suspect that was created last time SF had major downtime. I'm fine getting rid of it here until demand proves otherwise. `brew test` is failing, though.

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
👍

**Pull request closed without merging**
