### PR TITLE
goctl 1.5.6

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* feat: support json:"-" in mapping by @kevwan in https://github.com/zeromicro/go-zero/pull/3521
* improve: optimize encoding functions and add descriptive comments by @cubxxw in https://github.com/zeromicro/go-zero/pull/3543
* improve: limit logBrief http body size by @Awadabang in https://github.com/zeromicro/go-zero/pull/3498
* fix: avoid losing logs before closing by @xt-inking in https://github.com/zeromicro/go-zero/pull/3573
* fix: avoid integer overflow in mapping.Unmarshal by @kevwan in https://github.com/zeromicro/go-zero/pull/3582
* fix: avoid float overflow in mapping.Unmarshal by @kevwan in https://github.com/zeromicro/go-zero/pull/3590

## New Contributors
* @liumin-go made their first contribution in https://github.com/zeromicro/go-zero/pull/3512
* @POABOB made their first contribution in https://github.com/zeromicro/go-zero/pull/3517
* @cubxxw made their first contribution in https://github.com/zeromicro/go-zero/pull/3543
* @Awadabang made their first contribution in https://github.com/zeromicro/go-zero/pull/3498
* @xt-inking made their first contribution in https://github.com/zeromicro/go-zero/pull/3573

**Full Changelog**: https://github.com/zeromicro/go-zero/compare/v1.5.5...v1.5.6</pre>
</details>

### CODE REVIEW

**Comment by kevwan** [comment]
Sorry for the mistake!

Would you please give some advises? I'm not sure how to fix the problem.

Thanks!

**Comment by p-linnane** [comment]
We are only building `/tools/goctl` already. The only issue is that building from source does not return the correct version.

**Comment by p-linnane** [comment]
Oh I see. You cut releases specifically for `goctl` separate from `go-zero`. Let me change that.

**Review by chenrui333 — APPROVED** [review]

**Comment by kevwan** [comment]
> Oh I see. You cut releases specifically for `goctl` separate from `go-zero`. Let me change that.

Yes, that's right. Thank you very much!

**Pull request merged**
