### PR TITLE
transcrypt: fix manpage directory

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Kind of want #119967 to do `uses_from_macos "openssl"` and avoid manipulating `PATH`.

Just needs `openssl` command, which could use LibreSSL copy on macOS (though may be broken right now https://github.com/elasticdog/transcrypt/issues/147).

Alternatively, could add a dependency on `openssl@3` on both macOS and Linux.

**Comment by cho-m** [comment]
Now hitting LibreSSL 3 issue https://github.com/elasticdog/transcrypt/issues/147

**Comment by jmurty** [comment]
Hi @cho-m thanks for your work making _transcrypt_ work via Homebrew.

I'm the maintainer of transcrypt and have just [released a new version **2.2.1**](https://github.com/elasticdog/transcrypt/releases/tag/v2.2.1) (tagged `v2.2.1`) which should fix 🤞 compatibility with the LibreSSL 3+ `/usr/bin/openssl` shipped with MacOS 13 "Ventura".

I got here via your backlink to the relevant issue https://github.com/elasticdog/transcrypt/issues/147

**Comment by chenrui333** [comment]
FYI, there is transcrypt 2.2.3 release.

**Comment by chenrui333** [comment]
relates to #125274

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
