### PR TITLE
openconnect 8.08

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for msgfmt... /usr/local/opt/gettext/bin/msgfmt
checking for functional NLS support... yes (with  -lintl)
checking for GNUTLS... yes
checking for known-broken versions of GnuTLS... yes
configure: error: DTLS is insecure in GnuTLS v3.6.3 through v3.6.12.
See https://gitlab.com/gnutls/gnutls/issues/960
Add --without-gnutls-version-check to configure args to avoid this check (DTLS
will still be disabled at runtime), or build with another version.
```

**Comment by Moisan** [comment]
Either we wait that GnuTLS gets fixed upstream (see gitlab.com/gnutls/gnutls/-/issues/966) or we add `--without-gnutls-version-check` and a caveat about why DTLS is disabled.

**Comment by Bo98** [comment]
Disabling DTLS might break a lot of stuff. I don't think there's a rush to get 8.08 out there that would make that worth it.

If GnuTLS aren't interested in fixing the macOS compile, we can see what we can do to workaround it from our side.

**Comment by chenrui333** [comment]
yeah, I think we can totally wait for the gnutls before proceeding further. Closing the PR.

**Pull request closed without merging**
