### PR TITLE
packer 1.4.2

### PR DESCRIPTION
**Pull request by ahazem**
I'm seeing #41374 already exist but since it kind of stalled, I thought I would do this here instead.

### CODE REVIEW

**Comment by liamdawson** [comment]
This PR fails to build, which is why the other one is stalled:

```shell
$ brew install https://raw.githubusercontent.com/ahazem/homebrew-core/update-packer-to-1-4-2/Formula/packer.rb
Updating Homebrew...
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/packer-1.4.2.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "packer"
Download failed: https://homebrew.bintray.com/bottles/packer-1.4.2.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Cloning https://github.com/hashicorp/packer.git
Updating /Users/liamdawson/Library/Caches/Homebrew/packer--git
==> Checking out tag v1.4.2
HEAD is now at deb1334 Cut version 1.4.2
HEAD is now at deb1334 Cut version 1.4.2
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
Makefile:
  expected replacement of "go get golang.org/x/tools/cmd/stringer" with ""
```

**Comment by chenrui333** [comment]
Did not realize it is still using `govendor`.

Nice work though.

**Comment by ahazem** [comment]
@chenrui333 thank you, you're doing an awesome job yourself with other packages. :)
@liamdawson fixed now, it was just one of the dependencies that got changed in the makefile.

**Comment by lembacon** [comment]
Thanks @ahazem!

**Pull request closed without merging**
