### PR TITLE
kakoune 2022.10.31

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
This is very confusing, `brew info` may let user think the formula is only for macOS, while also requesting `linux-headers` and having a block to work on Linux:

```
==> Dependencies
Build: libxslt ✘, binutils ✘, linux-headers@5.15 ✘, pkg-config ✘
Required: ncurses ✔
==> Requirements
Required: macOS ✔
```
(Additionally the checkmark is checked, from a Linux computer this is even more confusing).

**Comment by chenrui333** [comment]
```
Full install --build-bottle kakoune output
  Warning: You are using macOS 10.15.
  We (and Apple) do not provide support for this old version.
  It is expected behaviour that some formulae will fail to build in this old version.
  It is expected behaviour that Homebrew will be buggy and slow.
  Do not create any issues about this on Homebrew's GitHub repositories.
  Do not create any issues even if you think this message is unrelated.
  Any opened issues will be immediately closed without response.
  Do not ask for help from MacHomebrew on Twitter.
  You may ask for help in Homebrew's discussions but are unlikely to receive a response.
  Try to figure out the problem yourself and submit a fix as a pull request.
  We will review it but may or may not accept it.
```

**Comment by chenrui333** [comment]
> This is very confusing, `brew info` may let user think the formula is only for macOS, while also requesting `linux-headers` and having a block to work on Linux:
> 
> ```
> ==> Dependencies
> Build: libxslt ✘, binutils ✘, linux-headers@5.15 ✘, pkg-config ✘
> Required: ncurses ✔
> ==> Requirements
> Required: macOS ✔
> ```
> 
> (Additionally the checkmark is checked, from a Linux computer this is even more confusing).
> 
> Is this normal?

```
depends_on macos: :high_sierra # needs C++17
```

That is special syntax for minimum required macOS version

**Comment by chenrui333** [comment]
Not sure if that is what you referred to.

**Comment by Porkepix** [comment]
> > (Additionally the checkmark is checked, from a Linux computer this is even more confusing).
> > Is this normal?
> 
> ```
> depends_on macos: :high_sierra # needs C++17
> ```
> 
> That is special syntax for minimum required macOS version

I know, but displaying it with a green checkmark from a Linux computer is very confusing. at first I thought the formula was mac-only due to that, so I think the display could be improved there either by detailing it's a mac minimum version, or by not showing it from a Linux computer?

**Comment by sminez** [comment]
@Porkepix is there something that needs to be done to get this working and merged? I'm currently running the latest release version of kakoune on my personal linux machine but I'm stuck with the previous build (complete with different key bindings 😞 ) on my work Mac. Happy to try and help if there's anything I can do!

**Comment by Porkepix** [comment]
I had no idea how to fix the breakage. On the other hand, the breakage was happening only on macos 10.15 which is to be disabled in the coming day if I'm not mistaken so maybe @chenrui333 might reopen this and rerun CI after a rebase once CI is switched from 10.15 to a full 13 run.

**Comment by chenrui333** [comment]
#118896

**Pull request closed without merging**
