### PR TITLE
gerbv 2.6.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
Some very explanatory output here :smile: 

```
==> ./configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/gerbv/2.6.1 --disable-update-desktop-database
Failed to execute: ./configure
```

**Comment by ilovezfs** [comment]
after running autogen, 
```
Undefined symbols for architecture x86_64:
  "_screen", referenced from:
      _pick_and_place_get_float_unit in pick-and-place.o
     (maybe you meant: _pick_and_place_screen_for_delimiter)
ld: symbol(s) not found for architecture x86_64
```

**Comment by woodruffw** [comment]
I'm at a loss on this one.

**Comment by ilovezfs** [comment]
It's fixed in HEAD. Oh well.

**Pull request closed without merging**
