### PR TITLE
gambit-scheme 4.9.4

### PR DESCRIPTION
**Pull request by mdbergmann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Duplicate of #123956

**Comment by mdbergmann** [comment]
Hi @carlocab .

Is it possible you close the other PR?
I was aware that there is another PR and contacted the author to close it, but the author didn't respond yet.

**Comment by carlocab** [comment]
Why should the other PR be closed?

**Comment by mdbergmann** [comment]
Well, I see it's moving forward.
From the missing action of the author I presumed that it's stuck.
It's alright then.

**Pull request closed without merging**
