### PR TITLE
jsoncpp 1.9.5

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Redex doesn't build at all, for unrelated reasons it seems. I'd suggest just merging this.

CC @iMichka

**Review by carlocab — DISMISSED** [review]

**Comment by iMichka** [comment]
I have a fix for redex: #92848
Let's wait and rebase once it is merged.

**Comment by pthariensflame** [comment]
Why was `libxslt` affected???

**Review by carlocab — DISMISSED** [review]
I suggest we merge this. `libsbol` can (probably) be fixed by adding a `depends_on "libxslt"`, which we can do shortly after merging this. It's probably not worth re-running CI here for it, since `libsbol` only builds on Catalina now.

**Comment by carlocab** [comment]
> Why was `libxslt` affected???

It doesn't seem to be. How was it affected?

**Comment by iMichka** [comment]
````
==> brew linkage --test libsbol
==> FAILED
Full linkage --test libsbol output
  Broken dependencies:
    /usr/local/opt/libxslt/lib/libxslt.1.dylib (libxslt)
```

Only on 10.15. Weird. Probably opportunistic linkage.

**Comment by carlocab** [comment]
> Only on 10.15.

`libsbol` doesn't build anwhere else

**Comment by iMichka** [comment]
And here is the fix for `libsbol`: #92994

**Comment by carlocab** [comment]
> > Only on 10.15.
> 
> `libsbol` doesn't build anywhere else

Now it builds everywhere. Thanks @iMichka

**Review by carlocab — APPROVED** [review]

**Comment by iMichka** [comment]
All green. I like that :)

**Pull request closed without merging**
