### PR TITLE
suite-sparse 7.1.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  suite-sparse
    * Files were found with references to the Homebrew shims directory.
      The offending files are:
        lib/libgraphblas.8.0.2.dylib
```

**Comment by cho-m** [comment]
May need to override `GB_C_COMPILER` (which is set to `CMAKE_C_COMPILER`)

**Comment by cho-m** [comment]
> > May need to override `GB_C_COMPILER` (which is set to `CMAKE_C_COMPILER`)
> 
> that did not work for me.

Did you `inreplace` the CMake file https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/v7.1.0/GraphBLAS/cmake_modules/GraphBLAS_JIT_configure.cmake#L11

**Comment by chenrui333** [comment]
> > > May need to override `GB_C_COMPILER` (which is set to `CMAKE_C_COMPILER`)
> > 
> > 
> > that did not work for me.
> 
> Did you `inreplace` the CMake file https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/v7.1.0/GraphBLAS/cmake_modules/GraphBLAS_JIT_configure.cmake#L11

oh, i just override as env variable, I can give that a shot.

**Comment by chenrui333** [comment]
rerun

**Comment by chenrui333** [comment]
known issue with julia regression build, good to be merged now.

**Review by chenrui333 — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Has this been tested with julia? I think it caused the failure we're seeing at https://github.com/Homebrew/homebrew-core/pull/136786

**Comment by cho-m** [comment]
> Has this been tested with julia? I think it caused the failure we're seeing at #136786

The test here did fail for `julia` (https://github.com/Homebrew/homebrew-core/actions/runs/5563882567/jobs/10163425893#step:3:199).

We still use bundled `suite-sparse` and I had added test to check bundled copy is picked up as users had issues when Homebrew's `suite-sparse` was also installed (#122305). Looks like this is no longer working.

**Comment by cho-m** [comment]
I'm guessing `brew` change. Part of RPATH (`@@HOMEBREW_CELLAR@@/julia/1.9.2/lib/julia`) is being dropped when pouring bottle:
```
❯ otool -L /usr/local/opt/julia/lib/julia/libcholmod.3.0.14.dylib
/usr/local/opt/julia/lib/julia/libcholmod.3.0.14.dylib:
	/usr/local/opt/julia/lib/julia/libcholmod.dylib (compatibility version 3.0.0, current version 3.0.14)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
	@rpath/libamd.dylib (compatibility version 2.0.0, current version 2.4.6)
	@rpath/libcolamd.dylib (compatibility version 2.0.0, current version 2.9.6)
	@rpath/libsuitesparseconfig.dylib (compatibility version 5.0.0, current version 5.10.1)
	@rpath/libccolamd.dylib (compatibility version 2.0.0, current version 2.9.6)
	@rpath/libcamd.dylib (compatibility version 2.0.0, current version 2.4.6)
	@rpath/libblastrampoline.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1500.65.0)

❯ objdump --rpaths --macho /usr/local/opt/julia/lib/julia/libcholmod.3.0.14.dylib
/usr/local/opt/julia/lib/julia/libcholmod.3.0.14.dylib:
/usr/local/opt/curl/lib
/usr/local/opt/mbedtls@2/lib
/usr/local/opt/openblas/lib
/usr/local/opt/gcc/lib/gcc/current
/usr/local/lib
/usr/lib
@loader_path/

❯ mkdir /tmp/test-julia
❯ cd /tmp/test-julia
❯ tar zxvf $(brew --cache --formula julia)
...
❯ objdump --rpaths --macho julia/1.9.2/lib/julia/libcholmod.3.0.14.dylib
julia/1.9.2/lib/julia/libcholmod.3.0.14.dylib:
@@HOMEBREW_CELLAR@@/julia/1.9.2/lib/julia
@@HOMEBREW_PREFIX@@/opt/curl/lib
@@HOMEBREW_PREFIX@@/opt/mbedtls@2/lib
@@HOMEBREW_PREFIX@@/opt/openblas/lib
@@HOMEBREW_PREFIX@@/opt/gcc/lib/gcc/current
@@HOMEBREW_PREFIX@@/lib
/usr/lib
@loader_path/
```

**Comment by cho-m** [comment]
Probably https://github.com/Homebrew/brew/commit/cff8d8c155b8935510295e8f50b97c7864379bc5

**Pull request merged**
