### PR TITLE
swift 5.3.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Needs Xcode 12

**Comment by chenrui333** [comment]
```
 -- The CXX compiler identification is AppleClang 12.0.0.12000032
 -- Detecting CXX compiler ABI info
 -- Detecting CXX compiler ABI info - done
 -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
 -- Detecting CXX compile features
 -- Detecting CXX compile features - done
 -- Looking for C++ include pthread.h
 -- Looking for C++ include pthread.h - found
 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
 -- Found Threads: TRUE  
 -- Found SQLite3: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include (found version "3.32.3") 
 -- Found Lit: /private/tmp/swift-20201128-74761-113cfq6/llvm-project/llvm/utils/lit/lit.py  
 -- Found FileCheck: /private/tmp/swift-20201128-74761-113cfq6/build/llvm-macosx-x86_64/bin/FileCheck  
 -- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
 -- Performing Test CXX_SUPPORTS_UNREACHABLE_CODE_FLAG
 -- Performing Test CXX_SUPPORTS_UNREACHABLE_CODE_FLAG - Success
 -- The Swift compiler identification is Apple 5.3.1
 -- Check for working Swift compiler: /private/tmp/swift-20201128-74761-113cfq6/build/swift-macosx-x86_64/bin/swiftc
 -- Check for working Swift compiler: /private/tmp/swift-20201128-74761-113cfq6/build/swift-macosx-x86_64/bin/swiftc - works
 CMake Deprecation Warning at tests/CMakeLists.txt:50 (cmake_policy):
   The OLD behavior for policy CMP0037 will be removed from a future version
   of CMake.
 
   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.
 
 
 -- Configuring done
 -- Generating done
 CMake Warning:
   Manually-specified variables were not used by the project:
 
     CLANG_VERSION_MAJOR
     CLANG_VERSION_MINOR
     CLANG_VERSION_PATCH
     CMAKE_LIBTOOL
     FOUNDATION_BUILD_DIR
     Foundation_DIR
     LIBDISPATCH_BUILD_DIR
     LIBDISPATCH_SOURCE_DIR
     LLVM_VERSION_MAJOR
     LLVM_VERSION_MINOR
     LLVM_VERSION_PATCH
     SWIFTC_EXECUTABLE
     dispatch_DIR
 
 
 -- Build files have been written to: /tmp/swift-20201128-74761-113cfq6/build/llbuild-macosx-x86_64
 + popd
 /private/tmp/swift-20201128-74761-113cfq6/build
 + /usr/local/opt/cmake/bin/cmake --build /private/tmp/swift-20201128-74761-113cfq6/build/llbuild-macosx-x86_64 -- -j6 -v all
 + /usr/local/opt/cmake/bin/cmake --build /private/tmp/swift-20201128-74761-113cfq6/build/llbuild-macosx-x86_64 -- -j6 -v all
 ninja: error: '/usr/lib/libsqlite3.dylib', needed by 'lib/XcodePerfTests.xctest/Contents/MacOS/XcodePerfTests', missing and no known rule to make it
 Building the standard library for: swift-stdlib-macosx-x86_64
 ERROR: command terminated with a non-zero exit status 1, aborting
```

**Comment by buttaface** [comment]
Could you just disable those tests since they aren't run by this build anyway, [like this other Swift toolchain for macOS does](https://github.com/vgorloff/swift-everywhere-toolchain/blob/master/Patches/llbuild/CMakeLists.txt.diff#L10)?

**Comment by chenrui333** [comment]
> Could you just disable those tests since they aren't run by this build anyway, [like this other Swift toolchain for macOS does](https://github.com/vgorloff/swift-everywhere-toolchain/blob/master/Patches/llbuild/CMakeLists.txt.diff#L10)?

Sure, definitely.

**Comment by chenrui333** [comment]
build failed in my local (11.0 machine).
```
[651/2029][ 32%][329.135s] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/IRGen -I/tmp/swift-20201219-17212-17y11kf/swift/lib/IRGen -Iinclude -I/private/tmp/swift-20201219-17212-17y11kf/swift-swift-5.3.2-RELEASE/include -I/tmp/swift-20201219-17212-17y11kf/llvm-project/llvm/include -I/tmp/swift-20201219-17212-17y11kf/build/llvm-macosx-x86_64/include -I/tmp/swift-20201219-17212-17y11kf/llvm-project/clang/include -I/tmp/swift-20201219-17212-17y11kf/build/llvm-macosx-x86_64/tools/clang/include -I/tmp/swift-20201219-17212-17y11kf/cmark/src -I/tmp/swift-20201219-17212-17y11kf/build/cmark-macosx-x86_64/src -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk   -UNDEBUG  -fno-exceptions -fno-rtti -Werror=gnu -target x86_64-apple-macosx10.9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch x86_64 -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/../../../Developer/Library/Frameworks -mmacosx-version-min=10.9 -O2 -g0 -UNDEBUG -std=c++14 -MD -MT lib/IRGen/CMakeFiles/swiftIRGen.dir/Fulfillment.cpp.o -MF lib/IRGen/CMakeFiles/swiftIRGen.dir/Fulfillment.cpp.o.d -o lib/IRGen/CMakeFiles/swiftIRGen.dir/Fulfillment.cpp.o -c /tmp/swift-20201219-17212-17y11kf/swift/lib/IRGen/Fulfillment.cpp
ninja: build stopped: subcommand failed.
Building the standard library for: swift-stdlib-macosx-x86_64
ERROR: command terminated with a non-zero exit status 1, aborting
```

**Comment by buttaface** [comment]
Huh, it's now failing with basic C++ issues when building the Swift compiler, looks like something screwed up with Xcode?

**Comment by chenrui333** [comment]
Create a new PR for swift 5.3.3 #70048

**Pull request closed without merging**
