### PR TITLE
libatomic_ops 7.6.0 (devel)

### PR DESCRIPTION
**Pull request by RandomDSdevel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
7.4.8 is the latest release

See
https://github.com/ivmai/libatomic_ops/releases/latest
https://github.com/ivmai/libatomic_ops/issues/29

**Comment by ilovezfs** [comment]
@RandomDSdevel I moved it into a devel spec.

**Comment by ilovezfs** [comment]
Thanks @RandomDSdevel!

**Comment by RandomDSdevel** [comment]
Still, having a release in a sort of limbo like that is…kind of weird, to say the least.  I actually didn't see _any_ indication that said release of libatomic_ops _was_ in such a state until you gave me those links, @ilovezfs.  You'd think there'd be some sort of change to the release notes or other such announcement.  (Maybe there's been talk of this on the project's mailing list(s,) if any, though those would be kind of out of the way and thus a bit obscure, relatively speaking…)

**Pull request merged**
