### PR TITLE
gl2ps 1.4.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by issyl0** [comment]
Looks like `dynare`, `octave` and `root` need revision bumps.

**Comment by chenrui333** [comment]
I did what happed in PR 52574

**Comment by chenrui333** [comment]
root has been bumped per this #52865

```
[34m==>[0m [1mbrew linkage --test root[0m
Broken dependencies:
/usr/local/opt/gl2ps/lib/libgl2ps.1.4.dylib (gl2ps)
==> [1m[31mFAILED[0m[0m
```

**Comment by chenrui333** [comment]
```
[34m==>[0m [1mbrew linkage --test root[0m
Broken dependencies:
  /usr/local/opt/gl2ps/lib/libgl2ps.1.4.dylib (gl2ps)
==> [1m[31mFAILED[0m[0m
```

**Pull request closed without merging**
