### PR TITLE
volt 0.3.5 (new formula)

### PR DESCRIPTION
**Pull request by mrymtsk**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you provide a more meaningful test? While it's better than nothing, version checks rarely catch real issues with the formula.

**Comment by mrymtsk** [comment]
Thanks for the review, added a test which tries to install a local vim plugin.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @mrymtsk for your contribution to Homebrew!

**Pull request closed without merging**
