### PR TITLE
presto 308 and devide from presto to presto and presto-server (new formula)

### PR DESCRIPTION
**Pull request by shigemk2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
What is the motivation for splitting the formula?

**Comment by SMillerDev** [comment]
Did Facebook give up development of presto? Otherwise a version bump shouldn't switch sources.

**Comment by shigemk2** [comment]
@fxcoudert 

> What is the motivation for splitting the formula?

I wanted to bump the version executing `brew bump-formula-pr`, but we can't execute `brew bump-formula-pr` in current Presto formula.

@SMillerDev 

https://github.com/Homebrew/homebrew-core/pull/38114

I am not sure whether Facebook give up development of presto, but according to these pages, Presto artifacts were move from `com.facebook.presto` to `io.prestosql`

https://mvnrepository.com/artifact/com.facebook.presto/presto-client
https://mvnrepository.com/artifact/com.facebook.presto/presto-server

**Comment by fxcoudert** [comment]
From the previous PR:

> PrestoSQL is a fork being run by a separate entity

and

> if there is a fork and both are maintained, the fork should open a new PR for a new formula

We won't switch the existing formula to the fork, but a new formula for the fork (in another PR) would be acceptable.

**Pull request closed without merging**
