### PR TITLE
mednafen: depend on gcc for clang >= 800

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

To fix fallouts as in: https://bot.brew.sh/job/Homebrew%20Core/18194/

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
actually there's a new version and I've got it working with clang it seems so I'll open a PR for that

**Comment by vszakats** [comment]
Thank you @ilovezfs!

**Comment by ilovezfs** [comment]
Voilà: https://github.com/Homebrew/homebrew-core/pull/11025

**Comment by vszakats** [comment]
Neat!

**Pull request closed without merging**
