### PR TITLE
magic-wormhole: bump python resources to latest version

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Replaces #72946 because I accidentally screwed up.

### CODE REVIEW

**Comment by alex** [comment]
I'm not sure why this ended up with the `automerge-skip` label (and without the `rust` and `python` labels).

**Comment by SMillerDev** [comment]
because it changes non-Formula files

**Comment by alex** [comment]
Ah. Thanks.

**Review by carlocab — APPROVED** [review]
Thanks, @alex.

**Pull request closed without merging**
