### PR TITLE
openssl@1.1 final deprecation

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
We originally pushed back the deprecation date for `openssl@1.1` to unblock our CI, since we had undeprecated dependents. There has been no progress with migrating the dependents to `openssl@3`. This PR restores the original deprecation date for `openssl@1.1` and deprecates all recursive dependents

### CODE REVIEW

**Comment by Bo98** [comment]
I wouldn't backdate tbh. I know some do that but it really just messes up any calculation where we check how long something has been deprecated for when moving to `disabled` etc.

So I would either set it to now, or set everything to say 1st November as a final call.

**Comment by p-linnane** [comment]
Since this should've happened on the original deprecation date, but we pushed it to see if we could perform any more migrations, I think it makes sense to set this to the original OpenSSL 1.1.1 deprecation date. I'm open to changing the date if people think it makes more sense.

**Comment by Bo98** [comment]
Thing is for users though is our deprecation period is ultimately what matters - it is a notice that we are going to remove the package soon. We don't at any point say "it's deprecated now but actually should have been a month ago" - only maintainers see this date in reality (+ API consumers but that's not common). Users will just see in their CI that deprecation warnings have started as of when this gets merged.

Our policy is that (excluding exceptional circumstances) we won't disable deprecated formulae for 3 months, in order to give sufficient notice. PRs that move formulae from deprecated -> disabled currently require manual review of commit histories to make sure we're not disabling things too soon, and my experience of that has tempted me to perhaps even suggest adding an audit that disallows backdating. If upstream EOL is important to document, it still can be in the form of a comment which has identical visibility reach as before.

That's just my opinion on it though.

**Comment by p-linnane** [comment]
Those are fair points. I will update the dates.

**Comment by p-linnane** [comment]
All dates have been moved to today.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
