### PR TITLE
wildfly-as 25.0.1

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Please delete all the prebuilt binaries if you want to remove the `:x86_64` dependency.

**Comment by carlocab** [comment]
You probably want to do something like
```ruby
buildpath.glob("**/main/lib").map(&:rmtree)
(buildpath/"docs/contrib/scripts/service").rmtree
```

**Comment by moonfruit** [comment]
Can I build it into different bottles?

**Comment by carlocab** [comment]
No. As you mentioned in #88717, these components are optional, so we should delete them since they violate [Homebrew policy regarding pre-built binaries](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae).

**Comment by moonfruit** [comment]
Errr, I think we update the version first. And after this, I will dig into it to solve this.

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
```
 ==> brew linkage --test wildfly-as
==> FAILED
Missing libraries:
  unexpected (libaio.so.1)
```

**Pull request closed without merging**
