### PR TITLE
Update TomEE Webprofile version to latest (7.1.1)

### PR DESCRIPTION
**Pull request by nfrankel**
- [X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by EricFromCanada** [comment]
You need to also update the `sha256` value for the download.

**Comment by nfrankel** [comment]
@EricFromCanada Thanks for the feedback, sorry about that... First PR on Homebrew.

**Comment by EricFromCanada** [comment]
Thanks for helping out. If you plan on doing more formula updates, you can use [`brew bump-formula-pr`](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html#submit-a-new-version-of-an-existing-formula) to automate the process.

**Comment by nfrankel** [comment]
Will do should I update more formulas

**Comment by nfrankel** [comment]
Will do should I update more formulas

**Comment by fxcoudert** [comment]
Thank you!

**Pull request merged**
