### PR TITLE
Remove old GCC and other versioned formulas

### PR DESCRIPTION
**Pull request by fxcoudert**
- Remove old GCC versions which do not work on High Sierra
- Remove old versions of clog, ppl, and isl, only used as deps for the removed GCC
- Remove docker@1.71, which I forgot in a previous PR

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by pronvit** [comment]
This is really disappointing. How exactly GCC doesn't work on High Sierra? It (definitely 4.8 and even 4.5 but have to use older Xcode) works perfectly for me, but maybe something is broken what I'm not using?

**Comment by fxcoudert** [comment]
The earliest version of GCC that builds and works, unpatched, on macOS High Sierra with Xcode 9 (i.e., an up-to-date system) is GCC 6. In Homebrew, we still ship GCC 5 and GCC 4.9 by including patches for them.

Versions earlier than 6 not supported anymore by the GCC project: https://gcc.gnu.org

**Comment by pronvit** [comment]
@fxcoudert This doesn't answer my question. The commit says "Remove old GCC versions which do not work on High Sierra". While just now I've successfully installed gcc@4.8 from sources on 10.13.1 and Xcode 9.1 (by removing OS version check in the formula), and it works without problems.

So I'm asking, how exactly does GCC 4.8 not work on High Sierra (and whether anyone actually checked that)? If it's been removed for other reasons, then it should probably be stated so.

**Comment by fxcoudert** [comment]
Every single formula, including GCC versions, was tested when High Sierra was released. At that point, GCC 4.8 and earlier didn't compile on High Sierra. Now we have a policy to remove versioned formulas that are not supported on the last 3 macOS versions, so it was removed accordingly.

The fact that it now builds (whether by chance, or because something go fixed in macOS or Xcode) is nice, but it won't be enough for us to add it back. We already ship 4 different versions of GCC, and I would like to focus on upstream-supported versions. We are trying to keep the number of older versioned formulas low in Homebrew core generally speaking.

As Homebrew was built to be extensible and modular, a good solution for you would be to maintain such a formula in a personal tap: https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by pronvit** [comment]
Right, that's ok then as long as the decision isn't based solely on possibly incorrect information about its inability to work on newer macOS versions.

**Pull request merged**
