### PR TITLE
pngcrush 1.8.12

### PR DESCRIPTION
**Pull request by ilovezfs**
fix build on 10.11 with Xcode 8.x

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @glennrp are you aware of the pngcrush clock_gettime problem on OS X 10.11?

**Comment by ilovezfs** [comment]
@glennrp I've created a bug report here: https://sourceforge.net/p/pmt/bugs/77/

**Comment by ilovezfs** [comment]
@zmwangx do you understand the point about lrt here: https://sourceforge.net/p/pmt/bugs/77/#5a84 ?

**Comment by zmwangx** [comment]
@ilovezfs Replied over there.

**Comment by ilovezfs** [comment]
@zmwangx thank you :)

**Comment by zmwangx** [comment]
No problem! clock_gettime keeps giving.

**Comment by glennrp** [comment]
Yes that's the truth.  And once you find clock_gettime you have to figure
out which timers are supported.  I think pngcrush is handling that part OK.

**Comment by ilovezfs** [comment]
@glennrp it's getting tripped up at line 1490 of pngcrush.c

```
#  elif defined(CLOCK_MONOTONIC) /* Linux & FreeBSD */
```
since `CLOCK_MONOTONIC` is defined in the Xcode 8 SDK, even if you happen to be on 10.11 where `clock_gettime` is not implemented

**Comment by glennrp** [comment]
OK so please suggest X in
#  elif defined(CLOCK_MONOTONIC) && !defined(X) /* Linux & FreeBSD but not
MacOS */

**Comment by ilovezfs** [comment]
@glennrp if you do not want to use weak linking, you can probably get away with this:
```
diff --git a/pngcrush.c b/pngcrush.c
index 7b5db76..8df6eb4 100644
--- a/pngcrush.c
+++ b/pngcrush.c
@@ -1487,7 +1487,10 @@ static int copy_idat = 0; /* = 1 to simply copy the IDAT chunk data */
 #    define PNGCRUSH_CLOCK_ID CLOCK_MONOTONIC_PRECISE
 #    define PNGCRUSH_USING_CLOCK "clock_gettime(CLOCK_MONOTONIC_PRECISE,&t)"
 #    define PNGCRUSH_USE_CLOCK_GETTIME 1
-#  elif defined(CLOCK_MONOTONIC) /* Linux & FreeBSD */
+#  elif defined(CLOCK_MONOTONIC) /* Linux & FreeBSD & macOS */
+#ifdef __APPLE__
+#include <AvailabilityMacros.h>
+#if MAC_OS_X_VERSION_MIN_REQUIRED >= 101200
 #    define PNGCRUSH_CLOCK_ID CLOCK_MONOTONIC
 #    define PNGCRUSH_USING_CLOCK "clock_gettime(CLOCK_MONOTONIC,&t)"
 #    define PNGCRUSH_USE_CLOCK_GETTIME 1
@@ -1495,6 +1498,16 @@ static int copy_idat = 0; /* = 1 to simply copy the IDAT chunk data */
 #    define PNGCRUSH_USING_CLOCK "clock()"
 #    undef PNGCRUSH_USE_CLOCK_GETTIME
 #    define PNGCRUSH_USE_CLOCK_GETTIME 0
+#endif
+#else
+#    define PNGCRUSH_CLOCK_ID CLOCK_MONOTONIC
+#    define PNGCRUSH_USING_CLOCK "clock_gettime(CLOCK_MONOTONIC,&t)"
+#    define PNGCRUSH_USE_CLOCK_GETTIME 1
+#endif
+#  else
+#    define PNGCRUSH_USING_CLOCK "clock()"
+#    undef PNGCRUSH_USE_CLOCK_GETTIME
+#    define PNGCRUSH_USE_CLOCK_GETTIME 0
 #  endif
 #else /* PNGCRUSH_TIMERS */
 #    define PNGCRUSH_USING_CLOCK "clock()"
```

**Comment by ilovezfs** [comment]
@glennrp in other words, && !(defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED < 101200)

**Comment by glennrp** [comment]
Thanks.  Try this patch based on your suggestion

1490c1493,1494
< #  elif defined(CLOCK_MONOTONIC) /* Linux & FreeBSD */
---
> #  elif defined(CLOCK_MONOTONIC) /* Linux & FreeBSD but not some MacOS */
&& \
>      !(defined(APPLE) && MAC_OS_X_VERSION_MIN_REQUIRED < 101200)

**Comment by glennrp** [comment]
I still would need to include the MacOS availability thing somewhere, right?

#ifdef __APPLE__
# include <AvailabilityMacros.h>
#endif

**Comment by glennrp** [comment]
Is that supposed to be !define(__APPLE__) && ...

I'm not sure whether some editor has eaten the underscores.


On Mon, Aug 21, 2017 at 12:00 PM, Glenn Randers-Pehrson <glennrp@gmail.com>
> wrote:
>
>> Thanks.  Try this patch based on your suggestion
>>
>> 1490c1493,1494
>> < #  elif defined(CLOCK_MONOTONIC) /* Linux & FreeBSD */
>> ---
>> > #  elif defined(CLOCK_MONOTONIC) /* Linux & FreeBSD but not some MacOS
>> */ && \
>> >      !(defined(APPLE) && MAC_OS_X_VERSION_MIN_REQUIRED < 101200)
>>
>>
>> On Mon, Aug 21, 2017 at 11:42 AM, ilovezfs <notifications@github.com>
>> wrote:
>>
>>> @glennrp <https://github.com/glennrp> in other words, && !(defined(
>>> *APPLE*) && MAC_OS_X_VERSION_MIN_REQUIRED < 101200)
>>>
>>

**Comment by ilovezfs** [comment]
@glennrp this seems to work: https://gist.githubusercontent.com/ilovezfs/37a3a1c0ec9d2183893bf1be7d343037/raw/c26b188a991ee6db51bf8851e70812f0f96a8512/gistfile1.txt

**Comment by glennrp** [comment]
Thanks.  I'll incorporate this patch in pngcrush-1.8.13 which I'll be
releasing
after libpng-1.6.32 is out at the end of this week.

**Pull request closed without merging**
