### PR TITLE
lexicon 3.11.2 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by branchvincent** [comment]
```
Error: Please make sure the libxml2 and libxslt development packages are installed.
```

**Review by branchv — APPROVED** [review]

**Comment by iMichka** [comment]
You can download it through `pypi`? Is there any reason we need to ship this package (like internal use for another formula)? https://pypi.org/project/dns-lexicon/

**Comment by chenrui333** [comment]
> You can download it through `pypi`? Is there any reason we need to ship this package (like internal use for another formula)? https://pypi.org/project/dns-lexicon/

it is a CLI app to manage the DNS records.

**Comment by iMichka** [comment]
What I mean is that not so long ago, we would not accept formulae that could be installed by `pip install` straight away. Just to avoid duplicating the effort with the `pypi` package manager. Unless the formula was needed as a dependency, or the `pypi` version was not compatible with macOS and we shipped a specific "fixed" version.
I recall there was something about this in our documentation back then about this, but I can't find it back, so maybe we changed our mind at one point.

**Comment by SMillerDev** [comment]
It's in https://docs.brew.sh/Python-for-Formula-Authors, but that only excludes python libraries.

**Comment by chenrui333** [comment]
yeah, based on the formulae guide, i think we only exclude the python library installations?

**Pull request closed without merging**
