### PR TITLE
pdftk-java 3.0.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
20:55:54 BUILD SUCCESSFUL in 38s
20:55:54 3 actionable tasks: 3 executed
20:55:54 Error: An exception occurred within a child process:
20:55:54   Errno::ENOENT: No such file or directory - build/libs/pdftk.jar

**Comment by chenrui333** [comment]
Not quite sure why it failed, btw the two release tags, the installation process did not change at all:

```
$ git diff v3.0.8 v3.0.9 -- .gitlab-ci.yml
diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
index 42940e7..864d5d1 100644
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,7 +9,7 @@ php-pdftk:
   extends: .ant-job
   script:
     - ant -lib /usr/share/java
-    - echo -e '#!/bin/bash\njava -cp' `pwd`'/build/jar/pdftk.jar:'`pwd`'/lib/bcprov-jdk15on-1.51.jar:'`pwd`'/lib/commons-lang3-3.7.jar com.gitlab.pdftk_java.pdftk "$@"' > /usr/bin/pdftk
+    - echo -e '#!/bin/bash\njava -cp' `pwd`'/build/jar/pdftk.jar:'`pwd`'/lib/bcprov-jdk15on-1.64.jar:'`pwd`'/lib/commons-lang3-3.9.jar com.gitlab.pdftk_java.pdftk "$@"' > /usr/bin/pdftk
     - chmod +x /usr/bin/pdftk
     - apt-get install php-mbstring phpunit composer -yqq
     - git clone --depth 1 https://github.com/marcvinyals/php-pdftk
@@ -46,7 +46,7 @@ pages:
   stage: test
   image: gradle:latest
   variables:
-    GRADLE_VERSION: "5.0"
+    GRADLE_VERSION: "6.0.1"
   script:
     - gradle wrapper --gradle-version=$GRADLE_VERSION
     - ./gradlew shadowJar
@@ -59,15 +59,10 @@ gradle:
     - build/libs/pdftk-all.jar
     expire_in: 1 month

-gradle-4.10.3:
+gradle-5.0:
   extends: .gradle-job
   variables:
-    GRADLE_VERSION: "4.10.3"
-
-gradle-4.0:
-  extends: .gradle-job
-  variables:
-    GRADLE_VERSION: "4.0"
+    GRADLE_VERSION: "5.0"

 spotless:
   extends: .gradle-job
```

**Comment by chenrui333** [comment]
Submitted an upstream issue, https://github.com/Homebrew/homebrew-core/pull/48981

**Comment by marcvinyals** [comment]
I think the problem is that the output jar is supposed to be named `pdftk-all.jar`. For some time there were some compatibility issues between Gradle and shadowJar and the jar got renamed to `pdftk.jar`, but these got fixed and the name is `pdftk-all.jar` again.

**Comment by chenrui333** [comment]
Let me give a try, thanks for pointing out the fatJar naming difference.

**Pull request merged**
