### PR TITLE
WIP: Fix build from HEAD for assh.rb

### PR DESCRIPTION
**Pull request by wd**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
I have tested use `brew edit assh & brew install assh --head`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
You should probably just update the formula to the latest version instead of building HEAD.

**Comment by wd** [comment]
Yeah, the author just released v2.9.1 yesterday, but I only found the source code, didn't found a binary package, So I didn't know how to bump up the version.

And I think the head version also should be fixed.

**Comment by SMillerDev** [comment]
Homebrew never uses binary packages. https://docs.brew.sh/Updating-Software-in-Homebrew can help you, since your change will likely break the normal build.

**Comment by wd** [comment]
Yeah, you are right, I misunderstand the bottle package and the binary package. I'll update the PR later.

**Pull request closed without merging**
