### PR TITLE
heroku 6.14.31

### PR DESCRIPTION
**Pull request by RasPhilCo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
The replacements should be
```
    inreplace "bin/run" do |s|
      s.gsub! "npm update -g heroku-cli", "brew upgrade heroku"
      s.gsub! "#!/usr/bin/env node", "#!#{Formula["node"].opt_bin}/node"
    end
```

**Comment by RasPhilCo** [comment]
Updated, but we dropped `bin/run.js`

**Comment by ilovezfs** [comment]
@RasPhilCo yes, but the string about how to upgrade is now in bin/run

**Comment by RasPhilCo** [comment]
@ilovezfs Correct! I read too quickly, thanks!

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by JCount** [comment]
@RasPhilCo Thank you for making your first contribution to Homebrew!! 🥇

**Pull request closed without merging**
