### PR TITLE
glib: migrate to `pkgconf`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
> In this case, could just do first `glib` install into `prefix` rather than staging and just install on top of it the 2nd time so that dylibs are always at the expected path.

Thanks, will try that. What I'm confused about is: why didn't this affect the last bottle build of `glib`? I can't tell what's changed since then.

**Comment by cho-m** [comment]
> What I'm confused about is: why didn't this affect the last bottle build of `glib`? I can't tell what's changed since then.

Not sure yet. Same failure happens in #193345 (https://github.com/Homebrew/homebrew-core/commit/85cc484c89b138aca8ae0c1e2cccf6d825edffb6 - based on annotations since logs aren't showing up) while we successfully built in #195052 

Those were roughly a day apart so not much should have changed other than new version.

**Comment by cho-m** [comment]
The new `meson` version may have been released in that 1 day period https://github.com/Homebrew/homebrew-core/commit/b4fcb5555f58491f5887cb707b0b7998d590bc1d

**Comment by carlocab** [comment]
> The new `meson` version may have been released in that 1 day period https://github.com/Homebrew/homebrew-core/commit/b4fcb5555f58491f5887cb707b0b7998d590bc1d

That'll do it. Building with the older version of `meson` fixes this.

**Comment by carlocab** [comment]
> Trying to install the bootstrap `glib` doesn't help either unfortunately. It seems to be using the path to the installed `gobject-introspection`.

Huh, maybe I tested this wrong locally, since it seems to be working in CI.

**Review by cho-m — APPROVED** [review]

**Comment by daeho-ro** [comment]
I think rebase will work.
- https://github.com/Homebrew/homebrew-core/pull/198495

**Comment by barracuda156** [comment]
> > The new `meson` version may have been released in that 1 day period [b4fcb55](https://github.com/Homebrew/homebrew-core/commit/b4fcb5555f58491f5887cb707b0b7998d590bc1d)
> 
> That'll do it. Building with the older version of `meson` fixes this.

Looks like Meson never fixed this ever since.

**Comment by carlocab** [comment]
No, I don't think they have. I meant to report it to them but never found the time to. It's probably still worth reporting to them in case they think it's worth fixing.

**Comment by barracuda156** [comment]
I am trying update gnome stack for the second day, and typelibs are still broken, apparently. Python stacktrace sounds meaningless, but googling for the error led here. So I think it is still broken. Everything works fine with older glib2/gobject-introspection/py-gobject3 (before the mess Gnome created), but not with the latest releases.

P. S. “Still broken” – I mean in meson, not Homebrew, of course.

**Comment by carlocab** [comment]
I suggest filing an issue with meson then. Feel free to link back here and/or tag me in the issue if desired; I'm afraid I won't be able to find the time to file an issue myself soon.

**Comment by barracuda156** [comment]
@carlocab Could you say how did you fix it here? Adding existing patches does not seem to have an effect (or I am missing something).

**Pull request merged**
