### PR TITLE
gti 1.9.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

---

- https://github.com/rwos/gti/issues/61

### CODE REVIEW

**Comment by chenrui333** [comment]
diffchecker, https://www.diffchecker.com/zL0Qms4Q/

**Comment by p-linnane** [comment]
v1.9.1 is out, so we shouldn't need the patch now.

**Comment by chenrui333** [comment]
should be good now.

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
- https://github.com/rwos/gti/commit/789bea8c6e330c75390ec4d38f8718b957d0084f

**Pull request merged**
