### PR TITLE
libgit2 1.4.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Blocked by `pygit2` support for 1.4.0. Looks like it is planned for `pygit2` 1.9.0 release: https://github.com/libgit2/pygit2/commit/935e2b5b4cd36bfbc8c15b5498a4f80df77c3176. Not sure if stable enough to just patch like we did for `libgit2 1.3.0` (https://github.com/Homebrew/formula-patches/blob/master/pygit2/libgit2-1.3.0.patch)

**Comment by nijikon** [comment]
Looks like it was released, can we update this PR?

**Comment by cho-m** [comment]
We could update, but I think it only unblocks the Python formulae.

Sadly, Rust formulae are still blocking this PR since we build with `--locked` flag.

Even if we try to modify Cargo.toml/Cargo.lock, `libgit2 >= 1.4` will force a Rust `git2 >= 0.14` requirement; however, current latest `cargo 0.60` package (https://crates.io/crates/cargo/0.60.0) still uses 0.13. So, formulae like `cargo-outdated` that use `cargo` Rust package will fail.

Not sure how this would impact `rust` formula itself (e.g. #95807), which has `cargo` resource built-in.

**Comment by cho-m** [comment]
I added some temporary workarounds. Will need to rebase and update `cargo-outdated` after recent merge (still won't work without workarounds based on upstream issue since there isn't a `cargo` release with fix).

Also need to wait for `llvm` fix #96067, which is blocking `julia` builds necessary in this PR.

**Comment by carlocab** [comment]
Removing `CI-long-timeout` here prematurely for #96101, as we need it to fix broken bottles.

**Comment by nijikon** [comment]
Great work on this! Looks like everything is passing now. https://github.com/Homebrew/homebrew-core/pull/96067 got merged.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
