### PR TITLE
migrate android-ndk, -sdk, -platform-tools to caskroom

### PR DESCRIPTION
**Pull request by yurikoles**
According to discussion in #7860.
Please don't merge till https://github.com/caskroom/homebrew-cask/pull/31126.

### CODE REVIEW

**Comment by yurikoles** [comment]
I had created PR with android-sdk to Caskroom https://github.com/caskroom/homebrew-cask/pull/31126. And @vitorgalvao, maintainer of Caskroom, [had requested](https://github.com/caskroom/homebrew-cask/pull/31126#issuecomment-288756037) confirmation of the plan to migrate this formulas. So please do confirm.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by yurikoles** [comment]
@MikeMcQuaid please merge

**Comment by MikeMcQuaid** [comment]
Thanks @yurikoles!

**Comment by mkatsevVR** [comment]
why was android-ndk deleted from core without being added to the caskroom? it's currently not possible to install the NDK using homebrew...

**Comment by MikeMcQuaid** [comment]
Our apologies @mkatsevVR. Please submit a PR to Caskroom to add it there, thanks.

**Comment by bronson** [comment]
What should ANDROID_HOME be set to now?  `/usr/local/Caskroom/android-sdk/25.2.3`?

(ref https://github.com/caskroom/homebrew-cask/pull/31126)

**Comment by yurikoles** [comment]
@mkatsevVR there is already an issue in caskroom: https://github.com/caskroom/homebrew-cask/issues/31234

**Comment by ilovezfs** [comment]
@MikeMcQuaid @yurikoles it looks like some reverse dependencies will need to die or be updated or migrated or whatever too:
```
crystax-ndk.rb:17:  depends_on "android-sdk" => :recommended
fb-adb.rb:15:  depends_on "android-ndk" => :build
fb-adb.rb:19:  depends_on "android-sdk"
fdroidserver.rb:22:  depends_on "android-sdk" => :recommended
gifcap.rb:11:  depends_on "android-sdk" => :optional
```

**Comment by MikeMcQuaid** [comment]
@yurikoles You can't reopen a merged pull request.



> I had tried to put caskroom/android-sdk as dependency, but brew can't resolve it. Is there any official way for formulae to depend on cask?

You can't depend on casks.

**Comment by cricket007** [comment]
A few questions: 

1. I don't use Android Studio, and I would prefer not to use the CLI of `sdkmanager`. How does IntelliJ handle the SDK Manager?
2. Is there a documented process here of migrating the old installed SDK tools & images from brew location to the Cask location? I would prefer not to re-download anything.

**Pull request merged**
