### PR TITLE
revision bumps for giflib

### PR DESCRIPTION
**Pull request by Bo98**
https://github.com/Homebrew/homebrew-core/pull/46991#issuecomment-557941476

I've verified from the bottles that all of these had at least one file linking to giflib compatibility version 8.0.0.

### CODE REVIEW

**Comment by Bo98** [comment]
EFL appears to not compile anymore on Xcode 11.

**Comment by Bo98** [comment]
Dropping EFL from this pull request.

**Comment by antoniovs1029** [comment]
Hi. So I was having some problems with `mono-libgdiplus` that got resolved after this PR got merged.

Since I am new to homebrew I am just curious to know what you changed so that I can learn about it. I believe your change on the revision number of `mono-libgdiplus.rb` in this PR is meant to make brew download the build from:

`https://homebrew.bintray.com/bottles/mono-libgdiplus-6.0.4_1.high_sierra.bottle.tar.gz`

So my question is what has changed between `mono-libgdiplus-6.0.4_1.high_sierra.bottle.tar.gz` and `mono-libgdiplus-6.0.4.high_sierra.bottle.tar.gz`?

Thanks for solving this problem!

**Comment by Bo98** [comment]
Thanks for reaching out @antoniovs1029.

`mono-libgdiplus` contains a dependency on `giflib`. A little over a week ago, that dependency was updated (#41436). Typically, unless there was binary compatibility changes, this isn't much of a problem.

In #46991, there was an attempt to update `z3`. Due to a symlink issue, `dafny` also had to be updated at the same time. It was when the CI was running tests for `dafny` that it discovered loading issues, curiously only on macOS High Sierra and not on Mojave or Catalina. You can see from discussions there that we eventually found the cause:

```
Incompatible library version: libgdiplus.dylib requires version 8.0.0 or later, but libgif.7.dylib provides version 0.0.0'.
```

Due to build system changes upstream in giflib, the "compatibility version" of the dylib is actually now an _earlier_ version (0.0.0) which you shouldn't really ever do. When you link a binary against a library the compatibility version of the library is stored in the binary. If the binary detects that the library on disk is older than the compatibility version it was linked to, it will refuse to load - as was above. (Why it worked on Mojave and Catalina is a bit of a mystery.)

The fix was to "revision bump" `mono-libgdiplus` which effectively means we rebuild it from source again and create a new bottle. The revision number increase (instead of just replacing the existing bottle) also means end users will be offered the update as it forms a part of the version number (6.0.4_1).

Before the rebuild, this was `mono-libgdiplus` was linked to giflib:

```
/usr/local/opt/giflib/lib/libgif.7.dylib (compatibility version 8.0.0, current version 8.0.0)
```

And now this is how the linkage looks:

```
/usr/local/opt/giflib/lib/libgif.dylib (compatibility version 0.0.0, current version 7.2.0)
```

**Pull request closed without merging**
