### PR TITLE
cloudflare-wrangler2 3.1.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
@samford Do we still believe this is the only test we can do? I attempted to mess around with `wrangler secret list` but couldn't get the output to match correctly.

**Comment by samford** [comment]
> Do we still believe this is the only test we can do?

I think so and others kind of confirmed the idea when I asked about it in the upstream issue. 3.1.1 includes some changes that were supposed to address the `wrangler init --yes` bug but it still appears to be present, so I think `wrangler --version` is our only option (in terms of commands that don't involve network requests, authentication, etc.). I believe the `init` command is going away in the long-term anyway.

**Comment by p-linnane** [comment]
Alright. Just need to sort out the Linux linkage issue and we should be good then.

**Comment by cho-m** [comment]
May need to rebuild https://github.com/cloudflare/workerd from source rather than using pre-built.

**Pull request closed without merging**
