### PR TITLE
Update formula referencing deprecated `brew cask install`

### PR DESCRIPTION
**Pull request by peterlewis**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
LGTM, thanks!

For next time: we'd appreciate it if you could name your commits in the style of `formula: change`

**Comment by peterlewis** [comment]
> For next time: we'd appreciate it if you could name your commits in the style of `formula: change`

Roger that, shall do, @Rylan12!

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Oops, sorry. I just realized I forgot to leave you as the author of those commits. My apologies! Regardless of who's listed in the commit log, we really value your contributions! Thanks again!

**Comment by peterlewis** [comment]
Hah, no worries, not making it into the commit log shall not cause me to lose any sleep! 👍🏻

**Pull request merged**
