### PR TITLE
libtorch 1.10.0 and torchvision 1.11.1

### PR DESCRIPTION
**Pull request by ankane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Attempt to address #87780 and #87785

It looks like `pybind11_PREFER_third_party=OFF` was changed to `USE_SYSTEM_PYBIND11=ON` - https://github.com/pytorch/pytorch/pull/58951

### CODE REVIEW

**Comment by ankane** [comment]
It looks like the torchvision test failed due to https://github.com/pytorch/vision/pull/4375, which requires PyTorch to download the model manually. I've updated the test to check [ops are registered](https://github.com/pytorch/vision/blob/f093d0821194ed55f80f4764cf56e744f9217533/test/cpp/test_custom_operators.cpp#L10-L11).

**Comment by ankane** [comment]
It looks like LibTorch is ignoring the `USE_SYSTEM_PYBIND11` option. Created an issue upstream: https://github.com/pytorch/pytorch/issues/67974

**Comment by carlocab** [comment]
> Edit: `USE_SYSTEM_BIND11` works (but appears to be a typo), so we could use that temporarily.

We could pass both. CMake will ignore unrecognised options anyway. Has the typo been reported upstream?

**Comment by ankane** [comment]
Sounds good, added both for now (with a comment), and the typo is mentioned in the upstream issue.

**Comment by ankane** [comment]
It looks like the failures on 11 were due to an issue with `brew test-bot --only-setup`.

**Review by SMillerDev — APPROVED** [review]

**Comment by ankane** [comment]
Thanks @carlocab and @SMillerDev

**Pull request closed without merging**
