### PR TITLE
terrascan 1.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Test failure seen on other PRs that test previous `terrascan 1.5.1` (e.g. `go 1.16.4`: https://github.com/Homebrew/homebrew-core/pull/76791#issuecomment-835534109)
```make
==> /opt/homebrew/Cellar/terrascan/1.6.0/bin/terrascan scan -f /private/tmp/terrascan-test-20210514-20239-11fffm2/ami.tf -t aws
Error: terrascan: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /\tPolicies\ Validated\ \ :\t158\n\tViolated\ Policies\ \ \ :\t0\n\tLow\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tMedium\ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tHigh\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n/ to match "\n\nScan Summary -\n\n\tFile/Folder         :\t/private/tmp/terrascan-test-20210514-20239-11fffm2/ami.tf\n\tIaC Type            :\tterraform\n\tScanned At          :\t2021-05-14 20:27:08.731761 +0000 UTC\n\tPolicies Validated  :\t203\n\tViolated Policies   :\t0\n\tLow                 :\t0\n\tMedium              :\t0\n\tHigh                :\t0\n\t\n\n".
```

Looks like something changed in output format of previous terrascan 1.5.1 update, but for some reason CI didn't catch.

**Comment by chenrui333** [comment]
it did pass in my local though 🤔

**Comment by cho-m** [comment]
With test fix, it is probably okay now (haven't actually taken a look at what exactly changed though).
Other failures appear to be network issue and just need to rerun CI.

**Comment by cho-m** [comment]
Looks like still failing on Terrascan homepage HTTP 403 error.
If there is a **label** to skip this check, it might be needed.

I see on my local system that I can access website on browser, but plain curl errors:
```console
❯ curl -I https://www.accurics.com/products/terrascan/
HTTP/2 403
date: Sun, 16 May 2021 00:40:58 GMT
content-type: text/html; charset=UTF-8
```

**Comment by SMillerDev** [comment]
No label, but we can merge without.

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
Still 403

```
$ curl -I https://www.accurics.com/products/terrascan/
HTTP/2 403
date: Wed, 19 May 2021 05:06:19 GMT
content-type: text/html; charset=UTF-8
```

**Pull request closed without merging**
