### PR TITLE
blast 2.10.0

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @tseemann!!

**Comment by tseemann** [comment]
@chenrui333 thanks for fixing the ftp -> http ; i thought I had but clearly not!

**Comment by issyl0** [comment]
The download URL for 2.10.0 appears to have been pulled. We had an [issue](https://github.com/Homebrew/linuxbrew-core/issues/17238) about it over on Homebrew/linuxbrew-core. It's apparently been flaky in the past, too. What do we do in these situations? Revert and rebuild/republish the old version's bottles? Wait?

**Pull request closed without merging**
