### PR TITLE
minimal-racket 7.6

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
```
minimal-racket:
  * A top-level "man" directory was found
    Homebrew requires that man pages live under share.
    This can often be fixed by passing "--mandir=#{man}" to configure.
```

**Comment by issyl0** [comment]
@BrewTestBot test this please

I want to see what the error is to try and fix it as this PR is quite old.

**Comment by zachauten** [comment]
@issyl0 thanks and sorry for leaving the pr open for so long, there are a bunch i opened with a script and i'm trying to give them each a shot at fixing them before closing.

**Comment by issyl0** [comment]
No worries, I thought as much! I was looking for something fairly harmless to do and "audit failures" are usually that. But this wasn't as quick as I thought it would be. I tried variations on other `mandir` hacks we have in other formulae for when `./configure` args don't work, but nope.

**Comment by Bo98** [comment]
Try `--enable-useprefix`.

**Comment by zachauten** [comment]
Thanks for the help @Bo98 @issyl0 @issyl0!

**Pull request closed without merging**
