### PR TITLE
kyma-cli 1.7.0

### PR DESCRIPTION
**Pull request by suakbas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks @suakbas! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by chenrui333** [comment]
It is building with `go modules` now.

17:59:24 ==> dep ensure -vendor-only
17:59:24 could not find project Gopkg.toml, use dep init to initiate a manifest
17:59:24 
17:59:24 ==> Formula
17:59:24 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kyma-cli.rb

**Comment by SMillerDev** [comment]
Whoops, spoke to soon. Can you fix those @suakbas

**Comment by suleymanakbas91** [comment]
Oops, sorry! Should be ready to go now :)

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you @suakbas!

**Pull request closed without merging**
