### PR TITLE
glibmm@2.64 2.66.0 and pangomm@2.42 2.46.0

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Should the formula still be named `glibmm@2.64` if it's version 2.66? Same for `pangomm@2.42`.

**Comment by tschoonj** [comment]
That' a good question... To be honest there is not going to be gained much from renaming. There is already a more recent ABI incompatible release series out for both formulas.

**Comment by carlocab** [comment]
>To be honest there is not going to be gained much from renaming.

I think it's confusing for users though since all the other formulae with `@`s represent their versions correctly.

**Comment by tschoonj** [comment]
Ok fair enough, will do some renaming later today or tomorrow.

**Review by carlocab — APPROVED** [review]

**Comment by tschoonj** [comment]
@carlocab can this be merged in? Thanks!

**Comment by carlocab** [comment]
I was waiting for you to decide when it was ready. Merging.

**Pull request closed without merging**
