### PR TITLE
archi-steam-farm: Build using dotnet publish

### PR DESCRIPTION
**Pull request by JustArchi**
As per official documentation on https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Compilation

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
What is the difference between using `dotnet build` and `dotnet publish`?

**Comment by JustArchi** [comment]
From the docs:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build

> The dotnet build command builds the project and its dependencies into a set of binaries. The binaries include the project's code in Intermediate Language (IL) files with a .dll extension.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

> dotnet publish compiles the application, reads through its dependencies specified in the project file, and publishes the resulting set of files to a directory.

While in some specific situation (such as ASF), both outputs may be run, the only official way to prepare aplication for deployment is using `dotnet publish`, as can be found in the above link:

> The dotnet publish command's output is ready for deployment to a hosting system (for example, a server, PC, Mac, laptop) for execution. It's the only officially supported way to prepare the application for deployment.

Therefore, using `dotnet build` is wrong if we intend to prepare app for deployment. It'd be different if we wanted just to compile it, e.g. as part of verification in CI environment.

**Comment by JustArchi** [comment]
From practice I can say that `dotnet build` may miss some dependencies that are available under target system. For example, I could add one of ASF dependencies, such as `SteamKit2` library into GAC and `dotnet build` would likely omit putting it in the output directory, as it's available elsewhere. If the same output was then transfered to some other PC where `SteamKit2` wasn't in the GAC, the program would not run correctly.

`dotnet publish` solves this by rendering the files that are required for application to run on the machine it was compiled on as well as other machines that meet the same requirements (so basically .NET SDK). Unless there is some strong reason why homebrew uses `dotnet build`, it should use `dotnet publish` as per the guidelines above.

**Comment by SMillerDev** [comment]
I'm not sure what GAC is or how it factors into this, but generally we don't want software to compile in libraries that are otherwise available in the system. Dependencies are supposed to be resolved by depending on homebrew Formula.

In this case using `dotnet build` and `depends_on "Steamkit2"` seems like the better option.

**Comment by JustArchi** [comment]
So you want the formula to work on one machine and fail or another? With different build output depending what user does in his `dotnet` package, rendering apps unusable through user actions? We're not talking about installation dependencies here, we're talking about the user doing user action such as adding/removing stuff from GAC and in result having unusable, broken apps on his system that require a full reinstall to satisfy new environment.

That's beyond me, but if that's your decision then just close this PR, I can always use this as a reference when somebody asks me why ASF installed through homebrew doesn't work on his machine anymore.

**Comment by SMillerDev** [comment]
I have no idea what a GAC is, I'm just trying to understand the situation here. But the build servers build formula in a clean environment so it's unlikely that something will be unknowingly picked up by a build script. That won't be defined in the formula.

**Comment by carlocab** [comment]
Under what circumstances would a copy of `archi-steam-farm` built in a clean CI environnement stop working on a user's machine? Does this only happen when a user modifies their `dotnet` installation, or are there other instances in which this occurs?

**Comment by Abrynos** [comment]
> I have no idea what a GAC

GAC is the "global assembly cache" @SMillerDev 

### Here is my take on the issue

If there is a command line argument that is specifically there for publishing something ready for deployment: It should be used. Nothing stops the dotnet team from changing the output of `dotnet build` to something completely different tomorrow, which can not be deployed any more, and they don't even have to touch documentation to do that. And please don't reply with "We will worry about that, when the time has come", because when the time has come it's too late. Shit already hit the fan. 💩 Using an inferior solution just because "currently it works" is not the right way to go.

Currently this may be a problem of principle, but I'm with @JustArchi on this one. This change is a legit improvement and should be applied.

**Comment by SMillerDev** [comment]
> If there is a command line argument that is specifically there for publishing something ready for deployment: It should be used

I agree with the principle here, but earlier comments made it sound like this will package the entire dependency tree into the binary, which will cause a lot of duplication and angry users.

Nobody is saying that the change isn't valid, but someone wrote the formula like this, and it's important to know if they were wrong or simply had different goals.

**Comment by Abrynos** [comment]
> Nobody is saying that the change isn't valid, but someone wrote the formula like this, and it's important to know if they were wrong or simply had different goals.

Then let's ask them! It's your turn @SeekingMeaning

**Comment by carlocab** [comment]
I'm also still interested in answers to these questions:

> Under what circumstances would a copy of `archi-steam-farm` built in a clean CI environnement stop working on a user's machine? Does this only happen when a user modifies their `dotnet` installation, or are there other instances in which this occurs?
> 
> Do you have user reports of `archi-steam-farm` not working because we use `dotnet build` instead of `dotnet publish`?

**Comment by SeekingMeaning** [comment]
I was summoned? Let's see...

> > Nobody is saying that the change isn't valid, but someone wrote the formula like this, and it's important to know if they were wrong or simply had different goals.
> 
> Then let's ask them! It's your turn @SeekingMeaning

Ah. I went with `dotnet build` since that's what `gitversion` does. It was the first formula to use `dotnet` (if I remember correctly), so I used it as an example for updating the `archi-steam-farm` formula. However, it sounds like `dotnet publish` is the command that we should be using, since it also includes necessary dependencies. I guess this would make dotnet formulae similar to ones that use python or node. However, that leads to a question: does dotnet have lock files? If not, then that might mean that we should add `resource` blocks for dependencies. (In this specific case, it sounds like `archi-steam-farm` doesn't have any dependencies, so we don't need to add `resource` blocks to this formula. Not certain though.)

> I'm also still interested in answers to these questions:
> 
> > Under what circumstances would a copy of `archi-steam-farm` built in a clean CI environnement stop working on a user's machine? Does this only happen when a user modifies their `dotnet` installation, or are there other instances in which this occurs?
> > Do you have user reports of `archi-steam-farm` not working because we use `dotnet build` instead of `dotnet publish`?

I, too, am interested. I might be wrong, but it sounds like the formula is currently working as is, although it might break in the future if dependencies are added upstream. @JustArchi could you clarify?

**Comment by JustArchi** [comment]
> @JustArchi could you clarify?

ASF already has its dependencies, and I've already explained above under what conditions the current approach won't work.

Regardless, I'm no longer interested in this PR since maintainers of the project expect me to defend and rationalize on MS decision, something I really don't care enough to be doing. I'll only leave https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish quote once again:

> It's the only officially supported way to prepare the application for deployment.

**Comment by alebcay** [comment]
To answer some of Homebrew team's questions, the [documentation on `dotnet publish`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) says this:

> dotnet publish compiles the application, reads through its dependencies specified in the project file, and publishes the resulting set of files to a directory. The output includes the following assets:
> * Intermediate Language (IL) code in an assembly with a dll extension.
> * A .deps.json file that includes all of the dependencies of the project.
> * A .runtimeconfig.json file that specifies the shared runtime that the application expects, as well as other configuration options for the runtime (for example, garbage collection type).
> * The application's dependencies, which are copied from the NuGet cache into the output folder.

The last entry is probably of most interest to Homebrew here. It looks like the path forward is to identify said dependencies and either

- Depend on NuGet/the DotNet build process to resolve these dependencies, if any, at `dotnet build` + `dotnet publish` time (as far as I can tell this is the upstream proposed solution), a la Node.js/Python/Golang software shipped in Homebrew
- Checksum and download these dependencies, if any, as Homebrew `resource` blocks, a la Python software shipped in Homebrew
- Ship these dependencies, if any, as separate formulae and convince packages that need them to depend on formulae

> I'm no longer interested in this PR since maintainers of the project expect me to defend and rationalize on MS decision, something I really don't care enough to be doing

The reason maintainers are asking so many questions is because we're not very familiar at all with the DotNet build and dependency ecosystem. Our questions aren't only with regard to ASF, we're trying to learn more about what the commands actually _do_ because that might affect how we ship other software that builds with DotNet.

We're not just trying to decide whether to change one word in a single package's build instructions. We're trying to decide whether to have a different precedent for how we handle building and packaging DotNet-based software in general.

> It's easier for me to claim that homebrew does things wrong rather than convincing maintainers of the project to follow the official docs.

Yeah, it's always going to be easier to blame other people and fling shit at them than it is to take the time to communicate effectively. That's nothing new.

**Comment by alebcay** [comment]
It looks like ASF has the following dependencies:
```
❯ dotnet list package
Project 'ArchiSteamFarm' has the following package references
   [net5.0]:
   Top-level Package                                 Requested   Resolved
   > AngleSharp.XPath                                            1.1.7
   > ConfigureAwaitChecker.Analyzer                              5.0.0
   > CryptSharpStandard                                          1.0.0
   > Humanizer                                                   2.11.10
   > JetBrains.Annotations                                       2021.2.0
   > Markdig.Signed                                              0.25.0
   > Newtonsoft.Json                                             13.0.1
   > Nito.AsyncEx.Coordination                                   5.1.0
   > NLog                                                        4.7.10
   > NLog.Web.AspNetCore                                         4.13.0
   > SteamKit2                                                   2.4.0-Alpha.2
   > Swashbuckle.AspNetCore                                      6.1.4
   > Swashbuckle.AspNetCore.Annotations                          6.1.4
   > Swashbuckle.AspNetCore.Newtonsoft                           6.1.4
   > System.Composition                                          5.0.1
   > System.IO.FileSystem.AccessControl                          5.0.0
   > System.Linq.Async                                           5.0.0
   > System.Security.Cryptography.ProtectedData                  5.0.0

Project 'ArchiSteamFarm.Tests' has the following package references
   [net5.0]:
   Top-level Package                     Requested   Resolved
   > ConfigureAwaitChecker.Analyzer                  5.0.0
   > Microsoft.NET.Test.Sdk                          16.10.0
   > MSTest.TestAdapter                              2.2.4
   > MSTest.TestFramework                            2.2.4

Project 'ArchiSteamFarm.CustomPlugins.ExamplePlugin' has the following package references
   [net5.0]:
   Top-level Package                         Requested   Resolved
   > ConfigureAwaitChecker.Analyzer                      5.0.0
   > Newtonsoft.Json                                     13.0.1
   > SteamKit2                                           2.4.0-Alpha.2
   > System.Composition.AttributedModel                  5.0.1

Project 'ArchiSteamFarm.CustomPlugins.PeriodicGC' has the following package references
   [net5.0]:
   Top-level Package                         Requested   Resolved
   > ConfigureAwaitChecker.Analyzer                      5.0.0
   > System.Composition.AttributedModel                  5.0.1

Project 'ArchiSteamFarm.OfficialPlugins.SteamTokenDumper' has the following package references
   [net5.0]:
   Top-level Package                         Requested   Resolved
   > ConfigureAwaitChecker.Analyzer                      5.0.0
   > Newtonsoft.Json                                     13.0.1
   > SteamKit2                                           2.4.0-Alpha.2
   > Swashbuckle.AspNetCore.Annotations                  6.1.4
   > System.Composition.AttributedModel                  5.0.1
```

So either we just let DotNet manage its own dependencies here or we need to do something with these.

**Comment by alebcay** [comment]
Also possibly of interest, I ran `dotnet build` and `dotnet publish` with two different output directories and checked the difference:
```
❯ diff -rq out_build out_publish
Only in out_build: ArchiSteamFarm.runtimeconfig.dev.json
Only in out_build: ref
```

Even the output from `dotnet build` has all of the needed DLLs. So as far as dependencies go, we're already shipping them anyways.

Having investigated that, it doesn't seem to improve/worsen the dependency situation on the Homebrew side and somehow manages to fix issues reported upstream, so I say we may as well make the switch.

**Comment by alebcay** [comment]
Since this PR can't be reopened, continuing discussion and investigation at #81873.

**Comment by carlocab** [comment]
Thanks for the explanation, @alebcay. That helps a lot. 

Pardon me for not wanting to ship code changes I don't understand. I guess others can afford to be more cavalier about it -- but perhaps that comes with the territory of claiming to have explained things that have never been explained, or quoting things "once again" for the very first time.

**Pull request closed without merging**
