### PR TITLE
beast 1.10.1

### PR DESCRIPTION
**Pull request by jonchang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jonchang** [comment]
Will probably hit a build error due to https://github.com/beast-dev/beast-mcmc/pull/1011

**Comment by jonchang** [comment]
Build failed but the patch fixing has been merged upstream in https://github.com/beast-dev/beast-mcmc/commit/0b6ab7d5771648051e430579c4baa51aea497c65. I'm just gonna wait for them to cut a new release since I don't recall homebrew/core's patch policy.

**Comment by DomT4** [comment]
If it's fixed upstream we're happy to consider adopting that patch.

**Comment by jonchang** [comment]
Alright then, let's see if this works.

**Pull request closed without merging**
