### PR TITLE
zsh-completions 0.25.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@zmwangx any idea what's going on here? This used to pass, but seems to be failing even for the current version: https://jenkins.brew.sh/job/Homebrew%20Testing/34/

**Comment by zmwangx** [comment]
No idea, can't reproduce in any non-interactive environment. Maybe explicitly pipe nothing into it?

By the way, it's a rather shitty test anyway; it is actually testing Zsh's compinit, rather than zsh-completions, and it relies on the formula being linked. How about replacing it with something like

```rb
  test do
    (testpath/"test.zsh").write <<-EOS.undent
      fpath=(#{pkgshare} $fpath)
      autoload _ack
      which _ack
    EOS
    assert_match /^_ack/, shell_output("/bin/zsh test.zsh")
  end
```

Not saying this is any better, but it is basically functionally equivalent, and the shell doesn't need to be interactive (due to skipping `compinit` and directly autoloading `_ack`, which is the only thing `compinit` does that's relevant to `which _ack`).

**Comment by ilovezfs** [comment]
@zmwangx mysterious that it broke out of the blue but your new test seems to have done the trick. Thanks.

**Comment by zmwangx** [comment]
No problem. Another useless test doesn't hurt 😋

**Pull request merged**
