### PR TITLE
sbcl 2.0.8

### PR DESCRIPTION
**Pull request by gromgit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by gromgit** [comment]
https://github.com/Homebrew/homebrew-core/pull/60516/checks?check_run_id=1059592544#step:5:53
```
==> FAILED
==> Testing acl2
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200902-78788-1n3muue.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/acl2.rb --verbose --retry
==> /usr/local/Cellar/acl2/8.3/bin/acl2 < /private/tmp/acl2-test-20200902-78789-a5sels/simple.lisp | grep 'ACL2 !>'
fatal error encountered in SBCL pid 78802 pthread 0x14648dc0:
core was built for runtime "Catalina-brew-2020-06-29-17-18-07" but this is "Catalina-brew-2020-09-02-04-24-17"
```
@tani, since you introduced the `acl2` formula, can you advise on what's triggering this, and what remedial action would have to be taken? Thanks much!

**Comment by gromgit** [comment]
The obvious solution (which passes CI) is to bump `acl2` along with `sbcl`, but I'm open to any alternatives.

**Comment by SMillerDev** [comment]
> The obvious solution (which passes CI) is to bump acl2 along with sbcl, but I'm open to other less resource-intensive alternatives.

It's just CI time right? Go for it!

**Comment by gromgit** [comment]
Cool, then this PR's ready for review.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @gromgit

**Pull request closed without merging**
