### PR TITLE
gdbm 1.18.1

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails on `pwntools` test. Maybe the new version (#33485) will solve the issue. 🤞

**Comment by zbeekman** [comment]
Yes, in theory the new version of pwntools should fix this (known bug in pwntools).

However, pwntools website is down so online audits are failing on #33485. If someone gives it a 👍 I'll merge it.

**Comment by zbeekman** [comment]
> Yes, in theory the new version of pwntools should fix this (known bug in pwntools).

Well let me clarify, there are multiple failures, pwntools upgrade will only fix pwntools, if that.

**Comment by commitay** [comment]
Failures are all known problems, merging.

**Pull request closed without merging**
