### PR TITLE
neovim 0.3.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Not released yet.

**Comment by af** [comment]
Can this be re-opened? Looks like it's officially released now: https://github.com/neovim/neovim/releases/tag/v0.3.1

**Comment by javian** [comment]
`luabitop` has been updated in this release to `1.0.2-3`. There is a newer version of luacheck available but neovim `0.3.1` uses the one currently resourced. There is also a new version of `lua_cliargs` so that should also be updated to `3.0-2` .

**Comment by ilovezfs** [comment]
Thanks @javian. Are these all listed in one place?

**Comment by javian** [comment]
No not quite. You can get some of the versions used for resourced dependencies with
```
➜  neovim git:(cd94dd6bb) grep -R "ARGS build" *
third-party/cmake/BuildLuarocks.cmake:  ARGS build mpack 1.0.7-0 ${LUAROCKS_BUILDARGS}
third-party/cmake/BuildLuarocks.cmake:  ARGS build lpeg 1.0.1-1 ${LUAROCKS_BUILDARGS}
third-party/cmake/BuildLuarocks.cmake:  ARGS build inspect 3.1.1-0 ${LUAROCKS_BUILDARGS}
third-party/cmake/BuildLuarocks.cmake:    ARGS build luabitop 1.0.2-3 ${LUAROCKS_BUILDARGS}
third-party/cmake/BuildLuarocks.cmake:    ARGS build penlight 1.5.4-1 ${LUAROCKS_BUILDARGS}
third-party/cmake/BuildLuarocks.cmake:    ARGS build busted 2.0.rc12-1 ${LUAROCKS_BUILDARGS}
third-party/cmake/BuildLuarocks.cmake:    ARGS build luacheck 0.21.2-1 ${LUAROCKS_BUILDARGS}
third-party/cmake/BuildLuarocks.cmake:    ARGS build nvim-client 0.1.0-1 ${LUAROCKS_BUILDARGS}
➜  neovim git:(cd94dd6bb)
```
Some of the resources are dependencies to the resource but I'm not sure you would list those.

**Comment by dkarter** [comment]
Yay new NeoVim! :) 🎉

**Comment by ilovezfs** [comment]
>`luabitop` has been updated in this release to `1.0.2-3`. There is a newer version of luacheck available but neovim `0.3.1` uses the one currently resourced. There is also a new version of `lua_cliargs` so that should also be updated to `3.0-2` .

luabitop didn't change between 1.0.2-1 and 1.0.2-3, only how the source is fetched, so I'm leaving that one unchanged for now as it will just complicate the formula.

busted 2.0.rc12-1 depends on lua_cliargs == 3.0-1 specifically, so I'm also leaving that unchanged.

**Pull request closed without merging**
