### PR TITLE
Fixes #43532 - Stubby 0.2.6 fails to start

### LINKED ISSUE #43532: Stubby 0.2.6 fails to start because of missing referenced libidn2 in libgetdns.10.dylib
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```Error: Not Found```

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: df3ad8d2619e15bede0bc01ce3e38fc7cc14c3e1
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_202
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:

- What you were trying to do (and why)

Install Stubby 0.2.6 on an empty homebrew installation.

- What happened (include command output)

Stubby gets installed but fails to start.

```
dyld: Library not loaded: /usr/local/opt/libidn2/lib/libidn2.0.dylib
  Referenced from: /usr/local/opt/getdns/lib/libgetdns.10.dylib
  Reason: image not found
Abort trap: 6
```

```
otool -L /usr/local/opt/getdns/lib/libgetdns.10.dylib 
/usr/local/opt/getdns/lib/libgetdns.10.dylib:
	/usr/local/opt/getdns/lib/libgetdns.10.dylib (compatibility version 12.0.0, current version 12.2.0)
	/usr/local/opt/unbound/lib/libunbound.8.dylib (compatibility version 10.0.0, current version 10.2.0)
	/usr/local/opt/libidn2/lib/libidn2.0.dylib (compatibility version 4.0.0, current version 4.6.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

- What you expected to happen

Stubby should start and run without errors.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install stubby
```

### PR DESCRIPTION
**Pull request by big-r81**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes  #43532

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is an issue of opportunistic linkage, meaning that the binary bottles for getdns got linked to libidn2 because it happened to be present on our CI machine at the time of building (because it was built at the same time as other formulas).

Before fixing it, we need to answer the question: is libidn2 really preferable to libidn? If so, then this is the right fix. If not, we need to rebuild the bottles, and force libidn2 not to be in (by a suitable configure option).

**Comment by big-r81** [comment]
I wrote an email to the getdns team.

The [build instructions](https://github.com/getdnsapi/getdns#building-and-external-dependencies) are showing the use of version 2 of libidn.

**Comment by big-r81** [comment]
I got an answer from William (thanks to @wtoorop):
> We have no preference really, both will suffice. That said, libidn2 in
> getdns is slightly more straightforward and less lines of code than
> libidn1.  Though we have to keep support for and maintain both anyway,
> so ... whatever is most convenient for you.

@fxcoudert So what to do?

**Comment by fxcoudert** [comment]
libidn2 has many more installs on Homebrew, so let's use that.

**Comment by fxcoudert** [comment]
Thanks @big-r81 for the pull request!

**Pull request closed without merging**
