### PR TITLE
git 2.22.1

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by chrmoritz** [comment]
I think the test-bot failure here is caused by https://github.com/Homebrew/homebrew-test-bot/pull/267. Since the formula itself (`git` in this case) isn't uninstalled anymore, the `git` version installed by this formula is used during the cleanup (calling `git -C homebrew/homebrew-core checkout master -f`). But unfortunately we've already forcefully uninstalled it's dependency and therefore it's broken.

**Comment by leonklingele** [comment]
One could revert the aforementioned change (https://github.com/Homebrew/homebrew-test-bot/pull/267) and conditionally `brew uninstall` only if the `formula_name` is not on a whitelist (which includes `git`).

**Comment by lembacon** [comment]
Since this was an existing issue with `brew-test-bot`, and the bottle was successfully built, I'm merging this as-is.

**Comment by lembacon** [comment]
Thanks @leonklingele! And it would be great if you'd like to submit a PR to [Homebrew/homebrew-test-bot](https://github.com/Homebrew/homebrew-test-bot) to address this issue. 😜

**Pull request closed without merging**
