### PR TITLE
tarantool 1.9.2.0

### PR DESCRIPTION
**Pull request by bigbes**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Fails to build luajit on Mojave (macOS 10.14). We fixed it in the `luajit` formula by adding: 

```
+    # Per https://luajit.org/install.html: If MACOSX_DEPLOYMENT_TARGET
+    # is not set then it's forced to 10.4, which breaks compile on Mojave.
+    ENV["MACOSX_DEPLOYMENT_TARGET"] = MacOS.version
```

Maybe this is needed here too?

**Comment by bigbes** [comment]
I'll try to patch brewfile with modifying env/passing it to cmake, but I guess CMake scripts in Tarantool should be patched..

**Review by fxcoudert — APPROVED** [review]

**Comment by bigbes** [comment]
Wow! It works. Thank you, @fxcoudert !

**Comment by fxcoudert** [comment]
Thanks @bigbes for the pull request!

**Pull request closed without merging**
