### PR TITLE
workflows: add a Big Sur bottling workflow

### PR DESCRIPTION
**Pull request by fxcoudert**
The basis for this workflow is taken from `dispatch-build-bottle.yml` by @dawidd6 
We're going to build a lot of Big Sur bottles, so make our life easier with a specific workflow:
- for Big Sur
- that always uploads and commits on success

*Help wanted!* Ideally I would like to make it able to run on multiple formulas at once, and loop over the formulas passed as argument. I don't know the Github Actions syntax well enough to achieve that.

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
> * for Big Sur

I'm pretty sure that should already be handled by https://github.com/Homebrew/homebrew-core/blob/542ff01c92e32b04301c2c5aa1ca335b8c438da0/.github/workflows/dispatch-build-bottle.yml#L26



> * that always uploads and commits on success

It'd be good to extend  https://github.com/Homebrew/homebrew-core/blob/542ff01c92e32b04301c2c5aa1ca335b8c438da0/.github/workflows/dispatch-build-bottle.yml#L26 to add conditionals to do this, I think.

**Comment by MikeMcQuaid** [comment]
> Ideally I would like to make it able to run on multiple formulas at once, and loop over the formulas passed as argument.

Multiple formulae can already be passed to the existing workflow. I think one workflow-run-per-formula would make debugging easier and avoid opportunistic linking, though.

**Comment by MikeMcQuaid** [comment]
See also https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/dispatch-build-bottle.rb for something that can be extended to ease doing this somewhat programatically. Loops, handling multiple formulae etc. are better done from that script so that there's one-workflow-per-formula.

**Comment by fxcoudert** [comment]
The idea was to have a specialised workflow with default settings so we can launch things more quickly. I guess scripting around `brew dispatch-build-bottle` is probably a better way to achieve that. Thanks @MikeMcQuaid

**Pull request closed without merging**
