### PR TITLE
dotnet: update the sdk to use the latest 8.0.1xx

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Currently, the dotnet formula is using `prep.sh` to pull the sdk, which is specified in global.json, but it is not up to date with the latest release (grabbed from [here](https://github.com/cake-build/cake/pull/4377#issuecomment-2446366262))

image

As result, it would require to change the dotnet formulae (like kiota or cake) build to match the sdk shipped with dotnet formula. Thus updating in here to use the latest sdk 4.x.x

> For SDKs there are currently three supported feature bands
> 
> - 8.0.1xx - This is the the foundational features and improvements introduced in .NET 8 + security patches only, no changes in behavior or new features. It's fixed at MSBuild 17.8 feature set.
> - 8.0.3xx - This includes updates and improvements made after the initial release up to MSBuild 17.10 feature set.
> - 8.0.4xx - This has further updates and refinements fter the previous up to MSBuild17.11 feature set.

from https://github.com/cake-build/cake/pull/4377#issuecomment-2439745938

relates to:
- https://github.com/cake-build/cake/pull/4377
- https://github.com/microsoft/kiota/pull/5548

cc @devlead @baywet

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Seems fine to me.

**Comment by cho-m** [comment]
Source build is only supported on the .1xx releases[^1]. The VMR monorepo is aligned to that those specific feature bands, e.g. 
* .NET 8 - https://github.com/dotnet/dotnet/tree/release/8.0.1xx
* .NET 9 - https://github.com/dotnet/dotnet/tree/release/9.0.1xx

The prep pulls a bootstrap .NET which is mainly used to build the full .NET. The actual code for SDK is part of monorepo, e.g. https://github.com/dotnet/dotnet/tree/release/8.0.1xx/src/sdk

[^1]: https://github.com/dotnet/source-build?tab=readme-ov-file#support

**Comment by chenrui333** [comment]
> There isn't a way for us to move to another SDK. Each .NET tag 8.0.xx is aligned to SDK 8.0.1xx, which is why the releases list both version numbers, e.g. [dotnet/source-build#4658](https://github.com/dotnet/source-build/discussions/4658). In the past, we use to version off of SDK which is more accurate, but switched to simplify livecheck/bumps.

that is good to know

for the context, the one with dotnet 8.0.8 has sdk version `8.0.108` which has some security vulnerabilities, let me just update to use the latest 8.0.1xx then.

**Comment by cho-m** [comment]
> for the context, the one with dotnet 8.0.8 has sdk version `8.0.108` which has some security vulnerabilities, let me just update to use the latest 8.0.1xx then.

What needs to be done is bump formula to 8.0.10.

So, should be handled via #193272

**Comment by chenrui333** [comment]
> > for the context, the one with dotnet 8.0.8 has sdk version `8.0.108` which has some security vulnerabilities, let me just update to use the latest 8.0.1xx then.
> 
> What needs to be done is bump formula to 8.0.10.
> 
> So, should be handled via #193272

but that pr does not build

```
  /private/tmp/dotnet-20241008-7321-p613u1/repo-projects/Directory.Build.targets(265,5): error MSB3073: The command "/private/tmp/dotnet-20241008-7321-p613u1/src/sdk/build.sh  --ci --configuration Release --restore --build --pack --publish -bl /p:ArcadeBuildFromSource=true /p:CopyWipIntoInnerSourceBuildRepo=true /p:DotNetBuildOffline=true /p:CopySrcInsteadOfClone=true /p:DotNetPackageVersionPropsPath="/private/tmp/dotnet-20241008-7321-p613u1/artifacts/obj/arm64/Release/PackageVersions.sdk.props" /p:AdditionalSourceBuiltNupkgCacheDir="/private/tmp/dotnet-20241008-7321-p613u1/artifacts/obj/arm64/Release/blob-feed/packages/" /p:ReferencePackageNupkgCacheDir="/private/tmp/dotnet-20241008-7321-p613u1/prereqs/packages/reference/" /p:PreviouslySourceBuiltNupkgCacheDir="/private/tmp/dotnet-20241008-7321-p613u1/prereqs/packages/previously-source-built/" /p:SourceBuildUseMonoRuntime= --nodereuse false /p:PackageProjectUrl=https://github.com/dotnet/sdk /p:PublishCompressedFilesPathPrefix=/private/tmp/dotnet-20241008-7321-p613u1/artifacts/obj/arm64/Release/blobs/Sdk/ /p:PortableRid=osx-arm64 /p:TargetRid=osx-arm64 -v minimal >> /private/tmp/dotnet-20241008-7321-p613u1/artifacts/logs/sdk.log 2>&1" exited with code 137. [/private/tmp/dotnet-20241008-7321-p613u1/repo-projects/sdk.proj]
    /private/tmp/dotnet-20241008-7321-p613u1/src/sdk/eng/common/tools.sh: line 561: 68305 Killed: 9               jq -e '.tools | has("runtimes")' "$global_json_file" >&/dev/null
```

**Comment by cho-m** [comment]
The inreplace here doesn't impact the installed SDK.

The way forward is to fix the other PR as we need the code in the 8.0.10 tag to get the 8.0.110 SDK

**Comment by cho-m** [comment]
Run in #193272 is fine so far. Patches/workarounds I applied in #196209 probably help.

Going to cancel self-hosted Linux here to reduce queue size and for reasons mentioned in prior comment.

**Comment by carlocab** [comment]
Seems like this is no longer needed.

**Pull request closed without merging**
