### PR TITLE
vc4asm 0.3

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

~~This admittedly doesn't build for me locally, but the error looks like it's coming from Ruby, so I'm wondering if it's just my system that's the issue.~~

### CODE REVIEW

**Comment by carlocab** [comment]
This is a weird error, as it looks like it's coming from Ruby?
```
Error: An exception occurred within a child process:
  Errno::EISDIR: Is a directory - read
```

**Comment by carlocab** [comment]
This is the error output when doing `brew install -s --debug`:

```
Error: An exception occurred within a child process:
  Errno::EISDIR: Is a directory - read
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `copy_stream'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `block (2 levels) in copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:419:in `block in cp'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1566:in `block in fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1564:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1564:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:418:in `cp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1228:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2262:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2261:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:87:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:198:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2241:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1216:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:134:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:227:in `<main>'
```

**Comment by carlocab** [comment]
Found it:

```
Permissions Size User     Date Modified Name
.rw-r--r--   13k carlocab 26 Dec  2019  .cproject
.rw-r--r--   453 carlocab 26 Dec  2019  .gitignore
.rw-r--r--   807 carlocab 26 Dec  2019  .project
drwxr-xr-x     - carlocab 26 Dec  2019  CMakeCache.txt
.rw-r--r--  2.4k carlocab 26 Dec  2019  CMakeLists.txt
drwxr-xr-x     - carlocab 26 Dec  2019  doc
drwxr-xr-x     - carlocab 26 Dec  2019  extra
.rwxr-xr-x    56 carlocab 26 Dec  2019  makeDebug.Cmd
.rwxr-xr-x    31 carlocab 26 Dec  2019  makeRelease.Cmd
.rwxr-xr-x    36 carlocab 26 Dec  2019  makeTest.Cmd
.rw-r--r--  1.6k carlocab 26 Dec  2019  README.md
.rwxr-xr-x    32 carlocab 26 Dec  2019  runTest.Cmd
drwxr-xr-x     - carlocab 26 Dec  2019  sample
drwxr-xr-x     - carlocab 26 Dec  2019  share
drwxr-xr-x     - carlocab 26 Dec  2019  src
drwxr-xr-x     - carlocab 26 Dec  2019  test
```

`CMakeCache.txt` is a _directory_, that contains
```
Permissions Size User     Date Modified Name
.rw-r--r--   303 carlocab 26 Dec  2019  readme.txt
```
with
```
❯ cat CMakeCache.txt/readme.txt
Just another work around for hard coded paths in cmake:
Prevent creation of CMakeCache.txt to allow out of source build for different platforms.
The name clash of this directory prevents the creation of the cache file and enables cross platform builds.
And this file forces git to create the directory.
```

Unfortunately, this breaks `brew` [here](https://github.com/Homebrew/brew/blob/e3b451cce8b555da5c4043767fe1659d14d04264/Library/Homebrew/formula.rb#L1228):
```ruby
      ensure
        cp Dir["config.log", "CMakeCache.txt"], logs
      end
```
where `brew`, quite reasonably, expects `CMakeCache.txt` to be a file.

**Comment by carlocab** [comment]
```
==> /usr/local/Cellar/vc4asm/0.3/bin/vc4asm -o test.hex -V /usr/local/Cellar/vc4asm/0.3/share/vc4.qinc test.qasm
/usr/local/Cellar/vc4asm/0.3/share/vc4.qinc: ERROR P250: Cannot locate file '/usr/local/Cellar/vc4asm/0.3/share/vc4.qinc'.
test.qasm (1,12): ERROR P31.10: The identifier 'sacq' is undefined.
FATAL a250: Aborted because of earlier errors.
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
