### PR TITLE
mikutter: depend on xz

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
This is in support of https://github.com/Homebrew/homebrew-core/pull/106045 but is slightly different from the other PRs.  Currently the formula declares `uses_from_macos "xz"` but this is misleading - it actually depends on brewed `xz` on macOS as well.  This happens because `python@3.9` is the dependency tree of `mikutter` and it depends on brewed `xz`, which gets linked instead of version provided by macOS.  As with the other PRs we can investigate if can use the macOS version after `python@3.9` is removed from the dependency tree.

**Comment by cho-m** [comment]
Website looks like it was changed to TLS 1.3-only. I think only Monterey runners support that with default curl, so may need to use Homebrew curl.
```console
❯ curl --tls-max 1.2 https://mikutter.hachune.net/ -I
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version

❯ curl --tls-max 1.3 https://mikutter.hachune.net/ -I
HTTP/2 200
...
```

**Comment by carlocab** [comment]
Looks like this fails to build on ARM Monterey because it tries to build a vendored `libxml2` but chokes because it doesn't recognise the build triplet `arm64-apple-darwin21`.

**Comment by danielnachun** [comment]
Both of the above issues should now be fixed, assuming the Intel runners don't hit any unexpected problems.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
