### PR TITLE
qcachegrind: move to homebrew/gui

### PR DESCRIPTION
**Pull request by dunn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

https://github.com/Homebrew/homebrew-gui/pull/36

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@dunn I'm actually thinking we do the opposite and start moving stuff back out of the non-community taps if it's popular and used and has no possible `cask` and otherwise boneyard it. I'm not convinced any more by the merits or user experience of maintaining a bunch of separate taps for this stuff where they are only maintained by a subset of current maintainers. Thoughts?

**Comment by dunn** [comment]
Sounds fine to me.  I'm not sure if I have access to the analytics; is this formula at all popular?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Let's pass on this for now.

**Pull request closed without merging**
