### PR TITLE
python@*: setuptools 41.0.1, pip 19.1.1, wheel 0.33.4

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by SMillerDev** [comment]
Bunch of unauthorized messages from bintray. I'm requeueing.

@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by scpeters** [comment]
I believe that this is suffering from a test-bot bug that I've observed in a tap that I maintain, but I haven't reported it because I've found it difficult to describe succinctly. I've observed it when building multiple bottles in a pull request and some downstream formulae depend on one of the formula directly, and the other indirectly.

For example, this PR modifies `python` and `python@2`. `python` gets built first and all its direct dependencies are tested without any failures. Then it is uninstalled, the `python@2` bottle is built (successfully) and the direct dependencies of `python@2` are tested. The first formula to fail is `alot`, which depends directly on `python@2`, but not directly on `python`:

* https://github.com/Homebrew/homebrew-core/blob/master/Formula/alot.rb#L18-L25

`alot` has multiple direct dependencies that depend indirectly on `python`, though, such as `gpgme` and `notmuch`. For some reason, `test-bot` ends up trying to find the new python bottle on bintray instead of installing it from the filesystem.

In terms of this pull request; I think a workaround would be to split it into separate PR's for `python` and `python@2`, but we should figure out how to fix the underlying issue in test-bot.

**Comment by scpeters** [comment]
Reported in https://github.com/Homebrew/homebrew-test-bot/issues/266

**Comment by scpeters** [comment]
@fxcoudert do you have any opinion about the changes in https://github.com/Homebrew/homebrew-test-bot/pull/267?

**Comment by fxcoudert** [comment]
@scpeters not really, no

**Pull request closed without merging**
