### PR TITLE
kafka 3.5.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/kafka/3.5.0/bin/kafka-server-stop
```

**Comment by chenrui333** [comment]
previous run, https://github.com/Homebrew/homebrew-core/actions/runs/5284135267/job/14309307226?pr=133887

**Comment by chenrui333** [comment]
only test failure on linux
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/kafka/3.5.0/bin/kafka-server-stop
  No kafka server to stop
  Killing child processes...
  Error: kafka: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/kafka/3.5.0/bin/kafka-server-stop
```

**Comment by miimou** [comment]
* putting line `ENV["COLUMNS"] = ""` after `ENV["LOG_DIR"] = "#{testpath}/kafkalog"` will solve CI problem.
```diff
diff --git a/Formula/k/kafka.rb b/Formula/k/kafka.rb
index ed872f218a9..3b0e0239eb9 100644
--- a/Formula/k/kafka.rb
+++ b/Formula/k/kafka.rb
@@ -68,6 +68,7 @@ class Kafka < Formula

   test do
     ENV["LOG_DIR"] = "#{testpath}/kafkalog"
+    ENV["COLUMNS"] = ""

     (testpath/"kafka").mkpath
     cp "#{etc}/kafka/zookeeper.properties", testpath/"kafka"
```

* this problem is caused by 3 things
    1. `brew test-bot` sets environment variable `COLUMNS` for `brew test` (maybe after [Homebrew/brew#15255](https://github.com/Homebrew/brew/pull/15255))
    2. `kafka-server-stop` script uses `ps ax` command to determine Process ID of kafka instances ([kafka/bin/kafka-server-stop.sh, lines 18-28](https://github.com/apache/kafka/blob/b97e8203eb1fb016cd7cccd3dbf5fecc716969be/bin/kafka-server-stop.sh#L18-L28))
    3. `ps` command implementation of Ubuntu truncates its output if environment variable `COLUMNS` is set even if its output is piped ([procps-ng/procps/src/ps/global.c, lines 226-230](https://gitlab.com/procps-ng/procps/-/blob/675246119df143a5f8ced6e3313edac6ccc3e222/src/ps/global.c#L226-L230))
        * this is Linux(Ubuntu) specific. because macOS uses its own implementation that ignores `COLUMNS` if its output is piped ([adv_cmds/ps/ps.c, lines 484-488](https://github.com/apple-oss-distributions/adv_cmds/blob/320b8e327652c75d74e60adb9d085f4a81ac3d9d/ps/ps.c#L484-L488), which follows [lines 237-245 where it looks `COLUMNS`](https://github.com/apple-oss-distributions/adv_cmds/blob/320b8e327652c75d74e60adb9d085f4a81ac3d9d/ps/ps.c#L237-L245))

* there are some possible fixes
    * treat it as upstream problem of kafka which does not use `ps axww` to avoid truncation
    * treat it as `brew-test-bot` problem that causes unexpected environment variable is set for `brew test`
    * add patch that replaces `ps ax` to `ps axww`, to `kafka` formula
* but, in my thought, because this problem blocks [`openjdk` 20.0.2](https://github.com/Homebrew/homebrew-core/pull/137124) which is a security fix, adding `ENV["COLUMNS"] = ""` is good because it can be applied quickly

**Comment by SMillerDev** [comment]
If someone reports the bug upstream I'm fine accepting a workaround in brew

**Comment by miimou** [comment]
I reported to kafka Jira ([KAFKA-15413](https://issues.apache.org/jira/browse/KAFKA-15413)).

They have some issues about `kafka-server-stop` script and `ps ax` truncation for some years. ([KAFKA-4931](https://issues.apache.org/jira/browse/KAFKA-4931) and [KAFKA-4110](https://issues.apache.org/jira/browse/KAFKA-4110)) So, this report may need long time or be rejected.

**Comment by ZhongRuoyu** [comment]
Thank you for the fix and upstream report, @miimou.

**Review by ZhongRuoyu — APPROVED** [review]

**Review by branchv — APPROVED** [review]

**Comment by chenrui333** [comment]
@miimou thanks for getting this forward 💯

**Pull request merged**
