### PR TITLE
tarantool 1.7.4.18

### PR DESCRIPTION
**Pull request by bigbes**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Update head to look at 1.8 branch, since it's now official HEAD of tarantool/tarantool repository.

### CODE REVIEW

**Comment by ilovezfs** [comment]
"Adding dependency"

what does that refer to?

**Comment by bigbes** [comment]
Sorry, It's an artifact. I've added `tcl-tk` as dependency, but OSX version is enough. Should I modify commit message?

**Comment by fxcoudert** [comment]
Thanks @bigbes for the pull request! Merged after updating the commit message.

**Comment by bigbes** [comment]
Thank you @fxcoudert and @ilovezfs !

**Pull request closed without merging**
