### PR TITLE
xapian: add python3 bindings

### PR DESCRIPTION
**Pull request by klmp200**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
We probably want to make `python` (i.e. Python 3) bindings the default. And remove the ruby option, to simplify things. See #31510 for rationale behind removing options from formulas.

**Comment by fxcoudert** [comment]
Having a new formula `sphinx-doc-python3` is overkill. We should be able to build Python 3 bindings with system Python for `sphinx-doc`.

**Comment by klmp200** [comment]
I'm having a hard time with this shpinx-doc formula, that's why I created another one. I'll try to make something clean.

**Comment by klmp200** [comment]
The formula is ready, I'm waiting for you.

**Comment by fxcoudert** [comment]
The changes to `sphinx-doc` are not explained an appear unnecessary.

**Comment by fxcoudert** [comment]
We're not going to ship an outdated version of `sphinx-doc` just to build bindings that are, apparently, not actively maintained. If you can build without documentation, let's do it. Otherwise we'll simply decline the bindings.

**Comment by klmp200** [comment]
Found a way to bypass the documentation generation, no need for sphinx-doc anymore.

**Comment by klmp200** [comment]
UP

**Comment by klmp200** [comment]
Up, someone ?

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by fxcoudert** [comment]
- Adding Python bindings to a formula, not sure how useful they are to the community (they're shipped separately, so not enabled by default)
- They don't build without patching, which is not acceptable for Homebrew core.

> Xapian bindings are not compatible with Sphinx-doc >= 2.0

Has it been reported upstream? What's the current status of work towards a fix for that?

**Comment by klmp200** [comment]
It seems to have been reported and patched 4 weeks ago https://trac.xapian.org/ticket/778
I'm gonna try again with this patch

**Comment by klmp200** [comment]
The patched version works without any workaround.
Nevertheless, I had to edit the sphinx-doc formula that crashed with the `typing` dependancy. As I said in the commit message, it's supposed to be required below python3.7 and it causes crash at build time like this with python3.7 :

```
Last 15 lines from /Users/klmp200/Library/Logs/Homebrew/xapian/04.make:
  File "/usr/local/opt/sphinx-doc/libexec/lib/python3.7/site-packages/sphinx/cmd/build.py", line 22, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/opt/sphinx-doc/libexec/lib/python3.7/site-packages/sphinx/application.py", line 27, in <module>
    from sphinx.config import Config
  File "/usr/local/opt/sphinx-doc/libexec/lib/python3.7/site-packages/sphinx/config.py", line 17, in <module>
    from typing import Any, NamedTuple, Union
  File "/usr/local/opt/sphinx-doc/libexec/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/opt/sphinx-doc/libexec/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
make[3]: *** [docs/html/index.html] Error 1
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

I generated a formula with `poet` and it didn't include this dependency. It also seems to pass all tests and everything works find for what I tested.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
