### PR TITLE
raylib: fix build to install static and shared libraries

### PR DESCRIPTION
**Pull request by nawarian**
As of raylib 3.7.0, brew no longer installs the shared object library (`libraylib.dylib` on MacOS) breaking all `ffi` implementations that using it.

Here's a summary of why:

- Raylib compiles a STATIC object by default, it is no longer possible to flag it
- Raylib updated the SHARED object flag to BUILD_SHARED_LIBS
- Users must now choose between static or shared compilation

See this commit for context: https://github.com/raysan5/raylib/commit/05dfbf3cd42e63f56d978cafec63f22fd7538e9f#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4

--- 

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
> Users must now choose between static or shared compilation

It's no longer possible to have both?

**Comment by carlocab** [comment]
> It's no longer possible to have both?

We could probably build the static lib separately then install the static libraries manually, as some other formulae do. We don't want to `make install` that lest the two `make install`s stomp on each other.

**Comment by carlocab** [comment]
By the way, the important part of the commit style guide is this:

> At Homebrew, we like to put the name of the formula up front like so: `foobar 7.3 (new formula)`.

**Comment by nawarian** [comment]
I'm not sure I like the idea of building both separately and moving things around. Is this common practice? Can you provide a Formula sample that does it?

@SMillerDev it seems like it is no longer possible to compile both the static and shared lib objects as the code path became binary. I just commented on the raylib's Pull Request to fetch more info from maintainers.

**Comment by carlocab** [comment]
Many formulae do this: `fmt`, `poppler`, `double-conversion`, `opencv`, `libgit2`, `netcdf`, `folly`, `wangle`, `leveldb`...

There's probably more. Try `rg 'lib\.install.*\.a'` in your local core repo. (That does produce false positives though.)

**Comment by nawarian** [comment]
Thank you for your suggestion. I just sent a commit applying it. Testing it locally, all worked fine :)

Files are correctly placed, I can compile C programs using the static lib and run FFI with the shared lib just fine!

If you agree with it, let's merge without waiting for Raylib's response on the build set up. If they decide to change something on their side, I'll just come back here with another PR.

**Comment by carlocab** [comment]
Please squash your commits together and use the commit message format from the commit style guide.

**Comment by nawarian** [comment]
Done. Let me know if I missed something. And thank you for the fast replies, much appreciated :)

**Review by SMillerDev — APPROVED** [review]
Thanks @nawarian  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by nawarian** [comment]
Thank you all for the collaboration. I'm positively surprised by the quality and speed this project has. You all can be proud of what you've built here! <3

See you next time 👋

**Pull request closed without merging**
