### PR TITLE
libevent 2.1.11

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
Blocked until #42770 and #42772 are merged.

**Comment by Moisan** [comment]
Only need to rebase on top of master now and you should be good to go.

**Comment by alebcay** [comment]
```
==> brew install --only-dependencies knot

==> FAILED
==> Installing dependencies for knot: unbound
==> Installing knot dependency: unbound
==> Downloading https://homebrew.bintray.com/bottles/unbound-1.9.2_1.high_sierra.bottle.tar.gz
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "unbound"
Download failed: https://homebrew.bintray.com/bottles/unbound-1.9.2_1.high_sierra.bottle.tar.gz
```

**Comment by alebcay** [comment]
Finally all green. 💯

**Pull request closed without merging**
