### PR TITLE
vim: use system perl on macOS

### PR DESCRIPTION
**Pull request by ryenus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

At this point all my locally installed formulae use system perl on macOS, with vim being the only exception. This saves people like me from having two perl installations.

### CODE REVIEW

**Comment by iMichka** [comment]
We did not make that change in 2021: https://github.com/Homebrew/homebrew-core/pull/88499
Wondering if we should reconsider this.

**Comment by p-linnane** [comment]
Seems fine. There's no linkage with `zlib` though. Do we really need that line?

**Comment by stefanb** [comment]
@p-linnane there was a warning:
image

**Comment by p-linnane** [comment]
> @p-linnane there was a warning

Looks like that is for `ttyd`. It's showing up in the "Unchanged files with check annotations" section.

**Review by p-linnane — APPROVED** [review]

**Review by nandahkrishna — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request merged**
