### PR TITLE
aws-sns-cli: delete

### PR DESCRIPTION
**Pull request by cmckni3**
aws cli provides this functionality

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is this tool just duplicate or actually deprecated? Because both MySQL and MariaDB provide an SQL server. Doesn't mean we need to get rid of one.

**Comment by issyl0** [comment]
This formula has had [54 macOS installs over the past 90 days](https://formulae.brew.sh/formula/aws-sns-cli), 👍 for removal as its functionality is provided by a more widely known formula which is [documented by Amazon](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-sns.html).

**Comment by cmckni3** [comment]
@issyl0 correct.

The link in the formula does not work anymore either. Pretty sure the functionality was baked into aws cli a long time ago.

**Comment by MikeMcQuaid** [comment]
> This formula has had [54 macOS installs over the past 90 days](https://formulae.brew.sh/formula/aws-sns-cli)

Unless this number was zero or this formula is actually broken: I think it should stay.

**Pull request closed without merging**
