### PR TITLE
notmuch: allow building with any non-Homebrew emacs

### PR DESCRIPTION
**Pull request by DivineDominion**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I'm terribly sorry, but I don't really understand the use of options according the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook) and the audit warnings. Is forbidding options too recent to be reflected in the cookbook?

What this PR is basically attempting to achieve is to install the `notmuch` tool and its Elisp files without forcing installation of homebrew Emacs. There's e.g. `emacs-head` formula or other reasons to have emacs built from source outside of Homebrew. As long as `emacs` is in PATH, `notmuch` installation will work. I wanted to reflect that.

Especially on Linux, I think people that care for Emacs at all will have Emacs installed in their favorite flavor already and don't want a homebrew'd copy just to check out HEAD here.

(Please note that the `notmuch` installation also offers an option to skip Elisp files completely. I wanted to add an option to reflect this as well, but since the use of options in formula isn't clear to me, I didn't add that in.)

### CODE REVIEW

**Comment by nandahkrishna** [comment]
> I'm terribly sorry, but I don't really understand the use of options according the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook) and the audit warnings. Is forbidding options too recent to be reflected in the cookbook?

https://docs.brew.sh/Formula-Cookbook#adding-optional-steps mentions right below the subsection heading that options aren't allowed in homebrew-core as they aren't tested in CI. I think this has been the case for quite a few years now.

**Comment by nandahkrishna** [comment]
> What this PR is basically attempting to achieve is to install the `notmuch` tool and its Elisp files without forcing installation of homebrew Emacs.

Currently, `emacs` will not be installed if installing `notmuch` from the bottle. Building from source is not supported, so if you wish to build `notmuch` with your preferred version of `emacs`, you should probably have your own version of the `notmuch` formula in a Tap (note that you may include options for formulae in a personal Tap, but these aren't tested and binary packages cannot be built for them).

**Comment by carlocab** [comment]
While we're looking at `notmuch`, I think this workaround

https://github.com/Homebrew/homebrew-core/blob/955b98f4c158560cf4470e4d73ae0333339441b0/Formula/notmuch.rb#L62-L74

might no longer be needed now that we do

https://github.com/Homebrew/homebrew-core/blob/955b98f4c158560cf4470e4d73ae0333339441b0/Formula/python%403.9.rb#L151

in `python@3.9`. @DomT4, can I interest you in taking a look at this? 😄

----

As for the change here, I'm open to considering scoping the `emacs` build dependency to a `stable` block so that it's not required when building `HEAD`. This will almost certainly skip the installation of `emacs` bindings whenever you have a Homebrew-installed `emacs`, though.

**Comment by DivineDominion** [comment]
@nandahkrishna Thanks for the clarification! Didn't notice that part, it seems. Have to look up how to maintain a personal tap :)

@carlocab I didn't understand the effect of the change immediately and looked into `stable` vs `head` in other formulae. I'm not sure that this would model either my intended effect or the original.

Original:

- Bottle: Download release and copy files; no need for emacs or any compilation tool
- HEAD: Download source and make sure files needed for compilation of e.g. `.el` files to `.elc` (emacs) are installed via homebrew

My intention

- Bottle: Download release and copy files; no need for emacs or any compilation tool
- HEAD: Download source and make sure files needed for compilation of e.g. `.el` files to `.elc` (emacs) are installed ~via homebrew~ _anywhere on the system_

Skipping `emacs` dependency in `stable` sounds like it wouldn't help with the HEAD situation, but since the original line was

    depends_on "emacs" => :build

i.e. for building from source, your proposed change wouldn't change much, would it?

**Comment by carlocab** [comment]
Not sure what you mean by my proposed change not changing much. My proposed change would allow you to `brew install --HEAD notmuch` without actually having installed `emacs` from Homebrew/core. Note that I didn't propose "[s]kipping `emacs` dependency in `stable`".

**Comment by DivineDominion** [comment]
Closing this since I'm seeming to hold the tool wrong w.r.t. options etc.. Thanks everyone for the feedback.

**Pull request closed without merging**
