### PR TITLE
docker-compose 1.8.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yurikoles** [comment]
```pkg_resources.DistributionNotFound: The 'docker-py<2.0,>=1.9.0' distribution was not found and is required by docker-compose```

**Comment by ushuz** [comment]
Should update `docker-py` resource to `1.9.0`, maybe other resources need to be updated as well.

**Comment by DomT4** [comment]
I sensed some growing impatience for people to play with this release, so pulled it as part of https://github.com/Homebrew/homebrew-core/pull/3486. I kept your commit credit @ilovezfs, fear not 😉.

**Comment by ilovezfs** [comment]
@DomT4 thanks for pulling this.

**Pull request closed without merging**
