### PR TITLE
nginx 1.10.0

### PR DESCRIPTION
**Pull request by uraimo**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

Updated the stable version of Nginx to 1.10.0

### CODE REVIEW

**Comment by uraimo** [comment]
`devel version 1.9.14 is older than stable version 1.10.0`

Yep, correct, but there is no 1.11.x version yet. Also, no local check (e.g. with brew audit) identified this error, but i think it's ok this way.

**Comment by UniqMartin** [comment]
> Yep, correct, but there is no 1.11.x version yet. Also, no local check (e.g. with brew audit) identified this error, but i think it's ok this way.

We prefer to remove the `devel` version in this case. We can re-add it once a `1.11.x` version has been published. This also means that PR #685 isn't really needed. Please update your commit to remove the `devel do` block and make the commit subject a simple `nginx 1.10.0` (see [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md)).

**Comment by DomT4** [comment]
We should also be able to fix the convoluted `spdy` option logic hack now via a simple `deprecated_option`.

**Comment by DomT4** [comment]
```diff
diff --git a/Formula/nginx.rb b/Formula/nginx.rb
index f790461..fd2cbe2 100644
--- a/Formula/nginx.rb
+++ b/Formula/nginx.rb
@@ -23,9 +23,11 @@ class Nginx < Formula
   option "with-passenger", "Compile with support for Phusion Passenger module"
   option "with-webdav", "Compile with support for WebDAV module"
   option "with-debug", "Compile with support for debug log"
-  option "with-spdy", "Compile with support for either SPDY or HTTP/2 module"
+  option "with-http2", "Compile with support for the HTTP/2 module"
   option "with-gunzip", "Compile with support for gunzip module"
 
+  deprecated_option "with-spdy" => "with-http2"
+
   depends_on "pcre"
   depends_on "passenger" => :optional
   depends_on "openssl" => :recommended
@@ -79,17 +81,7 @@ class Nginx < Formula
     args << "--with-http_dav_module" if build.with? "webdav"
     args << "--with-debug" if build.with? "debug"
     args << "--with-http_gunzip_module" if build.with? "gunzip"
-
-    # This became "with-http_v2_module" in 1.9.5
-    # http://nginx.org/en/docs/http/ngx_http_spdy_module.html
-    # We handle devel/stable block variable options badly, so this installs
-    # the expected module rather than fatally bailing out of configure.
-    # The option should be deprecated to the new name when stable.
-    if build.devel? || build.head? && build.with?("spdy")
-      args << "--with-http_v2_module"
-    elsif build.with?("spdy")
-      args << "--with-http_spdy_module"
-    end
+    args << "--with-http_v2_module" if build.with? "http2"
 
     if build.head?
       system "./auto/configure", *args
```
Something similar to that.

**Comment by uraimo** [comment]
@DomT4 i was thinking about something like this (replacing the old stuff where needed):

```
option "with-http2", "Compile with support for HTTP/2 module"

deprecated_option "with-spdy" => "with-http2"

args << "--with-http_v2_module" if build.with? "http2"
```

Did you mean something similar?

**Comment by uraimo** [comment]
Ok :D so the answer is yes :D

**Comment by uraimo** [comment]
Ok, done.

**Comment by DomT4** [comment]
Looks good to me.

Merged in https://github.com/Homebrew/homebrew-core/commit/c87f6ab2588d1f81cc197d0314eabdcebab28532. Thank you for your contribution to Homebrew @uraimo; we appreciate it! :smiley_cat:

**Pull request closed without merging**
