### PR TITLE
bartycrouch 4.1.0

### PR DESCRIPTION
**Pull request by Jeehut**

### CODE REVIEW

**Comment by Jeehut** [comment]
Of course, High Sierra isn't building as Xcode 11.4 isn't available there, which is a requirement.

**Comment by Bo98** [comment]
It’s failing on Mojave because you have the requirement set to 10.4.

**Comment by Jeehut** [comment]
@Bo98 Ahh, you are right of course, I meant `11.4`. Just updated. Good catch! 👍

**Comment by SMillerDev** [comment]
Please squash your commits

**Comment by Jeehut** [comment]
@SMillerDev I've just done that, but why don't you just use the `Quash and merge` button on GitHub? See the docs [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits).

**Comment by SMillerDev** [comment]
Because that would break the formula for every homebrew user. See https://docs.brew.sh/Maintainer-Guidelines#merging-rebasing-cherry-picking

**Comment by Jeehut** [comment]
@SMillerDev I don't get it. I just did the same thing manually as that button would do. But maybe I'm wrong. Anyways, as long as you understand it and are aware of that button, all is fine. I was just curious, but it seems there are reasons for that, whatever they might be.

**Comment by SMillerDev** [comment]
The reason is the bottle block in each formula, if I press the merge button in github that will not be updated, serving the old version in the updated formula. This will break shit for all homebrew users with this formula installed that don't use the unsupported "build everything from source"-setup

**Pull request closed without merging**
