### PR TITLE
proj 6.0.0

### PR DESCRIPTION
**Pull request by yyolk**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yyolk** [comment]
gonna hack on this more during the weekend, having issues with SQLITE3 not being found / pkg-config being out of date

**Comment by yyolk** [comment]
thank you @fxcoudert - i was hacking on that locally and had `depends_on "pkg-config" => :build"` in the `head` block 🙉

**Comment by yyolk** [comment]
this works now, all things checked. the build bot seems to be stuck on some stuff (for the last 11 hours 😨) hopefully I can get a maintainer to resubmit? 

@fxcoudert can you do that? 😇

**Comment by fxcoudert** [comment]
This is going to need revision bumps on: `gdal gmt gmt@4 libgaiagraphics libgeotiff liblwgeom librasterlite libspatialite mapnik mapserver osm2pgsql pdal pgrouting points2grid postgis simple-tiles spatialite-gui spatialite-tools`.

Each formula should get a bump of its revision number, in a separate commit named `gdal: revision for proj` (for `gdal`).

**Comment by yyolk** [comment]
@fxcoudert bunch of revision bump prs open, and x-ref this issue 😁 - let me know if theres anything else!

**Comment by lembacon** [comment]
@yyolk Those revision bumps should be placed within this pull request, on a one-formula-per-commit basis, otherwise those formulae will still be built against `proj` 5.2.0.

**Comment by fxcoudert** [comment]
@yyolk as @lembacon said, revision bumps need to occur in the same pull request (but as individual commits) so everything is built, tested, and updated at the same time. Sorry if I was not clear enough :(

**Comment by yyolk** [comment]
ah. yes i was under the impression you wanted a separate pr - i'll update this branch with those formula revisions at some point today!

**Comment by yyolk** [comment]
@fxcoudert @lembacon done! please let me know if theres anything else :)

**Comment by fxcoudert** [comment]
- `libgeotiff` fails to build with:

```
08:55:22 In file included from geotiff_proj4.c:1379:
08:55:22 /usr/local/include/proj_api.h:37:2: error: 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
08:55:22 #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
```

- `liblwgeom` fails to build with:

```
09:24:27 Using user-specified proj directory: /usr/local
09:24:27 checking proj_api.h usability... no
09:24:27 checking proj_api.h presence... no
09:24:27 checking for proj_api.h... no
09:24:27 configure: error: could not find proj_api.h - you may need to specify the directory of a PROJ.4 installation using --with-projdir
```

**Comment by fxcoudert** [comment]
I have tried to update related formulas so future work can start on a good basis. But this created conflicts in this PR, which will need to be resolved and rebased on top of current master.

Regarding the formulas that are failing:
- For `libgeotiff` we may want to use this patch `https://github.com/OSGeo/libgeotiff/commit/7425a7fc.diff?full_index=1` (from upstream commit https://github.com/OSGeo/libgeotiff/commit/7425a7fc314b27efd2141191f756810c8e936edd)
- For `postgis` and `liblwgeom` we may need to use this commit: https://github.com/postgis/postgis/commit/9647fa5dbddb6a1b82ec05096517721a35c00548

**Comment by yyolk** [comment]
@fxcoudert would you like me to rebase current master onto this branch?

**Comment by fxcoudert** [comment]
@yyolk yes please, and try to apply the patches/commits listed in my comment above, too

**Comment by yyolk** [comment]
sure thing @fxcoudert i think I'll be able to get to this today

**Comment by fxcoudert** [comment]
> For postgis and liblwgeom we may need to use this commit: postgis/postgis@9647fa5

Answering my own comment: this patch is already in latest postgis (and liblwgeom)

**Comment by fxcoudert** [comment]
Thanks @yyolk I'll take it from here, but you're welcome to comment and help out on the PR at #38215

**Comment by yyolk** [comment]
woot woot thanks @fxcoudert i learned a lot from this PR so I'm happy to have helped. I'll see if I can contribute to #38215

**Comment by fxcoudert** [comment]
We welcome all possible help with the geo/proj-based formulas, which tend to be a complex web for us to navigate :)

**Pull request closed without merging**
