### PR TITLE
netlify-cli 3.7.1

### PR DESCRIPTION
**Pull request by silverskyvicto**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by silverskyvicto** [comment]
I made a mistake, so I'll close it.

**Comment by silverskyvicto** [comment]
I have followed the official procedure and it is now re-opened.

- [Submit a new version of an existing formula](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula)

**Comment by carlocab** [comment]
`netlify-cli` appears to still be broken on ARM. Previous version bump attempts: #70234, #70079, #69982

The existing ARM version also appears to be broken: #70295

It might be better to just remove the ARM bottle.

**Comment by chenrui333** [comment]
> It might be better to just remove the ARM bottle, rather than keep Intel users on an outdated version for no reason. Thoughts, @Homebrew/core?

Agree! Remove the ARM bottle for the new release, until it can be supported.

**Review by chenrui333 — APPROVED** [review]
let's remove the arm bottle and release the new version.

**Comment by carlocab** [comment]
That's simple enough to do, but what does that do to existing ARM users who have this formula installed?

That said, I can't imagine it hurts too much since their existing installation probably doesn't work anyway...

**Comment by carlocab** [comment]
Ok, if there are no objections to this by tomorrow, I intend to merge this without the ARM bottle. The current one is broken, so there's no need to withhold version updates from Intel users.

Thanks for your PR and your patience, @silverskyvicto.

**Comment by carlocab** [comment]
ARM 🍾 75a2717b7b8bb1eaeab8213f53bbec0702b37709

**Pull request closed without merging**
