### PR TITLE
mupen64plus 2.5.9

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [ ] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by osalbahr** [comment]
Pre-release https://github.com/mupen64plus/mupen64plus-core/releases/tag/2.5.9.

---

```console
$ brew bump mupen64plus
==> mupen64plus
Current formula version:  2.5
Latest livecheck version: 2.5
Latest Repology version:  2.5.9
Open pull requests:       mupen64plus 2.5.9 (https://github.com/Homebrew/homebrew-core/pull/138612)
Closed pull requests:     none
```

**Comment by chenrui333** [comment]
relates to https://github.com/mupen64plus/mupen64plus-core/issues/973

**Comment by chenrui333** [comment]
once upstream sorted it out, we can revisit this.

**Comment by chenrui333** [comment]
#177843

**Pull request closed without merging**
