### PR TITLE
thors-serializer: drop GCC dependency

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
There is a unit test failure here I don't really understand:
```
EscapeControlTest.cpp:195: Failure
  Expected: (find) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
  [  FAILED  ] EscapeControlTest.BsonOutputContainsTab (0 ms)
  [ RUN      ] EscapeControlTest.BsonOutputContainsBS
  EscapeControlTest.cpp:212: Failure
  Expected: (find) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
  [  FAILED  ] EscapeControlTest.BsonOutputContainsBS (0 ms)
  [ RUN      ] EscapeControlTest.BsonOutputContainsNL
  EscapeControlTest.cpp:229: Failure
  Expected: (find) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
  [  FAILED  ] EscapeControlTest.BsonOutputContainsNL (0 ms)
  [ RUN      ] EscapeControlTest.BsonOutputContainsFF
  EscapeControlTest.cpp:246: Failure
  Expected: (find) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
  [  FAILED  ] EscapeControlTest.BsonOutputContainsFF (0 ms)
  [ RUN      ] EscapeControlTest.BsonOutputContainsCR
  EscapeControlTest.cpp:263: Failure
  Expected: (find) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
  [  FAILED  ] EscapeControlTest.BsonOutputContainsCR (0 ms)
```

**Comment by danielnachun** [comment]
@Loki-Astari could you provide us any insight into why this unit test is now failing on Linux when it apparently didn't before?  The only change made in this PR was to switch from using the GCC formula to the host GCC, but that would only be expected to affect the compilation, which worked fine.

**Comment by Loki-Astari** [comment]
Sorry. Just read the e-mail.
Let me have a look.

**Comment by Loki-Astari** [comment]
Looks like badly written code my end.
The test relies seem to rely on `std::stringstream` internal buffer being contiguous and maintained after `begin()` returns.

I will fix and submit a fix tonight.

**Comment by Loki-Astari** [comment]
OK I have a fix.
Should I submit the standard way? Or is there a way I can test it against these systems here before submitting?

**Comment by Loki-Astari** [comment]
https://github.com/Homebrew/homebrew-core/pull/110720

**Comment by danielnachun** [comment]
Resolved in https://github.com/Homebrew/homebrew-core/pull/110742.

**Pull request closed without merging**
