### PR TITLE
r 3.5.0

### PR DESCRIPTION
**Pull request by luispuerto**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by luisspuerto** [comment]
I don't understand why it has failed... I just installed it perfectly on my Mac. 
screen shot 2018-04-23 at 10 49 49

**Comment by SMillerDev** [comment]
It can't find the dependency https://cloud.r-project.org/src/contrib/gss_2.1-7.tar.gz (and neither can I locally)

**Comment by luisspuerto** [comment]
I was just about to say that there is a 2.1-8 version in `https://cloud.r-project.org/src/contrib/gss_2.1-8.tar.gz`

Thanks @SMillerDev

**Comment by luisspuerto** [comment]
I guess that it's just a bottle problem. 😃

**Comment by SMillerDev** [comment]
Nah, you'll have the same issue if you do reinstall I guess. Can you add that version bump to the commit?

**Comment by luisspuerto** [comment]
Done... let's see if now works :)

**Comment by luisspuerto** [comment]
now it works... 

Thanks for pointing out the problem @SMillerDev

**Review by SMillerDev — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @luisspuerto and @SMillerDev !

**Pull request closed without merging**
