### PR TITLE
Cake 0.16.1

### PR DESCRIPTION
**Pull request by gep13**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by gep13** [comment]
As per previous PR's for Cake, we are not in a position to run the final two steps. Please let us know if this causes a problem.

**Comment by zmwangx** [comment]
Merged as 315001c. Thank you for your contribution to Homebrew! For future reference, our preferred format of commit subject is `foo 1.2.3` (note the lowercase). Maybe you haven't [changed your release process documention](https://github.com/Homebrew/homebrew-core/pull/4857#issuecomment-247477461) or release script yet? (Just a gentle nudge.)

**Comment by gep13** [comment]
@zmwangx ah, I wasn't aware of the comment made on @patriksvensson PR from last release.  I will update our documentation just now.

Thanks!

**Comment by gep13** [comment]
@zmwangx Done.  Should be done this way going forward.

**Comment by zmwangx** [comment]
👍

**Pull request merged**
