### PR TITLE
libxcb: drop `libpthread-stubs`

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Upstream commit: https://gitlab.freedesktop.org/xorg/lib/libxcb/-/commit/d53ad60d774176c5b057e2ed4d03a4658ee13690

### CODE REVIEW

**Comment by fxcoudert** [comment]
Is the patch from upstream? Has it been proposed to upstream?

**Review by fxcoudert — DISMISSED** [review]

**Comment by fxcoudert** [comment]
OK then, but not revision.

**Comment by fxcoudert** [comment]
I do not see why the pkg-config change would require a revision. What will be broken without a revision?

**Comment by fxcoudert** [comment]
`suil` has:
```
Undeclared dependencies with linkage:
    gtk+
```

`gecode` has:
```
Undeclared dependencies with linkage:
    mpfr
```

**Comment by chenrui333** [comment]
do we want to give this PR another go?

**Comment by p-linnane** [comment]
Should be fine since they worked on all the other versions. Just waiting on Linux.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
