### PR TITLE
liquigraph 4.0.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Looks like failure seen on OpenJDK 16+.
Perhaps changing runtime JDK to `openjdk@11` will fix issue.

**Comment by chenrui333** [comment]
> Looks like failure seen on OpenJDK 16+.
> Perhaps changing runtime JDK to `openjdk@11` will fix issue.

Sounds about right!
related maven config, https://github.com/liquibase/liquigraph/blob/4.x/pom.xml#L23-L24

**Comment by chenrui333** [comment]
```
  "Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
  WARNING: 
  An illegal reflective access operation has occurred
  WARNING: Illegal reflective access by com.beust.jcommander.Parameterized (file:/opt/homebrew/Cellar/liquigraph/4.0.3/libexec/liquigraph-cli.jar) to method java.util.function.Consumer.lambda$andThen$0(java.util.function.Consumer,java.lang.Object)
  WARNING: Please consider reporting this to the maintainers of com.beust.jcommander.Parameterized
  WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
  WARNING: All illegal access operations will be denied in a future release
  Exception in thread \"main\" com.beust.jcommander.MissingCommandException: Expected a command, got -c
  \tat com.beust.jcommander.JCommander.parseValues(JCommander.java:788)
  \tat com.beust.jcommander.JCommander.parse(JCommander.java:356)
  \tat com.beust.jcommander.JCommander.parse(JCommander.java:335)
  \tat org.liquigraph.cli.LiquigraphCommandRegistry.resolve(LiquigraphCommandRegistry.java:58)
  \tat org.liquigraph.cli.LiquigraphCli.execute(LiquigraphCli.java:46)
  \tat org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:40)
  ".
```

**Comment by cho-m** [comment]
Could be due to the `run`/`dry-run` commands mentioned in release notes: https://github.com/liquibase/liquigraph/releases/tag/liquigraph-4.0.3

**Comment by SMillerDev** [comment]
```patch
- output = shell_output("#{bin}/liquigraph -c #{changelog.realpath} -g #{jdbc} 2>&1", 1)
+ output = shell_output("#{bin}/liquigraph run --changelog #{changelog.realpath} --graph-db-uri #{jdbc} 2>&1", 1)
```

**Comment by chenrui333** [comment]
Good find, I think that is the case.

**Comment by chenrui333** [comment]
Raised the `illegal reflective access` issue in the upstream and closing the PR for now.

**Comment by fbiville** [comment]
As I commented in https://github.com/liquibase/liquigraph/issues/438, these `illegal reflective access` are just a consequence of the introduction of Java modules in Java 9 and module encapsulation that some third-party libraries do not adhere to yet, this should not be a blocker. The main change was already identified in the thread: subcommands must be explicitly identified.

Could we reopen this PR?

**Comment by chenrui333** [comment]
Yes, I am reviving this PR now.

**Comment by cho-m** [comment]
`Exception in thread \"main\" com.beust.jcommander.ParameterException: The following option is required: [--dry-run-output-directory | -d | --output-directory]`

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
