### PR TITLE
netcdf 4.9.0

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Fortran resource needs updating

**Comment by SMillerDev** [comment]
```
   duplicate symbol '_NCJnew' in:
      CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o
      ../liblib/libnetcdf.a(ncjson.c.o)
  duplicate symbol '_NCJcvt' in:
      CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o
      ../liblib/libnetcdf.a(ncjson.c.o)
  duplicate symbol '_NCJdictget' in:
      CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o
      ../liblib/libnetcdf.a(ncjson.c.o)
  duplicate symbol '_NCJnewstringn' in:
      CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o
      ../liblib/libnetcdf.a(ncjson.c.o)
  duplicate symbol '_NCJreclaim' in:
      CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o
      ../liblib/libnetcdf.a(ncjson.c.o)
  duplicate symbol '_NCJnewstring' in:
      CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o
      ../liblib/libnetcdf.a(ncjson.c.o)
  duplicate symbol '_NCJparse' in:
      CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o
      ../liblib/libnetcdf.a(ncjson.c.o)
  ld: 7 duplicate symbols for architecture arm64
```

**Comment by carlocab** [comment]
No clue about the build error, but it looks like we've been really bad at keeping these resources updated. It may be better to ship them as separate formulae.

**Comment by carlocab** [comment]
Will introduce a merge conflict at #106755.

**Comment by jonchang** [comment]
Merged in https://github.com/Homebrew/homebrew-core/pull/112159.

**Comment by carlocab** [comment]
Thanks @jonchang!

**Pull request closed without merging**
