### PR TITLE
flux 0.139.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
# github.com/influxdata/flux/libflux/go/libflux
/home/linuxbrew/.cache/Homebrew/go_cache/pkgconfig/linux_amd64/lib/libflux-249527fc6acb4e9c7e1ae86be325fff60b8fcf5891280d1b1988b3d8c11395d6.a(std-d9afe58aec724292.std.fc180862-cgu.4.rcgu.o): In function `std::f32::_$LT$impl$u20$f32$GT$::lerp::h54ca618b0a1b1fa1':
std.fc180862-cgu.4:(.text._ZN3std3f3221_$LT$impl$u20$f32$GT$4lerp17h54ca618b0a1b1fa1E+0x20): undefined reference to `fmaf'
/home/linuxbrew/.cache/Homebrew/go_cache/pkgconfig/linux_amd64/lib/libflux-249527fc6acb4e9c7e1ae86be325fff60b8fcf5891280d1b1988b3d8c11395d6.a(std-d9afe58aec724292.std.fc180862-cgu.4.rcgu.o): In function `std::f64::_$LT$impl$u20$f64$GT$::lerp::h0ff7a470044adf56':
std.fc180862-cgu.4:(.text._ZN3std3f6421_$LT$impl$u20$f64$GT$4lerp17h0ff7a470044adf56E+0x22): undefined reference to `fma'
collect2: error: ld returned 1 exit status
Makefile:75: recipe for target 'build' failed
```

**Comment by chenrui333** [comment]
cc @Homebrew/linux

**Comment by iMichka** [comment]
Maybe try to build with gcc instead of gcc5?

**Comment by EricFromCanada** [comment]
Still failing with clang; a [similar issue](https://github.com/rustls/rustls-ffi/issues/133) suggests a problem with rust 1.55 and libmath.

**Comment by chenrui333** [comment]
Superseded by #90714

**Pull request closed without merging**
