### PR TITLE
gollum 0.4.3

### PR DESCRIPTION
**Pull request by ilovezfs**
use upstream vendor support

### CODE REVIEW

**Comment by DomT4** [comment]
👍 whenever you're happy with the resource situation.

**Comment by DomT4** [comment]
It looks like upstream introduced vendor support with this release, so you might actually be able to kill most/all of the resources.

**Comment by ilovezfs** [comment]
@DomT4 Refreshed PR to use upstream's vendor support.

**Comment by DomT4** [comment]
Looks so much nicer this way ❤️. LGTM 👍.

**Comment by ilovezfs** [comment]
@DomT4 I wish they would all do this!

**Comment by DomT4** [comment]
In time, hopefully.

**Pull request closed without merging**
