### PR TITLE
detected version of papilo is wrong

### PR DESCRIPTION
**Pull request by jurgen-lentz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is there no direct download for papilo?

**Comment by jurgen-lentz** [comment]
Here https://github.com/scipopt/papilo. But it does not pass through the CI because of too few stars etc.

**Comment by jurgen-lentz** [comment]
> Is there no direct download for papilo?

Here https://github.com/scipopt/papilo. But it does not pass through the CI because of too few stars etc.

**Comment by SMillerDev** [comment]
If that's the same project but a different source that audit won't trigger.

**Comment by jurgen-lentz** [comment]
Error ```* stable version should not decrease (from 8.0.3 to 2.1.2)```. How can I solve this? 8.0.3 was detected wrongly

**Comment by jurgen-lentz** [comment]
Ready to be merged. ☺️

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
