### PR TITLE
caddy 0.9.5

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
still no vendoring :sob:

**Comment by zmwangx** [comment]
On it.

**Comment by zmwangx** [comment]
The word on vendoring is https://github.com/mholt/caddy/issues/200#issuecomment-164170670. caddy is kind of a pain because addons need to be included at compile time, and they have a build server in order to serve the gazillions of combinations you can download on https://caddyserver.com/download. I guess it'd be a lot of work to have vendored dependencies work on their server.

**Comment by ilovezfs** [comment]
Looks like it's right around the corner for the last two years. lol

**Comment by zmwangx** [comment]
It will come in the year of the Linux desktop.

**Comment by ilovezfs** [comment]
:unicorn:

**Comment by mholt** [comment]
Huy guyz, look ^

**Comment by ilovezfs** [comment]
@mholt hurray!!!!

**Pull request closed without merging**
