### PR TITLE
erlang 24.1.6

### PR DESCRIPTION
**Pull request by alaadahmed**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by alaadahmed** [comment]
Please relax CI / Github actions checks 🙂

**Comment by alaadahmed** [comment]
any ideas why did this happen?

**Comment by carlocab** [comment]
No idea, unfortunately. You can try building `lfe` from source to see if you can reproduce the error locally.

**Comment by alaadahmed** [comment]
I installed `lfe` successfully on my mac Big Sur with erlang 24.1.5 already installed, I installed `lfe` from source using `make compile` -> `make install` and everything is fine! Should we try again rechecks here?!

Screen Shot 2021-11-19 at 12 47 48

**Comment by alaadahmed** [comment]
OK I think I know the issue, I removed installed `lfe` that I installed using `make install` and tried to reinstall it using `brew install --build-from-source lfe` as shown in `test (11)` action, and it failed because there were some files still symlinked some where and `brew` couldn't remove them so when I removed them or when you use `brew link --overwrite lfe` it worked, so I think in the `attempt #2` it seems there were some links point to old installed `lfe` that prevented the checks to complete due to brew errors. Is this something happen in `Github Actions`?

__screenshot from failed `test (11)`__
Screen Shot 2021-11-19 at 13 11 42

**Comment by carlocab** [comment]
Thanks for investigating. Let's run it again and hope it goes away.

**Comment by alaadahmed** [comment]
Nice, it passed all checks, waiting for approval 👍🏻

**Review by carlocab — APPROVED** [review]
Thanks, @alaadahmed!

**Pull request closed without merging**
