### PR TITLE
prestodb 0.270

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]

**Comment by cho-m** [comment]
May want to check if Python 2 comment still applies. Related to #93940
```rb
  depends_on :macos # Seems to require Python2
```

**Comment by cho-m** [comment]
Need to rebase since #95408 was merged with Python 2 -> 3 migration

**Comment by Porkepix** [comment]
This should be done manually, or GitHub have a rebase feature only usable by members, like GitLab can offers in their MR?

**Comment by carlocab** [comment]
> This should be done manually, or GitHub have a rebase feature only usable by members, like GitLab can offers in their MR?

I think it needs to be done manually, unfortunately.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
