### PR TITLE
arangodb 3.6.1

### PR DESCRIPTION
**Pull request by KVS85**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by KVS85** [comment]
Seems that after Jenkins was restarted something went wrong:
```16:42:37 *** Please tell me who you are.
16:42:37 
16:42:37 Run
16:42:37 
16:42:37   git config --global user.email "you@example.com"
16:42:37   git config --global user.name "Your Name"
16:42:37 
16:42:37 to set your account's default identity.
16:42:37 Omit --global to set the identity only in this repository.
16:42:37 
16:42:37 fatal: unable to auto-detect email address (got 'brew@HighSierra.(none)')
```

It's not related to any changes in this PR.

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by chenrui333** [comment]
```
20:32:14 ==> make deps
20:32:14 /usr/local/opt/docker/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
20:32:14 See '/usr/local/opt/docker/bin/docker run --help'.
20:32:14 make[1]: *** [/private/tmp/arangodb--starter-20200131-73296-1kedvn2/.gobuild] Error 125
20:32:14 make: *** [deps] Error 2
```

**Comment by KVS85** [comment]
> ```
> 20:32:14 ==> make deps
> 20:32:14 /usr/local/opt/docker/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
> 20:32:14 See '/usr/local/opt/docker/bin/docker run --help'.
> 20:32:14 make[1]: *** [/private/tmp/arangodb--starter-20200131-73296-1kedvn2/.gobuild] Error 125
> 20:32:14 make: *** [deps] Error 2
> ```

We need dockerd to be running and has `docker` as dependency. It works for us locally.

**Comment by KVS85** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Why does it need docker running?

**Comment by KVS85** [comment]
> Why does it need docker running?

For go-1.13 there is no possibility to build it without docker due to local limitations (in 1.13 they disabled local deps). We need go-1.13 to add feature to dependent component.

**Comment by SMillerDev** [comment]
We have go 1.13 bottled. I'm pretty sure it builds without docker running.

**Comment by KVS85** [comment]
@SMillerDev the developer of arangodb binary claimed the following:
```
This release is not fully moved to `go mod` (it still use linking like for 1.12 and some dependencies are not ready for 1.13).
In docker we can mount directories in specific places, so we can build this for 1.13 with workaround.
```

**Comment by SMillerDev** [comment]
So it hacks around a depreciation from at least a year ago by building in docker which doesn't work for macOS? I think we'll have to wait until it actually compiles with the latest go before we allow it in homebrew.

**Comment by ajanikow** [comment]
Hello!

This release is not fully moved to `go mod` (it still use linking like for 1.12 and some dependencies are not ready for 1.13).

In docker we can mount directories in specific places, so we can build this for 1.13 with workaround.

Best Regards,
Adam Janikowski.

**Comment by KVS85** [comment]
@SMillerDev can we please have prebuilt arangodb dependant resource this time? We can't change it's version till next ArangoDB release. That is the same binary we use in all our distributions.

**Comment by SMillerDev** [comment]
The rules of homebrew don't change because some other project didn't migrate something. You either make it build from source or someone else does but homebrew will not ship upstream's binaries.

**Comment by KVS85** [comment]
@SMillerDev OK. We can't have 3.6.1 without proper Starter version so I'll close this PR.

**Pull request closed without merging**
