### PR TITLE
node 9.6.1

### PR DESCRIPTION
**Pull request by chrmoritz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Heads up on a potential imminent 9.6.1: https://github.com/nodejs/node/pull/18946

**Comment by DomT4** [comment]
And landed.

```
url "https://nodejs.org/dist/v9.6.1/node-v9.6.1.tar.xz"
sha256 "b84c024d97b3f09ab55e352f91e038066afb44f8c49d13fdc298ffd8383d1112"
```

**Comment by chrmoritz** [comment]
Updated to the new 9.6.1 release.

thx @DomT4

**Comment by ilovezfs** [comment]
Thanks @chrmoritz!

**Pull request closed without merging**
