### PR TITLE
rav1e: Add option for building the HEAD of git

### PR DESCRIPTION
**Pull request by Mushroom**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Currently only the v4.0.0-alpha in git builds successfully for rav1e on M1 macs, as opposed to the v0.3.4 version the recipe pulls currently.

This pull request adds a `--HEAD` argument so that it can be successfully built on such a machine.

### CODE REVIEW

**Comment by bayandin** [comment]
You need to add `head "https://github.com/xiph/rav1e.git"` after `license`, instead of creating explicit `stable` and `head` blocks.

**Comment by Mushroom** [comment]
Agh, my bad, I based it on the rust formula, but I see that does things differently as it has to pull in cargo also - will update it now

**Review by bayandin — APPROVED** [review]

**Comment by bayandin** [comment]
Thanks @Mushroom 🎉

**Comment by Mushroom** [comment]
> Thanks @Mushroom 🎉

No problem, thanks for the quick review and merge!

**Pull request merged**
