### PR TITLE
Add Sake formula

### PR DESCRIPTION
**Pull request by pepicrft**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by pepibumur** [comment]
@ilovezfs I've simplified the formula as you suggested on [this PR](https://github.com/Homebrew/homebrew-core/pull/22644). Feel free to close that one and continue the discussion on this PR.

**Comment by fxcoudert** [comment]
From @ilovezfs' original review:

> As it stands there's far too much logic in the def install section that should not be maintained by us in the formula but should be maintained by upstream in its install scripts or Makefiles.

Something really needs to be done about this before we can consider this formula.

**Comment by pepibumur** [comment]
Hi @fxcoudert.
I did some cleanup and extracted some logic into scripts on the repository. However, there's a part that is still part of the formula install method. Which is the logic that takes the list of libraries that need to be copied and the binary, and copies them. Should I extract all that logic as well?

**Comment by fxcoudert** [comment]
@pepibumur yes please. We do not want to maintain build or install logic inside the formula. These should be provided (by makefiles, cmake, or other build scripts) in each project.

I'm going to close for now, but we can reopen once a version is out that has an installation script.

Thanks again for your contribution!

**Pull request closed without merging**
