### PR TITLE
clingo 5.4.1

### LINKED ISSUE #65792: problems with clingo formula
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

There seem to be some issues with the clingo formula on homebrew. This can be seen inspecting the log of:
```
brew reinstall --build-from-source --verbose --debug clingo
```

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
...
CMake Warning:
  Manually-specified variables were not used by the project:
    PYTHON_EXECUTABLE
...
-- Install configuration: "Release"
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/lpconvert
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/clasp
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.3.0.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.3.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/include/clingo.hh
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/include/clingo.h
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoTargets.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoTargets-release.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoConfig.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoConfigVersion.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.1.0.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.1.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/reify
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/gringo
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/clingo
-- Installing: /private/tmp/clingo-20201127-59348-gq8suv/clingo-5.4.0/.brew_home/Library/Python/3.9/lib/python/site-packages/clingo.cpython-39-darwin.so
...
  </pre>
</details>

## What you expected to happen

There are two problems.

First, there is the message that the variable `PYTHON_EXECUTABLE` is unused. If available, clingo uses cmake's `FindPython` module, which no longer uses this variable `PYTHON_EXECUTABLE`. It should be possible to fix this by using the variable `Python_EXECUTABLE`, instead.

The second bigger problem is that the clingo Python module is installed in the wrong location. I do not know where such a module should be installed, so I cannot tell how to fix this. In any case it is possible to specify the installation path using the `PYCLINGO_INSTALL_DIR` varibale.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew reinstall --build-from-source --verbose --debug clingo
```

### PR DESCRIPTION
**Pull request by trws**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR builds on top of #66362, and should be considered (and rebased) after that merges.  The patch removal and test update from that PR are necessary for the head version to build and test successfully.

It also fixes #65792 by fixing the cmake arguments to use the correct python variable and install the python extension to a loadable location.

@rkaminsk, would you be willing to take this for a test-drive and make sure it solves the issue you were reporting?

### CODE REVIEW

**Comment by rkaminsk** [comment]
Looks good. Running `import clingo` from Python works now.

PS: Sorry, it seems like I forgot to update the revision number for the last release.

**Comment by chenrui333** [comment]
test failure with hyperkit

**Comment by trws** [comment]
Does that mean this is going to end up blocked on the hyper kit failures from python 3.9 noted in #66450?

**Comment by chenrui333** [comment]
yeah, we should do the merge (I actually could not built hyperkit against master branch), let's see how it goes with the rerun.

**Comment by chenrui333** [comment]
lgtm for the rerun.

**Comment by trws** [comment]
Thanks for that @chenrui333.  Anything I should do at this point to help get it finished up?

**Comment by chenrui333** [comment]
not really, merging the PR now. Thanks!

**Pull request closed without merging**
