### PR TITLE
icu4c 59.1

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by JCount** [comment]
🤞

**Comment by chrmoritz** [comment]
This will likely break the atm [optional dependency of the V8 formula to be build with system-icu](https://github.com/Homebrew/homebrew-core/blob/master/Formula/v8.rb#L25).
If I remember correctly node ran into issues with upgrading icu to 59.1 for node8 and had to update to a more recent V8 version to resolve these issues. 

Our quite outdated v8 5.1 formula should be affected by the same issue and we should consider removing said option from the v8 formula after merging this, if we can reproduce it (I'm currently testing it).

Note: Our versioned node@6/4 formulae are not affected by this, because they statically link to a vendored version of icu58.2.

**Comment by ilovezfs** [comment]
@chrmoritz the option is used in less than 1% of v8 installs, and we don't need to rebuild the bottle, so a follow-up PR is probably best.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/commit/1c6a390c39f7b7cf837e31c6e07f0fca972953eb.

**Pull request closed without merging**
