### PR TITLE
rebar3: rename from rebar@3

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
`rebar3` is the current "erlang build tool", `rebar` is deprecated and the repo has been archived.

Upstream call it `rebar3` and it's packaged by others as `rebar3`. 

https://github.com/erlang/rebar3
https://github.com/rebar/rebar

http://www.rebar3.org/docs/from-rebar-2x-to-rebar3

https://repology.org/metapackage/rebar3/versions
https://repology.org/metapackage/rebar/versions

### CODE REVIEW

**Comment by DomT4** [comment]
Is it worth considering deleting `rebar` entirely and giving this formula its name? I noticed looking at the analytics data that `rebar` is doing an average of less than 4 installs a day compared to a healthier number for `rebar@3`.

**Comment by commitay** [comment]
Maybe but renaming this to `rebar` would make us inconsistent with upstream and the majority of the other packagers. 

On the other hand:
```
$ rebar3 --version
rebar 3.6.1 on Erlang/OTP 21 Erts 10.0.5
```

I don't really have a strong opinion on what we should actually call it, just wanted to change it so the current stable wasn't a versioned formula. 🙃

**Comment by DomT4** [comment]
I don't have an objection to this personally, I agree we're essentially using the wrong "branding" on this based on the upstream documentation; It looks more like a `perl6`/`perl` situation than it does an `erlang`/`erlang@19` situation.

**Comment by commitay** [comment]
I'll merge this in a few hours.

**Review by DomT4 — APPROVED** [review]

**Pull request closed without merging**
