### PR TITLE
gcc 11.3.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Seeing if things are going well on Intel. I will have to decide whether an ARM rebase is needed, so do not merge for now.

### CODE REVIEW

**Comment by Bo98** [comment]
The patch further down also needs removing.

**Comment by fxcoudert** [comment]
After considering the issue, given that GCC 12 release is approaching, I will not make a rebase of the 11 branch on ARM.

**Comment by fxcoudert** [comment]
On linux:

```
Warning: 6 failed steps ignored!
brew linkage --cached --test --strict diesel
brew linkage --cached --test --strict gdal
brew linkage --cached --test --strict hydra
brew linkage --cached --test --strict kitchen-sync
brew linkage --cached --test --strict libzdb
brew linkage --cached --test --strict stellar-core
Error: 4 failed steps!
brew test --retry --verbose gst-libav
brew test --retry --verbose jetty
brew test --retry --verbose root
brew test --retry --verbose yle-dl
```

On 11-arm64 (which should be unchanged) a weird build error in `libgccjit`:

```
echo "@set BUGURL @uref{https://github.com/Homebrew/homebrew-core/issues}" >> gcc-vers.texiT; \
  	mv -f gcc-vers.texiT gcc-vers.texi
  ../../gcc/jit/docs/_build/texinfo/libgccjit.texi:1183: warning: @image file `libgccjit-figures/sum-of-squares1.txt' (for text) unreadable: No such file or directory.
  ../../gcc/jit/docs/_build/texinfo/libgccjit.texi:1532: warning: @image file `libgccjit-figures/sum-of-squares1.txt' (for text) unreadable: No such file or directory.
  perl ../../gcc/../contrib/texi2pod.pl ../../gcc/doc/include/gpl_v3.texi > gpl.pod
  ../../gcc/jit/docs/_build/texinfo/libgccjit.texi:2728: warning: @image file `libgccjit-figures/factorial1.txt/usr/share/locale/en_US.UTF-8/LC_MESSAGES/texinfo.mo' (for text) unreadable: No such file or directory.
  /bin/sh: line 1: 93506 Abort trap: 6           makeinfo --split-size=5000000 --split-size=5000000 --split-size=5000000 --no-split -I ../../gcc/doc -I ../../gcc/doc/include -o doc/libgccjit.info ../../gcc/jit/docs/_build/texinfo/libgccjit.texi
  make[3]: *** [doc/libgccjit.info] Error 134
  make[3]: *** Waiting for unfinished jobs....
```

**Comment by Bo98** [comment]
Linux: (warnings can be ignored)
* `gst-libav` - not finding the correct libstdc++ for some reason, but I believe this issue has been seen beforee
* `jetty` - known failure, ignore this one
* `root` - not finding `string_view` header for some reason
* `yte-dl` - not GCC related

So `root` is probably the only "unexpected" one here. I wonder if that has a baked in versioned Cellar path to GCC somewhere.

---

11-arm64: looks like a crash bug in `makeinfo`. Given there's no changes, it could be a rare crash bug we've just not hit before? Might just work fine next time.

```
Process:               makeinfo [93506]
Path:                  /usr/bin/makeinfo
Identifier:            makeinfo
Version:               19
Code Type:             ARM-64 (Native)
Parent Process:        ??? [93490]
Responsible:           bash [1709]
User ID:               502

Date/Time:             2022-04-23 05:15:21.425 -0700
OS Version:            macOS 11.6.5 (20G527)
Report Version:        12
Anonymous UUID:        31FAF4F8-EAAA-98D7-BE22-8B050F6762F6


Time Awake Since Boot: 1000000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld3 mode
abort() called
makeinfo(93506,0x10454bd40) malloc: Incorrect checksum for freed object 0x14b0043b8: probably modified after being freed.
Corrupt value: 0x2f646c692f656475
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib              0x00000001a0d14e28 __pthread_kill + 8
1   libsystem_pthread.dylib             0x00000001a0d4743c pthread_kill + 292
2   libsystem_c.dylib                   0x00000001a0c8f454 abort + 124
3   libsystem_malloc.dylib              0x00000001a0b77ecc malloc_vreport + 560
4   libsystem_malloc.dylib              0x00000001a0b8dae4 malloc_zone_error + 104
5   libsystem_malloc.dylib              0x00000001a0b8d880 free_list_checksum_botch + 40
6   libsystem_malloc.dylib              0x00000001a0b6f594 tiny_free_no_lock + 2276
7   libsystem_malloc.dylib              0x00000001a0b6eb30 free_tiny + 428
8   makeinfo                            0x00000001041ab8d0 0x10419c000 + 63696
9   makeinfo                            0x00000001041b1de4 0x10419c000 + 89572
10  makeinfo                            0x00000001041b500c 0x10419c000 + 102412
11  makeinfo                            0x00000001041afe7c 0x10419c000 + 81532
12  libdyld.dylib                       0x00000001a0d65430 start + 4
```

**Comment by cho-m** [comment]
Just rev-bumped `root` for now unless someone wants to figure out why it previously failed.

I assume macOS audit failures were from brew's curl changes that were fixed after run.

Linux is known/reoccurring failures for `jetty` and `gst-libav`.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
