### PR TITLE
libhttpserver 0.17.5

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
A number of messages like this pops up
```
23:50:15 /usr/local/include/httpserver/http_response.hpp:71:36: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
```

**Comment by javian** [comment]
One solution to the issue in another formula is here https://github.com/Homebrew/homebrew-core/pull/28140/files

**Comment by igas** [comment]
@javian fixed, sierra has an https issue, do we skip it?

**Comment by javian** [comment]
@igas is it a general issue ? It sounds weird that Sierra woulnd't be able to download the tarball

**Comment by fxcoudert** [comment]
It fetched okay when testing, so probably the audit is a CI network fluke.

**Pull request closed without merging**
