### PR TITLE
corectl 0.7.13

### PR DESCRIPTION
**Pull request by AntonioMeireles**
Hey again...

yet another sunny day, yet another release...

thanks in advance!

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
@ilovezfs hey! ;-) (&& thanks in advance)

**Comment by ilovezfs** [comment]
Thanks @AntonioMeireles! Keep 'em coming!!! :sunglasses:

**Comment by DomT4** [comment]
> yet another sunny day, yet another release

It's pouring down with rain here 👀

**Comment by AntonioMeireles** [comment]
@DomT4 just Brexit and come to Portugal - we'll welcome you for sure !

**Comment by ilovezfs** [comment]
#toosoon

**Comment by DomT4** [comment]
> just Brexit and come to Portugal - we'll welcome you for sure !

I voted "Remain", don't blame me 🙈.

**Pull request closed without merging**
