### PR TITLE
mono 5.0.0.100

### PR DESCRIPTION
**Pull request by fallenoak**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by fxcoudert — CHANGES_REQUESTED** [review]
Hi @fallenoak, thanks for the pull request. Please update the `fsharp` resource.

**Comment by fallenoak** [comment]
@fxcoudert Done, pending CI! Thanks for looking at the PR.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Many thanks @fallenoak for the pull request!

**Comment by MartinJohns** [comment]
@fallenoak @fxcoudert This seems incomplete. There is no link for MSBuild added.

**Comment by fxcoudert** [comment]
@MartinJohns we build and install mono with `make install`, so if upstream decided to install this `msbuild` by default it should be there. Or is it not enabled by default?

**Comment by fallenoak** [comment]
@fxcoudert I've noticed that `msbuild` isn't available via this formula as well, despite ostensibly being added in Mono 5. Not sure why `make install` isn't sufficient. `xbuild` remains available and works just fine, albeit with a short deprecation warning logged to the console.

**Pull request closed without merging**
