### PR TITLE
Small fix for zsh-completions.rb

### PR DESCRIPTION
**Pull request by isnullxbh**
Use double quotes

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why don't single quotes work?

**Comment by isnullxbh** [comment]
> Why don't single quotes work?

Command:

`echo '$(brew --prefix)/xxx'`

Output:

> $(brew --prefix)/xxx

Expected output:

> /usr/local/xxx

Env.: macOS 10.15, bash 3.2 (same result in zsh)

Explanation:

https://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html#Single-Quotes

**Comment by fxcoudert** [comment]
`#{HOMEBREW}` prefix is not output as such, but substituted by `brew` itself:

```
Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
to load these completions, you may need to run this:

  chmod go-w '/usr/local/share'
```

so there is no need for double quotes.

**Comment by isnullxbh** [comment]
> `#{HOMEBREW}` prefix is not output as such, but substituted by `brew` itself:
> 
> ```
> Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
> to load these completions, you may need to run this:
> 
>   chmod go-w '/usr/local/share'
> ```
> 
> so there is no need for double quotes.

Sorry, it's my fault: I wanted to fix it:
https://formulae.brew.sh/formula/zsh-completions
Excuse me.

**Comment by isnullxbh** [comment]
> `#{HOMEBREW}` prefix is not output as such, but substituted by `brew` itself:
> 
> ```
> Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
> to load these completions, you may need to run this:
> 
>   chmod go-w '/usr/local/share'
> ```
> 
> so there is no need for double quotes.

I have I question.
Why I see **chmod go-w '$(brew --prefix)/share'** with single quotes at zsh-completions page?
https://formulae.brew.sh/formula/zsh-completions

**Comment by isnullxbh** [comment]
@fxcoudert, thanks for explanation!

**Pull request closed without merging**
