### PR TITLE
libgit2 1.1.0

### PR DESCRIPTION
**Pull request by jeroen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jeroen** [comment]
The [libgit2 github repo](https://github.com/libgit2/libgit2#libgit2---the-git-linkable-library) states:

> libgit2 is licensed under a very permissive license (GPLv2 with a special Linking Exception). This basically means that you can link it (unmodified) with any kind of software without having to release its source code.

**Comment by Rylan12** [comment]
Unless the linking exception is listed in the [SPDX license exception list](https://spdx.org/licenses/exceptions-index.html) we should probably just go with `GPL-2.0-only`. There's a `GPL-3.0-linking-exception` but the text isn't the same (and it's for `GPL-3.0`)

**Comment by jeroen** [comment]
OK I updated the PR to `GPL-2.0-only`

**Comment by jeroen** [comment]
The reverse dependency checks are timing out after 3 hours, but all seems good.

**Comment by fxcoudert** [comment]
```
brew linkage --test cargo-c
brew test --retry --verbose cargo-c
brew linkage --test git-series
brew test --retry --verbose git-series
brew linkage --test gitfs
brew test --retry --verbose gitfs
brew test --retry --verbose gitg
brew linkage --test gitless
brew test --retry --verbose gitless
brew linkage --test libgit2-glib
brew test --retry --verbose libgit2-glib
brew linkage --test literate-git
brew test --retry --verbose literate-git
brew linkage --test salt
```

**Comment by jeroen** [comment]
OK I didn't realize this changes the soname again. Going to talk to upstream if this is intended.

**Comment by fxcoudert** [comment]
`pygit2` in `salt` is not happy:

```
  In file included from src/blob.c:30:
  In file included from src/blob.h:34:
  src/types.h:36:2: error: You need a compatible libgit2 version (1.0.x)
  #error You need a compatible libgit2 version (1.0.x)
   ^
  1 error generated.
  error: command 'clang' failed with exit status 1
  Building wheel for pygit2 (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for pygit2
```

**Comment by Moisan** [comment]
The issue in `pygit2` has been fixed upstream but not released yet: https://github.com/libgit2/pygit2/issues/1040 .

**Comment by jeroen** [comment]
Sorry I have to give up on this. I don't know enough about python to fix these reverse dependencies. Hopefully somebody else can give this a shot, perhaps after the release of pygit2.

**Comment by chenrui333** [comment]
relates to #65706

**Pull request closed without merging**
