### PR TITLE
gtkwave 3.3.121 (new formula)

### PR DESCRIPTION
**Pull request by yanjiew1**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The cask `gtkwave` cannot be run on macOS 14 and later, so we need to build it from source. (Please see [the upstream issue](https://github.com/gtkwave/gtkwave/issues/250))

The patch is still needed to make gtkwave build on macOS successfully because GtkSocket and GtkPlug are not available on macOS. That patch also fixes the problem that `gtk-mac-integration` is not properly detected and used on macOS.

I have submitted [a pull request](https://github.com/gtkwave/gtkwave/pull/389) at the upstream repository.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Are upstream `gtkwave` trying to fix their cask? That seems like the preferable option.

**Comment by yanjiew1** [comment]
> Are upstream `gtkwave` trying to fix their cask? That seems like the preferable option.

I asked the upstream whether they will provide an updated prebuilt binary for macOS, they said they cannot provide an updated prebuilt binary for macOS because the maintainer of gtkwave does not own a mac.
* https://github.com/gtkwave/gtkwave/issues/390

**Comment by MikeMcQuaid** [comment]
@yanjiew1 Given they are on GitHub: the GitHub Actions macOS free runners could be useful here.

**Comment by yanjiew1** [comment]
@MikeMcQuaid, thanks for your suggestion. I will try to setup a GitHub workflow to build the macOS binary and package it as .app file. If successful, I will contribute the workflow upstream so that the upstream can produce the macOS binary with it.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Holding for now until we move forward a little with seeing if we can get the cake sorted.

**Pull request closed without merging**
