### PR TITLE
OpenVINO 2024.5.0

### PR DESCRIPTION
**Pull request by artanokhov**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by daeho-ro** [comment]
Related work here,
- https://github.com/Homebrew/homebrew-core/pull/197386

**Comment by cho-m** [comment]
Feel free to do version bump first.

My PR may take some more time as I am looking into `onnxruntime` and deciding on whether to try upstreaming a fix there.

**Comment by artanokhov** [comment]
Please add tags required for long-build, as we have in previous PR
https://github.com/Homebrew/homebrew-core/pull/191090

**Comment by cho-m** [comment]
The patch doesn't cleanly apply.

The exact lines that failed no longer show in stderr/stdout after https://github.com/Homebrew/brew/pull/18613.

**Review by cho-m — APPROVED** [review]

**Pull request merged**
