### PR TITLE
frescobaldi 2.19.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍 if the resources are fine.

**Comment by ilovezfs** [comment]
@DomT4 Actually the dependencies all look very-not-OK, though the upstream build system and brew-test-bot both seem to be oblivious! https://github.com/wbsoft/frescobaldi/blob/master/INSTALL#L48-L60

**Comment by ilovezfs** [comment]
Ah, I see that's because HEAD is on qt5 but their latest release is not.

**Comment by DomT4** [comment]
That's mildly annoying. Switching across to Qt5 would have been a nice bonus.

**Comment by ilovezfs** [comment]
@DomT4 I've asked when it's due just out of curiosity: https://github.com/wbsoft/frescobaldi/issues/842

**Pull request closed without merging**
