### PR TITLE
libcython: use Python's `libexec/"bin"` directory

### PR DESCRIPTION
**Pull request by carlocab**
Needed for #107517.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by cho-m** [comment]
Not sure why error is happening on Python 3.9. I think it is related to updating `setuptools` resource (which may have modified bundled `distutils`), but it is using same version as Python 3.10.
```
error: [Errno 2] No such file or directory: 'brew'
```

**Comment by cho-m** [comment]
Maybe https://github.com/pypa/setuptools/blob/main/setuptools/_distutils/command/_framework_compat.py#L45 ?
```py
    homebrew_prefix = subprocess.check_output(['brew', '--prefix'], text=True).strip()
```

**Comment by carlocab** [comment]
Same conclusion at https://github.com/Homebrew/homebrew-core/pull/107662.

**Comment by carlocab** [comment]
Testing an `inreplace` workaround.

**Review by SMillerDev — DISMISSED** [review]

**Review by branchv — APPROVED** [review]

**Pull request merged**
