### PR TITLE
openssl@1.1: keg only on all platforms

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is now falls under versioned formula rules and should be keg only on all platforms to prevent conflicts with `openssl@3`.

Also update resources while we are here.

### CODE REVIEW

**Comment by Bo98** [comment]
This is no-op on macOS and the test results are concerning. Something is already broken somewhere.

**Comment by GettingNifty** [comment]
t does not compile on Mac OS X El Capitan 10.11.6 possibly due to some kind of cmake dependency error. OpenSSL and lots of other programs are failing to compile using homebrew.

`Error: xmrig 6.15.3 did not build
Logs:
/Users/meltedroof/Library/Logs/Homebrew/xmrig/00.options.out
/Users/meltedroof/Library/Logs/Homebrew/xmrig/01.cmake
/Users/meltedroof/Library/Logs/Homebrew/xmrig/01.cmake.cc
/Users/meltedroof/Library/Logs/Homebrew/xmrig/02.make
/Users/meltedroof/Library/Logs/Homebrew/xmrig/02.make.cc
/Users/meltedroof/Library/Logs/Homebrew/xmrig/build
Do not report this issue to Homebrew/brew or Homebrew/core!

/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.3.7-38-g6295b08\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.11.6)\ curl/7.43.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=xmrig\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3+json --write-out '
'%{http_code} --header Accept:\ application/vnd.github.antiope-preview+json --dump-header /private/tmp/github_api_headers20211210-4704-1z074s7
These open issues may also help:
xmrig 6.16.2 https://github.com/Homebrew/homebrew-core/pull/90496`

Now I found out make wasn't installed. I keep having this issue, dependencies dissapearing?

After deleting the empty folder under /usr/local/Cellar/openssl/ and reinstalling openssl with brew install openssl --force
I'm getting
crypto/bn/rsaz-avx512.s:833:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA vmovdqa64 %ymm4,%ymm2 ^ crypto/bn/rsaz-avx512.s:834:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA vmovdqa64 %ymm4,%ymm1

Then sudo rm -rf /usr/bin/openssl because it was installed too and keg only I believe.

`Error: openssl@3 3.0.0 did not build
Logs:
/Users/meltedroof/Library/Logs/Homebrew/openssl@3/00.options.out
/Users/meltedroof/Library/Logs/Homebrew/openssl@3/01.perl
/Users/meltedroof/Library/Logs/Homebrew/openssl@3/01.perl.cc
/Users/meltedroof/Library/Logs/Homebrew/openssl@3/02.make
/Users/meltedroof/Library/Logs/Homebrew/openssl@3/02.make.cc
Do not report this issue to Homebrew/brew or Homebrew/core!

/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.3.7-38-g6295b08\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.11.6)\ curl/7.43.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=openssl\%403\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3+json --write-out '
'%{http_code} --header Accept:\ application/vnd.github.antiope-preview+json --dump-header /private/tmp/github_api_headers20211210-69381-dem3tp
These open issues may also help:
openssl@1.1: keg only on all platforms #85812
curl + recursive dependen{cies,ts}: switch to openssl@3 https://github.com/Homebrew/homebrew-core/pull/85775`

**Comment by SMillerDev** [comment]
That's because El Capitan is a very old OS that does not include the required software to compile this.

Please note this line in your output:
> Do not report this issue to Homebrew/brew or Homebrew/core!

You'll have to fix this for yourself.

**Comment by chris-araman** [comment]
It looks like `brew test-bot --only-formulae-dependents --testing-formulae=openssl@1.1` might succeed on macOS after merging the latest changes from `master` (https://github.com/chris-araman/homebrew-core/commit/84a18ef45837695127566481614f7828ceae8d8e), after the extraction of `ca-certificates`. @Bo98, are you able to update your branch?

**Comment by Bo98** [comment]
1.1.1m had issues just yesterday: #91326. I merged it anyway since I knew that PR didn't cause it.

Something breaks the certificate setup by the time it gets to `axel` and I've not figured out why that is. I'm not sure where the bug is yet (it's not necessarily `openssl@1.1` itself). Might need to try replicate what it's doing in a Docker container and go step by step to see at which point it breaks.

**Comment by chris-araman** [comment]
Interesting. I'm trying to learn more about how `test-bot` works, and `axel`, `curl` and others were passing On My Machine ™.

Are the failures intermittent, then? Or is there something I need to do differently in order to reproduce the issue locally?

**Comment by Bo98** [comment]
It consistently happens in CI. Testing the formulae individually works fine locally.

There’s something very specific about the order of operations that’s breaking things - I’m not sure exactly what yet. It might even be a bug in handling etc files when the bottles are being built - not much has been ruled out yet.

>

**Comment by chris-araman** [comment]
Running `test-bot` on GitHub Actions seems to [imply](https://github.com/Homebrew/homebrew-test-bot/blob/261e5e276066e1ec72776111cc60f4df0731678f/cmd/test-bot.rb#L107) the `--cleanup` argument, which causes things like [`cleanup_bottle_etc_var`](https://github.com/Homebrew/homebrew-test-bot/blob/15d0cdb1b3a7a00718e191a7fe521405f0d8cf55/lib/tests/formulae.rb#L384) to [happen](https://github.com/Homebrew/homebrew-test-bot/blob/15d0cdb1b3a7a00718e191a7fe521405f0d8cf55/lib/tests/formulae.rb#L127). Am I on the right track?

**Comment by chris-araman** [comment]
The `/opt/homebrew/etc/openssl@1.1/cert.pem` symlink is removed [here](https://github.com/Homebrew/homebrew-test-bot/blob/e08041320dead4a57bfe14634e6d272862eef58e/lib/tests/formulae.rb#L133). It’s not clear to me *why*, but this only happens when `openssl@1.1` was not already installed before invoking `--only-formulae`.

I can reproduce the missing `cert.pem` issue on my Mac:
```
find /opt/homebrew/etc -iname "cert.pem"
brew uninstall --ignore-dependencies openssl@1.1
brew test-bot --cleanup --only-formulae --testing-formulae=openssl@1.1
find /opt/homebrew/etc -iname "cert.pem"
```

If `openssl@1.1` was previously installed, `cleanup_bottle_etc_var` is a no-op and `/opt/homebrew/etc/openssl@1.1/cert.pem` remains.

**Comment by Bo98** [comment]
Thanks for looking into it!

It's likely a regression from when we changed the ordering.

If a PR modified multiple PRs, the order used to be:

- build formula 1
- test dependents of formula 1
- build formula 2
- ...

The `cleanup_bottle_etc_var` happened after dependent testing so this wasn't an issue. The reason we have `cleanup_bottle_etc_var` is because we diff the state of the `etc` and `var` folders before and after building the formula to determine what should be placed into the bottle.

But now the order is that all the formulae are built before moving to dependent testing.

If `formula.opt_prefix/".bottle/etc"` is still intact, I could use that to copy the files back to `HOMEBREW_PREFIX/"etc"` when we start dependent testing.

**Pull request closed without merging**
