### PR TITLE
pytorch: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by chenrui333**
See #134251.

### CODE REVIEW

**Comment by chenrui333** [comment]
no openssl linkage found

**Comment by carlocab** [comment]
No linkage to `openssl@1.1` in existing macOS 13-x86_64 bottles either:
```
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/opt/libomp/lib/libomp.dylib (libomp)
  /usr/local/opt/openblas/lib/libopenblas.0.dylib (openblas)
  /usr/local/opt/protobuf@21/lib/libprotobuf.32.dylib (protobuf@21)
Variable-referenced libraries:
  @rpath/libc10.dylib
  @rpath/libshm.dylib
  @rpath/libtorch.dylib
  @rpath/libtorch_cpu.dylib
  @rpath/libtorch_python.dylib
Dependencies with no linkage:
  eigen
  libuv
  python-typing-extensions
  pyyaml
```

**Comment by nandahkrishna** [comment]
I think it only needs `openssl` if the `USE_GLOO_WITH_OPENSSL` option is enabled. This matters only if both `USE_DISTRIBUTED` and `USE_GLOO` are enabled, but I don't think we do the latter.

**Comment by carlocab** [comment]
Cherry-picked onto #130487.

**Pull request closed without merging**
