### PR TITLE
Error: SHA256 mismatch

### PR DESCRIPTION
**Pull request by hhhernandez**
Updated sha256 - formula installed

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
$ brew uninstall --force wp-cli
Uninstalling wp-cli... (3 files, 4.4MB)
$ brew install --build-from-source wp-cli
==> Downloading https://github.com/wp-cli/wp-cli/releases/download/v1.5.1/wp-cli-1.5.1.phar
Already downloaded: /Users/hhhernandez/Library/Caches/Homebrew/wp-cli-1.5.1.phar
🍺  /usr/local/Cellar/wp-cli/1.5.1: 3 files, 4.4MB, built in 1 second
$ brew test wp-cli
Testing wp-cli
==> /usr/local/Cellar/wp-cli/1.5.1/bin/wp core download --path=wptest
$ brew audit --strict wp-cli
wp-cli:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
Error: 1 problem in 1 formula
_____
$ brew uninstall --force wpcli-completion
Uninstalling wpcli-completion... (5 files, 16.2KB)
$ brew install --build-from-source wpcli-completion
==> Downloading https://github.com/wp-cli/wp-cli/archive/v1.5.1.tar.gz
Already downloaded: /Users/hhhernandez/Library/Caches/Homebrew/wpcli-completion-1.5.1.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/wpcli-completion/1.5.1: 5 files, 16KB, built in 1 second
$ brew test wpcli-completion
Testing wpcli-completion
==> source /usr/local/Cellar/wpcli-completion/1.5.1/etc/bash_completion.d/wp && complete -p wp
$ brew audit --strict wpcli-completion
wpcli-completion:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
Error: 1 problem in 1 formula
-----

Formula is active and works.

### CODE REVIEW

**Review by mistydemeo — COMMENTED** [review]
Do you know why these tools changed `sha256`s? Have you checked in with the developers?

I noticed you committed a `.DS_Store` file - can you remove that, please?

**Comment by hhhernandez** [comment]
Hi mistidemeo, 

(1) I did not check with the developers. I looked (aka googled and looked at their issue board) but I didi not find anything related to this. I also googled some more and read that the sha256 can change 
https://github.com/Homebrew/homebrew-core/issues/18044 and a couple of other places that the sha hashes can change without notice (?). will try to go to the wp-cli site and open an issue.

(2) I apologize for loading the .DS file. forgot to put it in the ignore file. In the process of removing it.

Thanks for your help and understanding.

**Comment by hhhernandez** [comment]
HI mistydemeo,

I posted to th wp-cli wordpress board and I received a response on their take of the issue (see link below). According to them, there is no corresponding sha256 sum. Interesting ...

Hector
-----
https://wordpress.org/support/topic/wp-cli-sha256-mismatch/#post-10352562

**Comment by ilovezfs** [comment]
The sha256 in the formula is the checksum the download had in https://github.com/Homebrew/homebrew-core/pull/26917 on April 21st. We will not change the checksum in the formula until we know why the download was subsequently modified.

**Comment by ilovezfs** [comment]
I never deleted the old `phar` file from ~/Library/Caches/Homebrew

Here's the difference between the old file and the new file:
https://gist.github.com/ilovezfs/2095a51cd8a552840aaed34bd0a074e3

As you can see, the contents are very different. Note especially,

```
-wp-cli/wp-cli 1.5.1 2018-04-21T09:34:42+00:00
+wp-cli/wp-cli 1.5.1 2018-05-31T14:27:15+00:00
```
which suggests that the 1.5.1 release file was replaced yesterday.

**Comment by mistydemeo** [comment]
The release on GitHub also says it was released "a day ago", even though we know we had 1.5.1 in April, so it looks like it was retagged and a new .phar was uploaded.

image

**Comment by hhhernandez** [comment]
Hello All,

Thanks for all the info and comments. It's my first time posting a commit. Pretty exciting (at least for me). Any thoughts / comments would be greatly appreciated.

Hector

**Comment by mistydemeo** [comment]
I don't have a Wordpress account; would you mind passing along our comments to the Wordpress developers? It sounds like they're under the impression that the `.phar` didn't change, but we've got proof it did change yesterday. It'd be great to figure out from them what happened. 😃

**Comment by schlessera** [comment]
I wanted to chime in here as the maintainer of WP-CLI.

I re-released v1.5.1, as the file contained the wrong version information. It announced itself as being version `v2.0.0-alpha` instead.

All the hashes were updated to reflect the new official state of v1.5.1, DEB and RPM archives had been updated, etc...

The only thing that changed in the new package is the content of the `VERSION` file in the root of the Phar archive. In terms of functionality, it is the exact same release, still.

I forgot to check with Homebrew whether it got updated automatically or not.

In hindsight, I should have just pushed a v1.5.2 to fix the version issue instead of modifying the existing one (<- note to future self).

Sorry for the trouble!

**Comment by mistydemeo** [comment]
Thanks so much for the response!

> The only thing that changed in the new package is the content of the VERSION file in the root of the Phar archive. In terms of functionality, it is the exact same release, still.

Unfortunately, that's not the case! If you take a look at the diff in @ilovezfs's gist, there's actually quite a lot of changes from the previous 1.5.1.

> In hindsight, I should have just pushed a v1.5.2 to fix the version issue instead of modifying the existing one (<- note to future self).

In the future, that would be great from our perspective! As packagers, we think of releases as immutable - once we've got something tagged "1.5.1", the contents of that release/file shouldn't change.

> Sorry for the trouble!

No worries; thanks again for the very fast response!

**Comment by schlessera** [comment]
> Unfortunately, that's not the case! If you take a look at the diff in @ilovezfs's gist, there's actually quite a lot of changes from the previous 1.5.1.

Yes, I noticed that too now and will investigate: https://github.com/wp-cli/wp-cli/issues/4817

**Comment by mistydemeo** [comment]
> Yes, I noticed that too now and will investigate: wp-cli/wp-cli#4817

Perfect, thanks so much!

Are you okay with us sticking with the old 1.5.1 release? We uploaded a backed up copy of it to Bintray. We have a lot of users who already have that installed, and I'd prefer not to split our userbase between two versions or force those users who already have it to upgrade.

**Pull request closed without merging**
