### PR TITLE
libstfl: deprecate as upstream repo/website is gone

### PR DESCRIPTION
**Pull request by iMichka**
==> Analytics
install: 304 (30 days), 1,067 (90 days), 6,013 (365 days)
install-on-request: 126 (30 days), 529 (90 days), 2,855 (365 days)
build-error: 0 (30 days)

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
`newsboat` needs this. Deprecating is probably better for now while things get figured out (the Ruby PR will skip deprecated formulae).

**Comment by iMichka** [comment]
I opened an issue upstream: https://github.com/newsboat/newsboat/issues/1881

**Review by Bo98 — APPROVED** [review]

**Comment by jottr** [comment]
@iMichka how about adding the newsboat maintained [`stfl`](https://github.com/newsboat/stfl) library instead of just deprecating this one?

**Comment by jottr** [comment]
Nice. Do you have an idea why the build fails on ubuntu?

**Pull request merged**
