### PR TITLE
passenger: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
@SMillerDev this was another formula that was relying on the deprecated macOS Apache, so I have changed it to use the `httpd` formula on macOS as well.  Since it is only a build dependency I don't think it needs a revision bump.

**Comment by SMillerDev** [comment]
Wait, does it need httpd to build the nginx module?

**Comment by danielnachun** [comment]
I'm assuming it's using it for the `apache2` module that is also installed: https://github.com/Homebrew/homebrew-core/blob/87bf7cbe1332a821766160f86fa81ee4d5686890/Formula/passenger.rb#L42.  I'm not sure what it's using for `nginx`.

**Comment by SMillerDev** [comment]
Could you move the comment then?

**Comment by danielnachun** [comment]
I see now why that was very confusing. I've rearranged the comments so that it's clear that `httpd` is needed for building the Apache 2 module and `nginx` is need to build nginx module.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
