### PR TITLE
python@3.12: update resources (rev bump)

### PR DESCRIPTION
**Pull request by mavenor**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Bumping to revision <s>1 (`3.12.1_1`)</s> 2 (`3.12.1_2`) with:
- setuptools: 69.0.2 → 69.0.3
- pip: 23.3.1 → <s>23.3.2</s> 24.0

### CODE REVIEW

**Comment by bevanjkay** [comment]
@mavenor the `long build` label just designates that a long build is required. We only have two slots available for longer builds, so a maintainer will start the run when there's availability

**Comment by mavenor** [comment]
Ahh, I see! Thanks for the heads-up, @bevanjkay!
Stupid of me to not realise 😬😅

**Comment by mavenor** [comment]
`pip` has been bumped from `23.3.1` to `24.0`; bumping resource here too

**Comment by mavenor** [comment]
Oops! I’m so sorry: I forgot to squash the commits into one 😅😬

**Comment by mavenor** [comment]
Doesn’t #162003 (Python `3.12.1` → 13.12.2`) make this irrelevant? Perhaps I should close this PR 😆
<sup>and help reduce the number of <kbd>long build</kbd> PRs out there :)</sup>

**Comment by mavenor** [comment]
Now `3.12.1_2`: rebased onto 3.12.1_1, commit adf2dd61fe0 (#160009). Please advice, should I close this PR? 😅
<sup>Been open for > 3 weeks now and I wanna help, not add to the burden 👀😬</sup>

**Comment by p-linnane** [comment]
Hi @mavenor. Yes, at this point let's close this and focus our efforts on the version bump PR which will take care of this. I apologize for the delay in us getting back to you, many of us have been traveling for our Annual General Meeting. Apologies and thanks for the PR!

**Comment by mavenor** [comment]
Thanks for getting back! 😃
Please don't apologise, I understand that you maintainers have a lot on your plates 🙃
I'm glad for the mere existence of Homebrew, and I hope I'll be able to help sooner or later ✌️

**Pull request closed without merging**
