### PR TITLE
gstreamer 1.8.1

### PR DESCRIPTION
**Pull request by lovebug356**

### CODE REVIEW

**Comment by DomT4** [comment]
CC @tschoonj in case you've any additional comments here.

**Comment by tschoonj** [comment]
No looks good to me. Thanks @lovebug356 !

**Comment by DomT4** [comment]
Thanks for the extra review Tom!

@lovebug356 Looks like one of your new commits has a failing patch:
```
==> Verifying gst-validate-1.8.1.tar.xz checksum
==> Patching
patching file gst-libs/gst/video/Makefile.in
Hunk #1 FAILED at 487.
1 out of 1 hunk FAILED -- saving rejects to file gst-libs/gst/video/Makefile.in.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

**Comment by lovebug356** [comment]
Thx for reviewing. The patch for gst-validate is fixed upstream, so I removed it in the new patches.

**Comment by DomT4** [comment]
Merged in a bunch o'commits. Thank you for your contribution to Homebrew @lovebug356; we appreciate it! :smiley_cat:

**Pull request closed without merging**
