### PR TITLE
wrk fix Mojave compilation

### PR DESCRIPTION
**Pull request by zifeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lembacon** [comment]
```
10:37:21 ==> brew style wrk
10:37:25 ==> FAILED
10:37:25 == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wrk.rb ==
10:37:25 C: 21: 52: Trailing whitespace detected.
10:37:25 
10:37:25 1 file inspected, 1 offense detected
```

**Comment by zifeo** [comment]
@lembacon damn Github, fixed!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @zifeo for the fix! Merged

**Pull request closed without merging**
