### PR TITLE
gimp moved to cask

### PR DESCRIPTION
**Pull request by AnastasiaSulyagina**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

---

See [#15603](https://github.com/caskroom/homebrew-cask/issues/15603) for more details
In case somebody is opposed, cc @vitorgalvao for discussion

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍 but let's give it a few days to make sure the `osxfuse` and/or `tuntap` changes don't 💥

**Comment by DomT4** [comment]
Fine with this one, but this is likely to be noticed. `osxfuse` & `tuntap` together don't match 25% of `gimp` installations via us.

**Comment by vitorgalvao** [comment]
Thumbs up. Nothing more to add.

cc @jawshooah @adidalal

**Comment by adidalal** [comment]
Sure, LGTM

**Comment by ilovezfs** [comment]
What's the goal with killing the gimp source build?

**Comment by MikeMcQuaid** [comment]
Less maintenance, consistency with original Homebrew principle that this isn't the place for GUI apps (and the resulting deletion of e.g. `brew linkapps` that can eventually result).

**Comment by ilovezfs** [comment]
```
 -  depends_on "ghostscript" => :optional
-  depends_on "poppler" => :optional
-  depends_on "libexif" => :optional
```

Does the upstream version provide all three of those?

**Comment by ilovezfs** [comment]
```
-  depends_on "libpng" => :recommended
-  depends_on "libwmf" => :recommended
-  depends_on "libtiff" => :recommended
```
Also, these. My assumption that the answer would be yes for sure I realized is unwarranted.

In addition, there may be items we're unconditionally requiring that are actually options in configure and not included by upstream's version.

In any case, `brew linkapps` is :no_good:, so even if upstream's version is a severely incomplete toy version compared to ours or aborts on launch in a ball of :fire:, good riddance from my own perspective.

**Pull request merged**
