### PR TITLE
grafana 6.2.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
build step failed
```
08:22:42 /private/tmp/grafana-20190522-16185-9hf6ap/grafana-6.2.0/.brew_home/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: 'util-inl.h' file not found
08:22:42 #  include <util-inl.h>
08:22:42            ^~~~~~~~~~~~
08:22:42 1 error generated.
08:22:42 make: *** [Release/obj.target/iltorb/src/dec/stream_decode.o] Error 1
08:22:42 gyp ERR! build error 
08:22:42 gyp ERR! stack Error: `make` failed with exit code: 2
08:22:42 gyp ERR! stack     at ChildProcess.onExit (/private/tmp/grafana-20190522-16185-9hf6ap/grafana-6.2.0/src/github.com/grafana/grafana/node_modules/node-gyp/lib/build.js:262:23)
08:22:42 gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
08:22:42 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
08:22:42 gyp ERR! System Darwin 18.6.0
08:22:42 gyp ERR! command \"/usr/local/Cellar/node/12.3.0/bin/node\" \"/private/tmp/grafana-20190522-16185-9hf6ap/grafana-6.2.0/src/github.com/grafana/grafana/node_modules/iltorb/node_modules/.bin/node-gyp\" \"rebuild\"
08:22:42 gyp ERR! cwd /private/tmp/grafana-20190522-16185-9hf6ap/grafana-6.2.0/src/github.com/grafana/grafana/node_modules/iltorb
08:22:42 gyp ERR! node -v v12.3.0
08:22:42 gyp ERR! node-gyp -v v3.8.0
08:22:42 gyp ERR! not ok"
08:22:42 info This module is OPTIONAL, you can safely ignore this error
08:22:42 error /private/tmp/grafana-20190522-16185-9hf6ap/grafana-6.2.0/src/github.com/grafana/grafana/node_modules/node-sass: Command failed.
08:22:42 Exit code: 1
08:22:42 Command: node scripts/build.js
08:22:42 Arguments: 
08:22:42 Directory: /private/tmp/grafana-20190522-16185-9hf6ap/grafana-6.2.0/src/github.com/grafana/grafana/node_modules/node-sass
08:22:42 Output:
08:22:42 Building: /usr/local/Cellar/node/12.3.0/bin/node /private/tmp/grafana-20190522-16185-9hf6ap/grafana-6.2.0/src/github.com/grafana/grafana/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
08:22:42 gyp info it worked if it ends with ok
```

**Comment by chrmoritz** [comment]
Looks like `grafana`'s build dependencies aren't quite compatible with `node` 12 yet (it wasn't tested during the `node` 12 PR because it's a build-only dependency). 

Fortunately it can be easily fixed by bumping `node-sass` to [4.12.0](https://github.com/sass/node-sass/releases/tag/v4.12.0).

```diff
--- a/Formula/grafana.rb
+++ b/Formula/grafana.rb
@@ -17,6 +17,9 @@ class Grafana < Formula
   depends_on "yarn" => :build
 
   def install
+    # fix node 12 compatibility
+    inreplace "package.json", "\"node-sass\": \"4.11.0\",", "\"node-sass\": \"4.12.0\","
+
     ENV["GOPATH"] = buildpath
     grafana_path = buildpath/"src/github.com/grafana/grafana"
     grafana_path.install buildpath.children

```

**Comment by chenrui333** [comment]
@chrmoritz, cool, I will make an update.

**Comment by zbeekman** [comment]
> Fortunately it can be easily fixed by bumping `node-sass` to [4.12.0](https://github.com/sass/node-sass/releases/tag/v4.12.0).

We should not be relying on `inreplacing` stuff too heavily to patch problems with upstream. At a minimum we need a comment showing this was reported or a PR/patch was submitted upstream. This one case is simple enough that `inreplace` might be acceptable, provided it is reported upstream and a comment with a link is included.

**Comment by chenrui333** [comment]
I am testing locally now, once it passed and tested, I will submit the commit.

I will also add a PR to granfana repo to address this as well.

**Comment by chenrui333** [comment]
Added the issue tracker into the formula. 

I tried to just bump the version of `node-sass`, but seems running into other issues in grafana yarn dependencies refresh.

**Comment by marefr** [comment]
See https://github.com/grafana/grafana/issues/17242#issuecomment-495134934

**Comment by torkelo** [comment]
Can the PR author try to change 

 depends_on "node" => :build 
to 
 depends_on "node@10" => :build

So that LTS node is used

**Review by zbeekman — APPROVED** [review]
LGTM

**Comment by chenrui333** [comment]
Just squashed the commits.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
