### PR TITLE
grpc: build on Apple Silicon

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
Has the same issue as https://github.com/Homebrew/homebrew-core/pull/68457.

Setting `DYLD_LIBRARY_PATH` helps, but that's not an acceptable solution. https://github.com/Homebrew/discussions/discussions/485#discussioncomment-269750

**Comment by carlocab** [comment]
See also #68457, where I use the same hack.

**Comment by carlocab** [comment]
I suspect that the `MachO::Tools` hack is excessive, and it is only really needed for `grpc_cli`. This is because everything else is installed using `make install`, with the exception of `grpc_cli`, which is moved manually out of the build directory.

**Comment by fxcoudert** [comment]
I don't feel this is right to do such low-level fixing. We probably want to report this, and see if they have advice for how on our to set up cmake so it does the right thing.

**Comment by carlocab** [comment]
>I don't feel this is right to do such low-level fixing.

I think part of the need for the low-level fix is the low-level way we install `grpc_cli`, so I think the correct thing to do here might be to figure out how to, if possible, install `grpc_cli` directly through `cmake`. I'll look into it.

**Comment by carlocab** [comment]
Upstream issue filed: https://github.com/grpc/grpc/issues/25176

Closing this for now in favour of #69125.

**Pull request closed without merging**
