### PR TITLE
swiftgen 3.0.1

### PR DESCRIPTION
**Pull request by AliSoftware**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [X] Does your build pass `brew test <formula>` (after doing `brew install <formula>`)?

-----

Source code upgraded to Swift 2.3 and Xcode 8 🎉

### CODE REVIEW

**Comment by AliSoftware** [comment]
@MikeMcQuaid  The Yosemite bottle seems to have failed generating.
It is related to the fact that this version of SwiftGen needs to be built with Xcode 8?
Is there something I should do on my end to fix? (Don't have a Yosemite to test locally)

**Comment by MikeMcQuaid** [comment]
Looks like `depends_on :xcode => "7.0"` needs bumped.

**Comment by AliSoftware** [comment]
Oh, of course, silly me!
Thx

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
