### PR TITLE
bump python3 devel to python 3.6.0b2

### PR DESCRIPTION
**Pull request by myyc**
Just a trivial version bump. Installs cleanly etc.

### CODE REVIEW

**Comment by tdsmith** [comment]
Test failures should be resolved by https://github.com/Homebrew/brew/pull/1298.

**Comment by myyc** [comment]
Seems to be failing still. Any update?

**Comment by tdsmith** [comment]
Unrelated error in the shyaml formula; I'll fix it. Looks good!

**Comment by tdsmith** [comment]
Thanks for the PR!

**Comment by myyc** [comment]
Cool thanks :)

**Pull request merged**
