### PR TITLE
gmp 6.2.0

### PR DESCRIPTION
**Pull request by fxcoudert**
https://gmplib.org/gmp6.2.html

### CODE REVIEW

**Comment by fxcoudert** [comment]
`mlton` is apparently not finding the new `gmp` library. Trying to rebuild from source.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by fxcoudert** [comment]
Even rebuilt from source, `mlton` is not happy:

```
==> /usr/local/Cellar/mlton/20180207_1/bin/mlton hello.sml
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
unhandled exception: Fail: call to system failed with Fail: exit status 1:
gcc -o hello /private/tmp/filevmSVtP.o /private/tmp/fileKheAjZ.o -L/usr/local/Cellar/mlton/20180207_1/lib/mlton/targets/self -lmlton-pic -lgdtoa-pic -lm -lgmp -m64
```

I don't know why.

**Comment by fxcoudert** [comment]
The `mlton` failure is pre-existing.

**Pull request closed without merging**
