### PR TITLE
e2fsprogs 1.43.4

### PR DESCRIPTION
**Pull request by cimarronm**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
@cimarronm The checksum needs fixing:
```
Warning: Formula reports different SHA256: 1644db4fc58300c363ba1ab688cf9ca1e46157323aee1029f8255889be4bc856
Downloaded to: /Users/brew/Library/Caches/Homebrew/e2fsprogs-1.43.4.tar.gz
SHA256: a648a90a513f1b25113c7f981af978b8a19f832b3a32bd10707af3ff682ba66d
```

**Comment by neutric** [comment]
On second thought, the checksum matches for the download from kernel.org. Something is going on here.

**Comment by ilovezfs** [comment]
It looks like the one on kernel.org got altered. The only difference in the files is
```
< 00000000  1f 8b 08 00 04 46 91 58  02 03 ec 5b 69 73 1b 49  |.....F.X...[is.I|
---
> 00000000  1f 8b 08 00 d6 40 91 58  02 03 ec 5b 69 73 1b 49  |.....@.X...[is.I|
```

**Comment by ilovezfs** [comment]
We can use `https://fossies.org/linux/misc/e2fsprogs-1.43.4.tar.gz` for the mirror instead.

**Comment by ilovezfs** [comment]
@cimarronm shipped! Thanks for your first contribution to Homebrew. :+1:

**Pull request closed without merging**
