### PR TITLE
chakra 1.4.1

### PR DESCRIPTION
**Pull request by mathiasbynens**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Looks like O3 will need to be put back for now.

**Comment by ilovezfs** [comment]
@obastemur looks like we're still having a bit of trouble in 1.4.1 without the O3:
https://bot.brew.sh/job/Homebrew%20Core/16173/version=sierra/console
https://bot.brew.sh/job/Homebrew%20Core/16173/version=el_capitan/console
https://bot.brew.sh/job/Homebrew%20Core/16173/version=yosemite/console

```
[100%] Linking CXX executable ch
Undefined symbols for architecture x86_64:
  "void Js::ByteCodeWriter::Data::EncodeOpCode<(Js::LayoutSize)1>(unsigned short, Js::ByteCodeWriter*)", referenced from:
      bool Js::AsmJsByteCodeWriter::TryWriteAsmReg2<Js::LayoutSizePolicy<(Js::LayoutSize)1> >(Js::OpCodeAsmJs, unsigned int, unsigned int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      bool Js::AsmJsByteCodeWriter::TryWriteInt1Const1<Js::LayoutSizePolicy<(Js::LayoutSize)1> >(Js::OpCodeAsmJs, unsigned int, int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      bool Js::AsmJsByteCodeWriter::TryWriteReg1IntConst1<Js::LayoutSizePolicy<(Js::LayoutSize)1> >(Js::OpCodeAsmJs, unsigned int, int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      bool Js::AsmJsByteCodeWriter::TryWriteLong1Const1<Js::LayoutSizePolicy<(Js::LayoutSize)1> >(Js::OpCodeAsmJs, unsigned int, long) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      bool Js::AsmJsByteCodeWriter::TryWriteFloat1Const1<Js::LayoutSizePolicy<(Js::LayoutSize)1> >(Js::OpCodeAsmJs, unsigned int, float) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      bool Js::AsmJsByteCodeWriter::TryWriteDouble1Const1<Js::LayoutSizePolicy<(Js::LayoutSize)1> >(Js::OpCodeAsmJs, unsigned int, double) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      Js::AsmJsByteCodeWriter::AsmReg1(Js::OpCodeAsmJs, unsigned int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      ...
  "void Js::ByteCodeWriter::Data::EncodeOpCode<(Js::LayoutSize)2>(unsigned short, Js::ByteCodeWriter*)", referenced from:
      bool Js::AsmJsByteCodeWriter::TryWriteAsmReg2<Js::LayoutSizePolicy<(Js::LayoutSize)2> >(Js::OpCodeAsmJs, unsigned int, unsigned int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      Js::AsmJsByteCodeWriter::AsmInt1Const1(Js::OpCodeAsmJs, unsigned int, int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      Js::AsmJsByteCodeWriter::AsmReg1IntConst1(Js::OpCodeAsmJs, unsigned int, int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      Js::AsmJsByteCodeWriter::AsmLong1Const1(Js::OpCodeAsmJs, unsigned int, long) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      Js::AsmJsByteCodeWriter::AsmFloat1Const1(Js::OpCodeAsmJs, unsigned int, float) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      Js::AsmJsByteCodeWriter::AsmDouble1Const1(Js::OpCodeAsmJs, unsigned int, double) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      Js::AsmJsByteCodeWriter::AsmReg1(Js::OpCodeAsmJs, unsigned int) in libChakra.Jsrt.a(AsmJsByteCodeWriter.cpp.o)
      ...
  "Js::JavascriptString::Concat(Js::JavascriptString*, Js::JavascriptString*)", referenced from:
      Js::JavascriptError::EntryToString(Js::RecyclableObject*, Js::CallInfo, ...) in libChakra.Jsrt.a(JavascriptError.cpp.o)
      Js::JavascriptLibrary::CreateGetterFunction(int, Js::FunctionInfo*) in libChakra.Jsrt.a(JavascriptLibrary.cpp.o)
      Js::JavascriptLibrary::CreateSetterFunction(int, Js::FunctionInfo*) in libChakra.Jsrt.a(JavascriptLibrary.cpp.o)
      Js::JavascriptFunction::NewInstanceHelper(Js::ScriptContext*, Js::RecyclableObject*, Js::CallInfo, Js::ArgumentReader&, Js::JavascriptFunction::FunctionKind) in libChakra.Jsrt.a(JavascriptFunction.cpp.o)
      Js::JavascriptString* Js::JavascriptFunction::GetNativeFunctionDisplayStringCommon<Js::JavascriptString, Js::JavascriptString*, Js::ScriptContext>(Js::ScriptContext*, Js::JavascriptString*) in libChakra.Jsrt.a(JavascriptFunction.cpp.o)
      Js::JavascriptFunction::DisplayNameHelper(char16_t const*, unsigned int) const in libChakra.Jsrt.a(JavascriptFunction.cpp.o)
      Js::RecyclableObjectDisplay::Value(int) in libChakra.Jsrt.a(DiagObjectModel.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/ch/ch] Error 1
make[1]: *** [bin/ch/CMakeFiles/ch.dir/all] Error 2
make: *** [all] Error 2
See error details above. Exit code was 2
```

**Comment by mathiasbynens** [comment]
Added back the `O3`.

**Comment by ilovezfs** [comment]
@mathiasbynens yup. Let's see what @obastemur think went wrong before merging this though.

**Comment by obastemur** [comment]
I had mentioned this a bit before. Sorry for not being clear. ChakraCore's first cross platform release will be part of the next major release 2.0.

 1.41 doesn't include most of the xplat related updates and fixes made on master branch.

That 2.0 release and forward, Homebrew test is one of the pre-release check items.

If things go as planned, our next release is 2.0

**Comment by ilovezfs** [comment]
@obastemur Thanks for clarifying that. Let's merge this as-is then!

**Comment by ilovezfs** [comment]
@mathiasbynens Shipped. Thanks for the version bump! :white_check_mark:

**Comment by mathiasbynens** [comment]
Thanks for the help, everyone!

> That 2.0 release and forward, Homebrew test is one of the pre-release check items.

🎉🎉🎉

**Pull request closed without merging**
