### PR TITLE
gmime 3.0.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@ilovezfs any thoughts on what's the best approach here to deal with `notmuch` and `mu` not being compatible with gmime 3.0.0? Shall I make `gmime@2.6` and link these two formula against while we wait for new releases?

**Comment by ilovezfs** [comment]
@tschoonj I'd either wait for the new versions, or vendor gmime 2.6.23 into those two formulae, since a `gmime@2.6` is unlikely to be needed by users and the install method is simple.

**Comment by fxcoudert** [comment]
Don't `notmuch` and `mu` need a revision bump?

**Comment by tschoonj** [comment]
Sorry, I have been a bit sloppy lately... Should be fixed now

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
