### PR TITLE
quicktype 12.0.10

### PR DESCRIPTION
**Pull request by dvdsgl**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@dvdsgl 12.0.13 is now the current version. Also, if you could please make sure the email address you're using for commits is associated with your GitHub account that would be great.

**Comment by dvdsgl** [comment]
Oh, wow! This was sent by my CI system. It's never worked before but for some reason, suddenly it has.

Our patch version is auto-incremented and we release many times a day. I have a script that sends this PR on every tenth patch version. Are you saying you'd like me to send a PR for every patch, or release less often? 😆

**Comment by ilovezfs** [comment]
ah I didn't realize you'd throttled it. That is fine.

**Comment by ilovezfs** [comment]
@dvdsgl can you please add a comment above the url like the comments in vim and awscli?

**Comment by ilovezfs** [comment]
Feel free to reopen when feedback has been addressed.

**Pull request closed without merging**
