### PR TITLE
tcl-tk 8.6.12

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by SMillerDev** [comment]
I'm thinking libheif might need rebottling on 12.0?
```
==> /opt/homebrew/Cellar/openimageio/2.3.9.1/bin/oiiotool --info /opt/homebrew/Library/Homebrew/test/support/fixtures/test.jpg 2>&1
sh: line 1: 56683 Abort trap: 6           /opt/homebrew/Cellar/openimageio/2.3.9.1/bin/oiiotool --info /opt/homebrew/Library/Homebrew/test/support/fixtures/test.jpg 2>&1
dyld[56683]: Library not loaded: /opt/homebrew/opt/jpeg-xl/lib/libjxl.0.dylib
  Referenced from: /opt/homebrew/Cellar/libheif/1.12.0/lib/libheif.1.dylib
  Reason: tried: '/opt/homebrew/opt/jpeg-xl/lib/libjxl.0.dylib' (no such file), '/usr/local/lib/libjxl.0.dylib' (no such file), '/usr/lib/libjxl.0.dylib' (no such file), '/opt/homebrew/Cellar/jpeg-xl/0.6.1/lib/libjxl.0.dylib' (no such file), '/usr/local/lib/libjxl.0.dylib' (no such file), '/usr/lib/libjxl.0.dylib' (no such file)
```

**Review by carlocab — APPROVED** [review]
Yea, `libheif` needs rebottling.

**Comment by Bo98** [comment]
I've rebottled it now. It could arguably require a revision bump, though haven't heard anyone report it as a bug yet.

**Comment by Bo98** [comment]
(To be honest, I mostly went the rebottle route as an excuse to test if the workflow works - and it does)

**Comment by carlocab** [comment]
Probs because `brew` will rebuild it from source when it spots broken linkage and it only takes a few minutes so no one's too bothered by it yet.

**Pull request closed without merging**
