### PR TITLE
deno 1.20.3

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by cho-m** [comment]
```
     Compiling swc_common v0.17.5
       Running `CARGO=/opt/homebrew/Cellar/rust/1.59.0/bin/cargo CARGO_CRATE_NAME=swc_common CARGO_MANIFEST_DIR=/Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/swc_common-0.17.5 CARGO_PKG_AUTHORS='강동윤 <kdy1997.dev@gmail.com>' CARGO_PKG_DESCRIPTION='Common utilities for the swc project.' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=Apache-2.0 CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=swc_common CARGO_PKG_REPOSITORY='https://github.com/swc-project/swc.git' CARGO_PKG_VERSION=0.17.5 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=17 CARGO_PKG_VERSION_PATCH=5 CARGO_PKG_VERSION_PRE='' DYLD_FALLBACK_LIBRARY_PATH='/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps:/opt/homebrew/Cellar/rust/1.59.0/lib:/private/tmp/deno-20220316-45800-1v1vo9p/deno/.brew_home/lib:/usr/local/lib:/usr/lib' rustc --crate-name swc_common --edition=2021 /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/swc_common-0.17.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,future-incompat --crate-type lib --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=z -C codegen-units=1 --cfg 'feature="default"' --cfg 'feature="sourcemap"' -C metadata=2c29d773b66f5695 -C extra-filename=-2c29d773b66f5695 --out-dir /private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps -L dependency=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps --extern ahash=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libahash-189caedee97224b4.rlib --extern ast_node=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libast_node-1c14ab55c8b56de3.dylib --extern cfg_if=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libcfg_if-afc7fea0518959c0.rlib --extern debug_unreachable=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libdebug_unreachable-87098822d38e395a.rlib --extern either=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libeither-a19679ef8b51d461.rlib --extern from_variant=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libfrom_variant-f9f6b76e09794174.dylib --extern num_bigint=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libnum_bigint-45d717288eacaf6d.rlib --extern once_cell=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libonce_cell-27e5feffc0d26426.rlib --extern owning_ref=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libowning_ref-dadd1c35f21ce287.rlib --extern rustc_hash=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/librustc_hash-d48cbb7bcb6e691f.rlib --extern scoped_tls=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libscoped_tls-be7b0c0fc6df7dac.rlib --extern serde=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libserde-ba48e172fca715bb.rlib --extern siphasher=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libsiphasher-1b66ba32fdd78557.rlib --extern sourcemap=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libsourcemap-e1a575b0d592e62d.rlib --extern string_cache=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libstring_cache-36505bd4e0654669.rlib --extern swc_eq_ignore_macros=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libswc_eq_ignore_macros-0b426886d096bad4.dylib --extern swc_visit=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libswc_visit-16daed78a276841a.rlib --extern tracing=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libtracing-95474e5c83549814.rlib --extern unicode_width=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libunicode_width-5730b2182fb9f355.rlib --extern url=/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/liburl-abe777fe1fc1fac9.rlib --cap-lints warn -C link-arg=-fuse-ld=lld`
  error: linking with `cc` failed: exit status: 1
    |
    = note: "cc" "-Wl,-exported_symbols_list,/private/tmp/rustc5DXApL/list" "-arch" "arm64" "/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/swc_common-2c29d773b66f5695.swc_common.be6f6226-cgu.0.rcgu.o" "/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/swc_common-2c29d773b66f5695.1rsjjybhhu7c3okf.rcgu.rmeta" "-L" "/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps" "-L" "/opt/homebrew/Cellar/rust/1.59.0/lib/rustlib/aarch64-apple-darwin/lib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libcfg_if-afc7fea0518959c0.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libsourcemap-e1a575b0d592e62d.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libbase64-c68f36ba8f59604e.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libregex-d99a2ce131540814.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libaho_corasick-12d7df936cf514db.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libmemchr-98e333ed67468613.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libregex_syntax-70443654aac6cf41.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libif_chain-3cfbc5708ed7dd35.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libserde_json-995e74c4d39defa5.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libryu-cb512f895006fb1d.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libitoa-baecda159cb883b5.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libindexmap-540a471cf8cf3877.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libhashbrown-b05d23ea2a3709cf.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libahash-189caedee97224b4.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libgetrandom-239755343858b1d3.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/liburl-abe777fe1fc1fac9.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libidna-27330d54af535342.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libunicode_normalization-aa49860e69e5d6f9.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libtinyvec-8f272d0b09d42ab0.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libtinyvec_macros-aa96dc4fd4c9e327.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libunicode_bidi-0f518458146435a2.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libform_urlencoded-d7aae1a8b17478f1.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libpercent_encoding-89164f69073092d4.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libmatches-48e4acb7efae5723.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libonce_cell-27e5feffc0d26426.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libdebug_unreachable-87098822d38e395a.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libunreachable-7e4624c9a5f78c7f.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libvoid-6f3af01f11cbfa1c.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libunicode_width-5730b2182fb9f355.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libtracing-95474e5c83549814.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libpin_project_lite-803a5d903f3beec7.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libtracing_core-b38c0ccd33800c60.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libscoped_tls-be7b0c0fc6df7dac.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libstring_cache-36505bd4e0654669.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libprecomputed_hash-31a0855d231cc069.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libparking_lot-5fe8f3c6c9fc0483.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libparking_lot_core-a07a672d122b055f.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/liblibc-01390e326bfcfd0a.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libsmallvec-310453e2c6c5a0ad.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/liblock_api-48b900347ce286d0.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libscopeguard-d57fc183366dbba5.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libinstant-7e35572d68c033bb.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libcfg_if-f8e48318fcf80dd3.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/liblazy_static-0373e891afe07e79.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libspin-c733bd3d9d35e40c.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libphf_shared-31a4020da86d3a8d.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libsiphasher-1b66ba32fdd78557.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libdebug_unreachable-c705603e9da9e8e2.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libnum_bigint-45d717288eacaf6d.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libnum_integer-5611d23db6f8ac13.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libnum_traits-3cab869493e09eca.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/librustc_hash-d48cbb7bcb6e691f.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libswc_visit-16daed78a276841a.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libeither-a19679ef8b51d461.rlib" "-Wl,-force_load" "-Wl,/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libserde-ba48e172fca715bb.rlib" "-L" "/opt/homebrew/Cellar/rust/1.59.0/lib/rustlib/aarch64-apple-darwin/lib" "-lstd-cbff820a9d41b6bb" "/opt/homebrew/Cellar/rust/1.59.0/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-712e7ae136e2b352.rlib" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/opt/homebrew/Cellar/rust/1.59.0/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/private/tmp/deno-20220316-45800-1v1vo9p/deno/target/release/deps/libswc_common-2c29d773b66f5695.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs" "-fuse-ld=lld"
    = note: ld64.lld: error: LC_DYLD_INFO_ONLY not found in /opt/homebrew/Cellar/rust/1.59.0/lib/rustlib/aarch64-apple-darwin/lib/libstd-cbff820a9d41b6bb.dylib
            ld64.lld: error: undefined symbol: ___rust_alloc_zeroed
            >>> referenced by -exported_symbol(s_list)
            
            ld64.lld: error: undefined symbol: ___rust_alloc
            >>> referenced by -exported_symbol(s_list)
            
```

**Comment by harrysolovay** [comment]
Any updates on this? Would very much like to upgrade.

**Comment by seidtgeist** [comment]
> Any updates on this? Would very much like to upgrade.

@harrysolovay It doesn’t look like anyone figured out why swc_common doesn’t compile. It looks like you’re motivated. Want to give it a try?

**Comment by harrysolovay** [comment]
@seidtgeist that's a very reasonable response to me being pushy (apologies). Unfortunately, I don't think I can be of much help in this case :/

**Comment by aslilac** [comment]
Hmm. I can repro it locally. Updating the download url and hash, and running `brew install --build-bottle deno` gives the same error.

But if I run all the same steps manually, (`wget` the .tar.gz, unpack it, `V8_FROM_SOURCE=1 cargo build -vv`) I can get it to build just fine. 🤷‍♀️ So I'm not sure what's going on here.

**Comment by cho-m** [comment]
> Hmm. I can repro it locally. Updating the download url and hash, and running `brew install --build-bottle deno` gives the same error.
> 
> But if I run all the same steps manually, (`wget` the .tar.gz, unpack it, `V8_FROM_SOURCE=1 cargo build -vv`) I can get it to build just fine. 🤷‍♀️ So I'm not sure what's going on here, at least at first glance. I'll try again tomorrow if I have the time/energy.

Did you use Homebrew's `rust` or a local Rust(e.g. `rustup`) install?

After some quick local attempts, I am thinking the issue is `rust` bottle for `arm64_monterey` rather than `deno`. I noticed that installing `arm64_big_sur` on my Monterey system successfully built `deno`.

We could try temporarily rebuilding `rust` in this PR (with dependent testing disabled) to see if build works after rebottling `rust`. If it still fails, may need further analysis on why only Monterey ARM is having issues.

**Comment by aslilac** [comment]
The successful build was with a rustup managed version of cargo and rustc (1.59.0)

I removed `depends_on "rust" => :build` from the formula, added ~/.cargo/bin/ to the path manually, and that resulted in a successful build, so I think you're on to something.

**Comment by aslilac** [comment]
Ok, ran some more tests and I'm like 99% sure it's a bad bottle of Rust. Not sure the best way to force a rebuild?

**Comment by SMillerDev** [comment]
Running a rust rebuild in https://github.com/Homebrew/homebrew-core/actions/runs/2027266523

**Comment by kidonng** [comment]
Might have luck with [1.20.2](https://github.com/denoland/deno/releases/tag/v1.20.2)?

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
