### PR TITLE
ruby 3.1.0

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by carlocab** [comment]
```
  installing extension headers:       /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/opt/homebrew/Cellar/ruby/3.1.0/include/ruby-3.1.0/arm64-darwin21
  /private/tmp/ruby-20211225-33417-lk2t09/ruby-3.1.0/lib/fileutils.rb:240:in `mkdir': Operation not permitted @ dir_s_mkdir - /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/opt (Errno::EPERM)
```
Why are you trying to install the extension headers there?

**Comment by faisal** [comment]
Notes:

- `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/opt/homebrew/Cellar/ruby/3.1.0/include/ruby-3.1.0/arm64-darwin21` looks to be the concatenation of `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk` and `/opt/homebrew/Cellar/ruby/3.1.0/include/ruby-3.1.0/arm64-darwin21`.
- The former is probably coming from `HOMEBREW_SDKROOT`.
- The latter is presumably the intended new `include` dir for Ruby.
- My next question is then "what step is inappropriately concatenating these strings to produce a nonsense target include dir?"

**Comment by charlesbjohnson** [comment]
Could this change be related? It appears to have been introduced in 3.1.0.

https://github.com/ruby/ruby/commit/fd978621ccbc9519afc05ad031ba2518e9a6f379#diff-226c8470544d095d188b137f19734969e97a4031f2dd84ce91093823f6fc58eaR127-R129

That `installing extension headers` line from the failing build appears to be logged from here and here:

https://github.com/ruby/ruby/blob/v3_1_0/tool/rbinstall.rb#L431-L436
https://github.com/ruby/ruby/blob/v3_1_0/tool/rbinstall.rb#L443-L447

Both are referencing a `rubyhdrdir`, which on my machine for Ruby 3.0.3 is defined as:

```sh
❯ ruby -e "puts(RbConfig::MAKEFILE_CONFIG.values_at('rubyhdrdir', 'includedir', 'prefix'))"
$(includedir)/$(RUBY_VERSION_NAME)
$(prefix)/include
/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3
```

**Comment by faisal** [comment]
If I download the source myself, and run the build by hand including running `./configure` with the same flags the Formula feeds it, the build works.

**Comment by charlesbjohnson** [comment]
I was able to confirm that this change is the culprit: https://github.com/ruby/ruby/commit/fd978621ccbc9519afc05ad031ba2518e9a6f379#diff-226c8470544d095d188b137f19734969e97a4031f2dd84ce91093823f6fc58eaR127-R129

I tested [this formula](https://gist.github.com/charlesbjohnson/e21074e661dbeac8ad1d9271355248c1) on a GitHub Action using the `macos-latest` runner with [this workflow](https://github.com/charlesbjohnson/homebrew-sandbox/blob/master/.github/workflows/sandbox.yml). Here are the [raw logs](https://gist.github.com/charlesbjohnson/8d476381a9da7d46759bf18b920e724b).

Here is the diff between @carlocab's changes and mine:

```diff
--- carlocab.rb 2022-01-06 22:13:48.794583500 -0600
+++ charlesbjohnson.rb  2022-01-06 22:13:56.144583500 -0600
@@ -86,6 +86,10 @@
       s.gsub! 'prepare "extension objects", vendorarchlibdir', ""
     end

+    inreplace "tool/mkconfig.rb" do |s|
+      s.gsub! ' = sdkroot', '= ""'
+    end
+
     system "make"
     system "make", "install"
```

**Comment by carlocab** [comment]
Thanks for investigating, @faisal, @charlesbjohnson. I have a (speculative) fix. Let's see how it goes.

**Comment by carlocab** [comment]
@Bo98 do you mind having a look at this? I can't reproduce the attempt to install headers into the SDK outside of `brew`, so I can't tell what exactly is going wrong here.

**Comment by Bo98** [comment]
Will do. I’m back on Monday but I’ll maybe be able to look later tonight.

**Comment by faisal** [comment]
```shell
$ brew linkage --test fastlane
Broken dependencies:
  /opt/homebrew/opt/ruby/lib/libruby.3.0.dylib (ruby)
$ ls /opt/homebrew/opt/ruby/lib/                 
libruby.3.1.dylib	pkgconfig
libruby.dylib		ruby
```

**Comment by faisal** [comment]
Your patch works for all my test cases, though none of my test cases include libruby.

**Comment by Bo98** [comment]
> @Bo98 do you mind having a look at this? I can't reproduce the attempt to install headers into the SDK outside of `brew`, so I can't tell what exactly is going wrong here.

I think https://github.com/Homebrew/brew/pull/12508 will actually fix this without any changes to the Ruby formula. I've just not had the time to test that PR on `qt@5` yet (which was my primary concern before) which is why it's not merged yet.

**Comment by faisal** [comment]
I took @carlocab's patch minus the `inreplace` and `--includedir` additions, applyed @Bo98's patch at https://github.com/Homebrew/brew/pull/12508, and was able to build without incident on an ARM Mac running macOS Monterey.

**Comment by carlocab** [comment]
Thanks for testing, @faisal. I think that's the direction we'll want to go here.

**Comment by carlocab** [comment]
Homebrew/brew#12508 is stalled, so I think we'll make do with an `inreplace` here for now.

We'll need to wait for the self-hosted Linux runner from https://github.com/Homebrew/homebrew-core/pull/91712 though.

**Comment by carlocab** [comment]
`travis` and `weechat` probably need `ruby@3.0`. Not sure what's the issue with `macvim`.

**Comment by carlocab** [comment]
I think MacVim should be fixed now. 🤞

**Comment by carlocab** [comment]
`cucumber-cpp` failed on ARM Monterey, but it seems like it's just an issue with ports:
```
  ==> /private/tmp/cucumber-cpp-test-20220206-43161-1t4vb40/bin/cucumber --publish-quiet
  Unable to contact the wire server at localhost:3902. Is it up? (Cucumber::Wire::Connection::ConnectionError)
```

**Comment by carlocab** [comment]
The only real failure is `cucumber-cpp` on ARM Monterey. (Linux failure is from an `:all` bottle that doesn't work on Linux.)

Not sure what to make of `cucumber-cpp` -- it may not be spurious, since I've seen the same error twice now. I also don't know how to fix it, though. Ideas, @Homebrew/core? Would like to ship this soon, as this has been delayed for a while and it's looking very close now.

**Comment by SMillerDev** [comment]
I remember `cucumber-cpp` having spurious errors when I worked on `cucumber-ruby`. It's also not super popular, so let's prioritize shipping ruby over this.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
