### PR TITLE
aqbanking 5.6.12

### PR DESCRIPTION
**Pull request by afh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by vszakats** [comment]
Would you mind doing these URL updates to use secure protocols?:
```
homepage "https://www.aquamaniac.de/sites/home/"
```
```
head "https://git.aqbanking.de/git/aqbanking"
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Review by vszakats — CHANGES_REQUESTED** [review]
Would you mind doing these URL updates to use secure protocols?:

```
homepage "https://www.aquamaniac.de/sites/home/"
```

```
head "https://git.aqbanking.de/git/aqbanking"
```

**Comment by afh** [comment]
✅ Not at all

**Comment by vszakats** [comment]
Thank you, @afh 👍

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
