### PR TITLE
frugal 3.4.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by lembacon** [comment]
@Homebrew/core Do we want to keep adding `HEAD` in these version bump PRs?

**Comment by MikeMcQuaid** [comment]
@lembacon If the user (@chengr28 in this case) can confirm they've personally 1) tested it and 2) needed it then I'd be 👍 otherwise 👎.

**Comment by chenrui333** [comment]
I am adding these `HEAD <repo.git>` lines is just to be consistent with the other formulas. 

Regarding the testing, yeah, I have tested locally.

**Comment by MikeMcQuaid** [comment]
> I am adding these `HEAD <repo.git>` lines is just to be consistent with the other formulas.

Don't add them unless you personally use/need them, please.

**Comment by chenrui333** [comment]
I see, I will remove those HEAD lines then.

**Pull request closed without merging**
