### PR TITLE
gupnp 0.20.17

### PR DESCRIPTION
**Pull request by ilovezfs**
~~remove the patch~~ patch still needed. Responded to upstream inquiry about that here: https://github.com/GNOME/gupnp/pull/1#issuecomment-183446124

### CODE REVIEW

**Comment by ilovezfs** [comment]
Build failure is fixed with https://github.com/Homebrew/homebrew-core/pull/2185

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
@nijikon @DomT4 actually looks like the patch (https://github.com/GNOME/gupnp/pull/1) isn't needed anymore.

**Comment by ilovezfs** [comment]
Hmm looks like something was wrong with my test. Indeed still needed.

**Pull request closed without merging**
