### PR TITLE
capnp 0.6.0

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
CI failure is not my fault:

```
        ==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
Error: The 'rubocop' gem is installed but couldn't find 'rubocop' in the PATH:
```

**Comment by ilovezfs** [comment]
I blame you anyway!

**Comment by zmwangx** [comment]
Okay...

**Comment by neutric** [comment]
And I say thank you. :)

**Pull request closed without merging**
