### PR TITLE
direnv: add missing bash dependency

### PR DESCRIPTION
**Pull request by kingarrrt**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Mic92** [comment]
Motivation: the bash version that comes with macOS is quite old and does not support features that users might expect i.e. regex support.

**Comment by Mic92** [comment]
cc @zimbatm (upstream direnv maintainer)

**Comment by SMillerDev** [comment]
That sounds fine in the same way that it's fine that python scripting won't work in a lot of tools without python installed.

**Comment by Mic92** [comment]
So if you got a tool that depends on python, you don't install python because it's an optional feature?

**Review by p-linnane — APPROVED** [review]
This makes sense to me, especially given Bash 3.x will be dropped soon.

**Pull request merged**
