### PR TITLE
btop 1.3.2

### PR DESCRIPTION
**Pull request by muneebmahmed**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I saw that there have been several PRs for this formula such as #159221 and #162402 that have been closed as stale, as a failing test needs to be fixed on ARM and it does not seem anyone has been working on it. These tests have always been working on my ARM machine, so I opened this PR to be able to experiment against the GitHub runners. ~This PR should be considered a WIP until~ the tests are passing

### CODE REVIEW

**Comment by muneebmahmed** [comment]
All tests pass with a small change:
```
     assert_match "===> btop++ v.#{version}", log
     refute_match(/ERROR:/, log)
+  rescue Errno::EIO
+    # Apple silicon errors
   ensure
     Process.kill("TERM", pid)
```
However, I think this is just hiding the problem and skips the test, so I'll keep looking for a better workaround

**Comment by muneebmahmed** [comment]
macOS 13 and 14 on arm succeeded, but getting an error from macOS 12:
```
  Error: btop: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /ERROR:/ to not match "\n2024/02/20 (23:29:15) | ===> btop++ v.1.3.2\n2024/02/20 (23:29:15) | INFO: Logger set to DEBUG\n2024/02/20 (23:29:15) | WARNING: No UTF-8 locale detected! Some symbols might not display correctly.\n2024/02/20 (23:29:15) | INFO: Running on /dev/ttys001\n2024/02/20 (23:29:15) | DEBUG: get_sensors(): show_coretemp=1 check_temp=1\n2024/02/20 (23:29:15) | DEBUG: checking intel\n2024/02/20 (23:29:15) | ERROR: Exception in Shared::init() -> failed to get SMC device\n2024/02/20 (23:29:15) | INFO: Quitting! Runtime: 00:00:00\n".
```
I'll try adding a dependency on >= ventura to see if intel works

**Comment by muneebmahmed** [comment]
To summarize:
* Using either Apple or LLVM clang on Apple silicon results in this error: `DEBUG: checking intel\n2024/02/20 (23:29:15) | ERROR: Exception in Shared::init() -> failed to get SMC device`. This seems to only show up in the GitHub runners as my ARM machine shows `DEBUG: no intel sensors found` instead.
* Using Apple clang on <= Ventura results in build failures on both architectures, even when using Apple clang 15.0.0. LLVM clang works fine.
* Running on ARM results in `Errno::EIO` somewhere between the lines `(config/"btop.conf").write` and `w.write "q"` The actual test happens later when the log file is read, so it should be ok to catch and ignore this between those lines. Again, I haven't been able to reproduce this error on my ARM machine.
* The above SMC error seems to occur on ARM Monterey even when using gcc.

So, Apple clang can be used on Intel Sonoma, ARM Monterey might need to be disabled, and everything else should use gcc. If we figure out what's causing the SMC error then ARM can just be treated the same as Intel

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me. Just need to be careful with anything depending on `btop` in future (there aren't any now) because of the grief you get from throwing G++ into dependency trees.

**Pull request merged**
