### PR TITLE
pwncat 0.1.0 (new formula)

### PR DESCRIPTION
**Pull request by hurrtz**
Signed-off-by: Tobias Winkler <info@tobiaswinkler.berlin>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by srisuk2519** [comment]
เมื่อ อา. 21 มิ.ย. 2563 เวลา 18:35 Tobias Winkler <notifications@github.com>
เขียนว่า:

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/pwncat/0.1.0/bin/pwncat --version
env: python3: No such file or directory
Error: pwncat: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/pwncat/0.1.0/bin/pwncat --version
```

Checkout the other python formula, you might need to update the PATH.

**Comment by hurrtz** [comment]
> ```
> ==> /usr/local/Cellar/pwncat/0.1.0/bin/pwncat --version
> env: python3: No such file or directory
> Error: pwncat: failed
> An exception occurred within a child process:
>   BuildError: Failed executing: /usr/local/Cellar/pwncat/0.1.0/bin/pwncat --version
> ```
> 
> Checkout the other python formula, you might need to update the PATH.

This was the initial commit, can you pull the latest changes, it has been addressed already.

**Comment by chenrui333** [comment]
@hurrtz sorry for accidentally closing your PR, I was trying to help with the commits squash, but it turns out the forced PR update did close the PR. :(

No worries, I will create a new one. Couple of suggestions:
- Always squash your commits (so that we can merge it)
- Dont use master branch for your PR (create named branch like `pwncat` would be tremendously helpful)

**Comment by chenrui333** [comment]
@hurrtz, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by chenrui333** [comment]
```
$ brew install pwncat
==> Downloading https://homebrew.bintray.com/bottles/pwncat-0.1.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c1/c140bcf0cca3b1b2176e762dbbafb1c02f831c032741ece1dda4f95fa0ada397?__gda__=exp=1592771852~hmac=a24f5fd9b9377ff1b4ae3e3dc
######################################################################## 100.0%
==> Pouring pwncat-0.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/pwncat/0.1.0: 580 files, 6.7MB
```

**Pull request closed without merging**
