### PR TITLE
poppler-qt5, poppler 22.02.0

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
`poppler` needs C++17, but `pdf2djvu` needs C++11 (uses `std::auto_ptr`, which was removed in C++17). Probably needs to be reported to `pdf2djvu`.

**Comment by carlocab** [comment]
`pdf2djvu` failure needs to be reported upstream.

**Comment by carlocab** [comment]
#93653

**Comment by miccal** [comment]
FYI:
```
|-> brew livecheck poppler
poppler : 21.12.0 ==> 22.02.0
```

**Comment by carlocab** [comment]
Still blocked on `exiv2`

**Comment by carlocab** [comment]
It might be simpler to `resource` the right version of `exiv2` in `pdf2djvu` in order to unblock this.

**Comment by cho-m** [comment]
Just worked around issue by adding macro to allow libc++ to re-enable `auto_ptr` in C++17 (`_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR`). Seemed simpler than trying to make `exiv2` C++17 compliant.

GCC is fine as I think it only outputs a warning by default rather than failing on `auto_ptr` usage with C++17 standard.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
