### PR TITLE
staq 3.2.2

### PR DESCRIPTION
**Pull request by vsoftco**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by vsoftco** [comment]
Sorry for the multitude of PRs, I thought the previous were failing due to some commit issue. This uses the latest commit, and should pass (aside from the hash which I'm not sure why). Please let me know if there's anything I can help from our side. Thanks!

**Comment by vsoftco** [comment]
Any idea why the hash is different? I'm pulling the latest release. Thanks!

**Comment by vsoftco** [comment]
thanks!

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> thanks!

No worries!

**Review by p-linnane — APPROVED** [review]

**Comment by p-linnane** [comment]
@vsoftco Please do not close PR's after they are approved. We have a workflow that uploads the built bottles to GitHub Packages. The bottles in https://github.com/Homebrew/homebrew-core/pull/133447 were uploaded, and now these bottles cannot be. We will need to get the Homebrew organization owners involved to remove the incorrect bottles.

**Comment by vsoftco** [comment]
My apologies for this, won't happen again.

**Review by p-linnane — APPROVED** [review]

**Comment by p-linnane** [comment]
Incorrect bottles have been removed.

**Pull request merged**
