### PR TITLE
minipro: update sha

### PR DESCRIPTION
**Pull request by InPermutation**
```console
% curl --silent https://gitlab.com/DavidGriffith/minipro/-/archive/0.7/minipro-0.7.tar.gz | sha256sum
54eb59f5fe2e1850f08baaefcf2306ed770f7cdb91b3f58e8610849334a5a6f4  -
```

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@InPermutation can you raise an issue to check if there was re-tagging? Thanks!

**Comment by chenrui333** [comment]
raised an issue, https://gitlab.com/DavidGriffith/minipro/-/issues/317

**Comment by InPermutation** [comment]
Thanks, haven’t had the free time to get back to this.

**Comment by DavidGriffith** [comment]
There wasn't any retagging.  The problem is that on my machines at home I have these lines in my `.gitconfig`:

````
[core]
        abbrev = 8
````

This changes what goes into `GIT_HASH_SHORT` in `Makefile` from seven characters long to eight.  I'm not sure why I did that or when.  This means when I type `make dist` for version 0.7, `GIT_HASH_SHORT` contains `9f268f83`.  When done on some other machine without `abbrev` set that way, or by Gitlab, it contains `9f268f8`.

I'll edit `Makefile` to fix the length of that hash and tag a new release, perhaps 0.7.1.

**Comment by chenrui333** [comment]
Thanks @DavidGriffith!

**Review by chenrui333 — APPROVED** [review]

**Comment by DavidGriffith** [comment]
There's still a problem.  I can't get the hash from `git archive` to match what I get from downloading the tarball directly.  The underlying tar file is exactly the same.  I asked about how to deal with this over at https://stackoverflow.com/questions/78951285/getting-from-gitlab-the-exact-same-archive-i-get-from-using-git-archive.  Someone posted a link to something at Github (not Gitlab) about (what I got out of it) that Github can no longer guarantee hashes will remain constant.

Something that WOULD remain constant is if you could somehow get a hash of the underlying tar, but I'm pretty sure that getting Homebrew to do that is very nontrivial.  What are you guys doing with this phenomenon happening with other programs?

**Pull request merged**
