### PR TITLE
urdfdom 4.0.0, depend on tinyxml2

### PR DESCRIPTION
**Pull request by scpeters**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This version of `urdfdom` now depends on `tinyxml2` instead of `tinyxml`.

### CODE REVIEW

**Comment by scpeters** [comment]
I'm looking into the dartsim failure; sorry I didn't build that before opening the PR

**Comment by scpeters** [comment]
> I'm looking into the dartsim failure; sorry I didn't build that before opening the PR

I've submitted a patch in https://github.com/dartsim/dart/pull/1779 to fix the dartsim build. I'll wait for some maintainer feedback before using it here

**Comment by scpeters** [comment]
> > I'm looking into the dartsim failure; sorry I didn't build that before opening the PR
> 
> I've submitted a patch in [dartsim/dart#1779](https://github.com/dartsim/dart/pull/1779) to fix the dartsim build. I'll wait for some maintainer feedback before using it here

the patch is in https://github.com/Homebrew/homebrew-core/pull/159018

**Comment by SMillerDev** [comment]
> The formula version (4.0.0) is newer than the version from `brew livecheck` (3.0.0).

Doesn't seem like you made an actual release upstream yet.

**Comment by scpeters** [comment]
> > The formula version (4.0.0) is newer than the version from `brew livecheck` (3.0.0).
> 
> Doesn't seem like you made an actual release upstream yet.

we created a tag, which is our typical release process. In the past I had experimented with creating a few Release entries, but that hasn't been consistent; usually we just create a tag. Is it required to create a Release entry in order for a tag to not be recognized as a prerelease?

**Comment by samford** [comment]
Per the discussion on Slack, I modified the `urdfdom` commit to update the `livecheck` block to check tags using the standard regex for Git tags like `1.2.3`/`v1.2.3` (avoiding other tags in the repository like `robot_model-1.7.1`). This aligns the check with the current release process and returns 4.0.0, as expected.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
