### PR TITLE
opencv 4.5.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by cho-m** [comment]
`siril` needs revision bump too as upstream changed lib versioning to match ABI incompatibility in v4.x https://github.com/opencv/opencv/pull/21178 (now has `*.405.dylib` and `*.4.5.5.dylib` on macOS)

```
Full linkage --test siril output
  Broken dependencies:
    /opt/homebrew/opt/opencv/lib/libopencv_calib3d.4.5.dylib (opencv)
    /opt/homebrew/opt/opencv/lib/libopencv_core.4.5.dylib (opencv)
    /opt/homebrew/opt/opencv/lib/libopencv_imgproc.4.5.dylib (opencv)
```

**Comment by branchvincent** [comment]
rebased due to a `caffee` conflict

**Comment by SMillerDev** [comment]
caffe
```
  CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Atlas (missing: Atlas_CLAPACK_INCLUDE_DIR
    Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY)
```

visp
```
   In file included from /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/Core:162:0,
                   from /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/Dense:1,
                   from /tmp/visp-20220223-243424-1dnr3x0/visp-3.5.0/modules/core/include/visp3/core/vpEigenConversion.h:41,
                   from /tmp/visp-20220223-243424-1dnr3x0/visp-3.5.0/modules/core/src/math/matrix/vpEigenConversion.cpp:37:
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:504:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type
     typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                           ^
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:504:38: error: expected unqualified-id before ‘<’ token
     typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                                        ^
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:505:31: error: ‘type1’ was not declared in this scope
     typedef typename remove_all<type1>::type type;
                                 ^
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:505:36: error: template argument 1 is invalid
     typedef typename remove_all<type1>::type type;
                                      ^
  In file included from /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/Core:162:0,
                   from /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/Dense:1,
                   from /tmp/visp-20220223-243424-1dnr3x0/visp-3.5.0/modules/core/include/visp3/core/vpEigenConversion.h:41,
                   from /tmp/visp-20220223-243424-1dnr3x0/visp-3.5.0/modules/core/src/math/matrix/vpEigenConversion.cpp:37:
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:616:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type
     typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                           ^
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:616:38: error: expected unqualified-id before ‘<’ token
     typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                                        ^
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:617:31: error: ‘type1’ was not declared in this scope
     typedef typename remove_all<type1>::type type;
                                 ^
  /home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3/Eigen/src/Core/util/Meta.h:617:36: error: template argument 1 is invalid
     typedef typename remove_all<type1>::type type;
                                      ^
```

**Comment by cho-m** [comment]
`caffe` and `visp` aren't bottled on Linux, so those can be ignored here and fixed separately.

Failure may be temporary network issue:
```
==> brew audit opencv --online --git --skip-style
==> FAILED
Full audit opencv --online --git --skip-style output
  opencv:
    * The homepage URL https://opencv.org/ is not reachable
  Error: 1 problem in 1 formula detected
  Error: The homepage URL https://opencv.org/ is not reachable
```

**Comment by cho-m** [comment]
May want to look into #95811 here since `mlt` is already getting revision bumped.

**Review by branchv — APPROVED** [review]

**Pull request closed without merging**
