### PR TITLE
poac: fix Catalina build

### PR DESCRIPTION
**Pull request by ken-matsui**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Related to: https://github.com/Homebrew/homebrew-core/pull/104013

### CODE REVIEW

**Comment by ken-matsui** [comment]
Hi @carlocab,

If my understanding is correct, your change can now be built successfully on Catalina with the new release in 0.3.10.

**Comment by ken-matsui** [comment]
Are completions no longer needed installing explicitly?

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
> If my understanding is correct, your change can now be built successfully on Catalina with the new release in 0.3.10.

Thanks! This does seem to work now.

> Are completions no longer needed installing explicitly?

It's not that -- the existing code to install completions is wrong. They're currently installing broken symlinks (they point to a nonexistent location), and just get removed by `brew` (since `brew` prunes broken symlinks). I haven't had the chance to work out how to fix it yet (or whether it needs fixing it at all other than removal).

**Comment by ken-matsui** [comment]
> Thanks! This does seem to work now.

That's good to know. Thank you!

> It's not that -- the existing code to install completions is wrong. They're currently installing broken symlinks (they point to a nonexistent location), and just get removed by `brew` (since `brew` prunes broken symlinks). I haven't had the chance to work out how to fix it yet (or whether it needs fixing it at all other than removal).

What about doing the following?

```rb
    cp "src/etc/poac.bash", "src/etc/poac.zsh"
    bash_completion.install "src/etc/poac.bash" => "poac"
    zsh_completion.install "src/etc/poac.zsh" => "_poac"
```

**Comment by carlocab** [comment]
That would work, but let's try
```ruby
bash_completion.install "src/etc/poac.bash" => "poac"
zsh_completion.install_symlink bash_completion/"poac" => "_poac"
```

**Comment by ken-matsui** [comment]
Thanks!

**Pull request closed without merging**
