### PR TITLE
gdal 3.7.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
pdal build failure
```
  /tmp/pdal-20230511-67873-1dnf5de/PDAL-2.5.3-src/pdal/Geometry.cpp:156:26: error: cannot initialize a variable of type 'OGRSpatialReference *' with an rvalue of type 'const OGRSpatialReference *'
      OGRSpatialReference *srs = m_geom->getSpatialReference();
                           ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /tmp/pdal-20230511-67873-1dnf5de/PDAL-2.5.3-src/pdal/Geometry.cpp:175:26: error: cannot initialize a variable of type 'OGRSpatialReference *' with an rvalue of type 'const OGRSpatialReference *'
      OGRSpatialReference *inSrs = m_geom->getSpatialReference();
                           ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 errors generated.
```

**Comment by fxcoudert** [comment]
See https://github.com/PDAL/PDAL/pull/4030
We could apply https://github.com/PDAL/PDAL/commit/7b4b2d942bc0390d370d5b90f31daf77148005f6 or one of its backported versions

**Comment by t0b3** [comment]
beware https://github.com/PDAL/PDAL/pull/4043

**Comment by fxcoudert** [comment]
@t0b3 https://github.com/PDAL/PDAL/pull/4043 just makes the fix “nicer” in principle, but there is no bug exposed or behaviour that could be triggered by using the first fix

**Comment by chenrui333** [comment]
doing a rerun

**Comment by e-n-f** [comment]
I opened another PR, https://github.com/Homebrew/homebrew-core/pull/132095, before realizing that this one had been reopened. If you merge this one instead of mine, could you add the `libarchive` dependency from mine, which is necessary for `/vsi7z` and `/vsirar`? Thanks!

**Comment by carlocab** [comment]
Rev bumps cherry-picked onto #132095.

**Comment by chenrui333** [comment]
#134485

**Pull request closed without merging**
