### PR TITLE
geos 3.5.1

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
osm2pgsql failing on all platforms: https://bot.brew.sh/job/Homebrew%20Core/13031/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_osm2pgsql/

The other failures look spurious.

**Comment by nijikon** [comment]
Lets bump to 3.5.1 for now

**Comment by ilovezfs** [comment]
do we still need revision bumps then?

**Comment by nijikon** [comment]
I can try to run it without bumps.

**Comment by ilovezfs** [comment]
looks like everyone was happy except osm2pgsql

**Pull request closed without merging**
