### PR TITLE
juliaup 1.5.30

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
We probably want to add `--features no-self-update` as in `rustup` and `elan` here.

**Comment by davidanthoff** [comment]
Can we please not manually do these PRs? I have setup `juliaup` now that it automatically updates the brew formula as part of the github release workflow (see [here](https://github.com/JuliaLang/juliaup/blob/f698dcecbb265d214cde7dfcafdf53156647deb9/.github/workflows/release.yml#L403)), but that fails with a duplicate warning if someone else opens manual PRs here (like this https://github.com/JuliaLang/juliaup/runs/4893668610?check_suite_focus=true).

Also, just because there is a new tag in the `juliaup` repo does _not_ mean that we have a new release that should appear here in brew. There are many builds tagged with a version in the `juliaup` repo that are extremely experimental and should under no circumstances be shipped here. We use a concept of channels, where we promote individual (tagged) builds into various release channels/stages as they pass various quality gates. By integrating the `bump-formula-pr` into the GitHub workflow over at juliaup we avoid all of these problems because the brew update just becomes part of the regular release process.

@carlocab is there some way to indicate to others that they should not manually open PRs that update the juliaup formula?

> We probably want to add `--features no-self-update` as in `rustup` and `elan` here.

Are you referring to a brew concept here, or to the way `cargo` is called? There is no feature `no-self-update` in the juliaup crate.

**Comment by davidanthoff** [comment]
Oh, and now I can only test the auto brew update once someone closes this PR here, because the github action is not working as long as there are manual PRs open here. Could someone close this PR, and then I'll kick of another attempt for the automatic process to test that.

**Comment by SMillerDev** [comment]
> Can we please not manually do these PRs?

No, anyone in the Homebrew community can make pull requests to update software, in fact we encourage it.

> Also, just because there is a new tag in the juliaup repo does not mean that we have a new release that should appear here in brew.

Could you help determine which ones should be by making a PR that adds a livecheck block?

> Are you referring to a brew concept here, or to the way cargo is called? There is no feature no-self-update in the juliaup crate.

The way cargo is called, we want to avoid software auto-updating.

**Comment by carlocab** [comment]
> @carlocab is there some way to indicate to others that they should not manually open PRs that update the juliaup formula?

Not really. It seems the issue is that we're picking up what you've labelled as the [latest release](https://github.com/JuliaLang/juliaup/releases/tag/v1.5.31) on GitHub but isn't actually intended as a release. As Sean suggests above, we probably need a `livecheck` block to pick up which tags are proper releases. Without one, any contributor to homebrew-core might update this when they see `brew livecheck juliaup` return a potential version bump.
 
> > We probably want to add `--features no-self-update` as in `rustup` and `elan` here.
> 
> Are you referring to a brew concept here, or to the way `cargo` is called? There is no feature `no-self-update` in the juliaup crate.

I vaguely recall seeing `#[cfg(feature = "selfupdate")]` in the source -- does that feature not apply? That said, I don't really use Rust so I could be misunderstanding what these do 🙂

**Comment by davidanthoff** [comment]
Ah, understood! What I'm trying now is to mark these releases on github as prerelease. Would that be enough, or do we then still need a custom livecheck?

> I vaguely recall seeing #[cfg(feature = "selfupdate")] in the source -- does that feature not apply?

You need to explicitly add that feature to add self update functionality, so the existing compile step should be correct and won't include the self-update features in the brew distributed version.

**Comment by carlocab** [comment]
> Ah, understood! What I'm trying now is to mark these releases on github as prerelease. Would that be enough, or do we then still need a custom livecheck?
> 

Yes, but a simple one that specifies the strategy as `:github_latest` should suffice.

> 
> > I vaguely recall seeing #[cfg(feature = "selfupdate")] in the source -- does that feature not apply?
> 
> 
> 
> You need to explicitly add that feature to add self update functionality, so the existing compile step should be correct and won't include the self-update features in the brew distributed version.
> 
> 

Great, thanks for clarifying!

**Comment by davidanthoff** [comment]
> Yes, but a simple one that specifies the strategy as `:github_latest` should suffice.

So do I just add
```
livecheck do
  strategy :github_latest
end
```

before the `bottle do` line? A lot of the existing formulas also seem to have a line `url :stable` in there, not clear to me what that is?

@carlocab or maybe you could add that part? I have a Mac, but it is quite painful for me to do anything on there because everything is so unfamiliar. Also, could you close this PR here? We definitely don't want to merge this one.

**Pull request closed without merging**
