### PR TITLE
copilot 0.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
timing issue for 10.14 and 10.13 builds:

```
==> brew audit copilot --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
copilot:
  * v0.4.0 is a GitHub pre-release.
```

rerun now

**Comment by Rylan12** [comment]
Wait, so is this a prerelease? It doesn't look like it according to the [release page](https://github.com/aws/copilot-cli/releases/tag/v0.4.0)

**Comment by chenrui333** [comment]
> Wait, so is this a prerelease? It doesn't look like it according to the [release page](https://github.com/aws/copilot-cli/releases/tag/v0.4.0)

yeah, it was prerelease until they flipped the status (build timing issue. :) )

**Comment by Rylan12** [comment]
Gotcha

**Review by Rylan12 — APPROVED** [review]

**Pull request closed without merging**
