### PR TITLE
fltk: fix library operation on Mojave.

### PR DESCRIPTION
**Pull request by crmoore**
Fix backported from fltk repository

 #35682 #35664

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you also add a `revision 1` underneath the version? It'll rebuild the bottle for everyone.

**Comment by SMillerDev** [comment]
I'll leave the rest of this for @fxcoudert or others to decide since I don't know much about the issue or the patch.

**Comment by fxcoudert** [comment]
Why is it failing, it's the exact same patch?

**Comment by fxcoudert** [comment]
Hosting the patch outside the formula for easier maintenance. Other than that, the failure is important enough that we really want to fix it, so: approve.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @crmoore

**Pull request closed without merging**
