### PR TITLE
reposurgeon 4.15

### PR DESCRIPTION
**Pull request by Moisan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
only failed in high-sierra:

```
Testing reposurgeon
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200628-81919-1ell9rp.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/reposurgeon.rb --verbose
==> git init
Initialized empty Git repository in /private/tmp/reposurgeon-test-20200628-81920-9d2gci/.git/
==> git commit --allow-empty --message brewing
[master (root-commit) e4d647f] brewing
==> script -q /dev/null /usr/local/Cellar/reposurgeon/4.14/bin/reposurgeon read list
Error: reposurgeon: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </brewing/> was expected to be =~
<"^D\b\b">.
```

**Comment by bval** [comment]
I believe this is happening because [10.13 ships with git 2.17.2](https://github.com/Homebrew/homebrew-core/pull/57016/checks?check_run_id=814961397#step:5:39) and reposurgeon now [requires git 2.19.2 or later](https://gitlab.com/esr/reposurgeon/-/blob/master/INSTALL.adoc#user-content-prerequisites).

I believe the right way to fix this is to add `depends_on :macos => :mojave` to the Formula rather than requiring a newer version of git.

**Comment by bval** [comment]
> I believe the right way to fix this is to add `depends_on :macos => :mojave` to the Formula rather than requiring a newer version of git.

Scratch that. Thinking about linux support as well we probably need to add an explicit dependency on git. Who knows what versions are out there.

**Review by SeekingMeaning — APPROVED** [review]

**Comment by Moisan** [comment]
Thanks @bval for the pointer!

**Pull request closed without merging**
