### PR TITLE
Add :any_skip_relocation for kubernetes-cli bottle

### PR DESCRIPTION
**Pull request by errordeveloper**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by errordeveloper** [comment]
Please help me understand what's the issue here. I'm trying to compare this formula to `kops` and `kubernetes-helm`, but not sure why there `cellar :any_skip_relocation` gets set automatically and doesn't happen here.

> ...this is either a brew bug (which should be reported) or a problem in the way that the formula is built.

Let's assume it's a bug in the formula, how can I determine what it could be related to? I'm new to Homebrew.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bottle.rb#L287-L289

That code would need to be generalized to include the go@ formulae as well.

So this will resolve itself once kubernetes-cli goes back to using `depends_on "go"` instead of `depends_on "go@1.9"`.

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ brew install --build-bottle kubernetes-cli
==> Installing dependencies for kubernetes-cli: go@1.9
==> Installing kubernetes-cli dependency: go@1.9
==> Downloading https://homebrew.bintray.com/bottles/go@1.9-1.9.7.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring go@1.9-1.9.7.el_capitan.bottle.tar.gz
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go@1.9/libexec/bin

This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/go@1.9/bin:$PATH"' >> ~/.bash_profile

==> Summary
🍺  /usr/local/Cellar/go@1.9/1.9.7: 7,668 files, 294.2MB
==> Installing kubernetes-cli
==> Cloning https://github.com/kubernetes/kubernetes.git
Cloning into '/Users/joe/Library/Caches/Homebrew/kubernetes-cli--git'...
remote: Counting objects: 19041, done.
remote: Compressing objects: 100% (14953/14953), done.
remote: Total 19041 (delta 6484), reused 9402 (delta 3491), pack-reused 0
Receiving objects: 100% (19041/19041), 24.80 MiB | 7.94 MiB/s, done.
Resolving deltas: 100% (6484/6484), done.
Note: checking out '5ca598b4ba5abb89bb773071ce452e33fb66339d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (16518/16518), done.
==> Checking out tag v1.10.4
==> make generated_files
==> make kubectl
==> hack/generate-docs.sh
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall kubernetes-cli`
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kubernetes-cli/1.10.4: 178 files, 52.8MB, built in 4 minutes 10 seconds
iMac-TMP:~ joe$ brew bottle -dv kubernetes-cli
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
==> Determining kubernetes-cli bottle rebuild...
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
==> Bottling kubernetes-cli-1.10.4.el_capitan.bottle.1.tar.gz...
tar cf /Users/joe/kubernetes-cli-1.10.4.el_capitan.bottle.1.tar kubernetes-cli/1.10.4
gzip -f kubernetes-cli-bottle.tar
==> Detecting if kubernetes-cli-1.10.4.el_capitan.bottle.1.tar.gz is relocatable...
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/kubernetes-cli/1.10.4/bin/kubectl
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec1110223024625156540423631668090820312555511151231257827021181583404541015625All types must be pointers to structs.Current Number of Nodes Scheduled: %d' at offset 0x143e9a5
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/xml/typeinfo.go' at offset 0x1ed7869
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/xml/xml.go' at offset 0x1ed78ae
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/xml/read.go' at offset 0x1ed78ee
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/xml/marshal.go' at offset 0x1ed792f
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/cookiejar/punycode.go' at offset 0x1ed7973
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/cookiejar/jar.go' at offset 0x1ed79be
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/tar/writer.go' at offset 0x1edca4a
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/tar/strconv.go' at offset 0x1edca8c
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/tar/stat_atimespec.go' at offset 0x1edcacf
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/tar/stat_unix.go' at offset 0x1edcb19
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/tar/reader.go' at offset 0x1edcb5e
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/tar/format.go' at offset 0x1edcba0
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/tar/common.go' at offset 0x1edcbe2
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/zip/writer.go' at offset 0x1edf9d8
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/zip/struct.go' at offset 0x1edfa1a
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/zip/register.go' at offset 0x1edfa5c
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/archive/zip/reader.go' at offset 0x1edfaa0
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/os/executable.go' at offset 0x1ee086e
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/expvar/expvar.go' at offset 0x1ee6339
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/text/tabwriter/tabwriter.go' at offset 0x1ee9ab5
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/strings/compare.go' at offset 0x1ef0d3f
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/httputil/httputil.go' at offset 0x1f0528e
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/httputil/reverseproxy.go' at offset 0x1f052d8
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/httputil/persist.go' at offset 0x1f05326
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/httputil/dump.go' at offset 0x1f0536f
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/container/heap/heap.go' at offset 0x1f05636
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/zlib/writer.go' at offset 0x1f05861
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/zlib/reader.go' at offset 0x1f058a5
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/hash/adler32/adler32.go' at offset 0x1f058e9
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/runtime/debug/stack.go' at offset 0x1f0cb9c
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/runtime/debug/garbage.go' at offset 0x1f0cbdf
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/parser/parser.go' at offset 0x1f0d516
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/doc/reader.go' at offset 0x1f0d556
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/doc/example.go' at offset 0x1f0d593
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/doc/comment.go' at offset 0x1f0d5d1
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/ast/scope.go' at offset 0x1f0d60f
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/ast/ast.go' at offset 0x1f0d64b
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/token/token.go' at offset 0x1f0d685
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/go/token/position.go' at offset 0x1f0d6c3
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/math/pow10.go' at offset 0x1f0e396
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/json/tags.go' at offset 0x1f0f7e1
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/json/stream.go' at offset 0x1f0f823
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/json/indent.go' at offset 0x1f0f867
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/json/fold.go' at offset 0x1f0f8ab
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/json/encode.go' at offset 0x1f0f8ed
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/unicode/utf16/utf16.go' at offset 0x1f0f931
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/json/scanner.go' at offset 0x1f0f974
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/encoding/json/decode.go' at offset 0x1f0f9b9
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/transport.go' at offset 0x1f0faab
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/sniff.go' at offset 0x1f0faed
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/server.go' at offset 0x1f0fb2b
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/transfer.go' at offset 0x1f0fb6a
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/response.go' at offset 0x1f0fbab
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/http.go' at offset 0x1f0fbec
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/status.go' at offset 0x1f0fc29
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/h2_bundle.go' at offset 0x1f0fc68
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/header.go' at offset 0x1f0fcaa
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/fs.go' at offset 0x1f0fce9
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/cookie.go' at offset 0x1f0fd24
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/request.go' at offset 0x1f0fd63
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/client.go' at offset 0x1f0fda3
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/proxy/direct.go' at offset 0x1f0fde2
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/proxy/socks5.go' at offset 0x1f0fe36
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/internal/chunked.go' at offset 0x1f0fe8a
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/lex/httplex/httplex.go' at offset 0x1f0fed3
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/idna/trie.go' at offset 0x1f0ff2e
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/idna/tables.go' at offset 0x1f0ff7f
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/idna/punycode.go' at offset 0x1f0ffd2
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/idna/trieval.go' at offset 0x1f10027
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/idna/idna.go' at offset 0x1f1007b
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/trie.go' at offset 0x1f100cc
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/transform.go' at offset 0x1f10126
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/tables.go' at offset 0x1f10185
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/readwriter.go' at offset 0x1f101e1
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/normalize.go' at offset 0x1f10241
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/iter.go' at offset 0x1f102a0
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/input.go' at offset 0x1f102fa
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/forminfo.go' at offset 0x1f10355
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/norm/composition.go' at offset 0x1f103b3
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/secure/bidirule/bidirule.go' at offset 0x1f10414
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/bidi/trieval.go' at offset 0x1f10475
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/bidi/tables.go' at offset 0x1f104d2
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/unicode/bidi/prop.go' at offset 0x1f1052e
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/text/transform/transform.go' at offset 0x1f10588
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/http2/hpack/huffman.go' at offset 0x1f105e4
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/http2/hpack/hpack.go' at offset 0x1f1063f
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/http2/hpack/tables.go' at offset 0x1f10698
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/vendor/golang_org/x/net/http2/hpack/encode.go' at offset 0x1f106f2
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/net/http/httptrace/trace.go' at offset 0x1f1074c
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/gzip/gzip.go' at offset 0x1f10794
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/gzip/gunzip.go' at offset 0x1f107d6
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/hash/crc32/crc32_amd64.s' at offset 0x1f1081a
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/hash/crc32/crc32_generic.go' at offset 0x1f1085f
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/hash/crc32/crc32_amd64.go' at offset 0x1f108a7
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/hash/crc32/crc32.go' at offset 0x1f108ed
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/flate/inflate.go' at offset 0x1f1092d
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/flate/dict_decoder.go' at offset 0x1f10973
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/flate/deflatefast.go' at offset 0x1f109be
 --> match '/usr/local/Cellar/go@1.9/1.9.7/libexec/src/compress/flate/huffman_code.go' at offset 0x1f10a08
Only the first 100 matches were output

./kubernetes-cli-1.10.4.el_capitan.bottle.1.tar.gz
  bottle do
    rebuild 1
    sha256 "420b1c19779ab4aad35442da6736d6982be5015c23156b25aa296704faf6be6f" => :el_capitan
  end
iMac-TMP:~ joe$
```

**Comment by errordeveloper** [comment]
@ilovezfs see https://github.com/Homebrew/brew/pull/4348

**Pull request closed without merging**
