### PR TITLE
terragrunt 0.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> go build -o /usr/local/Cellar/terragrunt/0.3.0/bin/terragrunt -ldflags -X main.VERSION=0.3.0
src/github.com/gruntwork-io/terragrunt/remote/remote_state_s3.go:4:2: cannot find package "github.com/mitchellh/mapstructure" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/github.com/mitchellh/mapstructure (from $GOROOT)
	/private/tmp/terragrunt-20161128-37579-1a3dupf/terragrunt-0.3.0/src/github.com/mitchellh/mapstructure (from $GOPATH)

```

**Comment by Ninir** [comment]
@ilovezfs could you check the build status please?

**Comment by ilovezfs** [comment]
@Ninir I fixed it.

**Comment by Ninir** [comment]
@ilovezfs Thanks :)

**Pull request closed without merging**
