### PR TITLE
update xmake to v2.3.1

### PR DESCRIPTION
**Pull request by waruqi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you squash your commits?

**Comment by waruqi** [comment]
> Can you squash your commits?

ok

**Comment by SMillerDev** [comment]
And can you use the commit message `<formula name> <new version number>`.

**Comment by waruqi** [comment]
I have modified the commit message.

**Comment by waruqi** [comment]
ci fails. 

```
 Setup tap46s
##[error]Process completed with exit code 128.
Run git -C $(brew --repo) remote set-url origin https://github.com/Homebrew/brew
fatal: remote error: upload-pack: not our ref 1f6b68487d526a7df034e022a733a59e5942ab7a
fatal: The remote end hung up unexpectedly
##[error]Process completed with exit code 128.
```

**Comment by SMillerDev** [comment]
Thanks @waruqi! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by waruqi** [comment]
I need fix package shasum for this version.

**Pull request closed without merging**
