### PR TITLE
ansible@2.2: 2.2.2.0 (new formula)

### PR DESCRIPTION
**Pull request by dentarg**
This is ansible.rb from 339af3801cd3fc12174d728978804739d0af70e8 + 'keg_only :versioned_formula'.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

> Have you followed the guidelines for contributing?

Not really, as the instructions didn't really match what I wanted to do (just add the previous working formula for ansible 2.2 as `ansible@2.2`).

> Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?

No, but I did

```
$ brew tap dentarg/brew
$ brew install ansible@2.2
```

Full log from the install command can be seen at https://gist.github.com/dentarg/d71f3d85eeca6ba0d4a59b16c0137ba7

> Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

No, but I suspect that's because it's from my tap?

```
$ brew audit --strict ansible@2.2
Error: Error running `rubocop --format json --force-exclusion --config /usr/local/Homebrew/Library/.rubocop.yml /usr/local/Homebrew/Library/Taps/dentarg/homebrew-brew/Formula/ansible@2.2.rb`
```

### CODE REVIEW

**Comment by dentarg** [comment]
Tried the rubocop command manually:

```
$ rubocop --format json --force-exclusion --config /usr/local/Homebrew/Library/.rubocop.yml /usr/local/Homebrew/Library/Taps/dentarg/homebrew-brew/Formula/ansible@2.2.rb
{"metadata":{"rubocop_version":"0.47.1","ruby_engine":"ruby","ruby_version":"2.2.6","ruby_patchlevel":"396","ruby_platform":"x86_64-darwin15"},"files":[{"path":"../../../../usr/local/Homebrew/Library/Taps/dentarg/homebrew-brew/Formula/ansible@2.2.rb","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}
```

**Comment by dentarg** [comment]
Direct link to my tap: https://github.com/dentarg/homebrew-brew

**Comment by fxcoudert** [comment]
We already have versioned formulas for `ansible@1.9` and `ansible@2.0`. What is the rationale to add another one? Homebrew's goal is not too maintain all versions of software.

**Comment by dentarg** [comment]
> We already have versioned formulas for ansible@1.9 and ansible@2.0. What is the rationale to add another one?

There are breaking changes in Ansible 2.3. https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#23-ramble-on---2017-04-12 Playbook that ran fine with 2.2 does not with 2.3.

Even the minor changes are breaking, e.g.:

> The version and release facts for OpenBSD hosts were reversed. This has been changed so that version has the numeric portion and release has the name of the release.

**Comment by fxcoudert** [comment]
Is Ansible 2.2 maintained and supported by upstream? i.e. will there be new releases on this code branch with fixes for security issues and/or bugs?

**Comment by dentarg** [comment]
> Is Ansible 2.2 maintained and supported by upstream? i.e. will there be new releases on this code branch with fixes for security issues and/or bugs?

I think so, until 2.4 is released, http://docs.ansible.com/ansible/dev_guide/developing_releases.html#support-for-older-releases says

> Ansible supports the two most recent major, stable releases. Security- and bug-related fixes may be implemented in older versions, but this support is not guaranteed.

**Comment by ilovezfs** [comment]
Have you attempted to use `ansible@2.0`?

**Comment by dentarg** [comment]
@ilovezfs not really, I will try it and report back how it goes

**Comment by ilovezfs** [comment]
@dentarg thanks a lot!

**Comment by dentarg** [comment]
@ilovezfs I searched our issues and found a number of fixed bugs and added features since 2.0, that we rely on:

* [apt module](http://docs.ansible.com/ansible/apt_module.html) 
  * `autoremove`, added in 2.1
  * [ability to download deb from url](https://github.com/ansible/ansible-modules-core/commit/b0db35a369b0b0462a82e100d2adc16244f65a6c), added in 2.1
* [win_chocolatey](http://docs.ansible.com/ansible/win_chocolatey_module.html#options) 
  * `params` added in 2.1
* [Allow an empty password when adding a new MySQL user](https://github.com/ansible/ansible-modules-core/pull/3445/files)
  * 2.0 looks unchanged in this regard: https://github.com/ansible/ansible-modules-core/blob/stable-2.0/database/mysql/mysql_user.py

**Comment by dentarg** [comment]
With that said, I don't think what I've done in this PR works correctly. I noticed this in the caveats for `ansible@2.0`:

>Homebrew writes wrapper scripts that set PYTHONPATH in ansible's
>execution environment, which is inherited by Python scripts invoked
>by ansible. If this causes problems, you can modify your playbooks
>to invoke python with -E, which causes python to ignore PYTHONPATH.

I think that needs to be done here. I will try to get more time to work on this.

**Comment by ilovezfs** [comment]
@dentarg any update here?

**Comment by dentarg** [comment]
@ilovezfs sorry, no news here, I haven't been able to work on this. TBH I don't know when I will be, I might just spend the time on making may playbooks work with Ansible 2.3. Let me know it you want me to close the PR.

**Comment by ilovezfs** [comment]
@dentarg no problem. Let's close the PR for now, but feel free to re-open if you decide against 2.3.

**Pull request closed without merging**
