### PR TITLE
webkitgtk 2.14.1

### PR DESCRIPTION
**Pull request by tschoonj**
This will be fun...

### CODE REVIEW

**Comment by DomT4** [comment]
Good luck with this one. I tried a few times, it broke in a new way after every attempted fix and so I gave up and hoped you'd notice it 😄.

**Comment by tschoonj** [comment]
Thanks! I managed to get it compiling apart from the gobject-introspection bindings on my El Cap machine. If this works fine on the Yosemite bot, I will be able to confirm it's an SIP/python issue...

**Comment by MikeMcQuaid** [comment]
@tschoonj Feel free to ship an older version. Newest > newer > older 😁

**Comment by ilovezfs** [comment]
@tschoonj Just to be clear that means dropping introspection support even if we "only" ship 2.14.1, right?

**Comment by tschoonj** [comment]
Yep, but the gobject-introspection stuff never worked in 2.10.9 anyway (https://github.com/Homebrew/legacy-homebrew/issues/47000)

**Pull request closed without merging**
