### PR TITLE
binutils 2.37

### PR DESCRIPTION
**Pull request by xxyzz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
Thanks, @xxyzz.

**Comment by carlocab** [comment]
Looks like lots of things are broken on Linux.

<details><summary>Error: 513 failed steps!</summary>
<p>

```
Error: 513 failed steps!
brew install --only-dependencies abcl
brew test --retry --verbose abcl
brew test --retry --verbose abyss
brew install --only-dependencies --include-test acme
brew test --retry --verbose acme
brew install --only-dependencies adios2
brew linkage --test adios2
brew test --retry --verbose adios2
brew test --retry --verbose afflib
brew test --retry --verbose aide
brew test --retry --verbose alot
brew test --retry --verbose alpine
brew install --only-dependencies amtk
brew test --retry --verbose amtk
brew test --retry --verbose ansible
brew test --retry --verbose ansible-lint
brew test --retry --verbose ansible@2.9
brew test --retry --verbose apache-arrow
brew test --retry --verbose apache-arrow-glib
brew test --retry --verbose arcade-learning-environment
brew test --retry --verbose armadillo
brew linkage --test arpack
brew test --retry --verbose arpack
brew test --retry --verbose arss
brew test --retry --verbose as-tree
brew test --retry --verbose aspectj
brew test --retry --verbose asroute
brew test --retry --verbose asuka
brew test --retry --verbose asymptote
brew test --retry --verbose atomicparsley
brew test --retry --verbose atuin
brew test --retry --verbose authoscope
brew test --retry --verbose aws-elasticbeanstalk
brew test --retry --verbose awscli
brew test --retry --verbose awscli@1
brew test --retry --verbose awscurl
brew test --retry --verbose b3sum
brew test --retry --verbose babl
brew test --retry --verbose bandwhich
brew test --retry --verbose bat
brew test --retry --verbose bcftools
brew test --retry --verbose beagle
brew test --retry --verbose bear
brew test --retry --verbose bibtexconv
brew test --retry --verbose binaryen
brew test --retry --verbose bingrep
brew test --retry --verbose binwalk
brew test --retry --verbose biosig
brew test --retry --verbose blaze
brew install --only-dependencies --include-test bnfc
brew test --retry --verbose bnfc
brew test --retry --verbose boost-python3
brew test --retry --verbose boringtun
brew test --retry --verbose buku
brew test --retry --verbose bzt
brew test --retry --verbose caf
brew test --retry --verbose calceph
brew test --retry --verbose cargo-c
brew test --retry --verbose cargo-watch
brew test --retry --verbose castxml
brew test --retry --verbose cbc
brew test --retry --verbose ccls
brew test --retry --verbose ceres-solver
brew test --retry --verbose certbot
brew test --retry --verbose cfr-decompiler
brew test --retry --verbose cgl
brew install --only-dependencies chafa
brew test --retry --verbose chafa
brew test --retry --verbose charm-tools
brew test --retry --verbose chars
brew test --retry --verbose check_postgres
brew test --retry --verbose choose-rust
brew test --retry --verbose clib
brew test --retry --verbose click
brew test --retry --verbose cloudformation-guard
brew test --retry --verbose clp
brew test --retry --verbose cmdshelf
brew test --retry --verbose cobalt
brew test --retry --verbose code-minimap
brew test --retry --verbose cogl
brew test --retry --verbose coinutils
brew test --retry --verbose condure
brew test --retry --verbose cpl
brew test --retry --verbose cpr
brew test --retry --verbose credstash
brew test --retry --verbose crystal
brew test --retry --verbose curl
brew test --retry --verbose curlie
brew test --retry --verbose datetime-fortran
brew test --retry --verbose dcraw
brew test --retry --verbose devil
brew test --retry --verbose diesel
brew test --retry --verbose diffr
brew test --retry --verbose diskonaut
brew test --retry --verbose diskus
brew test --retry --verbose dlib
brew test --retry --verbose docker-compose
brew test --retry --verbose dog
brew test --retry --verbose dopewars
brew test --retry --verbose dotenv-linter
brew test --retry --verbose dprint
brew test --retry --verbose dssim
brew test --retry --verbose dua-cli
brew test --retry --verbose duckscript
brew test --retry --verbose duplicity
brew test --retry --verbose dust
brew test --retry --verbose dvc
brew install emscripten
brew test --retry --verbose envchain
brew test --retry --verbose epstool
brew install --only-dependencies eralchemy
brew test --retry --verbose eralchemy
brew test --retry --verbose esptool
brew test --retry --verbose eureka
brew test --retry --verbose eva
brew test --retry --verbose exa
brew test --retry --verbose exiv2
brew test --retry --verbose fabric
brew test --retry --verbose fastmod
brew test --retry --verbose fb-client
brew test --retry --verbose fblog
brew test --retry --verbose fcp
brew test --retry --verbose fd
brew test --retry --verbose feh
brew test --retry --verbose ffsend
brew test --retry --verbose fftw
brew test --retry --verbose fig2dev
brew install file-roller
brew test --retry --verbose findomain
brew test --retry --verbose flintrock
brew test --retry --verbose fltk
brew test --retry --verbose fnm
brew test --retry --verbose fobis
brew test --retry --verbose folly
brew test --retry --verbose ford
brew test --retry --verbose freeglut
brew test --retry --verbose frum
brew test --retry --verbose fselect
brew test --retry --verbose ganglia
brew test --retry --verbose gcab
brew test --retry --verbose gcc
brew install gcc@10
brew test --retry --verbose gcc@5
brew install --only-dependencies gcc@6
brew install gcc@6
brew install gcc@7
brew install gcc@8
brew install gcc@9
brew install --only-dependencies gdb
brew test --retry --verbose gdb
brew test --retry --verbose gdbgui
brew test --retry --verbose gdl
brew test --retry --verbose geckodriver
brew test --retry --verbose genact
brew install --only-dependencies geocode-glib
brew install geocode-glib
brew install ghex
brew test --retry --verbose ghostscript
brew test --retry --verbose gimme-aws-creds
brew test --retry --verbose git
brew test --retry --verbose git-absorb
brew test --retry --verbose git-annex
brew test --retry --verbose git-delta
brew test --retry --verbose git-interactive-rebase-tool
brew test --retry --verbose git-secret
brew test --retry --verbose git-series
brew test --retry --verbose git-trim
brew test --retry --verbose gitui
brew test --retry --verbose gl2ps
brew test --retry --verbose glibmm
brew test --retry --verbose glui
brew test --retry --verbose gluon
brew test --retry --verbose glyr
brew linkage --test gmic
brew test --retry --verbose gmic
brew test --retry --verbose gmime
brew test --retry --verbose gnirehtet
brew install gnumeric
brew test --retry --verbose gnupg
brew test --retry --verbose gnupg@2.2
brew test --retry --verbose gocr
brew test --retry --verbose gpgme
brew test --retry --verbose gprof2dot
brew test --retry --verbose gradle
brew test --retry --verbose graphicsmagick
brew test --retry --verbose graphviz
brew test --retry --verbose grex
brew test --retry --verbose groff
brew test --retry --verbose gromacs
brew test --retry --verbose groovy
brew test --retry --verbose groovysdk
brew test --retry --verbose gssdp
brew test --retry --verbose gtk+3
brew install --only-dependencies gtk-vnc
brew test --retry --verbose gtk-vnc
brew install gtk4
brew test --retry --verbose gtksourceview4
brew test --retry --verbose hadoop
brew test --retry --verbose hcxtools
brew linkage --test hdf5
brew test --retry --verbose hdf5
brew linkage --test hdf5-mpi
brew test --retry --verbose hdf5-mpi
brew linkage --test hdf5@1.10
brew test --retry --verbose hdf5@1.10
brew linkage --test hdf5@1.8
brew test --retry --verbose hdf5@1.8
brew install heimdal
brew test --retry --verbose hexyl
brew test --retry --verbose htmlcleaner
brew test --retry --verbose htslib
brew test --retry --verbose hyperfine
brew test --retry --verbose hypre
brew test --retry --verbose igraph
brew test --retry --verbose imagemagick
brew test --retry --verbose imagemagick@6
brew test --retry --verbose include-what-you-use
brew test --retry --verbose inko
brew test --retry --verbose irrlicht
brew test --retry --verbose jags
brew test --retry --verbose jasper
brew test --retry --verbose javacc
brew test --retry --verbose jdnssec-tools
brew test --retry --verbose jhipster
brew test --retry --verbose jmeter
brew test --retry --verbose joshua
brew test --retry --verbose jql
brew test --retry --verbose jrnl
brew test --retry --verbose jrsonnet
brew install jruby
brew test --retry --verbose jsonrpc-glib
brew test --retry --verbose jsvc
brew test --retry --verbose julia
brew test --retry --verbose just
brew test --retry --verbose kafka
brew test --retry --verbose kafkacat
brew test --retry --verbose kahip
brew test --retry --verbose kaitai-struct-compiler
brew test --retry --verbose kakoune
brew test --retry --verbose keydb
brew linkage --test kim-api
brew test --retry --verbose kim-api
brew test --retry --verbose kondo
brew test --retry --verbose kubie
brew test --retry --verbose lammps
brew linkage --test lapack
brew test --retry --verbose lapack
brew test --retry --verbose lastpass-cli
brew test --retry --verbose lc0
brew test --retry --verbose leaf-proxy
brew test --retry --verbose ledger
brew test --retry --verbose leiningen
brew test --retry --verbose libdazzle
brew test --retry --verbose libepoxy
brew test --retry --verbose libgee
brew test --retry --verbose libgeotiff
brew test --retry --verbose libgit2-glib
brew test --retry --verbose libhttpserver
brew test --retry --verbose libhttpseverywhere
brew test --retry --verbose libicns
brew test --retry --verbose libmatio
brew test --retry --verbose libosinfo
brew test --retry --verbose libpeas
brew test --retry --verbose libpqxx
brew test --retry --verbose libpulsar
brew test --retry --verbose libraw
brew test --retry --verbose librest
brew test --retry --verbose librsvg
brew test --retry --verbose libserdes
brew test --retry --verbose libsigc++
brew install --only-dependencies libsoup
brew test --retry --verbose libsoup
brew test --retry --verbose libspectre
brew test --retry --verbose libtorrent-rasterbar
brew test --retry --verbose libvirt
brew linkage --test libxc
brew test --retry --verbose libxc
brew test --retry --verbose libzdb
brew test --retry --verbose lighttpd
brew test --retry --verbose link-grammar
brew test --retry --verbose links
brew test --retry --verbose liquid-dsp
brew test --retry --verbose liquigraph
brew test --retry --verbose llvm
brew test --retry --verbose llvm@11
brew install --only-dependencies llvm@7
brew test --retry --verbose llvm@7
brew test --retry --verbose llvm@8
brew test --retry --verbose llvm@9
brew test --retry --verbose loc
brew test --retry --verbose lsd
brew test --retry --verbose luaradio
brew test --retry --verbose macchina
brew test --retry --verbose magic-wormhole
brew test --retry --verbose makefile2graph
brew test --retry --verbose man-db
brew test --retry --verbose mariadb
brew test --retry --verbose mariadb@10.2
brew test --retry --verbose mariadb@10.3
brew test --retry --verbose mariadb@10.4
brew test --retry --verbose mariadb@10.5
brew test --retry --verbose mask
brew test --retry --verbose maturin
brew test --retry --verbose maven
brew test --retry --verbose mavsdk
brew test --retry --verbose mdbook
brew test --retry --verbose mdcat
brew test --retry --verbose mdk
brew test --retry --verbose megatools
brew test --retry --verbose meilisearch
brew test --retry --verbose mesa
brew test --retry --verbose mesa-glu
brew test --retry --verbose micronaut
brew test --retry --verbose miniserve
brew test --retry --verbose molecule
brew test --retry --verbose monkeysphere
brew test --retry --verbose monolith
brew test --retry --verbose moto
brew test --retry --verbose mpi4py
brew linkage --test mpich
brew test --retry --verbose mpich
brew test --retry --verbose msitools
brew test --retry --verbose mupdf
brew test --retry --verbose mvtools
brew test --retry --verbose mycli
brew test --retry --verbose mysql
brew test --retry --verbose navi
brew test --retry --verbose ncmpcpp
brew test --retry --verbose neomutt
brew test --retry --verbose neovim
brew test --retry --verbose neovim-remote
brew test --retry --verbose netpbm
brew test --retry --verbose newsboat
brew test --retry --verbose ngspice
brew test --retry --verbose nicotine-plus
brew test --retry --verbose nomino
brew test --retry --verbose notmuch
brew test --retry --verbose numpy
brew test --retry --verbose nushell
brew test --retry --verbose oakc
brew test --retry --verbose oci-cli
brew test --retry --verbose onefetch
brew linkage --test open-mpi
brew test --retry --verbose open-mpi
brew test --retry --verbose open-sp
brew linkage --test openblas
brew test --retry --verbose openblas
brew test --retry --verbose opencoarrays
brew linkage --test openfast
brew test --retry --verbose openfast
brew test --retry --verbose openjdk
brew test --retry --verbose openldap
brew test --retry --verbose openstackclient
brew test --retry --verbose oq
brew test --retry --verbose orientdb
brew test --retry --verbose osc
brew test --retry --verbose osi
brew test --retry --verbose osinfo-db-tools
brew test --retry --verbose osslsigncode
brew test --retry --verbose otf2
brew test --retry --verbose ox
brew test --retry --verbose oxipng
brew linkage --test packmol
brew test --retry --verbose packmol
brew test --retry --verbose pandoc-plot
brew test --retry --verbose pass
brew test --retry --verbose pass-git-helper
brew test --retry --verbose pass-otp
brew test --retry --verbose passpie
brew test --retry --verbose pastel
brew test --retry --verbose pdf2image
brew test --retry --verbose pdns
brew test --retry --verbose pdnsrec
brew test --retry --verbose pg_top
brew test --retry --verbose pgpool-ii
brew install php
brew install php@7.3
brew install php@7.4
brew test --retry --verbose phplint
brew test --retry --verbose phpmyadmin
brew test --retry --verbose phpstan
brew test --retry --verbose pig
brew test --retry --verbose pinentry
brew test --retry --verbose pius
brew linkage --test plplot
brew test --retry --verbose plplot
brew test --retry --verbose pngquant
brew test --retry --verbose postgresql
brew test --retry --verbose powerman
brew test --retry --verbose procs
brew test --retry --verbose proj
brew test --retry --verbose proteinortho
brew test --retry --verbose psqlodbc
brew test --retry --verbose pueue
brew test --retry --verbose pwntools
brew test --retry --verbose pyflow
brew test --retry --verbose pythran
brew linkage --test qrupdate
brew test --retry --verbose qrupdate
brew test --retry --verbose quvi
brew test --retry --verbose rargs
brew test --retry --verbose ratfor
brew test --retry --verbose rav1e
brew test --retry --verbose raxml-ng
brew test --retry --verbose raylib
brew test --retry --verbose rbspy
brew test --retry --verbose rdkit
brew test --retry --verbose reprepro
brew test --retry --verbose rgbds
brew test --retry --verbose ripgrep
brew test --retry --verbose ripgrep-all
brew test --retry --verbose rm-improved
brew test --retry --verbose robot-framework
brew test --retry --verbose roswell
brew test --retry --verbose rpg-cli
brew test --retry --verbose rrdtool
brew test --retry --verbose rsyslog
brew test --retry --verbose rtags
brew test --retry --verbose rust
brew test --retry --verbose rust-analyzer
brew test --retry --verbose rustscan
brew test --retry --verbose rustup-init
brew test --retry --verbose samtools
brew linkage --test scalapack
brew test --retry --verbose scalapack
brew test --retry --verbose sccache
brew linkage --test scipy
brew test --retry --verbose scipy
brew test --retry --verbose sd
brew test --retry --verbose sdb
brew test --retry --verbose seal
brew test --retry --verbose semgrep
brew test --retry --verbose shadowenv
brew test --retry --verbose shellharden
brew test --retry --verbose simgrid
brew test --retry --verbose sk
brew test --retry --verbose skopeo
brew test --retry --verbose smali
brew test --retry --verbose smpeg
brew test --retry --verbose sn0int
brew test --retry --verbose snakemake
brew test --retry --verbose sniffglue
brew test --retry --verbose so
brew test --retry --verbose solidity
brew test --retry --verbose sonic
brew test --retry --verbose sparse
brew test --retry --verbose spotify-tui
brew test --retry --verbose spotifyd
brew test --retry --verbose ssh-permit-a38
brew test --retry --verbose sslyze
brew test --retry --verbose starship
brew test --retry --verbose subversion
brew test --retry --verbose sundials
brew test --retry --verbose superlu
brew test --retry --verbose suricata
brew test --retry --verbose svgcleaner
brew test --retry --verbose svtplay-dl
brew test --retry --verbose sylpheed
brew test --retry --verbose tealdeer
brew test --retry --verbose tectonic
brew test --retry --verbose termius
brew test --retry --verbose texlab
brew test --retry --verbose tiger-vnc
brew test --retry --verbose tldr
brew test --retry --verbose toast
brew test --retry --verbose tokei
brew test --retry --verbose topgrade
brew test --retry --verbose transmission-cli
brew test --retry --verbose tre-command
brew test --retry --verbose tree-sitter
brew test --retry --verbose trunk
brew test --retry --verbose ufraw
brew test --retry --verbose uutils-coreutils
brew test --retry --verbose vala
brew test --retry --verbose vala-language-server
brew test --retry --verbose valabind
brew test --retry --verbose vcftools
brew test --retry --verbose vcpkg
brew test --retry --verbose vifm
brew test --retry --verbose vivid
brew test --retry --verbose vlmcsd
brew test --retry --verbose volta
brew test --retry --verbose wagyu
brew test --retry --verbose wapm
brew test --retry --verbose wasm-pack
brew test --retry --verbose wasmer
brew test --retry --verbose wasmtime
brew test --retry --verbose watchexec
brew test --retry --verbose wdc
brew test --retry --verbose websocat
brew test --retry --verbose weechat
brew test --retry --verbose wllvm
brew test --retry --verbose wp-cli
brew test --retry --verbose wxmac
brew test --retry --verbose wxmac@3.0
brew test --retry --verbose x264
brew test --retry --verbose xalan-c
brew test --retry --verbose xerces-c
brew test --retry --verbose xfig
brew test --retry --verbose xh
brew test --retry --verbose xml-security-c
brew test --retry --verbose xplr
brew test --retry --verbose xsv
brew install yelp-tools
brew test --retry --verbose ykman
brew test --retry --verbose z3
brew test --retry --verbose zbar
brew test --retry --verbose zellij
brew test --retry --verbose zet
brew test --retry --verbose zig
brew test --retry --verbose zile
brew test --retry --verbose zita-convolver
brew test --retry --verbose zoxide
```

</p>
</details>

CC @Homebrew/linux

**Comment by carlocab** [comment]
They all seem to be errors that look like
```
==> /home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide add /
/home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide)
/home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide)
/home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by /home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide)
/home/linuxbrew/.linuxbrew/Cellar/zoxide/0.7.2/bin/zoxide: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/linuxbrew/.linuxbrew/lib/libgcc_s.so.1)
```
Not really sure what's going on there. @dawidd6, @danielnachun, thoughts?

**Comment by cho-m** [comment]
Perhaps due to running on Debian 7 Wheezy (glibc 2.13, gcc 4.7.2) rather than Ubuntu 16.04 Xenial (glibc 2.23, gcc 5.4.0) where pretty much all the bottles were built.

**Comment by iMichka** [comment]
Ha yes I see ... it should be built in Wheezy, and this is what happened. But when running the tests, I think we need to instal brewed `glibc` in the wheezy container (just after the build but before the dependents tests). Or run the depents tests in our ubuntu 16.04 container. cc @dawidd6 @sjackman

**Comment by carlocab** [comment]
Looks like Homebrew/homebrew-test-bot#650 helped a bit, but also revealed a bunch of other problems.

I'm not sure that the Linux failures here should block formula updates to Mac users, though, since we haven't rolled out using Homebrew/core to our Linux users yet anyway.

**Review by carlocab — APPROVED** [review]
I think this is ready to merge, given the experimental status of Linux formulae in Homebrew/core at the moment.

**Comment by dawidd6** [comment]
I think we should disable dependents testing for binutils

**Comment by danielnachun** [comment]
I don't think we should be testing dependents in Debian Wheezy at all, due to the `glibc` issues.  I believe we will eventually be able to eliminate our use of an older CI entirely, so we should just use it right now for the bare minimum needed to keep Linuxbrew working for users with older `glibc` (which includes me!).

**Comment by dawidd6** [comment]
I made a new PR for test-bot. Please wait a bit with merging this.

**Comment by iMichka** [comment]
Binutils is a core formula on Linux (like patchelf back then, but we replaced patchelf with a ruby implementation). So if stuff is broken with a binutils update, you might break a lot of things: the risk is to get a lot more of red PRs down the road in homebrew-core. It will not have ant impact on our users but might be a lot of work for maintainers to cleanup broken builds later on.

I would like to see a green CI here before merging, because binutils is very important.

**Comment by carlocab** [comment]
Sure, but I think the correct thing to do there would be to delay migrating Linux users to Homebrew/core while fixing `binutils` issues instead of delaying formula updates to macOS users.

We do have green CI now, but that's because we've skipped testing all dependents for `binutils` after Homebrew/homebrew-test-bot#651.

**Comment by dawidd6** [comment]
But we didn't test reverse deps in linuxbrew-core and everything was great (at least with binutils IIRC)

**Pull request closed without merging**
