### PR TITLE
apache-arrow-glib 0.11.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
So you know why bunp-formula-pr made a mirror here?

**Comment by igas** [comment]
I added it to match other apache formulas. Is there are special behaviour to it? as if I open it shows html page with link to download.

**Comment by SMillerDev** [comment]
I'm not sure how it works but it's not something that's done by the command that's in the pull request description. That's why it kind of confused me.

**Comment by igas** [comment]
It's been done with `bunp-formula-pr` there is flag `--mirror`.

**Pull request closed without merging**
