### PR TITLE
Crowdin version 2.0.29

### PR DESCRIPTION
**Pull request by dmtr-p**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zbeekman** [comment]
@dmytro-protsyk The test here is nearly useless, and it looks like you haven't tested locally, since the PR checkboxes are unchecked. Could you please update with a better test? Or at least verify that it works locally and address each checkbox of the PR?

**Comment by dmytro-protsyk** [comment]
I checked formula locally and it works. I will add better tests with another pull request.

**Comment by anis-campos** [comment]
Hi,

Could this be merged ? The v2.0.28 doesn't work see https://github.com/Homebrew/homebrew-core/pull/38711#issuecomment-481800996.

Thanks

**Comment by SMillerDev** [comment]
I was personally waiting for the other pull request to avoid merging faulty software next time.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by zbeekman** [comment]
I opened a PR for some better tests: https://github.com/Homebrew/homebrew-core/pull/39282

**Pull request closed without merging**
