### PR TITLE
micronaut: update to use openjdk 21

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  Could not determine the dependencies of task ':micronaut-cli:buildLayers'.
  > Could not resolve all dependencies for configuration ':micronaut-cli:runtimeClasspath'.
     > Failed to query the value of task ':micronaut-cli:compileGroovy' property 'javaLauncher'.
        > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=17, vendor=any vendor, implementation=vendor-specific} for MAC_OS on aarch64.
           > No locally installed toolchains match and toolchain download repositories have not been configured.
```

**Comment by daeho-ro** [comment]
Without patch, it is built on my local but cannot make sure it really built with java 21.

**Comment by daeho-ro** [comment]
Not even close. It seems that the cli build depends on several modules..

**Comment by daeho-ro** [comment]
Upstream try to change for using java 21 and maybe we can wait for the next release.
- https://github.com/micronaut-projects/micronaut-starter/commits/4.7.x/

**Comment by chenrui333** [comment]
close in favor of https://github.com/Homebrew/homebrew-core/pull/197622

**Pull request closed without merging**
