### PR TITLE
jmeter: pin dependency to openjdk@17

### PR DESCRIPTION
**Pull request by applestoapples**
This change pins jmeter's dependency to openjdk@17 since newer versions of the JDK are not fully supported by JMeter (specifically the [Groovy plugin](https://jmeter.apache.org/changes.html#Non-functional%20changes)).

Reference:
The current version of JMeter is tested only to JDK17 see notes from Apache [here](https://jmeter.apache.org/changes.html#New%20and%20Noteworthy) 

Specifically, one of its plugins, [Groovy](https://jmeter.apache.org/changes.html#Non-functional%20changes), does not support >JDK17 and throws a runtime exception when compiling scripts. See Groovy notes from [here](https://groovy-lang.org/releasenotes/groovy-4.0.html#Groovy4.0-requirements) listing the versions of JDK that it has been tested against (this is the most current version of Groovy, which is actually ahead of what JMeter includes).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Can we update the test to something that errors if the wrong Java version is used?

**Comment by applestoapples** [comment]
> Can we update the test to something that errors if the wrong Java version is used?

Great idea. I added a simple test that can be executed through the CLI that will fail unless a compatible version of the JDK is being used. This way we aren't tying directly to a specific version of the SDK if Apache releases a patch in the future that increases compatibility.

**Comment by applestoapples** [comment]
Sorry just realized my test could be better. Will update once test is complete

**Review by carlocab — APPROVED** [review]
Thanks; nice work!

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
