### PR TITLE
sip 5.0.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Update this outdated so it can build on Catalina

### CODE REVIEW

**Comment by fxcoudert** [comment]
Will need https://github.com/Homebrew/homebrew-core/pull/44965

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Parallel `make install` failing

**Comment by bayandin** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
```
==> /usr/local/Cellar/pyqt/5.13.1/bin/pyuic5 --version
Failed to execute: /usr/local/Cellar/pyqt/5.13.1/bin/pyuic5
Error: pyqt: failed
Failed executing:
```

**Comment by fxcoudert** [comment]
New qt bottles merged, let's try again.
@BrewTestBot test this please

**Comment by bayandin** [comment]
@fxcoudert It seems `pyuic5`, and `pylupdate5` are not included into official [pypi package](https://pypi.org/project/PyQt5/), so maybe we can remove it from the formulae tests as well?
Unfortunately can't find any notes about it in [the changelog](https://www.riverbankcomputing.com/static/Downloads/PyQt5/ChangeLog-5.13.2.dev1910120947) , so it could be a bug in `pyqt` itself.

**Comment by fxcoudert** [comment]
```
    Generating the Makefiles...
    Compiling the project...
    Installing the project...
    Traceback (most recent call last):
      File "/usr/local/Cellar/pyqt/5.13.2/libexec/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 103, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
```

**Comment by fxcoudert** [comment]
Some progress made, but not yet enough: https://www.riverbankcomputing.com/pipermail/pyqt/2019-November/042323.html

**Comment by fxcoudert** [comment]
pyqt 5.13.2, building with sip 4, is merged in https://github.com/Homebrew/homebrew-core/pull/46598

**Pull request closed without merging**
