### PR TITLE
svtplay-dl 2.2

### PR DESCRIPTION
**Pull request by spaam**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Is ffmpeg now required for all features, even without post-processing? Can you link to some documentation / release notes stating that?

**Comment by spaam** [comment]
Its used for post-processing. we are also using it to join the audio and video files that is separated. 
i always tell people to download ffmpeg to do it, by that i feel like its better to say its required to have it. 

there is no documentation or release notes mention its required to have it yet. but on my page we tell people to install it on macOS and linux for post-processing. 

i can add the `caveats` again until everything is updated and mentioned in the release notes for the next version.

**Comment by fxcoudert** [comment]
It's a question of what fraction of users will need it. ffmpeg is a heavy dependency, so we don't want to force users to install if only 10% are actually gonna need it.

I don't know the software, so I'll let you make the call on that (and comment below why). We'll go with that.

**Comment by spaam** [comment]
i will change the formula so its like the one before. will ask the community how they want to have it. maybe i will change it later. thanks for the comments :)

**Comment by fxcoudert** [comment]
Thanks! You rock

**Pull request closed without merging**
