### PR TITLE
gradle: Add option to install gradle-all

### PR DESCRIPTION
**Pull request by octylFractal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)? ❌ **I cannot run `RuboCop` as it currently segfaults on my system.**

-----

When writing Gradle plugins it's nice to have the source on hand. This PR adds the ability to install the `-all` distribution of Gradle, which, while larger, contains docs, source, and other useful files for a developer. I'm not sure if there is a recommended way to do such a thing, so I patched something together from what I could find on the documentation. If there's a better way, just tell me and I'd be glad to do it.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> while larger

What's the size difference?

If this has a different URL then it should be a different formula, probably. Alternatively, if it's not a huge difference we can just always use `-all` and selectively install the bits we need.

**Comment by kenzierocks** [comment]
The `-bin` zip is 66M and the `-all` zip is 85M. My reasoning for keeping the formula together is that they should both have the same version, and I'm worried that one of them might get behind a few versions if no one uses it.

**Comment by MikeMcQuaid** [comment]
@kenzierocks Let's change this one to use the `-all` zip and only install the same bits as currently by default unless the option is passed.

**Comment by kenzierocks** [comment]
Alright, made that change.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
