### PR TITLE
percona-xtrabackup 2.4.14

### PR DESCRIPTION
**Pull request by delgod**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
just update to the latest version

### CODE REVIEW

**Comment by fxcoudert** [comment]
High Sierra failure:

```
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/sql/geometry_rtree.cc:16:
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/sql/item_geofunc_internal.h:35:
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/sql/gis_bg_traits.h:38:
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/include/boost_1_59_0/patches/boost/geometry/util/math.hpp:28:
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/boost_1_59_0/boost/math/constants/constants.hpp:18:
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/boost_1_59_0/boost/lexical_cast.hpp:32:
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/boost_1_59_0/boost/lexical_cast/try_lexical_convert.hpp:35:
In file included from /tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/boost_1_59_0/boost/lexical_cast/detail/converter_lexical.hpp:54:
/tmp/percona-xtrabackup-20190507-40448-l4kz46/percona-xtrabackup-2.4.14/boost_1_59_0/boost/lexical_cast/detail/converter_lexical_streams.hpp:460:24: error: no template named 'array' in namespace 'boost'; did you mean 'std::array'?
            operator<<(boost::array<C, N> const& input) BOOST_NOEXCEPT { 
                       ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:223:64: note: 'std::array' declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
```

**Comment by Moisan** [comment]
The latest version seems to be `8.0`.

**Comment by delgod** [comment]
Hi @Moisan,

Percona XtraBackup 8.0 can be used only with MySQL 8.0 which is not widely used now.
2.4 and 8.0 versions of should be packaged into separate packages, like we have for mysql: mysql@5.5 mysql@5.6 mysql@5.7

so, please merge at least update for Percona XtraBackup 2.4 which can be used with mysql@5.5 mysql@5.6 mysql@5.7

**Comment by fxcoudert** [comment]
OK for now, but we probably want to migrate to MySQL 8 which is the version we ship in Homebrew.

**Pull request closed without merging**
