### PR TITLE
qt@5: patches to build with xcode 15

### LINKED ISSUE #144051: qmake fails after Xcode tools update, "failed to parse default search paths from compiler output"
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs qt
Error: No logs.

$ brew config 
HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 3 days ago
Core tap JSON: 19 Sep 15:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.POHQ6QaZR7/org.xquartz:0
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Building a project that uses `qt` and had been building for months. Moments after an XCode command-line tools update, the project started failing to build with an error:

```
Project ERROR: failed to parse default search paths from compiler output
```

This still happens after cleaning up the build directory and giving the spec manually, see below.

### What happened (include all command output)?

$ qmake
Project ERROR: failed to parse default search paths from compiler output

### What did you expect to happen?

$ qmake
(builds or update the makefile)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install qt
touch test.pro
qmake test.pro

clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

fixes #144051

upstream bug report, https://bugreports.qt.io/browse/QTBUG-117225

### CODE REVIEW

**Comment by fxcoudert** [comment]
Tried the patch locally, and it's currently building, but `configure` gave the following ominous warnings:

```
Note: The following modules are not being compiled in this configuration:
    webenginecore
    webengine
    webenginewidgets
    pdf
    pdfwidgets

WARNING: QtWebEngine requires at least version 10.0.0, but using Xcode version .
WARNING: QtPdf requires at least version 10.0.0, but using Xcode version .
WARNING: QtWebEngine will not be built.
WARNING: QtPdf will not be built.
```

**Comment by fxcoudert** [comment]
```
avfcamerautility.mm:104:35: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
struct FormatHasNoFPSRange : std::unary_function<AVCaptureDeviceFormat *, bool>
                             ~~~~~^~~~~~~~~~~~~~
                                  __unary_function
```

**Comment by Bo98** [comment]
> Tried the patch locally, and it's currently building, but `configure` gave the following ominous warnings:

Seems like some part of this is failing for you: https://github.com/qt/qtbase/blob/v5.15.10-lts-lgpl/mkspecs/features/mac/default_pre.prf#L36-L51

**Comment by fxcoudert** [comment]
Not sure why commit style is failing… can't autosquash take care of that?

**Review by fxcoudert — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
