### PR TITLE
jinx 1.1.8 (new formula)

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

```console
$ brew audit --strict --new-formula --online jinx
jinx:
  * The URL https://www.jinx-lang.org is not reachable
Error: 1 problem in 1 formula detected
```

https://www.jinx-lang.org works fine for me

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```console
$ curl https://www.jinx-lang.org/
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by gromgit** [comment]
Interesting project, but was the notability filter changed or turned off? I thought it was >= 30 forks/watchers in addition to >=75 stars; Jinx has only 5 forks and 12 watchers, yet `brew audit --online` didn't complain.

**Comment by SeekingMeaning** [comment]
I'm pretty sure notable enough == 75 stars or 30 forks or 30 watchers

**Comment by gromgit** [comment]
Oh sorry, got my conditional logic mixed up when reading `notability.rb`. :blush:

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
