### PR TITLE
mesa 24.1.2

### PR DESCRIPTION
**Pull request by yurikoles**
Follow-up of #172689

Co-authored-by: Rui Chen <rui@chenrui.dev>
Signed-off-by: Rui Chen <rui@chenrui.dev>
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Upstream [issue #11217](https://gitlab.freedesktop.org/mesa/mesa/-/issues/11217) was fixed by [MR !29732](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/29732).

### CODE REVIEW

**Comment by chenrui333** [comment]
Thanks @yurikoles!

**Review by chenrui333 — APPROVED** [review]

**Comment by yurikoles** [comment]
All jobs succeed except Linux (deps), which didn't even start for one day because of the lack of free runner.

I plan to retrigger the build by the rebase and force push.

**Comment by chenrui333** [comment]
unrelated quanzip test failure (known issue), merging.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
quazip passed my regression check

```
==> /home/linuxbrew/.linuxbrew/opt/qt/bin/qmake test.pro
Info: creating stash file /tmp/quazip-test-20240624-43068-vokowx/.qmake.stash
==> make
g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/quazip/1.4/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/include/QtGui -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/share/qt/mkspecs/linux-g++ -o test.o test.cpp
g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/quazip/1.4/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/lib -Wl,-rpath-link,/home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/lib -o test  test.o   -L/home/linuxbrew/.linuxbrew/Cellar/quazip/1.4/lib -lquazip1-qt6 /home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/lib/libQt6Gui.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.7.0_1/lib/libQt6Core.so -lpthread -lGL
==> ./test
```

**Pull request merged**
