### PR TITLE
python 3.7.6

### PR DESCRIPTION
**Pull request by sayomaki**
Created with `brew bump-formula-pr`.

---

Python 3.7.5 -> 3.7.6

### CODE REVIEW

**Comment by bayandin** [comment]
Thanks for the PR @willi123yao!
Could you please also update `setuptools` resource to 42.0.2

**Comment by willi123yao** [comment]
setuptools 41.6.0 -> 42.0.2

**Comment by fxcoudert** [comment]
You need to bump revisions for: `alure certbot doitlive euler-py remarshal statik ungit vim@7.4`

**Comment by willi123yao** [comment]
@fxcoudert How about the formula `bzt`? It also seems to need its revision bumped.

**Comment by fxcoudert** [comment]
I don't think `bzt` needs a revision bump. The test only fails on 1 macOS version, so the problem is likely something else.

**Comment by fxcoudert** [comment]
CI status for this latest run:
- High Sierra got stuck building `ungit`
- Catalina node ran out of space pouring out the Swift bottle during testing
- `bumpversion` is missing bottles
- Audio test failures: `dromeaudio libsoundio`
- Other test failures: `texlab alure euler-py`
-  `remarshal` conflicts with `msgpack-tools`

**Comment by fxcoudert** [comment]
The plan is therefore:

- merge this one first: https://github.com/Homebrew/homebrew-core/pull/48234
- I've proposed a testbot patch that should improve testing time: https://github.com/Homebrew/homebrew-test-bot/pull/307
- Possibly increase disk space on the CI machine
- Then we can rerun this

In the meantime, we probably want to figure out the other issues listed above.

**Comment by fxcoudert** [comment]
- `bumpversion` bottles fixed in 3bda9ab8f3bd72c1b0fc2ef620d5f71a16faee38

**Comment by fxcoudert** [comment]
- `alure` was an opportunistic linkage, rebuilding the bottle now
- same for `protobuf@3.7`

**Pull request closed without merging**
