### PR TITLE
little-cms2: avoid `register` storage class

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
C++17 removed the `register` storage class, uncomment `CMS_NO_REGISTER_KEYWORD` to make it compatible with C++17 code.

### CODE REVIEW

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Shouldn't need a revision bump and should be submitted upstream

**Comment by SMillerDev** [comment]
That PR suggests that it's already supported and the issue suggests that it's not something that should be changed in the library.

**Comment by carlocab** [comment]
Does doing
```
-DCMS_NO_REGISTER_KEYWORD=1
```
when compiling with C++17 not work?

**Comment by carlocab** [comment]
> > Does doing
> 
> > 
> 
> > ```
> 
> > -DCMS_NO_REGISTER_KEYWORD=1
> 
> > ```
> 
> > 
> 
> > when compiling with C++17 not work?
> 
> 
> 
> It works, but it is a configuration toggle in `lcms2`, like `mbedtls`.

So a library compiled with this macro defined is not binary-compatible with a library without this macro defined?

**Comment by carlocab** [comment]
If this breaks the ABI then we cannot merge this without rebuilding all dependents, and that's a show-stopper.

If this doesn't break the ABI, then I think it is sufficient for you to define this macro when including the lcms2 header, so there should be no need to rebuild the library with this defined.

**Pull request closed without merging**
