### PR TITLE
or-tools 9.5

### PR DESCRIPTION
**Pull request by Dekker1**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Dekker1** [comment]
From the logs, it looks like OR-Tools no longer supports MacOS 10.15 (although not explicitly mentioned in the change log).
Is there some (accepted) way to signal this in the formula?

**Comment by chenrui333** [comment]
```
  /tmp/or-tools-20221128-7856-eu6f70/or-tools-9.5/ortools/base/numbers.cc:200:3: error: use of undeclared identifier 'errno'
    errno = 0;
    ^
  /tmp/or-tools-20221128-7856-eu6f70/or-tools-9.5/ortools/base/numbers.cc:202:7: error: use of undeclared identifier 'errno'
    if (errno != 0 ||    // overflow/underflow happened
        ^
  2 errors generated.
```

**Comment by Dekker1** [comment]
Ah, my apologies. It seems that I was looking at the message that Homebrew itself adds at the end and interpreted that as the problem. Thank you for the correction.

**Comment by chenrui333** [comment]
> From the logs, it looks like OR-Tools no longer supports MacOS 10.15 (although not explicitly mentioned in the change log). Is there some (accepted) way to signal this in the formula?

Similar issue in here, https://github.com/Homebrew/homebrew-core/pull/68095

Patch would be like this, https://git.savannah.gnu.org/cgit/gnulib.git/commit/?id=6a76832db224ac5671599ce332717f985a2addc7

**Comment by Dekker1** [comment]
The patch as suggested seems to fix the problem. I will report the problem to the OR Tools repository so the patch will hopefully no longer be required for the next version.

**Comment by chenrui333** [comment]
> The patch as suggested seems to fix the problem. I have reported the problem to the OR Tools repository so the patch will hopefully no longer be required for the next version: [google/or-tools#3573](https://github.com/google/or-tools/issues/3573)

that is what I anticipated. :)

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
