### PR TITLE
bullet 3.22a

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
macOS failures are linkage failures for dependents. Those will need rev bumps.

Linux failure is a build failure. Not really sure what's going on there. @Homebrew/linux

**Comment by Bo98** [comment]
> Linux failure is a build failure. Not really sure what's going on there

Do we currently ship the examples? If not we should disable them via `BUILD_BULLET2_DEMOS=OFF` etc.

**Comment by danielnachun** [comment]
If I had to guess the failure on Linux is because it needs a newer GCC.

**Comment by scpeters** [comment]
the proper 3.22 release has now been made: https://github.com/bulletphysics/bullet3/releases/tag/3.22

**Comment by Bo98** [comment]
3.22a is what the GitHub latest release points to, and is a newer commit than 3.22.

**Comment by scpeters** [comment]
> 3.22a is what the GitHub latest release points to, and is a newer commit than 3.22.

you are correct. I was misled by the out-of-order listing in the GitHub tags page

* https://github.com/bulletphysics/bullet3/tags

thanks for looking more closely than I did. Weird numbering scheme though

**Pull request closed without merging**
