### PR TITLE
pypy3 5.7.0

### PR DESCRIPTION
**Pull request by chuanconggao**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Can you please squash the two commits together? Thanks

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
Undefined symbols for architecture x86_64:
  "_PyPyErr_NoMemory", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyMem_Free", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyMem_Malloc", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_acquire_lock", referenced from:
      __ssl_thread_locking_function in _pypy_openssl.o
  "_PyPyThread_allocate_lock", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_free_lock", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_release_lock", referenced from:
      __ssl_thread_locking_function in _pypy_openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dunn** [comment]
Has the build error been reported upstream?

**Comment by cclauss** [comment]
pypy3 5.7.1 is now released  https://morepypy.blogspot.ch

**Comment by chuanconggao** [comment]
Since PyPy3 5.7.1 is released, I think we can safely close this one.

**Comment by cclauss** [comment]
https://github.com/chuanconggao/homebrew-core/blob/f3ed1960f4954aff49cfcd0f9db09ff5093867ee/Formula/pypy3.rb#L27 Bootstrapping from such an old version of pypy might be a problem.  The [pypy3 build instructions](http://pypy.readthedocs.io/en/latest/build.html) suggest bootstrapping from the _current_ version of pypy.

**Comment by DomT4** [comment]
Same thing in the latest release FWIW:

```
*** failed to build the CFFI modules ['_ssl_build.py']

PyPy can still be used as long as you don't need the corresponding
modules.  If you do need them, please install the missing headers and
libraries (see error messages just above) and then re-run the command:

    /private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/pypy/goal/pypy3-c /private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/pypy/tool/build_cffi_imports.py

[2b33f] translation-task}
[translation:info] usession directory: /private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/usession-release-pypy3.5-v5.7.1-0
[Timer] Timings:
[Timer] annotate                       ---  330.9 s
[Timer] rtype_lltype                   ---  291.2 s
[Timer] pyjitpl_lltype                 ---  573.3 s
[Timer] backendopt_lltype              ---  103.7 s
[Timer] stackcheckinsertion_lltype     ---  123.4 s
[Timer] database_c                     ---  231.1 s
[Timer] source_c                       ---   99.7 s
[Timer] compile_c                      ---  270.7 s
[Timer] build_cffi_imports             ---   14.0 s
[Timer] ===========================================
[Timer] Total:                         --- 2038.1 s
in get_rpath_flags, rel_libdirs is not fixed up ['/usr/lib']
stdout:

stderr:
_pypy_openssl.c:2855:22: warning: comparison of constant 1152921504606846975 with expression of type 'unsigned int' is always false [-Wtautological-constant-out-of-range-compare]
        _ssl_locks = PyMem_New(PyThread_type_lock, _ssl_locks_count);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/include/pymem.h:38:10: note: expanded from macro 'PyMem_New'
  ( ((n) > PY_SSIZE_T_MAX / sizeof(type)) ? NULL : \
     ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_pypy_openssl.c:72224:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
2 warnings generated.
Undefined symbols for architecture x86_64:
  "_PyPyErr_NoMemory", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyMem_Free", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyMem_Malloc", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_acquire_lock", referenced from:
      __ssl_thread_locking_function in _pypy_openssl.o
  "_PyPyThread_allocate_lock", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_free_lock", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_release_lock", referenced from:
      __ssl_thread_locking_function in _pypy_openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/unixccompiler.py", line 211, in link
    self.spawn(linker + ld_args)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 347, in run
    self.build_extensions()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 456, in build_extensions
    self._build_extensions_serial()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 481, in _build_extensions_serial
    self.build_extension(ext)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 566, in build_extension
    target_lang=language)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/unixccompiler.py", line 213, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ssl_build.py", line 53, in <module>
    ffi.compile()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'clang' failed with exit status 1

==> /private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/bootstrap/bin/pypy package.py --archive-name pypy3 --targetdir . --nostrip
* _decimal_build.py
* _gdbm_build.py
* _audioop_build.py
* _curses_build.py
* _lzma_build.py
* _pwdgrp_build.py
* _resource_build.py
* _sqlite3_build.py
* _ssl_build.py
* _syslog_build.py
* _tkinter/tklib_build.py
!!!!!!!!!!
Building ssl bindings failed.
                You can either install development headers package,
                add the --without-ssl option to skip packaging this
                binary CFFI extension, or say --without-cffi.
stdout:

stderr:
_pypy_openssl.c:2855:22: warning: comparison of constant 1152921504606846975 with expression of type 'unsigned int' is always false [-Wtautological-constant-out-of-range-compare]
        _ssl_locks = PyMem_New(PyThread_type_lock, _ssl_locks_count);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/include/pymem.h:38:10: note: expanded from macro 'PyMem_New'
  ( ((n) > PY_SSIZE_T_MAX / sizeof(type)) ? NULL : \
     ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_pypy_openssl.c:72224:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
2 warnings generated.
Undefined symbols for architecture x86_64:
  "_PyPyErr_NoMemory", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyMem_Free", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyMem_Malloc", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_acquire_lock", referenced from:
      __ssl_thread_locking_function in _pypy_openssl.o
  "_PyPyThread_allocate_lock", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_free_lock", referenced from:
      __setup_ssl_threads in _pypy_openssl.o
  "_PyPyThread_release_lock", referenced from:
      __ssl_thread_locking_function in _pypy_openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/unixccompiler.py", line 211, in link
    self.spawn(linker + ld_args)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 347, in run
    self.build_extensions()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 456, in build_extensions
    self._build_extensions_serial()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 481, in _build_extensions_serial
    self.build_extension(ext)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/command/build_ext.py", line 566, in build_extension
    target_lang=language)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib-python/3/distutils/unixccompiler.py", line 213, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ssl_build.py", line 53, in <module>
    ffi.compile()
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/private/tmp/pypy3-20170416-3804-2xkprg/pypy3-v5.7.1-src/lib_pypy/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'clang' failed with exit status 1
```

**Pull request closed without merging**
