### PR TITLE
netcat: fix arm64/Apple Silicon build

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Audit failure:
```
netcat:
  * Formula netcat contains deprecated SPDX licenses: ["GPL-2.0"].
    You may need to add `-only` or `-or-later` for GNU licenses (e.g. `GPL`, `LGPL`, `AGPL`, `GFDL`).
    For a list of valid licenses check: https://spdx.org/licenses/
Error: 1 problem in 1 formula detected
```

Can you tell I recently moved over to an M1 Mac and discovered a variety of ancient software has no idea what to do with an Apple ARM chip? 🌝

### CODE REVIEW

**Comment by SMillerDev** [comment]
Same as the other PR, could you make an issue upstream?

**Comment by DomT4** [comment]
I can, but the last release was 2004 so at this point I'm not sure there is an upstream really 🙃. I'll file one but I think we're essentially carrying this until the decision is made to delete `netcat` one day.

**Comment by DomT4** [comment]
https://sourceforge.net/p/netcat/bugs/67/

**Comment by Bo98** [comment]
Looks like this would be a `GPL-2.0-or-later`:

```
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.
```

**Comment by DomT4** [comment]
Added the license update, thanks @Bo98.

**Review by Bo98 — APPROVED** [review]

**Comment by Bo98** [comment]
🚀 https://github.com/Homebrew/homebrew-core/actions/runs/754112446

**Comment by DomT4** [comment]
Thanks @Bo98! Can't promise the wave of PRs will keep flowing indefinitely, but it's been a nice distraction today from feeling a little unwell 😄.

**Comment by Bo98** [comment]
It's much appreciated. Any help with the Apple Silicon porting effort is always great to have. ❤️ 

And hope you get better soon!

**Pull request merged**
