### PR TITLE
gdbm 1.21

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..  -DIN_GDBM -DLOCALEDIR=\"/opt/homebrew/Cellar/gdbm/1.21/share/locale\"    -g -O2 -c -o gdbmcount.lo gdbmcount.c
gdbmshell.c:1013:36: error: no member named 'st_mtim' in 'struct stat'
      fprintf (fp, "%ld.%09ld", st.st_mtim.tv_sec, st.st_mtim.tv_nsec);
                                ~~ ^
gdbmshell.c:1013:55: error: no member named 'st_mtim' in 'struct stat'
      fprintf (fp, "%ld.%09ld", st.st_mtim.tv_sec, st.st_mtim.tv_nsec);
                                                   ~~ ^
2 errors generated.
```

**Comment by FnControlOption** [comment]
Here's a patch to fix the compilation errors: https://puszcza.gnu.org.ua/bugs/download.php?file_id=430

```diff
--- src/gdbmshell.c.orig
+++ src/gdbmshell.c
@@ -1010,7 +1010,13 @@ print_snapshot (char const *snapname, FILE *fp)
       fprintf (fp, "%s: ", snapname);
       fprintf (fp, "%03o %s ", st.st_mode & 0777,
 	       decode_mode (st.st_mode, buf));
-      fprintf (fp, "%ld.%09ld", st.st_mtim.tv_sec, st.st_mtim.tv_nsec);
+      struct timespec mtimespec;
+#ifdef __APPLE__
+      mtimespec = st.st_mtimespec;
+#else
+      mtimespec = st.st_mtim;
+#endif
+      fprintf (fp, "%ld.%09ld", mtimespec.tv_sec, mtimespec.tv_nsec);
       if (S_ISREG (st.st_mode))
 	{
 	  GDBM_FILE dbf;
```

Submitted upstream https://puszcza.gnu.org.ua/bugs/?521

**Comment by carlocab** [comment]
Thanks, @FnControlOption.

**Comment by FnControlOption** [comment]
Maybe replace

```
--- src/gdbmshell.c.orig
+++ src/gdbmshell.c
```

with

```
--- a/src/gdbmshell.c
+++ b/src/gdbmshell.c
```

**Comment by FnControlOption** [comment]
Actually I would use the official fix: https://git.gnu.org.ua/gdbm.git/commit/?id=32517af75ac8c32b3ff4870e14ff28418696c554 (Will probably need to be adjusted for 1.21)

**Comment by carlocab** [comment]
> Actually I would use the official fix: https://git.gnu.org.ua/gdbm.git/commit/?id=32517af75ac8c32b3ff4870e14ff28418696c554 (Will probably need to be adjusted for 1.21)

We probably need to regenerate the `configure` script for this, which I'd like to avoid if possible.

**Review by carlocab — APPROVED** [review]
macOS failures are pre-existing, except for `drill`, which should be fixed by #84846.

We should maybe check Linux though. Is it just more of the problem of having multiple `openjdk`s installed?

**Comment by SMillerDev** [comment]
@carlocab how do you feel about just merging this?

**Pull request closed without merging**
