### PR TITLE
Modify lv url

### PR DESCRIPTION
**Pull request by chezou**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

The host of lv is not found, because the host, iij4u is [closed at 31th March](https://www.iij4u.or.jp/).
In order to prevent failing installation, I will change URL of lv.

I'm not a author of lv, but If there is any better place to host it, please tell me.

### CODE REVIEW

**Comment by apjanke** [comment]
We've done the archive.org thing before for other formula whose hosts who've fallen offline; it's fine to use this for now.

Looks like the `homepage` is offline, too. Can that also be found on archive.org?

**Comment by chezou** [comment]
Yes. I tried download from archive.org and checked sha256 checksum of the file is same.

**Comment by apjanke** [comment]
No, I mean how about switching to 
```
homepage "https://web.archive.org/web/20160310122517/http://www.ff.iij4u.or.jp/~nrt/lv"
```
in addition to changing the download `url`?

**Comment by chezou** [comment]
Sorry, I misunderstood. I commit changing homepage.

**Comment by apjanke** [comment]
Cool.

[Merged](https://github.com/Homebrew/homebrew-core/commit/1c21ba1c467533de5278f811467a8ee64cac7851). Thank you for your contribution to Homebrew!

**Comment by chezou** [comment]
Thanks for quick merging :)

**Comment by apjanke** [comment]
And thank you for your quick responses! Homebrew wouldn't work without its contributors like yourself.

**Pull request closed without merging**
