### PR TITLE
SVN/Git protocol upgrades (2/2)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
`np2` and `llnode` don't work :(

**Comment by vszakats** [comment]
One of the dependent projects fail. It looks unrelated to these updates:
```
==> brew linkage --test mednafen
==> FAILED
Missing libraries:
  /usr/local/lib/gcc/6/libgcc_s.1.dylib
  /usr/local/opt/gcc/lib/gcc/6/libstdc++.6.dylib
==> brew test --verbose mednafen
==> FAILED
Testing mednafen
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170312-76580-1v9ej7b.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mednafen.rb --verbose
==> /usr/local/Cellar/mednafen/0.9.41/bin/mednafen -dump_modules_def M >/dev/null || head -n 1 M
dyld: Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
  Referenced from: /usr/local/Cellar/mednafen/0.9.41/bin/mednafen
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/Cellar/mednafen/0.9.41/bin/mednafen
sh: line 1: 76590 Abort trap: 6           /usr/local/Cellar/mednafen/0.9.41/bin/mednafen -dump_modules_def M > /dev/null
head: M: No such file or directory
Error: mednafen: failed
<0> expected but was
<1>.
```

**Comment by vszakats** [comment]
Just fixed `np2`.
As for `llnode`, `MacOS::Xcode.version < "8.0"` && `MacOS.version >= :sierra` looks like a fairly niche if at all possible setup, so I'll just remove that commit.

**Comment by vszakats** [comment]
`mednafen` remains, build machine failure on Yosemite.

**Comment by ilovezfs** [comment]
I think you can fix mednafen CI by explicitly depending on gcc if DevelopmentTools.clang_build_version >= 800

**Comment by vszakats** [comment]
@ilovezfs You mean in the `mednafen` formula, is that correct?

**Comment by ilovezfs** [comment]
@vszakats yes. You can do that in a separate PR first.

**Comment by vszakats** [comment]
Okay, it lives here: #11021

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by vszakats** [comment]
A single failure remains on Yosemite (unrelated to these updates):
```
==> brew linkage --test vorbis-tools
==> FAILED
Missing libraries:
  /usr/lib/libnetwork.dylib
```

**Comment by ilovezfs** [comment]
Cool. I'll fix that in another PR.

**Comment by ilovezfs** [comment]
Thanks @vszakats

**Comment by ilovezfs** [comment]
vorbis-tools fixed here: https://github.com/Homebrew/homebrew-core/pull/11030

**Pull request merged**
