### PR TITLE
pyenv-which-ext: test depend on python

### PR DESCRIPTION
**Pull request by tuzi3040**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Should fix test error in #89842 and #89760.

### CODE REVIEW

**Comment by tuzi3040** [comment]
Probably better to disable in #89873.

**Review by carlocab — APPROVED** [review]
Let's merge this one instead of #89873 so that the formula gets a deprecation period. Thanks @tuzi3040!

**Comment by tuzi3040** [comment]
Maybe better to use other basic binaries that macos and linux both have to test with, like ls, or ruby, which brew depends on.
Since this formulae was originally designed to support `pyenv which` other executables in `PATH` instead of just binaries installed by pyenv.

**Comment by carlocab** [comment]
Yes, probably. `which true` might be good enough.

**Pull request merged**
