### PR TITLE
gringo 5.2.1

### PR DESCRIPTION
**Pull request by domoritz**
Created with `brew bump-formula-pr`.

Build instructions for clingo: https://github.com/potassco/clingo/blob/master/INSTALL.md

### CODE REVIEW

**Comment by domoritz** [comment]
Unfortunately, I don't have the expertise to debug the build failure. 

Here is what I ran locally

```
brew bump-formula-pr --strict gringo --homepage=https://potassco.org/ --url=https://github.com/potassco/clingo/archive/v5.2.1.tar.gz --sha256=b486b0adbd0a2acdfe55856036039318844ccb1e3510f2796caf03c5ee455378                                                                   8.1s
Updated Homebrew from c0063bb8 to 302bc8be.
Updated 2 taps (caskroom/versions, caskroom/cask).
==> replace / +mirror \"https:\/\/www.mirrorservice.org\/sites\/distfiles.macports.org\/gringo\/gringo-4.5.4-source.tar.gz\"\n/m with ""
==> replace "https://downloads.sourceforge.net/project/potassco/gringo/4.5.4/gringo-4.5.4-source.tar.gz" with "https://github.com/potassco/clingo/archive/v5.2.1.tar.gz"
==> replace "81f8bbbb1b06236778028e5f1b8627ee38a712ec708724112fb08aecf9bc649a" with "b486b0adbd0a2acdfe55856036039318844ccb1e3510f2796caf03c5ee455378"
==> Installing or updating 'rubocop' gem
Fetching: parallel-1.12.0.gem (100%)
Successfully installed parallel-1.12.0
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: parser-2.4.0.0.gem (100%)
Successfully installed parser-2.4.0.0
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-2.2.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.3.0.gem (100%)
Successfully installed unicode-display_width-1.3.0
Fetching: rubocop-0.51.0.gem (100%)
Successfully installed rubocop-0.51.0
8 gems installed
remote: Counting objects: 382074, done.
remote: Compressing objects: 100% (153273/153273), done.
remote: Total 382074 (delta 229897), reused 378155 (delta 225992), pack-reused 0
Receiving objects: 100% (382074/382074), 123.92 MiB | 7.45 MiB/s, done.
Resolving deltas: 100% (229897/229897), completed with 3705 local objects.
M	Formula/gringo.rb
Switched to a new branch 'gringo-5.2.1'
[gringo-5.2.1 c91bb6ef38] gringo 5.2.1
 1 file changed, 2 insertions(+), 3 deletions(-)
Counting objects: 47877, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (16348/16348), done.
Writing objects: 100% (47877/47877), 10.72 MiB | 812.00 KiB/s, done.
Total 47877 (delta 35976), reused 43325 (delta 31509)
remote: Resolving deltas: 100% (35976/35976), completed with 3848 local objects.
remote: Checking connectivity: 47877, done.
To github.com:domoritz/homebrew-core.git
 * [new branch]            gringo-5.2.1 -> gringo-5.2.1
Branch 'gringo-5.2.1' set up to track remote branch 'gringo-5.2.1' from 'domoritz'.
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by dariusf** [comment]
Hey @domoritz,

Clingo moved to CMake a while ago, so that formula won't work without changes. It builds cleanly with the instructions in the file that you linked though.

Nevertheless, pre-built binaries are provided, so I have this in a local tap:

```ruby
class Clingo < Formula
  version '5.2.1'
  desc "An ASP system to ground and solve logic programs"
  homepage "https://potassco.org/"
  url "https://github.com/potassco/clingo/releases/download/v5.2.1/clingo-5.2.1-macos-10.9.tar.gz"
  sha256 "e5bd853e6240192c6fd98de972a48a86d4f1b9df2c34d0bb198c324268ee2cde"

  bottle do
    cellar :any_skip_relocation
    sha256 "e0faf8806b7ffbab272bdaead795e4d87a01bea99b709bd49aa56ff9dd33e11b" => :high_sierra
    sha256 "10fdd80c67761f30f49f95ec2e79f0f8cea9c8109053a07853491846af30fc6a" => :sierra
    sha256 "441c81748e551106a923ccd61298f98c8b5e46cba684fc2e0031a4fe11f1d0ae" => :el_capitan
    sha256 "e9b5ee97a0a0b8c14a66d6359936259b7edc96c2013531c250903a03df65bfb0" => :yosemite
    sha256 "7215d8a23fe6052bd67e4ce8b5537da6e16236f07fe387bd7b29fa5f9ee35ca9" => :mavericks
  end

  def install
    bin.install 'clasp', 'clingo', 'clingo-python', 'gringo', 'gringo-python', 'lpconvert', 'reify'
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clingo --version")
  end
end
```

Wasn't sure if the upgrade to Clingo 5 would break dependent packages (`aspcud` and `opam`), so I didn't submit it, but you're welcome to use it if it works for you.

**Comment by domoritz** [comment]
Thank you @dariusf! I guess if it breaks dependent packages, they will have to fix the version they depend on.

**Comment by domoritz** [comment]
I wonder whether there should be a new formula, given that even potassco uses clingo as the main repo now. 

Then a clean path forward would be to create a new formula `clingo` with the code you provided and deprecate the gringo formula.

**Comment by domoritz** [comment]
See https://github.com/Homebrew/homebrew-core/pull/20185

**Comment by domoritz** [comment]
Closing this in favor of deprecating `gringo`.

**Pull request closed without merging**
