### PR TITLE
glib: Make sure gobject-2.0.pc points to libffi's opt path

### LINKED ISSUE #40179: libffi: libffi.pc link not installed in /usr/local
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I tried to build a GTK+ application on macOS. This didn't work because **pkg-config** couldn't find **libffi.pc**. Upon inspection, I noticed this file was in the Cellar, but not linked in **/usr/include/lib/pkgconfig**. After creating a symlink myself, the issue was resolved.

Should this link be created upon installation, as is the case for other libraries I have installed?

Brew config:

```
HOMEBREW_VERSION: 2.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 099b047349d4ec67519206f15401d0e1cf90e953
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e47f3e2682fa3d8a6ee58ded40718a1326e08a6d
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
```

### PR DESCRIPTION
**Pull request by nox**
Fixes #40179.

There is some precedent in other formulas to do that, either for libffi, or for gettext in glib's own formula.

### CODE REVIEW

**Comment by nox** [comment]
I can't reproduce the `sofia-sip` failure, and I don't see how my patch can even break it.

**Comment by nox** [comment]
This also fixes @jeroen's issue reported in #37873.

**Comment by jonchang** [comment]
Try doing a revision bump for that formula, which I think should fix the symptom for now. It’s possible that an opportunistic link occurred when another formula was built. If you could fix that too that would be great, otherwise the revision increment should be sufficient.

**Comment by jonchang** [comment]
I meant bumping the revision of `sofia-sip`. There should be no need to do two revision bumps of `glib`.

**Comment by nox** [comment]
Oh, that makes more sense indeed. Done.

**Comment by nox** [comment]
Build was aborted for some reason and it failed to clone the repo on Mojave for some reason anyway, force-pushed new commits for the CI to trigger itself again.

**Comment by nox** [comment]
Those failures aren't related to anything I did, right @jonchang?

**Comment by jonchang** [comment]
The build machines seem to be having disk space issues.

**Comment by jonchang** [comment]
Merged despite unrelated test failures (due to build VM issues). Thanks for your help in getting this fixed for everyone @nox!

**Pull request closed without merging**
