### PR TITLE
at-spi2-core 2.48.0

### PR DESCRIPTION
**Pull request by nandahkrishna**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @Homebrew/linux

**Comment by nandahkrishna** [comment]
https://github.com/Homebrew/homebrew-core/pull/111065 indicates that this project was merged with `at-spi2-atk`. That PR was became stale and was closed though.

**Comment by iMichka** [comment]
#111065 should be revived. I don't have time for this now but anyone can pick it up. Closing here.

**Comment by chenrui333** [comment]
#154695

**Pull request closed without merging**
