### PR TITLE
Update Mono to 5.4.1.6

### PR DESCRIPTION
**Pull request by baz1860**
Updates Mono from 5.0.1.1 to 5.4.1.6 (Stable)

- [ Y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ Y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [Y ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [Y ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by fabriciomurta — COMMENTED** [review]
I was doing this same update until brew told me there were already that pull request. With these same changes I could install and run all tests.
But I believe for the next versions a `msbuild` formula should be created, and have msbuild depend on it (for both build and run), as it now complains saying `xbuild` will soon be deprecated.

**Comment by ilovezfs** [comment]
what version of fsharp goes with this release? it looks like the resource needs updating

**Comment by fabriciomurta** [comment]
merging the two packages kind of made it harder to maintain I'd say, because few people may actually use fsharp among the general crowd. But seems the .18 version of fsharp works just fine and could come in a subsequent pr.

Anyway, testing with 4.1.29 here
```
resource "fsharp" do
  url "https://github.com/fsharp/fsharp.git"
      :tag => "4.1.29",
      :revision => "1e9f26937cff8a22e8603c2176fab8100f03e6b1"
end
```

The two projects are developed separately so I guess it would be safe to use latest stable fsharp together. In mono site I see latest as 4.1.25 (http://download.mono-project.com/sources/fsharp/). That's most likely the one packaged with the original mono installer from mono-project.com.

**Comment by fabriciomurta** [comment]
It seems newer fsharp installations will either need to be patched to keep using xbuild, or a 'msbuild' package is made for brew. Last fsharp that looked for `xbuild` (without patching) was version 4.1.23, which I'm testing now.

```ruby
resource "fsharp" do
  url "https://github.com/fsharp/fsharp.git"
      :tag => "4.1.23",
      :revision => "35a4a5b1f26927259c3213465a47b27ffcd5cb4d"
end
```

I actually been working in the `msbuild` formula but at the moment stuck with it linking `dotnet` (cli) against OSX libcurl using LibreSSL and brew's OpenSSL (which seems be the reason that results in a segfault during build). I think that kegging curl and also making `dotnet` cli find that library instead of osx own libcurl may address the issue.

`xbuild` is left in mono with several issues and is being discouraged so, building the separate `msbuild` is kind of mandatory since 5.0.0. One of which is the _msbuild tasks_, which has been reported to work fine with `msbuild` built on linux/osx.

Just finished testing, fsharp 4.1.23 works nicely so it is good to be appended to this pull request.

**Comment by ilovezfs** [comment]
>EDIT: (little question: is the revision prop really required when we specify tag?? they look pretty overlapping and mutually exclusive)

Yes. That's how we verify the integrity of the tag (i.e. that there has been no re-tagging)

**Comment by ilovezfs** [comment]
>I actually been working in the msbuild formula but at the moment stuck with it linking dotnet (cli) against OSX libcurl using LibreSSL and brew's OpenSSL (which seems be the reason that results in a segfault during build).

@fabriciomurta do we need a `dotnet` formula too? I recall that was attempted unsuccessfully once: https://github.com/Homebrew/homebrew-core/pull/3691

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @baz1860! :+1:

**Comment by fabriciomurta** [comment]
> @fabriciomurta do we need a dotnet formula too? I recall that was attempted unsuccessfully once: #3691

I don't think so, msbuild installer "bootstraps" dotnet client by downloading a built copy of it. As far as I could see it is mostly used as a means to pull NuGet packages before attempting to build the project.

**Pull request closed without merging**
