### PR TITLE
netpbm 10.86.17

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

cc @Rylan12 @SMillerDev @dawidd6 (as we talked about this earlier)

### CODE REVIEW

**Comment by Rylan12** [comment]
Failure related to https://github.com/Homebrew/homebrew-core/pull/62077 and https://github.com/Homebrew/homebrew-core/pull/62023?

**Comment by chenrui333** [comment]
The tag and revision thing.

**Comment by chenrui333** [comment]
Doing the rebase now.

**Comment by SMillerDev** [comment]
I don't think SVN works quite the same as git in that regard.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
