### PR TITLE
php 7.4.0

### PR DESCRIPTION
**Pull request by morrislaptop**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alcaeus** [comment]
This needs some more changes:
* The `php@7.3` alias needs to be dropped
* PHP 7.3 needs to be added as `php@7.3` formula
* `php@7.4` alias pointing to `php` needs to be added

**Comment by SMillerDev** [comment]
7.3 should be a separate pull request. In practice I think the alias only needs to be renamed to php@7.4

**Comment by morrislaptop** [comment]
The php@7.3 alias was pointing to the php formula has been renamed to php@7.4 which takes care of the below points:

* The php@7.3 alias needs to be dropped
* php@7.4 alias pointing to php needs to be added

Will create a separate PR for `PHP 7.3 needs to be added as php@7.3 formula`

**Comment by derrabus** [comment]
Homebrew's php 7.3 patch set cannot be applied to 7.4 without modifications. This PR won't build.

**Comment by alcaeus** [comment]
Right, this also lacks some FFI stuff. I've previously copied a 7.4 formula from @javian that I've been using for a while now. Feel free to use that as starting point: https://github.com/alcaeus/homebrew-brew/blob/master/Formula/php%407.4.rb.

**Comment by alcaeus** [comment]
See https://github.com/Homebrew/homebrew-core/pull/47289 which takes care of build issues from this PR.

**Comment by morrislaptop** [comment]
Will close in favour of #47289

**Pull request closed without merging**
