### PR TITLE
icu4c 60.1

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @srl295 @DomT4

**Comment by DomT4** [comment]
Colour me pleasantly surprised by the lack of breakage.

**Comment by srl295** [comment]
@DomT4 Breakage is definitely a non-goal of ours…

**Comment by DomT4** [comment]
It's just one of those things with significant updates. When you have 20+ formula that directly depend on `icu4c` and a bunch of others with optional `icu4c` usage you go into significant updates just assuming somewhere there will be some issues 😄.

**Pull request closed without merging**
