### PR TITLE
adwaita-icon-theme: renamed from gnome-icon-theme

### PR DESCRIPTION
**Pull request by tschoonj**
It hasn't been called gnome-icon-theme for years...

### CODE REVIEW

**Comment by ilovezfs** [comment]
This should be one commit per formula, and have a comment about what bug is being fixed by the patch, and the date of the commit in the patch.

**Comment by tschoonj** [comment]
ok will fix that later

**Comment by tschoonj** [comment]
Happy with the changes?

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
