### PR TITLE
neovim 0.5.0

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by clason** [comment]
(Resources are still up-to-date wrt neovim's build script.)

**Comment by clason** [comment]
@carlocab beat you to it ;)

**Comment by carlocab** [comment]
Oops. I knew I was forgetting something. Distracted by football atm 😄

**Comment by carlocab** [comment]
Is tree-sitter not a dependency now? If it is, we can get rid of both `stable` and `head` blocks.

**Comment by clason** [comment]
It is; forgot how old 0.4.4 is 😆

**Review by fsouza — COMMENTED** [review]
Need to promote tree-sitter as a dependency for the whole thing and remove the CMakeLists.txt patching from the end of the file x)

**Comment by clason** [comment]
OK, everybody wants to get into that PR -- it's a commit war :)

(I'll stop editing then.)

**Comment by carlocab** [comment]
> OK, everybody wants to get in on that PR -- it's a commit war :)
> 
> (I'll stop editing then.)

I was actually waiting for you to push the fix! All done now.

**Review by carlocab — APPROVED** [review]

**Comment by clason** [comment]
I did, but @chenrui333 beat me to pushing it :)

**Comment by carlocab** [comment]
Took twenty minutes longer than I would've liked. Thanks for getting this started!

**Comment by clason** [comment]
My fault -- I should have done this right from the start :) 

(It _still_ feels like this got fast-tracked 😄 )

**Comment by carlocab** [comment]
We try! I think Arch may have done it first tho.

**Comment by clason** [comment]
But only by a bit, if so ;)

**Comment by clason** [comment]
(I would have been quicker, by the way, if Monterey hadn't broken  `bump-formula-pr`... *shakes fist*)

**Comment by chenrui333** [comment]
> I did, but @chenrui333 beat me to pushing it :)

:D

**Pull request closed without merging**
