### PR TITLE
quazip 1.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
The QuaZip library is licensed under the GNU Lesser General Public
License V2.1 plus a static linking exception.

STATIC LINKING EXCEPTION

The copyright holders give you permission to link this library with
independent modules to produce an executable, regardless of the license
terms of these independent modules, and to copy and distribute the
resulting executable under terms of your choice, provided that you also
meet, for each linked independent module, the terms and conditions of
the license of that module. An independent module is a module which is
not derived from or based on this library. If you modify this library,
you must extend this exception to your version of the library.

```

**Comment by chenrui333** [comment]
cc @Rylan12

**Comment by chenrui333** [comment]
moved to cmake

**Comment by Rylan12** [comment]
Based on the last line of the `STATIC LINKING EXCEPTION`:

> If you modify this library, you must extend this exception to your version of the library.

And the last line of the [`Classpath-exception-2.0`](https://spdx.org/licenses/Classpath-exception-2.0.html#licenseExceptionText) exception:

> If you modify this library, you may extend this exception to your version of the library, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.

I don't think this is the correct exception.

**Comment by chenrui333** [comment]
> Based on the last line of the `STATIC LINKING EXCEPTION`:
> 
> > If you modify this library, you must extend this exception to your version of the library.
> 
> And the last line of the [`Classpath-exception-2.0`](https://spdx.org/licenses/Classpath-exception-2.0.html#licenseExceptionText) exception:
> 
> > If you modify this library, you may extend this exception to your version of the library, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.
> 
> I don't think this is the correct exception.

I see, I will revert that change. Can you weigh in on the license part? Thanks! :)

**Comment by Rylan12** [comment]
I don't think this exception matches any SPDX exception. Before, we would just list the license without the exception in these cases (i.e. just `license "LGPL-2.1-or-later"`).

Now, though, we have the `:cannot_represent` symbol. We might want to start using that for situations like these. Alternatively, we could create a new symbol specifically for missing exceptions and have something like:

```ruby
license "LGPL-2.1-or-later" => { with: :non_spdx_exception }
```

Thoughts?

CC: @fxcoudert

**Comment by fxcoudert** [comment]
I think `:cannot_represent` is correct in this case

**Pull request closed without merging**
