### PR TITLE
youtube-dl 2017.10.20

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@zmwangx did `cron` crash?

**Comment by zmwangx** [comment]
Nope.
screen shot 2017-10-21 at 4 15 14 am
It was buried by ~100 other unread emails though.

**Comment by ilovezfs** [comment]
@zmwangx Does Cron Daemon have a middle name?

**Comment by zmwangx** [comment]
Yep, I believe it's Vixie.

**Pull request merged**
