### PR TITLE
xtitle: Change test assert_equal to assert_match

### PR DESCRIPTION
**Pull request by dj-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Altered test block to use assert_equal & to_s instead of string interpolation.

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/2d304b8b155e1083eef9354255bcd98398a92f86. Thank you for another contribution to Homebrew @dj-m! 😺

**Comment by dj-m** [comment]
@DomT4 inching along with any help I can give! Thanks for reviewing! 🙌🏾

**Comment by DomT4** [comment]
I see you've submitted quite a few! Will review those shortly. Working my way through the backlog bit by bit 😄.

**Comment by dj-m** [comment]
They're minor things, trying to build up some confidence before tackling harder bits @DomT4!

**Comment by DomT4** [comment]
No worries at all. [This](https://github.com/Homebrew/legacy-homebrew/pull/30131) was my first PR contribution to Homebrew, so you've broken less stuff than I did right off the bat 😉.

**Comment by MikeMcQuaid** [comment]
Thanks again @dj-m!

**Pull request merged**
