### PR TITLE
blahtexml: deprecate

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
From http://gva.noekeon.org/blahtexml/:

> Blahtex(ml) has moved to [github](https://github.com/gvanas/blahtexml)!

The latest commit in the GitHub repo https://github.com/gvanas/blahtexml was a bug fix made ~2 months ago, so I think although no release has been made for a while, it's still considered maintained.

**Comment by p-linnane** [comment]
> From its homepage http://gva.noekeon.org/blahtexml/:
> 
> > Blahtex(ml) has moved to [github](https://github.com/gvanas/blahtexml)!
> 
> The latest commit in the GitHub repo https://github.com/gvanas/blahtexml was a bug fix made ~2 months ago, so I think although no release has been made for a while, it's still considered maintained.

I see there have been intermittent commits over the years, but no new releases. Given the low download numbers (4 on macOS in the last 90 days, 8 on Linux in the last 90 days), I still think we should deprecate this. Let's see what other maintainers think.

**Review by carlocab — CHANGES_REQUESTED** [review]
We should try upstreaming the patches (assuming they haven't been applied upstream yet) first, and then ask upstream to cut a new release before declaring this unmaintained.

If upstream doesn't respond, then we can deprecate.

**Comment by p-linnane** [comment]
It looks like the patches are already upstreamed, but not in a release. I'll open an issue asking about the status of the project.

**Comment by p-linnane** [comment]
[Response from upstream](https://github.com/gvanas/blahtexml/issues/11#issuecomment-1470289603):
>Hello, thanks for the heads up. Indeed I haven't been actively working on blahtexml for a few years, as it works fine for me as is (I use it almost every day as part of our documentation flow).
>
>There were a couple of (minor) bug fixes recently, and I'd be happy to make a release with these. This said, I guess the decision of keeping or not blahtexml in Homebrew would be best based on how many other people find it useful.

**Comment by p-linnane** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/126830.

**Pull request closed without merging**
