### PR TITLE
objfw 0.90.2 (new formula)

### PR DESCRIPTION
**Pull request by Midar**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is required by scrypt-pwgen.

### CODE REVIEW

**Comment by Midar** [comment]
> * C: 14: col 3: Formulae should not have an `option`
> * Formulae should not have a `HEAD` or `devel` spec

I don't understand this. Are options and HEAD Formulae not desired anymore?

**Comment by Midar** [comment]
> Indeed. Options and HEAD can't be tested on our CI machines. Thus options often bitrot and cause users trouble. So we prefer to have optionless formulas, which most users can download in binary form.

I see. I'm fine with removing the options.

> Head is only for widely-used formulas.

What about software that mostly lives at HEAD and only does irregular releases, as is the case here?

**Comment by fxcoudert** [comment]
@Midar then this software is a bad fit for a package manager / software distributor such as Homebrew. I suggest you ask upstream to do more regular releases (_release early, release often_).

**Comment by Midar** [comment]
Releases happen and are stable, but some software requires HEAD.

I removed HEAD and options now.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @Midar for your contribution to Homebrew!

**Pull request closed without merging**
