### PR TITLE
Remove deprecated licenses

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Remove licenses from 1479 formulae.

These formulae contain deprecated license identifiers (e.g. `GPL-3.0`) and should be replaced with a non-deprecated license in the future (e.g. `GPL-3.0-only` or `GPL-3.0-or-later`)

CC: @MikeMcQuaid

### CODE REVIEW

**Review by MikeMcQuaid — DISMISSED** [review]
Sad but necessary until we get these right.

**Comment by sjackman** [comment]
Having the deprecated `GPL-3.0` in the formula seems more useful that no license at all. What's the motivation for this PR? Why not leave it as is until a future PR can change these to the more specific `GPL-3.0-only` or `GPL-3.0-or-later`?

**Comment by MikeMcQuaid** [comment]
> Having the deprecated `GPL-3.0` in the formula seems more useful that no license at all.

I think it's an important distinction and while there's still energy to get licenses set on formulae it would be good to get them entered correctly rather than have a deprecated placeholder.

**Comment by Rylan12** [comment]
Furthermore, I'm trying to get https://github.com/Homebrew/brew/pull/8201 merged (which will enforce using `GPL-3.0-only` or `GPL-3.0-or-later` instead of `GPL-3.0`. If https://github.com/Homebrew/brew/pull/8201 is merged without formulae in homebrew/core complying all `tap_syntax` checks will fail because `brew audit` will fail on these formulae.

**Comment by Rylan12** [comment]
Closing because https://github.com/Homebrew/brew/pull/8201 now only checks for deprecated licenses on `brew audit --strict` so this is no longer necessary.

**Pull request closed without merging**
