### PR TITLE
emacs: remove options.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
See https://github.com/Homebrew/homebrew-core/issues/31510.

### CODE REVIEW

**Comment by muffinmad** [comment]
I used to install emacs like this `brew install emacs --with-cocoa --HEAD`.

Now `--with-cocoa` option is gone and emacs always compiled with `--without-ns` option. This leads to terminal-only emacs and there are no Emacs.app any more.

How can I build Emacs.app now?

**Comment by MikeMcQuaid** [comment]
@muffinmad As the caveats have said for a while: `brew cask install emacs`.

**Comment by muffinmad** [comment]
@MikeMcQuaid but I need recent development version and not 26.1 provided with cask

**Comment by MikeMcQuaid** [comment]
@muffinmad You will have to maintain it yourself in a tap. See https://github.com/Homebrew/homebrew-core/issues/31510

**Pull request closed without merging**
