### PR TITLE
zrepl 0.2.0

### PR DESCRIPTION
**Pull request by JMoVS**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I don't know what's wrong with my fork but when I *don't* remove the workflow file, I receive:

```
To https://github.com/jmovs/homebrew-core.git
 ! [remote rejected]       master -> master (refusing to allow an integration to create or update .github/workflows/generate_formulae.brew.sh_data.yml)
error: Fehler beim Versenden einiger Referenzen nach 'https://JMoVS@github.com/jmovs/homebrew-core.git'
```

as an error

### CODE REVIEW

**Comment by JMoVS** [comment]
any ideas on how to solve this, @fxcoudert ?

**Comment by fxcoudert** [comment]
Maybe delete your fork and start again?

**Comment by JMoVS** [comment]
seems to me it's like a github.com issue, but I have no idea where I could even file a bug about this

**Comment by JMoVS** [comment]
Sent an email to support, let's see what they say

**Pull request closed without merging**
