### PR TITLE
bzt 1.14.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Run into test failure with python 3.8

```
[2020-03-10 21:35:22,120 ERROR root] AttributeError: 'Constant' object has no attribute 'kind'
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/bzt/cli.py", line 258, in perform
    self.engine.prepare()
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/bzt/engine/engine.py", line 195, in prepare
    self.__prepare_provisioning()
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/bzt/engine/engine.py", line 591, in __prepare_provisioning
    self.provisioning.prepare()
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/bzt/modules/provisioning.py", line 73, in prepare
    executor.prepare()
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/bzt/modules/apiritif/executor.py", line 62, in prepare
    self.script = self.__tests_from_requests()
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/bzt/modules/apiritif/executor.py", line 110, in __tests_from_requests
    builder.save(filename)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/bzt/modules/apiritif/generator.py", line 1429, in save
    fds.write(astunparse.unparse(self.tree))
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/__init__.py", line 13, in unparse
    Unparser(tree, file=v)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 38, in __init__
    self.dispatch(tree)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 78, in _Module
    self.dispatch(stmt)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 120, in _Assign
    self.dispatch(t.value)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 723, in _Call
    self.dispatch(e)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/local/Cellar/bzt/1.14.1/libexec/lib/python3.8/site-packages/astunparse/unparser.py", line 551, in _Constant
    if t.kind == "u":
```

**Comment by chenrui333** [comment]
relates to https://github.com/simonpercivall/astunparse/issues/43

**Comment by chenrui333** [comment]
Should be fixed now. It can only run with python 3.7 at this moment.

**Comment by Bo98** [comment]
Can we wait until #50712 is merged (or the CI fails) to avoid merge conflicts?

**Comment by chenrui333** [comment]
Just FYI, this formula does not live well with python 3.8

**Comment by chenrui333** [comment]
we can chat about this tomorrow, I am totally ok with the python upgrade first.

**Comment by Bo98** [comment]
I think I can get this merged at the same time with some `git rebase` work and being careful about the bottle.

**Pull request closed without merging**
