### PR TITLE
openssl@1.1: backport two fixes

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by tdsmith** [comment]
On principle, I worry about cherry-picking commits for openssl. :( I don't have the expertise to make sure they don't depend on other fixes applied to master, especially since openssl test coverage is dismal. My preference would be to wait for the next release. What's the advantage to patching these now? Projects like pyopenssl won't test correctly on other platforms until this gets fixed by an upstream release anyway.

**Comment by DomT4** [comment]
We do it considerably less than a lot of package managers, but we are prone to backporting fixes for our current `openssl` formula because it saves us grief & I think that's "fair game" here too. 

Bearing in mind that all of the patches are picked off their respective branch rather than `master`, and go through two sets of individual review & two sets of CI upstream. We don't cherry pick from `master` for OpenSSL, pretty much ever.

> What's the advantage to patching these now?

Less breakage for users, is the obvious one. Beyond that, we can test stuff against 1.1.0 cleanly with the chance of it turning out to be some unrelated bug lessened. The next release could well be months unless 1.1.0 pretty drastically departs from OpenSSL's classic stable release timetable, or rather lack of release timetable.

In the mean time we block projects like `pyopenssl` from using Homebrew to test against, which reduces usage of `openssl@1.1` as a whole, which reduces the amount of real-world testing our new versioning system gets before we start using it more widely.

I'm happy to wait, but I think we'd be being overly-cautious here personally. Potentially worth a discussion point is that we don't regularly turn down patches for other crypto libraries, only ever OpenSSL.

**Comment by tdsmith** [comment]
FWIW I checked in with the PyCA devs and they don't want us to patch.

If you're happy to wait, shall we close this?

> Less breakage for users, is the obvious one.

I guess I wonder what breakage means and who the users are. Holding off on these patches shouldn't affect `brew` users.

> Potentially worth a discussion point is that we don't regularly turn down patches for other crypto libraries, only ever OpenSSL.

Yes, I think we should always approach patches against security-critical libraries conservatively.

**Comment by DomT4** [comment]
> Yes, I think we should always approach patches against security-critical libraries conservatively.

You're welcome to start enforcing this, as long as we do it consistently. A lot of my gripe with bothering to maintain the core any more is that we can't ever decide anything consistently & it makes everyone's lives harder.

**Comment by tdsmith** [comment]
> A lot of my gripe with bothering to maintain the core any more is that we can't ever decide anything consistently & it makes everyone's lives harder.

Yes, it would be nice to have a conversation about policy-setting at some point.

**Comment by DomT4** [comment]
As you said yourself in the past, too many cooks in the kitchen. I've basically given up on the team ever agreeing on anything consistently.

**Comment by tdsmith** [comment]
Yeah, that's why I think defining a process for legislating policy or accepting changes would be helpful, especially as the team grows. I don't have a next action item, though. :/

**Comment by DomT4** [comment]
No, me either to be honest.

It's a cache-22-esque situation; we need to expand the team so maintaining any single aspect of Homebrew doesn't fall overwhelmingly on one or two people, including things like you & Python, but every expansion of the team makes agreeing things as a team even more difficult than it already has become, which is massively demotivating & frustrating.

**Comment by MikeMcQuaid** [comment]
> but every expansion of the team makes agreeing things as a team even more difficult than it already has become, which is massively demotivating & frustrating.

There is no agreement as a team and I don't think it's worth seeking to get it. As I've stated privately before: I think you should have a corresponding amount of say on a particular item based on how much you work on it and how responsible you've proved yourself to be in the past in cleaning up your mistakes. From that point of view, I actually agree with @tdsmith's viewpoint on being careful on OpenSSL patches but given @DomT4's almost solely working on this I think the final decision should be up to him on whether to merge this.

**Pull request closed without merging**
