### PR TITLE
cargo-instruments 0.3.0 (new formula)

### PR DESCRIPTION
**Pull request by smorimoto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by zbeekman — APPROVED** [review]
LGTM

**Comment by imbsky** [comment]
Thanks for the review 🙂

**Comment by zbeekman** [comment]
No problem. I'm not a rust expert so I may let other maintainers take a glance at this since it's a new formula. If no one else has looked at this or merged it in ~24 hours please ping me.

**Review by dawidd6 — APPROVED** [review]

**Comment by imbsky** [comment]
Sure.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you @imbsky!

**Comment by imbsky** [comment]
Thank you, too!

**Pull request closed without merging**
