### PR TITLE
osquery 3.3.2

### PR DESCRIPTION
**Pull request by VonUniGE**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
That's not the right url. Your update points it to a pre-built binary. Please point to the new tarbal version.

**Comment by VonUniGE** [comment]
I've corrected url and sha256 but patches doesn't apply:
```
﻿==> Patching
==> Applying 512f775c.diff
patching file osquery/config/config.cpp
Hunk #1 FAILED at 30.
Hunk #2 FAILED at 899.
Hunk #3 FAILED at 927.
3 out of 3 hunks FAILED -- saving rejects to file osquery/config/config.cpp.rej
patching file osquery/config/packs.cpp
Hunk #1 FAILED at 19.
Hunk #2 FAILED at 72.
2 out of 2 hunks FAILED -- saving rejects to file osquery/config/packs.cpp.rej
patching file osquery/config/tests/config_tests.cpp
Hunk #1 FAILED at 240.
1 out of 1 hunk FAILED -- saving rejects to file osquery/config/tests/config_tests.cpp.rej
patching file osquery/core/conversions.cpp
Hunk #1 FAILED at 13.
Hunk #2 FAILED at 348.
2 out of 2 hunks FAILED -- saving rejects to file osquery/core/conversions.cpp.rej
patching file osquery/core/conversions.h
Hunk #1 FAILED at 138.
1 out of 1 hunk FAILED -- saving rejects to file osquery/core/conversions.h.rej
patching file osquery/core/tests/conversions_tests.cpp
Hunk #1 FAILED at 75.
1 out of 1 hunk FAILED -- saving rejects to file osquery/core/tests/conversions_tests.cpp.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/osquery--patch-20190304-70454-13w9qg5/512f775c.diff` exited with 1.

**Comment by VonUniGE** [comment]
The patch is needed removing it gives:
```
make[2]: *** [osquery/CMakeFiles/osquery_logger_aws_plugins.dir/logger/plugins/aws_firehose.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 63%] Built target osquery_numeric_monitoring_plugins
In file included from /tmp/osquery-20190304-70989-ykk4hq/osquery-3.3.2/osquery/logger/plugins/aws_kinesis.cpp:30:
In file included from /tmp/osquery-20190304-70989-ykk4hq/osquery-3.3.2/osquery/logger/plugins/aws_kinesis.h:24:
In file included from /tmp/osquery-20190304-70989-ykk4hq/osquery-3.3.2/osquery/logger/plugins/aws_log_forwarder.h:22:
/tmp/osquery-20190304-70989-ykk4hq/osquery-3.3.2/osquery/utils/aws_util.h:78:13: error: only virtual member functions can be marked 'override'
      const override;
            ^~~~~~~~
1 error generated.
make[2]: *** [osquery/CMakeFiles/osquery_logger_aws_plugins.dir/logger/plugins/aws_kinesis.cpp.o] Error 1
make[1]: *** [osquery/CMakeFiles/osquery_logger_aws_plugins.dir/all] Error 2
make: *** [all] Error 2

**Comment by fxcoudert** [comment]
Upstream mentions awk-sdk-cpp 1.4.55 in some commits: https://github.com/facebook/osquery/commits/3.3.2/tools so let's try that

**Pull request closed without merging**
