### PR TITLE
zsh-completions: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by Amar1729**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See #75943.

### CODE REVIEW

**Comment by Amar1729** [comment]
```
sha256sum *tar.gz

91c622e31c02e1405484ff6f8ebd891174d0160bddd8e9a6ab46eb9b71898a95  bottles/zsh-completions--0.32.0.arm64_big_sur.bottle.tar.gz
8de3c33a6695339766ba8446637e4a406105dbd86c7aa3d5da8d20496fc07a03  bottles/zsh-completions--0.32.0.big_sur.bottle.tar.gz
8de3c33a6695339766ba8446637e4a406105dbd86c7aa3d5da8d20496fc07a03  bottles/zsh-completions--0.32.0.catalina.bottle.tar.gz
1ee78c06fbe812cbf39b715c90a4c953a74af5422ff80dac83fb923db034f747  bottles/zsh-completions--0.32.0.mojave.bottle.tar.gz
```

**Comment by Amar1729** [comment]
After rebuild:

```
> sha256sum *.tar.gz

0d433bc55d208e9cc66d74017a6a5d5ae1a768e51d984ab2e25a4dcf1a01899e  zsh-completions--0.32.0.arm64_big_sur.bottle.tar.gz
b717660dece7fdbcd772f6d331679518a580e020cff879c58e9cc8a3b9c51ab5  zsh-completions--0.32.0.big_sur.bottle.tar.gz
b717660dece7fdbcd772f6d331679518a580e020cff879c58e9cc8a3b9c51ab5  zsh-completions--0.32.0.catalina.bottle.tar.gz
b717660dece7fdbcd772f6d331679518a580e020cff879c58e9cc8a3b9c51ab5  zsh-completions--0.32.0.mojave.bottle.tar.gz
```

Still the same difference as above between the big sur arm/x86 bottles.

**Comment by Amar1729** [comment]
After rebuild / relocation fix, hashes match:
```
> sha256sum *.tar.gz

a70978173faa1ce102d7a1fe224c4fcc90ef56f414f42781c109d4b4883bcaa9  zsh-completions--0.32.0.arm64_big_sur.bottle.tar.gz
a70978173faa1ce102d7a1fe224c4fcc90ef56f414f42781c109d4b4883bcaa9  zsh-completions--0.32.0.big_sur.bottle.tar.gz
a70978173faa1ce102d7a1fe224c4fcc90ef56f414f42781c109d4b4883bcaa9  zsh-completions--0.32.0.catalina.bottle.tar.gz
a70978173faa1ce102d7a1fe224c4fcc90ef56f414f42781c109d4b4883bcaa9  zsh-completions--0.32.0.mojave.bottle.tar.gz

```

**Review by carlocab — APPROVED** [review]
Thanks, @Amar1729!

**Pull request closed without merging**
