### PR TITLE
libx11 1.7.4

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
May need to check if test segfaults are related to update:
```
brew test --retry --verbose dwm
brew test --retry --verbose ncview
brew test --retry --verbose xsel
```

```
  ==> Testing dwm
  ==> DISPLAY= /opt/homebrew/Cellar/dwm/6.3/bin/dwm 2>&1
  sh: line 1: 32660 Segmentation fault: 11  DISPLAY= /opt/homebrew/Cellar/dwm/6.3/bin/dwm 2>&1
  warning: no locale support
```

```
  ==> Testing ncview
  ==> DISPLAY= /opt/homebrew/Cellar/ncview/2.1.8_6/bin/ncview -c 2>&1
  sh: line 1: 87112 Segmentation fault: 11  DISPLAY= /opt/homebrew/Cellar/ncview/2.1.8_6/bin/ncview -c 2>&1
```

```
  ==> Testing xsel
  ==> /opt/homebrew/Cellar/xsel/1.2.0/bin/xsel --help
  ==> /opt/homebrew/Cellar/xsel/1.2.0/bin/xsel --version
  ==> DISPLAY= /opt/homebrew/Cellar/xsel/1.2.0/bin/xsel -o 2>&1
  sh: line 1: 33938 Segmentation fault: 11  DISPLAY= /opt/homebrew/Cellar/xsel/1.2.0/bin/xsel -o 2>&1
```

**Comment by iMichka** [comment]
These errors look new to me.

**Comment by mhmdanas** [comment]
libx11 1.7.5 has been released, and it includes a commit that seems relevant (take this with a grain of salt though, I know zilch about C): https://github.com/mirror/libX11/commit/76d1cc3c1ce943c6ff81dc8c62a1d1b30fabf02e

**Comment by SMillerDev** [comment]
linkage failures on linux seem unrelated, merging

**Pull request closed without merging**
