### PR TITLE
gdal 2.3.2

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hopefully this fixes #32869

**Comment by javian** [comment]
Looks like there's only audit issues left.
```
20:01:56 ==> brew audit gdal --online
20:02:28 ==> FAILED
20:02:28 Error: 2 problems in 1 formula detected
20:02:28 gdal:
20:02:28   * Stable: The URL http://download.osgeo.org/gdal/2.3.2/gdal-2.3.2.tar.xz should use HTTPS rather than HTTP
20:02:28   * HEAD: The URL https://svn.osgeo.org/gdal/trunk/gdal is not a valid svn URL
```

**Comment by javian** [comment]
They have a github site `https://github.com/OSGeo/gdal`

**Comment by fxcoudert** [comment]
Still fails on High Sierra:

```
In file included from ogrgeometryfactory.cpp:31:
In file included from /private/tmp/gdal-20181219-11476-1f7kwtz/gdal-2.3.2/port/cpl_port.h:602:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
```

To be honest, we have this issue on quite a few formulas now, and I don't understand why 😢

**Comment by fxcoudert** [comment]
Given this is the current state on High Sierra, and we don't know how to fix it… merging.

**Pull request closed without merging**
