### PR TITLE
sproxy: update urls, add license

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The `stable` and `livecheck` block URLs for `sproxy` redirect from HTTP to HTTPS, so this PR updates the URLs accordingly.

### CODE REVIEW

**Comment by samford** [comment]
The license appears to be `GPL-2.0-or-later`. The FAQ on the website simply says, "Sproxy is licensed under the GNU Public License." The `README` file in the current tarball says, "Consult the file COPYING for complete license information" but...there's no `COPYING` file.

The only first-party source files with license comments seem to be the various `Makefile.am` files (e.g., in `/`, `doc`, `lib`, `src`, `utils`) and these contain a GPL license comment using the "or...later" language. For example, from `/src/Makefile.am`:

```
##
## src/Makefile.am
##
## Copyright (C) 2003 by
## Jeffrey Fulmer - <jdfulmer@armstrong.com>
## This file is distributed as part of sproxy
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
##
```

**Comment by samford** [comment]
Seeing a `mandir` issue on Linux CI and I'm able to replicate this in a local Linux container on macOS:

```
==> brew audit sproxy --online --git --skip-style
==> FAILED
  sproxy:
    * A top-level "man" directory was found.
      Homebrew requires that man pages live under "share".
      This can often be fixed by passing `--mandir=#{man}` to `configure`.
  Error: 1 problem in 1 formula detected
```

It seems like the existing `inreplace` call isn't cutting it anymore and even adding `"--mandir=#{man}"` to the `configure` args doesn't resolve the issue.

**Comment by ZhongRuoyu** [comment]
> It seems like the existing `inreplace` call isn't cutting it anymore and even adding `"--mandir=#{man}"` to the `configure` args doesn't resolve the issue.

That's because of this in `lib/Makefile.am`. The modules are installed from separate tarballs, and the `mandir` isn't passed to Perl.

```makefile
MODULES:
	if test $(haveconfig) = "no"; then \
	  $(GUNZIP) -9cd JoeDog-Config-1.2.tar.gz | $(TAR) xvf -; \
	  cd JoeDog-Config-1.2 && \
	  $(PERL) Makefile.PL LIB=$(prefix)/lib/sproxy \
	  && make; \
	fi
```

This should do it:

```diff
--- a/Formula/sproxy.rb
+++ b/Formula/sproxy.rb
@@ -119,7 +119,9 @@ class Sproxy < Formula
     # configure, though, as a result of this change, that flag would be honored.
     # Reported 10th May 2016 to https://www.joedog.org/support/
     inreplace "doc/Makefile.am", "$(prefix)/man", "$(mandir)"
-    inreplace "lib/Makefile.am", "Makefile.PL", "Makefile.PL PREFIX=$(prefix)"
+    inreplace "lib/Makefile.am",
+              "Makefile.PL",
+              "Makefile.PL PREFIX=$(prefix) INSTALLSITEMAN3DIR=$(mandir)/man3"
 
     # Only needed due to the change to "Makefile.am"
     system "autoreconf", "-fiv"
```

Reference to `INSTALLSITEMAN3DIR`: https://perldoc.perl.org/ExtUtils::MakeMaker#INSTALLSITEMAN3DIR.

**Comment by samford** [comment]
> That's because of this in `lib/Makefile.am`. The modules are installed from separate tarballs, and the `mandir` isn't passed to Perl.

I had a feeling it probably had something to do with the other `Makefile` files but hadn't dug into it yet. Thanks for the fix!

**Comment by ZhongRuoyu** [comment]
This looks fine now, so I'll add a https://github.com/Homebrew/homebrew-core/labels/ready%20to%20merge; do we still want https://github.com/Homebrew/homebrew-core/labels/CI-no-bottles, though?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
