### PR TITLE
openmodelica: fix build with CMake 3.20+

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
I think you are going to need the patch from https://github.com/OpenModelica/OpenModelica/commit/71aa2f871639041f3569fafe1b1cea25b84981ff due to latest `cmake` in Homebrew.

**Comment by carlocab** [comment]
Forgot that you mentioned that in the last PR. Will try applying that patch.

**Comment by carlocab** [comment]
Nope. Still no dice.

**Comment by cho-m** [comment]
From local build, the errors I see (as some errors are occur earlier in `cmake` log):
```make
find 3rdParty/sundials-5.4.0/build/lib* -xtype f -exec cp -pf {} /private/tmp/openmodelica-20210507-36765-jkrbaw/build/lib/x86_64-darwin20.4.0/omc ";"
find: -xtype: unknown primary or operator
make[4]: *** [/private/tmp/openmodelica-20210507-36765-jkrbaw/build/lib/x86_64-darwin20.4.0/omc/libsundials_ida.a] Error 1
make[3]: *** [sundials] Error 2
make[3]: *** Waiting for unfinished jobs....

...

make[6]: Nothing to be done for `install-data-am'.
Run make install-doxydoc to generate and install Doxygen documentation.
test ! `uname` = Darwin || install_name_tool -id @rpath/libipopt.0.0.0.dylib 3rdParty/Ipopt/lib/libipopt.0.0.0.dylib
test ! `uname` = Darwin || install_name_tool -id @rpath/libcoinmumps.1.5.2.dylib 3rdParty/Ipopt/lib/libcoinmumps.1.5.2.dylib
test ! `uname` = Darwin || install_name_tool -change "`pwd`/3rdParty/Ipopt/lib/libcoinmumps.1.dylib" @rpath/libcoinmumps.1.dylib 3rdParty/Ipopt/lib/libipopt.0.0.0.dylib
cp -a 3rdParty/Ipopt/lib*/*.* /private/tmp/openmodelica-20210507-36765-jkrbaw/build/lib/x86_64-darwin20.4.0/omc
make[2]: *** [omc-bootstrapped] Error 2
make[1]: *** [omc-and-runtimeCPPinstall] Error 2
make: *** [omc.skip] Error 2
```

At least the `autoreconf` and `cmake` patch fixed other issues I saw when I previously built locally.
Probably need to see if there is anything upstream.

**Comment by cho-m** [comment]
Maybe related upstream PR: https://github.com/OpenModelica/OpenModelica/pull/7238
Corresponding commit: https://github.com/OpenModelica/OpenModelica/commit/65bb214bd59e6ab6610e0d390b252c24409a5abc

Probably need some other dependencies like `findutils` (for `gfind`)

**Comment by carlocab** [comment]
> I don't think this will cleanly patch.

Well, let's give it a try. I'm not sure I have the patience to backport this one. If this formula ends up to be the only one blocking  #74843, then I'm ready to disable it.

**Comment by cho-m** [comment]
I am also trying a build with just basic fixes on **1.16.5** (with `autoreconf` and `cmake` patch).
If that works, we could just ignore **1.17.0** update and just get build fixes in.
If both this and 1.16.5 fail, it is probably better to prioritize `gcc`.

**Comment by cho-m** [comment]
I can confirm that 1.16.5 with `autoreconf` and 1st patch for `cmake` successfully built on macOS 11.3 via Rosetta layer:
```console
🍺  /usr/local/Cellar/openmodelica/1.16.5: 5,538 files, 159.0MB, built in 15 minutes 46 seconds
Removing: /Users/cho-m/Library/Caches/Homebrew/openmodelica--patch--cea5c51f88e1b55c73065f64cae8c85e3bf9450f2e6167f155eb07757e0cf4de.patch... (26.6KB)
```

I wasn't able to build 1.17.0.

**Comment by carlocab** [comment]
Ok, let's do that. Thanks, @cho-m.

**Comment by carlocab** [comment]
Merging, as this is blocking #74843.

**Pull request merged**
