### PR TITLE
libevent 2.1.12

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
```
Error: 2 failed steps!
brew test --verbose adios2
brew test --verbose agda
```

For `adios2` see https://github.com/Homebrew/homebrew-core/pull/57315#issuecomment-653736274 and https://github.com/Homebrew/homebrew-core/pull/55556 -- perhaps just a revision bump?

For `agda` see https://github.com/Homebrew/homebrew-core/pull/57315#issuecomment-653736274 and https://github.com/Homebrew/homebrew-core/issues/55253

I was not successful in getting this to build with `doxygen` support for either the `man` pages or the `html` output after several tries, so I have removed them. Please let me know if this is acceptable.

Thanks.

**Comment by miccal** [comment]
A revision bump for `adios2` was not successful. Since neither failing tests are a result of this PR, I think this could be merged?

**Comment by miccal** [comment]
Thank you @Rylan12 and @chenrui333 for your help in my PR for `glib` -- I hope you do not mind if I trouble you again to review what I have done here.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@miccal great work, logged a separate build issue and proceeding with the merge.

**Comment by miccal** [comment]
Thank you so much @chenrui333.

**Comment by chenrui333** [comment]
> Thank you so much @chenrui333.

Thank you!! Great to have you help maintaining and improving homebrew project! :)

**Pull request closed without merging**
