### PR TITLE
texlive: revision bump (icu4c 70.1)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Also, update the resources (thanks @branchvincent).

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
`brew fetch` failed on Big Sur for some reason. Merging this to fix broken linkage then will just dispatch a separate Big Sur bottle.

**Comment by carlocab** [comment]
Actually, we can probably just build the Big Sur bottle in #96101.

**Comment by carlocab** [comment]
Weird.
```
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew pr-upload --debug --committer=BrewTestBot\ \<1589480\+BrewTestBot@users.noreply.github.com\> --root-url=[https://ghcr.io/v2/homebrew/core`](https://ghcr.io/v2/homebrew/core%60) was terminated by uncaught signal KILL.
```

**Comment by Bo98** [comment]
I suspect OOM from https://github.com/Homebrew/brew/blob/7c4247eec9685071cbadc52952d0f2afadf022cc/Library/Homebrew/github_packages.rb#L342, which I will try fix before we merge texlive 62297. Self hosted will probably work.

**Comment by carlocab** [comment]
> I suspect OOM 

That was my guess as well, though I didn't try tracking it down.

> Self hosted will probably work.

Yup, the latest publish job uses the self-hosted runner.

**Comment by carlocab** [comment]
Thanks @Bo98!

**Comment by Bo98** [comment]
I'll fix it.

**Pull request closed without merging**
