### PR TITLE
clarinet 1.8.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error[E0080]: evaluation of constant value failed
      --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/v8-0.47.1/src/isolate.rs:1216:3
       |
  1216 |   assert!(size_of::<TypeId>() == size_of::<u64>());
       |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: size_of::<TypeId>() == size_of::<u64>()', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/v8-0.47.1/src/isolate.rs:1216:3
       |
       = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by hugocaillard** [comment]
hey @chenrui333, did you open this PR manually?
We haven't push 1.8.0 on our main branch yet 🤔

**Comment by chenrui333** [comment]
yes, opened it manually. 😄 

I saw the bot PR, gonna close this one now.

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/142106

**Comment by hugocaillard** [comment]
Thank @chenrui333.
Although I don't get why you opened it. Hopefully the build failed. Was it for investigation purpose? Would you have merge even if we hadn't release it? I was kind of worried at first when I saw the PR

**Comment by chenrui333** [comment]
> Thank @chenrui333. Although I don't get why you opened it. Hopefully the build failed. Was it for investigation purpose? Would you have merge even if we hadn't release it? I was kind of worried at first when I saw the PR

we wont

**Comment by chenrui333** [comment]
@hugocaillard let me know if that makes sense.

**Comment by hugocaillard** [comment]
Yeah it kind it does. I don't really get why you opened the PR in the first place though

**Comment by chenrui333** [comment]
> Yeah it kind it does. I don't really get why you opened the PR in the first place though

it is being autobumped in batch

**Pull request closed without merging**
