### PR TITLE
compcert 3.4

### PR DESCRIPTION
**Pull request by fxcoudert**
This should fix compcert on Mojave

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
Error: CompCert requires one of the following Coq versions: 8.8.0, 8.7.2, 8.7.1, 8.7.0, 8.6.1
```

**Comment by javian** [comment]
Looks like an issue with the Menhir dep which has a new release out.

**Comment by DomT4** [comment]
Pulling in https://github.com/AbsInt/CompCert/commit/b8552c55a3c65a3f598d155aeb764e68841ba501 & https://github.com/AbsInt/CompCert/commit/4d4e82ae48d34c4930a4e176db8ee54ac5ca2fab as patches would likely resolve that, I guess.

**Comment by fxcoudert** [comment]
Fails to build because menhir was not revbumped when ocaml was last updated. Updating menhir to the latest version will do the job.

**Pull request closed without merging**
