### PR TITLE
cmake cmake-docs 3.24.3

### PR DESCRIPTION
**Pull request by yurikoles**
- cmake 3.24.3
- cmake-docs 3.24.3

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
The `CI-skip-recursive-dependents` may be required to speedup CI.

**Review by chenrui333 — DISMISSED** [review]

**Comment by yurikoles** [comment]
Dear maintainers,

Is `Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections` may be fixed by a simple revision bump? I assumed it is and bumped `rav1e` and `linux-pam`.

**Comment by cho-m** [comment]
> Dear maintainers,
> 
> Is `Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections` may be fixed by a simple revision bump? I assumed it is and bumped `rav1e` and `linux-pam`.

We've already rebuilt the bottles, so you can drop the commits and just rebase.

**Comment by dawidd6** [comment]
The only failure on Linux:

```
 ==> Testing quazip
  ==> /home/linuxbrew/.linuxbrew/opt/qt/bin/qmake test.pro
  Info: creating stash file /tmp/quazip-test-20221108-186836-zd99gz/.qmake.stash
  ==> make
  g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtGui -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/share/qt/mkspecs/linux-g++ -o test.o test.cpp
  g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -Wl,-rpath-link,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -o test  test.o   -L/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/lib -lquazip1-qt6 /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Gui.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Core.so -lpthread -lGL   
  ==> ./test
  ./test: error while loading shared libraries: libquazip1-qt6.so.1.3.0: cannot open shared object file: No such file or directory
  ==> Testing quazip (again)
  ==> /home/linuxbrew/.linuxbrew/opt/qt/bin/qmake test.pro
  Info: creating stash file /tmp/quazip-test-20221108-187032-1ljecm/.qmake.stash
  ==> make
  g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtGui -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/share/qt/mkspecs/linux-g++ -o test.o test.cpp
  g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -Wl,-rpath-link,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib -o test  test.o   -L/home/linuxbrew/.linuxbrew/Cellar/quazip/1.3/lib -lquazip1-qt6 /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Gui.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0/lib/libQt6Core.so -lpthread -lGL   
  ==> ./test
  ./test: error while loading shared libraries: libquazip1-qt6.so.1.3.0: cannot open shared object file: No such file or directory
  Error: quazip: failed
```

**Comment by yurikoles** [comment]
This `quazip` error is unrelated and reproducible on current `master` / Linux. [mesa update](https://github.com/Homebrew/homebrew-core/actions/runs/3415153491/jobs/5684028043) also showed it.

**Comment by yurikoles** [comment]
I can add that the test is being built via `qmake` against the formula, which is poured from the bottle.

**Review by SMillerDev — APPROVED** [review]

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
