### PR TITLE
cdk8s 1.0.0-beta.3

### PR DESCRIPTION
**Pull request by campionfellin**
Signed-off-by: campionfellin <campionfellin@gmail.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please don't submit beta software.

**Comment by campionfellin** [comment]
@SMillerDev 

I was under the impression we could submit beta versions with the `--head` tag?

https://docs.brew.sh/Formula-Cookbook#unstable-versions-head

**Comment by SMillerDev** [comment]
That tag is just to indicate the location of the upstream repo.

**Comment by campionfellin** [comment]
Gotcha, thanks!

**Pull request closed without merging**
