### PR TITLE
instead 3.2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Looks like it moved to sdl2:

```
CMake Error at cmake/FindSDL2.cmake:23 (MESSAGE):
  Could not find SDL2
```

**Comment by ilovezfs** [comment]
```
Undefined symbols for architecture x86_64:
  "_CFBundleCopyResourcesDirectoryURL", referenced from:
      _macosx_init in main.c.o
  "_CFBundleGetMainBundle", referenced from:
      _macosx_init in main.c.o
  "_CFRelease", referenced from:
      _macosx_init in main.c.o
  "_CFURLGetFileSystemRepresentation", referenced from:
      _macosx_init in main.c.o
  "_OBJC_CLASS_$_NSArray", referenced from:
      objc-class-ref in macosx.m.o
  "_OBJC_CLASS_$_NSOpenPanel", referenced from:
      objc-class-ref in macosx.m.o
  "___CFConstantStringClassReference", referenced from:
      CFString in macosx.m.o
      CFString in macosx.m.o
      CFString in macosx.m.o
  "_objc_msgSend", referenced from:
      _open_file_dialog in macosx.m.o
```

**Comment by ilovezfs** [comment]
https://github.com/instead-hub/instead/issues/45

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/26952

**Pull request closed without merging**
