### PR TITLE
perl 5.38.0

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @carlocab!

**Review by SMillerDev — APPROVED** [review]

**Comment by pheiduck** [comment]
If I am right, `tcl` is missing as dependency for linux.

**Comment by carlocab** [comment]
That seems right. Would be good to work out how to fix `bioperl`, though. Which should hopefully suffice to fix `abricate` too.

**Comment by pheiduck** [comment]
help wanted

**Pull request closed without merging**
