### PR TITLE
consul-template 0.15.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Thanks to whoever upstream vendored everything.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 ` +14 −119` LOL.

**Comment by DomT4** [comment]
They've moved to vendoring? Nice. I'll trust you this all builds correctly, I've had enough `go` for the week 😄.

**Comment by ilovezfs** [comment]
Yeah, it works beautifully, modulo the fact that it still needs requires `make bootstrap`, which sneaks in that old gox thing through the backdoor.

**Comment by DomT4** [comment]
We could always keep just the `gox` resource. I vaguely recall that's the situation in at least a couple other formulae as well.

**Comment by ilovezfs** [comment]
Oh, no it's fine as is. The vendoring of gox is the same as the rest of it. I'm just still disappointed it needs that tool at all.

**Comment by DomT4** [comment]
Thanks for the clarification. Initially thought you meant that bit wasn't vendored for some reason and online fetching was still happening. Nice work here.

**Pull request closed without merging**
