### PR TITLE
bear 2.4.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by djerfy** [comment]
Can you replace `depends_on "python"` by `depends_on "python@2"`? Thx

**Comment by Moisan** [comment]
This [closed upstream issue](https://github.com/rizsotto/Bear/issues/203) indicates it should support Python3.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please.

**Comment by SMillerDev** [comment]
```
==> /usr/local/Cellar/bear/2.4.2/bin/bear true
env: python2: No such file or directory
Error: bear: failed
```

**Comment by igas** [comment]
Thank you @Moisan!

**Pull request closed without merging**
