### PR TITLE
mtools 4.0.41

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
failed on linux

```
  ==> make
  gcc-11  -DHAVE_CONFIG_H -DSYSCONFDIR=\"/home/linuxbrew/.linuxbrew/etc\" -DCPU_x86_64 -DVENDOR_pc -DOS_linux_gnu -g -O2 -I.  -I.  -c buffer.c
  gcc-11  -DHAVE_CONFIG_H -DSYSCONFDIR=\"/home/linuxbrew/.linuxbrew/etc\" -DCPU_x86_64 -DVENDOR_pc -DOS_linux_gnu -g -O2 -I.  -I.  -c charsetConv.c
  In file included from buffer.c:20:
  sysincludes.h:299:10: fatal error: xlocale.h: No such file or directory
    299 | #include <xlocale.h>
        |          ^~~~~~~~~~~
  compilation terminated.
  make: *** [Makefile:145: buffer.o] Error 1
  make: *** Waiting for unfinished jobs....
  In file included from charsetConv.c:19:
  sysincludes.h:299:10: fatal error: xlocale.h: No such file or directory
    299 | #include <xlocale.h>
        |          ^~~~~~~~~~~
  compilation terminated.
  make: *** [Makefile:145: charsetConv.o] Error 1
```

**Comment by carlocab** [comment]
Used to be in `glibc`, but no longer. Not sure what's mean to provide it now. CC @Homebrew/linux

**Comment by jonchang** [comment]
Pretty sure xlocale.h is supposed to be replaced with locale.h. This is likely an upstream bug. See https://sourceware.org/legacy-ml/libc-alpha/2017-08/msg00010.html

**Review by carlocab — APPROVED** [review]
Only 13 Linux installs in the past year (less than 1% of all installs in that time period).

If someone needs this on Linux, they can help fix it.

**Pull request closed without merging**
