### PR TITLE
logtalk 3.67.0

### PR DESCRIPTION
**Pull request by pmoura**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
> ⛔ It looks like @BrewTestBot cannot push to your PR branch. For future pull requests, please [allow maintainers to edit your PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to simplify the merge process.

@pmoura can you fix it for the future sake? Thanks!

**Comment by chenrui333** [comment]
this has been the case for multiple times. https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+logtalk+label%3A%22no+push+access%22

**Comment by pmoura** [comment]
May I suggest you ask GitHub to add a more sensible and convenient way to allow maintainers to edit a pull request **when creating it**? A simple button would do. Having to edit a pull request that was just created to enable this option is not good design.

**Comment by pmoura** [comment]
Moreover, it seems that if the pull request submitter is not fast enough in editing the pull request, an automatic action may have already fired and created a replacement pull request?

**Pull request closed without merging**
