### PR TITLE
binwalk: migrate to boneyard

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by sbromberger** [comment]
Just wondering - is there a reason binwalk was migrated to the boneyard?

**Comment by tdsmith** [comment]
Its dependency pyside was boneyarded because it doesn't support qt4, which is EOL'd and does not build on sierra. cf: https://github.com/Homebrew/homebrew-core/pull/5725

**Comment by tdsmith** [comment]
cf https://github.com/Homebrew/homebrew-core/issues/1705 for qt4 deprecation

**Comment by sbromberger** [comment]
Thanks for the quick response! I'm unfamiliar with the process here - will it eventually be reinstated or is that it for binwalk?

**Comment by tdsmith** [comment]
That's it, unless binwalk is rewritten to use qt5.

**Comment by sbromberger** [comment]
I've never used binwalk as a gui though - it's a good command line tool.

**Comment by tdsmith** [comment]
I think we'd probably consider a PR to reinstate it as a command-line tool.

**Comment by sbromberger** [comment]
It's a command-line tool by default. The only time it uses QT is when you ask it to graph something (for example, using `-E`), in which case you get

```
Entropy Exception: PyQtGraph requires either PyQt4 or PySide; neither package could be imported.
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/binwalk/2.1.1_1/libexec/lib/python2.7/site-packages/binwalk/core/module.py", line 566, in main
    retval = self.run()
  File "/usr/local/Cellar/binwalk/2.1.1_1/libexec/lib/python2.7/site-packages/binwalk/modules/entropy.py", line 122, in run
    self._run()
  File "/usr/local/Cellar/binwalk/2.1.1_1/libexec/lib/python2.7/site-packages/binwalk/modules/entropy.py", line 128, in _run
    import pyqtgraph as pg
  File "/usr/local/Cellar/binwalk/2.1.1_1/libexec/vendor/lib/python2.7/site-packages/pyqtgraph/__init__.py", line 13, in <module>
    from .Qt import QtGui
  File "/usr/local/Cellar/binwalk/2.1.1_1/libexec/vendor/lib/python2.7/site-packages/pyqtgraph/Qt.py", line 32, in <module>
    raise Exception("PyQtGraph requires either PyQt4 or PySide; neither package could be imported.")
Exception: PyQtGraph requires either PyQt4 or PySide; neither package could be imported.
----------------------------------------------------------------------------------------------------
```

**Comment by MikeMcQuaid** [comment]
I'm 👍 to reinstate it if the Qt dependency is removed. @sbromberger Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by sbromberger** [comment]
I'm happy to give it a shot. Does removing the dependency just mean not including it in the homebrew build and accepting the error message above, or will it require removing the `-E` option in the code itself and maintaining a QT-free fork? If the latter, I'm probably not prepared to be the maintainer.

**Comment by MikeMcQuaid** [comment]
Just not including it and accepting that error message sounds fine 👍

**Comment by sbromberger** [comment]
@MikeMcQuaid gonna take you up on your offer to help. Almost there, but audit gives me

```
  * binwalk seems to be listed in tap_migrations.json!
    Please remove binwalk from present tap & tap_migrations.json
    before submitting it to Homebrew/homebrew-core.
```

What do I need to do?

**Comment by MikeMcQuaid** [comment]
@sbromberger Remove it from `tap_migrations.json` in your homebrew/core PR and create a PR in this repo to remove the formula too. Thanks!

**Comment by sbromberger** [comment]
Thanks. cf #5797 and https://github.com/Homebrew/homebrew-boneyard/pull/202

**Comment by MikeMcQuaid** [comment]
Re-added by @sbromberger in https://github.com/Homebrew/homebrew-core/pull/5797. Nice work.

**Pull request merged**
