### PR TITLE
fortio 1.0.1

### PR DESCRIPTION
**Pull request by ldemailly**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Follow up from previous PR/issues (the GOOS bit and the -dirty bit is worked around in https://github.com/istio/fortio/pull/262 and I just released fortio 1.0.1 which includes it)

cc @ilovezfs @ymesika

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks again @ldemailly!

**Comment by ldemailly** [comment]
Thanks a lot @ilovezfs - is there a delay in binary bottles production:
```
$ brew install fortio
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
fortio
==> Downloading https://homebrew.bintray.com/bottles/fortio-1.0.1.high_sierra.bottle.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "fortio"
Download failed: https://homebrew.bintray.com/bottles/fortio-1.0.1.high_sierra.bottle.1.tar.gz
```

**Comment by ilovezfs** [comment]
are you still on your branch maybe?

**Comment by ldemailly** [comment]
you are right! I switched back to origin master and it worked fine - my bad (maybe this could be a warning "==> warning: you recipe git repo is on development branch..." somehow expected brew update to switch/point to the "real" thing)
```
ldemailly-macbookpro:~ ldemailly$ brew install fortio
==> Downloading https://homebrew.bintray.com/bottles/fortio-1.0.1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring fortio-1.0.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/fortio/1.0.1: 12 files, 13MB
ldemailly-macbookpro:~ ldemailly$ /usr/local/bin/fortio version
1.0.1 2018-06-29 10:35 1e338e499d8ae134dcc32ad63825e7b972158687 go1.10.3
ldemailly-macbookpro:~ ldemailly$ /usr/local/bin/fortio version -s
1.0.1
```
and the version string is cleaned/fixed now 🎉 thanks a lot @ilovezfs !

**Comment by ilovezfs** [comment]
I believe `brew doctor` will warn you if you're on a branch other than master.

**Comment by ilovezfs** [comment]
>and the version string is cleaned/fixed now 🎉 thanks a lot @ilovezfs !

You're welcome!

**Comment by ldemailly** [comment]
> I believe `brew doctor` will warn you if you're on a branch other than master.

oh indeed, cool!
```
Warning: Homebrew/homebrew-core is not on the master branch

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master

```

**Pull request closed without merging**
