### PR TITLE
notmuch 0.25

### PR DESCRIPTION
**Pull request by opie4624**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by opie4624** [comment]
It looks like the git url is valid, but limited access. Perhaps removing the `head` directive is the right move? The repo can be browsed here: https://git.notmuchmail.org/git/notmuch

**Comment by pxlpnk** [comment]
It seems there where connectivity problems with the git server until a few hours ago. From what I see here: https://github.com/Homebrew/brew/blob/8f068a356dfe4769905d2487533b9e8124287098/Library/Homebrew/utils/git.rb#L72-L75
a simple `git ls-remote git://notmuchmail.org/git/notmuch` is performed which should work now. I guess a rebuild should be green :crossed_fingers:

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @opie4624 for the pull request!

**Pull request closed without merging**
