### PR TITLE
imagemagick 7.0.9-1

### PR DESCRIPTION
**Pull request by ROpdebee**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
~Note: Tarball needs to be mirrored to bintray.~

### CODE REVIEW

**Comment by fxcoudert** [comment]
The following formulas need to have their revision bumped: `blockhash chafa dmtx-utils mgba pqiv vapoursynth-imwri vips zbar`

One commit per formula revision, with revision message `blockhash: revision for imagemagick`

**Comment by apjanke** [comment]
ImageMagick 7.0.9.0 is 404 already; they've replaced it with a 7.0.9.1.

```
$ brew install -s ImageMagick                                                                                                   ImageMagick-7.0.9-0
==> Downloading https://dl.bintray.com/homebrew/mirror/ImageMagick-7.0.9-0.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
```

While we're on this, maybe we should be using the https://imagemagick.org/download/releases/ URLs for ImageMagick instead of plain https://imagemagick.org/download? It looks like only the very latest releases are kept in https://imagemagick.org/download, so as soon as a new release is out, the old release will become 404 and the formula will break, whereas https://imagemagick.org/download/releases/ keeps several older releases.

**Comment by ROpdebee** [comment]
The recycling of releases is the main reason why the source tarballs are mirrored to bintray, but it seems the previous release was not mirrored, and the tarball for this release wasn't either. Good catch on the alternative directory, I'll update the PR with the new directory and version soon.

@fxcoudert  should we keep the mirror URL now that we have the https://imagemagick.org/download/releases/ source?

**Comment by ROpdebee** [comment]
One of the failures in CI is a 503 error on a download, so nothing serious.

The other failure is `blockhash`, which is trying to build with openmp support with the vanilla Apple clang compiler. It does so because it gets the `-fopenmp` flag from `pkg-config` for ImageMagick. The build system is `waf` though, which I'm completely unfamiliar with, so I'm not sure how to proceed.

**Comment by fxcoudert** [comment]
Can we instead ask `waf` to compile `blockhash` with no OpenMP at all? Thanks

**Comment by ROpdebee** [comment]
Using a similar approach? Sure thing, updated and rebased.

By politely asking `waf` during install? Not sure, there are barely any options we can give to the configure command. An alternative fix would be to patch the build script to remove the `-fopenmp` flag, but that's a bit more involved.

**Comment by ROpdebee** [comment]
Apparently even https://imagemagick.org/download/releases/ removes old revisions (7.0.9-0 isn't there anymore). To prevent this from causing issues in the future (e.g., #45999), I'll switch this formula over to use git tags.

Also diagnosing Octave test failure locally.

**Comment by fxcoudert** [comment]
I'm reverting the URL scheme for imagemagick, and adding back the mirror. This worked for us so far…

**Comment by fxcoudert** [comment]
Issue filed upstream as well: https://github.com/ImageMagick/ImageMagick/issues/1771

**Comment by ROpdebee** [comment]
What's the issue with using git tags from https://github.com/ImageMagick/ImageMagick (or even their releases there)? They seem persistent (although the latest version isn't there yet).

Also still unsure why the Octave test fails on High Sierra, may just be a gimmick.

**Comment by fxcoudert** [comment]
git tags mean we can't cache downloads (so we generally prefer source archives), and for IM they aren't as up to date as source tarballs.

**Comment by ROpdebee** [comment]
Okay that's a fair argument. Thanks for the explanation!

**Comment by ROpdebee** [comment]
FWIW: I cannot reproduce the test failure for Octave on High Sierra 10.12.6, either locally or on a private Travis instance. Seems to be a CI hickup.

**Comment by apjanke** [comment]
Sorry if I'm not following this right; can you link me to the Octave build failures? Octave build looks good for me locally with this change...

**Comment by ROpdebee** [comment]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50727/version=highsierra/testReport/junit/brew-test-bot/high_sierra/test_octave/
Build is fine but the test times out.

**Pull request closed without merging**
