### PR TITLE
zlib: don't build with glibc@2.13

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
The test failures here are all unrelated, so this is ready to merge.

**Comment by SMillerDev** [comment]
It also timed out though, that seems problematic

**Comment by carlocab** [comment]
This change primarily affects Linux, so I'd like to avoid skipping dependents on Linux here. I don't want to get burned from skipping dependents again, as what happened [here](https://github.com/Homebrew/homebrew-core/pull/108662#issuecomment-1225072379).

**Comment by danielnachun** [comment]
`zlib` has 3098 recursive dependencies so I think we should skip recursive dependencies in this case and just do direct.  467 is a still a lot but more manageable than half of all formulae on Linux.

**Comment by danielnachun** [comment]
There were only a handful of failures and warnings, none of which are relevant to this PR:
- `hdf5@5.10` - linkage failure that is likely because it is keg-only
- `john-jumbo`, `ruby@2.7`, `ruby@3.0` - need to depend on `libxcrypt`
- `qt` - will be fixed by https://github.com/Homebrew/homebrew-core/pull/107400
- `root` - might need a revision bump after the GCC update, but it's not totally clear
- `python@3.7`, `python@3.8`, `python@3.9`, `python@3.10`, `texlive` - need to depend on `libnsl`

I will open PRs for the obvious issues but none of them are needed for us to merge this.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
