### PR TITLE
pyinstaller 4.9

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
`* The homepage URL https://www.pyinstaller.org/ is not reachable`

**Comment by carlocab** [comment]
This is a known issue: https://github.com/pyinstaller/pyinstaller/issues/6490

**Comment by bayandin** [comment]
> Not sure if it's worth changing it with one that works but is otherwise less suitable than the current homepage when accessible.

I'd change it to `https://pyinstaller.readthedocs.io/` with a comment to put `https://www.pyinstaller.org/` back when it is back (and a link to https://github.com/pyinstaller/pyinstaller/issues/6490 probably).

**Review by carlocab — APPROVED** [review]
Intel nodes are down, so let's fix the homepage separately.

**Pull request closed without merging**
