### PR TITLE
workflows: build on GitHub macOS runners (where available) by default

### PR DESCRIPTION
**Pull request by carlocab**
- **workflows: build on macOS runners by default**
  Let's use GitHub macOS runners where available unless requested
  otherwise with a `CI-no-github-macos-runners` or a `long build` label.
  

- **workflows: rename `setup_runners` to `determine_runners`**
  And similarly for `setup_dep_runners`. This will make it easier to
  distinguish from the `setup_tests` and `setup_dep_tests` jobs.

### CODE REVIEW

**Comment by Bo98** [comment]
One big question: are these actually sufficiently clean? We cleanup some Homebrew prefix stuff but we do not clean the whole system. Arbitrary libraries could exist in /usr/local/lib etc. I could see build scripts picking up dynamic linkage to Python.framework, which brew linkage might not pick up as if we test on GitHub-hosted too. Arbitrary static libraries can also be a concern.

Something to be aware of too (though you're probably aware of this): the disk space on these will be as much as 80-90% less than ours and will be without the space-saving hacks we have on Linux.

**Comment by MikeMcQuaid** [comment]
> Arbitrary libraries could exist in /usr/local/lib etc. I could see build scripts picking up dynamic linkage to Python.framework, which brew linkage might not pick up if we test on GitHub-hosted too. Arbitrary static libraries can also be a concern. I feel like we need to be significantly more aggressive in cleanup here.

Agreed, sadly.

I think it might be nice/best to use these runners just to do e.g. dependent testing and never build on them?

**Review by MikeMcQuaid — COMMENTED** [review]
Pending further discussion.

**Comment by carlocab** [comment]
Closing given discussion above.

**Pull request closed without merging**
