### PR TITLE
ios-deploy 1.11.0

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
See https://github.com/Homebrew/homebrew-core/pull/57389#issuecomment-656284046

```
==> xcodebuild -configuration Release SYMROOT=build
2020-07-09 19:19:01.463 xcodebuild[59157:5233333]  DVTErrorPresenter: Unable to load simulator devices.
Domain: DVTCoreSimulatorAdditionsErrorDomain
Code: 3
Failure Reason: The version of the CoreSimulator framework installed on this Mac is out-of-date and not supported by this version of Xcode.
Recovery Suggestion: Please ensure that you have installed all available updates to your Mac's software, and that you are running the most recent version of Xcode supported by macOS.
--
CoreSimulator is out of date. Current version (681.17.2) is older than build version (704.12.2).
Domain: DVTCoreSimulatorAdditionsErrorDomain
Code: 3
--
2020-07-09 19:19:01.463 xcodebuild[59157:5233333]  iOSSimulator: [SimServiceContext sharedServiceContextForDeveloperDir:error:] returned nil (Error Domain=DVTCoreSimulatorAdditionsErrorDomain Code=3 "CoreSimulator is out of date. Current version (681.17.2) is older than build version (704.12.2)." UserInfo={NSLocalizedDescription=CoreSimulator is out of date. Current version (681.17.2) is older than build version (704.12.2).}). Simulator device support disabled.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -configuration Release SYMROOT=build

Build settings from command line:
    SYMROOT = build

2020-07-09 19:19:02.345 xcodebuild[59157:5233265] [MT] IDELogStore: Failed to open log store at /Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Build
2020-07-09 19:19:02.345 xcodebuild[59157:5233265] [MT] IDELogStore: Failed to open Build log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Build': (513) You don’t have permission to save the file “Build” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Build': (513) You don’t have permission to save the file “Build” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Build': (513) You don\U2019t have permission to save the file \U201cBuild\U201d in the folder \U201cLogs\U201d.";
}.
2020-07-09 19:19:02.391 xcodebuild[59157:5233265] [MT] IDELogStore: Failed to open log store at /Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Package
2020-07-09 19:19:02.392 xcodebuild[59157:5233265] [MT] IDELogStore: Failed to open Package log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Package': (513) You don’t have permission to save the file “Package” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Package': (513) You don’t have permission to save the file “Package” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Package': (513) You don\U2019t have permission to save the file \U201cPackage\U201d in the folder \U201cLogs\U201d.";
}.
2020-07-09 19:19:02.416 xcodebuild[59157:5233265] Couldn't create intermediates directory: You don’t have permission to save the file “Intermediates.noindex” in the folder “Build”.
2020-07-09 19:19:03.536 xcodebuild[59157:5233265] [MT] IDELogStore: Failed to open log store at /Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Test
2020-07-09 19:19:03.536 xcodebuild[59157:5233265] [MT] IDELogStore: Failed to open Test log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Test': (513) You don’t have permission to save the file “Test” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Test': (513) You don’t have permission to save the file “Test” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Logs/Test': (513) You don\U2019t have permission to save the file \U201cTest\U201d in the folder \U201cLogs\U201d.";
}.
2020-07-09 19:19:03.554 xcodebuild[59157:5233265] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-16139/IDEFoundation/Buildables/IDEWorkspaceArena.m:1131
Details:  Failed to create workspace arena at <DVTFilePath:0x7ff608c9bc30:'/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo'>: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “ios-deploy-drlrtpgxlohblscnbfdnohxalgpo” in the folder “DerivedData”." UserInfo={NSFilePath=/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo, NSUnderlyingError=0x7ff608ca5750 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
Object:   <IDEWorkspaceArena: 0x7ff608c0e5f0>
Method:   -createWorkspaceArenaFolderIfNecessary
Thread:   <NSThread: 0x7ff608c19060>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
note: Using new build system
error: Build service could not start build operation: unknown error while handling message: fopen(/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Build/Intermediates.noindex/XCBuildData/PIFCache/WORKSPACE@v11_hash=(null)_subobjects=fb64f23ceab12b8230ecfc80e713b4f3-Workspace.lock, wb): No such file or directory (2)

** BUILD FAILED **

Couldn't set atribute on intermediates directory: setxattr(/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Build/Intermediates.noindex, com.apple.xcode.CreatedByBuildSystem, true): No such file or directory (2)
Couldn't set atribute on intermediates directory: setxattr(/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Build/Intermediates.noindex, com.apple.xcode.CreatedByBuildSystem, true): No such file or directory (2)
Couldn't set atribute on intermediates directory: setxattr(/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Build/Intermediates.noindex, com.apple.xcode.CreatedByBuildSystem, true): No such file or directory (2)
Couldn't set atribute on intermediates directory: setxattr(/Users/brew/Library/Developer/Xcode/DerivedData/ios-deploy-drlrtpgxlohblscnbfdnohxalgpo/Build/Intermediates.noindex, com.apple.xcode.CreatedByBuildSystem, true): No such file or directory (2)
```

**Comment by SeekingMeaning** [comment]
Build succeeded, #57460 is also fixed and can be merged as well

**Comment by Rylan12** [comment]
Is this a pre-release? It's marked as beta 1 in [GitHub](https://github.com/ios-control/ios-deploy/releases/tag/1.11.0-beta.1)

**Comment by SeekingMeaning** [comment]
Hmm I looked into it and I'm not sure myself. Let me open an issue on their end

**Comment by SeekingMeaning** [comment]
- 1.11.0 https://github.com/ios-control/ios-deploy/commit/fcbba00cd6561deed70d235caa58ee00c1f9bbff
- 1.11.0-beta.1 https://github.com/ios-control/ios-deploy/commit/e8e321c4212659de550c7184f544518f608103c6

fcbba00 is the parent revision of e8e321c (in other words, 1.11.0 is an older release than 1.11.0-beta.1 so I guess it's a pre-release)

**Comment by gabebear** [comment]
In hindsight I should not have bumped the version in the main repo... I didn't realize this would auto-pull a version into Homebrew. Releases on ios-deploy are primarily done via Github releases https://github.com/ios-control/ios-deploy/releases

**Comment by chenrui333** [comment]
> In hindsight I should not have bumped the version in the main repo... I didn't realize this would auto-pull a version into Homebrew. Releases on ios-deploy are primarily done via Github releases https://github.com/ios-control/ios-deploy/releases

it is not auto-pulling the version, we just run `livecheck` to see if we need to keep the software up to date. It mostly follows the stable release (which is latest release tag).

**Comment by gabebear** [comment]
Can this PR be re-opened and merged? 1.11.0 turned out to not need any fixes and is already live on npm and is already pulled into Flutter. (This version is important because Xcode12 will not work without it)

This would be the correct PR to release the current version of ios-deploy https://github.com/ios-control/ios-deploy/releases/tag/1.11.0. When I try to run my normal `brew bump-formula-pr` I get a warning about this PR
```
Warning: These pull requests may be duplicates:
ios-deploy 1.11.0 https://github.com/Homebrew/homebrew-core/pull/57738
```
I tried `--force` but that leads me to a bunch of other errors.

**Comment by Rylan12** [comment]
I just opened a new one at #58553.

Not sure why `bump-formula-pr` didn't work for you.

Thanks for bringing this back up!

**Comment by gabebear** [comment]
thanks!

**Pull request closed without merging**
