### PR TITLE
varnish 6.1.0

### PR DESCRIPTION
**Pull request by SpikesDivZero**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
checking for sphinx-build... no
configure: error: sphinx-build is needed to build Varnish, please install python-sphinx.
```

**Comment by SpikesDivZero** [comment]
Thanks @fxcoudert! I'd noticed the failure and was already working on a PR. This is my first brew PR, so while I've got the upgraded varnish formula to build locally with the updated commit, I don't know of a decent way to test it from a "clean" install as Jenkins is likely doing.

**Comment by SpikesDivZero** [comment]
Hmm, it looks like the build failed on Jenkins again, but I'm not sure what's happening in the CI side. There seems to be an issue with it attempting to checkout a bad revision?

**Comment by fxcoudert** [comment]
Thanks @SpikesDivZero

**Pull request closed without merging**
