### PR TITLE
php 8.2.0 php@8.1 (new formula)

### PR DESCRIPTION
**Pull request by vintagesucks**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /opt/homebrew/Cellar/deployer/7.0.2/bin/dep init --no-interaction
   ErrorException  in DumpCompletionCommand.php on line 48:
  
    Using ${var} in strings is deprecated, use {$var} instead
```

```
  ==> /opt/homebrew/Cellar/php-cs-fixer/3.13.0/bin/php-cs-fixer fix test.php
  PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.1.*.
  Current PHP version: 8.2.0.
  To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
  If you use PHP version higher than supported, you may experience code modified in a wrong way.
  Please report such cases at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer .
```

php-cs-fixer does not work php 8.2

**Comment by chenrui333** [comment]
php-cs-fixer issue label, https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/labels/topic%2FPHP8.2

**Comment by SMillerDev** [comment]
They can all be easily downgraded to PHP 8.0

**Comment by chenrui333** [comment]
> They can all be easily downgraded to PHP 8.0

yeah, I just created a php@8.1 (looks like it is LTS release), we can use 8.1 for those two formulae

**Comment by chenrui333** [comment]
long time build needed for 13

**Comment by derrabus** [comment]
We have this problem with PHP CS Fixer every year. 😓 

Last year, I solved this with a wrapper script: #89978

**Comment by d8vjork** [comment]
Probably not understanding the issue very well, but why not just leave PHP CS Fixer to use php@8.1 formula until PHP 8.2 support is added to this?

**Comment by chenrui333** [comment]
> Probably not understanding the issue very well, but why not just leave PHP CS Fixer to use php@8.1 formula until PHP 8.2 support is added to this?

yeah, that is what I did in here, right now, just need a new run.

**Comment by chenrui333** [comment]
> We have this problem with PHP CS Fixer every year. 😓
> 
> Last year, I solved this with a wrapper script: #89978

😅

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @vintagesucks!

**Comment by vintagesucks** [comment]
@chenrui333 Thank you for taking care of the necessary changes!

**Pull request closed without merging**
