### PR TITLE
appscale-tools 3.8.1

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Current issue

```
$ /usr/local/Cellar/appscale-tools/3.8.1/bin/appscale
Traceback (most recent call last):
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/bin/appscale", line 11, in <module>
    load_entry_point('appscale-tools==3.8.1', 'console_scripts', 'appscale')()
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/lib/python2.7/site-packages/appscale/tools/scripts/appscale.py", line 9, in <module>
    from appscale.tools.appscale import AppScale
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/lib/python2.7/site-packages/appscale/tools/appscale.py", line 16, in <module>
    from appscale.tools.appscale_tools import AppScaleTools
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/lib/python2.7/site-packages/appscale/tools/appscale_tools.py", line 33, in <module>
    from appscale.tools.node_layout import NodeLayout
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/lib/python2.7/site-packages/appscale/tools/node_layout.py", line 11, in <module>
    from appscale.agents.factory import InfrastructureAgentFactory
ImportError: No module named agents.factory
```

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Rebase needed

**Comment by chenrui333** [comment]
only test failed on 10.14

```
==> /usr/local/Cellar/appscale-tools/3.8.1/bin/appscale help
Traceback (most recent call last):
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/bin/appscale", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'keyrings.alt<3.2,>=3.1' distribution was not found and is required by appscale-agents
```

**Comment by chenrui333** [comment]
but the dependency is there :(

```
  resource "keyrings.alt" do
    url "https://files.pythonhosted.org/packages/62/a4/cfa759dc4a5113d653a1dfdbd61011e88fe7abb7a476c8ca10f37e2a789c/keyrings.alt-3.1.1.tar.gz"
    sha256 "0bc7b75c7e710a3dd7bc4c3841c71467b24ccbce1b85efb2586bdf0c4713f751"
  end

```

**Comment by chenrui333** [comment]
I can reproduce the issue on my mojave machine.

**Comment by chenrui333** [comment]
I am inclined to have it supported on >= 10.15 (that save us some hassle of maintaining it)
image

**Pull request closed without merging**
