### PR TITLE
s6 2.12.0.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
some audit check failures for macos builds, good to be merged.

**Comment by SMillerDev** [comment]
On macOS none of the urls are accessible yet somehow it builds. That's an odd one.

**Comment by chenrui333** [comment]
yeah, indeed.

**Comment by chenrui333** [comment]
since homebrew_curl, does not help, gonna revert it now.

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
