### PR TITLE
boost and open-mpi: always build with C++11

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 what do you suppose the chances are this runs Jenkins out of disk space? lol

**Comment by DomT4** [comment]
@ilovezfs Can we open a betting pool both on that & how long this CI build is going to take? 😄

**Comment by ilovezfs** [comment]
@DomT4 15 hours.

**Comment by ilovezfs** [comment]
And it actually failed to complete the build on 10.12 and 10.13.

**Comment by ilovezfs** [comment]
OK looks like nothing but unrelated failures here.

**Comment by DomT4** [comment]
> 15 hours.

That's not actually as bad as I was expecting.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
:green_apple:

**Pull request closed without merging**
