### PR TITLE
bat: install bundled fish completions

### PR DESCRIPTION
**Pull request by lwolfsonkin**
Installs bundled fish completions for [`bat`](https://github.com/sharkdp/bat).

In `bat` version [v0.11.0](https://github.com/sharkdp/bat/releases/tag/v0.11.0), they added manually written fish completions (in sharkdp/bat#524 and sharkdp/bat#555) since they disabled the automatically generated completions in [v0.10.0](https://github.com/sharkdp/bat/releases/tag/v0.10.0). This update simply installs them during `brew install`. Note that this is a sort of soft reversion of #36116.

---

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
  - Unfortunately, my Homebrew errors out when I try to run `brew audit` like in #5561, so I could not. I attempted troubleshooting, but to no avail.

-----

### CODE REVIEW

**Review by zbeekman — APPROVED** [review]
LGTM

**Review by zbeekman — CHANGES_REQUESTED** [review]
I spoke too soon. If you want this change to be shipped out to users, can you please add a revision bump? i.e., `revision 1` below the sha256 checksum? You can automate the process with `brew bump-revision bat`.

Thanks!

**Comment by lwolfsonkin** [comment]
Revision bumped!

Thanks for the review, @zbeekman!

**Review by zbeekman — APPROVED** [review]
LGTM

**Comment by zbeekman** [comment]
@lwolfsonkin For future reference: Please set the commit message to start with the formula name (like the PR title) and squash commits.

Thanks!

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by lwolfsonkin** [comment]
Will squash for the future! Sorry about that.

And no problem! :)

**Pull request closed without merging**
