### PR TITLE
pyside 6.3.0

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I've refactored this to use CMake for the build process as we already do for `pyside@2`.  This is a much better system for package managers to use and lets us get rid of a lot of cruft.  The fix I had to add for building on macOS needs to be upstreamed assuming this passes CI.

**Comment by danielnachun** [comment]
The `metaobjectdump.py` and `project.py` files are not shebang scripts as I originally thought but must be invoked using `python3`.  I agree with the audit that these don't belong in `bin`.  What's the best place to move these to?  I was thinking `share`, but I'm not sure what we've done in previous formulae with Python scripts like this.

**Comment by danielnachun** [comment]
I got this to build by moving the Python scripts to `pkgshare`.  Any thoughts on whether this acceptable?  I have everything ready to upstream to Qt Gerrit for the macOS fix to the CMake build, but I want to make sure we're okay with the changes I've made before submitting it.

**Comment by SMillerDev** [comment]
Yeah, sounds good

**Comment by danielnachun** [comment]
I submitted the macOS fix to the PySide Gerrit and linked it in a comment so we can merge this once the CI run is done.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
