### PR TITLE
mysql@5.7: disable

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
It has been more than six months now.

There are still more than 6000 downloads / month but users have been warned for some time now.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
extended support ended 9 months ago

image

**Comment by mickeyreiss** [comment]
This was a breaking change for me. Given that Google Cloud Platform will continue to offer "extended support" for MySQL 5.7 through February 2028[^1], I'd recommend reverting this change for now.

[^1]: https://cloud.google.com/sql/docs/mysql/db-versions#database-version-support

**Comment by mickeyreiss** [comment]
@iMichka This is for local developer environments on MacOS who are creating applications that will use GCP's Cloud SQL MySQL 5.7 in production. In this use-case, they simply need a stable version of MySQL 5.7 - doesn't necessarily need to be the exact GCP fork.

**Comment by SMillerDev** [comment]
> In this use-case, they simply need a stable version of MySQL 5.7 - doesn't necessarily need to be the exact GCP fork.

And we need a supported version of the codebase. I agree it doesn't have to be the GCP version, but it must be _a_ version.

**Pull request merged**
