### PR TITLE
truffle 5.5.6

### PR DESCRIPTION
**Pull request by cho-m**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Trying to see if we can modify binaries for ARM.

Main issues I see are:
- `fsevents` is the x86_64 binary rather than the universal binary from newer releases
- `ganache` has `dist/node/*.node` files. It looks like it distributes a universal binary via NPM, so seems like it should work on ARM.

```
Full audit truffle --online --git --skip-style output
  truffle:
    * Files were found with references to the Homebrew shims directory.
      The offending files are:
        libexec/lib/node_modules/truffle/node_modules/ursa-optional/stderr.log
    * Binaries built for a non-native architecture were installed into truffle's prefix.
      The offending files are:
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/fsevents/fsevents.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/1Upv6xCm.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/2RS2pBU5.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/2qsIiqa9.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/3wfpWiF8.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/PiqCNgsh.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/WUY_356Y.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/node_modules/@trufflesuite/bigint-buffer/prebuilds/darwin-x64/node.napi.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/node_modules/keccak/prebuilds/darwin-x64/node.napi.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/node_modules/secp256k1/prebuilds/darwin-x64/node.napi.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/keccak/prebuilds/darwin-x64/node.napi.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/leveldown/prebuilds/darwin-x64/node-napi.node	(x86_64)
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/secp256k1/prebuilds/darwin-x64/node.napi.node	(x86_64)
      Unexpected universal binaries were found.
      The offending files are:
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/bufferutil/prebuilds/darwin-x64+arm64/node.napi.node
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/node_modules/bufferutil/prebuilds/darwin-x64+arm64/node.napi.node
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/node_modules/leveldown/prebuilds/darwin-x64+arm64/node.napi.node
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/node_modules/utf-8-validate/prebuilds/darwin-x64+arm64/node.napi.node
        /opt/homebrew/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/utf-8-validate/prebuilds/darwin-x64+arm64/node.napi.node
```

**Comment by SMillerDev** [comment]
>   unexpected (libc.musl-x86_64.so.1)

Great

**Comment by cho-m** [comment]
Node formulae are always annoying with their pre-built binaries.

I'm guessing Linux issue is due to pre-built in one of the other directories.

macOS issue is even more annoying as the names of files are meaningless and it would require reading file information to figure out ELF/Mach-O formats to delete the unwanted ones, e.g.
```
/usr/local/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/1PxYImYD.node	(arm64)
```

Once I fix Linux issue, I will probably need to add this as audit exception.

Other options are tricky to get working:
- detect ELF/Mach-O and delete unwanted (don't think we have DSL for this. some similar logic to `deuniversalize_machos`)
- rebuild problematic module (i.e. `ganache`); however, the NPM module doesn't contain source code, so will need to have workaround of building GitHub source and injecting into NPM's downloaded tree. I'm not familiar with NodeJS to do this.

**Comment by cho-m** [comment]
Linux passed.

macOS audit error is now only for those random filenames. Adding following as reference. Will add a comment inside formula and add to audit allowlist:
```
==> brew audit truffle --online --git --skip-style
==> FAILED
Full audit truffle --online --git --skip-style output
  truffle:
    * Binaries built for a non-native architecture were installed into truffle's prefix.
      The offending files are:
        /usr/local/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/1PxYImYD.node	(arm64)
        /usr/local/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/1xr7gg_Q.node	(arm64)
        /usr/local/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/2DXHq0Du.node	(arm64)
        /usr/local/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/34-3SbKj.node	(arm64)
        /usr/local/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/3LG0kv4n.node	(arm64)
        /usr/local/Cellar/truffle/5.5.6/libexec/lib/node_modules/truffle/node_modules/ganache/dist/node/GCJgCoqg.node	(arm64)
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
