### PR TITLE
Add test to drip

### PR DESCRIPTION
**Pull request by Git-Jiro**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Reference: https://github.com/Homebrew/homebrew-core/issues/11898

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/drip/0.2.4/bin/drip version
mkdir: classes/: Operation not permitted
mkdir: classes/: Operation not permitted
make: *** [classes/org/flatland/drip/Switchable.class] Error 1
make: *** Waiting for unfinished jobs....
make: *** [classes/org/flatland/drip/Main.class] Error 1
mkdir: classes/: Operation not permitted
make: *** [classes/org/flatland/drip/SwitchableInputStream.class] Error 1
Error: drip: failed
```

**Comment by Git-Jiro** [comment]
@fxcoudert Do you have any ideas how to find out what kind of directories drip wants to create and where?

**Comment by SMillerDev** [comment]
@Git-Jiro I guess it's mostly a matter of trial and error unless it's in their documentation. Are you planning on finishing this review still?

**Comment by Git-Jiro** [comment]
Sure I want to finish this! :-)

**Comment by Git-Jiro** [comment]
I have a theory: It seems like $DRIP_HOME is not pointing to a writeable directory.
My workaround `system "DRIP_HOME=/tmp", "#{bin}/drip", "version"` does not yet work as expected ...

**Comment by Git-Jiro** [comment]
I still would like to be able to fix this issue, but I have no new idea how to do that ...

**Comment by igas** [comment]
try `ENV["DRIP_HOME"] = testpath`

**Comment by Git-Jiro** [comment]
It is still not working, I need to find a path where creating the directories will not fail: 

> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/drip.rb --verbose
==> /usr/local/Cellar/drip/0.2.4/bin/drip version
mkdir: classes/: Operation not permitted
mkdir: classes/: Operation not permitted
make: *** [classes/org/flatland/drip/Switchable.class] Error 1
make: *** Waiting for unfinished jobs....
make: *** [classes/org/flatland/drip/Main.class] Error 1
mkdir: classes/: Operation not permitted
make: *** [classes/org/flatland/drip/SwitchableInputStream.class] Error 1
mkdir: classes/: Operation not permitted
make: *** [classes/org/flatland/drip/SwitchableOutputStream.class] Error 1
Error: drip: failed

**Comment by fxcoudert** [comment]
Given nobody has any idea how to make drip create its directories in the right place, closing for now.

**Comment by Git-Jiro** [comment]
At least we tried ... 
I guess it's okay if I delete my branch now?

**Comment by igas** [comment]
@Git-Jiro this is up to you. If you want to keep your fork clean, feel free to delete it.

**Pull request closed without merging**
