### PR TITLE
abcmidi: use secure url in test

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by DomT4** [comment]
I'm impressed you spotted a lot of these 😄. Merged in https://github.com/Homebrew/homebrew-core/commit/b396048d6dfc0987a2adea82fbe5749a36e04a53. Thanks again @vszakats!

**Comment by vszakats** [comment]
I have a script for help :)

Expect 4 more batches tomorrow with similar fixes.

**Comment by DomT4** [comment]
If you limit yourself to ~10 formulae per PR you're considerably more likely to not run into CI timeouts, FWIW.

**Comment by vszakats** [comment]
Noted, and I apologise for running over that, even though we had discussed this in the past.

Expect about 6 smaller batches. (hard to tell exactly which automated hits survive manual verification)

**Comment by mikemcquaid** [comment]
> I have a script for help :)

@vszakats Reminder that the best thing would be to try and get said script integrated in Homebrew so we can check these automatically ourselves.

**Comment by vszakats** [comment]
@mikemcquaid For the download URL it's trivial, such script could make attempts to upgrade the protocol (from `ftp` to `http`, from `http` to `https`) and verify if the result is the same. For non-download URLs, such as URLs in comments, homepage, etc, the same can be done, which helps some of the time, and in some other cases &mdash; where the content is different &mdash; flags the upgrade for human verification. I've published such script here in the past: https://gist.github.com/vszakats/663dc8ccf1d49b903f8e

In this particular case I used this older one: https://github.com/vszakats/harbour-core/blob/master/tests/checkssl.hb

**Comment by mikemcquaid** [comment]
@vszakats Now that we support Bash commands it should be relatively easy to stick that in the `dev-cmd` directory and add it to `brew test-bot`. Happy to help walk you through that!

**Comment by vszakats** [comment]
@mikemcquaid And there is also the logic in this script: https://gist.github.com/vszakats/ddd9be9631bfe2ee33af

Let me try consolidating these scattered attempts into a single logic and get back to the integration then. Thanks in advance for helping with the latter, I'll surely be needing it.

**Comment by vszakats** [comment]
@DomT4 Split larger PRs into two parts to stay under 10 commits.

**Comment by vszakats** [comment]
Picking up on the this old topic, I just rewrote my checker script in bash. It may be rusty/suboptimal/etc, plus it lacks any sort of `brew audit` integration whatsoever. It also gives about 5-10 false positives when run through the current set of core formulae, so these may need to be blacklisted or fixed. Please take this as a start.

```bash
#!/bin/bash

# Copyright 2014-2016 Viktor Szakats (https://github.com/vszakats)

# Fetch all http URLs from formulae and check
# whether the same URL is available via https.
#
# NOTE: curl may accept a different set of certificates
#       than web browsers.

check_secure_urls() {
  local _line
  local url
  local len
  local domain

  rm -f ./_cookie

  if grep -R -H -I -n -o "http://[a-zA-Z0-9_/\.\~\%\?&\+=@:-]*" ./*.rb > ./_urls
  then

    while IFS= read -r _line
    do
      IFS=: url=($_line)
      len=${#url[@]}
      if [ "$len" -gt 3 ]
      then
        domain="${url[3]}"
        if [ "${domain#*apple.com/DTDs/*}" = "${domain}" ] && \
           [ "${domain#*googlecode.com/svn/*}" = "${domain}" ] && \
           [ "${domain#*svn.code.sf.net/*}" = "${domain}" ] && \
           [ "${domain#*/trunk*}" = "${domain}" ] && \
           [ "${domain#*/svn.*}" = "${domain}" ] && \
           [ "$(echo "${domain}" | tail -c 5)" != ".xsd" ] && \
           [ "${domain}" != '' ] && \
           [ "${domain}" != '//' ] ; then

          # Make sure the URL is not found in the patch section, if there is one
          if grep -B100000 '^__END__$' "${url[0]}" > ./_temp1
          then
            if ! grep "${domain}" ./_temp1 > /dev/null 2>&1
            then
               domain=''
            fi
          fi

          if [ "${domain}" != '' ]
          then
            # Make sure it's not an XML namespace
            grep "${domain}" "${url[0]}" > ./_temp2
            if ! grep 'xmlns' ./_temp2 > /dev/null 2>&1
            then
              if [ "${url[2]}" = 'http' ]
              then
                if curl -fsS -v -L --max-redirs 10 --cookie-jar ./_cookie --connect-timeout 2 "https:${domain}" -o ./_outs > /dev/null 2>&1
                then
                  if curl -fsS -v -L --max-redirs 10 --cookie-jar ./_cookie --connect-timeout 2 "http:${domain}" -o ./_outo > /dev/null 2>&1
                  then
                    if diff -s --binary --speed-large-files ./_outs ./_outo > /dev/null 2>&1
                    then
                      echo "${url[0]} -> https:${domain} [OK]"
                    else
                      echo "${url[0]} -> https:${domain} [Different content - verify manually]"
                    fi
                  fi
                fi
              fi
            fi
          fi
        fi
      fi
    done < ./_urls
  fi

  rm -f ./_cookie ./_urls ./_temp1 ./temp2 ./_outs ./outo
}

check_secure_urls
```

**Comment by MikeMcQuaid** [comment]
@vszakats Could you consider putting that into a public GitHub repository so we could submit patches to it? Thanks!

**Comment by vszakats** [comment]
@MikeMcQuaid Good idea, there we go: https://github.com/vszakats/https-check

**Pull request merged**
