### PR TITLE
mariadb 11.2.3

### PR DESCRIPTION
**Pull request by SMillerDev**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by bevanjkay** [comment]
```
  -- Performing Test HAVE_SYSTEM_LIBFMT
  -- Performing Test HAVE_SYSTEM_LIBFMT - Failed
  CMake Error at cmake/libfmt.cmake:44 (MESSAGE):
    system libfmt library is not found or unusable
  Call Stack (most recent call first):
    CMakeLists.txt:405 (CHECK_LIBFMT)
```

**Comment by bevanjkay** [comment]
```
  /tmp/mariadb-20240209-4871-k0c51/mariadb-11.2.3/storage/innobase/fil/fil0fil.cc:1415:15: error: use of undeclared identifier 'OS_DATA_FILE_NO_O_DIRECT'
          type= OS_DATA_FILE_NO_O_DIRECT;
                ^
  1 error generated.
  make[2]: *** [storage/innobase/CMakeFiles/innobase.dir/fil/fil0fil.cc.o] Error 1
  make[1]: *** [storage/innobase/CMakeFiles/innobase.dir/all] Error 2
```

**Comment by SMillerDev** [comment]
Still the same issue

**Comment by bevanjkay** [comment]
@chenrui333 has a fix upstream

**Review by bevanjkay — APPROVED** [review]

**Comment by chenrui333** [comment]
- https://github.com/MariaDB/server/pull/3064

**Pull request merged**
