### PR TITLE
circleci 0.1.25519

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Comment by p-linnane** [comment]
Looks like the failed job pushed some bottles:
`Error: docker://ghcr.io/homebrew/core/circleci:0.1.25519 already exists!`

**Comment by carlocab** [comment]
Ah, that's from an earlier botched publish job. Let me fix it.

**Review by carlocab — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
@carlocab So the fix was to tick ``Pass `--warn-on-upload-failure` to `brew pr-pull`? (default: false)``, right?

**Comment by ZhongRuoyu** [comment]
Well noted. Thanks @carlocab!

**Pull request merged**
