### PR TITLE
llvm: enable flang

### PR DESCRIPTION
**Pull request by junghans**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by junghans** [comment]
@fxcoudert can we try that out to see where flang still fails?

**Comment by carlocab** [comment]
It should work for compiling simple Fortran programs. But if we want to enable this, we should add a test, which will need a test dependency on GCC.

I suspect it would be nicer to ship this as a separate formula.

**Comment by junghans** [comment]
Also see https://github.com/orgs/Homebrew/discussions/2753

**Comment by junghans** [comment]
> It should work for compiling simple Fortran programs. But if we want to enable this, we should add a test, which will need a test dependency on GCC.
> 
> I suspect it would be nicer to ship this as a separate formula.

Sounds like a good idea.

**Comment by fxcoudert** [comment]
It would need to be a stable release, to be included in homebrew-core. Otherwise, the best solution is probably to maintain it in a separate tap.

**Comment by carlocab** [comment]
Upstream include it in their binary package, and every other mainstream distro/package manager has a flang package, so it probably makes sense to include it in homebrew/core now.

**Comment by junghans** [comment]
> Upstream include it in their binary package, and every other mainstream distro/package manager has a flang package, so it probably makes sense to include it in homebrew/core now.

👍 Yeah, fedora and ubuntu have packages as well.

**Pull request closed without merging**
