### PR TITLE
remove `docker` dependencies

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
https://github.com/Homebrew/brew/issues/4769, https://github.com/Homebrew/homebrew-core/issues/31579

### CODE REVIEW

**Comment by mfriedenhagen** [comment]
BTW, to my understanding docker-machine and docker-compose do not depend on the docker CLI command either as both access the dockerd socket directly.

**Comment by commitay** [comment]
Not really sure if caveats are needed for these, the upstreams all have some variant of "this requires docker". We also have other "requires docker" formulae that don't have a docker dep or a caveat.

Not sure how many of these we would want to mention if we do go with adding caveats.
```
brew install docker docker-machine
brew cask install docker
brew cask install docker-toolbox
brew cask install homebrew/cask-versions/docker-edge
```

**Comment by mfriedenhagen** [comment]
A lot of tools interact with a running docker daemon. The docker formula, however, does only install a CLI client. (The daemon would be useless on a Mac anyways and probably is not compilablr even)

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks for this @commitay.

> Not sure how many of these we would want to mention if we do go with adding caveats.

I think we can maybe even go without adding caveats; it seems enough people are using docker outside of our formula that I think they'll figure it out (particularly given it's a pretty developer-centric tool).

**Comment by commitay** [comment]
No problem 😄 

- [`docker-machine-driver-hyperkit`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-hyperkit.rb)
- [`docker-machine-driver-vultr`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-vultr.rb)
- [`docker-machine-driver-xhyve`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-xhyve.rb)
- [`docker-machine-parallels`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-parallels.rb)

These four also have `docker` deps but I'm not really familiar with them. A couple look like they might be able to be switched to `:test` deps, I'll take a look and do a follow up PR if needed.

**Review by DomT4 — APPROVED** [review]
As long as it doesn't degrade our ability to test formulae properly, which I assume/hope it doesn't given CI passed heh, I'm cool with this 👍.

**Comment by mfriedenhagen** [comment]
docker-machine creates a virtualized Linux host with a running docker daemon, normally by starting a tiny Linux based boot2docker iso. It supports some hypervisors out of the box like virtualbox or VMware, other might be add via drivers, these are adapters which implement the API calls for creating VMs .

So my guess would be they do not need the docker client executable either. Of course if you want to interact with the dockerd in the created VM the executable could be handy, but e.g. there is a docker Maven plugin or docker-compose which use the API directly so in the strict sense the executable is not required.

**Pull request closed without merging**
