### PR TITLE
entropy 1.0.1 (new formula)

### PR DESCRIPTION
**Pull request by EwenQuim**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Adds [entropy](https://github.com/EwenQuim/entropy), a tool that scans your files for high entropy lines, which are often secrets

### CODE REVIEW

**Comment by chenrui333** [comment]
Hey @EwenQuim and thanks for the PR. This looks like a nice piece of software, but it currently does not meet the notability requirements for inclusion into homebrew-core.

If you wish, you can host this formula in your own tap. Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by EwenQuim** [comment]
Is it okay now that entropy has more than 150 stars ? 😁 The docs says project over 75 stars can have access to this repo.

I myself am quite impressed by this immediate success, it seems that it met the audience I wanted.

**Comment by SMillerDev** [comment]
There combination mentioned in the doc is required, not just the stars

**Comment by EwenQuim** [comment]
Can you tell me which criteria isn't met, so I can work on it? Thanks!

image

**Comment by EwenQuim** [comment]
FYI, I created a tap, the formula is available with `brew install ewenquim/repo/entropy`

**Pull request closed without merging**
