### PR TITLE
truffle: deprecate

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- https://github.com/Homebrew/homebrew-cask/pull/161372
- https://github.com/trufflesuite/truffle/commit/5b5312dbd5ffe2d5ec575e078ff09d98eb1b45c2

### CODE REVIEW

**Comment by iMichka** [comment]
`echidna` and `medusa` still seem to be using it and look unaware of the deprecation. I guess we should open upstream issues?

**Comment by chenrui333** [comment]
> `echidna` and `medusa` still seem to be using it and look unaware of the deprecation. I guess we should open upstream issues?

both are using truffle as test dependencies, we can probably just replace truffle usage with hardhat, let me run some tests in my local.

**Comment by chenrui333** [comment]
yeah, totally, thanks @elopez!

**Comment by chenrui333** [comment]
- done via https://github.com/Homebrew/homebrew-core/pull/156152

**Comment by chenrui333** [comment]
Will need a bit time to update truffle related tests (there is some linkage issue, closing this PR for now)

**Pull request closed without merging**
