### PR TITLE
qt: fix macdeployqt

### PR DESCRIPTION
**Pull request by rggjan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This was merged so it could be used in lieu of a patch :DATA: https://github.com/Homebrew/formula-patches/pull/99

**Comment by rggjan** [comment]
Sure, changed :Data: to formula-patches...

**Comment by ilovezfs** [comment]
@rggjan thanks! The URL should be
```
https://raw.githubusercontent.com/Homebrew/formula-patches/a627e0a/qt5/QTBUG-56814.patch
```

**Comment by rggjan** [comment]
Oh, sure, thanks! Missed that...

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@rggjan Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by rggjan** [comment]
You're welcome! Great project, I'm glad to help:)

**Comment by lparsons** [comment]
@ilovezfs Did this get merged?

**Comment by ilovezfs** [comment]
@lparsons indeed: https://github.com/Homebrew/homebrew-core/commit/1d0837fc8ab14a3c40ae014b71effdc46efe4d18

**Comment by lparsons** [comment]
Thanks, strange it doesn't show merged on GitHub (unless there was a different PR?). Anyway, thanks!

**Comment by ilovezfs** [comment]
@lparsons that's always the case for PRs that have bottles since we use `brew pull` on the command line not the GitHub merge button.

**Comment by lparsons** [comment]
Learn something new everyday... ;-)

**Pull request closed without merging**
