### PR TITLE
tree-sitter 0.20.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by bayandin** [comment]
I need this to test https://github.com/Homebrew/brew/pull/11988:
> Reopening PR

Please ignore it

**Comment by bayandin** [comment]
An actor is a user who re-opens a PR:
Example: https://api.github.com/repos/Homebrew/homebrew-core/actions/workflows/tests.yml/runs?event=pull_request&branch=bump-tree-sitter-0.20.0&actor=bayandin

**Comment by carlocab** [comment]
Can I delete my branch now

**Comment by bayandin** [comment]
> Can I delete my branch now

Yep, thanks for the help 😄

**Comment by carlocab** [comment]
🎉

**Pull request closed without merging**
