### PR TITLE
cloudformation-guard 3.0.3

### PR DESCRIPTION
**Pull request by joshfried-aws**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* [BugFix]: Gracefully handle keys for maps that are not of type string by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/418
* [BugFix]: discovered bug in loader when handling type casted nulls by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/420
* [Misc]: Removing unnecessary clones by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/421
* guard: add fuzz target. by @sepehrdaddev in https://github.com/aws-cloudformation/cloudformation-guard/pull/419
* [BugFix]: fix for converting serde_yaml::Value into internal Value type by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/422
* [Docs]: fixing list for cfn-guard-fuzz README.md by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/423
* [Misc]: bumping up nom to version 5.1.3 by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/424
* [BugFix]: fix to catch panic when parsing inner portion of a string by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/426
* [Misc]: bumping up fancy-regex to 0.12.0 by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/427
* [BugFix]: Add check for control characters in regex by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/428
* [BugFix]: Fix panic occurring for regex with incomplete groupings by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/429
* [Misc]: split fuzz targets into 2 by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/430
* [BugFix]: fixing panic in evaluator when query from typeblock is unresolved by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/432
* [Misc]: adding fuzzer to ci by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/433
* [Misc]: changing build and test ci job run on both macos and ubuntu by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/434
* [Misc]: adding multiple targets for install script job by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/435
* [Misc]: adding apple silicon runner to os targets for registry job by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/436
* [Misc]: adding apple silicon runner to os targets for cargo build/test by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/437
* Bump unsafe-libyaml from 0.2.9 to 0.2.10 in /guard/fuzz by @dependabot in https://github.com/aws-cloudformation/cloudformation-guard/pull/439
* Bump unsafe-libyaml from 0.2.5 to 0.2.10 by @dependabot in https://github.com/aws-cloudformation/cloudformation-guard/pull/438
* [Misc]: clippy lints by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/440
* Bump rustix from 0.36.8 to 0.36.17 by @dependabot in https://github.com/aws-cloudformation/cloudformation-guard/pull/441
* [Misc]: Reverting previous changes + bumping up fancy-regex version by @joshfried-aws in https://github.com/aws-cloudformation/cloudformation-guard/pull/442

## New Contributors
* @sepehrdaddev made their first contribution in https://github.com/aws-cloudformation/cloudformation-guard/pull/419

**Full Changelog**: https://github.com/aws-cloudformation/cloudformation-guard/compare/3.0.2...3.0.3</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
@joshfried-aws your base branch is outdated, you need to do `brew update` before filing this PR to avoid merge conflict.

**Comment by joshfried-aws** [comment]
> @joshfried-aws your base branch is outdated, you need to do `brew update` before filing this PR to avoid merge conflict.

Sorry about that, I had rebased. I forgot about this step. Can i rerun the same command now that i've updated?

**Comment by p-linnane** [comment]
Run `brew update`, rebase, and then force push to this branch.

**Comment by chenrui333** [comment]
yeah, just like @p-linnane said :)

**Comment by joshfried-aws** [comment]
> Run `brew update`, rebase, and then force push to this branch.

@p-linnane @chenrui333 sorry, i seem to be having issues. I was trying to rebase off of the repo i cd into when i run 

`cd "$(brew --repository)"` 

But that's clearly not the right way to go about it. Can you clarify here. Sorry about this.

**Comment by p-linnane** [comment]
That's the repository the actual `brew` package manger lives in. You want the homebrew-core repo:
`cd "$(brew --repository)/Library/Taps/homebrew/homebrew-core"`

**Comment by chenrui333** [comment]
another way to do is to run the sync in github UI and pull to update your local branch

image

**Comment by chenrui333** [comment]
or you dont have to anything and it would be covered by the bot

https://github.com/Homebrew/homebrew-core/blob/0bf8bf16dfdadf5a88278d3f930a5180b7f3ba20/.github/workflows/autobump.yml#L299

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
