### PR TITLE
gst-plugins-bad: revision for cocoa set_render_rectangle patch

### PR DESCRIPTION
**Pull request by philn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by tschoonj — CHANGES_REQUESTED** [review]
Patch doesn't apply. Where did you get it from?

**Comment by philn** [comment]
There's this PR https://github.com/Homebrew/formula-patches/pull/217 too. I was hoping the sha1 would be preserved after merge.

**Comment by philn** [comment]
Ok I've updated it, it was indeed not applying correctly. Sorry about this!

**Comment by philn** [comment]
Jenkins is happy now. Please review :)

**Review by tschoonj — APPROVED** [review]

**Comment by philn** [comment]
Can the other PR be merged too?

**Comment by ilovezfs** [comment]
@philn yes but the directory name needs to be the same as the formula name.

**Comment by philn** [comment]
Done :)

**Comment by ilovezfs** [comment]
https://raw.githubusercontent.com/Homebrew/formula-patches/5f5b837/gst-plugins-bad/0001-gl-cocoa-Implement-set_render_rectangle.patch is the merged url

**Comment by philn** [comment]
All set!

**Comment by ilovezfs** [comment]
thanks @philn. please squash this down to 1 commit

**Comment by philn** [comment]
Done!

**Review by ilovezfs — APPROVED** [review]

**Comment by philn** [comment]
So, what now?

**Comment by ilovezfs** [comment]
@philn it looks like the patch belongs inside a `stable do` block since it's already been merged to `head` right?

**Comment by philn** [comment]
It's been merged upstream yes but is not in any stable release of the 1.12 series. I'm not sure what you mean with `stable do` because I'm not fully aware of all recipe features :)

**Comment by ilovezfs** [comment]
@philn look at `go.rb`

**Comment by philn** [comment]
Ah. Like that?

**Comment by ilovezfs** [comment]
Yup, but
```
iMac-TMP:~ joe$ brew audit --strict gst-plugins-bad
gst-plugins-bad:
  * C: 4: col 3: `url` should be put inside `stable` block
  * C: 5: col 3: `sha256` should be put inside `stable` block
  * C: 45: col 3: `stable` (line 45) should be put before `bottle` (line 8)
Error: 3 problems in 1 formula
```

**Comment by ilovezfs** [comment]
@philn I fixed it :)

**Comment by philn** [comment]
Oops. Thanks!

**Comment by ilovezfs** [comment]
@philn thanks for another contribution to Homebrew! Shipped.

**Pull request closed without merging**
