### PR TITLE
Upload bottles to GitHub Packages

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Upload (new) bottles to both GitHub Packages and Bintray.

TODO:
- [x] Merge https://github.com/Homebrew/brew/pull/10948
- [x] Add and setup secret
- [ ] Do some test builds

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]
Let's try it

**Comment by Bo98** [comment]
Is it taking the HEAD of your branch rather than the core master?

**Comment by MikeMcQuaid** [comment]
@bo98 yup, exactly it, figured it out the same time as you 😅

**Comment by Bo98** [comment]
Cheeky bot

**Comment by MikeMcQuaid** [comment]
Pushed a fix in https://github.com/Homebrew/homebrew-core/commit/c78c3be94ca825485bd27523975882adec5f1de1. Will try it out again now.

**Comment by dawidd6** [comment]
```
==> Installing dependencies for skopeo: go, pkg-config, gdbm, mpdecimal, openssl@1.1, gpatch, ncurses, readline, zlib, sqlite, xz, bzip2, expat, libffi, unzip, python@3.9, pcre, swig, m4, adns, libxml2, gettext, berkeley-db, perl, autoconf, automake, gmp, gnu-sed, libatomic_ops, bdw-gc, libtool, libunistring, gperf, guile, libidn2, libtasn1, nettle, p11-kit, libevent, sphinx-doc, cmake, ninja, c-ares, jemalloc, libev, nghttp2, unbound, coreutils, guile@2, autogen, gnutls, libgpg-error, ...
```

This is gonna take forever

**Comment by Bo98** [comment]
`gnupg` has an unfortunately large dependency tree.

Why is it building from source though? Are some of these unbottled on Linux?

**Comment by Bo98** [comment]
Oh right no Linux bottle lines in homebrew-core yet.

**Comment by MikeMcQuaid** [comment]
Reverted in a883956917cd7122e600e01e68853304e6d11ca9 a2bbec6d216c25976e0e0df0a70437c8a54cf1ff

**Pull request merged**
