### PR TITLE
pypy3 5.5.0

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Note that while this is marked as being an "alpha", the last stable release is so old as to be useless, and isn't even provided on the download page anymore. This is the only version provided on the official download page.

cc @tdsmith

### CODE REVIEW

**Comment by tdsmith** [comment]
I requested comment from #pypy. https://botbot.me/freenode/pypy/2016-11-10/?msg=76245027

**Comment by mistydemeo** [comment]
> I requested comment from #pypy.

Thank you!

**Comment by tdsmith** [comment]
I'm 👍  on this unless a strong informed opinion to the contrary appears :)

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by mistydemeo** [comment]
clock_gettime bug on Xcode 8/El Cap: https://bot.brew.sh/job/Homebrew%20Core/11102/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install___pypy3_5_5_0_el_capitan_bottle_tar_gz/

**Comment by mistydemeo** [comment]
The patch we're carrying for pypy is already applied to this pypy3 release.

**Pull request closed without merging**
