### PR TITLE
qemu: Patch for "mprotect failed: Permission denied" issues on Apple …

### PR DESCRIPTION
**Pull request by stefannilsson**
…Silicon.

New PR after discussions in PR https://github.com/Homebrew/homebrew-core/pull/73277.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks. Does this resolve any issues in the stable tarball, whether for ARM or otherwise? We do still need a reason to apply this patch to the stable build.

**Comment by stefannilsson** [comment]
Yes - Same issue exists in `stable`, as reported at: https://github.com/Homebrew/homebrew-core/issues/73286
`stable` suffers from even more troubles though so the only way right now is to use the `HEAD` release for `qemu` on Apple Silicon, with this fix.

**Comment by carlocab** [comment]
I understand that the same issue exists in the stable, but you've also mentioned the patch doesn't resolve it, so this seems not enough to justify the inclusion of the patch. It has to fix _something_ at least.

**Comment by chrmoritz** [comment]
Looks like at least https://github.com/qemu/qemu/commit/653b87eb36045b506b79f0bb433016ef1c54bc9a needs to be applied too, for qemu to work on Apple Silicon.

**Comment by stefannilsson** [comment]
Guess we'll have to wait for a new stable qemu release then from **qemu**-team?

Published my own tap formula as a work around for people with Apple Silicon in need of getting `qemu`  working for the time being:

```brew install stefannilsson/apple/qemu```

**Comment by chrmoritz** [comment]
You could try to apply the patch from that commit too. Maybe it's enough to get the latest stable working, idk. I've unfortunately no access to a apple silicon mac to test it myself.

**Comment by cobbm** [comment]
I am also facing an issue trying to use QEMU installed through homebrew. 
`brew install qemu`
succeeds, and
`qemu-system-x86_64 --version`
works, but launching qemu gives the error
`Could not allocate dynamic translator buffer`.

I have successfully built qemu on M1 by following these instructions:
```
git clone https://git.qemu.org/git/qemu.git
git checkout master -b wip/hvf
curl 'https://patchwork.kernel.org/series/400619/mbox/'|git am --3way
curl 'https://patchwork.kernel.org/project/qemu-devel/patch/20210103145055.11074-1-r.bolshakov@yadro.com/mbox/'|git am --3way
mkdir build
cd build
../configure --target-list=aarch64-softmmu,x86_64-softmmu,i386-softmmu --enable-cocoa
make -j 8
```
which I found here: https://www.sevarg.net/2021/01/09/arm-mac-mini-and-boinc/
however after building my own version, x86 emulation is very slow. I've been using UTM and it's version of qemu seems to emulate x86 much much faster. 
I'm not sure why there is such a huge difference in speed (15 min to boot Windows XP in qemu vs 2 minutes in UTM)

**Comment by Lunaticf** [comment]
> curl 'https://patchwork.kernel.org/project/qemu-devel/patch/20210103145055.11074-1-r.bolshakov@yadro.com/mbox/'|git am --3way

patch merge error...
git clone https://git.qemu.org/git/qemu.git should not be the 5.2.50 version?
I tried checkout 5.2.0 but failed.

**Pull request closed without merging**
