### PR TITLE
mesos 1.2.0

### PR DESCRIPTION
**Pull request by haosdent**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by fxcoudert — CHANGES_REQUESTED** [review]
Could you update resources to `python-gflags 3.1.1`, `protobuf 3.2.0`, `python-dateutil 2.6.0`, `pytz 2016.10`?

**Comment by haosdent** [comment]
@fxcoudert thanks a lot for your review, let me update.

**Comment by haosdent** [comment]
@fxcoudert may you help to check again? I have updated the version.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @haosdent for your contribution!

**Comment by haosdent** [comment]
Thanks a lot for your help @fxcoudert

**Pull request closed without merging**
