### PR TITLE
ansible@2.8 2.8.10

### PR DESCRIPTION
**Pull request by laserscout**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks @laserscout! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by chenrui333** [comment]
@laserscout can you also try to upgrade the python resource dependencies to see if it works with this build? Thanks!

**Comment by chenrui333** [comment]
Here is bunch of possible dependencies bump that I can see

```
==> pbr
5.4.2 -> 5.4.4
==> pytz
2019.2 -> 2019.3
==> cryptography
2.7 -> 2.8
==> idna
2.8 -> 2.9
==> pyOpenSSL
19.0.0 -> 19.1.0
==> Babel
2.7.0 -> 2.8.0
==> Jinja2
2.10.1 -> 2.11.1
==> MarkupSafe
==> PrettyTable
==> PyNaCl
==> PyYAML
5.1.2 -> 5.3.1
==> apache-libcloud
2.5.0 -> 2.8.1
==> appdirs
==> asn1crypto
1.2.0 -> 1.3.0
==> backports.ssl_match_hostname
==> bcrypt
==> boto
==> boto3
1.9.209 -> 1.12.32
==> botocore
1.12.209 -> 1.15.32
==> cachetools
3.1.1 -> 4.0.0
==> certifi
2019.6.16 -> 2019.11.28
==> cffi
1.12.3 -> 1.14.0
==> chardet
==> cliff
2.15.0 -> 3.1.0
==> cmd2
0.9.16 -> 1.0.1
==> contextlib2
0.5.5 -> 0.6.0.post1
==> debtcollector
1.21.0 -> 2.0.0
==> decorator
4.4.0 -> 4.4.2
==> deprecation
==> dictdiffer
0.8.0 -> 0.8.1
==> dnspython
==> docker-py
==> docker-pycreds
==> docutils
0.15.2 -> 0.16
==> dogpile.cache
0.7.1 -> 0.9.0
==> funcsigs
==> google-auth
1.6.3 -> 1.12.0
==> ipaddress
1.0.22 -> 1.0.23
==> iso8601
==> jmespath
0.9.4 -> 0.9.5
==> jsonpatch
1.24 -> 1.25
==> jsonpointer
==> junos-eznc
2.2.1 -> 2.3.1
==> jxmlease
==> kerberos
==> keystoneauth1
3.16.0 -> 3.18.0
==> kubernetes
9.0.1 -> 11.0.0
==> lxml
4.4.1 -> 4.5.0
==> monotonic
==> msgpack
0.6.1 -> 1.0.0
==> munch
2.3.2 -> 2.5.0
==> ncclient
0.6.6 -> 0.6.7
==> netaddr
==> netifaces
==> ntlm-auth
1.3.0 -> 1.4.0
==> oauthlib
==> openshift
0.9.0 -> 0.11.0
==> openstacksdk
0.34.0 -> 0.45.0
==> os-client-config
1.32.0 -> 2.0.0
==> os-service-types
==> osc-lib
1.13.0 -> 2.0.0
==> oslo.config
6.11.0 -> 8.0.1
==> oslo.context
2.22.1 -> 3.0.1
==> oslo.i18n
3.23.1 -> 4.0.0
==> oslo.log
3.44.0 -> 4.1.0
==> oslo.serialization
2.29.1 -> 3.1.0
==> oslo.utils
3.41.0 -> 4.1.0
==> packaging
19.1 -> 20.3
==> paramiko
2.6.0 -> 2.7.1
==> passlib
1.7.1 -> 1.7.2
==> pyasn1
0.4.6 -> 0.4.8
==> pyasn1-modules
0.2.6 -> 0.2.8
==> pycparser
2.19 -> 2.20
==> pycrypto
==> pyparsing
2.4.2 -> 2.4.6
==> pyperclip
1.7.0 -> 1.8.0
==> pyserial
==> pysphere
==> python-consul
==> python-dateutil
2.8.0 -> 2.8.1
==> python-keyczar
==> python-keystoneclient
3.20.0 -> 3.22.0
==> python-neutronclient
6.12.0 -> 7.1.0
==> python-string-utils
0.6.0 -> 1.0.0
==> pywinrm
0.3.0 -> 0.4.1
==> requests
2.22.0 -> 2.23.0
==> requests-credssp
1.0.2 -> 1.1.1
==> requests-oauthlib
1.2.0 -> 1.3.0
==> requests_ntlm
==> requestsexceptions
==> rfc3986
==> rsa
==> ruamel.yaml
0.16.2 -> 0.16.10
==> ruamel.yaml.clib
0.1.2 -> 0.2.0
==> s3transfer
0.2.1 -> 0.3.3
==> scp
==> shade
1.31.0 -> 1.33.0
==> simplejson
3.16.0 -> 3.17.0
==> six
1.12.0 -> 1.14.0
==> stevedore
1.30.1 -> 1.32.0
==> subprocess32
==> unicodecsv
==> urllib3
1.25.3 -> 1.25.8
==> wcwidth
0.1.7 -> 0.1.9
==> websocket_client
0.56.0 -> 0.57.0
==> wrapt
1.11.2 -> 1.12.1
==> xmltodict
==> zabbix-api
```

**Comment by laserscout** [comment]
@chenrui333  I tried it locally and it seems to work. So I pushed the dependencies bump as well.

**Comment by laserscout** [comment]
As I already missed one dependency, I would value a second pair of eyes checking everything.

**Comment by chenrui333** [comment]
Sure, let me test on my local as well.

**Comment by chenrui333** [comment]
tested on my local catalina machine, and squashed the commits ()

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
