### PR TITLE
cdo: fix version

### PR DESCRIPTION
**Pull request by iMichka**
2.4.4 is a moving target.
I updated the livecheck to only check for announced releases

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
This was merged 6 days ago: https://github.com/Homebrew/homebrew-core/pull/191126
Wondering if we should revert back to 2.4.3

**Comment by chenrui333** [comment]
sounds like an upstream issue?

**Comment by iMichka** [comment]
Sort of. They did not announce 2.4.4 and the url changed, so I suspect this is a pre-release.

**Comment by chenrui333** [comment]
let me also reach out to the author as well.

**Comment by cho-m** [comment]
> Sort of. They did not announce 2.4.4 and the url changed, so I suspect this is a pre-release.

Sounds reasonable given previous timeframes, e.g.
* https://code.mpimet.mpg.de/projects/cdo/activity?from=2024-06-27
  * `2024-06-21` 2.4.2 last tarball upload
  * `2024-06-27` 2.4.2 official release
* https://code.mpimet.mpg.de/projects/cdo/activity?from=2024-08-26
  * `2024-08-20` 2.4.3 last tarball upload
  * `2024-08-21` 2.4.3 official release

Probably some RCs in progress for 2.4.4

**Review by carlocab — APPROVED** [review]
We differ only in the patch version so I'm ok with merging this for now. We can revert to 2.4.3 (without a `version_scheme` bump) if desired.

**Pull request merged**
