### PR TITLE
Tomcat@10.0

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

According to [Apache Tomcat Versions](https://tomcat.apache.org/whichversion.html), tomcat 10.1 and 10.0 support different Java Versions, different Specs. And both tomcat 10.1 and 10.0 will be support by Apache Tomcat Team.
I think that since we already have `tomcat@8`, `tomcat@9` and `tomcat@10`, we should add `tomcat@10.0` and `tomcat@10.1`.

### CODE REVIEW

**Comment by moonfruit** [comment]
Why is this pull request not accepted? @fxcoudert

**Comment by SMillerDev** [comment]
Because nobody reviewed it yet.

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Do you have any links where tomcat says they will support this version? Because that's not stated in the link in the description as far as I can see.

**Comment by moonfruit** [comment]
Here: https://tomcat.apache.org/whichversion.html

**Comment by moonfruit** [comment]
Sorry, I haven't noticed that Apache Tomcat marked version 10.0.x as superseded **recently**.

**Pull request closed without merging**
