### PR TITLE
fb303, fbthrift, fizz, folly, wangle, watchman: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by krehel**
See #134251

### CODE REVIEW

**Comment by p-linnane** [comment]
We are going to have to do the whole Facebook suite in one PR (`edencommon`, `fb303`, `fbthrift`, `fizz`, `folly`, `wangle`, `watchman`)

**Comment by krehel** [comment]
Thanks @p-linnane - I'll close this

**Comment by p-linnane** [comment]
You can just push the updates to all the other ones here and we can run it.

**Comment by krehel** [comment]
Sounds good @p-linnane!

**Comment by krehel** [comment]
Note that `edencommon` did not appear to have a dependency on `openssl` and therefore was not updated

**Comment by p-linnane** [comment]
`fb303` has no linkage with `openssl@3` on Linux.

cc @carlocab

**Review by carlocab — APPROVED** [review]
> `fb303` has no linkage with `openssl@3` on Linux.

That's fine, it didn't have linkage with `openssl@1.1` on Linux either.

**Pull request merged**
