### PR TITLE
lua-language-server 2.6.1

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

I believe the test changes from the last bump can be reverted again (the old test was much simpler).

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by clason** [comment]
Does this mean I _should_ revert the change? Or is the more robust test better anyway?

**Comment by carlocab** [comment]
Simpler test is better, I think.

**Comment by clason** [comment]
I just tested locally, and the old test still fails (or rather, again, since it passed briefly on HEAD).

Let's go with the current test for now and revisit on the next release.

**Comment by carlocab** [comment]
> I just tested locally, and the old test still fails (or rather, again, since it passed briefly on HEAD).

I suspected this would happen, hence my desire not to punt. Good thing we didn't 😄

**Pull request closed without merging**
