### PR TITLE
ghc 9.4.4

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by fishtreesugar** [comment]
@chenrui333 @cho-m pls add "CI-long-timeout" label

**Comment by chenrui333** [comment]
on linux

```
    ghcide compiled against GHC 9.4.3 but currently using 9.4.4
```

**Comment by chenrui333** [comment]
```
  Command line: /opt/homebrew/opt/sphinx-doc/bin/sphinx-build -b man -d /private/tmp/extra-dir-55768274273/.doctrees-man -n -w /private/tmp/extra-dir-55768274273/.log docs/users_guide /private/tmp/extra-dir-55768274273
  ===> Command failed with error code: 2
  
  Exception occurred:
    File "/opt/homebrew/Cellar/sphinx-doc/6.0.0/libexec/lib/python3.11/site-packages/sphinx/ext/extlinks.py", line 101, in role
      title = caption % part
              ~~~~~~~~^~~~~~
  TypeError: not all arguments converted during string formatting
```

**Comment by chenrui333** [comment]
raised an upstream bug report, https://gitlab.haskell.org/ghc/ghc/-/issues/22690

**Comment by chenrui333** [comment]
cancelled the workflow run.

**Comment by cho-m** [comment]
> Command line: /opt/homebrew/opt/sphinx-doc/bin/sphinx-build -b man -d /private/tmp/extra-dir-55768274273/.doctrees-man -n -w /private/tmp/extra-dir-55768274273/.log docs/users_guide /private/tmp/extra-dir-55768274273
>   ===> Command failed with error code: 2
>   
>   Exception occurred:
>     File "/opt/homebrew/Cellar/sphinx-doc/6.0.0/libexec/lib/python3.11/site-packages/sphinx/ext/extlinks.py", line 101, in role
>       title = caption % part
>               ~~~~~~~~^~~~~~
>   TypeError: not all arguments converted during string formatting

Probably some deprecated behavior removed in Sphinx 6.

Specifically https://github.com/sphinx-doc/sphinx/commit/ce31e1c0c7b32f6be93186e0fef076ef65ff0b05#diff-437b1b031f7488e4c051cd111e665fe4b514cba5c64b9f2f23b9cd04aacd89bb

GHC usage is https://gitlab.haskell.org/ghc/ghc/-/blob/master/docs/users_guide/ghc_config.py.in#L1-4
```py
extlinks = {
    'ghc-ticket': ('https://gitlab.haskell.org/ghc/ghc/issues/%s', '#'),
    'ghc-wiki': ('https://gitlab.haskell.org/ghc/ghc/wikis/%s', '#'),
}
```

Could try appending `%s`, e.g.
```py
extlinks = {
    'ghc-ticket': ('https://gitlab.haskell.org/ghc/ghc/issues/%s', '#%s'),
    'ghc-wiki': ('https://gitlab.haskell.org/ghc/ghc/wikis/%s', '#%s'),
}
```

**Comment by cho-m** [comment]
As note, the Sphinx new behavior was introduced in 4.0.0.

GHC minimum Sphinx requirement is 1.0.0, so may need to be handled based on Sphinx version or by uplifting minimum requirement.

**Comment by cho-m** [comment]
Trying out upstream MR for `ghc@9.2`: #117867.

**Comment by chenrui333** [comment]
> > Command line: /opt/homebrew/opt/sphinx-doc/bin/sphinx-build -b man -d /private/tmp/extra-dir-55768274273/.doctrees-man -n -w /private/tmp/extra-dir-55768274273/.log docs/users_guide /private/tmp/extra-dir-55768274273
> > ===> Command failed with error code: 2
> > Exception occurred:
> > File "/opt/homebrew/Cellar/sphinx-doc/6.0.0/libexec/lib/python3.11/site-packages/sphinx/ext/extlinks.py", line 101, in role
> > title = caption % part
> > ~~~~~~~~^~~~~~
> > TypeError: not all arguments converted during string formatting
> 
> Probably some deprecated behavior removed in Sphinx 6.
> 
> Specifically [sphinx-doc/sphinx@ce31e1c#diff-437b1b031f7488e4c051cd111e665fe4b514cba5c64b9f2f23b9cd04aacd89bb](https://github.com/sphinx-doc/sphinx/commit/ce31e1c0c7b32f6be93186e0fef076ef65ff0b05#diff-437b1b031f7488e4c051cd111e665fe4b514cba5c64b9f2f23b9cd04aacd89bb)
> 
> GHC usage is https://gitlab.haskell.org/ghc/ghc/-/blob/master/docs/users_guide/ghc_config.py.in#L1-4
> 
> ```python
> extlinks = {
>     'ghc-ticket': ('https://gitlab.haskell.org/ghc/ghc/issues/%s', '#'),
>     'ghc-wiki': ('https://gitlab.haskell.org/ghc/ghc/wikis/%s', '#'),
> }
> ```
> 
> Could try appending `%s`, e.g.
> 
> ```python
> extlinks = {
>     'ghc-ticket': ('https://gitlab.haskell.org/ghc/ghc/issues/%s', '#%s'),
>     'ghc-wiki': ('https://gitlab.haskell.org/ghc/ghc/wikis/%s', '#%s'),
> }
> ```

yeah, upstream had the same patch, https://gitlab.haskell.org/ghc/ghc/-/commit/00dc51060881df81258ba3b3bdf447294618a4de

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @cho-m!

**Pull request closed without merging**
