### PR TITLE
libgit2 0.28.1

### PR DESCRIPTION
**Pull request by hobbsh**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

#38263 has been opened already, but this PR has all the required changes. All changes built/tested/audited on Mojave.

Currently running into an issue with `libgit2-glib` not building from source because of `meson-internal` version being too old. Not sure what the course of action should be:

```
homebrew-core whobbs$ brew install --build-from-source Formula/libgit2-glib.rb
==> Downloading https://download.gnome.org/sources/libgit2-glib/0.27/libgit2-glib-0.27.8.tar.xz
Already downloaded: /Users/whobbs/Library/Caches/Homebrew/downloads/d3fe0e2f5e31878891ee4f71a4a6cef428faeb2a2f7bb6c20cf69f6e3ee1b373--libgit2-glib-0.27.8.tar.xz
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
libgit2-glib/meson.build:
  expected replacement of "libgit2_glib_link_args = [ '-Wl,-Bsymbolic-functions' ]" with "libgit2_glib_link_args = []"
```

So I removed that section and now I get:

```
==> Downloading https://download.gnome.org/sources/libgit2-glib/0.27/libgit2-glib-0.27.8.tar.xz
Already downloaded: /Users/whobbs/Library/Caches/Homebrew/downloads/d3fe0e2f5e31878891ee4f71a4a6cef428faeb2a2f7bb6c20cf69f6e3ee1b373--libgit2-glib-0.27.8.tar.xz
==> meson --prefix=/usr/local/Cellar/libgit2-glib/0.27.8 -Dpython=false -Dvapi=true ..
Last 15 lines from /Users/whobbs/Library/Logs/Homebrew/libgit2-glib/01.meson:
meson
--prefix=/usr/local/Cellar/libgit2-glib/0.27.8
-Dpython=false
-Dvapi=true
..

The Meson build system
Version: 0.46.1
Source dir: /private/tmp/libgit2-glib-20190402-31281-iao806/libgit2-glib-0.27.8
Build dir: /private/tmp/libgit2-glib-20190402-31281-iao806/libgit2-glib-0.27.8/build
Build type: native build

meson.build:1:0: ERROR:  Meson version is 0.46.1 but project requires >= 0.48.0.

A full log can be found at /private/tmp/libgit2-glib-20190402-31281-iao806/libgit2-glib-0.27.8/build/meson-logs/meson-log.txt

Do not report this issue to Homebrew/brew or Homebrew/core!
```

### CODE REVIEW

**Comment by Moisan** [comment]
The `inreplace` in `libgit2-glib` is failing.

**Comment by hobbsh** [comment]
@Moisan If I remove the `inreplace` block, the second error shows up and I'm not really sure what the best course of action would be. Let me know and I can make the change. Thanks

**Comment by tschoonj** [comment]
This should fix the `libgit2-glib` formula for use with the regular `meson`.

**Comment by Moisan** [comment]
Thank you @hobbsh  or your first contribution! Without people like you, we couldn't run this project.

Thank you also @tschoonj for the help!

**Pull request closed without merging**
