### PR TITLE
podman-tui v1.2.0

### PR DESCRIPTION
**Pull request by navidys**
podman-tui v1.2.0

### CODE REVIEW

**Review by branchv — APPROVED** [review]

**Comment by navidys** [comment]
Hi @branchvincent 

Thanks for the approve, however MAC 12 X64 is failing which I am not sure why (the MAC 12 ARM is passed).

I'll appreciate if you can have a look.

Regards

**Comment by branchvincent** [comment]
I'd try bumping to `sleep 3` (intel machines are just a little slower)

Btw, can we also simplify the build by using the same `binary` make target on mac? It seems to be the same as `binary-darwin`, unless I'm missing something

**Comment by navidys** [comment]
Thanks @branchvincent 

I don't think so at this stage, I need to be able generate Linux, MAC and windows binaries from a Linux nodes as part of each release thats why there are  `binary-darwin` and `binary-win` targets.

**Comment by branchvincent** [comment]
That makes sense, but homebrew builds on each supported os/arch separately. So the formulae can just run `make build`

**Review by ZhongRuoyu — APPROVED** [review]
Thanks, @navidys!

**Pull request merged**
