### PR TITLE
mongodb 4.0.5

### PR DESCRIPTION
**Pull request by utkonos**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
`gotools` doesn't seem to contain `build.sh` anymore.

**Comment by utkonos** [comment]
I've found the problem. 4.0.5, unfortunately has a path problem in the source tarball that was introduced it appears via a copy paste error by one of the maintainers. I've submitted a pull request to fix it here:

https://github.com/mongodb/mongo/pull/1290

Also, I've opened a bug report in mongo's JIRA here:

https://jira.mongodb.org/browse/SERVER-38804

I think they will need to push a 4.0.6 source tarball. Once that's pushed, homebrew should update to 4.0.6 and skip this one (or someone else can try to untie the path knots to get this version to build correctly).

**Comment by utkonos** [comment]
After repackaging the tarball with the directory problem corrected, I have tested by uploading the patched tarball to S3. There is a change to `build.sh` in 4.0.5 where the find and replace using in the old formula is wrong. Removing those lines of find and replace, it now dies with a new error:

```
==> ./build.sh ssl
Last 15 lines from /Users/administrator/Library/Logs/Homebrew/mongodb/04.build.sh:
2019-01-02 00:31:53 -0500

./build.sh
ssl

GOROOT not set and preferred GOROOT '/opt/golang/go1.10' doesn't exist. Aborting.
```

**Comment by utkonos** [comment]
The path change was on purpose according to the maintainers. The reason is that gotools are no longer provided in the mongodb tarball. gotools is now mongo-tools and provided as a separate repo https://github.com/mongodb/mongo-tools . This new package appears to be required to build and also to run mongo.

**Comment by utkonos** [comment]
As requested by the maintainers, I've opened a ticket here with the latest info about the build failure:

https://jira.mongodb.org/browse/TOOLS-2184

**Comment by utkonos** [comment]
Found the problems and fixed them. Closing this in favor of this pull:
https://github.com/Homebrew/homebrew-core/pull/35717

**Pull request closed without merging**
