### PR TITLE
knot 2.7.6

### PR DESCRIPTION
**Pull request by salzmdan**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by salzmdan** [comment]
It seems bottles for userspace-rcu-0.10.2 were not updated.

**Comment by fxcoudert** [comment]
Building the missing `userspace-rcu` bottles in https://jenkins.brew.sh/job/Homebrew%20Testing/1152/

**Comment by fxcoudert** [comment]
And now it should be good. @BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
        ==> Determining knot bottle rebuild...
Error: Failed changing install name in /usr/local/Cellar/knot/2.7.6/sbin/kjournalprint
  from /usr/local/Cellar/knot/2.7.6/lib/libdnssec.6.dylib
    to @@HOMEBREW_CELLAR@@/knot/2.7.6/lib/libdnssec.6.dylib
Error: Failed changing install name in /usr/local/Cellar/knot/2.7.6/bin/kdig
  from @@HOMEBREW_CELLAR@@/knot/2.7.6/lib/libdnssec.6.dylib
    to /usr/local/Cellar/knot/2.7.6/lib/libdnssec.6.dylib
Error: Unrecognized Mach-O magic: 0x00
```

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @salzmdan for the pull request, and sorry it took so long to merge

**Pull request closed without merging**
