### PR TITLE
minica 1.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
Not the latest release https://github.com/jsha/minica/releases

**Comment by chenrui333** [comment]
- https://github.com/jsha/minica/issues/69

**Comment by chenrui333** [comment]
close for now.

**Comment by Moisan** [comment]
This is now the latest release.

**Review by samford — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
