### PR TITLE
openssl@3 3.1.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> Pouring fluent-bit--2.1.9.arm64_monterey.bottle.tar.gz
  The formula built, but is not symlinked into /opt/homebrew
  Could not symlink bin/luajit
  Target /opt/homebrew/bin/luajit
  is a symlink belonging to luajit. You can unlink it:
    brew unlink luajit
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite fluent-bit
  
  To list all files that would be deleted:
    brew link --overwrite --dry-run fluent-bit
```

**Comment by SMillerDev** [comment]
Yeah, https://github.com/Homebrew/homebrew-core/issues/143177 reports that too. I think we need to make them conflict, or get fluent-bit to stop using vendored dependencies of everything.

**Comment by ZhongRuoyu** [comment]
`fluent-bit` should be fixed by #145109.

**Review by ZhongRuoyu — APPROVED** [review]
`fluent-bit` is fixed by #145109.

`ntp` looks like a network issue.

`condure` timed out again.

**Pull request merged**
