### PR TITLE
gmp 6.2.1

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Force-pushed to remove the patch and assorted ARM configure tricks

**Comment by miccal** [comment]
Thank you @fxcoudert, apologies for missing that.

**Comment by fxcoudert** [comment]
Effing style police 😢

**Comment by miccal** [comment]
11.0 failures:
```
brew test --retry --verbose augustus
brew test --retry --verbose dungeon
brew test --retry --verbose monkeysphere
brew test --retry --verbose ncview
brew test --retry --verbose networkit
brew test --retry --verbose pipgrip
brew test --retry --verbose root
```

10.13 failures:
```
brew test --retry --verbose ffmpeg@2.8
```

**Comment by fxcoudert** [comment]
The 11.0 failures are for formulas that still have missing Big Sur bottles. Merging.

**Pull request closed without merging**
