### PR TITLE
notcurses: build on Linux

### PR DESCRIPTION
**Pull request by carlocab**
Using GCC doesn't work, so let's try Clang.

### CODE REVIEW

**Comment by carlocab** [comment]
@dankamongmen do these errors mean anything to you? Do we just have the wrong C++ standard set, or something?

**Comment by dankamongmen** [comment]
> @dankamongmen do these errors mean anything to you? Do we just have the wrong C++ standard set, or something?

`std::is_same` is c++2017 (https://en.cppreference.com/w/cpp/types/is_same), and as CMake specifies, we do indeed need a C++17  compiler. CMake ought be adding `-std=c++17` to the invocation arguments.

**Comment by Bo98** [comment]
This still uses GCC 5 C++ headers, that's why.

I'd recommend using GCC 10 here - what's the error with that? Otherwise we would need to switch entirely to libc++.

**Comment by carlocab** [comment]
```
In file included from /usr/include/string.h:630,
                 from /tmp/notcurses-20210914-22292-1761r02/notcurses-2.4.1/src/lib/direct.c:6:
/tmp/notcurses-20210914-22292-1761r02/notcurses-2.4.1/src/compat/compat.h:82:7: error: expected identifier or '(' before '__extension__'
   82 | char* strndup(const char* str, size_t size);
      |       ^~~~~~~
CMakeFiles/notcurses-core.dir/build.make:120: recipe for target 'CMakeFiles/notcurses-core.dir/src/lib/direct.c.o' failed
make[2]: *** [CMakeFiles/notcurses-core.dir/src/lib/direct.c.o] Error 1
```
https://github.com/Homebrew/homebrew-core/pull/85148/checks?check_run_id=3597979801#step:7:327

I guess it's still the same problem as here.

**Comment by Bo98** [comment]
Looks like that error didn't disappear with Clang.

`strndup` is a #define on our Ubuntu installation so overriding that will just break things. If overriding it is the intention, it looks like a `#undef strndup` is needed - this is what `glibc` does.

**Comment by carlocab** [comment]
That just reads like a forward declaration and not an override to me?

**Comment by Bo98** [comment]
Well, it's a header and there's a `.c` file we've not yet reached but the point still stands.

From our glibc: https://github.com/bminor/glibc/blob/glibc-2.23/string/bits/string2.h#L1295-L1321

This would result in the declaration being:

```
char* (__extension__ (__builtin_constant_p (s) && __string2_1bptr_p (s)	      \
		  ? (((const char *) (s))[0] == '\0'			      \
		     ? (char *) calloc ((size_t) 1, (size_t) 1)		      \
		     : ({ size_t __len = strlen (s) + 1;		      \
			  size_t __n = (n);				      \
			  char *__retval;				      \
			  if (__n < __len)				      \
			    __len = __n + 1;				      \
			  __retval = (char *) malloc (__len);		      \
			  if (__retval != NULL)				      \
			    {						      \
			      __retval[__len - 1] = '\0';		      \
			      __retval = (char *) memcpy (__retval, s,	      \
							  __len - 1);	      \
			    }						      \
			  __retval; }))					      \
		  : __strndup (s, n)))(const char* str, size_t size);
```

Which is obviously not what is desired.

The fix would be to do one of:

* Use one available in the system if available
* Call it something else
* Check for and undef `strndup`

**Comment by carlocab** [comment]
What happens if we define `_HAVE_STRING_ARCH_strndup`?

**Comment by Bo98** [comment]
Sounds like a hack to a problem that should probably be resolved upstream.

**Comment by dankamongmen** [comment]
> Sounds like a hack to a problem that should probably be resolved upstream.

indeed; if y'all want to use these compilers, let me go get things working with these compilers.

**Comment by Bo98** [comment]
I'd say you will probably manage to reproduce the issue with Ubuntu 16.04. Using the latest GCC (11) is fine - `glibc` version is the main blocker here.

**Comment by carlocab** [comment]
Let's revisit this later.

**Comment by dankamongmen** [comment]
hey there, sorry, forgot all about this. i'd love to build in Linuxbrew. if you'd be willing, @carlocab (or anyone else), please file an issue on Notcurses explaining what needs done, and i'll make sure it happens, ideally before the 3.0.0 release coming up this November.

**Comment by carlocab** [comment]
Well, part of the reason I've closed this is 1) I'm not super clear on what needs to be done (which makes filing an issue tricky), and 2) I suspect the problem will go away when we start building on Ubuntu 18.04 (migration should happen at some point soon).

Point 2 above in particular means we might be able to get this built on Linux by just waiting a little bit.

**Pull request closed without merging**
