### PR TITLE
ffmpeg 5.1

### PR DESCRIPTION
**Pull request by joh-klein**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by billyzs — COMMENTED** [review]
I think the text replacement block beginning at line 127 needs to be removed for this version. Upstream changed the wording in source and docs so the text replacement is no longer needed (and now fails)

**Comment by billyzs** [comment]
> I think the text replacement block beginning at line 127 needs to be removed for this version. Upstream changed the wording in source and docs so the text replacement is no longer needed (and now fails)

tried this locally and seem to have worked.

**Comment by carlocab** [comment]
Does it pick up the right search path for vmaf models now?

**Comment by slhck** [comment]
@carlocab In our custom tap we've [removed these lines](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/commit/5ab700c566cff70b0a9a8e74f25b4e5e71a7acc5) and the libvmaf filter runs fine.

```
ffmpeg -f lavfi -i testsrc=duration=10 -f lavfi -i testsrc=duration=10 -filter_complex libvmaf -f null /dev/null
ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --enable-opencl --enable-audiotoolbox --enable-videotoolbox --enable-neon --disable-htmlpages --enable-libvmaf --enable-version3
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, lavfi, from 'testsrc=duration=10':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn
Input #1, lavfi, from 'testsrc=duration=10':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 (rawvideo) -> libvmaf
  Stream #1:0 (rawvideo) -> libvmaf
  libvmaf:default -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
Output #0, null, to '/dev/null':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: wrapped_avframe, yuv444p(tv, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 200 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.37.100 wrapped_avframe
frame=  250 fps=117 q=-0.0 Lsize=N/A time=00:00:10.00 bitrate=N/A speed=4.67x
video:115kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_libvmaf_0 @ 0x103904080] VMAF score: 97.925365
```

**Comment by joh-klein** [comment]
@carlocab I don't know what to do now … maybe you have an idea?

**Comment by SMillerDev** [comment]
This should be resolved:
```
Missing libraries:
    unexpected (libGLU.so.1)
```

**Comment by carlocab** [comment]
> This should be resolved:
> ```
> Missing libraries:
>     unexpected (libGLU.so.1)
> ```

Resolved in https://github.com/Homebrew/homebrew-core/pull/106591.

Rebase to rerun CI.

**Comment by carlocab** [comment]
For `corsixth`:
```
  An exception occurred within a child process:
    Minitest::Assertion: Expected /Welcome\ to\ CorsixTH/ to match "dyld[80775]: Symbol not found: _av_get_default_channel_layout\r\n  Referenced from: /opt/homebrew/Cellar/corsixth/0.66/CorsixTH.app/Contents/MacOS/CorsixTH\r\n  Expected in: /opt/homebrew/Cellar/ffmpeg/5.1/lib/libavcodec.59.37.100.dylib\r\n".
```

[`_av_get_default_channel_layout`](https://github.com/FFmpeg/FFmpeg/blob/6f8b8e633205ab690a6a33b139f4e95828e4892f/libavutil/channel_layout.h#L451-L457) is deprecated but seems to be there still. However, it appears to be in `libavutil` and not `libavcodec`.

For `fceux`:
```
  dyld[82853]: Symbol not found: _av_frame_make_writable
    Referenced from: /opt/homebrew/Cellar/fceux/2.6.4_1/libexec/fceux
    Expected in: /opt/homebrew/Cellar/ffmpeg/5.1/lib/libavcodec.59.37.100.dylib
```

Similar thing for [`_av_frame_make_writable`](https://github.com/FFmpeg/FFmpeg/blob/130d19bf2044ac76372d1b97ab87ab283c8b37f8/libavutil/frame.h#L827-L838) (except it's not deprecated).

Not sure why it's failing on Monterey but not on Big Sur. Did Apple change something in `dyld`?

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
