### PR TITLE
ace 7.0.10

### PR DESCRIPTION
**Pull request by jwillemsen**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jwillemsen** [comment]
Not sure why ests/ubuntu-22.04 fails, we have versioned libraries, so we now create libACE.so.7.0.10, not libACE.so.7.0.9

**Comment by SMillerDev** [comment]
ivtools needs a revision bump because of that.

**Comment by jwillemsen** [comment]
Ok, I see that now, will make that change

**Review by SMillerDev — DISMISSED** [review]
Thanks @jwillemsen  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
CI didn't run, let's try again

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
