### PR TITLE
phoronix-test-suite: 10.4.0, remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by yurikoles**
See #75943.

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nandahkrishna** [comment]
```
5b077d7dbfae6f43206b81dfb18b93c9497a5677fafeb9d9116f16469b9cab05  phoronix-test-suite--10.2.2.arm64_big_sur.bottle.tar.gz
e295d87acb4da40bcd1f1b13b0e9fe23bd93a14c4e92b9dd8c8aaf31dd6f6cb2  phoronix-test-suite--10.2.2.big_sur.bottle.tar.gz
e295d87acb4da40bcd1f1b13b0e9fe23bd93a14c4e92b9dd8c8aaf31dd6f6cb2  phoronix-test-suite--10.2.2.catalina.bottle.tar.gz
e295d87acb4da40bcd1f1b13b0e9fe23bd93a14c4e92b9dd8c8aaf31dd6f6cb2  phoronix-test-suite--10.2.2.mojave.bottle.tar.gz
```

From the diff, quite a few files need `inreplace`s.

**Comment by yurikoles** [comment]
I'm unsure why checksum differs for arm64, I ran diff on archives contents, it's same.

**Comment by bayandin** [comment]
Here's an example of difference in files (`phoronix-test-suite/10.4.0/bin/phoronix-test-suite`):

```diff
-elif [ -x /usr/bin/php7 ] || [ -x @@HOMEBREW_PREFIX@@/bin/php7 ] || [ -x /usr/pkg/bin/php7 ]
+elif [ -x /usr/bin/php7 ] || [ -x /usr/local/bin/php7 ] || [ -x /usr/pkg/bin/php7 ]
 then
 	export PHP_BIN="php7"
-elif [ -x /usr/bin/php8 ] || [ -x @@HOMEBREW_PREFIX@@/bin/php8 ] || [ -x /usr/pkg/bin/php8 ]
+elif [ -x /usr/bin/php8 ] || [ -x /usr/local/bin/php8 ] || [ -x /usr/pkg/bin/php8 ]
```

On Apple Silicon we keep `/usr/local`, on Intel Mac we use `@@HOMEBREW_PREFIX@@` placeholder

**Comment by nandahkrishna** [comment]
We could probably use `inreplace` to change `/usr/local` to `HOMEBREW_PREFIX` like we did when bottling the other formulae with similar diffs.

**Comment by yurikoles** [comment]
```
$ grep -R "@@HOMEBREW_PREFIX@@" phoronix-test-suite_amd64 -l | wc -l
$ 35
```

Is there a better way? Because I see 35 files with `@@HOMEBREW_PREFIX@@` in Intel bottle and `inreplace` expects a list of files, it doesn't support recursion on directories.

**Comment by MikeMcQuaid** [comment]
@nandahkrishna and others: I think it's good to fix this stuff up but I don't think it should block these PRs. We can make these fixes after stuff is bottled.

**Comment by nandahkrishna** [comment]
Sure Mike. In some places though, such as in #78756, we really shouldn't be changing `/usr/local` to `HOMEBREW_PREFIX` – like within a Dockerfile for an Alpine Linux image. I understand this comment isn't topical to this PR, but is there a way we can skip this/avoid this behaviour?

As for this PR, I'll get it merged right away.

**Review by nandahkrishna — APPROVED** [review]
Thanks, @yurikoles. We can do the `inreplace`/other fixes later if required.

**Pull request closed without merging**
