### PR TITLE
llvm 16.0.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Before rev bumping the linkage failures, check if they work with LLVM 16. It's more likely than not that they work only with LLVM 15 or older.

**Comment by carlocab** [comment]
macOS failures are pretty similar:
```
brew test --retry --verbose c2rust
brew test --retry --verbose castxml
brew test --retry --verbose enzyme
brew test --retry --verbose halide
brew test --retry --verbose include-what-you-use
brew test --retry --verbose ispc
brew test --retry --verbose nvc # not on 12, 11-arm64
brew test --retry --verbose pocl
brew test --retry --verbose spirv-llvm-translator
brew test --retry --verbose symengine # not on 11-arm64, 11
```
Linux failures:
```
Error: 28 failed steps!
brew linkage --test c2rust
brew test --retry --verbose c2rust
brew linkage --test castxml
brew test --retry --verbose castxml
brew test --retry --verbose cf4ocl
brew test --retry --verbose clinfo
brew linkage --test creduce
brew linkage --test enzyme
brew test --retry --verbose enzyme
brew linkage --test halide
brew test --retry --verbose halide
brew test --retry --verbose hashcat
brew linkage --test include-what-you-use
brew test --retry --verbose include-what-you-use
brew linkage --test ispc
brew test --retry --verbose ispc
brew linkage --test mesa
brew linkage --test nvc
brew test --retry --verbose nvc
brew linkage --test pocl
brew test --retry --verbose pocl
brew linkage --test pyqt
brew test --retry --verbose pyqt
brew linkage --test qt
brew linkage --test spirv-llvm-translator
brew test --retry --verbose spirv-llvm-translator
brew linkage --test symengine
brew test --retry --verbose symengine
```

**Comment by carlocab** [comment]
Some notes here. The following formulae are likely broken because `pocl` is broken. Revision bumps will probably not be needed.
- c4ocl
- clinfo
- hashcat

**Review by MikeMcQuaid — DISMISSED** [review]

**Comment by carlocab** [comment]
Yea, should be fine. The new version of `castxml` should also support LLVM 16.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
- castxml https://github.com/Homebrew/homebrew-core/pull/126465
- pocl https://github.com/Homebrew/homebrew-core/pull/126466
- pyqt https://github.com/Homebrew/homebrew-core/actions/runs/4503312053
- spirv-llvm-translator https://github.com/Homebrew/homebrew-core/actions/runs/4503312132
- symengine https://github.com/Homebrew/homebrew-core/actions/runs/4503312261

That should be all left outstanding here.

**Comment by carlocab** [comment]
Build failure for `pyqt` is not very helpful:
```
  sip-install: '/home/linuxbrew/.linuxbrew/opt/qt/bin/qmake -recursive PyQt6-WebEngine.pro' failed returning 3
```
https://github.com/Homebrew/homebrew-core/actions/runs/4504170179/jobs/7928305146#step:8:301

CC @Homebrew/linux, @paperchalice for ideas.

**Comment by iMichka** [comment]
Weird. I'm trying to get it to build in a docker container and I am stuck a few steps before that in the `pyqt`build:

```
==> sip-install --target-dir /home/linuxbrew/.linuxbrew/Cellar/pyqt/6.4.2_1/lib/python3.11/site-packages --scripts-dir /home/linuxbrew/.linuxbrew/Cellar/pyqt/6.4.2_1/bin --confirm-license
Querying qmake about your Qt installation...
This is the GPL version of PyQt 6.4.2 (licensed under the GNU General Public License) for Python 3.11.2 on linux.
Found the license file 'pyqt-gpl.sip'.
Checking to see if the QtCore bindings can be built...
Checking to see if the QtNetwork bindings can be built...
Checking to see if the QtGui bindings can be built...
Checking to see if the QtQml bindings can be built...
Checking to see if the QtWidgets bindings can be built...
Checking to see if the QtDBus bindings can be built...
The QtDesigner bindings are disabled with a static Qt installation...
Checking to see if the QtHelp bindings can be built...
Checking to see if the QtOpenGL bindings can be built...
Checking to see if the QtOpenGLWidgets bindings can be built...
Checking to see if the QtPrintSupport bindings can be built...
Checking to see if the QtQuick bindings can be built...
Checking to see if the QtQuick3D bindings can be built...
Checking to see if the QtQuickWidgets bindings can be built...
Checking to see if the QtSql bindings can be built...
Checking to see if the QtSvg bindings can be built...
Checking to see if the QtSvgWidgets bindings can be built...
Checking to see if the QtTest bindings can be built...
Checking to see if the QtXml bindings can be built...
Checking to see if the QtMultimedia bindings can be built...
Checking to see if the QtMultimediaWidgets bindings can be built...
Checking to see if the QtPositioning bindings can be built...
Checking to see if the QtRemoteObjects bindings can be built...
Checking to see if the QtSensors bindings can be built...
Checking to see if the QtSerialPort bindings can be built...
Checking to see if the QtWebChannel bindings can be built...
Checking to see if the QtWebSockets bindings can be built...
Checking to see if the QtBluetooth bindings can be built...
Checking to see if the QtNfc bindings can be built...
Checking to see if the QtPdf bindings can be built...
Checking to see if the QtPdfWidgets bindings can be built...
Checking to see if the QtTextToSpeech bindings can be built...
Checking to see if the QAxContainer bindings can be built...
sip-install: There are no bindings that can be built
```

**Comment by iMichka** [comment]
Tried to run that step with verbose mode, getting suspicious stuff:
```
Checking to see if the QtHelp bindings can be built...
/home/linuxbrew/.linuxbrew/opt/qt/bin/qmake QtHelp.pro
Info: creating stash file /tmp/tmpbqyx_pk0/cfgtest_QtHelp/.qmake.stash
make
g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_HELP_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/include/QtHelp -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/include/QtWidgets -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/include/QtGui -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/include/QtSql -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/share/qt/mkspecs/linux-g++ -o cfgtest_QtHelp.o cfgtest_QtHelp.cpp
g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib -Wl,-rpath-link,/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib -o QtHelp  cfgtest_QtHelp.o   /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib/libQt6Help.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib/libQt6Widgets.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib/libQt6Gui.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib/libQt6Sql.so /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib/libQt6Core.so -lpthread -lGL
/home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.3_1/lib/libQt6Core.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
```

I'm going to rebuild `qt` from source to see if it goes away.

**Comment by iMichka** [comment]
Disregard my two comments above I had a broken qt install due to other reasons. I made a new try in a clean container and I am now at the same issue as reported by our CI.

**Comment by iMichka** [comment]
Let's try to debug this here : #126565

**Pull request merged**
