### PR TITLE
node 15.8.0

### PR DESCRIPTION
**Pull request by xandris**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by dawidd6** [comment]
Please upgrade the `npm` resource too.

**Comment by xandris** [comment]
totally flubbed this, sorry

**Comment by SMillerDev** [comment]
Is that the npm packaged with this node release?

**Comment by carlocab** [comment]
It's in their changelog, so I hope so

https://github.com/nodejs/node/releases/tag/v15.8.0

**Comment by xandris** [comment]
Yeah I updated to 7.5 because they mentioned it in the changelog

**Comment by carlocab** [comment]
ARM failures:
```
Error: 3 failed steps!
brew test --retry --verbose emscripten
brew test --retry --verbose netlify-cli
brew test --retry --verbose tree-sitter
```
`emscripten` and `tree-sitter` are documented in #66450. (`tree-sitter` almost certainly fails because `emscripten` is broken.)

`netlify-cli` has missed two version bumps because of an ARM failure: #70234, #70079, #69982

**Comment by carlocab** [comment]
`netlify-cli` fails with [the same error](https://github.com/Homebrew/homebrew-core/pull/70295/checks?check_run_id=1821863683#step:7:52) even without this version bump.

**Review by carlocab — APPROVED** [review]
Thanks, @xandris!

**Comment by carlocab** [comment]
Upstream issue for `netlify-cli`: https://github.com/netlify/cli/issues/1800

**Pull request closed without merging**
