### PR TITLE
latino 1.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Previous attempt #75202

**Comment by nandahkrishna** [comment]
Seems like the action re-creates closed PRs? Happened for `snap` too (#75747).

**Comment by chenrui333** [comment]
> Previous attempt #75202

This is more of the branch deletion which happened in the other PR as well.
image

**Comment by chenrui333** [comment]
I am gonna stop deleting the branches when closing the PRs.

**Pull request closed without merging**
