### PR TITLE
Irrlicht 1.8.3

### PR DESCRIPTION
**Pull request by neoascetic**
See also [this attempt](https://github.com/Homebrew/legacy-homebrew/pull/44699).
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by ilovezfs** [comment]
Build failure caused by upstream not having adapted to Xcode 7 yet
```
==> xcodebuild -project source/Irrlicht/MacOSX/MacOSX.xcodeproj -configuration Release -target libIrrlicht.a SYMROOT=build -sdk macosx10.10
xcodebuild: error: SDK "macosx10.10" cannot be located.
```

**Comment by apjanke** [comment]
Simply removing [the `"-sdk", "macosx#{MacOS.version}"`](https://github.com/Homebrew/homebrew-core/blob/a6e9721dc7655dd5b5ae8bff3ef701954a1b5660/Formula/irrlicht.rb#L38) still compiles for me on 10.9 and 10.11. Might be enough to clear it up. (I don't have a 10.10 box to test it on.)

There are also some `audit --strict` failures you might want to clean up while in here.

```
==> audit problems
irrlicht:
 * `bottle block` (line 31) should be put before `head block` (line 7)
 * `url` should be put inside `stable block`
 * `checksum` should be put inside `stable block`
 * A `test do` test block should be added
```

**Comment by ilovezfs** [comment]
@apjanke I think we need to do this
```
diff --git a/Formula/irrlicht.rb b/Formula/irrlicht.rb
index 899c975..cd579e9 100644
--- a/Formula/irrlicht.rb
+++ b/Formula/irrlicht.rb
@@ -4,30 +4,6 @@ class Irrlicht < Formula
   url "https://downloads.sourceforge.net/irrlicht/irrlicht-1.8.3.zip"
   sha256 "9e7be44277bf2004d73580a8585e7bd3c9ce9a3c801691e4f4aed030ac68931c"
 
-  head do
-    url "https://irrlicht.svn.sourceforge.net/svnroot/irrlicht/trunk"
-
-    # may be removed when https://sourceforge.net/p/irrlicht/patches/297/ will
-    # be applied
-    if MacOS.version == :yosemite
-      patch do
-        url "https://raw.githubusercontent.com/Homebrew/patches/da81091065df021758e02b9e07e36eaba20c4ec3/irrlicht/yosemite-head.patch"
-        sha256 "32e4a964a50325489ec1598bd6ca3e24f4c773bca74cc59f585fb2703d7e6d46"
-      end
-    end
-  end
-
-  # may be removed when https://sourceforge.net/p/irrlicht/patches/297/ will
-  # be applied
-  stable do
-    if MacOS.version == :yosemite
-      patch do
-        url "https://raw.githubusercontent.com/Homebrew/patches/da81091065df021758e02b9e07e36eaba20c4ec3/irrlicht/yosemite.patch"
-        sha256 "2dca39defb1044acaa87f6c8975283ce153c3f5e0ee0971565e490da8c12a496"
-      end
-    end
-  end
-
   bottle do
     cellar :any
     revision 1
@@ -42,9 +18,12 @@ class Irrlicht < Formula
     xcodebuild "-project", "source/Irrlicht/MacOSX/MacOSX.xcodeproj",
                "-configuration", "Release",
                "-target", "libIrrlicht.a",
-               "SYMROOT=build",
-               "-sdk", "macosx#{MacOS.version}"
+               "SYMROOT=build"
     lib.install "source/Irrlicht/MacOSX/build/Release/libIrrlicht.a"
     include.install "include" => "irrlicht"
   end
+
+  test do
+    assert_match "x86_64", shell_output("lipo -info #{lib}/libIrrlicht.a")
+  end
 end

```

**Comment by ilovezfs** [comment]
The Yosemite patch now causes build failure, and it builds without the patch, so maybe Apple fixed an SDK bug or something? It also builds without the patch on the 10.11 test bot.

HEAD does indeed build as well, but would need more customization in the install method in order to work if we felt head was still a desirable option.

**Comment by apjanke** [comment]
> @apjanke I think we need to do this

Looks like it to me too. Want to just make that a PR to supersede this one?

**Comment by neoascetic** [comment]
I may update the PR if you wish

**Comment by apjanke** [comment]
Yes please!

**Comment by apjanke** [comment]
Closed by ef7479fd7c5ba577badd1e1bcc6fe9b621de4635

**Pull request closed without merging**
