### PR TITLE
gst-plugins-good: Make orc dependency recommended

### PR DESCRIPTION
**Pull request by aleb**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
### Description

"Not a hard requirement, but highly recommended.
Packagers, please hard-depend on liborc."
https://cgit.freedesktop.org/gstreamer/gst-plugins-good/tree/REQUIREMENTS

### CODE REVIEW

**Comment by DomT4** [comment]
Should probably bump the `revision` of the formula if we're changing a dependency to recommended or mandatory.

**Comment by aleb** [comment]
Where is `revision`?

**Comment by DomT4** [comment]
You'll need to add it, in this case. Underneath the `homepage` line add `revision 1`.

**Comment by aleb** [comment]
I see sometimes it appears in `bottle do` .. anyway, added it under `homepage`.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
