### PR TITLE
bear 3.0.7

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

Previous attempts:
- 3.0.4 https://github.com/Homebrew/homebrew-core/pull/67303
- 3.0.3 https://github.com/Homebrew/homebrew-core/pull/66099
- 3.0.0 https://github.com/Homebrew/homebrew-core/pull/61977

### CODE REVIEW

**Comment by carlocab** [comment]
Try adding `depends_on "pkg-config" => :build`?

**Comment by SeekingMeaning** [comment]
This might require https://github.com/Homebrew/homebrew-core/pull/69125

`abseil` version 20200923 (https://github.com/Homebrew/homebrew-core/pull/61866) broke `grpc` (https://github.com/rizsotto/Bear/issues/344#issuecomment-749894886) which was fixed in https://github.com/grpc/grpc/commit/e95f3fb98c20210f60a8f7550ac6420ef8eaca1c but the Homebrew `grpc` formula has not been updated to a version that includes the fix

**Comment by carlocab** [comment]
Boo. #69125 is waiting for an `apache-arrow` release... I _think_ one is coming soon, but who knows

**Comment by carlocab** [comment]
Actually, maybe `apache-arrow` isn't getting updated soon. I just noticed that it was recently retagged on GitHub, and who knows how often that'll happen before they cut an official release.

**Comment by carlocab** [comment]
Waiting for apache-arrow might not make too much sense. Trying a different approach at #69125.

**Comment by carlocab** [comment]
#69125 Should be ready to merge soon.

**Comment by SeekingMeaning** [comment]
`error: 'path' is unavailable: introduced in macOS 10.15`

Possible fix: https://stackoverflow.com/a/59002869

**Comment by carlocab** [comment]
So, `-DCMAKE_CXX_STANDARD=17`?

**Comment by SeekingMeaning** [comment]
I’m not familiar with that flag but that sounds about right

**Comment by carlocab** [comment]
Yep, I think it should do it: https://cmake.org/cmake/help/v3.19/variable/CMAKE_CXX_STANDARD.html

**Comment by SeekingMeaning** [comment]
I think `grpc` needs to be added as a runtime dependency, but first let's wait to see how 10.14 turns out

**Comment by carlocab** [comment]
The build docs say it fetches its own dependencies though (which is bad, actually):

https://github.com/rizsotto/Bear/blob/master/INSTALL.md#dependencies

They also say they need llvm on Mojave:

https://github.com/rizsotto/Bear/blob/master/INSTALL.md#platform-macos

**Comment by carlocab** [comment]
>Install dependencies from packages from Brew
>```
> brew install fmt spdlog nlohmann-json sqlite grpc pkg-config
>```

**Comment by SeekingMeaning** [comment]
> They also say they need llvm on Mojave:
> 
> https://github.com/rizsotto/Bear/blob/master/INSTALL.md#platform-macos

We could maybe do `uses_from_macos "llvm", since: :catalina`

**Comment by carlocab** [comment]
`git` is taking ages for some reason

**Comment by SeekingMeaning** [comment]
> `git` is taking ages for some reason

Weird, this seems to happen around this time quite regularly

**Comment by carlocab** [comment]
Build still failed on Mojave 😞 

However, it did build on ARM, but the test failed.

**Comment by SeekingMeaning** [comment]
I think we have to explicitly set the compiler to Homebrew's LLVM; there should be at least one formula that does this

**Comment by carlocab** [comment]
You mean like in https://github.com/Homebrew/homebrew-core/commit/6aeb9db1df3d716d64c3724861706b26320ecfca#diff-6028ba6d481d9d187e797174157d7bcd8bf228c6fddd88199ec3f6886f5bc5a8 ?

Though, I'm confused, the build docs say they only need LLVM libraries

**Comment by SeekingMeaning** [comment]
> You mean like in [6aeb9db#diff-6028ba6d481d9d187e797174157d7bcd8bf228c6fddd88199ec3f6886f5bc5a8](https://github.com/Homebrew/homebrew-core/commit/6aeb9db1df3d716d64c3724861706b26320ecfca#diff-6028ba6d481d9d187e797174157d7bcd8bf228c6fddd88199ec3f6886f5bc5a8) ?

Yeah

> Though, I'm confused, the build docs say they only need LLVM libraries

We might be able to get away with adding the `llvm` formula prefix to `PATH`

**Comment by carlocab** [comment]
Cool, will do that after I have a look at the bottle when Big Sur finishes running.

Yay for https://github.com/Homebrew/homebrew-test-bot/pull/561

**Comment by carlocab** [comment]
Wait, I noticed the failed bottles are in a link identical to successful bottles. I think we're not supposed to do that? Because I think `pr-publish` will pick up failed bottles this way...

**Comment by carlocab** [comment]
Test should be good now. Went with the slightly more verbose way of determining the compiler on Mojave. I thought it would be more transparent about what's going on.

**Comment by SeekingMeaning** [comment]
https://github.com/rizsotto/Bear/blob/3.0.7/CMakeLists.txt#L13

```
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_EXECUTABLE
```

**Comment by carlocab** [comment]
It actually did use LLVM Clang in the last run on Mojave... But it still failed 😞

https://github.com/Homebrew/homebrew-core/runs/1775393159?check_suite_focus=true

**Comment by SeekingMeaning** [comment]
Oh...

**Comment by carlocab** [comment]
So I had a look at some of the issues upstream:

https://github.com/rizsotto/Bear/issues/232
https://github.com/rizsotto/Bear/issues/215

It looks like the developer just isn't able to provide a proper fix for this. I think the only thing to do here is making this depend on a new enough version of macOS.

**Review by carlocab — APPROVED** [review]

**Comment by rizsotto** [comment]
@SeekingMeaning @carlocab Thanks for doing this!

Can I ask what is the solution for the `ld: library not found for -labsl_dynamic_annotations` error? The CI for the upstream is still failing with that. Can I ask for a look at it?

https://github.com/rizsotto/Bear/runs/1782750797?check_suite_focus=true <- is the latest run

https://github.com/rizsotto/Bear/blob/master/.github/workflows/build_on_push.yml <- is the CI job control file

**Comment by carlocab** [comment]
@rizsotto I'm not sure, tbh, as we didn't encounter that error. I just followed your build instructions at https://github.com/rizsotto/Bear/blob/master/INSTALL.md#build-commands.

I notice however that you ask CMake to build the `install` target right away in your second invocation of CMake. The linker also complains about a missing library, so I suspect you have a parallelization issue. Try calling `cmake --build "$BUILD_DIR" --target all` just before `cmake --build "$BUILD_DIR" --target install`.

**Comment by carlocab** [comment]
As an aside, do you still have reports of problems on macOS 10.14? We were unable to get it to build there, even if we used LLVM Clang 11 instead of the system-bundled Clang.

**Comment by rizsotto** [comment]
@carlocab thanks for the quick reply. Will try the non parallel build with the `all` target before the `install`.

I think the CI build is `10.15.7`. So, `10.14` problem does not hurt me now. (No bug report so far.)

My other question would be, what this line is doing? `rewrite_shebang detected_python_shebang, bin/"bear"`

**Comment by carlocab** [comment]
Now? Probably nothing, tbh. Before, it was probably used to remove references to a non-Homebrew Python.

**Comment by rizsotto** [comment]
Thanks @carlocab , I thought this is some leftover from previous Python based version. I would say the dependency on Python is no longer required, unless you run the integration tests.

And FYI, the CI build recovered today, without changing anything on it. I'm pleased. And hope it'll stay as is. :)

**Comment by carlocab** [comment]
Interesting; we don't run the integration tests. However, `brew` does detect a runtime dependency on Python, so `bear` may be picking up linkage just by having it available in the build environment.

**Pull request closed without merging**
