### PR TITLE
shellz 1.4.0 (new formula)

### PR DESCRIPTION
**Pull request by djerfy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
@djerfy Can you update this to `1.4.0` please?

**Comment by djerfy** [comment]
@commitay Yes of course, it's done! I wanted to do it but I was waiting for the merge request to be done

**Comment by djerfy** [comment]
Branch name is `shellz-1.3.0` but it's `shellz-1.4.0`

**Comment by commitay** [comment]
Thanks @djerfy!

**Pull request closed without merging**
