### PR TITLE
mesa: revision bump (remove libelf linkage)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

See #84364.

### CODE REVIEW

**Comment by carlocab** [comment]
Let's just do `dispatch-rebottle` to avoid having a no-op rev bump on macOS. https://github.com/Homebrew/homebrew-core/actions/runs/1194385257

**Comment by carlocab** [comment]
`dispatch-rebottle` isn’t working for some reason.

**Review by cho-m — APPROVED** [review]
Can either go ahead with this, or try a minor modification w/o revision to upload rebuild. Skipping automerge to give time for other ideas.

**Comment by carlocab** [comment]
Doesn't seem like there's much else we can do here, so let's merge this.

**Pull request closed without merging**
