### PR TITLE
rust 1.44.1

### PR DESCRIPTION
**Pull request by optikfluffel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
wapm test failure is due to the cert expiration (https://github.com/wasmerio/wapm-cli/issues/194)

**Comment by chenrui333** [comment]
mgba 0.8.2 release failed to build as well (https://github.com/Homebrew/homebrew-core/pull/56319)

**Review by chenrui333 — COMMENTED** [review]
lgtm, also this is a patch version upgrade.

**Comment by alebcay** [comment]
Cancelled CI run on Catalina (failed in 20-22 hours on Mojave/High Sierra; still stuck running on Catalina after 35 hours).

**Comment by chenrui333** [comment]
rebased to the latest master and have another run 🤞

**Comment by optikfluffel** [comment]
Another rebase 🙃🤞

**Comment by chenrui333** [comment]
> Another rebase 🙃🤞

Full transparency here, I was trying to merge the PR but run into the artifact download issue, if we run into the merge issue again, I might think to re-raise a separate PR.

```
==> Downloading https://api.github.com/repos/Homebrew/homebrew-core/actions/artifacts/9524979/zip
    #  #   #   #                 -=O=-
ditto: logs/caffe/test.01.caffe: No such file or directory
ditto: Couldn't read pkzip signature.
Error: Failure while executing; `ditto -x -k /Users/ruichen/Library/Caches/Homebrew/downloads/74a79165535a1e5fbda56694f1c01043c3979a141b1e0e2a23c4eed3c47eb0b7--artifact.zip /var/folders/cb/s5w4_0p50639mbdvqhnmf7wm0000gn/T/d20200625-5601-y4dhgw` exited with 1. Here's the output:
ditto: logs/caffe/test.01.caffe: No such file or directory
ditto: Couldn't read pkzip signature.
```

**Comment by chenrui333** [comment]
we have gcc, openjdk formula upgrade going on, and we only have three machines (cancelled the builds, and let those two thru first). today we are going to focus on merging openjdk14

**Comment by optikfluffel** [comment]
I never thought it would be so "difficult" to merge a patch update. Good luck with gcc and openjdk 😄

**Comment by chenrui333** [comment]
> I never thought it would be so "difficult" to merge a patch update. Good luck with gcc and openjdk 😄

We will get back to this once those two big PRs got sorted out. (there is another improvement for cargo manpages and auto-completions) :)

Thanks for the PR though.

**Pull request closed without merging**
