### PR TITLE
heroku 6.12.3

### PR DESCRIPTION
**Pull request by jdx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@dickeyxxx thanks! By the way, you want to start using 8 digit hashes for these, instead of 7, since that is the length Git chooses for your repo size now.

https://github.com/heroku/cli/commit/fca882c43e2570f79614bbb5fcb863bb2a5f69a9.patch

Note `index d046afba..103e0400 100644`

**Comment by dickeyxxx** [comment]
that might be github doing that, we run `https://github.com/heroku/cli-engine/blob/master/bin/version#L2` so we're not specifying the length.

BTW we're still discussing the updating stuff, hope to reach out soon with that but I've got a few things going on at the moment.

**Comment by dickeyxxx** [comment]
that might be github doing that, we run `https://github.com/heroku/cli-engine/blob/master/bin/version#L2` so we're not specifying the length.

BTW we're still discussing the build stuff, hope to reach out soon with that but I've got a few things going on at the moment.

**Comment by ilovezfs** [comment]
>BTW we're still discussing the updating stuff, hope to reach out soon with that but I've got a few things going on at the moment.

Excellent!

>that might be github doing that

It's actually just caused by Git >= 2.11.0 which uses a dynamic length instead of 7 for the short hashes.

See https://github.com/blog/2288-git-2-11-has-been-released

(We had some issues related to this recently https://github.com/Homebrew/homebrew-core/pull/13792)

Luckily there's a new GitHub feature (`?full_index=1` equivalent to Git's `--full-index`) that let's you get the full index instead now so that it's not variable length, e.g.

https://github.com/heroku/cli/commit/fca882c43e2570f79614bbb5fcb863bb2a5f69a9.patch?full_index=1

**Comment by ilovezfs** [comment]
```
bash-4.4$ cd $(brew --repo homebrew/core)
bash-4.4$ git rev-parse --short HEAD
41e6a4bbcc
bash-4.4$
```
(So Homebrew Core ttps://github.com/Homebrew/homebrew-core.git has a variable short hash length of 10.

So I think https://github.com/heroku/cli-engine/blob/master/bin/version#L2 is correct but you must be using an older Git in your backend that still hard codes length 7 instead of the dynamic length.

**Comment by dickeyxxx** [comment]
hrm. I'm on git 2.13.2 and it's sending 7 digit hashes. The point may be moot though (see my next PR)

**Comment by ilovezfs** [comment]
Yeah, locally I get 7 for your repo
```
Josephs-MacBook-Pro:cli-engine joe$ git rev-parse --short HEAD
ccb0289
```
The backend GitHub repo for your repository must be a bit larger than the user-facing one. Interesting.

**Comment by ilovezfs** [comment]
Thanks for the upgrade! Merged!

**Pull request merged**
