### PR TITLE
qt 5.12.1, head to use dev branch

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
HS and Mojave logs looks fine, at least I can't find errors. Sierra seems to have some issue in third-party deps. Maybe we should just set min macOS ver to HS?

**Comment by scpeters** [comment]
The post-install step of `shared-mime-info` failed on mojave and sierra; I'm not sure why.

~~~
==> Pouring shared-mime-info-1.10.mojave.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall shared-mime-info`
==> Summary
/usr/local/Cellar/shared-mime-info/1.10: 83 files, 4.6MB
~~~

**Comment by scpeters** [comment]
the high sierra build fails due to 3rd party source code

~~~
ERROR at //third_party/skia/gn/core.gni:1:1: Invalid token.
^
I have no idea what this is.
See //skia/BUILD.gn:11:1: whence it was imported.
import("//third_party/skia/gn/shared_sources.gni")
^------------------------------------------------
See //BUILD.gn:71:5: which caused the file to be included.
    "//skia:skia_unittests",
    ^----------------------
Project ERROR: GN run error!
make[3]: *** [sub-gn_run-pro-make_first] Error 3
make[2]: *** [sub-core-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtwebengine-make_first] Error 2
~~~

**Comment by ZeldaZach** [comment]
Thanks for jumping on this. Not surprised Qt is having third party lib issues

**Comment by albertosottile** [comment]
I was trying to prepare a bug report for the Qt people, but I just managed to build this locally while in `brew` on 10.13.6. Is it possible to run the tests again to get a detailed log of the errors?

**Comment by yurikoles** [comment]
@BrewTestBot test this again, please

**Comment by albertosottile** [comment]
Everything seems fine indeed, I have no idea of what happened the first time. Now we probably need a maintainer to step up.

**Comment by scpeters** [comment]
not sure why it failed the first time, but it seems to have built correctly this time

**Comment by yurikoles** [comment]
@fxcoudert could you merge this?

**Comment by fxcoudert** [comment]
Thanks @yurikoles for the pull request!

**Pull request closed without merging**
