### PR TITLE
Support `brew services` for NSQ

### PR DESCRIPTION
**Pull request by plainprogrammer**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Added necessary post-install and `plist` definition to facilitate running NSQ with `brew services`.

### CODE REVIEW

**Comment by dunn** [comment]
Thanks! Could you also add `revision 1` below line 6, so that this update gets pushed out to everyone?

**Comment by plainprogrammer** [comment]
@dunn done!

**Comment by dunn** [comment]
Oh, could you also squash it into a single commit? Thanks!

**Review by JCount — APPROVED** [review]

**Comment by JCount** [comment]
@plainprogrammer Thank you for your first contribution to Homebrew! 🎊  Please, feel free to contribute more! 😄

**Pull request closed without merging**
