### PR TITLE
Update mksh.rb: The URL needs to be updated to download the tgz file

### PR DESCRIPTION
**Pull request by docfate111**
- [ X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by docfate111** [comment]
Just a small change.
For some reason the the url for downloading mksh has changed.

**Comment by SMillerDev** [comment]
That makes it the same as the mirror. I don't think this is the correct fix. I think upstream should be notified that this is broken

**Comment by docfate111** [comment]
Sorry I changed the url. It is different now.

**Comment by fxcoudert** [comment]
You're moving back to an older version, which is not good. We can find another mirror, more up to date, like `http://mirror.fsf.org/dragora/v3/sources/mksh-R59b.tgz`

**Comment by docfate111** [comment]
Okay. Sounds good.

**Pull request closed without merging**
