### PR TITLE
opencascade 7.3.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Same error on `sierra`, `high_sierra` and `mojave`:
```
cp -p /Users/brew/Library/Caches/Homebrew/downloads/063d729bcdb46efea80d5500728b45778e6a396b11715e8b46067ee0c5fa4410--p=occt.git;a=snapshot;h=refs /private/tmp/opencascade-20181015-883-1htejer/p=occt.git;a=snapshot;h=refs
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ dir_chdir - occt-V7_3_0
```

**Comment by fxcoudert** [comment]
That URL is not recognised as a `.tgz` file anymore. @reitermarkus any suggestion?

**Comment by fxcoudert** [comment]
Blocked by #5143

**Comment by fxcoudert** [comment]
Hopefully this will now work

**Comment by luzpaz** [comment]
Is this formula working ?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
