### PR TITLE
pixie 0.8.3

### PR DESCRIPTION
**Pull request by ddelnano**
Modeled this off the #183657, which was made with `brew bump-formula-pr`. I ran into the 'duplicate PR' issue since I tried to delete it and re-create it with `brew bump-formula-pr`

### CODE REVIEW

**Comment by ddelnano** [comment]
@chenrui333 sorry for the trouble with the v0.8.3 release. This PR should be ready from a pixie release perspective now.

**Comment by stefanb** [comment]
Ugh, does this mean that the 0.8.3 tag was moved?

**Comment by ddelnano** [comment]
Hey @stefanb, unfortunately yes. I understand that is generally a bad practice and apologize if this causes a complication here.

**Review by stefanb — APPROVED** [review]

**Comment by stefanb** [comment]
No worries, just wanted to clarify.

It isn't causing us problems in this case, but it could do so in other cases, eg when there is a new release of Go and it tries to build all formulae as a test, running into mismatched hashes because of moved tags...

Also your brew bump attempt would likely realize it isn't really _exactly_ the same version and would create the PR 😉

**Pull request merged**
