### PR TITLE
openjdk: test build

### PR DESCRIPTION
**Pull request by Bo98**
test opt build

### CODE REVIEW

**Comment by fxcoudert** [comment]
Really great work on the `vim` thread and here! 🙇

**Comment by Bo98** [comment]
Thank you!

**Comment by fxcoudert** [comment]
I think this is ready for review…

**Comment by fxcoudert** [comment]
I've added that to the update PR, if it goes fine, we can merge it; if it takes longer to resolve, we'll merge here :)

**Comment by cho-m** [comment]
Closing as merged in #194557

**Pull request closed without merging**
