### PR TITLE
infer: deprecate

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by jvillard** [comment]
@Bo98 great info, thanks! Is there a release of llvm that includes these commits already? We're on 12.0.1 but can upgrade if so, else we can apply these commits locally.

**Comment by carlocab** [comment]
> * [llvm/llvm-project@9cd2413](https://github.com/llvm/llvm-project/commit/9cd2413f1ca7a7f40132ea3c44f251851aa325c2)

Should be in LLVM 12.

> * [llvm/llvm-project@2de0a18](https://github.com/llvm/llvm-project/commit/2de0a18a8949f0235fb3a08dcc55ff3aa7d969e7)

This needs LLVM 13.

**Comment by iMichka** [comment]
@jvillard I tried to apply a few patches from infer to get this to build, but these patches need even more patches else they don't apply, as the code touches multiples files which have all been modified over multiple commits. So it will be hard to extract just the necessary changes (or we need to write our own patch-set from scratch).

Do you know when the next infer release is planned?

**Comment by iMichka** [comment]
I've asked upstream to tag a new release: https://github.com/facebook/infer/issues/1568

**Comment by iMichka** [comment]
I updated the PR with a deprecation notice starting as of today. This PR has been open for way too long. This leave upstream 1 year to make a proper release and bring CI green again.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
