### PR TITLE
elasticsearch 7.8.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chrmoritz** [comment]
I think this this is still blocked by `openjdk` 14: #51883.

**Comment by SMillerDev** [comment]
Does it require openjdk 14?

**Comment by chrmoritz** [comment]
Yeah, `elasticsearch` 7.7.0+ requrres `openjdk` 14, see #55419. Should have added a comment though.

**Comment by ankane** [comment]
Hey @SMillerDev, it looks like that cryptic error message is due to the data and logs directories not being created ahead of time. Also, it should be able to use `gradle` from Homebrew now. I was able to get tests passing with these changes:

https://github.com/Homebrew/homebrew-core/compare/master...ankane:elasticsearch-7.8.0

**Comment by ankane** [comment]
Also, it may make sense to remove the minor version from aliases (change to `elasticsearch@6`, `elasticsearch@7`).

**Comment by SMillerDev** [comment]
Agreed, could you make a PR and I'll close this.

**Comment by ankane** [comment]
Created a PR for the 7.8 upgrade. I think it'll be easier to remove the minor versions in a separate PR (for Elasticsearch and Kibana), but we can do it all together if that's better.

**Pull request closed without merging**
