### PR TITLE
auditbeat 6.2.0

### PR DESCRIPTION
**Pull request by tylerjl**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Error: inreplace failed
auditbeat.yml:
  expected replacement of /^- module: audit\n^  metricsets: \[kernel\]\n^  kernel.audit_rules: \|/ with "#- module: audit\n#  metricsets: [kernel]\n#  kernel.audit_rules: |"
```

**Comment by ilovezfs** [comment]
Is there an upstream issue for that `inreplace`? It would be best not to have to carry that around in the formula $forever.

**Comment by tylerjl** [comment]
@ilovezfs the find and replace is there to disable auditbeat's hooks into Linux kernel-specific `audit` APIs, otherwise it'd fail when initializing those modules - it leaves behind other default configurations that work on OS X such as file integrity monitors, etc. It isn't the prettiest but the configs assume Linux by default, so this helps OS X work with least surprise.

**Comment by ilovezfs** [comment]
@tylerjl a separate file for macOS would be nice, even if we have to `mv` it over the Linux one.

**Comment by ilovezfs** [comment]
```
==> brew test auditbeat --verbose
==> FAILED
Testing auditbeat
/usr/bin/sandbox-exec -f /tmp/homebrew20180206-63659-15xsfgz.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/auditbeat.rb --verbose
Exiting: 1 error: 1 error: metricset 'audit/file' is not registered, module not found
Error: auditbeat: failed
No such file or directory @ rb_sysopen - /tmp/auditbeat-test-20180206-63660-vqgj0a/auditbeat/auditbeat
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/auditbeat.rb:102:in `readlines'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/auditbeat.rb:102:in `block in <class:Auditbeat>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1636:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:551:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1635:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:835:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1634:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1628:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by tylerjl** [comment]
@ilovezfs dug a little further and found a supported way to generate darwin-specific configs, so these latest changes ^ should be compatible with OS X out of the box and forward compatible with any future Linux-specific features that may get added to the reference config.

**Comment by ilovezfs** [comment]
nice find!

**Comment by fxcoudert** [comment]
Thanks @tylerjl for the pull request!

**Pull request closed without merging**
