### PR TITLE
Boost 1.74.0

### PR DESCRIPTION
**Pull request by HLXEasy**
The reason for this PR is https://github.com/boostorg/process/issues/92, which should be fixed on Boost 1.74.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?

Unfortunately I can't built myself as my XCode version is too old. I have only one Mac at my hands and can't update the machine for other reasons, so it would be cool if somebody else could check this.

- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?

See previous comment.

- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

See previous comment.

-----

### CODE REVIEW

**Comment by HLXEasy** [comment]
Tests failed with
`==> FAILED
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining`

Is this my fault?

**Comment by jonchang** [comment]
Nah, it's a transient github issue. You'll need to remove this patch though:

https://github.com/Homebrew/homebrew-core/pull/62549/files#diff-5148b5dd1fa3716ad2777ce49eaf03a9L28-L33

**Comment by HLXEasy** [comment]
@jonchang Thx for your response. Which patch do you refer to? If I click on your link, I see just my changes!?

**Comment by bayandin** [comment]
> @jonchang Thx for your response. Which patch do you refer to? If I click on your link, I see just my changes!?

This one https://github.com/Homebrew/homebrew-core/blob/2b88bd8e6b64d5fac0966bdde346c48e1e2b6d5c/Formula/boost.rb#L28-L33

It has been merged

**Comment by HLXEasy** [comment]
Ah ok, thx. Will update the PR asap.

**Comment by fxcoudert** [comment]
- Adding other boost-related formulas
- Squashing the patch removal in the same commit
- Revision bumping dependents

**Comment by fxcoudert** [comment]
```
brew test --retry --verbose freeling
brew test --retry --verbose i2pd
brew test --retry --verbose pcl
brew test --verbose libbitcoin-protocol
brew test --verbose libbitcoin-client
brew test --verbose libbitcoin-explorer
brew test --verbose libbitcoin-server
brew install --verbose --build-bottle wownero
```

- Revision bumps needed for `freeling`, `i2pd`, and `libbitcoin`.
- `pcl` is failing to build, but I think it was fixed
- `wownero` conflicts with `monero`

**Comment by fxcoudert** [comment]
`freeling` does not build due to change in checksum: https://github.com/TALP-UPC/FreeLing/issues/111

**Comment by fxcoudert** [comment]
And now it's a freeling build failure: https://github.com/TALP-UPC/FreeLing/issues/112

**Comment by fxcoudert** [comment]
`boost` has 40,915 monthly installs, freeling has 8. I'd say we merge this in, and open a separate PR for the freeling revision bump. @Homebrew/core what say you?

**Review by jonchang — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Thanks @HLXEasy and @fxcoudert

**Comment by fxcoudert** [comment]
I'll try to merge this one before: https://github.com/Homebrew/homebrew-core/pull/62560

**Comment by HLXEasy** [comment]
> Thanks @HLXEasy and @fxcoudert

You're welcome, even if it was way more than I thought initially. So all the fame is dedicated to @fxcoudert

**Comment by SMillerDev** [comment]
FX is plenty famous already, he can share.

**Comment by jonchang** [comment]
Looks like a different revision bump made it in prior to this being merged:

```
[master 203288a8d9] source-highlight: revision for boost
 Author: Francois-Xavier Coudert <fxcoudert@gmail.com>
 Date: Sat Oct 10 12:11:21 2020 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
Auto-merging Formula/widelands.rb
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
```

This will need to be rebased and its revision bumps checked.

**Comment by fxcoudert** [comment]
- `widelands` needs a revision bump
- given that `freeling` is not building anymore, probably do not revision bump

**Pull request closed without merging**
