### PR TITLE
[wip] charm-tools 2.5.2

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
08:35:11     /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
08:35:11         PyObject *curexc_traceback;
08:35:11                   ^
08:35:11     15 errors generated.
08:35:11     error: command 'clang' failed with exit status 1
08:35:11   Running setup.py install for PyYAML: finished with status 'error'
08:35:11 Cleaning up...
08:35:11   Removing source in /private/tmp/pip-req-build-08sxavkk
08:35:11 Removed build tracker '/private/tmp/pip-req-tracker-13xvlx3b'
08:35:11 ERROR: Command "/usr/local/Cellar/charm-tools/2.5.1/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-08sxavkk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-ismppbdl/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/charm-tools/2.5.1/libexec/bin/../include/site/python3.7/PyYAML" failed with error code 1 in /private/tmp/pip-req-build-08sxavkk/
```

**Comment by chenrui333** [comment]
`Running setup.py install for PyYAML: finished with status 'error'`

**Comment by Moisan** [comment]
I tried to `pip install charm-tools` on Python 3 but its dependencies fail to install. This will be probably be hard to make it work here also. This is due to `ruamel.yaml<=0.10.23` in this version. 

The pypi version is not up to date with the [releases on Github](https://github.com/juju/charm-tools/releases), and there is an [issue upstream about this](https://github.com/juju/charm-tools/issues/414).

I think the best course of action would be to use the Github release `1.5.2` instead.

**Comment by chenrui333** [comment]
Cool, I can certainly try with a new PR to use 2.5.2. Yeah, I found out the pypi is not up to date.

**Comment by chenrui333** [comment]
```
20:47:02 pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/charm-tools/2.5.2/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-uri6qyn3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-1xgqvv67/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/charm-tools/2.5.2/libexec/bin/../include/site/python3.7/PyYAML" failed with error code 1 in /private/tmp/pip-req-build-uri6qyn3/
20:47:02 
20:47:02 ==> Formula
20:47:02 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/charm-tools.rb
```

**Comment by chenrui333** [comment]
20:47:02 ERROR: Command "/usr/local/Cellar/charm-tools/2.5.2/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-uri6qyn3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-1xgqvv67/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/charm-tools/2.5.2/libexec/bin/../include/site/python3.7/PyYAML" failed with error code 1 in /private/tmp/pip-req-build-uri6qyn3/

**Comment by chenrui333** [comment]
Maybe that is reason why they did not support py3.7 yet. I will switch to use py2

**Comment by Moisan** [comment]
I think we should stick with Python3 and update all the resources.

**Comment by chenrui333** [comment]
upstream repo only support py3.5 yet, maybe we should test in the upstream repo first with py3.7 support?

**Comment by SMillerDev** [comment]
I'd prefer to use python 3 too.

**Comment by chenrui333** [comment]
ok, I will try with python 3.7 then.

**Pull request closed without merging**
