### PR TITLE
wazero 1.2.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — COMMENTED** [review]
Not yet the latest (see https://github.com/tetratelabs/wazero/releases).

**Comment by SMillerDev** [comment]
Should it use the github strategy then?

**Comment by nandahkrishna** [comment]
> Should it use the github strategy then?

Might be worth confirming with upstream if we should wait for a GitHub release or just a tag is considered a release.

**Comment by codefromthecrypt** [comment]
Hi, I can say for sure any tag is a release. We click the button only after formalizing the release notes, which takes a while as we make [elaborate ones](https://github.com/tetratelabs/wazero/releases). Yesterday was a special case where I didn't finish them the same day as the release. Usually, this isn't an issue.

Sorry about the confusion!

**Review by p-linnane — APPROVED** [review]
Thank you for weighing in @codefromthecrypt. We appreciate it!

**Pull request merged**
