### PR TITLE
dnspython 2.6.1 (new Formula)

### PR DESCRIPTION
**Pull request by obnoxxx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — CHANGES_REQUESTED** [review]
need test

**Comment by branchvincent** [comment]
This is a pure python library right, there's no CLI? We don't typically accept libraries except in rare circumstances, see https://docs.brew.sh/Python-for-Formula-Authors#libraries. Do you think this meets those requirements?

**Comment by obnoxxx** [comment]
@branchvincent  wrote:
> This is a pure python library right, there's no CLI?

correct, it's a pure library without CLI. I was guided bt python-markdown.

We don't typically accept libraries except in rare circumstances, see https://docs.brew.sh/Python-for-Formula-Authors#libraries. Do you think this meets those requirements?


Thanks for the hint! still reading up on that doc

**Comment by SMillerDev** [comment]
> Do you think this meets those requirements?

What is special about this library that it's better to have Homebrew install the install than pip?

**Comment by obnoxxx** [comment]
@chenrui333  wrote:
> need test

Agreed. The test I originally addedwas a stub.

Now I tried to add a real test, but I am afraid it is not working quite correctly yet Need to debug further.

**Comment by obnoxxx** [comment]
@SMillerDev  wrote:
> > Do you think this meets those requirements?
> 
> What is special about this library that it's better to have Homebrew install the install than pip?

Before starting to work on this formula,  I tried to pip install directly, but it errored out:

```console
 $ pip3 install dnspython
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:


```

Because of this and in general, I think it is the cleanest solution to have python and all libs provided by homebrew.

**Comment by SMillerDev** [comment]
> Because of this and in general, I think it is the cleanest solution to have python and all libs provided by homebrew.

I disagree, pip should be used to install python components. Homebrew should be used to install things for the system. It seems you're not using a virtual environment, which can cause some issues, so Python 3.12 and later block you from doing that. But that's not really a reason to install something with Homebrew.

**Comment by obnoxxx** [comment]
@SMillerDev  wrote: 
> > Because of this and in general, I think it is the cleanest solution to have python and all libs provided by homebrew.
> 
> I disagree, pip should be used to install python components. Homebrew should be used to install things for the system.

Right. And I do consider python libraries part of my system installation. That's why I like to have them as part of homebrew.

It annoys me if I have to manually fiddle with library installs 


> It seems you're not using a virtual environment, which can cause some issues, so Python 3.12 and later block you from doing that.

right. I was trying to pip install without virtual env.

But I also tried with virtual env which worked without problems.

However, I consider this too much of a hassle to do every time I need some lib.

>  But that's not really a reason to install something with Homebrew.

Ok. That's a legitimate point of view. For me,avoiding the hassle does  justify
having libs in system packages.

I just like to have libs  as part of the stable and relatively static system install.

This applies not only to homebrew but also to Linux distros' system packages. 😄

**Comment by obnoxxx** [comment]
@SMillerDev  wrote:
> ...
>  But that's not really a reason to install something with Homebrew.

Given this comment, should I close this PR and abandon this effort?

**Comment by SMillerDev** [comment]
> Given this comment, should I close this PR and abandon this effort?

I don't think it's a good candidate for inclusion in Homebrew/core
Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by obnoxxx** [comment]
@SMillerDev  wrote:
> > Given this comment, should I close this PR and abandon this effort?
> 
> I don't think it's a good candidate for inclusion in Homebrew/core 

Given this assessment, I will close this PR.

Thanks for your review though!



Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

Thanks for the hint, I will check it out.

**Pull request closed without merging**
