### PR TITLE
librdkafka 0.9.5

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ilovezfs — COMMENTED** [review]
Wait for announcement later today https://github.com/edenhill/librdkafka/releases

**Comment by JCount** [comment]
@ilovezfs It's now marked as the latest release, so I am removing the `do not merge`, and merging it.

**Comment by JCount** [comment]
The sha256 hashes of all of the bintray bottles do not match the ones in the bottle block.

**Comment by JCount** [comment]
@ilovezfs Just saw the problem. Someone opened a dupe pull request https://github.com/Homebrew/homebrew-core/pull/12603 and that PR's bottle job overwrote the ones from this PR.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please.

**Pull request closed without merging**
