### PR TITLE
prometheus 2.6.0

### PR DESCRIPTION
**Pull request by kadaan**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
```
04:11:33 ==> make build
04:11:33 curl -s -L https://github.com/prometheus/promu/releases/download/v0.2.0/promu-0.2.0.darwin-amd64.tar.gz | tar -xvzf - -C /var/folders/kw/j7f63hdn1lj39702nh90xm9w0000gp/T/tmp.JEhNXd3y
04:11:33 x promu-0.2.0.darwin-amd64/
04:11:33 x promu-0.2.0.darwin-amd64/LICENSE
04:11:33 x promu-0.2.0.darwin-amd64/NOTICE
04:11:33 x promu-0.2.0.darwin-amd64/promu
04:11:33 mkdir -p /private/tmp/prometheus-20181219-81118-1by4968/prometheus-2.6.0/bin
04:11:33 cp /var/folders/kw/j7f63hdn1lj39702nh90xm9w0000gp/T/tmp.JEhNXd3y/promu-0.2.0.darwin-amd64/promu /private/tmp/prometheus-20181219-81118-1by4968/prometheus-2.6.0/bin/promu
04:11:33 rm -r /var/folders/kw/j7f63hdn1lj39702nh90xm9w0000gp/T/tmp.JEhNXd3y
04:11:33 >> building binaries
04:11:33 GO111MODULE=on /private/tmp/prometheus-20181219-81118-1by4968/prometheus-2.6.0/bin/promu build --prefix /private/tmp/prometheus-20181219-81118-1by4968/prometheus-2.6.0
04:11:33  >   prometheus
04:11:33 $GOPATH/go.mod exists but should not
04:11:33 !! command failed: build -o /private/tmp/prometheus-20181219-81118-1by4968/prometheus-2.6.0/prometheus -ldflags -X github.com/prometheus/common/version.Version=2.6.0 -X github.com/prometheus/common/version.Revision=non-git -X github.com/prometheus/common/version.Branch=non-git -X github.com/prometheus/common/version.BuildUser=brew@Mojave-2.local -X github.com/prometheus/common/version.BuildDate=20181219-04:11:30  -mod=vendor -a -tags netgo github.com/prometheus/prometheus/cmd/prometheus: exit status 1
04:11:33 make: *** [common-build] Error 1
```

**Comment by javian** [comment]
Thanks for the first submission @kadaan and welcome to the Homebrew community! Would it be possible for you to look into the build error by any chance ?

**Comment by kadaan** [comment]
@javian Sure.  Feels like it is related to this [commit](https://github.com/prometheus/promu/commit/ad9cc26685ca43b9e0dfc3da3ee4ebc5f5cd871f).  That is where they added the `-mod vendor` parameter.  If I remove that from the `.promu.yml` file, it builds.

Where is the code/configuration that pulls down promu?  I don't see it in the file I modified.

**Comment by kadaan** [comment]
> Where is the code/configuration that pulls down promu? I don't see it in the file I modified.

Ahhh.  It is done by the Makefile in prometheus.

**Comment by kadaan** [comment]
@javian What go version is available on the build server?  Is there any way to get a specific version?

**Comment by javian** [comment]
@kadaan it uses the go formula (that the formula depends upon) so whatever version is there is used

**Comment by kadaan** [comment]
@javian Just saw that it does this: `depends_on "go" => :build`.  When I check locally:
 ```
$ brew info go
go: stable 1.11.4 (bottled), HEAD
```
The prometheus [document](https://github.com/prometheus/prometheus/blob/master/README.md#building-from-source) state that 1.11.x is required.

Once I installed go 1.11.4 on my box it all works: 
```
$ goenv install 1.11.4
Downloading go1.11.4.darwin-amd64.tar.gz...
-> https://dl.google.com/go/go1.11.4.darwin-amd64.tar.gz
Installing Go Darwin 64bit 1.11.4...
Installed Go Darwin 64bit 1.11.4 to /Users/jbaranick/.goenv/versions/1.11.4

$ goenv shell 1.11.4

$ GO111MODULE=on /Source/homebrew_prometheus/prometheus-2.6.0/bin/promu build --prefix /Source/homebrew_prometheus/prometheus-2.6.0
 >   prometheus
 >   promtool

$
```
@javian To me, this implies that the go version being use in Jenkins is not 1.11.4, even though that is the version that is available in homebrew.  Is there a way you can verify the go version on the build server?

**Comment by javian** [comment]
@kadaan is it possible for you to install by doing `brew install -s prometheus` to build the formula from source locally ?

**Comment by kadaan** [comment]
@javian I did and it fails.  I added a log line in the formula to get the go version and it is `1.11.4`.  So odd.  It build manually outside of brew.

**Comment by kadaan** [comment]
@javian Got a debug shell and looked further.  The issue is that the `GOPATH` is set to the source directory.  There are numerous reports online that builds fail when the `go.mod` is in the `GOPATH`.  Removed the line from the formula which test the `GOPATH` and it all works.

**Comment by javian** [comment]
Fantastic @kadaan ! Thank you for finding that and congrats on you first commit ^^.

**Comment by javian** [comment]
I managed to discard the fix message so I'll close this manually.

**Comment by igas** [comment]
There are a few issues with this PR:

- it's a duplicate for https://github.com/Homebrew/homebrew-core/pull/35203
- as @fxcoudert mentioned in #35203 it downloads the binary with a curl which is against brew policy (most likely not related to this PR, but needs to be addressed)
- I think by not setting ENV["GOPATH"] we do not build it in isolation

**Comment by kadaan** [comment]
@igas 
- I searched for a duplicate, not sure why I didn't find it.  
- It isn't related to this PR, and I think it should be addressed separate to the version update
- Not in isolation how?  From what I could tell promu dropped the binaries in the working directory

**Comment by kadaan** [comment]
@igas See my comment https://github.com/Homebrew/homebrew-core/pull/35203#issuecomment-448960133

**Comment by igas** [comment]
No worries, I managed to fix the build with GOPATH:

```diff
diff --git a/Formula/prometheus.rb b/Formula/prometheus.rb
index 892e46dc6a..123b462f26 100644
--- a/Formula/prometheus.rb
+++ b/Formula/prometheus.rb
@@ -14,12 +14,15 @@ class Prometheus < Formula
   depends_on "go" => :build
 
   def install
-    mkdir_p buildpath/"src/github.com/prometheus"
-    ln_sf buildpath, buildpath/"src/github.com/prometheus/prometheus"
+    ENV["GOPATH"] = buildpath
+    srcpath = buildpath/"src/github.com/prometheus"
+    srcpath.install buildpath.children
 
-    system "make", "build"
-    bin.install %w[promtool prometheus]
-    libexec.install %w[consoles console_libraries]
+    cd srcpath do
+      system "make", "build"
+      bin.install %w[promtool prometheus]
+      libexec.install %w[consoles console_libraries]
+    end
   end
 
   def caveats; <<~EOS
```

Regarding 3rd poing, I'm not very familiar with golang, but based on our languages in brew, we should not pollute user system, by not setting GOPATH to tmp build directory we potentially leave things in user system.

Regarding second point, we should use resourse, build it, put to build path so make will check that it exists and will not download it.

Wanna send a PR @kadaan?

**Comment by kadaan** [comment]
Regarding the goland go.mod issue see:
https://github.com/golang/go/issues/24106#issuecomment-377556518

**Comment by kadaan** [comment]
No worries. Didn’t take it the wrong way. Thanks for figuring out how to make it work. Did you already get that change into master?  If not, I could maybe do that tomorrow. Regarding promu, the approach would be to make it a brew package, right?

—
Joel Baranick
jbaranick@gmail.com

________________________________

**Comment by igas** [comment]
No, not yet.

I think the better way would be to use local `resource`. I have not tried it but it would be something like this:

```
  resource "promu" do
    url "url to relaese"
    sha256 "sha"
  end
```

The fields basically like in formula itself, with url to tarball. And in install something like:

```
promu_srcpath = buildpath/"src/github.com/prometheus/promu"
promu_srcpath.install resource("promu")
```

This should go after we set `ENV["GOPATH"] = buildpath` and build it similarly to prom itself with installing binary to place where make expects it.

Feel free to open PR and ask questions, we'll figure it out.

**Pull request closed without merging**
