### PR TITLE
workflows/triage: fully quote single-quote in "don't"

### PR DESCRIPTION
**Pull request by timsutton**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Follow-up on https://github.com/Homebrew/homebrew-core/pull/164519: in shell it looks like we can't escape a single-quote like `\'` – instead we use the first `'` to terminate the single-quoted string, then `"'"` followed by one more `'` to "resume" the rest of the single-quoted string 😬

### CODE REVIEW

**Comment by bevanjkay** [comment]
Do we just change it to "do not" to avoid this 😅

**Comment by timsutton** [comment]
> Do we just change it to "do not" to avoid this 😅

I 100% had the same thought, but then I felt like it'd be admitting defeat :D

**Comment by timsutton** [comment]
Further thoughts, I can definitely see the argument to using Octokit.js or similar so that we could more easily pass things around without needing to worry about shell-isms.

**Comment by Bo98** [comment]
Yeah this is really a bug on the action side, but will approve this anyway

**Review by Bo98 — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Sorry, this is bad 😅 I've got a fix on the action's side, hold off for a minute!

**Review by Bo98 — CHANGES_REQUESTED** [review]
Cool, thanks!

**Comment by ZhongRuoyu** [comment]
Homebrew/actions#502

Then we should be able to remove any escaping in the comment body.

**Comment by timsutton** [comment]
> Then we should be able to remove any escaping in the comment body.

Much better, thanks!

**Pull request closed without merging**
