### PR TITLE
duf: add livecheckable

### PR DESCRIPTION
**Pull request by chenrui333**
duf: add livecheckable

--- 

relates to #73964

### CODE REVIEW

**Review by Rylan12 — COMMENTED** [review]
Is this mismatch going to be a regular thing? I think it may make sense to wait to hear back from upstream in the issue you opened to see what their plan is.

From the [`brew livecheck` docs](https://docs.brew.sh/Brew-Livecheck#general-guidelines)
> **Only use the GithubLatest strategy when it’s necessary and correct.** Github.com rate limits requests and we try to minimize our use of this strategy to avoid hitting the rate limit on CI or when using brew livecheck --tap on large taps (e.g. homebrew/core). The Git strategy is often sufficient and we only need to use GithubLatest when the “latest” release is different than the newest version from the tags.

If this is just a one-time occurance, it may not be worth using the more-taxing `github_latest`. If they respond saying "no 0.6.0 is the latest release until 0.6.1 is officially marked on GitHub" then I'd be 👍 on this. Otherwise, not sure.

CC @samford for your opinion

**Review by samford — COMMENTED** [review]
It wouldn't hurt to wait and see if upstream explains whether 0.6.1 is officially released or not.

If upstream says that versions shouldn't be treated as released until there are release notes and artifacts (not just a tag), then using `GithubLatest` would be appropriate. We've applied it in other formulae where a GitHub repository regularly publishes releases with release notes/artifacts but a version tag appears that doesn't have either. There are some repositories that tag a version before turning it into a proper release and that may be the case here.

However, if upstream comes back saying that 0.6.1 should be treated as released when it's tagged (not just when it has release notes/artifacts and is "latest"), then we're fine simply checking the Git tags and it's not necessary to use `GithubLatest`. The `stable` archive in the formula is simply a tag archive and that technically exists right now for 0.6.1.

If we don't hear back from upstream, then I would say that using `GithubLatest` may be more appropriate. If it's ambiguous whether a tagged version is released or not in this type of context, it's potentially better to err on the side of caution and not version bump the formula until the version is a proper release.

**Comment by muesli** [comment]
It will become a proper release, and the git tag already points to the right commit. The only reason it's not "properly released" just yet, is an issue on the Snap store, that prevents me from publishing all the binaries/packages. :disappointed: 

This hopefully gets resolved this weekend.

**Comment by Rylan12** [comment]
@muesli is it fair to say, then, that the latest version corresponds to the latest tag rather than the latest GitHub release? In your opinion, which should we track?

**Comment by muesli** [comment]
No, generally we prepare a proper GitHub release and the current situation is the exception.

Our release pipeline first creates a git tag, then builds all the binaries/packages from that tag and uploads them to GitHub/Snap/Docker. Sadly the Snap upload got blocked and aborted the entire pipeline, which left us with the dangling git tag. I'm hoping for Canonical to resolve this asap.

**Comment by Rylan12** [comment]
Thanks for the info, @muesli.

Based on that, I'd recommend not switching the livecheck strategy to `github_latest`. It seems that `git` will work just fine in most cases.

**Comment by samford** [comment]
I agree. In this case, we should simply stick with checking the Git tags instead of using `GithubLatest`. Thanks, everyone.

**Pull request closed without merging**
