### PR TITLE
semgrep 0.16.0

### PR DESCRIPTION
**Pull request by brendongo**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by dtrodrigues** [comment]
The python resources need to be bumped.

**Comment by brendongo** [comment]
Which ones need to be updated and how do I do that?

**Comment by brendongo** [comment]
We also didn't change dependencies in semgrep?

**Comment by brendongo** [comment]
Updated python dependencies

**Comment by dtrodrigues** [comment]
Thanks @brendongo. Do you think it makes more sense to pull from the tagged git revision or from [PyPI](https://files.pythonhosted.org/packages/5e/9f/6449ff48aa851a1b9692372d79fd7f176f553d495edad24286d75043e140/semgrep-0.16.0.tar.gz). If all else is equal, going with the latter would assist in us more easily updating the python resources in future releases.

**Comment by brendongo** [comment]
Do you have documentation somewhere on what is involved in using the pypi release? Though I would like to get this in as is and if ever do the change in 0.17.0. Is there something I have to do to get the 10.15 test to run?

**Comment by brendongo** [comment]
Also the pypi release comes with pre-built binaries if that changes the thinking?

**Comment by dtrodrigues** [comment]
We can leave it as-is for now.

The CI has been flaky today so I just restarted the tests - nothing needs to be done on your end.

**Review by dtrodrigues — APPROVED** [review]
Thanks for your patience and contribution to Homebrew @brendongo! 🍾

**Pull request closed without merging**
