### PR TITLE
qt 6.2.0 (modify HOMEBREW_TEMP)

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why are you modifying the CI flow?

**Comment by paperchalice** [comment]
> Why are you modifying the CI flow?

Due to [QTBUG-89559](https://bugreports.qt.io/browse/QTBUG-89559) `qt` can't be built when source or build dir are symlinked. `qt` 6.2.0 re-add the `qtwebengine` module which contains a `chromium` fork. The inconsistence of the absolute path and real path let `GN` generate build files in different directory layout. The CMakeLists doesn't consider this case.

**Comment by SMillerDev** [comment]
Then we need to find a fix for that bug, we won't be changing the CI setup so we can build QT. If it's in QTWebengine, can we just disable that?

**Comment by carlocab** [comment]
Still seems useful to know whether it will build if not for the temp directory issues.

**Comment by paperchalice** [comment]
> Then we need to find a fix for that bug, we won't be changing the CI setup so we can build QT. If it's in QTWebengine, can we just disable that?

We could disable `qtwebengine`, this is what we do on Linux (due to the `python2`). I'm not sure how many formulae or developer need this module, because `qt@5` provides `qtwebengine`.

**Pull request closed without merging**
