### PR TITLE
Add etcher, resin.io's image flasher

### PR DESCRIPTION
**Pull request by erikzaadi**
Adds the cli for etcher, which enables you to easily flash images to your SD cards or USBs.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Homebrew formulae must build from source, and this would need a test that exercises and verifies the functionality of the software. Thank you for the PR nonetheless @erikzaadi!

**Comment by erikzaadi** [comment]
@ilovezfs Hey there!
Regarding the test, I checked that executables' version is the correct, do you mean that I need to download the source tarball and built it, instead of the released tarball with the prebuilt executable?

**Comment by ilovezfs** [comment]
>download the source tarball and built it

yup

>I checked that executables' version is the correct

right. The `test do` needs to do a functional test not just a `--version` or `--help` test.

**Comment by erikzaadi** [comment]
@ilovezfs and if I only want to extract an executable, then create a tap / cask?

**Comment by ilovezfs** [comment]
A `cask` won't be accepted in https://github.com/caskroom/homebrew-cask for things that can build from source, but yes you can do what you want in your own tap, of course, whether with a formula or cask.

**Comment by erikzaadi** [comment]
@ilovezfs Thanks! will open another PR if I manage to compile from source.

**Pull request closed without merging**
