### PR TITLE
dependency-check: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
```
737193a21954c8e17ee6cceba9fe5feb428539ae8a049dde766a7216a1aafbb4  bottles/dependency-check--6.2.0.arm64_big_sur.bottle.1.tar.gz
737193a21954c8e17ee6cceba9fe5feb428539ae8a049dde766a7216a1aafbb4  bottles/dependency-check--6.2.0.big_sur.bottle.1.tar.gz
737193a21954c8e17ee6cceba9fe5feb428539ae8a049dde766a7216a1aafbb4  bottles/dependency-check--6.2.0.catalina.bottle.1.tar.gz
737193a21954c8e17ee6cceba9fe5feb428539ae8a049dde766a7216a1aafbb4  bottles/dependency-check--6.2.0.mojave.bottle.1.tar.gz
```

**Review by nandahkrishna — APPROVED** [review]

**Comment by carlocab** [comment]
Also, it seems weird to me that new bottles for previously `bottle :unneeded` formulae are getting `rebuild 1`. Should it be doing that?

CC @Rylan12 since I think you took a look at this last time

**Comment by Rylan12** [comment]
@carlocab is this happening for all `bottle :unneeded` removals or just here? I agree, it doesn't seem right. My guess is that the rebuild is set to 0 by default behind the scenes and is just never reached when `bottle :unneeded` is set. So the rebuild calculation sees that a bottle does exist (even though it's `:unneeded`) and is 0 so it bumps it. That's all a guess; I'll try to take a look later.

**Comment by carlocab** [comment]
> is this happening for all `bottle :unneeded` removals or just here?

I think it's happening for all of them.

**Pull request closed without merging**
