### PR TITLE
sccache 0.2.6

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
```
$ brew linkage sccache
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/Security.framework/Versions/A/Security
  /usr/lib/libSystem.B.dylib
  /usr/lib/libresolv.9.dylib
Homebrew libraries:
  /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (openssl@1.1)
  /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (openssl@1.1)
Undeclared dependencies with linkage:
  openssl@1.1
```

**Comment by alex** [comment]
I'm not sure I understand what I'm looking at -- is the issue that it should be marked as depending on `openssl@1.1` instead of `openssl`, since it will prefer to link against that if it's available?

**Comment by alex** [comment]
@commitay Are there any blockers to landing this?

**Comment by alex** [comment]
Thanks!

**Pull request closed without merging**
