### PR TITLE
xz 5.2.9

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Continuing from https://github.com/Homebrew/homebrew-core/pull/115687

**Comment by chenrui333** [comment]
pyflow failure seems legit, raise [an issue in the upstream](https://github.com/David-OConnor/pyflow/issues/184)

**Comment by p-linnane** [comment]
Thanks for opening that. I am also on 13-arm64, so cannot do additional testing.

**Comment by p-linnane** [comment]
Rebased with 5.2.9 and re-running.

**Comment by cho-m** [comment]
`pyflow` failure occurs in other PRs. It looks like it queries dependencies via https://github.com/David-OConnor/pydeps but the API (e.g. https://pydeps.herokuapp.com/requests) doesn't seem to work right now.

**Comment by p-linnane** [comment]
@cho-m Is `pyflow` our blocker here? Seems like the `pydeps` API has been down for some time.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Given the huge number of dependencies, and the nature of the failures seen, I think this can be merged. @cho-m any objection?

**Review by cho-m — APPROVED** [review]
Should be fine to merge. Need to manually create `archive.org` mirrors though, particularly the HTTP one.

**Comment by p-linnane** [comment]
Do we have any doscumentation on that process anywhere?

**Pull request closed without merging**
