### PR TITLE
freetype 2.9

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The SSL certificate for https://purl.org/net/pkgwpub/tectonic-default expired on 4 Jan, which is why the tectonic test is failing. CC @pkgw

**Comment by ilovezfs** [comment]
Upstream issue for that is here: https://github.com/tectonic-typesetting/tectonic/issues/131

**Comment by pkgw** [comment]
Argh. I have attempted to contact archive.org multiple times about this issue — purl.org is supposed to be a bullet-proof, long-term link service, so the expired SSL cert is really disappointing. But if they can't fix it soon, I guess I'll have to update Tectonic to use another service.

**Comment by lembacon** [comment]
The test for `libdrawtext` is failing on High Sierra, due to that the hardcoded font path `/System/Library/Fonts/LastResort.ttf` becomes `LastResort.otf` as of High Sierra.

**Comment by ilovezfs** [comment]
@lembacon do you want to handle letting upstream know about your fix?

**Comment by lembacon** [comment]
@ilovezfs For `libdrawtext`, there is nothing to do with upstream. The hardcoded path `/System/Library/Fonts/LastResort.ttf` is inside the `test` block of the formula.

https://github.com/Homebrew/homebrew-core/blob/31c3f459e69c4f8b9c0d083756d1b49f78e723e1/Formula/libdrawtext.rb#L30-L31

**Comment by ilovezfs** [comment]
@pkgw I'm not sure what the best practices are for automatically keeping Let's Encrypt certificates up to date, but it seems purl.org isn't following them if this keeps happening.

**Comment by ilovezfs** [comment]
@lembacon hehe oh ok. CAN HAZ PR? ❤️

**Comment by lembacon** [comment]
@ilovezfs on it

**Comment by ilovezfs** [comment]
thanks!

**Comment by ilovezfs** [comment]
Thanks again @lembacon!

**Pull request closed without merging**
