### PR TITLE
nim: adding tools.

### PR DESCRIPTION
**Pull request by ghost**
Building and adding tools 'nimble', 'nimgrep' and 'nimsuggest', which are part of the core nim tree. Added a small test to make sure the basic nimble behavior works.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@ysalmi In future please continue in the existing PR (https://github.com/Homebrew/homebrew-core/pull/5919) rather than opening a new one.

**Comment by ysalmi** [comment]
@MikeMcQuaid ok sorry wasn't sure, this was my first PR and the docs say 'one commit per formula'. And my commit messages were badly formatted.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by ysalmi** [comment]
Thank you for running such an awesome project!

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words!

**Comment by ysalmi** [comment]
@MikeMcQuaid hey, if I have another small fix, should I submit it here or open a new request?

**Comment by MikeMcQuaid** [comment]
@ysalmi Open a new one, thanks!

**Pull request closed without merging**
