### PR TITLE
pulp 13.0.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
relates to https://github.com/Homebrew/homebrew-core/pull/41635

### CODE REVIEW

**Comment by chenrui333** [comment]
test step failed:
03:18:27 ==> /usr/local/Cellar/pulp/13.0.0/bin/pulp --version
03:18:27 ==> /usr/local/Cellar/pulp/13.0.0/bin/pulp init 2>&1
03:18:27 Error: pulp: failed
03:18:27 An exception occurred within a child process:
03:18:27   Test::Unit::AssertionFailedError: <0> expected but was
03:18:27 <1>.

**Comment by chenrui333** [comment]
Cannot reproduce locally.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Please squash your commits

**Comment by chenrui333** [comment]
@SMillerDev updated 👍

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @chenrui333

**Pull request closed without merging**
