### PR TITLE
chromedriver: migrate to cask

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
https://github.com/caskroom/homebrew-cask/pull/45029

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by vitorgalvao** [comment]
I think this should instead be changed to allow installing from source.

Some users are already confused by the difference between HB and HBC, but our current explanation makes sense and is easy to give: it it’s open-source and CLI-only it goes in HB, everything else in HBC. Exceptions need to have a *strong* reason.

If we start to get open-source CLI-only stuff in HBC because casks are easier to make (feeble reason), we start a bad precedent. I say this as someone who many times refused PRs in HBC to say “try HB first, since it makes more sense there”. If we’re the ones doing it, we’re not setting the example we’d like for users to follow and might start having duplication again.

**Comment by ilovezfs** [comment]
I am fine with just deleting it.

**Comment by ilovezfs** [comment]
Actually, sorry I didn't realize this has so many installs.
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics chromedriver
install events in the last 30 days for chromedriver
================================================================================
1 | chromedriver                                              | 18,162 | 100.00%
================================================================================

install_on_request events
================================================================================
1 | chromedriver                                              | 16,626 | 100.00%
================================================================================

Error: No BuildError data found!
Josephs-MacBook-Pro:~ joe$ 
```
and is #17 in https://brew.sh/analytics/install-on-request/ so we can't just delete this.

I certainly am not volunteering to attempt a source build of this but @fxcoudert correctly noted it is in violation of our policies. @fxcoudert @vitorgalvao are either of you willing to write a formula for it? If not, we're just going to have keep distributing the binaries in homebrew-core until someone comes along willing to fix this.

**Comment by ilovezfs** [comment]
To build, it looks like we need to clone a Git repository that as a shallow clone is 888 MiB. Also, there are no tags for chromedriver itself, just a https://github.com/chromium/chromium/commits/master/chrome/test/chromedriver/VERSION file. So the prospects for a source build aren't looking great.

**Comment by fxcoudert** [comment]
Building instructions are there: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/mac_build_instructions.md
I'm not willing to do it myself.

I agree we don't want to remove it, given how many users it has. But similarly we can't continue much longer shipping binaries in Homebrew core, while we ask all other formulas to do the job of building from source.

**Comment by LouisStAmour** [comment]
I took a stab at trying to reduce the source code required to build ChromeDriver. I found a link to download a .tgz of the chrome/test/chromedriver folder at https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver

It's 286K. Simple, I thought. :)

After installing depot_tools from http://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up I then got the error:
```
$ gn gen out/Default
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
```

As it happens, `gn` requires a Chromium checkout because the `depot_tools` repo is just filled with wrapper scripts and such. And the checkout provides a hook to execute gcloud. So I found the manual alternative: I downloaded the `chromium/buildtools` repo, got the SHA1 from `buildtools/mac/gn.sha1` and ran `gsutil cp gs://chromium-gn/5f3ab6d8d2729ae84a49ec5ef766b6c13b018af7 buildtools/mac/gn` to get a full copy of `gn`. After which my problem was just beginning:

ChromeDriver has these deps:

```
  deps = [
    ":embed_extension_in_cpp",
    ":embed_js_in_cpp",
    ":embed_user_data_dir_in_cpp",
    "//base",
    "//base/third_party/dynamic_annotations",
    "//net",
    "//third_party/WebKit/public:features",
    "//third_party/zlib:minizip",
    "//third_party/zlib/google:zip",
    "//ui/accessibility:ax_enums_mojo",
    "//ui/base",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//url",
  ]
```

... which I eventually downloaded one by one as tarball source extracts (they're tiny):

```
-rw-r--r--  1 lsta  staff   286K 31 Mar 15:48 ../chromedriver.tar.gz
-rw-r--r--  1 lsta  staff   2.9M 31 Mar 16:27 base.tar.gz
-rw-r--r--  1 lsta  staff   899K 31 Mar 16:23 build.tar.gz
-rw-r--r--  1 lsta  staff   2.3K 31 Mar 16:36 build_overrides.tar.gz
-rw-r--r--  1 lsta  staff   9.3M 31 Mar 16:42 net.tar.gz
-rw-r--r--  1 lsta  staff   1.6M 31 Mar 16:26 testing.tar.gz
-rw-r--r--  1 lsta  staff   375K 31 Mar 16:34 third_party/WebKit/public.tar.gz
-rw-r--r--  1 lsta  staff   221K 31 Mar 16:35 third_party/webdriver/webdriver.tar.gz
-rw-r--r--  1 lsta  staff   273K 31 Mar 16:34 third_party/zlib.tar.gz
-rw-r--r--  1 lsta  staff   510K 31 Mar 16:45 ui/accessibility/accessibility.tar.gz
-rw-r--r--  1 lsta  staff   646K 31 Mar 16:46 ui/base/base.tar.gz
-rw-r--r--  1 lsta  staff   631K 31 Mar 16:47 ui/gfx/gfx.tar.gz
-rw-r--r--  1 lsta  staff   152K 31 Mar 16:48 url/url.tar.gz
```

But then in turn, each of these has a `BUILD.gn` file. Even things you'd hope would be self-contained are not: `base` relies on `third_party/modp_b64`, for example. `WebKit/public` relies on: `//cc`, `//components/viz/common`, `//media/midi`, `//mojo/public/cpp/bindings`, `//services/device`, `//services/network` and `//v8`. And each of these deps may in turn rely on other parts of the codebase.

All of this is complex enough to make me wonder if https://blogs.msdn.microsoft.com/devops/2018/03/15/gvfs-for-mac/ is a viable alternative at some future date if the goal is to save disk space and transfer time.

Either that or I'd have to write a script to go through an existing checkout for full Chromium, figure out which modules/files are used when building ChromeDriver to save on download size, and download and set up just these files. And it could change with new releases, so it would have to be automated. 

Really, this is a job for Google to do, but given the cost is disk space, they probably prefer to just centralize builds and ship binaries to avoid it. And as broadband speeds increase, they may have even less of an incentive to "fix" this given the maintenance cost of splitting out the obviously integrated ChromeDriver (and deps) from everything else Chromium.

**Comment by woodruffw** [comment]
I'm :+1: on a Cask migration -- building something this complex from source is going to impose a pretty big maintenance burden, and attempting to slim down the repo introduces more avenues for failure.

**Comment by vitorgalvao** [comment]
It has now been merged in HBC. Ready to proceed here whenever you are.

**Pull request merged**
