### PR TITLE
libre 0.6.1

### PR DESCRIPTION
**Pull request by samford**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by samford** [comment]
Looking at a previous baresip/libre/librem-related PR (#37254), it was expected that the baresip tests would fail here with the same errors.  For what it's worth, I intend to update the baresip formula after this to fix the issues (using the aforementioned PR as a guide), which is why I wanted to update the libre version first.

**Comment by samford** [comment]
I've looked into baresip's test failure a bit more and it seems like the source of the issue is that baresip isn't handling the command line arguments, at least not on Mojave or Catalina.

Without the `-f` argument, baresip will look for a `.baresip` folder in the user's home folder and initialize it when not found.  Similarly, if a `.baresip` folder exists in the user's home folder, the test won't complete because the `-t` flag (test and exit) isn't being respected, so baresip simply runs until the timeout.

baresip's [`main.c` file](https://github.com/alfredh/baresip/blob/master/src/main.c) seems to suggest that they use getopt for handling CLI args but I haven't been able to get any arguments to work (on macOS Catalina) regardless of whether baresip is built with or without `HAVE_GETOPTS=1`.  I've tested the current version of baresip in Homebrew (0.5.10), built or bottled, as well as the current version (0.6.4).

If we can fix this issue with arguments not being handled, it may make the test work properly again and we can then update the baresip formula.  It's strange that it seems to have passed fine in PRs from 2017-06-26 to 2018-07-04 (before failing in the next PR on 2019-04-11).

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Then merging, and you can fix baresip later

**Pull request closed without merging**
