### PR TITLE
boost@1.63 (new formula)

### PR DESCRIPTION
**Pull request by randy3k**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
Why do you believe this is needed?

**Comment by randy3k** [comment]
It is required by `rstudio-server --HEAD`.
RStudio-Server is only compatible with [v1.63 or later](https://github.com/rstudio/rstudio/blob/9847564eb69eefe5b37e26031dd2536ac3961014/src/cpp/CMakeLists.txt#L177), and it doesn't build with v1.65 (the current version of boost).

**Comment by ilovezfs** [comment]
Unfortunately that's not a sufficient reason for us to add a new versioned formula. Please see https://github.com/Homebrew/brew/blob/master/docs/Versions.md#acceptable-versioned-formulae. Thanks for the PR nonetheless @randy3k!

**Comment by randy3k** [comment]
Boost is such a common library, I am quite sure there are formulas which only compile with a particular version of boost but not the another version of boost.

Given that there are already 5 versions of boosts (include `boost.rb`), 
screen shot 2017-09-08 at 4 41 24 pm

I really don't understand why you allow  `boost v1.55`, `boost v1.57`, `boost v1.59` but not `boost v1.63`.

**Pull request closed without merging**
