### PR TITLE
bitrise v1.34.0

### PR DESCRIPTION
**Pull request by trapacska**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by alebcay** [comment]
```
==> Fast-forwarding to the merge commit
fatal: Not possible to fast-forward, aborting.
Error: Failure while executing; `git merge --quiet --ff-only --no-edit FETCH_HEAD` exited with 128.
Homebrew/brew 2.1.11-59-g9d15c2b83 (Merge pull request #6451 from Homebrew/revert-6411-argv-cleanup-1)
```

**Comment by SMillerDev** [comment]
@BrewTestBot test this please.

**Comment by SMillerDev** [comment]
Can you remove the merge commit and rebase on master?

**Comment by trapacska** [comment]
@SMillerDev sorry for responding too late. Closed this PR in favor of the newer version. Sorry about that!

**Pull request closed without merging**
