### PR TITLE
openfst: build optional modules

### PR DESCRIPTION
**Pull request by marcusb**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why are they not enabled by default by upstream?

**Comment by marcusb** [comment]
I don't know why they don't, but the formula contributed by some of the upstream devs did build the additional modules. There are dependent projects that require some of the extension modules.

The formula was completely rewritten in [this PR](https://github.com/Homebrew/homebrew-core/pull/60511) and the extra modules were dropped, making it much less useful.

**Comment by marcusb** [comment]
cf also the [formula](https://github.com/brewsci/homebrew-science/blob/master/Formula/openfst.rb) from homebrew-science with includes the modules. (It has slightly different options but they are equivalent.)

**Review by fxcoudert — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]
Thanks @marcusb  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
