### PR TITLE
e2fsprogs 1.45.4

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
I'm pretty sure the test failure for `ext2fuse` is because `osxfuse` is not available in the test environment (unrelated to this PR).

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by SMillerDev** [comment]
```
        Missing libraries:
  /usr/local/lib/libfuse.2.dylib
```

**Comment by bradleyfalzon** [comment]
Having this issue, what needs to happen to get this prodded along?

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Close due to inactivity.

**Pull request closed without merging**
