### PR TITLE
alluxio 2.6.1

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
alluxio 2.5.0-3

The test currently fails locally, seemingly due to a sandboxing issue.

### CODE REVIEW

**Review by nandahkrishna — DISMISSED** [review]
Thanks, @JCount!

**Review by SMillerDev — DISMISSED** [review]

**Comment by nandahkrishna** [comment]
This isn't getting merged because it isn't an `all` bottle. I even tried downloading the artifact locally and using `pr-upload` but that didn't work either perhaps due to the bottle size.

Checking the source, this might be the reason:
```
➜ grep -R "/usr/local" .
./integration/docker/Dockerfile.fuse:ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin/tini
./integration/docker/Dockerfile.fuse:RUN chmod +x /usr/local/bin/tini
./integration/docker/Dockerfile:ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin/tini
./integration/docker/Dockerfile:RUN chmod +x /usr/local/bin/tini
```

**Comment by cho-m** [comment]
I think the Big Sur (Intel) bottle may also have an issue.

I've tried downloading bottles twice and see SHA for that tar is 
`5cfb0a6c6468e3e93752617ec88630d6bf38c72948f8eb4c09cbab2ba71c5fc4`

But JSON file says:
`1674d41ab93adb2eec35b539f042fd8cb3c3430145b78364bae2e3d123cf529a`

I've also tried to untar and end up with an error:
```
x alluxio/2.5.0-3/libexec/client/presto/plugins/prestodb-hive-alluxio-227/zstd-jni-1.3.5-4.jar
x alluxio/2.5.0-3/libexec/client/presto/plugins.tar.gz: gzip decompression failed
tar: Error exit delayed from previous errors.
```

**Comment by nandahkrishna** [comment]
Interesting. The `pr-upload` failed for me at the Big Sur bottle upload step, and I think this might have caused it.

**Comment by nandahkrishna** [comment]
Interesting. The `pr-upload` failed for me when uploading the Big Sur bottle, not sure if this could be the cause.

**Comment by cho-m** [comment]
I am guessing that Big Sur had some unlucky corruption in tar file.

Anyway, once the ARM diff for `/usr/local` is fixed and CI is re-run, all tar should be identical and just need to hope similar issue doesn't happen.

```diff
--- a/alluxio-arm64_big_sur/2.5.0-3/libexec/integration/docker/Dockerfile
+++ b/alluxio-catalina/2.5.0-3/libexec/integration/docker/Dockerfile
@@ -49,8 +49,8 @@ ARG ENABLE_DYNAMIC_USER=false
 # Add Tini
 # - https://github.com/krallin/tini
 ENV TINI_VERSION v0.18.0
-ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin/tini
-RUN chmod +x /usr/local/bin/tini
+ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini @@HOMEBREW_PREFIX@@/bin/tini
+RUN chmod +x @@HOMEBREW_PREFIX@@/bin/tini

 RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
   add-apt-repository -y ppa:openjdk-r/ppa && \
diff --git a/alluxio-arm64_big_sur/2.5.0-3/libexec/integration/docker/Dockerfile.fuse b/alluxio-catalina/2.5.0-3/libexec/integration/docker/Dockerfile.fuse
index fc2b3b1..c01723a 100644
--- a/alluxio-arm64_big_sur/2.5.0-3/libexec/integration/docker/Dockerfile.fuse
+++ b/alluxio-catalina/2.5.0-3/libexec/integration/docker/Dockerfile.fuse
@@ -49,8 +49,8 @@ ARG ENABLE_DYNAMIC_USER=false
 # Add Tini since it isn't included in Ubuntu by default
 # - https://github.com/krallin/tini
 ENV TINI_VERSION v0.18.0
-ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin/tini
-RUN chmod +x /usr/local/bin/tini
+ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini @@HOMEBREW_PREFIX@@/bin/tini
+RUN chmod +x @@HOMEBREW_PREFIX@@/bin/tini

 RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
     add-apt-repository -y ppa:openjdk-r/ppa && \
```

**Review by SMillerDev — DISMISSED** [review]

**Comment by nandahkrishna** [comment]
> Anyway, once the ARM diff for `/usr/local` is fixed and CI is re-run, all tar should be identical and just need to hope similar issue doesn't happen.

I'm not sure if doing an `inreplace` to fix the diff would be correct here (it's placing an executable in `/usr/local/bin`, and we may not want to modify that to `/opt/homebrew` on ARM).

**Comment by cho-m** [comment]
It looks more like a reverse issue.
`@@HOMEBREW_PREFIX@@` seems a bit questionable since this is for the docker (Alpine Linux) image, not specific to the local Homebrew paths.

**Comment by cho-m** [comment]
I have a feeling the Dockerfile isn't essential so we could try to merge again, though it does add extra GB of unneeded data.

Could also directly bump to use newer version too:
```console
❯ brew livecheck alluxio
alluxio : 2.5.0-2 ==> 2.6.1
```

**Comment by SMillerDev** [comment]
Sounds good

**Review by cho-m — APPROVED** [review]
Let's give the merge another try.

**Pull request closed without merging**
