### PR TITLE
haproxy 2.6.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Question, why is it not possible to use unversioned openssl versions as brew is complaining it's an alias: `* Dependency 'openssl' is an alias; use the canonical name 'openssl@3'.` while others I seems to find in aliases such as unversioned Go version aren't a problem?

**Comment by SMillerDev** [comment]
Because unversioned go is not an alias: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/go.rb#L1

**Comment by Porkepix** [comment]
> Because unversioned go is not an alias: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/go.rb#L1

I looked here: https://github.com/Homebrew/homebrew-core/tree/master/Aliases where I found both `go` and `openssl`, so it's not the right way to do?

**Comment by SMillerDev** [comment]
The unversioned formula is always the latest version, unless that causes problems, then we make the unversioned option the alias and version all formula.

**Comment by Porkepix** [comment]
> The unversioned formula is always the latest version, unless that causes problems, then we make the unversioned option the alias and version all formula.

And then what's the point of having an alias of the versioned one (`go@1.18` for example) pointing to the unversioned one? Because that alias would become a problem as soon as unversioned one points to `1.19`, right?

As for `haproxy` here, as i checked for openssl 3 compatibility I guess it's fine like that?

**Comment by SMillerDev** [comment]
> And then what's the point of having an alias of the versioned one (go@1.18 for example) pointing to the unversioned one? 

So people can do `brew install go@1.18` if they choose to do so.

> Because that alias would become a problem as soon as unversioned one points to 1.19, right?

There's an audit for that.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
