### PR TITLE
cabal-install 3.6.0

### PR DESCRIPTION
**Pull request by fishtreesugar**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Use binary provided in https://github.com/haskell/cabal/issues/7433#issuecomment-858590474 to bootstrap darwin aarch64 build

### CODE REVIEW

**Comment by fishtreesugar** [comment]
@carlocab I think this PR need `CI-long-timeout` label

**Comment by carlocab** [comment]
I don't think any of these revision bumps are needed.

**Comment by fishtreesugar** [comment]
@carlocab sry, I am not sure how to fix these errors, so I gave a random shot of it. Any suggestions?

**Comment by carlocab** [comment]
The ARM failures are not bottled, so those are expected. We should look into the Mojave failures though. Revision bumps here won't help since these dependents are built from source.

**Comment by fishtreesugar** [comment]
`cedille`'s failure is known. and `elm-format` due to hard coded ghc version, both not related to `cabal-install` I think.

**Comment by cho-m** [comment]
`elm-format` is unrelated and I have opened a fix for issue in #85118. My previous PR #82910 tried to use `stack setup` to install required older version, but it relied on the default resolver, which now picks 8.10.7 rather than 8.10.4.

**Review by carlocab — APPROVED** [review]
Thanks @fishtreesugar!

**Comment by ivanperez-keera** [comment]
By the way: cabal 3.6 is buggy. Currently, I have no way of using it: https://github.com/haskell/cabal/issues/7331.

Please bring back 3.4 or let's create versioned formulas.

**Comment by carlocab** [comment]
@ivanperez-keera why can't you create a versioned formula in your own tap, as has been repeatedly suggested to you?

**Pull request closed without merging**
