### PR TITLE
poco 1.7.9p1

### PR DESCRIPTION
**Pull request by quantumsteve**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks @quantumsteve! :rocket:

**Comment by s172262** [comment]
???
```
$ brew fetch -s poco
==> Downloading https://pocoproject.org/releases/poco-1.7.9/poco-1.7.9p1-all.tar
######################################################################## 100.0%
Downloaded to: /Users/aoyamatakuo/Library/Caches/Homebrew/poco-1.7.9p1.tar.gz
SHA256: 76f698d3e537879664f56a3dfde3a88e88f06c13b6474dd6a0ee6ad7f6ab4e4a
Warning: Formula reports different SHA256: 463f58aac40a7f7f28950b2c5bfe6c25a0dc61a70e5269a2be8c35d76fcbea84

$ ls -la poco-1.7.9p1.tar.gz 
-rw-r--r--  1 s172262  staff  6230036 11  4 21:37 poco-1.7.9p1.tar.gz
```

**Comment by ilovezfs** [comment]
@s172262 reported: https://github.com/pocoproject/poco/issues/1976

**Comment by ilovezfs** [comment]
@s172262 This is now fixed via https://github.com/Homebrew/homebrew-core/pull/20290.

**Pull request closed without merging**
