### PR TITLE
hledger 1.20.3

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
`resource` + `install` blocks need updating, I think. Ping @simonmichael

**Comment by simonmichael** [comment]
@chenrui333 I modified your commit and added another simplifying the script: https://github.com/Homebrew/homebrew-core/compare/master...simonmichael:master

**Comment by carlocab** [comment]
Thanks, @simonmichael. Feel free to create a new PR with your changes. Just link back to this one so they aren't both merged by mistake.

**Comment by simonmichael** [comment]
#69129 created.

**Comment by carlocab** [comment]
Superseded by #69129.

**Pull request closed without merging**
