### PR TITLE
gsound 1.0.2 (new formula)

### PR DESCRIPTION
**Pull request by aleb**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?

_I did actually, but it printed that it's already installed. It's even mentioned in https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#add-a-new-formula-for-foo-version-234-from-url - not sure what the point is, for new formulas._

- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Error Message

failed: brew test gsound --verbose

Stacktrace

        Testing gsound
/usr/bin/sandbox-exec -f /tmp/homebrew20171130-91354-x388vn.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gsound.rb --verbose
==> python -c from gi.repository import GSound
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gi.repository
Error: gsound: failed
Failed executing: python -c from\ gi.repository\ import\ GSound
```

**Review by tschoonj — COMMENTED** [review]
This appears to be a dead project since it hasn't had a commit in more than two years.

Is there a particular reason why you need this package? Perhaps as a dependency of another formula you plan on submitting?

**Comment by aleb** [comment]
I think the test fails because it's using the system python. It should work fine if python2 is installed (or python3). I'll have to fix the test to ignore the Mac system python.

GSound has not been updated lately because there was no need to - it's a gi wrapper for libcanberra which had the last release in 2012 http://0pointer.de/lennart/projects/libcanberra/

I need this package for Pitivi. The plan is to use an "Untar anywhere" installation of Homebrew to "brew install" https://gist.github.com/aleb/8bfe374e4fe68419567a9d473217da95 and then bundle that in an `.app` somehow. Suggestions welcome! I waited 1h for gcc to build and I'm looking now at a numpy build failure.

**Comment by tschoonj** [comment]
Ok then, I do not object if you manage to fix the test failure. For that you should probably set the PYTHONPATH variable in the test block and make it point to the correct folder. Check the `pygobject3` formula for an example.

**Pull request closed without merging**
