### PR TITLE
node@14 14.18.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by derrabus** [comment]
Test failure:

<details>

```
npm verb stack Error: bufferutil@4.0.4 install: `node-gyp-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@14/14.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:400:28)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@14/14.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1058:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm verb pkgid bufferutil@4.0.4
npm verb cwd /private/tmp/nodeA14-test-20210928-23403-1uxi9h5
npm verb Darwin 20.6.0
npm verb argv "/usr/local/Cellar/node@14/14.18.0/bin/node" "/usr/local/Cellar/node@14/14.18.0/bin/npm" "-ddd" "--cache=/Users/brew/Library/Caches/Homebrew/npm_cache" "--build-from-source" "install" "bufferutil"
npm verb node v14.18.0
npm verb npm  v6.14.15
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.4 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
```

</details>

The failure does not seem to be related to the version bump. The very same test fails if I execute it for the currently bottled versions of `node@12`, `node@14` and `node`.

**Comment by derrabus** [comment]
Blocked by #86090

**Comment by carlocab** [comment]
Let's just get rid of the failing test for now. It'll be fixed properly in #86090. There's no need to delay a version update while we're waiting for the test to be fixed.

**Review by SMillerDev — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you for completing and merging the PR. ❤️

**Pull request closed without merging**
