### PR TITLE
tinyxml2 7.0.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`dartsim` and `lgogdownloader` need revision bump

**Comment by scpeters** [comment]
I just pushed revision bumps for `dartsim` and `lgogdownloader`

**Comment by fxcoudert** [comment]
Sadly this conflicts with boost and I have to rerun it through CI :(

**Comment by scpeters** [comment]
this version of tinyxml2 has a broken pkg-config file, for which I have offered a patch in https://github.com/leethomason/tinyxml2/pull/720

if upstream is slow to respond, I will submit that patch to fix this formula as it is affecting downstream users

**Pull request closed without merging**
