### PR TITLE
v8 9.8.177.9

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chrmoritz** [comment]
You need to update all resources too: https://chromium.googlesource.com/v8/v8.git/+/refs/tags/9.8.177.9/DEPS#43

**Comment by carlocab** [comment]
Looks like this crashed while trying to build `libicui18n`. I wonder if this needs an unreleased LLVM again.

```
  libc++abi: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
  PLEASE submit a bug report to https://github.com/Homebrew/homebrew-core/issues and include the crash backtrace.
  Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
  0  libLLVM.dylib            0x0000000108b49e9c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
  1  libLLVM.dylib            0x0000000108b4a470 SignalHandler(int) + 324
  2  libsystem_platform.dylib 0x000000019d4944e4 _sigtramp + 56
  3  libsystem_pthread.dylib  0x000000019d47d15c pthread_kill + 288
  4  libsystem_c.dylib        0x000000019d3ba314 abort + 164
  5  libc++abi.dylib          0x000000019d439b50 __cxxabiv1::__aligned_malloc_with_fallback(unsigned long) + 0
  6  libc++abi.dylib          0x000000019d42af4c demangling_terminate_handler() + 308
  7  libobjc.A.dylib          0x000000019d3221b0 _objc_terminate() + 160
  8  libc++abi.dylib          0x000000019d438ee4 std::__terminate(void (*)()) + 20
  9  libc++abi.dylib          0x000000019d43bc5c __cxa_get_exception_ptr + 0
  10 libc++abi.dylib          0x000000019d43bc08 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 0
  11 lld                      0x000000010232acb4 std::__1::__throw_out_of_range(char const*) + 52
  12 lld                      0x000000010232a890 lld::macho::WordLiteralInputSection::getOffset(unsigned long long) const + 528
  13 lld                      0x00000001023195e0 equalsConstant(lld::macho::ConcatInputSection const*, lld::macho::ConcatInputSection const*) + 360
  14 lld                      0x000000010231758c ICF::segregate(unsigned long, unsigned long, std::__1::function<bool (lld::macho::ConcatInputSection const*, lld::macho::ConcatInputSection const*)>) + 164
  15 lld                      0x000000010231938c std::__1::__function::__func<ICF::run()::$_4, std::__1::allocator<ICF::run()::$_4>, void (unsigned long, unsigned long)>::operator()(unsigned long&&, unsigned long&&) + 84
  16 lld                      0x0000000102318698 std::__1::__function::__func<void llvm::parallel::detail::parallel_for_each_n<unsigned long, ICF::forEachClass(std::__1::function<void (unsigned long, unsigned long)>)::$_1>(unsigned long, unsigned long, ICF::forEachClass(std::__1::function<void (unsigned long, unsigned long)>)::$_1)::'lambda'(), std::__1::allocator<void llvm::parallel::detail::parallel_for_each_n<unsigned long, ICF::forEachClass(std::__1::function<void (unsigned long, unsigned long)>)::$_1>(unsigned long, unsigned long, ICF::forEachClass(std::__1::function<void (unsigned long, unsigned long)>)::$_1)::'lambda'()>, void ()>::operator()() + 280
  17 libLLVM.dylib            0x0000000108adddc8 std::__1::__function::__func<llvm::parallel::detail::TaskGroup::spawn(std::__1::function<void ()>)::$_0, std::__1::allocator<llvm::parallel::detail::TaskGroup::spawn(std::__1::function<void ()>)::$_0>, void ()>::operator()() + 40
  18 libLLVM.dylib            0x0000000108add70c llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) + 408
  19 libLLVM.dylib            0x0000000108add84c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()> >(void*) + 48
  20 libsystem_pthread.dylib  0x000000019d47d4ec _pthread_start + 148
  21 libsystem_pthread.dylib  0x000000019d4782d0 thread_start + 8
  clang++: error: unable to execute command: Abort trap: 6
  clang++: error: linker command failed due to signal (use -v to see invocation)
  Traceback (most recent call last):
    File "../build/toolchain/apple/linker_driver.py", line 291, in <module>
      LinkerDriver(sys.argv).run()
    File "../build/toolchain/apple/linker_driver.py", line 116, in run
      subprocess.check_call(compiler_driver_args, env=env)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['../../../../opt/homebrew/opt/llvm/bin/clang++', '-shared', '-Wl,-install_name,@rpath/libicui18n.dylib', '-fuse-ld=lld', '-Wl,-fatal_warnings', '-Wl,--icf=all', '-Wl,--color-diagnostics', '-stdlib=libc++', '-arch', 'arm64', '-no-canonical-prefixes', '-Wl,-dead_strip', '-isysroot', '../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk', '-mmacosx-version-min=10.11.0', '-Wl,-ObjC', '-Wl,-rpath,@loader_path/.', '-Wl,-rpath,@loader_path/../../..', '-o', './libicui18n.dylib', '@./libicui18n.dylib.rsp']' returned non-zero exit status 254
```

**Comment by chrmoritz** [comment]
Yeah, maybe worth testing with `llvm` 14.0.0-rc1 once that is released tomorrow.

**Comment by chrmoritz** [comment]
It build fine on my intel macbook with `llvm` 13.0.0, so maybe this is an arm only issue?

**Comment by carlocab** [comment]
Yep, looks to be ARM-specific. Probably a bug in `lld`, given that that's where the exception seems to originate from.

I suggest we keep using `ld` as the linker on macOS. I know upstream use `lld`, but I suspect that's primarily because they're cross-compiling, and doing so with `lld` is a little bit easier given that they already have an LLVM toolchain. `ld` is a much more mature linker anyway.

**Pull request closed without merging**
