### PR TITLE
ospray 2.7.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

---

build depends on:
- #81436
- #83719

### CODE REVIEW

**Comment by cho-m** [comment]
May want to check on status of ARM support https://github.com/ospray/ospray/releases/tag/v2.7.0
> OSPRay can now be built for ARM64 CPUs with NEON (e.g., Apple M1)
using the superbuild. Thus, new minimum versions are for ISPC
1.16.0, for Embree 3.13.1 and for rkcommon 1.7.0

**Comment by chenrui333** [comment]
yeah, good call, re-queue the build for 11-arm64 build

**Comment by chenrui333** [comment]
test failure on 11-arm64

```
==> /usr/bin/clang test.c -I/opt/homebrew/Cellar/ospray/2.7.0/include -L/opt/homebrew/Cellar/ospray/2.7.0/lib -lospray
==> ./a.out
dyld: Library not loaded: @rpath/librkcommon.1.dylib
  Referenced from: /opt/homebrew/opt/ospray/lib/libospray.2.dylib
  Reason: image not found
Error: ospray: failed
An exception occurred within a child process:
  BuildError: Failed executing: ./a.out
```

**Comment by cho-m** [comment]
Seems to be an RPATH issue. The libraries both exist in bottle.
```console
❯ otool -L lib/libospray.2.dylib
lib/libospray.2.dylib:
	@@HOMEBREW_PREFIX@@/opt/ospray/lib/libospray.2.dylib (compatibility version 2.0.0, current version 2.7.0)
	@rpath/librkcommon.1.dylib (compatibility version 1.0.0, current version 1.7.0)
	@@HOMEBREW_PREFIX@@/opt/tbb/lib/libtbb.12.dylib (compatibility version 12.0.0, current version 12.3.0)
	@@HOMEBREW_PREFIX@@/opt/tbb/lib/libtbbmalloc.2.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)

❯ otool -L lib/librkcommon.1.dylib
lib/librkcommon.1.dylib:
	@@HOMEBREW_PREFIX@@/opt/ospray/lib/librkcommon.1.dylib (compatibility version 1.0.0, current version 1.7.0)
	@@HOMEBREW_PREFIX@@/opt/tbb/lib/libtbb.12.dylib (compatibility version 12.0.0, current version 12.3.0)
	@@HOMEBREW_PREFIX@@/opt/tbb/lib/libtbbmalloc.2.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

We do use `-DCMAKE_INSTALL_RPATH=#{rpath}`, so this may not work on ARM.

**Comment by cho-m** [comment]
One possible fix would be changing install dir for resources to use `opt_lib` path rather than `@rpath` via `-DCMAKE_INSTALL_NAME_DIR=#{opt_lib}` 

Not sure if there is a reason why `@rpath` isn't working though. Using `-DCMAKE_INSTALL_RPATH=#{rpath}` results in `-DCMAKE_INSTALL_RPATH=@loader_path/../lib`, so it seems like it should have found it.

Need someone else to comment on this.

**Comment by carlocab** [comment]
Should be fixed now, but `@executable_path` isn't a great choice for an `RPATH` prefix. Opened ospray/ospray#489 to fix that.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
