### PR TITLE
gperf: make keg_only, is provided by macos since Yosemite

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Companion PR in brew: https://github.com/Homebrew/brew/pull/10207

**Comment by carlocab** [comment]
Does it cause problems if it's not `keg_only`? 

My understanding is that that's the motivation behind the other formulae that are `keg_only`. Some of them you actually don't want to make `keg_only`, because you do want the formula to override the one `:provided_by_macos`. Obvious examples here are `python@3.9` and `vim`, though I'm sure there are more.

**Comment by iMichka** [comment]
The list in https://github.com/Homebrew/brew/pull/10207 is quite huge, and I would like to add `gperf` to it. Python is a little bit special as the version provided by brew is not the same as the one provided by macOS. The same for vim. On the other hand this holds true some other keg only formulae. We have not been consistent here and it is probably too late to change it.

How am I supposed to use `uses_from_macos "gperf"` if I can't add it to the list? If I can't, it means that I will need to add:
```
on_linux do
  depends_on "gperf"
end
```

which feels weird as it defines the dependency only for linux, raising the question as to why we do not use brewed gperf for Mac too.

**Comment by carlocab** [comment]
Does anything that is `uses_from_macos` need to be `keg_only`? If so, then perhaps this restriction in `brew` needs to be relaxed a bit. Happy to help look into it if this is the case. I think this might be the right solution anyway, as I imagine there will be other formulae affected. Take `perl`, for instance, which is provided by macOS but is similarly not `keg_only`.

If the above is not an option, I prefer the alternatives of using an `on_linux` block or making brewed `gperf` a dependency on macOS too over making `gperf` `keg_only`. I view a formula becoming `keg_only` as an experience regression. It is, admittedly, a minor one, but I do think we get some pretty loud complaints about minor issues.

**Comment by iMichka** [comment]
I thought I needed to make it keg-only for uses_from_macos, but it's not true. https://github.com/Homebrew/brew/pull/10207 worked without that. Closing here.

**Pull request closed without merging**
