### PR TITLE
knot 2.7.0

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
```
==> /usr/local/Cellar/knot-resolver/2.4.1/sbin/kresd --version
dyld: Library not loaded: /usr/local/opt/knot/lib/libknot.7.dylib
  Referenced from: /usr/local/Cellar/knot-resolver/2.4.1/sbin/kresd
  Reason: image not found
Error: knot-resolver: failed
```
Probably need a `revision` bump there.

**Comment by fxcoudert** [comment]
```
In file included from lib/cache/entry_list.c:21:
/private/tmp/knot-resolver-20180811-26025-45zgt5/knot-resolver-2.4.1/lib/cache/impl.h:26:10: fatal error: 'dnssec/error.h' file not found
#include <dnssec/error.h>
         ^~~~~~~~~~~~~~~~
```

**Comment by lembacon** [comment]
An issue suggesting `knot-resolver` to migrate to `knot` 2.7.0 was opened 3 months ago. https://gitlab.labs.nic.cz/knot/knot-resolver/issues/351

Should probably close this PR for now and hold the `knot` 2.7.0 update until `knot-resolver` addresses this issue.

**Comment by DomT4** [comment]
I'm reluctant to pin `knot` for very long, but there don't seem to be any vulnerabilities fixed with this release so I'm happy to keep it where it is temporarily.

3 months is plenty of time for upstream to offer some response on the `knot-resolver` issue though, and if that drags on much longer we may have to explore alternative solutions.

**Pull request closed without merging**
