### PR TITLE
icmake 8.01.00

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
This is quite broken.

**Comment by apjanke** [comment]
Haha. `icmake` 8.0 added an extra step in its bootstrapping process to provide the equivalent of `$DESTDIR`. And this new `icm_prepare` step looks like it has a bad `find` call.

```
try find -name '*.o' -exec rm -f '{}' \;
```

Maybe it's a GNU-specific syntax? Its `sed` calls used GNU-only stuff.

Not too surprising for `icmake`. It is brittle, and not developed for OS X.

I would say bail on this. AFAIK, the only thing `icmake` is used for in the Homebrew ecosystem is `zsh` development. (Not `zsh` itself, just `zsh` development: their documentation generation uses Yodl, which depends on `icmake`. I might be the only actual Homebrewed `icmake` user. And I still haven't gotten a `yodl` formula running.) Let `icmake` sit at the old 7.x version, and if that becomes an issue, I'd rather ask the `zsh` folks about switching to a different document format than doing ongoing support for icmake/yodl on OS X.

**Comment by ilovezfs** [comment]
@apjanke right, gnu-find does fix that. The even more broken part is actually after that's fixed!

**Comment by apjanke** [comment]
icmake [9.0.0](https://github.com/fbb-git/icmake/releases/tag/9.00.00) got released a couple days ago. Odds are good it has a very different build implementation; maybe it'll work on OS X now if you want to give it another try.

**Comment by apjanke** [comment]
I tried 9.0. Looks similarly broken. Let's just boneyard it. #3487

**Comment by ilovezfs** [comment]
:skull:

**Comment by CNG** [comment]
I'm not super familiar with this, but since building `ssh-cron` [requires `icmake` (>= 8.00.04)](https://github.com/fbb-git/ssh-cron/blob/master/ssh-cron/required), I'm guessing I'm out of luck.

**Comment by apjanke** [comment]
I'm afraid so, unless you can convince `icmake` to provide better BSD support, or inspire someone to patch (or fork) it to do so.

**Pull request closed without merging**
