### PR TITLE
fix android-platform-tools migration path

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
-----
The corresponding cask has been added in https://github.com/caskroom/homebrew-cask/pull/31501

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks again @yurikoles!

**Comment by MikeMcQuaid** [comment]
Will be great when we have this for `android-ndk` too.

**Comment by yurikoles** [comment]
@MikeMcQuaid it's not approved yet, as well as `crystax-ndk`

**Comment by gtklocker** [comment]
I noticed that `android-platform-tools` from Cask got automatically installed when I ran `brew update`, which is really unexpected behaviour and requires no user intervention. ([output](https://gist.github.com/gtklocker/7a789bdd3b94f7eeb5ec07fd1978e507))

However while I had [manually verified the URL and shasum of the old cask](https://github.com/Homebrew/homebrew-core/pull/11468/files#diff-a8cf25419c1c7d406bf8cdd5f16e4caaL8), the new one has a [different link and no checksum at all](https://github.com/caskroom/homebrew-cask/commit/00ad65b19e6ff5c3cdb01fb3b26833880cdda498#diff-76080a65c896f608f66d37222aeed0bbR3). Maybe [this](https://github.com/caskroom/homebrew-cask/pull/31501) shouldn't have been merged, since the option of versioning and also having a checksum as available?

I think at least asking the user before installing a different formula would make sense.

**Comment by MikeMcQuaid** [comment]
> However while I had manually verified the URL and shasum of the old cask, the new one has a different link and no checksum at all. Maybe this shouldn't have been merged, since the option of versioning and also having a checksum as available?
> 
> I think at least asking the user before installing a different formula would make sense.

It's a migration so we're moving users from something we don't support to something we do. We don't prompt users for actions but take the sensible default for the majority.

**Pull request merged**
