### PR TITLE
flint 3.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Needs revbumps

**Comment by chenrui333** [comment]
waiting for this, https://github.com/symengine/symengine/issues/1983, closed the PR for now.

**Comment by chenrui333** [comment]
https://github.com/symengine/symengine/issues/1983 isuse got fixed, gonna retry this PR

**Comment by chenrui333** [comment]
that looks like a brew bug? 

image

**Comment by chenrui333** [comment]
arb failure would be handled in the deprecate PR

**Review by ZhongRuoyu — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks folks! Merging.

**Pull request merged**
