### PR TITLE
erdtree: add shell completion

### PR DESCRIPTION
**Pull request by zuisong**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>### Bug fixes
- Fixed issue where empty directories were automatically being pruned despite not opting into `--prune`.
    - https://github.com/solidiquis/erdtree/issues/185
- Fixed issue where searching via globs or regex doesn't work when user has a config file.

### Other changes:
- Added exit codes to `erdtree`.
- Progress indicator now acquires a lock to `stdout` reduce likelihood of printing the progress-text being a bottleneck.
- Some code-cleanup.

### Pull Requests
- https://github.com/solidiquis/erdtree/pull/183
- https://github.com/solidiquis/erdtree/pull/186
- https://github.com/solidiquis/erdtree/pull/187

### Contributors
- @KP64 

**Full Changelog**: https://github.com/solidiquis/erdtree/compare/v3.0.0...v3.0.1</pre>
</details>

### CODE REVIEW

**Comment by fxcoudert** [comment]
> Created with brew bump-formula-pr

Really?

**Comment by zuisong** [comment]
I manually edit `erdtree.rb`, and change the version to a old version , then run `brew bump-formula-pr --version 3.0.1 erdtree --force`

**Comment by chenrui333** [comment]
> I manually edit `erdtree.rb`, and change the version to a old version , then run `brew bump-formula-pr --version 3.0.1 erdtree --force`
> 
> Do you think there might be any issues with doing this? 🤔

there is no way `bump-formula-pr` would generate such PR :)

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
PR looks good though, thanks @zuisong!

**Pull request merged**
