### PR TITLE
qt 6.0.0

### PR DESCRIPTION
**Pull request by 3719e04**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yhu266** [comment]
work in progress

**Comment by yhu266** [comment]
I underestimated the complexity of `qt`, and I'm afraid I don't have enough knowledge to update it. Closing.

**Comment by jonaski** [comment]
Qt 6 needs to be added alongside Qt 5 as not all programs will be ready for Qt 6.
Is anyone else working on it?
I have built it for Linux and Windows and could possible help.
But I don't know Ruby and too much about homebrew.

**Comment by SMillerDev** [comment]
You could be working on it. As long as you have a copy and a paste key I think you'd be fine for homebrew knowledge.

**Pull request closed without merging**
