### PR TITLE
chapel 1.28.0

### PR DESCRIPTION
**Pull request by bhavanijayakumaran**
This is a new version of chapel formula for chapel 1.28.0 release.
 
Signed-off-by: bhavanijayakumaran <82669529+bhavanijayakumaran@users.noreply.github.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
Let's wait a bit to see how CI at #106925 goes. I don't want to be forced to rebase there since CI takes a long time.

**Comment by bradcray** [comment]
Hi @carlocab — Just to make sure I'm understanding the situation:  Is your hope that the current CI checks on #106925 will pass in the current run, that you'll merge today, and then we'll resolve conflicts between this PR and that one?  If the checks on #106925 do not pass on this run, will this PR be able to proceed, or might it be held off for a few days in favor of #106925?  

(I'm asking from the perspective of how we should phrase our release announcement today w.r.t. homebrew availability and how long I should wait to make that call).

Thanks!

**Comment by bradcray** [comment]
@carlocab / @chenrui333 / @here: From what we're seeing, it looks as though #106925 is not passing its CI (and, happily, not due to any of the Chapel dependencies, at least for the cases I've looked at so far).  That makes me wonder whether we have any chance of getting this merged today (our release day), or whether we need to caveat our release announcement to say "except for homebrew" because it's going to take several more days.  Thanks!

**Comment by carlocab** [comment]
@bradcray your observations are all correct. I've merged this now. Apologies for any delay we've caused your release!

**Comment by bradcray** [comment]
No trouble at all, I definitely understand why waiting would've benefitted that formula.  Sorry that there are still issues to work through, and thanks for merging.  I hadn't quite hit send on my announcement, and am glad to be able to remove the "no homebrew" caveat.  :)

I believe that the changes to the formula here should not be at all difficult to merge into your PR, but please let us know if we can be of any assistance.

**Pull request closed without merging**
