### PR TITLE
logstash 7.16.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
From the [release notes](https://www.elastic.co/guide/en/logstash/7.16/logstash-7-16-0.html):
> Logstash added tests against Java 17 and started supporting JDK 17

We should use `depends_on "openjdk"` which would also unlock ARM bottling.

**Comment by chenrui333** [comment]
> From the [release notes](https://www.elastic.co/guide/en/logstash/7.16/logstash-7-16-0.html):
> 
> > Logstash added tests against Java 17 and started supporting JDK 17
> 
> We should use `depends_on "openjdk"` which would also unlock ARM bottling.

good call

**Comment by carlocab** [comment]
This keeps breaking ARM CI because it leaves directories that `test-bot` isn't able to clean up.

**Comment by chenrui333** [comment]
good to know, I will leave it as it is in here then.

**Comment by chenrui333** [comment]
Closing it for now.

**Pull request closed without merging**
