### PR TITLE
debianutils 4.9

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
See https://github.com/Homebrew/homebrew-core/issues/45514

**Comment by fxcoudert** [comment]
```
run-parts.c:404:21: error: use of undeclared identifier 'O_TMPFILE'
  fd = open(tmpdir, O_TMPFILE|O_RDWR|O_EXCL, S_IRUSR | S_IWUSR);
                    ^
```

**Comment by dawidd6** [comment]
`O_TMPFILE` seems to be not available on macOS. Might need to be patched.

Compare between releases: https://salsa.debian.org/debian/debianutils/compare/debian%2F4.8.6.3...debian%2F4.9

**Comment by fxcoudert** [comment]
I can't find where to file a bug report, though…

**Comment by dawidd6** [comment]
I'll submit the bug report.

**Comment by dawidd6** [comment]
Maintainer proposed this patch:
```diff
+#ifdef O_TMPFILE
+static int open_tmpfile_rw(void)
+{
+       const char *tmpdir;
+
+       tmpdir = getenv("TMPDIR");
+       if (!tmpdir) {
+               tmpdir = "/tmp";
+       }
+
+       return open(tmpdir, O_TMPFILE|O_RDWR|O_EXCL, S_IRUSR | S_IWUSR);
+}
+#else
+static char tmpfile_path[] = "/tmp/run-parts.stdin.XXXXXX";
+static int cleanup_tmpfile(void)
+{
+       unlink(tmpfile_path);
+}
+
+static int open_tmpfile_rw(void)
+{
+       int fd;
+
+       fd = mkstemp(tmpfile_path);
+       if (fd != -1) {
+               atexit(&cleanup_tmpfile);
+       }
+       return fd;
+}
+#endif
+
+
 /*
  * Copy stdin into temporary read-write file, and return file descriptor to it.
  */
@@ -396,15 +429,7 @@ static int copy_stdin(void)
   char buffer[4096];
   ssize_t bytes;

-  tmpdir = getenv("TMPDIR");
-  if (!tmpdir) {
-    tmpdir = "/tmp";
-  };
-
-  fd = open(tmpdir, O_TMPFILE|O_RDWR|O_EXCL, S_IRUSR | S_IWUSR);
-  if (fd < 0) {
-    return -1;
-  };
+  fd = open_tmpfile_rw();

   do {
     ssize_t rest;
```

**Comment by alebcay** [comment]
If/when this gets merged, this will be relevant to #45514.

**Comment by clinty** [comment]
I've released this as debianutils 4.9.1.  It has not been tested on any system without O_TMPFILE

**Comment by dawidd6** [comment]
Superseded by: https://github.com/Homebrew/homebrew-core/pull/47600

**Pull request closed without merging**
