### PR TITLE
ghc: Support sphinx >= 1.8

### LINKED ISSUE #33249: ghc build failure with recent sphinx-doc
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
only warnings

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/timotheecour/7812f64f07b0147b1c39a5e045b8f150

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Not sure whether related to:
* https://github.com/Homebrew/homebrew-core/issues/25568 
* [ghc 8.6.1 by commitay · Pull Request #32342 · Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/32342)

### LINKED ISSUE #33385: ghc failed to build, macOS 10.14 (Mojave)
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/tftio/9ffd8e5cbd1fdb175f81c9e301a9f4ac

- What you were trying to do (and why)

Install `ghc` (as a transitive dependency of `pandoc`)

- What happened (include command output)

It appears to be failing in some `gmp` related build stage? I've included the gist above.

- What you expected to happen

I expected `ghc` to build and install.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install ghc`

### PR DESCRIPTION
**Pull request by mizunashi-mana**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
resolve #33385
resolve #33249  

Include https://github.com/ghc/ghc/commit/a257782f56e5e330349d4cc7db71e297d8396c67 and exclude HTML and PDF documents from build.

### CODE REVIEW

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-core/blob/9285c8dcd62b828136bf9fce7f49348f604c34a9/Formula/gcc%407.rb#L56

Needs a `patch :DATA` for the patch to be applied.

> exclude HTML and PDF documents from build

Why?

**Comment by mizunashi-mana** [comment]
@commitay 
> > exclude HTML and PDF documents from build
> 
> Why?

I thought HTML and PDF usually should be not included, but official GHC package includes them.  So, this is my miss.  Sorry.

I added `patch :DATA`.

**Comment by fxcoudert** [comment]
Instead of using `patch :DATA`, can we use a `patch do` block with the commit diff `https://github.com/ghc/ghc/commit/a257782f.diff?full_index=1`

**Comment by mizunashi-mana** [comment]
@fxcoudert https://github.com/ghc/ghc/commit/a257782f56e5e330349d4cc7db71e297d8396c67 is for GHC 8.6.1 and cannot be straightforward applied for GHC 8.4.x.  I have less knowledge for patching.  Are there any solutions?

**Comment by fxcoudert** [comment]
PL we'll keep the patch as-is then.

**Pull request closed without merging**
