### PR TITLE
agda: add categories library and agda2hs

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Also add access files for the libraries, that the user can then copy to their standard locations.

### CODE REVIEW

**Comment by pthariensflame** [comment]
Ready to run for real!  :shipit:

**Comment by pthariensflame** [comment]
Well, that was a truly stupid typo to have gone unnoticed for so long.

@ZhongRuoyu, this should be ready to go again, for real this time!

**Comment by pthariensflame** [comment]
Tests pass again locally now too.

**Comment by ZhongRuoyu** [comment]
Can you explain a bit more what these changes do and why they are useful for inclusion, @pthariensflame?

**Comment by pthariensflame** [comment]
> Can you explain a bit more what these changes do and why they are useful for inclusion, @pthariensflame?

There are two related changes being made here.

Firstly, two more "standard libraries" are added to the bundle that Agda comes with, along with a helper binary for use with one of them.  We already bundle Agda with the core stdlib and the cubical library, so this is just completing the set of things the Agda organization officially develops for use with it.

Secondly, Agda has recently added a "libraries" facility that makes it smoother to use these things (and third-party ones) rather than having to manually specify the included directories on every invocation of the toolchain.  This change generates `libraries` and `defaults` files for the user to copy to their canonical locations where the toolchain can automatically find them; the generated contents supplies the install locations of all the libraries we now bundle, both the ones just added and the ones we already had.

**Review by ZhongRuoyu — APPROVED** [review]
Thanks @pthariensflame!

**Comment by ZhongRuoyu** [comment]
Test on 12-x86_64 timed out:

```
Timeout::Error: execution expired
```

Can the test be simplified? Technically we can merge this, but this will likely just pop up again in the future.

**Comment by pthariensflame** [comment]
@ZhongRuoyu 
> Test on 12-x86_64 timed out:
> 
> ```
> Timeout::Error: execution expired
> ```
> 
> Can the test be simplified? Technically we can merge this, but this will likely just pop up again in the future.

I'll do my best!

**Comment by pthariensflame** [comment]
I think I've managed it?  We'll see how local tests go.

**Comment by pthariensflame** [comment]
@ZhongRuoyu Should be fine now!  I made the following changes beyond the ones I previously described:
- Shortened one of the tests to make the check time for it lower.
- Moved the installation of some dependencies from test time to build time.
- Passed a flag to make the Agda binary run faster at the cost of additional optimization time during building.

**Review by ZhongRuoyu — APPROVED** [review]
Great work, @pthariensflame!

**Pull request merged**
