### PR TITLE
gpsim 0.32.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> Might be GPL 2.0 or later according to https://gpsim.sourceforge.net/ but that page also wasn't updated since 2017, so it might be good finding a more recent source.

can you also file an upstream issue for the page thing?

**Comment by chenrui333** [comment]
`expected replacement of "#include \"error.h\"" with ""`

**Comment by chenrui333** [comment]
license ref

```
/*
   Copyright (C) 1999 T. Scott Dattalo

This file is part of gpsim.

gpsim is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

gpsim is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with gpsim; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330,
Boston, MA 02111-1307, USA.  */
```

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
I see, I thought the license info on the homepage are outdated, looks like it is not, I need to file another ticket for upstream to fix the license header mismatch issue. :)

**Comment by chenrui333** [comment]
also the source file missing issue is fixed in 0.32.1, https://github.com/Homebrew/homebrew-core/pull/153244

**Comment by chenrui333** [comment]
looks like there is github status reporting issue and we lost some bottles per this PR merge

image

**Comment by chenrui333** [comment]
dispatching a new action run for missing bottles, https://github.com/Homebrew/homebrew-core/actions/runs/6746638476

**Pull request merged**
