### PR TITLE
libpointing 0.9.6

### PR DESCRIPTION
**Pull request by Izzatbek**
Fixed linking errors

### CODE REVIEW

**Comment by DomT4** [comment]
This needs rebasing against an up-to-date master. There's currently a merge conflict.

**Comment by Izzatbek** [comment]
Sorry, but how should I do it? When I try to rebase, it says "Current branch libpointing is up to date."

**Comment by Izzatbek** [comment]
Also, what would be the correct way of doing it each time. Can I just commit newer version of the formula with `git commit -m "Message" --amend` instead of rebasing?

**Comment by Izzatbek** [comment]
OK. I rebased it

**Comment by DomT4** [comment]
Thanks! Was about to leave some advice but I presume you discovered how since you managed it okay 😄.

Merged in https://github.com/Homebrew/homebrew-core/commit/7a2b7503239e20d67330f02b7667c009fa0730f1. Thank you once again 🙇.

**Pull request closed without merging**
