### PR TITLE
workflows: move pull number upload back to `tests.yml`

### PR DESCRIPTION
**Pull request by carlocab**
Our workflows that use this look for it as an upload of `tests.yml`.

### CODE REVIEW

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by Bo98** [comment]
> Our workflows that use this look for it as an upload of `tests.yml`.

It's probably worth changing all that. In fact all that stuff can probably use the event payload instead.

**Comment by carlocab** [comment]
> It's probably worth changing all that at some point. In fact all that stuff can probably use the event payload instead.

We can change it, but AFAICT it will require at least an extra GitHub API call to do.

**Comment by MikeMcQuaid** [comment]
> We can change it, but AFAICT it will require at least an extra GitHub API call to do.

Seems a fine use of the API to me 👍🏻

**Comment by carlocab** [comment]
> We can change it, but AFAICT it will require at least an extra GitHub API call to do.

#133230

**Pull request merged**
