### PR TITLE
subversion 1.10.0

### PR DESCRIPTION
**Pull request by brainy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

* Update subversion.rb for the 1.10.0 release
* Add versioned alias for subversion@1.10

### CODE REVIEW

**Comment by brainy** [comment]
The check failures are caused by a misconfiguration of the test server. It wants to publish JUnit test reports but of course there are no such reports for Subversion.

**Comment by commitay** [comment]
`1.10.0` hasn't been released yet. https://subversion.apache.org/docs/release-notes/1.10.html

**Comment by commitay** [comment]
@brainy Do you intend to use `subversion@1.9` yourself?

**Comment by commitay** [comment]
Let's remove `1.9` from this PR, it can be added later if there is any demand for it.

**Comment by brainy** [comment]
OK

**Comment by commitay** [comment]
Can you squash this down to one commit with the subject `subversion 1.10.0` please?

**Comment by ilovezfs** [comment]
What's with the new dependencies? Are they actually required?

**Comment by brainy** [comment]
@ilovezfs Yes. Subversion has built-in copies of LZ4 and utf8proc for situations where these dependencies are not easily available, but Homebrew does provide standard packages.

Analogy: Subversion could use the amalgamated SQLite sources, but the formula prefers to use Homebrew's version instead.

**Comment by ilovezfs** [comment]
ok

**Comment by brainy** [comment]
Huh, the check failures don't seem to have anything to do with Subversion but with mesos (on Sierra and El Capitan). Is this a test configuration bug?

**Comment by brainy** [comment]
Subversion 1.10.0 release announced:
https://lists.apache.org/thread.html/2f7a0e4a6294aaa5a4c800d20f0bfd183ee2b9657c88dfe92c119a66@%3Cannounce.subversion.apache.org%3E

**Comment by commitay** [comment]
@BrewTestBot test this please

**Comment by commitay** [comment]
Thanks @brainy!

**Pull request closed without merging**
