### PR TITLE
po4a 0.59.1 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This formula will fail the notability audit because the source is hosted on GitHub, although as far as I can tell, the project predates GitHub's existence.

This would probably be helpful for #56969.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> brew linkage --test po4a
==> FAILED
Broken dependencies:
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
```

Hmm

**Comment by alebcay** [comment]
Looks like `gettext` needs to be an all-around dependency, not just `:build`.

**Comment by SMillerDev** [comment]
Do any Linux distributions ship it?

**Comment by chenrui333** [comment]
> Do any Linux distributions ship it?

Yeah, it does.
https://repology.org/project/po4a/versions

**Review by dawidd6 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
side note, failed on notability check

**Pull request closed without merging**
