### PR TITLE
enonic 0.3 (new formula)

### PR DESCRIPTION
**Pull request by pmi**
This PR adds a formula for the [enonic](http://www.enonic.com) cli tool

### CODE REVIEW

**Review by mistydemeo — CHANGES_REQUESTED** [review]
We don't accept prebuilt binaries. Is this tool open-source?

**Comment by alansemenov** [comment]
@mistydemeo yes, it's an open-source CLI tool.

**Comment by pmi** [comment]
@mistydemeo Here's the link to the sources https://github.com/enonic/enonic-cli

**Comment by SMillerDev** [comment]
> @mistydemeo Here's the link to the sources https://github.com/enonic/enonic-cli

You'll have to make it so that it compiles from source then.

**Comment by pmi** [comment]
@SMillerDev We use goreleaser for binaries compilation. The process is documented on https://github.com/enonic/enonic-cli.
Let me know If you have any specific requirements regarding build process.

**Comment by SMillerDev** [comment]
> @SMillerDev We use goreleaser for compilation from source. The process is documented on https://github.com/enonic/enonic-cli.
> Let me know If you have any specific requirements regarding build process.

that's fine but homebrew only ships prebuilt binaries in the caskroom. You'll either have to make this formula build from source or make it a cask instead.

**Comment by SMillerDev** [comment]
Actually, I just checked and the software isn't released under any known OSI License so it'll have to be made into a tap either way as homebrew-core only ships OSI licensed software. (see https://docs.brew.sh/Acceptable-Formulae)

**Pull request closed without merging**
