### PR TITLE
giflib 4->5 migration, part 1

### PR DESCRIPTION
**Pull request by fxcoudert**
Creating a new `giflib@4` formula for `swftools`, which depends on that version.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Looking good to me.

**Comment by ilovezfs** [comment]
We may be able to avoid adding `giflib@4` altogether. What're the analytics on those two? Have you tried to fix their issues with giflib 5? Were those issues with giflib 5 reported upstream? Has upstream responded? etc.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Let's not add a new versioned formula we're not already providing and no one has asked for unless we have to and it meets the guidelines for versioned formulae.

**Comment by fxcoudert** [comment]
We are already providing giflib 4 anyway (see #12061), the goal here is to change which is the default version and which is the versioned formula.

- `swftools` and `pdf2htmlex` both get decent numbers of installs, so we can't just throw them out.
- Both appear to have very slow development.
- Giflib 5 support was [added to `swftools` in 2013](http://lists.nongnu.org/archive/html/swftools-common/2013-06/msg00004.html) but there was no release since then.
- I have reported the issue to `pdf2htmlex`: https://github.com/coolwanglu/pdf2htmlEX/issues/713

**Pull request closed without merging**
