### PR TITLE
micro 1.3.3

### PR DESCRIPTION
**Pull request by zyedidia**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
/usr/local/Cellar/micro/1.3.3/bin/micro -version
Error: micro: failed
</1\.3\.3/> expected to be =~
<"Version: 1.3.4\nCommit hash: a02ae3c\nCompiled on September 29, 2017\n">.
```

**Comment by zyedidia** [comment]
Oops sorry it's hopefully fixed now.

@BrewTestBot test this please

**Comment by zyedidia** [comment]
@BrewTestBot test this please

**Comment by zyedidia** [comment]
Sorry I re-uploaded the tarballs but forgot the `-src` but then I forgot to change the shasum...

@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @zyedidia! Shipped! Just FYI: BrewTestBot won't respond unless the person addressing it is a maintainer. You can achieve the same effect by rebasing and force pushing.

**Comment by zyedidia** [comment]
Oh really? The brew test bot did re-test the formula for me a number of times. Anyway I'll keep your tip about rebasing and force pushing in mind. Thanks!

**Pull request closed without merging**
