### PR TITLE
crytic-compile 0.3.5

### PR DESCRIPTION
**Pull request by elopez**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you split this into two PRs please

**Comment by elopez** [comment]
Hi @SMillerDev! slither-analyzer 0.10.0 depends on crytic-compile >=0.3.5, so that's why I opted to keep both on the same PR. Would you prefer I drop the slither commit from here and wait for this PR to be merged before opening the other PR?

https://github.com/crytic/slither/blob/0.10.0/setup.py#L18

**Comment by SMillerDev** [comment]
Yes, since, besides being against the standards, I don't think our merge system will be able to handle 3 commits for 2 files

**Comment by elopez** [comment]
@SMillerDev sounds good! I left just the crytic-compile commits in now 👍

**Review by SMillerDev — DISMISSED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
