### PR TITLE
ghostscript 9.26

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
`libspectre` and `pqiv` requires revision bumps.

**Comment by lembacon** [comment]
@BrewTestBot this this please

**Comment by lembacon** [comment]
```
17:47:24 ==> brew install --only-dependencies gv
17:47:25 ==> FAILED
17:47:25 Error: ghostscript is already installed from !
17:47:25 Please `brew uninstall ghostscript` first."
17:47:25 ==> Installing dependencies for gv: ghostscript
17:47:25 
17:47:25 ==> brew install gv
17:47:27 ==> FAILED
17:47:27 Error: ghostscript is already installed from !
17:47:27 Please `brew uninstall ghostscript` first."
17:47:27 ==> Installing dependencies for gv: ghostscript
```

This is weird, let's try again. 🙃

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Merged. Tested manually, and `gv` is okay.

**Pull request closed without merging**
