### PR TITLE
kubebuilder 3.8.0

### PR DESCRIPTION
**Pull request by Moulick**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
HI @Moulick,

The release was made feel free to update the formula and move forward within.

**Comment by Moulick** [comment]
Will need someone to trigger a re-run of the CI

**Comment by chenrui333** [comment]
> Will need someone to trigger a re-run of the CI, I don't think I have the permissions to do so

yeah, the PR rebase would auto-trigger a new PR build 👍

**Review by chenrui333 — APPROVED** [review]

**Comment by Moulick** [comment]
Is there no way for the PR author to trigger the recheck apart from rebasing or adding more commits?

**Pull request closed without merging**
