### PR TITLE
kubernetes-cli 1.16.0

### PR DESCRIPTION
**Pull request by mikesplain**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
13:43:15 go/build: importGo k8s.io/kubernetes: exit status 1
13:43:15 can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes
13:43:15 
13:43:15 
13:43:15 +++ [0918 18:42:30] Building go targets for darwin/amd64:
13:43:15     ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
13:43:15 go: finding k8s.io/kubernetes/vendor/k8s.io latest
13:43:15 go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd latest
13:43:15 go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator latest
13:43:15 go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen latest
13:43:15 go: finding k8s.io/kubernetes/vendor latest
13:43:15 can't load package: package k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen: no matching versions for query "latest"
13:43:15 !!! [0918 18:43:10] Call tree:
13:43:15 !!! [0918 18:43:10]  1: /private/tmp/kubernetes-cli-20190918-47463-1is533u/src/k8s.io/kubernetes/hack/lib/golang.sh:714 kube::golang::build_some_binaries(...)
13:43:15 !!! [0918 18:43:10]  2: /private/tmp/kubernetes-cli-20190918-47463-1is533u/src/k8s.io/kubernetes/hack/lib/golang.sh:853 kube::golang::build_binaries_for_platform(...)
13:43:15 !!! [0918 18:43:10]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
13:43:15 make[1]: *** [_output/bin/deepcopy-gen] Error 1
13:43:15 make: *** [generated_files] Error 2

**Comment by mikesplain** [comment]
Looking into this now, we likely need to use go 1.12 since go 1.13 is now default.

**Comment by mikesplain** [comment]
Converting this into a non-brew bump pr

**Comment by mikesplain** [comment]
Thanks @chenrui333, should be good to go now.

**Review by chenrui333 — APPROVED** [review]
lgtm

**Comment by chenrui333** [comment]
@mikesplain Thanks for finding it out.

**Pull request closed without merging**
