### PR TITLE
pgroonga 1.1.9

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> ilovezfs added the do not merge label 2 days ago

Why, out of interest? Not disagreeing but just for reference.

**Comment by ilovezfs** [comment]
This should be completed first: https://github.com/Homebrew/homebrew-core/pull/7310

**Comment by MikeMcQuaid** [comment]
🙆‍♂️

**Comment by ilovezfs** [comment]
:rocket:

**Pull request closed without merging**
