### PR TITLE
sbcl: add RPATH for Monterey `pgloader` build

### LINKED ISSUE #103273: pgloader won't install on macOS Monterey (M1)
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs pgloader
Error: Not Found

% brew config
HOMEBREW_VERSION: 3.5.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2258ba5797c1ea8149a49673b5c080011c366237
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 87f5c3bf311f07f5c94fb5dba009224196c13136
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  protobuf
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

attempted to install pgloader

### What happened (include all command output)?

% brew install pgloader
Error: pgloader: no bottle available!
You can try to install from source with:
  brew install --build-from-source pgloader
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

% brew install --build-from-source pgloader
==> Downloading https://github.com/dimitri/pgloader/releases/download/v3.6.2/pgloader-bundle-3.6.2.tgz
Already downloaded: /Users/anullvalue/Library/Caches/Homebrew/downloads/2a1b2485b3a52a8aa90117254bcc5b1701cd81cc53b0e6f1c16900b1d967f948--pgloader-bundle-3.6.2.tgz
==> Patching
==> make
Last 15 lines from /Users/anullvalue/Library/Logs/Homebrew/pgloader/01.make:
                         --load local-projects/pgloader-3.6.2/src/hooks.lisp              \
                         --load-system pgloader                    \
                         --eval '(setf pgloader.params::*version-string* "3.6.2")' \
                         --entry pgloader:main                        \
                         --dynamic-space-size 4096              \
                         --compress-core                         \
                         --output bin/pgloader.tmp
;; loading system "cffi"
;; loading system "cl+ssl"
WARNING: /opt/homebrew/Cellar/sbcl/2.2.5/libexec/bin/sbcl is loading libcrypto in an unsafe way
fatal error encountered in SBCL pid 29817 pthread 0x101078580:
SIGABRT received.

   0:     0x21b9022e8 pc=0x19c4b4db0  BAD FRAME
make: *** [bin/pgloader] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

### What did you expect to happen?

pgloader to be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install pgloader
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The `pgloader` build fails because `sbcl` tries to dynamically load the system `libssl`, which is poisoned. Let's convince it to look for Homebrew OpenSSL instead.

Fixes #103273.

### CODE REVIEW

**Comment by carlocab** [comment]
Nope, that didn't work. Adding an `RPATH` seems to have broken `sbcl`. Let's see if something else works...

**Comment by cho-m** [comment]
I think `pgloader` needs a newer `cl+ssl`. Current tarball packages `cl+ssl-20191130` which has search paths for:
```lisp
  (:darwin (:or "/opt/local/lib/libssl.dylib" ;; MacPorts
                "/sw/lib/libssl.dylib"        ;; Fink
                "/usr/local/opt/openssl/lib/libssl.dylib" ;; Homebrew
                "/usr/local/lib/libssl.dylib" ;; personalized install
                "libssl.dylib"                ;; default system libssl, which may have insufficient crypto
                "/usr/lib/libssl.dylib"))
```

Newer commits have some extra logic (https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/reload.lisp#L147-L151):
```lisp
    ((:and :darwin :cl+ssl-macports-found) "/opt/local/lib/libssl.dylib")
    ((:and :darwin :cl+ssl-fink-found) "/sw/lib/libssl.dylib")
    ((:and :darwin :cl+ssl-homebrew-found) "/usr/local/opt/openssl/lib/libssl.dylib")
    ((:and :darwin :cl+ssl-homebrew-arm64-found) "/opt/homebrew/opt/openssl/lib/libssl.dylib")
    ((:and :darwin :cl+ssl-personalized-install-found) "/usr/local/lib/libssl.dylib")
```

You could try downloading newer version and replacing or hacking it with
```rb
    inreplace "software/cl+ssl-20191130-git/src/reload.lisp",
              "/usr/local/opt/openssl/lib",
              Formula["openssl@1.1"].opt_lib
```

**Comment by cho-m** [comment]
New `pgloader` #104688 includes newer `cl+ssl` that no longer hits issue and has at least built on ARM Monterey.

**Comment by cho-m** [comment]
Closing this as #104688 merge included Monterey and ARM bottles https://github.com/Homebrew/homebrew-core/commit/efc08588a90c5e96a485dc7fccc1a40448b0fd7f

If you feel there is still something off about `sbcl` you can reopen.

**Comment by carlocab** [comment]
Well, it would be nice for `sbcl` to find a Homebrew OpenSSL whenever it tries to dynamically load `libssl` -- but no idea how to fix that.

**Pull request closed without merging**
