### PR TITLE
siril 1.2.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /private/tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.h:27:9: error: function definition does not declare parameters
      Key currange[2] { 0 }; /* Low and High */
          ^
  /private/tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.h:16:25: error: use of undeclared identifier 'currange'
          range->getNext(&currange[0], &currange[1]);
                          ^
  /private/tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.h:16:39: error: use of undeclared identifier 'currange'
          range->getNext(&currange[0], &currange[1]);
                                        ^
  /private/tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.h:17:19: error: use of undeclared identifier 'currange'
          nextval = currange[0] - 1;
                    ^
  /tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.cpp:17:9: error: use of undeclared identifier 'currange'
      if (currange[0] <= 0)
          ^
  /tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.cpp:23:19: error: use of undeclared identifier 'currange'
      if (nextval > currange[1])
                    ^
  /tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.cpp:25:25: error: use of undeclared identifier 'currange'
          range->getNext(&currange[0], &currange[1]);
                          ^
  /tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.cpp:25:39: error: use of undeclared identifier 'currange'
          range->getNext(&currange[0], &currange[1]);
                                        ^
  /tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.cpp:26:13: error: use of undeclared identifier 'currange'
          if (currange[0] <= 0)
              ^
  /tmp/siril-20230916-16980-b1y5ob/siril-1.2.0/subprojects/htmesh/HtmRangeIterator.cpp:31:19: error: use of undeclared identifier 'currange'
          nextval = currange[0];
                    ^
  10 errors generated.
```

**Comment by p-linnane** [comment]
Upstream [recommends `meson`](https://siril.readthedocs.io/en/stable/installation/source.html#meson) now, so we might want to try that out as well.

**Comment by chenrui333** [comment]
raise an upstream report, https://gitlab.com/free-astro/siril/-/issues/1196

**Comment by chenrui333** [comment]
let's close it for now. Upstream shared some insights, i will have to check later.

> As you can see here: https://gitlab.com/free-astro/siril/-/pipelines/1005535362
All pipelines work well (on macOS or Linux or Windows). For me this is an issue on your side. What could be the difference between homebrew env and a native env.?
Then, I can build with homebrew on my side.

**Pull request closed without merging**
