### PR TITLE
mysql mysql-client 8.0.28

### PR DESCRIPTION
**Pull request by yahonda**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yahonda** [comment]
#93711 and #93710 depend on each other. Let me push the commit [e1edf71ca698901316a8f07e67128fad536495c4](https://github.com/Homebrew/homebrew-core/pull/93710/commits/e1edf71ca698901316a8f07e67128fad536495c4) to this pull request.

**Comment by carlocab** [comment]
Can you split your last commit into two? @BrewTestBot can't merge PRs with commits that modify multiple formulae (or PRs with merge commits). That's why there's an `automerge-skip` label.

Thanks!

**Comment by yahonda** [comment]
Thanks for the comment.

The reason why I have modified two mysql and mysql-client formulaes by one pull request is 
CI raises these error, it looks like both mysql-client and mysql should be the same version.

https://github.com/Homebrew/homebrew-core/runs/4923607880?check_suite_focus=true#step:4:25

```
Error: Version of `mysql-client` (8.0.28) should match version of `mysql` (8.0.27)
Error: Version of `mysql` (8.0.27) should match version of `mysql-client` (8.0.28)
```

Still, do I need to split these two commits into separate pull request?

**Comment by carlocab** [comment]
No, please keep them in this pull request. By split the commit, I mean split the commit into two commits in this pull request.

This pull request can (and should) update both formulae, but each commit in this pull request should modify only at most one formula file.

**Comment by yahonda** [comment]
> This pull request can (and should) update both formulae, but each commit in this pull request should modify only at most one formula file.

Sure. Understood.

**Review by carlocab — APPROVED** [review]
Thanks, @yahonda!

**Pull request closed without merging**
