### PR TITLE
libheif 1.17.4

### PR DESCRIPTION
**Pull request by timsutton**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Linux failure
```
  Error: Failure while executing; `/usr/bin/env cp -pR /tmp/d20231121-224515-1nwhp4j/texlive/. /home/linuxbrew/.linuxbrew/Cellar/texlive` exited with 1. Here's the output:
  cp: error writing '/home/linuxbrew/.linuxbrew/Cellar/texlive/20230313_2/share/texmf-dist/source/latex/rcsinfo/rcsinfo.dtx': No space left on device
```

**Comment by chenrui333** [comment]
> Linux failure is pre-exisiting - [#151812 (comment)](https://github.com/Homebrew/homebrew-core/pull/151812#issuecomment-1774114118)
> 
> ```
>   Error: Failure while executing; `/usr/bin/env cp -pR /tmp/d20231121-224515-1nwhp4j/texlive/. /home/linuxbrew/.linuxbrew/Cellar/texlive` exited with 1. Here's the output:
>   cp: error writing '/home/linuxbrew/.linuxbrew/Cellar/texlive/20230313_2/share/texmf-dist/source/latex/rcsinfo/rcsinfo.dtx': No space left on device
> ```

yeah, it needs self-hosted linux runner for such build.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
I will followup with a texlive regression run.

**Comment by chenrui333** [comment]
passed by regression check, https://github.com/chenrui333/github-action-test/actions/runs/6945170597/job/18893916632

**Pull request merged**
