### PR TITLE
visp 3.4.0

### PR DESCRIPTION
**Pull request by morusn**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by morusn** [comment]
[https://visp.inria.fr/visp-license/](url)
```
ViSP is released under a dual licensing model. It is open-source with a GNU GPLv2 license. A professional edition license that replace GNU GPLv2 is also available. Don’t hesitate to contact visp@inria.fr if you have questions about our licensing model.

GNU GPL v2 or later license
This license is appropriate for the development of applications where you wish to use ViSP in combination with software subject to the terms of the GNU General Public License version 2 or later or where you are otherwise willing to comply with the terms of the GNU General Public License version 2 or later.

```

**Comment by fspindle** [comment]
Not easy to fix this build issue without having access to such a machine.

But I think that the following patch could work. Is there someone that can try ?

```
$ more 11-arm.patch 
diff --git a/3rdparty/simdlib/Simd/SimdEnable.h b/3rdparty/simdlib/Simd/SimdEnable.h
index a5ca71702..6c79eb0d9 100644
--- a/3rdparty/simdlib/Simd/SimdEnable.h
+++ b/3rdparty/simdlib/Simd/SimdEnable.h
@@ -44,8 +44,8 @@
 #include <TargetConditionals.h>             // To detect OSX or IOS using TARGET_OS_IPHONE or TARGET_OS_IOS macro
 #endif
 
-// The following includes <sys/auxv.h> and <asm/hwcap.h> are not available for iOS.
-#if (TARGET_OS_IOS == 0) // not iOS
+// The following includes <sys/auxv.h> and <asm/hwcap.h> are not available for macOS, iOS.
+#if !defined(__APPLE__) // not macOS, iOS
 #if defined(SIMD_PPC_ENABLE) || defined(SIMD_PPC64_ENABLE) || defined(SIMD_ARM_ENABLE) || defined(SIMD_ARM64_ENABLE)
 #include <unistd.h>
 #include <fcntl.h>
@@ -124,7 +124,7 @@ namespace Simd
     }
 #endif//defined(SIMD_X86_ENABLE) || defined(SIMD_X64_ENABLE)
 
-#if (TARGET_OS_IOS == 0) // not iOS
+#if !defined(__APPLE__) // not macOS, iOS
 #if defined(__GNUC__) && (defined(SIMD_PPC_ENABLE) || defined(SIMD_PPC64_ENABLE) || defined(SIMD_ARM_ENABLE) || defined(SIMD_ARM64_ENABLE))
     namespace CpuInfo
     {
```

**Comment by carlocab** [comment]
Thanks for the suggestion, @fspindle. I tried applying the patch. Let's see if it helps.

**Comment by carlocab** [comment]
The patch worked. Thanks, @fspindle.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
