### PR TITLE
wpcli-completion: mirror to Bintray

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by yurikoles** [comment]
Related issue: #28579. Without this change formula isn't installable.

**Comment by ilovezfs** [comment]
use the mirror from the main formula

**Comment by yurikoles** [comment]
@ilovezfs it's impossible, because it only provides phar, this formula is for bash-completion which is only in source code.

**Comment by yurikoles** [comment]
Maybe we should use git with tag directly?

**Comment by ilovezfs** [comment]
ah ok. here you go https://dl.bintray.com/homebrew/mirror/wpcli-completion-1.5.1.tar.gz

**Comment by yurikoles** [comment]
@ilovezfs maybe we should provide a bottle to avoid this issue?

**Comment by ilovezfs** [comment]
The issue is that upstream regtagged. Hopefully it will not recur. Using the mirror + bottle unneeded is fine. There is no reason for a revision bump since nothing has changed :)

**Comment by yurikoles** [comment]
@ilovezfs rebased

**Comment by ilovezfs** [comment]
Thanks again @yurikoles!

**Comment by yurikoles** [comment]
@ilovezfs you are welcome :)

**Pull request merged**
