### PR TITLE
uriparser 0.9.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by hartwork — CHANGES_REQUESTED** [review]
Hi! I noticed it still says `cpptest` while the test suite is using gtest >=1.8.1 now.

**Comment by apjanke** [comment]
Build failed. Looks like gtest is required, not optional, and will need to be vendored in to the formula now.

```
checking for GTEST... no
configure: error: Please install Googletest 1.8.1 or later.
			Alternatively, you could pass --disable-test to the call to configure.
			However, it is not recommended to disable the test suite.
```

**Comment by apjanke** [comment]
Here's a PR that vendors in gtest: https://github.com/Homebrew/homebrew-core/pull/33501

**Comment by hartwork** [comment]
> Build failed. Looks like gtest is required, not optional, and will need to be vendored in to the formula now.

Why not optional? Is `--disable-test` not working?

**Comment by apjanke** [comment]
> Why not optional? Is --disable-test not working?

`--disable-test` is working fine; I just figured we didn't want to use it since the build script says it's "not recommended", and Homebrew likes to have some tests as long as they're not too expensive in terms of build time. I guess I meant "required if you want to keep the make test enabled".

Anyway, I got it working in that PR, and IMHO I think it's better to have the test than not. Could be a good reference for other formulae that need a vendored gtest, too.

**Comment by hartwork** [comment]
> Could be a good reference for other formulae that need a vendored gtest, too.

I see vendoring as a workaround, as a (maybe less evil than usual since it's test rather than production code, but still a) flavor of bundling dependencies. Is packaging gtest 1.8.1 not an option? Everyone could depend on that package then.

**Comment by apjanke** [comment]
I went with vendoring/bundling it because [brew's `missing_formula.rb` says to do so here](https://github.com/Homebrew/brew/blob/cbb2e1b3dd63e1b9621c67b619aad8c914772041/Library/Homebrew/missing_formula.rb#L41-L44).

Here's what looks like the rationale for the choice in gtest's case (found by searching for "googletest" in the brew and legacy-homebrew repos). 
https://github.com/Homebrew/legacy-homebrew/pull/46929
https://github.com/Homebrew/legacy-homebrew/issues/25791
https://github.com/Homebrew/legacy-homebrew/pull/16551

Looks like GoogleTest itself recommends the vendoring approach. Homebrew typically defers to upstream.

And that last PR got me to a concrete explanation here:
https://github.com/fuchsia-mirror/third_party-googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal

So, it's C++ ABI and compiler-option compatibility stuff. And yeah, you don't want to futz around with that.

So, no. It does not sound like packaging gtest (of any version) is an option, and everybody's gotta vendor.

**Comment by apjanke** [comment]
We oughta write this up as a FAQ or something. Googling "Homebrew googletest" produces no useful results, and that ain't right, for something so specific.

**Comment by hartwork** [comment]
> https://github.com/fuchsia-mirror/third_party-googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal

Interesting link, thanks. Debian and Gentoo have packaged it and linking against the system-wide version works well for me despite different compile flags and despite different compiler for me. I get that that cannot prove absence of problems for all cases and everyone.

**Comment by hartwork** [comment]
Mentioned section `Why is it not recommended to install a pre-compiled copy of Google Test (for example, into /usr/local)?` was removed from the _upstream_ docs in this commit https://github.com/google/googletest/commit/5437926b2213b1c45c2f34bd858734de90e5fffd#diff-c07107b4d3c5447d005aa4969d54f34bL97 that is included in gtest 1.8.1. gtest changed quite a bit over time it seems, older versions up to 1.8.0(!) did not even have a `.a` file to link against ([see Debian stretch file listing](https://packages.debian.org/stretch/amd64/googletest/filelist)). Maybe it was all-headers before and mentioned issues no longer exist?

@gennadiycivil could you shed some light why that paragraph was dropped from the docs?

**Comment by gennadiycivil** [comment]
@hartwork This was most probably a victim of a massive merge I was performing at that time. This section should be there. Thank you for noticing

**Pull request closed without merging**
