### PR TITLE
awsume 4.2.6

### PR DESCRIPTION
**Pull request by GabriellaXue**
bump the version

### CODE REVIEW

**Comment by brettkoonce** [comment]
see #50898

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@GabriellaXue Thanks for your contribution to Homebrew! 🎉 🥇

**Comment by chenrui333** [comment]
Trying to upgrade python dep to python 3.8.
https://github.com/trek10inc/awsume/blob/master/setup.py#L42

relates to https://github.com/Homebrew/homebrew-core/issues/47274

**Pull request closed without merging**
