### PR TITLE
libgsm 1.0.19

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
@alebcay This formula still carries an old patch around, which builds libgsm.1.0.13.dylib. This does not correspond to the 1.0.19 version. Also the comments reads: Builds a dynamic library for gsm, this package is no longer developed upstream.

Did you do this update based on a regular version bump / livecheck bump? Or do you follow this project in particular. I would like to get rid of that patch, and see if upstream could help us.

**Comment by Bo98** [comment]
> I would like to get rid of that patch, and see if upstream could help us.

I've yet to see a repository not carry that patch. I don't know why upstream doesn't want to accept it.

**Comment by iMichka** [comment]
I sent them an email with the patch.

**Comment by alebcay** [comment]
> Did you do this update based on a regular version bump / livecheck bump?
Just to follow up, this was a livecheck bump.

**Comment by iMichka** [comment]
I wrote to upstream, and they were not confortable to maintain this patch by themselves. This does not seem to be a supported configuration, as they can not test the shared libraries build and usage.

As there has not been any development done on the project for the last 20 years, and nothing new is planned for it in the next 20 years, they consider that if we want to use the patch, we can just continue to ship it and maintain it.

**Pull request closed without merging**
