### PR TITLE
liquidprompt 2.0.4

### PR DESCRIPTION
**Pull request by augmentedfourth**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
>   ==> /bin/sh -c '. /home/linuxbrew/.linuxbrew/share/liquidprompt --no-activate; lp_theme --list'
  /bin/sh: 1: lp_theme: not found
  Error: test failed

**Comment by iMichka** [comment]
The last update for this formula was more than 6 months ago. Since the we added the Linux tests and made them mandatory. Some formulae (like this one) might have a broken test due to this. The goal is to fix all these broken tests slowly over time.

How does this `lp_theme` thing work?

**Comment by augmentedfourth** [comment]
Liquidprompt isn't an executable; it's a shell script that gets sourced in your environment to modify your prompt. The test command sources the script and makes sure the `lp_theme` function has been defined.

I used the 2.0.4 tarball and manually ran the command from the test on an Ubuntu Server 20.04 host I run, and it succeeded. I'm not sure what's going on, and I'd like to request that it be re-run.

**Comment by augmentedfourth** [comment]
Huh. So it seems that it works if I run the script directly in the shell:
```
$ . ./liquidprompt --no-activate; lp_theme --list
default
tritone@augmentedfourth:~/liq_204/liquidprompt-2.0.4$ echo $?
0
```

But it doesn't work if I run it as a command to `/bin/sh`:
```
$ /bin/sh -c '. ./liquidprompt --no-activate; lp_theme --list'
/bin/sh: 1: lp_theme: not found
```

I think it might be because Ubuntu aliases `/bin/sh` to `dash`, which may not be supported by liquidprompt.

**Comment by augmentedfourth** [comment]
OK, I fixed the test and it passes now in all builds.

**Review by nandahkrishna — APPROVED** [review]
Thanks, @augmentedfourth!

**Pull request closed without merging**
