### PR TITLE
typewritten 1.4.6 (new formula)

### PR DESCRIPTION
**Pull request by danielbayley**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielbayley** [comment]
No idea why this `test` is failing… it works locally on my macOS 12.3.1.

**Comment by chenrui333** [comment]
I can reproduce the issue on my m1 (macos 12.4)

**Comment by danielbayley** [comment]
> I can reproduce the issue on my m1 (macos 12.4)

Ah well I don’t have an M1 yet… How to resolve?

**Comment by danielbayley** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

@chenrui333 Any ideas?

**Comment by danielbayley** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

@chenrui333 Any ideas?

**Comment by danielbayley** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

@chenrui333 Any ideas?

**Comment by fxcoudert** [comment]
The error is:

```
Error: typewritten: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /❯/ to match "\e[39m\e[49m\nUnknown theme: typewritten\n\e[39m\e[49m\n".
```

so clearly the zsh test fails and outputs `Unknown theme: typewritten`. Probably typewritten is installed in a location where it is not found?

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
