### PR TITLE
imagemagick@6 6.9.7-5

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

Please remember to
```
brew mirror imagemagick@6
```
when merging.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Looks like the mirror URL is bogus as can be.

**Comment by zmwangx** [comment]
Yeah forgot to percent-encode. Fixed. Not sure whether brew-mirror/bintray handles percent-encoding though.

**Comment by ilovezfs** [comment]
I guess it's possible it's right. Let's find out lol

**Comment by ilovezfs** [comment]
Looks like both

https://dl.bintray.com/homebrew/mirror/imagemagick%406-6.9.7-5.tar.xz
https://dl.bintray.com/homebrew/mirror/imagemagick@6-6.9.7-5.tar.xz

work. No idea which we "should" standardize.

**Comment by zmwangx** [comment]
RFC 3986 says @ belongs to gen-delims and should be percent-encoded, so I'd go with %40. But it's ugly as hell.

**Comment by ilovezfs** [comment]
```
[joe:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula] master+ ± brew pull https://github.com/Homebrew/homebrew-core/pull/9135
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/9135.patch
==> Applying patch
Applying: imagemagick@6 6.9.7-5
Warning: imagemagick@6 has a bottle: do you need to update it with --bottle?
==> Patch closes issue #9135
==> Patch changed:
 Formula/imagemagick@6.rb | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
[joe:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula] master(1)+ 5s ± brew mirror imagemagick@6
{"name":"imagemagick:6","repo":"mirror","owner":"homebrew","desc":null,"labels":[],"attribute_names":[],"licenses":[],"custom_licenses":[],"followers_count":0,"created":"2017-01-21T16:30:22.011Z","website_url":null,"issue_tracker_url":null,"github_repo":"","github_release_notes_file":"","public_download_numbers":true,"public_stats":true,"linked_to_repos":[],"versions":[],"latest_version":null,"updated":"2017-01-21T16:30:22.025Z","rating_count":0,"system_ids":[],"vcs_url":null,"maturity":""}
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick%406-6.9.7-5.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www.imagemagick.org/download/ImageMagick-6.9.7-5.tar.xz
######################################################################## 100.0%
==> Uploading to https://dl.bintray.com/homebrew/mirror/imagemagick@6-6.9.7-5.tar.xz
{"message":"success"}```

If we do go with %40, it looks like `brew pull` should be changed to print that.

**Comment by zmwangx** [comment]
Switched back to `@6` for the least amount of work possible.

**Comment by ilovezfs** [comment]
hehe ok

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
:trophy:

**Pull request closed without merging**
