### PR TITLE
mesos 1.3.0

### PR DESCRIPTION
**Pull request by mpark**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
See https://issues.apache.org/jira/browse/MESOS-7583. We may need to remove mesos from Homebrew.

**Comment by ilovezfs** [comment]
@mpark any news here?

**Comment by mpark** [comment]
@ilovezfs: I've asked around and we haven't really had time to look into it. Do you want me to close this until we get around to looking at it?

**Comment by ilovezfs** [comment]
@mpark it can stay open. Just curious: how is upstream building this on Sierra …

**Comment by mpark** [comment]
Okay, I'm on vacation for a couple of weeks so I'll only be able to get back to this afterwards.

**Comment by ilovezfs** [comment]
@mpark interestingly, the failure does not occur if I use Xcode 9 beta 3.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @mpark! Shipped!

**Pull request closed without merging**
