### PR TITLE
fftw: build with cmake to workaround its issue 130

### PR DESCRIPTION
**Pull request by huiyiqun**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The `brew audit --strict <formula>` failed actually, but that's not caused by this pull request.

Building fftw with cmake workarounds https://github.com/FFTW/fftw3/issues/130.

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
What gets installed has changed significantly between the two builds:
https://gist.github.com/ilovezfs/8ddf18a2f5c445e2fe72e72851afdf24

a) the programs in `bin` are gone
b) the man pages are gone
c) the static libraries are gone
d) the library version numbers changed

(d) could be remedied by revision bumping the reverse the dependencies.

The others would need formula changes or upstream changes to iron out.

Also, I think we'll need to consult with upstream about which build system they'd recommend package managers use.

**Comment by huiyiqun** [comment]
I've just investigated the CMakeLists.txt, but (a) (b) and (c) seem impossible to solve without upstream changes.

**Comment by ilovezfs** [comment]
(c) can be fixed by building twice. See https://github.com/Homebrew/homebrew-core/blob/24a2af9a0bdd8b8c269b57ddbee67c0cf8ba9748/Formula/snappy.rb#L25-L31

**Comment by huiyiqun** [comment]
@ilovezfs No, we can't.

There is no static library generated even if I let `BUILD_SHARED_LIBS=off`

**Comment by ilovezfs** [comment]
Ah OK. Yes there would need to be upstream support for building statics libraries, which is usually present, but I guess not here.

We're going to pass on this PR as it looks like the recommended build system for a complete and correct build is Autotools. Thanks, nonetheless!

**Pull request closed without merging**
