### PR TITLE
CGAL: Upgrade to 5.2

### PR DESCRIPTION
**Pull request by maxGimeno**
Upgrade CGAL to version 5.2

### CODE REVIEW

**Comment by fxcoudert** [comment]
I've added a commit that should let it through CI for testing purposes

**Comment by maxGimeno** [comment]
@fxcoudert Thank you !

**Comment by fxcoudert** [comment]
Not working… @Rylan12 would you have an idea why?

**Comment by fxcoudert** [comment]
Working, all tests are passing.

**Comment by Rylan12** [comment]
Sorry, had a busy morning so just getting to my notifications now. Looks like whatever the issue was has been resolved. If not, let me know and I'll look into it more.

**Pull request closed without merging**
