### PR TITLE
pnpm 7.13.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
@Porkepix please don't open duplicate PRs with Testbot: https://github.com/Homebrew/homebrew-core/pull/113274

**Comment by Porkepix** [comment]
> @Porkepix please don't open duplicate PRs with Testbot: #113274

@SMillerDev Mine was opened 6 hours before @BrewTestBot's… (and it's not the first time @BrewTestBot open PR I already opened).

**Comment by SMillerDev** [comment]
You should adjust your script to ensure that it doesn't open pull requests for software testing tracks.

**Comment by Porkepix** [comment]
> You should adjust your script to ensure that it doesn't open pull requests for software testing tracks then.

What do you mean by software testing tracks? And I don't use any script, just using bare `brew` commands: `$ brew livecheck --eval-all -q --newer-only` (which answer badly for some formulas with messages such as `cURL failed without a detectable error
` or SSL errors, for the record).

**Comment by SMillerDev** [comment]
"Testing" should be "testbot" and the way your command works you'll create a lot of duplicates. It's TestBots job to update everything and contributors can update what the bot doesn't, if you have software that can be auto updated you can add it to the list in `.github/workflows/autobump.yml`

**Comment by Porkepix** [comment]
> "Testing" should be "testbot" and the way your command works you'll create a lot of duplicates. It's TestBots job to update everything and contributors can update what the bot doesn't, if you have software that can be auto updated you can add it to the list in `.github/workflows/autobump.yml`

Dupes are not that commons, and I was always said that the bot was supposed to check for dupes first the same way it does when you bump from your terminal. Just that it seemed the dupe check had sometimes some issues.

**Comment by carlocab** [comment]
Yea, it's on @BrewTestBot to not open dupes here. Expecting contributors to monitor the content of `.github/workflows/autobump.yml` is not reasonable, IMO.

**Pull request closed without merging**
