### PR TITLE
throttled_formulae: add testkube

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

`testkube` gets several releases per day: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+testkube+is%3Aclosed
Quite often, we have several open PRs with it. I suggest throttling it a little

### CODE REVIEW

**Comment by carlocab** [comment]
We'll need to get upstream to switch to `@dawidd6`'s action. I don't think `@mislav`'s action currently handles throttled formulae.

**Comment by Porkepix** [comment]
They even got two releases on the exact same commit: https://github.com/kubeshop/testkube/releases (`1.4.12` and `1.4.13`).

On the other hand, when minor/dot releases bring so few changes (for example https://github.com/kubeshop/testkube/compare/v1.4.13...v1.4.14), is it conceivable that *if* all tests are greens *and* only for minor/dot releases (here for example any `1.4.x` release), brewtestbot gives itself an approval and a merge?
This would avoid to have several opened at once, while allowing to have latest release, which might be bugfixes or security fixes that can't be obtained otherwise. The throttle can prevent those bug/security releases to be updated.

(Another issue I happened to notice with throttled formulas is for example some might slow down or even stop the development for a while and users can't get the latest release because that's not a good multiple. See for example `quicktype` formula, stuck with an update at x+1 for now a very long time, but can't be updated due to throttle).

**Comment by bayandin** [comment]
> This would avoid to have several opened at once, while allowing to have latest release, which might be bugfixes or security fixes that can't be obtained otherwise. 

Regarding the first part, I don't think so; building a package could take more time than cutting a release (and creating a PR).

> (Another issue I happened to notice with throttled formulas is for example some might slow down or even stop the development for a while and users can't get the latest release because that's not a good multiple. See for example quicktype formula, stuck with an update at x+1 for now a very long time, but can't be updated due to throttle).

This can be addressed with throttle logic, if there were no releases for some time (for a week, for example) — stop complaining

**Comment by SMillerDev** [comment]
> brewtestbot gives itself an approval and a merge?

Never gonna make that mistake again: https://brew.sh/2021/04/21/security-incident-disclosure/

**Comment by Bo98** [comment]
A lot of these quick releases appear to be CI tweaks. I'm not entirely convinced it'll necessarily be like that long term.

**Comment by Bo98** [comment]
Ok I've figured it out: some CI changes are being worked on at https://github.com/kubeshop/testkube/commits/update-ci-choco but they're testing the full release flow. Really those should not be actually be public releases, but if we ignore those releases the actual number of proper releases is more normal.

**Review by carlocab — APPROVED** [review]
I still see multiple updates in a day.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
