### PR TITLE
gomplate 3.0.0

### PR DESCRIPTION
**Pull request by hairyhenderson**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Test is failing:

```
==> /usr/local/Cellar/gomplate/3.0.0/bin/gomplate --version
Error: gomplate: failed
An exception occured within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<nil>.
```

**Comment by hairyhenderson** [comment]
That's... strange! I'm actually seeing the same thing locally. The non-slim build works fine, so maybe something's wrong with UPX 😞

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by hairyhenderson** [comment]
@fxcoudert this is likely to continue failing until UPX has released a fix 😞

**Comment by fxcoudert** [comment]
Has the bug been reported to them?
Can we do a non-compress build?

**Comment by hairyhenderson** [comment]
@fxcoudert yup - it's fixed in https://github.com/upx/upx/issues/222

A non-compressed build _is_ done, but the binary is ~10x larger.

If it's possible to use `HEAD` of `upx` as the dependency, this'll work...

**Comment by fxcoudert** [comment]
Nope, this will have to wait for a new release.

**Comment by fxcoudert** [comment]
Closing for now, as there is sadly no timeline on a new `upx` release.

**Comment by hairyhenderson** [comment]
@fxcoudert understood - I'll re-open when a new one comes out!

**Pull request closed without merging**
