### PR TITLE
curl: Add NSS support

### PR DESCRIPTION
**Pull request by joneskoo**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Have you built your formula locally prior to submission with `brew install <formula>`?
  --with-nghttp2 --with-nss

NSS is needed because it has a nice SSLKEYLOGFILE that allows wiresharking TLS traces without controlling the server.

Fails tests due to CA certs

### CODE REVIEW

**Comment by joneskoo** [comment]
@l-hedgehog @DomT4 Can we get ca certs from nss somehow for this like openssl and libressl?

**Comment by mikemcquaid** [comment]
@joneskoo We already provide 2 SSL providers and I'm pretty hesistant to provide a third in a formula like `curl` that's both important to us and already overcomplex.

**Comment by joneskoo** [comment]
@mikemcquaid Fair enough. The only reason for nss is the excellent SSLKEYLOGFILE but I suppose in the rare occasion it's needed, it's simple enough to modify the formula manually like I did. Otherwise I don't think NSS adds anything. I don't know why LibreSSL is needed then either, though?

Thanks.

**Comment by mikemcquaid** [comment]
Yeh, we may consider removing LibreSSL from a few places now it's not looking like it's going to take over fully from OpenSSL CC @DomT4

**Comment by DomT4** [comment]
Given LibreSSL was added as an optional test-bed to `curl` and `libssh2` in particular I'm happy for it to remain there. We've had reports of people using it so it's not sat there idly.

There are places where upstreams have abandoned OpenSSL in favour of LibreSSL and that is reflected in dependencies as well, and then there are formulae like `h2o` that use LibreSSL upstream but we use OpenSSL here.

On the broader issue, I agree we should place a hold on adding more optional *SSL-competing dependencies until a point where we handle it better.

**Pull request closed without merging**
