### PR TITLE
ace-6.4.4

### PR DESCRIPTION
**Pull request by jwillemsen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jwillemsen** [comment]
The failing of ace on yosemite happened also previous times, no idea why, there are no differences for yosemite in the scripts

**Comment by jwillemsen** [comment]
@fxcoudert A new ACE release is available, same issue as with PR #8986

**Comment by ilovezfs** [comment]
@woodruffw seems like on >= 10.11 the linkage is seen as
```
Variable-referenced libraries:
  @rpath/libACE.dylib
  @rpath/libExport_Lib.dylib
  @rpath/libIPC_Tests_Server.dylib
  @rpath/libTimer.dylib
  @rpath/libtqtd.dylib
```
whereas on 10.10 it's just
```
Variable-referenced libraries:
  libACE.dylib
  libExport_Lib.dylib
  libIPC_Tests_Server.dylib
  libTimer.dylib
  libtqtd.dylib
```

**Comment by ilovezfs** [comment]
@jwillemsen the linkage issue should go away if you remove the line

```
    system "make", "-C", "examples"
```

**Comment by jwillemsen** [comment]
@ilovezfs Thanks for having a look, I think I found the issue in ACE, there is a special addition for 10.11 and newer for the System Integrity Protection (SIP) which changes the variable reference libraries to use rpath. I will move that code to the 10.10 support which will be used by newer ones.

The problem in the CI build is just for one of the examples which are used to test ACE, maybe this PR can be merged, with the next ACE release 10.10 should also work

**Comment by ilovezfs** [comment]
ok

**Comment by ilovezfs** [comment]
@jwillemsen thanks for the PR.

For future reference, the commit subject should be `ace 6.4.4` not `ace-6.4.4`.

**Comment by jwillemsen** [comment]
@ilovezfs Thanks for the merge, will try to remember the commit subject rules

**Comment by jwillemsen** [comment]
Now 10.10 works also out of the box, see #17756

**Pull request closed without merging**
