### PR TITLE
lttng-ust 2.13.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
need `CI-long-timeout`

**Comment by chenrui333** [comment]
looks like the linux build times out? 🤔

**Comment by SMillerDev** [comment]
Yeah, it needs the self-hosted runner

**Comment by iMichka** [comment]
Wondering what takes so long to build on Linux ...

**Comment by iMichka** [comment]
lttng-ust 2.13.0 #83755 had already issues.

I'm going to stop the linux CI to free the worker and have a look at the logs / build this locally.

**Comment by iMichka** [comment]
So, `brew install --verbose --build-bottle dotnet` got stuck for more than 12 hours. I'll try to compile this locally.

**Pull request closed without merging**
