### PR TITLE
votca: enable xtp module

### PR DESCRIPTION
**Pull request by junghans**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by junghans** [comment]
Needs #132477

**Comment by junghans** [comment]
@chenrui333  ready for you review!

**Comment by junghans** [comment]
Needs #132812

**Comment by junghans** [comment]
@chenrui333 sorry for the back and forth, this is ready to go now!

**Comment by junghans** [comment]
@carlocab could you review this please?

**Review by chenrui333 — APPROVED** [review]
LGTM

**Comment by chenrui333** [comment]
@junghans sorry about the delay, thanks for the patience.

**Comment by junghans** [comment]
@chenrui333 huh?

**Comment by p-linnane** [comment]
@junghans There was some kind of issue with the GitHub merge queue. I've rebased this and started new builds. I will get this merged after that completes. Thanks for your patience.

**Review by p-linnane — APPROVED** [review]

**Comment by junghans** [comment]
> @junghans There was some kind of issue with the GitHub merge queue. I've rebased this and started new builds. I will get this merged after that completes. Thanks for your patience.

Thanks!

**Pull request merged**
