### PR TITLE
corsixth 0.67

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not the latest release: https://github.com/CorsixTH/CorsixTH/releases

**Comment by chenrui333** [comment]
https://github.com/CorsixTH/CorsixTH/issues/2380

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/139168

**Comment by chenrui333** [comment]
#139658

**Pull request closed without merging**
