### PR TITLE
exiftool 12.42

### PR DESCRIPTION
**Pull request by fxstein**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Thanks!

**Comment by fxstein** [comment]
Thank you all for making this so easy!

**Comment by ashmckenzie** [comment]
On macOS 12.4 (21F79), `exiftool` fails to execute with the new 12.42 version:

```sh
$ brew uninstall exiftool ; brew install exiftool ; exiftool -ver
Error: No such keg: /opt/homebrew/Cellar/exiftool
==> Downloading https://ghcr.io/v2/homebrew/core/exiftool/manifests/12.42
Already downloaded: /Users/ash/Library/Caches/Homebrew/downloads/c060fe42c29fa73aa43d4ba8148f01272e927edccec1dc16303624d81b66dc15--exiftool-12.42.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/exiftool/blobs/sha256:4d262f00f8f26d69838dad118928276859984c4b69885c606cb3bcf7eee44452
Already downloaded: /Users/ash/Library/Caches/Homebrew/downloads/e5453514ad587c89fae26ccb2d21f0f4f6951e0b8d602068f63203167f54ca98--exiftool--12.42.arm64_monterey.bottle.tar.gz
==> Pouring exiftool--12.42.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/exiftool/12.42: 582 files, 24.0MB
==> Running `brew cleanup exiftool`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Can't locate Image/ExifTool.pm in @INC (you may need to install the Image::ExifTool module) (@INC contains: /opt/homebrew/bin/../Cellar/exiftool/12.42/bin/lib /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at /opt/homebrew/bin/exiftool line 40.
BEGIN failed--compilation aborted at /opt/homebrew/bin/exiftool line 40.
```

**Comment by ashmckenzie** [comment]
Proposed fix PR https://github.com/Homebrew/homebrew-core/pull/103182 🙏

**Comment by fxstein** [comment]
Can confirm, saw the same error after the merge. Have been investigating and checking with the author. A recent fix for a related problem has introduced this behavior when installed via homebrew. Here is the link to the discussion: 
https://exiftool.org/forum/index.php?topic=13629.msg73532#msg73532

**Pull request closed without merging**
