### PR TITLE
linklint 2.3.6.d

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
> The formula version (2.3.6.d) is newer than the version from `brew livecheck` (2.3.5).

**Comment by osalbahr** [comment]
I think `bump --open-pr` is using Repology.

```console
% brew bump linklint
==> linklint
Current formula version:  2.3.5
Latest livecheck version: 2.3.5
Latest Repology version:  2.3.6.d
Open pull requests:       linklint 2.3.6.d (https://github.com/Homebrew/homebrew-core/pull/138605)
Closed pull requests:     none
```

Or, `livecheck` falls back to Repology when GitHub's limit is reached?
```console
...

Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 12 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 12 seconds
==> linklint
Current formula version:  2.3.5
Latest livecheck version: 2.3.6.d
Latest Repology version:  2.3.6.d
Open pull requests:       none
Closed pull requests:     none
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 9 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 9 seconds
==> Downloading http://linklint.org/download/linklint-2.3.6.d.tar.gz
######################################################################### 100.0%
Warning: Cannot verify integrity of 'b7a0bdbd141898f598f4fcaa6f8770771a281a9a87782a99db45522f83828d57--linklint-2.3.6.d.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "05c2aee1c530af566ef67857fc6b052abb3521d54318749375f8c4a092cd3dea"
==> replace /http:\/\/linklint\.org\/download\/linklint\-2\.3\.5\.tar\.gz/ with 
==> replace "ecaee456a3c2d6a3bd18a580d6b09b6b7b825df3e59f900270fe3f84ec3ac9c7" w
M	Formula/linklint.rb
Switched to a new branch 'bump-linklint-2.3.6.d'
[bump-linklint-2.3.6.d f4db8874009] linklint 2.3.6.d
 1 file changed, 2 insertions(+), 2 deletions(-)
remote: 
remote: Create a pull request for 'bump-linklint-2.3.6.d' on GitHub by visiting:        
remote:      https://github.com/osalbahr/homebrew-core/pull/new/bump-linklint-2.3.6.d        
remote: 
To https://github.com/osalbahr/homebrew-core.git
 * [new branch]              bump-linklint-2.3.6.d -> bump-linklint-2.3.6.d
branch 'bump-linklint-2.3.6.d' set up to track 'https://******@github.com/osalbahr/homebrew-core.git/bump-linklint-2.3.6.d'.
https://github.com/Homebrew/homebrew-core/pull/138605

...
```

**Comment by chenrui333** [comment]
image

**Comment by osalbahr** [comment]
Too early

**Pull request closed without merging**
