### PR TITLE
node@4 4.7.2

### PR DESCRIPTION
**Pull request by febLey**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@febLey do we know why that checksum changed?

**Comment by febLey** [comment]
I've pasted the wrong checksum, I copied the checksum from the release post, which was the first one, but it seems that this sum was incorrect:

https://nodejs.org/en/blog/release/v4.7.1/

This file contains the correct sum:

https://nodejs.org/dist/v4.7.1/SHASUMS256.txt

**Comment by ilovezfs** [comment]
Thanks for explaining!

**Comment by febLey** [comment]
Here's the according issue:

https://github.com/nodejs/build/issues/586

**Comment by febLey** [comment]
Ah node 4.7.2 with the correct hashes was release. Should I update this PR or create a new one?

https://nodejs.org/en/blog/release/v4.7.2/

**Comment by MikeMcQuaid** [comment]
> Should I update this PR

That'd be great, thanks 👍

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
