### PR TITLE
rust 1.73.0

### PR DESCRIPTION
**Pull request by junminhong**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

# brew test
截圖 2023-10-11 上午11 36 36

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Previous run with https://github.com/Homebrew/homebrew-core/labels/CI-build-dependents-from-source: https://github.com/Homebrew/homebrew-core/actions/runs/6427402091

**Comment by ZhongRuoyu** [comment]
12-arm64 still failed, somehow.

```
  thread 'main' panicked at 'could not read dir "/private/tmp/rust-20231011-5418-uaahrv/rustc-1.73.0-src/build/aarch64-apple-darwin/stage0/lib/rustlib/aarch64-apple-darwin/codegen-backends": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1714:25
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SMillerDev** [comment]
```
Building stage0 library artifacts (aarch64-apple-darwin)
      Finished release [optimized] target(s) in 0.24s
  thread 'main' panicked at 'could not read dir "/private/tmp/rust-20231019-5370-1ajvakf/rustc-1.73.0-src/build/aarch64-apple-darwin/stage0/lib/rustlib/aarch64-apple-darwin/codegen-backends": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1714:25
```

**Comment by junminhong** [comment]
```
Warning: no codegen-backends config matched the requested path to build a codegen backend. Help: add backend to codegen-backends in config.toml.
```

**Comment by junminhong** [comment]
I tried compiling with Rust version 1.72.1 but need CI-long-timeout tag for testing.

**Comment by junminhong** [comment]
CI-long-timeout

**Comment by chenrui333** [comment]
previous run, https://github.com/Homebrew/homebrew-core/actions/runs/6573972389/job/17862992046

**Comment by chenrui333** [comment]
rebased after #152284

**Comment by chenrui333** [comment]
rerun 🤞

**Comment by chenrui333** [comment]
```
  error: failed to select a version for the requirement `serde = "^1.0.171"` (locked to 1.0.188)
  candidate versions found which didn't match: 1.0.171, 1.0.164, 1.0.160, ...
  location searched: directory source `/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/vendor` (which is replacing registry `crates-io`)
  required by package `cargo-platform v0.1.4 (/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/src/tools/cargo/crates/cargo-platform)`
  perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by junminhong** [comment]
> ```
>   error: failed to select a version for the requirement `serde = "^1.0.171"` (locked to 1.0.188)
>   candidate versions found which didn't match: 1.0.171, 1.0.164, 1.0.160, ...
>   location searched: directory source `/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/vendor` (which is replacing registry `crates-io`)
>   required by package `cargo-platform v0.1.4 (/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/src/tools/cargo/crates/cargo-platform)`
>   perhaps a crate was updated and forgotten to be re-vendored?
> ```

because of caching? I'm not sure 😅
Does anyone know how to solve this problem?

**Comment by chenrui333** [comment]
> > ```
> >   error: failed to select a version for the requirement `serde = "^1.0.171"` (locked to 1.0.188)
> >   candidate versions found which didn't match: 1.0.171, 1.0.164, 1.0.160, ...
> >   location searched: directory source `/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/vendor` (which is replacing registry `crates-io`)
> >   required by package `cargo-platform v0.1.4 (/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/src/tools/cargo/crates/cargo-platform)`
> >   perhaps a crate was updated and forgotten to be re-vendored?
> > ```
> 
> because of caching? I'm not sure 😅 Does anyone know how to solve this problem?

can you build and test out fine in your local?

**Comment by junminhong** [comment]
> > > ```
> > >   error: failed to select a version for the requirement `serde = "^1.0.171"` (locked to 1.0.188)
> > >   candidate versions found which didn't match: 1.0.171, 1.0.164, 1.0.160, ...
> > >   location searched: directory source `/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/vendor` (which is replacing registry `crates-io`)
> > >   required by package `cargo-platform v0.1.4 (/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/src/tools/cargo/crates/cargo-platform)`
> > >   perhaps a crate was updated and forgotten to be re-vendored?
> > > ```
> > 
> > 
> > because of caching? I'm not sure 😅 Does anyone know how to solve this problem?
> 
> can you build and test out fine in your local?

I have the same problem if I use this commit 1c689ed
But when I commit using da76e67, I can build and test.

**Comment by chenrui333** [comment]
okay, let's kick off another run (I am also testing on 12-arm now)

**Comment by chenrui333** [comment]
> > > > ```
> > > >   error: failed to select a version for the requirement `serde = "^1.0.171"` (locked to 1.0.188)
> > > >   candidate versions found which didn't match: 1.0.171, 1.0.164, 1.0.160, ...
> > > >   location searched: directory source `/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/vendor` (which is replacing registry `crates-io`)
> > > >   required by package `cargo-platform v0.1.4 (/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/src/tools/cargo/crates/cargo-platform)`
> > > >   perhaps a crate was updated and forgotten to be re-vendored?
> > > > ```
> > > 
> > > 
> > > because of caching? I'm not sure 😅 Does anyone know how to solve this problem?
> > 
> > 
> > can you build and test out fine in your local?
> 
> I have the same problem if I use this commit [1c689ed](https://github.com/Homebrew/homebrew-core/commit/1c689ed0b4ec4185dd6f9cc0f4affbfbced7ff0b) But when I commit using [da76e67](https://github.com/Homebrew/homebrew-core/commit/da76e67475f92096615a8e7a443cdf117e8e2746), I can build and test in my local.

@junminhong can you use brew gist-logs to upload your local logs if you are using 12-arm for the build? (we only have rust build issue for 12-arm build)

**Comment by junminhong** [comment]
> > > > > ```
> > > > >   error: failed to select a version for the requirement `serde = "^1.0.171"` (locked to 1.0.188)
> > > > >   candidate versions found which didn't match: 1.0.171, 1.0.164, 1.0.160, ...
> > > > >   location searched: directory source `/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/vendor` (which is replacing registry `crates-io`)
> > > > >   required by package `cargo-platform v0.1.4 (/private/tmp/rust-20231024-5920-vmoiy9/rustc-1.73.0-src/src/tools/cargo/crates/cargo-platform)`
> > > > >   perhaps a crate was updated and forgotten to be re-vendored?
> > > > > ```
> > > > 
> > > > 
> > > > because of caching? I'm not sure 😅 Does anyone know how to solve this problem?
> > > 
> > > 
> > > can you build and test out fine in your local?
> > 
> > 
> > I have the same problem if I use this commit [1c689ed](https://github.com/Homebrew/homebrew-core/commit/1c689ed0b4ec4185dd6f9cc0f4affbfbced7ff0b) But when I commit using [da76e67](https://github.com/Homebrew/homebrew-core/commit/da76e67475f92096615a8e7a443cdf117e8e2746), I can build and test in my local.
> 
> @junminhong can you use brew gist-logs to upload your local logs if you are using 12-arm for the build? (we only had rust build issue for 12-arm build on CI)

sorry, I use macos 13.5.2

**Comment by jqnatividad** [comment]
Hi folks,
Not sure if this is relevant, but putting it here just the same...

https://github.com/rust-lang/rust/issues/116397

**Comment by chenrui333** [comment]
#154526

**Comment by chenrui333** [comment]
> Hi folks, Not sure if this is relevant, but putting it here just the same...
> 
> [rust-lang/rust#116397](https://github.com/rust-lang/rust/issues/116397)

For what is worth, this PR (http://rust-lang/rust#117875) actually fixed the build issue on 12-arm

**Comment by jqnatividad** [comment]
With 1.74.0 now out, is the team planning on skipping 1.73.0 and just go directly to 1.74.0?

**Comment by ZhongRuoyu** [comment]
> With 1.74.0 now out, is the team planning on skipping 1.73.0 and just go directly to 1.74.0?

Yes, we're doing that in #154526.

**Comment by chenrui333** [comment]
for folks on this thread, we have just shipped rust 1.74.0

**Pull request closed without merging**
