### PR TITLE
knot: revision to fix broken bottle

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

current bottle is missing its config file

### CODE REVIEW

**Comment by ilovezfs** [comment]
Config file still missing after regenerating the bottles. Something is wrong.

**Comment by ilovezfs** [comment]
@fxcoudert the good news is that the config files are back after fully reverting the changes so the problem is specific to the revised formula, not more widespread.

**Comment by ilovezfs** [comment]
OK latest batch is good this time. CC @MikeMcQuaid it seems we have config-files-not-getting-cleaned-up-always issues (again).

**Comment by MikeMcQuaid** [comment]
> OK latest batch is good this time. CC @MikeMcQuaid it seems we have config-files-not-getting-cleaned-up-always issues (again).

@ilovezfs Given all the CI chaos recently I'm thinking this is the fault of that.

**Comment by ilovezfs** [comment]
I don't think so. See above: "Config file still missing after regenerating the bottles. Something is wrong." It happened AGAIN just yesterday.

**Comment by MikeMcQuaid** [comment]
@ilovezfs 😭 Are you able to reproduce anything locally? If you do manage and could file a Homebrew/brew issue I'll try to take a look.

**Pull request closed without merging**
