### PR TITLE
rust 1.43.0

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Fails:

On Catalina
```
brew install --build-from-source diesel
brew install --build-from-source pcb2gcode
brew install --build-from-source topgrade
brew test --verbose watchexec
```

On Mojave
```
brew install --build-from-source diesel
brew install --build-from-source grin
brew install --build-from-source grin-wallet
brew test --verbose watchexec
```

On High Sierra
```
brew install --build-from-source cargo-c
brew install --build-from-source diesel
brew install --build-from-source git-series
brew install --build-from-source grin
brew install --build-from-source grin-wallet
brew test --verbose watchexec
```

**Comment by Bo98** [comment]
Because being consistent between OS versions would be too easy...

---

`grin*` is known, so can be ignored for this pull request: #50815

`cargo-c` failure is also seen here: #53314, so probably not 1.43.0 related.

`git-series` seems to be identical failure to `cargo-c` (same `libssh2` dependency).

There is insufficient information in the build logs to figure out why `pcb2gcode` broke.

`topgrade` is a CLT SDK bug (#52332). Not 1.43.0 related.

`watchexec` is a test timeout. Worth be worthwhile someone testing whether it happens on its own in another pull request (or even locally).

I see `diesel` broke, again. Bit annoying how fragile it is.

**Comment by Bo98** [comment]
* cargo-c - #53766
* diesel - #53762
* git-series - #53764
* grin - #53791
* grin-wallet - #53792
* pcb2gcode - #53769
* topgrade - #53794
* watchexec - #53771

**Comment by Bo98** [comment]
* deno - #53841

---

Bottle upload broke:

```
Fail to upload '/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/rust--1.43.0.catalina.bottle.tar.gz' due to 'Blob is incomplete (missing block). Blob: a9aee3738188ea1186e9501ac58b53d6, Expected Offset: 0, Actual Offset: 125829120'.
```

**Comment by bayandin** [comment]
Well done @bo98!

**Comment by Bo98** [comment]
Never thought I'd see a ✅ on a Rust pull request

**Pull request closed without merging**
