### PR TITLE
a*|b*: replace `plist` with `service` block

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nandahkrishna** [comment]
This required Homebrew/brew#11355, re-running CI.

**Comment by nandahkrishna** [comment]
`blazegraph` failure on ARM is expected (depends on `openjdk@8`).

**Comment by SMillerDev** [comment]
Can this be merged then?

**Review by nandahkrishna — APPROVED** [review]
👍🏼

**Pull request merged**
