### PR TITLE
flac 1.3.3

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by alebcay** [comment]
CI failure should be resolved after #42861 is merged.

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
```
==> Pouring shared-mime-info-1.12_1.mojave.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall shared-mime-info`
```

🙃

**Comment by alebcay** [comment]
Well, _one_ of the CI failures has disappeared (`brew test --verbose dynare` was previously failing too) 😂

Baby steps. And deep breaths.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
