### PR TITLE
Fix audit --strict warning about sourceforge link

### PR DESCRIPTION
**Pull request by miguelarauj1o**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

``` shell
FORMULAE:
  * http://FORMULAE.sourceforge.net/ should be `https://FORMULAE.sourceforge.io/`
```

### CODE REVIEW

**Comment by ilovezfs** [comment]
what does `--warning` mean here?

**Comment by miguelarauj1o** [comment]
@ilovezfs, it's should be --strict. :/

**Comment by ilovezfs** [comment]
@miguelarauj1o I actually think this are hard audit failures even without --strict, no?

**Comment by miguelarauj1o** [comment]
I got theses warnings after run 'brew audit --strict'

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew audit vpcs
vpcs:
  * http://vpcs.sourceforge.net/ should be `https://vpcs.sourceforge.io/`
Error: 1 problem in 1 formula
```
so looks like they're failures even without `--strict`.

Also I think there are a few more: https://gist.github.com/ilovezfs/b4c5f091e38ebb6c4bd35428ceeca623

**Comment by ilovezfs** [comment]
@miguelarauj1o don't worry about updating these just yet. We can probably do this in a single commit.

**Comment by miguelarauj1o** [comment]
Yes, you're right, these are hard audit failures. I don't need pass --strict flag to get them.

Using ```sed```, I made an shell script to handle all cases that respect this structure: ```"http://FORMULAE.sourceforge.net/"```. 
So,
``` shell
chadwick:
  * http://chadwick.sourceforge.net/doc/index.html should be `https://chadwick.sourceforge.io/`
[...]
dumb:
  * http://dumb.sourceforge.net/index.php?page=about should be `https://dumb.sourceforge.io/`
```
```sed``` will ignore theses examples from your gist.

I can modify it to get the other cases.
Also, @ilovezfs, should I fix all commit messages (--warning to --strict)?

**Comment by MikeMcQuaid** [comment]
We can update the commit messages in future but these are fine for now (or at least we don't want another CI run). Thanks @miguelarauj1o!

**Comment by miguelarauj1o** [comment]
Great!

**Comment by ilovezfs** [comment]
@MikeMcQuaid this explicitly had do not merge on it. Not sure why this was merged as is.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Apologies; because the email notifications don't include label changes and when I click through to a long thread it jumps to the comment I missed it. I think we should consider replacing "do not merge" with PR reviews as they are more prominent at the bottom of a PR next to the merge. Thoughts?

**Comment by ilovezfs** [comment]
>Apologies

That's all right. Unfortunately the only actual remedy here is a force push, which is against the repository's religion.

>I think we should consider replacing "do not merge" with PR reviews

This won't work because you cannot perform a GitHub PR review on your own PRs, and the vast majority of my use of `do not merge` is on my own PRs so we need some other solution that covers that case as well.

**Comment by MikeMcQuaid** [comment]
> This won't work because you cannot perform a GitHub PR review on your own PRs, and the vast majority of my use of do not merge is on my own PRs so we need some other solution that covers that case as well.

A failing CI job feels like it would be the best solution.

**Pull request merged**
