### PR TITLE
toast 0.45.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /opt/homebrew/Cellar/toast/0.45.0/bin/toast --list
[INFO] Here are the tasks that have a description and any environment variables they support:
Error: test failed
Error: toast: failed
```

**Comment by chenrui333** [comment]
https://github.com/stepchowfun/toast/issues/397

**Comment by stepchowfun** [comment]
Ah, we need to add a `description` on the task to make it show up in the `--list` output.

**Comment by stepchowfun** [comment]
@chenrui333 Can you change the test toastfile to this:

```yaml
      image: alpine
      tasks:
        homebrew_test:
          description: Greet the user.
          command: echo hello
```

**Comment by stepchowfun** [comment]
Thanks for updating the test!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
