### PR TITLE
miller 5.3.0

### PR DESCRIPTION
**Pull request by johnkerl**
Subsequent release following same procedure as always

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> Downloading https://github.com/johnkerl/miller/releases/download/v5.3.0/mlr-5.3.0.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
```
There's not yet an asset uploaded for this release.
https://github.com/johnkerl/miller/releases/5.3.0

**Comment by johnkerl** [comment]
All right, some new step since my previous releases. I'll look into it.

**Comment by johnkerl** [comment]
screen shot 2018-01-06 at 10 10 27 pm

**Comment by johnkerl** [comment]
Second time's a charm -- the assets didn't fail upload this time. Sorry about that!

**Comment by sjackman** [comment]
@BrewTestBot Test this please

**Comment by ilovezfs** [comment]
It looks like there's no `v` in your tag name this time.

**Comment by johnkerl** [comment]
I updated the release tag; also for future sanity-checking I updated

http://johnkerl.org/miller-releases/miller-head/doc/build.html#Creating_a_new_release:_for_developers
https://github.com/johnkerl/miller/commit/28de70878f73f4358942ebbac6f9daa61653b3ee
https://github.com/johnkerl/miller/commit/b105d294f7e2ab46781b9aaf8ffc48fee3efca10

**Comment by johnkerl** [comment]
@BrewTestBot Test this please

**Comment by ilovezfs** [comment]
Thanks for the upgrade @johnkerl!

**Pull request closed without merging**
