### PR TITLE
apache-spark 3.0.0

### PR DESCRIPTION
**Pull request by williamhyun**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does this version work with Java 11?

**Comment by williamhyun** [comment]
Yes. Apache Spark 3.0.0 officially support JDK11.

**Comment by SMillerDev** [comment]
Can you change the dependency to `openjdk@11` then.

**Comment by williamhyun** [comment]
@SMillerDev I changed the dependency.

**Review by SMillerDev — COMMENTED** [review]
Please also change the Java 8 parameter in the install block to `:JAVA_HOME => Formula["openjdk@11"].opt_prefix`

**Comment by SMillerDev** [comment]
Looks good, could you squash your commits to just say `apache-spark 3.0.0`?

**Comment by williamhyun** [comment]
@SMillerDev Thank you, I squashed my commits.

**Review by SMillerDev — APPROVED** [review]
Thanks @williamhyun ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by williamhyun** [comment]
Thank you @SMillerDev :)

**Pull request closed without merging**
