### PR TITLE
mmctl: use `Utils.git_head`

### PR DESCRIPTION
**Pull request by SeekingMeaning**
See https://github.com/Homebrew/homebrew-core/issues/68805

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```
Error: v5.31.0 tag should be 689bd041b5aa02183721fda0c4e9a4e3d84fab15
but is actually fc161b2931110a913169a0601f0d9d0a36b1749a
```

**Comment by SeekingMeaning** [comment]
Tag was moved over by 2 commits:

- https://github.com/mattermost/mmctl/commit/689bd041b5aa02183721fda0c4e9a4e3d84fab15 Adds command to reset default role permissions **(original tag location)**
- https://github.com/mattermost/mmctl/commit/94a8f4332e3a4900e510c5eb2e96ab32c917b685 Lock CI from cloud/release-5.31
- https://github.com/mattermost/mmctl/commit/fc161b2931110a913169a0601f0d9d0a36b1749a Bump version to 5.31 **(new tag location)**

**Comment by SMillerDev** [comment]
Can you request clarification upstream?

**Comment by SeekingMeaning** [comment]
https://github.com/mattermost/mmctl/issues/301

**Comment by SeekingMeaning** [comment]
> Yes, this change was intended, mainly to include the updated mmctl version before the corresponding mattermost-server was released.

**Comment by SeekingMeaning** [comment]
```
Error: Failure while executing; `/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.7.5-70-g152eac3\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --fail --progress-bar --silent --retry 3 --request POST --fail --user brewtestbot:****** https://api.bintray.com/content/homebrew/bottles/mmctl/5.31.0_1/publish` exited with 35. Here's the output:
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.bintray.com:443 
```

**Pull request closed without merging**
