### PR TITLE
sqlite: remove options and caveats.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
See https://github.com/Homebrew/homebrew-core/issues/31510

### CODE REVIEW

**Comment by fxcoudert** [comment]
Oops… I just realised I overrode that PR in my commit 7789d6ffc82bc4ad4254b030d1ab124c67276bf4

@MikeMcQuaid the reason I didn't include `functions` in my commit is that instructions to load that module are rather complicated. If it does not work "out of the box", I don't think we should include it. (And it's not that widely used, really)

**Comment by lembacon** [comment]
@fxcoudert But I think we should include `FTS`.

**Comment by MikeMcQuaid** [comment]
@fxcoudert Cool. Omitting functions and leaving the rest.

**Comment by MikeMcQuaid** [comment]
`mps-youtube` test is working locally so assuming https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/36546/#showFailuresLink was a blip.

`theharvester` test being fixed in https://github.com/Homebrew/homebrew-core/pull/36208.

**Pull request merged**
