### PR TITLE
drake 1.0.3

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
No, the sha256 did not change. See https://github.com/Factual/drake/issues/217.

**Comment by DomT4** [comment]
👍. This doesn't actually need bottles really, you could make that `bottle :unneeded`. Feel free to do in post though.

**Comment by MikeMcQuaid** [comment]
👍

**Comment by dirtyvagabond** [comment]
thanks @ilovezfs @DomT4 @MikeMcQuaid

**Comment by ilovezfs** [comment]
@dirtyvagabond You're welcome!

**Pull request closed without merging**
