### PR TITLE
taskell 1.1.0 (new formula)

### PR DESCRIPTION
**Pull request by smallhadroncollider**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is my own project, but it's got a fair number of users now.

### CODE REVIEW

**Comment by commitay** [comment]
https://docs.brew.sh/Acceptable-Formulae

> We frown on authors submitting their own work unless it is very popular.

**Comment by ilovezfs** [comment]
Thanks for the PR @smallhadroncollider! Please have one of your users submit this if you'd like it included in Homebrew. Also, it needs to use `install_cabal_package` and

```
depends_on "cabal-install" => :build
```

**Comment by smallhadroncollider** [comment]
@ilovezfs Are there any examples or documentation about how to use `install_cabal_package`? I can't work out how to make it do anything. Thanks.

**Comment by smallhadroncollider** [comment]
@ilovezfs Just realised Google was removing the underscores from my search. I found this: https://searchcode.com/codesearch/view/109095129/ - which will hopefully point me in the right direction

**Pull request closed without merging**
