### PR TITLE
moreutils 0.64

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
Further modified to solve the missing `license` issue, incorporate/obviate #60416, and update `resource` dependencies.

**Comment by pthariensflame** [comment]
The license `GPL-2.0-only` is the minimal cover of the licenses listed in https://metadata.ftp-master.debian.org/changelogs//main/m/moreutils/moreutils_0.63-1_copyright.

**Comment by SMillerDev** [comment]
@Rylan12 suggestions?

**Comment by Rylan12** [comment]
I had a look at the files we distribute in the cellar. It looks like there are 15 binaries we distribute. According to their man pages, 6 of them list a license. 5 are `GNU GPL` and one is `GNU GPL version 2 or higher`.

I know the license file linked above lists many different licenses, but I'm not sure whether we need to include all of those because we aren't distributing those files.

There are also some man pages for `IPC::Run*` and `Time::Duration` in `libexec/man/man3` that declare either `GPL-2.0` or `Artistic-2.0`. I'm not sure what these man pages correspond to.

Based on this, `GPL-2.0-or-later` seems reasonable. I think we should also include the `GPL-2.0` or `Artistic-2.0` as well, meaning this:

```ruby
license all_of: [
  "GPL-2.0-or-later",
  any_of: ["GPL-2.0-only", "Artistic-2.0"]
]
```

There's no indication of `-only` or `-or-later` in the `IPC::*` and `Time::*` files so I went with `GPL-2.0-only`.

If we don't need to include the `IPC` files than just `license "GPL-2.0-or-later"` should be fine.

**Comment by Rylan12** [comment]
Separately, it looks like the `conflicts_with` line was added independently in https://github.com/Homebrew/homebrew-core/pull/60416/ so you may need to rebase to remove that conflict.

**Comment by pthariensflame** [comment]
@Rylan12 @SMillerDev The above stuff has been resolved now.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
