### PR TITLE
bump brogue up to the latest version. 1.7.5

### PR DESCRIPTION
**Pull request by dragonfax**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

## Screenshot
jstillwell_ _brogue_1_7_5_ _brogue_ _brogue_ _100x34

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @dragonfax for your contribution to Homebrew!

**Comment by dragonfax** [comment]
no merge? What was the problem? Maybe I could fix it.

**Comment by fxcoudert** [comment]
It was merged in https://github.com/Homebrew/homebrew-core/commit/05bbad8ba9a5873fbb75e3f5d799b619b365c843

**Comment by dragonfax** [comment]
oh thanks

**Pull request closed without merging**
