### PR TITLE
jsign: add build option

### PR DESCRIPTION
**Pull request by ebourg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by daeho-ro** [comment]
Can you explain why do we need the build option?

**Comment by ebourg** [comment]
@daeho-ro Yes, in the developement version of Jsign the jsign-core module has been split in two parts, jsign-core and jsign-crypto, with jsign-core depending on jsign-crypto. The current formula doesn't build the jsign-crypto module and fails to build with `--HEAD`. Adding the `--also-make` option ensures that any module required by the modules listed in the mvn command will also be built, so the formula will work with Jsign 6.0 and later.

**Review by daeho-ro — APPROVED** [review]
Thank you @ebourg , it looks fine.

**Comment by ebourg** [comment]
Thanks!

**Pull request merged**
