### PR TITLE
various: fix missing metafiles

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
🙃

### CODE REVIEW

**Comment by ilovezfs** [comment]
are you going to make me pull bottles lol

**Comment by DomT4** [comment]
Na, if you want to merge this as-is it can wait for the next update cycle, or next OS release 😆.

**Comment by ilovezfs** [comment]
done

**Comment by DomT4** [comment]
One day we'll work out a sane fix for this issue 🙈. Thanks for the swift merge!

**Pull request merged**
