### PR TITLE
svtplay-dl 1.9.5

### PR DESCRIPTION
**Pull request by spaam**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apjanke** [comment]
Crashed during test on our CI servers.

```
        Testing svtplay-dl
/usr/bin/sandbox-exec -f /tmp/homebrew20170918-19635-19ych15.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/svtplay-dl.rb --verbose
==> /usr/local/Cellar/svtplay-dl/1.9.5/bin/svtplay-dl -g https://tv.aftonbladet.se/abtv/articles/121638
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue
Error: svtplay-dl: failed
Failed executing: /usr/local/Cellar/svtplay-dl/1.9.5/bin/svtplay-dl -g https://tv.aftonbladet.se/abtv/articles/121638
```

Does `brew test svtplay-dl` pass for you locally?

**Comment by ilovezfs** [comment]
It fails for me locally as well. The prior version passes.

The error is

```
iMac-TMP:~ joe$ /usr/local/Cellar/svtplay-dl/1.9.5/bin/svtplay-dl --verbose -g https://tv.aftonbladet.se/abtv/articles/121638
DEBUG [1505713469.63] /usr/local/Cellar/svtplay-dl/1.9.5/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://tv.aftonbladet.se/abtv/articles/121638'
ERROR [1505713470.78] /usr/local/Cellar/svtplay-dl/1.9.5/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.5
Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/1.9.5/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.5/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 469, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.5/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 199, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.5/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 247, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.5/libexec/lib/python2.7/site-packages/svtplay_dl/service/aftonbladet.py", line 42, in get
    streams = hlsparse(self.options, self.http.request("get", data["streamUrls"]["hls"]), data["streamUrls"]["hls"])
KeyError: 'streamUrls'
```

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Test fails, and a bunch of resource blocks need to be updated.

**Comment by spaam** [comment]
I have released 1.9.6 with a fix for the failing test. 
updated the resource blocks too in the formula. 
the CI still use the 1.9.5 for some reason.. should i open a new pull request for 1.9.6 instead?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
>Does your build pass brew audit --strict <formula> (after doing brew install <formula>)?

The pypi URLs don't pass strict audit.

**Comment by spaam** [comment]
it should use the right domains now

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@spaam thanks. It looks like there's some kind of minor installation failure:
```
==> /usr/local/Cellar/svtplay-dl/1.9.6/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/svtplay-dl-20170920-80069-hm12l6/svtplay-dl-1.9.6
Processing /private/tmp/svtplay-dl-20170920-80069-hm12l6/svtplay-dl-1.9.6
  Running setup.py (path:/private/tmp/pip-yt59Nw-build/setup.py) egg_info for package from file:///private/tmp/svtplay-dl-20170920-80069-hm12l6/svtplay-dl-1.9.6
    Running command python setup.py egg_info
    You need to install python-requests to use this script
Cleaning up...
Command "python setup.py egg_info" failed with error code 3 in /private/tmp/pip-yt59Nw-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 3 in /private/tmp/pip-yt59Nw-build/
```

**Comment by spaam** [comment]
@ilovezfs it should be fine now. sorry for the noise.

**Comment by ilovezfs** [comment]
Thanks for the upgrade, @spaam!

**Pull request closed without merging**
