### PR TITLE
docker-edge 17.04.0 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @JCount @MikeMcQuaid

### CODE REVIEW

**Comment by ilovezfs** [comment]
See
https://docs.docker.com/edge/
https://github.com/docker/docker/pull/31075
https://blog.docker.com/2017/03/docker-enterprise-edition/
https://github.com/docker/docker/issues/31842

**Comment by ilovezfs** [comment]
Alternatively, we can put this in the docker formula as the devel spec.

**Review by nijikon — APPROVED** [review]

**Comment by ilovezfs** [comment]
Actually I'm tempted to just make 17.04.0 the stable version for the main docker formula and ignore this stable vs. edge distinction, which looks like a bunch of nonsense, since it's actually time based releases with no semantic meaning whatsoever.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/12142.

**Pull request closed without merging**
