### PR TITLE
wxmac: fix custom print paper size bug

### PR DESCRIPTION
**Pull request by sarim**
Fix Custom Print Paper Size bug. Upstream #16959

Patch from upstream wxWidgets bug tracker.
http://trac.wxwidgets.org/ticket/16959

### CODE REVIEW

**Comment by DomT4** [comment]
Does it work if we use the actual upstream patch rather than inlining it here? We're trying to gently phase out inline patches beyond a certain length because people keep accidentally breaking 'em.

**Comment by sarim** [comment]
Umm, What other way is there to add patches other than inline?

**Comment by DomT4** [comment]
```ruby
patch do
  url "blah"
  sha256 "blah"
end
```

**Comment by sarim** [comment]
@DomT4 did that. check now.

**Comment by sarim** [comment]
At last all checks passed :)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/dbc17c1f6eeb6ab185154acdd61653a3db3bf113. Thank you for your contribution to Homebrew @sarim; we appreciate it! :smiley_cat:

**Pull request closed without merging**
