### PR TITLE
tox: migrate to python@3.10

### PR DESCRIPTION
**Pull request by branchv**
tox: migrate to python@3.10

### CODE REVIEW

**Comment by henryiii** [comment]
```
pyver = Language::Python.major_minor_version("python3.9").to_s.delete(".")
```
Needs to be changed. Are these being made by hand, or is there any tooling?

**Comment by branchvincent** [comment]
go for it! the only caveat is that to migrate formula X, all dependents must also be migrated to use the same python. (if you don't, you'll see an error like https://github.com/Homebrew/homebrew-core/runs/3821983689)

see https://github.com/Homebrew/homebrew-core/issues/62201 for how we handled the last migration

**Comment by henryiii** [comment]
I liked the tracking issue. So far, I guess we have, from a simple grep + count:

| version | count |
|-----|------|
| 3.10 | 141 |
| 3.9 | 456 |
| 3.8 | 11 | 
| 3.7 | 4 | 
| 2.7 | 21 |

**Comment by henryiii** [comment]
When will python3 point at 3.10?

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
