### PR TITLE
taskell 1.7.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
15:54:07 [68 of 68] Compiling App              ( src/App.hs, dist/dist-sandbox-b3df35cc/build/App.o )
15:54:07 
15:54:07 src/App.hs:129:13: error:
15:54:07     • Couldn't match type ‘IO’ with ‘EventM ResourceName’
15:54:07       Expected type: EventM ResourceName Int
15:54:07         Actual type: IO Int
15:54:07     • In the expression:
15:54:07         snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
15:54:07       In an equation for ‘getHeight’:
15:54:07           getHeight
15:54:07             = snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
15:54:07     |
15:54:07 129 | getHeight = snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
15:54:07     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:54:07 
15:54:07 src/App.hs:129:40: error:
15:54:07     • Couldn't match type ‘EventM n0’ with ‘IO’
15:54:07       Expected type: IO Graphics.Vty.Output.Interface.Output
15:54:07         Actual type: EventM n0 Graphics.Vty.Output.Interface.Output
15:54:07     • In the second argument of ‘(=<<)’, namely
15:54:07         ‘outputIface <$> getVtyHandle’
15:54:07       In the second argument of ‘(<$>)’, namely
15:54:07         ‘(displayBounds =<< outputIface <$> getVtyHandle)’
15:54:07       In the expression:
15:54:07         snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
15:54:07     |
15:54:07 129 | getHeight = snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
15:54:07     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:54:07 cabal: Leaving directory '.'
15:54:07 cabal: Error: some packages failed to install:
15:54:07 taskell-1.6.2.0-2F3leOWD3T1LdS29ISIvA0 failed during the building phase. The
15:54:07 exception was:
15:54:07 ExitFailure 1

**Comment by smallhadroncollider** [comment]
Was this an automated pull request? My build script was automatically creating pull requests, but now they're all getting marked as duplicates.

**Comment by chenrui333** [comment]
@smallhadroncollider This is done by script. But I will keep your automated script in mind.

**Comment by chenrui333** [comment]
Can you rerun on your side? Thanks!

**Pull request closed without merging**
