### PR TITLE
Update valgrind to new repository location

### PR DESCRIPTION
**Pull request by jameshilliard**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jameshilliard** [comment]
I don't think this is causing a regression as it's not possible to build valgrind 3.13.0 using xcode 9

**Comment by apjanke** [comment]
We don't have a requirement for minimum/maximum Xcode versions. If I understand correctly, we generally only support the latest Xcode on any given macOS version.

I agree this is not a regression. I get the same error using the `valgrind` formula from `master`, and the change is only in the `head do` block.

Do you have a link to the upstream bug report where this patch is introduced and discussed? Since it's on HEAD, maybe it'll get merged soon and we won't need to include the patch; just the conditionalization of the `MaximumMacOSRequirement`.

Is it this bug report? https://bugs.kde.org/show_bug.cgi?id=383811 One of the comments there says "Patch won't land in valgrind as-is...". Homebrew's policy is generally only to use patches that will be accepted by upstream.

**Comment by apjanke** [comment]
I posted a comment on the upstream bug report at https://bugs.kde.org/show_bug.cgi?id=383811 asking about splitting out Xcode 9 support from macOS 10.13 support.

**Comment by jameshilliard** [comment]
Yes, it was that bug report, however I think this might entirely be a xcode 9 compatibility issue since I'm hitting the exact same issue on OSX 10.12.6 with xcode 9 they reported in 10.13.

**Comment by apjanke** [comment]
Yes, it's Xcode 9; the current configure file has a too-restrictive pattern-matching test. That's why I asked them to split it out; hopefully that can get merged upstream more quickly than full 10.13 support.

**Comment by Echelon9** [comment]
Upstream valgrind dev here.

I've split out and landed in valgrind git master the Xcode 9/LLVM 9.x support. See [here](https://sourceware.org/git/gitweb.cgi?p=valgrind.git;h=27e1503bc7bd767f3a98824176558beaa5a7c1d5)

The broader macOS 10.13 support will land separately once we've ironed out a few more of the issues against the final public release (which I understand will be released tomorrow).

**Comment by jameshilliard** [comment]
I removed the patch, now only updates repo.

**Comment by apjanke** [comment]
Looks good. The new repo location agrees with http://valgrind.org/downloads/repository.html, and I was able to build on macOS Sierra/Xcode 9 from `HEAD` with no modifications.

The CI is failing on Sierra because it's trying to build the stable release against Xcode 9. Not a regression.

Merged. Thank you for your contribution!

**Comment by hasahmed** [comment]
Is this issue closed? Valgrind fails to install on my system. Fails with the error message
"valgrind: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility"
Should I open a new issue? 

MacOS: Sierra
Version: 10.12.6

**Comment by JCount** [comment]
@hasahmed Please open a new issue if you are experiencing a problem, rather than commenting on a closed PR. Make certain to completely fill out the issue template, so we can we can best determine how to help solve your problem.

**Pull request merged**
