### PR TITLE
icu4c 57.1

### PR DESCRIPTION
**Pull request by skystrife**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

The fossies mirror link isn't valid yet, but I assume it will be in time.

### CODE REVIEW

**Comment by apjanke** [comment]
Bunch of test failures. Looks like additional formulae in `homebrew-php` and `homebrew-games` that need their revisions bumped, too.

```
    brew-test-bot.el_capitan.test liblcf
    brew-test-bot.el_capitan.test php53-intl
    brew-test-bot.el_capitan.install php54-intl
    brew-test-bot.el_capitan.install php55-intl
    brew-test-bot.el_capitan.install php56-intl
    brew-test-bot.el_capitan.install php70-intl
    brew-test-bot.el_capitan.test vislcg3
    brew-test-bot.el_capitan.install php53-yaz
    brew-test-bot.el_capitan.install php54-yaz
    brew-test-bot.el_capitan.install php55-yaz
    brew-test-bot.el_capitan.install php56-yaz
    brew-test-bot.el_capitan.install zorba
```

`zorba` and `vislcg3` can be added to this PR. The others from homebrew-games and homebrew-php will need PRs on their corresponding repos, and they'll need to be built after this PR is merged. (Make sure to `brew update` first; I also fixed a warning in `liblcf`.)

**Comment by skystrife** [comment]
`vislcg3` is from `homebrew-science`, right?

I don't know what's happening with `zorba`; there is a `revision` bump in this PR already. Something about missing `zend.h`? Is it somehow related to the php packages that come before it failing to install?

I'm attempting to build it locally now.

**Comment by apjanke** [comment]
> vislcg3 is from homebrew-science, right?

Oh, yep. Would have to be a separate PR, too.

> I don't know what's happening with zorba; there is a revision bump in this PR already. Something about missing zend.h? Is it somehow related to the php packages that come before it failing to install?

That makes sense. Maybe a missing dependency in `zorba`? I don't see it depending on `php`.

**Comment by apjanke** [comment]
You know what? Some of those `phpNN-XXX` formulae which are broken or failing the test are being left installed. That could well be it.

```
==> brew fetch --retry php53-intl
==> brew install php53-intl
==> brew test --verbose php53-intl
==> FAILED
Testing homebrew/php/php53-intl
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160410-77703-1r7hdg5-0.sb /Users/brewadmin/Homebrew/Cellar/ruby187/1.8.7-p374_1/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php53-intl.rb --verbose
==> /usr/local/opt/php53/bin/php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php53-intl/intl.so' - dlopen(/usr/local/opt/php53-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.56.dylib
  Referenced from: /usr/local/opt/php53-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php53-intl/intl.so' - dlopen(/usr/local/opt/php53-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.56.dylib
  Referenced from: /usr/local/opt/php53-intl/intl.so
  Reason: image not found in Unknown on line 0
Error: homebrew/php/php53-intl: failed
failed to find extension in php -m output.
<false> is not true.
==> brew test --verbose php53
==> brew fetch --retry php54-intl
==> brew install php54-intl
```

This might be a little screwy to actually get fully fixed in this PR, due to some problems with `brew`'s dependency resolution.

I think the thing to do here is to actually revert the `zorba` revision in this PR, ignore the failures and merge it, and then do a separate PR for the `zorba` revision bump so it can build without interference from those various `php-*` formulae. Looks like something similar happened with 56.1. https://github.com/Homebrew/legacy-homebrew/pull/46374

**Comment by skystrife** [comment]
It looks like zorba really ought to have a build dependency on Java, Ruby, PHP, and Python if we're expecting its formula to build the language bindings for all four: http://www.zorba.io/documentation/latest/zorba/build/build_prerequisites/

Trying to build it locally complained about me lacking Java.

OK, so to make sure I've got everything lined up right, I need to do the following:

- [ ] Revert `zorba` formula revision in this PR
- [ ] Get this PR merged
- [ ] Create a separate PR for `zorba` to:
  - [ ] Add build dependencies for `:java`, `:ruby`, `:php`, and `:python`
  - [ ] Bump revision for `icu4c`
- [ ] Create PRs for `homebrew-games`, `homebrew-science`, and `homebrew-php` that bump the revision for the formulae that depend on `icu4c`

Is that right?

**Comment by apjanke** [comment]
Yep!

**Comment by skystrife** [comment]
OK the `zorba` changes are reverted. Failing tests are

    brew-test-bot.el_capitan.test zorba
    brew-test-bot.el_capitan.test liblcf
    brew-test-bot.el_capitan.test php53-intl
    brew-test-bot.el_capitan.install php54-intl
    brew-test-bot.el_capitan.install php55-intl
    brew-test-bot.el_capitan.install php56-intl
    brew-test-bot.el_capitan.install php70-intl
    brew-test-bot.el_capitan.test vislcg3
    brew-test-bot.el_capitan.install php53-yaz
    brew-test-bot.el_capitan.install php54-yaz
    brew-test-bot.el_capitan.install php55-yaz
    brew-test-bot.el_capitan.install php56-yaz

as expected.

Should I issue the other PRs now, or wait until this is merged first?

Also, should I bump the `revision` for formulae that have `icu4c` as an optional dependency?

**Comment by apjanke** [comment]
I've merged it. You can go ahead with the other PRs now.

> Also, should I bump the revision for formulae that have icu4c as an optional dependency?

Yes. This doesn't affect bottles, but does ensure that users who have installed dependents with `icu4c` enabled perform the required reinstallation to avoid dylib linkage errors. (At the cost of causing some spurious reinstalls for other users.)

Except...

```
[/usr/local/Library/Taps/homebrew on ⇄ master]
$ grep icu4c */*/*.rb | grep depends_on | grep optional
homebrew-core/Formula/boost.rb:    depends_on "icu4c" => [:optional, "c++11"]
homebrew-core/Formula/boost.rb:    depends_on "icu4c" => :optional
homebrew-core/Formula/parrot.rb:  depends_on "icu4c" => :optional
homebrew-core/Formula/rakudo-star.rb:  depends_on "icu4c" => :optional
homebrew-core/Formula/sqlite.rb:  depends_on "icu4c" => :optional
homebrew-core/Formula/sword.rb:  depends_on "icu4c" => :optional
homebrew-core/Formula/v8.rb:  depends_on "icu4c" => :optional
homebrew-core/Formula/znc.rb:  depends_on "icu4c" => :optional
[/usr/local/Library/Taps/homebrew on ⇄ master]
$
```

Oh my, `boost`. That's a pain to reinstall. Let's skip the revision bump for `boost` but do the rest.

**Comment by DomT4** [comment]
We don't generally bother with optional dep bumps FWIW. It's a lot of CI time and effort and we don't know how many users actually build with those optional dependencies yet.

**Comment by apjanke** [comment]
Gotcha. I was going off the last [ffmpeg bump](https://github.com/Homebrew/legacy-homebrew/pull/49178), which did the optionals as well.

**Comment by DomT4** [comment]
I think we made an exception there because of how much broke up front, but I'm happy to revise my prior advice if @mikemcquaid wants to start doing optional bumps by default despite CI being unable to test them for build failure (Hopefully one day we'll get to that point, somehow).

**Comment by apjanke** [comment]
Cool. Okay, let's skip the optionals here, at least for now.

**Comment by mikemcquaid** [comment]
Agreed on optionals.

**Pull request closed without merging**
