### PR TITLE
libtermkey 0.21.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @lembacon for your contribution to Homebrew. You are awesome! 🥇

**Comment by dominiklohmann** [comment]
Much like yesterdays libtermkey@0.21 this crashes neovim.

**Comment by fxcoudert** [comment]
Please file an issue, and fill the full template so we can investigate

**Comment by dominiklohmann** [comment]
See #37103, #37106 and neovim/neovim#9630. The 0.21.1 patch did not fix the issue, neovim still segfaults right away. Honestly don't see the need to create another issue here, just stop pushing a broken update for the third time without an easy, built-in way to rollback besides `brew edit`. 

What's so hard about testing the formula locally and then trying to run nvim?

**Comment by lembacon** [comment]
@dominiklohmann The issue should have now been fixed by #37118. Please try `brew update && brew upgrade libtermkey`.

**Comment by dominiklohmann** [comment]
Thank you very much @lembacon, fourth time's the charm 👍

**Pull request closed without merging**
