### PR TITLE
yarn 1.10.0

### PR DESCRIPTION
**Pull request by DanBuild**
Created with `brew bump-formula-pr`.

---

This PR was automatically created via a script. Contact @Daniel15 with any questions.

### CODE REVIEW

**Comment by commitay** [comment]
Need to wait for https://yarnpkg.com/en/ to show `1.10.0` as stable.

**Comment by Daniel15** [comment]
@commitay It's coming, the site build is just a bit slow: https://github.com/yarnpkg/website/commit/1208081b1b83d5caecac6c081a258a5f0e00183c. This PR is created in parallel with updating the site 😃

**Comment by connorshea** [comment]
the site now shows 1.10 as stable :)

**Comment by ruchern** [comment]
@ilovezfs the build seems stucked.

**Comment by commitay** [comment]
@ruchern ILZ has left the project.

**Comment by commitay** [comment]
Thanks @Daniel15!

**Comment by ruchern** [comment]
@commitay oh. Thank you for informing. Would have thought that he is still part of this.

**Pull request merged**
