### PR TITLE
pulumi 2.15.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by stack72** [comment]
Thanks @chenrui333 :)

**Comment by stack72** [comment]
Please hold on merging this PR until we give the go-ahead - we are having release issues upstream

**Comment by stack72** [comment]
ok, we have made the release on the Pulumi side so you can proceed on this when required

**Comment by stack72** [comment]
@chenrui333 we just made pulumi v.15.3 release so this can be closed out

**Comment by stack72** [comment]
Superceded by #66437

**Comment by chenrui333** [comment]
Thanks @stack72!

**Pull request closed without merging**
