### PR TITLE
ldc 1.21.0

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
```
because /usr/local/Cellar/ldc/1.21.0/lib/libLTO-ldc.dylib could not be loaded file 'test.o'
```

That's not even English. What can't be loaded - the dylib or the `.o` file?

**Comment by Bo98** [comment]
This is wrong:

```
$ otool -L /usr/local/opt/ldc/lib/libLTO-ldc.dylib
/usr/local/opt/ldc/lib/libLTO-ldc.dylib:
	/usr/local/opt/ldc/lib/libLTO.dylib (compatibility version 1.0.0, current version 10.0.0)
	@rpath/libLLVM.dylib (compatibility version 1.0.0, current version 10.0.0)
```

LDC copies libLTO.dylib but does not properly adjust the install name and linkage paths.

* `/usr/local/opt/ldc/lib/libLTO.dylib` should be `/usr/local/opt/ldc/lib/libLTO-ldc.dylib`
* `@rpath/libLLVM.dylib` probably won't work since libLLVM.dylib is not located in the LDC installation (which `@rpath` will point to), but rather the LLVM isntallation. Either the path should be adjusted, the `rpath` should include the LLVM directory, or, failing all that, I suppose libLLVM could be copied (though copying libraries kinda sucks).

**Comment by Geod24** [comment]
Did you report the issue upstream ? The devs are usually quite responsive.

**Comment by Bo98** [comment]
I did plan to, but I haven't had the chance yet. I still have to report the MySQL regressions too.

**Comment by Geod24** [comment]
CC @kinke

**Comment by Bo98** [comment]
I haven't investigated turning `LDC_INSTALL_LTOPLUGIN` off yet - I'll try to do so tonight.

**Comment by kinke** [comment]
> I haven't investigated turning LDC_INSTALL_LTOPLUGIN off yet

Yeah that should do. The .so copy is only encouraged when wanting to keep LDC independent from a shared system LLVM (as its version must be in sync with the LLVM LDC was linked against), in which case LLVM is usually linked statically.

**Comment by Geod24** [comment]
Ping @Bo98

**Pull request closed without merging**
