### PR TITLE
terraform_landscape 0.2.0

### PR DESCRIPTION
**Pull request by mwarkentin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Created w/ `brew bump-formula-pr --strict --url=https://github.com/coinbase/terraform-landscape/archive/v0.2.0.tar.gz terraform_landscape`

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> gem install /Users/brew/Library/Caches/Homebrew/terraform_landscape--commander--4.4.5.gem --no-document --install-dir /usr/local/Cellar/terraform_landscape/0.2.0/libexec
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: commander requires highline (~> 1.7.2)
```

**Comment by mwarkentin** [comment]
@fxcoudert Sorry about that, not super familiar w/ the ruby ecosystem. Any good way for me to install this into a "sandbox" locally where I could reproduce? The install command in the PR description worked for me..

**Comment by DomT4** [comment]
Try moving the `highline` resource to the top of the `resources` list.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/249f3b9a9877d9e4d1375d6803a02f8178ca1062. Thank you for your contribution to Homebrew @mwarkentin; we appreciate it! :smiley_cat:

**Pull request closed without merging**
