### PR TITLE
php 7.3.8

### PR DESCRIPTION
**Pull request by Toflar**
Updated formula to php 7.3.8.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by Toflar** [comment]
Hey @derrabus, this is my first contribution to the formula. Can you tell me what else I need to do (and maybe show me that `brew bump-formula-pr` thingy at SymfonyCon 😄 ).

**Comment by derrabus** [comment]
@Toflar The PR looks good to me. The bot probably expected the PR title to be `<formula> <version>`, so in this case "php 7.3.8" (without the `@`) and in case of #42671 "php@7.2 7.2.21", but that's a guess. I'm just an occasional contributor myself. 🤷‍♂

**Review by chalasr — APPROVED** [review]

**Comment by derrabus** [comment]
pinging @SMillerDev because you've merged previous PRs on the php formulae: Is there anything we can do to move this forward? This release contains an important fix for Symfony, see symfony/symfony#32395.

**Comment by SMillerDev** [comment]
Thanks @Toflar

**Comment by danherd** [comment]
Would be great if #42671 could be merged ASAP as well, as that also fixes the Symfony bug.

**Comment by SMillerDev** [comment]
It'd be even better if I'd get generously payed tons of money for my open source contributions. But until, and even when, that's the case you'll have to wait until someone has time. In my case that means waiting until I'm done with my day job.

**Comment by danherd** [comment]
> It'd be even better if I'd get generously payed tons of money for my open source contributions. But until, and even when, that's the case you'll have to wait until someone has time. In my case that means waiting until I'm done with my day job.

I really appreciate what you've done here and I apologise for hassling you.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Pull request closed without merging**
