### PR TITLE
vapoursynth 33.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
This needs the new zimg, which is having issues on 10.9 and 10.10

https://github.com/Homebrew/homebrew-core/pull/3956
https://github.com/Homebrew/homebrew-core/pull/4109

CC @apjanke @DomT4

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@apjanke woo hoo! zimg fix has paid for itself! :green_apple:

**Comment by apjanke** [comment]
Nice!

**Pull request closed without merging**
