### PR TITLE
aircrack-ng: also install experimental tools

### PR DESCRIPTION
**Pull request by vioint**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Hi, added this option for building the extra tools that are included in aircrack-ng suite, I hope this will benefit everybody. Let me know if there are any questions or changes needed to include this.

### CODE REVIEW

**Comment by vioint** [comment]
Hi Team, 
A lot of people would be happy to see these tools incorporated into this formula, 
is any more info needed in order to have this merged?

**Comment by fxcoudert** [comment]
Hi @vioint, thanks for the pull request. Given that these experimental tools are not built by default and enabled by upstream, I am going to decline. But you (or other people interested) could host the full suite of tools in a personal tap https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by vioint** [comment]
Hi @fxcoudert ,
Thanks for the reply, I considered this reasoning too before adding this PR but after seeing this is pretty much the same case as Docker's experimental features (and I'm sure quite a few other formulae out there), I thought it deserves to be included as an optional flag.
Having said that, if you're willing to reconsider merging this based it would be great and although I am aware of the personal tap option, this alone wouldn't warrant yet-another-tap out there.

Thanks!

**Comment by ilovezfs** [comment]
If it's not adding any dependencies and only building more programs I think we can just include them by default.

**Comment by vioint** [comment]
@ilovezfs : yep, it provides extra binaries and doesn't add any dependencies for the build.

**Comment by ilovezfs** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @vioint!

Side note: please make sure the email you use for commits is actually associated with your GitHub account.

**Pull request closed without merging**
