### PR TITLE
rpm 4.18.1 (add back)

### PR DESCRIPTION
**Pull request by lionelfleury**
Add rpm 4.18.1 for MacOS users (taken from commit before 4.19.0).
Version 4.19.0 being Linux only.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions) and why we might want to ship an older version?

**Comment by kishaningithub** [comment]
Why is rpm 4.19 linux only? Cant it also be built for mac?

**Comment by SMillerDev** [comment]
> Why is rpm 4.19 linux only? Cant it also be built for mac?

It can not, see https://github.com/Homebrew/homebrew-core/pull/144033

**Comment by iMichka** [comment]
See https://github.com/orgs/Homebrew/discussions/4826 for a longer discussion. Given this, I will sadly have to close this pull request. Sorry but passing on this as upstream will not support macOS, and we can't afford to keep an older "unmaintained" version around in Homebrew-core.

**Pull request closed without merging**
