### PR TITLE
voldemort 1.10.18

### PR DESCRIPTION
**Pull request by ilovezfs**
build system now uses gradle instead of ant

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
Maybe worth env scripting `VOLDEMORT_HOME` to the executables & ditching the caveat?

**Comment by ilovezfs** [comment]
@DomT4 how's that?

**Comment by DomT4** [comment]
If it works, and it seems to, 👍. Nice work.

**Comment by ilovezfs** [comment]
@DomT4 Thanks. Also, working on the env scripts caused me to find a bug: the name of the environment variable for the config directory had changed, but I'd not noticed (not sure in which version that change actually occurred - the version in core right now may be broken).

**Comment by DomT4** [comment]
Heh, if it turns out that change was made prior to this version it's quite telling in terms of how few people bother to read caveats that nobody has reported that to us.

**Comment by ilovezfs** [comment]
Appears to have been VOLDEMORT_CONFIG_DIR since 2011 https://github.com/voldemort/voldemort/commit/903943ff3137ceb95566c2b5a5dfba0f52005aa4

Our VOL_CONF_DIR goes all the way back to when the formula was originally added https://github.com/Homebrew/homebrew-core/blob/00b63b132c7b4ae15528b303180e315449680b50/Formula/voldemort.rb but I can't find any reference to it in the current sources, so who knows when that was last a thing that worked!

It also makes me wonder if anyone actually uses this formula. lol

**Comment by DomT4** [comment]
According to GA nobody is using this formula. According to Bintray, 24 downloads in the last year, including 8 today.

**Comment by ilovezfs** [comment]
So 1/3 of a download a week, not including today. Well, that's not zero, I suppose. Ahem.

**Comment by DomT4** [comment]
Not our most popular formula it's fair to say.

**Comment by ilovezfs** [comment]
Perhaps we can have homebrew/core and homebrew/not-so-core.

**Comment by UniqMartin** [comment]
I want to have `homebrew/turtles` and `homebrew/rabbits` for different release frequencies. :joy:

**Pull request closed without merging**
