### PR TITLE
Update Kubeless to v0.3.4

### PR DESCRIPTION
**Pull request by andresmgot**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
duplicates https://github.com/Homebrew/homebrew-core/pull/22894 but I will defer to your PR :)

**Comment by andresmgot** [comment]
oh @ilovezfs are those PR automated? That's great, I was thinking on creating the automation myself but I see it is not needed :)

**Comment by ilovezfs** [comment]
Only semi-automated unless you consider me to be a :robot:. I would recommend you automate it still :)

**Comment by andresmgot** [comment]
Ah, I see. Thanks for checking then!

**Comment by ilovezfs** [comment]
Thanks for the upgrade @andresmgot! Shipped. Note the standard git commit subject for a version bump is `kubeless 0.3.4`

**Pull request closed without merging**
