### PR TITLE
varnish 6.2.0

### PR DESCRIPTION
**Pull request by kkirsche**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by kkirsche** [comment]
Release Page: https://varnish-cache.org/releases/rel6.2.0.html#rel6-2-0

**Comment by fxcoudert** [comment]
```
checking for dot... no
configure: WARNING: dot not found - build will fail if svg files are out of date.
checking for a Python interpreter with version >= 3.4... none
configure: error: Python >= 3.4 is required.
```

**Comment by kkirsche** [comment]
OK, so dot is part of graphviz, so added that. Also added python as a dependency which should address the python interpreter piece, if I understand Homebrew's build directives correctly

**Comment by kkirsche** [comment]
```
Error Message
failed: brew audit varnish --online
Stacktrace
        ==> Installing 'bundler' gem
Successfully installed bundler-2.0.1
1 gem installed
Error: 1 problem in 1 formula detected
varnish:
  * C: 17: col 3: dependency "python" (line 17) should be put before dependency "sphinx-doc" (line 16)
```

seems my alphabetical ordering was not correct

**Comment by kkirsche** [comment]
Pushed update to fix this

**Comment by kkirsche** [comment]
Yay! That fixed it 👍 :)

**Comment by lembacon** [comment]
Thanks @kkirsche!

**Pull request closed without merging**
