### PR TITLE
stella 7.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by daeho-ro** [comment]
The script path for macos looks changed from `src/macos` to `src/os/macos`.

**Comment by stefanb** [comment]
Not yet latest on https://github.com/stella-emu/stella/releases

**Comment by daeho-ro** [comment]
It is released today.

**Comment by chenrui333** [comment]
```
  In file included from /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/gui/SnapshotDialog.cxx:20:
  In file included from ../../gui/EditTextWidget.hxx:22:
  In file included from ../../gui/EditableWidget.hxx:25:
  In file included from ../../gui/ContextMenu.hxx:24:
  /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/common/Variant.hxx:52:65: error: no member named 'view' in 'std::ostringstream'
      Variant(Int32 i)  { buf().str(""); buf() << i; data = buf().view(); }
                                                            ~~~~~ ^
  /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/common/Variant.hxx:53:65: error: no member named 'view' in 'std::ostringstream'
      Variant(uInt32 i) { buf().str(""); buf() << i; data = buf().view(); }
                                                            ~~~~~ ^
  /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/common/Variant.hxx:54:65: error: no member named 'view' in 'std::ostringstream'
      Variant(float f)  { buf().str(""); buf() << f; data = buf().view(); }
                                                            ~~~~~ ^
  /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/common/Variant.hxx:55:65: error: no member named 'view' in 'std::ostringstream'
      Variant(double d) { buf().str(""); buf() << d; data = buf().view(); }
                                                            ~~~~~ ^
  /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/common/Variant.hxx:56:65: error: no member named 'view' in 'std::ostringstream'
      Variant(bool b)   { buf().str(""); buf() << b; data = buf().view(); }
                                                            ~~~~~ ^
  /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/common/Variant.hxx:57:78: error: no member named 'view' in 'std::ostringstream'
      Variant(const Common::Size& s) { buf().str(""); buf() << s; data = buf().view(); }
                                                                         ~~~~~ ^
  /tmp/stella-20250123-5141-ydz7mo/stella-7.0c/src/common/Variant.hxx:58:79: error: no member named 'view' in 'std::ostringstream'
      Variant(const Common::Point& s) { buf().str(""); buf() << s; data = buf().view(); }
                                                                          ~~~~~ ^
```

**Comment by stefanb** [comment]
Superseded by
* https://github.com/Homebrew/homebrew-core/pull/205268

**Pull request closed without merging**
