### PR TITLE
ispell 3.4.01

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
BSD-variant.


<details>
<summary>license file</summary>

```
/*
 * ispell.c - An interactive spelling corrector.
 *
 * Copyright (c), 1983, by Pace Willisson
 *
 * Copyright 1992, 1993, 1999, 2001, 2005, Geoff Kuenning, Claremont, CA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All modifications to the source code must be clearly marked as
 *    such.  Binary redistributions based on modified source code
 *    must be clearly marked as modified versions in the documentation
 *    and/or other materials provided with the distribution.
 * 4. The code that causes the 'ispell -v' command to display a prominent
 *    link to the official ispell Web site may not be removed.
 * 5. The name of Geoff Kuenning may not be used to endorse or promote
 *    products derived from this software without specific prior
 *    written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY GEOFF KUENNING AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL GEOFF KUENNING OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
```

</details>

**Comment by carlocab** [comment]
Since the license is `:cannot_represent`, can we make sure a copy of the license can be found in the prefix?

**Comment by chenrui333** [comment]
> Since the license is `:cannot_represent`, can we make sure a copy of the license can be found in the formula `prefix`? I think this is needed to comply with the license terms:
> 
> ```
>  Redistributions in binary form must reproduce the above copyright notice
> ```
I think it is fine, they did not include the LICENSE or COPYING in the artifact, it is hard for us to include it in the binary installation folder.

**Comment by carlocab** [comment]
>I think it is fine

I'm not convinced it is fine since the conditions of the license require that anyone who redistributes their software (that's us) must reproduce their copyright notice. If we cannot reproduce their copyright notice, we have violated the conditions of their license.

**Comment by SMillerDev** [comment]
Yeah, I guess we have to download it as a resource then. We shouldn't willingly violate licenses.

**Comment by chenrui333** [comment]
looks like this release is gone in the upstream :(

```
$ curl -I https://www.cs.hmc.edu/~geoff/tars/ispell-3.4.01.tar.gz
HTTP/2 404
date: Fri, 25 Dec 2020 21:34:12 GMT
server: Apache/2.4.46 (Gentoo)
vary: accept-language,accept-charset
accept-ranges: bytes
x-clacks-overhead: GNU Terry Pratchett
strict-transport-security: max-age=15768000; includeSubDomains
content-type: text/html; charset=utf-8
content-language: en
```

**Comment by chenrui333** [comment]
Close the PR for now.

**Comment by chenrui333** [comment]
reopen the PR as the artifact is back.

**Comment by chenrui333** [comment]
informed upstream with the license situation.

**Review by SeekingMeaning — APPROVED** [review]

**Pull request closed without merging**
