### PR TITLE
ocaml 5.1.0; ocaml@4 4.14.1 (new formula); ledit 2.06

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Still need to figure out `coccinelle`. Using `ocaml@4` would require locally building `ocaml-findlib` and I don't know situation with runtime dependency (as `ocaml@4` would be keg-only and not have the `HOMEBREW_PREFIX` prefix-logic).

Backporting OCaml 5 fixes is tedious as I have tried applying a number of patches so far and it still doesn't build. Also, HEAD may work on Linux but there are build issues on macOS due to `LD_LIBRARY_PATH` usage.

Probably will end up going with `ocaml@4` once I figure out what is needed to get it working.

**Comment by cho-m** [comment]
Going to try deferring `ott` and `ledit` updates to future PR and re-run with `ocaml@4`-based build.

**Comment by alebcay** [comment]
Regarding `ott` update, @EricFromCanada posted [this](https://github.com/Homebrew/homebrew-core/pull/139613#issuecomment-1684342932) in a different PR:

> I added `ocaml-findlib` as a build requirement which fixed the initial error but now it looks like we have new problem - `ott` now depends on `ocamlgraph` and that needs a new formula.  I will try to submit one in the next few days, but any other contributors should feel free to do so before me!

I had some time to take a look at `ocamlgraph`. Looks like it depends on `lablgtk2`, provided by our lablgtk formula. But `lablgtk` is deprecated because it depends on `gtk+` (GTK+ 2), which is no longer supported upstream.

I attempted to build `lablgtk3` (3.x branch of `lablgtk` sources) but that seems to depend on OCaml package `cairo2`, which in turn depends on `lablgtk2`. (And this is all without testing that `ocamlgraph` can even use `lablgtk3`). So it would appear that we're at an impasse on this front.

**Comment by cho-m** [comment]
> I had some time to take a look at `ocamlgraph`. Looks like it depends on `lablgtk2`, provided by our lablgtk formula. But `lablgtk` is deprecated because it depends on `gtk+` (GTK+ 2), which is no longer supported upstream.
> 
> I attempted to build `lablgtk3` (3.x branch of `lablgtk` sources) but that seems to depend on OCaml package `cairo2`, which in turn depends on `lablgtk2`. (And this is all without testing that `ocamlgraph` can even use `lablgtk3`). So it would appear that we're at an impasse on this front.

The easiest way to build newer `ott` is just let `opam` build all dependencies and statically link them (https://github.com/Homebrew/homebrew-core/commit/29eff10c68d8cdea985b2f5b716bf240edc4ee51). But I dropped version updates for `ott` and `ledit` since the current build environment is causing some odd behavior.

**Comment by cho-m** [comment]
No idea why `ledit` fails in Linux test. Easiest option may be to just drop Linux bottle for now and retry in separate PR.

**Comment by cho-m** [comment]
Only a CI issue remains:
```
Error: Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz
```

Not entirely sure why it is trying to download `libvorbis` source.

I think it is okay to ignore this failure.

**Comment by EricFromCanada** [comment]
> ```
> Error: Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz
> ```
It looks like the fix for mirrors not being checked in https://github.com/Homebrew/brew/pull/16079 isn't applying when one of the URLs requires brewed curl. (cc @Bo98)

**Comment by Bo98** [comment]
`brew fetch` I believe does not install curl for you so we do it in test-bot instead and the current code presumably doesn't yet support the `CI-build-dependents-from-source` scenario.

Though really our `using: :homebrew_curl` should probably be sometthing like `using: :tls_1_3` as system curl works fine since macOS 12.3 AFAIK.

**Comment by cho-m** [comment]
Does test-bot really need to build `libvorbis` from source here? I think it is being fetched for `pdfsandwich` which has a build dependency on `ocaml`, but not sure why it needs the source code rather than bottle.

**Comment by Bo98** [comment]
Probably not, yeah. Will check.

**Comment by cho-m** [comment]
For this PR, I did locally confirm `pdfsandwich` built & passed test.

Will remove build-from-source and rerun to try to get clean output.

**Review by SMillerDev — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Great work @cho-m! Thanks!

**Pull request merged**
