### PR TITLE
ode: Fix sha256 and add minimum test

### PR DESCRIPTION
**Pull request by jslee02**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR updates the sha256 field and also add missing test block (see #11898).

### CODE REVIEW

**Comment by DomT4** [comment]
Why did the checksum change?

**Comment by jslee02** [comment]
> Why did the checksum change?

[ODE changed the tag to a different changeset](https://bitbucket.org/odedevs/ode/commits/6598a30021688018a0995577df52a5de8806af86).

**Comment by JCount** [comment]
@jslee02 Is there any reason not to also update this to the most recent ODE release, 15.2 I believe, as well in this PR?

**Comment by jslee02** [comment]
> @jslee02 Is there any reason not to also update this to the most recent ODE release, 15.2 I believe, as well in this PR?

When I tested ODE 0.15.2 (and 0.15.1), it couldn't be compiled by `brew install --build-from-source ode --with-libccd --with-enable-double-precision` with the following errors:
```
==> make
Last 15 lines from /Users/jeongseoklee/Library/Logs/Homebrew/ode/03.make:
libtool: compile:  clang++ -DPACKAGE_NAME=\"ou\" -DPACKAGE_TARNAME=\"ou\" -DPACKAGE_VERSION=\"0\" "-DPACKAGE_STRING=\"ou 0\"" -DPACKAGE_BUGREPORT=\"oleh_derevenko@users.sourceforge.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"ou\" -DVERSION=\"0\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBC=1 -DHAVE_LIBPTHREAD=1 -D_REENTRANT=1 -DSTDC_HEADERS=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_STDBOOL_H=1 -DHAVE_PTRDIFF_T=1 -DHAVE_MEMSET=1 -DMAC_OS_X_VERSION=1050 -D_OU_TARGET_OS=_OU_TARGET_OS_MAC -I. -I../../include -D_OU_NAMESPACE=odeou -D_OU_FEATURE_SET=_OU_FEATURE_SET_ATOMICS -fno-exceptions -fno-rtti -g -O2 -MT threadlocalstorage.lo -MD -MP -MF .deps/threadlocalstorage.Tpo -c threadlocalstorage.cpp -o threadlocalstorage.o >/dev/null 2>&1
In file included from atomic.cpp:32:
../../include/ou/atomic.h:717:2: error: unknown type name '__ou_cmpxchg_value_t'
        __ou_cmpxchg_value_t aoOldValue = *paoDestination;
        ^
libtool: compile:  clang++ -DPACKAGE_NAME=\"ou\" -DPACKAGE_TARNAME=\"ou\" -DPACKAGE_VERSION=\"0\" "-DPACKAGE_STRING=\"ou 0\"" -DPACKAGE_BUGREPORT=\"oleh_derevenko@users.sourceforge.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"ou\" -DVERSION=\"0\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBC=1 -DHAVE_LIBPTHREAD=1 -D_REENTRANT=1 -DSTDC_HEADERS=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_STDBOOL_H=1 -DHAVE_PTRDIFF_T=1 -DHAVE_MEMSET=1 -DMAC_OS_X_VERSION=1050 -D_OU_TARGET_OS=_OU_TARGET_OS_MAC -I. -I../../include -D_OU_NAMESPACE=odeou -D_OU_FEATURE_SET=_OU_FEATURE_SET_ATOMICS -fno-exceptions -fno-rtti -g -O2 -MT customization.lo -MD -MP -MF .deps/customization.Tpo -c customization.cpp -o customization.o >/dev/null 2>&1
1 error generated.
make[2]: *** [atomic.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -DPACKAGE_NAME=\"ou\" -DPACKAGE_TARNAME=\"ou\" -DPACKAGE_VERSION=\"0\" "-DPACKAGE_STRING=\"ou 0\"" -DPACKAGE_BUGREPORT=\"oleh_derevenko@users.sourceforge.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"ou\" -DVERSION=\"0\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBC=1 -DHAVE_LIBPTHREAD=1 -D_REENTRANT=1 -DSTDC_HEADERS=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_STDBOOL_H=1 -DHAVE_PTRDIFF_T=1 -DHAVE_MEMSET=1 -DMAC_OS_X_VERSION=1050 -D_OU_TARGET_OS=_OU_TARGET_OS_MAC -I. -I../../include -D_OU_NAMESPACE=odeou -D_OU_FEATURE_SET=_OU_FEATURE_SET_ATOMICS -fno-exceptions -fno-rtti -g -O2 -MT malloc.lo -MD -MP -MF .deps/malloc.Tpo -c malloc.cpp -o malloc.o >/dev/null 2>&1
mv -f .deps/threadlocalstorage.Tpo .deps/threadlocalstorage.Plo
mv -f .deps/customization.Tpo .deps/customization.Plo
mv -f .deps/malloc.Tpo .deps/malloc.Plo
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by jslee02** [comment]
Could we merge this now as this prevent from installing `ode`, then update to the latest version in a separate PR once the issue resolved?

**Comment by ilovezfs** [comment]
@jslee02 sorry, I'm not sure I understand. Why was 0.14 retagged if the problem is with 0.15.1/0.15.2?

**Comment by jslee02** [comment]
0.14 was retagged for other reason, which I don't know. 0.14 works anyway, but just the sha256 needs to be updated.

I mentioned the problem of 0.15.1/0.15.2 to explain why this PR just update to the latest version of ode per @JCount.

**Comment by ilovezfs** [comment]
>0.14 was retagged for other reason, which I don't know. 0.14 works anyway, but just the sha256 needs to be updated.

We'll need to understand why it was retagged before this is merged.

**Comment by jslee02** [comment]
I'm not the author. Let me ask the author then.

**Comment by ilovezfs** [comment]
@jslee02 thank you!

**Comment by jslee02** [comment]
[The author said](https://bitbucket.org/odedevs/ode/issues/40/build-error-of-0151-and-0152-with-libccd#comment-36889193):
> I had found that I had missed a version number in one place in configure.ac and left it as "0.13.2" instead of "0.14". So I had to re-tag.

So it seems there was no change in the code but just the version number fix.

**Comment by fxcoudert** [comment]
That sounds OK. We probably want to bump revision, though, in case the version number change impacted some libraries/binaries…

**Comment by jslee02** [comment]
I don't have an objection that idea as long as it's acceptable that the formula is allowed to have a different version number (I guess it would be 0.14.1?) from the upstream. If this makes sense, I will update the version to 0.14.1.

**Comment by JCount** [comment]
@jslee02 The revision is separate from the version number. It is used solely by Homebrew internally. In this instance a `revision 1` line would be inserted between the `sha256` and `head` lines.

**Comment by jslee02** [comment]
Oh, I didn't know that. Added `revision 1`, thanks!

**Comment by JCount** [comment]
No problem, happy to explain. 😄

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks very much @jslee02 for the pull request!

**Pull request closed without merging**
