### PR TITLE
openvino: 2023.1.0

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Old passed PR https://github.com/Homebrew/homebrew-core/pull/134935, but no one wanted to review it, so have to re-create to make changes more visible.

**Comment by chenrui333** [comment]
sorry, missed it. thanks for creating this new one.

**Comment by chenrui333** [comment]
but that PR is running??

image

**Comment by ilya-lavrenov** [comment]
> but that PR is running??
> 
> image

commit is the same. 

I suppose we need one more label for long timeout.

**Comment by ilya-lavrenov** [comment]
Please, pay attention to this PR.

**Comment by chenrui333** [comment]
we pay attention to it, but we can run slim due to the mass bottling thing for the sonoma thing

**Comment by chenrui333** [comment]
once node@18 is over, we will do this, https://github.com/Homebrew/homebrew-core/pull/143899

**Comment by ZhongRuoyu** [comment]
@ilya-lavrenov

We seek your cooperation to allow maintainers some more time to review PRs, please. Closing an all-green PR only adds more burden to our CI infrastructure, which, despite operating at full capacity, is still not enough to meet our demand. There are [a long list of PRs pending CI run](https://github.com/Homebrew/homebrew-core/labels/long%20build) that equally require our attention.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @ZhongRuoyu! 💯 

And thanks @ilya-lavrenov for your patience! 😄 

we are getting there. lots of stuff going on with limited resources.

**Review by chenrui333 — APPROVED** [review]

**Comment by fxcoudert** [comment]
I don't think it will automerge. There seems to be an issue with the CI (it has run twice in the same run?)

**Comment by ZhongRuoyu** [comment]
> There seems to be an issue with the CI

Probably because I cancelled the workflow adding back the long timeout label. 🙊

**Comment by ZhongRuoyu** [comment]
Rebased to resolve conflict with #143084.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@chenrui333 @fxcoudert @ZhongRuoyu 
Thanks for your help in mering OpenVINO 2023.1.0 🤗 

Could you please give a hint when it will be available for macOS 14 given that I have provided a patch in this PR?

**Comment by ZhongRuoyu** [comment]
> Could you please give a hint when it will be available for macOS 14 given that I have provided a patch in this PR?

When this workflow finishes: https://github.com/Homebrew/homebrew-core/actions/runs/6259117290

**Pull request merged**
