### PR TITLE
hashlink: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by tobil4sk** [comment]
@danielnachun Hi, what issue was this fixing exactly? Is there anything that should also be fixed in hashlink itself for the next release?

**Comment by danielnachun** [comment]
This PR made 3 changes to the formula:
1) Add `mesa` as a dependency on Linux for OpenGL support.
2) Initialize `LIBFLAGS` to be equal to the value of `EXTRA_LFLAGS` instead of nothing.
3) In the test block, add a missing RPATH on Linux  so that shared libraries can be found and change the ordering of the `LDFLAGS` so they work on Linux systems that use `--as-needed` with their dynamic linker.

Of these changes, only number 2 would make sense to upstream as it is not Homebrew-specific.  Right now in the `Makefile`, `EXTRA_LFLAGS` can be used by the user to provide additional flags to the linker, but is only used for building the `hl` and `hlc` executables.  There doesn't seem to be a way for the user to specify additional linker flags for linking the libraries (`libhl` and `.dll` files) as `LIBFLAGS` is initialized to nothing.  I think the most sensible ways to fix this would be:
1) Initialize `LIBFLAGS` as `LIBFLAGS ?=` instead of `LIBFLAGS =` so the user can provide an initial value.
2) Pass `EXTRA_LFLAGS` to the libraries as well as the executables (maybe just stick `EXTRA_LFLAGS` after `LIBFLAGS`).
3) Create a new variable like `EXTRA_LIBFLAGS` that is added after `LIBFLAGS` if you want to keep those flags separate from `EXTRA_LFLAGS` for the executables.

From our perspective any of these options would be equally valid as we'd just add the extra `RPATH` to whatever variable is used to pass the flags to the linker.  The reason we need to be able to pass extra linker flags when linking the libraries is because on Linux shared libraries are always found using RPATH, whereas on macOS the linker usually uses install names with the exact path to the library.  `brew` automatically adds an RPATH to `lib` but in this case we have libraries in `libexec/lib`, which we don't automatically add as it may contain shared libraries we don't want to link to.

**Comment by tobil4sk** [comment]
Thanks for the response! Is there any particular reason to set the rpath to the dynamic libraries? On my Linux system it seems fine as long as the rpath is set for the `hl` executable, or for the executable compiled from `hlc` code. I guess maybe it is useful for preventing system libraries in `/usr/lib/` being loaded accidentally instead of the intended ones?

**Comment by danielnachun** [comment]
> Thanks for the response! Is there any particular reason to set the rpath to the dynamic libraries? On my Linux system it seems fine as long as the rpath is set for the `hl` executable, or for the executable compiled from `hlc` code. I guess maybe it is useful for preventing system libraries in `/usr/lib/` being loaded accidentally instead of the intended ones?

We have an automated check for any dynamically linked binary that will throw an error if the loader reports that it cannot find a shared library for that binary.  In this case we were getting that error thrown for the dynamic libraries.  We definitely do want to avoid loading shared libraries in `/usr/lib` or other default locations but I think our larger concern is that the binary might not work if it's trying to load libraries that cannot be found.

This may be an edge case where these dynamic libraries (especially the ones with `.dll` extensions) are not likely to be linked by anything other than `hlc` and the user is expected to set the right rpath when using `hlc`.  However we try to play it safe and make sure that the loader can find all linked libraries for dynamically linked binaries without any special intervention.  Our precaution here is partly motivated by the fact that we isolate each package into its own directory rather than having a single library folder as is done by system package managers.  Because a lot of software is written assuming that all shared libraries will be in the same directory, this can lead to problems with finding libraries at runtime so we try to anticipate linkage issues with these automated checks.

**Pull request closed without merging**
