### PR TITLE
gd 2.2.4

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes #9042.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Honestly, I'd like to see them tag a new version given the prior release was in July.

**Comment by nijikon** [comment]
@ilovezfs That's probably not going to happen as they release new version 10 days ago. Let's just merge this.

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
That is my point. I don't think it's OK if they plan to leave macOS broken for 7 months now.

**Comment by DomT4** [comment]
There's known security issues in the existing release prior to this one...

**Comment by ilovezfs** [comment]
I left a nasty gram https://github.com/libgd/libgd/issues/377.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks Dom

**Comment by DomT4** [comment]
No worries @ilovezfs. Understand your position here too, but you know well enough that I'm loathe to let security issues sit for long 😄.

**Comment by ilovezfs** [comment]
@DomT4 Looks like the whining may bear Whine Fruit: https://github.com/libgd/libgd/issues/377#issuecomment-275848245

**Comment by DomT4** [comment]
Nice! Presumably not everyone in the world is using Homebrew, so a released fix is definitely a 👍.

**Pull request closed without merging**
