### PR TITLE
fx 30.0.0

### PR DESCRIPTION
**Pull request by antonmedv**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>**Fx - terminal JSON viewer**.

<a href="https://fx.wtf">fx preview</a>
</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/fx/30.0.0/bin/fx
  panic: open /dev/tty: no such device or address
```

**Comment by antonmedv** [comment]
This is known issue, as fx in TUI app. 

Strange why this return was not executed? 

```
   # Fix `panic: open /dev/tty: no such device or address` error
    return if OS.linux? && ENV["HOMEBREW_GITHUB_ACTIONS"]
```

**Comment by chenrui333** [comment]
> This is known issue, as fx in TUI app.

oh interesting, i thought it was runner issue, do you have linked report or PRs?

> Strange why this return was not executed?
> 
>   Fix `panic: open /dev/tty: no such device or address` error
>    return if OS.linux? && ENV["HOMEBREW_GITHUB_ACTIONS"]

what do you mean?

**Comment by antonmedv** [comment]
I think I fixed tests.

**Comment by antonmedv** [comment]
Now fx consists of two parts: interactive JSON viewer and cli JSON processor. TUI is written in go, and cli JSON processor uses node or deno.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Looks good, thanks!

**Pull request merged**
