### PR TITLE
webify 1.5.0 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
some audit failure:

```
Error: 1 problem in 1 formula detected
webify:
  * GitHub repository too new (<30 days old)

```

**Comment by alebcay** [comment]
Yeah, repo looks like 3 weeks old. Will just wait another week or so and try CI again and see if repo is old enough 😉.

**Comment by chenrui333** [comment]
This kind of reminds me `https://github.com/BBVA/kapow`, which seems more popular?

**Comment by chenrui333** [comment]
let's go for the merge, I am eager to try it out. 👍

**Pull request closed without merging**
