### PR TITLE
mpv: remove Xcode build dependency

### PR DESCRIPTION
**Pull request by triallax**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by mhmdanas** [comment]
And this seems to be failing on 10.15. Is there some way not to require Xcode only on macOS 11 or later?

**Comment by carlocab** [comment]
```ruby
uses_from_macos :xcode, since: :big_sur
```
might work.

It's a little abusive of the DSL though. CC @Homebrew/core in case of objections.

**Comment by mhmdanas** [comment]
@carlocab maybe I'm mistaken, but I think that line does the opposite of what I'm asking for?

**Comment by Bo98** [comment]
Does the build work if you do something like:

```rb
if OS.mac? && (sdk = MacOS.sdk)
  ENV["MACOS_SDK"] = sdk.path
  ENV["MACOS_SDK_VERSION"] = sdk.version
end
```

**Comment by mhmdanas** [comment]
@Bo98 it doesn't; I get this error on the configure step:
```
Last 15 lines from /Users/mhmdanas/Library/Logs/Homebrew/mpv/02.python3:
  File "/private/tmp/mpv-20220526-25433-pcmmpv/mpv-0.34.1/waftools/dependencies.py", line 47, in check
    self.check_autodetect_func()
  File "/private/tmp/mpv-20220526-25433-pcmmpv/mpv-0.34.1/waftools/dependencies.py", line 76, in check_autodetect_func
    if self.attributes['func'](self.ctx, self.identifier):
  File "/private/tmp/mpv-20220526-25433-pcmmpv/mpv-0.34.1/waftools/checks/generic.py", line 180, in fn
    return all([check(ctx, dependency_identifier) for check in checks])
  File "/private/tmp/mpv-20220526-25433-pcmmpv/mpv-0.34.1/waftools/checks/generic.py", line 180, in <listcomp>
    return all([check(ctx, dependency_identifier) for check in checks])
  File "/private/tmp/mpv-20220526-25433-pcmmpv/mpv-0.34.1/waftools/checks/generic.py", line 199, in fn
    if StrictVersion(ctx.env.MACOS_SDK_VERSION) >= StrictVersion(version):
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 54, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 157, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '12'
```

**Comment by Bo98** [comment]
Ok maybe try `ENV["MACOS_SDK_VERSION"] = "#{sdk.version}.0"` instead.

**Comment by mhmdanas** [comment]
Works now, let's see how the CI fares...

**Comment by carlocab** [comment]
> @carlocab maybe I'm mistaken, but I think that line does the opposite of what I'm asking for?

Well, there's a reason why I said it's abusive of the DSL.

```ruby
uses_from_macos "foo", since: :bar
```
is a no-op on `:bar` and newer, and is
```ruby
depends_on "foo"
```
otherwise.

**Comment by mhmdanas** [comment]
@carlocab wow, that's incredibly wacky.

**Comment by Bo98** [comment]
Oh I see we're hitting a Swift compiler crash now.

I think the problem is Swift quite often breaks when using older SDKs, which is kind of the point why we're using `depends_on :xcode` to begin with - Swift from Xcode is only really guaranteed to work with the SDK from Xcode.

If you are saying it works without Xcode installed, what might work is adding `ENV["SWIFT"] = "#{MacOS::CLT::PKG_PATH}/usr/bin/swift" if MacOS::CLT.installed?` to what we have to also force usage of the CLT Swift. Not entirely sure how well it'll work but there's probably not much other options.

**Comment by MikeMcQuaid** [comment]
Given this is a build-time only dependency and we don't support building from source: I don't think it's worth trying to iterate on this too much, honestly.



> It's a little abusive of the DSL though.

I agree, this is weird 👎🏻

**Comment by mhmdanas** [comment]
Nothing I tried so far works, so closing.

**Pull request closed without merging**
