### PR TITLE
enchant 2.2.0

### PR DESCRIPTION
**Pull request by RandomDSdevel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
@Homebrew/homebrew-core/maintainers:  I think a build or test failed here somewhere since I'm seeing cascading test and build failures rather early on in the CI logs.  (I would have tested a from-source build locally, but I'm not aware of any way you can start one from within `brew bump-formula-pr` at the moment.)  It seems to me that it's building Enchant itself, or at least its bottle, that failed, but I'd need more CI logs to be sure…

**Comment by ilovezfs** [comment]
@RandomDSdevel it's an API breaking release. Executable name changed, library path changed, include path changed, all reverse dependencies need to be revision bumped, and most (all?) of them won't build or even find it.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Oh, _ouch._  So a `bump-formula-pr` won't cut it here, then.  Ah, well; _figures…_  I can only presume that the API changes in question are part of what's announced rather quietly here in [the Enchant project's release notes](https://github.com/AbiWord/enchant/blob/master/NEWS):  

> 2.2.0 (December 11, 2017)
> -------------------------
>
> This release improves support for parallel installation with other major versions of Enchant (specifically for man pages), fixes relocation support, which only partly worked (thanks to Sandro Mani), …
>
> ⋮
>
> 2.1.3 (November 26, 2017)
> --------------------------
>
> This release adds support for parallel installation with other major versions of Enchant, …

I'll look into fixing the dependents this failed upgrade attempt breaks soon-ish, but you're free to beat me to it if you feel like it, of course.

**Comment by ilovezfs** [comment]
@RandomDSdevel thanks for the pointer to the release notes. "Improves support for parallel installation" makes me think maybe we can turn that feature off and things will go back to normal.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Oh, cool.  Wonder what the `configure` switch for that might be…

**Comment by ilovezfs** [comment]
Nope looks like they're all in on that as of 2.1.3 (interesting change for a patch level release ...):

https://github.com/AbiWord/enchant/commit/8a853ad69ca8bd896723d86eea3e7573a8c11ebd

So yeah we'll need to fix/report the reverse dependencies' issues with finding things.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Bummer.  Gee, _that'll_ be fun…

**Comment by ilovezfs** [comment]
That's probably why they quickly followed 2.1.3 up with 2.2.0.

So I think what we should do is create a generic enchant.pc

```
diff --git a/Formula/enchant.rb b/Formula/enchant.rb
index 4a0ac6be3f..a6d084f3d8 100644
--- a/Formula/enchant.rb
+++ b/Formula/enchant.rb
@@ -28,6 +28,8 @@ class Enchant < Formula
 
     system "make", "install"
 
+    ln_s "enchant-2.pc", lib/"pkgconfig/enchant.pc"
+
     if build.with? "python"
       resource("pyenchant").stage do
         # Don't download and install distribute now
@@ -45,6 +47,6 @@ class Enchant < Formula
     enchant_result = text.sub("fox ", "").split.join("\n")
     file = "test.txt"
     (testpath/file).write text
-    assert_equal enchant_result, shell_output("#{bin}/enchant -l #{file}").chomp
+    assert_equal enchant_result, shell_output("#{bin}/enchant-2 -l #{file}").chomp
   end
 end
```

and revision bump

corebird
gedit
gitg
gnome-builder
gnome-recipes
gspell
gtkspell3
latexila

and see if anything still breaks.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  'Kay, I'll get on it, then.

**Comment by ilovezfs** [comment]
thx!

**Comment by RandomDSdevel** [comment]
You're welcome, @ilovezfs.  Forgot to mention I should probably wait until some other Homebrew upgrades I'm running right now finish, though, as changing Git branches out from underneath `brew`…well, _let's_ just say that _probably_ wouldn't be a good idea…

**Comment by ilovezfs** [comment]
Or you could control C and `unset HOMEBREW_BUILD_FROM_SOURCE` :trollface:

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Just wanted to let you I know I recently rebased this PR's initial change in preparation for applying the changes you said to make in [your earlier comment](https://github.com/Homebrew/homebrew-core/pull/21807#issuecomment-352273004).  I should also point out that running `brew uses --recursive --include-build --include-optional enchant` prints the following:  

```
corebird                                homebrew/php/php54-yaf                  homebrew/php/php56-uuid
gedit                                   homebrew/php/php54-yaml                 homebrew/php/php56-v8js
gitg                                    homebrew/php/php54-yar                  homebrew/php/php56-varnish
gnome-builder                           homebrew/php/php54-yaz                  homebrew/php/php56-vld
gnome-recipes                           homebrew/php/php54-yp                   homebrew/php/php56-wbxml
gspell                                  homebrew/php/php54-yrmcds               homebrew/php/php56-xcache
gtkspell3                               homebrew/php/php54-zmq                  homebrew/php/php56-xdebug
homebrew/php/phan                       homebrew/php/php54-zookeeper            homebrew/php/php56-xdiff
homebrew/php/phan@0.10                  homebrew/php/php55                      homebrew/php/php56-xhgui
homebrew/php/phan@0.8                   homebrew/php/php55-amqp                 homebrew/php/php56-xhprof
homebrew/php/php53                      homebrew/php/php55-apcu                 homebrew/php/php56-xmldiff
homebrew/php/php53-amqp                 homebrew/php/php55-augmentedtypes       homebrew/php/php56-xxtea
homebrew/php/php53-apc                  homebrew/php/php55-binpack              homebrew/php/php56-yac
homebrew/php/php53-apcu                 homebrew/php/php55-blitz                homebrew/php/php56-yaf
homebrew/php/php53-binpack              homebrew/php/php55-boxwood              homebrew/php/php56-yaml
homebrew/php/php53-blitz                homebrew/php/php55-chdb                 homebrew/php/php56-yar
homebrew/php/php53-boxwood              homebrew/php/php55-couchbase            homebrew/php/php56-yaz
homebrew/php/php53-chdb                 homebrew/php/php55-crypto               homebrew/php/php56-yp
homebrew/php/php53-couchbase            homebrew/php/php55-dbase                homebrew/php/php56-yrmcds
homebrew/php/php53-crypto               homebrew/php/php55-dbus                 homebrew/php/php56-zmq
homebrew/php/php53-dbase                homebrew/php/php55-dmtx                 homebrew/php/php56-zookeeper
homebrew/php/php53-dbus                 homebrew/php/php55-eio                  homebrew/php/php70
homebrew/php/php53-dmtx                 homebrew/php/php55-ev                   homebrew/php/php70-amqp
homebrew/php/php53-eio                  homebrew/php/php55-event                homebrew/php/php70-apcu
homebrew/php/php53-gearman              homebrew/php/php55-fast_assert          homebrew/php/php70-apcu-bc
homebrew/php/php53-geoip                homebrew/php/php55-gearman              homebrew/php/php70-ast
homebrew/php/php53-geos                 homebrew/php/php55-geoip                homebrew/php/php70-blitz
homebrew/php/php53-gmagick              homebrew/php/php55-geos                 homebrew/php/php70-couchbase
homebrew/php/php53-gmp                  homebrew/php/php55-gmagick              homebrew/php/php70-ds
homebrew/php/php53-gnupg                homebrew/php/php55-gmp                  homebrew/php/php70-ev
homebrew/php/php53-graphdat             homebrew/php/php55-gnupg                homebrew/php/php70-event
homebrew/php/php53-hprose               homebrew/php/php55-graphdat             homebrew/php/php70-gearman
homebrew/php/php53-htscanner            homebrew/php/php55-grpc                 homebrew/php/php70-geoip
homebrew/php/php53-http                 homebrew/php/php55-hprose               homebrew/php/php70-geos
homebrew/php/php53-igbinary             homebrew/php/php55-htscanner            homebrew/php/php70-gmagick
homebrew/php/php53-imagick              homebrew/php/php55-http                 homebrew/php/php70-gmp
homebrew/php/php53-intl                 homebrew/php/php55-httpparser           homebrew/php/php70-gnupg
homebrew/php/php53-ioncubeloader        homebrew/php/php55-igbinary             homebrew/php/php70-grpc
homebrew/php/php53-jsmin                homebrew/php/php55-imagick              homebrew/php/php70-hprose
homebrew/php/php53-kafka                homebrew/php/php55-intl                 homebrew/php/php70-http
homebrew/php/php53-leveldb              homebrew/php/php55-ioncubeloader        homebrew/php/php70-ice
homebrew/php/php53-libevent             homebrew/php/php55-jsmin                homebrew/php/php70-igbinary
homebrew/php/php53-libsodium            homebrew/php/php55-kafka                homebrew/php/php70-imagick
homebrew/php/php53-libvirt              homebrew/php/php55-leveldb              homebrew/php/php70-intl
homebrew/php/php53-lz4                  homebrew/php/php55-libevent             homebrew/php/php70-ioncubeloader
homebrew/php/php53-lzf                  homebrew/php/php55-libsodium            homebrew/php/php70-kafka
homebrew/php/php53-magickwand           homebrew/php/php55-libvirt              homebrew/php/php70-libsodium@1.0
homebrew/php/php53-mailparse            homebrew/php/php55-lz4                  homebrew/php/php70-lua
homebrew/php/php53-maxminddb            homebrew/php/php55-lzf                  homebrew/php/php70-lz4
homebrew/php/php53-mcrypt               homebrew/php/php55-magickwand           homebrew/php/php70-lzf
homebrew/php/php53-mecab                homebrew/php/php55-mailparse            homebrew/php/php70-mailparse
homebrew/php/php53-memcache             homebrew/php/php55-maxminddb            homebrew/php/php70-maxminddb
homebrew/php/php53-memcached            homebrew/php/php55-mcrypt               homebrew/php/php70-mcrypt
homebrew/php/php53-midgard2             homebrew/php/php55-mecab                homebrew/php/php70-mecab
homebrew/php/php53-mongo                homebrew/php/php55-memcache             homebrew/php/php70-memcache
homebrew/php/php53-mosquitto            homebrew/php/php55-memcached            homebrew/php/php70-memcached
homebrew/php/php53-msgpack              homebrew/php/php55-meminfo              homebrew/php/php70-meminfo
homebrew/php/php53-mysqlnd_ms           homebrew/php/php55-midgard2             homebrew/php/php70-molten
homebrew/php/php53-oauth                homebrew/php/php55-molten               homebrew/php/php70-mongodb
homebrew/php/php53-opcache              homebrew/php/php55-mongo                homebrew/php/php70-mosquitto
homebrew/php/php53-parsekit             homebrew/php/php55-mongodb              homebrew/php/php70-msgpack
homebrew/php/php53-pcntl                homebrew/php/php55-mosquitto            homebrew/php/php70-mustache
homebrew/php/php53-pdflib               homebrew/php/php55-msgpack              homebrew/php/php70-oauth
homebrew/php/php53-pdo-dblib            homebrew/php/php55-mustache             homebrew/php/php70-opcache
homebrew/php/php53-phalcon              homebrew/php/php55-mysqlnd_ms           homebrew/php/php70-pcntl
homebrew/php/php53-pimple               homebrew/php/php55-oauth                homebrew/php/php70-pdo-dblib
homebrew/php/php53-pinba                homebrew/php/php55-opcache              homebrew/php/php70-pdo-pgsql
homebrew/php/php53-proctitle            homebrew/php/php55-parsekit             homebrew/php/php70-phalcon
homebrew/php/php53-propro               homebrew/php/php55-pcntl                homebrew/php/php70-propro
homebrew/php/php53-protobuf             homebrew/php/php55-pdflib               homebrew/php/php70-pspell
homebrew/php/php53-pspell               homebrew/php/php55-pdo-dblib            homebrew/php/php70-pthreads
homebrew/php/php53-pthreads             homebrew/php/php55-pdo-pgsql            homebrew/php/php70-raphf
homebrew/php/php53-qr                   homebrew/php/php55-phalcon              homebrew/php/php70-rdkafka
homebrew/php/php53-raphf                homebrew/php/php55-pimple               homebrew/php/php70-redis
homebrew/php/php53-rdkafka              homebrew/php/php55-pinba                homebrew/php/php70-ref
homebrew/php/php53-redis                homebrew/php/php55-proctitle            homebrew/php/php70-scrypt
homebrew/php/php53-redland              homebrew/php/php55-propro               homebrew/php/php70-snmp
homebrew/php/php53-riak                 homebrew/php/php55-protobuf             homebrew/php/php70-sodium
homebrew/php/php53-runkit               homebrew/php/php55-pspell               homebrew/php/php70-solr
homebrew/php/php53-scrypt               homebrew/php/php55-pthreads             homebrew/php/php70-ssh2
homebrew/php/php53-snappy               homebrew/php/php55-qr                   homebrew/php/php70-stats
homebrew/php/php53-snmp                 homebrew/php/php55-raphf                homebrew/php/php70-swoole
homebrew/php/php53-sodium               homebrew/php/php55-rdkafka              homebrew/php/php70-tidy
homebrew/php/php53-solr                 homebrew/php/php55-redis                homebrew/php/php70-timecop
homebrew/php/php53-sphinx               homebrew/php/php55-redland              homebrew/php/php70-timezonedb
homebrew/php/php53-spl-types            homebrew/php/php55-riak                 homebrew/php/php70-trace
homebrew/php/php53-ssh2                 homebrew/php/php55-runkit               homebrew/php/php70-trader
homebrew/php/php53-stats                homebrew/php/php55-scrypt               homebrew/php/php70-uopz
homebrew/php/php53-stemmer              homebrew/php/php55-snappy               homebrew/php/php70-uuid
homebrew/php/php53-suhosin              homebrew/php/php55-snmp                 homebrew/php/php70-uv
homebrew/php/php53-sundown              homebrew/php/php55-sodium               homebrew/php/php70-v8js
homebrew/php/php53-svm                  homebrew/php/php55-solr                 homebrew/php/php70-xdebug
homebrew/php/php53-swoole               homebrew/php/php55-sphinx               homebrew/php/php70-xdiff
homebrew/php/php53-symfony-debug        homebrew/php/php55-spl-types            homebrew/php/php70-xmldiff
homebrew/php/php53-thrift               homebrew/php/php55-ssh2                 homebrew/php/php70-xxtea
homebrew/php/php53-tidy                 homebrew/php/php55-stats                homebrew/php/php70-yac
homebrew/php/php53-timecop              homebrew/php/php55-stemmer              homebrew/php/php70-yaf
homebrew/php/php53-timezonedb           homebrew/php/php55-suhosin              homebrew/php/php70-yaml
homebrew/php/php53-twig                 homebrew/php/php55-sundown              homebrew/php/php71
homebrew/php/php53-uploadprogress       homebrew/php/php55-svm                  homebrew/php/php71-amqp
homebrew/php/php53-uuid                 homebrew/php/php55-swoole               homebrew/php/php71-apcu
homebrew/php/php53-v8js                 homebrew/php/php55-symfony-debug        homebrew/php/php71-apcu-bc
homebrew/php/php53-varnish              homebrew/php/php55-thrift               homebrew/php/php71-ast
homebrew/php/php53-vld                  homebrew/php/php55-tidy                 homebrew/php/php71-blitz
homebrew/php/php53-wbxml                homebrew/php/php55-timecop              homebrew/php/php71-couchbase
homebrew/php/php53-xcache               homebrew/php/php55-timezonedb           homebrew/php/php71-ds
homebrew/php/php53-xdebug               homebrew/php/php55-trace                homebrew/php/php71-ev
homebrew/php/php53-xhgui                homebrew/php/php55-trader               homebrew/php/php71-event
homebrew/php/php53-xhprof               homebrew/php/php55-twig                 homebrew/php/php71-gearman
homebrew/php/php53-xmldiff              homebrew/php/php55-uopz                 homebrew/php/php71-geoip
homebrew/php/php53-xxtea                homebrew/php/php55-uploadprogress       homebrew/php/php71-geos
homebrew/php/php53-yac                  homebrew/php/php55-uuid                 homebrew/php/php71-gmagick
homebrew/php/php53-yaf                  homebrew/php/php55-v8js                 homebrew/php/php71-gmp
homebrew/php/php53-yaml                 homebrew/php/php55-varnish              homebrew/php/php71-gnupg
homebrew/php/php53-yar                  homebrew/php/php55-vld                  homebrew/php/php71-grpc
homebrew/php/php53-yaz                  homebrew/php/php55-wbxml                homebrew/php/php71-hprose
homebrew/php/php53-yp                   homebrew/php/php55-xcache               homebrew/php/php71-http
homebrew/php/php53-yrmcds               homebrew/php/php55-xdebug               homebrew/php/php71-ice
homebrew/php/php53-zenddebugger         homebrew/php/php55-xdiff                homebrew/php/php71-igbinary
homebrew/php/php53-zmq                  homebrew/php/php55-xhgui                homebrew/php/php71-imagick
homebrew/php/php53-zookeeper            homebrew/php/php55-xhprof               homebrew/php/php71-intl
homebrew/php/php54                      homebrew/php/php55-xmldiff              homebrew/php/php71-ioncubeloader
homebrew/php/php54-amqp                 homebrew/php/php55-xxtea                homebrew/php/php71-libsodium@1.0
homebrew/php/php54-apc                  homebrew/php/php55-yac                  homebrew/php/php71-lua
homebrew/php/php54-apcu                 homebrew/php/php55-yaf                  homebrew/php/php71-lz4
homebrew/php/php54-augmentedtypes       homebrew/php/php55-yaml                 homebrew/php/php71-lzf
homebrew/php/php54-binpack              homebrew/php/php55-yar                  homebrew/php/php71-mailparse
homebrew/php/php54-blitz                homebrew/php/php55-yaz                  homebrew/php/php71-maxminddb
homebrew/php/php54-boxwood              homebrew/php/php55-yp                   homebrew/php/php71-mcrypt
homebrew/php/php54-chdb                 homebrew/php/php55-yrmcds               homebrew/php/php71-mecab
homebrew/php/php54-couchbase            homebrew/php/php55-zmq                  homebrew/php/php71-memcached
homebrew/php/php54-crypto               homebrew/php/php55-zookeeper            homebrew/php/php71-meminfo
homebrew/php/php54-dbase                homebrew/php/php56                      homebrew/php/php71-molten
homebrew/php/php54-dbus                 homebrew/php/php56-amqp                 homebrew/php/php71-mongodb
homebrew/php/php54-dmtx                 homebrew/php/php56-apcu                 homebrew/php/php71-mosquitto
homebrew/php/php54-eio                  homebrew/php/php56-augmentedtypes       homebrew/php/php71-msgpack
homebrew/php/php54-ev                   homebrew/php/php56-binpack              homebrew/php/php71-mustache
homebrew/php/php54-event                homebrew/php/php56-blitz                homebrew/php/php71-oauth
homebrew/php/php54-fast_assert          homebrew/php/php56-boxwood              homebrew/php/php71-opcache
homebrew/php/php54-gearman              homebrew/php/php56-chdb                 homebrew/php/php71-pcntl
homebrew/php/php54-geoip                homebrew/php/php56-couchbase            homebrew/php/php71-pdo-dblib
homebrew/php/php54-geos                 homebrew/php/php56-crypto               homebrew/php/php71-pdo-pgsql
homebrew/php/php54-gmagick              homebrew/php/php56-dbase                homebrew/php/php71-phalcon
homebrew/php/php54-gmp                  homebrew/php/php56-dbus                 homebrew/php/php71-propro
homebrew/php/php54-gnupg                homebrew/php/php56-dmtx                 homebrew/php/php71-protobuf
homebrew/php/php54-graphdat             homebrew/php/php56-eio                  homebrew/php/php71-pspell
homebrew/php/php54-hprose               homebrew/php/php56-ev                   homebrew/php/php71-raphf
homebrew/php/php54-htscanner            homebrew/php/php56-event                homebrew/php/php71-rdkafka
homebrew/php/php54-http                 homebrew/php/php56-fast_assert          homebrew/php/php71-redis
homebrew/php/php54-httpparser           homebrew/php/php56-gearman              homebrew/php/php71-ref
homebrew/php/php54-igbinary             homebrew/php/php56-geoip                homebrew/php/php71-snmp
homebrew/php/php54-imagick              homebrew/php/php56-geos                 homebrew/php/php71-sodium
homebrew/php/php54-intl                 homebrew/php/php56-gmagick              homebrew/php/php71-solr
homebrew/php/php54-ioncubeloader        homebrew/php/php56-gmp                  homebrew/php/php71-ssh2
homebrew/php/php54-jsmin                homebrew/php/php56-gnupg                homebrew/php/php71-stats
homebrew/php/php54-kafka                homebrew/php/php56-graphdat             homebrew/php/php71-swoole
homebrew/php/php54-leveldb              homebrew/php/php56-grpc                 homebrew/php/php71-tidy
homebrew/php/php54-libevent             homebrew/php/php56-hprose               homebrew/php/php71-timecop
homebrew/php/php54-libsodium            homebrew/php/php56-htscanner            homebrew/php/php71-timezonedb
homebrew/php/php54-libvirt              homebrew/php/php56-http                 homebrew/php/php71-trader
homebrew/php/php54-lz4                  homebrew/php/php56-httpparser           homebrew/php/php71-translit
homebrew/php/php54-lzf                  homebrew/php/php56-ice                  homebrew/php/php71-uopz
homebrew/php/php54-magickwand           homebrew/php/php56-igbinary             homebrew/php/php71-uuid
homebrew/php/php54-mailparse            homebrew/php/php56-imagick              homebrew/php/php71-uv
homebrew/php/php54-maxminddb            homebrew/php/php56-intl                 homebrew/php/php71-v8js
homebrew/php/php54-mcrypt               homebrew/php/php56-ioncubeloader        homebrew/php/php71-xdebug
homebrew/php/php54-mecab                homebrew/php/php56-jsmin                homebrew/php/php71-xdiff
homebrew/php/php54-memcache             homebrew/php/php56-kafka                homebrew/php/php71-xmldiff
homebrew/php/php54-memcached            homebrew/php/php56-leveldb              homebrew/php/php71-xxtea
homebrew/php/php54-meminfo              homebrew/php/php56-libevent             homebrew/php/php71-yac
homebrew/php/php54-midgard2             homebrew/php/php56-libsodium            homebrew/php/php71-yaf
homebrew/php/php54-molten               homebrew/php/php56-libvirt              homebrew/php/php71-yaml
homebrew/php/php54-mongo                homebrew/php/php56-lz4                  homebrew/php/php71-zmq
homebrew/php/php54-mongodb              homebrew/php/php56-lzf                  homebrew/php/php72
homebrew/php/php54-mosquitto            homebrew/php/php56-magickwand           homebrew/php/php72-amqp
homebrew/php/php54-msgpack              homebrew/php/php56-mailparse            homebrew/php/php72-apcu
homebrew/php/php54-mustache             homebrew/php/php56-maxminddb            homebrew/php/php72-apcu-bc
homebrew/php/php54-mysqlnd_ms           homebrew/php/php56-mcrypt               homebrew/php/php72-ast
homebrew/php/php54-oauth                homebrew/php/php56-mecab                homebrew/php/php72-blitz
homebrew/php/php54-opcache              homebrew/php/php56-memcache             homebrew/php/php72-couchbase
homebrew/php/php54-parsekit             homebrew/php/php56-memcached            homebrew/php/php72-ev
homebrew/php/php54-pcntl                homebrew/php/php56-meminfo              homebrew/php/php72-event
homebrew/php/php54-pdflib               homebrew/php/php56-midgard2             homebrew/php/php72-gearman
homebrew/php/php54-pdo-dblib            homebrew/php/php56-molten               homebrew/php/php72-geoip
homebrew/php/php54-pdo-pgsql            homebrew/php/php56-mongo                homebrew/php/php72-geos
homebrew/php/php54-phalcon              homebrew/php/php56-mongodb              homebrew/php/php72-gmagick
homebrew/php/php54-pimple               homebrew/php/php56-mosquitto            homebrew/php/php72-gmp
homebrew/php/php54-pinba                homebrew/php/php56-msgpack              homebrew/php/php72-grpc
homebrew/php/php54-proctitle            homebrew/php/php56-mustache             homebrew/php/php72-hprose
homebrew/php/php54-propro               homebrew/php/php56-mysqlnd_ms           homebrew/php/php72-http
homebrew/php/php54-protobuf             homebrew/php/php56-oauth                homebrew/php/php72-igbinary
homebrew/php/php54-pspell               homebrew/php/php56-opcache              homebrew/php/php72-imagick
homebrew/php/php54-pthreads             homebrew/php/php56-parsekit             homebrew/php/php72-intl
homebrew/php/php54-qr                   homebrew/php/php56-pcntl                homebrew/php/php72-lua
homebrew/php/php54-raphf                homebrew/php/php56-pdflib               homebrew/php/php72-lz4
homebrew/php/php54-rdkafka              homebrew/php/php56-pdo-dblib            homebrew/php/php72-lzf
homebrew/php/php54-redis                homebrew/php/php56-pdo-pgsql            homebrew/php/php72-mailparse
homebrew/php/php54-redland              homebrew/php/php56-phalcon              homebrew/php/php72-maxminddb
homebrew/php/php54-riak                 homebrew/php/php56-pimple               homebrew/php/php72-mecab
homebrew/php/php54-runkit               homebrew/php/php56-pinba                homebrew/php/php72-memcached
homebrew/php/php54-scrypt               homebrew/php/php56-proctitle            homebrew/php/php72-meminfo
homebrew/php/php54-snappy               homebrew/php/php56-propro               homebrew/php/php72-molten
homebrew/php/php54-snmp                 homebrew/php/php56-protobuf             homebrew/php/php72-mongodb
homebrew/php/php54-sodium               homebrew/php/php56-pspell               homebrew/php/php72-mosquitto
homebrew/php/php54-solr                 homebrew/php/php56-pthreads             homebrew/php/php72-msgpack
homebrew/php/php54-sphinx               homebrew/php/php56-qr                   homebrew/php/php72-mustache
homebrew/php/php54-spl-types            homebrew/php/php56-raphf                homebrew/php/php72-oauth
homebrew/php/php54-ssh2                 homebrew/php/php56-rdkafka              homebrew/php/php72-opcache
homebrew/php/php54-stats                homebrew/php/php56-redis                homebrew/php/php72-pcntl
homebrew/php/php54-stemmer              homebrew/php/php56-redland              homebrew/php/php72-pdo-dblib
homebrew/php/php54-suhosin              homebrew/php/php56-riak                 homebrew/php/php72-pdo-pgsql
homebrew/php/php54-sundown              homebrew/php/php56-runkit               homebrew/php/php72-phalcon
homebrew/php/php54-svm                  homebrew/php/php56-scrypt               homebrew/php/php72-propro
homebrew/php/php54-swoole               homebrew/php/php56-snappy               homebrew/php/php72-pspell
homebrew/php/php54-symfony-debug        homebrew/php/php56-snmp                 homebrew/php/php72-raphf
homebrew/php/php54-thrift               homebrew/php/php56-sodium               homebrew/php/php72-rdkafka
homebrew/php/php54-tidy                 homebrew/php/php56-solr                 homebrew/php/php72-redis
homebrew/php/php54-timecop              homebrew/php/php56-sphinx               homebrew/php/php72-ref
homebrew/php/php54-timezonedb           homebrew/php/php56-spl-types            homebrew/php/php72-snmp
homebrew/php/php54-trace                homebrew/php/php56-ssh2                 homebrew/php/php72-ssh2
homebrew/php/php54-trader               homebrew/php/php56-stats                homebrew/php/php72-stats
homebrew/php/php54-twig                 homebrew/php/php56-stemmer              homebrew/php/php72-swoole
homebrew/php/php54-uopz                 homebrew/php/php56-suhosin              homebrew/php/php72-tidy
homebrew/php/php54-uploadprogress       homebrew/php/php56-sundown              homebrew/php/php72-timecop
homebrew/php/php54-uuid                 homebrew/php/php56-svm                  homebrew/php/php72-timezonedb
homebrew/php/php54-v8js                 homebrew/php/php56-swoole               homebrew/php/php72-trader
homebrew/php/php54-varnish              homebrew/php/php56-symfony-debug        homebrew/php/php72-uopz
homebrew/php/php54-vld                  homebrew/php/php56-thrift               homebrew/php/php72-uv
homebrew/php/php54-wbxml                homebrew/php/php56-tidy                 homebrew/php/php72-v8js
homebrew/php/php54-xcache               homebrew/php/php56-timecop              homebrew/php/php72-xdebug
homebrew/php/php54-xdebug               homebrew/php/php56-timezonedb           homebrew/php/php72-xxtea
homebrew/php/php54-xdiff                homebrew/php/php56-trace                homebrew/php/php72-yac
homebrew/php/php54-xhgui                homebrew/php/php56-trader               homebrew/php/php72-yaml
homebrew/php/php54-xhprof               homebrew/php/php56-translit             latexila
homebrew/php/php54-xmldiff              homebrew/php/php56-twig                 mcabber
homebrew/php/php54-xxtea                homebrew/php/php56-uopz                 yle-dl
homebrew/php/php54-yac                  homebrew/php/php56-uploadprogress
```

Should I just give the formulae you listed revision bumps, or do I have to go through _all_ of these?

**Comment by ilovezfs** [comment]
Just the ones I listed. See https://github.com/Homebrew/homebrew-core/pull/20617

**Comment by RandomDSdevel** [comment]
@ilovezfs:  'Kay, thanks.  Just pushed all of that.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  OK, I think the commits I pushed solved all of the build issues, but the CI logs are still showing failing tests.  Perhaps fiddling with the tests' linkage might help?  I was seeing some header issues, too.

**Comment by ilovezfs** [comment]
```
iMac-TMP:homebrew-core joe$ git diff -- Formula/gspell.rb 
diff --git a/Formula/gspell.rb b/Formula/gspell.rb
index b5dea3067f..c69de08331 100644
--- a/Formula/gspell.rb
+++ b/Formula/gspell.rb
@@ -59,7 +59,7 @@ class Gspell < Formula
     flags = %W[
       -I#{atk.opt_include}/atk-1.0
       -I#{cairo.opt_include}/cairo
-      -I#{enchant.opt_include}/enchant
+      -I#{enchant.opt_include}/enchant-2
       -I#{fontconfig.opt_include}
       -I#{freetype.opt_include}/freetype2
       -I#{gdk_pixbuf.opt_include}/gdk-pixbuf-2.0
iMac-TMP:homebrew-core joe$ git diff -- Formula/gtkspell3.rb 
diff --git a/Formula/gtkspell3.rb b/Formula/gtkspell3.rb
index 0087451e7e..b9e33ec5c9 100644
--- a/Formula/gtkspell3.rb
+++ b/Formula/gtkspell3.rb
@@ -46,7 +46,7 @@ class Gtkspell3 < Formula
     flags = %W[
       -I#{atk.opt_include}/atk-1.0
       -I#{cairo.opt_include}/cairo
-      -I#{enchant.opt_include}/enchant
+      -I#{enchant.opt_include}/enchant-2
       -I#{fontconfig.opt_include}
       -I#{freetype.opt_include}/freetype2
       -I#{gdk_pixbuf.opt_include}/gdk-pixbuf-2.0
@@ -73,7 +73,7 @@ class Gtkspell3 < Formula
       -latk-1.0
       -lcairo
       -lcairo-gobject
-      -lenchant
+      -lenchant-2
       -lgdk-3
       -lgdk_pixbuf-2.0
       -lgio-2.0
iMac-TMP:homebrew-core joe$ 
```

**Comment by RandomDSdevel** [comment]
@ilovezfs:  D'oh; _that_ should have been obvious.  I'll have that pushed in a little bit, then.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  I just applied the linkage fixes you pointed out obviously had to be made to this PR's staging branch after rebasing it and have just now pushed the results of doing that here to GitHub.  Build troubles, begone; I banish thee!  (Now, let's see if CI agrees with me…)

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Review by ilovezfs — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @RandomDSdevel for the pull request!

**Comment by fxcoudert** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/3bc30a3f7d92e912186eae3082bf4e7550fdf72d

**Pull request closed without merging**
