### PR TITLE
kerl 0.9 (new formula, import from head-only)

### PR DESCRIPTION
**Pull request by bfontaine**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

---

https://github.com/Homebrew/homebrew-head-only/pull/206

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like there's already a new version upstream here. The expression about buses comes to mind :smile:.

**Comment by sanmiguel** [comment]
Forgive me if I'm missing something obvious, but it looks to me like Homebrew/homebrew-head-only#206 needs to be merged first?

**Comment by DomT4** [comment]
The `audit` complains but we tend to merge the PR in core first to add the formula and then just afterwards merge the one in `boneyard`. The audit isn't intended so much as "Don't merge this" but "Please make sure you've started migrating it first".

**Comment by sanmiguel** [comment]
OK - thanks for the explanation @DomT4 !

So, for clarity - is there anything more you need from us for this migration to go ahead?

**Comment by bfontaine** [comment]
@DomT4 You mean `head-only` instead of `boneyard` :wink:

**Comment by bfontaine** [comment]
@sanmiguel Nope; I’ll merge this tonight if Dom doesn’t beat me.

**Comment by DomT4** [comment]
@bfontaine Oops, I did. Thanks for spotting that :smile:. Happy to leave the PR to you for merge, don't want to step on your work :).

**Pull request closed without merging**
