### PR TITLE
WIP: arm-none-eabi-gcc 8-2018-q4-major (new formula)

### PR DESCRIPTION
**Pull request by kousu**
So far this imports https://github.com/ARMmbed/homebrew-formulae/ verbatim.
I realize formulas are supposed to build from source (it's casks from binaries),
but this is just to get me started. I intend to tweak it to make it build from source.

Addresses https://github.com/Homebrew/homebrew-cask/pull/56802

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by kousu** [comment]
I'm trying to rewrite this to install from sources, but I'm currently stuck because one of the dependencies. The build of https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-src.tar.bz2 wants to download a bunch of its own dependencies, and one of them has evaporated:

```
$ wget http://www.mr511.de/software/libelf-0.8.13.tar.gz ; echo $?
--2019-05-15 01:44:47--  http://www.mr511.de/software/libelf-0.8.13.tar.gz
Résolution de www.mr511.de (www.mr511.de)… 80.67.16.8
Connexion à www.mr511.de (www.mr511.de)|80.67.16.8|:80… connecté.
requête HTTP transmise, en attente de la réponse… 302 Moved Temporarily
Emplacement : http://leere.seite [suivant]
--2019-05-15 01:44:47--  http://leere.seite/
Résolution de leere.seite (leere.seite)… échec : nodename nor servname provided, or not known.
wget : impossible de résoudre l’adresse de l’hôte « leere.seite »
```

Incidentally, the same url is used in brew: https://github.com/Homebrew/homebrew-core/issues/39870

I'm going to see if I can convince it to link against homebrew's pre-existing copy of libelf (and all the other deps).

**Comment by kousu** [comment]
I am pretty sure I can use the bundled libelf. I extracted the source from the official release, ignoring their build scripts:

```
wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-src.tar.bz2
tar xf gcc-arm-none-eabi*-src.tar.bz2
cd gcc-arm-none-eabi-8-2018-q4-major
cd src/
tar xf gcc.tar.bz2
cd gcc
```

then, porting https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/arm-none-eabi-gcc, I tried,

```
mkdir build-gcc
cd build-gcc
export CFLAGS_FOR_TARGET='-g -Os -ffunction-sections -fdata-sections'
export CXXFLAGS_FOR_TARGET='-g -Os -ffunction-sections -fdata-sections'
../configure \
    --target=arm-none-eabi \
    --prefix=/usr \
    --with-sysroot=/usr/arm-none-eabi \
    --with-native-system-header-dir=/include \
    --libexecdir=/usr/lib \
    --enable-languages=c,c++ \
    --enable-plugins \
    --disable-decimal-float \
    --disable-libffi \
    --disable-libgomp \
    --disable-libmudflap \
    --disable-libquadmath \
    --disable-libssp \
    --disable-libstdcxx-pch \
    --disable-nls \
    --disable-shared \
    --disable-threads \
    --disable-tls \
    --with-gnu-as \
    --with-gnu-ld \
    --with-system-zlib \
    --with-newlib \
    --with-headers=/usr/arm-none-eabi/include \
    --with-python-dir=share/gcc-arm-none-eabi \
    --with-gmp \
    --with-mpfr \
    --with-mpc \
    --with-isl \
    --with-libelf \
    --enable-gnu-indirect-function \
    --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' \
    --with-pkgversion='brew' \
    --with-bugurl='https://github.com/Homebrew/homebrew-core/issues/' \
    --with-multilib-list=rmprofile
make INHIBIT_LIBC_CFLAGS='-DUSE_TM_CLONE_REGISTRY=0'
```

and it started building. `configure` complained a bit

**Comment by fxcoudert** [comment]
You can look at `i386-elf-gcc` or `mingw-w64` to see how toolchains can be built.

**Comment by kousu** [comment]
Dope! Thank you. I will do just that.

**Comment by Ecco** [comment]
Out of curiosity: would a "simple" formula that just pulls in the official binary release be accepted?

I know packages are usually built from source, but in this specific case using the original build from the CPU founder would make a lot of sense.

**Comment by SMillerDev** [comment]
> Out of curiosity: would a "simple" formula that just pulls in the official binary release be accepted?

It wouldn't https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by Ecco** [comment]
Indeed, but https://docs.brew.sh/Acceptable-Formulae#sometimes-there-are-exceptions 😄 

Jokes aside, it might be a case where an exception makes sense.

When doing embedded development you rely on your compiler behaving in a very specific, reproductible way. Having the same compiler as everyone else is a major feature, and toolchains are complicated beasts. I know that I'd personnaly be reluctant to using a custom-built toolchain instead of the founder-provided one.

**Comment by fxcoudert** [comment]
We already have toolchains that build from source, even when it’s complicated (wine, mingw). The right solution, if you wish to ship upstream binaries, is to make the formula a cask, not a Homebrew core formula.

**Comment by MikeMcQuaid** [comment]
> Jokes aside, it might be a case where an exception makes sense.

I disagree. `brew cask` is simpler a better delivery mechanism for binaries. If you disagree, you can do so in a tap (and if you don't need binaries built there's no real reason to have them in homebrew-core).

It also seems a bit weird to call this `gcc` when it's a patched version from another upstream (CC @fxcoudert for thoughts on that).

**Comment by Ecco** [comment]
> I disagree. `brew cask` is simpler a better delivery mechanism for binaries.

Well, thing is, it used to be a cask, but it was [dropped](https://github.com/Homebrew/homebrew-cask/pull/56802) because "it should be a formula, not a cask, as it is a CLI-only open-source tool." 😄 

> If you disagree, you can do so in a tap (and if you don't need binaries built there's no real reason to have them in homebrew-core).

Indeed. Or just not use homebrew altogether, which is what I'm doing for this package 😄 

I still think I have a point: when doing embedded development you end up caring *a lot* about weird compiler features (e.g. volatiles, linker scripts, remote debugging). Those features aren't well tested because there aren't so many people doing embedded dev, so as a safeguard it's a great idea to try and use the same binary as everyone else.

I do understand the general policy of Homebrew though, and building from source might actually yield the exact same toolchain as the one distributed by ARM.

**Comment by fxcoudert** [comment]
> it's a great idea to try and use the same binary as everyone else

Which Homebrew allows, due to its extensible nature. But that's not a good fit for Homebrew core.

**Comment by SMillerDev** [comment]
Maybe @kousu doesn't prefer a binary though. In that case we can reopen this one.

**Comment by kousu** [comment]
I don't prefer a binary. I want to get to this, I'm just busy with other obligations. I'll reopen it when I have something more substatiantial to show. If anyone would like to collaborate on getting this done you can message me!

I know what @ecco says about embedded development, but I wish it didn't have to be that way. My philosophy is that if I'm depending on very compiler-specific settings then my code is fragile and I should fix my code, not my compiler. For my project at least, this has panned out: I am able to do my same build on ArchLinux and on macOS, and even build parts of it using OS X's clang (though not yet all of it). Arch is [using a source-built toolchain](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/arm-none-eabi-gcc) -- in fact they aren't using ARM's fork of gcc v8, they are using mainline gcc v9 compiled with `--target=arm-none-eabi`. That works fine there. I think it will work fine here too.

**Comment by kousu** [comment]
For reference, in the meantime I'm using ARM corp's (semi?) official brew tap https://github.com/ArmMbed/homebrew-formulae

```
brew tap ArmMbed/homebrew-formulae
brew install arm-none-eabi-gcc
```

**Comment by MikeMcQuaid** [comment]
> in the meantime I'm using ARM corp's (semi?) official brew tap

Collaborating on that tap may be a better fit than this being in homebrew-core.

**Pull request closed without merging**
