### PR TITLE
daq: use mirrors

### PR DESCRIPTION
**Pull request by queengooborg**
New SHA256 was pulled directly from the URL.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.`

**Comment by vinyldarkscratch** [comment]
Submitted a bug report -- closing PR for now!

**Comment by vinyldarkscratch** [comment]
Upstream is confirming the hashsum this PR changes it to is the correct one.  They don't know where the hashsum that's in the Homebrew formula came from.  Possibly a derp with an auto-update?

**Comment by ilovezfs** [comment]
OK. We'll need to bump the revision, too.

**Review by ilovezfs — DISMISSED** [review]

**Comment by vinyldarkscratch** [comment]
Failing on the test bot for obvious reasons -- local install succeeds though!

**Comment by ilovezfs** [comment]
@vinyldarkscratch though their explanation doesn't pass the smell test as we have bottles for this version going all the way back to OS X 10.8 and through macOS 10.13, which means this checksum was the same from 2012 - 2017 and then suddenly changed.

**Comment by ilovezfs** [comment]
And indeed our checksum matches what is on fossies: https://fossies.org/linux/misc/daq-2.0.6.tar.gz

**Comment by ilovezfs** [comment]
Yeah, they need to do better than that in their explanation.

**Comment by ilovezfs** [comment]
ditto macports https://distfiles.macports.org/daq/daq-2.0.6.tar.gz

same as our original checksum

**Comment by vinyldarkscratch** [comment]
Okay, here's the strange thing: the tarballs differ from each other, but their contents do not.  Either I'm running the command wrong*, or there was a change in it's compression.

* `diff -rq /Users/vinyldarkscratch/Desktop/daq-2.0.6 /Users/vinyldarkscratch/Desktop/daq-2.0.6-fossies`

**Comment by ilovezfs** [comment]
I guess we can do
```
url "https://www.mirrorservice.org/sites/distfiles.macports.org/daq/daq-2.0.6.tar.gz"
mirror "https://fossies.org/linux/misc/daq-2.0.6.tar.gz"
```

for now.

**Comment by ilovezfs** [comment]
>Either I'm running the command wrong*, or there was a change in it's compression.

Could be, yeah. But release artifacts morphing for any reason is a problem especially if they think it's not happening.

**Comment by ilovezfs** [comment]
Thanks @vinyldarkscratch!

**Pull request merged**
