### PR TITLE
libusb 1.0.25

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by cpunion** [comment]
@miccal @chenrui333 `libusb@1.0.25` broke `openocd`

**Comment by jj1bdx** [comment]
Homebrew's libusb-1.0.25 quite often (not always but mostly) causes segfault at libusb_free_transfer() for Airspy HF+ Discovery with libairspyhf. Found both on x86_64 and arm64 (M1).

**Comment by mcuee** [comment]
@cpunion That is an openocd bug which has been fixed in openocd git head.
Ref: https://github.com/openocd-org/openocd/commit/cff0e417da58adef1ceef9a63a99412c2cc87ff3

**Comment by mcuee** [comment]
Ref: https://github.com/libusb/libusb/issues/1059
The issues are application bugs and the above libusb issue has been closed.

**Pull request closed without merging**
