### PR TITLE
fix xmake-2.2.6 sha256

### PR DESCRIPTION
**Pull request by waruqi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why has the hash changed? Has this been reported upstream already?

**Comment by waruqi** [comment]
I fixed a more serious bug on 2.2.6, only one commit, so I recreated the 2.2.6 tag and didn't publish a new version.

**Comment by waruqi** [comment]
@SMillerDev How can I modify the hash of version 2.2.6? It seems that the test failed, but I don't know why it failed. Must I submit a new version to pass?

**Comment by SMillerDev** [comment]
Generally retagging software is considered bad practice since it means 2 states of the software are now known under the same identifier. The test is failing on an audit because of this. If you have a link to somewhere upstream has documented that the changed hash is intentional we could merge it despite the failure

**Comment by waruqi** [comment]
@SMillerDev I agree that this is bad practice. Usually I won't do this either.

However, since the time to modify the tag is very short, there is no one to download and update. And I have not announced the new version yet.

so I feel that there is no need to publish a new version. I hope you can help merge this pr. Thanks.

**Comment by fxcoudert** [comment]
@waruqi please next time release a 2.2.7 version instead of replacing existing files. This creates confusion in users, and can be a sign of security issues.

**Comment by waruqi** [comment]
@fxcoudert Ok, Thanks!

**Pull request closed without merging**
