### PR TITLE
meilisearch 1.3.2

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR updates the latest version of meilisearch to v1.3.2.

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey 👋 Can we have more info on why the installation failed?

**Comment by SMillerDev** [comment]
You can check the build output, here is a relevant snippet:
```
error: failed to run custom build command for `lindera-unidic v0.27.0`
  
  Caused by:
    process didn't exit successfully: `/private/tmp/meilisearch-20230824-5854-1s02r9j/meilisearch-1.3.2/target/release/build/lindera-unidic-24e64b4bca6d64cf/build-script-build` (exit status: 1)
    --- stdout
    cargo:rerun-if-changed=build.rs
    cargo:rerun-if-changed=Cargo.toml
  
    --- stderr
    Error: Status(500, Response[status: 500, status_text: Internal Server Error, url: https://doc-08-24-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/up940q62mp4hhqfs6jps8c761q6mg32b/1692870225000/00509699103184555041/*/1LsYNZqw_ep1VJf3p49NZd9UTYaRq-V4p?e=download&uuid=63b6fd51-ef13-4605-b2e3-4[770](https://github.com/Homebrew/homebrew-core/actions/runs/5961852071/job/16172097424?pr=140345#step:3:771)9ebde10d])
  warning: build failed, waiting for other jobs to finish...
  error: failed to compile `meilisearch v1.3.2 (/private/tmp/meilisearch-20230824-5854-1s02r9j/meilisearch-1.3.2/meilisearch)`, intermediate artifacts can be found at `/private/tmp/meilisearch-20230824-5854-1s02r9j/meilisearch-1.3.2/target`
```

**Comment by Kerollmops** [comment]
Thank you @SMillerDev, can we rerun the build as it looks like a spurious Google API error?

**Review by ZhongRuoyu — APPROVED** [review]
Thanks, @Kerollmops.

**Pull request merged**
