### PR TITLE
loki 2.3.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
```
==> brew test --retry --verbose logcli
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/local/etc/loki-local-config.yaml`
```

can't reproduce this locally

**Comment by carlocab** [comment]
Rebasing this should probably fix the `logcli` failure.

**Comment by SMillerDev** [comment]
@branchvincent it should be using configuration from the test directory that it's running in. It might not have access to configuration outside of it.

**Comment by cho-m** [comment]
`logcli` is failing on CI when trying to copy `loki` YAML file.
```rb
    cp etc/"loki-local-config.yaml", testpath
```

Happened previously, https://github.com/Homebrew/homebrew-core/pull/67704#issuecomment-762368850.

May be related to order of updating `logcli` vs. `loki`, as previously this was seen when both were updated together. The solution was to update `loki` first, and then rebase `logcli` PR.

Since we merged `logcli` first #82894, we may want to look into rewriting test to find a better way to deal with. Perhaps make YAML into a test resource? Not sure what else is possible.

**Comment by carlocab** [comment]
Let's try rebasing...

**Comment by cho-m** [comment]
Still failed. It could be some issue with how Homebrew test is handled in relation to test-only dependencies.

The workaround for now would be to add YAML file as either a test resource or save a local copy.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
