### PR TITLE
vis: fix lpeg detection

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/martanne/vis/issues/633#issuecomment-359213730.

### CODE REVIEW

**Comment by ilovezfs** [comment]
:face_with_thermometer:

**Comment by DomT4** [comment]
Just colour me grateful the fix was simple & obvious.

**Comment by ilovezfs** [comment]
:1st_place_medal:

**Comment by DomT4** [comment]
Thanks Joe.

**Pull request closed without merging**
