### PR TITLE
imageoptim-cli: build on Apple Silicon

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
Could we try having this build the native binaries for both ARM and Intel?  It seems like it's a just a matter of changing the target names.  Even if it's not absolutely necessary, I feel like any time we can avoid install pre-built binaries we should, even if they don't cause audit failure.

**Comment by cho-m** [comment]
> Could we try having this build the native binaries for both ARM and Intel? It seems like it's a just a matter of changing the target names. Even if it's not absolutely necessary, I feel like any time we can avoid install pre-built binaries we should, even if they don't cause audit failure.

In this case, the pre-built is an intermediary tool (built using Node.js code base) used to compile the native binaries. The native binaries are built from raw TypeScript --> Javascript files during our installation block for both Intel and ARM.

There is a bit of maintenance overhead since we would need to keep track of version used to compile (right now using Node 12 because upstream set that and I had some issues with Node 17)

I am actually not sure if our `node` dependency is being used at runtime since ImageOptim-CLI is a self-contained binary. I think `node` may be used in build to get `npm` so that the dependencies can be pulled from npmjs

**Comment by cho-m** [comment]
Another option would be to avoid compiling and just create a wrapper to run 
```sh
exec /path/to/node /path/to/imageoptim.js $@
```
though, not sure if it will work correctly and there will be some performance impact.

Right now, the upstream is using Node.js 12.18.2, which is probably due to that being latest v12 that `nexe` has pre-built for. This does mean it was built with Node.js containing some CVEs and the runtime is embedded within the binary.

**Comment by cho-m** [comment]
Just noting that, in case of current approach, I am waiting for `nexe` V4 stable release.

On other hand, it is still up to consideration whether we should avoiding bundling the NodeJS v12 runtime. It may be worth checking with upstream on adding an option to allow `node` runtime dependency rather than current behavior of using `nexe` to build a self-contained binary.

**Pull request closed without merging**
