### PR TITLE
gauge 0.6.0

### PR DESCRIPTION
**Pull request by kaustavdm**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

@kashishm Tagging you so that you can keep track of this.

### CODE REVIEW

**Comment by DomT4** [comment]
I'm a bit confused where the https://github.com/Homebrew/homebrew-core/pull/3156/commits/88891ee0b23a597298691a8e4c1ef49cb5eec439 commit comes in. We moved to the `godep` system in https://github.com/Homebrew/homebrew-core/commit/c2a80007ac6998c974a11eab2fc7e8e325a385b2, so if your branch is up-to-date it shouldn't need redoing 😕.

**Comment by kaustavdm** [comment]
@DomT4 We moved to the new homebrew system with this release of gauge. Looks like we need to do some housekeeping on our end. We'll let you know once we have things updated.

**Comment by kaustavdm** [comment]
@DomT4 Does this look good now? Migrating from Homebrew Legacy had messed up the first commit. Are there any changes needed? If yes, please suggest.

**Comment by DomT4** [comment]
Looks great, Thanks.

Merged in https://github.com/Homebrew/homebrew-core/commit/91e2bd4d1bcfd42b8084ce1d9ac50397961b4fe5. Thank you for your contribution to Homebrew @kaustavdm; we appreciate it! :smiley_cat:

**Comment by kaustavdm** [comment]
@DomT4 Thanks!

**Pull request closed without merging**
