### PR TITLE
Node 9.2.0 & npm 5.6.0

### PR DESCRIPTION
**Pull request by ruchernchong**
Signed-off-by: Ru Chern Chong <ruchern@sproud.biz>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by JLHwung** [comment]
I'm afraid we should not merge this PR yet since npm 5.6.0 is *not* the upstream node.js bundled version.

Yet it is more of an egg/chicken issues. If we bump to node.js 9.x, another node@8 formula should be drafted.

**Comment by Alhadis** [comment]
This isn't the first time I've wished NPM was Homebrew...

**Comment by ruchern** [comment]
I think this is still early as I cannot seem to be able to access the bottles on the server.

**Comment by ilovezfs** [comment]
`brew install --devel node` will now give you node 9.2.0 + npm 5.6.0

**Comment by ruchern** [comment]
@ilovezfs 

The command did not work.

Below is the error

```bash
ruchern:~/ $ brew install --devel node
Error: node 8.9.1 is already installed
To upgrade to 9.2.0, run `brew upgrade node`

ruchern:~/ $ brew upgrade node
Error: node 8.9.1 already installed
```

**Comment by egoroof** [comment]
`brew upgrade node --devel`

**Comment by ruchern** [comment]
@egoroof Right thanks. I did not thought of that.

**Pull request closed without merging**
