### PR TITLE
Add higan, a multi-system emulator for games

### PR DESCRIPTION
**Pull request by ararslan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

This creates .app bundles, so I put them in libexec to expose them to `brew linkapps`, which I took from the Qt formula.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does it just create an app?

**Comment by ararslan** [comment]
It creates two apps: higan.app and icarus.app. The latter loads game ROMs and the former is the actual emulator.

**Comment by bayandin** [comment]
Hi @ararslan,

We generally don't want formulae that build `.app`s: https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app
If upstream provides a `.dmg` files then it might be suitable to just use that and create the formula in [homebrew-cask](https://github.com/homebrew/homebrew-cask), rather than building a `.app`.

Thanks!

**Comment by ararslan** [comment]
Upstream doesn't provide anything, which is why this just calls `make` and uses the result. I figured it was nice to use the .app bundles since they're created, but I could instead just use the binaries that they wrap.

**Pull request closed without merging**
