### PR TITLE
htmlcleaner 2.18

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@apjanke any idea what's up with CI here?

**Comment by apjanke** [comment]
Not a clue; sorry.

**Comment by MikeMcQuaid** [comment]
@ilovezfs It's an edge-case we've mostly avoided where the command output can cause Jenkins to fail to parse the output. Looks good here https://bot.brew.sh/job/Homebrew%20Core/14842/version=sierra/console so I say :shipit:

**Comment by ilovezfs** [comment]
The prior version does not fail, so I'm :-1: to shipping it until that's sorted.

**Comment by MikeMcQuaid** [comment]
This is 100% our bug. The relevant code: https://github.com/Homebrew/homebrew-test-bot/blob/46178ff5bb968e01c2153fda7e79a5129f0740a9/cmd/brew-test-bot.rb#L1223-L1237

**Comment by ilovezfs** [comment]
:green_apple: now.

Based on the error message
>"The element type "system-out" must be terminated by the matching end-tag "</system-out>". Nested exception: The element type "system-out" must be terminated by the matching end-tag "</system-out>".

I think the relevant code is actually https://github.com/Homebrew/homebrew-test-bot/blob/46178ff5bb968e01c2153fda7e79a5129f0740a9/cmd/brew-test-bot.rb#L1196

The part of the output causing trouble is
```
Running org.htmlcleaner.HtmlCleanerTest
<?xml version="1.0" encoding="UTF-8"?>
<html>
<head><script>/*<![CDATA[*/
a < b
/*]]>*/</script></head>
<body></body></html>
<?xml version="1.0" encoding="UTF-8"?>
<html>
	<head></head>
	<body>
		<pre class="executable">&lt;?xml version=&quot;1.0&quot;?&gt;<root></root></pre>
	</body>
</html>
Tests run: 42, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 0.089 sec - in org.htmlcleaner.HtmlCleanerTest
```

**Pull request closed without merging**
