### PR TITLE
evernote-backup: vendor Python resources

### PR DESCRIPTION
**Pull request by timsutton**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by timsutton** [comment]
Note: evernote-backup at latest release uses an old `oauth2` pypi dep, which depended on distutils. Probably need to include [this](https://github.com/vzhd1701/evernote-backup/commit/32a094cda70492fda2ba6796acbc016c80424fd0) and swap out the resource.

**Comment by p-linnane** [comment]
Opened an upstream issue asking if they can cut a release with that change: https://github.com/vzhd1701/evernote-backup/issues/77

**Comment by timsutton** [comment]
@p-linnane For this one, I just added my first patch to formula-patches: https://github.com/Homebrew/formula-patches/commit/ae02b930cd5abca86e964daa6327e01507e53c2f. Hope I did this right!

I couldn't take the upstream's commit as-is because of other files (poetry.lock, test files) modified in the same commit.

**Review by p-linnane — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
