### PR TITLE
lighttpd 1.4.49

### PR DESCRIPTION
**Pull request by metowolf**
Created with `brew bump-formula-pr`.
https://www.lighttpd.net/2018/3/11/1.4.49/

### CODE REVIEW

**Comment by ilovezfs** [comment]
@metowolf any news here?

**Comment by metowolf** [comment]
Duplicate of #25135

**Comment by ilovezfs** [comment]
It needed to depend on the openldap formula for a newer version of libldap than macOS provides.

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/25995

**Pull request closed without merging**
