### PR TITLE
ipopt: update MUMPS flags

### PR DESCRIPTION
**Pull request by nrontsis**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

## The problem
Currently, `Ipopt` is installed without any functional linear solver as `MUMPS` fails to be detected by `Ipopt`. This makes `Ipopt` non-functional unless the user has already installed some other supported linear solver.

## Suggested solution
Replace outdated flags:
```
--with-mumps-incdir/--with-mumps-lib
```
with
```
--with-mumps-cflags/--with-mumps-lflags
```
 for `Ipopt`'s `configure`. See `Ipopt`'s documentation [here](https://coin-or.github.io/Ipopt/INSTALL.html#DOWNLOAD_MUMPS) for more details.

## How about testing?
The current test of this recipe does not capture the issue, as it only initialises `Ipopt` but it does not instruct `Ipopt` to optimise a model. I see two options:
- Run `make test` instead of `make` in line 65. This will invoke `Ipopt's` internal tests that will capture the issue.
- Include a considerably lengthier test that defines and optimises a model, e.g. like [this one](https://github.com/coin-or/Ipopt/tree/master/examples/hs071_cpp).

### CODE REVIEW

**Comment by SMillerDev** [comment]
> Include a considerably lengthier test that defines and optimises a model, e.g. like this one.

This is the way to go, test length doesn't matter as much as catching bugs does.

**Comment by SMillerDev** [comment]
What might actually be easier is downloading the example as a resource and trying to run that as a test.

**Comment by nrontsis** [comment]
Thanks, do you have an example I can follow?

**Comment by nrontsis** [comment]
This is now ready with a test that detects the issue that this PR fixes.

@SMillerDev I am happy to implement your suggestion of pulling the example as a resource if you point me to another recipe that does something similar.

**Comment by SMillerDev** [comment]
Slightly simpler example, but here is one: https://github.com/Homebrew/homebrew-core/blob/master/Formula/zpaq.rb

**Comment by nrontsis** [comment]
Done

**Review by SMillerDev — APPROVED** [review]
Thanks @nrontsis  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
