### PR TITLE
llama.cpp b3003 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #172186
Closes #169894

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by Vaibhavs10** [comment]
This looks way more robust than my attempt! Thanks, @carlocab & @SMillerDev - I've learnt a great deal from you two in the past couple of days! 🤗

**Comment by carlocab** [comment]
macOS 12-x86_64 failure looks like a flake. I'll just dispatch a bottle separately.

**Comment by Vaibhavs10** [comment]
Quick question, @carlocab / @SMillerDev: Should we merge PRs for the latest releases, too (via auto bump)? I see that there are new releases in llama.cpp, but I don't see any open PRs from BrewTestBot.

**Comment by carlocab** [comment]
Should hopefully be fixed by #172946.

**Pull request merged**
