### PR TITLE
civl: deprecate

### PR DESCRIPTION
**Pull request by chenrui333**
civil: deprecate

---

relates to https://github.com/Homebrew/homebrew-core/pull/194557

---

stats:

image

### CODE REVIEW

**Comment by Bo98** [comment]
Maybe worth seeing if it's just a temporary or permanent thing (maybe ask their mailing list). The webapp is still working: http://civl.cis.udel.edu/app/

**Comment by chenrui333** [comment]
Works for me, move to draft mode

**Comment by chenrui333** [comment]
Also raised an issue on this, https://github.com/civl-verifier/civl-dev/issues/2

**Comment by calvinit** [comment]
> Maybe worth waiting a few days to see if it's just a temporary or permanent thing (maybe ask their mailing list). The webapp is still working: http://civl.cis.udel.edu/app/

Hey, they have returned to normal now! 😄

**Comment by chenrui333** [comment]
looks like the artifact is there again now

image

**Pull request closed without merging**
