### PR TITLE
xctool 0.3.5

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Following request for a new release that includes Xcode 10 fixes: https://github.com/facebook/xctool/issues/756
Thanks @ExtremeMan !

**Comment by ExtremeMan** [comment]
thanks, `brew bump-formula-pr` failed for me. But you submitted the request quicker than I have figured our what is wrong with my setup :)

**Comment by fxcoudert** [comment]
@ExtremeMan fails to build on High Sierra and Mojave (Xcode 10) with:

```
CompileC /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.o /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query/otest-query-ios/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: otest-query-appletv)
    cd /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query
    export LANG=en_US.US-ASCII
    clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -Wno-trigraphs -fpascal-strings -Os -Werror -Werror=incompatible-pointer-types -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DOBJC_OLD_DISPATCH_PROTOTYPES=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator12.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mtvos-simulator-version-min=9.0 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-generated-files.hmap -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-own-target-headers.hmap -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-all-target-headers.hmap -iquote /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-project-headers.hmap -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Products/Release/include -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/DerivedSources/x86_64 -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/DerivedSources -F/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Products/Release -F/Applications/Xcode.app/Contents/Developer/Library/Frameworks -include /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query/otest-query-ios/otest-query-ios-Prefix.pch -MMD -MT dependencies -MF /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.d --serialize-diagnostics /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.dia -c /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query/otest-query-ios/main.m -o /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.o
clang: error
: using sysroot for 'MacOSX' but targeting 'AppleTV' [-Werror,-Wincompatible-sysroot]

WriteAuxiliaryFile /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/otest-query-appletv.LinkFileList (in target: otest-query-appletv)
    cd /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query
    write-file /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/otest-query-appletv.LinkFileList

** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.o /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query/otest-query-ios/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by ExtremeMan** [comment]
Hm, this is weird. It works on all my machines and all test machines.

**Comment by ExtremeMan** [comment]
from logs:

```
CompileC /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.o /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query/otest-query-ios/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: otest-query-appletv)
19:42:08     cd /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query
19:42:08     export LANG=en_US.US-ASCII
19:42:08     clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -Wno-trigraphs -fpascal-strings -Os -Werror -Werror=incompatible-pointer-types -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DOBJC_OLD_DISPATCH_PROTOTYPES=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator12.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mtvos-simulator-version-min=9.0 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-generated-files.hmap -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-own-target-headers.hmap -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-all-target-headers.hmap -iquote /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/otest-query-appletv-project-headers.hmap -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Products/Release/include -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/DerivedSources/x86_64 -I/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/DerivedSources -F/tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Products/Release -F/Applications/Xcode.app/Contents/Developer/Library/Frameworks -include /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query/otest-query-ios/otest-query-ios-Prefix.pch -MMD -MT dependencies -MF /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.d --serialize-diagnostics /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.dia -c /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/otest-query/otest-query-ios/main.m -o /tmp/xctool-20180928-43673-z2yx4a/xctool-0.3.5/build/10A255/Intermediates/otest-query.build/Release-appletvsimulator/otest-query-appletv.build/Objects-normal/x86_64/main.o
```

The error says - ```using sysroot for 'MacOSX' but targeting 'AppleTV'```

if you check sysroot flag it is correct and points to appletv:

```-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator12.0.sdk```

**Comment by fxcoudert** [comment]
That's because Homebrew's `superenv` system adds flags behind the scenes to allow apps to find the headers and SDK, even if the app is not well configured. In particular, it's adding `--sysroot=/Applications/Xcode.app/Content
s/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk` which is detrimental in your case.

**Comment by ExtremeMan** [comment]
I guess the only way is to disable the warning which is quite unfortunate. Any other ideas?

**Comment by aklowther** [comment]
@ExtremeMan @fxcoudert thanks for getting this started, do you think it will merge soon?

**Comment by ExtremeMan** [comment]
I don't think I want to change how xctool is built and support wrong build environments.

**Pull request closed without merging**
