### PR TITLE
[ace] Upgrade to 7.0.4

### PR DESCRIPTION
**Pull request by jwillemsen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
>  Have you ensured that your commits follow the commit style guide?

Please actually perform the actions before you check the checkbox. This format is nothing like the style guide

**Comment by jwillemsen** [comment]
Ok, closed the PR, will leave this for someone else to update at some point

**Comment by SMillerDev** [comment]
You could also just rename your commit to the style guide, or leave the checkbox unchecked.

**Comment by jwillemsen** [comment]
Would be much easier when there would be a bot for this kind of upgrades like conda-forge has, they automatically create a PR https://github.com/conda-forge/ace-feedstock/pull/27

**Pull request closed without merging**
