### PR TITLE
openjdk@12: delete

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

OpenJDK 12 reached its end of life in September 2019.

### CODE REVIEW

**Comment by zbeekman** [comment]
Just to confirm since I'm ignorant about java: OpenJDK 11 is a long term release that is still supported, presumably?

**Comment by Bo98** [comment]
Yes, OpenJDK 11 is LTS. Regular major releases are only supported until the next one is released - OpenJDK 13 will cease being supported when OpenJDK 14 is released next month. The next LTS is OpenJDK 17.

When exactly until is a little bit up in the air but it's at least 2-3 years more. OpenJDK 8 is still going, and potentially may continue to longer than OpenJDK 11, but there was a lot of changes between 8 and 9 which has left some projects stuck relying on 8.

**Review by zbeekman — APPROVED** [review]
LGTM

**Comment by zbeekman** [comment]
merging 🍻

**Pull request closed without merging**
