### PR TITLE
elektra 0.9.14

### PR DESCRIPTION
**Pull request by mpranj**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not marked as the latest release yet: https://github.com/ElektraInitiative/libelektra/releases

**Comment by mpranj** [comment]
> Not marked as the latest release yet

It's published now.

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Thanks @mpranj.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@mpranj I wonder if you can add [bump-homebrew-formula-action step](https://github.com/mislav/bump-homebrew-formula-action) as part of your release pipeline.

**Comment by mpranj** [comment]
> I wonder if you can add [bump-homebrew-formula-action step](https://github.com/mislav/bump-homebrew-formula-action) as part of your release pipeline.

Thank you! We'll definitely look into it.

**Pull request closed without merging**
