### PR TITLE
logstash 8.4.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Now supporting `openjdk@17`, and it fixed the issues with tests!

**Review by iMichka — APPROVED** [review]
From what I see in the logs, ARM bottles were built. It's just 4 times faster to build on ARM than on Intel.

**Comment by Porkepix** [comment]
> From what I see in the logs, ARM bottles were built. It's just 4 times faster to build on ARM than on Intel.

But then why is there a `no ARM bottle` tag?

**Comment by chenrui333** [comment]
> > From what I see in the logs, ARM bottles were built. It's just 4 times faster to build on ARM than on Intel.
> 
> But then why is there a `no ARM bottle` tag?

when it was built [last time](https://github.com/Homebrew/homebrew-core/pull/96266), there was ARM bottles for dependencies.

**Comment by iMichka** [comment]
Ha yes, that's openjdk was not bottled for ARM at one point, so I guess the previous build/run did not create an ARM bottle.
The label on the pull request just tells us that there was no ARM bottle before.

This should be fixed with the current run.

**Comment by iMichka** [comment]
ARM bottles are here now: https://github.com/Homebrew/homebrew-core/commit/a6af59ccda6b56d6c14d5637c04f91ecd36a923d

**Pull request closed without merging**
