### PR TITLE
docker 17.04.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nijikon — APPROVED** [review]

**Comment by JCount** [comment]
I am somewhat concerned about only tracking the Docker CE Edge, because although the release names have no real semantic meaning, there really are two separate release channels. The Docker CE 17.03.x branch is the current "Stable" branch and will continue to see patch level, but not feature level, releases. Importantly, Docker EE is also synchronized with this release branch, so Docker CE Edge might have compatibility issues with it, though this may not really be an issue for our users.
```
Stable
The Stable version is fully baked and tested, and comes with the
latest GA release of Docker.
Edge
The Edge version offers cutting edge features and comes with
experimental features turned on.
```

I acknowledge that most users will want to be using Docker CE Edge, so I think that this PR makes sense, though adding that this formula tracks the Edge release branch to the description is probably a good idea.

-----
Therefore my proposal is such:
* Add text to the formula description indicating that it is tracking the Edge branch
* Create a new `docker-stable` formula and indicate that it is tracking the Stable branch
* Hopefully users who need the Stable branch will read the description in this formula, and find the new formula.
* Having this slight reversal where the Edge branch is the main formula instead of the Stable branch is probably what most of our users want/expect.

**DISCLAIMER**
I wrote this in a rush because I have little time, so please excuse any mistakes or if this makes no sense at all.

**Review by JCount — APPROVED** [review]
The most sensible thing to do here is probably just merge this, and see if there ends up being user demand for CE Stable, at which point we can reevaluate whether we want to track both branches or not. So, merge away!

**Comment by JCount** [comment]
👽

**Comment by ilovezfs** [comment]
>The Edge version offers cutting edge features and comes with
experimental features turned on.

Note that while that might be the case for their prebuilt binaries, the experimental features are still opt-in, not opt-out, in this PR.

**Comment by JCount** [comment]
Correct. Being able to make those features optional lends weight to the decision to track the Edge branch ourselves.

**Pull request closed without merging**
