### PR TITLE
phpunit: import from homebrew/php

### PR DESCRIPTION
**Pull request by javian**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This is a migration from homebrew-core @MikeMcQuaid

### CODE REVIEW

**Comment by kabel** [comment]
General question about these packages. They _could_ be managed through composer (`composer global require phpunit`), so what's the motivation to keep them in brew, other than popular historic use?

**Comment by ilovezfs** [comment]
@kabel it's a good question. I think in this case `brew install` is a replacement for the procedure described on the left, not the right, in https://phpunit.de/getting-started/phpunit-7.html

**Comment by javian** [comment]
@kabel composer doesn't seem to handle dependencies very well when projects are not using the same versions such as in this case
```
➜  ~ composer global require friendsofphp/php-cs-fixer
Changed current directory to /Users/javian/.composer
Using version ^2.11 for friendsofphp/php-cs-fixer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 16 installs, 0 updates, 0 removals
  - Installing symfony/stopwatch (v4.0.6): Downloading (100%)
  - Installing symfony/process (v4.0.6): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.7.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.11): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.7.0): Downloading (100%)
  - Installing symfony/options-resolver (v4.0.6): Downloading (100%)
  - Installing symfony/finder (v4.0.6): Downloading (100%)
  - Installing symfony/filesystem (v4.0.6): Downloading (100%)
  - Installing symfony/event-dispatcher (v4.0.6): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.7.0): Downloading (100%)
  - Installing symfony/console (v4.0.6): Downloading (100%)
  - Installing php-cs-fixer/diff (v1.3.0): Downloading (100%)
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
  - Installing doctrine/annotations (v1.6.0): Downloading (100%)
  - Installing composer/semver (1.4.2): Downloading (100%)
  - Installing friendsofphp/php-cs-fixer (v2.11.1): Downloading (100%)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/console suggests installing symfony/lock ()
symfony/console suggests installing psr/log (For using the console logger)
Writing lock file
Generating autoload files
➜  ~ composer global require wp-cli/wp-cli
Changed current directory to /Users/javian/.composer
Using version ^1.5 for wp-cli/wp-cli
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wp-cli/wp-cli ^1.5 -> satisfiable by wp-cli/wp-cli[v1.5.0].
    - Conclusion: remove symfony/console v4.0.6
    - Conclusion: don't install symfony/console v4.0.6
    - wp-cli/wp-cli v1.5.0 requires symfony/console ^2.7|^3.0 -> satisfiable by symfony/console[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6].
    - Can only install one of: symfony/console[v3.2.0, v4.0.6].
    - Can only install one of: symfony/console[v3.2.1, v4.0.6].
    - Can only install one of: symfony/console[v3.2.10, v4.0.6].
    - Can only install one of: symfony/console[v3.2.11, v4.0.6].
    - Can only install one of: symfony/console[v3.2.12, v4.0.6].
    - Can only install one of: symfony/console[v3.2.13, v4.0.6].
    - Can only install one of: symfony/console[v3.2.14, v4.0.6].
    - Can only install one of: symfony/console[v3.2.2, v4.0.6].
    - Can only install one of: symfony/console[v3.2.3, v4.0.6].
    - Can only install one of: symfony/console[v3.2.4, v4.0.6].
    - Can only install one of: symfony/console[v3.2.5, v4.0.6].
    - Can only install one of: symfony/console[v3.2.6, v4.0.6].
    - Can only install one of: symfony/console[v3.2.7, v4.0.6].
    - Can only install one of: symfony/console[v3.2.8, v4.0.6].
    - Can only install one of: symfony/console[v3.2.9, v4.0.6].
    - Can only install one of: symfony/console[v3.3.0, v4.0.6].
    - Can only install one of: symfony/console[v3.3.1, v4.0.6].
    - Can only install one of: symfony/console[v3.3.10, v4.0.6].
    - Can only install one of: symfony/console[v3.3.11, v4.0.6].
    - Can only install one of: symfony/console[v3.3.12, v4.0.6].
    - Can only install one of: symfony/console[v3.3.13, v4.0.6].
    - Can only install one of: symfony/console[v3.3.14, v4.0.6].
    - Can only install one of: symfony/console[v3.3.15, v4.0.6].
    - Can only install one of: symfony/console[v3.3.16, v4.0.6].
    - Can only install one of: symfony/console[v3.3.2, v4.0.6].
    - Can only install one of: symfony/console[v3.3.3, v4.0.6].
    - Can only install one of: symfony/console[v3.3.4, v4.0.6].
    - Can only install one of: symfony/console[v3.3.5, v4.0.6].
    - Can only install one of: symfony/console[v3.3.6, v4.0.6].
    - Can only install one of: symfony/console[v3.3.7, v4.0.6].
    - Can only install one of: symfony/console[v3.3.8, v4.0.6].
    - Can only install one of: symfony/console[v3.3.9, v4.0.6].
    - Can only install one of: symfony/console[v3.4.0, v4.0.6].
    - Can only install one of: symfony/console[v3.4.1, v4.0.6].
    - Can only install one of: symfony/console[v3.4.2, v4.0.6].
    - Can only install one of: symfony/console[v3.4.3, v4.0.6].
    - Can only install one of: symfony/console[v3.4.4, v4.0.6].
    - Can only install one of: symfony/console[v3.4.5, v4.0.6].
    - Can only install one of: symfony/console[v3.4.6, v4.0.6].
    - Can only install one of: symfony/console[v2.7.0, v4.0.6].
    - Can only install one of: symfony/console[v2.7.1, v4.0.6].
    - Can only install one of: symfony/console[v2.7.10, v4.0.6].
    - Can only install one of: symfony/console[v2.7.11, v4.0.6].
    - Can only install one of: symfony/console[v2.7.12, v4.0.6].
    - Can only install one of: symfony/console[v2.7.13, v4.0.6].
    - Can only install one of: symfony/console[v2.7.14, v4.0.6].
    - Can only install one of: symfony/console[v2.7.15, v4.0.6].
    - Can only install one of: symfony/console[v2.7.16, v4.0.6].
    - Can only install one of: symfony/console[v2.7.17, v4.0.6].
    - Can only install one of: symfony/console[v2.7.18, v4.0.6].
    - Can only install one of: symfony/console[v2.7.19, v4.0.6].
    - Can only install one of: symfony/console[v2.7.2, v4.0.6].
    - Can only install one of: symfony/console[v2.7.20, v4.0.6].
    - Can only install one of: symfony/console[v2.7.21, v4.0.6].
    - Can only install one of: symfony/console[v2.7.22, v4.0.6].
    - Can only install one of: symfony/console[v2.7.23, v4.0.6].
    - Can only install one of: symfony/console[v2.7.24, v4.0.6].
    - Can only install one of: symfony/console[v2.7.25, v4.0.6].
    - Can only install one of: symfony/console[v2.7.26, v4.0.6].
    - Can only install one of: symfony/console[v2.7.27, v4.0.6].
    - Can only install one of: symfony/console[v2.7.28, v4.0.6].
    - Can only install one of: symfony/console[v2.7.29, v4.0.6].
    - Can only install one of: symfony/console[v2.7.3, v4.0.6].
    - Can only install one of: symfony/console[v2.7.30, v4.0.6].
    - Can only install one of: symfony/console[v2.7.31, v4.0.6].
    - Can only install one of: symfony/console[v2.7.32, v4.0.6].
    - Can only install one of: symfony/console[v2.7.33, v4.0.6].
    - Can only install one of: symfony/console[v2.7.34, v4.0.6].
    - Can only install one of: symfony/console[v2.7.35, v4.0.6].
    - Can only install one of: symfony/console[v2.7.36, v4.0.6].
    - Can only install one of: symfony/console[v2.7.37, v4.0.6].
    - Can only install one of: symfony/console[v2.7.38, v4.0.6].
    - Can only install one of: symfony/console[v2.7.39, v4.0.6].
    - Can only install one of: symfony/console[v2.7.4, v4.0.6].
    - Can only install one of: symfony/console[v2.7.40, v4.0.6].
    - Can only install one of: symfony/console[v2.7.41, v4.0.6].
    - Can only install one of: symfony/console[v2.7.42, v4.0.6].
    - Can only install one of: symfony/console[v2.7.43, v4.0.6].
    - Can only install one of: symfony/console[v2.7.5, v4.0.6].
    - Can only install one of: symfony/console[v2.7.6, v4.0.6].
    - Can only install one of: symfony/console[v2.7.7, v4.0.6].
    - Can only install one of: symfony/console[v2.7.8, v4.0.6].
    - Can only install one of: symfony/console[v2.7.9, v4.0.6].
    - Can only install one of: symfony/console[v2.8.0, v4.0.6].
    - Can only install one of: symfony/console[v2.8.1, v4.0.6].
    - Can only install one of: symfony/console[v2.8.10, v4.0.6].
    - Can only install one of: symfony/console[v2.8.11, v4.0.6].
    - Can only install one of: symfony/console[v2.8.12, v4.0.6].
    - Can only install one of: symfony/console[v2.8.13, v4.0.6].
    - Can only install one of: symfony/console[v2.8.14, v4.0.6].
    - Can only install one of: symfony/console[v2.8.15, v4.0.6].
    - Can only install one of: symfony/console[v2.8.16, v4.0.6].
    - Can only install one of: symfony/console[v2.8.17, v4.0.6].
    - Can only install one of: symfony/console[v2.8.18, v4.0.6].
    - Can only install one of: symfony/console[v2.8.19, v4.0.6].
    - Can only install one of: symfony/console[v2.8.2, v4.0.6].
    - Can only install one of: symfony/console[v2.8.20, v4.0.6].
    - Can only install one of: symfony/console[v2.8.21, v4.0.6].
    - Can only install one of: symfony/console[v2.8.22, v4.0.6].
    - Can only install one of: symfony/console[v2.8.23, v4.0.6].
    - Can only install one of: symfony/console[v2.8.24, v4.0.6].
    - Can only install one of: symfony/console[v2.8.25, v4.0.6].
    - Can only install one of: symfony/console[v2.8.26, v4.0.6].
    - Can only install one of: symfony/console[v2.8.27, v4.0.6].
    - Can only install one of: symfony/console[v2.8.28, v4.0.6].
    - Can only install one of: symfony/console[v2.8.29, v4.0.6].
    - Can only install one of: symfony/console[v2.8.3, v4.0.6].
    - Can only install one of: symfony/console[v2.8.30, v4.0.6].
    - Can only install one of: symfony/console[v2.8.31, v4.0.6].
    - Can only install one of: symfony/console[v2.8.32, v4.0.6].
    - Can only install one of: symfony/console[v2.8.33, v4.0.6].
    - Can only install one of: symfony/console[v2.8.34, v4.0.6].
    - Can only install one of: symfony/console[v2.8.35, v4.0.6].
    - Can only install one of: symfony/console[v2.8.36, v4.0.6].
    - Can only install one of: symfony/console[v2.8.4, v4.0.6].
    - Can only install one of: symfony/console[v2.8.5, v4.0.6].
    - Can only install one of: symfony/console[v2.8.6, v4.0.6].
    - Can only install one of: symfony/console[v2.8.7, v4.0.6].
    - Can only install one of: symfony/console[v2.8.8, v4.0.6].
    - Can only install one of: symfony/console[v2.8.9, v4.0.6].
    - Can only install one of: symfony/console[v3.0.0, v4.0.6].
    - Can only install one of: symfony/console[v3.0.1, v4.0.6].
    - Can only install one of: symfony/console[v3.0.2, v4.0.6].
    - Can only install one of: symfony/console[v3.0.3, v4.0.6].
    - Can only install one of: symfony/console[v3.0.4, v4.0.6].
    - Can only install one of: symfony/console[v3.0.5, v4.0.6].
    - Can only install one of: symfony/console[v3.0.6, v4.0.6].
    - Can only install one of: symfony/console[v3.0.7, v4.0.6].
    - Can only install one of: symfony/console[v3.0.8, v4.0.6].
    - Can only install one of: symfony/console[v3.0.9, v4.0.6].
    - Can only install one of: symfony/console[v3.1.0, v4.0.6].
    - Can only install one of: symfony/console[v3.1.1, v4.0.6].
    - Can only install one of: symfony/console[v3.1.10, v4.0.6].
    - Can only install one of: symfony/console[v3.1.2, v4.0.6].
    - Can only install one of: symfony/console[v3.1.3, v4.0.6].
    - Can only install one of: symfony/console[v3.1.4, v4.0.6].
    - Can only install one of: symfony/console[v3.1.5, v4.0.6].
    - Can only install one of: symfony/console[v3.1.6, v4.0.6].
    - Can only install one of: symfony/console[v3.1.7, v4.0.6].
    - Can only install one of: symfony/console[v3.1.8, v4.0.6].
    - Can only install one of: symfony/console[v3.1.9, v4.0.6].
    - Installation request for symfony/console (locked at v4.0.6) -> satisfiable by symfony/console[v4.0.6].


Installation failed, reverting ./composer.json to its original content.
➜  ~
```
Keeping these contained to your project rather than using them on the global level (or using something like phive to manage your phars) is probably the easiest way to make sure you don't get conflicts or can handle them on a per project basis.

**Comment by javian** [comment]
Here's another explanation of the dependency issues with composer https://github.com/composer/composer/issues/2609

**Comment by javian** [comment]
The test fails since this version of phpunit only supports php 7.1 and 7.2 . Either putting a hard dependency on `php` or use `depends_on "php" => :test` - which option do you think would be most viable ? In the tap there's been older versions of the formula to also work against the other php versions but that could potentially make it a bit messy going forward.

**Comment by SMillerDev** [comment]
I'd say depends_on :test

**Review by SMillerDev — APPROVED** [review]
Nice tests

**Comment by ilovezfs** [comment]
Thanks @javian! ✅

**Pull request merged**
