### PR TITLE
ffmpeg 3.3.3

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

### CODE REVIEW

**Comment by zmwangx** [comment]
3.3.3 still uses yasm as the default x86 assembler.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Why does the CI say `macOS El Capitan or newer is required`?

**Comment by zmwangx** [comment]
? Got a link?

**Comment by fxcoudert** [comment]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5590/version=yosemite/console

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-test-bot/pull/14

**Comment by zmwangx** [comment]
I only see two MinMOSR's in core, `nordugrid-arc` and `phantomjs`, and they don't appear to be related to `ffmpeg`.

**Comment by fxcoudert** [comment]
@ilovezfs I don't see which deps would do that

**Comment by ilovezfs** [comment]
zimg

**Comment by fxcoudert** [comment]
That's an optional dependency, why should the CI care?

**Comment by ilovezfs** [comment]
because ffmpeg.stable.recursive_requirements makes no distinction

**Comment by zmwangx** [comment]
But losing the bottles because of some optional dependency is not great.

**Comment by ilovezfs** [comment]
```
irb(main):002:0> Formula["ffmpeg"].stable.recursive_requirements.map(&:inspect)
=> ["#<GitRequirement: \"git\" [:build]>", "#<MinimumMacOSRequirement: \"minimummacos\" [:lion]>", "#<MinimumMacOSRequirement: \"minimummacos\" [:el_capitan]>", "#<JavaRequirement: \"java\" [] version=\"1.8+\">"]
```

**Comment by ilovezfs** [comment]
@zmwangx I didn't say it was good.

**Comment by ilovezfs** [comment]
:video_camera:

**Comment by ilovezfs** [comment]
```
diff --git a/Library/Homebrew/software_spec.rb b/Library/Homebrew/software_spec.rb
index 0d2b48a..c91d949 100644
--- a/Library/Homebrew/software_spec.rb
+++ b/Library/Homebrew/software_spec.rb
@@ -164,6 +164,7 @@ class SoftwareSpec
     deps_f = []
     recursive_dependencies = deps.map do |dep|
       begin
+        next if dep.optional?
         deps_f << dep.to_formula
         dep
       rescue TapFormulaUnavailableError
@@ -173,6 +174,7 @@ class SoftwareSpec
     end.compact.uniq
     deps_f.compact.each do |f|
       f.recursive_dependencies.each do |dep|
+        next if dep.optional?
         recursive_dependencies << dep unless recursive_dependencies.include?(dep)
       end
     end
```
I think is what we want, though I'm not sure if we should filter build too.

**Pull request closed without merging**
