### PR TITLE
*formulae: Normalize resource names from Python package name

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- Companion PR to https://github.com/Homebrew/brew/pull/15942 to ensure that Python resource names follow a consistent format and match PyPI package names.

### CODE REVIEW

**Comment by chenrui333** [comment]
there are some formulae are deprecated/disabled, not sure if we need to touch them.

**Comment by issyl0** [comment]
The audit fails on them (see https://github.com/Homebrew/brew/actions/runs/6108075734/job/16576395843?pr=15942#step:6:1), so maybe we want it to come back clean? Should this new audit skip disabled formulae? Do other audits skip disabled formulae?

**Comment by chenrui333** [comment]
oh, if it failed the action run, then that is good then.

**Comment by p-linnane** [comment]
Can you squash the two `ansible@6` commits together? Otherwise this will dispatch the PR replacement workflow to autosquash them and rerun all the jobs again 🫠

**Comment by issyl0** [comment]
Thanks @p-linnane; done.

**Comment by issyl0** [comment]
The `textract` formula is failing to build with the following error due to https://github.com/deanmalmgren/textract/issues/476.

```
  error in textract setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; .* suffix can only be used with `==` or `!=` operators
      extract-msg<=0.29.*
```

**Review by p-linnane — APPROVED** [review]
Looks great. Thanks @issyl0!

**Pull request merged**
