### PR TITLE
subversion: remove options.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
See https://github.com/Homebrew/homebrew-core/issues/31510

### CODE REVIEW

**Comment by markphip** [comment]
I do not understand how this is OK and was committed?

If you want to remove the --with-java option fine, but that should just mean this option is part of the normal bottle and not an option.  Instead it was just removed, so now the Java bindings are not included. I never understood why this was an option in the first place, but the code to build the Java binding should just happen with or without the option being provided ... not be removed.

**Comment by MikeMcQuaid** [comment]
> I do not understand how this is OK and was committed?

https://formulae.brew.sh/formula/subversion showed the vast majority of Subversion users did not use this option.

> I never understood why this was an option in the first place, but the code to build the Java binding should just happen with or without the option being provided ... not be removed.

Is Java a build-time dependency in this case i.e. can Subversion be used if the Java bindings are built without the user needing to have Java installed? If so, we can consider building the bindings by default.

Reminder that Java does not ship with macOS so we cannot make everyone who wants to use Subversion require Java to be installed.

**Comment by markphip** [comment]
Yes. Was chatting with @brainy about this on the SVN mailing lists too.

Java is just a build-time dependency.  It will cause a dylib and jar to be added to the deliverables but has little effect on the runtime.  We would probably want to still tell the user about adding the symlink of the lib if they want to use it, but otherwise it ought not have any other impact.

This is really widely used by Eclipse IDE users. I maintain Subclipse and have already received an issue today.

**Comment by MikeMcQuaid** [comment]
> Yes. Was chatting with @brainy about this on the SVN mailing lists too.
> 
> Java is just a build-time dependency. It will cause a dylib and jar to be added to the deliverables but has little effect on the runtime.

Perfect. Opened a PR for this: https://github.com/Homebrew/homebrew-core/pull/36387

**Pull request merged**
