### PR TITLE
ansible@2.8 2.8.7 (new formula)

### PR DESCRIPTION
**Pull request by mathbunnyru**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions) and why we might want to ship an older version?

**Comment by mathbunnyru** [comment]
Ansible 2.9 breaks some things. (https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#deprecated-features)

This change fills all the criteria in the bullet list.
2.8 is still maintained and it will be maintained for a year.

If you think I should still create my tap, let me know, I will try to learn how to do that, but I think it may be useful to have 2.8 for everyone for some time.

**Comment by SMillerDev** [comment]
Thanks @mathbunnyru! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by bayandin** [comment]
We need to recreate bottles

@BrewTestBot test this please.

**Pull request closed without merging**
