### PR TITLE
compcert 2.7.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Coq 8.5 support

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 Finally!

**Comment by DomT4** [comment]
Nice! So much nicer a formula to look at this way 😄. LGTM, Thanks 🙇.

**Comment by ilovezfs** [comment]
@DomT4 So what you're saying is, you don't think every formula should vendor its own compiler? :confused:

:)

**Comment by DomT4** [comment]
> So what you're saying is, you don't think every formula should vendor its own compiler?

I am very, very much saying this, yes 😉

**Pull request closed without merging**
