### PR TITLE
Gnome 3.20.0

### PR DESCRIPTION
**Pull request by tschoonj**
This is the continuation of PR Homebrew/legacy-homebrew#50257

Not to be merged yet as gtk+3.0 (and a couple of others too) is still quite buggy.

### CODE REVIEW

**Comment by apjanke** [comment]
I'm bumping `vte3` in a separate PR -  #277 - because a user reports our current version is broken - #255.

**Comment by UniqMartin** [comment]
@tschoonj What is the status here? Can you give an estimate of when this might be ready? I'm asking because there have been already several attempts to bump `libgit2` (as apparently some packages that depend on it started raising their requirements) …

**Comment by tschoonj** [comment]
Currently there are only three packages in Homebrew that depend on libgit2: libgit2-glib, gnome-builder and gitg (all three are GNOME packages btw). Unfortunately this new version of libgit2 breaks API which means that its three dependents will need to be updated too. Problem is that gnome-builder depends on gtk3 3.20, which is still not working properly...

**Comment by UniqMartin** [comment]
Thanks for the update!

> Currently there are only three packages in Homebrew that depend on libgit2: […]

Yes, I know. It seems that other software outside of Homebrew proper depends on `libgit2` and people are using Homebrew to get all necessary dependencies, notice they are not getting the latest version, and consequently attempt to bump it. They don't see the bigger picture with respect to Gnome. I guess there's not much we can do until `gtk+3` stabilizes …

**Comment by s172262** [comment]
Gnome 3.20.0 needs libffi-3.2.1. But you use "3.0.13" in some cases(gedit.rb, gitg.rb and libpeas.rb). I think using `#{libffi.version}` is better.

**Comment by tschoonj** [comment]
Gnome 3.20.0 does not need libffi 3.2.1. Currently the Homebrew formula is at 3.0.13 and this turned out to be sufficient to build all the formulas in this PR.

I think it's best that if someone updates libffi to 3.2.1 (there have been many attempts), it is best that at that moment all formulas whose tests will fail (including the ones you mention), have their test blocks updated to reflect the new libffi version.

**Comment by s172262** [comment]
I'm sorry my lack of talk. 
I think it is better to writte `libffi-#{Formura["libffi"].version}` like a https://github.com/Homebrew/homebrew-core/blob/fb81645562f7e495a49561065912788af2d1f14f/Formula/rakudo-star.rb

I wonder why I cannot add note on your source in this PR?

By the way, Upstream say  that my patch for libffi 3.2.1 (https://github.com/Homebrew/legacy-homebrew/pull/50312) builds just fine on recent OSX versions but doesn't build on older versions, specifically 10.6 and earlier. I will not develop it no more because I don't have environment of 10.6 and  earlier.

**Comment by blogabe** [comment]
What's the ETA to merge all these changes.  Not necessarily interested in Gnome but there are some dependencies that are covered in this request that are ready to merge.  I think so anyway?

**Comment by tschoonj** [comment]
Unfortunately I no longer have the time to manage this thread properly. Feel free to do what it as you see fit. 

For the record: from the changelings it looks like they still haven't fixed that problem with the FileChooserDialogs but I havent actually compiled and checked.

**Comment by blogabe** [comment]
@UniqMartin please advise

**Comment by MikeMcQuaid** [comment]
@blogabe At this stage we probably need to close this out and wait for @tschoonj to open a new PR or someone else to do so based on his work.

For me this situation is a pretty strong argument for almost everything in this PR to move into a `homebrew-gnome` tap.

**Comment by blogabe** [comment]
@MikeMcQuaid In my personal case, I don't really care about Gnome, but I do care about certain dependencies.  I understand the rationale on filing one PR when Gnome gets updated, but it's stopping the other dependencies that I depend on from getting independently updated (https://github.com/Homebrew/homebrew-core/pull/550).

**Comment by DomT4** [comment]
If we update to the latest GNOME releases, GTK+3 is currently on `3.20.6` for example upstream, apparently the hold-up here has been fixed. From the Debian changelog on `3.20.5`'s release:

> Cherry-pick patch from upstream Git which reverts a commit that was causing crashes in the filechooser in some applications.

So if they patched that in `3.20.5` either there's a patch floating around Debian we can steal, or the fix already made it into the `3.20.6` release.

**Comment by MikeMcQuaid** [comment]
@blogabe In this case the problem is that upgrading some of these things independently breaks others.

**Comment by sirblackheart** [comment]
>  or the fix already made it into the 3.20.6 release.

Arch [dropped](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gtk3&id=8f7b1f1fce4cd4760505e06f2e9e38f80db118a3) the patch for the `3.20.6` release so i guess this issue is fixed in  `3.20.6`.

**Pull request closed without merging**
