### PR TITLE
octave 7.3.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Is configuring with `--enable-link-all-dependencies` still necessary for macOS?

**Comment by ZhongRuoyu** [comment]
> Is configuring with `--enable-link-all-dependencies` still necessary for macOS?

Sorry, I am not familiar with Octave, nor authoritative enough, to answer this. But looks like it's been there since the beginning (40d0219285de5e4b215faf2dbc1a920ce5a5e042).

---

CI failed while running `patchelf` on `cups`. Does that have anything to do with the newly upgraded `patchelf-1.4.0`?

```
  ==> Installing octave dependency: cups
  ==> Pouring cups--2.4.2.x86_64_linux.bottle.tar.gz
  Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
  Do not report this issue until you've run `brew update` and tried again.
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:682:in `normalize_note_segment'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:659:in `block in normalize_note_segments'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:955:in `block in phdrs_by_type'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each_with_index'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `phdrs_by_type'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:653:in `normalize_note_segments'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:638:in `rewrite_sections_library'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:475:in `rewrite_sections'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:88:in `save!'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:191:in `save'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:167:in `save_using_patchelf_rb'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:112:in `patch!'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:53:in `change_rpath'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:15:in `block (2 levels) in relocate_dynamic_linkage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:341:in `ensure_writable'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:14:in `block in relocate_dynamic_linkage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `each'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `relocate_dynamic_linkage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:132:in `replace_placeholders_with_locations'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1226:in `pour'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:425:in `install'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:738:in `install_dependency'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:656:in `block in install_dependencies'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:656:in `each'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:656:in `install_dependencies'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:400:in `install'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `each'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by mmuetzel** [comment]
> > Is configuring with `--enable-link-all-dependencies` still necessary for macOS?
> 
> Sorry, I am not familiar enough with Octave, so it may be better to wait for a more authorirative answer to this. But looks like it's been there since the beginning ([40d0219](https://github.com/Homebrew/homebrew-core/commit/40d0219285de5e4b215faf2dbc1a920ce5a5e042)).

I'm in the reverse position: I don't know much about macOS. It might be that this switch was needed in the past. But there have been some macOS-related changes in Octave's build system. And I'm not certain if it is still required to link to all dependencies.
Fwiw, Octave itself seems to build fine on GitHub runners in our CI without that flag. I'm not sure if it is needed for something else though (apart from building and running the test suite). Maybe Octave packages?

**Comment by siko1056** [comment]
@ZhongRuoyu Was it possible to re-open this PR again and re-run the test pipeline once more?  I do not think this error is Octave (Octave does not configure cups) related at all and the run failure might just have been "bad luck"

https://github.com/Homebrew/homebrew-core/actions/runs/3395969513/jobs/5646579523#step:7:4455

**Comment by siko1056** [comment]
CC: @carlocab

**Comment by ZhongRuoyu** [comment]
> Was it possible to re-open this PR again and re-run the test pipeline once more?

A scheduled `brew bump` has opened #116780 before me. Let's check that out.

**Pull request closed without merging**
