### PR TITLE
snapcraft 3.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tobias-grasse** [comment]
@chenrui333 [Build logs](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/51071/version=catalina/testReport/junit/brew-test-bot/catalina/test_snapcraft/) indicate a missing dependency `httplib2`. Would you mind adding it?

**Comment by chenrui333** [comment]
@tobias-grasse, I will tweak more about the deps tomorrow. Thanks for pointing it out.

**Comment by chenrui333** [comment]
@tobias-grasse, also feel free to submit a PR at your end, as the release is `v3.9.2` now. :)

**Comment by Bo98** [comment]
Will revisit this after Python 3.8.

**Comment by chenrui333** [comment]
Finished the updates of the formula and rebase to the latest master branch.

**Pull request closed without merging**
