### PR TITLE
libphonenumber 7.4.4

### PR DESCRIPTION
**Pull request by ilovezfs**
remove the patch since upstream has fixed the issue it was addressing

### CODE REVIEW

**Comment by DomT4** [comment]
Any chance at all that patch has been merged upstream?

**Comment by ilovezfs** [comment]
@DomT4 Upstream went with a different fix, but apparently it's fixed: https://github.com/googlei18n/libphonenumber/commit/86ace5112bd89ecc251d923ea67320cc73043421

So I'll remove the patch.

**Comment by ilovezfs** [comment]
PR refreshed.

**Comment by DomT4** [comment]
👍 when 🍏.

**Pull request closed without merging**
