### PR TITLE
ceres-solver 2.2.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Let's try this again

**Comment by SMillerDev** [comment]
This seems to break `opencv@3`
```
  /tmp/opencvA3-20231022-53690-1yafehw/opencv-3.4.16/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc:488:10: error: no type named 'SubsetParameterization' in namespace 'ceres'
    ceres::SubsetParameterization *constant_translation_parameterization = NULL;
    ~~~~~~~^
  /tmp/opencvA3-20231022-53690-1yafehw/opencv-3.4.16/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc:498:20: error: no type named 'SubsetParameterization' in namespace 'ceres'
          new ceres::SubsetParameterization(6, constant_translation);
              ~~~~~~~^
  /tmp/opencvA3-20231022-53690-1yafehw/opencv-3.4.16/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc:541:17: error: no member named 'SetParameterization' in 'ceres::Problem'
          problem.SetParameterization(current_camera_R_t,
          ~~~~~~~ ^
  /tmp/opencvA3-20231022-53690-1yafehw/opencv-3.4.16/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc:589:12: error: no type named 'SubsetParameterization' in namespace 'ceres'
      ceres::SubsetParameterization *subset_parameterization =
      ~~~~~~~^
  /tmp/opencvA3-20231022-53690-1yafehw/opencv-3.4.16/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc:590:18: error: no type named 'SubsetParameterization' in namespace 'ceres'
        new ceres::SubsetParameterization(OFFSET_MAX, constant_intrinsics);
            ~~~~~~~^
  /tmp/opencvA3-20231022-53690-1yafehw/opencv-3.4.16/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc:592:13: error: no member named 'SetParameterization' in 'ceres::Problem'
      problem.SetParameterization(ceres_intrinsics, subset_parameterization);
      ~~~~~~~ ^
```

**Review by iMichka — APPROVED** [review]

**Comment by SMillerDev** [comment]
@rgov any ideas for a fix for colmap?

**Comment by SMillerDev** [comment]
If anyone has time before me, what happens if we force colmap to C++17

**Comment by cho-m** [comment]
Kind of curious how next `colmap` release works as they also force C++14 though it could be dodging `ceres-solver` code that causes C++17 error.

Could try `inreplace`-ing the C++ standard in current release (maybe at https://github.com/colmap/colmap/blob/3.8/src/CMakeLists.txt#L46) but may fail if `colmap` is not C++17 compatible

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
