### PR TITLE
rocksdb 4.8

### PR DESCRIPTION
**Pull request by flier**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like `osquery` needs a formula `revision` bump here as well.

**Comment by ilovezfs** [comment]
@DomT4 I think we may need to wait on @theopolis to do these.

**Comment by DomT4** [comment]
He's usually pretty quick to reply, let's see what he says then.

**Comment by ilovezfs** [comment]
@DomT4 I've checked on the build from time to time, and there seem to be issues with aws-sdk-cpp version versus ours, but I'm sure he'll fill us in on the state of play :)

**Comment by theopolis** [comment]
Hey everyone, there shouldn't be an issue bumping the osquery revision. :) 

The `aws-sdk-cpp` formula is a dependency, but there's nothing blocking a bump or rebuild.

**Comment by DomT4** [comment]
Neat, thanks @theopolis! @flier Would you mind bumping the formula revision of `osquery` here as well, unless @ilovezfs has any thoughts/objections/etc?

**Comment by ilovezfs** [comment]
>any thoughts/objections/etc

My thought: :green_apple: makes me happy.

**Comment by flier** [comment]
I'm a little confuse about the `bumping the formula revision of osquery`, do you means to add a `revision 1` line after the `sha256`?

Thanks

**Comment by theopolis** [comment]
:+1:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/5d11bc1367d5d6df012bab2020195b036ad6ee93 & https://github.com/Homebrew/homebrew-core/commit/c097f9aee01fbfce274669137da7df7de0c8f417. Thank you for your contributions to Homebrew @flier; we appreciate them! :smiley_cat:

Minor future nit: I tweaked the commit messages to match our usual standard here. If you could try to stick to that sort of format in future that'd be ❤️. Not a big big deal, just makes things easier to read through at a glance.

**Comment by flier** [comment]
ok, thanks :)

**Comment by ilovezfs** [comment]
@DomT4 the aws issue I mentioned: https://github.com/facebook/osquery/issues/2362.

**Pull request closed without merging**
