### PR TITLE
Subversion 1.11.0

### PR DESCRIPTION
**Pull request by brainy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
In addition to updating to 1.11.0, I also disabled storing of passwords in clear text on the disk. The macOS Keychain is used by default anyway. Existing passwords stored on disk will still be used.

Edit: `--disable-plaintext-password-storage` will be the default in Subversion 1.12.

This pull request replaces #32885.

### CODE REVIEW

**Comment by brainy** [comment]
**Maintainers, please fix your High Sierra build machine.**

This is the `configure` error that causes the Subversion Ruby bindings build to fail:
```
checking for /usr/bin/ruby... /usr/bin/ruby
checking rb_hash_foreach... /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
```
The same problem broke #32885 and the fix is described in #33250.

**Comment by fxcoudert** [comment]
@brainy no need to shout. The High Sierra CI machines are working fine for all other builds.

According to [your analysis](https://github.com/Homebrew/homebrew-core/issues/33250#issuecomment-432391116), issue #33250 is about having an incomplete CLT install where the license has not been accepted, and the compiler is thus failing. This is not the case on our CI machine:

```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by brainy** [comment]
Sorry for "shouting" but it's been this way for weeks and `subversion.rb` updates are blocked because of it, despite a possible fix being known. Maybe the CLT needs to be reinstalled, or the license accepted on the command line anyway despite `clang --version` appearing to work. Not doing anything is hardly going to help unblock updates to this formula.

Frankly it's not clear to me why this is even happening; the 1.10.2 version checked out fine on your High Sierra bot, and that check for `rb_hash_foreach` has been in Subversion's configury for more than seven years. Something must have changed recently on that bot to break Ruby native extensions.

**Comment by brainy** [comment]
(FWIW, Subversion's build scripts did not change at all between 1.10.2 and 1.10.3.)

**Comment by MikeMcQuaid** [comment]
> and the fix is described in #33250.

That does not fix or reproduce the issue. `/usr/bin/ruby -r mkmf -e 'exit(have_func("rb_hash_foreach") ? 0 : 1)'` on both High Sierra build machines outputs the expected `yes` and `clang --version` doesn't produce the output you stated.

**Comment by MikeMcQuaid** [comment]
> Finally, to move this forward: do you have confirmation that this builds on High Sierra with Xcode 10 outside of our bot? On an interactive machine it would be much easier to debug that on a remote CI node.

Seconded and if you can provide your `brew config` output that would be helpful, too.

**Comment by brainy** [comment]
I installed High Sierra and Xcode 10+CLT a couple of weeks ago to test this issue, that's how I found the (a?) fix. Whatever is happening can't be specific to Subversion but to native Ruby extensions.

```
$ brew config
HOMEBREW_VERSION: 1.8.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdd8e9b7cf1e53322492e1e90f685c19bdfde506
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 27d60b06207177c80a997dc04b0d4a507639dd9c
Core tap last commit: 5 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_05
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
```

**Comment by brainy** [comment]
FYI, today I upgraded the CLT on that machine so that `brew config` now says:
```
...
CLT: 10.1.0.0.1.1539992718
Xcode: 10.0
```
but this did not affect the Ruby extensions.

**Comment by brainy** [comment]
Good morning,

Is there any chance that I could get SSH access to a non-privileged account on that High Sierra build machine to investigate this issue? It would probably make things simpler if I can compare the setup there with the [build slave](https://ci.apache.org/builders/svn-x64-macosx-full) for Subversion tests, which is also High Sierra and Xcode 10.

**Comment by MikeMcQuaid** [comment]
@brainy Sorry, we don't give out SSH access to non-maintainers for security reasons. Do you need to check `brew config` or more than that?

**Comment by brainy** [comment]
I really don't know, since I have no idea why the build is failing for you but works on Subversion's build slave that has the same configuration, as far as I'm aware.

**Comment by MikeMcQuaid** [comment]
Here's the `brew config` from our High Sierra machine (from the last completed build): https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/lastCompletedBuild/version=high_sierra/testReport/brew-test-bot/high_sierra/config/

If you let us know what commands you're interested in the output of we could run them and report back here.

**Comment by brainy** [comment]
I see two differences between the `brew config` output on the Subversion build slave and the one you just posted:
```
HOMEBREW_FORCE_VENDOR_RUBY: 1
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
```
on your High Sierra machine, but:
```
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
```
on our buildslave, the latter is the standard version of Ruby shipped with macOS. Given the output of the native extensions check from my [other comment](#issuecomment-434499875), I'm wondering if the reason could be some kind of mismatch between Ruby runtime libraries?

**Comment by brainy** [comment]
This is the [`mkmf.log`](https://paste.apache.org/IQVX) file from the Ruby configuration check on Subversion's build slave.

Could you please run the same commands on Homebrew's High Sierra machine? Ideally, though, you'd retry the whole subversion formula build and look at the `mkmf.log` file at the root of the build directory.

**Comment by MikeMcQuaid** [comment]
> Given the output of the native extensions check from my [other comment](#issuecomment-434499875), I'm wondering if the reason could be some kind of mismatch between Ruby runtime libraries?

Yes, it could be. I will retry the build here with that unset.

> Could you please run the same commands on Homebrew's High Sierra machine?

Sorry, I don't know which commands you mean based on that output. Can you paste them here (just the commands you would like the output from)?

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by brainy** [comment]
Just this: ```/usr/bin/ruby -r mkmf -e 'have_func("rb_hash_foreach")'``` and then look at mkmf.log (it should be in the same directory).

**Comment by brainy** [comment]
```
subversive@subversive:~$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```

**Comment by jbarehart** [comment]
I have also noticed this problem on my Sierra system.

My `brew config` output:

```
HOMEBREW_VERSION: 1.8.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f458aaed494eaab92622f41f9f1967add00b0f4
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6739097ca1677ab2742e67e3e674ef301b77fa8c
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11
```

I ran `/usr/bin/ruby -v -d -r mkmf -e 'have_func("rb_hash_foreach")'` after verifying that I receive valid output from `clang --version`. Following is the content of `mkmf.log` from that run:

```
Exception `RuntimeError' at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456 - The compiler failed to generate an executable file.
You have to install development tools first.

"xcrun clang -o conftest -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin16 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS -iwithsysroot /usr/local/libressl/include conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib -L.             -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/local/libressl/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/local/lib   -arch x86_64 -arch i386   -lruby.2.3.0  -lpthread -ldl -lobjc "
In file included from conftest.c:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

And here is looking for ruby/config.h inside Xcode.app:

```
$ find /Applications/Xcode.app -iname config.h -print | grep -i ruby
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/Headers/ruby/config.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h
```

So maybe something in recent Xcode builds is broken? Or maybe the recently updated system ruby (from https://support.apple.com/en-us/HT209193) has an issue? Or something else entirely?

Additionally, I installed ruby@2.3 and when using it, `ruby -v -d -r mkmf -e 'have_func("rb_hash_foreach")'` is successful.

**Comment by brainy** [comment]
@jbarehart thanks for that! From your `mkmf.log` it's appears that either Ruby or Xcode are broken: the include path for xcrun does *not* contain the Ruby framework include directory. This should probably be reported to Apple, it looks like their bug.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by moonfruit** [comment]
No progress?

**Comment by smokris** [comment]
FWIW, this PR builds and runs successfully on my system.  My `brew config`:
```
HOMEBREW_VERSION: 1.8.6-14-ga2b4d4a
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a2b4d4aac294ec0872cd84d44f65bd5bd507e166
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ba684053676eea2abd0053b59b65aad7f2743d05
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11, 1.8.0_31
macOS: 10.14.2-x86_64
CLT: N/A
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```
Let me know if I can provide additional information or testing to help move this forward.

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
The current failure is a bit different:

```
/bin/sh "/private/tmp/subversion-20181226-87512-77q342/subversion-1.11.0/libtool" --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=penryn -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -O2  -DNDEBUG -Os -w -pipe -march=penryn -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/subversion/1.11.0/libexec/serf/include/serf-1 -I/usr/local/Cellar/openssl/1.0.2q/include -I/usr/local/opt/sqlite/include -I/usr/include -I/usr/local/Cellar/lz4/1.8.3/include   -o subversion/libsvn_subr/macos_keychain.lo -c subversion/libsvn_subr/macos_keychain.c
In file included from subversion/libsvn_subr/macos_keychain.c:42:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:36:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:354:49: error: expected a version of the form 'major[.minor[.subminor]]'
                                    macos(10.3, API_TO_BE_DEPRECATED),
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:355:46: error: expected a version of the form 'major[.minor[.subminor]]'
                                    ios(2.0, API_TO_BE_DEPRECATED),
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:356:50: error: expected a version of the form 'major[.minor[.subminor]]'
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
                                              ^
/bin/sh "/private/tmp/subversion-20181226-87512-77q342/subversion-1.11.0/libtool" --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=penryn -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -O2  -DNDEBUG -Os -w -pipe -march=penryn -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/subversion/1.11.0/libexec/serf/include/serf-1 -I/usr/local/Cellar/openssl/1.0.2q/include -I/usr/local/opt/sqlite/include -I/usr/include -I/usr/local/Cellar/lz4/1.8.3/include   -o subversion/libsvn_subr/md5.lo -c subversion/libsvn_subr/md5.c
4 errors generated.
make: *** [subversion/libsvn_subr/macos_keychain.lo] Error 1
```

I can repro this locally on a macOS 10.13 VM. I'll investigate.

**Comment by mistydemeo** [comment]
I've been able to come up with a minimal repro. This looks to be caused specifically by clashing system headers. It can be reproduced with this test file, which does nothing more than import the offending header:

```c
#include <Security/SecTrust.h>

int main() {}
```

And the following command:

```
/usr/bin/clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -I/usr/include   -o test.lo -c test.c
```

If either the `-isysroot` or `-I/usr/include` is missing, it builds fine. It's having both that's the fatal combination. My 10.13 VM *does* have a `/usr/include`, possibly left over from an older CLT version. I need to confirm what we have in CI.

**Comment by mistydemeo** [comment]
The following patch gets us a bit further by ensuring it no longer tries to access headers in `/usr/include`:

```patch
diff --git a/Formula/subversion.rb b/Formula/subversion.rb
index 18f7ad27..e9d44526 100644
--- a/Formula/subversion.rb
+++ b/Formula/subversion.rb
@@ -100,7 +100,7 @@ class Subversion < Formula
       --with-ruby-sitedir=#{lib}/ruby
       --with-serf=#{serf_prefix}
       --with-sqlite=#{Formula["sqlite"].opt_prefix}
-      --with-zlib=/usr
+      --with-zlib=#{MacOS.sdk_path}/usr
       --without-apache-libexecdir
       --without-berkeley-db
       --without-gpg-agent
```

However, that gets us back to the old `line 1760: none: command not found` bug. I'm continuing to investigate that one. My logs are here: https://gist.github.com/f9eec260582abff84f955ad2b933d680

**Pull request closed without merging**
