### PR TITLE
astyle: use linux-compatible url

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
This one is a little bit weird, and it is the only formula that does this. Why are there two different urls for a src package?

**Comment by SeekingMeaning** [comment]
```console
% ls astyle_3.1_macos/build
mac  xcode
```

```console
% ls astyle_3.1_linux/build
cb-clang  cb-gcc  cb-intel  clang  gcc	intel
```

Only the `build` folder is different

**Comment by fxcoudert** [comment]
Building from `astyle_3.1_linux.tar.gz` with `make -f ../build/gcc/Makefile` works perfectly on macOS :)

**Comment by fxcoudert** [comment]
And `CXX=#{ENV.cxx}` is not even needed, in fact

**Comment by SeekingMeaning** [comment]
`make -f ../build/gcc/Makefile` should produce `.so` libraries instead of `.dylib` though

**Comment by fxcoudert** [comment]
We're not building any libraries (and definitely not installing anything other than one binary).

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
