### PR TITLE
Use OpenBLAS instead of Accelerate on Armadillo

### PR DESCRIPTION
**Pull request by matteosecli**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Homebrew's ARPACK is compiled with OpenBLAS, but by default Armadillo is linked against the Accelerate framework on MacOS. This leads to uncaught runtime issues when using ARPACK-based routines in Armadillo.

Additionally Armadillo uses SuperLU to solve sparse systems and extend sparse diagonalization routines, so it should be added as a dependency. Homebrew's SuperLU is compiled with OpenBLAS as well.

Related: https://gitlab.com/conradsnicta/armadillo-code/-/issues/162

### CODE REVIEW

**Comment by SMillerDev** [comment]
@Homebrew/core anyone with experience with OpenBLAS etc?

**Comment by Bo98** [comment]
We've been regularly using OpenBLAS over Accelerate in recent times so this makes sense: https://github.com/Homebrew/homebrew-core/issues/39226

**Comment by sjackman** [comment]
@dpo Opinions?

**Comment by sjackman** [comment]
@matteosecli Please report the output of `brew linkage armadillo` with this patch applied.

**Comment by matteosecli** [comment]
> @matteosecli Please report the output of `brew linkage armadillo` with this patch applied.

```console
$ brew linkage armadillo
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib (arpack)
  /usr/local/opt/hdf5/lib/libhdf5.200.dylib (hdf5)
  /usr/local/opt/openblas/lib/libopenblas.0.dylib (openblas)
  /usr/local/opt/szip/lib/libsz.2.dylib (szip)
Indirect dependencies with linkage:
  openblas
```

**Comment by dpo** [comment]
> @dpo Opinions?

What's the motivation? The last time I checked, OpenBLAS wasn't always faster than Accelerate and Accelerate is already present on all macOS systems. The brewsci/num tap collects dependencies built against OpenBLAS. But I may have missed an episode. What does homebrew/core use these days? Accelerate or OpenBLAS?

**Comment by sjackman** [comment]
Looks good to me!

**Review by SMillerDev — DISMISSED** [review]

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
