### PR TITLE
talloc 2.3.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
```
Stable: The URL https://www.samba.org/ftp/talloc/talloc-2.3.0.tar.gz is not reachable (HTTP status code 103)
```

HTTP status code 103 is not indicative of an error, as far as I can tell.

**Comment by fxcoudert** [comment]
Merging. @alebcay can you please file a `brew` issue?

**Comment by alebcay** [comment]
`brew` issue has been filed at https://github.com/Homebrew/brew/issues/6431.

**Pull request closed without merging**
