### PR TITLE
hbase 2.2.5

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
==> nc 127.0.0.1 50953 2>&1
==> /usr/local/Cellar/hbase/2.2.5/bin/stop-hbase.sh
no hbase master found
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error: hbase: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Zookeeper/> was expected to be =~
<"">.
```

**Comment by SeekingMeaning** [comment]
I'm able to run the test commands manually but for some reason they don't work with `brew test`

**Comment by chenrui333** [comment]
> I'm able to run the test commands manually but for some reason they don't work with `brew test`

somehow I had the similar issues with rabbitmq and apache-flink. 

I think this might be well related to the port setup.

**Comment by chenrui333** [comment]
apache-flink is got fixed with modifying the result path.

**Pull request closed without merging**
