### PR TITLE
libtiff: enable zstd

### LINKED ISSUE #106450: GDAL with libtiff and ZSTD
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Convert a GeoTIFF file using GDAL with libtiff and ZSTD compression

### What happened (include all command output)?

```
❯ brew reinstall zstd libtiff gdal
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/manifests/1.5.2-2
Already downloaded: /Users/zakjan/Library/Caches/Homebrew/downloads/8c46fb1c48b918fc37efba746bfd56937d317bc161cf9fa7d777c36058b2a587--zstd-1.5.2-2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/blobs/sha256:c7084442d57331eb75dc51926bdbaab33c31059587a1626c714be87c1c43
Already downloaded: /Users/zakjan/Library/Caches/Homebrew/downloads/9e1f72f3479c2801ea261d72650b0f1c2031ada2747a4c18861ec89d88f3fa8e--zstd--1.5.2.arm64_monterey.bottle.2.tar.gz
==> Reinstalling zstd
==> Pouring zstd--1.5.2.arm64_monterey.bottle.2.tar.gz
🍺  /opt/homebrew/Cellar/zstd/1.5.2: 31 files, 2.2MB
==> Running `brew cleanup zstd`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/manifests/4.4.0
Already downloaded: /Users/zakjan/Library/Caches/Homebrew/downloads/b37cf6c170f1c01d5757e2494de5d65c9b117306a86f9e29f28e57b1a9972191--libtiff-4.4.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/blobs/sha256:d2dfbad3fe68e070d0937c71b4de6ca110dda32599a2adfc2272f3106
Already downloaded: /Users/zakjan/Library/Caches/Homebrew/downloads/a26e660ed5b116421a6dbb7550c38769a2c1ee3619e4e05202768cc1d729446e--libtiff--4.4.0.arm64_monterey.bottle.tar.gz
==> Reinstalling libtiff
==> Pouring libtiff--4.4.0.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libtiff/4.4.0: 249 files, 4.8MB
==> Running `brew cleanup libtiff`...
==> Downloading https://ghcr.io/v2/homebrew/core/gdal/manifests/3.5.1_1
Already downloaded: /Users/zakjan/Library/Caches/Homebrew/downloads/bed7495f4ddbd69c6f23ce19dee1a2478c9d6945a6f591250b259626a1ac6974--gdal-3.5.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gdal/blobs/sha256:913d17c33289ba2e65b9beaa5c0f00653207881cb6ddbb277f915c9d0aef
Already downloaded: /Users/zakjan/Library/Caches/Homebrew/downloads/29c614ea39165155dbb81736f692b8c4d0062c11984b4cf58c720fd253f98074--gdal--3.5.1_1.arm64_monterey.bottle.tar.gz
==> Reinstalling gdal
==> Pouring gdal--3.5.1_1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/gdal/3.5.1_1: 422 files, 60.9MB
==> Running `brew cleanup gdal`...
```

```
❯ gdal_translate -co COMPRESS=ZSTD test.tif test2.tif
Input file size is 539, 448
Warning 6: 'ZSTD' is an unexpected value for COMPRESS creation option of type string-select.
ERROR 1: Cannot create TIFF file due to missing codec for ZSTD.
```

### What did you expect to happen?

`gdal_translate` should output the converted GeoTIFF file with ZSTD compression

I suppose the issue is that zstd was disabled in https://github.com/Homebrew/homebrew-core/pull/64718, but I'm not sure how to link them together.

### Step-by-step reproduction instructions (by running `brew` commands)

```
brew install gdal
wget https://github.com/EOxServer/autotest/raw/f8d9f4bde6686abbda09c711d4bf5239f5378aa9/autotest/data/meris/MER_FRS_1P_reduced/ENVISAT-MER_FRS_1PNPDE20060816_090929_000001972050_00222_23322_0058_uint16_reduced_compressed.tif -O test.tif
gdal_translate -co COMPRESS=ZSTD test.tif test2.tif
```

### PR DESCRIPTION
**Pull request by Firefishy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Enabled ZSTD support in libtiff to allow usage downstream e.g.: gdal

Fixes: #106450

### CODE REVIEW

**Comment by Firefishy** [comment]
Can I also bump `gdal revision` from this PR? gdal is the main consumer of zstd support via libtiff.

**Comment by carlocab** [comment]
> Can I also bump `gdal revision` from this PR? gdal is the main consumer of zstd support via libtiff.

Does `gdal` need to be rebuilt to take advantage of zstd support in libtiff?

**Comment by Firefishy** [comment]
> > Can I also bump `gdal revision` from this PR? gdal is the main consumer of zstd support via libtiff.
> 
> Does `gdal` need to be rebuilt to take advantage of zstd support in libtiff?

Yes, `gdal` does need a rebuilt to get zstd support.

**Comment by carlocab** [comment]
Ok, sure, go ahead.

**Comment by Firefishy** [comment]
> Ok, sure, go ahead.

Done. Bumped `gdal` revision to enable ZSTD support.

**Comment by carlocab** [comment]
Actually, I'm having second thoughts about the `libtiff` revision bump here. `gdal` is probably ok since we have multiple users interested in the new features.

Thoughts, @Bo98?

**Comment by Firefishy** [comment]
To enabled ZSTD in `gdal` both a rebuild of `libtiff` (with ZSTD support) and `gdal` is needed.

**Comment by carlocab** [comment]
Yes. It is possible to rebuild either (or both) of them without bumping the `revision`. The `revision` change just determines whether we should force everyone to install the newer build with `brew upgrade`.

**Comment by Bo98** [comment]
AFAICT libtiff zstd changes apply to runtime rather than changing API - so it should just work without rebuilding gdal given it should be liked to the shared library?

If I have missed something and it does require a rebuild of gdal then it probably does need revision for both because of new API or whatever.

**Comment by Bo98** [comment]
That's the bundled version of libtiff which we should not be using.

**Comment by Firefishy** [comment]
Unsure what is being asked for me... Should I drop the `revision` bump on both `gdal` and `libtiff` packages? My goal is to get a `ZSTD` build of `gdal`

**Comment by Firefishy** [comment]
I can confirm only a rebuild of `libtiff` is required to enabled `ZSTD` in gdal, aka no rebuild of gdal required. I will rebase PR shortly.

**Comment by Firefishy** [comment]
Rebased and cleaned up.

**Comment by Firefishy** [comment]
Confirmed working for me with `gdal` with ZSTD compression. No rebuild of `gdal` required.

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
@Firefishy could you rebase this PR?

**Review by SMillerDev — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
