### PR TITLE
macvim migrated to cask

### PR DESCRIPTION
**Pull request by AnastasiaSulyagina**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

---

Deleting macvim from homebrew-core as part of deduplication process . See context [here](https://github.com/caskroom/homebrew-cask/issues/15603). 

_Please note that this PR is created to continue case-by-case discussions from thread linked above and if decision is made not to remove the formula, PR will be closed._

### CODE REVIEW

**Comment by tdsmith** [comment]
This will make it harder to obtain macvim built against a non-system Python. macvim has proven to be a troublesome but popular package for us.

**Comment by MikeMcQuaid** [comment]
@tdsmith It's maybe worth us contacting upstream about the desire for this?

**Comment by chdiza** [comment]
Not sure upstream will be sympathetic.  MacVim has never consistently played nice with non-system pythons at any point in its entire existence (2007, IIRC).  If memory serves, this isn't the fault of the upstream devs, either current or former.

**Comment by MikeMcQuaid** [comment]
Passing on this for now but thanks for the PR @AnastasiaSulyagina!

**Pull request closed without merging**
