### PR TITLE
net-snmp 5.9.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
upstream [supports openssl 3 now](https://github.com/net-snmp/net-snmp/commit/f5cc42798c996796ec04e38d67f5589153353bd8)

**Comment by cho-m** [comment]
Looks like `net-snmp` is also in the `curl` tree (ref: #85775), so may be tricky to migrate right now unless we use audit allowlist. Also, may want to first deal with broken `openssl@3` support for older macOS (due to AVX-512) as mentioned in `curl` PR.

**Comment by chenrui333** [comment]
> Looks like `net-snmp` is also in the `curl` dependents and related tree (ref: #85775), so may be tricky to migrate right now unless we use audit allowlist. Also, may want to first deal with broken `openssl@3` support for older macOS (due to AVX-512) as mentioned in `curl` PR.

I see, let me use the openssl@1.1 for now.

**Comment by chenrui333** [comment]
#105934

**Pull request closed without merging**
