### PR TITLE
chapel 1.33

### PR DESCRIPTION
**Pull request by tzinsky**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by tzinsky** [comment]
Not sure how to diagnose this failure:   

`Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
`
Any assistance folks can offer would be appreciated.

**Comment by tzinsky** [comment]
Ah, I understand and we have to pin to these versions because we are not ready to move to the most recent version of llvm at this time.   There are code changes to move to that version that prevent us from making that change today. Any chance we can just restart the CI?

**Comment by krehel** [comment]
Running again - issue affected several PR's so we're queueing.

**Comment by tzinsky** [comment]
Yes, we can work with Python 3.12.   If necessary, I can close this PR and resubmit with that change.

**Comment by krehel** [comment]
@tzinsky - feel free to open another PR with `python@3.12` to see if it builds.  We can replace this PR with that new one if needed.

**Comment by tzinsky** [comment]
Follow up PR in the queue:   https://github.com/Homebrew/homebrew-core/pull/157408.   Let me know if I need to change something and I will be monitoring the CI.

**Comment by tzinsky** [comment]
The other PR failed with a number errors.   I would like to merge this one and we can work on resolving those issues.

**Review by krehel — APPROVED** [review]

**Pull request merged**
