### PR TITLE
contentful-cli 1.8.20

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
> ==> FAILED
> contentful-cli:
>   * Binaries built for a non-native architecture were installed into contentful-cli's prefix.
      The offending files are:
        /opt/homebrew/Cellar/contentful-cli/1.8.20/libexec/lib/node_modules/contentful-cli/node_modules/fsevents/fsevents.node
> Error: 1 problem in 1 formula detected

**Comment by carlocab** [comment]
`contentful-cli` probably installs pre-built binaries. @danielnachun, you seem to know about this sort of thing -- any ideas here?

`fsevents` is supposed to support M1 in v2.3 (see Changelog [here](https://www.npmjs.com/package/fsevents)), so I'm guessing `contentful-cli` depends on a version older than that.

**Comment by carlocab** [comment]
Or, we could just get rid of the parts we don't need with something like
```ruby
diff --git a/Formula/contentful-cli.rb b/Formula/contentful-cli.rb
index fb0c6f4762..8d1d99215e 100644
--- a/Formula/contentful-cli.rb
+++ b/Formula/contentful-cli.rb
@@ -21,6 +21,13 @@ class ContentfulCli < Formula
   def install
     system "npm", "install", *Language::Node.std_npm_install_args(libexec)
     bin.install_symlink Dir["#{libexec}/bin/*"]
+
+    on_macos do
+      fat_file = libexec/"lib/node_modules/contentful_cli/node_modules/fsevents/fsevents.node"
+      macho = MachO::FatFile.new(fat_file)
+      native_slice = macho.extract(Hardware::CPU.arch)
+      native_slice.write fat_file
+    end
   end
 
   test do
```
Not necessarily saying we should... but it's an option.

**Comment by carlocab** [comment]
If #81591 is merged as-is you can rebase this to fix the audit error.

**Review by carlocab — APPROVED** [review]

**Comment by Gmail38** [comment]
Every body happy !!!! Victoria i know u are.

**Pull request closed without merging**
