### PR TITLE
node 12.6.0

### PR DESCRIPTION
**Pull request by metowolf**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chrmoritz** [comment]
The `react-native-cli` error is caused by the recent release of `react-native` 0.60.0 and unrelated to this `node` upgrade here (it's failing with the current version of `node` too).

The `react-native-cli` test is currently set up to always initialize the project with the latest version of `react-native` (which points to 0.60.0 since yesterday). It will pass if you change it to explicitly initialize the project with the 0.59.x `react-native` release line. However I'm still not sure what's broken with 0.60.0 atm, as this is quite a big project and the error isn't really helpful.

```diff
diff --git a/Formula/react-native-cli.rb b/Formula/react-native-cli.rb
index 5a00ae9c14..b4154317e5 100644
--- a/Formula/react-native-cli.rb
+++ b/Formula/react-native-cli.rb
@@ -21,7 +21,7 @@ class ReactNativeCli < Formula
   end
 
   test do
-    output = shell_output("#{bin}/react-native init test")
+    output = shell_output("#{bin}/react-native init test --version=react-native@0.59.x")
     assert_match "Run instructions for Android", output
   end
 end
```

**Comment by chrmoritz** [comment]
The `react-native-cli` test failure should be fixed now. Refs: #41651

**Comment by diabloevagto** [comment]
@fxcoudert hi, is ready merged ?

**Comment by jonchang** [comment]
@brewtestbot test this please

**Comment by jonchang** [comment]
rebased on master

**Pull request closed without merging**
