### PR TITLE
vtk 9.0.1

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Previous work was done here: https://github.com/Homebrew/homebrew-core/pull/58621

### CODE REVIEW

**Comment by dtrodrigues** [comment]
gdcm build failure reported upstream: https://sourceforge.net/p/gdcm/bugs/509/

**Comment by dtrodrigues** [comment]
pcl does not yet support vtk 9. Current progress here: https://github.com/PointCloudLibrary/pcl/pull/4262

**Comment by SMillerDev** [comment]
Maybe we can make an vtk@8 formula for those 2 formula and deprecate it right away?

**Comment by dtrodrigues** [comment]
In summary:
* `opencv` needed a small patch for vtk 9 which has been merged: https://github.com/opencv/opencv_contrib/pull/2659
* `vtk@8.2` was created in a deprecated state for the following three formulae
  * `pcl`: actively working on supporting vtk 9
  * `gdcm`: has a recently open issue about vtk 9 support 
  * `itk`: looks like it builds with vtk 9 without `gdcm`, but since it's configured to use `gdcm`, it needs `vtk@8.2`

`pcl` uses HomeBrew in their CI, so getting this merged will facilitate support for them to upgrade.

**Comment by SMillerDev** [comment]
For itk I'd say we drop gdcm support then.

**Comment by dtrodrigues** [comment]
Removed `-DModule_ITKLevelSetsv4Visualization=ON` from `itk` per https://github.com/InsightSoftwareConsortium/ITK/issues/739#issuecomment-493600572 and trying it without `gdcm`.

**Comment by dtrodrigues** [comment]
Looks like if you don't tell itk to use the system gdcm, itk will build gdcm and openjpeg from its ThirdParty directory and then will try and install the openjpen pkg-config file, which conflicts with the openjpeg Homebrew formula which is also being installed. I've put the itk dependency on vtk@8.2 back in and gdcm back in.

**Review by SMillerDev — APPROVED** [review]
Thanks @dtrodrigues  ! Without your contributions it'd be impossible to keep homebrew going. You can feel good knowing that you've made the world a lot better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
