### PR TITLE
node 7.7.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 any idea what's going on here?

**Comment by DomT4** [comment]
```
In file included from ../node_modules/nan/nan.h:47:
/Users/xyz/.node-gyp/7.7.0/include/node/node.h:44:10: fatal error: 'tracing/trace_event.h' file not found
#include "tracing/trace_event.h"
         ^
1 error generated.
make: *** [Release/obj.target/bignum/bignum.o] Error 1
gyp ERR! build error
```

https://github.com/nodejs/node/issues/11628

**Comment by ilovezfs** [comment]
Thanks @DomT4 ... it's vaguely disturbing our CI caught this and theirs, not so much.

**Comment by DomT4** [comment]
I presume there will be a new release cut very soon at least. This will be quite the unpleasant surprise to anyone who automatically goes _"Ooh new `node` release, let's update"_ and then tries to install anything that uses `node-gyp` 😕.

**Comment by JCount** [comment]
pending PR with cherry-picked fix, slated for a quick 7.7.1 release: https://github.com/nodejs/node/pull/11634

**Comment by ilovezfs** [comment]
At least someone is asking the "right" question: https://github.com/nodejs/node/pull/11634#issuecomment-283361266

**Comment by DomT4** [comment]
Heads up when there is a new release cut the `test do` block could do with tweaking as well. Nobody is currently running that full localisation test because the `"full-icu"` option no longer exists.

**Comment by JCount** [comment]
superseded by https://github.com/Homebrew/homebrew-core/pull/10497

**Pull request closed without merging**
