### PR TITLE
libcouchbase: update 2.7.7 formula

### PR DESCRIPTION
**Pull request by avsej**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
This duplicates https://github.com/Homebrew/homebrew-core/pull/16909 but I will close mine :)

**Comment by avsej** [comment]
Thanks

**Comment by avsej** [comment]
actually #16909 created two seconds later than this one, at least github says so. And why your script does not create PR once I publish new version on the URL, but rather when I prepare change for PR in my fork?
It does not make sense as I pushing changes into fork only to create this pull request, and the PR template requires me to check 4 checkboxes before pushing "Create pull request", does you script skip all these steps? It should either automate the job completely without me pushing new changes into fork at all, or do not try to create duplicates.

**Comment by ilovezfs** [comment]
I detected there was a new tag, and opened the pull request with bump-formula-pr, which does check for duplicates. There's no connection between that and your having pushed to a branch.

**Comment by avsej** [comment]
okay. but here in formula it does not use tags, why github tags trigger your script?

**Comment by ilovezfs** [comment]
>okay. but here in formula it does not use tags, why github tags trigger your script?

Because there's no custom livecheck for the formula (https://github.com/Homebrew/homebrew-livecheck/tree/master/Livecheckables), so it falls back to using the head spec
```
  head "https://github.com/couchbase/libcouchbase.git"
```
to detect tags.

**Comment by avsej** [comment]
ok in this case I will stop opening PRs here, and hope that this script will pick up the tags

**Comment by ilovezfs** [comment]
@avsej Note that some upstreams have fully automated their use of `brew bump-formula-pr` as part of their release process.

For example
`flow`'s `flow-bot` (see https://github.com/Homebrew/homebrew-core/pull/16330)

`yarn`'s `DanBuild` (see https://github.com/Homebrew/homebrew-core/pull/15173)

**Comment by ilovezfs** [comment]
@avsej Thanks for the upgrade! Shipped. :rocket:

**Comment by avsej** [comment]
@ilovezfs, you script didn't open PR for libcouchbase 2.8.0. It seems like capable to open duplicates when I do it manually :)

**Comment by ilovezfs** [comment]
The script isn't running in a permanent loop, nor does it open the PRs itself.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/17455 :tada:

**Pull request closed without merging**
