### PR TITLE
a*: Fix `Homebrew/NoFileutilsRmrf` RuboCop offenses

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- Part of https://github.com/Homebrew/brew/pull/17705.
- Different approach from the previous massive PR - I'm splitting them up per-alphabet letter (ish) and letting CI do the full "no bottles" build. This is `a*`.

### CODE REVIEW

**Comment by p-linnane** [comment]
`apache-archiva` link can be updated to https://www.apache.org/dist/archiva/2.2.10/binaries/apache-archiva-2.2.10-bin.zip.

**Comment by issyl0** [comment]
> `apache-archiva` link can be updated to https://www.apache.org/dist/archiva/2.2.10/binaries/apache-archiva-2.2.10-bin.zip.

`FormulaAudit/Urls` doesn't like this, so I've kept it as is and it's continually failing to download.

**Comment by p-linnane** [comment]
> `FormulaAudit/Urls` doesn't like this, so I've kept it as is and it's continually failing to download. Maybe the URL audit should skip deprecated formulae?

Yeah the original link is just a redirect to Apache's deprecation page now. Thoughts on skipping URL audits for deprecated/disabled formula @Homebrew/core?

**Comment by Bo98** [comment]
That actually looks like a brew bug really. The mirror works fine but it's clearly not detecting it properly.

**Comment by Bo98** [comment]
https://github.com/Homebrew/brew/pull/17829

**Comment by issyl0** [comment]
Thanks, Bo!

**Comment by issyl0** [comment]
I [split `apt-dater` into its own PR](https://github.com/Homebrew/homebrew-core/pull/178318) because the build failures were unrelated, and the debug files we were trying to remove in `arrayfire` are no longer included. Hopefully this goes green now. 🤞🏻

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
