### PR TITLE
scala@2.11 2.11.11

### PR DESCRIPTION
**Pull request by qayshp**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by qayshp** [comment]
Tried using ```brew bump-formula-pr --strict scala@2.11 --url=https://downloads.lightbend.com/scala/2.11.11/scala-2.11.11.tgz --sha256=12037ca64c68468e717e950f47fc77d5ceae5e74e3bdca56f6d02fd5bfd6900b --revision=2```
Will update the PR with manual changes too.

**Comment by qayshp** [comment]
The commit has been amended to update all URLs for mirrors, sources, and docs.
The only thing I wasn't sure about was if I should leave in the ```revision``` and increment the number.
I was looking at http://www.rubydoc.info/github/Homebrew/brew/master/Formula.revision= but didn't think it applied in this case.

**Comment by fxcoudert** [comment]
You did right, revisions are for changes in the formula's install or content when the version number hasn't changed.

**Comment by fxcoudert** [comment]
Thanks @qayshp for the pull request!

**Pull request closed without merging**
