### PR TITLE
semgrep 0.31.1

### PR DESCRIPTION
**Pull request by brendongo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by brendongo** [comment]
Hmm I used the github UI to resolve the conflict but looks like it does a merge of master. Is this ok?

**Comment by jonchang** [comment]
> Hmm I used the github UI to resolve the conflict but looks like it does a merge of master. Is this ok?

Our tools currently can't deal with merge commits. I've rebased this manually for you.

**Comment by Rylan12** [comment]
Yeah, merges don't work well with our autosquash/merge process. I fixed it up and rebased so once CI runs this should be 👍

**Comment by Rylan12** [comment]
Ah, oops, hope I didn't overwrite anything @jonchang

**Comment by jonchang** [comment]
Our simultaneous force pushes collided with each other 🚥

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Thanks, @brendongo!

**Pull request closed without merging**
