### PR TITLE
graphviz 10.0.1

### PR DESCRIPTION
**Pull request by ik11235**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
we cannot patch the jar 😅  (need a upstream release for the graphviz version check)

**Comment by chenrui333** [comment]
- waiting for a new release of `plantuml/`

**Comment by chenrui333** [comment]
rebased per https://github.com/Homebrew/homebrew-core/pull/162896 merge

**Comment by chenrui333** [comment]
plantuml 1.2024.3 works fine with graphviz 10.0.1 in my local.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
