### PR TITLE
vale 2.0.0

### PR DESCRIPTION
**Pull request by infotexture**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by zbeekman — APPROVED** [review]
LGTM

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you @infotexture!

**Comment by infotexture** [comment]
@zbeekman Thanks for merging. The bottle checks passed, so based on the [bottle creation info in the docs](https://docs.brew.sh/Bottles#creation), I was operating on the assumption that bottle SHAs would be updated automatically:

> Bottles are created using the [Brew Test Bot](https://docs.brew.sh/Brew-Test-Bot). This happens mostly when people submit pull requests to Homebrew and the `bottle do` block is updated by maintainers when they `brew pull --bottle` the contents of a pull request. 

I don't see those changes reflected in e590f45.

Is a separate step necessary? 🤔

**Comment by ChrisChinchilla** [comment]
Ah right thanks @infotexture had no idea it had been released officially. We should script this 🤔

**Comment by issyl0** [comment]
@ChrisChinchilla There's https://github.com/mislav/bump-homebrew-formula-action that can automate this process based on when it detects releases on GitHub.

**Pull request closed without merging**
