### PR TITLE
mesos: fixed binary path used in test.

### PR DESCRIPTION
**Pull request by bbannier**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Stupid question: why didn't this fail before?

**Comment by bbannier** [comment]
@ilovezfs: The test I added did work on my machine since the path existed there, but I am pretty sure it didn't run in your CI since even the existing test fails.

**Comment by ilovezfs** [comment]
which is what is strange since CI always runs the test block ...

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
