### PR TITLE
wellington 1.0.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> godep restore
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /private/tmp/wellington-20160923-21358-1ng0kxh/wellington-1.0.3
godep: [WARNING]:	$GOPATH: /private/tmp/wellington-20160923-21358-1ng0kxh/wellington-1.0.3
godep: Dep (github.com/fatih/color) restored, but was unable to load it with error:
	Package (fmt) not found
godep: Dep (github.com/fsnotify/fsevents) restored, but was unable to load it with error:
	Package (runtime/cgo) not found
godep: Dep (github.com/inconshreveable/mousetrap) restored, but was unable to load it with error:
	Package (os) not found
godep: Dep (github.com/mattn/go-colorable) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Dep (github.com/mattn/go-isatty) restored, but was unable to load it with error:
	Package (syscall) not found
godep: Dep (github.com/spf13/cobra) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Dep (github.com/spf13/pflag) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Dep (github.com/wellington/go-libsass) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Dep (github.com/wellington/spritewell) restored, but was unable to load it with error:
	Package (bufio) not found
godep: Dep (golang.org/x/net/context) restored, but was unable to load it with error:
	Package (errors) not found
godep: Dep (gopkg.in/fsnotify.v1) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Error checking some deps.
```

**Comment by drewwells** [comment]
appears godep no longer works properly in homebrew. Fortunately, wellington doesn't require godeps any longer. I'll submit a PR to fix

**Comment by drewwells** [comment]
I took the opportunity to update to new patterns found in other Go projects, so the PR was a bit more work than expected: https://github.com/Homebrew/homebrew-core/pull/5226

**Comment by ilovezfs** [comment]
>appears godep no longer works properly in homebrew.

godep works fine in Homebrew. The above post was just a note to myself to switch the formula over to this pattern: https://github.com/Homebrew/homebrew-core/blob/master/Formula/the_platinum_searcher.rb#L20-L27

If you're going to redo the vendoring approach, please make sure it does not require any `go_resource` blocks if at all possible.

**Pull request closed without merging**
