### PR TITLE
dbhash, sqldiff, sqlite-analyzer, sqlite 3.40.0

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
tracker formula test failure on all osx

sqlite build issue on linux

```
  ==> make install
  tclsh /tmp/sqlite-20221116-4041-g4v3jn/sqlite-src-3400000/tool/mkshellc.tcl >shell.c
  /bin/sh: 1: tclsh: not found
  make: *** [Makefile:1128: shell.c] Error 127
```

**Comment by chenrui333** [comment]
only tracker formula failed on the regression tests.

**Comment by chenrui333** [comment]
For tracker regression test failure, https://gitlab.gnome.org/GNOME/tracker/-/issues/387

**Comment by chenrui333** [comment]
Log a separate new ticket for the issue, https://gitlab.gnome.org/GNOME/tracker/-/issues/388

**Comment by chenrui333** [comment]
While this is being investigated in the upstream, I think we can merge the PR?

**Comment by p-linnane** [comment]
@chenrui333 Works for me. Based off the response on the issue you opened, they are pointing to SQLite instead.

**Comment by chenrui333** [comment]
I am gonna merge this for now, and handle tracker formulae separately.

**Review by chenrui333 — APPROVED** [review]

**Comment by Bo98** [comment]
> Error: 4 failed steps!
> brew deps --tree --annotate --include-build --include-test sqlite
> brew deps --tree --annotate --include-build --include-test dbhash
> brew deps --tree --annotate --include-build --include-test sqldiff
> brew deps --tree --annotate --include-build --include-test sqlite-analyzer

This was a genuine problem and should not have been ignored as it broke Homebrew on older Linux.

(In terms of Tracker: I'm a little concerned we've merged something with a potential regressions given Tracker team have told us it's a SQLite problem, but I've not looked into it so I'm not too conerned about that part.)

**Comment by chenrui333** [comment]
tclsh issue is back again on 3.40.1 linux build
```
  tclsh /tmp/sqlite-20221228-31551-1alhvzj/sqlite-src-3400100/tool/mkshellc.tcl >shell.c
  /bin/sh: 1: tclsh: not found
```

**Pull request closed without merging**
