### PR TITLE
tomee-webprofile 1.7.5

### PR DESCRIPTION
**Pull request by gtmgianni**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by gtmgianni** [comment]
Apologies if I've not updated this formula correctly – this is my first pull request on this repository.

**Comment by fxcoudert** [comment]
```
==> /usr/local/opt/tomee-webprofile/libexec/bin/configtest.sh
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
-Djava.endorsed.dirs=/usr/local/opt/tomee-webprofile/libexec/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Configuration error detected!
Error: tomee-webprofile: failed
```

**Comment by ilovezfs** [comment]
Same as the failure already noted in https://github.com/Homebrew/homebrew-core/issues/19696. This probably needs a Java 8 wrapper.

**Comment by ilovezfs** [comment]
@gtm87x Since this doesn't work with Java 9, please report it upstream, so they can fix it (and we can ship new versions). If you can figure out how to get it working in a mixed Java 8 and Java 9 environment (like our CI) with wrapper scripts, we'd be happy to take a look at a PR for that.

Thanks for the PR nonetheless!

**Pull request closed without merging**
