### PR TITLE
gifski 0.3.0 (new formula)

### PR DESCRIPTION
**Pull request by danielbayley**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
Sorry, but we can't merge this into homebrew-core, per our notability tests:

```
gifski:
  * GitHub repository too new (<30 days old)
```

If you'd still like to install it via brew, I suggest setting up a [custom tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by pornel** [comment]
Suggestions for the formula:

* test with at least 2 png files (1 file will be interpreted as a video and give an error)

* consider compiling with `CC=gcc-7 cargo build --release --features=openmp`. With OpenMP it's 50% faster (but needs gcc, because OpenMP doesn't work with Xcode's clang).

**Comment by danielbayley** [comment]
@pornel I've checked _Allow edits from maintainers_ so someone wants to pick this up…

**Comment by danielbayley** [comment]
@woodruffw Reopen?

**Comment by woodruffw** [comment]
@danielbayley Reopened!

Looks like `gifski` is currently on `0.6.2`.

**Comment by danielbayley** [comment]
@woodruffw Updated. @pornel Want to chip in?

**Comment by pornel** [comment]
The test is invalid, as per my previous comment

**Review by ilovezfs — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @danielbayley for your contribution to Homebrew! 🎊

**Comment by danielbayley** [comment]
@fxcoudert Ah cool, you beat me to it! No worries.

**Pull request closed without merging**
