### PR TITLE
nushell: enable extra features

### PR DESCRIPTION
**Pull request by jakevossen5**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Based off this discussion: https://github.com/nushell/nushell/issues/3362

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Thanks, @jakevossen5.

Please bump the `revision` (either add `revision 1` or increment the `revision` right after `license`) so that users get the updated version of the formula when they do `brew upgrade`.

**Comment by jakevossen5** [comment]
Thanks, just added that

**Comment by carlocab** [comment]
Squashed your commits together for you; we try to keep things to one-commit-per-formula in a PR.

**Review by nandahkrishna — APPROVED** [review]
Thanks, @jakevossen5!

**Pull request closed without merging**
