### PR TITLE
maven 3.6.0

### PR DESCRIPTION
**Pull request by mfriedenhagen**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
- _“Apache Maven 3.5.4 is the latest release and recommended version for all users”_
- We already have many versioned maven formulas, if we add one we need to remove another. 
- Also, the criteria for versioned formulas include the requirement that the version still be maintained. I am not sure why we carry maven 3.0, 3.1, and 3.2 when these versioned have been unmaintained for 3 to 4 years.

**Comment by mfriedenhagen** [comment]
Hi @fxcoudert, thanks for the fast feedback.
* The vote for 3.6.0 passed yesterday https://mail-archives.apache.org/mod_mbox/maven-dev/201810.mbox/%3C9d133c74-99b0-a1a3-895b-6229ac53a60f%40gmx.de%3E but I agree that the web page seems not to be up to date.
* If I understand you correctly you want me to remove old versions with the this PR as well? Or would a new PR be more feasible?
* I will dig through the dev mailing list and look the EOL.

**Comment by fxcoudert** [comment]
For now I welcome more information… we'll decide based on that. A separate PR would then be a possibility.

**Comment by mfriedenhagen** [comment]
@fxcoudert https://maven.apache.org/download.cgi now shows 3.6. After a discussion at the dev-list I added a commit which removes 3.0 and 3.1, as these are not tested anymore with plugin updates.

**Comment by mfriedenhagen** [comment]
I just did a rebase on the master, hopefully this helps.

**Pull request merged**
