### PR TITLE
Sqlite-family 3.19.2

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Another day, another release.

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
@DomT4:  You'd _think_ they'd slow down a bit, wouldn't you?

**Comment by ilovezfs** [comment]
This is turning into Whac-A-Mole.

Thanks, Dom

**Comment by DomT4** [comment]
`sqlite` is usually pretty good at getting semi-major bumps out the door without issue, but this one has been a bit rocky.

> You'd think they'd slow down a bit

Hopefully this was the last imminent bug fix release 😅.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  

> This is turning into Whac-A-Mole.
>
> …

Sure _feels_ like it!  :laughing:

<hr />

@DomT4:  

> …
>
> Hopefully this was the last bug fix release for at least this week 😅.

Oh, _that's_ for sure.  _Then_ we can all _relax_, at least in regard to _SQLite_ and company.

**Pull request closed without merging**
