### PR TITLE
node 9.2.0 (devel)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

npm 5.6.0 (pre-release)

CC @DomT4 @chrmoritz

### CODE REVIEW

**Comment by chrmoritz** [comment]
Should we apply metadata compatibility patches (to minizlib) for devel/HEAD to ensure, that a downgrade of npm to the latest stable version on npm doesn't break it for devel/HEAD or are we fine here with having this issue?

**Comment by DomT4** [comment]
The position generally on `devel` and `HEAD` is that if you broke it, you should know how to fix it, otherwise stick to `stable`.

**Comment by ilovezfs** [comment]
I think
```
brew postinstall --devel node
```
will fix that, right?

**Comment by chrmoritz** [comment]
Yeah, `brew postinstall --devel node` will always work.

What I meant was basically a backwards version of #20431: Faking `minizlib@1.0.4` in npm 5.6.0 to think that it is `minizlib@1.0.3`, so that it is reused instead of replaced with the real broken `minizlib@1.0.3` version of a npm downgrade to the stable v5.5.1.

**Comment by ilovezfs** [comment]
I think we can avoid that for the time being, but can reconsider if it becomes a problem.

**Comment by ilovezfs** [comment]
shipped.

**Comment by chrmoritz** [comment]
Here is the patch, that would add compatibility for downgrading npm to the latest stable version (v5.5.1) without breaking it: https://gist.github.com/chrmoritz/965365c1fbcab38720f004fa40b30a84

**Pull request merged**
