### PR TITLE
broot 1.2.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
error[E0658]: use of unstable library feature 'clamp'
  --> src/app/context.rs:98:14
   |
98 |             .clamp(2, 100);
   |              ^^^^^
   |
   = note: see issue #44095 <https://github.com/rust-lang/rust/issues/44095> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `broot`
```

**Comment by carlocab** [comment]
Title is 1.2.7, but the formula and commit is still 1.2.6?

**Review by carlocab — APPROVED** [review]

**Comment by chenrui333** [comment]
@carlocab I missed the 1.2.7 commit.  :(

**Comment by chenrui333** [comment]
created a new one, #72511

**Pull request closed without merging**
