### PR TITLE
sbcl 1.3.16

### PR DESCRIPTION
**Pull request by jinwoo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Are all of the patches actually still needed?

CC @dunn

**Comment by jinwoo** [comment]
Looks like some patches don't work well anymore. Someone more familiar with those patches should probably take a look.

**Comment by jinwoo** [comment]
One of the patches doesn't seem needed anymore.
#-(and darwin x86) was added at line 541 in the latest upstream change: https://github.com/sbcl/sbcl/commit/1e956ac379050bf4e5227bb4dc48af4b875d56da#diff-e5dc8a0000a866c05787756a8997187c

A new commit was added.

**Comment by jinwoo** [comment]
Build failed. I don't have time to look into the details now. Abandoning this PR.

**Comment by dunn** [comment]
I'll take a look.  It works locally, so maybe something needs to be configured on Jenkins: `Error opening /dev/tty: Device not configured`

**Comment by ilovezfs** [comment]
thanks Alex

**Comment by jinwoo** [comment]
Thanks, Alex.

**Pull request closed without merging**
