### PR TITLE
Bulk import from homebrew/versions (4/7)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Import formulae from homebrew/versions. Those that fail to build will likely be killed.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@dunn Could do with a hand with the `ledger@2.6` emacs audit failure if you get a chance 🙇‍♀️

**Comment by dunn** [comment]
What's the failure? On Jenkins I'm just seeing one of the 
```
FATAL: Could not checkout 6212415202a9480f294e0ae72601e9f965437bd8
hudson.plugins.git.GitException: Could not checkout 6212415202a9480f294e0ae72601e9f965437bd8
```

**Comment by ilovezfs** [comment]
@dunn https://bot.brew.sh/job/Homebrew%20Core/17905/version=sierra/console

**Comment by dunn** [comment]
`--with-lispdir=#{elisp}`

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
One question: should we import `imagemagick@6.9` given we already have `imagemagick@6.rb`?

Some of the software doesn't download anymore:

```
imagemagick@6.9:
  * Stable: The URL https://www.imagemagick.org/download/ImageMagick-6.9.8-1.tar.xz is not reachable (HTTP status code 404)
  * Stable resource "monolite": The URL http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz is not reachable
Download failed: http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz
```

which means that `mono@3` does not build and should be removed.

Other issues:

```
imagemagick@6.5:
  * A `test do` test block should be added
libpqxx@3:
  * A `test do` test block should be added
maven@3.1:
  * A `test do` test block should be added
  * Non-executables were installed to "/usr/local/opt/maven@3.1/bin"
    The offending files are:
      /usr/local/opt/maven@3.1/bin/m2.conf
```

**Comment by MikeMcQuaid** [comment]
Let's hold off merging this until we have a new tag with https://github.com/Homebrew/brew/pull/1732.

> One question: should we import imagemagick@6.9 given we already have imagemagick@6.rb?

Probably not. 6.5's argument was it's the last version that works with Ruby 1.8 I believe.

> which means that mono@3 does not build and should be removed.

It's maybe fixable but: I agree, let's kill it.

> Other issues:

Will take a look, thanks.

**Comment by MikeMcQuaid** [comment]
> One question: should we import imagemagick@6.9 given we already have imagemagick@6.rb?

It was actually a rename from `imagemagick@6`

**Pull request closed without merging**
