### PR TITLE
openjdk 14.0.2

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
See #57222 for expected failures

**Comment by SMillerDev** [comment]
hbase PR in: https://github.com/Homebrew/homebrew-core/pull/58150

link-grammar could be moved to: https://github.com/opencog/link-grammar

**Comment by Fudoshiki** [comment]
merge?

**Comment by SMillerDev** [comment]
There's CI failures so those need to be resolved first. Feel free to make pull requests for the formulae that fail

**Comment by montogeek** [comment]
This will fix this error when running `brew install elixir` ?
```
==> Installing dependencies for elixir: openjdk, fop, libtool, jpeg, libtiff, wxmac and erlang
==> Installing elixir dependency: openjdk
==> ./configure --without-version-pre --without-version-opt --with-version-build=14.0.1 --with-toolchain-path=/usr/bin --with-extra-ldflags=-headerpad_max_install_names --with-boot-jdk=/private/
==> make images
Last 15 lines from /Users/montogeek/Library/Logs/Homebrew/openjdk/02.make:
             ^
/private/tmp/openjdk-20200803-47717-rf7rl1/jdk14u-jdk-14.0.1-ga/src/hotspot/share/runtime/sharedRuntime.cpp:2875:85: note: place parentheses around the 'sizeof(relocInfo)' expression to silence this warning
      buffer.insts()->initialize_shared_locs((relocInfo*)locs_buf, sizeof(locs_buf) / sizeof(relocInfo));
                                                                                    ^
1 error generated.

* All command lines available in /private/tmp/openjdk-20200803-47717-rf7rl1/jdk14u-jdk-14.0.1-ga/build/macosx-x86_64-server-release/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

make[1]: *** [main] Error 2
make: *** [images] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
openjdk 14.0.2 https://github.com/Homebrew/homebrew-core/pull/58134
openjdk 14.0 upgrade failures https://github.com/Homebrew/homebrew-core/issues/57222

Error: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.
```

**Comment by SMillerDev** [comment]
No, I think running a non-beta os would be the only solution there.

**Comment by montogeek** [comment]
@SMillerDev Thanks for the information

**Comment by SMillerDev** [comment]
Currently failing formula:
- [x] mgba - Should be fixed with a rebase
- [ ] astrometry-net
- [ ] cbmc
- [ ] gammaray
- [ ] mesos
- [ ] minidlna
- [ ] pax-construct
- [ ] root
- [ ] link-grammar

**Comment by SMillerDev** [comment]
I can't figure out the issues and I'm just going to merge this since the dependent bottles still seem to work. @jonchang since you did the initial openjdk 14 work, maybe you have some ideas?

**Comment by asbjornu** [comment]
Was this actually merged, @SMillerDev? Seems like version `14.0.1` is still the version available in `master`?

https://github.com/Homebrew/homebrew-core/blob/9e6eaa2ea0be2a9e704a179643721e78804e4c35/Formula/openjdk.rb#L4

**Comment by SMillerDev** [comment]
Nope, took me too much time to finish

**Pull request closed without merging**
