### PR TITLE
telnet(d) 69

### PR DESCRIPTION
**Pull request by SMillerDev**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
  ==> make -C telnetd.tproj OBJROOT=build/Intermediates SYMROOT=build/Products DSTROOT=build/Archive CC=clang CFLAGS=$(CC_Flags) -isystembuild/Products/ LDFLAGS=$(LD_Flags) -Lbuild/Products/ RC_ARCHS=arm64
  make: *** No targets specified and no makefile found.  Stop.
```

I guess no more Make builds.

**Comment by SMillerDev** [comment]
Can't review it but looks great! Thanks for the help @alebcay

**Review by chenrui333 — APPROVED** [review]
LGTM

**Comment by chenrui333** [comment]
💯

**Pull request merged**
