### PR TITLE
sile 0.9.5.1

### PR DESCRIPTION
**Pull request by simoncozens**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by simoncozens** [comment]
This is showing broken symlinks with libfuseprivate. I can't see how this relates to SILE or its dependencies. I'm guessing this is just a SNAFU with the CI build process, but let me know if not and I will investigate further.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by alerque** [comment]
Should this be bumped straight to 0.9.5.1?

**Comment by Moisan** [comment]
Thank you @simoncozens !

**Pull request closed without merging**
