### PR TITLE
sbt 1.3.13

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - lib
```

**Comment by SethTisue** [comment]
cc @eed3si9n

**Comment by eed3si9n** [comment]
> did something change in 1.3.13?

Yes. There is no `lib/` directory in the tar ball for 1.3.13.

I stopped including preloaded local repo (all the JAR files used by sbt) in sbt 1.3.13 because I found that it's currently incomplete and it's not possible to satisfy both Apache Ivy and Coursier.

**Comment by SeekingMeaning** [comment]
This can be closed, thanks for your help everyone 🎉

**Pull request closed without merging**
