### PR TITLE
nss 3.60

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
The failures are simply:
```
brew fetch --retry diff-pdf
brew fetch --retry mapnik
```

**Comment by chenrui333** [comment]
Not sure about the context, but diff-pdf is related to [this commit](6474b708f48902e5ab23885b22b0acd9328d8d83), and mapnik is related to [this commit](98a3aaa2e383c334c4be424f54fdce70b173a1ec)

**Comment by chenrui333** [comment]
maybe revision bump again to fix the missing bottles issue?

**Comment by miccal** [comment]
@chenrui333 the revision bumps are being handles in https://github.com/Homebrew/homebrew-core/pull/66830 and https://github.com/Homebrew/homebrew-core/pull/66369.

**Pull request closed without merging**
