### PR TITLE
ffmpeg 3.3.2

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
vcs randomly failing again. Probably ignorable, or we can requeue it.

**Comment by ilovezfs** [comment]
I guess it needs a new test that doesn't randomly break.

**Comment by ilovezfs** [comment]
Looks like it failed again ... hmmmm

**Comment by zmwangx** [comment]
Maybe it doesn't like the video, or maybe it doesn't like the interval. Anyway, let's see what happens with an updated video and another way to specify the frame interval.

**Comment by ilovezfs** [comment]
It's strange since it doesn't seem to be reproducible locally.

**Comment by zmwangx** [comment]
Yeah.

**Comment by ilovezfs** [comment]
@zmwangx worth noting:
https://github.com/Homebrew/brew/issues/2742
https://github.com/Homebrew/brew/pull/2714

**Comment by zmwangx** [comment]
Not a tty problem can (almost) always be solved with a pty.

**Comment by ilovezfs** [comment]
>Not a tty problem can (almost) always be solved with a pty.

I'm not sure I understand that sentence

**Comment by ilovezfs** [comment]
Two :green_apple:s in a row so I think it's fixed.

**Comment by zmwangx** [comment]
#2742's issue is "stty: stdin isn't a terminal". Putting the process in a pty should almost certainly resolve that issue.

PR is 🍏 now. Not sure whether it's an accident.

**Comment by ilovezfs** [comment]
:movie_camera:

**Comment by ilovezfs** [comment]
@zmwangx mind taking a look at https://github.com/Homebrew/brew/pull/2745 ?

**Comment by zmwangx** [comment]
Re my previous comment:

> #2742's issue is "stty: stdin isn't a terminal". Putting the process in a pty should almost certainly resolve that issue.

Never mind, I thought #2742 was about some test failing, but it was actually unsuppressed messages on stderr from brew itself. #2745 LGTM, except the tput invocation alone might be sufficient, but trying stty first doesn't hurt.

**Comment by ilovezfs** [comment]
Cool. (BTW just writing `#2742` and `#2745` is linking to the wrong repository)

**Comment by zmwangx** [comment]
Yeah I always forget there are two repos. Good old days of Homebrew/homebrew...

Btw, looking more closely, the failure in https://github.com/Homebrew/brew/issues/2742 appears to be totally unrelated to stty lol... Those are just harmless messages. Their own build was failing.

**Comment by ilovezfs** [comment]
>Btw, looking more closely, the failure in Homebrew/brew#2742 appears to be totally unrelated to stty lol... Those are just harmless messages. Their own build was failing.

Shocking.

**Comment by ilovezfs** [comment]
@zmwangx OK I figured out was causing the original vcs test to fail. It fails if mplayer is installed, and passes if mplayer is not installed (or is unlinked).

**Comment by zmwangx** [comment]
@ilovezfs I still can't reproduce:

```
$ ls -l /usr/local/bin/vcs /usr/local/bin/mplayer
lrwxr-xr-x 1 zmwang admin 35 Jun  7 12:15 /usr/local/bin/mplayer -> ../Cellar/mplayer/1.3.0/bin/mplayer
lrwxr-xr-x 1 zmwang admin 28 Jun  7 12:14 /usr/local/bin/vcs -> ../Cellar/vcs/1.13.2/bin/vcs
$ ffmpeg -loglevel panic -f rawvideo -s hd720 -pix_fmt yuv420p -r 30 -t 5 -i /dev/zero -y video.mp4
$ vcs -i 1 video.mp4
Video Contact Sheet *NIX v1.13.2, (c) 2007-2014 Toni Corvera
Unable to locate DejaVu Sans font. Falling back to helvetica.
Processing video.mp4...
Detected video length can't be reached. Safe measuring enabled.
Starting safe length measuring (this might take a while)...
   ... trying 00:04.50
Capturing in range [00:01.00-00:04.00]. Total length: 00:04.50
Generating capture #1/4 (00:01.00)...
Generating capture #2/4 (00:02.00)...
Generating capture #3/4 (00:03.00)...
Generating capture #4/4 (00:04.00)...
Composing standard contact sheet...
Adding header and footer...
Done. Output wrote to video.mp4-1.png
Cleaning up...
```

**Comment by ilovezfs** [comment]
Are you using the new test or the old test?

**Comment by ilovezfs** [comment]
@zmwangx demo: https://gist.github.com/ilovezfs/1c425155ab7e60b7c5b4597f0a2c2d24

**Comment by retokromer** [comment]
It seems to me that this is a more general issue. I guess the warning message
```
stty: stdin isn't a terminal
```
is generated when brew commands are executed from a (Bash) script, instead as be typing the same commands into the Terminal.

E.g.
```
Please wait while updating Brew...
Updated 2 taps (caskroom/cask, homebrew/core).
stty: stdin isn't a terminal
==> Updated Formulae
stty: stdin isn't a terminal
mediaconch ✔
Please wait while upgrading Brew's formulae...
stty: stdin isn't a terminal
==> Upgrading 1 outdated package, with result:
mediaconch 17.05
stty: stdin isn't a terminal
==> Upgrading mediaconch 
stty: stdin isn't a terminal
==> Downloading https://homebrew.bintray.com/bottles/mediaconch-17.05.el_capitan
######################################################################## 100,0%
stty: stdin isn't a terminal
==> Pouring mediaconch-17.05.el_capitan.bottle.tar.gz
stty: stdin isn't a terminal
==> Using the sandbox
🍺  /usr/local/Cellar/mediaconch/17.05: 52 files, 19.8MB
```

**Comment by zmwangx** [comment]
@ilovezfs Okay, old test fails when mplayer is around, so the new test does fix the problem.

**Comment by zmwangx** [comment]
@retokromer That's been fixed. brew update.

**Comment by ilovezfs** [comment]
@zmwangx Indeed!

**Comment by ilovezfs** [comment]
(It does make me think though that the reverse dependency test of vcs for ffmpeg PRs may be bogus if vcs is using mplayer instead of ffmpeg to run the test.)

**Comment by zmwangx** [comment]
Whatever, I don't give a shit about vcs ;)

**Comment by ilovezfs** [comment]
LOL.

**Pull request closed without merging**
