### PR TITLE
rio 0.0.28

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>- **Breaking**: Settings UI has been removed and `editor` property has been added.
- **Breaking**: default `padding-x` for MacOS has moved from `10.0` to `5.0`.
- **Breaking: Background API has moved to Window**

Example:

```toml
[window]
width = 600
height = 400
mode = "Windowed"
foreground-opacity = 1.0
background-opacity = 1.0
```

Using image as background:

```toml
[window.background-image]
path = "/Users/rapha/Desktop/eastward.jpg"
width = 200.0
height = 200.0
x = 0.0
y = 0.0
```

- **Breaking:** MacOS default navigation mode will become `NativeTab`.
- Support for blur background.
- Support opacity for foreground and background.
- Cursor hide feature is now behind configuration `hide-cursor-when-typing`.
- Confirm before quite (it can be disabled through configuration `confirm-before-quit`).
- Close the last tab in MacOS when using `command + w` (Ref: [#296](https://github.com/raphamorim/rio/issues/296))
- OSC 8 (Hyperlinks).
- Fix current path on new tab is not working when using Native Tab (Ref [#323](https://github.com/raphamorim/rio/issues/323)).
- Change `POLLING_TIMEOUT` for configuration update from 1s to 2s.
- Update `.icns` file with more format and add new icon (Ref: [#329](https://github.com/raphamorim/rio/pull/329)) by [@nix6839](https://github.com/nix6839).
- Update `.ico` files with more resolution and add new icon (Ref: [#329](https://github.com/raphamorim/rio/pull/329)) by [@nix6839](https://github.com/nix6839).</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> cargo install --locked --root=/opt/homebrew/Cellar/rio/0.0.28 --path=rio
  error: `/private/tmp/rio-20231129-5490-gsf7ja/rio-0.0.28/rio` is not a directory. --path must point to a directory containing a Cargo.toml file.
```

**Comment by Bo98** [comment]
Directory got moved to `frontends/cross-winit` I think - will need testing locally to ensure it runs (not just `brew test` ideally)

**Comment by chenrui333** [comment]
- relates to https://github.com/raphamorim/rio/commit/6edff974b8bd2169b21af2ce68414174fadc5204

**Review by p-linnane — APPROVED** [review]
I've verified this works locally.

**Pull request merged**
