### PR TITLE
php: removed extension 'tidy'

### PR DESCRIPTION
**Pull request by JoyceBabu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thank you for the pull request @JoyceBabu. However, we're not planning on adding any options to the php formula.

**Comment by JoyceBabu** [comment]
`Homebrew/homebrew-php` was using `libxml2` and `tidy-html5` by default. Will you accept a PR for making it the default in new `Homebrew-core/php`?

**Comment by ilovezfs** [comment]
@JoyceBabu we use system dependencies wherever possible unless there's some extraordinary reason not to. What would be the reason for preferring those formulae over the system versions?

**Comment by JoyceBabu** [comment]
I am only interested in `tidy-html5`. Unfortunately, it requires `libxml2`.

The system tidy packages does not validate HTML5 code correctly. Since most websites have moved to HTML5, it makes the default tidy extension pretty much useless. IMHO a better option would be to remove tidy from the core extensions list.

**Comment by ilovezfs** [comment]
>But that would still require libxml2.

What would? The php formula is already using the system libxml2.

**Comment by JoyceBabu** [comment]
Sorry, I meant `homebrew-libxml2`. Compiling tidy with `tidy-html5` fails when php is configured with  `--enable-libxml`. But it will compile successfully with homebrew's libxml2.

**Comment by ilovezfs** [comment]
@JoyceBabu can you please change this PR to remove the tidy support altogether, and bump the revision?

**Comment by JoyceBabu** [comment]
In the PR I had made homebrew libxml2 support optional. It was enabled only when either `--with-homebrew-libxml2` or `--with-homebrew-tidy-html5` was specified. Since you mentioned that there are no plans for adding options to the `php` formula, should I make `homebrew-libxml2` support enabled by default?

**Comment by ilovezfs** [comment]
No we'll continue using system libxml2.

**Comment by JoyceBabu** [comment]
I just checked, the conflict with system `libxml2` happens only when building with `tidy-html5` statically. I can build `tidy` with `tidy-html5` as a shared extension without any errors. I will update the PR shortly.

**Comment by ilovezfs** [comment]
Actually no dependencies are changing so we don't need the revision bump. I've removed it. We will need to pull new bottles, though.

**Comment by JoyceBabu** [comment]
I tried to create a new `php72-tidy` package under `Homebrew/homebrew-php`. But I am not sure how to populate the `sha256` values for different osx versions.

**Review by ilovezfs — APPROVED** [review]

**Comment by SMillerDev** [comment]
> I tried to create a new php72-tidy package under Homebrew/homebrew-php. But I am not sure how to populate the sha256 values for different osx versions.

The idea would be that you'd install the extension through pecl as the homebrew-php tap is deprecated. https://github.com/Homebrew/homebrew-php/issues/4721

**Comment by kabel** [comment]
> The idea would be that you'd install the extension through pecl

I don't think that applies in this case. Along with some of the other core/upstream maintained extensions that are being pulled out (imap, mcrypt, tidy), pecl _does not_ have the latest source suitable for installation with the latest versions. That is, pecl and upstream have diverged.

It remains unclear what should be done with these extensions that are being pulled out, as the deprecation notice explicitly stated that separate formula for individual extensions would _not_ be accepted. So there needs to be a clear decision on allowing shared extensions to be built, as a mentioned in #24766.

**Comment by kabel** [comment]
@ilovezfs I respectfully ask for an exception to the system included libs rule in the case of libTidy. The system lib is the 31 October 2006 version which is _well_ behind the current maintained upstream and lacks the modern HTML features that users are reporting missing. https://github.com/Homebrew/homebrew-core/commit/9bc73e960acc58233ac058e78d3a76b968eb4097 works fine and addresses the users' concerns.

**Comment by ilovezfs** [comment]
There's insufficient interest in the tidy feature based on the analytics to justify depending on the Homebrew formula, and we won't be allowing shared extensions at this time.

**Comment by JoyceBabu** [comment]
> @ilovezfs I respectfully ask for an exception to the system included libs rule in the case of libTidy. The system lib is the 31 October 2006 version which is well behind the current maintained upstream and lacks the modern HTML features that users are reporting missing. 

I am not sure whether it is just for me, but I was able to compile tidy extension statically with libtidy from `tidy-html5` along with system `libxml2`. I had to either use latest `libxml2` from homebrew or had to compile tidy extension as shared library. Can someone please try if it is working for you.
```
./configure --no-reexec --prefix=/usr/local/Cellar/php/7.2.3_2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.2 --with-config-file-path=/usr/local/etc/php/7.2 --with-config-file-scan-dir=/usr/local/etc/php/7.2/conf.d --disable-all --enable-fpm --with-layout=GNU --enable-libxml --with-tidy=/usr/local/opt/tidy-html5
make
```
But it compiles successfully, when either `--with-libxml-dir=/usr/local/opt/libxml2` is added or the tidy library location is omitted.

**Comment by commitay** [comment]
Thanks for your first contribution to Homebrew @JoyceBabu!

**Comment by ondrejmirtes** [comment]
Hi, I really don't understand this PR - how can I install tidy now? I installed fresh php@7.2 via homebrew/core and ext-tidy is missing from my installation.

**Comment by ondrejmirtes** [comment]
@kabel Thanks! After homebrew/php got deprecated, the PHP ecosystem on macOS became a huge mess...

**Pull request closed without merging**
