### PR TITLE
apache-spark 2.0.0

### PR DESCRIPTION
**Pull request by zhiboz**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by kunickiaj** [comment]
JW how we handle hadoop version changes. The default is now 2.7 and no longer 2.6.
There's also a sans-hadoop package available.

Maybe these should become separate formulae?

**Comment by zhiboz** [comment]
Updated to `spark-2.0.0-bin-hadoop2.7.tgz`.

**Comment by leaxoy** [comment]
good job

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/7418b231190d137f0378b267f5b76ff91dd37ea8. Thank you for your contribution to Homebrew @zhiboz; we appreciate it! :smiley_cat:

**Pull request merged**
