### PR TITLE
jenkins 2.231

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Test seems to time out, maybe a more agressive kill?

**Comment by chenrui333** [comment]
```
2020-04-14 16:43:12.796+0000 [id=28]	INFO	jenkins.install.SetupWizard#init: 

*************************************************************
*************************************************************
*************************************************************

Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:

3d09e495779441d0b0ec37b01ed50dc7

This may also be found at: /private/tmp/jenkins-test-20200414-46380-b6nka1/secrets/initialAdminPassword

*************************************************************
*************************************************************
*************************************************************

2020-04-14 16:43:17.316+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2020-04-14 16:43:17.328+0000 [id=51]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
2020-04-14 16:43:17.328+0000 [id=51]	INFO	hudson.util.Retrier#start: Performed the action check updates server successfully at the attempt #1
2020-04-14 16:43:17.333+0000 [id=21]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
2020-04-14 16:43:17.334+0000 [id=51]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Download metadata. 6,782 ms
2020-04-14 16:43:22.387+0000 [id=61]	WARNING	h.n.AbstractAsyncNodeMonitorDescriptor#error: Failed to monitor master for Free Swap Space
java.io.IOException: No suitable implementation found: os.name=Mac OS X os.arch=x86_64 sun.arch.data.model=64
	at org.jvnet.hudson.MemoryMonitor.obtain(MemoryMonitor.java:91)
	at org.jvnet.hudson.MemoryMonitor.get(MemoryMonitor.java:57)
	at hudson.node_monitors.SwapSpaceMonitor$MonitorTask.call(SwapSpaceMonitor.java:119)
	at hudson.node_monitors.SwapSpaceMonitor$MonitorTask.call(SwapSpaceMonitor.java:115)
	at hudson.remoting.LocalChannel$1.call(LocalChannel.java:52)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at hudson.remoting.LocalChannel$2.get(LocalChannel.java:81)
	at hudson.node_monitors.AbstractAsyncNodeMonitorDescriptor.monitorDetailed(AbstractAsyncNodeMonitorDescriptor.java:114)
	at hudson.node_monitors.AbstractAsyncNodeMonitorDescriptor.monitor(AbstractAsyncNodeMonitorDescriptor.java:78)
	at hudson.node_monitors.AbstractNodeMonitorDescriptor$Record.run(AbstractNodeMonitorDescriptor.java:306)
[34m==>[0m [1mcurl localhost:50254/[0m
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   677  100   677    0     0   1267      0 --:--:-- --:--:-- --:--:--  1267
Killing child processes...
[31mError:[0m jenkins: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

**Comment by SMillerDev** [comment]
Yeah, try a sigterm at the end of the test. The server isn't killed correctly.

**Comment by chenrui333** [comment]
I see, sounds good!

**Comment by bayandin** [comment]
As per https://github.com/Homebrew/homebrew-core/pull/53212#issuecomment-614628167 we don't need to bother about killing Jenkins server anymore

**Pull request merged**
