### PR TITLE
cmake cmake-docs 3.28.4

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Anyone knows why cmake depends on OpenSSL on linux? That seems weird… and there is no comment in the PR that added that dependency.

**Comment by Bo98** [comment]
> Anyone knows why cmake depends on OpenSSL on linux?

My guess is from it using a bundled curl, which makes sense given curl depends on cmake itself via brotli and zstd.

Though there's probably some things bundled that don't really need to be like `zlib`.

**Comment by fxcoudert** [comment]
> My guess is from it using a bundled curl

I think I underestimated what cmake does. Next I'll learn it's actually a full OS :)

**Comment by fxcoudert** [comment]
Capture d’écran 2024-03-20 à 17 18 17

**Comment by ZhongRuoyu** [comment]
In CMake's typical release process the website is updated some time after release assets are published on GitHub (https://github.com/Kitware/CMake/releases). (Probably because the URLs to those release assets are referenced on the website.) We can check https://cmake.org/download/#latest again when CI finishes; it should be updated by then.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
