### PR TITLE
checkov 3.1.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
     File "/opt/homebrew/Cellar/checkov/3.1.0/libexec/lib/python3.12/site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client
      raise ValueError("Credentials for client are not set")
  ValueError: Credentials for client are not set
```

**Comment by chenrui333** [comment]
- https://github.com/bridgecrewio/checkov/issues/5784

**Comment by p-linnane** [comment]
Upstream recommends v3.1.3 to resolve this error. We will need to wait for v3.1.10+.

**Comment by chenrui333** [comment]
> Upstream recommends v3.1.3 to resolve this error. We will need to wait for v3.1.10+.

I am gonna make another PR to check if that is the case.

**Comment by chenrui333** [comment]
Looks like 3.1.9 works. I guess we can ship and bring the throttling back in the next release?

**Pull request closed without merging**
