### PR TITLE
kubernetes-cli 1.22.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
E0804 14:32:54.302716   94775 openapi.go:309] Error when generating: status, Status invalid type
2021/08/04 14:32:54 OpenAPI code generation error: Failed executing generator: some packages had errors:
failed to generate default in k8s.io/api/apps/v1.DaemonSetCondition: Status: not sure how to enforce default for Unsupported
```

**Comment by branchvincent** [comment]
```
==> make WHAT=cmd/kubectl
...
+++ [0805 04:50:25] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
ln: failed to create symbolic link '/private/tmp/kubernetes-cli-20210805-12646-1u4ds13/_output/bin': File exists
```

we've seen this before: https://github.com/Homebrew/homebrew-core/pull/77884#issuecomment-846611867

**Comment by chenrui333** [comment]
yeah, that sounds about right, k8s-cli build is certainly the flaky one.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
all good now. :)

**Pull request closed without merging**
