### PR TITLE
pgrouting 2.4.0 / 2.4.1

### PR DESCRIPTION
**Pull request by dersvenhesse**
Updated pgrouting's url to latest `2.4.0`.

### CODE REVIEW

**Comment by dersvenhesse** [comment]
@ilovezfs Do you mind helping out by looking at the build errors?

**Comment by fxcoudert** [comment]
```
[ 72%] Building C object src/max_flow/src/CMakeFiles/max_flow.dir/max_flow_many_to_one.c.o
cd /tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/build/src/max_flow/src && /usr/local/Homebrew/Library/Homebrew/shims/super/clang   -I/usr/local/Cellar/postgresql/9.6.2/include/server -I/usr/local/include -I/tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/common/src -I/tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/dijkstra/src  -DPGSQL_VERSION=96  -std=gnu99 -fPIC  -frounding-math  -DNDEBUG -DPGSQL_VERSION=96 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -o CMakeFiles/max_flow.dir/max_flow_many_to_one.c.o   -c /tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/max_flow/src/max_flow_many_to_one.c
In file included from /tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/bdDijkstra/src/bdDijkstra_driver.cpp:35:
/tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/bdDijkstra/src/./pgr_bdDijkstra.hpp:84:24: error: reference to non-static member function must be called
     void clean_log() {log.clear();}
                       ^~~
```

**Comment by fxcoudert** [comment]
@dersvenhesse can you patch the offending line to be `void clean_log() {m_log.clear();}` (as per upstream PR) so we can check if this builds?

**Comment by dersvenhesse** [comment]
@fxcoudert Here it is: https://github.com/pgRouting/pgrouting/pull/768

**Comment by fxcoudert** [comment]
That's not how we usually do this… keep the stable release, but use a `patch` command.

**Comment by fxcoudert** [comment]
Actually, upstream is talking about releasing a 2.4.1 soon, so we might as well wait for that.

**Comment by dersvenhesse** [comment]
Tried it anyhow and it built without errors. Now we can either merge or wait for `2.4.1`.

**Comment by cvvergara** [comment]
@dersvenhesse 
v2.4.1 is out
https://github.com/pgRouting/pgrouting/releases/tag/v2.4.1

**Comment by cvvergara** [comment]
@dersvenhesse 
I have this wiki:
https://github.com/pgRouting/pgrouting/wiki/Download%3A-FreeBSD-OS-X
I don’t have macOS
and I don’t  know if the brew command is correct, or what users have to do before brew statement
and also I don’t  know which versions of pgRouting are available using the command
Can you help me out with this?
Can you edit the wiki? (I don’t  know about the permissions on the wiki)

**Comment by dersvenhesse** [comment]
@cvvergara I updated this PR for homebrew to include 2.4.1. Thanks for hinting to the issue and releasing the fixed version! 

The installation command in your wiki is pretty much all one needs to do on macOS if homebrew is installed. The requirements can be installed via brew as well and are configured here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pgrouting.rb. Specific versions for pgrouting can't be chosen at the moment. The version defined in the formulas file will be installed. If specific versions are need to be, there is https://github.com/Homebrew/homebrew-versions.

@fxcoudert do you mind merging?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @dersvenhesse for the pull request, and thanks @cvvergara for the new release.

**Pull request closed without merging**
