### PR TITLE
mingw-w64: update binutils resource

### LINKED ISSUE #69843: mingw-w64 bottle depends on zstd but formula doesn't install it
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Build Windows executables using mingw-w64

## What happened (include command output)

When using mingw-w64 to build anything, it fails to run because the bottle has an implicit dependency on zstd. After manually installing zstd, it does work. This is probably because of GCC 10's [zstd support for LTO byte code compression](https://gcc.gnu.org/legacy-ml/gcc/2019-07/msg00003.html), and the formula probably needs to either require zstd or pass `--with-zstd=no` when configuring gcc.

<details>
  <summary>Command output</summary>
  <pre>
 $ x86_64-w64-mingw32-gcc -dM -E - < /dev/null
dyld: Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
  Referenced from: /usr/local/Cellar/mingw-w64/8.0.0_1.reinstall/toolchain-x86_64/bin/../libexec/gcc/x86_64-w64-mingw32/10.2.0/cc1
  Reason: image not found
x86_64-w64-mingw32-gcc: internal compiler error: Abort trap: 6 signal terminated program cc1
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
  </pre>
</details>

## What you expected to happen

mingw-w64 should work.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew uninstall zstd
$ brew install mingw-w64
$ x86_64-w64-mingw32-gcc -dM -E - < /dev/null
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #69843.

### CODE REVIEW

**Comment by carlocab** [comment]
Bottle install receipt reports no linkage with zstd.

**Comment by jonchang** [comment]
It was probably an opportunistic link. Is there some way we can pass a configure option to avoid using that even if it's detected on the system?

**Comment by carlocab** [comment]
I did try looking at the configure flags, but couldn't find anything related. I'll look at it again.

**Comment by carlocab** [comment]
Nope. `grep zstd` in the tarball doesn't even give me anything.

**Comment by jonchang** [comment]
:shrug: maybe the linker just thought the two went well together. I guess let's hope it doesn't happen again 🤞

**Comment by mrpippy** [comment]
> Nope. `grep zstd` in the tarball doesn't even give me anything.

It's in the gcc source. I think passing `--with-zstd=no` to [gcc's configure](https://github.com/Homebrew/homebrew-core/blob/07a7ed8dd934635ce2c6dad2ee5aa3a06262c5c9/Formula/mingw-w64.rb#L93) should do it.

**Comment by carlocab** [comment]
@mrpippy can you open a PR for that?

**Comment by mrpippy** [comment]
> @mrpippy can you open a PR for that?

Ok I created #70849

**Pull request closed without merging**
