### PR TITLE
pytorch 2.3.0 torchvision 0.18.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by fxcoudert** [comment]
I think the openai-whisper test failure is a brew bug: https://github.com/Homebrew/brew/issues/17203

**Comment by fxcoudert** [comment]
`openai-whisper` failure on Intel is preexisting, see also https://github.com/Homebrew/homebrew-core/pull/170804

**Review by fxcoudert — APPROVED** [review]

**Comment by chenrui333** [comment]
rebased after https://github.com/Homebrew/homebrew-core/pull/170804 merge

**Comment by timsutton** [comment]
```
  ==> /usr/local/Cellar/openai-whisper/20231117_4/bin/whisper tests --model tiny.en --model_dir models --output_format txt
  /usr/local/Cellar/openai-whisper/20231117_4/libexec/lib/python3.12/site-packages/whisper/transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead
    warnings.warn("FP16 is not supported on CPU; using FP32 instead")
  Error: openai-whisper: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /usr/local/Cellar/openai-whisper/20231117_4/bin/whisper tests --model tiny.en --model_dir models --output_format txt
  /usr/local/Homebrew/Library/Homebrew/formula.rb:3049:in `block in system'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2985:in `open'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2985:in `system'
```

**Comment by AkiSakurai** [comment]
```
* thread #1, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000111a993bc
->  0x111a993bc: vpbroadcastq %rax, %zmm0
    0x111a993c2: vmovdqa64 %zmm0, 0xc0(%rsp)
    0x111a993ca: leaq   0x28(%rsp), %r15
    0x111a993cf: movq   %r14, 0x10(%rsp)
  thread #2, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000111a993bc
```
When I built and ran the PyTorch formula locally, the Whisper tests crashed with the EXC_BAD_INSTRUCTION error, and it seemed to be attempting to run AVX512 instructions, which the CPU does not support.

**Pull request closed without merging**
