### PR TITLE
icu4c 73.1

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Need to wait for the proper source archive to be released. Can take a day or two.

**Comment by p-linnane** [comment]
> Need to wait for the proper source archive to be released. Can take a day or two.

It's out now.

**Comment by SMillerDev** [comment]
on 13-arm
```
brew linkage --test apngasm
brew linkage --test boost
brew linkage --test boost@1.76
brew linkage --test couchdb
brew linkage --test tarantool
brew linkage --test tectonic
brew linkage --test tepl
brew linkage --test tesseract
brew linkage --test texlive
brew linkage --test tracker
brew linkage --test urweb
brew linkage --test vte3
brew linkage --test widelands
brew linkage --test yaz
brew linkage --test zebra
brew linkage --test zk
brew linkage --test znc
brew linkage --test zorba
```

**Comment by SMillerDev** [comment]
Linux failed on a bunch of:
```
  /usr/bin/ld: warning: libicuuc.so.72, needed by /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.10.4/lib/libxml2.so, not found (try using -rpath or -rpath-link)
```

But how did that manage to evade linkage checks?

**Comment by SMillerDev** [comment]
Spidermonkey needs a bump

**Comment by SMillerDev** [comment]
Requesting a review before a conflict arises

**Review by iMichka — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Comment by SMillerDev** [comment]
Re-running dependency testing since I broke doctor on the arm-11 runner with https://github.com/Homebrew/homebrew-portable-ruby/pull/174

**Comment by fxcoudert** [comment]
11-arm64 failed (https://github.com/Homebrew/homebrew-core/actions/runs/4906283498/jobs/8771591166?pr=128294#logs) but it did not produce logs. The rest were cancelled because there is no `CI-no-fail-fast`.

**Comment by fxcoudert** [comment]
Deps failures on 12-x86_64 are linkage issues referenced in:

```
chakra
clickhouse-odbc
dwdiff
easyrpg-player
freeciv
hfstospell
icu4c
libical
liblcf
libzim
mysql
ncmpcpp
node
node@16
node@18
openrct2
pazpar2
percona-server
percona-xtrabackup
php
php@8.1
postgresql@14
qt
samba
sile
simdutf
```

**Comment by fxcoudert** [comment]
A story in three pictures:

1. FAQ:
Capture d’écran 2023-05-11 à 18 56 06

2. That's interesting:

Capture d’écran 2023-05-11 à 18 56 11

3. So I clicked:

Capture d’écran 2023-05-11 à 18 56 17

**Comment by carlocab** [comment]
> A story in three pictures:

That makes a lot of sense

**Comment by fxcoudert** [comment]
`Error: 239 failed steps!` 😭

**Comment by fxcoudert** [comment]
@SMillerDev could we maybe kill the remaining ARM runners? I don't think we're going to learn more than we already have with both the x86_64 and the 13-arm64.

**Comment by fxcoudert** [comment]
I am removing https://github.com/Homebrew/homebrew-core/labels/no%20long%20build%20conflict for now, because I don't think we can merge in this round of testing anyway, and it blocks https://github.com/Homebrew/homebrew-core/pull/130739

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
macOS 13-arm64:

```
brew install --verbose --build-bottle clickhouse-odbc
brew install --verbose --build-bottle percona-server
brew install --verbose --build-bottle percona-xtrabackup
```

Intel:

```
brew install --verbose --build-bottle chakra
brew fetch --retry libmspub --build-bottle --force
brew install --verbose --build-bottle libmspub
brew install --verbose --build-bottle percona-xtrabackup
brew install --verbose --build-bottle tectonic
```

**Comment by carlocab** [comment]
Merging this via a staging branch might be easier: #133611

**Comment by carlocab** [comment]
#133740 should be pretty close to merging, so I'm closing this in favour of the other one.

**Pull request closed without merging**
