### PR TITLE
groonga 6.1.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Release has not been announced yet.

**Comment by kenhys** [comment]
Groonga 6.1.1 has been released!
http://groonga.org/en/blog/2016/11/29/groonga-6.1.1.html 

Could you support zstd which is introduced feature in 6.1.1?

**Comment by ilovezfs** [comment]
@kenhys sure. Now that https://github.com/Homebrew/homebrew-core/pull/7351 is merged, I'll take a look at adding support for zstd.

**Comment by kenhys** [comment]
Thanks, @ilovezfs!

**Pull request closed without merging**
