### PR TITLE
consul 1.15.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by vvarga007** [comment]
@chenrui333 As I see there is a problem with the tools that depend on consul. 
envconsul, fabio, stolon

**Comment by vvarga007** [comment]
@chenrui333 Can we try this one more time?

**Comment by chenrui333** [comment]
absolutely!

**Comment by vvarga007** [comment]
@chenrui333 It worked. Thanks!

**Comment by chenrui333** [comment]
Thanks @vvarga007!! 🚀

**Review by ZhongRuoyu — APPROVED** [review]
Thanks @vvarga007!

**Pull request closed without merging**
