### PR TITLE
juju 2.8.1

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by claui — APPROVED** [review]

**Comment by claui** [comment]
Thanks @SeekingMeaning! 🍻

**Comment by SimonRichardson** [comment]
@claui Can we revert this, we haven't released the 2.8.1 version. As we've not officially released the 2.8.1 and only have 2.8.1 in proposed, users of the client will have to use `--agent-stream` in order to fix and that's not something we want users to have to do.

**Comment by SeekingMeaning** [comment]
@SimonRichardson Would it be possible to mark 2.8.1 as a pre-release on GitHub?

**Comment by SimonRichardson** [comment]
@SeekingMeaning Yes I can, but is Homebrew automating things now? I'd like to question how you noticed that 2.8.1 was released, so I can adapt our release process...

**Comment by chenrui333** [comment]
@SimonRichardson, should we downgrade to `juju-2.8.0` or `juju-2.7.7`?

I saw juju-2.7.7 is the latest version

**Comment by SeekingMeaning** [comment]
@SimonRichardson Sure, Homebrew provides a tool ([`brew livecheck`](https://github.com/Homebrew/homebrew-livecheck)) for automatically checking for new versions of packages. It noticed the 2.8.1 tag and reported it as a new version.

I'm not sure which one but either `livecheck` or `audit` will prevent an update if the release is marked as a pre-release.

(Note: I'm not an official maintainer, only a contributor)

**Comment by SimonRichardson** [comment]
@SeekingMeaning thanks for this. I'll ensure that we mark new releases as pre-releases and hopefully, that'll help with this.

**Comment by battlemidget** [comment]
> @SimonRichardson, should we downgrade to `juju-2.8.0` or `juju-2.7.7`?
> 
> I saw juju-2.7.7 is the latest version

Hi @chenrui333 it should be juju-2.8.0 please

**Comment by chenrui333** [comment]
> > @SimonRichardson, should we downgrade to `juju-2.8.0` or `juju-2.7.7`?
> > I saw juju-2.7.7 is the latest version
> 
> Hi @chenrui333 it should be juju-2.8.0 please

Is there any good way that we can find this piece of info anywhere (either by using the `latest` tag or on the homepage), I can actually see this would be ongoing problem for the future as well.

**Comment by claui** [comment]
> @SeekingMeaning thanks for this. I'll ensure that we mark new releases as pre-releases and hopefully, that'll help with this.

Thanks @SimonRichardson, that would be super helpful indeed!

**Pull request closed without merging**
