### PR TITLE
guile 2.0.14, 2.1.7 (devel)

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Useful error:
```
Making install in module
  GUILEC ice-9/eval.go
Backtrace:
In unknown file:
   ?: 3 [apply-smob/1 #<boot-closure 10c187ac0 (_ _ _)> #t ...]
   ?: 2 [apply-smob/1 #<catch-closure 10c2bc240>]
   ?: 1 [primitive-eval ((@ # %) (begin # # #))]
   ?: 0 [mkstemp! "ice-9/eval.go.XXXXXX" "wb"]

ERROR: make[2]: *** [ice-9/eval.go] Error 1

**Comment by dunn** [comment]
Also the version scanning must be goofy:
```
        Error: 1 problem in 1 formula
guile:
  * revision should not decrease

**Comment by ilovezfs** [comment]
@dunn the workaround for the Sierra bug is `ENV["ac_cv_func_mkostemp"] = "no"`

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
@ilovezfs This is now green, but you may have had other concerns that kept you from pursuing merging this, so you should be the one to decide what to do from here.

**Comment by ilovezfs** [comment]
Yeah, MacPorts has a more elaborate patch that addresses a related issue, which we should adopt.

**Pull request closed without merging**
