### PR TITLE
libusb 1.0.23

### PR DESCRIPTION
**Pull request by jeffreywildman**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`libftdi` and `owfs` need to have their revision bumped.

**Comment by bryancostanich** [comment]
hm. could really use this version of libusb. :)

**Comment by jeffreywildman** [comment]
@fxcoudert I'm not sure how to interpret the failing tests in order to make additional necessary corrections.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Two linkage issues are false positives. I think the `exodriver` is a preexisting issue, so I'll merge now.

**Pull request closed without merging**
