### PR TITLE
protobuf 3.14.0

### PR DESCRIPTION
**Pull request by jeroen**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by jeroen** [comment]
I don't understand why grpc fails to rebuild, it seems unrelated to protobuf:

```
Undefined symbols for architecture x86_64:
  "bool absl::lts_2020_09_23::str_format_internal::FormatArgImpl::Dispatch<absl::lts_2020_09_23::string_view>(absl::lts_2020_09_23::str_format_internal::FormatArgImpl::Data, absl::lts_2020_09_23::str_format_internal::FormatConversionSpecImpl, void*)", referenced from:
      grpc_core::JoinHostPort(absl::lts_2020_09_23::string_view, int) in host_port.cc.o
  "absl::lts_2020_09_23::string_view::find(char, unsigned long) const", referenced from:
      grpc_core::(anonymous namespace)::DoSplitHostPort(absl::lts_2020_09_23::string_view, absl::lts_2020_09_23::string_view*, absl::lts_2020_09_23::string_view*, bool*) in host_port.cc.o
  "absl::lts_2020_09_23::string_view::rfind(char, unsigned long) const", referenced from:
      grpc_core::JoinHostPort(absl::lts_2020_09_23::string_view, int) in host_port.cc.o
ld: symbol(s) not found for architecture x86_64
```

I suspect a recent change in cmake.

**Comment by jeroen** [comment]
Rebased for the updated grpc...

**Comment by SMillerDev** [comment]
```
brew fetch --retry libphonenumber --build-bottle --force
brew install --verbose --build-bottle libphonenumber
brew test --retry --verbose torchvision
```

**Comment by jeroen** [comment]
We now see 2 errors in reverse dependencies which are unrelated protobuf. libphonenumber seems to have moved a tag:

```
==> Downloading https://github.com/google/libphonenumber/archive/v8.12.13.tar.gz
Error: SHA256 mismatch
Expected: 1d0dab61ab0d4ffa9d86fd93a46b0f4df7ab159bf8b8f08416dc211a753747b2
  Actual: 4d202b3d20c545d39a9a0bbaf0f7f26e64a8875429bfadf36f7015adb9bada37
 Archive: /Users/brew/Library/Caches/Homebrew/downloads/27743676f863120797162238737b4e922e38442c316df1848d20bb017ac70e7a--libphonenumber-8.12.13.tar.gz
To retry an incomplete download, remove the file above.
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/27743676f863120797162238737b4e922e38442c316df1848d20bb017ac70e7a--libphonenumber-8.12.13.tar.gz
```

And it looks like libtorchvision has been compiled agains xQuartz (which is in /opt/X11) which is no longer available?

```
==> Testing torchvision
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201117-3508-1m51uot.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/torchvision.rb --verbose --retry
==> /usr/bin/clang++ -std=c++14 main.cpp -o test -I/usr/local/opt/libtorch/include -I/usr/local/opt/libtorch/include/torch/csrc/api/include -L/usr/local/opt/libtorch/lib -ltorch -ltorch_cpu -lc10 -L/usr/local/Cellar/torchvision/0.8.1/lib -ltorchvision
==> ./test
dyld: Library not loaded: /opt/X11/lib/libpng16.16.dylib
  Referenced from: /usr/local/opt/torchvision/lib/libtorchvision.dylib
  Reason: image not found
```

I don't think there is anything I can do about these

**Comment by SMillerDev** [comment]
For libphonenumber we should ask upstream if it was intentional, for torchvision we should figure out how to make it not do that. @gromgit might be able to help there.

**Comment by gromgit** [comment]
@jeroen, based on my local tests, `torchvision` just needs a `depends_on "libpng"` and a revision bump.

**Comment by jeroen** [comment]
@chenrui333 I think this is ready to merge. The only remaining error is:

```
==> FAILED
Error: 1 problem in 1 formula detected
libphonenumber:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

The upstream git repository doesn't have an issue tracker, but they seem to be creating and moving the latest tag as part of the release process to test release candidates.

**Comment by chenrui333** [comment]
yeah, let's move forward with the change.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
Auto-merging Formula/opencv.rb
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty
```

**Comment by jeroen** [comment]
Is it because [opencv was updated](https://github.com/homebrew/homebrew-core/blob/master/Formula/opencv.rb) between when yesterday and now?

**Comment by chenrui333** [comment]
yeah, that sounds about right, unfortunately. I just rebased and have another run before the merge.

**Comment by jeroen** [comment]
Hmm OK, I think the PR now no longer contains a bump to opencv, so it will probably fail for that...

**Comment by chenrui333** [comment]
> Hmm OK, I think the PR now no longer contains a bump to opencv, so it will probably fail for that...

my bad

**Comment by chenrui333** [comment]
This time should work. 🤞

**Comment by jeroen** [comment]
🤞

**Comment by ydnar** [comment]
:wave: any word on when this will be deployed?

**Comment by scpeters** [comment]
from the most recent build:

~~~
Error: 3 failed steps!
brew audit libphonenumber --online --git --skip-style
brew install --verbose --build-bottle monero
brew install --verbose --build-bottle wownero
~~~

**Comment by scpeters** [comment]
> from the most recent build:
> 
> ```
> Error: 3 failed steps!
> brew audit libphonenumber --online --git --skip-style
> brew install --verbose --build-bottle monero
> brew install --verbose --build-bottle wownero
> ```

both `monero` and `wownero` appear to be trying to compile files ending in `.S` as c++, but these files are not c++, so it is rather unsuccessful

~~~
/tmp/monero-20201119-46407-vmue1z/external/randomx/src/jit_compiler_x86_static.S:1:3: error: invalid preprocessing directive
# Copyright (c) 2018-2019, tevador <tevador@gmail.com>
  ^
/tmp/monero-20201119-46407-vmue1z/external/randomx/src/jit_compiler_x86_static.S:3:3: error: invalid preprocessing directive
# All rights reserved.
  ^
~~~

**Comment by traversaro** [comment]
> 
> 
> > from the most recent build:
> > ```
> > Error: 3 failed steps!
> > brew audit libphonenumber --online --git --skip-style
> > brew install --verbose --build-bottle monero
> > brew install --verbose --build-bottle wownero
> > ```
> 
> both `monero` and `wownero` appear to be trying to compile files ending in `.S` as c++, but these files are not c++, so it is rather unsuccessful
> 
> ```
> /tmp/monero-20201119-46407-vmue1z/external/randomx/src/jit_compiler_x86_static.S:1:3: error: invalid preprocessing directive
> # Copyright (c) 2018-2019, tevador <tevador@gmail.com>
>   ^
> /tmp/monero-20201119-46407-vmue1z/external/randomx/src/jit_compiler_x86_static.S:3:3: error: invalid preprocessing directive
> # All rights reserved.
>   ^
> ```

Related CMake issue: https://gitlab.kitware.com/cmake/cmake/-/issues/21469 . I think this regression will be fixed in CMake 3.19.1 .

**Comment by jeroen** [comment]
I'll try to unblock this again via: https://github.com/Homebrew/homebrew-core/pull/65416

**Comment by chenrui333** [comment]
merged the cmake fix and rebased the PR. 🤞

**Comment by chenrui333** [comment]
rerun the build because 10.14 build somehow got skipped previously.

**Comment by chenrui333** [comment]
I will do the merge around lunch today.

**Comment by SMillerDev** [comment]
> The upstream git repository doesn't have an issue tracker, but they seem to be creating and moving the latest tag as part of the release process to test release candidates. 

Can you try and contact them regardless? Maybe tagging some maintainers here? The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do and it just causes a lot of trouble for everyone.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
Hi @rohininidhi or maybe @penmetsaa, 👋  we run into some libphonenumber audit check issue (since it got re-released?). Because there is no way for us to create an issue to track down on your side, I will tag you for clarifying the re-release is intentional for our better understanding the release process in general. Any feedback or comments are appreciated. Thanks!!

**Comment by chenrui333** [comment]
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.bintray.com:443 `

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @jeroen!!

**Comment by jeroen** [comment]
Thanks for your help! I think this issue shows that there is some room for improvement in the homebrew build process.

Perhaps the CI could automatically bump the required bottles, such that the PR is not constantly outdated/blocked due to other things changing at the same time.

**Pull request closed without merging**
