### PR TITLE
bandcamp-dl 0.0.8-11

### LINKED ISSUE #24855: Installing bandcamp-dl installs wrong version
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Installing [bandcamp-dl](https://github.com/Homebrew/homebrew-core/blob/b7e81b52d0578332569ca40c71754710746ba6be/Formula/bandcamp-dl.rb)
```
brew install bandcamp-dl
```
 installs `0.0.8-09`, not `0.0.8-10` as specified in formula. Installing with --HEAD option
```
brew install bandcamp-dl --HEAD
```
installs proper version.

### PR DESCRIPTION
**Pull request by nrlquaker**
Fix #24855

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nrlquaker** [comment]
Can someone help with tests please?
Files are downloading, but tests don't see them. Maybe some problem with path?

**Comment by ilovezfs** [comment]
@nrlquaker it's being caused by line 180 https://github.com/iheanyi/bandcamp-dl/commit/e8a016fc355dff920d13617a9ce034fdd01c5603#diff-b45ec36ac3245028fa568bb3c3da48c1R180 which now causes the test block not to function properly throwing `[Errno 25] Inappropriate ioctl for device`. It needs to be reported upstream.

**Comment by Evolution0** [comment]
I know what is causing this and its frustrating as its not actually an issue for the user only Jenkins and other automated testing. (It has to do with moving my calls to `sys.stdout.write()` to a separate function)

But as I know a lot of my users are on OSX I'll make some changes to fix this.

**Comment by Evolution0** [comment]
Latest release: iheanyi/bandcamp-dl/releases/tag/v0.0.8-11 Hopefully takes care of the Jenkins issue.

**Comment by ilovezfs** [comment]
@Evolution0 unfortunately it looks like it's still failing.

**Comment by ilovezfs** [comment]
@Evolution0 it looks like it's fine if you use `shutil.get_terminal_size` instead of `os.get_terminal_size`.

**Comment by Evolution0** [comment]
That would solve the permissions issue which tends to cause `[Errno 25] Inappropriate ioctl for device` as its higher level yes. I'll leave it as is though in the codebase as the `inreplace` in the formula does the job and its an incompatibility with Jenkins to begin with.

**Comment by ilovezfs** [comment]
Sorry we'll need a testable release. But thanks nonetheless @nrlquaker!

**Comment by Evolution0** [comment]
@nrlquaker Latest release now uses `shutil` now that its fixed upstream you can create a new PR.

**Comment by nrlquaker** [comment]
@Evolution0 thanks, I've opened #25067.

**Pull request closed without merging**
