### PR TITLE
Use https://deb.debian.org for all Debian mirrors

### PR DESCRIPTION
**Pull request by geofft**
deb.debian.org is a redirector service that will send you to either AWS
CloudFront or Fastly, both of which have official Debian mirrors. The
current choice of mirror appears to be somewhat ad-hoc; switch
everything to deb.debian.org and remove redundant mirror lines.

This commit was generated with

    find Formula -name \*.rb -exec sed -i "s|https\?://mirrors.ocf.berkeley.edu/debian|https://deb.debian.org/debian|" {} +
    find Formula -name \*.rb -exec sed -i "s|https\?://\(www\.\)\?mirrorservice.org/sites/ftp.debian.org/debian|https://deb.debian.org/debian|" {} +
    find Formula -name \*.rb -exec sed -i "s|https\?://mirrors.kernel.org/debian|https://deb.debian.org/debian|" {} +
    find Formula -name \*.rb -exec sed -i "s|https\?://ftp.de.debian.org/debian|https://deb.debian.org/debian|" {} +
    git grep --files-with-match 'url "https://deb.debian.org' | xargs sed -i '/mirror "https:\/\/deb.debian.org/d'

plus manual fixes to ldapvi, mytop, and toilet, which reference multiple
tarballs in the same file and broke my naive regexes.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by geofft** [comment]
There is an HTTPS server at https://deb.debian.org which will send you a redirect to either AWS or Fastly. There are also SRV records for deb.debian.org, and new versions of apt look at that and skip the redirector server.

If we don't trust the redirector server to be as highly available as AWS and Fastly themselves (which is probably reasonable), another option is to have all the formulas do

    url "https://cdn-aws.deb.debian.org/debian/..."
    mirror "https://cdn-fastly.deb.debian.org/debian/..."

which relies only on Debian DNS + the third-party services. But it does hard-code the list of services in the formulas. I'm not sure which is preferable.

**Comment by DomT4** [comment]
> The current choice of mirror appears to be somewhat ad-hoc

We intentionally chose those two mirrors over a period because they seem to be high-capacity & incredibly reliable, which are both nice things when it comes to package management, heh.

Does this _always_ redirect to a HTTPS mirror? That was the other intention here originally, that we weren't fetching _anything_ over plaintext when it comes to Debian links at least.

**Comment by geofft** [comment]
> We intentionally chose those two mirrors over a period because they seem to be high-capacity & incredibly reliable, which are both nice things when it comes to package management, heh.

Well, there's four. :) Maybe getting it to two just requires fixing a couple of formulas?

> Does this _always_ redirect to a HTTPS mirror? That was the other intention here originally, that we weren't fetching anything over plaintext when it comes to Debian links at least.

Yes, or, at the least, the next version of apt will be enforcing HTTPS [and will reject redirects from HTTPS to HTTP](https://lists.debian.org/debian-devel/2017/06/msg00381.html), so I don't expect an official Debian service to start sending redirects that break apt.

**Comment by JCount** [comment]
CI killed since this PR would make it build 128 formulae.

**Comment by DomT4** [comment]
> Well, there's four. :)

Yeah. The standardisation has been a gradual thing rather than a one-and-done deal. There is some [minor nudging](https://github.com/Homebrew/brew/blob/2b3717a5a0452271bb7dcfcdfa2680714ac99c2a/Library/Homebrew/dev-cmd/audit.rb#L1411-L1420) in terms of URL usage around Debian _(which would likely need to be tweaked or scrapped if this PR went in)_ but it's not broad enough to capture absolutely everything.

As long as we're not suddenly pushing HTTP onto people when we've been using secure links for all Debian stuff for quite some time now I'm cool with the idea _personally_, but it's down to ILZ/JCount/etc. I stuck my neck in here because I helped tweak a lot of the Debian handling whilst I was part of the team & I was curious 😄.

**Comment by ilovezfs** [comment]
Passing on this for now but thanks for the PR nonetheless.

**Pull request closed without merging**
