### PR TITLE
libgosu 0.11.3.1

### PR DESCRIPTION
**Pull request by bfontaine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
We already rejected doing this.

https://github.com/Homebrew/homebrew-core/pull/11978

**Comment by ilovezfs** [comment]
https://github.com/gosu/gosu/issues/396

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/11979

**Comment by bfontaine** [comment]
Thanks @ilovezfs.

**Pull request closed without merging**
