### PR TITLE
terraform 0.7.7

### PR DESCRIPTION
**Pull request by bsiegel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by idris — APPROVED** [review]

**Comment by brianknight10** [comment]
Is the build failure due to an actual issue or an issue on the build box?

**Comment by cblecker** [comment]
The `github.com/hashicorp/terraform/builtin/providers/azurerm` test seems to have failed. There have been some changes to this code since v0.7.6, so it's possible there is something that is failing to build on Sierra that built cleanly on the last version.

Is it possible to get a CI-requeue to see if it'll build cleanly? If not, then we might need to dig into why it's panicking when running the test suite.

**Comment by mengesb** [comment]
I have sierra installed and I'm using the vagrant/docker setup in the repo. I ran the tests there and all passed:

```
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make
==> Checking that code complies with gofmt requirements...
==> Checking AWS provider for unchecked errors...
==> NOTE: at this time we only look for uncheck errors in the AWS package
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/18 23:30:22 Generated command/internal_plugin_list.go
TF_ACC= go test $(go list ./... | grep -v '/terraform/vendor/' | grep -v '/builtin/bins/')  -timeout=30s -parallel=4
ok  	github.com/hashicorp/terraform	0.017s
ok  	github.com/hashicorp/terraform/builtin/providers/archive	0.013s
ok  	github.com/hashicorp/terraform/builtin/providers/atlas	0.021s
ok  	github.com/hashicorp/terraform/builtin/providers/aws	1.718s
ok  	github.com/hashicorp/terraform/builtin/providers/azure	0.016s
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	6.834s
ok  	github.com/hashicorp/terraform/builtin/providers/bitbucket	0.006s
ok  	github.com/hashicorp/terraform/builtin/providers/chef	0.006s
ok  	github.com/hashicorp/terraform/builtin/providers/clc	0.006s
ok  	github.com/hashicorp/terraform/builtin/providers/cloudflare	0.009s
ok  	github.com/hashicorp/terraform/builtin/providers/cloudstack	0.009s
ok  	github.com/hashicorp/terraform/builtin/providers/cobbler	0.014s
ok  	github.com/hashicorp/terraform/builtin/providers/consul	0.011s
ok  	github.com/hashicorp/terraform/builtin/providers/datadog	0.010s
ok  	github.com/hashicorp/terraform/builtin/providers/digitalocean	0.009s
ok  	github.com/hashicorp/terraform/builtin/providers/dme	0.008s
ok  	github.com/hashicorp/terraform/builtin/providers/dnsimple	0.008s
ok  	github.com/hashicorp/terraform/builtin/providers/docker	0.006s
ok  	github.com/hashicorp/terraform/builtin/providers/dyn	0.006s
ok  	github.com/hashicorp/terraform/builtin/providers/fastly	0.011s
ok  	github.com/hashicorp/terraform/builtin/providers/github	0.007s
ok  	github.com/hashicorp/terraform/builtin/providers/google	0.020s
ok  	github.com/hashicorp/terraform/builtin/providers/grafana	0.018s
ok  	github.com/hashicorp/terraform/builtin/providers/heroku	0.017s
ok  	github.com/hashicorp/terraform/builtin/providers/influxdb	0.005s
ok  	github.com/hashicorp/terraform/builtin/providers/librato	0.008s
ok  	github.com/hashicorp/terraform/builtin/providers/logentries	0.007s
?   	github.com/hashicorp/terraform/builtin/providers/logentries/expect	[no test files]
ok  	github.com/hashicorp/terraform/builtin/providers/mailgun	0.013s
ok  	github.com/hashicorp/terraform/builtin/providers/mysql	0.008s
ok  	github.com/hashicorp/terraform/builtin/providers/null	0.005s
ok  	github.com/hashicorp/terraform/builtin/providers/openstack	0.009s
ok  	github.com/hashicorp/terraform/builtin/providers/packet	0.071s
ok  	github.com/hashicorp/terraform/builtin/providers/postgresql	0.006s
ok  	github.com/hashicorp/terraform/builtin/providers/powerdns	0.017s
ok  	github.com/hashicorp/terraform/builtin/providers/rabbitmq	0.010s
ok  	github.com/hashicorp/terraform/builtin/providers/random	0.008s
ok  	github.com/hashicorp/terraform/builtin/providers/rundeck	0.007s
ok  	github.com/hashicorp/terraform/builtin/providers/scaleway	0.018s
ok  	github.com/hashicorp/terraform/builtin/providers/softlayer	0.006s
ok  	github.com/hashicorp/terraform/builtin/providers/statuscake	0.013s
ok  	github.com/hashicorp/terraform/builtin/providers/template	0.236s
ok  	github.com/hashicorp/terraform/builtin/providers/terraform	0.091s
ok  	github.com/hashicorp/terraform/builtin/providers/test	0.541s
ok  	github.com/hashicorp/terraform/builtin/providers/tls	0.020s
ok  	github.com/hashicorp/terraform/builtin/providers/triton	0.032s
ok  	github.com/hashicorp/terraform/builtin/providers/ultradns	0.032s
ok  	github.com/hashicorp/terraform/builtin/providers/vcd	0.018s
ok  	github.com/hashicorp/terraform/builtin/providers/vsphere	0.012s
ok  	github.com/hashicorp/terraform/builtin/provisioners/chef	0.018s
ok  	github.com/hashicorp/terraform/builtin/provisioners/file	0.008s
ok  	github.com/hashicorp/terraform/builtin/provisioners/local-exec	0.020s
ok  	github.com/hashicorp/terraform/builtin/provisioners/remote-exec	0.010s
ok  	github.com/hashicorp/terraform/command	0.683s
ok  	github.com/hashicorp/terraform/communicator	0.006s
ok  	github.com/hashicorp/terraform/communicator/remote	0.004s
ok  	github.com/hashicorp/terraform/communicator/shared	0.029s
ok  	github.com/hashicorp/terraform/communicator/ssh	0.018s
ok  	github.com/hashicorp/terraform/communicator/winrm	0.038s
ok  	github.com/hashicorp/terraform/config	0.112s
ok  	github.com/hashicorp/terraform/config/module	0.032s
ok  	github.com/hashicorp/terraform/dag	0.042s
ok  	github.com/hashicorp/terraform/digraph	0.003s
?   	github.com/hashicorp/terraform/dot	[no test files]
ok  	github.com/hashicorp/terraform/flatmap	0.013s
?   	github.com/hashicorp/terraform/helper/acctest	[no test files]
ok  	github.com/hashicorp/terraform/helper/config	0.023s
?   	github.com/hashicorp/terraform/helper/copy	[no test files]
ok  	github.com/hashicorp/terraform/helper/diff	0.019s
ok  	github.com/hashicorp/terraform/helper/hashcode	0.002s
?   	github.com/hashicorp/terraform/helper/hilmapstructure	[no test files]
?   	github.com/hashicorp/terraform/helper/logging	[no test files]
ok  	github.com/hashicorp/terraform/helper/mutexkv	0.053s
ok  	github.com/hashicorp/terraform/helper/pathorcontents	0.009s
ok  	github.com/hashicorp/terraform/helper/resource	1.929s
ok  	github.com/hashicorp/terraform/helper/schema	0.025s
ok  	github.com/hashicorp/terraform/helper/signalwrapper	0.025s
ok  	github.com/hashicorp/terraform/helper/validation	0.006s
ok  	github.com/hashicorp/terraform/plugin	0.070s
ok  	github.com/hashicorp/terraform/scripts	0.591s
ok  	github.com/hashicorp/terraform/state	0.048s
ok  	github.com/hashicorp/terraform/state/remote	1.257s
ok  	github.com/hashicorp/terraform/terraform	1.341s
go tool vet -all .
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ logout
Connection to 127.0.0.1 closed.
```

**Comment by brianknight10** [comment]
Perhaps make a cosmetic change to re-kick the build?

**Comment by bsiegel** [comment]
> Perhaps make a cosmetic change to re-kick the build?

Re-kicked

**Comment by mengesb** [comment]
Weeee! Passes!

**Review by cblecker — APPROVED** [review]
LGTM

**Comment by bsiegel** [comment]
Looks like possibly the bottle failed to build? I'm getting this:

```
==> Downloading https://homebrew.bintray.com/bottles/terraform-0.7.7.el_capitan.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
```

**Comment by cblecker** [comment]
@bsiegel --
That's because this hasn't been merged. You can fix your local repo with:
```
cd $(brew --repo)/Library/Taps/homebrew/homebrew-core/
git checkout master
git reset HEAD --hard
```

**Comment by bsiegel** [comment]
> @bsiegel --
> That's because this hasn't been merged (yet). You can fix your local repo with:

D'oh, thanks :) My brew auto-update kicked in this morning and I had forgotten that I was still on that branch. /gif shame

**Comment by apjanke** [comment]
Merged (and undid the cosmetic change). Thank you for your contribution to Homebrew!

**Pull request closed without merging**
