### PR TITLE
clarinet 1.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Not sure why [the other PR](https://github.com/Homebrew/homebrew-core/pull/130619) builds always queueing, creating this fresh PR to give another try

**Comment by hugocaillard** [comment]
@chenrui333 We can close this PR. New version 1.6.1 on the way.

Thanks for your help

**Comment by hugocaillard** [comment]
Hey @chenrui333,
Can we close this PR please? It's blocking the release of 1.6.1 with
```
Error: These open pull requests may be duplicates:
clarinet 1.6.0 https://github.com/Homebrew/homebrew-core/pull/130963
Duplicate PRs should not be opened. Use --force to override this error.
```

(or @SMillerDev if you're around)

Thank you!

**Comment by chenrui333** [comment]
> Hey @chenrui333, Can we close this PR please? It's blocking the release of 1.6.1 with
> 
> ```
> Error: These open pull requests may be duplicates:
> clarinet 1.6.0 https://github.com/Homebrew/homebrew-core/pull/130963
> Duplicate PRs should not be opened. Use --force to override this error.
> ```
> 
> (or @SMillerDev if you're around)
> 
> Thank you!

`--force` is fine, thanks for the new PR.

**Comment by hugocaillard** [comment]
Ah! I didn't have access to submit the PR but got some help from a colleague! Thanks for closing this one

**Comment by chenrui333** [comment]
#131430

**Pull request closed without merging**
