### PR TITLE
redis 6.0.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
lgtm

**Comment by chenrui333** [comment]
Thanks @dtrodrigues!

**Comment by dmlittle** [comment]
Thoughts on adding an option to the formula to all you to build Redis with the [`BUILD_TLS` flag](https://github.com/antirez/redis/blob/unstable/TLS.md)?

**Comment by Bo98** [comment]
We don’t accept options, but you could propose to have it enabled by default. That’s assuming there isn’t any particular reason why upstream don’t enable it by default.

**Pull request closed without merging**
