### PR TITLE
gcc@11: do not strip on macOS

### LINKED ISSUE #106394: GCC 12.1 missing symbol when loading plugin
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config

HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b18dae855942fc9b75ff9741e395481416390433
Core tap last commit: 23 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit penryn
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
```

```
% brew info gcc

gcc: stable 11.3.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb
License: GPL-3.0-or-later with GCC-exception-3.1
==> Dependencies
Required: gmp, isl, libmpc, mpfr, zstd
==> Options
--HEAD
	Install HEAD version
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am attempting to build and load a GCC plugin (it is part of the ODB compiler project).

### What happened (include all command output)?

Everything builds fine but when I attempt to load the plugin, I get this diagnostics:

```
cc1plus: error: cannot load plugin /private/tmp/build-host/odb-2.5.0-b.22.20220718100540.58b7c3add166/odb/odb.so: dlopen(/private/tmp/build-host/odb-2.5.0-b.22.20220718100540.58b7c3add166/odb/odb.so, 0x000A): symbol not found in flat namespace (__Z10pragma_lexPP9tree_nodePj)
```

This only appear to happen with GCC 12.1. I have a build with GCC 11.2 which builds and loads without any problem. To be exact, the GCC 11.2 was also installed from the bottle but on Mac OS 11, not 12. If it helps, I can try to install the latest GCC 11 on exactly the  same machine to confirm, but I am pretty sure it works (I tried GCC 11.3 on an M1 machine, and it does load without any problems).

Also, another piece of information: the same ODB plugin builds and loads fine on Linux with GCC 12.1.

Let me know if you need me to run any commands or provide any additional information.

### What did you expect to happen?

I expected there to be no missing symbols, just like with the previous version of GCC on Mac OS or with this version of GCC on Linux.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# The only brew command involved was installing GCC 12.1:

brew install gcc@12
```

### PR DESCRIPTION
**Pull request by fxcoudert**
Fix https://github.com/Homebrew/homebrew-core/issues/106394 on gcc 11 as well.

### CODE REVIEW

**Comment by carlocab** [comment]
Should do this with #110779 to avoid doubling up on CI runs.

**Comment by carlocab** [comment]
Build fails, presumably due to the Xcode 14 bug.

We probably should've built this first before upgrading...

**Comment by boris-kolpackov** [comment]
I am still interesting in seeing this merged.

**Comment by fxcoudert** [comment]
So are we. But right now, we cannot build with Xcode 14 due to the linker bug, so it will have to wait until Xcode 14.1 is released and we update it on our CI machines.

**Pull request closed without merging**
