### PR TITLE
jing-trang fix #53099

### LINKED ISSUE #53099: jing-trang should install dependent .jar files to build directory or symlink them
The jing-trang formula installs the files `jing.jar` and `trang.jar` to `/usr/local/Cellar/jing-trang/20181222/libexec/build`, and the dependent jars to `/usr/local/Cellar/jing-trang/20181222/libexec/lib`. However, `jing.jar:META-INF/MANIFEST.MF` sets a Class-Path that references the dependent jar files from that same directory, so they aren't found when jing.jar is launched as an executable jar file. This restricts jing's functionality and may lead to spurious errors, like because jing will be using Java's bundled and buggy XSLT processor instead of Saxon's. See, eg, https://github.com/relaxng/jing-trang/issues/257. 

The formula should either install all .jar files to libexec/build or symlink all .jar files from libexec/lib to libexec/build.

# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
-- Error: No logs.
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

$ brew config
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2a5aa6f9218fc8c50c8f1a9716ef5c2751552028
Core tap last commit: 71 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.…/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.6, 1.8.0_242
macOS: 10.15.4-x86_64
CLT: 11.0.33.17
Xcode: 11.4
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gnupg

## What you were trying to do (and why)

Running Jing to do a Schematron validation (see https://github.com/relaxng/jing-trang/issues/257)

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
ERROR:  'Namespace for prefix 't' has not been declared.'
fatal: exception "java.lang.RuntimeException" thrown: Namespace for prefix 't' has not been declared.  </pre>
</details>

## What you expected to happen

The Schematron should have worked. It does if you symlink the dependent .jar files from the libexec/lib to the libexec/build folder.

## Step-by-step reproduction instructions (by running `brew install` commands)

$ brew install jing-trang
$ jing test.sch test.xml

### PR DESCRIPTION
**Pull request by tsteven4**
This fixes the issue identified in #53099.
This fix follows the suggestion to update the classpath of jing and trang instead of installing the depenedent .jar files to the build directory or symlinking them.
As a result of this chang jing can validate against schematron schema. Without this fix a fatal error is returned:
% jing http://docs.oasis-open.org/docbook/xml/5.0/sch/docbook.sch xmldoc/readme.xml
ERROR:  'Namespace for prefix 'db' has not been declared.'

- [X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by tsteven4** [comment]
Thanks for the question.

The upstream packaging creates a zip file with the dependent jars in the same directory as jing.jar and trang.jar.  The upstream packaging sets the class path in the manifest for jing.jar and trang.jar to look in that directory. 

In contrast, homebrew installs the dependent jars in a different directory. 

This patch just changes the manifest to point to the directory where homebrew actually installs the dependent jars, as was suggested by you here: https://github.com/Homebrew/homebrew-core/issues/53099#issuecomment-613348631

**Comment by SMillerDev** [comment]
But all the files are in libexec. It really seems like it's looking in the directory the files are called from instead of the directory they are located, which could be upstreamed.

**Comment by tsteven4** [comment]
The way the homebrew install works the jars are all under libexec, but not in the same subdirectory.  The dependent jars are in libexec/lib while the jars with the main entry points are in libexec/build.

The way upstream works is by creating a zip file with a different directory structure that has the dependent jars and the jars with the main class all in the same directory.  Homebrew hasn't attempted to mimic that zip file structure, instead it just copies the source tree (libexec.install Dir["*"]).

Perhaps it is preferable to let the upstream build process create the zip file and just unzip it into libexec.  Then homebrew wouldn't need to change the classpath in the mainfests.

Cellar % find jing-trang/20220510/libexec -name "*.jar"
jing-trang/20220510/libexec/lib/saxon9.jar
jing-trang/20220510/libexec/lib/serializer.jar
jing-trang/20220510/libexec/lib/xalan.jar
jing-trang/20220510/libexec/lib/resolver.jar
jing-trang/20220510/libexec/lib/ant.jar
jing-trang/20220510/libexec/lib/ant-googlecode.jar
jing-trang/20220510/libexec/lib/ant-nodeps.jar
jing-trang/20220510/libexec/lib/doccheck.jar
jing-trang/20220510/libexec/lib/javacc.jar
jing-trang/20220510/libexec/lib/testng.jar
jing-trang/20220510/libexec/lib/isorelax.jar
jing-trang/20220510/libexec/lib/ant-trax.jar
jing-trang/20220510/libexec/lib/ant-launcher.jar
jing-trang/20220510/libexec/lib/xml-apis.jar
jing-trang/20220510/libexec/lib/xercesImpl.jar
jing-trang/20220510/libexec/lib/maven-ant-tasks-2.1.3.jar
jing-trang/20220510/libexec/build/dtdinst.jar
jing-trang/20220510/libexec/build/trang.jar
jing-trang/20220510/libexec/build/jing.jar

**Comment by SMillerDev** [comment]
So how is upstream making their zip? The formula is running `ant ant-jar` which creates this structure that is apparently broken.

**Comment by tsteven4** [comment]
upstream builds different ant targets to create the zip files.  They use the build targets jing-dist and trang-dist, which depend on the build target ant-jar.  The jing-dist target moves the dependent jars to the location expected by the classpath created in the ant-jar target.

To use the upstream distribution files we could do something like:

```   
    system "./ant", "jing-dist"
    system "./ant", "trang-dist"
    system "unzip", "-o", "-d", "build/dist", "build/dist/jing-#{version}.zip"
    system "unzip", "-o", "-d", "build/dist", "build/dist/trang-#{version}.zip"
    libexec.install Dir["build/dist/jing-#{version}"]
    libexec.install Dir["build/dist/trang-#{version}"]
    bin.write_jar_script libexec/"jing-#{version}/bin/jing.jar", "jing", java_version: "11"
    bin.write_jar_script libexec/"trang-#{version}/trang.jar", "trang", java_version: "11"
```

**Comment by SMillerDev** [comment]
Is there an ant target that doesn't zip the distribution build? Otherwise I think your suggestion is a good option.

**Comment by tsteven4** [comment]
> Is there an ant target that doesn't zip the distribution build?

No, there is not.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
