### PR TITLE
workflows/autolabel: add gopath deprecation

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds `gopath deprecation` label if any occurrences of `"GOPATH"` (including `"`) are found in modified formulae

Related: #47627

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
👍🏻 but could you explain how this will be used?

**Comment by Bo98** [comment]
The [motiviation](https://github.com/Homebrew/homebrew-core/issues/47627) for deprecating `GOPATH` is because we should be preferring Go modules. My only concern is that some formulae still use `GOPATH` because upstream aren't using Go modules yet. I'm not aware of plans to deprecate using `GOPATH` for such formulae, but maybe I've missed some discussion here.

**Comment by SeekingMeaning** [comment]
> My only concern is that some formulae still use `GOPATH` because upstream aren't using Go modules yet. I'm not aware of plans to deprecate using `GOPATH` for such formulae, but maybe I've missed some discussion here.

Perhaps I'm wrong, my assumption is that we add `gopath deprecation` to any PRs that use `GOPATH` and then remove `GOPATH` if possible

**Comment by dawidd6** [comment]
I think we add `gopath deprecation` label only if it is possible and doable to deprecate.

**Comment by dawidd6** [comment]
@BrewTestBot decided 😄

**Comment by SeekingMeaning** [comment]
Whoops, should have added a DNM tag

**Comment by MikeMcQuaid** [comment]
> I think we add `gopath deprecation` label only if it is possible and doable to deprecate.

👍🏻 to this from me. I know this was already reverted but this seems like the type of thing worth doing manually. I like the initiative though, thanks @SeekingMeaning and all for conversation!

**Pull request closed without merging**
