### PR TITLE
ghc: fix llc process leak

### PR DESCRIPTION
**Pull request by Bo98**
This causes long builds on Apple Silicon to eventually exhaust the process limit.

We should consider a plan of action for migrating to GHC 9. It appears 8.10 isn't receiving new updates.

But since I don't expect GHC 9 migration to happen overnight, let's try fix 8.10 until then - this bug has more than enough taken a lot of maintainer time to figure out over the last few months.

### CODE REVIEW

**Comment by carlocab** [comment]
@fishtreesugar has been trying to get us migrated, but needs some help/direction.

**Comment by Bo98** [comment]
Ah great, glad to hear there was some movement.

Is the effort so far documented anywhere? I appear to have been completely unaware.

**Comment by carlocab** [comment]
There's https://github.com/Homebrew/homebrew-core/pull/92258 and https://github.com/Homebrew/homebrew-core/pull/97309.

**Comment by Bo98** [comment]
Will need to investigate why Linux linkage is all broken. This isn't even a version bump.

**Comment by cho-m** [comment]
I'm guessing the Cellar paths in conf files are used in RPATH, 
e.g. in `lib/ghc-8.10.7/package.conf.d/array-0.5.4.0.conf`
```
import-dirs:
    @@HOMEBREW_CELLAR@@/ghc/8.10.7_1/lib/ghc-8.10.7/array-0.5.4.0

library-dirs:
    @@HOMEBREW_CELLAR@@/ghc/8.10.7_1/lib/ghc-8.10.7/array-0.5.4.0

dynamic-library-dirs:
    @@HOMEBREW_CELLAR@@/ghc/8.10.7_1/lib/ghc-8.10.7/array-0.5.4.0
```

In `cedille`, the binary in `bin/cedille-core` has RPATH:
```
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/directory-1.3.6.0
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/unix-2.7.2.2
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/bytestring-0.10.12.0
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/time-1.9.3
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/filepath-1.4.2.1
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/deepseq-1.4.4.0
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/array-0.5.4.0
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/base-4.14.3.0
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/integer-gmp-1.0.3.0
@@HOMEBREW_PREFIX@@/opt/gmp/lib
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/ghc-prim-0.6.1
@@HOMEBREW_PREFIX@@/Cellar/ghc/8.10.7_1/lib/ghc-8.10.7/rts
@@HOMEBREW_PREFIX@@/Cellar/cedille/1.1.2_4/lib
@@HOMEBREW_PREFIX@@/lib
@@HOMEBREW_PREFIX@@/opt/ncurses/lib
@@HOMEBREW_PREFIX@@/opt/ghc/lib
```

**Comment by fishtreesugar** [comment]
https://github.com/haskellfoundation/tech-proposals/pull/34 states
>  * GHC 9.2 is still young but the GHC developers are currently planning on supporting it into 2023.

and according to stackage nightly https://www.stackage.org/nightly-2022-05-28, GHC 9.2.x got quite a lot of adoptions

I think homebrew could skip 9.0 and jump to 9.2 series

**Comment by Bo98** [comment]
> I think homebrew could skip 9.0 and jump to 9.2 series

I agree.

There is still some work to do here to stop having Cellar paths everywhere, which doesn't have to be a part of the GHC 9 update but can be if it's easier.

**Comment by fishtreesugar** [comment]
I am not familiar with linking staff, may this link helps https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6003

**Pull request closed without merging**
