### PR TITLE
mit-scheme: Use x64 binaries instead of svm1

### LINKED ISSUE #52925: mit-scheme uses svm1 instead of x86_64
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [formula succeeded] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install a library ([scmutils](http://groups.csail.mit.edu/mac/users/gjs/6946/installation.html)) for mit-scheme.

## What happened (include command output)

I got an architecture not supported error: 
https://lists.gnu.org/archive/html/mit-scheme-devel/2020-04/msg00003.html

<details>
  <summary>Command output</summary>
  <pre>

```
~/D/scmutils-20190830 ❯❯❯ ls
COPYING       calculus      general       mechanics     numerics      solve
INSTALL       display       install.sh    mechanics.com poly          uninstall.sh
README        enclose       kernel        mechanics.sh  simplify      units
~/D/scmutils-20190830 ❯❯❯ export MITSCHEME_HEAP_SIZE=100000
export MITSCHEME_BAND=mechanics.com
~/D/scmutils-20190830 ❯❯❯ mit-scheme
MIT/GNU Scheme running under OS X
Type `^C' (control-C) followed by `H' to obtain information about interrupts.


Bad compiled-code version in FASL File: /usr/local/Cellar/mit-scheme/10.1.10/lib/mit-scheme-svm1/mechanics.com
File has: compiled-code interface 3; architecture 14.
Expected: compiled-code interface 3; architecture 13.

Microcode Error: No error handlers.
Error code 0x3a (fasload-compiled-mismatch).

**** Stack Trace ****

{0x119273fb8}
    Return code: [return-code pop-return-error]
    _expression_: #F
{0x119273fc8}
    Return code: [return-code internal-apply]
    _expression_: #F
{0x119273fd8}  ...: [false 0x2]
{0x119273fe0}  ...: [primitive LOAD-BAND]
{0x119273fe8}  ...: "/usr/local/Cellar/mit-scheme/10.1.10/lib/mit-scheme-svm1/mechanics.com"
{0x119273ff0}
    Return code: [return-code non-existent-continuation]
    _expression_: #F

No error handler.
~/D/scmutils-20190830 ❯❯❯
```

  </pre>
</details>

## What you expected to happen
Have mit-scheme libraries compiled for x86_64 work on my x86_64 machine (or have an option to select the native architecture). 

This is how that is supposed to run:
```
MIT/GNU Scheme running under OS X
Type `^C' (control-C) followed by `H' to obtain information about interrupts.

Copyright (C) 2019 Massachusetts Institute of Technology
This is free software; see the source for copying conditions. There is NO warranty; not even for
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Image saved on Friday August 30, 2019 at 11:20:36 PM
  Release 10.1.10                || Microcode 15.3 || Runtime 15.7 || SF 4.41 || LIAR/x86-64 4.118
  SOS 1.8                        || XML 1.0        || Edwin 3.117  || X11 1.3 || X11-Screen 1.0
  ScmUtils Mechanics.Summer 2019

1 ]=> (edit)

```
## Step-by-step reproduction instructions (by running `brew install` commands)

brew install mit-scheme
wget http://groups.csail.mit.edu/mac/users/gjs/6946/scmutils-20190830.tar.gz
tar xvf scmutils-20190830.tar.gz
cd scmutils-20190830
./install.sh
./mechanics.sh

### PR DESCRIPTION
**Pull request by duncanmak**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This resolves https://github.com/Homebrew/homebrew-core/issues/52925, by following the instructions outlined [here](https://github.com/Homebrew/homebrew-core/issues/52925#issuecomment-612570752).

This patch is patterned after the Rust formula, as suggested [here](https://github.com/Homebrew/homebrew-core/issues/52925#issuecomment-612590131).

Audit currently fails because of I changed the source from the svm1 bundle to the plain source bundle:
```
$ brew audit --strict mit-scheme
mit-scheme:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/mit-scheme-x86-64/runtime.com
      lib/mit-scheme-x86-64/all.com
```

Using my local build, I see that I'm not using svm1 anymore:
```
Image saved on Friday May 22, 2020 at 5:26:53 PM
  Release 10.1.10 || Microcode 15.3 || Runtime 15.7 || SF 4.41 || LIAR/x86-64 4.118
```

Whereas the current bottle shows:
```
Image saved on Saturday August 10, 2019 at 7:30:42 PM
  Release 10.1.10 || Microcode 15.3 || Runtime 15.7 || SF 4.41 || CREF 2.6 || LIAR/svm1 4.118
```

### CODE REVIEW

**Comment by duncanmak** [comment]
@Bo98 - I made this PR per the conversation in #52925, but it's stuck because of `audit --strict` failing.
```
mit-scheme:
  * Stable: version 10.1.10 is redundant with version scanned from URL
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

What do I do to clear that?

Thanks!

**Comment by jonchang** [comment]
Just remove the `version` line. We can ignore the hash change audit in this case.

**Comment by duncanmak** [comment]
There are 2 more issues that's causing audit to fail:

```
* stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```
I dunno how to clear this one.
```
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/mit-scheme-x86-64/runtime.com
      lib/mit-scheme-x86-64/all.com
```
These files contain some paths, but they are harmless - the [prebuilt binaries on the site}(http://ftp.gnu.org/gnu/mit-scheme/stable.pkg/10.1.10/mit-scheme-10.1.10-x86-64.dmg) contains this:

```
$ strings /Applications/MIT\:GNU\ Scheme\ 10.1.10.app/Contents/Resources/all.com | grep cph | wc -l
     201
$ strings /Applications/MIT\:GNU\ Scheme\ 10.1.10.app/Contents/Resources/all.com | grep cph | head -5
t/home/cph/Software/release-10.1.10/mit-scheme-10.1.10/src/lib/all.com
tcph
tfile:/home/cph/Software/release-10.1.10/mit-scheme-10.1.10/src/sf.so
tfile:/home/cph/Software/release-10.1.10/mit-scheme-10.1.10/src/lib/sf/make
tfile:/home/cph/Software/release-10.1.10/mit-scheme-10.1.10/src/lib/optiondb.so
```

**Comment by duncanmak** [comment]
@jonchang Is there anything I can to do to get this PR to move along?

**Comment by chenrui333** [comment]
Closing this PR in favor of the new one.

**Pull request closed without merging**
