### PR TITLE
infracost 0.10.20

### PR DESCRIPTION
**Pull request by aliscott**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not marked as the latest release yet: https://github.com/infracost/infracost/releases. Is this ready for distribution, @aliscott?

**Comment by chenrui333** [comment]
I think they just forgot to mark the draft release to the latest release. 😅

**Comment by hugorut** [comment]
Hey @ZhongRuoyu / @chenrui333, sorry for the slow movement on this. We've published 0.10.20 release now.

**Comment by ZhongRuoyu** [comment]
Thanks @hugorut!

**Review by ZhongRuoyu — DISMISSED** [review]

**Pull request merged**
