### PR TITLE
aws-google-auth 0.0.34

### PR DESCRIPTION
**Pull request by angusfretwell**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by stephenrjohnson** [comment]
Any chance we can get this merge, it's causing major issues with people not being able to login.

**Comment by SMillerDev** [comment]
Yes, as soon as a maintainer has time to review it. We're all volunteers here, I'd suggest putting your efforts towards helping upstream improve their CI instead of trying to hurry homebrew maintainers.

**Comment by stephenrjohnson** [comment]
A+ engagement with the users, the issue is google has made a change to the login page, so it's now failing. I'm poking this to let the homebrew maintainers know this affect quite a few users. I'm leaving this thread now as it's becoming toxic.

**Comment by metersk** [comment]
> Interesting engagement with the users, the issue is google has made a change to the login page, so it's now failing. I'm poking this to let the homebrew maintainers know this affect quite a few users. I'm leaving this thread now as it's becoming toxic.

**Pull request closed without merging**
