### PR TITLE
gsl 2.7.1

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
What happened here?  😕

**Comment by carlocab** [comment]
You need to bump the `revision`s of the linkage failures. You can do this by checking out your PR branch and doing
```
brew bump-revision --message="(gsl 2.7.1)" \
asymptote \
bcftools \
dieharder \
nco \
nest \
flowgrind \
oscats \
root \
siril \
qsoas \
astrometry-net \
gnuradio
```

**Comment by pthariensflame** [comment]
@carlocab Done!

**Comment by carlocab** [comment]
Killing the Big Sur and Catalina tests for now to free up the CI queue.

**Comment by pthariensflame** [comment]
I am once again stumped.

**Comment by pthariensflame** [comment]
Someone add `help wanted` here too, please?

**Comment by iMichka** [comment]
Fix for `oscats` in #92397

**Comment by iMichka** [comment]
Rebased

**Comment by iMichka** [comment]
`root` fails to build now:
```
While building module 'Core':
While building module 'std' imported from input_line_1:1:
In file included from <module-includes>:31:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/complex.h:28:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/ccomplex:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/complex:245:
/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:321:9: error: missing '#include <math.h>'; declaration of 'signbit' must be imported from module 'std.depr.math_h' before it is required
using ::signbit;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/math.h:329:1: note: previous declaration is here
signbit(_A1 __lcpp_x) _NOEXCEPT
^
input_line_1:1:10: fatal error: could not build module 'std'
#include <new>
 ~~~~~~~~^
```

**Comment by pthariensflame** [comment]
Wat.

**Comment by iMichka** [comment]
I'm running a separate `root` test build here: #92497
Looks related to https://github.com/root-project/root/issues/7881

**Comment by iMichka** [comment]
Fix for `dieharder`: #92808

`qsoas` issue looks transitient

**Comment by iMichka** [comment]
I had to disable `dieharder` as we need to rev bump it, but CI can't download the sources, so the project falls into the "does not build anymore" category to me.

**Comment by iMichka** [comment]
I opened an issue upstream: https://github.com/fourmond/QSoas/issues/2

Giving upstream a few days to respond, but might need to disable `qsoas`: it does not build anymore on 10.15/11, and does not build on macOS 12 either. The download counts are very low too.

**Comment by iMichka** [comment]
I have a fix for qsoas: #93798

**Comment by iMichka** [comment]
`dynare` and `gnuradio` need a rev-bump. l'll trigger a new build as soon as we enough CI available.

**Review by carlocab — COMMENTED** [review]
`dynare` and `gnuradio` also need `revision` bumps. Will get to it when the other long timeout jobs finish.

**Comment by iMichka** [comment]
Had to rebase because `nest` got updated yesterday.

**Review by carlocab — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
