### PR TITLE
caddy 0.9.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍 unless resources need an update.

**Comment by maletor** [comment]
How do we add middleware/directives into this? For instance, to add `cors`?

**Comment by ilovezfs** [comment]
@maletor Can you elaborate please? I don't think I understand your question yet.

**Comment by ilovezfs** [comment]
@DomT4 I swear I want to boneyard everything that doesn't vendor its go resources. LOL

**Comment by DomT4** [comment]
I'm pretty sure one day Go will get there for us the glorious way things are going 🙏. Given the significant upsides to vendoring it's somewhat bemusing there are still so many holdouts.

**Comment by ilovezfs** [comment]
I'm wondering if we should start filing issues against every go formula that doesn't vendor.

**Comment by DomT4** [comment]
It's tempting. It's certainly a usability issue on our side of the deal, things that don't vendor are more intensive to maintain & more prone to breaking.

**Comment by ilovezfs** [comment]
As the saying goes: if you don't ask, you don't get.

**Pull request closed without merging**
