### PR TITLE
openjdk 18.0.1.1

### PR DESCRIPTION
**Pull request by SMillerDev**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Created https://github.com/armedbear/abcl/issues/487 for abcl

**Comment by SMillerDev** [comment]
@carlocab do you know of any precedent to fix RPATH outside of CMake builds?

**Comment by carlocab** [comment]
Depends on the problem. If you just want to specify it you can pass `-Wl,-rpath,foo` in `LDFLAGS`.

**Comment by SMillerDev** [comment]
No errors seem related to Java, I think this is mergable.

**Pull request closed without merging**
