### PR TITLE
liburing 2.5

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
Not the latest release https://github.com/axboe/liburing/releases

**Comment by chenrui333** [comment]
looks like all the past releases, only 2.4 had the release note
image


no need to a blocker for shipping it.

**Comment by chenrui333** [comment]
@p-linnane let's ship the 2.5, no need to do the livecheck part

**Comment by chenrui333** [comment]
- https://github.com/axboe/liburing/issues/1008

**Comment by Bo98** [comment]
So does that mean we don't want the `github_latest` livecheck? Seems like tag alone is what denotes the release rather than a full GitHub release.

**Comment by chenrui333** [comment]
oh shoot, I thought the livecheck block got removed. let me update the PR

**Comment by chenrui333** [comment]
While I am in here, let me also update to use `std_configure_args`.

**Comment by chenrui333** [comment]
> oh shoot, I thought the livecheck block got removed. let me update the PR

looks like upstream did also actually tag 2.5 release, we will have another struggle next time.

**Comment by Bo98** [comment]
> looks like upstream did also actually tag 2.5 release, we will have another struggle next time.

Could leave a comment in the formula saying that GitHub is a backup so GitHub releases aren't an indicator of pre-release.

**Comment by Bo98** [comment]
> While I am in here, let me also update to use `std_configure_args`.

It isn't an autotools configure so this doesn't work. Probably should be called `std_autotools_configure_args` but that's maybe a bit long

**Comment by chenrui333** [comment]
> > looks like upstream did also actually tag 2.5 release, we will have another struggle next time.
> 
> Could leave a comment in the formula saying that GitHub is a backup so GitHub releases aren't an indicator of pre-release.

yeah, that sounds about right.

**Comment by chenrui333** [comment]
left comments for both. I will try to leave more notes in the future PRs.

**Review by Bo98 — APPROVED** [review]
Thanks!

**Pull request merged**
