### PR TITLE
zbctl 1.3.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
not yet marked as latest: https://github.com/camunda-cloud/zeebe/releases/latest

**Comment by chenrui333** [comment]
raise an issue in the upstream about the release status.

**Comment by chenrui333** [comment]
The release would be in this week.

**Comment by branchvincent** [comment]
fixed now

**Review by branchv — APPROVED** [review]

**Pull request closed without merging**
