### PR TITLE
standard 17.1.1

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by fxcoudert** [comment]
Rebasing on top of master (with Sequoia bottle) and pushing again.

**Review by fxcoudert — APPROVED** [review]

**Comment by carlocab** [comment]
> Rebasing on top of master (with Sequoia bottle) and pushing again.

Note that this can cause upload jobs to fail in a way that's very difficult to recover from -- it'll happen as soon as the previous build's checksum is reproducible. It often isn't, so we might be fine, but FYI.

**Comment by fxcoudert** [comment]
```
Error: docker://ghcr.io/homebrew/core/standard:17.1.1 already exists!
```

**Comment by carlocab** [comment]
Should be ok now, I think. Sequoia bottle is lost and should be dispatched separately.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Sequoia bottle dispatched

**Pull request merged**
