### PR TITLE
go 1.16.1

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Error: 7 failed steps!
brew test --retry --verbose bit-git
brew test --retry --verbose bit-git
brew install --build-from-source chronograf
brew install --build-from-source devdash
brew install --build-from-source lab
brew install --build-from-source mmark
brew install --build-from-source td
```

**Comment by Bo98** [comment]
`bit-git` is a env issue which I've submitted a PR upstream to fix (not Go related).
`chronograf` is a Node dependency issue (`parcel` needs to be pinned to 1.12.3`).

**Comment by Bo98** [comment]
Because this is a security release, I will still merge this when Big Sur completes despite 1.16.2 now being available.

**Comment by carlocab** [comment]
Catalina:

```
Error: 7 failed steps!
brew test --retry --verbose bit-git
brew test --retry --verbose bit-git
brew install --build-from-source chronograf
brew install --build-from-source devdash
brew install --build-from-source lab
brew install --build-from-source mmark
brew install --build-from-source td
```

Big Sur:

```
Error: 9 failed steps!
brew test --retry --verbose bit-git
brew test --retry --verbose bit-git
brew install --build-from-source chronograf
brew install --build-from-source devdash
brew test --retry --verbose dgraph
brew test --retry --verbose gost
brew install --build-from-source lab
brew install --build-from-source mmark
brew install --build-from-source td
```

ARM:

???

**Comment by carlocab** [comment]
```
==> Testing gost
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210311-6835-l36mas.sb ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gost.rb --verbose --retry
==> curl -I -x 127.0.0.1:54656 https://github.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 54656: Connection refused
Killing child processes...
```

**Pull request closed without merging**
