### PR TITLE
zsh-completions: update the fix command

### PR DESCRIPTION
**Pull request by saltbo**
update the fix command

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — CHANGES_REQUESTED** [review]
This doesn't look right. I'm pretty sure this isn't meant to reference the `zsh-completions` directory, or else we'd be using `opt_pkgshare`.

**Comment by saltbo** [comment]
But I use `chmod -R go-w '#{HOMEBREW_PREFIX}/share/zsh'` not resolve the error "zsh compinit: insecure directories"，use `chmod -R go-w '#{HOMEBREW_PREFIX}/share/zsh-completions'` resolved.

Env:
mac m1 
macos 12.3
Homebrew 3.4.2

**Comment by carlocab** [comment]
You probably need to `chmod` both of them. Do you not get the error after doing
```
chmod -R go+w "$(brew --prefix)/share/zsh"
```
?

**Comment by saltbo** [comment]
> You probably need to `chmod` both of them. Do you not get the error after doing
> 
> ```
> chmod -R go+w "$(brew --prefix)/share/zsh"
> ```
> 
> ?

Yes, found `zsh compinit: insecure directories, run compaudit for list`

``` bash
➜  ~ compaudit
There are insecure directories:
/opt/homebrew/share/zsh/site-functions
/opt/homebrew/share/zsh
```

**Comment by carlocab** [comment]
That means the command you just replaced is still necessary.

**Comment by saltbo** [comment]
> That means the command you just replaced is still necessary.

`/opt/homebrew/share/zsh/site-functions` worked fine before I install zsh-completions. I don't need to execute `chmod-R go-w "$(brew-- prefix) / share/zsh" `. 

Now that I've installed zsh-completions, I think should change the corresponding `/opt/homebrew/share/zsh-completions` directory. Why change the`/opt/homebrew/share/zsh`?

**Pull request closed without merging**
