### PR TITLE
libcouchbase 2.8.4

### PR DESCRIPTION
**Pull request by avsej**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@avsej why not depend on the snappy formula?

**Comment by avsej** [comment]
Because right now we only tested against snappy-1.1.1, and snappy-1.1.7 homebrew is shipping does not define its version correctly at least.

**Comment by ilovezfs** [comment]
That may be because we build snappy with CMake. I'd like to use the formula regardless of whether that specific version has been tested.

**Comment by avsej** [comment]
snappy-1.1.7 ships broken header file

**Comment by avsej** [comment]
Because these packages don't use version macros in the header.

**Comment by ilovezfs** [comment]
We'll need to find some workaround for that then and get it reported upstream.

**Comment by avsej** [comment]
Workaround is to use verified snappy we have in the source package. I will report the issue to upstream.

**Comment by ilovezfs** [comment]
I'm not comfortable using a static vendored version when we have a formula that nine other formulae are using fine.

**Comment by avsej** [comment]
So you would rather change this formula and likely break it, than accept it with bundled snappy?

You can take this patch to fix snappy formula: https://github.com/google/snappy/pull/61.patch

**Comment by ilovezfs** [comment]
@avsej https://github.com/Homebrew/homebrew-core/pull/21925

**Comment by avsej** [comment]
@ilovezfs I have updated the formula. Now it will compile snappy if the end user will decide to do it. And by default it will not use compression at all.

**Comment by ilovezfs** [comment]
@avsej https://github.com/Homebrew/homebrew-core/pull/21925 is shipped so you can just depend on snappy unconditionally now.

**Comment by avsej** [comment]
No, I cannot depend on that snappy. I would rather make this feature optional now. In its current shape, is this formula acceptable?

**Comment by ilovezfs** [comment]
Why not? It builds as expected now.

**Comment by avsej** [comment]
Because we have not tested with this snappy. I'm not actively using MacOS, so we can change formula to use external snappy later.

**Comment by ilovezfs** [comment]
@avsej The difference is in patch level. I don't think we need to worry about a problem here. I'm happy to revert it later if you identify an actual problem but we should be optimistic that it'll be fine.

**Comment by avsej** [comment]
Right now compression feature is not publicly available on Couchbase Server, so I would rather stick to static optional snappy.

**Comment by ilovezfs** [comment]
I'm :-1: on adding new options here, let alone options for static libraries. So we'll need to go without compression or use the external library.

**Comment by avsej** [comment]
What wrong with options? It will make it easier for people to opt-in for features.

**Comment by ilovezfs** [comment]
They result in source builds instead of using the prebuilt binary, but if you want to make it

```
depends_on "snappy" => :optional
```

I'd be OK with that for now.

**Comment by avsej** [comment]
I removed snappy support from the formula.

**Comment by ilovezfs** [comment]
OK.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for the upgrade @avsej! Shipped.

**Pull request closed without merging**
