### PR TITLE
gnupg 2.2.4

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
:key:

**Comment by DomT4** [comment]
Thanks for the merge ❤️

**Comment by ilovezfs** [comment]
I'm just glad we didn't have to revision bump anything given the req situation.

**Comment by DomT4** [comment]
I think things checking for `gpg` during the build process is pretty rare, thankfully. Personally I'm not even convinced `gopass` checking it exists _simply to print completions_ is a valid failure, but, ho hum.

**Comment by ilovezfs** [comment]
I guess in terms of using post install as a hack, we could add a dummy file so it gets linked in properly and then overwrite it ...

**Comment by DomT4** [comment]
Something of a fun fact seems to be that if you move the blob inside `post_install` as I did in the `diff` in the other thread brew still prints:
```
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```
but that's of course nonsense.

**Comment by ilovezfs** [comment]
How so?

**Comment by DomT4** [comment]
Well, because `post_install` happens post-linking rather than pre-linking.

Reproducer, after applying diff from https://github.com/Homebrew/homebrew-core/issues/21903#issuecomment-353179881:
```
=> rm /usr/local/etc/bash_completion.d/gopass-completion
=> brew install gopass -s

...
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/gopass/1.6.5: 7 files, 9.9MB, built in 11 seconds

=> file /usr/local/etc/bash_completion.d/gopass-completion
/usr/local/etc/bash_completion.d/gopass-completion: cannot open `/usr/local/etc/bash_completion.d/gopass-completion' (No such file or directory)
```

**Comment by ilovezfs** [comment]
Yeah it's just checking
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg.rb#L333-L342
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/caveats.rb#L81

I guess since we want it to print for keg only too? Although I guess completions don't work for keg_only, do they?

**Comment by DomT4** [comment]
Yeah, it checks existence inside the keg and assumes as long as it exists in the `keg` it'll be getting linked.

> Although I guess completions don't work for keg_only, do they?

No, they don't. Arguably since they get installed inside `etc` it might be a legitimate exemption from `keg_only`. We typically have allowed even `keg_only` formulae semi-free roam of `etc` and `var` inside `HOMEBREW_PREFIX`.

```
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because To test completion linkage.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/gopass/bin:$PATH"' >> ~/.zshrc


Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

**Comment by ilovezfs** [comment]
not a legitimate exemption unless they're going to be automatically deconflicted with other keg_only versioned formulae …

**Comment by DomT4** [comment]
That's true. Although the `mysql` stuff all used to share `var/mysql`. Not sure if that's still the case.

**Comment by ilovezfs** [comment]
Using multiple mysql at once is totally unsupported lol. Ditto any of the other databases

**Comment by DomT4** [comment]
`mysql` has a guard in place at least:
```
unless (datadir/"mysql/user.frm").exist?
```
That wouldn't be the case for completions, so I think your point is valid.

**Comment by ilovezfs** [comment]
I think if we wanted completions to work for keg only, assuming you're not force linking, they'd need to be added to the completions path.

**Comment by ilovezfs** [comment]
https://serverfault.com/questions/506612/standard-place-for-user-defined-bash-completion-d-scripts

**Comment by DomT4** [comment]
Aye. Locally I played with:
```diff
diff --git a/Library/Homebrew/caveats.rb b/Library/Homebrew/caveats.rb
index aad354607..4fd97130b 100644
--- a/Library/Homebrew/caveats.rb
+++ b/Library/Homebrew/caveats.rb
@@ -88,10 +88,21 @@ class Caveats
 
     case shell
     when :bash
-      <<~EOS
-        Bash completion has been installed to:
-          #{HOMEBREW_PREFIX}/etc/bash_completion.d
-      EOS
+      if f.keg_only?
+        completions = Dir["#{f.opt_prefix}/etc/bash_completion.d/*"].first
+        <<~EOS
+          Bash completion has been installed to:
+            #{f.opt_prefix}/etc/bash_completion.d
+          You may wish to add:
+            . #{completions}
+          to your shell profile for completions to work.
+        EOS
+      else
+        <<~EOS
+          Bash completion has been installed to:
+            #{HOMEBREW_PREFIX}/etc/bash_completion.d
+        EOS
+      end
     when :zsh
       <<~EOS
         zsh #{installed.join(" and ")} have been installed to:
```

But that's not exactly pretty.

**Comment by ilovezfs** [comment]
Yeah we should probably do something like that, not print them for keg_only at all, or move completions messaging to the link step.

**Comment by DomT4** [comment]
> not print them for keg_only at all

This is my immediate temptation, to avoid having to individually handle `zsh`, `bash` and `fish`, at least until enough people kick up a fuss to show fixing it is worth the complication.

**Comment by DomT4** [comment]
Also there's the issue with `keg_only` stuff that if you simply do something like:
```
. /usr/local/opt/gopass/etc/bash_completion.d/gopass-completion
```
and then do `gopass <tab>` inside `bash` it vomits because it isn't in the `PATH` unless the user has handled that side of `keg_only` already as well:
```
gopass bash: gopass: command not found
```

**Comment by ilovezfs** [comment]
keg_only is awesome. Honest. I swear.

**Comment by DomT4** [comment]
It remains super that `clang`/etc still search for headers and libraries using a completely different priority list. Really helpful.

**Comment by DomT4** [comment]
If that ever got fixed we could at least talk about `keg_only`'s future one day, but with that issue & with Homebrew living in `/usr/local` by default `keg_only` is essentially forever, heh.

**Comment by DomT4** [comment]
Opened https://github.com/Homebrew/brew/pull/3590 to move the completion caveat discussion over there at least.

**Comment by msummers42** [comment]
@DomT4  @ilovezfs  I am curious if we might start buildingGnuPG with the `--auto-expand-secmem` option now, with 2.2.4. This solves a concurrency problem that causes gpg-agent to crash.

```
* agent: New option --auto-expand-secmem to help with high numbers
    of concurrent connections.  Requires libgcrypt 1.8.2 for having
    an effect.  [#3530]
```
Source: https://lists.gnupg.org/pipermail/gnupg-announce/2017q4/000419.html

**Comment by DomT4** [comment]
It would seem a reasonable enough change to make, from my point of view. Or at least provide an option for.

**Comment by ilovezfs** [comment]
do we know why it's not the default

**Comment by DomT4** [comment]
There may be an actual answer somewhere, but I'd guess either upstream is trying to remain default-friendly to devices operating in a memory-constrained environment or they're unwilling to flip the switch by default on a new feature in a minor release.

**Comment by msummers42** [comment]
The default does not even enable `---large-secmem`, so I see this as mainly being friendly and backward compatible with memory-constrained systems, but the point is very valid that it's a new feature in a minor release.

It begs the question if there should be a new brew package to test this feature (keeping the current defaults in the main pkg), although I think it's generally pretty stable.

**Comment by DomT4** [comment]
> It begs the question if there should be a new brew package to test this feature

Homebrew doesn't really do this, because it's a hellscape for maintainers. Personally I'd be fine with `--auto-expand-secmem` being flipped on by default & seeing if anyone complains.

**Comment by msummers42** [comment]
@DomT4  This sounds reasonable to me. I would be happy to do the PR, but I am new to Homebrew (not to building GnuPG however). How do you think it best to proceed?

**Comment by DomT4** [comment]
Alright, I set aside some of my time to look into this properly given I'm full of plague right now & have nothing better to do. The reason it's not a default, at least in part, is because it's not a build option at all. It's a runtime option you can pass to `gpg-agent` as an option or presumably more sensibly set in your `gpg-agent.conf` file inside `~/.gnupg`. So any change here would need to be made on the user's side rather than Homebrew's.

**Comment by msummers42** [comment]
Well that makes thing easy! Thanks for solving this seeming mystery!!

**Comment by DomT4** [comment]
They did make things unnecessarily confusing by picking a flag name _really_ close to the already-existing configure flag for `large-secmem`. The similarity between the names creates an idea of similarity in purpose but 🤷‍♂️.

**Pull request closed without merging**
