### PR TITLE
mono: fix build for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
```
Build FAILED.

/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,3): warning : Unable to load the service index for source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json.
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,3): warning : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json.
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,3): warning : Unable to load the service index for source https://api.nuget.org/v3/index.json.
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,3): warning : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json.
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,3): warning : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3/index.json.
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,3): error : Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): arcade, dotnet-core, dotnet-tools, nuget-build, nuget.org
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
/tmp/mono--msbuild-20210727-5491-ka8pdc/Directory.Build.props(3,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [/tmp/mono--msbuild-20210727-5491-ka8pdc/mono/build/sdks_and_nugets/sdks/sdks.csproj]
```

**Comment by SMillerDev** [comment]
It's not working so approving it won't help you much.

**Comment by SCWR** [comment]
I know that this PR cannot be merged, because he has not passed the test.
Just see it passed TEST 11 ARM64
Installing Mono on Mac M1 will have problems
And just I need to build a Window platform electronic app on the Mac.
I want to express this PR may solve my problem.
If there is any offense, I said sorry.

**Comment by cho-m** [comment]
> Just see it passed TEST 11 ARM64

ARM is actually skipped, which shows up as passing in CI.

I don't think stable .NET frameworks (`dotnet`, `mono`, etc) build on M1 ARM yet.
At least `dotnet` needs fixes in preview, so probably similar situation for `mono`.

**Comment by SCWR** [comment]
I found this PR through this link. 
image

I also guessed that I needed mono itself to support the build installation in the ARM64 architecture.

Just came here to see the test pass, and it was like a light at the end of the tunnel.

Can you help me to see if it is to solve the problem. (But you said you skipped arm64)

Thank you for your advice.

**Comment by SMillerDev** [comment]
It's unsupported on ARM so it will not work. The check is green because we know this and don't even try to test it until 6.0

**Comment by SCWR** [comment]
Thank you for your response, so THAT I don't feel alone, looking forward to `dotnet` (6.0.0)

**Pull request closed without merging**
