### PR TITLE
flank 20.06.2 (new formula)

### PR DESCRIPTION
**Pull request by technoir42**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@technoir42 thanks for the PR, do you have any recipe to adopt this in the pipeline?

**Comment by technoir42** [comment]
@chenrui333 sorry, I'm not sure what you mean

**Comment by chenrui333** [comment]
That is actually a side question about your PR, I will move this to a email chat. 😄

**Review by chenrui333 — DISMISSED** [review]
lgtm

**Comment by chenrui333** [comment]
sorry, head does not work and should not be added (as it depends on jar artifact).

Will merge after build turns green.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@technoir42, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request merged**
