### PR TITLE
erlang 24.1.1

### PR DESCRIPTION
**Pull request by alaadahmed**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by alaadahmed** [comment]
Please remove the restrictions because tests take a lot of time and it will be cancelled.

**Comment by jonchang** [comment]
Looks like it finished in under 60 minutes! Thanks for contributing to Homebrew, @alaadahmed!

**Review by jonchang — APPROVED** [review]

**Comment by alaadahmed** [comment]
It didn't install on my macOS 11.6!! I got this message 
```
Error: /usr/local/Cellar/erlang/24.1.1 is not a directory
```
I wonder what did go wrong?

**Comment by alaadahmed** [comment]
Sorry my mistake. It seems I switched branch inside `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` to some branch but not master. I installed it successfully.

**Pull request closed without merging**
