### PR TITLE
handbrake 1.3.0

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can we build this with python 3?

**Comment by Moisan** [comment]
There is also a minimum required version of `xcodebuild`:
```
version probe: xcodebuild 10.3.0...(fail) 10.1
```
I guess we should add `depends_on :macos => :mojave`

**Comment by fxcoudert** [comment]
How about `depends_on :xcode => ["10.3", :build]`? Seems clearer to me.

**Comment by SMillerDev** [comment]
Can you squash @Moisan?

**Pull request closed without merging**
