### PR TITLE
openjdk@11 11.0.15

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
looks like `jdk-11.0.15-ga` does not build on arm

**Comment by Bo98** [comment]
> looks like `jdk-11.0.15-ga` does not build on arm (tested out in my local)

What error do you get?

**Comment by chenrui333** [comment]
> > looks like `jdk-11.0.15-ga` does not build on arm (tested out in my local)
> 
> What error do you get? It is supposed to work.

These are the errors I got in my local
```
/private/tmp/openjdkA11-20220420-71861-1dnt01y/jdk11u-jdk-11.0.15-ga/src/jdk.hotspot.agent/macosx/native/libsaproc/symtab.c:69:67: error: too few arguments to function call, expected 5, have 4
    (*symtab->hash_table->put)(symtab->hash_table, &key, &value, 0);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~                                    ^
/private/tmp/openjdkA11-20220420-71861-1dnt01y/jdk11u-jdk-11.0.15-ga/src/jdk.hotspot.agent/macosx/native/libsaproc/symtab.c:81:73: error: too few arguments to function call, expected 5, have 4
        (*symtab->hash_table->get)(symtab->hash_table, &rkey, &rvalue, 0);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~                                      ^
/private/tmp/openjdkA11-20220420-71861-1dnt01y/jdk11u-jdk-11.0.15-ga/src/jdk.hotspot.agent/macosx/native/libsaproc/symtab.c:407:71: error: too few arguments to function call, expected 5, have 4
  ret = (*symtab->hash_table->get)(symtab->hash_table, &key, &value, 0);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~                                    ^
3 errors generated.
```

I guess it is sorted out now.

**Comment by Bo98** [comment]
I've seen some people with that issue but have been having issues tracking it down. Can you do a `brew gist-logs openjdk@11` so I can have a look?

Also does `ls -l /usr/local/include/db.h` output anything?

**Comment by chenrui333** [comment]
> I've seen some people with that issue but have been having issues tracking it down. Can you do a `brew gist-logs openjdk@11` so I can have a look?
> 
> Also does `ls -l /opt/homebrew/include/db.h` output anything?

here is the gist (I realized that I have to upgrade CLI for xcode to the latest in order to use this feature)
https://gist.github.com/chenrui333/fc68bddd64cf6201e5648a44d7bf0142

```
$ ls -l /opt/homebrew/include/db.h
lrwxr-xr-x  1 rui  admin  42 Dec 11 00:10 /opt/homebrew/include/db.h -> ../Cellar/berkeley-db/18.1.40/include/db.h
```

**Comment by Bo98** [comment]
Can you try `brew upgrade berkeley-db` and try again? There should be a 18.1.40_1, which contains my initial attempt at fixing this.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
