### PR TITLE
neovim 0.9.0

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

~`resource` blocks updated (tree-sitter parsers, mpack-lua)~

### CODE REVIEW

**Comment by clason** [comment]
For those wondering what's going on here: the 11-arm64 runner is flaky and keeps crashing.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Neovide test failed on 11-arm64, but seems spurious, since it passed elsewhere. Though 13-arm64 is still queued.

**Comment by clason** [comment]
> Neovide test failed on 11-arm64, but seems spurious, since it passed elsewhere. Though 13-arm64 is still queued.

Yeah, this is what confused me as well; since it's the same runner that just crashed when testing Neovim itself, I chalked it up to flakiness (e.g., relating timings). Needless to say, Neovide works fine on my macOS 13 M1...

**Comment by carlocab** [comment]
Ah well. I'm fine with merging this. No point blocking an upgrade for everyone else.

**Comment by clason** [comment]
I'll keep this in mind and talk to the other Neovide maintainers; we should consider a new release anyway.

**Comment by carlocab** [comment]
Still seeing the ARM Big Sur Neovide failure at #127894. FYI.

**Pull request merged**
