### PR TITLE
b3sum 0.2.2

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Due to a [compiler bug](https://bugs.llvm.org/show_bug.cgi?id=36202), the version of clang used on High Sierra does not work properly with AVX512 assembly instructions.

The solution could be either:
* Supplying `--no-default-features --features=rayon` if `DevelopmentTools.clang_build_version <= 1000`.
* Depending on `llvm` for builds where `DevelopmentTools.clang_build_version <= 1000`.

**Comment by Bo98** [comment]
Don't know if Rust will pick up brew LLVM or Xcode but we'll soon find out.

**Comment by Bo98** [comment]
I think `CLANG_BASE_PATH` is specific to some other build tool.

`ENV["HOMEBREW_CC"] = "llvm_clang"` might be enough to make it "just work". The superenv will hopefully handle the rest.

The `ENV.remove "HOMEBREW_LIBRARY_PATHS", ....` is indeed a good idea.

**Comment by dawidd6** [comment]
Thanks for help @Bo98!

**Pull request closed without merging**
