### PR TITLE
i686-elf-binutils 2.38

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Will require #92329 to be updated after this is merged.

### CODE REVIEW

**Comment by iMichka** [comment]
The binutils formula needs to be built with the Linux Wheezy container, in a separate PR. Can you open a separate PR for that?

**Comment by pthariensflame** [comment]
> The binutils formula needs to be built with the Linux Wheezy container, in a separate PR. Can you open a separate PR for that?

Just the `binutils` commit by itself, leaving the rest here?

**Comment by carlocab** [comment]
Why are there so many revision bumps here? We didn't have any for past `binutils` version bumps: #81485, #70688, #69699, #61358, #58537

**Comment by pthariensflame** [comment]
> Why are there so many revision bumps here? We didn't have any for past `binutils` version bumps: #81485, #70688, #69699, #61358, #58537

I was just assuming I should bump things that depend on `*binutils`.  I'll remove them.

**Comment by carlocab** [comment]
Lots of users dislike the consequences of `revision` bumps, so we should really keep these to a minimum. Also all those revision bumps are likely to require more CI time than the 3-day timeout on GitHub Actions.

**Comment by pthariensflame** [comment]
Understood!

**Review by iMichka — DISMISSED** [review]

**Comment by cho-m** [comment]
Needed to rebase due to other updates being merged in #95143 and #95245

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
