### PR TITLE
valijson 1.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

repology inclusion, https://repology.org/project/valijson/versions
needed by #113760

### CODE REVIEW

**Comment by chenrui333** [comment]
on linux
```
  /usr/bin/ld: /tmp/cc7W3TVt.o: in function `valijson::adapters::JsonCppFrozenValue::~JsonCppFrozenValue()':
  test.cpp:(.text._ZN8valijson8adapters18JsonCppFrozenValueD2Ev[_ZN8valijson8adapters18JsonCppFrozenValueD5Ev]+0x2a): undefined reference to `Json::Value::~Value()'
  collect2: error: ld returned 1 exit status
  Error: valijson: failed
  An exception occurred within a child process:
```

**Comment by chenrui333** [comment]
undefined symbols on x86

**Comment by SMillerDev** [comment]
Why would we allow this as an unstable version?

**Comment by chenrui333** [comment]
> Why would we allow this as an unstable version?

I dont think it is unstable, just they marked as `pre release` in the github releases though (probably like any release before 1.0.0 should be pre-release kind of thing)

**Comment by SMillerDev** [comment]
Could you ask? Because I'd rather not allow this as a pre-release unless it's absolutely required.

**Comment by chenrui333** [comment]
that is a good point, let me raise an issue about it.

**Comment by chenrui333** [comment]
Upstream just released the 1.0, which should be good for the PR now.

**Review by SMillerDev — DISMISSED** [review]

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
