### PR TITLE
task 2.6.0

### PR DESCRIPTION
**Pull request by bradyt**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Changing head branch from `2.6.0` to `stable` is assumed to be correct according to the following change from https://github.com/GothenburgBitFactory/taskwarrior/commit/64ea936d7fd3f782474a05c69df28d18659633dd:

```diff
modified   README.md
@@ -64,13 +64,15 @@ For code contributions, please use pull requests, or alternately send your code
 
 We use the following branching model:
 
-* `master` is the stable branch. Building from here is the same as building
-  from the latest tarball, or installing a binary package. No development is
-  done on the `master` branch.
-
-* `2.6.0` is the current development branch. All work is done here, and upon
-  release it will be merged to `master`. This development branch is not stable,
-  and should be treated accordingly. Make backups.
+* `stable` is a branch containing the content of the latest release. Building
+  from here is the same as building from the latest tarball, or installing a
+  binary package. No development is done on the `stable` branch.
+
+* `develop` is the current development branch. All work is done here, and upon
+  release it will be merged to `stable`. While development branch is not
+  stable, we utilize CI to ensure we're at least not merging improvements that
+  break existing tests, and hence should be relatively safe. We still recommend
+  making backups when using the development branch.
 
 ## Installing

```

### CODE REVIEW

**Comment by carlocab** [comment]
The Linux build failed. Can we see if this works:
```diff
diff --git a/Formula/task.rb b/Formula/task.rb
index de96cc54fe3..d729c705851 100644
--- a/Formula/task.rb
+++ b/Formula/task.rb
@@ -24,11 +24,14 @@ class Task < Formula
   depends_on "gnutls"
 
   on_linux do
+    depends_on "gcc"
     depends_on "linux-headers@4.4"
     depends_on "readline"
     depends_on "util-linux"
   end
 
+  fails_with gcc: "5"
+
   def install
     system "cmake", ".", *std_cmake_args
     system "make", "install"
```

**Comment by bradyt** [comment]
@carlocab Thank you for helping with this. I squashed your suggestion to my commit, and force pushed, so I guess we see what that does in some minutes.

I think the logs suggest we see gcc 5 there, whereas the Taskwarrior README has "C++ compiler, currently gcc 7.1+ or clang 5.0+ for full C++17 support".

Is there a simple way to troubleshoot locally on macOS? I'm considering starting a VM via docker, installing homebrew, and trying the process there with the ability to get more direct feedback, etc.

**Comment by carlocab** [comment]
You can use the same Docker image we use in CI, to save you from having to install `brew` separately:
```
docker run -it --rm homebrew/ubuntu16.04:latest /bin/bash
cd $(brew --repo homebrew/core)
git remote set-url origin https://github.com/Homebrew/homebrew-core
git fetch origin
git reset --hard origin/master
```
You need to change the remote because the Docker image has [Linuxbrew/core](https://github.com/Homebrew/linuxbrew-core.git) set up as the core tap.

**Review by carlocab — APPROVED** [review]
Looks like that worked. Thanks @bradyt!

**Pull request closed without merging**
