### PR TITLE
gcc: update patch

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-core/issues/194778 for context

### CODE REVIEW

**Comment by Bo98** [comment]
Would you like me to update macOS 14 to Xcode 16 first or does it not matter much? I have already set aside Monday to do that.

**Comment by fxcoudert** [comment]
> Would you like me to update macOS 14 to Xcode 16 first or does it not matter much?

I'll hold this PR until the update is done, then. No hurry.

**Comment by saschasc** [comment]
@Bo98 Any progress on the update? Would be great to have a working gcc 14.2 soon for macOS. Thanks for your effort!

**Comment by fxcoudert** [comment]
> Any progress on the update? Would be great to have a working gcc 14.2 soon for macOS. Thanks for your effort!

The current gcc 14.2 does work on all macOS versions we support, provided the matching SDK is used. It should always be the case.

**Comment by saschasc** [comment]
Sure, but r1 doesn't include important fixes (e.g. for gRPC and other libraries). So an official gcc 14.2 r2 Homebrew package would be highly desirable.

**Comment by Bo98** [comment]
> Any progress on the update?

It got moved to today since I had a few meetings yesterday. I will start a new run here shortly.

**Review by MikeMcQuaid — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
`aubio` is a network failure. Not sure about `alpscore`, but seems isolated.

**Comment by fxcoudert** [comment]
`aubio` is a network failure. `alpscore` will be rebottled following the macOS 14 CI update.

**Comment by saschasc** [comment]
Thanks a lot for pushing this @fxcoudert and @Bo98 update. Much appreciated!

Crazy how long the CI takes ...

**Comment by Bo98** [comment]
One of the changes was removing libgcc_s.1.dylib so running tests on everything that used GCC was very important to make sure nothing did use it.

GCC 13 and earlier should be much quicker CI as nothing else in Homebrew uses them really.

**Comment by carlocab** [comment]
> One of the changes was removing libgcc_s.1.dylib so running tests on everything that used GCC was very important to make sure nothing did use it.

It's already broken as-is, so we'd have spotted users of it much earlier.

**Pull request merged**
