### PR TITLE
kubeprod 1.1.0 (new formula)

### PR DESCRIPTION
**Pull request by sameersbn**
Signed-off-by: Sameer Naik <sameer@bitnami.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by sameersbn** [comment]
ping!

**Comment by SMillerDev** [comment]
Is there a way to test more of the functionality?

**Comment by SMillerDev** [comment]
Could you check for a specific failure then? Version checks rarely indicate something that isn't spectacularly broken. Maybe you could check for an error code and text in the output when you attempt a common command?

**Comment by sameersbn** [comment]
@SMillerDev Thanks for your feedback. I was able to figure out a way to test some of the functionality of the binary. Can you please take a look.

**Comment by SMillerDev** [comment]
Test looks good, brew audit is complaining though. Could you check that?

**Comment by sameersbn** [comment]
Sorry about that. Should be fixed now.

**Comment by fxcoudert** [comment]
Thanks @sameersbn it's merged now!

**Comment by sameersbn** [comment]
Thank you!

**Pull request closed without merging**
