### PR TITLE
hbase: Make it work out of the box, add compression

### PR DESCRIPTION
**Pull request by CamJN**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

fixes ipv6 issue in default config, and adds lzo compression which is essential for production use.

### CODE REVIEW

**Comment by apjanke** [comment]
Could you bump the formula `revision` since this changes the default dependencies? It doesn't have a bottle built, so it won't matter for most users, but it should still be reinstalled so users pick up the latest version.

**Comment by DomT4** [comment]
This will need a bottle after this PR, as it contains a compile step now.

**Comment by CamJN** [comment]
Is there anything I should do RE: the bottle?

**Comment by apjanke** [comment]
> Is there anything I should do RE: the bottle?

Nope. Building the bottle happens automatically here. This is probably just a note to maintainers to make sure to pull the bottle when merging this PR.

**Comment by apjanke** [comment]
This LGTM.

Could you explain why the `depends_on :arch => :x86_64` is necessary, especially for a Java program? Is it just that 32-bit isn't supported?

**Comment by CamJN** [comment]
The reasoning behind requiring `:x86_64` is this:

The LZO compression jar compiles native extensions
To compile the code, [the instructions I followed](http://opentsdb.net/setup-hbase.html) had me pass in some flags specifying 64 bit 
The hadoop-lzo project [delegates describing how to compile it to the hadoop-gpl project](https://github.com/twitter/hadoop-lzo/tree/f761f10a818fa286fbad0466c3279da6739a01ff#building-and-configuring)
The hadoop-gpl project says that you [need a 32 bit java install](https://code.google.com/archive/a/apache-extras.org/p/hadoop-gpl-compression/wikis/FAQ.wiki) to build a 32 bit native extension
The hadoop-lzo project [requires java 7+ on OS X](https://github.com/twitter/hadoop-lzo/tree/f761f10a818fa286fbad0466c3279da6739a01ff#building-and-configuring) which is [only available as 64 bit on OS X](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
Therefore there's no good way to build the jar as 32 bit, and since I don't know exactly what happens if I don't specify an arch, it seemed prudent to require 64 bit OS X.

**Comment by apjanke** [comment]
Wow. That's non-intuitive enough, could you put a brief 2-3 line summary of it in the code where it's specified, so future updates know why it's there and that they shouldn't remove it?

**Comment by apjanke** [comment]
Looks good now.

The test-bot is being finicky with this build and I'm having trouble pulling it. Could you squash this to a single commit and rebase on `master`? That'll kick off another build which should have less trouble.

**Comment by CamJN** [comment]
Ok, hopefully that's right.

**Comment by apjanke** [comment]
Looks good. Now we just let BrewTestBot do its work and I'll merge it.

**Comment by apjanke** [comment]
Still broken. Build appears to have no results in Jenkins. What the heck?

Manually queued up a rebuild through the Jenkins interface; we'll see if that works.

**Comment by CamJN** [comment]
[This](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1274/) one seems to have worked.

**Comment by apjanke** [comment]
The pull is still broken. Can't tell what's going on here.

```
$ brew pull --bottle 670
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: Make hbase work out of the box, add compression
==> Patch closes issue #670
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.9.5)\ curl/7.30.0 --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-core/compare/homebrew:master...pr-670
```

Any other maintainers know what might be causing this and how to fix it? I'm getting a "there isn't anything to compare" GitHub error page when I go to that URL in a browser, too

https://github.com/BrewTestBot/homebrew-core/compare/homebrew:master...pr-670

**Comment by mikemcquaid** [comment]
@apjanke The bottle job failed: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1274/downstreambuildview/

`Error: cowsay-3.03_2.el_capitan.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles/cowsay/view#files`

I removed those files and reran the job. Should be pullable now.

**Comment by apjanke** [comment]
Same failure as before.

```
$ brew pull --bottle 670
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-core/pull/670.patch
==> Applying patch
Applying: Make hbase work out of the box, add compression
==> Patch closes issue #670
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.9.5)\ curl/7.30.0 --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-core/compare/homebrew:master...pr-670
```

The downstream bottle job is still complaining about the files already being published.

```
curl -I --silent --fail --output /dev/null https://homebrew.bintray.com/bottles/hbase-1.1.4_1.el_capitan.bottle.tar.gz
Error: hbase-1.1.4_1.el_capitan.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles/hbase/view#files
Build step 'Execute shell' marked build as failure
Started calculate disk usage of build
```

Maybe we should just bump the `revision` up to `2` here as a workaround?

**Comment by mikemcquaid** [comment]
> Error: hbase-1.1.4_1.el_capitan.bottle.tar.gz is already published. Please remove it manually from
> https://bintray.com/homebrew/bottles/hbase/view#files

@apjanke Did that not work?

**Comment by apjanke** [comment]
Oh, sorry. I thought you meant that you had already removed them for this hbase run. Now I see you were just referencing an example.

I manually removed those bottle files for `hbase`, reran the build job, and then the `brew pull` worked.

*Now* I think I finally understand what this error is and how to resolve it. Sorry it's taking me so long to get up to speed on this Jenkins and test-bot stuff.

Thanks!

**Comment by mikemcquaid** [comment]
@apjanke No worries!

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew and patience with this PR, @CamJN!

**Pull request closed without merging**
