### PR TITLE
gnuradio: update deps

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
To be honest, current `gnuradion` fails to build from source on my machine, maybe because I have case-sensitive FS.

**Comment by carlocab** [comment]
For ARM:
```
❯ brew unbottled --tag=arm64_big_sur gnuradio
==> Populating dependency tree...
==> :arm64_big_sur bottle status
gnuradio: unbottled deps: qwt volk
```

**Comment by yurikoles** [comment]
It looks like it should be rebased after merge of #69209.

**Comment by bayandin** [comment]
Probably, we can update `gnuradio` to 3.9.0.0 also

**Comment by bayandin** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/69326

**Pull request closed without merging**
