### PR TITLE
hdf5 1.12.0

### PR DESCRIPTION
**Pull request by tschoonj**
Also creates a new versioned formula hdf5@1.10

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tschoonj** [comment]
`field3d` fails to build because its `scons` build scripts are using python 2.7 syntax. Given the lack of development in this project: remove the formula?

**Comment by SMillerDev** [comment]
Will upstream keep maintaining the old version?

**Comment by tschoonj** [comment]
I would expect so... They kept releasing 1.8 updates long after 1.10 came out

**Comment by lgritz** [comment]
@tschoonj Can we reinstate field3d? It has both scons and cmake build systems. The cmake one should still work just fine despite lack of python2.

**Comment by tschoonj** [comment]
Feel free to open a PR, but the project looks dead to me...

**Comment by conradsnicta** [comment]
**Note:** HDF5 v1.12 contains API breaks.  This package should not have been updated without more involved coordination with dependent packages.  Example of fallout: https://github.com/Homebrew/homebrew-core/issues/52003

**Comment by EricFromCanada** [comment]
New version of `field3d` posted in #54743.

**Pull request closed without merging**
