### PR TITLE
libxcrypt 4.4.33

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Error: 11 failed steps!
brew test --retry --verbose beast
brew linkage --test fourstore
brew test --retry --verbose mrbayes
brew test --retry --verbose pyflow
brew test --retry --verbose ruby
brew test --retry --verbose ruby@2.7
brew test --retry --verbose ruby@3.0
brew install spotifyd
brew test --retry --verbose streamlink
brew test --retry --verbose xmltoman
brew test --retry --verbose zorba

**Comment by chenrui333** [comment]
```
$ brew linkage --test fourstore
  Missing libraries:
    unexpected (libavahi-client.so.3)
    unexpected (libavahi-common.so.3)
    unexpected (libavahi-glib.so.1)
```

**Review by fxcoudert — APPROVED** [review]

**Comment by chenrui333** [comment]
xmltoman and zobra test failures are reproducible in codespace

```
@chenrui333 ➜ /workspaces/homebrew-core (bump-libxcrypt-4.4.33) $ brew test xmltoman
==> Testing xmltoman
==> xmltoman 2>&1
Error: xmltoman: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /You\ need\ to\ specify\ a\ file\ to\ parse/ to match "perl: warning: Setting locale failed.\nperl: warning: Please check that your locale settings:\n\tLANGUAGE = (unset),\n\tLC_ALL = \"C.UTF-8\",\n\tLANG = (unset)\n    are supported and installed on your system.\nperl: warning: Falling back to the standard locale (\"C\").\nExpat.c: loadable library and perl binaries are mismatched (got first handshake key 0xeb00080, needed 0xeb80080)".
  
  @chenrui333 ➜ /workspaces/homebrew-core (bump-libxcrypt-4.4.33) $ brew test zorba
==> Testing zorba
==> /home/linuxbrew/.linuxbrew/Cellar/zorba/3.1_16/bin/zorba -q 1+1
Error: zorba: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: nil
```

**Comment by chenrui333** [comment]
pyflow is a known issue

**Comment by chenrui333** [comment]
ruby test all suffered gcc-11 issue

```
==> /home/linuxbrew/.linuxbrew/Cellar/ruby@3.0/3.0.4_1/bin/gem install json
Last 15 lines from /home/codespace/.cache/Homebrew/Logs/ruby@3.0/test.01.gem:
creating Makefile

current directory: /tmp/rubyA3.0-test-20221204-377-91t6v8/gems/json-2.6.2/ext/json/ext/generator
make DESTDIR\= clean

current directory: /tmp/rubyA3.0-test-20221204-377-91t6v8/gems/json-2.6.2/ext/json/ext/generator
make DESTDIR\=
compiling generator.c
make: gcc-11: Command not found
make: *** [Makefile:245: generator.o] Error 127

make failed, exit code 2

Gem files will remain installed in /tmp/rubyA3.0-test-20221204-377-91t6v8/gems/json-2.6.2 for inspection.
Results logged to /tmp/rubyA3.0-test-20221204-377-91t6v8/extensions/x86_64-linux/3.0.0/json-2.6.2/gem_make.out
```

**Comment by chenrui333** [comment]
We probably need a rebuild for xmltoman bottle.

```
@chenrui333 ➜ /workspaces/homebrew-core (bump-libxcrypt-4.4.33) $ brew reinstall -s xmltoman
==> Downloading https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/project/xmltoman/xmltoman/xmltoman-0.4.tar.gz/xmltoman-0.4.tar.gz
==> Downloading from https://versaweb.dl.sourceforge.net/project/xmltoman/xmltoman/xmltoman-0.4.tar.gz/xmltoman-0.4.tar.gz
######################################################################## 100.0%
==> Reinstalling xmltoman 
==> perl Makefile.PL INSTALL_BASE=/home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4/libexec
==> make PERL5LIB=/home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4/libexec/lib/perl5
==> make install
==> ./xmltoman xml/xmltoman.1.xml > xmltoman.1
==> ./xmltoman xml/xmlmantohtml.1.xml > xmlmantohtml.1
🍺  /home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4: 55 files, 607.5KB, built in 5 seconds
==> Running `brew cleanup xmltoman`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
@chenrui333 ➜ /workspaces/homebrew-core (bump-libxcrypt-4.4.33) $ brew test xmltoman
==> Testing xmltoman
==> xmltoman 2>&1
```

**Comment by chenrui333** [comment]
ruby formulae fixes can be also tracked into each new ruby updates
- #116659
- #116660
- #116661

**Comment by chenrui333** [comment]
raised an upstream issue for zorba, https://github.com/28msec/zorba/issues/232

**Comment by chenrui333** [comment]
rebottle for xmltoman, https://github.com/Homebrew/homebrew-core/actions/runs/3615918468

**Pull request closed without merging**
