### PR TITLE
mdv 1.4.1

### PR DESCRIPTION
**Pull request by jyggen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Changed the install process a bit since mdv now ships with a `setup.py` and I figured it's better to just use that.

My first formula PR, so let me know if there's something I've missed! :)

### CODE REVIEW

**Comment by ilovezfs** [comment]
Current release is now 1.4.1, and this PR should be created using homebrew-pypi-poet (https://github.com/tdsmith/homebrew-pypi-poet)

**Comment by jyggen** [comment]
I updated the formula with the help of homebrew-pypi-poet.

**Comment by ilovezfs** [comment]
@jyggen thanks!

**Comment by MikeMcQuaid** [comment]
@ilovezfs 👍 from me if 👍 from you.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@jyggen nice work on your first formula PR! Thanks for taking the time to investigate homebrew-pypi-poet. You're awesome! :white_check_mark:

**Pull request closed without merging**
