### PR TITLE
git: Fix test

### PR DESCRIPTION
**Pull request by DoomHammer**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Cheery-pick of https://github.com/Linuxbrew/homebrew-core/pull/210

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Can you elaborate what this is "fixing" in the tests?

**Comment by DoomHammer** [comment]
Mentioned in the original PR, but short story is: Linuxbrew Travis uses `curl` for Tap so the original test fails. Attached tests are also a bit more robust, in my opinion.

**Comment by mikemcquaid** [comment]
Passing on this as it's a Linuxbrew rather than Homebrew issue. Thanks for the PR anyway, though.

**Comment by DoomHammer** [comment]
Thought this might be useful here as well, but I understand it is not necessary. Thanks for the input :)

**Pull request closed without merging**
