### PR TITLE
sbcl 2.0.2

### PR DESCRIPTION
**Pull request by samford**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Just curious, are the following two resources upgradable and removable?

```
  # Current binary versions are listed at https://sbcl.sourceforge.io/platform-table.html
  resource "bootstrap64" do
    url "https://downloads.sourceforge.net/project/sbcl/sbcl/1.2.11/sbcl-1.2.11-x86-64-darwin-binary.tar.bz2"
    sha256 "057d3a1c033fb53deee994c0135110636a04f92d2f88919679864214f77d0452"
  end

  patch :p0 do
    url "https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-make-doc.diff"
    sha256 "7c21c89fd6ec022d4f17670c3253bd33a4ac2784744e4c899c32fbe27203d87e"
  end
```

**Comment by samford** [comment]
In the case of macOS, we look at the "Darwin (Mac OS X)" entry on the [SBCL platform table](http://sbcl.sourceforge.net/platform-table.html) page in the comment, where 1.2.11 is still listed as the appropriate version for AMD64.

The `doc/make-doc.sh` patch also still applies.

**Comment by chenrui333** [comment]
Got you, thanks for the explanations.

**Pull request closed without merging**
