### PR TITLE
git-delta: add delta alias

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

The previous `delta` was removed last month: https://github.com/Homebrew/homebrew-core/pull/175148/commits/5b3058d832d2d1d0596ac005ce48da81a01caac5

Add an alias for https://github.com/dandavison/delta, which ships a `delta` executable

### CODE REVIEW

**Comment by chenrui333** [comment]
I actually dont think shipping the executable would justify adding an alias. :)

**Comment by branchvincent** [comment]
> I actually dont think shipping the executable would justify adding an alias. :)

Hmm but I think we provide plently of aliases solely because the command name is far more recognizable / likely to be used than the official name? It's certainly something I expect and a core use-case of aliases in my mind:

* [2ping](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/2ping) for `twoping`
* [ag](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/ag) for `the_silver_searcher`
* [az](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/az) for `azure-cli`
* [dlv](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/dlv) for `delve`
* [gpg](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/gpg) for `gnupg`
* [gs](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/gs) for `ghostscript`
* [gsed](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/gsed) for `gnu-sed`
* [hg](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/hg) for `mercurial`
* [java](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/java) for `openjdk`
* [kubectl](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/kubectl) for `kubernetes-cli`
* [mc](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/mc) for `midnight-commander`
* [mvn](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/mvn) for `maven`
* [npm](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/mvn) for `node`
* [nvim](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/mvn) for `neovim`
* [pgrep](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/mvn) / [pkill](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/pkill) for `proctools`
* [svn](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/svn) for `subversion`

Anyway, you get the point. It's just really frustrating UX when you know and use a command by the name `delta` but everytime you try `brew info delta` / `brew reinstall delta` etc you are reminded that it's actually called something else (and then you're forced to spend time remembering/searching to find what that special name is)

> FWIW, we can also consider just renaming the formula file to delta

Rename works for me too, I mainly just want `brew info delta` to work. But honestly, I'm a little surprised we're hesitant to add an alias

**Review by p-linnane — APPROVED** [review]

**Review by dtrodrigues — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Let's add the alias. If we want to rename it too then we can consider it in another PR.

**Comment by dandavison** [comment]
Hello, thanks for all the work on homebrew! I'm the delta author and co-maintainer. I'd support renaming the formula to "delta" with "git-delta" as an alias, if that's one of the suggestions.

**Pull request merged**
