### PR TITLE
Golang 1.14.5

### PR DESCRIPTION
**Pull request by blaedj**
Update formula to latest security release

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Nivl** [comment]
I _think_ the Actions need to be restarted. According to the other PRs it should take about 10/15min to pass, and it's been running for over an hour now 🤔

**Comment by blaedj** [comment]
I didn't see a way to restart the actions from the UI, so I pushed an amended commit, maybe it'll work? 🤞

**Comment by Rylan12** [comment]
> I _think_ the Actions need to be restarted. According to the other PRs it should take about 10/15min to pass, and it's been running for over an hour now 🤔

@Nivl the CI makes sure that `go` builds/tests/audits successfully but also checks all formulae that depend on `go`. This can take a long time for formulae that have a lot of dependents. `go` has over 400 formulae that depend on it, so this is expected to take a while.

In case you're curious, you can see which formulae will be checked by the CI with `brew uses --include-build --include-test --recursive <formula>`

**Comment by Nivl** [comment]
> > I _think_ the Actions need to be restarted. According to the other PRs it should take about 10/15min to pass, and it's been running for over an hour now 🤔
> 
> @Nivl the CI makes sure that `go` builds/tests/audits successfully but also checks all formulae that depend on `go`. This can take a long time for formulae that have a lot of dependents. `go` has over 400 formulae that depend on it, so this is expected to take a while.
> 
> In case you're curious, you can see which formulae will be checked by the CI with `brew uses --include-build --include-test --recursive <formula>`

Ah, interesting! Thanks for letting me know, that's very useful! My apologies for the bad advice @blaedj!

**Comment by SMillerDev** [comment]
Now the old build will need to be canceled though, to avoid wasting CI time. @Rylan12 could you kill it?

**Comment by Rylan12** [comment]
Done!

**Comment by Bo98** [comment]
I can already say, from past experience, that `godep` will need a revision bump here too.

**Comment by Bo98** [comment]
Usually we do one commit per formula but I did it for you while merging.

**Comment by blaedj** [comment]
> Usually we do one commit per formula but I did it for you while merging.

Good to know, I'll keep that in mind next time, thanks!

**Comment by chenrui333** [comment]
go upgrade failure tracker, ##56539

**Pull request closed without merging**
