### PR TITLE
jpeg-turbo: un-keg-only

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Now that most `jpeg` dependents have been switched to `jpeg-turbo`, it
makes sense to link this instead of `jpeg`.

This will allow us to remove some workarounds needed from `jpeg-turbo`
being keg-only (e.g. fe8e1dc94e37c39de1700920ba98a52dba280b16).

### CODE REVIEW

**Comment by carlocab** [comment]
Should be merged simultaneously with #107511.

**Comment by carlocab** [comment]
Some dependents may still try to install `jpeg`, which will result in `brew link` conflicts.

**Comment by cho-m** [comment]
Leaving a list of remaining `jpeg` dependent formulae that haven't been deprecated/disabled.

With open PRs:
- [ ] `argyll-cms` - #106695
- [ ] `astrometry-net` - #107220
- [ ] `gdal` - #107250
- [ ] `gmic` - #107090
- [ ] `gocr` - #107220
- [ ] `halide` - #106719
- [ ] `harbour` - #107019
- [ ] `lanraragi` - #106961
- [ ] `libsixel` - #107284
- [ ] `netpbm` - #107220
- [ ] `openclonk` - #103535
- [ ] `opencv` - #107250
- [ ] `openimageio` - #107244
- [ ] `siril` - #107220
- [ ] `visp` - #107250
- [ ] `vtk` - #107250
- [ ] `xfig` - #107220

Without PRs:
- [ ] `mapnik` - may add along with `opencv`/`gdal` PR
- [ ] `mpv` - we are having trouble rebuilding on our Big Sur runner
- [ ] `itk`
- [ ] `vtk@8.2`

Also indirect broken linkage:
- [ ] `texlive` - #106766

**Comment by carlocab** [comment]
All but one of the CI failures are `brew link jpeg` failures.

I think this should be fine to merge.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
