### PR TITLE
bdw-gc: apply multithreading patch

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Also, switch crystal dependency to `bdw-gc`.

Follow up to discussion at #70236. CC @bcardiff

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by bcardiff** [comment]
What is the value of `HOMEBREW_LIBRARY_PATHS` ?
I think that `ENV["CRYSTAL_LIBRARY_PATH"] = ENV["HOMEBREW_LIBRARY_PATHS"]` should be done after `ENV.append_path "PATH", "boot/bin"` So the resulting crystal binary will have `/usr/local/opt/bdw-gc/lib/libgc.1.dylib` as a dependency. The shards binary has that, but the generated crystal binary it does not.

It does not bother much, it is currently linking against the static gc shipped in the boot resource. (And actually it has been like that since the beginnings of time probably)

**Comment by carlocab** [comment]
>So the resulting crystal binary will have `/usr/local/opt/bdw-gc/lib/libgc.1.dylib` as a dependency. 

Built this locally, and this is already the case. `HOMEBREW_LIBRARY_PATHS` just includes the library paths of the declared dependencies and system libraries.

**Comment by carlocab** [comment]
So should `CRYSTAL_LIBRARY_PATH` be included in `crystal_build_opts`? Or should `CRYSTAL_CONFIG_LIBRARY_PATH` be changed?

**Comment by bcardiff** [comment]
Sorry for the delay, we should tweak `CRYSTAL_LIBRARY_PATH`. That _prepends_ library paths to the compile process. But when I try that, the embedded libraries from the boot resource are still available and I think those are linked still. I would need to debug a bit why is not picking the HOMEBREW_LIBRARY_PATHS first. Worst case, deleting the embeded gc should do the trick.

The `CRYSTAL_CONFIG_LIBRARY_PATH` is the default library path by the compiler. Useful only if the path where the compiler will be installed is known in advance. In brew (and tar.gz distributions) we use a wrapper script to set `CRYSTAL_LIBRARY_PATH` and leave `CRYSTAL_CONFIG_LIBRARY_PATH` unused/empty.

The shards binary is compiled with the new crystal and not the boot one. That's why it's picking the brew bdw-gc.

**Comment by carlocab** [comment]
Right, so is the fix to just set `CRYSTAL_LIBRARY_PATH` earlier, or is it something else?

I guess `crystal` isn't picking these paths up because the paths in `HOMEBREW_LIBRARY_PATHS` are injected via compiler flags when calls are made to the compiler shim during the build. So there's currently no way for the bootstrap `crystal` to discover these.

**Comment by bcardiff** [comment]
When setting earlier

`ENV["CRYSTAL_LIBRARY_PATH"] = ENV["HOMEBREW_LIBRARY_PATHS"]` 

the generated crystal binary does not depend on `/usr/local/opt/bdw-gc/lib/libgc.1.dylib`.

That was unexpected on my end.

If besides setting `ENV["CRYSTAL_LIBRARY_PATH"] = ENV["HOMEBREW_LIBRARY_PATHS"]`  a `rm_rf (buildpath/"boot"/"embedded"/"lib")` is done, then the binary will depend on `/usr/local/opt/bdw-gc/lib/libgc.1.dylib`. So 👍 , but is a bit ugly to remove those files I guess.

I also tried, without removing the embedded lib director to use `ENV["CRYSTAL_LIBRARY_PATH"] = "/usr/local/Cellar/bdw-gc/8.0.4_2/lib:#{ENV["HOMEBREW_LIBRARY_PATHS"]}"`. This worked as a charm and the compiler depends on `/usr/local/opt/bdw-gc/lib/libgc.1.dylib`. 

But on the other hand, `HOMEBREW_LIBRARY_PATHS` includes `/usr/local/lib`, which has symlinks:

```
/usr/local/lib/libgc.a -> ../Cellar/bdw-gc/8.0.4_2/lib/libgc.a
/usr/local/lib/libgc.dylib -> ../Cellar/bdw-gc/8.0.4_2/lib/libgc.dylib
```

So I don't understand why those are not used. Also using `ENV["CRYSTAL_LIBRARY_PATH"] = "/usr/local/opt/bdw-gc:#{ENV["HOMEBREW_LIBRARY_PATHS"]}"` does not work. The symlink in /usr/local/opt/bdw-gc are not picked.

The compiler will pass to the linker `-Lpath1 -Lpath2 -lgc` when `CRYSTAL_LIBRARY_PATH="path1:path2"`. There is nothing more crystal is doing. If you want to see this details change `crystal_build_opts << "FLAGS=--no-debug"` to `crystal_build_opts << "FLAGS=--no-debug --verbose"` and use `$ brew install --build-from-source --verbose Formula/crystal.rb`

**Comment by bcardiff** [comment]
> > Useful only if the path where the compiler will be installed is known in advance.
>
>  Do we not know this in advance?

No, since brew can be installed in different locations.

**Comment by carlocab** [comment]
>No, since brew can be installed in different locations.

Ah, you're thinking of users who install brew into an unsupported prefix. But, fair enough, we don't have to break it for them if we know how to make the bottle relocatable.

>I also tried, without removing the embedded lib director to use `ENV["CRYSTAL_LIBRARY_PATH"] = "/usr/local/Cellar/bdw-gc/8.0.4_2/lib:#{ENV["HOMEBREW_LIBRARY_PATHS"]}"`

This seems like a cleaner solution. Will open a PR to try that.

**Pull request closed without merging**
