### PR TITLE
flyctl 0.0.424

### PR DESCRIPTION
**Pull request by flyio-buildbot**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
This formula should be throttled. Releases happen too often. See https://github.com/superfly/flyctl/releases

**Comment by carlocab** [comment]
Throttle when version is divisible by 5 or 10? We can add you to `CODEOWNERS` to make sure we remember to add the throttle.

**Comment by jsierles** [comment]
What does it mean to throttle a formula?

**Comment by chenrui333** [comment]
> What does it mean to throttle a formula? We sometimes have to release often to get hotfixes out, but other times, a release will be days apart. Is there a better way to do this besides having homebrew 4-5 versions behind?

based on the history, you never had slow release cadence, right? (it is like always one release per day)
https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+flyctl+

**Comment by jsierles** [comment]
Yeah, recently the cadence is high. What would be the best solution for us to ensure the latest version is available, even at a high cadence? We used to run a cask. If we have to move back to that, so be it.

**Comment by SMillerDev** [comment]
A cask doesn't fix the strain on Homebrew maintainers from just this package. If you release very often the package will have to be throttled to keep the maintainer load manageable. If you absolutely need to have the latest release out the second you press the button you can maintain a tap where you are in charge of the releases because you are the maintainer

**Comment by jsierles** [comment]
OK, thanks. We'll consider moving back to a tap.

Meanwhile, could the throttle be set to something lower than 5 patch versions? Or based on minor version bumps instead of patch? Using minor versions would be a good way for us to indicate the severity of the release, rather than throttling be based on an arbitrary number of releases.

**Comment by SMillerDev** [comment]
> Meanwhile, could the throttle be set to something lower than 5 patch versions? Or based on minor version bumps instead of patch? Using minor versions would be a good way for us to indicate the severity of the release, rather than throttling be based on an arbitrary number of releases.

Currently, no. But a pull request that adds this feature would be very welcome.

**Comment by chenrui333** [comment]
> OK, thanks. We'll consider moving back to a tap.
> 
> Meanwhile, could the throttle be set to something lower than 5 patch versions? Or based on minor version bumps instead of patch? Using minor versions would be a good way for us to indicate the severity of the release, rather than throttling be based on an arbitrary number of releases.

if it is indeed critical patch fixes, we can accommodate, I think the general sentiment in here is just about the CI resources,  not like release three times a day or something like that. Does that paint the better picture?

**Comment by jsierles** [comment]
Thanks, that info helps. The problem is that we're early stage and our CLI is the core of the platform, being used on a daily basis, in CI, etc. We're releasing both fixes and features in the same fashion. We'll discuss what to do about this internally.

**Comment by chenrui333** [comment]
> Thanks, that info helps. The problem is that we're early stage and our CLI is the core of the platform, being used on a daily basis, in CI, etc. We're releasing both fixes and features in the same fashion. We'll discuss what to do about this internally.

Thanks for your understanding, also it does not have to be automated if you release that frequently, we as maintainers bump the formulae versions pretty frequently as well.

**Comment by jsierles** [comment]
Sorry, what do you mean? We don't need to submit PRs?

**Comment by chenrui333** [comment]
@jsierles this coming up again as a bit hassle for our sonoma bottling effort cc @fxcoudert, can you make sure not releasing that frequently? 

image

**Comment by chenrui333** [comment]
link this PR to the new chat, https://github.com/Homebrew/homebrew-core/pull/174298

**Pull request closed without merging**
