### PR TITLE
minizinc 2.3.0

### PR DESCRIPTION
**Pull request by Dekker1**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Test is failing:

```
==> /usr/local/Cellar/minizinc/2.3.0/bin/mzn2doc /usr/local/Cellar/minizinc/2.3.0/share/examples/functions/warehouses.mzn
Error: cannot open file '/usr/local/Cellar/minizinc/2.3.0/share/examples/functions/warehouses.mzn'.
```

**Comment by javian** [comment]
The file seems to have been moved to https://github.com/MiniZinc/libminizinc/tree/master/tests/examples

**Comment by Dekker1** [comment]
Since the test runs `mzn2doc` and not the MiniZinc compiler, it is probably better to run it on a library file that actually has documentation. I've changed the test to run on the `all_different.mzn` definition in the standard library.

**Comment by fxcoudert** [comment]
Thanks @Dekker1

**Pull request closed without merging**
