### PR TITLE
Grafana v4.2.0

### PR DESCRIPTION
**Pull request by torkelo**
Version update to 4.2.0 and changed yarn to proper homebrew dependency.

Tested and build works on my macbook running Sierra.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```

Running "karma:test" (karma) task
22 03 2017 15:14:53.207:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
22 03 2017 15:14:53.208:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
22 03 2017 15:14:53.212:INFO [launcher]: Starting browser PhantomJS
22 03 2017 15:14:53.454:ERROR [phantomjs.launcher]: 2017-03-22 15:14:53.453 phantomjs[72127:8788399] -[_NSXPCDistantObjectWithError performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: unrecognized selector sent to instance 0x7f8bf390cff0

22 03 2017 15:14:53.454:ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

22 03 2017 15:14:53.454:ERROR [launcher]: Cannot start PhantomJS
	
22 03 2017 15:14:53.457:INFO [launcher]: Trying to start PhantomJS again (1/2).
22 03 2017 15:14:53.681:ERROR [phantomjs.launcher]: 2017-03-22 15:14:53.680 phantomjs[72129:8788550] -[_NSXPCDistantObjectWithError performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: unrecognized selector sent to instance 0x7f8608701c40

22 03 2017 15:14:53.681:ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

22 03 2017 15:14:53.681:ERROR [launcher]: Cannot start PhantomJS
	
22 03 2017 15:14:53.682:INFO [launcher]: Trying to start PhantomJS again (2/2).
22 03 2017 15:14:53.913:ERROR [phantomjs.launcher]: 2017-03-22 15:14:53.912 phantomjs[72130:8788709] -[_NSXPCDistantObjectWithError performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: unrecognized selector sent to instance 0x7fd19303dfe0

22 03 2017 15:14:53.913:ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

22 03 2017 15:14:53.913:ERROR [launcher]: Cannot start PhantomJS
	
22 03 2017 15:14:53.914:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
Warning: Task "karma:test" failed. Use --force to continue.

Aborted due to warnings.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: node_modules/grunt-cli/bin/grunt build
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 
```

**Comment by ilovezfs** [comment]
And a bit of trouble on the Sierra CI, it seems
```
==> brew install ./grafana-4.2.0.sierra.bottle.tar.gz
==> brew test grafana --verbose
==> FAILED
Testing grafana
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170403-22055-12caodo.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/grafana.rb --verbose
==> /usr/local/Cellar/grafana/4.2.0/bin/grafana-server -v
Error: grafana: failed
Failed executing: /usr/local/Cellar/grafana/4.2.0/bin/grafana-server -v
/usr/local/Homebrew/Library/Homebrew/formula.rb:1840:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1778:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1778:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/grafana.rb:95:in `block in <class:Grafana>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1677:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:886:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1676:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1670:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by dunn** [comment]
Any progress here?

**Comment by fxcoudert** [comment]
Thanks @torkelo for the pull request!

**Comment by ilovezfs** [comment]
For the record: the phantomjs were never fixed here.

**Pull request closed without merging**
