### PR TITLE
tvnamer: Alter test string interpolation

### PR DESCRIPTION
**Pull request by dj-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Modified test block string interpolation statements to use to_s

### CODE REVIEW

**Comment by DomT4** [comment]
I'm unsure that passing `.to_s` here is particularly necessary. The audit failure is moaning about using `#{}` unnecessarily, which is fine, but the referenced strings are part of the test & easily verified as being actual strings, so think we're fine removing the `#{}` stuff without also chucking in `to_s`.

**Comment by dj-m** [comment]
Of course! 😝 Updated now. Thanks @DomT4

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/f036f51489d0718fc56943ca0e49929a50976db7. Thanks @dj-m! 😃

**Comment by MikeMcQuaid** [comment]
Nice work @dj-m ⭐

**Pull request merged**
