### PR TITLE
dvc 0.91.3

### PR DESCRIPTION
**Pull request by efiop**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks @efiop! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by chenrui333** [comment]
Trying the latest release

**Comment by efiop** [comment]
@chenrui333 Thank you! Was about to submit a new PR :slightly_smiling_face: Are you using dvc, btw? Or just updating it along the way?

**Comment by chenrui333** [comment]
not really, maybe I should recommend DS folks using it.

My expertise is mostly on the web platform engineering side.

**Comment by efiop** [comment]
@chenrui333 Got it :slightly_smiling_face: Well, it is also useful in general for storing binary files or big text files in your git repo, like `git lfs/annex`. So not only for DS guys :wink: Anyway, thank you so much for all the updates and reviews! :pray:

**Comment by chenrui333** [comment]
Speaking of managing large files, how does this tool compare with https://git-annex.branchable.com/? Thanks!

**Comment by efiop** [comment]
@chenrui333 Have to clarify that I'm the maintainer of DVC, so I'm probably biased :slightly_smiling_face: If we talk specifically about features for local large files, then they are pretty comparable, but there are a few key differences. Unlike annex, dvc _natively_ supports a great variety of cloud providers (s3/gs/google drive/hdfs/sftp/etc). DVC is much easier to use and understand, it has great documentation. It is fully written in python (while annex - in haskel), so it is easy to extend and contribute to for anyone. DVC also has lots of additional features, one of those is the fact that it can tie your code and artefacts using pipelines (think of it like portable Makefiles)
so you not only be able to download some artefact but will also be able to reproduce it in one command. And many other features, especially for DS/ML guys with many more features coming :)

**Comment by chenrui333** [comment]
I see, that is really good to know. :)

**Pull request closed without merging**
