### PR TITLE
libjcat 0.1.14 (new formula)

### PR DESCRIPTION
**Pull request by hughsie**
This is needed as the second of the two deps required by fwupd, which has 52 stars, 370 forks and 2300 stars on GitHub.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by hughsie** [comment]
Whilst this package isn't _notable enough_ it's a dep of one that has 52 stars, 370 forks and 2300 stars on GitHub: https://github.com/fwupd/fwupd -- it'll need CI-no-fail-fast

**Comment by chenrui333** [comment]
@hughsie can you pipe in all the new formulae in one PR, I think that also works for us. :)

**Comment by hughsie** [comment]
@chenrui333 to double check; you want me to push this commit and the fwupd commit into https://github.com/Homebrew/homebrew-core/pull/140779 -- that has two approvals now, and I didn't want to "ruin" it by adding commits.

**Comment by hughsie** [comment]
@chenrui333 oh the other one got merged, lets stick to this one.

**Review by chenrui333 — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
