### PR TITLE
parallel 20210822

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by bevanjkay** [comment]
@alebcay @carlocab This release is not currently marked as 'stable' upstream, and therefore livecheck is still returning version `20210622`

**Comment by alebcay** [comment]
I'm not sure what the significance of that is, this and the previous (20210722) release were not marked as such; neither was `20210522`.

It's unclear to me if they're just releasing unstable things now (which ideally should be noted as such, rather than that being implied) or if they're just neglecting to mention that the more recent releases are stable.

**Comment by bevanjkay** [comment]
@alebcay Here's the reference (https://github.com/Homebrew/homebrew-core/pull/61063#issuecomment-691680144) to why livecheck is looking for `stable` releases only. I do use parallel, however, I'm not familiar with upstream's development. I guess we should either use stable releases or update the livecheck to match the latest version present on the homepage.

It *may* be worth noting the from the FTP archive, parallel-latest.tar.gz does provide version `202108221

**Comment by carlocab** [comment]
I don't think upstream use the term `stable` the way we do. If you read through their release notes, the releases tagged as stable are just the ones where no new features have been added. I think what we want to be tracking are the releases they consider latest.

**Pull request closed without merging**
