### PR TITLE
libsvg-cairo: fix for ARM/M1 Macs

### PR DESCRIPTION
**Pull request by areese**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [-] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This relies on https://github.com/Homebrew/homebrew-core/pull/74623, which is for libsvg, and very similar.
make check doesn't seem to run any sort of tests for libsvg or libsvg-cairo, so I'm not sure what to do as far as tests.

### CODE REVIEW

**Comment by Bo98** [comment]
> I'm not sure what to do as far as tests

If you can't think of anything then you can omit the test block entirely like it was before. As it stands, it's currently ok for `brew audit --strict` to fail for older formulae (but not the non-strict version).

If we can think of something to test though, then it is of course useful to add a test. In this case, a basic C program that maybe does nothing more than link to the library and initialise it (`svg_cairo_create`) is probably sufficient. Don't worry though if you can't figure that out - it won't be a blocker!

**Comment by areese** [comment]
I had the same idea, is there a good place to store a .c file for a test?  I'm not very familiar with how brew builds and links, but I'd be happy to throw together something that tries to at least link against libsvg and libsvg-cairo, maybe even load a sample svg file.

Also, this will fail until the libsvg fix is merged, I wasn't sure that the work there was complete, so I didn't pull it into this fork.

**Comment by Bo98** [comment]
> I had the same idea, is there a good place to store a .c file for a test?

The current working directory or the pre-set `testpath` variable (they should be the same thing). This directory is temporary and is auto-cleaned when the test is complete.

> Also, this will fail until the libsvg fix is merged, I wasn't sure that the work there was complete, so I didn't pull it into this fork.

I'll get that PR merged soon.

**Comment by areese** [comment]
Perfect, ty.  I'll look at popt and add some basic tests to both libs if I can.

**Comment by areese** [comment]
https://github.com/Homebrew/homebrew-core/pull/74623 is merged so this should work now.  The tests are coming in a separate pr

**Comment by Bo98** [comment]
Thanks! Can you rebase on master (since your branch will currently be based before the `libsvg` fix)?

Also remove the test block entirely if you're not adding it in this PR.

**Comment by areese** [comment]
I'll do both shortly, thank you

**Comment by areese** [comment]
@Bo98 done.

I didn't touch the license clause, it shouldn't have changed with my original patch that was an oversight.

Once this merges, then svg2pdf and svg2png work.

**Review by Bo98 — APPROVED** [review]
Thanks @areese!

**Comment by Bo98** [comment]
Bottles have been built and uploaded for `libsvg-cairo`, `svg2pdf` and `svg2png`. 🎉

**Comment by areese** [comment]
Thank you!

**Pull request merged**
