### PR TITLE
irrlicht 1.8.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
The `inreplace` needs updating.

**Comment by carlocab** [comment]
```
Undefined symbols for architecture arm64:
  "_inflateValidate", referenced from:
      _png_inflate_claim in pngrutil.o
ld: symbol(s) not found for architecture arm64
```

**Comment by FnControlOption** [comment]
The [changelog](https://irrlicht.sourceforge.io/forum/viewtopic.php?f=2&t=52775) mentions libpng being updated but libpng isn’t a dependency here. Should the vendored libpng be replaced with Homebrew’s?

**Comment by carlocab** [comment]
Probably, yes.

**Comment by FnControlOption** [comment]
Here's a patch that updates Irrlicht to use Homebrew libraries: https://gist.github.com/FnControlOption/cea08f7fc2d072dd169a936e912dcf59 (I don't know why but I keep getting `Hunk #1 FAILED` when I run `brew install irrlicht` with the patch)

- Deleted references to dependency sources
- Fixed compile error from using Homebrew's jpeg 9d instead of Irrlicht's jpeg 8d
- Link libpng.dylib and libjpeg.dylib
- Add libpng and jpeg `include` directories to search paths
- Define macros such as `NO_IRR_USE_NON_SYSTEM_LIB_PNG_` to use system/Homebrew libraries

`depends_on` and `uses_from_macos` to add to irrlicht.rb:

```rb
  depends_on "jpeg"
  depends_on "libpng"

  uses_from_macos "bzip2"
  uses_from_macos "zlib"
```

**Comment by carlocab** [comment]
Your patch hardcodes `/usr/local/opt` in some places -- can we make that more portable?

**Pull request closed without merging**
