### PR TITLE
minimal-racket 7.4

### PR DESCRIPTION
**Pull request by lukel97**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
21:10:32   context...:
21:10:32    /private/tmp/minimal-racket-20191015-99736-6zglgn/racket-7.4/collects/compiler/private/xform.rkt:4072:10: loop
21:10:32    /private/tmp/minimal-racket-20191015-99736-6zglgn/racket-7.4/collects/compiler/private/xform.rkt:4109:10: loop
21:10:32    /private/tmp/minimal-racket-20191015-99736-6zglgn/racket-7.4/collects/compiler/private/xform.rkt:8:2: xform
21:10:32    "/private/tmp/minimal-racket-20191015-99736-6zglgn/racket-7.4/src/racket/gc2/xform-mod.rkt": [running body]
21:10:32    temp37_0
21:10:32    for-loop
21:10:32    run-module-instance!125
21:10:32    "/private/tmp/minimal-racket-20191015-99736-6zglgn/racket-7.4/collects/setup/main.rkt": [running body]
21:10:32    temp37_0
21:10:32    for-loop
21:10:32    run-module-instance!125
21:10:32    perform-require!78
21:10:32 env XFORM_USE_PRECOMP=xsrc/precomp.h ../racketcgc  -O "info@compiler/cm error" -l- setup --boot ./../../setup-go.rkt ../../compiled --tag ++out ./xform-mod.rkt --depends --cpp "clang -E -I./.. -I./../include -I./../../rktio -I../../rktio -DOS_X -D_DARWIN_UNLIMITED_SELECT  -fno-common -DUSE_SENORA_GC  -Wno-nullability-completeness  "  --keep-lines -o ++out xsrc/env.c ./../src/env.c
21:10:32 make[4]: *** [xsrc/salloc.c] Error 1
21:10:32 make[4]: *** Waiting for unfinished jobs....
21:10:32 make[3]: *** [all] Error 2
21:10:32 make[2]: *** [3m] Error 2
21:10:32 make[1]: *** [3m] Error 2
21:10:32 make: *** [all] Error 2
21:10:32

**Comment by bubba** [comment]
Fixed by [this](https://github.com/racket/racket/commit/27c1847ce8e77b4d0024c10a67ecd2316dbbda33), will bring this patch in now (thanks @mflatt !)

**Comment by chenrui333** [comment]
07:40:43 raco setup: --- checking package dependencies ---                  [12:40:42]
07:40:43 /Applications/Xcode.app/Contents/Developer/usr/bin/make install-common-last
07:40:43 /Applications/Xcode.app/Contents/Developer/usr/bin/make fix-paths
07:40:43 if [ "" != "" ]; then \
07:40:43           if [ "" = "" ]; then \
07:40:43             racket/racketcgc  -u \
07:40:43               "./../collects/setup/unixstyle-install.rkt" \
07:40:43               make-install-destdir-fix "./.." \
07:40:43               "/usr/local/Cellar/minimal-racket/7.4/bin" "/usr/local/Cellar/minimal-racket/7.4/collects" "/usr/local/Cellar/minimal-racket/7.4/doc" "/usr/local/Cellar/minimal-racket/7.4/lib" "/usr/local/Cellar/minimal-racket/7.4/include" "/usr/local/Cellar/minimal-racket/7.4/lib" "/usr/local/Cellar/minimal-racket/7.4/share" "/usr/local/Cellar/minimal-racket/7.4/etc" "/usr/local/Cellar/minimal-racket/7.4/share/applications" "/usr/local/Cellar/minimal-racket/7.4/man" "yes"; \
07:40:43           fi \
07:40:43         fi
07:40:43 /Applications/Xcode.app/Contents/Developer/usr/bin/make preserve-raco-pkg-default-scope
07:40:43 :
07:40:43 cp "./COPYING-libscheme.txt" "./COPYING_LESSER.txt" "./COPYING.txt" "/usr/local/Cellar/minimal-racket/7.4/share"/
07:40:43 Error: An exception occurred within a child process:
07:40:43   Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/local/etc/racket/config.rktd
07:40:43 
07:40:43 ==> git -C homebrew/homebrew-core checkout master -f
07:40:47

**Comment by fxcoudert** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
