### PR TITLE
duck 8.2.0

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by dkocher** [comment]
As with #90118 there seems to be an issue building the ARM bottle.

```
Error: duck: no bottle available!
You can try to install from source with:
```

**Comment by jbburf** [comment]
Still seeing this as of today on M1 running Monterey 12.1.

**Comment by chenrui333** [comment]
@jbburf the test failed on Monterey arm build, which prevents from uploading the bottle. (it somehow works for me in my local)

**Comment by dkocher** [comment]
> @jbburf the test failed on Monterey arm build, which prevents from uploading the bottle. (it somehow works for me in my local)

It seems to be a codesign issue (#92180) I have been unable to resolve.

**Comment by jbburf** [comment]
> > @jbburf the test failed on Monterey arm build, which prevents from uploading the bottle. (it somehow works for me in my local)
> 
> It seems to be a codesign issue (#92180) I have been unable to resolve.

Thanks @dkocher, I was able to build from source so I'm good and will use the bottle for the next update (if the code sign issue is fixed).

**Pull request closed without merging**
