### PR TITLE
datasette 0.47.1 (new formula)

### PR DESCRIPTION
**Pull request by simonw**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[Datasette](https://datasette.readthedocs.io/en/stable/) is an open source multi-tool for exploring and publishing data, written in Python.

I've made this formula available as a tap which can be installed like so:

    brew install simonw/datasette/datasette

See https://github.com/simonw/homebrew-datasette for details.

### CODE REVIEW

**Comment by simonw** [comment]
Here's the output of `brew test datasette`:
```
% brew test datasette
==> Testing simonw/datasette/datasette
==> /usr/local/Cellar/datasette/0.47.1/bin/datasette --get '/:memory:.csv?sql=select+3*5'
==> /usr/local/Cellar/datasette/0.47.1/bin/datasette --get '/'
```
Datasette usually runs as a localhost web server, but I added a feature where running `--get /path` simulates running a request through the the server and outputs the HTTP response to standard-out. This was useful for building the tests for Homebrew but is also a great feature for the software to have generally: https://datasette.readthedocs.io/en/stable/getting_started.html#datasette-get

**Comment by dawidd6** [comment]
Please squash your commits.

**Comment by simonw** [comment]
I was hoping this commit could be landed using the "squash merge" option, but I can squash the commits and force push to the branch instead if that's the Homebrew preferred way.

**Comment by simonw** [comment]
(For my own notes) I ran this:

```
git rebase -i HEAD~2
```
Then typed `s` next to the license commit. This merged the two into one. Then I ran this:
```
git push --force
```

**Review by dawidd6 — APPROVED** [review]

**Comment by simonw** [comment]
Thanks @dawidd6!

**Pull request closed without merging**
