### PR TITLE
broot 0.11.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
Error: broot: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/broot-test-20191222-34859-d65rq5/output.txt
```

**Comment by chenrui333** [comment]
```
22:13:46 ==> brew test broot --verbose
22:13:49 ==> FAILED
22:13:49 Testing broot
22:13:49 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191231-52232-tibfly.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/broot.rb --verbose
22:13:49 Error: broot: failed
22:13:49 An exception occurred within a child process:
22:13:49   Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/broot-test-20191231-52233-1vamoa9/output.txt
```

**Comment by alebcay** [comment]
`broot` 0.11.7 is now available.

**Comment by chenrui333** [comment]
Let me try build and test locally.

**Comment by chenrui333** [comment]
It is still has the same issue for the formula:

```
$ brew test broot
Testing broot
Error: broot: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/broot-test-20200111-31388-1jdyksa/output.txt
```

**Comment by chenrui333** [comment]
Let's just make our life easier and I have updated the test part.

The pain point is with 

```
==> /usr/local/Cellar/broot/0.11.7/bin/broot --dates

Broot should be launched using a shell function (see https://github.com/Canop/b
root for explanations).
The function is either missing, old or badly installed.
Can I install it now? [Y n]
```

**Comment by fxcoudert** [comment]
Version test is a really bad test, so we only do that if we have absolutely no other possible way. The test did pass previously, so there was some functionality that we could test.

**Comment by dakira** [comment]
@fxcoudert what do you suggest? The test is not working because of the needed install step. A solution could be to actually add the needed shell function to the test env to simulate broot being installed already, the test should work then.

**Comment by chenrui333** [comment]
@dakira, @fxcoudert and I have just chatted offline about how to get it merged. 

I have updated the formula test block and tested locally. We should be able to ship this upgrade soonsih.

**Comment by chenrui333** [comment]
Filed a separate PR on the new release, #48947

**Pull request closed without merging**
