### PR TITLE
cabal-install 3.2.0.0

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fishtreesugar** [comment]
There is a bit strange the bootstrap script does not follow the bound of the package, and I decide to patch the script for respect the package's bounds

**Comment by Bo98** [comment]
Upstream patches more: https://github.com/haskell/cabal/commit/b6f7ec5f3598f69288bddbdba352e246e337fb90

**Comment by fishtreesugar** [comment]
@Bo98 Thanks for your suggestion!

**Comment by Bo98** [comment]
The patch block should be outside of `install`.

We generally prefer `full_index` patches as well: https://github.com/haskell/cabal/commit/b6f7ec5f3598f69288bddbdba352e246e337fb90.patch?full_index=1

**Comment by Bo98** [comment]
The directory structure used by the git repo, and thus the patch, is different. Maybe try `patch :p2 do`.

**Comment by Bo98** [comment]
Thanks

**Pull request closed without merging**
