### PR TITLE
aws-elasticbeanstalk: Switch to Python 3 and improve the test slightly

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Part of #47050. See individual commits for more detail.

### CODE REVIEW

**Comment by Bo98** [comment]
There's a few resources for 2.7 compat that could be removed and may be causing problems with the build like `backports.ssl_match_hostname` and `enum34`.

**Comment by issyl0** [comment]
If anyone has a clue as to why the test is failing, I'd appreciate a pointer. 😳 I've locally tried every permutation of `\n`, `2>&1` and `.strip` as in other `shell_output` examples.

**Comment by issyl0** [comment]
Thanks to @SMillerDev for helping with the test. It was the one thing I hadn't tried to fix it. 😬

**Comment by issyl0** [comment]
@Bo98 I probably shouldn't stick a "ready to merge" label on this, should I? Would you be able to give it a review first? CI is green now, though.

**Comment by SMillerDev** [comment]
You're as much a maintainer as the rest of us.

**Review by Bo98 — APPROVED** [review]
If it's green I'm happy with that.

This should be pretty trivial to migrate to 3.8 too since it depends on nothing else but Python and nothing else depends on it. I'll make sure it is noted in #47274.

**Comment by issyl0** [comment]
Thanks, @Bo98! I'm still pretty unconfident with the workflows in this repo - can I merge this as is via the GitHub UI or does it need more things?

**Comment by Bo98** [comment]
This one should be merged via `brew pull --bottle`. I’ll do it in a few hours if someone else hasn’t.

**Comment by SMillerDev** [comment]
That's not needed, no bottles are build.

**Comment by Bo98** [comment]
But there is a bottle block in this formula?

**Comment by Bo98** [comment]
Actually this should also have a revision bump - I forgot about that.

**Comment by SMillerDev** [comment]
No version change = no uploaded bottle changes

**Comment by Bo98** [comment]
Yes, but there should be a revision change as we changed between Python 2 and 3.

**Comment by chenrui333** [comment]
Oh, I just saw the `ready to merge` tag and merged the PR, is there anything that I should be concerned about? :)

**Comment by Bo98** [comment]
I think there's a disagreement on whether this should have had a revision bump. Perhaps best to propose the question in a separate PR.

**Comment by chenrui333** [comment]
I think I did republish the bottle files, not sure if that helps.

```
==> Applying patch
Applying: aws-elasticbeanstalk: Switch to Python 3
Applying: aws-elasticbeanstalk: Improve the test slightly
Applying: aws-elasticbeanstalk: update 3.14.6 bottle.
==> Publishing on Bintray: aws-elasticbeanstalk 3.14.6
{"files":3}
==> Verifying bottles published on Bintray
Verifying bottle: aws-elasticbeanstalk-3.14.6.catalina.bottle.1.tar.gz
Waiting on Bintray.....
######################################################################## 100.0%
```

**Comment by chenrui333** [comment]
The revision bump seems not quite needed (even though semantically it needs to happen)

**Comment by Bo98** [comment]
The problem is that people with existing installations will still have a dependency to python@2 - and we plan to remove python@2 at the end of the year.

**Comment by Bo98** [comment]
It seems like there's a 3.16.0 available now anyway so I suppose we could just try update the formula to that and then the case of whether it needs a revision bump no longer matters.

**Pull request closed without merging**
