### PR TITLE
cubejs-cli 0.33.50

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Unwanted system libraries: 
  /lib/x86_64-linux-gnu/libz.so.1
```

**Comment by p-linnane** [comment]
@iMichka We've tried this, but it looks like @alebcay [found the issue](https://github.com/Homebrew/homebrew-core/pull/136210#issuecomment-1630184914):

>The linkage to system `libz.so` originates from `libexec/"lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/native/native/index.node"`, which is a prebuilt binary.

**Comment by iMichka** [comment]
Ha yes, I remember this now: https://github.com/cube-js/cube/issues/6738

If upstream is not able to fix this, we will need to remove the formula ...

**Comment by cho-m** [comment]
Could try to build it https://github.com/cube-js/cube/blob/v0.33.50/.github/workflows/publish.yml#L127-L140 and replace binary.

**Comment by alebcay** [comment]
> Could try to build it [cube-js/cube@`v0.33.50`/.github/workflows/publish.yml#L127-L140](https://github.com/cube-js/cube/blob/v0.33.50/.github/workflows/publish.yml?rgh-link-date=2023-09-04T22%3A25%3A24Z#L127-L140) and replace binary.

I think I briefly tried this when I looked into it earlier. My approach was to `cd` to the offending module directory in `node_modules`, delete the existing binary, and perform whatever `yarn`/`npm`/`tsc` steps are needed to create a fresh binary.

Unfortunately, it seems that contents in `node_modules` don't have package lock files (which makes sense, all of the lock data is kept at the root package lock). So `npm`/`yarn` will complain/error about missing lockfile if using `npm ci` or `yarn install --frozen-lockfile` or similar in the offending module directory. Ignoring the lockfile is not ideal since then we are essentially performing unversioned/unchecked dependencies download at build time.

One option I am only thinking of now that I didn't try at the time is maybe to copy the root package lock into the offending module directory. This assumes that the build dependencies for the offending module are contained in the root package lock (maybe they're not) and also that `npm`/`yarn` will ignore the superset of other data in the root package that does not pertain to the of fending module.

One more option (probably less maintainable, in my opinion) is to forget trying to build the binary from the copy of the source already contained in the `node_modules` tree and just to track the version of this module, make a `resource` for it, and build it separately, only copying in the build outputs into place at the end.

**Review by MikeMcQuaid — APPROVED** [review]

**Pull request merged**
