### PR TITLE
mono 5.2.0.215, fsharp 4.1.25, msbuild 15.3

### PR DESCRIPTION
**Pull request by mfilippov**
mono 5.2.0.215 with MSBuild.

### CODE REVIEW

**Comment by mfilippov** [comment]
@ilovezfs build fixed.

**Comment by mfilippov** [comment]
@ilovezfs ping

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by mfilippov** [comment]
any news?

**Comment by ilovezfs** [comment]
See my comment here: https://github.com/Homebrew/homebrew-core/pull/17435#issuecomment-329990406

**Comment by mfilippov** [comment]
I think separate formula it is not a good solution. The official installer from mono team contains the MSBuild. Mono without MSBuild could not build some projects. xBuild marked as deprecated technology.

**Comment by mfilippov** [comment]
I additional current MSBuild find reference assemblies in mono which it installed. If you try to install MSBuild separately, you should describe for MSBuild where is the reference assemblies folder.

**Comment by ilovezfs** [comment]
Whether or not it's a separate formula, we'll need an approach to msbuild that is significantly simpler than what's in this PR. Otherwise, we'll need to go without msbuild and without any of the components that need it.

**Comment by ilovezfs** [comment]
Going to pass on this PR because the resource block involves patching that needs to be fixed upstream rather than in the formula but thanks nonetheless @mfilippov!

**Pull request closed without merging**
