### PR TITLE
ammonite-repl 0.7.4

### PR DESCRIPTION
**Pull request by emanresusername**

### CODE REVIEW

**Comment by emanresusername** [comment]
hold off on this one `0.7.4` is on the way soon

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/a923e6b80d42230046796172056068d881095880. Thank you for your contribution to Homebrew @emanresusername; we appreciate it! :smiley_cat:

**Comment by ilovezfs** [comment]
There is a bug in the brew version detection code:
```
Summary
/usr/local/Cellar/ammonite-repl/0.7: 2 files, 30.7M, built in 0 seconds
```

Until that bug is fixed this one has to have its version set explicitly in the formula:
```
    version "0.7.4"
```

**Comment by ilovezfs** [comment]
@DomT4 I assume you'll fix this since I'm on my iPhone ;)

**Comment by emanresusername** [comment]
@DomT4 lmk if i should push an addendum for that

**Comment by DomT4** [comment]
I have zero idea how this is returning a bad version 😕. Fixed in https://github.com/Homebrew/homebrew-core/commit/0f1e16f64adcc4b7fb0b0661108684429f5c541f for now. Thanks for noticing @ilovezfs.

**Comment by ilovezfs** [comment]
@DomT4 I already chased it down locally and figured out where it breaks. That's the only reason I hadn't already done this one because I wanted to fix that first in the brew repo :)

**Comment by DomT4** [comment]
It's such a simple version, it shouldn't be problematic 😅. Shall await your `brew` PR with curiosity. We can pluck this line out of the formula once the `brew` PR is merged, but might as well not break the update for now.

**Comment by ilovezfs** [comment]
Yup that's why I piped up just now despite being AFK :)

**Pull request merged**
