### PR TITLE
create-dmg 1.0.10

### PR DESCRIPTION
**Pull request by aonez**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by aonez** [comment]
This is macOS only. Will need to check how to tell that in the formula.

**Comment by aonez** [comment]
Only found [that](https://docs.brew.sh/Acceptable-Formulae):

> If upstream does not support one of these platforms, an exception can be made and the formula can be disabled for that platform.

**Comment by cho-m** [comment]
> This is macOS only. Will need to check how to tell that in the formula.

You can add `depends_on :macos`

**Comment by fastily** [comment]
^ this.  Also, here's an [example](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/molten-vk.rb#L21) if you just want to copy & paste

**Review by iMichka — APPROVED** [review]
Thanks!

**Pull request closed without merging**
