### PR TITLE
iperf 3.2

### PR DESCRIPTION
**Pull request by zmwangx**
ℹ️🎭

### CODE REVIEW

**Comment by ilovezfs** [comment]
`"--with-openssl=#{Formula["openssl"].opt_prefix}"` will probably fix it

**Comment by ilovezfs** [comment]
+ `depends_on "openssl"`

**Comment by zmwangx** [comment]
Yep.

**Comment by ilovezfs** [comment]
Cf. https://github.com/Homebrew/homebrew-core/pull/14991.

**Comment by zmwangx** [comment]
Oh that was stupid...

**Comment by zmwangx** [comment]
Anyway, iperf is deprecated per their website and doesn't build on 10.13. Probably should be trashed.

**Comment by ilovezfs** [comment]
Yeah ... not sure why it's still around.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:Formula joe$ brew formula-analytics iperf
install events in the last 30 days for iperf
=====================================================================================================
1 | iperf                                                                           | 1,437 | 100.00%
=====================================================================================================
Total                                                                               | 1,437 |    100%
=====================================================================================================
Josephs-MacBook-Pro:Formula joe$ brew formula-analytics iperf3
install events in the last 30 days for iperf3
=====================================================================================================
1 | iperf3                                                                          | 2,936 | 100.00%
=====================================================================================================
Total                                                                               | 2,936 |    100%
=====================================================================================================
Josephs-MacBook-Pro:Formula joe$
```

**Comment by zmwangx** [comment]
At least 2936 people were smarter than me in the last 30 days.

**Comment by ilovezfs** [comment]
LOL

**Pull request closed without merging**
