### PR TITLE
stellar-core 17.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
> We could try building this with GCC.

I'd rather use `depends_on macos: :catalina`

**Comment by carlocab** [comment]
It almost certainly builds with `gcc` (or `llvm` Clang), though. Do we really not want to provide a Mojave bottle where we can?

**Comment by bayandin** [comment]
I don't really have a strong opinion about it. 
My thought was It easier to drop support of Mojave now (in the light of the Monterey is coming this year), then don't forget to return to this formula after the release of Monterey and clean it up.

The formula is not so popular, but it definitely in use:
```
==> Analytics
install: 29 (30 days), 71 (90 days), 191 (365 days)
```

**Comment by carlocab** [comment]
Supporting Mojave is just a few extra lines. The Mojave bottle doesn't necessarily disappear when Monterrey comes around; that only happens when the bottles are rebuilt and we no longer have Mojave runners.

Also, at the moment, we do still support Mojave, so I think when there are simple things we can do to keep it supported, we should do that. At the very least, it will allow users still on Mojave to build this formula from source even when we no longer ship Mojave bottles (which we do try to do on a "best-effort" bases per the docs).

**Comment by carlocab** [comment]
Nope, I lied. Mojave build still failed (though it did make it past `configure`). `depends_on macos: :catalina` it is.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
