### PR TITLE
nuget 6.5.0

### PR DESCRIPTION
**Pull request by slang25**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
Thanks @slang25!

**Review by ZhongRuoyu — COMMENTED** [review]
Thanks @slang25 for your first contribution to Homebrew!

The warnings [here](https://github.com/Homebrew/homebrew-core/actions/runs/4303108274) suggest that v6.5.0 is "not yet recommended for wide-spread consumption" ([reference](https://learn.microsoft.com/en-us/nuget/api/tools-json)); upstream still marks v6.4.0 as the recommended latest: https://www.nuget.org/downloads.

So, let's wait for a while before merging this.

**Comment by slang25** [comment]
I did not know about this endpoint and the "ReleasedAndBlessed" status, TIL!

**Comment by ZhongRuoyu** [comment]
They might have forgotten to update the status because VS 2022 is already shipping NuGet 6.5.0. I filed https://github.com/NuGet/Home/issues/12507.

**Comment by p-linnane** [comment]
6.5.0 is now marked as the recommended gersion on the downloads page, and it's "ReleasedAndBlessed". Going to rebase and rerun this to get it merged.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
