### PR TITLE
lsof 4.93.2

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Change in upstream after conversation at https://github.com/Homebrew/homebrew-core/issues/39572.

### CODE REVIEW

**Comment by alebcay** [comment]
Looks like my arbitrary replacement of `9.0` from the generated Makefile only works on Mojave. Maybe High Sierra and Sierra are 8.0 and 7.0, respectively? In any case, [the issue has been reported upstream](https://github.com/lsof-org/lsof/issues/68).

**Comment by alebcay** [comment]
Resolved the `Configure` issue by manually setting `ENV["LSOF_CC"]` and `ENV["LSOF_CCV"]`. Issue upstream was basically met with "please submit a pull request"; if anyone wants to have a go, have at it, but all the `sed` and other stuff in the Configure is too much for me to figure out.

**Comment by lembacon** [comment]
Bottles are gone, rebuilding…

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
