### PR TITLE
thefuck 3.23

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Upstream are getting [murdery](https://github.com/nvbn/thefuck/issues/685) towards `python2` support, and new features require `python3`, so.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Passing on this until they actually drop python3 support completely.

**Comment by DomT4** [comment]
I mean, you could've just asked me to change this PR back to a simple version bump rather than closing it completely 😄.

**Comment by ilovezfs** [comment]
Go for it.

**Comment by DomT4** [comment]
💁‍♂️

**Comment by ilovezfs** [comment]
:tada:

**Comment by ilovezfs** [comment]
3.23 is out.

**Comment by ilovezfs** [comment]
`ENV["LC_ALL"] = "en_US.UTF-8"` fixes the test.

**Comment by ilovezfs** [comment]
It looks like we're out-of-luck with the python3 thing as it prints a big ol' nasty warning unless we were to patch the warning out, which would be spitting in the wind :(

So yeah ... python3 it is. Sorry to have you chasing your tail like a :dog:.

**Comment by ilovezfs** [comment]
I'm confused why the test is still failing. That seemed to fix it locally …

**Comment by DomT4** [comment]
> Sorry to have you chasing your tail like a 🐶 

🙈 🙈 🙈 🙈 🙈.

> That seemed to fix it locally

Aye. I didn't have any problems locally in the first place, and still don't, but my `LC_ALL` is set to `en_US.UTF-8` in shell already.

**Comment by ilovezfs** [comment]
Thousands of more python3 installations here we come … :snake: :snake: :snake: :see_no_evil:

**Pull request closed without merging**
