### PR TITLE
acme 0.97

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
license header ref (file, `code-0/trunk/contrib/toacme/src/main.c`)
```
// ToACME - converts other source codes to ACME format.
// Copyright (C) 1999-2015 Marco Baye
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
```

**Review by dawidd6 — DISMISSED** [review]

**Comment by dawidd6** [comment]
```
==> brew fetch --retry acme --build-bottle --force
==> FAILED
==> Cloning https://svn.code.sf.net/p/acme-crossass/code-0/trunk
==> Checking out 266
You must: brew install svn
==> Retrying download
==> Cloning https://svn.code.sf.net/p/acme-crossass/code-0/trunk
==> Checking out 266
You must: brew install svn
Error: Failed to download resource "acme"
Failure while executing; `svn checkout https://svn.code.sf.net/p/acme-crossass/code-0/trunk /Users/brew/Library/Caches/Homebrew/acme--svn --quiet -r 266` exited with 1. Here's the output:
You must: brew install svn
```

Only Catalina

**Comment by dawidd6** [comment]
I think this should be adjusted in brew:

https://github.com/Homebrew/brew/blob/176c85d42c209348bb42ee511fc0bc207d155c03/Library/Homebrew/extend/os/mac/dependency_collector.rb#L9

The method `subversion_dep_if_needed(tags)` could be `undef`ed only when `MacOS.version < :catalina`, I think.

**Comment by chenrui333** [comment]
interesting call out, that would save tons of work on the client side.

**Pull request closed without merging**
