### PR TITLE
sbcl 2.1.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Fatal COMPILE-FILE-ERROR:
  COMPILE-FILE-ERROR while
  compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "opt" "sbcl" "x86oid-vm">
make: *** [bin/pgloader] Error 1
```

**Comment by jinwoo** [comment]
> ```
> Fatal COMPILE-FILE-ERROR:
>   COMPILE-FILE-ERROR while
>   compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "opt" "sbcl" "x86oid-vm">
> make: *** [bin/pgloader] Error 1
> ```

I'm told the latest ironclad fixes this. https://github.com/sharplispers/ironclad/pull/37

**Comment by chenrui333** [comment]
looks like still the same error

```
;; loading system "pgloader"
Fatal COMPILE-FILE-ERROR:
  COMPILE-FILE-ERROR while
  compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "opt" "sbcl" "x86oid-vm">
make: *** [bin/pgloader] Error 1
```

**Comment by jinwoo** [comment]
There was a new Quicklisp release a couple days ago. It includes the new version of ironclad. Would it be possible that it fixes the build problem?

**Comment by miccal** [comment]
Closing as version 2.1.1 has been released.

**Comment by chenrui333** [comment]
> There was a new Quicklisp release a couple days ago. It includes the new version of ironclad. Would it be possible that it fixes the build problem?

let me try out with the latest sbcl 2.1.1

**Pull request closed without merging**
