### PR TITLE
aws-vault 6.4.0

### PR DESCRIPTION
**Pull request by Moulick**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moulick** [comment]
wait, we have the exact same thing in https://github.com/Homebrew/homebrew-cask/pull/117623,
I mean we have `aws-vault` as both cask and formula ?

**Comment by amadejpapez** [comment]
> wait, we have the exact same thing in [Homebrew/homebrew-cask#117623](https://github.com/Homebrew/homebrew-cask/pull/117623),
>I mean we have `aws-vault` as both cask and formula ?

After your comment, I was interested into seeing how many packages appear in both. Matching was done based on the file name and I assume most are actually installing different things in cask and in formula. So I do not know how useful this list may be, but as I already have it why not share it if anyone more familiar maybe spots something. :)

<details>
<summary>List</summary>

angband.rb
appium.rb
archiver.rb
atlantis.rb
aws-vault.rb
bee.rb
blitz.rb
brightness.rb
brook.rb
ckan.rb
cmake.rb
cocoapods.rb
crunch.rb
cutter.rb
dash.rb
datasette.rb
davmail.rb
docker.rb
dosbox-x.rb
dosbox.rb
dotnet.rb
doxygen.rb
emacs.rb
enigma.rb
fetch.rb
flow.rb
flume.rb
flux.rb
fontforge.rb
fs-uae.rb
gitup.rb
handbrake.rb
hey.rb
igv.rb
ipfs.rb
jasper.rb
julia.rb
jump.rb
jupyterlab.rb
kawa.rb
kite.rb
knock.rb
lab.rb
lepton.rb
lilypond.rb
lynx.rb
macvim.rb
mame.rb
marked.rb
megacmd.rb
metabase.rb
mgba.rb
mkvtoolnix.rb
mpv.rb
namebench.rb
nano.rb
neo4j.rb
nomad.rb
noti.rb
nzbget.rb
onedrive.rb
openmsx.rb
openrct2.rb
opensc.rb
openttd.rb
platypus.rb
ppsspp.rb
puzzles.rb
r.rb
rhino.rb
scummvm.rb
silicon.rb
singularity.rb
sip.rb
snappy.rb
spark.rb
squirrel.rb
stella.rb
subnetcalc.rb
svgcleaner.rb
swift.rb
swimat.rb
syncthing.rb
tag.rb
termius.rb
unison.rb
vapor.rb
volt.rb
widelands.rb
wireshark.rb
</details>

**Comment by Moulick** [comment]
@bevanjkay is this the codesign error you mentioned? I don't think so this seems to be some issue in the makefile

**Comment by SMillerDev** [comment]
>  I mean we have aws-vault as both cask and formula ?

Yes, upstream prefers the macOS build to be a cask, but for linux support we made it a formula (and recently enabled macOS too)

**Comment by branchvincent** [comment]
@Moulick this formula isn't codesigned because we remove the reference to it: https://github.com/Homebrew/homebrew-core/blob/4aa04ba885a29eb84babe1a9474d4afbee1d6473/Formula/aws-vault.rb#L21-L23

the error here is because that reference slightly changed (see the source [here](https://github.com/99designs/aws-vault/blob/3a9eafb38759ddf44c4887948b2862c7ad19e757/Makefile#L11)), so we'll just need to update it

**Comment by Moulick** [comment]
Thanks @branchvincent fixed now :)

**Review by SMillerDev — APPROVED** [review]
Thanks @Moulick  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
