### PR TITLE
handbrake 1.5.1

### PR DESCRIPTION
**Pull request by zuisong**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
>   probe: repo info...(fail) code 128
>  probe: version.txt...(fail)

**Comment by iMichka** [comment]
Looks like we need to download an official source archive instead:
```
2022-01-10T15:39:53.7831860Z ERROR: HandBrake is missing version information it needs to build properly.
2022-01-10T15:39:53.7833440Z Clone the official git repository at https://github.com/HandBrake/HandBrake.git
2022-01-10T15:39:53.7835030Z or download an official source archive from https://handbrake.fr
2022-01-10T15:39:53.7836070Z ; configure stop.
```

**Comment by cho-m** [comment]
The source tarballs from homepage link to GitHub.

Might want to try **1.5.1** release: https://github.com/HandBrake/HandBrake/releases/download/1.5.1/HandBrake-1.5.1-source.tar.bz2

[Release notes](https://github.com/HandBrake/HandBrake/releases/tag/1.5.1) mention a source tarball issue was fixed.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @zuisong!

**Pull request closed without merging**
