### PR TITLE
rust 1.67.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by chenrui333** [comment]
failed with `cargo-zigbuild` on linux build, https://github.com/Homebrew/homebrew-core/actions/runs/4016616611/jobs/6900416401

**Comment by ZhongRuoyu** [comment]
> failed with `cargo-zigbuild` on linux build, https://github.com/Homebrew/homebrew-core/actions/runs/4016616611/jobs/6900416401

Smells like OOM:

```plaintext
  [ 99%] Building stage2 object /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/zig2.o
  cd /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1 && /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/zig1 src/stage1.zig --name zig2 --zig-lib-dir /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/lib -femit-bin=/tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/zig2.o -fcompiler-rt -target native -mcpu native -lc --pkg-begin build_options /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/config.zig --pkg-end
  Killed
```

**Comment by chenrui333** [comment]
> > failed with `cargo-zigbuild` on linux build, https://github.com/Homebrew/homebrew-core/actions/runs/4016616611/jobs/6900416401
> 
> Smells like OOM:
> 
> ```
>   [ 99%] Building stage2 object /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/zig2.o
>   cd /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1 && /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/zig1 src/stage1.zig --name zig2 --zig-lib-dir /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/lib -femit-bin=/tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/zig2.o -fcompiler-rt -target native -mcpu native -lc --pkg-begin build_options /tmp/zig-20230126-105481-vy2xnk/zig-0.10.1/build/config.zig --pkg-end
>   Killed
> ```
> 
> Update: Yeah, this also happened in #121008. If this is still happening, [ CI-linux-self-hosted](https://github.com/Homebrew/homebrew-core/labels/CI-linux-self-hosted) Build on Linux self-hosted runner may be needed.

that makes sense, but I can followup separately though if just `cargo-zigbuild` failure again.

**Comment by chenrui333** [comment]
some compilation issues for dependencies of `pueue` and `sn0int`
```
brew install --build-from-source pueue
brew install --build-from-source sn0int
```

**Comment by ZhongRuoyu** [comment]
> some compilation issues for dependencies of `pueue` and `sn0int`

- `brew install --build-from-source pueue`: Related to https://github.com/Nukesor/pueue/issues/409. Its dependency `darwin-libproc` had its repo removed from GitHub. Not sure what can be done here.
- `brew install --build-from-source sn0int`: Its dependency `geo-types` failed to build, due to a change in the language. This was already fixed *upupstream*, so upstream could possibly fix this with a dependency version bump. I created https://github.com/kpcyrd/sn0int/issues/238.

**Comment by chenrui333** [comment]
All rust deps are build deps, merging it now and will followup with [this list](https://github.com/Homebrew/homebrew-core/pull/121561#issuecomment-1406874632).

**Comment by Nukesor** [comment]
> brew install --build-from-source pueue: Related to https://github.com/Nukesor/pueue/issues/409. Its dependency darwin-libproc had its repo removed from GitHub. Not sure what can be done here.

This has been fixed by creating our own fork of the fix.
We're also working actively with another Mac procfs crate to merge some fixes upstream, so we no longer depend on this abandoned library.

Should I publish a new point release to fix this? Right now this is only on `main` and I didn't think of publishing a new release, as this is only a dev-dependency.

**Comment by ZhongRuoyu** [comment]
Thanks, @Nukesor.

> Should I publish a new point release to fix this? Right now this is only on main and I didn't think of publishing a new release, as this is only a dev-dependency.

If possible, yes, please, since currently a source build of `pueue`'s stable version still results in the same error.

Cc maintainer @chenrui333 on this.

**Comment by mjpieters** [comment]
I'm on the libproc issue; we contributed to another, maintained project to cover the functionality we need and I'm about to rip out darwin-libproc. :-)

**Comment by Nukesor** [comment]
New minor release has been published :)

**Comment by ZhongRuoyu** [comment]
Thanks, @Nukesor and @mjpieters! I opened #122681.

**Pull request closed without merging**
