### PR TITLE
zimg 2.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
fix "error: use of undeclared identifier '_mm256_cvtph_ps'"
add head spec
specify cxx11 for < mavericks

### CODE REVIEW

**Comment by apjanke** [comment]
Failed on Mavericks and Yosemite only.

```
  CXX      src/zimg/depth/libf16c_la-f16c_ivb.lo
src/zimg/depth/f16c_ivb.cpp:52:14: error: use of undeclared identifier '_mm256_cvtph_ps'; did you mean '_mm256_cvtpd_ps'?
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + vec_left - 8)));
                           ^~~~~~~~~~~~~~~
                           _mm256_cvtpd_ps
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/avxintrin.h:528:1: note: '_mm256_cvtpd_ps' declared here
_mm256_cvtpd_ps(__m256d __a)
^
src/zimg/depth/f16c_ivb.cpp:52:30: error: cannot initialize a parameter of type '__m256d' with an rvalue of type '__m128i'
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + vec_left - 8)));
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/avxintrin.h:528:25: note: passing argument to parameter '__a' here
_mm256_cvtpd_ps(__m256d __a)
                        ^
src/zimg/depth/f16c_ivb.cpp:57:14: error: use of undeclared identifier '_mm256_cvtph_ps'; did you mean '_mm256_cvtpd_ps'?
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + j)));
                           ^~~~~~~~~~~~~~~
                           _mm256_cvtpd_ps
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/avxintrin.h:528:1: note: '_mm256_cvtpd_ps' declared here
_mm256_cvtpd_ps(__m256d __a)
^
src/zimg/depth/f16c_ivb.cpp:57:30: error: cannot initialize a parameter of type '__m256d' with an rvalue of type '__m128i'
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + j)));
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/avxintrin.h:528:25: note: passing argument to parameter '__a' here
_mm256_cvtpd_ps(__m256d __a)
                        ^
src/zimg/depth/f16c_ivb.cpp:62:14: error: use of undeclared identifier '_mm256_cvtph_ps'; did you mean '_mm256_cvtpd_ps'?
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + vec_right)));
                           ^~~~~~~~~~~~~~~
                           _mm256_cvtpd_ps
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/avxintrin.h:528:1: note: '_mm256_cvtpd_ps' declared here
_mm256_cvtpd_ps(__m256d __a)
^
src/zimg/depth/f16c_ivb.cpp:62:30: error: cannot initialize a parameter of type '__m256d' with an rvalue of type '__m128i'
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + vec_right)));
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/avxintrin.h:528:25: note: passing argument to parameter '__a' here
_mm256_cvtpd_ps(__m256d __a)
                        ^
src/zimg/depth/f16c_ivb.cpp:76:15: error: use of undeclared identifier '_mm256_cvtps_ph'
                __m128i x = _mm256_cvtps_ph(_mm256_load_ps(src_p + vec_left - 8), 0);
                            ^
src/zimg/depth/f16c_ivb.cpp:81:15: error: use of undeclared identifier '_mm256_cvtps_ph'
                __m128i x = _mm256_cvtps_ph(_mm256_load_ps(src_p + j), 0);
                            ^
src/zimg/depth/f16c_ivb.cpp:86:15: error: use of undeclared identifier '_mm256_cvtps_ph'
                __m128i x = _mm256_cvtps_ph(_mm256_load_ps(src_p + vec_right), 0);
                            ^
9 errors generated.
make[1]: *** [src/zimg/depth/libf16c_la-f16c_ivb.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1
```

**Comment by ilovezfs** [comment]
@apjanke yeah ... I'd hoped 2.2.1 would bring more luck, but no dice. You can see the ugliness those errors were leading me to: https://github.com/Homebrew/homebrew-core/pull/3956/files

which was enough to rehabilitate it on Yosemite, but Mavericks still died in a ball of flames.

This PR turns out to block https://github.com/Homebrew/homebrew-core/pull/4210 so the fate of two are now at stake.

**Comment by apjanke** [comment]
Well, crap.

I recently upgraded my machines to El Capitan. If I have some time this week I'll spin up a Mavericks VM and see if I can help diagnose this.

**Comment by ilovezfs** [comment]
I'm tempted to limit it to El Capitan and then decide about using gcc to prop up Yosemite and finding a Mavericks fix after that so that we can at least ship vapoursynth and zimg for 10.11, which probably covers most users (not sure what the analytics say about that). Or we could ship 10.11 and 10.10-with-gcc-crutch right away and worry about getting Yosemite gcc free and getting Mavericks to work at all after that.

**Comment by DomT4** [comment]
Might be worth reporting upstream if not done already. They've been pretty helpful on Clang issues previously, IIRC.

**Comment by ilovezfs** [comment]
@DomT4 that sucks all the fun out of the puzzle :)
but yeah I agree since 2.2.1 didn't fix it, it's it time to report. Note that for 10.9 this doesn't appear to be a clang issue at all.

**Comment by ilovezfs** [comment]
@apjanke mystery solved :) https://reviews.llvm.org/D15127

Those symbols were moved from `f16cintrin.h` to `immintrin.h`. Adding `#include <f16cintrin.h>` to the files that include immintrin.h fixes the build.

**Comment by ilovezfs** [comment]
_Look, ma! No patches! No string replacements!_

**Comment by ilovezfs** [comment]
Reported upstream: https://github.com/sekrit-twc/zimg/issues/52.

**Comment by ilovezfs** [comment]
:ship:'d

**Pull request closed without merging**
