### PR TITLE
readline 8.1.2

### PR DESCRIPTION
**Pull request by miccal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
`asuka` has been fixed here: #92656

**Comment by iMichka** [comment]
Here is a fix for `ivtools`: #93005

**Comment by miccal** [comment]
Thanks @iMichka for your help here.

**Comment by iMichka** [comment]
```
2022-01-07T20:59:50.6820920Z [34m==>[0m [1mPouring texlive--58837.arm64_big_sur.bottle.tar.gz[0m
2022-01-07T20:59:50.6821540Z The formula built, but is not symlinked into /opt/homebrew
2022-01-07T20:59:50.6822020Z Could not symlink bin/cfftot1
2022-01-07T20:59:50.6822420Z Target /opt/homebrew/bin/cfftot1
2022-01-07T20:59:50.6823120Z is a symlink belonging to lcdf-typetools. You can unlink it:
2022-01-07T20:59:50.6823830Z   brew unlink lcdf-typetools
2022-01-07T20:59:50.6824110Z 
2022-01-07T20:59:50.6824470Z To force the link and overwrite all conflicting files:
2022-01-07T20:59:50.6825150Z   brew link --overwrite texlive
2022-01-07T20:59:50.6825420Z 
2022-01-07T20:59:50.6825730Z To list all files that would be deleted:
2022-01-07T20:59:50.6826370Z   brew link --overwrite --dry-run texlive
```

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
