### PR TITLE
micronaut 2.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/micronaut/2.1.0/bin/mn create-app hello-world
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
| Error Unsupported JDK version: 14. Supported values are [8, 9, 10, 11, 12, 13, 14, 15]
Error: micronaut: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/micronaut/2.1.0/bin/mn create-app hello-world
```

**Comment by chenrui333** [comment]
works with jdk8 and 11, but not 14, filed an upstream issue for this.

**Comment by chenrui333** [comment]
will wait for the upstream's comments before moving forward.

**Comment by bayandin** [comment]
> works with jdk8 and 11, but not 14, filed an upstream issue for this.

Let's switch it to `openjdk@11` for now (it will be switched back to `openjdk` in https://github.com/Homebrew/homebrew-core/pull/61226)

**Review by bayandin — APPROVED** [review]

**Comment by chenrui333** [comment]
Sounds good, thanks @bayandin !

**Pull request closed without merging**
