### PR TITLE
vtk@8.2: add linux dependencies

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Blocked until `pyqt@5` is fixed & bottled. It currently fails during sip-install.

**Comment by danielnachun** [comment]
I was able to get `pyqt@5` to build locally, and this should fix it now: https://github.com/Homebrew/homebrew-core/pull/84181.  Note that we also will need to fix `vtk`, as that is a dependency for `opencv`, which still needs to be bottled as well.

**Comment by danielnachun** [comment]
This will probably need to be built with `gcc` based on the test failure I got with `vtk`.

**Comment by danielnachun** [comment]
This fails because it doesn't like the `inreplace` we try to do after building:
```
Utils::Inreplace::Error: inreplace failed
/home/linuxbrew/.linuxbrew/Cellar/vtk@8.2/8.2.0_7/lib/cmake/vtk-8.2/VTKTargets-release.cmake:
expected replacement of #<Pathname:/home/linuxbrew/.linuxbrew/Cellar/vtk@8.2/8.2.0_7> with #<Pathname:/home/linuxbrew/.linuxbrew/opt/vtk@8.2>
```
Once we've fixed those `inreplace` issues, if we need to build with `gcc`, we will probably have to apply the same upstream commits here that I had to use for `vtk` to get it to build with GCC-11.

**Comment by danielnachun** [comment]
I used the test for VTK 9 and confirmed that it needs to be built with GCC 11.  I had to apply a few fixes for this to work with GCC 11, but they were pretty minor.  Now I've just got to figure out what's up with the `inreplace` lines after the build finishes.

**Comment by danielnachun** [comment]
I fixed the `inreplace` issue, and also took the test from VTK 9, which failed when using GCC 5 and passes with GCC 11.  I was also able to confirm that the only dependent of `vtk@8.2`, `gdcm`, needs to be built with GCC 11.  It will only need a small upstream commit applied to work with GCC 11.

On a related note, `gdcm` has made VTK 9 support a goal for the 3.1 milestone (currently it is at 3.0.9).  Once that is released, I think we should disable `vtk@8.2` at the same time, as its complex dependency tree requires a lot of patching already and will make it difficult to maintain.

**Comment by danielnachun** [comment]
Whoops I forgot to make `cmake` a test dependency 🤦.  Now I think it should work.

**Comment by iMichka** [comment]
Thanks for the fixes, looks good. I am going to merge this. We will probably drop this versioned formula anytime soon anyway, given the above. It has still a bunch of downloads so we can wait a little bit:

```
==> Analytics
install: 501 (30 days), 2,103 (90 days), 12,056 (365 days)
install-on-request: 324 (30 days), 920 (90 days), 3,763 (365 days)
build-error: 0 (30 days)
```

**Pull request closed without merging**
