### PR TITLE
terraform: revision for non-cgo root cert discovery fix

### LINKED ISSUE #8576: Terraform TLS Handshake Timeout errors
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

Summary: Terraform 0.8.2 installed via homebrew gets TLS handshake timeout errors, terraform 0.8.2 downloaded from terraform.io works correctly. Several people on our team saw the same issue with the brew installed version only.

```
Error refreshing state: 8 error(s) occurred:
* cloudflare_record.primary: Error finding zone "*****.com": ListZones command failed: error from makeRequest: HTTP request failed: Get https://api.cloudflare.com/client/v4/zones?name=******.com: net/http: TLS handshake timeout
...
```

Perhaps it has something to do with the version of Go used to build it or some other dependency?

* https://github.com/hashicorp/terraform/issues/10718#issuecomment-266946488
* https://github.com/hashicorp/terraform/issues/11007

### Brew Config

```
$ brew config
HOMEBREW_VERSION: 1.1.6-23-g1a394aa
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1a394aa7e5b7bf4f6281826248345be0308b30a4
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 74063d85f4da579d02e34d8770756273707aec0b
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/var/pyenv/shims/python => /usr/local/var/pyenv/versions/2.7.11/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

### Brew Doctor

Note: brew doctor is reporting my xcode is out of date, however I don't see any upgrades available. This might be because I'm still on El Cap instead of Sierra or something?

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/local/var/pyenv/shims/python-config
  /usr/local/var/pyenv/shims/python2-config
  /usr/local/var/pyenv/shims/python2.7-config
  /usr/local/var/pyenv/shims/python3-config
  /usr/local/var/pyenv/shims/python3.5-config
  /usr/local/var/pyenv/shims/python3.5m-config

Warning: Your Xcode (8.1) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.
```

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #8576.

CC @mwarkentin @mitchellh

### CODE REVIEW

**Comment by mwarkentin** [comment]
@ilovezfs Thanks! It looks like this just rebuilds Terraform with the following updates to Go that should fix the issue?

* https://github.com/Homebrew/homebrew-core/commit/489e554fd47d7973f0cf22b265fccdf5511cf44b
* https://github.com/Homebrew/homebrew-core/commit/de1fb87c42b7b6379e5d79fba370b3cf95c874bb

**Review by mwarkentin — APPROVED** [review]

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by mwarkentin** [comment]
@ilovezfs Awesome, thanks! Does this mean this is available now if I install TF from homebrew? Or does it take some time?

**Comment by ilovezfs** [comment]
@mwarkentin yes, it's available as of 
https://github.com/Homebrew/homebrew-core/commit/f81498c0619be8092e76e4d274d30eeed524a233
https://github.com/Homebrew/homebrew-core/commit/5ac038c64ea7d237d4f20b88c701f71ff9210f49

**Pull request closed without merging**
