### PR TITLE
ghc 8.10.2

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fishtreesugar** [comment]
#59336

**Comment by chenrui333** [comment]
`#59336` is merged

**Comment by fishtreesugar** [comment]
#59709

**Comment by bubba** [comment]
@fishtreesugar what was this getting blocked on last? just lots of dependent formulae failures?

**Comment by fishtreesugar** [comment]
@bubba Yeah, I lost the patient of figuring out failed checkings.

**Pull request closed without merging**
