### PR TITLE
translate-shell: backport Google API fix

### PR DESCRIPTION
**Pull request by dunn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
No revision?

**Comment by zmwangx** [comment]
And could you please remind me why setting `TERM` is necessary? Even when I unset `TERM`, I only get a warning `tput: No value for $TERM and no -T specified` on stderr, which doesn't affect the exit code.

**Comment by dunn** [comment]
> No revision?

Woops, good catch.

> And could you please remind me why setting TERM is necessary?

It's just to silence that warning.

**Comment by zmwangx** [comment]
> It's just to silence that warning.

It might get outdated though, if upstream ever decides to silence the warning. Then it's just one stray line that was unnecessary to begin with.

**Comment by dunn** [comment]
OK. I don't have strong feelings either way so I'll remove it.

**Pull request closed without merging**
