### PR TITLE
ansible: add missing resources

### LINKED ISSUE #4977: ansible: formula broken (missing resources)
In #4471 the resources were [sorted alphabetically](https://github.com/Homebrew/homebrew-core/commit/f2b7124374a1d2d8dd60844a07514f2752e50d3c), however a few of the resources were lost in the sort (I compared the resources before and after the commit):

* pywinrm
* xmltodict
* zabbix-api

### PR DESCRIPTION
**Pull request by walro**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Some resources were lost when the resources were alphabetically ordered in #4471. This PR adds those missing resources back to the formula.

Closes #4977.

### CODE REVIEW

**Comment by tdsmith** [comment]
Do you have a use case for each of these? Please add them to the comment at the top of the resource section so that they are not dropped again.

**Comment by walro** [comment]
> Do you have a use case for each of these? Please add them to the comment at the top of the resource section so that they are not dropped again.

I use Ansible to manage Windows machines, so I need `pywinrm` and `xmltodict`: https://github.com/ansible/ansible/blob/4ed88512e45112f9670560ac3f01707a40a7f5c5/lib/ansible/plugins/connection/winrm.py#L45-L55. `pywinrm` is already mentioned in the top of the file, I can add `xmltodict` to the list.

I do not use `zabbix-api`, just happened to notice it was also dropped at the same time as `pywinrm` and `xmltodict` so I figured I'd add it back in. I can drop it if you'd like, but it is needed if someone wants to just the [zabbix modules](http://docs.ansible.com/ansible/zabbix_host_module.html#requirements-on-host-that-executes-module).

**Comment by tdsmith** [comment]
That all sounds good, thanks.

(though what the heck is a zabbix)

**Comment by tdsmith** [comment]
Thanks!

**Pull request closed without merging**
