### PR TITLE
tcl-tk: use installed tcl-tk headers

### PR DESCRIPTION
**Pull request by tcely**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by tcely** [comment]
@carlocab Did I see that all the checks passed across the three attempts?

**Comment by carlocab** [comment]
> @carlocab Did I see that all the checks passed across the three attempts?

Not quite. There are consistently failing attempts for the `(deps)` jobs.

**Comment by tcely** [comment]
> Not quite. There are consistently failing attempts for the `(deps)` -- dependents -- jobs.

I see `bazarr` is having problems retrieving a page from the GitHub API. I have no idea how that could be related to these changes. (As an aside, I have seen that action fail regularly on another project using GH Actions.)

**Review by carlocab — APPROVED** [review]
Yes, probably not related. Thanks!

**Pull request merged**
