### PR TITLE
openapi-generator 3.0.0 (new formula)

### PR DESCRIPTION
**Pull request by wing328**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by wing328** [comment]
>   * GitHub repository too new (<30 days old)

OpenAPI Generator is a fork of Swagger Codegen as explained in https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md and Swagger Codegen (https://github.com/swagger-api/swagger-codegen) was created a few years back.

**Comment by wing328** [comment]
This formula is based on https://github.com/Homebrew/homebrew-core/blob/master/Formula/swagger-codegen.rb

**Comment by wing328** [comment]
@ilovezfs I wonder if you can review and give an exception for this case as OpenAPI Generator is a fork of Swagger Codegen as explained in https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md and Swagger Codegen (https://github.com/swagger-api/swagger-codegen) was created a few years back. For more information on the fork, please refer to https://github.com/OpenAPITools/openapi-generator/blob/master/docs/migration-from-swagger-codegen.md

Please let me know if you've any question.

**Comment by jraqula** [comment]
@wing328 in the meantime, do you maintain a tap elsewhere that this formula can be pulled from?

**Comment by wing328** [comment]
@jraqula sorry we don't. This formula should be ready for merge in a few days.
```
created_at: "2018-05-12T09:57:56Z",
```

**Comment by philsturgeon** [comment]
source

**Comment by MartinDelille** [comment]
1) As you can see here, `openapi-generator` is much more active than `swagger-codegen`:

- https://github.com/OpenAPITools/openapi-generator/pulse
- https://github.com/swagger-api/swagger-codegen/pulse

2) `openapi-generator` handle OpenAPI specification v3 when `swagger-codegen` support only v2.

**Comment by wing328** [comment]
Closing this one as I've opened a new one for OpenAPI Generator 3.0.1 instead: https://github.com/Homebrew/homebrew-core/pull/28921

**Pull request closed without merging**
