### PR TITLE
pypy: update sha256 for the re-released tarball

### LINKED ISSUE #873: pypy 5.1.1 is 5.1.0
pypy 5.1.1 was installed:
```
brew info pypy
pypy: stable 5.1.1 (bottled)
Highly performant implementation of Python 2 in Python
http://pypy.org/
/usr/local/Cellar/pypy/5.1.1 (2,453 files, 104.7M) *
  Poured from bottle
```

But it reports as 5.1.0:
```
/usr/local/Cellar/pypy/5.1.1/bin/pypy --version
Python 2.7.10 (3260adbeba4a8b6659d1cc0d0b41f266769b74da, May 03 2016, 20:38:25)
[PyPy 5.1.0 with GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)]
```

### PR DESCRIPTION
**Pull request by rakkesh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Closes #873.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Build timed out but fetch succeeded so can pull this.

**Comment by DomT4** [comment]
I presume it's not worth bumping the `revision` given the only breakage is the version number, IIRC? @tdsmith

**Comment by mikemcquaid** [comment]
> I presume it's not worth bumping the revision given the only breakage is the version number, IIRC? @tdsmith

@DomT4 Yeh, I think so 👍

**Comment by rakkesh** [comment]
@DomT4 as the build for this PR timed out, I guess no new bottles were generated.😅

**Comment by Marqin** [comment]
@DomT4 I see some missing .h files in old tarball, so it's not minor...

**Pull request merged**
