### PR TITLE
go@1.12 1.12.12

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by AlekSi — CHANGES_REQUESTED** [review]
Please update to Go 1.12.12.

**Comment by chenrui333** [comment]
@AlekSi thanks for the feedback, I was trying to update it yesterday, got 404 error. Looks like it is up now. Just updated! :)

**Review by AlekSi — APPROVED** [review]

**Comment by chenrui333** [comment]
audit failure as before
```
13:37:54 ==> brew audit go@1.12 --online
13:38:52 ==> FAILED
13:38:52 ==> Installing 'bundler' gem
13:38:52 Successfully installed bundler-2.0.2
13:38:52 1 gem installed
13:38:52 Error: 1 problem in 1 formula detected
13:38:52 go@1.12:
13:38:52   * C: 25: col 5: https://storage.googleapis.com/golang/go1.7.darwin-amd64.tar.gz looks like a binary package, not a source archive. Homebrew/homebrew-core is source-only.
```

**Comment by chenrui333** [comment]
Same audit failure as #44873

**Comment by chenrui333** [comment]
Merging the PR now.

**Pull request closed without merging**
