### PR TITLE
go 1.14.4

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Some fails:
```
brew install --build-from-source baidupcs-go
brew install --build-from-source charm
brew install --build-from-source dashing
brew install --build-from-source docker-swarm
brew install --build-from-source dvm
brew install --build-from-source gor
brew install --build-from-source perkeep
brew install --build-from-source source-to-image
brew install --build-from-source sync_gateway
brew install --build-from-source wellington
brew test --verbose aws-es-proxy
brew test --verbose cql
brew test --verbose dashing
brew test --verbose devd
brew test --verbose fn
brew test --verbose jabba
brew test --verbose mailhog
```

**Comment by dawidd6** [comment]
Looks like the repository of `baidupcs-go` vanished: https://github.com/iikira/BaiduPCS-Go.git

It doesn't seem to be a dependency of anything though. Maybe we should remove it @Homebrew/core ?

**Comment by chenrui333** [comment]
> Looks like the repository of `baidupcs-go` vanished: https://github.com/iikira/BaiduPCS-Go.git
> 
> It doesn't seem to be a dependency of anything though. Maybe we should remove it @Homebrew/core ?

yeah, we should remove it, it is not rebuildable now.

**Comment by dawidd6** [comment]
@bayadin could you please rebase on top of latest master?

**Comment by bayandin** [comment]
As the last build failed on Catalina ([No space left on device](https://github.com/Homebrew/homebrew-core/pull/55639/checks?check_run_id=738764235#step:6:3987)) and we need to rerun it anyway, I've separated fixes for failed tests (which is unrelated to the current go upgrade) to a separate PR:

https://github.com/Homebrew/homebrew-core/pull/55639

**Comment by roopakv** [comment]
@Bo98 is there anything we can do to help push this along?

**Comment by alebcay** [comment]
Current failed steps:
```
brew test --verbose annie
brew install --build-from-source charm
brew test --verbose darksky-weather 
brew install --build-from-source dashing
brew test --verbose dashing
brew install --build-from-source dvm
brew test --verbose faas-cli
brew install --build-from-source gor
brew test --verbose jabba
brew test --verbose jabba
brew install --build-from-source perkeep
brew install --build-from-source source-to-image
brew install --build-from-source sync_gateway
brew install --build-from-source wellington
```

Ideally, these would all be resolved before merging. Some of the failures are coupled (e.g. `dashing` - test will fail since build failed).

**Comment by roopakv** [comment]
@alebcay https://github.com/Homebrew/homebrew-core/issues/52184

if you notice there I have opened PRs for perkeep and wellington. If the repos are sort of in maintenance mode could we not block merging at least for those?

**Comment by Bo98** [comment]
Yeah, most of the rest are pre-existing and this pull request shouldn’t be blocked on them. We’ll probably deprecate them at some point.

**Comment by roopakv** [comment]
@Bo98 if you have a list we canon skip, I am happy to start working on trying to fix them

**Comment by ryboe** [comment]
They finally cut a new release of [`charmstore-client`](https://github.com/juju/charmstore-client/releases/tag/2.2.0), so if we update `charm` it should build with Go 1.14.

**Comment by roopakv** [comment]
@Bo98 I feel like with every go release we come to packages that are broken and don't keep up. 

What would a longer-term approach be here? use an internal version for homebrew downloads and builds and keep the external go keep moving along? 

currently, charmstore has cut a release but quite a few other packages still have  issues.

**Comment by MikeMcQuaid** [comment]
> @Bo98 I feel like with every go release we come to packages that are broken and don't keep up.
> 
> What would a longer-term approach be here? use an internal version for homebrew downloads and builds and keep the external go keep moving along?

This is "rolling release package management" in a nutshell. It's not really avoidable.

**Comment by SMillerDev** [comment]
The best way forward that wouldn't just help Homebrew is to help other projects improve their CI and code. That way we can avoid running into these issues altogether.

**Comment by roopakv** [comment]
hmmm thanks for the info @MikeMcQuaid & @SMillerDev :)

I don't really understand too much of the internals. Very naively I was sort of hoping we could do something like use `go@1.14.3` to build older breaking packages while moving `go` latest to be 1.14.4

But I also understand how that might become a nightmare with a lot of packages being left behind.

**Comment by atakanyenel** [comment]
I'm also following this PR for some time and I think one of the improvements could be to cache correctly building packages. That way , if a package fails , we don't have to wait for 10 hours in the next run. I'm also aware that implementing this with Github actions is **not trivial**.

**Comment by Bo98** [comment]
I'm sorry for not being around this week and following up here - I should have dealt with this pull request last week.

You are right that pre-existing failures are _not_ a blocker for merging this.

I've gone through every single formula failing here and confirmed they are either already known as broken or not as a result of 1.14.4.

I will spend some time this weekend documenting these known broken formulae (or fixing the ones that can be fixed) so that it is more clearly known in the future.

**Comment by MikeMcQuaid** [comment]
> I will spend some time this weekend documenting these known broken formulae (or fixing the ones that can be fixed) so that it is more clearly known in the future.

Thanks @bo98! Dumped the basics into https://github.com/Homebrew/homebrew-core/issues/56539

**Pull request closed without merging**
