### PR TITLE
krb5 1.19.2

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Linux failures:
```
Error: 23 failed steps!
brew test --retry --verbose gradle
brew test --retry --verbose groovy
brew test --retry --verbose groovysdk
brew test --retry --verbose hadoop
brew test --retry --verbose htmlcleaner
brew test --retry --verbose javacc
brew test --retry --verbose jdnssec-tools
brew test --retry --verbose jmeter
brew test --retry --verbose joshua
brew test --retry --verbose jruby
brew test --retry --verbose kafka
brew test --retry --verbose kaitai-struct-compiler
brew test --retry --verbose leiningen
brew test --retry --verbose liquigraph
brew test --retry --verbose maven
brew test --retry --verbose micronaut
brew test --retry --verbose openjdk
brew test --retry --verbose openjdk@11
brew test --retry --verbose orientdb
brew test --retry --verbose pdftk-java
brew test --retry --verbose pig
brew test --retry --verbose smali
brew test --retry --verbose swagger-codegen
```

A number (all?) of errors look like
```
Error: LinkageError occurred while loading main class org.gradle.launcher.GradleMain
	java.lang.UnsatisfiedLinkError: /home/linuxbrew/.linuxbrew/Cellar/openjdk/16.0.1/libexec/lib/libnio.so: /home/linuxbrew/.linuxbrew/Cellar/openjdk/16.0.1/libexec/lib/libnio.so: undefined symbol: reuseport_available
```

Do we just need rev bumps for `openjdk` and `openjdk@11` here? @Homebrew/linux

**Comment by iMichka** [comment]
I can not reproduce this locally. Not sure this is related to the krb5 version bump. `openjdk` does not link against krb5 (but openjdk is special on Linux, it loads libraries dynamically at runtime). Maybe a mixup when both `openjdk` and `openjdk@11` are installed at the same time?

**Comment by iMichka** [comment]
I see that `openjdk` and `openjdk@11` both use the same cache: `Picked up _JAVA_OPTIONS: -Duser.home=/home/linuxbrew/.cache/Homebrew/java_cache`

Maybe that's not a good idea?

**Comment by carlocab** [comment]
Maybe. Why is it causing issues on Linux but not macOS? Is it just that two `openjdk` versions are simultaneously installed here only on Linux?

**Comment by iMichka** [comment]
Yes, on Linux both are installed/tested at the same time. Not on macOS.

The cache folder is defined here: https://github.com/Homebrew/brew/blob/0e6dc7badb43d2d7b2844e11ba66696740e38b8a/Library/Homebrew/formula.rb#L2385

I think we should have one cache folder for each openjdk version. But I am unsure it will solve the issue, I might just be that both java's are in the PATH, and one is taking precedence over the other. Or any other issue. I have really no clue right now. Maybe some maintainers with Java expertise might now.

**Comment by carlocab** [comment]
Actually, I think both get installed on an `openjdk` PR on macOS -- `gradle` depends on `openjdk`, but a few formulae that depend on `gradle` at build-time depend on `openjdk@{8,11}` at runtime.

So that makes me wonder why we don't see this on macOS too...

**Comment by cho-m** [comment]
This issue is seen in #81724 too.

It may be some particular order of dependents that are tested, which leave behind various installed dependencies and/or cache files and like.

Probably need to try to reproduce with a smaller example.

**Review by carlocab — APPROVED** [review]
CI failures are almost certainly not due to the version bump.

**Pull request closed without merging**
