### PR TITLE
glib 2.58.1

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by fxcoudert** [comment]
`dartsim` is fixed by https://github.com/Homebrew/homebrew-core/commit/1313226bd5424a3aed8b30f43e74cf5135ae0a0b

**Comment by fxcoudert** [comment]
For the other two, it's possible in the mass bottling for Mojave we pushed bottles whose test failed… there were so many to audit

**Comment by lembacon** [comment]
`mpv` is known to crash on Mojave at this moment. We're still on 0.28.2 while the latest is 0.29.0 which we cannot upgrade to. We're still waiting for them to release 0.29.1 with mpv-player/mpv#6004 merged. See #30369.

For the crash on Mojave, we need to apply mpv-player/mpv#5953, but that patch does not apply to 0.28.2 though.

**Comment by lembacon** [comment]
> For the other two, it's possible in the mass bottling for Mojave we pushed bottles whose test failed… there were so many to audit

Then we could end up fixing a lot of tests, Clang from Xcode 10 seems not picking up the library path from `/usr/local/lib` by default. 🙃 
https://github.com/Homebrew/homebrew-core/pull/32384#issuecomment-423910370

**Pull request closed without merging**
