### PR TITLE
arduino-cli 0.20.0

### PR DESCRIPTION
**Pull request by ArduinoBot**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by umbynos** [comment]
The test is failing because we removed the alpha suffix in https://github.com/arduino/arduino-cli/pull/1553

**Comment by umbynos** [comment]
```patch
--- <old>
+++ <new>
@@ -50,7 +50,7 @@
     assert File.directory?("#{testpath}/test_sketch")
 
     version_output = shell_output("#{bin}/arduino-cli version 2>&1")
-    assert_match("arduino-cli alpha Version: #{version}", version_output)
+    assert_match("arduino-cli  Version: #{version}", version_output)
     assert_match("Commit:", version_output)
     assert_match(/[a-f0-9]{8}/, version_output)
     assert_match("Date: ", version_output)
```

**Comment by SMillerDev** [comment]
Does it build with Go 17 now?

**Comment by umbynos** [comment]
no, not yet

**Comment by SMillerDev** [comment]
That doesn't mean it doesn't work though. It just means upstream uses Go 1.16.

**Comment by umbynos** [comment]
Sorry @SMillerDev I misread your question, I'm trying now and yes, it does build with go 1.17.3.
We were thinking of bumping the go version we use to build upstream **in the next release**. In order to have consistency, would it be a problem to leave the version unchanged for this release?

**Comment by SMillerDev** [comment]
If something works with the latest version we want to have the latest version in Homebrew, consistency with upstream in dependency versions is really not a concern for us

**Comment by umbynos** [comment]
@SMillerDev We just finished running our tests with the binary built with go 1.17 and everything went fine, so it's ok to bump and release with go 1.17

**Comment by umbynos** [comment]
```patch
--- <old>
+++ <new>
@@ -22,8 +22,8 @@
     sha256 cellar: :any_skip_relocation, x86_64_linux:   "9467a330e3df2f50d077c19af97e6a9cfa2e9a4546494f281c306a93450ca672"
   end
 
-  # Switch to Go 1.17 at version bump
-  depends_on "go@1.16" => :build
+
+  depends_on "go@1.17" => :build
 
   def install
     ldflags = %W[
```
@carlocab @SMillerDev This one should do

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
