### PR TITLE
swift-format 0.50400.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Probable needs Xcode 12.5. We should probably wait until our Intel Big Sur nodes get upgraded to Big Sur 11.3. The ARM runners are already on 11.3, so this worked there.

**Comment by carlocab** [comment]
@Bo98 can we use brewed `swift` to build this for Catalina?

**Comment by Bo98** [comment]
Possibly, yes. I do plan to have a `SwiftRequirement` or similar so that we can do `depends_on swift: "5.4"`.

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
> Possibly, yes. I do plan to have a `SwiftRequirement` or similar so that we can do `depends_on swift: "5.4"` and it'll work on either macOS or Linux, so that could cover Catalina handling.

Agree, that would bring switch tools to more platforms.

**Comment by rgoldberg** [comment]
Is there anything preventing this from being merged?

**Comment by Bo98** [comment]
Our Intel CI isn't running Xcode 12.5 yet, and thus can't built this, but it will be by the end of the week.

**Comment by carlocab** [comment]
Yes. The fact that it only built on ARM. It should also build on Intel Big Sur, but we haven't upgraded the Big Sur node to 11.3 yet.

**Review by carlocab — APPROVED** [review]
Let's just bottle this for Catalina later when we have Swift 5.4

**Pull request closed without merging**
