### PR TITLE
mavsdk 1.4.15

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by p-linnane — COMMENTED** [review]
I think the comment about using `homebrew-pypi-poet` isn't necessary anymore. Probably better to use `pipgrip`.

Using `pipgrip` shows the `future` resource isn't necessary any longer, and the other 2 are up to date.

**Comment by chenrui333** [comment]
> I think the comment about using `homebrew-pypi-poet` isn't necessary anymore. Probably better to use `pipgrip`.
> 
> Using `pipgrip` shows the `future` resource isn't necessary any longer, and the other 2 are up to date.

You are absolutely right :) 

- relates to https://github.com/mavlink/MAVSDK/pull/1906

**Comment by chenrui333** [comment]
I think their dockerfile needs some love :)

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
looks like linux build, it does need it
```
  HEAD is now at 3b52eac0 add COMPONENT_METADATA, deprecate COMPONENT_INFORMATION (#1823)
  Submodule 'pymavlink' (https://github.com/ardupilot/pymavlink.git) registered for path 'pymavlink'
  Cloning into '/tmp/mavsdk-20230601-17774-1ovuhtn/build/default/third_party/mavlink/mavlink/src/mavlink/pymavlink'...
  Submodule path 'pymavlink': checked out 'df6e4d7c37edda3f687bb31db1b3e12a67eab831'
  [ 37%] Performing update step for 'mavlink'
  [ 50%] No patch step for 'mavlink'
  [ 62%] Performing configure step for 'mavlink'
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/tmp/mavsdk-20230601-17774-1ovuhtn/build/default/third_party/mavlink/mavlink/src/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
      from pymavlink.generator import mavgen
    File "/tmp/mavsdk-20230601-17774-1ovuhtn/build/default/third_party/mavlink/mavlink/src/mavlink/pymavlink/generator/mavgen.py", line 26, in <module>
      from future import standard_library
  ModuleNotFoundError: No module named 'future'
```

**Comment by carlocab** [comment]
Yea, you can't use `pipgrip` because PyPI only has a wheel, but we build from the included submodule which is basically an sdist.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
