### PR TITLE
cassandra-reaper 2.0.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
The 2.0.x branch does not contain the fix I submitted. Feel free to apply https://github.com/thelastpickle/cassandra-reaper/commit/f94dbf6f3ba702b8c173837a9a96c2a2ab45ea13.patch?full_index=1 though now that is has been merged.

**Comment by chenrui333** [comment]
i tried to apply this diff in my local, but it seems not quite working:

```
__END__
diff --git a/bin/cassandra-reaper b/bin/cassandra-reaper
index 6d8c74281ab8edf94cabf344e89dfce350375bee..ae4c33b1aae859fbf15d0067921a14b1b685c0a5 100755
--- a/bin/cassandra-reaper
+++ b/bin/cassandra-reaper
@@ -23,7 +23,7 @@ fi

 if [ -z "$CLASS_PATH" ]; then
   echo "Looking for reaper in /usr/local/share/"
-  CLASS_PATH="$(find /usr/local/share -maxdepth 4  -regex '.*/cassandra-reaper-.*[0-9rT]\.jar'):$(find /usr/share -regex '.*/cassandra-reaper-.*[0-9rT]\.jar')"
+  CLASS_PATH="$(find -L /usr/local/share -maxdepth 4 -regex '.*/cassandra-reaper-.*[0-9rT]\.jar'):$(find -L /usr/share -maxdepth 4 -regex '.*/cassandra-reaper-.*[0-9rT]\.jar')"
 fi

 if [ $# -eq 0 ]; then
```

**Comment by Bo98** [comment]
Can you elaborate on "not quite working"? Same error as before?

**Comment by chenrui333** [comment]
let me rerun really quick.

**Comment by chenrui333** [comment]
```
$ brew test cassandra-reaper
Testing cassandra-reaper
Looking for reaper in /usr/local/share/
Picked up _JAVA_OPTIONS: -Duser.home=/Users/ruichen/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp/cassandra-reaper-test-20200407-19416-16gleox
13:53:15,884 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
13:53:15,884 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
13:53:15,885 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
13:53:15,888 |-INFO in ch.qos.logback.classic.BasicConfigurator@312b34e3 - Setting up default configuration.
13:53:17,653 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@26844abb - Propagating INFO level on Logger[ROOT] onto the JUL framework
13:53:17,654 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@26844abb - Propagating WARN level on Logger[io.dropwizard] onto the JUL framework
13:53:17,655 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@26844abb - Propagating WARN level on Logger[org.eclipse.jetty] onto the JUL framework
13:53:17,658 |-INFO in ch.qos.logback.classic.AsyncAppender[async-console-appender] - Attaching appender named [console-appender] to AsyncAppender.
13:53:17,659 |-INFO in ch.qos.logback.classic.AsyncAppender[async-console-appender] - Setting discardingThreshold to 51
13:53:17,661 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Setting bufferSize to [8 KB]
13:53:17,666 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@445010547 - Will use gz compression
13:53:17,667 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@445010547 - Will use the pattern /var/log/cassandra-reaper/reaper-%d.log for the active file
13:53:17,671 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/cassandra-reaper/reaper-%d.log.gz'.
13:53:17,671 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
13:53:17,674 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Apr 07 13:53:17 EDT 2020
13:53:17,730 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Active log file name: /var/log/cassandra-reaper/reaper.log
13:53:17,730 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - File property is set to [/var/log/cassandra-reaper/reaper.log]
13:53:17,735 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Failed to create parent directories for [/var/log/cassandra-reaper/reaper.log]
13:53:17,736 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - openFile(/var/log/cassandra-reaper/reaper.log,true) call failed. java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
	at java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at io.dropwizard.logging.AbstractOutputStreamAppenderFactory.build(AbstractOutputStreamAppenderFactory.java:30)
	at 	at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:143)
	at 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:83)
	at 	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at 	at io.dropwizard.Application.run(Application.java:93)
	at 	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:110)
13:53:17,736 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Attaching appender named [file-appender] to AsyncAppender.
13:53:17,736 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Setting discardingThreshold to 51

WARN   [2020-04-07 13:53:19,450] [main] i.c.ReaperApplication - Reaper is ready to get things done!
==> curl -Im3 -o- http://localhost:8080/webui/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Error: cassandra-reaper: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </200 OK.*/m> was expected to be =~
<"HTTP/1.1 302 Found\r\n" +
"Date: Tue, 07 Apr 2020 17:53:21 GMT\r\n" +
"Set-Cookie: JSESSIONID=node0n897i5yllfzh1svmb6pjuoti80.node0;Path=/\r\n" +
"Expires: Thu, 01 Jan 1970 00:00:00 GMT\r\n" +
"Location: http://localhost:8080/webui/login.html;jsessionid=node0n897i5yllfzh1svmb6pjuoti80.node0\r\n" +
"Content-Length: 0\r\n" +
"\r\n">.
```

**Comment by Bo98** [comment]
Ok, so we got further which is good. I'll have a look and see if I can fix that error.

**Comment by chenrui333** [comment]
Sounds good!

**Comment by Bo98** [comment]
Before the `etc.install`, try:

```rb
inreplace Dir["resource/*.yaml"], ": /var/", ": #{var}/" 
```

**Comment by chenrui333** [comment]
Just did, failure looks like this

```
18:15:21,295 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - File property is set to [/var/log/cassandra-reaper/reaper.log]
18:15:21,298 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Failed to create parent directories for [/var/log/cassandra-reaper/reaper.log]
18:15:21,363 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - openFile(/var/log/cassandra-reaper/reaper.log,true) call failed. java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
	at java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at io.dropwizard.logging.AbstractOutputStreamAppenderFactory.build(AbstractOutputStreamAppenderFactory.java:30)
	at 	at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:143)
	at 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:83)
	at 	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at 	at io.dropwizard.Application.run(Application.java:93)
	at 	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:110)
18:15:21,363 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Attaching appender named [file-appender] to AsyncAppender.
18:15:21,363 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Setting discardingThreshold to 51

WARN   [2020-04-12 18:15:23,018] [main] i.c.ReaperApplication - Reaper is ready to get things done!
==> curl -Im3 -o- http://localhost:8080/webui/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Error: cassandra-reaper: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </200 OK.*/m> was expected to be =~
<"HTTP/1.1 302 Found\r\n" +
"Date: Sun, 12 Apr 2020 22:15:25 GMT\r\n" +
"Set-Cookie: JSESSIONID=node019wd0yhx5lj752iehm3zwjr1e0.node0;Path=/\r\n" +
"Expires: Thu, 01 Jan 1970 00:00:00 GMT\r\n" +
"Location: http://localhost:8080/webui/login.html;jsessionid=node019wd0yhx5lj752iehm3zwjr1e0.node0\r\n" +
"Content-Length: 0\r\n" +
"\r\n">.
```

**Pull request closed without merging**
