### PR TITLE
new formula: vulkan-portability 0.2

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Seems barely notable, too low activity (repo has 3 commits) for us to ship.

**Comment by yurikoles** [comment]
its spec repo, it usually updates when new spec version is issued, see [KhronosGroup/Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers/commits/master) as activity example. For example, you don't expect IETF to issue new revisions of its standard every day.

**Comment by fxcoudert** [comment]
If you need several header-only things for a specific formula (MoltenVK) maybe it makes more sense to vendor them inside the formula. I don't see much use of these headers as a separate entity. (And it makes it difficult to find good tests, too…)

**Comment by rafaga** [comment]
is not only needed to build MoltenVk, it is neededto develop or build other entities basen on vulkan 
i have made a tap to build MoltenVK, using the revision recomended Khronos if you can check, it is still WIP due to the fact it is missing the test https://github.com/rafaga/homebrew-r2k

**Pull request closed without merging**
