### PR TITLE
workflows/tests: don't fail fast

### PR DESCRIPTION
**Pull request by Bo98**
cc @jonchang

### CODE REVIEW

**Review by jonchang — APPROVED** [review]
Hopefully we can migrate fully to GitHub Actions soon so this doesn't murder our queue times!

**Comment by Bo98** [comment]
On that note, can we make it so that new commits to a pull request cancel old builds? I think that would substantially help with build queues.

Not entirely sure what the best approach to that is.

**Comment by jonchang** [comment]
I believe this is a requested feature in Github Actions. I don't know what the timeline is to implement it though.

**Comment by dawidd6** [comment]
We can create an Action that would cancel all previous workflow runs for a specific branch.

**Pull request merged**
