### PR TITLE
mysql mysql-client 8.3.0

### PR DESCRIPTION
**Pull request by bevanjkay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bevanjkay** [comment]
`mysql++` is failing due to the deprecation of `mysql_kill()` and `mysql_refresh()` in 8.3.0 - https://dev.mysql.com/doc/relnotes/mysql/8.3/en/news-8-3-0.html
Has only had ~300 downloads in the last year, and no releases for 3 years, maybe deprecate?

**Comment by bevanjkay** [comment]
`mysql++` report upstream and deprecate

`qt-mysql`

```
/tmp/qt-mysql-20240117-5259-v8oicv/qtbase-everywhere-src-6.6.1/src/plugins/sqldrivers/mysql/qsql_mysql.cpp:1481:20: error: use of undeclared identifier 'mysql_list_fields'

MYSQL_RES *r = mysql_list_fields(d->mysql, table.toUtf8().constData(), nullptr);

^

1 error generated.

make[2]: *** [mysql/CMakeFiles/QMYSQLDriverPlugin.dir/qsql_mysql.cpp.o] Error 1

make[1]: *** [mysql/CMakeFiles/QMYSQLDriverPlugin.dir/all] Error 2

make: *** [all] Error 2
```


`root`

```
2024-01-17T12:50:08.5969830Z /tmp/root-20240117-14093-76plq7/root-6.30.02/sql/mysql/src/TMySQLServer.cxx:642:16: error: use of undeclared identifier 'mysql_reload'
2024-01-17T12:50:08.5970520Z    Int_t res = mysql_reload(fMySQL);
2024-01-17T12:50:08.5970770Z                ^
2024-01-17T12:50:08.5971380Z /tmp/root-20240117-14093-76plq7/root-6.30.02/sql/mysql/src/TMySQLServer.cxx:661:10: error: use of undeclared identifier 'mysql_shutdown'
2024-01-17T12:50:08.5972100Z    res = mysql_shutdown(fMySQL, SHUTDOWN_DEFAULT);
2024-01-17T12:50:08.5972430Z          ^
2024-01-17T12:50:08.5972600Z 2 errors generated.
```


`sys bench`

```
2024-01-17T14:28:05.4632230Z /usr/bin/ld: drivers/mysql/libsbmysql.a(libsbmysql_a-drv_mysql.o): in function `mysql_drv_real_connect':
2024-01-17T14:28:05.4633039Z drv_mysql.c:(.text+0x18c): undefined reference to `mysql_ssl_set'
2024-01-17T14:28:05.4633488Z collect2: error: ld returned 1 exit status
2024-01-17T14:28:05.4633857Z make[2]: *** [Makefile:561: sysbench] Error 1
2024-01-17T14:28:05.4634514Z make[2]: Leaving directory '/tmp/sysbench-20240117-247227-jb93om/sysbench-1.0.20/src'
2024-01-17T14:28:05.4635124Z make[1]: *** [Makefile:622: install-recursive] Error 1
2024-01-17T14:28:05.4635743Z make[1]: Leaving directory '/tmp/sysbench-20240117-247227-jb93om/sysbench-1.0.20/src'
2024-01-17T14:28:05.4636323Z make: *** [Makefile:501: install-recursive] Error 1
```

**Comment by bevanjkay** [comment]
`libzdb` - https://bitbucket.org/tildeslash/libzdb/issues/67/build-error-with-mysql-83

**Comment by bevanjkay** [comment]
`innotop` - https://github.com/innotop/innotop/issues/198
`percona-xtrabackup` - https://perconadev.atlassian.net/browse/PXB-3224
`percona-toolkit` - https://perconadev.atlassian.net/jira/software/c/projects/PT/issues/PT-2312

**Comment by bevanjkay** [comment]
These failures are isolated to macOS 13 only

```
brew install --verbose --build-bottle innotop
brew install --verbose --build-bottle percona-toolkit
brew install --verbose --build-bottle percona-xtrabackup
```

**Review by p-linnane — APPROVED** [review]
Awesome work here!

**Pull request merged**
