### PR TITLE
simgrid 3.25

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Test failed:

```
==> /usr/bin/clang test.c -I/usr/local/Cellar/simgrid/3.25/include -L/usr/local/Cellar/simgrid/3.25/lib -lsimgrid -o test
test.c:3:10: fatal error: 'simgrid/msg.h' file not found
#include <simgrid/msg.h>
         ^~~~~~~~~~~~~~~
1 error generated.
Error: simgrid: failed
```

**Comment by Moisan** [comment]
Our current test is based on a part of `simgrid` that is being deprecated. Either we add flags to keep using the deprecated portion or we find another test.

**Comment by bayandin** [comment]
Thanks for pointing out @Moisan 👍 
Merging it now

**Comment by bayandin** [comment]
https://github.com/Homebrew/homebrew-core/commit/dfbffe58e6bd39474bab3fb1ccb0b714ce495e90

**Pull request closed without merging**
