### PR TITLE
pidgin 2.14.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Pidgin `2.14.1` was released - https://pidgin.im/posts/2020-06-2.14.1-released/

**Comment by dtrodrigues** [comment]
The test is failing because  starting in Pidgin 2.14.x, `finch` requires the standalone `libgnt` library (https://pidgin.im/posts/2020-06-2.14.0-released/ / https://keep.imfreedom.org/libgnt/libgnt) which was refactored out of the main Pidgin repository. Possible solutions include discontinuing support for `finch` (probably not), building `libgnt` as part of the `pidgin` build (probably easiest), or installing `libgnt` as a separate formula (not sure the demand but that seems to be the purpose of removing it from Pidgin in the first place).

**Comment by alebcay** [comment]
Thanks for digging up the information on `libgnt`. I noticed that `libgnt` is only up to 2.14.0, which doesn't track `pidgin`'s 2.14.1. Not sure if they have to match up exactly.

**Comment by dtrodrigues** [comment]
I got PIdgin `2.14.1` building against libgnt `2.14.0` and finch builds/runs now. Would you prefer libgnt be its own formula or be bundled as part of the pidgin build process?

**Comment by alebcay** [comment]
I've bumped `pidgin` to 2.14.1 and created a new formula for `libgnt`. The rationale for this is mostly based on the fact that `libgnt` was already seeing separate release times compared to `pidgin`, ships with its own different build system, could be used in other projects, and is not tightly coupled (version-for-version) with Pidgin.

**Comment by dawidd6** [comment]
Maybe we should add new formula in separate PR to keep things tidy?

**Comment by alebcay** [comment]
Sure, I can do that. This PR will be blocked until the merge of that new formula PR.

**Comment by alebcay** [comment]
Pending #56267.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
