### PR TITLE
libstfl: use Python3

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
cc @MikeMcQuaid this is how it would/should look like.

I couldn't fine a `python-config` for system python 3 though.

**Comment by MikeMcQuaid** [comment]
> I couldn't fine a `python-config` for system python 3 though.

I don't think there is one 😭 

Otherwise: looks good!

**Comment by iMichka** [comment]
`/usr/bin/python3` is actually a stub file, which triggers a CLT install. Sounds ugly ...

https://apple.stackexchange.com/questions/376077/is-usr-bin-python3-provided-with-macos-catalina

Looks like the Python 3 stuff then gets installed to `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7`. But no sign of `pkg-config`. This may be an issue. I'll have to setup the cflags manually.

**Comment by iMichka** [comment]
Also: I disagree with the system Python 3.7 vs brewed Python 3.8 strategy here. It looks tempting, because we would follow the historical way homebrew has been designed: use as much as possible system libraries. But I dislike the fact that we are now adding complexity to the formulae.

If we want to be strict with this, we need probably to go back, and make the same changes to at least 100 formulae (where we used brewed Python 3.8).

Also, the fact that system Python 3 is installed through the CLT is not making this solution look nice (is Python 3 still a system library? Will the CLT still exist in a few years from now?)

I am in favour of using plain brewed Python@3.8 here for simplicity, and I would gather some opinions from other @Homebrew/core maintainers.

**Comment by issyl0** [comment]
I agree with Michka. This PR's approach is way harder to understand (too many branches and possibilities) than standardising on using `depends_on "python@3.8"` in formulae that support it (which we've already been moving towards).

**Comment by Bo98** [comment]
Do we actually even require the CLT to be installed on Catalina? I thought we only do for older releases. If that's right, we shouldn't assume that the CLT is installed on Catalina.

**Comment by SMillerDev** [comment]
We require the CLT to be present when installing homebrew on all OS versions.
While I would prefer the system library approach I think being located in the CLT might make installs more complicated then they need to be. Can the homebrew TSC decide on this?

**Comment by Bo98** [comment]
Indeed we install the CLT in the Homebrew installer, but thereafter [we don't _require_ it](https://github.com/Homebrew/brew/blob/b1eb96dfddbbcaa7fef56c98f95037199ee56977/Library/Homebrew/os/mac/xcode.rb#L50). We also don't mandate CLT installation through [other documented installation methods](https://docs.brew.sh/Installation.html):

> You can install Xcode, the CLT, or both; Homebrew supports all three configurations.

This is shown by the effort we put in to have CLT checks, e.g. https://github.com/Homebrew/homebrew-core/search?q=CLT&unscoped_q=CLT and https://github.com/Homebrew/brew/blob/88a13346647067538e1db462795a97892c82daf1/Library/Homebrew/os/mac.rb#L115-L119

**Comment by MikeMcQuaid** [comment]
Given the above: I'm fine just using the brewed Python 3. Thanks for investigating @iMichka!

**Comment by iMichka** [comment]
Thanks @MikeMcQuaid

**Pull request closed without merging**
