### PR TITLE
guile 3.0.0

### PR DESCRIPTION
**Pull request by ngquerol**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ngquerol** [comment]
Looks like this new major version breaks two other formulas, namely `mdk` & `autogen`. They both look for guile <= 2.2 pkg-config files, and so should be updated upstream.

In the meantime we could split this formula so that we have `guile@2` & `guile@3`, and update existing formulas so that they depend on `guile@2`. Thoughts ?

**Comment by fxcoudert** [comment]
Revision for `autogen` and `mdk`.

**Comment by fxcoudert** [comment]
`autogen` indeed doesn't like guile 3:

```
configure: checking for guile 2.2
configure: checking for guile 2.0
configure: checking for guile 1.8
configure: error: 
No Guile development packages were found.
```

I have reported this to  the autogen project: https://sourceforge.net/p/autogen/bugs/196/

**Comment by brkorb** [comment]
Once upon a time, long ago tho not far away, Guile would change its interface even on minor releases causing dependent programs to fail in inscrutable ways. I haven't seen that behavior now for over a decade, so I think it is time to remove the version checks and go back to inscrutable failures in the event of Guile interface changes. I just have to hope they won't do it again.

Please expect an "upstream" release in the next few weeks. Meantime, feel free to hack the source to eliminate the version check. Thank you!

**Comment by fxcoudert** [comment]
Thanks @brkorb. Homebrew's policy is to only ship patches that have been accepted by upstream (they're the ones who know their software best!), so we'll wait on you :)

**Comment by ngquerol** [comment]
I should add that I provide a [tap](https://github.com/ngquerol/homebrew-guile) for those willing to install guile 3 alongside the existing guile 2, pending its *official* integration into Homebrew.

**Pull request closed without merging**
