### PR TITLE
libtermkey 0.21

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by schanzel** [comment]
Could it be that this breaks neovim?

```bash
$ nvim
Abort trap: 6
```

**Comment by lembacon** [comment]
Oops, it seems this does indeed break neovim. 🙃

We have a few options now:

- Simply revert this `libtermkey` 0.21 update.
- Revert this update, and also bump the `version_scheme`.
- Do nothing, wait for neovim people to figure this out. https://github.com/neovim/neovim/issues/9630#issuecomment-465253453

@Homebrew/maintainers Any preferences?

**Comment by sjackman** [comment]
Could someone please test whether reinstall neovim from source fixes the issue?
```sh
brew reinstall -s neovim
```

**Comment by ohwillie** [comment]
@sjackman installing from source right now

**Comment by mhinz** [comment]
The issue is with libtermkey. It also happens if you compile it from source and dynamically link it against libtermkey from Homebrew.

**Comment by jpmontez** [comment]
> Could someone please test whether reinstall neovim from source fixes the issue?
> 
> ```shell
> brew reinstall -s neovim
> ```

I tried this. It doesn't solve it.

**Comment by mhinz** [comment]
I vote for reverting back to the previous version of libtermkey for now. The Neovim team contacted the author of  libtermkey.

**Comment by mhinz** [comment]
https://github.com/neovim/neovim/issues/9630#issuecomment-465261774

**Comment by sjackman** [comment]
I suggest we wait a few hours to see if the `libtermkey` / `neovim` developers roll out a hot fix.

**Comment by sjackman** [comment]
Or if the patch in https://github.com/neovim/neovim/issues/9630#issuecomment-465261774 is known to work, we apply the patch to `libtermkey` and bump the revision.

**Comment by mhinz** [comment]
I can confirm that the patch from the comment fixes the problem.

**Pull request closed without merging**
