### PR TITLE
readline 7.0.3

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
The CI failures look unrelated. But `readline` is an optional `wine` dep, so we probably shouldn't remove `ENV.universal_binary` yet.

**Comment by JCount** [comment]
Added back in the universal build, good job noticing the optional wine dependency @fxcoudert

**Comment by ilovezfs** [comment]
It looks like there are some others we should probably walk back:
```
Josephs-MacBook-Pro:~ joe$ brew deps --include-optional wine|while read f; do brew cat $f|grep -q universal || echo $f; done
gmp
gnutls
guile
libevent
libexif
libunistring
net-snmp
nettle
p11-kit
pkg-config
sane-backends
unbound
webp
xz
```

Also, hopefully there is no opportunistic linkage from these, which are added by `--include-build`:
```
atk
autoconf
automake
berkeley-db@4
cairo
cmake
doxygen
gdbm
gdk-pixbuf
gettext
glib
gobject-introspection
graphite2
graphviz
gsettings-desktop-schemas
gtk+3
gts
harfbuzz
hicolor-icon-theme
homebrew/dupes/tcl-tk
icu4c
intltool
libatomic_ops
libcroco
libepoxy
libgsf
librsvg
libxml2
makedepend
netpbm
ocaml
pango
pcre
pixman
qt5
shared-mime-info
sphinx-doc
sqlite
```

**Comment by JCount** [comment]
@ilovezfs I add back in universal options to the four from the first group that appear to have had one removed. As far as I can tell, the rest never had the option. See #10422

**Pull request closed without merging**
