### PR TITLE
node 14.0.0

### PR DESCRIPTION
**Pull request by billinghamj**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by issyl0** [comment]
Thanks for this PR!

> ERROR: icu4c v64.2 is too old, v65.x or later is required.

This depends on the in-progress (ish) #52481 for the newest version of `icu4c`. So I guess it's a waiting game.

**Comment by billinghamj** [comment]
👋 Haven't seen you for a veeeery long time! :)

**Comment by issyl0** [comment]
I was thinking that too! Hi, James! 👋

**Comment by faradaytrs** [comment]
can we speed this up

**Comment by SMillerDev** [comment]
No, we're all volunteers here. A maintainer will get to it when they have time.

**Comment by billinghamj** [comment]
Looks like currently dependent on #52481 & #53506. Shouldn't take too long :)

**Comment by billinghamj** [comment]
Rebased. Should be good to go now I think!

**Comment by billinghamj** [comment]
It seems like `bcoin` and `joplin` failed. Not entirely clear why though

**Comment by billinghamj** [comment]
```
❯ brew test --verbose bcoin
Testing bcoin
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200423-9561-u62kyq.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bcoin.rb --verbose
==> /usr/local/opt/node/bin/node /private/tmp/bcoin-test-20200423-9562-q6peq3/script.js
/usr/local/Cellar/bcoin/2.0.0/libexec/lib/node_modules/bcoin/node_modules/loady/lib/loady.js:109
      throw e;
      ^

Error: Module did not self-register: '/usr/local/Cellar/bcoin/2.0.0/libexec/lib/node_modules/bcoin/node_modules/bcrypto/build/Release/bcrypto.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1235:18)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/usr/local/Cellar/bcoin/2.0.0/libexec/lib/node_modules/bcoin/node_modules/loady/lib/loady.js:98:17)
    at Object.<anonymous> (/usr/local/Cellar/bcoin/2.0.0/libexec/lib/node_modules/bcoin/node_modules/bcrypto/lib/native/binding.js:14:33)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
Error: bcoin: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1987:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1925:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1925:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bcoin.rb:37:in `block in <class:Bcoin>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1795:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1794:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:867:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1793:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2037:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2036:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1787:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
```

**Comment by billinghamj** [comment]
```
❯ brew test --verbose joplin
Testing joplin
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200423-16893-dmhyk.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/joplin.rb --verbose
==> /usr/local/Cellar/joplin/1.0.163/bin/joplin config editor subl
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module '/usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node'
Require stack:
- /usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js
- /usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/lib/database-driver-node.js
- /usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/lib/BaseApplication.js
- /usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/app.js
- /usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js',
    '/usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/lib/database-driver-node.js',
    '/usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/lib/BaseApplication.js',
    '/usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/app.js',
    '/usr/local/Cellar/joplin/1.0.163/libexec/lib/node_modules/joplin/main.js'
  ]
}
Error: joplin: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1987:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1925:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1925:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/joplin.rb:27:in `block in <class:Joplin>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1795:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1794:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:867:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1793:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2037:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2036:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1787:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
```

**Comment by billinghamj** [comment]
What is typically the approach to this kind of situation? Do we just have to file issues with the other projects and wait until they've resolved downstream before the new Node can be made available?

**Comment by bayandin** [comment]
Could you try to bump revisions for `bcoin` and `joplin` (I'm not sure, but it looks like they aren't compatible with node update):

```
brew bump-revision --message="for node" bcoin
brew bump-revision --message="for node" joplin
```

**Comment by billinghamj** [comment]
Doesn't seem to help - I'm pretty sure the projects just aren't compatible yet. Maybe they could be attached to the last LTS instead - node@12?

**Comment by SMillerDev** [comment]
Can you file an issue and change them to node@12?

**Comment by billinghamj** [comment]
Sorry actually I think I'm mistaken. Don't really understand why it makes a difference, but bumping the revisions seemingly has fixed it :)

**Comment by Bo98** [comment]
> `Cannot find module ... node-v83-darwin-x64 ...`

Yeah, that makes sense. Node 13 was v79. Revision bump is the right thing to do.

**Comment by billinghamj** [comment]
Looks like it's good to merge :)

**Comment by issyl0** [comment]
Thanks again, @billinghamj! :wave:

**Pull request closed without merging**
