### PR TITLE
apr: depend on libxcrypt

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by Bo98** [comment]
```
 Dependencies with no linkage:
  libxcrypt
```

**Comment by carlocab** [comment]
Well, that was pointless. Should've checked more carefully; sorry.

**Comment by shivammathur** [comment]
@carlocab 

Possibly as this was run by skipping dependents we have the issue In https://github.com/Homebrew/homebrew-core/pull/100296 again.

https://github.com/shivammathur/homebrew-php/runs/7985886068?check_suite_focus=true#step:8:272

Should I create a PR with a revision bump on `httpd` to rebuild it?

**Comment by carlocab** [comment]
Yes please. Thanks @shivammathur.

**Pull request closed without merging**
