### PR TITLE
oil 0.12.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Still linux build failure, should we just disable the linux build instead?

**Comment by chenrui333** [comment]
@danielnachun, per your comment in [here](https://github.com/Homebrew/homebrew-core/pull/111428#issuecomment-1257258207), I am thinking to ignore linux test, what do you think? Also going to file an issue to the upstream to get some help.

**Comment by chenrui333** [comment]
I cannot reproduce the linux issue, here is the test output

```
==> Testing oil
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.9/bin/osh -c shopt -q parse_backticks
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.9/bin/osh -c 'echo `pwd -P`'
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.9/bin/oil -c shopt -u parse_equals
==> /home/linuxbrew/.linuxbrew/Cellar/oil/0.12.9/bin/oil -c 'var foo = "bar"; write $foo'
@chenrui333 ➜ /workspaces/homebrew-core (bump-oil-0.12.9) $ uname -a
Linux codespaces-d485d1 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by danielnachun** [comment]
Actually, I have managed to reproduce it now in Docker and it is definitely broken on Linux.  

@Bo98 I believe this another case of broken relocation, because the test passes if I do:
```
brew install -s oil
brew test oil
```
with but fails if I do: 
```
brew install --build-bottle oil
brew bottle oil
brew uninstall oil
brew install -f ./oil--0.12.9.x86_64_linux.bottle.tar.gz
brew test oil
```

In the previous relocation problems we've had this is always the pattern - building directly from source has no issues because no relocation is happening, while installing from a bottle leads to a failure.

I'm not really sure of what to make of these lines in the Makefile which seem to append the app bundle to the end of the binaries:
```
# App bundles.
_bin/%.ovm-dbg: _build/%/ovm-dbg _build/%/$(BYTECODE_ZIP)
	cat $^ > $@
	chmod +x $@

_bin/%.ovm: _build/%/ovm-opt.stripped _build/%/$(BYTECODE_ZIP)
	cat $^ > $@
	chmod +x $@

# Optimized version with symbols.
_bin/%.ovm-opt: _build/%/ovm-opt _build/%/$(BYTECODE_ZIP)
	cat $^ > $@
	chmod +x $@
```
Interestingly I was able to package this in Anaconda which uses a very similar relocation strategy and it works with no issues, so I suspect this is specific to our relocation approach.

**Comment by danielnachun** [comment]
@chenrui333 I think this is not a trivial problem to fix and I think we should delete the Linux bottle line so we can at least get an updated bottle to macOS users and not ship a broken one to Linux users.

I'm guessing something may have changed with how they are packaging this app bundle that has made this, for now, incompatible with our relocation strategy.  Fortunately this is trivial to build from source so it's not going to be hugely disruptive for Linux users to build this from source until this problem is fixed.

**Review by cho-m — APPROVED** [review]

**Comment by Bo98** [comment]
Thanks for the ping. Noted this one down and will take a look.

**Comment by chenrui333** [comment]
let me see if I can merge this PR without linux bottle. Otherwise, I will remove the linux bottle in a separate PR then.

**Comment by chenrui333** [comment]
Looks like it works, thanks folks!

**Pull request closed without merging**
