### PR TITLE
v2ray: update geo data

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
> Considering that the release/update cadence and version scheme of this data is different from that of `v2ray` itself, would it be worth considering putting these into their own formulae?

I dont know how to better handle data stuff, but technically, we can also livecheck those resources.

**Comment by p-linnane** [comment]
There's some idiosyncrasies with livechecking resources.

cc @samford @nandahkrishna

**Review by nandahkrishna — COMMENTED** [review]
I've been meaning to get to these at some point, but I'm unsure if this should be fixed in Homebrew/brew or in the formulae themselves. What's happening is that the versions for these resources aren't getting detected from their URLs. A simple fix would be just adding a `version` like so:
```
resource "geoip" do
  url "https://github.com/v2fly/geoip/releases/download/202306010100/geoip.dat"
  version "202306010100"
  sha256 "033864e77e40f8b9c1a5254bf85881515c51340d3d11e142a4e01594eb151914"
end
```
However I wonder if it would be possible to avoid this by changing the version parsing from URLs in Homebrew/brew.

The `livecheck` for these resources works fine though (by default), it's just that incorrect information is displayed for the current version:
```
v2ray: 5.7.0 ==> 5.7.0
  geoip (guessed): 5.7.0 ==> 202307060057
  geoip-only-cn-private (guessed): 5.7.0 ==> 202307060057
  geosite (guessed): 5.7.0 ==> 20230711133630
```

**Comment by carlocab** [comment]
> Considering that the release/update cadence and version scheme of this data is different from that of `v2ray` itself, would it be worth considering putting these into their own formulae?

This sounds like the ideal situation for me if `v2ray` can be pointed at the new prefix for the separate formulae.

**Comment by alebcay** [comment]
> This sounds like the ideal situation for me if `v2ray` can be pointed at the new prefix(es) for the separate formula(e).

This should be possible. The current prefix is `pkgshare`, or `share/"v2ray"`. We can also install the dat files as additional formula(e) into `share/"v2ray"`.

We already use a similar approach for `pari` to consume additional data from `pari-seadata`, `pari-elldata`, etc. formulae.

**Review by alebcay — APPROVED** [review]
👍 this for now. We can try moving the data to separate formulae in another PR.

**Pull request merged**
