### PR TITLE
cpr 1.8.3

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Continuation of #98161. Adding `CI-no-fail-fast` to check if build succeeds across Intel platforms, as I am able to build this locally on Intel Monterey, so that issue can be raised upstream.

### CODE REVIEW

**Comment by Bo98** [comment]
`CURLOPT_SSLKEY_BLOB` requires Curl 7.71.0 or later, so this might need `uses_from_macos "curl", since: :monterey`.

**Comment by Bo98** [comment]
Or actually it should probably be patched with `LIBCURL_VERSION_NUM` checks since there's several of those already: https://github.com/libcpr/cpr/search?q=LIBCURL_VERSION_NUM

**Comment by alebcay** [comment]
Thanks for the insight, Bo. The CI results are consistent with what you pointed out. I'll open an upstream issue regarding the need to guard usage of `CURLOPT_SSLKEY_BLOB`.

**Comment by alebcay** [comment]
One thing I'm confused about: the curl version reported in the failed 11-arm64 run is 7.64.1. But the curl version reported on my Monterey machine (from inside Xcode) is also 7.64.1. It builds fine on my machine, but not the Big Sur, even though both are apparently detected as curl 7.64.1.

**Comment by Bo98** [comment]
> the curl version reported on my Monterey machine (from inside Xcode) is also 7.64.1

Monterey 12.0-12.2 should be 7.77.0.
12.3 updated to 7.79.1.

Where are you seeing 7.64.1? Are you using the macOS 11 SDK?

**Comment by alebcay** [comment]
No, it seems to be the 12.3 SDK that I'm using:
```
-- Found CURL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libcurl.tbd (found version "7.64.1") found components: HTTP HTTPS
-- Curl 7.64.1 found on this system.
```

**Comment by Bo98** [comment]
Try `brew reinstall pkg-config`. You might be using one from a Big Sur bottle (we should really tackle forced updates for that at some point).

**Comment by alebcay** [comment]
Ah, that fixed it.
```
-- Found CURL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libcurl.tbd (found version "7.79.1") found components: HTTP HTTPS
-- Curl 7.79.1 found on this system.
```

**Comment by Bo98** [comment]
Another example where our [pkg-config files](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/os/mac/pkgconfig/12) appear to be the glue for some build systems once again.

**Comment by alebcay** [comment]
Opened the issue https://github.com/libcpr/cpr/issues/732 upstream. As an aside, I wonder if it might make more sense to point `pkg-config` to a location like `$HOMEBREW_LIBRARY/os/mac/pkgconfig/current` and let Homebrew manage symlinking the particular version to that location (and update the symlink when a new OS version is detected, etc).

**Comment by Bo98** [comment]
Seems like a decent idea.

**Comment by chenrui333** [comment]
cpr 1.8.2 is released.

**Comment by alebcay** [comment]
Issue is not fixed in 1.8.2, issue has been identified. Downstream patch is available and I'm in the process of contributing it back to upstream.

**Comment by carlocab** [comment]
> Opened the issue [libcpr/cpr#732](https://github.com/libcpr/cpr/issues/732) upstream. As an aside, I wonder if it might make more sense to point `pkg-config` to a location like `$HOMEBREW_LIBRARY/os/mac/pkgconfig/current` and let Homebrew manage symlinking the particular version to that location (and update the symlink when a new OS version is detected, etc).

I like this idea.

**Comment by alebcay** [comment]
1.8.3 has been released upstream with a fix.

> > Opened the issue [libcpr/cpr#732](https://github.com/libcpr/cpr/issues/732) upstream. As an aside, I wonder if it might make more sense to point `pkg-config` to a location like `$HOMEBREW_LIBRARY/os/mac/pkgconfig/current` and let Homebrew manage symlinking the particular version to that location (and update the symlink when a new OS version is detected, etc).
> 
> I like this idea.

Feel free to have a go at implementing this if you're interested; I did try to poke around in `Homebrew/brew` recently but work has been especially busy for me as of late.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
