### PR TITLE
tcl-tk: add main lib dir to package search path

### PR DESCRIPTION
**Pull request by gromgit**
Currently, `tcl-tk`'s package search path only includes its own directories:
```
$ /usr/local/opt/tcl-tk/bin/tclsh <<<'puts $auto_path'
/usr/local/Cellar/tcl-tk/8.6.12_1/lib/tcl8.6 /usr/local/Cellar/tcl-tk/8.6.12_1/lib /usr/local/opt/tcl-tk/lib

$ ls /usr/local/lib/expect5.45.4/
libexpect5.45.4.dylib  pkgIndex.tcl

$ /usr/local/opt/tcl-tk/bin/tclsh <<<'puts [package require Expect]'
can't find package Expect
```
so packages from other formulae like `expect` can't be loaded, even after they're linked into the main lib dir at install time.

This PR adds the main lib dir to the search path:
```
$ /opt/homebrew/opt/tcl-tk/bin/tclsh <<<'puts $auto_path'
/opt/homebrew/Cellar/tcl-tk/8.6.12_2/lib/tcl8.6 /opt/homebrew/Cellar/tcl-tk/8.6.12_2/lib /opt/homebrew/opt/tcl-tk/lib /opt/homebrew/lib

$ ls /opt/homebrew/lib/expect5.45.4/
libexpect5.45.4.dylib	pkgIndex.tcl

$ /opt/homebrew/opt/tcl-tk/bin/tclsh <<<'puts [package require Expect]'
5.45.4
```
Also added a test to confirm the path, in case upstream breaks this configuration process at some point.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by gromgit** [comment]
This is a more generalized fix than #113812, and @carlocab [wondered therein](https://github.com/Homebrew/homebrew-core/pull/113812#issuecomment-1287988150):
> I wonder if we should just make `tcl-tk` not-keg-only instead.
> 
> The macOS version is old and buggy, and the formula ships versioned libraries so there's little danger of other things picking it up when they wanted the system version (even though they usually don't).

Indeed, both system and Homebrew Tcls already don't see each other's libraries by default:
```
$ /usr/bin/tclsh <<<'puts $auto_path'
/System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/Scripts /System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources /usr/lib ~/Library/Tcl /Library/Tcl /System/Library/Tcl /System/Library/Tcl/8.5 ~/Library/Frameworks /Library/Frameworks /System/Library/Frameworks
```
and I can't think of a reason not to "expose" Homebrew Tcl.

**Comment by carlocab** [comment]
Ok, so should we make this not-keg-only?

**Comment by gromgit** [comment]
> Ok, so should we make this not-keg-only?

Might as well try it, at least to see if anything depending on `tcl-tk` goes wonky.

**Comment by gromgit** [comment]
> > Ok, so should we make this not-keg-only?
> 
> Might as well try it, at least to see if anything depending on `tcl-tk` goes wonky.

Well, that was a bust. Conflicting Aqua-enabled X11 headers are installed by `tcl-tk` for (I guess) stuff linking with the Tk library, like `python-tk`:
```
  ==> Pouring xorgproto--2022.2.arm64_monterey.bottle.tar.gz
  The formula built, but is not symlinked into /opt/homebrew
  Error: The `brew link` step did not complete successfully
  Could not symlink include/X11/DECkeysym.h
  Target /opt/homebrew/include/X11/DECkeysym.h
  is a symlink belonging to tcl-tk. You can unlink it:
    brew unlink tcl-tk
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite xorgproto
  
  To list all files that would be deleted:
    brew link --overwrite --dry-run xorgproto
  
  Possible conflicting files are:
  /opt/homebrew/include/X11/DECkeysym.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/DECkeysym.h
  /opt/homebrew/include/X11/HPkeysym.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/HPkeysym.h
  /opt/homebrew/include/X11/Sunkeysym.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/Sunkeysym.h
  /opt/homebrew/include/X11/X.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/X.h
  /opt/homebrew/include/X11/XF86keysym.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/XF86keysym.h
  /opt/homebrew/include/X11/Xatom.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/Xatom.h
  /opt/homebrew/include/X11/Xfuncproto.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/Xfuncproto.h
  /opt/homebrew/include/X11/ap_keysym.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/ap_keysym.h
  /opt/homebrew/include/X11/keysym.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/keysym.h
  /opt/homebrew/include/X11/keysymdef.h -> /opt/homebrew/Cellar/tcl-tk/8.6.12_2/include/X11/keysymdef.h
```
Reverting to keg-only then.

**Comment by gromgit** [comment]
I completely forgot about this PR. Anything else that needs doing?

**Comment by gromgit** [comment]
Crap, sorry, messed up a rebase. Will close and start another PR.

**Pull request closed without merging**
