### PR TITLE
grafana-agent 0.26.0

### PR DESCRIPTION
**Pull request by grafanabot**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==>/opt/homebrew/Cellar/grafana-agent/0.26.0/bin/grafana-agentctl config-check /private/tmp/grafana-agent-test-20220718-86635-ua5jz8/grafana-agent.yaml
  failed to validate config: yaml: unmarshal errors:
    line 3: field http_listen_port not found in type server.config
    line 4: field grpc_listen_port not found in type server.config
  Error: grafana-agent: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /opt/homebrew/Cellar/grafana-agent/0.26.0/bin/grafana-agentctl config-check /private/tmp/grafana-agent-test-20220718-86635-ua5jz8/grafana-agent.yaml
```

**Comment by rlankfo** [comment]
Thanks @chenrui333 🙏 

I'll plan to re-base this PR once the following fix is merged:
- https://github.com/Homebrew/homebrew-core/pull/106079

**Comment by chenrui333** [comment]
Sounds good, thanks!

**Comment by chenrui333** [comment]
> Version v0.26.0 of grafana-agent introduced a dependency on [libbcc](https://github.com/iovisor/bcc) (only on Linux). Is it possible to define a `depends_on` relationship for this library w/o introducing a formula for it?

yeah, you can make a resource and added it as part of the installation process.

**Comment by chenrui333** [comment]
but why can't we add a formulae for bcc? I can see many package managers already included it.

**Comment by rlankfo** [comment]
> but why can't we add a formulae for bcc? I can see many package managers already included it.

I'll look into adding a formula for this. Thanks @chenrui333

**Comment by rlankfo** [comment]
@chenrui333 took a shot at adding this formula, but it's still a work in progress. Any help is appreciated: https://github.com/Homebrew/homebrew-core/pull/106250

**Pull request closed without merging**
