### PR TITLE
rich-cli: renamed from richmd

### PR DESCRIPTION
**Pull request by branchv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

`rich` now has its [own CLI](https://github.com/Textualize/rich-cli), which feels more appropriate here

### CODE REVIEW

**Comment by branchvincent** [comment]
Oops: `GitHub repository too new (<30 days old)`

It does already have 1k stars, but I'm also fine waiting

**Review by dtrodrigues — APPROVED** [review]

**Comment by willmcgugan** [comment]
Author of rich-cli here. I was planning on proposing this myself once the dust settled.

Does this install the command as "rich-cli" ?  I would much prefer the simpler "rich".

**Comment by SMillerDev** [comment]
The command is the same as you wrote it, but the package name is `rich-cli` since that's also the name of the project.

**Comment by willmcgugan** [comment]
The Pypi name is `rich-cli` to differentiate it from `rich` the library. But if you install rich-cli it adds `rich` to the path.

I appreciate @branchvincent adding this, but if its possible I'd like to change the name back to `rich`.

**Comment by SMillerDev** [comment]
It was never called `rich`, it was called `richmd`.

**Comment by willmcgugan** [comment]
The Python library is called `rich`. `richmd` is the name of the brew package which exposed an internal command within Rich. I didn't add that, as it was never really intended as a standalone thing.

But now there is the [Rich CLI](https://github.com/Textualize/rich-cli) project which *is* intended as a standalone application (and does a lot more than just Markdown). I was going to add this to brew under the name `rich`, but this PR beat me to it.

Having the brew package install `rich-cli` for no good reason when `rich` doesn't conflict with anything is forever going to be a source of confusion, especially given the app is called `rich` everywhere else.

I'm happy to do the legwork to create a PR to change the name.

**Comment by SMillerDev** [comment]
Since the project is `rich-cli` and the command `rich`, why not just add an alias to the current formula so people can find it as `rich` too?

**Comment by branchvincent** [comment]
A rename sounds good to me, I just went with the PyPI name

**Pull request closed without merging**
