### PR TITLE
monero 0.12.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
remove readline dependency
depend on unbound and zeromq
vendor cppzmq
update test

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
-- Looking for libunbound
CMake Error at external/CMakeLists.txt:82 (add_subdirectory):
  The source directory
    /tmp/monero-20180325-99041-c3uwz9/monero-0.12.0.0/external/unbound
  does not contain a CMakeLists.txt file.
```

and

```
-- Could not find GNU readline library so building without readline support
CMake Error at CMakeLists.txt:848 (message):
  Could not find required header zmq.hpp
```

**Comment by sammy007** [comment]
Omg, there is a dependency on unbound as submodule and github tarballs are missing submodules. Use git tags.

**Comment by ilovezfs** [comment]
@sammy007 nope. Using the unbound formula is supported by the build system so we will do that as we do elsewhere (e.g. see [grpc](https://github.com/Homebrew/homebrew-core/blob/master/Formula/grpc.rb)).

**Comment by sammy007** [comment]
Highly likely there is submodule because it depends on a special revision of unbound.

**Comment by ilovezfs** [comment]
@sammy007 that is up to the build system to decide.

**Comment by jtgrassie** [comment]
`system "make", "install"` is doing the debug build. Probably should do `make release install`.

Also, why drop readline? Believe the homebrew checks now work for brew installed readline (though may not be in 12.0, will be in next point release).

Lastly, unbound, this is a submodule in monero so no need to depend on unbound in the formula (the submodule has modifications which is why it's there and is used).

**Comment by ilovezfs** [comment]
@jtgrassie 

>`system "make", "install"` is doing the debug build. Probably should do `make release install`.

Even though we always pass `-DCMAKE_BUILD_TYPE=Release` in `std_cmake_args`?

>Also, why drop readline? Believe the homebrew checks now work for brew installed readline (though may not be in 12.0, will be in next point release).

`brew linkage` showed the dependency was not being used at all. I can manually force it to be used by passing `-DReadline_ROOT_DIR=/usr/local/opt/readline`

>Lastly, unbound, this is a submodule in monero so no need to depend on unbound in the formula (the submodule has modifications which is why it's there and is used).

Because the build system uses Homebrew's unbound instead of the submodule if Homebrew's unbound just happens to be installed. I can attempt to force the submodule to be used but if the submodule should always be preferred over an externally installed version, that "shouldn't" be necessary.

**Comment by ilovezfs** [comment]
```
==> make release install
make: *** No rule to make target `release'.  Stop.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make release install
```

**Comment by ilovezfs** [comment]
Yeah, it's still using Homebrew's unbound even if I pass `-DINSTALL_VENDORED_LIBUNBOUND=ON`.

**Comment by ilovezfs** [comment]
@jtgrassie see https://github.com/monero-project/monero/blob/master/CMakeLists.txt#L887-L889

**Comment by jtgrassie** [comment]
Release builds: There is definitely a release target in the official Makefile so not sure why brew is complaining for you. But yes, `-DCMAKE_BUILD_TYPE=Release` should enforce, you'll need to double check build logs to be sure.

Readline: You can add a depends for gnu readline and force finding it with the `-DReadline_ROOT_DIR=/usr/local/opt/readline` flag for now, but it will be fixed anyway when https://github.com/monero-project/monero/pull/3708 gets merged.

Unbound: Just remove the depends in the formula should be all that's needed.

**Comment by ilovezfs** [comment]
>Unbound: Just remove the depends in the formula should be all that's needed.

That only works if `unbound` isn't already installed as CMake is strictly preferring the Homebrew unbound if it's there.

**Comment by ilovezfs** [comment]
>Release builds: There is definitely a release target in the official Makefile so not sure why brew is complaining for you.

running `cmake` regenerates the Makefile, so the one you have checked into source control is overwritten

**Comment by jtgrassie** [comment]
But why are you running cmake directly? The official Makefile runs cmake and builds into the build/[debug|release] directory.

**Comment by ilovezfs** [comment]
>But why are you running cmake directly? The official Makefile runs cmake and builds into the build/[debug|release] directory.

That's just a pattern in Homebrew so that we can use the `std_cmake_args` DSL which passes:
```
irb(monero):001:0> std_cmake_args
=> ["-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/monero/0.12.0.0_2", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_FIND_FRAMEWORK=LAST", "-DCMAKE_VERBOSE_MAKEFILE=ON", "-Wno-dev", "-DHAVE_CLOCK_GETTIME:INTERNAL=0"]
irb(monero):002:0> 
```

**Comment by ilovezfs** [comment]
>but it will be fixed anyway when monero-project/monero#3708 gets merged.

Note that the Homebrew prefix is not necessarily /usr/local (that is only the default), so that PR doesn't obviate the need to specify the location of readline.

You'd need to use something like `brew --prefix readline` to handle it correctly.

**Comment by jtgrassie** [comment]
The patch is specifically a fix for Homebrew installed readline. When that's merged you won't need `-DReadline_ROOT_DIR=/usr/local/opt/readline` (not that it matters, as being specific doesn't hurt).

**Comment by ilovezfs** [comment]
@jtgrassie yes but that patch is hard coding the Homebrew prefix, which is not correct.

**Comment by jtgrassie** [comment]
No it's not. The paths are hints.

**Comment by ilovezfs** [comment]
@jtgrassie Ah OK. I've opened https://github.com/Homebrew/homebrew-core/pull/27968 if you want to look it over.

**Pull request closed without merging**
