### PR TITLE
r: patch for Ventura

### PR DESCRIPTION
**Pull request by fxcoudert**
Bug reported at https://bugs.r-project.org/show_bug.cgi?id=18426
Patch submitted there as well.

### CODE REVIEW

**Comment by Bo98** [comment]
Looks like upstream might have amended the patch slightly judging by the latest comment in that issue.

**Comment by fxcoudert** [comment]
Yes, we should use https://github.com/r-devel/r-svn/commit/ee8e200e021c2783a0e325bd32b0111a35714f5f instead. Can't do it right now…

**Comment by p-linnane** [comment]
@fxcoudert Please let me know if I didn't do this right 😄

**Comment by fxcoudert** [comment]
Patch does not apply cleanly, we'll need to host an adapted copy.

**Review by SMillerDev — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
