### PR TITLE
stlink 1.6.0

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zbeekman** [comment]
@EricFromCanada any chance you have thoughts on how to implement a better test for this?

**Comment by EricFromCanada** [comment]
I doubt it could be properly tested without the hardware attached.

**Comment by SMillerDev** [comment]
Not even checking for a failure?

**Comment by SMillerDev** [comment]
Not even checking for a failure?

**Comment by zbeekman** [comment]
Yeah something like:
```
$ st-util -v -1
st-util 1.5.1
2020-02-24T09:21:59 WARN sg.c: Failed to find an stlink v1 by VID:PID
2020-02-24T09:21:59 ERROR sg.c: Could not open stlink device
```

Verify exit code is non-zero and that devices not found, and that the version info is printed, maybe?

**Comment by zbeekman** [comment]
Can also test the flash binary:
```
$ st-flash --debug reset
st-flash 1.5.1
2020-02-24T09:23:19 WARN usb.c: Couldn't find any ST-Link/V2 devices
```

**Pull request closed without merging**
