### PR TITLE
libass 0.16.0

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failure with `pc6001vx` and `virt-manager`

**Comment by chenrui333** [comment]
`pdfsandwich` is known test failure on linux.

**Comment by owine** [comment]
`pianod` linkage fixed in #100627

**Comment by owine** [comment]
Remains blocked by linkage fixes in other PRs

**Comment by owine** [comment]
> `pianod` linkage fixed in #100627



> Remains blocked by linkage fixes in other PRs

**Comment by chenrui333** [comment]
known linux failure

```
brew test --retry --verbose pdfsandwich
```

**Pull request closed without merging**
