### PR TITLE
nift 2.4.11

### PR DESCRIPTION
**Pull request by n-ham**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
I've noticedd that `nift` compiles bundled `luajit`. Will it be possible to link it against luajit from homebrew? 
We have `luajit` 2.0.5 (which is not updated for quite a time) and `luajit-openresty` 2.1-20201229

**Comment by carlocab** [comment]
It actually bundles an old-ish LuaJIT (but still a newer version than Homebrew `luajit`), which probably explains why it hasn't been bottled for ARM yet.

**Comment by n-ham** [comment]
I tend to have the beta version of LuaJIT embedded, I can't remember what the problem was with the non-beta version but I had something that didn't work, there's a good chance though that might have been Windows specific or something. 

I think it's the latest beta version available on the official site that I have embedded, though Mike fixed up even some compiler flags I got about unused variables for LuaJIT (probably a result of me having extra flags in the Nift makefile). I am not sure how much he is working on it these days though, so unsure whether he will ever do another official beta release even. 

Any idea if there's much difference with the openresty version? Especially from the beta release? Nift does compile fine with normal versions of Lua as well, so it might be possible to just bundle it with either of the versions already available through brew, but also might not be a bad idea to put up the most stable beta release of LuaJIT, as it seems to be the most used when I was looking in to that a while back.

**Comment by carlocab** [comment]
Mike Pall is still developing LuaJIT, and recommends building from the tip of the v2.1 branch. See https://github.com/LuaJIT/LuaJIT/issues/665 and https://github.com/LuaJIT/LuaJIT/issues/648#issuecomment-752404043.

The OpenResty fork should be a drop-in replacement. In either case, it would be good to use either Homebrew Lua or LuaJIT in place of the bundled one.

**Comment by n-ham** [comment]
That's awesome to know about Mike Pall. The sentiment I seemed to find in places was LuaJIT is largely a dead and dying community, which seemed a huge shame given how awesome it is for embedding. I will follow what Mike suggests for his own project with the normal Nift releases and look in to bundling a version with Nift on brew. Thanks for the suggestions and info :)

**Comment by SMillerDev** [comment]
> look in to bundling a version with Nift on brew. 

This is the opposite of brews requirements outlined in https://docs.brew.sh/Acceptable-Formulae#stuff-that-requires-vendored-versions-of-homebrew-formulae

You should instead make the formula depend on a system wide Luajit managed by brew.

**Comment by n-ham** [comment]
That's what I intended to say, my apologies if it's not.

**Comment by SMillerDev** [comment]
No problem, just wanted to avoid you spending effort going in the wrong direction

**Comment by n-ham** [comment]
Any chance anyone knows of an example formula file which depends on a version of lua(jit) managed by brew? Presumably I just need to add depends on the specific version and possibly add a Makefile option to change what's being linked if needed? 

Also should I then just add a PR to the homebrew-core repo when updating the nift.rb formula file?

**Comment by carlocab** [comment]
There are many formulae that use Lua/JIT. Just `grep` the core repo for `depends_on "lua(jit(-openresty)?)?"`. You can add the changes to this PR.

**Comment by n-ham** [comment]
I haven't looked at brew yet, however put out a new release just before with an updated version of LuaJIT from their repo and it failed to build on amd64 and arm[64/hf] for snap(craft). I have reverted it back to the website version for snap and will likely do them same for the rest of the repos at some point. Should still be able to get the brew install to do what you folks are asking though.

**Pull request closed without merging**
