### PR TITLE
mariadb-connector-c 3.1.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
16:37:42 ==> brew audit mariadb-connector-c --online
16:38:24 ==> FAILED
16:38:24 ==> Installing 'bundler' gem
16:38:24 Successfully installed bundler-2.0.1
16:38:24 1 gem installed
16:38:24 Error: 1 problem in 1 formula detected
16:38:24 mariadb-connector-c:
16:38:24   * Stable: The URL https://downloads.mariadb.org/f/connector-c-3.1.1/mariadb-connector-c-3.1.1-src.tar.gz is not reachable (HTTP status code 404)
16:38:24 
16:38:24 ==> brew style mariadb-connector-c
```

image

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Server hiccups. Merging!

**Comment by chenrui333** [comment]
Thanks!

**Comment by fxcoudert** [comment]
Well, merging once we get bottles uploaded.
@BrewTestBot test this please

**Pull request closed without merging**
