### PR TITLE
notmuch: add the new (CFFI-based) python bindings named "notmuch2"

### PR DESCRIPTION
**Pull request by llange**
Since [release 0.30](https://notmuchmail.org/news/release-0.30/), notmuch has deprecated the current `notmuch` python bindings, and has replaced them with new, CFFI-based, bindings `notmuch2`.
Current `notmuch` python bindings are still supported.

This PR adds the build of the new `notmuch2` python bindings.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @llange. Can we add a test that checks that we can do `import notmuch2` with the new Python bindings? I know we don't do that with the old ones, but we probably should've.

Also, if you happen to be on an M1 Mac (I am not, unfortunately), I'd appreciate if you could test if this workaround is still needed, because I suspect it isn't anymore:

https://github.com/Homebrew/homebrew-core/blob/ac8c7d509c59ff4999892ac5744d3c7684984d8e/Formula/notmuch.rb#L62-L74

**Comment by llange** [comment]
Hi @carlocab,
Unfortunately I cannot confirm for the workaround as I'm using an old-school Intel Mac :-)

I'm looking into the tests and will update the PR accordingly.

**Comment by llange** [comment]
Hi @carlocab,
I succeeded in adding tests for previous bindings (and updated the patch accordingly), but unfortunately I'm not completely able to do it for the new ones.

What we have is a test-time dependency on an external python package ("cffi") (Which, itself, depends on another Formula - "libffi").

I could try to make the whole notmuch formula depending on this python package ("cffi") but I'm not sure it's the good approach.

Here is the patch if you want to have a look at it:
```diff
@ Formula/notmuch.rb:32 @ class Notmuch < Formula
   depends_on "python@3.9"
   depends_on "talloc"
   depends_on "xapian"
+  depends_on "libffi" => :test
 
   uses_from_macos "zlib", since: :sierra
 
@ Formula/notmuch.rb:97 @ class Notmuch < Formula
       db.close()
     EOS
     assert_match "#{testpath}/Mail", shell_output("#{Formula["python@3.9"].opt_bin}/python3 '#{testpath}/test-bindings-v1.py'")
+
+    (testpath/"test-bindings-v2.py").write <<~EOS
+      import notmuch2
+      db = notmuch2.Database(mode=notmuch2.Database.MODE.READ_ONLY)
+      print(db.path)
+      db.close()
+    EOS
+    assert_match "#{testpath}/Mail", shell_output("#{Formula["python@3.9"].opt_bin}/python3 '#{testpath}/test-bindings-v2.py'")
   end
 end
```

which fails with the expected missing package:
```
==> /usr/local/opt/python@3.9/bin/python3 '/private/tmp/notmuch-test-20210725-78647-1va36x4/test-bindings-v2.py'
Traceback (most recent call last):
  File "/private/tmp/notmuch-test-20210725-78647-1va36x4/test-bindings-v2.py", line 1, in <module>
    import notmuch2
  File "/usr/local/Cellar/notmuch/0.32.2/lib/python3.9/site-packages/notmuch2/__init__.py", line 45, in <module>
    from notmuch2 import _capi
ModuleNotFoundError: No module named '_cffi_backend'
```

My idea would be to have a test-time virtualenv created for it - I'd pip-install the external dependency in the virtualenv and run the test.

Before rushing into it, I prefer to ask if there are some guidelines I could use:
* Is it better to make the whole notmuch formula depending on this python package ("cffi") ? It would be a resource.
* Or a test-time dependency only, with a virtualenv at test-time ?

Let me know.

**Comment by carlocab** [comment]
This is a tough one. On the one hand, it seems difficult to install the bindings yourself if the formula doesn't. On the other, we also want to make this work out-of-the-box such that users can just do `import notmuch2` in Python without having to do any extra setup.

I don't think we need the `libffi` dependency, though. The `cffi` module should work just fine with the system-provided one, AFAIK.

**Comment by llange** [comment]
Hi @carlocab,
Thanks for your insights.

I updated the patch accordingly:
* Depending on system `libffi`
* Installing `cffi` python package alongside the `notmuch2` (and also `notmuch`) python bindings
* Adding the `notmuch2` python bindings tests

Now the tests are working as expected:
```shell
==> Testing notmuch
==> /usr/local/Cellar/notmuch/0.32.2/bin/notmuch new
==> /usr/local/opt/python@3.9/bin/python3 '/private/tmp/notmuch-test-20210805-94079-1cshx8f/test-bindings-v1.py'
==> /usr/local/opt/python@3.9/bin/python3 '/private/tmp/notmuch-test-20210805-94079-1cshx8f/test-bindings-v2.py'
```

It seems that installing `cffi` to site-packages (i.e. a dependency, not provided by notmuch formula) may be something particular as I was not able to quickly find another formula doing the same (but then, I only search on homebrew-core).
=> Do you think we should update the formula with a specific note about it ?

**Comment by carlocab** [comment]
Installing `cffi` into the prefix also has its own problems:

1. I think it also has a `pycparser` dependency.
2. This would cause problems for users with their own `cffi` installations.

This is why nearly all other formulae install Python resources into `libexec`.

I actually meant to write this in my previous comment, but it slipped my mind when I got around to responding 😅

**Comment by llange** [comment]
I understand what you mean but I don't see how libexec would prevent that.

According to [the official doc I'm trying to follow](https://docs.brew.sh/Python-for-Formula-Authors#installing-1), after installation in libexec (or libexec/vendor), a ".pth" file is then dropped into the prefix site-packages...
So, to me, it looks like the same thing :
* It would also "conflict" with any user-installed CFFI
* It would have the issue you mentionned with `pycparser` (which is not impacting me when running the `notmuch2` library nor the `brew test notmuch`)

Obviously I need more details :-)

**Comment by carlocab** [comment]
You're right about using `.pth` files; we're trying to avoid using those since #73875. The docs should probably be updated to reflect this. This is also why I didn't suggest its use.

I'm not really sure we have any good alternatives here, which is why I said that this was tough.

**Pull request closed without merging**
