### PR TITLE
rust 1.40.0

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by samford** [comment]
The previous failure was due to this being one of the two tasks being run (and cancelled) before CI was restarted, so it'll need to run again.

@BrewTestBot test this please

**Comment by samford** [comment]
Looks like tests are failing for gleam, tectonic, and texlab. I’ll look into this when I get a chance later today, if no one gets to it first.

**Comment by fxcoudert** [comment]
We've seen those test failures now and then before. Given the sorry state of our CI at the moment, I'm gonna merge this anyway, but please investigate the test failures when you get the time.

**Comment by samford** [comment]
# Gleam

The Gleam test failed when I tested it locally (macOS 10.15.2) using the current formula (v0.4.2).  The test worked fine on the 0.5.0 release when I built it from source using Rust 1.40.0, so it should be resolved in #48021.  I left a comment in that PR on how to resolve the build error that occurred.


# Tectonic

The Tectonic test seemingly failed because it either couldn't access a URL or received a response it didn't like:

```
        Testing tectonic
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191221-32568-1qef48w.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tectonic.rb --verbose
==> /usr/local/Cellar/tectonic/0.1.11_3/bin/tectonic -o /private/tmp/tectonic-test-20191221-32569-ha401n --format plain /private/tmp/tectonic-test-20191221-32569-ha401n/test.tex
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
note: indexing https://archive.org/services/purl/net/pkgwpub/tectonic-default
error: could not get backend summary digest
caused by: couldn't probe https://archive.org/services/purl/net/pkgwpub/tectonic-default
caused by: Invalid Status provided
Error: tectonic: failed
```

The test ran fine when I built Tectonic from source using Rust 1.40.0, so it may be a fluke or something related to the CI environment.  For what it's worth, the response from that URL is as follows:

```
HTTP/1.1 302 FOUND
Server: nginx/1.14.0 (Ubuntu)
Date: Sat, 21 Dec 2019 22:25:15 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 226
Connection: keep-alive
Location: https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=15724800
```

I'm going to run the test on the 0.1.12 PR (#47633) and see if it encounters the error again.  0.1.12 also builds and tests fine with Rust 1.40.0 locally.  It may be that the test will have to be reworked to something more dependable.

# Texlab

I built texlab (v1.8.0) from source and it tested fine locally, so I can't say why it failed this time.  The error is as follows:

```
       Testing texlab
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191221-30525-mcc8oo.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/texlab.rb --verbose
Error: texlab: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Content\-Length:\ 543/> was expected to be =~
<"Tectonic 0.1.11\n">
```

**Pull request closed without merging**
