### PR TITLE
balena-cli 11.18.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chrmoritz** [comment]
Looks like the native addon dependency `ext2fs` isn't compatible with `node` 13 yet and it was not discovered during the `node` 13 PR, because the test of `balena-cli` doesn't cover that functionality.

**Comment by chenrui333** [comment]
Good to know!!

**Comment by chenrui333** [comment]
@chrmoritz, what is the recommended approach on this?

**Comment by chrmoritz** [comment]
The fix is quite trivial, I'm trying to submit it upstream, but we could either move this formula to `node@12` or apply the patch here too:

```diff
diff --git a/src/node_ext2fs.cc b/src/node_ext2fs.cc
index 2c59f8b..efd60cf 100644
--- a/src/node_ext2fs.cc
+++ b/src/node_ext2fs.cc
@@ -679,7 +679,8 @@ class ReadDirWorker : public AsyncWorker {
                        }
                        v8::Local<v8::Array> result = Nan::New<v8::Array>();
                        for(auto const& filename: filenames) {
-                               result->Set(
+                               Nan::Set(
+                                       result,
                                        result->Length(),
                                        Nan::CopyBuffer(
                                                filename.c_str(),
```

**Comment by Bo98** [comment]
I'd probably suggest making it depend on `node@12` until the patch is accepted upstream. At that point we can bring that in.

**Comment by chrmoritz** [comment]
@Bo98 I agree, because `ext2fs` is not a top level dependency of `balena-cli` and nested somewhere down the dependency tree, making the patching non trivial.

But we need in addition to changing the dependency to `node@12` to also change `bin.install_symlink Dir["#{libexec}/bin/*"]` to something writing wrapper scripts to to keg-only `node@12` executable.

**Comment by chrmoritz** [comment]
@chenrui333 

```diff
diff --git a/Formula/balena-cli.rb b/Formula/balena-cli.rb
index c4c6dde472..814475590e 100644
--- a/Formula/balena-cli.rb
+++ b/Formula/balena-cli.rb
@@ -13,10 +13,11 @@ class BalenaCli < Formula
     sha256 "bfac0f117924bf61f81b8d212c8731bc144b429a5bfa97674a4044b6bb6d02bb" => :high_sierra
   end
 
-  depends_on "node"
+  depends_on "node@12"
 
   def install
     system "npm", "install", *Language::Node.std_npm_install_args(libexec)
+    inreplace libexec/"bin/balena", "#!/usr/bin/env node", "#!#{Formula["node@10"].opt_bin}/node"
     bin.install_symlink Dir["#{libexec}/bin/*"]
   end
 
```

**Comment by chenrui333** [comment]
doing that now.

**Comment by chenrui333** [comment]
looks like permission issue

20526 verbose argv "/usr/local/Cellar/node@12/12.13.1/bin/node" "/usr/local/opt/node/libexec/bin/npm" "install" "-ddd" "--global" "--build-from-source" "--cache=/Users/ruichen/Library/Caches/Homebrew/npm_cache" "--prefix=/usr/local/Cellar/balena-cli/11.18.3/libexec" "/private/tmp/balena-cli-20191122-2839-bvmfqi/package/balena-cli-11.18.3.tgz"
20527 verbose node v12.13.1
20528 verbose npm  v6.12.1
20529 error code EPERM
20530 error syscall spawn
20531 error errno EPERM
20532 error Error: spawn EPERM
20532 error     at ChildProcess.spawn (internal/child_process.js:394:11)
20532 error     at Object.spawn (child_process.js:540:9)
20532 error     at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24
20532 error     at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
20532 error     at runMicrotasks (<anonymous>)
20532 error     at processTicksAndRejections (internal/process/task_queues.js:93:5)
20532 error  OperationalError: spawn EPERM
20532 error     at ChildProcess.spawn (internal/child_process.js:394:11)
20532 error     at Object.spawn (child_process.js:540:9)
20532 error     at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24
20532 error     at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
20532 error     at runMicrotasks (<anonymous>)
20532 error     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
20532 error   cause: Error: spawn EPERM
20532 error       at ChildProcess.spawn (internal/child_process.js:394:11)
20532 error       at Object.spawn (child_process.js:540:9)
20532 error       at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24
20532 error       at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
20532 error       at runMicrotasks (<anonymous>)
20532 error       at processTicksAndRejections (internal/process/task_queues.js:93:5) {
20532 error     errno: 'EPERM',
20532 error     code: 'EPERM',
20532 error     syscall: 'spawn'
20532 error   },
20532 error   stack: 'Error: spawn EPERM\n' +
20532 error     '    at ChildProcess.spawn (internal/child_process.js:394:11)\n' +
20532 error     '    at Object.spawn (child_process.js:540:9)\n' +
20532 error     '    at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24\n' +
20532 error     '    at /usr/local/Cellar/node/13.1.0/libexec/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24\n' +
20532 error     '    at runMicrotasks (<anonymous>)\n' +
20532 error     '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
20532 error   errno: 'EPERM',
20532 error   code: 'EPERM',
20532 error   syscall: 'spawn',
20532 error   parent: 'balena-cli'
20532 error }
20533 error The operation was rejected by your operating system.
20533 error It is likely you do not have the permissions to access this file as the current user
20533 error

**Comment by Bo98** [comment]
Looks like it's mixing up which node to use in the install process.

I suspect it might be a shortcoming of `Language::Node.std_npm_install_args`.

**Comment by chenrui333** [comment]
rebased to latest master and build with latest release, still failed locally.

```
==> Downloading https://registry.npmjs.org/balena-cli/-/balena-cli-11.20.2.tgz
######################################################################## 100.0%
==> npm install -ddd --global --build-from-source --cache=/Users/ruichen/Library/Caches/Homebrew/npm_cache --p
Last 15 lines from /Users/ruichen/Library/Logs/Homebrew/balena-cli/01.npm:
npm verb argv "/usr/local/Cellar/node/13.5.0/bin/node" "/usr/local/opt/node/libexec/bin/npm" "install" "-ddd" "--global" "--build-from-source" "--cache=/Users/ruichen/Library/Caches/Homebrew/npm_cache" "--prefix=/usr/local/Cellar/balena-cli/11.20.2/libexec" "/private/tmp/balena-cli-20191222-91554-i35asu/package/balena-cli-11.20.2.tgz"
npm verb node v13.5.0
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ext2fs@1.0.29 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ext2fs@1.0.29 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 87666ms
```

**Comment by chrmoritz** [comment]
@chenrui333: This should work with the latest v11.20.2. Could you update this PR to use that version instead?

**Comment by chrmoritz** [comment]
Can confirm that this works for me:

```diff
diff --git a/Formula/balena-cli.rb b/Formula/balena-cli.rb
index c4c6dde472..60aebab505 100644
--- a/Formula/balena-cli.rb
+++ b/Formula/balena-cli.rb
@@ -4,8 +4,8 @@ class BalenaCli < Formula
   desc "The official balena CLI tool"
   homepage "https://www.balena.io/docs/reference/cli/"
   # Frequent upstream releases, do not update more than once a week
-  url "https://registry.npmjs.org/balena-cli/-/balena-cli-11.18.0.tgz"
-  sha256 "39890bd18d6649ce041f477c22b8561027bdac70f0de7885d79709b9cb4875e7"
+  url "https://registry.npmjs.org/balena-cli/-/balena-cli-11.20.2.tgz"
+  sha256 "a78f84c3d343f274d3e51fed1f06656e7cfe557dbe22f9af78871c94f6c1040b"
 
   bottle do
     sha256 "0a5dcaf03c6e45854662631da360f55ca55b16f34341ac4ea1e024f2e0a79f19" => :catalina
@@ -16,6 +16,7 @@ class BalenaCli < Formula
   depends_on "node"
 
   def install
+    rm "npm-shrinkwrap.json" # fix node 13 compatibility
     system "npm", "install", *Language::Node.std_npm_install_args(libexec)
     bin.install_symlink Dir["#{libexec}/bin/*"]
   end
```

**Comment by chenrui333** [comment]
Thanks @chrmoritz for moving this forward!!

**Pull request closed without merging**
