### PR TITLE
jpeg-xl 0.3.5

### PR DESCRIPTION
**Pull request by NeRdTheNed**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @NeRdTheNed. Did you check if the `resource` blocks need updating?

Previous attempt: #73296

**Comment by NeRdTheNed** [comment]
> Thanks for your PR, @NeRdTheNed. Did you check if the `resource` blocks need updating?
> 
> Previous attempt: #73296

Sorry, this is the first time I've done this! I'll take a look.

**Comment by carlocab** [comment]
Actually, I had a look myself and they don't need updating. However, the build still fails, unfortunately. This might need to be reported upstream to be fixed.

**Comment by NeRdTheNed** [comment]
> Actually, I had a look myself and they don't need updating. However, the build still fails, unfortunately. This might need to be reported upstream to be fixed.

No problems, I'll ask about it on the JPEG-XL discord. Thanks for looking into it!

**Comment by carlocab** [comment]
Great, thanks for getting on that. It seems the build fails starting with these errors:
```
/tmp/jpeg-xl-20210324-62707-7huyw6/jpeg-xl-v0.3.5/lib/extras/codec_exr.cc:93:12: error: virtual function 'tellg' has a different return type ('uint64_t' (aka 'unsigned long long')) than the function it overrides (which has return type 'Imath_2_5::Int64' (aka 'unsigned long'))
  uint64_t tellg() override { return pos_; }
  ~~~~~~~~ ^
/usr/local/Cellar/openexr/2.5.5/include/OpenEXR/ImfIO.h:117:19: note: overridden virtual function is here
    virtual Int64       tellg () = 0;
            ~~~~~       ^
/tmp/jpeg-xl-20210324-62707-7huyw6/jpeg-xl-v0.3.5/lib/extras/codec_exr.cc:94:34: error: non-virtual member function marked 'override' hides virtual member function
  void seekg(const uint64_t pos) override {
                                 ^
```

**Comment by NeRdTheNed** [comment]
> Great, thanks for getting on that. It seems the build fails starting with these errors:
> 
> ```
> /tmp/jpeg-xl-20210324-62707-7huyw6/jpeg-xl-v0.3.5/lib/extras/codec_exr.cc:93:12: error: virtual function 'tellg' has a different return type ('uint64_t' (aka 'unsigned long long')) than the function it overrides (which has return type 'Imath_2_5::Int64' (aka 'unsigned long'))
>   uint64_t tellg() override { return pos_; }
>   ~~~~~~~~ ^
> /usr/local/Cellar/openexr/2.5.5/include/OpenEXR/ImfIO.h:117:19: note: overridden virtual function is here
>     virtual Int64       tellg () = 0;
>             ~~~~~       ^
> /tmp/jpeg-xl-20210324-62707-7huyw6/jpeg-xl-v0.3.5/lib/extras/codec_exr.cc:94:34: error: non-virtual member function marked 'override' hides virtual member function
>   void seekg(const uint64_t pos) override {
>                                  ^
> ```

It looks like there might have been issues with OpenEXR integration in v0.3.4, I'm placing my bets on [this change](https://gitlab.com/wg1/jpeg-xl/-/commit/f2aeba7e3d091314eaccb64748791e1f4e2cf0a6#0442ba75b1c9e65970a8c225708b9e10fee0631b) being the specific one that "broke" the build.

**Comment by NeRdTheNed** [comment]
Hey @carlocab, it looks like some changes were pushed to the JPEG-XL repository which might be related to this issue. As I'm unsure how to properly rebase this PR through brew bump-formula-pr, I'll close this PR and use brew bump-formula-pr to create a new one.

**Pull request closed without merging**
