### PR TITLE
sollya v7.0 (new formula)

### PR DESCRIPTION
**Pull request by radford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This formula requires `fplll` which has been submitted as its own PR #53515 .

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please make one commit per pull request

**Comment by radford** [comment]
@SMillerDev, there will be one commit in this PR once/if #53515 gets merged as this is based on the commit there.  If you think there should only be one PR with both formula, then I'd be happy to squash the commits in this PR and close #53515 .

**Comment by SMillerDev** [comment]
No, I think this pr should only contain one formula.

**Comment by chenrui333** [comment]
@radford now with fplll formula merged, can you make this PR just for sollya? Thanks!

**Comment by radford** [comment]
@chenrui333, I have rebased now that `fplll` has been merged.  Thanks!

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@radford, thanks a lot!! Merging this formula now.

**Comment by chenrui333** [comment]
@radford Thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
