### PR TITLE
restic 0.9.2

### PR DESCRIPTION
**Pull request by sonicdoe**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @sonicdoe

**Comment by b-long** [comment]
@fxcoudert Just curious, why is it the bottle section (specifically the SHA256 sums) is not updated in this scenario?

**Comment by fxcoudert** [comment]
The bottle section is updated in a separate commit (https://github.com/Homebrew/homebrew-core/commit/3fe8fd942346934322d94a6c6f00acf4e9576c8e) pushed at the same time.

**Pull request closed without merging**
