### PR TITLE
sbt 1.0.0 + sbt@0.13 0.13.16 (new formula)

### PR DESCRIPTION
**Pull request by eed3si9n**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR bumps "sbt" formula to sbt 1.0.0, and saves the older stable sbt 0.13 as "sbt@0.13".

### CODE REVIEW

**Comment by ilovezfs** [comment]
Will the next API breaking release be 2 or 1.1? (wondering whether the versioned alias should be @1 or @1.0?)

**Comment by eed3si9n** [comment]
> Will the next API breaking release be 2 or 1.1? (wondering whether the versioned alias should be @1 or @1.0?)

Next breaking will be 2. We are adopting SemVer.

**Comment by ilovezfs** [comment]
Thanks!

**Comment by eed3si9n** [comment]
Thanks for merging! :)

**Comment by DomT4** [comment]
This is lacking a `keg_only :versioned_formula` no?

**Comment by eed3si9n** [comment]
I don't know what `keg_only :versioned_formula` do. Both the formulae install `sbt`.

**Comment by DomT4** [comment]
Was mostly a question for @ilovezfs given he merged this as-is & if anything me and him only ever go back & forth over who wants to be more pedantic than the other 😄.

**Comment by eed3si9n** [comment]
ok. Please carry on then :) Thank you both for the all the maintenance.

**Comment by ilovezfs** [comment]
done https://github.com/Homebrew/homebrew-core/pull/16653

**Pull request merged**
