### PR TITLE
libxmlb 0.3.13 (new formula)

### PR DESCRIPTION
**Pull request by hughsie**
This is needed as one of the two deps required by fwupd, which has 52 stars, 370 forks and 2300 stars on GitHub.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by hughsie** [comment]
This is also my first time submitting a package into brew, and also my first time "using" ruby, so please be gentle :)

**Comment by hughsie** [comment]
If it helps, my working document for this task is https://docs.google.com/document/d/1qt7lUbAE24RFsBbZwdWH27Ffq4khLpZoJZ5Tljf79X8/edit?usp=sharing

**Review by chenrui333 — APPROVED** [review]
LGTM

**Comment by chenrui333** [comment]
@hughsie thanks a lot for your first PR contribution to homebrew-core. 🎉

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
