### PR TITLE
Use Ruby 1.9+ symbol hash keys in all formulae.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

@DomT4 requested we do this en-masse after doing it in Homebrew/brew.

Skipping CI because it's lol too many.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I assume this will not ship until it's :green_apple: right?

**Comment by MikeMcQuaid** [comment]
@ilovezfs It was cancelled because there was too many formulae. I trust Rubocop's `--auto-correct` and `brew readall` confirms these look good.

**Comment by ilovezfs** [comment]
I was hoping for 977 new Sierra bottles. /s

**Comment by UniqMartin** [comment]
I think stuff like `depends_on python3: :optional` (previously `depends_on :python3 => :optional`) reads horrible. It also breaks the symmetry with when it's not optional, where one still has to write `depends_on :python3`. The same problem arises with every special (symbol) dependency we have. I expect some confusion among contributors (particularly those not very familiar with Ruby) and the docs might need to be updated for this (if they haven't been yet).

Maybe there's are more such gems in this automated conversion, but I'm obviously not going to review 977 changed files for a change that has already been merged …

**Comment by MikeMcQuaid** [comment]
@UniqMartin It may not read that nicely but I think the consistency trumps it, personally.

**Comment by dunn** [comment]
> I think stuff like depends_on python3: :optional (previously depends_on :python3 => :optional) reads horrible.

Agree, but that's a problem with Ruby in general.

**Pull request merged**
