### PR TITLE
moto 2.2.17

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
ERROR: Some build dependencies for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/22/fa/ac431f0571bd84d8da5b55d9c9a00d510ae8682324405eabd96a752d090c/setuptools-rust-1.0.0.tar.gz#sha256=eb6e6d41f01e63d042288e5c609684adf93426c10ea745ec324263f3fcbf27e9 conflict with the backend dependencies: setuptools_scm==6.0.1 is incompatible with setuptools_scm>=6.3.2.

**Comment by chenrui333** [comment]
- relates to pyca/cryptography#6671

**Comment by alex** [comment]
The latest setuptools-rust release hopefully ameliorates this issue.

**Comment by chenrui333** [comment]
Let's give a shot.

**Comment by cclauss** [comment]
Nice!

**Review by SMillerDev — DISMISSED** [review]

**Comment by cclauss** [comment]
Approved, ready to merge, and stale.  What is the todo on this one?

**Pull request closed without merging**
