### PR TITLE
youtube-dl 2019.09.12.1

### PR DESCRIPTION
**Pull request by vitorgalvao**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vitorgalvao** [comment]
The formula causing the tests to fail is `mps-youtube`, not this one.

Youtube broke `youtube-dl` today (this update fixes it), so we might be seeing a few duplicate PRs while this isn’t merged.

**Comment by fxcoudert** [comment]
We need to use this as an opportunity to fix the `mps-youtube` failure, given the formula is related to `youtube-dl`.

**Comment by vitorgalvao** [comment]
> We need to use this as an opportunity to fix the `mps-youtube` failure, given the formula is related to `youtube-dl`.

I’m bound to be misunderstand the feature, but don’t [lines 26–29](https://github.com/Homebrew/homebrew-core/blob/ffc0c99aba5add4a273c9cb7fa4be1c8c8bc0140/Formula/mps-youtube.rb#L26L29) indicate `mps-youtube`’s `youtube-dl` dependency is taken from somewhere else, and is thus not dependent on this particular formula, meaning it shouldn’t even be affected by it and could be fixed in a different PR?

**Comment by fxcoudert** [comment]
`mps-youtube` depends on `mpv`, which in turn depends on `youtube-dl`. Our policy is that when updating a given formula (here `youtube-dl`) all others than depend on it are tested (in this case, `mpv` and `mps-youtube`). We should use this opportunity to fix the bug that is exposed, even if it is a preexisting issue, rather than ignore it.

**Comment by vitorgalvao** [comment]
> `mps-youtube` depends on `mpv`, which in turn depends on `youtube-dl`.

Ah, that’s it.

I’ve fixed `mps-youtube`, though I can’t test locally due to broken `audit` and `style` commands. Will have to wait for CI to confirm if it’s OK (I don’t see why not).

**Comment by vitorgalvao** [comment]
But if this depends on `mpv` which depends on `youtube-dl`, then why is the `resource` block even needed? `youtube-dl` is possibly the worst script to keep locked to a specific version in any formula.

**Comment by fxcoudert** [comment]
> But if this depends on mpv which depends on youtube-dl, then why is the resource block even needed?

Can you try to add an explicit `youtube-dl` dependency to `mps-youtube`, and remove the resource, see if it works? I agree it would be better.

**Comment by teddywing** [comment]
> But if this depends on mpv which depends on youtube-dl, then why is the resource block even needed?

Looks like the `resource` block enabled `youtube-dl` to be installed into `mps-youtube`'s virtualenv. Since the `youtube-dl` Homebrew formula gets installed outside of `mps-youtube`'s Homebrew virtualenv, `mps-youtube` complains that it can't find the module:

```
Running command python setup.py egg_info
Traceback (most recent call last):
  File "/private/tmp/pip-req-build-qoxiscjd/pafy/pafy.py", line 48, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/pip-req-build-qoxiscjd/setup.py", line 13, in <module>
    from pafy import __version__
  File "/private/tmp/pip-req-build-qoxiscjd/pafy/__init__.py", line 7, in <module>
    from .pafy import new
  File "/private/tmp/pip-req-build-qoxiscjd/pafy/pafy.py", line 52, in <module>
    "pafy: youtube-dl not found; you can use the internal backend by "
ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.
```
(https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/48357/version=sierra/testReport/junit/brew-test-bot/sierra/install___build_bottle_mps_youtube/)

The `youtube-dl` dependency comes from `pafy`: https://github.com/mps-youtube/pafy/blob/9eecd423bf2025d1c34506c2a076ddd8043cd3d3/setup.py#L26-L28

**Comment by vitorgalvao** [comment]
Build is passing now.

**Pull request closed without merging**
