### PR TITLE
ipcalc 0.51

### PR DESCRIPTION
**Pull request by rnsc**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by rnsc** [comment]
I used `brew bump-formula-pr`, however, I probably should update the livecheck too right?

**Comment by chenrui333** [comment]
> I used `brew bump-formula-pr`, however, I probably should update the livecheck too right?

yeah, you are right, we dont need `livecheck` block anymore, the default one works well for github artifact.

**Review by carlocab — APPROVED** [review]

**Comment by rnsc** [comment]
@carlocab @chenrui333 is it normal that the PR was closed?

**Comment by carlocab** [comment]
Yes. This PR was merged in https://github.com/Homebrew/homebrew-core/commit/fa03bdcc24187fff1606b80040d6b52eff0348ca.

**Pull request closed without merging**
