### PR TITLE
x265 enabled HDR10+

### PR DESCRIPTION
**Pull request by mrasmussen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Enabled HDR10+ to be able to use it with FFMPEG

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like setting this flag turns off building the shared library, which is causing many dependent formulae to fail.

**Comment by mrasmussen** [comment]
I have removed the -DENABLE_HDR10_PLUS=ON from the 8bit build.  This has resolved the issue of the shared libraries not building while still enabling HDR10+.

**Comment by jonchang** [comment]
Looks good! One last thing: if all of our users need to be updated to this, then please add `revision 1` to the formula. (I assume this is the case but I wanted to check beforehand)

**Comment by mrasmussen** [comment]
> Looks good! One last thing: if all of our users need to be updated to this, then please add `revision 1` to the formula. (I assume this is the case but I wanted to check beforehand)

@johnchang Thank you for your help!  This is my first time contributing and I wasn't sure of all the steps needed. :) I have added revision 1 to the formula

**Comment by mrasmussen** [comment]
I put the revision in the wrong place, fixed.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @mrasmussen  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
