### PR TITLE
libxml2: add readline history support

### PR DESCRIPTION
**Pull request by MindTooth**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

## Rational

As an assignment this week, we are dealing with XPath.  Having tried a quite few apps, I've landed on `xmllint`.  However, I became irritated with writing the same query over and over.  To my fortune, the `libxml2` has a configure flag (`--with-history`) that enables the support for readline history when using `xmllint --shell`.

I've tested it some, and it behaves just as a readline app.  No issue so far.

## Formula

If accepted, do I need to bump the revision, and should I add `readline` as a dependency?

### CODE REVIEW

**Comment by zbeekman** [comment]
> should I add `readline` as a dependency?

If you still have it installed and built from source on your system (using homebrew) then we probably don't need a readline dependency. To double check this you could run `brew linkage libxml2` and see if it picks up anything suspicious.

> do I need to bump the revision

A *LOT* of stuff depends on libxml2 so I'm tempted to *NOT* bump the revision. This means users won't get to enjoy the benefits of the completion enhancement until libxml2 is next rebottled.

**Comment by MindTooth** [comment]
```
❯ brew linkage libxml2
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/Cellar/libxml2/2.9.9_2/lib/libxml2.2.dylib (libxml2)
  /usr/local/opt/readline/lib/libhistory.8.dylib (readline)
  /usr/local/opt/readline/lib/libreadline.8.dylib (readline)
Indirect dependencies with linkage:
  readline
```

Does that mean I should add it?

**Comment by zbeekman** [comment]
> Does that mean I should add it?

Yes, please add `readline` as a dependency. Also, please make sure to run `brew audit --strict` again before pusing. And if possible, please squash any new commits.

**Review by zbeekman — CHANGES_REQUESTED** [review]
Needs `depends_on "readline"` below `depends_on "python"`.

**Comment by MindTooth** [comment]
Done.  Waiting build.

**Pull request closed without merging**
