### PR TITLE
ruby 3.1.3

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /private/tmp/ruby-20221124-55694-1qmecln/ruby-3.1.3/lib/rubygems/ext/builder.rb:102:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)
```

**Comment by p-linnane** [comment]
For reference, this built fine for me locally on `13-arm64`.

**Comment by Bo98** [comment]
This might be an upstream bug (MacPorts also had issues with native gems on 3.1.3), but I'm still tracking down what the issue is.

**Comment by Bo98** [comment]
Ok, I've tracked this one down to a brew bug: https://github.com/Homebrew/brew/pull/14189

**Comment by Bo98** [comment]
I'd say this requires a new brew release with that fix before this is merged, particularly given Ruby is not a relocatable bottle.

**Comment by p-linnane** [comment]
`cucumber-cpp` is failing on `13-arm64`:
```
==> /private/tmp/cucumber-cpp-test-20221204-27379-dtsuf9/bin/cucumber --publish-quiet
Unable to contact the wire server at localhost:3902. Is it up? (Cucumber::Wire::Connection::ConnectionError)
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
I think we can followup later with `cucumber-cpp` test failure

**Comment by p-linnane** [comment]
Sounds good. I will merge this after the next `brew` release.

**Comment by XuehaiPan** [comment]
`brew` 3.6.14 is released.

---

PS: Unfortunately, tt still fails to build from source on Ubuntu pre-22.04 (#110558) with Homebrew/brew#14189.

- #110558
- Homebrew/brew#14189

**Pull request closed without merging**
