### PR TITLE
youtube-dl 2018.09.08

### PR DESCRIPTION
**Pull request by aphex3k**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by aphex3k** [comment]
mps-youtube is installing a long outdated version of youtube-dl and should not block testing of its updated dependency!

**Comment by javian** [comment]
`pafy` seems to have no explicit version dependency on `youtube_dl` so it should be safe to submit a pr to update `mps-youtube` - would you mind helping out with that @aphex3k ?

**Comment by aphex3k** [comment]
How can I create a PR for a package that is depending on this PR not having been merged?

**Comment by javian** [comment]
Sorry, `pafy` is a resource used in the `mps-youtube` formula which had the "old" youtube-dl dep. The `mps-youtube` formula is the one that needs updating.

**Comment by aphex3k** [comment]
@javian It looks I was able to resolve it for everything but mohave.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/24163bfe742d0d79e2946b0950a2f887b310798f & https://github.com/Homebrew/homebrew-core/commit/3b7113afa492c25be211df0f13399597d4929bcf. Thank you for your contributions to Homebrew @aphex3k; we appreciate them! :smiley_cat:

**Pull request closed without merging**
