### PR TITLE
mono: add msbuild tool

### PR DESCRIPTION
**Pull request by fabriciomurta**
This adds the msbuild tool to mono, following as close as possible to
what is distributed in mono-project.com's 5.4.1.6 release for mac os x.

It uses the msbuild project from mono -- which is a fork from microsoft's
and the git repo used to put together the msbuild version that is shipped
from mono-project.com.

Because it bootstraps with the dotnet client, the formula needs to include
both openssl and curl kegs and wrap the dotnet cli in-place, so that the
tool runs using homebrew versions of libcurl and libcrypto. At least from
recent OSX versions, native libcurl breaks the dotnet client when linked
against homebrew's openssl.

Additionally, it is not possible to just set the library search path due
to OSX's default SIP (system integrity protection, details in formula
comments), so the dotnet cli wrapper was the only solution I could think
of that would work on every system.

The patches present in the formula then are specific for homebrew and are
not generic nor OSX-specific.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)? _it passes `brew audit --strict --online mono`_

-----
First I tried to make this over a separate formula but it imposes installing files within mono library folders, much like the fortran support, so there was not much choice but bundle it with mono itself. Anyway, this tool is not useful without mono and mono will become pretty much deprecated without this tool, as `xbuild` is being deprecated since mono 5.0.

Install Notice: I'm not 100% sure, but I believe the original mono package from mono-project.com, if installed, places the `msbuild` tool man page in the same place homebrew would symlink, so installation's `brew link` would fail in such cases. Following mono instructions to uninstall it does not include uninstalling/removing the man page. :)

### CODE REVIEW

**Comment by fabriciomurta** [comment]
This does not bump the package version as it just adds the msbuild tool. mono version bump recently happened from #21405.

**Comment by ilovezfs** [comment]
This has the same complications that https://github.com/Homebrew/homebrew-core/pull/17435 and https://github.com/Homebrew/homebrew-core/pull/17378 did. Ultimately, it's an upstream issue and not something we can address in a formula. They'll need to provide some sane way of building msbuild along the lines of `./configure && make install` or we're not going to be able to package it in Homebrew.

**Comment by fabriciomurta** [comment]
got it! anyway, it was a good experience to crack those issues. I'll switching to use the mono package and drop brew support... or I could just let it sit in a tap.

**Comment by ilovezfs** [comment]
@fabriciomurta If I understand the issue, you're saying the msbuild binary that gets downloaded is itself _already_ broken until you force it to use Homebrew's openssl and curl?

**Comment by ilovezfs** [comment]
s/msbuild/dotnet/

**Comment by fabriciomurta** [comment]
yes and no (`dotnet` is and is not broken)
The problem is detailed here: dotnet/core-setup#2649. And the only way to trick OSX into using homebrew kegged libraries (so that libcurl uses openssl and not libressl), without disabling SIP seems to be "wrapping" it to look first at brew's paths.

The "patch" is not in msbuild actually. It is just in that tool. I don't really see mono patching `msbuild`, but I'm not sure how they guarantee in their CI that dotnet runs under the right libraries. Probably their CI didn't upgrade to high sierra yet.

**Comment by fabriciomurta** [comment]
Oh, and without `msbuild`, I don't expect any future fsharp version after 4.1.23 to be available to homebrew, as they dropped `xbuild` support. Current OSX stable/release packaged mono is shipped with 4.1.25.
The project I work with will also probably drop xbuild support soon, as msbuild tasks are handled nicely (while been pretty much broken with xbuild).

**Comment by ilovezfs** [comment]
@fabriciomurta OK, so the problem is that they're not including the appropriate openssl and curl with dotnet, even though macOS itself isn't providing them. That is a pretty strange state of affairs since they _should_ be including the requisite libraries linked statically or dynamically along with the binary not pretending the system is going to provide them. If it's possible to specify the locations (by passing it to configure not by patching) of openssl and curl during the build of `dotnet` itself in a dotnet formula that might be a way to address this.

**Comment by fabriciomurta** [comment]
Yes, well, seems that recent osx updates "broke" the dotnet client, so at least as far as I could find, forcing it to use homebrew versions of the libraries address the issue. I don't think that would be something they'd patch in their side. Mono does not even use the dotnet client. It is only used cause the msbuild project comes from microsoft (mono's a fork from microsoft/msbuild).

I still think the patch applied is very specific to enforce the install in homebrew environment and could be seen not as a fix to the installed package itself, but an instruction for its tool to rely on homebrew during installation. The openssl and libcurl dependencies will not be necessary at run time, for example.

**Comment by fabriciomurta** [comment]
for who may interest I'm hosting this formula under my tap at `fabriciomurta/bridge/mono`. Shipping mono 5.4.1.6 + fsharp 4.1.25 + msbuild 5.4, in sync with current mono-develop.com OSX package's (5.4.1.6, stable) versions and github branch revisions.

**Pull request closed without merging**
