### PR TITLE
joplin 1.0.135

### PR DESCRIPTION
**Pull request by chrmoritz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/joplin/1.0.127/bin/joplin config editor subl
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module '../locales/index.js'
Require stack:
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/locale.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/logger.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/database.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/BaseModel.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/models/Note.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/reducer.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/BaseApplication.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/app.js
- /usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at supportedLocales (/usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/locale.js:194:46)
    at closestSupportedLocale (/usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/locale.js:215:18)
    at localeStrings (/usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/locale.js:278:17)
    at _ (/usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/locale.js:297:16)
    at Function.label (/usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/SyncTargetFilesystem.js:19:10)
    at Function.addClass (/usr/local/Cellar/joplin/1.0.127/libexec/lib/node_modules/joplin/lib/SyncTargetRegistry.js:13:27)
Error: joplin: failed
```

**Comment by chrmoritz** [comment]
The missing `locales` are fixed in 1.0.128.

Note: The newer 1.0.129 release changed the build script (resulting in a different directory layout without any other change), but didn't update the main entry point accordingly, so it's broken too atm and that's why I'm sticking here with the otherwise identical 1.0.128

**Comment by fxcoudert** [comment]
You're adding an unrelated formula

**Comment by chrmoritz** [comment]
Ups, should be fixed now.

**Pull request closed without merging**
