### PR TITLE
bitcoin: 24.1

### PR DESCRIPTION
**Pull request by fanquake**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fanquake** [comment]
> Is there going to be any release announcements in this page

Yes, they'll be up shortly. See https://github.com/bitcoin-core/bitcoincore.org/pull/968.

**Comment by fanquake** [comment]
I assume this isn't a blocker, given https://github.com/Homebrew/homebrew-cask/pull/147468 has already been merged?

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks!

**Comment by chenrui333** [comment]
> I assume this isn't a blocker, given [Homebrew/homebrew-cask#147468](https://github.com/Homebrew/homebrew-cask/pull/147468) has already been merged?

yeah, it is not, just curious, thanks for that announcement PR. :)

**Pull request merged**
