### PR TITLE
ncurses 6.4

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /tmp/ncurses-test-20230101-18355-172c0tm/test/bin/keynames
  Failed to execute: /tmp/ncurses-test-20230101-18355-172c0tm/test/bin/keynames
```

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Linux-only failures:

```
Full linkage --test c-kermit output
  Unwanted system libraries:
    /lib/x86_64-linux-gnu/libcrypt.so.1
  Error: Calling linkage to libcrypt.so.1 is disabled! Use libcrypt.so.2 in the libxcrypt formula instead.
```

```
==> Testing glkterm
  ==> /usr/bin/gcc-11 test.c -I/home/linuxbrew/.linuxbrew/Cellar/glkterm/1.0.4/include -L/home/linuxbrew/.linuxbrew/Cellar/glkterm/1.0.4/lib -lglkterm -lncurses -o test
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/glkterm/1.0.4/lib/libglkterm.a(gtfref.o): in function `glk_fileref_create_temp':
  gtfref.c:(.text+0x16d): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/glkterm/1.0.4/lib/libglkterm.a(main.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
  /usr/bin/ld: failed to set dynamic section sizes: bad value
  collect2: error: ld returned 1 exit status
```

Same test failure for `glktermw` as well.

**Comment by iMichka** [comment]
Fix for `c-kermit`: #119598

**Comment by iMichka** [comment]
For  `glkterm` and `glktermw`: a rebuild with -fPie should fix it (`.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE`).

This means rebottling, and can be done after this PR is merged.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Good to ship, other errors are unrelated, will fix per #119598 and some rebottling for the 2 others.

**Comment by chenrui333** [comment]
Thanks @iMichka!

**Pull request closed without merging**
