### PR TITLE
Drop explicit python/python@3.8 dependency for formula which uses meson

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Initially, this PR was about migration a couple of formula to `python@3.8`, then it transformed to dropping `python`/`python@3.8` after @tschoonj comment https://github.com/Homebrew/homebrew-core/pull/54390#issuecomment-626114624

### CODE REVIEW

**Comment by tschoonj** [comment]
You may want to drop the python build dependency line: it should be dragged in by meson anyway.

I remember that this was done long time ago because all build time dependencies had to be listed explicitly, as they wouldn't be pulled in recursively.

**Comment by bayandin** [comment]
Fair enough, thanks for the suggestion!

I guess I could drop it for a whole bunch of formulae:
```
$ git grep -l 'depends_on "meson"'  | xargs grep 'depends_on "python" => :build'
Formula/babl.rb:  depends_on "python" => :build
Formula/baobab.rb:  depends_on "python" => :build
Formula/file-roller.rb:  depends_on "python" => :build
Formula/gcab.rb:  depends_on "python" => :build
Formula/gdk-pixbuf.rb:  depends_on "python" => :build
Formula/gexiv2.rb:  depends_on "python" => :build
Formula/ghex.rb:  depends_on "python" => :build
Formula/gom.rb:  depends_on "python" => :build
Formula/handbrake.rb:  depends_on "python" => :build
Formula/libdazzle.rb:  depends_on "python" => :build
Formula/libepoxy.rb:  depends_on "python" => :build
Formula/libgweather.rb:  depends_on "python" => :build
```

**Comment by tschoonj** [comment]
Looks good!

**Comment by bayandin** [comment]
There're left 3 formulae with python/python@3.8 build dependency. 2 are using a path to python site-packages in their meson args:

- `gexiv2`: 
https://github.com/Homebrew/homebrew-core/blob/672d537573cb5e5573c69986969dc9451907490f/Formula/gexiv2.rb#L32

- `gom`:
https://github.com/Homebrew/homebrew-core/blob/d1f3e0b8a57aece6472839a90e532214a8c83b2f/Formula/gom.rb#L27-L28

- `handbrake` will be done in https://github.com/Homebrew/homebrew-core/pull/54221

**Comment by bayandin** [comment]
Regarding `handbrake` I would keep python as a dependency since it uses it is built by make.

**Comment by bayandin** [comment]
`lc0` failed with strange (not related to PR changes at the first glance) error:

```
clang++ -Ichessboard_test@exe -I. -I../.. -I../../src -Xclang -fcolor-diagnostics -DNDEBUG -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wthread-safety -march=native '-DBUILD_IDENTIFIER="git.dirty"' -DUSE_BLAS -DNO_PEXT -isystem../../third_party -MD -MQ 'chessboard_test@exe/src_chess_board_test.cc.o' -MF 'chessboard_test@exe/src_chess_board_test.cc.o.d' -o 'chessboard_test@exe/src_chess_board_test.cc.o' -c ../../src/chess/board_test.cc
../../src/chess/board_test.cc:21:10: fatal error: 'gtest/gtest.h' file not found
#include <gtest/gtest.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

We shouldn't build tests in the first place, so I've disabled them.

**Comment by bayandin** [comment]
It turns out `lc0` requires to have python3 for compiling some proto files, so we need to keep it as an explicit dependency.

`lc0`, `gexiv2` and `gom` will be ported to `python@3.8` in https://github.com/Homebrew/homebrew-core/pull/54563

**Pull request closed without merging**
