### PR TITLE
grin-wallet 3.0.0

### PR DESCRIPTION
**Pull request by quentinlesceller**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
@BrewTestBot test this please

**Comment by quentinlesceller** [comment]
Looks like a CI related issue?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @quentinlesceller! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
