### PR TITLE
buku 3.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
https://gist.githubusercontent.com/anonymous/4228dc3dbe746cc9d2269d4f8ce60f57/raw/098df3b22067207c34a3b6787683c7bd5ec872a6/0001-buku-3.2-fix.patch

```diff
From 63af0243b3d2b2b78cdee358034104a4c190cdda Mon Sep 17 00:00:00 2001
From: Zhiming Wang <zmwangx@gmail.com>
Date: Thu, 3 Aug 2017 08:42:34 -0400
Subject: [PATCH] buku 3.2 fix

---
 Formula/buku.rb | 18 ++++++++++--------
 1 file changed, 10 insertions(+), 8 deletions(-)

diff --git a/Formula/buku.rb b/Formula/buku.rb
index 72acdec81d..1b4ffb09ca 100644
--- a/Formula/buku.rb
+++ b/Formula/buku.rb
@@ -27,8 +27,8 @@ class Buku < Formula
   end
 
   resource "certifi" do
-    url "https://files.pythonhosted.org/packages/dd/0e/1e3b58c861d40a9ca2d7ea4ccf47271d4456ae4294c5998ad817bd1b4396/certifi-2017.4.17.tar.gz"
-    sha256 "f7527ebf7461582ce95f7a9e03dd141ce810d40590834f4ec20cddd54234c10a"
+    url "https://files.pythonhosted.org/packages/20/d0/3f7a84b0c5b89e94abbd073a5f00c7176089f526edb056686751d5064cbd/certifi-2017.7.27.1.tar.gz"
+    sha256 "40523d2efb60523e113b44602298f0960e900388cf3bb6043f645cf57ea9e3f5"
   end
 
   resource "cffi" do
@@ -42,8 +42,8 @@ class Buku < Formula
   end
 
   resource "cryptography" do
-    url "https://files.pythonhosted.org/packages/2a/0c/31bd69469e90035381f0197b48bf71032991d9f07a7e444c311b4a23a3df/cryptography-1.9.tar.gz"
-    sha256 "5518337022718029e367d982642f3e3523541e098ad671672a90b82474c84882"
+    url "https://files.pythonhosted.org/packages/0a/23/ffee389a45f752dc745706cdb2d354b91ddb71594506fac45236cf67af49/cryptography-2.0.2.tar.gz"
+    sha256 "3780b2663ee7ebb37cb83263326e3cd7f8b2ea439c448539d4b87de12c8d06ab"
   end
 
   resource "idna" do
@@ -57,8 +57,8 @@ class Buku < Formula
   end
 
   resource "requests" do
-    url "https://files.pythonhosted.org/packages/2c/b5/2b6e8ef8dd18203b6399e9f28c7d54f6de7b7549853fe36d575bd31e29a7/requests-2.18.1.tar.gz"
-    sha256 "c6f3bdf4a4323ac7b45d01e04a6f6c20e32a052cd04de81e05103abc049ad9b9"
+    url "https://files.pythonhosted.org/packages/c3/38/d95ddb6cc8558930600be088e174a2152261a1e0708a18bf91b5b8c90b22/requests-2.18.3.tar.gz"
+    sha256 "fb68a7baef4965c12d9cd67c0f5a46e6e28be3d8c7b6910c758fbcc99880b518"
   end
 
   resource "six" do
@@ -67,8 +67,8 @@ class Buku < Formula
   end
 
   resource "urllib3" do
-    url "https://files.pythonhosted.org/packages/96/d9/40e4e515d3e17ed0adbbde1078e8518f8c4e3628496b56eb8f026a02b9e4/urllib3-1.21.1.tar.gz"
-    sha256 "b14486978518ca0901a76ba973d7821047409d7f726f22156b24e83fd71382a5"
+    url "https://files.pythonhosted.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz"
+    sha256 "cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
   end
 
   def install
@@ -107,6 +107,8 @@ class Buku < Formula
 
     (testpath/"import").write <<-EOS.undent
       spawn #{bin}/buku --nc --import bookmarks.html
+      expect "Specify unique tag for imports (Enter to skip): "
+      send "\r"
       expect "Add imported folders names as tags? (y/n): "
       send "y\r"
       expect {
-- 
2.13.4

```

**Comment by ilovezfs** [comment]
@zmwangx thanks!

**Comment by ilovezfs** [comment]
@zmwangx btw we're restricted to cryptography < 2 because it's re-broken: https://github.com/pyca/cryptography/issues/3332#issuecomment-319886204

**Comment by zmwangx** [comment]
Sure.

**Pull request closed without merging**
