### PR TITLE
include-what-you-use 0.22

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /tmp/include-what-you-use-20240313-5190-vsdofl/include-what-you-use/iwyu_ast_util.cc:278:66: error: no member named 'None' in 'clang::ElaboratedTypeKeyword'
           elaborated_type->getKeyword() != ElaboratedTypeKeyword::None;
                                            ~~~~~~~~~~~~~~~~~~~~~~~^
  /tmp/include-what-you-use-20240313-5190-vsdofl/include-what-you-use/iwyu.cc:4240:71: error: no member named 'None' in 'clang::ElaboratedTypeKeyword'
      if (type_loc.getTypePtr()->getKeyword() != ElaboratedTypeKeyword::None) {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by chenrui333** [comment]
- relates to #165206

**Comment by carlocab** [comment]
Needs to be cherry-picked onto #165206

**Comment by chenrui333** [comment]
close in favor of https://github.com/Homebrew/homebrew-core/pull/165206

**Comment by danra** [comment]
IMHO, it's a shame this was closed - `brew install include-what-you-use` (much lighter than `brew install llvm`) keeps downloading the older 0.21

**Pull request closed without merging**
