### PR TITLE
python3 3.6.4

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
At least pre-commit & pipenv will need revision bumps. Possibly sip too

**Comment by zmwangx** [comment]
@ilovezfs sip needing a revision bump shouldn't be too surprising; I would do it for safety even. But why pre-commit and pipenv? They are just pure python packages and shouldn't be affected by a patch release. Tests work fine too. How should they fail? That should probably be written into tests.

**Comment by ilovezfs** [comment]
@zmwangx see the virtualenv hot garbage:
https://github.com/Homebrew/homebrew-core/commit/39a6dd0dbe7497f05d5363d335cdbc5bda332371
https://github.com/Homebrew/homebrew-core/commit/df14ab737d2a2c45fe6a2c8d5514738c429081d5

It probably works because you haven't removed the old python3 from your Cellar yet?

**Comment by zmwangx** [comment]
>  removed the old python3 from your Cellar 

Good point. That should affect all packages using `Language::Python::Virtualenv`.

**Comment by ilovezfs** [comment]
@zmwangx bizarrely it seems to pass on CI too … which I cannot explain.

In any case, I have no idea why some virtualenv formulae hate the relative paths and others seemingly don't care. But they're originating from the Brew backend stuff that converts to relative symlinks not from virtualenv itself. So presumably we need some real fix in Brew besides adding the undo relative symlinks thing in post install to every formula that develops a cold.

**Comment by ilovezfs** [comment]
@zmwangx don't worry about gnuradio: https://github.com/Homebrew/homebrew-core/pull/21883

**Comment by zmwangx** [comment]
> bizarrely it seems to pass on CI too …

pipenv test failed locally and succeeded on the next run. WTF. Anyway I'm bumping it.

> not from virtualenv itself.

Yeah, virtualenv itself should be happy as long as there's still a `python3.6` in the same place as when you first created the virtualenv.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
:snake: :snake: :snake:

**Comment by ilovezfs** [comment]
@zmwangx 

>pipenv test failed locally and succeeded on the next run. WTF. Anyway I'm bumping it.

OK, so that's happening because the realpathing hacks for pipenv and for pre-commit are in `post_install` so a revision bump will break existing installations but not new ones. So the test blocks will pass even though the existing user installations are all broken. I'm not sure there's an easy way to add regression tests for this particular brand of crazy.

**Pull request closed without merging**
