### PR TITLE
Deprecate formulae that depend on a Java 1.8 Requirement.

### PR DESCRIPTION
**Pull request by jonchang**
Rebottle these formula for `openjdk@8`. Part of #63290.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
For `opentsdb`, adding those lines to `install` passes build and testing:
```
    ENV["JAVA"] = "#{Formula["openjdk@8"].bin}/java"
    ENV["JAVAC"] = "#{Formula["openjdk@8"].bin}/javac"
    ENV["JAR"] = "#{Formula["openjdk@8"].bin}/jar"
    ENV["JAVADOC"] = "#{Formula["openjdk@8"].bin}/javadoc"
```
However `hbase` requires `openjdk@11` so we get conflicting dependencies. I tried using `openjdk@11` on `opentsdb` without success, it leads to build errors. Upstream only mention this regarding java version:

> Java Runtime Environment 1.6 or later

**Comment by jonchang** [comment]
> For `opentsdb`, adding those lines to `install` passes build and testing:
> 
> ```
>     ENV["JAVA"] = "#{Formula["openjdk@8"].bin}/java"
>     ENV["JAVAC"] = "#{Formula["openjdk@8"].bin}/javac"
>     ENV["JAR"] = "#{Formula["openjdk@8"].bin}/jar"
>     ENV["JAVADOC"] = "#{Formula["openjdk@8"].bin}/javadoc"
> ```
> 
> However `hbase` requires `openjdk@11` so we get conflicting dependencies. I tried using `openjdk@11` on `opentsdb` without success, it leads to build errors. Upstream only mention this regarding java version:
> 
> > Java Runtime Environment 1.6 or later

Yeah, I've been thinking about adding an audit exception for openjdk to permit mixed versions in its build tree, since they can all coexist happily.

**Comment by jonchang** [comment]
drip: stable 0.2.4 (bottled)
install: 10 (30 days), 23 (90 days), 93 (365 days)
install-on-request: 10 (30 days), 23 (90 days), 92 (365 days)
build-error: 0 (30 days)

groovyserv: stable 1.2.0 (bottled)
install: 9 (30 days), 21 (90 days), 156 (365 days)
install-on-request: 9 (30 days), 21 (90 days), 153 (365 days)
build-error: 0 (30 days)

henplus: stable 0.9.8 (bottled)
install: 4 (30 days), 8 (90 days), 28 (365 days)
install-on-request: 4 (30 days), 8 (90 days), 28 (365 days)
build-error: 0 (30 days)

hexgui: stable 0.9.3 (bottled), HEAD
install: 5 (30 days), 18 (90 days), 61 (365 days)
install-on-request: 4 (30 days), 16 (90 days), 58 (365 days)
build-error: 0 (30 days)

infer: stable 0.17.0 (bottled)
install: 380 (30 days), 1,066 (90 days), 4,692 (365 days)
install-on-request: 376 (30 days), 1,059 (90 days), 4,579 (365 days)
build-error: 0 (30 days)

nailgun: stable 1.0.1 (bottled), HEAD
install: 23 (30 days), 78 (90 days), 407 (365 days)
install-on-request: 22 (30 days), 74 (90 days), 380 (365 days)
build-error: 0 (30 days)

opentsdb: stable 2.4.0 (bottled)
install: 33 (30 days), 60 (90 days), 205 (365 days)
install-on-request: 33 (30 days), 59 (90 days), 203 (365 days)
build-error: 0 (30 days)

**Comment by jonchang** [comment]
* Cherry picked `hexgui` since it actually built and tested properly
* The others have extremely low analytics and it's not worth editing our audits or otherwise spending more maintainer time on these. These will be deprecated.
* Infer can be fixed if we figure out what to do with https://github.com/Homebrew/homebrew-core/pull/62862 and get it to actually build on supported versions of macOS.

**Comment by jonchang** [comment]
Rebase and merging this when CI "passes"

**Pull request merged**
