### PR TITLE
pybind11 2.4.2

### PR DESCRIPTION
**Pull request by DennisOSRM**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DennisOSRM** [comment]
Looks like something is fishy with the build environment:

```
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk' [-Wmissing-sysroot]
```

**Comment by DennisOSRM** [comment]
@brewbot retest this please

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by DennisOSRM** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
