### PR TITLE
use secure urls #1

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Failing to run `brew audit` as a non-admin user on a formula residing in a local repo:

```
$ brew audit --strict --online ./xapian.rb 
error: could not lock config file /usr/local/Homebrew/.git/config: Permission denied
Error: Failure while executing: git config --file=/usr/local/Homebrew/.git/config --replace-all homebrew.devcmdrun true
```

### CODE REVIEW

**Comment by vszakats** [comment]
`poco` fails on El Capitan only:
```
==> FAILED
Testing poco
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161010-61198-7q9p2s.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/poco.rb --verbose
==> /usr/local/Cellar/poco/1.7.5/bin/cpspc -h
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/poco/1.7.5/lib/libPocoFoundation.45.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/poco/1.7.5/lib/libPocoFoundation.45.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by zmwangx** [comment]
https://predictionio.incubator.apache.org/ uses a SHA-1 cert which is no longer considered secure. I intentionally selected HTTP over HTTPS to discourage the false sense of security.

**Comment by vszakats** [comment]
Since this is an URL opened in a browser, wouldn't it be enough to leave handling this aspect to those? (like it's done with mixed-content and redirection to HTTP)

**Comment by ilovezfs** [comment]
@vszakats thanks again!

@zmwangx feel free to restore http on predictionio if you'd like

**Pull request merged**
