### PR TITLE
fio 2.17

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
clock joy on 10.11
```
==> FAILED
Testing fio
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161026-66749-10ckz1t.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fio.rb --verbose
==> /usr/local/Cellar/fio/2.15/bin/fio --parse-only
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/fio/2.15/bin/fio
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/fio/2.15/bin/fio
  Expected in: /usr/lib/libSystem.B.dylib

Error: fio: failed
```

**Comment by JCount** [comment]
@ilovezfs this is quite a hack, but this should fix this on 10.11 by making the _clock_gettime symbol definition test fail as we need it to:
```
if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
  inreplace "configure", "return clock_gettime(0, NULL);", "return foo();"
end
```
I tried to find a better way to do this, but this seemed to be the only reliable way. If this isn't a good fix, maybe it will at least be informative.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
closing in favor of #9644

**Pull request closed without merging**
