### PR TITLE
swiftformat 0.43.0

### PR DESCRIPTION
**Pull request by nicklockwood**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zachauten** [comment]
Thanks @nicklockwood! Also you might find `brew bump-formula-pr` useful next time there's a formula that only needs an updated url & sha256.

**Comment by yous** [comment]
It seems that the bottle for this version is not built. Other PRs recently merged are shipped with a bottle, but this one doesn't have one. Is there a way to trigger building a bottle?

``` console
$ brew install swiftformat
==> Downloading https://homebrew.bintray.com/bottles/swiftformat-0.43.0.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "swiftformat"
Download failed: https://homebrew.bintray.com/bottles/swiftformat-0.43.0.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/nicklockwood/SwiftFormat/archive/0.43.0.tar.gz
Already downloaded: /Users/yous/Library/Caches/Homebrew/downloads/11e7c4b2aad8f2e75c104fe3ada7dd7cdf40f31c415087e53bd43e93f57da2bf--SwiftFormat-0.43.0.tar.gz
==> xcodebuild -project SwiftFormat.xcodeproj -scheme SwiftFormat (Command Line Tool) CODE_SIGN_IDENTITY= SYMROOT=build OBJROOT=build
🍺  /usr/local/Cellar/swiftformat/0.43.0: 6 files, 2.0MB, built in 35 seconds
```

**Comment by zachauten** [comment]
@yous Looks like I forgot to trigger a build, thanks for letting me know! I can fix it later today.

**Comment by MikeMcQuaid** [comment]
Bottle fixed/added in 433cc8783b60874e95466331b248c842b77b7a48.

**Pull request merged**
