### PR TITLE
libadwaita 1.4.0 appstream 0.16.3 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`src/meson.build:289:16: ERROR: Dependency 'appstream' is required but not found.`

**Comment by alex-tee** [comment]
This needs appstream now: https://github.com/ximion/appstream

This patch fixes the appstream build on MacOS: https://github.com/ximion/appstream/pull/526

**Comment by chenrui333** [comment]
I will check on both tomorrow (it would be good that appstream project can make a release for the osx build patch :) )

**Comment by chenrui333** [comment]
got some appstream build failure on ventura arm
https://gist.github.com/chenrui333/c68d24faf5b61fadca8cf719f6be646c

**Comment by chenrui333** [comment]
closing for now. for anyone watching this, feel free to create a new PR.

**Comment by chenrui333** [comment]
```

```

**Comment by chenrui333** [comment]
https://github.com/ximion/appstream/issues/552

**Comment by danyeaw** [comment]
I got appstream and libadwaita to build on this branch: https://github.com/danyeaw/homebrew-core/tree/bump-libadwaita-1.4.0

`brew test appstream` is giving:

```
test.c:1:10: fatal error: 'appstream-glib.h' file not found
#include <appstream-glib.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
Error: appstream: failed
```

**Comment by chenrui333** [comment]
close in favor of #153408

Thanks @danyeaw for carrying this over.

**Pull request closed without merging**
