### PR TITLE
wxmac 3.1.4

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Looks like these formulae need revision bumps:

```
Error: 9 failed steps!
brew linkage --test diff-pdf
brew test --verbose diff-pdf
brew linkage --test erlang
brew linkage --test erlang@21
brew linkage --test erlang@22
brew linkage --test gambit
brew linkage --test homeworlds
brew linkage --test scummvm-tools
brew linkage --test spatialite-gui
```

**Comment by fxcoudert** [comment]
I do not think it is acceptable:

> wxWidgets 3.1.4 is the latest release in the 3.1 development branch. **This release is a "development" one** as it makes (very few) incompatible API changes compared to 3.0 and **does not guarantee the ABI stability, unlike the 3.0.x series**. It is not inherently more buggy or less stable than the "stable" releases and you're encouraged to use it, including in production.

**Comment by miccal** [comment]
@SeekingMeaning thank you, just waiting for the 10.15 check before I go ahead with the required bumps.

**Comment by SeekingMeaning** [comment]
I think 10.15 stalled

**Comment by miccal** [comment]
@fxcoudert I thought that too, but it is marked at `Latest` in their GitHub feed and as you quoted:

> It is not inherently more buggy or less stable than the "stable" releases and you're encouraged to use it, including in production. If you're already using 3.0, upgrading shouldn't require any special effort, so please try it out.

Happy to close though, if you prefer.

**Comment by miccal** [comment]
Also, the three `erlang` fomula are being updated:

https://github.com/Homebrew/homebrew-core/pull/58313
https://github.com/Homebrew/homebrew-core/pull/58388
https://github.com/Homebrew/homebrew-core/pull/58389

Adding a `revision` bump here will cause a conflict in these -- ping @chenrui333

**Comment by SeekingMeaning** [comment]
I think those stalled too

**Comment by SeekingMeaning** [comment]
Huh, `homeworlds` doesn't have official release tags

**Comment by miccal** [comment]
@SeekingMeaning I _think_ the version is the last commit date. Anyway, this commit I added was just to test it out ...

**Comment by SeekingMeaning** [comment]
I'm going to close this since 3.1 is a development version. Regardless, thank you for opening this pull request! If you want to watch the workflow and see how it turns out, here's a link: https://github.com/Homebrew/homebrew-core/actions/runs/179221418

**Comment by cdalvaro** [comment]
For people looking for wxWidgets 3.1.4, you can install it directly from my custom tap:

```
brew install cdalvaro/tap/wxmac
```

**Pull request closed without merging**
