### PR TITLE
bullet 3.22b

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

continuing #98473

### CODE REVIEW

**Comment by chenrui333** [comment]
there might be some linux build failure as show in #98473

**Comment by Bo98** [comment]
To quote my previous question:

> Do we currently ship the examples? If not we should disable them via `BUILD_BULLET2_DEMOS=OFF` etc.

**Comment by cho-m** [comment]
> To quote my previous question:
> 
> > Do we currently ship the examples? If not we should disable them via `BUILD_BULLET2_DEMOS=OFF` etc.
> 
> I should probably check out the 3.21 bottles myself and see.

At least the ones that have an CMake install section like `ExampleBrowser` (https://github.com/bulletphysics/bullet3/blob/3.22b/examples/ExampleBrowser/CMakeLists.txt#L75-L78):
```console
❯ fd ExampleBrowser
include/bullet/ExampleBrowser
include/bullet/ExampleBrowser/ExampleBrowserInterface.h
include/bullet/ExampleBrowser/InProcessExampleBrowser.h
include/bullet/ExampleBrowser/OpenGLExampleBrowser.h
lib/bullet/double/libBulletExampleBrowserLib.3.20.dylib
lib/bullet/double/libBulletExampleBrowserLib.dylib
lib/bullet/single/libBulletExampleBrowserLib.3.20.dylib
lib/bullet/single/libBulletExampleBrowserLib.a
lib/bullet/single/libBulletExampleBrowserLib.dylib
lib/libBulletExampleBrowserLib.3.20.dylib
lib/libBulletExampleBrowserLib.a
lib/libBulletExampleBrowserLib.dylib
```

**Comment by cho-m** [comment]
`efl` is impacted by `bullet` deciding to include an example header they don't install https://github.com/bulletphysics/bullet3/commit/fb3b306af19aac4d7581702a7676c2452fb9658a

**src/BulletSoftBody/btSoftBodyHelpers.h**
```h
#include "../../examples/CommonInterfaces/CommonFileIOInterface.h"
```

**Comment by cho-m** [comment]
Odd how our audit is failing on GitHub URLs. This is happening in multiple PRs. Downloading the same URLs work.

**Pull request closed without merging**
