### PR TITLE
hub 2.3.0-pre10 (devel)

### PR DESCRIPTION
**Pull request by ed-flanagan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ed-flanagan** [comment]
`brew audit --strict hub` failed:

```
$ brew audit --strict hub

hub:
  * devel version should not decrease (from 2.3.0-pre9 to 2.3.0-pre10)
Error: 1 problem in 1 formula
```

---

`bump-formula-pr` failed:

```
$ brew bump-formula-pr --devel --dry-run --strict --version=2.3.0-pre10 --url=https://github.com/github/hub/archive/v2.3.0-pre10.tar.gz --sha256=9b4764dc2647bc0c14de2bd386e6f428f002d93baf01059d994e1cfa928483fc hub

==> brew update
==> replace "https://github.com/github/hub/archive/v2.3.0-pre9.tar.gz" with "https://github.com/github/hub/archive/v2.3.0-pre10.tar.gz"
==> replace "3246a5e3a071a7ccb06c30230a720b6457837bd6b97b32ab248dfb2b2222dbfb" with "9b4764dc2647bc0c14de2bd386e6f428f002d93baf01059d994e1cfa928483fc"
==> replace /(  devel do.+?version \")2.3.0-pre9(\"\n.+?end\n)/m with "\\12.3.0-pre10\\2"
Error: You probably need to bump this formula manually since changing the
version from 2.3.0-pre9 to 2.3.0-pre10 would be a downgrade.
```

---

Something with `pre9`/`pre10` comparison? https://github.com/Homebrew/brew/blob/22c431d221ca25413f3b63374d75173bedbe9e66/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L244

**Comment by ilovezfs** [comment]
And then there's
```
irb(main):001:0> Version.new("2.3.0-pre9") > Version.new("2.3.0")
=> true
```

CC @MikeMcQuaid It would be unfortunate to have to add version_scheme 1 to `hub` over this ...

**Comment by ed-flanagan** [comment]
Certainly don't mean to be presumptuous, especially since I'm not at all familiar with the actual `brew` internals.
But, could `/pre\d+/` be a potential `CompositeToken`?
For example: https://gist.github.com/ed-flanagan/ee74c8cc93b8ba610b421ded9e6ab2b9
Figured I'd at least send send something up, since my PR ran into this case.

**Comment by MikeMcQuaid** [comment]
@ed-flanagan Seems like a great idea, nice spot. Can you send a PR? Please be even more presumptuous in future 😆. We'll cut a tag soonish after it's merged.

**Comment by ed-flanagan** [comment]
Haha, thanks, will do!

I could see where this same problem arises again when a project uses unexpected `CompositeToken` conventions, e.g. `x.y.z-prerelease9`.

To be extra generic, could `StringToken` be more generic (basically any alphanum combo, e.g. `/\d*[a-z][a-z0-9]*/i`) and `CompositeToken` strictly be `/[a-z]+\d+/i`?

Example: https://gist.github.com/ed-flanagan/c6fb100bf6611860625d5b95f2cac8b6
Probably a far more involved/un-tested change. (But can be used in conjunction with the above `PreToken` - providing "precedence")

**Comment by ed-flanagan** [comment]
Haha, thanks, will do!

I can imagine this exact issue occurring again when a project uses an unexpected `CompositeToken`, e.g. `x.y.z-prerelease10`.

Might it be be useful to make `StringToken` more "generic" while keeping `CompositeToken` strictly `/[a-z]+\d*/i`? I.e. `StringToken` is similar to SemVer's [pre-release](http://semver.org/#spec-item-9) and `CompositeToken` is just a subset with "precedence."
Example: https://gist.github.com/ed-flanagan/d5100723d00d57590f55a3bb5b866301 (not totally fleshed out)

Definitely a more involved/un-tested change. But it can work in conjunction with the `PreToken` since additional `CompositeToken`s benefit the "precedence."

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
We'll need to wait for a new tag.

**Comment by ed-flanagan** [comment]
@ilovezfs `brew audit` seems to pass now (with https://github.com/Homebrew/brew/releases/tag/1.2.4)

**Comment by PaulCapestany** [comment]
Nice @ed-flanagan—I was just about to do a PR for this! We could really use the new `pull-request --reviewer` ability included in `v2.3.0-pre10` (and have it easily installed by our engs @ Foursquare via `brew install hub --devel`), so hopefully this gets merged soon 🤞

**Comment by ilovezfs** [comment]
Thanks @ed-flanagan :rocket:

**Pull request merged**
