### PR TITLE
gdal 3.8.0

### PR DESCRIPTION
**Pull request by Firefishy**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Firefishy** [comment]
Bump `revision` on downstream dependencies.

**Comment by chenrui333** [comment]
@Firefishy can you spread the commits per formula? (like `xx: revision bump (gdal 3.8.0`)) Thanks!

**Comment by chenrui333** [comment]
Thanks!

**Comment by Firefishy** [comment]
It is unclear to me why the CI tests failed. False negative?

**Comment by chenrui333** [comment]
the build timed out, that is why :)

**Comment by Firefishy** [comment]
Upstream PR to fix `simple-tiles` compatibility with new versions of python: https://github.com/propublica/simple-tiles/pull/23

**Comment by Firefishy** [comment]
PR to fix the `simple-tiles` build failure: https://github.com/Homebrew/homebrew-core/pull/154771

**Comment by Firefishy** [comment]
The tests should pass once rebased now that `simple-tiles` change has been merged. I am out for the next few hours, others are welcome to rebase now if desired.

**Comment by Firefishy** [comment]
@chenrui333 @ZhongRuoyu Please could you add the magic flag to allow this to build? I think it should then pass all tests now.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
