### PR TITLE
mosquitto 2.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by okket** [comment]
Just FYI: No announcement on https://mosquitto.org/download/, no tag/release on https://github.com/eclipse/mosquitto/releases yet.

Main branch has merged 2.0.0 though, changelog can be found at https://github.com/eclipse/mosquitto/blob/master/ChangeLog.txt

**Comment by SMillerDev** [comment]
We should probably fix the livecheck then to look at tags or the download page.

**Comment by okket** [comment]
The 2.0.0 release is now live on the website and is tagged here in GitHub.

**Comment by chenrui333** [comment]
> We should probably fix the livecheck then to look at tags or the download page.

Make sense, I will do that.

**Comment by chenrui333** [comment]
> The 2.0.0 release is now live on the website and is tagged here in GitHub.

oh cool!!

**Comment by chenrui333** [comment]
Now the livecheck got updated, I think we can shoot for the merge.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
