### PR TITLE
git-dendrify-0.2.0 and literate-git-0.3.1 (new formulae)

### PR DESCRIPTION
**Pull request by lukel97**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

cc @bennorth

### CODE REVIEW

**Comment by bubba** [comment]
literate-git passes the notable audit, but using it is pretty dependent on the git-dendrify tool which doesn't seem to have as much love on GitHub.

**Comment by SMillerDev** [comment]
Please create one formula per pull request

**Comment by zbeekman** [comment]
> literate-git passes the notable audit, but using it is pretty dependent on the git-dendrify tool which doesn't seem to have as much love on GitHub.

Can you please explain why this is? It's not listed as a dependency...

**Comment by bennorth** [comment]
Hi, I'm the author of the literate-git and git-dendrify packages.  Thanks for including literate-git in the Homebrew world, and considering git-dendrify.  If I can jump in regarding the pseudo-dependency:

The literate-git tool lets developers produce a web-page 'rendering' of a section of git history.  There's an example of the result here:

[https://www.redfrontdoor.org/20200201-literate-git-demo/index.html](https://www.redfrontdoor.org/20200201-literate-git-demo/index.html)

This web page is generated just from the git history; the text comes from the commit messages.

To take full advantage of the tool, your repo history needs to be in an 'organized' form, where branches and sub-branches show how the history is structured as sections and sub-sections.  Interactively rebasing such histories, to give the clearest presentation, is very fiddly.  The git-dendrify tool allows you to work with a linear history, and then turn it into a structured history suitable for rendering with literate-git.  So while you _can_ use literate-git without git-dendrify, it's much easier _with_ it.

Hope this helps — please let me know if more detail would be useful.

**Comment by zbeekman** [comment]
@bennorth @bubba: How useful is git-dendrify on its own? Should it be resourced as part of literate-git? I think, at least until it reaches the notability metrics, that's the approach that I favor.

Or, alternatively, removing literate-git until git-dendrify can also meet the notability metrics.

**Comment by bubba** [comment]
@zbeekman I'm happy to include it as a resource of `literate-git`, as long as its able to be symlinked ok

**Pull request closed without merging**
