### PR TITLE
thefuck 3.10

### PR DESCRIPTION
**Pull request by ilovezfs**
- fix the test as output to non-tty is now unadorned text
- style tweaks in the test

### CODE REVIEW

**Comment by DomT4** [comment]
👍 when 🍏

**Comment by ilovezfs** [comment]
@DomT4 it will be soon thanks to @tdsmith https://github.com/nvbn/thefuck/pull/525

**Comment by DomT4** [comment]
Looks like there's an additional issue 😢
```
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/3.10/libexec --single-version-externally-managed --record=installed.txt
error in thefuck setup command: Invalid environment marker: python_version<"3.4"
```

**Comment by ilovezfs** [comment]
Probably the `':python_version<"3.4"'` should be `":python_version<'3.4'"`

**Comment by ilovezfs** [comment]
Nope, it's something else.

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed. :green_apple: 

It requires a newish version of setuptools. Same issue as https://github.com/docker/docker-py/issues/1019.

**Comment by DomT4** [comment]
🎉 Thanks ILZ!

**Comment by ilovezfs** [comment]
*ilovezfs wags his tail*

**Pull request closed without merging**
