### PR TITLE
leptonica 1.74.4

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
Sorry to open a duplicate, but OP in #14945 hasn't responded in 11 days, and this 404 ought to be fixed.

**Comment by zmwangx** [comment]
(I'm kind of resubmitting for a CI rebuild; I'm fine if a maintainer decides to fix up #14945 directly and close this.)

**Comment by zmwangx** [comment]
Switching to the release tarball on GitHub as the primary URL so that we don't run into the same 404 problem in the future whenever a new point release comes out.

**Comment by ilovezfs** [comment]
:leopard:

**Pull request closed without merging**
