### PR TITLE
imagemagick 7.0.8-16

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
**The mirror needs to be handled upon merging.**

**Comment by lembacon** [comment]
@Homebrew/maintainers Please do not forget to run `brew mirror imagemagick` upon merging. 😅 https://github.com/Homebrew/homebrew-core/commit/2d8a8f34b21bf88763f4a5925d650a07928f3dc4#comments

**Comment by SMillerDev** [comment]
Could we make an audit for that?

**Comment by sjackman** [comment]
> Could we make an audit for that?

I would expect that `brew audit --online` already tests that the `mirror` is a valid URL. It should if it doesn't. The error message could be made extra helpful when the URL is a Homebrew mirror URL.

**Comment by sjackman** [comment]
`brew test geeqie` and `brew test pqiv` failed on High Sierra. The error message is…
```
==> /usr/local/Cellar/geeqie/1.4_1/bin/geeqie --version
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2018-12-10 16:49:28.714 geeqie[77550:33801548] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
```
I've seen this error message with other PRs as well. It appears that the High Sierra Jenkins configuration is headless (I don't know why).

**Pull request closed without merging**
