### PR TITLE
chronograf 1.7.12

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
07:05:01 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
07:05:01 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
07:05:01 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
07:05:01 node-pre-gyp ERR! System Darwin 18.6.0
07:05:01 node-pre-gyp ERR! command \"/usr/local/Cellar/node/12.4.0/bin/node\" \"/private/tmp/chronograf-20190621-1097-1m2hdip/chronograf-1.7.12/src/github.com/influxdata/chronograf/ui/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
07:05:01 node-pre-gyp ERR! cwd /private/tmp/chronograf-20190621-1097-1m2hdip/chronograf-1.7.12/src/github.com/influxdata/chronograf/ui/node_modules/fsevents
07:05:01 node-pre-gyp ERR! node -v v12.4.0
07:05:01 node-pre-gyp ERR! node-pre-gyp -v v0.10.0
07:05:01 node-pre-gyp ERR! not ok 
07:05:01 Failed to execute '/usr/local/Cellar/node/12.4.0/bin/node /private/tmp/chronograf-20190621-1097-1m2hdip/chronograf-1.7.12/src/github.com/influxdata/chronograf/ui/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/tmp/chronograf-20190621-1097-1m2hdip/chronograf-1.7.12/src/github.com/influxdata/chronograf/ui/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/private/tmp/chronograf-20190621-1097-1m2hdip/chronograf-1.7.12/src/github.com/influxdata/chronograf/ui/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)"
07:05:01 info This module is OPTIONAL, you can safely ignore this error
07:05:01 make: *** [.jsdep] Error 1
07:05:01 
07:05:01 ==> Formula
07:05:01 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chronograf.rb
```

**Comment by chrmoritz** [comment]
I think this requires a `depends_on "node@10" => :build` for now (however the actual critical build error is the one from `deasync` and not from the optional `fsevents` dependency).

Also I think we should finally remove the `ignore-engines` workaround added over a year ago here.

**Comment by chrmoritz** [comment]
Alternatively we could upgrade a few build dependencies for node 12 support (or just delete the `yarn.lock` file altogether, because the semver ranges in their `package.json` are relaxed enough to match the node 12 compatible versions):

```diff
@@ -27,10 +27,10 @@ class Chronograf < Formula
     chronograf_path = buildpath/"src/github.com/influxdata/chronograf"
     chronograf_path.install buildpath.children
 
-    # fixes yarn + upath@1.0.4 incompatibility, remove once upath is upgraded to 1.0.5+
-    Pathname.new("#{ENV["HOME"]}/.yarnrc").write("ignore-engines true\n")
-
     cd chronograf_path do
+      cd "ui" do # fix node 12 compatibility
+        system "yarn", "upgrade", "parcel@1.11.0", "node-sass@4.12.0"
+      end
       system "make", "dep"
       system "make", ".jssrc"
       system "make", "chronograf"
```

**Comment by chenrui333** [comment]
test phase failed:
```
06:43:27 ==> curl -s 0.0.0.0:8888/chronograf/v1/
06:43:27 Error: chronograf: failed
06:43:27 An exception occurred within a child process:
06:43:27   Test::Unit::AssertionFailedError: <0> expected but was
06:43:27 <7>.
```

**Comment by chrmoritz** [comment]
I can reproduce the test failure locally on the first run. However all subsequent test runs are passing. So there might be some missing bootstrap which fails the first run only?

**Comment by chenrui333** [comment]
It works, thanks @chrmoritz!

**Comment by chenrui333** [comment]
@fxcoudert good for the merg.

**Pull request closed without merging**
