### PR TITLE
flake8: depends on `python` instead of `python@2`

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
What is the motivation for this change?

**Comment by moonfruit** [comment]
Because python maintainer says this from [Python2orPython3](https://wiki.python.org/moin/Python2orPython3).
> Python 2.x is legacy, Python 3.x is the present and future of the language

And flake8 does support python3.

And I don't want install the huge `python@2` that **macOS already have** because of the installation of such a small tool.

**Comment by ilovezfs** [comment]
That's not a sufficient reason to switch this over as we're not actively migrating things to Python 3 just because they can be. That may change at some point but not yet.

**Comment by ilovezfs** [comment]
Thanks for the PR nonetheless @moonfruit

**Pull request closed without merging**
