### PR TITLE
i2p 0.9.32

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
> Error: Invalid or corrupt jarfile i2pinstall_0.9.32.jar

Upstream `sha256`: 
```
2ff82498c5491a138e42991658d0d747f13579392d0d065c65fbe9a94ae18fdf  i2pinstall_0.9.32.jar
```

https://geti2p.net/en/blog/post/2017/11/07/0.9.32-Release

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ curl -sL https://download.i2p2.de/releases/0.9.32/i2pinstall_0.9.32.jar | shasum -a256
2ff82498c5491a138e42991658d0d747f13579392d0d065c65fbe9a94ae18fdf  -
```

**Comment by commitay** [comment]
Thanks @ilovezfs! Reverted to original URL.

**Comment by ilovezfs** [comment]
Thanks again, @commitay!

**Pull request merged**
