### PR TITLE
glib 2.58.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
A couple of test and linking failures on `mojave_testing`, which appear unrelated to `glib`

**Comment by DomT4** [comment]
Aye, most of those are known issues. https://github.com/Homebrew/homebrew-core/pull/31630 should fix the test failures for a couple of them. This is fine to go in as-is; I'll pull it imminently.

**Comment by tschoonj** [comment]
Thanks!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/0a098294320b649dff510c42f60462226837ee73. Thanks again Tom 🙇

**Pull request closed without merging**
