### PR TITLE
rust: merge in `rustfmt` to avoid pre-builts

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #191373
Closes #191375
Closes #191305

### CODE REVIEW

**Comment by cho-m** [comment]
Currently looking into deprecating `rustfmt` (#191375) if anyone was using that without `rust` as merging into `rust` will require full installation.

May need to add `link_overwrite` to make this work.

**Review by carlocab — APPROVED** [review]
Been thinking about doing exactly this, except I was also going to delete `rustfmt` and then add `"rustfmt": "rust"` to `formula_renames.json`.

**Comment by cho-m** [comment]
Keeping a draft until we finalize approach (i.e. rename or deprecation). Probably need revision bump.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Cancelling merge for now to avoid introducing conflicts at #181351.

**Comment by carlocab** [comment]
Merged in 84a752174aa638f7a08cfbe052d0e77e5e13af91.

**Pull request closed without merging**
