### PR TITLE
moto 2.0.2 (new formula)

### PR DESCRIPTION
**Pull request by singingwolfboy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[Moto](http://docs.getmoto.org/en/latest/) is a library for mocking AWS services. It comes with a stand-alone server mode, which is useful for projects that don't use Python. This formula is about packaging this stand-alone server so that it's easy to install through Homebrew.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
It seems that the test is passing for 10.14 and 11-arm, but failing for 10.15 and 11.0. This is really strange, and makes me wonder if the problem is with the testing environment somehow? I don't see any output from running `moto_server` either, which makes this really tricky to debug.

Does anyone have any suggestions for how I can proceed here?

**Comment by carlocab** [comment]
Yea, the failures stump me too. I'd try to `sleep` a bit longer between `curl` attempts, and then maybe just try a simpler version of the test if that didn't help.

**Comment by singingwolfboy** [comment]
I got the tests to pass! 🎉

**Review by carlocab — APPROVED** [review]
Thanks, @singingwolfboy!

(FYI, for future reference, your commit message should put the name of the formula first.)

**Pull request closed without merging**
