### PR TITLE
Solidity 0.7.4

### PR DESCRIPTION
**Pull request by chriseth**
Updates the version of the Solidity package from 0.7.3 to 0.7.4.

### CODE REVIEW

**Comment by chriseth** [comment]
Improved the description.

**Comment by chenrui333** [comment]
`The URL https://solidity.readthedocs.io is not reachable (HTTP status code 404)`

**Comment by chriseth** [comment]
@chenrui333 that was the case when the PR was created, but it has been fixed in the meantime. Sorry for the inconvenience!

**Comment by Rylan12** [comment]
@chriseth the failures here are unrelated. Rebasing this PR should fix them

**Comment by chriseth** [comment]
Re-triggered the CI by force-pushing and it seems to work. Thanks, @Rylan12

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Thanks, @chriseth!

**Pull request closed without merging**
