### PR TITLE
sonobuoy: fetch resources before testing

### PR DESCRIPTION
**Pull request by iwittkau**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Tests for this formula kept failing on current Go version, related to https://github.com/Homebrew/homebrew-core/pull/47510

### CODE REVIEW

**Comment by iwittkau** [comment]
```
error: could not lock config file .git/config: No space left on device
```

Can someone trigger the pipeline, @SMillerDev @chenrui333, please?

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by iwittkau** [comment]
@SMillerDev I didn't know about this 😅, thanks!

**Comment by SMillerDev** [comment]
Should only be available to maintainers but that restriction doesn't always seem to work 😅

**Comment by SMillerDev** [comment]
Can you squash your commits?

**Pull request merged**
