### PR TITLE
whisperkit-cli 0.7.0

### PR DESCRIPTION
**Pull request by argmaxincbot**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by ZachNagengast** [comment]
Looks like maybe it's not completing the model download in time to test?

**Comment by chenrui333** [comment]
> Looks like maybe it's not completing the model download in time to test?

```
2024-05-24 18:35:26.791 whisperkit-cli[32834:15551371] NetworkStorageDB:_openDBReadConnections: failed to open read connection to DB @ /Users/rui/Library/Caches/whisperkit-cli/Cache.db.  Error=14. Cause=unable to open database file
2024-05-24 18:35:26.791 whisperkit-cli[32834:15551371] The read-connection to the DB=/Users/rui/Library/Caches/whisperkit-cli/Cache.db is NOT valid.  Unable to determine schema version.
2024-05-24 18:35:26.791 whisperkit-cli[32834:15551371] NetworkStorageDB:_openDBWriteConnections: failed to open write connection to DB @ /Users/rui/Library/Caches/whisperkit-cli/Cache.db.  Error=14. Cause=unable to open database file
```

**Comment by chenrui333** [comment]
Sounds like the test step needs to be updated?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
All good ✅

**Pull request merged**
