### PR TITLE
platformio 6.1.10

### PR DESCRIPTION
**Pull request by ivankravets**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

# Release Notes

* Resolved an issue that caused generated projects for [PlatformIO IDE for VSCode](https://docs.platformio.org/en/latest/integration/ide/vscode.html) to break when the ``-iprefix`` compiler flag was used
* Resolved an issue encountered while utilizing the [pio pkg exec](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_exec.html) command on the Windows platform to execute Python scripts from a package
* Implemented a crucial improvement to the [pio run](https://docs.platformio.org/en/latest/core/userguide/cmd_run.html) command, guaranteeing that the ``monitor`` target is not executed if any of the preceding targets, such as ``upload``, encounter failures
* [Cppcheck](https://docs.platformio.org/en/latest/plus/check-tools/cppcheck.html) v2.11 with new checks, CLI commands and various analysis improvements
* Resolved a critical issue that arose on macOS ARM platforms due to the Python "requests" module, leading to a "ModuleNotFoundError: No module named 'chardet'" ([issue #4702](https://github.com/platformio/platformio-core/issues/4702))

### CODE REVIEW

**Comment by chenrui333** [comment]
image
@ivankravets can you follow the guide?

**Comment by ivankravets** [comment]
I've been having pain with publishing PlatformIO releases to brew since the beginning. The rules changes fast and I waste a lot of time to provide PR.

How to use this system?

**Comment by ivankravets** [comment]
I forgot to add. I use `poetry`. I remember brew recommended it for Python packages. Then I manually merge `poetry` output with the latest brew formula and make PR.

**Comment by chenrui333** [comment]
> I've been having pain with publishing PlatformIO releases to brew since the beginning. The rules changes fast and I waste a lot of time to provide PR.
> 
> How to use this system?

it is really easy, `brew bump --open-pr platformio` and if you want to override, you can do `brew bump-open-pr platformio --version=x.x.x --force`

**Comment by chenrui333** [comment]
And if you want to integrate with your pipeline, you can just use these actions:
- https://github.com/dawidd6/action-homebrew-bump-formula
- https://github.com/mislav/bump-homebrew-formula-action

**Comment by ivankravets** [comment]
```
brew bump --open-pr platformio
==> platformio
Current formula version:  6.1.9
Latest livecheck version: 6.1.10
Latest Repology version:  6.1.9
Open pull requests:       none
Closed pull requests:     platformio 6.1.10 (https://github.com/Homebrew/homebrew-core/pull/139300), platformio 6.1.10 (https://github.com/Homebrew/homebrew-core/pull/139295)
```

What is next? Has anyone tried to you this for the Python project?

**Comment by ivankravets** [comment]
Does it make sense to remove `platformio` from the `brew` registry? Do you provide this option? It will save us a lot of time maintaining PlatformIO just in the PyPi registry.

**Comment by ivankravets** [comment]
Can this PR be merged now?

**Comment by p-linnane** [comment]
If you can change the commit message to be `platformio 6.1.10`, then yes.

**Comment by chenrui333** [comment]
> if you want to override, you can do `brew bump-open-pr platformio --version=x.x.x --force`

I thought I already mentioned this.

**Pull request closed without merging**
