### PR TITLE
yydecode: add test

### PR DESCRIPTION
**Pull request by mauromorales**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add test that verifies version against `yydecode --version`

relates to #11898

### CODE REVIEW

**Comment by SMillerDev** [comment]
Don't think the test is working?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by SMillerDev** [comment]
@BrewTestBot test this please
@mauromorales do you know why it's failing?

**Comment by mauromorales** [comment]
@SMillerDev seems to be related to the building of the tool in sierra (mojave and high sierra passed last build)

I'm pasting the result of make install of the last build in sierra, maybe we can run it again and see if the failure is consistent.

```
==> make install
Making install in src
clang -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c `test -f 'yydecode.c' || echo './'`yydecode.c
clang -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c `test -f 'crc32.c' || echo './'`crc32.c
clang -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c `test -f 'error.c' || echo './'`error.c
clang -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c `test -f 'getopt1.c' || echo './'`getopt1.c
In file included from crc32.c:20:
./crc32.h:16:2: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
        u_int32_t crc32;
        ^~~~~~~~~
        __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
In file included from crc32.c:20:
./crc32.h:23:8: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
extern u_int32_t crc32_read_ctx(const struct crc32_ctx *ctx);
       ^~~~~~~~~
       __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
crc32.c:22:8: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
static u_int32_t
       ^~~~~~~~~
       __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
crc32.c:73:2: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
        u_int32_t crc32 = ctx->crc32;
        ^~~~~~~~~
        __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
crc32.c:82:1: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
u_int32_t
^~~~~~~~~
__int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
5 errors generated.
make[1]: *** [crc32.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1
```

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by fxcoudert** [comment]
Fails on High Sierra:

```
In file included from crc32.c:20:
./crc32.h:16:2: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
        u_int32_t crc32;
        ^~~~~~~~~
        __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
In file included from crc32.c:20:
./crc32.h:23:8: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
extern u_int32_t crc32_read_ctx(const struct crc32_ctx *ctx);
       ^~~~~~~~~
       __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
crc32.c:22:8: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
static u_int32_t
       ^~~~~~~~~
       __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
crc32.c:73:2: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
        u_int32_t crc32 = ctx->crc32;
        ^~~~~~~~~
        __int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
crc32.c:82:1: error: unknown type name 'u_int32_t'; did you mean '__int32_t'?
u_int32_t
^~~~~~~~~
__int32_t
/usr/include/i386/_types.h:44:15: note: '__int32_t' declared here
typedef int                     __int32_t;
                                ^
5 errors generated.
```

**Comment by mauromorales** [comment]
@fxcoudert seems to be related to building in Sierra OS, I don't have it available to test locally, is there a way to debug in the CI or how do you guys go about debugging OS specific issues?

**Pull request closed without merging**
