### PR TITLE
sonarlint 2.0 (new formula)

### PR DESCRIPTION
**Pull request by adam-moss**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by adam-moss** [comment]
3rd question is not applicable to this PR as this is a prebuilt java .jar package.

**Comment by woodruffw** [comment]
We don't currently include binary (including prebuilt Java JARs) formulae in the core Homebrew tap. This formula would need to build `sonarlint` from source (looks like it can be found [here](https://github.com/SonarSource/sonarlint-cli/releases)) in order to be considered for merging.

In the meantime (or as an alternative), you can always set up a personal tap that installs it as-is.

**Comment by adam-moss** [comment]
Has that changed?  I've based this formula on the hadoop and jmeter ones which do the same thing?

**Comment by woodruffw** [comment]
Oh, interesting. I was going by the [formulae guidelines](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md), but those appear to be counterexamples that we've accepted in the past.

I'm asking the other maintainers for advice on this, but in the meantime you can add `bottle :unneeded` to the formula since a prebuilt JAR shouldn't need bottles.

**Comment by adam-moss** [comment]
Ok, I've added `bottle :unneeded`, thanks :)

**Comment by woodruffw** [comment]
Thanks @adam-moss, great work!

**Comment by adam-moss** [comment]
Thanks for accepting it! 👍

**Comment by adam-moss** [comment]
Hmmm.  @woodruffw the build for this seems to have failed when doing the merge.  Is there something I need to fix?

**Comment by woodruffw** [comment]
From what I can see, the last build passed. Are you looking at the same build job?

**Comment by adam-moss** [comment]
Possibly not, however I've yet to see it appear following a `brew update` and `brew search sonarlint` just outputs that it is a closed pull request?

**Comment by MikeMcQuaid** [comment]
You can likely ignore this, don't worry.

**Comment by adam-moss** [comment]
Ok, I take it it'll just automagically appear as a result of `brew update` at some point?

**Comment by woodruffw** [comment]
Ah, just realized that this created `Formula/homebrew/core/sonarlint.rb`, not `Formula/sonarlint.rb`.
I'll fix this in a moment.

**Comment by adam-moss** [comment]
Uh oh.  Is that something I did wrong ?

**Comment by woodruffw** [comment]
Yeah, but it's minor - don't worry about it :smile:

**Comment by woodruffw** [comment]
#6979 will take care of this; it'll be merged once the CI passes.

**Comment by adam-moss** [comment]
Heh.  I've just realised what it was :(  My bad, lesson learned 🔪

**Pull request merged**
