### PR TITLE
pdal 2.6.0

### PR DESCRIPTION
**Pull request by pomadchin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Error: Could not remove pdal keg! Do so manually:
    sudo rm -rf /opt/homebrew/Cellar/pdal/2.6.0
```

**Comment by pomadchin** [comment]
@chenrui333 before I'll go too deep; wondering how the first `Could not remove pdal keg` is connected with the next one `pdal is not linked` 🤔 or could these two errors be linked at all?

**Comment by pomadchin** [comment]
It is in progress, I'll look into it once I have some time, but any help is appreciated.

**Comment by chenrui333** [comment]
> It is in progress, I'll look into it once I have some time, but any help is appreciated.

should be covered by #160446

**Pull request closed without merging**
