### PR TITLE
vgmstream r1050

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
We've tried before, without much success: https://github.com/Homebrew/homebrew-core/pull/18913

**Comment by fxcoudert** [comment]
```
gcc -Wall -O3 -I../ext_includes -DUSE_ALLOCA -DVGM_USE_MAIATRAC3PLUS -L../src -L ../ext_libs -lvgmstream -lvorbisfile -lmpg123 -lat3plusdecoder -lpthread -lm "-DVERSION=\"`../version.sh`\"" test.c -L../src -L ../ext_libs -lvgmstream -lvorbisfile -lmpg123 -lat3plusdecoder -lpthread -lm -o vgmstream
fatal: Not a git repository (or any of the parent directories): .git
ld: library not found for -lat3plusdecoder
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by fxcoudert** [comment]
I suggest we close this, because it has 4 installs a month, and the "new version" is from 2015 anyway :)

**Pull request closed without merging**
