### PR TITLE
jsoncpp 1.9.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
../meson.build:1:0: ERROR: Unknown options: "python"
```

**Comment by carlocab** [comment]
```
Error: 15 failed steps!
brew linkage --test f3d
brew test --retry --verbose f3d
brew linkage --test lgogdownloader
brew test --retry --verbose lgogdownloader
brew linkage --test libjson-rpc-cpp
brew test --retry --verbose libjson-rpc-cpp
brew linkage --test mavsdk
brew test --retry --verbose mavsdk
brew test --retry --verbose openalpr
brew linkage --test opencv
brew test --retry --verbose opencv
brew linkage --test pcl
brew test --retry --verbose pcl
brew linkage --test vtk
brew test --retry --verbose vtk
```

@chenrui333, please only `revision` bump the `linkage` failures. We don't need to rebuild something just because the test failed:
```
f3d
lgogdownloader
libjson-rpc-cpp
mavsdk
opencv
pcl
vtk
```

**Comment by carlocab** [comment]
Failures on ARM are due to formulae no longer being skipped. Those shouldn't register as errors, though. Working on it at Homebrew/homebrew-test-bot#691.

**Comment by carlocab** [comment]
Needs rebasing after #88907.

**Pull request closed without merging**
