### PR TITLE
libuv 1.28.0

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> make man
sphinx-build -b man -d build/doctrees   src build/man
Running Sphinx v2.0.1

Exception occurred:
  File "/private/tmp/libuv-20190416-2357-kxqrsd/libuv-1.28.0/docs/src/sphinx-plugins/manpage.py", line 42, in setup
    app.info('Initializing manpage plugin')
AttributeError: 'Sphinx' object has no attribute 'info'
The full traceback has been saved in /private/tmp/sphinx-err-7bmqipoc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [man] Error 2
```

**Comment by fxcoudert** [comment]
I've filed a PR upstream, maybe we can link it: https://github.com/libuv/libuv/pull/2265

**Comment by schanzel** [comment]
Install from bottle fails right now with an `HTTP 401 Unauthorized`
```bash

$ brew upgrade
==> Upgrading 1 outdated package:
libuv 1.27.0 -> 1.28.0
==> Upgrading libuv
==> Downloading https://homebrew.bintray.com/bottles/libuv-1.28.0.mojave.bottl

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "libuv"
Download failed: https://homebrew.bintray.com/bottles/libuv-1.28.0.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by fxcoudert** [comment]
Can you retry? bintray has been having issues today: https://status.bintray.com

**Comment by schanzel** [comment]
Aye, retried it, it worked. Thank you!

**Pull request closed without merging**
