### PR TITLE
prest: rename binary name prest to prestd

### PR DESCRIPTION
**Pull request by avelino**
ref:
https://github.com/prest/prest/commit/d09190e9f628021fed768325a39b5502d8bc1964#diff-78ccd09aaa8e28464f095d37bd33e165dd0cb4c14d87892b7768754b16c70b08

Signed-off-by: Avelino <t@avelino.xxx>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@avelino maybe you can take a look at the other rename PRs?
like this one, `https://github.com/Homebrew/homebrew-core/pull/68004`

**Comment by carlocab** [comment]
Should the rename be put in `formula_renames.json`?

**Review by chenrui333 — DISMISSED** [review]
lgtm

**Comment by chenrui333** [comment]
Thanks @avelino!

**Pull request closed without merging**
