### PR TITLE
pillow: delete

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adding a pillow formula in core had been considered and rejected
multiple times in the past.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Didn't realise that, sorry for the migration

**Comment by delitestudio** [comment]
Hello, now Pillow is neither in homebrew-core nor in homebrew-science... Could you put it back in homebrew-science?

**Comment by ilovezfs** [comment]
@delitestudio please use pip.

**Comment by delitestudio** [comment]
Oh, so Pillow is no longer available on Homebrew? If I can ask: why?

**Comment by ilovezfs** [comment]
@delitestudio we generally package only Python applications not Python libraries in Homebrew.

**Comment by delitestudio** [comment]
Got it. Thank you!

**Pull request merged**
