### PR TITLE
git-imerge 1.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jasonkarns** [comment]
Can we remove the `head?` check now, since bash completion is included in v1.0?

**Comment by ilovezfs** [comment]
@jasonkarns I'm not sure I understand your question.

**Comment by jasonkarns** [comment]
https://github.com/Homebrew/homebrew-core/pull/4986/commits/309e8820d1a90d9092ee7963abcbad46c40e6e5c#diff-741b603e6c11b9dd667d77696c8fc33bR21

The inclusion of bash-completion in this formula is dependent on it being installed as `--head`. It should be unconditional.

**Comment by zmwangx** [comment]
Lol, this thing is attempting to write directly to `/etc/bash_completion.d` although `PREFIX` is not `/usr`. Guess we need an inreplace.

**Comment by ilovezfs** [comment]
I'll let someone else handle this one.

**Pull request closed without merging**
