### PR TITLE
rust 1.16.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
SHA256 issue:

```
==> Downloading https://github.com/phildawes/racer/archive/2.0.6.tar.gz
==> Downloading from https://codeload.github.com/phildawes/racer/tar.gz/2.0.6
Warning: Resource racer reports different SHA256: f6cc46e0f87e01448943e1406bdd7d548ed41dc149b1f3cf6ddb5cfcc8b24448
Downloaded to: /Users/brew/Library/Caches/Homebrew/rust--racer-2.0.6.tar.gz
SHA256: a9704478f72037e76d4d3702fe39b3c50597bde35dac1a11bf8034de87bbdc70
```

and please remove the `revision 1` line.

**Comment by alex** [comment]
Am I losing my mind?

```
/p/tmp $ curl -O https://github.com/phildawes/racer/archive/2.0.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122    0   122    0     0    723      0 --:--:-- --:--:-- --:--:--   730
/p/tmp $ sha256 2.0.6.tar.gz
SHA256(2.0.6.tar.gz)= f6cc46e0f87e01448943e1406bdd7d548ed41dc149b1f3cf6ddb5cfcc8b24448
```

**Comment by JCount** [comment]
@alex Try adding an `-L` to your `-O`, and I think you'll find your mind.

**Review by ilovezfs — DISMISSED** [review]
bootstrap will need to be updated based on stage0.txt too

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @alex :confetti_ball:

**Comment by alex** [comment]
Thanks for finishing this up!

**Comment by ilovezfs** [comment]
No problem

**Pull request closed without merging**
