### PR TITLE
fabio 1.3.1

### PR DESCRIPTION
**Pull request by magiconair**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
The checksum seems wrong. Both the CI and my local download report `9fc1ea0fafff9c077cd7465731fadceae7b85cf7e3826628fdd064419c6fd42a`.

**Comment by magiconair** [comment]
Looking.

**Comment by magiconair** [comment]
That is correct. The script that creates the PR was using `curl -s` and I must be making a mistake there. (too tired to look now) Replaced it with `wget -O-` for now and that produces the correct checksum. Sorry for the noise.

**Comment by zmwangx** [comment]
You probably need `curl -sL`, or you won't be redirected.

**Comment by magiconair** [comment]
Yep, that was it :)

**Comment by zmwangx** [comment]
Merged as 2b387af. Thank you for your contribution to Homebrew! I wrapped a few assignment operators with whitespace along the way; the cramped style hurts my eyes...

**Pull request closed without merging**
