### PR TITLE
crystal-lang 0.25.1

### PR DESCRIPTION
**Pull request by matiasgarciaisaia**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

It _may be_ that the formula is not building on El Capitan & earlier. I'd like the CI to check, but I'm not sure how we would fix this issue if it's true.

Crystal 0.25.0 can't build on El Capitan due to the missing `clock_gettime` (see #28930), but 0.24.1 won't build 0.25.1 anymore due to syntax changes (if my test was correct).

### CODE REVIEW

**Comment by matiasgarciaisaia** [comment]
@ilovezfs the build [is failing](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/26577/version=el_capitan/testReport/brew-test-bot/el_capitan/install_crystal_lang/) on El Capitan with this:

```
==> bin/crystal build -D without_openssl -D without_zlib -o .build/crystal src/compiler/crystal.cr --release --no-debug
dyld: _dyld_bind_fully_image_containing_address() error
dyld: Symbol not found: _clock_gettime
  Referenced from: /private/tmp/crystal-lang-20180628-36267-1jmhchu/crystal-0.25.1/boot/embedded/bin/crystal (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /private/tmp/crystal-lang-20180628-36267-1jmhchu/crystal-0.25.1/boot/embedded/bin/crystal
/private/tmp/crystal-lang-20180628-36267-1jmhchu/crystal-0.25.1/boot/bin/crystal: line 102: 36352 Trace/BPT trap: 5       "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

It says there's a `/private/tmp/crystal-lang-20180628-36267-1jmhchu/crystal-0.25.1/boot/embedded/bin/crystal` Crystal that was built for OSX 10.12 (aka, Sierra), but the formula is being built on El Capitan.

Do you know _where_ does that boot version come from?

May it be that homebrew's build process is caching the same boot version for every platform instead of using a different one for each platform?

**Comment by matiasgarciaisaia** [comment]
I was able to build Crystal `master` (b782738, the same as 0.25.1) using the `brew`-provided Crystal 0.25.0 on a El Capitan Vagrantbox just OK.

**Comment by ilovezfs** [comment]
@matiasgarciaisaia can upstream provide a bootstrap binary built on <= macOS 10.11 (or built on newer macOS but with clock_gettime force disabled during the build)?

**Comment by matiasgarciaisaia** [comment]
Thanks for the help, @ilovezfs!

That's what we're trying to get. It's a bit funny, because we're [explicitly trying to avoid `clock_gettime` in darwin](https://github.com/crystal-lang/crystal/blob/f3168b6be999dc10e7b63fa2281e7d9265087609/src/crystal/system/unix/time.cr#L5-L10), but it seems to get linked anyway.

Those binaries are built on CircleCI, which I haven't found to provide older versions of macOS than Sierra. But we're investigating 👍

**Comment by bcardiff** [comment]
@ilovezfs i think we got it, the culprit was the config of libevent and the missing of --disable-clock-gettime , meanwhile now the build process also sets MACOSX_DEPLOYMENT_TARGET=10.11

Can I ask you to test if the following re packed version of 0.25.0 is able to build on your end the 0.25.1 compiler?
https://8516-6887813-gh.circle-artifacts.com/0/dist_packages/crystal-0.25.0-2-darwin-x86_64.tar.gz

If so, we can publish that on github, and also publish a 0.25.1-2 for when the next compiler comes.

**Comment by ilovezfs** [comment]
@bcardiff https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/26644/

**Comment by bcardiff** [comment]
Thanks! Once it passes we will give that asset a proper url.
I found lots of issues with your name and _clock_gettime

**Comment by ilovezfs** [comment]
@bcardiff yes, I have some serious clock_gettime PTSD. We even gave it its own label https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+label%3Aclock_gettime+is%3Aclosed

**Comment by asterite** [comment]
@bcardiff Amazing detective work! 🎉 

It seems the build passed :-)

**Comment by matiasgarciaisaia** [comment]
I've updated the formula to use the official, patched 0.25.0 binaries - we're More Than Good To Go™ now 👌

Thanks for all the support, @ilovezfs 💙

**Comment by ilovezfs** [comment]
@matiasgarciaisaia you're welcome! I'll try to get this merged before we freeze Homebrew/homebrew-core for the rest of the day due to https://github.com/Homebrew/homebrew-core/pull/29490

**Comment by ilovezfs** [comment]
Shipped! Thanks for the upgrade @matiasgarciaisaia

**Comment by asterite** [comment]
@ilovezfs Thank you!

Totally unrelated to this issue: the formula is called `crystal-lang` because back then there was a competing `crystal` formula, which doesn't exist anymore (probably the tool was abandoned). Would it be good to rename this formula to `crystal`? It doesn't have to be now, but I don't know what's the process to rename a formula. In most other distributions we are using the name `crystal` and not `crystal-lang`.

**Comment by ilovezfs** [comment]
@asterite the competing formula was itself renamed https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json#L33 so if that entry is removed from formula_renames it should be safe for crystal-lang to be renamed to crystal.

**Comment by Sija** [comment]
@matiasgarciaisaia Shouldn't [0.25.1 release files](https://github.com/crystal-lang/crystal/releases/tag/0.25.1) for macOS be updated as well?

**Pull request closed without merging**
