### PR TITLE
jsoncpp 1.9.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>[1.9.6: Bug fixes, optimizations, infrastructure changes](https://github.com/open-source-parsers/jsoncpp/releases/tag/1.9.6)

This release includes several important bug fixes and security fixes, as well as various infrastructure changes and cleanup.

## What's Changed
* Parse large floats as infinity (#1349) by @terokinnunen in https://github.com/open-source-parsers/jsoncpp/pull/1353
* Fix various typos by @luzpaz in https://github.com/open-source-parsers/jsoncpp/pull/1350
* Use default rather than hard-coded 8 for maximum aggregate member alignment by @jrtc27 in https://github.com/open-source-parsers/jsoncpp/pull/1378
* Fix wrong usage of doxygen groups by @mwestphal in https://github.com/open-source-parsers/jsoncpp/pull/1417
* feat: adds front and back methods to Value type by @jwidauer in https://github.com/open-source-parsers/jsoncpp/pull/1458
* Avoid using cmake glob vars if we are a subproject v2 by @nkh-lab in https://github.com/open-source-parsers/jsoncpp/pull/1459
* Create meson_build_and_run by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1553
* Fix clang format issues by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1555
* Delete .travis.yml by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1557
* Delete .travis_scripts directory by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1556
* add comment space directive by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1558
* Clang format updates by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1560
* Update meson.yml by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1554
* Fix a parser bug where tokens are misidentified as commas. by @vslashg in https://github.com/open-source-parsers/jsoncpp/pull/1502
* Fix out-of-bounds read. by @vslashg in https://github.com/open-source-parsers/jsoncpp/pull/1503
* Fix asserts in Value::setComment by @vslashg in https://github.com/open-source-parsers/jsoncpp/pull/1445
* add a valueToQuotedString overload  by @phlptp in https://github.com/open-source-parsers/jsoncpp/pull/1397
* Add code coverage by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1561
* Update meson.yml by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1562
* build(meson): use find_program('python3') by @Tachi107 in https://github.com/open-source-parsers/jsoncpp/pull/1386
* Bump CMake policy version to avoid deprecation warning by @roehling in https://github.com/open-source-parsers/jsoncpp/pull/1499
* Update link in amalgamate.py to GitHub by @NotWearingPants in https://github.com/open-source-parsers/jsoncpp/pull/1335
* CharReader: Add StructuredError by @martinduffy1 in https://github.com/open-source-parsers/jsoncpp/pull/1409
* Fix configure Clang on Windows by @TsynkPavel in https://github.com/open-source-parsers/jsoncpp/pull/1480
* Fixed setting JSONCPP_USE_SECURE_MEMORY definition by @TsynkPavel in https://github.com/open-source-parsers/jsoncpp/pull/1479
* Update readFromString.cpp print error by @gnudles in https://github.com/open-source-parsers/jsoncpp/pull/1477
* Add security policy by @pnacht in https://github.com/open-source-parsers/jsoncpp/pull/1484
* CMake: remove ccache micro management by @SpaceIm in https://github.com/open-source-parsers/jsoncpp/pull/1448
* Create cmake.yml by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1563
* Update meson.yml by @baylesj in https://github.com/open-source-parsers/jsoncpp/pull/1564
* Move removeIndex's result instead of copying by @jedav in https://github.com/open-source-parsers/jsoncpp/pull/1516
* Use current source / binary dir when assuring out of source builds by @appgurueu in https://github.com/open-source-parsers/jsoncpp/pull/1527
* Opportunistically take advantage of C++20 move-in/out-of stringstream by @beevvy in https://github.com/open-source-parsers/jsoncpp/pull/1457
* Protect target JsonCpp::JsonCpp against multi-include by @rjoomen in https://github.com/open-source-parsers/jsoncpp/pull/1435
* Don't use build dir build interfaces - Fix use with CMake FetchContent by @matthieugleg in https://github.com/open-source-parsers/jsoncpp/pull/1528
* Create a jsoncppConfig.cmake file, even if building under meson by @wdouglass in https://github.com/open-source-parsers/jsoncpp/pull/1486
* include/json/value.h is changed by @KeremTAN in https://github.com/open-source-parsers/jsoncpp/pull/1462
* meson.build: fix the version number by @heitbaum in https://github.com/open-source-parsers/jsoncpp/pull/1432
* Introduce CharReaderBuilder::ecma404Mode by @axic in https://github.com/open-source-parsers/jsoncpp/pull/1333
* cmake export configuration: allow repeating find_package(jsoncpp) calls by @zeroxia in https://github.com/open-source-parsers/jsoncpp/pull/1491
* Added Value::find with String key by @petukhovtd in https://github.com/open-source-parsers/jsoncpp/pull/1467
* Don't use build dir build interfaces by @Scotty1701 in https://github.com/open-source-parsers/jsoncpp/pull/1419

## New Contributors
* @terokinnunen made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1353
* @jrtc27 made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1378
* @mwestphal made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1417
* @jwidauer made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1458
* @nkh-lab made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1459
* @vslashg made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1502
* @phlptp made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1397
* @Tachi107 made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1386
* @roehling made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1499
* @NotWearingPants made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1335
* @martinduffy1 made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1409
* @TsynkPavel made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1480
* @gnudles made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1477
* @pnacht made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1484
* @jedav made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1516
* @appgurueu made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1527
* @beevvy made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1457
* @rjoomen made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1435
* @matthieugleg made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1528
* @wdouglass made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1486
* @KeremTAN made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1462
* @heitbaum made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1432
* @zeroxia made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1491
* @petukhovtd made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1467
* @Scotty1701 made their first contribution in https://github.com/open-source-parsers/jsoncpp/pull/1419

**Full Changelog**: https://github.com/open-source-parsers/jsoncpp/compare/1.9.5...1.9.6</pre>
</details>

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
  -- All plugins enabled
  CMake Error at /home/linuxbrew/.linuxbrew/lib/cmake/jsoncpp/jsoncppConfig.cmake:27 (check_required_components):
    Unknown CMake command "check_required_components".
  Call Stack (most recent call first):
    src/cmake/Modules/Findjsoncpp.cmake:1 (find_package)
    src/mavsdk/CMakeLists.txt:9 (find_package)
```

**Comment by chenrui333** [comment]
- https://github.com/open-source-parsers/jsoncpp/issues/1568

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
- https://github.com/Homebrew/brew/pull/18364

**Review by carlocab — APPROVED** [review]
Failure is a `test-bot` bug.

**Comment by carlocab** [comment]
#191155

**Comment by carlocab** [comment]
Needs rebase.

**Comment by carlocab** [comment]
Dependent failures will be fixed by Homebrew/homebrew-test-bot#1231

**Review by carlocab — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
Failure due to missing bottle attestation for `libfuse@2`.

**Pull request merged**
