### PR TITLE
blitz: depend on python@2 at build time for head

### PR DESCRIPTION
**Pull request by slayoo**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Apologies, but hard to match all above expectations not being an OSX user, but still hope this will help!

For more discussion on the issue, see: https://github.com/blitzpp/blitz/pull/31

For an example fail case log, see: https://travis-ci.org/igfuw/libmpdataxx/jobs/388702067

### CODE REVIEW

**Comment by ilovezfs** [comment]
Is the `python2` executable really only needed at build time not also at run time?

**Comment by slayoo** [comment]
Yes, here is how it is used within Makefiles to generate C++ headers that are installed upon "make install":
https://github.com/blitzpp/blitz/commit/7b34d1894d8c6e2292919e7749715ab895318576

**Comment by slayoo** [comment]
btw, there is also a need to upgrade the blitz package - there are 2 new releases since the one used in the formula file. Plus, the project has moved from SF to github which is not reflected in the formula metadata.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @slayoo! You're awesome.

>btw, there is also a need to upgrade the blitz package - there are 2 new releases since the one used in the formula file. Plus, the project has moved from SF to github which is not reflected in the formula metadata.

Feel free to open a PR for the upgrade!

**Comment by slayoo** [comment]
Thanks!

**Comment by ilovezfs** [comment]
You're welcome!

**Pull request merged**
