### PR TITLE
gutenberg: rename to zola

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Upstream has changed their name from `gutenberg` to `zola`. Could you follow [this guideline](https://docs.brew.sh/Rename-A-Formula) to rename the formula?

**Comment by igas** [comment]
`brew cleanup --prune=7` failed but I don't think it's related

**Comment by igas** [comment]
Failed on `brew cleanup --prune=7` the rest is ok.

@Moisan I followed the guide and bot comments. Why a new formula should not have a head?

Thanks.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @igas!

**Pull request closed without merging**
