### PR TITLE
choose-gui: delete

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Any chance of a status update on `choose-gui` here @sdegutis? It's 404.

### CODE REVIEW

**Comment by sb-js** [comment]
It is? Dang hmm let me take a look...

**Comment by sdegutis** [comment]
Sorry about that @DomT4. It should be fixed now. Can you verify?

**Comment by sdegutis** [comment]
As far as 404, it should be fixed now. As far as status: it's still working and there's no new version updates because it's Feature Complete™ and Bug Free®. I remember reading that this can sometimes be grounds for a formula to be removed from Homebrew. If that's the case, remove it as you see fit.

**Comment by DomT4** [comment]
> I remember reading that this can sometimes be grounds for a formula to be removed from Homebrew.

As long as it's still available and still builds it's more than okay to keep existing with me. Just wasn't sure where things stood re the 404, so seemed easiest to prepare a PR & gently ping you into it. Thanks for the quick fix here! The formula lives on 😄.

**Comment by sdegutis** [comment]
The 404 was my fault, I have been removing my repos since people have been migrating away from all my software projects. I didn't realize choose was used by anyone and forgot it was in homebrew.

**Comment by DomT4** [comment]
94 known installations in the last year, FWIW. Could be more than that, given obviously Homebrew is only aware of the number where people haven't disabled analytics.

**Comment by sdegutis** [comment]
Cool, thanks for those stats.

**Pull request closed without merging**
