### PR TITLE
grafana 6.5.1

### PR DESCRIPTION
**Pull request by hugohaggmark**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Not related fails (https://github.com/Homebrew/homebrew-test-bot/issues/301): 
```
Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/libfuseprivate.0.dylib
  /usr/local/lib/libfuseprivate.dylib
```

**Comment by hugohaggmark** [comment]
@chenrui333 @bayandin  please advice what I should do to make this pass

**Comment by bayandin** [comment]
It's nothing you need to worry about, this error is not related to your changes and this PR will be merged.

Thanks for your contribution :+1: :tada:

**Comment by chenrui333** [comment]
Thanks @hugohaggmark!!

**Pull request closed without merging**
