### PR TITLE
coccinelle 1.0.7

### PR DESCRIPTION
**Pull request by batbyR**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Doesn't seem to like the sandbox:

```
[ERROR] The compilation of ocaml-system failed at "/private/tmp/coccinelle-20191009-58357-17lzefl/coccinelle-1.0.7/opamroot/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml".

#=== ERROR while compiling ocaml-system.4.08.1 ================================#
# context              2.0.5 | macos/x86_64 |  | https://opam.ocaml.org#af3b9ec7
# path                 /private/tmp/coccinelle-20191009-58357-17lzefl/coccinelle-1.0.7/opamroot/default/.opam-switch/build/ocaml-system.4.08.1
# command              /private/tmp/coccinelle-20191009-58357-17lzefl/coccinelle-1.0.7/opamroot/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml
# exit-code            71
# env-file             /private/tmp/opam-brew-58373/ocaml-system-58373-548b09.env
# output-file          /private/tmp/opam-brew-58373/ocaml-system-58373-548b09.out
### output ###
# sandbox-exec: sandbox_apply_container: Operation not permitted
```

One solution could be to pass `--disable-sandboxing`

**Comment by alebcay** [comment]
Saw the same error with `hyperkit` a while ago, documented in https://github.com/Homebrew/homebrew-core/issues/39680. The PR that fixed it is #41057.

**Comment by alebcay** [comment]
`coccinelle` 1.0.8 is now available.

**Comment by fxcoudert** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
