### PR TITLE
dte 1.6 (new formula)

### PR DESCRIPTION
**Pull request by yumitsu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yumitsu** [comment]
`dte` is a successor to [dex](https://github.com/tihirvon/dex) as dex is dead as nail for 2+ years.

**Comment by vinyldarkscratch** [comment]
@yumitsu `dte` seems pretty nice, I'd love to see this merged!  It's kind of funny, though: what the brew bot is saying is that `dte` isn't popular enough.  I would personally say that it's good, but let's see what the maintainers decide on?

**Comment by yumitsu** [comment]
@vinyldarkscratch I hope they will accept it, `dte` is really cool and is in active development.

**Comment by fxcoudert** [comment]
It's not a judgment on the quality of the project, but we have to draw the line somewhere :) There is just too much code out there that could be potentially integrated in Homebrew, and we can't maintain it centrally.

That's why brew is not limited to homebrew-core, and you can very easily host the formula in a personal tap: https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md  We recommend that for now, and when it is more widely used you can come back to us and we'll be happy to revisit!

**Comment by craigbarnes** [comment]
So can this be re-opened if it gets 17 more stars? :smile:

**Pull request closed without merging**
