### PR TITLE
python3: Added dtrace support to python 3

### PR DESCRIPTION
**Pull request by mraspberry**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you elaborate on why this is useful and needed?

**Comment by nixalot** [comment]
dtrace is a dynamic instruction framework ported to OS X years ago by Apple. Python 3.6 added dtrace probes into CPython so you can dynamically instrument the python interpreter. This eases developer's lives, especially if they develop C extensions or contribute to CPython

**Comment by ilovezfs** [comment]
I think this merits a revision bump unless we're adding it as an option. :+1: to making it non-optional though.

**Comment by MikeMcQuaid** [comment]
Yeh, if there's no negative consequences 👍 to revision bump and non-optional.

**Comment by nixalot** [comment]
revision bumped. That look right?

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thank you very much @nixalot for your contribution!

**Comment by nixalot** [comment]
No problem! Thanks for making it a pleasant experience!

**Comment by DanThomson** [comment]
I'm pretty sure this broke building python3 from source. The formula seems to have the output of git diff appended to the end. I've copied the [python3 formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/python3.rb) starting at line 355 below.
```ruby
__END__
diff --git a/setup.py b/setup.py
index 2779658..902d0eb 100644
--- a/setup.py
+++ b/setup.py
@@ -1699,9 +1699,6 @@ class PyBuildExt(build_ext):
         # Rather than complicate the code below, detecting and building
         # AquaTk is a separate method. Only one Tkinter will be built on
         # Darwin - either AquaTk, if it is found, or X11 based Tk.
-        if (host_platform == 'darwin' and
-            self.detect_tkinter_darwin(inc_dirs, lib_dirs)):
-            return

         # Assume we haven't found any of the libraries or include files
         # The versions with dots are used on Unix, and the versions without
@@ -1747,22 +1744,6 @@ class PyBuildExt(build_ext):
             if dir not in include_dirs:
                 include_dirs.append(dir)

-        # Check for various platform-specific directories
-        if host_platform == 'sunos5':
-            include_dirs.append('/usr/openwin/include')
-            added_lib_dirs.append('/usr/openwin/lib')
-        elif os.path.exists('/usr/X11R6/include'):
-            include_dirs.append('/usr/X11R6/include')
-            added_lib_dirs.append('/usr/X11R6/lib64')
-            added_lib_dirs.append('/usr/X11R6/lib')
-        elif os.path.exists('/usr/X11R5/include'):
-            include_dirs.append('/usr/X11R5/include')
-            added_lib_dirs.append('/usr/X11R5/lib')
-        else:
-            # Assume default location for X11
-            include_dirs.append('/usr/X11/include')
-            added_lib_dirs.append('/usr/X11/lib')
-
         # If Cygwin, then verify that X is installed before proceeding
         if host_platform == 'cygwin':
             x11_inc = find_file('X11/Xlib.h', [], include_dirs)
@@ -1786,10 +1767,6 @@ class PyBuildExt(build_ext):
         if host_platform in ['aix3', 'aix4']:
             libs.append('ld')

-        # Finally, link with the X11 libraries (not appropriate on cygwin)
-        if host_platform != "cygwin":
-            libs.append('X11')
-
         ext = Extension('_tkinter', ['_tkinter.c', 'tkappinit.c'],
                         define_macros=[('WITH_APPINIT', 1)] + defs,
                         include_dirs = include_dirs,
```

**Comment by fxcoudert** [comment]
The data at the end of the formula is expected, it's a patch that we apply (with the following line: `patch :DATA if build.with? "tcl-tk"`). If the build is broken for you, can you open an issue and report it, including all necessary diagnostics? Thanks

**Pull request closed without merging**
