### PR TITLE
metricbeat 7.8.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@chrmoritz ideas?

**Comment by chrmoritz** [comment]
They've updated the build system of this `beat` too in 7.8.0. Taking a look now.

**Comment by chrmoritz** [comment]
https://github.com/chrmoritz/homebrew-core/commit/e928c7701076e613552dc9a14217f81ae805187e fixes the build issue, however I'm not sure yet how we should prevent downloading binary wheels now with the new build system.

**Comment by chenrui333** [comment]
Going to close this PR in favor of #57340.

**Pull request closed without merging**
