### PR TITLE
mame 0.225

### PR DESCRIPTION
**Pull request by WorkInProgress-Development**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mbcoguno** [comment]
```patch
@@ -57,7 +58,7 @@ class Mame < Formula
     bin.install "mame64" => "mame"
     cd "docs" do
       # We don't convert SVG files into PDF files, don't load the related extensions.
-      inreplace "source/conf.py", "'sphinxcontrib.rsvgconverter'", ""
+      inreplace "source/conf.py", "'sphinxcontrib.rsvgconverter',", ""
       system "make", "text"
       doc.install Dir["build/text/*"]
       system "make", "man"
```

**Comment by WorkInProgress-Development** [comment]
Thanks for providing that fix, @mbcoguno.

**Comment by miccal** [comment]
@WorkInProgress-Development please squash your commits into one with the message `mame 0.225`, thank you.

**Comment by WorkInProgress-Development** [comment]
Could I please have some help with this? I accidentally merged my branch into itself, creating an additional commit, and I'd rather not do anything else without checking, so I don't end up making things worse.

**Comment by Rylan12** [comment]
@WorkInProgress-Development you're looking for the `git rebase -i` command rather than `git merge`.

Take a look at [this part of the docs](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#following-up) for some brief instructions

**Review by SMillerDev — APPROVED** [review]
Thanks @WorkInProgress-Development  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
