### PR TITLE
flyctl 0.0.446

### PR DESCRIPTION
**Pull request by flyio-buildbot**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]

**Comment by p-linnane** [comment]
@superfly @michaeldwan Can you please rebase this? This was opened before 0.0.445 was merged.

**Comment by chenrui333** [comment]
let's just wait the new release instead.

**Comment by chenrui333** [comment]
#120417

**Comment by chenrui333** [comment]
> let's just wait the new release instead.

There is also a discussion on this in this PR, https://github.com/Homebrew/homebrew-core/pull/114123

**Pull request closed without merging**
