### PR TITLE
openjdk 21.0.3

### PR DESCRIPTION
**Pull request by WangEdward**
bump openjdk to 21.0.3 https://github.com/Homebrew/homebrew-core/pull/168294#issuecomment-2061101373

BrewTestBot could not bump it because the existence of #168294

### CODE REVIEW

**Comment by cho-m** [comment]
Need to wait for https://github.com/Homebrew/brew/pull/17149 to fix Linux run.

**Comment by calvinit** [comment]
> Need to wait for [Homebrew/brew#17149](https://github.com/Homebrew/brew/pull/17149) to fix Linux run.

Now it seems that this work has been completed. Is there any way to trigger the check actions without committing? @cho-m @WangEdward

**Comment by fxcoudert** [comment]
- macOS 12-x86_64 ran in 18 hours
- macOS 13-x86_64 ran in 14 hours
- macOS 14-x86_64 has spent more than two days, and it's still stuck at `c` (`carrot2`, specifically). I'm cancelling that job.

**Comment by WangEdward** [comment]
CI result: https://github.com/Homebrew/homebrew-core/actions/runs/8885577698

Build related issues:
- `pkl` on arm machines
- `jsvc` on macOS 14-arm64
- `bigloo` on macOS 14-x86_64

**Comment by chenrui333** [comment]
IMO, I think we have enough CI data/info to move this PR forward

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
