### PR TITLE
jdtls 1.32.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
@Homebrew/core Any ideas on incorporating the date in the tarball url as part of the version? Bumping this always fails because it fetches a nonexistent page and uses that hash, which obviously doesn't work until we manually correct the date.

**Comment by Bo98** [comment]
There's many formulae where you have to specify `--url` manually. Does the nonexistent URL not 404? Seems like a bug in `brew bump` if it is allowing dead URLs to be submitted as it shouldn't be doing that.

**Comment by Bo98** [comment]
Try add `&nf=1` to the end of the URL.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> Created by `brew bump`
> 
> Created with `brew bump-formula-pr`.

technically, that `brew bump` wont work for such PR.

**Pull request merged**
