### PR TITLE
scala 2.12.3

### PR DESCRIPTION
**Pull request by a10y**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by a10y** [comment]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5489/version=sierra/console

This looks like a flake of the sierra build?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @a10y for the pull request! Homebrew exists thanks to people like you!

**Pull request merged**
