### PR TITLE
[nats-streaming] Release v0.11.0

### PR DESCRIPTION
**Pull request by kozlovic**
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.11.0)

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks for your contribution @kozlovic ! The next time you submit a PR can you please make the commit message adhere to the standard format ? It should look like this `nats-streaming-server 0.11` without any additional info in the message it self. Thanks!

**Comment by javian** [comment]
@kozlovic no problem and thanks ^^

**Comment by kozlovic** [comment]
@javian Actually, you say commit message should be `nats-streaming-server 0.11.0`. Our github tag is `v0.11.0` (notice the `v`). So should it be the actual tag name or simply the version it represents, like here `0.11.0`?

**Comment by javian** [comment]
@kozlovic just the version without the `v´ prefix

**Pull request closed without merging**
