### PR TITLE
mmseqs2 14-7e284

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by fxcoudert** [comment]
We probably want to update the `documentation`

**Comment by Porkepix** [comment]
> We probably want to update the `documentation`

Documentation seems now to be distributed differently: there isn't a dedicated repo anymore, and user have to use the GitHub wiki (https://github.com/soedinglab/MMseqs2/wiki) or a PDF (https://github.com/soedinglab/MMseqs2/releases/download/14-7e284/userguide.pdf) in which case I don't know what's the policy here, and if it's a PDF how should it be distributed. In the case of the second choice though, maybe can it be automatically updated by `brew bump` too?

I also noticed there are tests done through a resource called `testdata`, here being two versions late (those comes from version 12) but those are not yet available from this version's assets. It's available from previous version (current one), but was released later on (2 to 3 weeks later), will it be the case here, I don't know?

**Comment by milot-mirdita** [comment]
Documentation still the same as before. The PDF is generated from the wiki and is just there as a convenience.
The new hash for the documentation should be `4cd4a50c83d72dc60d75dc79afe1b9b67b5e775d`.

`testdata` is also fine to remain as-is. It's a very reduced set from the full regression suite to fit better into hombrew's CI. It doesn't need updating.

**Comment by Porkepix** [comment]
> Documentation still the same as before. The PDF is generated from the wiki and is just there as a convenience. The new hash for the documentation should be `4cd4a50c83d72dc60d75dc79afe1b9b67b5e775d`.

How do you find this hash? Also asking because I was following the repository url and it lead to a 404.
> 
> `testdata` is also fine to remain as-is. It's a very reduced set from the full regression suite to fit better into hombrew's CI. It doesn't need updating.

I noticed https://github.com/soedinglab/MMseqs2/releases/download/13-45111/MMseqs2-Regression.zip which seems named the same way as the one from release 12, so it's not a reduced set the same that could be used? And why is there no set for latest release?

**Comment by milot-mirdita** [comment]
It's this one: https://github.com/soedinglab/MMseqs2/wiki/Home/4cd4a50c83d72dc60d75dc79afe1b9b67b5e775d

Every github wiki is backed by a hidden git repository (In this case https://github.com/soedinglab/MMseqs2.wiki.git). The commit is part of that repository.

Regarding the regression zip, uhhh I just forgot about it, but that one is not reduced and would require ~20 minutes to run in the CI.

**Comment by Porkepix** [comment]
> Every github wiki is backed by a hidden git repository (In this case [soedinglab/MMseqs2.wiki.git](https://github.com/soedinglab/MMseqs2.wiki.git)). The commit is part of that repository.

Yes but it doesn't tell me how do you find the relevant commit id? (And also, why this repo doesn't seems to be accessible from GitHub's Web interface?)

> Regarding the regression zip, uhhh I just forgot about it, but that one is not reduced and would require ~20 minutes to run in the CI.

When you say that one, you mean current version 12 already shipped? The one with version 13?
Because I see that version 12 have one named "Regression-minimal", but that's not the one used here. I also see you just added a regression zip for version 14.

**Comment by milot-mirdita** [comment]
> Yes but it doesn't tell me how do you find the relevant commit id? (And also, why this repo doesn't seems to be accessible from GitHub's Web interface?)

You can see the git commit hashes here in the web interface: https://github.com/soedinglab/MMseqs2/wiki/Home/_history
GitHub doesn't offer a "normal" git web interface to wiki's, just their wiki view. I don't know why they don't.

> When you say that one, you mean current version 12 already shipped? The one with version 13?
Because I see that version 12 have one named "Regression-minimal", but that's not the one used here. I also see you just added a regression zip for version 14.

I uploaded the full regression for 14. The minimal one I built for 12 should be remain the one used in Homebrew.

**Comment by Porkepix** [comment]
> You can see the git commit hashes here in the web interface: [soedinglab/MMseqs2/wiki/Home/_history](https://github.com/soedinglab/MMseqs2/wiki/Home/_history) GitHub doesn't offer a "normal" git web interface to wiki's, just their wiki view. I don't know why they don't.

Okay, thanks for the explanations, pushed with an updated hash.
 
> > When you say that one, you mean current version 12 already shipped? The one with version 13?
> > Because I see that version 12 have one named "Regression-minimal", but that's not the one used here. I also see you just added a regression zip for version 14.
> 
> I uploaded the full regression for 14. The minimal one I built for 12 should be remain the one used in Homebrew.

The minimal version do require additional manual work? Because otherwise I guess always have one distributed with the release would be better (I hesitated to add a comment about keep using latest available minimal one, but finally didn't).
Thanks for the feedback.

**Comment by Porkepix** [comment]
`10.15` job doesn't seems to pickup, might need a rerun.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
