### PR TITLE
poppler 20.12.1

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`diff-pdf` revision bump

**Comment by fxcoudert** [comment]
```
configure: error: Package requirements (poppler-cairo >= 0.10 poppler-glib >= 0.10 cairo-pdf) were not met:
No package 'poppler-cairo' found
```

**Comment by miccal** [comment]
Thank you (as always) for your help @fxcoudert, it is very much appreciated.

**Comment by fxcoudert** [comment]
poppler-cairo was removed from poppler: https://github.com/vslavik/diff-pdf/pull/69

**Comment by aried3r** [comment]
> For diff-pdf we should apply this patch: [vslavik/diff-pdf@00fd9ab](https://github.com/vslavik/diff-pdf/commit/00fd9ab8bf435658616f3f25b18d51b0a7ee5769)

Is this something that needs to happen in this PR or is it a separate one? I'd love to help out since I am also facing issues using `diff-pdf` right now and would like to get it working again. :)

**Comment by fxcoudert** [comment]
@aried3r I've updated the pull request, that should fix it

**Comment by aried3r** [comment]
Oh wow, thank you! That was much faster than anticipated.

**Comment by carlocab** [comment]
10.14
```
Error: 1 failed steps!
brew install --verbose --build-bottle diff-pdf
```

**Comment by fxcoudert** [comment]
My bad…

**Pull request closed without merging**
