### PR TITLE
mlt: add more effects for kdenlive

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Are all these runtime dependencies?

**Comment by yurikoles** [comment]
> Are all these runtime dependencies?

It seems to be true, e.g. in [ArchLinux PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/mlt) they are listed in both `makedepends` and `optdepends`. This means that this extra functionality will be unavailable in runtime if they are absent.

**Comment by yurikoles** [comment]
@deftdawg one possible way to change dependencies for next version is by putting them in `head` block.

**Comment by SMillerDev** [comment]
Please reword the commit to the standard format and we can merge this

**Comment by yurikoles** [comment]
> Please reword the commit to the standard format and we can merge this

you mean message?

**Comment by SMillerDev** [comment]
Commit message yeah, something like: `mlt: add more effects for kdenlive`

**Comment by yurikoles** [comment]
@SMillerDev done.

**Review by SeekingMeaning — APPROVED** [review]
Thanks again for your contribution to Homebrew/core! 🌟

**Comment by ryanmaclean** [comment]
No luck getting this back in by chance? Can I help at all?

**Pull request closed without merging**
