### PR TITLE
fluidsynth: add static lib

### PR DESCRIPTION
**Pull request by jeroen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

No revision bump needed because this only adds a file to the bottle, no other changes.

Some precedents: https://github.com/Homebrew/homebrew-core/pulls?q=static+is%3Apr+author%3Ajeroen+is%3Aclosed

### CODE REVIEW

**Comment by iMichka** [comment]
Is there any reason you need the static library?

Per our policy, we do not like shipping static libraries: https://docs.brew.sh/Acceptable-Formulae#static-libraries

I see that some precedents were accepted before, but maybe the maintainers that accepted this were not aware of the policy or had their reasons to merge the changes you made. CC @p-linnane @chenrui333 @SMillerDev

We might have to revert some of the latest changes (and maybe enforce our policy with a test-bot check in the long run).

**Comment by SMillerDev** [comment]
I've only reviewed a PR that claimed to add back lost libraries. I agree that we shouldn't add static libraries against our policy just because they were accepted for another piece of software.

**Comment by jeroen** [comment]
We heavily rely on homebrew static libraries in the R programming language, in order to build standalone R binary packages. These are builds of the R bindings that are fully standalone and are distributed to end-users that do no thave homebrew or dynamic libraries on their machine. I think many other people use static libraries in a similar way.

We have been using this for at least 6 or 7 years, this policy has never been pointed out. Is this policy new? I agree with the policy that you should not have formula that have _only_ a static library, but that is not what we do. We just build and add the static library file as an extra for people that need it.

Adding a static library file to the package (in addition to the standard shared libraries) does not have any side effects. The linker will always prefer the dynamic libraries. Linux distributions do the same.

**Comment by jeroen** [comment]
> If this is always true 100% of the time: I'd love to see some solid evidence for this and would consider adapting our policy.

You can easily test it using any formula that has both shared and static libs. Let's take openssl, here is a test program:

```c
#include <openssl/ssl.h>
int main(int argc, char *argv[]) {
  SSL_library_init();
  printf("This is %s\n", OPENSSL_VERSION_TEXT);
}
```

Compile and confirm that the executable is linked to the the shared openssl library:

```
clang test.c $(pkg-config --cflags --libs openssl)
otool -L a.out
```

Here `otool` output shows the executable is linked to `libssl.dylib`. Also note that the `a.out` program is small (only 32k).

The way to force static linking is to specify the full path to the static libraries, for example:

```
clang test.c $(pkg-config --cflags openssl) /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a 
otool -L a.out
```

You will confirm that it is statically linked from the output of otool, but also because `a.out` is much bigger (about 5MB) because it contains the full openssl lib statically linked.

But you will see that it is impossible to make clang/ld link to the static library without explicitly specifying the path to the static libs; the linker will always prefer the dynamic library if one exists.

**Comment by MikeMcQuaid** [comment]
> Compile and confirm that the executable is linked to the the shared openssl library:

That's using a single version of `clang` on macOS. Is this behaviour consistent across many versions of `clang` and `gcc` and Linux? CC @fxcoudert for GCC thoughts/knowledge here too.

> But you will see that it is impossible to make clang/ld link to the static library without explicitly specifying the path to the static libs; the linker will always prefer the dynamic library if one exists.

How does e.g. `cmake` and other build systems handle this?

**Comment by SMillerDev** [comment]
The comments so far ignore the reason the rule exists AFAIK: Static libraries can not be updated unless the source is recompiled. Meaning that Homebrew can ship a critical update to the OpenSSL library in the example above, but it would never be used unless the user does an additional step to a `brew upgrade`.

**Comment by jeroen** [comment]
> The comments so far ignore the reason the rule exists AFAIK: Static libraries can not be updated unless the source is recompiled. Meaning that Homebrew can ship a critical update to the OpenSSL library in the example above, but it would never be used unless the user does an additional step to a brew upgrade.

Yes this is the deliberate choice that we make when static compiling. But because the default is shared linking, this is not a concern for homebrew, only for people that build external static applications.

**Comment by fxcoudert** [comment]
> The linker will always prefer the dynamic libraries.

Yes @MikeMcQuaid that is, I believe, always true.

**Comment by MikeMcQuaid** [comment]
Given what @jeroen and @fxcoudert have said: I think we should change our policy (starting with this PR) and ship static libraries more often. Ultimately, this makes Homebrew more useful to our consumers and won't cause problems for us unless we start specifying static linking explicitly (which we aren't going to and shouldn't do).

**Comment by jeroen** [comment]
Thanks! This is what [Debian packaging policy](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#s-sharedlibs-static) says:

Screenshot 2024-02-13 at 16 19 47

**Comment by MikeMcQuaid** [comment]
Have opened a PR in https://github.com/Homebrew/brew/pull/16656 to update the guidance. Will happily ✅ here once we've merged (or at least approved) that.

**Review by MikeMcQuaid — APPROVED** [review]

**Pull request merged**
