### PR TITLE
boost: add zstd and lzma support

### PR DESCRIPTION
**Pull request by pettyalex**
Update formula to depend on xz and zstd, allowing boost::iostreams to use zstd and lzma. This matches how boost is distributed on Debian and other major linux distros, making software that depends on boost zstd or lzma support easier to build and work with via Homebrew.

I was surprised earlier this week when my homebrew-installed Boost was not linked against zstd and lzma, which are present in most boost distributions. After making these changes and running all of the brew tests, I also tested them locally by successfully using `boost::iostreams::zstd_compressor()`. Here's the otool output, validating that this change causes boost to be linked against these:

```
otool -L /opt/homebrew/lib/libboost_iostreams.dylib
/opt/homebrew/lib/libboost_iostreams.dylib:
	/opt/homebrew/opt/boost/lib/libboost_iostreams.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
	/opt/homebrew/opt/xz/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
	/opt/homebrew/opt/zstd/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

The downsides of this change would be that installing boost brings along not just the liblzma and libzstd libraries, but also the zstd and xz executable. However, boost is huge already, so I don't feel this is a problem.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
> I also tested them locally by successfully using `boost::iostreams::zstd_compressor()`.

Can we update the `test` block to do something like this?

**Comment by pettyalex** [comment]
The thought crossed my mind, but we'd need to link the test.cpp against the libboost-iostreams library and libzstd, and I'm not entirely familiar with how much the toolchain is set up inside of the homebrew test environment. Hopefully those libs are already on the search path, after all boost itself was easily able to find libzstd during it's compilation.

I'll take a look at getting this into the tests today.

**Comment by pettyalex** [comment]
@carlocab Thanks for the assist.

It did end up needing `"-L#{lib}"` to find `-lboost_iostreams` after all. The test will now link and call these libraries. It's working on my machine, but I have not validated on Linux.

**Comment by carlocab** [comment]
Cleaned your PR up a bit. We can run this in CI when there are runners available.

**Comment by pettyalex** [comment]
Looks like it failed because it couldn't find `-lboost_iostreams`, looks like it really may need `"-L#{lib}"`

**Review by carlocab — APPROVED** [review]
Thanks again!

**Pull request closed without merging**
