### PR TITLE
create-dmg 1.1

### PR DESCRIPTION
**Pull request by aonez**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by aonez** [comment]
Why was this closed?

**Comment by aonez** [comment]
Sorry to invoke you @SMillerDev, saw you in a near closed issue, do you know why this was closed?

**Comment by SMillerDev** [comment]
In my ui it only shows closed after you asked that. Maybe a github bug?

**Comment by aonez** [comment]
Yep, the closed message shows at the bottom no matter what. Will force a new PR. Thanks!

**Pull request closed without merging**
