### PR TITLE
node 9.2.0

### PR DESCRIPTION
**Pull request by robcresswell**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
This is blocked on having a compatible npm, but thanks for the PR nonetheless.

**Comment by robcresswell** [comment]
Ah; anything I can do to move that along? Sorry for wasting your time there, failed in my due diligence.

**Comment by ilovezfs** [comment]
Complain to upstream here: https://github.com/npm/npm/issues/19019

**Comment by ilovezfs** [comment]
`brew install --devel node` will now give you node 9.2.0 + npm 5.6.0

**Pull request closed without merging**
