### PR TITLE
Fix git on mojave

### LINKED ISSUE #29322: Install/Update of git fails with --with-gettext option
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): I was trying to update 2.17.1 version of git to 2.18.0 because the newer versions contains performance fixes and I wanted to stay up to date.

- What happened (include command output):
brew upgrade
```bash
Error: Not upgrading 3 pinned packages:
go 1.10.3, nginx 1.15.0, gnupg 2.2.8
==> Upgrading 1 outdated package, with result:
git 2.17.1 -> 2.18.0
==> Upgrading git --with-pcre2 --with-gettext --with-perl
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.18.0.tar.xz
Already downloaded: /Users/johnmcmahon/Library/Caches/Homebrew/git-2.18.0.tar.xz
==> make install prefix=/usr/local/Cellar/git/2.18.0 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
Last 15 lines from /Users/johnmcmahon/Library/Logs/Homebrew/git/01.make:
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make: *** [levenshtein.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [line-range.o] Error 1
make: *** [ident.o] Error 1
make: *** [hex.o] Error 1
1 error generated.
make: *** [kwset.o] Error 1
1 error generated.
make: *** [list-objects.o] Error 1
1 error generated.
make: *** [line-log.o] Error 1
```
- What you expected to happen:
I expected the new version of git to be installed without issue.

- Step-by-step reproduction instructions (by running `brew install` commands):
1. `brew install git --with-pcre2 --with-gettext --with-perl`

1. `brew update && brew outdated && brew missing && brew prune && brew cleanup && brew doctor`

1. `brew upgrade`

- **Workaround**

I **uninstalled* git `brew uninstall git`` then via trial and error, slowly removed the additional `--with` options until the formula installed without issue.

Which landed me at running `brew install git --with-pcre2 --with-perl`, **Note**: that `--with-gettext` was removed and the installation worked after that.

- brew config output:
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f331594dbb82eb5ef6b1e9956b44a80c6231980e
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.0 build 900
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_141
macOS: 10.13.1-x86_64
CLT: N/A
Xcode: 9.2
XQuartz: N/A
- brew doctor output:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (9.2) is outdated.
Please update to Xcode 9.4 (or delete it).
Xcode can be updated from the App Store.

### PR DESCRIPTION
**Pull request by DesWurstes**
Tested, Resolves #29322

### CODE REVIEW

**Comment by fxcoudert** [comment]
Do you understand why this fixes things? I mean, depending on the gettext formula, as is done, should automatically set those variables. Also, why is the issue only on Mojave?

**Comment by DesWurstes** [comment]
macOS has built-in gettext. After Mojave, libs are no longer in /usr/include, and the compiler doesn't know how to find it. So, we need to show it the path of the *real* gettext.

If this is true, "depends_on "gettext"" has been a lie as it has used the system gettext.

**Comment by fxcoudert** [comment]
After a fresh install of `git` by `brew install -s git` on Mojave, I have:

```
$ otool -L /usr/local/opt/git/bin/git | grep gettext
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
```

Moreover, the bug report you link to was filed with macOS 10.13 and Xcode 9.

**Comment by fxcoudert** [comment]
More investigation is needed, not sure that this is the right fix to the problem. Closing for now.

**Pull request closed without merging**
