### PR TITLE
chapel 2.1.0

### PR DESCRIPTION
**Pull request by arezaii**
Updates the Chapel formula for release 2.1, which includes dependency changes to `LLVM` 18, and adds dependencies on `hwloc`, `jemalloc`, and `pkg-config`.

This release also includes the Chapel language server and Chapel code linter as additional tools.

This formula update includes a patch that can be removed in the next Chapel release, 2.2 assuming https://github.com/chapel-lang/chapel/pull/25354 has been merged, expected ~3 months from now. 

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by arezaii** [comment]
All the other configurations passed, but one (macOS 14-x86_64) looks like it timed out and/or was cancelled. 

I wish to restart the CI, but it doesn't seem that I have that option without pushing an update. Would someone with access please restart the CI checks?

**Comment by branchvincent** [comment]
looks like it was a flake, @arezaii is this ready now?

**Comment by arezaii** [comment]
It's not yet ready to be merged. I have a final update to remove the pre-release info from the build, which will be ready to go Thursday when the release becomes available.

**Comment by branchvincent** [comment]
Sounds good, I'll mark it as a draft then. Feel free to undo that when it's officially released

**Comment by bradcray** [comment]
Hi @branchvincent: We're hoping to wrap up our 2.1 release today, so are hoping for a final review + merge here, if possible.  Not knowing what timezones anyone is in, I'm also tagging @carlocab , @chenrui333 , @krehel , and @p-linnane who've helped with past releases.

As a reviewer suggested in our last release, this time around, we re-purposed our pre-release PR (to validate the CI checks before today) for the final release.  But I'm worried that may have caused it to fall so far down the open PR lists that it may go unnoticed today without this ping.  If there's a preferred technique for getting attention on a PR on a release day, please let us know.

Thanks!

**Comment by p-linnane** [comment]
Pinging is ok. I personally sort PR's by last updated rather than when they were opened, so should be fine either way.

**Review by branchv — APPROVED** [review]
lgtm, sorry for the delay!

**Comment by bradcray** [comment]
No sweat, thanks for the assist, @branchvincent!

**Pull request merged**
