### PR TITLE
gat 0.8.1 (new formula)

### PR DESCRIPTION
**Pull request by koki-develop**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by p-linnane** [comment]
Audit is failing due to the repo being newer than 30 days old. Rerunning to see if the builds pass.

**Comment by koki-develop** [comment]
@p-linnane 

```
* GitHub repository too new (<30 days old)
```

Sorry, there was no problem in the local timezone (Japan), but the CI timezone is UTC, which seems to have caused the problem.

I think it is probably OK now, so may I ask you to re-run the CI?

**Comment by p-linnane** [comment]
@koki-develop I'm not worried about that failure given how much traction the project is getting. I will merge it after this CI run. Thank you for your first contribution!

**Review by p-linnane — APPROVED** [review]

**Comment by koki-develop** [comment]
@p-linnane 
Thank you for merging!!

**Pull request merged**
