### PR TITLE
libbi 1.4.4

### PR DESCRIPTION
**Pull request by sbfnk**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why did the owner of the Github repo change?

**Comment by sbfnk** [comment]
It changed a while ago when the libbi user was abandoned and its repositories moved into the respective main contributors' repositories. [https://github.com/libbi](https://github.com/libbi) does not contain any more repositories, and [https://github.com/libbi/LibBi](https://github.com/libbi/LibBi) redirects to [https://github.com/lawmurray/LibBi](https://github.com/lawmurray/LibBi) (which is why any links to release files pointing to subdirectories of the libbi user continue to work).

**Comment by Moisan** [comment]
Could you also update the head url please?

**Comment by fxcoudert** [comment]
Thanks @sbfnk for the pull request!

**Pull request closed without merging**
