### PR TITLE
qemu 7.0.0

### PR DESCRIPTION
**Pull request by reishoku**
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc@pm.me>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
I believe we're waiting for the release of macOS 12.4 before merging this.
See https://github.com/Homebrew/homebrew-core/pull/99652#discussion_r853708368

**Comment by reishoku** [comment]
Thanks for the comment. I didn't know that. Will close this PR.

**Comment by tbutter** [comment]
> I believe we're waiting for the release of macOS 12.4 before merging this. See [#99652 (comment)](https://github.com/Homebrew/homebrew-core/pull/99652#discussion_r853708368)

https://gitlab.com/qemu-project/qemu/-/issues/903#note_876417804 says this also happens with the current version in homebrew so waiting won't help.

**Comment by chenrui333** [comment]
#101585

**Pull request closed without merging**
