### PR TITLE
libgit2-glib 0.25.0

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
also remove vendored libgit2

### CODE REVIEW

**Comment by DomT4** [comment]
`gitg` and `gnome-builder` are going to need a bump too.

**Comment by JCount** [comment]
Thanks DomT4, I noticed that but haven't had a chance yet. :smile:

**Comment by JCount** [comment]
The `gitg` formula needs to be updated to the most recent release, `3.23.90`, to support the `libgit2-glib` api changes in this version.

**Comment by DomT4** [comment]
Alas, `3.23.90` is a development release per GNOME's usual versioning. I think in the past we simply [hacked around configure](https://git.gnome.org/browse/gitg/commit/?h=gnome-3-22&id=9faf6e075384090c372c1b780f5b3a7b6dc9b0d3) providing there's no API breakage, but 🤷‍♂️.

**Comment by JCount** [comment]
@DomT4 ugh.... :unamused:

**Comment by DomT4** [comment]
Aye, a distinct lack of great options here, sigh.

**Comment by JCount** [comment]
I wonder if I can get away with applying [this](https://git.gnome.org/browse/gitg/patch/?id=86cc68589ed53ccd7e7016fdb6884ee5f655d647). Especially given how small the api change is.

cc @tschoonj @ilovezfs

**Comment by JCount** [comment]
Waiting on the next stable release of `gitg`.

**Pull request closed without merging**
