### PR TITLE
aqbanking: migrate to boneyard

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
May I ask why? This one isn't broken or anything.

**Comment by zmwangx** [comment]
It seems you're removing qt revdeps. If that's the case: `qt` is just an optional dep of `gwenhywfar`.

**Comment by MikeMcQuaid** [comment]
@zmwangx of course you can 😁 https://github.com/Homebrew/homebrew-core/issues/1705 as it depends on `gwenhywfar` (No Qt5 support, even in latest 2016 beta)

**Comment by zmwangx** [comment]
Yeah, I'm saying you can simply remove the optional `qt` dep of `gwenhywfar`.

**Comment by MikeMcQuaid** [comment]
@zmwangx Yes, you're right. Not sure how I missed that?

**Pull request closed without merging**
