### PR TITLE
tarantool 1.9.0.60

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
Upstream seems to remove source tarballs. http://download.tarantool.org/tarantool/1.9/src/

GitHub `1.9.0` tarball has a different `sha256` https://github.com/tarantool/tarantool/releases/tag/1.9.0

**Comment by ilovezfs** [comment]
@bigbes any idea what's going on here?

**Comment by commitay** [comment]
Updated to `1.9.0.61` in https://github.com/Homebrew/homebrew-core/commit/5155278c074e8080781f952e287c432809657133

**Comment by bigbes** [comment]
Hello. Sorry, for waiting - some strange thing happened with our S3 storage, that should be append-only. Thank you for quick bumping!

**Comment by ilovezfs** [comment]
Thanks for following up @bigbes! In general, are we "supposed to" be staying current with the latest tarball in https://download.tarantool.org/tarantool/1.9/src or waiting for your upgrade PRs?

**Comment by bigbes** [comment]
You've done great! 1.9 contains only bugfixes, now. So updating inside a branch shouldn't break anything :) Thank you, again @commitay and @ilovezfs

**Pull request closed without merging**
