### PR TITLE
opencv@3: migrate from homebrew/science

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-core/issues/15619

### CODE REVIEW

**Comment by fxcoudert** [comment]
Choice of options is the same as in https://github.com/Homebrew/homebrew-core/pull/15853

`contrib` and `nonfree` are both included without option, as they do not induce any additional dependency

**Comment by ilovezfs** [comment]
This is still far too many options IMO. Ditto for opencv in #15619.

We need to wait for @iMichka to return before proceeding with `opencv`, `opencv3`, or `vtk`, regardless.

**Comment by ilovezfs** [comment]
There are several issues that should be closed or resolved before this is merged as well:

- [ ] https://github.com/Homebrew/homebrew-science/issues/5395
- [ ] https://github.com/Homebrew/homebrew-science/issues/5433
- [ ] https://github.com/Homebrew/homebrew-science/pull/5960
- [ ] https://github.com/Homebrew/homebrew-science/issues/5463
- [ ] https://github.com/Homebrew/homebrew-science/issues/5819

**Comment by ilovezfs** [comment]
Probably this should be opencv and the other opencv should be opencv@2 if we're going to stick to the usual @ naming scheme.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by chocol4te** [comment]
#5960 Has been closed so can be removed from the list.

**Comment by ilovezfs** [comment]
Thanks @chocol4te

**Pull request closed without merging**
