### PR TITLE
mgba 0.10.3

### PR DESCRIPTION
**Pull request by Eraguzy**
updated link and hash for the .tar.gz file
hashes missing for binary files

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by p-linnane — CHANGES_REQUESTED** [review]
Please don't comment out the bottle block. It's not a platform-specific index of hashes, it's the hashes for the built binaries we ship.

**Review by p-linnane — APPROVED** [review]

**Comment by cho-m** [comment]
The current failure is due to some bottles built back when `HOMEBREW_RELOCATABLE_INSTALL_NAMES` was enabled.

However, for `homebrew-core`, the bigger issue is probably that the build is doing `fixup_bundle` to create a portable App bundle, which means the dylibs are getting copied rather than remaining linked to the corresponding formulae.

Will probably need to manually disable that like some other formulae.

**Comment by p-linnane** [comment]
> The current failure is due to some bottles built back when `HOMEBREW_RELOCATABLE_INSTALL_NAMES` was enabled.
> 
> However, for `homebrew-core`, the bigger issue is probably that the build is doing `fixup_bundle` to create a portable App bundle, which means the dylibs are getting copied rather than remaining linked to the corresponding formulae.
> 
> Will probably need to manually disable that like some other formulae.

Thanks for the pointer, I wasn't aware of this workaround. I've pushed the change here.

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
linux build is still failing

**Comment by cho-m** [comment]
Related issue: https://github.com/mgba-emu/mgba/issues/3115

**Comment by p-linnane** [comment]
Turned off the Discord thing and now am it's looking for `icu4c`. We're on 74.x though.:
```
  /home/linuxbrew/.linuxbrew/opt/qt@5/bin/uic: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory
  /home/linuxbrew/.linuxbrew/opt/qt@5/bin/lrelease: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory
```

**Comment by cho-m** [comment]
Needs #164247

**Review by cho-m — APPROVED** [review]

**Pull request merged**
