### PR TITLE
ansible 2.7.2

### PR DESCRIPTION
**Pull request by ffloimair**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lembacon** [comment]
Some of those resources also need updating, for example, the latest version of the `pytz` resource is `2018.7`.

**Comment by ffloimair** [comment]
> Some of those resources also need updating, for example, the latest version of the `pytz` resource is `2018.7`.

Where do I get this info?
I can't find anything about this in the source tarball.

**Comment by ffloimair** [comment]
> Some of those resources also need updating, for example, the latest version of the `pytz` resource is `2018.7`.

Done. Updated all resources to latest version.

**Comment by ffloimair** [comment]
Not sure why 2 of 3 builds fail on Jenkins. The error "directory not empty" does not seem related to the commit. Local build works on Mojave.

**Comment by ffloimair** [comment]
> Not sure why 2 of 3 builds fail on Jenkins. The error "directory not empty" does not seem related to the commit. Local build works on Mojave.

And the same seems to be the case with all other builds for PRs on Jenkins (works on High Sierra, fails on Sierra & Mojave)!

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Review by lembacon — APPROVED** [review]

**Comment by lembacon** [comment]
Thanks @ffloimair!

**Pull request closed without merging**
