### PR TITLE
workflows/generate_formulae.brew.sh_data: fix breakage

### PR DESCRIPTION
**Pull request by Bo98**
We require Jekyll to be installed now. Let bundler handle the dependencies.

### CODE REVIEW

**Comment by Bo98** [comment]
Further discussion: https://github.com/Homebrew/formulae.brew.sh/pull/271#issuecomment-615897164

**Review by MikeMcQuaid — APPROVED** [review]
Looks good! Not sure it's still needed given the other PR that's merged so up to you if you merge or pass on this.

**Comment by Bo98** [comment]
I suppose it's more "correct" to be using `bundle install` here. Though it doubles the time the workflow takes to run with no actual runtime benefit after the fixes made in the other PR so 🤷

The changes that stop using brew's portable Ruby is probably worth doing at least.

**Comment by MikeMcQuaid** [comment]
> Though it doubles the time the workflow takes to run with no actual runtime benefit after the fixes made in the other PR so 🤷
> 
> The changes that stop using brew's portable Ruby is probably worth doing at least.

Agreed 👍

**Comment by SMillerDev** [comment]
@Bo98 still applicable?

**Comment by Bo98** [comment]
Nope

**Pull request closed without merging**
