### PR TITLE
l formulae: add `head` branch

### PR DESCRIPTION
**Pull request by chenrui333**
update formulae head branches

relates to Homebrew/brew#11720

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
Can you rebase this? Looks like there is a conflict.

**Comment by chenrui333** [comment]
Sure.

**Comment by chenrui333** [comment]
I did not actually see the conflict in the rebase though (but just did the rebase anyway)

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Maybe just the GitHub UI that was confused. Looks good now.

**Comment by chenrui333** [comment]
Maybe some git performance issue earlier.

**Pull request merged**
