### PR TITLE
aws-okta 1.0.5

### PR DESCRIPTION
**Pull request by richadams**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I couldn't get `brew bump-formula-pr` to complete locally, it would hang when trying to push to GitHub. So while the change itself came from `bump-formula-pr`, this PR was raised manually as I didn't want to spend time debugging an unrelated issue with my local setup. 

The `--build-from-source`, `test`, and `audit` commands all finished without issue locally.

### CODE REVIEW

**Comment by Frangello** [comment]
I was having the same issue when trying to push

**Comment by sdann** [comment]
@chenrui333 @Rylan12 Could we get a quick review on this minor version bump? The fix unblocks several companies/users that are having a partial outage. Thanks!

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
sorry for the wait, I think we have some github performance issue lately. but definitely happy to get this up to the latest.

**Comment by chenrui333** [comment]
Thanks @richadams for the help!

**Comment by chenrui333** [comment]
> I couldn't get brew bump-formula-pr to complete locally, it would hang when trying to push to GitHub. 

This is the github performance issue that we are suffering right now.

**Comment by chenrui333** [comment]
@sdann can you link the relevant bug report and fixes attached to it, I would be personally interested about it. Thanks!

**Comment by sdann** [comment]
> @sdann can you link the relevant bug report and fixes attached to it, I would be personally interested about it. Thanks!

Thanks for the quick merge @chenrui333! Here's the bug: https://github.com/segmentio/aws-okta/issues/298

**Comment by Rylan12** [comment]
Thanks, everyone! I merged this is manually (it only took about 3 hours to push...)

**Pull request closed without merging**
