### PR TITLE
vstr: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
@carlocab This formula needs a `flat_namespace` fix due to the `libtool` bug, and it doesn't work with our usual pataches.  Unfortunately `autoreconf` is failing (more specifically, `autoheader` is failing, the errors are in the logs).  If we can't figure out how to get autoheader to work, is this a case where we should patch `configure` in `:DATA`?  I see we've had to do that for some other formulae.

**Comment by carlocab** [comment]
Does using one of the versioned autoconf formulae help?

**Comment by danielnachun** [comment]
Unfortunately they do not work. `autoconf@2.69` fails with the same error, and `autoconf@2.13` fails because it is too old (it says the minimum version needed is `autoconf 2.58`).

**Comment by danielnachun** [comment]
@carlocab I ended up just patching `configure` here to get rid of the flat namespace usage.  The patch is even more trivial than our usual ones.

**Comment by SMillerDev** [comment]
Could you make sure to submit it upstream too?

**Comment by danielnachun** [comment]
@carlocab can comment more on this but normally for autotools the "correct" solution here is to rerun `autoreconf`.  Since that's not working here, we end up patching the `configure` script.  From what I understand we try to use our existing patches first, then when that doesn't work, run `autoreconf`, and only patch the `configure` script specifically for that formula as a last resort.

If we could figure out why `autoheader` wasn't working, that is something that should be upstreamed, but that has proven difficult so far.

**Comment by cho-m** [comment]
On side note, might be able to fix ARM build by manually disabling deprecated stat64, which has caused similar build issues in other formulae:
```rb
ENV["ac_cv_func_stat64"] = "no" if Hardware::CPU.arm?
```

**Comment by danielnachun** [comment]
> On side note, might be able to fix ARM build by manually disabling deprecated stat64, which has caused similar build issues in other formulae:
> 
> ```ruby
> ENV["ac_cv_func_stat64"] = "no" if Hardware::CPU.arm?
> ```

That worked!  Thanks for the suggestion @cho-m, I'll keep this mind for other ARM build failures too.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
