### PR TITLE
apache-geode 1.13.3

### PR DESCRIPTION
**Pull request by onichols-pivotal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does Apache Geode not work with OpenJDK 11 yet?

**Comment by onichols-pivotal** [comment]
Geode is tested on both openjdk8 and openjdk11 runtimes. For compatibility it is still compiled on jdk8

**Comment by SMillerDev** [comment]
I think it would be good for brew to switch to OpenJDK 11 so that it can run on ARM based macOS devices.

**Comment by onichols-pivotal** [comment]
Please go ahead and make that change!

**Review by nandahkrishna — APPROVED** [review]
Thanks!

**Pull request closed without merging**
