### PR TITLE
workflows/dispatch-command: add action

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This PR in conjunction with #139608 will allow us to comment `/rebase` to dispatch PR rebases like we do in `homebrew-cask`

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
@chenrui333 let's wait for multiple reviews (especially those from the TSC and/or @MikeMcQuaid) before merging new workflows please -- especially when those workflows use external actions.

**Comment by MikeMcQuaid** [comment]
@carlocab if desired we can make this an actual branch protection requirement.

**Comment by carlocab** [comment]
> @carlocab if desired we can make this an actual branch protection requirement.

Sounds good to me!

**Comment by MikeMcQuaid** [comment]
Screenshot 2023-08-16 at 14 20 02

@carlocab unless you just enabled this: looks like it was already on?

**Pull request merged**
