### PR TITLE
cryptol: trigger CI

### PR DESCRIPTION
**Pull request by ilovezfs**
**Added by UniqMartin:** See https://github.com/Homebrew/homebrew-core/pull/1339#issuecomment-221021992 for details.

### CODE REVIEW

**Comment by UniqMartin** [comment]
Relating to this, #1375, and #1376:

- It would be nice to have an explanation (however short) of why triggering CI is needed. Sorry if I missed the discussion on that, but I would have appreciated to find a link to it in the body of respective PRs. As it stands, these PRs are very opaque.

- Also, are you aware that you can rebuild bottles without introducing dummy changes (that just clutter the history except maybe for the minor `desc` fix)? It's easy to use, too. You can learn more about the “Homebrew Testing” Jenkins job here: [Brew Test Bot For Core Contributors](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Brew-Test-Bot-For-Core-Contributors.md#homebrew-testing).

Thanks!

**Comment by ilovezfs** [comment]
@UniqMartin I was following the procedure recommended here: https://github.com/Homebrew/homebrew-core/pull/898#issuecomment-217436734

**Comment by UniqMartin** [comment]
You've left my first point completely without comment and that's the one I feel strongly about. 😢 I'm rather confident that writing a short sentence that motivates the PR wouldn't have been much of a burden to you. In contrast, almost everyone looking at these PRs in their current state will be just puzzled.

> I was following the procedure recommended here: https://github.com/Homebrew/homebrew-core/pull/898#issuecomment-217436734

And relating to the linked comment: Those aren't even style changes (something `brew audit --strict` would have pointed out) but really just dummy changes that are unnecessary. In the same comment, Dom also mentioned the solution that I suggested: “[…], or queue up a test build on CI, […]”.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/1339#issuecomment-221021992

**Comment by MikeMcQuaid** [comment]
@UniqMartin Please don't edit the PR bodies written by other maintainers, thanks. Commentary underneath is sufficient. In the case of at least https://github.com/Homebrew/homebrew-core/pull/1374 the GitHub cross-reference does provide some context but I agree a little more context would be nicer on others (even if it's just a "For #1339")

**Comment by UniqMartin** [comment]
> Please don't edit the PR bodies written by other maintainers, thanks.

I strictly *added* to the PR body and didn't change anything that was already there, so I probably should have used “Added” instead of “Edited”. Anyway, if that's frowned upon, I'll refrain from doing that in the future. And I only did it to make the PR body *somewhat* useful to anyone coming across these PRs.

In any case, this was a pragmatic (and I believe not exactly hostile) solution to an issue (lack of cross-references and any explanation) that I went to the trouble of calmly explaining, motivating, and providing suggestions/alternatives. Being “answered” with copy-pasted links twice made it clear to me I'm not likely to receive an actual answer or the issues raised to be addressed.

> In the case of at least #1374 the GitHub cross-reference does provide some context […]

That's also the only one that got any cross-reference to the original issue. 😢 I probably wouldn't even have complained if that was the case for all of the listed PRs.

**Comment by MikeMcQuaid** [comment]
> Anyway, if that's frowned upon, I'll refrain from doing that in the future.

Yes, thanks.

> Being “answered” with copy-pasted links twice made it clear to me I'm not likely to receive an actual answer or the issues raised to be addressed.

Please have a little more faith in your fellow maintainers to take your feedback on board. Publicly stating you assume it won't be addressed is a pretty good way of ensuring it will not be.

**Comment by UniqMartin** [comment]
> Please have a little more faith in your fellow maintainers to take your feedback on board. Publicly stating you assume it won't be addressed is a pretty good way of ensuring it will not be.

Yes, you're right. I'm sorry about that! I hope that now that this has been stated publicly and can't be taken back, at least @ilovezfs has enough insight into my thoughts and reasons for my reaction. I let him be the judge on whether my train of thought makes any sense and if my reaction was appropriate.

**Pull request closed without merging**
