### PR TITLE
goreleaser 0.76.0 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @tsenart

### CODE REVIEW

**Comment by tsenart** [comment]
❤️

**Comment by tsenart** [comment]
CC @goreleaser

**Comment by tsenart** [comment]
CC @caarlos0

**Comment by caarlos0** [comment]
Nice!

FWIW, I just released v0.76.1 :D 

Thanks @ilovezfs and @tsenart

**Comment by ilovezfs** [comment]
@caarlos0 0.76.1 https://github.com/Homebrew/homebrew-core/pull/28189

**Pull request closed without merging**
