### PR TITLE
Remove all remaining bottle :unneeded

### LINKED ISSUE #75943: Bottle all `bottle :unneeded`
Everything that's `bottle :unneeded` ~has got to go!~ should be bottled. This can be done by creating a pull request removing the `bottle :unneeded` line and allowing the bottles to be committed as usual.

For bonus points, verify the checksums of all generated artefacts are the same and attempt to fix them up (or CC me and I'll give it a go).

---

[cho-m] Tracking the remaining:
- [x] g* - #79997
- [x] `civl` - #80077
- [x] `couchpotatoserver` - #80078
- [x] `golo` - #80154
- [x] `growly` - #80151
- [x] `gwt` - #80145
- [x] `i2p` - #80106
- [x] `idnits` - #80107
- [x] `iphotoexport` - #80108
- [x] `kobalt` - #80037
- [x] `payara` - #80114
- [x] `polynote` - #80105
- [x] `serveit` - #80080
- [x] `skinny` - #80152

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Fixes https://github.com/Homebrew/homebrew-core/issues/75943

### CODE REVIEW

**Comment by nandahkrishna** [comment]
@MikeMcQuaid Just to confirm, do you want these to bottled separately for ARM (and not in this PR)? Some of them may not work on ARM because they depend on, e.g., `openjdk@8`.

**Comment by MikeMcQuaid** [comment]
@nandahkrishna I want these all bottled for ARM when possible. I plan on removing the PRs from here that refuse to build.

**Comment by nandahkrishna** [comment]
Alright, I'll have to rerun CI since the label was added just after it was supposed to be detected 😅.

**Comment by cho-m** [comment]
Probably should make sure to avoid approving/merging any other [`bottle-up-everything` PRs](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aopen+label%3Abottle-up-everything) (specifically, any that are touched here) to avoid conflicts.

**Comment by nandahkrishna** [comment]
Actually, I wonder if we'll be able to automerge this pull request. I remember the workflow kept failing because of storage issues with `alluxio`, and the `bottles.zip` artifact there was just about 6.5 GB.

**Comment by MikeMcQuaid** [comment]
@nandahkrishna @cho-m This should be good to merge after CI finishes now. I've stripped out anything where the builds were failing consistently. I will be offline until Monday so if either if you get the chance to merge: that'd be great. If it can't be merged at all: I can split it into more batches.

**Comment by chenrui333** [comment]
I wonder it might better to divide this big PR into smaller ones by languages, so that we can make more effective merges.

**Comment by Moisan** [comment]
Current failures on ARM:

<details>
  <summary><b>build-bottle failures</b></summary>

- amdatu-bootstrap
- apache-drill
- apache-geode
- apktool
- ne-java
- ballerina
- bee
- blazegraph
- ceylon
- embulk
- git-annex-remote-rclone
- javarepl
- jmxterm
- jooby-bootstrap
- jsawk
- jvm-mon
- jvmtop
- kettle
- naturaldocs
- predictionio
- sbt@0.13
- scala@2.11

</details>


<details>
  <summary><b>test failures</b></summary>

- apgdiff
- bltool
- briss
- htmlcompressor
- jslint4java
- rhino
- scalariform
- scalastyle

</details>

**audit failure**: `inxi`

**fetch failure**: `predictionio` and `stanford-ner`

**Review by cho-m — DISMISSED** [review]

**Comment by cho-m** [comment]
Only `inxi` audit failure on Intel, which was expected.

Total 33.3 GB for bottles.

**Comment by cho-m** [comment]
```
Error: Expected 304 commits but actually got 250!
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:570:in `block in pull_request_commits'
```

**Comment by cho-m** [comment]
As we now have conflicts and need to do another run, we might as well split this up to avoid hitting issues with too many commits or too much GB of data.

**Comment by nandahkrishna** [comment]
Yes I think it's better we split this, either by language as suggested by Rui or alphabetically. I guess we'll have to try to know whether automerge will work with the split PRs.

**Comment by cho-m** [comment]
Top 20 Catalina bottles by size. May be better to have separate PR for some:
```console
❯ du -sh *catalina* | sort -hr | head -20
1.7G	kettle--9.1.0.0-324_1.catalina.bottle.tar.gz
1.5G	nifi--1.13.2.catalina.bottle.tar.gz
1.1G	prestosql--344.catalina.bottle.tar.gz
624M	apache-ctakes--4.0.0_1.catalina.bottle.tar.gz
474M	hadoop--3.3.0.catalina.bottle.tar.gz
466M	hapi-fhir-cli--5.4.0.catalina.bottle.tar.gz
364M	apache-drill--1.18.0.catalina.bottle.tar.gz
263M	sonarqube--8.9.0.43852.catalina.bottle.tar.gz
218M	apache-spark--3.1.2.catalina.bottle.tar.gz
185M	pig--0.17.0_1.catalina.bottle.tar.gz
182M	solr--8.8.2.catalina.bottle.tar.gz
174M	stanford-parser--4.2.0.catalina.bottle.tar.gz
172M	stanford-ner--4.2.0.catalina.bottle.tar.gz
158M	solr@7.7--7.7.3_1.catalina.bottle.tar.gz
153M	fits--1.5.0.catalina.bottle.tar.gz
151M	redpen--1.10.4_1.catalina.bottle.tar.gz
140M	mahout--0.13.0_1.catalina.bottle.tar.gz
139M	titan-server--1.catalina.bottle.tar.gz
133M	tika--1.26.catalina.bottle.tar.gz
126M	grails--4.0.10.catalina.bottle.tar.gz
```

**Comment by MikeMcQuaid** [comment]
Thanks for the work here all! Will try to split this out at some point (but feel free to beat me to it).

**Comment by MikeMcQuaid** [comment]
Closing in favour of separate PRs.

**Pull request closed without merging**
