### PR TITLE
pgloader: add missing dependencies

### PR DESCRIPTION
**Pull request by greencrab**
that's needed for compiling latest source per [issues from upstream](https://github.com/dimitri/pgloader/issues/641)

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — DISMISSED** [review]
@greencrab if these are only needed for the `--HEAD` build they should be scoped to a `head do` block.

**Comment by greencrab** [comment]
@ilovezfs oh.. didn't know about the `head do` block, testing the changes now and will do another commit

**Comment by ilovezfs** [comment]
@greencrab please squash this down to a single commit :)

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@greencrab Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
