### PR TITLE
fontconfig 2.14.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
test failure on 11-arm and 12-arm

```
brew test --retry --verbose man-db
```

**Comment by chenrui333** [comment]
need a rebase to do the rerun.

**Comment by chenrui333** [comment]
Now just a rerun should be good

**Comment by cho-m** [comment]
```
gman: can't create temporary cat for /opt/homebrew/share/man/cat1/gman.1.gz: Operation not permitted
```

Not sure why `man-db` has swapped the `man1` to `cat1` on ARM.

Same failure in #114858 so probably not related to these PRs.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
