### PR TITLE
geoipupdate 4.2.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
postinstall failed:

```
/usr/local/Cellar/geoipupdate/4.2.0/bin/geoipupdate
-v

error loading configuration file: invalid account ID format: strconv.Atoi: parsing "YOUR_ACCOUNT_ID_HERE": invalid syntax
```

**Comment by chenrui333** [comment]
Should be good now.

**Comment by chenrui333** [comment]
Still the same post_install error.

**Comment by chenrui333** [comment]
relates to https://github.com/maxmind/geoipupdate/pull/60

**Comment by chenrui333** [comment]
Removed version check in the post_install step.

**Comment by SMillerDev** [comment]
Pretty sure that was a verbose download and not a version check.

**Comment by chenrui333** [comment]
> Pretty sure that was a verbose download and not a version check.

yeah, you are right. Let me submit an upstream issue about how to do this correctly.

**Comment by oschwald** [comment]
Removing the automatic post-install download seems right to me. Users will need to get a free account and license key from MaxMind in order to download. This isn't particular to 4.2.x; it is now true for all `geoipupdate` versions. See [this blog post](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) for more information.

**Comment by SMillerDev** [comment]
Does the software work without that download?

**Comment by oschwald** [comment]
The purpose of this tool is to download the databases and keep them up to date.

**Comment by Bo98** [comment]
I think we've established that this is ok.

@BrewTestBot test this please

**Pull request closed without merging**
