### PR TITLE
cadaver: add mirror

### PR DESCRIPTION
**Pull request by queengooborg**
Found a mirror for the tarball, and checked to make sure it's the same SHA256, which it is!

### CODE REVIEW

**Comment by ilovezfs** [comment]
Since the main url isn't working, we should add a comment about that and use a mirror for the primary. There's an audit that will prevent fossies from being the primary though. So we'll need another mirror here for the main url.

**Comment by vinyldarkscratch** [comment]
Looking around for another mirror now -- a lot of the links are routing right back to www.webdav.org, or are other package managers (which I assume are unusable due to either an audit or Homebrew policies).  Will commit both the comment and a main mirror when I can find one!

**Comment by ilovezfs** [comment]
http://pkgs.fedoraproject.org/repo/pkgs/cadaver/cadaver-0.23.3.tar.gz/502ecd601e467f8b16056d2acca39a6f/cadaver-0.23.3.tar.gz

**Comment by ilovezfs** [comment]
https://ftp.mirrorservice.org/sites/download.salixos.org/i486/extra-14.2/source/network/cadaver/cadaver-0.23.3.tar.gz

**Comment by vinyldarkscratch** [comment]
...Well, I stand corrected about other package managers used as mirrors, then.  X3

**Comment by ilovezfs** [comment]
I'd make https://ftp.mirrorservice.org/sites/download.salixos.org/i486/extra-14.2/source/network/cadaver/cadaver-0.23.3.tar.gz primary since it's https and it's not fossies :)

**Review by ilovezfs — APPROVED** [review]

**Comment by vinyldarkscratch** [comment]
The failing check seems to be due to the fact that webdav.org is still down, and it's listed as the homepage.  This newest commit should fix that!

**Comment by ilovezfs** [comment]
Thanks again @vinyldarkscratch!

**Pull request merged**
