### PR TITLE
lsusb 1.1.4

### PR DESCRIPTION
**Pull request by wyan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The previous version of this formula was pointing to a repo that is now abandoned, I have updated the URL to the most current fork of this project.

### CODE REVIEW

**Comment by iMichka** [comment]
Thanks for your contribution.
For reference: some discussions about the best fork to chose happened here: https://github.com/jlhonora/lsusb/issues/19

The proposed fork has only 4 stars, so that does not really meet our notability criteria.
Maybe the original author could endorse one of the forks?

I'm also worried that there are so many downloads for a seemingly abandoned project ...
```
==> Analytics
install: 783 (30 days), 2,278 (90 days), 7,601 (365 days)
install-on-request: 783 (30 days), 2,278 (90 days), 7,601 (365 days)
build-error: 0 (30 days)
```

**Comment by wyan** [comment]
Thank you for your comment, that is indeed the discussion from which I learnt about the proposed fork, as the version currently in homebrew-core has a bug that, while not serious, is annoying. If the proposed PR does not meet notability criteria, perhaps it'd be convenient to consider removing the formula (I'm happy to move it to a personal tap), but I'm not familiar with the procedure to do so.

**Comment by iMichka** [comment]
What about `usbutils`? Does it provide equivalent functionality? Is it well maintained? Maybe we could drop the formula and recreate users to `usbutils`?

I'm worried to deprecate the formula as there are 783 downloads / month. We will not advertise private taps so we can't redirect our users to your tap. So that's also not an ideal solution.

**Comment by wyan** [comment]
The `lsusb` command in `usbutils` doesn't seem to work properly on my machine, sadly.

The version currently in `homebrew-core` sort of works, but displays the following error:
```/opt/homebrew/bin/lsusb: line 89: 16#: invalid integer constant (error token is "16#")```
once per USB device found. The fix should be really brief, but the original repo has several PRs pending, the oldest since 2021, so I'm not sure it'd be easy to get them to endorse any alternative repos.

**Review by chenrui333 — COMMENTED** [review]
LGTM, I think it would be useful for some folks! 👍

**Comment by iMichka** [comment]
I would like some more thoughts from @Homebrew/core maintainers. Looks good IMHO, let's just wait a few more days if someone wants to block this from being merged.

**Comment by p-linnane** [comment]
@LanikSJ's fork is the most active, and people obviously care enough so let's merge it.. They've also been a Homebrew contributor for some time, so that helps me with my decision 😆.

**Review by p-linnane — APPROVED** [review]

**Comment by LanikSJ** [comment]
Thank you @p-linnane I fully intend to support this project as long as humanly possible.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Hold please. Usual/documented fork rules should apply: either upstream needs to bless this fork or we need evidence that multiple other distros have moved to this fork.

I've skimmed for evidence of either and can't see them. That's not saying they aren't the case, just let's be explicit in the PR first, thanks.

**Comment by Bo98** [comment]
> we need evidence that multiple other distros have moved to this fork

On this point it's worth noting we're the _only_ known package manager to ship this at all, largely because it's macOS-only. So there are no other distros to check.

**Comment by MikeMcQuaid** [comment]
> On this point it's worth noting we're the _only_ known package manager to ship this at all, largely because it's macOS-only. So there are no other distros to check.

In that case: I'd rather vote (again, as per-docs) that we disabled it rather than move to a fork that doesn't seem to be sufficiently canonical. We could also consider accepting this as-is as `lsusb-LanikSJ` if other notability guidelines are met.

**Comment by LanikSJ** [comment]
I'm willing to take whatever steps necessary for this formula to be included. I haven't proposed it myself as in my experience I didn't think it would get included.

In the mean time I maintain my own tap https://github.com/LanikSJ/homebrew-tap however I don't pretend to know how write Taps correctly. 🙂

**Comment by p-linnane** [comment]
I've opened https://github.com/Homebrew/homebrew-core/pull/164273 to add @LanikSJ's fork as a new formula. Will deprecate this one once that's merged.

**Pull request closed without merging**
