### PR TITLE
Valgrind cavheat highsierra

### PR DESCRIPTION
**Pull request by MartinDelille**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I simply added a cavheat information for 10.13 users.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Afaik as a rule homebrew doesn't suggest using the head option of a formula as it requires compiling everything on the machine. @ilovezfs any opinions?

**Comment by ilovezfs** [comment]
Upstream should do a release. Has anyone asked for one? Given how close macOS Mojave is to release, and the current stable version of valgrind is not High Sierra compatible, we're nearing deletion territory for the formula at this point.

**Comment by MartinDelille** [comment]
I will ask.

**Comment by MartinDelille** [comment]
Done: https://bugs.kde.org/show_bug.cgi?id=383811#c26

**Comment by Echelon9** [comment]
Valgrind's upstream MacOS maintainer here.
Preliminary work is being undertaken to prepare for Valgrind's next numbered release. Unfortunately I don't have a specific date that I can communicate, but it is in train.
Appreciate this might not be the immediate answer you wanted -- but thought best to get it out there.
Thanks for the interest.

**Comment by SMillerDev** [comment]
Will that release work on mojave? Or no idea about that yet?

**Comment by fxcoudert** [comment]
Thanks for suggesting the caveat @MartinDelille.
Given the information given by upstream, I think we'll decline the caveat: we typically don't suggest building from head, and hopefully a new release is here soon!

**Pull request closed without merging**
