### PR TITLE
sile → 0.10.8 → 0.10.9

### PR DESCRIPTION
**Pull request by alerque**
[Upstream v0.10.8 release notes.](https://github.com/sile-typesetter/sile/releases/tag/v0.10.8)
[Upstream v0.10.9 release notes.](https://github.com/sile-typesetter/sile/releases/tag/v0.10.9)

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> make
 cd . && bash /private/tmp/sile-20200718-2308-3tjws8/sile-0.10.8/missing automake-1.16 --foreign
/private/tmp/sile-20200718-2308-3tjws8/sile-0.10.8/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile.in] Error 1
```

**Comment by alerque** [comment]
Not sure what happened there, but I'll look into it.

**Comment by alerque** [comment]
@chenrui333 I honestly can't make out what happened there. I can replicate the error when compiling the release tarball on a system *without* `automake` — which should work and does not so clearly something is wrong. The problem is I can't replicate the problem rebuilding the release tarball now.

In any event Lua 5.4 support has landed in master and a new release is immanent. I think I'll just update this PR to v0.10.9 when it gets tagged and move on.

**Comment by alerque** [comment]
@chenrui333 Looks like the v0.10.9 release fixed the build issue, CI tests at least are passing now. Anything else from me?

**Comment by gromgit** [comment]
> Anything else from me?

Fixing the PR title (`sile 0.10.9`) would be good. I seem to recall that various CI actions expect the title to be in a specific format, so individual creativity is not encouraged in this.

**Comment by SMillerDev** [comment]
> > Anything else from me?
> 
> Fixing the PR title (`sile 0.10.9`) would be good. I seem to recall that various CI actions expect the title to be in a specific format, so individual creativity is not encouraged in this.

The PR title is fine, it's the commit that we would like in a certain format so we can easily find it.

**Review by SMillerDev — APPROVED** [review]

**Comment by alerque** [comment]
@SMillerDev Thanks. I think I've followed the expected commit format. Is the (now obsolete) tag on the PR holding up the works?

**Pull request closed without merging**
