### PR TITLE
teleport 6.0.1

### PR DESCRIPTION
**Pull request by dawidd6**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Moisan** [comment]
`webassets` needs to be updated.

**Comment by bayandin** [comment]
> The `webassets` resource needs to be updated.

Do we really want to keep this submodule as a resource? 
I would suggest switching to git for getting source code and then we won't need to track this separately.

**Comment by dawidd6** [comment]
> The webassets resource needs to be updated.

Don't think it should. The comment states that the resource should be kept in sync with what is included in tagged repo tree (version) and this submodule didn't change between those releases.

**Review by Moisan — APPROVED** [review]
>this submodule didn't change between those releases

You're right, I wrongly compared the git revision and the hash. No need to update it this time 👍 . I'll approve and we can revisit @bayandin proposal in another PR.

**Pull request closed without merging**
