### PR TITLE
passenger 5.0.28

### PR DESCRIPTION
**Pull request by FooBarWidget**

### CODE REVIEW

**Comment by DomT4** [comment]
Yosemite build failed:
```
mkdir -p 'buildout/ruby/ruby-2.0.0-universal-macosx/'
cd 'buildout/ruby/ruby-2.0.0-universal-macosx/' && /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby '/private/tmp/passenger-20160428-66268-1di6hde/passenger-5.0.28/src/ruby_native_extension/extconf.rb'
checking for alloca.h... *** /private/tmp/passenger-20160428-66268-1di6hde/passenger-5.0.28/src/ruby_native_extension/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=/private/tmp/passenger-20160428-66268-1di6hde/passenger-5.0.28/src/ruby_native_extension
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:549:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:502:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:549:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:1044:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:1043:in `have_header'
	from /private/tmp/passenger-20160428-66268-1di6hde/passenger-5.0.28/src/ruby_native_extension/extconf.rb:38:in `<main>'
rake aborted!
Command failed with status (1): [cd 'buildout/ruby/ruby-2.0.0-universal-mac...]
/private/tmp/passenger-20160428-66268-1di6hde/passenger-5.0.28/build/ruby_extension.rb:56:in `block in <top (required)>'
Tasks: TOP => apache2 => buildout/ruby/ruby-2.0.0-universal-macosx/passenger_native_support.bundle => buildout/ruby/ruby-2.0.0-universal-macosx/Makefile
```

**Comment by FooBarWidget** [comment]
> The compiler failed to generate an executable file. You have to install development tools first.

Is this a problem in the formula or in the Yosemite CI environment? The CI build succeeds on Mavericks and El Capitan; *only* the Yosemite CI build fails.

**Comment by DomT4** [comment]
> Can you find out what's inside mkmf.log?

Not from CI, but I'll try to grab it from a manual machine for you ASAP.

**Comment by CamJN** [comment]
@DomT4 did you ever get @FooBarWidget the log?

**Comment by DomT4** [comment]
I went one better and found (Via @ilovezfs's suggestion in another PR) a "fix" for Yosemite. Add:

```ruby
ENV.delete("SDKROOT")
```
at the top of `def install`.

**Comment by FooBarWidget** [comment]
What does that do? And why would I have to put it in my formula, as opposed to doing it globally in the CI server?

**Comment by CamJN** [comment]
Here's the discussion that @DomT4 is referring to: https://github.com/Homebrew/homebrew-core/pull/1046

**Comment by FooBarWidget** [comment]
I read #1046. I still have no idea what all of that means, what's going, and why my formula needs to unset SDKROOT (as opposed to the Homebrew runtime doing that for me). But I've updated my formula to unset SDKROOT so hopefully the patch is now eligible for merging.

**Comment by DomT4** [comment]
Homebrew can't set it globally because doing so actually _breaks_ certain build systems. It's something we're working on but there's a lack of simple, elegant answers at this point. A lot of the problem is that prior to 10.11 Apple provided an SDK-per-OSX-release, but with Xcode 7 that changed so one SDK served both 10.10 & 10.11, and a lot of upstream build systems don't quite know how to react to that.

Merged in https://github.com/Homebrew/homebrew-core/commit/d72cfb2ef09fc9d1a271dbcb08f1b0e33fda46d5. Thank you for your contribution to Homebrew @FooBarWidget; we appreciate it! :smiley_cat:

**Comment by FooBarWidget** [comment]
Are you sure that `ENV.delete('SDKROOT')` isn't going to break things? Isn't the intention that SDKROOT is unset while installing the passenger formula? Calling `ENV.delete('SDKROOT')` will permanently unset that environment variable during the rest of the Homebrew process's life cycle. So if any additional formula installs are run after Passenger, then they will also not have $SDKROOT even though they might expect it to be set. Am I wrong?

**Comment by DomT4** [comment]
> Calling ENV.delete('SDKROOT') will permanently unset that environment variable during the rest of the Homebrew process's life cycle. 

`ENV` blocks only impact operations within that `def` block unless you execute the `def` block externally. You can test this yourself locally:

```ruby
ENV["SDKROOT"] = "/tmp/testing"
puts ENV["SDKROOT"]
=> /tmp/testing

def test
  ENV.delete("SDKROOT")
  puts ENV["SDKROOT"]
end
=> nil

puts ENV["SDKROOT"]
=> /tmp/testing

test
puts ENV["SDKROOT"]
=> nil
```

**Pull request closed without merging**
