### PR TITLE
readline 8.1

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
On 10.14:

```
brew test --retry --verbose cargo-edit
brew test --retry --verbose couchdb-lucene
brew test --retry --verbose cucumber-cpp
brew fetch --retry diff-pdf
brew test --retry --verbose dnstwist
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew fetch --retry mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose pcl
brew install percona-server
brew test --retry --verbose pipgrip
brew test --retry --verbose renameutils
```

**Comment by sharris40** [comment]
Most of those failures are reported in https://github.com/Homebrew/homebrew-core/issues/66450, and `diff-pdf` in https://github.com/Homebrew/homebrew-core/issues/66385. That leaves `couchdb-lucene`, `dnstwist`, and `renameutils`.

**Comment by bayandin** [comment]
Can't reproduce problems with `dnstwist`, but was able to fix it in https://github.com/elceef/dnstwist/pull/115.
If it happens again — will backport the patch

**Comment by bayandin** [comment]
Also can't reproduce locally `renameutils` failure:
```
==> /usr/local/Cellar/renameutils/0.12.0_3/bin/icp test.txt
/usr/local/Cellar/renameutils/0.12.0_3/bin/icp: cannot execute gcp: No such file or directory
```

it complaints about missing `gcp` which is a part of `coreutils` and `renameutils` has it as a dependency.

**Comment by bayandin** [comment]
10.15 (Catalina) failures:

```
brew test --retry --verbose cargo-edit
brew test --retry --verbose couchdb-lucene
brew fetch --retry diff-pdf
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew fetch --retry mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose pcl
brew install percona-server
brew test --retry --verbose renameutils
```

**Comment by carlocab** [comment]
Fixing 10.14 failures here will also fix 10.14 failures in openssl version bump: https://github.com/Homebrew/homebrew-core/pull/66501#issuecomment-741994775

**Comment by fxcoudert** [comment]
Please collate and investigate all the unrelated issues found during testing. I will merge in the meantime.

**Comment by carlocab** [comment]
There might be a bug in this version of readline: https://github.com/Homebrew/homebrew-core/issues/68193#issuecomment-753623858

**Comment by dtrodrigues** [comment]
Not a readline bug, but a change in the default value of `enable-bracketed-paste` from off to on.

**Pull request closed without merging**
