### PR TITLE
mas 1.6.3

### PR DESCRIPTION
**Pull request by phatblat**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by phatblat** [comment]
Whoops, forgot that we have a formula revision from mas-cli/mas#214. Don't merge yet.

**Comment by phatblat** [comment]
OK, 🐟 completions are in. Merge away!

**Comment by phatblat** [comment]
Build failed on Mojave for a dependency.

```
22:50:05 *** Building scheme "Nimble-macOS" in Nimble.xcodeproj
22:50:05 Build Failed
22:50:05 	Task failed with exit code 65:
22:50:05 	/usr/bin/xcrun xcodebuild -project /private/tmp/mas-20190331-68256-11i4q0s/Carthage/Checkouts/Nimble/Nimble.xcodeproj -scheme Nimble-macOS -configuration Release -derivedDataPath /tmp/mas-20190331-68256-11i4q0s/.brew_home/.carthage/DerivedData/10.2_10E125/Nimble/v7.3.2 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/kw/j7f63hdn1lj39702nh90xm9w0000gp/T/Nimble SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /tmp/mas-20190331-68256-11i4q0s/Carthage/Checkouts/Nimble)
```

Running a similar command (with paths made relative) works for me on 10.14.4.

```
/usr/bin/xcrun xcodebuild -project Carthage/Checkouts/Nimble/Nimble.xcodeproj -scheme Nimble-macOS -configuration Release -derivedDataPath build/Nimble/v7.3.2 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath build/Nimble SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO
...
** ARCHIVE SUCCEEDED ** [16.763 sec]
```

Nimble is a test dependency so maybe I can configure Carthage to skip it for the Homebrew build.

**Comment by lembacon** [comment]
Thanks @phatblat!

**Pull request closed without merging**
