### PR TITLE
ejabberd 16.08

### PR DESCRIPTION
**Pull request by ilovezfs**
use upstream vendoring

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 the upstream vendoring is revision pegged, so I think these resource blocks should be taken out back.

**Comment by ilovezfs** [comment]
@dunn basically this reverts https://github.com/Homebrew/legacy-homebrew/pull/46462. Do you still see a need to use resource blocks here? We've been using non-cached resources pretty extensively now with the go formulae wherever possible, and it's been fine.

**Comment by DomT4** [comment]
I'm happy if @dunn is happy.

**Comment by dunn** [comment]
Yeah, if upstream isn't just pulling the master branch anymore, 👍

**Comment by ilovezfs** [comment]
@dunn I actually had at first updated all of the resource blocks with the latest release tags in each repo, and then the build failed because upstream had specifically pegged a lower tag for some of them (so I could have gone back in and lowered the tags accordingly, of course).

**Pull request closed without merging**
