### PR TITLE
libgccjit (new formula)

### PR DESCRIPTION
**Pull request by jonchang**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Should probably conflict with the main GCC

**Comment by jonchang** [comment]
> Should probably conflict with the main GCC

I'm trying to do this Debian-style, where it only installs `libgccjit` and headers and nothing else.

**Comment by d12frosted** [comment]
Hi everyone. What is the state of this PR?

**Comment by jonchang** [comment]
> Hi everyone. What is the state of this PR?

The CI status and logs are publicly available, and shows that this build is currently not passing.

**Comment by d12frosted** [comment]
I mean, I thought that there was an open question. 🤔

**Comment by CarlQLange** [comment]
> > Hi everyone. What is the state of this PR?
> 
> The CI status and logs are publicly available, and shows that this build is currently not passing.

This seems like a bit of a standoffish response given that @d12frosted created the [initial PR](https://github.com/Homebrew/homebrew-core/pull/59134) to achieve this result and has shown a lot of willingness to help and do the right thing in that thread (as have you!). Do you think perhaps you could lay out your plans for this PR, since it sounds like you intend to take this one rather than the original? Are you looking for help on it? Do you have some further steps planned for it?

**Comment by jonchang** [comment]
This isn't going to get merged until it passes CI. Again, the logs are public if anyone wants to help out.

**Comment by seanfarley** [comment]
> > The CI status and logs are publicly available, and shows that this build is currently not passing.
> 
> Sorry if I'm overstepping. This seems like a bit of a standoffish response given that @d12frosted created the [initial PR](https://github.com/Homebrew/homebrew-core/pull/59134) to achieve this result and has shown a lot of willingness to help and do the right thing in that thread (as have you!). Do you think perhaps you could lay out your plans for this PR, since it sounds like you intend to take this one rather than the original? Are you looking for help on it? Do you have some further steps planned for it?

I came here to check on the status and also agree with this comment. I find it incredibly rude to take over someone else's PR with no discussion beforehand and then, as if to twist the knife even more, provide a very curt response. What are the errors in the CI even? It would have been nice if @jonchang could have listed the errors and asked for help. In a very honest ask, should I expect the level of response from LKML in Homebrew and just grew another inch of skin?

Trying to be constructive, here is one error I was able to find in the sea of output from the logs:

```
libgccjit:
  * Non-libraries were installed to "/usr/local/opt/libgccjit/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/opt/libgccjit/lib/libgccjit.so.0
            /usr/local/opt/libgccjit/lib/libgccjit.so.0.0.1
```

That looks like a false positive but I'm not familiar with the internals of this project nor do I want to be after this PR.

**Comment by jonchang** [comment]
> > > The CI status and logs are publicly available, and shows that this build is currently not passing.
> > 
> > 
> > Sorry if I'm overstepping. This seems like a bit of a standoffish response given that @d12frosted created the [initial PR](https://github.com/Homebrew/homebrew-core/pull/59134) to achieve this result and has shown a lot of willingness to help and do the right thing in that thread (as have you!). Do you think perhaps you could lay out your plans for this PR, since it sounds like you intend to take this one rather than the original? Are you looking for help on it? Do you have some further steps planned for it?
> 
> I came here to check on the status and also agree with this comment. I find it incredibly rude to take over someone else's PR with no discussion beforehand and then, as if to twist the knife even more, provide a very curt response. What are the errors in the CI even? It would have been nice if @jonchang could have listed the errors and asked for help. In a very honest ask, should I expect the level of response from LKML in Homebrew and just grew another inch of skin?
> 
> Trying to be constructive, here is one error I was able to find in the sea of output from the logs:
> 
> ```
> libgccjit:
>   * Non-libraries were installed to "/usr/local/opt/libgccjit/lib"
>     Installing non-libraries to "lib" is discouraged.
>     The offending files are:
>       /usr/local/opt/libgccjit/lib/libgccjit.so.0
>             /usr/local/opt/libgccjit/lib/libgccjit.so.0.0.1
> ```
> 
> That looks like a false positive but I'm not familiar with the internals of this project nor do I want to be after this PR.

Thanks for your feedback on how to run our project. I apologize if anything I've written has come off as being hostile, it was not intended as such. I want to point out that Homebrew maintainers work entirely on our free time and no one is paid to work on this project. 

As I've already stated (and you have discovered), our CI logs are public and anyone can see the errors and help out. I haven't gotten any offers to help, nor has anyone else apparently (up until now) looked at the logs to see what is failing. To be perfectly clear as to what needs to be done:

1. this must be built separately since adding 2 hours to the build of gcc is not acceptable
2. this must not conflict with the main gcc formula
3. this must pass CI

If you want to help out: please open a pull request; there's no "takeover" happening as anyone is free to contribute a pull rqeuest. If you don't want to help out: that's also fine.

**Comment by jonchang** [comment]
I think this is ready to go. cc @smillerdev

**Comment by nyamada** [comment]
jonchang -- as someone who was waiting for this formula to pass -- thanks for all your hard work on this -- _much_ appreciated!

**Review by SMillerDev — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Comment by kaz-yos** [comment]
I'm not sure where to ask. Has anyone successfully installed gccemacs with this new `libgccjit` formula?

My attempt (https://gist.github.com/kaz-yos/379e5f0f56ef703dfe2707f3b6fed4da) resulted in 

```
...
checking for gcc_jit_context_acquire in -lgccjit... yes
checking libgccjit.h usability... yes
checking libgccjit.h presence... yes
checking for libgccjit.h... yes
configure: error: Installed libgccjit has failed passing the smoke test.
You can verify it yourself compiling:
<https://gcc.gnu.org/onlinedocs/jit/intro/tutorial01.html>.
Please report the issue to your distribution if libgccjit was installed through
that.
Here instructions on how to compile and install libgccjit from source:
<https://gcc.gnu.org/wiki/JIT>.
```

**Comment by mnewt** [comment]
@kaz-yos My guess is that the library is not found on the path. I'm not sure what the Homebrew recommended way to put it on the path is. One way is to add something like this before running `configure`. 

```
export LIBRARY_PATH="$(brew --prefix libgccjit)/lib/gcc/10/"
```

That begs the question: is that the right approach, to manually add to `LIBRARY_PATH`? Or should the formula be updated to link itself to somewhere that will already be on a searched path, like `/usr/local/lib`?

Oh, and you'll probably also need to add a similar configuration when running Emacs.

**Comment by kaz-yos** [comment]
Thanks! I’ll examine that.

**Comment by razzmatazz** [comment]
> After adding the above suggestion, the same test gave the following. It looks like I'm almost there. I recently updated to Big Sur. I brew-reinstalled both `gcc` and `libgccjit`, but the result was the same.

Same issue on Catalina too. Stuck on:
```
configure: error: Installed libgccjit has failed passing the smoke test.
```

It works, however when building emacs/native-comp with the whole gcc@10 installed with a patch to enable `jit` manually. So something is missing in this formula still..

config.log says:
```
configure:16279: checking libgccjit.h presence
configure:16279: gcc -E   -I/usr/local/opt/libgccjit/include conftest.c
configure:16279: $? = 0
configure:16279: result: yes
configure:16279: checking for libgccjit.h
configure:16279: result: yes
configure:16346: gcc -o conftest -I/usr/local/opt/libgccjit/include   -I/usr/local/opt/libgccjit/include -L/usr/local/opt/libgccjit/lib/gcc/10 conftest.c -lgccjit >&5
configure:16346: $? = 0
configure:16346: ./conftest
ld: library not found for -lgcc_ext.10.5
libgccjit.so: error: error invoking gcc driver
configure:16346: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU Emacs"

(...)

|         if (foo () != 1)
|           exit (1);
|         gcc_jit_context_release (ctxt);
|         gcc_jit_result_release (result);
|         return 0;
|       }
configure:16350: error: Installed libgccjit has failed passing the smoke test.
You can verify it yourself compiling:
<https://gcc.gnu.org/onlinedocs/jit/intro/tutorial01.html>.
Please report the issue to your distribution if libgccjit was installed through
that.
Here instructions on how to compile and install libgccjit from source:
<https://gcc.gnu.org/wiki/JIT>.
```
```

**Comment by seanfarley** [comment]
`libgccjit` (and perhaps `gcc` as well) need to be compiled from source on MacOS 11 (Big Sur).

Here is the test file from Emac's configure:

<pre>
$ cat jittest.c
<details>
#include <libgccjit.h>
    #include <stdlib.h>
    #include <stdio.h>
    int
    main (int argc, char **argv)
    {
      gcc_jit_context *ctxt;
      gcc_jit_result *result;
      ctxt = gcc_jit_context_acquire ();
      if (!ctxt)
        exit (1);
      gcc_jit_type *int_type =
        gcc_jit_context_get_type (ctxt, GCC_JIT_TYPE_INT);
      gcc_jit_function *func =
        gcc_jit_context_new_function (ctxt, NULL,
                                      GCC_JIT_FUNCTION_EXPORTED,
                                      int_type, "foo", 0, NULL, 0);
      gcc_jit_block *block = gcc_jit_function_new_block (func, "foo");
      gcc_jit_block_end_with_return (
        block,
        NULL,
        gcc_jit_context_new_rvalue_from_int (ctxt, int_type, 1));
      result = gcc_jit_context_compile (ctxt);
      if (!result)
        exit (1);
      typedef int (*fn_type) (void);
      fn_type foo =
        (fn_type)gcc_jit_result_get_code (result, "foo");
      if (!foo)
        exit (1);
      if (foo () != 1)
        exit (1);
      gcc_jit_context_release (ctxt);
      gcc_jit_result_release (result);
      return 0;
    }
</details>
</pre>

Compile it:

<pre>
$ gcc -o jittest -I/usr/local/include -L/usr/local/lib/gcc/10  jittest.c -lgccjit
</pre>

Run it:
<pre>
$ ./jittest
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
libgccjit.so: error: error invoking gcc driver
</pre>

Recompile from source:
<pre>
$ brew reinstall gcc --build-from-source --force
$ brew reinstall libgccjit --build-from-source --force
</pre>

Now, recompile `jittest.c` and it runs fine.

**Comment by razzmatazz** [comment]
I have created a follow-up PR that attempts to fix operation/installation/usage of `libgccjit` on my machine when building gcc-emacs.

- https://github.com/Homebrew/homebrew-core/pull/67706

Would love some feedback from @d12frosted and @jonchang

**Pull request closed without merging**
