### PR TITLE
nift 2.1

### PR DESCRIPTION
**Pull request by n-ham**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Test failed:

```
==> /usr/local/Cellar/nift/2.1/bin/nsm init-html
opening project config file: �[1;35m'.nsm/nift.config'�[0;39m
�[2K
�[1;36mwarning�[0;39m: �[1;35m'.nsm/nift.config'�[0;39m: root or output branch not detected, have attempted to determine them, ensure values in config file are correct
�[2K
opening project tracking file..�[2K
successfully tracking index
�[2K
building project..
�[2K
�[1;34mprogress: �[0;39m0/1 0% (0s)�[2K
all 1 output files built successfully
initialised empty project in /private/tmp/nift-test-20200316-40261-1u0bjkc/empty
Error: nift: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <#<Pathname:/private/tmp/nift-test-20200316-40261-1u0bjkc/empty/site/index.html>>.exist? is true value expected but was
<false>
```

**Comment by n-ham** [comment]
Oops, I had planned to change `init-html` to `init '.html'` before releasing the next version and had left `init-html` in the meantime, however had forgotten that I changed the default output directory to `output/` rather than `site/` as Nift can be used for a lot more than just websites. My apologies, should be fixed now.

**Comment by n-ham** [comment]
@bayandin it failed for the same reason as the first time then, but that's because it was using the old test and not the test with the most recent commit, I'm not sure how to get it to use the updated nift.rb file when testing?

**Comment by bayandin** [comment]
According to the error message it uses command `/usr/local/Cellar/nift/2.1/bin/nsm init '.html'` which came from the last commit.
```
==> /usr/local/Cellar/nift/2.1/bin/nsm init '.html'
�[2K
�[1;31m�error�[0;39m: Nift does not recognise the command "init '.html'"
Error: nift: failed
```

And before it was `/usr/local/Cellar/nift/2.1/bin/nsm init-html`

**Comment by n-ham** [comment]
Ah whoops, I thought it was failing to find the build file again, sorry about that, I passed `init '.html'` as one input parameter rather than two. Now should work when checked. My apologies :).

**Comment by bayandin** [comment]
Thanks @n-ham for your contribution to Homebrew! 🎉 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
