### PR TITLE
rust: migrate to python@3.9

### PR DESCRIPTION
**Pull request by fxcoudert**
Splitting from https://github.com/Homebrew/homebrew-core/pull/62560

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
brew install --build-from-source findomain
brew install --build-from-source komposition
brew install --build-from-source mdbook
brew install --build-from-source spotifyd
```

```
Unknown GIR element "docsection" when processing namespace "GLib", aborting.
CallStack (from HasCallStack):
  error, called at lib/Data/GI/CodeGen/API.hs:199:16 in hskll-g-0.23.1-5232f4d8:Data.GI.CodeGen.API
cabal: Failed to build gi-glib-2.0.23 (which is required by
exe:komposition-split from komposition-0.2.0 and exe:komposition from
komposition-0.2.0). See the build log above for details.
```

```
==> Downloading https://github.com/rust-lang/mdBook/archive/v0.4.3.tar.gz
Error: SHA256 mismatch
Expected: e1a60eb877a95c6cf8832cb158a8f09b2d641206fe853378905bcdb962902935
  Actual: 3a3c4da76ff47943dbd5d490567a3d283cf85889f16d4d96ae04328371c1a817
```

```
  thread 'main' panicked at 'unable to generate bindings: ()', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/coreaudio-sys-0.2.3/build.rs:100:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `spotifyd v0.2.24 (/private/tmp/spotifyd-20201012-73267-11hoo7e/spotifyd-0.2.24)`, intermediate artifacts can be found at `/private/tmp/spotifyd-20201012-73267-11hoo7e/spotifyd-0.2.24/target`
```

**Comment by SMillerDev** [comment]
I think we should deprecate komposition. It's been failing for a while and clearly nobody is going to fix it.

**Comment by fxcoudert** [comment]
@SMillerDev I've opened an issue upstream https://github.com/owickstrom/komposition/issues/104

**Comment by bayandin** [comment]
> @SMillerDev I've opened an issue upstream [owickstrom/komposition#104](https://github.com/owickstrom/komposition/issues/104)

It looks like the problem not in `komposition` itself, but in one of the dependency `gi-glib`: https://github.com/haskell-gi/haskell-gi/issues/318.
I'm wondering if we can a backport [the patch](https://github.com/haskell-gi/haskell-gi/issues/318#issuecomment-698498863) to the formula

**Pull request closed without merging**
