### PR TITLE
dotnet 5.0.204

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by cho-m** [comment]
Patch was backported in https://github.com/dotnet/runtime/pull/51188

**Comment by chenrui333** [comment]
> Patch was backported in [dotnet/runtime#51188](https://github.com/dotnet/runtime/pull/51188)

good find.

**Comment by chenrui333** [comment]
artifact downloading issue on 10.15, gonna rerun the CI build now.
```
/private/tmp/dotnet-20210613-27677-1qxgrbg/build.proj(99,5): error : DownloadFileSB.ErrorDownloading https://dotnetcli.azureedge.net/source-built-artifacts/assets/Private.SourceBuilt.Artifacts.0.1.0-5.0.203-1135543-20210512.3.tar.gz System.IO.IOException: The response ended prematurely.
```

**Comment by cho-m** [comment]
Might be an unlucky, transient failure for Catalina?
```make
        Cloning https://github.com/dotnet/sdk to /private/tmp/dotnet-20210613-74389-1vzt0iz/artifacts/src/sdk
  fail: Microsoft.DotNet.Darc.Operations.Operation[0]
        Something failed while cloning.
  System.Exception: Something went wrong when cloning repo https://github.com/dotnet/sdk at <default branch> into /private/tmp/dotnet-20210613-74389-1vzt0iz/artifacts/src/sdk
---> LibGit2Sharp.LibGit2SharpException : SecureTransport error : decryption failure [/private/tmp/dotnet-20210613-74389-1vzt0iz/tools-local/init-build.proj]
     at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
```

Could go away by re-running.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
