### PR TITLE
bazel 0.5.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mhlopko** [comment]
Hi @ilovezfs :)
Thanks for doing this! :) Just a quick question (from a total homebrew noobie :), don't we need to update the version alias?

**Comment by ilovezfs** [comment]
@mhlopko yup but that's not something bump-formula-pr knows how to do, so I fix it up afterwards. See the second commit :)

**Comment by mhlopko** [comment]
Awesome :) Thanks again!

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by mhlopko** [comment]
Hi @ilovezfs, would you mind updating the recipe for bazel [0.5.2](https://github.com/bazelbuild/bazel/releases)? That would be awesome :) Thanks!

**Comment by ilovezfs** [comment]
@mhlopko :tada: : https://github.com/Homebrew/homebrew-core/pull/15003

**Pull request closed without merging**
