### PR TITLE
volta 0.8.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
I think it is fine, as the releases are all pre-release, maybe we need to update the brew audit rule.

**Comment by SMillerDev** [comment]
I think we should ask upstream first. If there's a good reason we can update the audit.

**Comment by chenrui333** [comment]
> I think we should ask upstream first. If there's a good reason we can update the audit.

yeah, I did ask before, here is the old issue, https://github.com/volta-cli/volta/issues/738

**Comment by chenrui333** [comment]
never mind, that is actually a wrong reference. let me ask again.

**Comment by chenrui333** [comment]
Interesting, did we change the `prerelease` logic recently, I thought it would be `if previous release is pre-release, and the current release is also pre-release`, we won't fail the pre-release check?

**Comment by dtrodrigues** [comment]
I'm not a huge fan of software using the pre-release tag since at least on GitHub, pre-release indicates
>To notify users that the release is not ready for production and may be unstable, select This is a pre-release. 

It didn't seem worth it at the time to contact all existing pre-release formula maintainers, but as new versions are created, I'm of the opinion that they should not be marked as `pre-release` if they would like to be included in `homebrew/core`.

See: https://github.com/Homebrew/brew/pull/8321

**Comment by SMillerDev** [comment]
We should ask upstream if it's unstable software, as they are indicating. If it is, it should be hosted in a personal tap.

**Comment by chenrui333** [comment]
some folks consider pre-1.0.0 as pre-release, honestly, it is just a practice thing.

**Comment by SMillerDev** [comment]
And homebrew considers pre-releases not stable enough to ship. We shouldn't determine for upstream if something is stable or not.

**Comment by chenrui333** [comment]
> Hi @chenrui333, thanks for the question! Our general philosophy has been to mark it as a `pre-release` until we reach 1.0, for reasons of both stability and feature readiness. That said, at this point we definitely consider Volta stable, so the outstanding concern is having all of the features we consider necessary for 1.0.
> 
> However, given that version 1.0 itself serves as a marker for that feature-completeness and that we are stable and committed to a smooth upgrade process for new versions, I think it's reasonable to drop the `pre-release` label. Our next release will most likely be 0.9.0, which will include the last of the significant changes needed before 1.0, so at that point I think dropping the `pre-release` tag makes sense.

Will revisit after 0.9.0

**Pull request closed without merging**
