### PR TITLE
baresip 0.4.18

### PR DESCRIPTION
**Pull request by yous**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

Bump [baresip](http://www.creytiv.com/baresip.html) to 0.4.18.

### CODE REVIEW

**Comment by apjanke** [comment]
Build [failed](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1273/) on Yosemite only with a bunch of compiler errors, like this one.

```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfo.h:529:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1242:27: error: missing ',' between enumerators
  kLSHandlerOptionsDefault       __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_11, __IPHONE_4_0, __IPHONE_9_0, "Creator codes are deprecated on OS X.") = 0,
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1242:34: error: expected '= constant-expression' or end of enumerator definition
  kLSHandlerOptionsDefault       __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_11, __IPHONE_4_0, __IPHONE_9_0, "Creator codes are deprecated on OS X.") = 0,
                                 ^
/usr/include/Availability.h:167:108: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
                                                    __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep##_MSG(_msg)
                                                                                                           ^
```

Maybe this is an issue with not setting the target OS version correctly?

**Comment by yous** [comment]
I think the problem is that the program uses frameworks inside Xcode instead of them under `/System/Library/Frameworks/`. According to documentation, ["Locations for Public Frameworks"](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/InstallingFrameworks.html#//apple_ref/doc/uid/20002261-97184-TPXREF101), compiler looks for frameworks in the following way:

> When you build an application or other executable, the compiler looks for frameworks in `/System/Library/Frameworks` as well as any other location specified to the compiler.

But I can't find any locations pointing to inside Xcode in Makefiles, for example, `modules/coreaudio/module.mk` adds `-framework CoreAudio -framework AudioToolbox` to `$(MOD)_LFLAGS`. And that seems to be the right way to include framework according to ["Including Frameworks"](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/IncludingFrameworks.html#//apple_ref/doc/uid/20002257-BAJJBBHJ).

Is there any clue here?

**Comment by mikemcquaid** [comment]
@yous Does this work for you on your machine?

**Comment by yous** [comment]
@mikemcquaid Actually I don't have a Yosemite machine, only El Capitan. So unfortunately I can't test on it now. Is there a way to test on Yosemite without having actually machine? Maybe on VirtualBox or something?

**Comment by mikemcquaid** [comment]
We don't have an easy way. Let's see if the new Xcode helps at all.

**Comment by apjanke** [comment]
New Xcode won't matter: Yosemite is stuck on the older Xcode 7.2 series, since they're tied to OS releases.

I was able to reproduce locally on a Yosemite VM running under VMware. https://gist.github.com/39336d7d07f00af0560cd785ac98d9fa (@yous, if you wanted to work on debugging it, you could install a Yosemite VM on VirtualBox (free) or another VM host. You can download the Yosemite installer from the Mac App Store even if you're already running a newer version of the OS; just look under Purchased.)

```
In file included from modules/avcapture/avcapture.m:9:
...
In file included from /Applications/Xcode-7.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:60:
/Applications/Xcode-7.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/SecItem.h:985:49: error: expected ';' after top level declarator
extern const CFStringRef kSecUseAuthenticationUI
                                                ^
```

These look like the sort of version-related errors we saw back when we were switching SDKs and not setting the deployment target. But now we're setting `OSX_DEPLOYMENT_TARGET`, and my build log says it's 10.10 here, so I don't know why this is happening.

For example, this old issue - https://github.com/Homebrew/legacy-homebrew/pull/50137 - had the same error messages. But that was supposed to be fixed in https://github.com/Homebrew/legacy-homebrew/pull/50355.

I confirmed the env vars were being set by dumping the `env` as part of the build process.
```
MACOSX_DEPLOYMENT_TARGET=10.10
SDKROOT=/Applications/Xcode-7.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
```

Ping @ilovezfs since he figured out the SDK/deployment-target fix in the first place.

**Comment by yous** [comment]
I tried on Yosemite which is installed in VirtualBox as the following guide: https://blog.frd.mn/install-os-x-10-10-yosemite-in-virtualbox/.

Running `brew install baresip` succeeded after installing Xcode 7.2.1 on clean installed Yosemite, but `brew test baresip` fails and it seemed to try to use `~/.baresip` while test script specifies to use some temporary directory like the following:

```
/usr/local/Cellar/baresip/0.4.18/bin/baresip -f /tmp/baresip-test-20160509-1113-xtb1w5/.baresip -t
Last 15 lines from ~/Library/Logs/Homebrew/baresip/01.baresip:
2016-05-09 07:43:38 -0700

/usr/local/Cellar/baresip/0.4.18/bin/baresip
-f
/tmp/baresip-test-20160509-1113-xtb1w5/.baresip
-t

baresip v0.4.18 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
config: creating config template ~/.baresip/config
config: writing ~/.baresip/config: No such file or directory
main: configure failed: No such file or directory
ua: stop all (forced=1)
```

So I can't reproduce the build failure. Is there any additional package do I need to install? This is the result of `brew config`:

```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a90e7190b0e06379ea2c94561e5914af9370f0b
Last commit: 87 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9ff361d5a2f2226084c048312e1192a03daf1a50
Core tap last commit: 7 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: single-core 64-bit penryn
GCC-4.2: build 5666
Clang: 7.0 build 700
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
System Ruby: 2.0.0-p481
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: N/A
X11: N/A
```

Also the result of `brew list`:

```
apple-gcc42     automake        libre           lzlib           pkg-config
autoconf        cmake           librem          openssl         xctool
```

**Comment by rakkesh** [comment]
I have CLT `7.2.0.0.1.1447826929` installed without Xcode on Yosemite(VM); `brew` install/test runs fine.

```
% brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 2f20a42292e7d8d8f9ae9286632155a46e599700
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c04dd5ed8592011384904caa9aa1ee084a40b898
Core tap last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit haswell
Clang: 7.0 build 700
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
Java: 1.8.0_60
System Ruby: 2.0.0-p481
OS X: 10.10.5-x86_64
Xcode: N/A
CLT: 7.2.0.0.1.1447826929
X11: 2.7.8 => /opt/X11

% brew install baresip -s
==> Downloading http://www.creytiv.com/pub/baresip-0.4.18.tar.gz
######################################################################## 100.0%
==> make install PREFIX=/usr/local/Cellar/baresip/0.4.18 LIBRE_MK=/usr/local/opt/libre/share/re/re.mk LIBRE_INC=/usr/local/opt/libre/include/re LIBRE_SO=/usr/local/opt/libre/lib MOD_AUTODETECT= USE_
🍺  /usr/local/Cellar/baresip/0.4.18: 36 files, 823.4K, built in 24 seconds

% brew test baresip
Testing baresip
==> Using the sandbox
==> /usr/local/Cellar/baresip/0.4.18/bin/baresip -f /tmp/baresip-test-20160517-4516-1e3pzp9/.baresip -t

% <~/Library/Logs/Homebrew/baresip/01.baresip
2016-05-17 22:15:38 +0530

/usr/local/Cellar/baresip/0.4.18/bin/baresip
-f
/tmp/baresip-test-20160517-4516-1e3pzp9/.baresip
-t

baresip v0.4.18 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
config: creating config template /tmp/baresip-test-20160517-4516-1e3pzp9/.baresip/config
/usr/local/Cellar/baresip/0.4.18/lib/baresip/modules: detected 26 modules
Local network address: IPv4=en0:10.0.2.15
```
`"#{ENV["HOME"]}"` doesn't seem to expand correctly in the sandbox on your VM.

You could debug the test, `% brew test baresip --debug` and verify `HOME` env var in the shell.

Other than `libre` and `librem`, no other formulae are required for installing and testing `baresip`. 
Anyway, the output of `brew ls`,
```
autoconf    libevent      lzlib
automake    libffi        makedepend
baresip     libgcrypt     mitmproxy
bazel       libgpg-error  mpfr
cmake       libmpc        openssl
cpulimit    libpng        pcre
fontconfig  libre         pkg-config
freetype    librem        python
gcc         libressl      python3
gdb         libtasn1      ruby
gettext     libtool       the_silver_searcher
gmp         libxml2       w-calc
iftop       libyaml       wget
isl         lua           xz
jpeg        lz4           zsh-completions
```

**Comment by ilovezfs** [comment]
@rakkesh It works for you because you don't have Xcode installed.

@yous Try adding

```
ENV.delete("SDKROOT")
```
at the beginning of `def install`

**Comment by ilovezfs** [comment]
@apjanke Do we have any way to require CLT be installed? Even with ENV.delete("SDKROOT") or with https://github.com/Homebrew/brew/pull/251 `baresip` will fail if *only* Xcode is installed.

**Comment by DomT4** [comment]
> Do we have any way to require CLT be installed?

Sadly not.

**Comment by yous** [comment]
I installed baresip with `ENV.delete("SDKROOT")` added at the beginning of `def install`. But `brew test baresip` still fails on VM. Also it seems to have correct `ENV["HOME"]`.

```
$ brew test --debug baresip
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/baresip.rb
Testing baresip
==> Using the sandbox
/usr/local/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/baresip.rb
==> /usr/local/Cellar/baresip/0.4.18/bin/baresip -f /tmp/baresip-test-20160522-2630-1fnlmul/.baresip -t
Last 15 lines from /Users/yous/Library/Logs/Homebrew/baresip/01.baresip:
2016-05-22 10:05:13 -0700

/usr/local/Cellar/baresip/0.4.18/bin/baresip
-f
/tmp/baresip-test-20160522-2630-1fnlmul/.baresip
-t

baresip v0.4.18 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
config: creating config template /Users/yous/.baresip/config
config: writing /Users/yous/.baresip/config: No such file or directory
main: configure failed: No such file or directory
ua: stop all (forced=1)
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/local/Cellar/baresip/0.4.18/bin/baresip -f /tmp/baresip-test-20160522-2630-1fnlmul/.baresip -t
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 4
When you exit this IRB session, execution will continue.
irb(baresip):001:0> require 'pp'; pp ENV
{"Apple_PubSub_Socket_Render"=>
  "/private/tmp/com.apple.launchd.DMgI427dYy/Render",
 "CC"=>"/usr/bin/clang",
 "CFLAGS"=>
  "-Os -w -pipe -march=core2 -msse4.1 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
 "CMAKE_FRAMEWORK_PATH"=>
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks",
 "CMAKE_PREFIX_PATH"=>
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr",
 "CPATH"=>
  "/usr/local/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include",
 "CPPFLAGS"=>
  "-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
 "CXX"=>"/usr/bin/clang++",
 "CXXFLAGS"=>
  "-Os -w -pipe -march=core2 -msse4.1 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
 "HOME"=>"/tmp/baresip-test-20160522-2737-dkv20h",
 "HOMEBREW_ANALYTICS_ID"=>"UA-76679469-1",
 "HOMEBREW_ANALYTICS_USER_UUID"=>"F7349339-A9C8-4C2C-ADD1-B7E15150C3D6",
 "HOMEBREW_BREW_FILE"=>"/usr/local/bin/brew",
 "HOMEBREW_CELLAR"=>"/usr/local/Cellar",
 "HOMEBREW_CURL"=>"/usr/bin/curl",
 "HOMEBREW_ERROR_PIPE"=>"/tmp/homebrew20160522-2676-1un4di9/socket",
 "HOMEBREW_LIBRARY"=>"/usr/local/Library",
 "HOMEBREW_OSX_VERSION"=>"10.10.5",
 "HOMEBREW_OS_VERSION"=>"Mac OS X 10.10.5",
 "HOMEBREW_PREFIX"=>"/usr/local",
 "HOMEBREW_PROCESSOR"=>"Intel",
 "HOMEBREW_PRODUCT"=>"Homebrew",
 "HOMEBREW_REPOSITORY"=>"/usr/local",
 "HOMEBREW_RUBY_PATH"=>
  "/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby",
 "HOMEBREW_SYSTEM"=>"Macintosh",
 "HOMEBREW_USER_AGENT"=>"Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.10.5)",
 "HOMEBREW_USER_AGENT_CURL"=>
  "Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.10.5) curl/7.43.0",
 "HOMEBREW_VERSION"=>"0.9.9",
 "LANG"=>"en_US.UTF-8",
 "LC_CTYPE"=>"C",
 "LDFLAGS"=>
  "-L/usr/local/lib -Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
 "LOGNAME"=>"yous",
 "MACOSX_DEPLOYMENT_TARGET"=>"10.10",
 "MAKEFLAGS"=>"-j1",
 "OBJC"=>"/usr/bin/clang",
 "OBJCFLAGS"=>
  "-Os -w -pipe -march=core2 -msse4.1 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
 "OBJCXX"=>"/usr/bin/clang++",
 "OBJCXXFLAGS"=>
  "-Os -w -pipe -march=core2 -msse4.1 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
 "PATH"=>
  "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/ENV/scm:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin",
 "PKG_CONFIG_LIBDIR"=>
  "/usr/local/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10:/usr/lib/pkgconfig",
 "PWD"=>"/usr/local/Library/Taps/homebrew/homebrew-core",
 "SDKROOT"=>
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
 "SHELL"=>"/bin/bash",
 "SHLVL"=>"1",
 "SSH_AUTH_SOCK"=>"/private/tmp/com.apple.launchd.DJ67d1fVfJ/Listeners",
 "TERM"=>"xterm-256color",
 "TERM_PROGRAM"=>"Apple_Terminal",
 "TERM_PROGRAM_VERSION"=>"343.7",
 "TERM_SESSION_ID"=>"1FF39C5E-3465-4380-93C1-DC2F583A8453",
 "TMPDIR"=>"/var/folders/gs/2z8rw6vn7q571kg7yczvm6km0000gn/T/",
 "USER"=>"yous",
 "XPC_FLAGS"=>"0x0",
 "XPC_SERVICE_NAME"=>"0",
 "__CF_USER_TEXT_ENCODING"=>"0x1F5:0x0:0x0"}
```

**Comment by ilovezfs** [comment]
Yeah that's a sandbox violation since it's trying to write outside of the test path.

**Comment by UniqMartin** [comment]
Closing this since 0.4.19 has been merged in #2120. Nonetheless, thanks for the PR @yous!

**Pull request closed without merging**
