### PR TITLE
gradle 6.8.2

### PR DESCRIPTION
**Pull request by wolfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @wolfs. The test appears to failing on the ARM runner. Do we know that gradle doesn't work on Apple Silicon yet?

**Comment by wolfs** [comment]
> The test appears to failing on the ARM runner. Do we know that gradle doesn't work on Apple Silicon yet?

Gradle 7.0 will work on Apple Silicon. Gradle 6.8 should also work on Apple Silicon, only not so fast. The exception seems to be
```
java.lang.IllegalArgumentException: Unsupported class file major version 60
```

I think class file major version if Java 16, which Gradle 6.8 does not support.

**Comment by carlocab** [comment]
>I think class file major version if Java 16, which Gradle 6.8 does not support.

We only have Java 16 and Java 11 on Apple Silicon. Does Gradle 6.8 support Java 11?

**Comment by wolfs** [comment]
Yes, Gradle 6.8 supports Java 11.

**Comment by carlocab** [comment]
Thanks; let's use Java 11 on ARM then. Pushed the necessary changes here.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
