### PR TITLE
Merge pull request #1 from Homebrew/master

### PR DESCRIPTION
**Pull request by n-ham**
Pulling in recent changes

- [ y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ y] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by n-ham** [comment]
I'm unsure about what the proper way to manually push it is then? Previously I created a new branch in a cloned repo and then put in a PR?

**Comment by carlocab** [comment]
What change are you trying to make? If you look in your PR, it says that there are no files changed in this PR.

You may wish to have a look at this guide: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by n-ham** [comment]
Oh my bad, I merged the wrong branch from my cloned repo sorry, will put in a new one now. First update to Nift in a while..

**Comment by carlocab** [comment]
Try to avoid `git merge`, since you don't want to create merge commits. Use `git rebase` instead.

**Pull request closed without merging**
