### PR TITLE
Add versioning for `kubernetes-cli` formulae

### PR DESCRIPTION
**Pull request by cdayjr**
- [x] Have you followed the
      [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open
      [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the
      same formula update/change?
- [x] Have you built your formula locally with
      `brew install --build-from-source <formula>`, where `<formula>` is the
      name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the
      name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing
      `brew install <formula>`)?

---

Adding additional versions for `kubectl` per discussion here:
https://github.com/Homebrew/discussions/discussions/1286

Please read the above for additional context. I believe the current strategy of
only supporting the latest version of `kubernetes-cli` in brew leads to
unknowingly using unsupported `kubectl` versions with their clusters- I'm sure
I'm not the only one who had to learn about the kubectl versioning compatibility
the hard way.

- Added an alias for `kubernetes-cli@1.21` to `kubernetes-cli`
- Added the upstream supported `kubernetes-cli` versioned formulae:
  - `kubernetes-cli@1.20`
  - `kubernetes-cli@1.19`
- Removed the `kubernetes-cli` dependency from the `minikube` formula, which
  isn't necessary to use it, per below:

When running `minikube start` you'll get the following message:

```
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
```

`minikube kubectl` will download a version of `kubectl` with the exact version
of the local minikube cluster for management, so the `kubernetes-cli` dependency
isn't necessary, both for running the base minikube commands as well as running
management commands in your minikube cluster.

### CODE REVIEW

**Comment by cdayjr** [comment]
Just noticed this, https://docs.brew.sh/Formula-Cookbook#commit - will clean up the commits to conform to that style guide.

**Comment by SMillerDev** [comment]
Does this deprecated by upstream mean it still fulfills this requirement?

> Upstream should have a release branch for each formula version, and release security updates for each version when necessary. For example, PHP 7.0 was not a supported version but PHP 7.2 was in January 2020. By contrast, most software projects are structured to only release security updates for their latest versions, so their earlier versions are not eligible for versioning.

**Comment by cdayjr** [comment]
> Does this deprecated by upstream mean it still fulfills this requirement?
> 
> > Upstream should have a release branch for each formula version, and release security updates for each version when necessary. For example, PHP 7.0 was not a supported version but PHP 7.2 was in January 2020. By contrast, most software projects are structured to only release security updates for their latest versions, so their earlier versions are not eligible for versioning.

I'm not completely sure. Kubernetes v1.18 had a security release after v1.21 was released, which meant it was at the point it was no longer supported. 

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#important-security-information

but I guess because the older versions did not get an update, presumably it was just because 1.21 was released recently. I can pull those deprecated versions out.

**Comment by SMillerDev** [comment]
> When running minikube start you'll get the following message

Since we have a formula for kubectl it should just depend on it. We're making the user experience worse for everyone that does abide by Homebrew's evergreen policy if we remove the dependency.

**Comment by cdayjr** [comment]
> > When running minikube start you'll get the following message
> 
> Since we have a formula for kubectl it should just depend on it. We're making the user experience worse for everyone that does abide by Homebrew's evergreen policy if we remove the dependency.

`minikube` doesn't require `kubectl` for any of it's base functionality and keeping the dependency is a worse user experience if they spin up a cluster of a version that is incompatible with the latest `kubectl` version.

**Comment by cdayjr** [comment]
Looks like this is a no-go for now since despite 1.19 and 1.20 being officially supported, they do not support darwin/arm64 as that was only introduced in the latest, and that goes against this in the versioning policy:

> Versioned software should build on all Homebrew’s supported versions of macOS.

I'll make a separate PR for the minikube dependency removal and come back to this concept 1.22 comes out.

**Pull request closed without merging**
