### PR TITLE
node: symlink `npm`/`npx` into `bin`.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
These will then, in turn, be symlinked into `HOMEBREW_PREFIX/bin`.

The old way is:
- inconsistent with what we do with the `node@*` formulae
- means `nodenv` is unable to find `npm` when used with `brew nodenv-sync`
- results in a `HOMEBREW_PREFIX/bin/npm` that isn't cleaned up on `brew uninstall node`

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by Bo98** [comment]
`post_install` happens after linking I think so you will need to do HOMEBREW_PREFIX/bin -> bin symlinks too like:

https://github.com/Homebrew/homebrew-core/blob/0a8a9383afe6a635c6f2dc50ca0cb487d3ec5ebf/Formula/p/python%403.11.rb#L402-L405

**Comment by MikeMcQuaid** [comment]
@bo98 thanks, on it.

**Comment by Bo98** [comment]
Looks good but I wonder changing the symlink to instead be from bin to HOMEBREW_PREFIX/bin (rather than directly from node_modules) will fix a commonly reported issue of npm symlink being left behind on uninstall/unlink: https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core+npm+symlink&type=issues

**Comment by MikeMcQuaid** [comment]
@bo98 Good idea and: confirmed if you do the symlinks how was suggested there this no longer occurs. Should be good to 🚢 now.

**Review by Bo98 — APPROVED** [review]
Thanks!

**Pull request merged**
