### PR TITLE
buf: delete

### PR DESCRIPTION
**Pull request by bufdev**
This deletes the buf formula introduced in https://github.com/Homebrew/homebrew-core/pull/117863. The Buf team maintains a tap for buf at github.com/bufbuild/homebrew-buf, which is extensively documented and also fits into our release strategy. We cannot commit to maintaining this in homebrew-core, and this being in two places will confuse our users.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
It meets all Homebrew core requirements. I see no reason to revert this.

**Comment by chenrui333** [comment]
You can also see what Hashicorp is doing for their custom tap as well.

**Comment by bufdev** [comment]
@chenrui333 it would have been great if you would have talked to the team first - this is making the Buf team's job harder to ship reliable OSS software.

**Comment by SMillerDev** [comment]
You are releasing under an open source license but "please ask before distributing" is not really in the spirit of open source.

**Comment by bufdev** [comment]
This obviously isn't a legal issue, and of course others can distribute if abiding by the license, but making sure OSS users have a reliable and consistent way to do things that is as up to date as possible definitely feels in the spirit of OSS in our view. However we understand there are competing opinions.

**Comment by SMillerDev** [comment]
If your main concern is being up to date I'd like to point out that the merge speed of Homebrew/core is good enough for  [GitHub](https://cli.github.com/manual/installation) for example.

**Comment by fxcoudert** [comment]
We are a software distribution. We help users by making it simple to install things from one central source, yet provide a way to do this modularly so that other organisations (you included) can also use the same platform for your own use.

There are many ways in which homebrew-core is advantageous for users: easier to discover (not separate tap installation) and we provide binaries for all supported platforms, so it's a faster and easier install: `go` is a 176 MB download, so ten times the size of the `buf` bottle.

Yes, the fact that it will take a bit more time to distribute updates is the other side of that coin, but you can minimise this by integrating a homebrew-core PR into your release process. (You stated in the other PR that you do not wish to do that, and again, we're not asking you to do that: it's just one possibility, but the software will be updated in homebrew-core anyway.)

**Comment by bufdev** [comment]
We're OSS maintainers ourselves - we get that there are competing viewpoints, and are not asking you to change your processes to agree with ours - it's totally your call how on you want to treat this, as it should be.

From our angle, we respectfully disagree here for a few reasons:

- We are busy on many items - having another team implicitly ask us to change our release processes because they merged in a PR in a major distribution repository (homebrew-core) is asking us to change our priorities. Our homebrew tap has served our users well, and changing our release processes is not a top priority item for us. We wouldn't presume to do something that forces the homebrew-core team to change their priorities.
- Users will now file issues on our repositories asking us to update homebrew-core, which is adding more work for us as OSS maintainers. We're trying our best to serve our community, and this will just serve as an additional distraction for the team.

I can see the viewpoint from the homebrew-core team that homebrew-core is a better experience for end-users than taps, but while we won't agree on this point, that hasn't been my experience as an author and maintainer - I used to get our projects merged into homebrew-core, but it caused more pain for both users and for us in maintenance than it was worth, hence our usage of taps now.

**Comment by chenrui333** [comment]
> I can see the viewpoint from the homebrew-core team that homebrew-core is a better experience for end-users than taps, but while we won't agree on this point, that hasn't been my experience as an author and maintainer - I used to get our projects merged into homebrew-core, but it caused more pain for both users and for us in maintenance than it was worth, hence our usage of taps now.

can you pinpoint which PRs? Based on [the search](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3Abufdev+), I dont see we gave you a hard time before?

**Comment by chenrui333** [comment]
On the other side, I can also see this inclusion [would help your user as well](https://github.com/bufbuild/homebrew-buf/issues/16).

**Pull request closed without merging**
