### PR TITLE
mprocs 0.6.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Needs a
```ruby
uses_from_macos "python" => :build
```

**Comment by Porkepix** [comment]
> Needs a
> 
> ```ruby
> uses_from_macos "python" => :build
> ```

I don't get why it would need something telling to use the python from macOS while the error happens on a Linux runner?

Also, I checked their repository and didn't found any mention of python anywhere.

**Comment by carlocab** [comment]
> I don't get why it would need something telling to use the python from macOS while the error happens on a Linux runner?

`uses_from_macos` is not for macOS. It is for Linux. It does nothing on macOS (unless there is a `since:` argument).
 
> Also, I checked their repository and didn't found any mention of python anywhere.

The Python dependency doesn't come from `mprocs`. It comes from the `xcb` crate.

**Comment by Porkepix** [comment]
> > I don't get why it would need something telling to use the python from macOS while the error happens on a Linux runner?
> 
> `uses_from_macos` is not for macOS. It is for Linux. It does nothing on macOS (unless there is a `since:` argument).

Okay so I don't understand the (argument? keyword? don't even know how to name it here); English isn't my native language, but I read `uses_from_macos` as "On macOS, use this package already provided by the OS, rather than using one provided by homebrew", what am I reading wrong in this?

**Comment by carlocab** [comment]
```ruby
uses_from_macos "foo"
```
is equivalent to
```ruby
on_linux do
  depends_on "foo"
end
```
I can see that it's a little misleading, but that's what `uses_from_macos` means in Homebrew formulae. i.e. "do nothing on macOS, but add a dependency on Linux"

**Comment by carlocab** [comment]
Well, `uses_from_macos "x"` means that the formula uses `x` from macOS, so `brew` doesn't need to do anything there. We don't want to assume the system provides `x` on Linux, so we need a `depends_on "x"`.

> Yes, the very old Ubuntu 16.04 will provide a python2 and not a python3, but this is also what provides macOS.

The build complained about a missing `python3`, so we need `python3` and not `python2`. When building formulae, we assume development tools are installed (Xcode/CLT), so `python3` is available. (You won't get anywhere trying to build formulae if you have no dev tools installed.)

Looks like this also needs
```ruby
on_linux do
  depends_on "libxcb"
end
```

**Comment by Porkepix** [comment]
> Well, `uses_from_macos "x"` means that the formula uses `x` from macOS, so `brew` doesn't need to do anything there. We don't want to assume the system provides `x` on Linux, so we need a `depends_on "x"`.
> 
> > Yes, the very old Ubuntu 16.04 will provide a python2 and not a python3, but this is also what provides macOS.
> 
> The build complained about a missing `python3`, so we need `python3` and not `python2`. When building formulae, we assume development tools are installed (Xcode/CLT), so `python3` is available. (You won't get anywhere trying to build formulae if you have no dev tools installed.)
> 
> Looks like this also needs
> 
> ```ruby
> on_linux do
>   depends_on "libxcb"
> end
> ```

What does CLT stands for? And why `libxcb` would only be needed on Linux here?
As for the syntax, I guess mixing `on_linux` and `use_from_mac` would be even worth, so everything can be in the `on_linux`, right?

**Comment by carlocab** [comment]
CLT = Command Line Tools

Most other formulae use `uses_from_macos` for dependencies that are available on macOS, so we should do that here.

**Comment by Porkepix** [comment]
> CLT = Command Line Tools
> 
> Most other formulae use `uses_from_macos` for dependencies that are available on macOS, so we should do that here.

Even considering there will be a `on_linux` block? I'd consider it would be better to group both `python` and `libxcb` within, don't you agree?

**Comment by carlocab** [comment]
> Even considering there will be a `on_linux` block?

Yes.

> I'd consider it would be better to group both `python` and `libxcb` within, don't you agree?

No. We should be consistent with other formulae.

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by SMillerDev** [comment]
The main benefit of `uses_from_macos` vs `on_linux` is that it conveys information about the dependencies. Anything in an `on_linux` block will never be needed on a mac because the software does not need it there. When a `uses_from_macos` block is used however, it indicates that the dependency exists on macos too, but the system can take care of it. That provides a huge benefit when new macOS versions remove or add tools, since we can then keep track of where the system version can be used.

**Comment by Porkepix** [comment]
Thanks for the explanations, it makes sense. It's just that the keyword in itself doesn't convey very well that it applies to Linux. Actually by reading it, what I understood from it was that the dependency was only needed on macOS, and that it was preferred to rely on macOS' one rather than brewed ones.

**Pull request closed without merging**
