### PR TITLE
lmod: rebuild luarocks + add test

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://github.com/Homebrew/discussions/discussions/218#discussioncomment-146086

### CODE REVIEW

**Comment by SMillerDev** [comment]
The test should also be updated to catch this.

**Comment by carlocab** [comment]
I was thinking that too. Alas, I don't know what the appropriate test should be. I'll look into it.

**Comment by carlocab** [comment]
I don't know why CI didn't catch this. I can't even build lmod locally without this PR.

**Comment by SMillerDev** [comment]
Unless you change something in the formula it doesn't build from source. And if the test doesn't catch it you'll never know.

**Comment by carlocab** [comment]
I see, ok. Still trying to work out the test...

**Comment by carlocab** [comment]
Strangely enough, `lmod` was caught in my bump to lua5.4.2: https://github.com/Homebrew/homebrew-core/actions/runs/398547104

I think I've worked out an additional test, but I'm trying to see if it'll catch the previous breakage.

**Comment by carlocab** [comment]
I think I need help translating the following:

Say I have the following script written to `testpath/"lmodtest.sh"`:

```
#!/bin/sh
source #{init_sh}
module list
```

and I want to be able to run the following shell command from the test block:

    sh lmodtest.sh > lmodtest.out 2>&1

and then verify that the content of `lmodtest.out` is `No modules loaded`. How do I do that?

The following didn't work:

```
    sh_init = "#{prefix}/init/sh"

    (testpath/"lmodtest.sh").write <<~EOS
      #!/bin/sh
      source #{sh_init}
      module list
    EOS

    system "sh", "lmodtest.sh", ">", "#{testpath}/lmodtest.out", "2>&1"
    assert_match "No modules loaded", File.read("#{testpath}/lmodtest.out")

```

**Comment by carlocab** [comment]
Added a new test. Confirmed that it fails before revision, and succeeds after.

**Comment by carlocab** [comment]
@SMillerDev I don't mean to rush you, but just a heads up that CI is green.

**Review by SMillerDev — APPROVED** [review]
Thanks @carlocab  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
