### PR TITLE
minetest: Only download dependencies on build

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Doesn't the app link against the libraries?

**Comment by SeekingMeaning** [comment]
Yes, it stores the shared libraries in `minetest.app/Contents/Frameworks`.

**Comment by fxcoudert** [comment]
Wow… bad practice :( There's a reason why they're shared libraries

**Comment by SeekingMeaning** [comment]
Ah. Maybe I should open a new pull request for the non-dependencies changes?

**Comment by EricFromCanada** [comment]
And bump to 5.1.1 also.

**Comment by SeekingMeaning** [comment]
What the... I didn't even notice 5.1.1 was released! The main website isn't updated hah!

**Comment by SeekingMeaning** [comment]
Moved non-dependencies changes to #49197

**Pull request closed without merging**
