### PR TITLE
youtube-dl 2017.01.10

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JaKXz** [comment]
@neutric anything I can do to help get this merged? v2017.01.08 is broken on playlists atm and I'm in need of that feature atm.

**Comment by JaKXz** [comment]
Seems that the `sha256` is actually: 

```
e6fe22a447629470002f31d887b13fd4b5e7e0b33dcad1cf27fe736d1c425d2c
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@neutric thanks for the version bump

**Pull request closed without merging**
