### PR TITLE
cortexso 0.1.4

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
hey @louis-jan, it looks like `cortex-cpp` is being published to npm [without the actual source code](https://github.com/janhq/cortex/blob/4a09e8c4d6fbf3ea51c18b96c3c698bf95e70649/cortex-cpp/package.json#L38-L39) (so it only works with the prebuilt binaries). do you mind also publishing the source?

**Comment by louis-jan** [comment]
> hey @louis-jan, it looks like `cortex-cpp` is being published to npm [without the actual source code](https://github.com/janhq/cortex/blob/4a09e8c4d6fbf3ea51c18b96c3c698bf95e70649/cortex-cpp/package.json#L38-L39) (so it only works with the prebuilt binaries). do you mind also publishing the source?

Hey @branchvincent, thank you for the reminders. Ye, I'm working on it now.

**Comment by louis-jan** [comment]
Hey @branchvincent. We've published the Cortex-CPP source code on npm so it can be compiled from source. Please help us review the new bump PR.
https://github.com/Homebrew/homebrew-core/pull/180461

**Comment by branchvincent** [comment]
thanks for the ping @louis-jan, left some comments there

**Pull request closed without merging**
