### PR TITLE
imagemagick 6.9.6-8

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

Please remember to
```
brew mirror imagemagick
```
when merging.

### CODE REVIEW

**Comment by zmwangx** [comment]
Revision a bump of revdeps because ABI compatibility has been broken and the dylib versions have been bumped.

**Comment by ryofurue** [comment]
The fact that it's "normal" doesn't automatically mean that it's a "desireable behavior".  Are you sure that nobody can do absolutely nothing to automate the update?

Ryo

**Comment by ilovezfs** [comment]
We could, by bumping the emacs revision when imagemagick is upgraded. That will force reinstalls of emacs for everyone including the people who are using the default configuration and don't need a reinstall.

**Comment by ryofurue** [comment]
Does that mean that there is no mechanism that options to "brew install" can affect the bumping behavior?  If so, shouldn't homebrew be improved to take care of that scenario?

The error we get ("LSOpenURLsWithRole() failed") is so obscure that normal users wouldn't be able to fix it.

**Comment by ilovezfs** [comment]
Nope. You may want to use the emacs cask to avoid this situation: https://github.com/caskroom/homebrew-cask/blob/master/Casks/emacs.rb

**Comment by zmwangx** [comment]
Well, `--with-imagemagick` is not related to `--with-cocoa`... Here's a list of things you can do when you compile with IM suppport: https://www.emacswiki.org/emacs/ImageMagick. You can simply drop `--with-imagemagick` if you don't need those features.

**Comment by zmwangx** [comment]
(The cask isn't compiled with IM support.)

**Comment by ilovezfs** [comment]
Sigh.

**Comment by ilovezfs** [comment]
@zmwangx any thoughts on whether imagemagick upgrades should include emacs revision bumps?

**Comment by ryofurue** [comment]
> Nope. You may want to use the emacs cask to avoid this situation: 

Thank you for your help!  But, I don't understand the meaning of your "nope". Does that mean that it's impossible to detect that emacs depends through a non-default option on imagemagick and the latter is updated?  Brew doctor sometimes detects missing dependencies. I wonder if that feature could be extended, for example?  I'm not saying this for my own purpose.  Can't this can happen to any users of any package who use non-default options?

I'm not a developer and what I'm saying may be off the mark. . . .

**Comment by ilovezfs** [comment]
@ryofurue it's possible, sure. But someone would need to implement it. There's no existing mechanism for that in brew.

**Comment by zmwangx** [comment]
> whether imagemagick upgrades should include emacs revision bumps?

Don't think so.

This ABI-breaking-dep-upgrade-breaks-formula-compiled-with-options problem has been there since I started using brew years ago. IMO the best we could do is issue a warning and encourage a reinstall when some linkage is broken where it wasn't pre-upgrade.

**Comment by zmwangx** [comment]
> Does that mean that it's impossible to detect that emacs depends through a non-default option on imagemagick and the latter is updated?

ImageMagick is updated all the time: https://github.com/Homebrew/homebrew-core/pulls?utf8=%E2%9C%93&q=is%3Apr%20imagemagick. Most of them are ABI-compatible updates.

**Comment by ryofurue** [comment]
> Most of them are ABI-compatible updates.

I see. That means that this problem isn't frequent enough to worry too much about.

**Pull request closed without merging**
