### PR TITLE
libpng 1.6.27

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
New upstream release.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
The failures here don't look related to libpng; they are all installation failures of other packages.

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by rleigh-codelibre** [comment]
@nijikon Some of the failures here are due to e.g. coreutils not being installed on the build nodes, and the package installation failing as a consequence.  Not sure if that's some transient thing, a setup issue or something else.

**Comment by ilovezfs** [comment]
It's a deficiency in test-bot.

**Comment by ilovezfs** [comment]
The couchdb fail is unrelated to the coreutils stuff but is also likely unrelated to libpng. But that one is indeed broken.

**Comment by ilovezfs** [comment]
couchdb is one of the bad bottles from when config files weren't getting included. It absolutely should be rebuilt but has nothing to do with libpng.

**Comment by ilovezfs** [comment]
There's also another possibly legitimate failure here:
```
Error Message

failed: brew audit libpng --online

Stacktrace

        Error: 1 problem in 1 formula
libpng:
  * The homepage http://www.libpng.org/pub/png/libpng.html is not reachable (HTTP status code 000
``

**Comment by rleigh-codelibre** [comment]
@ilovezfs Maybe a transient issue?  That URL is reachable for me locally.

**Comment by ilovezfs** [comment]
@rleigh-codelibre My guess is it's a problem with the El Capitan VM timing out during the check.

**Comment by ilovezfs** [comment]
@rleigh-codelibre shipped! Thanks for the PR.

**Pull request closed without merging**
