### PR TITLE
llvm 12.0.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Yep, checking which patches can be removed now. The last one is a bit tricky to track down.

**Comment by carlocab** [comment]
I'm really confused by this last patch: https://github.com/llvm/llvm-project/commit/c86f56e32e724c6018e579bb2bc11e667c96fc96

It's not in the release tag, despite the GitHub UI suggesting it should be. In fact, there's no evidence of it on the main branch at all...

**Comment by carlocab** [comment]
Guess I was too optimistic to hope this would build without a new set of patches.

**Comment by carlocab** [comment]
```
CMake Error: failed to create symbolic link '/tmp/llvm-20210414-76838-8bclbi/llvm-project-12.0.0.src/llvm/build/runtimes/builtins-bins/outline_atomic_helpers.dir/outline_atomic_ldeor2_2.S': file already exists
15921
make[5]: *** [outline_atomic_helpers.dir/outline_atomic_ldeor2_2.S] Error 1
15922
make[5]: *** Deleting file `outline_atomic_helpers.dir/outline_atomic_ldeor2_2.S'
15923
make[4]: *** [CMakeFiles/clang_rt.cc_kext_arm64_osx.dir/all] Error 2
```

**Comment by carlocab** [comment]
Mojave:
```
Error: 22 failed steps!
brew linkage --test castxml
brew test --retry --verbose castxml
brew linkage --test ccls
brew test --retry --verbose ccls
brew test --retry --verbose coin3d
brew test --retry --verbose csound
brew test --retry --verbose enzyme
brew test --retry --verbose faust
brew test --retry --verbose gjs
brew test --retry --verbose halide
brew linkage --test include-what-you-use
brew test --retry --verbose include-what-you-use
brew test --retry --verbose ispc
brew test --retry --verbose klee
brew test --retry --verbose ldc
brew test --retry --verbose nvc
brew test --retry --verbose odin
brew test --retry --verbose pyside
brew test --retry --verbose pyside@2
brew test --retry --verbose rtags
brew test --retry --verbose standardese
brew test --retry --verbose zig
```

**Comment by carlocab** [comment]
Catalina & Big Sur:

```
Error: 22 failed steps!
brew linkage --test castxml
brew test --retry --verbose castxml
brew linkage --test ccls
brew test --retry --verbose ccls
brew test --retry --verbose coin3d
brew test --retry --verbose csound
brew test --retry --verbose enzyme
brew test --retry --verbose faust
brew test --retry --verbose gjs
brew test --retry --verbose halide
brew linkage --test include-what-you-use
brew test --retry --verbose include-what-you-use
brew test --retry --verbose ispc
brew test --retry --verbose klee
brew test --retry --verbose ldc
brew test --retry --verbose nvc
brew test --retry --verbose odin
brew test --retry --verbose pyside
brew test --retry --verbose pyside@2
brew test --retry --verbose rtags
brew test --retry --verbose standardese
brew test --retry --verbose zig
```

**Comment by Bo98** [comment]
That's an extraordinarily high number of revision bumps.

> dyld: Library not loaded: @rpath/libc++abi.1.dylib
>   Referenced from: /usr/local/opt/llvm/lib/libc++.1.dylib
>   Reason: image not found

When did we start shipping `libc++abi` again? We removed it for exactly this reason.

**Comment by abpostelnicu** [comment]
> I'm really confused by this last patch: [llvm/llvm-project@c86f56e](https://github.com/llvm/llvm-project/commit/c86f56e32e724c6018e579bb2bc11e667c96fc96)
> 
> It's not in the release tag, despite the GitHub UI suggesting it should be. In fact, there's no evidence of it on the main branch at all...
> 
> I'm not even sure why we need it. We're not building LLDB standalone. Is this CMake module is somehow invoked while building LLDB? If it is, then the naming scheme is very unfortunate.
> 
> I'm removing it.

That should be removed. It wasn't accepted in the official release, it's been backed-out.

**Comment by carlocab** [comment]
@abpostelnicu already removed.

**Comment by abpostelnicu** [comment]
@carlocab why don't we move to Ninja build system, it's way better supported by LLVM and almost all of llvm toolchain providers use it, take as an example [Mozilla](https://searchfox.org/mozilla-central/source/build/build-clang/build-clang.py#127).

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/blob/d9803523cc5cfae711b6fa94c523d0de36ca63e5/Formula/llvm.rb#L65-L66

**Comment by abpostelnicu** [comment]
> of

I know about that, but I built it with ninja without having any issues and also this doesn't reproduce the symlink issue that make has.

**Comment by Bo98** [comment]
We can try Ninja and inspect the bottle size when it's done. We rejected Ninja in the past because the difference in the size of the bottle was several GB, which is a significant regression, but maybe it's been fixed since.

**Review by abpostelnicu — CHANGES_REQUESTED** [review]
This is incorrect, please don't do this, otherwise `include-what-you-use` will be broken. Save llvm 11 as another formula, like I did in my PR, llvm@11 and make it a dependency here. 

`include-what-you-use` doesn't work well with clang12, it's only compatible with clang 11 because in 12 lots of the AST semantics has been changed.

**Comment by abpostelnicu** [comment]
> We can try Ninja and inspect the bottle size when it's done. We rejected Ninja in the past because the difference in the size of the bottle was several GB, which is a significant regression, but maybe it's been fixed since.

This is a valid point, maybe cause of the missing symlinks that ninja is not doing and it uses copy instead?

**Comment by carlocab** [comment]
> This is incorrect, please don't do this, otherwise `include-what-you-use` will be broken. Save llvm 11 as another formula, like I did in my PR, llvm@11 and make it a dependency here.
> 
> `include-what-you-use` doesn't work well with clang12, it's only compatible with clang 11 because in 12 lots of the AST semantics has been changed.

I'm aware. I wanted to test a build with llvm 12 first. In fact, it looks like all the formulae that currently depend on `llvm` need `llvm@11`.

**Comment by carlocab** [comment]
I actually suspect the build failure on ARM is a parallelization issue. I was thinking about doing
```ruby
ENV.deparallelize if Hardware::CPU.arm?
```
I doubt the bottle size issue has been fixed in Ninja.

**Comment by abpostelnicu** [comment]
> I actually suspect the build failure on ARM is a parallelization issue. I was thinking about doing
> 
> ```ruby
> ENV.deparallelize if Hardware::CPU.arm?
> ```
> 
> I doubt the bottle size issue has been fixed in Ninja. It was still there last time I built `llvm` with Ninja, which wasn't too long ago.

Are you referring to these errors?

2021-04-15T09:20:55.5814010Z /opt/homebrew/opt/llvm/include/llvm/IR/DerivedTypes.h:436:22: note: candidate function not viable: no known conversion from 'unsigned int' to 'llvm::ElementCount' for 2nd argument
2021-04-15T09:20:55.5815040Z   static VectorType *get(Type *ElementType, ElementCount EC);
2021-04-15T09:20:55.5815510Z                      ^
2021-04-15T09:20:55.5816710Z /opt/homebrew/opt/llvm/include/llvm/IR/DerivedTypes.h:444:22: note: candidate function not viable: no known conversion from 'unsigned int' to 'const llvm::VectorType *' for 2nd argument
2021-04-15T09:20:55.5817740Z   static VectorType *get(Type *ElementType, const VectorType *Other) {
2021-04-15T09:20:55.5818180Z                      ^
2021-04-15T09:20:55.5818810Z /opt/homebrew/opt/llvm/include/llvm/IR/DerivedTypes.h:438:22: note: candidate function not viable: requires 3 arguments, but 2 were provided
2021-04-15T09:20:55.5819760Z   static VectorType *get(Type *ElementType, unsigned NumElements,
2021-04-15T09:20:55.5820250Z                      ^
2021-04-15T09:20:55.5821010Z In file included from /tmp/enzyme-20210415-38254-a7wv0x/Enzyme-0.0.9/enzyme/Enzyme/EnzymeLogic.cpp:30:
2021-04-15T09:20:55.5822220Z /tmp/enzyme-20210415-38254-a7wv0x/Enzyme-0.0.9/enzyme/Enzyme/AdjointGenerator.h:1160:18: error: no matching function for call to 'get'
2021-04-15T09:20:55.5823490Z             FT = VectorType::get(FT, CV->getType()->getNumElements());

**Comment by carlocab** [comment]
No, I'm referring to the `llvm` build failure on ARM. That's a build failure for `enzyme`.

**Comment by Bo98** [comment]
> I'm aware. I wanted to test a build with llvm 12 first. In fact, it looks like all the formulae that currently depend on `llvm` need `llvm@11`.

The problem shown with `libc++abi` is unlikely to be fixed by any revision bump. There's something fundamentally broken with the way it is being linked.

**Comment by carlocab** [comment]
Re `libcxxabi` https://github.com/Homebrew/homebrew-core/pull/62798#pullrequestreview-510996798

**Comment by Bo98** [comment]
> The previous formula already did that however only for HEAD with a note to check when llvm-11 is released.

I wrote that note and that doesn't mean start shipping libcxxabi as a resource. The note meant to remove one line from the install block.

**Comment by carlocab** [comment]
See edit. Seems the build fails without it?

**Comment by Bo98** [comment]
Ah cool, I completely forgot that commit. Makes sense, but there's still something broken here that we need to fix.

**Comment by Bo98** [comment]
Before:

```
Load command 12
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)
Load command 13
          cmd LC_RPATH
      cmdsize 88
         path /tmp/llvm-20210402-54252-g30z3i/llvm-project-11.1.0.src/llvm/build/./lib (offset 12)
```


After: no `LC_RPATH`

I'll see if I can find what's changed to regress this.

**Comment by Bo98** [comment]
https://github.com/llvm/llvm-project/commit/8d51969bd40a0351ed2f0be54c61b1e62b0b433c

Maybe `-DCMAKE_INSTALL_RPATH=@loader_path/../lib` so we don't need to bake in paths?

**Comment by carlocab** [comment]
I was just about to push a similar change, except using `opt_lib`. Your suggestion is better. Let me just fix that up again.

**Comment by Bo98** [comment]
You'll probably find a lot of the revision bumps are no longer needed.

**Comment by carlocab** [comment]
Deparallelizing the ARM build worked. Still a bunch of failures though:
```
Error: 13 failed steps!
brew linkage --test castxml
brew test --retry --verbose castxml
brew linkage --test ccls
brew test --retry --verbose ccls
brew test --retry --verbose coin3d
brew test --retry --verbose halide
brew test --retry --verbose ldc
brew test --retry --verbose pyside
brew test --retry --verbose pyside@2
brew test --retry --verbose standardese
brew install --verbose --build-bottle faust
brew test --verbose include-what-you-use
brew install --verbose --build-bottle rtags
```

**Comment by carlocab** [comment]
Building with `ninja` still massively inflates the bottle size.
```
❯ ls -l
.rw-r--r--@ 3.3k carlocab 15 Apr 19:37 llvm@12--12.0.0.big_sur.bottle.json
.rw-r--r--@ 1.3G carlocab 15 Apr 19:38 llvm@12--12.0.0.big_sur.bottle.tar.gz
.rw-r--r--@ 3.3k carlocab 15 Apr 19:40 llvm@12--12.0.0.catalina.bottle.json
.rw-r--r--@ 1.3G carlocab 15 Apr 19:41 llvm@12--12.0.0.catalina.bottle.tar.gz
❯ tar -xf llvm@12--12.0.0.big_sur.bottle.tar.gz
❯ du -hc -d1 llvm@12
7.3G    llvm@12/12.0.0
7.3G    llvm@12
7.3G    total
```
It also breaks the Linux build.

**Comment by Bo98** [comment]
Hmm, seems like the RPATH didn't work. I guess we'll see if it added any `LC_RPATH` or not.

`castxml` and `ccls` require a revision bump though.

**Comment by carlocab** [comment]
Checked the bottle built using `ninja`. No `RPATH`.
```
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1292.60.1
compatibility version 1.0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libc++abi.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 13
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 632360
 datasize 2656
Load command 14
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 635016
 datasize 400
```

**Comment by Bo98** [comment]
Hmm, not quite sure why - the flag is correct.

**Comment by carlocab** [comment]
Some libraries do get built with the specified `RPATH`, though. Except it looks to me like these were libraries that already had a provisional `RPATH` that was just overridden by `CMAKE_INSTALL_RPATH` (unless this is a `make` vs `ninja` difference).

For example, in `libLLVM.dylib`, without `CMAKE_INSTALL_RPATH` (using `make`):
```
Load command 18
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)
Load command 19
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 71382032
 datasize 164656
Load command 20
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 71546688
 datasize 21664
```
with `CMAKE_INSTALL_RPATH` (using `ninja`):
```
Load command 18
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 160182240
 datasize 1242080
Load command 19
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 161424320
 datasize 27040
Load command 20
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)
```

**Comment by Bo98** [comment]
LLVM's build scripts by default set most RPATHs to `@loader_path/../lib` if `CMAKE_INSTALL_RPATH` is not set. Otherwise it'll let CMake handle it (which should mean it is based on what `CMAKE_INSTALL_RPATH` is set to).

The "default RPATH" part was removed from `libc++`, `libc++abi` and `libunwind`, but `CMAKE_INSTALL_RPATH` should still work.

**Comment by Bo98** [comment]
Try `-DRUNTIMES_CMAKE_ARGS=-DCMAKE_INSTALL_RPATH=@loader_path/../lib`. This should be in the `on_macos` block.

While we're here:

* The Mojave linker workaround is no longer required now (even in `llvm@11`) that we have bumped the minimum CLT version of that to match Xcode.
* Is it worth trying `uses_from_macos "libffi", since: :catalina`?

**Comment by carlocab** [comment]
Go ahead and push/rebase those. I kicked off a build locally to experiment with and now my woefully underpowered laptop is basically unusable.

**Comment by Bo98** [comment]
> I kicked off a build locally to experiment with and now my woefully underpowered laptop is basically unusable.

You're braver and more patient than me. If a build takes longer than 10 minutes I usually give up.

**Comment by Bo98** [comment]
Few notes:

* `enzyme` - appears to support LLVM 13 - it just needs a patch to support 12. LLVM 11 seems to work for now though.
* `faust` - I dropped this commit because it doesn't support LLVM 11.1 without a patch. It does support LLVM 13, and can support LLVM 12 with a patch that I'll need to submit upstream. It might well not need a revision bump anyway.
* `ispc` - I dropped this commit because it does not support LLVM 11 - see my other PR for that (which might cover LLVM 12 too). It probably doesn't need a revision bump anyway.
* `klee` - Just to note here for future reference: LLVM 12 support is in a draft PR just now.
* `nvc` - I don't see how this would be LLVM 12 incompatible. Seems like something is wrong with how things are linked. Stuck with the LLVM 11 commit for now but perhaps worth revisiting.
* `rtags` - I think the issues seen here all stem back to the RPATH issue

**Comment by carlocab** [comment]
> If a build takes longer than 10 minutes I usually give up.

Me too, but I was trying to use it as a commitment device to not stay up all night. It kinda worked.

Re notes -- sounds fine to me. I just switched a formula wherever the build logs had an error I didn't recognise.

**Comment by carlocab** [comment]
ARM:

```
Error: 3 failed steps!
brew test --retry --verbose halide
brew test --verbose include-what-you-use
brew install --verbose --build-bottle nvc
```

All Intel Nodes:

```
Error: 3 failed steps!
brew test --retry --verbose halide
brew test --retry --verbose odin
brew test --verbose include-what-you-use
```

Will take a closer look soon.

**Comment by Bo98** [comment]
```
dyld: lazy symbol binding failed: Symbol not found: __ZNK4llvm6Module13getTypeByNameENS_9StringRefE
  Referenced from: /opt/homebrew/opt/halide/lib/libHalide.11.dylib
  Expected in: /opt/homebrew/opt/llvm/lib/libLLVM.dylib
```

This is fixed by a revision bump but it's disappointing that we don't have ABI versioning for libLLVM. I'll need to see why this is because we could be shipping more broken things here without us knowning.

Looks like the RPATH fix worked though which is good news.

**Comment by carlocab** [comment]
Yep, just saw that too. As an aside: why does `halide` depend on both `libomp` and `llvm`?

**Comment by Bo98** [comment]
Not sure, it shouldn't need to.

**Comment by carlocab** [comment]
`odin` just needs `llvm@11`, I think. It seems to be calling `opt` with the wrong command-line flags for now. Will probably (?) be fixed at the next release.

**Comment by Bo98** [comment]
Yes, in https://github.com/llvm/llvm-project/commit/f4f7df037e71fa77b06a37d86f2596db47d583d0 `-die` was removed in favour of `-dce`.

**Comment by Bo98** [comment]
I'm thinking of something like https://github.com/Bo98/llvm-project/commit/bed10d1fe2510d1851cf57612eb083aad15ac4fb to fix ABI versioning here.

Of course, I'll need to test whether that works and discuss with upstream about it.

**Comment by Bo98** [comment]
This is the amended commit I tested a build of now: https://github.com/Bo98/llvm-project/commit/2d6577e3e599d58e5a0113f327929a00950caee8

Results in:

```
libLLVM-13.0.0git.dylib -> libLLVM-13git.dylib
libLLVM-13git.dylib
libLLVM.dylib -> libLLVM-13git.dylib

libLLVM-C.13.0.0git.dylib
libLLVM-C.13git.dylib -> libLLVM-C.13.0.0git.dylib
libLLVM-C.dylib -> libLLVM-C.13git.dylib

libLTO.13.0.0git.dylib
libLTO.13git.dylib -> libLTO.13.0.0git.dylib
libLTO.dylib -> libLTO.13git.dylib

libRemarks.13.0.0git.dylib
libRemarks.13git.dylib -> libRemarks.13.0.0git.dylib
libRemarks.dylib -> libRemarks.13git.dylib

libclang-cpp.13.dylib
libclang-cpp.dylib -> libclang-cpp.13.dylib

libclang.13.dylib
libclang.dylib -> libclang.13.dylib

libomp.dylib
```

Which is much better.

Means it will enforce a `brew linkage` failure for anything linking with libLLVM etc when a new major version is released - as it should since it's ABI incompatible.

**Comment by carlocab** [comment]
Nice. That makes sense. Though I also remember `-13git` showing up in some of those libraries the last time I built LLVM from master...

----

`llvm@11` failed to build on ARM. Not sure why. And `nvc` seems to fail non-deterministically.

**Comment by abpostelnicu** [comment]
Please use the script that we use at Mozilla, I’ve posted a couple of comments earlier.

**Comment by Bo98** [comment]
`llvm@11` failing is just a freak incident - seems like something crashed on the system end. It'll work on a re-run.

**Comment by SMillerDev** [comment]
> Please use the script that we use at Mozilla, I’ve posted a couple of comments earlier.

https://github.com/Homebrew/homebrew-core/pull/75204#issuecomment-820705880 explains why we don't/can't use the `ninja` build.

**Comment by abpostelnicu** [comment]
Disregard the ninja build system, look at the flags...

**Comment by carlocab** [comment]
There are many flags there. Which ones are you referring to?

**Comment by abpostelnicu** [comment]
We are building clang 11 and 12 for all platforms almost, including macos aarch64 from linux64. We do only cross builds from linux64 to different platforms, and those are our official toolchain s that we use in production.
For example let’s not build lldb, it’s broken anyway... and what Apple offers is way superior

**Comment by SMillerDev** [comment]
We don't do cross compilation for homebrew so that won't work. And it doesn't matter which version is superior if people find the current version useful.

**Comment by abpostelnicu** [comment]
The current version of lldb on macos is broken since the integration tests for lldb on llvm infra are offline...

**Comment by carlocab** [comment]
How is lldb broken?

**Comment by abpostelnicu** [comment]
For example it doesn’t respect the break address and neither can resolve the return address of a function call.
Also remember what patches we had to do on 11 only to be able to compile on macos?

**Comment by SMillerDev** [comment]
Homebrew aims to ship versions of software as upstream makes them available. If this is the state of upstream that is how we should ship it. Not what Mozilla thinks upstream should have shipped.

**Comment by abpostelnicu** [comment]
It was just a personal opinion that we shouldn’t ship lldb, but thanks for detailing this.

**Comment by carlocab** [comment]
@abpostelnicu If you have specific improvements you'd like to suggest for the `llvm` formula that don't involve using `ninja` or deactivating functionality that other users have come to expect to be there, please open a PR once this one has been merged so they can be reviewed.

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
Right, don't pass autosquash.

**Comment by Bo98** [comment]
> For example let’s not build lldb, it’s broken anyway... and what Apple offers is way superior

I agree that most will want system LLDB, but it's a bit more complicated than that. We also ship LLDB libraries which Apple do not, and downstream projects _do_ rely on them.

**Pull request closed without merging**
