### PR TITLE
gdb: Fix for Sierra SIP.

### PR DESCRIPTION
**Pull request by Manouchehri**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I will push another commit to point to Homebrew/formula-patches as soon as https://github.com/Homebrew/formula-patches/pull/87 is merged in.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Has this patch been submitted to upstream?

If so, has upstream indicated it intends to merge this patch?

**Comment by Manouchehri** [comment]
Yes, it's already merged in upstream. No release yet.

https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=82b19a4d2f9c9e8d56fdffdd702f7db4af486386

Since the `gdb/ChangeLog` file conflicts, I split the patch (to formula-patches).

```
8:40:34 PM <dave0x6d> Is there a way to make patch continue even if it fails to apply a certain chunk? https://github.com/Homebrew/homebrew-core/pull/6805/files#diff-0d323e48452c426a3b4cc61ef5e266e8R37
8:40:51 PM <dave0x6d> The ChangeLog fails, but that doesn't really matter, I only care about the one file.
8:57:27 PM <tdsmith> dave0x6d: no; you should just split out the patch you need and host it as a gist
```

**Comment by ilovezfs** [comment]
Does it require SIP to be disabled to work?

**Comment by Manouchehri** [comment]
No. It just has to be signed and startup-with-shell set to off.

**Comment by ilovezfs** [comment]
I think I'd prefer to wait for a new release here since the patch has security implications.

**Comment by Manouchehri** [comment]
Not sure I understand, security implications in what? SIP is enforced by the kernel, all this patch does is stop violating it (by following Apple's guidelines).

http://sourceware-org.1504.n7.nabble.com/gdb-on-macOS-10-12-Sierra-tp415708p419627.html

> Spawning children processes of processes restricted by System Integrity Protection, such as by launching a helper process in a bundle with NSTask or calling the exec(2) command, resets the Mach special ports of that child process. Any dynamic linker (dyld) environment variables, such as DYLD_LIBRARY_PATH, are purged when launching protected processes.

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html

**Comment by ilovezfs** [comment]
Yes, I understand. Do you mind asking upstream what their timetable is for a release that includes this change?

**Comment by Manouchehri** [comment]
Approximately two months.

https://www.gnu.org/software/gdb/schedule/

**Comment by ilovezfs** [comment]
:rocket: 

@Manouchehri thanks for your contribution to Homebrew!

**Pull request closed without merging**
