### PR TITLE
packer 1.4.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
06:56:04 cp -pR /private/tmp/d20190626-6122-kd2pkz/.travis.yml /private/tmp/packer-20190626-6122-17z4xg/.travis.yml
06:56:04 cp -pR /private/tmp/d20190626-6122-kd2pkz/main.go /private/tmp/packer-20190626-6122-17z4xg/main.go
06:56:04 cp -pR /private/tmp/d20190626-6122-kd2pkz/vendor/. /private/tmp/packer-20190626-6122-17z4xg/vendor
06:56:04 cp -pR /private/tmp/d20190626-6122-kd2pkz/packer/. /private/tmp/packer-20190626-6122-17z4xg/packer
06:56:04 cp -pR /private/tmp/d20190626-6122-kd2pkz/main_test.go /private/tmp/packer-20190626-6122-17z4xg/main_test.go
06:56:04 chmod -Rf +w /private/tmp/d20190626-6122-kd2pkz
06:56:04 Error: An exception occurred within a child process:
06:56:04   Utils::InreplaceError: inreplace failed
06:56:04 Makefile:
06:56:04   expected replacement of "go get golang.org/x/tools/cmd/stringer" with ""
```

**Comment by chenrui333** [comment]
```
05:32:05 cp -pR /private/tmp/d20190628-23386-n8hd98/vendor/. /private/tmp/packer-20190628-23386-1lnxgoo/vendor
05:32:05 cp -pR /private/tmp/d20190628-23386-n8hd98/packer/. /private/tmp/packer-20190628-23386-1lnxgoo/packer
05:32:05 cp -pR /private/tmp/d20190628-23386-n8hd98/main_test.go /private/tmp/packer-20190628-23386-1lnxgoo/main_test.go
05:32:05 chmod -Rf +w /private/tmp/d20190628-23386-n8hd98
05:32:05 ==> make releasebin
05:32:05 ==> Checking for necessary tools...
05:32:05 make: *** [releasebin] Error 1
05:32:05 
05:32:05 ==> Formula
05:32:05 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/packer.rb
```

**Comment by chenrui333** [comment]
Trying to use `go modules` approach, looks like the `go.sum` has some issue:

```
   def install
-    ENV["XC_OS"] = "darwin"
-    ENV["XC_ARCH"] = "amd64"
     ENV["GOPATH"] = buildpath
+    ENV["GO111MODULE"] = "on"

     packerpath = buildpath/"src/github.com/hashicorp/packer"
-    packerpath.install Dir["{*,.git}"]
+    packerpath.install buildpath.children

     cd packerpath do
-      # Avoid running `go get`
-      inreplace "Makefile" do |s|
-        s.gsub! "go get github.com/mitchellh/gox", ""
-        s.gsub! "go get -u github.com/mna/pigeon", ""
-        s.gsub! "go get golang.org/x/tools/cmd/goimports", ""
-        s.gsub! "go get github.com/alvaroloes/enumer", ""
-      end
-
-      (buildpath/"bin").mkpath
-      if build.head?
-        system "make", "bin"
-      else
-        system "make", "releasebin"
-      end
-      bin.install buildpath/"bin/packer"
+      system "go", "build", "-o", bin/"packer"
       zsh_completion.install "contrib/zsh-completion/_packer"
       prefix.install_metafiles
     end
```

error log

```
go: finding github.com/digitalocean/godo v1.11.1
go: finding github.com/google/shlex v0.0.0-20150127133951-6f45313302b9
go: finding github.com/joyent/triton-go v0.0.0-20180116165742-545edbe0d564
go: finding github.com/scaleway/scaleway-cli v0.0.0-20180921094345-7b12c9699d70
go: finding github.com/antchfx/xpath v0.0.0-20170728053731-b5c552e1acbd
go: error loading module requirements
```

**Comment by basictheprogram** [comment]
Is there a reason you just don't bump the tag, revision, and sha256? 

brew install --build-from-source  packer to confirm all is ok and commit?

**Comment by chenrui333** [comment]
@basictheprogram, yeah, I did test locally, which is the error I reported above.

I am confused with what you said about `Is there a reason you just don't bump the tag, revision, and sha256?`

**Comment by basictheprogram** [comment]
@chenrui333  Why change these things?
```patch
+    ENV["GO111MODULE"] = "on"
+    packerpath.install buildpath.children
+    system "go", "build", "-o", bin/"packer"
```
Why not not just changed (below) :tag, :revsion and the sha256?
```ruby
  url "https://github.com/hashicorp/packer.git",
      :tag      => "v1.4.2",
      :revision => "0bb38f438570dc0b3b1253169b0de0f4a2be6801"
  head "https://github.com/hashicorp/packer.git"

  bottle do
    cellar :any_skip_relocation
    sha256 "4e9bf72be16b00953dd7213e19fba97de569b91d8b8116b190efd647efe7d047" => :mojave
    sha256 "4e998603e188aa2ba421a99d38d9da00581a89896ade34d099b5ae33934e37ef" => :high_sierra
    sha256 "41fecd6ec48dd132f17506477b8d94150188893c9deeab6e21acda763cc4df9a" => :sierra
  end
```

**Comment by chenrui333** [comment]
yeah, because of the build process got updated to `go modules` (with `go.mod` and `go.sum` present in the top level directory)

**Comment by chenrui333** [comment]
Close in favor of #42728

**Pull request closed without merging**
