### PR TITLE
Revert "Revert "publish-commit-bottles: optionally push to pull request branc… (#126011)"

### PR DESCRIPTION
**Pull request by carlocab**
We need to make sure an empty string is returned whenever
`commit_bottles_to_pr_branch` is false.

This reverts commit f6816db6a1622d7512607f8379b5dadd65c321fc.

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]
Looks good!

**Comment by carlocab** [comment]
@Rylan12 Thanks! How long are you around in case we need a revert? I don't expect we'll need one, but you never know...

**Comment by Rylan12** [comment]
I'll definitely be around for another hour. Then I'll be gone for a bit but should be back later today (not sure what time). Even when I'm out I should be able to mobile-approve a revert PR if needed (you'll just need to ping me so I get a notification).

**Comment by MikeMcQuaid** [comment]
Thanks both!

**Pull request merged**
