### PR TITLE
cloudflare-wrangler2 3.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Full linkage --test cloudflare-wrangler2 output
  Missing libraries:
    unexpected (libc++.so.1)
    unexpected (libc++abi.so.1)
    unexpected (libunwind.so.1)
```

**Comment by chenrui333** [comment]
test failure on macos is due the missing directory of `/opt/homebrew/Cellar/node/20.1.0/lib`

**Comment by samford** [comment]
This test runs `wrangler init --yes` but it seems like the `--yes` option isn't being respected so it ends up hanging on an interactive prompt:

```
$ wrangler init --yes
 ⛅️ wrangler 3.0.0
------------------
Using npm as package manager.
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare@2` instead.

  The `init` command will be removed in a future version.


Running `npm create cloudflare@2`...
Need to install the following packages:
  create-cloudflare@2.0.7
Ok to proceed? (y)
```

I've opened an [upstream issue](https://github.com/cloudflare/workers-sdk/issues/3286) to see if this is a bug that they will fix or if there's an alternative command we could use for testing. Worst case scenario, we may have to drop back to `wrangler --version`, as I think all the other commands involve network requests and/or authentication.

**Comment by samford** [comment]
Upstream confirmed that `--yes` is broken in 3.0.0 and will be fixed in a future release. However, `wrangler init` will be deprecated in a future version, so it seems like our only reliable option is `wrangler --version`, as everything else involves network requests (sometimes requiring authentication, opening a browser window, etc.). With `--yes` broken in this version, we'll have to address the issue in this PR, though.

-----

One thing upstream mentioned (that I was also thinking) is that `cloudflare-wrangler2` is now an unusual name. We used `cloudflare-wrangler2` because the previous Rust (1.x) version is `cloudflare-wrangler2` and the upstream repository for the JavaScript (2.x) version was cloudflare/wrangler2. `wrangler` has since been integrated into the cloudflare/workers-sdk repository and is simply referred to as "wrangler" (not "wrangler2").

The ideal name for this formula is `cloudflare-wrangler` (as upstream suggests) but we still have a deprecated formula with that name for the old Rust version of `wrangler`. Upstream officially deprecated v1 on 2023-02-16 and is providing critical updates until 2023-08-01 (the most recent change was on 2023-02-21, for version 1.21.0), at which point they will drop all support for v1.

I don't think we can recycle that name until after we've removed the current `cloudflare-wrangler` formula and it's unclear when we'll do that. I'm also not sure how that would work for existing v1 users. For example, if renaming this formula to `cloudflare-wrangler` would cause users of the old formula to be upgraded to v3, that seems like an issue.

With that aside, how do we want to handle the mismatch between `cloudflare-wrangler2` and this being 3.0.0 (and beyond) in the interim time? It seems like the options are either 1) do nothing and accept the temporary mismatch or 2) rename the formula to `cloudflare-wrangler3` or something unversioned like `cloudflare-wrangler-js` (and add a rename or alias for existing `cloudflare-wrangler2` users).

I may not have a complete understanding of how renames are typically handled, so it would be good to get @Homebrew/core's thoughts.

**Comment by p-linnane** [comment]
#135250

**Pull request closed without merging**
