### PR TITLE
diff-so-fancy 1.4.0

### PR DESCRIPTION
**Pull request by BuonOmo**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by BuonOmo** [comment]
Hi brewers and thanks for the good work,

I'm really unsure of what I tried:
- I've added the tag link, not the `.tar.gz` link (which is here in case it is better: https://github.com/so-fancy/diff-so-fancy/archive/v1.4.0.tar.gz)
- I did not add sha manually, it was added by the script :/

I'd be glad to add an example to documentation if this can improve the PR quality 🙂

**Comment by carlocab** [comment]
How did you call `bump-formula-pr`? The correct command should've been 

```
brew bump-formula-pr --version=1.4.0 diff-so-fancy
```

**Comment by carlocab** [comment]
I've fixed your commit for you. Thanks for the PR.

**Review by carlocab — APPROVED** [review]
Thanks again, @BuonOmo.

**Comment by BuonOmo** [comment]
@carlocab I used the `--strict` option as mentioned in contributing, and tried:

```
23972  2021-02-10 21:33  brew bump-formula-pr --strict diff-so-fancy
23973  2021-02-10 21:35  brew bump-formula-pr --strict diff-so-fancy --tag=1.4.0 --revision=93f360b
23974  2021-02-10 21:36  brew bump-formula-pr --strict diff-so-fancy --tag=v1.4.0 --revision=93f360b
23975  2021-02-10 21:36  brew bump-formula-pr --strict diff-so-fancy --tag=v1.4.0 --revision=93f360bd0c7f86d423bc2ade391bcde6109c95ae
23976  2021-02-10 21:37  brew bump-formula-pr --strict diff-so-fancy --url=https://github.com/so-fancy/diff-so-fancy/releases/tag/v1.4.0
```

Only the last one worked

**Comment by carlocab** [comment]
Specifying the URL works too, but you chose the wrong one. It should've been  https://github.com/so-fancy/diff-so-fancy/archive/v1.4.0.tar.gz

Or, better, just use `--version=`.

**Comment by BuonOmo** [comment]
Ok, I'll offer a minor contribution to the `CONTRIBUTING.md` then 🙂

**Pull request merged**
