### PR TITLE
wireshark: build for Apple Silicon

### PR DESCRIPTION
**Pull request by fxcoudert**
One of the most-downloaded formula with no Apple Silicon bottle… let's try to fix it

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /opt/homebrew/Cellar/wireshark/3.4.2_1/bin/randpkt -b 100 -c 2 capture.pcap
dyld: Library not loaded: @rpath/libwiretap.11.dylib
  Referenced from: /opt/homebrew/Cellar/wireshark/3.4.2_1/bin/randpkt
```

despite `-DCMAKE_INSTALL_RPATH=#{lib}`

**Comment by carlocab** [comment]
Same problem in https://github.com/Homebrew/homebrew-core/pull/68585

**Comment by carlocab** [comment]
Ok, that seems to work. Not sure this is the right hack though. And I guess it might have implications for whether this formula has a relocatable bottle?

**Comment by carlocab** [comment]
See also #68585, where I use the same hack.

**Comment by fxcoudert** [comment]
I don't feel this is right to do such low-level fixing. We probably want to report this, and see if they have advice for how on our to set up cmake so it does the right thing.

**Comment by carlocab** [comment]
>We probably want to report this

I had been thinking this, but I didn't know whom we wanted to report it to. Is it a build system bug for Wireshark? Or is it a problem in CMake that `INSTALL_RPATH` doesn't seem to be doing what we expect it to?

**Comment by fxcoudert** [comment]
The majority of cmake-based formulas install fine, so I'd say it's a wireshark problem. Might be common to others, indeed, but probably not a generic cmake issue.

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
Bump wireshark into the latest version in #70116

**Comment by carlocab** [comment]
Closed in #73035.

**Pull request closed without merging**
