### PR TITLE
gdbgui 0.15.1.0

### PR DESCRIPTION
**Pull request by branchv**
gdbgui: migrate to `python@3.11`

### CODE REVIEW

**Comment by cho-m** [comment]
https://github.com/cs01/gdbgui/issues/425
https://github.com/cs01/gdbgui/pull/430

---

May be fixed in 0.15.1.0 but that update failed -- #104383

Could try updating to 0.15.1.0, downgrading `werkzeug` version, or patching.

**Comment by branchvincent** [comment]
Bumped to latest release, did have to manually change `greenlet` from 1.1.2 to 1.1.3 for [3.11 support](https://github.com/python-greenlet/greenlet/compare/1.1.2...1.1.3)

**Comment by cho-m** [comment]
Can you create an upstream PR since they have locked in `greenlet` 1.1.2 https://github.com/cs01/gdbgui/blob/master/requirements.txt#L25 (install_requires is set to requirements.txt)

**Comment by chenrui333** [comment]
> Can you create an upstream PR since they have locked in `greenlet` 1.1.2 https://github.com/cs01/gdbgui/blob/master/requirements.txt#L25 (install_requires is set to requirements.txt)

raised a PR to bump the dependency, https://github.com/cs01/gdbgui/pull/452

And will pursue the version bump in [this new PR](https://github.com/Homebrew/homebrew-core/pull/122822)

**Pull request closed without merging**
