### PR TITLE
libgit2 1.6.2

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
I don't think `gitg` necessarily needs a rebuild. The test failure is
```
  ==> Testing gitg
  ==> /opt/homebrew/Cellar/gitg/41/bin/gitg --version
  dyld[92727]: Library not loaded: '/opt/homebrew/opt/libgit2/lib/libgit2.1.5.dylib'
    Referenced from: '/opt/homebrew/Cellar/libgit2-glib/1.0.0.1_2/lib/libgit2-glib-1.0.0.dylib'
    Reason: tried: '/opt/homebrew/opt/libgit2/lib/libgit2.1.5.dylib' (no such file), '/usr/local/lib/libgit2.1.5.dylib' (no such file), '/usr/lib/libgit2.1.5.dylib' (no such file), '/opt/homebrew/Cellar/libgit2/1.6.1/lib/libgit2.1.5.dylib' (no such file), '/usr/local/lib/libgit2.1.5.dylib' (no such file), '/usr/lib/libgit2.1.5.dylib' (no such file)
```
so it may be enough to rebuild `libgit2-glib`.

**Comment by carlocab** [comment]
It may be a while before dependents are ready for 1.6.1. Opened #124264 to pick up bug fixes for 1.5.*.

**Comment by carlocab** [comment]
Also, the `libgit2-glib` build failure seems to be from upstream renaming their `libgit2.pc` to `git2.pc`. How nice.

**Comment by carlocab** [comment]
Needs rebase for #124264.

**Comment by carlocab** [comment]
The rust-based formulae are probably building a vendors libgit2 since the `libgit2-sys` crate will only use up to version 1.6.0.

**Comment by carlocab** [comment]
`dvc`, `gitless`, and `literate-git` blocked on `pygit2`. Upstream issue: https://github.com/libgit2/pygit2/issues/1193

We'll need a separate one for the `libgit2-sys` crate.

**Comment by carlocab** [comment]
`libgit2-sys` is being updated at https://github.com/rust-lang/git2-rs/pull/935.

Not sure how to pull that in to `cargo` builds when updates, though. CC @branchvincent @cho-m who've handled similar issues before I think.

**Comment by carlocab** [comment]
In order to avoid having to rebuild multiple formulae that use a `pygit2` resource, I'm adding a `pygit2` formula in #124511. This should save a lot of time here, given that it'll allow us to get rid of a `dvc` rebuild (which is a `long build` label all by itself).

**Comment by carlocab** [comment]
> Also, the `libgit2-glib` build failure seems to be from upstream renaming their `libgit2.pc` to `git2.pc`. How nice.

Fixed in libgit2/libgit2#6514.

**Comment by agimbrac** [comment]
Le dim. 26 févr. 2023 à 16:05, Carlo Cabrera ***@***.***> a
écrit :

**Comment by p-linnane** [comment]
Per https://github.com/Homebrew/homebrew-core/pull/125155, libgit2 1.6.2 has been released.

**Comment by carlocab** [comment]
Oops, forgot about those audits. But `libgit@1.5` should have a `head` spec since it has a [maintenance branch](https://github.com/libgit2/libgit2/tree/maint/v1.5). We can add it to `audit_exceptions/versioned_head_spec_allowlist.json`. See also:

https://github.com/Homebrew/homebrew-core/blob/2c9f881a09f82aa50d70c879859efeaed464bd97/Formula/mbedtls%402.rb#L7

**Comment by carlocab** [comment]
`pygit2` seems to have somehow used `libgit2@1.5` headers but linked with `libgit2` on Intel macOS. Probably because `libgit2` is linked to `/usr/local`. Will need a workaround.

**Review by carlocab — COMMENTED** [review]
This should be ready to go. When merging, please handle `TODO`s below.

**Review by ZhongRuoyu — APPROVED** [review]
I will open a PR to follow up.

**Pull request closed without merging**
