### PR TITLE
lighthouse 2.3.1

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by PythonCoderAS** [comment]
As per #103752, the PR is being recreated.

**Comment by chenrui333** [comment]
```
    make: warning: -jN forced in submake: disabling jobserver mode.
    /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/strutil.cc:1255:19: error: expected unqualified-id
      } else if (std::isnan(value)) {
                      ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/math.h:165:5: note: expanded from macro 'isnan'
        ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
        ^
    /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/strutil.cc:1373:19: error: expected unqualified-id
      } else if (std::isnan(value)) {
                      ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/math.h:165:5: note: expanded from macro 'isnan'
        ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
        ^
    /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/strutil.cc:1255:19: error: expected unqualified-id
      } else if (std::isnan(value)) {
                      ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/math.h:165:5: note: expanded from macro 'isnan'
        ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
        ^
    /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/strutil.cc:1373:19: error: expected unqualified-id
      } else if (std::isnan(value)) {
                      ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/math.h:165:5: note: expanded from macro 'isnan'
        ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
        ^
    2 errors generated.
```

**Comment by chenrui333** [comment]
cc @michaelsproul

**Comment by cho-m** [comment]
Looks similar to errors that happen when build scripts don't pick up correct XCode/CLT SDK.

`prost-build` programmatically calls `cmake` to build `protobuf` (v3.14.0), so it may not play well with Homebrew's build environment (e.g. given that it doesn't include all the `std_cmake_args`).

**Comment by PythonCoderAS** [comment]
There is an entire section on `prost_build` about `protoc`: https://docs.rs/prost-build/latest/prost_build/#sourcing-protoc

**Comment by chenrui333** [comment]
#106928

**Pull request closed without merging**
