### PR TITLE
libtorch: fix `python3` reference.

### PR DESCRIPTION
**Pull request by miles170**
See #110462.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by miles170** [comment]
Rerun CI tests with Python 3.10.7 (#109777).

**Comment by miles170** [comment]
@carlocab Could you help with either removing the `long build` label or adding the `CI-long-timeout` label?

**Comment by miles170** [comment]
It seems that PyTorch fails to build on Intel Mac (https://github.com/pytorch/pytorch/issues/85956).

**Comment by miles170** [comment]
Should this pull request be cherry-picked into #111889 or closed instead?

**Comment by iMichka** [comment]
Done. We need a long build slot to test again.

**Comment by miles170** [comment]
@cho-m Could you help with adding `CI-long-timeout` label to test the new patch?

**Comment by danielnachun** [comment]
We might also want to have this depend on `pyyaml` and drop the `PyYAML` dependency as done in https://github.com/Homebrew/homebrew-core/pull/111889.

**Comment by danielnachun** [comment]
I'm turning off `long build` temporarily to make sure this works for the first 90 minutes.  That will help to avoid wasting a long timeout run.

**Comment by danielnachun** [comment]
Now I see what the problem is - we need grab the newer version of `fbgemm` as a resource using commit hash in that patch.

**Comment by danielnachun** [comment]
Everything worked in the local build I ran on my Intel Mac so I'm hoping we'll have a successful run here now.

**Comment by danielnachun** [comment]
@carlocab I think these changes are still compatible with `CI-no-bottles`.  If so we should be able to get this merged.

**Review by danielnachun — APPROVED** [review]
No opposition to this has been raised so I am going to approve and merge this.

**Pull request merged**
