### PR TITLE
arangodb 3.8.5.1

### PR DESCRIPTION
**Pull request by KVS85**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by KVS85** [comment]
ArangoDB 3.8 is not able to be built by `g++-5`. We require at least `g++-9`. 3.8.5 version has the same codebase for this part and it compiled normally here.

**Comment by KVS85** [comment]
@carlocab can you please trigger checks again (probably with `long build` additional label)?

**Comment by carlocab** [comment]
You can add
```ruby
on_linux do
  depends_on "gcc"
end

fails_with gcc: "5"
```
for Linux.

**Comment by fceller** [comment]
Added 

```
on_linux do
  depends_on "gcc"
end

fails_with gcc: "5"
```

**Comment by KVS85** [comment]
@carlocab we fixed the formula. Can you please merge this PR?

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Does this still need `go@1.13`? That's been EOL for a while, and is blocking the bottling of this on Monterey.

**Comment by fceller** [comment]
@KVS85 I believe it can be moved to go17

**Pull request closed without merging**
