### PR TITLE
dart-sdk 3.1.1

### PR DESCRIPTION
**Pull request by ntkme**
Closes #141730

### CODE REVIEW

**Comment by ntkme** [comment]
@chenrui333 The linux build failed but I don't see any errors in the log. Do you know if it is a timeout of CI or something else?

**Comment by ntkme** [comment]
Ok found out why. The CI worker ran out of disk space on Linux worker. This was printed only as an annotation on run so that it was not part of the log:

```
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 92 MB
```

**Comment by p-linnane** [comment]
We can use our self-hosted Linux runner which won't run into this issue.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@ntkme thanks a lot for your help on maintaining this formula. 🎉

**Pull request merged**
