### PR TITLE
Revert back q to 1.7.4

### PR DESCRIPTION
**Pull request by harelba**
- [V] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [V] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [V] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [V] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [V] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Reverting back to previous q 1.7.4 version due to a bad version bump two weeks ago.

### CODE REVIEW

**Comment by bayandin** [comment]
> due to a bad version bump two weeks ago.

What does it mean? 
What is the problem with the current version? Why do we need to revert it back?

**Comment by harelba** [comment]
Hi @bayandin , sorry for the late reply.

The packaging of q has been changed in 2.x from source to a standalone binary.

Some weeks ago, someone with the best intentions bumped the version of q in brew from 1.7.4 to to 2.x without realising it would break things (currently everyone downloading q succeeds, but running it fails).

I would like to revert it back to the previous version 1.7.4, so people will be able to download and use q properly while i devise a proper distribution for the binary (probably through cask?).

From the results of the CI, i can see that there's a check which prevents downgrading the version. 

Could you please advise regarding the best approach for this?

Thanks!

**Comment by gromgit** [comment]
Can `q` still be built from source? If so, I think the proper course of action would be to update the formula to Do The Right Thing.

**Comment by SMillerDev** [comment]
From what I can see we just need a pyci formula and run `pyci pack binary`. Then we have a binary.

**Comment by bayandin** [comment]
May I suggest to use `virtualenv_install_with_resources` (as the major of python formulae do):

```ruby
class Q < Formula
  include Language::Python::Virtualenv

  desc "Run SQL directly on CSV or TSV files"
  homepage "https://harelba.github.io/q/"
  url "https://github.com/harelba/q/archive/2.0.12.tar.gz"
  sha256 "41473be9bce34b94c31e9fe3e30bd26ef72bb6a55cf63b6362be215a11229c24"
  license "GPL-3.0-only"
  head "https://github.com/harelba/q.git"

  depends_on "python@3.8"

  resource "six" do
    url "https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz"
    sha256 "30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259"
  end

  def install
    rm_f "bin/qtextasdata.py" # broken symlink

    virtualenv_install_with_resources
  end

  test do
    seq = (1..100).map(&:to_s).join("\n")
    output = pipe_output("#{bin}/q -c 1 'select sum(c1) from -'", seq)
    assert_equal "5050\n", output
  end
end
```

**Comment by harelba** [comment]
Thanks a lot for the input and suggestions. I'm hardly an expert when it comes to packaging, especially for osx.

There were several reasons for changing the packaging to binary:
1. Prevent the need for python itself, not only the python dependencies
2. Remove the variance of having a specific python version installed on the target machine
3. Prevent the need for update the osx packaging whenever the python dependencies are changed
4. Short installation time (as it's a "linux-like" command-line, a long installation time might hurt adoption).

@bayandin The option you suggest is very interesting, i'm playing with it to see if some variation of it will work well. Several concerns:
1. It requires compiling/installing python3 on the target machine, which is heavy (although in most cases the machines would already have it).
2. Managing the python dependencies manually in addition to setup.py. The [docs](https://docs.brew.sh/Python-for-Formula-Authors#installing) say that this is not encouraged, but it mentions other ways there of generating the proper resources. I'll check this out, as this might be a good way to make it work without actually duplicating the management of the python dependencies.
3. python dependency conflicts - From the docs it's unclear if the virtualenv being created is specific to q or general to all installed formulas (the docs mention a virtualenv located at libexec, and not a specific one). I'll make some tests with it and see.

In essence q is only incidentally written in python - it's a command-line tool, so I was under the impression that providing a standalone binary without any external dependencies (not even python) would be a better solution. However, perhaps it's not such a big deal pragmatically.

Btw, @bayandin - What do you think about using cask for this? Is this a relevant/reasonable option as well? Or will it be considered an "abuse"?

I'll update when I have some conclusions.

Thanks again for the input and for caring.
Harel

**Comment by harelba** [comment]
@SMillerDev Building it from source requires a lot of dependencies, including python itself, pyci, and takes a very long time, plus the pyci flow is not completely stable unfortunately, and I would like users to endure this entire flow whenever they install q.

@gromgit you are right about the versioning issue. 2.0.9 is the official stable release. The others are there because pyci has an issue with being able to publish to a pre-release. I'm in the midst of streamlining the entire packaging/versioning flow after moving to pyci. build/tests/publish are working properly, however there's some manual stuff that needs to be done related to creating the release in github. I modified the 2.0.10/11 releases so they're pre-releases, to prevent confusion.

Thanks a lot for the input people.

**Comment by SMillerDev** [comment]
> @SMillerDev Building it from source requires a lot of dependencies, including python itself, pyci, and takes a very long time, plus the pyci flow is not completely stable unfortunately, and I would like users to endure this entire flow whenever they install q.

They won't when they install through Homebrew. This is what package managers do, they simplify the install method. Homebrew CI would build a package (like you're doing right now) that would be compatible with the versions of the software that Homebrew provides. It would take about 20 seconds to install for most users depending on the internet connection and hardware.

---

> 
    Prevent the need for python itself, not only the python dependencies
    Remove the variance of having a specific python version installed on the target machine
    Prevent the need for update the osx packaging whenever the python dependencies are changed
    Short installation time (as it's a "linux-like" command-line, a long installation time might hurt adoption).

None of these apply when refering to the homebrew package since homebrew takes care of all those.

> python dependency conflicts - From the docs it's unclear if the virtualenv being created is specific to q or general to all installed formulas (the docs mention a virtualenv located at libexec, and not a specific one). I'll make some tests with it and see.

It's per formula, otherwise the virtualenv wouldn't help much.

> What do you think about using cask for this? Is this a relevant/reasonable option as well? Or will it be considered an "abuse"?

It's an open source command line tool, this is not allowed as a cask.

**Comment by harelba** [comment]
Thanks for the replies @SMillerDev !

> They won't when they install through Homebrew. This is what package managers do, they simplify the install method. Homebrew CI would build a package (like you're doing right now) that would be compatible with the versions of the software that Homebrew provides. It would take about 20 seconds to install for most users depending on the internet connection and hardware.

This is extremely interesting, I was under the impression that brew actually installs "from-source" in many cases where i've installed stuff. If the CI is actually pre-building for each supported platform, that is awesome. 

> None of these apply when refering to the homebrew package since homebrew takes care of all those.

Does it provide full isolation and encapsulation for conflicting dependencies? If yes, that's great as well. 

> It's per formula, otherwise the virtualenv wouldn't help much.

Thanks for that info, I didn't want to assume this, but obviously, this is trivial otherwise there's no point to using a virtualenv.

> It's an open source command line tool, this is not allowed as a cask.

Hmm, thanks for the info as well, very important.


@bayandin It seems that making it work properly with the new version is gonna take some effort and time. Would it be possible in some way to make brew install the older 1.7.4 version in the mean time? Currently, users are actually not getting a proper installation whenever they install q with brew.

**Comment by bayandin** [comment]
> @bayandin It seems that making it work properly with the new version is gonna take some effort and time. 

What kind of effort do you mean? Everything is done in https://github.com/Homebrew/homebrew-core/pull/60798#issuecomment-689488973, you need just to update the PR with it suggested code.

> Currently, users are actually not getting a proper installation whenever they install q with brew.

What do you mean by proper installation, btw?
In the formula, we have a test block and it seems it worked fine. Do you have any examples of formula misbehaviour?

**Comment by harelba** [comment]
Sorry @bayandin you're absolutely right. I've coupled between trying to prevent the duplication of the python dependencies and fixing this formula. There's obviously no need to couple them. I'll work on that separately as needed.

Also when writing "proper installation" i was referring to the other suggestion on the thread of installing using pyci inside brew.

Anyway, I've created a new proper PR with the relevant changes (the version will be 2.0.16, since i had to fix some versioning issues inside q itself, which i found during testing).

Will check that it passes CI properly in the other PR.

Closing this PR.

Thanks @gromgit @bayandin @SMillerDev for the help!

**Comment by harelba** [comment]
For reference - The new PR is #60861

**Pull request closed without merging**
