### PR TITLE
glassfish 6.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/opt/glassfish/libexec/glassfish/bin/asadmin version | grep 6.0.0
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

**Comment by SMillerDev** [comment]
Maybe we can try and wrap all commands like we would normally do for Java tools

**Comment by chenrui333** [comment]
> Maybe we can try and wrap all commands like we would normally do for Java tools

sounds about right, let me give that a shot.

**Review by SMillerDev — DISMISSED** [review]

**Comment by bayandin** [comment]
`openjdk@8` doesn't support Apple Silicon, so failure on 11-arm it's ok

**Review by bayandin — APPROVED** [review]

**Pull request merged**
