### PR TITLE
jasper 2.0.21

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: 1 failed steps!
brew test --retry --verbose gtksourceview3
Error: Process completed with exit code 1.
```

**Comment by chenrui333** [comment]
known issue in the other PRs, #61226, #61539

**Comment by chenrui333** [comment]
The most recent update for gtksourceview3, #57063

**Comment by chenrui333** [comment]
Same issue seen in #62023

**Comment by chenrui333** [comment]
`gtksourceview3` test got fixed in #62023

**Review by Rylan12 — APPROVED** [review]

**Pull request closed without merging**
