### PR TITLE
pdnsrec: revision for boost

### PR DESCRIPTION
**Pull request by ilovezfs**
boost 1.61.0 patch

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 I threw in the goofy `depends_on "gcc"` until there's something better since there's no point in causing CI failures elsewhere.

**Comment by DomT4** [comment]
👍. That "something better" may well be when we stop shipping bottles for Mavericks, which will defer the issue until whenever the Yosemite `clang` starts being problematic, sigh.

**Comment by ilovezfs** [comment]
At some point, maybe we'll acknowledge that Apple really doesn't support anything other than the latest version of macOS and only bottle for that version.

**Comment by DomT4** [comment]
To be fair, they do at least support two OS X/macOS versions. Yosemite still gets fairly frequent security updates, and they got Xcode updates until Xcode 7.3. We've discussed cutting back to two major OS X/macOS versions before though.

**Comment by ilovezfs** [comment]
I think with the unitary SDK approach, they really only seriously support the latest regardless of what they say. All lower versions have a screwball experience with development now.

**Comment by ilovezfs** [comment]
CC @Habbie

**Comment by Habbie** [comment]
Looks like `configure: MTasker will use the Boost context library for context switching` turned into `configure: MTasker will use System V ucontexts for context switching` for all OSX versions. I'll investigate.

**Comment by ilovezfs** [comment]
@Habbie thank you!!!

**Comment by justinclift** [comment]
@DomT4 Btw, Mavericks is still receiving security updates too.  Installed one here just a few days ago. :wink:

**Comment by DomT4** [comment]
> Btw, Mavericks is still receiving security updates too. Installed one here just a few days ago. 😉

I suspect the most recent one will be the last one, unless something big happens. Yosemite should be eligible for another year of support yet, and El Cap another two years, which was my thinking.

**Comment by Habbie** [comment]
From the Boost 1.61 notes "fcontext_t: no longer part of public API". This is going to hurt :)

**Comment by Habbie** [comment]
@ilovezfs fixed by https://github.com/PowerDNS/pdns/pull/4271 which will be merged onto master and released in 4.0.2 soon. Can you add it to the brew as a patch?

**Comment by ilovezfs** [comment]
@DomT4 @Habbie PR refreshed with @Habbie's patch.

**Comment by DomT4** [comment]
Thanks @ilovezfs, and thanks @Habbie for the upstream fix ❤️.

**Pull request closed without merging**
