### PR TITLE
azure-cli: switch to PyPI source

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

The current GitHub tarball doesn't have a `pyproject.toml` or `setup.py` at its root, which means it doesn't work with our `brew update-python-resources` and upstream has to rely on generating accurate resource blocks themselves.

Instead, this switches to the published sdist on PyPI, which we generally prefer anyway.

### CODE REVIEW

**Comment by branchvincent** [comment]
cc @bebound from the azure side

**Comment by p-linnane** [comment]
> 1. How to deal with `pip` and `setuptools`? Can `--extra-packages` address this?

We can add `pip` and `setuptools` as extra packages in `pypi_formula_mappings.json`.

**Comment by p-linnane** [comment]
One issue with this method is that `pymsalruntime` does not have an sdist on PyPI or a repository. It'd be great if that was published because it would make the formula dramatically easier to maintain.

**Comment by cho-m** [comment]
> One issue with this method is that `pymsalruntime` does not have an sdist on PyPI or a repository.

Although this will cause `update-python-resources` to fail on macOS, if run on Linux (which I think is the case for both upstream CI and Homebrew CI), then it will pass as `pymsalruntime` is not used there.

There are a couple other packages that are OS-specific so may want to add those as extra resources, e.g. `distro` on Linux.

**Comment by p-linnane** [comment]
> There are a couple other packages that are OS-specific so may want to add those as extra resources, e.g. `distro` on Linux.

I had a complete formula rewrite done locally with those changes, but the test kept failing with missing modules so I abandoned it.

**Pull request closed without merging**
