### PR TITLE
semgrep 0.30.0

### PR DESCRIPTION
**Pull request by brendongo**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by nbrahms** [comment]
This release is erroneous; please do not merge

**Comment by nbrahms** [comment]
cc. @brendongo

**Comment by brendongo** [comment]
Updated the revision to the correct git hash

**Comment by Rylan12** [comment]
Looks like the `colorama`, `pyrsistent`, `ruamel.yaml`, `tqdm` and `urllib3` resources should be bumped to the latest versions

**Comment by brendongo** [comment]
Updated dependencies. semgrep specifically pins ruamel.yaml to 16.10 so did not update that

**Review by SMillerDev — APPROVED** [review]
Thanks @brendongo  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
