### PR TITLE
akamai 0.2.0

### PR DESCRIPTION
**Pull request by kporowski**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@dshafik It looks like c17627c5ee10ed6e9ef92dafb8d5b46160484e0d is no longer a valid revision for the https://github.com/src-d/go-git repository. It still exists on GitHub but appears to be a dangling commit.

>Failed to set version on github.com/src-d/go-git to c17627c5ee10ed6e9ef92dafb8d5b46160484e0d: Unable to update checked out version

**Comment by ilovezfs** [comment]
@kporowski I believe the command in the test needs to change from `akamai get purge` to `akamai install purge`.

**Comment by dshafik** [comment]
I too ran into this while working on 0.3.0; the change to `install` is in 0.2.0 for which the formula hasn't been updated yet. I'll release an updated 0.2.1 and update the formula today.

Can't say as I've ever experienced a commit going away like this, obviously a history rewrite and a force push.

**Comment by ilovezfs** [comment]
>Can't say as I've ever experienced a commit going away like this, obviously a history rewrite and a force push.

Yeah it's not good. I'm not sure there's a great way to avoid this happening without committing a `vendor/` directory to your own repository, or creating a release tarball with the full set of resources.

**Comment by ilovezfs** [comment]
@kporowski passing on this PR for now since it doesn't build and 0.2.1 will be out soon. Thank you for the PR nonetheless!

**Comment by kporowski** [comment]
@dshafik I have figured the same thing out and were going to update cli later today. Just wanted to investigate why that commit was missing. You can find more info here: src-d/go-git#535 and src-d/go-git#504
@ilovezfs I was not expecting `brew bump-formula-pr` to proceed without a successful local build. I would need to do some more reading it seems :)

**Pull request closed without merging**
