### PR TITLE
swiftlint 0.13.0

### PR DESCRIPTION
**Pull request by norio-nomura**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by norio-nomura** [comment]
`brew audit --strict <formula>` generate error:
```terminal.session
swiftlint:
  * C: 5: col 7: Use the new Ruby 1.9 hash syntax.
  * C: 6: col 7: Use the new Ruby 1.9 hash syntax.
  * C: 14: col 14: Use the new Ruby 1.9 hash syntax.
Error: 3 problems in 1 formula
```
But, that caused error on jenkins: https://bot.brew.sh/job/Homebrew%20Core/10669/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/style_swiftlint/
😕

**Comment by ilovezfs** [comment]
Are you running that on the file outside of the brew tree?

**Comment by norio-nomura** [comment]
Yes, I did on `~`

**Comment by norio-nomura** [comment]
I followed the steps on https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#submit-a-123-version-upgrade-for-the-foo-formula

**Comment by norio-nomura** [comment]
I reverted to using `=>` and tests passed. 😃

**Comment by ilovezfs** [comment]
Hash rocket is correct for formulae. You have to run audit with the file in the tree or it uses different rules.

**Comment by ilovezfs** [comment]
@norio-nomura Thanks for the new release and for your contribution to Homebrew!

**Comment by norio-nomura** [comment]
Yeah, I understand. This is my first PR against Homebrew. Thanks! :pray:

**Comment by ilovezfs** [comment]
In the future you may want to use `brew bump-formula-pr`

**Comment by norio-nomura** [comment]
I'll try that on next! 👍

**Pull request closed without merging**
