### PR TITLE
delve 0.11.0 (new formula)

### PR DESCRIPTION
**Pull request by steeve**
This formula installs the delve Go debugger, signed with a self-signed certificate.

### CODE REVIEW

**Comment by steeve** [comment]
So apparently this is not building on jenkins due to the formula installing a certificate in the keychain, via sudo.
Should we maintain a separate tap ?

**Comment by mikemcquaid** [comment]
If it needs to be signed: yes. Can it be used unsigned?

**Comment by steeve** [comment]
That's the main issue yes: https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md

A separate tap is fine. Should I close the PR ?

**Comment by mikemcquaid** [comment]
Yep, sorry!

**Comment by AlekSi** [comment]
https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md recommends:
```shell
$ brew install go-delve/delve/delve
```

**Comment by den-stripe** [comment]
seems like it is not recommended or supported anymore https://github.com/derekparker/delve/pull/1142

**Pull request closed without merging**
