### PR TITLE
copilot 0.1.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

relates to https://github.com/aws/copilot-cli/issues/1140

### CODE REVIEW

**Review by kohidave — CHANGES_REQUESTED** [review]
Our build process is a little more complicated because we package some CloudFormation custom resources which are built in JavaScript. 

Perhaps you could take a look at our make target - but it requires the tool "packer" and npm.

**Comment by chenrui333** [comment]
Doing the requested updates now.

**Comment by chenrui333** [comment]
@kohidave, can you take another look of this PR?

**Comment by chenrui333** [comment]
Considering some of my upstream PRs have been merged and I have updated the build process the same as upstream script. Merging this formula now.

**Comment by SMillerDev** [comment]
Commits should have been squashed first

**Comment by chenrui333** [comment]
> Commits should have been squashed first

yeah, I only have one commit in here though.

**Pull request closed without merging**
