### PR TITLE
tbb 2018

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@ilovezfs why is this `do not merge`?

**Comment by ilovezfs** [comment]
@fxcoudert the removal of the patch needed to be validated as sane, but it's looks fine to me. It's look like upstream went with a slightly different approach but it should still be ok.

We had
```
-#if __GXX_EXPERIMENTAL_CXX0X__ && ((__INTEL_COMPILER >=1300 && __INTEL_COMPILER <=1310 && __TBB_GLIBCXX_VERSION>=40700) || (__TBB_GLIBCXX_VERSION < 40500))
+#if __GXX_EXPERIMENTAL_CXX0X__ && !__clang__ && ((__INTEL_COMPILER >=1300 && __INTEL_COMPILER <=1310 && __TBB_GLIBCXX_VERSION>=40700) || (__TBB_GLIBCXX_VERSION < 40500))
```

They went with
```
#if __GXX_EXPERIMENTAL_CXX0X__ && __GLIBCXX__ && ((__INTEL_COMPILER >=1300 && __INTEL_COMPILER <=1310 && __TBB_GLIBCXX_VERSION>=40700) || (__TBB_GLIBCXX_VERSION < 40500))
```

**Comment by fxcoudert** [comment]
@brewtestbot test this please

@ilovezfs yes the fix they have is correct, it depends on the libc++ rather than the compiler

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Somehow this didn't get High Sierra bottles (which were there in the previous version)

**Comment by ilovezfs** [comment]
yeah high sierra bottling has been on vacation

**Pull request closed without merging**
