### PR TITLE
comby 1.2.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by rvantonder** [comment]
@carlocab this should work with OCaml 4.12. 

It needs:

`depends_on "libev"`

and possibly (?)

`depends_on "libevent"`

too.

(I didn't have the chance to open a PR in time, before it was was autogenerated :-))

**Comment by carlocab** [comment]
Thanks, @rvantonder. I've added a dependency on `libev`, and can add one on `libevent` too if it's needed.

Are these runtime dependencies, or build-only?

And thanks for the update on Ocaml 4.12. Right now the version bump (#71942) is being blocked by Coccinelle, though. If you have any hints about that, that would be appreciated.

**Comment by rvantonder** [comment]
`libev` is a runtime dependency, yep.

Commented about `coccinelle` in https://github.com/Homebrew/homebrew-core/pull/71942#issuecomment-790016168

**Review by carlocab — APPROVED** [review]
Looks like this is building now. Thanks, @rvantonder.

**Pull request closed without merging**
