### PR TITLE
New formula: Kash (Kotlin-powered shell)

### PR DESCRIPTION
**Pull request by cbeust**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
The formula is missing a Java dependency.

**Comment by cbeust** [comment]
@SMillerDev, which dependency? The test passes...

**Comment by cbeust** [comment]
Ah, I added `depends_on :java`.

**Comment by Stvad** [comment]
```
==> Downloading https://github.com/cbeust/kash/archive/v1.9.tar.gz
Already downloaded: /Users/sitalov/Library/Caches/Homebrew/downloads/a5187d6ffb716daf9ed8b02f95824c24bad0f5b9670e8a38125f3e00f3ff55be--kash-1.9.tar.gz
==> ./gradlew assemble
Last 15 lines from /Users/sitalov/Library/Logs/Homebrew/kash/01.gradlew:
e: /private/tmp/kash-20190801-79086-br7sfm/kash-1.9/src/main/kotlin/com/beust/kash/CommandRunner.kt: (95, 37): Cannot infer a type for this parameter. Please specify it explicitly.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 2 executed

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
New formula: Kash (Kotlin-powered shell) https://github.com/Homebrew/homebrew-core/pull/42629
```

getting this when trying to install the current formula.  
My guess for the problem is that java is cask and it's not properly fetched.  So it's trying to use a different version of Java that does not work?

anyhow - manually running `brew cask install java` helped

**Comment by cbeust** [comment]
@Stvad That is very weird, any idea why your run is failing while the test is passing?

**Comment by Stvad** [comment]
@cbeust not really. I don't know how the brew test env works, but maybe they have java on system that works by default? After all judging by discussion above - they worked even before you've added the dependency

**Comment by SMillerDev** [comment]
The way you currently set the dependency any java will suffice but your install requires 11. I guess the build environment has all installed by default

**Comment by cbeust** [comment]
The error you're seeing doesn't make sense to me (also, it's a Kotlin compilation error, so really nothing to do with the JDK version) and it doesn't correspond to a source line where that error would even make sense.

I'm thoroughly stumped right now.

**Comment by Stvad** [comment]
🤷‍♂️ it's reproducible - just removed the java12 cask and now getting the error again:

```
 /Users/sitalov  brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/c60e31b6f29afab2b95a3ff1f97de1ccec0b8379/Formula/kash.rb
==> Consider using `brew extract kash ...`!
This will extract your desired kash version to a stable tap instead of
installing from an unstable URL!

######################################################################## 100.0%
==> Reinstalling kash
==> Downloading https://github.com/cbeust/kash/archive/v1.9.tar.gz
Already downloaded: /Users/sitalov/Library/Caches/Homebrew/downloads/a5187d6ffb716daf9ed8b02f95824c24bad0f5b9670e8a38125f3e00f3ff55be--kash-1.9.tar.gz
==> ./gradlew assemble
Last 15 lines from /Users/sitalov/Library/Logs/Homebrew/kash/01.gradlew:
e: /private/tmp/kash-20190801-87370-p5hne4/kash-1.9/src/main/kotlin/com/beust/kash/CommandRunner.kt: (95, 37): Cannot infer a type for this parameter. Please specify it explicitly.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 23s
2 actionable tasks: 2 executed

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
New formula: Kash (Kotlin-powered shell) https://github.com/Homebrew/homebrew-core/pull/42629
```

**Comment by cbeust** [comment]
I'll try to reproduce, how can I do this:

>  just removed the java12 cask

?

**Comment by SMillerDev** [comment]
`brew cask uninstall java` afaik

**Comment by cbeust** [comment]
```
$ brew cask uninstall java
> Error: Cask 'java' is not installed.
```

So still not sure how to reproduce this error.

Is this a blocker?

**Comment by cbeust** [comment]
Ok I made a blind fix (blind in the sense that I can't reproduce the failure locally). Please let me know if this fixes the problem.

**Comment by Stvad** [comment]
nope ☹️ 

```
######################################################################## 100.0%
==> Upgrading 1 outdated package:
kash 1.9 -> 1.11
==> Upgrading kash
==> Downloading https://github.com/cbeust/kash/archive/v1.11.tar.gz
Already downloaded: /Users/sitalov/Library/Caches/Homebrew/downloads/a0c8c39defdab8b77780a2679040923871294dd08881722b1ba9c5aa50367949--kash-1.11.tar.gz
==> ./gradlew assemble
Last 15 lines from /Users/sitalov/Library/Logs/Homebrew/kash/01.gradlew:
e: /private/tmp/kash-20190802-34704-130l6hu/kash-1.11/src/main/kotlin/com/beust/kash/CommandRunner.kt: (94, 40): Unresolved reference: startPipeline

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 20s
2 actionable tasks: 2 executed

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
New formula: Kash (Kotlin-powered shell) https://github.com/Homebrew/homebrew-core/pull/42629
```

What's your PATH java version? Mine is:

```
 /Users/sitalov  java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```

**Comment by cbeust** [comment]
This is because the compilation is being performed by Java 8.

I thought the formula I wrote forced Java to be 11 at least, did I miss
something?

**Comment by Stvad** [comment]
I think  your formula should create the launch script that'd use java 11, but for the compilation it uses whatever is in the PATH apparently

**Comment by cbeust** [comment]
Looks like it. Is there an easy way to require Java 11? I thought the
syntax I used when I create the script was it:

:java_version => "11.0
end
n Fri, Aug 2, 2019, 8:50 PM Vladyslav Sitalo <notifications@github.com>
wrote:

**Comment by jonchang** [comment]
You can require a specific version by using `depends_on :java => "1.8+"` or similar

`fgrep -r 'depends_on :java ' $(brew --repo homebrew/core)` for examples

**Comment by cbeust** [comment]
Thanks, @jonchang, I just pushed a new commit.

I first set the requirement to "12.0", verified that it failed, then made it "11.0" and confirmed that it correctly installed.

**Comment by Stvad** [comment]
Works as expected now 🎉

**Comment by cbeust** [comment]
Great. Is there anything else I need to do?

**Comment by jonchang** [comment]
Please rebase this on master and force push; the bottles have likely expired and will need to be rebuilt.

**Comment by cbeust** [comment]
Rebased.

**Comment by jonchang** [comment]
This shouldn't have brought in all of those commits. Can you force-push with a clean set of just this formula with the commit message `kash 1.9 (new formula)` [per our guidelines](https://docs.brew.sh/Formula-Cookbook#commit)?

**Comment by iMichka** [comment]
This has not moved for the last 26 days. The PR makes changes to more than 1000 files, which is probably a mistake.

I'll close this for the time being. Please open a new PR will a single commit to add the formula, and link to this PR for reference. Thanks.

**Pull request closed without merging**
