### PR TITLE
certbot: install more plugins

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://github.com/Homebrew/homebrew-core/issues/18227.

CC @DomT4

### CODE REVIEW

**Comment by DomT4** [comment]
No major objection. I basically held off on moving ahead with this in recent updates simply because formulae with a huge wad of python `resource`s have proven pretty unpleasant to update/maintain over time.

**Comment by ilovezfs** [comment]
Yeah I'm not thrilled with this, though it doesn't seem like a crazy request given these plugins are actually in the upstream repository.

**Comment by ilovezfs** [comment]
Yeah let's not do this.

**Comment by ameliaikeda** [comment]
While I think this is the wrong way to be going about it (installing certbot shouldn't install all plugins), there is a definite need for the plugins to be installable; it's literally impossible to use `dns-01` without them, so people end up just using pip instead of brew.

Maybe options, like `--with-cloudflare`, `--with-dnsimple`, etc?

**Comment by ilovezfs** [comment]
@ameliaikeda we should probably just not use virtualenv for certbot.

**Comment by ryansobol** [comment]
@ilovezfs In your opinion, how do we move forward with this? A project I'm working on depends on the bundled [`dns-dnsimple`](https://github.com/certbot/certbot/tree/master/certbot-dns-dnsimple) plugin and I'd rather use Homebrew instead of PIP.

**Pull request closed without merging**
