### PR TITLE
elasticsearch: use oss version

### PR DESCRIPTION
**Pull request by igas**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/homebrew-core/pull/36636 switched to non OSS version of elasticsearch. @hyuraku @lembacon please be careful next time, we only distribute [OSI-approved license](https://opensource.org/licenses).

### CODE REVIEW

**Comment by lembacon** [comment]
Should we also add a comment above the `url` line to clarify this?

**Comment by igas** [comment]
CI fails due to sha, but this is different archive, so it's ok

**Comment by javian** [comment]
@igas would bumping the revision make that error go away ?

**Comment by javian** [comment]
Thanks @igas ! ^^

**Pull request closed without merging**
