### PR TITLE
aliyun-cli 3.0.53

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can we get rid of the GOPATH usage here?

**Comment by SeekingMeaning** [comment]
Probably, working on it currently

**Comment by SeekingMeaning** [comment]
It depends on https://github.com/aliyun/aliyun-openapi-meta.git and uses whatever is the latest head, not sure what to do about that

**Comment by CL-Jeremy** [comment]
Spend some time trying to find a solution there. Some thoughts:
1. The tarball is (mostly) self-contained. The purpose of go module caching, I suppose, is to avoid repetitive downloads of dependencies. This is only achieved by switching from tarball to Git checkout, and upstream seems to support that.
2. The part which is not self-contained, as mentioned by @SeekingMeaning, is where `go get` gets used to pull the latest heads. Since upstream is using [shuLhan/go-bindata](https://github.com/shuLhan/go-bindata) out of the many variants of [go-bindata](https://github.com/Homebrew/homebrew-core/blob/master/Formula/go-bindata.rb), there is hardly any way around it: all variants suggest installing with `go get -u github.com/shuLhan/go-bindata/...`. No other Homebrew core formulae require this particular variant, and having that binary lingering in `go_mod_cache` is certainly a bad thing (FWIW, the switches are not exactly the same, nor are the outputs, but both should mostly work the same. I see Arch Linux using [this same variant](https://www.archlinux.org/packages/community/x86_64/go-bindata/) for [minikube](https://github.com/Homebrew/homebrew-core/blob/master/Formula/minikube.rb), while its [upstream](https://github.com/kubernetes/minikube/blob/master/Makefile#L293) uses the ancient [jteeuwen/go-bindata](https://github.com/jteeuwen/go-bindata)).
https://github.com/aliyun/aliyun-cli/issues/262 addresses exactly this, but I believe it's a bit superfluous in this context.
3. Regarding the problem of heads, if we are to ditch `GOPATH`, then it certainly wouldn't make a whole lot of sense to use `go_resource` either, so it seems `resource` is the way to go. It's easy to specify a hash there. 

Incorporating the above changes while retaining the use of vendored packages, here's the diff:
```diff --git a/Formula/aliyun-cli.rb b/Formula/aliyun-cli.rb
index 960c4e2425..72c3401e57 100644
--- a/Formula/aliyun-cli.rb
+++ b/Formula/aliyun-cli.rb
@@ -13,17 +13,18 @@ class AliyunCli < Formula
   end

   depends_on "go" => :build
+  depends_on "go-bindata" => :build
+
+  resource "aliyun-openapi-meta" do
+    url "https://github.com/aliyun/aliyun-openapi-meta.git",
+        :revision => "7d5ff4781f12b82970496dfd13acfcbf7dfec59b"
+  end

   def install
-    ENV["GO111MODULE"] = "off"
-    ENV["GOPATH"] = buildpath
-    ENV["PATH"] = "#{ENV["PATH"]}:#{buildpath}/bin"
-    (buildpath/"src/github.com/aliyun/aliyun-cli").install buildpath.children
-    cd "src/github.com/aliyun/aliyun-cli" do
-      system "make", "metas"
-      system "go", "build", "-o", bin/"aliyun", "-ldflags",
-                            "-X 'github.com/aliyun/aliyun-cli/cli.Version=#{version}'", "main/main.go"
-    end
+    (buildpath/"../aliyun-openapi-meta").install resource("aliyun-openapi-meta")
+    system "go-bindata", "-o", "resource/metas.go", "-pkg", "resource", "../aliyun-openapi-meta/..."
+    system "go", "build", "-mod=vendor", "-o", bin/"aliyun", "-ldflags",
+                          "-X 'github.com/aliyun/aliyun-cli/cli.Version=#{version}'", "main/main.go"
   end

   test do
```
Note the use of the flag `-mod=vendor`.

Another (hackier) approach if Git is used instead of tarball:
```diff --git a/Formula/aliyun-cli.rb b/Formula/aliyun-cli.rb
index 960c4e2425..d9974b738a 100644
--- a/Formula/aliyun-cli.rb
+++ b/Formula/aliyun-cli.rb
@@ -1,8 +1,9 @@
 class AliyunCli < Formula
   desc "Universal Command-Line Interface for Alibaba Cloud"
   homepage "https://github.com/aliyun/aliyun-cli"
-  url "https://github.com/aliyun/aliyun-cli/archive/v3.0.53.tar.gz"
-  sha256 "6a8c18830ac2c068feca763212809325a28fe0ea9646879962b34aba94e8ec26"
+  url "https://github.com/aliyun/aliyun-cli.git",
+      :tag      => "v3.0.53",
+      :revision => "3a18d15b71aa2d2320a1ab6b091ab3862ec03be0"
   license "Apache-2.0"

   bottle do
@@ -13,17 +14,19 @@ class AliyunCli < Formula
   end

   depends_on "go" => :build
+  depends_on "go-bindata" => :build

   def install
-    ENV["GO111MODULE"] = "off"
-    ENV["GOPATH"] = buildpath
-    ENV["PATH"] = "#{ENV["PATH"]}:#{buildpath}/bin"
-    (buildpath/"src/github.com/aliyun/aliyun-cli").install buildpath.children
-    cd "src/github.com/aliyun/aliyun-cli" do
-      system "make", "metas"
-      system "go", "build", "-o", bin/"aliyun", "-ldflags",
-                            "-X 'github.com/aliyun/aliyun-cli/cli.Version=#{version}'", "main/main.go"
+    meta_pkg_url = "github.com/aliyun/aliyun-openapi-meta"
+    meta_pkg_hash = "7d5ff4781f12b82970496dfd13acfcbf7dfec59b"
+    inreplace "Makefile" do |s|
+      s.gsub! /(go get.*#{meta_pkg_url})/, "\\1@#{meta_pkg_hash}"
+      s.gsub! %r{go get.*bindata/...},
+              "ln -s $$(go list -m -f {{.Dir}} #{meta_pkg_url}@#{meta_pkg_hash} | tr -d '\\n') ../aliyun-openapi-meta"
     end
+    system "make", "metas"
+    system "go", "build", "-o", bin/"aliyun", "-ldflags",
+                          "-X 'github.com/aliyun/aliyun-cli/cli.Version=#{version}'", "main/main.go"
   end

   test do
```
This is just to give some idea on possible solutions. The `resource` approach could work just as well here.

**Comment by SeekingMeaning** [comment]
Wow nice, thanks for looking at this, @CL-Jeremy

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
