### PR TITLE
cockroach: delete

### PR DESCRIPTION
**Pull request by bdarnell**
CockroachDB 19.2 uses a non-OSI-approved license so it is no longer
eligible for inclusion in homebrew-core. Its new home is

    brew install cockroachdb/tap/cockroach

It would be nice if we could leave some sort of forwarding stub in
place, but there doesn't seem to be any good way to do that and
mongodb was removed without a replacement in #43770 so we'll do the
same here.

### CODE REVIEW

**Comment by jonchang** [comment]
Hmm, as long as it still builds and is used I think we can leave this in. What do analytics say about usage? 

https://www.cockroachlabs.com/blog/oss-relicensing-cockroachdb/

This blog post seems to suggest that 19.2 will become OSI compliant in 2022.

**Comment by issyl0** [comment]
macOS analytics [say ~500 installs in the last 30 days, >1500 installs in the last 90 days](https://formulae.brew.sh/formula/cockroach). Linux analytics are significantly less but that's to be expected given the Homebrew on Linux user base, I think.

**Comment by jonchang** [comment]
@homebrew/core thoughts?

**Comment by MikeMcQuaid** [comment]
Agreed on removal if it doesn't use an OSI-approved license any more.

**Comment by chenrui333** [comment]
+1 for removal!

**Comment by igas** [comment]
+1 for removal

**Comment by SMillerDev** [comment]
Thanks @bdarnell even though you brought sad news

**Comment by chenrui333** [comment]
attach cockroachdb license change PR in here for future ref,  https://github.com/cockroachdb/cockroach/pull/42275

**Pull request merged**
