### PR TITLE
qt: QTBUG-67545 and QTBUG-67810, work around QTBUG-67606: Homebrew issue #27095

### PR DESCRIPTION
**Pull request by z00m1n**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

+ this patch works well, but once applied, a subsequent compile error occurs; hence `WIP:` for work in progress
+ will tick off point 3 and 4 in list above before submitting final pull request
+ see also https://github.com/Homebrew/homebrew-core/issues/27095

### CODE REVIEW

**Comment by DomT4** [comment]
Each patch needs its own `patch do` block, not least because the existing patch is pretty much quasi-permanent & the others shouldn't be.

**Comment by z00m1n** [comment]
giving up; see <https://github.com/Homebrew/homebrew-core/issues/27095>

**Comment by z00m1n** [comment]
managed to get this to work after all; re-open and submit to upstream:

```
host:~ user$ brew audit --strict qt
==> Installing or updating 'rubocop' gem
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.5.1.0.gem (100%)
Successfully installed parser-2.5.1.0
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.3.2.gem (100%)
Successfully installed unicode-display_width-1.3.2
Fetching: rubocop-0.55.0.gem (100%)
Successfully installed rubocop-0.55.0
8 gems installed

host:~ user$ brew audit --strict qt
```

--> no output, I take that as a pass

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by z00m1n** [comment]
In addition to the BrewTestBot tests and checks, we have successfully applied the proposed changes locally for custom Qt builds on several macOS 10.13 MBPs. The [Qt 5.11 release](https://wiki.qt.io/Qt_5.11_Release) (which possibly will have the fixes built in) might not take place until the end of May. This PR solves the 5.10 compilation issues for everyone building current Qt 5.10 in the meantime.

**Comment by DomT4** [comment]
Probably superseded by https://github.com/Homebrew/homebrew-core/pull/27882.

**Comment by ilovezfs** [comment]
@z00m1n thanks for the PR! This should now be resolved because 5.11.0 shipped.

**Pull request closed without merging**
