### PR TITLE
opencascade 7.3.0_p3

### PR DESCRIPTION
**Pull request by luzpaz**
Wasn't sure what to name the file. Some other package repos are naming it `7.3.0p3`. I'll defer to the devs

### CODE REVIEW

**Comment by luzpaz** [comment]
responded above

**Comment by zbeekman** [comment]
Does upstream provide pre-compiled binaries? This formula seems better suited for homebrew-cask.

In the meantime, if other package managers are calling this release `7.3.0p3` then I think we should follow suite. Can you please update and squash?

Thanks!

**Comment by luzpaz** [comment]
It's a mix when it comes how others have named the package:   
[Packaging status](https://repology.org/project/opencascade/versions)

**Comment by zbeekman** [comment]
> It's a mix when it comes how others have named the package:

50/50 mix it looks like. In that case, let's use what appears to be consistent with upstreams intentions, which is the way it is now, judging by the download url.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
