### PR TITLE
Gradle 4.0.1

### PR DESCRIPTION
**Pull request by ajayk**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Even though i have updated the aliases the brew audit is still complaining 
gradle:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/gradle.rb gradle@4.0
  * Formula has invalid versioned aliases:
      gradle@4.0.1

### CODE REVIEW

**Review by chenrui333 — COMMENTED** [review]
why did you need to revert the alias?

**Comment by ajayk** [comment]
@chenrui333 `brew audit --strict  gradle` was failing with the following error 

Formula has other versions so create a versioned alias:
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
ln -s ../Formula/gradle.rb gradle@4.0
Formula has invalid versioned aliases:
gradle@4.0.1

**Comment by ilovezfs** [comment]
Thanks @ajayk! Shipped!

**Comment by chenrui333** [comment]
@ajayk thanks for the explanation!

**Pull request merged**
