### PR TITLE
sbt 1.4.6

### PR DESCRIPTION
**Pull request by aaabramov**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] **Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?** **
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

** Tests are hanging because of https://github.com/Homebrew/homebrew-core/issues/67624

### CODE REVIEW

**Comment by SMillerDev** [comment]
You can change the test to use [`pipe_output("cmd", "input", exitcode)`](https://rubydoc.brew.sh/Homebrew/Assertions.html#pipe_output-instance_method)

**Comment by aaabramov** [comment]
@SMillerDev Found out that `--sbt-create` does the job.

```ruby
# --sbt-create        start sbt even if current directory contains no sbt project

  test do
    ENV.append "_JAVA_OPTIONS", "-Dsbt.log.noformat=true"
    system("#{bin}/sbt", "--sbt-create", "--debug", "about")
    assert_match version.to_s, shell_output("#{bin}/sbt sbtVersion")
    system "#{bin}/sbtn", "about"
    system "#{bin}/sbtn", "shutdown"
  end
```

Am I right that dir contents will be persisted in test sandbox between 
`system("#{bin}/sbt", "--sbt-create", "--debug", "about")` and `shell_output("#{bin}/sbt sbtVersion")` calls? Or should I add `--sbt-create` to `shell_output` also?

**Comment by SMillerDev** [comment]
The whole test block runs in a single sandbox so that's fine 👍

**Comment by aaabramov** [comment]
@SMillerDev pushed, could you please review?

**Comment by SMillerDev** [comment]
I could, but I'd rather wait for CI. Why do things a server can do for you instead 🤷

**Pull request merged**
