### PR TITLE
haskell-language-server 1.1.0

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
Currently, `1.1.0` is marked as a pre-release ([link](https://github.com/haskell/haskell-language-server/releases)).
```
haskell-language-server:
  * 1.1.0 is a GitHub pre-release.
```

**Comment by carlocab** [comment]
That's weird because the releases page says this was released 10 hours ago? https://github.com/haskell/haskell-language-server/releases

**Comment by nandahkrishna** [comment]
The release was created 10 hours ago on GitHub, but was marked as a pre-release and not the latest (at the time I checked). Now `1.1.0` is the latest.

**Comment by carlocab** [comment]
Nothing changed about the tarball, though, so I expect to see the same test failures. Not sure what to do about them though.

**Comment by kret** [comment]
Concerning failures in `brew test haskell-language-server` I did this:
https://github.com/Homebrew/homebrew-core/pull/75115/commits/221a92e5c5e08d373f290c21f512115d6508d772#diff-d1a55ee7c03c579c12c172ecf6d64ef59ff066be462d1706dc54ee01da8d04ddR70
It seems that HLS changed how it logs output...

**Comment by carlocab** [comment]
Thanks, @kret. I've included your change here.

**Review by nandahkrishna — APPROVED** [review]
Thanks @fishtreesugar and @kret!

**Pull request closed without merging**
