### PR TITLE
openrtsp 2021.01.01

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Let's see if it can build for ARM

**Comment by chenrui333** [comment]
```
==> make PREFIX=/usr/local/Cellar/openrtsp/2021.01.01 LIBS_FOR_CONSOLE_APPLICATION=/usr/local/opt/openssl@1.1/lib/libcrypto.dylib /usr/local/opt/openssl@1.1/lib/libssl.dylib install
cd liveMedia ; /Applications/Xcode.app/Contents/Developer/usr/bin/make install
make[1]: *** No rule to make target `Media.', needed by `libliveMedia.'.  Stop.
make: *** [install] Error 2
```

**Comment by chenrui333** [comment]
#69307

**Comment by chenrui333** [comment]
I think we can disable the formula (as we failed to update it many times)

**Pull request closed without merging**
