### PR TITLE
grafana 7.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> node_modules/grunt-cli/bin/grunt build
Failed to execute: node_modules/grunt-cli/bin/grunt
```

**Comment by burningalchemist** [comment]
Hi @chenrui333, @carlocab! `grunt` was recently replaced with `webpack` and removed from the dependencies. So the new way to build is to use the command behind `yarn build` from `package.json`:

```
system "node_modules/webpack/bin/webpack.js", "--config", "scripts/webpack/webpack.prod.js"
```
With the above I was able to successfully build the bottle. :)

Reference: [Grafana PR #29461](https://github.com/grafana/grafana/pull/29461/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R10)

**Comment by carlocab** [comment]
Thanks, @burningalchemist. Do you mind opening a new PR to update the formula?

**Comment by burningalchemist** [comment]
@carlocab Sure, will be open in a moment. :+1:

**Comment by carlocab** [comment]
Superseded by #70521.

**Pull request closed without merging**
