### PR TITLE
Updating the OpenVDB source hash

### PR DESCRIPTION
**Pull request by dcoeurjo**
Update of the mismatched SHA256 hash for the source code.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
This has to be reported to, and explained by, upstream before we merge it, in order to rule out malicious circumstances.

Please open an issue here: https://github.com/dreamworksanimation/openvdb/issues

**Comment by dcoeurjo** [comment]
reported in https://github.com/dreamworksanimation/openvdb/issues/172

**Comment by dcoeurjo** [comment]
Hash confirmed form upstream (see above).

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @dcoeurjo!

**Pull request closed without merging**
