### PR TITLE
flang 11.0.0 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Sets up flang as a separate formula so that llvm can be built without a
gcc dependency. See https://github.com/Homebrew/homebrew-core/pull/63081

Follow up to https://github.com/Homebrew/homebrew-core/pull/65223

`brew audit` does not like the `depends_on "llvm"`, but I don't think
this will build with just Apple Clang. flang needs to be built with
mlir.

### CODE REVIEW

**Comment by carlocab** [comment]
This is the build error, even if the arguments to `cmake` omit the `DMLIR_DIR` option.

```
CMake Error at CMakeLists.txt:75 (find_package):
  Could not find a package configuration file provided by "MLIR" with any of
  the following names:

    MLIRConfig.cmake
    mlir-config.cmake
```

I guess flang really needs llvm with the mlir project built.

**Comment by jonchang** [comment]
Would it be possible to do what we've done in `libgccjit` (vs gcc) to essentially do a separate build of llvm that just has mlir plus flang?

**Comment by carlocab** [comment]
I was thinking of doing something like that. I'll have a look at the `libgccjit` formula for ideas.

I guess one issue that might come up is that it looks like it will produce about a dozen (maybe, didn't count) binaries that duplicate ones that already come with llvm. That's what happened when I tried to build llvm locally with just mlir. Hard to say if I just did something wrong though -- building it takes forever.

**Comment by jonchang** [comment]
I know you can speed up gcc by skipping the second and third stage build so see if that is possible for llvm as well. You can also set `ENV.O0` to build without optimizations for testing.

**Comment by carlocab** [comment]
Huh, good to know. Thanks.

I've changed the formula to build llvm+mlir&flang. However, I suspect that this won't build -- it'll probably need some of the same patches already in the llvm formula. If it does build, however, I'll then have to look at taking care of duplicates.

**Comment by carlocab** [comment]
Avoiding duplications of what is already in the llvm formula/keg seems tricky, since flang seems to look for things that come in a standard llvm installation. This is the build error when I insist on building only mlir and flang:
```
CMake Error at lib/FuzzMutate/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/tmp/flang-20201120-94637-1q400kx/llvm-project-11.0.0/llvm/build/lib/libLLVMFuzzMutate.a":
  No such file or directory.
Call Stack (most recent call first):
  lib/cmake_install.cmake:43 (include)
  cmake_install.cmake:65 (include)
```
I'll need to think a bit about how to make this work properly.

The formulae for `libgccjit`, `libomp` and `clang-format` may serve as useful inspiration.

**Comment by fxcoudert** [comment]
> Flang is still a work in progress for this release and is included for experimentation and feedback

I'm a bit unconvinced that this definition fits Homebrew's general policy of including only stable software. Moreover, when flang is stable, we'll presumably build it as part of the llvm formula, and therefore will remove this standalone flang (and mlir) formulas. This seems all quite confusing for a couple of users, and maybe more suitable for a tap.

**Comment by carlocab** [comment]
@fxcoudert:

Sure, I can understand that. What are your thoughts on mlir? It seems mature enough and has a number of interesting applications: https://mlir.llvm.org/users/ It seems to be the most active bit of llvm, if their discourse is of any indication. (It may well not be.)

I unfortunately can't get it to build with the llvm formula, but it seems to build just fine on its own without duplicating anything (or at least, too much) from basic llvm.

Also interested in your thoughts, @jonchang.

**Comment by SMillerDev** [comment]
Flang is still a work in progress for this release and is included for experimentation and feedback

This is in conflict with this rule: https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

**Comment by carlocab** [comment]
@SMillerDev that wasn't my reading of the rule, but I'm happy to defer to you and FX on this issue.

Do you have thoughts on mlir? Adding it to the llvm formula seems to require more work than one would initially guess. If it's acceptable as a stand-alone formula, I think I have enough pieces to put together a complete PR. I don't think it duplicates anything in llvm, but I'll take a closer look at the completely built package if it's worth adding as a new formula.

**Comment by SMillerDev** [comment]
> Do you have thoughts on mlir? Adding it to the llvm formula seems to require more work than one would initially guess. If it's acceptable as a stand-alone formula, I think I have enough pieces to put together a complete PR. I don't think it duplicates anything in llvm, but I'll take a closer look at the completely built package if it's worth adding as a new formula.

I don't know much about the LLVM ecosystem, but if it doesn't violate any requirements it should be fine to add.

**Comment by carlocab** [comment]
I've managed to get the llvm formula to build with mlir: https://github.com/Homebrew/homebrew-core/pull/65223/checks?check_run_id=1451133623

The test failure in 11.0 is because odin, which depends on llvm, is broken on Big Sur. (Details on my llvm PR.)

I've confirmed that flang builds against that version of the llvm formula, so anyone interested in flang can use Homebrew llvm to compile flang. (I will set up a formula for flang in my tap if my llvm PR is merged.)

**Comment by fxcoudert** [comment]
OK, closing this then

**Comment by carlocab** [comment]
Here's the flang formula, for anyone interested: https://github.com/carlocab/homebrew-personal/blob/main/Formula/flang.rb

Thanks for the feedback while I worked in this, everyone.

**Pull request closed without merging**
