### PR TITLE
Chromedriver: fix use 2.23 mac64 because mac32 not available

### PR DESCRIPTION
**Pull request by schlueter**
- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open Pull Requests for the same formula update/change?
- [x] Have you built your formula locally prior to submission with brew install <formula> (where <formula> is the name of the formula you're submitting)?
- [x] Does your submission pass brew audit --new-formula <formula> (after doing brew install <formula>)?

### CODE REVIEW

**Comment by macosgrove** [comment]
I'd love to see this merged soon. The issue is blocking me.

**Comment by MikeMcQuaid** [comment]
@macosgrove Please be patient; you commented 8 hours after this was open. We're a project run by volunteers that is made freely available to the community.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew, @schlueter! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by schlueter** [comment]
Funny, I went to show the difference between this and the previous version to someone on an installation I knew had the previous version, and the 32 bit package had been restored. I suppose both work now, dunno if there should be options. Would anyone want to have the 32 bit version available as well?

**Comment by MikeMcQuaid** [comment]
> Would anyone want to have the 32 bit version available as well?

Will let this question sit open for a while and assume no answer means "no".

**Comment by outreach-devin-canterberry** [comment]
Looking just now, I don't see a *mac32* version anymore.

https://chromedriver.storage.googleapis.com/index.html?path=2.23/

BTW, regardless, my vote is that I don't need the 32-bit version.

**Pull request merged**
