### PR TITLE
FStar 0.9.5.0

### PR DESCRIPTION
**Pull request by beurdouche**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by beurdouche** [comment]
@ilovezfs :)

**Comment by ilovezfs** [comment]
Thanks @beurdouche! :tada:

For future reference, the bump subject should be downcased.

**Comment by beurdouche** [comment]
Ack @ilovezfs Thanks :)

**Comment by beurdouche** [comment]
@ilovezfs Corollary question: The release of F* on our website is shipped with a custom version that the Z3 team released just for us. https://github.com/FStarLang/binaries/tree/master/z3-tested
Unfortunately it is not considered ready for other uses, so we won't update the z3 formula until the next official release. Can you recommend a strategy to ship our own z3 within the F* formula ?
We have an option `--smt` within F* to point to the proper solver location... CC: @tchajed

**Comment by ilovezfs** [comment]
It can go in a resource block. If it's linked statically, the resource should be installed in the `buildpath`. If it's linked dynamically or just used as an executable at runtime, it should be installed in `libexec`.

**Pull request closed without merging**
