### PR TITLE
azion 1.12.0

### PR DESCRIPTION
**Pull request by tiagokrebs**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## Changelog
### New Features
* 540c0a2 feat: add metrics collector to all commands #minor
* 6792014 feat: add unlink command
* a287d34 feat: send metrics to the segment
### Improvements
* f199e9b chore: check for errors before writing metrics file
### Other Work
* e681b1d refactor: change link to unlink
* 27af127 refactor: removed prints adjustind lint no check error
* 583b6ff refactor: update message error
* 1ff4d6d refactor: update tests
* fef7cdc refactor: update tests

</pre>
</details>

### CODE REVIEW

**Comment by PatrickMenoti** [comment]
Apparently some actions got cancelled

**Comment by PatrickMenoti** [comment]
@p-linnane

**Comment by p-linnane** [comment]
We have a time limit on how long jobs can run, since our CI is self-hosted and we have limited resources. It's 45 minutes for arm64, and 90 minutes for x86_64. If this requires longer than that, we will need to wait for one of our two long-timeout slots to open up.

**Comment by PatrickMenoti** [comment]
> We have a time limit on how long jobs can run, since our CI is self-hosted and we have limited resources. It's 45 minutes for arm64, and 90 minutes for x86_64. If this requires longer than that, we will need to wait for one of our two long-timeout slots to open up.

Got it! I'll be waiting then. Thanks for replying.

**Comment by maxwelbm** [comment]
🍭

**Comment by PatrickMenoti** [comment]
> We have a time limit on how long jobs can run, since our CI is self-hosted and we have limited resources. It's 45 minutes for arm64, and 90 minutes for x86_64. If this requires longer than that, we will need to wait for one of our two long-timeout slots to open up.

Something I forgot to say yesterday: usually our PRs take 25-30 minutes for all CIs to run... for some reason, this one took more than that 🤔

**Comment by p-linnane** [comment]
So it appears the build is hanging. I just tried it locally:
```
==> go build -trimpath -o=/opt/homebrew/Cellar/azion/1.12.0/bin/azion -ldflags=-s -w -X github.com/aziontech/azion-cli/pkg/cmd/version.BinVersion=1.12.0 -X github.com/aziontech/azion-cli/pkg/constants.StorageApiURL=https://api.azion.com -X github.com/aziontech/azion-cli/pkg/constants.AuthURL=https://sso.azion.com/api -X github.com/aziontech/azion-cli/pkg/constants.ApiURL=https://api.azionapi.net ./cmd/azion
go: downloading github.com/MakeNowJust/heredoc v1.0.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/spf13/viper v1.14.0
go: downloading github.com/zcalusic/sysinfo v1.0.2
go: downloading go.uber.org/zap v1.24.0
go: downloading github.com/AlecAivazis/survey/v2 v2.3.7
go: downloading github.com/aziontech/go-thoth v0.0.0-20231215171110-aaa75e75c8df
go: downloading github.com/go-git/go-git/v5 v5.4.2
go: downloading github.com/joho/godotenv v1.5.1
go: downloading github.com/pelletier/go-toml/v2 v2.1.0
go: downloading github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966
go: downloading github.com/aziontech/azionapi-go-sdk v0.121.0
go: downloading github.com/schollz/progressbar/v3 v3.13.1
go: downloading github.com/zRedShift/mimemagic v1.2.0
go: downloading github.com/MaxwelMazur/tablecli v0.0.0-20230208145104-c9458b902b58
go: downloading github.com/segmentio/analytics-go/v3 v3.3.0
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/tidwall/gjson v1.14.3
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/tidwall/sjson v1.2.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading golang.org/x/term v0.6.0
go: downloading golang.org/x/text v0.4.0
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.9.2
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/mitchellh/colorstring v0.0.0-20190213212951-d06e56a500db
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20210428141323-04723f9f07d7
go: downloading github.com/go-git/go-billy/v5 v5.3.1
go: downloading github.com/imdario/mergo v0.3.12
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading github.com/google/uuid v1.3.1
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/machinebox/graphql v0.2.2
go: downloading github.com/segmentio/backo-go v1.0.0
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading golang.org/x/sys v0.6.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/magiconair/properties v1.8.6
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/subosito/gotenv v1.4.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/emirpasic/gods v1.12.0
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e
go: downloading github.com/go-git/gcfg v1.5.0
go: downloading github.com/kevinburke/ssh_config v0.0.0-20201106050909-4977a11b4351
go: downloading github.com/xanzy/ssh-agent v0.3.0
go: downloading golang.org/x/net v0.0.0-20221014081412-f15817d10f9b
go: downloading gopkg.in/warnings.v0 v0.1.2
```
It sits and ever gets past that point.

**Comment by PatrickMenoti** [comment]
> So it appears the build is hanging. I just tried it locally:
> 
> ```
> ==> go build -trimpath -o=/opt/homebrew/Cellar/azion/1.12.0/bin/azion -ldflags=-s -w -X github.com/aziontech/azion-cli/pkg/cmd/version.BinVersion=1.12.0 -X github.com/aziontech/azion-cli/pkg/constants.StorageApiURL=https://api.azion.com -X github.com/aziontech/azion-cli/pkg/constants.AuthURL=https://sso.azion.com/api -X github.com/aziontech/azion-cli/pkg/constants.ApiURL=https://api.azionapi.net ./cmd/azion
> go: downloading github.com/MakeNowJust/heredoc v1.0.0
> go: downloading github.com/fatih/color v1.13.0
> go: downloading github.com/pelletier/go-toml v1.9.5
> go: downloading github.com/spf13/cobra v1.7.0
> go: downloading github.com/spf13/viper v1.14.0
> go: downloading github.com/zcalusic/sysinfo v1.0.2
> go: downloading go.uber.org/zap v1.24.0
> go: downloading github.com/AlecAivazis/survey/v2 v2.3.7
> go: downloading github.com/aziontech/go-thoth v0.0.0-20231215171110-aaa75e75c8df
> go: downloading github.com/go-git/go-git/v5 v5.4.2
> go: downloading github.com/joho/godotenv v1.5.1
> go: downloading github.com/pelletier/go-toml/v2 v2.1.0
> go: downloading github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966
> go: downloading github.com/aziontech/azionapi-go-sdk v0.121.0
> go: downloading github.com/schollz/progressbar/v3 v3.13.1
> go: downloading github.com/zRedShift/mimemagic v1.2.0
> go: downloading github.com/MaxwelMazur/tablecli v0.0.0-20230208145104-c9458b902b58
> go: downloading github.com/segmentio/analytics-go/v3 v3.3.0
> go: downloading github.com/manifoldco/promptui v0.9.0
> go: downloading github.com/tidwall/gjson v1.14.3
> go: downloading github.com/spf13/pflag v1.0.5
> go: downloading github.com/tidwall/sjson v1.2.5
> go: downloading github.com/mattn/go-colorable v0.1.13
> go: downloading github.com/mattn/go-isatty v0.0.19
> go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
> go: downloading golang.org/x/term v0.6.0
> go: downloading golang.org/x/text v0.4.0
> go: downloading github.com/fsnotify/fsnotify v1.6.0
> go: downloading github.com/mitchellh/mapstructure v1.5.0
> go: downloading github.com/spf13/afero v1.9.2
> go: downloading github.com/spf13/cast v1.5.0
> go: downloading github.com/spf13/jwalterweatherman v1.1.0
> go: downloading go.uber.org/atomic v1.9.0
> go: downloading go.uber.org/multierr v1.8.0
> go: downloading github.com/mattn/go-runewidth v0.0.14
> go: downloading github.com/mitchellh/colorstring v0.0.0-20190213212951-d06e56a500db
> go: downloading github.com/ProtonMail/go-crypto v0.0.0-20210428141323-04723f9f07d7
> go: downloading github.com/go-git/go-billy/v5 v5.3.1
> go: downloading github.com/imdario/mergo v0.3.12
> go: downloading github.com/sergi/go-diff v1.1.0
> go: downloading github.com/google/uuid v1.3.1
> go: downloading github.com/tidwall/match v1.1.1
> go: downloading github.com/tidwall/pretty v1.2.0
> go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
> go: downloading github.com/machinebox/graphql v0.2.2
> go: downloading github.com/segmentio/backo-go v1.0.0
> go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
> go: downloading golang.org/x/sys v0.6.0
> go: downloading github.com/hashicorp/hcl v1.0.0
> go: downloading github.com/magiconair/properties v1.8.6
> go: downloading gopkg.in/yaml.v3 v3.0.1
> go: downloading gopkg.in/ini.v1 v1.67.0
> go: downloading github.com/subosito/gotenv v1.4.1
> go: downloading github.com/mitchellh/go-homedir v1.1.0
> go: downloading github.com/emirpasic/gods v1.12.0
> go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
> go: downloading github.com/rivo/uniseg v0.2.0
> go: downloading github.com/pkg/errors v0.9.1
> go: downloading golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e
> go: downloading github.com/go-git/gcfg v1.5.0
> go: downloading github.com/kevinburke/ssh_config v0.0.0-20201106050909-4977a11b4351
> go: downloading github.com/xanzy/ssh-agent v0.3.0
> go: downloading golang.org/x/net v0.0.0-20221014081412-f15817d10f9b
> go: downloading gopkg.in/warnings.v0 v0.1.2
> ```
> 
> It sits and ever gets past that point.

This is strange 🤔 it's stuck while downloading dependencies?

**Comment by PatrickMenoti** [comment]
We're trying to simulate this error locally, but we can't. 
We will keep on trying to figure out why this is happening

**Comment by PatrickMenoti** [comment]
@p-linnane can you provide more information on when you got stuck? Did you run exactly the command in your comment? 
Does it always get stuck when installing that same package? or it happens with different packages depending on the execution? 
Does the action have a different way/order of running things? (so we can better simulate the same behavior locally)

We are testing locally (excluding all dependencies first, so they are downloaded again) and we cannot simulate this issue.

**Comment by p-linnane** [comment]
All I did was check out this PR and run `brew install -sv azion`:
```
╰─ brew install -sv azion
==> Fetching azion
==> Downloading https://github.com/aziontech/azion/archive/refs/tags/1.12.0.tar.gz
==> Downloading from https://codeload.github.com/aziontech/azion/tar.gz/refs/tags/1.12.0
#-#O=#   #
/usr/bin/env tar --extract --no-same-owner --file /Users/patrick/Library/Caches/Homebrew/downloads/4f443702f438cb7fec2d5b83b815154b77485bc4cd4432bb0bcf058c3b9b69cf--azion-1.12.0.tar.gz --directory /private/tmp/d20240215-70205-ad8w1b
/usr/bin/env cp -pR /private/tmp/d20240215-70205-ad8w1b/azion-1.12.0/. /private/tmp/azion-20240215-70205-tf46t0/azion-1.12.0
==> go build -trimpath -o=/opt/homebrew/Cellar/azion/1.12.0/bin/azion -ldflags=-s -w -X github.com/aziontech/azion-cli/pkg/cmd/version.BinVersion=1.12.0 -X github.com/aziontech/azion-cli/pkg/constants.StorageApiURL=https://api.azion.com -X github.com/aziontech/azion-cli/pkg/constants.AuthURL=https://sso.azion.com/api -X github.com/aziontech/azion-cli/pkg/constants.ApiURL=https://api.azionapi.net ./cmd/azion
go: downloading github.com/MakeNowJust/heredoc v1.0.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/spf13/viper v1.14.0
go: downloading github.com/zcalusic/sysinfo v1.0.2
go: downloading go.uber.org/zap v1.24.0
go: downloading github.com/AlecAivazis/survey/v2 v2.3.7
go: downloading github.com/aziontech/go-thoth v0.0.0-20231215171110-aaa75e75c8df
go: downloading github.com/go-git/go-git/v5 v5.4.2
go: downloading github.com/joho/godotenv v1.5.1
go: downloading github.com/pelletier/go-toml/v2 v2.1.0
go: downloading github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966
go: downloading github.com/MaxwelMazur/tablecli v0.0.0-20230208145104-c9458b902b58
go: downloading github.com/aziontech/azionapi-go-sdk v0.121.0
go: downloading github.com/schollz/progressbar/v3 v3.13.1
go: downloading github.com/zRedShift/mimemagic v1.2.0
go: downloading github.com/segmentio/analytics-go/v3 v3.3.0
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/tidwall/gjson v1.14.3
go: downloading github.com/tidwall/sjson v1.2.5
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading github.com/google/uuid v1.3.1
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading golang.org/x/term v0.6.0
go: downloading golang.org/x/text v0.4.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/afero v1.9.2
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20210428141323-04723f9f07d7
go: downloading github.com/go-git/go-billy/v5 v5.3.1
go: downloading github.com/imdario/mergo v0.3.12
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading github.com/machinebox/graphql v0.2.2
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/mitchellh/colorstring v0.0.0-20190213212951-d06e56a500db
go: downloading github.com/segmentio/backo-go v1.0.0
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading golang.org/x/sys v0.6.0
go: downloading github.com/subosito/gotenv v1.4.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.6
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/emirpasic/gods v1.12.0
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/go-git/gcfg v1.5.0
go: downloading github.com/kevinburke/ssh_config v0.0.0-20201106050909-4977a11b4351
go: downloading github.com/xanzy/ssh-agent v0.3.0
go: downloading golang.org/x/net v0.0.0-20221014081412-f15817d10f9b
go: downloading gopkg.in/warnings.v0 v0.1.2
```

**Comment by maxwelbm** [comment]
󰌓  homebrew-core/Formula/a bump-azion-1.12.0 ✓ brew install -sv azion
==> Fetching azion
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/a2bf56561e5b5e6daa354926b11b7e1c0400a00f/Formula/a/azion.rb
Already downloaded: /Users/maxwel.mazur/Library/Caches/Homebrew/downloads/b97b92998141f4f5d6a60ec0603b28ac50b9d91691b4c0f975d73bb16a0a35cb--azion.rb
==> Downloading https://github.com/aziontech/azion/archive/refs/tags/1.11.2.tar.gz
Already downloaded: /Users/maxwel.mazur/Library/Caches/Homebrew/downloads/b902f7a0fbcc8f1c0edca4d5712d37d35767f4625f2c7bbc88aaa74aae620346--azion-1.11.2.tar.gz
/usr/bin/env tar --extract --no-same-owner --file /Users/maxwel.mazur/Library/Caches/Homebrew/downloads/b902f7a0fbcc8f1c0edca4d5712d37d35767f4625f2c7bbc88aaa74aae620346--azion-1.11.2.tar.gz --directory /private/tmp/d20240215-39152-5g80ir
/usr/bin/env cp -pR /private/tmp/d20240215-39152-5g80ir/azion-1.11.2/. /private/tmp/azion-20240215-39152-tr5rfm/azion-1.11.2
==> go build -trimpath -o=/opt/homebrew/Cellar/azion/1.11.2/bin/azion -ldflags=-s -w -X github.com/aziontech/azion-cli/pkg/cmd/version.BinVersion=1.11.2 -X github.com/aziontech/azion-cli/pkg/constants.StorageApiURL=https://api.azion.com -X github.com/aziontech/azion-cli/pkg/constants.AuthURL=https://sso.azion.com/api -X github.com/aziontech/azion-cli/pkg/constants.ApiURL=https://api.azionapi.net ./cmd/azion
go: downloading github.com/MakeNowJust/heredoc v1.0.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/spf13/viper v1.14.0
go: downloading github.com/zcalusic/sysinfo v1.0.2
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading go.uber.org/zap v1.24.0
go: downloading github.com/AlecAivazis/survey/v2 v2.3.7
go: downloading github.com/aziontech/azionapi-go-sdk v0.121.0
go: downloading github.com/aziontech/go-thoth v0.0.0-20231215171110-aaa75e75c8df
go: downloading github.com/schollz/progressbar/v3 v3.13.1
go: downloading github.com/zRedShift/mimemagic v1.2.0
go: downloading github.com/go-git/go-git/v5 v5.4.2
go: downloading github.com/joho/godotenv v1.5.1
go: downloading github.com/pelletier/go-toml/v2 v2.1.0
go: downloading github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/tidwall/gjson v1.14.3
go: downloading github.com/MaxwelMazur/tablecli v0.0.0-20230208145104-c9458b902b58
go: downloading github.com/tidwall/sjson v1.2.5
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading github.com/google/uuid v1.3.1
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading golang.org/x/text v0.4.0
go: downloading golang.org/x/term v0.6.0
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.9.2
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/mitchellh/colorstring v0.0.0-20190213212951-d06e56a500db
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20210428141323-04723f9f07d7
go: downloading github.com/go-git/go-billy/v5 v5.3.1
go: downloading github.com/imdario/mergo v0.3.12
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading golang.org/x/sys v0.6.0
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading github.com/subosito/gotenv v1.4.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.6
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/machinebox/graphql v0.2.2
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/emirpasic/gods v1.12.0
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading golang.org/x/net v0.0.0-20221014081412-f15817d10f9b
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e
go: downloading github.com/go-git/gcfg v1.5.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/kevinburke/ssh_config v0.0.0-20201106050909-4977a11b4351
go: downloading github.com/xanzy/ssh-agent v0.3.0
go: downloading gopkg.in/warnings.v0 v0.1.2
==> Cleaning
==> Finishing up
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
:beer:  /opt/homebrew/Cellar/azion/1.11.2: 8 files, 17.3MB, built in 18 seconds
==> Running `brew cleanup azion`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

**Comment by p-linnane** [comment]
I've figured out that for some reason I have to hit return to escape that part where it hangs and finish the build. Not sure why that's happening, but guessing it's also what's occurring in CI. Let me see how we can resolve this.

**Comment by p-linnane** [comment]
Current theory is that there is some kind of flaw in your new code related to asking for permission to collect metrics. The application immediate attempts to make a network call after I hit return. Obviously I don't know your codebase, but I've verified 1.11.2 builds as expected, so that leads us to believe there may be some kind of issue there.

**Comment by PatrickMenoti** [comment]
> Current theory is that there is some kind of flaw in your new code related to asking for permission to collect metrics. The application immediate attempts to make a network call after I hit return. Obviously I don't know your codebase, but I've verified 1.11.2 builds as expected, so that leads us to believe there may be some kind of issue there.

Apparently, since brew runs the completions command, it is waiting for acceptance. I think we will have to ignore metrics collection for this command in specific so that we can escape this problem

**Comment by PatrickMenoti** [comment]
> Current theory is that there is some kind of flaw in your new code related to asking for permission to collect metrics. The application immediate attempts to make a network call after I hit return. Obviously I don't know your codebase, but I've verified 1.11.2 builds as expected, so that leads us to believe there may be some kind of issue there.

You can close this PR and we will open a new one with a patch for this unforeseen issue. Thanks for all the help

**Comment by p-linnane** [comment]
Thanks to @dduugg for figuring this out on our end & the azion team for all the patience!

**Pull request closed without merging**
