### PR TITLE
poppler 0.59.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @edporras looks like this upgrade is going to require some love :(

**Comment by edporras** [comment]
Uh oh 😐

FYI: I'd hold off on 0.58.0 if possible as the poppler team found an issue w/ it and will be releasing 0.59.0 in a day or two. See [this thread](https://lists.freedesktop.org/archives/poppler/2017-September/012445.html).

**Comment by DomT4** [comment]
IMO anything on >15 revisions should probably just be declared dead in these situations, unless upstreams are willing to resume issuing releases.

**Comment by ilovezfs** [comment]
@DomT4 that's not a particularly great policy since that many revisions without any patches means the software is solid regardless of when it had its last release, especially if the new problems haven't even been reported and ignored (yet).

**Comment by DomT4** [comment]
@ilovezfs That's a fair comment. I over-generalised my point, which was ill-advised here.

I more specifically meant that `diff-pdf` seems to still be pretty active upstream so abandoning cutting new tags may well have been a deliberate decision, which would make it an awkward fit for Homebrew, and that it may be worth seeking clarity on that point.

The other one, `pdf2htmlEX`, is officially marked dead upstream. They're seeking new maintainers but I presume from the lack of activity people haven't leapt forwards.

**Comment by ilovezfs** [comment]
Unfortunately it's still pretty popular:
```
Josephs-MacBook-Pro:Formula joe$ brew formula-analytics pdf2htmlex
install events in the last 30 days for pdf2htmlex
=====================================================================================================
1 | pdf2htmlex                                                                        | 892 |  99.89%
2 | pdf2htmlex --without-jpeg                                                         |   1 |   0.11%
=====================================================================================================
Total                                                                                 | 893 |    100%
=====================================================================================================
Josephs-MacBook-Pro:Formula joe$ 
```

**Comment by DomT4** [comment]
Formula could maybe be kept around with its own version of `poppler` in `libexec/vendor` or something if it's not worth trying to get a patch accepted upstream, I guess? :see_no_evil:

**Comment by ilovezfs** [comment]
Yeah, unless it can be patched.

**Comment by ilovezfs** [comment]
Or just a versioned formula if it will be useful for 3rd parties too which it sounds like it may be: https://github.com/macports/macports-ports/commit/5fc8c736bd715ee5b3d12cbba747cc571e2eef0d

**Comment by DomT4** [comment]
I _suspect_ its internal `fontforge` may well be vulnerable to the CVE Debian made public the other week, but I'm not completely sure. I can look into it later today. But I guess if it's going to carry a whole unique `fontforge` adding another resource to that, however chunky, isn't too hideous.

**Comment by DomT4** [comment]
Aye if there's a broader use case that's generally where versioned formulae come in rather than resources. I helped implement the darn system & I still can't work out quite how I feel about versioned formulae :smile:

**Comment by ilovezfs** [comment]
They're demons from the Underworld. It's not even a question.

**Comment by ilovezfs** [comment]
The evince problem should be fixed by https://github.com/Homebrew/homebrew-core/pull/17593.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please.

**Comment by ilovezfs** [comment]
clang build failure reported here: https://bugs.freedesktop.org/show_bug.cgi?id=102538

**Pull request closed without merging**
