### PR TITLE
protobuf 3.4.0

### PR DESCRIPTION
**Pull request by ed-flanagan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
The usual [horde of formulae](https://github.com/Homebrew/homebrew-core/pull/13021) will need revisions since this is a significant bump.

**Comment by ilovezfs** [comment]
protobuf-swift is toast: https://github.com/alexeyxo/protobuf-swift/issues/217

**Comment by fxcoudert** [comment]
@ed-flanagan please bump revision for `gjstest, grpc, libphonenumber, mobile-shell, protobuf-c, supersonic, szl, upscaledb, zbackup`

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Please do the revision bumps requested by @fxcoudert.

**Comment by ed-flanagan** [comment]
Apologize for being MIA. I probably should've let someone else commandeer.
I bumped the revisions for the formulae listed (minus `szl` which was deleted)
I also saw formulas `cockatrice`, `ddar`, `influxdb@0.8`, `mitmproxy`, `nanopb-generator`, `osm-pbf`, and `protobuf-swift` (already mentioned) had `depends_on` for `protobuf`. Should I bump those as well.

**Comment by ilovezfs** [comment]
@ed-flanagan thanks. Can you split it up as one commit per formula, please? Also, switching `protobuf-swift` to use `protobuf@3.1` should work for now.

**Comment by ed-flanagan** [comment]
Sure thing!

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Shipped! Thanks @ed-flanagan! You're awesome :white_check_mark:

**Pull request closed without merging**
