### PR TITLE
optipng: fix on 10.13

### PR DESCRIPTION
**Pull request by zmwangx**
See patch comments for details.

Patch submitted to upstream: https://sourceforge.net/p/optipng/patches/9/.

### CODE REVIEW

**Comment by ilovezfs** [comment]
>The block referencing st_atim used to be guarded by defined UTIME_NOW &&     # defined UTIME_OMIT, but futimens(2) and utimensat(2) have been added in     # macOS 10.13, and these macros are now defined.

I feel like crying.

**Comment by zmwangx** [comment]
> I feel like crying.

Wait until dyld3 breaks everything.

**Comment by ilovezfs** [comment]
formula-patches PR? Link to, and date of, upstream report in the formula?

**Comment by zmwangx** [comment]
Done.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
:eyeglasses: :ping_pong:

**Pull request merged**
