### PR TITLE
python@3.10 3.10.7

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
This should be done in the next hour or so.

**Comment by iMichka** [comment]
Fix for speedtest-cli: #110021

**Comment by iMichka** [comment]
Looks like `poetry` did not like that update:

```
2022-09-07T01:36:26.2528322Z ##[group]Full test poetry output
2022-09-07T01:36:26.2529036Z [32m==>[0m [1mTesting poetry[0m
2022-09-07T01:36:26.2531618Z [34m==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/poetry/1.2.0/bin/poetry --version[0m
2022-09-07T01:36:26.2532183Z [34m==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/poetry/1.2.0/bin/poetry new homebrew[0m
2022-09-07T01:36:26.2532892Z [34m==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/poetry/1.2.0/bin/poetry config virtualenvs.in-project true[0m
2022-09-07T01:36:26.2533599Z [34m==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/poetry/1.2.0/bin/poetry add requests[0m
2022-09-07T01:36:26.2534260Z Creating virtualenv homebrew in /tmp/poetry-test-20220907-1029002-1fmn9m/homebrew/.venv
2022-09-07T01:36:26.2534481Z 
2022-09-07T01:36:26.2534581Z Failed to unlock the item!
```

**Comment by xxyzz** [comment]
Looks like it's [keyring](https://github.com/jaraco/keyring)'s error, it can be [disabled](https://keyring.readthedocs.io/en/latest/#disabling-keyring) by setting this `PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`.

**Comment by carlocab** [comment]
`poetry` might have been fixed by #110433.

It would be good to rebase and re-run this. Not sure there's enough time for that before tomorrow's maintenance window though.

**Comment by xxyzz** [comment]
The poetry error is not fixed, maybe keyring is still need to be disabled. I wonder why the poetry tests only fail in this pull request.

**Comment by carlocab** [comment]
If we disable keyring in the test, does that mean users need to disable it on their own to use `poetry`?

If so, then that's not a good solution, because we are then shipping something effectively broken.

**Comment by xxyzz** [comment]
The test failed because Keychain can't be unlocked in CI, normal user probably won't encounter this error. But these test commands shouldn't need to find password in Keychain.

**Comment by carlocab** [comment]
> The test failed because Keychain can't be unlocked in CI

This was always the case, though. Why didn't it fail previously, and why is it failing now with this version of Python?

**Comment by xxyzz** [comment]
Maybe because it's a new feature: https://github.com/python-poetry/poetry/issues/1917#issuecomment-1238154825

I don't know why poetry wants to use keyring in this case but other people in that issue solved this error by disabling keyring.

**Comment by carlocab** [comment]
> Maybe because it's a new feature: [python-poetry/poetry#1917 (comment)](https://github.com/python-poetry/poetry/issues/1917#issuecomment-1238154825)
> 
> I don't know why poetry wants to use keyring in this case but other people in that issue solved this error by disabling keyring.

But the feature seems to be there already, but the failure appears to be triggered only by Python 3.10.7 and not Python 3.10.6. So I don't think the feature being new is enough of an explanation.

Hey @neersighted, apologies for the tag but we could use your expertise here. Does it make sense to disable `keyring` when testing `poetry` in CI here?

This makes sense to do if the `keyring` failure is peculiar to our CI environment. However, if it's an error a user will see when using it on their machine, then we'll want to do something else.

**Comment by neersighted** [comment]
Hi @carlocab -- keyring usage in Poetry is new, and the matrix of possible OS versions/keyring backends/local system configration is vast and well beyond the ability of any project to test. It's been pretty clear since this feature has made it out into the wild that Poetry needs more robust error handling/usage of keyring.

There should be improvements to keyring usage coming to future releases (including patch releases) of Poetry, but in the here and now, keyring should not be something you need in CI and can be safely disabled. It is a very desirable feature for end users (e.g. on macOS, storing credentials in the keychain instead of plaintext on disk), as PyPI credentials are incredibly valuable as supply chain attacks can be conducted using them.

I would suggest keeping an eye on the Poetry changelog for improvements to our handling of these errors, and in the mean time just setting the env var (or using the config file as described in https://github.com/python-poetry/poetry/issues/1917) to disable keyring in CI.

**Comment by iMichka** [comment]
Fix for audio: #111745

**Review by carlocab — APPROVED** [review]
I've seen the macOS failures elsewhere so they're pre-existing. Having `python3` built against `gcc-5` is also causing failures elsewhere on Linux, so let's merge this.

We probably want to set `CC=cc` on Linux or something to avoid hardcoding the GCC version.

**Pull request closed without merging**
