### PR TITLE
glib 2.64.4

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
```
Error: 3 failed steps!
brew test --verbose csound
brew test --verbose opentsdb
brew install root
```
 For `csound` see https://github.com/Homebrew/homebrew-core/pull/54364#issuecomment-626316365

For `opentsdb` see https://github.com/Homebrew/homebrew-core/pull/57232

For `root` see https://github.com/Homebrew/homebrew-core/pull/56512#issuecomment-650733319

**Comment by Rylan12** [comment]
@miccal if you're actively working on this, can you replace the deprecated `Language::Python.rewrite_python_shebang` with `rewrite_shebang` (See #55255)?

If you're not working on this, can you let me know so I can fix it in a different PR?

**Comment by miccal** [comment]
@Rylan12 all done -- I ran `brew audit --strict` before pushing, but would you mind having a quick look to ensure I did this correctly, thank you.

**Comment by Rylan12** [comment]
Thanks, @miccal! This looks good to me 👍 

Feel free to ping me once the CI finishes.

**Comment by miccal** [comment]
@Rylan12 done, just two failed steps now:
```
Error: 2 failed steps!
brew fetch --retry mlpack
brew test --verbose opentsdb
```

**Comment by Rylan12** [comment]
I think a rebase will solve the `mlpack` problem. It looks like a new bottle was published in the PR you linked but the new information (specifically the `rebuild 1`) wasn't in this PR.

Not sure about `opentsdb`. It looks like they're having the same problem in #57232, so hopefully it will be resolved there and a rebase will fix it here.

**Pull request closed without merging**
