### PR TITLE
aws-iam-authenticator 0.5.3

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
May need new `ldflags`
- **0.5.3**: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/v0.5.3/.goreleaser.yaml#L16
   `      - "-s -w -X pkg.Version={{.Version}} -X pkg.CommitID={{.Commit}} -buildid=''"`
- **0.5.2**: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/v0.5.2/.goreleaser.yaml#L16
   `      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"`

**Comment by nandahkrishna** [comment]
Thanks @cho-m. It's worth noting that the tests still fail though. I even downloaded their own binary from the releases page, and it suffers from the same problem.

**Comment by cho-m** [comment]
@nandahkrishna It may be related to how `ldflags` and `import` behave together.
Not entirely familiar with this, so will defer to someone else to comment.

I was able to use the full path that is being imported to get version info, e.g.
```
sigs.k8s.io/aws-iam-authenticator/pkg.Version=#{version}
sigs.k8s.io/aws-iam-authenticator/pkg.CommitID=#{Utils.git_head}
```

**Comment by nandahkrishna** [comment]
That fixes the problem, thanks @cho-m!

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
