### PR TITLE
f3d: ship optional components

### LINKED ISSUE #129767: F3D is not correctly installed
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I'm not a brew user, I'm a developper of the F3D application
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm looking at the update of the F3D package to 2.0.0 and it looks like you do not install it correctly

### What happened (include all command output)?

You are only installing using `make install` but missed to install optional component, especially the `configuration` component, which means that F3D is very barebone without any installed configuration.

The `sdk` component could also be installed in order to provide the libf3d.

### What did you expect to happen?

Correct configuration and sdk installed

More information here: https://github.com/f3d-app/f3d/releases/tag/v2.0.0

And here: https://f3d.app/doc/dev/BUILD.html#installing

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
not a brew user, but I suppose something like that:


brew install f3d
f3d /path/to/stl
```

resulting f3d windows contains only the stl instead of the whole UI of F3D with the grid and axis.
```

### PR DESCRIPTION
**Pull request by fxcoudert**
Closes #129767

### CODE REVIEW

**Comment by fxcoudert** [comment]
@carlocab why not autosquash?

**Comment by carlocab** [comment]
We can autosquash if you prefer. Just thought we didn't really need a new squashed version of your PR opened to replace this one since the extra commit is otherwise in the right format anyway.

**Comment by fxcoudert** [comment]
I don't have any preference, I thought our policy was one commit per formula.

**Review by carlocab — APPROVED** [review]

**Comment by mwestphal** [comment]
Thanks @fxcoudert !

**Pull request merged**
