### PR TITLE
cmake: wrap patch in stable...do block

### PR DESCRIPTION
**Pull request by nasyxx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Good catch - thanks!

The preferred way of stable-only patches is to instead have it like this, just above the bottle block:

```rb
stable do
  url "https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0.tar.gz"
  sha256 "b74c05b55115eacc4fa2b77a814981dbda05cdc95a53e279fe16b7b272f00847"

  # Allows CMAKE_FIND_FRAMEWORKS to work with CMAKE_FRAMEWORK_PATH, which brew sets.
  # Remove with 3.18.0.
  patch do
    url "https://gitlab.kitware.com/cmake/cmake/-/commit/c841d43d70036830c9fe16a6dbf1f28acf49d7e3.diff"
    sha256 "87de737abaf5f8c071abc4a4ae2e9cccced6a9780f4066b32ce08a9bc5d8edd5"
  end
end
```

instead of the current `url`/`sha256` lines & `patch` block.

Example for reference: https://github.com/Homebrew/homebrew-core/blob/f6834007e7854372363b92e20ac851cdd53cfc7b/Formula/cd-discid.rb

**Comment by nasyxx** [comment]
Should I also update the `revision` to `2`?

**Comment by Bo98** [comment]
Move the `depends_on` stuff back below the bottle block (`brew audit` will complain).

`revision` does not need to be bumped as this change only affects HEAD builds.

**Comment by nasyxx** [comment]
It should pass.

Screen Shot 2020-03-27 at 12 52 53 PM

**Comment by Bo98** [comment]
Thanks!

**Pull request merged**
