### PR TITLE
django-completion 3.2.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
>   ==> . /home/linuxbrew/.linuxbrew/Cellar/django-completion/3.2.9/etc/bash_completion.d/django && complete -p django-admin.py
  sh: 35: /home/linuxbrew/.linuxbrew/Cellar/django-completion/3.2.9/etc/bash_completion.d/django: Syntax error: "(" unexpected (expecting "}")

**Comment by iMichka** [comment]
sh: 35: -> this is using `sh` instead of `bash`. I force the usage of `bash`.

But there is another issue now:
`django-admin.py: no completion specification`

**Comment by chenrui333** [comment]
let me report the issue to the upstream.

**Comment by chenrui333** [comment]
upstream bug report, https://code.djangoproject.com/ticket/33354

**Comment by chenrui333** [comment]
Somehow it is working fine in both macOS and linux builds in my local.

```
linuxbrew@14950312653b:~/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ source "/home/linuxbrew/.linuxbrew/Cellar/django-completion/3.2.9/etc/bash_completion.d/django" && complete -p django-admin.py
complete -o default -F _django_completion django-admin.py
```

**Comment by chenrui333** [comment]
Also updating all the completion tests for linux builds, #91055

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
