### PR TITLE
sqlite 3.17.0

### PR DESCRIPTION
**Pull request by neutric**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by neutric** [comment]
3.17.0 introduced [a](https://www.sqlite.org/compile.html#default_lookaside) [few](https://www.sqlite.org/compile.html#disable_intrinsic) [new](https://www.sqlite.org/compile.html#enable_null_trim) compile-time options, none of which looked like must-haves to me and my moderate use of sqlite. Options are generally added based on user request, correct?

**Comment by neutric** [comment]
Now that Jenkins finished, [one](https://www.sqlite.org/compile.html#disable_intrinsic) of those newly introduced compile-time options sounds exactly like what I need to fix the failing Yosemite build. Can one of the more experienced contributors kindly guide me towards a canonical example of how to selectively enable an option for Yosemite?

**Comment by neutric** [comment]
Build fails on Yosemite/Xcode 7.2.1 with:
```bash
sqlite3.c:28836:10: error: use of unknown builtin '__builtin_add_overflow' [-Wimplicit-function-declaration]
  return __builtin_add_overflow(*pA, iB, pA);
         ^
sqlite3.c:28856:10: error: use of unknown builtin '__builtin_sub_overflow' [-Wimplicit-function-declaration]
  return __builtin_sub_overflow(*pA, iB, pA);
         ^
sqlite3.c:28856:10: note: did you mean '__builtin_add_overflow'?
sqlite3.c:28836:10: note: '__builtin_add_overflow' declared here
  return __builtin_add_overflow(*pA, iB, pA);
         ^
sqlite3.c:28871:10: error: use of unknown builtin '__builtin_mul_overflow' [-Wimplicit-function-declaration]
  return __builtin_mul_overflow(*pA, iB, pA);
         ^
sqlite3.c:28871:10: note: did you mean '__builtin_sub_overflow'?
sqlite3.c:28856:10: note: '__builtin_sub_overflow' declared here
  return __builtin_sub_overflow(*pA, iB, pA);
         ^
```

Integer overflow builtins were added in [GCC5](https://www.gnu.org/software/gcc/gcc-5/changes.html) and somewhat later in [Clang](https://bugs.llvm.org//show_bug.cgi?id=21716), perhaps 3.7.1.

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by neutric** [comment]
@nijikon Thanks for merging! Would you mind saying a few words to my question [above](https://github.com/Homebrew/homebrew-core/pull/9928#issuecomment-279495156)?

**Comment by nijikon** [comment]
`Options are generally added based on user request, correct?` Correct.

**Comment by ilovezfs** [comment]
>Options are generally added based on user request, correct?

@neutric that's correct, since we don't try to add options for every single configure feature.

**Comment by neutric** [comment]
@nijikon, @ilovezfs Thanks! Before I go and edit dbhash, sqldiff and sqlite-analyzer the same way: was the solution I chose to fix the Yosemite build too general?

**Comment by plumbojumbo** [comment]
@neutric Your fix is fine, but note that it probably won't be needed anymore with the next release as SQLite has a patch for this in the trunk already. [[1]](https://www.sqlite.org/src/info/810d29320b853b3a)

**Comment by dunn** [comment]
@neutric for #9931, #9930, and #9929, feel free to use the fix you used here.

**Comment by neutric** [comment]
@dunn Thanks for the feedback, it's done.

**Pull request closed without merging**
