### PR TITLE
libressl 2.4.2

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by alex** [comment]
If I understood the release notes correctly, 2.4.2 is now the latest stable release.

**Comment by DomT4** [comment]
Sigh. Yup, looks like it. If they've stuck to their usual thing of breaking API/ABI compatibility with each new stable branch & consequently adjusting the `.dylib` versioning you'll also need to revision `osquery` & `ponyc`.

**Comment by alex** [comment]
👍 will see what jenkins says.

**Comment by alex** [comment]
Nope! No ABI breakages, thank god.

**Comment by DomT4** [comment]
We're going to need the revision bumps. I'm unsure why it isn't being flagged here, perhaps the tests are insufficient or the projects only generate static libraries, but the `.dylib` versions have changed from:

* `libssl.38.dylib` => `libssl.39.dylib`
* `libcrypto.37.dylib` => `libcrypto.38.dylib`
* `libtls.10.dylib` => `libtls.11.dylib`.

Which means there's incompatible changes.

**Comment by DomT4** [comment]
Just a nit, but please try to stick to:
```
ponyc: revision for libressl
```
or similar when doing revision bumps in this context. It helps us trace things later if necessary & is a bit clearer in `brew log` for users.

Merged in https://github.com/Homebrew/homebrew-core/commit/a6bf3eb0fea07babb4aa25c14cc91fe239db1548, https://github.com/Homebrew/homebrew-core/commit/c19b74bf6972ec8a52e7d90d9c2a644a770fd9c7 & https://github.com/Homebrew/homebrew-core/commit/0e8cae31abb7c837fb9a54a0173d053d93a94818. Thank you again @alex, appreciated.

**Pull request closed without merging**
