### PR TITLE
glib 2.74.0, gobject-introspection 1.74

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by danielnachun** [comment]
This now requires `pcre2` instead of `pcre`.

**Comment by carlocab** [comment]
`cpansearch` still failing. Fixed in #111038.

**Comment by carlocab** [comment]
R is failing to build on Linux with
```
  In file included from ../../src/include/R_ext/Applic.h:41,
                   from integrate.c:33:
  ../../src/include/R_ext/BLAS.h:103:69: error: expected declaration specifiers or ‘...’ before ‘)’ token
    103 |                 const double *beta, double *y, const int *incy FCLEN);
        |                                                                     ^
  ../../src/include/R_ext/BLAS.h:110:49: error: expected declaration specifiers or ‘...’ before ‘)’ token
    110 |                 double *y, const int *incy FCLEN);
        |                                                 ^
  ../../src/include/R_ext/BLAS.h:117:69: error: expected declaration specifiers or ‘...’ before ‘)’ token
    117 |                 const double *beta, double *y, const int *incy FCLEN);
        |                                                                     ^
```
CC @Homebrew/linux

**Comment by carlocab** [comment]
Queue is empty. I'm borrowing the long-timeout label for #110946.

**Comment by danielnachun** [comment]
> R is failing to build on Linux with
> 
> ```
>   In file included from ../../src/include/R_ext/Applic.h:41,
>                    from integrate.c:33:
>   ../../src/include/R_ext/BLAS.h:103:69: error: expected declaration specifiers or ‘...’ before ‘)’ token
>     103 |                 const double *beta, double *y, const int *incy FCLEN);
>         |                                                                     ^
>   ../../src/include/R_ext/BLAS.h:110:49: error: expected declaration specifiers or ‘...’ before ‘)’ token
>     110 |                 double *y, const int *incy FCLEN);
>         |                                                 ^
>   ../../src/include/R_ext/BLAS.h:117:69: error: expected declaration specifiers or ‘...’ before ‘)’ token
>     117 |                 const double *beta, double *y, const int *incy FCLEN);
>         |                                                                     ^
> ```
> 
> CC @Homebrew/linux

I've reproduced this and noticed something very strange - if I force it to use brewed GCC 12 to build the code instead of the host GCC, it works.  I actually have been planning to propose that we just use brewed GCC for both the C/C++ and Fortran parts of R anyway so that it always uses the latest GCC to compile its own packages.  To make this work we'd just need (for now) `fails_with gcc: 11` to force it to use brewed GCC.

**Comment by carlocab** [comment]
Everything failed on Linux with
`  ** (/tmp/glib-20220919-10986-1uuf4ot/glib-2.74.0/build/glib/gtester:13705): WARNING **: 06:37:53.549: Failed to execute test binary: /tmp/glib-20220919-10986-1uuf4ot/glib-2.74.0/build/glib/gtester: Failed to close file descriptor for child process (Operation not permitted)`

Is the self-hosted runner broken? CC @Homebrew/linux

**Comment by carlocab** [comment]
> Everything failed on Linux with ` ** (/tmp/glib-20220919-10986-1uuf4ot/glib-2.74.0/build/glib/gtester:13705): WARNING **: 06:37:53.549: Failed to execute test binary: /tmp/glib-20220919-10986-1uuf4ot/glib-2.74.0/build/glib/gtester: Failed to close file descriptor for child process (Operation not permitted)`
> 
> Is the self-hosted runner broken? CC @Homebrew/linux

Thuis doesn't happen on a GitHub runner.

**Comment by carlocab** [comment]
Let's try skipping recursive dependents...

**Review by carlocab — APPROVED** [review]
Linux failures are pre-existing.

**Pull request closed without merging**
