### PR TITLE
gitlab-gem 4.16.1

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]
Thanks @SeekingMeaning  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by Rylan12** [comment]
The `httparty` resource can be updated to 0.18.1.

I tried to take care of it and push to this PR. It seems my changes pushed to your fork at https://github.com/SeekingMeaning/homebrew-core/commit/2d5d378345639304b9274fe8297dc335c9603b94 but didn't make it to this PR...

**Comment by Rylan12** [comment]
@SMillerDev sorry, looks we commented at the same time...

Should the `httparty` resource be updated first (it looks like its a [very minor change](https://github.com/jnunemaker/httparty/blob/master/Changelog.md#0181))

**Comment by SeekingMeaning** [comment]
That's strange, why didn't it update?

**Comment by SeekingMeaning** [comment]
I wonder how shortages work in terms of what happens to CI

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
