### PR TITLE
pulumi 1.0.0-beta.2

### PR DESCRIPTION
**Pull request by pgavlin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Homebrew formula should only ship stable software. Beta versions aren't allowed.

**Comment by pgavlin** [comment]
(I am an engineer on the Pulumi team)

The current version of Pulumi that is published on Brew is also a pre-release version. These changes update the formula to the latest pre-release, which we've labeled as a beta for clearer messaging.

**Comment by SMillerDev** [comment]
If that's the case it needs to be removed rather than updated.

**Comment by SMillerDev** [comment]
In addition to that, where does it say the current version is a pre-release version? So that mistake isn't made anymore in the future.

**Comment by pgavlin** [comment]
> In addition to that, where does it say the current version is a pre-release version?

As per our understanding of semver, the 0.x.y series is pre-release. We'd really prefer not to remove the formula: we have users that depend on this formula being available.

**Comment by SMillerDev** [comment]
> As per our understanding of semver, the 0.x.y series is pre-release. 
That's fair, but homebrew can't really assume that everyone follows that nicely. Was that really the only indication?

> We'd really prefer not to remove the formula: we have users that depend on this formula being available.
That's really unfortunate, maybe other @Homebrew/core members have a different opinion?

**Comment by casey-robertson** [comment]
what's the bar/standard?  Is there a QA/QC process?  Or is the word 'beta' enough to flag it?  Heavy Pulumi user here.....

**Comment by pgavlin** [comment]
> That's fair, but homebrew can't really assume that everyone follows that nicely. Was that really the only indication?

Just to be clear, the pre-1.0 versions we have released versions are vetted, validated releases. The v1.0.0-beta series we would like to publish is subject to the same validation. As we consider it our latest stable release (and indeed mark it as such on our install site), we would like to publish it here as well if possible.

**Comment by SMillerDev** [comment]
Admittedly the documentation is a bit lacking: https://docs.brew.sh/Acceptable-Formulae#stable-versions but the idea is that for homebrew to include anything, upstream must consider their software stable. There isn't an automated process for this but having beta in the name of your release is kind of a big red flag regarding the stability.

**Comment by MikeMcQuaid** [comment]
There's enough 30 day installs that we should probably keep this in: https://formulae.brew.sh/analytics/install/30d/. Agreed that it would have been good to more strongly indicate this was prerelease/beta software but nothing we can do about this now. 👍 to just merge this.

As a higher meta-commentary: we shouldn't accept new beta software/versions but once stuff is in we should aim to be on the newest equivalencies version which I consider this to be.

Thanks everyone for the input here.

**Pull request closed without merging**
