### PR TITLE
babl 0.1.74

### PR DESCRIPTION
**Pull request by yinmeng2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by brettkoonce** [comment]
see #50891

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
build failure
```
==> brew install --verbose --build-bottle babl
==> FAILED
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200303-27280-1xd6k99.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/babl.rb --build-bottle --verbose
==> Downloading https://download.gimp.org/pub/babl/0.1/babl-0.1.74.tar.xz
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/bec8f969f61409894f195f5f70fd0c7e5d765532c23b679676df91fa99427cf3--babl-0.1.74.tar.xz
==> Verifying bec8f969f61409894f195f5f70fd0c7e5d765532c23b679676df91fa99427cf3--babl-0.1.74.tar.xz checksum
tar xof /Users/brew/Library/Caches/Homebrew/downloads/bec8f969f61409894f195f5f70fd0c7e5d765532c23b679676df91fa99427cf3--babl-0.1.74.tar.xz -C /private/tmp/d20200303-27281-wbr2pe
cp -pR /private/tmp/d20200303-27281-wbr2pe/babl-0.1.74/. /private/tmp/babl-20200303-27281-zi6wa1/babl-0.1.74
chmod -Rf +w /private/tmp/d20200303-27281-wbr2pe
==> ./autogen.sh
Failed to execute: ./autogen.sh

```

**Comment by brettkoonce** [comment]
we noticed this as well when trying to build manually, fwiw

**Pull request closed without merging**
