### PR TITLE
r: build R.framework

### PR DESCRIPTION
**Pull request by my2dev**
- [ x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Enable build R.framework for homebrew/science/r-gui.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Can you please explain why you think this is needed? We've deliberately switched away from the framework build.

**Comment by my2dev** [comment]
r-gui requires R.framework at build time and run time. If R.framework does not exist, r-gui fails to build because xcodebuild can not find the header file.

**Comment by ilovezfs** [comment]
@my2dev can you not use https://github.com/caskroom/homebrew-cask/blob/master/Casks/r-app.rb for that?

**Comment by my2dev** [comment]
Science's r-gui and Cask's r-app are the same. I use Cask's r-app. Thanks for the advice.

**Pull request closed without merging**
