### PR TITLE
futhark 0.4.0

### PR DESCRIPTION
**Pull request by athas**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can it now compile with `ghc` (8.4.1) instead of `ghc@8.2`?

**Comment by Athas** [comment]
In principle yes, but I'm not sure it'll work with the current Stackage nightlies (a few missing dependencies that I'm working on updating in, but it will take an indeterminate amount of time to involve all the transitive maintainers).  I can certainly add enough crud to the formula that will make it use a newer GHC and a list of hardcoded older dependencies from Hackage, if that's preferable.  I can also see whether just asking for GHC 8.4.1 will work, but I think it's easiest to just stick to GHC 8.2 for now, and move to GHC 8.4 with the next version (which will certainly happen anyway).

**Comment by Athas** [comment]
Depending on GHC 8.4 will not work (Stack complains that it does not match the indicated LTS snapshot).

**Comment by fxcoudert** [comment]
https://github.com/Homebrew/homebrew-core/issues/25568

**Comment by Athas** [comment]
It does not look like it is feasible to build Futhark with GHC 8.4 at the moment.  Could this version bump still go in?  It won't cause an increase in the number of GHC 8.2 dependents, and the next version of Futhark will certainly use GHC 8.4 (assuming the upstream dependencies have been updated, which they likely will have).

**Comment by fxcoudert** [comment]
Can you please report the issue to them? It seems surprising that the latest release of the software doesn't build with the latest compiler version

**Pull request closed without merging**
