### PR TITLE
joplin: migrate to cask

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Same testing error as in https://github.com/Homebrew/homebrew-core/pull/57813

I have tried to fix this, but have not been successful.

Even changing the `test do` block to the very simple:
```
  test do
    system bin/"joplin", "help"
  end
```
gives the same keychain error.

Ping @SeekingMeaning and @chenrui333 for any advise.

Thanks.

**Comment by miccal** [comment]
No matter what I do, running `brew test joplin` _always_ results in a keychain error that I cannot reproduce when calling `joplin` directly from my shell.

**Comment by chenrui333** [comment]
Is there anyone that we can find some external help on this?

**Comment by chenrui333** [comment]
never mind, I saw the comment in the previous PR.

**Comment by miccal** [comment]
Sorry @chenrui333 I have tried several things to fix this, but all my attempts have been unsuccessful.

**Comment by SMillerDev** [comment]
What happens when you run the command in `brew sh`?

**Comment by miccal** [comment]
> What happens when you run the command in `brew sh`?

I will test this out tomorrow and report back, thanks @SMillerDev.

**Comment by miccal** [comment]
I have tried to re-build `joplin` from source to test @SMillerDev's suggestion regarding the failing tests, but I have run into another issue possibly related to the recent upgrade of `node` to 14.9.0 -- after running `brew install node`, running `brew test node` fails:
```
|-> brew test node
==> Testing node
==> /usr/local/Cellar/node/14.9.0/bin/node /private/tmp/node-test-20200830-65173-1ump12b/test.js
==> /usr/local/Cellar/node/14.9.0/bin/node -e 'console.log(new Intl.NumberFormat("en-EN").format(1234.56))'
==> /usr/local/Cellar/node/14.9.0/bin/node -e 'console.log(new Intl.NumberFormat("de-DE").format(1234.56))'
==> /usr/local/bin/npm -ddd --cache=/Users/miccal/Library/Caches/Homebrew/npm_cache --build-from-source install npm@
==> /usr/local/bin/npm -ddd --cache=/Users/miccal/Library/Caches/Homebrew/npm_cache --build-from-source install buff
Last 15 lines from /Users/miccal/Library/Logs/Homebrew/node/test.02.npm:
npm verb argv "/usr/local/Cellar/node/14.9.0/bin/node" "/usr/local/bin/npm" "-ddd" "--cache=/Users/miccal/Library/Caches/Homebrew/npm_cache" "--build-from-source" "install" "bufferutil"
npm verb node v14.9.0
npm verb npm  v6.14.7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 3401ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miccal/Library/Caches/Homebrew/npm_cache/_logs/2020-08-30T04_58_44_112Z-debug.log
Error: node: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/bin/npm -ddd --cache=/Users/miccal/Library/Caches/Homebrew/npm_cache --build-from-source install bufferutil
/usr/local/Homebrew/Library/Homebrew/formula.rb:2037:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1975:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1975:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb:112:in `block in <class:Node>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1846:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:492:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1845:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:910:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1844:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2086:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1838:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:37:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:36:in `<main>'
```

**Comment by miccal** [comment]
> What happens when you run the command in `brew sh`?

@SMillerDev no effect -- running `joplin config editor subl` in `brew sh` works as it should, but `brew test joplin` fails with the same keychain error.

**Comment by miccal** [comment]
Some thoughts:

1. I have tried in vain to fix the weird keychain error.

2. [As pointed out by @SeekingMeaning:](https://github.com/Homebrew/homebrew-core/pull/57813#issuecomment-660160918)

Screen Shot 2020-09-13 at 02 03 13

3. [I also reached out to the developer, but got no response.](https://github.com/Homebrew/homebrew-cask/pull/88554#issue-477478228)

4. [This is more up-to-date in `homebrew-cask`,](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/joplin.rb).

So, I propose that this formula be removed from `homebrew-core`. 

If this is removed, I could perhaps investigate adding a `binary` option to the Cask version.

Thoughts?

**Comment by SMillerDev** [comment]
If we have a conflict and this version doesn't work I'm fine with removing it in favor of a cask.

**Comment by miccal** [comment]
Just an FYI, though -- the Cask version does **not** support a `binary`, and the GUI and CLI versions [work quite differently.](https://github.com/laurent22/joplin/issues/2553#issuecomment-589946717)

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by huyz** [comment]
Is there a plan to bring back the Joplin CLI tool?

**Comment by miccal** [comment]
> Is there a plan to bring back the Joplin CLI tool?

Not at this stage, no.

[According to their homepage](https://joplinapp.org/#terminal-application) the best way to install the CLI tool is to use Node.

**Pull request closed without merging**
