### PR TITLE
gtk-mac-integration: fix for Apple Silicon

### PR DESCRIPTION
**Pull request by fxcoudert**
This is a call for help. `gtk-mac-integration` is one of the top blockers on Apple Silicon (https://github.com/Homebrew/brew/issues/10152), and we need to figure out how to fix it.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
gtk-mac-menu.c:73:10: error: use of undeclared identifier '_eventRef'
  return _eventRef;
         ^
```

@tschoonj do you have any idea what's happening?

**Comment by tschoonj** [comment]
That code uses the old Carbon API and should probably be disabled. I don't think any of the packages that depend on `gtk-mac-integration` are using the methods in that file so it should be safe to do so.

I could give it a try this weekend if you can wait that long...

**Comment by fxcoudert** [comment]
@tschoonj there is no hurry, I'm just trying to make steady (if slow) progress on ARM bottles

**Comment by tschoonj** [comment]
@jralls do you have an idea what can be done to fix this build issue? Thanks!

**Comment by jralls** [comment]
@tschoonj Of course, you got it in one. The old Carbon-based menu code isn't supported on Apple Silicon.

Why haven't you guys raised an issue on [gtk-mac-integration](https://gitlab.gnome.org/GNOME/gtk-mac-integration)? I hadn't noticed the issue because I don't routinely build for gtk2 anymore. 

However Ignacio Casal Quintero opened [an issue](https://gitlab.gnome.org/GNOME/gtk-mac-integration/-/issues/2) two years ago proposing that I remove Gtk2 support entirely and since it's had its [final release](https://gitlab.gnome.org/GNOME/gtk/-/commit/68631945733158f164427db84f01301d7e875763) I'm inclined to follow through on that. You said nobody is using the Carbon stuff. Is anyone that you know about still using PyGtk?

**Comment by tschoonj** [comment]
> @tschoonj Of course, you got it in one. The old Carbon-based menu code isn't supported on Apple Silicon.

Thanks for confirming my suspicions. 


> Why haven't you guys raised an issue on [gtk-mac-integration](https://gitlab.gnome.org/GNOME/gtk-mac-integration)? I hadn't noticed the issue because I don't routinely build for gtk2 anymore.

See https://gitlab.gnome.org/GNOME/gtk-mac-integration/-/issues/7

> However Ignacio Casal Quintero opened [an issue](https://gitlab.gnome.org/GNOME/gtk-mac-integration/-/issues/2) two years ago proposing that I remove Gtk2 support entirely and since it's had its [final release](https://gitlab.gnome.org/GNOME/gtk/-/commit/68631945733158f164427db84f01301d7e875763) I'm inclined to follow through on that. You said nobody is using the Carbon stuff. Is anyone that you know about still using PyGtk?

We still have two formulas (`gtksourceview` and `gwyddion`) that use gtk-mac-integration in combination with gtk2, so we would like to keep gtk2 support around for a bit longer if possible... Since both gtk2 and gtk3 version of gtk-mac-integration rely on the same source code, I assume this should not be very hard to do?

I am not 100% sure that any of the formulas use the Carbon frameworks, but would be really surprised if there are any.

We removed the PyGtk formula quite some time ago.

As a quick fix, would removing the `gtk-mac-*` files from `SOURCES` and `HEADERS` in [src/Makefile.am](https://gitlab.gnome.org/GNOME/gtk-mac-integration/-/blob/master/src/Makefile.am) produce a working build again? They appear to be the only files that use the Carbon API...

**Comment by tschoonj** [comment]
Looks like this fixed things!

**Pull request closed without merging**
