### PR TITLE
kubernetes-helm 2.11.0

### PR DESCRIPTION
**Pull request by sc250024**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sc250024** [comment]
@fxcoudert This one was a bit weird. I know Helm is a popular package: has this issue been encountered before?

**Comment by fxcoudert** [comment]
Yes, it was reported 3 weeks ago to the helm team: https://github.com/helm/helm/issues/4584

**Comment by mattfarina** [comment]
I'll take a look into this today. Just learned of the problem. For those who don't know... I'm a Glide and Helm maintainer so... I guess this is sorta on me or @technosophos to work out.

**Comment by sc250024** [comment]
Thank you @mattfarina !

**Comment by mattfarina** [comment]
https://github.com/Homebrew/homebrew-core/pull/32474 has the fix (I hope)

**Comment by commitay** [comment]
@BrewTestBot test this please

**Comment by commitay** [comment]
Thanks @sc250024 and @mattfarina!

**Comment by sc250024** [comment]
Thanks guys!

**Pull request closed without merging**
