### PR TITLE
sonarqube: renamed from sonar

### PR DESCRIPTION
**Pull request by Godin**
Sonar has been renamed into SonarQube 3 years ago - http://www.sonarsource.com/company/news/sonarsource-news/sonar-becomes-the-sonarqube-platform/

### CODE REVIEW

**Comment by zmwangx** [comment]
`sonar` was last updated 2016-08-08, so apparently people have noticed but have been happy with the status quo. I wonder if it's more appropriate to add `sonarqube` as an alias.

**Comment by zmwangx** [comment]
Actually there is already an alias: https://github.com/Homebrew/homebrew-core/blob/master/Aliases/sonarqube. I'll pass on this, but will let other maintainers chime in.

**Comment by Godin** [comment]
@zmwangx well, I was updating formula since Jan 2015, but unfortunately wasn't aware of mechanism of renaming and aliases, so kept it as is to not break things for existing users.

What is preferable - keep an alias or perform rename?

**Comment by zmwangx** [comment]
Oh it's you who's been updating the formula 😃 

On second thought, I don't feel strongly either way, you could rename it, but then you need to delete that alias.

**Comment by Godin** [comment]
I also don't mind to keep an existing name 😄  But renaming seems cleaner than aliasing.
So added removal of existing alias to this PR, let someone with merge rights decide whether to accept or reject this 😉 

Also should be noted that failure of check in Jenkins has been already discussed in https://github.com/Homebrew/homebrew-core/pull/3613#issuecomment-238281556 but unfortunately I had no time to work on this in upstreams.

**Comment by DomT4** [comment]
No objection to the rename. Would be nice to fix:
```
* `bottle modifier` (line 9) should be put before `depends_on` (line 7)
```
though 😉.

**Comment by Godin** [comment]
@DomT4 sure, fixed

**Comment by zmwangx** [comment]
I'm tempted to fix the test to remove useless use of regexp: `/SonarQube/` => `"SonarQube"` too.

**Comment by DomT4** [comment]
Aye. It can be done in post if necessary, but killing unnecessary regexes in favour of strings is 👍.

**Comment by zmwangx** [comment]
> It can be done in post if necessary

It's also a note to self 😃

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/8a1d0aea090a7e77cf4870c088eb759b9bad5072. Thank you for another contribution to Homebrew @Godin! 😺

**Comment by Godin** [comment]
@DomT4 sorry, missed messages about regex. Thanks for merging.

**Pull request closed without merging**
