### PR TITLE
ios-webkit-debug-proxy 1.7

### PR DESCRIPTION
**Pull request by artygus**
Upgrade ios-webkit-debug-proxy to v1.7

### CODE REVIEW

**Comment by zmwangx** [comment]
Could you please put

```ruby
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}"
```

on one line? That's just a total of 79 characters, doesn't deserve a line break. Thanks.

**Comment by zmwangx** [comment]
Never mind, I'll just shovel that into the same commit.

**Comment by zmwangx** [comment]
Merged as ace1729. Thank you for your contribution to Homebrew!

**Comment by artygus** [comment]
@zmwangx read to late, sorry. thanks for the merge!

**Comment by zmwangx** [comment]
No, 14 min is not "too late"! Sometimes our "needs response" tag goes unanswered for months. It's just a trivial fix without a CI rerun, so I being impatient just jumped the gun.

**Pull request closed without merging**
