### PR TITLE
libnghttp2: fix conflict error on upgrading

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/pull/86291#issuecomment-934394872

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
```
==> FAILED
xz:
  * Stable: should always include at least one HTTP mirror
Error: 1 problem in 1 formula detected
Error: Stable: should always include at least one HTTP mirror
```

**Comment by Bo98** [comment]
Uh ok not entirely sure why that's only showing up now but I guess I'll add one?

**Comment by Bo98** [comment]
Or actually there's no reason to use `xz` here anyway - I'll just switch the source to `gz`.

**Comment by carlocab** [comment]
We probably want to check that the new source compiles, just in case.

**Review by carlocab — DISMISSED** [review]

**Comment by Bo98** [comment]
Ok it's still picking up `xz` from somewhere, but not in brew CI or locally.

**Comment by carlocab** [comment]
`gettext`

**Comment by Bo98** [comment]
Just went ahead and added one. We can figure out the discrepancy later.

**Comment by Bo98** [comment]
oh ok I'll have a look

**Comment by Bo98** [comment]
I think I broke GitHub. Won't even push now.

**Review by MikeMcQuaid — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request merged**
