### PR TITLE
gjs 1.68.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Bo98** [comment]
mozjs resource can be updated to 78.9.0esr.

**Comment by carlocab** [comment]
We also have an `autoconf@2.13` formula (why tho?). Perhaps that can be used instead of the resource?

**Comment by SMillerDev** [comment]
> We also have an autoconf@2.13 formula (why tho?)

I believe 1 formula depends on it.

**Comment by Bo98** [comment]
`autoconf@2.13` exited for `gjs`. The resource was introduced because there was a proposal to delete the formula, but that never actually happened in the end.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
