### PR TITLE
yara 4.0.1

### PR DESCRIPTION
**Pull request by nyx0**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
```
./configure: line 14733: syntax error near unexpected token `PROTOBUF_C,'
./configure: line 14733: `    PKG_CHECK_MODULES(PROTOBUF_C, libprotobuf-c >= 1.0.0)'
```
Looks like there's a new dependency on `protobuf-c`.

**Comment by SMillerDev** [comment]
osquery needs a revision bump.

**Comment by nyx0** [comment]
Sorry, I'm not sure to understand why I need to do, it looks like it's an issue with another Formula isn't it?

**Comment by SMillerDev** [comment]
The `osquery` formula depends on yara so it will have to be rebuild. You can use https://docs.brew.sh/Manpage#bump-revision-options-formula to add a revision to that formula, causing the rebuild.

**Comment by issyl0** [comment]
I rebased this branch on master as there've been some `osquery` changes since ten days ago. Let's see how this goes.

**Review by issyl0 — DISMISSED** [review]

**Comment by SMillerDev** [comment]
OS query seems broken with this version.

**Comment by SMillerDev** [comment]
OS query still broken. Could you report this to osquery and try and get a release or patch that fixes it?

**Comment by nyx0** [comment]
I tried to compile the latest version of osquery (`4.3.0`) but it failed. Do you prefer me to open an issue or to pull request the formula and ask for help?

**Comment by SMillerDev** [comment]
Yeah, osquery is difficult to build.
https://github.com/Homebrew/homebrew-core/pull/54905 this would fix your issue.

**Comment by nyx0** [comment]
Ha yes easier that way :) thank you

**Comment by alebcay** [comment]
[`yara` 4.0.1 is now available](https://github.com/VirusTotal/yara/releases/tag/v4.0.1).

**Comment by iMichka** [comment]
You can now rebase this, and remove the osquery version bump.

**Comment by bayandin** [comment]
Could you please squash all the commits into one `yara 4.0.1`, then we're good to go

**Comment by nyx0** [comment]
damn I'm so sorry it's not what I thought it would happen. If you want you can delete this PR and I can recreate another one.

**Comment by MikeMcQuaid** [comment]
@nyx0 Try to `git fetch --all; git rebase -i origin/master` and ensure only your commit shows up.

**Comment by nyx0** [comment]
sorry again but I did that, I squashed commits that are irrelevant for this PR (aka `yara 4.0.0`, `osquery: revision bump for yara` and `ossuary - put the revision back to 16`) and pick `Bump YARA to 4.0.1` but I'm still not able to push.
```
$ git fetch --all; git rebase -i origin/master
Fetching origin
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
interactive rebase in progress; onto 96372720d2
Last commands done (2 commands done):
   pick e8f88bbfa0 tox: update 3.15.1 bottle.
   pick 52caa85765 tox: update 3.15.1 bottle.
Next commands to do (5 remaining commands):
   pick dc9aa248aa Bump YARA to 4.0.1
   squash 551aa98be1 yara 4.0.0
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'yara-4.0.0' on '96372720d2'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit (use -u to show untracked files)
Could not apply 52caa85765... tox: update 3.15.1 bottle.
```
```
$ git push
To github.com:nyx0/homebrew-core.git
 ! [rejected]              yara-4.0.0 -> yara-4.0.0 (non-fast-forward)
error: failed to push some refs to 'git@github.com:nyx0/homebrew-core.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
if I git pull I'm coming back to the way I was at the beginning.

**Comment by MikeMcQuaid** [comment]
> $ git push

Use `git push --force-with-lease` when you've changed history locally.

**Comment by SMillerDev** [comment]
Fixed it using:
```
git fetch --all
git rebase -i origin/master
//Removed the tox update here and squashed everything
git push --force-with-lease
```

**Comment by nyx0** [comment]
```
$ git rebase -i origin/master
error: cannot 'squash' without a previous commit
You can fix this with 'git rebase --edit-todo' and then run 'git rebase --continue'.
Or you can abort the rebase with 'git rebase --abort'.

$ git status                 
interactive rebase in progress; onto 96372720d2
No commands done.
Next commands to do (2 remaining commands):
   d e8f88bbfa0 tox: update 3.15.1 bottle.
   s b80db0bf2d Bump YARA to 4.0.1
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'yara-4.0.0' on '96372720d2'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit (use -u to show untracked files)

$ git rebase --edit-todo     
error: cannot 'squash' without a previous commit

$ git status            
interactive rebase in progress; onto 96372720d2
No commands done.
Next commands to do (2 remaining commands):
   drop e8f88bbfa0 tox: update 3.15.1 bottle.
   pick b80db0bf2d Bump YARA to 4.0.1
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'yara-4.0.0' on '96372720d2'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit (use -u to show untracked files)
```
I guess I'm still confuse why it's not working...

**Comment by bayandin** [comment]
It fails with
```
./configure: line 14733: syntax error near unexpected token `PROTOBUF_C,'
./configure: line 14733: `    PKG_CHECK_MODULES(PROTOBUF_C, libprotobuf-c >= 1.0.0)'
```

**Comment by bayandin** [comment]
Ah, it failed with the same error as initially. Have we lost adding a `protobuf-c` dependency (or it was fixed another way somehow)?

**Comment by nyx0** [comment]
hum it looks it disappear with the commits mess I did... I think I will just close this PR and reopen a proper one without all my mess. Are you ok with that?

**Comment by alebcay** [comment]
Superseded by #55506.

**Pull request closed without merging**
