### PR TITLE
balena-cli 16.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  npm WARN notsup Unsupported engine for balena-cli@16.0.0: wanted: {"node":">=16 <18"} (current: {"node":"14.21.3","npm":"6.14.18"})
  npm WARN notsup Not compatible with your version of node/npm: balena-cli@16.0.0
  npm verb notsup Not compatible with your version of node/npm: balena-cli@16.0.0
  npm verb notsup Required: {"node":">=16 <18"}
  npm verb notsup Actual:   {"npm":"6.14.18","node":"14.21.3"}
```

**Comment by chenrui333** [comment]
```
npm ERR! ../libusb/libusb/os/linux_udev.c:28:10: fatal error: libudev.h: No such file or directory
npm ERR!    28 | #include <libudev.h>
npm ERR!       |          ^~~~~~~~~~~
npm ERR! compilation terminated.
```

**Comment by chenrui333** [comment]
```
  balena-cli:
    * Files were found with references to the Homebrew shims directory.
      The offending files are:
        libexec/lib/node_modules/balena-cli/node_modules/lzma-native/build/liblzma/config.log
```

that is easy

**Comment by chenrui333** [comment]
some failures in here, https://github.com/Homebrew/homebrew-core/actions/runs/5005315102/jobs/8969273560?pr=131056

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
