### PR TITLE
libzip 1.6.1

### PR DESCRIPTION
**Pull request by samford**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by samford** [comment]
I tested this locally on macOS 10.15.2 and the error is as follows:

```
==> zip file1.zip file1
  adding: file1 (stored 0%)
==> zip file2.zip file1 file2
  adding: file1 (stored 0%)
  adding: file2 (stored 0%)
==> /usr/local/Cellar/libzip/1.6.0/bin/zipcmp -v file1.zip file2.zip
zipcmp(12650,0x11571cdc0) malloc: *** error for object 0x755e2cd7025e2cd7: pointer being freed was not allocated
zipcmp(12650,0x11571cdc0) malloc: *** set a breakpoint in malloc_error_break to debug
Error: libzip: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <1> expected but was
<nil>
```

`zipmerge` and `ziptool` seem to work fine, it's just `zipcmp` that's running into an error when executed.

**Comment by fxcoudert** [comment]
The error should be reported to the libzip project.

**Comment by samford** [comment]
I created an upstream issue (nih-at/libzip#150), so we'll have to wait and see if they can identify and resolve the source of the `malloc` error.  It was newly introduced with v1.6.0 and doesn't occur with v1.5.2 but unfortunately that's 10 months worth of commits where the error could have been introduced.

**Comment by samford** [comment]
It looks like they fixed the bug in [a commit after 1.6.0 was released](https://github.com/nih-at/libzip/commit/bd9fb11fa88f6a95b8afbd53796934adf4e6e6bd).  Looking at their previous release dates, it could be anywhere from a month to a year before the next release, unless they do a point release in the interim time.

If they don't, we can always include the patch in the formula until the next release.  I've tested this locally and it works as expected, so I can update the PR if necessary.

**Comment by fxcoudert** [comment]
Go for the patch!

**Comment by samford** [comment]
I was just about to add the version with a patch when I received a notification that a new version was released, so here's 1.6.1 (which includes the fix for the issue).

**Comment by SMillerDev** [comment]
If it does now, maybe move back to the upstream URL?

**Comment by samford** [comment]
The libzip.org website looks to be updated sometime after a release is made on GitHub (it doesn't appear to happen automatically with a release), so the GitHub releases would seem to be more canonical (and potentially more reliable), at least to me.  However, if you disagree, I can certainly update this later today when I get a chance.

**Comment by SMillerDev** [comment]
I know the php project tags before they officially release on the website and I sort of expect the same here. So moving to the website URL would be my preference.

**Comment by samford** [comment]
I've updated the PR to use the libzip.org URL, so this should be good to go now.

**Comment by SMillerDev** [comment]
Thanks @samford

**Pull request closed without merging**
