### PR TITLE
clarinet 2.8.0

### PR DESCRIPTION
**Pull request by daeho-ro**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by stefanb** [comment]
Not yet released on https://github.com/hirosystems/clarinet/releases

**Comment by chenrui333** [comment]
https://github.com/hirosystems/clarinet/issues/1521

**Comment by hugocaillard** [comment]
Thanks for warning us @chenrui333 
2.8.0 hasn't been released yet. I don't know why @daeho-ro opened this issue 🤔

**Comment by daeho-ro** [comment]
@hugocaillard 

The livecheck is working with tag as default, so I opened this.

```
brew lc clarinet
clarinet: 2.7.0 ==> 2.8.0
```

**Comment by hugocaillard** [comment]
@daeho-ro 
Ok I see, I wasn't aware of this livecheck command.
It's weird because the tag was apparently craeted (by me), but usually only the CI creates tags. I'll try to figure out how was this tag created
I'll delete the tag and we can close this issue.

**Comment by hugocaillard** [comment]
The tag was created by error, shouldn't happen again

**Comment by chenrui333** [comment]
#179242

**Pull request closed without merging**
