### PR TITLE
openssl 1.0.2k

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
Several packages didn't build, I sampled a few of them, not sure if they're relevant.

**Comment by DomT4** [comment]
`tor` will need a revision bump at least. The `osc` failure is weird but everything else looks as expected.

**Comment by tdsmith** [comment]
The failures all look like CI bugs except osc's pycurl build, which looks broken in a way that probably isn't specific to this version of openssl. I'll open tickets to bump tor and fix osc.

**Comment by tdsmith** [comment]
Thanks, Alex!

**Pull request closed without merging**
