### PR TITLE
assh 2.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@UniqMartin @DomT4 here's an example of one that should have
```
    prefix.install_metafiles "src/github.com/moul/advanced-ssh-config"
```
but doesn't have it.

A dodgy workaround would be to move prefix.install_metafiles to occur before entering def install rather than after. Perhaps a better answer would be to make brew aware of (or actually handle automatically or via DSL) these relocations so it knows where to find the metafiles after def install.

**Comment by ilovezfs** [comment]
@DomT4 more random CI breakage.

**Comment by ilovezfs** [comment]
It appears that the taps don't get updated to origin/master but just sit stuck at a random revision.

**Comment by ilovezfs** [comment]
I've manually corrected all of the nodes. Hopefully it won't regress again.

**Comment by MikeMcQuaid** [comment]
Would this be fixed by `cd "src/github.com/moul/advanced-ssh-config/cmd/assh"` (not the block form) or does it try to install metafiles from the `buildpath` itself? I like the idea of perhaps copying (rather than moving) before `install`.

**Comment by ilovezfs** [comment]
It's explicitly the buildpath: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/build.rb#L137-L139

>Would this be fixed by cd "src/github.com/moul/advanced-ssh-config/cmd/assh" (not the block form) or does it try to install metafiles from the buildpath itself? 

Nope, just tried. Also, I think that would be considered a bug since although we prefer the block form, an arbitrary formula can return from install with CWD any random unpredictable directory.

>I like the idea of perhaps copying (rather than moving) before install.

Yes, that should work, though it's possible that will prove confusing for some people.

**Comment by ilovezfs** [comment]
Also, that means we cannot use our `foo.install`, so the directory will have to be created in a separate mkdir_p or mkpath step first.

**Comment by ilovezfs** [comment]
And the items to be copied are then not easily specified since you have to explicitly exclude the directories you just created.

**Comment by ilovezfs** [comment]
@MikeMcQuaid So we get this:
```
    ENV["GOPATH"] = buildpath
    (buildpath/"src/github.com/moul/advanced-ssh-config").mkpath
    cp_r buildpath.children - [buildpath/"src"], buildpath/"src/github.com/moul/advanced-ssh-config"
    cd "src/github.com/moul/advanced-ssh-config/cmd/assh" do
      system "go", "build", "-o", bin/"assh"
    end
```

**Comment by MikeMcQuaid** [comment]
Seems the manual metafiles call may just be the answer here?

**Comment by ilovezfs** [comment]
Or you can choose from this banquet:
```
    ENV["GOPATH"] = buildpath
    dir = Pathname.new("src/github.com/moul/advanced-ssh-config")
    (buildpath/dir).mkpath
    cp_r buildpath.children - [buildpath/"src"], dir
    cd dir/"cmd/assh" do
      system "go", "build", "-o", bin/"assh"
    end
```
or
```
    ENV["GOPATH"] = buildpath
    dir = "src/github.com/moul/advanced-ssh-config"
    (buildpath/dir).mkpath
    cp_r buildpath.children - [buildpath/"src"], dir
    cd "#{dir}/cmd/assh" do
      system "go", "build", "-o", bin/"assh"
    end
```
or
```
    ENV["GOPATH"] = buildpath
    dir = "src/github.com/moul/advanced-ssh-config"
    (buildpath/dir).mkpath
    cp_r buildpath.children - [buildpath/"src"], dir
    cd dir do
      system "go", "build", "-o", bin/"assh", "cmd/assh/main.go"
    end
```
or when it fits
```
  def install
    ENV["GOPATH"] = buildpath
    dir = "src/github.com/moul/advanced-ssh-config"
    (buildpath/dir).mkpath
    cp_r buildpath.children - [buildpath/"src"], dir
    cd(dir) { system "go", "build", "-o", bin/"assh", "cmd/assh/main.go" }
  end
```

**Comment by DomT4** [comment]
I tried to come up with a sensible, reasonable addition to `build.rb` earlier & couldn't think of anything that would satisfy every case. We may just have to reintroduce the manual `prefix.install_metafiles` party for Go formulae that `cd` elsewhere to build.

**Comment by ilovezfs** [comment]
I think we could define something like `copy_install` and even let it take a block.
```
copy_install(buildpath, "src/github.com/moul/advanced-ssh-config") do
  system "go", "build", "-o", bin/"assh", "cmd/assh/main.go"
end
```

**Comment by ilovezfs** [comment]
And if you prefer it as a method of pathname:
```
(buildpath/"src/github.com/moul/advanced-ssh-config").copy_install(buildpath) do
  system "go", "build", "-o", bin/"assh", "cmd/assh/main.go"
end
```
or written with a silly intermediate variable:
```
pn = buildpath/"src/github.com/moul/advanced-ssh-config"
pn.copy_install(buildpath) do
  system "go", "build", "-o", bin/"assh", "cmd/assh/main.go"
end
```

**Comment by ilovezfs** [comment]
Or if you prefer it from the perspective of the source, not the destination:
```
buildpath.copy_to_subdir("src/github.com/moul/advanced-ssh-config") do
  system "go", "build", "-o", bin/"assh", "cmd/assh/main.go"
end
```

**Comment by UniqMartin** [comment]
To be honest, all of those variants look pretty unconvincing to me, particularly if this is repeated in a non-trivial number of Go-using formulae.

One idea I can currently think of is that we introduce some new DSL element that allows us to specify the directory inside the `buildpath` that the resource should be staged to (instead of into the `buildpath` directly), and by “resource” I also mean the primary resource associated with the `url`, `sha256` etc. lines at the top level of a formula (or in its `stable do` etc. blocks). This could look something like:

```ruby
url "https://github.com/moul/advanced-ssh-config/archive/v2.4.0.tar.gz",
    :stage_to => "src/github.com/moul/advanced-ssh-config"
```

That would also be the directory the `install` method would invoked in and that would be passed to `install_metafiles` instead of `buildpath`, e.g. for this formula:

```ruby
def install
  ENV["GOPATH"] = buildpath
  cd "cmd/assh" do
     system "go", "build", "-o", bin/"assh"
  end
end
```

Would this make any sense or is that too awfully contrived with too surprising behavior?

**Comment by MikeMcQuaid** [comment]
Or you can just use `cp` or `cp_r` instead of `install` 😉.

**Comment by ilovezfs** [comment]
@UniqMartin Yes, that's exactly the sort of thing I had in mind when I said

>Perhaps a better answer would be to make brew aware of (or actually handle automatically or via DSL) these relocations so it knows where to find the metafiles after install.

I, too, much prefer that to any of the variants above.

**Comment by ilovezfs** [comment]
pulling this as is, since it's no more broken than any of the others

**Pull request closed without merging**
