### PR TITLE
mypy 0.4.6

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by apjanke** [comment]
Build [failed](https://bot.brew.sh/job/Homebrew%20Core/11867/) during the doc generation step.

```
==> make -C docs html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.5
making output directory...

Configuration error:
There is a syntax error in your configuration file: invalid syntax (git.py, line 10)
make: *** [html] Error 1
```

**Comment by apjanke** [comment]
Looks like this may be because the `.py` files are using Python 3 syntax, but the `sphinx-build` invocation is using Python 2?

```
[~/tmp/mypy/mypy on ⇄ 29b7675]
$ python -m py_compile mypy/git.py
  File "mypy/git.py", line 10
    def is_git_repo(dir: str) -> bool:
                       ^
SyntaxError: invalid syntax

[✘ ~/tmp/mypy/mypy on ⇄ 29b7675]
$ python3 -m py_compile mypy/git.py
[~/tmp/mypy/mypy on ⇄ 29b7675]
$
```

It doesn't look like the Python 3 syntax in the files is new in itself, so maybe something in the doc build script has changed? A diff between the two tags doesn't show any changes, though. Locally, running the `make -C docs html` build step runs for v0.4.5 but not v0.4.6.

**Comment by apjanke** [comment]
Yeah, I think it's a Python/sphinx version incompatibility. If I `pip install sphinx` locally, then I get the same syntax error. But if I `pip3 install sphinx` so `sphinx-build` runs under `python3`, then `make -C docs html` succeeds.

**Comment by ilovezfs** [comment]
@apjanke I guess we need to add a `with-python3` option on the sphinx-doc formula?

**Comment by apjanke** [comment]
> I guess we need to add a with-python3 option on the sphinx-doc formula?

Sounds like.

Or maybe just switch sphinx-doc to install with python3 all the time? I would expect it to be backward compatible. It would be a heavier dependency, but sphinx-doc is generally a build-time-only dependency, so might not be that big a deal. IMHO, it would be nice to avoid having variants of sphinx-doc, since it's a nontrivial formula. Though I'm no Python expert.

A python3 sphinx-doc variant or requirement might be nontrivial, since the `python3` formula itself depends on `sphinx-doc` (optionally). The circular dependency with an option on part of the graph might not behave well. Hmm.

Or maybe the sphinx-doc formula could be modified to have `sphinx-build3` and similar suffixed commands which run it under python3?

Wish we knew why the breakage happened with this version. I don't see any changes in the distribution that would have triggered it. And it seems like the python 2.x based sphinx-doc was happy with python3 syntax before.

**Comment by zmwangx** [comment]
The doc build failure here is due to python/mypy#2394 by Guido... See python/mypy#2593. py27-sphinx compatibility can be quite easily restored; I'm waiting for an official response.

Meanwhile, my unofficial patch can be found in #8073. There's also an unrelated theme fix that not only applies to 0.4.6.

@ilovezfs Feel free to close #8073 and apply the changes here. But I figured you have enough open PRs to worry about.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by nijikon** [comment]
Fixed in #8073

**Pull request closed without merging**
