### PR TITLE
cpr 1.10.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
See upstream issue at https://github.com/libcpr/cpr/issues/870.

**Comment by cho-m** [comment]
Big Sur failure (system `curl`):
```
/tmp/cpr-20230126-31846-t1uved/cpr-1.10.0/include/cpr/util.h:26:36: error: use of undeclared identifier 'CURL_PROGRESSFUNC_CONTINUE'
      static_assert(cancel_retval != CURL_PROGRESSFUNC_CONTINUE);
                                     ^
```

`CURL_PROGRESSFUNC_CONTINUE` was added in 7.68.0 (https://github.com/curl/curl/commit/7cf18b05e04bbb0f08c74d2567b0648f6c31a952). Big Sur has 7.64.1.

---

Linux failure (homebrew `curl`): 
```
/tmp/cpr-20230126-7792-cii1x0/cpr-1.10.0/cpr/curlholder.cpp:24:18: error: ‘void curl_formfree(curl_httppost*)’ is deprecated: since 7.56.0. Use curl_mime_free() [-Werror=deprecated-declarations]
```

We could try adding work around to not fail on this warning.

**Comment by alebcay** [comment]
> `CURL_PROGRESSFUNC_CONTINUE` was added in 7.68.0 (https://github.com/curl/curl/commit/7cf18b05e04bbb0f08c74d2567b0648f6c31a952). Big Sur has 7.64.1.

This should be fixed upstream - they have version detection and should be able to decide which functions/methods to use based on the version of `curl` that it is built against.

**Comment by p-linnane** [comment]
Upstream is responding to all issues indicating they are "on vacation" until March, so not sure if we will see anything from them for another month or so.

**Comment by chenrui333** [comment]
#124820

**Pull request closed without merging**
