### PR TITLE
gettext 0.21

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
The only failure for 10.15 and 10.14 was for `agda`, [which is to be expected](https://github.com/Homebrew/homebrew-core/issues/55253).

On 10.13 the failures were for `agda` and `gopass`; the `gopass` failure appears to merely be a time-out issue.

I think this can be merged.

Thanks.

**Review by Rylan12 — DISMISSED** [review]
LGTM.

The `agda` issue should be fine, but I just want to check with @chenrui333 about the `gopass` failure on 10.13.

<details><summary>Here's the output</summary>
<pre>==> FAILED
Testing gopass
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200727-17762-yh0nlb.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gopass.rb --verbose
==> /usr/local/Cellar/gopass/1.9.2_1/bin/gopass version
Killing child processes...
Error: gopass: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in ``'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in `shell_output'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gopass.rb:37:in `block in <class:Gopass>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1818:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1817:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:900:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1816:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2060:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2059:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1810:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
</pre></details>

It's pretty clearly a timeout error so I think it's fine.

**Comment by miccal** [comment]
Thanks again @Rylan12.

**Comment by SMillerDev** [comment]
> It's pretty clearly a timeout error so I think it's fine.

That's not fine, it should be fixed.

**Comment by Rylan12** [comment]
> That's not fine, it should be fixed.

Yes, you're right. Sorry for jumping the gun a little here.

In #58772, there were no timeout issues. I think this means it's either:

1. A fluke for some reason
1. An issue with `gettext`

I don't have a high sierra machine to test in so I'm not sure how to diagnose

**Comment by miccal** [comment]
@Rylan12 would you like me to `rebase` after https://github.com/Homebrew/homebrew-core/pull/58772?

**Comment by Rylan12** [comment]
Yeah, let's try that. I'm not really sure how else to diagnose it.

There's only one run going on at the moment so now's probably an okay time to start another long build.

**Comment by miccal** [comment]
@Rylan12 very strange -- the dependencies were not tested this time?

**Comment by Rylan12** [comment]
Thanks for pointing this out. It should be fixed in https://github.com/Homebrew/brew/pull/8141

**Comment by miccal** [comment]
@Rylan12 `agda` is now the only failure in all three runs -- `gopass` has passed.

**Comment by Rylan12** [comment]
Thanks. I'm going to continue with the merge as there's an issue open that needs the new `gettext` (#58819)

@Bo98 can you at least open a PR with the `agda` changes, even if it's not ready yet? As mentioned in https://github.com/Homebrew/homebrew-core/pull/58696#issuecomment-665694504, we need an open PR or issue that's specific to `agda` or we probably won't get around to fixing it.

**Review by Rylan12 — APPROVED** [review]

**Comment by fxcoudert** [comment]
Agda issue reported https://github.com/Homebrew/homebrew-core/issues/58984
Merging

**Comment by Rylan12** [comment]
Thanks, @miccal (sorry it took so long...)

**Comment by miccal** [comment]
Thank you @Rylan12 and @fxcoudert.

**Pull request closed without merging**
