### PR TITLE
topgrade 4.3.1

### PR DESCRIPTION
**Pull request by bashofmann**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by drrlvn** [comment]
Did this really cause the CI to fail? I suspect not, can the CI just be retried?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @bashofmann !!

**Comment by chenrui333** [comment]
```
  Compiling proc-macro2 v1.0.9
  Compiling unicode-xid v0.2.0
  Compiling syn v1.0.16
  Compiling cfg-if v0.1.10
  Compiling cc v1.0.50
  Compiling autocfg v1.0.0
  Compiling rustversion v1.0.2
  Compiling lazy_static v1.4.0
  Compiling memchr v2.3.3
  Compiling getrandom v0.1.14
  Compiling bitflags v1.2.1
  Compiling unicode-segmentation v1.6.0
  Compiling ppv-lite86 v0.2.6
  Compiling log v0.4.8
  Compiling unicode-width v0.1.7
  Compiling regex-syntax v0.6.14
  Compiling quick-error v1.2.3
  Compiling rustc-demangle v0.1.16
  Compiling block v0.1.6
  Compiling serde v1.0.104
  Compiling ansi_term v0.11.0
  Compiling termcolor v1.1.0
  Compiling vec_map v0.8.1
  Compiling nix v0.17.0
  Compiling anyhow v1.0.26
  Compiling strsim v0.8.0
  Compiling remove_dir_all v0.5.2
  Compiling topgrade v4.3.1 (/private/tmp/topgrade-20200419-19069-r75iws/topgrade-4.3.1)
  Compiling same-file v1.0.6
  Compiling void v1.0.2
  Compiling glob v0.3.0
  Compiling thread_local v1.0.1
  Compiling heck v0.3.1
  Compiling textwrap v0.11.0
  Compiling humantime v1.3.0
  Compiling num-traits v0.2.11
  Compiling num-integer v0.1.42
  Compiling c2-chacha v0.2.3
  Compiling walkdir v2.3.1
  Compiling quote v1.0.2
  Compiling malloc_buf v0.0.6
  Compiling atty v0.2.14
  Compiling dirs-sys v0.3.4
  Compiling time v0.1.42
  Compiling dirs v1.0.5
  Compiling termios v0.3.1
  Compiling clicolors-control v1.0.1
  Compiling aho-corasick v0.7.9
  Compiling backtrace-sys v0.1.32
  Compiling mac-notification-sys v0.3.0
  Compiling objc v0.2.7
  Compiling clap v2.33.0
  Compiling rand_core v0.5.1
  Compiling dirs v2.0.2
  Compiling directories v2.0.2
  Compiling regex v1.3.4
  Compiling objc_id v0.1.1
  Compiling rand_chacha v0.2.1
  Compiling shellexpand v2.0.0
  Compiling env_logger v0.7.1
  Compiling console v0.9.2
error: failed to run custom build command for `mac-notification-sys v0.3.0`
```

Failed to build on Catalina.

**Comment by chenrui333** [comment]
Give another try.

**Comment by chenrui333** [comment]
seems working fine on my catalina machine.
```
$ brew reinstall topgrade
==> Reinstalling topgrade
==> Downloading https://homebrew.bintray.com/bottles/topgrade-4.3.1.catalina.bottle.tar.gz
##O=#  #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "topgrade"
Download failed: https://homebrew.bintray.com/bottles/topgrade-4.3.1.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for topgrade: rust
==> Installing topgrade dependency: rust
==> Downloading https://homebrew.bintray.com/bottles/rust-1.42.0.catalina.bottle.tar.gz
Already downloaded: /Users/ruichen/Library/Caches/Homebrew/downloads/1ef21706dde1133c72a5902fe2639e95c83b1e4bc10f3bb85b5995e51d573f1c--rust-1.42.0.catalina.bottle.tar.gz
==> Pouring rust-1.42.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/rust/1.42.0: 20,487 files, 523MB
==> Downloading https://github.com/r-darwish/topgrade/archive/v4.3.1.tar.gz
==> Downloading from https://codeload.github.com/r-darwish/topgrade/tar.gz/v4.3.1
######################################################################## 100.0%
==> cargo install --locked --root /usr/local/Cellar/topgrade/4.3.1 --path .
🍺  /usr/local/Cellar/topgrade/4.3.1: 7 files, 1.6MB, built in 3 minutes 41 seconds
```

**Comment by bayandin** [comment]
Build fails on Catalina only:
```
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ImageIO.framework/Headers/ImageIOBase.h:16:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=In file included from objc/notify.m:1:
cargo:warning=objc/notify.h:1:9: fatal error: could not build module 'Foundation'
cargo:warning=#import <Foundation/Foundation.h>
cargo:warning= ~~~~~~~^
cargo:warning=16 errors generated.
exit code: 1

--- stderr


error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-apple-darwin" "-fmodules" "-o" "/private/tmp/topgrade-20200419-90728-q34l04/topgrade-4.3.1/target/release/build/mac-notification-sys-51b79d5eb48ef840/out/objc/notify.o" "-c" "objc/notify.m" with args "clang" did not execute successfully (status code exit code: 1).

```

**Comment by drrlvn** [comment]
I don't know enough to know but it looks like either the package is missing some kind of dependency or the CI is missing something because clang isn't available.

**Comment by bayandin** [comment]
`topgrade` 4.3.0 fails with the same error, so this error could be related either to Xcode update or some changes in superenv.

Adding `ENV.delete("HOMEBREW_SDKROOT") if MacOS.version == :catalina` make it works. Probably @Bo98 could comment it

**Comment by Bo98** [comment]
The latest CLT SDK has a bug. Apparently that bug doesn't exist in the Xcode SDK.

Apple should have deleted `<SDK>/usr/include/libxml2/module.modulemap` but they didn't. I will send a report to Apple later today.

As for why that is being read here, I don't know. For most formulae this is enough: https://github.com/Homebrew/brew/commit/32497bd5119f6ff7602f5a3c72a3c33df6813245. Apparently not for `topgrade`. Is it getting information from elsewhere?

`ENV.delete("HOMEBREW_SDKROOT")` might work, but it will still fail for CLT-only installs or installs where both are installed but `xcode-select` points to the CLT. It would probably be more "correct" to instead do `depends_on :xcode => :build if MacOS::CLT.version >= Version.new("11.4")` or similar - which enforces the Xcode SDK is used - though it's a bit annoying to have.

**Comment by bashofmann** [comment]
Should I try it and add this in this PR?

**Comment by bayandin** [comment]
> Apparently not for `topgrade`. Is it getting information from elsewhere?

It looks like it's not `topgrade` itself, but its dependency: `mac-notification-sys v0.3.0` fails

**Comment by Bo98** [comment]
I tried the Xcode thing in #53794. Can you rebase this?

**Pull request closed without merging**
