### PR TITLE
gdb i386-elf-gdb x86_64-elf-gdb 10.1

### PR DESCRIPTION
**Pull request by ksherlock**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Let's also update (but in a separate commit each) `i386-elf-gdb` and `x86_64-elf-gdb`. And migrate to `python@3.9`.

**Comment by fxcoudert** [comment]
`gdbgui` should be migrate at the same time (and its revision bumped)
When I tried in https://github.com/Homebrew/homebrew-core/pull/62462 it lead to issues, though

**Comment by ksherlock** [comment]
it's been rebased and the commits squished into 3

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @ksherlock

**Pull request closed without merging**
