### PR TITLE
perl 5.26.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @DomT4

**Comment by DomT4** [comment]
Will look this over later. You’ll need to bump everything that uses Perl because of the versioned packages path.

**Comment by ilovezfs** [comment]
@DomT4 any objections?

**Comment by DomT4** [comment]
`subversion` will need a bump too, to refresh the site-packages versioning.

**Comment by DomT4** [comment]
I'll try and throw together a test for `svn` so it won't need manually remembering every time.

**Comment by DomT4** [comment]
Yeah, adding `system "perl", "-e", "use SVN::Client; new SVN::Client()"` to the `subversion` formula should fail with this PR applied but without `svn` being bumped.

**Comment by ilovezfs** [comment]
@DomT4 perfect. Thanks!

**Comment by DomT4** [comment]
No worries! Hopefully makes things a bit easier in future. Thanks for pushing the `perl` update through.

**Pull request closed without merging**
