### PR TITLE
mxnet: migrate to python@3.11

### PR DESCRIPTION
**Pull request by ryenus**
Update formula **mxnet** to use python@3.11 instead of python@3.10, see the related pr https://github.com/Homebrew/homebrew-core/pull/114154

### CODE REVIEW

**Comment by chenrui333** [comment]
source tarball does not exist anymore
```
  ==> Downloading https://dlcdn.apache.org/incubator/mxnet/1.9.1/apache-mxnet-src-1.9.1-incubating.tar.gz
  curl: (22) The requested URL returned error: 404
```

**Comment by equal-l2** [comment]
The tarball has moved to <https://dlcdn.apache.org/mxnet/1.9.1/apache-mxnet-src-1.9.1-incubating.tar.gz>.

**Comment by chenrui333** [comment]
> The tarball has moved to https://dlcdn.apache.org/mxnet/1.9.1/apache-mxnet-src-1.9.1-incubating.tar.gz. (From `incubator` to own directory)

Thanks for the pointer!

**Comment by ryenus** [comment]
FYI, the releases are also available here: https://github.com/apache/mxnet/releases
e.g.: https://github.com/apache/mxnet/archive/refs/tags/1.9.1.tar.gz

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
