### PR TITLE
monit: Add plist according to the official wiki.

### PR DESCRIPTION
**Pull request by huxuan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by huxuan** [comment]
For reference of the official wiki: https://mmonit.com/wiki/Monit/Launchd

**Comment by huxuan** [comment]
Closed since the continuous integration test hang.

**Comment by SMillerDev** [comment]
We can just resrart those.

**Comment by huxuan** [comment]
@SMillerDev Hi Sean, this is Sean, too! :-)

I failed to find the place to trigger it, so I send a new pull request #52366 instead.

Could you tell me what I should do in case of similar situations?

**Comment by SMillerDev** [comment]
Just mention that it's stuck, a maintainer can restart it.

**Comment by huxuan** [comment]
@SMillerDev So just leaving a comment? Or is there anyone I should mention?

**Comment by SMillerDev** [comment]
Just leave a comment like you did. Except there's no need to close it.

**Comment by huxuan** [comment]
@SMillerDev Gotcha! Thanks so much!

**Pull request closed without merging**
