### PR TITLE
mercury: trigger CI

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
CI timed out but locally, this is fine: https://gist.githubusercontent.com/ilovezfs/b27ef778438f92118360a40a7724c95b/raw/c2ae6dfd158d1e99ebb7430c150b2fa25ca5d632/gistfile1.txt

**Comment by mikemcquaid** [comment]
👍 to bump timeout and get this bottled.

**Comment by DomT4** [comment]
FWIW in these situations we generally prefer to make some minor style change to the formula, or queue up a test build on CI, rather than force a revision for everyone.

**Comment by apjanke** [comment]
Merged regardless to avoid doing another two hour build on the CI.

**Pull request closed without merging**
