### PR TITLE
dependency-check 7.3.0

### PR DESCRIPTION
**Pull request by jeremylong**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]
Thanks @jeremylong  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Review by SMillerDev — APPROVED** [review]

**Comment by jeremylong** [comment]
@SMillerDev thanks for the fast approval - sorry about the test failures. The NVD implemented rate limiting a while back and homebrew kicking off multiple updates causes the rate limiting to kick in. We switched to a more stable mirror for this test so we shouldn't see the rate limiting issue in the future.

**Comment by SMillerDev** [comment]
That's fine, all tests fail sometimes. While I have you here, do you have any influence on https://github.com/OWASP/www-project-dependency-check/pull/2 ?

**Comment by jeremylong** [comment]
@SMillerDev sorry about missing the PR on that repo. I've merged the update.

**Pull request closed without merging**
