### PR TITLE
ki18n 5.111.0

### PR DESCRIPTION
**Pull request by osalbahr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
Note: `brew bump --open-pr` couldn't correctly construct the new url:
```
$ brew bump --open-pr ki18n
==> ki18n
Current formula version:  5.110.0
Latest livecheck version: 5.111.0
Latest Repology version:  5.111.0
Open pull requests:       none
Closed pull requests:     none
==> Downloading https://download.kde.org/stable/frameworks/5.110/ki18n-5.111.0.tar.xz
curl: (22) The requested URL returned error: 404                                                                                                                                                           

Error: Failed to download resource "ki18n"
Download failed: https://download.kde.org/stable/frameworks/5.110/ki18n-5.111.0.tar.xz
                                                        here ---^
```

(I made this PR with `brew bump-formula-pr ki18n --version 5.111.0 --url https://download.kde.org/stable/frameworks/5.111/ki18n-5.111.0.tar.xz`)

**Comment by osalbahr** [comment]
Could you re-trigger the CI? I want to see if the same error happens in the Linux CI.

**Comment by chenrui333** [comment]
rerun

**Comment by p-linnane** [comment]
This is part of a set of packages that need to be updated together. I've got this working in #151842.

**Pull request closed without merging**
