### PR TITLE
llvm 13.0.1

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Killing CI for now until the queue clears up.

**Comment by carlocab** [comment]
Needs the self-hosted runner on Linux.

**Comment by carlocab** [comment]
Fixing LDC failure on Catalina in #94469.

**Comment by carlocab** [comment]
Audit failures on Intel Big Sur:
```
Error: 2 failed steps!
brew audit llvm --online --git --skip-style
brew audit ccls --online --git --skip-style
```
And the audit failures are:
```
  Error: GitHub API Error: Bad credentials
  HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
    https://github.com/settings/tokens
```

**Comment by carlocab** [comment]
I think this should be ready to merge.

The only real failure should be fixed by #94469. We didn't test dependents on Intel Big Sur, but dependent testing ran fine (other than `ldc` on Catalina) everywhere else.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
