### PR TITLE
ex-vi: update formula desc

### PR DESCRIPTION
**Pull request by Nathan2055**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is an incredibly minor change; it just corrects "tradition vi" to "traditional vi" in the formula description.

### CODE REVIEW

**Comment by chenrui333** [comment]
@Nathan2055, thanks for the PR, can you amend your commit msg as the PR title?

**Comment by Nathan2055** [comment]
@chenrui333 No problem, give me 60 seconds...

**Comment by Nathan2055** [comment]
@chenrui333 All right, let me know if that looks good.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@Nathan2055 thanks for your first contribution to homebrew-core! 💯

**Pull request merged**
