### PR TITLE
leptonica 1.74.1

### PR DESCRIPTION
**Pull request by Schultzer**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
The `brew test` seems to be failing due to a version number mismatch: https://bot.brew.sh/job/Homebrew%20Core/14064/version=sierra/testReport/junit/brew-test-bot/sierra/test_leptonica/

**Comment by Schultzer** [comment]
@MikeMcQuaid Is this a problem with the current version of leptonica or homebrew?

**Comment by MikeMcQuaid** [comment]
It's a problem with the change of version in this PR.

**Comment by Schultzer** [comment]
@MikeMcQuaid Thanks for pointing out the problem the `brew test` should be resolved now. 🚀

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
