### PR TITLE
Mill 0.1.4 (new formula)

### PR DESCRIPTION
**Pull request by benjaminfrank**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by benjaminfrank** [comment]
SIerra build fails but I do not understand what the issue is. Any help is appreciated

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by benjaminfrank** [comment]
bumped to version 0.1.4

**Comment by fxcoudert** [comment]
Thanks @benjaminfrank for the pull request!

**Pull request merged**
