### PR TITLE
mosquitto: Add a cjson build dependency to get mosquitto_ctrl built

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you make sure the test catches this?

**Comment by therealprof** [comment]
Any pointers how to do that? Do you want me to add checks for the other binaries, too?

**Comment by SMillerDev** [comment]
> Any pointers how to do that? Do you want me to add checks for the other binaries, too?

Below is the standard explanation for tests, if you can make a good test for all binaries that would be a massive improvement for the formula and much appreciated.

---

We need a test that exercises the some of the functionality of the app. Version checks or usage checks (foo --version or foo --help) are not sufficient, as explained in the formula cookbook.

In most cases, a good test would involve running a simple test case: run #{bin}/foo input.txt.

- Then you can check that the output is as expected (with assert_equal or assert_match on the output of shell_output)
- You can also check that an output file was created, if that is expected: assert_predicate testpath/"output.txt", :exist?

Some advice for specific cases:

- If the formula is a library, compile and run some simple code that links against it. It could be taken from upstream's documentation / source examples.
- If the formula is for a GUI program, try to find some function that runs as command-line only, like a format conversion, reading or displaying a config file, etc.
- If the software cannot function without credentials, a test could be to try to connect with invalid credentials (or without credentials) and confirm that it fails as expected.
- Same if the software requires a virtual machine, docker instance, etc. to be running.

**Comment by therealprof** [comment]
> We need a test that exercises the some of the functionality of the app. Version checks or usage checks (foo --version or foo --help) are not sufficient, as explained in the formula cookbook.

Coincidentally that seems to be the only test that exists at the moment. 😅

I do find it hard to come up with actual integrations tests (since the binaries don't do much on their own with, a proper test setup would be quite a project).

I don't have time to setup to develop a complex test setup to test it according to the rules; if tests for the existence of all expected binaries are okay, I'd be happy to add those.

**Comment by SMillerDev** [comment]
> I do find it hard to come up with actual integrations tests (since the binaries don't do much on their own with, a proper test setup would be quite a project).

Is there any way you could call the binaries without the proper setup and trigger a situation similar to: 
> If the software cannot function without credentials, a test could be to try to connect with invalid credentials (or without credentials) and confirm that it fails as expected.

**Comment by therealprof** [comment]
> > I do find it hard to come up with actual integrations tests (since the binaries don't do much on their own with, a proper test setup would be quite a project).
> 
> Is there any way you could call the binaries without the proper setup and trigger a situation similar to:
> 
> > If the software cannot function without credentials, a test could be to try to connect with invalid credentials (or without credentials) and confirm that it fails as expected.

That'd be possible for some/the client binaries. For the server that's a no-go...

```
# mosquitto_pub -L mqtt://127.0.0.1/topic -n
Error: Connection refused
# echo $?
1
```

**Comment by SMillerDev** [comment]
> That'd be possible for some/the client binaries. For the server that's a no-go...

That sounds like progress already, maybe we skip the server for now and just improve the client tests. That way we know that your change works and you won't spend too much of your time fixing the formula.

**Comment by therealprof** [comment]
This is proving way harder than expected. Almost any easily creatable error uses the return code 1 which is the same as the shell "command not found"...

**Comment by therealprof** [comment]
At least there's a test for the successful implementation of this change (i.e. `mosquitto_ctrl`exists and can be executed) and another one for `mosquitto_passwd`.

**Comment by SMillerDev** [comment]
You can do this.
```
assert_match "something", shell_output("#{bin}/command", 1)
```

**Comment by therealprof** [comment]
Okay, I still don't want to sink a large amount of time into such a simple PR since it's a very scarse resource a the moment. I've added the test that the PR does what it says on the tin and a bonus one for good measure.

**Review by SMillerDev — APPROVED** [review]
Thanks @therealprof  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
