### PR TITLE
percona-server 5.7.23-25

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Fails on majove with
```
Can't locate loadable object for module Fcntl in @INC
```
Same error as #34349. 🤔

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @igas !

**Pull request closed without merging**
