### PR TITLE
fluid-synth: add HEAD

### PR DESCRIPTION
**Pull request by ColinKinloch**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Adding HEAD as carla seems like it's going to be blocking #32986 for a while.

### CODE REVIEW

**Comment by ColinKinloch** [comment]
I think that mpd test has a problem: https://github.com/Homebrew/homebrew-core/pull/34182#issuecomment-439492305

**Comment by ColinKinloch** [comment]
@BrewTestBot test this please

**Comment by ColinKinloch** [comment]
No, it can output via sdl2 when used as a library.

**Comment by fxcoudert** [comment]
Given that's it's used as dependency for other projects, and SDL2 is rather heavy, I'd prefer not to include it if it's optional.

**Comment by fxcoudert** [comment]
Thanks @ColinKinloch

**Pull request closed without merging**
