### PR TITLE
use secure Git access with savannah.gnu.org repos

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
Let's go ahead and merge #10825, #10826, and #10827 into this PR (unless there's a reason not to that I'm not aware of).

**Comment by vszakats** [comment]
@woodruffw My last known instruction from maintainers was to always groups such changes into smaller PRs to avoid exhausting the CI sessions. That's what I'm doing since then. Are you saying that this is not undesired and one can pack in any number of changes inside a single PR? [I'd be happy about it, but not necessarily in context of the already submitted PRs :) ]

**Comment by woodruffw** [comment]
If another maintainer said to split it up, that's fine. Thanks for clarifying :smile:

**Comment by ilovezfs** [comment]
It would be good to have an audit check for these.

**Comment by ilovezfs** [comment]
Thanks @vszakats

**Comment by vszakats** [comment]
@ilovezfs Thank you. (A `brew audit --strict --online` was done for all of them, in every PR.)

**Comment by ilovezfs** [comment]
@vszakats right. I mean that it doesn't catch these.

**Comment by vszakats** [comment]
Ah okay, I definitely agree. Though these (or at least `svn.code.sf.net`) were special cases, so there didn't seem to be an obvious way to do it. It also seems non-trivial to recommend the correct replacement URL.

**Comment by ilovezfs** [comment]
It seems safe to say http://git.savannah.gnu.org is never OK now though right?

**Comment by vszakats** [comment]
These are never OK:
```
(http|git)://git.(savannah|sv).gnu.org/
(http|git)://git.(savannah|sv).gnu.org/
http://hg.(savannah|sv).gnu.org/
(http|svn)://svn.code.sf.net/
(http|git)://git.code.sf.net/
(http|git)://*.git.sourceforge.net/gitroot/
http://(download|download-mirror).savannah.gnu.org/
```

**Pull request merged**
