### PR TITLE
ruby 2.6.0

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
```
==> /usr/local/Cellar/haste-client/0.2.3_5/bin/haste
failure uploading: <!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<title>Application Error</title>
<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
</head>
<body>
<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
</body>
</html>
Error: haste-client: failed
```

Test failure of `haste-client` is likely due to their server error. 🙃

Due to Homebrew/brew#5391, we are probably not able to merge this as-is. @fxcoudert any opinions?

**Comment by fxcoudert** [comment]
No idea. You need to build haste locally and figure out what is wrong with it, because the test error is not very explicit.

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
Back to green after another retry. 😅

**Pull request closed without merging**
