### PR TITLE
elm 0.19.0

### PR DESCRIPTION
**Pull request by pfitz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by optikfluffel** [comment]
@pfitz I'm getting `494df33724224307d6e2b4d0b342448cc927901483384ee4f8cfee2cb38e993c` when running `shasum -a 256` on the downloaded archive. It seems Jenkins agrees with that. 😁

**Comment by pfitz** [comment]
@optikfluffel 

You are absolutely right. My os did unarchived the tar.gz and I did a Sha256 on the unarchived tar which was inside. Will fix it tomorrow!

**Comment by robsonpeixoto** [comment]
Already exists a compiled binary: https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-mac.tar.gz

**Comment by Tuxified** [comment]
Kudos for making a PR so short after the release, but like @robsonpeixoto mentioned, some things might be improved: the extras like elm-reactor, elm-package etc seem to be combined into one binary. This PR also doesn't address new versions of those extras? The test will also need a change as the Elm package (elm-lang/html) has moved/been renamed to elm/html.

**Comment by robsonpeixoto** [comment]
The `elm` command combine all extras:

```
> elm
Hi, thank you for trying out Elm 0.19.0. I hope you like it!

-------------------------------------------------------------------------------
I highly recommend working through <https://guide.elm-lang.org> to get started.
It teaches many important concepts, including how to use `elm` in the terminal.
-------------------------------------------------------------------------------

The most common commands are:

    elm repl
        Open up an interactive programming session. Type in Elm expressions like
        (2 + 2) or (String.length "test") and see if they equal four!

    elm init
        Start an Elm project. It creates a starter elm.json file and provides a
        link explaining what to do from there.

    elm reactor
        Compile code with a click. It opens a file viewer in your browser, and
        when you click on an Elm file, it compiles and you see the result.

There are a bunch of other commands as well though. Here is a full list:

    elm repl    --help
    elm init    --help
    elm reactor --help
    elm make    --help
    elm install --help
    elm bump    --help
    elm diff    --help
    elm publish --help

Adding the --help flag gives a bunch of additional details about each one.

Be sure to ask on the Elm slack if you run into trouble! Folks are friendly and
happy to help out. They hang out there because it is fun, so be kind to get the
best results!
```

**Comment by DomT4** [comment]
> Already exists a compiled binary:

Homebrew builds things from source & provides its own binary packages _(bottles)_ to users.

**Comment by DomT4** [comment]
Re https://github.com/elm/compiler/issues/1695 can we change the `ghc@8.0` dependency here to at least `ghc@8.2` or is that still problematic?

**Comment by commitay** [comment]
Builds okay with 8.2, 8.4 goes 💥

**Comment by DomT4** [comment]
8.2 is at least progress. 👍 to shipping this with 8.2 & removing the 8.0 formula.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/7d32c6af5517c8c22692a93fbaa05cea88345882. Thank you for your contribution to Homebrew @pfitz; we appreciate it! :smiley_cat:

**Comment by pfitz** [comment]
My pleasure :)!

**Pull request closed without merging**
