### PR TITLE
infer 0.17.0

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Let's see if this turns out to be another dumpster fire or not.

There are several key differences between the way this is built. Changes just had to be made as it was clear from countless previous attempts (#35980, #39190, #40039, #42965) that the way it was previously built was not suitable for Homebrew, prone to break and left us stuck with it being in an unmaintainable state, with considerations for removal. The lack of even a Mojave bottle further shows this. I consider this a last attempt to recover it from that.

I'm detailing the changes I've made in an effort to encourage discussion. I'd appreciate if people could share their thoughts on them.

## OCaml toolchain

This is now compiled using Homebrew's OCaml toolchain.

A recurring and unresolved issue in previous attempts was how to build the OCaml toolchain in a way that works in Homebrew. In particular, adding the `--disable-graph-lib` flag, which is needed to avoid an X11 dependency. Previously this was done using `inreplace` hacks. This method no longer works and previous attempts tried and failed to find a suitable alternative. It is clear that the system to download and build an OCaml toolchain through opam is not designed for this use case.

Instead, I've opted to make it use Homebrew's build of it. It is a build that is tested and is known to work, and is something that is going to cause a lot less headaches. It also means a reduction in Infer's build time since it doesn't need to build _another_ copy of OCaml's toolchain.

It does however cause some slight issues with it being mismatched with what Infer was designed to support. Notably I had to force update some dependencies (which are installed in opam - more on that later) for them to work with OCaml 4.08.1 (this is done in a fairly non-hacky way without any `inreplace` using opam's version pinning system). It does mean that if OCaml receives an update in Homebrew that it _may_ require some more dependencies to be updated if there were breakages. In some sense however, it's not too dissimilar to when Clang updates (or even Python - see the 3.8 PR). That can also break some things and we need to fix them.

Another option is having Homebrew have versioned formulae for OCaml like ocaml@4.07. Note however that older versions of OCaml are not supported.

If the original scenario used previously is really desired, it could be reintroduced when Infer is updated to use OCaml 4.09, which splits off the graph lib. We'd then have to hope that one of the "standard" builds for OCaml works for Homebrew and that we never need to add in our own options.

I might have broken one of the OCaml ten commandments or something by using the system toolchain, so I appreciate thoughts on this approach.

There is one runtime difference - the previous compiler built by Infer was built using the `flambda` option. Homebrew's OCaml does not currently build with that option. The option increases compile time but improves runtime performance. I'd like to ask the question of whether we should enable that option in Homebrew's OCaml build.

## Release builds

Perhaps nothing much to discuss here but I got rid of the terrible hack to enable release builds.

Instead I've made it do it properly - by creating a `.release` file which the build system reads and recognises that it should be built in release mode.

## Java

Java 10+ is currently not supported due to an upstream problem with one of Infer's dependencies: antoinemine/apron#21. As such, I've mandated use of Java 8.

I'd really like to avoid this. If others agree, I may create a patch to fix the problem myself, submit it upstream and use it for Homebrew (unless merged quickly and released). We can then install and patch that dependency ourselves before invoking the Infer build script.

That said, I have not created such a patch yet so I have not experimented to see if there are further problems down the line. I do not know what the official stance is on Java support by Infer.

## Homebrew's sandbox

The build didn't even work before under Homebrew's sandbox, which has been enabled by default for a while now. I've fixed that now.

## Homebrew dependencies

I've added 3 dependencies required for it to run. These are required as far as I know. Notably sqlite was missing. Infer's test didn't even pass before because it crashed immediately under certain scenarios due to it not finding the sqlite library.

## Infer dependencies via opam

This isn't a change but is linked to what I said earlier about us force updating certain dependencies.

All of Infer's dependencies are installed via opam. This follows a similar approach as we are taking to cargo. It uses a `--locked` flag so that the builds are more stable.

We could alternatively bring it all into Homebrew's handling, either again through opam but invoked by us (still version pinned), or we can download them via resources and get opam to install them from disk rather than downloading them itself. I do want to note however that if we go the resources route, that would be a few hundred lines added to the formula file. I think the current approach is ok but I just wanted to cover everything.

### CODE REVIEW

**Comment by Amar1729** [comment]
Woah, good work on this - I could never figure out some of these more intricate changes. Looks much cleaner than previous iterations used to be.

**Comment by fxcoudert** [comment]
Sterling work, @Bo98!

**Comment by Bo98** [comment]
Thanks!

Any thoughts on this?

> There is one runtime difference - the previous compiler built by Infer was built using the flambda option. Homebrew's OCaml does not currently build with that option. The option increases compile time but improves runtime performance. I'd like to ask the question of whether we should enable that option in Homebrew's OCaml build.

Not particularly important but I just wondered what people's thoughts were on that.

**Comment by fxcoudert** [comment]
@Bo98 no idea, really

**Comment by Bo98** [comment]
Well if someone thinks it matters they can open a pull request.

**Comment by jvillard** [comment]
Thanks a lot @Bo98 for this huge overhaul of infer's formula! Glad to see infer back in Homebrew core :tada: 

Thanks @Amar1729 for having provided a tap in the meantime :heart:

**Comment by jvillard** [comment]
The flambda switch makes infer about 20% faster in the analysis phase (after compilation of the project under analysis). It's not a big deal if it's turned off. It may make more sense to just wait for flambda to be enabled by default in the OCaml compiler than enabling flambda on Homebrew's end.

**Pull request closed without merging**
