### PR TITLE
ktmpl: fix typo in formula (found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by carlocab** [comment]
`ktmpl` has been failing CI because of the test for a few weeks now. If this fixes that I may shoot myself.

**Comment by stweil** [comment]
A local `brew install --build-from-source ktmpl` works, and `brew test ktmpl` passes. `brew audit --strict ktmpl` failed to build required software (`nokogiri`), so I could not run that. Please review.

**Comment by stweil** [comment]
> If this fixes that I may shoot myself.

Please don't. 😃

**Comment by carlocab** [comment]
No, I think you're fine. The audit failure sounds more like an issue with your local Ruby rather than the formula itself.

Brb, going to find a rope. Just remembered there are no guns here.

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
Oh, and thanks, @stweil! I forgive you for breaking `luajit`.

**Pull request closed without merging**
