### PR TITLE
Go 1.13.1

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Review by daniel-munoz — APPROVED** [review]
LGTM

**Comment by SteelPhase** [comment]
pfft go 1.13.2 will be out before this merges

**Comment by gclove** [comment]
Why does this ci take several days?

**Comment by SMillerDev** [comment]
Because there were issues with it that people are trying to resolve.

**Comment by SteelPhase** [comment]
Is there some discussion going somewhere discussing these issues. So I and others can get an idea of what's going on?

**Comment by SMillerDev** [comment]
Not really no, I just checked jenkins.brew.sh to find out the issues so far and send a message to some other maintainers.

**Comment by fxcoudert** [comment]
We're migrating our CI infrastructure, and adding Catalina support. We had a few rough days.

@BrewTestBot test this please

**Pull request closed without merging**
