### PR TITLE
go 1.14.7

### PR DESCRIPTION
**Pull request by jnozsc**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by jnozsc** [comment]
test failure on macOS 10.15
```
Error: 10 failed steps!
brew install --build-from-source berglas
brew install --build-from-source charm
brew install --build-from-source cig
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew install --build-from-source ship
brew install --build-from-source tektoncd-cli
brew install --build-from-source the_platinum_searcher
brew install --build-from-source wellington
brew install --build-from-source wskdeploy
```

test failure on macOS 10.14
```
Error: 11 failed steps!
brew install --build-from-source berglas
brew install --build-from-source charm
brew install --build-from-source cig
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew install --build-from-source grv
brew install --build-from-source ship
brew install --build-from-source tektoncd-cli
brew install --build-from-source the_platinum_searcher
brew install --build-from-source wellington
brew install --build-from-source wskdeploy
```

test failure on macOS 10.13
```
Error: 10 failed steps!
brew install --build-from-source berglas
brew install --build-from-source charm
brew install --build-from-source cig
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew install --build-from-source ship
brew install --build-from-source tektoncd-cli
brew install --build-from-source the_platinum_searcher
brew install --build-from-source wellington
brew install --build-from-source wskdeploy
```

These 3 
```
charm
dashing
wellington
```
are covered in https://github.com/Homebrew/homebrew-core/issues/56539

new issues
```
berglas
cig
grv (10.14 only)
ship
tektoncd-cli
the_platinum_searcher
wskdeploy
```

**Comment by jnozsc** [comment]
do I still need to bump the revision in `Formula/godep.rb` ?  The formula has been marked as `deprecate!` from https://github.com/Homebrew/homebrew-core/pull/58115

**Comment by chenrui333** [comment]
@jnozsc, another thing I just realized is if you checked the previous PRs, we should have two separate commits:
- one for go, `go 1.14.7`
- one for dep, `godep: revision bump for go`

But we can totally do it after fixing the stuff that we can fix.

**Comment by jnozsc** [comment]
@chenrui333 
thanks.

That's exactly what I am still confused. in previous PR https://github.com/Homebrew/homebrew-core/pull/58115 , `godep` had been marked as ` deprecate!` , do we still need to maintain it?

**Comment by SMillerDev** [comment]
> That's exactly what I am still confused. in previous PR #58115 , `godep` had been marked as ` deprecate!` , do we still need to maintain it?

It's just deprecated. It isn't removed so people can and will still install it. And that install should be working correctly

**Comment by jnozsc** [comment]
ok, thanks for clarifying this

**Comment by chenrui333** [comment]
cancelled the build for now, and we can have a final run after fixing the stuff that we can fix.

**Comment by jnozsc** [comment]
rebase from `master`.  let's check whether these issues get fixed or not

**Comment by chenrui333** [comment]
I am also inclined to do the merge and rebase to fix each formula (it is little bit costly to have golang runs)

**Comment by jnozsc** [comment]
the test on 10.15 takes too much time, let's focus on 10.14 and 10.13 first

tests fail on 10.14
```
Error: 6 failed steps!
brew install --build-from-source charm
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew install --build-from-source grv
brew test --retry --verbose ssh-vault
brew install --build-from-source wellington
```

tests fails on 10.13
```
Error: 4 failed steps!
brew install --build-from-source charm
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew install --build-from-source wellington
```

the revision bump on `godep` definitely fixes some issues

what we have now

| formula  | issue | note | fix |
| ------------- | ------------- | ------------- | ------------- |
|charm| project is abandoned from upstream | | tracked in homebrew https://github.com/Homebrew/homebrew-core/issues/56539, upstream ticket https://github.com/juju/charmstore-client/issues/209 |
|dashing | test is broken ||tracked in homebrew https://github.com/Homebrew/homebrew-core/issues/56539, a workaround maybe like this https://github.com/Homebrew/homebrew-core/pull/59391 |
|grv| xcode issue | 10.14 only, was introduced since #58115, similar issue #32533 | still broken after revision bump in godep, NEED HELP|
|ssh-vault|`key new not found` error |10.14 only, this issue does not happen last time when we bump `go` to 1.14.7|a flaky test?|
|wellington|  project is abandoned from upstream||tracked in homebrew https://github.com/Homebrew/homebrew-core/issues/56539, upstream ticket https://github.com/wellington/wellington/issues/218|

**Comment by WZZ1998** [comment]
Emm... Have these formula been fixed?

**Comment by jnozsc** [comment]
the test on `10.15` is too longer than it should be, should we restart it? cc @chenrui333

**Comment by chenrui333** [comment]
> the test on `10.15` is too longer than it should be, should we restart it? cc @chenrui333

nope, unless there is something very wrong happening. We can also cross map how much time it should run before.

**Comment by jnozsc** [comment]
it took 13 hours on previous `go` PR. https://github.com/Homebrew/homebrew-core/pull/58115

**Comment by chenrui333** [comment]
Two days over the previous release is indeed too long (`1d 23h 18m 37s` vs `13h 9m 26s`), cancelled the build

**Comment by jnozsc** [comment]
update the table above by adding a `installation analytics` column.

Due to the number of installation, I would like to suggest to rebase from `master` again, leave buggy stuff with low installation on tracking with #56539, and merge this PR if no new issue gets introduced

**Comment by jnozsc** [comment]
trigger the test again by rebasing on `master`

**Comment by jnozsc** [comment]
I file a ticket for grv https://github.com/rgburke/grv/issues/107

**Review by jszczuko — APPROVED** [review]

**Review by jszczuko — APPROVED** [review]
Move to version 1.14.7
all looks good

**Comment by bayandin** [comment]
`go` 1.15 is coming: https://github.com/Homebrew/homebrew-core/pull/59486.
Probably we'll need to move 1.14 to versioned formulae, so we need this update as well.

**Comment by jnozsc** [comment]
I have acknowledge the `1.15` release, the test on 10.15 is almost done (if you check the github action log).

There should be no new issues introduced, except `grv`, which I have already submitted the upstream tickets.

For rest of these issues,  they are being tracked in https://github.com/Homebrew/homebrew-core/issues/56539 , basically most of them are pending on a upstream release

**Comment by jnozsc** [comment]
10.15
```
brew install --build-from-source charm
brew install --build-from-source prometheus
brew test --retry --verbose sync_gateway
brew test --retry --verbose termshark
brew install --build-from-source wellington
```

10.14
```
Error: 4 failed steps!
brew install --build-from-source charm
brew test --retry --verbose faas-cli
brew install --build-from-source grv
brew install --build-from-source wellington
```

10.13
```
Error: 2 failed steps!
brew install --build-from-source charm
brew install --build-from-source wellington
```

summary

| formula  | issue | note | fix |
| ------------- | ------------- | ------------- | ------------- |
|charm| project is most likely abandoned from upstream | | tracked in homebrew https://github.com/Homebrew/homebrew-core/issues/56539, upstream ticket https://github.com/juju/charmstore-client/issues/209 |
| faas-cli| never happen in previous build, build succeeded, test failed | only on 10.14| flaky test? |
|grv| build issue |only on 10.14| upstream ticket https://github.com/rgburke/grv/issues/107|
|prometheus| a network issue when yarn tried to download external resource |only on 10.15| a temporary issue?|
|sync_gateway| a flaky test on network issue during build process | only on 10.15 | homebrew issue track https://github.com/Homebrew/homebrew-core/issues/56539|
|wellington| project is most likely abandoned from upstream | | tracked in homebrew https://github.com/Homebrew/homebrew-core/issues/56539, upstream ticket https://github.com/wellington/wellington/issues/218|

I suggest a merge and handle the leftover in https://github.com/Homebrew/homebrew-core/issues/56539

**Comment by chenrui333** [comment]
Sounds good with me. Going for the merge now.

**Comment by chenrui333** [comment]
Just 🚢  it.

**Pull request closed without merging**
