### PR TITLE
Add nomad 0.5 formula

### PR DESCRIPTION
**Pull request by commarla**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Is there a compelling need for us to ship this specific version? Homebrew's goal is to provide the latest released version of software. We don't intend to carry every version…

**Comment by commarla** [comment]
There is a breaking between 0.5.6 and 0.6.x. if you're running a nomad cluster in 0.5.x and the nomad client installed with brew, you got a beautiful stacktrace and it doesn't work.

**Comment by fxcoudert** [comment]
If upstream decided to make breaking changes, they probably knew the cost to users, and people are warned to run coherent installs client/server.

I suggest maintaining a version in a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by commarla** [comment]
Ok. It works for me. We're gonna upgrade very soon to 0.6.

**Pull request closed without merging**
