### PR TITLE
flow-cli 1.0.1

### PR DESCRIPTION
**Pull request by devbugging**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
https://github.com/onflow/flow-cli/blob/v1.0.1/flowkit/gateway/mocks/gateway_mock.go#L42-L43:

```go
type TestGateway struct {
	Mock                           *Gateway
```

https://github.com/onflow/flow-cli/blob/v1.0.1/flowkit/gateway/mocks/gateway_mock.go#L61-L62:

```go
func DefaultMockGateway() *TestGateway {
	m := &Gateway{}
```

This `Gateway` type is not defined in the `mocks` package. Is it supposed to be imported from the outer `gateway` package? (Even with that, the mock still doesn't look right.) Can you please double check that, @sideninja?

I could reproduce the error locally. I downloaded the source tarball and ran `make cmd/flow/flow VERSION=v1.0.1`.

**Comment by sideninja** [comment]
The gateway should be generated. Will change for it to be included. Thank you @ZhongRuoyu that helps.

**Comment by p-linnane** [comment]
Superseded by #129419

**Comment by ZhongRuoyu** [comment]
`flow` and `flow-cli` are different formulae.

**Comment by p-linnane** [comment]
Copied the wrong link. Here's the right one: https://github.com/Homebrew/homebrew-core/pull/129414

**Comment by ZhongRuoyu** [comment]
Ah, I see. 😬

**Pull request closed without merging**
