### PR TITLE
datafusion 12.0.0

### PR DESCRIPTION
**Pull request by iajoiner**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Jimexist** [comment]
looks good to me

**Comment by iajoiner** [comment]
I will close this one and reopen it using `brew bump-formula-pr`

**Comment by iajoiner** [comment]
Sorry for closing and reopening it. All tests have passed / should pass and all tasks have been complete.

**Comment by chenrui333** [comment]
@iajoiner thanks for your contribution, can you please follow the commit guidelines for your future PRs? Thanks!

**Comment by chenrui333** [comment]
Also if you want to automate the process, you can try out [this gh action](https://github.com/mislav/bump-homebrew-formula-action) as well.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
