### PR TITLE
giflib 5.1.9

### PR DESCRIPTION
**Pull request by alebcay**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Apparently it doesn't have a configure anymore

**Comment by alebcay** [comment]
Seems that author has a bone to pick with autoconf/autotools and did not bother making the Makefile cross-platform: https://sourceforge.net/p/giflib/code/merge-requests/3/.

**Comment by alebcay** [comment]
Also, ideally, the work done by the `inreplace` call would be included in the patch, but I can't, for the life of me, get it to work (the hunk keeps failing if I try to include it in the patch).

**Comment by fxcoudert** [comment]
Bug filed upstream: https://sourceforge.net/p/giflib/bugs/133/

That's too major for us to patch, I believe. Closing for now, hopefully they can fix it.

**Pull request closed without merging**
