### PR TITLE
riak 2.2.3

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

build from source

CC @randysecrist

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 isn't it beautiful?

**Comment by DomT4** [comment]
I'm not sure whether this is one of the most clever uses I've seen for a formula or one of the most hideous... or possibly both 😉. It's hideous but I feel impressed you made it work 😄.

**Comment by ilovezfs** [comment]
It was a bit less hideous with the `make rel` target, which did not involve fighting with rebar as much, but the `make rel` target doesn't result in a functional `riak version` command. That could be solved by figuring out what `make package` is doing differently, but I ran out of patience.

**Comment by DomT4** [comment]
I can't remember if this is the formula we'd been trying to convince people to rewrite from source for _literally_ years. I think it was originally built from source & then someone decided it was too much hassle to make work and the switch was made.

**Pull request closed without merging**
