### PR TITLE
fnm 1.35.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
··Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/Cellar/fnm/1.35.0/bin/fnm completions --shell bash` exited with 101. Here's the output:··

**Comment by branchvincent** [comment]
already reported: https://github.com/Schniz/fnm/issues/1006

**Comment by chenrui333** [comment]
closing for now.

**Comment by chenrui333** [comment]
relates to #136514

**Comment by chenrui333** [comment]
adopted the patch, https://github.com/Schniz/fnm/pull/1010 and it works for me.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
