### PR TITLE
octave: revision for gcc 7.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

mkoctfile hard codes the Cellar path to gcc

CC @fxcoudert @DomT4

### CODE REVIEW

**Comment by DomT4** [comment]
Wonder if it's worth adding to the test something like:

```ruby
output = shell_output("strings #{bin}/mkoctfile")
assert_match Formula["gcc"].prefix.realpath, output
```
🤷‍♂️ 😭.

**Comment by ilovezfs** [comment]
I'm sure linuxbrew will be thrilled if I use `strings`

**Comment by DomT4** [comment]
GNU has a version of `strings` doesn't it?

**Comment by ilovezfs** [comment]
Not that you can assume is installed as far as I know?

**Comment by ilovezfs** [comment]
It looks like we can do `mkoctfile -p FLIBS`
```
iMac-TMP:~ joe$ mkoctfile -p FLIBS
 -L/usr/local/Cellar/gcc/7.3.0/lib/gcc/7/gcc/x86_64-apple-darwin15.6.0/7.3.0 -L/usr/local/Cellar/gcc/7.3.0/lib/gcc/7/gcc/x86_64-apple-darwin15.6.0/7.3.0/../../.. -lgfortran -lquadmath -lm
iMac-TMP:~ joe$ 
```

**Comment by ilovezfs** [comment]
```
    output = shell_output("#{bin}/mkoctfile -p FLIBS")
    assert_match Formula["gcc"].prefix.realpath.to_s, output
```
works. (Without the `.to_s` we get `NoMethodError: undefined method `=~' for #<Pathname:/usr/local/Cellar/gcc/7.3.0>` because all things are terrible.)

**Comment by DomT4** [comment]
> Not that you can assume is installed as far as I know?

Oh, yeah, that could well be true. I tend to blast through a lengthy `apt-get` list as soon as I create a new box, so it's been a while since I've run for long with a truly bare box.

> It looks like we can do mkoctfile -p FLIBS

👍Sounds like a good way to go.

> because all things are terrible.

*Nods head in agreement*.

**Review by DomT4 — APPROVED** [review]

**Pull request closed without merging**
