### PR TITLE
htpdate 1.2.0

### PR DESCRIPTION
**Pull request by alebcay**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Failed on Sierra:

```
==> make prefix=/usr/local/Cellar/htpdate/1.2.0 STRIP=/usr/bin/strip CC=clang CFLAGS= install
clang    -o htpdate htpdate.c
htpdate.c:48:10: fatal error: 'sys/timex.h' file not found
#include <sys/timex.h>
         ^~~~~~~~~~~~~
```

We might mark it High Sierra and later.

**Comment by SMillerDev** [comment]
@alebcay got time to improve the test too?

**Comment by alebcay** [comment]
Upon closer inspection, I'm fairly certain that htpdate 1.2.0 is broken. Here is a sample query in the current version, 0.9.1:
```
• htpdate -q -d example.org
No time correction needed
```
and the same query in this version, 1.2.0:
```
• htpdate -q -d example.org
burst: 1 try: 1 when: 500000
example.org               80 28 Jun 2019 22:10:33 GMT (0.119) => -1561759834
burst: 1 try: 2 when: 500000
example.org               80 28 Jun 2019 22:10:34 GMT (0.031) => -1561759835
No server suitable for synchronization found
```

**Comment by fxcoudert** [comment]
I don't see a way to report the bug upstream (not feedback / bug database), so i'd suggest simply closing this.

**Pull request closed without merging**
