### PR TITLE
torxakis 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by harcokuppens**
Tool for Model Based Testing

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by harcokuppens** [comment]
when I did the check I got:

> $ brew audit --new-formula Formula/torxakis.rb
> torxakis:
>   * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
> Error: 1 problem in 1 formula

I didn't understand what it meaned, so I googled for it, and found 
   https://github.com/Homebrew/homebrew-core/issues/3440
where they claim that you can ignore it. 
But now I get the same error again.  
What did I do wrong?

Best regards,
Harco Kuppens

**Comment by harcokuppens** [comment]
update: I found comment in my previous PR at https://github.com/Homebrew/homebrew-core/pull/23329  where it was adviced: You may want to host this software in your own tap

I looked again at the criteria at https://docs.brew.sh/Acceptable-Formulae.html saying:
The software in question must:

    be maintained (e.g. upstream is still making new releases)
    be known
    be stable (e.g. not declared “unstable” or “beta” by upstream)
    be used
    have a homepage

the software 'torxakis' is actively developed and maintain, has a homepage, but probably doesn't fullfill the criteria "be known" because it is pretty new for industry. 

So I guess the audit saying:

> GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
> Error: 1 problem in 1 formula

is a technical way to determine it is not known??  or I'm a wrong?
If I'm right, I suppose I will advice to setup my own tap. No problem.
However I really like that the brew bot automatically makes bottles for the different macOS versions.
Can I somehow still use this feature?  

Best regards 
Harco Kuppens

**Comment by vinyldarkscratch** [comment]
Hey @harcokuppens,

About ignoring that message, what @DomT4 was saying was that we can ignore that message on existing formulae.  New formulae, however, must meet this requirement.  Thus, unfortunately, until the repository reaches 20 forks, 20 watchers, and 50 stars, this formula cannot be pulled into homebrew-core as it does not pass the audits.

> So I guess the audit [...] is a technical way to determine it is not known?

That's correct -- it's unfortunate because a lot of wonderful software is rejected due to this audit, but it also makes sense that Homebrew has to draw the line somewhere.

> However I really like that the brew bot automatically makes bottles for the different macOS versions.  Can I somehow still use this feature?

Unfortunately, the brew test bot's bottling features only apply to homebrew-core as far as I know.  I've heard of developers setting up CI systems (CircleCI and Travis CI) to provide formula bottles, however.  It might be a good idea to look into that.  🙂

**Comment by harcokuppens** [comment]
Ok, very clear, I understand that you have the draw the line somewhere.

So  I will setup my own tap.  Maybe in the future torxakis will become more popular, and if we then meet the criteria I will try again to get in the homebrew core.

`Unfortunately, the brew test bot's bottling features only apply to homebrew-core as far as I know. I've heard of developers setting up CI systems (CircleCI and Travis CI) to provide formula bottles, however. It might be a good idea to look into that. 🙂`

That would be great.

I really like homebrew, keep up the good work!

Best regards
Harco Kuppens

**Pull request closed without merging**
