### PR TITLE
cockroach 2.1.0

### PR DESCRIPTION
**Pull request by tbg**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
I've cancelled the build for this, it was stuck building for 9 hours on all nodes.

**Comment by tschottdorf** [comment]
To figure out why that is, would I run the steps in https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/32638/version=mojave/console manually? I assume you're implying that this is something I need to look at (i.e. not a CI problem).

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by glerchundi** [comment]
Waiting for this too.

**Comment by tschottdorf** [comment]
That test run isn't looking good:

```
23:53:13 ==> brew install --verbose --build-bottle cockroach
07:41:47 FATAL: command execution failed
07:41:47 java.io.IOException
07:41:47 	at hudson.remoting.Channel.close(Channel.java:1447)
07:41:47 	at hudson.remoting.Channel.close(Channel.java:1403)
07:41:47 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:821)
07:41:47 	at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:788)
07:41:47 	at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:88)
07:41:47 	at jenkins.model.Jenkins.access$2200(Jenkins.java:305)
07:41:47 	at jenkins.model.Jenkins$19.run(Jenkins.java:3394)
07:41:47 	at hudson.model.Queue._withLock(Queue.java:1380)
07:41:47 	at hudson.model.Queue.withLock(Queue.java:1257)
07:41:47 	at jenkins.model.Jenkins._cleanUpDisconnectComputers(Jenkins.java:3388)
07:41:47 	at jenkins.model.Jenkins.cleanUp(Jenkins.java:3263)
07:41:47 	at hudson.WebAppMain.contextDestroyed(WebAppMain.java:379)
07:41:47 	at org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:961)
07:41:47 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:571)
07:41:47 	at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:938)
07:41:47 	at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:381)
07:41:47 	at org.eclipse.jetty.webapp.WebAppContext.stopWebapp(WebAppContext.java:1503)
07:41:47 	at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1467)
07:41:47 	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:990)
07:41:47 	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:297)
07:41:47 	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:569)
07:41:47 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
07:41:47 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
07:41:47 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
07:41:47 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
07:41:47 	at org.eclipse.jetty.server.Server.doStop(Server.java:490)
07:41:47 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
07:41:47 	at winstone.Launcher.shutdown(Launcher.java:310)
07:41:47 	at winstone.ShutdownHook.run(ShutdownHook.java:25)
07:41:47 Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on mojave_stadium_2 failed. The channel is closing down or has closed down
```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by mholt** [comment]
OK so it's pretty clear the build doesn't work. Now what? This is how the logs end:

```
[ 86%] Building CXX object CMakeFiles/rocksdb.dir/utilities/persistent_cache/block_cache_tier.cc.o
[ 86%] Building CXX object CMakeFiles/rocksdb.dir/utilities/persistent_cache/block_cache_tier_file.cc.o
[ 89%] Building CXX object CMakeFiles/rocksdb.dir/utilities/persistent_cache/block_cache_tier_metadata.cc.o
[ 89%] Building CXX object CMakeFiles/rocksdb.dir/utilities/persistent_cache/persistent_cache_tier.cc.o
[ 89%] Building CXX object CMakeFiles/rocksdb.dir/utilities/persistent_cache/volatile_tier_impl.cc.o
[ 89%] Building CXX object CMakeFiles/rocksdb.dir/utilities/redis/redis_lists.cc.o
[ 89%] Building CXX object CMakeFiles/rocksdb.dir/utilities/simulator_cache/sim_cache.cc.o
[ 89%] Building CXX object CMakeFiles/rocksdb.dir/utilities/spatialdb/spatial_db.cc.o
[ 89%] Building CXX object CMakeFiles/rocksdb.dir/utilities/table_properties_collectors/compact_on_deletion_collector.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/optimistic_transaction_db_impl.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/optimistic_transaction.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/pessimistic_transaction.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/pessimistic_transaction_db.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/snapshot_checker.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/transaction_base.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/transaction_db_mutex_impl.cc.o
[ 93%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/transaction_lock_mgr.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/transaction_util.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/write_prepared_txn.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/write_prepared_txn_db.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/utilities/ttl/db_ttl_impl.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/utilities/write_batch_with_index/write_batch_with_index.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/utilities/write_batch_with_index/write_batch_with_index_internal.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/port/port_posix.cc.o
[100%] Building CXX object CMakeFiles/rocksdb.dir/env/env_posix.cc.o
[100%] Building CXX object CMakeFiles/rocksdb.dir/env/io_posix.cc.o
[100%] Linking CXX static library librocksdb.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(db_impl_debug.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(db_bench_tool.cc.o) has no symbols
Error: An exception occurred within a child process:
  SignalException: SIGTERM
```

@tschottdorf

**Comment by tschottdorf** [comment]
I think the SIGTERM is due to the build being aborted, but it ran for 23h so something is definitely wrong. Let me try to run this on my local machine.

**Comment by tschottdorf** [comment]
Able to repro this locally. Seems that `make` goes into an infinite loop. Essentially it prints

```
  The prerequisites of `cockroach' are being made.
 Finished prerequisites of target file `install'.
The prerequisites of `install' are being made.

**Comment by benesch** [comment]
Yikes. I'll take a look today.

It should perhaps be a release binary (via `make BUILDTYPE=release`), but we intentionally don't compile with `build/builder.sh mkrelease darwin`. Homebrew builds need to be perfectly reproducible and using `build/builder.sh` would introduce a dependency on Docker Hub. Plus Homebrew packages are supposed to use the Homebrew versions of dependencies (Go, CMake, autotools, etc.), not what we've pinned in the builder container.

**Comment by tschottdorf** [comment]
Ack, good to know. Let me know if I can help. To repro, I just downloaded the 2.1 tarball and ran the make invocation above. Let me know if that doesn't spin in a circle for you and I'll figure out what else I did.

**Comment by benesch** [comment]
This appears to be a bug in the ancient version of GNU Make that macOS ships (v3.81). I say that because things compile just fine with a more recent version of Make. I'm pretty burnt out on trying to find workarounds for these Make bugs—I've tracked at least two down already—so I'm going to propose that we simply use Homebrew's version of Make to build Cockroach. Here's the patch to do so:

```
diff --git a/Formula/cockroach.rb b/Formula/cockroach.rb
index 0b27c609a4..abe4b73693 100644
--- a/Formula/cockroach.rb
+++ b/Formula/cockroach.rb
@@ -15,11 +15,16 @@ class Cockroach < Formula
 
   depends_on "autoconf" => :build
   depends_on "cmake" => :build
+  depends_on "make" => :build
   depends_on "go" => :build
   depends_on "xz" => :build
 
   def install
-    system "make", "install", "prefix=#{prefix}"
+    # The make that ships with macOS (v3.81 at the time of writing) has a bug
+    # that causes it to loop infinitely when trying to build cockroach. Use
+    # the more up-to-date make that Homebrew provides.
+    ENV.prepend_path "PATH", Formula["make"].opt_libexec/"gnubin"
+    system "make", "install", "prefix=#{prefix}", "BUILDTYPE=release"
   end
 
   def caveats; <<~EOS
```

**Comment by tbg** [comment]
Patch was applied. Let's see if this turns green...

**Comment by benesch** [comment]
Gah! Looks like the build succeeded but I didn't sort the dependencies correctly:

```
 * C: 19: col 3: dependency "go" (line 19) should be put before dependency "make" (line 18)
```

**Comment by tbg** [comment]
Here we go.

**Comment by benesch** [comment]
Bisecting Make pointed the finger at http://git.savannah.gnu.org/cgit/make.git/commit/?id=b9f831b858761366e0db418e6f226a053ed550af, which seems more than plausible. I'm not seeing any easy way to work around that.

**Comment by tbg** [comment]
It's green! Paging @mholt.

**Comment by mholt** [comment]
Woo hoo! Nice work -- thanks guys. Who can accept the change? @fxcoudert?

**Comment by glerchundi** [comment]
@commitay @fxcoudert would love to this see this merged now it's passing, any chance to look at this? thanks!

**Comment by jjzazuet** [comment]
+1 to have this `cockroach` upgrade. Thanks!!

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by tbg** [comment]
```
17:54:19 ==> brew untap homebrew/cask
17:54:20 ==> FAILED
17:54:20 Error: Directory not empty @ dir_s_rmdir - /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
17:54:20 Untapping homebrew/cask...
17:54:23 
17:54:23 ==> git -C homebrew/homebrew-cask reset --hard origin/master
17:54:23 
17:54:23 ==> brew prune
17:54:24 Build step 'Execute shell' marked build as failure
17:54:25 Recording test results
17:54:25 Archiving artifacts
17:54:29 [WS-CLEANUP] Deleting project workspace...
17:54:29 [WS-CLEANUP] done
17:54:29 Finished: FAILURE
```

Is that a problem with the build harness or the formula?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
