### PR TITLE
kotlin-native 1.3.50 (new formula)

### PR DESCRIPTION
**Pull request by jasonwyatt**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I saw there were previously two kotlin-native PRs which didn't build from source and were closed for that reason. Here's one which does build from source! 😄

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please don't update the dependencies in the formula. This way everyone's build will be different, making it easy harder to maintain.

**Comment by jasonwyatt** [comment]
> Please don't update the dependencies in the formula. This way everyone's build will be different, making it easy harder to maintain.

That step is part of the official build instructions on https://github.com/JetBrains/kotlin-native

I'll see if it works without that step, but IIUC,  `./gradlew dependencies:update` simply downloads the dependencies outlined in the main `build.gradle` - which all have fixed versions.

**Comment by jasonwyatt** [comment]
Yeah, the build fails if I try to remove that line.

**Comment by chenrui333** [comment]
I wonder if it is possible to include those dependencies into upstream repo so that we can just simply invoke the make command to do the install step?

BTW, thanks for your contribution!!

**Pull request closed without merging**
