### PR TITLE
mariadb 10.5.10

### PR DESCRIPTION
**Pull request by el7cosmos**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
ARM node build failing due to repeatedly seen issue with macOS 11.3 (XCode 12.5) C++20 `<version>` header.
```make
In file included from /tmp/mariadb-20210508-62434-1gxtvnw/mariadb-10.5.10/storage/maria/ha_maria.cc:24:
In file included from /tmp/mariadb-20210508-62434-1gxtvnw/mariadb-10.5.10/include/my_global.h:287:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/math.h:309:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:417:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:37:
/tmp/mariadb-20210508-62434-1gxtvnw/mariadb-10.5.10/storage/maria/libmarias3/version:1:1: error: expected unqualified-id
3.1.2
^
```

The VERSION file from https://github.com/mariadb-corporation/libmarias3 (included in tar at `storage/maria/libmarias3/VERSION`) is causing current issue.

**Comment by SMillerDev** [comment]
That should be reported to mariadb.

**Comment by Bo98** [comment]
https://github.com/MariaDB/server/commit/e788738e18bd5cedb21f75b21f902f1bbcc34719.patch?full_index=1

Same commit applies to all MariaDB versions.

**Comment by cho-m** [comment]
@carlocab I think the linked issue is already closed/fixed in 10.5.10. 
It shows up among tagged releases: https://github.com/MariaDB/server/commit/e788738e18bd5cedb21f75b21f902f1bbcc34719

This issue seems to happen while compiling submodule.

---

CMake include: https://github.com/MariaDB/server/blob/mariadb-10.5.10/storage/maria/CMakeLists.txt#L133
>   INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/libmarias3)

Submodule VERSION file: https://github.com/mariadb-corporation/libmarias3/blob/0d48bf334fde7d4e0dac22bda560e86037d35d77/VERSION

**Comment by cho-m** [comment]
The CMake include is probably necessary to build since header is accessed like:
```c
#include <libmarias3/marias3.h>
```

CMakeLists path: `storage/maria/CMakeLists.txt`
Header file path: `storage/maria/libmarias3/libmarias3/marias3.h`

---


Sadly, this is not the only location with a `version`/`VERSION` file.
I tried manually deleting the file and end up failing at
`storage/mroonga/version:1:1: error: expected unqualified-id`

Here is a search through for any `version` file:
```console
❯ fd '^version$'
VERSION
storage/columnstore/columnstore/VERSION
storage/columnstore/columnstore/utils/libmarias3/libmarias3/VERSION
storage/maria/libmarias3/VERSION
storage/mroonga/vendor/groonga/vendor/mruby/version
storage/mroonga/vendor/groonga/vendor/plugins/groonga-normalizer-mysql/version
storage/mroonga/version
```

**Comment by cho-m** [comment]
I did get build to succeed with some manual workarounds.
Probably need to open/find upstream issue to get a proper fix.
The main build issues I saw:
1. Need to get `storage/maria/libmarias3/VERSION` out of include path. This is the failure in Homebrew's CI.
2. Need to get `storage/mroonga/version` out of include path (but is currently required during `cmake` phase)
3. Need to get top-level `VERSION` file out of include path for `mroonga`.
   File is used during `make` phase, so manually patched include.
4. Still ends up failing due to missing `<jni.h>` used by `storage/connect/javaconn.h`.
   Just added `opendjdk` as dependency, but could probably also disable part of build.
---

A hacked together formula patch provided below.

**_I don't recommend using this as is._**

Just providing info for what currently worked.

```patch
@@ -18,6 +18,7 @@ class Mariadb < Formula
   end

   depends_on "cmake" => :build
+  depends_on "openjdk" => :build
   depends_on "pkg-config" => :build
   depends_on "groonga"
   depends_on "openssl@1.1"
@@ -36,6 +37,8 @@ class Mariadb < Formula
   conflicts_with "mytop", because: "both install `mytop` binaries"
   conflicts_with "mariadb-connector-c", because: "both install `mariadb_config`"

+  patch :DATA
+
   def install
     # Set basedir and ldata so that mysql_install_db can find the server
     # without needing an explicit path to be set. This can still
@@ -73,6 +76,10 @@ class Mariadb < Formula
     args << "-DPLUGIN_ROCKSDB=NO" if Hardware::CPU.arm?

     system "cmake", ".", *std_cmake_args, *args
+
+    rm "storage/maria/libmarias3/VERSION"
+    rm "storage/mroonga/version"
+
     system "make"
     system "make", "install"

@@ -186,3 +193,19 @@ class Mariadb < Formula
     system "#{bin}/mysqladmin", "--port=#{port}", "--user=root", "--password=", "shutdown"
   end
 end
+
+__END__
+diff --git a/storage/mroonga/CMakeLists.txt b/storage/mroonga/CMakeLists.txt
+index 555ab248751..cddb6f2f2a6 100644
+--- a/storage/mroonga/CMakeLists.txt
++++ b/storage/mroonga/CMakeLists.txt
+@@ -215,8 +215,7 @@ set(MYSQL_INCLUDE_DIRS
+   "${MYSQL_REGEX_INCLUDE_DIR}"
+   "${MYSQL_RAPIDJSON_INCLUDE_DIR}"
+   "${MYSQL_LIBBINLOGEVENTS_EXPORT_DIR}"
+-  "${MYSQL_LIBBINLOGEVENTS_INCLUDE_DIR}"
+-  "${MYSQL_SOURCE_DIR}")
++  "${MYSQL_LIBBINLOGEVENTS_INCLUDE_DIR}")
+
+ if(MRN_BUNDLED)
+   set(MYSQL_PLUGIN_DIR "${INSTALL_PLUGINDIR}")
```

**Comment by freebrowser1** [comment]
I also got this error on building MariaDB v 10.5.9.
I am running macOS 10.16.3 Big Sur and Xcode 2.5 but on Intel Mac.

How can I revert to ge a working earlier version of MariaDB ?

**Pull request closed without merging**
