### PR TITLE
watchexec 1.7.0

### PR DESCRIPTION
**Pull request by mattgreen**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by vszakats** [comment]
The URL protocol was downgraded to cleartext from HTTPS. This should have been caught in the `brew audit` phase, but if this was done by `brew bump-formula-pr`, there may be a bug lurking somewhere. Issue a fix for this formula: #9701

**Comment by ilovezfs** [comment]
doesn't show up on audit or audit --strict

**Comment by vszakats** [comment]
Thank you for the info. Looks like this case wasn't covered, possibly because github.com was fairly well covered with HTTPS in the past. Made a PR for this: https://github.com/Homebrew/brew/pull/1961/files

**Comment by mattgreen** [comment]
Sorry about that, pasted and didn't check the URL. I presume we don't want to only rely on the SHA256 for integrity?

**Comment by vszakats** [comment]
Ideally, SHA256 should only be applied to a blob received from an authenticated server and with certainty that it wasn't altered in transit. These are resolved by using HTTPS. Besides that, it's also useful to hide the traffic from 3rd parties, so it's a good idea to use it if available.

**Comment by ilovezfs** [comment]
>should only be applied to a blob received from an authenticated server and with certainty that it wasn't altered in transit

why?

**Comment by vszakats** [comment]
Is this a trick question?

**Comment by ilovezfs** [comment]
If we know the checksum matches, why would we care if it came from warez4u.ru?

**Comment by vszakats** [comment]
Matches with what? Unless it matches with a hash proven to be generated by original author made before upload, we can't say for sure it's correct. Short of that, we can minimise issues while generating the hash on the receiver end, one tool for that is making sure that the server offering the file is the one we believe it is and by making the transport secure. HTTPS helps that.

**Comment by ilovezfs** [comment]
So then there's no reason for the mirror urls to be https, right?

**Comment by vszakats** [comment]
That's not the only two features of HTTPS, so no. HTTPS also makes download traffic hidden from eavesdroppers, so f.e. someone sitting next to a Homebrew user on a public WiFi wouldn't be able to tell which package that user is busy installing. For such reason it's _always_ a good practice to use HTTPS whenever available, even for mirrors, homepages, resources, tests and whatever speaks on the network.

**Comment by ilovezfs** [comment]
That's more coherent.

**Pull request closed without merging**
