### PR TITLE
sysdig 0.27.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
CMake Error at CMakeLists.txt:474 (message):
  Couldn't find system c-ares
```

**Comment by Moisan** [comment]
I tested locally and `c-ares` seems to be a build dependency, or at least the build and test works fine when using a it as a build dependency.

**Comment by alebcay** [comment]
Can you check `brew linkage sysdig` after installing it? From what I can tell, there's still linkage from `sysdig` to `c-ares`, so I would not consider it just a build dependency.

**Comment by Moisan** [comment]
```
Undeclared dependencies with linkage:
  c-ares
```
You're right, this is not just a build dependency.

**Review by Moisan — APPROVED** [review]

**Pull request closed without merging**
