### PR TITLE
perl 5.28.2

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
High Sierra failure to build `perl`:

```
Failed 1 test out of 2543, 99.96% okay.
	../cpan/DB_File/t/db-hash.t
### Since not all tests were successful, you may want to run some of
### them individually and examine any diagnostic messages they produce.
```

**Comment by chdiza** [comment]
FYI, the temporary hack in the middle of the formula to work around SIP is no longer necessary; that's been fixed according to perldelta.pod or whatever it's called.

**Comment by chdiza** [comment]
> FYI, the temporary hack in the middle of the formula to work around SIP is no longer necessary; that's been fixed according to perldelta.pod or whatever it's called.

Removing it might even also get rid of this test failure.

**Comment by SMillerDev** [comment]
@lembacon can you rebase?

**Comment by lembacon** [comment]
Well, the `perl` build failure on High Sierra somehow got fixed by itself mysteriously again…

Merging. 🤗

**Comment by lembacon** [comment]
(Probably that's @SMillerDev's poke which does the trick. 🤣)

**Pull request closed without merging**
