### PR TITLE
sloc 0.3.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
I have reported the test failure in https://github.com/flosse/sloc/issues/137

**Comment by domengasperlin** [comment]
Actually related to regression in cli option `csv` https://github.com/flosse/sloc/pull/144

**Comment by chenrui333** [comment]
> @chenrui333 related to regression in cli option format `csv` [flosse/sloc#144](https://github.com/flosse/sloc/pull/144)

cool, let me try the patch. Thanks!

**Comment by chenrui333** [comment]
> > @chenrui333 related to regression in cli option format `csv` [flosse/sloc#144](https://github.com/flosse/sloc/pull/144)
> 
> cool, let me try the patch. Thanks!

the patch cannot be applied cleanly, we need a release to be able to test the new change.

**Comment by chenrui333** [comment]
need a new release for the upstream change, closing this PR for now.

**Pull request closed without merging**
