### PR TITLE
node 19.0.1

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~ The bundled NPM version did not change.

### CODE REVIEW

**Comment by carlocab** [comment]
All CI nodes:
```
Error: 2 failed steps!
brew test --retry --verbose autorest
brew test --retry --verbose cdktf
```
`autorest` and `cdktf` probably need older versions of Node.

**Comment by cho-m** [comment]
> `autorest` and `cdktf` probably need older versions of Node.

We may want a `node@18` formula since it will be maintained until 2025 and use it as dependency for those.

Also may want to remove `node@10` before 1 year to match our max versions policy (currently at max of 5 -- v10, v12, v14, v16, unversioned). `node@10` has been disabled for a little under 3mo but has been officially EOL since Apr 2021.

**Comment by carlocab** [comment]
> We may want a `node@18` formula since it will be maintained until 2025 and use it as dependency for those.

Fine with this. Could add it in a separate PR.

> Also may want to remove `node@10` before 1 year to match our max versions policy (currently at max of 5 -- v10, v12, v14, v16, unversioned). `node@10` has been disabled for a little under 3mo but has been officially EOL since Apr 2021.

👍

**Comment by SMillerDev** [comment]
Actually, 12 should be disabled too: https://github.com/nodejs/release#end-of-life-releases and 14 should be disabled for "2023-04-30". I'll make a PR.

**Comment by derrabus** [comment]
I've added a `node@18` formula to the PR and switched those two packages to that new formula.

**Comment by SMillerDev** [comment]
There's a PR for that here already: https://github.com/Homebrew/homebrew-core/pull/113826

**Comment by derrabus** [comment]
Okay, let's wait for that PR to be merged and I'll rebase this one as soon as that happened.

**Comment by derrabus** [comment]
Can we please merge #113826, so we can continue here?

**Comment by bcomnes** [comment]
Should be unblocked now that https://github.com/Homebrew/homebrew-core/pull/113826 is in!

**Comment by derrabus** [comment]
I've rebased the PR. 🤞🏻

**Comment by derrabus** [comment]
Can someone please start the CI on this PR?

**Comment by miccal** [comment]
FYI:
```
|-> brew livecheck node
node: 18.11.0 ==> 19.0.1
```

**Comment by derrabus** [comment]
I've bumped this PR to 19.0.1

**Comment by derrabus** [comment]
Can we please run the CI? The formula builds fine on my machine and I'd like to know if there's anything left to do for me here.

**Comment by Porkepix** [comment]
> Can we please run the CI? The formula builds fine on my machine and I'd like to know if there's anything left to do for me here.

It's a long build, so it needs this tag to run: https://github.com/Homebrew/homebrew-core/issues?q=is%3Aopen+label%3ACI-long-timeout+sort%3Aupdated-desc a maintainer have to rerun with it. But it's limited at two maximum at a time, and two are already running, as well as many more (including that one) waiting to get long build slots: https://github.com/Homebrew/homebrew-core/issues?q=is%3Aopen+label%3A%22long+build%22+sort%3Aupdated-desc

**Comment by derrabus** [comment]
> It's a long build, so it needs this tag to run:

Yeah, I know. That's what I'm asking for.

> two are already running, as well as many more (including that one) waiting to get long build slots:

Sure, no pressure. It's just this PR is waiting for > 5 days and I can't really tell if there's just that many PRs ahead of this one of if this PR has simply been forgotten.

**Review by SMillerDev — DISMISSED** [review]

**Comment by derrabus** [comment]
Failure:

```
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:cfdfee3ff9db24a542cd8afd72cd05e67dffd88105b6af3bb1aabd9d48811dd2?se=2022-11-07T05%3A55%3A00Z&sig=paUiowmw8wx7RaFfRE3EbW0U2r3iVWE9Q0mCjqGzrys%3D&sp=r&spr=https&sr=b&sv=2019-12-12
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: joplin-cli: Failed to download resource "docbook-xsl"
Download failed: https://ghcr.io/v2/homebrew/core/docbook-xsl/blobs/sha256:cfdfee3ff9db24a542cd8afd72cd05e67dffd88105b6af3bb1aabd9d48811dd2
```

This looks unrelated to the node version bump.

**Comment by derrabus** [comment]
Thank you, @SMillerDev!

**Pull request closed without merging**
