### PR TITLE
JHipster 4.6.0

### PR DESCRIPTION
**Pull request by jdubois**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@jdubois please squash this down to 1 commit. Thanks!

**Comment by jdubois** [comment]
Sorry I messed up, managing to squash it from 3 to 5 commits :-)
Must have an issue with GitUp

**Comment by ilovezfs** [comment]
@jdubois OK I fixed it.

git fetch --all
git reset --hard @{u}

**Comment by ilovezfs** [comment]
Thanks for the upgrade @jdubois!

**Comment by jdubois** [comment]
OK thanks!

**Pull request closed without merging**
