### PR TITLE
rocksdb 5.17.2

### PR DESCRIPTION
**Pull request by DennisOSRM**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
@DennisOSRM Yes, add a `revision` line or if one exists increase the number by at least 1 in the `osquery` formula.

**Comment by javian** [comment]
The remaining error stems from
```
01:25:06 Resource: bcel
01:25:06 ==> Downloading https://www.apache.org/dyn/closer.cgi?path=commons/bcel/binaries/bcel-6.2-bin.tar.gz
01:25:06 ==> Downloading from http://apache.mirrors.tds.net/commons/bcel/binaries/bcel-6.2-bin.tar.gz
01:25:06 curl: (22) The requested URL returned error: 404 Not Found
```
which has been corrected in #36493 so we need to wait for that to merge before rerunning the ci on this.

**Comment by fxcoudert** [comment]
```
Undefined symbols for architecture x86_64:
  "operator delete(void*, std::align_val_t)", referenced from:
      rocksdb::LRUCacheShard::~LRUCacheShard() in lru_cache.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [librocksdb.5.17.2.dylib] Error 1
```

**Comment by DennisOSRM** [comment]
The latest revision seems to build fine, yet it fails for the dependent osquery package:

```
23:58:39 SHA256: 8cd1c5d78f8731f935f38b15c95ab714c3ef9c1c2268239743e406230fd73d0e
23:58:39 ==> Downloading https://homebrew.bintray.com/bottles/rocksdb-5.17.2.sierra.bottle.tar.gz
23:58:39 curl: (22) The requested URL returned error: 404 Not Found
23:58:39 ==> Retrying download
23:58:39 ==> Downloading https://homebrew.bintray.com/bottles/rocksdb-5.17.2.sierra.bottle.tar.gz
23:58:39 curl: (22) The requested URL returned error: 404 Not Found
23:58:39 Error: Failed to download resource "rocksdb"
23:58:39 Download failed: https://homebrew.bintray.com/bottles/rocksdb-5.17.2.sierra.bottle.tar.gz
```

**Comment by javian** [comment]
I'm not sure why it happends but perhaps removing the bottle block in rocksdb would prevent it from downloading the non-exisiting bottle and build it as expected.

**Comment by DennisOSRM** [comment]
@fxcoudert @javian Any ideas on how to fix this issue?

**Comment by DennisOSRM** [comment]
friendly ping

**Comment by javian** [comment]
@brewtestbot test this please

**Comment by DennisOSRM** [comment]
closing here in favor of #37127 which passes CI checks and brings in a newer version of rocksdb

**Pull request closed without merging**
