### PR TITLE
gpgme: add Qt bindings

### PR DESCRIPTION
**Pull request by sl1pkn07**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/homebrew-core/issues/39173

### CODE REVIEW

**Comment by fxcoudert** [comment]
I don't think we should do that. We have a lot of users who are happily using gpgme without the Qt interface, and we shouldn't force it on them.

**Comment by sl1pkn07** [comment]
and if set qt as `:build`, and have formulas that depend on Qt bindings have qt as dependencies?

> I don't think we should do that. We have a lot of users who are happily using gpgme without the Qt interface, and we shouldn't force it on them.

is the same example if i want use gpgme without python bindings, and this formula it forces me to have not one, two, python bindings files, one for python(3) and other for python(2) installed in my system

**Comment by sl1pkn07** [comment]
Hi. any update?

greetings

**Comment by fxcoudert** [comment]
It's a 👎 on building systematically with Qt dependency. If you figure out a way to build Qt bindings, but Qt is not required at runtime for all users, we would be OK with that, as long as it is a supported build configuration from upstream.

**Comment by sl1pkn07** [comment]
@fxcoudert what you mean i can't understand you point

qpgme Qt bindings not interfiere in the normal usage of gpgme, gpgme can living without Qt if the Qt bindings is builded/installed, because Qt is only used by the gpgme Qt bindings

**Comment by fxcoudert** [comment]
The current PR requires Qt at run-time, which is not acceptable.

**Comment by sl1pkn07** [comment]
i change that

https://github.com/sl1pkn07/homebrew-core/commit/08a47466163f4f7257d4ca6e46a612d09b152de5

but you closed the pull request and the changes is not updated

**Comment by fxcoudert** [comment]
I can't reopen because of the force-push, apparently. But you can open another pull request, if this is working locally for you.

**Comment by sl1pkn07** [comment]
done https://github.com/Homebrew/homebrew-core/pull/41225

**Comment by sl1pkn07** [comment]
python an python2 neither

**Pull request closed without merging**
