### PR TITLE
packer: leave build tool fetching to Makefile

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
Same comment as https://github.com/Homebrew/homebrew-core/pull/11253#issuecomment-287577823.

**Comment by cblecker** [comment]
Title and commit message updated

**Comment by dunn** [comment]
Are the dependencies pinned by upstream to a specific version? We don't want to just download the last commit on master; that was what `go_resources` were made to avoid.

**Comment by ilovezfs** [comment]
@dunn clearly not since the inreplaces are of `go get`, so closing this.

**Comment by ilovezfs** [comment]
@cblecker thanks for the PR. The `brew`-friendly solution here would be to have formulae for these deps. I attempted to get the ball rolling on that but never got a response: https://github.com/mitchellh/gox/issues/66

**Pull request closed without merging**
