### PR TITLE
terraform 0.12.13

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @diogoazevedos!!

**Comment by chenrui333** [comment]
Having some difficulty of pulling the bottle commit

```
==> Fetching patch (bottle commit)
Patch: https://github.com/BrewTestBot/homebrew-core/compare/Homebrew:master...pr-46038.patch
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing; `/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.15-95-g3944416\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15\)\ curl/7.64.1 --fail --progress-bar --location --remote-time --continue-at 0 --output /Users/ruichen/Library/Caches/Homebrew/Homebrew:master...pr-46038.patch https://github.com/BrewTestBot/homebrew-core/compare/Homebrew:master...pr-46038.patch` exited with 22. Here's the output:
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by lhaig** [comment]
Just registering a request to get this in as soon as possible please. 
Thanks for an amazing project. All OSX dev's would be lost without it

**Comment by chenrui333** [comment]
failed only in highsierra build.

```
07:53:01 go test -mod=vendor -timeout=2m -parallel=4 github.com/hashicorp/terraform/tools/terraform-bundle/e2etest github.com/hashicorp/terraform/version
07:53:01 ok  	github.com/hashicorp/terraform/tools/terraform-bundle/e2etest	3.163s
07:53:01 ?   	github.com/hashicorp/terraform/version	[no test files]
07:53:01 make: *** [test] Error 1
07:53:01 
07:53:01 ==> Formula
07:53:01 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/terraform.rb
```

going to retest now. as it did not happen earlier.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
This time, Mojave build failed.

image

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
