### PR TITLE
duck 8.0.0

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
The Linux-only `inreplace`s need updating.
```
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
cli/linux/build.xml:
  expected replacement of "<arg value=\"--license-file\"/>" with ""
```
CC @danielnachun

**Comment by carlocab** [comment]
Can someone have a look at the Linux `inreplace`? @Homebrew/linux

**Comment by danielnachun** [comment]
Sorry about the delay!  Let me try to take a look now.

**Comment by danielnachun** [comment]
@dkocher please go ahead and delete the following lines, as they are not needed now that an app-image is build by `ant`:
```
      # This changes allow maven to build the cli/linux project as an appimage instead of an RPM/DEB.
      # This has been reported upstream at https://trac.cyberduck.io/ticket/11762#ticket.
      # It has been added the version 8 milestone.
      inreplace "cli/linux/build.xml", "value=\"rpm\"", "value=\"app-image\""
      inreplace "cli/linux/build.xml", "<arg value=\"--license-file\"/>", ""
      inreplace "cli/linux/build.xml", "<arg value=\"${license}\"/>", ""
      inreplace "cli/linux/build.xml", "<arg value=\"--linux-deb-maintainer\"/>", ""
      inreplace "cli/linux/build.xml", "<arg value=\"&lt;feedback@cyberduck.io&gt;\"/>", ""
      inreplace "cli/linux/build.xml", "<arg value=\"--linux-rpm-license-type\"/>", ""
      inreplace "cli/linux/build.xml", "<arg value=\"GPL\"/>", ""
```
Thanks once again for fixing this upstream.  I promise I'll get formulae ready for Java Native Access and Java Native Foundation ready as soon as I can, and then this formula will get much smaller and simpler!

**Review by carlocab — APPROVED** [review]
Thanks, @dkocher.

**Pull request closed without merging**
