### PR TITLE
postgresql 11.1

### PR DESCRIPTION
**Pull request by fxcoudert**
Following up on #33966 (and incorporating #34774)

### CODE REVIEW

**Comment by fxcoudert** [comment]
`pldebugger` also has few installs. Could be removed, but first I am trying to patch it with these upstream commits: 
  - https://git.postgresql.org/gitweb/?p=pldebugger.git;a=commitdiff;h=19e67c8f82e32a08f99698c2486ac80c8fff1802
  - https://git.postgresql.org/gitweb/?p=pldebugger.git;a=commitdiff;h=bcf24ee2962dd8e0c87d41bc5fb6995886f30f7a
  - https://git.postgresql.org/gitweb/?p=pldebugger.git;a=commitdiff;h=fe8e2b18beb08065dea7c840442d83983688f55d
  - https://git.postgresql.org/gitweb/?p=pldebugger.git;a=commitdiff;h=2a298eb80bb1318836ce34f4ce2284c9f509a496

**Comment by fxcoudert** [comment]
`pldebugger`, even patched, does not work. Given it has 9 installs a month, I suggest that we remove it.

**Comment by fxcoudert** [comment]
No objection, so I am merging :)

**Comment by giannisp** [comment]
Great merging this, however we need postgresql@10 to be able to update db files from 10 => 11.

**Pull request closed without merging**
