### PR TITLE
ctunnel: delete

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

4 installs in the last 30 days
https://www.alienrobotarmy.com/ctunnel/0.7/ctunnel-0.7.tar.gz is 404

### CODE REVIEW

**Comment by alienrobotarmy** [comment]
URL is working again

**Comment by vinyldarkscratch** [comment]
Thanks, @alienrobotarmy!

**Comment by vinyldarkscratch** [comment]
@alienrobotarmy Thank you!  Can confirm from my end.  🙂

**Comment by ilovezfs** [comment]
Thanks @alienrobotarmy. Reverted in https://github.com/Homebrew/homebrew-core/pull/22662

**Pull request merged**
