### PR TITLE
tidy-html5: fix sha256 of the release, due to improper retagging of the release…

### PR DESCRIPTION
**Pull request by balthisar**
… on our end.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by balthisar** [comment]
This test run is failing because:

> tidy-html5:
>  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.

This PR is coming directly from the repository that the affect formula references.

The upstream issue identifying the issue is this:

https://github.com/htacg/tidy-html5/issues/974

I'm the one who allowed the re-tag to happen. It was not malicious, and was the result of attempting some integrated build solutions.

Thanks.

**Comment by carlocab** [comment]
Thanks for opening this, @balthisar. Do we need to replace our bottles (pre-built packages for each OS version), or will the ones we built from before the checksum changed suffice?

**Comment by balthisar** [comment]
@carlocab, thanks for taking a look. No bottles have to be rebuilt. Literally the only change is the checksum.

**Review by carlocab — APPROVED** [review]
Great, thanks again.

For future reference, please put the name of the formula first in your commit message, for example:
```
tidy-html5: fix checksum
```
(Or similar).

**Pull request merged**
