### PR TITLE
fastlane 2.188.0

### PR DESCRIPTION
**Pull request by joshdholtz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by joshdholtz** [comment]
Hello homebrew team 😊  This is a critical release. If this could be reviewed and merged as soon as possible that would be greatly appreciated! 

Much love from the fastlane team ❤️

**Comment by ThienMD** [comment]
please merge soon

**Comment by SMillerDev** [comment]
Pinging @carlocab for the audit.

**Comment by carlocab** [comment]
Oh right. I was meaning to reply to this then got distracted. This is installing an x86-only `terminal-notifier`:
```
==> brew audit fastlane --online --git --skip-style
==> FAILED
fastlane:
  * Binaries built for an incompatible architecture were installed into fastlane's prefix.
    The offending files are:
      /opt/homebrew/Cellar/fastlane/2.188.0/libexec/gems/terminal-notifier-2.0.0/vendor/terminal-notifier/terminal-notifier.app/Contents/MacOS/terminal-notifier
Error: 1 problem in 1 formula detected
```
Can we delete this and just do `depends_on "terminal-notifier"` instead, so we also get a native version on ARM?

**Review by carlocab — APPROVED** [review]

**Comment by joshdholtz** [comment]
@SMillerDev @carlocab Thanks for getting this merged in!

I was a little confused about this test failure. Is there anything we need to change to prevent this for new versions in the future?

**Comment by carlocab** [comment]
> I was a little confused about this test failure. Is there anything we need to change to prevent this for new versions in the future?

We could try this:

> Can we delete this and just do `depends_on "terminal-notifier"` instead, so we also get a native version on ARM?

**Comment by joshdholtz** [comment]
Ohhhhhh, I (for some reason) thought that was referring to something with the CI jobs 🤦 

I will look into figuring out how to do that 😅 Thanks for the reply!

**Comment by carlocab** [comment]
Sure. Shouldn't be too hard -- see #81621 for an example where we do something similar. You can ignore the changes to `universal_binary_allowlist.json`, since this formula doesn't install any universal binaries.

**Pull request closed without merging**
