### PR TITLE
postgresql 10.6

### PR DESCRIPTION
**Pull request by lrosenman**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lrosenman** [comment]
I *THINK* that the PostgreSQL folks have changed some of the build infrastructure to deal with the SDK changes.  How can I help fix this?

**Comment by yurikoles** [comment]
@lrosenman please fix inreplaces [here](https://github.com/Homebrew/homebrew-core/blob/2a7e246a26762167dc4f78ddd5da3aecc333d2da/Formula/postgresql.rb#L74):

**Comment by lrosenman** [comment]
Is it normal for the checks to take 6+ hours?

**Comment by lrosenman** [comment]
I'm not sure where to go from here.  On *MY* box with the HomeBrew perl, it runs installs fine on Mojave:

[lrosenman:/usr … homebrew-core/Formula] master+ ± psql --version
psql (PostgreSQL) 10.6
[lrosenman:/usr … homebrew-core/Formula] master+ ± psql -c "select version()"
                                                     version
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 10.6 on x86_64-apple-darwin18.2.0, compiled by Apple LLVM version 10.0.0 (clang-1000.11.45.5), 64-bit
(1 row)

⌂62% [lrosenman:/usr … homebrew-core/Formula] master+ ±

**Comment by apjanke** [comment]
Audit failure:

```
failed: brew audit postgresql --online
Stacktrace
        Error: 1 problem in 1 formula detected
postgresql:
  * C: 24: col 3: dependency "perl" (line 24) should be put before dependency "readline" (line 23)
```

And it looks like `libpqxx` needs a revision bump.

```
failed: brew test --verbose libpqxx
[...]
==> /usr/bin/clang++ -std=c++11 test.cpp -L/usr/local/Cellar/libpqxx/6.2.5/lib -lpqxx -I/usr/local/Cellar/libpqxx/6.2.5/include -o test
Error: libpqxx: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: Please revision bump libpqxx.
```

**Comment by lrosenman** [comment]
How do I "revision bump" libpqxx?

**Comment by apjanke** [comment]
> How do I "revision bump" libpqxx?

In this PR, but in a separate commit, edit `Formula/libpqxx.rb` and add a line saying `revision 1` after the `sha256` line. Make the commit message be "libpqxx: revision bump for postgresql 10.6".

**Comment by lrosenman** [comment]
Ok, so what magic am I missing to have Brew pick up:
[lrosenman:/usr/local] $ find . -type f -name perl.h
./Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE/perl.h
[lrosenman:/usr/local] $

@apjanke ?

**Comment by SMillerDev** [comment]
I think all you need to do is remove all the `inreplace`s in that block and not actually link to homebrew perl.

**Comment by lrosenman** [comment]
I just pushed a rev without any reinplace, and removed the perl dependency.  We'll see.

**Comment by SMillerDev** [comment]
Tests pass, maybe you were just unlucky with an unrelated CI failure last time.

**Comment by SMillerDev** [comment]
@fxcoudert how do you want to do this with 11?

**Comment by fxcoudert** [comment]
I'm fine with merging this now, provided that all commits are squashed into two commits: one per formula, with conflicts resolved.

We can continue to work on postgresql 11 in the meantime.

**Comment by lrosenman** [comment]
can someone(tm) help me fix this (I'm not a rebase/squash guru).

**Comment by lrosenman** [comment]
@fxcoudert can you help me with this?  (I apparently screwed up my branch :( )

**Comment by fxcoudert** [comment]
@lrosenman you can open a new PR, with two commits: one for postgresql, one for the revision bump of libpqxx

**Comment by fxcoudert** [comment]
Thanks @lrosenman I have now merged it in https://github.com/Homebrew/homebrew-core/pull/34687

**Pull request closed without merging**
