### PR TITLE
libnghttp2, nghttp2 1.51.0

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
On linux

```
brew test --retry --verbose beast
brew test --retry --verbose hbase
brew test --retry --verbose mrbayes
brew test --retry --verbose quazip
brew test --retry --verbose zorba
```

On other osx versions

```
brew test --retry --verbose fauna-shell
```

**Comment by cho-m** [comment]
Linux failures are expected.

May want to make sure on `fauna-shell` by trying locally.

**Review by SMillerDev — APPROVED** [review]

**Comment by bayandin** [comment]
It looks like we're missing bottles for this PR:
```
% brew upgrade
==> Upgrading 1 outdated package:
libnghttp2 1.50.0 -> 1.51.0
==> Downloading https://ghcr.io/v2/homebrew/core/libnghttp2/manifests/1.51.0
curl: (22) The requested URL returned error: 404                              

Error: libnghttp2: Failed to download resource "libnghttp2_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/libnghttp2/manifests/1.51.0
```

**Comment by p-linnane** [comment]
I just noticed that and have a rebuild running.

**Comment by cjgratacos** [comment]
@p-linnane thanks for expediting this, it looks like the build failed :(

**Comment by p-linnane** [comment]
Waiting on runners: https://github.com/Homebrew/homebrew-core/actions/runs/3525708025

**Comment by frosit** [comment]
same problem here on osx 12.6.1

**Comment by p-linnane** [comment]
This was due to an error on my part. `libnghttp2` is fixed, with `nghttp2` currently queued. Run `brew update` before trying again.

**Comment by timjstewart1024** [comment]
@p-linnane Thank you so much for resolving this issue and for your work on such a foundational library!

**Pull request merged**
