### PR TITLE
siril: bump version, enable OpenMP support, point to a new repository

### PR DESCRIPTION
**Pull request by susemeee**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- 0.9.10
- OpenMP support
- Points toward a new repository (git)

### CODE REVIEW

**Comment by lock042** [comment]
@fxcoudert : Hello, do you think it is possible to merge this PR? It should fix the issue you've noticed with openmp.
Cheers,

**Comment by fxcoudert** [comment]
Thanks @susemeee for the pull request

**Comment by lock042** [comment]
@susemeee : do you think you could rebase on top of master ?

**Comment by susemeee** [comment]
Did it again.

**Comment by lock042** [comment]
@fxcoudert : I think this is ok now ;).

**Comment by susemeee** [comment]
CI failed in Sierra. Is it related to removal of `cxx11` flag?

**Comment by lock042** [comment]
@susemeee : I don't know :s

**Comment by fxcoudert** [comment]
Thanks @susemeee

**Pull request closed without merging**
