### PR TITLE
Mercurial 4.2

### PR DESCRIPTION
**Pull request by ngoldbaum**
This updates mercurial to version 4.2.

This version moved the pager extension into core, which means we need to configure a default pager lest it use `more` (which is guaranteed to be there by POSIX, unlike `less`). To make sure that the transition is seamless, I've installed an hgrc file into a location that mercurial will search on startup. If people already have a pager configured in an hgrc file in their home directory, that configuration will take precedence over the one I'm installing.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Huh, I can't reproduce the build failures.

**Comment by ngoldbaum** [comment]
Ok, now it looks like the build is failing because this broke `git-remote-hg`. I guess `git-remote-hg` needs to be updated for mercurial 4.2 somehow?

**Comment by ngoldbaum** [comment]
OK, I've resolved the test failures by vendoring mercurial in the `git-remote-hg` formula. I had to do this because `git-remote-hg` is using private APIs that changed in mercurial 4.2. `git-remote-hg` will need to be updated before we can de-vendor hg.

**Comment by tdsmith** [comment]
Thanks for your work on this!

**Pull request closed without merging**
