### PR TITLE
cbmc: use openjdk@11 as JBMC build fails with JDK 17

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
AFAIK this has never been bottled for Linux, so I think we should be fine to disable the Java bindings on it, and that wouldn't be a regression.

**Comment by cho-m** [comment]
Could be due to Bison 3.8.x update (e.g. #84931), which happened after `cbmc` was bottled on Linux. Error is happening on Bison trying to run M4:
```
[ 13%] [BISON][parser] Building parser with bison 3.8.1
cd /tmp/cbmc-20210916-10749-6xzh9n/src/xmllang && /home/linuxbrew/.linuxbrew/bin/bison -pyyxml -d -o /tmp/cbmc-20210916-10749-6xzh9n/build/src/xmllang/xml_y.tab.cpp /tmp/cbmc-20210916-10749-6xzh9n/src/xmllang/parser.y
/home/linuxbrew/.linuxbrew/bin/bison: m4 subprocess failed
src/xmllang/CMakeFiles/xml.dir/build.make:76: recipe for target 'src/xmllang/xml_y.tab.cpp' failed
make[2]: *** [src/xmllang/xml_y.tab.cpp] Error 1
make[2]: Leaving directory '/tmp/cbmc-20210916-10749-6xzh9n/build'
CMakeFiles/Makefile2:2172: recipe for target 'src/xmllang/CMakeFiles/xml.dir/all' failed
make[1]: *** [src/xmllang/CMakeFiles/xml.dir/all] Error 2
```

In theory, M4 should be indirectly accessed via Bison's dependency, but can try directly adding via `uses_from_macos`.

If still has issue, then can try using `M4` environment variable.

**Comment by carlocab** [comment]
Opened Homebrew/brew#12069.

**Comment by cho-m** [comment]
Also need to re-run as Homebrew/brew commit didn't get picked up on CI:
```
==> Using Homebrew/brew 3.2.12-45-ge011b1595 (Merge pull request #12072 from XuehaiPan/refactor-shell-formatter)
```

**Comment by carlocab** [comment]
CI's not starting for some reason. Let's try to get this going.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
