### PR TITLE
func-e 0.5.1

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This makes the version override look nice like the others.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
let's see if arm bottle can be built

**Comment by chenrui333** [comment]
@carlocab looks like we just have some race condition in here 😅  just cancelled the merge build and see if the formula can be built in 11-arm64 runner.

**Comment by carlocab** [comment]
ARM doesn't work, see #80802

**Comment by codefromthecrypt** [comment]
We can do arm if it is possible to know that rosetta 2 is installed.. it would be setting `FUNC_E_PLATFORM=darwin/amd64`. Is there a way to do that?

**Comment by carlocab** [comment]
`brew` only knows whether it's running in Rosetta, and not whether Rosetta is installed.

**Comment by codefromthecrypt** [comment]
> brew only knows whether it's running in Rosetta, and not whether Rosetta is installed.

I suppose if it is running in rosetta, is the important thing. Would it make sense to set ENV based on this? I mean are there other formulas that do this? Also does test-bot run in rosetta?

cc @karl-cardenas-coding who added the `FUNC_E_PLATFORM` feature.

**Comment by carlocab** [comment]
test-bot does not run under Rosetta because it's meant to be building natively for ARM. I don't think there are any formulae that do what you're suggesting.

**Comment by codefromthecrypt** [comment]
ok let's drop the arm64 idea for now. Thanks for the advice. power users can meanwhile download using the curl-sh from the [website](https://func-e.io/) knowing the env trick from the [release notes](https://github.com/tetratelabs/func-e/releases/tag/v0.5.1)

**Comment by karl-cardenas-coding** [comment]
@codefromthecrypt Yeah, it's probably just best to wait until Envoy releases `darwin/arm64`

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
