### PR TITLE
plantuml-1.2017.16

### PR DESCRIPTION
**Pull request by jessetan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Changes: http://plantuml.com/changes

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @jessetan for the pull request!

**Comment by keithballdotnet** [comment]
I am getting:

➜ brew install plantuml
==> Downloading https://downloads.sourceforge.net/project/plantuml/1.2017.16/plantuml.1.2017.16.jar
==> Downloading from https://downloads.sourceforge.net/#!/project/plantuml/1.2017.16/plantuml.1.2017.16.jar
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a3d319ed54ed78ce3cf7bfcfe76ffc5aa6ed28a72b5aa575fe9125e0c6bd985c
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/keithball/Library/Caches/Homebrew/plantuml-1.2017.16.jar
To retry an incomplete download, remove the file above.

Any solution to this?

**Comment by ogom** [comment]
@keithballdotnet 

> To retry an incomplete download, remove the file above.

```
rm /Users/keithball/Library/Caches/Homebrew/plantuml-1.2017.16.jar
brew install plantuml
```

**Comment by keithballdotnet** [comment]
@ogom Nope the hash was incorrect.

**Pull request merged**
