### PR TITLE
pdnsrec 4.5.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: Failed changing rpath in /opt/homebrew/Cellar/pdnsrec/4.5.1/sbin/pdns_recursor
  from /opt/homebrew/opt/boost/lib
    to @@HOMEBREW_PREFIX@@/opt/boost/lib
Error: Unrecognized Mach-O load command: 0x00
```

**Comment by carlocab** [comment]
>```
> Error: Failed changing rpath in /opt/homebrew/Cellar/pdnsrec/4.5.1/sbin/pdns_recursor
>   from /opt/homebrew/opt/boost/lib
>     to @@HOMEBREW_PREFIX@@/opt/boost/lib
> Error: Unrecognized Mach-O load command: 0x00
>```

@woodruffw any chance you can take a look at this?

**Comment by carlocab** [comment]
The problem seems to be that `/usr/local/opt/boost/lib` appears several times:
```
❯ otool -l pdns_recursor | rg -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 40
         path /usr/local/opt/boost/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 40
         path /usr/local/opt/boost/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 40
         path /usr/local/opt/boost/lib (offset 12)
```

**Comment by carlocab** [comment]
Opened an issue at https://github.com/Homebrew/ruby-macho/issues/356.

**Comment by carlocab** [comment]
Should be fixed by https://github.com/Homebrew/brew/pull/11387.

**Comment by carlocab** [comment]
Fixed in https://github.com/Homebrew/brew/pull/11391. Restarting CI.

**Comment by carlocab** [comment]
Hmmm, looks like the fix didn't take.

**Comment by carlocab** [comment]
Not sure why, as I can't reproduce the failure locally when I try to use `MachO::Tools.change_rpath` on it (which is essentially what `brew` does).

Let's try rebasing and see if that helps (even if I have no idea why it should). Otherwise, we can try deleting those `LC_RPATH` entries in the install method directly. They're not needed.

**Comment by carlocab** [comment]
Ah, wait, no, the error is different:

```
Error: No such runtime path: /opt/homebrew/opt/boost/lib
```

I see. This can be fixed.

**Comment by carlocab** [comment]
https://github.com/Homebrew/brew/pull/11392

**Comment by carlocab** [comment]
Missed the Mojave build failure:
```
Undefined symbols for architecture x86_64:
  "MOADNSParser::init(bool, std::__1::basic_string_view<char, std::__1::char_traits<char> > const&)", referenced from:
      MOADNSParser::MOADNSParser(bool, char const*, unsigned int) in axfr-retriever.o
      MOADNSParser::MOADNSParser(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ixfr.o
      MOADNSParser::MOADNSParser(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in pdns_recursor.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This was present also in previous runs, and is unrelated to the duplicate `RPATH` bug.

**Comment by carlocab** [comment]
I think Mojave libc++ is just too old. See also https://github.com/PowerDNS/pdns/issues/10270.

**Comment by carlocab** [comment]
Added dependency on Catalina.

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
