### PR TITLE
libxcb: migrate to `python@3.12`

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by iMichka** [comment]
PyTorch, fmt: #154197

**Comment by chenrui333** [comment]
```
brew test --retry --verbose lilypond
brew test --retry --verbose mps-youtube
brew install --only-dependencies openai-whisper
brew link pytorch
brew link pytorch
brew test --retry --verbose torchvision
```

**Comment by iMichka** [comment]
Fix for lilypond: #154318

**Comment by iMichka** [comment]
`lilypond`, `pytorch`, `torchvision`, `openai-whisper` are unrelated and fixed.

**Comment by iMichka** [comment]
`mps-youtube` has an unrelated failure, and I do not know how to fix it.
`mps-youtube` depends either on `mplayer` or `mpv`.
We do not explicitly depend on `mpv`, only on `mplayer` in the formula.

You can switch between both, while the app is running in the terminal, with:
`set player mpv or set player mplayer - change player application`

We can't chose the player through a flag ... so if `mpv` is installed on the system, it will pick it up first.
`mpv` has issues with `libplacebo`, thus resulting in an error in the test.
See:
https://github.com/Homebrew/homebrew-core/pull/153349
https://github.com/Homebrew/homebrew-core/pull/153961

I'm unsure on how to properly fix this. We could depend on `mpv` too, but that's adding a bunch of dependencies ...

**Review by iMichka — APPROVED** [review]

**Pull request merged**
