### PR TITLE
hurl 3.0.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not marked as the latest release yet:
- https://github.com/Orange-OpenSource/hurl/releases
- https://crates.io/crates/hurl

**Comment by p-linnane** [comment]
Release PR is here, but not yet merged: https://github.com/Orange-OpenSource/hurl/pull/1508

**Comment by jcamiel** [comment]
Hi @p-linnane we have just published the release and removed the draft status on 3.0.0
Thanks for the update !

**Review by ZhongRuoyu — APPROVED** [review]
Thanks for confirming, @jcamiel!

**Pull request merged**
