### PR TITLE
ghostscript 9.54.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by carlocab** [comment]
Weird errors:
```
In file included from tesseract/src/api/altorenderer.cpp:20:
In file included from tesseract/include/tesseract/baseapi.h:29:
In file included from tesseract/include/tesseract/resultiterator.h:24:
In file included from tesseract/include/tesseract/ltrresultiterator.h:26:
tesseract/include/tesseract/unichar.h:24:10: fatal error: 'cstring' file not found
#include <cstring>
         ^~~~~~~~~
In file included from tesseract/src/api/capi.cpp:18:
In file included from tesseract/include/tesseract/capi.h:24:
In file included from tesseract/include/tesseract/baseapi.h:29:
In file included from tesseract/include/tesseract/resultiterator.h:24:
In file included from tesseract/include/tesseract/ltrresultiterator.h:26:
tesseract/include/tesseract/unichar.h:24:10: fatal error: 'cstring' file not found
#include <cstring>
         ^~~~~~~~~
In file included from tesseract/src/api/baseapi.cpp:27:
In file included from tesseract/src/classify/blobclass.h:24:
tesseract/src/ccutil/strngs.h:24:10: fatal error: 'cassert' file not found
#include <cassert>  // for assert
         ^~~~~~~~~
```

**Comment by Bo98** [comment]
> `-stdlib=libstdc++`

**Comment by Bo98** [comment]
> Mainly due to time constraints, we only support including Tesseract from source included in our release packages, and not linking to Tesseract/Leptonica shared libraries. Whether we add this capability will be largely dependent on community demand for the feature. 

https://www.ghostscript.com/doc/9.54.0/News.htm

I'd suggest adding `--without-tesseract`, with a comment to revisit it when they support linking with the brewed version.

I also think we need to do a better job at using brewed libraries. For example, it uses its own version of `jpeg`, but it seems like using the system version is possible if we remove the `jpeg` directory. I can poke at this a little later.

**Comment by carlocab** [comment]
It also passes `--without-libidn`, but `depends_on "libidn"` on Linux.

**Pull request closed without merging**
