### PR TITLE
iso-codes: fix dependencies and test

### PR DESCRIPTION
**Pull request by tschoonj**
also rev bump gspell

### CODE REVIEW

**Comment by tschoonj** [comment]
@MikeMcQuaid this is an interesting failure... `iso-codes` gets built successfully but then `gspell` cannot find the bottle as it desperately tries to download from bintray.

**Comment by MikeMcQuaid** [comment]
@tschoonj `iso-codes` probably shouldn't be uninstalled. As a workaround you could try and remove its bottle block.

**Comment by fxcoudert** [comment]
It seems to be a bug in test bot, and recent. I've seen it happen with at least one other formula: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/37061/

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Bottles already published, now removed. Rebuilding.
@BrewTestBot test this please

**Comment by tschoonj** [comment]
Merci @fxcoudert!

**Pull request closed without merging**
