### PR TITLE
erlang: add ODBC support using unixodbc

### PR DESCRIPTION
**Pull request by nosnilmot**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by p-linnane** [comment]
Build failure on Ventura Intel:
```
  escript /private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/bootstrap/lib/erl_docgen/priv/bin/specs_gen.escript -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/include -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/src -o../specs/ ../../preloaded/src//erl_prim_loader.erl
  escript /private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/bootstrap/lib/erl_docgen/priv/bin/specs_gen.escript -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/include -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/src -o../specs/ ../../preloaded/src//erlang.erl
  escript /private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/bootstrap/lib/erl_docgen/priv/bin/specs_gen.escript -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/include -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/src -o../specs/ ../../preloaded/src//erl_tracer.erl
  escript /private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/bootstrap/lib/erl_docgen/priv/bin/specs_gen.escript -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/include -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/src -o../specs/ ../../preloaded/src//init.erl
  escript /private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/bootstrap/lib/erl_docgen/priv/bin/specs_gen.escript -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/include -I/private/tmp/erlang-20221221-7215-1yt50fv/otp_src_25.2/lib/*/src -o../specs/ ../../preloaded/src//persistent_term.erl
  could not write file '../specs/erl_prim_loader.specs': no such file or directory
  make[2]: *** [../specs/specs_erl_prim_loader.xml] Error 2
  make[2]: *** Waiting for unfinished jobs....
  could not write file '../specs/erl_tracer.specs': no such file or directory
  make[2]: *** [../specs/specs_erl_tracer.xml] Error 2
  could not write file '../specs/init.specs': no such file or directory
  could not write file '../specs/persistent_term.specs': no such file or directory
  make[2]: *** [../specs/specs_init.xml] Error 2
  make[2]: *** [../specs/specs_persistent_term.xml] Error 2
  could not write file '../specs/erlang.specs': no such file or directory
  make[2]: *** [../specs/specs_erlang.xml] Error 2
  make[1]: *** [docs] Error 2
  make: *** [docs] Error 2
```

**Comment by nosnilmot** [comment]
> Build failure on Ventura Intel:

It's quite unlikely this is caused by the changes in this PR, far more likley to be a lingering/latent issue with paralellism in 'make docs'

4bbb39f218f335fa4f7e6c9740f376eeb39a93e5 removed parallelism from 'make install-docs' but the commit message didn't sound convincing that it was 100% fixed ("...try to mitigate CI failure"), so I will do the same for 'make docs' and cross my fingers.

**Comment by nosnilmot** [comment]
> Error: PR requires the CI-long-timeout label but it is not set!
> Error: If the longer timeout is not required, remove the "long build" label.
> Error: Otherwise, add the "CI-long-timeout" label.
> Error: No more than 2 PRs at a time may use "CI-long-timeout".

This PR still needs "CI-long-timeout", but I guess @fxcoudert removed it because of the 4th item above.
How do I request it is added again?

**Comment by p-linnane** [comment]
Other PR's are running using the label right now, but I will circle back and relabel this one after one frees up.

**Comment by p-linnane** [comment]
Re-running.

**Comment by nosnilmot** [comment]
> Ventura Intel failure this time (truncated):

Same problem but because previous attempted fix wasn't made in erlang@23 I didn't try it this time either - fixed.

**Review by p-linnane — APPROVED** [review]
Thanks for your persistence with this one @nosnilmot!

**Pull request closed without merging**
