### PR TITLE
bzt 1.10.0 (updated formula)

### PR DESCRIPTION
**Pull request by greyfenrir**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by greyfenrir** [comment]
Hello.
I was trying to use bump-formula-pr, but
1. I've got "Error: cannot get remote from 'hub'!" error, so I decided to send new formula by the regular way
2. If I understood correctly, changes of resources (e.g. new version of pypi package) aren't supported by bump-formula-pr. Am I right?

**Comment by ilovezfs** [comment]
>I've got "Error: cannot get remote from 'hub'!" error, so I decided to send new formula by the regular way

Are you using the `--devel` version? I believe only stable and HEAD work currently.

>If I understood correctly, changes of resources (e.g. new version of pypi package) aren't supported by bump-formula-pr. Am I right?

If you make the changes to the resource blocks locally first, the command will preserve those changes, but there's no way to specify them via the CLI.

**Comment by ilovezfs** [comment]
@greyfenrir for future, reference, the bottle block shouldn't be modified or removed manually.

**Comment by ilovezfs** [comment]
Thanks @greyfenrir! Shipped.

**Pull request closed without merging**
