### PR TITLE
imagemagick 7.1.1-11

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
only one regression test failure on linux build
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/spaceman-diff/1.0.3/bin/spaceman-diff
  ==> script -q /dev/null -c /home/linuxbrew/.linuxbrew/Cellar/spaceman-diff/1.0.3/bin/spaceman-diff /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.png a190ba 100644 /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.png 000000 100644
  script: unexpected number of arguments
```

**Comment by carlocab** [comment]
@iMichka, didn't you fix this?

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Will need rebase for #131668.

**Comment by iMichka** [comment]
> @iMichka, didn't you fix this?

I thought I had. I will have another look

**Comment by chenrui333** [comment]
> only one regression test failure on linux build
> 
> ```
>   ==> /home/linuxbrew/.linuxbrew/Cellar/spaceman-diff/1.0.3/bin/spaceman-diff
>   ==> script -q /dev/null -c /home/linuxbrew/.linuxbrew/Cellar/spaceman-diff/1.0.3/bin/spaceman-diff /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.png a190ba 100644 /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.png 000000 100644
>   script: unexpected number of arguments
> ```

should be good with #132695

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
