### PR TITLE
nest 2.20.0 (new formula)

### PR DESCRIPTION
**Pull request by tammoippen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Continuing the migration from in #21561.

Migrating because of: Homebrew/homebrew-science#6331

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
lgtm 💯

**Comment by laurentperrinet** [comment]
by curiosity, why use python@3.8 rather than the standard version available now?

**Comment by tammoippen** [comment]
@laurentperrinet Homebrew is in transition to python 3.8 (#47274) - at some point it will be the standard version ;). Further all dependencies like numpy, scipy, etc are build already with python@3.8, hence nest / PyNEST need to be build with python@3.8 as well - otherwise we have to vendor (build our own) versions of these dependencies.

**Comment by laurentperrinet** [comment]
got it thanks. another reason to switch to python@3.8 before the official transition date :-)

thanks, Laurent

**Pull request closed without merging**
