### PR TITLE
theharvester 4.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
```
/opt/homebrew/Cellar/theharvester/4.0.0/libexec/venv/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
```
Resources probably need updating.

**Comment by chenrui333** [comment]
doing that now.

**Comment by cho-m** [comment]
`orjson` needs Rust to build https://github.com/ijl/orjson/tree/3.5.3#packaging

The docs mention that Rust should be from nightly channel.
If so, this would require `rustup-init` like `signal-cli`.

**Comment by cho-m** [comment]
I added an initial set of changes to build `orjson` resource.
May need to be cleaned-up/improved.

Unlike `signal-cli`, the `orjson` code base does not include a Rust version file (e.g. `rust-toolchain` or `rust-toolchain.toml`) so it needs to be manually set.

Alternatively,
- Can use unpinned `nightly`; however, there will be a version released every day, which means the build can easily change from passing one day to failing on another.
- Or can try using grep-logic to pick up version from README.md or ci/azure-pipelines.yml

**Comment by carlocab** [comment]
I think we can just hardcode the existing value in `README.md`, `nightly-2021-05-25`.

**Review by nandahkrishna — APPROVED** [review]

**Pull request closed without merging**
