### PR TITLE
stunnel: revision for openssl update

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This looks like an upstream issue. Why would we need to revision bump on an update that doesn't change the shared library version numbers?

**Comment by DomT4** [comment]
It's a slightly silly situation, but nonetheless us and IIRC Debian & other distros have been rebuilding `stunnel` to burn away the warning for years regardless, partly because if you search the warning phrase you encounter mountains of confusion & anxiety about it. I presume upstream are well aware it's an annoyance, but nonetheless it remains.

**Comment by ilovezfs** [comment]
To put it another way, I'm unwilling to revision bump this every openssl update unless we're having to revision bump everything because there was an actual library number change. Hence, closing.

**Comment by DomT4** [comment]
Alright 🤷‍♂️.

**Pull request closed without merging**
