### PR TITLE
ispc 1.18.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Their CI use LLVM 15, maybe this could be used here too?

**Comment by chenrui333** [comment]
> Their CI use LLVM 15, maybe this could be used here too?

The change is not part of the latest release. Maybe next release to try?

**Comment by Porkepix** [comment]
Well it's been one month they use LLVM 15, and this release is from yesterday. The last commit merely moved from 15.0.2 to 15.0.3.

**Comment by iMichka** [comment]
Rebased and updated the checksum, it looks like it changed meanwhile ...

**Comment by chenrui333** [comment]
it does not build with llvm@15, unfortunately.

**Pull request closed without merging**
