### PR TITLE
oci-cli: license update

### PR DESCRIPTION
**Pull request by kernleee**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
Need to wait for next `brew` release.

**Comment by chenrui333** [comment]
bumped the release in #59169

**Comment by kernleee** [comment]
@dawidd6 @chenrui333 Could I get review/merge on this pr? Thanks

**Comment by SeekingMeaning** [comment]
@kernleee Sorry for the wait! Now that `brew` 2.4.10 is released, we can merge this PR 🎉

**Comment by SeekingMeaning** [comment]
Thanks again for your contribution to Homebrew/core! 🌟

**Pull request merged**
