### PR TITLE
aws-okta 0.19.3

### PR DESCRIPTION
**Pull request by josacar**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by josacar** [comment]
Will check if build succeeds as Golang 1.11 fails :(

**Comment by DomT4** [comment]
```
==> go build -ldflags -X main.Version=0.19.1
# github.com/segmentio/aws-okta/vendor/github.com/keybase/go-keychain
vendor/github.com/keybase/go-keychain/corefoundation_go110.go:35:33: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFDataCreate
vendor/github.com/keybase/go-keychain/corefoundation_go110.go:61: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/keybase/go-keychain/corefoundation_go110.go:98:41: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithBytes
vendor/github.com/keybase/go-keychain/corefoundation_go110.go:133: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
```

Looks like this was fixed in https://github.com/keybase/go-keychain/commit/15d3657f24fc7e290714ab795239c5bb33b091ea, so might just be a case of upstream needing to update their vendored dependencies.

**Comment by josacar** [comment]
Yes, I did a PR https://github.com/segmentio/aws-okta/pull/72 some minutes ago, but release is tagged already.

**Comment by DomT4** [comment]
Thanks for that. If upstream aren't willing to cut a new release so soon after the last one we could always pull that PR in as a patch in the formula, but we'll see what they say upstream.

**Comment by josacar** [comment]
@DomT4 Let's see with new upstream, they included okta verification when adding credentials and now these test credentials fail as expected

**Comment by josacar** [comment]
@DomT4 What do you think? It works, but I want to know if you have any concern

**Comment by javian** [comment]
This looks ready to ship now that all the issues have been resolved. Thanks for putting in the work to make this happen @josacar !

**Pull request closed without merging**
