### PR TITLE
neovim 0.4.0

### PR DESCRIPTION
**Pull request by 1995parham**
Update Neovim version from 0.3.8 to 0.4.0.

### CODE REVIEW

**Comment by justinmk** [comment]
Updating to Nvim 0.4.x will require getting the `luv` dependency working, see discussion at https://github.com/Homebrew/homebrew-core/issues/40854 .

This wasn't done for the `--HEAD` build because AFAIK homebrew was waiting on an official Nvim release before tackling it.

**Comment by 1995parham** [comment]
@justinmk Thanks for your information I haven't seen the thread. Neovim release officially 0.4.0, 4 hours earlier. Besides `luv`, it requires `libvterm` that is provided [here](https://github.com/neovim/libvterm) instead of the official version.

**Comment by justinmk** [comment]
> it requires `libvterm` that is provided [here](https://github.com/neovim/libvterm) instead of the official version

No. It works with libvterm 0.1. https://github.com/neovim/libvterm is simply a mirror, and the [0.1](https://github.com/neovim/libvterm/tree/v0.1) branch is equivalent to libvterm 0.1 in the upstream bzr repo.

**Comment by 1995parham** [comment]
@justinmk Sorry for my mistake. I think in the first step we need to update the libvterm formula before we can proceed with neovim.

**Pull request closed without merging**
