### PR TITLE
Remove picolisp and ufoai

### PR DESCRIPTION
**Pull request by fxcoudert**
The two remaining formulas that don't build with Xcode 9.

- ufoai has little usage and sources aren't even online anymore… poke @mistydemeo 
- picolisp is 32-bit only, and does not build with Xcode 9; author does not intend to fix, and the 64-bit engine never was intended to work on macOS

### CODE REVIEW

**Comment by ylluminarious** [comment]
@fxcoudert Sigh... I hate seeing so many deleted formulas when I run `brew update`...

Would you accept a new version of the `picolisp` formula if I write one? I'm a bit strapped for time currently, but I could get around to it at some point.

**Comment by fxcoudert** [comment]
@ylluminarious yes, of course! but given the state of the project, which is explicitly not supported on macOS, it seems like an ambitious project (and will probably require new code in picolisp and a new release)

**Comment by fxcoudert** [comment]
To be clear: I hate deleting formulas, but on the other hand, we're not a software conservation project: we want to ship software that people use, and that works :)  Formulas deleted were not working.

**Comment by ylluminarious** [comment]
@fxcoudert Ok, understood. I'll have to think on that and see what I can do.

**Pull request merged**
