### PR TITLE
openstackclient 6.6.1

### PR DESCRIPTION
**Pull request by cardoe**
Python 3.12 wasn't officially supported by this past release cycle of OpenStack so a handful of the command line clients do not work correctly with it. So drop the Python version down to 3.11 to ensure compatibility while using "brew update-python-resources" to get other packages up to date.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cardoe** [comment]
I bumped the revision to fix the commands that I added in #176382

**Comment by branchvincent** [comment]
Can you be more specific about the issues you see? Are there issues tracking 3.12 support? If possible, we try to help patch upstreams to be compatible rather than downgrading python

**Comment by cardoe** [comment]
> Can you be more specific about the issues you see? Are there issues tracking 3.12 support? If possible, we try to help patch upstreams to be compatible rather than downgrading python

Yeah so they depend on pkg_resources which isn't being installed and isn't depended on. I've created gerrit changes to start fixing things up but they want me to support Python 3.8 as well which means I need to use the importlib_resources backport. But that's not allowed per their global requirements policies. So yeah... yak shaving. This is the base changes from which others will depend on https://review.opendev.org/c/openstack/requirements/+/925306

**Comment by cardoe** [comment]
As far as the specific issue seen, I honestly don't know the exact issue. You aren't able to run `openstack baremetal <anything>` because it says `baremetal` isn't a valid sub-command even though it should be. That's why I added it as a test in this change.

**Comment by cardoe** [comment]
Not sure if that's a transient error cause that's building the Rust program maturin which is used by cryptography which I would think has a wider usage than just this package.

**Comment by cardoe** [comment]
I think we can keep Python 3.12 support if we add "setuptools" to `extra_packages` and then remove it in a later release.

**Comment by branchvincent** [comment]
Gotcha yea adding `setuptools` would definitely be preferred + a comment above the resource blocks about what exact dependencies need it and a reference to an upstream bug/PR that we are waiting on. 

Looks like `python-ironicclient` was fixed in https://opendev.org/openstack/python-ironicclient/commit/54b878238c712b6bff890fac0a9e51c42214a861 and `pbr` changes are still under review: https://review.opendev.org/c/openstack/pbr/+/924216

Also [6.6.1](https://pypi.org/project/python-openstackclient/6.6.1/) was just published so would could bump to that version here if you want

**Comment by cardoe** [comment]
Beat me to pushing the change. Thank you.

**Comment by branchvincent** [comment]
No worries, thank you for creating the PR!

**Review by chenrui333 — APPROVED** [review]

**Review by cardoe — COMMENTED** [review]
Looks good to me. I'll work the rest of the patches upstream into a release and clean this up once it's all released. I'm already working on some Python 3.13 fixes as well.

**Pull request merged**
