### PR TITLE
go 1.9.3

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by cblecker** [comment]
@leonklingele similar to last time, you need to bump the revision on godep:
https://github.com/Homebrew/homebrew-core/pull/19000#issuecomment-334285372

**Comment by leonklingele** [comment]
@cblecker oops, totally forgot about that. Should be fixed now.

**Comment by DomT4** [comment]
Oh, we were going to change the URL here. What did the Google folk want us to use instead. Let me hunt down the other PR 🙈.

**Comment by DomT4** [comment]
Yeah. `https://dl.google.com/go/go1.9.3.src.tar.gz` is the new format.

**Comment by leonklingele** [comment]
Interesting, where did you find this?

**Comment by DomT4** [comment]
The original discussion? See my "review" in https://github.com/Homebrew/homebrew-core/pull/21448.

**Comment by DomT4** [comment]
The bootstrap would become `https://dl.google.com/go/go1.7.darwin-amd64.tar.gz` but @ilovezfs might want that kept as-is until the bootstrap gets bumped at some later point in time. That's his call.

**Comment by leonklingele** [comment]
Updated to adapt to the new URL format.

**Comment by DomT4** [comment]
Thanks!

**Comment by ilovezfs** [comment]
Thanks again @leonklingele :lion:

**Pull request closed without merging**
