### PR TITLE
libgit2 0.24.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
You'll have to wait until my GNOME PR I'm afraid. This won't work alone, same as most of the major GNOME stuff. Planning to set aside time for that this afternoon now I've finally got the initial GPG PRs out the door.

**Comment by ilovezfs** [comment]
does that include pango?

**Comment by DomT4** [comment]
Yup.

**Comment by UniqMartin** [comment]
You're also duplicating #492. 😢 I believe not duplicating PRs also applies to maintainers …

**Comment by ilovezfs** [comment]
@UniqMartin I really have no kind response to that, so I'll just say nothing.

**Comment by UniqMartin** [comment]
@ilovezfs Don't get me wrong. I appreciate you wrangling this immense amount of formulae and pushing for more automation, but sometimes there are limits to that and some manual steps (or better automated guards) are necessary … Assuming this version bump PR was created semi-automatically, consider this a feature request to check for existing open pull requests.

**Comment by ilovezfs** [comment]
No comment.

**Comment by UniqMartin** [comment]
@ilovezfs If I said something wrong, not pointing that out and instead giving me the silent treatment won't help me understand and won't make it possible for me to apologize or correct my mistake. 😞

**Pull request closed without merging**
