### PR TITLE
python: Don't memorize Cellar paths.

### LINKED ISSUE #5428: Wrong Python directory when installing MacVim from bottle
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

After updating the homebrew version of python from 2.7.12 to 2.7.12_1 (https://github.com/Homebrew/homebrew-core/commit/6b08d86854de8668cb873f8fb27acd61296e19a5), the path to the homebrew python that MacVim uses is incorrect when installing MacVim from a bottle. This results in the following error when starting up MacVim and attempting to execute some python vimscript:

```
Error detected while processing function <SNR>36_InitializePythonBuiltin:
line   23:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```

Notice the python path in the following commands. In the former, python is installed to `/usr/local/Cellar/python/2.7.12_1`, but MacVim is looking for it in `/usr/local/Cellar/python/2.7.12`.

```
# brew --config
HOMEBREW_VERSION: 1.0.5-43-g41b2df8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 41b2df8e338c3fe345afc89b1bb394e824213561
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a5fba74ccdfc3f54aceb9defccd653beb64134af
Core tap last commit: 73 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/ruby-build/ruby-2.3.0/bin/ruby
Java: 1.8.0_77
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: N/A
```

```
# mvim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 16 2016 20:34:19)
MacOS X (unix) version
Included patches: 1-3
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     +tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      +terminfo
+browse          +fork()          +multi_lang      +termresponse
++builtin_terms  +fullscreen      -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +odbeditor       +toolbar
+clientserver    +insert_expand   +packages        +transparency
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
+file_in_path    +mouse_sgr       +tag_old_static  
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.12/Frameworks -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.12/Frameworks -L/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.12/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
```

I've tried reinstalling MacVim several times (`brew reinstall macvim`, `brew rm macvim && brew install macvim`), but the same issue happens every time. **However**, if I build MacVim from source with homebrew (`brew install -s macvim`), the path is correct, and the error does not appear.

Thanks, and please let me know if I can provide more information.

### PR DESCRIPTION
**Pull request by tdsmith**
Probably fixes #5428! Should probably be mirrored to python3 if we like the change.

### CODE REVIEW

**Comment by tdsmith** [comment]
secret check incantation: `grep -IRp --exclude installed.txt --exclude-dir .brew -e '^[^#].*Cellar.*' $(brew --prefix python)/`

**Comment by tdsmith** [comment]
confirmed the Cellar path is no longer memorized by vim after this change, i.e. no Python path appears in `strings $(which vim) | grep Cellar`

**Comment by MikeMcQuaid** [comment]
Nice work 👍

**Comment by tdsmith** [comment]
The test failures are real; I missed a way virtualenvs remember paths. Homebrew/brew#1225 resolves that. Everything here will still need a revision bump.

**Comment by tdsmith** [comment]
(where "everything" is "the python3 apps," not "all virtualenv formulas")

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
python bottle failed in https://bot.brew.sh/job/Homebrew%20Bottles/60884/console because I published a bad one last week.

**Pull request closed without merging**
