### PR TITLE
Add punto

### PR DESCRIPTION
**Pull request by rahulsom**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you add a more meaningful check? Version checks rarely throw errors if dependencies are wrong for example.

**Comment by rahulsom** [comment]
> Could you add a more meaningful check? Version checks rarely throw errors if dependencies are wrong for example.

Thanks! I've added a test to check if it parses a configuration file.

**Comment by fxcoudert** [comment]
Hi, thanks for the pull request! Homebrew formulas need to build from source to be acceptable in the core repository: https://docs.brew.sh/Acceptable-Formulae

**Comment by fxcoudert** [comment]
@rahulsom this is a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Pull request closed without merging**
