### PR TITLE
imagemagick family: more openmp tweaking

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Product of the discussion in https://github.com/Homebrew/homebrew-core/issues/23461.

### CODE REVIEW

**Comment by DomT4** [comment]
I guess the question is do we want a `deprecated_option` for `gcc` here now 🙈.

**Comment by ilovezfs** [comment]
I'd
```
deprecated_option "with-gcc" => "with-openmp"
```
just to try to avoid annoying people I guess? Presumably some of them had with-openmp converted to with-gcc and just haven't noticed I broke it yet.

**Comment by DomT4** [comment]
> just to try to avoid annoying people I guess?

Yeah, probably wise. There's bound to be someone out there who changed it & didn't notice the new version shipped no `openmp` support regardless of the updated flag. Made the change.

**Comment by ilovezfs** [comment]
>There's bound to be someone out there who changed it 

The deprecated options get changed automatically to undeprecated options in the install receipts so probably more than one someone and they wouldn't have had to actively change anything themselves.

**Comment by DomT4** [comment]
Oh nice. Missed that change. I don't prowl `brew` as aggressively as I do `core`, evidently. Largely because going through the commits on the `brew` side takes more time per commit in terms of clicking through to the original PR & finding any discussion there, etc.

**Comment by DomT4** [comment]
Well, my initial fix left things messy, so, my bad too 😅.

**Pull request merged**
