### PR TITLE
akamai 0.3.1

### PR DESCRIPTION
**Pull request by dshafik**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Downloading binary.....  
Available Commands:

  help
    Displays help information
  list
    Displays available commands
  install
    Fetch and install a package from a Git repository.
  update
    Update a command. If no command is specified, all commands are updated
  upgrade
    Upgrade Akamai CLI to the latest version
 purge
    Purge content from the Edge

See "akamai help [command]" for details.
```
It looks like there's an alignment issue with "purge."

**Comment by dshafik** [comment]
@ilovezfs good catch, I've fixed it, and will push out 0.3.1 next week. I don't think this needs to hold up this PR unless you'd rather not merge this and another one next week?

**Comment by ilovezfs** [comment]
@dshafik I think we can apply it as a `patch do` here. What commit fixes it?

**Comment by ilovezfs** [comment]
@dshafik 

```
diff --git a/Formula/akamai.rb b/Formula/akamai.rb
index 8d98f59..1141e13 100644
--- a/Formula/akamai.rb
+++ b/Formula/akamai.rb
@@ -1,8 +1,18 @@
 class Akamai < Formula
   desc "CLI toolkit for working with Akamai's APIs"
   homepage "https://github.com/akamai/cli"
-  url "https://github.com/akamai/cli/archive/0.3.0.tar.gz"
-  sha256 "089b0f2b8bd8419fa7fee2c18bc391d28b6c8251da198fabe901638bdff968df"
+
+  stable do
+    url "https://github.com/akamai/cli/archive/0.3.0.tar.gz"
+    sha256 "089b0f2b8bd8419fa7fee2c18bc391d28b6c8251da198fabe901638bdff968df"
+
+    # Remove for > 0.3.0
+    # Upstream commit from 10 Aug 2017 "Fix spacing (reported by @ilovezfs)"
+    patch do
+      url "https://github.com/akamai/cli/commit/aafe887.patch?full_index=1"
+      sha256 "7cdc9322a722e50da6870171819994e557af49c86fd8e25fa657d41062785bae"
+    end
+  end
 
   bottle do
     cellar :any_skip_relocation
```

**Comment by dshafik** [comment]
@ilovezfs I fixed the issue and _also_ made it compile without the new automatic on-boarding (confirms `akamai` exists in PATH/installs it) and auto-upgrading (because homebrew should handle this).

**Comment by ilovezfs** [comment]
@dshafik Nice!

```
        == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/akamai.rb ==
C: 26: 65: Unnecessary spacing detected.

1 file inspected, 1 offense detected
```

**Comment by dshafik** [comment]
@ilovezfs fixed the spacing issue... that seems to be a theme with this PR.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @dshafik!

**Pull request closed without merging**
