### PR TITLE
[hana] Bump to v1.1.0

### PR DESCRIPTION
**Pull request by ldionne**
Also, remove bottles, which are inexistent.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — DISMISSED** [review]
Please leave the bottle as-is.

**Comment by ldionne** [comment]
Ok.. But why?

**Comment by ilovezfs** [comment]
@ldionne the bottle commit follows as a separate commit, and changes the bottle block in-place.

**Comment by ilovezfs** [comment]
See?
https://github.com/Homebrew/homebrew-core/commit/b0c2b57d26e00e3dd7588ceb8a3964b0068256f2
https://github.com/Homebrew/homebrew-core/commit/848c173cdb3aecf188e06cce220e8ab9e7c05725

Thanks for the PR. Note the standard bump subject is "hana 1.1.0" for future reference.

**Pull request closed without merging**
