### PR TITLE
openssl@1.1: remove unnecessary build option

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---
- `enable-cms` is a no-op and the feature is enabled by default

### CODE REVIEW

**Comment by DomT4** [comment]
Sorry, I left them in there very deliberately to help people who don't follow OpenSSL so closely debug breakage when switching from 1.0.2 to 1.1.0. `enable-cms` can be removed, but I'd like the rest to stay.

**Comment by vszakats** [comment]
Updated to readd the first three ones. Thanks for jumping in and for committing this formula.

**Comment by DomT4** [comment]
No worries. The work it took to get Homebrew to support and translate (because `@` isn't a valid class character) the new style of core-versioned formulae held things up for a bit 🙈.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/bb93c48973494b8c2791250732254323075a0b20. Thanks @vszakats!

**Comment by vszakats** [comment]
I saw some steps of the struggle. From the outside you couldn't tell, `@` looks as native as it can get (even on Bintray). Excellent job!

BTW, curl and libssh2 are expected to have 1.1 support in their next consecutive releases.

**Pull request merged**
