### PR TITLE
vim: fix missing symlinks with parallel install

### PR DESCRIPTION
**Pull request by chaoren**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by dunn** [comment]
We usually consider parallelization failures to be bugs, so could you report this upstream? Thanks!

**Comment by chaoren** [comment]
I saw tons of `ENV.deparallelize`'d installs in other formulas, so I thought this was a common occurrence. I'll try to report this upstream.

**Comment by dunn** [comment]
It is sadly common, but we try to avoid it when possible.  Thanks!

**Comment by chaoren** [comment]
Filed https://github.com/vim/vim/issues/1031. Should we just wait for upstream to resolve this, or is this temporary fix in Homebrew okay? I'll add the Issue to the comment.

**Comment by dunn** [comment]
If they don't respond in a day or so we'll go ahead and merge, thanks!

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
