### PR TITLE
Aliasing libdwarf -> dwarf-utils

### PR DESCRIPTION
**Pull request by YSaxon**
I spent far too long creating a `libdwarf` (https://github.com/davea42/libdwarf-code) formula, after I couldn't find it in homebrew, only to realize once I was done that the formula was already made but called `dwarf-utils`. So this is just a simple pull request to make that alias so this doesn't happen to other people.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please don't use merge commits, they are not compatible with our merge process

**Comment by YSaxon** [comment]
(the doubled commit is because I originally tried to do it on Github.com, but wasn't able to make a proper symlink that way, so then I cloned it locally)

**Comment by YSaxon** [comment]
Ok, so should I clone it fresh and resubmit?

**Comment by SMillerDev** [comment]
Or just drop the merge commit from your branch

**Pull request closed without merging**
