### PR TITLE
Include 'emacs-module.h' header when option is enabled

### PR DESCRIPTION
**Pull request by malthe**
- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
This should be installed by `make install`. Why did Emacs choose not to install it?

**Comment by malthe** [comment]
Oh I see. So it's actually an Emacs issue rather than a homebrew issue.

**Comment by fxcoudert** [comment]
I think so. We install files by running `make install` from Emacs, so if that header is useful, it should be included in that.

**Comment by malthe** [comment]
For future reference – I reported the bug here: https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-11/msg00017.html

**Pull request closed without merging**
