### PR TITLE
git-svn: Separate it from git 

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Separate `git-svn` from `git` to solve #52490. @iMichka @Bo98

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks very much for working on this, @moonfruit.

**Comment by moonfruit** [comment]
```
git-svn:
  * Don't use 'git' as a dependency (it's always available)
```

This is why I do not depend on `git` at first.

**Review by Bo98 — COMMENTED** [review]
I'm quite happy with this approach - thank you!

**Comment by moonfruit** [comment]
Is there something to do about this? @Bo98

**Review by Bo98 — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
