### PR TITLE
gfxutil 1.80b (new formula)

### PR DESCRIPTION
**Pull request by fmunteanu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
New `gfxutil 1.80b` formula added.

### CODE REVIEW

**Comment by fmunteanu** [comment]
As discussed with @vitorgalvao in https://github.com/Homebrew/homebrew-cask/pull/97272, I created a PR here.

**Comment by carlocab** [comment]
Thanks for your PR. The formula in its current form is not acceptable for homebrew/core: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

You will need to modify the formula so that it builds gfxutil from its source tarball at https://github.com/acidanthera/gfxutil/archive/1.80b.tar.gz.

**Comment by fmunteanu** [comment]
Hi @carlocab, to build `gfxutil` an additional framework is required:

```sh
git clone https://github.com/acidanthera/audk edk2
git clone https://github.com/acidanthera/gfxutil gfxutil
cd gfxutil
xcodebuild
```

Can you please provide a link or some short guide how to perform the build from source based on above example? `xcodebuild` will look for `edk2` directory outside the `gfxutil` build directory.

**Comment by carlocab** [comment]
You can use a `resource` block, but `edk2` should be a versioned tarball. If there isn't one, you'll need to specify a specific commit hash: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-install-scripts-that-download-unversioned-things

There are many formulae that use `resource` blocks in homebrew/core. You can `grep` the core repo for many examples.

**Comment by fmunteanu** [comment]
@carlocab I could not find any real example using a non-versioned repo, saw for example I want to use:
https://github.com/acidanthera/audk/tree/872f953262d68a11da7bc2fb3ded16df234b8700

How do I calculate the `sha256` for the resource?

```rb
  resource "edk2" do
    url "https://github.com/acidanthera/audk/tree/872f953262d68a11da7bc2fb3ded16df234b8700"
    sha256 "??"
  end
```

**Comment by carlocab** [comment]
I think this should work:
```
resource "edk2" do
  url "https://github.com/acidanthera/audk.git",
      revision: "872f953262d68a11da7bc2fb3ded16df234b8700"
end
```

**Pull request closed without merging**
