### PR TITLE
graphicsmagick 1.3.32

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/graphicsmagick/1.3.32/bin/gm identify /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.png
/usr/local/Cellar/graphicsmagick/1.3.32/bin/gm identify: abort due to signal 6 (SIGABRT) "Abort"...
Error: graphicsmagick: failed
```

**Comment by chdiza** [comment]
I got the same result with my custom tap version.  I've reported upstream: https://sourceforge.net/p/graphicsmagick/bugs/609/

**Comment by chdiza** [comment]
Upstream verified this is a bug, and have fixed it in master.  The linked bug report points to a commit that can be made into a patch to carry in this formula until they cut a new version.

**Comment by alex** [comment]
I won't be back on a mac to update this PR for a day or two. If no one beats me to it, I'll include this patch then. (If anyone is motivated to do this themselves, you're welcome to steal the PR from me).

**Comment by fxcoudert** [comment]
Patch is here: https://sourceforge.net/p/graphicsmagick/code/ci/f30492f40f78d867b43422215057dd21de4ba447/tree/coders/png.c?diff=95c4711e8beecc5f342e38f5b08ece60f54c51e7

**Comment by alex** [comment]
I have not had time to finish this.

**Pull request closed without merging**
