### PR TITLE
clojure 1.8.0.174, 1.9.0-beta1.229 (devel)

### PR DESCRIPTION
**Pull request by puredanger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks, @puredanger! By the way, in the last 30 days, there have been 862 install-on-request events and 1,130 install events. :)

**Comment by ilovezfs** [comment]
@puredanger is this expected?

```
iMac-TMP:~ joe$ clj
Downloading: org/clojure/clojure/1.8.0/clojure-1.8.0.pom from https://repo1.maven.org/maven2/
Downloading: org/sonatype/oss/oss-parent/7/oss-parent-7.pom from https://repo1.maven.org/maven2/
Downloading: org/clojure/clojure/1.8.0/clojure-1.8.0.jar from https://repo1.maven.org/maven2/
```

It seems like some of the jars were missing if it's having to fetch them.

**Comment by puredanger** [comment]
Yes, that's how all Maven-based tools work (they download and cache Java dependency libs in the ~/.m2/repository). This is exactly the same as other Maven-based formulae like `maven`, `leiningen` (actually mentions this explicitly in the caveats), `boot-clj`, `gradle`, etc. The ~/.m2/repository is a cache - you can delete the ~/.m2 directory and Maven-based tools will recreate as needed. Because Maven repos are append-only versioned stores, typically users never explicitly delete or manage the contents of those directories; they just rely on things being downloaded and cached in that directory over time.

All dependencies needed to run the `clj`/`clojure` script itself *are* included in the jar inside the tar file (including the files you see getting downloaded here). But `clj` is itself a tool that lets the user specify dependencies to use in their Clojure REPL. The default configuration specifies to include clojure 1.8.0 as the default dependency and that's what triggers the download and management of the clojure jar here (on behalf of the user).

**Comment by puredanger** [comment]
You can see the exact same behavior for example with:

```
rm -rf ~/.m2
brew install leiningen
lein new foo
cd foo
lein repl
```

**Comment by ilovezfs** [comment]
>The default configuration specifies to include clojure 1.8.0 as the default dependency and that's what triggers the download and management of the clojure jar here (on behalf of the user).

This seems like weird default behavior if we already have the file.

**Comment by puredanger** [comment]
The difference here is that the deps we require to build the classpath are all included in the script installation - they thus have a lifecycle managed by brew and handled during upgrade or removal, etc.

The original version of the scripts didn't do this - it relied on downloading and caching dependencies via the standard Maven APIs. You requested that we change it to include all the necessary dependencies so brew could manage the deps for the script itself.

Either way is possible, but I feel like you are now objecting to the very thing that you asked us to change, which required a fair amount of work. I feel like the current implementation is both being a good brew citizen and being a good Maven citizen so I'm happy with how it works now.

**Comment by ilovezfs** [comment]
@puredanger no worries. I'm not actually asking you to change anything.

**Pull request merged**
