### PR TITLE
node@6 6.12.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Alhadis** [comment]
I'm literally about to submit a PR for v9.1, what the hell :p

**Comment by ilovezfs** [comment]
@Alhadis we're not doing 9.0 or 9.1 yet due to npm being incompatible.

**Comment by Alhadis** [comment]
... yeah, I just noticed why the local `--build-from-source` failed. :\

~~~
npm info using node@v9.1.0
npm verb npm-session c1643d546911d59a
npm sill install loadCurrentTree
npm sill install readGlobalPackageData
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0)…
~~~

*swears incomprehensibly in Perl*

**Comment by Alhadis** [comment]
@ilovezfs Is there an issue reported upstream anywhere? Wouldn't mind tracking progress on this.

**Comment by ilovezfs** [comment]
@Alhadis 

https://github.com/nodejs/node/issues/16649
https://github.com/npm/npm/issues/19019
https://github.com/npm/npm/pull/19025

**Pull request closed without merging**
