### PR TITLE
thundersvm 0.3.3 (new formula)

### PR DESCRIPTION
**Pull request by ankane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

A few notes:

- It currently requires `gcc` to build. I'm following up with the authors to see if they'll support Clang + `libomp`.
- Homebrew's `std_cmake_args` sets `DCMAKE_CXX_FLAGS_RELEASE` which causes `-O3` to be lost. This greatly reduces performance, which is why it is added back.
- There's no `make install`.

### CODE REVIEW

**Comment by ankane** [comment]
Switched to Clang, but seeing odd behavior specifically when installed in the Homebrew environment. The library has issues when reading input (can't parse some files, only detects some lines in other files). When compiled outside of Homebrew with the exact same `cmake` command, there isn't an issue. Do any Homebrew maintainers know of similar behavior with other libraries?

**Comment by Bo98** [comment]
Homebrew does inject some added arguments to the compiler. You can look at the *.cc files in ~/Library/Logs/Homebrew/thundersvm.

**Comment by SMillerDev** [comment]
That's a whole lot of patching you're doing in the formula. Do all of the changes have an issue or pull request created upstream? Because homebrew formula shouldn't just start replacing cmake file content.

**Comment by ankane** [comment]
Thanks @Bo98 and @SMillerDev. I think the issue I mentioned above is outside my expertise, so going to close. If anyone tries this in the future, clang support was accepted, which solves one of the two patches (https://github.com/Xtra-Computing/thundersvm/pull/185). There's also a PR for `make install` (https://github.com/Xtra-Computing/thundersvm/pull/184), but it needs additional work before it can be merged.

**Pull request closed without merging**
