### PR TITLE
openfast 3.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]

**Comment by nandahkrishna** [comment]
patch doesn't apply, the pull request has been merged and is included in `3.0.0`: [this commit](https://github.com/OpenFAST/openfast/tree/bf2fdc55eb18503cd08ebadef1d0aed10202bbc8).

**Comment by chenrui333** [comment]
Look like the 11-arm64 build still does not work, do we have any upstream tracker for this?

**Comment by carlocab** [comment]
> Look like the 11-arm64 build still does not work, do we have any upstream tracker for this?

I checked, and it doesn't look like it.

**Review by carlocab — DISMISSED** [review]
Doesn't have an ARM bottle, so ARM failure shouldn't block this. (The comment for the patch--which I wrote--is mistaken 😅)

**Comment by carlocab** [comment]
We should get rid of this line:

https://github.com/Homebrew/homebrew-core/blob/5c74b4363bf9545fdfc00e115e43e2ab346085da/Formula/openfast.rb#L28

It's a no-op, since the `cc` shim strips out `-g` flags.

**Comment by chenrui333** [comment]
> Doesn't have an ARM bottle, so ARM failure shouldn't block this. (The comment for the patch--which I wrote--is mistaken 😅)

noted, no worries. ;)

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
