### PR TITLE
pillow: fix build failure when openjpeg is installed

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
when did this sneak into core lol

**Comment by DomT4** [comment]
10 hours ago 🙈. https://github.com/Homebrew/homebrew-core/pull/17341

**Comment by ilovezfs** [comment]
Yeah I'm not so sure we're going to be keeping this. This had been considered and rejected multiple times.

**Comment by DomT4** [comment]
No disagreement from me if you set 🔥 to the formula. Just figured I'd fix the known & silly `openjpeg` issue whilst I remembered.

**Comment by DomT4** [comment]
Whatever you decide, let me know what to do with https://github.com/Homebrew/brew/pull/3102 as well.

**Comment by ilovezfs** [comment]
It's now gone: https://github.com/Homebrew/homebrew-core/pull/17357.

**Pull request closed without merging**
