### PR TITLE
gitbucket 4.32.0: issue checksum (SHA256)

### PR DESCRIPTION
**Pull request by TakayunDev**
fix checksum. current checksum is invalid.

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Can upstream (gitbucket) confirm that they moved the release tag (which they really should not have done)?

**Comment by TakayunDev** [comment]
#42883 is commited at `2019-08-07T02:57:57Z`, but gitbucket 4.32.0 latest release commited at `2019-08-07T13:55:45Z`.
So, I consider that upstream, after #42883, would have been changed release tag.
gitbucket 4.32.0 release is here: https://github.com/gitbucket/gitbucket/releases/tag/4.32.0

**Comment by SMillerDev** [comment]
You'd need to ask gitbucket to confirm that this is intentional though

**Comment by TakayunDev** [comment]
I could confirm that gitbucket tag change.
Please refer to: https://gitter.im/gitbucket/gitbucket?at=5d511e64bb5364334c1843eb, August 12, 2019 5:08 PM

**Pull request merged**
