### PR TITLE
edencommon fb303 fbthrift fizz folly wangle watchman 2023.04.10.00

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Porkepix** [comment]
Dupe of https://github.com/Homebrew/homebrew-core/pull/127965 and I believe since the dependents testing have their own 90 minutes timer, it doesn't need long builds anymore.

**Comment by ZhongRuoyu** [comment]
> Dupe of #127965 and I believe since the dependents testing have their own 90 minutes timer, it doesn't need long builds anymore.

Actually, we are almost always hitting the timeout on Intel Big Sur, even without testing deps. For example, https://github.com/Homebrew/homebrew-core/actions/runs/4656022796/jobs/8239306351 finished in 1h 31m 42s.

**Comment by chenrui333** [comment]
I dont know why I did not find the other PR when I created this one.

> https://github.com/Homebrew/homebrew-core/actions/runs/4656022796/jobs/8239306351 finished in 1h 31m 42s.

On the edge 😅

**Comment by Porkepix** [comment]
> > Dupe of #127965 and I believe since the dependents testing have their own 90 minutes timer, it doesn't need long builds anymore.
> 
> Actually, we are almost always hitting the timeout on Intel Big Sur, even without testing deps. For example, [Homebrew/homebrew-core/actions/runs/4656022796/jobs/8239306351](https://github.com/Homebrew/homebrew-core/actions/runs/4656022796/jobs/8239306351) finished in 1h 31m 42s.

Testing deps doesn't really matter anymore here: since this was split into two different jobs, first-party tests have a 90 minutes timer, and dependencies testing earn another new 90 minutes timer, as opposed to a single timer for both jobs before. Unless timer gets reduced for every jobs in the future.

**Comment by carlocab** [comment]
> Actually, we are almost always hitting the timeout on Intel Big Sur, even without testing deps. For example, https://github.com/Homebrew/homebrew-core/actions/runs/4656022796/jobs/8239306351 finished in 1h 31m 42s.

Generally finishing in 1:33 is safe. As long as the 1:30 mark is hit inside the steps that have `if: always()` we should be good.

**Comment by ZhongRuoyu** [comment]
Yeah, I just didn't want to risk a rerun because I've seen jobs getting killed while building `watchman`.

**Pull request closed without merging**
