### PR TITLE
wildfly-as 17.0.0.Final

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zbeekman** [comment]
Any chance we could get better tests for this?

**Comment by jasontedor** [comment]
@zbeekman I think that we can get a little bit better testing here but not much beyond "does this thing even turn on?". Wildfly is an application server, it would require quite a lot of effort to get real functional tests here. Is it enough that we know Wildfly starts and responds to a main request, as I've suggested in #40883? We can come back to this PR after we have reached a decision there?

**Comment by zbeekman** [comment]
As I mentioned in my other PR review: The test here should do more than just dump a help or version message to stdout. If it's client/server software checking logs or stdout/stderr during a graceful exception (such as a failure to authenticate, or a failure to connect to a non-existant server at a dummy uri) is acceptable too. Thanks for adding the test.

I'd like to combine these two PRs, if possible, so that we only need to merge one.

**Comment by jasontedor** [comment]
@zbeekman Thanks for your feedback. I pushed a commit with the suggestions that you made, made the process for terminating Wildfly more robust, and cherry-picked the version bump over to here.

**Comment by jasontedor** [comment]
Superseded by #40883

**Comment by chenrui333** [comment]
Sounds good, thanks!

**Pull request closed without merging**
