### PR TITLE
rpki-client 8.3

### PR DESCRIPTION
**Pull request by geeohgeegeeoh**
Version 8.3 released

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  output-ometric.c:131:16: error: use of undeclared identifier 'HOST_NAME_MAX'
          char hostname[HOST_NAME_MAX + 1];
                        ^
  1 error generated.
```

**Comment by carlocab** [comment]
Needs
```c
#define __USE_POSIX
```
🤷

**Comment by geeohgeegeeoh** [comment]
This didn't help. I added CPPFLAGS -D__USE_POSIX=1 to the configure call
and I can see in the fail logs that the #define is being passed into clang.

Sorry, I am unsure how to proceed.

**Comment by carlocab** [comment]
Huh, guess that macro no longer works. Weird. Apologies for misleading you!

**Comment by geeohgeegeeoh** [comment]
Looks like -DHOST_NAME_MAX=_POSIX_HOST_NAME_MAX will do the trick

-G

**Comment by job** [comment]
Upstream now provides a workaround for this, but tagging a new release hasn’t been scheduled yet.

https://github.com/rpki-client/rpki-client-portable/commit/65e5d4b99131b7cc8091ea222b70d24ec04fac60

**Review by carlocab — APPROVED** [review]
Thanks!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
