### PR TITLE
step 0.9.0

### PR DESCRIPTION
**Pull request by dopey**
shasums have changed - super weird

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please confirm with upstream that the change of checksum is intended, not malicious.

**Comment by dopey** [comment]
This checksum change is intended and not malicious. 

We were using the source tarball that github uploads by default with each release and did not know that those artifacts have a habit of changing SHAs. For future releases we have updated our build process and homebrew formula to use our own uploaded tarballs.

**Comment by dopey** [comment]
Is there anything else I should do on our end to clear this update? I can also push a 0.9.1 release if that would be easier. Lmk, thanks.

**Comment by dopey** [comment]
Pushing 0.9.1 release with updated git archive location and matching SHAs.

**Pull request closed without merging**
