### PR TITLE
libupnp 1.10.1

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
URL is unreachable. Can use this: https://github.com/mrjimenez/pupnp/archive/release-1.10.1.tar.gz instead.

**Comment by chenrui333** [comment]
The url seems OK now.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by zachauten** [comment]
CI failed because of audit. The project's homepage is also currently down, so I will push the fix once that's back online so audit doesn't fail.

**Comment by Bo98** [comment]
The behaviour of downloads.sourceforge.net depends a little on where you look at it. If you open it in a web browser it will redirect to some countdown download page. But if it is accessed via `curl` (and by extension `brew`) it redirects to a direct download that is picked by geolocation.

https://downloads.sourceforge.net/project/pupnp/pupnp/libupnp-1.10.1/libupnp-1.10.1.tar.bz2

**Comment by zachauten** [comment]
@Bo98 Thanks!

**Comment by dawidd6** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by zachauten** [comment]
@BrewTestBot test this please.

**Comment by zachauten** [comment]
@BrewTestBot test this please.

**Comment by alebcay** [comment]
Looks like several formulae need revision bumps:
```
djmount
gmediaserver
mpd
```

**Comment by zachauten** [comment]
@alebcay That makes sense, thanks! I haven’t done much stuff in core yet; Trying to get more experience with it. 

Do maintainers even bump libraries if reverse dependencies aren’t being updated?

**Comment by alebcay** [comment]
Generally, we don't bump any revision numbers unless there are linkage issues. Ideally, dependents dynamically link to unversioned copies of their dependencies (or they link a way that doesn't break on every update, e.g. link to dependencies that are versioned on API/ABI, not just version number).

Some dependency relationships, on the other hand, are more tightly coupled (every update of `nginx` requires a bump of `passenger`).

**Pull request closed without merging**
