### PR TITLE
scipy: migrate to `python@3.13`

### PR DESCRIPTION
**Pull request by chenrui333**
eigenpy: migrate to `python@3.13`

### CODE REVIEW

**Comment by cho-m** [comment]
This needs to be done with all its dependents. May need to remove the audit exception to see mixed dependency tree issues.

**Comment by chenrui333** [comment]
there is some issue with some formula to do py3.13 like https://github.com/scikit-image/scikit-image/pull/7565

**Comment by cho-m** [comment]
Fedora may be a good reference for issues since they've been testing/fixing Python 3.13 since alpha.

**Comment by branchvincent** [comment]
Migrated in #194577

**Pull request closed without merging**
