### PR TITLE
vault 1.14.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — APPROVED** [review]
Confirmed that license is still MPL 2.0.

**Comment by chenrui333** [comment]
both 13 and 14 bottles are not built due to 

```
2023-09-27T05:21:52.589+0100 [INFO]  core: successful mount: namespace="" path=secret/ type=kv version=""
  WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
  and starts unsealed with a single unseal key. The root token is already
  authenticated to the CLI, so you can immediately begin using Vault.
  
  You may need to set the following environment variables:
  
      $ export VAULT_ADDR='http://127.0.0.1:51825/'
  
  The unseal key and root token are displayed below in case you want to
  seal/unseal the Vault or re-authenticate.
  
  Unseal Key: cioNo1mDQpsIbsAjITBR18aWP0Y5VoleMjO0DtbhfEg=
  Root Token: hvs.wHqxasLEnWJFeSXDkgnou6qX
  
  Development mode should NOT be used in production installations!
  
  Killing child processes...
```

**Comment by Bo98** [comment]
Done.

**Comment by p-linnane** [comment]
All bottles built correctly this time around.

**Comment by chenrui333** [comment]
thanks @Bo98, @p-linnane!!

**Pull request merged**
