### PR TITLE
hdf5: remove options.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Fixes https://github.com/Homebrew/homebrew-core/issues/31510.

### CODE REVIEW

**Comment by tschoonj** [comment]
This is a bad idea IMHO as it enforces all HDF5 libraries to get build with MPI support which is unnecessary for the vast majority of users and will break a lot of software as they expect the serial libraries to get linked in which have a different name.

If you really insist on removing the options here, better is to remove MPI support altogether.

**Comment by tschoonj** [comment]
I am wrong about the different naming scheme for the MPI enabled libraries, sorry about that.

But I still think it's a bad idea to enforce MPI 😄 Also since you removed the C++ bindings, some formulas will no longer build, as shown in the failing tests.

**Comment by MikeMcQuaid** [comment]
> This is a bad idea IMHO as it enforces all HDF5 libraries to get build with MPI support which is unnecessary for the vast majority of users and will break a lot of software as they expect the serial libraries to get linked in which have a different name.

Ok, will change, thanks.



> If you really insist on removing the options here

Please see https://github.com/Homebrew/homebrew-core/issues/31510 and the 1.9.0 release notes.

**Comment by MikeMcQuaid** [comment]
Will address `libbi` in a follow-up PR.

**Pull request merged**
