### PR TITLE
cdk8s 0.27.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
Why those python resources were added?

**Comment by dtrodrigues** [comment]
`bump-formula-pr` falls back to searching PyPI for the formula name if it doesn't find a PyPI url as the stable URL: https://github.com/Homebrew/brew/blob/36c7a3f27fb15a346d6238eb2a0da9d25a2070ab/Library/Homebrew/utils/pypi.rb#L64

```
 $ brew bump-formula-pr cdk8s --url https://registry.npmjs.org/cdk8s-cli/-/cdk8s-cli-0.27.0.tgz --no-browse
==> Downloading https://registry.npmjs.org/cdk8s-cli/-/cdk8s-cli-0.27.0.tgz
######################################################################## 100.0%
Warning: Cannot verify integrity of cdd39a2eaffb524e5c7072f99efec79790b551b145b479c05757b8e2730ff19b--cdk8s-cli-0.27.0.tgz
A checksum was not provided for this resource.
For your reference the SHA-256 is: 77010866c1e04f3c4ef09bd9076b3adb32c8585f4580acebf7599d2834be861b
==> replace /https:\/\/registry\.npmjs\.org\/cdk8s\-cli\/\-\/cdk8s\-cli\-0\.26\.0\.tgz/ with "https://registry.npmjs.org/cdk8s-cli/-/cdk8s-cli-0.27.0.tgz"
==> replace "d4cd0eca893011420765bea1aed6a198a1f21b09d9650223dac33c17ed5eb4fa" with "77010866c1e04f3c4ef09bd9076b3adb32c8585f4580acebf7599d2834be861b"
==> Retrieving PyPI dependencies for "cdk8s==0.27.0"...
==> Getting PyPI info for "attrs==19.3.0"
==> Getting PyPI info for "cattrs==1.0.0"
==> Getting PyPI info for "constructs==2.0.2"
==> Getting PyPI info for "jsii==1.10.0"
==> Getting PyPI info for "publication==0.0.3"
==> Getting PyPI info for "python-dateutil==2.8.1"
==> Getting PyPI info for "six==1.15.0"
==> Getting PyPI info for "typing-extensions==3.7.4.2"
==> Updating resource blocks
```

This shouldn't happen in this case. This either needs to be added to the PyPI blocklist or we might not want to search PyPI unless a Python URL is passed in. @Rylan12 what do you think?

**Comment by Rylan12** [comment]
This feels like a special case because the formula happens to be available on PyPI even though we don't use that distribution. I think I would just add it to the blocklist.

The idea for having the fallback was that there were some PyPI formulae that needed resources but the url provided was an e.g. GitHub url rather than the `files.pythonhosted.org` one. An example is [`ansible`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible.rb) (although, `ansible` has since been added to blocklist as well). Without knowing exactly how many formulae this applies to, I think it's worth keeping the fallback. If we find that lots of formulae are having this issue, we should probably revisit, though, as having a massive blocklist isn't great.

**Comment by dtrodrigues** [comment]
I don't have any hard numbers, but it does seem like in a non-trivial number of the of the cases where GitHub/other URLs are used even when it's on PyPI as well, there's some reason we don't use the PyPI one. Maybe an alternative could be to migrate all the URLs that work on PyPI over to the `pythonhosted` URL and use that as as trigger to bump the Python resources. 

Either way, I agree that adding `cdk8s` to the blocklist for now seems appropriate until we get a sense of formulae name name collisions/packaging issues occurring on PyPI being a prevailing theme.

**Comment by Rylan12** [comment]
> Maybe an alternative could be to migrate all the URLs that work on PyPI over to the `pythonhosted` URL and use that as as trigger to bump the Python resources.

I think that we should try to avoid having the `resource` blocks if we can so this might not be any better. 

In terms of whether to fall back, I don't have any strong feelings. If you think it's worth removing the fallback that would be fine. If that's what's done, we may want to consider adding an e.g. `--force` flag which will still include the fallback. That way, `update-python-resources` can still be used on these formulae in the future for whatever reason. That's just my gut feeling.

**Comment by dtrodrigues** [comment]
Closing due to test failure on 10.13 and 10.14.

**Pull request closed without merging**
