### PR TITLE
gradle: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by Amar1729**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See #75943

### CODE REVIEW

**Comment by carlocab** [comment]
```
❯ sha256sum *.tar.gz
d057a9591280d4ce61d6ba104b968d13412ca13cca3c8e217c2535f088beb43f  gradle--7.0.arm64_big_sur.bottle.tar.gz
d4b8ba944ac2afa00f6c571e8233b906dd3ae17a5cf7cc56a6712651d738fa9c  gradle--7.0.big_sur.bottle.tar.gz
d4b8ba944ac2afa00f6c571e8233b906dd3ae17a5cf7cc56a6712651d738fa9c  gradle--7.0.catalina.bottle.tar.gz
1686a9b7b275d1cd853ea5d2533c1113fa108e19d72afaa3caa7c7e713dc0d95  gradle--7.0.mojave.bottle.tar.gz
```
The Mojave bottle differing should be fixed by https://github.com/Homebrew/brew/pull/11253. The ARM bottle diff probably comes from the use of Java 11 on ARM.

**Comment by Amar1729** [comment]
just verified, it's due do arm using java 11 - 
```
> diff -r gradle--7.0.arm64_big_sur.bottle/ gradle--7.0.big_sur.bottle/

diff -r gradle--7.0.arm64_big_sur.bottle/gradle/7.0/bin/gradle gradle--7.0.big_sur.bottle/gradle/7.0/bin/gradle
2c2
< JAVA_HOME="${JAVA_HOME:-@@HOMEBREW_PREFIX@@/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home}" exec "@@HOMEBREW_CELLAR@@/gradle/7.0/libexec/bin/gradle"  "$@"
---
> JAVA_HOME="${JAVA_HOME:-@@HOMEBREW_PREFIX@@/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" exec "@@HOMEBREW_CELLAR@@/gradle/7.0/libexec/bin/gradle"  "$@"
```

**Comment by Amar1729** [comment]
After rebuild:

```
> sha256sum *.tar.gz

e0ed8d98ce5c603dfbab5dd45dcbc423a02ccaef2a0cd4da73d4bbb2d0528f06  gradle--7.0.arm64_big_sur.bottle.tar.gz
543d05adec995a96c1ca38fd9b291cf0b47db6a9d036836a34f09e6de9a7cff5  gradle--7.0.big_sur.bottle.tar.gz
543d05adec995a96c1ca38fd9b291cf0b47db6a9d036836a34f09e6de9a7cff5  gradle--7.0.catalina.bottle.tar.gz
543d05adec995a96c1ca38fd9b291cf0b47db6a9d036836a34f09e6de9a7cff5  gradle--7.0.mojave.bottle.tar.gz
```

and the difference is java 11:
```
> diff -r gradle--7.0.arm64_big_sur.bottle gradle--7.0.big_sur.bottle

diff -r gradle--7.0.arm64_big_sur.bottle/gradle/7.0/bin/gradle gradle--7.0.big_sur.bottle/gradle/7.0/bin/gradle
2c2
< JAVA_HOME="${JAVA_HOME:-@@HOMEBREW_PREFIX@@/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home}" exec "@@HOMEBREW_CELLAR@@/gradle/7.0/libexec/bin/gradle"  "$@"
---
> JAVA_HOME="${JAVA_HOME:-@@HOMEBREW_PREFIX@@/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" exec "@@HOMEBREW_CELLAR@@/gradle/7.0/libexec/bin/gradle"  "$@"
```

**Comment by Bo98** [comment]
This might be improved when we clean up the ARM patches in the OpenJDK 16 PR. I'll need to have a look at the status of that but we should hopefully be able to get it all on the same version.

**Pull request closed without merging**
