### PR TITLE
python@3.9: do not symlink as pip3 and wheel3

### LINKED ISSUE #62911: Installation of Python 3.8 and Python 3.9 side by side breaks pip version.
# Bug report

## What you were trying to do (and why)

We are generating MacOS VMs for CI. We install `python@3.8` formula. Then we install some other tools via brew and those tools bring `python@3.9` as dependency to machine.

As a result, we have inconsistent python3 and pip3 on machine:
- `python3` from `python@3.8` formula
- `pip3` from `python@3.9` formula

It causes issues because If you install any packages via `pip3 install`, they won't be available via `python3`.

See related issues:
- https://github.com/actions/virtual-environments/issues/1818
- https://github.com/actions/virtual-environments/issues/1819

## Step-by-step reproduction instructions

Repro steps:
1) Take clean MacOS (10.14, 10.15 or 11.0)
2) Install brew
3) run `brew install python@3.8`
4) run `brew install python@3.9`
5) Run `python3 --version` and `pip3 --version`

## What happened (include command output)
Actually, we have the following output:
```
Mac-1972:~ runner$ python3 --version
Python 3.8.6
Mac-1972:~ runner$ pip3 --version
pip 20.2.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Mac-1972:~ runner$ ls -la /usr/local/bin/python3
lrwxr-xr-x  1 runner  admin  38 Oct 15 01:01 /usr/local/bin/python3 -> ../Cellar/python@3.8/3.8.6/bin/python3
Mac-1972:~ runner$ ls -la /usr/local/bin/pip3
lrwxr-xr-x  1 runner  admin  35 Oct 15 01:02 /usr/local/bin/pip3 -> ../Cellar/python@3.9/3.9.0/bin/pip3
```

It means that Python3 is used from `python@3.8` formula. Pip3 is used from `python@3.9` formula. Those versions are not compatible.
If you install any packages via `pip3 install`, they won't be available via `python3`

## What you expected to happen
I am expecting that `python3` version and `pip3` will be consistent.

## Possible workaround
We have found a workaround for this issue but it definitely looks like an issue with `python` formula that should be fixed:
```
brew install python@3.8
brew install python@3.9
brew unlink python@3.9
brew unlink python@3.8
brew link python@3.8
```

### PR DESCRIPTION
**Pull request by fxcoudert**
Fixes https://github.com/Homebrew/homebrew-core/issues/62911

### CODE REVIEW

**Comment by SMillerDev** [comment]
I think this warrants a revbump

**Comment by fxcoudert** [comment]
Revision-bumping sadly will not remove the previously created symlinks, will it?

**Comment by SMillerDev** [comment]
I'm not sure about that, but at least it'll make sure everyone gets the fix. Which was what I was more worried about.

**Comment by iMichka** [comment]
Maybe if you revbump python@3.8 to override these symlinks?

Just a note: last time we made a Python migration, we were bitten by a similar issue if I remember well. But it's hard to test upfront to avoid this mistake.

**Comment by SMillerDev** [comment]
Maybe we could make an audit/rubocop to make sure only one formula has these? @MikeMcQuaid probably has a better idea on how feasible that would be.

**Comment by MikeMcQuaid** [comment]
> Maybe if you revbump python@3.8 to override these symlinks?

Yes, this could work.



> Maybe we could make an audit/rubocop to make sure only one formula has these? @MikeMcQuaid probably has a better idea on how feasible that would be.

Specifying "only one formula" probably isn't feasible. Having `brew audit` check "no python formula except PYTHON_ALLOWED_FORMULA has these symlinks" seems sensible.

Something like https://github.com/Homebrew/brew/blob/7f422af7897f4f58cc84079ccb6f1d25ac66a759/Library/Homebrew/dev-cmd/audit.rb#L985-L994 will allow checking this only if the formula is installed. I'd suggest this be done before this PR is merged.

**Comment by fxcoudert** [comment]
> I'd suggest this be done before this PR is merged

The original reporter's use case (CI testing) would benefit from merging this as-is, and looking at systematic improvements laters.

**Comment by SMillerDev** [comment]
It would only affect those that build from source right? Or do you plan on overwriting the bottles?

**Comment by fxcoudert** [comment]
My plan was overwriting the bottles: isn't that what the merging bot does, when there is no revision?

**Comment by SMillerDev** [comment]
I don't think it does.

**Comment by fxcoudert** [comment]
@SMillerDev see for example this PR: https://github.com/Homebrew/homebrew-core/pull/58881
It was auto-merged, does not have a revision bump, and lead to two commits: https://github.com/Homebrew/homebrew-core/commit/4f17008e56aa1ddf7bbdde192b0854565bf0e9e0 and https://github.com/Homebrew/homebrew-core/commit/731f2b10fb01d715688f04f1cdc6c28adeb7f174

**Comment by MikeMcQuaid** [comment]
> The original reporter's use case (CI testing) would benefit from merging this as-is, and looking at systematic improvements later. Without revision bump, it will only affect new users and CI systems, which is still important.

My issue is: here we are several days later and no-one has opened an issue or a PR to track this work. We've got to get better at adding regression tests like this or things get forgotten and will repeatedly reoccur in future. This work should block just getting a fix out there and is definitely more important than e.g. migrating more formulae.

**Comment by fxcoudert** [comment]
> here we are several days later

Testing finished about 24 hours ago, and merging was yesterday.

> no-one has opened an issue or a PR to track this work

I have not forgotten about it, even though I have not filed an issue, this tab is open in my browser because I know it's in my to-do list. All help is welcome, especially to write an audit, as I'm totally ignorant of the brew codebase.

Also, there already is an open issue, which was purposely not closed, at https://github.com/Homebrew/homebrew-core/issues/62911

**Comment by fxcoudert** [comment]
And now there is a tracking issue for the brew side: https://github.com/Homebrew/brew/issues/8949

**Comment by MikeMcQuaid** [comment]
@fxcoudert Thanks for opening the tracking issue 👍🏻

**Pull request closed without merging**
