### PR TITLE
haskell-stack: depend on `llvm` for build on ARM

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/runs/2775561424?check_suite_focus=true#step:6:604

### CODE REVIEW

**Comment by aryairani** [comment]
CI failing because there's no 10.14 bottle for `ghc`

**Comment by Bo98** [comment]
Why does x86_64 work with Apple Clang and ARM64 doesn't?

**Comment by carlocab** [comment]
GHC seems to occasionally need an LLVM backend on ARM.

**Comment by Bo98** [comment]
Oh right, I see now - full ARM support isn't actually released yet. The LLVM dependency can be dropped with GHC 9.2.1, due soon.

> Not really clear on whether it should be a hard runtime dep.

Runtime in the `ghc` formula.

**Comment by carlocab** [comment]
This is no-op on the Intel nodes, so I'm merging this then killing the tests. Will dispatch a bottle separately.

**Pull request merged**
