### PR TITLE
latexindent 3.8.2 (new formula)

### PR DESCRIPTION
**Pull request by gpanders**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vladimyr** [comment]
Hi @gpanders 👋 

you are seeing test failures because not all required dependencies were listed/installed. It is a bit tricky to convert the complete dependency graph of Perl package to formula resources and there are also special cases requiring custom compilation procedures. To save you some time I jumped over all the hurdles and created the working version. In order to get there you'll need to apply the following diff:
```diff
diff --git a/Formula/latexindent.rb b/Formula/latexindent.rb
index 0492afe2f6..f1e806fc35 100644
--- a/Formula/latexindent.rb
+++ b/Formula/latexindent.rb
@@ -1,14 +1,44 @@
 class Latexindent < Formula
   desc "Add indentation to LaTeX files"
-  homepage "https://github.com/cmhughes/latexindent.pl"
+  homepage "https://www.ctan.org/pkg/latexindent"
   url "https://github.com/cmhughes/latexindent.pl/archive/V3.8.2.tar.gz"
   sha256 "a134e27d56b7daee2bea37563424f996fc559bc8019e92213261b25cdb84a688"
 
   depends_on "perl"
 
-  resource "YAML::Tiny" do
-    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.73.tar.gz"
-    sha256 "bc315fa12e8f1e3ee5e2f430d90b708a5dc7e47c867dba8dce3a6b8fbe257744"
+  resource "B::Hooks::EndOfScope" do
+    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/B-Hooks-EndOfScope-0.24.tar.gz"
+    sha256 "03aa3dfe5d0aa6471a96f43fe8318179d19794d4a640708f0288f9216ec7acc6"
+  end
+
+  resource "Class::Data::Inheritable" do
+    url "https://cpan.metacpan.org/authors/id/T/TM/TMTM/Class-Data-Inheritable-0.08.tar.gz"
+    sha256 "9967feceea15227e442ec818723163eb6d73b8947e31f16ab806f6e2391af14a"
+  end
+
+  resource "Devel::GlobalDestruction" do
+    url "https://cpan.metacpan.org/authors/id/H/HA/HAARG/Devel-GlobalDestruction-0.14.tar.gz"
+    sha256 "34b8a5f29991311468fe6913cadaba75fd5d2b0b3ee3bb41fe5b53efab9154ab"
+  end
+
+  resource "Devel::StackTrace" do
+    url "https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.04.tar.gz"
+    sha256 "cd3c03ed547d3d42c61fa5814c98296139392e7971c092e09a431f2c9f5d6855"
+  end
+
+  resource "Dist::CheckConflicts" do
+    url "https://cpan.metacpan.org/authors/id/D/DO/DOY/Dist-CheckConflicts-0.11.tar.gz"
+    sha256 "ea844b9686c94d666d9d444321d764490b2cde2f985c4165b4c2c77665caedc4"
+  end
+
+  resource "Eval::Closure" do
+    url "https://cpan.metacpan.org/authors/id/D/DO/DOY/Eval-Closure-0.14.tar.gz"
+    sha256 "ea0944f2f5ec98d895bef6d503e6e4a376fea6383a6bc64c7670d46ff2218cad"
+  end
+
+  resource "Exception::Class" do
+    url "https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.44.tar.gz"
+    sha256 "33f3fbf8b138d3b04ea4ec0ba83fb0df6ba898806bcf4ef393d4cafc1a23ee0d"
   end
 
   resource "File::HomeDir" do
@@ -21,9 +51,9 @@ class Latexindent < Formula
     sha256 "b79dc2244b2d97b6f27167fc3b7799ef61a179040f3abd76ce1e0a3b0bc4e078"
   end
 
-  resource "Unicode::GCString" do
-    url "https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2019.001.tar.gz"
-    sha256 "486762e4cacddcc77b13989f979a029f84630b8175e7fef17989e157d4b6318a"
+  resource "Log::Dispatch" do
+    url "https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Log-Dispatch-2.69.tar.gz"
+    sha256 "58624c0a0c4c620873efb7ce2f11dde55fa2e24c22be2551f548ff3624585277"
   end
 
   resource "Log::Log4perl" do
@@ -31,15 +61,120 @@ class Latexindent < Formula
     sha256 "b739187f519146cb6bebcfc427c64b1f4138b35c5f4c96f46a21ed4a43872e16"
   end
 
-  resource "Log::Dispatch::File" do
-    url "https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Log-Dispatch-2.69.tar.gz"
-    sha256 "58624c0a0c4c620873efb7ce2f11dde55fa2e24c22be2551f548ff3624585277"
+  resource "MIME::Charset" do
+    url "https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/MIME-Charset-1.012.2.tar.gz"
+    sha256 "878c779c0256c591666bd06c0cde4c0d7820eeeb98fd1183082aee9a1e7b1d13"
+  end
+
+  resource "MRO::Compat" do
+    url "https://cpan.metacpan.org/authors/id/H/HA/HAARG/MRO-Compat-0.13.tar.gz"
+    sha256 "8a2c3b6ccc19328d5579d02a7d91285e2afd85d801f49d423a8eb16f323da4f8"
+  end
+
+  resource "Mac::SystemDirectory" do
+    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/Mac-SystemDirectory-0.13.tar.gz"
+    sha256 "8730740e4ff3ea4812139b0787dbd1b544e093a08218d908071629b70fde3684"
+  end
+
+  resource "Module::Build" do
+    url "https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-0.4231.tar.gz"
+    sha256 "7e0f4c692c1740c1ac84ea14d7ea3d8bc798b2fb26c09877229e04f430b2b717"
+  end
+
+  resource "Module::Implementation" do
+    url "https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Module-Implementation-0.09.tar.gz"
+    sha256 "c15f1a12f0c2130c9efff3c2e1afe5887b08ccd033bd132186d1e7d5087fd66d"
+  end
+
+  resource "Module::Runtime" do
+    url "https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Module-Runtime-0.016.tar.gz"
+    sha256 "68302ec646833547d410be28e09676db75006f4aa58a11f3bdb44ffe99f0f024"
+  end
+
+  resource "Package::Stash" do
+    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-0.38.tar.gz"
+    sha256 "c58ee8844df2dda38e3bf66fdf443439aaefaef1a33940edf2055f0afd223a7f"
+  end
+
+  resource "Package::Stash::XS" do
+    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-XS-0.29.tar.gz"
+    sha256 "d3676ba94641e03d6a30e951f09266c4c3ca3f5b58aa7b314a67f28e419878aa"
+  end
+
+  resource "Params::ValidationCompiler" do
+    url "https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.30.tar.gz"
+    sha256 "dc5bee23383be42765073db284bed9fbd819d4705ad649c20b644452090d16cb"
+  end
+
+  resource "Role::Tiny" do
+    url "https://cpan.metacpan.org/authors/id/H/HA/HAARG/Role-Tiny-2.001004.tar.gz"
+    sha256 "92ba5712850a74102c93c942eb6e7f62f7a4f8f483734ed289d08b324c281687"
+  end
+
+  resource "Specio" do
+    url "https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Specio-0.46.tar.gz"
+    sha256 "0bf42aa116076d6efc18f72b72c7acb5638bd41c0aa09aecc12fc8bf9ceb9596"
+  end
+
+  resource "Sub::Exporter::Progressive" do
+    url "https://cpan.metacpan.org/authors/id/F/FR/FREW/Sub-Exporter-Progressive-0.001013.tar.gz"
+    sha256 "d535b7954d64da1ac1305b1fadf98202769e3599376854b2ced90c382beac056"
+  end
+
+  resource "Sub::Identify" do
+    url "https://cpan.metacpan.org/authors/id/R/RG/RGARCIA/Sub-Identify-0.14.tar.gz"
+    sha256 "068d272086514dd1e842b6a40b1bedbafee63900e5b08890ef6700039defad6f"
+  end
+
+  resource "Sub::Quote" do
+    url "https://cpan.metacpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.006006.tar.gz"
+    sha256 "6e4e2af42388fa6d2609e0e82417de7cc6be47223f576592c656c73c7524d89d"
+  end
+
+  resource "Test::Fatal" do
+    url "https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.014.tar.gz"
+    sha256 "bcdcef5c7b2790a187ebca810b0a08221a63256062cfab3c3b98685d91d1cbb0"
+  end
+
+  resource "Try::Tiny" do
+    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.30.tar.gz"
+    sha256 "da5bd0d5c903519bbf10bb9ba0cb7bcac0563882bcfe4503aee3fb143eddef6b"
+  end
+
+  resource "Unicode::LineBreak" do
+    url "https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2019.001.tar.gz"
+    sha256 "486762e4cacddcc77b13989f979a029f84630b8175e7fef17989e157d4b6318a"
+  end
+
+  resource "Variable::Magic" do
+    url "https://cpan.metacpan.org/authors/id/V/VP/VPIT/Variable-Magic-0.62.tar.gz"
+    sha256 "3f9a18517e33f006a9c2fc4f43f01b54abfe6ff2eae7322424f31069296b615c"
+  end
+
+  resource "XString" do
+    url "https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/XString-0.002.tar.gz"
+    sha256 "260e252f7367228c9b4e43ef50c0becb04c4781de660577b3086cc106c0028c0"
+  end
+
+  resource "YAML::Tiny" do
+    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.73.tar.gz"
+    sha256 "bc315fa12e8f1e3ee5e2f430d90b708a5dc7e47c867dba8dce3a6b8fbe257744"
+  end
+
+  resource "namespace::autoclean" do
+    url "https://cpan.metacpan.org/authors/id/E/ET/ETHER/namespace-autoclean-0.29.tar.gz"
+    sha256 "45ebd8e64a54a86f88d8e01ae55212967c8aa8fed57e814085def7608ac65804"
+  end
+
+  resource "namespace::clean" do
+    url "https://cpan.metacpan.org/authors/id/R/RI/RIBASUSHI/namespace-clean-0.27.tar.gz"
+    sha256 "8a10a83c3e183dc78f9e7b7aa4d09b47c11fb4e7d3a33b9a12912fd22e31af9d"
   end
 
   def install
     ENV.prepend_create_path "PERL5LIB", libexec/"lib/perl5"
 
-    resources.each do |r|
+    resources.reject { |r| r.name == "MIME::Charset" }.each do |r|
       r.stage do
         system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
         system "make"
@@ -47,6 +182,11 @@ class Latexindent < Formula
       end
     end
 
+    resource("MIME::Charset").stage do
+      system "perl", "Makefile.PL", "--defaultdeps", "INSTALL_BASE=#{libexec}"
+      system "make", "install"
+    end
+
     (libexec/"lib/perl5").install "LatexIndent"
     (libexec/"bin").install "latexindent.pl"
     (libexec/"bin").install "defaultSettings.yaml"

```

Both the diff and working version of the formula can be c/p from following gist: https://gist.github.com/vladimyr/194fd6b63a8f7de6e5c719d0cc728716#file-latexindent-rb

**Comment by gpanders** [comment]
Thanks @vladimyr for doing that. I'm curious why I did not see these failures on my machine when I was testing the formula? Also, what is your method for discovering the dependency graph and adding them to the formula? I just kept trying to run the script and every time it said I was missing a dependency, I would manually go to ctag.org, copy the download link, calculate the sha256sum, and add it to the formula. It was a tedious and slow process, I'm curious if there is a better way.

**Comment by vladimyr** [comment]
> Thanks @vladimyr for doing that. I'm curious why I did not see these failures on my machine when I was testing the formula? 

Well, I can't say for sure but most probably you somehow modified `PERL5LIB` to contain paths to both libexec and your global Perl installation which had those modules installed.

> Also, what is your method for discovering the dependency graph and adding them to the formula? 
I just kept trying to run the script and every time it said I was missing a dependency, I would manually go to cpan.org, copy the download link, calculate the sha256sum, and add it to the formula. It was a tedious and slow process, I'm curious if there is a better way.

Officially there isn't but I quickly hacked some process. Here is what I did:
1. cloned https://github.com/cmhughes/latexindent.pl.git locally
2. created file named `cpanfile` inside cloned dir (`latexindent.pl`) with the following contents:
	```
	requires 'YAML::Tiny';
	requires 'File::HomeDir';
	requires 'Unicode::GCString';
	requires 'Log::Log4perl';
	requires 'Log::Dispatch::File';
	```
	In case you are wondering, I got those from https://github.com/cmhughes/latexindent.pl/blob/64b2bee/.travis.yml#L15-L19
3. if you don't have [`carton`](https://github.com/perl-carton/carton) install it using `cpan/m`
4. run `carton install` and it will install all required dependencies inside `latexindent.pl/local` folder
5. `carton` creates cache folder `latexindent.pl/local/cache`, there you'll find all those downloaded tarballs from CPAN
6. create file `generate_requirements.rb` with the following contents:
	```rb
	#!/usr/bin/env ruby
	
	# frozen_string_literal: true
	
	require "digest"
	require "uri"
	
	mirror = "https://cpan.metacpan.org/"
	distributions = Dir["local/cache/**/*.tar.gz"]
	
	resources = distributions.map do |d|
	  path = d.split("/id/")[1]
	  name = File.basename(path, ".tar.gz").split("-")[0...-1].join("::")
	  url = URI.join mirror, "/authors/id/#{path}"
	  sha256 = Digest::SHA256.file d
	  { name: name, url: url, sha256: sha256 }
	end
	resources.sort! { |a, b| a[:name] <=> b[:name] }
	
	resources.each do |r|
	  print <<~EOS
	    resource "#{r[:name]}" do
	      url "#{r[:url]}"
	      sha256 "#{r[:sha256]}"
	    end
	
	  EOS
	end
	```
	I wrote that script to automate resource blocks templating 🙃 
6. alter permissions `chmod +x generate_resources.rb`
7. run it using `./generate_resources.rb` and it will output the required resource blocks 🎉

It is pretty messy but at least it is _mostly_ automated 🙃

**Review by SMillerDev — DISMISSED** [review]
Thanks @gpanders ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
