### PR TITLE
python3 3.5.2

### PR DESCRIPTION
**Pull request by cclauss**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

https://www.python.org/downloads/release/python-352/  Also upgrades `setuptools`, `pip`, and `wheel`
# Fails when applying Homebrew/python3--patch

```
==> Downloading https://homebrew.bintray.com/bottles/python3-3.5.2.el_capitan.bottle.3.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "python3"
Download failed: https://homebrew.bintray.com/bottles/python3-3.5.2.el_capitan.bottle.3.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
Already downloaded: /Users/cclauss/Library/Caches/Homebrew/python3-3.5.2.tar.xz
==> Downloading https://bugs.python.org/file40478/xcode-stubs.diff
Already downloaded: /Users/cclauss/Library/Caches/Homebrew/python3--patch-029cc0dc72b1bcf4ddc5f913cc4a3fd970378073c6355921891f041aca2f8b12.diff
==> Patching
==> Applying xcode-stubs.diff
patching file Lib/distutils/ccompiler.py
Hunk #1 FAILED at 875.
1 out of 1 hunk FAILED -- saving rejects to file Lib/distutils/ccompiler.py.rej
patching file Lib/distutils/unixccompiler.py
Hunk #1 FAILED at 76.
Hunk #2 FAILED at 257.
Hunk #3 FAILED at 277.
Hunk #4 FAILED at 286.
Hunk #5 FAILED at 294.
5 out of 5 hunks FAILED -- saving rejects to file Lib/distutils/unixccompiler.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/python3--patch-20160627-47816-92pvb8/xcode-stubs.diff
```

### CODE REVIEW

**Comment by apetresc** [comment]
The patch that is failing to apply is no longer required. It was [applied upstream](https://github.com/python/cpython/commit/6e0963c9c7849a0cbce2b715c96fbebca687e030) (the only difference between the patch in this recipe and the upstream commit is that the upstream commit also added some comments explaining it).

The recipe seems to build fine for me by removing that patch.

**Comment by tdsmith** [comment]
Looks good once the patch is removed. I'll plan to squash these into a single commit with the title `python3 3.5.2`; you can do that yourself if you like.

**Comment by cclauss** [comment]
Hi Tim,  If you could do that, it would be great.  My git skills are pretty weak.

**Comment by tdsmith** [comment]
Sure thing. Please go ahead and push another commit to this branch removing the patch. Thanks!

**Comment by rakkesh** [comment]
could you update devel block with the latest alpha release,

```rb
devel do
  url "https://www.python.org/ftp/python/3.6.0/Python-3.6.0a2.tar.xz"
  sha256 "2dd2ddf22a63ef9642a20b1f5a40983209e8d7a8ad8371a881fde520edc9ff86"
end
```

**Comment by tdsmith** [comment]
I'll do that on pull; thanks for noticing the new alpha release.

**Comment by tdsmith** [comment]
I'm not sure those URLs for setuptools and wheel are correct; can you verify?

**Comment by apetresc** [comment]
I believe they're wrong. I have a fixed patch that passes tests on cclauss/homebrew-core#1, if @cclauss just merges it, everything should be fine.

**Comment by sashkab** [comment]
FYI: You can use new URL for packages:

```
https://pypi.io/packages/source/v/virtualenv/virtualenv-15.0.2.tar.gz
```

where:
* `v` -  first letter of the package
* `virtualenv` - package name
* `virtualenv-15.0.2.tar.gz` - file name to download.

From what I heard, this is how it will work from now on. There are cons and pros for this. 

Pros:
* URL alway will point to the tar.gz you pointing to.

Cons:
* You won't know if tar.gz was replaced, as this link will always point to the latest version (ie same version, but file was updated)

**Comment by tdsmith** [comment]
> You won't know if tar.gz was replaced, as this link will always point to the latest version (ie same version, but file was updated)

FWIW, pypi doesn't allow files to be replaced, so this shouldn't be a concern.

**Comment by tdsmith** [comment]
Oops! This is blocking on an issue with our new MachO support; ping @woodruffw. See http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/3886/version=yosemite/testReport/junit/brew-test-bot/yosemite/bottle_python3/

**Comment by tdsmith** [comment]
confirm fixed by https://github.com/Homebrew/brew/pull/400

**Comment by cclauss** [comment]
In the meantime Python 2.7.12 was released https://www.python.org/downloads/release/python-2712/. Perhaps someone with better brew chops than I have should update https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb

**Comment by woodruffw** [comment]
Sorry for the build chaos over here :bow:

**Comment by cclauss** [comment]
@woodruffw I the test failing above a problem for this PR on not?

**Comment by woodruffw** [comment]
@cclauss Not anymore, only earlier.

**Comment by cclauss** [comment]
@woodruffw Your meaning of your response is not clear to me.  The formula works on my Mac but the test above is failing.  Does the test failure above (on PyQT5 ??) mean that there is a problem with this PR?

**Comment by woodruffw** [comment]
@cclauss Sorry for the confusion. A commit not related to your formula (Homebrew/brew/pull/400) was merged prematurely, causing your build failure. That commit was reverted, and I've restarted your build on the CI.

**Comment by tdsmith** [comment]
To extend @woodruffw's remarks: we need some version of Homebrew/brew#400 to land before this PR will succeed, so this won't pass just yet, but the PR itself is still fine.

**Comment by UniqMartin** [comment]
Restarted the build after Homebrew/brew#400 had landed and looks like the bug has been properly resolved this time. I guess this PR can be merged if @tdsmith is happy with this.

**Comment by tdsmith** [comment]
Thanks for your patience, everyone!

**Pull request closed without merging**
