### PR TITLE
azure-cli-2.0.54

### PR DESCRIPTION
**Pull request by tjprescott**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tjprescott** [comment]
@SMillerDev I retriggered the Jenkins build and it passed.

**Comment by tjprescott** [comment]
ping @SMillerDev

**Comment by sgellock** [comment]
Hey guys, bot framework has a dependency on 2.0.54, so right now I'm unable to deploy to azure from a macOS machine until brew gets updated.  I'd like to ask for some urgency on getting this PR merged please.

**Comment by carlosscastro** [comment]
Hello @SMillerDev, I'm also blocked by this. Could we merge? Thanks!

**Comment by yugangw-msft** [comment]
Add a few other folks who have helped with Azure CLI release recently.
@lembacon, @fxcoudert, assuming @SMillerDev is not available, can one of you please help to get this merged? Azure CLI users are waiting on the new release

**Comment by tjprescott** [comment]
https://github.com/Homebrew/homebrew-core/pull/35779

Opened a separate PR which has been merged.

**Pull request closed without merging**
