### PR TITLE
zint: fix sandbox violation

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by xu-cheng** [comment]
Try 
```ruby
inreplace "CMakeLists.txt", "${CMAKE_ROOT}", "#{share}/cmake"

**Comment by apjanke** [comment]
LGTM

**Comment by DomT4** [comment]
Possibly worth adding a short `#` on it being a sandbox workaround so it's a little clearer to contributors, but 👍.

**Comment by mikemcquaid** [comment]
Agreed on comment otherwise 👍

**Pull request closed without merging**
