### PR TITLE
Remove pgcli formula.

### PR DESCRIPTION
**Pull request by amjith**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I would like to withdraw the formula for pgcli from the official repository. Installing pgcli using brew will upgrade the currently installed version of postgres database as a side-effect. This can result in undesirable consequences for the user. Hence the request for removal. 

Background: https://github.com/Homebrew/homebrew-core/pull/14004

### CODE REVIEW

**Comment by ilovezfs** [comment]
There were 900 installs in the last 30 days, so that's not really an option here.

**Comment by amjith** [comment]
Can you offer me a recourse? I really don't want to be fielding questions from people who install pgcli via brew and having their workflow disrupted.

**Comment by MikeMcQuaid** [comment]
@amjith You're welcome to tell them to you don't support installation via Homebrew.

**Comment by amjith** [comment]
> There were 900 installs in the last 30 days

Thank you for that. That made my day. 😄

**Comment by tsroten** [comment]
@MikeMcQuaid Thanks for the prompt feedback :)

Can we [migrate it via `tap_migrations.json`](https://github.com/Homebrew/brew/blob/master/docs/Migrating-A-Formula-To-A-Tap.md)?

**Comment by ilovezfs** [comment]
@tsroten no.

**Comment by tsroten** [comment]
@ilovezfs Thanks for the response 😄

I think we've been confused before by some of the wording/terms used in package managers like Homebrew, so I'm sorry for any misunderstandings on our part. PostgreSQL is actually **not** a pgcli dependency.  It only needs it during the build process. Is it acceptable to make PostgreSQL a build-time only dependency? If the user is installing via a bottle, they do not need to have PostgreSQL installed.

A local PostgreSQL install is not needed for the `test do` block in Homebrew or any other part of the pgcli end-user experience.

It's like the Psycopg docs [say](http://initd.org/psycopg/docs/install.html#build-prerequisites):
> You only need **pg_config** to compile `psycopg2`, not for its regular usage.

I might be misunderstanding the purpose of the `:build` symbol in Homebrew, but it seems like a good fit for this situation.

Thanks again!

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$  brew linkage pgcli
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/opt/postgresql/lib/libpq.5.dylib (postgresql)
iMac-TMP:~ joe$ 
```
It is needed at run time since it's linked.

**Comment by ilovezfs** [comment]
Specifically it is linked to `_psycopg.so`

```
iMac-TMP:~ joe$  brew linkage pgcli
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/opt/postgresql/lib/libpq.5.dylib (postgresql)
iMac-TMP:~ joe$ brew linkage --reverse pgcli
/usr/lib/libSystem.B.dylib
  libexec/vendor/lib/python2.7/site-packages/psycopg2/_psycopg.so
  libexec/vendor/lib/python2.7/site-packages/setproctitle.so

/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  libexec/vendor/lib/python2.7/site-packages/psycopg2/_psycopg.so

/usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  libexec/vendor/lib/python2.7/site-packages/psycopg2/_psycopg.so

/usr/local/opt/postgresql/lib/libpq.5.dylib
  libexec/vendor/lib/python2.7/site-packages/psycopg2/_psycopg.so
iMac-TMP:~ joe$
```

**Comment by tsroten** [comment]
@ilovezfs `brew linkage` -- that's useful!

It looks like Psycopg only works the way I was describing if it's installed from a wheel, but I think Homebrew requires installing from the source distribution. Oh well, thanks for your time.

**Comment by ilovezfs** [comment]
@tsroten you're welcome

**Comment by tsroten** [comment]
@ilovezfs It looks like Psycopg supports compiling as a static library. I'm happy to stop this train of thought if it's not looking productive, but here is Homebrew pgcli installed without PostgreSQL (build-time dependency only):

```bash
~ $ brew list postgres
Error: No such keg: /usr/local/Cellar/postgresql

~ $ brew linkage pgcli
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
  /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)

~ $ brew linkage --reverse pgcli
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  libexec/bin/python

/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
  libexec/lib/python2.7/site-packages/psycopg2-2.7.1-py2.7-macosx-10.11-x86_64.egg/psycopg2/_psycopg.so
  libexec/lib/python2.7/site-packages/setproctitle.so

/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
  libexec/lib/python2.7/site-packages/psycopg2-2.7.1-py2.7-macosx-10.11-x86_64.egg/psycopg2/_psycopg.so
  libexec/lib/python2.7/site-packages/setproctitle.so

/usr/lib/libSystem.B.dylib
  libexec/bin/python
  libexec/lib/python2.7/site-packages/psycopg2-2.7.1-py2.7-macosx-10.11-x86_64.egg/psycopg2/_psycopg.so
  libexec/lib/python2.7/site-packages/setproctitle.so

/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  libexec/lib/python2.7/site-packages/psycopg2-2.7.1-py2.7-macosx-10.11-x86_64.egg/psycopg2/_psycopg.so

/usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  libexec/lib/python2.7/site-packages/psycopg2-2.7.1-py2.7-macosx-10.11-x86_64.egg/psycopg2/_psycopg.so
```

**Comment by ilovezfs** [comment]
Yes that's how static libraries work. However, we generally do not build _anything_ with static libraries since that means the reverse dependencies will not automatically use the new versions of the libraries when there are updates, including security updates, to the underlying library, nor will there be any indication from CI that that needs to be done manually.

>I'm happy to stop this train of thought if it's not looking productive

This.

**Comment by MikeMcQuaid** [comment]
I'd like to gently suggest that the `pgcli` folks spend a bit more time reading our documentation before asking any more questions, thanks.

**Comment by MikeMcQuaid** [comment]
For Homebrew maintainers reference when looking at these issues: it seems the outcome here was the `pgcli` folks have decided to run their [own Homebrew tap](https://github.com/dbcli/homebrew-tap) (currently two versions outdated from Homebrew's `pgcli`) which [modifies Homebrew internals](https://github.com/dbcli/homebrew-tap/blob/b7512734820701c7a833202940f2fe7fdeb5c4a2/Formula/pgcli.rb#L8-L14) to try and make Homebrew behave differently just for their formula. Analytics show that 96.5% of people are still using the Homebrew/homebrew-core version so this shouldn't cause us support problems in the near future but just something to be aware of if we get people reporting `pgcli` formula issues on older versions.

**Pull request closed without merging**
