### PR TITLE
CKAN 1.24.0

### PR DESCRIPTION
**Pull request by HebaruSan**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Updated to latest version
- Added a caveat about missing functionality when installing via brew

### CODE REVIEW

**Comment by HebaruSan** [comment]
@Kamik423, the tests are failing with:

```
Error: --arch=32 Failed to switch to 'mono32'.
```

Did you test this with a mono installed by homebrew, or installed manually?

**Comment by Kamik423** [comment]
I installed `mono-mdk` as suggested in [this answer](https://github.com/KSP-CKAN/CKAN/issues/1844#issuecomment-270916462). I think that has to do with it. With just mono it will not even attempt to launch

**Comment by HebaruSan** [comment]
OK, this seems to be blocked by Homebrew/homebrew-core#4332, lack of 32 bit support in brew's mono install, closed without a fix.

The mono brew appears to compile mono from source, rather than installing a prebuilt binary, and also chooses the architecture:

https://github.com/Homebrew/homebrew-core/blob/edaca39cfdeab153bef0ea60e2c18bda70ebcb6d/Formula/mono.rb#L47-L49

So we can't fix this issue with the ckan brew until the mono brew gets fixed.

@vszakats , you worked on mono.rb. Can you by any chance tell us how to make it include 32 bit support?

**Comment by vszakats** [comment]
@HebaruSan Can't help you with this (not a Mono expert here), sorry.

**Comment by HebaruSan** [comment]
@Kamik423 , if I give you a ckan.rb cask file, can you try installing it in a clean cask install? If this works then I think we'll change this PR to delete this entry and open a new one in cask instead.

**Comment by fxcoudert** [comment]
Thanks @HebaruSan for the pull request!

**Pull request merged**
