### PR TITLE
python: fix for 10.14.sdk [CLOSES #31679]

### LINKED ISSUE #31679: Python fails to build on macOS 10.13.6, with MacOSX10.14.sdk command line tools.
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install python with `brew install python`, on macOS 10.13.6, with MacOSX10.14.sdk command line tools.
- What happened (include command output)
Gist-logs: <https://gist.github.com/138b058432ac0e7ef3cc01af128389ac>
Build error for python:
```
==> make
==> make install PYTHONAPPSDIR=/Users/ling/homebrew/Cellar/python/3.7.0
Last 15 lines from /Users/ling/Library/Logs/Homebrew/python/03.make:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:472:147: error: expected ';' after top level declarator
FOUNDATION_EXPORT NSFileProtectionType const NSFileProtectionCompleteUntilFirstUserAuthentication API_AVAILABLE(ios(5.0), watchos(2.0), tvos(9.0)) API_PROHIBITED(macos);
                                                                                                                                                  ^
In file included from ./FileSettings.m:9:
In file included from ./FileSettings.h:9:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:39:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSHashTable.h:5:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPointerFunctions.h:36:100: error: missing ',' between enumerators
    NSPointerFunctionsZeroingWeakMemory API_DEPRECATED("GC no longer supported", macos(10.5, 10.8)) API_PROHIBITED(ios, watchos, tvos) = (1UL << 0),  // deprecated; uses GC weak read and write barriers, and dangling pointer behavior otherwise
                                                                                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [FileSettings.o] Error 1
make[1]: *** [install_PythonLauncher] Error 2
make: *** [frameworkinstallapps] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
pipenv cannot easily manage multiple python versions https://github.com/Homebrew/homebrew-core/issues/31487
WeeChat fails to build --with-python https://github.com/Homebrew/homebrew-core/issues/30509
Jupyter notebook is launched with PYTHONPATH, modifies sys.path in Python kernels https://github.com/Homebrew/homebrew-core/issues/31325
`vim` fails to build from source with option `--with-client-server` when python is installed with '--with-tcl-tk' https://github.com/Homebrew/homebrew-core/issues/30949
```
- What you expected to happen
See if someone has same problem.
- Step-by-step reproduction instructions (by running `brew install` commands)
On macOS 10.13.6, with MacOSX10.14.sdk command line tools, just run `brew install python`

### PR DESCRIPTION
**Pull request by adrw**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fix for open issue #31679

### CODE REVIEW

**Comment by chapeladmin** [comment]
python@2.rb has a similar problem. Removing the line will probably break things on < xcode 10 unless the fix for 10.14 sdk pathing changes modified how include paths are added to cflags irregardless of version.

**Comment by adrw** [comment]
@chapeladmin fair point, added condition to only add the flags on macOS versions before High Sierra to mitigate that risk.

**Comment by fxcoudert** [comment]
I'm thinking it should depend on `DevelopmentTools.clang_build_version < 1000` rather than macOS version. People can have Xcode 9 still installed on High Sierra.

**Comment by fxcoudert** [comment]
Thanks @adrw for the pull request! Now meged

**Pull request merged**
