### PR TITLE
hbase 2.2.3

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by mistydemeo — CHANGES_REQUESTED** [review]
CI is seeing a different `sha256`:

```
==> Downloading https://www.apache.org/dyn/closer.cgi?path=hbase/2.2.3/hbase-2.2.3-bin.tar.gz
==> Downloading from http://mirrors.advancedhosters.com/apache/hbase/2.2.3/hbase-2.2.3-bin.tar.gz
Warning: Formula reports different SHA256: ac0c840cd11560f6eec9b337058b83ecf692a4c59aea011c0f5c2ef33394b0d1
```

**Comment by zachauten** [comment]
@mistydemeo It seems like the url in the formula is unreliable. https://www.apache.org/dyn/closer.cgi?path=hbase/2.2.3/hbase-2.2.3-bin.tar.gz suggests using one of their mirrors. Is the solution to just pick one and add it as a mirror, or should the main url be something that's more stable?

**Comment by mistydemeo** [comment]
I wonder if there's a more reliable main URL we could pick...

**Comment by zachauten** [comment]
Is it possible apache changed how their url routing works? I just tried downloading the old url with curl and it's just getting the webpage instead of a tarball. That would explain the changing sha256.

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/50404 picks better urls

**Pull request closed without merging**
