### PR TITLE
hurl 4.2.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
https://github.com/Orange-OpenSource/hurl/releases

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Needs a livecheck

**Comment by jcamiel** [comment]
Hi, Hurl maintainers here. We made a mistake preparing a new release yesterday and labelling it 4.2.2 (this was only a draft GitHub release). The new Hurl latest (and stable) release is _4.2.0_: https://github.com/Orange-OpenSource/hurl/releases/tag/4.2.0 Sorry for this 😓 !!!

**Comment by p-linnane** [comment]
Closing since this was tagged in error.

**Pull request closed without merging**
