### PR TITLE
prototool hash update

### PR DESCRIPTION
**Pull request by smaye81**
Updated the sha256 for prototool and added a `revision 1` statement

### CODE REVIEW

**Comment by SMillerDev** [comment]
Van you rename this and the commit to `prototool hash update`

**Comment by smaye81** [comment]
> Van you rename this and the commit to `prototool hash update`

Yep.  Done.

**Comment by SMillerDev** [comment]
Thanks @smaye81

**Comment by smaye81** [comment]
Not sure why CI is failing though.  Any ideas?

**Comment by mistydemeo** [comment]
It's only red because of the warning about the sha256 changing. That's an ignorable one.

**Pull request closed without merging**
