### PR TITLE
openfast 3.2.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Linux test failure:
```
   FAST_InitializeAll:FAST_Init:FAST_ReadPrimaryFile:Invalid numerical input for file "homebrew.fst"
   occurred while trying to read MHK.
  
   OpenFAST encountered an error during module initialization.
    Simulation error level: FATAL ERROR
  
    Aborting OpenFAST.
```

**Comment by chenrui333** [comment]
relates to https://github.com/OpenFAST/openfast/issues/1094
API change between 3.0 and 3.1, https://openfast.readthedocs.io/en/main/source/user/api_change.html

**Comment by iMichka** [comment]
I fixed it by adding the missing entries to the test.

**Review by cho-m — APPROVED** [review]

**Comment by chenrui333** [comment]
> I fixed it by adding the missing entries to the test.

nice work!

**Pull request closed without merging**
