### PR TITLE
scdoc 1.9.4 (new formula)

### PR DESCRIPTION
**Pull request by nnathan**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)? No, seems gems with C extensions were breaking trying to link to i386 versions of system libraries, i'm just going to hope the CI system tries this instead.

-----

### CODE REVIEW

**Comment by notpeter** [comment]
This formula worked for me! 👍

**Comment by SMillerDev** [comment]
Looks pretty okay. Just wondering what the empty LDFLAGS are doing there.

**Comment by nnathan** [comment]
> Looks pretty okay. Just wondering what the empty LDFLAGS are doing there.

scdoc by default tries to build as a statically linked program which cannot be done in macOS. Do you think it'd be pertinent to add a comment in the formula to indicate this?

**Comment by SMillerDev** [comment]
afaik homebrew already passes it's own LDFLAGS to make

**Comment by nnathan** [comment]
> afaik homebrew already passes it's own LDFLAGS to make

So I tried removing the LDFLAGS= argument, and got the following output when trying to install scdoc:

```
clang -std=c99 -pedantic -c -o .build/util.o -g -DVERSION='"1.9.4"' -Wall -Wextra -Werror -Wno-unused-parameter -Iinclude src/util.c
clang -static -o scdoc .build/main.o .build/string.o .build/utf8_chsize.o .build/utf8_decode.o .build/utf8_encode.o .build/utf8_fgetch.o .build/utf8_fputch.o .build/utf8_size.o .build/util.o
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SMillerDev** [comment]
Empty LDFLAGS it is. Thanks @nnathan! without people like you it would be impossible to keep homebrew going 🎉 🎈

**Comment by SMillerDev** [comment]
Oh, one more thing @nnathan. Could you rebase against the latest master?

**Comment by nnathan** [comment]
> Oh, one more thing @nnathan. Could you rebase against the latest master?

Yep done.

**Pull request closed without merging**
