### PR TITLE
librealsense 2.39.0

### PR DESCRIPTION
**Pull request by oori**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dtrodrigues** [comment]
https://github.com/IntelRealSense/librealsense/releases/tag/v2.39.0

>Error: 1 problem in 1 formula detected
librealsense:
> * v2.39.0 is a GitHub pre-release.

**Comment by SMillerDev** [comment]
We don't ship pre-releases. Please make another pull request once this is stable.

**Comment by oori** [comment]
@SMillerDev It is now marked as released.  not pre-release.   same version, no change in the PR needed.

**Comment by dtrodrigues** [comment]
The audit still thinks it's a pre-release for some reason. I can take a closer look later to see why that may be.

**Review by SMillerDev — APPROVED** [review]
Thanks @oori ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
