### PR TITLE
buildifier 0.19.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Fails during build:
```
==> go build -o /usr/local/Cellar/buildifier/0.19.2/bin/buildifier buildifier/buildifier.go
src/github.com/bazelbuild/buildtools/api_proto/api.gen.pb.go:6:8: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/local/Cellar/go/1.11.2/libexec/src/github.com/golang/protobuf/proto (from $GOROOT)
	/private/tmp/buildifier-20181122-96378-jc2x67/src/github.com/golang/protobuf/proto (from $GOPATH)
```

**Comment by igas** [comment]
Yeah, I see it in the code but don't see any package management locks.

**Comment by dpursehouse** [comment]
FWIW I get the same build error locally.  It builds fine with bazel though, which seems to also build the protobuf dependency.

**Comment by dpursehouse** [comment]
Same error with the latest 0.19.2.1

**Comment by dpursehouse** [comment]
The problem is fixed by installing the missing dependency before building.  See #34815 which updates to the latest version 0.19.2.1.

**Pull request closed without merging**
