### PR TITLE
rust: build with --enable-profiler

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by alex** [comment]
Since I didn't document this originally, the motivation here is that this is required for code coverage to work.

**Comment by chenrui333** [comment]
> Since I didn't document this originally, the motivation here is that this is required for code coverage to work.

make sense, thanks for the context 👍

**Comment by alex** [comment]
This requires the `CI-long-timeout` label to be set.

**Comment by chenrui333** [comment]
> This requires the `CI-long-timeout` label to be set.

we are aware of this. too many long builds these days, as you can see in here, https://github.com/Homebrew/homebrew-core/labels/long%20build

**Comment by alex** [comment]
Got it. thanks!

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
