### PR TITLE
qemu: Patch for "mprotect failed: Permission denied" issues on Apple …

### PR DESCRIPTION
**Pull request by stefannilsson**
…Silicon.

Bug tracker: https://bugs.launchpad.net/qemu/+bug/1914849

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
This is a patch for `HEAD` installs only? We don't carry any patched for `HEAD` builds.

**Comment by stefannilsson** [comment]
`qemu` (latest `stable` formula/5.2.0) is broken on Apple Silicon.
```
$ qemu-system-arm
Could not allocate dynamic translator buffer
```

`HEAD` works **with** the supplied patch, but not without.
_(without patch)_
```
$ qemu-system-x86_64
qemu-system-x86_64: qemu_mprotect__osdep: mprotect failed: Permission denied
```

And `qemu` does not have a more stable release than `5.2.0`.

Isn't it better to have a `HEAD`-specific patch in place for now, to at least allow people to use `qemu` on Apple Silicon via `HEAD`?
And remove this workaround when this is hopefully resolved in upcoming `qemu` releases?

**Comment by carlocab** [comment]
Is there no patch we could apply to the stable release?

>Isn't it better to have a `HEAD`-specific patch in place for now, to at least allow people to use `qemu` on Apple Silicon via `HEAD`?

This is true for `qemu` but unsustainable as a general policy when we're dealing with ~5000 formulae and ~25 maintainers.

`HEAD` builds are unsupported in homebrew/core, but we keep them around when they entail next to zero maintenance. A patch for a moving target doesn't satisfy that criterion, and I'm afraid that we're more likely to remove `head` specs when they're broken rather than entertain patches for them.

**Comment by stefannilsson** [comment]
The patch **is** compatible with latest `stable`, even though it does not resolve the stable bug:
```
Could not allocate dynamic translator buffer
```

But it would still help the people using `HEAD` for now.
Is it OK to move this patch to a general level (`stable`+`HEAD`)?

(I'm also trying to figure out a way to improve the test formula `tests` since they didn't capture this issue...)

**Comment by carlocab** [comment]
>Is it OK to move this patch to a general level

This would be fine. Just put it right before the `install` block.

**Comment by stefannilsson** [comment]
New PR https://github.com/Homebrew/homebrew-core/pull/73281

**Pull request closed without merging**
