### PR TITLE
fail2ban: migrate to python@3.10

### PR DESCRIPTION
**Pull request by Moisan**
fail2ban: migrate to python@3.10

### CODE REVIEW

**Comment by Moisan** [comment]
Upstream code header includes
```
# Fail2Ban is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
```

**Comment by Moisan** [comment]
Fails with `error in fail2ban setup command: use_2to3 is invalid`.

**Comment by cho-m** [comment]
Upstream issue/fix:
- https://github.com/fail2ban/fail2ban/issues/3098
- https://github.com/fail2ban/fail2ban/commit/5ac303df8a171f748330d4c645ccbf1c2c7f3497

**Review by carlocab — DISMISSED** [review]
Rebased to prevent @BrewTestBot from squashing the commit message to `fail2ban: revision`.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
