### PR TITLE
Gradle 4.1

### PR DESCRIPTION
**Pull request by Nebu1eto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR resolves update gradle to latest version. 
Here are [gradle's release](https://github.com/gradle/gradle/releases/tag/v4.1.0).

### CODE REVIEW

**Comment by fxcoudert** [comment]
I think the alias should just be `gradle@4` (and `gradle@2.14` should be `gradle@2`).

**Comment by Hazealign** [comment]
Thanks @fxcoudert, and sorry for late.

**Comment by emartynov** [comment]
Waiting for it!

**Comment by ilovezfs** [comment]
Thanks for the pull request @Hazealign! Shipped.

**Pull request merged**
