### PR TITLE
ranger: fix shebang to use Homebrew Python

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Existing formula/bottle uses `/usr/bin/python`.

https://github.com/Homebrew/homebrew-core/runs/3370259409?check_suite_focus=true
```
==> brew test --verbose ranger
==> FAILED
==> Testing ranger
==> /home/linuxbrew/.linuxbrew/Cellar/ranger/1.9.3/bin/ranger --version
Error: ranger: failed
An exception occurred within a child process:
```

### CODE REVIEW

**Comment by carlocab** [comment]
We could also maybe do an `inreplace` to get an `all` bottle here.

**Review by SMillerDev — APPROVED** [review]

**Comment by cho-m** [comment]
> We could also maybe do an `inreplace` to get an `all` bottle here.

3 diffs, but some are "incorrect" relocations:
- ranger/1.9.3/libexec/ranger/config/rc.conf
    ```diff
    -# ":cd /u/lo/b<tab>" expands to ":cd /usr/local/bin".
    +# ":cd /u/lo/b<tab>" expands to ":cd @@HOMEBREW_PREFIX@@/bin".
    ```
- ranger/1.9.3/share/man/man1/ranger.1
    ```diff
    -\&\fB:cd /u/lo/b<\s-1TAB\s0>\fR expands to \fB:cd /usr/local/bin\fR.
    +\&\fB:cd /u/lo/b<\s-1TAB\s0>\fR expands to \fB:cd @@HOMEBREW_PREFIX@@/bin\fR.
    ```
- ranger/1.9.3/libexec/ranger/ext/img_display.py
    ```diff
    -    '/usr/local/libexec/w3m/w3mimgdisplay',
    +    '@@HOMEBREW_PREFIX@@/libexec/w3m/w3mimgdisplay',
    ```

**Comment by carlocab** [comment]
So how about
```ruby
inreplace_files = [libexec/"ranger/config/rc.conf", man1/"ranger.1"]
inreplace inreplace_files, "/u/lo/b", "/o/ho/b" if Hardware::CPU.arm?

inreplace_files << libexec/"ranger/ext/img_display.py"
inreplace inreplace_files, "/usr/local", HOMEBREW_PREFIX
```
It's still wrong on non-default prefixes, but not much we can do about that.

**Review by carlocab — APPROVED** [review]

**Comment by cho-m** [comment]
Do we want to rebuild macOS bottles or leave them?
Right now, the bottles are using system Python 2.

There shouldn't be any issues for users, as long as Apple provides `/usr/bin/python`. It does add an unused `python@3.9` dependency, but I would assume a number of users already have this installed.

**Pull request closed without merging**
