### PR TITLE
ispc 1.21.1

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>A minor ISPC update with interop related fixes for ISPCRT needed to Intel® oneAPI Rendering Toolkit release.

This update contains only Linux oneAPI x86, macOS universal and Windows binaries. Use [v1.21.0](https://github.com/ispc/ispc/releases/tag/v1.21.0) binaries for other platforms.</pre>
</details>

### CODE REVIEW

**Comment by osalbahr** [comment]
Note: from the release notes:
> This update contains only Linux oneAPI x86, macOS universal and Windows binaries. Use [v1.21.0](https://github.com/ispc/ispc/releases/tag/v1.21.0) binaries for other platforms.

If I understand correctly this does not apply to Homebrew.

**Comment by osalbahr** [comment]
> The formula version (1.21.1) is newer than the version from `brew livecheck` (1.21.0).

No (?)

```console
% brew bump ispc
Running `brew update --auto-update`...
==> ispc
Current formula version:  1.21.0
Latest livecheck version: 1.21.1
Latest Repology version:  1.21.1
Open pull requests:       ispc 1.21.1 (https://github.com/Homebrew/homebrew-core/pull/153413)
Closed pull requests:     none
% brew livecheck ispc
ispc: 1.21.0 ==> 1.21.1
```

Works on my machine.

**Comment by chenrui333** [comment]
I think the main issue is more of cosmetic issue

image

**Review by chenrui333 — APPROVED** [review]

**Comment by osalbahr** [comment]
> I think the main issue is more of cosmetic issue
> 
> image

Interesting. I guess that might explain why the CI got a different result. I assumed it just runs `brew livecheck` but I didn’t look into it.

**Pull request merged**
