### PR TITLE
cue 0.4.0 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by verdverm** [comment]
Reviewers, please see https://github.com/cue-lang/cue/pull/1241 The core maintainers there may wish to have their input considered.

CUE already has an existing tap that is published to via release automation. https://github.com/cue-lang/homebrew-tap

This formula uses a different methodology than the official one. (build vs download)

**Comment by jonchang** [comment]
The cue maintainers are free to continue to use their tap if they wish. That by itself has no bearing on whether this software will be packaged in Homebrew/core or not. In particular, see https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#official-vendor-taps for our stance on this.

**Comment by verdverm** [comment]
@jonchang is there a way to specify the go version used to build from source.when using a tap? Are there guidelines for ensuring consistent or reproducible builds?

**Comment by chenrui333** [comment]
> @jonchang is there a way to specify the go version used to build from source when using a tap? Are there guidelines for ensuring consistent or reproducible builds?

The only difference is there would be limited bottle upload capability. You can specify `depends_on go@xx` or `depends_on go` like what I am doing in here.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
