### PR TITLE
burp 3.1.4

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [ ] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not a stable release; see https://burp.grke.org/download.html

**Comment by osalbahr** [comment]
`brew bump --open-pr`:

```console
...
==> brightness
Current formula version:  1.2
Latest livecheck version: 1.2
Latest Repology version:  3.0
Open pull requests:       none
Closed pull requests:     none

==> burp
Current formula version:  2.4.0
Latest livecheck version: 3.1.4
Latest Repology version:  3.1.4
Open pull requests:       none
Closed pull requests:     none
Warning: This formula has resources that may need to be updated.
==> Downloading https://github.com/grke/burp/releases/download/3.1.4/burp-3.1.4.
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
Warning: Cannot verify integrity of '1079acecbdcbbf583bc70f27c89267171cc6c2896ae5874a3ea77ee1c6a7dd0b--burp-3.1.4.tar.bz2'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "4bdcbde98082db78679a7a7170c76dff5dacb9f8b984aaa3f01d2999dac6e3f9"
==> replace /^  revision \d+\n(\n(  head "))?/m with "\\2"
==> replace /https:\/\/github\.com\/grke\/burp\/releases\/download\/2\.4\.0\/bur
==> replace "1f88d325f59c6191908d13ac764db5ee56b478fbea30244ae839383b9f9d2832" w
M	Formula/arkade.rb
M	Formula/burp.rb
Switched to a new branch 'bump-burp-3.1.4'
[bump-burp-3.1.4 210c8454bff] burp 3.1.4
 1 file changed, 2 insertions(+), 3 deletions(-)
remote: 
remote: Create a pull request for 'bump-burp-3.1.4' on GitHub by visiting:        
remote:      https://github.com/osalbahr/homebrew-core/pull/new/bump-burp-3.1.4        
remote: 
To https://github.com/osalbahr/homebrew-core.git
 * [new branch]              bump-burp-3.1.4 -> bump-burp-3.1.4
branch 'bump-burp-3.1.4' set up to track 'https://******@github.com/osalbahr/homebrew-core.git/bump-burp-3.1.4'.
https://github.com/Homebrew/homebrew-core/pull/138580

==> bvm
Current formula version:  0.4.2
Latest livecheck version: 1.3.3
Latest Repology version:  1.3.3
Open pull requests:       none
Closed pull requests:     none
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 21 seconds
Warning: GitHub API Error: API rate limit exceeded for user ID 54853250.
Try again in 21 seconds
Error: Failed to download resource "bvm"
Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.3-58-g3f49592\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/bvm/bvm/archive/1.3.3.tar.gz` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
HTTP/2 302 
server: GitHub.com
date: Sat, 05 Aug 2023 00:39:40 GMT
content-type: text/html; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
location: https://codeload.github.com/bvm/bvm/tar.gz/1.3.3
cache-control: max-age=0, private
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: no-referrer-when-downgrade
...
```

Running `brew bump burp`:
```console
% brew bump burp
==> burp
Current formula version:  2.4.0
Latest livecheck version: 2.4.0
Latest Repology version:  3.1.4
Open pull requests:       burp 3.1.4 (https://github.com/Homebrew/homebrew-core/pull/138580)
Closed pull requests:     none
```

The pattern of falling to Repology is consistent, even without GitHub limit messages. But when I run `brew bump --open-pr burp` (as opposed to argument-less) the "livecheck version" is correct.
```console
$ brew bump --open-pr burp
==> burp
Current formula version:  2.4.0
Latest livecheck version: 2.4.0
Latest Repology version:  3.1.4
Open pull requests:       burp 3.1.4 (https://github.com/Homebrew/homebrew-core/pull/138580)
Closed pull requests:     none
burp was not bumped to the Repology version because it's livecheckable.
```

I don't know if the apparent fallback happens because of running argument-less or something to do with rate-limiting, but I guess it is the latter.

**Comment by chenrui333** [comment]
it is not a stable release yet, it is indeed latest.

**Comment by chenrui333** [comment]
good catch, raised an issue asking about this.

**Comment by chenrui333** [comment]
confirmed, it is not a stable release.

**Pull request closed without merging**
