### PR TITLE
gdal 3.0.4

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Just for the reference to the previous attempt to bump `gdal`: https://github.com/Homebrew/homebrew-core/pull/46817#issuecomment-571719793

**Comment by aneeskA** [comment]
@bayandin @zachauten I am very new to this. How can I help to get this merged?

**Comment by bayandin** [comment]
I'm afraid we're blocked by `liblas` incompatibility with `gdal` (>=2.5.0): https://github.com/libLAS/libLAS/issues/164

**Comment by zachauten** [comment]
Closing since it’s blocked. @aneeska feel free to open another pr if you find a fix for the blocking issue.

**Comment by aneeskA** [comment]
> I'm afraid we're blocked by `liblas` incompatibility with `gdal` (>=2.5.0): [libLAS/libLAS#164](https://github.com/libLAS/libLAS/issues/164)

@zachauten if I go to Debian Sid, I see that it is built and released. [gdal in Debian Sid](https://packages.debian.org/source/sid/gdal)

**Comment by bayandin** [comment]
> > I'm afraid we're blocked by `liblas` incompatibility with `gdal` (>=2.5.0): [libLAS/libLAS#164](https://github.com/libLAS/libLAS/issues/164)
> 
> @zachauten if I go to Debian Sid, I see that it is built and released. [gdal in Debian Sid](https://packages.debian.org/source/sid/gdal) What am I missing?

Debian Sid doesn't have `liblas`: https://packages.debian.org/source/sid/liblas

(in compare with Debian Stable which has both [`gdal` (2.4.0+dfsg-1)](https://packages.debian.org/source/stable/gdal) and [`liblas` (1.8.1-10)](https://packages.debian.org/source/stable/liblas))

**Comment by aneeskA** [comment]
Stupid question, but I do not see `liblas` in the `build-depends` list.

**Comment by bayandin** [comment]
> Stupid question, but I do not see `liblas` in the `build-depends` list.

It's vice versa, `liblas` does depend on `gdal`: https://github.com/Homebrew/homebrew-core/blob/b15f78cb6488f0ba6ff5b94842914d4ee54eade5/Formula/liblas.rb#L18

**Comment by aneeskA** [comment]
Ah! I see. So if I update `gdal`, `liblas` breaks and hence deadlock?

**Comment by bayandin** [comment]
> Ah! I see. So if I update `gdal`, `liblas` breaks and hence deadlock?

Exactly!

**Comment by aneeskA** [comment]
Thanks for being patient with me. I am very much interested in gdal v3 because I want to use `MakeValid()`. Is there something that can be done to get `liblas` in order so that I get what I want? :)

**Comment by Bo98** [comment]
Probably the best way, if you're interested, is to propose and submit a patch to `liblas`. If they accept it, we will include that patch in Homebrew.

Otherwise, I might have a look myself at some point if I get the time.

**Comment by aneeskA** [comment]
No offence to me, but @Bo98 I am pretty sure you looking into it is the fastest method to sorting it out! :) I am desperate so let me give it a shot over the weekend.

**Comment by Bo98** [comment]
> I am pretty sure you looking into it is the fastest method

Fair enough, but I can't guarantee when I'll be able to, so if you have the time over the weekend then feel free to give it a shot.

**Comment by aneeskA** [comment]
@Bo98 @bayandin Over the weekend I was able to reach as described here : https://github.com/libLAS/libLAS/issues/164 . I could move a little further but then got stuck here:

```
root@f4381c014d4e:~/libLAS-1.8.1/makefiles# make
[ 41%] Built target las
[ 44%] Built target las_c
[ 45%] Linking CXX executable ../bin/Release/lasinfo
/usr/bin/ld: CMakeFiles/lasinfo.dir/laskernel.cpp.o: undefined reference to symbol '_ZNSt15basic_streambufIcSt11char_traitsIcEE8overflowEi@@GLIBCXX_3.4'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [apps/CMakeFiles/lasinfo.dir/build.make:112: bin/Release/lasinfo] Error 1
make[1]: *** [CMakeFiles/Makefile2:281: apps/CMakeFiles/lasinfo.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

I think the issue is the use of `-lstdc++` flag but I so far couldn't figure out how to fix.

**Comment by Bo98** [comment]
> I think the issue is the use of `-lstdc++` flag but I so far couldn't figure out how to fix.

I'm not entirely familiar with Linux toolchain, but I believe that error can happen if the flag is either missing or misplaced (wrong ordering). Perhaps one of the Linuxbrew folks will be familiar with that error.

I'm surprised though you got that problem from CMake. Are you using GCC?

**Pull request closed without merging**
