### PR TITLE
gst-plugins-good: Add gtk+3 support back

### PR DESCRIPTION
**Pull request by LecrisUT**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the pull request, I'm just wondering if pulling in QT and all it's dependencies would be worth it for the majority of homebrew users. It didn't seem to be used too often when it was an option either.

**Comment by LecrisUT** [comment]
I don't know about QT, but the `gtk+3` will be needed for `pdfpc` which is built on `gtk+3`, thus the current request

**Comment by SMillerDev** [comment]
Yeah, I should have had some coffee and not answered 2 PRs at the same time. I meant GTK+3

**Comment by LecrisUT** [comment]
Go on a break and enjoy some coffee :D
Should I submit a gst-plugin with only the gtk+3 support as well, and let you guys choose which option you prefer?

**Comment by LecrisUT** [comment]
Uhm, I made a mistake committing the alternative formula as well. How do I undo that commit?

**Comment by tschoonj** [comment]
Modifying the current `gst-plugins-good` formula to add `gtk+3` support seems like a reasonable thing to do. Do you need to add a configure flag to ensure that plugin gets built? Or will it get built as soon as the `gtk+3` pkg-config file is found?

**Comment by LecrisUT** [comment]
As soon as the dependency is added, everything is resolved. You can check the first 2 commits (ignore the last one, I'm still new to github).

**Comment by tschoonj** [comment]
Ok, I see that you have done this all through the website... I will open a PR with the proper commit. Please close this one, as well as #40912.

**Comment by LecrisUT** [comment]
Ok. I'll have to figure out how brew bump-formula, but I'm confused as to what the URL and SHA-256 in the manual refer to, or does it just update the version and there is another tool to edit the formulas?

**Comment by tschoonj** [comment]
No worries, I took care of it in #40941

**Comment by LecrisUT** [comment]
Yeah, thanks for the support. Hopefully I'll do better on the next PR (`pdfpc`)

**Pull request closed without merging**
