### PR TITLE
llvm@3.9 (new formula)

### PR DESCRIPTION
**Pull request by tmcdonell**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Versioned install of LLVM-3.9. Useful for people who need to install multiple versions of LLVM simultaneously (like me), or who need to install a specific version (also useful in documentation).

LLVM-4.0 is currently in RC and scheduled to be released in a few days. Once that is out we can bump the `llvm.rb` formula and LLVM-3.9 will still be available via this formula.

I included the fix to `llvm@3.8` in this PR, since that was causing problems installing multiple versions simultaneously, but I could probably split that out. I currently have `llvm@3.7`, `llvm@3.8`, and `llvm@3.9` formula installed and they seem to be working together nicely.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The current formula is already 3.9.x, so at most we'd consider adding an alias.

**Comment by tmcdonell** [comment]
@ilovezfs As I mentioned in the comment, LLVM is about to land 4.0, so this is still necessary. At worst I am a few days early with the PR.

Additionally, for my own use can, LLVM is one of the dependencies of my software and it requires a specific version to be installed. It is much easier to write in the documentation/installation instructions `brew install llvm@3.9`; rather than `brew install llvm; brew link --force llvm` and hope for the best. I think this is a valid use case.

**Comment by ilovezfs** [comment]
which is why I said we'd accept a PR for an alias

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/pull/8945.

**Comment by MikeMcQuaid** [comment]
> I included the fix to llvm@3.8 in this PR, since that was causing problems installing multiple versions simultaneously, but I could probably split that out.

Yeh, a separate PR would be best for this, thanks.

> As I mentioned in the comment, LLVM is about to land 4.0, so this is still necessary. At worst I am a few days early with the PR.

I'd recommend creating a PR for both LLVM 4.0 and LLVM@3.9 in the same one.

**Comment by tmcdonell** [comment]
@MikeMcQuaid sure, I'll create a separate PR for that.

I appreciate your courtesy to actually read the commit message. Thanks.

**Comment by ilovezfs** [comment]
Cute.

**Comment by MikeMcQuaid** [comment]
> I appreciate your courtesy to actually read the commit message. Thanks.

GitHub's UI is PR-focused rather than commit-focused and Homebrew's maintainers are busy people so it's best to put information you need to be read in the PR message as well as the commit message.

**Pull request closed without merging**
