### PR TITLE
mariadb 10.4.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
```
[  3%] Linking C shared module client_ed25519.so
cd /tmp/mariadb-20190801-49663-kucwn2/mariadb-10.4.7/libmariadb && /usr/local/Cellar/cmake/3.15.1/bin/cmake -E cmake_link_script CMakeFiles/client_ed25519.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang   -pie -fPIC -fstack-protector --param=ssp-buffer-size=4 -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -DDBUG_OFF -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -bundle -Wl,-headerpad_max_install_names  -o client_ed25519.so CMakeFiles/client_ed25519.dir/plugins/auth/ed25519.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_0.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_isnegative.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_sub.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p1p1_to_p2.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p3_to_cached.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/open.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_1.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_isnonzero.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_tobytes.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p1p1_to_p3.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p3_to_p2.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/sc_muladd.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_add.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_mul.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_add.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p2_0.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_precomp_0.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/sc_reduce.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_cmov.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_neg.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_double_scalarmult.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p2_dbl.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_scalarmult_base.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/sign.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_copy.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_pow22523.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_frombytes.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p3_0.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_sub.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/verify.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_frombytes.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_sq2.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_madd.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p3_dbl.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_tobytes.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_invert.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/fe_sq.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_msub.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/ge_p3_tobytes.c.o CMakeFiles/client_ed25519.dir/plugins/auth/ref10/keypair.c.o CMakeFiles/client_ed25519.dir/libmariadb/secure/openssl_crypt.c.o 
Undefined symbols for architecture x86_64:
  "_EVP_DigestFinal_ex", referenced from:
      _ma_hash_result in openssl_crypt.c.o
  "_EVP_DigestInit", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_DigestUpdate", referenced from:
      _ma_hash_input in openssl_crypt.c.o
  "_EVP_MD_CTX_create", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_MD_CTX_destroy", referenced from:
      _ma_hash_new in openssl_crypt.c.o
      _ma_hash_free in openssl_crypt.c.o
  "_EVP_md5", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_ripemd160", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_sha1", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_sha224", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_sha256", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_sha384", referenced from:
      _ma_hash_new in openssl_crypt.c.o
  "_EVP_sha512", referenced from:
      _ma_hash_new in openssl_crypt.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libmariadb/client_ed25519.so] Error 1
make[1]: *** [libmariadb/CMakeFiles/client_ed25519.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by satyago** [comment]
@terinjokes are you still supporting mariadb?

If you are, could you please take a look at this and help adding 10.4.7?
I have absolutely no idea of how this works, for me to be able to pick this up - and believe me, I tried. I feel like the checksums for the bottles are off, but then again, they probably don't exist and I wouldn't know how to change that without wasting a day - it's not what I do usually.

For my local install I could just downgrade to 10.3.16 but the story is that 10.4.6 has a few severe bugs that cause `IN` queries on tables with multiple single column table indexes to not work anymore, I'd love to check if this is resolved with 10.4.7

Would be great, thanks!

**Comment by terinjokes** [comment]
I don't have the time to take a look at this until later today or this weekend.

**Comment by satyago** [comment]
@terinjokes That is perfectly fine. Thank you for the response !

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
14:47:22 [  4%] Linking C static library libpcre.a
14:47:22 cd /tmp/mariadb-20190820-75139-27rg04/mariadb-10.4.7/pcre && /usr/local/Cellar/cmake/3.15.2/bin/cmake -P CMakeFiles/pcre.dir/cmake_clean_target.cmake
14:47:22 cd /tmp/mariadb-20190820-75139-27rg04/mariadb-10.4.7/pcre && /usr/local/Cellar/cmake/3.15.2/bin/cmake -E cmake_link_script CMakeFiles/pcre.dir/link.txt --verbose=1
14:47:22 /usr/bin/ar qc libpcre.a  CMakeFiles/pcre.dir/pcre_byte_order.c.o CMakeFiles/pcre.dir/pcre_chartables.c.o CMakeFiles/pcre.dir/pcre_compile.c.o CMakeFiles/pcre.dir/pcre_config.c.o CMakeFiles/pcre.dir/pcre_dfa_exec.c.o CMakeFiles/pcre.dir/pcre_exec.c.o CMakeFiles/pcre.dir/pcre_fullinfo.c.o CMakeFiles/pcre.dir/pcre_get.c.o CMakeFiles/pcre.dir/pcre_globals.c.o CMakeFiles/pcre.dir/pcre_jit_compile.c.o CMakeFiles/pcre.dir/pcre_maketables.c.o CMakeFiles/pcre.dir/pcre_newline.c.o CMakeFiles/pcre.dir/pcre_ord2utf8.c.o CMakeFiles/pcre.dir/pcre_refcount.c.o CMakeFiles/pcre.dir/pcre_string_utils.c.o CMakeFiles/pcre.dir/pcre_study.c.o CMakeFiles/pcre.dir/pcre_tables.c.o CMakeFiles/pcre.dir/pcre_ucd.c.o CMakeFiles/pcre.dir/pcre_valid_utf8.c.o CMakeFiles/pcre.dir/pcre_version.c.o CMakeFiles/pcre.dir/pcre_xclass.c.o
14:47:22 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpcre.a(pcre_string_utils.c.o) has no symbols
14:47:22 /usr/bin/ranlib libpcre.a
14:47:22 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpcre.a(pcre_string_utils.c.o) has no symbols
14:47:22 [  4%] Built target pcre
14:47:22 make: *** [all] Error 2
14:47:22 
14:47:22 ==> Formula
14:47:22 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mariadb.rb

**Pull request closed without merging**
