### PR TITLE
gateway-go 0.1.97

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Not the latest release on GitHub yet: https://github.com/OpenIoTHub/gateway-go/releases

But I think it's only a matter of time until it becomes the latest release; they're just waiting to finish building the binary artifacts.

**Comment by chenrui333** [comment]
raising an issue now.

**Comment by IoTServ** [comment]
rebuilded,marked as latest release(github actions failed yesterday for snapcraft push failed)

**Comment by chenrui333** [comment]
Thanks @IoTServ!!

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
