### PR TITLE
mitmproxy 2.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mhils** [comment]
@mitmproxy maintainer here - thanks for doing this. I'm not on Mac and so I unfortunately can't test stuff, but I hope this helps:

- We don't depend on Pillow anymore, so this can be removed (including freetype & jpeg dependencies)
- We do not support pyamf anymore (it's Python 2 only), so that can be removed as well.
- 2.0 requires a new dependency: [kaitaistruct](https://pypi.python.org/pypi/kaitaistruct)


Thanks again!
Max

**Comment by ilovezfs** [comment]
@mhils thanks Max. That's why the `do not merge` is on here heh

**Comment by ilovezfs** [comment]
@mhils we should be good now if you want to look it over.

**Comment by mhils** [comment]
Fantastic, thanks! :smiley:

**Pull request closed without merging**
