### PR TITLE
protoc-gen-js 3.21.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>This release consists of mostly minor changes:

* Documentation link fixes
* Updated code generator to work with upstream API changes
* Groundwork for moving to Bazel modules</pre>
</details>

### CODE REVIEW

**Comment by Moisan** [comment]
```
  ERROR: /private/tmp/protoc-gen-js-20240715-4848-ktlwad/protobuf-javascript-3.21.3/generator/BUILD.bazel:1:10: Compiling generator/protoc-gen-js.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //generator:protoc-gen-js) external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 151 arguments skipped)
  
  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  generator/protoc-gen-js.cc:31:10: error: module //generator:protoc-gen-js does not depend on a module exporting 'google/protobuf/compiler/plugin.h'
  #include <google/protobuf/compiler/plugin.h>
           ^
  1 error generated.
```

The issue is known upstream: https://github.com/protocolbuffers/protobuf-javascript/issues/214

**Comment by luangong** [comment]
protoc-gen-js 3.21.4 now depends on the `protobuf` instead of `protobuf@21`.

**Comment by luangong** [comment]
It seems that `protoc-gen-grpc-web` depends on `protoc-gen-js` and `protobuf`, so we should update them in the same commit, but a new release of `protoc-gen-grpc-web` that depends on `protobuf` 27.1 is not yet ready.

**Comment by chenrui333** [comment]
yeah, that is what I saw as well, might be good just close the PR and wait for the `protoc-gen-grpc-web` update and get everything in the protobuf 27 land.

**Pull request closed without merging**
