### PR TITLE
gcc: fix mojave build, numpy: revision bump

### PR DESCRIPTION
**Pull request by carlocab**
Follow up to https://github.com/Homebrew/homebrew-core/pull/67951.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by fxcoudert** [comment]
The numpy revision is probably not necessary, actually. But it doesn't hurt, I guess

**Comment by carlocab** [comment]
Nope, didn't work. The problem might be here, taken from `MacOSX10.14.sdk/usr/include/malloc/_malloc.h`:
```c
#if (__DARWIN_C_LEVEL >= __DARWIN_C_FULL) && \
        ((defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L) || \
         (defined(__cplusplus) && __cplusplus >= 201703L))
void    *aligned_alloc(size_t __alignment, size_t __size) __result_use_check __alloc_size(2) __OSX_AVAILABLE(10.15) __IOS_AVAILABLE(13.0) __TVOS_AVAILABLE(13.0) __WATCHOS_AVAILABLE(6.0);
#endif
```
@gromgit, can you confirm that the above is L47-L51 on your Mojave box?

**Comment by fxcoudert** [comment]
You can see in the gcc make logs, it says:

```
checking for aligned_alloc... yes
```

Maybe because it's not the top-level configure, that variable needs to go in the environment. Let me try.

**Comment by gromgit** [comment]
> @gromgit, can you confirm that the above is L47-L51 on your Mojave box?

Yes, but only for CLT 11.3.1.0.1.1576735732, which matches the Xcode 11.3.1 that's also installed.

I just did a VM Mojave install without Xcode, and on that box, `xcode-select --install` pulled down CLT 10.3.0.0.1.1562985497, which has a different `usr/include/malloc/_malloc.h` that doesn't define `aligned_alloc`.

**Comment by fxcoudert** [comment]
Yeah, it worked!

**Comment by fxcoudert** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/90b04342989feeeee05db7caf06ba9260ae37612

**Pull request closed without merging**
