### PR TITLE
Only install postgresql with pgcli if not already installed.

### PR DESCRIPTION
**Pull request by j-bennet**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This is already what `depends_on :postgresql` will do if the user builds from source. As I mentioned on the other PR, if the user needs to use an older version of postgresql, that's why we have the @ formulae (postgresql@9.5 and postgresql@9.4).

**Comment by j-bennet** [comment]
@ilovezfs This is not what `depends_on :postgresql` does. We had that in the formula before, and the users' postgresql was updated unnecessarily, leading to loss of data etc. I don't see how merging this would be a problem. Can you please explain?

**Comment by ilovezfs** [comment]
It is what it does _if the user builds from source_ but not what it does if the user pours the bottle, as this case with all requirements that have a default formula. There are 29 formulae in core with a required or recommended `"postgresql"` or `:postgresql` requirement. There's nothing unusual here with `pgcli` that requires different handling as far as I can tell.

**Comment by ilovezfs** [comment]
Specifically: https://github.com/Homebrew/brew/blob/60f6dfea14c9f5a070334c6341b2a39c9bdc4163/Library/Homebrew/requirements.rb#L63-L68

**Comment by MikeMcQuaid** [comment]
> leading to loss of data etc.

I'm afraid I need to correct this: `brew upgrade postgresql` whether run manually or automatically will not cause data loss. If the user (re)starts postgresql through `brew services` or a system restart then the database may need migrated to the later data format so it works. The user should be pointed towards formulae like `postgresql@9.5` which will prevent these upgrades from occurring. Thanks!

**Comment by j-bennet** [comment]
> It is what it does if the user builds from source but not what it does if the user pours the bottle.

This is not what I see. In the example below, I have postgresql 9.5.3 installed:

```
--- src/homebrew-core ‹master*?› » brew list --versions postgresql
postgresql 9.5.3
```

I am not building from source:

```
--- src/homebrew-core ‹master*?› » brew install pgcli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/science).
==> New Formulae
fsql
==> Updated Formulae
homebrew/science/swetest               juju                                   juju@1.25                              urh
==> Installing dependencies for pgcli: postgresql
==> Installing pgcli dependency: postgresql
==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.6.3.sierra.bottle.tar.gz
Already downloaded: /Users/irina/Library/Caches/Homebrew/postgresql-9.6.3.sierra.bottle.tar.gz
==> Pouring postgresql-9.6.3.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/legacy-homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.0) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/upgrading.html

To migrate existing data from a previous minor version (9.0-9.5) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/pgupgrade.html

  You will need your previous PostgreSQL installation from brew to perform `pg_upgrade`.
  Do not run `brew cleanup postgresql` until you have performed the migration.

To have launchd start postgresql now and restart at login:
  brew services start postgresql
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgres start
==> Summary
🍺  /usr/local/Cellar/postgresql/9.6.3: 3,259 files, 36.6MB
==> Installing pgcli
==> Downloading https://homebrew.bintray.com/bottles/pgcli-1.5.1.sierra.bottle.tar.gz
Already downloaded: /Users/irina/Library/Caches/Homebrew/pgcli-1.5.1.sierra.bottle.tar.gz
==> Pouring pgcli-1.5.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pgcli/1.5.1: 510 files, 5.4MB
```

Even though "loss of data" might have been the wrong term, I don't think it's a good idea to upgrade the users' databases and mess with their workflow, unless they explicitly stated that they want to upgrade postgresql.

**Comment by MikeMcQuaid** [comment]
> I am not building from source:

The behaviour you describe is expected unless you are building from source.

> upgrade the users' databases

We do not upgrade their databases, we upgrade their database software to a newer version and the old version is still installed until then run `brew cleanup`.

> I don't think it's a good idea to upgrade .. unless they explicitly stated that they want to upgrade postgresql.

This is not how we or the majority of package managers behave. We cannot support having arbitrary versions of everything in the dependency tree as it's nearly impossible to debug issues. I appreciate that you're trying to help your user here and that's admirable but I'd like to gently ask that you defer to our experience with how to support a widely used package manager at scale.

**Comment by j-bennet** [comment]
It is exactly because you know better that I asked you in my first PR - what **is** the recommended way of doing what I am trying to do, i.e. keep the user at their preferred version of postgresql while still being able to install pgcli? You mentioned @-formulae above. How should the user run `brew install pgcli` so as to indicate that he also wants postgresql@9.5 or postgresql@9.4? What additional options would he have to provide?

**Comment by MikeMcQuaid** [comment]
> It is exactly because you know better that I asked you in my first PR - what is the recommended way of doing what I am trying to do, i.e. keep the user at their preferred version of postgresql while still being able to install pgcli?

Have the user use `postgresql@9.5` for their database server and ignore any changes to `postgresql` versions which will end up pulled in as a dependency.

**Comment by j-bennet** [comment]
@MikeMcQuaid You mean the user would have to `brew install pgcli`, and then `brew switch postgresql 9.5.3`?

**Comment by MikeMcQuaid** [comment]
@j-bennet The user should `brew uninstall --force postgresql`, `brew services stop postgresql`, `brew install postgresql@9.5`, configure and setup that database e.g. `brew services start postgresql@9.5` and then `brew install pgcli` and ignore the `postgresql` formula.

**Comment by j-bennet** [comment]
This sounds like a lot of work, and all for something that is not even really a dependency of pgcli. pgcli needs psycopg2, it does not necessarily need postgresql on the person's machine. Is there really no way to do this with less inconvenience for the user?

**Comment by MikeMcQuaid** [comment]
> Is there really no way to do this with less inconvenience for the user?

Correct, there is no other way we support.

**Comment by amjith** [comment]
@MikeMcQuaid and @ilovezfs Thank you for clarifying the various ways to workaround. 

I'm still missing the point behind the original reasoning.

The changes submitted by @j-bennet seems to satisfy the needs of pgcli while complying with the guidelines of brew. I understand that if the user builds pgcli from source then it won't upgrade an existing installation of postgresql. But that is not the default way in which users install brew packages. 

Even though I'm a core dev on pgcli I've accidentally run brew install pgcli which upgraded my postgres rendering my databases useless. It took me a better part of a morning trying to migrate my databases to work with the new version. 

Apparently I'm not the only one who has done it and that's what triggered this change request. 

You've raised a poignant issue with this point: 

> We cannot support having arbitrary versions of everything in the dependency tree as it's nearly impossible to debug issues.

The change that @j-bennet has submitted doesn't require a specific version of postgresql. We're in fact requesting the exact opposite, we're being extremely liberal with the postgres version and being cautious about unnecessarily disrupting an existing installation if it exists. 

I hope you'll reconsider the rejection and provide us with an easier way. 

Thank you!

**Comment by MikeMcQuaid** [comment]
> Even though I'm a core dev on pgcli I've accidentally run brew install pgcli which upgraded my postgres rendering my databases useless. It took me a better part of a morning trying to migrate my databases to work with the new version.

You should not be trying to have Homebrew packages sit on old versions by just not upgrading them.

> postgres rendering my databases useless

Again, this is wrong and people should stop saying it. Your database server is not restarted by a `brew upgrade`. Your old database version is not removed by a `brew upgrade`.

> The change that @j-bennet has submitted doesn't require a specific version of postgresql. We're in fact requesting the exact opposite, we're being extremely liberal with the postgres version and being cautious about unnecessarily disrupting an existing installation if it exists.

Yes, which is exactly my point. If this breaks with a postgresql 0.0.1 formula or postgresql 9.9.9 formula then Homebrew is going to get support issues about that. That's not acceptable to us. We will install the version for users in the default configuration which is known to work. You're attempting to override Homebrew's behaviour for all other packages which is specifically chosen.

> I hope you'll reconsider the rejection and provide us with an easier way.

The way I've described above is easier, it's just not what you're doing today and requires change on your part.

**Comment by MikeMcQuaid** [comment]
> I'm still missing the point behind the original reasoning.

To be clear, we've gone way beyond what we would normally do in terms of explaining our justification and workaround here. We're a very active and understaffed project and I don't think the onus is on us to why the internals of Homebrew are the way they are (or, more accurately, why we will not be changing the current behaviour).

> while complying with the guidelines of brew.

The guidelines of Homebrew are decided by the maintainers. Within the maintainers, primarily this is myself and @ilovezfs. Given we're in agreement about this PR: this does not meet our guidelines, sorry.

**Comment by amjith** [comment]
Thank you for your response. I can understand why you're reluctant to accept this change. If we had this conversation in person we could have come to an amicable agreement.

I don't want to waste your time by arguing any further. I'd like to withdraw the pgcli formula from the official repos. 

The reason is simple. I don't want a homebrew user to install pgcli on their machine and suddenly realize that their postgresql got upgraded as a side-effect. This will only make them angry at pgcli.

Thank you for taking the time to answer all of our questions patiently. 

Perhaps we'll run into a conference sometime in the future and we can hash it out in person. 😄 

Ref: https://github.com/Homebrew/homebrew-core/pull/14078

**Comment by MikeMcQuaid** [comment]
Latest status here: https://github.com/Homebrew/homebrew-core/pull/14078#issuecomment-316003520

**Pull request closed without merging**
