### PR TITLE
ext2fuse: Fix dependence issue

### PR DESCRIPTION
**Pull request by iMonZ**
Fix dependence issue

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
The requirement on FUSE (and the fact that the macOS implementation is not open source is still a problem). Renaming the dependency will not solve this.

**Comment by iMonZ** [comment]
> The requirement on FUSE (and the fact that the macOS implementation is not open source) is still a problem. Renaming the dependency will not solve this.

But with the cask as a dependency it will still work.
Do you know what I am doing wrong?

**Comment by SMillerDev** [comment]
> But with the cask as a dependency it will still work.

It will work, but it's against our policy of shipping only open-source software in homebrew core.

**Comment by Bo98** [comment]
`depends_on :macfuse` is not valid syntax. The colon prefix doesn't mean cask dependency - it means to use the `brew`'s requirement system (so installing `osxfuse` outside of Cask works too). The list of valid values is limited: https://github.com/Homebrew/brew/blob/b8d55e5a777e31acdd43ad2bbba14835b1f11ae9/Library/Homebrew/dependency_collector.rb#L121-L129.

`OsxfuseRequirement` has however been disabled in Homebrew 3.0.0 so we won't be making any further changes to it - that includes adding `macfuse` support as we no longer allow formulae to depend on casks.

Formulae which currently have a `depends_on :osxfuse` will likely be removed (or rather, made Linux only) in Homebrew 3.1.0.

**Comment by iMonZ** [comment]
> `depends_on :macfuse` is not valid syntax. The colon prefix doesn't mean cask dependency - it means to use the `brew`'s requirement system (so installing `osxfuse` outside of Cask works too). The list of valid values is limited: https://github.com/Homebrew/brew/blob/b8d55e5a777e31acdd43ad2bbba14835b1f11ae9/Library/Homebrew/dependency_collector.rb#L121-L129.
> 
> `OsxfuseRequirement` has however been disabled in Homebrew 3.0.0 so we won't be making any further changes to it - that includes adding `macfuse` support as we no longer allow formulae to depend on casks or other external non-system dependencies.
> 
> Formulae which currently have a `depends_on :osxfuse` will likely be removed (or rather, made Linux only) before Homebrew 3.1.0.

Oh this is very sad :( so should this cask have a requirement for <= Catalina?

**Comment by SMillerDev** [comment]
> Oh this is very sad :( so should this cask have a requirement for <= Catalina?

Homebrew deprecating this has nothing to do with the macOS version. The cask will continue to work just fine. It is just no longer allowed in homebrew/core formulae.

**Comment by iMonZ** [comment]
> > Oh this is very sad :( so should this cask have a requirement for <= Catalina?
> 
> Homebrew deprecating this has nothing to do with the macOS version. The cask will continue to work just fine. It is just no longer allowed in homebrew/core formulae.

It has.
This cask does not work with BigSur or higher except you add the mac fuse dependency because the osxfuse dependency does not work with newer macOS versions.

This cask has a time bomb, so it will be removed in a year and my recommendation is to remove the time bomb and add the requirement that the macOS version must be under BigSur.

**Comment by gromgit** [comment]
> my recommendation is to remove the time bomb and add the requirement that the macOS version must be under BigSur.

Or you could do what I did, and start [a third-party tap specifically for FUSE-related stuff](https://github.com/gromgit/homebrew-fuse/), with a custom requirement that is a close copy of the existing `OsxfuseRequirement`.

**Comment by Bo98** [comment]
> osxfuse dependency does not work with newer macOS versions

osxfuse 3.11.2 should work with Big Sur.

> This cask has a time bomb, so it will be removed in a year and my recommendation is to remove the time bomb and add the requirement that the macOS version must be under BigSur.

`depends_on :osxfuse` won't work on _any_ macOS version when Homebrew 3.1.0 releases (in fact `depends_on :osxfuse` is supposed to print an error that it's no loner supported - I'm not sure why that's not working properly at the moment).

I actually suggest changing the `deprecate!` to `disable!`, to match the status of `depends_on :osxfuse`. Then when Homebrew 3.1.0 is released, these formulae will move to `depends_on :linux`.

**Comment by carlocab** [comment]
This formula has been disabled.

**Pull request closed without merging**
