### PR TITLE
Icu4c 66.1

### PR DESCRIPTION
**Pull request by pOmelchenko**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Updated icu4c and all dependent formulas.

P.S.: I hope that on second try I will made all right ☺️

### CODE REVIEW

**Comment by pOmelchenko** [comment]
Who can help with solving problems? I was think I made all correct but CI failed and now I don't understand what happens

**Comment by Bo98** [comment]
These still need revision bumping:
* gjs
* ncmpcpp
* vte3

**Comment by pOmelchenko** [comment]
> These still need revision bumping:
> 
> * gjs
> * ncmpcpp
> * vte3

Thx! But why? I don't see relations with `icu4c`

**Comment by Bo98** [comment]
The CI detected that the current bottles are linking against icu4c (via `brew linkage --test`). It is likely the case that icu4c is there as a dependency of another dependency. Arguably there should be a `depends_on "icu4c"` there to be more implicit, but no one noticed since it was being pulled in as a dependency anyway.

For example, ncmpcpp depends on boost which depends on icu4c. icu4c is therefore a dependency of ncmpcpp because boost needs it, but ncmpcpp happens to also actually use icu4c directly.

**Comment by pOmelchenko** [comment]
I'm understood, thank you

**Comment by pOmelchenko** [comment]
Guys, I need help, again. I'm right in my mind about dependents? If I run that command `brew uses icu4c --recursive` I got full list of packages which I must bumping for correct building?

I'm not sure but I got list of 450+ names. It's really correct?

**Comment by Bo98** [comment]
No you don't need to revision bump every single one. In some cases, you might not even need to do every one at the first level `brew uses`. The best way really is to see what the CI says.

It looks like you've covered everything, but it's just that some of them, like `mapnik`have compile errors. See #48349 for a previous attempt. It looks like not much has changed since.

**Comment by SMillerDev** [comment]
Mapnik had a release since then. Updating a release is preferable over version bumping

**Pull request closed without merging**
