### PR TITLE
gcc 8.2.0

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
was going to leave this for fx but off we go ...

**Comment by DomT4** [comment]
Apologies. I figured it was going to take ages on CI & wanted to get a start on that.

**Comment by ilovezfs** [comment]
no worries

**Comment by DomT4** [comment]
The latest `opencoarrays` still doesn't built FWIW, even though [this patch](https://raw.githubusercontent.com/sourceryinstitute/OpenCoarrays/9e6f2cb0e6ad6c385ec2c941ce51aa29740bca2c/prerequisites/build-functions/patches/gcc/8.1.0/partially-revert-rev259385.diff) is in this `gcc` release.

```
[  6%] Building C object src/tests/unit/iso-fortran-binding/CMakeFiles/ISO_Fortran_binding_tests.dir/ISO_Fortran_binding_tests.c.o
cd /tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/build/src/tests/unit/iso-fortran-binding && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -DPREFIX_NAME=_gfortran_caf_ -I/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src -I/usr/local/include -I/usr/local/Cellar/open-mpi/3.1.1/lib -I/usr/local/Cellar/open-mpi/3.1.1/include  -DNDEBUG   -o CMakeFiles/ISO_Fortran_binding_tests.dir/ISO_Fortran_binding_tests.c.o   -c /tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:82:15: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
              CFI_CDESC_T (rank) test1;
              ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:95:24: note: expanded from macro 'CFI_CDESC_T'
#define CFI_CDESC_T(r) CFI_CDESC_TYPE_T (r, void)
                       ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:93:27: note: expanded from macro 'CFI_CDESC_TYPE_T'
                CFI_dim_t dim[r]; \
                          ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:168:15: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
              CFI_CDESC_T (rank) test2;
              ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:95:24: note: expanded from macro 'CFI_CDESC_T'
#define CFI_CDESC_T(r) CFI_CDESC_TYPE_T (r, void)
                       ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:93:27: note: expanded from macro 'CFI_CDESC_TYPE_T'
                CFI_dim_t dim[r]; \
                          ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:310:15: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
              CFI_CDESC_T (rank) test3;
              ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:95:24: note: expanded from macro 'CFI_CDESC_T'
#define CFI_CDESC_T(r) CFI_CDESC_TYPE_T (r, void)
                       ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:93:27: note: expanded from macro 'CFI_CDESC_TYPE_T'
                CFI_dim_t dim[r]; \
                          ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:362:3: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
  CFI_CDESC_T (rank) test4;
  ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:95:24: note: expanded from macro 'CFI_CDESC_T'
#define CFI_CDESC_T(r) CFI_CDESC_TYPE_T (r, void)
                       ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:93:27: note: expanded from macro 'CFI_CDESC_TYPE_T'
                CFI_dim_t dim[r]; \
                          ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:377:3: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
  CFI_CDESC_T (rank) test5;
  ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:95:24: note: expanded from macro 'CFI_CDESC_T'
#define CFI_CDESC_T(r) CFI_CDESC_TYPE_T (r, void)
                       ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:93:27: note: expanded from macro 'CFI_CDESC_TYPE_T'
                CFI_dim_t dim[r]; \
                          ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:413:7: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
      CFI_CDESC_T (rank) test6;
      ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:95:24: note: expanded from macro 'CFI_CDESC_T'
#define CFI_CDESC_T(r) CFI_CDESC_TYPE_T (r, void)
                       ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/../../../iso-fortran-binding/ISO_Fortran_binding.h:93:27: note: expanded from macro 'CFI_CDESC_TYPE_T'
                CFI_dim_t dim[r]; \
                          ^
/tmp/opencoarrays-20180726-66443-1k3vcnb/OpenCoarrays-2.1.0/src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c:460:11: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
          CFI_CDESC_T (rank) test7;
          ^
[snip]
```

**Comment by ilovezfs** [comment]
Right: https://github.com/sourceryinstitute/OpenCoarrays/issues/549 https://github.com/sourceryinstitute/ISO_Fortran_binding/issues/5

**Comment by ilovezfs** [comment]
🚀 

Thanks @DomT4

**Comment by DomT4** [comment]
Thanks @ilovezfs. Those upstream issues seem... fun 🙃. At least the existing release builds okay & we're not stuck waiting.

**Pull request closed without merging**
