### PR TITLE
pypy 5.9.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
Any chance we can update the outdated `setuptools`, since that is not updated out-of-band often given `pypy`'s build time? The whole `stable do` block is redundant here too, but that's less annoying.

**Comment by alex** [comment]
Will do after the meeting I'm in :-)

**Comment by alex** [comment]
@DomT4 done.

**Comment by DomT4** [comment]
Thanks @alex ❤️.

@ilovezfs If you're around the first build probably wants killing given `pypy`'s delightful build time.

**Comment by ilovezfs** [comment]
Thanks @alex!

:snake: :snake:

**Pull request closed without merging**
