### PR TITLE
elm-format 0.8.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by Rylan12** [comment]
Looks like it's still a prerelease.

**Comment by chenrui333** [comment]
looking at their releases, they are all pre-release. We might need to consider still rollout.

**Comment by SMillerDev** [comment]
Please ask upstream if they're going to change this.

**Comment by SMillerDev** [comment]
Did we ask if upstream will switch away from pre-releases?

**Review by dtrodrigues — APPROVED** [review]
It's no longer a pre-release: https://github.com/avh4/elm-format/releases/tag/0.8.4

**Pull request closed without merging**
