### PR TITLE
llnode: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
@Homebrew/brew this audit failure seems wrong.  I thought we had decided to allow to `OS.linux?`/`OS.mac?` inside of blocks and methods.  Maybe we overlooked allowing it inside `resource` blocks?

**Comment by MikeMcQuaid** [comment]
> @Homebrew/brew this audit failure seems wrong. I thought we had decided to allow to `OS.linux?`/`OS.mac?` inside of blocks and methods. Maybe we overlooked allowing it inside `resource` blocks?

Not all blocks and methods.

**Comment by danielnachun** [comment]
@MikeMcQuaid would it be reasonable to more broadly allow `OS.mac?`/`OS.linux?` statements in other blocks and methods?  I can open an issue in @Homebrew/brew if that would be a better place to discuss this.

**Comment by MikeMcQuaid** [comment]
@danielnachun We can consider it but basically we don't want to use `if` if there's any conceivable reason we'd want to e.g. output those different URL on different platforms in `brew info` or formulae.brew.sh. As a result, I personally think it's pretty much only things that are run but don't produce output e.g. test/install that should use `if`.

**Comment by danielnachun** [comment]
I see, that's a very helpful explanation.  I was under the impression that the desire was generally to prefer `if` statements for cleaner syntax, but there's clearly good reasons to prefer `on_linux`/`on_macos` blocks that I was not aware of.  I'm going to revise this PR and the other similar one to avoid using the `if` statements rather than changing any audits.

**Comment by MikeMcQuaid** [comment]
@danielnachun Thanks for understanding! ❤️

**Comment by danielnachun** [comment]
The audit issues are fixed and this should be ready to go now.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
