### PR TITLE
chapel: fix chpldoc installation problem

### PR DESCRIPTION
**Pull request by arezaii**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Fixes a bug that prevented `chpldoc` from being installed even though it was built. Injects a new Makefile target temporarily until the next version of Chapel is released.

Enables some testing of `chpldoc` that was previously disabled.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @arezaii!

**Comment by arezaii** [comment]
> ⚠️ Bottle publish [failed](https://github.com/Homebrew/homebrew-core/actions/runs/8679745798).

hmm...I'm unsure if this is something I need to address

**Comment by arezaii** [comment]
> blocked by #165206

I see, thank you! This version of Chapel doesn't officially support use with LLVM 18. The homebrew maintainers previously asked me to remove the version pinning at 17 since it was the canonical version at the time, but I think that will be needed before #165206 can be merged.

**Comment by chenrui333** [comment]
> > blocked by #165206
> 
> I see, thank you! This version of Chapel doesn't officially support use with LLVM 18. The homebrew maintainers previously asked me to remove the version pinning at 17 since it was the canonical version at the time, but I think that will be needed before #165206 can be merged.

we can switch to llvm@17, any issue tracker for llvm 18 support?

**Comment by arezaii** [comment]
> we can switch to llvm@17, any issue tracker for llvm 18 support?

yes, but it's tracked in a private issue. We expect it will be supported in the June release of Chapel 2.1.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
we are gonna rerun #165206, so merging this for now. thanks for the wait.

**Pull request merged**
