### PR TITLE
menhir 20200211

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Possible packaging bug? There's no root-level `Makefile`, even though it's still referenced by another file. It's in the git repository but not the distributed tarball.

**Comment by Bo98** [comment]
Upstream say ["someone who wishes to install Menhir from source should use the master branch, not the release commit."](https://gitlab.inria.fr/fpottier/menhir/issues/33#note_306972)

**Comment by SMillerDev** [comment]
So... Don't use releases?

**Comment by Bo98** [comment]
That's basically the message. No tagged source releases for anyone except a special one for opam.

Considering the majority of the Makefile was just lines upon lines of deleting files as a part of their release process, I suppose we could just deal with it being missing and just do `dune build @install` & `dune install`.

**Comment by zachauten** [comment]
@Bo98 I'm not really familiar with ocaml or dune; Running `dune build @install` and `dune install` give this error; looks like a file named `fix.install` is missing? 
```
/private/tmp/menhir-20200309-78372-idloe4/menhir-20200211👉 dune build @install
        pack lib/pack/menhirLib.{ml,mli}
Creating menhirLib.ml...
Creating menhirLib.mli...
      menhir src/stage2/parserMessages.check
Read 101 sample input sentences and 101 error messages.
Read 101 sample input sentences and 48 error messages.
      menhir src/stage2/parser.{ml,mli}
Grammar has 56 nonterminal symbols, among which 1 start symbols.
Grammar has 37 terminal symbols.
Grammar has 129 productions.
Built an LR(0) automaton with 194 states.
The grammar is not SLR(1) -- 5 states have a conflict.
The construction mode is no-pager.
Built an LR(1) automaton with 298 states.
One shift/reduce conflict was silently solved.
Extra reductions on error were added in 40 states.
Priority played a role in 0 of these states.
152 out of 298 states have a default reduction.
102 out of 298 states are represented.
44 out of 96 symbols keep track of their start position.
48 out of 96 symbols keep track of their end position.
The action table is 11324 entries; 1610 non-zero; 1359 compressed.
The action table occupies roughly 2816 bytes.
The goto table is 16986 entries; 329 non-zero; 636 compressed.
The goto table occupies roughly 1368 bytes.
The error table occupies roughly 1448 bytes.
The default_reduction table occupies roughly 336 bytes.
The lhs table occupies roughly 168 bytes.
The trace table occupies roughly 8 bytes.
      menhir src/stage2/parserMessages.ml
Read 101 sample input sentences and 48 error messages.
/private/tmp/menhir-20200309-78372-idloe4/menhir-20200211👉 dune install
Error: The following <package>.install are missing:
- _build/default/fix/fix.install
Hint: try running: dune build @install
/private/tmp/menhir-20200309-78372-idloe4/menhir-20200211👉 
```

**Comment by Bo98** [comment]
This needs rebasing onto master, but apart from that try add `--prefix=#{prefix}` to the `dune install` line.

**Comment by Bo98** [comment]
It probably also needs `--mandir=#{man}`. I forgot about that one - sorry!

**Pull request closed without merging**
