### PR TITLE
dbus 1.11.4 (devel)

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by DomT4** [comment]
Although you need to squash your commits :trollface:

**Comment by ilovezfs** [comment]
>Although you need to squash your commits :trollface:

Can you provide step-by-step instructions on how to do this please, the more detail the better? :innocent:

**Comment by MikeMcQuaid** [comment]
Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master` and then mark each commit other than the first as `squash` or `fixup` then `git push -f`. Thanks!

**Comment by ilovezfs** [comment]
LOL

**Comment by MikeMcQuaid** [comment]
(TextExpander 👋)

**Comment by ilovezfs** [comment]
@MikeMcQuaid I was hoping for a dissertation from @DomT4

**Comment by DomT4** [comment]
Since this is devel rather than stable, `Merge pull request` => `Confirm squash and merge`. You're welcome 😉.

**Comment by ilovezfs** [comment]
But I'm allergic to GUIs.

**Comment by DomT4** [comment]
Ah, this is not the UNIX operating system you were looking for; you wanted OpenBSD apparently 😄.

**Comment by ilovezfs** [comment]
Are you saying I'm not supposed to run in single user mode all the time?

**Pull request closed without merging**
