### PR TITLE
rswift 3.0.0

### PR DESCRIPTION
**Pull request by tomasharkema**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
doesn't this have an xcode 8 dependency?

**Comment by tomasharkema** [comment]
your absolutely right. fixed it.

**Comment by ilovezfs** [comment]
thanks Tomas!

**Review by DomT4 — COMMENTED** [review]
We'll need to sit on this until we've got El Cap running Xcode 8, so this can actually be tested/bottled.

**Comment by tomasharkema** [comment]
Allright. Keep me posted!

**Comment by zmwangx** [comment]
@BrewTestBot Test this please.

**Comment by zmwangx** [comment]
Due to recent style changes I rebased this on master. I'll merge once CI is green (should be, since I only made style changes).

**Comment by zmwangx** [comment]
Merged as 999f7e6. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
