### PR TITLE
neo4j 3.1.4

### PR DESCRIPTION
**Pull request by tuddman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hi @tuddman could you provide a new PR from a clean branch, to avoid conflicts? Thanks!

**Comment by tuddman** [comment]
@fxcoudert sorry. I resolved conflict from carrying forward the old version.  GH can squash commits before merging.  is that alright?

**Review by tuddman — COMMENTED** [review]
remove whitespace

**Comment by tuddman** [comment]
closing this one. will open a clean one.

**Pull request closed without merging**
