### PR TITLE
qscintilla2, octave: use qt

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by bayandin — APPROVED** [review]

**Comment by mmuetzel** [comment]
This seems to have broken using the graphical user interface for users:
https://octave.discourse.group/t/octave-8-3-0-1-no-gui/4810

Support for Qt6 in Octave is currently worked on and might be available in Octave 9 or later:
https://octave.discourse.group/t/transition-octave-to-qt6/3139

Please, consider reverting this change.

**Comment by mdb5** [comment]
That is interesting.  
I see that I have qt version 6.5.1_3 installed.  qt@5 is also still there.  How do you force an older or different version of qt to be used when installing Octave from homebrew?  Or do I backtrack and install an older version of qt? Which version?

**Comment by mmuetzel** [comment]
@mdb5: I don't know if I understand your question correctly.
Octave has to be *built* with Qt5. Afaict, there is no way to switch between Qt6 and Qt5 after it was built.
The binaries that are distributed by Homebrew should be rebuilt linking to Qt5 again.

Alternatively, you might be able to rebuild Octave locally linking to Qt5. I can't help with that though because I don't have access to any macOS systems.

**Comment by mdb5** [comment]
After doing a brew/reinstall of octave with verbose on, the feedback looks to me like homebrew is pulling files from ***@***.***, which I suspect is homebrew’s way of providing a library of qt5 legacy software.

Still get runtime message when attempting: octave —gui :

    octave: GUI features missing or disabled in this build

I can run Octave in command line mode only.

The octave support people say it is a homebrew problem.

**Comment by mmuetzel** [comment]
The following page says that the homebrew package for Octave depends on Qt 6.5.1.
The configure script of Octave 8.x doesn't yet have any logic to find Qt6. So, it was likely configured to build without GUI.
Additionally, this PR reverted some flags that -- according to the accompanying comments -- were necessary to get Qt5 to work for Octave with Homebrew. So, even if Qt5 is still installed, it would likely not get picked up any more.

I don't know how to bring the point across to you. So trying to be as clear as I possibly can: Revert this change, and it will likely work again.
I don't know if this is something you can do in Homebrew locally. Maybe, you'll have to wait until the distributed binaries are updated again after a revert in Homebrew.

**Comment by mdb5** [comment]
Understood.  I wonder how long it will be before this is resolved?

I do not know how to revert to an older version of Octave.  It does not seem as simple as just restoring the previous Octave version folder from my time machine backup.  There appear to be other compatible libraries that need to be restored to other folders, as well, and that seems too complicated to figure out without breaking things.  It seems Homebrew does not provide a way to install previous versions of Octave.

Maybe try the other approach of building Octave locally from source?  I think I stumbled through that once successfully, but not sure I remember how.

**Comment by mdb5** [comment]
So, I get these errors/warnings listed in the verbose output of the brew build script (build from source and using gcc-13)...

checking Qt version 5... checking for Qt5Core Qt5Gui Qt5Help Qt5Network Qt5PrintSupport Qt5Xml... no
configure: WARNING: Qt libraries not found; disabling Qt GUI

I suspect this is flagging a key problem.

***@***.*** is installed.  The needed folder names are found in this folder:
          ***@***.***/5.15.10_1/lib/cmake

How do I get the install script to find these files?

**Comment by iMichka** [comment]
Sorry for breaking things. I was under the impression octave was fine, the build did not complain when fed with qt 6 flags and paths. I have opened a pull request to revert my change: #141309

QT 5 is EOL as far as I know, and we are having more and more trouble keeping it building on newer operating systems.
This might lead to the removal of octave and the whole qt 5 stack one day, which might come sooner than expected.
I really hope the octave devs can speed up things in https://octave.discourse.group/t/transition-octave-to-qt6/3139

**Comment by mmuetzel** [comment]
> I really hope the octave devs can speed up things

If you're interested in a speedy adoption, there is a macOS specific bug that needs attention from someone who knows their way around that platform:
https://savannah.gnu.org/bugs/?64498

Any help would be appreciated. 👍

**Comment by iMichka** [comment]
I see, looking at https://bugreports.qt.io/browse/QTBUG-86080, @fxcoudert made a comment on it, so at least one Homebrew maintainer already looked into it. Fixing this looks like some major effort; we need to add .pc files back in the qt macOS build ...

**Comment by fxcoudert** [comment]
@mmuetzel we are aware: I was the one who opened the bug, a month ago. There was no response, no comment.

**Comment by mmuetzel** [comment]
@fxcoudert: Are you referring to the report on the Octave bug tracker?
I asked over there how projects that use autotools/gmake as their build system can detect how to include and link to Qt6 on macOS. Do you have any recommendations?

**Comment by fxcoudert** [comment]
@mmuetzel apologies, I thought I had replied: pkg-config detection can usually be bypassed by environment variables, we do that for gnuplot and it works.

**Comment by mmuetzel** [comment]
@fxcoudert: In case, you are nor receiving notifications for the email address that you register on that bug tracker: I left a couple of comments there.

**Comment by fxcoudert** [comment]
A new pull request to use Qt 6 is under testing: https://github.com/Homebrew/homebrew-core/pull/141675

**Comment by mmuetzel** [comment]
Support for Qt6 is still in development for Octave. It will hopefully be ready for Octave 9. Octave 8 doesn't support it yet.

**Pull request merged**
