### PR TITLE
apache-arrow apache-arrow-glib 15.0.0

### PR DESCRIPTION
**Pull request by timsutton**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by timsutton** [comment]
Will test bumping revision of `vineyard`

**Comment by chenrui333** [comment]
@timsutton I think the other revisions are also tied with apache-arrow change like

```
  ==> /opt/homebrew/Cellar/gdal/3.8.3/bin/gdalinfo --formats
  dyld[15714]: Library not loaded: /opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1400.dylib
    Referenced from: <74D7B054-C82A-39CC-B61D-8BECFC608AE6> /opt/homebrew/Cellar/gdal/3.8.3/lib/libgdal.34.3.8.3.dylib
    Reason: tried: '/opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1400.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1400.dylib' (no such file), '/opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1400.dylib' (no such file), '/opt/homebrew/Cellar/apache-arrow/15.0.0/lib/libarrow_dataset.1400.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/apache-arrow/15.0.0/lib/libarrow_dataset.1400.dylib' (no such file), '/opt/homebrew/Cellar/apache-arrow/15.0.0/lib/libarrow_dataset.1400.dylib' (no such file)
```

**Comment by raulcd** [comment]
It seems vineyard has to be updated for arrow 15.0.0, right?
```
  In file included from /tmp/vineyard-20240122-87256-on1dbr/v6d-0.20.2/modules/basic/ds/arrow_shim/concatenate.cc:67:
  /opt/homebrew/include/arrow/visit_type_inline.h:54:34: error: no matching member function for call to 'Visit'
      ARROW_GENERATE_FOR_ALL_TYPES(TYPE_VISIT_INLINE);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  /opt/homebrew/include/arrow/visitor_generate.h:43:3: note: expanded from macro 'ARROW_GENERATE_FOR_ALL_TYPES'
    ACTION(StringView);                           \
    ^~~~~~~~~~~~~~~~~~
  /opt/homebrew/include/arrow/visit_type_inline.h:29:21: note: expanded from macro 'TYPE_VISIT_INLINE'
      return visitor->Visit(internal::checked_cast<const TYPE_CLASS##Type&>(type), \
             ~~~~~~~~~^~~~~
  /tmp/vineyard-20240122-87256-on1dbr/v6d-0.20.2/modules/basic/ds/arrow_shim/concatenate.cc:255:19: note: in instantiation of function template specialization 'arrow::VisitTypeInline<vineyard::arrow_shim::(anonymous namespace)::ConcatenateImpl>' requested here
      RETURN_NOT_OK(VisitTypeInline(*out_->type, this));
                    ^
  /tmp/vineyard-20240122-87256-on1dbr/v6d-0.20.2/modules/basic/ds/arrow_shim/concatenate.cc:260:10: note: candidate function not viable: no known conversion from 'const arrow::StringViewType' to 'const NullType' for 1st argument
    Status Visit(const NullType&) { return Status::OK(); }
           ^
```

**Comment by timsutton** [comment]
>It seems vineyard has to be updated for arrow 15.0.0, right?

It would appear so. Do you happen to know if there's already any upstream issue or tracker we could reference for that?

**Comment by raulcd** [comment]
> Do you happen to know if there's already any upstream issue or tracker we could reference for that?

No sorry, I am an Apache Arrow committer but I don't work with vineyard.

**Comment by raulcd** [comment]
I took a look on the vineyard repo and as I did not see any issue opened I opened a new issue: https://github.com/v6d-io/v6d/issues/1728

**Comment by timsutton** [comment]
@raulcd was just about to do the same and then saw you did already. Thank you!

**Comment by sighingnow** [comment]
> I took a look on the vineyard repo and as I did not see any issue opened I opened a new issue: [v6d-io/v6d#1728](https://github.com/v6d-io/v6d/issues/1728)

Addressed by https://github.com/v6d-io/v6d/releases/tag/v0.20.3

**Review by p-linnane — APPROVED** [review]
Thanks for the collaboration here everyone! @sighingnow is always great about pushing quick updates when we hit these issues with major `apache-arrow` upgrades.

**Comment by timsutton** [comment]
@p-linnane Could you help me with adding the long build label? I think the macOS 12 x86_64 build timed out?

**Pull request merged**
