### PR TITLE
gnutls 3.6.13

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
See #52457, #52682

**Comment by SMillerDev** [comment]
Thanks, shouldn't brew-bump-formula warn about that?

**Comment by chenrui333** [comment]
Yeah, I think I did bring this up before is the brew-bump-formula should detect the previously failed PRs.

**Comment by chenrui333** [comment]
Running an issue in https://github.com/Homebrew/homebrew-core/pull/52944

```
configure: error: DTLS is insecure in GnuTLS v3.6.3 through v3.6.12.
```

**Comment by chenrui333** [comment]
```
14:27:43 ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
14:27:43 clang: error: linker command failed with exit code 1 (use -v to see invocation)
14:27:43 make[3]: *** [ocsptool] Error 1
14:27:43 ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
14:27:43 clang: error: linker command failed with exit code 1 (use -v to see invocation)
14:27:43 make[3]: *** [danetool] Error 1
14:27:43 make[2]: *** [install-recursive] Error 1
14:27:43 make[1]: *** [install] Error 2
14:27:43 make: *** [install-recursive] Error 1
```

**Pull request closed without merging**
