### PR TITLE
Import of versioned formulas

### PR DESCRIPTION
**Pull request by fxcoudert**
Based on #10859 (because I couldn't push to @MikeMcQuaid's branch), adding the missing alias `kibana@5.2 -> kibana`.

The two other audit issues are:

```
kibana@4.1:
  * Use Language::Node for npm install args
kibana@4.4:
  * Use Language::Node for npm install args
```

which I would be inclined to ignore right now given that those are existing formulas.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Nice work 👏

**Comment by ilovezfs** [comment]
Why are we ignoring
```
kibana@4.1:
  * Use Language::Node for npm install args
kibana@4.4:
  * Use Language::Node for npm install args
```
?

**Comment by fxcoudert** [comment]
@ilovezfs I am happy if people want to fix it, but given that those were working formulas I figured a rewrite would be considered too high a barrier for migration in the short term. Also: because I could not figure out how to fix it exactly :)

**Comment by ilovezfs** [comment]
As far as I know, the main `kibana` formula isn't failing that audit.

**Comment by fxcoudert** [comment]
Yes, and I could not figure out why, as the build process is pretty similar :(

**Comment by ilovezfs** [comment]
It's possible it's a bug in the audit. There's something to be learned here.

**Comment by ilovezfs** [comment]
@fxcoudert yes this is a bug in the audit: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L1179. It has a specific exemption for kibana and its versioned formulae, but the change to the `@` naming scheme hasn't been incorporated into that exemption yet.

**Pull request closed without merging**
