### PR TITLE
crosstool-ng 1.23.0

### PR DESCRIPTION
**Pull request by matteo-pacini**
This commit updates the formula for crosstool-ng 1.23.0

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
The changes in this PR look like they may be intended for Linuxbrew. Is that the case?

**Comment by Zi0P4tch0** [comment]
@ilovezfs I tested it on macOS Sierra only,  and it works - I build two cross-toolchains  so far. 

I just got rid of the `--with-ARG` options as they're deprecated (`configure` will exit if one of those it's encountered).

**Comment by ilovezfs** [comment]
@Zi0P4tch0 ah OK. Can you explain the reasons for
```
-  depends_on "grep" => :optional
-  depends_on "make" => :optional
+  depends_on "grep"
+  depends_on "make"
```
please?

**Comment by Zi0P4tch0** [comment]
@ilovezfs Crosstool relies on GNU `make` and `grep`. Using Apple `make` and `grep` is a recipe for trouble. In fact, in crosstool `configure.ac`, they recommend to use GNU grep on OSX if available (https://github.com/crosstool-ng/crosstool-ng/blob/master/configure.ac#L166-L172). Same goes for GNU make (https://github.com/crosstool-ng/crosstool-ng/blob/master/configure.ac#L291-L297).

**Comment by MikeMcQuaid** [comment]
@Zi0P4tch0 Is it actually broken or just "a recipe for trouble"?

**Comment by Zi0P4tch0** [comment]
@MikeMcQuaid Both. Compiling crosstool-ng with Xcode's toolchain seems to be okay, but it's just a false positive. Makefiles generation will fail sometimes, and even if that succeeds, you'll get `grep` errors when compiling toolchains.

Xcode's `make` - as of Xcode 8.3 - seems to be the GNU one (see first attachment).
screen shot 2017-08-11 at 07 44 54
I will update the formula and mark `make` as optional, but we still need GNU `grep`.

**Comment by MikeMcQuaid** [comment]
> I will update the formula and mark make as optional

Let's not even make it optional, then.

**Comment by JCount** [comment]
@Zi0P4tch0 For the sake of getting this merged I modified your PR to change `make` as a required dependency so that it always builds with it.

**Review by ilovezfs — APPROVED** [review]

**Pull request closed without merging**
