### PR TITLE
openldap: disable systemd and manpage generation on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
Disabling `systemd` prevents opportunistic linking, and `groff` on Linux has a massive dependency tree which includes OpenGL, so we disabled manpage generation in linuxbrew-core.  OpenLDAP is a dependency for `curl`, so many Linux users have to install and it is not worth making them install OpenGL just to do this.

**Comment by danielnachun** [comment]
The test failure here is because of `roswell`, and has nothing to do with `openldap`.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Nobody on Linux is likely using this yet.

**Review by carlocab — APPROVED** [review]
`roswell` is pre-existing.

**Pull request merged**
