### PR TITLE
coq 8.14.1

### PR DESCRIPTION
**Pull request by tchajed**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by tchajed** [comment]
The error is an audit failure "Libraries were compiled with a flat namespace" in all the cmxs files.

I don't really understand how to fix this, or what might have changed. It does seem OCaml passes this flag: https://github.com/ocaml/ocaml/blob/3fa2cfce074d0a83225d7a21678b971bad959a7f/configure.ac#L954.

**Comment by tchajed** [comment]
I confirmed that the same error now appears when auditing coq 8.13.2 and 8.14.0, which is a relief since I wouldn't expect anything to have changed upstream.

**Comment by carlocab** [comment]
> It does seem OCaml passes this flag: https://github.com/ocaml/ocaml/blob/3fa2cfce074d0a83225d7a21678b971bad959a7f/configure.ac#L954.

Yep. It shouldn't, though: https://github.com/ocaml/ocaml/pull/10723

**Review by carlocab — DISMISSED** [review]
The `-flat_namespace` flag comes from OCaml, so should be fixed there. I think we can ignore the audit for now, since it should be fixed when OCaml is updated.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
