### PR TITLE
qpdf 8.4.0

### PR DESCRIPTION
**Pull request by jbarlow83**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
It appears `ocrmypdf` needs a `revision` bump

**Comment by jbarlow83** [comment]
This should work if/after #36755 is accepted

**Comment by fxcoudert** [comment]
Adding the revision bump in #36876, thanks @jbarlow83 for the pull request.

**Comment by javian** [comment]
I don't think there was a reason that this was left open since the version bump was done by fx. Closing.

**Pull request closed without merging**
