### PR TITLE
ffmpeg: fix build on 10.11

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@MikeMcQuaid @zmwangx any thoughts on whether we should or shouldn't do a revision bump for this one?

**Comment by zmwangx** [comment]
I vote for no bump.

**Comment by ilovezfs** [comment]
Needs https://github.com/Homebrew/brew/pull/990.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
Can confirm this works with the current `HEAD` as well. It feels a bit like patching a leaking boat with duct-tape....

**Comment by ilovezfs** [comment]
@JCount Feel like doing the upstream report for me? :innocent:

**Pull request closed without merging**
