### PR TITLE
upx 4.2.2

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@osalbahr need to remove the `deprecate!` lines.

---

relates to https://github.com/upx/upx/issues/612

**Comment by osalbahr** [comment]
How can I fix the commit style? I tried to closely follow https://github.com/Homebrew/homebrew-core/commit/3ee479cc56a8800da63c1663b43875a6f6d58299.

**Comment by chenrui333** [comment]
> How can I fix the commit style? I tried to closely follow [3ee479c](https://github.com/Homebrew/homebrew-core/commit/3ee479cc56a8800da63c1663b43875a6f6d58299).

@osalbahr you can try using `brew style --fix xx` or check out the commit style guide in here, https://docs.brew.sh/Formula-Cookbook#commit

**Comment by osalbahr** [comment]
I made a guess that the "commit style" issue was that I haven't squashed the commits. I can't tell for sure if there were other style issues. Un-deprecating doesn't need its own commit anyways.

---

Regarding the failure,

```
  Error: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/bundle clean
  ==> Testing upx
  ==> /usr/local/Cellar/upx/4.2.2/bin/upx -1 --force-execve ./upx
                         Ultimate Packer for eXecutables
                            Copyright (C) 1996 - 2024
  UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024
  
          File size         Ratio      Format      Name
     --------------------   ------   -----------   -----------
  upx: ./upx: CantPackException: macOS is currently not supported (try --force-macos)
```

it's odd that this line is only hit for macOS 12 x86 and nothing else:
https://github.com/upx/upx/blob/5d649f83ecae9afa68f77d344aec5575b5eac948/src/p_mach.cpp#L2244

However [the developer README](https://github.com/upx/upx/blob/5d649f83ecae9afa68f77d344aec5575b5eac948/README.SRC#L101) does mention macOS.

**Comment by osalbahr** [comment]
- https://github.com/upx/upx/issues/777

**Comment by osalbahr** [comment]
> UPX x86_64 and arm64 **should** work on macOS 12 and earlier, but the packed binaries won't run on macOS 13+.

> That's why we added `--force-macos` so that you can override if you know what you are doing.

_Originally posted by @markus-oberhumer in https://github.com/upx/upx/issues/777#issuecomment-1909529962_

The above makes me lean more towards deprecating the formula for x86 macOS 12. That might depend on how common it is for macOS 12 `upx` users to need the packed binary to be portable to macOS 13+.

**Comment by osalbahr** [comment]
review wanted

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Seems like the crash is still happening

**Comment by osalbahr** [comment]
> Seems like the crash is still happening

When I look at https://github.com/Homebrew/homebrew-core/pull/160367/checks the CI passes with the last edit.

But when I look at https://github.com/Homebrew/homebrew-core/pull/160367/files I see warnings.

What does this mean?

**Comment by SMillerDev** [comment]
If it didn't have bottles on a platform before it'll be a green build if it still doesn't build. It will report the issues as a warning though.

**Pull request closed without merging**
