### PR TITLE
ox 0.2.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
relates to https://github.com/curlpipe/ox/issues/62

**Comment by chenrui333** [comment]
cc @vladimyr

**Comment by vladimyr** [comment]
Roger that, we'll have to wait for the upstream 🤷

**Comment by chenrui333** [comment]
#135686

**Pull request closed without merging**
