### PR TITLE
Secure URLs

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
It seems audit isn't noticing that fdclone's homepage and pcre's homepage could use https. Any idea what's going on?

**Comment by vszakats** [comment]
@ilovezfs: It seems related to the issue I wrote you [here](https://github.com/Homebrew/homebrew-core/pull/18288#issuecomment-330903948) a few days ago. It looks like a recent `brew` update broke the HTTPS checker in `audit`, not just the size checks, but all checks, f.e. the `pcre` homepage is a clear-cut ETag match.

**Comment by ilovezfs** [comment]
ok, that should be bisectable

**Comment by ilovezfs** [comment]
```
ffdda0eb9f4a2e56366e8c665d147d9be637f6f4 is the first bad commit
commit ffdda0eb9f4a2e56366e8c665d147d9be637f6f4
Author: Mike McQuaid <mike@mikemcquaid.com>
Date:   Sat Sep 16 12:41:08 2017 +0100

    Tweaks for older Mac OS X versions.
    
    - `brew update` should try to install `curl` before `git` on older
      versions of Mac OS X where it is needed for accessing modern SSL
      certificates.
    - We don't need an HTTP mirror for `git` because `curl` will already be
      installed before it is downloaded.
    - Don't recommend GCC on Mac OS X versions where it can't be built with
      the default system compiler.
    - Start using the Homebrew `curl` on Mac OS X versions where it is
      needed as soon as it is installed.

:040000 040000 418204619cc9b8272a74a70b0153756b551b399a efe3b4a2cb72c97d2aae9879f6190bc3f2dab584 M	Library
```

**Comment by ilovezfs** [comment]
@vszakats
```
diff --git a/Library/Homebrew/extend/os/mac/development_tools.rb b/Library/Homebrew/extend/os/mac/development_tools.rb
index 66b3bf9..b0d78f4 100644
--- a/Library/Homebrew/extend/os/mac/development_tools.rb
+++ b/Library/Homebrew/extend/os/mac/development_tools.rb
@@ -85,7 +85,7 @@ class DevelopmentTools
     def curl_handles_most_https_certificates?
       # The system Curl is too old for some modern HTTPS certificates on
       # older macOS versions.
-      !ENV["HOMEBREW_SYSTEM_CURL_TOO_OLD"].nil?
+      ENV["HOMEBREW_SYSTEM_CURL_TOO_OLD"].nil?
     end
 
     def subversion_handles_most_https_certificates?
```
fixes it.

**Comment by ilovezfs** [comment]
Even catches kettle
```

**Comment by vszakats** [comment]
Nice find, I can confirm it fixed it, also `nethack` is being found now.

**Comment by ilovezfs** [comment]
Shipped! Thanks again @vszakats!

**Pull request merged**
