### PR TITLE
whalebrew 0.2.2 (new formula)

### LINKED ISSUE #33: Create a Homebrew formula
$ brew install whalebrew

https://twitter.com/teabass/status/824682166361751552

### PR DESCRIPTION
**Pull request by superbrothers**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR adds whalebrew 0.2.2 (new formula).

```
$ brew install --build-from-source whalebrew
Updating Homebrew...
^C==> Cloning https://github.com/whalebrew/whalebrew.git
Updating /Users/ksuda/Library/Caches/Homebrew/whalebrew--git
From https://github.com/whalebrew/whalebrew
 * branch            master     -> FETCH_HEAD
 * [new tag]         0.2.2      -> 0.2.2
==> Checking out tag 0.2.2
Note: checking out '0.2.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at eef2cdc... Release 0.2.2
HEAD is now at eef2cdc Release 0.2.2
==> go build -o /usr/local/Cellar/whalebrew/0.2.2/bin/whalebrew .
🍺  /usr/local/Cellar/whalebrew/0.2.2: 6 files, 15.1MB, built in 48 seconds
$ brew audit --new-formula whalebrew
$ brew audit --strict whalebrew
$ brew test whalebrew
Testing whalebrew
==> /usr/local/Cellar/whalebrew/0.2.2/bin/whalebrew version
```

Closes https://github.com/whalebrew/whalebrew/issues/33

### CODE REVIEW

**Comment by SMillerDev** [comment]
We need a test that exercises the some of the functionality of the app. Version checks or usage checks (foo --version or foo --help) are not sufficient, as explained in the formula cookbook.

In most cases, a good test would involve running a simple test case: run #{bin}/foo input.txt.

- Then you can check that the output is as expected (with assert_equal or assert_match on the output of shell_output)
- You can also check that an output file was created, if that is expected: assert_predicate testpath/"output.txt", :exist?

Some advice for specific cases:

- If the formula is a library, compile and run some simple code that links against it. It could be taken from upstream's documentation / source examples.
- If the formula is for a GUI program, try to find some function that runs as command-line only, like a format conversion, reading or displaying a config file, etc.
- If the software cannot function without credentials, a test could be to try to connect with invalid credentials (or without credentials) and confirm that it fails as expected.
- Same if the software requires a virtual machine, docker instance, etc. to be running.

**Comment by superbrothers** [comment]
I did at 1a7fd08.

**Comment by SMillerDev** [comment]
I just see a stricter version check. Version checks aren't good enough for new homebrew formula though since they rarely ever indicate issues.

**Comment by superbrothers** [comment]
@SMillerDev How do you think change of 7a524b2?

**Comment by superbrothers** [comment]
@SMillerDev Could you please tell me how to use docker container in test environment?

**Comment by superbrothers** [comment]
@SMillerDev I changed test not to use docker engine using https://github.com/Homebrew/homebrew-core/blob/master/Formula/container-diff.rb#L27-L31 as reference.

**Comment by SMillerDev** [comment]
That makes sense and the build succeeded. I think this is good to go.

**Comment by SMillerDev** [comment]
Thanks @superbrothers ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
