### PR TITLE
delete android-sdk and -ndk dependencies due to migration to caskroom

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

>I had tried to put caskroom/android-sdk as dependency, but brew can't resolve it. Is there any official way for formulae to depend on cask?

@MikeMcQuaid maybe we can introduce special case like `:xquartz` os `:osxfuse`?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
This won't work. You need to just remove all these dependencies and, where not removable, formulae.

**Comment by yurikoles** [comment]
@MikeMcQuaid done.

**Review by JCount — DISMISSED** [review]
Both `crystal-ndk` and `fdroidserver` need revision bumps, since the removed dependencies were `:recommended`.

**Comment by yurikoles** [comment]
@JCount done

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @yurikoles! I was unable to preserve commit attribution, unfortunately, because we need only one formula changed per commit.

**Pull request closed without merging**
