### PR TITLE
use secure urls and other minor fixes #8

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by vszakats** [comment]
@apjanke It's `riak`, please note it had `openssl` added as dependency as the bot suggested.

**Comment by apjanke** [comment]
Cool. Going to let this one run through CI since there's a nontrivial change in it.

**Comment by vszakats** [comment]
Let me resubmit the `riak` formula as a separate PR, so this one can finished more easily.

**Comment by apjanke** [comment]
Sounds good.

I've manually reviewed and merged all your other pending PRs. Thanks for doing all of these! Keeping Homebrew healthy depends on contributors like yourself.

**Comment by vszakats** [comment]
Thank you! `riak` landed in #420, removed from this one.

**Comment by apjanke** [comment]
This one looks good then. Merged.

**Pull request closed without merging**
