### PR TITLE
offlineimap: use python-certifi formula

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
Just to make sure, your gpg check is "unverified", is that ok?

**Comment by alex** [comment]
It's signed with https://github.com/sigstore/gitsign

**Comment by iMichka** [comment]
image

It's just that is shows up as unverified in GitHub.

**Comment by alex** [comment]
See https://github.com/sigstore/gitsign/issues/40

**Review by iMichka — APPROVED** [review]
Thanks :) This makes sense now.

**Pull request merged**
