### PR TITLE
libgit2 1.7.1

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
The julia test failure is weird…

**Comment by chenrui333** [comment]
we can give this PR another spin after #138466

**Comment by ZhongRuoyu** [comment]
Previous CI run, for reference: https://github.com/Homebrew/homebrew-core/actions/runs/5699758360

**Review by branchv — APPROVED** [review]
nice work @ZhongRuoyu!

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
