### PR TITLE
uutils-coreutils 0.0.1.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by equal-l2** [comment]
I can reproduce this with or without Homebrew.
I created an issue on the upstream. (https://github.com/uutils/coreutils/issues/1555)

**Comment by alebcay** [comment]
Thanks for investigating and reporting, @equal-l2. 🎉

**Comment by rivy** [comment]
This should now be fixed.

**Comment by carlocab** [comment]
@rivy it still doesn't build, unfortunately: https://github.com/Homebrew/homebrew-core/pull/66608

**Pull request closed without merging**
