### PR TITLE
wxmac 3.1.4

### PR DESCRIPTION
**Pull request by miccal**
This version update for `wxmac` was closed in the past for the reasons discussed in https://github.com/Homebrew/homebrew-core/pull/58413.

However, an issue has been identified with wxMaxima on Big Sur (see https://github.com/wxMaxima-developers/wxmaxima/issues/1441 for more information) and it seems that this issue may be rectified by bumping `wxmac` to the newest version and then bumping `wxmaxima`.

So for the moment, this is just for testing purposes.

Thanks.

### CODE REVIEW

**Comment by carlocab** [comment]
On the Mojave runner, it looks like 6 of the 10 failures are from:
```
==> FAILED
Error: GitHub Bad credentials:HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
  https://github.com/settings/tokens
```
You also have a `sha256` mismatch for `scummvm-tools`.

**Comment by carlocab** [comment]
Only one error on ARM, though not really sure what's going on there:
```
Error: 1 failed step!
brew install --verbose --build-bottle spatialite-gui
```

**Comment by miccal** [comment]
The `11.0` failures for the two `erlang*` Formula are also being seen in https://github.com/Homebrew/homebrew-core/pull/69413 and https://github.com/Homebrew/homebrew-core/pull/69412.

**Comment by miccal** [comment]
`gambit` is being skipped on `11-arm`, and `spatialite-gui` is failing across the board.

**Comment by miccal** [comment]
[`gambit` has not seen an update in a long time](https://github.com/gambitproject/gambit), and does not seem too popular:
```
=> Analytics
install: 12 (30 days), 44 (90 days), 129 (365 days)
install-on-request: 12 (30 days), 44 (90 days), 129 (365 days)
build-error: 0 (30 days)
```

**Comment by miccal** [comment]
I have not yet been successful in fixing the errors for `gambit` or `spatialite-gui`, and I am not sure what else to try?

**Comment by carlocab** [comment]
gambit I don't mind deprecating/deactivating. It seems to be unmaintained. Will need to have a closer look at spatialite-gui.

**Comment by miccal** [comment]
For `spatialite-gui`:
```
==> Analytics
install: 86 (30 days), 252 (90 days), 862 (365 days)
install-on-request: 86 (30 days), 251 (90 days), 830 (365 days)
build-error: 0 (30 days)
```

**Comment by carlocab** [comment]
spatialite-gui is a bit trickier. It hasn't been updated since 2013, but it does seem to be under development, as they have a beta release as of 2020.

**Comment by carlocab** [comment]
Does the `spatialite-gui` beta version work with this version of `wxmac`?

I know we don't like shipping betas, but it may be better than shipping a broken formula. Otherwise, I may not be hugely opposed to just disabling `spatialite-gui`, it seems silly to block a working `wxmac` for it.

**Comment by miccal** [comment]
> Does the `spatialite-gui` beta version work with this version of `wxmac`?
> 
> I know we don't like shipping betas, but it may be better than shipping a broken formula. Otherwise, I may not be hugely opposed to just disabling `spatialite-gui`, it seems silly to block a working `wxmac` for it.

Worth a try, thanks @carlocab.

**Comment by carlocab** [comment]
You may need to add `spatialite-gui` to https://github.com/Homebrew/homebrew-core/blob/master/audit_exceptions/unstable_allowlist.json or else `test-bot` will just refuse to touch it

**Comment by miccal** [comment]
Thanks again @carlocab.

**Comment by zeha** [comment]
I gave this a try, and a rebuilt erlang cannot find its wxe_driver.so.

Indeed, during build time it says:

```
...
checking for debug build of wxWidgets... checking for wx-config... /opt/homebrew/opt/wxmac/bin/wx-config
checking for wxWidgets version >= 2.8.4 (--unicode --debug=yes)... yes (version 3.1.4)
checking for wxWidgets static library... no
checking for standard build of wxWidgets... checking for wx-config... (cached) /opt/homebrew/opt/wxmac/bin/wx-config
checking for wxWidgets version >= 2.8.4 (--unicode --debug=no)... yes (version 3.1.4)
checking for wxWidgets static library... no
checking for wxwidgets 2.8 compatibility ... no
checking for wxwidgets opengl support... yes
...
wx             : wxWidgets was not compiled with --enable-compat28, wx will NOT be useable
Can not link the wx driver, wx will NOT be useable
```

**Comment by carlocab** [comment]
Thanks for looking at this, @zeha. Does adding the flag `--enable-compat28` help?

Though, it's weird that erlang is complaining about this now, given that the stable version is 3.0+. Unless the `--enable-compat28` is default for it but not the dev version?

**Comment by zeha** [comment]
> Thanks for looking at this, @zeha. Does adding the flag `--enable-compat28` help?

Yes, that helps.

**Comment by miccal** [comment]
@carlocab and @zeha this time the `erlang@*`  passed the `10.15` and `10.14` tests, which is a bit odd.

**Comment by carlocab** [comment]
Were we expecting them to fail? Also, should we not use the `--enable-compat28` for `wxmac`?

**Comment by miccal** [comment]
> Were we expecting them to fail? Also, should we not use the `--enable-compat28` for `wxmac`?

Apologies, I misunderstood. I have added it now and changed a few things with `spatialite-gui` after looking at what Debian does.

**Comment by miccal** [comment]
3.1.5 has been released.

**Pull request closed without merging**
