### PR TITLE
ocamlbuild 0.11.0

### PR DESCRIPTION
**Pull request by bfontaine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
sandbox violation
```
mkdir -p /usr/local/Cellar/ocaml/4.04.1/share/man/man1
cp man/ocamlbuild.1 /usr/local/Cellar/ocaml/4.04.1/share/man/man1/ocamlbuild.1
cp: /usr/local/Cellar/ocaml/4.04.1/share/man/man1/ocamlbuild.1: Operation not permitted
make[1]: *** [install-man] Error 1
make: *** [install] Error 2
```

**Comment by bfontaine** [comment]
Thank you @ilovezfs for fixing this!

**Comment by ilovezfs** [comment]
@bfontaine It was @JCount who fixed it :)

**Comment by bfontaine** [comment]
Oh, right, I mixed up your avatars :)

**Pull request closed without merging**
