### PR TITLE
conda-lock: exclude keyring resources

### PR DESCRIPTION
**Pull request by branchv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

cryptography was already removed in #138282 (required through `keyring`)

### CODE REVIEW

**Comment by p-linnane** [comment]
Not 100% sure I understand. Do we need to add `python-cryptography` here?

**Comment by branchvincent** [comment]
It's a bit murky here, but no since it doesn't depend on `cryptography` directly. Its only required on linux (as a dep of `keyring`). Here's the relevant part of dependency tree:

```console
$ uname
Linux
$ pipgrip --tree conda-lock
├── keyring>=21.2.0 (24.2.0)
│   ├── importlib-metadata>=4.11.4 (6.8.0)
│   │   └── zipp>=0.5 (3.16.2)
│   ├── jaraco-classes (3.3.0)
│   │   └── more-itertools (10.1.0)
│   ├── jeepney>=0.4.2 (0.8.0)          <-- linux only           
│   └── secretstorage>=3.2 (3.3.3)      <-- linux only        
│       ├── cryptography>=2.0 (41.0.3) 
│       │   └── cffi>=1.12 (1.15.1)
│       │       └── pycparser (2.21)
│       └── jeepney>=0.6 (0.8.0)
```

So `depends_on "keyring"` is all we need (technically this should be in an `on_linux` block, I'll push a fix for this)

**Comment by p-linnane** [comment]
I guess my point of confusion here is that we are saying `use python-cryptography` without actually adding it as a dependency.

**Comment by branchvincent** [comment]
My bad, yea the commit message doesn’t make sense (was copy/pasted from the other pr’s). Can fix later today

**Comment by chenrui333** [comment]
yeah, we can remove `python-cryptography` mentioning in the commit msg.

**Comment by branchvincent** [comment]
Good now

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
