### PR TITLE
mftrace: add HEAD

### PR DESCRIPTION
**Pull request by dunn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Emailed upstream about the missing stable tarball.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@dunn the tarball is on GitHub too: https://github.com/hanwen/mftrace/archive/release/1.2.18.tar.gz

**Comment by dunn** [comment]
Yeah but the checksum is different

**Comment by ilovezfs** [comment]
It's normal that the checksum is different because it's an automatically generated source archive tarball, not a manually uploaded one.

**Comment by dunn** [comment]
Right, which is why I didn't want to use it, since that'll be an autoconf dependency for stable.

**Comment by ilovezfs** [comment]
same checksum as original:
https://mirrors.ocf.berkeley.edu/debian/pool/main/m/mftrace/mftrace_1.2.18.orig.tar.gz
https://mirrors.kernel.org/debian/pool/main/m/mftrace/mftrace_1.2.18.orig.tar.gz

**Comment by dunn** [comment]
Not sure what you mean?
```
🌲  curl -sL https://github.com/hanwen/mftrace/archive/release/1.2.18.tar.gz | gsha256sum
d994cea643317eb746a0e4dfdcf2352ab943f5acecd620d9d9971bac4d23ea10  -
cat in snow at /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on master[$]
🌲  curl -sL https://mirrors.ocf.berkeley.edu/debian/pool/main/m/mftrace/mftrace_1.2.18.orig.tar.gz | gsha256sum
0d31065f1d35919e311d9170bbfcdacc58736e3f783311411ed1277aa09d3261  -

**Comment by ilovezfs** [comment]
same as the original one https://github.com/dunn/homebrew-core/blob/92102ab0dff77c4dba7daea4f066a9da409b7c18/Formula/mftrace.rb#L5

i.e., we can use mirrors till upstream responds

**Comment by dunn** [comment]
Ha, realized what you mean right after posting my comment.  Thanks!

**Comment by ilovezfs** [comment]
Hehe no problem. It's strange upstream hasn't responded to you yet. At least there a ton of mirrors out there.

**Comment by dunn** [comment]
The developer emailed me this morning; they're not in control of lilypond.org anymore, so they don't know why the tarball was removed, and suggested the GitHub tarball as an alternative.

**Comment by ilovezfs** [comment]
Weird... did you point out they can upload "the real one" to GitHub ... lol

**Comment by dunn** [comment]
I think I just asked if they're going to put future releases there.

**Pull request closed without merging**
