### PR TITLE
partio 1.7.3

### PR DESCRIPTION
**Pull request by DennisOSRM**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/partio/lib/python2.7/site-packages/_partio.so
```

**Comment by fxcoudert** [comment]
Let's try without the python bindings, since they are not currently used in Homebrew.

**Comment by DennisOSRM** [comment]
Created an upstream PR https://github.com/wdas/partio/pull/74

**Comment by DennisOSRM** [comment]
requires a second upstream patch, updating on that.

**Comment by SMillerDev** [comment]
Final patch there yet @DennisOSRM ?

**Comment by fxcoudert** [comment]
We'll wait for the next release. Thanks @DennisOSRM

**Pull request closed without merging**
