### PR TITLE
zsh: make gdbm and pcre optional instead of required

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Requiring these never seems to have been discussed at length
https://github.com/Homebrew/legacy-homebrew/pull/9691.

CC @zmwangx Any thoughts here?

### CODE REVIEW

**Comment by zmwangx** [comment]
I'm fine with it. I guess most people never load a zsh module anyway (other than when frameworks use them behind the scene).

I personally do use zsh/pcre in a few scripts, but I don't see why it should be a requirement.

**Comment by ilovezfs** [comment]
@zmwangx cool. My thinking here is that https://github.com/Homebrew/homebrew-core/pull/22479 in combination with https://github.com/Homebrew/homebrew-core/pull/22490 seem to have conspired to break some people's login shell, so I shipped https://github.com/Homebrew/homebrew-core/pull/22534 to mitigate that situation and opened the current PR to try to prevent it next time.

**Comment by zmwangx** [comment]
Wait, why does not being able to upgrade htop affect zsh? (By the way, htop doesn't seem to crash on my 10.13 system.)

**Comment by ilovezfs** [comment]
I think what was happening is they were running `brew upgrade` and it would upgrade gdbm to libgdbm.5 and then it would get stuck on htop because of the maximum macOS requirement, leaving them with a broken zsh.

**Comment by zmwangx** [comment]
brew upgrade wouldn't stop just because a single package failed to upgrade, no?

**Comment by ilovezfs** [comment]
It stops dead in its tracks on a maximum macOS requirement :(

**Comment by zmwangx** [comment]
Oh that's surprising. Glad I pinned htop.

**Comment by ilovezfs** [comment]
@zmwangx anything you can do to help debug https://github.com/hishamhm/htop/issues/682 would I'm sure be appreciated by the masses :)

**Comment by zmwangx** [comment]
I'm just happy that I can't reproduce :)

**Comment by ilovezfs** [comment]
Yeah. So I set a `depends_on MaximumMacOSRequirement => :lion` on my python3 formula locally and here's how it goes:
```
Josephs-MacBook-Pro:~ joe$ brew upgrade
==> Upgrading 4 outdated packages, with result:
gdbm 1.14.1_1, python 2.7.14_2, python3 3.6.4_2, vim 8.0.1400_4
==> Upgrading gdbm 
==> Downloading https://ftp.gnu.org/gnu/gdbm/gdbm-1.14.1.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/gdbm-1.14.1.tar.gz
==> ./configure --disable-silent-rules --without-readline --prefix=/usr/local/Cellar/gdbm/1.14.1_1
==> make install
🍺  /usr/local/Cellar/gdbm/1.14.1_1: 20 files, 573.7KB, built in 37 seconds
==> Upgrading python 
==> Downloading https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tar.xz
Already downloaded: /Users/joe/Library/Caches/Homebrew/python-2.7.14.tar.xz
==> ./configure --prefix=/usr/local/Cellar/python/2.7.14_2 --enable-ipv6 --datarootdir=/usr/local/Cellar/python/2.7.14_2/share --datadir=/usr/local/Cellar/python/2.7.14_2/share --enable-framework=/usr/loc
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.14_2
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.14_2/share/python
==> Downloading https://files.pythonhosted.org/packages/a4/c8/9a7a47f683d54d83f648d37c3e180317f80dc126a304c45dc6663246233a/setuptools-36.5.0.zip
Already downloaded: /Users/joe/Library/Caches/Homebrew/python--setuptools-36.5.0.zip
==> Downloading https://files.pythonhosted.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/python--pip-9.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fa/b4/f9886517624a4dcb81a1d766f68034344b7565db69f13d52697222daeb72/wheel-0.30.0.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/python--wheel-0.30.0.tar.gz
==> /usr/local/Cellar/python/2.7.14_2/bin/python2 -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/local/Cellar/python/
==> /usr/local/Cellar/python/2.7.14_2/bin/python2 -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/local/Cellar/python/
==> /usr/local/Cellar/python/2.7.14_2/bin/python2 -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/local/Cellar/python/
==> Caveats
This formula installs a python2 executable to /usr/local/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html
==> Summary
🍺  /usr/local/Cellar/python/2.7.14_2: 6,344 files, 88.0MB, built in 3 minutes 29 seconds
python3: This formula either does not compile or function as expected on macOS
versions newer than Lion due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
Josephs-MacBook-Pro:~ joe$
```

**Comment by zmwangx** [comment]
An `UnsatisfiedRequirements` exception is not caught until https://github.com/Homebrew/brew/blob/4438fe117592475d4ddf255c064d2fd95b541a90/Library/Homebrew/brew.rb#L140, where brew exits.

**Comment by ilovezfs** [comment]
Yeah, and `brew upgrade` isn't atomic so here we are.

**Comment by zmwangx** [comment]
GSoC: transactional brew operations.

**Comment by ilovezfs** [comment]
Yeah, that would be nice, especially if it somehow preserved lengthy source builds (maybe unlinked in the Cellar).

**Comment by DomT4** [comment]
Weirdly, I don't seem to have any kind of obvious issue with `htop` on High Sierra. Maybe I'm not leaving it long enough but as of writing this it's been running for 3 solid minutes & neither macOS or iTerm2 have abandoned ship.

**Comment by DomT4** [comment]
Alright, I managed to have `htop` running for 35 minutes with `stress -c 8` with no issues, but the second I chucked `while true; do sh -c "exit 0"; done` in the mix the system died a horrible death. So the latter still reproduces on 10.13.3, at least.

**Comment by ilovezfs** [comment]
@DomT4 I'm considering removing the maximum macOS requirement given the popularity of the software, but I'm having trouble squaring that with our policy of carrying stable software only, and software that can bring the system to a horrible death in its normal use, without even running it with `sudo`, seems well outside that policy. Thoughts?

**Comment by DomT4** [comment]
@ilovezfs It's difficult in this case because it _seems_ like an Apple problem rather than an upstream issue? Punishing `htop` for Apple's issue seems a touch unfair, but yeah, at the same time shipping a formula that is known to be capable of forcing hard resets onto users risking potential data loss/etc depending on what else the user is doing at the time is... not great.

It's a tough call. I lean towards removing the requirement & slapping a great big caveat onto the formula pointing people towards the upstream issue & saying there are known issues on High Sierra people should be aware of, but I'm aware and persistently concerned by how infrequently caveats are noticed or read.

**Comment by ilovezfs** [comment]
@DomT4 yeah it's definitely an Apple issue _by definition_ and the goal is certainly not to punish upstream. If anything, I'd hope it would help upstream by bringing this to the attention of more macOS developers who might be able to dream up a workaround until Apple actually makes it stop.

**Comment by zmwangx** [comment]
```rb
depends_on BypassMaximumMacOSRequirementIfYouAreOkayWithTheRiskOfHorribleSystemDeath
```

**Comment by DomT4** [comment]
> the goal is certainly not to punish upstream

Punish was just the first term that came to mind; wasn't poking at you with it or anything 🙈. Unhelpfully it looks like everything that everyone suggested as a workaround is still partially problematic, otherwise this would be a significantly easier call, sigh.

**Comment by ilovezfs** [comment]
Somewhat of a middle ground if you already have htop installed, this will cause `brew upgrade` to skip `htop` and print the unsatisfied macOS maximum requirement message instead of printing that message and halting: https://github.com/Homebrew/brew/pull/3644

**Comment by DomT4** [comment]
Aye, that's a good step. That it completely killed `brew upgrade` wherever it was in the process was quite the annoyance.

**Pull request closed without merging**
