### PR TITLE
ledger 3.3.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  cd /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/build/doc && /bin/bash -c "groff -mandoc -Thtml /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger.1 > ledger.1.html"
  cd /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/build/doc && makeinfo --force --html --no-split -o ledger3.html /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi
  cd /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/build/doc && makeinfo --force --no-split -o ledger3.info /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:9: Unknown command `codequoteundirected'.
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:9: Unknown command `codequoteundirected'.
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:160: warning: unrecognized encoding name `UTF-8'.
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:160: warning: unrecognized encoding name `UTF-8'.
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:3111: Prev reference to nonexistent node `Metadata payee' (perhaps incorrect sectioning?).
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:3014: Node `Metadata' lacks menu item for `Payee metadata' despite being its Up target.
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:3111: Prev reference to nonexistent node `Metadata payee' (perhaps incorrect sectioning?).
  /tmp/ledger-20230208-78422-1que1nq/ledger-3.3.0/doc/ledger3.texi:3014: Node `Metadata' lacks menu item for `Payee metadata' despite being its Up target.
```

**Comment by chenrui333** [comment]
failed on all 12 and 11 builds

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
For future, macos-12

```
bash-3.2$ makeinfo --version
makeinfo (GNU texinfo) 4.8
```

from texinfo

```
$ /opt/homebrew/Cellar/texinfo/7.0.2/bin/makeinfo --version
texi2any (GNU texinfo) 7.0.2
```

**Comment by watou** [comment]
Is there a chance that a new revision could be built so that the new features added in 3.3.0 will be included?  Please see https://github.com/ledger/ledger/commit/4de50f49a1a20e59b2a97743ac80b85920e94ac5#commitcomment-101053123 .  Thank you!

**Comment by p-linnane** [comment]
Feel free to open a PR making that change and we will review it.

**Comment by watou** [comment]
> Feel free to open a PR making that change and we will review it.

It might miss the mark and sorry for that. https://github.com/Homebrew/homebrew-core/pull/123548

**Pull request closed without merging**
