### PR TITLE
iowow 1.2.8 (new formula)

### PR DESCRIPTION
**Pull request by adamansky**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
Thanks for the PR nonetheless @adamansky! 

https://docs.brew.sh/Acceptable-Formulae

> We frown on authors submitting their own work unless it is very popular.

**Comment by adamansky** [comment]
@commitay  Please provide required project popularity rating, number of github stars? Something else?

**Comment by ilovezfs** [comment]
@adamansky even then, we'd still prefer the pull request come from one of your users who wants it added to Homebrew.

**Comment by MikeMcQuaid** [comment]
@adamansky As lead maintainer of the Homebrew project: I'd rather you insult our project and maintainers on Twitter: https://twitter.com/ejdblab/status/998827382579621888

**Comment by adamansky** [comment]
@ilovezfs @MikeMcQuaid It seems you don't like any kind of critics? I mentioned - you have no clear acceptance policy, it you have one would you like to share it in public?

**Comment by MikeMcQuaid** [comment]
> It seems you don't like any kind of critics?

We welcome constructive criticism; "pretty arrogant bureaucracy" is neither.

> I mentioned - you have no clear acceptance policy, if you have one would you like to share it in public?

You were linked to it: https://docs.brew.sh/Acceptable-Formulae

In addition we have `brew audit --new-formula`. It's pretty clear that in this case you are the sole author (and sole contributor) to the project and that it is not "very popular". Also not from that document: 

> Even if all criteria are met we may not accept the formula. Documentation tends to lag behind current decision-making. Although some rejections may seem arbitrary or strange they are based on years of experience making Homebrew work acceptably for our users.

**Comment by MikeMcQuaid** [comment]
> We welcome constructive criticism; "pretty arrogant bureaucracy" is neither.

Furthermore on that: say whatever you like about Homebrew without @mentioning the project or using our hash tag. If you're doing that you're inviting us to read and comment on it.

> https://github.com/Softmotions/ejdb/ has enough popularity?

That was submitted almost 5 years ago, not by you and has 14 contributors. So: yes, it met our looser requirements then and would likely meet our requirements now. Given it's had <100 installs in the last year, though, it's not "very popular" either.

**Pull request closed without merging**
