### PR TITLE
mariadb 10.6.5

### PR DESCRIPTION
**Pull request by n-thumann**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by n-thumann** [comment]
As far a I can tell, the patch can be removed, because it has been included into the upstream repo (see MariaDB/server@15ac6c5).

**Comment by carlocab** [comment]
It looks like the Intel builds fail during the rocksdb build. This is disabled on ARM, which is why the ARM runners succeeded.

**Comment by n-thumann** [comment]
I was able to reproduce this locally. Any ideas on how to proceed?

**Comment by carlocab** [comment]
I'd start by checking the upstream issue tracker. I think that's on Jira. If there are no reports about this yet, it would help to open one.

**Pull request closed without merging**
