### PR TITLE
git, git-gui 2.27.0

### PR DESCRIPTION
**Pull request by miccal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
This looks like a prerelease. However, `git` 2.27.0 was released today.

**Comment by miccal** [comment]
@alebcay I just used `livecheck` for this:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck git
git : 2.26.2 ==> 2.27.0
```

**Comment by alebcay** [comment]
Your revision on `git` looks correct, my point was regarding `git-gui`, which should also be bumped to `2.27.0`, not `2.70.0`.

**Comment by miccal** [comment]
Oh crap :)

**Comment by miccal** [comment]
Thank you @alebcay, and sorry about the mistake.

**Comment by alebcay** [comment]
No problem! Thanks for contributing. 🥇

**Comment by bayandin** [comment]
Could you please split a commit into two (one per formula: `git 2.27.0` and `git-gui 2.27.0`).

**Comment by miccal** [comment]
@bayandin [I just followed the format of the previous PR?](https://github.com/Homebrew/homebrew-core/pull/53464)

**Comment by bayandin** [comment]
> @bayandin [I just followed the format of the previous PR?](https://github.com/Homebrew/homebrew-core/pull/53464)

And #53464 has 2 commits (one per formula), but this PR has only one (which changes 2 formulae).

**Comment by miccal** [comment]
@bayandin ah, I did not notice that.

**Comment by bayandin** [comment]
> @bayandin ah, I did not notice that.

No problem, you can just rebase it

**Comment by miccal** [comment]
Sorry @bayandin, I did not see you message until I created new PR's:
https://github.com/Homebrew/homebrew-core/pull/55659
https://github.com/Homebrew/homebrew-core/pull/55658

**Comment by bayandin** [comment]
We could do it in a one PR, but just need to have it in 2 commits 😄

**Comment by miccal** [comment]
I will remember that for next time, thank you :)

**Comment by bayandin** [comment]
> Sorry @bayandin, I did not see you message until I created new PR's:
> #55659
> #55658

Both are merged, thanks again @miccal 🎉

**Pull request closed without merging**
