### PR TITLE
iperf3 3.13-mt1

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Slightly odd version. Has this been announced anywhere (aside from the download page)?

**Comment by p-linnane** [comment]
Not seeing any announcements. It's tagged on GitHub as well. Probably best to hold off on merging while we wait for some kind of announcement.

**Comment by carlocab** [comment]
Do they have any for any previous versions? We might be waiting for one that never comes 😅

**Comment by p-linnane** [comment]
Under the Contents header: https://software.es.net/iperf/

**Comment by carlocab** [comment]
Ok, let's give it a few days. If there's nothing we can ask upstream in an issue.

**Comment by p-linnane** [comment]
Pinging @bmah888 who created the tag. We are trying to determine if we should package and distribute this as the latest official release. Would you mind weighing in here?

**Comment by bmah888** [comment]
> Pinging @bmah888 who created the tag. We are trying to determine if we should package and distribute this as the latest official release. Would you mind weighing in here?

Thanks for the ping! No you don’t want this tag as a production version. It’s a beta of new multi threading capabilities that will be appear in some future release. There’s a blurb on this in the discussions area in our GitHub project (sorry not in front of a real computer or I’d give you the link, shouldn’t be hard to find though).

**Comment by p-linnane** [comment]
Thanks for the quick response! I will add a check to our formula to only return the release marked as latest going forward.

**Comment by carlocab** [comment]
Thanks for the clarification, @bmah888. You may want to yank this version from your [downloads page](https://downloads.es.net/pub/iperf/), or else others might mistake it for a production version.

Going forward, should we classify any version that ends in `-xy` (where x and y can be any letters) as testing versions not for use in production?

**Comment by bmah888** [comment]
> Thanks for the clarification, @bmah888. You may want to yank this version from your [downloads page](https://downloads.es.net/pub/iperf/), or else others might mistake it for a production version.
> 
> Going forward, should we classify any version that ends in `-xy` (where x and y can be any letters) as testing versions not for use in production?

Thanks for the feedback! I'm not planning to remove the download because it's supposed to be there for our testers to grab. :-)

But we probably need to work to get the word "beta" into the version numbers for future beta releases. If I had to do this again it'd probably be something like "iperf-3.13-mt-beta1" or something like that. Honestly I didn't anticipate anyone would be trolling through the downloads page. Note that we don't do beta releases of iperf3 very often...this is a special situation where we want to get some early feedback on a somewhat disruptive change (multi-threading) before it hits the mainline. I could anticipate doing another one or two of these before we merge it.

**Comment by carlocab** [comment]
> Honestly I didn't anticipate anyone would be trolling through the downloads page.

The downloads page is how we determine whether there's been a new release. We have automated tooling that parses your downloads page to let us know whether our package is outdated. Should we be checking somewhere else for releases?

**Comment by p-linnane** [comment]
We've implemented a livecheck so that only standard tags will be returned. If upstream is using `-beta`, `-mt1` or something to that effect we won't pull it anymore.

**Pull request closed without merging**
