### PR TITLE
citus 8.3.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
08:21:36 creating configuration files ... ok
08:21:36 running bootstrap script ... 2019-07-29 13:21:35.112 BST [6693] FATAL:  could not create shared memory segment: No space left on device
08:21:36 2019-07-29 13:21:35.112 BST [6693] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
08:21:36 2019-07-29 13:21:35.112 BST [6693] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
08:21:36 	The PostgreSQL documentation contains more information about shared memory configuration.
08:21:36 child process exited with exit code 1
08:21:36 initdb: removing data directory "/private/tmp/citus-test-20190729-6632-18g2xpi/test"
08:21:36 Error: citus: failed

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
ping @lembacon

**Comment by Moisan** [comment]
Thank you @chenrui333 !

**Pull request closed without merging**
