### PR TITLE
bzt 1.15.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
fuzzyset/cfuzzyset.c -o build/temp.macosx-11-arm64-3.9/fuzzyset/cfuzzyset.o
    fuzzyset/cfuzzyset.c:6309:35: error: no member named 'tp_print' in 'struct _typeobject'
      __pyx_type_9cfuzzyset_cFuzzySet.tp_print = 0;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    1 error generated.
    error: command '/opt/homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
    Running setup.py install for fuzzyset: finished with status 'error'
```

**Comment by chenrui333** [comment]
relates to 
- https://github.com/axiak/fuzzyset/issues/28

**Comment by chenrui333** [comment]
```
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patching file .github/workflows/deploy.yml
patching file .bumpversion.cfg
patching file fuzzyset/__init__.py
Hunk #1 FAILED at 4.
1 out of 1 hunk FAILED -- saving rejects to file fuzzyset/__init__.py.rej

```

**Comment by cho-m** [comment]
An alternative option would be to force the (slower) Pure Python implementation via `--pure-python`, which would require separating install step for `fuzzyset` to be able to pass arguments to `python setup.py ...`

Otherwise, would need to modify patch to apply on top of v0.0.19. The GitHub repo was originally using v0.0.18 and committed on top of that. It looks like latest commits are related to forking off into separate [`fuzzyset2`](https://pypi.org/project/fuzzyset2/)

**Comment by Moisan** [comment]
Upstream has a PR to update the requirements to use `fuzzyset2`: https://github.com/Blazemeter/taurus/pull/1539

**Pull request closed without merging**
