### PR TITLE
gdbm: use homebrew texinfo when building

### PR DESCRIPTION
**Pull request by rjpontefract**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
This creates a circular dependency on Linux. We could maybe restrict this to macOS, but I’d really like to avoid adding dependencies to formulae with large dependency trees, which `gdbm` does.

**Comment by rjpontefract** [comment]
I'm building it on Big Sur 11.6 with "brew reinstall -v --build-from-source gdbm".  It fails here:

`
 /usr/bin/install -c -m 644 gdbm_dump.1 gdbm_load.1 gdbmtool.1 '/usr/local/Cellar/gdbm/1.21_1/share/man/man1'
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1918: `Crash Tolerance API' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1849: `Numsync' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1837: `Availability' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1824: `Performance Impact' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1736: `Manual crash recovery' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1630: `Crash recovery' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1609: `Synchronizing the Database' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1575: `Enabling crash tolerance' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1525: `Filesystems supporting crash tolerance' has no Up field (perhaps incorrect sectioning?).
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1837: warning: unreferenced node `Availability'.
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1824: warning: unreferenced node `Performance Impact'.
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1575: warning: unreferenced node `Enabling crash tolerance'.
/private/tmp/gdbm-20211018-81044-19yea8e/gdbm-1.21/doc//gdbm.texi:1525: warning: unreferenced node `Filesystems supporting crash tolerance'.
makeinfo: Removing output file `gdbm.info' due to errors; use --force to preserve.
make[2]: *** [gdbm.info] Error 1
make[1]: *** [install-am] Error 2
`

**Comment by rjpontefract** [comment]
$ which makeinfo
/usr/bin/makeinfo

$ makeinfo --version
makeinfo (GNU texinfo) 4.8

**Comment by carlocab** [comment]
I've attempted builds on both Intel and ARM Big Sur (those are the two failed messages you see from @BrewTestBot). Both builds succeeded but errored out because of the existing bottle.

I'm afraid your issue might be particular to your setup.

Why are you building `gdbm` from source? The bottle is relocatable.

**Comment by carlocab** [comment]
All our build hosts are running `makeinfo (GNU texinfo) 4.8`. What version is shipped with High Sierra?

**Comment by rjpontefract** [comment]
High Sierra has the same version `makeinfo (GNU texinfo) 4.8`

**Comment by rjpontefract** [comment]
I agree, as it doesn't seem to be an issue that affects everyone.  Feel free to reject this PR and I'll just edit it locally on my HS machine if I need to.  I'm happy to use the bottle on big Sur.  Thanks fo looking into this though, it's turned out to be quite interesting.  I might do a clean install of big Sur in a VM to see what happens there.

**Comment by rjpontefract** [comment]
And, given that I'm in New Zealand, it wouldn't surprise me if this works OK in the US and not in NZ due to the TZ difference.  I've seen many cases where comparisons involving dates fail. And it seems this is no different.
The file in the tar file has:

`@set UPDATED 2 September 2021
@set UPDATED-MONTH September 2021
@set EDITION 1.21
@set VERSION 1.21`

and it gets replaced with:

`@set UPDATED 3 September 2021
@set UPDATED-MONTH September 2021
@set EDITION 1.21
@set VERSION 1.21`

Note the 2nd has changed to the 3rd.  

I'l try it again in 3 hours time when NZ and the US are on the same day.  I wonder if it'll just work then.

**Comment by Bo98** [comment]
Does `ENV["TZ"] = "UTC0"` before the make call fix the issue?

**Comment by rjpontefract** [comment]
Indeed it does, which seems to prove the hypothesis.

**Comment by Bo98** [comment]
I wonder if we should just set that by default across all formulae.

**Comment by rjpontefract** [comment]
That might make sense, who would be able to do that?

**Comment by carlocab** [comment]
> I wonder if we should just set that by default across all formulae.

Probably a good idea, I think.

**Pull request closed without merging**
