### PR TITLE
inform6 6.34-6.12.4-1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
license update in #62665

**Comment by chenrui333** [comment]
<details>
<summary>build failure</summary>

```
==> brew install --verbose --build-bottle inform6
==> FAILED
==> Downloading https://inform-fiction.org/examples/Adventureland/Adventureland.inf
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/465bdce63c52b182facbacea575a284a4f3f88f62740933ec2c0c8805ab207be--Adventureland.inf
==> Verifying 465bdce63c52b182facbacea575a284a4f3f88f62740933ec2c0c8805ab207be--Adventureland.inf checksum
==> Downloading https://ifarchive.org/if-archive/infocom/compilers/inform6/source/inform-6.34-6.12.4-1.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/f4551bb61bc8cbcd0ea745f8c568dfb98e6a7579c3848c0d92012bb4ca1e73cb--inform-6.34-6.12.4-1.tar.gz
==> Verifying f4551bb61bc8cbcd0ea745f8c568dfb98e6a7579c3848c0d92012bb4ca1e73cb--inform-6.34-6.12.4-1.tar.gz checksum
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201011-75888-987k5t.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/inform6.rb --build-bottle --verbose
tar xof /Users/brew/Library/Caches/Homebrew/downloads/f4551bb61bc8cbcd0ea745f8c568dfb98e6a7579c3848c0d92012bb4ca1e73cb--inform-6.34-6.12.4-1.tar.gz -C /private/tmp/d20201011-75889-1pmmao2
cp -pR /private/tmp/d20201011-75889-1pmmao2/inform-6.34-6.12.4-1/. /private/tmp/inform6-20201011-75889-1xw771c/inform-6.34-6.12.4-1
chmod -Rf +w /private/tmp/d20201011-75889-1pmmao2
==> make PREFIX=/usr/local/Cellar/inform6/6.34-6.12.4-1 MAN_PREFIX=/usr/local/Cellar/inform6/6.34-6.12.4-1/share/man install
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/arrays.o -c src/arrays.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/asm.o -c src/asm.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/bpatch.o -c src/bpatch.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/chars.o -c src/chars.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/directs.o -c src/directs.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/errors.o -c src/errors.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/expressc.o -c src/expressc.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/expressp.o -c src/expressp.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/files.o -c src/files.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/inform.o -c src/inform.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/lexer.o -c src/lexer.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/linker.o -c src/linker.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/memory.o -c src/memory.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/objects.o -c src/objects.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/states.o -c src/states.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/symbols.o -c src/symbols.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/syntax.o -c src/syntax.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/tables.o -c src/tables.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/text.o -c src/text.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/veneer.o -c src/veneer.c
clang -DUNIX -DDefault_Language=\"english\" -DInclude_Directory=\",/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib,/usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include\" -DTemporary_Directory=\"/tmp\"  -o src/verbs.o -c src/verbs.c
install -d -m 755 /usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib
install -c -m 644 lib/ARTISTIC lib/COPYING lib/ChangeLog lib/README.txt lib/english.h lib/grammar.h lib/infglk.h lib/infix.h lib/linklpa.h lib/parser.h lib/verblib.h lib/version.h lib/voices_and_tenses.txt /usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/lib
install -d -m 755 /usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include
install -c -m 644 include/dmenus.h include/doors.h include/doors2.h include/footnote.h include/helproutines.h include/howtoplay.h include/mistype.h include/moveclass.h include/newbiegrammar.h include/seeno.h include/shuffle.h include/smartcantgo.h include/sound.h include/tmenus.h include/torch.h include/trinitystat.h include/whowhat.h include/yesno.h include/zclock.h /usr/local/Cellar/inform6/6.34-6.12.4-1/share/inform/include
install -d -m 755 /usr/local/Cellar/inform6/6.34-6.12.4-1/share/man/man1
Not adding library symlinks to installation.
/private/tmp/inform6-20201011-75889-1xw771c/inform-6.34-6.12.4-1/inform +lib demos/advent.inf demos/advent.z5
make: /private/tmp/inform6-20201011-75889-1xw771c/inform-6.34-6.12.4-1/inform: No such file or directory
install -c -m 644 inform.1 /usr/local/Cellar/inform6/6.34-6.12.4-1/share/man/man1
make: *** [demos/advent.z5] Error 1
make: *** Waiting for unfinished jobs....
```

</details>

**Comment by chenrui333** [comment]
revisit later

**Comment by DavidGriffith** [comment]
The build failed because it tried to install the `inform` binary before it was finished compiling.  To stop that behavior, change the `def install` block to match the following:

````
  def install
    ENV.deparallelize
    system "make", "PREFIX=#{prefix}", "MAN_PREFIX=#{man}"    
    system "make", "PREFIX=#{prefix}", "MAN_PREFIX=#{man}", "install"
  en
````

**Pull request closed without merging**
