### PR TITLE
cpr 1.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
I believe the patch is no longer needed anymore. CMake flag names have also changed in this release, so we may need to revisit those too.

**Comment by chenrui333** [comment]
```
==> brew audit cpr --online --git --skip-style
==> FAILED
cpr:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      bin/curl-config
  * Header files that shadow system header files were installed to "/opt/homebrew/opt/cpr/include"
    The offending files are:
      /opt/homebrew/opt/cpr/include/curl/mprintf.h
            /opt/homebrew/opt/cpr/include/curl/easy.h
            /opt/homebrew/opt/cpr/include/curl/curl.h
            /opt/homebrew/opt/cpr/include/curl/curlver.h
            /opt/homebrew/opt/cpr/include/curl/system.h
            /opt/homebrew/opt/cpr/include/curl/typecheck-gcc.h
            /opt/homebrew/opt/cpr/include/curl/multi.h
            /opt/homebrew/opt/cpr/include/curl/urlapi.h
            /opt/homebrew/opt/cpr/include/zlib.h
            /opt/homebrew/opt/cpr/include/zconf.h
Error: 2 problems in 1 formula detected
```

**Comment by alebcay** [comment]
I believe the CMake flag `-DUSE_SYSTEM_CURL=ON` should now be `-DCPR_FORCE_USE_SYSTEM_CURL=ON`. That should force use of system curl and fix the shadowing issue.

**Comment by carlocab** [comment]
Is there a way to get rid of the `gtest` dependency? (Does it go away by just not building the tests?) If not, we should probably force it to use system `gtest` too.

**Comment by carlocab** [comment]
Ah, here's the answer: https://github.com/whoshuu/cpr/blob/aac5058a15e9ad5ad393973dc6fe44d7614a7f55/CMakeLists.txt#L190-L194

It needs `gtest` only if you're building the tests.

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
