### PR TITLE
giter8: update disabled message

### PR DESCRIPTION
**Pull request by TonioGela**
Hello, I've customized the disabling message to point at other installation methods directly on the homepage of the project.

### CODE REVIEW

**Comment by SMillerDev** [comment]
That's not part of the reason it was disabled though.

**Comment by TonioGela** [comment]
> That's not part of the reason it was disabled though.
You are totally right, but it will be handy to have it to do not block people from installing the tool. The original reason was kept, but the detail of where to get the tools were added. If there's a way to provide a helpful message without mangling the disabling reason I'll be happy to implement it like so.

**Comment by TonioGela** [comment]
Any news on this PR?

**Comment by TonioGela** [comment]
@carlocab or @SMillerDev can I get any news?

**Comment by SMillerDev** [comment]
Gonna pass on this (sorry for the delayed response), since it's not the disable reason and `brew home giter8` will already take people to the website with instructions.

**Pull request closed without merging**
