### PR TITLE
proj 6.0.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Trying to follow up on #37943

### CODE REVIEW

**Comment by fxcoudert** [comment]
Now `libspatialite` doesn't seem to want to build :sad:

```
17:56:13 ==> ./configure --prefix=/usr/local/Cellar/libspatialite/4.3.0a_7 --with-sysroot=/usr/local --enable-geocallbacks
17:56:13 Last 150 lines from /Users/brew/Jenkins/workspace/core/logs/libspatialite/01.configure:
17:56:13 2019-03-23 17:56:10 +0000
17:56:13 
17:56:13 ./configure
17:56:13 --disable-dependency-tracking
17:56:13 --prefix=/usr/local/Cellar/libspatialite/4.3.0a_7
17:56:13 --with-sysroot=/usr/local
17:56:13 --enable-geocallbacks
```

**Comment by fxcoudert** [comment]
So, proj 6.0.0 was released and dropped previous headers, and none of the projects depending on it actually cared. Almost all broken… 😠

**Comment by rouault** [comment]
@fxcoudert In case you are not aware of it, see https://github.com/OSGeo/proj.4/wiki/proj.h-adoption-status

**Comment by fxcoudert** [comment]
@rouault thanks for the link to the table… It does not track which projects actually manage to define `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` in their build process to work around the new release, though.

**Comment by fxcoudert** [comment]
The testing of #38182 overwrote the bottles from this build. Rebuild one last time, and merge when ready.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Single `mapnik` failure on High Sierra, preexisting.

**Pull request closed without merging**
