### PR TITLE
gtk4 4.6.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
> Error: invalid code lengths set

Any ideas what this could be?

**Comment by cho-m** [comment]
Probably a corrupt tarball. I guess it happened during CI artifact upload given that tests passed with local tarball and error happened on 2 separate merge attempts.

Specifically seems to be failing on `arm64_monterey` bottle. Maybe can just rerun that.

**Comment by SMillerDev** [comment]
Rebuilding all since there is no way to just run 1.

**Comment by cho-m** [comment]
Needs to be rebased as https://github.com/Homebrew/brew/pull/12926 was merged.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
