### PR TITLE
glfw: provide a static library

### PR DESCRIPTION
**Pull request by laytan**
During #164071 it came up to provide a static library for glfw, see https://github.com/Homebrew/homebrew-core/pull/164071#discussion_r1510822455.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
The idea in https://github.com/Homebrew/homebrew-core/pull/164071 was to use to in `odin`, can you please check it works?

**Comment by laytan** [comment]
> The idea in #164071 was to use to in `odin`, can you please check it works? That would remove a resource there.

Sorry, what?

**Comment by laytan** [comment]
> You said:
> 
> > For glfw brew just installs a dynamic library, not a static one, so that won't work in its current state
> 
> I'm not sure why odin would not build with a dynamic library, but that statement was the reason for suggesting adding a static library.

Odin provides an option for both (for users of Odin, it is not required for Odin the compiler, but for the "std" library), but prefers static because it is objectively better.

Even without thinking of the Odin PR, having a static library available is a good thing in general.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @laytan!

**Pull request merged**
