### PR TITLE
pypy 7.3.4 pypy3 7.3.4

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Based on upstream commits.

(Also, don't expect arm64 support anytime soon: https://morepypy.blogspot.com/2020/12/mac-meets-arm64.html)

### CODE REVIEW

**Comment by Bo98** [comment]
Ah, we also need to patch the bootstrap... This is a bit of a chicken and egg problem.

**Comment by bayandin** [comment]
They have promised to make a release "in a few weeks" (2 weeks ago); I hope this is going to happen soon, and we can wait for it.

See https://foss.heptapod.net/pypy/pypy/-/issues/3405

**Comment by Bo98** [comment]
Could do. Seems a bit vague on the timing.

Other options include:

* Using a nightly build for the bootstrap
* Using system Python 2 as a bootstrap (2-3x slower builds though)

**Review by jayvdb — DISMISSED** [review]
wfm

**Comment by aimileus** [comment]
PyPy just released a new release, https://www.pypy.org/posts/2021/04/pypy-v734-release-of-python-27-and-37.html, which I assume includes this patch.

**Comment by bayandin** [comment]
Are there any changes you'd like to add here @Bo98? Otherwise, it's good to merge it

**Comment by jayvdb** [comment]
I guess this PR is unnecessary now after the upstream release.

**Comment by bayandin** [comment]
> I guess this PR is unnecessary now after the upstream release.

I've updated the PR from RC testing to building a release version. So, if homebrew wants to ship a new version of `pypy`/`pypy3` (and we want it), we'll need to merge it 🙂

**Comment by Bo98** [comment]
LGTM

**Review by bayandin — APPROVED** [review]

**Comment by bayandin** [comment]
Thanks @Bo98! Without contributions like yours, it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
