### PR TITLE
formulae: disable

### PR DESCRIPTION
**Pull request by branchv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

Disables deprecated formulae using the script from #113529

### CODE REVIEW

**Comment by chenrui333** [comment]
I think it can be just syntax only?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> I think it can be just syntax only?

yeah, you are right, this would be way to check the deps.

**Review by p-linnane — APPROVED** [review]

**Comment by branchvincent** [comment]
> this would be way to check the deps

yea exactly, I think there might be at least some `conflicts_with` that need to be removed

**Comment by branchvincent** [comment]
nvm about `conflicts_with` since this is just disabling not removing. I don't see any dependents so this should be good

**Comment by p-linnane** [comment]
I don't think it's ever going to complete the `setup_dep_runners` job since everything is disabled. We should rerun this as syntax only to get it merged.

**Pull request merged**
