### PR TITLE
cmake 3.18.0

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
```
==> FAILED
Error: 1 problem in 1 formula detected
cmake:
  * Emacs Lisp files were linked directly to /usr/local/share/emacs/site-lisp
    This may cause conflicts with other packages.
    They should instead be installed into:
      /usr/local/opt/cmake/share/emacs/site-lisp/cmake
    
    The offending files are:
      /usr/local/opt/cmake/share/emacs/site-lisp/cmake-mode.el
```

I don't get it, folder are the same, don't it?

**Comment by Bo98** [comment]
It should be `/usr/local/opt/cmake/share/emacs/site-lisp/cmake/cmake-lisp.el`.

Homebrew already puts it in the right place with `elisp.install` but it looks like CMake 3.18 now installs another copy in the unwanted location.

Maybe try change the `elisp.install` line to `mv share/"emacs/site-lisp/cmake-mode.el", elisp/"cmake-mode.el"`

**Comment by yurikoles** [comment]
I give up, I don't know how to fix it and it uses a lot of time to build, since I can't use ccache with brew.

**Comment by hjmallon** [comment]
I made https://gitlab.kitware.com/cmake/cmake/-/issues/20993 to try to find someone who knows enough about emacs to see what the soln is.

**Comment by Bo98** [comment]
I presume the suggestion I made didn't work then.

**Comment by hjmallon** [comment]
I have not tried your suggestion yet, but I have found the commit in cmake that changes behaviour https://gitlab.kitware.com/cmake/cmake/commit/2642f432ef05d083da66c0b24cd10d655f951186. Is that useful?

**Comment by Bo98** [comment]
Our policy is `${CMAKE_XDGDATA_DIR}/emacs/site-lisp/cmake`. This isn't some Homebrew-specific thing - I know Fedora/Red Hat also install there. Debian doesn't.

**Comment by Bo98** [comment]
I've opened #58306 to continue this.

**Pull request closed without merging**
