### PR TITLE
terraform 0.7.5

### PR DESCRIPTION
**Pull request by cblecker**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cblecker** [comment]
Build failed on Sierra, but that appears to be unrelated to the formula change.

**Comment by ilovezfs** [comment]
nonetheless, let's get it fixed before shipping this.

**Comment by awallace-cray** [comment]
The error in the Sierra build here points to "chapel.rb" - that's mine - chapel's Sierra build just failed w the same errors a little while ago. https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8827/

**Comment by ilovezfs** [comment]
yeah I just put a hold on all CI on Jenkins until this is sorted.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by Ninir** [comment]
@ilovezfs Any news of @BrewTestBot ? ahah 😄

**Comment by ilovezfs** [comment]
@Ninir as you can see it passed :)

**Comment by Ninir** [comment]
@ilovezfs Woopsy... ahah, sorry!
Can't wait to have it, thank you guys :)

**Comment by ilovezfs** [comment]
@Ninir :rocket:

**Comment by ilovezfs** [comment]
@cblecker Thanks for updating this formula and for your patience with test-bot!

**Comment by Ninir** [comment]
You guys rock, awesome! 👍

**Pull request closed without merging**
