### PR TITLE
ffmpeg 3.3

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
`clock_crap` is still broken?

**Comment by zmwangx** [comment]
No, fixed in https://github.com/FFmpeg/FFmpeg/commit/0e8b68a2c4031e25082603ad88711be12210d41f.

**Comment by ilovezfs** [comment]
hmm still seems to be broken to me

Without our fix:
```
iMac-TMP:~ joe$ nm /usr/local/Cellar/ffmpeg/3.3/lib/*.dylib|grep clock
                 U _clock_gettime
                 U _clock_gettime
                 U _clock_gettime
```


With our fix:
```
iMac-TMP:homebrew-core joe$ nm /usr/local/Cellar/ffmpeg/3.3/lib/*.dylib|grep clock
iMac-TMP:homebrew-core joe$
```

**Comment by ilovezfs** [comment]
But maybe it's OK the symbol is in there and they handle it properly at runtime now, wonder of wonders?

**Comment by zmwangx** [comment]
I think that's the case.

**Comment by ilovezfs** [comment]
:clap: for the "proper" fix

**Comment by zmwangx** [comment]
The more `ifdef __APPLE__` the merrier. /s

**Comment by ilovezfs** [comment]
```
#if HAVE_CLOCK_GETTIME && defined(CLOCK_MONOTONIC)
#ifdef __APPLE__
    if (clock_gettime)
```
is pretty awful :)

**Comment by zmwangx** [comment]
You need to install a cpp to your mind. Then you won't see preprocessor macros any longer.

**Comment by ilovezfs** [comment]
I hear they're expensive – especially the Pro model.

**Comment by zmwangx** [comment]
The Pro model isn't coming this year.

**Comment by ilovezfs** [comment]
:disappointed_relieved:

**Comment by zmwangx** [comment]
The mps_youtube failure doesn't look remotely related, and it wasn't present in the first build, where only mpv failed since I forgot to bump it. Wtf.

**Comment by ilovezfs** [comment]
I suspect the test is no good.

**Comment by zmwangx** [comment]
Looks like the vendored youtube-dl can't parse the YouTube js payload. Guess it's time to update the resource.

**Comment by ilovezfs** [comment]
want to do that in a separate PR?

**Comment by zmwangx** [comment]
Probably. It's not related to FFmpeg 3.3 at all.

**Comment by ilovezfs** [comment]
:ship: :boat: :motor_boat: :rocket: :car:

**Comment by zmwangx** [comment]
#12390.

**Pull request closed without merging**
