### PR TITLE
kubernetes-helm 0.8.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like `docker` is mandatory now:

```
Missing `docker` client which is required for development and testing
make: *** [check-docker] Error 2
```

**Comment by ilovezfs** [comment]
@DomT4 Does this mean that we have to boneyard it? It seems to require *running* docker in order to build.

**Comment by DomT4** [comment]
Yeah. If a simple `depends_on "docker"` doesn't do the trick, it'll either need to go live in the boneyard or if there's binaries available ([apparently some are](https://bintray.com/deis/helm/helmc/0.8.1%2Be4b3983#files)) it'll need to be shipped out to the Cask with an explanation.

**Comment by ilovezfs** [comment]
> If a simple depends_on "docker" doesn't do the trick

Indeed that does not help at all since upstream actually requires docker to do the build. So I'll close this. In addition, the current version in core not only has a broken checksum (due to a change in the repository name), but also has dependencies that can no longer be resolved with the URLs specified in the tarball, so the formula is currently a zombie.

**Comment by DomT4** [comment]
Sounds like it should be boneyarded, at least in the short term.

**Comment by ilovezfs** [comment]
@DomT4 Voilà: https://github.com/Homebrew/homebrew-boneyard/pull/132

**Comment by DomT4** [comment]
👍 🙇

**Pull request closed without merging**
