### PR TITLE
emscripten 1.38.6

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
`url "https://github.com/kripken/emscripten.git", :branch => "master"`

What's the deal with this sort of thing in `head`? Isn't `master` _always_ the assumed default?

**Comment by ilovezfs** [comment]
I think it's needed when the default branch isn't master.

**Comment by DomT4** [comment]
```
~> brew fetch emscripten -vf --HEAD
==> Cloning https://github.com/kripken/emscripten.git
git clone --depth 1 --branch master https://github.com/kripken/emscripten.git /usr/local/var/homebrewcache/emscripten--git
Cloning into '/usr/local/var/homebrewcache/emscripten--git'...
remote: Counting objects: 7886, done.
remote: Compressing objects: 100% (6470/6470), done.
remote: Total 7886 (delta 1069), reused 6147 (delta 958), pack-reused 0
Receiving objects: 100% (7886/7886), 32.13 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (1069/1069), done.
git config homebrew.cacheversion 0
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up to date with 'origin/master'.
Resource: fastcomp
==> Cloning https://github.com/kripken/emscripten-fastcomp.git
git clone --depth 1 --branch master https://github.com/kripken/emscripten-fastcomp.git /usr/local/var/homebrewcache/emscripten--fastcomp--git
Cloning into '/usr/local/var/homebrewcache/emscripten--fastcomp--git'...
remote: Counting objects: 26978, done.
remote: Compressing objects: 100% (24942/24942), done.
remote: Total 26978 (delta 3295), reused 9546 (delta 1743), pack-reused 0
Receiving objects: 100% (26978/26978), 37.78 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (3295/3295), done.
git config homebrew.cacheversion 0
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up to date with 'origin/master'.
Resource: fastcomp-clang
==> Cloning https://github.com/kripken/emscripten-fastcomp-clang.git
git clone --depth 1 --branch master https://github.com/kripken/emscripten-fastcomp-clang.git /usr/local/var/homebrewcache/emscripten--fastcomp-clang--git
Cloning into '/usr/local/var/homebrewcache/emscripten--fastcomp-clang--git'...
remote: Counting objects: 14043, done.
remote: Compressing objects: 100% (12200/12200), done.
remote: Total 14043 (delta 1134), reused 6855 (delta 751), pack-reused 0
Receiving objects: 100% (14043/14043), 17.08 MiB | 1.60 MiB/s, done.
Resolving deltas: 100% (1134/1134), done.
git config homebrew.cacheversion 0
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by DomT4** [comment]
I guess it's harmless, but seems to be behaving fine with the explicit `master` removed.

**Comment by ilovezfs** [comment]
I guess one question is why `incoming` isn't what we're using

**Comment by DomT4** [comment]
Aye, that would seem to be logical. `master` is actually significantly behind even stable at this point.

**Pull request closed without merging**
