### PR TITLE
numpy 1.23.5

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by clason** [comment]
`biosig` test file seems to have vanished into thin air (user removed/retired: https://pub.ist.ac.at/~schloegl/)

**Comment by clason** [comment]
@chenrui333 I removed the two tests from `biosig` that used a no longer existing test file (see above). I hope this is acceptable.

**Comment by chenrui333** [comment]
> @chenrui333 I removed the two tests from `biosig` that used a no longer existing test file (see above). I hope this is acceptable.

I actually did the same thing recently, #116761 

I will rebase your PR and we should be good to go

**Comment by chenrui333** [comment]
Some networking flakiness for 11 builds

```
brew install --only-dependencies caffe
brew install --only-dependencies spatialite-gui
```

Rerun the failed one job

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
