### PR TITLE
autorest 3.1.4

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~ [test resource]

### CODE REVIEW

**Comment by Rylan12** [comment]
Interesting, the `homebrew-*` resource handling was supposed to be removed as those were used only to separate the `virtualenv` resources from the formula-defined resources. I forgot it was used in `bump-formula-pr`, too. I'm not opposed to having some way to ignore resources for this message, so I guess this is fine to keep unless you think there's a better way to handle them.

**Comment by Rylan12** [comment]
Actually, thinking about this more, I'm not sure we should be ignoring them. If we're using a test resource, we probably want to use the latest version to ensure that the latest version works. If the file we download to test with is updated, it's likely because the formula changed to so we'd want to catch that, right?

**Comment by carlocab** [comment]
This one's just a YAML file, though. I don't think we need newer versions of a YAML file, do we? This one also hasn't changed in a while (~3 years).

**Comment by Rylan12** [comment]
Yeah, I agree that this particular case shouldn't need to be updated. I'm just asking in general whether we should have the ability to disable the message.

**Comment by carlocab** [comment]
I guess it might be useful to have a way to ignore test resources when doing `bump-formula-pr`. TBH I don't think I remember any recent PRs where there was a need to update a test-only resource.

**Comment by Rylan12** [comment]
Yeah, I guess ignoring test resources is probably fine. If they need to be updated they'll probably break CI anyway. Right not we don't have a way to separate which resources are used for tests vs build, though, so this might be the way to do it for now...

**Review by Rylan12 — APPROVED** [review]

**Pull request closed without merging**
