### PR TITLE
mongocli 1.29.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not the latest release: https://github.com/mongodb/mongodb-atlas-cli/releases

**Comment by ZhongRuoyu** [comment]
Given that the repo holds two separate CLI tools (the other one is [`mongodb-atlas-cli`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb-atlas-cli.rb)), a "latest" release would be somewhat ambiguous. I'm inclined to consider this as the latest because upstream has published release notes here: https://www.mongodb.com/docs/mongocli/stable/release-notes/

**Comment by p-linnane** [comment]
I just meant that it's not even listed on the release page. 1.28.1 is the latest version of this specific tool on the release page.

**Comment by chenrui333** [comment]
https://github.com/mongodb/mongodb-atlas-cli/issues/1772

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
