### PR TITLE
apt-dater 1.0.3

### PR DESCRIPTION
**Pull request by geoffmacintosh**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
There's already a pull request  at #5763, but it links the old website.

### CODE REVIEW

**Comment by geoffmacintosh** [comment]
This is actually a change in version as well as a homepage update. I think it should be left with the current commit message, perhaps?

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by nijikon** [comment]
Yes, we will leave it as is, it's ok.

**Comment by mbi** [comment]
@nijikon @geoffmacintosh my apologies if this should rather be discussed in a new issue… but the new version has a new, backwards incompatible configuration syntax, and it's really not obvious how one should migrate to the new configuration. The [current product README](https://github.com/DE-IBH/apt-dater) actually only mentions the *old* format. 

I kind of agree with the comments in #5763 that suggested we stick in pre-1.0 land (their [changelog](https://github.com/DE-IBH/apt-dater/blob/master/ChangeLog) marks version 1.0.3 as unstable and low-urgency)

Would it be possible to have some kind of upgrade documentation and / or have the previous version in `homebrew/versions`?

**Comment by MikeLund** [comment]
@geoffmacintosh You linked my old pull request, but did you read what I said in it? Newer versions of apt-dater are super buggy, and the developer hasn't came back to it. 

@nijikon I would suggest you roll-back this change. There is no reason to give users this newer version, it is hopelessly buggy and seemingly will be that way for the foreseeable future.

(Also funny how @mbi noticed this as well, guess we both decided to `brew upgrade` today and use apt-dater... :))

**Comment by MikeMcQuaid** [comment]
If we're not going to get a new stable version for 5 years that implies this software isn't really maintained at this point. I'm pretty sure `unstable` points to the Debian repo rather than a comment on the software, no?

**Comment by geoffmacintosh** [comment]
@MikeLund My apologies. I built and tested the version and didn't find any issues, and wrongly assumed that it was improved, as apparently I am not very good at telling the difference between two numbers (or in this case, a remarkable similarity). I hope my mistake hasn't caused you too much hassle.

**Comment by MikeMcQuaid** [comment]
> @geoffmacintosh You linked my old pull request, but did you read what I said in it? Newer versions of apt-dater are super buggy, and the developer hasn't came back to it. Did you test apt-dater after updating the formula, or did you assume it worked because it built? :\

@MikeLund The reason formulae have tests is to we can assume they work when they build and pass tests. If you don't want this to happen in future instead of berating individual contributors like @geoffmacintosh who are, like you, trying to help run this project then please add a more substantial test to this formula which reproduces one of these bugs.

**Comment by MikeLund** [comment]
Yeah I am sorry myself @geoffmacintosh, it came off bad. I had a tight day and misdirected my frusturation when this change broke for me on my job. In the end it was my fault for doing brew upgrade without seeing what was changed first, not your fault for just trying to help out.

Hope I didnt make you feel bad, appologies again.

**Comment by MikeMcQuaid** [comment]
@MikeLund @geoffmacintosh Thanks to you both for being humble and apologetic and demonstrating how to resolve these things amicably in the open-source. ❤️ to you both.

**Pull request closed without merging**
