### PR TITLE
rsync: update patch

### PR DESCRIPTION
**Pull request by fxcoudert**
Patches were not updated. Maybe related to https://github.com/Homebrew/homebrew-core/issues/129732 ?

### CODE REVIEW

**Comment by fxcoudert** [comment]
The patch is totally unrelated to configure files, why would it try to run `autoconf`? That looks like a Makefile issue

**Comment by SMillerDev** [comment]
Make seems to run it regardless and now it fails since nothing changed? How did this ever work before?
```
 ==> make
  autoconf -o configure.sh
  autoconf -o configure.sh
  autoheader && touch config.h.in
  autoheader && touch config.h.in
  configure.sh is unchanged.
  configure.sh is unchanged.
  rm: cannot remove 'configure.sh.old': No such file or directory
  make: *** [Makefile:204: config.h.in] Error 1
  make: *** Waiting for unfinished jobs....
  config.h.in is unchanged.
```

**Comment by fxcoudert** [comment]
```
patching file aclocal.m4
```

I was wrong, the patch does touch autoconf files. Also, your change is building for me locally, so maybe it's a Linux-only issue?

**Comment by fxcoudert** [comment]
Also, the logs showed that `--disable-simd` is now ignored by `configure`

**Comment by fxcoudert** [comment]
In the new merging workflow, we can’t run `brew pr-publish` on a PR not approved. That’s a new limitation. What is the recommended procedure for merging one’s own PR, where no other maintainer has approved it? (given one can’t self-approve)

**Comment by Bo98** [comment]
> ```
> patching file aclocal.m4
> ```
> 
> I was wrong, the patch does touch autoconf files. Also, your change is building for me locally, so maybe it's a Linux-only issue?

Worth noting the aclocal.m4 patch is due to an error made in the 3.2.7 release, which is why it was not needed for 3.2.6 and we can remove the deps again in 3.3.0.

**Comment by fxcoudert** [comment]
Well, in any case, things now work fine.

**Review by carlocab — APPROVED** [review]
> In the new merging workflow, we can’t run `brew pr-publish` on a PR not approved. That’s a new limitation. What is the recommended procedure for merging one’s own PR, where no other maintainer has approved it? (given one can’t self-approve)

Request a review from @Homebrew/core, I guess.

I placed the approval check there initially because it seemed like we wanted to avoid PRs being merged without review (based on initial experiments with requiring approvals for the latest reviewable push).

The requirement can be removed if we don't think it's needed though.

**Pull request merged**
