### PR TITLE
mariadb@10.3 10.3.17

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
17:23:20 /usr/bin/ar qc libpcre.a  CMakeFiles/pcre.dir/pcre_byte_order.c.o CMakeFiles/pcre.dir/pcre_chartables.c.o CMakeFiles/pcre.dir/pcre_compile.c.o CMakeFiles/pcre.dir/pcre_config.c.o CMakeFiles/pcre.dir/pcre_dfa_exec.c.o CMakeFiles/pcre.dir/pcre_exec.c.o CMakeFiles/pcre.dir/pcre_fullinfo.c.o CMakeFiles/pcre.dir/pcre_get.c.o CMakeFiles/pcre.dir/pcre_globals.c.o CMakeFiles/pcre.dir/pcre_jit_compile.c.o CMakeFiles/pcre.dir/pcre_maketables.c.o CMakeFiles/pcre.dir/pcre_newline.c.o CMakeFiles/pcre.dir/pcre_ord2utf8.c.o CMakeFiles/pcre.dir/pcre_refcount.c.o CMakeFiles/pcre.dir/pcre_string_utils.c.o CMakeFiles/pcre.dir/pcre_study.c.o CMakeFiles/pcre.dir/pcre_tables.c.o CMakeFiles/pcre.dir/pcre_ucd.c.o CMakeFiles/pcre.dir/pcre_valid_utf8.c.o CMakeFiles/pcre.dir/pcre_version.c.o CMakeFiles/pcre.dir/pcre_xclass.c.o
17:23:20 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpcre.a(pcre_string_utils.c.o) has no symbols
17:23:20 /usr/bin/ranlib libpcre.a
17:23:20 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpcre.a(pcre_string_utils.c.o) has no symbols
17:23:20 [  6%] Built target pcre
17:23:20 make: *** [all] Error 2
17:23:20 
17:23:20 ==> Formula

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
