### PR TITLE
bumpversion 0.5.11

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is there a 'blessing' from the old project to continue as a fork? We don't just change upstreams without a very good reason and confirmation from the original upstream.

**Comment by chenrui333** [comment]
@SMillerDev yeah, he did even put a commit saying the future work would go to the fork (even though there might be potential work needed to merge the fork back to main).

https://github.com/peritus/bumpversion/commit/cc3c8cfd77380ef50eeac740efe627509a248101

**Comment by chenrui333** [comment]
The fork is completely drop-in replacement. 

And I think the fork would be promoted to its own repo shortly.

**Comment by SMillerDev** [comment]
It just tells you to contribute to a fork with "c4urself" being an example. None of this actually mentions that the fork is now the official project.

**Comment by SMillerDev** [comment]
@Homebrew/core any opinions?

**Comment by chenrui333** [comment]
> 🎬If you want to start **using bumpversion**, you're best advised to **install one of the maintained forks**, e.g. ➡ `@c4urself's bump2version <https://github.com/c4urself/bump2version/#installation>`_.

I think this is pretty clear that is the actively maintained fork, but yeah, it might take some time to become official repo.

**Comment by SMillerDev** [comment]
> one of the maintained forks, e.g.

So there are multiple and this is an example.

**Comment by chenrui333** [comment]
Yeah, I think so. Considering the last activity for the main repo was four or five years back, this change might be beneficial.

I will also create an upstream issue to get them sorted out and turn this back to track.

**Comment by MikeMcQuaid** [comment]
Given it's "blessed" by the original project maintainer: 👍 to this change.

**Comment by Bo98** [comment]
To emphasise the GitHub issue mentioned in the formula: https://github.com/c4urself/bump2version/issues/86

It seems like the plan is for either that specified fork to eventually merge back into the main one or for the main repo to be transferred to the individual(s) managing the fork. It's probably as "official" as it's going to get without being official.

**Comment by sjackman** [comment]
@c4urself Could you ask @peritus for commit rights to https://github.com/peritus/bumpversion?

**Comment by chenrui333** [comment]
There is ongoing discussion for this, I think instead of merging back, it would be nice to promote the fork to become as official repo.

**Comment by chenrui333** [comment]
what is the take now? merge or close?

**Comment by sjackman** [comment]
Ideally @peritus would either grant commit rights to @c4urself, or alternatively transfer the GitHub repo to @c4urself.

@MikeMcQuaid approved this PR in https://github.com/Homebrew/homebrew-core/pull/47379#issuecomment-560445948. That's good enough for me.

**Comment by peritus** [comment]
I did give @c4urself access to both my repository and the PyPI project a few weeks ago:  https://github.com/c4urself/bump2version/issues/86#issuecomment-531287602

**Comment by c4urself** [comment]
Yep, it's on my radar -- going to spend some time on that this week hopefully.

**Comment by chenrui333** [comment]
Thanks @peritus, @c4urself!! I will give this PR a go and iterate on top of it.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
