### PR TITLE
ldpl 5.1.0

### PR DESCRIPTION
**Pull request by Lartu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by daeho-ro** [comment]
Thank you, @Lartu for the PR.
There is a patch process and I think it does not required or updated. Can you check?

**Comment by Lartu** [comment]
Hi there @daeho-ro! I'm afraid I didn't understand what you mean with your message 😥 I'm trying to update the LDPL cask from 4.4.0 to 5.1.0, but I have yet to fix the Linux CI that's failing.

**Comment by chenrui333** [comment]
yeah, like @daeho-ro said, there is a linux patch needs to be handled, I just removed it.

**Comment by chenrui333** [comment]
@Lartu looks like it failed with 

```
  ==> /opt/homebrew/Cellar/ldpl/5.1.0/bin/ldpl hello.ldpl -o=hello
  * Loading hello.ldpl
  * Compiling hello.ldpl
  * Building hello
  ldpl-temp.cpp:1:10: fatal error: '/usr/local/lib/ldpl/ldpl_lib.cpp' file not found
      1 | #include "/usr/local/lib/ldpl/ldpl_lib.cpp"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```

**Comment by Lartu** [comment]
Hi @chenrui333, thank you for your help! I'll check what I've done wrong and come back with a fix.

**Comment by chenrui333** [comment]
np, thanks @Lartu!

**Pull request closed without merging**
