### PR TITLE
nvm 0.31.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by apjanke** [comment]
Test failure.

```
Error Message

failed: brew test nvm --verbose

Stacktrace

        Testing nvm
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160720-74868-uwu937.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb --verbose
==> NODE_VERSION=homebrewtest /usr/local/Cellar/nvm/0.31.3/nvm-exec 2>&1
Error: nvm: failed
Expected /N\/A:\ version\ "homebrewtest"\ is\ not\ yet\ installed/ to match "N/A: version \"N/A\" is not yet installed.\n\nYou need to run \"nvm install N/A\" to install it before using it.\n".
```

Looks like the error message behavior has changed with this version?

**Comment by ilovezfs** [comment]
@DomT4 that test is truly awful but thank you for burying it in the vast sea of other awful tests while leaving me feeling slightly less guilty.

**Comment by DomT4** [comment]
Yeah, the test is basically checking `nvm` is broken really 😄. Super annoying `assert_no_match` doesn't take a string as well.

**Comment by ilovezfs** [comment]
Martin was suggesting refute, which we should be able to switch over to once the brew requirement is raised to >= ruby 2

**Comment by DomT4** [comment]
Ruby 2.x is going to make a lot of this sort of stuff simpler. Forever envy the Cask who have been able to presume Ruby 2.x from the start (IIRC).

**Comment by ilovezfs** [comment]
On 10.8 I've been setting HOMEBREW_RUBY_PATH to /usr/local/opt/ruby/bin/ruby to use brew's ruby for a while now without any problems. The only gotcha is that it only works to do that if you also set HOMEBREW_DEVELOPER. If we dropped the must-set-developer requirement, I think we could switch over to requiring 2.x basically immediately.

**Comment by MikeMcQuaid** [comment]
@ilovezfs We'll be shipping the vendored Ruby 2 in the next week.

**Comment by ilovezfs** [comment]
Not soon enough!

**Pull request closed without merging**
