### PR TITLE
balena-cli 12.50.0

### PR DESCRIPTION
**Pull request by tmigone**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tmigone** [comment]
With regards to the test for nodejs v10.15 that's failing, `balena-cli v12.50.0` requires nodejs > v10.20

See https://github.com/balena-io/balena-cli/blob/v12.50.0/package.json#L91

**Comment by carlocab** [comment]
> With regards to the test for nodejs v10.15 that's failing, `balena-cli v12.50.0` requires nodejs > v10.20

So why doesn't it work with v17?

**Comment by pdcastro** [comment]
> See https://github.com/balena-io/balena-cli/blob/v12.50.0/package.json#L91

The link above points to a line that reads:
```
"node": ">=10.20.0 <13.0.0",
```

I.e., Node.js greater than or equal to 10.20.0 AND less than 13.0.0.
Related issue: balena-io/balena-cli/issues/2079

Having said that, some commands with some input will work with Node.js v13 or v14, and possibly later versions. It's corner cases that are known to fail. When the balena CLI is executed with Node.js v14 or later, it produces this warning:

```
$ balena version
---------------------------------------------------------------------------------
[Warn] Node.js version "14.18.1" does not satisfy requirement ">=10.20.0 <13.0.0"
[Warn] This may cause unexpected behavior.
---------------------------------------------------------------------------------
12.51.1
```

**Comment by SMillerDev** [comment]
There is about half a year of support left for nodeJS 12 though. Is upstream going to fix this?

**Comment by pdcastro** [comment]
> There is about half a year of support left for nodeJS 12 though. Is upstream going to fix this?

Oh yes, upstream would very much like to fix this, and help is wanted! :-)
The remaining known issue is balena-io/balena-cli/issues/2165

A few people tried fixing it, myself included, but so far without success. When running `balena push <ip-address>` to a local device running a development image of balenaOS, it always succeeds when using Node.js v10 or v12, but fails when using Node.js v14 or v16 (I can't really say about other versions), depending on the project contents. The failure manifests as the Node.js process exiting unexpectedly but without any error, as if the Node.js event loop had found that there was nothing else to do or wait for. We have not yet determined for sure what the root cause is. The furthest we got to, as far as I am aware, pointed to some `on('end', ...` event not being produced by the `dockerode` dependency, but it needs confirmation. Updating `dockerode` (in the relevant code path) did not help, or at least that was the case a few months ago. (cc: @srlowe)

If you would like to help us fix that issue and discuss further details about that problem, I suggest quoting this comment in issue balena-io/balena-cli/issues/2165, so that all the facts are collected in the same place, for anyone else to find.

**Comment by SMillerDev** [comment]
It should work with this change then

**Comment by carlocab** [comment]
```
make: *** No rule to make target `/usr/local/Cellar/balena-cli/12.50.0/libexec/lib/node_modules/balena-cli/node_modules/@ronomon/direct-io/build/Release/binding.node', needed by `/usr/local/Cellar/balena-cli/12.50.0/libexec/lib/node_modules/balena-cli/node_modules/@ronomon/direct-io/binding.node'.  Stop.
```

**Pull request closed without merging**
