### PR TITLE
guile 3.0.8

### PR DESCRIPTION
**Pull request by joh-klein**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
The patch needs to be removed.

**Comment by carlocab** [comment]
This needs the `CI-long-timeout` label, but that's currently in use. (We only want two long running jobs at a time to avoid clogging up the CI queue.) We can add the label when one of the other jobs finishes.

**Review by SMillerDev — APPROVED** [review]
Thanks @joh-klein  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Review by carlocab — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

**Comment by joh-klein** [comment]
> Thanks @joh-klein ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

Wow – thanks for these really kind words! They made my day!

**Pull request closed without merging**
