### PR TITLE
protobuf 3.9.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by scpeters** [comment]
protobuf-swift failed due to a header file that was removed in protobuf 3.8. I submitted a patch upstream in https://github.com/alexeyxo/protobuf-swift/pull/256

**Comment by scpeters** [comment]
I rebased and added a patch for protobuf-swift

**Comment by scpeters** [comment]
I suppose an alternative would be for `protobuf-swift` to depend on `protobuf@3.7`

**Comment by scpeters** [comment]
it looks like the protobuf-swift patch doesn't even work

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/43419/version=mojave/testReport/junit/brew-test-bot/mojave/install___build_bottle_protobuf_swift/
* https://gist.github.com/scpeters/8a7c86683a2a772acd9338bc49083f2d

**Comment by scpeters** [comment]
removed patch and changed protobuf-swift to depend on protobuf@3.7

**Comment by scpeters** [comment]
The shogun tarball is not accessible from their website, so I've created an issue asking if we should be getting it directly from GitHub instead: https://github.com/shogun-toolbox/shogun/issues/4696

**Comment by PureWhiteWu** [comment]
The latest version is v3.9.0 now.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
The latest version is v3.9.1 now.

**Comment by scpeters** [comment]
shogun is still failing because of unavailable tarballs. I've asked about the problems with their website but there has been very slow progress, so I'm close to suggesting that we remove the shogun formula from homebrew-core if no functional tarball is publicly available

* https://github.com/shogun-toolbox/shogun/issues/4696#issuecomment-520306967

**Comment by scpeters** [comment]
we should bump the revision for `collectd`

I'll investigate whether https://github.com/mobile-shell/mosh/commit/e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0 will fix the mojave build of mosh

**Comment by scpeters** [comment]
That mosh commit seems to fix it, and the mosh build fails on mojave even without this PR so I've added it as a patch to mosh in https://github.com/Homebrew/homebrew-core/pull/43037

**Comment by scpeters** [comment]
I just rebased and added a revision bump for collectd; I think the main failures will now be from shogun

**Comment by scpeters** [comment]
I can't reproduce the apache-arrow bottle build failure on sierra:

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/46558/version=sierra/testReport/junit/brew-test-bot/sierra/install___build_bottle_apache_arrow/

**Comment by scpeters** [comment]
shogun tarballs are fixed, so I just rebased

**Comment by scpeters** [comment]
shogun is fixed! but now there's a bunch of test failures complaining about a lack of shared memory in the test machines. maybe we need to rebuild the virtual machine images?

**Comment by scpeters** [comment]
I rebooted the VM images and will try a rebuild

**Comment by scpeters** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
@scpeters, just so you know, the shared memory issue has an issue in #43142. I'm keeping track of PRs (or at least trying to) that are failing due to this issue.

**Comment by scpeters** [comment]
now there are just some failures related to apache-arrow on mojave

**Comment by scpeters** [comment]
Again, I can't reproduce the apache-arrow failure, so I don't have anything else to add to this PR at the moment

**Comment by scpeters** [comment]
wow, it worked!

**Comment by lembacon** [comment]
Actually, `mosh` should now build properly with `protobuf` rather than `protobuf@3.7` after #43037. I'm going to submit a new pull request for that. 😜

**Comment by scpeters** [comment]
@lembacon do you want to include the fix from https://github.com/Homebrew/homebrew-core/pull/43349 also?

**Comment by lembacon** [comment]
I've already merged #43430, but can do that separately 😹

**Comment by scpeters** [comment]
ok, thanks I was up a little late last night

**Pull request closed without merging**
