### PR TITLE
dvd-vr 0.9.7 (new formula)

### PR DESCRIPTION
**Pull request by tadayosi**
Signed-off-by: Tadayoshi Sato <sato.tadayoshi@gmail.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
How widely used is this tool? It is not in active development (no releases in 7 years, no github commit in 5 years) and the [github repository](https://github.com/pixelb/dvd-vr) has very low notability (6 stars, 2 watchers, 1 fork).

**Comment by tadayosi** [comment]
@fxcoudert I have no ideas, honestly. At least I can find one answer [1] that promotes the tool at superuser.com (it's also quite old though), and the official forum [2] seemingly had been vibrant until 2015.

Why I need it is just because even though it's an old, seemingly inactive project there are no other alternative tools in the same category that are as simple and can do the same job.

[1] http://superuser.com/questions/11101/how-can-i-encode-a-vro-file-to-an-avi-file/11385#11385
[2] http://comments.pixelbeat.org/programs/dvd-vr/

**Comment by pixelb** [comment]
Yes it's fairly unique in that I reversed engineered the VRO format to create the program.
I can make any changes needed to the original project

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Given reasoning above I'm fine with accepting this. Thanks all.

**Comment by fxcoudert** [comment]
Thanks @tadayosi for contributing the formula!

**Pull request closed without merging**
