### PR TITLE
libtorch 1.7.0 and torchvision 0.8.1

### PR DESCRIPTION
**Pull request by ankane**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates. <-- PyYAML and typing are already on the latest versions

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by ankane** [comment]
Looks like TorchVision needs updated at the same time. Okay to add as part of this PR? (I think they'll fail individually if updated separately)

**Comment by chenrui333** [comment]
yeah, let's add part of this PR. always good to have dependencies bump together though.

**Comment by jonchang** [comment]
Split the commits and force pushed.

**Review by chenrui333 — DISMISSED** [review]

**Comment by jonchang** [comment]
Looks like the test will need to be updated as there's been an upstream change in their "hello world" example: https://github.com/pytorch/vision/commit/c36dc43b115b495943813a26004c740d8bffd5b6#diff-bebf2888976ae2dc4aa66683575d9e2d0fb1e11716b9917c0f62ff9ad579ffcc

**Review by fxcoudert — APPROVED** [review]

**Review by jonchang — APPROVED** [review]

**Comment by ankane** [comment]
Thanks all!

**Pull request closed without merging**
