### PR TITLE
swagger-codegen 3.0.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails on test:
```
==> /usr/local/Cellar/swagger-codegen/3.0.2/bin/swagger-codegen generate -i minimal.yaml -l swagger
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name swagger
```

**Comment by SMillerDev** [comment]
@igas Got time to fix this?

**Comment by igas** [comment]
@SMillerDev, unfortunately, I'm not java dev. I would need help here or we should close it.

**Comment by jbonhag** [comment]
@igas It looks like the `swagger` generator is no longer support in 3.0.2: https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.2

The `html` generator can be used instead.  Also, I'd suggest changing the version to use `openapi: 3.0.0` since that is how versions are handled in OAS 3.

So, the full test should look like this:

```
  test do
    (testpath/"minimal.yaml").write <<~EOS
      ---
      openapi: 3.0.0
      info:
        version: 0.0.0
        title: Simple API
      paths:
        /:
          get:
            responses:
              200:
                description: OK
    EOS
    system "#{bin}/swagger-codegen", "generate", "-i", "minimal.yaml", "-l", "html"
  end
```

**Pull request closed without merging**
