### PR TITLE
git-cola 3.12.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /opt/homebrew/Cellar/git-cola/3.12.0/bin/git-cola --version
  
  You do not seem to have PyQt5, PySide, or PyQt4 installed.
  Please install it before using git-cola, e.g. on a Debian/Ubutnu system:
  
      sudo apt-get install python-pyqt5 python-pyqt5.qtwebkit
  
  Error: git-cola: failed
  An exception occurred within a child process:
```

**Comment by davvid** [comment]
The installed `/opt/homebrew/Cellar/git-cola/3.12.0/bin/git-cola` *should* be using the correct `#!` line pointing to python3.9 after the distutils `#!` replacement happens during the install step. That's something worth confirming.

Otherwise, verifying that PyQt5 is importable using the same interpreter should be sufficient for cola. Did anything change nearby Qt / PyQt5 recently?

**Comment by chenrui333** [comment]
nope, I did not see anything changed with pyqt5, let me check with shebang setup in my local install.

**Comment by chenrui333** [comment]
> The installed `/opt/homebrew/Cellar/git-cola/3.12.0/bin/git-cola` _should_ be using the correct `#!` line pointing to python3.9 after the distutils `#!` replacement happens during the install step. That's something worth confirming.

Yeah, confirmed
```
$ cat /opt/homebrew/Cellar/git-cola/3.12.0/bin/git-cola
#!/opt/homebrew/opt/python@3.9/bin/python3.9
# EASY-INSTALL-SCRIPT: 'git-cola==3.12.0','git-cola'
__requires__ = 'git-cola==3.12.0'
__import__('pkg_resources').run_script('git-cola==3.12.0', 'git-cola')
```

**Comment by chenrui333** [comment]
Looks like it is indeed on our end, the re-test on git-cola 3.11.0 also has some issue.

**Comment by chenrui333** [comment]
@davvid you can see the regression test in #94146

**Pull request closed without merging**
