### PR TITLE
wpscan 3.8.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Could not reproduce the `$ brew audit --skip-style wpscan --online` error locally, re-run the build.

**Comment by chenrui333** [comment]
```
==> brew install ./wpscan--3.8.1.catalina.bottle.tar.gz
==> /usr/local/Cellar/wpscan/3.8.1/bin/wpscan --update
Warning: Files were found with references to the Homebrew shims directory.
The offending files are:
  libexec/ruby/2.7.0/extensions/x86_64-darwin-19/2.7.0/ffi-1.12.2/mkmf.log
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/man/Makefile
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/libtool
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/Makefile
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/include/Makefile
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/testsuite/Makefile
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/config.status
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/doc/Makefile
  libexec/ruby/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19/config.log
==> Summary
/usr/local/Cellar/wpscan/3.8.1: 10,489 files, 96.9MB
Removing: /Users/brew/Library/Caches/Homebrew/wpscan--3.8.1.catalina.bottle.tar.gz... (0B)
```

**Comment by Bo98** [comment]
None of those files should really be installed in the first place. Is that normal from Ruby gems?

**Comment by chenrui333** [comment]
> None of those files should really be installed in the first place. Is that normal from Ruby gems?

not normal, never saw things like this before.

**Comment by Bo98** [comment]
I think the problem here is that it is building libffi from source. We don't really want to do that - it should just use macOS's included one or Homebrew's one.

**Comment by Bo98** [comment]
(This should use `uses_from_macos "libffi", :since => :catalina` when that is in `brew`: Homebrew/brew#7458)

**Pull request closed without merging**
