### PR TITLE
tcl-tk: align with linux

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
On ARM:
```
Error: 1 failed step!
brew test --retry --verbose flawfinder
```
That looks new, though I don't know where it's coming from.

**Comment by dtrodrigues** [comment]
PR for `flawfinder` submitted: https://github.com/Homebrew/homebrew-core/pull/69244

**Comment by iMichka** [comment]
I guess that all of these are unrelated and already known:
```
2021-01-17T17:45:35.6170600Z Error: 12 failed steps!
2021-01-17T17:45:35.6182290Z brew test --retry --verbose asuka
2021-01-17T17:45:35.6183590Z brew test --retry --verbose augustus
2021-01-17T17:45:35.6184890Z brew test --retry --verbose creduce
2021-01-17T17:45:35.6186140Z brew test --retry --verbose geant4
2021-01-17T17:45:35.6187190Z brew test --retry --verbose glyr
2021-01-17T17:45:35.6188360Z brew test --retry --verbose googler
2021-01-17T17:45:35.6189570Z brew test --retry --verbose hyperkit
2021-01-17T17:45:35.6190660Z brew test --retry --verbose networkit
2021-01-17T17:45:35.6191200Z brew install pypy
2021-01-17T17:45:35.6192280Z brew install pypy3
2021-01-17T17:45:35.6193480Z brew test --retry --verbose qxmpp
2021-01-17T17:45:35.6194790Z brew test --retry --verbose treefrog
```

**Comment by carlocab** [comment]
If that's Big Sur then yes. Otherwise, some of those are new.

**Comment by iMichka** [comment]
Merged as this is almost a no-op on Mac, the rest of the tests are fine. I'll help our with the remaining Python 3 issues when I am done with the whole linux to code migration.

**Comment by carlocab** [comment]
>I am done with the whole linux to code migration.

Might be a while then...

**Comment by iMichka** [comment]
Ha ha yes but when it is done I'll have less merging to do, so I'll have a lot of idle time to fill.

**Pull request merged**
