### PR TITLE
cargo-auditable 0.6.1 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

```
cargo-auditable
  * line 39, col 7: use "cargo", "install", *std_cargo_args
Error: 1 problem in 1 formula detected.
```

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
Looks like the style check needs a fix in Homebrew/brew.

**Comment by MikeMcQuaid** [comment]
PR opened in https://github.com/Homebrew/brew/pull/15888

**Comment by MikeMcQuaid** [comment]
Actually went with https://github.com/Homebrew/brew/pull/15887 instead. Have kicked off a rerun.

**Comment by chenrui333** [comment]
Nice, now it is good to go.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
