### PR TITLE
[WIP] Temporary duplicate of #1123 - mitmproxy 0.17.1

### PR DESCRIPTION
**Pull request by rogeriopradoj**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@rogeriopradoj Can you explain why you're creating a temporary duplicate?

**Comment by rogeriopradoj** [comment]
Hi, @mikemcquaid . My intention was to rebuild it on CI.

**Comment by mikemcquaid** [comment]
@rogeriopradoj Why?

**Comment by rogeriopradoj** [comment]
#1123 commit is working fine on my machine. So I'd like to know if if could re-trigger http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1817/ 's (with a new commit/PR), and it pass, `mitmproxy v0.17.1` could be merged.

Too wrong ? 😅

**Comment by mikemcquaid** [comment]
@rogeriopradoj Please comment in future rather than creating PRs with other people's commits. Does it work on your 10.9 machine? Thanks!

**Comment by rogeriopradoj** [comment]
@mikemcquaid , alright, sorry for my bad.

**Comment by mikemcquaid** [comment]
No worries!

**Pull request closed without merging**
