### PR TITLE
guile: Update to 2.2.0

### PR DESCRIPTION
**Pull request by ts826848**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Devel is now older than stable, but doesn't seem a "real" devel is available, since 2.2.0 just came out?

### CODE REVIEW

**Comment by ilovezfs** [comment]
other patch is still needed?

**Comment by ilovezfs** [comment]
Also the devel spec is older than the stable spec … is there a new devel version that actually is > 2.2.0?

**Comment by ilovezfs** [comment]
@DomT4 I hate to even ask this question, but … do you think we're going to need a guile@2.0?

**Comment by aw1621107** [comment]
Don't know about the patch. Trying right now...

Latest tag in the guile repo appears to be 2.2.0, so doesn't seem to be a devel spec at the moment. Should I just get rid of it?

**Comment by ilovezfs** [comment]
>Should I just get rid of it?

Yup.
```
iMac-TMP:~ joe$ brew audit guile
guile:
  * devel version 2.1.8 is older than stable version 2.2.0
Error: 1 problem in 1 formula
```

**Comment by aw1621107** [comment]
Looks like the other patch shouldn't be necessary. From libguile/filesys.c:1497:

```
     /* mkostemp(2) only defines O_APPEND, O_SYNC, and O_CLOEXEC to be
         useful, as O_RDWR|O_CREAT|O_EXCL are implicitly added.  It also
         notes that other flags may error on some systems, which turns
         out to be the case.  Of those flags, O_APPEND is the only one
         of interest anyway, so limit to that flag.  */
      open_flags &= O_APPEND;
```

**Comment by ilovezfs** [comment]
@aw1621107 looks like we need revision bumps for mdk and autogen

**Comment by ilovezfs** [comment]
and actually autogen doesn't build :(

**Comment by aw1621107** [comment]
Should we hold off on this until autogen is fixed?

**Comment by ilovezfs** [comment]
push the revision bumps and I'll add my patch :)

**Comment by aw1621107** [comment]
Done!

**Comment by ilovezfs** [comment]
patch added

**Comment by DomT4** [comment]
> @DomT4 I hate to even ask this question, but … do you think we're going to need a guile@2.0?

Hopefully not 😖. Possibly for `gnutls`; the compatibility there hasn't always been great.

**Comment by JCount** [comment]
@aw1621107 Thank you for another great contribution! 😸

**Pull request closed without merging**
