### PR TITLE
GMIC: Install dylib and gmic.h on macOS

### PR DESCRIPTION
**Pull request by zisoft**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
The GMIC formula applies the patch to create the dylib for macOS.

When building from source one can see in the build directory that the dylib is successfully created, it is just not installed in `/usr/local/lib`. Same is true for `glib.h`, it is not installed in `/usr/local/include`.

### CODE REVIEW

**Comment by Bo98** [comment]
Makes sense. The mess here is largely because the Makefile doesn't support macOS.

Ideal scenario would be getting #156785 working, but I've not followed what the latest state of that is.

**Comment by MikeMcQuaid** [comment]
> The mess here is largely because the Makefile doesn't support macOS so needs large hacks like this to get it remotely useful.

Yeh, would be good to report this upstream.

**Review by MikeMcQuaid — COMMENTED** [review]
Seems fine, would be nice to add a Ruby comment explaining why this is needed.

**Comment by zisoft** [comment]
> Seems fine, would be nice to add a Ruby comment explaining why this is needed.

Now done.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @zisoft!

**Pull request merged**
