### PR TITLE
filebeat: migrate to python@3.10

### PR DESCRIPTION
**Pull request by cclauss**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
This will need a revision bump. Please add `revision 1`

**Comment by cclauss** [comment]
That contradicts https://github.com/Homebrew/homebrew-core/pull/90767#discussion_r765700666

**Review by iMichka — APPROVED** [review]
Right sorry, I missed that it was only a build dep. All good then :)

**Comment by iMichka** [comment]
Thanks @cclauss !

**Pull request closed without merging**
