### PR TITLE
pprint 0.9.1 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
This formula depends on C++17 (it's written for use only with C++17). Should I just `depends_on MacOS.version >= :sierra` or is this formula just not eligible for inclusion? It seems that we've tried to avoid C++17 in the past with some other formulae.

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
I'm fine with c++17... as long as CI is happy.

**Comment by zbeekman** [comment]
merged. Thanks! 🍻

**Pull request closed without merging**
