### PR TITLE
passenger 5.0.29

### PR DESCRIPTION
**Pull request by FooBarWidget**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@FooBarWidget Shouldn't the fix for https://github.com/phusion/passenger/issues/1288 be removed from the formula?

**Comment by FooBarWidget** [comment]
@ilovezfs I don't know? Why should it be removed from the formula? Did something change recently?

**Comment by ilovezfs** [comment]
@FooBarWidget The upstream issue https://github.com/phusion/passenger/issues/1288 is closed and yet we're still patching it, so I'm confused.

**Comment by FooBarWidget** [comment]
The upstream issue is for the homebrew formula itself. The fix referred to
by the upstream issue *is* the very fix inside the formula.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/97f648f2171a457a6ba4aee28bb7173884d1d1ff. Thank you for your contribution to Homebrew @FooBarWidget; we appreciate it! :smiley_cat:

**Pull request closed without merging**
