### PR TITLE
moto 4.2.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`  ModuleNotFoundError: No module named 'boto3'`

**Comment by branchvincent** [comment]
we need a `.pth` file for `cfn-lint`

**Review by iMichka — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
So ok to ship or not? I don't see any failure here.

**Comment by chenrui333** [comment]
> So ok to ship or not? I don't see any failure here.

I think we can ship for now, and followup with cfn-lint pth thing

**Review by iMichka — APPROVED** [review]

**Pull request merged**
