### PR TITLE
postgresql 12.1 (and related changes)

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Just testing the waters at first. May well require more revision bumps and patches.

### CODE REVIEW

**Comment by Bo98** [comment]
I've also attempted to fix the include directories in pg_config pointing to the Cellar. This means that libpqxx should no longer need to be rev bumped every single time postgresql gets any sort of version or revision bump.

I've also taken the opportunity to make it use libpq instead of postgresql since it doesn't need the full set of server files. Might be an idea to make most things use libpq which will make it easier to identify what actually does need a rev bump, like any server plugin.

**Comment by Bo98** [comment]
Note to self: try to get it to build on catalina_orka_1 and highsierra_orka_1 as the tests don't work on the other nodes.

**Comment by Bo98** [comment]
I have a fix for all the remaining errors except Citus, which is blocked on Homebrew/brew#6749 being merged or otherwise alternatively fixed.

I'll push the changes once that happens.

**Review by chenrui333 — APPROVED** [review]
Thanks for the work!!

**Comment by chenrui333** [comment]
🎉

**Pull request closed without merging**
