### PR TITLE
deno 1.7.4

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by carlocab** [comment]
|Commit|Big Sur ARM|Big Sur|Catalina|Mojave|CI Logs|
|---|:---:|:---:|:---:|:---:|---|
|1cd0d1c1ce0bcc17436e5f7104df984214e72de9| ❌ | ❌ | ❌ | ❌ | https://github.com/Homebrew/homebrew-core/actions/runs/564044255 |

**Comment by carlocab** [comment]
Errors are the same across the four nodes, so I think there's something wrong that needs fixing:
```
[rusty_v8 0.17.0] ninja: error: '../../../../../../../Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.17.0/v8/tools/gen-v8-gn.py', needed by 'gen/v8/include/v8-gn.h', missing and no known rule to make it
```

**Comment by Bo98** [comment]
Deno 1.7.3 (and 1.7.4) ships with a buggy rusty_v8 0.17.0, that simply doesn't build from source from its cargo crate. The bug was fixed in rusty_v8 0.18.1. There's an effort to update to the latest rusty_v8 here: https://github.com/denoland/deno/pull/9466

Until then, this is probably a "won't merge" unless someone knows a temporary workaround.

**Comment by Bo98** [comment]
(Also, Deno gets a new version weekly so it won't be long before the next version is out)

**Comment by chenrui333** [comment]
Sounds good, closing the PR and wait for the next release.

**Pull request closed without merging**
