### PR TITLE
taskwarrior-tui 0.13.31

### PR DESCRIPTION
**Pull request by kdheepak**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling failure v0.1.8
error: aborting due to previous error
```

**Comment by kdheepak** [comment]
Looks like I'm using a package that is not supported on the version of rustc that homebrew uses. I'll downgrade the dependency and make a new release.

**Comment by kdheepak** [comment]
I've made a new release and the PR is here: https://github.com/Homebrew/homebrew-core/pull/83406.

**Comment by chenrui333** [comment]
yeah, we have an ongoing Rust 1.54 upgrade - #82155

**Comment by carlocab** [comment]
I've triggered a merge for #82155, so Homebrew `rustc` should be good for your next version bump. Thanks @kdheepak!

**Comment by kdheepak** [comment]
Thank you!

**Pull request closed without merging**
