### PR TITLE
snap-telemetry: various fixes/tweaks

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

🙈

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks! Now which of these do you think I could/should write an audit for?

**Comment by DomT4** [comment]
`go` and `glide` are _almost_ always going to be `:build` deps. We'd been trying to solve the metafiles issue for ages but hadn't come up with a good solution before I ran off.

**Comment by DomT4** [comment]
I guess you _could_ write an audit check to see if some variation of `LICENSE` or `COPYING` exist in the prefix, but inevitably that would raise some false flags.

**Comment by DomT4** [comment]
https://github.com/Homebrew/brew/pull/1432

**Comment by dunn** [comment]
😸

**Pull request closed without merging**
