### PR TITLE
nifi nifi-registry 1.20.0

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]

**Comment by chenrui333** [comment]
`cp: error writing '/tmp/12298520230211-2049-2gzcnq/nifi--1.20.0.arm64_ventura.bottle.tar.gz': No space left on device`

**Comment by chenrui333** [comment]
CI uploading bottle issue

**Review by chenrui333 — DISMISSED** [review]

**Comment by p-linnane** [comment]
Going to publish bottles using the large runner.

**Comment by chenrui333** [comment]
🎉 🚀

**Pull request closed without merging**
