### PR TITLE
binwalk: remove gcc dependency since is no longer needed

### PR DESCRIPTION
**Pull request by abpostelnicu**
This PR addresses issue #56363

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
Hi. Can you please bump the `revision` line from 1 to 2 as we are changing a dependency here. Thanks!

**Comment by abpostelnicu** [comment]
> Hi. Can you please bump the `revision` line from 1 to 2 as we are changing a dependency here. Thanks!

Sure, thanks! I've updated the PR.

**Review by iMichka — APPROVED** [review]
Thans for your contribution @abpostelnicu !

**Comment by abpostelnicu** [comment]
@iMichka can you merge this?

**Pull request closed without merging**
