### PR TITLE
algol68g 3.1.2

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
I'm not sure what to do about the Linux failure.

**Comment by chenrui333** [comment]
```
  Unwanted system libraries:
    /lib/x86_64-linux-gnu/libquadmath.so.0
```

**Comment by chenrui333** [comment]
> I'm not sure what to do about the Linux failure.

maybe try removing it.

**Review by carlocab — APPROVED** [review]
```
❯ curl -fsSL https://formulae.brew.sh/api/formula/algol68g.json | jq '[.["analytics"], .["analytics-linux"] | .["install"]["365d"]["algol68g"]] | {macos: .[0], linux: .[1]}'
{
  "macos": 15654,
  "linux": 11
}
```
~15000 installs on macOS vs 11 installs on Linux in the past year. Let's ship this.

**Comment by danielnachun** [comment]
I opened a fix for this in `brew`: https://github.com/Homebrew/brew/pull/14653.  We should allow linkage to this library as it's part of GCC normally.

**Pull request closed without merging**
