### PR TITLE
smimesign 0.0.13

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> go build -o /usr/local/Cellar/smimesign/0.0.13/bin/smimesign -ldflags -X main.versionString=0.0.13
command_verify.go:11:2: cannot find package "github.com/certifi/gocertifi" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/certifi/gocertifi (from $GOROOT)
	/private/tmp/smimesign-20190513-77950-ig2itw/smimesign-0.0.13/src/github.com/certifi/gocertifi (from $GOPATH)
command_sign.go:12:2: cannot find package "github.com/mastahyeti/certstore" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/mastahyeti/certstore (from $GOROOT)
	/private/tmp/smimesign-20190513-77950-ig2itw/smimesign-0.0.13/src/github.com/mastahyeti/certstore (from $GOPATH)
command_sign.go:13:2: cannot find package "github.com/mastahyeti/cms" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/mastahyeti/cms (from $GOROOT)
	/private/tmp/smimesign-20190513-77950-ig2itw/smimesign-0.0.13/src/github.com/mastahyeti/cms (from $GOPATH)
main.go:11:2: cannot find package "github.com/pborman/getopt/v2" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/pborman/getopt/v2 (from $GOROOT)
	/private/tmp/smimesign-20190513-77950-ig2itw/smimesign-0.0.13/src/github.com/pborman/getopt/v2 (from $GOPATH)
command_sign.go:14:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/pkg/errors (from $GOROOT)
	/private/tmp/smimesign-20190513-77950-ig2itw/smimesign-0.0.13/src/github.com/pkg/errors (from $GOPATH)
status.go:11:2: cannot find package "golang.org/x/crypto/openpgp/packet" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/golang.org/x/crypto/openpgp/packet (from $GOROOT)
	/private/tmp/smimesign-20190513-77950-ig2itw/smimesign-0.0.13/src/golang.org/x/crypto/openpgp/packet (from $GOPATH)
status.go:12:2: cannot find package "golang.org/x/crypto/openpgp/s2k" in any of:
	/usr/local/Cellar/go/1.12.5/libexec/src/golang.org/x/crypto/openpgp/s2k (from $GOROOT)
	/private/tmp/smimesign-20190513-77950-ig2itw/smimesign-0.0.13/src/golang.org/x/crypto/openpgp/s2k (from $GOPATH)
```

**Comment by chenrui333** [comment]
in my local
```
==> /usr/local/Cellar/smimesign/0.0.13/bin/smimesign --version
panic: Too many strings for String helpvalue

goroutine 1 [running]:
github.com/pborman/getopt/v2.(*Set).VarLong(0xc000148000, 0x43bfcc0, 0xc0000e2c70, 0x431bc68, 0xc, 0xc000000000, 0xc0000e8d80, 0x3, 0x3, 0x400e2d8, ...)
	/private/tmp/smimesign-20190515-10377-19to3zh/smimesign-0.0.13/src/github.com/pborman/getopt/v2/var.go:52 +0x403
github.com/pborman/getopt/v2.(*Set).EnumVarLong(0xc000148000, 0xc0000e2c70, 0x431bc68, 0xc, 0x0, 0xc0000e2c60, 0x1, 0x1, 0xc0000e8d80, 0x3, ...)
	/private/tmp/smimesign-20190515-10377-19to3zh/smimesign-0.0.13/src/github.com/pborman/getopt/v2/enum.go:72 +0x160
github.com/pborman/getopt/v2.(*Set).EnumLong(...)
	/private/tmp/smimesign-20190515-10377-19to3zh/smimesign-0.0.13/src/github.com/pborman/getopt/v2/enum.go:48
github.com/pborman/getopt/v2.EnumLong(0x431bc68, 0xc, 0x0, 0xc0000e2c60, 0x1, 0x1, 0xc0000e8d80, 0x3, 0x3, 0xc000111f78)
	/private/tmp/smimesign-20190515-10377-19to3zh/smimesign-0.0.13/src/github.com/pborman/getopt/v2/enum.go:43 +0xcc
main.init.ializers()
	/private/tmp/smimesign-20190515-10377-19to3zh/smimesign-0.0.13/src/github.com/github/smimesign/main.go:36 +0x5a5
Error: smimesign: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<2>.
```

**Comment by chenrui333** [comment]
Should be fixed now!

**Comment by chenrui333** [comment]
@fxcoudert commits squashed :)

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by chenrui333** [comment]
Thanks @zbeekman !

**Pull request closed without merging**
