### PR TITLE
efl: fix array brace position

### PR DESCRIPTION
**Pull request by miguelarauj1o**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@UniqMartin Out of interest: do you agree with this Rubocop check? I'm not sure if I do 😒

**Comment by UniqMartin** [comment]
@MikeMcQuaid I do, in the sense that it enforces a more consistent brace placement. But I don't agree with the proposed fix, though that's the one with a minimal diff. I think in almost all cases we want to have either:

```ruby
args = [
  "--foo",
  "--bar",
  "--baz",
]
```

Or even better:

```ruby
args = %W[
  --foo
  --bar
  --baz
]
```

(The latter is what we tend to use when changing these kinds of arrays or in new formulae, as far as I can tell.)

**Comment by DomT4** [comment]
> (The latter is what we tend to use when changing these kinds of arrays or in new formulae, as far as I can tell.)

👍 x 💯 x 💯

**Comment by DomT4** [comment]
Made some changes separately afterwards because there were other things annoying me in the formula, which you can see in https://github.com/Homebrew/homebrew-core/commit/6f2678fa1e03fb8f724aae0c2ffc18145c945927. 

Merged this PR in https://github.com/Homebrew/homebrew-core/commit/944f300b2931ec84077fe45e96a1d3a8ee03d4c8. Thanks for helping with the style cleanup @miguelarauj1o! 😺

**Pull request merged**
