### PR TITLE
sourcery 0.6.1

### PR DESCRIPTION
**Pull request by jpsim**
and moving url to git

### CODE REVIEW

**Comment by ilovezfs** [comment]
>and moving url to git

Why? Can it not build from the source archive tarball anymore?

**Comment by jpsim** [comment]
> Why? Can it not build from the source archive tarball anymore?

Yes, but that doesn't allow `brew install sourcery --HEAD`.

**Comment by ilovezfs** [comment]
They're entirely independent. If the head url is a Git repository, it will be cloned, etc.

**Comment by jpsim** [comment]
Good point, I'll switch that back then.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @jpsim :rocket:

**Pull request closed without merging**
