### PR TITLE
Add livecheck to Vulkan formulas that don't already have it

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by p-linnane** [comment]
Thanks for the PR @pthariensflame! Livecheck uses the `:git` strategy inherently for GitHub URL's, which fetches tags. Taking a look at all of these formula, `vulkan-profiles` and `vulkan-validationlayers` are the only two that need this change. The default `:git` strategy is working perfect for the others. Would you mind dropping the other 4 commits and then we can get this merged?

**Review by samford — COMMENTED** [review]
Though we generally only add a `livecheck` block if/when it's needed, adding all of these `livecheck` blocks may make some kind of sense if we strictly want to match tags like `v1.3.278` for these formulae. All of these repositories also have other tags that don't use the aforementioned format:

* vulkan-extensionlayer: repository also contains tags like `sdk-1.3.261.1`, `sdk.1.2.176.1-TAG`, `vulkan-sdk-1.3.268.0`
* vulkan-headers: repository also contains tags like `sdk-1.3.261.1`, `sdk.1.2.176.1-TAG`, `vksc1.0.12`, `vulkan-sdk-1.3.275.0`
* vulkan-profiles: repository also contains tags like `roadmap2024`, `sdk-1.3.261.1`, `vulkan-sdk-1.3.275.0`
* vulkan-tools: repository also contains tags like `sdk-1.3.261.1`, `sdk.1.2.176.1-TAG`, `vulkan-sdk-1.3.275.0`
* vulkan-utility-libraries: repository also contains tags like `sdk-1.3.261.1`, `vulkan-sdk-1.3.275.0`
* vulkan-validationlayers: repository also contains tags like `sdk`, `sdk-1.3.261.1`, `sdk.1.2.176.1-TAG`, `snapshot-2024wk07`, `v1.2.133.1-alpha-AndroidBinaries`, `vulkan-sdk-1.3.275.0`

**Comment by p-linnane** [comment]
Naturally, I defer to you on this topic @samford. That makes sense to me for consistency.

**Review by samford — APPROVED** [review]
Since these repositories are connected, all of them contain some tags other than the ones we're interested in, and a couple repositories contain tags that are currently causing problems, I'm okay with adding these `livecheck` blocks as a way of resolving current issues and avoiding potential ones in the future.

Thanks, @pthariensflame!

**Pull request merged**
