### PR TITLE
swagger-codegen 3.0.27

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
I disabled the tests run during Maven build, which are expecting Java 8 environment.
Alternatively, I think the following dependency changes can work:
```diff
diff --git a/modules/swagger-codegen/pom.xml b/modules/swagger-codegen/pom.xml
index 6d49a95e7..aadd310b8 100644
--- a/modules/swagger-codegen/pom.xml
+++ b/modules/swagger-codegen/pom.xml
@@ -294,7 +294,13 @@
         <dependency>
             <groupId>org.mockito</groupId>
             <artifactId>mockito-core</artifactId>
-            <version>2.8.47</version>
+            <version>2.28.2</version>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>javax.annotation</groupId>
+            <artifactId>javax.annotation-api</artifactId>
+            <version>1.3.2</version>
             <scope>test</scope>
         </dependency>

diff --git a/pom.xml b/pom.xml
index 75db83a53..e52cfb1f5 100644
--- a/pom.xml
+++ b/pom.xml
@@ -125,7 +125,7 @@
                 <version>${surefire-version}</version>
                 <configuration>
                     <testNGArtifactName>none:none</testNGArtifactName>
-                    <argLine>-XX:+StartAttachListener</argLine>
+                    <argLine>-Djdk.attach.allowAttachSelf=true -XX:+StartAttachListener</argLine>
                 </configuration>
                 <executions>
                     <execution>
```

---

However, I think it is going to fail on Homebrew's test based on local attempt.
Haven't taken a look why though.

**Comment by cho-m** [comment]
Actually looks like a mistagged release based on 2.X codebase rather than 3.X.

Only 2 commit difference between 2.4.21 and 3.0.27: 
https://github.com/swagger-api/swagger-codegen/compare/v2.4.21...v3.0.27

However, ~1500 commit difference between 3.0.26 and 3.0.27:
https://github.com/swagger-api/swagger-codegen/compare/v3.0.26...v3.0.27

**Comment by chenrui333** [comment]
> Actually looks like a mistagged release based on 2.X codebase rather than 3.X.
> 
> Only 2 commit difference between 2.4.21 and 3.0.27:
> [swagger-api/swagger-codegen@v2.4.21...v3.0.27](https://github.com/swagger-api/swagger-codegen/compare/v2.4.21...v3.0.27)
> 
> However, ~1500 commit difference between 3.0.26 and 3.0.27:
> [swagger-api/swagger-codegen@v3.0.26...v3.0.27](https://github.com/swagger-api/swagger-codegen/compare/v3.0.26...v3.0.27)

Nice find!!

**Comment by KillDozerX2** [comment]
Any updates in this?

**Comment by chenrui333** [comment]
No update on this, I think we filed an upstream issue, but have not heard any feedback on it yet?

**Pull request closed without merging**
