### PR TITLE
workflows: add triage-ci.yml

### PR DESCRIPTION
**Pull request by carlocab**
This will allow us to add automation that will be done after CI
failures.

For now, we can automate pinging `@woodruffw` and `@alex` on failures of
the `brew-pip-audit` workflow to avoid other maintainers from having to
manually do this.

See related discussions at #131661.

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
> For now, we can automate pinging `@woodruffw` and `@alex` on failures of
> the `brew-pip-audit` workflow to avoid other maintainers from having to
> manually do this.

Could this be done in that workflow instead?

**Comment by alex** [comment]
I think that's phrased in a confusing way: brew-pip-audit generates regular PRs to bump resources in formulas, we're interested in CI failures on _those_ PRs, not failures in brew-pip-audit itself.

**Comment by carlocab** [comment]
> I think that's phrased in a confusing way: brew-pip-audit generates regular PRs to bump resources in formulas, we're interested in CI failures on _those_ PRs, not failures in brew-pip-audit itself.

Yes, exactly, sorry for the lack of clarity.

Given the desired behaviour the workflow needs to live here. I can stick this into an existing workflow (e.g. `automerge.yml`), but I imagine we'd rather have shorter workflows that do specific things rather than fewer but longer workflows that do multiple different things.

**Review by MikeMcQuaid — APPROVED** [review]
Ok, thanks: with that context this approach makes sense to me!

**Review by ZhongRuoyu — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Review by woodruffw — APPROVED** [review]
LGTM, thank you @carlocab!

**Pull request merged**
