### PR TITLE
mysql: coexist with brew-supplied protobuf

### PR DESCRIPTION
**Pull request by Hajitorus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As per #45342.

### CODE REVIEW

**Comment by scpeters** [comment]
per the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook#patches), it's best to first submit the patch upstream to make sure they are aware of it and that it hasn't already been fixed in a different way

it's also great to reference the patch submitted to upstream via a URL instead of embedding it into the formula

**Comment by Hajitorus** [comment]
I'd investigated reporting upstream but chickened out. Will get it done. Guessing that https://github.com/Homebrew/formula-patches is a decent place to host this tiny patch so I'm not referencing some random gist?

**Comment by Hajitorus** [comment]
Upstream report: https://bugs.mysql.com/bug.php?id=97246

**Comment by Hajitorus** [comment]
PR for formula-patches submitted to enable URL patching instead of formula-inline.

#https://github.com/Homebrew/formula-patches/pull/279

**Pull request closed without merging**
