### PR TITLE
swiftlint 0.19.0

### PR DESCRIPTION
**Pull request by jpsim**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jpsim** [comment]
Question: what should I do with the `devel` version now that it's been superseded by the official release of 0.19.0? I assume that straight up removing it from the formula will make `brew install swiftlint --devel` fail?

**Comment by ilovezfs** [comment]
Yeah, you'll get `Error: No devel block is defined for swiftlint` which is what we want to happen.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @jpsim :tada:

**Comment by jpsim** [comment]
Thanks!

**Pull request closed without merging**
