### PR TITLE
libcbor 0.6.0

### PR DESCRIPTION
**Pull request by PJK**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
@PJK can you try including the fix from https://github.com/Homebrew/homebrew-core/pull/50588?

**Comment by xanderlent** [comment]
Hi! I've dug into the Jenkins output and it seems like the two failures in the build are related to using this library:

```
[snip]

==> brew linkage --test libfido2
==> FAILED
Broken dependencies:
  /usr/local/opt/libcbor/lib/libcbor.0.dylib (libcbor)

==> brew install --only-dependencies --include-test libfido2

==> brew test --verbose libfido2
==> FAILED
Testing libfido2
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200316-37323-i5mz4m.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libfido2.rb --verbose
==> /usr/bin/clang -std=c99 test.c -I/usr/local/Cellar/libfido2/1.3.1/include -I/usr/local/opt/openssl@1.1/include -o test -L/usr/local/Cellar/libfido2/1.3.1/lib -lfido2
==> ./test
dyld: Library not loaded: /usr/local/opt/libcbor/lib/libcbor.0.dylib
  Referenced from: /usr/local/opt/libfido2/lib/libfido2.1.dylib
  Reason: image not found
Error: libfido2: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1968:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libfido2.rb:53:in `block in <class:Libfido2>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1775:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1774:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:865:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1773:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2018:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2017:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1767:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:32:in `<main>'

[snip]
```

**Comment by jonchang** [comment]
`libfido2` will probably need a revision bump in that case.

**Comment by PJK** [comment]
It is not obvious to me why libfido gets linked to that particular object (libcbor.0.dylib), this is what I get after a fresh installation, which seems to be WAI (with https://github.com/PJK/libcbor/issues/75 being fixed):

```
=> ls /usr/local/opt/libcbor/lib
libcbor.0.6.0.dylib libcbor.dylib       pkgconfig
```

**Comment by jonchang** [comment]
Add `revision 1` to `libfido2` in a separate commit on this pull request.

**Comment by PJK** [comment]
Thanks, done! Jenkins looks good, PTAL

**Comment by SMillerDev** [comment]
> Add `revision 1` to `libfido2` in a separate commit on this pull request.

`brew bump-revision libfido2` is the easiest way

**Pull request closed without merging**
