### PR TITLE
bluepill 3.1.0

### PR DESCRIPTION
**Pull request by oliverhu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Update for #32602 , cc @fxcoudert

### CODE REVIEW

**Comment by fxcoudert** [comment]
Fails to build on Sierra:

```
Ld /tmp/bluepill-20181023-72426-4tbiig/bluepill-3.1.0/Release/bp normal x86_64
    cd /tmp/bluepill-20181023-72426-4tbiig/bluepill-3.1.0/Bluepill-cli
    export MACOSX_DEPLOYMENT_TARGET=10.12
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/tmp/bluepill-20181023-72426-4tbiig/bluepill-3.1.0/Release -F/tmp/bluepill-20181023-72426-4tbiig/bluepill-3.1.0/Release -F/Library/Developer/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/../SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks -filelist /Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-genpenqdeokipjbgewhcfqkxcgrg/Build/Intermediates.noindex/Bluepill-cli.build/Release/bp.build/Objects-normal/x86_64/bp.LinkFileList -mmacosx-version-min=10.12 -Xlinker -object_path_lto -Xlinker /Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-genpenqdeokipjbgewhcfqkxcgrg/Build/Intermediates.noindex/Bluepill-cli.build/Release/bp.build/Objects-normal/x86_64/bp_lto.o -fobjc-arc -fobjc-link-runtime -weak_framework DVTFoundation -weak_framework DVTiPhoneSimulatorRemoteClient -weak_framework CoreSimulator -weak_framework XCTest -weak_framework DTXConnectionServices -weak_framework SimulatorKit -framework CoreSimulator -framework AppKit -framework Foundation -framework DVTiPhoneSimulatorRemoteClient -Xlinker -dependency_info -Xlinker /Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-genpenqdeokipjbgewhcfqkxcgrg/Build/Intermediates.noindex/Bluepill-cli.build/Release/bp.build/Objects-normal/x86_64/bp_dependency_info.dat -o /tmp/bluepill-20181023-72426-4tbiig/bluepill-3.1.0/Release/bp
ld: warning: Auto-Linking supplied '/tmp/bluepill-20181023-72426-4tbiig/bluepill-3.1.0/Release/BluepillLib.framework/BluepillLib', framework linker option at /tmp/bluepill-20181023-72426-4tbiig/bluepill-3.1.0/Release/BluepillLib.framework/BluepillLib is not a dylib
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BPApplicationLaunchHandler", referenced from:
      objc-class-ref in Bluepill.o
  "_OBJC_CLASS_$_BPConfiguration", referenced from:
      objc-class-ref in main.o
  "_OBJC_CLASS_$_BPCreateSimulatorHandler", referenced from:
      objc-class-ref in Bluepill.o
  "_OBJC_CLASS_$_BPDeleteSimulatorHandler", referenced from:
      objc-class-ref in Bluepill.o
  "_OBJC_CLASS_$_BPSimulator", referenced from:
      objc-class-ref in Bluepill.o
  "_OBJC_CLASS_$_BPStats", referenced from:
      objc-class-ref in BPTreeAssembler.o
      objc-class-ref in Bluepill.o
      objc-class-ref in main.o
  "_OBJC_CLASS_$_BPUtils", referenced from:
      objc-class-ref in BPTestBundleConnection.o
      objc-class-ref in BPTreeParser.o
      objc-class-ref in BPTestDaemonConnection.o
      objc-class-ref in Bluepill.o
      objc-class-ref in main.o
  "_OBJC_CLASS_$_BPWaitTimer", referenced from:
      objc-class-ref in Bluepill.o
  "_OBJC_CLASS_$_BPXCTestFile", referenced from:
      objc-class-ref in Bluepill.o
  "_OBJC_CLASS_$_SimulatorHelper", referenced from:
      objc-class-ref in BPTestBundleConnection.o
      objc-class-ref in main.o
  "_kCFBundleIdentifier", referenced from:
      -[BPTestBundleConnection _XCT_launchProcessWithPath:bundleID:arguments:environmentVariables:] in BPTestBundleConnection.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jineshqa** [comment]
@fxcoudert xcode 10 not supported on Sierra.

Thanks,
Jinesh

**Comment by fxcoudert** [comment]
If the formula needs Xcode 10, please modify `depends_on :xcode => ["9.0", :build]`

**Comment by oliverhu** [comment]
Thanks, updated @fxcoudert

**Comment by lembacon** [comment]
@fxcoudert This added a file named `3.1.0.tar.gz` to the root of the repository. 🙃

**Comment by oliverhu** [comment]
oh darn, I'll create another PR to get rid of that. Sorry for this.

**Comment by oliverhu** [comment]
https://github.com/Homebrew/homebrew-core/pull/33353 @lembacon  @fxcoudert

**Pull request closed without merging**
