### PR TITLE
groonga 6.0.8

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 I realized a cumbersome workaround to the way the build.with? stuff causes invisibility is to do this

```
  depends_on "zeromq" => :optional
  depends_on "libevent" if build.with? "zeromq"
  depends_on "libevent" => :optional
  depends_on "zeromq" if build.with? "libevent"
```
lol

**Comment by DomT4** [comment]
😆 Lord our dependency system needs a rewrite. Any volunteers? 🙈

**Comment by ilovezfs** [comment]
@DomT4 I'm tempted to just start using the workaround with the hope that the workaround  itself annoys *somone else* enough to do something about it. In the meantime, things would actually work!

**Comment by DomT4** [comment]
I think the team should draw lots, and whichever maintainer gets the shortest straw has to come back with a whole new dependency system within a couple months :trollface:.

**Comment by ilovezfs** [comment]
New dependency system: all options die.

**Pull request closed without merging**
