### PR TITLE
util-linux: build column

### PR DESCRIPTION
**Pull request by progmem**
The original `util-linux` package source made an update around 2017 that included [changes to how the `column` utility functions internally](https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/commit/?id=4762ae9d60f772d40bb2664170045447f7e4ff3a). Prior to these changes, `column` had a defined `MAX_LINE_LEN` that prevented its use with files with longer-than-expected line lengths. This was actually brought up by someone in 2014 with regards to Debian, where they [arbitrarily bumped up the size per line to 1MB](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737348). 

Even with an updated macOS the line limitation is still at the original POSIX limitation of 2048 characters. By building an updated `column` binary, this allows users access to the command without these limitations.

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by progmem** [comment]
It looks like the Catalina build is failing. Reading up on this it looks like the test fails since the `/usr` folder is no longer owned by the `wheel` group, but by `admin`.

I've added another commit that checks if the group is `wheel` first (pre-Catalina); on the raised assertion it'll perform a second check for `admin`. This is the first time I've made contributions to a Homebrew formula, so if there's a more elegant way to pick up on the version of macOS then please let me know.

**Comment by SMillerDev** [comment]
Can you squash your commits into a single one?

**Comment by progmem** [comment]
> Can you squash your commits into a single one?

Sorted!

**Pull request closed without merging**
