### PR TITLE
Cake 0.16.0

### PR DESCRIPTION
**Pull request by patriksvensson**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by patriksvensson** [comment]
As per previous PR's for Cake, we are not in a position to run the final two steps. Please let us know if this causes a problem.

**Comment by zmwangx** [comment]
Merged as d6dfe01. Thank you for your contribution to Homebrew! For future reference, our preferred format of commit subject is `foo 1.2.3` (note the lowercase).

**Comment by patriksvensson** [comment]
@zmwangx Ah, our release process documentation had `Cake` uppercase.
I will change this to specify that it should be lowercase.

Thanks!

**Comment by zmwangx** [comment]
Cool.

**Pull request merged**
