### PR TITLE
rswift 2.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@tomasharkema any idea what the problem is?

**Comment by tomasharkema** [comment]
Ah i see there is a build error. 

@mac-cain13:
```
/tmp/rswift-20160626-16716-885yj3/R.swift/input.swift:147:101: error: cannot force unwrap value of non-optional type 'NSURL'
        self.outputURL = outputURL.URLByAppendingPathComponent(ResourceFilename, isDirectory: false)!
```

**Comment by ilovezfs** [comment]
@tomasharkema yeah, reproduces locally outside of brew using xcodebuild from CLI too, so I was surprised :)

**Comment by mac-cain13** [comment]
Are you using Xcode 8 to compile the project? It is Swift 2.3 so Xcode 7 won't work anymore.

**Comment by ilovezfs** [comment]
Xcode 7, so that explains it. Our CI isn't equipped with Xcode 8 yet, since Xcode 8 hasn't actually shipped yet.

**Comment by DomT4** [comment]
It'll be literal months until Xcode 8 is stable. That's quite some wait we'll have here 😕.

**Comment by mac-cain13** [comment]
It's not that it's impossible to build something with a beta. The Swift 2.3 compiler in Xcode 8 only has minor changes to adjust to the updated SDKs, so give it a shot. :)

**Comment by ilovezfs** [comment]
I think for software distributed by Homebrew under the banner of the stable spec, that would be pretty unorthodox, and I suspect @MikeMcQuaid would not be on board with that.

But entertaining heterodoxy for a moment, it might be interesting to see how things go with the El Capitan CI running Xcode 8. I doubt the underlying LLVM toolchain is that different from the one in Xcode 7, and it may help weed out El Capitan plus 10.12 SDK/Xcode 8 bugs sooner rather than later, as well as start to indirectly catch some of the nascent Sierra bugs.

That said, I'm estimating the probability of that happening at about 1.7%.

**Comment by DomT4** [comment]
Yeah, we're not actively blocking this from being built against Xcode 8. For example if I fire up the Sierra VM I have & try to build this PR I'm sure it'll be fine.

My concern was just that we can't assume _(or demand, really)_ users run a beta Xcode to build a formula inside Homebrew, so we'll probably have to sit on this until Xcode 8 blossoms into a stable release. Agree this PR should be kept open though, we can reference it if others submit similar `rswift` version updates we can't adopt yet.

**Comment by ilovezfs** [comment]
If a maintainer verifies it builds with Xcode 8, I wonder if we should just ship it sans bottles with a ` depends_on :xcode => "8.0"` requirement.

**Comment by DomT4** [comment]
We could do that for a `head` IMO, but I'd be uncomfortable making a stable formula unavailable to users for another 3+ months.

**Comment by ilovezfs** [comment]
@DomT4 Should we relocate to the devel-only tap temporarily, since there is indeed a tag?

**Comment by ilovezfs** [comment]
Or I guess it could be kept here with 2.3.0 in the stable spec, if @mac-cain13 is OK with 2.3.0 being what users get by default, as opposed to being shepherded over to devel-only with 2.4.0 being the only one available.

**Comment by tomasharkema** [comment]
Hi guys, thanks for the effort to get a new version of Rswift in homebrew.

Using 2.3.0 is fine, the only change between 2.3.0 en 2.4.0 is that the source is updated for swift 2.3, so no features are missing in 2.3.0. 

2.4.0 in a separate formula wouldn't make any sense, since there is no real difference in the final binary and in using rswift in xcode.

**Comment by ilovezfs** [comment]
Thanks @tomasharkema Let's close this for now, and re-raise the issue when there's a change that merits a `:head` and/or `:devel` spec.

**Comment by MikeMcQuaid** [comment]
Longer term it may be worth investigating if e.g. the `swift` formula can be used for such things.

**Pull request closed without merging**
