### PR TITLE
flow 0.44.1

### PR DESCRIPTION
**Pull request by gabelevi**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by gabelevi** [comment]
Oh wow, `brew bump-formula-pr` is awesome!

**Comment by ilovezfs** [comment]
>Created with brew bump-formula-pr.

Yay!

**Comment by ilovezfs** [comment]
>Oh wow, brew bump-formula-pr is awesome!

Glad you like it!

**Comment by ilovezfs** [comment]
@gabelevi shipped! Thanks for the upgrade and the PR.

**Pull request closed without merging**
