### PR TITLE
sqlsmith: bump revision

### PR DESCRIPTION
**Pull request by iMichka**
Fixes (on Linux):
sqlsmith: sqlite.cc:64: sqlite_connection::sqlite_connection(std::string&): Assertion `sqlite3_libversion_number()==SQLITE_VERSION_NUMBER' failed.

Seen in #154691

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
@chenrui333 we skip recursive deps for `sqlite`, and I think this might not be a good idea:
https://github.com/Homebrew/homebrew-core/pull/155161
https://github.com/Homebrew/homebrew-core/pull/141987

But I guess that testing whole tree takes ages, and this is why we are doing it?

**Comment by Bo98** [comment]
This is an immediate dependent rather than a recursive one so it should still be tested even with `CI-skip-recursive-dependents`.

The last CI run did catch the regression (https://github.com/Homebrew/homebrew-core/pull/153035), but it was ignored and the follow up never happened.

**Review by Bo98 — APPROVED** [review]

**Comment by Bo98** [comment]
If revision bumping gets too much, we could also pass `-DNDEBUG` to disable the checks.

**Comment by iMichka** [comment]
> This is an immediate dependent rather than a recursive one so it should still be tested even with `CI-skip-recursive-dependents`.
> 
> The last CI run did catch the regression (#153035), but it was ignored and the follow up never happened.

All good, I see. Thanks!

**Comment by chenrui333** [comment]
> The last CI run did catch the regression (#153035), but it was ignored and the follow up never happened.

my bad, I thought I have run the linux regression tests.

**Comment by chenrui333** [comment]
it might be just because so many `CI-linux-self-hosted `, I would think it would be caught out, just like like these two PRs.

**Pull request merged**
