### PR TITLE
ghc@8.6: fix `python3` reference.

### PR DESCRIPTION
**Pull request by miles170**
See #108008.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by miles170** [comment]
`/tmp/ghcA8.6-20220912-7114-bef8i8/ghc-8.6.5/binary/lib/ghc-8.6.5/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

Should we add
```ruby
on_linux do
    depends_on "ncurses"
end
```

**Comment by miles170** [comment]
`/tmp/ghcA8.6-20220912-7114-bef8i8/ghc-8.6.5/binary/lib/ghc-8.6.5/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

which requires Ubuntu to install libncurses5.

**Comment by miles170** [comment]
I think the CI failure may be related to the problem encountered at #110086.

**Comment by cho-m** [comment]
Should be similar problem with Linux bootstrap binary linkage to system libraries. Will need to find a binary that links to `ncurses` v6 since v5 is neither available in Ubuntu 22.04 container nor in Homebrew.

**Comment by miles170** [comment]
> Should be similar problem with Linux bootstrap binary linkage to system libraries. Will need to find a binary that links to `ncurses` v6 since v5 is neither available in Ubuntu 22.04 container nor in Homebrew.

I saw your [comment](https://github.com/Homebrew/homebrew-core/pull/110086#issuecomment-1241585340) which points out that switching to Debian 10 fixes the issue. But [ghc@8.6](https://downloads.haskell.org/ghc/8.6.5/) latest distro is Debian 9, which still uses libtinfo.so.5. Is there another way to fix this issue?

**Comment by cho-m** [comment]
Most binaries are built on too old systems to work.

The Fedora binary might work, which is what `ghcup` uses for Ubuntu 19+

https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-fedora27-linux.tar.xz

**Comment by danielnachun** [comment]
Linux is working now but this needs `long build` to finish on Intel macOS.

**Review by danielnachun — APPROVED** [review]

**Pull request closed without merging**
