### PR TITLE
bazelisk 1.3.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by reitermarkus** [comment]
@chenrui333, killing this build since it got stuck again.

**Comment by chenrui333** [comment]
What is the root cause for "build stuck"?

**Comment by reitermarkus** [comment]
It's the `bazel` command. I tried changing the formula to just use their build script 

```ruby
system "./build.sh"
```

and it works since it downloads a different `bazel` than the `bazel` formula.

**Comment by chenrui333** [comment]
Thanks @bayandin!

**Comment by bayandin** [comment]
No problem @chenrui333 🙂

I've managed to get it built (at least locally) by adopting changes from https://github.com/bazelbuild/bazelisk/commit/05f5542148fb747c24273ed9f40fa718ac5b57d5

**Comment by chenrui333** [comment]
Cool, cool!

**Pull request closed without merging**
