### PR TITLE
cyral-gimme-db-token: remove formula

### PR DESCRIPTION
**Pull request by chenrui333**
There is no open source license in the source tarball file and there is no open source repository for the project either.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
This has had zero installs since Homebrew 4.0.0. I would perhaps even suggest outright deletion that our [removal guidelines](https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#removal) suggests doing for cases like this (non-open-source), but I'd like to hear if anyone else agrees or disagrees @Homebrew/core.

**Comment by p-linnane** [comment]
I am on board with immediate removal.

**Comment by chenrui333** [comment]
yeah, I am ok with just removing it.

**Comment by alebcay** [comment]
It may be worth notifying the folks at Cyral about this removal, since a `brew install cyral-gimme-db-token` command is documented at https://cyral.com/docs/connect/repo-connect/#cli-token-retriever-for-sso.

Alternatively, if this is their tool, maybe they can clarify on the licensing terms.

**Comment by carlocab** [comment]
Yes, let's double check with upstream regarding licensing terms first please. If they don't respond or don't provide an open source license then we can remove this.

**Comment by chenrui333** [comment]
> It may be worth notifying the folks at Cyral about this removal, since a `brew install cyral-gimme-db-token` command is documented at https://cyral.com/docs/connect/repo-connect/#cli-token-retriever-for-sso.

This PR is linked into the original PR, so ideally they should be already aware.

**Comment by chenrui333** [comment]
> Yes, let's double check with upstream regarding licensing terms first please. If they don't respond or don't provide an open source license then we can remove this.

there is no way to report the issue, I doubt it they even have any open source community.

**Comment by chenrui333** [comment]
@antoniomrfranco @ewall tag you both for this issue.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Repeating https://github.com/Homebrew/homebrew-core/pull/85729#discussion_r1233972136

Hold off removal please, @antoniomrfranco, at least at the time, was employed by `cyral.com` so may be able to provide more information for us here.

In general if we want to ask people to verify such things: let's:
- @mention them so they are most likely to receive the message rather than assuming they are still watching >2 year old PRs
- assume good intent, my reading of the PR is that this is probably licensed correctly, there's just no real way of us verifying
- give people 1-2 weeks (in case they are e.g. on vacation) to respond

**Comment by MikeMcQuaid** [comment]
> @antoniomrfranco @ewall tag you both for this issue.

Saw this after! Apologies @chenrui, this is exactly what I was hoping for re: @mentioning, thanks for this 🙇🏻

**Review by MikeMcQuaid — APPROVED** [review]
Fine with me.

**Review by fxcoudert — APPROVED** [review]

**Comment by chenrui333** [comment]
🚀

**Review by iMichka — APPROVED** [review]

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
