### PR TITLE
socat 1.7.4.2

### PR DESCRIPTION
**Pull request by nwtgck**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by glguy** [comment]
In my attempts to build socat 1.7.4.2 manually I've found that this version introduces a mistake in `filan.c` where `struct tcp_info` and `TCP_INFO` are used without the correct guards. Completing the build required me to manually edit the source files. It was not sufficient to attempt to configure with `--disable-filan`.

On the other hand this version is very useful as it fixes a bug in the `OPENSSL-LISTEN` functionality on macOS.

**Comment by nwtgck** [comment]
@glguy 

Thank you so much for the information!

> On the other hand this version is very useful as it fixes a bug in the OPENSSL-LISTEN functionality on macOS.

Actually, I reported a bug to the author by email and the author fixed, so I'd like to use the patched version.

**Comment by dest-unreach** [comment]
> In my attempts to build socat 1.7.4.2 manually I've found that this version introduces a mistake in `filan.c` where `struct tcp_info` and `TCP_INFO` are used without the correct guards. Completing the build required me to manually edit the source files. It was not sufficient to attempt to configure with `--disable-filan`.

Hello, please provide the error messages when trying to build original socat 1.7.4.2, and the changes you needed to fix it!

**Comment by nwtgck** [comment]
@dest-unreach 

I `make` and get errors on macOS. I hope it would be helpful.

```
... ( elided ) ...
filan.c:767:14: warning: unused variable 'optlen' [-Wunused-variable]
   socklen_t optlen = sizeof(optproto);
             ^
filan.c:908:20: error: variable has incomplete type 'struct tcp_info'
   struct tcp_info tcpinfo;
                   ^
filan.c:908:11: note: forward declaration of 'struct tcp_info'
   struct tcp_info tcpinfo;
          ^
filan.c:912:37: error: use of undeclared identifier 'TCP_INFO'
   result = Getsockopt(fd, SOL_TCP, TCP_INFO, &tcpinfo, &tcpinfolen);
                                    ^
4 warnings and 2 errors generated.
make: *** [filan.o] Error 1
```

**Comment by nwtgck** [comment]
@dest-unreach 

GitHub Actions provides free macOS enviroment for public repository. So I made a continuous integration (CI) setting.  The following link is the CI setting diff.

CI setting: https://github.com/nwtgck/socat/compare/tag-1.7.4.1..github-actions

The log of the CI shows `./socat` 1.7.4.1. (not 1.7.4.2) was built in the GitHub Actions.
image
log link: <https://github.com/nwtgck/socat/runs/4171892618?check_suite_focus=true>

It might help the great socat development! But, I'm ready to patch and build, so feel free to post me a patch.

**Comment by chenrui333** [comment]
we need some fix like this, varnish/varnish-modules#38

**Comment by dest-unreach** [comment]
Please try this patch!


Am 10.12.21 um 05:33 schrieb rui:

**Comment by iMichka** [comment]
I'm fine with the change, but I would like to know if the patch will be included in the next release. Just to avoid to have to maintain a patch in homebrew forever.

**Comment by nwtgck** [comment]
I agree with the idea. I also hope the patch included in the next release.

@chenrui333 
By the way, how did you push my branch ` nwtgck:bump-socat-1.7.4.2` in the forked repo? Does GitHub allow the members push forked repo?

**Comment by chenrui333** [comment]
> @chenrui333 By the way, how did you push my branch ` nwtgck:bump-socat-1.7.4.2` in the forked repo? Does GitHub allow the members push forked repo?

When you create the PR, you have an option to allow maintainer to forced push the fork.

You can find details in this page, https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by chenrui333** [comment]
I have dropped an email to the owner about how to include this patch into the upstream repo. I did not see it included in `git://repo.or.cz/socat.git` yet.

**Comment by nwtgck** [comment]
@chenrui333 Thank you for the information.

**Comment by dest-unreach** [comment]
Am 30.12.21 um 23:59 schrieb Michka Popoff:
>
> I'm fine with the change, but I would like to know if the patch will
> be included in the next release. Just to avoid to have to maintain a
> patch in homebrew forever.
>
Hello,

yes this patch will be included in the next bug fix release, hopefully
in a few days.

- Gerhard

**Comment by chenrui333** [comment]
@dest-unreach thanks for confirming it. I think we can merge the PR when it is green.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Thanks @dest-unreach and @nwtgck

**Comment by dest-unreach** [comment]
Hello,

Socat version 1.7.4.3 with the TCP_INFO fix has just been released, see
http://www.dest-unreach.org/socat for download and git sites.

- Gerhard


Am 30.12.21 um 23:59 schrieb Michka Popoff:

**Comment by nwtgck** [comment]
Thank you so much for the release!

**Pull request closed without merging**
