### PR TITLE
dnsviz: Remove dependency on libnacl

### PR DESCRIPTION
**Pull request by cdeccio**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Does this remove any functionality? Or is it just an unneeded dependency?

**Comment by bayandin** [comment]
It looks like they have replaced it with cryptography: https://github.com/dnsviz/dnsviz/pull/54, probably we want to do the same.

A bit offtopic, but `brew update-python-resources dnsviz` removes all the resources, don't know why

**Comment by bayandin** [comment]
> It looks like they have replaced it with cryptography: [dnsviz/dnsviz#54](https://github.com/dnsviz/dnsviz/pull/54), probably we want to do the same.
> 
> A bit offtopic, but `brew update-python-resources dnsviz` removes all the resources, don't know why

Sorry I'm wrong, the actually PR is https://github.com/dnsviz/dnsviz/pull/67 — they just removed it

**Comment by dtrodrigues** [comment]
> A bit offtopic, but `brew update-python-resources` dnsviz removes all the resources, don't know why


I believe it's because they use `requires` instead of `install_requires` in their `setup.py`: https://github.com/dnsviz/dnsviz/blob/78a6b658a106841bae41f86af6d79b04cede82c9/setup.py#L136-L140. I ran into this when bumping the formula version so I ended up doing it manually.

**Comment by cdeccio** [comment]
> > A bit offtopic, but `brew update-python-resources` dnsviz removes all the resources, don't know why
> 
> I believe it's because they use `requires` instead of `install_requires` in their `setup.py`: https://github.com/dnsviz/dnsviz/blob/78a6b658a106841bae41f86af6d79b04cede82c9/setup.py#L136-L140. I ran into this when bumping the formula version so I ended up doing it manually.
> 

Should I be doing something differently in `setup.py`?  Maybe I'm out of date?

Also unrelated, an old version of `dnsviz.rb` used to call `setup.py` explicitly; the reason was because it allowed `--install-data` to be specified, which cannot be done with `pip` (as far as I know).  This way, the data files could be put in (for example) `/usr/local/share/dnsviz`.  This was changed in e4e849ba3.  I know it looks cleaner, but the tradeoff is that those files now live in a location specific to the dnsviz install.  Thoughts?

**Comment by Rylan12** [comment]
> > A bit offtopic, but `brew update-python-resources` dnsviz removes all the resources, don't know why
> 
> I believe it's because they use `requires` instead of `install_requires` in their `setup.py`: https://github.com/dnsviz/dnsviz/blob/78a6b658a106841bae41f86af6d79b04cede82c9/setup.py#L136-L140. I ran into this when bumping the formula version so I ended up doing it manually.
> 
> cc @Rylan12

Yeah, that's probably it. I don't know much about setuptools and how the pipgrip dependency resolver works. I don't see `requires` as a valid option in the setuptools documentation, so I think that's probably the issue. Shouldn't this mean that `pip install dnsviz` doesn't install necessary dependencies? If so, it should almost certainly be changed to `install_requires`.

Otherwise, we should add to the auto-update resource blocklist.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
