### PR TITLE
galen 2.4.4

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @julianxhokaxhiu

**Comment by julianxhokaxhiu** [comment]
You're welcome, but it actually wasn't merged. What happened?

**Comment by SMillerDev** [comment]
It is merged in https://github.com/Homebrew/homebrew-core/commit/7bd505a3e83518ba719ac0e4b8b37d6c8c5d4534

**Comment by julianxhokaxhiu** [comment]
Oh sorry, Github has a wrong order for the commit, mine for some unknown reason is the last of the day ( although it is set to 2 hours ago ). Thanks :)

**Pull request closed without merging**
