### PR TITLE
kubevela update install script

### PR DESCRIPTION
**Pull request by sunny0826**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why is this change needed/wanted?

**Comment by sunny0826** [comment]
> Why is this change needed/wanted?

Before installation, a number of configurations need to be injected, without which the `kubevela` will not work. 
I overlooked this and the kubevela installed with brew did not work!

**Comment by SMillerDev** [comment]
Could you also add a test that verifies this then?

**Comment by sunny0826** [comment]
This function is dependent on the k8s cluster and helm,  I'm not sure how to test it in brew.

**Pull request closed without merging**
