### PR TITLE
vim 8.0.0771

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MakeNowJust** [comment]
Since vim 8.0 patch 712, it supports `:terminal`command which can open terminal emulator inside vim like neovim and emacs. I wish `brew install` version vim is enabled this feature and there should be `--with-terminal` option to enable `:terminal` at least.

**Comment by ilovezfs** [comment]
@MakeNowJust https://github.com/Homebrew/homebrew-core/pull/16015

**Comment by ilovezfs** [comment]
@MakeNowJust `brew update && brew upgrade vim` if you want the new feature :)

**Comment by MakeNowJust** [comment]
@ilovezfs Thank you!

**Pull request closed without merging**
