### PR TITLE
sbt 1.0.3

### PR DESCRIPTION
**Pull request by eed3si9n**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Java 9! Yay!

**Comment by ilovezfs** [comment]
@eed3si9n :( seems we're still having a Java 9 hiccup
```
==> brew test sbt --verbose
==> FAILED
Testing sbt
/usr/bin/sandbox-exec -f /tmp/homebrew20171027-78651-wqp736.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sbt.rb --verbose
==> /usr/local/Cellar/sbt/1.0.3/bin/sbt sbtVersion
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Dsbt.log.noformat=true
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Dsbt.log.noformat=true
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Dsbt.log.noformat=true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/usr/local/Cellar/sbt/1.0.3/libexec/bin/sbt-launch.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Error: sbt: failed
<0> expected but was
<1>.
```

**Comment by eed3si9n** [comment]
That's too bad. I think that's https://github.com/sbt/launcher/issues/38, which has been fixed, but fell between the cracks.

**Comment by ilovezfs** [comment]
Thanks for the upgrade, @eed3si9n!

**Pull request merged**
