### PR TITLE
rust: disable stable on 10.12

### PR DESCRIPTION
**Pull request by zmwangx**
See #4960 for an example of an unfortunate soul who wasted 4-5 valuable
hours in his life just because we let him.

@ilovezfs I'd love to have your thoughts.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by ilovezfs** [comment]
@zmwangx did you check if the rust elcap bottles work on sierra?

**Comment by zmwangx** [comment]
@ilovezfs No.

**Comment by ilovezfs** [comment]
```
==> Installing rust
==> Downloading https://homebrew.bintray.com/bottles/rust-1.11.0.sierra.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/rust-1.11.0.sierra.bottle.tar.gz
==> Pouring rust-1.11.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/rust/1.11.0: 12,344 files, 255.3M
Josephs-Mac:Homebrew joe$ brew test -v rust
git config --file=/usr/local/Homebrew/.git/config --replace-all homebrew.devcmdrun true
Testing rust
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160919-77522-31z3vm.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rust.rb -v
==> /usr/local/Cellar/rust/1.11.0/bin/rustdoc -h
/usr/local/Cellar/rust/1.11.0/bin/rustdoc [options] <input>

Options:
    -h --help           show this help message
    -V --version        print rustdoc's version
    -v --verbose        use verbose output
    -r --input-format [rust]
                        the input type of the specified file
    -w --output-format [html]
                        the output type to write
    -o --output PATH    where to place the output
    --crate-name NAME   specify the name of this crate
    -L --library-path DIR
                        directory to add to crate search path
    --cfg               pass a --cfg to rustc
    --extern NAME=PATH  pass an --extern to rustc
    --plugin-path DIR   directory to load plugins from
    --passes PASSES     list of passes to also run, you might want to pass it
                        multiple times; a value of `list` will print available
                        passes
    --plugins PLUGINS   space separated list of plugins to also load
    --no-defaults       don't run the default passes
    --test              run code examples as tests
    --test-args ARGS    arguments to pass to the test runner
    --target TRIPLE     target triple to document
    --markdown-css FILES
                        CSS files to include via <link> in a rendered Markdown
                        file
    --html-in-header FILES
                        files to include inline in the <head> section of a
                        rendered Markdown file or generated documentation
    --html-before-content FILES
                        files to include inline between <body> and the content
                        of a rendered Markdown file or generated documentation
    --html-after-content FILES
                        files to include inline between the content and
                        </body> of a rendered Markdown file or generated
                        documentation
    --markdown-playground-url URL
                        URL to send code snippets to
    --markdown-no-toc   don't include table of contents
    -e --extend-css PATH
                        to redefine some css rules with a given file to
                        generate doc with your own theme
    -Z FLAG             internal and debugging options (only on nightly build)

==> /usr/local/Cellar/rust/1.11.0/bin/rustc hello.rs
==> /usr/local/Cellar/rust/1.11.0/bin/cargo new hello_world --bin
   Compiling hello_world v0.1.0 (file:///private/tmp/rust-test-20160919-77523-oxocqw/hello_world)
     Running `target/debug/hello_world`
```

So I think I'd prefer to add the el cap bottle as a Sierra bottle and odie in install if someone is trying to source build.

**Comment by zmwangx** [comment]
I'll leave this to someone else

**Pull request closed without merging**
