### PR TITLE
pc6001vx 4.2.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

---

relates to https://github.com/eighttails/PC6001VX/issues/13

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Testing pc6001vx
  Detected locale "C" with character encoding "US-ASCII", which is not UTF-8.
  Qt depends on a UTF-8 locale, and has switched to "UTF-8" instead.
  If this causes problems, reconfigure your locale. See the locale(1) manual
  for more information.
  Error: pc6001vx: failed
  An exception occurred within a child process:
    Minitest::Assertion: User config directory should exist.
  Expected #<Pathname:/private/tmp/pc[60](https://github.com/Homebrew/homebrew-core/actions/runs/6756572079/job/18366204151?pr=153342#step:3:61)01vx-test-20231104-14850-13hpy9o/.pc6001vx4/pc6001vx.ini> to be exist?.
```

**Comment by p-linnane** [comment]
I don't think we should add a macOS dependency here. We can just delete the Linux bottle. That'll make it more clear that it's not a real dependency, just that Linux is not building.

**Review by p-linnane — APPROVED** [review]

**Comment by iMichka** [comment]
Did someone open a upstream issue to get the Linux issue sorted out?

**Comment by chenrui333** [comment]
> Did someone open a upstream issue to get the Linux issue sorted out?

I did, see discussions in here, https://github.com/eighttails/PC6001VX/issues/13

**Comment by chenrui333** [comment]
the linux build is not an easy fix.

**Comment by iMichka** [comment]
Ok for me then

**Review by iMichka — APPROVED** [review]

**Pull request merged**
