### PR TITLE
Fpp 0.9.2

### PR DESCRIPTION
**Pull request by pcottle**
Ran install from source, tested, and audited:

```
> brew install --build-from-source ./Formula/fpp.rb 
> fpp --version
fpp version 0.9.2
>  brew test ./fpp.rb
Testing fpp
==> /usr/local/Cellar/fpp/0.9.2/bin/fpp --help
> brew audit --strict ./fpp.rb
```

### CODE REVIEW

**Review by friederbluemle — APPROVED** [review]
👍

**Comment by pcottle** [comment]
oh no, and there are merge conflicts now :/

**Comment by friederbluemle** [comment]
Hmm, it seems your commit is based on an old parent (fpp 0.7.2), whereas the current master branch has fpp 0.8.2

**Comment by pcottle** [comment]
sorry I'm struggling so much, heres a non-merge-conflict version in:
https://github.com/Homebrew/homebrew-core/pull/43684

**Comment by friederbluemle** [comment]
Thanks!

**Pull request closed without merging**
