### PR TITLE
lftp 4.8.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
```
make[5]: Nothing to be done for `install-data-am'.
Making install in src
/bin/sh ../libtool --silent  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o PollVec.lo PollVec.cc
/bin/sh ../libtool --silent  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o SMTask.lo SMTask.cc
/bin/sh ../libtool --silent  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o ProcWait.lo ProcWait.cc
/bin/sh ../libtool --silent  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o GetPass.lo GetPass.cc
PollVec.cc:33:42: error: non-constant-expression cannot be narrowed from type 'unsigned int' to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
   struct timeval new_timeout={t/1000000,t%1000000};
                                         ^~~~~~~~~
PollVec.cc:33:42: note: insert an explicit cast to silence this issue
   struct timeval new_timeout={t/1000000,t%1000000};
                                         ^~~~~~~~~
                                         static_cast<__darwin_suseconds_t>( )
1 error generated.
make[2]: *** [PollVec.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Upstream commit that fixes it: https://github.com/lavv17/lftp/commit/ee60a0f71fde2de9d124ef287034d4d170544b17

**Pull request closed without merging**
