### PR TITLE
expect 5.45.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
```
Error: SHA256 mismatch
Expected: d082bf340fdb7a85b1e4e5df4d967d0140835db34a8a035c3102abb5eb62d450
Actual: 49a7da83b0bdd9f46d04a04deec19c7767bb9a323e40c4781f89caf760b92c34
Archive: /home/linuxbrew/.cache/Homebrew/expect-5.45.4.tar.gz
To retry an incomplete download, remove the file above.
```

https://github.com/Linuxbrew/homebrew-core/pull/5956

**Comment by iMichka** [comment]
Do you know who is the developer or who I can contact here? Their webpage is not really clear about that ...

**Comment by RandomDSdevel** [comment]
I'm seeing certificate errors when trying to download this new Expect version:  

```
$ brew fetch -vd --force --retry --build-from-source expect
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/expect.rb
==> Downloading https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
/usr/local/opt/curl/bin/curl --show-error --user-agent Homebrew/1.5.3 (Macintosh; Intel Mac OS X 10.11.6) curl/7.58.0 --fail --location --remote-time --continue-at - --output /Users/zadmin/Library/Caches/Homebrew/expect-5.45.4.tar.gz.incomplete https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> Retrying download
==> Downloading https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
/usr/local/opt/curl/bin/curl --show-error --user-agent Homebrew/1.5.3 (Macintosh; Intel Mac OS X 10.11.6) curl/7.58.0 --fail --location --remote-time --continue-at - --output /Users/zadmin/Library/Caches/Homebrew/expect-5.45.4.tar.gz.incomplete https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Failed to download resource "expect"
Download failed: https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:329:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:326:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:137:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1603:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:124:in `fetch_fetchable'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:93:in `fetch_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:65:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:45:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:45:in `fetch'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

As noted by my `brew config`…:  

```
$ brew config
HOMEBREW_VERSION: 1.5.3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: af8f8f11e32fe78677fc1d4cd62c07a29dc6d326
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 83f665fe3cefb8adeb0c447343d813eb30eea579
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications --prefpanedir=/Library/PreferencePanes --colorpickerdir=/Library/ColorPickers --dictionarydir=/Library/Dictionaries --servicedir=/Library/Services --qlplugindir=/Library/QuickLook --fontdir=/Library/Fonts --input_methoddir=/Library/Input\ Methods --screen_saverdir=/Library/Screen\ Savers --internet_plugindir=/Library/Internet\ Plug\-Ins
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_FORCE_BREWED_CURL: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_UPDATE_TO_TAG: 1
CPU: dual-core 64-bit core2
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.58.0 => /usr/local/opt/curl/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
Java: 9.0.4
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

…I'm on the macOS version of Homebrew, not Linuxbrew.

**Comment by DomT4** [comment]
```
Downloaded to: /usr/local/var/homebrewcache/expect-5.45.4.tar.gz
SHA256: 49a7da83b0bdd9f46d04a04deec19c7767bb9a323e40c4781f89caf760b92c34
==> Verifying expect-5.45.4.tar.gz checksum
Warning: Formula reports different SHA256: d082bf340fdb7a85b1e4e5df4d967d0140835db34a8a035c3102abb5eb62d450

file /usr/local/var/homebrewcache/expect-5.45.4.tar.gz
gzip compressed data, last modified: Sun Feb  4 13:55:43 2018, from Unix
```
Can repro.

**Comment by DomT4** [comment]
Potentially a speedy retag. Someone should ask upstream.

**Comment by RandomDSdevel** [comment]
@DomT4:  Just started poking around IRC.

**Comment by RandomDSdevel** [comment]
Here's what went down there:  

```
[14:49] == RandomDSdevel [4432b1dc@gateway/web/freenode/ip.68.50.177.220] has joined #tcl
[14:49] -ChanServ- [#tcl] This channel is bridged to a Jabber chat via ijchain. ijchain is a bot. Set your IRC client for UTF-8 encoding in this channel.
[14:50] <RandomDSdevel> ?:  https://github.com/Homebrew/homebrew-core/pull/23665#issuecomment-363697185
[14:51] <RandomDSdevel> (Unless there's an Expect-specific IRC channel, of course.)  
[14:54] <RandomDSdevel> I should probably repeat what's on the other end of that link here:  Expect v5.45.4's `.tar.gz` checksum and host download site certificate are wrong.  
[14:54] <RandomDSdevel> (Thus preventing downloads and/or verification of them, obviously.)  
[14:56] * ijchain tomk has become available
[14:56] <@ijchain> <aku> RandomDSDevel - Are you subscribed to the tcl-core mailing list ?
[14:57] <RandomDSdevel> No, should I report this there?  
[14:57] <@ijchain> <tomk> ~~~
[14:57] <@ijchain> <aku> I saw the announcement of E 5.45.4 on that list - You might wish to report the problem there too.
[14:57] <@ijchain> <aku> The download site, is that SForge ?
[14:57] <rkeene> aku, Expect work progressings ?
[14:58] <RandomDSdevel> Is that outdated, aku?  
[14:59] <@ijchain> <aku> rkeene - Nils announced 5.45.4 on tcl-core yesterday or so.
[14:59] <@ijchain> <teo> RandomDSdevel: expect 5.45.4 has been released twice: by february 2 and 4. the first release misses a part of the changelog
[14:59] <@ijchain> <aku> outdated ? Now I just want to know `what` the download site is, as you did not say.
[14:59] <@ijchain> <aku> I have now confirmed that it is SF
[14:59] <@ijchain> <aku> poer the github issue.
[14:59] <@ijchain> <aku> A bad cert is an SF issue.
[15:00] <@ijchain> <aku> A bad checksum might be a problem on Nils side.
[15:00] <RandomDSdevel> Hmm, that doesn't bode well for SourceForge, now, does it?  
[15:00] <@ijchain> <aku> I.e. you have two problems, with different people/orgs responsible for fixing.
[15:00] * RandomDSdevel nods.  
[15:01] <RandomDSdevel> I mean, OK.  
[15:01] <@ijchain> <aku> You could try to download using http:// instead of https:// see if that gives you something with correct checksum
[15:01] <RandomDSdevel> That'd probably fail Homebrew's `brew audit` checks, but I could try manually outside of the package manager.  
[15:01] <@ijchain> <aku> i.e. if the download failed due bad cert, but left a file behind then that file likely is empty, or incopete and soc could not match the checksum
[15:01] <RandomDSdevel> (The first if I changed the download strategy by making a formula edit that is.)  
[15:01] <@ijchain> <aku> in that case the 2nd problem would be a consequence of the first.
[15:02] * RandomDSdevel ponders for a moment…
[15:03] <RandomDSdevel> I'll see if downloading manually without SSL/TLS gives me any similar errors.  Hang on for a bit…
[15:04] == You have been marked as being away
[15:06] == You are no longer marked as being away
[15:07] <RandomDSdevel> OK, the file I get from doing that is only 618 KB.  
[15:07] <RandomDSdevel> I'd have to check to see if that's the right size.  
[15:09] <@ijchain> <jima> .
[15:14] <nuclightq> schelte: what's his nickname? probably tutorial should explicitly say from doc "Since the pattern arguments are in braces in the second form, no command or variable substitutions are performed on them; this makes the behavior of the second form different than the first form in some cases. "
[15:14] <@ijchain> <schelte> arjen
[15:15] <RandomDSdevel> Hmm, should I sandbox decompressing that?  OS X/macOS `sandboxd`/`sandbox-exec` seem a little too heavy-handed to start going through now.  I hope the checksum goof is just because this 'Nils' person you mentioned as an Expect maintainer forgot to update it when they re-tagged the release, so hopefully the difference is benign enough that I don't have to bother.  
[15:15] <@ijchain> <aku> file size - https://sourceforge.net/projects/expect/files/Expect/5.45.4/ tells me 623 K
[15:15] <@ijchain> <aku> tyop 632K
[15:15] <RandomDSdevel> Could that just be the difference between KB and KiB?  
[15:16] <@ijchain> <aku> Maybe? I don't know if SF uses KB or KiB
[15:16] <RandomDSdevel> Yeah, I'm not sure how to make `ls` say either.  
[15:19] * ijchain tpoindex has left
[15:21] <RandomDSdevel> Well, I get the contents I'd expect if I decompress.  
[15:23] <@ijchain> <aku> I will try to make time this evening to do my own download and checking ...
[15:24] <RandomDSdevel> 'Kay.  In the meantime, I'll report this to the mailing list and copy what discussion happened here to the relevant downstream Homebrew PR thread.  
```

**Comment by RandomDSdevel** [comment]
I've notified [tcl-core mailing list](https://sourceforge.net/p/tcl/mailman/tcl-core/) of this.

**Comment by andreas-kupries** [comment]
Hi. `aku` here.

I just tried
```
wget https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256 https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
```
and the resulting files check out ok, i.e.
```
hephaistos:(539) ~/Downloads/x > ll
total 624
-rw-r--r-- 1 aku aku 632363 Feb  4 05:56 expect5.45.4.tar.gz
-rw-r--r-- 1 aku aku     86 Feb  4 05:56 expect5.45.4.tar.gz.SHA256
hephaistos:(540) ~/Downloads/x > sha256sum -c expect5.45.4.tar.gz.SHA256 
expect5.45.4.tar.gz: OK
hephaistos:(541) ~/Downloads/x > cat expect5.45.4.tar.gz.SHA256 
49a7da83b0bdd9f46d04a04deec19c7767bb9a323e40c4781f89caf760b92c34  expect5.45.4.tar.gz
```

Note my use of `wget` instead of `curl`.

Trying the same with `curl`, and using `-k` to ignore any cert issues I see

```
hephaistos:(547) ~/Downloads/y > for p in https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256 https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz ; do curl -k $p > $(basename $p) ; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   359  100   359    0     0    708      0 --:--:-- --:--:-- --:--:--   709
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   349  100   349    0     0    579      0 --:--:-- --:--:-- --:--:--   579
hephaistos:(548) ~/Downloads/y > sha256sum -c expect5.45.4.tar.gz.SHA256 
sha256sum: expect5.45.4.tar.gz.SHA256: no properly formatted SHA256 checksum lines found
hephaistos:(549) ~/Downloads/y > ll
total 8
-rw-r--r-- 1 aku aku 349 Feb  7 21:36 expect5.45.4.tar.gz
-rw-r--r-- 1 aku aku 359 Feb  7 21:36 expect5.45.4.tar.gz.SHA256
hephaistos:(550) ~/Downloads/y > cat expect5.45.4.tar.gz.SHA256
<html>
 <head>
  <title>302 Found</title>
 </head>
 <body>
  <h1>302 Found</h1>
  The resource was found at <a href="https://ayera.dl.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256">https://ayera.dl.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256</a>;
you should be redirected automatically.


 </body>
```

So, `curl` does not seem to follow SF's redirection to the actual download mirror site.
Whereas `wget` does.
Checking back in the terminal, confirmed:

```

wget https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256 https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
--2018-02-07 21:31:38--  https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://iweb.dl.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256 [following]
--2018-02-07 21:31:39--  https://iweb.dl.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256
Resolving iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)... 192.175.120.182, 2607:f748:10:12::5f:2
Connecting to iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)|192.175.120.182|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 86 [application/octet-stream]
Saving to: ‘expect5.45.4.tar.gz.SHA256’

...
```

**Comment by ilovezfs** [comment]
`-L`

**Comment by andreas-kupries** [comment]
Thanks. Adding that option `curl` is fine too. I.e. it retrieves the files ok and the checksums checks out ok as well.

```
for p in https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz.SHA256 https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz ; do curl -k -L $p > $(basename $p) ; done ; ll ;sha256sum -c expect5.45.4.tar.gz.SHA256 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   365    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    86  100    86    0     0     92      0 --:--:-- --:--:-- --:--:--   272
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   359    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  617k  100  617k    0     0   402k      0  0:00:01  0:00:01 --:--:--  744k
total 624
-rw-r--r-- 1 aku aku 632363 Feb  7 23:02 expect5.45.4.tar.gz
-rw-r--r-- 1 aku aku     86 Feb  7 23:02 expect5.45.4.tar.gz.SHA256
expect5.45.4.tar.gz: OK
```

**Comment by andreas-kupries** [comment]
I can only report on the current state.
That current state is that for me the SHA file file contains `49a7...`,
and that the local `sha256sum` reports that the tarball has that same checksum `49a7...`.

If I understand you correctly you are saying that for some time the tarball had checksum `d082`
and that this older checksum is stored in your build system (recipe?).

What is it what you are now asking for the Expect maintainer should do ?

**Comment by RandomDSdevel** [comment]
@ilovezfs:  For the record, I was still seeing SourceForge certificate errors even when running cURL outside Homebrew with the `-L` option, so there's still that to finish troubleshooting.  Given [@DomT4's earlier guess](https://github.com/Homebrew/homebrew-core/pull/23665#issuecomment-363697185) and what @andreas-kupries is saying, though, we can solve the checksum issue with a quick PR to adjust the relevant line in Homebrew's Expect formula (I can file one if nobody gets to it first&thinsp;—&thinsp;would that require a formula revision bump, though?)

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Hold on, I'm not seeing certificate problems outside of Homebrew anymore; let's see what happens when I do a local build to test my checksum-fixing PR…

**Comment by RandomDSdevel** [comment]
Still getting that same error from within Homebrew when I try to run a test build.  Maybe it's something to do with my local machine…?  (_Starts digging…_)

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Do you know of any way I could make Homebrew pass arbitrary options to cURL when the former runs the latter to fetch a package tarball?  My last two comments here still hold true, head-scratchingly enough…

**Comment by RandomDSdevel** [comment]
Wait…could my problem here be related to Homebrew's `ENV` sanitization…?  (_Checks to see if setting `HOMEBREW_NO_ENV_FILTERING=1` helps any…)

**Comment by RandomDSdevel** [comment]
OK, I've almost got a PR-staging branch ready to push to my fork of Homebrew Core, but I can't get `brew audit` to pass locally.  Here's what I see:  

```
$ brew audit -vd --strict expect
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/expect.rb
Error: The 'rubocop' gem is installed but couldn't find 'rubocop' in the PATH:
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `odie'
/usr/local/Homebrew/Library/Homebrew/utils.rb:234:in `install_gem_setup_path!'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:73:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:67:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:103:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

(FYI, this happened both before and after setting `HOMEBREW_FORCE_BREWED_CURL` back to `1`, which is what I have it at by default.)

**Comment by RandomDSdevel** [comment]
Yup, that was it.  Just a moment more, and then I'll have pushed and submitted my PR for this.

**Comment by RandomDSdevel** [comment]
One last note:  I got this from `brew audit --strict`…:  

```
expect:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
Error: 1 problem in 1 formula
```

…but I think I can ignore this since it's already been confirmed that the `sha256` change in question is kosher upstream.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I saw more certificate errors similar to the ones I [mentioned earlier in this thread](https://github.com/Homebrew/homebrew-core/pull/23665#issuecomment-363619563) crop up again when trying to upgrade a different package hosted on SourceForge under my default configuration; the same fix I mentioned before (w. r. t. `HOMEBREW_FORCE_BREWED_CURL`) worked around them, but they still make me a bit nervous.  Given that I've seen said errors appear in relation to multiple formulas now, I should probably file a new issue about this, correct?  (_Wanders off to do that…_)

**Pull request closed without merging**
