### PR TITLE
wandio 4.2.5 libtrace 4.0.22

### PR DESCRIPTION
**Pull request by carlocab**
See #134251.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks @nandahkrishna!

**Comment by nandahkrishna** [comment]
Updated `wandio` to `4.2.5` and `libtrace` to `4.0.22` along with the `openssl@3` switch.

### Note on `livecheck` and `version`

Both formulae seem to have tags with a `-1` suffix, but upstream seems to ignore this from the version (see: [`wandio` releases page](https://github.com/LibtraceTeam/wandio/releases) and [Repology](https://repology.org/project/wandio/versions), [`libtrace` releases page](https://github.com/LibtraceTeam/libtrace/releases) and [Repology](https://repology.org/project/libtrace/versions)).

I've updated the `livecheck` blocks such that the `-1` suffix is ignored (but `-2` and higher are not). I've also added a `version` in line with this change.

CC @samford for feedback, but we can also revisit this later.

**Comment by nandahkrishna** [comment]
Hm, no `openssl@3` linkage on Linux:
```
==> brew linkage --cached libtrace
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libstdc++.so.6
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/opt/libpcap/lib/libpcap.so.1 (libpcap)
  /home/linuxbrew/.linuxbrew/Cellar/libtrace/4.0.22/lib/libpacketdump.so.5 (libtrace)
  /home/linuxbrew/.linuxbrew/Cellar/libtrace/4.0.22/lib/libtrace.so.7 (libtrace)
  /home/linuxbrew/.linuxbrew/opt/ncurses/lib/libncursesw.so.6 (ncurses)
  /home/linuxbrew/.linuxbrew/opt/wandio/lib/libwandio.so.6 (wandio)
Indirect dependencies with linkage:
  ncurses
```
All macOS version seem to have linkage though.

**Comment by carlocab** [comment]
Seems fine to merge. Will pull in OpenSSL via `uses_from_macos "curl"` in `wandio` anyway.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
