### PR TITLE
open-scene-graph 3.5.5

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
It seems the Qt 5 version now has its own separate repository https://github.com/openscenegraph/osgQt CC @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
Think it's fine to merge this as-is 👍

**Comment by MikeMcQuaid** [comment]
What happens if you use the `--with-qt5` option now? :boom: or just does nothing?

**Comment by ilovezfs** [comment]
Does nothing. The Qt 5 version is now https://github.com/openscenegraph/osgQt

**Comment by MikeMcQuaid** [comment]
Separate repo probably warrants a separate formula.

**Comment by davenquinn** [comment]
So does somebody need to create an `open-scene-graph-qt5` formula, then? I'm not sure exactly how these were split apart or what would need to happen to recombine, but I might be game to try to publish something unless someone is already working on this...

**Comment by MikeMcQuaid** [comment]
> open-scene-graph-qt5 formula, then

Probably `open-scene-graph-qt` but: yes. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Pull request closed without merging**
