### PR TITLE
new formula torxakis

### PR DESCRIPTION
**Pull request by harcokuppens**
torxakis 0.9.0 (new formula)
We supply our own tap https://github.com/TorXakis/homebrew-TorXakis but want to use the brew bot to build the bottles. It doesn't need to be put in homebrew-core. If there is another way to build to build the bottles using the brew-bot we would like to hear.

### CODE REVIEW

**Comment by harcokuppens** [comment]
got the bottles from jenkins, 
thanks for using the brew bot

**Comment by SMillerDev** [comment]
https://github.com/brewsci/homebrew-bio has bottles, you can look there for reference. Please don't abuse our CI for your own tap.

**Comment by harcokuppens** [comment]
I only see information there how to install  from the "bio" tap.

Could you please  give me more information how they build bottles for the different versions of macos, because I only have 1 mac version.

**Comment by SMillerDev** [comment]
On that case you'll have to get someone to provide other versions for you. Macstadium very graciously sponsors ours. You could look into that.

**Comment by MikeMcQuaid** [comment]
Agreed with @smillerdev. While you can technically use our CI in this manner it's a bit rude to do so.

**Comment by harcokuppens** [comment]
Originally I wanted our package in homebrew/core but on first build on the brew bot, it was refused because it was not popular enough. But the bottles where build and I put them on our own tap. Because I didn't know how to build the bottles for other macs, so  I thought if would retry with above message it would be ok, and never got any complaints about it..until today.
I thought it would be ok to build bottles that way, so that even though on another tap, installing with homebrew would be as convenient as possible. 

Sorry for my rudeness, my apologies.

I won't use this approach anymore, and  are going only to build a bottle for my own mac version, and not supporting other mac versions anymore. People with a not supported mac version have to build from source then. Takes a while but does work. Having bottles was very nice!

I looked into Macstadium, but buying a licence only for a build each half a year is too much. 

The only solution seems to have you mac boot multiple versions of macos, which is probably a lot of work, I don't want to do.

Hope there will be a solution for tap owners with not so popular software to build bottles for the most recent macos versions.

Best regards,
Harco Kuppens

**Comment by MikeMcQuaid** [comment]
> Sorry for my rudeness, my apologies.

No worries, we appreciate the apology ❤️.



> The only solution seems to have you mac boot multiple versions of macos, which is probably a lot of work, I don't want to do.

You could build just on the oldest version of macOS you wish to support and the bottle will be automatically used on all newer versions.

**Comment by harcokuppens** [comment]
> You could build just on the oldest version of macOS you wish to support and the bottle will be automatically` used on all newer versions.

Ok, just tested it, and indeed it works! That is great, because I'm personally not fast in switching to the latest macos version until all problems are solved.  Thus bottles build on my older macos version can just be used on the newer macos versions.

So I can imagine often it will work, but I'm not sure that apple guarantees Forward compatibility of older macos application on a newer macos. If you upgrade to an newer macos it will often work, because you probably still have the older libraries etc installed, but if you buy a new macbook with the newest macos, that an old bottle may not work because an older version of library used there is not available.  

Am I right, or is there somewhere  a technical document of apple which specifies this forward compatibility?
Anyway in most cases it will just work.

**Comment by MikeMcQuaid** [comment]
Apple doesn't guarantee it but we've been doing it successfully for a few versions across many packages with no reported issues.

**Comment by harcokuppens** [comment]
clear! 

I found this a fruitful conversation, maybe it is an idea to instruct small projects who want to build bottles in the homebrew documentation at section of the https://docs.brew.sh/Bottles#creation  that the brew bot is only available for big/popular projects, and then redirect them to the page https://docs.brew.sh/Taps with the note that building a bottle for an older macOS will also be used for newer macOS versions. And  in case this gives problems, which is improbable, then you can still force a build from source. I changed my installation page for torxakis already with this notification. (see below).  Or make a special page for small projects how they best can setup their homebrew installation procedure. We just found out a good way in this discussion, why not help others struggling with this!
This would help future small projects to quickly setup a good fast installation with homebrew!!

By the way another possibility to build bottles for different macos versions maybe to use
-  github actions which supports a docker kind of version of macOS Catalina hosted  MacStadium  : https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
- appveyor which hosts for you both as virtual machines macOS Catalina and Mojave: https://www.appveyor.com/docs/build-environment/#build-worker-images
- or just install macOS in virtualbox yourself, but I understand according the apple licensing this is illegal. So forget about this option.

But for now I just changed our installation page at: 
https://github.com/TorXakis/homebrew-TorXakis/blob/master/README.md#install-torxakis-on-macos


### Install `TorXakis` on macOS ###

To install `TorXakis` using this tap, use the following commands:

```sh
brew tap torxakis/torxakis
brew install torxakis
```
Homebrew will fetch a pre-build binary and do a quick installation. 
Homebrew will also install [SMT][1] solver [Z3][3] as runtime dependency of the  `TorXakis` package.

If you just have the newest MacOS version installed for which no pre-build binary is installed yet, then homebrew will install the pre-build binary from the previous MacOS version. In case this gives problems, which is improbable, then you can still force a build from source with the commands: 

```sh
brew tap torxakis/torxakis
brew install --build-from-source torxakis
```

Thank you for your fruitful ideas,

cheers
Harco

**Comment by MikeMcQuaid** [comment]
Thanks @harcokuppens, good ideas!

**Pull request closed without merging**
