### PR TITLE
php@7.3 7.3.12 (new formula)

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

To be merged after #47289: brings back PHP 7.3.12 as versioned formula.

### CODE REVIEW

**Comment by alcaeus** [comment]
@SMillerDev should I drop the `bottle` block? The bot complains, but the bottles should be the same if I'm not mistaken since we already had the version (albeit under a different name).

**Comment by Bo98** [comment]
This is a new formula with a different name so the bottles will be in a different place and regenerated so they won't end up being the same. You should indeed remove that block.

**Comment by alcaeus** [comment]
I see, thanks for the explanation, @Bo98! Bottle block is removed now.

**Comment by Bo98** [comment]
The CI will remain red due to the conflict with the alias. It should go green once #47289 is merged.

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
