### PR TITLE
vala 0.42.2

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by javian** [comment]
This is the only build failure
```
14:00:11 ==> brew linkage --test submarine
14:00:12 ==> FAILED
14:00:12 Missing libraries:
14:00:12   /tmp/submarine-20180827-60452-1o3uvmq/submarine-0.1.7b/src/lib/libSubmarine.1.dylib
```

**Comment by fxcoudert** [comment]
Given that submarine has relatively low install count (8 last month), that the parent project is dead since 2013, that the fork we're using has had no activity for a year, that it doesn't accept bug reports… I'd say we remove it?

**Comment by javian** [comment]
@fxcoudert I'd second that

**Comment by fxcoudert** [comment]
I welcome review on #32416
Meanwhile I am going to merge `vala`

**Pull request closed without merging**
