### PR TITLE
zellij 0.11.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Error: Failure while executing; `/opt/homebrew/Cellar/zellij/0.11.0/bin/zellij generate-completion bash` exited with 1. Here's the output:

```
I think they changed how completions are generated.

**Comment by cho-m** [comment]
OLD: `zellij generate-completion ...`
NEW: `zellij setup --generate-completion ...`

**Comment by carlocab** [comment]
Build succeeds, but the test fails.

**Comment by carlocab** [comment]
Marking as `do not merge`, as this will introduce a merge conflict in #77365. That PR should be merged before this one.

**Comment by cho-m** [comment]
> Build succeeds, but the test fails.

I think `--dump-config` return code may have changed.
Haven't taken much of a look, but seems to be no error (0) rather than 1.

**Comment by cho-m** [comment]
Removing label as other PR is merged.

Hopefully can pass CI after rebasing & changing testcase output return code from 1 to 0.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
