### PR TITLE
xml-security-c 2.0.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`shibboleth-sp` requires a revision bump

**Comment by javian** [comment]
It still seems to fail after revision bump :/

**Comment by igas** [comment]
```
==> /usr/local/Cellar/shibboleth-sp/3.0.2_4/sbin/shibd -t
dyld: Symbol not found: __ZN11xercesc_3_212ArrayJanitorIDsEC1EPDs
  Referenced from: /usr/local/opt/xml-tooling-c/lib/libxmltooling.8.dylib
  Expected in: /usr/local/opt/xml-security-c/lib/libxml-security-c.20.dylib
 in /usr/local/opt/xml-tooling-c/lib/libxmltooling.8.dylib
Error: shibboleth-sp: failed
```

**Comment by fxcoudert** [comment]
`xml-tooling-c` needs revision too, then :)

**Comment by fxcoudert** [comment]
Thanks @igas

**Pull request closed without merging**
