### PR TITLE
go 1.9.1

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by leonklingele** [comment]
This release fixes two security issues, https://github.com/golang/go/issues/22131 and https://github.com/golang/go/issues/22133

**Comment by cblecker** [comment]
@leonklingele You need to bump the revision on `Formulas/godep.rb`

**Comment by leonklingele** [comment]
@cblecker done. I wonder why this needs to be done though.

**Comment by fxcoudert** [comment]
Thanks @leonklingele for the pull request!

**Comment by DomT4** [comment]
>  I wonder why this needs to be done though.

The `godep` executable stores the full Cellar path to `go` rather than the `opt_prefix`, sadly.

**Pull request closed without merging**
