### PR TITLE
jpeg 9e

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
timeout on build

**Comment by Porkepix** [comment]
Can we have the tag for the long CI run, @chenrui333?

**Comment by alebcay** [comment]
Restarted long-running build. Heads up, the Fossies mirror doesn't seem to have the file yet.

**Comment by iMichka** [comment]
```
  ==> Pouring texlive--58837.arm64_big_sur.bottle.tar.gz
  The formula built, but is not symlinked into /opt/homebrew
  Could not symlink bin/cfftot1
  Target /opt/homebrew/bin/cfftot1
  is a symlink belonging to lcdf-typetools. You can unlink it:
    brew unlink lcdf-typetools
```

**Comment by carlocab** [comment]
`jpegrescan` failure is probably pre-existing on Linux: https://github.com/Homebrew/linuxbrew-core/blob/51b47956b0713413d134a533759a1873e53a3578/Formula/jpegrescan.rb

**Review by carlocab — APPROVED** [review]
No real failures. `texlive` install failure fixed in #93623.

**Pull request closed without merging**
