### PR TITLE
lftp: migrate to boneyard

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
4.7.3 still doesn't build unless we apply @nijikon's patch, which does work.

**Comment by zmwangx** [comment]
Quite a few installs actually, 3754 last month 7166 total.

**Comment by ilovezfs** [comment]
if upstream can be convinced to absorb the patch, :skull: can be avoided

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/1509

**Pull request merged**
