### PR TITLE
libgit2 1.1.0 salt 3002.2

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
brew test --retry --verbose cargo-c
brew test --retry --verbose cargo-edit
brew test --retry --verbose git-series
brew test --retry --verbose gitg
brew test --retry --verbose gitless
brew test --retry --verbose libgit2-glib
brew test --retry --verbose literate-git
```

**Comment by davidetacchini** [comment]
Is `bottle do` block failing? If so, I followed what is written in the documentation, so what can I do?

Documentation reference:
If there’s a `bottle do` block in the formula, don’t remove or change it; we’ll update it when we pull your PR.

**Comment by chenrui333** [comment]
@davidetacchini you are fine, just the linkage test failure (which is hard to do locally)

**Comment by chenrui333** [comment]
```
brew install --verbose --build-bottle gitless
brew install --verbose --build-bottle literate-git
```

**Comment by chenrui333** [comment]
only failed with salt on 11.0
```
Error: 1 failed steps!
brew install --verbose --build-bottle salt
```

**Comment by chenrui333** [comment]
Should be good to go after this build.

**Comment by bayandin** [comment]
`salt` has changed the way they handle dependencies (https://github.com/saltstack/salt/pull/56904), so we need to find a way to avoid `pyobjc` installation.

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
