### PR TITLE
hadolint 1.17.4

### LINKED ISSUE #380: hadolint 1.17.4 homebrew upgrade issue
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

We have issue upgrading hadolint to either v1.17.4 or v1.17.3 (same error log for both)
Relates to 
- v1.17.4 upgrade, https://github.com/Homebrew/homebrew-core/pull/48554/ 
- v1.17.3 upgrade, https://github.com/Homebrew/homebrew-core/pull/47018

Build log, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/54565/version=mojave/console

**Additional environment details (OS, stack version, etc.)**

Failed on Catalina, Mojave, and HighSierra.

### PR DESCRIPTION
**Pull request by zemanlx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I have decided to replace the installation method for our `hadolint` build to our supported `stack`. If fixes #48554 and may help as an inspiration in #48604. On my way to enlightenment, I had to add Linux build for `haskell-stack` formula.

Also fixes https://github.com/hadolint/hadolint/issues/380.

### CODE REVIEW

**Comment by issyl0** [comment]
Thanks for thinking of Linux users too! 😍

 You'll be pleased to know there's an easier way to detect macOS vs. Linux: Homebrew includes `OS.mac?` and `OS.linux?`.

You'll find more examples of the usage in [Homebrew/linuxbrew-core](https://github.com/Homebrew/linuxbrew-core), the separate (downstream) Linux repo. For now, changes are merged from here into there a couple of times a day, and we make Linux-specific edits in the Linux repo rather than here. In light of this, could you please submit the Linux tweaks separately downstream, if they're not already done?

Thanks!

**Comment by zemanlx** [comment]
@issyl0 Oh, I haven't noticed that there is a separate repository for Linux. I will drop that Linux commit here a post it in `linuxbrew-core`.

**Comment by zemanlx** [comment]
I have not committed Linux changes in the end as there is a PR https://github.com/Homebrew/linuxbrew-core/pull/19236 waiting to be merged (not sure why it is failing). 

Can @issyl0 or @chenrui333 please give me any estimation when this can be merged? I would like to do another release of `hadolint` soon and want this one working before that.

**Comment by chenrui333** [comment]
@zemanlx sorry for the delay, merging the PR now.

**Pull request closed without merging**
