### PR TITLE
go 1.10.2

### PR DESCRIPTION
**Pull request by AlekSi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

/cc @ilovezfs

### CODE REVIEW

**Comment by AlekSi** [comment]
I see #25924 also bumped `godep` revision, but I'm not sure that makes it special, and why `dep`, `glide` and other formulas should not be bumped too.

**Comment by commitay** [comment]
@AlekSi Please make `godep` a separate commit with the subject `godep: revision for go`

**Comment by DomT4** [comment]
> but I'm not sure that makes it special

`godep` embeds `go`'s full versioned prefix in the binary.

**Review by DomT4 — APPROVED** [review]

**Comment by commitay** [comment]
Thanks @AlekSi!

**Pull request closed without merging**
