### PR TITLE
openjdk 21.0.1

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Is there a way to see the previous CI run before a force push - or is it irretrievable?

**Comment by SMillerDev** [comment]
> Is there a way to see the previous CI run before a force push - or is it irretrievable?

Open the commit from the timeline and see the status next to the title in the top left

**Comment by bevanjkay** [comment]
Is there a chance that the failing tests are Sonoma-specific? I could not find anything regarding the `bnfc` test, and the `carrot2` test failure seems to have carried over from version `21`.

**Comment by chenrui333** [comment]
consider this is just patch upgrade, no need to build from source.

**Comment by chenrui333** [comment]
somewhat known unstable test failures

```
brew test --retry --verbose solr@8.11
brew test --retry --verbose trino
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
rebased after #152284

**Pull request merged**
