### PR TITLE
Rename cdiff to ydiff

### PR DESCRIPTION
**Pull request by ymattw**
Per user request I renamed the package to ydiff to avoid binary name
conflict on major Linux distributions.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ymattw** [comment]
Not sure what's the best practice for renaming. Until version 1.1 it conflicts with `colordiff`, should I keep an alias `Aliases/cdiff`?

**Comment by ymattw** [comment]
Any feedback?

**Comment by ymattw** [comment]
Hello, do I need to do anything else in order to move this forward?

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
Thanks for the submission! I'm sorry for the time it's tkaen to merge.

**Comment by ymattw** [comment]
Thanks for your support!

**Pull request merged**
