### PR TITLE
gobject-introspection 1.54.0

### PR DESCRIPTION
**Pull request by tschoonj**
Depends on #17933

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Are these sort of warnings during compile expected?

screen shot 2017-09-11 at 22 01 36

**Comment by tschoonj** [comment]
Yep, I see them too... not sure if they're harmful though. Will open a bugzilla ticket over this.

**Comment by tschoonj** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=787571

**Comment by DomT4** [comment]
Thanks @tschoonj. Colour me relieved at least it decided not to share the suppressed block of 629 warnings.

**Pull request closed without merging**
