### PR TITLE
haskell-stack 2.7.5

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
  [ 68 of 111] Compiling Stack.Config
  
  src/Stack/Config.hs:662:5: error:
      Variable not in scope:
        fetchReposRaw :: [(Repo, RawPackageMetadata)] -> RIO env a0
      |
  662 |     fetchReposRaw gitRepos
      |     ^^^^^^^^^^^^^
```
Ideas here, @simnalamburt?

**Comment by fishtreesugar** [comment]
`fetchReposRaw` expose in  `pantry-0.5.3`:https://github.com/commercialhaskell/pantry/pull/41, but using pantry-0.5.2.2

**Comment by fishtreesugar** [comment]
https://github.com/commercialhaskell/pantry/blob/master/ChangeLog.md#v054 pantry v0.5.4 support aeson-2.0, let me try to remove the freezing cabal patch

**Comment by simnalamburt** [comment]
We have two options:

1. Instead of removing the `cabal.project.freeze` file, update it properly. [stack2cabal](https://github.com/brunjlar/stack2cabal) will do all the heavy-lifting.
2. Change the build script to use not cabal but stack itself as a build tool. This is the only officially supported way to build stack from source code.

Which one do you prefer?

**Comment by fishtreesugar** [comment]
Hackage's release has version bounds https://hackage.haskell.org/package/stack, but tarball download from GitHub hasn't 😕

**Comment by fishtreesugar** [comment]
@simnalamburt option 2 will meet the bootstrap problem, so imo option 1 is better, but seems it won't accept by upstream

**Comment by simnalamburt** [comment]
Ok. I’ll prepare option 1.

I just found that you just fixed this problem by manually adjusting dependencies. This option is indeed simple, but it has a danger of sudden build failure in the future. Just like before which is #95032.

Do you prefer my option (completely freezing dependencies) or your option? (Manually adjusting few dependencies accepting future build breaking)

FYI, both option is not really automatically maintainable. The option 2 (dealing with bootstrap problem) is the only way to completely automate the future updates.

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by fishtreesugar** [comment]
@simnalamburt How about use Hackage's tarball instead of GitHub release's tarball? 

As I mentioned above:
> Hackage's release has version bounds https://hackage.haskell.org/package/stack, but tarball download from GitHub hasn't 😕

and Stack's release process already instructed use `stack upload . --pvp-bounds=lower`  upload to Hackage( https://docs.haskellstack.org/en/stable/maintainers/releases/#release-process), so I believe that's a stable source to depend on.

**Comment by simnalamburt** [comment]
@fishtreesugar It sounds like a good idea. Maybe we can change the build instruction if there's any further build issue with haskell-stack in the future releases.

**Pull request closed without merging**
