### PR TITLE
libgcrypt 1.9.0

### PR DESCRIPTION
**Pull request by J-M0**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like this needs another patch? The original patch failed to apply, but now there's a build failure.

**Comment by J-M0** [comment]
Is embedding the patches ok, or is there a way to download them from the mailing list?

**Comment by carlocab** [comment]
It's a small patch, so I guess embedding it is fine. Not sure there's a way to get the patches from the mailing list. I'd like to wait a little bit to see if that patch will get reviewed, especially given how security-sensitive libgrypt is. Unless there is something important in this version bump that we don't want to delay?

**Comment by J-M0** [comment]
I'm not aware of any pressing reason to upgrade to 1.9 right away, so I think waiting is fine

**Comment by carlocab** [comment]
Great. Let's wait a little bit to see if the patch will be reviewed. I think the author of the patch is a libgcrpyt developer, so it probably should be fine even if it isn't.

**Comment by carlocab** [comment]
Judging from https://dev.gnupg.org/T5159 (see last comment), it looks like at least some of this

https://github.com/Homebrew/homebrew-core/blob/9a60a0f9b770261c0556f6edb63b7b66e66963e2/Formula/libgcrypt.rb#L43-L52

can be removed?

**Comment by chenrui333** [comment]
try out hack removal commit.

**Comment by carlocab** [comment]
Exactly what I would've tried removing too. Thanks, @chenrui333.

**Comment by carlocab** [comment]
Should we keep a comment explaining why we still codesign on ARM? A link to an upstream report would be good for that too...

**Comment by carlocab** [comment]
Not sure why `dar` is failing on Big Sur. Can you try giving it a revision bump, @J-M0?

**Comment by carlocab** [comment]
Third time's not the charm, I guess:
```
Error: 1 failed step!
brew test --retry --verbose dar
```

**Comment by SeekingMeaning** [comment]
Oops, I should have checked https://github.com/Homebrew/homebrew-core/issues/65000; `dar` is a known failure on Big Sur

**Review by SeekingMeaning — APPROVED** [review]

**Pull request closed without merging**
