### PR TITLE
monero: build bottle

### PR DESCRIPTION
**Pull request by Bo98**
The bottle did not get generated in #52481.

(This commit will not be merged)

### CODE REVIEW

**Comment by Bo98** [comment]
I did this as a quick way to generate the bottle but we should probably fix the miniupnpc problem. Either via a `conflicts_with` (not really ideal but can be done if necessary) or by applying [the patch](https://git.alpinelinux.org/aports/tree/testing/monero/system-miniupnpc.patch) other package repositories use.

cc @bayandin

**Comment by Bo98** [comment]
930d6a6e8d0afad09db9bffaecb1148fe13ef497

**Comment by bayandin** [comment]
By any chance do you know was there attempts to upstream that patch?

**Comment by Bo98** [comment]
I tried looking for that, but didn't find anything. It is effectively a revert of https://github.com/monero-project/monero/commit/6b8539803184eebbf6bb7aef499ac0f5f242901d which was done because they needed patched version of miniupnpc for https://hackerone.com/reports/340012. However miniupnpc has those patches incorporated into 2.1, which Homebrew ships. There's now no real difference between bundled and system miniupnpc: https://github.com/monero-project/miniupnp/compare/monero

Upstream have previously shown little interest in fixing the conflict with miniupnpc (they say they don't support `make install`): https://github.com/monero-project/monero/issues/3862

**Pull request closed without merging**
