### PR TITLE
eigen 3.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
```
==> Testing ceres-solver (again)
==> cmake -DCeres_DIR=/home/linuxbrew/.linuxbrew/Cellar/ceres-solver/2.0.0_3/share/Ceres .
...
CMake Error at /home/linuxbrew/.linuxbrew/lib/cmake/Ceres/CeresConfig.cmake:85 (message):
  Failed to find Ceres - Found Eigen dependency, but the version of Eigen
  found (3.4.0) does not exactly match the version of Eigen Ceres was
  compiled with (3.3.9).
```

**Comment by carlocab** [comment]
We might have trouble merging this because the bottles from #75452 are probably still on GitHub packages. If so it should be possible to just bump the revisions again.

**Comment by SMillerDev** [comment]
I'll remove those so these can upload.

**Comment by SMillerDev** [comment]
>  Publicly visible package versions with more than 5000 downloads cannot be deleted. contact GitHub support for further assistance 

Or maybe not.

**Review by carlocab — APPROVED** [review]
Only one way to find out...

**Comment by carlocab** [comment]
Oh. Guess that worked. Ok then.

**Comment by cho-m** [comment]
Looks like extra patch number helped (old `3.4`, new `3.4.0`)

**Pull request closed without merging**
