### PR TITLE
bzt 1.16.21

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
```
==> brew audit bzt --online --git --skip-style
==> FAILED
Full audit bzt --online --git --skip-style output
  bzt:
    * The homepage URL https://gettaurus.org/ is not reachable
  Error: 1 problem in 1 formula detected
```

Not sure why this happened multiple times, but the homepage is actually reachable: https://gettaurus.org/

**Comment by SMillerDev** [comment]
Maybe it needs brew curl?

**Comment by ZhongRuoyu** [comment]
> Maybe it needs brew curl?

No, tried locally, that didn't work. When accessing the homepage with `curl`, `curl` said:

```console
$ /home/linuxbrew/.linuxbrew/bin/curl -v https://gettaurus.org/
*   Trying 34.67.81.175:443...
* Connected to gettaurus.org (34.67.81.175) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

There was already some discussion about this issue in https://github.com/Homebrew/homebrew-core/pull/111035. Also some in their Google Groups discussion board: [this](https://groups.google.com/g/codename-taurus/c/FS_cC9yMoqw) posted by a user, and [this](https://groups.google.com/g/codename-taurus/c/tbZ8YR_iV0s) posted by @chenrui333.

Since this is still an unsolved issue, I filed https://github.com/Blazemeter/taurus/issues/1703. Meanwhile, I think that we can at least ship the release for now, as this issue isn't blocking.

**Comment by ZhongRuoyu** [comment]
Left with the audit failure now so I'm marking this as https://github.com/Homebrew/homebrew-core/labels/ready%20to%20merge. Also, upstream is checking on the SSL issue now: https://github.com/Blazemeter/taurus/issues/1703#issuecomment-1469834393

**Comment by ZhongRuoyu** [comment]
Upstream fixed this super quickly, and I am able to verify the fix locally (`brew livecheck --online bzt`).

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
