### PR TITLE
axel: use openssl@1.1

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Is there a reason for this change?

**Comment by equal-l2** [comment]
For future version bump of `openssl`.
`openssl` will be replaced with `openssl@1.1`, right?

**Comment by ilovezfs** [comment]
@equal-l2 it may be at some point, but currently we're not switching things over unless there is a compelling reason for a given formula.

**Comment by equal-l2** [comment]
@ilovezfs OK, I'll make PR again in future.

**Comment by ilovezfs** [comment]
@equal-l2 cool. Thanks for the PR nonetheless!!

**Pull request closed without merging**
