### PR TITLE
python 2.7.12

### PR DESCRIPTION
**Pull request by rakkesh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Do we want to update `pip`, etc here at all @tdsmith?

**Comment by tdsmith** [comment]
That would be lovely!

**Comment by rakkesh** [comment]
[pip](https://pypi.python.org/pypi/pip/) 8.1.2 and [wheel](https://pypi.python.org/pypi/wheel/) 0.29.0 are the latest versions available and already present the formula.

**Comment by DomT4** [comment]
I think there's a new `setuptools` at least?

**Comment by rakkesh** [comment]
Ah, I didn't check just that package, thanks for noticing 👍. I am not sure how to get the URL of `setuptools` on `files.pythonhosted.org`.

**Comment by rakkesh** [comment]
Updated the `resource` `setuptools` as suggested by @tdsmith.

**Comment by DomT4** [comment]
Thanks @rakkesh. Are you happy here @tdsmith? I notice the new patch covers a pretty ancient bug, but I don't mind us using it if you're happy.

**Comment by tdsmith** [comment]
Looks great, thanks for your help!

**Pull request closed without merging**
