### PR TITLE
mkvtoolnix: Link CoreFoundation on QT builds.

### PR DESCRIPTION
**Pull request by leetoburrito**
This addresses #35256.  Not sure if this is the Right Way(tm) to fix this, but it works for me.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by indocomsoft** [comment]
I can confirm that this works

**Comment by MikeMcQuaid** [comment]
@leetoburrito Could you submit an upstream issue and/or pull request for this and link it as a Ruby comment in the line above? Thanks!

**Comment by retokromer** [comment]
This works fine on my end as well.

**Comment by naos** [comment]
I can also confirm this works perfectly for mkvtoolnix 29.0.0_1 on macOS 10.14.2

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/35383 and https://github.com/Homebrew/homebrew-cask/pull/56633

**Pull request closed without merging**
