### PR TITLE
cucumber-cpp 0.3.1

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing:
```
==> /usr/bin/clang++ test.cpp -L/usr/local/Cellar/cucumber-cpp/0.3.1/lib -lcucumber-cpp -o test -lboost_regex -lboost_system
In file included from test.cpp:1:
/usr/local/include/cucumber-cpp/defs.hpp:1:2: warning: Use of defs.hpp is deprecated, please use either autodetect.hpp or generic.hpp [-W#warnings]
#warning Use of defs.hpp is deprecated, please use either autodetect.hpp or generic.hpp
 ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "boost::program_options::validators::check_first_occurrence(boost::any const&)", referenced from:
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, int*, long) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::to_internal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > boost::program_options::to_internal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::variables_map::variables_map()", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::options_description::add_options()", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::options_description::m_default_line_length", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::options_description::options_description(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, unsigned int)", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::invalid_option_value::invalid_option_value(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, int*, long) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::error_with_option_name::error_with_option_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::options_description_easy_init::operator()(char const*, char const*)", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::arg", referenced from:
      boost::program_options::typed_value<int, char>::name() const in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool)", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>)", referenced from:
      boost::program_options::basic_command_line_parser<char>::extra_parser(boost::function1<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::detail::cmdline::set_options_description(boost::program_options::options_description const&)", referenced from:
      boost::program_options::basic_parsed_options<char> boost::program_options::parse_command_line<char>(int, char const* const*, boost::program_options::options_description const&, int, boost::function1<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::detail::cmdline::get_canonical_option_prefix()", referenced from:
      boost::program_options::basic_command_line_parser<char>::run() in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::detail::cmdline::run()", referenced from:
      boost::program_options::basic_command_line_parser<char>::run() in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::detail::cmdline::style(int)", referenced from:
      boost::program_options::basic_parsed_options<char> boost::program_options::parse_command_line<char>(int, char const* const*, boost::program_options::options_description const&, int, boost::function1<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::detail::cmdline::cmdline(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::notify(boost::program_options::variables_map&)", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::program_options::options_description const&)", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::abstract_variables_map::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::error_with_option_name::substitute_placeholders(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> > in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error> in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::program_options::validation_error in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> > in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::program_options::invalid_option_value in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::error_with_option_name::what() const", referenced from:
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> > in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error> in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::program_options::validation_error in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> > in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> in libcucumber-cpp.a(main.cpp.o)
      vtable for boost::program_options::invalid_option_value in libcucumber-cpp.a(main.cpp.o)
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<int, char> in libcucumber-cpp.a(main.cpp.o)
  "typeinfo for boost::program_options::error_with_option_name", referenced from:
      typeinfo for boost::program_options::validation_error in libcucumber-cpp.a(main.cpp.o)
  "typeinfo for boost::program_options::value_semantic_codecvt_helper<char>", referenced from:
      typeinfo for boost::program_options::typed_value<int, char> in libcucumber-cpp.a(main.cpp.o)
  "vtable for boost::program_options::variables_map", referenced from:
      _main in libcucumber-cpp.a(main.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for boost::program_options::error_with_option_name", referenced from:
      boost::program_options::error_with_option_name::error_with_option_name(boost::program_options::error_with_option_name const&) in libcucumber-cpp.a(main.cpp.o)
      boost::program_options::error_with_option_name::~error_with_option_name() in libcucumber-cpp.a(main.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: cucumber-cpp: failed
Failed executing: /usr/bin/clang++ test.cpp -L/usr/local/Cellar/cucumber-cpp/0.3.1/lib -lcucumber-cpp -o test -lboost_regex -lboost_system
```

**Comment by tdsmith** [comment]
The compiler invocation is probably missing `-lboost_program_options`.

**Comment by Jerzerak** [comment]
Spot on Tim!

**Comment by apjanke** [comment]
Passes now.

Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
