### PR TITLE
ntopng 3.6

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Add `--with-ndpi-static-lib=DIR` ?

**Comment by fxcoudert** [comment]
Sadly, it does not help.

**Comment by fxcoudert** [comment]
So we'll have to wait for the next version…

**Comment by fxcoudert** [comment]
And now it tries to link a non existing library:

```
13:30:55 clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6 -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6/include -I/usr/local/include -I /private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6/third-party/hiredis -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6/third-party/mongoose -I/usr/local/Cellar/json-c/0.13.1/include/json-c  -I./nDPI/src/include -I./nDPI/src/lib/third_party/include -I/usr/local/include/lua -DDONT_USE_LUAJIT -I/usr/local/Cellar/rrdtool/1.7.0_1/include -I/usr/local/Cellar/zeromq/4.2.5/include -I/usr/local/opt/mysql-client/include/mysql  -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6 -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6/include -I/usr/local/include -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6/third-party/http-client-c/src/   -DDATA_DIR='"/usr/local/Cellar/ntopng/3.6/share"' -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6/third-party/libgeohash -I/private/tmp/ntopng-20180919-21146-4iutd4/ntopng-3.6/third-party/patricia   -c src/nDPIStats.cpp -o src/nDPIStats.o
13:30:55 clang++  src/AddressList.o  src/AddressResolution.o  src/AddressTree.o  src/AlertCounter.o  src/AlertsManager.o  src/AutonomousSystem.o  src/AutonomousSystemHash.o  src/Checkpointable.o  src/CollectorInterface.o  src/CountriesHash.o  src/Country.o  src/DB.o  src/DnsStats.o  src/DummyInterface.o  src/ElasticSearch.o  src/EthStats.o  src/ExportInterface.o  src/Flow.o  src/FlowGrouper.o  src/FlowHash.o  src/FrequentNumericItems.o  src/FrequentStringItems.o  src/FrequentTrafficItems.o  src/GenericHash.o  src/GenericHashEntry.o  src/GenericTrafficElement.o  src/Geolocation.o  src/Grouper.o  src/HTTPBL.o  src/HTTPserver.o  src/HTTPstats.o  src/Host.o  src/HostHash.o  src/HostPools.o  src/ICMPstats.o  src/InterfaceStatsHash.o  src/IpAddress.o  src/LocalHost.o  src/LocalTrafficStats.o  src/Logstash.o  src/LuaEngine.o  src/MDNS.o  src/Mac.o  src/MacHash.o  src/MacManufacturers.o  src/Mutex.o  src/MySQLDB.o  src/NetworkDiscovery.o  src/NetworkInterface.o  src/NetworkStats.o  src/Ntop.o  src/NtopGlobals.o  src/PF_RINGInterface.o  src/PacketDumper.o  src/PacketDumperTuntap.o  src/PacketStats.o  src/Paginator.o  src/ParserInterface.o  src/PcapInterface.o  src/PeriodicActivities.o  src/Prefs.o  src/ProtoStats.o  src/Redis.o  src/RemoteHost.o  src/RwLock.o  src/SNMP.o  src/StatsManager.o  src/StoreManager.o  src/TcpFlowStats.o  src/TcpPacketStats.o  src/ThreadPool.o  src/ThreadedActivity.o  src/TimeSeriesExporter.o  src/Trace.o  src/TrafficStats.o  src/Utils.o  src/ViewInterface.o  src/VirtualHost.o  src/VirtualHostHash.o  src/Vlan.o  src/VlanAddressTree.o  src/VlanHash.o  src/ZCCollectorInterface.o  src/main.o  src/nDPIStats.o  -Wall ./nDPI/src/lib/libndpi.a -lpcap -L/usr/local/lib -llua -lm -L/usr/local/Cellar/rrdtool/1.7.0_1/lib -lrrd   /usr/local/lib/libzmq.a -L/usr/local/Cellar/json-c/0.13.1/lib -ljson-c -lmaxminddb   -lsqlite3 -L/usr/local/opt/mysql-client/lib -lmysqlclient -lssl -lcrypto  -pagezero_size 10000 -image_base 100000000 -image_base 7fff04c4a000  -L/usr/local/lib -lldap -llber -lz -ldl -lcurl   -lm -lpthread -lstdc++.6 -o ntopng
13:30:55 ld: library not found for -lstdc++.6
```

**Comment by fxcoudert** [comment]
Given that the current work doesn't work on Mojave either, I am going to merge this. Someone else (hopefully upstream) can open a pull request when the next release is cut, hopefully it will work on Mojave.

**Pull request closed without merging**
