### PR TITLE
Update fish to 3.2.0

### PR DESCRIPTION
**Pull request by pusewicz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by pusewicz** [comment]
There's a PR already. Closing.

**Comment by andreiborisov** [comment]
@pusewicz reopen please, the other PR was closed

**Comment by SMillerDev** [comment]
It was closed because it was merged, no need to merge the same change twice

**Comment by andreiborisov** [comment]
Ok, sorry, I was misled by GitHub mobile app UI😅

**Pull request closed without merging**
