### PR TITLE
numpy 1.17.1, scipy 1.3.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
```
20:53:56 ==> python2 setup.py build --fcompiler=gnu95 --parallel=3 install --prefix=/usr/local/Cellar/numpy/1.17.0 --single-version-externally-managed --record=installed.txt
20:53:56 Traceback (most recent call last):
20:53:56   File "setup.py", line 31, in <module>
20:53:56     raise RuntimeError("Python version >= 3.5 required.")
20:53:56 RuntimeError: Python version >= 3.5 required.
```

**Comment by jonchang** [comment]
Rebased on master and made some updates.

**Comment by fxcoudert** [comment]
The `ola` release notes (https://github.com/OpenLightingProject/ola/releases/tag/0.10.7) have stuff about Python 3, so there must be a way to compile it with Python 3. And `gnuradio`'s latest version has Python 3 support as well, although I haven't fully managed to get it working: https://github.com/Homebrew/homebrew-core/pull/43753

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
