### PR TITLE
mbedtls 3.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
The `inreplace` needs to be adjusted. `include/mbedtls/config.h` now lives at `include/mbedtls/mbedtls_config.h`.

**Comment by carlocab** [comment]
ARM

```
Error: 1 failed step!
brew test --verbose mbedtls
```

Intel macOS

```
Error: 9 failed steps!
brew linkage --test gauche
brew linkage --test hashlink
brew test --retry --verbose hashlink
brew linkage --test haxe
brew test --retry --verbose haxe
brew linkage --test neko
brew linkage --test ortp
brew linkage --test shadowsocks-libev
brew test --retry --verbose shadowsocks-libev
```

Linux

```
Error: 2 failed steps!
brew linkage --test shadowsocks-libev
brew test --retry --verbose shadowsocks-libev
```

**Comment by carlocab** [comment]
Looks like most dependent formulae don't support this version yet.

**Comment by colinthart** [comment]
I've just encountered this [same issue](https://gist.github.com/colinthart/9841a8315f96a13daf1b29edc2ffe01c).

**Comment by carlocab** [comment]
That issue isn't quite the same. The only similarity is the need to rename `config.h` to `mbedtls_config.h` but that's just a minor difficulty. The major issue here is that many dependent formulae don't build with 3.0.0, whereas your problem is that `mbedtls` just doesn't build.

Note that we don't provide support for source builds, and this includes `--HEAD` installs. You can try the [discussions page](https://github.com/Homebrew/discussions/discussions) to see if someone else might have a solution, but I wouldn't count on it.

**Comment by colinthart** [comment]
Thank you carlocab.  I was attempting `--HEAD` because that was in the instruction in the readme I was following, but I've now performed the homebrew install without it and was able complete my original build task with dependence on `mbedtls` successfully.

**Comment by chenrui333** [comment]
Will revisit it at a different time.

**Pull request closed without merging**
