### PR TITLE
harfbuzz 6.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Marking `do not merge` just in case as conflict with `icu4c`.

**Comment by chenrui333** [comment]
for linux build

```
  /tmp/qt-20221218-319294-2b0rad/qt-everywhere-src-6.4.1/qtquick3d/src/quick3d/qquick3dtexturedata.h:84:2: fatal error: cannot write PCH file: No space left on device
     84 | };
        |  ^
```

**Comment by cho-m** [comment]
That's because we haven't rebottled `qt` on Linux yet and building `qt` requires self-hosted Linux. Bottle should be available with `icu4c` PR.

**Comment by p-linnane** [comment]
Rebased now that `qt` is bottled on Linux again.

**Comment by SMillerDev** [comment]
```
 ==> Testing walkmod
  ==> git clone --depth 1 https://github.com/walkmod/walkmod-core.git
  Cloning into 'walkmod-core'...
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128: warning: conflicting chdir during another chdir block
  ==> /usr/local/Cellar/walkmod/3.0.0_1/bin/walkmod chains
  Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
   INFO [main] - Java version: 19.0.1
   INFO [main] - Java Home: /usr/local/Cellar/openjdk/19.0.1/libexec/openjdk.jdk/Contents/Home
   INFO [main] - OS: Mac OS X, Vesion: 13.0.1
  --------------------------------------------------------------------------------
                       _    _       _ _   ___  ___          _                     
                      | |  | |     | | |  |  \/  |         | |                    
                      | |  | | __ _| | | _| .  . | ___   __| |                    
                      | |/\| |/ _` | | |/ / |\/| |/ _ \ / _` |                    
                      \  /\  / (_| | |   <| |  | | (_) | (_| |                    
                       \/  \/ \__,_|_|_|\_\_|  |_/\___/ \__,_|                    
  --------------------------------------------------------------------------------
  An open source tool to apply code conventions
  version 3.0 - February 2017 -
  --------------------------------------------------------------------------------
  FATAL [main] - The markup declarations contained or pointed to by the document type declaration must be well-formed. at (-//WALKMOD//DTD:1:3)
  org.xml.sax.SAXParseExceptionpublicId: -//WALKMOD//DTD; systemId: http://www.walkmod.com/dtd/walkmod-1.1.dtd; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.
  	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
  	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(XMLDTDScannerImpl.java:2030)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDExternalSubset(XMLDTDScannerImpl.java:299)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1165)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
  	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
  	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
  	at org.walkmod.util.DomHelper.parse(DomHelper.java:90)
  	at org.walkmod.conf.providers.XMLConfigurationProvider.loadDocument(XMLConfigurationProvider.java:214)
  	at org.walkmod.conf.providers.XMLConfigurationProvider.init(XMLConfigurationProvider.java:143)
  	at org.walkmod.conf.ConfigurationManager.executeConfigurationProviders(ConfigurationManager.java:123)
  	at org.walkmod.WalkModFacade.getConfiguration(WalkModFacade.java:918)
  	at org.walkmod.commands.PrintChainsCommand.execute(PrintChainsCommand.java:57)
  	at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
  	at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
  Exception in thread "main" org.walkmod.conf.ConfigurationException: Unable to load /private/tmp/walkmod-test-20221223-96725-15zpi60/walkmod-core/walkmod.xml
  	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
  	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(XMLDTDScannerImpl.java:2030)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDExternalSubset(XMLDTDScannerImpl.java:299)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1165)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
  	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
  	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
  	at org.walkmod.util.DomHelper.parse(DomHelper.java:90)
  	at org.walkmod.conf.providers.XMLConfigurationProvider.loadDocument(XMLConfigurationProvider.java:214)
  	at org.walkmod.conf.providers.XMLConfigurationProvider.init(XMLConfigurationProvider.java:143)
  	at org.walkmod.conf.ConfigurationManager.executeConfigurationProviders(ConfigurationManager.java:123)
  	at org.walkmod.WalkModFacade.getConfiguration(WalkModFacade.java:918)
  	at org.walkmod.commands.PrintChainsCommand.execute(PrintChainsCommand.java:57)
  	at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
  	at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
  Caused by: The markup declarations contained or pointed to by the document type declaration must be well-formed. - org.walkmod.util.location.LocationImpl@7692d9cc
  	... 27 more
  Caused by: org.xml.sax.SAXParseExceptionpublicId: -//WALKMOD//DTD; systemId: http://www.walkmod.com/dtd/walkmod-1.1.dtd; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.
  	... 27 more
```

**Comment by Bo98** [comment]
Looks like the WalkMod domain has expired, and should probably be deprecated.

**Comment by p-linnane** [comment]
`walkmod` deprecated in https://github.com/Homebrew/homebrew-core/pull/118826.

**Comment by cho-m** [comment]
Linux probably needs `pkg-config`:
```
  Did not find pkg-config by name 'pkg-config'
  Found Pkg-config: NO
  Did not find CMake 'cmake'
  Found CMake: NO
  Run-time dependency freetype2 found: NO (tried pkgconfig and cmake)
  Run-time dependency freetype found: NO (tried pkgconfig and cmake)
```

**Comment by chenrui333** [comment]
> Linux probably needs `pkg-config`:
> 
> ```
>   Did not find pkg-config by name 'pkg-config'
>   Found Pkg-config: NO
>   Did not find CMake 'cmake'
>   Found CMake: NO
>   Run-time dependency freetype2 found: NO (tried pkgconfig and cmake)
>   Run-time dependency freetype found: NO (tried pkgconfig and cmake)
> ```
> 
> Might have been an indirect dependency beforehand.

it was not an issue in this workflow run though, https://github.com/Homebrew/homebrew-core/actions/runs/3716962046/jobs/6319562802

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
