### PR TITLE
statically link the Swift runtime libraries into sourcery

### PR DESCRIPTION
**Pull request by jpsim**
The current formula _requires_ that the user have the exact same version of Xcode as Homebrew's Jenkins CI machines located exactly at the same location (`/Applications/Xcode.app`).

That's because the formula uses Swift Package Manager to build the bottle, which adds an `LC_RPATH` command to the binary with an absolute path to the SDK where the Swift runtime dynamic libraries can be found (e.g. `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx`). So if you've installed Xcode anywhere else, or if the version of Xcode you have installed at that location isn't the same version as was used on Homebrew's Jenkins machines, you'll have to build from source using a command like `brew install sourcery --HEAD`.

### CODE REVIEW

**Comment by jpsim** [comment]
CC'ing @ilovezfs & @vknabel as they added/updated this formula before.

**Comment by ilovezfs** [comment]
Thanks for this. It sounds like we should bump the revision, too.

**Comment by ilovezfs** [comment]
I rebased it, and added the revision.

**Comment by ilovezfs** [comment]
The build fails on Sierra, presumably due to Xcode 8.3
```
==> swift build -c release -Xswiftc -static-stdlib
swift-build: error: the package has an unsupported layout, modulemap (/private/tmp/sourcery-20170412-49020-7oic81/Sourcery-0.5.9/.build/checkouts/SourceKitten.git-6484296299232452758/Source/SourceKittenFramework/clang-c/module.modulemap) is not allowed to be mixed with sources
fix: move the modulemap inside include directory
Fetching https://github.com/kylef/Stencil.git
Fetching https://github.com/kylef/Commander.git
Fetching https://github.com/kylef/PathKit.git
Fetching https://github.com/jpsim/SourceKitten.git
Fetching https://github.com/vknabel/SwiftTryCatch.git
Fetching https://github.com/IBM-Swift/CommonCrypto.git
Fetching https://github.com/SwiftGen/StencilSwiftKit.git
Fetching https://github.com/kylef/Spectre.git
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/norio-nomura/Clang_C.git
Fetching https://github.com/norio-nomura/SourceKit.git
Fetching https://github.com/antitypical/Result.git
Cloning https://github.com/jpsim/SourceKitten.git
Resolving https://github.com/jpsim/SourceKitten.git at 0.15.3
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 0.1.2
Cloning https://github.com/antitypical/Result.git
Resolving https://github.com/antitypical/Result.git at 3.2.1
Cloning https://github.com/kylef/Stencil.git
Resolving https://github.com/kylef/Stencil.git at 0.8.0
Cloning https://github.com/IBM-Swift/CommonCrypto.git
Resolving https://github.com/IBM-Swift/CommonCrypto.git at 0.1.4
Cloning https://github.com/norio-nomura/Clang_C.git
Resolving https://github.com/norio-nomura/Clang_C.git at 1.0.2
Cloning https://github.com/kylef/Commander.git
Resolving https://github.com/kylef/Commander.git at 0.6.1
Cloning https://github.com/kylef/PathKit.git
Resolving https://github.com/kylef/PathKit.git at 0.8.0
Cloning https://github.com/norio-nomura/SourceKit.git
Resolving https://github.com/norio-nomura/SourceKit.git at 1.0.1
Cloning https://github.com/SwiftGen/StencilSwiftKit.git
Resolving https://github.com/SwiftGen/StencilSwiftKit.git at 1.0.1
Cloning https://github.com/vknabel/SwiftTryCatch.git
Resolving https://github.com/vknabel/SwiftTryCatch.git at 1.1.0
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.7.2
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 3.0.3
Cloning https://github.com/Carthage/Commandant.git
Resolving https://github.com/Carthage/Commandant.git at 0.11.3
```

**Comment by ilovezfs** [comment]
I've mentioned this here: https://github.com/krzysztofzablocki/Sourcery/issues/15#issuecomment-293581315

**Comment by krzysztofzablocki** [comment]
@ilovezfs I see 2 pr's for sourcery formula, not sure which approach is better, the second one is https://github.com/Homebrew/homebrew-core/pull/11821

**Comment by ilovezfs** [comment]
@krzysztofzablocki probably this one.

**Comment by jpsim** [comment]
The failure is due to a change in requirements to SwiftPM that affected one of Sourcery's dependencies (SourceKitten). SourceKitten was updated to conform to these new requirements in https://github.com/jpsim/SourceKitten/commit/686d4523abd4e2e352dd6297fb95e2277c29bd59, which was first included in its [0.17.1 release](https://github.com/jpsim/SourceKitten/releases/tag/0.17.1).

Sourcery updated its version of SourceKitten to 0.17.1 in https://github.com/krzysztofzablocki/Sourcery/commit/4f9a5f95ede61aa713280b164b25200b195248ff which hasn't made it into a release yet.

**Comment by krzysztofzablocki** [comment]
@jpsim @ilovezfs I've released a new version of Sourcery, it has the 0.17.1 release

**Comment by jpsim** [comment]
I've updated this formula to point to sourcery 0.6.0.

**Comment by jpsim** [comment]
CI seems to be happy with it.

**Comment by dunn** [comment]
Sorry for the wait! Merged as fc363d74ebe621d9169ee1ae9f4552e894ff25c3 and 24e7983bf5eee73a4542a8375bdc9f884250c8a3.

**Pull request closed without merging**
