### PR TITLE
Removes Micronaut formula in favour of a new cask

### PR DESCRIPTION
**Pull request by alvarosanchez**
See https://github.com/Homebrew/homebrew-cask/pull/84439

### CODE REVIEW

**Comment by SMillerDev** [comment]
Seeing the cask thread I don't really understand why it shouldn't just be built from source. It's an open source CI tool, it shouldn't be a cask.

**Comment by alvarosanchez** [comment]
First of all, because it is my understanding that Java applications aren't built from source. Correct me if I'm wrong.

But more importantly, it is not practical to build it from source. To do so, users would first need to install [GraalVM JDK](https://github.com/graalvm/homebrew-tap). Then, [the build would take ~10 minutes](https://github.com/micronaut-projects/micronaut-starter/actions?query=workflow%3A%22Mac+OS+X+Native+CLI%22) and use a lot of their CPU and memory.

Instead, you guys should adapt your acceptable formulae to consider GraalVM native images to fall in the same category as Java applications, as a native image is a binary file produced by a Java JDK, exactly what a JAR file is.

**Comment by SMillerDev** [comment]
> First of all, because it is my understanding that Java applications aren't built from source. Correct me if I'm wrong.

If they provide cross platform jar files they don't have to be built from source

> To do so, users would first need to install GraalVM JDK. Then, the build would take ~10 minutes and use a lot of their CPU and memory.

Homebrew is mostly a binary package manager, hardly anyone compiles from source. All compilation is done within our CI.

> Instead, you guys should adapt your acceptable formulae to consider GraalVM native images to fall in the same category as Java applications, as a native image is a binary file produced by a Java JDK, exactly what a JAR file is.

It is my understanding that GraalVM binaries are not cross-platform. If they are we could make an exception for those.

**Comment by alvarosanchez** [comment]
It is true that GraalVM native images are platform-specific.

So are you saying that if we provide a formula with the steps to build from source, it will be built on your CI, and users will download the pre-built binary?

**Comment by SMillerDev** [comment]
Yes they will, we call those bottles.

**Comment by alvarosanchez** [comment]
Fair enough. I will close both PRs and prepare an update for the existing formula.

**Comment by alvarosanchez** [comment]
@SMillerDev what is the syntax to make a formula `depends_on` a cask?

**Comment by SMillerDev** [comment]
That requires special whitelisting, what do you need to depend on?

**Comment by alvarosanchez** [comment]
GraalVM: https://github.com/graalvm/homebrew-tap

But if it is much trouble, I can download GraalVM as part of the installation process

**Comment by SMillerDev** [comment]
I think it'll be good to make a seperate formula for GraalVM if possible.

**Comment by alvarosanchez** [comment]
It doesn't make sense to me to create and maintain another formula when they provide an official cask.

**Comment by SMillerDev** [comment]
The requirements for homebrew-core software are that the software builds from source and comes from the homebrew organization repo. It doesn't matter if the tap is official, there is no way we can verify the software works with all the homebrew parts.

**Comment by alvarosanchez** [comment]
GraalVM is itself a platform-specific binary distribution, so if anything, I'd had to create a cask, which takes me back to square one.

Never mind anyway. I have the new formula ready and am about to submit a new PR

**Pull request closed without merging**
