### PR TITLE
iozone 3.471

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> brew install --verbose --build-bottle iozone
==> FAILED
/usr/bin/sandbox-exec -f /tmp/homebrew20170915-91433-n8uvg7.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/iozone.rb --build-bottle --verbose
==> Downloading http://www.iozone.org/src/current/iozone3_470.tar
Already downloaded: /Users/brew/Library/Caches/Homebrew/iozone-3.470.tar
==> Verifying iozone-3.470.tar checksum
tar xf /Users/brew/Library/Caches/Homebrew/iozone-3.470.tar
==> make macosx CC=clang



Build iozone for MacOSX
Building fileop for MAC OS X
Building the pit_server

clang -c -O -Dunix -Dbsd4_2 -DIOZ_macosx -DHAVE_ANSIC_C -DNO_THREADS \
		-DNAME='"macosx"' -DSHARED_MEM  iozone.c -o iozone_macosx.o


clang -c   pit_server.c  -o pit_server.o 
clang -Wall -c -O -DIOZ_macosx  fileop.c -o fileop_macosx.o
fileop.c:127:6: error: expected parameter declarator
void bzero();
     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/secure/_strings.h:53:31: note: expanded from macro 'bzero'
                __builtin___memset_chk (dest, 0, __VA_ARGS__, __darwin_obsz0 (dest))
                                            ^
fileop.c:127:6: error: expected parameter declarator
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/secure/_strings.h:53:33: note: expanded from macro 'bzero'
                __builtin___memset_chk (dest, 0, __VA_ARGS__, __darwin_obsz0 (dest))
                                              ^
fileop.c:127:6: error: expected ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/secure/_strings.h:53:33: note: expanded from macro 'bzero'
                __builtin___memset_chk (dest, 0, __VA_ARGS__, __darwin_obsz0 (dest))
                                              ^
fileop.c:127:6: note: to match this '('
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/secure/_strings.h:53:26: note: expanded from macro 'bzero'
                __builtin___memset_chk (dest, 0, __VA_ARGS__, __darwin_obsz0 (dest))
                                       ^
fileop.c:127:6: error: conflicting types for '__builtin___memset_chk'
void bzero();
     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/secure/_strings.h:53:3: note: expanded from macro 'bzero'
                __builtin___memset_chk (dest, 0, __VA_ARGS__, __darwin_obsz0 (dest))
                ^
fileop.c:127:6: note: '__builtin___memset_chk' is a builtin with type 'void *(void *, int, unsigned long, unsigned long)'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/secure/_strings.h:53:3: note: expanded from macro 'bzero'
                __builtin___memset_chk (dest, 0, __VA_ARGS__, __darwin_obsz0 (dest))
                ^
4 errors generated.
make: *** [fileop_macosx.o] Error 1
make: *** Waiting for unfinished jobs....
clang -c -O -Dunix -Dbsd4_2 -DIOZ_macosx -DHAVE_ANSIC_C -DNO_THREADS \
		-DSHARED_MEM  libbif.c -o libbif.o
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Don't know why the author wants to have `bzero` prototype defined by hand, but it shouldn't be.

```
diff -pur a/src/current/fileop.c b/src/current/fileop.c
--- a/src/current/fileop.c	2017-09-14 20:33:03.000000000 +0200
+++ b/src/current/fileop.c	2017-09-18 10:16:53.000000000 +0200
@@ -124,7 +124,6 @@ void file_unlink(int);
 void file_read(int);
 void splash(void);
 void usage(void);
-void bzero();
 void clear_stats();
 int validate(char *, int , char );
 
```

I reported the issue and patch by email to capps@iozone.org

**Pull request closed without merging**
