### PR TITLE
dolt v0.22.11

### PR DESCRIPTION
**Pull request by oscarbatori**

### CODE REVIEW

**Comment by chenrui333** [comment]
see #68827

**Comment by oscarbatori** [comment]
@chenrui333 we have merged [this](https://github.com/dolthub/dolt/pull/1180). Thank you for that!

Can you merge the above so that our latest release gets into Homebrew?

**Comment by chenrui333** [comment]
> @chenrui333 we have merged [this](https://github.com/dolthub/dolt/pull/1180). Thank you for that!
> 
> Can you merge the above so that our latest release gets into Homebrew?

yeah, totally. thanks for the turnaround.

**Review by chenrui333 — APPROVED** [review]

**Comment by oscarbatori** [comment]
Thanks so much @chenrui333, thanks again for the PR!

**Pull request closed without merging**
