### PR TITLE
aws-nuke 2.23.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not marked as latest: https://github.com/rebuy-de/aws-nuke/releases

**Comment by SMillerDev** [comment]
Should have the livecheck updated then

**Comment by chenrui333** [comment]
I think this is more of a label thing, let me raise it up.

image
image

**Comment by chenrui333** [comment]
latest release now 🎉 
image

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
