### PR TITLE
PcapPlusPlus 23.09

### PR DESCRIPTION
**Pull request by egecetin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by egecetin** [comment]
Does anyone have any idea for why the test application fails with following errors for MacOS 13 and 14 (it passes in MacOS 12 CI and in my local linux),

```
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/cstddef:46:5: error: <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
  #   error <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header. \
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/cstddef:59:9: error: no member named 'nullptr_t' in the global namespace
  using ::nullptr_t;
```

I tried compile with and without framework flags, explicitly set C+11 but still can't solve the issue. Any help appreciated

**Comment by MikeMcQuaid** [comment]
> Does anyone have any idea for why the test application fails with following errors for MacOS 13 and 14 (it passes in MacOS 12 CI and in my local linux),

Sounds like a missing header inclusion or similar. @fxcoudert may know.

**Comment by fxcoudert** [comment]
To figure out, one would need to see how the compiler was called (command line that generated this error).

**Comment by egecetin** [comment]
@fxcoudert Added verbose flag to CMake. Compile command of the failing line from the CI of MacOS 14,

https://github.com/Homebrew/homebrew-core/actions/runs/6385242420/job/17329629985#step:3:89

` /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -isystem /opt/homebrew/include/pcapplusplus -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include -Os -w -pipe  -mmacosx-version-min=14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -std=gnu++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -MD -MT CMakeFiles/test.dir/test.cpp.o -MF CMakeFiles/test.dir/test.cpp.o.d -o CMakeFiles/test.dir/test.cpp.o -c /tmp/pcapplusplus-test-20231002-6601-jt8nec/test.cpp`

**Comment by fxcoudert** [comment]
See:

```
meau /tmp $ cat a.cpp                                                                                  
#include <cstddef>

meau /tmp $ clang++ a.cpp -c                                                                           
meau /tmp $ clang++ a.cpp -c -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include    
In file included from a.cpp:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:46:5: error: <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
#   error <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header. \
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:59:9: error: no member named 'nullptr_t' in the global namespace
using ::nullptr_t;
      ~~^
2 errors generated.
```

So adding `-isystem` in this case made the order of the headers include go wrong. You should probably figure out what adds this flag.

**Comment by fxcoudert** [comment]
Or should `#include "stdlib.h"` in the test be `#include <cstdlib>` ?

**Comment by egecetin** [comment]
@MikeMcQuaid @fxcoudert Looks like I managed the solve the issue by adding following line to CMakeLists,

`set_target_properties(test PROPERTIES NO_SYSTEM_FROM_IMPORTED ON)`

This property replaces `-isystem` flag with standard `-i` but to be honest still I don't have any idea why it failed without this option. I used a simple CMake file so most of the options were default. There are different formulas in brew, uses CMake based test applications already merged (this means passed checks) not sets this property and not encountered this error 🤔.

Thanks for your help!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @egecetin!

**Pull request merged**
