### PR TITLE
xxh 0.8.3

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Should/can any of the resources be updated?

**Comment by dtrodrigues** [comment]
They're all up to date here. In general, should resources be bumped when an overall formula is updated? Across all formulae, there's a ton of resources that can/probably should be updated, but I didn't want to spam updates.

**Comment by SMillerDev** [comment]
Yeah, on every update with resources you should check if they're still "good".

**Review by chenrui333 — APPROVED** [review]
:shipit:

**Comment by chenrui333** [comment]
@dtrodrigues, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
