### PR TITLE
taskell 1.7.2

### PR DESCRIPTION
**Pull request by smallhadroncollider**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
13:26:54 src/App.hs:129:13: error:
13:26:54     • Couldn't match type ‘IO’ with ‘EventM ResourceName’
13:26:54       Expected type: EventM ResourceName Int
13:26:54         Actual type: IO Int
13:26:54     • In the expression:
13:26:54         snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
13:26:54       In an equation for ‘getHeight’:
13:26:54           getHeight
13:26:54             = snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
13:26:54     |
13:26:54 129 | getHeight = snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
13:26:54     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:26:54 
13:26:54 src/App.hs:129:40: error:
13:26:54     • Couldn't match type ‘EventM n0’ with ‘IO’
13:26:54       Expected type: IO Graphics.Vty.Output.Interface.Output
13:26:54         Actual type: EventM n0 Graphics.Vty.Output.Interface.Output
13:26:54     • In the second argument of ‘(=<<)’, namely
13:26:54         ‘outputIface <$> getVtyHandle’
13:26:54       In the second argument of ‘(<$>)’, namely
13:26:54         ‘(displayBounds =<< outputIface <$> getVtyHandle)’
13:26:54       In the expression:
13:26:54         snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
13:26:54     |
13:26:54 129 | getHeight = snd <$> (displayBounds =<< outputIface <$> getVtyHandle)
13:26:54     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:26:54 cabal: Leaving directory '.'
13:26:54 cabal: Error: some packages failed to install:
13:26:54 taskell-1.7.2.0-2UkSzuNYApaDVBo7JTnmT8 failed during the building phase. The
13:26:54 exception was:
13:26:54 ExitFailure 1

**Comment by smallhadroncollider** [comment]
Hmm, I wish Homebrew would support Stack builds.

**Comment by chenrui333** [comment]
I am not quite familiar with the haskell build system. Did you see any example of using `Stack` in this repo?

**Comment by smallhadroncollider** [comment]
There's two main ones: Cabal and Stack.

With Cabal you have to declare package versions in a `.cabal` file. With Stack you have a "resolver", which handles all of the package versioning for you (it's got some clever system to make sure they'll all work together).

I use Stack to build taskell, but Homebrew uses Cabal. That means the package versioning gets lost in the process, so the Homebrew build is often using different package versions, which can obviously result in incompatibilities with my code.

I've looked into it and I might be able to update my build script so that it can automatically generate the Cabal package versioning info, which should avoid the issue in the future.

But, it would be nice to just be able to use Stack. When I first wrote the brew recipe all the examples of Haskell packages used Cabal and I think I was recommended not to use Stack, but I can't actually remember. It took me so long to get it working at all, that I was just happy to have it done!

**Pull request closed without merging**
