### PR TITLE
pdns: fix for Xcode 9

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Habbie can we get a new release here please? :)

**Comment by ilovezfs** [comment]
@fxcoudert this should have been scoped.

**Comment by Habbie** [comment]
Wait, this was not merged? Why not?

**Comment by fxcoudert** [comment]
It was: https://github.com/Homebrew/homebrew-core/commit/e1d77729f005d5e3111397f2ccf0da9c35a77e56

**Comment by Habbie** [comment]
Oh sorry, I misread :)

**Pull request closed without merging**
