### PR TITLE
Fix paths for tomcat homebrew

### PR DESCRIPTION
**Pull request by vojkny**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Hmm, I'm not sure this does what we want. Let's try this:
```diff
diff --git a/Formula/tomcat.rb b/Formula/tomcat.rb
index 7d22402f0d..7a3808e571 100644
--- a/Formula/tomcat.rb
+++ b/Formula/tomcat.rb
@@ -18,15 +18,15 @@ class Tomcat < Formula
 
     # Install files
     prefix.install %w[NOTICE LICENSE RELEASE-NOTES RUNNING.txt]
+
+    pkgetc.install Dir["conf/*"]
+    (buildpath/"conf").rmdir
+    libexec.install_symlink pkgetc => "conf"
+
     libexec.install Dir["*"]
     (bin/"catalina").write_env_script "#{libexec}/bin/catalina.sh", JAVA_HOME: Formula["openjdk"].opt_prefix
   end
 
-  def post_install
-    pkgetc.mkpath
-    ln_s pkgetc, libexec/"conf" unless (libexec/"conf").exist?
-  end
-
   def caveats
     <<~EOS
       Configuration files: #{pkgetc}
```

**Comment by knyttl** [comment]
> Hmm, I'm not sure this does what we want. Let's try this:
> 
> ```diff
> diff --git a/Formula/tomcat.rb b/Formula/tomcat.rb
> index 7d22402f0d..529f2eb75c 100644
> --- a/Formula/tomcat.rb
> +++ b/Formula/tomcat.rb
> @@ -5,6 +5,7 @@ class Tomcat < Formula
>    mirror "https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.10/bin/apache-tomcat-10.0.10.tar.gz"
>    sha256 "cd1e27216cd8dad1e9b7f9a0a4107c7148b748eb646f2aee45a11016d1268bb2"
>    license "Apache-2.0"
> +  revision 1
>  
>    bottle do
>      sha256 cellar: :any_skip_relocation, all: "0cdfbbdd72060205ff5346d2046f8369779623221c09ed52c6e990a1c2107752"
> @@ -18,15 +19,15 @@ class Tomcat < Formula
>  
>      # Install files
>      prefix.install %w[NOTICE LICENSE RELEASE-NOTES RUNNING.txt]
> +
> +    pkgetc.install Dir["conf/*"]
> +    (buildpath/"conf").rmdir
> +    libexec.install_symlink pkgetc => "conf"
> +
>      libexec.install Dir["*"]
>      (bin/"catalina").write_env_script "#{libexec}/bin/catalina.sh", JAVA_HOME: Formula["openjdk"].opt_prefix
>    end
>  
> -  def post_install
> -    pkgetc.mkpath
> -    ln_s pkgetc, libexec/"conf" unless (libexec/"conf").exist?
> -  end
> -
>    def caveats
>      <<~EOS
>        Configuration files: #{pkgetc}
> ```

like this?

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Yes. Thanks again, @knyttl!

**Review by carlocab — DISMISSED** [review]
Looks like a GitHub issue. Let's try again in a bit.

**Review by carlocab — DISMISSED** [review]

**Review by SMillerDev — DISMISSED** [review]

**Pull request closed without merging**
