### PR TITLE
hledger 1.16.2

### PR DESCRIPTION
**Pull request by simonmichael**
Update hledger to 1.16.2.

### CODE REVIEW

**Comment by simonmichael** [comment]
Description updated, perhaps @chenrui333 can unblock this if manual action required .

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
all looks good, thanks @simonmichael!!

**Comment by simonmichael** [comment]
@chenrui333: CI has failed because the build command
```
cabal v1-install --jobs=6 --max-backjumps=100000 --only-dependencies hledger hledger-web hledger-ui
```
is selecting a too-old version of brick (0.26 from 2017) instead of a more recent version (like 0.50). It's able to do this because of a problem with bounds in old releases of brick. Here are [more details](https://github.com/jtdaugherty/brick/issues/162#issuecomment-574714852).

Whether or not that gets fixed, cabal v1-install (and v2-install) are always going to be vulnerable to this problem. This isn't the first time it has happened. I think homebrew should consider switching to a stack/stackage-based process, like eg Debian does. Do you think there's a chance of this, or past discussion ?

**Comment by SMillerDev** [comment]
AFAIK there's no past discussion on this and there's a chance only if someone is willing to put in the work. I'm sure pull requests that prevent build failures will happily be reviewed.

**Comment by simonmichael** [comment]
Thanks @SMillerDev, I've begun looking into that. In parallel, I guess I'll need to find a workaround for the cabal install process. Because I suppose if CI can fail, maybe brew install can fail for users, or at least, bottles won't get built. I don't know how hledger passed CI in the past - maybe lucky ?

**Comment by simonmichael** [comment]
The workaround turned out to be pretty easy - please requeue this new commit.

**Comment by simonmichael** [comment]
In case @chenrui333 or anyone might be waiting for the outcome of the stack discussion here - I'm happy for this PR to be merged right away, so that brew users can install the latest hledger.

**Comment by chenrui333** [comment]
@simonmichael the problem is the build failed, and there is no bottles associated with this PR.

If we do the merge, and it would break the installation experience.

**Comment by chenrui333** [comment]
Looks like this PR #49156 suffers the similar cabal build issue too.

**Comment by simonmichael** [comment]
Darn, I guess I (still) don't understand how to update a homebrew package. I thought "you ignore the bottles, just update the rest and a homebrew bot will update the bottles". Back to the docs..

**Comment by issyl0** [comment]
@simonmichael Yes, that's correct - you don't have to touch the bottle lines yourself! But our CI can't build your changes, so the bot can't update the bottles yet. There's some output [here](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/55208/version=catalina/testReport/junit/brew-test-bot/catalina/install___build_bottle_hledger/) that details the failures.

**Comment by simonmichael** [comment]
Apologies, I had pushed to the wrong branch. I've pushed the latest and checks have passed.

**Pull request closed without merging**
