### PR TITLE
git-archive-all 1.19.3

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
```
00:30:05 ==> /usr/local/Cellar/git-archive-all/1.19.3/bin/git-archive-all --dry-run ./archive
00:30:05 Error: git-archive-all: failed
00:30:05 An exception occurred within a child process:
00:30:05   Test::Unit::AssertionFailedError: <"/private/tmp/git-archive-all-test-20181128-12681-2gc7lw/homebrew => archive/homebrew"> expected but was
00:30:05 <"Unable to parse Git version \"Git-113)\".\n/private/tmp/git-archive-all-test-20181128-12681-2gc7lw/homebrew => archive/homebrew">.
00:30:05 
00:30:05 diff:
00:30:05 + Unable to parse Git version "Git-113)".
00:30:05   /private/tmp/git-archive-all-test-20181128-12681-2gc7lw/homebrew => archive/homebrew
```

**Comment by igas** [comment]
https://github.com/Kentzo/git-archive-all/pull/68

**Comment by igas** [comment]
https://github.com/Kentzo/git-archive-all/pull/69

**Comment by igas** [comment]
I could've fix test to check only substring of the output, but let's hope this PR and new version will help.

**Pull request closed without merging**
