### PR TITLE
osquery: vendor Boost 1.65.1

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

remove boost dependency

CC @fxcoudert

### CODE REVIEW

**Comment by ilovezfs** [comment]
Follow-up to https://github.com/Homebrew/homebrew-core/pull/21867

**Comment by ilovezfs** [comment]
Depending on how quickly upstream plans on fixing https://github.com/facebook/osquery/issues/4009 we may want to hold off shipping this.

CC @theopolis

**Comment by theopolis** [comment]
@ilovezfs you may need to remove the vendored Thrift v0.10.0 in the osquery formula and use the 0.11.0 version in Homebrew.

**Comment by ilovezfs** [comment]
@theopolis here's what happens with thrift 0.11.0: https://gist.github.com/ilovezfs/20eeea29e86a535f1d463a41f198792f

**Comment by theopolis** [comment]
Ok @ilovezfs, osquery's `master` should address what you saw in that gist. If master works then I can give it a pre-release tag.

**Comment by theopolis** [comment]
Ok, thanks for testing @ilovezfs, please close this and use https://github.com/facebook/osquery/releases/tag/2.11.1 for the `osquery` formula, removing the vendored `thrift`.

And thanks again for maintaining the Formula!

**Comment by ilovezfs** [comment]
@theopolis you're welcome! Should we be at all concerned about not having the thrift patch https://github.com/facebook/osquery/blob/489ec3fc59d8cedc45cbc6392b7ff1c9f2f79903/tools/provision/formula/thrift.rb#L59-L95 ?

**Comment by theopolis** [comment]
No that's OK. You can ignore those patches. The silencing of `EINTR` can be ignored safely. The second is because we don't want to require `python3` libraries.

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/22090.

**Pull request closed without merging**
