### PR TITLE
youtube-dl 2020.11.1.1

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jonchang** [comment]
You just need to update the `url` and `sha256` from the PyPI page. Adding a new `resource` shouldn't be necessary unless the build process has radically changed.

**Comment by robertleeblairjr** [comment]
> You just need to update the `url` and `sha256` from the PyPI page. Adding a new `resource` shouldn't be necessary unless the build process has radically changed.

I didn't add a new resource. I changed the existing one. But, I'll look at the PyPl page.

**Review by chenrui333 — APPROVED** [review]
👍

**Comment by karbassi** [comment]
The original [GitHub org](https://github.com/ytdl-org) notes the website to be `https://yt-dl.org/`

@robertleeblairjr @chenrui333 @jonchang

**Comment by DesWurstes** [comment]
Also the head is now at: https://gitlab.com/dstftw/youtube-dl

**Comment by robertleeblairjr** [comment]
> The original [GitHub org](https://github.com/ytdl-org) notes the website to be `https://yt-dl.org/`
> 
> @robertleeblairjr @chenrui333 @jonchang

Just checked and they both are owned URLs. I guess either one is fine? But, feel free to change it back. I didn't check that 'https://yt-dl.org/' was still active.

**Comment by robertleeblairjr** [comment]
> Also the head is now at: https://gitlab.com/dstftw/youtube-dl

Yep. I saw that when I was first looking for info on where the repo had moved. Feel free to add a header reference. It didn't have one before.

**Pull request closed without merging**
