### PR TITLE
zabbix: fix Support SQLite databases.

### PR DESCRIPTION
**Pull request by chickenriggies**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
 depends_on :postgresql if build.without? "mysql"
```
may want to also check for sqlite there

**Comment by MikeMcQuaid** [comment]
May also want to `odie` if more than one is specified.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by binkley** [comment]
Is there some other resolution for updating sqlite?

```
checking whether we are cross compiling... configure: error: in `/private/tmp/sqlite-20170202-19542-17q9m39/sqlite-autoconf-3160200':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
zabbix: fix Support SQLite databases. https://github.com/Homebrew/homebrew-core/pull/6982
```

**Comment by mrcsparker** [comment]
@binkley I uninstalled sqlite and then reinstalled and it upgraded fine.

**Comment by binkley** [comment]
@mrcsparker Reinstalling `sqlite` did the trick -- thanks!

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
