### PR TITLE
duck 8.4.4.38366

### PR DESCRIPTION
**Pull request by dkocher**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by carlocab** [comment]
Tried updating `jna` to `5.12.1` but that caused the build to fail.

**Comment by carlocab** [comment]
Not sure why, since you seem to be using 5.12.1: https://github.com/iterate-ch/cyberduck/blob/89bf82c9d89b6451e87aab370c46cd2b7b19766a/pom.xml#L80

**Comment by carlocab** [comment]
`mvn` fails at building `libcore` with
```
[[1;34mINFO[m]      [exec] The following build commands failed:
[[1;34mINFO[m]      [exec] 	CompileC /private/tmp/duck-20220915-5259-dd7ox9/core/dylib/target/Cyberduck.build/Release/libcore.build/Objects-normal/x86_64/WorkspaceSchemeHandlerProxy.o /tmp/duck-20220915-5259-dd7ox9/core/src/main/objc/WorkspaceSchemeHandlerProxy.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by dkocher** [comment]
> Not sure why, since you seem to be using 5.12.1: https://github.com/iterate-ch/cyberduck/blob/89bf82c9d89b6451e87aab370c46cd2b7b19766a/pom.xml#L80
> 
> Ah, it succeeded on ARM, but not on Catalina.

Possibly because we rely on JNA dynamic library dependencies as a single file as in https://github.com/iterate-ch/cyberduck/blob/89bf82c9d89b6451e87aab370c46cd2b7b19766a/core/dylib/pom.xml#L124-L130

Otherwise when embedding the regular JNA archive with the dynamic libraries included these cannot be properly signed and builds are rejected when notarized.

**Comment by carlocab** [comment]
Hmm, that doesn't explain why it works on ARM Big Sur/Monterey and not on Catalina though.

**Comment by dkocher** [comment]
> Hmm, that doesn't explain why it works on ARM Big Sur/Monterey and not on Catalina though.

if you refer to the compilation failure that is possibly an issue as `WorkspaceSchemeHandlerProxy.m ` uses macOS 12 only API that is wrapped with macro `@available(macOS 12.0, *)` but obviously needs later SDK to compile.

**Comment by carlocab** [comment]
Ah, that'll be why. Looks like we can't build this on Catalina then. Do you know which version of Xcode you require?

**Comment by dkocher** [comment]
> Ah, that'll be why. Looks like we can't build this on Catalina then. Do you know which version of Xcode you require? We have Xcode 12.4 on Catalina but that failed.

According to [Minimum requirements and supported SDKs](https://developer.apple.com/support/xcode/) that would need to be Xcode 13.1+.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
