### PR TITLE
subversion: fix `python3` references.

### PR DESCRIPTION
**Pull request by miles170**
See #110462.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by miles170** [comment]
`/tmp/subversion-20220913-21862-vaqme0/subversion-1.14.2/libtool: line 1763: gcc-5: command not found`

**Comment by danielnachun** [comment]
Is `libtool` hardcoding `gcc-5` here?  I'll see if a rebuild fixes this, but I would have expected more failures by now if that was really the culprit.

**Comment by miles170** [comment]
I couldn't reproduce the error in `ghcr.io/homebrew/ubuntu22.04:master`, failed at `Failed to execute: scons`

**Comment by miles170** [comment]
I have already traced it to `build/get-py-info.py --compile` which calls

```python
sysconfig.get_config_vars('CC')
```

returns `['gcc-5 -pthread']`.

**Comment by carlocab** [comment]
The hard-coded `gcc-5` comes from `python@3.10`. Should be fixed by #109777.

**Comment by miles170** [comment]
Rerun CI tests with Python 3.10.7 (#109777).

**Comment by miles170** [comment]
> subversion perl test failed
> 
> `Can't locate SVN/Client.pm in @INC (you may need to install the SVN::Client module)`

On homebrew/ubuntu22.04:master, the perl library is installed at `/home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2/lib/site_perl/5.34.0/x86_64-linux-thread-multi` rather than `/home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi`.

**Comment by carlocab** [comment]
Let's align those paths to make the difference easier to spot:
```
/home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2/lib/site_perl/5.34.0/x86_64-linux-thread-multi
/home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi
```
CC @danielnachun since you fixed a bunch of these `perl` paths recently.

**Comment by miles170** [comment]
> Let's align those paths to make the difference easier to spot:
> 
> ```
> /home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2/lib/site_perl/5.34.0/x86_64-linux-thread-multi
> /home/linuxbrew/.linuxbrew/Cellar/subversion/1.14.2/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi
> ```
> 
> CC @danielnachun since you fixed a bunch of these `perl` paths recently.

tracked down to
```
Prefixing sitearch                                                                                                                                           
  prefixify installsitearch => /home/linuxbrew/.linuxbrew/Cellar/perl/5.34.0_1/lib/perl5/site_perl/5.34/x86_64-linux-thread-multi                            
    from /home/linuxbrew/.linuxbrew/opt/perl to $(SITEPREFIX)                                                                                                
    cannot prefix, using default.                                                                                                                            
    now $(SITEPREFIX)/lib/site_perl/5.34.0/x86_64-linux-thread-multi                                                                                         
  INSTALLSITEARCH == $(SITEPREFIX)/lib/site_perl/5.34.0/x86_64-linux-thread-multi 
```

**Comment by carlocab** [comment]
So, do we just need to set `INSTALLSITEARCH` on Linux? Having to do this manually is a bit of a mess...

**Comment by miles170** [comment]
> So, do we just need to set `INSTALLSITEARCH` on Linux? Having to do this manually is a bit of a mess...

The root cause was a different `$Config{installstyle}` since we uses system perl on macOS.

# arm64 (macOS Monterey)

```bash
$ perl -MConfig -e 'print $Config{installstyle}'
lib/perl5
```

# amd64 (homebrew/ubuntu22.04:master)

```bash
$ perl -MConfig -e 'print $Config{installstyle}'
lib
```

**Comment by danielnachun** [comment]
I've rebased this because I think this should work now that we've updated perl to 5.36.

**Review by danielnachun — APPROVED** [review]
The Linux build is now fixed.  This is ready to merge once CI is done.

**Pull request merged**
