### PR TITLE
gauge 0.9.1

### PR DESCRIPTION
**Pull request by gaugeci**
Created with `brew bump-formula-pr`.

---

Created by a bot. Please cc `@getgauge/core` if issue(s) crop up

### CODE REVIEW

**Review by fxcoudert — CHANGES_REQUESTED** [review]
Can we update `gauge_screenshot` to the latest revision, i.e. `f16bcf089e263db525a255c9f9621ca0270ff1d3`?

**Comment by ilovezfs** [comment]
@sriv should we close this as well?

**Comment by sriv** [comment]
@ilovezfs - I guess so :) I wonder if `brew bump-formula-pr` can handle this use case? I believe not, but would like to confirm.

**Comment by ilovezfs** [comment]
@sriv bump-formula-pr will preserve local edits to the formula file so it's sort of possible. But ideally gauge should vendor all of its resources so that this isn't an issue.

**Comment by ilovezfs** [comment]
@sriv specifically I mean in a Go `vendor/` directory, or in git submodule, or via `godep` as you're doing for the other resources.

**Comment by sriv** [comment]
@ilovezfs makes sense, thanks.

**Pull request closed without merging**
