### PR TITLE
Quill 1.2.0 (new formula)

### PR DESCRIPTION
**Pull request by odygrd**
[Quill](https://github.com/odygrd/quill) a C++ 14/17 logging library 
 
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you squash your commits?

**Comment by odygrd** [comment]
Squashed them

**Comment by SMillerDev** [comment]
Thanks @odygrd ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by bayandin** [comment]
I've an error for `brew pr-pull`, want to check if it's a bug with this particular build or with `brew pr-pull` 

I will take care of this PR.

```
$ brew pr-pull 53304
==> Fetching homebrew/core pull request #53304
==> Cherry-picking 1 commit from #53304
==> Downloading https://api.github.com/repos/Homebrew/homebrew-core/actions/artifacts/4696165/zip
Already downloaded: /Users/bayandin/Library/Caches/Homebrew/downloads/b5e8d5bfc66223b6278061d92e251f54408b1432815d83f66c3d5b3c8d4365a5--artifact.zip
curl: (22) The requested URL returned error: 404 Not Found
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing; `/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.13-114-g05e66e9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --fail --progress-bar --retry 3 --output /dev/null https://api.bintray.com/packages/homebrew/bottles/quill` exited with 22. Here's the output:
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by Bo98** [comment]
Could be something weird with Bintray. Does `--verbose` reveal more?

**Comment by bayandin** [comment]
> Could be something weird with Bintray. Does `--verbose` reveal more?

I think the same as a message before (https://api.bintray.com/packages/homebrew/bottles/quill returns `{"message":"Package 'quill' was not found"}`):

```
$ brew pr-pull -v 53304
==> Fetching homebrew/core pull request #53304
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --quiet --force origin +refs/pull/53304/head
==> Cherry-picking 1 commit from #53304
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core cherry-pick --ff --allow-empty 1efbadc543b89e02e25a3fbe8d18660b1b3c7cde..FETCH_HEAD
[master 427bf57ab7] Quill 1.2.0
 Author: Odysseas Georgoudis <odygrd@gmail.com>
 Date: Sat Apr 18 17:12:14 2020 +0100
 1 file changed, 38 insertions(+)
 create mode 100644 Formula/quill.rb
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core commit --amend --signoff --allow-empty -q -m Quill 1.2.0


Closes #53304.
==> Downloading https://api.github.com/repos/Homebrew/homebrew-core/actions/artifacts/4696165/zip
Already downloaded: /Users/bayandin/Library/Caches/Homebrew/downloads/b5e8d5bfc66223b6278061d92e251f54408b1432815d83f66c3d5b3c8d4365a5--artifact.zip
unzip -o /Users/bayandin/Library/Caches/Homebrew/downloads/b5e8d5bfc66223b6278061d92e251f54408b1432815d83f66c3d5b3c8d4365a5--artifact.zip -d /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f
cp -pR /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f/quill--1.2.1.mojave.bottle.json /private/var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/5330420200421-79902-l0vlbr/quill--1.2.1.mojave.bottle.json
cp -pR /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f/quill--1.2.1.catalina.bottle.json /private/var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/5330420200421-79902-l0vlbr/quill--1.2.1.catalina.bottle.json
cp -pR /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f/quill--1.2.1.mojave.bottle.tar.gz /private/var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/5330420200421-79902-l0vlbr/quill--1.2.1.mojave.bottle.tar.gz
cp -pR /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f/logs/. /private/var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/5330420200421-79902-l0vlbr/logs
cp -pR /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f/quill--1.2.1.catalina.bottle.tar.gz /private/var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/5330420200421-79902-l0vlbr/quill--1.2.1.catalina.bottle.tar.gz
cp -pR /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f/quill--1.2.1.high_sierra.bottle.tar.gz /private/var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/5330420200421-79902-l0vlbr/quill--1.2.1.high_sierra.bottle.tar.gz
cp -pR /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f/quill--1.2.1.high_sierra.bottle.json /private/var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/5330420200421-79902-l0vlbr/quill--1.2.1.high_sierra.bottle.json
chmod -Rf +w /var/folders/v5/ly_6fqkn1_l7g5w7lmwm_qlh0000gn/T/d20200421-79902-4qzh8f
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    43  100    43    0     0     76      0 --:--:-- --:--:-- --:--:--    76
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  352k  100    44  100  352k     16   134k  0:00:02  0:00:02 --:--:--  134k
{"message":"Failed to resolve package name"}curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    43  100    43    0     0     81      0 --:--:-- --:--:-- --:--:--    81
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  352k  100    44  100  352k     16   132k  0:00:02  0:00:02 --:--:--  132k
{"message":"Failed to resolve package name"}curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    43  100    43    0     0     80      0 --:--:-- --:--:-- --:--:--    80
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  357k  100    44  100  357k     16   137k  0:00:02  0:00:02 --:--:--  136k
{"message":"Failed to resolve package name"}  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    43  100    43    0     0     76      0 --:--:-- --:--:-- --:--:--    76
{"message":"Package 'quill' was not found"}
```

Do we create a new package on bintray during the build or during package publishing?
(haven't try `brew pr-publish` because want to see if it's a bug with `brew pr-pull`)

**Comment by Bo98** [comment]
Package creation is handled here: https://github.com/Homebrew/brew/blob/1147106/Library/Homebrew/bintray.rb#L115-L119. It is done on pr-pull.

**Comment by bayandin** [comment]
It seems I found a reason, will create a PR soon

**Pull request closed without merging**
