### PR TITLE
bareos-client: update and fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I'm not sure why we were on such an old version before, though it appears that upstream may be supporting multiple major versions simultaneously.

I had to disable building the Python bindings because they try to install into the `python@3.10` keg instead of the formula's own keg, which will fail due to lack of permissions (as intended).  I believe this was not a problem before either because the bindings were automatically disabled, or used the system Python 2 and installed somewhere it had permission to modify.

**Comment by cho-m** [comment]
I have a PR to update and fix build Apple Silicon & Linux build in #98016, though with only bare feature set.

Was still pending on fixing static linkage to `readline` and need to look into upstreaming inreplaces for ARM's non-default prefix.

I had also disabled Python due to lacking any option to remove Python2 without patching build scripts.

**Comment by danielnachun** [comment]
I'll close this for now!

**Comment by cho-m** [comment]
I can try merging some of your changes, though may need extra inreplaces since upstream keeps forcing static libraries on macOS like `lzo` (https://github.com/bareos/bareos/blob/Release/21.1.2/core/cmake/BareosFindAllLibraries.cmake#L187)

If I had to guess, Python 3.10 issue may be related to prefix scheme change that is not present in Python 3.9 and older. I can try taking a look after patching out Python 2 code, which is causing issues for my local Monterey testing.

**Pull request closed without merging**
