### PR TITLE
gdal 3.0.2

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> python3 -c import gdal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/usr/local/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/usr/local/lib/python3.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/osgeo/_gdal.cpython-37m-darwin.so, 2): Symbol not found: _curl_mime_addpart
  Referenced from: /usr/local/Cellar/gdal/3.0.2/lib/libgdal.26.dylib
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/gdal/3.0.2/lib/libgdal.26.dylib
```

**Comment by Bo98** [comment]
`curl_mime_addpart` is only available in system curl shipped with Catalina and later. The fix will be similar to `git` (#46474):

```ruby
if MacOS.version == :mojave && MacOS::CLT.installed?
  ENV["HOMEBREW_SDKROOT"] = MacOS::CLT.sdk_path(MacOS.version)
end
```

Not tested might need tweaking if `HOMEBREW_SDKROOT` doesn't work.

**Comment by Bo98** [comment]
Let me know if you plan to deal with this before or after 3.8. Just trying to keep track of open Python pull requests.

**Comment by bayandin** [comment]
> Let me know if you plan to deal with this before or after 3.8. Just trying to keep track of open Python pull requests.

I think I'll try to sort it out after Python 3.8, thanks!

**Comment by bayandin** [comment]
- `mapnik` the same as https://github.com/Homebrew/homebrew-core/pull/48349#issuecomment-569488295:
> * `mapnik` needs [mapnik/mapnik#4094](https://github.com/mapnik/mapnik/pull/4094) and [mapnik/mapnik#4103](https://github.com/mapnik/mapnik/pull/4103) 

- `liblas` fails with https://github.com/libLAS/libLAS/issues/164 (`liblas` 1.8.1 incompatible with `gdal` >=2.5.0)

**Pull request closed without merging**
