### PR TITLE
git-annex 10.20230126

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Error: cabal: Failed to build git-annex-10.20230126. The failure occurred
  during the configure step. The exception was:
  /private/tmp/git-annex-20230126-60354-3rfcx4/git-annex-10.20230126/.brew_home/.cabal/logs/ghc-9.2.5/gt-nnx-10.20230126-b4011ef4.log:
  withFile: user error (Error: cabal: '/opt/homebrew/opt/ghc@9.2/bin/ghc' exited
  with an error:
  
  /private/tmp/cabal-install.-60458/dist-newstyle/tmp/src-60458/git-annex-10.20230126/Utility/Process.hs:48:1:
  error:
  Could not load module ‘Control.Concurrent.Async’
  It is a member of the hidden package ‘async-2.2.4’.
  Perhaps you need to add ‘async’ to the build-depends in your .cabal file.
  it is a hidden module in the package ‘tasty-1.4.3’
  Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
  48 | import Control.Concurrent.Async
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  )
```

**Comment by p-linnane** [comment]
@cho-m Can you lend your Haskell experience here please?

**Comment by p-linnane** [comment]
Closing as there is no progress on this one.

**Comment by yarikoptic** [comment]
May be @joeyh has an idea?

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/123142

**Pull request closed without merging**
