### PR TITLE
borg: use GitHub for homepage

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
Reported https://github.com/ok-borg/borg/issues/52

**Comment by crufter** [comment]
The problem is not actually with the frontend, that could be on github. But the server is also down. Will fix after work.

**Comment by ilovezfs** [comment]
@crufter thanks

**Comment by ilovezfs** [comment]
@crufter hmm it still seems to be down.

**Pull request closed without merging**
