### PR TITLE
ponyc: depend on llvm@3.7

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

CC @SeanTAllen

### CODE REVIEW

**Review by ilovezfs — COMMENTED** [review]
Upstream hasn't decided if they want this to ship yet so let's not merge on a dime.

**Comment by ilovezfs** [comment]
Cf. https://github.com/ponylang/ponyc/issues/1483#issuecomment-286739968

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by SeanTAllen** [comment]
No reason to do this @ilovezfs both 3.7 and 3.8 have the crashing bug and 3.9 doesn't. So no reason to change from 3.8 to 3.7 as it won't fix the issue.

**Comment by ilovezfs** [comment]
OK. I'll eagerly await the fix for 4.0.

**Pull request closed without merging**
