### PR TITLE
node@15 15.14.0 (new formula)

### PR DESCRIPTION
**Pull request by derrabus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Follow-up to #75595

`brew audit --strict node@15` complains about a naming conflict with the alias of the same name, but that will go away as soon as #75595 is merged.

### CODE REVIEW

**Comment by carlocab** [comment]
Do we need a `node@15`? We typically only keep versioned formulae if they're either a) still maintained, or b) needed by other formulae.

My understanding of the node version scheme is that `node@15` will no longer be maintained, and I'm not sure other formulae will need this.

**Comment by derrabus** [comment]
Node 15 will be maintained until June 1st, see https://nodejs.org/en/about/releases/

But that is of course a very short period of time. I would totally understand if the Homebrew projects decides against adding a dedicated `node@15` formula.

**Comment by carlocab** [comment]
Do you think users will find it useful? If there's a genuine use for it that you can't get for some reason with `node@14` and `node@16`, then I won't be opposed to it. (I don't speak for other maintainers here though.)

If we do add it, though, we should probably already add the `deprecate!` line for when it's no longer supported.

**Comment by carlocab** [comment]
It looks like some formulae failed the tests at #75595, so it may well be that they do need `node@15`.

**Comment by derrabus** [comment]
> Do you think users will find it useful? If there's a genuine use for it that you can't get for some reason with `node@14` and `node@16`, then I won't be opposed to it. (I don't speak for other maintainers here though.)

If you look at the test failure of the node 16 bump, you can see at least one formula that is apparently not yet ready for node 16. Keeping Node 15 for a little while might smoothen the transition.

> If we do add it, though, we should probably already add the `deprecate!` line for when it's no longer supported.

I've added this already.

**Comment by Bo98** [comment]
Honestly, I'd rather just make `jhipster` depend on `node@14`.

Node 15 will only last another month while if we introduce this formula would have to go through the full deprecation -> disabled -> removal process which takes much, much longer.

**Comment by derrabus** [comment]
All right, let's close this PR then. 😃

**Pull request closed without merging**
