### PR TITLE
John jumbo 1.9.0 openssl@1.1

### PR DESCRIPTION
**Pull request by catap**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by catap** [comment]
Opened a pull request into upstream to fix support not default openssl at homebrew: https://github.com/magnumripper/JohnTheRipper/pull/4101

**Comment by catap** [comment]
Cc: @fxcoudert

**Comment by fxcoudert** [comment]
Can you replace the three patches with `https://github.com/magnumripper/JohnTheRipper/pull/4101.diff?full_index=1`?

**Comment by catap** [comment]
@fxcoudert I don't like this idea because if I made push to this branch I will broke the formula because chechsum will be changed.

**Comment by fxcoudert** [comment]
We'll probably wait until the patch is accepted/merged by upstream, in any case. We'll use the final commit.

**Comment by catap** [comment]
@fxcoudert sure, no rush.

Anyway, I haven't touched autostuff for a years and it was very exceeding :)

**Comment by catap** [comment]
@fxcoudert I can add required patches over `DATA` but it isn't good idea I guess

**Comment by catap** [comment]
@fxcoudert ok, it was merged into upstream => I've moved from 3 patches to 1.

**Pull request closed without merging**
