### PR TITLE
got 0.86

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Encountering a segfault in the test:
```
[1]    62293 segmentation fault  got import -m Initial Commit -r repo.git import-dir
```

**Comment by carlocab** [comment]
Same error as in #125107.

**Comment by carlocab** [comment]
It seems to be segfaulting inside a `strdup` call
```
❯ lldb -- got import -m "initial commit" -r repo.git import-dir
(lldb) target create "got"
Current executable set to 'got' (x86_64).
(lldb) settings set -- target.run-args  "import" "-m" "initial commit" "-r" "repo.git" "import-dir"
(lldb) r
Process 29562 launched: '/usr/local/bin/got' (x86_64)
Process 29562 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007ff80d07c6b2 libsystem_platform.dylib`_platform_strlen + 18
libsystem_platform.dylib`:
->  0x7ff80d07c6b2 <+18>: pcmpeqb (%rdi), %xmm0
    0x7ff80d07c6b6 <+22>: pmovmskb %xmm0, %esi
    0x7ff80d07c6ba <+26>: andq   $0xf, %rcx
    0x7ff80d07c6be <+30>: orq    $-0x1, %rax
Target 0: (got) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00007ff80d07c6b2 libsystem_platform.dylib`_platform_strlen + 18
    frame #1: 0x00007ff80cf346c8 libsystem_c.dylib`strdup + 18
    frame #2: 0x0000000100001f79 got`cmd_import(argc=6, argv=0x00007ff7bfefe398) at got.c:788:13 [opt]
    frame #3: 0x0000000100001c36 got`main(argc=6, argv=0x00007ff7bfefe398) at got.c:260:11 [opt]
    frame #4: 0x00000001000c952e dyld`start + 462
(lldb) up
frame #1: 0x00007ff80cf346c8 libsystem_c.dylib`strdup + 18
libsystem_c.dylib`strdup:
->  0x7ff80cf346c8 <+18>: movq   %rax, %rbx
    0x7ff80cf346cb <+21>: incq   %rbx
    0x7ff80cf346ce <+24>: movq   %rbx, %rdi
    0x7ff80cf346d1 <+27>: callq  0x7ff80cfb5856            ; symbol stub for: malloc
(lldb) up
warning: got was compiled with optimization - stepping may behave oddly; variables may not be available.
frame #2: 0x0000000100001f79 got`cmd_import(argc=6, argv=0x00007ff7bfefe398) at got.c:788:13 [opt]
   785                                  goto done;
   786                          break;
   787                  case 'm':
-> 788                          logmsg = strdup(optarg);
   789                          if (logmsg == NULL) {
   790                                  error = got_error_from_errno("strdup");
   791                                  goto done;
```

**Comment by carlocab** [comment]
Reported upstream at https://lists.openbsd.org/cgi-bin/mj_wwwusr?user=carlo.antonio.cabrera%40gmail.com&passw=E130-0739-9EB1&list=gameoftrees&brief=on&func=archive-get-part&extra=202303/93.

**Comment by carlocab** [comment]
The `tap_syntax` job seems to be stuck on the `Initializing containers` step.

**Comment by carlocab** [comment]
Upstream's fix is more general, but functionally the same for our purposes: https://git.gameoftrees.org/gitweb/?p=got-portable.git;a=commitdiff;h=62f363ce7bf30bd7855ef9d7a54628f64322926e

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
