### PR TITLE
Apache arrow 2.0.0

### PR DESCRIPTION
**Pull request by kszucs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

cc @kou

### CODE REVIEW

**Comment by fxcoudert** [comment]
Holding for #62560

**Comment by kou** [comment]
@kszucs Could you add `-DARROW_S3=ON`?

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Please rebase

**Comment by fxcoudert** [comment]
Revision for `dvc` because of broken linkage

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
