### PR TITLE
bibtexconv 1.1.12

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
SHAsum appears to have changed since you opened the PR :(

**Comment by ilovezfs** [comment]
I just checked and the difference between the original and the new tarball is the addition of one file
```
Josephs-MacBook-Pro:bib joe$ cat new/bibtexconv-1.1.12/website.config 
WEBSITE_DIRECTORY=~/public_html/bibtexconv
WEBSITE_PAGE=index.html
WEBSITE_DATE="`env LANG=en_AU date +"%B %d, %Y"`"
```
I'm not sure what that's about but it doesn't set off any alarm bells for me.

**Comment by ilovezfs** [comment]
Thanks for the help @fxcoudert!

**Comment by ilovezfs** [comment]
uploaded https://dl.bintray.com/homebrew/mirror/bibtexconv-1.1.12.tar.gz just in case someone wants to change it again

**Pull request closed without merging**
