### PR TITLE
protobuf 1.3.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by scpeters** [comment]
The commit message confused me a bit, but this is the `protobuf-gen-go` formula, not protobuf. Our [guide suggests (see number 6)](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#create-your-pull-request-from-a-new-branch): 

our preferred commit message format for simple version updates is “<FORMULA_NAME> <NEW_VERSION>”"

It's just a suggestion for the future. Thanks for your contribution!

**Comment by fxcoudert** [comment]
@chenrui333 see above ^^

@scpeters I realized, and I edited the commit message when I merged: https://github.com/Homebrew/homebrew-core/commit/76dbc635412e94391ef535b0fb5782b7dbd89cc3

**Comment by scpeters** [comment]
thanks @fxcoudert! I only noticed it from the email subject line; thanks for catching it in the commit

**Comment by chenrui333** [comment]
@scpeters Sorry, I missed it. I will pay more close attentions on it.

@fxcoudert thanks for taking care of it!

**Pull request closed without merging**
