### PR TITLE
masscan 1.0.4

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
Failed on `el_capitan` with:
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
```

**Comment by JCount** [comment]
This is an ugly hack, and the issue should be reported to upstream, but the attached patch should fix the formula on El Capitan.

```
diff --git a/Formula/masscan.rb b/Formula/masscan.rb
index a2bdac482c..693a97e3bd 100644
--- a/Formula/masscan.rb
+++ b/Formula/masscan.rb
@@ -14,6 +14,10 @@ class Masscan < Formula
   end
 
   def install
+    if MacOS.version == :el_capitan && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
+      inreplace "src/pixie-timer.c", "#elif defined(CLOCK_MONOTONIC)", "#elif defined(NOT_A_MACRO)"
+    end
+
     system "make"
     bin.install "bin/masscan"
   end
 ```

**Comment by commitay** [comment]
🎉  Thanks @JCount! 

Reported upstream: https://github.com/robertdavidgraham/masscan/issues/284

**Comment by ilovezfs** [comment]
Thanks @commitay!

Please squash this down to one commit and a comment above the string replacement with a link to the upstream issue and the date it was reported. For examples of such comments, see https://gist.github.com/ilovezfs/62a9eb715dc044f7202cbf86caaf713b

**Comment by ilovezfs** [comment]
Thanks @commitay! :rocket:

**Pull request closed without merging**
