### PR TITLE
Istioctl version bump to 1.0.6

### PR DESCRIPTION
**Pull request by murarisumit**
- [] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lembacon** [comment]
Thanks @murarisumit!

**Comment by murarisumit** [comment]
@lembacon was this the right way to bump up the version, or should I be doing something else for it ?

**Comment by lembacon** [comment]
@murarisumit Yes it is. Despite the commit message should be `istioctl 1.0.6`. 😉

**Comment by murarisumit** [comment]
thanks 👍

**Pull request closed without merging**
