### PR TITLE
gwenhywfar: migrate to boneyard

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by chdiza** [comment]
I think that these boneyarding PRs should include, in the commit message, the reason for the boneyarding.

**Comment by ilovezfs** [comment]
Can we use hashtags? #BecauseQt4

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Merged by mistake, reverting.

**Pull request merged**
