### PR TITLE
Deprecate :perl - part 3

### PR DESCRIPTION
**Pull request by commitay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/22771#issuecomment-357302358

**Comment by ilovezfs** [comment]
@DomT4 how's that?

**Comment by DomT4** [comment]
👍 That looks perfect. Exactly how I'd have approached it here.

**Comment by ilovezfs** [comment]
Thanks again @commitay!

**Pull request closed without merging**
