### PR TITLE
emacs 25.1.90 (devel)

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
https://alpha.gnu.org/gnu/emacs/pretest/ returns 404, although alpha.gnu.org uses HSTS.

**Comment by dunn** [comment]
Sweet, thanks!

**Comment by ilovezfs** [comment]
@zmwangx Has the https problem been reported?

**Comment by zmwangx** [comment]
@ilovezfs The official download link (from announcement) is ftp://alpha.gnu.org/gnu/emacs/pretest/emacs-25.1.90.tar.xz, and I don't think https://alpha.gnu.org/gnu/emacs/pretest/ ever worked. So: it's kinda stupid, but nothing was promised in the first place.

**Comment by ilovezfs** [comment]
I think it might be worth raising this with them if you feel like it. I've wasted time on this stupid server too for the same reason.  GNU recently switched everything to https so this may just be an oversight.

**Comment by zmwangx** [comment]
@ilovezfs I sent a bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25056. Never enjoy reporting this sort of logistics problems though.

**Comment by ilovezfs** [comment]
Thanks. Let's see what they say!

**Pull request closed without merging**
