### PR TITLE
libpano: hacks to build on Big Sur

### PR DESCRIPTION
**Pull request by mitchblank**
As described in the comment, there is a long-standing issue with `libtiff` and `Security.framework` defining types of the same name.  This has been reported in multiple forms dating back to at least
*  http://bugzilla.maptools.org/show_bug.cgi?id=2464
*  https://github.com/Homebrew/homebrew-core/issues/36035
And most recently I started a discussion as part of a related closed bug:
*  https://gitlab.com/libtiff/libtiff/-/merge_requests/51#note_476410984

This is now biting `libpano` on Big Sur, apparently because some system header is newly sucking in that `Security.framework` header.  As a hopefully-temporary hack we can use the preprocessor to change that symbol name (but only while processing `libtiff` headers)

The long-term fix will probably be for `libtiff` not avoid these common names, but that discussion is ongoing.  This fixes a formula build in the short/medium term.

NOTE: I realize that this might be flirting with the limits of how icky a workaround can be and still be allowed in a formula, but I wanted to at least get a PR open for discussion... not least with the `libtiff` folks

### CODE REVIEW

**Comment by mitchblank** [comment]
Well it looks like that fixed 11.0 but broke earlier:
```
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.   -I/usr/local/include -DHasJPEG -I/usr/local/include -DHasPNG -I/usr/local/include -DHasTIFF -DHasZLIB   -D__Ansi__=1     -g -O2 -c -o pan.lo pan.c
file.c:769:5: error: unknown type name 'uint32'; did you mean 'uint32_t'?
    uint32           len;
    ^~~~~~
    uint32_t
```
... so I'll have to make that change conditional I guess, since it seems that some code in libpano actually relies on *somebody* defining those "uint32" etc types

**Comment by fxcoudert** [comment]
That's way to much of a hack for a seldom-used formula. We have to let some of those die, if they're not maintained. Otherwise, we become _de facto_ maintainers, and we don't want that.

So, with many thanks for your very appreciated pull requests @mitchblank… on such occasions, maybe don't try too hard :)

**Comment by mitchblank** [comment]
Well, I'll leave it to you guys to decide on the fate of formulae.  I have just been going through the list and trying to solve their problems... especially since the same class of problem pops up over and over.

fwiw this formula is also a dependency of `autopano-sift-c`, although that's also pretty rarely installed.

**Comment by SMillerDev** [comment]
Should be disabled IYAM

**Comment by ThinkDigitalSoftware** [comment]
> Well, I'll leave it to you guys to decide on the fate of formulae. I have just been going through the list and trying to solve their problems... especially since the same class of problem pops up over and over.
> 
> fwiw this formula is also a dependency of `autopano-sift-c`, although that's also pretty rarely installed.

Putting in my vote for installing autopano-sift-c being the reason I'm here

**Pull request closed without merging**
