### PR TITLE
txr: disable

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Eww, a `#define noreturn` in a header (`lib.h`), which ends up messing with system headers:

```
In file included from lex.yy.c:3718:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:429:18: error: use of undeclared identifier 'noreturn'
void     _exit(int) __dead2;
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:155:40: note: expanded from macro '__dead2'
#define __dead2         __attribute__((noreturn))
                                       ^
./lib.h:60:33: note: expanded from macro 'noreturn'
#define noreturn __attribute__((noreturn))
                                ^
```

`__attribute__((__attribute__((noreturn))))`

**Comment by chenrui333** [comment]
There is a new release for v238

**Comment by issyl0** [comment]
Let's try 238. It worked locally.

**Comment by Bo98** [comment]
Thanks! Been a bit busy these past 3 weeks so have neglected some PRs.

**Comment by alebcay** [comment]
`txr` 239 is now available.

**Comment by alebcay** [comment]
`txr` 240 is now available.

**Comment by chenrui333** [comment]
tag it as `almost there`, so that we periodically check the PR.

**Comment by jonchang** [comment]
Upstream git repo and tarball leads to a parked domain, so let's disable this formula.

**Pull request merged**
