### PR TITLE
ejabberd 16.04

### PR DESCRIPTION
**Pull request by marktran**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by marktran** [comment]
I removed all of the resources because the build script will actually download any needed dependencies so it isn't necessary to maintain it in the formula.

**Comment by DomT4** [comment]
> I removed all of the resources since the build script will actually download any needed dependencies.

We'd prefer the current system.

We don't knowingly permit build scripts to fetch dependencies on the fly because it breaks caching for users, and often upstreams perform a lesser level of verification in terms of tags matching expected commits, etc than we do.

**Comment by marktran** [comment]
Ok, I'll update this shortly with the latest dependencies since they've changed a bit from the previous version.

**Comment by marktran** [comment]
Added the resources back with the latest dependencies.

**Comment by nijikon** [comment]
@marktran Can you please squash this to one commit?

**Comment by MikeMcQuaid** [comment]
@nijikon Probably worth just doing that locally when we pull.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
