### PR TITLE
node 11 (version)

### PR DESCRIPTION
**Pull request by joshmedeski**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chrmoritz** [comment]
Node 11.15.0 is the latest `node@11` version released yesterday. However please not that node 11 isn't a LTS version and will be in Maintenance (security fixes only) mode after this last minor update until the end of June, when it finally becomes End of Life. This would also be the first time that we'd create a versioned formula for an odd node release.

**Comment by joshmedeski** [comment]
I decided to use `nvm` to support one old project that won't support Node v12. Like @chrmoritz mentioned, if there's no LTS then maybe adding this isn't a good idea. I'll let the maintainers decide :)

**Comment by fxcoudert** [comment]
@joshmedeski I suggest you maintain this in a personal tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
It's probably not a good fit for Homebrew core, for the reasons detailed by @chrmoritz

**Comment by joshmedeski** [comment]
I agree, thanks @fxcoudert!

**Pull request closed without merging**
