### PR TITLE
yarn-completion 0.14.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
19:33:23 ==> source /usr/local/Cellar/yarn-completion/0.14.0/etc/bash_completion.d/yarn && complete -p yarn
19:33:23 /usr/local/Cellar/yarn-completion/0.14.0/etc/bash_completion.d/yarn: line 239: syntax error near unexpected token `('
19:33:23 /usr/local/Cellar/yarn-completion/0.14.0/etc/bash_completion.d/yarn: line 239: `		<(echo "${flags[@]}" "${global_flags[@]}" | tr ' ' '\n' | LC_ALL=C sort -u) \'
19:33:23 Error: yarn-completion: failed
19:33:23 An exception occurred within a child process:
19:33:23   Test::Unit::AssertionFailedError: <0> expected but was
19:33:23 <1>.
19:33:23 /Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:55:in `block in assert_block'
19:33:23 /Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1632:in `_wrap_assertion'
19:33:23 /Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:53:in `assert_block'
19:33:23 /Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:240:in `assert_equal'
19:33:23 /usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:13:in `shell_output'
19:33:23 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarn-completion.rb:15:in `block in <class:YarnCompletion>'
```

**Comment by chenrui333** [comment]
Filed a bug report.

**Comment by igas** [comment]
Thanks @chenrui333. I'll close this one with the upstream issue. When it's resolved let's do a new one.

**Comment by chenrui333** [comment]
Sounds good, thanks!

**Pull request closed without merging**
