### PR TITLE
Envoy 1.20

### PR DESCRIPTION
**Pull request by codefromthecrypt**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@chenrui333 you might notice from the commits here that  #86741 is missing some steps including updating the alias and bumping the minor versions. that's why I don't use bump automation yet..

**Comment by codefromthecrypt** [comment]
It will take a while for me to mark this ready for review as I need to test locally and envoy takes ages to build. Here's what I am doing:

```bash
$ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
$ gh pr checkout 86755
$ brew install --build-from-source envoy@1.19
$ envoy version
$ brew install --build-from-source envoy
$ envoy version
```

**Comment by codefromthecrypt** [comment]
Envoy still doesn't build on M1 due to an unmerged Bazel-related change, so it will continue to fail here. I would also warn that even if merged, typically Envoy doesn't backport build-related stuff to release branches, so it might not effect anything until 1.21 or later https://github.com/envoyproxy/envoy/pull/17438

**Comment by codefromthecrypt** [comment]
Ran the following and it all worked, except a warning about patches in new formula. I looked and found the patch did seem to land in 1.20, so running the below again, and if they pass will mark ready for review.

```bash
$ brew install --build-from-source envoy
$ brew test envoy
$ brew audit --strict envoy
$ brew audit --new envoy
$ envoy --version
```

**Comment by codefromthecrypt** [comment]
another one for you @carlocab 😎

**Comment by codefromthecrypt** [comment]
nm @cho-m I found the part I missed

```
  on_linux do
    # GCC added as a test dependency to work around Homebrew issue. Otherwise `brew test` fails.
    # CompilerSelectionError: envoy cannot be built with any available compilers.
    depends_on "gcc@9" => [:build, :test]
    depends_on "python@3.9" => :build
  end
```

**Comment by codefromthecrypt** [comment]
Current failure looks like `tar` for go isn't found, or the file it is looking for isn't found. It seems unlikely `tar` is missing.

```
INFO: Repository go_sdk instantiated at:
  /tmp/envoyA1.19-20211009-12166-1s4jbbp/WORKSPACE:21:25: in <toplevel>
  /tmp/envoyA1.19-20211009-12166-1s4jbbp/bazel/dependency_imports.bzl:19:27: in envoy_dependency_imports
  /tmp/envoyA1.19-20211009-12166-1s4jbbp/.brew_home/_bazel/32ea98d9ad756d02b6517b5463b86b30/external/io_bazel_rules_go/go/private/sdk.bzl:453:28: in go_register_toolchains
  /tmp/envoyA1.19-20211009-12166-1s4jbbp/.brew_home/_bazel/32ea98d9ad756d02b6517b5463b86b30/external/io_bazel_rules_go/go/private/sdk.bzl:129:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /tmp/envoyA1.19-20211009-12166-1s4jbbp/.brew_home/_bazel/32ea98d9ad756d02b6517b5463b86b30/external/io_bazel_rules_go/go/private/sdk.bzl:116:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/tmp/envoyA1.19-20211009-12166-1s4jbbp/.brew_home/_bazel/32ea98d9ad756d02b6517b5463b86b30/external/io_bazel_rules_go/go/private/sdk.bzl", line 100, column 16, in _go_download_sdk_impl
		_remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
	File "/tmp/envoyA1.19-20211009-12166-1s4jbbp/.brew_home/_bazel/32ea98d9ad756d02b6517b5463b86b30/external/io_bazel_rules_go/go/private/sdk.bzl", line 196, column 17, in _remote_sdk
		fail("error extracting Go SDK:\n" + res.stdout + res.stderr)
Error in fail: error extracting Go SDK:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(tar, ...)": No such file or directory
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/tmp/envoyA1.19-20211009-12166-1s4jbbp/.brew_home/_bazel/32ea98d9ad756d02b6517b5463b86b30/external/io_bazel_rules_go/go/private/sdk.bzl", line 100, column 16, in _go_download_sdk_impl
		_remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
	File "/tmp/envoyA1.19-20211009-12166-1s4jbbp/.brew_home/_bazel/32ea98d9ad756d02b6517b5463b86b30/external/io_bazel_rules_go/go/private/sdk.bzl", line 196, column 17, in _remote_sdk
		fail("error extracting Go SDK:\n" + res.stdout + res.stderr)
Error in fail: error extracting Go SDK:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(tar, ...)": No such file or directory
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: error extracting Go SDK:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(tar, ...)": No such file or directory
```

**Comment by codefromthecrypt** [comment]
I asked for help on https://github.com/envoyproxy/envoy/pull/17438 on the failure extracting go here

**Comment by codefromthecrypt** [comment]
the error message seems to match this from bazel
```
        ctx.download(
            url = urls,
            sha256 = sha256,
            output = "go_sdk.tar.gz",
        )
        res = ctx.execute(["tar", "-xf", "go_sdk.tar.gz", "--strip-components=1"])
        if res.return_code:
            fail("error extracting Go SDK:\n" + res.stdout + res.stderr)
        ctx.delete("go_sdk.tar.gz")
```
https://github.com/bazelbuild/rules_go/commit/e01a4e8270674949c496d9eee034e294c85b7286

If this is the right bazel code, the command invoked was 'tar -xf go_sdk.tar.gz --strip-components=1' and 'No such file or directory' could possibly have been from tar, if the "go_sdk.tar.gz" didn't actually download. On my ubuntu host's tar, the message is longer, but ends in 'No such file or directory', whereas a binary not found looks like 'not found' or 'command not found'
```

**Comment by codefromthecrypt** [comment]
Summary:

Envoy's build uses go to generate files from protobuf sources. Due to bazel norms, it nests download and extraction of a pinned go SDK. Recently, the bazel rules changed to use system tar instead of built-in. So, downloading would work, but if system tar can't be found, the build would fail.

The default PATH changed recently when on_mac/on_linux was phased out and replaced with OS.mac/OS.linux. This wasn't tested, but also the substitution went fine on macOS.

Linux ended up with a partial failure: `#{Formula["python@3.9"].opt_libexec}/bin` is placed first in the PATH, so worked, but the rest of the path was messed up. This meant only what's in python's bin ended up in the path, delaying other PATH failures. When bazel went to extract go, it went to fork tar and failed. It probably would fork other things and fail, but tar failed first.

The main takeaway is this formula can't use mechanical substitution due to branching logic. All changes need to be built-from-source on change on all supported operating systems.

FWIW, I still recommend removing linux support. It is true this formula will still be patched and complicated even without linux, but it will be less. More importantly, the burden of change is lower, instead of having to test on linux due to issues like this, possibly via docker which is painfully slow, tests are limited to "just macOS". Even if that still takes an hour or more to build locally, it is an improvement and in this case would have saved days.

Thanks to @cho-m for spending time to get to the bottom of this. Hopefully, this passes now except for the known issue where arm64 won't yet work on macOS.

**Comment by codefromthecrypt** [comment]
updated the comments on patches and remaining upstream issues

**Comment by codefromthecrypt** [comment]
I removed the dropping 1.18 for 1.19 after thinking through the implications of https://github.com/Homebrew/homebrew-core/pull/86755#discussion_r725905021. The summary is that if the project team suggest skipping 1.19.0 and 1.19.1, there's no value in retaining it. Implicitly, 1.18.x has higher priority.

**Comment by codefromthecrypt** [comment]
I feel the osx 10.14 fail might be around old certs as it consistently fails `The homepage URL https://www.envoyproxy.io/index.html is not reachable`

I'm surprised arm64 is passing.. I'll try it on my M1

**Review by carlocab — APPROVED** [review]
Ok, let's try it. The weird state of the Linux runner might make @BrewTestBot unhappy though.

**Comment by codefromthecrypt** [comment]
thanks @carlocab. I'll keep an eye out!

**Pull request closed without merging**
