### PR TITLE
sqlparse 0.2.2 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes https://github.com/Homebrew/homebrew-python/issues/383.

CC @tdsmith

### CODE REVIEW

**Comment by tdsmith** [comment]
-1 on making this `import`able; if someone wants to use this in a Python project they should use pip.

**Comment by tdsmith** [comment]
Specifically: I think this shouldn't be installed to `prefix`.

**Comment by ilovezfs** [comment]
The docs make it look like importing it is the primary use case: https://sqlparse.readthedocs.io/en/latest/

**Comment by tdsmith** [comment]
My preference is that we expose only the CLI component or decline to ship it at all; I think the former is reasonable if you want to do it.

**Comment by ilovezfs** [comment]
That's fine. It's what I had originally before reading the documentation.

**Comment by tdsmith** [comment]
For completeness, some of the reasons I feel that way are that:

* pip doesn't have a sense of ownership and will happily try and upgrade or downgrade any modules in sys.path while trying to satisfy the requirements of something it's been asked to install, which can lead to confusion
* pip and Homebrew both dump files in the HOMEBREW_PREFIX site-packages, which can lead to linking conflicts if pip has already installed something
* having pip manage importables avoids our having to worry about installing for python3.x

Now that the Python world has wheels I think homebrew-python has mostly outlived its utility.

**Comment by ilovezfs** [comment]
@tdsmith PR refreshed

**Review by tdsmith — APPROVED** [review]

**Pull request closed without merging**
