### PR TITLE
netpbm 10.86.09

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by samford** [comment]
```
failed: brew linkage --test root

       Broken dependencies:
  /usr/local/opt/fcgi/lib/libfcgi.0.dylib (fcgi)
```

**Comment by SMillerDev** [comment]
I'd say so

**Comment by samford** [comment]
I added a revision for `root` and everything looks good on CI now.

**Comment by SMillerDev** [comment]
Thanks @samford! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
