### PR TITLE
sngrep 1.4.8

### PR DESCRIPTION
**Pull request by mprince**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mprince** [comment]
This might be easy to find but how would I differential between `GPL-3.0-only` or `GPL-3.0-or-later`? I know the license are [here](https://spdx.org/licenses/).

**Comment by chenrui333** [comment]
license header ref (`src/main.c`):

```
/**************************************************************************
 **
 ** sngrep - SIP Messages flow viewer
 **
 ** Copyright (C) 2013-2018 Ivan Alonso (Kaian)
 ** Copyright (C) 2013-2018 Irontec SL. All rights reserved.
 **
 ** This program is free software: you can redistribute it and/or modify
 ** it under the terms of the GNU General Public License as published by
 ** the Free Software Foundation, either version 3 of the License, or
 ** (at your option) any later version.
 **
 ** This program is distributed in the hope that it will be useful,
 ** but WITHOUT ANY WARRANTY; without even the implied warranty of
 ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 ** GNU General Public License for more details.
 **
 ** You should have received a copy of the GNU General Public License
 ** along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **
 ****************************************************************************/
```

**Comment by chenrui333** [comment]
@mprince the license header in the respective file or README would be the differentiator to decide the exact license. So far that is the path I chose.

**Review by chenrui333 — APPROVED** [review]

**Comment by Rylan12** [comment]
> This might be easy to find but how would I differentiate between `GPL-3.0-only` or `GPL-3.0-or-later`? I know the license are [here](https://spdx.org/licenses/).

The keywords to look for are `or (at your option) any later version.` If it has that, `-or-later`. If not, `-only`.

But yeah, that's usually found in the readme or source file headers rather than the license file itself.

**Comment by mprince** [comment]
Thank you guys for the tip 👍

**Pull request closed without merging**
