### PR TITLE
itk 4.13.2 (new formula)

### PR DESCRIPTION
**Pull request by fblupi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Moving formula from **homebrew-sci** [as they say they don't keep maintaining the repo](https://github.com/brewsci/homebrew-science/blob/master/CONTRIBUTING.md). I have renamed the formula from insighttoolkit to itk and updated it to a more recent version.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
  * Non-libraries were installed to "/usr/local/opt/itk/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/opt/itk/lib/itkLIBMINCConfig.cmake
            /usr/local/opt/itk/lib/UseitkLIBMINC.cmake
```

**Comment by fblupi** [comment]
> * New formulae should not have a `bottle do` block

Fixed



>   * Non-libraries were installed to "/usr/local/opt/itk/lib"
>     Installing non-libraries to "lib" is discouraged.
>     The offending files are:
>       /usr/local/opt/itk/lib/itkLIBMINCConfig.cmake
>             /usr/local/opt/itk/lib/UseitkLIBMINC.cmake

I think I can't do anything to solve this. I can't detect what cmake option is generating the cmake file in the lib folder and the formula from the homebrew-sci repo generate this cmake file too.

**Comment by fxcoudert** [comment]
> the formula from the homebrew-sci repo generate this cmake file too

That does not make it suitable for homebrew-core.

**Comment by zbeekman** [comment]
libminc (vendored by itk) needs updating it's CMakeLists.txt. I've [added a patch](https://raw.githubusercontent.com/Homebrew/formula-patches/master/itk/4.13.2-MINC-cmake-files-location.patch), and submitted a [PR to ITK](https://github.com/InsightSoftwareConsortium/ITK/pull/754), which is being investigated [upstream of that by MINC](https://github.com/BIC-MNI/libminc/tree/develop-homebrew-style) too.

@fblupi do you mind if I force push to your branch with my changes (and rebased onto a more recent homebrew-core/master)?

**Comment by zbeekman** [comment]
@fblupi I hope you don't mind: I'm going to force push to your branch so that this can get tested with CI.

**Comment by fblupi** [comment]
@zbeekman No problem. Feel free :)

**Comment by zbeekman** [comment]
Yes, we know brew testbot...

**Comment by zbeekman** [comment]
@fxcoudert what are your thoughts on merging it? It looks like the upstream of the upstream is patching this, and the upstream package is going to incorporate that patch.

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by fblupi** [comment]
Thank you too @zbeekman for your help with the issue I had! 🍻

**Pull request closed without merging**
