### PR TITLE
wolfssl: Enable Java JNI support

### PR DESCRIPTION
**Pull request by bondolo**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by UniqMartin** [comment]
The formula unfortunately fails to build on our Yosemite CI. Any idea what might be going on here?

Also regarding your change: Can you provide a bit more detail why you want to enable it and what the effect of that switch is exactly? Does enabling this have any impact on the formula dependencies, e.g. does it now require Java to be installed for this flag to work?

**Comment by ilovezfs** [comment]
@UniqMartin If you have CLT and Xcode on 10.10, and you ENV.delete("SDKROOT"), build will succeed. However, if you have only Xcode, and no CLT, ENV.delete("SDKROOT") won't save you, and build fails anyway.

The problem turns out to be that configure is screwing up (not sure the cause) and deciding that SIZEOF_LONG_LONG  and SIZEOF_LONG are both 0, instead of both 8, which then causes that enum mentioned in the Jenkins report to be empty. Changing config.h before running make to say 8 and 8 "fixes" the build (at least for 64-bit machines), but it would be nice to know why the configure check is failing so spectacularly.

**Comment by ilovezfs** [comment]
LOL https://gist.github.com/anonymous/7b1bdbf9966c5f329f75ff56fb17f33b

```
configure:16977: ./conftest
dyld: Library not loaded: /usr/lib/libnetwork.dylib
  Referenced from: /private/tmp/wolfssl-20160610-38012-13qsm2o/wolfssl-3.9.1/./conftest
  Reason: image not found
./configure: line 2090: 40599 Trace/BPT trap: 5       ./conftest$ac_exeext
```

Yosemite has no /usr/lib/libnetwork.dylib. El Capitan does. Guess what happens if I copy the libnetwork.dylib from iPhone platform folder to /usr/lib... value comes back as 8 and build succeeds.

**Comment by ilovezfs** [comment]
OK looks like this is superenv being overly helpful and turning what's supposed to be a build-time bug into a run-time bug:

>vm1010:~ joe$ clang -o conftest -mdynamic-no-pic -fvisibility=hidden conftest.c -lnetwork
ld: library not found for -lnetwork
clang: error: linker command failed with exit code 1 (use -v to see invocation)
vm1010:~ joe$ clang -pipe -Os -march=native -o conftest -mdynamic-no-pic -fvisibility=hidden conftest.c -lnetwork -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -isystem/usr/local/include -isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 -isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/apache2 -isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
vm1010:~ joe$ ./conftest 
dyld: Library not loaded: /usr/lib/libnetwork.dylib
  Referenced from: /Users/joe/./conftest
  Reason: image not found
Trace/BPT trap: 5
vm1010:~ joe$

**Comment by ilovezfs** [comment]
In particular it's the `-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk` that causes it not to fail at build time.

**Comment by ilovezfs** [comment]
This workaround is successful, but maybe @UniqMartin will have a different idea:
```
unless File.exist?("/usr/lib/libnetwork.dylib")
  inreplace "configure.ac", "AC_CHECK_LIB(network,socket)", ""
end
```

**Comment by UniqMartin** [comment]
@ilovezfs I see, the build failure is completely unrelated to the change in this PR, but instead caused by a change in how we set up `SDKROOT` since `wolfssl` was bottled. I'm increasingly of the opinion that no matter what default we pick for setting `SDKROOT` and related build settings, there will always be some formulae that fail with the CLT but succeed with Xcode and vice versa. (I just ran the unmodified formula through our CI to confirm your observation. Unsurprisingly, it was confirmed.)

**Comment by ilovezfs** [comment]
Yep, and the bright side is that it turned up a bug that we'd not otherwise have known about that affects anyone who doesn't have CLT.

**Comment by bondolo** [comment]
The effect of the switch is to enable support for using wolfssl with the wolfssl-jni library. The practical effect is to add one additional field to certain wolfssl data structures which provides the current jni context (if any). The feature is can be disabled for small platforms but it is not a significant cost for desktop paltforms--one additional pointer. Once enabled the wolfssl libraries can be used with the https://github.com/wolfSSL/wolfssljni libraries.  Java is not required for the wolfssl portion.

**Comment by UniqMartin** [comment]
@bondolo Thank you for this very clear explanation! This sounds like a reasonable change to me. I created PR #1903 to combine your changes (preserved your commit, thus you will be properly credited) with a workaround to make things hopefully build successfully on our CI.

**Comment by UniqMartin** [comment]
Merged in 5896e5e132371bd97ede550690b8eb5b22d2ab1b. Thank you for this contribution to Homebrew, @bondolo! :tada:

**Pull request closed without merging**
