### PR TITLE
sdl12-compat 1.2.64

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /usr/bin/clang test.c -o test -I/usr/local/include/SDL -D_THREAD_SAFE -L/usr/local/lib -lSDLmain -lSDL -Wl,-framework,Cocoa
  test.c:3:5: error: conflicting types for 'SDL_main'
  int main() {
      ^
  /usr/local/include/SDL/SDL_main.h:34:14: note: expanded from macro 'main'
  #define main SDL_main
               ^
  /usr/local/include/SDL/SDL_main.h:35:12: note: previous declaration is here
  extern int SDL_main(int argc, char *argv[]);
             ^
  1 error generated.
```

**Comment by carlocab** [comment]
`Error: no implicit conversion of nil into String` will be fixed in Homebrew/homebrew-test-bot#933.

Though, `brew test` is also failing only on Ventura:
```
  test.c:3:5: error: conflicting types for 'SDL_main'
  int main() {
      ^
  /usr/local/include/SDL/SDL_main.h:34:14: note: expanded from macro 'main'
  #define main SDL_main
               ^
  /usr/local/include/SDL/SDL_main.h:35:12: note: previous declaration is here
  extern int SDL_main(int argc, char *argv[]);
             ^
  1 error generated.
```
https://github.com/Homebrew/homebrew-core/actions/runs/5132722097/jobs/9235453445?pr=132415#step:3:48

Not sure what that's about. Ideas, @Bo98, @fxcoudert?

**Comment by Bo98** [comment]
`int main()` -> `int main(int argc, char* argv[])` should fix it.

**Comment by carlocab** [comment]
Thanks for the tip!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
