### PR TITLE
dmagnetic 0.23

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dfabulich** [comment]
The tests failed on this PR because the test failed. On line 20, the md5 hash needs to change from `2d90033c199915d2f4d4ecc964121928 ` to `2d90033c199915d2f4d4ecc964121928`

**Review by dfabulich — CHANGES_REQUESTED** [review]
The tests failed on this PR because the test failed. On line 20, the md5 hash needs to change from `2d90033c199915d2f4d4ecc964121928 ` to `0be77b320a608a1778a0714adafaed69`

**Comment by alebcay** [comment]
Thanks for catching that! 🥇

**Review by dfabulich — APPROVED** [review]

**Comment by dfabulich** [comment]
Now just the 10.13 tests are failing, but I think that's the CI's fault, not the fault of this PR.

**Comment by alebcay** [comment]
CI re-run fixed it.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
