### PR TITLE
cubejs-cli 0.33.28

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
package diff

```
diff --git a/package.json b/package.json
index e3b8adf..54976cf 100644
--- a/package.json
+++ b/package.json
@@ -2,7 +2,7 @@
   "name": "cubejs-cli",
   "description": "Cube.js Command Line Interface",
   "author": "Cube Dev, Inc.",
-  "version": "0.33.25",
+  "version": "0.33.26",
   "repository": {
     "type": "git",
     "url": "https://github.com/cube-js/cube.git",
@@ -31,8 +31,8 @@
   ],
   "dependencies": {
     "@cubejs-backend/dotenv": "^9.0.2",
-    "@cubejs-backend/schema-compiler": "^0.33.25",
-    "@cubejs-backend/shared": "^0.33.24",
+    "@cubejs-backend/schema-compiler": "^0.33.26",
+    "@cubejs-backend/shared": "^0.33.26",
     "chalk": "^2.4.2",
     "cli-progress": "^3.10",
     "commander": "^2.19.0",
@@ -50,7 +50,7 @@
   },
   "devDependencies": {
     "@cubejs-backend/linter": "^0.33.0",
-    "@cubejs-backend/server": "^0.33.25",
+    "@cubejs-backend/server": "^0.33.26",
     "@oclif/command": "^1.8.0",
     "@types/cli-progress": "^3.8.0",
     "@types/cross-spawn": "^6.0.2",
@@ -69,5 +69,5 @@
   "eslintConfig": {
     "extends": "../cubejs-linter"
   },
-  "gitHead": "b858d30f55e130c9afdef5dea339125af1752ad9"
+  "gitHead": "a1e1fee0525de30d9a3f80d1b8050b604e64b133"
 }
```

**Comment by chenrui333** [comment]
also cc @Homebrew/linux

**Comment by iMichka** [comment]
Looks like this ships a precompiled binary that links against some system libraries of the system's host they were built on ...

```
linuxbrew@3647d6eeb30f:~/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula$ brew linkage --reverse cubejs-cli
/lib/x86_64-linux-gnu/libc.so.6
  libexec/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/native/native/index.node

/lib/x86_64-linux-gnu/libdl.so.2
  libexec/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/native/native/index.node

/lib/x86_64-linux-gnu/libgcc_s.so.1
  libexec/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/native/native/index.node

/lib/x86_64-linux-gnu/libm.so.6
  libexec/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/native/native/index.node

/lib/x86_64-linux-gnu/libpthread.so.0
  libexec/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/native/native/index.node

/lib/x86_64-linux-gnu/libz.so.1
  libexec/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/native/native/index.node
```

**Comment by chenrui333** [comment]
gonna try out in a new PR.

**Comment by chenrui333** [comment]
#135484

**Pull request closed without merging**
