### PR TITLE
deno 1.40.4

### PR DESCRIPTION
**Pull request by crunchtime-ali**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by zuisong** [comment]
```diff
@@ -144,9 +144,8 @@ class Deno < Formula
       console.log("hello", "deno");
     EOS
     assert_match "hello deno", shell_output("#{bin}/deno run hello.ts")
-    assert_match "console.log",
-      shell_output("#{bin}/deno run --allow-read=#{testpath} https://deno.land/std@0.50.0/examples/cat.ts " \
-                   "#{testpath}/hello.ts")
+    assert_match "Welcome to Deno!",
+      shell_output("#{bin}/deno run --allow-read=#{testpath} https://deno.land/std@0.100.0/examples/welcome.ts")
 
     linked_libraries = [
       Formula["sqlite"].opt_lib/shared_library("libsqlite3"),
```

**Comment by ZhongRuoyu** [comment]
What's the difference, @zuisong?

**Comment by zuisong** [comment]
> What's the difference, @zuisong?
> 
> 

deno 1.40.4 removed some deprecated method

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
need a restart

image

**Pull request merged**
