### PR TITLE
glib 2.64.4

### PR DESCRIPTION
**Pull request by miccal**
Continuation of https://github.com/Homebrew/homebrew-core/pull/57298

Ping @Rylan12

### CODE REVIEW

**Comment by miccal** [comment]
Note sure why the tests were cancelled?

**Comment by Rylan12** [comment]
Not sure why they were canceled. I just triggered a rerun.

**Comment by miccal** [comment]
Thanks @Rylan12 -- the same thing happened in https://github.com/Homebrew/homebrew-core/pull/57562

**Comment by Rylan12** [comment]
Yeah, there seems to be a CI bug. I'll go trigger the other one as well.

**Comment by miccal** [comment]
```
Error: 3 failed steps!
brew fetch --retry evince
brew test --verbose opentsdb
brew fetch --retry sile
```

I think `evince` and `sile` have issues with their bottles:
```
-bash-5.0.17- /Users/miccal (29) [> brew fetch evince
==> Downloading https://homebrew.bintray.com/bottles/evince-3.36.7_1.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found                    
Error: Failed to download resource "evince"
Download failed: https://homebrew.bintray.com/bottles/evince-3.36.7_1.catalina.bottle.tar.gz
```
```
-bash-5.0.17- /Users/miccal (29) [> brew fetch sile
==> Downloading https://homebrew.bintray.com/bottles/sile-0.10.5_2.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found                    
Error: Failed to download resource "sile"
Download failed: https://homebrew.bintray.com/bottles/sile-0.10.5_2.catalina.bottle.tar.gz
```
probably fixed by a revision bump.

For `opentsdb` see https://github.com/Homebrew/homebrew-core/pull/57232

**Comment by Bo98** [comment]
I'm looking into the bottle thing just now.

**Comment by miccal** [comment]
Thank you @Bo98 :)

**Comment by Bo98** [comment]
Should be fixed now.

**Comment by miccal** [comment]
@Rylan12 the only failure now is `opentsdb`, so I think this can be merged?

**Comment by Rylan12** [comment]
I think so but I want to double-check.

@chenrui333 can you take a look?

`brew test --verbose opentsdb` is the only one that fails. `opentsdb` is being worked on in #57232 and fails with what looks like the same issue.

Locally, the bottled `opentsdb`'s tests succeed against both this version and the previous version of `glib`. Building `opentsdb` from source seems to make the tests fail regardless of which version of `glib` is installed, so I don't think this will cause any new breakage for users.

**Comment by chenrui333** [comment]
The caliana build got cancelled, just triggered a new PR build.

**Comment by miccal** [comment]
Thank you @Rylan12 and @chenrui333.

**Comment by chenrui333** [comment]
on `10.15`

brew test --verbose csound
brew test --verbose opentsdb

on `10.14`
brew test --verbose opentsdb

on `10.13`

brew test --verbose opentsdb

similar situation as #57583

Proceeding with the merge.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
