### PR TITLE
wxformbuilder 4.1.0 (new formula)

### PR DESCRIPTION
**Pull request by ghost**
GUI Builder for wxWidgets

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by stefanoweidmann** [comment]
Can someone please help me what is wrong with my commit message?

**Comment by chenrui333** [comment]
```
  -- Could NOT find wxWidgets (missing: wxWidgets_DIR)
  CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.29.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES) (Required is at
    least version "3.2")
```

**Comment by chenrui333** [comment]
> Can someone please help me what is wrong with my commit message?

nothing wrong with the msg, might be just ci hiccup.

**Comment by chenrui333** [comment]
> Can someone please help me what is wrong with my commit message?

the formula should be all lower case, like `wxformbuilder 4.1.0 (new formula)`

**Pull request closed without merging**
