### PR TITLE
node 11.4.0

### PR DESCRIPTION
**Pull request by tommyang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
I think generate-json-schema needs an update or a revision bump (hard to tell on mobile) @tommyang could you check if there's an update to that software to support 11.4.0?

**Comment by tommyang** [comment]
@SMillerDev No update, but this is a known failure for some time now. https://github.com/Homebrew/homebrew-core/pull/33690#issuecomment-435671842

**Comment by chrmoritz** [comment]
After looking into it, it seems to be more of an issue with our `generate-json-schema` too. Piping data to if was never officially supported. We should just write our test data to a `test.json` and the pass the filename as a first parameter to `generate-schema' as documented: https://www.npmjs.com/package/generate-schema#cli

**Comment by tommyang** [comment]
Looks like this is already reported to upstream when this happens on Node 11.3.0 nijikokun/generate-schema#44

**Comment by chrmoritz** [comment]
PR to fix the test flakiness: https://github.com/Homebrew/homebrew-core/pull/34953

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by chrmoritz** [comment]
Now we got the random network error in the `npm install` step of the `grunt-cli` test, which also did happen before but it's a quite infrequent one.

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
Shipped. Thanks @tommyang and @chrmoritz!

**Pull request closed without merging**
