### PR TITLE
gnu-apl 1.5

### PR DESCRIPTION
**Pull request by ilovezfs**
- upstream patch for clang build failures
- add a head spec

### CODE REVIEW

**Comment by DomT4** [comment]
The build is fairly impressively broken 😄

**Comment by ilovezfs** [comment]
The pseudo good news is that it's fine with gcc.

**Comment by ilovezfs** [comment]
OK, found upstream link about it: https://lists.gnu.org/archive/html/bug-apl/2015-08/msg00111.html and sure enough it's fixed in HEAD.
```
```

**Comment by DomT4** [comment]
Nice. Can we grab that as a patch, if it applies cleanly?

**Comment by ilovezfs** [comment]
Yeah, this fixes it:
```
    patch do
      url "https://github.com/ilovezfs/gnu-apl/commit/d3b5ce9f4a079af8f03c664d6f455cb8eb7f722f.patch"
    end

    patch do
      url "https://github.com/ilovezfs/gnu-apl/commit/23dd9084c6227a2f4c01857d5c03e5f6988b8645.patch"
    end

    patch do
      url "https://github.com/ilovezfs/gnu-apl/commit/d69d4ba3774ccc7e9f351a6cc5dd82762e5b9bef.patch"
    end

    patch do
      url "https://github.com/ilovezfs/gnu-apl/commit/7fafa990cf5bed607d3b0a2c820a21a02d964339.patch"
    end

    patch do
      url "https://github.com/ilovezfs/gnu-apl/commit/e82978d154f22ebe782bc034109d93c0df58cc55.patch"
    end

    patch do
      url "https://github.com/ilovezfs/gnu-apl/commit/ae9f34a216a046b29c4b69a87c315509688b6366.patch"
    end

    patch do
      url "https://github.com/ilovezfs/gnu-apl/commit/408da4d7ef6f066d10d9eea81cf0cda745f29d90.patch"
    end
```

**Comment by ilovezfs** [comment]
They're all directly sequential, so could be put into a single patch using the revision range, or separately as above. Not sure which you prefer.

**Comment by ilovezfs** [comment]
Another option (unorthodox) would be to fake it and just define 1.5.0 as the last of these since these commits all directly followed the tag.

**Comment by ilovezfs** [comment]
@DomT4 In other words, I think we should consider doing this:
```
  url "http://svn.savannah.gnu.org/svn/apl/trunk", :revision => 586
  version "1.5"
```

**Comment by ilovezfs** [comment]
PR refreshed with a combo patch in formula-patches.

**Comment by DomT4** [comment]
Apologies, I wasn't around much last night & completely missed the initial emails here. This LGTM. Feel free to :shipit:.

**Comment by ilovezfs** [comment]
Woo hoo 12,258 line patch for the win

**Comment by DomT4** [comment]
😆 Sometimes I wish you wouldn't tell me these things. Should be alright given people can't screw up the whitespacing with external patches, unless we want to wait for the next stable release instead, don't mind either way.

**Comment by ilovezfs** [comment]
>Sometimes I wish you wouldn't tell me these things.

Well that is indeed the point. I don't ever want to hear, "Well if you'd only told me *that*, then ..."

I actually think it's fine in this case. For instance, 8,607 of it is just aclocal.m4 being added.

**Comment by DomT4** [comment]
👍

**Pull request closed without merging**
