### PR TITLE
conan 1.40.3

### PR DESCRIPTION
**Pull request by theirix**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by theirix** [comment]
Could you please restart this PR that is probably failed due to a network problem (`"* The homepage URL https://conan.io is not reachable"`)?

**Comment by carlocab** [comment]
Re-running won't help, unfortunately: Homebrew/brew#12161

**Comment by theirix** [comment]
Got it, thanks. It's curious that this formula release fixes the same certificate problem.

**Comment by carlocab** [comment]
That's unfortunate. We're still working on a way to fix this, and I may have a temporary workaround we can use till then. We can restart this when one of those is done.

**Review by carlocab — APPROVED** [review]
Thanks, @theirix!

**Comment by carlocab** [comment]
By the way, if you use `brew bump-formula-pr`, the `resource` updates should be handled for you automatically.

**Pull request closed without merging**
