### PR TITLE
uncrustify 0.73.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/tmp/uncrustify-20210514-76886-1407m21/uncrustify-uncrustify-0.73.0/src/output.cpp:2004:13: error: no template named 'map' in namespace 'std'; did you mean 'max'?
static std::map<std::size_t, std::pair<std::wregex, std::wregex> > get_reflow_fold_regex_map()
       ~~~~~^~~
            max
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:2648:1: note: 'max' declared here
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/tmp/uncrustify-20210514-76886-1407m21/uncrustify-uncrustify-0.73.0/src/output.cpp:2004:13: error: C++ requires a type specifier for all declarations
static std::map<std::size_t, std::pair<std::wregex, std::wregex> > get_reflow_fold_regex_map()
~~~~~~      ^
/tmp/uncrustify-20210514-76886-1407m21/uncrustify-uncrustify-0.73.0/src/output.cpp:2004:13: error: template specialization requires 'template<>'
static std::map<std::size_t, std::pair<std::wregex, std::wregex> > get_reflow_fold_regex_map()
            ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
template<> 
/tmp/uncrustify-20210514-76886-1407m21/uncrustify-uncrustify-0.73.0/src/output.cpp:2004:13: error: no variable template matches specialization; did you mean to use 'max' as function template instead?
/tmp/uncrustify-20210514-76886-1407m21/uncrustify-uncrustify-0.73.0/src/output.cpp:2004:67: error: expected ';' after top level declarator
static std::map<std::size_t, std::pair<std::wregex, std::wregex> > get_reflow_fold_regex_map()
                                                                  ^
                                                                  ;
/tmp/uncrustify-20210514-76886-1407m21/uncrustify-uncrustify-0.73.0/src/output.cpp:2962:14: error: unknown type name 'kw_subst_t'
static const kw_subst_t kw_subst_table[] =
             ^
[ 76%] Building CXX object CMakeFiles/uncrustify.dir/src/punctuators.cpp.o
```

**Comment by cho-m** [comment]
Looks like upstream only has include for Windows:
https://github.com/uncrustify/uncrustify/blob/uncrustify-0.73.0/src/output.cpp#L23-L25
```c
#ifdef WIN32
#include <map>                    // to get std::map
#endif // WIN32
```

PR that changed modified includes: https://github.com/uncrustify/uncrustify/pull/3143

**Comment by cho-m** [comment]
PR to re-add `<map>` (and `<stack>`) include: uncrustify/uncrustify#3178

**Comment by clason** [comment]
Since a 0.73.1 does not seem forthcoming, would it be acceptable to add the patch from the linked PR to the formula?

**Pull request closed without merging**
