### PR TITLE
gnuplot 5.0.4

### PR DESCRIPTION
**Pull request by ilovezfs**
- add linked library dependency freetype
- add webp dependency
- make gd non-optional since its dependencies are already fulfilled

### CODE REVIEW

**Comment by ilovezfs** [comment]
here we go again with the linked

**Comment by DomT4** [comment]
> set TERM to xterm in the test to fix terminal type error

This doesn't seem to have worked on CI for some reason.

**Comment by ilovezfs** [comment]
@DomT4 I'm not surprised. It was a pure guess :)

**Comment by DomT4** [comment]
Looking at the error itself:
```
line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list
```
We set that in the test, so perhaps that's no longer a valid type of terminal to set & we need to tweak that line.

**Comment by ilovezfs** [comment]
It's not lying of course
```
Available terminal types:
           canvas  HTML Canvas object
              cgm  Computer Graphics Metafile
          context  ConTeXt with MetaFun (for PDF documents)
            corel  EPS format for CorelDRAW
             dumb  ascii art for anything that prints text
              dxf  dxf-file for AutoCad (default size 120x80)
            eepic  EEPIC -- extended LaTeX picture environment
              emf  Enhanced Metafile format
            emtex  LaTeX picture environment with emTeX specials
         epslatex  LaTeX picture environment using graphicx package
              fig  FIG graphics language for XFIG graphics editor
             hpgl  HP7475 and relatives [number of pens] [eject]
            latex  LaTeX picture environment
              lua  Lua generic terminal driver
               mf  Metafont plotting standard
               mp  MetaPost plotting standard
             pcl5  HP Designjet 750C, HP Laserjet III/IV, etc. (many options)
       postscript  PostScript graphics, including EPSF embedded files (*.eps)
          pslatex  LaTeX picture environment with PostScript \specials
            pstex  plain TeX with PostScript \specials
         pstricks  LaTeX picture environment with PSTricks macros
              qms  QMS/QUIC Laser printer (also Talaris 1200 and others)
              svg  W3C Scalable Vector Graphics
          tek40xx  Tektronix 4010 and others; most TEK emulators
Press return for more:           tek410x  Tektronix 4106, 4107, 4109 and 420X terminals
          texdraw  LaTeX texdraw environment
             tgif  TGIF X11 [mode] [x,y] [dashed] ["font" [fontsize]]
             tikz  TeX TikZ graphics macros via the lua script driver
         tkcanvas  Tk canvas widget
             tpic  TPIC -- LaTeX picture environment with tpic \specials
          unknown  Unknown terminal type - not a plotting device
            vttek  VT-like tek40xx terminal emulator
            xterm  Xterm Tektronix 4014 Mode
```
we're not even linked to libpng.

**Comment by ilovezfs** [comment]
hehe
```
    args << ((build.with? "gd") ? "--with-gd=#{gd}" : "--without-gd")
```
but there is no gd option ... so it passes --without gd :)

**Comment by DomT4** [comment]
Is `libpng` part of the recursive deps tree? Maybe it linked opportunistically beforehand but doesn't now or something 💭.

**Comment by ilovezfs** [comment]
fixed:
```
🍺  /usr/local/Cellar/gnuplot/5.0.4: 44 files, 2.3M, built in 30 seconds
iMac-TMP:local joe$ brew linkage gnuplot
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib (fontconfig)
  /usr/local/opt/freetype/lib/libfreetype.6.dylib (freetype)
  /usr/local/opt/gd/lib/libgd.3.dylib (gd)
  /usr/local/opt/jpeg/lib/libjpeg.8.dylib (jpeg)
  /usr/local/opt/libpng/lib/libpng16.16.dylib (libpng)
  /usr/local/opt/libtiff/lib/libtiff.5.dylib (libtiff)
  /usr/local/opt/lua/lib/liblua.5.2.dylib (lua)
  /usr/local/opt/readline/lib/libreadline.6.dylib (readline)
  /usr/local/opt/webp/lib/libwebp.6.dylib (webp)
iMac-TMP:local joe$ brew test -vd gnuplot
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gnuplot.rb
Testing gnuplot
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160721-78684-shkwt2.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gnuplot.rb -vd
/usr/local/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gnuplot.rb
==> /usr/local/Cellar/gnuplot/5.0.4/bin/gnuplot -e set terminal png;
set output "/tmp/gnuplot-test-20160721-78685-wsrj3r/image.png";
plot sin(x);
iMac-TMP:local joe$ 
```

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
👍 🌟

**Pull request closed without merging**
