### PR TITLE
lua: fix Linux pc file

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Review by SMillerDev — COMMENTED** [review]
Doesn't upstream have a way to generate these?

**Comment by cho-m** [comment]
Can someone check on `libdl` linkage?
```
Dynamic Section:
  NEEDED               libm.so.6
  NEEDED               libc.so.6
  SONAME               liblua.so.5.4
  RPATH                @@HOMEBREW_PREFIX@@/Cellar/lua/5.4.3/lib:@@HOMEBREW_PREFIX@@/lib:@@HOMEBREW_PREFIX@@/opt/ncurses/lib:@@HOMEBREW_PREFIX@@/opt/readline/lib

...

Version References:
  required from libm.so.6:
    0x09691a75 0x00 05 GLIBC_2.2.5
  required from libc.so.6:
    0x06969191 0x00 08 GLIBC_2.11
    0x06969194 0x00 07 GLIBC_2.14
    0x0d696914 0x00 06 GLIBC_2.4
    0x09691974 0x00 04 GLIBC_2.3.4
    0x09691a75 0x00 03 GLIBC_2.2.5
    0x0d696913 0x00 02 GLIBC_2.3
```

**Comment by carlocab** [comment]
> Doesn't upstream have a way to generate these?

Sadly not. The `-ldl` flag comes from the `pc` file we already ship on Linux currently, however: https://github.com/Homebrew/linuxbrew-core/blob/24ee965a2eaabd7e87e77d19c55712cdee8aad94/Formula/lua.rb#L111

Not sure about linkage with `libdl`, but this flag is also in the example `pc` file in the Linux patch reference: https://www.linuxfromscratch.org/blfs/view/cvs/general/lua.html

**Comment by cho-m** [comment]
As comparison, I added Arch Linux's linkage below, which does have `libdl`.

One thing to try is rearranging the flags to make.
From @iMichka patch, maybe change
```diff
+	$(CC) -shared -ldl -Wl,-soname,$(LUA_SO).$(V) -o $@.$(R) $? -lm $(MYLDFLAGS)
```
to 
```diff
+	$(CC) -shared -Wl,-soname,$(LUA_SO).$(V) -o $@.$(R) $? -lm -ldl $(MYLDFLAGS)
```

```
Dynamic Section:
  NEEDED               libdl.so.2
  NEEDED               libm.so.6
  NEEDED               libc.so.6
  SONAME               liblua.so.5.4
...
Version References:
  required from libdl.so.2:
    0x09691a75 0x00 09 GLIBC_2.2.5
  required from libm.so.6:
    0x09691a75 0x00 06 GLIBC_2.2.5
    0x06969189 0x00 05 GLIBC_2.29
  required from libc.so.6:
    0x06969191 0x00 10 GLIBC_2.11
    0x06969194 0x00 08 GLIBC_2.14
    0x0d696914 0x00 07 GLIBC_2.4
    0x09691974 0x00 04 GLIBC_2.3.4
    0x09691a75 0x00 03 GLIBC_2.2.5
    0x0d696913 0x00 02 GLIBC_2.3
```

**Comment by cho-m** [comment]
Can we test out order change in Linux patch https://github.com/Homebrew/formula-patches/pull/383

And then check the linkage.

**Comment by cho-m** [comment]
I'll merge the updated patch file and we can rerun using patch from `Homebrew/formula-patches`

The previous patch looks like one from Arch https://github.com/archlinux/svntogit-packages/blob/packages/lua/trunk/liblua.so.patch but they don't hit the linkage issue unlike our Ubuntu CI.

**Review by cho-m — DISMISSED** [review]
I think it is fine to merge. Will let others confirm as unrelated failures should block automerge.

Linkage should allow using libs without extra `-l` flags, but having them in `*.pc` file doesn't hurt.
```
Dynamic Section:
  NEEDED       libdl.so.2
  NEEDED       libm.so.6
  NEEDED       libc.so.6
  SONAME       liblua.so.5.4
```

**Comment by danielnachun** [comment]
Can we also change:
```
lib.install_symlink "liblua.#{version.major_minor}.dylib" => "liblua#{version.major_minor}.dylib"
```
to 
```
lib.install_symlink shared_library("liblua", version.major_minor) => shared_library("liblua#{version.major_minor}")
```

This is the last thing that needs to be upstreamed for the Lua formulae.  Let me know if you are planning to backport this to the other versions of Lua - otherwise I'm happy to do it.

**Comment by cho-m** [comment]
> Can we also change:
> ...

Updated.

> Let me know if you are planning to backport this to the other versions of Lua - otherwise I'm happy to do it.

I'm not. If no one else is planning, then it is free for anyone to work on.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
