### PR TITLE
glib-openssl: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by mchoo7**
See https://github.com/Homebrew/homebrew-core/issues/134251.

### CODE REVIEW

**Comment by Bo98** [comment]
glib-openssl is no longer updated and should probably be deprecated.

Homepage should probably point to https://gitlab.gnome.org/Archive/glib-openssl too.

**Comment by fel1x-developer** [comment]
> glib-openssl is no longer updated and should probably be deprecated. It does not support OpenSSL 3.
> 
> Homepage should probably point to https://gitlab.gnome.org/Archive/glib-openssl too.

I'll take it.

**Comment by fel1x-developer** [comment]
https://github.com/Homebrew/homebrew-core/pull/134489

Created pull request

**Comment by fel1x-developer** [comment]
https://github.com/Homebrew/homebrew-core/pull/134489
Formula deprecated.

**Pull request closed without merging**
