### PR TITLE
spice-gtk 0.38

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

move to meson/ninja build

previous effort, #52379

### CODE REVIEW

**Comment by tschoonj** [comment]
Please do not merge until #56388 is merged in. Thanks!

**Comment by chenrui333** [comment]
> Please do not merge until #56388 is merged in. Thanks!

sounds good, closing this PR and reopen this later.

**Comment by chenrui333** [comment]
Now #57063 is merged, going to retry this PR now.

**Comment by chenrui333** [comment]
Keep running into the python module `six` issue. Not sure how to chip the python module into the build path.

**Comment by diversys** [comment]
There are several formulas which use `six` module: 
https://github.com/Homebrew/homebrew-core/search?q=six

**Pull request closed without merging**
