### PR TITLE
eigen 3.3.7

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
`graph-tool` is still failing on high_sierra. @fxcoudert I think we are ok with this right?

**Comment by igas** [comment]
@Moisan I don't think so https://github.com/Homebrew/brew/pull/5391

**Comment by fxcoudert** [comment]
Here it is not a test, but an entire formula that has failed to build for quite some time :(

**Comment by Moisan** [comment]
@fxcoudert I see, at least my commit should fix the issue when no screen is present.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
