### PR TITLE
added squashfs as a dependency of snapcraft

### PR DESCRIPTION
**Pull request by caarlos0**
it is needed to build snap packages.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
If this was failing before, why isn't our test catching it? Can you explain a bit more?

**Comment by caarlos0** [comment]
@fxcoudert test only do this:

```ruby
  test do
    ENV["LC_ALL"]="en_US.UTF-8"
    system "#{bin}/snapcraft", "--version"
    system "#{bin}/snapcraft", "--help"
    system "#{bin}/snapcraft", "init"
    File.exist? "#{testpath}/snap/snapcraft.yaml"
  end
```

What fails is `snapcraft snap`, which is used to generate a snapcraft package. Dunno how to test it in homebrew, but it is a dependency for creating snap packages.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Please bump the revision.

**Comment by caarlos0** [comment]
@ilovezfs done

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @caarlos0! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by caarlos0** [comment]
Thanks @ilovezfs :)

**Pull request closed without merging**
