### PR TITLE
io: fix build on Sierra

### PR DESCRIPTION
**Pull request by cielavenir**
- [✓] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

https://github.com/stevedekorte/io/issues/333#issuecomment-249376400
https://github.com/stevedekorte/io/issues/335
https://github.com/Homebrew/formula-patches/issues/71

### CODE REVIEW

**Comment by ilovezfs** [comment]
is there an upstream commit or PR for this yet?

**Comment by cielavenir** [comment]
My pull request is already merged, so --HEAD is OK. But stable archive is not good.

**Comment by ilovezfs** [comment]
Ah OK. So can we use your upstream commit in the patch block then?

**Comment by cielavenir** [comment]
Yes, that's why I firstly sent pull request to formula-patches.
However, patch is only for stable...

```
stable do
  patch :p0 do
  end
end
```

right?

**Comment by ilovezfs** [comment]
yes and you move the stable url and sha256 into that block too.

an explicit :p0 shouldn't be needed

**Comment by cielavenir** [comment]
I might be doing something wrong, but the patch says

```
can't find file to patch at input line 3
|--- addons/AppleSensors/CMakeLists.txt.orig  2015-10-22 21:36:35.000000000 +0100
|+++ addons/AppleSensors/CMakeLists.txt   2016-06-19 11:37:06.000000000 +0100
```

**Comment by ilovezfs** [comment]
Are you doing this?
```
diff --git a/Formula/io.rb b/Formula/io.rb
index 5501cd1..145d125 100644
--- a/Formula/io.rb
+++ b/Formula/io.rb
@@ -1,14 +1,16 @@
 class Io < Formula
   desc "Small prototype-based programming language"
   homepage "http://iolanguage.com/"
-  url "https://github.com/stevedekorte/io/archive/2015.11.11.tar.gz"
-  sha256 "00d7be0b69ad04891dd5f6c77604049229b08164d0c3f5877bfab130475403d3"
-
   head "https://github.com/stevedekorte/io.git"
 
-  patch :p0 do
-    url "https://raw.githubusercontent.com/Homebrew/formula-patches/master/io/io.patch"
-    sha256 "62489be25589fff7e25c0f82775a36950d36c1ff691a07cb2ba85efc497e62dd"
+  stable do
+    url "https://github.com/stevedekorte/io/archive/2015.11.11.tar.gz"
+    sha256 "00d7be0b69ad04891dd5f6c77604049229b08164d0c3f5877bfab130475403d3"
+
+    patch do
+      url "https://github.com/stevedekorte/io/commit/db4d9c2.patch"
+      sha256 "25245bcfcde145ee5c0d142bee5be3017622173b98a04b26c2169ff738b5914d"
+    end
   end
 
   bottle do
```

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
