### PR TITLE
ntopng 3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by BenjaminHCCarr** [comment]
So this actually fails to build Homebrew/homebrew-core#14278

It's building against `libiconv.dylib` which hasn't been around since XCode 6 I think, or was symlinked for a while.

More digging: I have two version of this file, neither "correctly" named:
/usr/local/Cellar/libiconv/1.15/lib/libiconv.2.dylib
/usr/lib/libiconv.2.dylib

---
*Config*
```
tyr:~ benc$ brew config
HOMEBREW_VERSION: 1.2.2-4-g51aa2e3f4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 51aa2e3f4dd3276912cc5b42e4eca50ac6028989
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e82aaed1d8ccb32c07ee270135d4d71481414118
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_102
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by ilovezfs** [comment]
The three bottles built on CI make me fairly sure "this actually fails to build" is not the case.

**Comment by BenjaminHCCarr** [comment]
Okay, well, with `--with-mariadb` it unfortunately fails to build:

[ntopng-with-mariadb.txt](https://github.com/Homebrew/homebrew-core/files/1053811/ntopng-with-mariadb.txt)

```
tyr:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula (master) benc$ brew unlink ntopng
Unlinking /usr/local/Cellar/ntopng/2.4_1... 3 symlinks removed
tyr:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula (master) benc$ brew install ntopng --with-mariadb | tee ~/tmp/ntopng-with-mariadb.txt 

Updating Homebrew...
==> Using the sandbox
==> Downloading https://github.com/ntop/ntopng/archive/3.0.tar.gz
Already downloaded: /Users/benc/Library/Caches/Homebrew/ntopng-3.0.tar.gz
==> Cloning https://github.com/ntop/nDPI.git
Updating /Users/benc/Library/Caches/Homebrew/ntopng--nDPI--git
==> Checking out branch 2.0-stable
==> ./autogen.sh
==> make
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/ntopng/3.0
==> make
<snip>
ld: library not found for -l/usr/lib/libiconv.dylib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ntopng] Error 1

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
`ntopng --with-mariadb` fails to upgrade/reinstall `@3.0`: https://github.com/Homebrew/homebrew-core/issues/14278
```

**Comment by BenjaminHCCarr** [comment]
`tyr:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula (master) benc$ time brew install --verbose ntopng --with-mariadb | tee ~/tmp/ntopng-with-mariadb-verbose.txt`

[ntopng-with-mariadb-verbose.txt](https://github.com/Homebrew/homebrew-core/files/1053816/ntopng-with-mariadb-verbose.txt)

`tyr:~/Library/Logs/Homebrew/ntopng benc$ brew gist-logs ntopng`

https://gist.github.com/dafdbff4cfef9bbe6b62cc470f61569b

**Comment by ilovezfs** [comment]
You can report the problem upstream. Also let's keep the discussion confined to #14278.

**Pull request closed without merging**
