### PR TITLE
joplin 0.10.85

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@chrmoritz any idea what's going on with the test failure here? I'm not seeing it locally.
```
==> brew test joplin --verbose
==> FAILED
Testing joplin
/usr/bin/sandbox-exec -f /tmp/homebrew20180103-7634-tlxaw0.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/joplin.rb --verbose
==> /usr/local/Cellar/joplin/0.10.85/bin/joplin config editor subl
/usr/local/Cellar/joplin/0.10.85/libexec/lib/node_modules/joplin/main.js:23
Resource.fsDriver_ = fsDriver;
                   ^

TypeError: Cannot set property 'fsDriver_' of undefined
    at Object.<anonymous> (/usr/local/Cellar/joplin/0.10.85/libexec/lib/node_modules/joplin/main.js:23:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by chrmoritz** [comment]
Can reproduce this locally with both 0.10.85 and 0.10.84 but not with 0.10.83. Looks like something in https://github.com/laurent22/joplin/compare/caae7f7cf89300375479d71014bf23ce6a06d6df...70a33f8533030fbba3bc0e573edb02ea67d50fb5#diff-41a974b9a7f8898159da7f61c824178d has broken it.

**Comment by chrmoritz** [comment]
Ah it's because of case-sensitive file systems. On the fs it's `libexec/lib/node_modules/joplin/lib/models/Resource.js` but it's `require('lib/models/resource.js');`.

**Comment by ilovezfs** [comment]
And your local fs is case-insensitive?

**Comment by chrmoritz** [comment]
Right, I still wonder why the test passes for you locally. Node modules system should always handle module imports case sensitive.

Anyway it looks like the upstream tarball contains the file correctly lower cased files. I don't know why brew/npm is upper casing them during install yet.

**Comment by ilovezfs** [comment]
My file system is case sensitive.

**Comment by chrmoritz** [comment]
A local npm install contains also lower cased files. It looks like it's brew, which does the upper casing? 😕

**Comment by ilovezfs** [comment]
unlikely

**Comment by chrmoritz** [comment]
I think it may be related to some stuff we do in Language::node

**Comment by ilovezfs** [comment]
The pack?

**Comment by chrmoritz** [comment]
Right, it's the pack, which is upper casing the files.

**Comment by ilovezfs** [comment]
npm :bug: ?

**Comment by ilovezfs** [comment]
Or maybe they're supposed to be upper case …

**Comment by chrmoritz** [comment]
No, I'm stupid. The upstream tarball already contains them uppercased. I've just accidentally downloaded the 0.10.83 last time.

**Comment by ilovezfs** [comment]
hehe

**Comment by chrmoritz** [comment]
Looks like they get upper cased during the [rsync](https://github.com/laurent22/joplin/blob/master/CliClient/build.sh#L7) on their upstream release machine somehow.

**Comment by ilovezfs** [comment]
@chrmoritz I wonder if it's a regression in node-tar

**Comment by ilovezfs** [comment]
@chrmoritz hmm seems fixed in 0.10.86? https://github.com/Homebrew/homebrew-core/pull/22474

**Pull request closed without merging**
