### PR TITLE
dnscrypt-proxy 1.7.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Checking for Homebrew updates...
==> Pouring dnscrypt-proxy-1.7.0.mavericks.bottle.tar.gz
==> Using the sandbox
==> /usr/local/Cellar/dnscrypt-proxy/1.7.0/bin/dnscrypt-update-resolvers
Last 150 lines from /Users/brew/Jenkins/pr-core/version/mavericks/logs/dnscrypt-proxy/01.dnscrypt-update-resolvers:
Sun Jul 31 16:29:32 +0100 2016

/usr/local/Cellar/dnscrypt-proxy/1.7.0/bin/dnscrypt-update-resolvers
```
well isn't that informative.

**Comment by DomT4** [comment]
I'd just retry the build, personally. This seems to fail on Mavericks alone without any real consistency.

**Comment by ilovezfs** [comment]
@DomT4 yup :green_apple: this time. Weird. :ship:?

**Comment by DomT4** [comment]
👍

**Pull request closed without merging**
