### PR TITLE
berkeley-db@5 5.3.28 (new formula)

### PR DESCRIPTION
**Pull request by onlynone**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Should we remove berkeley-db@4, which is not maintained anymore by upstream?

**Comment by ilovezfs** [comment]
There are lots of people still using @4 so I don't think we're ready to remove that yet.

Is @5 still maintained?

**Comment by ilovezfs** [comment]
As far as I can tell the answer to that question is no, the prior versions are not maintained. While @4 is grandfathered in as long as it remains popular, the current [guidelines for versioned formulae](https://github.com/Homebrew/brew/blob/master/docs/Versions.md) preclude adding another unmaintained version of berkeley-db. Thanks for the PR nonetheless @onlynone

**Comment by onlynone** [comment]
Sorry, I should have mentioned I thought it should be included because 5.x is the last version released under the old Sleepycat License.  Thought some people might find that useful. Installing the python bsddb bindings with v6 installed threw up some warnings.

**Pull request closed without merging**
