### PR TITLE
terraform 0.7.0

### PR DESCRIPTION
**Pull request by hrak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Upgrade terraform to version 0.7.0

### CODE REVIEW

**Comment by erickt** [comment]
@hrak: With this commit, terraform is now emitting these warnings:

```
[WARN] /usr/local/Cellar/terraform/0.7.0/bin/terraform-provider-tls overrides an internal plugin for tls-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
[WARN] /usr/local/Cellar/terraform/0.7.0/bin/terraform-provider-cobbler overrides an internal plugin for cobbler-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
[WARN] /usr/local/Cellar/terraform/0.7.0/bin/terraform-provider-clc overrides an internal plugin for clc-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
...
```

Would it be possible to remove this? It might be as simple as removing https://github.com/hrak/homebrew-core/blob/aa800fb2fddbedf1b615fc9f952961fdc5086210/Formula/terraform.rb#L64.

**Comment by DomT4** [comment]
>  It might be as simple as removing https://github.com/hrak/homebrew-core/blob/aa800fb2fddbedf1b615fc9f952961fdc5086210/Formula/terraform.rb#L64.

I doubt it. That's the build process for `terraform`. Wouldn't be much of an installation to install without that 😃.

Can you elaborate on where you're seeing those warnings? Are they build or runtime?

**Comment by RichardKnop** [comment]
👍 I would like this merged soonish. Terraform 0.7 has some really good new features that could simplify our manifests.

**Comment by ruudk** [comment]
🙏

**Comment by hrak** [comment]
@erickt This is a documented change in Terraform 0.7.0. The plugins are no longer provided as seperate binaries:

> In versions of Terraform prior to 0.7, each plugin shipped as a separate binary. In versions of Terraform >= 0.7, all of the official plugins are shipped as a single binary. This saves a lot of disk space and makes downloads faster for you!
> 
> However, when you upgrade you will need to manually delete old plugins from disk.
> 

See https://www.terraform.io/docs/internals/internal-plugins.html for more info

**Comment by olly** [comment]
I just installed this formula after uninstalling all previous versions of terraform. It looks as if the separate provider binaries are still built. I assume to keep backwards compatibility with other tooling. Once I removed all binaries except `terraform` from `/usr/local/Cellar/terraform/0.7.0/bin` the warnings were silenced.

**Comment by MikeMcQuaid** [comment]
> 👍 I would like this merged soonish. Terraform 0.7 has some really good new features that could simplify our manifests.

@RichardKnop Please be patient, we're volunteers working on our free time.

**Comment by DomT4** [comment]
> I just installed this formula after uninstalling all previous versions of terraform. It looks as if the separate provider binaries are still built. I assume to keep backwards compatibility with other tooling. Once I removed all binaries except terraform from /usr/local/Cellar/terraform/0.7.0/bin the warnings were silenced.

Interesting. Thanks for that, and to @hrak for the answer linking the upstream documentation. That's the sort of thing that's useful on deciding how to move ahead.

I'm unsure it's great UX to install executables that are essentially there to nag users to remove said executables, but it seems to be upstream's intention. The question largely is whether or not _we_ should remove those executables so users don't see a flood of warnings.

**Comment by kpumuk** [comment]
@DomT4 Another option would be to add a flag like `--with-deprecated-binaries`, and not install them by default

**Comment by DomT4** [comment]
That'd be acceptable to me, at least. We could just execute:
```ruby
rm_f Dir[bin/"*"].select { |f| f.to_s.include?("terraform-") }
```
Or some variation thereof.

If people feel an option is a better fit than an outright removal we could wrap that in a `if build.without? "deprecated-executables"` flag & respective `option "with-deprecated-executables", "Explanation"`.

**Comment by DomT4** [comment]
The official zip upstream for OS X/macOS only includes the `terraform` executable, so I think we'd be alright to get rid of the rest unconditionally, unless that sounds unacceptable to those of you who actually use `terraform`.

**Comment by mwarkentin** [comment]
Works for me (light TF user).

**Comment by kpumuk** [comment]
Works for me as well

**Comment by DomT4** [comment]
Great. Thanks for the feedback both. @hrak If you've no objection as well, would you mind tacking that into the formula here:

```diff
diff --git a/Formula/terraform.rb b/Formula/terraform.rb
index 3e1d5fe..fc67cae 100644
--- a/Formula/terraform.rb
+++ b/Formula/terraform.rb
@@ -74,6 +74,7 @@ class Terraform < Formula
       bin.install Dir["bin/*"]
       zsh_completion.install "contrib/zsh-completion/_terraform"
     end
+    rm_f Dir[bin/"*"].select { |f| f.to_s.include?("terraform-") }
   end
 
   test do
```

I think we'll be in a good place to ship this with that tweak.

**Comment by kpumuk** [comment]
Or just remove `bin.install Dir["bin/*"]` ?

**Comment by DomT4** [comment]
Heh, I missed the `bin.install "bin/terraform-terraform" => "terraform"` line above. Removing the extra `bin.install Dir["bin/*"]` is certainly simpler 🙈.

**Comment by hrak** [comment]
PR updated with requested changes (removed ```bin.install Dir["bin/*"]```)

**Comment by MikeMcQuaid** [comment]
Sorry for the delay. Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by ruudk** [comment]
Thanks all! Very awesome :D

**Pull request closed without merging**
