### PR TITLE
afsctool: Remove formula as it is unfree

### PR DESCRIPTION
**Pull request by amarshall**
This package has copyrighted code with no license, and is thus unfree and not eligible for inclusion in homebrew-core.

https://github.com/RJVB/afsctool/issues/56

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
that is really annoying, let's see how they respond on it (I feel like that might be simply license misunderstanding/misusage)

**Comment by carlocab** [comment]
CC @Homebrew/plc

**Comment by SMillerDev** [comment]
I'd say disabling it is good enough, especially now that we have the API. And it's the better user experience.

I would vote against waiting for any sort of clarification on an old closed issue.

**Comment by MikeMcQuaid** [comment]
> The code I wrote myself clearly states that I make it available without any form of license (= restriction) at all. IMO that's all there is to know.

This sounds like we're being unnecessarily pedantic here. If they wrote this: it's not proprietary.

---

> thus unfree

This is not our criteria for inclusion.

> 8+ months since they replied with their “clarification” that itself is ambiguous

If it's ambitious, we should err on the side of "continue to package this software that people find useful". 

---

Assuming I've not grossly misunderstood the above: strong 👎🏻 from me on removal/deprecation/disabling.

**Comment by carlocab** [comment]
> > The code I wrote myself clearly states that I make it available without any form of license (= restriction) at all. IMO that's all there is to know.
> 
> This sounds like we're being unnecessarily pedantic here. If they wrote this: it's not proprietary.
> 
> > thus unfree
> 
> This is not our criteria for inclusion.
> 
> > 8+ months since they replied with their “clarification” that itself is ambiguous
> 
> If it's ambitious, we should err on the side of "continue to package this software that people find useful".
> 
> Assuming I've not grossly misunderstood the above: strong 👎🏻 from me on removal/deprecation/disabling.

My understanding is exactly the same as all of the above, FWIW.

**Comment by alebcay** [comment]
> This sounds like we're being unnecessarily pedantic here. If they wrote this: it's not proprietary.

> This is not our criteria for inclusion.

I have no strong opinion on inclusion or exclusion of this particular formula, but the language at https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae refers explicitly (and exclusively) to DFSG licenses. Maybe the guidelines there should be relaxed to better reflect what we want to include/exclude, based on the discussion in this issue.

**Comment by MikeMcQuaid** [comment]
> At the very least, upstream's comment about intended licensing (that is, with no restrictions) should probably be linked in this formula.

Agreed.

**Comment by SMillerDev** [comment]
We can use `:cannot_represent`

**Comment by colindean** [comment]
I think `:cannot_represent` would suffice. A chunk of the code is GPLv3, a chunk is Boost, and that one file is _essentially_ public domain, but the author hasn't said the incantation in the Right Way. None of `any_of` or `all_of` can accurately represent the reality of this mixed-license source code, methinks.

Has anyone thought to put up a PR that perhaps goes the route of [SQLite's public domain + blessing](https://github.com/sqlite/sqlite/blob/f1f4f090c77dc0d36829999a2b57167851a5df2d/src/auth.c#L4C4-L11)?

> The author disclaims copyright to this source code. <blessing text>

Some folks just need a nudge.

**Comment by MikeMcQuaid** [comment]
> We can use `:cannot_represent`

That also seems far too strong here. I think this is fine as-is. This PR is an attempt to solve a problem that doesn't exist.

> If it is to remain included, what identifier should be added to the `license` field?

It is fine as-is. If we really, really, really want to do something: add a comment above it with a link to the relevant issue.

> Problem is that “without any form of license” means it’s non-free and copyrighted in most (all?) jurisdictions. ... I dunno, and IANAL.

I don't agree. Unless someone is an actual copyright lawyer who can speak to the legal status in multiple jurisdictions here: let's leave it as-is.

> and that one file is _essentially_ public domain, but the author hasn't said the incantation in the Right Way.

This is very much up for debate and: I don't agree with this interpretation.

> Some folks just need a nudge.

They've had a nudge and they've provided clarification. 

Similarly, some folks need to chill out about license minutiae. 

If in doubt, with any decision like this in Homebrew really, we should ask: "what is the most useful outcome to the users of Homebrew".

From https://formulae.brew.sh/analytics/install-on-request/365d/: this formula is in the top 5000 formulae in the Homebrew ecosystem, was installed on request by >1000 people last year.

On that basis: it is clearly not "most useful" to remove it based on a minor licensing disagreement.

`license all_of: ["GPL-3.0-only", "BSL-1.0"]` most accurately describes to me what the upstream repository, GitHub detection AND the author all state it is so I think it should remain as-is.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry.

**Pull request closed without merging**
