### PR TITLE
cockroach 2.1.6

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
```
/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64/link: /usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: segmentation fault
```

**Comment by danielb2** [comment]
What's the problem here ?

**Comment by SMillerDev** [comment]
the build is failing and nobody is fixing it.

**Comment by danielb2** [comment]
The failure log in jenkins appears to be long gone, and there's nothing in the commit that stands out to cause failures

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by danielb2** [comment]
seems to look good now

**Pull request closed without merging**
