### PR TITLE
dnsee 0.2.0 (new formula)

### PR DESCRIPTION
**Pull request by bschaatsbergen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Due to the nature of this tool it's very hard to add a test to test the applications functionality, the response contains a TTL which changes every second.

**Comment by SMillerDev** [comment]
> the response contains a TTL which changes every second.

So check for the other parts and/or match the TTL with a regex.

**Comment by bschaatsbergen** [comment]
cc @chenrui333 - it would be awesome to get this into homebrew-core 🍺

**Comment by fxcoudert** [comment]
Hi @bschaatsbergen this is a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

This comes from the github stats, but also we do have some statistics from your own tap, that show 3 installs in the last 30 days, so very low usage. For now, the personal tap hosting is probably a better fit for this. (But we would be happy to reconsider if/when usage of your software becomes more widespread!)

**Comment by bschaatsbergen** [comment]
> Hi @bschaatsbergen this is a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.
> 
> This comes from the github stats, but also we do have some statistics from your own tap, that show 3 installs in the last 30 days, so very low usage. For now, the personal tap hosting is probably a better fit for this. (But we would be happy to reconsider if/when usage of your software becomes more widespread!)

Hi @fxcoudert,

Thanks for responding. We acknowledge the notability criteria and low usage concerns. I'll work on gaining traction for the project before creating a new PR! :)

**Pull request closed without merging**
