### PR TITLE
cloudformation-cli: use python-certifi and pyyaml

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by alex** [comment]
Looks like an error building pyyaml related to cython. I believe this is probably an issue impacting many formula. Is there a correct fix?

**Comment by chenrui333** [comment]
> Looks like an error building pyyaml related to cython. I believe this is probably an issue impacting many formula. Is there a correct fix?

the fix is to upgrade to pyyaml 6.0.1

**Comment by chenrui333** [comment]
- relates to https://github.com/aws-cloudformation/cloudformation-cli/pull/1014

**Comment by alex** [comment]
👍, I had just discovered that the pin prevents this. So I suppose this is in a holding pattern for now.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
