### PR TITLE
openssl@3 3.0.0 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I've separated the commit adding `openssl@3` from #84822, and made minor modifications.

I haven't removed `openssl@1.1` because it's still supported until 11 September 2023. I think we can migrate formulae to this version of OpenSSL in separate PRs so we can ship this version to users who want to use it ASAP.

### CODE REVIEW

**Comment by SMillerDev** [comment]
A 404 on the source... Interesting.

**Comment by carlocab** [comment]
Nixed the patches, since they were for the 1.1 branch. I'll try to track down the patches on the 3.0 branch at some point.

**Comment by carlocab** [comment]
Well, that's weird.
```
==> brew linkage --test openssl@3
==> FAILED
Missing libraries:
  unexpected (libcrypto.so.3)
  unexpected (libssl.so.3)
```

**Comment by jonchang** [comment]
Thanks, I'm still in the process of analyzing the openssl@3 failures from the other pull request, and I'll use that one to start with the easy migrations to @3 (probably something like: no failures, leaf formulae only)

**Review by jonchang — APPROVED** [review]

**Pull request closed without merging**
