### PR TITLE
x264 r2917

### PR DESCRIPTION
**Pull request by Moisan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Bump `x264` to the latest commit on the stable branch. I also removed the `with-10-bit` option since by default configure now compiles with all bit-depths.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Quite a few formulas need a revision bump…

**Comment by igas** [comment]
🤖 we are still tracking upstream issue here.

**Comment by Moisan** [comment]
I screwed up the history by rebasing after a merge from master. Fixing this...

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Tests are all fine, `qmmp` is a false positive from the linkage audit. Good to merge!

**Pull request closed without merging**
