### PR TITLE
bzt 1.15.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/bzt/1.15.1/libexec/include -I/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c fuzzyset/cfuzzyset.c -o build/temp.macosx-10.15-x86_64-3.9/fuzzyset/cfuzzyset.o
    fuzzyset/cfuzzyset.c:6309:35: error: no member named 'tp_print' in 'struct _typeobject'
      __pyx_type_9cfuzzyset_cFuzzySet.tp_print = 0;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    1 error generated.
    error: command '/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
    Running setup.py install for fuzzyset: finished with status 'error'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/bzt/1.15.1/libexec/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-qv1fvjvw/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-qv1fvjvw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-_764cxtm/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/bzt/1.15.1/libexec/include/site/python3.9/fuzzyset Check the logs for full command output.
```

**Comment by chenrui333** [comment]
```
pkg_resources.DistributionNotFound: The 'importlib-metadata<3,>=0.12' distribution was not found and is required by virtualenv

```

**Comment by chenrui333** [comment]
Since we no longer support 10.13, I think this PR is ready to go.

**Comment by chenrui333** [comment]
failed on 10.15 test build

**Review by Moisan — APPROVED** [review]

**Pull request closed without merging**
