### PR TITLE
cpmtools: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
That doesn't seem to be enough, CI is still failing

**Comment by danielnachun** [comment]
Hmm, weird.  I can't reproduce this failure at all in Docker.  I'll have to look into this more.

**Comment by cho-m** [comment]
The following command doesn't work in `dash` when `FSED_CPM=`
```sh
[ "$(FSED_CPM)" == '' ] || $(INSTALL) -s -m 755 fsed.cpm $(DESTDIR)$(BINDIR)/fsed.cpm
```

Looks like this feature is enabled when `ncurses` is installed:
```configure
dnl Check for curses. If not found, don't build fsed.cpm
dnl Try both curses and ncurses
AC_CHECK_LIB(curses, printw, FSED_CPM=fsed.cpm LIBS="-lcurses $LIBS", FSED_CPM=)
```

So, easiest fix may be to add `uses_from_macos "ncurses"` (assuming it picks up Homebrew copy).

**Comment by danielnachun** [comment]
That worked! Thanks @cho-m, that was a simple solution to a very tricky problem.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
