### PR TITLE
boxes 2.0.0

### PR DESCRIPTION
**Pull request by mathomp4**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

More complex than a simple `bump-formula-pr` so I'm trying this by hand.

### CODE REVIEW

**Comment by mathomp4** [comment]
A note: I think I have the `depends_on` correct. The main issue is that my brew installation has a *lot* of packages, so I think `pcre` and `libunistring` were already there. I don't have a place to test a "bare" brew.

**Comment by SMillerDev** [comment]
> A note: I think I have the depends_on correct. The main issue is that my brew installation has a lot of packages, so I think pcre and libunistring were already there. I don't have a place to test a "bare" brew.

Brew won't expose programs to the build process unless the process depends on it. If it is enough on your machine it's enough everywhere.

**Comment by mathomp4** [comment]
Oop. Let me fix an issue...

**Comment by mathomp4** [comment]
Ugh. I guess there are two pcre! Once more!

**Review by carlocab — APPROVED** [review]
Thanks, @mathomp4.

For future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings. For example, yours would have been
```
bosses 2.0.0
```

Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

**Comment by mathomp4** [comment]
> Thanks, @mathomp4.
> 
> For future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings. For example, yours would have been
> 
> ```
> bosses 2.0.0
> ```
> 
> Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

Sorry! I'm used to `bump-formula-pr` here and my other project prefer more verbose PR titles. :)

**Comment by carlocab** [comment]
`bump-formula-pr` writes the expected commit messages, so you could've patterned this PR after those. But that's fine, now you know for next time.

**Pull request closed without merging**
