### PR TITLE
tarantool: revert to stable version

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
https://github.com/tarantool/tarantool/releases

2.7.1 is still in beta...

**Comment by carlocab** [comment]
Looks like we need to roll this one back to 2.6.2.

**Comment by chenrui333** [comment]
I think you are right.

**Comment by carlocab** [comment]
Yes, sorry, I actually knew that 2.7.1 was beta; I don't know why I approved the last version bump. My mistake.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
