### PR TITLE
Preventing diffutils to shadow system diff

### PR DESCRIPTION
**Pull request by mys721tx**
This commit prevents diffutils to shadow the system diff. The binaries with original names can be added to the path using the same method as that of `coretuils`.

Caveats and renaming codes are borrowed from `coreutils.rb`.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
What's the upside here? IIRC `coreutils` is done like this because it can break things otherwise, but it seems unlikely having a GNU `diff` in your `PATH` rather than the BSD one is going to routinely risk breakage.

**Comment by mys721tx** [comment]
I was aiming for a systematic way to load GNU packages that shadows the system ones. By putting binaries with the original names in `gnubin`, the two packages coexist and users can choose which one is in their `PATH`.

**Comment by fxcoudert** [comment]
I'm not sure we want to do it systematically… only where there is marked incompatibility

**Comment by DomT4** [comment]
> users can choose which one is in their PATH.

Given nothing in Homebrew `depends_on "diffutils"` I think there's an argument to be made that users are _already_ choosing which one is in their `PATH`, to be honest.

I know we do this sort of thing _a lot_ for GNU stuff that shadows the system but I'm not finding a compelling reason to extend that further in this case. Not my call to make though, FWIW.

**Pull request closed without merging**
