### PR TITLE
diffoscope 84

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @ilovezfs re the code comment about https://github.com/Homebrew/brew/commit/4fb7626ce55edd2db910781298c770cd49c1302b. Reasonably sure that's the problem.

### CODE REVIEW

**Comment by DomT4** [comment]
Not really sure what's going on here, to be honest. It seems to be a Homebrew thing, but, not quite sure where/why.

Locally if I untar it & then run:
```
PYTHONPATH="/Users/xyz/Downloads/diffoscope-84/testing/lib/python3.6/site-packages/" python3 setup.py install --prefix=`pwd`/testing
```
it builds & installs fine.

**Comment by DomT4** [comment]
Going to comment out the `ENV.delete` just to see what happens on CI.

**Comment by DomT4** [comment]
And that worked fine. Now I'm even more confused. Where is `/usr/local/lib/python2.7/site-packages` slipping into my `PYTHONPATH` from, and apparently only during `brew` stuff. What.

**Comment by DomT4** [comment]
Meh. I have no idea. Dropped the commit. I'll keep looking around locally but 🤷‍♂️.

**Comment by ilovezfs** [comment]
Could it be the old `/Users/xyz/Library/Python/2.7/lib/python/site-packages/homebrew.pth`

**Comment by DomT4** [comment]
That's what I thought possible too, but `cat ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth` turns up nothing and neither does `mdfind "homebrew.pth"`.

**Comment by ilovezfs** [comment]
```
python -c "import sys; print sys.path"
```

**Comment by DomT4** [comment]
```
['', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/Cellar/protobuf/3.3.2/libexec/lib/python2.7/site-packages', '/usr/local/opt/libxml2/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0', '/usr/local/lib/python2.7/site-packages/gtk-2.0']
```

**Comment by ilovezfs** [comment]
if you `brew unlink python` does it go away?

**Comment by DomT4** [comment]
Nope. `python -c "import sys; print sys.path"` then returns:

```
['', '/usr/local/lib/python2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']
```

**Comment by JCount** [comment]
Thanks @DomT4 🐃

**Comment by DomT4** [comment]
Thanks for the merge @JCount 🙇

**Pull request closed without merging**
