### PR TITLE
fceux 2.6.3

### PR DESCRIPTION
**Pull request by mjbudd77**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @mjbudd77. Can we switch this to Qt6? It might be enough to just do this:
```diff
diff --git a/Formula/fceux.rb b/Formula/fceux.rb
index 944f9dec472..9005a78bf77 100644
--- a/Formula/fceux.rb
+++ b/Formula/fceux.rb
@@ -19,7 +19,7 @@ class Fceux < Formula
   depends_on "pkg-config" => :build
   depends_on "ffmpeg"
   depends_on "minizip"
-  depends_on "qt@5"
+  depends_on "qt"
   depends_on "sdl2"
   depends_on "x264"
 
@@ -30,7 +30,7 @@ class Fceux < Formula
 
   def install
     ENV["CXXFLAGS"] = "-DPUBLIC_RELEASE=1" if build.stable?
-    system "cmake", ".", *std_cmake_args
+    system "cmake", ".", *std_cmake_args, "-DQT6=ON"
     system "make"
     cp "src/auxlib.lua", "output/luaScripts"
     libexec.install "src/fceux.app/Contents/MacOS/fceux"
```

**Comment by mjbudd77** [comment]
Last I checked fceux does build with Qt6, but most of my testing has been using Qt5.

**Comment by carlocab** [comment]
I'm inclined to give Qt6 a try. If it's broken and can't be fixed in a reasonable amount of time, we can switch it back to Qt5.

**Comment by mjbudd77** [comment]
Ok I will modify the formula to switch to Qt6

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
