### PR TITLE
node_exporter: Add caveats around configuration location

### PR DESCRIPTION
**Pull request by msiebuhr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Have you opened an upstream issue asking for support for a config file? I'd really prefer we not bolt on our own workaround for what should be a standard feature.

**Comment by msiebuhr** [comment]
It doesn't look like they'll add it: https://github.com/prometheus/node_exporter/issues/675

**Comment by ilovezfs** [comment]
@msiebuhr it sounds like it may already support it? https://github.com/prometheus/node_exporter/issues/675#issuecomment-335010265

**Comment by msiebuhr** [comment]
Indeed. I hadn't spotted that one. But as I read it, the file still has to contain the CLI arguments for the program.

The difference is merely `node_exporter $(< node_exporter.args)` vs `node_exporter @node_exporter.conf`.

**Comment by ilovezfs** [comment]
Yeah, the latter is probably a little nicer though since I think it means we can avoid the `sh -c` in the plist.

**Comment by msiebuhr** [comment]
Doing that changes make the `node_exporter.args`-file required (instead of optional):

```diff
--- a/Formula/node_exporter.rb
+++ b/Formula/node_exporter.rb
@@ -45,9 +45,8 @@ class NodeExporter < Formula
         <string>#{plist_name}</string>
         <key>ProgramArguments</key>
         <array>
-          <string>sh</string>
-          <string>-c</string>
-          <string>#{opt_bin}/node_exporter $(&lt; #{etc}/node_exporter.args)</string>
+          <string>#{opt_bin}/node_exporter</string>
+          <string>@#{etc}/node_exporter.args</string>
         </array>
         <key>RunAtLoad</key>
         <true/>
```

```shell
$ /usr/local/opt/node_exporter/bin/node_exporter @/usr/local/etc/node_exporter.args
node_exporter: error: failed to open arguments file "/usr/local/etc/node_exporter.args": open /usr/local/etc/node_exporter.args: no such file or directory, try --help
```

That leaves us with a few options
 1. Keep using the shell-trick (so the args-file is optional).
 2. Always install an (possibly empty) args-file.
 3. Try to get a change through upstream as to make the `@file`-thing ignore missing files.

IMHO, 3 would be nice, but a lot more work and might not go through. The shell-trick *does* work, so I'm tempted to leave it as-is.

**Comment by ilovezfs** [comment]
Fair enough. Shipped. Thanks again @msiebuhr

**Pull request merged**
