### PR TITLE
allegro: fix build on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
@carlocab `allegro` uses CMake so its use of `flat_namespace` is not due to the `libtool` bug.  I added it the allowlist because it's not clear to me if the usage is unintentional or not.

**Comment by SMillerDev** [comment]
Can you ask upstream then?

**Comment by cho-m** [comment]
The build flags were added back in 2008 (around OS X 10.5), so I think it is just outdated upstream. Original commit https://github.com/liballeg/allegro5/commit/646aa94fc52640e79864cb471eff8535d02fd719

Current location after some refactors: https://github.com/liballeg/allegro5/blob/fbb3f0c9cb62fe19bba58e8a3fa7892196070fc8/cmake/Common.cmake#L157-L163
```cmake
    # Suppress errors about _mangled_main_address being undefined on Mac OS X.
    if(MACOSX)
        set_target_properties(${target}
            PROPERTIES
            LINK_FLAGS "-flat_namespace -undefined suppress"
            )
    endif(MACOSX)
```

**Comment by danielnachun** [comment]
Thanks for finding that @cho-m.  I'm going to open a pull request on their `allegro` GitHub to remove this as I agree that it just seems to be outdated.  I'll also patch this out of the CMake file (and link to the PR) and drop the commit to add `allegro` to the flat namespace allowlist.

**Comment by danielnachun** [comment]
Unrelated to the flat namespace issue, I forgot that this is blocked until https://github.com/Homebrew/homebrew-core/pull/101177 is merged, because `dumb` currently provides no shared library and the build for `allegro` fails on Linux because of this.

**Comment by danielnachun** [comment]
I tried patching out the addition of the `-flat_namespace` flag locally before submitting a PR upstream, and to my surprise, the build fails with this error:
```
Undefined symbols for architecture x86_64:
  "__al_mangled_main", referenced from:
      _main in osx_main.m.o
ld: symbol(s) not found for architecture x86_64
```
This is reminiscent of the error that originally motivated them to add the flag in the first place.  There is a lengthy unresolved issue about this on the upstream GitHub https://github.com/liballeg/allegro5/issues/555 and it's still not clear to me why this happens.  

At this point my conclusion is that we probably should **not** try to remove this flag as it seems necessary for the build to succeed, though I'm happy to hear if anyone else has thoughts on how to proceed.

**Comment by cho-m** [comment]
Did you try changing `-undefined` from `suppress` to `dynamic_lookup` similar to libtool patches?

**Comment by danielnachun** [comment]
Ah, I did not.  Let me see what happens when I try that instead.

**Comment by danielnachun** [comment]
Using `-undefined dynamic_lookup` fixed the build failure on macOS.  That gives me what I need to submit the upstream PR for this, which I will link to in a comment.

Note that we are still blocked until https://github.com/Homebrew/homebrew-core/pull/101177 is merged, but that is now fixed as well so we should be close!

**Review by SMillerDev — DISMISSED** [review]

**Comment by danielnachun** [comment]
I rebased this now that https://github.com/Homebrew/homebrew-core/pull/101177 is merged and the Linux build passes now.  This should be ready to go!

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
