### PR TITLE
Mass migration of remaining formulas to OpenSSL 1.1

### PR DESCRIPTION
**Pull request by fxcoudert**
Nuke_d3c65a_638430

### CODE REVIEW

**Comment by chenrui333** [comment]
looks like build failed:
11:26:20 ==> brew readall --aliases homebrew/core
11:26:29 ==> FAILED
11:26:29 Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rust.rb
11:26:29 rust: undefined method `revision' for #<SoftwareSpec:0x00007fe862a494b0>

**Comment by fxcoudert** [comment]
@chenrui333 indeed, my script made a mistake there… should be fixed (though I expect plenty more failures on the first round of testing)

**Comment by chenrui333** [comment]
was about to say it, but seems like you got it. :)

**Comment by fxcoudert** [comment]
- `rtmpdump` has a patch from FreeBSD https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231940

**Comment by fxcoudert** [comment]
- Formulas needing revision: `ffmpeg ffmpeg@2.8 doitlive fb-client`

**Comment by scpeters** [comment]
unrelated error from currently running build:

~~~
11:18:34 ==> brew linkage --test coturn
11:18:35 ==> FAILED
11:18:35 Broken dependencies:
11:18:35   /usr/local/opt/hiredis/lib/libhiredis.0.14.dylib (hiredis)
~~~

probably a rev-bump for coturn is in order, but I'll hold off in case this build has a chance of working

**Comment by fxcoudert** [comment]
- Unrelated `coturn` error fixed in https://github.com/Homebrew/homebrew-core/commit/f3182b7155cac2a1fefd214a7a0e43e12911d95e
- `xrootd` fails to build with a Python issue:

```
In file included from /tmp/xrootd-20190906-24434-1o4wty4/xrootd-4.10.0/bindings/python/src/PyXRootDFile.cc:25:
/tmp/xrootd-20190906-24434-1o4wty4/xrootd-4.10.0/bindings/python/src/PyXRootD.hh:28:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
error: command 'clang' failed with exit status 1
make[2]: *** [bindings/python/python_bindings] Error 1
make[1]: *** [bindings/python/CMakeFiles/python_target.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

- `erlang@17` and `erlang@19` build but test fails with:

```
==> /usr/local/Cellar/erlang@19/19.3.6.13_1/bin/erl -noshell -eval crypto:start(). -s init stop
{"init terminating in do_boot",{undef,[{crypto,start,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
Error: erlang@19: failed
```

- `couchdb` test  fails, probably because it depends on broken `erlang@19`
- `ettercap` fails because of a harfbuzz/pango issue with headers:

```
In file included from /tmp/ettercap-20190906-10640-szhqbv/ettercap-0.8.3/src/ec_interfaces.c:31:
In file included from /tmp/ettercap-20190906-10640-szhqbv/ettercap-0.8.3/src/interfaces/gtk3/ec_gtk3.h:4:
In file included from /usr/local/include/gtk-3.0/gtk/gtk.h:30:
In file included from /usr/local/include/gtk-3.0/gdk/gdk.h:32:
In file included from /usr/local/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30:
In file included from /usr/local/include/gtk-3.0/gdk/gdktypes.h:35:
In file included from /usr/local/include/pango-1.0/pango/pango.h:25:
In file included from /usr/local/include/pango-1.0/pango/pango-attributes.h:25:
In file included from /usr/local/include/pango-1.0/pango/pango-font.h:25:
/usr/local/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: 'hb.h' file not found
#include <hb.h>
         ^~~~~~
```

- `freeswitch` appears not to support OpenSSL 1.1:

```
In file included from srtp/srtp.c:46:
In file included from ./include/srtp.h:53:
In file included from ./crypto/include/crypto_kernel.h:50:
In file included from ./crypto/include/prng.h:17:
./crypto/include/aes_icm_ossl.h:66:20: error: field has incomplete type 'EVP_CIPHER_CTX' (aka 'struct evp_cipher_ctx_st')
    EVP_CIPHER_CTX ctx;
                   ^
/usr/local/Cellar/openssl@1.1/1.1.1c/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'struct evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
               ^
In file included from srtp/srtp.c:50:
./crypto/include/aes_gcm_ossl.h:58:18: error: field has incomplete type 'EVP_CIPHER_CTX' (aka 'struct evp_cipher_ctx_st')
  EVP_CIPHER_CTX ctx;
                 ^
/usr/local/Cellar/openssl@1.1/1.1.1c/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'struct evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
               ^
2 errors generated.
```

- `httest` does not support OpenSSL 1.1 either:

```
lua_crypto.c:127:38: error: invalid application of 'sizeof' to an incomplete type 'EVP_MD_CTX' (aka 'struct evp_md_ctx_st')
  EVP_MD_CTX *c = lua_newuserdata(L, sizeof(EVP_MD_CTX));
                                     ^     ~~~~~~~~~~~~
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:92:16: note: forward declaration of 'struct evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
```

- `ipmitool`, `isync`, `john-jumbo` do not either
- `konoha` cannot find python headers:

```
/tmp/konoha-20190906-69687-1nz087f/konoha3-0.1/package/python/python_glue.c:25:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
```

- `liboauth` says `C: 23: col 12: sha256 is empty`
- `libopendkim` needs a patch from FreeBSD for OpenSSL 1.1 https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223568

**Comment by fxcoudert** [comment]
- The `xrootd` failure I cannot reproduce locally… but I hope it can be fixed by adding `-DENABLE_PYTHON=OFF`

**Comment by fxcoudert** [comment]
Second round started, now we wait…

**Pull request closed without merging**
