### PR TITLE
contentful-cli 1.3.23

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/contentful-cli/1.3.23/bin/contentful space list 2>&1
Error: contentful-cli: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </🚨\ \ Error:\ You\ have\ to\ be\ logged\ in\ to\ do\ this\./> was expected to be =~
<"internal/modules/cjs/loader.js:584\n" +
"            if (e.code !== 'ERR_PACKAGE_PATH_NOT_EXPORTED') throw e;\n" +
"                                                            ^\n" +
"\n" +
"Error [ERR_INVALID_PACKAGE_TARGET]: Invalid \"exports\" main target \"index.js\" defined in the package config /usr/local/Cellar/contentful-cli/1.3.23/libexec/lib/node_modules/contentful-cli/node_modules/is-promise/package.json\n" +
"    at resolveExportsTarget (internal/modules/cjs/loader.js:542:13)\n" +
"    at resolveExportsTarget (internal/modules/cjs/loader.js:581:20)\n" +
"    at applyExports (internal/modules/cjs/loader.js:455:14)\n" +
"    at resolveExports (internal/modules/cjs/loader.js:508:23)\n" +
"    at Function.Module._findPath (internal/modules/cjs/loader.js:632:31)\n" +
"    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)\n" +
"    at Function.Module._load (internal/modules/cjs/loader.js:884:27)\n" +
"    at Module.require (internal/modules/cjs/loader.js:1074:19)\n" +
"    at require (internal/modules/cjs/helpers.js:72:18)\n" +
"    at Object.<anonymous> (/usr/local/Cellar/contentful-cli/1.3.23/libexec/lib/node_modules/contentful-cli/node_modules/run-async/index.js:3:17) {\n" +
"  code: 'ERR_INVALID_PACKAGE_TARGET'\n" +
"}\n">.
```

**Comment by Bo98** [comment]
Maybe not compatible with Node 14? Try Node 12.

**Comment by chenrui333** [comment]
> Maybe not compatible with Node 14? Try Node 12.

I tried with node 13 locally, it did not quite work out either.

**Comment by chenrui333** [comment]
outside brew, it works fine though.

**Comment by chenrui333** [comment]
node@12 might be good idea, trying it now.

**Comment by Bo98** [comment]
Tracked it down to https://github.com/then/is-promise/issues/12.

I suppose a problem with our npm formulae right now is that they don't really lock versions, so this `is-promise` update released 2 hours ago applied to all dependents immediately.

Maybe we should try `npm ci` rather than `npm install`. That apparently properly locks dependencies to use package-lock.json, which is a good thing for reproducability.

**Comment by chenrui333** [comment]
I thought this is something related to this, `https://github.com/nodejs/node/issues/32107`?

**Comment by chenrui333** [comment]
`npm ci` does not work:

```
==> npm ci -ddd --global --build-from-source --cache=/Users/ruichen/Library/Caches/Homebrew/npm_cache --prefix=/usr/
Last 15 lines from /Users/ruichen/Library/Logs/Homebrew/contentful-cli/01.npm:
npm verb argv "/usr/local/Cellar/node/14.0.0/bin/node" "/usr/local/opt/node/libexec/bin/npm" "ci" "-ddd" "--global" "--build-from-source" "--cache=/Users/ruichen/Library/Caches/Homebrew/npm_cache" "--prefix=/usr/local/Cellar/contentful-cli/1.3.23/libexec" "/private/tmp/contentful-cli-20200425-2886-qj0hn8/package/contentful-cli-1.3.23.tgz"
npm verb node v14.0.0
npm verb npm  v6.14.4
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /usr/local/Cellar/contentful-cli/1.3.23/libexec/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/Cellar/contentful-cli/1.3.23/libexec/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm verb exit [ -2, true ]
npm timing npm Completed in 372ms
```

**Comment by Bo98** [comment]
Seems to have issues with `std_npm_install_args`. Was worth a shot.

**Comment by Bo98** [comment]
is-promise has released an update to fix the problem so I’ve restarted the CI run.

**Comment by chenrui333** [comment]
> `is-promise` has released an update to fix the problem so I’ve restarted the CI run.

Nice! Seems test failure got resolved now.

**Pull request closed without merging**
