### PR TITLE
dependency-check 6.3.2

### PR DESCRIPTION
**Pull request by jeremylong**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jeremylong** [comment]
Great - hitting the rate limiting again from the NVD...  I have an idea on how to resolve this for the next release. Note - I believe the failure above is only occurring during the homebrew build and would not occur during normal usage. This is because the downloads from the NVD are running multiple times because of the multiple builds - thus triggering the rate limiting from the NVD.

**Comment by SMillerDev** [comment]
Could a later start date help?

**Comment by jeremylong** [comment]
There needs to be a longer pause between the multiple executions of dependency-check. I'm going to make some of the time outs more configurable in the next version (too be released very soon) so that the builds here should work even with multiple executions - it'll just take longer to complete because it'll have longer time outs.

**Comment by SMillerDev** [comment]
Would a random timeout of a couple of seconds in the test block help?

**Pull request closed without merging**
