### PR TITLE
mercurial: fix shebang so it uses Homebrew Python

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @RokerHRO

### CODE REVIEW

**Comment by RokerHRO** [comment]
Wow, that was quick. :-) Whould that update conflict with my manual edit in the shebang?

**Comment by ilovezfs** [comment]
@RokerHRO no. Just run `brew update` and `brew upgrade` once this ships.

**Comment by ilovezfs** [comment]
@RokerHRO this is now fixed.

**Comment by RokerHRO** [comment]
Excellent! Thank you! :-)

**Comment by MikeMcQuaid** [comment]
@RokerHRO Thanks again for your kind words ❤️

**Pull request closed without merging**
