### PR TITLE
go 1.17

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by marians** [comment]
Looks like Github actions are stuck here

**Comment by carlocab** [comment]
Not stuck; it really just does take ages. See previous Go PRs.

**Comment by carlocab** [comment]
ARM failures:
```
Error: 20 failed steps!
brew test --retry --verbose akamai
brew test --retry --verbose awsweeper
brew fetch --build-from-source --retry baidupcs-go
brew install --build-from-source cf-tool
brew install --build-from-source --only-dependencies clair
brew install --build-from-source clair
brew test --retry --verbose darksky-weather
brew test --retry --verbose darksky-weather
brew install --build-from-source dvm
brew install --build-from-source envoy
brew install --build-from-source envoy@1.18
brew test --retry --verbose func-e
brew fetch --build-from-source --retry helmfile
brew fetch --build-from-source --retry kubeprod
brew install --build-from-source mmctl
brew install --build-from-source mpdviz
brew test --retry --verbose ooniprobe
brew install --build-from-source pilosa
brew install --build-from-source virgil
brew test --retry --verbose xray
```
At least some of these (e.g. `envoy`) don't have ARM bottles. Some of them do, though (e.g. `darksky-weather`, but I think that's from a broken test rather than a broken formula).

**Comment by carlocab** [comment]
These are the ARM failures with bottles:
```
baidupcs-go
darksky-weather
darksky-weather
kubeprod
helmfile
mmctl
ooniprobe
xray
```

**Comment by roopakv** [comment]
@carlocab is there a way to help add ARM failures?

**Comment by SMillerDev** [comment]
Try building them with go 1.17 and fix them if they're broken.

**Comment by roopakv** [comment]
@SMillerDev some of them are flakes i guess, cos I got it to pass locally. and that is why I was confused

**Comment by carlocab** [comment]
You can help by trying to make the tests less flaky so they don't show up on the next Go PR, if you can.

**Comment by carlocab** [comment]
Mojave failures:
```
Error: 27 failed steps!
brew test --retry --verbose algernon
brew fetch --build-from-source --retry baidupcs-go
brew test --retry --verbose cartridge-cli
brew test --retry --verbose consul
brew test --retry --verbose convox
brew test --retry --verbose cql
brew test --retry --verbose devd
brew test --retry --verbose flux
brew test --retry --verbose ghz-web
brew fetch --build-from-source --retry helmfile
brew test --retry --verbose ksync
brew fetch --build-from-source --retry kubeprod
brew test --retry --verbose minio-mc
brew install --build-from-source mmctl
brew test --retry --verbose modd
brew test --retry --verbose naabu
brew test --retry --verbose nomad
brew test --retry --verbose ooniprobe
brew test --retry --verbose orgalorg
brew test --retry --verbose orgalorg
brew test --retry --verbose ory-hydra
brew test --retry --verbose pulumi
brew test --retry --verbose sdns
brew test --retry --verbose syncthing
brew test --retry --verbose traefik
brew test --retry --verbose xray
brew test --retry --verbose yubikey-agent
```
I don't think all of these are just flaky tests.

**Comment by samuel** [comment]
A number of those failures seem to be related to https://github.com/golang/go/issues/46763

Specifically the comment:

```
@marwan-at-work the golang.org/x/sys/unix.libc_ioctl_trampoline error looks like what was fixed as part of #45702. The fix on your end should be to update golang.org/x/sys to latest (it looks like you are on a version before the fix at golang/sys@a76c4d0).
```

Referring to https://github.com/golang/go/issues/45702

**Comment by carlocab** [comment]
Big Sur failures are the same as on Mojave. Catalina failures are also the same except for `orgalorg`, which did not fail.

**Comment by roopakv** [comment]
I've started going to packages and updating x/sys and asking packages to cut new releases.  Feels like this will be a manual process and we need to split the work and get them upgraded and then rebase this branch

- [ ] ooniprobe
- [ ] algernon
- [ ] baidupcs-go
- [ ] cartridge-cli
- [ ] consul
- [ ] convox
- [ ] cql
- [ ] devd
- [ ] flux
- [ ] ghz-web
- [ ] helmfile
- [ ] ksync
- [ ] kubeprod
- [ ] minio-mc
- [ ] mmctl
- [ ] modd
- [ ] naabu
- [ ] nomad
- [ ] ooniprobe
- [ ] orgalorg
- [ ] orgalorg
- [ ] ory-hydra
- [ ] pulumi
- [ ] sdns
- [ ] syncthing
- [ ] traefik
- [ ] xray
- [ ] yubikey-agent

**Comment by blacktop** [comment]
Would it be possible for you all to kind of pin previous versions of Golang?  Like `brew install go1.16` and then all these packages that depend on Go can pin to a version and not hold up the release of NEW versions? #askingforafriendwholovesbrewandrunninglatestgoasap 😏

**Comment by roopakv** [comment]
@blacktop I am not a maintainer, so take my words with a grain of salt, but the only time that the community will really push things forward is if stuff is blocked.

Selfishly you will see me unblocking all major go versions just so I can a new go version on brew ASAP :) So while the maintainers are going to evaluate your suggestion, please pick a few packages above and help upgrade them. we can be done in the next few days.

**Comment by carlocab** [comment]
Thanks, @roopakv, for the work you've done!

> Would it be possible for you all to kind of pin previous versions of Golang? Like `brew install go1.16` and then all these packages that depend on Go can pin to a version and not hold up the release of NEW versions?

This just creates extra maintenance work that someone's going to have to do -- and given that we only have a small number of people helping to fix CI failures in Go PRs relative to the number of reactions, I doubt anyone's volunteering to do that, unfortunately. This entails:

1. Changing ~600 formulae that currently do `depends_on "go"` to `depends_on "go@x.y"`. (Easy.)
2. Updating each of ~600 formulae to the newest version of Go that they support as and when they're supported. (Not easy.)

The fastest way to get this merged really is to contribute to helping fix the CI failures.

**Comment by SMillerDev** [comment]
> Selfishly you will see me unblocking all major go versions just so I can a new go version on brew ASAP

Much appreciated @roopakv !

There's really no better group to fix these Go failures than the group of Go developers that seems to be here. And just like I find myself saying at every major Go release, if everyone just fixes one project from the list it would take very little time to merge this. We just need a pull request to upstream to use as a patch.

**Comment by sluongng** [comment]
So the alternative to fixing this upstream (and ask each packages maintainers to review/approve), we can just patch the formulas with a patch exported from the pending PR?

That should help us unblock the rollout of 1.17 a lot faster but then each formulas might be attached with a '.patch' file that need to be maintained/deprecated.

**Comment by SMillerDev** [comment]
We can use a pending PR as a patch, the important part for Homebrew is that upstream is aware of the issue and has a path forward. But it's pretty common to use pull requests as patches.

**Comment by bouk** [comment]
PR for devd: https://github.com/cortesi/devd/pull/117 and yubikey-agent: https://github.com/FiloSottile/yubikey-agent/pull/99 (I'd do the rest but don't have a very good internet connection right now)

For those who want to help, fork and check out one of the above projects and run the following commands:

```bash
git checkout -b upgrade-sys-go117
go get -u golang.org/x/sys@latest
git add go.mod go.sum
git commit -m "Update x/sys to support go 1.17" -m "See: https://github.com/golang/go/issues/46763"
git push -u origin upgrade-sys-go117
```

Then create a PR to the upstream project, copying and pasting the following message:

```
Updating x/sys so that this project supports go 1.17.

More context: https://github.com/Homebrew/homebrew-core/pull/83413
```

**Comment by ydnar** [comment]
Thinking out loud: would it be useful if Homebrew allowed users to install prerelease (or upcoming) versions of certain packages, with the caveat that the user takes on any compatibility risk? e.g.:

```sh
brew install go@next
```

**Comment by imsodin** [comment]
Just as a heads up: I don't think the x/sys issue is the only problem, likely not even the main problem here. The CI failure points at quic, which is "normal": They almost always require an upgrade to support an ewer go version.

**Comment by SMillerDev** [comment]
> would it be useful if Homebrew allowed users to install prerelease (or upcoming) versions of certain packages, with the caveat that the user takes on any compatibility risk?

You can make a tap for that if you'd like. We won't be adding it to homebrew-core though.

**Comment by blacktop** [comment]
> Thanks, @roopakv, for the work you've done!
> 
> > Would it be possible for you all to kind of pin previous versions of Golang? Like `brew install go1.16` and then all these packages that depend on Go can pin to a version and not hold up the release of NEW versions?
> 
> This just creates extra maintenance work that someone's going to have to do -- and given that we only have a small number of people helping to fix CI failures in Go PRs relative to the number of reactions, I doubt anyone's volunteering to do that, unfortunately. This entails:
> 
> 1. Changing ~600 formulae that currently do `depends_on "go"` to `depends_on "go@x.y"`. (Easy.)
> 2. Updating each of ~600 formulae to the newest version of Go that they support as and when they're supported. (Not easy.)
> 
> The fastest way to get this merged really is to contribute to helping fix the CI failures.

This kinda sounds like what is happening right now or am I wrong?

Currently update ALL go depending formulas to go (latest) blocking go (latest)

vs.

Update ALL go depending formulas to go1.16, release go (latest) and then slowly update ALL go depeding formulas to go (latest) without blocking go (latest) ?

Same amount of work is done, however, go (latest) isn't blocked.

**Comment by SMillerDev** [comment]
> Same amount of work is done, however, go (latest) isn't blocked.

We tried that before and nobody will fix the remaining formulae in between. So realistically you're just doubling the maintenance on all other version bumps after.

I'm really tired of having to explain the same thing at every go version bump. Can't the Go community just get their shit fixed and actually anticipate new versions in their software and test betas instead of complaining about the speed of homebrew updates? Because really this is more on the Go community then Homebrew iyam.

**Comment by blacktop** [comment]
> > Same amount of work is done, however, go (latest) isn't blocked.
> 
> We tried that before and nobody will fix the remaining formulae in between. So realistically you're just doubling the maintenance on all other version bumps after.
> 
> I'm really tired of having to explain the same thing at every go version bump. Can't the Go community just get their shit fixed and actually anticipate new versions in their software and test betas instead of complaining about the speed of homebrew updates? Because really this is more on the Go community then Homebrew iyam.

I was wondering about that too, if you pinned them to go1.16 isn't it kind of on them (Go bin maintainer) to update their formula if they want go1.17 for some reason and not your responsibility?

**Comment by SMillerDev** [comment]
> if you pinned them to go1.16 isn't it kind of on them (Go bin maintainer) to update their formula if they want go1.17 for some reason and not your responsibility?

But it is our responsibility not to ship outdated software, so for the release of 1.19 we'd have to delete the formula that people depend on (not great) or help the open source community by updating the software to work with a recent Go version (like we do now).

**Comment by carlocab** [comment]
> This kinda sounds like what is happening right now or am I wrong?

It's similar, but it's not the same. Your suggestion has about 20 times more code churn, 95% of which is the equivalent of boilerplate. No one's going to do that.

For reference, this is what we do with Python (that's why all the Python formulae are versioned): that's how I know what you're proposing takes a lot more work and time.

> Currently update ALL go depending formulas to go (latest) blocking go (latest)
> 
> vs.
> 
> Update ALL go depending formulas to go1.16, release go (latest) and then slowly update ALL go depeding formulas to go (latest) without blocking go (latest) ?
> 
> Same amount of work is done, however, go (latest) isn't blocked.

It's not the same because the former involves changing only the Go formula, whereas the latter involves changing an additional 600 formulae. That makes a huge difference. For one thing, it allows everything to be done all in a single PR. Trying to modify more than ~50 formulae in a single PR tends to stress CI too much (typically due to space constraints).

**Comment by gordonbondon** [comment]
Submitted a bunch of fix PRs.

The once that have failed brew test with panic:
`naabu` - https://github.com/projectdiscovery/naabu/pull/204
`ory-hydra` - https://github.com/ory/hydra/pull/2687
`modd` - https://github.com/cortesi/modd/pull/103
`minio-mc` - https://github.com/minio/mc/pull/3779
`ksync` - https://github.com/ksync/ksync/pull/544
`flux` - https://github.com/influxdata/flux/pull/3982
`convox` - https://github.com/convox/convox/pull/389
`sdns` - https://github.com/semihalev/sdns/pull/100

`helmfile` actually has a sha mismatch, fix here https://github.com/Homebrew/homebrew-core/pull/83630

**Comment by carlocab** [comment]
The following are checksum mismatches:
```
baidupcs-go
kubeprod
```

`ghz-web` and `cql` segfaulted in similar ways, so I think they also need an `x/sys` update.

`mmctl` is a `gofmt` failure while running `make install`.

Not sure what happened to `xray`:
```
==> brew test --retry --verbose xray
==> FAILED
==> Testing xray
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210818-49361-5a3xo6.sb ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xray.rb --verbose --retry
==> /usr/local/Cellar/xray/1.4.2_1/bin/xray -c /private/tmp/xray-test-20210818-49362-18jdvuy/config.json -test
panic: qtls.CertificateRequestInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
	github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x198
```
This error is similar to the error with `ooniprobe`, so maybe it could be the `x/sys` issue too? Unsure.

**Comment by imsodin** [comment]
> Not sure what happened to `xray`:

That's due to them using an outdated quic version as mentioned earlier:

> Just as a heads up: I don't think the x/sys issue is the only problem, likely not even the main problem here. The CI failure points at quic, which is "normal": They almost always require an upgrade to support an ewer go version.

I believe initial go support was added in 0.21.x, 0.22.0 is definitely compatible: https://github.com/lucas-clemente/quic-go/

**Comment by gordonbondon** [comment]
Investigating other packages with issues unrelated to x/sys:
`xray`, `ooniprobe` - fail to run because underlying dependency does not support apple silicon quic-go https://github.com/marten-seemann/qtls-go1-15/issues/1
`orgalorg` - fails because new macOS sets `SSH_AUTH_SOCK` by default, which changes error output and breaks test. Fix here: https://github.com/Homebrew/homebrew-core/pull/83639
`mmctl` - makefile build break with latest gofmt version https://github.com/mattermost/mmctl/issues/363, we can either update formula to run go build directly, or submit a pr that updates new `gofmt` requirements
`kubeprod` - sha mismatch, looks like tag was updated, created issues to check with maintainers https://github.com/bitnami/kube-prod-runtime/issues/1411
`helmfile` - sha mismatch after retag, fix here https://github.com/Homebrew/homebrew-core/pull/83630
`baidupcs-go` - sha mismatch, republish confirmed by maintainers, fix here: https://github.com/Homebrew/homebrew-core/pull/83643

**Comment by carlocab** [comment]
> That's due to them using an outdated quic version as mentioned earlier:

Aha, yes, I read your comment but didn't manage to put two and two together. There's a lot of information floating around here. Thanks, @imsodin.

Thanks for your work too, @gordonbondon.

**Comment by bouk** [comment]
PR for cql: https://github.com/CovenantSQL/CovenantSQL/pull/379

**Comment by andig** [comment]
@chenrui333 I must admit that I do not understand all these "bump go 1.17" PRs you've opened. There is absolutely no reason for a module to declare go1.17 required in order to build. What are you really trying to achieve or solve here?

**Comment by carlocab** [comment]
It looks like all the failures have been reported upstream where needed, with some formulae patched here to pull in fixes where new releases haven't been cut.

Let's re-run CI to check that the fixed formulae have, in fact, been fixed.

**Comment by bmhatfield** [comment]
> If you really need the newest version of Go, you can do things that will allow you to brew install the latest version of Go well before this PR is merged.

Is there a link to some docs? I have been extensively Googling for clues and I can't find a doc explaining how to do this.

**Comment by SMillerDev** [comment]
A tap, or checking out the branch would allow you to run Go 1.17 already.

**Review by carlocab — APPROVED** [review]
I think we're far enough along here that nearly all (if not all) the remaining failures should be fixed in time.

Thanks for the help, @samuel, @roopakv, @bouk, @bn4t, @imsodin, @gordonbondon, @AlekSi, @ucwong, @stefanb and @andig! (Apologies if I missed anyone.)

**Pull request closed without merging**
