### PR TITLE
hide v0.1

### PR DESCRIPTION
**Pull request by EvanCooper9**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chdiza** [comment]
Self-submitted; homepage URL doesn't actually point to anything (but the project's github page has zero stars); description makes it sound like a GUI app.

**Comment by EvanCooper9** [comment]
@chdiza is there a minimum amount of stars required? Homepage and description modified.

**Comment by chdiza** [comment]
If you read and actually do all the steps [here](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md), one of the audits  would catch a lot.

Also: yes, there is a minimum number of stars.  http://docs.brew.sh/Acceptable-Formulae.html

**Comment by chdiza** [comment]
Ah, I thought the star minimum was documented there.  I think it used to be.

**Comment by EvanCooper9** [comment]
Yeah, I read up on self-submitted software. Unfortunately don't meet the requirements.

**Pull request closed without merging**
