### PR TITLE
mongodb 3.6.0 (devel)

### PR DESCRIPTION
**Pull request by Fudoshiki**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Fudoshiki the build failure is caused by https://github.com/mongodb/mongo-tools/commit/05a9140db5f4f2746f98c98ed2fec2a7d15e040a

```
bash-3.2$ stty sane </dev/null
stty: stdin isn't a terminal
bash-3.2$ echo $?
1
bash-3.2$ 
```

That's not appropriate for a build script so upstream will need to fix that.

**Comment by ilovezfs** [comment]
Thanks @Fudoshiki!

**Comment by Fudoshiki** [comment]
@ilovezfs thank you for help

**Comment by ilovezfs** [comment]
You're welcome :)

**Pull request merged**
