### PR TITLE
poppler 20.09.0

### PR DESCRIPTION
**Pull request by miccal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Supersedes https://github.com/Homebrew/homebrew-core/pull/58991.

I will add the required patches for `gdal` and then any necessary revision bumps once the initial CI run is complete.

### CODE REVIEW

**Comment by miccal** [comment]
Try to get `gdal` working first ...

**Comment by miccal** [comment]
`gdal` now builds successfully, next thing is revision bumps for `diff-pdf` and `pdftoipe` ...

**Comment by miccal** [comment]
Closes https://github.com/Homebrew/homebrew-core/pull/58991

😎

**Review by chenrui333 — APPROVED** [review]
💯

**Comment by chenrui333** [comment]
@miccal thanks!!

**Pull request closed without merging**
