### PR TITLE
phpstan 0.11.12

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
image

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
It fails because of a PCRE JIT error as far as I can see.

**Comment by chenrui333** [comment]
yeah, it certainly is:

PHP Warning:  preg_match_all(): JIT compilation failed: no more memory in phar:///usr/local/Cellar/phpstan/0.11.12/bin/phpstan/vendor/symfony/console/Formatter/OutputFormatter.php on line 172
09:04:55 Error: phpstan: failed

**Comment by chenrui333** [comment]
What is the possible solution for it?

**Comment by SMillerDev** [comment]
Figuring out if this is a PHP issue or just phpstan. If it's a phpstan issue this needs to be reported upstream

**Comment by chenrui333** [comment]
Just submit a upstream issue to get more ideas on this. :)

**Comment by SMillerDev** [comment]
Can you please apply the patch to the formula that has the issue (php). Cause currently you're going to leave people with unexplainable system changes after a tool upgrade.

**Comment by chenrui333** [comment]
oh, do you mean instead of doing the `inreplace` for the JIT setting change, do a `PATCH` section instead?

**Comment by SMillerDev** [comment]
No, I mean that this isn't fixed in phpstan but in PHP (where it should be )

**Comment by chenrui333** [comment]
Just added a PR.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
The php JIT setting has been updated.

**Comment by Moisan** [comment]
Thank you @chenrui333 and @SMillerDev !

**Pull request merged**
