### PR TITLE
aws-sdk-cpp 1.9.140

### PR DESCRIPTION
**Pull request by simpl1g**
Adds suport to build on linux

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by simpl1g** [comment]
@chenrui333 oped this PR to  this https://github.com/Homebrew/homebrew-core/pull/88847#issuecomment-962418010
Can you please review

**Comment by simpl1g** [comment]
@kou looks like this doesn't help https://github.com/Homebrew/homebrew-core/pull/88847#issuecomment-962411447

**Comment by kou** [comment]
Could you disable building tests?

```diff
diff --git a/Formula/aws-sdk-cpp.rb b/Formula/aws-sdk-cpp.rb
index e924449db8a..2031488316c 100644
--- a/Formula/aws-sdk-cpp.rb
+++ b/Formula/aws-sdk-cpp.rb
@@ -24,7 +24,10 @@ class AwsSdkCpp < Formula
   def install
     ENV.append "LDFLAGS", "-Wl,-rpath,#{rpath}"
     mkdir "build" do
-      system "cmake", "..", *std_cmake_args
+      args = %W[
+        -DENABLE_TESTSING=OFF
+      ]
+      system "cmake", "..", *std_cmake_args, *args
       system "make"
       system "make", "install"
     end
```

**Review by SMillerDev — APPROVED** [review]
Thanks @simpl1g  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
