### PR TITLE
pgroonga 3.0.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /home/linuxbrew/.linuxbrew/opt/postgresql@14/bin/pg_ctl start -D /tmp/pgroonga-test-20230511-24887-86n30c/test -l /tmp/pgroonga-test-20230511-24887-86n30c/log
  waiting for server to start.... stopped waiting
  pg_ctl: could not start server
  Examine the log output.
```

**Comment by chenrui333** [comment]
crash log

```
2023-05-14 19:46:49.699865|n|84574: grn_init: <13.0.1>
2023-05-14 19:46:49.700927|C|84574: -- CRASHED!!! --
2023-05-14 19:46:49.703932|C|84574: 0   libgroonga.0.dylib                  0x0000000102fb2ed0 grn_segv_handler.cold.1 + 120
2023-05-14 19:46:49.703961|C|84574: 1   libgroonga.0.dylib                  0x0000000102ce2bbc grn_set_int_handler + 0
2023-05-14 19:46:49.703968|C|84574: 2   libsystem_platform.dylib            0x00000001b1fef2a4 _sigtramp + 56
2023-05-14 19:46:49.703975|C|84574: 3   pgroonga.so                         0x000000010174b190 _PG_init + 144
2023-05-14 19:46:49.703984|C|84574: 4   pgroonga.so                         0x000000010174b190 _PG_init + 144
2023-05-14 19:46:49.703991|C|84574: 5   postgres                            0x00000001010db3d8 internal_load_library + 384
2023-05-14 19:46:49.703999|C|84574: 6   postgres                            0x00000001010db4b0 load_file + 72
2023-05-14 19:46:49.704005|C|84574: 7   postgres                            0x00000001010e2b08 load_libraries + 172
2023-05-14 19:46:49.704025|C|84574: 8   postgres                            0x00000001010e2a4c process_shared_preload_libraries + 48
2023-05-14 19:46:49.704029|C|84574: 9   postgres                            0x0000000100f76f9c PostmasterMain + 1884
2023-05-14 19:46:49.704033|C|84574: 10  postgres                            0x0000000100eeb330 init_locale + 0
2023-05-14 19:46:49.704038|C|84574: 11  dyld                                0x00000001b1c97e50 start + 2544
2023-05-14 19:46:49.704043|C|84574: ----------------
```

**Comment by kou** [comment]
I'll take a look at this.

**Comment by kou** [comment]
Could you try this?

```diff
diff --git a/Formula/pgroonga.rb b/Formula/pgroonga.rb
index 3b709fa8c41..12c469f93a1 100644
--- a/Formula/pgroonga.rb
+++ b/Formula/pgroonga.rb
@@ -48,8 +48,6 @@ class Pgroonga < Formula
 
     system pg_ctl, "initdb", "-D", testpath/"test"
     (testpath/"test/postgresql.conf").write <<~EOS, mode: "a+"
-
-      shared_preload_libraries = 'pgroonga'
       port = #{port}
     EOS
     system pg_ctl, "start", "-D", testpath/"test", "-l", testpath/"log"
```

PGroonga wants to drop support for `shared_preload_libraries = 'pgroonga'` usage.

**Comment by askdkc** [comment]
The `shared_preload_libraries  = 'pgroonga'` setting is causing trouble in version 3.0.2 but has been fixed in [ver 3.0.3](https://github.com/pgroonga/pgroonga/discussions/338).

In fact, this [Ver 3.0.3 PR](https://github.com/Homebrew/homebrew-core/pull/131286) seems passing all the tests.

**Comment by kou** [comment]
In general, we should remove `shared_preload_libraries = 'pgroonga'` because (PGroonga 3.0.3 isn't crashed but) PGroonga doesn't work well with `shared_preload_libraries = 'pgroonga'`.

**Comment by askdkc** [comment]
@kou san

> In general, we should remove `shared_preload_libraries = 'pgroonga'`

Thanks for the info!
I should keep this in my mind until next time so that I can fix it.

**Pull request closed without merging**
