### PR TITLE
llvm@8: fix C++ compilation for Mojave and Catalina

### PR DESCRIPTION
**Pull request by smorimoto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Port from #45693. Thank you @jamiesnape.

Related issue and PR: #45061 and #45304.

### CODE REVIEW

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by imbsky** [comment]
@BrewTestBot test this please!

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/llvm@8/8.0.1_1/bin/scan-build clang++ scanbuildtest.cpp 2>&1
Error: llvm@8: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by imbsky** [comment]
I wonder why llvm@7 succeeded and llvm@8 failed. Let's take a closer look at it anyway.

**Comment by jamiesnape** [comment]
Maybe something to do with this? https://github.com/llvm/llvm-project/commit/193278821fbbef992ae083e406dedcadfa19aaba#diff-0c7516e3549ab095e9bef2a491937235

**Comment by imbsky** [comment]
Maybe scan-build could not find clang. I hope test will run correctly with last commit.

**Comment by imbsky** [comment]
Test passed!

**Comment by imbsky** [comment]
Squashed.

**Comment by imbsky** [comment]
Ready to review (or merge?)

**Review by chenrui333 — APPROVED** [review]
Thanks!

**Comment by imbsky** [comment]
👍

**Pull request closed without merging**
