### PR TITLE
kamel 1.5.0

### PR DESCRIPTION
**Pull request by oscerd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
--- FAIL: TestPermissionDenied (0.00s)
    util_test.go:40: 
        	Error Trace:	util_test.go:40
        	Error:      	Expected value not to be nil.
        	Test:       	TestPermissionDenied
Could not parse <nil> (error: Invalid Semantic Version)
Could not parse <nil> (error: Invalid Semantic Version)
```

**Comment by oscerd** [comment]
Feel free to fix it, if you have time.

**Comment by oscerd** [comment]
on the camel-k repository we don't see this error. Btw the tag is that one.

**Comment by Abirdcfly** [comment]
after add bugfix apache/camel-k#2561 all test pass.😊

```
# kamel.rb
class Kamel < Formula
  desc "Apache Camel K CLI"
  version "1.6.0-SNAPSHOT"
  homepage "https://camel.apache.org/"
  url "https://github.com/abirdcfly/camel-k.git",
      branch: "main",
      revision: "009ef13475780a1a4976484325450c87e329f622"
  license "Apache-2.0"
  head "https://github.com/abirdcfly/camel-k.git"
...

# kamel version
Camel K Client 1.6.0-SNAPSHOT
# brew test kamel
==> Testing kamel
==> /usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel 2>&1
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel help 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel get 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel version 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel run 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel run None.java 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel reset 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel rebuild 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.6.0-SNAPSHOT/bin/kamel reset 2>&1)

```

**Comment by chenrui333** [comment]
Applied the build patch and it should work fine now.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
