### PR TITLE
gnuplot 5.2.5

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tseemann** [comment]
```
  Error: 2 problems in 1 formula detected
gnuplot:
  * Stable resource "libcerf": The URL http://apps.jcns.fz-juelich.de/src/libcerf/libcerf-1.5.tgz is not reachable (HTTP status code 404)
  * HEAD resource "libcerf": The URL http://apps.jcns.fz-juelich.de/src/libcerf/libcerf-1.5.tgz is not reachable (HTTP status code 404)
```

**Comment by fxcoudert** [comment]
- `libcerf` now builds with `cmake`
- I have not been able to make a static build of it, so it needs to be installed in path

**Comment by lembacon** [comment]
@fxcoudert I've forgotten that you are our expert of scientific formulae 😅, I'm closing this one so that you can take it over. :-)

**Comment by fxcoudert** [comment]
Here: #32840
(but I'm very happy with everyone working on science formulas! 😄)

**Pull request closed without merging**
