### PR TITLE
perl-build 1.13

### PR DESCRIPTION
**Pull request by bfontaine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@bfontaine See https://github.com/Homebrew/homebrew-core/pull/1939.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Let's make sure the issues identified in https://github.com/Homebrew/homebrew-core/pull/1939 are actually resolved before merging this. As far as I know, nothing has changed.

**Comment by bfontaine** [comment]
I finally found a way to build this "from source" (i.e. not using upstream’s pre-packed script).

**Comment by ilovezfs** [comment]
It might be good to find out why the pre-packed script wasn't refreshed.

**Comment by bfontaine** [comment]
Probably because upstream forgot about it. They updated it in https://github.com/tokuhirom/Perl-Build/issues/58.

**Comment by bfontaine** [comment]
@ilovezfs Are you ok on this?

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@bfontaine it seems fine to me. We can always go back to the prebuilt thingy if this doesn't work out for whatever reason.

**Comment by bfontaine** [comment]
@BrewTestBot build this please.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please.

**Pull request closed without merging**
