### PR TITLE
cycode 1.4.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by MarshalX** [comment]
@chenrui333 @Porkepix Hi! After migration to python 3.12 it started raised errors about missed deps :( could you pls help to understand why it happens? from our side it was testes on 2 mac machines. the first raises error about missed "six" dep, the second one about "yaml". both dependencies are described in formula using "depends_on" directive

six:
image

yaml:
image

pls let me know what kind of logs/info i can provide you to understand the problem

**Comment by MarshalX** [comment]
looks like deps are resolved fine, installed with proper versions, but can't be accessed from cycode formula

`pyvenv.cfg` in `/opt/homebrew/Cellar/cycode/1.4.0/libexec` contains `include-system-site-packages = true` 

image

**Comment by MarshalX** [comment]
I found this issue. What is the guideline to fix it for our users until migration to Python 3.12 is not finished? https://github.com/Homebrew/homebrew-core/issues/149998

**Comment by MarshalX** [comment]
@ZhongRuoyu hello, maybe you could assist?

**Comment by ZhongRuoyu** [comment]
@MarshalX I tried with a fresh install of `cycode` and could not reproduce the error you posted.

```console
$ brew install cycode
[truncated]
==> Installing dependencies for cycode: ca-certificates, python-certifi, mpdecimal, openssl@3, ncurses, readline, zlib, sqlite, xz, bzip2, expat, libedit, libffi, libxcrypt, unzip, berkeley-db@5, krb5, libtirpc, libnsl, python@3.12, libyaml, pyyaml and six
[truncated]
==> Installing cycode
==> Pouring cycode--1.4.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/cycode/1.4.0: 547 files, 5.2MB
==> Running `brew cleanup cycode`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
$ cycode report sbom --help
Usage: cycode report sbom [OPTIONS] COMMAND [ARGS]...

  Generate SBOM report.

Options:
  -f, --format [spdx-2.2|spdx-2.3|cyclonedx-1.4]
                                  SBOM format.  [required]
  -o, --output-format [json]      Specify the output file format (the default is json).
  --output-file PATH              Output file (the default is autogenerated filename saved to the current directory).
  --include-vulnerabilities       Include vulnerabilities.
  --include-dev-dependencies      Include dev dependencies.
  --help                          Show this message and exit.

Commands:
  path            Generate SBOM report for provided path in the command.
  repository_url  Generate SBOM report for provided repository URI in the command.
```

Does `brew update && brew upgrade` help to fix the issue? If not, can you show the output of the following:

```shell
brew ls --versions $(brew deps cycode)
cat $(brew --prefix cycode)/libexec/lib/python3.12/site-packages/homebrew_deps.pth
```

**Comment by MarshalX** [comment]
@ZhongRuoyu thank you for your effort!

`brew update`:
```
==> Updated Homebrew from d3fd36da4 to c0c8a4dd4.
Updated 3 taps (mongodb/brew, homebrew/core and homebrew/cask).
==> New Formulae
cf2tf                                                           diffoci                                                         dockly                                                          gptline                                                         libnghttp3
==> Outdated Formulae
assimp                       cloc                         go                           libomp                       llvm                         node                         openjdk                      poetry                       qemu                         unbound                      zeromq
c-ares                       cmake                        imagemagick                  libplist                     mockery                      nss                          openssl@1.1                  pycparser                    qt@5                         vegeta
capstone                     ghostscript                  ipython                      librist                      mongodb-community-shell      numpy                        osslsigncode                 pygments                     shared-mime-info             watch
ccache                       git                          jbig2dec                     libusbmuxd                   mongodb-database-tools       nvm                          perl                         pyqt@5                       telnet                       wimlib
cffi                         glab                         jq                           libx11                       nghttp2                      oniguruma                    pipenv                       python@3.11                  tesseract                    x264
==> Outdated Casks
ngrok                                                                                                                                                           nightfall

You have 51 outdated formulae and 2 outdated casks installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
```

`brew upgrade`: 
```
==> Upgrading 51 outdated packages:
mongodb/brew/mongodb-database-tools 100.7.4 -> 100.8.0
ccache 4.8.2 -> 4.8.3
nghttp2 1.55.1 -> 1.57.0
libplist 2.2.0 -> 2.3.0
pipenv 2023.9.1 -> 2023.10.3
go 1.20.7 -> 1.21.3
ghostscript 10.01.2 -> 10.02.0
pygments 2.16.1 -> 2.16.1_1
pyqt@5 5.15.7_2 -> 5.15.9
pycparser 2.21 -> 2.21_1
cmake 3.27.2 -> 3.27.7
qt@5 5.15.10 -> 5.15.10_1
assimp 5.2.5 -> 5.3.1
ipython 8.15.0 -> 8.16.1
mockery 2.32.4 -> 2.35.4
shared-mime-info 2.2 -> 2.3
zeromq 4.3.4 -> 4.3.5
cffi 1.16.0 -> 1.16.0_1
perl 5.36.1 -> 5.38.0
wimlib 1.14.2 -> 1.14.3
llvm 16.0.6 -> 17.0.2
nss 3.92 -> 3.94
tesseract 5.3.2_1 -> 5.3.3
c-ares 1.19.1 -> 1.20.1
nvm 0.39.4 -> 0.39.5
numpy 1.26.0_1 -> 1.26.1
openjdk 20.0.1 -> 21
poetry 1.6.1_1 -> 1.6.1_2
capstone 4.0.2 -> 5.0.1
libusbmuxd 2.0.2 -> 2.0.2_1
librist 0.2.7_3 -> 0.2.7_4
qemu 8.1.0_1 -> 8.1.1
vegeta 12.11.0 -> 12.11.1
jbig2dec 0.19 -> 0.20
osslsigncode 2.6 -> 2.7
glab 1.32.0 -> 1.33.0
watch 4.0.3 -> 4.0.4
oniguruma 6.9.8 -> 6.9.9
openssl@1.1 1.1.1v -> 1.1.1w
cloc 1.96.1 -> 1.98
x264 r3095 -> r3108
node 20.5.1 -> 20.8.1
libomp 16.0.6 -> 17.0.2
unbound 1.18.0 -> 1.18.0_1
jq 1.6 -> 1.7
mongodb/brew/mongodb-community-shell 5.0.17 -> 5.0.21
python@3.11 3.11.5 -> 3.11.6
imagemagick 7.1.1-15 -> 7.1.1-20
libx11 1.8.6 -> 1.8.7
git 2.41.0_2 -> 2.42.0
telnet 69 -> 294
```
it didn't help

`brew ls --versions $(brew deps cycode)`:
```
ca-certificates 2023-08-22
libyaml 0.2.5
mpdecimal 2.5.1
openssl@3 3.1.2 3.1.3
python-certifi 2023.7.22 2023.7.22_1
python@3.12 3.12.0
pyyaml 6.0.1
readline 8.2.1
six 1.16.0_4 1.16.0_3
sqlite 3.43.0_1 3.42.0 3.43.2
xz 5.4.4
```

`cat $(brew --prefix cycode)/libexec/lib/python3.12/site-packages/homebrew_deps.pth`:

```
import site; site.addsitedir('/opt/homebrew/opt/python-certifi/lib/python3.12/site-packages')
import site; site.addsitedir('/opt/homebrew/opt/pyyaml/lib/python3.12/site-packages')
import site; site.addsitedir('/opt/homebrew/opt/six/lib/python3.12/site-packages')
```

**Comment by MarshalX** [comment]
Well, idk what is going on.... but reinstalling of pyyaml/six helped... pls see the log:

```shell
➜  python3.12 (master) /opt/homebrew/bin/cycode                                                                                                                                                                              ✱
Traceback (most recent call last):
  File "/opt/homebrew/bin/cycode", line 5, in <module>
    from cycode.cli.main import main_cli
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/main.py", line 9, in <module>
    from cycode.cli import code_scanner
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/code_scanner.py", line 16, in <module>
    from cycode.cli.config import configuration_manager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/config.py", line 3, in <module>
    from cycode.cli.user_settings.configuration_manager import ConfigurationManager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/user_settings/configuration_manager.py", line 8, in <module>
    from cycode.cli.user_settings.config_file_manager import ConfigFileManager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/user_settings/config_file_manager.py", line 5, in <module>
    from cycode.cli.user_settings.base_file_manager import BaseFileManager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/user_settings/base_file_manager.py", line 5, in <module>
    from cycode.cli.utils.yaml_utils import read_file, update_file
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/utils/yaml_utils.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
➜  python3.12 (master) brew install pyyaml                                                                                                                                                                                   ✱
Running `brew update --auto-update`...
Warning: pyyaml 6.0.1 is already installed and up-to-date.
To reinstall 6.0.1, run:
  brew reinstall pyyaml
➜  python3.12 (master) /opt/homebrew/bin/cycode                                                                                                                                                                              ✱
Traceback (most recent call last):
  File "/opt/homebrew/bin/cycode", line 5, in <module>
    from cycode.cli.main import main_cli
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/main.py", line 9, in <module>
    from cycode.cli import code_scanner
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/code_scanner.py", line 16, in <module>
    from cycode.cli.config import configuration_manager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/config.py", line 3, in <module>
    from cycode.cli.user_settings.configuration_manager import ConfigurationManager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/user_settings/configuration_manager.py", line 8, in <module>
    from cycode.cli.user_settings.config_file_manager import ConfigFileManager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/user_settings/config_file_manager.py", line 5, in <module>
    from cycode.cli.user_settings.base_file_manager import BaseFileManager
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/user_settings/base_file_manager.py", line 5, in <module>
    from cycode.cli.utils.yaml_utils import read_file, update_file
  File "/opt/homebrew/Cellar/cycode/1.4.0/libexec/lib/python3.12/site-packages/cycode/cli/utils/yaml_utils.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
➜  python3.12 (master) brew reinstall pyyaml                                                                                                                                                                                 ✱
==> Downloading https://ghcr.io/v2/homebrew/core/pyyaml/manifests/6.0.1-1
######################################################################################################################################################################################################################## 100.0%
==> Fetching pyyaml
==> Downloading https://ghcr.io/v2/homebrew/core/pyyaml/blobs/sha256:9ce2dadb085a4e6fe2fa4f5f107384559f7fd7f4d006a71a83bab79021be70c2
######################################################################################################################################################################################################################## 100.0%
==> Reinstalling pyyaml
==> Pouring pyyaml--6.0.1.arm64_ventura.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/pyyaml/6.0.1: 86 files, 1.5MB
==> Running `brew cleanup pyyaml`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜  python3.12 (master) /opt/homebrew/bin/cycode                                                                                                                                                                              ✱
Usage: cycode [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --verbose                   Show detailed logs.
  --no-progress-meter             Do not show the progress meter.
  -o, --output [text|json|table]  Specify the output type (the default is text).
  --user-agent TEXT               Characteristic JSON object that lets servers identify the application.
  --help                          Show this message and exit.

Commands:
  auth       Authenticate your machine to associate the CLI with your Cycode account.
  configure  Initial command to configure your CLI client authentication.
  ignore     Ignores a specific value, path or rule ID.
  report     Generate report. You`ll need to specify which report type to perform.
  scan       Scan the content for Secrets/IaC/SCA/SAST violations. You`ll need to specify which scan type to perform: ci/commit_history/path/repository/etc.
  version    Show the CLI version and exit.
➜  python3.12 (master)
```

**Comment by ZhongRuoyu** [comment]
> reinstalling of pyyaml/six helped

That's a good hint; it seems that changes to `pyyaml` in #149598 was not picked up before your reinstallation as it was not revision-bumped. (Although from the output of `brew ls --versions $(brew deps cycode)`, it seems your `six` is already up-to-date.)

Nevertheless, glad that it works for you now.

**Comment by ZhongRuoyu** [comment]
> So this affects all users who installed cycode formula already, right?

For those who installed `cycode` before the `pyyaml` update: yes, I presume so.

**Pull request merged**
