### PR TITLE
henplus: use :java requirement

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by DomT4** [comment]
This won't test on CI because one of the dependencies wants Java 1.6, somehow.

Personally given the need for an ancient Java I'd just been tempted to kill this and `libreadline-java` but if you want to keep it I don't mind.

**Comment by ilovezfs** [comment]
@DomT4 I've fixed the libreadline-java issue and reported it upstream: https://github.com/Homebrew/homebrew-core/pull/837

In addition, henplus upstream has agreed to create a new tag: https://github.com/neurolabs/henplus/issues/41

So I don't think either need be removed.

**Comment by DomT4** [comment]
Alright, as long as you're working on it. Anything using Java 1.6 these days frankly seems unsupported by upstream.

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
Seems reasonable 👍

**Pull request closed without merging**
