### PR TITLE
ocaml 4.13.1

### PR DESCRIPTION
**Pull request by dmbaturin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by dmbaturin** [comment]
This PR is blocked by the need to update camlp5 first, I made a separate PR for that: https://github.com/Homebrew/homebrew-core/pull/97766 That's because camlp5 8.00 only supports the OCaml 4.12 AST format, while the latest 8.00.03 supports 4.13 already.

The other failed checks are now coming from bottled dependents no longer working because they were built with 4.12, and OCaml doesn't preserve binary compatibility, so they need to be rebuilt.

I'm new to homebrew packaging, so I'll need some guidance on how to update them properly: should I increment the `revision` field of every dependent package within this PR _in a single commit_, or every formula revision update should be a separate commit? Or I get the procedure wrong and I should do something else instead?

P.S. Sorry for lots of CI failures due to broken patch, I really shouldn't have worked on that while being too tired.

**Comment by carlocab** [comment]
You can apply the revision bumps correctly by checking out your PR branch and doing something like:
```
brew bump-revision --message="(ocaml 4.13.1)" foo bar baz
```
where `foo`, `bar` and `baz` are the names of relevant formulae.

**Comment by Porkepix** [comment]
Livecheck is now detecting 4.14.0 for your information.

**Comment by dmbaturin** [comment]
@Porkepix 4.14 is the latest release now. I'm going to look back into it, not abandoning my homebrew OCaml update idea.

**Pull request closed without merging**
