### PR TITLE
audio_visualizer 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by gituser12981u2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    gcc-11 -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/usr/local/include -I/usr/include -I/home/linuxbrew/.linuxbrew/Cellar/audio_visualizer/1.0.0/libexec/include -I/home/linuxbrew/.linuxbrew/opt/python@3.12/include/python3.12 -c src/pyaudio/device_api.c -o build/temp.linux-x86_64-cpython-312/src/pyaudio/device_api.o
    src/pyaudio/device_api.c:9:10: fatal error: portaudio.h: No such file or directory
        9 | #include "portaudio.h"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    error: command '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-11' failed with exit code 1
    error: subprocess-exited-with-error
    
    × Building wheel for PyAudio (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/linuxbrew/.linuxbrew/Cellar/audio_visualizer/1.0.0/libexec/bin/python /home/linuxbrew/.linuxbrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp4h82tbs5
    cwd: /tmp/audio_visualizer--PyAudio-20240707-10087-jpazc5/PyAudio-0.2.14
    Building wheel for PyAudio (pyproject.toml): finished with status 'error'
    ERROR: Failed building wheel for PyAudio
```

**Comment by gituser12981u2** [comment]
chenrui333, Thank you for showing the error. 

I added portaudio as a dependency and that seemed to have fixed that error for the macOS checks.

The linux errors are a bit more complicated and I will need to get rid of the pynput dependency and instead use something that doesn't require an x server, as the ci test is a headless linux environment.

This will take a bit. Thank you for your help.

**Comment by gituser12981u2** [comment]
I have fixed the linux error.

I am not sure what is wrong with my git commit styling. I have checked the formula cookbook and I don't see anything wrong with them.

**Comment by gituser12981u2** [comment]
My builds fail due to notability and because of git commit styling.

I am not sure what is wrong with my git commit styling, so I require assistance in that regard.

As for the notability fails, is this a strict rule? I have little notability, and I was hoping that putting my package on homebrew would make my project gain notability, instead of notability being a prerequisite to getting my package on homebrew.

Thank you for who reads this and can help out

**Comment by SMillerDev** [comment]
> As for the notability fails, is this a strict rule? I have little notability, and I was hoping that putting my package on homebrew would make my project gain notability, instead of notability being a prerequisite to getting my package on homebrew.

Yes, this is a strict rule. Homebrew is not a discovery service. Additionally:
> We frown on authors submitting their own work unless it is very popular.

https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by gituser12981u2** [comment]
I see. Thank you for your time.

**Pull request closed without merging**
