### PR TITLE
ooniprobe 3.15.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
JSON::ParserError: 767: unexpected token at '07/04 16:32:03 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

**Comment by MikeMcQuaid** [comment]
> Tempted to just skip the test on Linux. Unless we have some way to try the workaround suggested [here](https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size)?

I'd like to:
1. try that workaround
2. if that fails, try a `--help` test
3. if that fails, skip test on Linux

**Comment by carlocab** [comment]
Trying a `--version` test. The suggested workaround doesn't help; `sysctl` doesn't even seem to recognise `net.core.rmem_max`.

**Review by carlocab — APPROVED** [review]

**Comment by cho-m** [comment]
> `sysctl` doesn't even seem to recognise `net.core.rmem_max`.

It doesn't seem supported in Docker unless running host network mode with a host kernel that supports the parameter.

Even then, modifying kernel values will usually need to be done from the host machine or while creating the container (e.g. `docker run --sysctl ...`), so it isn't that simple without modifying CI workflow.

**Pull request closed without merging**
