### PR TITLE
openttd 14.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Looks like the minimum macOS has been [bumped to 10.15](https://github.com/OpenTTD/OpenTTD/pull/10745).

**Comment by chenrui333** [comment]
> Looks like the minimum macOS has been [bumped to 10.15](https://github.com/OpenTTD/OpenTTD/pull/10745).

10.15 is the min macOS.

**Comment by EricFromCanada** [comment]
Error when linking:
```
undef: _CGLChoosePixelFormat
undef: _CGLCreateContext
undef: _CGLDestroyPixelFormat
undef: _CGLReleaseContext
undef: _CGLSetCurrentContext
Undefined symbols for architecture arm64:
  "_CGLChoosePixelFormat", referenced from:
      +[OTTD_CGLLayer defaultPixelFormat] in lto.o
  "_CGLCreateContext", referenced from:
      VideoDriver_CocoaOpenGL::AllocateContext(bool) in lto.o
      -[OTTD_CGLLayer copyCGLContextForPixelFormat:] in lto.o
  "_CGLDestroyPixelFormat", referenced from:
      VideoDriver_CocoaOpenGL::AllocateContext(bool) in lto.o
  "_CGLReleaseContext", referenced from:
      VideoDriver_CocoaOpenGL::Stop() in lto.o
  "_CGLSetCurrentContext", referenced from:
      VideoDriver_CocoaOpenGL::AllocateContext(bool) in lto.o
      VideoDriver_CocoaOpenGL::Stop() in lto.o
      VideoDriver_CocoaOpenGL::ClearSystemSprites() in lto.o
      VideoDriver_CocoaOpenGL::AllocateBackingStore(bool) in lto.o
      VideoDriver_CocoaOpenGL::GetVideoPointer() in lto.o
      VideoDriver_CocoaOpenGL::ReleaseVideoPointer() in lto.o
      VideoDriver_CocoaOpenGL::Paint() in lto.o
      ...
ld: symbol(s) not found for architecture arm64
```
Getting the same error locally when building v13.4, so something must have changed on Homebrew's side.

**Comment by EricFromCanada** [comment]
The linking step runs this: `/opt/homebrew/Cellar/cmake/3.29.2/bin/cmake -E cmake_link_script CMakeFiles/openttd.dir/link.txt --verbose=1`

The problem is in `link.txt` where OpenGL is referenced as: `/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries/libGL.tbd`

If I compile in interactive mode and replace that with `-framework OpenGL` and re-run the above command, it works.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
