### PR TITLE
abcmidi 2018-01-25

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
fails on case insensitive file systems

**Comment by ilovezfs** [comment]
```
/usr/bin/sandbox-exec -f /tmp/homebrew20180126-87748-1y445ta.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/abcmidi.rb --build-bottle --verbose
==> Downloading https://www.ifdo.ca/~seymour/runabc/abcMIDI-2018.01.25.zip
Already downloaded: /Users/brew/Library/Caches/Homebrew/abcmidi-2018-01-25.zip
==> Verifying abcmidi-2018-01-25.zip checksum
unzip -qq /Users/brew/Library/Caches/Homebrew/abcmidi-2018-01-25.zip
replace abcmidi/makefile? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Error: Failure while executing: unzip -qq /Users/brew/Library/Caches/Homebrew/abcmidi-2018-01-25.zip
```

**Comment by mistydemeo** [comment]
Reported to the author by email.

**Comment by ilovezfs** [comment]
Thank you!

**Comment by ilovezfs** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/24444.

**Pull request closed without merging**
