### PR TITLE
zabbix 4.0.0

### PR DESCRIPTION
**Pull request by jordonr**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Fails to build on Mojave with:

```
checking for zlib support... no
configure: error: Unable to use zlib (zlib check failed)
```

**Comment by SMillerDev** [comment]
@jordonr could you still fix that issue?

**Comment by jordonr** [comment]
@SMillerDev I will try to get to it today.  Only have a Mac at work so need to find appropriate time to work on it.

**Comment by MatthiasKuehneEllerhold** [comment]
Please dont close it.

**Comment by stissot** [comment]
I believe this issue should be re-opened, and the zlib error on Mojave fixed before the PR can be merged

**Comment by SMillerDev** [comment]
I think it would be better to make a new pull request. This one isn't very active as evidenced by the stalebot.

**Pull request closed without merging**
