### PR TITLE
ktlint 0.38.1

### PR DESCRIPTION
**Pull request by shashachu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @shashachu  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by matthewtodd** [comment]
Thanks, @shashachu, I'm eager to try out `ktlint`!

Is there some binary artifact you've yet to publish? I'm getting a 404 when I try to `brew install ktlint`:

```
$ brew install ktlint
==> Downloading https://github.com/pinterest/ktlint/releases/download/0.38.1/ktlint
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ktlint"
Download failed: https://github.com/pinterest/ktlint/releases/download/0.38.1/ktlint
```

**Comment by shashachu** [comment]
@matthewtodd I forgot to hit the `Publish Release` button 🤦‍♀️ . Should be live now. Thanks for flagging this!

**Comment by matthewtodd** [comment]
@shashachu no worries! Confirmed working, thank you!

**Pull request closed without merging**
