### PR TITLE
freetype 2.8.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
The test for dependent `pdfsandwich` is failing.

```
        Testing pdfsandwich
/usr/bin/sandbox-exec -f /tmp/homebrew20170918-78545-7zimmh.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pdfsandwich.rb --verbose
==> /usr/local/Cellar/pdfsandwich/0.1.6/bin/pdfsandwich -o /tmp/pdfsandwich-test-20170918-78546-1op39yr/test_ocr.pdf /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.pdf
Fatal error: exception Failure("Could not find program pdfunite. Make sure this program exists and can be found in your search path.\nUse command line options to specify a custom binary.")
Error: pdfsandwich: failed
Failed executing: /usr/local/Cellar/pdfsandwich/0.1.6/bin/pdfsandwich -o /tmp/pdfsandwich-test-20170918-78546-1op39yr/test_ocr.pdf /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.pdf
```

The `pdfunite` command is provided by `poppler`. But in the test sequence, `poppler` is being unlinked before `pdfsandwich` is being tested.

```
00:27:28 ==> brew unlink poppler
00:27:29 ==> brew install pdf2image
00:27:31 ==> brew linkage --test pdf2image
00:27:32 ==> brew test --verbose pdf2image
00:27:33 ==> brew fetch --retry pdf2svg
00:27:34 ==> brew unlink pdf2image
00:27:35 ==> brew install pdf2svg
00:27:38 ==> brew linkage --test pdf2svg
00:27:39 ==> brew test --verbose pdf2svg
00:27:40 ==> brew fetch --retry pdfgrep
00:27:41 ==> brew unlink pdf2image
00:27:42 ==> brew install pdfgrep
00:27:45 ==> brew linkage --test pdfgrep
00:27:45 ==> brew test --verbose pdfgrep
00:27:47 ==> brew fetch --retry pdfsandwich
00:27:48 ==> brew unlink pdf2image
00:27:49 ==> brew install pdfsandwich
00:27:59 ==> brew linkage --test pdfsandwich
00:28:00 ==> brew test --verbose pdfsandwich
00:28:03 ==> FAILED
00:28:03 Testing pdfsandwich
```

I think this might be due to a flaw in the `brew test` dependency logic, which is getting tripped up because `poppler` is both a direct dependent of `freetype` (and thus tested and unlinked) and a dependency of `pdfsandwich`. And `pdfsandwich` is relying on `poppler` being linked and not just installed.

I'd say we merge this despite the test failure, because it doesn't look like it's caused by freetype or introduced by this version bump.

**Comment by ilovezfs** [comment]
:-1: to merging in the red.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @lembacon! Shipped :)

**Pull request closed without merging**
