### PR TITLE
Vsts cli 0.1.3

### PR DESCRIPTION
**Pull request by atbagga**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Test is failing:

```
==> /usr/local/Cellar/vsts-cli/0.1.3/bin/vsts configure --help
Failed to execute: /usr/local/Cellar/vsts-cli/0.1.3/bin/vsts
Error: vsts-cli: failed
```

**Comment by atbagga** [comment]
Working on fix.

**Comment by atbagga** [comment]
@fxcoudert Thanks for pointing out the failures. The issues are fixed now.

**Comment by Moisan** [comment]
Seems like the bottle wasn't published correctly, re-launching the CI hoping it will work out this time. 🤞

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by atbagga** [comment]
@Moisan Do I have an action item here? Or is it the CI issue which is blocking merge?

**Comment by SMillerDev** [comment]
@atbagga it's a CI failure

**Comment by javian** [comment]
Thank you for the contribution @atbagga and welcome to the Homebrew project ❤️ ! Without people like you we would not have a vibrant community.

**Comment by atbagga** [comment]
@Moisan @javian @SMillerDev 

brew install vsts-cli 
There is a checksum failure on the bottle on installing on high-sierra.
Is this due to CI issue we  were facing? INstallation does finish by source build and work eventually. 

**Logs here for reference:** 
Atuls-MBP: atbagga$ brew install vsts-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 05e670e1b to 158a34bda.
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
fx                                                                                                     kubespy
==> Updated Formulae
vsts-cli ✔                                                                                             pulumi

Warning: vsts-cli 0.1.3 is already installed and up-to-date
To reinstall 0.1.3, run `brew reinstall vsts-cli`
Atuls-MBP: atbagga$ brew reinstall vsts-cli
==> Reinstalling vsts-cli 
==> Downloading https://homebrew.bintray.com/bottles/vsts-cli-0.1.3.high_sierra.bottle.tar.gz
######################################################################## 100.0%
**Error: SHA256 mismatch
Expected: f581e56644210416738424264db59d1264e40959d7a24dc762fce10b385f3650
Actual: 07d7621e12494cf85135b3775877b9ef14704587b58122b650e6e7834eef64e4**
Archive: /Users/atbagga/Library/Caches/Homebrew/downloads/ee31577ef75e005a09434feaba40fc5335af7e501cd58d83ffb8cdab092c32cb--vsts-cli-0.1.3.high_sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.

I cleared the cached bottle. Brew uninstalled vsts-cli and installed again and I see same error as above.

**Comment by javian** [comment]
@SMillerDev can you submit it and I can merge ?

**Comment by atbagga** [comment]
Thanks a lot all of you for being so prompt in replying and fixing. Since the PR is raised I have closed the issue raised for this since I didn't follow the right template too.

**Pull request closed without merging**
