### PR TITLE
python@3.{10,11}: revision bump for alias migration

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

We didn't rev bump in #114154 but I think we should so all users have the same `python3`

### CODE REVIEW

**Comment by michaelblyons** [comment]
Does the rev-bump need to go through "The tests are failing," "That one pre-dates the change," and so on? It took four months to get the #114154 through. Please don't delay too long before users actually see [the benefits](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-faster-cpython).

**Comment by branchvincent** [comment]
No this should be good to merge after a single CI run, we didn't intend for the other PR to take that long

**Comment by branchvincent** [comment]
Forgot the self-hosted label so Linux got halfway through before timing out, but without any failures. Don't think it's worth rerunning

**Comment by SMillerDev** [comment]
Do we have bottles for everything?

**Comment by branchvincent** [comment]
Yes all bottles were built/uploaded (here's the [linux](https://github.com/Homebrew/homebrew-core/actions/runs/4169825013/jobs/7263300768#step:18:28) one)

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Yeah, I can see the bottles for [the linux run](https://github.com/Homebrew/homebrew-core/actions/runs/4169825013/jobs/7263300768) as well

```
2 bottles
ls: cannot access 'failed/*.json': No such file or directory
0 failed bottles
```

**Pull request closed without merging**
