### PR TITLE
zpaqfranz 57.5

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>### Changed help
Rationalisation of help  
```
zpaqfranz
zpaqfranz h
zpaqfranz h h
zpaqfranz h full
```

### Multioperation (with wildcards)  
In commands t and x (test, extract)
```
zpaqfranz t *.zpaq ...
zpaqfranz x pippo*.zpaq...
```

# Initial (kind of) text based GUI (Windows)
The new gui command open a (rudimentaly) ncurses-based GUI for listing, sorting, selecting and extracting files  
Yes, I know, the vim-style syntax is not exactly user friendly, there will be future improvements

Under Windows, compiling with the -DGUI switch, you can do something like
```
zpaqfranz gui 1.zpaq
```

The vim-like commands are
f F / => find substring
Cursor arrow up-down left-right => page up, page down, line up, line down
+ - => move line + -
: => goto line
m M => set minsize Maxsize
d D => set datefrom Dateto
q Q ESC => exit
F1 sort name, F2 sort size, F3 sort date, F4 sort ext, F5 sort hash
F6 show size, F7 show date, F8 show hash, F9 show stdout
t => change -to
s => searchfrom
r => replace to
x => extract visible rows

In this example we want to extract all the .cpp files as .bak from the 1.zpaq archive. This is something you typically cannot do with other archives such as tar, 7z, rar etc.
### With a "sort of" WYSIWYG 'composer'
First f key (find) and entering .cpp
Then s (search) every .cpp substring
Then r (replace) with .bak
Then t (to) for the z:\example folder
Finally x to run the extraction

[Example](https://user-images.githubusercontent.com/77727889/226925740-d62b92ae-4eee-43ac-94a9-e1a6dae684c1.mp4)

In the medium term, in addition to bug fixes, box filters etc., there will be a PAKKA-style sorted list, or time machine style, with versions of individual files

[Download zpaqfranz](https://sourceforge.net/projects/zpaqfranz/files/57.5/)</pre>
</details>

### CODE REVIEW

**Comment by p-linnane** [comment]
macOS:
```
==> make install -f NONWINDOWS/Makefile BINDIR=/opt/homebrew/Cellar/zpaqfranz/57.5/bin/zpaqfranz
  objc[41729]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1fbffb480) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x110e902b8). One of the two will be used. Which one is undefined.
  objc[41729]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1fbffb4d0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x110e90308). One of the two will be used. Which one is undefined.
  clang  -DNOJIT -O3 -Dunix zpaqfranz.cpp -o zpaqfranz -pthread -lstdc++ -lm
  zpaqfranz.cpp:37744:128: error: a space is required between consecutive right angle brackets (use '> >')
          int64_t         franzparallelhashfiles(string i_hashtype,int64_t i_totalsize,vector<string> i_thefiles,vector<std::pair<string,string>>& o_hashname);
                                                                                                                                               ^~
                                                                                                                                               > >
  zpaqfranz.cpp:64457:34: error: a space is required between consecutive right angle brackets (use '> >')
          vector<std::pair<uint64_t,string>> bysize;
                                          ^~
                                          > >
  zpaqfranz.cpp:64493:37: error: a space is required between consecutive right angle brackets (use '> >')
                                  vector<std::pair<uint64_t,string>>::iterator basso      = std::lower_bound(bysize.begin(), bysize.end(), p->second.size,mycompareuint64string());
                                                                  ^~
                                                                  > >
  zpaqfranz.cpp:64502:38: error: a space is required between consecutive right angle brackets (use '> >')
                                          vector<std::pair<uint64_t,string>>::iterator alto       = std::upper_bound(bysize.begin(), bysize.end(), p->second.size,mycompareuint64string());
                                                                          ^~
                                                                          > >
  zpaqfranz.cpp:64503:43: error: a space is required between consecutive right angle brackets (use '> >')
                                          for (vector<std::pair<uint64_t,string>>::iterator a=basso; a!=alto; a++)
                                                                               ^~
                                                                               > >
  zpaqfranz.cpp:64529:32: error: a space is required between consecutive right angle brackets (use '> >')
          vector<std::pair<string,string>> tobehashedsource_hashname;
                                        ^~
                                        > >
  zpaqfranz.cpp:64544:32: error: a space is required between consecutive right angle brackets (use '> >')
          vector<std::pair<string,string>> tobehasheddest_hashname;
                                        ^~
                                        > >
  zpaqfranz.cpp:64575:33: error: a space is required between consecutive right angle brackets (use '> >')
                  vector<std::pair<string,string>>::iterator basso        = std::lower_bound(tobehasheddest_hashname.begin(), tobehasheddest_hashname.end(), cerco,mycomparestringstring());
                                                ^~
                                                > >
  zpaqfranz.cpp:64578:34: error: a space is required between consecutive right angle brackets (use '> >')
                          vector<std::pair<string,string>>::iterator alto                 = std::upper_bound(tobehasheddest_hashname.begin(), tobehasheddest_hashname.end(), cerco,mycomparestringstring());
                                                        ^~
                                                        > >
  zpaqfranz.cpp:64580:39: error: a space is required between consecutive right angle brackets (use '> >')
                          for (vector<std::pair<string,string>>::iterator a=basso; a<alto; a++)
                                                             ^~
                                                             > >
  zpaqfranz.cpp:64606:33: error: a space is required between consecutive right angle brackets (use '> >')
                  vector<std::pair<string,string>>::iterator basso        = std::lower_bound(tobehasheddest_hashname.begin(), tobehasheddest_hashname.end(), cerco,mycomparestringstring());
                                                ^~
                                                > >
  zpaqfranz.cpp:64609:34: error: a space is required between consecutive right angle brackets (use '> >')
                          vector<std::pair<string,string>>::iterator alto                 = std::upper_bound(tobehasheddest_hashname.begin(), tobehasheddest_hashname.end(), cerco,mycomparestringstring());
                                                        ^~
                                                        > >
  zpaqfranz.cpp:64613:39: error: a space is required between consecutive right angle brackets (use '> >')
                          for (vector<std::pair<string,string>>::iterator a=basso; a<alto; a++)
                                                             ^~
                                                             > >
  zpaqfranz.cpp:64712:133: error: a space is required between consecutive right angle brackets (use '> >')
  int64_t Jidac::franzparallelhashfiles(string i_hashtype,int64_t i_totalsize,vector<string> i_thefiles,vector<std::pair<string,string>>& o_hashname)
                                                                                                                                      ^~
                                                                                                                                      > >
  14 errors generated.
  make: *** [zpaqfranz] Error 1
```

**Comment by p-linnane** [comment]
Opened an issue upstream: https://github.com/fcorbelli/zpaqfranz/issues/50

**Comment by ZhongRuoyu** [comment]
This is a C++ syntax issue. A space used to be required between consecutive right angles before - IIRC - C++11. It's very uncommon nowadays.

**Comment by ZhongRuoyu** [comment]
```
  g++-11  -O3 -std=c++11 -Dunix zpaqfranz.cpp -o zpaqfranz -pthread -lm
  zpaqfranz.cpp: In function ‘int64_t getramdisksize()’:
  zpaqfranz.cpp:52412:16: error: ‘internal_getramdisksize’ was not declared in this scope
  52412 |         return internal_getramdisksize(); /// if you get an error HERE substitute with return 0;
        |                ^~~~~~~~~~~~~~~~~~~~~~~
  make: *** [NONWINDOWS/Makefile:18: zpaqfranz] Error 1
```

Mmm. That's another issue.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
