### PR TITLE
Cake 0.14.0

### PR DESCRIPTION
**Pull request by gep13**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by gep13** [comment]
As per previous PR's for Cake, we are not in a position to run the final two steps. Please let us know if this causes a problem.

**Comment by MikeMcQuaid** [comment]
@gep13 Why not, out of interest?

**Comment by gep13** [comment]
@MikeMcQuaid as the person doing the release, I don't have access to a Mac, I am a Windows guy :smile: 

There are others on the team who have access to a Mac, but it was my turn to do the release this time around.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/b52714c13301afe2e24f1a10e3a13a480b539c6c. Thank you for your contribution to Homebrew @gep13; we appreciate it! :smiley_cat:

**Comment by gep13** [comment]
@DomT4 thank you! :-D

**Pull request merged**
