### PR TITLE
nyx 2.0.4 (new formula)

### PR DESCRIPTION
**Pull request by emanresusername**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

only tested on linuxbrew

### CODE REVIEW

**Comment by BenjaminHCCarr** [comment]
I run `nyx` and was maintaining `arm` - HEAD / `nyx` in my repo as well as `toralpha`

But `nyx` is available from `pip`, and my last understanding was that `pip` installable python was to be avoided.

```
benc$ pip search nyx
<snip>
Nyx (2.0.4)             - Terminal status monitor for Tor
                          (https://www.torproject.org/).
<snip>

benc$ pip install nyx
Password:
Collecting nyx
  Using cached nyx-2.0.4.tar.gz
Collecting stem>=1.6.0 (from nyx)
Installing collected packages: stem, nyx
  Running setup.py install for nyx ... done
Successfully installed nyx-2.0.4 stem-1.6.0
```

**Comment by DomT4** [comment]
> my last understanding was that pip installable python was to be avoided.

Applies to libraries rather than applications, IIRC.

**Comment by emanresusername** [comment]
yeah [some else said something similar](https://github.com/gleitz/howdoi/pull/174#issuecomment-342697550)
i could see the argument for not duplicating the package management
... *but* ...
i also like `brew install`ing all the things 
🤔 
figured i'd just leave this here and worse case it just gets closed out ¯\_(ツ)_/¯

**Comment by DomT4** [comment]
I think this has a legitimate place in Homebrew under the application/not a library general rule. It should have a functionality test and probably a `tor` dependency though.

**Comment by emanresusername** [comment]
re: `tor` dependency: thought about that too, but then considered a setup where they just want to monitor a tor process outside this homebrew ecosystem (e.g. [tor browser bundle](https://www.torproject.org/projects/torbrowser.html.en) has it's own self contained `tor` stuff). optional dependency maybe? 
re: functionality test: more than just the version check?

**Comment by DomT4** [comment]
> optional dependency maybe?

We've done two completely different things on this front in the past. We've either made it `:recommended` on the grounds that formulae should work "out-of-the-box" as such, or we've left the dependency out completely on the grounds that it isn't mandatory to build/install the formula. Throwing to @ilovezfs for a ruling.

> re: functionality test: more than just the version check?

Aye.

**Comment by emanresusername** [comment]
re: more than just version check: forgive my homebrew formula testing n00bery 😅 , could you outline what a functionality test in this context would look like?

**Comment by DomT4** [comment]
That's a good question. Having looked at `nyx` it's pretty minimalist unless you go to the trouble of setting up a whole `tor` relay, which I'm not sure Homebrew wants to be doing inside `test do` blocks for multiple reasons.

**Comment by emanresusername** [comment]
yeah that's what i was thinking

**Review by DomT4 — APPROVED** [review]
I think the test is as good as it gets here practically, for better or worse 🙃, so it's good with me at least.

**Review by ilovezfs — APPROVED** [review]

**Comment by JCount** [comment]
Thank you for your contribution, @emanresusername! 😄
I'm sorry it took so long to get it merged. Thank you for you patience, 👍!

**Pull request closed without merging**
