### PR TITLE
rust 1.14.0

### LINKED ISSUE #8656: Rust failed to build on Mac OS 10.12.2
Trying to install **rust** `HEAD` with following command: `brew install --HEAD rust`, I have an error:

~~~
configure: error: needed, but unable to find any of: CFG_CARGO cargo
~~~

Link to gist-logs: https://gist.github.com/cema-sp/4085820d0073d76cee591bdeeb2c6057

As I understood from [this cargo issue](https://github.com/rust-lang/cargo/issues/3437), one should have previous version of binary OR compile it from source. But compilation doesn't work on my laptop.

I have tried it a number of times and resolved the issue providing _./configure_ script `cargo` binary from stable **rust** bottle:

~~~sh
./configure --prefix=/usr/local/Cellar/rust/HEAD-7ef1a69 --local-rust-root=/usr/local/Cellar/rust/HEAD-7ef1a69 --enable-optimize --cargo=/usr/local/Cellar/rust/1.13.0/bin/cargo
make && make install
~~~

Any suggestions?
____

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew?

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Supersedes #5490.
Supersedes #8138.
Supersedes #8699.
Fixes #8656.

CC @nomoon @alex @cema-sp

### CODE REVIEW

**Comment by nijikon** [comment]
❤️

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by aktau** [comment]
This broke installing rust on Linuxbrew (not that this should be tested in the main homebrew repo I think, just leaving a note).

**Comment by ilovezfs** [comment]
interesting. can you please file an issue with Linuxbrew so we can determine the problem and where/who needs to fix it?

**Comment by aktau** [comment]
I already had before I posted here: https://github.com/Linuxbrew/homebrew-core/issues/1588.

**Comment by ilovezfs** [comment]
@aktau yes I think you're on to something. Linuxbrew, downstream, will need to alter that block to use the prebuilt Linux one.

**Comment by aktau** [comment]
> @aktau yes I think you're on to something. Linuxbrew, downstream, will need to alter that block to use the prebuilt Linux one.

Is it still possible to self-build one (or force that with some --without-prebuilt-cargo flag)? Because that would also be a solution. I tried manually generating the path for the prebuilt linux one but failed. I wonder where those are found.

**Pull request closed without merging**
