### PR TITLE
babeld 1.11

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by money5240** [comment]
porkepix:bump-babeld-1.11

**Comment by money5240** [comment]
porkepix:bump-babeld-1.11

**Comment by money5240** [comment]
porkepix:bump-babeld-1.11

**Comment by chenrui333** [comment]
```
message.c:501:16: error: member reference base type 'const unsigned char' is not a structure or union if(IN6_IS_ADDR_MULTICAST(to)) ^~~~~~~~~~~~~~~~~~~~~~~~~ /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/netinet6/in6.h:301:45: note: expanded from macro 'IN6_IS_ADDR_MULTICAST' #define IN6_IS_ADDR_MULTICAST(a) ((a)->s6_addr[0] == 0xff) ~~~^ ~~~~~~~ 1 error generated.
```

**Pull request closed without merging**
