### PR TITLE
yarn-completion 0.9.0

### PR DESCRIPTION
**Pull request by dsifford**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by kachkaev** [comment]
🤔 There's a hash mismatch for some reason.

    Expected: e7c7884fd4163f40be210aa70f5f2dd1ebe11e610eef938f1ca0795cc8e16f08
    Actual: b28fb51d5417a78b9e18c947e87dafd602de620e80360741ff0183dcf1e9c701

**Comment by dsifford** [comment]
Ping @jasonkarns -- Not sure why tests are failing, but if I had to guess it's because they are being ran on bash 3. Bash 4 is a firm requirement now.

**Comment by fxcoudert** [comment]
Please add a `depends_on "bash"` line with a comment on top

**Comment by fxcoudert** [comment]
Although I'm not entirely sure how useful are completions that only target a small fraction of our users

**Comment by dsifford** [comment]
@fxcoudert I hear ya, but bash-completion no longer supports bash 3 either. And I'd argue that there is really **no good reason** for anybody, ever, to use bash 3. The only reason why most people use it now is because apple is forced to use it due to licensing conflicts in bash 4 and the users either aren't aware of that OR they don't know how to upgrade to bash 4 (and set it as the login shell).

Adding the depends now...

**Comment by dsifford** [comment]
If someone can give me a little help here... It seems impossible to edit with the github editor and not have a trailing whitespace.

And I have no idea how to check this out... since this ostensibly isn't a branch on github.

Thanks

**Comment by jasonkarns** [comment]
It is a branch. The bump-formula-pr creates the branch locally, and pushes it to your fork of homebrew-core: https://github.com/dsifford/homebrew-core/tree/yarn-completion-0.9.0

Looking at the whitespace now, though.

**Comment by dsifford** [comment]
I think I may have just fixed it. I think the error message was a misnomer... wasn't actually trailing whitespace but a trailing blank line between the top commands and the bottle step

**Comment by jasonkarns** [comment]
You can also audit the formula locally with `brew audit yarn-completion`

**Comment by jasonkarns** [comment]
The audit errors are that `depends_on` needs to be after all the `url`, sha, and bottle lines...

**Comment by dsifford** [comment]
Gotcha. The issue though for me is I have no idea where homebrew made the local repo. It wasn't in the directory that I ran the PR command from. And too busy/lazy right now to sift through `~/Library`, etc.

I cloned this github repo locally, but there is no branch called `dsifford:yarn-completion-0.9.0` (not even on github -- go check). So yeah, sort of clunky.

**Comment by dsifford** [comment]
@jasonkarns Looks like it's still failing due to a bash 3 issue. 

I can confirm for sure that the [syntax is valid](https://travis-ci.com/dsifford/yarn-completion/jobs/148461062) so not sure how to make the tests run on bash 4.

**Comment by jasonkarns** [comment]
@fxcoudert Are we sure we want to include bash-completion@2 as a dependency? When this formula was introduced, we specifically _removed_ that dependency because it would mean that installing this formula will _also_ install a new version of bash. 

https://github.com/Homebrew/homebrew-core/pull/28645#issuecomment-394625273

I think it would be a bad UX to install a completion script and end up with an entirely new shell.

Separately, is there a way we can trigger a re-build? I've confirmed that the completion script itself is _syntactically_ valid for bash 3.2 so it sources successfully on old bash.

**Comment by dsifford** [comment]
> Are we sure we want to include bash-completion@2 as a dependency?

The syntax is mostly fine for bash 3, but I believe there are also some bash 4 goodies sprinkled in there as well. And, if somehow it _does_ run without issues, it uses stuff from `bash-completion@2` that will certainly not work on bash 3. So really, if the person is running bash 3, there's really no reason whatsoever to have this installed on the system.

**Comment by jasonkarns** [comment]
@dsifford adding bash-completion@2 as a dependency means that installing yarn-completion will _also_ install bash-completion@2 (if not already installed) which itself installs bash v4 (if not already installed).

> I think it would be a bad UX to install a completion script and end up with an entirely new shell.

So while this formula does rely on bash4 and bash-completion@2, I do not think it should explicitly list either as an actual dependency, since installing a completion script should not upgrade my shell. This is why bash was explicitly omitted from the dependency list when this formula was initially added to homebrew.

**Comment by dsifford** [comment]
Makes sense. Just throwing some thoughts out there to mull over. No strong feelings either way since I have bash 4 installed on my mac so it really doesn't affect me either way.

**Pull request closed without merging**
