### PR TITLE
git-annex 7.20190912

### PR DESCRIPTION
**Pull request by nirgo**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Please squash everything into a single commit

**Comment by nirgo** [comment]
@BrewTestBot test

**Comment by nirgo** [comment]
@fxcoudert - Tests failed due to mojave_stadium_2 having Jenkins issues. What's the best way to trigger another test without another commit? Can I trigger with a comment?

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@nirgo just did a trigger :)

**Comment by nirgo** [comment]
@chenrui333 - thanks! Do you know if the @BrewTestBot commands documented anywhere?

**Comment by chenrui333** [comment]
It is documented in here, https://docs.brew.sh/New-Maintainer-Checklist

Seems only available for maintainers.

**Pull request closed without merging**
