### PR TITLE
qt 5.9.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @dakcarto it's that time again!

**Review by ilovezfs — COMMENTED** [review]
.

**Comment by DomT4** [comment]
Oh no, not a fresh Qt release 😅.

**Comment by ilovezfs** [comment]
@DomT4 I cannot wait to see what will now fail to build.

**Comment by DomT4** [comment]
This is taking a long time even for a Qt build. How fun.

**Pull request closed without merging**
