### PR TITLE
wolfssl 3.15.5

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
Build fails due to regression here https://github.com/Homebrew/homebrew-core/pull/34198

**Comment by ejohnstown** [comment]
How is homebrew's script cloning our repo for your build? Are you doing an actual git clone or are you downloading the GitHub tagged source archive?

**Comment by ejohnstown** [comment]
Switching to git clone will help. The autogen.sh script looks for the existence of ".git", and if present touches the access controlled files like fips.h to create them. (The stub files end up in the archives we create with make dist.)

BTW, we have a new option called "--enable-sp", which turns on the single precision math library for the public key operations. They are time invariant and come in both C and assembly versions. They make a tremendous speed up in the public key operations.

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
`brew cleanup --prune=7` failed but I don't think it's related

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
@Moisan same as https://github.com/Homebrew/homebrew-core/pull/34349 and https://github.com/Homebrew/homebrew-core/pull/34338
```
==> ./autogen.sh
Can't locate loadable object for module Fcntl in @INC (@INC contains: /usr/local/Cellar/autoconf/2.69/share/autoconf /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /System/Library/Perl/5.18/File/stat.pm line 30.
Compilation failed in require at /System/Library/Perl/5.18/File/stat.pm line 30.
BEGIN failed--compilation aborted at /System/Library/Perl/5.18/File/stat.pm line 30.
Compilation failed in require at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 40.
BEGIN failed--compilation aborted at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 40.
Compilation failed in require at /usr/local/opt/autoconf/bin/autoreconf line 42.
BEGIN failed--compilation aborted at /usr/local/opt/autoconf/bin/autoreconf line 42.
```

**Comment by igas** [comment]
Apart from it formula itself fixed

**Comment by Moisan** [comment]
Thank you @igas for the PR and @ejohnstown for the input!

**Pull request closed without merging**
