### PR TITLE
imake: use tradcpp

### PR DESCRIPTION
**Pull request by paperchalice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why?

**Comment by paperchalice** [comment]
> Why?

[macports](https://ports.macports.org/port/imake/details/) uses it and `imake` just needs a traditional c preprocessor, `tradcpp` is a lightweight choice.

**Comment by SMillerDev** [comment]
Is anything wrong with the current version?

**Comment by fxcoudert** [comment]
If we can avoid a super-heavy dependency like gcc with a functional, lighter equivalent, I think we should do it.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
