### PR TITLE
Secure URL(s)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
`ftp://invisible-island.net/` doesn't seem to respond and I couldn't find public `https` download links for the versioned downloads, so I used `mirrorservice.org` links to replace them.

### CODE REVIEW

**Comment by vszakats** [comment]
Removed `mawk` due to test failure on Sierra (unrelated to these updates):
```
09:32:40 Testing mawk
09:32:40 /usr/bin/sandbox-exec -f /tmp/homebrew20170809-37928-8y2fmh.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mawk.rb --verbose
09:32:40 ==> /usr/local/Cellar/mawk/1.3.4-20161120/bin/mawk -W version 2>&1 | /usr/local/Cellar/mawk/1.3.4-20161120/bin/mawk '/^mawk / {printf("%s-%s", $2, $3)}'
09:32:40 sh: line 1: 37938 Abort trap: 6           /usr/local/Cellar/mawk/1.3.4-20161120/bin/mawk -W version 2>&1
09:32:40      37939                       | /usr/local/Cellar/mawk/1.3.4-20161120/bin/mawk '/^mawk / {printf("%s-%s", $2, $3)}'
09:32:40 Error: mawk: failed
09:32:40 <0> expected but was
09:32:40 <134>.
```

**Comment by fxcoudert** [comment]
I think it's a bad idea to replace `ftp` sites with a third-party service, even over HTTPS (`https://mirrorservice.org`). We already use SHA sums to ensure that users download the right files, and content isn't changed.

The rest (moving to HTTPS on the same site, when supported) is OK.

**Comment by vszakats** [comment]
I agree it's a bad idea, but as I wrote in the initial message, the reason for this was that the FTP site _doesn't work_, making all CI tests fail. I have no way to say if this is temporary or by design, but it was consistently down while testing, as tested from multiple clients. The homepage still lists the FTP as a valid download site, so maybe it's just a bug.

So, shall I restore them to their originals anyway and let the CI tests fail?

**Comment by fxcoudert** [comment]
Sorry, read to quickly. Please notify upstream, and see what they say. We'll decide accordingly.

**Comment by vszakats** [comment]
I've sent an email.

**Comment by ilovezfs** [comment]
I think it's changed from, for example, `ftp://invisible-island.net/bcpp/bcpp31209.tgz` to `ftp://ftp.invisible-island.net/bcpp/bcpp-20131209.tgz`

**Comment by vszakats** [comment]
@ilovezfs Yes, just received the same answer from the author:
`ftp://ftp.invisible-island.net/bcpp/bcpp-20131209.tgz`

**Comment by vszakats** [comment]
Closing this one in favour of https://github.com/Homebrew/homebrew-core/pull/16616
(it was quicker to recreate than fixing this one)

**Pull request closed without merging**
