### PR TITLE
f3d 1.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by chenrui333** [comment]
Filed build failure report in here, https://gitlab.kitware.com/f3d/f3d/-/issues/197

**Comment by chenrui333** [comment]
cc @Meakk

**Comment by Meakk** [comment]
Sorry, we missed this build error and I noticed that yesterday. We have pushed a new tag, so it should be ok now.  
The new sha is `93aa9759efcc4e77beac4568280aaeaca21bfb233d3c9f60262207ca595bde79`.  
Please, remove the patch as well which is useless now (`# Is fixed upstream, remove this line for v1.1` and the lines below this comment).  
Thanks for taking care of this!

**Comment by chenrui333** [comment]
> Sorry, we missed this build error and I noticed that yesterday. We have pushed a new tag, so it should be ok now.
> The new sha is `93aa9759efcc4e77beac4568280aaeaca21bfb233d3c9f60262207ca595bde79`.
> Please, remove the patch as well which is useless now (`# Is fixed upstream, remove this line for v1.1` and the lines below this comment).
> Thanks for taking care of this!

Thanks for confirming! :)

**Comment by chenrui333** [comment]
```
CMake Error in src/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
```

**Comment by SeekingMeaning** [comment]
Possibly related: https://github.com/Homebrew/homebrew-core/issues/67075, which might be fixed by https://github.com/Homebrew/brew/pull/10072 (changes `MacOS.sdk_path_if_needed` to return the unversioned SDK path)

**Comment by carlocab** [comment]
Forcing a rebuild of `vtk` should fix this error, I think. This probably shouldn't be a revision bump, since a revision bump will probably break `vtk` for everyone still running 11.0.1.

This probably also means `vtk` is already broken for everyone on 11.1, but they'll be able to do `brew upgrade vtk` to fix it if `vtk` is rebuilt.

**Comment by chenrui333** [comment]
still the same error :(

**Comment by SeekingMeaning** [comment]
Should hopefully be fixed once #67428 is merged

**Comment by carlocab** [comment]
Merged. Try rebasing this against master.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
