### PR TITLE
metals: fix source sha256

### PR DESCRIPTION
**Pull request by WangEdward**
Checksum for metals 1.2.2 source archive changed

https://github.com/Homebrew/homebrew-core/actions/runs/8602702349/job/23584694069?pr=168294#step:3:3387

### CODE REVIEW

**Comment by chenrui333** [comment]
@WangEdward can you file an upstream issue to confirm if there is any re-tagging happened?

**Comment by WangEdward** [comment]
> @WangEdward can you file an upstream issue to confirm if there is any re-tagging happened?

https://github.com/scalameta/metals/discussions/6291

**Comment by tgodzik** [comment]
That was my bad, sorry about the issue! I wasn't entirely aware of the impact the retagging would cause.

**Comment by chenrui333** [comment]
@tgodzik thanks for confirming the re-tagging. Yeah, in general, as package manager, we are trying to reduce the supply chain risk.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Also thanks @WangEdward for the efforts!

**Pull request merged**
