### PR TITLE
nauty: add missing nauty's installed programs

### PR DESCRIPTION
**Pull request by dimpase**
nauty 2.8.8 added new programs, but they were not added at the update. See https://pallini.di.uniroma1.it/changes24-28.txt

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
This is a tricky to maintain installation.

Is there any reason we can't use `make install` for most of files (I think everything other than `doc` and `pkgshare` files)? I would hope upstream keeps that target up-to-date.

---

Also need confirmation of tarball checksum change by upstream.

**Comment by dimpase** [comment]
I just went for a minimal change without looking at nauty's build system. I'll see if I can make it easier.

**Comment by dimpase** [comment]
earlier versions of nauty provided no proper `make install`.  But 2.8.8 does have a `make install`, it even does the right thing with the libraries.

**Comment by dimpase** [comment]
> This is a tricky to maintain installation.
> 
> Is there any reason we can't use `make install` for most of files (I think everything other than `doc` and `pkgshare` files)? I would hope upstream keeps that target up-to-date.

It should be possible, I'm updating the formula now.
> 
> Also need confirmation of tarball checksum change by upstream.

I'm not 100% sure what you mean by this.
Yes, sha265 has changed since 2023-11-20, the day before the release:
```
01749727ab2d Formula/n/nauty.rb (Patrick Linnane 2023-11-20 17:50:12 -0800  5)   sha256 "accf5eeddde623d179c8fee9d15cfb7d66d7a90cc7684d11c96ad9b3f3655dbb"
```
is no longer valid. (sorry, I forgot to check...) 

5 days after the release date, 2023-11-21 (cf. https://mailman.anu.edu.au/pipermail/nauty/2023-November/000940.html), sha1 and md5 were computed, see
https://github.com/sagemath/sage/blob/develop/build/pkgs/nauty/checksums.ini
```
% git blame build/pkgs/nauty/checksums.ini
...
3e8011f4e18 (Matthias Koeppe 2023-11-26 11:58:06 -0800 2) sha1=672e9fc9dfd07201af37ee65807a9b493331ed92
3e8011f4e18 (Matthias Koeppe 2023-11-26 11:58:06 -0800 3) md5=16c6edc1a8747c9281041b7c7092135f
...
```
and these are OK today (2024-01-13)

**Comment by dimpase** [comment]
@p-linnane - could you comment on the history of `sha256` of the source tarball?

**Comment by p-linnane** [comment]
> @p-linnane - could you comment on the history of `sha256` of the source tarball?

The appropriate thing to do here is reach out to upstream and ask them to confirm they retagged or reuploaded the release.

**Comment by dimpase** [comment]
How do I actually test the updated formula locally? I'm getting
```
Error: nauty: SHA256 mismatch
Expected: accf5eeddde623d179c8fee9d15cfb7d66d7a90cc7684d11c96ad9b3f3655dbb
  Actual: 159d2156810a6bb240410cd61eb641add85088d9f15c888cdaa37b8681f929ce
```
(the "Actual" is the correct value for the tarball...)

**Comment by p-linnane** [comment]
Edit the `nauty.rb` file locally and change the hash to the new one.

**Comment by dimpase** [comment]
> > @p-linnane - could you comment on the history of `sha256` of the source tarball?
> 
> The appropriate thing to do here is reach out to upstream and ask them to confirm they retagged or reuploaded the release.

I wrote to upstream - how quickly they'd reply is another question.
Do you have the tarfile with the old checksum anywhere?
We could just compare the contents, it might be quicker.

**Comment by dimpase** [comment]
> Edit the `nauty.rb` file locally and change the hash to the new one.

sure, that's what I did, and I made my github homebrew-core clone a local tap `dimpase/core`.
(maybe there is an easier way, I don't know - or don't recall)

Now I'm running `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source dimpase/core/nauty` and getting the SHA mismatch error - i.e. `brew` has the old SHA stored somewhere it trusts better than my cask.

**Comment by dimpase** [comment]
With changed `nauty.rb`, it works fine with just `brew install --build-from-source --formula nauty.rb`. Also `brew test nauty.rb` works.

**Comment by dimpase** [comment]
all clear w.r.t. the tarball:

> > > @p-linnane - could you comment on the history of `sha256` of the source tarball?
> > 
> > 
> > The appropriate thing to do here is reach out to upstream and ask them to confirm they retagged or reuploaded the release.
> 
> I wrote to upstream - how quickly they'd reply is another question. Do you have the tarfile with the old checksum anywhere? We could just compare the contents, it might be quicker.

```
Date: Sun, 14 Jan 2024 11:50:50 +1100
From: Brendan McKay <Brendan.McKay@anu.edu.au>
To: Dmitrii Pasechnik <dima.pasechnik@cs.ox.ac.uk>
Subject: Re: changed tarball for nauty 2.8.8 ?
User-Agent: Mozilla Thunderbird

Dear Dima,

We fixed a typo in the changes file  changes24-28.txt  about Nov 22.
None of the program code was changed.

Sorry about the trouble.

Brendan.


On 14/1/2024 9:13 am, Dmitrii Pasechnik wrote:
> Dear Brendan,
>
> at some point in November 2023 (?), the tarball for nauty 2.8.8
> at https://pallini.di.uniroma1.it/nauty2_8_8.tar.gz
> and https://users.cecs.anu.edu.au/~bdm/nauty/nauty2_8_8.tar.gz
> has changed, its sha256 became
> 159d2156810a6bb240410cd61eb641add85088d9f15c888cdaa37b8681f929ce
> while it was
> accf5eeddde623d179c8fee9d15cfb7d66d7a90cc7684d11c96ad9b3f3655dbb
> at the time the update was done for the Homebrew
> https://formulae.brew.sh/formula/nauty#default
> (Homebrew is a "missing package manager" for macOS, very popular
> among Apple users)
>
> I'm trying to fix something there:
> https://github.com/Homebrew/homebrew-core/pull/159841
> and am asked to contact you for a confirmation that the tarball
> was indeed changed...
>
> Could you please tell us what happened to the tarball.
>
> Season's greetings,
> Dima
>
```

**Comment by p-linnane** [comment]
Thanks for confirming. Running through CI now and will get this merged.

**Review by p-linnane — APPROVED** [review]

**Comment by dimpase** [comment]
This introduced a regression: the `*.pc` files got installed in `/usr/local/Cellar/nauty/2.8.8/libdata/pkgconfig/`
rather than `/usr/local/Cellar/nauty/2.8.8/lib/pkgconfig/`, sorry.

The easiest way to fix this would be to patch sources `makefile.in`.
Is this OK? I'll open a new PR then.

**Comment by p-linnane** [comment]
Please open the PR and we will review.

**Pull request merged**
