### PR TITLE
apache-arrow and apache-arrow-glib 1.0.0

### PR DESCRIPTION
**Pull request by nealrichardson**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jeroen** [comment]
I think you need to remove `depends_on "llvm" => :build` ? You don't need homebrew llvm, it builds fine with xcode.

**Comment by nealrichardson** [comment]
We need `llvm` for the `-DARROW_GANDIVA=ON` flag. This was added in https://github.com/apache/arrow/commit/de88c9ae4cad883c8fbeba51d5da40b2c99e03c7, which we test nightly in our CI. But apparently our nightly testing doesn't match what's being run here. So the solution is to disable Gandiva again.

**Comment by SMillerDev** [comment]
Xcode ships a version of llvm. Why isn't that one sufficient?

**Comment by nealrichardson** [comment]
> Xcode ships a version of llvm. Why isn't that one sufficient?

🤷 I'll try it and we'll see if it is sufficient.

**Comment by jeroen** [comment]
> But apparently our nightly testing doesn't match what's being run here. 

The problem is that you have declared llvm as a build dependency, however, by compiling with llvm you are linking against the libc++ that comes with llvm. So thereby llvm is actually a runtime dependency (which you probably want to avoid).

**Comment by nealrichardson** [comment]
Without specifying llvm but leaving Gandiva on, it fails:

```
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Could NOT find LLVM (missing: LLVM_DIR)
CMake Error at /usr/local/Cellar/cmake/3.18.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find LLVMAlt (missing: LLVM_PACKAGE_VERSION CLANG_EXECUTABLE
  LLVM_FOUND LLVM_LINK_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindLLVMAlt.cmake:71 (find_package_handle_standard_args)
  src/gandiva/CMakeLists.txt:28 (find_package)
```

I'll turn Gandiva back off and we can sort out enabling it in the next release.

**Comment by nealrichardson** [comment]
I've disabled the offending feature and squashed the commits so that they're clean. PTAL.

**Comment by nealrichardson** [comment]
Checking back in; is there anything left to do here?

**Comment by SeekingMeaning** [comment]
Question: why is jemalloc enabled here?

**Review by SeekingMeaning — DISMISSED** [review]

**Comment by nealrichardson** [comment]
> Question: why is jemalloc enabled here?

It is a cmake option for `apache-arrow`, and we've made some changes such that we can now enable it in the Homebrew formula.

**Pull request closed without merging**
