### PR TITLE
pyqt@5: add `python@3.11`

### PR DESCRIPTION
**Pull request by branchv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

### CODE REVIEW

**Comment by chenrui333** [comment]
can you maybe you use rebase? I think that would be better way to do this.

**Comment by chenrui333** [comment]
I feel like github status is sometimes not good with close/reopen

**Comment by branchvincent** [comment]
Yea not sure what happened, CI never kicked off after clicking `Re-run jobs` so tried re-opening

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
> Yea not sure what happened, CI never kicked off after clicking `Re-run jobs` so tried re-opening

Could be github outage?

**Comment by chenrui333** [comment]
Looks like the same deal as the other one

**Comment by chenrui333** [comment]
Need a re-run for this PR.

**Review by chenrui333 — APPROVED** [review]

**Comment by fxcoudert** [comment]
On macOS Ventura Intel, this replacement is not working:


:x: @fxcoudert bottle request for pyqt@5 [failed](https://github.com/Homebrew/homebrew-core/actions/runs/3481969428).

```
Error: inreplace failed
  /usr/local/Cellar/pyqt@5/5.15.7_1/bin/pyrcc5:
    expected replacement of #<Pathname:/usr/local/opt/python@3.10/bin/python3.10> with "python3"
```

**Comment by fxcoudert** [comment]
I have been able to repeat this failure of `inreplace` on CI. I do not know why it is specific to Intel Ventura, either some instability in the order in which resources are installed? But a more general fix is required.

**Pull request closed without merging**
