### PR TITLE
openssl@3 3.0.7

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Dependents look good on ARM. Let's not wait for the results elsewhere to avoid needing a long-running CI job.

**Review by carlocab — APPROVED** [review]

**Comment by Tklaversma** [comment]
@carlocab do you have any ETA on those tests and thus when the update is live?

**Comment by p-linnane** [comment]
@Tklaversma I just checked the queue. It will be within the next couple hours.

**Comment by NickTaylor-** [comment]
Looks like this is good to go?

**Pull request closed without merging**
