### PR TITLE
Add interval service blocks

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
If we want to run these changes as syntax-only we should add an audit.

**Comment by spywhere** [comment]
I'm not sure why I cannot submit a new issue, though I believe this PR is breaking the service installation.

```
~ ➜ brew install mpd
==> Downloading https://ghcr.io/v2/homebrew/core/mpd/manifests/0.22.11
Already downloaded: /Users/spywhere/Library/Caches/Homebrew/downloads/eb02dca9672e1e9998a8df7274e2772b5c740ddffadf9d0e3e8950173d17bfbf--mpd-0.22.11.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpd/blobs/sha256:1b530b08224755e76ed13fe0a22c6f23fb274e650fbd3b46313da7ff7ebadfdd
Already downloaded: /Users/spywhere/Library/Caches/Homebrew/downloads/1e0c009b9fcaa78bbb89c6d23a3c309501e06f5ff2315f45b121c12c1f780869--mpd--0.22.11.arm64_monterey.bottle.tar.gz
==> Pouring mpd--0.22.11.arm64_monterey.bottle.tar.gz
Error: Failed to install service files
Error: Service#process_type expects a String
/opt/homebrew/Library/Homebrew/service.rb:139:in `process_type'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpd.rb:95:in `block in <class:Mpd>'
/opt/homebrew/Library/Homebrew/service.rb:196:in `instance_eval'
/opt/homebrew/Library/Homebrew/service.rb:196:in `manual_command'
/opt/homebrew/Library/Homebrew/caveats.rb:160:in `service_caveats'
/opt/homebrew/Library/Homebrew/caveats.rb:43:in `caveats'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:224:in `empty?'
/opt/homebrew/Library/Homebrew/formula_installer.rb:767:in `caveats'
/opt/homebrew/Library/Homebrew/formula_installer.rb:825:in `finish'
/opt/homebrew/Library/Homebrew/upgrade.rb:209:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:320:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:310:in `block in install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:309:in `each'
/opt/homebrew/Library/Homebrew/install.rb:309:in `install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:208:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by carlocab** [comment]
Try doing `brew update` first. What is the output of `brew config` and `brew doctor`?

**Comment by spywhere** [comment]
It is already up to date.

```
~ ➜ brew update                                                                                                                                                                                                                             
Already up-to-date.
```

`brew config`

```
~ ➜ brew config
HOMEBREW_VERSION: 3.3.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 64fb3c86f87eaf4a4b2ba64ddec0a5a3f2530b4c
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cceccf01a8edd873f0c0be98fdfc9ebc228f67d1
Core tap last commit: 9 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
Rosetta 2: false
```

`brew doctor`

```
~ ➜ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/spywhere/.asdf/shims/python3.9-config
  /Users/spywhere/.asdf/shims/python-config
  /Users/spywhere/.asdf/shims/python3-config
  /Users/spywhere/.asdf/shims/pre-commit-validate-config

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

**Comment by carlocab** [comment]
https://github.com/Homebrew/brew/commit/ca7623c70ff65a90b3689f312767ca85a2fbb6d5 isn't in the 3.3.3 release tag, which is what you need to be able to install `mpd`.

Try `brew developer on && brew update && brew install mpd`. You can do `brew developer off` after that.

**Comment by spywhere** [comment]
That's worked perfectly, thanks for the quick workaround while waiting for the official update 😄

**Comment by carlocab** [comment]
Great; glad it works. We usually wait until an appropriate release is tagged before merging changes like this. There was an oversight here. Apologies for the inconvenience!

**Pull request closed without merging**
