### PR TITLE
php@5.6 removal due to EOL

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
PHP 5.6 is EOL since december 31st.

### CODE REVIEW

**Comment by javian** [comment]
I'm all for this but perhaps and we should also refer to the discussion in https://github.com/Homebrew/homebrew-core/pull/34739 where we removed 7.0 for similar reasons. Since we have 10k installs since the final update in december it is likely that it will be noticed.

**Review by javian — DISMISSED** [review]
There's also an entry in "formula_renames.json" that can be removed.

**Comment by javian** [comment]
No, I don't think anything should change about it but since a similar discussion is likely to appear we can just refer to the discussion in the old issue to not have to repeat it again from the beginning.

**Review by fxcoudert — APPROVED** [review]

**Review by igas — APPROVED** [review]

**Review by javian — APPROVED** [review]

**Comment by pgrenaud** [comment]
I'm leaving this note here in case someone stumble on this PR in the near future. Not that we condone the use of deprecated software, but I've setup a tap at my organisation to be able to support older software that were not migrated yet. I've already added the php 5.6 formula in anticipation of January first.

You can find the tap here: https://github.com/eXolnet/homebrew-deprecated

**Comment by afilina** [comment]
@pgrenaud Thanks!

@SMillerDev Just because a language is EOL, doesn't mean that devs stop supporting the legacy applications built on it. I don't see what upstream EOL has to do with package distribution. It's not like they deleted the tar.gz

**Comment by SMillerDev** [comment]
It's the policy homebrew defines for any non-latest version it keeps around. It prevents potentially insecure versions to be shipped by homebrew, if upstream stops supporting an older version so will homebrew.

**Pull request merged**
