### PR TITLE
Remove long timeout label handling

### PR DESCRIPTION
**Pull request by carlocab**
This shouldn't be needed anymore after Homebrew/ci-orchestrator#13.

### CODE REVIEW

**Comment by carlocab** [comment]
I'll be around tomorrow to make sure this is working as intended post-merge.

**Review by MikeMcQuaid — APPROVED** [review]
Looks great, thanks again @carlocab, excited to see this land!

**Review by chenrui333 — APPROVED** [review]
nice!

**Review by p-linnane — APPROVED** [review]
Awesome work! Thanks!

**Review by ZhongRuoyu — APPROVED** [review]
Thanks @carlocab!

**Comment by carlocab** [comment]
Merging now. Next we probably want to handle setting long time outs more carefully by separating out `long build` from `long deps tests`.

**Pull request merged**
