### PR TITLE
apr: remove `libxcrypt` dependency.

### PR DESCRIPTION
**Pull request by carlocab**
This is not a dependency. See #108662.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by cho-m** [comment]
`apr` does create files (apr-1-config, apr-1.pc) with `-lcrypt`.

libcrypt.so is currently indirect via `util-linux` (though, based on Fedora, if we were to split `libuuid` from `util-linux` then it might not directly depend on `libxcrypt`).

`apr` build does try to compile with `-lcrypt` so I am a bit curious why upstream is doing this but we have no linkage.

**Comment by danielnachun** [comment]
On the system I am on, I see this for `brew linkage --reverse apr`:
```
/home/dnachun/.linuxbrew/lib/libc.so.6
  lib/libapr-1.so.0.7.0

/home/dnachun/.linuxbrew/opt/libxcrypt/lib/libcrypt.so.2
  lib/libapr-1.so.0.7.0

/home/dnachun/.linuxbrew/opt/util-linux/lib/libuuid.so.1
  lib/libapr-1.so.0.7.0
```

And `libuuid.so.1` only reports linkage to `libc.so.6`.  In fact the only thing in `util-linux` that reports linkage to `libcrypt.so.2` is `sbin/sulogin`, so that does not seem to support the idea that `apr` gets the linkage to `libcrypt` through `util-linux` and, at least optionally, can depend on `libxcrypt`.  

However when I build the `apr` bottle in the CI Docker image without `libxcrypt` as a dependency, it doesn't try to link to `libcrypt.so.1`.  Perhaps the linkage cache I had was outdated?  `apr` is a relocatable bottle so I would never have built it from source where opportunistic linkage could have happened.

**Comment by Bo98** [comment]
I do see `apr` does contain crypt code.

`config.log` data might be useful here.

**Comment by carlocab** [comment]
That should be available in the `logs-*` artifacts, except uploading the logs doesn't work on Linux for some reason.

**Comment by Bo98** [comment]
Because GitHub hosted runners don’t currently use --local, which the upload logic assumes is passed.

Self-hosted does use it.

**Comment by danielnachun** [comment]
I'll do a local run and upload the logs shortly.

**Comment by danielnachun** [comment]
Gist for building without `libxcrypt`: https://gist.github.com/danielnachun/6923e5b44250d810b92b81c3d7e5fe83

Gist for building with `libxcrypt`: https://gist.github.com/a4ac226148f6b15c746bf8837b914c62

**Pull request closed without merging**
