### PR TITLE
geant4 10.6.2

### PR DESCRIPTION
**Pull request by cxwx**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@cxwx 👋  thanks for the PR, can you squash your commits into one, `geant4 10.6.2`?

Also for your future PRs, it would be better to have a separate branch rather than `master` so that I can help with the commit squash as well. Thanks!

**Comment by cxwx** [comment]
> @cxwx 👋 thanks for the PR, can you squash your commits into one, `geant4 10.6.2`?
> 
> Also for your future PRs, it would be better to have a separate branch rather than `master` so that I can help with the commit squash as well. Thanks!
sorry for that.
my network is too bad, it is easier for me to recreate a new branch, I'll close this one and recreate new one.

**Comment by chenrui333** [comment]
Sounds good, thanks!!

**Comment by cxwx** [comment]
new pull request @ `https://github.com/Homebrew/homebrew-core/pull/58662`

**Pull request closed without merging**
