### PR TITLE
vulkan 1.3.269

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
`    Errno::ENOENT: No such file or directory - /opt/homebrew/Cellar/vulkan-tools/1.3.269/vulkaninfo/vulkaninfo`

**Review by juan-lunarg — COMMENTED** [review]
Note you can remove the following from the vulkan validation layers.

BUILD_LAYERS and BUILD_LAYER_SUPPORT_FILES are removed and do nothing except trigger warnings.

```
      "-DBUILD_LAYERS=ON",
      "-DBUILD_LAYER_SUPPORT_FILES=ON",
```

**Comment by chenrui333** [comment]
> Note you can remove the following from the vulkan validation layers.
> 
> BUILD_LAYERS and BUILD_LAYER_SUPPORT_FILES are removed and do nothing except trigger warnings.
> 
> ```
>       "-DBUILD_LAYERS=ON",
>       "-DBUILD_LAYER_SUPPORT_FILES=ON",
> ```

thanks for that info, i think the current issue is with the vulkan-tools build

**Comment by juan-lunarg** [comment]
> thanks for that info, i think the current issue is with the vulkan-tools build

Does it relate to this?
https://github.com/LunarG/VulkanTools/pull/1917

**Pull request closed without merging**
