### PR TITLE
ccze: Fix C pre-processor directive

### PR DESCRIPTION
**Pull request by onlynone**
See issue #681

### CODE REVIEW

**Comment by DomT4** [comment]
Where was this reported upstream? We probably want to bump the `revision` as well if we're fixing breakage.

**Comment by onlynone** [comment]
It hadn't been previously (until I just did today).
On May 3, 2016 13:21, "Dominyk Tiller" <notifications@github.com> wrote:

Where was this reported upstream? We probably want to bump the revision as
well if we're fixing breakage.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Homebrew/homebrew-core/pull/810#issuecomment-216602128>

**Comment by UniqMartin** [comment]
> It hadn't been previously (until I just did today).

I think we have a misunderstanding here. By “reported to upstream” we mean reported to the developers of `ccze`. That's not us (Homebrew), as we're just packaging other people's software, but not maintaining it ourselves. For Homebrew to accept a patch to a formula, it needs to be sent to the upstream developers and accepted by them. (If you did, please provide a URL to the mailing list message, issue tracker entry, or whatever channel of communication you used to submit your patch.)

**Comment by onlynone** [comment]
I know what reported to upstream means.

1. I hadn't reported this issue anywhere except for here at first.
2. Then I found the issue with `HAVE_SUBOPTARg`.
3. Then I created the PR here.
4. Then I [created this bug report at Debian](http://bugs.debian.org/823334) after you said "Alright, so this seems to be an upstream issue. Thanks for reporting it to them!"

Now, a true upstream doesn't really seem to exist. The package seems to be abandoned and only maintained at various distros like debian. Since this formula points to debian for the source, I figured that's the closest to "upstream" this package has.

However, upon further investigation I've found that this bug was independently fixed in freebsd 13 years ago:

http://lists.freebsd.org/pipermail/freebsd-ports-bugs/2003-September/013364.html

And in gentoo 6 years ago:

https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/app-admin/ccze/files/ccze-fbsd.patch?hideattic=0&revision=1.1&view=markup

I'm thinking that it might make more sense to base this formula on either the freebsd port (since OS X has a bsd userland) or gentoo since they seem to have even more patches to ccze that address building and segfaulting:

https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/app-admin/ccze/files/

**Comment by UniqMartin** [comment]
> I know what reported to upstream means.

Sorry if I implied otherwise and thanks for clarifying things! That's just what I gathered from the little information that I had available. Now I have a much clearer picture.

> Now, a true upstream doesn't really seem to exist.

That's somewhat unfortunate and doesn't really fit Homebrew's expectations for fomulae. Our [usual acceptance criteria](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md) require upstream to exist and be active. Of course since the formula is already in Homebrew, we might judge differently than with new formulae being submitted.

As the formula basically never changed since it was added three years ago and seems to be both low maintenance and somewhat popular, we might as well accept this patch. I'm not sure about the other patches (the ones from Gentoo) and whether they apply here. Thanks for the through investigation!

Can you please extend the comment above the `patch :DATA` line with a brief summary of this and links to the respective FreeBSD/Gentoo resources, so future maintainers/contributors can easier understand the situation? Thanks!

@DomT4 Any major objections to pulling this as-is? An upstream is unlikely to appear out of nowhere, but I think it's worth applying the patch instead of boneyarding this formula.

**Comment by DomT4** [comment]
Given it's only a single line and we may well be carrying this indefinitely we should be using an `inreplace` rather than a patch, i.e.:

```ruby
def install
  # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823334
  inreplace "src/ccze-compat.c", "#if HAVE_SUBOPTARg", "#if HAVE_SUBOPTARG"
```

And we probably want to bump the revision since it fixes current breakage.

Otherwise, 👍.

**Comment by UniqMartin** [comment]
> Given it's only a single line and we may well be carrying this indefinitely we should be using an `inreplace` rather than a patch, i.e.:

What's the advantage of using `inreplace` over extending the already existing patch? I can only see disadvantages: no context and a greater likelihood of matching stuff it's not supposed to match …

> And we probably want to bump the revision since it fixes current breakage.

Indeed, good point.

**Comment by DomT4** [comment]
> What's the advantage of using inreplace over extending the already existing patch?

It's Homebrew "policy" that if we have to carry something indefinitely with potentially no chance of it ever being accepted upstream we heavily prefer `inreplace`s, especially for single-line changes.

I'm way too tired to get particularly passionate about if it you are, but let's at least ship the patch to the patches repo given the awful dance that is inline patching.

**Comment by UniqMartin** [comment]
@onlynone Please follow @DomT4's advice on using `inreplace` instead of extending the inline patch and please bump the revision, i.e. add a `revision 1` line below the topmost `sha256` line in the formula, so existing installations will be updated and users get the fixed version. Once this is done we're good to go.

**Comment by DomT4** [comment]
Applied additional changes in a follow-up commit.

Merged in https://github.com/Homebrew/homebrew-core/commit/0a02e10fefcfd1e79839fa9c0892ee5d27bfc0b1. Thank you for your contribution to Homebrew @onlynone; we appreciate it! :smiley_cat:

**Pull request closed without merging**
