### PR TITLE
hatari 2.4.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
Errno::ENOENT: No such file or directory - etos512k.img

**Comment by Porkepix** [comment]
> ```
> Errno::ENOENT: No such file or directory - etos512k.img
> ```

Well it now seems like it offer several `.img` files, because it gives choice for a localized one. Should Homebrew pick blindly English (US? UK?) or offer a choice for those localizations (if so, I don't know how).

Here are the different localizations:
```
etos512cz.img  etos512de.img  etos512es.img  etos512fi.img  etos512fr.img  etos512gr.img  etos512hu.img  etos512it.img  etos512nl.img  etos512no.img  etos512pl.img  etos512ru.img  etos512se.img  etos512sg.img  etos512tr.img  etos512uk.img  etos512us.img
```

**Comment by czietz** [comment]
Short introduction: I'm one of the main [EmuTOS](https://emutos.sourceforge.io/) developers. 

As @Porkepix found out, EmuTOS 1.1 and above has localized 512k ROMs images. If you want to keep distributing a multi-language ROM image like before, EmuTOS now has a 1024k ROM, which is supported by Hatari 2.4. This is the way the Hatari maintainers went for their Windows binary release, for example.

**Comment by chenrui333** [comment]
> Short introduction: I'm one of the main [EmuTOS](https://emutos.sourceforge.io/) developers.
> 
> As @Porkepix found out, EmuTOS 1.1 and above has localized 512k ROMs images. If you want to keep distributing a multi-language ROM image like before, EmuTOS now has a 1024k ROM, which is supported by Hatari 2.4. This is the way the Hatari maintainers went for their Windows binary release, for example.

Thanks for the direction, I will just go head using `etos1024k.img` then. Also feel free to file a PR to keep this up to date.

**Comment by cho-m** [comment]
I think we can drop `portaudio` dependency?

No linkage and `doc/changelog.txt` mentions:
```
2022-01-08 Thomas Huth

        Replace PortAudio microphone code with SDL2 audio input

        SDL2 supports microphones / audio input, too. Since we've got rid of 
        SDL1.2 recently, we don't need the PortAudio code anymore and simply 
        can use SDL2 instead.
```

**Comment by chenrui333** [comment]
> I think we can drop `portaudio` dependency?
> 
> No linkage and `doc/changelog.txt` mentions:
> 
> ```
> 2022-01-08 Thomas Huth
> 
>         Replace PortAudio microphone code with SDL2 audio input
> 
>         SDL2 supports microphones / audio input, too. Since we've got rid of 
>         SDL1.2 recently, we don't need the PortAudio code anymore and simply 
>         can use SDL2 instead.
> ```
> 
> Corresponding commit: https://git.tuxfamily.org/hatari/hatari.git/commit/?id=38accc16310038cb80de714e3d4110e61ccc2c30

make sense 👍

**Review by branchv — APPROVED** [review]

**Pull request closed without merging**
