### PR TITLE
cilium-cli 0.15.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not the latest release yet: https://github.com/cilium/cilium-cli/releases

**Comment by chenrui333** [comment]
draft release, https://github.com/cilium/cilium-cli/actions/runs/5871828729/job/15922095918

**Comment by samford** [comment]
There's now a 0.15.6 release (as of yesterday) and it's currently marked "latest".

**Comment by chenrui333** [comment]
> There's now a 0.15.6 release (as of yesterday) and it's currently marked "latest".

I must have seen the cached page 😢

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
