### PR TITLE
mandown 1.0.2

### PR DESCRIPTION
**Pull request by Titor8115**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR. It looks like the rest of the formula needs to be updated:
```
==> make install PREFIX=/usr/local/Cellar/mandown/1.0.2
  MKDIR build/*.d
make: *** build/*.d: Is a directory.  Stop.
```

**Comment by Titor8115** [comment]
What do you mean by `MKDIR build/*.d`?

**Comment by carlocab** [comment]
I don't know; that's just the error from running `make install`.

**Comment by carlocab** [comment]
If I try to run this locally:
```
❯ curl -L https://github.com/Titor8115/mandown/archive/v1.0.2.tar.gz | tar -x
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125  100   125    0     0   1315      0 --:--:-- --:--:-- --:--:--  1315
100 78956  100 78956    0     0   221k      0 --:--:-- --:--:-- --:--:-- 1676k
❯ make -C mandown-1.0.2
  MKDIR build/*.d
make: *** build/*.d: Is a directory.  Stop.
```
So I guess there's an issue with the `Makefile`.

**Comment by Titor8115** [comment]
@carlocab I think I found bug. The newest tar.gz should be ready now.
Thanks!

**Comment by carlocab** [comment]
Did you push any changes to your repo? I don't see any...

**Comment by Titor8115** [comment]
Yeah it has the newest version of Makefile. It's kind of weird that even the old Makefile runs just fine on my system... The only thing I can think of is ncursesw isn't recognized by every distro. Below is the new Makefile run result.
```
make -C mandown
make: Entering directory '/home/titor/mandown'
  MKDIR build/blender/
  CC    blender/blender.c
  CC    blender/houdini_blender_e.c
  CC    blender/houdini_href_e.c
  MKDIR build/parser/
  CC    parser/autolink.c
  CC    parser/buffer.c
  CC    parser/markdown.c
  CC    parser/stack.c
  MKDIR build/src/
  CC    src/dom.c
  CC    src/mandown.c
  CC    src/view.c
  LD    mdn
make: Leaving directory '/home/titor/mandown'
```

**Comment by carlocab** [comment]
I don't think the new `Makefile` is in your repo? This is the last commit that modifies your `Makefile`: https://github.com/Titor8115/mandown/commit/5b1bbabe491544dc232d8c098f4c9b99fca09df6

**Comment by Titor8115** [comment]
I just  commit another one. The last commit should've been f5cc50c.
Below is the newest one.
https://github.com/Titor8115/mandown/commit/06028da6a4331aae40c2e3895488f25118d3a3da

**Comment by carlocab** [comment]
Tried cloning your repo then running `make`; still the same error:
```
❯ make
  MKDIR build/*.d
make: *** build/*.d: Is a directory.  Stop.
```

**Comment by Titor8115** [comment]
Alright... I'm looking into it.

Sorry for troubling you this much.

**Pull request closed without merging**
