### PR TITLE
operator-sdk: simplify install, improve tests, bump revision

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The bottled version doesn't seem to be working properly with go1.12.8.

However, bumping the revision fixes it, and I also rewrote some tests that should verify that the formula doesn't break. Also simplified the build steps.

### CODE REVIEW

**Comment by cblecker** [comment]
@SMillerDev sorry for the direct ping.. is it possible to get feedback on these changes? Thank you!

**Comment by SMillerDev** [comment]
Just remove the version check completely. Otherwise it's good to go.

**Comment by SMillerDev** [comment]
Other formula generally have this to have any test at all. I don't think I've ever seen it indicate an actual problem with a formula. Having a test that runs a much used part of a program is a much better, and preferred, option.

**Comment by SMillerDev** [comment]
Thanks @cblecker

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Pull request closed without merging**
