### PR TITLE
vfuse 2.2.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

previous failed attempt, https://github.com/Homebrew/homebrew-core/pull/49331

### CODE REVIEW

**Comment by issyl0** [comment]
```
==> brew test --verbose vfuse
==> FAILED
Testing vfuse
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200510-10086-1namqwk.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vfuse.rb --verbose
==> /usr/local/Cellar/vfuse/2.2.6/bin/vfuse --version
Error: vfuse: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </2\.2\.6/> was expected to be =~
<"2.2.5\n">.
```

Looks like they didn't update the version string in the actual code itself.

**Comment by chenrui333** [comment]
version test sometimes did catch something :)

**Comment by chenrui333** [comment]
let's try the latest release to see how it goes.

**Comment by chenrui333** [comment]
Alright, 3.0.0 is prerelease, waiting for upstream to see how to proceed (it does pass the test this time)

**Pull request merged**
