### PR TITLE
sile 0.10.3

### PR DESCRIPTION
**Pull request by alerque**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alerque** [comment]
See upstream [release checklist](https://github.com/sile-typesetter/sile/issues/817) and [issue about git HEAD builds needing history](https://github.com/sile-typesetter/sile/issues/807).

**Comment by alerque** [comment]
@simoncozens I attempted a fix here for the Lua path issue. I think the wrapper script should now just prepend its own paths instead of completely clobbering what Lua would otherwise have had. I am completely unable to test this though so I'm leaving the PR in draft mode for now until there is some confirmation that it works.

**Comment by alerque** [comment]
If this works, another thing to try and simplify (and avoid the Lua invocations) is this:

```patch
diff --git a/Formula/sile.rb b/Formula/sile.rb
index 3909af5e6b..90501c13ce 100644
--- a/Formula/sile.rb
+++ b/Formula/sile.rb
@@ -139,8 +139,8 @@ class Sile < Formula
     (libexec/"bin").install bin/"sile"
     (bin/"sile").write <<~EOS
       #!/bin/bash
-      export LUA_PATH="#{ENV["LUA_PATH"]};$(lua -e 'print(package.path)')"
-      export LUA_CPATH="#{ENV["LUA_CPATH"]};$(lua -e 'print(package.cpath)')"
+      export LUA_PATH="#{ENV["LUA_PATH"]};;"
+      export LUA_CPATH="#{ENV["LUA_CPATH"]};;"
       "#{libexec}/bin/sile" "$@"
     EOS
   end
```

The double `;;` should be a shortcut to tell Lua to add it's default paths, but I was unsure if that worked from the environment variable or only internally after it was already running.

**Comment by simoncozens** [comment]
PR as written works fine. Checking the suggested patch now.

**Comment by simoncozens** [comment]
Double-semicolon solution also seems to work.

**Comment by alerque** [comment]
@simoncozens Thanks. The double-semicolon trick is less process overhead so we'll go with that.

**Comment by SMillerDev** [comment]
Looks good, can you squash your commits?

**Comment by alerque** [comment]
@SMillerDev Done.

**Comment by alerque** [comment]
It seems like CI got stuck...

**Comment by alerque** [comment]
Hey looks like that worked. If there is a different way to un-jam CI checks that never return I'd be happy to learn.

**Comment by SMillerDev** [comment]
You can ask `brewtestbot` to `test this please`

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @alerque!!

**Pull request closed without merging**
