### PR TITLE
nicotine-plus 3.3.2

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  [02/03/2024 01:44:12] Loading GTK 3.24.41
  [02/03/2024 01:44:12] Loading plugin system
  [02/03/2024 01:44:12] Loaded plugin Nicotine+ Commands
  [02/03/2024 01:44:12] You need to specify a username and password before connecting…
  [02/03/2024 01:44:13] Rebuilding shares…
  [02/03/2024 01:44:13] Rescan complete: 0 folders found
  [02/03/2024 01:44:14] Quitting Nicotine+ 3.3.0, terminating…
  Killing child processes...
  [02/03/2024 01:44:14] Quitting Nicotine+ 3.3.0, terminating…
  [02/03/2024 01:44:14] Quit Nicotine+ 3.3.0!
  Error: nicotine-plus: failed
  An exception occurred within a child process:
    SignalException: SIGTERM
```

**Comment by chenrui333** [comment]
- https://github.com/nicotine-plus/nicotine-plus/issues/2852

```
$ lldb /opt/homebrew/Cellar/nicotine-plus/3.3.0/bin/nicotine
(lldb) target create "/opt/homebrew/Cellar/nicotine-plus/3.3.0/bin/nicotine"
error: '/opt/homebrew/Cellar/nicotine-plus/3.3.0/bin/nicotine' doesn't contain any 'host' platform architectures: arm64, armv7, armv7f, armv7k, armv7s, armv7m, armv7em, armv6m, armv6, armv5, armv4, arm, thumbv7, thumbv7k, thumbv7s, thumbv7f, thumbv7m, thumbv7em, thumbv6m, thumbv6, thumbv5, thumbv4t, thumb, x86_64, x86_64, arm64, arm64e, arm64, arm64e
```

**Comment by slook** [comment]
The log message `Quit Nicotine+ 3.3.0!` is the last line of output that does indicate the program finished executing gracefully, so it doesn't make sence that bre CI fails with a "SIGTERM exception occurred within a child process".

**Comment by mathiascode** [comment]
> * [Failure to launch 3.3.0 on Mac nicotine-plus/nicotine-plus#2852](https://github.com/nicotine-plus/nicotine-plus/issues/2852)
> 
> ```
> $ lldb /opt/homebrew/Cellar/nicotine-plus/3.3.0/bin/nicotine
> (lldb) target create "/opt/homebrew/Cellar/nicotine-plus/3.3.0/bin/nicotine"
> error: '/opt/homebrew/Cellar/nicotine-plus/3.3.0/bin/nicotine' doesn't contain any 'host' platform architectures: arm64, armv7, armv7f, armv7k, armv7s, armv7m, armv7em, armv6m, armv6, armv5, armv4, arm, thumbv7, thumbv7k, thumbv7s, thumbv7f, thumbv7m, thumbv7em, thumbv6m, thumbv6, thumbv5, thumbv4t, thumb, x86_64, x86_64, arm64, arm64e, arm64, arm64e
> ```

`nicotine` is a plain Python script, so this output makes sense.

As for the SIGTERM issue, does Nicotine+ keep running after the last quit log message?

**Comment by mathiascode** [comment]
The test started failing when we started using Python's readline module for CLI:
https://github.com/nicotine-plus/nicotine-plus/blob/cec4c043c5a4d085274761f2a0b74bf664a00c8e/pynicotine/cli.py#L39

I.e. simply importing the readline module will cause the test to fail, presumably because readline starts another process on macOS. I think either the test should be changed, or you could use the tests we provide, which also includes a startup test. You can run them with either `python3 -m unittest` or `pytest`.

**Comment by chenrui333** [comment]
gonna try out this patch, https://github.com/nicotine-plus/nicotine-plus/commit/16b4e56c2f57238961f0332f8d9bc2d5e65f2884

**Comment by chenrui333** [comment]
Just did the head build, still seeing some error:

```
==> Testing nicotine-plus
/opt/homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/n/nicotine-plus.rb
[02/09/24 08:08:25] Loading Python 3.12.1
[02/09/24 08:08:25] Loading Nicotine+ 3.3.1.dev1
[02/09/2024 08:08:26] Loading GTK 3.24.41
[02/09/2024 08:08:27] Loading plugin system
[02/09/2024 08:08:27] Loaded plugin Nicotine+ Commands
[02/09/2024 08:08:27] You need to specify a username and password before connecting…
[02/09/2024 08:08:27] Rebuilding shares…
[02/09/2024 08:08:27] Rescan complete: 0 folders found
2024-02-09 08:08:27.329 Python[32829:81887622] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[02/09/2024 08:08:28] Quitting Nicotine+ 3.3.1.dev1, terminating…
==> Temporary files retained at:
/private/tmp/nicotine-plus-test-20240209-32820-gjnz9m
Killing child processes...
[02/09/2024 08:08:28] Quitting Nicotine+ 3.3.1.dev1, terminating…
[02/09/2024 08:08:28] Quit Nicotine+ 3.3.1.dev1!
Error: nicotine-plus: failed
An exception occurred within a child process:
  SignalException: SIGTERM
```

### how to reproduce
- `brew install --HEAD nicotine-plus`
- `brew edit nicotine-plus`, removing version test line
- `brew test -d -v nicotine-plus`, and you would see the error

**Comment by mathiascode** [comment]
> Just did the head build, still seeing some error:

See my previous comment above.

**Comment by chenrui333** [comment]
It is a bit challenging to run the GUI test, and thus simplifying it to be a version check.

Upstream has a pretty comprehensive test suite checks, like this https://github.com/nicotine-plus/nicotine-plus/actions/runs/8132491915/job/22222983261

**Review by iMichka — APPROVED** [review]

**Pull request merged**
